#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Thu May 23 01:05:40 2024

Found 36 results from 2024-05-16 to 2024-05-23
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Edge-Site Co–Nx Model Single-Atom Catalysts for CO2 Electroreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396916929
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02079")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396916929"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396916929"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396916929"))][Get cited by]]

OpenAlex: https://openalex.org/W4396916929 (Open access: False)
    
[[https://openalex.org/A5040114437][Yao‐Ti Cheng]], [[https://openalex.org/A5084177862][Jianzhao Peng]], [[https://openalex.org/A5015798300][Guozhong Lai]], [[https://openalex.org/A5076162876][Xian Yue]], [[https://openalex.org/A5015547238][Fuzhi Li]], [[https://openalex.org/A5072315367][Qing Wang]], [[https://openalex.org/A5003910460][Lina Chen]], [[https://openalex.org/A5047021453][Junjie Gu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02079 
     
No abstract    

    

* Ethanol Upgrading with N,N,N-Pincer-Based Ru Catalysts: Delineating Key Factors Governing Catalyst Evolution and Stability  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396917420
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Homogeneous Catalysis with Transition Metals, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01361")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396917420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396917420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396917420"))][Get cited by]]

OpenAlex: https://openalex.org/W4396917420 (Open access: False)
    
[[https://openalex.org/A5090229707][Benjamin M. Farris]], [[https://openalex.org/A5024907657][Alex M. Davies]], [[https://openalex.org/A5036992723][Corey R. J. Stephenson]], [[https://openalex.org/A5009251963][Nathaniel K. Szymczak]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01361 
     
No abstract    

    

* Rate-Determining Step for Electrochemical Reduction of Carbon Dioxide into Carbon Monoxide at Silver Electrodes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396917646
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00192")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396917646"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396917646"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396917646"))][Get cited by]]

OpenAlex: https://openalex.org/W4396917646 (Open access: True)
    
[[https://openalex.org/A5073128014][Etienne Boutin]], [[https://openalex.org/A5041466191][Sophia Haussener]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00192  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00192][pdf]])
     
Silver is one of the most studied electrode materials for the electrochemical reduction of carbon dioxide into carbon monoxide, a product with many industrial applications. There is a growing number of reports in which silver is implemented in gas diffusion electrodes as part of a large-scale device to develop commercially relevant technology. Electrochemical models are expected to guide the design and operation toward cost-efficient devices. Despite decades of investigations, there are still uncertainties in the way this reaction should be modeled due to the absence of scientific consensus regarding the reaction mechanism and the nature of the rate-determining step. We review previously reported studies to draw converging conclusions on the value of the Tafel slope and existing species at the electrode surface. We also list conflicting experimental observations and provide leads to tackling these remaining questions.    

    

* Constructing Heteronuclear Bridging Atoms toward Bifunctional Electrocatalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396920380
:TOPICS: Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01705")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396920380"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396920380"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396920380"))][Get cited by]]

OpenAlex: https://openalex.org/W4396920380 (Open access: False)
    
[[https://openalex.org/A5012710067][Minkai Qin]], [[https://openalex.org/A5082391052][Jiadong Chen]], [[https://openalex.org/A5091275109][Menghui Qi]], [[https://openalex.org/A5016829733][H. H. Wang]], [[https://openalex.org/A5017864467][Shanjun Mao]], [[https://openalex.org/A5026863594][Lingling Xi]], [[https://openalex.org/A5030325177][Yong Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01705 
     
No abstract    

    

* Ligand Relay Cobalt Catalysis for Vicinal Si,O-Alkanes from Terminal Alkynes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396921464
:TOPICS: Transition Metal-Catalyzed Cross-Coupling Reactions, Gold Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02438")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396921464"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396921464"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396921464"))][Get cited by]]

OpenAlex: https://openalex.org/W4396921464 (Open access: False)
    
[[https://openalex.org/A5051539737][Yuhan Sun]], [[https://openalex.org/A5044174487][Binghe Wang]], [[https://openalex.org/A5043030267][Linhong Long]], [[https://openalex.org/A5017067065][Jingan Lou]], [[https://openalex.org/A5071043055][Hui Chen]], [[https://openalex.org/A5070489845][Zhan Lu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02438 
     
No abstract    

    

* Modulating Activity and Selectivity of CO2 Electroreductions at Au–Water Interfaces via Engineering Local Cation Condition  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396937858
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00639")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396937858"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396937858"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396937858"))][Get cited by]]

OpenAlex: https://openalex.org/W4396937858 (Open access: True)
    
[[https://openalex.org/A5053758631][Xueping Qin]], [[https://openalex.org/A5083050334][Tejs Vegge]], [[https://openalex.org/A5015539284][Heine Anton Hansen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00639  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00639][pdf]])
     
The mechanistic understanding of the CO2 reduction reaction (CO2RR) under electrochemical conditions is crucial for optimizing the overall catalytic performance. While electrolyte ions have received considerable attention, it remains unclear how the condition of interfacial cations modulates the CO2RR and the competitive hydrogen evolution reaction (HER) at the electrode–electrolyte interfaces. Herein, we explore the CO2 activation and Volmer step representing the critical first electron transfer during the CO2RR and HER, respectively. This investigation involves manipulating the cation identity (K+, Li+, and H+) and concentration at Au–water interfaces, which is carried out via the slow-growth sampling approach integrated with ab initio molecular dynamics simulations. Our results demonstrate that the high local alkali metal cation (AM+) concentration facilitates the CO2RR following the order of 2K+ > 1K+ > 2Li+ > 1Li+ > 0AM+, and the highly promoted CO2 activation kinetics originate from the short-range coordination between alkali metal cations and reaction intermediates. However, the interfacial HER behaves very differently with the kinetic order of 1Li+ > 0AM+ > 1K+ > 2Li+ > 2K+, closely related to the interfacial water structures, which are affected by both cation identity and local concentrations. Overall, the activity and selectivity of the CO2RR at the Au–water interface can be enhanced by increasing the local cation concentration (K+ > Li+). These findings highlight the critical roles of alkali metal cations and reaction microenvironments in modulating interfacial reaction kinetics.    

    

* Controlling the Selectivity of Chlorine Evolution Reaction by IrTaOx/TiO2 Heterojunction Anodes: Mechanism and Real Wastewater Treatment  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396939013
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Photocatalysis and Solar Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06174")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396939013"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396939013"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396939013"))][Get cited by]]

OpenAlex: https://openalex.org/W4396939013 (Open access: False)
    
[[https://openalex.org/A5004568324][Evandi Rahman]], [[https://openalex.org/A5044676126][Jae Sun Shin]], [[https://openalex.org/A5039715599][Sukhwa Hong]], [[https://openalex.org/A5036965622][Sunmi Im]], [[https://openalex.org/A5072751301][Jiseon Kim]], [[https://openalex.org/A5037782178][Chan‐Moon Chung]], [[https://openalex.org/A5020632530][Seok Won Hong]], [[https://openalex.org/A5078307783][Michael R. Hoffmann]], [[https://openalex.org/A5033596181][Kangwoo Cho]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06174 
     
This study investigated the effects of varied loadings of TiO2 overlayers in heterojunction with conventional Ir0.7Ta0.3Ox (IrTaOx) anodes on chlorine evolution reaction (ClER) and real (waste)water treatment at circum-neutral pH. With an optimized design of IrTaOx/TiO2, elevated ClER selectivity was attained by more facile chemisorption of chloride ions to a thin TiO2 layer on IrTaOx. The current efficiency (CE) of ClER in galvanostatic electrolysis of 50 mM NaCl solutions (at 30 mA cm–2) was maximized to ∼80% by a heterojunction architecture with ∼605 μg cm–2 of IrTaOx and ∼265 μg cm–2 of TiO2 after specific rounds of drop casting. Further increases in loading resulted in escalated film-pore resistance or deterioration of ClER selectivity. The observed CE values were correlated with experimental descriptors, such as potential of zero charge and flat band potential, demonstrating that the weaker metal–oxygen bond strength on TiO2 could enhance the ClER selectivity compared to bare IrTaOx. We concluded that ClER primarily occurs on TiO2 near the junction owing to the nanoporous nature of the TiO2 layer, while IrTaOx serves as ohmic contact. The optimized IrTaOx/TiO2 anodes effectively improved the treatment of reverse osmosis concentrate, but phosphate ions in livestock wastewater caused adverse effects due to complexation on TiO2. The heterojunction architecture effectively tunes the surface charge density for selective generation of oxidants, which can facilitate electrochemical water treatment with reduced use of the precious metals.    

    

* Tafel Analysis Predicts Cooperative Redox Enhancement Effects in Thermocatalytic Alcohol Dehydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396952692
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-05-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06103")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396952692"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396952692"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396952692"))][Get cited by]]

OpenAlex: https://openalex.org/W4396952692 (Open access: True)
    
[[https://openalex.org/A5083516753][Bohyeon Kim]], [[https://openalex.org/A5089330812][Isaac H Daniel]], [[https://openalex.org/A5028475580][Mark Douthwaite]], [[https://openalex.org/A5004665220][Samuel Pattisson]], [[https://openalex.org/A5020068159][Graham J. Hutchings]], [[https://openalex.org/A5072550183][Steven McIntosh]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06103  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06103][pdf]])
     
No abstract    

    

* Mixed Potential Driven Self-Cleaning Strategy in Direct Isopropanol Fuel Cells  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396964603
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-05-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01939")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396964603"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396964603"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396964603"))][Get cited by]]

OpenAlex: https://openalex.org/W4396964603 (Open access: False)
    
[[https://openalex.org/A5056591946][Hanjoo Kim]], [[https://openalex.org/A5042130024][Do-Hoon Kim]], [[https://openalex.org/A5077642532][Ji‐Won Son]], [[https://openalex.org/A5090096815][Segeun Jang]], [[https://openalex.org/A5055851063][Dong Young Chung]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01939 
     
No abstract    

    

* Antiover-Reduction of Ni/In2O3 Nanocatalysts by Atomic Layer Deposition of Al2O3 Films for Durable CO2 Hydrogenation to Methanol  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396964972
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02168")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396964972"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396964972"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396964972"))][Get cited by]]

OpenAlex: https://openalex.org/W4396964972 (Open access: False)
    
[[https://openalex.org/A5014412226][Yanmei Cai]], [[https://openalex.org/A5022787977][Cun‐biao Lin]], [[https://openalex.org/A5031403502][Xingwen Cha]], [[https://openalex.org/A5046474017][Yi-Chien Wu]], [[https://openalex.org/A5020301182][Xiaoping Rao]], [[https://openalex.org/A5033936621][Kok Bing Tan]], [[https://openalex.org/A5036032193][Dongren Cai]], [[https://openalex.org/A5034742697][Gui−Lin Zhuang]], [[https://openalex.org/A5007715508][Guowu Zhan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02168 
     
No abstract    

    

* Carbon Support Corrosion in PEMFCs Followed by Identical Location Electron Microscopy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4396978035
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-05-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00417")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396978035"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396978035"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396978035"))][Get cited by]]

OpenAlex: https://openalex.org/W4396978035 (Open access: True)
    
[[https://openalex.org/A5019882034][Linnéa Strandberg]], [[https://openalex.org/A5088693530][Victor Shokhen]], [[https://openalex.org/A5078392737][Magnus Skoglundh]], [[https://openalex.org/A5034924108][Björn Wickman]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00417  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00417][pdf]])
     
Identical location scanning electron microscopy (IL-SEM) and transmission electron microscopy (IL-TEM) are used to follow the degradation of the cathodic catalytic Pt/C electrode layer in a real proton-exchange membrane fuel cell under operation. During an accelerated stress test, mimicking start-up/shutdown conditions, the IL-SEM analysis reveals the formation and growth of cracks in the electrode layer, which expose the underlying membrane, leading to the creation of isolated islands of the electrode layer that tend to delaminate from the membrane. This is found to correlate with a 2- to 4-fold increase of the cell resistance. Nanoscale IL-TEM imaging shows that the diameter of the primary particles of the carbon support shrinks by on average 20%. Consequently, the Pt particles on the support agglomerate and grow by 63% contributing to an observed 65% loss in the electrochemically active surface area. The corrosion of the structural weak points of the carbon support leads to structural collapse. This collapse of the porous structure and weakening of connective points within the cathodic catalyst layers coincide with increased cell and mass transport resistance, resulting in large performance losses. While similar effects have been indicated before, the IL microscopy analysis provides a deeper understanding of the underlying mechanisms and the connection between morphological changes and fuel cell performance losses.    

    

* Catalytic Cycle of Type II 4′-Phosphopantetheinyl Transferases  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397001924
:TOPICS: Click Chemistry in Chemical Biology and Drug Development, Neurodegeneration with Brain Iron Accumulation, Nucleotide Metabolism and Enzyme Regulation
:PUBLICATION_DATE: 2024-05-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06249")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397001924"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397001924"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397001924"))][Get cited by]]

OpenAlex: https://openalex.org/W4397001924 (Open access: False)
    
[[https://openalex.org/A5063207020][Sabine Gavalda]], [[https://openalex.org/A5056859995][Alexandre Faille]], [[https://openalex.org/A5098675590][Simone Fioccola]], [[https://openalex.org/A5036917649][Minh Nguyen]], [[https://openalex.org/A5029547202][Coralie Carivenc]], [[https://openalex.org/A5088900876][Karine Rottier]], [[https://openalex.org/A5098675591][Yann Rufin]], [[https://openalex.org/A5066654323][Stéphane Saitta]], [[https://openalex.org/A5050011825][Georges Czaplicki]], [[https://openalex.org/A5064626955][Christophe Guilhot]], [[https://openalex.org/A5024629125][Christian Chalut]], [[https://openalex.org/A5040690121][Mihaela Brut]], [[https://openalex.org/A5069188437][Lionel Mourey]], [[https://openalex.org/A5060559234][J.D. Pédelacq]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06249 
     
No abstract    

    

* Impact of Carbon Corrosion and Denitrogenation on the Deactivation of Fe–N–C Catalysts in Alkaline Media  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397002376
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-05-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01219")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397002376"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397002376"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397002376"))][Get cited by]]

OpenAlex: https://openalex.org/W4397002376 (Open access: True)
    
[[https://openalex.org/A5085147145][Yu-Ping Ku]], [[https://openalex.org/A5046771382][Kavita Kumar]], [[https://openalex.org/A5019937016][Andreas Hutzler]], [[https://openalex.org/A5064302325][Christian Götz]], [[https://openalex.org/A5043951136][Mykhailo Vorokhta]], [[https://openalex.org/A5089413121][Moulay Tahar Sougrati]], [[https://openalex.org/A5020677451][Vicent Lloret]], [[https://openalex.org/A5088338724][Konrad Ehelebe]], [[https://openalex.org/A5053735446][Karl J. J. Mayrhofer]], [[https://openalex.org/A5030090315][Simon Thiele]], [[https://openalex.org/A5093082010][Ivan Khalakhan]], [[https://openalex.org/A5010518851][Thomas Böhm]], [[https://openalex.org/A5015338172][Frédéric Jaouen]], [[https://openalex.org/A5039409285][Ivan Khalakhan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01219  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01219][pdf]])
     
No abstract    

    

* Revisiting Factors Controlling the Electrochemical CO2 Reduction to CO and HCOOH on Transition Metals with Grand Canonical Density Functional Theory Calculations  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397007370
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-05-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00347")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397007370"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397007370"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397007370"))][Get cited by]]

OpenAlex: https://openalex.org/W4397007370 (Open access: False)
    
[[https://openalex.org/A5008734353][Wanghui Zhao]], [[https://openalex.org/A5062351268][Tao Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00347 
     
No abstract    

    

* High Selectivity Reactive Carbon Dioxide Capture over Zeolite Dual-Functional Materials  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397007386
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-05-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01340")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397007386"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397007386"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397007386"))][Get cited by]]

OpenAlex: https://openalex.org/W4397007386 (Open access: False)
    
[[https://openalex.org/A5082248197][James M. Crawford]], [[https://openalex.org/A5021879653][Mathew J. Rasmussen]], [[https://openalex.org/A5064741675][W. Wilson McNeary]], [[https://openalex.org/A5092088100][Sawyer Halingstad]], [[https://openalex.org/A5075313987][Steven C. Hayden]], [[https://openalex.org/A5077547804][Nikita S. Dutta]], [[https://openalex.org/A5037709742][Simon H. Pang]], [[https://openalex.org/A5009505579][Matthew M. Yung]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01340 
     
No abstract    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397009151
:TOPICS: 
:PUBLICATION_DATE: 2024-05-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i010_1802932")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397009151"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397009151"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397009151"))][Get cited by]]

OpenAlex: https://openalex.org/W4397009151 (Open access: False)
    
, ACS catalysis. 14(10)] 2024. https://doi.org/10.1021/csv014i010_1802932 
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397009268
:TOPICS: 
:PUBLICATION_DATE: 2024-05-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i010_1802933")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397009268"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397009268"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397009268"))][Get cited by]]

OpenAlex: https://openalex.org/W4397009268 (Open access: False)
    
, ACS catalysis. 14(10)] 2024. https://doi.org/10.1021/csv014i010_1802933 
     
No abstract    

    

* A Bulky Imidodiphosphorimidate Brønsted Acid Enables Highly Enantioselective Prins-semipinacol Rearrangements  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397012225
:TOPICS: Olefin Metathesis Chemistry, Homogeneous Catalysis with Transition Metals, Asymmetric Catalysis
:PUBLICATION_DATE: 2024-05-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01494")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397012225"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397012225"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397012225"))][Get cited by]]

OpenAlex: https://openalex.org/W4397012225 (Open access: False)
    
[[https://openalex.org/A5078265381][Junshan Lai]], [[https://openalex.org/A5034853042][Jolene P. Reid]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01494 
     
No abstract    

    

* Ligand-Controlled Regioreversed 1,2-Aryl-Aminoalkylation of Alkenes Enabled by Photoredox/Nickel Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397021977
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-05-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01312")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397021977"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397021977"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397021977"))][Get cited by]]

OpenAlex: https://openalex.org/W4397021977 (Open access: False)
    
[[https://openalex.org/A5043225850][Ye Fu]], [[https://openalex.org/A5021408521][Songlin Zheng]], [[https://openalex.org/A5082580932][Yixin Luo]], [[https://openalex.org/A5005068784][Xiaotian Qi]], [[https://openalex.org/A5014969687][Weiming Yuan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01312 
     
A ligand-controlled regioreversed 1,2-arylalkylation of alkenes via photoredox/nickel dual catalysis is reported. In contrast with previous reports on photoredox/nickel-catalyzed 1,2-alkylarylation reactions that initiate from the Giese addition of an alkyl radical to alkene, this three-component conjugate coupling process occurs through nickel-catalyzed aryl radical addition to alkene, thereby leading to a complementary regioselectivity to conventional 1,2-alkylarylation. An ortho-substituted bipyridyl ligand is the key to tune the regioselectivity, which was found to be dictated by the reactivity of alkene-coordinated LnNi(0) complexes that trigger the formation of aryl radicals via halogen-atom transfer (XAT). This regioreversed transformation allows a concise entry to structurally abundant β-amino acid derivatives, including ORL1-receptor antagonists.    

    

* Molecular Insights into the One-Carbon Loss Oxidation of Indole-3-acetic Acid  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397022232
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Platinum-Based Cancer Chemotherapy, Biological Methane Utilization and Metabolism
:PUBLICATION_DATE: 2024-05-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02178")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397022232"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397022232"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397022232"))][Get cited by]]

OpenAlex: https://openalex.org/W4397022232 (Open access: False)
    
[[https://openalex.org/A5078397516][Jing Cheng]], [[https://openalex.org/A5078600953][Nanxi Wang]], [[https://openalex.org/A5040547872][Liang Yu]], [[https://openalex.org/A5017609294][Yu Luo]], [[https://openalex.org/A5018557213][Ao Liu]], [[https://openalex.org/A5042471205][Shuo Tang]], [[https://openalex.org/A5016952077][Jin Xu]], [[https://openalex.org/A5006839839][Yi Shuang Wang]], [[https://openalex.org/A5050731485][Jiapeng Zhu]], [[https://openalex.org/A5028801665][А. А. Лебедев]], [[https://openalex.org/A5006239480][Changlin Tian]], [[https://openalex.org/A5052763946][Ren Xiang Tan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02178 
     
Dye-decolorizing peroxidases (DyPs) represent a unique family of heme peroxidases that exhibit significant biotechnological promise. DyPs resemble classical peroxidases and operate through the peroxidative cycle, but they differ in structure and function and are ubiquitous in bacterial genomes, particularly in gut-associated species. Nonetheless, the metabolic capabilities and physiological roles of DyPs within the intestine remain unexplored. Here, we report the discovery of a Lactobacillus fermentum-derived DyP (LfDyP) with the unexpected property of directly converting indole-3-acetic acid (IAA) into indole-3-aldehyde (IAld) and indole-3-carbinol (I3C). To elucidate the underlying mechanism, protein crystallography, site-directed mutagenesis, electron paramagnetic resonance (EPR), and density functional theory (DFT) calculations were conducted. LfDyP was found to catalyze the one-electron oxidative decarboxylation of IAA to the skatole radical and its resonance via a long-range electron transfer (LRET) mechanism in the presence of O2. This catalysis initiates the IAA catabolic network, which is further formed through the formation of peroxyl radicals, dimerization, and tetraoxide decomposition. In summary, this study demonstrates the (bio)chemical basis for the catabolism of IAA by the intestinal microbiota into multiple indole-based signaling molecules.    

    

* Phosphorization-Induced “Fence Effect” on the Active Hydrogen Species Migration Enables Tunable CO2 Hydrogenation Selectivity  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4397030606
:TOPICS: Ammonia Synthesis and Electrocatalysis, Materials and Methods for Hydrogen Storage, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-05-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00742")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397030606"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397030606"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397030606"))][Get cited by]]

OpenAlex: https://openalex.org/W4397030606 (Open access: False)
    
[[https://openalex.org/A5048629905][Chunpeng Wu]], [[https://openalex.org/A5056408850][Jiahui Shen]], [[https://openalex.org/A5038244618][Xingda An]], [[https://openalex.org/A5004342383][Zhiyi Wu]], [[https://openalex.org/A5043570145][Shuairen Qian]], [[https://openalex.org/A5040303259][Shumin Zhang]], [[https://openalex.org/A5022938018][Zhiqiang Wang]], [[https://openalex.org/A5070736389][Bin Song]], [[https://openalex.org/A5057638808][Yi Cheng]], [[https://openalex.org/A5047133857][Binhang Yan]], [[https://openalex.org/A5036700518][Tsun‐Kong Sham]], [[https://openalex.org/A5060613485][Shun Zhang]], [[https://openalex.org/A5075446655][Chaoran Li]], [[https://openalex.org/A5033303258][Kai Feng]], [[https://openalex.org/A5057537114][Le He]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00742 
     
No abstract    

    

* Optimizing Selectivity in VOx/TiO2 Catalysts for Ammoxidation: Insights from Structure–Performance Relationships  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398130912
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02141")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398130912"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398130912"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398130912"))][Get cited by]]

OpenAlex: https://openalex.org/W4398130912 (Open access: False)
    
[[https://openalex.org/A5068863304][Haojie Yu]], [[https://openalex.org/A5017864467][Shanjun Mao]], [[https://openalex.org/A5014528965][Bing Liu]], [[https://openalex.org/A5016829733][H. H. Wang]], [[https://openalex.org/A5041161037][Zhiyong Xie]], [[https://openalex.org/A5091275109][Menghui Qi]], [[https://openalex.org/A5069636831][Ruqi Gao]], [[https://openalex.org/A5030325177][Yong Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02141 
     
Multicomponent reactions such as ammoxidation are highly desirable for chemical synthesis. The complicated reaction network and catalytic active sites involved, however, make it rather challenging for extensive structure–performance relationship investigations and subsequent rational design of an efficient catalyst. In this work, efficient VOx/TiO2 catalysts with concise components and exquisite structure design demonstrated 95% selectivity at 98% conversion under 2070 h–1 for 3-picoline ammoxidation. After clarifying that the oxidative dehydrogenation process is rate-limiting, we assumed that the abundance of reactive surface lattice oxygen at the interface of vanadium–titanium is the key to high productivity and suppression of oxidation side reactions since low reaction temperature is beneficial for enlarging the difference in rates of different energy barriers. In addition, rather than applying the traditional neutralization method with alkaline components, in situ formed V2O5 crystallite was subtly to cover the strong acid sites on VOx/TiO2 catalysts in that the strong adsorption of pyridine nitrogen in 3-cyanopyridine on strong acid sites can lead to severe hydrolysis side reactions.    

    

* Non-Oxidative Propane Dehydrogenation by a Well-Defined Ga Catalyst Prepared by Surface Organometallic Chemistry  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398135666
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01118")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398135666"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398135666"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398135666"))][Get cited by]]

OpenAlex: https://openalex.org/W4398135666 (Open access: False)
    
[[https://openalex.org/A5001329661][Jessy Abou Nakad]], [[https://openalex.org/A5019349020][Kaï C. Szeto]], [[https://openalex.org/A5024002693][Aimery De Mallmann]], [[https://openalex.org/A5023777772][Li Li]], [[https://openalex.org/A5029871622][Susannah L. Scott]], [[https://openalex.org/A5042769927][Laurent Delevoye]], [[https://openalex.org/A5069074061][Régis M. Gauvin]], [[https://openalex.org/A5032643129][Mostafa Taoufik]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01118 
     
Ga ions dispersed on alumina catalyze propane dehydrogenation (PDH). Their reactivity has been attributed to the presence of isolated Ga sites, while aggregation to GaOx oligomers and reduction to GaI are reported to be responsible for catalyst deactivation. In this study, we present the preparation and characterization of a highly active and stable single-site catalyst for propane dehydrogenation, consisting of fully dispersed GaIII ions on γ-alumina. The catalyst was synthesized using a surface organometallic chemistry route. Grafting [Ga(OtBu)3]2 onto Al2O3–500 results in the formation of monopodal [(AlsO)Ga(OtBu)2] (I). The controlled thermal treatment of (I) at 300 °C removes the alkoxide ligands and converts (I) into tetracoordinated [(AlsO)3Ga(AlsO-X), X = Als or H] (II). The structures of the intermediate species (I) and the active species (II) were confirmed through elemental analysis, diffuse reflectance infrared Fourier transform spectroscopy (DRIFTS), solid-state NMR, and X-ray absorption spectroscopy (XAS). Material (II) was tested in PDH at 540 °C and exhibited high activity and stability compared to its silica-supported counterpart [(≡SiO)3Ga], suggesting that the isolated nature and robust attachment of (II) onto γ-alumina limit its deactivation.    

    

* Identifying the Active Phase on Atomically Dispersed Catalysts for Propane Dehydrogenation: Positively Charged vs Metallic Transition Metals  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398139287
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-05-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01372")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398139287"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398139287"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398139287"))][Get cited by]]

OpenAlex: https://openalex.org/W4398139287 (Open access: False)
    
[[https://openalex.org/A5052776807][Ping Hu]], [[https://openalex.org/A5068442915][Ming Lei]], [[https://openalex.org/A5067153584][Zhi‐Jun Sui]], [[https://openalex.org/A5042349571][Xinggui Zhou]], [[https://openalex.org/A5025506719][De Chen]], [[https://openalex.org/A5085673398][Yi‐An Zhu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01372 
     
Atomically dispersed transition-metal catalysts have received increasing research interest in heterogeneous catalysis. However, the nature of the real active phase, specifically how the oxidation state of active species may affect the catalytic performance, remains elusive. In this work, ab initio molecular dynamics and large-scale molecular dynamics simulations based on neural network potentials have been employed to assess the structural stability of 52 single- and dual-atom catalysts with transition metals including Mn–Cu, Ru–Ag, and Os–Au embedded in the metal or oxygen vacancies on the defective TiO2 surface. On the thermodynamically stable surfaces, microkinetic analysis combined with results from DFT calculations indicates the metal atoms stabilized in the Ti vacancies with a positive oxidation state generally promote propane dehydrogenation (PDH) with the assistance of adjacent O sites, whereas those in the O vacancies exhibiting metallic properties act as a sole active site for C–H bond activation. The scaling relations established show that the adsorption energies of H and H&H can be used as two simple but effective PDH activity descriptors across both positively charged and metallic metal-doped surfaces. The calculated TOF under the realistic experimental conditions reaches a maximum at a slightly negative oxidation state, implying the Pt and Ir in the metallic state would dominate the kinetics of PDH. Moreover, a high selectivity toward propylene may be attained because the scaling relation between the activation energies for the C–H bond breaking in propane and propylene is broken in the absence of multiple metallic metal–metal sites on the atomically dispersed catalysts. An understanding of this structure–activity relationship is of vital importance for the rational design and optimization of heterogeneous catalysts for light alkane dehydrogenation.    

    

* Precisely Designed Nitrogen-Doped Mesoporous Carbon Sphere-Confined Electron-Deficient Pd Nanoclusters with Enhanced Catalytic Hydrogenation Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398139306
:TOPICS: Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02348")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398139306"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398139306"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398139306"))][Get cited by]]

OpenAlex: https://openalex.org/W4398139306 (Open access: False)
    
[[https://openalex.org/A5035380029][Huacheng Zhao]], [[https://openalex.org/A5005792080][Chuang Liu]], [[https://openalex.org/A5042284357][Yuanzhou Zheng]], [[https://openalex.org/A5031292351][Shuwen Li]], [[https://openalex.org/A5033375004][Yan Gao]], [[https://openalex.org/A5076293642][Qing Ma]], [[https://openalex.org/A5045789022][Fushan Wang]], [[https://openalex.org/A5087289556][Zhengping Dong]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02348 
     
The controlled fabrication of metal nanocluster-based catalysts with high catalytic performance and stability is currently a research hotspot, while it is still a research challenge. Herein, nitrogen-doped mesoporous carbon spheres (CS-N) with a regular and open structure were precisely designed and prepared. Pd nanoclusters with an average size of 1.44 nm were highly dispersed and stably confined in the radial mesoporous structure of CS-N, forming Pd/CS-N catalysts. The obtained Pd/CS-N catalysts showed high catalytic performance in the hydrogenation of phenol to cyclohexanone and hydrogenation of benzoic acid to cyclohexanecarboxylic acid (yield of almost 99%) under mild reaction conditions, outperforming most reported Pd nanoparticle-based catalysts. Theoretical calculation illustrates that the Pd nanocluster exists as an electron-deficient state on Pd/CS-N, thus can efficiently facilitate reactant preadsorption and activation, and also reduce the Gibbs free energy of the rate-determining step of the hydrogenation reactions. Moreover, the Pd/CS-N catalyst exhibited good reusability and stability. Thus, this work will promote the precise construction of stable metal nanocluster-based catalysts, enabling highly efficient catalytic hydrogenation reactions.    

    

* Supported Organochromium Ethylene Oligomerization Enabled by Surface Lithiation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398142351
:TOPICS: Lithium-ion Battery Technology, Battery Recycling and Rare Earth Recovery, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01672")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398142351"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398142351"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398142351"))][Get cited by]]

OpenAlex: https://openalex.org/W4398142351 (Open access: False)
    
[[https://openalex.org/A5001821736][Uddhav Kanbur]], [[https://openalex.org/A5034027190][Jacklyn N. Hall]], [[https://openalex.org/A5027042391][Yu Lim Kim]], [[https://openalex.org/A5040522837][Jens Niklas]], [[https://openalex.org/A5014669390][Oleg G. Poluektov]], [[https://openalex.org/A5060587255][Cong Liu]], [[https://openalex.org/A5010945358][A. Jeremy Kropf]], [[https://openalex.org/A5054572356][Massimiliano Delferro]], [[https://openalex.org/A5024573620][David M. Kaphan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01672 
     
In this work, supported organochromium ethylene polymerization catalysts have been tuned to mediate ethylene oligomerization via surface lithiation, which provides a generalizable protocol to control stereoelectronics and redox states of surface organometallic active sites. The homoleptic chromium(IV) alkyl complex Cr(CH2SiMe3)4 was grafted on high-surface-area anatase titania (TiO2) nanoparticles as well as on silica to produce Cr/TiO2 and Cr/SiO2, respectively. Treatment of these materials with excess n-butyllithium led to the reduced chromium complexes Cr/LixTiO2 and Cr/Li/SiO2, each of which still retains one hydrocarbyl ligand on chromium. A set of heterogeneous complexes were studied by electron paramagnetic resonance and X-ray absorption spectroscopy, which indicate a reduction in the oxidation state of the major chromium species to CrII upon lithiation. Cr/LixTiO2 converts ethylene to hexenes with a high selectivity (>80%), which was persistent over 10 days at 80 °C, achieving >950 turnovers. The exclusive formation of C4 and C6 olefins, preferring the trimerization product, without a statistical (Flory–Schulz) distribution is characteristic of the oxidative cyclization oligomerization mechanism rather than the traditional Cossee–Arlman mechanism, whereas Cr/Li/SiO2 produced a mixture of trimerization and polymerization products, suggesting site heterogeneity in the silica-based material. On the other hand, the unreduced chromium(IV) materials as well as low lithium-containing Cr/LixTiO2 (x < 0.16) exclusively produced ultrahigh molecular weight polyethylene, determined by differential scanning calorimetry and gel permeation chromatography analysis, likely formed via a linear-insertion mechanism, with a crossover from the polymerization to oligomerization regime observed at ∼16% Li intercalation.    

    

* Photocatalyzed H2-Acceptorless Dehydrogenative Borylation by Using Amine Borane  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398142757
:TOPICS: Frustrated Lewis Pairs Chemistry, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00401")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398142757"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398142757"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398142757"))][Get cited by]]

OpenAlex: https://openalex.org/W4398142757 (Open access: False)
    
[[https://openalex.org/A5035180071][Haowen Jiang]], [[https://openalex.org/A5006124276][Wancong Yu]], [[https://openalex.org/A5035557326][Dong Wang]], [[https://openalex.org/A5012000152][Peng‐Fei Xu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00401 
     
Catalytic dehydrogenative borylation of alkenes is arguably the most straightforward approach for synthesizing alkenyl boronates, as it eliminates the need for alkene or boranes prefunctionalizion. While transition-metal catalysis has conventionally been employed for this transformation, competitive side reactions including hydroborylation, overborylation, and regioisomer formation always exist. In this study, we present a radical approach for catalytic dehydrogenative borylation, which involves the synergistic merger of photoredox/HAT/cobalt catalysis, thereby circumventing the necessity for noble metals, sacrificial hydrogen acceptors, and high temperatures. This method employs stable and cost-effective amine borane reagents as feedstocks, resulting in the sole byproduct of H2. This dehydrogenative borylation methodology facilitates the conversion of a diverse array of functionalized alkenes into valuable organoboron reagents. Furthermore, the late-stage borylation of complex molecules demonstrates high levels of site selectivity.    

    

* Photocatalysis toward Microplastics Conversion: A Critical Review  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398143102
:TOPICS: Microplastic Pollution in Marine and Terrestrial Environments, Global E-Waste Recycling and Management, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01449")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398143102"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398143102"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398143102"))][Get cited by]]

OpenAlex: https://openalex.org/W4398143102 (Open access: False)
    
[[https://openalex.org/A5013790248][Ganghua Zhou]], [[https://openalex.org/A5037489490][Hui Xu]], [[https://openalex.org/A5048706086][Hao Song]], [[https://openalex.org/A5025274259][Jianjian Yi]], [[https://openalex.org/A5086657866][Xiaozhi Wang]], [[https://openalex.org/A5044243872][Zupeng Chen]], [[https://openalex.org/A5007599540][Xingwang Zhu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01449 
     
Microplastics (MPs, particle size < 5 mm) have become increasingly ubiquitous on Earth due to the cleavage and degradation of the heavy use of plastics. MPs have recently been reported to be detected in human blood, alveoli, breast milk, embryos, and other organs, raising concerns about their environmental risks. Photocatalysis has been identified as a potential means for MPs conversion, which utilizes solar energy to stimulate a semiconductor photocatalyst. However, the study of photocatalytic conversion of MPs is still in the incubation period. This review overviews the current state-of-the-art technologies for MPs conversion. Then, the fundamental principles, challenges, analytical techniques, and evaluation indexes of photocatalytic MPs reforming are highlighted. We have systematically summarized the recent advances in the photocatalytic conversion of MPs and identified the key factors influencing photocatalytic performance. Finally, we propose some perspectives for developing efficient photocatalytic systems for reforming MPs. This review will provide a guideline for developing and applying photocatalytic technology for reforming MPs, which will significantly contribute to developing this emerging research field.    

    

* Measuring Adsorbate Profiles in Heterogeneous Catalytic Reactors by Iso-Potential Operando DRIFTS Applied to CO2 Methanation on Ni  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398143495
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00536")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398143495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398143495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398143495"))][Get cited by]]

OpenAlex: https://openalex.org/W4398143495 (Open access: False)
    
[[https://openalex.org/A5098710879][Sebastian Sichert]], [[https://openalex.org/A5060326670][Sarah-Franziska Stahl]], [[https://openalex.org/A5013654589][Oliver Korup]], [[https://openalex.org/A5061718643][Raimund Horn]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00536 
     
The development and improvement of catalytic processes require a detailed understanding of catalyst dynamics, reaction mechanisms, and structure–activity relationships inside catalytic reactors, from the laboratory to production scale. This paper presents the methodology of iso-potential operando DRIFTS for measuring the profiles of surface adsorbates inside catalytic reactors. Iso-potential operando spectroscopy (IPOS) in general and iso-potential operando DRIFTS in particular separate the functionality "catalytic reactor" and "spectroscopic cell" from each other. The catalytic reactor is equipped with a mechanism of spatial sampling and spatial temperature measurement. A small fraction of the reaction mixture is sampled locally in the reactor and transferred continuously into a spectroscopic cell containing a very small amount of the same catalyst as in the reactor. The temperature is set to the same value as is locally measured in the reactor. In this way, the catalyst in the spectroscopic cell is exposed to the same chemical potential as that locally in the catalytic reactor. It is hypothesized that it takes on the same structure, the same surface adsorbates, and shows the same reactivity. IPO DRIFTS is applied to CO2 methanation on Ni/γ-Al2O3 catalysts. Two surface adsorbate species, adsorbed carbonyl (*COads) and adsorbed formate (*HCOOads), are detected. The band intensity of *HCOOads decreases along the catalyst bed with the CO2 concentration in the gas phase, identifying surface formate as a kinetically relevant intermediate. This finding is in line with an associative mechanism where CO2 adsorbs on γ-Al2O3 forming carbonate or bicarbonate, being rapidly hydrogenated to formate. Formate reduction is the rate-determining step, with all subsequent hydrogenation steps to CH4 being fast. The band intensity of *COads does not change, irrespective of position in the catalyst bed. This invariance of *COads can be interpreted in two ways. *COads could be a spectator species that is present at the catalyst surface but not involved in any kinetically relevant reaction channel. Alternatively, *COads could be formed by rapid dissociative adsorption of CO2 at the surface of the Ni nanoparticles with a high adsorption equilibrium constant, leading to an almost constant *COads coverage within the investigated CO2 conversion range. If the rate-determining step in the reaction sequence to CH4 would then occur after the formation of *COads, e.g., *COads → *Cads + *Oads or *COads + *Hads → *HCOads, an almost constant *COads signal would result as well.    

    

* Spin Crossover and Exchange Effects on Oxygen Evolution Reaction Catalyzed by Bimetallic Metal Organic Frameworks  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398145641
:TOPICS: Electrocatalysis for Energy Conversion, Perovskite Solar Cell Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01091")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398145641"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398145641"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398145641"))][Get cited by]]

OpenAlex: https://openalex.org/W4398145641 (Open access: True)
    
[[https://openalex.org/A5067593932][Guangsheng Liu]], [[https://openalex.org/A5029818968][Fajun Xie]], [[https://openalex.org/A5074421390][Xu Cai]], [[https://openalex.org/A5045963921][Jingyun Ye]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01091  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01091][pdf]])
     
Bimetallic metal–organic frameworks (BMOFs) have shown a superior oxygen evolution reaction (OER) performance, attributed to the synergistic effects of dual metal sites. However, the significant role of these dual-metal synergies in the OER is not yet fully understood. In this study, we employed density functional theory to systematically investigate the OER performance of NiAl- and NiFe-based BMOFs by examining all possible spin states of each intermediate across diverse external potentials and pH environments. We found that the spin state featuring a shallow hole trap state and Ni ions with a higher oxidation state serve as strong oxidizing agents, promoting the OER. An external potential-induced spin crossover was observed in each intermediate, resulting in significant changes in the overall reaction and activation energies due to altered energy levels. Combining the constant potential method and the electrochemical nudged elastic band method, we mapped the minimum free energy barriers of the OER under varied external potential and pH by considering the spin crossover effect for both NiAl and NiFe BMOFs. The results showed that NiFe exhibits better OER thermodynamics and kinetics, which is in good agreement with experimentally measured OER polarization curves and Tafel plots. Moreover, we found that the improved OER kinetics of NiFe not only is attributed to lower barriers but also is a result of improved electrical conductivity arising from the synergistic effects of Ni–Fe dual-metal sites. Specifically, replacing the second metal Al with Fe leads to two significant outcomes: a reduction in both the band gap and the effective hole mass compared to NiAl, and the initiation of super- and double-exchange interactions within the Ni–F–Fe chain, thereby enhancing electron transfer and hopping and leading to the improved OER kinetics.    

    

* Selective Electrosynthesis of Ethanol via Asymmetric C–C Coupling in Tandem CO2 Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398159967
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01579")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398159967"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398159967"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398159967"))][Get cited by]]

OpenAlex: https://openalex.org/W4398159967 (Open access: False)
    
[[https://openalex.org/A5074562260][Peng Luan]], [[https://openalex.org/A5002524555][Xue Dong]], [[https://openalex.org/A5025734756][Linqi Liu]], [[https://openalex.org/A5004947752][Jianping Xiao]], [[https://openalex.org/A5066863522][Pengfei Zhang]], [[https://openalex.org/A5000201876][Jie Zhang]], [[https://openalex.org/A5058298755][Haibo Chi]], [[https://openalex.org/A5053863846][Qingnan Wang]], [[https://openalex.org/A5014014148][Chunmei Ding]], [[https://openalex.org/A5080416058][Rengui Li]], [[https://openalex.org/A5085201914][Fengyuan Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01579 
     
Selective electroreduction of CO2 to ethanol has economic value and environmental significance. However, the activity and selectivity of CO2 reduction toward ethanol are still low due to the sluggish kinetics of C–C coupling and the intense competition of hydrocarbon production. Herein, we report a layered tandem catalyst consisting of Cu nanosheets with a Cu(111)-oriented surface and Ag nanoparticles, which can effectively shift the selectivity from hydrocarbons to ethanol. The Faradaic efficiency of ethanol was improved from less than 30% on bare Cu(111) to 56.5 ± 2.6% on the layered Cu/Ag tandem catalysts, with a partial current density of 356.7 ± 9.5 mA cm–2. In situ Raman spectroscopy results and density functional theory calculations suggest that the high selectivity toward ethanol can be attributed to the asymmetric *CH2–CO coupling mechanism, which is facilitated by the selective generation of *CH2 species on (111)-facet-exposed Cu nanosheets and the high local CO concentration supplied by the Ag catalyst.    

    

* Atmosphere-Dependent Strong Metal–Support Interactions in Au/ZnO Catalysts and Their Overlayer Permeability  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398162683
:TOPICS: Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02124")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398162683"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398162683"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398162683"))][Get cited by]]

OpenAlex: https://openalex.org/W4398162683 (Open access: False)
    
[[https://openalex.org/A5009089098][Guandong Wu]], [[https://openalex.org/A5077702921][Yiwei Jiang]], [[https://openalex.org/A5014923511][Yiming Niu]], [[https://openalex.org/A5088842976][Bingsen Zhang]], [[https://openalex.org/A5089015352][Lin Li]], [[https://openalex.org/A5077140649][Guoji Liu]], [[https://openalex.org/A5052932306][Yufei He]], [[https://openalex.org/A5055663516][Junhu Wang]], [[https://openalex.org/A5066904777][Dianqing Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02124 
     
The oxidative strong metal–support interaction (O-SMSI) emerges as a pioneering approach for promoting the formation of overlayers, which has garnered significant interest in the exploration of the synthesis of O-SMSI materials. However, the manipulation of the overlayer is rarely discussed and presents a challenge due to its trace presence on the nanoparticle (NP) surface, which impedes the development and utilization of the O-SMSI. In this work, we demonstrate a strong correlation between the treatment atmosphere and the state of the permeable overlayer in the Au/ZnO catalyst. The ZnO overlayer can be formed in both oxidative and inert atmospheres, but the permeability of the overlayer occurs under an oxidative atmosphere. The difference in the permeabilities of the overlayer, at similar particle sizes, leads to a reaction rate difference of approximately 1.4 times. While the permeability of the ZnO overlayer is improved by an oxidative atmosphere treatment, it is also accompanied by an increase in the geometric strain in the ZnO matrix. The permeable ZnO formation is related to the process of gold species insertion into the ZnO matrix, as indicated by density functional theory calculations. This study is the first to describe the role of O2 in manipulating the O-SMSI and suboxide overlayers, offering a potential method for surface engineering.    

    

* Chemosphere-Inspired Irradiation Reallocation Strategy Based on Mie Theory for Stable CO2 Photoreduction over Cu2O  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398164278
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Zinc Oxide Nanostructures
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05802")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398164278"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398164278"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398164278"))][Get cited by]]

OpenAlex: https://openalex.org/W4398164278 (Open access: False)
    
[[https://openalex.org/A5031675164][Tongyu Wang]], [[https://openalex.org/A5089306036][Kuan Deng]], [[https://openalex.org/A5005264493][Hailing Huo]], [[https://openalex.org/A5057441318][Chelsea X. Huang]], [[https://openalex.org/A5091838363][Yiqin Du]], [[https://openalex.org/A5022631289][Ming-Yuan Yu]], [[https://openalex.org/A5042228449][Jingjing Ma]], [[https://openalex.org/A5048140096][Erjun Kan]], [[https://openalex.org/A5022512191][Ang Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05802 
     
No abstract    

    

* Mechanistic and Kinetic Insights into Intermolecular [2+2] Photocycloadditions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398164282
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01678")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398164282"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398164282"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398164282"))][Get cited by]]

OpenAlex: https://openalex.org/W4398164282 (Open access: False)
    
[[https://openalex.org/A5061326292][Gina Quach]], [[https://openalex.org/A5019894293][Hasti Iranmanesh]], [[https://openalex.org/A5063410577][Ena T. Luis]], [[https://openalex.org/A5048562511][Jason B. Harper]], [[https://openalex.org/A5069934510][Jonathon E. Beves]], [[https://openalex.org/A5057877864][Evan G. Moore]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01678 
     
No abstract    

    

* Enantioselective Synthesis of Cyclopropanes via CuH-Catalyzed Intramolecular Hydroalkylation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398172089
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Homogeneous Catalysis with Transition Metals, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02119")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398172089"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398172089"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398172089"))][Get cited by]]

OpenAlex: https://openalex.org/W4398172089 (Open access: False)
    
[[https://openalex.org/A5014423647][Giovanni Lonardi]], [[https://openalex.org/A5066181785][Santiago Franco]], [[https://openalex.org/A5098732689][Mattia Sartorello]], [[https://openalex.org/A5035489826][Carla De Faveri]], [[https://openalex.org/A5089734852][Mariano Stivanello]], [[https://openalex.org/A5069328269][Giulia Licini]], [[https://openalex.org/A5078857322][Manuel Orlandi]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02119 
     
No abstract    

    

* Synthesis of Chiral Polycyclic Indoles via Pd(II)-Catalyzed Sequential Cyclization and Carbonylation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398176145
:TOPICS: Homogeneous Catalysis with Transition Metals, Transition-Metal-Catalyzed C–H Bond Functionalization, Asymmetric Catalysis
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01325")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398176145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398176145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398176145"))][Get cited by]]

OpenAlex: https://openalex.org/W4398176145 (Open access: False)
    
[[https://openalex.org/A5012324763][Long Chen]], [[https://openalex.org/A5040332516][Hongyou Zhou]], [[https://openalex.org/A5000876494][Yuan Xue]], [[https://openalex.org/A5075372754][Lingyu Kong]], [[https://openalex.org/A5029667848][Yi Wang]], [[https://openalex.org/A5014475523][Xuyao Han]], [[https://openalex.org/A5052874928][Hequan Yao]], [[https://openalex.org/A5011404596][Aijun Lin]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01325 
     
No abstract    

    
