#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Thu Apr  4 00:46:10 2024

Found 25 results from 2024-03-28 to 2024-04-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Keep the Ligands: Potential Benefits for Fuel Cell Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393220540
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-03-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06298")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393220540"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393220540"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393220540"))][Get cited by]]

OpenAlex: https://openalex.org/W4393220540 (Open access: False)
    
[[https://openalex.org/A5021423945][Andrés Molina Villarino]], [[https://openalex.org/A5065755632][Jonathan L. Rowell]], [[https://openalex.org/A5027510746][Dasol Yoon]], [[https://openalex.org/A5062716145][Li Xiao]], [[https://openalex.org/A5061811357][Yunyi Jia]], [[https://openalex.org/A5029671045][Zixiao Shi]], [[https://openalex.org/A5033981532][Joesene Soto]], [[https://openalex.org/A5094257249][Julia Koldobskiy]], [[https://openalex.org/A5042016235][David A. Muller]], [[https://openalex.org/A5013115261][Richard D. Robinson]], [[https://openalex.org/A5042053197][Héctor D. Abruña]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06298 
     
No abstract    

    

* Polystyrene Hydrogenolysis to High-Quality Lubricants Using Ni/SiO2  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393232044
:TOPICS: Additive Manufacturing and 3D Printing Technologies, Biodegradable Polymers as Biomaterials and Packaging, Global E-Waste Recycling and Management
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05900")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393232044"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393232044"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393232044"))][Get cited by]]

OpenAlex: https://openalex.org/W4393232044 (Open access: False)
    
[[https://openalex.org/A5027076305][Brandon C. Vance]], [[https://openalex.org/A5090561307][Sean Najmi]], [[https://openalex.org/A5066110304][Dionisios G. Vlachos]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05900 
     
Pyrolytic and light-activated oxidation processes are leading technologies for utilizing polystyrene (PS) wastes. These approaches exhibit poor selectivities, use complex reactors, and require solvents. Hydrogenolysis is effective for deconstructing polyolefins, but its application to PS feedstocks has been limited. Herein, we demonstrate Ni/SiO2 catalysts to facilitate PS (Mw ≈ 97 kDa) hydrogenolysis to produce lubricant base oils possessing group IV properties, achieving maximum yields of 70% within 6 h at 300 °C and 70 bar of H2. Gas, liquid, and oil product yields are stable across reaction conditions, whereas hydrogenation of the PS aromaticity and reduction of the molecular weight benefit from higher temperatures and H2 pressures. Time-dependent experiments underscore the importance of elevated H2 pressure, revealing that PS hydrogenolysis occurs sequentially, with aromatic ring hydrogenation preceding degradation of the C–C backbone. Kinetic measurements with 1,2-diphenylethane as a probe molecule demonstrate that ring hydrogenation pis 3 orders of magnitude faster than internal C–C bond cleavage over Ni/SiO2. Ni/SiO2 proves to be effective in the hydrogenolysis of heavier PS polymers and rigid commercial PS products. Conversely, flexibility and foam PS feeds result in Ni/SiO2 deactivation, attributed to performance additives. Unlike polyolefins, the process produces very little methane and other light hydrocarbons. These findings expand the applicability of hydrogenolysis to PS feedstocks, offering a versatile solution and broadening the range of high-value products from PS to include lubricant base oils.    

    

* Tailoring Hydrogen Evolution Performance: Size and Phase Engineering of Ruthenium Nanoparticles  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393233907
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00368")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393233907"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393233907"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393233907"))][Get cited by]]

OpenAlex: https://openalex.org/W4393233907 (Open access: False)
    
[[https://openalex.org/A5063987951][Chi-Kai Hung]], [[https://openalex.org/A5013583666][Antony R. Thiruppathi]], [[https://openalex.org/A5058583659][Nicholas Burns]], [[https://openalex.org/A5030598553][Cameron McGuire]], [[https://openalex.org/A5078666039][Jonathan Quintal]], [[https://openalex.org/A5085194936][Dazhi Jiang]], [[https://openalex.org/A5081413879][S. Kycia]], [[https://openalex.org/A5021802673][Aicheng Chen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00368 
     
Ruthenium-based nanomaterials have seen increased interest as an alternative to platinum electrocatalysts for the hydrogen evolution reaction (HER). In this study, ruthenium nanoparticles supported on a graphene-based composite consisting of expanded graphite and reduced graphene oxide were successfully prepared by using a one-step thermal method. The nanocomposite was optimized for alkaline HER performance by varying the expanded graphite content and annealing temperature, exhibiting an overpotential of 54 mV to achieve 10 mA cm–2, outperforming the benchmark 20% Pt/C. Through surface characterization of the nanocomposite, the high electrocatalytic activity and stability were found to originate from the interconnected microstructure, optimized porosity, tuned Ru particle size, and homogeneous particle dispersion, revealing the key roles of each component. Using X-ray absorption and X-ray total scattering techniques, the electrochemical performance of the nanocomposite was found to depend on a balance between the size and quality of the ruthenium nanoparticles. The catalyst design principles demonstrated in this work can be applied to streamline and simplify the processes used to develop advanced HER electrocatalysts and other energy storage and conversion materials.    

    

* Understanding pH-Dependent Oxygen Reduction Reaction on Metal Alloy Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393234212
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00461")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393234212"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393234212"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393234212"))][Get cited by]]

OpenAlex: https://openalex.org/W4393234212 (Open access: False)
    
[[https://openalex.org/A5003725369][Xinnan Mao]], [[https://openalex.org/A5026705378][Lu Wang]], [[https://openalex.org/A5035944985][Youyong Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00461 
     
Exploring low-cost and high-efficiency catalysts for oxygen reduction reaction (ORR) kinetics in both acidic and alkaline environments could dramatically improve the efficiency of hydrogen fuel cells and their industrial applications. During the electrochemical process, the effect of pH is a complicating factor and is of great importance in identifying high-efficiency electrocatalysts. In this work, we conducted systematic computations to gain a deep understanding of the pH-dependent ORR activity on Pt, Pd, and their near-surface alloys (NSAs). The effects of pH were calculated by employing the double-reference method, and our calculated pH-dependent current densities are in good agreement with the experimental results. High-throughput calculations identified a series of NSA catalysts with superior ORR performance under acidic or alkaline conditions, and we have developed a pH-corrected theoretical model to efficiently estimate the ORR activity on metal catalysts. This work underscores the importance of considering pH effects when evaluating ORR activity from calculations and provides a strategy for designing superior ORR electrocatalysts in acidic and alkaline solutions.    

    

* Multiscale Investigation of the Mechanism and Selectivity of CO2 Hydrogenation over Rh(111)  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393252805
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Advancements in Density Functional Theory
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05939")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393252805"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393252805"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393252805"))][Get cited by]]

OpenAlex: https://openalex.org/W4393252805 (Open access: True)
    
[[https://openalex.org/A5050790072][Shijia Sun]], [[https://openalex.org/A5074429295][Michael Higham]], [[https://openalex.org/A5043608187][Xingfan Zhang]], [[https://openalex.org/A5042572313][C. Richard A. Catlow]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05939  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05939][pdf]])
     
No abstract    

    

* Radical 1,2-Nitrogen Migration Cascades of β-Bromo α-Amino Acid Esters to Access β-Amino Acid Motifs Enabled by Cooperative Ni/Diboron Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393255866
:TOPICS: Peptide Synthesis and Drug Discovery, Frustrated Lewis Pairs Chemistry, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01034")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393255866"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393255866"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393255866"))][Get cited by]]

OpenAlex: https://openalex.org/W4393255866 (Open access: False)
    
[[https://openalex.org/A5054433332][Yeonchul Hong]], [[https://openalex.org/A5002633843][Zi-Cheng Liao]], [[https://openalex.org/A5030945438][Jiajie Chen]], [[https://openalex.org/A5060564864][Jian Liu]], [[https://openalex.org/A5037263864][Yin-Ling Liu]], [[https://openalex.org/A5035738103][Jin‐Heng Li]], [[https://openalex.org/A5011249790][Qing Sun]], [[https://openalex.org/A5083328254][Shi‐Lu Chen]], [[https://openalex.org/A5017209279][Shuo‐Wen Wang]], [[https://openalex.org/A5044494605][Shi Tang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01034 
     
Amino acid esters serve as crucial intermediates in protein synthesis and as common structural elements in biologically active natural compounds. Herein, we present an efficient radical cascade reaction involving 1,2-nitrogen migration and C(sp2)–H intramolecular cyclization, enabling access to a diverse array of β-amino acid motifs. Upon cooperative Ni/diboron catalysis, a π-system-independent 1,2-N-shift of β-bromo α-amino acid esters is achieved, which allows the formation of two new bonds, including a C(sp3)–C(sp2) bond and a C(sp3)–N bond. The cascade reaction exhibits extensive substrate compatibility and high diastereoselectivity and proceeds without the need for oxidants, toxic radical initiators, and/or elevated temperatures. It has been observed that diboron compounds serve as both an activating reagent for inert C–N bond cleavage/migration and a reductant for the Ni catalytic cycle. This sheds light on the radical remote migration of N-functionalities without the need for π-systems. The radical cascades involving a 1,2-N-shift followed by intermolecular halogenation or selenation are also demonstrated.    

    

* Rational Design of Spontaneous Self-Cyclization Enzymes In Vivo and In Vitro with Improved Thermal Tolerance and Activity  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393260657
:TOPICS: Enzyme Immobilization Techniques, Microbial Enzymes and Biotechnological Applications, Technologies for Biofuel Production from Biomass
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00056")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393260657"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393260657"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393260657"))][Get cited by]]

OpenAlex: https://openalex.org/W4393260657 (Open access: False)
    
[[https://openalex.org/A5012589494][Bin Wei]], [[https://openalex.org/A5083214612][Yilin Kang]], [[https://openalex.org/A5019622389][Yuxuan Zhao]], [[https://openalex.org/A5091514700][Haichang Xu]], [[https://openalex.org/A5009620553][Hao Liang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00056 
     
Enzymes have selectivity, require mild catalytic conditions, and are important cornerstones in many industrial catalytic processes. Protein self-cyclization has opened up the possibility of preserving fragile enzymes during long-term high-temperature catalysis. However, the mechanism for self-cyclization and improvement of thermal tolerance have not been elucidated, severely limiting their industrial applications. Herein, we provide a strategy for the rational design of fusion proteins based on structural analysis to obtain cyclized enzymes with improved properties. First, we constructed fusion proteins that preferentially translated SpyCatcher (CBT) or SpyTag (TBC), both of which could form stable single self-cyclization with significantly improved thermal tolerance. Especially, the thermal half-life of TBC obtained by modifying the N-terminal SpyTag at 40 °C was 10.83 times that of wild enzymes. Structural analysis revealed that the terminus of the protein, which preferentially translated to SpyCatcher, folded into a conformation that adversely affected stability. In addition, the structure of the catalytic pocket and the orientation of the catalytic residues of CBT were significantly different from those of the wild-type enzymes, which led to a decrease in the catalytic activity. These conclusions were confirmed when another industrial enzyme, sucrose phosphorylase, was cyclized. Finally, the cyclized glucosidase was also superior to the wild-type strain for the preparation of ginsenoside F1 at high titers and as a whole-cell catalyst for extended use. In conclusion, we demonstrated for the first time that conjugated long oligopeptide SpyCatcher significantly affected the catalytic activity and stability of cyclized enzymes. It was necessary to preferentially translate units with less steric hindrance to reduce their impact on the protein structure. The rational design of cyclized enzymes based on structural analysis provides a simple and effective strategy for the modification of industrial enzymes with poor thermal tolerance, providing considerable prospects for biosynthesis in vivo and in vitro.    

    

* Identification of the Thermal Activation Network in Human 15-Lipoxygenase-2: Divergence from Plant Orthologs and Its Relationship to Hydrogen Tunneling Activation Barriers  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393262678
:TOPICS: Role of Nrf2 Signaling in Oxidative Stress Response, Brown Adipose Tissue Function and Physiology, Structure and Function of G Protein-Coupled Receptors
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00439")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393262678"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393262678"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393262678"))][Get cited by]]

OpenAlex: https://openalex.org/W4393262678 (Open access: False)
    
[[https://openalex.org/A5066641704][Amanda Ohler]], [[https://openalex.org/A5063147447][P. E. Taylor]], [[https://openalex.org/A5094268421][Jasmine A. Bledsoe]], [[https://openalex.org/A5025340342][Anthony T. Iavarone]], [[https://openalex.org/A5044090789][Nathaniel C. Gilbert]], [[https://openalex.org/A5038450160][Adam R. Offenbacher]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00439 
     
The oxidation of polyunsaturated fatty acids by lipoxygenases (LOXs) is initiated by a C–H cleavage step in which the hydrogen atom is transferred quantum mechanically (i.e., via tunneling). In these reactions, protein thermal motions facilitate the conversion of ground-state enzyme–substrate complexes to tunneling-ready configurations and are thus important for transferring energy from the solvent to the active site for the activation of catalysis. In this report, we employed temperature-dependent hydrogen–deuterium exchange mass spectrometry (TDHDX-MS) to identify catalytically linked, thermally activated peptides in a representative animal LOX, human epithelial 15-LOX-2. TDHDX-MS of wild-type 15-LOX-2 was compared to two active site mutations that retain structural stability but have increased activation energies (Ea) of catalysis. The Ea value of one variant, V427L, is implicated to arise from suboptimal substrate positioning by increased active-site side chain rotamer dynamics, as determined by X-ray crystallography and ensemble refinement. The resolved thermal network from the comparative Eas of TDHDX-MS between wild-type and V426A is localized along the front face of the 15-LOX-2 catalytic domain. The network contains a clustering of isoleucine, leucine, and valine side chains within the helical peptides. This thermal network of 15-LOX-2 is different in location, area, and backbone structure compared to a model plant lipoxygenase from soybean that exhibits a low Ea value of catalysis compared to the human ortholog. The presented data provide insights into the divergence of thermally activated protein motions in plant and animal LOXs and their relationships to the enthalpic barriers for facilitating hydrogen tunneling.    

    

* Catalytic Contra-Thermodynamic Isomerization–Asymmetric Hydroboration of Alkenyl Alcohols and Amines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393277873
:TOPICS: Homogeneous Catalysis with Transition Metals, Frustrated Lewis Pairs Chemistry, Asymmetric Catalysis
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06194")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393277873"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393277873"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393277873"))][Get cited by]]

OpenAlex: https://openalex.org/W4393277873 (Open access: False)
    
[[https://openalex.org/A5091963612][Chenchen Li]], [[https://openalex.org/A5013053381][Kezhuo Zhang]], [[https://openalex.org/A5001418981][Wanxiang Zhao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06194 
     
Catalytic isomerization of alkenes is a powerful tool for the construction of complex synthetically valuable molecules due to their redox-neutral, atom- and step-economical nature. However, traditional catalytic asymmetric isomerization of alkenes typically required the use of a heteroatomic group such as OH or NR2 as the thermodynamic driving force (i.e., the C═C double bond isomerizes along the direction of heteroatomic groups). Here, we present a contra-thermodynamic isomerization/asymmetric hydroboration of alkenyl alcohols and amines, in which the C═C double bond isomerizes along the opposite direction of OR and NR2. Compared to the traditional thermal isomerizations, this reaction overcomes the unfavorable thermodynamic bias to form a contra-thermodynamic alkene intermediate, followed by an irreversible asymmetric terminal hydroboration to provide highly synthetically valuable chiral 1,n-boryl ethers and amines. This protocol shows a wide substrate scope, including allylic alcohols, homoallylic alcohols, alkenyl alcohols, protected alkenyl alcohols, and various free and protected alkenyl amines. The synthetic utilities and practicability of this method were demonstrated by gram-scale reactions, diverse product transformations, and its applications in the synthesis of bioactive molecules. Preliminary mechanistic studies show that this reaction involves dissociative alkene isomerization and an asymmetric hydroboration of 1,1-disubstituted alkene intermediates.    

    

* Photocatalyzed Dual Strain Release of [1.1.1]Propellane with Diazo Compounds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393278427
:TOPICS: Role of Porphyrins and Phthalocyanines in Materials Chemistry, Applications of Photoredox Catalysis in Organic Synthesis, Excited-State Proton Transfer Mechanisms and Applications
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00533")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393278427"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393278427"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393278427"))][Get cited by]]

OpenAlex: https://openalex.org/W4393278427 (Open access: False)
    
[[https://openalex.org/A5062751136][Jiahao Hu]], [[https://openalex.org/A5041793664][Xiaobin Yuan]], [[https://openalex.org/A5052569205][Yufei Li]], [[https://openalex.org/A5043094856][Xiaoyu Chen]], [[https://openalex.org/A5072314592][Zaicheng Nie]], [[https://openalex.org/A5091641575][Mong‐Feng Chiou]], [[https://openalex.org/A5068956051][Yajun Li]], [[https://openalex.org/A5020334340][Hongli Bao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00533 
     
In recent years, many methods for the synthesis of bicyclo[1.1.1]pentane (BCP) scaffolds have been successfully established owing to their remarkable potent bioactive properties. These BCP scaffolds are typically derived from the single strain release of [1.1.1]propellane. However, approaches for dual strain release of [1.1.1]propellane remain elusive, despite the potential to create innovative opportunities for useful propellane derivatization. In this report, we present herein an efficient method for photocatalyzed dual strain release of [1.1.1]propellane with diazo compounds. Many diazo compounds, including those derived from natural products, such as (+)-borneol, estrone, vitamin E, L-menthol, metronidazole, and geraniol, can be applied to these transformations. Importantly, this method allows the cleavage and formation of multiple C–C bonds in a photocatalyzed tandem intersystem crossing (ISC)/radical ring-opening/radical–radical recombination process, and the products can be easily transformed into synthetically challenging spiro compounds, such as spiro [2.3] and spiro [3.4] compounds.    

    

* Insight into the Synergistic Effect of the Oxide–Metal Interface on Hot Electron Excitation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393280380
:TOPICS: Atomic Layer Deposition Technology, Emergent Phenomena at Oxide Interfaces, Surface Analysis and Electron Spectroscopy Techniques
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00407")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393280380"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393280380"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393280380"))][Get cited by]]

OpenAlex: https://openalex.org/W4393280380 (Open access: False)
    
[[https://openalex.org/A5035324394][Eunji Lee]], [[https://openalex.org/A5072049895][Beomjoon Jeon]], [[https://openalex.org/A5041196388][Hyuk Soon Choi]], [[https://openalex.org/A5079554524][Jihun Kim]], [[https://openalex.org/A5019593657][Jong-Seok Kim]], [[https://openalex.org/A5052121107][Gyuho Han]], [[https://openalex.org/A5034804943][Kwangjin An]], [[https://openalex.org/A5021028646][Hyun You Kim]], [[https://openalex.org/A5066625153][Jeong Young Park]], [[https://openalex.org/A5034066496][Si Woo Lee]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00407 
     
Formulating a quantitative relationship between the extent of electron transfer at metal–oxide interfaces and catalytic performance aids the rational design of oxide-supported metal catalysts. An effective strategy for monitoring electron transfer at nanoscale interfacial sites is to detect in real time the hot electrons excited when catalytic reactions occur at metal–oxide perimeter sites. Here, based on our in situ techniques for extracting electron transfer as a current signal using a catalytic nanodiode sensor, we observe hot electron excitation at the CeO2/Pt interface during H2 oxidation. By quantitatively analyzing the hot electrons released during the reaction, we identified the optimal concentration of CeO2/Pt interfaces that maximize the catalytic performance of CeO2/Pt. Through a combinatorial study of experiment and theory, we confirm the decisive role of CeO2/Pt interfacial sites in improving the reactivity and electronic excitation.    

    

* Molecular Engineering of Electrocatalytic Nanomaterials for Hydrogen Evolution: The Impact of Structural and Electronic Modifications of Anchoring Linkers on Electrocatalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393305578
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00336")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393305578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393305578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393305578"))][Get cited by]]

OpenAlex: https://openalex.org/W4393305578 (Open access: False)
    
[[https://openalex.org/A5068400290][Andrew J. Bagnall]], [[https://openalex.org/A5092760919][Matthieu Haake]], [[https://openalex.org/A5071474652][Sergi Grau]], [[https://openalex.org/A5025011392][Tatiana Straistari]], [[https://openalex.org/A5008192334][Matthieu Koepf]], [[https://openalex.org/A5008669299][Navid Jameei Moghaddam]], [[https://openalex.org/A5027825269][Carolina Gimbert‐Suriñach]], [[https://openalex.org/A5003571345][Jordi Benet‐Buchholz]], [[https://openalex.org/A5005120127][Antoni Llobet]], [[https://openalex.org/A5009538487][Murielle Chavarot‐Kerlidou]], [[https://openalex.org/A5020577271][Bertrand Reuillard]], [[https://openalex.org/A5047933845][Vincent Artero]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00336 
     
The anticipated shortage of an increasing number of critical elements, especially metals, requires a shift toward molecularly defined materials with low metal loadings. More particularly, surface-anchored molecular catalysts are attractive to prospectively enable cost-effective electrochemical hydrogen evolution. However, the design of ligands integrating specific anchoring unit(s) for the immobilization of molecular catalysts can be challenging and has direct consequences for the intrinsic properties of the grafted complex. In this work, two cobalt tetraazamacrocyclic complexes bearing pyrene anchoring groups at different positions on the macrocyclic ligands were synthesized. The pyrene unit allows for simple immobilization and electrochemical characterization of the two complexes on multi-walled carbon nanotube-based electrodes. Thorough electrochemical and electrocatalytic investigation demonstrates important differences between the two closely related catalysts in terms of catalyst loading, catalytic response, and stability over time, with a significantly higher stability observed at pH 7 than at pH 2.    

    

* Axially Chiral Copper Catalyst for Asymmetric Synthesis of Valuable Diversely Substituted BINOLs  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393308838
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Chiroptical Spectroscopy in Organic Compound Analysis, Aromaticity in Organic Molecules and Materials
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00726")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393308838"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393308838"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393308838"))][Get cited by]]

OpenAlex: https://openalex.org/W4393308838 (Open access: False)
    
[[https://openalex.org/A5086976460][Jun Gao]], [[https://openalex.org/A5080077246][P.L. Wang]], [[https://openalex.org/A5071298608][Ahui Shen]], [[https://openalex.org/A5037358505][Xueyan Yang]], [[https://openalex.org/A5067090172][Shouyi Cen]], [[https://openalex.org/A5022807400][Zhipeng Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00726 
     
Optically pure BINOL (1,1′-bi-2-naphthol) and diversely substituted BINOLs are highly valuable chiral motifs featuring axial chirality widely applied in various fields. Although unsubstituted BINOL is commercially available, the catalytic asymmetric synthesis of optically pure diversely substituted BINOLs is still very challenging. Herein, we report the development of a highly enantioselective dinuclear copper catalyst for oxidative homo- and cross-coupling of a variety of 2-naphthols to provide access to a broad range of highly valuable diversely substituted C2- and C1-symmetric BINOLs in up to 92% yield with high enantioselectivities (up to 99.5:0.5 er).    

    

* How Micropore Topology Influences the Structure and Location of Coke in Zeolite Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393309555
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00025")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393309555"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393309555"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393309555"))][Get cited by]]

OpenAlex: https://openalex.org/W4393309555 (Open access: True)
    
[[https://openalex.org/A5011286202][Przemysław Rzepka]], [[https://openalex.org/A5058790744][Denis Sheptyakov]], [[https://openalex.org/A5055838753][Chao Wang]], [[https://openalex.org/A5054120563][Jeroen A. van Bokhoven]], [[https://openalex.org/A5059144530][Vladimir Paunović]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00025  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00025][pdf]])
     
Zeolite catalysts exhibit microporous structures, akin to the pockets in naturally occurring enzyme catalysts, which enable the confinement of reaction intermediates, thus facilitating chemical transformations. Nonetheless, the micropores also influence the formation of coke species, which is the main source of catalytic activity loss. Unveiling the relationships between the micropore topology and the internal structure and location of deactivating coke compounds is of high relevance for comprehending the deactivation mechanisms. In this study, we used an approach exploiting powder neutron diffraction to assess the location of coke and determine the dominating structures in the topologically distinct ZSM-5 (MFI topology), ZSM-35 (FER), and SSZ-13 (CHA) zeolite catalysts deactivated in industrially relevant methanol-to-hydrocarbon (MTH) conversion. In ZSM-5 and ZSM-35 catalysts, coke resides along the straight 10-membered ring (MR) channels and exhibits the highest concentration in their intersecting regions with sinusoidal 10 MR and straight 8 MR pores, respectively. In the SSZ-13 catalyst, coke is not only located in cages but also protrudes through their 8 MR windows, suggesting the interconnectivity of coke molecules between the large cavities. Notably, the coke-associated signals in the ZSM-5 and ZSM-35 catalysts show a strong planar arrangement that can be fitted by polycyclic and monocyclic arene structures, respectively. These averaged coke structures are consistent with the composition of coke assessed by gas chromatography–mass spectrometry, 13C and two-dimensional 1H double-quantum single-quantum magic-angle spinning nuclear magnetic resonance, and operando diffuse reflectance ultraviolet–visible spectroscopic analysis. The findings evidence that the pore topology directs the confinement and structure of coke, wherein the largest void zones of the micropore space are the most susceptible to coking.    

    

* Choose Your Own Adventure: A Comprehensive Database of Reactions Catalyzed by Cytochrome P450 BM3 Variants  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393311212
:TOPICS: Drug Metabolism and Pharmacogenomics, Homogeneous Catalysis with Transition Metals, Computational Methods in Drug Discovery
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00086")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393311212"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393311212"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393311212"))][Get cited by]]

OpenAlex: https://openalex.org/W4393311212 (Open access: True)
    
[[https://openalex.org/A5064757543][Douglas J. Fansher]], [[https://openalex.org/A5046459245][Jonathan N. Besna]], [[https://openalex.org/A5071852582][Ali Fendri]], [[https://openalex.org/A5024277895][Joelle N. Pelletier]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00086  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00086][pdf]])
     
No abstract    

    

* Harnessing the Synergistic Power of Ce2S3/TiO2 S-Scheme Heterojunctions for Profound C–O Bond Cleavage in Lignin Model Compounds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393316547
:TOPICS: Desulfurization Technologies for Fuels, Photocatalytic Materials for Solar Energy Conversion, Catalytic Valorization of Lignin for Renewable Chemicals
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00297")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393316547"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393316547"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393316547"))][Get cited by]]

OpenAlex: https://openalex.org/W4393316547 (Open access: False)
    
[[https://openalex.org/A5045922800][Hongwu Liao]], [[https://openalex.org/A5003098842][Yanmin Zhou]], [[https://openalex.org/A5017825677][Zhuo Chen]], [[https://openalex.org/A5056411651][Swellam W. Sharshir]], [[https://openalex.org/A5022798909][Sameh M. Osman]], [[https://openalex.org/A5007803202][Chong Wang]], [[https://openalex.org/A5055500155][Meng An]], [[https://openalex.org/A5037509120][Yusuke Yamauchi]], [[https://openalex.org/A5085415818][Yusuke Asakura]], [[https://openalex.org/A5069831567][Zhanhui Yuan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00297 
     
In the context of achieving carbon neutrality, converting lignin-derived molecules into high-value products through photocatalytic technology provides an environmentally friendly pathway. Establishing energy-efficient processes for converting lignin derivatives requires the construction of highly active and selective photocatalysts. However, enhancing the efficiency and selectivity of photocatalysts for lignin degradation poses an ongoing challenge due to discrepancies in the redox potential and the rapid recombination of photogenerated carriers. To address these significant obstacles, we devised an innovative strategy by developing a Ce2S3 nanoparticle-anchored TiO2 nanorod (Ce2S3/TiO2). This advanced photocatalyst with the S-scheme heterojunction, enabling simultaneous control of carrier dynamics and band structure, was used to study the photocatalytic degradation of the lignin model compound 2-phenoxy-1-acetophenone. Moreover, the photocatalyst can cleave the Cβ-O-4 bond selectively to convert the lignin model compound 2-phenoxy-1-acetophenone into phenol and acetophenone under visible-light irradiation. The yields are up to 94 and 80%, respectively, and 94 or 1.4 times greater than those obtained by pure TiO2 or Ce2S3 individually. In addition, our study for the increased activity in Ce2S3/TiO2 based on density functional theory calculations emphasizes the pivotal role of the S-scheme heterojunction generated between Ce2S3 and TiO2. This heterojunction significantly enhances carrier separation efficiency, thereby augmenting the efficacy of the photocatalytic process. The findings furnish valuable insights for developing advanced photocatalytic systems tailored to the efficient depolymerization of Cβ-O-4 bonds in lignin.    

    

* General, Modular Access toward Immobilized Chiral Phosphoric Acid Catalysts and Their Application in Flow Chemistry  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393316637
:TOPICS: Droplet Microfluidics Technology, Homogeneous Catalysis with Transition Metals, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00985")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393316637"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393316637"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393316637"))][Get cited by]]

OpenAlex: https://openalex.org/W4393316637 (Open access: True)
    
[[https://openalex.org/A5078412901][Michael Laue]], [[https://openalex.org/A5078656621][Maximilian Schneider]], [[https://openalex.org/A5035158328][Markus G. Gebauer]], [[https://openalex.org/A5009489291][Winfried Böhlmann]], [[https://openalex.org/A5035784012][Roger Gläser]], [[https://openalex.org/A5005127669][Christoph Schneider]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00985  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00985][pdf]])
     
Chiral phosphoric acids (CPAs) are among the most frequently used organocatalysts, with an ever-increasing number of applications. However, these catalysts are only obtained in a multistep synthesis and are poorly recyclable, which significantly deteriorates their environmental and economic performance. We herein report a conceptually different, general strategy for the direct immobilization of CPAs on a broad scope of solid supports including silica, polystyrene, and aluminum oxide. Solid-state catalysts were obtained in high yields and thoroughly characterized with elemental analysis by inductively coupled plasma-optical emission spectrometry (ICP-OES), nitrogen sorption measurements, thermogravimetric analysis, scanning transmission electron microscopy/energy-dispersive X-ray spectroscopy (STEM/EDX) images, and solid-state NMR spectroscopy. Further, the immobilized catalysts were applied to a variety of synthetically valuable, highly stereoselective transformations under batch and flow conditions including transfer hydrogenations, a Friedländer condensation/transfer hydrogenation sequence, and Mannich reactions under cryogenic flow conditions. Generally, high yields and stereoselectivities were observed along with robust catalyst stability and reusability. After being used for 10 runs under batch conditions, no loss of selectivity or catalytic activity was observed. Under continuous-flow conditions, the heterogeneous system was in operation for 19 h and the high enantioselectivity remained unchanged throughout the entire process. We expect our approach to extend the applicability of CPAs to a higher level, with a focus on flow chemistry and a more environmentally friendly and resource-efficient use of these powerful catalysts.    

    

* Modeling Complex Ligands for High Oxidation State Catalysis: Titanium Hydroamination with Unsymmetrical Ligands  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393316892
:TOPICS: Transition Metal Catalysis, Homogeneous Catalysis with Transition Metals, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05658")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393316892"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393316892"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393316892"))][Get cited by]]

OpenAlex: https://openalex.org/W4393316892 (Open access: True)
    
[[https://openalex.org/A5086536041][Zhilin Hou]], [[https://openalex.org/A5091300507][Rashmi Jena]], [[https://openalex.org/A5011415802][Tanner J. McDaniel]], [[https://openalex.org/A5000702642][Brennan S. Billow]], [[https://openalex.org/A5045654916][Seokjoo Lee]], [[https://openalex.org/A5043497566][Hannah I. Barr]], [[https://openalex.org/A5082247410][Aaron L. Odom]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05658  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05658][pdf]])
     
A method for modeling high oxidation state catalysts is used on precatalysts with unsymmetrical and symmetrical bidentate ligands to get a more detailed understanding of how changes to ancillary ligands affect the hydroamination of alkynes catalyzed by titanium. To model the electronic donor ability, the ligand donor parameter (LDP) was used, and to model the steric effects, percent buried volume (% Vbur) was employed. For the modeling study, 7 previously unpublished unsymmetrical Ti(XX′)(NMe2)2 precatalysts were prepared, where XX′ is a chelating ligand with pyrrolyl/indolyl linkages. The rates of these unsymmetrical and 10 previously reported symmetrical precatalysts were used with the model kobs = a + b(LDP)1 + c(LDP)2 + d(% Vbur)1 + e(% Vbur)2, where a–e were found through least-squares refinement. The model suggests that (1) the two attachment points of the bidentate ligand XX′ are in different environments on the metal (e.g., axial and equatorial in a trigonal bipyramidal or square pyramidal structure), (2) the position of the unsymmetrical ligand on the metal is determined by the electronics of the ligand rather than the sterics, and (3) that one side of the chelating ligand's electronics strongly influences the rate, while the other side's sterics more strongly influences the rate. From these studies, we were able to generate catalysts fitting to this model with rate constants larger than the fastest symmetrical catalyst tested.    

    

* Benzylic C(sp3)–H Functionalization via Copper-Catalyzed [3+3] Radical Cycloaddition  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393317410
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00637")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393317410"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393317410"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393317410"))][Get cited by]]

OpenAlex: https://openalex.org/W4393317410 (Open access: False)
    
[[https://openalex.org/A5082496097][Junsheng Shi]], [[https://openalex.org/A5005759312][Xiong-Jiang Li]], [[https://openalex.org/A5067645447][Shu-Yun Jiang]], [[https://openalex.org/A5011461470][Wei Wu]], [[https://openalex.org/A5066293769][Hai Ren]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00637 
     
The development of benzylic C(sp3)–H functionalization methods for the assembly of benzylic derivatives has been extensively explored in recent years. However, the engagement of benzylic carbon and its adjacent C=C bond as a C3 synthon in the cycloaddition reaction via direct benzylic C–H activation is rare. Herein, we report a copper-catalyzed [3+3] radical cycloaddition reaction through benzylic C–H bond functionalization to construct six-membered cyclohexane-type rings. In this reaction, the 2-benzylic C–H bond of an indole is selectively activated and the indole serves as a C3 synthon that reacts through highly chemoselective intermolecular self-[3+3] and cross-[3+3] cycloaddition pathways. Multiple symmetric and nonsymmetric polycyclic hexahydrocarbazole scaffolds with hexacyclic 6/5/5/6/5/5/6 and pentacyclic 6/5/5/6/5/6 ring systems are synthesized with high efficiency and chemoselectivity using this strategy. Inspired by the unique radical addition pathway of cross-[3+3] cycloaddition, a highly controllable benzylic C–H functionalization for the construction of C3a-alkylated pyrroloindolines was also developed.    

    

* Rare-Earth-Catalyzed Regiodivergent Hydrosilylation of Aryl Alkenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393317760
:TOPICS: Frustrated Lewis Pairs Chemistry, Homogeneous Catalysis with Transition Metals, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05747")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393317760"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393317760"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393317760"))][Get cited by]]

OpenAlex: https://openalex.org/W4393317760 (Open access: False)
    
[[https://openalex.org/A5075128272][Wufeng Chen]], [[https://openalex.org/A5077386687][N. Zhang]], [[https://openalex.org/A5051879914][Zhengqi Chai]], [[https://openalex.org/A5033889166][Junnian Wei]], [[https://openalex.org/A5046378812][Gen Luo]], [[https://openalex.org/A5029642484][Wen‐Xiong Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05747 
     
While transition-metal catalysts have shown the ability to regulate the Markovnikov or anti-Markovnikov regioselective hydrosilylation of aryl alkenes, the selective control of anti-Markovnikov hydrosilylation of aryl alkenes is still a huge challenge in rare-earth catalyst systems. In this study, we report the rare-earth-catalyzed regiodivergent hydrosilylation of aryl alkenes. Specifically, we achieved the highly regioselective anti-Markovnikov hydrosilylation of aryl alkenes with a scandium alkyl complex Cp*AmtBuScCH2SiMe3 (Cp* = pentamethylcyclopentadienyl, AmtBu = tBuNC(Me)NtBu, tBu = t-butyl) as a catalyst. Two key intermediates, e.g., the scandium hydride and scandium phenethyl complex for anti-Markovnikov hydrosilylation, were characterized. Guided by density functional theory (DFT) calculations, we successfully achieved the selective inversion of aryl alkenes in Markovnikov hydrosilylation using a neodymium halide complex [Cp*AmiPrNdCl]2 (AmiPr = iPrNC(Me)NiPr, iPr = isopropyl) with the larger ion radius and reduced steric hindrance in conjunction with LiCH2SiMe3. Interestingly, our study has demonstrated the significant influence of gradually increasing rare-earth ion radii on controlling the increasing Markovnikov selectivity of hydrosilylation reactions, possibly due to the enlargement of the coordination space around rare-earth metal ions. Furthermore, through a comparison of computational and experimental data, we have observed a high level of consistency, reaffirming the potential of using calculations to predict experimental outcomes and providing researchers with valuable insights.    

    

* Regulation of Catalyst Immediate Environment Enables Acidic Electrochemical Benzyl Alcohol Oxidation to Benzaldehyde  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393319141
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00476")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393319141"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393319141"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393319141"))][Get cited by]]

OpenAlex: https://openalex.org/W4393319141 (Open access: True)
    
[[https://openalex.org/A5075812681][G. Shiva Shanker]], [[https://openalex.org/A5086461939][Arnab Ghatak]], [[https://openalex.org/A5005608415][Shahar Binyamin]], [[https://openalex.org/A5094278970][Rotem Balilty]], [[https://openalex.org/A5085963150][Ran Shimoni]], [[https://openalex.org/A5041755694][Itamar Liberman]], [[https://openalex.org/A5014582181][Idan Hod]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00476  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00476][pdf]])
     
Electrocatalytic alcohol oxidation in acid offers a promising alternative to the kinetically sluggish water oxidation reaction toward low-energy H2 generation. However, electrocatalysts driving active and selective acidic alcohol electrochemical transformation are still scarce. In this work, we demonstrate efficient alcohol-to-aldehyde conversion achieved by reticular chemistry-based modification of the catalyst's immediate environment. Specifically, coating a Bi-based electrocatalyst with a thin layer of metal–organic framework (MOF) substantially improves its performance toward benzyl alcohol electro-oxidation to benzaldehyde in a 0.1 M H2SO4 electrolyte. Detailed analysis reveals that the MOF adlayer influences catalysis by increasing the reactivity of surface hydroxides as well as weakening the catalyst-benzaldehyde binding strength. In turn, low-potential (0.65 V) cathodic H2 evolution was obtained through coupling it with anodic benzyl alcohol electro-oxidation. Consequently, the presented approach could be implemented in a wide range of electrocatalytic oxidation reactions for energy-conversion application.    

    

* Enlarging the Three-Phase Boundary to Raise CO2/CH4 Conversions on Exsolved Ni–Fe Alloy Perovskite Catalysts by Minimal Rh Doping  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393319453
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00151")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393319453"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393319453"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393319453"))][Get cited by]]

OpenAlex: https://openalex.org/W4393319453 (Open access: True)
    
[[https://openalex.org/A5006264721][Xueli Yao]], [[https://openalex.org/A5068697796][Qingpeng Cheng]], [[https://openalex.org/A5075558687][Xueqin Bai]], [[https://openalex.org/A5015654220][Bambar Davaasuren]], [[https://openalex.org/A5065521871][Georgian Melinte]], [[https://openalex.org/A5070190889][Natalia Morlanés]], [[https://openalex.org/A5069291762][José Luis Cerrillo]], [[https://openalex.org/A5030367733][Vijay Kumar Velisoju]], [[https://openalex.org/A5053107002][Hend Omar Mohamed]], [[https://openalex.org/A5004116629][Pewee Datoo Kolubah]], [[https://openalex.org/A5065268874][Lirong Zheng]], [[https://openalex.org/A5002349598][Yu Han]], [[https://openalex.org/A5015619826][Osman M. Bakr]], [[https://openalex.org/A5058113997][Jorge Gascón]], [[https://openalex.org/A5011280331][Pedro Castaño]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00151  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00151][pdf]])
     
Exsolved Ni–Fe alloy perovskite catalysts exhibit remarkable coking resistance during C–H and C–O activation. However, metallic utilization is typically incomplete, resulting in relatively low catalytic activity. Herein, we investigated minimal doping with Rh to boost the catalytic activity in the dry reforming of methane by promoting exsolution and enlargement of the three-phase boundary between the alloy, support, and reactants. The Rh influences the formation of the Ni–Fe alloy, as revealed by X-ray diffraction, and promotes the individual and collective CH4 and CO2 conversions, as revealed by packed bed reactor runs, temperature-programmed surface reactions, and in situ infrared spectroscopy. A minimal 0.21 wt % Rh addition enlarges the three-phase boundary while improving oxygen mobility and storage. The oxygen mobility is responsible for promoting CH4 dissociation and dynamic removal of carbon-containing intermediates, such that the catalyst remains stable for over 100 h under both 1 and 14 bar.    

    

* Tuning Strong Metal–Support Interactions via Synergistic Alloying  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393345356
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Accelerating Materials Innovation through Informatics, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-03-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06171")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393345356"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393345356"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393345356"))][Get cited by]]

OpenAlex: https://openalex.org/W4393345356 (Open access: False)
    
[[https://openalex.org/A5050613147][Yunlong Wang]], [[https://openalex.org/A5010949964][Xiaobo Chen]], [[https://openalex.org/A5075446655][Chaoran Li]], [[https://openalex.org/A5086708025][Yaguang Zhu]], [[https://openalex.org/A5012677271][Jing Li]], [[https://openalex.org/A5080482655][Shiyao Shan]], [[https://openalex.org/A5061621593][Adrian Hunt]], [[https://openalex.org/A5053922026][Iradwikanari Waluyo]], [[https://openalex.org/A5070392626][J. Anibal Boscoboinik]], [[https://openalex.org/A5026877218][Chuan‐Jian Zhong]], [[https://openalex.org/A5009173681][Guangwen Zhou]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06171 
     
The encapsulation phenomenon associated with a strong metal–support interactions (SMSI) has been largely restricted to catalyst systems consisting of group VIII metals with high surface energy and reducible transition metal oxide supports with low surface energy. Here, we demonstrate an encapsulation phenomenon that, while sharing morphological similarities with conventional SMSI, follows a distinctive pathway. This is shown by the encapsulation of CuAu nanoparticles (NPs) supported on a highly ordered pyrolytic graphite (HOPG). Through dynamic monitoring of Cu, Au, and Cu50Au50 NPs in an oxidizing atmosphere using ambient-pressure X-ray photoelectron spectroscopy, we show that this spontaneous encapsulation is achieved through the synergistic effect of the alloying elements. Specifically, the surface segregation of Cu promotes dissociative O2 adsorption, leading to the formation of atomic O species, while the subsurface enrichment of Au hinders O incorporation of oxygen into the bulk of CuAu NPs. Consequently, O spillover onto the graphite support occurs, resulting in the oxidation of the HOPG surface into graphitic oxide species. The higher affinity of the graphitic oxide species toward the Cu-segregated surface prompts their migration from the HOPG support to encapsulate the CuAu NPs. These results transcend the conventional SMSI and bear practical implications for the design and development of heterogeneous catalysts, particularly in carbon-supported alloy systems.    

    

* Thermodynamic Equilibrium versus Kinetic Trapping: Thermalization of Cluster Catalyst Ensembles Can Extend Beyond Reaction Time Scales  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393224125
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Advancements in Density Functional Theory
:PUBLICATION_DATE: 2024-03-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06154")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393224125"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393224125"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393224125"))][Get cited by]]

OpenAlex: https://openalex.org/W4393224125 (Open access: False)
    
[[https://openalex.org/A5083349408][Patricia Poths]], [[https://openalex.org/A5088574626][Santiago Vargas]], [[https://openalex.org/A5025258970][Philippe Sautet]], [[https://openalex.org/A5000151397][Anastassia N. Alexandrova]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06154 
     
No abstract    

    

* Tunable Divergent Reactivity of Aziridinium Ylides in the Synthesis of Complex Piperidines and Azetidines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393372078
:TOPICS: Catalytic C-H Amination Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06173")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393372078"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393372078"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393372078"))][Get cited by]]

OpenAlex: https://openalex.org/W4393372078 (Open access: False)
    
[[https://openalex.org/A5063494151][Mahzad Dehghany]], [[https://openalex.org/A5033112655][Giuliana Pavaneli]], [[https://openalex.org/A5093551048][Jacob W. Kailing]], [[https://openalex.org/A5087213395][Olivia M. Duke]], [[https://openalex.org/A5040701048][Ilia A. Guzei]], [[https://openalex.org/A5069102842][Caroline Da Ros Montes D’Oca]], [[https://openalex.org/A5009883474][Israel Fernández]], [[https://openalex.org/A5047518130][Jennifer M. Schomaker]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06173 
     
Nitrogenated heterocycles comprise the cores of a number of synthetically useful compounds, including pharmaceuticals, bioactive natural products, agrochemicals, and other drug-like molecules. The widespread interest in methods to increase the fraction of sp3 carbon atoms (Fsp3) of drug-like scaffolds in a stereocontrolled manner, while enabling explorations of unusual amine chemical space, inspired our efforts to tune the reactivity of aziridinium ylides. A sequential nitrene–carbene transfer of simple allenes leads to divergent product outcomes depending on the nature of the carbene precursor, furnishing products of different ring sizes. In addition, the catalyst control over the ring size via proposed hydrogen-bonding interactions between the catalyst and substrate was explored. Computational studies were employed to gain insight into the major features of substrates and catalysts that influence the tunable reactivity of aziridinium ylide intermediates formed in this chemistry.    

    
