#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Fri Apr 12 01:02:56 2024

Found 21 results from 2024-04-05 to 2024-04-12
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Realizing the 4e–/2e– Pathway Transition of O2 Reduction on Co–N4–C Catalysts by Regulating the Chemical Structures beyond the Second Coordination Shells  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393940834
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-04-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00781")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393940834"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393940834"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393940834"))][Get cited by]]

OpenAlex: https://openalex.org/W4393940834 (Open access: False)
    
[[https://openalex.org/A5091348611][Wang Wang]], [[https://openalex.org/A5038320521][Yunzi Hu]], [[https://openalex.org/A5001120009][Peng Li]], [[https://openalex.org/A5039374096][Yucheng Liu]], [[https://openalex.org/A5034911893][Shengli Chen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00781 
     
The catalytic performance of single-atom catalysts (SACs) is vitally determined by their coordination environments. So far, the catalytic manipulation of SACs has been mainly focused on the first and second nearest coordination structures of the center atoms. We herein demonstrate that the chemical environments beyond the second coordination shells also significantly influence the catalytic behaviors of SACs. Our findings reveal that the presence of graphitic nitrogen can induce a shift of the O2 reduction pathway on CoN4C sites from an energy-conversion favorite 4e– pathway to a H2O2-production desirable 2e– pathway. The remote graphitic N tunes the electronic structure of Co from the lower-spin state to the higher-spin state, as proved by the zero-field cooling (ZFC) temperature-dependent magnetic susceptibility, which weakens the adsorption of O2/*OOH, ultimately enhancing the selectivity toward H2O2. It is further revealed that the catalytic influence of graphitic N may be universally present in other SACs such as FeN4C and MnN4C. Impressively, the graphitic N-doped CoN4C exhibits a high H2O2 Faraday efficiency (82%) in a flow cell, with a remarkable H2O2 yield of 0.096 mmol cm–2 h–1 for 200 h at 0.358 V (vs RHE), which is sufficient for many applications such as the electro-Fenton-like degradation of the malachite green and demonstrated the feasibility of H2O2 electrosynthesis.    

    

* Correction to “Multi-Functionality of Methanol in Sustainable Catalysis: Beyond Methanol Economy”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393969748
:TOPICS: Homogeneous Catalysis with Transition Metals, Engineering of Surface Nanostructures, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01632")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393969748"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393969748"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393969748"))][Get cited by]]

OpenAlex: https://openalex.org/W4393969748 (Open access: True)
    
[[https://openalex.org/A5003799146][G. Sivakumar]], [[https://openalex.org/A5071468998][Rohit Kumar]], [[https://openalex.org/A5013512043][Vinita Yadav]], [[https://openalex.org/A5037088357][Virendra K. Gupta]], [[https://openalex.org/A5025119113][Ekambaram Balaraman]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01632  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01632][pdf]])
     
No abstract    

    

* Catalytic Photoredox Carbobromination of Unactivated Alkenes with α-Bromocarbonyls via the Mechanistically Distinct Radical-Addition Radical-Pairing Pathway  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393974861
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-04-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00955")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393974861"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393974861"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393974861"))][Get cited by]]

OpenAlex: https://openalex.org/W4393974861 (Open access: False)
    
[[https://openalex.org/A5057703848][Himmat Singh]], [[https://openalex.org/A5046833366][Raj Kumar Tak]], [[https://openalex.org/A5014703056][Dhruba P. Poudel]], [[https://openalex.org/A5086361985][Ramesh Giri]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00955 
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393982452
:TOPICS: 
:PUBLICATION_DATE: 2024-04-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i007_1787822")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393982452"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393982452"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393982452"))][Get cited by]]

OpenAlex: https://openalex.org/W4393982452 (Open access: True)
    
, ACS catalysis. 14(7)] 2024. https://doi.org/10.1021/csv014i007_1787822  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i007_1787822][pdf]])
     
No abstract    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393990563
:TOPICS: 
:PUBLICATION_DATE: 2024-04-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i007_1787821")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393990563"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393990563"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393990563"))][Get cited by]]

OpenAlex: https://openalex.org/W4393990563 (Open access: True)
    
, ACS catalysis. 14(7)] 2024. https://doi.org/10.1021/csv014i007_1787821  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i007_1787821][pdf]])
     
No abstract    

    

* Temperature-Dependent Selectivity and Detection of Hidden Carbon Deposition in Methane Oxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393991266
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-04-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00228")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393991266"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393991266"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393991266"))][Get cited by]]

OpenAlex: https://openalex.org/W4393991266 (Open access: True)
    
[[https://openalex.org/A5095090324][Ulrike Küst]], [[https://openalex.org/A5054780272][Weijia Wang]], [[https://openalex.org/A5034196928][Changda Wang]], [[https://openalex.org/A5028247969][Helena E. Hagelin‐Weaver]], [[https://openalex.org/A5035963338][Johan Gustafson]], [[https://openalex.org/A5051598053][Andrey Shavorskiy]], [[https://openalex.org/A5010210029][Jason F. Weaver]], [[https://openalex.org/A5028067161][Jan Knudsen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00228  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00228][pdf]])
     
Reaction products in heterogeneous catalysis can be detected either on the catalyst surface or in the gas phase after desorption. However, if atoms are dissolved in the catalyst bulk, then reaction channels can become hidden. This is the case if the dissolution rate of the deposits is faster than their formation rate. This might lead to the underestimation or even overlooking of reaction channels such as, e.g., carbon deposition during hydrocarbon oxidation reactions, which is problematic as carbon can have a significant influence on the catalytic activity. Here, we demonstrate how such hidden deposition channels can be uncovered by carefully measuring the product formation rates in the local gas phase just above the catalyst surface with time-resolved ambient pressure X-ray photoelectron spectroscopy. As a case study, we investigate methane oxidation on a polycrystalline Pd catalyst in an oxygen-lean environment at a few millibar pressure. By ramping the temperature between 350 and 525 °C, we follow the time evolution of the different reaction pathways. Only in the oxygen mass-transfer limit do we observe CO production, while our data suggests that carbon deposition also happens outside this limit.    

    

* Brønsted Acid-Site Density Controls the Mechanistic Cycle and Product Selectivity in the Methanol-to-Hydrocarbons Reaction in BEA Zeolite  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393995116
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06077")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393995116"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393995116"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393995116"))][Get cited by]]

OpenAlex: https://openalex.org/W4393995116 (Open access: True)
    
[[https://openalex.org/A5035975994][Juan Carlos Navarro de Miguel]], [[https://openalex.org/A5023228106][Sang–Ho Chung]], [[https://openalex.org/A5060433554][Alla Dikhtiarenko]], [[https://openalex.org/A5004701231][Teng Li]], [[https://openalex.org/A5011483166][Javier Patarroyo]], [[https://openalex.org/A5051034025][Javier Ruiz‐Martínez]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06077  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06077][pdf]])
     
In this work, we show that the acid-site density controls the dominant cycle during the methanol-to-hydrocarbons reaction on beta zeolite. Our experimental evidence is based on the study of beta zeolites with very similar diffusional pathways and different aluminum content. High selectivity to propylene was observed for samples with low Brønsted acid-site density, which is a consequence of the promotion of the olefinic cycle. Our results also confirm that the production of ethylene via the olefinic cycle is negligible. In contrast, high ethylene and aromatics are found at a high Brønsted acid-site density, highlighting the predominancy of the aromatic cycle. Operando UV–vis data show that monoenylic carbocationic species predominate on the olefinic cycle, whereas the aromatic cycle is dominated by polyalkylated monoaromatics. Analysis of the spectroscopy data also shows a linear correlation of the formation of polyaromatic species with the Brønsted acid-site density.    

    

* Rh(III)-Catalyzed Atroposelective C–H Selenylation of 1-Aryl Isoquinolines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393998487
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Toxicology and Pharmacology of Organoselenium Compounds, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01082")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393998487"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393998487"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393998487"))][Get cited by]]

OpenAlex: https://openalex.org/W4393998487 (Open access: False)
    
[[https://openalex.org/A5020216890][Dong‐Song Zheng]], [[https://openalex.org/A5013298161][Pei‐Pei Xie]], [[https://openalex.org/A5065611087][Fangnuo Zhao]], [[https://openalex.org/A5064536916][Chao Zheng]], [[https://openalex.org/A5051425300][Qianqun Gu]], [[https://openalex.org/A5019588728][Shu‐Li You]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01082 
     
Rhodium(III)-catalyzed atroposelective C–H selenylation of 1-aryl isoquinolines has been achieved. The direct C–H selenylation reaction between 1-aryl isoquinolines and 2-(phenylselanyl)isoindoline-1,3-dione in the presence of the chiral SCpRh(III) complex afforded a series of axially chiral 1-aryl isoquinoline selenides in up to 95% yield and 96% ee. The reaction features mild conditions and a broad substrate scope. DFT calculations revealed that the C–Se bond formation step proceeds through a formal SN2 pathway.    

    

* Regio- and Diastereoselective Synthesis of E-Allylic Amines through Hydroalkylation of Terminal Alkynes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394014260
:TOPICS: Asymmetric Catalysis, Homogeneous Catalysis with Transition Metals, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00853")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394014260"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394014260"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394014260"))][Get cited by]]

OpenAlex: https://openalex.org/W4394014260 (Open access: False)
    
[[https://openalex.org/A5052221681][Bofei Wang]], [[https://openalex.org/A5042228437][Avijit Hazra]], [[https://openalex.org/A5090439522][Gojko Lalić]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00853 
     
Allylic amines make up an important class of organic compounds that have inspired the development of numerous methods for their synthesis. One of the most effective transformations involves the coupling of internal alkynes with appropriate nitrogen-containing electrophiles in the presence of a transition metal catalyst. We have developed a method that allows transformation of terminal alkynes into allylic amines through a copper-catalyzed reductive cross coupling with α-chloro phthalimides. The method has a broad substrate scope and results in the highly selective formation of the E-isomer of the anti-Markovnikov hydroamination product. A preliminary mechanistic study supports a mechanism that involves the hydrocupration of the alkyne and the formation of a solvent-caged radical pair.    

    

* Assessment of the Reaction Location of Skeletal 1-Butene Isomerization over Ferrierite  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394566285
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Dehydrogenation of Light Alkanes, Characterization and Behavior of Nuclear Graphite Materials
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00786")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394566285"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394566285"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394566285"))][Get cited by]]

OpenAlex: https://openalex.org/W4394566285 (Open access: True)
    
[[https://openalex.org/A5093007599][Pawel A. Chmielniak]], [[https://openalex.org/A5025006045][Karoline L. Hebisch]], [[https://openalex.org/A5035794316][Urim Pearl Kim]], [[https://openalex.org/A5069105128][Jeffrey Kenvin]], [[https://openalex.org/A5088976109][Carsten Sievers]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00786  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00786][pdf]])
     
No abstract    

    

* Oxidative Redispersion-Derived Single-Site Ru/CeO2 Catalysts with Mobile Ru Complexes Trapped by Surface Hydroxyls Instead of Oxygen Vacancies  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394566556
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01230")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394566556"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394566556"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394566556"))][Get cited by]]

OpenAlex: https://openalex.org/W4394566556 (Open access: False)
    
[[https://openalex.org/A5037077755][Pengfei Liu]], [[https://openalex.org/A5000696502][Zheng Chen]], [[https://openalex.org/A5060633377][Wei Liu]], [[https://openalex.org/A5004299496][Xiaodong Wu]], [[https://openalex.org/A5064821504][Shuang Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01230 
     
No abstract    

    

* Fluorinated Biphenyl Phosphine Ligands for Accelerated [Au(I)]-Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394567969
:TOPICS: Gold Catalysis in Organic Synthesis, Transition Metal Catalysis, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00593")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394567969"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394567969"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394567969"))][Get cited by]]

OpenAlex: https://openalex.org/W4394567969 (Open access: False)
    
[[https://openalex.org/A5031838921][Riccardo Pedrazzani]], [[https://openalex.org/A5003292804][Sofia Kiriakidi]], [[https://openalex.org/A5083086799][Magda Monari]], [[https://openalex.org/A5066784317][Irene Lazzarini]], [[https://openalex.org/A5019212035][Giulio Bertuzzi]], [[https://openalex.org/A5058546077][Carlos Silva López]], [[https://openalex.org/A5077034819][Marco Bandini]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00593 
     
Fluorinated JohnPhos-type ligands are proposed as accelerating tools in homogeneous gold(I) catalysis, with PedroPhosAuCl (Cat1) as the most efficient one. The ligands as well as the corresponding gold complexes were synthesized in high yields and fully characterized also via single-crystal X-ray diffraction. A secondary interaction between the distal phenyl ring of the phosphane ligand and the metal center is identified as key for the fine-tuning of the overall catalytic performance of the complexes. In particular, kinetic as well as computational analysis revealed that by accommodating F atoms on the biphenyl pendant of the ligand, more reactive organo-gold intermediates are realized toward subsequent nucleophilic condensations. The gold-catalyzed indole-hydroarylation of 1,6-enynes and the intramolecular hydroindolynation of alkynes have been adopted as benchmark reactions to exemplify these accelerating effects.    

    

* Electrifying Energy and Chemical Transformations with Single-Atom Alloy Nanoparticle Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394576674
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-04-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00365")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394576674"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394576674"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394576674"))][Get cited by]]

OpenAlex: https://openalex.org/W4394576674 (Open access: True)
    
[[https://openalex.org/A5035090837][Qiang Gao]], [[https://openalex.org/A5038027282][Xue Han]], [[https://openalex.org/A5024914236][Yuanqi Liu]], [[https://openalex.org/A5087106141][Huiyuan Zhu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00365  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00365][pdf]])
     
Single-atom alloys (SAAs) have attracted considerable attention as promising electrocatalysts in reactions central to energy conversion and chemical transformation. In contrast to monometallic nanocrystals and metal alloys, SAAs possess unique and intriguing physicochemical properties, positioning them as ideal model systems for studying structure–property relationships. However, the field is still in its early stages. In this Perspective, we first review and summarize rational synthesis methods and advanced characterization techniques for SAA nanoparticle catalysts. We then emphasize the extensive applications of SAAs in a range of electrocatalytic reactions, including fuel cell reactions, water splitting, and carbon dioxide and nitrate reductions. Finally, we provide insights into existing challenges and prospects associated with the controlled synthesis, characterization, and design of SAA catalysts.    

    

* Research Progress on Preparation of Metal Oxide Catalysts with Porous Structure and Their Catalytic Purification of Diesel Engine Exhausts Gases  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394578929
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00323")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394578929"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394578929"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394578929"))][Get cited by]]

OpenAlex: https://openalex.org/W4394578929 (Open access: False)
    
[[https://openalex.org/A5008476939][Shian Zhou]], [[https://openalex.org/A5016660396][Lanyi Wang]], [[https://openalex.org/A5084746751][Siyu Gao]], [[https://openalex.org/A5078226849][Xinyu Chen]], [[https://openalex.org/A5088059015][Chunlei Zhang]], [[https://openalex.org/A5038450038][Di Yu]], [[https://openalex.org/A5067365795][Xiaoqiang Fan]], [[https://openalex.org/A5045949335][Xin Yu]], [[https://openalex.org/A5065361552][Zhao Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00323 
     
Because of their special physicochemical properties, pore-structured metal oxide catalysts are widely used in environmental catalysis, energy chemicals, fuel cells, medicine, and other related fields. In recent years, these oxides have also been increasingly studied in the catalytic purification of diesel engine exhaust gases. In this paper, the research progresses of preparation methods of porous metal oxide catalysts and their application in the catalytic purification of diesel engine exhaust were reviewed. The advantages and disadvantages of different methods for the synthesis of porous metal oxide catalysts were elaborated, as well as the mechanism comparison of different types of porous metal oxide catalysts in catalytic purification of diesel engine exhaust pollutants. Finally, the current issues on the preparation of porous metal oxide catalysts and their development trends in application of diesel engine exhaust purification were summarized and discussed. The pore-structured metal oxide catalysts are beneficial for improving the contact efficiency between catalysts and pollutants, which can enhance the catalytic purification efficiency of catalysts. Meanwhile, the intrinsic activity is the most fundamental factor for determining their catalytic activity except for porous structure effects. In addition, this paper can help researchers to deeply understand the important effect of porous metal oxide catalysts in the treatment of diesel engine exhaust pollutants and provide theoretical guidance for the design and development of high-efficiency catalysts.    

    

* An Overview on Dynamic Phase Transformation and Surface Reconstruction of Iron Catalysts for Catalytic Hydrogenation of COx for Hydrocarbons  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394579619
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05854")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394579619"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394579619"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394579619"))][Get cited by]]

OpenAlex: https://openalex.org/W4394579619 (Open access: False)
    
[[https://openalex.org/A5000821238][Xiaoxu Ding]], [[https://openalex.org/A5052454489][Minghui Zhu]], [[https://openalex.org/A5008837035][Bo Sun]], [[https://openalex.org/A5017547546][Zixu Yang]], [[https://openalex.org/A5057242677][Yi‐Fan Han]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05854 
     
Catalytic hydrogenation of COx (CO and CO2) with renewable H2 represents a feasible practice for carbon capture and utilization and synthesis of chemical commodities, such as olefins, aromatics, and higher alcohols as well as liquid fuels. Direct synthesis via Fischer–Tropsch Synthesis (FTS) is considered as one of the most promising processes. Iron-based catalysts have been recognized as efficient candidates for catalytic hydrogenation of both CO and CO2 to value-added hydrocarbons due to their superior activities for C–O bond dissociative activation, reverse/water gas shift reaction, and C–C chain growth. The structural complexity and dynamic evolution of iron-based catalysts under COx-FTS conditions impose challenges on the understanding of the reaction mechanisms, the dynamic structure of active sites and further improvements of the catalytic performance. In this Review, we discussed the recent developments in characterization techniques for identifying the structural evolution of iron-based catalysts under reaction conditions. We also summarized feasible strategies to manipulate the process of the structural change via promoter interfacing, catalyst pretreating protocols, and application of external physical fields. Finally, we concluded the review by identifying current challenges and opportunities for the next generation of COx catalytic hydrogenation process with an emphasis on the combinatorial contributions from in situ/operando characterizations, chemometrics and machine learning.    

    

* Structural Evolution of Oxide-Derived Nanostructured Silver Electrocatalysts during CO2 Electroreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394579662
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00217")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394579662"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394579662"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394579662"))][Get cited by]]

OpenAlex: https://openalex.org/W4394579662 (Open access: False)
    
[[https://openalex.org/A5067922425][Mengying Yang]], [[https://openalex.org/A5059630698][Jingjing Wu]], [[https://openalex.org/A5050556980][Yue Li]], [[https://openalex.org/A5060188714][Haitao Pan]], [[https://openalex.org/A5071407794][Hongbo Cui]], [[https://openalex.org/A5035794202][Xianglong Lu]], [[https://openalex.org/A5002911869][Xiaohong Tang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00217 
     
Oxide-derived (OD) metals have been demonstrated as a kind of promising catalyst with superior catalytic activity for carbon dioxide electroreduction. Here we fabricate OD nanoporous silver by a simple, cost-effective electrochemical oxidation–reduction treatment, which enables reducing carbon dioxide to carbon monoxide with a Faradaic efficiency of 87% at −0.8 V vs RHE, significantly higher than that of untreated silver foil under the same conditions. Electron backscattered diffraction analysis reveals that there is a distinct grain refining during the initial CO2 electrochemical reduction from Ag oxide to OD-Ag. Experiment results indicated that the catalytic activity and selectivity are closely linked to the grain boundary and nanoporous structure on the surface, which has also been proven by theoretical calculation. However, after a long catalysis time (12 h), it was found that the surface grain coarsened and the thickness of the nanostructured layer reduced, resulting in the deactivation of the OD-Ag electrode. A dissolution–redeposition mechanism was proposed to govern the degradation of OD-Ag. The catalytic activity can be regenerated again by applying electrochemical oxidation–reduction treatment, which can increase the thickness of the porous layer and electrochemical active surface area significantly.    

    

* Biocatalytic Enantioselective Reduction of Cyclopropenyl Esters and Ketones Using Ene-Reductases  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394581090
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Enzyme Immobilization Techniques, Click Chemistry in Chemical Biology and Drug Development
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00899")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394581090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394581090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394581090"))][Get cited by]]

OpenAlex: https://openalex.org/W4394581090 (Open access: False)
    
[[https://openalex.org/A5045482234][Tomohiro Yasukawa]], [[https://openalex.org/A5083465305][Pierre Gilles]], [[https://openalex.org/A5035382136][Juliette Martin]], [[https://openalex.org/A5069511260][Julien Boutet]], [[https://openalex.org/A5040685904][Janine Cossy]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00899 
     
Enantioselective reduction of cyclopropenyl esters and ketones to optically active cyclopropanes has been achieved by using whole-cell-overexpressing ene-reductases (EREDs). By using these enzymes, trans-cyclopropanes were isolated in good yield and high enantiomeric excess. A wide range of optically active cyclopropane esters and ketones were obtained, and a variety of substituent patterns on the cyclopropenes were tolerated.    

    

* Ene-Reductase-Catalyzed Enantioselective Desymmetrization of Cyclohexadienones: Straightforward Access to All-Carbon Quaternary Stereocenters  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394581211
:TOPICS: Olefin Metathesis Chemistry, Homogeneous Catalysis with Transition Metals, Asymmetric Catalysis
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00239")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394581211"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394581211"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394581211"))][Get cited by]]

OpenAlex: https://openalex.org/W4394581211 (Open access: False)
    
[[https://openalex.org/A5037955329][Xiaofan Wu]], [[https://openalex.org/A5069352060][Lin Yang]], [[https://openalex.org/A5045267855][Zhigang Liu]], [[https://openalex.org/A5030064573][Ke Zhang]], [[https://openalex.org/A5015046053][Zedu Huang]], [[https://openalex.org/A5001652506][Fen‐Er Chen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00239 
     
An unprecedented enzyme-catalyzed enantioselective desymmetrization of achiral 2,5-cyclohexadienones has been reported. Using ene-reductases as the biocatalysts, a variety of γ,γ-disubstituted cyclohexadienones were reduced to the respective chiral cyclohexenones bearing an all-carbon quaternary stereocenter in high yields (up to 96%) along with low levels of over-reduction (less than 4% cyclohexanones in most cases) and good enantioselectivities (mostly 99% ee), which are superior to the enantioselectivities obtained with the chemocatalysis. A mutagenesis study indicated residue Q232 was likely important for NCR in providing cyclohexenones selectively over cyclohexanones, and molecular dynamics (MD) simulations were performed to rationalize the good enantioselectivity and low level of over-reduction observed for this enzyme. The deuterium-labeling experiment suggested the hydrogen at the N5 atom of the reduced flavin cofactor added to the face of the substrate 1a that has the bulkier phenyl group facing toward it. The current work expands the substrate scope of ene-reductases, providing an efficient, stereoselective access to valuable chiral γ,γ-disubstituted cyclohexenones, and will stimulate the development of other classes of enzyme-catalyzed enantioselective desymmetrization of cyclohexadienones.    

    

* Enzymatic Fluoroethylation by a Fluoroethyl Selenium Analogue of S-Adenosylmethionine  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394603197
:TOPICS: Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Role of Homocysteine in Health and Disease, Amino Acid Transport and Metabolism in Health and Disease
:PUBLICATION_DATE: 2024-04-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01112")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394603197"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394603197"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394603197"))][Get cited by]]

OpenAlex: https://openalex.org/W4394603197 (Open access: False)
    
[[https://openalex.org/A5065908524][Neng-Wei Yu]], [[https://openalex.org/A5014465828][Huimin Zhao]], [[https://openalex.org/A5004952405][Wenrui Wang]], [[https://openalex.org/A5073267812][Min Dong]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01112 
     
Fluorine is a unique element with important roles in medicinal chemistry, agrochemistry, and materials chemistry. The fluoroethyl group is an important fluoroalkyl functional unit that is widely used in clinical drugs, 19F probes and 18F PET diagnostic drugs. Chemo- and regioselective fluoroethylation is difficult in chemical synthesis. To date, no enzymatic reaction for selective fluoroethylation has been reported. Based on the widespread natural methyl donor S-adenosine-l-methionine (SAM), we designed and synthesized a fluoroethyl SAM analogue (FEt-SAM). A stability study revealed that FEt-SAM was very labile under physiological conditions and gave the fluorine-elimination product vinyl-SAM. We circumvented this problem by replacing the S in FEt-SAM with Se to give fluoroethyl Se-adenosyl-l-selenomethionine (FEt-SeAM). By using halide methyltransferase (HMT) and its mutant for the in situ production of FEt-SeAM, we created cascade reactions of the HMT mutant with methyltransferases and fluoroethylated several O-, N-, S-, and C-nucleophiles. For methyltransferases that did not recognize FEt-SeAM well, such as DnrK and NovO, simple mutagenesis of the conserved hydrophobic residues (Leu and Ile) in the SAM binding pocket to smaller amino acids significantly increased the activities. Therefore, we have provided a useful tool for the late-stage fluoroethylation of natural products and drugs. This method could also be used to enzymatically prepare probes for 19F NMR and 18F PET tests.    

    

* Self-Reconstruction of Core–Shell Structured Electrocatalysts for Tailoring Reaction Pathways Revealed by Electrochemical Surface-Enhanced Raman Spectroscopy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394605271
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00269")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394605271"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394605271"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394605271"))][Get cited by]]

OpenAlex: https://openalex.org/W4394605271 (Open access: False)
    
[[https://openalex.org/A5032411718][Zhixuan Lu]], [[https://openalex.org/A5060479752][Yajun Huang]], [[https://openalex.org/A5013191926][Ningyu Chen]], [[https://openalex.org/A5002314156][Chuan Liu]], [[https://openalex.org/A5033792704][Xiang Wang]], [[https://openalex.org/A5016139257][Bin Ren]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00269 
     
The electrocatalysts undergo structural reconstruction during electrocatalytic reactions, accompanied by significant variations in the catalytic activity and selectivity. However, it is still challenging to track in situ structural evolution and reaction process simultaneously to further figure out the origin of the surface reconstruction and its correlation to the electrocatalytic performance. By utilizing the species involved in formic acid electrooxidation reaction (FAER) as probe molecules, we employed electrochemical surface-enhanced Raman spectroscopy (EC-SERS) to reveal that the surface reconstruction process occurred on Au core-Pt shell nanoparticles (Au@Pt NPs). Via potential-dependent Raman features, we clearly revealed that the Au atoms from the Au core can migrate to the ultrathin Pt shell during FAER. Importantly, in situ SERS spectra showed that the reconstruction of Au@Pt NPs originated from the CO produced during the electrocatalytic process. We further showed that this structural transformation reduces the CO binding strength on Pt surfaces and tailors the reaction pathways of the FAER, thus facilitating the pathway of direct dehydrogenation of formic acid to CO2 by 2.6 times. This work demonstrates the importance of structural evolution of electrocatalysts during the reaction process to the catalytic performance, providing insight for designing highly efficient and robust electrocatalysts.    

    

* Correction to “N-Heterocyclic Carbene-Carbodiimide (NHC-CDI) Betaines as Organocatalysts for β-Butyrolactone Polymerization: Synthesis of Green PHB Plasticizers with Tailored Molecular Weights”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394620060
:TOPICS: Transition Metal Catalysis, Carbon Dioxide Utilization for Chemical Synthesis, Biodegradable Polymers as Biomaterials and Packaging
:PUBLICATION_DATE: 2024-04-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01882")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394620060"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394620060"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394620060"))][Get cited by]]

OpenAlex: https://openalex.org/W4394620060 (Open access: True)
    
[[https://openalex.org/A5046769905][David Sánchez-Roa]], [[https://openalex.org/A5044974820][Valentina Sessini]], [[https://openalex.org/A5011679409][Marta E. G. Mosquera]], [[https://openalex.org/A5041336405][Juan Cámpora]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01882  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01882][pdf]])
     
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVAddition/CorrectionNEXTORIGINAL ARTICLEThis notice is a correctionCorrection to "N-Heterocyclic Carbene-Carbodiimide (NHC-CDI) Betaines as Organocatalysts for β-Butyrolactone Polymerization: Synthesis of Green PHB Plasticizers with Tailored Molecular Weights"David Sánchez-RoaDavid Sánchez-RoaDepartamento de Química Orgánica y Química Inorgánica, Instituto de Investigación en Química "Andrés M. del Río" (IQAR) Universidad de Alcalá, Campus Universitario, Alcalá de Henares, Madrid 28871, SpainMore by David Sánchez-Roa, Valentina SessiniValentina SessiniDepartamento de Química Orgánica y Química Inorgánica, Instituto de Investigación en Química "Andrés M. del Río" (IQAR) Universidad de Alcalá, Campus Universitario, Alcalá de Henares, Madrid 28871, SpainMore by Valentina Sessinihttps://orcid.org/0000-0003-1205-4586, Marta E. G. Mosquera*Marta E. G. MosqueraDepartamento de Química Orgánica y Química Inorgánica, Instituto de Investigación en Química "Andrés M. del Río" (IQAR) Universidad de Alcalá, Campus Universitario, Alcalá de Henares, Madrid 28871, Spain*Email: [email protected]More by Marta E. G. Mosquerahttps://orcid.org/0000-0003-2248-3050, and Juan Cámpora*Juan CámporaInstituto de Investigaciones Químicas, CSIC-Universidad de Sevilla, Sevilla 41092, Spain*Email: [email protected]More by Juan Cámporahttps://orcid.org/0000-0001-7305-1296Cite this: ACS Catal. 2024, 14, XXX, 6203Publication Date (Web):April 9, 2024Publication History Received28 March 2024Published online9 April 2024https://doi.org/10.1021/acscatal.4c01882© 2024 The Authors. Published by American Chemical Society. This publication is licensed under CC-BY 4.0. License Summary*You are free to share (copy and redistribute) this article in any medium or format and to adapt (remix, transform, and build upon) the material for any purpose, even commercially within the parameters below:Creative Commons (CC): This is a Creative Commons license.Attribution (BY): Credit must be given to the creator.View full license*DisclaimerThis summary highlights only some of the key features and terms of the actual license. It is not a license and has no legal value. Carefully review the actual license before using these materials. This publication is Open Access under the license indicated. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (812 KB) Get e-Alertsclose Get e-Alerts    

    
