#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Mon Dec  9 01:38:37 2024

Found 36 results from 2024-12-02 to 2024-12-09
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Correction to “Uncovering Hydroxynitrile Lyase Variants with Promiscuous Diastereoselective Nitroaldolase Activity toward the Highly Stereocontrolled Synthesis of Anti β-Nitroalcohols”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404905332
:TOPICS: Chemical Glycobiology and Therapeutic Applications, Amino Acid Transport and Metabolism in Health and Disease, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06888")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404905332"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404905332"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404905332"))][Get cited by]]

OpenAlex: https://openalex.org/W4404905332 (Open access: True)
    
[[https://openalex.org/A5114944281][Ayon Chaterjee]], [[https://openalex.org/A5107869341][G. Priyanka]], [[https://openalex.org/A5017053564][N. Prakash Prabhu]], [[https://openalex.org/A5019648537][Santosh Kumar Padhi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06888  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c06888?ref=article_openPDF][pdf]])
     
InfoMetricsFiguresRef.SI ACS CatalysisASAPArticle This publication is free to access through this site. Learn More CiteCitationCitation and abstractCitation and referencesMore citation options ShareShare onFacebookX (Twitter)WeChatLinkedInRedditEmailJump toExpandCollapse ORIGINAL ARTICLE. This notice is a correction.Addition/CorrectionDecember 2, 2024Correction to "Uncovering Hydroxynitrile Lyase Variants with Promiscuous Diastereoselective Nitroaldolase Activity toward the Highly Stereocontrolled Synthesis of Anti β-Nitroalcohols"Click to copy article linkArticle link copied!Ayon ChaterjeeAyon ChaterjeeMore by Ayon ChaterjeeG. PriyankaG. PriyankaMore by G. PriyankaN. Prakash PrabhuN. Prakash PrabhuMore by N. Prakash Prabhuhttps://orcid.org/0000-0002-3024-1142Santosh Kumar Padhi*Santosh Kumar PadhiMore by Santosh Kumar Padhihttps://orcid.org/0000-0001-5202-6702Open PDFSupporting Information (1)ACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 18406–18407Click to copy citationCitation copied!https://pubs.acs.org/doi/10.1021/acscatal.4c06888https://doi.org/10.1021/acscatal.4c06888Published December 2, 2024 Publication History Received 8 November 2024Published online 2 December 2024correction© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsThis publication is licensed for personal use by The American Chemical Society. ACS Publications© 2024 American Chemical SocietyIt has come to our attention that the kinetic parameters were erroneously calculated during the change of their units from the data presented in the Supporting Information to the main article. While the Supporting Information correctly represented the kinetic parameters (Figure S76 and Figure S77), the units (KM in mM, kcat in min–1, and kcat /KM in min–1 mM–1) are different from those in the main article (Table 1, Page 12626). The corrected Table 1 and its corresponding description (Kinetic Studies, Page 12629) (corrections are in bold) as well as the corrected sections of the Supporting Information (Figure S76 and Figure S77) are provided with this Correction. It is important to note that these modified parameters do not impact any of the conclusions drawn in the original article.In addition, we erroneously typed T14 to represent the Y14 in Figure S85A and Figure S86A of the Supporting Information. The corrected figures are provided in the Supporting Information with this Correction.Kinetic StudiesClick to copy section linkSection link copied!In order to gain insights of kinetics information about the DHR, both the variants, Y14C and Y14A, along with the wild-type enzyme were taken for evaluation. The steady-state kinetic parameters of Y14C toward the synthesis of (1R,2S)-1a were determined by measuring the initial velocities against different concentrations of 1. In comparison to the wild-type, Y14C exhibited >88-fold improved kcat, and ∼3-fold reduced KM (Table 1, Figure S77A,B). The single variant elicited a remarkable increase in catalytic efficiency of >250-fold than the wild-type, as kcat/KM of Y14C and the wild-type were found to be 5.01 and 0.02 s–1 M–1, respectively. The kinetic parameters for Y14A toward (1R,2S)-9b were kcat = 0.06 s–1, KM = 40.2 mM (Table 1, Figure S77C). Selection of 9 for this study was based on the highest catalytic activity and stereoselectivity of Y14A achieved during asymmetric addition of 1-nitropropane to this substrate (Figure 4). Unfortunately, the kinetic data of the wild-type was not possible to measure toward the synthesis of 9b due to its extremely low activity. The catalytic efficiency (kcat/KM) of Y14A was found to be 1.49 s–1 M–1. Even though it is unfair to compare, the catalytic efficiency of Y14A toward (1R,2S)-9b, which is assumed to be highest among the molecules of Figure 4, appeared to be ∼3.5-fold less than the catalytic efficiency of Y14C toward the synthesis of 1a. The former case has demonstrated a ∼2-fold reduced kcat along with increased KM compared with data for the latter. This explains the overall reduced biocatalytic conversion to 1-nitropropane based β-nitroalcohols as compared to nitroethane based β-nitroalcohols. Due to lack of similar data the kinetics parameters could not be compared with other HNLs. However, the catalytic efficiency (kcat/KM) of Y14C catalyzed synthesis of 1a is >580-fold and Y14A catalyzed synthesis of 9b is >720-fold lower than the catalytic efficiency of one of the best AtHNL variants (F179N) toward nitromethane addition to 1 or 9.70 This suggests that stereoselective addition of longer nitroalkanes remains a challenge despite the use of the same aldehyde, 1 in the asymmetric Henry reaction.Table 1. Kinetic Data of Wild-Type AtHNL and Variants toward 1a and 9b SynthesisaEnzymeAldehydeNucleophilepHKM (mM)kcat (s–1)kcat/KM (s–1 M–1)wild-type1a5.570.12 ± 5.931.4 × 10–3 ± 7.6 × 10–50.02 ± 0.001Y14C1a5.525.14 ± 3.470.126 ± 0.0195.01 ± 0.16Wild-type1a8.276.85 ± 2.665.2 × 10–4 ± 7 × 10–50.0068 ± 0.0009Y14C1a8.256.87 ± 3.820.38 ± 0.0426.6 ± 0.73Wild-type9b5.5ndndndY14A9b5.540.2 ± 2.880.06 ± 0.0041.49 ± 0.1aThe Michaelis–Menten plots are shown in Figures S77 and S78. Each value represents the average of three independent measurements. nd: not determined.Supporting InformationClick to copy section linkSection link copied!The Supporting Information is available free of charge at https://pubs.acs.org/doi/10.1021/acscatal.4c06888.Corrected versions of Figures S77, S78, S85, and S86 (PDF)cs4c06888_si_001.pdf (125.89 kb) Terms & Conditions Most electronic Supporting Information files are available without a subscription to ACS Web Editions. Such files may be downloaded by article for research use (if there is a public use license linked to the relevant article, that license may permit other uses). Permission may be obtained from ACS for other uses through requests via the RightsLink permission system: http://pubs.acs.org/page/copyright/permissions.html. Author InformationClick to copy section linkSection link copied!Corresponding AuthorSantosh Kumar Padhi; https://orcid.org/0000-0001-5202-6702; Email: AuthorsAyon ChaterjeeG. PriyankaN. Prakash Prabhu; https://orcid.org/0000-0002-3024-1142Cited By Click to copy section linkSection link copied!This article has not yet been cited by other publications.Download PDFFiguresReferencesSupporting Information Get e-AlertsGet e-AlertsACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 18406–18407Click to copy citationCitation copied!https://doi.org/10.1021/acscatal.4c06888Published December 2, 2024 Publication History Received 8 November 2024Published online 2 December 2024© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsArticle Views-Altmetric-Citations-Learn about these metrics closeArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated.Recommended Articles FiguresReferencesSupporting InfoThis publication has no figures.This publication has no References.Supporting InformationSupporting InformationThe Supporting Information is available free of charge at https://pubs.acs.org/doi/10.1021/acscatal.4c06888.Corrected versions of Figures S77, S78, S85, and S86 (PDF)cs4c06888_si_001.pdf (125.89 kb) Terms & Conditions Most electronic Supporting Information files are available without a subscription to ACS Web Editions. Such files may be downloaded by article for research use (if there is a public use license linked to the relevant article, that license may permit other uses). Permission may be obtained from ACS for other uses through requests via the RightsLink permission system: http://pubs.acs.org/page/copyright/permissions.html.    

    

* Controlling Cubic versus Octahedral Morphology in Plasmonic Aluminum Nanoparticle Synthesis with Titanocene Catalysts: A Systematic Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404913495
:TOPICS: Plasmonic Nanoparticles: Synthesis, Properties, and Applications, Formation and Properties of Nanocrystals and Nanostructures, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06286")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404913495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404913495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404913495"))][Get cited by]]

OpenAlex: https://openalex.org/W4404913495 (Open access: False)
    
[[https://openalex.org/A5012050880][Jae‐Kwan Kim]], [[https://openalex.org/A5047514009][Christian R. Jacobson]], [[https://openalex.org/A5069086177][Naomi J. Halas]], [[https://openalex.org/A5083700647][Ian A. Tonks]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06286 
     
Ti precatalysts containing the titanocene moiety (Cp2Ti–, Cp = cyclopentadienyl) can, under certain conditions, selectively produce cubic Al nanocrystals through the dehydrocoupling of alane amine adducts such as AlH3·NMe2Et. A systematic study of reaction conditions reveals that cubic Al nanoparticle formation occurs at a higher temperature (e.g., 65 °C) and/or higher catalyst-concentration conditions (e.g., 0.5 mol % [Ti]). Kinetic studies reveal that under these conditions nanoparticle formation and alane consumption are much faster, and cubic nanoparticle formation takes place under kinetically controlled conditions. On the other hand, employing a wide suite of TiX4 (X = anionic ligand)-type precatalysts yielded only octahedral-shaped aluminum nanoparticles regardless of conditions. Finally, we report the synthesis of a hydride-bridged Ti–Al heterobimetallic compound from the reaction of Cp2TiCl2 with AlH3·NMe2Et and characterized it to show that it is a reaction intermediate in the Ti-catalyzed aluminum nanoparticle synthesis.    

    

* Tailoring the Coordination Environment of Cu Single Atoms for Achieving Regioselective C–C Bond Activation of Amides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404917578
:TOPICS: Homogeneous Catalysis with Transition Metals, Peptide Synthesis and Drug Discovery, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05223")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404917578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404917578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404917578"))][Get cited by]]

OpenAlex: https://openalex.org/W4404917578 (Open access: False)
    
[[https://openalex.org/A5007958844][Wunengerile Zhang]], [[https://openalex.org/A5004470604][Chaolumen Bai]], [[https://openalex.org/A5100326883][Dan Liu]], [[https://openalex.org/A5075440492][Agula Bao]], [[https://openalex.org/A5029620953][Tegshi Muschin]], [[https://openalex.org/A5064108348][Yong‐Sheng Bao]], [[https://openalex.org/A5006099744][Jin Xie]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05223 
     
C–C bond activation can provide a direct reconstruction strategy of carbon skeletons to furnish a number of structurally diverse molecules. In general, regioselectivity represents the state-of-the-art owing to the existence of several different carbon–carbon bonds, having a high BDE, ∼90 kcal/mol. Here, we report a directed strategy for amides for the concise synthesis of a range of urea derivatives and carbamates via regioselective C–C bond activation enabled by the heterogeneous single-atom copper catalyst (Cu-SAC), with a turnover frequency of 249 h–1, which is 19 times higher than that of the analogous homogeneous copper catalyst. Multitechnique characterization data show that single-atom Cu species are associated with an unsaturated coordination structure and plentiful oxygen vacancies on γ-Al2O3 that facilitate the adsorption of multiple coordinated amides and dioxygen, leading to high catalytic activity and selectivity. It would offer opportunities to speed up the heterogenized process of homogeneous catalysts in regioselective inert-bond activation reactions.    

    

* Ru(II)-Catalyzed [1,4]-Sigmatropic Rearrangement and Intramolecular Concerted SNAr of Aryl and Heteroarylthio Derivatives using Quinoid Carbene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404917688
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05272")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404917688"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404917688"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404917688"))][Get cited by]]

OpenAlex: https://openalex.org/W4404917688 (Open access: False)
    
[[https://openalex.org/A5085524549][Subarna Pan]], [[https://openalex.org/A5099986984][Md. Saimuddin Sk]], [[https://openalex.org/A5111203598][B. SANYAL]], [[https://openalex.org/A5053449233][Lisa Roy]], [[https://openalex.org/A5004014371][Rajarshi Samanta]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05272 
     
A Ru(II)-catalyzed straightforward and efficient strategy has been developed to construct O-alkylated arylnaphthyl thioether derivatives using arylthioacetates/arylalkylthioethers with diazonaphthoquinone via a [1,4]-oxa sigmatropic rearrangement. In a complementary method, heteroaryl thioacetate/heteroaryl alkylthioethers offer O-heteroaryl alkylnaphthyl thioether derivatives via an interesting concerted intramolecular SNAr-type reaction. Both of these methods proceed through the formation of Ru-based quinoid carbene and sulfur ylide, respectively. A detailed mechanistic study and DFT calculations reveal that the reaction is going via a concerted manner. Postsynthetic modifications of the synthesized compounds led to sulfur-containing polyaromatic heterocycles.    

    

* Photocatalytic Carboxylation of Terminal Alkynes with CO2 over Metal–Porphyrin Framework Nanosheets  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404920674
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06006")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404920674"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404920674"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404920674"))][Get cited by]]

OpenAlex: https://openalex.org/W4404920674 (Open access: False)
    
[[https://openalex.org/A5083141761][Yanyue Wang]], [[https://openalex.org/A5102006388][Jianling Zhang]], [[https://openalex.org/A5100608375][Sha Wang]], [[https://openalex.org/A5016948713][Zhonghao Tan]], [[https://openalex.org/A5022371906][Yisen Yang]], [[https://openalex.org/A5013241583][Yingzhe Zhao]], [[https://openalex.org/A5112805144][Buxing Han]], [[https://openalex.org/A5100340669][Qian Li]], [[https://openalex.org/A5064648986][Junfeng Xiang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06006 
     
To develop an environmentally benign and efficient route for converting CO2 into value-added chemicals is of great importance. Here, we demonstrate the photocatalytic carboxylation of terminal alkynes with CO2 at room temperature and atmospheric pressure, by copper-based porphyrinic framework photocatalysts Cu2TCPP(M) (TCPP = 5,10,15,20-tetrakis(4-carboxyphenyl)porphyrin; M = Fe, Co, Ni, Cu). The Cu2TCPP(Cu) nanosheets (with a small thickness of ∼5.1 nm) exhibit an extremely high performance for the reaction of 1-ethynylbenzene with CO2 to produce 3-phenylpropiolic acid. The turnover frequency is up to 3.33 mmol g–1 h–1 at 10 h, which is much higher than those of the photothermally and thermally driven routes that are usually adopted for the carboxylation reactions catalyzed by metal–organic frameworks. The mechanism for the superior activity of Cu2TCPP(Cu) nanosheets was investigated by a series of experiments and theoretical calculations. It is revealed that the Cu2TCPP(Cu) nanosheets not only possess good photoelectronic properties but have desired molecular structure for boosting CO2 activation, alkyne activation, and carboxylation reactions.    

    

* Disrupted Spin Degeneracy Promoted C≡C Triple Bond Activation for Efficient Electrochemical Acetylene Semihydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404924221
:TOPICS: Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06191")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404924221"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404924221"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404924221"))][Get cited by]]

OpenAlex: https://openalex.org/W4404924221 (Open access: False)
    
[[https://openalex.org/A5086662186][Menglei Yuan]], [[https://openalex.org/A5024214452][Hongyu Jiang]], [[https://openalex.org/A5112783857][Ruyi Jiang]], [[https://openalex.org/A5035758335][Zhao Wang]], [[https://openalex.org/A5100762170][Zhihao Zhao]], [[https://openalex.org/A5022972481][Bao‐Lian Su]], [[https://openalex.org/A5100409923][Jian Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06191 
     
Disrupting the spin degeneracy of the electrocatalyst and further manipulating the related orbital electron arrangement are highly desirable for activating acetylene molecules. Herein, a squarate cobalt-based metal–organic framework (Co-MOF) ([Co3(C4O4)2(OH)2]·3H2O) is post-treated to accelerate the evolution from CoO6 octahedron to CoO5 pentahedron and further utilized for the electrochemical acetylene semihydrogenation reaction. Comprehensive analyses corroborate that the disrupted spin degeneracy of active sites originated from the breakage of the Co–O bond, which promotes the cleavage of the orbital energy level and the rearrangement of the d-orbital electron. The newly emerged half-occupied dx2–y2 orbitals and empty dz2 orbitals in CoO5 pentahedron concerted interplay with the bonding and antibonding orbitals of acetylene, which reduces the adsorption energy of acetylene and facilitates the activation of the inert C≡C triple bond. Thus, the defective Co-MOF exhibits the superior ethylene Faradaic efficiency of 96% and partial current density of 128 mA cm–2 at −1.0 V vs RHE compared to that of pristine Co-MOF (FEC2H4: 60%; JC2H4: 66 mA cm–2). This work delivers inspiration for spin-state regulation of active sites and sparks renewed interest in designing highly efficient electrocatalysts.    

    

* Artificial Intelligence-Driven Development of Nickel-Catalyzed Enantioselective Cross-Coupling Reactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404941646
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Transition Metal-Catalyzed Cross-Coupling Reactions, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-12-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04277")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404941646"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404941646"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404941646"))][Get cited by]]

OpenAlex: https://openalex.org/W4404941646 (Open access: False)
    
[[https://openalex.org/A5020503704][Yadong Gao]], [[https://openalex.org/A5009307008][Kunjun Hu]], [[https://openalex.org/A5047983120][Jianhang Rao]], [[https://openalex.org/A5108264438][Qiang Zhu]], [[https://openalex.org/A5033384728][Kuangbiao Liao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04277 
     
The conventional approach to developing asymmetric synthetic methods relies heavily on empirical optimization. However, the integration of artificial intelligence (AI) and high-throughput experimentation (HTE) technology presents a paradigm shift with immense potential to revolutionize the discovery and optimization of asymmetric reactions. In this study, we present an efficient workflow for the development of a series of nickel-catalyzed asymmetric cross-coupling reactions, leveraging AI and HTE technology. Many nickel-catalyzed enantioselective cross-coupling reactions share a common Ni(III) intermediate, which dictates the enantioselectivity. To harness this mechanistic insight, we embarked on developing a predictive model for nickel-catalyzed enantioselective coupling reactions, elucidating the general rules governing enantioselectivity. Through the application of data science tools and HTE technology, we curated a data set to construct an AI-based model. This model was subsequently utilized to facilitate the discovery of efficient nickel hydride-catalyzed enantioselective and regioselective cross-coupling reactions. Employing AI-assisted virtual ligand screening and HTE-enabled condition optimization, we successfully identified optimal ligands for eight coupling reactions. Consequently, a series of chiral sp3 C–C bonds were synthesized with high yield and enantioselectivity.    

    

* Controlling Product Selectivity in Photochemical CO2 Reduction with the Redox Potential of the Photosensitizer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404944465
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Droplet Microfluidics Technology
:PUBLICATION_DATE: 2024-12-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03845")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404944465"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404944465"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404944465"))][Get cited by]]

OpenAlex: https://openalex.org/W4404944465 (Open access: False)
    
[[https://openalex.org/A5108049818][Lei Zhang]], [[https://openalex.org/A5011977174][Andressa V. Müller]], [[https://openalex.org/A5075691616][Sai Puneet Desai]], [[https://openalex.org/A5004375411][David C. Grills]], [[https://openalex.org/A5083979016][Dmitry E. Polyansky]], [[https://openalex.org/A5006832213][Renato N. Sampaio]], [[https://openalex.org/A5080197399][Javier J. Concepcion]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03845 
     
No abstract    

    

* Boron Designer Enzyme with a Hybrid Catalytic Dyad  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404961214
:TOPICS: Enzyme Immobilization Techniques, Electrospun Nanofibers in Biomedical Applications, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-12-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06052")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404961214"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404961214"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404961214"))][Get cited by]]

OpenAlex: https://openalex.org/W4404961214 (Open access: True)
    
[[https://openalex.org/A5032959008][Lars Longwitz]], [[https://openalex.org/A5028183720][Marijn D. Kamer]], [[https://openalex.org/A5060375530][Bart Brouwer]], [[https://openalex.org/A5087468780][A.M.W.H. Thunnissen]], [[https://openalex.org/A5032880385][Gérard Roelfes]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06052 
     
No abstract    

    

* Using Enzymes for Catalysis under Industrial Conditions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404974317
:TOPICS: Enzyme Immobilization Techniques, Metabolic Engineering and Synthetic Biology, Technologies for Biofuel Production from Biomass
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05265")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404974317"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404974317"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404974317"))][Get cited by]]

OpenAlex: https://openalex.org/W4404974317 (Open access: False)
    
[[https://openalex.org/A5086466356][Elif Erdem]], [[https://openalex.org/A5036903025][John M. Woodley]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05265 
     
No abstract    

    

* Deciphering Faujasite Zeolite Dealumination at the Atomic Scale  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404974759
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Nanomaterials, Novel Methods for Cesium Removal from Wastewater
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03036")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404974759"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404974759"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404974759"))][Get cited by]]

OpenAlex: https://openalex.org/W4404974759 (Open access: False)
    
[[https://openalex.org/A5043145785][Zhuoran Wang]], [[https://openalex.org/A5079354447][Thomas Jarrin]], [[https://openalex.org/A5010028411][Mickaël Rivallan]], [[https://openalex.org/A5078414887][Isabelle Clémençon]], [[https://openalex.org/A5074419428][Emmanuel Soyer]], [[https://openalex.org/A5027199996][Theodorus de Bruin]], [[https://openalex.org/A5088922603][L. Lemaître]], [[https://openalex.org/A5047261367][Virgile Rouchon]], [[https://openalex.org/A5085506972][David Gajan]], [[https://openalex.org/A5013812058][Gerhard D. Pirngruber]], [[https://openalex.org/A5014892353][Céline Chizallet]], [[https://openalex.org/A5023874849][Anne Lesage]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03036 
     
No abstract    

    

* Engineering Conjugation of Covalent Organic Frameworks for Carbon Dioxide Reduction Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404990562
:TOPICS: Covalent Organic Framework Applications, CO2 Reduction Techniques and Catalysts, Metal-Organic Frameworks: Synthesis and Applications
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03742")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404990562"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404990562"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404990562"))][Get cited by]]

OpenAlex: https://openalex.org/W4404990562 (Open access: False)
    
[[https://openalex.org/A5101741759][Shuang Zheng]], [[https://openalex.org/A5113124915][Shuai Xia]], [[https://openalex.org/A5044605278][Zhaofeng Ouyang]], [[https://openalex.org/A5009058201][Shuai Bi]], [[https://openalex.org/A5015297626][Yubin Fu]], [[https://openalex.org/A5040261155][Guojuan Liu]], [[https://openalex.org/A5100322900][Yan Wang]], [[https://openalex.org/A5069765087][Qing Xu]], [[https://openalex.org/A5028394871][Gaofeng Zeng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03742 
     
No abstract    

    

* Correction to “Mixed Silver–Bismuth Oxides: A Robust Oxygen Evolution Catalyst Operating at Low pH and Elevated Temperatures”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404991001
:TOPICS: Catalytic Processes in Materials Science, Electrocatalysts for Energy Conversion, Electronic and Structural Properties of Oxides
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404991001"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404991001"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404991001"))][Get cited by]]

OpenAlex: https://openalex.org/W4404991001 (Open access: False)
    
[[https://openalex.org/A5014780715][Darcy Simondson]], [[https://openalex.org/A5033971776][Manjunath Chatti]], [[https://openalex.org/A5079752274][James L. Gardiner]], [[https://openalex.org/A5069370180][Brittany Kerr]], [[https://openalex.org/A5089189830][Dijon A. Hoogeveen]], [[https://openalex.org/A5082353134][Pavel V. Cherepanov]], [[https://openalex.org/A5031911397][Inga Kuschnerus]], [[https://openalex.org/A5042031508][Tam D. Nguyen]], [[https://openalex.org/A5042673824][Bernt Johannessen]], [[https://openalex.org/A5015023372][Shery L. Y. Chang]], [[https://openalex.org/A5017109393][Douglas R. MacFarlane]], [[https://openalex.org/A5002235771][Rosalie K. Hocking]], [[https://openalex.org/A5062733036][Alexandr N. Simonov]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c07007 
     
No abstract    

    

* Dual Nickel/Photoredox-Catalyzed Aryl Etherification Enabled by an Oxidative Near-Infrared-to-Blue Triplet–Triplet Annihilation Upconversion System Leveraging Spin-Forbidden Excitation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404995780
:TOPICS: Radical Photochemical Reactions, Sulfur-Based Synthesis Techniques, Catalytic C–H Functionalization Methods
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06084")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404995780"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404995780"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404995780"))][Get cited by]]

OpenAlex: https://openalex.org/W4404995780 (Open access: False)
    
[[https://openalex.org/A5067437484][Logan R. Beck]], [[https://openalex.org/A5027086641][Katherine A. Xie]], [[https://openalex.org/A5019978169][Brendan C. Lainhart]], [[https://openalex.org/A5046082892][Trevor C. Sherwood]], [[https://openalex.org/A5088370687][Eric R. Welin]], [[https://openalex.org/A5044707223][Candice L. Joe]], [[https://openalex.org/A5074994681][Tomislav Rovis]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06084 
     
No abstract    

    

* Pd and Fe Cocatalyzed Synthesis of Remotely Borylated Aza-Heterocycles  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404998360
:TOPICS: Catalytic C–H Functionalization Methods, Catalytic Cross-Coupling Reactions, Radical Photochemical Reactions
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05702")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404998360"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404998360"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404998360"))][Get cited by]]

OpenAlex: https://openalex.org/W4404998360 (Open access: False)
    
[[https://openalex.org/A5002090481][Shreeja Bhatt]], [[https://openalex.org/A5092457737][Aja M. Nicely]], [[https://openalex.org/A5068741247][Camila U. Powell]], [[https://openalex.org/A5075594838][Marylin C. Huff]], [[https://openalex.org/A5054755565][Stefan Jon Thibodeaux]], [[https://openalex.org/A5010750871][Ya‐Nong Wang]], [[https://openalex.org/A5071047360][Serhii Vasylevskyi]], [[https://openalex.org/A5053697725][Kami L. Hull]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05702 
     
No abstract    

    

* Pd-Catalyzed Difluoroalkylation of Alkenes Using Chlorodifluoroalkanes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405002150
:TOPICS: Fluorine in Organic Chemistry, Inorganic Fluorides and Related Compounds
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06842")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405002150"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405002150"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405002150"))][Get cited by]]

OpenAlex: https://openalex.org/W4405002150 (Open access: False)
    
[[https://openalex.org/A5100378437][Jing Wang]], [[https://openalex.org/A5101101078][Qixin Zhou]], [[https://openalex.org/A5020457126][Liejin Zhou]], [[https://openalex.org/A5067205564][Zuxiao Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06842 
     
No abstract    

    

* Oxidation State of Single-Atom Re/TiO2 Hydrogenation Catalysts: A Computational Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405008567
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Hydrodesulfurization Studies, Nanomaterials for catalytic reactions
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05697")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405008567"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405008567"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405008567"))][Get cited by]]

OpenAlex: https://openalex.org/W4405008567 (Open access: True)
    
[[https://openalex.org/A5035603699][A. Sreenithya]], [[https://openalex.org/A5066349037][Alexander A. Kolganov]], [[https://openalex.org/A5013737627][In Won Yeu]], [[https://openalex.org/A5114994105][Muhammad Helmi Risansyauqi]], [[https://openalex.org/A5074252826][Evgeny A. Pidko]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05697 
     
No abstract    

    

* Electronic Interactions between Anchored Molecular Catalyst and Support  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405023659
:TOPICS: Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science, Surface Chemistry and Catalysis
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05947")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405023659"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405023659"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405023659"))][Get cited by]]

OpenAlex: https://openalex.org/W4405023659 (Open access: False)
    
[[https://openalex.org/A5032407202][Stephanie A. Johnson]], [[https://openalex.org/A5006690638][James R. Wilkes]], [[https://openalex.org/A5040290819][Dunwei Wang]], [[https://openalex.org/A5086992939][Jeffery A. Byers]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05947 
     
Immobilizing molecular catalysts on surfaces introduces spatial control of catalysis and promises improved stability and recyclability of the catalyst. The interplays between the support and the immobilized molecular species, however, remain underexplored. Using Ni as a prototypical support, here we report a study on how the electronic interactions between the support and the molecular catalyst impacts the reactivity. This work was built upon our previous successes in switching the reactivity of iron bis(iminopyridine) alkoxide complexes through redox toggling, where the anchored iron(II) complex polymerizes lactide, and its cationic iron(III) counterpart polymerizes epoxides. It was found that Ni as a metal support could readily oxidize the complex to exhibit catalytic activity toward epoxide polymerization. The charge transfer between Ni and the Fe complex could be modulated by either electrochemical reduction or adding a layer of TiO2. The results are expected to have major implications for research efforts aimed at converging homogeneous and heterogeneous catalysis.    

    

* Promoting Heptazine-Based Graphitic Carbon Nitride Photocatalytic Overall Water Splitting by Effectively Assembling Double-Unit Polymers  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405039581
:TOPICS: 
:PUBLICATION_DATE: 2024-12-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05801")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405039581"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405039581"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405039581"))][Get cited by]]

OpenAlex: https://openalex.org/W4405039581 (Open access: False)
    
[[https://openalex.org/A5016145553][Ruilin Guan]], [[https://openalex.org/A5048714219][Anqi Shi]], [[https://openalex.org/A5100744364][Xiuyun Zhang]], [[https://openalex.org/A5100382552][Bing Wang]], [[https://openalex.org/A5100753077][Yongtao Li]], [[https://openalex.org/A5045012383][Xianghong Niu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05801 
     
No abstract    

    

* Correction to “Influence of Carbon Support on the Pyrolysis of Cobalt Phthalocyanine for the Efficient Electroreduction of CO2”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405054009
:TOPICS: CO2 Reduction Techniques and Catalysts, Molecular Junctions and Nanostructures, Carbon dioxide utilization in catalysis
:PUBLICATION_DATE: 2024-12-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07096")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405054009"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405054009"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405054009"))][Get cited by]]

OpenAlex: https://openalex.org/W4405054009 (Open access: False)
    
[[https://openalex.org/A5026053485][Johan Hamonnet]], [[https://openalex.org/A5022266216][Michael S. Bennington]], [[https://openalex.org/A5042673824][Bernt Johannessen]], [[https://openalex.org/A5017012368][Jessica L. Hamilton]], [[https://openalex.org/A5055664078][Paula A. Brooksby]], [[https://openalex.org/A5011574979][Sally Brooker]], [[https://openalex.org/A5038674107][Vladimir B. Golovko]], [[https://openalex.org/A5023646639][Aaron T. Marshall]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c07096 
     
No abstract    

    

* Automated Exploration of Heterogeneous Catalysis with a Gas–Solid Nanoreactor  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405055249
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Machine Learning in Materials Science
:PUBLICATION_DATE: 2024-12-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06026")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405055249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405055249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405055249"))][Get cited by]]

OpenAlex: https://openalex.org/W4405055249 (Open access: False)
    
[[https://openalex.org/A5110388865][Jiawei Bai]], [[https://openalex.org/A5100644714][Xingchen Liu]], [[https://openalex.org/A5080670426][Tingyu Lei]], [[https://openalex.org/A5072985266][Yuwei Zhou]], [[https://openalex.org/A5103793376][Wenping Guo]], [[https://openalex.org/A5080199946][Dennis R. Salahub]], [[https://openalex.org/A5047313833][Xiaodong Wen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06026 
     
We present an automated method, gas–solid nanoreactor molecular dynamics (GS-NMD), designed to explore reaction space and construct reaction networks for complex gas–solid heterogeneous catalysis systems by integrating multiple acceleration techniques. Periodic pulses were used to drive gas-phase molecules toward the catalyst surface, accelerating adsorption and Eley–Rideal reactions. Adsorbed species were then subjected to metadynamics to overcome reaction barriers associated with migration, Langmuir–Hinshelwood-type reactions, and desorption, using the root-mean-square deviations in Cartesian space as collective variables. We demonstrate the efficiency of GS-NMD with the case of N2 dissociation on Fe surfaces, showing its ability to effectively screen for low-barrier reactions within a vast reaction space and distinct catalysts of different performances. Additionally, we illustrate the method's utility in constructing effective reaction networks for heterogeneous catalysis, exemplified by ammonia synthesis, which comprises only low-barrier elementary steps. These results suggest that GS-NMD is a promising and efficient tool for the automated exploration of heterogeneous catalysis, enabling the identification of the most favorable mechanisms and active sites for gas–solid reactions.    

    

* How Do Variants of Residues in the First Coordination Sphere, Second Coordination Sphere, and Remote Areas Influence the Catalytic Mechanism of Non-Heme Fe(II)/2-Oxoglutarate Dependent Ethylene-Forming Enzyme?  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405057265
:TOPICS: Metal-Catalyzed Oxygenation Mechanisms, Enzyme Structure and Function, Metal complexes synthesis and properties
:PUBLICATION_DATE: 2024-12-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04010")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405057265"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405057265"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405057265"))][Get cited by]]

OpenAlex: https://openalex.org/W4405057265 (Open access: False)
    
[[https://openalex.org/A5026364332][Midhun George Thomas]], [[https://openalex.org/A5038449861][Simahudeen Bathir Jaber Sathik Rifayee]], [[https://openalex.org/A5057631651][Christo Christov]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04010 
     
No abstract    

    

* Highly Efficient Photocatalytic Divergent Decarbonylative Silylation with Cinnamaldehyde via a [Ru(dcbpy)(bpy)2]2+-Incorporated UiO-67 Framework  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405075494
:TOPICS: Catalytic C–H Functionalization Methods, Polyoxometalates: Synthesis and Applications, Sulfur-Based Synthesis Techniques
:PUBLICATION_DATE: 2024-12-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05535")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405075494"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405075494"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405075494"))][Get cited by]]

OpenAlex: https://openalex.org/W4405075494 (Open access: False)
    
[[https://openalex.org/A5084159924][Huahui Wang]], [[https://openalex.org/A5111065243][Bing-Bing Qin]], [[https://openalex.org/A5075973287][Jiali Cai]], [[https://openalex.org/A5101472686][Yun Wu]], [[https://openalex.org/A5019750202][Cong Zhao]], [[https://openalex.org/A5112747003][Xiao‐Yan Bai]], [[https://openalex.org/A5100432107][Lu Chen]], [[https://openalex.org/A5072124977][Yan‐Zhong Fan]], [[https://openalex.org/A5100402936][Min Zhang]], [[https://openalex.org/A5010238813][Jiewei Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05535 
     
We herein develop an innovative approach for the decarbonylative silylation using a molecular [Ru(dcbpy)(bpy)2]2+ (dcbpy = 2,2′-bipyridyl-5,5′-dicarboxylic acid; bpy = 2,2′-bipyridine) incorporated UiO-67 metal–organic framework (MOFs) (denoted as UiO-67-Ru) as a powerful heterogeneous catalyst, which is then applied in the reaction of abundantly available cinnamaldehydes with silanes under photothermal condition. Mechanistic studies reveal that the silane can be absorbed and activated within the cavities of the framework, leading to the generation of a silyl radical. The silyl radical plays a key role in the decarbonylative silylation process and further goes through oxidative silylation with cinnamaldehydes to generate the corresponding alkenyl silanes. This work not only develops a strategy for the preparation of alkenyl silane from highly abundant cinnamaldehyde and silanes but also affords useful inspiration on the rational design of MOFs materials for the decarbonylative silylation.    

    

* Shallow Rate-Redox Potential Scaling in Aqueous Molecular Oxygen Reduction Electrocatalysis Across a Family of Iron Macrocycles  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405089233
:TOPICS: Electrocatalysts for Energy Conversion, Electrochemical Analysis and Applications, CO2 Reduction Techniques and Catalysts
:PUBLICATION_DATE: 2024-12-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06561")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405089233"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405089233"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405089233"))][Get cited by]]

OpenAlex: https://openalex.org/W4405089233 (Open access: False)
    
[[https://openalex.org/A5065288721][Travis Marshall-Roth]], [[https://openalex.org/A5054906524][Liang Liu]], [[https://openalex.org/A5083980714][Vennela Mannava]], [[https://openalex.org/A5022499260][Deiaa M. Harraz]], [[https://openalex.org/A5101856406][Brian J. Cook]], [[https://openalex.org/A5022980951][R. Morris Bullock]], [[https://openalex.org/A5021899292][Yogesh Surendranath]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06561 
     
Rate-overpotential scaling relationships have been employed widely to understand trends in oxygen reduction reaction (ORR) electrocatalysis by dissolved metal macrocycles in organic electrolytes. Similar scaling relationships remain unknown for surface-adsorbed ORR electrocatalysts in the acidic aqueous environments germane to proton-exchange membrane (PEM) fuel cells. Herein, we examine ORR catalysis in aqueous perchloric acid media for a structurally diverse array of iron macrocycle complexes adsorbed on Vulcan carbon black. The macrocycles encompass Fe–N4, Fe–N2N′2 and Fe–NxC4–x motifs bearing pyrrolic, pyridinic, and N-heterocyclic carbene (NHC) moieties in the primary ligation sphere, giving rise to a 670 mV range in Fe(III/II) redox potentials, EFe(III/II). Experimental Tafel data in the micropolarization regime were extrapolated to the EFe(III/II) to furnish estimated per-site-normalized current density (jper-site) values that span ∼4.6 orders of magnitude across the family of compounds. Despite the structural diversity of this family of compounds, extrapolated jper-site values correlate with the Fe(III/II) redox potentials in a roughly log-linear fashion with a shallow scaling factor of approximately 145 mV/decade. These findings highlight the phenomenology that negative shifts in EFe(III/II) track with diminishing returns in catalytic rate promotion, regardless of the exact ORR mechanism, and suggest that changes to the primary ligating environment in a macrocycle are insufficient to break fundamental rate-potential scaling relationships in aqueous ORR catalysis. Together these studies motivate the further development of higher-potential iron complexes that employ motifs beyond the equatorial ligation plane to enhance ORR catalysis.    

    

* Single-Atom Catalyst Restructuring during Catalytic Reforming of CH4 by CO2  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405093687
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Catalysts for Methane Reforming
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05703")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405093687"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405093687"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405093687"))][Get cited by]]

OpenAlex: https://openalex.org/W4405093687 (Open access: False)
    
[[https://openalex.org/A5004494343][Yu Tang]], [[https://openalex.org/A5067168903][Xupeng Zong]], [[https://openalex.org/A5077444518][Luan Nguyen]], [[https://openalex.org/A5074200142][Franklin Tao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05703 
     
No abstract    

    

* Ag-Regulated Interfacial Electron Transfer between TiO2 and MoSx for Enhanced H2O2 Production  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405104681
:TOPICS: Advanced Photocatalysis Techniques, Copper-based nanomaterials and applications, Perovskite Materials and Applications
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05674")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405104681"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405104681"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405104681"))][Get cited by]]

OpenAlex: https://openalex.org/W4405104681 (Open access: False)
    
[[https://openalex.org/A5101533967][Xidong Zhang]], [[https://openalex.org/A5051376349][Jiachao Xu]], [[https://openalex.org/A5113424237][Haoyu Long]], [[https://openalex.org/A5100423139][Jiaguo Yu]], [[https://openalex.org/A5060100426][Huogen Yu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05674 
     
The electronic configuration mismatch between the TiO2 support and the MoSx cocatalyst induces spontaneous free-electron transfer in an unfavorable direction, resulting in stronger O2 adsorption on Mo active sites and causing limited H2O2 production. Herein, we propose a strategy for directional free-electron transfer to produce electron-enriched Mo(4 – δ)+ sites via introducing an Ag mediator into the TiO2/MoSx photocatalyst, which aims to weaken O2 adsorption for improving H2O2 production activity. To achieve this, a core–shell Ag@MoSx cocatalyst was ingeniously constructed on the TiO2 surface to synthesize the TiO2/Ag@MoSx photocatalyst. The resultant TiO2/Ag@MoSx achieves a significantly enhanced H2O2 production rate of 16.13 mmol g–1 h–1 with an AQY value of 8.79%, surpassing TiO2/Ag and TiO2/MoSx by 10.0 and 237.2 times, respectively. Theoretical calculations and experimental results reveal that the incorporation of the Ag mediator into the TiO2/Ag@MoSx system can facilitate directional free-electron transfer to the MoSx cocatalyst. This causes the creation of electron-enriched Mo(4 – δ)+ sites and an increase in the antibonding-orbital occupancy of Mo–Oads, ultimately weakening the Mo–Oads bond and enabling high activity in H2O2 production. This study provides valuable insights into optimizing reactant adsorption for efficient artificial photosynthesis.    

    

* Stereospecific and Stereodivergent Allyl–Allyl Coupling: Construction of Vicinal Tertiary and All-Carbon Quaternary Stereocenters  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405106290
:TOPICS: Asymmetric Synthesis and Catalysis, Synthetic Organic Chemistry Methods, Chemical synthesis and alkaloids
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06203")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405106290"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405106290"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405106290"))][Get cited by]]

OpenAlex: https://openalex.org/W4405106290 (Open access: False)
    
[[https://openalex.org/A5031544301][Yongsuk Jung]], [[https://openalex.org/A5100413012][Jieun Kim]], [[https://openalex.org/A5011345696][G.N. Kim]], [[https://openalex.org/A5112065623][Jeong Wan Ko]], [[https://openalex.org/A5044287208][Sungwoo Hong]], [[https://openalex.org/A5030673319][Seung Hwan Cho]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06203 
     
No abstract    

    

* Bifunctional Photocatalysts Display Proximity-Enhanced Catalytic Activity in Metallaphotoredox C–O Coupling  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405107662
:TOPICS: Radical Photochemical Reactions, Oxidative Organic Chemistry Reactions, Advanced Photocatalysis Techniques
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05893")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405107662"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405107662"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405107662"))][Get cited by]]

OpenAlex: https://openalex.org/W4405107662 (Open access: False)
    
[[https://openalex.org/A5069999688][Luigi Dolcini]], [[https://openalex.org/A5107567512][Andrea Solida]], [[https://openalex.org/A5107402798][Daniele Lavelli]], [[https://openalex.org/A5107402799][Andrés Mauricio Hidalgo-Núñez]], [[https://openalex.org/A5070712730][Tommaso Gandini]], [[https://openalex.org/A5033994385][Matthieu Fornara]], [[https://openalex.org/A5102584253][Alessandro Colella]], [[https://openalex.org/A5063584845][Alberto Bossi]], [[https://openalex.org/A5018432174][Marta Penconi]], [[https://openalex.org/A5079142494][Daniele Fiorito]], [[https://openalex.org/A5019442123][Cesare Gennari]], [[https://openalex.org/A5023881545][Alberto Dal Corso]], [[https://openalex.org/A5031541703][Luca Pignataro]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05893 
     
No abstract    

    

* Analogy in the Mechanism of Heterolytic H2 Dissociation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405109345
:TOPICS: Advanced Chemical Physics Studies, Ammonia Synthesis and Nitrogen Reduction, Quantum, superfluid, helium dynamics
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05629")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405109345"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405109345"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405109345"))][Get cited by]]

OpenAlex: https://openalex.org/W4405109345 (Open access: False)
    
[[https://openalex.org/A5101760202][Ping Jin]], [[https://openalex.org/A5029421795][Nengchao Luo]], [[https://openalex.org/A5038772372][Feng Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05629 
     
No abstract    

    

* Photocatalytic Multicomponent Carboxylation of Olefins and Sulfinate Salts with 13CO2  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405109917
:TOPICS: Carbon dioxide utilization in catalysis, Chemical Synthesis and Reactions, Sulfur-Based Synthesis Techniques
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06335")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405109917"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405109917"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405109917"))][Get cited by]]

OpenAlex: https://openalex.org/W4405109917 (Open access: False)
    
[[https://openalex.org/A5020998193][Julien R. Lyonnet]], [[https://openalex.org/A5030466505][Álvaro Velasco‐Rubio]], [[https://openalex.org/A5028736854][Roman Abrams]], [[https://openalex.org/A5073798086][Duc-Ha Phan-Vu]], [[https://openalex.org/A5091117270][Kim S. Mühlfenzl]], [[https://openalex.org/A5101909990][Xuemeng Chen]], [[https://openalex.org/A5059606474][Alessandro Cerveri]], [[https://openalex.org/A5023599993][José Tiago Menezes Correia]], [[https://openalex.org/A5020914880][Márcio W. Paixão]], [[https://openalex.org/A5038118766][Charles S. Elmore]], [[https://openalex.org/A5004700113][Rubén Martı́n]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06335 
     
Herein, we describe a photoinduced multicomponent catalytic carboxylation protocol that streamlines the access to 13C-labeled carboxylic acids from simple olefin precursors, sulfinate salts and 13CO2. Site selectivity is dictated by the radical philicity of the starting precursors and reaction intermediates, resulting in either a four-component or a five-component endeavor. The method is characterized by its simplicity and flexibility across a wide number of coupling counterparts    

    

* Nanocrystalline High-Dimensional Nb2O5 for Efficient Electroreductive Dicarboxylation of CO2 with Cycloalkane  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405110494
:TOPICS: Carbon dioxide utilization in catalysis, CO2 Reduction Techniques and Catalysts, Advanced Photocatalysis Techniques
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06490")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405110494"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405110494"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405110494"))][Get cited by]]

OpenAlex: https://openalex.org/W4405110494 (Open access: False)
    
[[https://openalex.org/A5102809665][Yuanming Xie]], [[https://openalex.org/A5100639857][Xuelin Wang]], [[https://openalex.org/A5016114882][Junjun Mao]], [[https://openalex.org/A5100408854][Chenchen Zhang]], [[https://openalex.org/A5102172292][Qingqing Song]], [[https://openalex.org/A5025940540][Toru Murayama]], [[https://openalex.org/A5101477421][M. C. Lin]], [[https://openalex.org/A5004645356][Jiawei Zhang]], [[https://openalex.org/A5012006645][Yang Lou]], [[https://openalex.org/A5065654129][Chengsi Pan]], [[https://openalex.org/A5101723568][Ying Zhang]], [[https://openalex.org/A5004893546][Yongfa Zhu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06490 
     
No abstract    

    

* Improvement of CO2 Reduction Photocatalysis of a Ru(II)–Re(I) Complex and Carbon Nitride Hybrid by Coadsorption of an Os(II) Complex Photosensitizer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405112143
:TOPICS: CO2 Reduction Techniques and Catalysts, Advanced Photocatalysis Techniques, Nanocluster Synthesis and Applications
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06134")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405112143"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405112143"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405112143"))][Get cited by]]

OpenAlex: https://openalex.org/W4405112143 (Open access: True)
    
[[https://openalex.org/A5104017287][Toshiya Tanaka]], [[https://openalex.org/A5020795480][Mitsuhiko Shizuno]], [[https://openalex.org/A5085783586][Yusuke Tamaki]], [[https://openalex.org/A5058951596][Kazuhiko Maeda]], [[https://openalex.org/A5070733375][Osamu Ishitani]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06134 
     
No abstract    

    

* Light-Driven Hybrid Nanoreactor Harnessing the Synergy of Carboxysomes and Organic Frameworks for Efficient Hydrogen Production  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405113641
:TOPICS: Metal-Organic Frameworks: Synthesis and Applications, Electrocatalysts for Energy Conversion, Catalytic Processes in Materials Science
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03672")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405113641"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405113641"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405113641"))][Get cited by]]

OpenAlex: https://openalex.org/W4405113641 (Open access: True)
    
[[https://openalex.org/A5023691773][Jing Yang]], [[https://openalex.org/A5027203237][Qiuyao Jiang]], [[https://openalex.org/A5100401944][Yu Chen]], [[https://openalex.org/A5100687073][Quan Wen]], [[https://openalex.org/A5113355567][Xingwu Ge]], [[https://openalex.org/A5042353045][Qiang Zhu]], [[https://openalex.org/A5026789421][Wei Zhao]], [[https://openalex.org/A5022172017][Oluwatobi Samuel Adegbite]], [[https://openalex.org/A5028124766][Haofan Yang]], [[https://openalex.org/A5112186510][Liang Luo]], [[https://openalex.org/A5092784527][Hang Qu]], [[https://openalex.org/A5115031799][Veronica Del-Angel-Hernandez]], [[https://openalex.org/A5010858274][Rob Clowes]], [[https://openalex.org/A5100647288][Jun Gao]], [[https://openalex.org/A5075000824][Marc A. Little]], [[https://openalex.org/A5060033823][Andrew I. Cooper]], [[https://openalex.org/A5041021580][Lu‐Ning Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03672 
     
Synthetic photobiocatalysts are promising catalysts for valuable chemical transformations by harnessing solar energy inspired by natural photosynthesis. However, the synergistic integration of all of the components for efficient light harvesting, cascade electron transfer, and efficient biocatalytic reactions presents a formidable challenge. In particular, replicating intricate multiscale hierarchical assembly and functional segregation involved in natural photosystems, such as photosystems I and II, remains particularly demanding within artificial structures. Here, we report the bottom-up construction of a visible-light-driven chemical–biological hybrid nanoreactor with augmented photocatalytic efficiency by anchoring an α-carboxysome shell encasing [FeFe]-hydrogenases (H–S) on the surface of a hydrogen-bonded organic molecular crystal, a microporous α-polymorph of 1,3,6,8-tetra(4′-carboxyphenyl)pyrene (TBAP-α). The self-association of this chemical–biological hybrid system is facilitated by hydrogen bonds, as revealed by molecular dynamics simulations. Within this hybrid photobiocatalyst, TBAP-α functions as an antenna for visible-light absorption and exciton generation, supplying electrons for sacrificial hydrogen production by H–S in aqueous solutions. This coordination allows the hybrid nanoreactor, H–S|TBAP-α, to execute hydrogen evolution exclusively driven by light irradiation with a rate comparable to that of photocatalyst-loaded precious cocatalyst. The established approach to constructing new light-driven biocatalysts combines the synergistic power of biological nanotechnology with the multilength-scale structure and functional control offered by supramolecular organic semiconductors. It opens up innovative opportunities for the fabrication of biomimetic nanoreactors for sustainable fuel production and enzymatic reactions.    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405120090
:TOPICS: 
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i023_1874629")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405120090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405120090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405120090"))][Get cited by]]

OpenAlex: https://openalex.org/W4405120090 (Open access: False)
    
, ACS Catalysis. 14(23)] 2024. https://doi.org/10.1021/csv014i023_1874629 
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405121157
:TOPICS: 
:PUBLICATION_DATE: 2024-12-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i023_1874630")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405121157"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405121157"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405121157"))][Get cited by]]

OpenAlex: https://openalex.org/W4405121157 (Open access: False)
    
, ACS Catalysis. 14(23)] 2024. https://doi.org/10.1021/csv014i023_1874630 
     
No abstract    

    

* Surface Nanosteps Modulate the Local Environment of Co Single Atoms to Boost the Electrocatalytic Hydrogen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405136849
:TOPICS: Electrocatalysts for Energy Conversion, Electrochemical Analysis and Applications, CO2 Reduction Techniques and Catalysts
:PUBLICATION_DATE: 2024-12-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05624")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405136849"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405136849"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405136849"))][Get cited by]]

OpenAlex: https://openalex.org/W4405136849 (Open access: False)
    
[[https://openalex.org/A5101195596][Sheng Qian]], [[https://openalex.org/A5061360949][Tengfei Jiang]], [[https://openalex.org/A5100649620][Junhua Wang]], [[https://openalex.org/A5086459194][Wenzhi Yuan]], [[https://openalex.org/A5110827512][Dailing Jia]], [[https://openalex.org/A5021692036][Ningyan Cheng]], [[https://openalex.org/A5101034995][Huaiguo Xue]], [[https://openalex.org/A5106300176][Zhongfei Xu]], [[https://openalex.org/A5114376025][Romain Gautier]], [[https://openalex.org/A5056556778][Jingqi Tian]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05624 
     
No abstract    

    
