#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sat Jan  4 01:19:24 2025

Found 15 results from 2024-12-28 to 2025-01-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Triethoxysilane-Catalyzed Single and Sequential Regioselective Hydroboration of Terminal Alkynes: Sustainable Access to E-Alkenylboronate and Alkyl Gem-Diboronate Esters by Non-Covalent Interactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405973307
:TOPICS: Organoboron and organosilicon chemistry, Chemical Synthesis and Analysis, Asymmetric Hydrogenation and Catalysis
:PUBLICATION_DATE: 2025-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06845")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405973307"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405973307"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405973307"))][Get cited by]]

OpenAlex: https://openalex.org/W4405973307 (Open access: False)
    
[[https://openalex.org/A5111032542][Harleen Kaur]], [[https://openalex.org/A5037730598][Himani Ahuja]], [[https://openalex.org/A5016064847][Rebeca Arévalo]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06845 
     
No abstract    

    

* Regulating Heteroatom Doping-Induced Embedded Pt-M Bimetallic Sites Coupled with Ce3+-OVs for Efficient Low-Temperature Methanol Steam Reforming  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405991185
:TOPICS: Catalytic Processes in Materials Science, Catalysts for Methane Reforming, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05507")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405991185"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405991185"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405991185"))][Get cited by]]

OpenAlex: https://openalex.org/W4405991185 (Open access: False)
    
[[https://openalex.org/A5101624169][Wei Zheng]], [[https://openalex.org/A5090847139][Shengfang Shi]], [[https://openalex.org/A5068536978][Fei Dong]], [[https://openalex.org/A5076254456][Hekun Jia]], [[https://openalex.org/A5107657755][Zhiling Chen]], [[https://openalex.org/A5003538933][Bifeng Yin]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05507 
     
No abstract    

    

* Hydrogen Evolution and Oxygen Reduction on OH/F-Terminated Titanium Nitride MXene Reveal the Role of the Surface Termination Group in Electrocatalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405994823
:TOPICS: MXene and MAX Phase Materials, Advanced Photocatalysis Techniques, Advanced Memory and Neural Computing
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05247")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405994823"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405994823"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405994823"))][Get cited by]]

OpenAlex: https://openalex.org/W4405994823 (Open access: True)
    
[[https://openalex.org/A5075083911][Eugenie Pranada]], [[https://openalex.org/A5019655814][Bright Ngozichukwu]], [[https://openalex.org/A5038104345][Ray Yoo]], [[https://openalex.org/A5023017337][Denis Johnson]], [[https://openalex.org/A5031920355][Mark A. Barteau]], [[https://openalex.org/A5038398773][Ahmed Abdel‐Wahab]], [[https://openalex.org/A5021880950][Abdoulaye Djire]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05247 
     
No abstract    

    

* Advances and Challenges for Catalytic Recycling and Upgrading of Real-World Mixed Plastic Waste  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405843775
:TOPICS: Recycling and Waste Management Techniques, Microplastics and Plastic Pollution, Additive Manufacturing and 3D Printing Technologies
:PUBLICATION_DATE: 2024-12-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06344")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405843775"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405843775"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405843775"))][Get cited by]]

OpenAlex: https://openalex.org/W4405843775 (Open access: False)
    
[[https://openalex.org/A5011229071][Yawen Shi]], [[https://openalex.org/A5059620811][Xinyong Diao]], [[https://openalex.org/A5033986934][Na Ji]], [[https://openalex.org/A5102482212][Hu Ding]], [[https://openalex.org/A5017640332][Zongyang Ya]], [[https://openalex.org/A5085263496][Dong Xu]], [[https://openalex.org/A5100618502][Rui Wei]], [[https://openalex.org/A5005782389][Kejiang Cao]], [[https://openalex.org/A5045637364][Shengbo Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06344 
     
No abstract    

    

* Modulating the Selectivity of CO2 Photoreduction by Regulating the Location of PtCu in a UiO-66@ZnIn2S4 Core–Shell Nanoreactor  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405853698
:TOPICS: Advanced Photocatalysis Techniques, Gas Sensing Nanomaterials and Sensors, Copper-based nanomaterials and applications
:PUBLICATION_DATE: 2024-12-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05717")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405853698"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405853698"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405853698"))][Get cited by]]

OpenAlex: https://openalex.org/W4405853698 (Open access: False)
    
[[https://openalex.org/A5084432276][Zengrong Li]], [[https://openalex.org/A5100396151][Peng Wang]], [[https://openalex.org/A5101430724][Chun-Xia Ren]], [[https://openalex.org/A5039487548][Linyi Wu]], [[https://openalex.org/A5103153947][Yue Yao]], [[https://openalex.org/A5037678225][Shuxian Zhong]], [[https://openalex.org/A5107980754][Hongjun Lin]], [[https://openalex.org/A5056196238][Leihong Zhao]], [[https://openalex.org/A5037410761][Yijing Gao]], [[https://openalex.org/A5011190440][Song Bai]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05717 
     
No abstract    

    

* Constructing Ordered Oxophilic Tin Sites on Platinum to Achieve a High-Performance and Anti-CO Poisoning Hydrogen Oxidation Reaction under an Alkaline Electrolyte  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405867615
:TOPICS: Electrocatalysts for Energy Conversion, Catalytic Processes in Materials Science, Advanced battery technologies research
:PUBLICATION_DATE: 2024-12-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06469")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405867615"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405867615"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405867615"))][Get cited by]]

OpenAlex: https://openalex.org/W4405867615 (Open access: False)
    
[[https://openalex.org/A5104120338][Chaoyi Yang]], [[https://openalex.org/A5051536788][Guangqin Wang]], [[https://openalex.org/A5081310019][Jianchao Yue]], [[https://openalex.org/A5077311986][Zhifeng Dai]], [[https://openalex.org/A5062213729][Wei Luo]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06469 
     
No abstract    

    

* Unlocking the Substrate Acceptance of Phenylalanine Amine Dehydrogenase Enables the Asymmetric Synthesis of Pharmaceutical N-Heterocyclic Primary Amines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405883541
:TOPICS: Enzyme Catalysis and Immobilization, Chemical Synthesis and Analysis, Biochemical and Molecular Research
:PUBLICATION_DATE: 2024-12-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06478")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405883541"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405883541"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405883541"))][Get cited by]]

OpenAlex: https://openalex.org/W4405883541 (Open access: False)
    
[[https://openalex.org/A5101525600][Tao Wu]], [[https://openalex.org/A5087324294][Yao Nie]], [[https://openalex.org/A5103159262][Jiaxing Xu]], [[https://openalex.org/A5062611477][Xiaoqing Mu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06478 
     
N-Heterocyclic primary amines are highly valuable and recurrent synthons in the pharmaceutical industry. Amine dehydrogenase (AmDH)-catalyzed direct asymmetric reductive amination of the readily available N-heterocyclic ketones represents a promising approach for synthesizing N-heterocyclic primary amines. However, the limited substrate acceptance of AmDHs restricts their application in reductive amination. In this endeavor, we unlocked the substrate acceptance of phenylalanine amine dehydrogenase from Bacillus badius (F-BbAmDH) to access a panel of N-Boc-substituted heterocyclic ketones with a broad range of structural features. Based on the combination of a reverse substrate design strategy and structural-guided steric hindrance mutagenesis, two active F-BbAmDH mutants with expanded N-heterocyclic ketone specificity toward N-Boc-3-piperidone were generated, and two rounds of additional iterative site mutagenesis further increased the catalytic activity by 143.4-fold. The optimal triple mutant M3-2 displayed a significantly extended scope of N-Boc-substituted heterocyclic ketones, and its practical asymmetric synthesis performance was confirmed in the gram-scale synthesis of the key intermediate of alogliptin, (R)-1-Boc-3-piperidinamine, achieving >99% ee, 86% conversion, and 80% (4.0 g) isolated yield. This work lays the foundation for the biocatalytic synthesis of structurally diverse N-heterocyclic primary amines and gives referable guidance for engineering oxidoreductases sharing an analogous pocket into versatile biocatalysts.    

    

* Structural Insights into Novel Thiolases for Enhancing the Production of Tailored Biochemicals  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405892706
:TOPICS: Enzyme function and inhibition, Synthesis and Characterization of Heterocyclic Compounds, Biochemical and Molecular Research
:PUBLICATION_DATE: 2024-12-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05635")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405892706"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405892706"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405892706"))][Get cited by]]

OpenAlex: https://openalex.org/W4405892706 (Open access: False)
    
[[https://openalex.org/A5103944944][Jiyeon Hong]], [[https://openalex.org/A5016068844][Hyeoncheol Francis Son]], [[https://openalex.org/A5100417971][Soyoung Park]], [[https://openalex.org/A5000973344][Jiyoung Park]], [[https://openalex.org/A5048830775][Hogyun Seo]], [[https://openalex.org/A5065474597][Kwang‐Hyeon Liu]], [[https://openalex.org/A5100671815][Kyung‐Jin Kim]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05635 
     
Thiolase is essential in the first step of synthesizing many value-added biochemicals. However, only a few feasible THLs have been reported, and a limited understanding of these enzymes has restricted their broader application in valuable production processes. In this study, biochemical and structural analysis identified the specific properties of THLs belonging to three groups for synthesizing medium- to long-chain fatty acids, polyketide, and dicarboxylic acid, represented by adipic acid. We further demonstrated that hydrolysis activity, considered a rate-limiting step in the biosynthetic process, can be alleviated through flux balance and site-directed mutagenesis. Notably, we discovered two THLs with strong biosynthetic abilities and low hydrolysis: PaTHL4, effective for medium- to long-chain fatty acids and polyketides, and PaTHL7, tailored for adipic acid production. This study provides valuable insights into tailored THLs for specific biochemical production.    

    

* Bioinformatics and Computationally Supported Redesign of Aspartase for β-Alanine Synthesis by Acrylic Acid Hydroamination  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405896055
:TOPICS: Enzyme Structure and Function, Biochemical and Molecular Research, Diet, Metabolism, and Disease
:PUBLICATION_DATE: 2024-12-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05525")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405896055"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405896055"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405896055"))][Get cited by]]

OpenAlex: https://openalex.org/W4405896055 (Open access: True)
    
[[https://openalex.org/A5008894842][Alejandro Gran‐Scheuch]], [[https://openalex.org/A5040139581][Hein J. Wijma]], [[https://openalex.org/A5032943526][Nikolas Capra]], [[https://openalex.org/A5009460713][Hugo L. van Beek]], [[https://openalex.org/A5084669242][Miloš Trajković]], [[https://openalex.org/A5068574859][Kai Baldenius]], [[https://openalex.org/A5059755170][Michael Breuer]], [[https://openalex.org/A5087468780][A.M.W.H. Thunnissen]], [[https://openalex.org/A5076930474][Dick B. Janssen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05525 
     
Aspartate ammonia lyases catalyze the reversible amination of fumarate to l-aspartate. Recent studies demonstrate that the thermostable enzyme from Bacillus sp. YM55–1 (AspB) can be engineered for the enantioselective production of substituted β-amino acids. This reaction would be attractive for the conversion of acrylic acid to β-alanine, which is an important building block for the preparation of bioactive compounds. Here we describe a bioinformatics and computational approach aimed at introducing the β-alanine synthesis activity. Three strategies were used: First, we redesigned the α-carboxylate binding pocket of AspB to introduce activity with the acrylic acid. Next, different template enzymes were identified by genome mining, equipped with a redesigned α-carboxylate pocket, and investigated for β-alanine synthesis, which yielded variants with better activity. Third, interactions of the SS-loop that covers the active site and harbors a catalytic serine were computationally redesigned using energy calculations to stabilize reactive conformations and thereby further increase the desired β-alanine synthesis activity. Different improved enzymes were obtained and the best variants showed kcat values with acrylic acid of at least 0.6–1.5 s–1 with KM values in the high mM range. Since the β-alanine production of wild-type enzyme was below the detection limit, this suggests that the kcat/Km was improved by at least 1000-fold. Crystal structures of the 6-fold mutant of redesigned AspB and the similarly engineered aspartase from Caenibacillus caldisaponilyticus revealed that their ligand-free structures have the SS-loop in a closed (reactive) conformation, which for wild-type AspB is only observed in the substrate-bound enzyme. AlphaFold-generated models suggest that other aspartase variants redesigned for acrylic acid hydroamination also prefer a 3D structure with the loop in a closed conformation. The combination of binding pocket redesign, genome mining, and enhanced active-site loop closure thus created effective β-alanine synthesizing variants of aspartase.    

    

* Monitoring Radical Intermediates in Photoactivated Palladium-Catalyzed Coupling of Aryl Halides to Arenes by an Aryl Radical Assay  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405908083
:TOPICS: Radical Photochemical Reactions, Catalytic C–H Functionalization Methods, Sulfur-Based Synthesis Techniques
:PUBLICATION_DATE: 2024-12-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06913")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405908083"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405908083"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405908083"))][Get cited by]]

OpenAlex: https://openalex.org/W4405908083 (Open access: True)
    
[[https://openalex.org/A5091956203][Seb Tyerman]], [[https://openalex.org/A5109804276][Donald Mackay]], [[https://openalex.org/A5010754912][Kenneth Clark]], [[https://openalex.org/A5041199149][Alan R. Kennedy]], [[https://openalex.org/A5090644105][Craig M. Robertson]], [[https://openalex.org/A5059225947][Laura Evans]], [[https://openalex.org/A5015996956][Robert M. Edkins]], [[https://openalex.org/A5038338444][John A. Murphy]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06913 
     
No abstract    

    

* Nickel-Catalyzed Synthesis of Silaindanes via Sequential C–H Activating 1,5-Nickel Migration and C–Si Activating 1,4-Nickel Migration  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405908160
:TOPICS: Catalytic C–H Functionalization Methods, Catalytic Cross-Coupling Reactions, Organoboron and organosilicon chemistry
:PUBLICATION_DATE: 2024-12-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06910")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405908160"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405908160"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405908160"))][Get cited by]]

OpenAlex: https://openalex.org/W4405908160 (Open access: False)
    
[[https://openalex.org/A5100724475][Donghyeon Lee]], [[https://openalex.org/A5113249474][Ikuya Fujii]], [[https://openalex.org/A5015816816][Ryo Shintani]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06910 
     
No abstract    

    

* Site-Specific Introduction of Sulfoxides and Sulfones into Polyketide Scaffolds through a Relayed Chemo-Biosynthetic Strategy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405912420
:TOPICS: Sulfur-Based Synthesis Techniques, Chemical Synthesis and Reactions, Microbial Natural Products and Biosynthesis
:PUBLICATION_DATE: 2024-12-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05446")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405912420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405912420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405912420"))][Get cited by]]

OpenAlex: https://openalex.org/W4405912420 (Open access: False)
    
[[https://openalex.org/A5100433153][Jun Zhang]], [[https://openalex.org/A5059787539][Xiaodong Zeng]], [[https://openalex.org/A5052082332][Huixue Chen]], [[https://openalex.org/A5034338159][Yun Qian]], [[https://openalex.org/A5022926058][Wenya Tian]], [[https://openalex.org/A5113876393][Ye‐Qing Du]], [[https://openalex.org/A5101577471][Zhi Lin]], [[https://openalex.org/A5111994677][Chun Lei]], [[https://openalex.org/A5107927264][Zixin Deng]], [[https://openalex.org/A5018336786][Xudong Qu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05446 
     
Sulfoxides and sulfones are pivotal pharmacophores and versatile functional groups in drug design; however, they are rarely found in natural products. In this study, we developed a chemo-biosynthetic strategy for the site-specific introduction of sulfoxides and sulfones into polyketide frameworks. This method involves integrating hydrophobic sulfide-extender units into the polyketide structure, followed by sequential oxidation with hydrogen peroxide to convert the sulfides into polar sulfoxides and sulfones. This approach addresses the challenge that polar groups face in being recognized by the natural hydrophobic pockets of biosynthetic enzymes. The sulfide-extender units were synthesized using a permissive acyl-CoA synthetase (UkaQFAV) and an acyl-CoA carboxylase (Arm13-ACC), which is specific to medium- to long-chain acyl-CoA substrates. The crystal structure of Arm13 was resolved to 1.6 Å, enabling the development of the mutant Arm13V157I, which exhibits significantly enhanced catalytic efficiency for short-chain acyl-CoA substrates. By incorporating these units into a deacyl antimycin (DA)-producing strain and feeding it sulfur-containing substrates, followed by oxidation, we successfully generated nine representative sulfone and sulfoxide-DAs. This work not only paves the way for the development of sulfur-containing polyketides but also provides an effective strategy for introducing polar functionalities into polyketide frameworks.    

    

* Redox-Activated Supersaturation of Ceria Solid Solution as a Dynamic Catalyst Enabling Low-Temperature Ethylbenzene Oxidative Dehydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405924773
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Catalysis and Hydrodesulfurization Studies
:PUBLICATION_DATE: 2024-12-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05793")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405924773"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405924773"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405924773"))][Get cited by]]

OpenAlex: https://openalex.org/W4405924773 (Open access: False)
    
[[https://openalex.org/A5029517067][Juping Zhang]], [[https://openalex.org/A5029244026][Wenpei Gao]], [[https://openalex.org/A5062190734][Kunran Yang]], [[https://openalex.org/A5086027530][Junchen Liu]], [[https://openalex.org/A5037354460][Yanping Zheng]], [[https://openalex.org/A5087130084][Kun Yang]], [[https://openalex.org/A5100460074][Chao Zhang]], [[https://openalex.org/A5000215848][Kongzhai Li]], [[https://openalex.org/A5014921770][Kun Zhao]], [[https://openalex.org/A5100403970][Hua Wang]], [[https://openalex.org/A5053943428][Yunfei Gao]], [[https://openalex.org/A5088345844][Xing Zhu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05793 
     
Dynamic structural changes in the reactive environment often lead to catalyst deactivation in the thermal-catalysis field. Taking advantage of the dynamic changes in bulk phases, interfaces, and surface structures to design highly active catalysts is a unique but important strategy. Herein, we report a supersaturated ceria solid solution catalyst enabling a styrene yield of 91.8% over extended redox cycles at 430 °C in the redox oxidative dehydrogenation (ODH) of ethylbenzene. In-situ characterizations reveal that the oxygen anions (O2–) and transition-metal cations (Fe and Mn) reversibly shuttle through a ceria solid solution (bulk ↔ surface) in a K–Ce0.47Fe0.2Mn0.33O2−δ catalyst during the redox ODH process. The ceria solid solution acts as a dynamic transition-metal cations/oxygen reservoir, creating atomic interfaces of K–Fe–O/K–Mn–O and an oxygen gateway for efficient ethylbenzene ODH. The findings concerning the formation of a supersaturated ceria solid solution and cations, lattice oxygen migration, and the coupling between oxygen donation and catalytic reactions offer new strategies for designing high-performance dynamic catalysts.    

    

* Elucidating the Reaction Mechanism and Deactivation of CO2-Assisted Propane Oxidative Dehydrogenation over VOx/TiO2 Catalysts: A Multiple Operando Spectroscopic Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405944424
:TOPICS: Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science, Oxidative Organic Chemistry Reactions
:PUBLICATION_DATE: 2024-12-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04900")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405944424"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405944424"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405944424"))][Get cited by]]

OpenAlex: https://openalex.org/W4405944424 (Open access: False)
    
[[https://openalex.org/A5045824959][Leon Schumacher]], [[https://openalex.org/A5048343148][Kathrin Hofmann]], [[https://openalex.org/A5028546703][Christian Heß]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04900 
     
The CO2-assisted oxidative dehydrogenation (ODH) of propane is of great technical importance and enables the use (and thus removal from the atmosphere) of CO2, a greenhouse gas, in a value-adding process. Supported vanadium oxide (VOx) catalysts are a promising alternative to more active but toxic chromium oxide catalysts. Despite its common use, TiO2 has not been investigated as a support material for VOx in the CO2–ODH of propane. In this study, we elucidate the interaction between titania (P25) and vanadia in the reaction mechanism by analyzing the reaction network and investigating the catalyst using X-ray diffraction (XRD), multiwavelength Raman, UV–vis and diffuse reflectance IR Fourier transform (DRIFT) spectroscopy. Besides direct and indirect ODH reaction pathways, propane dry reforming (PDR) is identified as a side reaction, which is more prominent on bare titania. The presence of VOx enhances the stability and the selectivity toward propylene by participating in the redox cycle, activating CO2 and leading to a higher rate of regeneration. Additionally, VOx catalyzes the conversion of anatase to rutile, which facilitates CO2 activation, thereby leading to an encapsulation of vanadium. At higher loadings, reducible VOx oligomers are present on the surface, facilitating some PDR, but less than on bare P25. As the main deactivation mechanisms of the catalyst system, we propose the reduction of the titania lattice and the consumption of vanadium, while carbon formation appears to be less relevant. Our results highlight the importance of analyzing the CO2–ODH reaction network and applying a multispectroscopic approach to obtain a detailed mechanistic understanding of CO2-assisted propane ODH over supported VOx catalysts.    

    

* Expedited Synthesis of Axially Chiral 3-Monosilyl and 3,3′-Bis-silyl Biphenols, Binaphthols, and Phosphoramidites Enabled by Catalytic Two-Fold C–H Silylation with a Traceless Acetal Directing Group  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405963253
:TOPICS: Axial and Atropisomeric Chirality Synthesis, Asymmetric Synthesis and Catalysis, Asymmetric Hydrogenation and Catalysis
:PUBLICATION_DATE: 2024-12-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05927")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405963253"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405963253"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405963253"))][Get cited by]]

OpenAlex: https://openalex.org/W4405963253 (Open access: False)
    
[[https://openalex.org/A5057084692][Hiep H. Nguyen]], [[https://openalex.org/A5107376498][Suman Das Adhikary]], [[https://openalex.org/A5111332695][Yao Chung Chang]], [[https://openalex.org/A5115732211][Peter Zotor]], [[https://openalex.org/A5004384865][Junha Jeon]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05927 
     
The design and development of supporting ligands have significantly propelled the discovery of new catalytic reactions and the improvement of existing ones. Among these, axially chiral biphenols and 1,1′-binaphthalene-2,2′-diol (BINOL) are some of the most privileged ligands used in a wide array of enantioselective reactions. Despite the well-established benefits of structural modifications to biphenol and BINOL scaffolds, particularly at their 3,3′-positions─for enhancing reactivity and stereofidelity in catalytic asymmetric transformations─only a limited number of 3,3′-bis-functionalized biphenols and BINOLs are currently available. Here, we report a unified strategy to rapidly access a range of axially chiral 3-monosilyl and 3,3′ bis-silyl-substituted and biphenols and BINOLs as well as their corresponding 3-monosilyl and 3,3′ bis-silyl BINOL-based phosphoramidites. This approach involves traceless acetal-directed, catalytic two-fold C–H silylation of axially chiral biaryls, coupled with selective monoprotodesilylation, expanding the versatility of catalytic C–H functionalization in ligand design and development. Scope studies on the augmentation of the topological space of potentially stereoselectivity-amplifying 3,3′-bis-silyl substituents in axially chiral biphenols and BINOLs were achieved through C–H silylation of biphenols and BINOLs using various dihydrosilanes, as well as the derivatization of 3,3′-silanes, leading to functionalized silane-substituted biphenols and BINOLs. Lastly, the phosphoramidation of newly synthesized 3-monosilyl and 3,3′ bis-silyl BINOL and biphenols with dichlorophosphinamine provided a series of 3-monosilyl and 3,3′ bis-silyl BINOL-based phosphoramidites. The efficiency of this synthetic approach is underscored by its short synthetic steps, expedited reaction times, and minimal purification, making it versatile for the synthesis of a wide array of organosilicon-functionalized axially chiral biaryls and phosphoramidites.    

    
