#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sun Feb  4 23:59:52 2024

Found 25 results from 2024-01-27 to 2024-02-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Theoretical Insights into H2 Activation and Hydrogen Spillover on Near-Surface Alloys with Embedded Single Pt Atoms  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391253549
:TOPICS: Materials and Methods for Hydrogen Storage, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05660")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391253549"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391253549"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391253549"))][Get cited by]]

OpenAlex: https://openalex.org/W4391253549 (Open access: False)
    
[[https://openalex.org/A5042788784][Zefu Tan]], [[https://openalex.org/A5046810720][Jun Chen]], [[https://openalex.org/A5016546361][Sen Lin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05660 
     
Despite extensive studies of hydrogen spillover on single-atom alloy surfaces, a thorough understanding of the structure–activity relationship is still lacking. Here, we investigate H2 dissociation and diffusion of the dissociated H species on the near-surface alloys embedded with single Pt atoms using density functional theory (DFT) calculations and ab initio molecular dynamics (AIMD) simulations. The DFT results indicate that subsurface alloying with early transition metals (X) (Pt1-X/Cu(111)) can generally promote the initial hydrogen spillover but suppress the H2 dissociation process, showing an intractable trade-off effect. While the DFT-calculated H2 dissociation barrier on Pt1-Co/Cu(111) is higher than that on Pt1-Ni/Cu(111), the AIMD results show that the H2 dissociation probability on the Pt1-Co/Cu(111) surface is much higher than that on Pt1-Ni/Cu(111). The trajectory analysis shows that H2 molecules on Pt1-Co/Cu(111) can adopt a more convenient conformation for dissociation when approaching the so-called close-range physisorption zone (CPZ) due to the relatively flat topography of the potential energy surface, thus increasing the H2 dissociation probability compared to the case on Pt1-Ni/Cu(111). This work provides a clear picture for understanding the structure–activity relationships of H2 activation and hydrogen spillover over single-atom catalysts. More importantly, it highlights an overlooked but essential role of the dynamic orientation of the reactant in heterogeneous catalysis.    

    

* Aerobic Alcohol Oxidation with a Cerium–Phenanthrolinedione Complex: A Mimic of Lanthanide-Based Methanol Dehydrogenase  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391254069
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Biological Methane Utilization and Metabolism, Biological and Synthetic Hydrogenases: Mechanisms and Applications
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05428")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391254069"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391254069"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391254069"))][Get cited by]]

OpenAlex: https://openalex.org/W4391254069 (Open access: False)
    
[[https://openalex.org/A5030020949][Duyi Shen]], [[https://openalex.org/A5017654858][Ting Ren]], [[https://openalex.org/A5008148923][Haixing Zhang]], [[https://openalex.org/A5025033841][Mianran Chao]], [[https://openalex.org/A5063357603][Cheng Sun]], [[https://openalex.org/A5069778212][Peiwei Gong]], [[https://openalex.org/A5088180194][Shumiao Zhang]], [[https://openalex.org/A5069214483][Yong Min Lee]], [[https://openalex.org/A5066193981][Shunichi Fukuzumi]], [[https://openalex.org/A5081854202][Wonwoo Nam]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05428 
     
No abstract    

    

* The Missing Link for Electrochemical CO2 Reduction: Classification of CO vs HCOOH Selectivity via PCA, Reaction Pathways, and Coverage Analysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391255963
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04851")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391255963"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391255963"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391255963"))][Get cited by]]

OpenAlex: https://openalex.org/W4391255963 (Open access: False)
    
[[https://openalex.org/A5014378699][Oliver Christensen]], [[https://openalex.org/A5061339044][Alexander Bagger]], [[https://openalex.org/A5083668074][Jan Rossmeisl]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04851 
     
No abstract    

    

* Hydrazine Oxidation Electrocatalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391310056
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05657")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391310056"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391310056"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391310056"))][Get cited by]]

OpenAlex: https://openalex.org/W4391310056 (Open access: False)
    
[[https://openalex.org/A5032610635][Tomer Y. Burshtein]], [[https://openalex.org/A5056010516][Yakov Yasman]], [[https://openalex.org/A5093810554][Lisa Muñoz-Moene]], [[https://openalex.org/A5043992472][José H. Zagal]], [[https://openalex.org/A5041536711][David Eisenberg]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05657 
     
The electro-oxidation of hydrazine is important for direct hydrazine fuel cells and for fundamental understanding of electrocatalysis in the nitrogen cycle. In this Review, we discuss electrocatalysis of the hydrazine oxidation reaction (HzOR), spanning a vast range of metal surfaces, nanoparticles, atomically dispersed ions, organometallic macrocycles, and enzymes. Emphasis is given to structure–activity correlations and reactivity descriptors, including the formulation of the Zagal principle, an electrochemical corollary of the Sabatier principle. In addition, we identify overarching themes that span the different subfields of HzOR electrocatalysis, hoping to inspire cross-disciplinary research avenues.    

    

* Harnessing the “Methyl Effect” in the Development of Novel meta-Directing Template for C–H Cyanation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391318030
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic C-H Amination Reactions, Deuterium Incorporation in Pharmaceutical Research
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04953")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391318030"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391318030"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391318030"))][Get cited by]]

OpenAlex: https://openalex.org/W4391318030 (Open access: False)
    
[[https://openalex.org/A5090848241][Trisha Bhattacharya]], [[https://openalex.org/A5061971502][Chitrala Teja]], [[https://openalex.org/A5034740343][Nikunj Kumar]], [[https://openalex.org/A5088542301][Kanhaiya Kumar Bhagat]], [[https://openalex.org/A5062826786][Goutam Kumar Lahiri]], [[https://openalex.org/A5021247800][Puneet Gupta]], [[https://openalex.org/A5028537817][Sameer Tyagi]], [[https://openalex.org/A5051885484][Debabrata Maiti]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04953 
     
The significance of chelation-assisted C–H functionalization stands upon the superior site-selectivity, easy synthesis, and diverse product utility. In this work, we design a meta-directing scaffold by tuning the side chain of a pyrimidine-based template to attain unconventional site-selectivity in anilines. A simple methyl substitution at the side chain enhances the directing group (DG) efficacy significantly, leading to an almost exclusive meta-selectivity. The current DG further enables a meta-selective cyanation of aniline and its higher homologues irrespective of the substrate electronic bias. The synthetic impact of the methodology is further highlighted with late-stage functionalizations of two very popular local anesthetics butamben and benzocaine. A thorough experimental and in silico study further unfolds the importance of the substitution effect in attaining superior site-selectivity and the role of silver carbonate in the mechanistic cycle.    

    

* Mechanistic Insights into Enantiocontrolling of Styrene Monooxygenase-Catalyzed Epoxidation of Olefins  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391322724
:TOPICS: Enzyme Immobilization Techniques, Metabolic Engineering and Synthetic Biology, Drug Metabolism and Pharmacogenomics
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06328")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391322724"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391322724"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391322724"))][Get cited by]]

OpenAlex: https://openalex.org/W4391322724 (Open access: False)
    
[[https://openalex.org/A5044594907][Hui Lin]], [[https://openalex.org/A5035081565][Shunyan Fang]], [[https://openalex.org/A5037275451][Hang Gao]], [[https://openalex.org/A5074093712][Zhi-lie QIN]], [[https://openalex.org/A5084848491][Donglin Fan]], [[https://openalex.org/A5031315906][Na Li]], [[https://openalex.org/A5033691855][Zhong‐Liu Wu]], [[https://openalex.org/A5062177930][Hongge Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06328 
     
Although styrene monooxygenases (SMOs) are widely used in the production of (S)- or (R)-enantiopure epoxides, the underlying enantiocontrol mechanism of SMO-catalyzed epoxidation remains elusive. Herein, we observed that the substrate-binding pose in the catalytic center, which was codetermined by the residues in the catalytic center and size of the alkyl moiety in the substrates, governed the enantioselectivity of the StyA-catalyzed epoxidation. The mutagenesis of the aromatic residue at site 73 into a nonaromatic residue or that of the nonaromatic residue at site 211 into aromatic residues resulted in the inversion of the enantioselectivity. The variants Y73V, V211F, V211Y, Y73V/V211F, and Y73V/V211Y of the (S)-selective StyA exhibited reversible enantioselectivity during the catalyzed epoxidation of 1-phenylcyclohexene derivatives, yielding the corresponding (R)-epoxides with high enantioselectivity (68–85% ee). Moreover, the (R)-selective variants catalyzed the olefins that harbored large hydrophobic groups, such as 1-phenylcyclohexene derivatives, into their corresponding (R)-epoxides with high enantioselectivity (up to >99% ee). However, these (R)-selective variants retained (S)-selectivity for the epoxidation of styrene, trans-β-methylstyrene, and trans-β-ethylstyrene. The elucidation of the enantiocontrolling mechanism of SMOs would thus be valuable for creating efficient styrene monooxygenases with different enantioselectivities.    

    

* Gold-Catalyzed N-Alkenylation of Isoxazolines and the Use of Alkenyl Gold Intermediates in the Synthesis of 2-Amino-1-pyrrolines  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391323117
:TOPICS: Gold Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05824")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391323117"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391323117"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391323117"))][Get cited by]]

OpenAlex: https://openalex.org/W4391323117 (Open access: False)
    
[[https://openalex.org/A5036280186][Abdullah S. Alshreimi]], [[https://openalex.org/A5079992311][Guanqun Zhang]], [[https://openalex.org/A5049849188][Eun-Kyung Shim]], [[https://openalex.org/A5063130237][Donald J. Wink]], [[https://openalex.org/A5026606130][Laura L. Anderson]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05824 
     
A gold-catalyzed method for N-alkenylation has been developed for NH-isoxazolines, which are challenging substrates for alternative transition-metal-catalyzed N-functionalization reactions. Generation of a vinyl gold intermediate from the addition of NH-isoxazolines to gold-activated ynamides initiates a diastereoselective [3,3′]-sigmatropic rearrangement to give 2-amino-1-pyrrolines. Optimization of this transformation is described, in addition to reaction scope, the use of chiral auxiliaries for the preparation of chiral nonracemic 2-amino-1-pyrrolines, and mechanistic insight. This method prepares heterocycles that are difficult to access through traditional approaches with an enabling gold-catalyzed disconnection.    

    

* Interfacial Spontaneous Reduction Strategy to Synthesize Low-Valent Pt Single-Atom Catalyst for Boosting Hydrosilylation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391338350
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03541")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391338350"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391338350"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391338350"))][Get cited by]]

OpenAlex: https://openalex.org/W4391338350 (Open access: False)
    
[[https://openalex.org/A5074656283][Chan Yang]], [[https://openalex.org/A5024381538][Jinmeng Tong]], [[https://openalex.org/A5056725318][Hailong Li]], [[https://openalex.org/A5059856771][Huiying Gao]], [[https://openalex.org/A5071151916][Guodong Wen]], [[https://openalex.org/A5033115045][Jinsong Zhang]], [[https://openalex.org/A5017315695][Yukun Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c03541 
     
A heterogeneous N-coordinated Pt single-atom catalyst with low valence was synthesized via an “interfacial spontaneous reduction (ISR)” strategy under mild conditions, using cheap and widely available industrial raw materials. The reducing groups were modified onto commercial carbon black XC-72R, which was able to reduce the Pt species at the solid–liquid interface without the need of an extra reducing agent, followed by in situ coordination of the reduced Pt atoms, preventing their aggregation. The prepared Pt single-atom catalyst (Pt1–N–C) acted as an actual reactive center for hydrosilylation and catalyzed the reaction directly, resulting in the absence of an induction period and an ultrahigh turnover frequency of 9.3 × 106 h–1. Moreover, the catalysts can be used on a wide range of olefin and silane substrates, achieving a turnover number of over 4.5 × 106 in the subkilogram-scale reaction. The ISR strategy provides a low-cost method to prepare noble metal single atoms on industrial-grade materials with the potential for large-scale preparation and application.    

    

* Insights into the Confinement Effect of NiMo Catalysts toward Alkaline Hydrogen Oxidation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391348864
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06058")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391348864"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391348864"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391348864"))][Get cited by]]

OpenAlex: https://openalex.org/W4391348864 (Open access: False)
    
[[https://openalex.org/A5042063495][Fulin Yang]], [[https://openalex.org/A5033686868][Shouci Lu]], [[https://openalex.org/A5024509056][Y. Feng]], [[https://openalex.org/A5010542535][Luhong Fu]], [[https://openalex.org/A5008529319][Ligang Feng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06058 
     
Replacing platinum-group metals by Ni-based catalysts for the alkaline hydrogen oxidation reaction (HOR) is highly desired for anion-exchange membrane fuel cells (AEMFCs), while huge challenges still exist due to the sluggish kinetics and oxidative deactivation of the Ni active centers. Herein, we report an ingenious design of the microstructured Ni-based electrocatalysts featured by nanoparticulate NiMo alloy cores encapsulated by N-doped carbon layer shells (NiMo-5%@NC) to address these problems. Electrochemical experiments and theoretical calculations confirm that the confinement effect can rationally weaken the binding energy to oxygenated species through direct interactions with the carbon layers rather than relying on the traditionally regulated electronic structures of NiMo surfaces. This ultimately reduces the energy barrier for water formation, the potential-determining step for the alkaline HOR undergoing the bifunctional path. Moreover, the incorporation of carbon layers not only enhances the passivation resistance of Ni-based surfaces but also alleviates the oxidative dissolution of the alloyed Mo-species, resulting in obviously improved stability. As a result, NiMo-5%@NC exhibits significantly improved HOR activity and stability compared to the counterpart without the protection of the shells (NiMo-5%). This work shows comprehensive insights into the confinement effect exerted by carbon layer shells, providing a different light on the guidelines to deal with the sluggish kinetics and oxidative deactivation of the Ni active centers for AEMFCs.    

    

* Comprehensive Density Functional and Kinetic Monte Carlo Study of CO2 Hydrogenation on a Well-Defined Ni/CeO2 Model Catalyst: Role of Eley–Rideal Reactions  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391361162
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Carbon Dioxide Utilization for Chemical Synthesis
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05336")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391361162"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391361162"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391361162"))][Get cited by]]

OpenAlex: https://openalex.org/W4391361162 (Open access: True)
    
[[https://openalex.org/A5043938385][Pablo Lozano-Reis]], [[https://openalex.org/A5065370507][Pablo Gamallo]], [[https://openalex.org/A5012738512][R. Sayós]], [[https://openalex.org/A5012273051][Francesc Illas]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05336  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05336][pdf]])
     
A detailed multiscale study of the mechanism of CO2 hydrogenation on a well-defined Ni/CeO2 model catalyst is reported that couples periodic density functional theory (DFT) calculations with kinetic Monte Carlo (kMC) simulations. The study includes an analysis of the role of Eley–Rideal elementary steps for the water formation step, which are usually neglected on the overall picture of the mechanism, catalytic activity, and selectivity. The DFT calculations for the chosen model consisting of a Ni4 cluster supported on CeO2 (111) show large enough adsorption energies along with low energy barriers that suggest this catalyst to be a good option for high selective CO2 methanation. The kMC simulations results show a synergic effect between the two 3-fold hollow sites of the supported Ni4 cluster with some elementary reactions dominant in one site, while other reactions prefer the another, nearly equivalent site. This effect is even more evident for the simulations explicitly including Eley–Rideal steps. The kMC simulations reveal that CO is formed via the dissociative pathway of the reverse water–gas shift reaction, while methane is formed via a CO2 → CO → HCO → CH → CH2 → CH3 → CH4 mechanism. Overall, our results show the importance of including the Eley–Rideal reactions and point to small Ni clusters supported on the CeO2 (111) surface as potential good catalysts for high selective CO2 methanation under mild conditions, while very active and selective toward CO formation at higher temperatures.    

    

* Lowering the Coordination of Octahedra in Spinel Oxides by the Robust Fe–N Bonds for Enhancing Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391362025
:TOPICS: Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05344")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391362025"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391362025"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391362025"))][Get cited by]]

OpenAlex: https://openalex.org/W4391362025 (Open access: False)
    
[[https://openalex.org/A5061418233][Yantao Wang]], [[https://openalex.org/A5000364516][Jinzhi Jia]], [[https://openalex.org/A5079262736][Xiaohua Zhao]], [[https://openalex.org/A5062426880][Wenhui Hu]], [[https://openalex.org/A5021987795][Hua Li]], [[https://openalex.org/A5073327563][Xiaowan Bai]], [[https://openalex.org/A5002884743][Junfeng Huang]], [[https://openalex.org/A5047171623][Jinhua Zhang]], [[https://openalex.org/A5052883326][Jian Li]], [[https://openalex.org/A5038927175][Xiaohai Tang]], [[https://openalex.org/A5070724508][Yong Peng]], [[https://openalex.org/A5038255119][Jier Huang]], [[https://openalex.org/A5018390453][Cailing Xu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05344 
     
The coordination environment of octahedra in spinel oxides plays a vital role in regulating the OER performance. But selectively engineering the octahedral units is very challenging for the design of low-cost and high-efficient electrocatalysts. In this work, the low Fe coordinated CoFe2O4 (CoFe2O4–Cd) is successfully obtained by taking advantage of the different bond strength between metal centers and N atoms in 7,7,8,8-tetracyanoquinodimethane-decorated CoFe-MOF-74 (CoFe-MOF-74/TCNQ) and shows promising physical and chemical properties. DFT calculations reveal that the low-coordinated Fe improves the electrochemical symmetry of catalysts and reduces the free energy barrier of the potential-determining step, resulting in the high activity and stability of CoFe2O4–Cd. Systematic experimental and theoretical analyses demonstrate that TCNQ motivates the more electron-occupied states at the Fermi level of CoFe-MOF-74 and enhances the hybridization of Co 3d, Fe 3d, and N 2p, leading to the formation of the Co/Fe–N bond. Owing to the stronger Fe–N bonds, CoFe-MOF-74/TCNQ realizes the step-by-step phase transformation upon electrochemical activation, achieving the CoFe2O4–Cd. This work advances the current comprehension of the controllable regulation of coordination environment of octahedra in spinel oxides, which in turn contributes to the design of high-performance electrocatalysts for OER.    

    

* Nitrogenation and Oxygenation of an Unstrained C–C Bond Enabled by the Merger of Visible-Light and Cu-Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391379480
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis, Transition Metal-Catalyzed Cross-Coupling Reactions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05701")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391379480"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391379480"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391379480"))][Get cited by]]

OpenAlex: https://openalex.org/W4391379480 (Open access: False)
    
[[https://openalex.org/A5079594267][Yu Wang]], [[https://openalex.org/A5011975977][Huan Meng]], [[https://openalex.org/A5066598051][Sifan Li]], [[https://openalex.org/A5030583530][Wei Shu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05701 
     
Unstrained carbon–carbon bonds are among the most prevalent and inert chemical bonds. Thus, developing synthetic transformations directly from unstrained carbon–carbon bonds under mild conditions is ideal yet challenging due to the inertness and steric hindrance. Here, a visible-light and copper-catalyzed azidation and etherification of a remote and unstrained C–C bond of amines via 1,4-aryl migration have been reported. This redox-neutral protocol shows exquisite site-selectivity, broad scope, and good functional group tolerance, directly transforming unstrained C–C bonds to C–N and C–O bonds at room temperature. Facile derivatizations of benzyl azide products into free amines, triazoles, and phosphamides highlight the potential utility of this method for target molecule synthesis and medicinal chemistry.    

    

* Flavin-Mediated Photocatalysis Provides a General Platform for Sulfide C–H Functionalization  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391381968
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Catalytic C-H Amination Reactions, Applications of Photoredox Catalysis in Organic Synthesis
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05785")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391381968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391381968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391381968"))][Get cited by]]

OpenAlex: https://openalex.org/W4391381968 (Open access: True)
    
[[https://openalex.org/A5093827907][Alex S. Anderton]], [[https://openalex.org/A5078112212][Oliver Knowles]], [[https://openalex.org/A5000065563][James A. Rossi‐Ashton]], [[https://openalex.org/A5040225377][David J. Procter]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05785  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05785][pdf]])
     
Functionalized sulfides are important in many areas of science, ranging from chemical biology through drug discovery to organic materials chemistry. Sulfides bearing pendant reactive groups in the α-position are particularly useful; however, methods for the selective valorization of simple sulfides or the late-stage functionalization of complex sulfides by the convenient addition of valuable functionality are underexplored. Here we exemplify a general reaction platform for sulfide functionalization by showcasing three modes of α-sulfur C–H functionalization; cyanation, alkenylation, and alkynylation. Using inexpensive and commercially available riboflavin tetraacetate and visible light, decoration of both feedstock and complex sulfides proceeds in a good yield and with high selectivity. Methionine-containing peptides can also be selectively functionalized and a tolerance screen using amino-acid dopants suggests that the platform is compatible with most amino-acid side chains and thus is a potential tool for bioconjugation.    

    

* Oxygen-18 Labeling Defines a Ferric Peroxide (Compound 0) Mechanism in the Oxidative Deformylation of Aldehydes by Cytochrome P450 2B4  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391383010
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Drug Metabolism and Pharmacogenomics, Metabolic Reprogramming in Cancer Biology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00106")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391383010"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391383010"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391383010"))][Get cited by]]

OpenAlex: https://openalex.org/W4391383010 (Open access: False)
    
[[https://openalex.org/A5080246471][Yasuhiro Tateishi]], [[https://openalex.org/A5042518092][Kevin D. McCarty]], [[https://openalex.org/A5088708740][Martha V. Martin]], [[https://openalex.org/A5058389506][F. Peter Guengerich]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00106 
     
No abstract    

    

* Constructing a Highly Active Pd Atomically Dispersed Catalyst for Cinnamaldehyde Hydrogenation: Synergistic Catalysis between Pd–N3 Single Atoms and Fully Exposed Pd Clusters  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391386420
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05883")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391386420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391386420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391386420"))][Get cited by]]

OpenAlex: https://openalex.org/W4391386420 (Open access: False)
    
[[https://openalex.org/A5022526821][Xin Li]], [[https://openalex.org/A5045960607][Jiaqi Liu]], [[https://openalex.org/A5062636173][Jian Wu]], [[https://openalex.org/A5076495171][Lipeng Zhang]], [[https://openalex.org/A5001966929][Dong Cao]], [[https://openalex.org/A5006520119][Daojian Cheng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05883 
     
No abstract    

    

* Ni-Catalyzed Cyanation of (Hetero)aryl Halides with Acetonitrile as Cyano Source  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391401203
:TOPICS: Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05836")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391401203"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391401203"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391401203"))][Get cited by]]

OpenAlex: https://openalex.org/W4391401203 (Open access: False)
    
[[https://openalex.org/A5052209030][M. Siddique]], [[https://openalex.org/A5077470082][Bing Zeng]], [[https://openalex.org/A5092336971][Ruqiya Qasim]], [[https://openalex.org/A5051769353][Dandan Zheng]], [[https://openalex.org/A5015957505][Qing Zhang]], [[https://openalex.org/A5000254862][Yi Jiang]], [[https://openalex.org/A5016834374][Qifeng Wang]], [[https://openalex.org/A5029086223][Kamel Meguellati]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05836 
     
We present a highly efficient method for cyanating challenging substrates with a specific focus on aryl fluorides. This innovative methodology has been successfully expanded to encompass a diverse array of aryl halides, underscoring its versatility and broad applicability. The nickel-catalyzed protocol utilizes acetonitrile under mild temperature conditions, providing a clean and safe alternative for cyanation. Notably, it employs a nonhazardous, nongaseous, metal-free cyanide source and demonstrates a wide substrate scope, accommodating aryl chlorides, fluorides, bromides, and iodides. The reaction is particularly effective with acetonitrile. This catalytic cyanation process serves as a valuable route for synthesizing pharmaceuticals such as letrozole, citalopram, and other NNRTI drugs. Mechanistically, we propose that a catalytic cycle involving zerovalent nickel and divalent nickel is more plausible for this reaction.    

    

* Design of Advanced Thin-Film Catalysts for Electrooxidation of Formic Acid  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391404712
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05520")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391404712"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391404712"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391404712"))][Get cited by]]

OpenAlex: https://openalex.org/W4391404712 (Open access: False)
    
[[https://openalex.org/A5034117811][Dušan Tripković]], [[https://openalex.org/A5063735085][Dragana Milošević]], [[https://openalex.org/A5016216807][Sanja Stevanović]], [[https://openalex.org/A5027372824][K.Dj. Popović]], [[https://openalex.org/A5080898167][Vladan Jovanović]], [[https://openalex.org/A5050235192][Pietro Papa Lopes]], [[https://openalex.org/A5055560859][Pedro Farinazzo Bergamo Dias Martins]], [[https://openalex.org/A5005598291][Vojislav R. Stamenković]], [[https://openalex.org/A5063468691][Dušan Strmčnik]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05520 
     
Successful development of catalysts for electrochemical formic acid oxidation (FAO) requires finding an optimal balance between catalytic performance (activity, stability, and selectivity) and catalyst cost. While platinum is one of the most active catalyst materials for FAO, it suffers from performance loss at low overpotentials due to poisoning with CO, which is one of the intermediates formed in the so-called indirect path of FAO. In this work, we explored the synergistic effects of the supporting material and annealing temperature on the performance of Pt thin films for FAO in acidic media. Compared to the as-prepared Pt films, the annealed films show up to 5-fold and 15-fold improvement for FAO on Pt@Ni and Pt@Cr, respectively. While the most active Pt@Ni thin film shows the lowest stability, the most active Pt@Cr thin film is also the most stable, challenging conventional trade-offs in electrocatalysis and providing a promising candidate for FAO nanocatalyst synthesis.    

    

* Continuous-Flow Enantioselective Hydrogenative Enyne Cyclization with Chiral Heterogeneous Rh Catalysts  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391248381
:TOPICS: Droplet Microfluidics Technology, Homogeneous Catalysis with Transition Metals, Catalytic Reduction of Nitro Compounds
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391248381"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391248381"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391248381"))][Get cited by]]

OpenAlex: https://openalex.org/W4391248381 (Open access: False)
    
[[https://openalex.org/A5042731264][Yuki Saito]], [[https://openalex.org/A5048421476][Satoshi Yuki]], [[https://openalex.org/A5049553063][Shū Kobayashi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05868 
     
Continuous-flow hydrogenations provide greatly improved reaction efficiency due to the efficient mass-transfer between heterogeneous catalysts and hydrogen gas. However, reported flow hydrogenations were limited to only simple functional group transformations, and the development of sophisticated catalysis such as enantioselective reductive C–C bond formations remains challenging. Herein, we have developed continuous-flow enantioselective cyclization of 1,6-enynes using chiral heterogeneous catalysts supported on heteropoly acid/amine-functionalized SiO2 composites developed in our group. Investigations under continuous-flow conditions revealed that the tuning of the structure of heteropoly acids and amines could improve the catalyst performance. A variety of substrates could produce products with high yields and enantioselectivities under optimized reaction conditions without leaching of the Rh catalyst. Mechanistic studies revealed the cause of catalyst deactivation of this transformation.    

    

* Zinc Blende CoO as an Efficient CO Nondissociative Adsorption Site for Direct Synthesis of Higher Alcohols from Syngas  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391253587
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05579")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391253587"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391253587"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391253587"))][Get cited by]]

OpenAlex: https://openalex.org/W4391253587 (Open access: False)
    
[[https://openalex.org/A5053789239][Zhuoshi Li]], [[https://openalex.org/A5018838816][Guangyuan Luo]], [[https://openalex.org/A5003964217][Zhiwei Hu]], [[https://openalex.org/A5018021055][Xin Pei]], [[https://openalex.org/A5013304309][Zhuang Zeng]], [[https://openalex.org/A5041459154][Shaoxia Guo]], [[https://openalex.org/A5048623668][Jing Lv]], [[https://openalex.org/A5075318509][Shouying Huang]], [[https://openalex.org/A5065841119][Yue Wang]], [[https://openalex.org/A5043956105][Xinbin Ma]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05579 
     
Monometallic Co0–Coδ+ catalysts have shown considerable potential in higher alcohol synthesis (HAS) direct from syngas, however, the alcohol selectivity and catalyst stability still need to be promoted. Here, we prepared a series of cobalt silicate hydroxide-derived catalysts and surprisingly obtained tetrahedrally coordinated zinc blende CoO (Z-CoO) during reduction and reaction. The nanoscale close interacted Co0-Z-CoO achieved an ROH selectivity of 64.4%, a higher alcohol (HA) selectivity of 43.6%, and a space time yield (STY) toward HA of 42.0 mmol·gCo–1·h–1, which outperformed most of the reported Co-based HAS catalysts. In addition, as a contrast, the commonly obtained rocksalt CoO (R-CoO) with octahedral structure was prepared. It is proved that Z-CoO serves as the CO nondissociative adsorption site, which exhibits a much stronger adsorption capability compared to R-CoO and Co2C, greatly facilitating the alcohol formation. Moreover, unlike the R-CoO, there were barely no phase transition of Z-CoO during HAS reaction, contributing to the catalyst stability over 550 h reaction. This work offers a facile preparation method and insights of zinc blende CoO as promising high-performance active sites for HAS.    

    

* Enrichment of Polarized Alkynes over Negatively Charged Pt for Efficient Electrocatalytic Semihydrogenation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391254081
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05646")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391254081"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391254081"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391254081"))][Get cited by]]

OpenAlex: https://openalex.org/W4391254081 (Open access: False)
    
[[https://openalex.org/A5057310526][Xiu Lin]], [[https://openalex.org/A5075393358][Qiyuan Li]], [[https://openalex.org/A5008010079][Siyuan Xia]], [[https://openalex.org/A5085263496][D. Xu]], [[https://openalex.org/A5055190492][Shi‐Nan Zhang]], [[https://openalex.org/A5034303391][Fei Hu]], [[https://openalex.org/A5056809571][Bing-Liang Leng]], [[https://openalex.org/A5067818215][Weiyao Hu]], [[https://openalex.org/A5038732392][Peng Gao]], [[https://openalex.org/A5053710394][Jie‐Sheng Chen]], [[https://openalex.org/A5064771919][Xin‐Hao Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05646 
     
No abstract    

    

* Unlocking Catalytic Diversity of a Formate Dehydrogenase: Formamide Activity for NADPH Regeneration and Amine Supply for Asymmetric Reductive Amination  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391270073
:TOPICS: Enzyme Immobilization Techniques, Amino Acid Transport and Metabolism in Health and Disease, Pancreatic Islet Dysfunction and Regeneration
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05409")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391270073"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391270073"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391270073"))][Get cited by]]

OpenAlex: https://openalex.org/W4391270073 (Open access: True)
    
[[https://openalex.org/A5059230884][Artur Maier]], [[https://openalex.org/A5042518682][Tanja Knaus]], [[https://openalex.org/A5072616467][Francesco G. Mutti]], [[https://openalex.org/A5001303954][Dirk Tischler]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05409  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05409][pdf]])
     
The formate dehydrogenase (FDH) from Candida boidinii is a well-studied and applied enzyme for NADH regeneration in various reactions. As many oxidoreductases require NADPH, FDH mutants were created with shifted cofactor specificity toward NADP+. However, less effort was made to elucidate the substrate specificity for the hydride donors. Here, we report the FDH-catalyzed cleavage of formamide (F) and derivatives thereof into CO2 and amines, while regenerating the cofactors NADH and NADPH. Wild-type FDH and the NADP+-accepting variant FDH C23S/D195Q/Y196R/Q197N (FDH M5) showed both activity with 10% (v/v) F, N-methylformamide (MF), and N,N-dimethylformamide of 80, 67, and 4.5 mU/mg, and 4.9, 4.7, and 0.5 mU/mg, respectively. In silico docking and molecular dynamics simulation gave insights into substrate binding, indicating an altered binding conformation. NADP+-accepting variants were utilized in a cascade set up for the reductive amination of cyclohexanone by means of reductive aminase from Aspergillus oryzae with MF as hydride and amine donor, thereby reaching conversion rates of 72% in a whole cell approach. This work broadens the applicability of FDHs in biocatalysis.    

    

* Mechanistic Investigation of a Photocatalyst Model Reveals Function by Perylene-Like Closed Shell Super-Photoreductant Capable of Reducing Unactivated Arenes  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391313838
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Breath Analysis Technology, Catalytic Oxidation of Alcohols
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05386")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391313838"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391313838"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391313838"))][Get cited by]]

OpenAlex: https://openalex.org/W4391313838 (Open access: False)
    
[[https://openalex.org/A5008850845][Arjun C. Sau]], [[https://openalex.org/A5047621259][Nicholas F. Pompetti]], [[https://openalex.org/A5027116417][Alexander R. Green]], [[https://openalex.org/A5041625174][Mihai V. Popescu]], [[https://openalex.org/A5021610812][Robert S. Paton]], [[https://openalex.org/A5087097153][Garret M. Miyake]], [[https://openalex.org/A5047400818][Niels H. Damrauer]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05386 
     
Benzo[ghi]perylene monoimides (BPIs) have recently been employed as organic photocatalysts for challenging reductions. In probing their function, we identify a thermal degradation product involving imide ring opening, and this in turn motivates the development and synthesis of a high-symmetry model system─a benzo[ghi]perylene diester (BPDE)─whose structural simplicity is useful for mechanistic exploration relevant to the broader photocatalyst class. Using electrochemical and spectroscopic tools, we probe both the singly and doubly reduced states of BPDE and report the generation of [BP-H]–, a two-electron, one-proton activated closed-shell super-reductant. This catalytically active species, after visible photon absorption, operates from its singlet excited state, where the motions of the added proton are coupled to an electron transfer event, which enables direct reduction of inert substrates like benzene and fluorobenzene. Traditional Birch chemistry on benzene has been previously realized only by solvated electrons or electrochemistry. The function of this model system uncovered in these mechanistic explorations suggests modes of operation for this photocatalyst class that will enable future optimizations.    

    

* Functional Assessment of the Lewis Acid Strength of Structurally Complex Solid Acids  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391315694
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Dehydrogenation of Light Alkanes, Applications of Ionic Liquids
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04931")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391315694"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391315694"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391315694"))][Get cited by]]

OpenAlex: https://openalex.org/W4391315694 (Open access: False)
    
[[https://openalex.org/A5013338202][William Thomas Broomhead]], [[https://openalex.org/A5039229575][Ya-Huei Cathy Chin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04931 
     
A 3D linear scaling relation─connecting elementary 2-butanol C–O bond activation enthalpy, pyridine adsorption enthalpy, and the affinity of metal–oxygen site pairs to hydroxyls as reflected in the interaction enthalpy difference─is established here with combined kinetic and chemical titration techniques, allowing for accurate quantitative assessments of the Lewis acid strength even at low site densities in structurally complex metal oxides and nitrides. This construction is a kinetic-thermodynamic free energy relation─using the measured pyridine adsorption enthalpy as a functional descriptor for the electronic chemical potential of the Lewis site (μMO), one could reliably predict its 2-butanol dehydration turnover rate and vice versa. These relations allow for a rapid assessment of the Lewis acid strength on ill-defined solid acid catalysts especially on surfaces containing structural defects with low site densities and those that dynamically reconstruct.    

    

* Stereoblock vs Stereoblend: Orchestrating Competing Living Coordination Chain Transfer Polymerizations for the One-Pot Production of New Viscoelastic Grades of Poly(4-methyl-1-pentene)  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391346144
:TOPICS: Biodegradable Polymers as Biomaterials and Packaging, Living Radical Polymerization, Transition Metal Catalysis
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05570")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391346144"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391346144"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391346144"))][Get cited by]]

OpenAlex: https://openalex.org/W4391346144 (Open access: False)
    
[[https://openalex.org/A5068054889][Danyon M. Fischbach]], [[https://openalex.org/A5086526778][Charlotte M. Wentz]], [[https://openalex.org/A5041076419][S. Paktinat Mehdiabadi]], [[https://openalex.org/A5005700484][João B. P. Soares]], [[https://openalex.org/A5034964331][Lawrence R. Sita]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05570 
     
By exerting control over two populations of coexisting cyclopentadienyl, amidinate (CPAM) group 4 metal active species that possess different stereoselectivities for chain growth propagation during the living coordinative chain transfer polymerization (LCCTP) of 4-methyl-1-pentene, controlled production of grades for poly(4-methyl-1-pentene) (PMP) materials that display a tunable range of viscoelastic properties can be achieved in “one-pot” fashion. Analytical and spectroscopic investigations reveal that these differences in viscoelastic properties are associated with formation of atactic/isotactic PMP stereoblends, rather than a stereoblock chain architecture. These results serve to establish the ability of low molar mass atactic PMP to function as an effective property modifier for commercially important isotactic PMP, which in its pure form is highly brittle with low tensile strength. The further outcome of these studies is extension of multistate LCCTP as a tool for expanding the range of accessible grades and properties of polyolefins that can be produced from the limited small set of industrially significant olefins.    

    

* Deciphering the Role of Internal Donors in Shaping Heterogeneous Ziegler–Natta Catalysts Based on Nonempirical Structural Determination  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391361100
:TOPICS: Transition Metal Catalysis, Accelerating Materials Innovation through Informatics, Biodegradable Polymers as Biomaterials and Packaging
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05480")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391361100"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391361100"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391361100"))][Get cited by]]

OpenAlex: https://openalex.org/W4391361100 (Open access: False)
    
[[https://openalex.org/A5085994654][Juan Pedro Silveira]], [[https://openalex.org/A5057317480][Hiroki Chikuma]], [[https://openalex.org/A5051550176][Gentoku Takasao]], [[https://openalex.org/A5056860372][Toru Wada]], [[https://openalex.org/A5086506896][Patchanee Chammingkwan]], [[https://openalex.org/A5086047381][Toshiaki Taniike]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05480 
     
The addition of internal donors (IDs) to the heterogeneous Ziegler–Natta catalyst for propylene polymerization is fundamental to obtain highly isotactic polypropylene, but its role in shaping the stereospecific structure of the catalyst is still not comprehended. In this work, we apply nonempirical structure determination, based on a genetic algorithm and density functional theory calculations, to ternary systems composing MgCl2, TiCl4, and ID. We found that the copresence of TiCl4 and ID led to the preferential formation of specific surface motifs, involving sharp edges and concavities. This was achieved by concerted adsorption of chelating ID and octahedral TiCl4 and significantly promoted TiCl4 situated in stereospecific environments. The multiplicity of adsorption modes of IDs was found to have a direct consequence on the structural diversity, where phthalate exhibited far greater diversity than 1,3-diether. In conclusion, this study revealed the essentiality of ID-driven reconstruction of MgCl2 in understanding the structure and function of this catalyst.    

    
