#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Thu Feb 22 00:43:19 2024

Found 25 results from 2024-02-15 to 2024-02-22
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* A Water-Promoted Mars−van Krevelen Reaction Dominates Low-Temperature CO Oxidation over Au-Fe2O3 but Not over Au-TiO2  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391806007
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05978")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391806007"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391806007"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391806007"))][Get cited by]]

OpenAlex: https://openalex.org/W4391806007 (Open access: True)
    
[[https://openalex.org/A5013981591][Alexander Holm]], [[https://openalex.org/A5045357923][Bernadette Davies]], [[https://openalex.org/A5026383153][Sara Boscolo Bibi]], [[https://openalex.org/A5000887640][Félix Moncada]], [[https://openalex.org/A5092656027][Joakim Halldin-Stenlid]], [[https://openalex.org/A5092656028][Laurynas Paškevičius]], [[https://openalex.org/A5092656029][Vincent Claman]], [[https://openalex.org/A5004773873][Adam Slabon]], [[https://openalex.org/A5034520322][Cheuk‐Wai Tai]], [[https://openalex.org/A5007728343][Egon Campos dos Santos]], [[https://openalex.org/A5048699879][Sergey Koroidov]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05978  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05978][pdf]])
     
No abstract    

    

* Subnanometer Cu Clusters on Porous Ag Enhancing Ethanol Production in Electrochemical CO2 Reduction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391806039
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03469")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391806039"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391806039"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391806039"))][Get cited by]]

OpenAlex: https://openalex.org/W4391806039 (Open access: False)
    
[[https://openalex.org/A5052152711][Jiwon Park]], [[https://openalex.org/A5073948306][Chaehwa Jeong]], [[https://openalex.org/A5083175433][Moony Na]], [[https://openalex.org/A5043026627][Yusik Oh]], [[https://openalex.org/A5078186897][Kug‐Seung Lee]], [[https://openalex.org/A5060842309][Yongsoo Yang]], [[https://openalex.org/A5063790278][Hye Ryung Byon]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c03469 
     
Controlling the electrochemical CO2 reduction process for multicarbon production is challenging. Ethanol is typically produced with lower selectivity compared to ethylene. In addition, ill-defined catalytic active sites and elusive mechanisms of C–C coupling further hinder the enhancement of ethanol generation. Here, we carefully regulated the quantity of the Cu atoms and deposited them onto a Ag inverse-opal structure (AgIOs) using the pulse-electrodeposition method. Subnanometer Cu clusters demonstrated a 2.5 times higher Faradaic efficiency for ethanol production compared to that for ethylene at −1.05 V vs RHE. Conversely, as the size of Cu increased to nanometers, ethylene became the dominant product. Excessive adsorption of CO on Cu clusters, which migrates from the Ag surface, is attributed to the improved ethanol production. Abundant Ag/Cu boundaries and adjacent spacing between Ag and Cu clusters may enhance the surface migration of CO. In contrast, the preferential site-selective CO adsorption on large Cu nanoparticles is associated with solution-mediated CO migration. Operando shell-isolated nanoparticle-enhanced Raman spectroscopy (SHINERS) revealed a high coverage of the CO on the Cu clusters. The initial intermediate *OCCOH by C–C coupling appeared for both Cu clusters and nanoparticles. However, Cu clusters accommodated more carbonaceous intermediates, highlighting the critical role of CO and intermediate coverages on Cu in ethanol production.    

    

* Energy-Transfer-Enabled Radical Acylation Using Free Alkyl Boronic Acids through Photo and NHC Dual Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391807503
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06027")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391807503"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391807503"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391807503"))][Get cited by]]

OpenAlex: https://openalex.org/W4391807503 (Open access: False)
    
[[https://openalex.org/A5038338910][W.–B. Liu]], [[https://openalex.org/A5031804038][Xiang Zhang]], [[https://openalex.org/A5078143614][Lin Chen]], [[https://openalex.org/A5075090862][Rong Zeng]], [[https://openalex.org/A5042492943][Yu Tian]], [[https://openalex.org/A5021727268][Ernest Ma]], [[https://openalex.org/A5052878834][Yapeng Wang]], [[https://openalex.org/A5046881277][Bin Zhang]], [[https://openalex.org/A5053163012][Jun‐Long Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06027 
     
No abstract    

    

* New Mechanistic Insights into CO2/CO Electroreduction to Acetate by Combining Computations and Experiments  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391807606
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05825")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391807606"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391807606"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391807606"))][Get cited by]]

OpenAlex: https://openalex.org/W4391807606 (Open access: False)
    
[[https://openalex.org/A5073327563][Xiaowan Bai]], [[https://openalex.org/A5075203986][Ming He]], [[https://openalex.org/A5048798891][Yifei Xu]], [[https://openalex.org/A5073687384][Bingjun Xu]], [[https://openalex.org/A5032451131][Qi Lü]], [[https://openalex.org/A5020585562][Jinlan Wang]], [[https://openalex.org/A5007388482][Chongyi Ling]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05825 
     
No abstract    

    

* Beyond Hydrogen Storage: Metal Hydrides for Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391812707
:TOPICS: Materials and Methods for Hydrogen Storage, Ammonia Synthesis and Electrocatalysis, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05696")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391812707"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391812707"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391812707"))][Get cited by]]

OpenAlex: https://openalex.org/W4391812707 (Open access: False)
    
[[https://openalex.org/A5008530846][Haoming Yu]], [[https://openalex.org/A5042080363][Xingguo Li]], [[https://openalex.org/A5053175805][Jianlong Zheng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05696 
     
Metal hydrides (MHs) are featured for their reversible hydrogen absorption and desorption properties, which are conventionally used as hydrogen storage materials. MHs can also be used for catalysis, particularly for chemical reactions that involve hydrogen. This Review summarizes the historical and recent progress in the catalytic application of MHs. The focus topic is how the reversible hydrogen absorption and desorption properties of MHs enable their catalytic effect in hydrogen involving chemical reactions. We start with the basic properties of MHs, and their applications in hydrogen storage and related fields. The application of MHs in four important catalytic reactions: olefin hydrogenation, reversible hydrogen storage in liquid organic hydrogen carriers, CO2 hydrogenation, and NH3 synthesis are discussed. Finally, we compare MH-based catalysts with their analogues, including hydrogen spillover, oxyhydrides, mixed-anion hydrides, and electrides in catalysis. The Review demonstrates the inherent relationship between MH catalysis and their intrinsic hydrogen absorption and desorption properties, providing insights into diverse applications of MHs beyond hydrogen storage.    

    

* Importance of Site Diversity and Connectivity in Electrochemical CO Reduction on Cu  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391821487
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Analysis of Brain Functional Connectivity Networks
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05904")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391821487"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391821487"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391821487"))][Get cited by]]

OpenAlex: https://openalex.org/W4391821487 (Open access: True)
    
[[https://openalex.org/A5044316913][Chansol Kim]], [[https://openalex.org/A5023895763][Nitish Govindarajan]], [[https://openalex.org/A5093526280][Sydney Hemenway]], [[https://openalex.org/A5060549590][Jun Ho Park]], [[https://openalex.org/A5093526281][Anya Zoraster]], [[https://openalex.org/A5091102586][Calton J. Kong]], [[https://openalex.org/A5084951895][Rajiv Ramanujam Prabhakar]], [[https://openalex.org/A5089128933][Joel B. Varley]], [[https://openalex.org/A5002468117][Hee‐Tae Jung]], [[https://openalex.org/A5051674745][Christopher Hahn]], [[https://openalex.org/A5070081966][Joel W. Ager]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05904  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05904][pdf]])
     
Electrochemical CO2 reduction on Cu is a promising approach to produce value-added chemicals using renewable feedstocks, yet various Cu preparations have led to differences in activity and selectivity toward single and multicarbon products. Here, we find, surprisingly, that the effective catalytic activity toward ethylene improves when there is a larger fraction of less active sites acting as reservoirs of *CO on the surface of Cu nanoparticle electrocatalysts. In an adaptation of chemical transient kinetics to electrocatalysis, we measure the dynamic response of a gas diffusion electrode (GDE) cell when the feed gas is abruptly switched between Ar (inert) and CO. When switching from Ar to CO, CO reduction (COR) begins promptly, but when switching from CO to Ar, COR can be maintained for several seconds (delay time) despite the absence of the CO reactant in the gas phase. A three-site microkinetic model captures the observed dynamic behavior and shows that Cu catalysts exhibiting delay times have a less active *CO reservoir that exhibits fast diffusion to active sites. The observed delay times and the estimated *CO reservoir sizes are affected by catalyst preparation, applied potential, and microenvironment (electrolyte cation identity, electrolyte pH, and CO partial pressure). Notably, we estimate that the *CO reservoir surface coverage can be as high as 88 ± 7% on oxide-derived Cu (OD-Cu) at high overpotentials (−1.52 V vs SHE) and this increases in reservoir coverage coincide with increased turnover frequencies to ethylene. We also estimate that *CO can travel substantial distances (up to 10s of nm) prior to desorption or reaction. It appears that active C–C coupling sites by themselves do not control selectivity to C2+ products in electrochemical COR; the supply of CO to those sites is also a crucial factor. More generally, the overall activity of Cu electrocatalysts cannot be approximated from linear combinations of individual site activities. Future designs must consider the diversity of the catalyst network and account for intersite transportation pathways.    

    

* Tuning the CO2 Hydrogenation Activity via Regulating the Strong Metal–Support Interactions of the Ni/Sm2O3 Catalyst  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391823363
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06345")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391823363"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391823363"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391823363"))][Get cited by]]

OpenAlex: https://openalex.org/W4391823363 (Open access: False)
    
[[https://openalex.org/A5034913146][Jianxiong Zhao]], [[https://openalex.org/A5074896161][Xiaozhi Liu]], [[https://openalex.org/A5033870660][Zhengwen Li]], [[https://openalex.org/A5033303258][Kai Feng]], [[https://openalex.org/A5025390487][Yue Pan]], [[https://openalex.org/A5045088389][Pengxiang Ji]], [[https://openalex.org/A5048901189][Kangning Zhao]], [[https://openalex.org/A5047133857][Binhang Yan]], [[https://openalex.org/A5014058024][Dan Zhou]], [[https://openalex.org/A5015415276][Dong Su]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06345 
     
Strong metal–support interactions (SMSIs), characterized by the encapsulation of metal nanoparticles by the support oxide, have a significant impact on various heterogeneous catalytic reactions. In this study, we present our investigations on tuning the catalytic performance of CO2 hydrogenation through regulating the SMSI in a Ni/Sm2O3 catalyst. Our results demonstrate that the complete encapsulation of Ni nanoparticles with amorphous Sm2O3, achieved through H2 reduction, leads to nearly full selectivity to CO. In contrast, with controlled in situ thermal postannealing in an H2/CO2/N2 mixture, the encapsulated Sm2O3 layer can be partially removed and crystallized, as revealed by atomic-resolution transmission electron microscopy analyses, which results in enhanced activity and a full selectivity toward CH4. In addition, the prolonged postannealing durations completely remove the Sm2O3 overlayer, causing a decline in CO2 methanation activity. These findings underscore the critical role of the SMSI effect in CO2 hydrogenation activity and offer valuable insights for regulating SMSI to produce targeted value-added chemicals.    

    

* Correction to “Searching for the Rules of Electrochemical Nitrogen Fixation”  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391823418
:TOPICS: Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00448")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391823418"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391823418"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391823418"))][Get cited by]]

OpenAlex: https://openalex.org/W4391823418 (Open access: True)
    
[[https://openalex.org/A5061575652][Romain Tort]], [[https://openalex.org/A5061339044][Alexander Bagger]], [[https://openalex.org/A5046040902][Olivia Westhead]], [[https://openalex.org/A5033416410][Yasuyuki Kondo]], [[https://openalex.org/A5092649448][Artem Khobnya]], [[https://openalex.org/A5086013761][Anna Winiwarter]], [[https://openalex.org/A5081900881][Bethan J. V. Davies]], [[https://openalex.org/A5035797693][Aron Walsh]], [[https://openalex.org/A5059373986][Yu Katayama]], [[https://openalex.org/A5041044598][Yuki Yamada]], [[https://openalex.org/A5038499496][Mary P. Ryan]], [[https://openalex.org/A5075732110][Maria‐Magdalena Titirici]], [[https://openalex.org/A5039064548][Ifan E. L. Stephens]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00448  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00448][pdf]])
     
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVCorrectionNEXTORIGINAL ARTICLEThis notice is a correctionCorrection to “Searching for the Rules of Electrochemical Nitrogen Fixation”Romain TortRomain TortMore by Romain Tort, Alexander Bagger*Alexander BaggerMore by Alexander Baggerhttps://orcid.org/0000-0002-6394-029X, Olivia WestheadOlivia WestheadMore by Olivia Westhead, Yasuyuki KondoYasuyuki KondoMore by Yasuyuki Kondohttps://orcid.org/0000-0003-1103-3329, Artem KhobnyaArtem KhobnyaMore by Artem Khobnya, Anna WiniwarterAnna WiniwarterMore by Anna Winiwarter, Bethan J. V. DaviesBethan J. V. DaviesMore by Bethan J. V. Davieshttps://orcid.org/0000-0002-3789-8462, Aron WalshAron WalshMore by Aron Walshhttps://orcid.org/0000-0001-5460-7033, Yu KatayamaYu KatayamaMore by Yu Katayamahttps://orcid.org/0000-0002-7842-2938, Yuki YamadaYuki YamadaMore by Yuki Yamadahttps://orcid.org/0000-0002-7191-7129, Mary P. RyanMary P. RyanMore by Mary P. Ryanhttps://orcid.org/0000-0001-8582-3003, Maria-Magdalena TitiriciMaria-Magdalena TitiriciMore by Maria-Magdalena Titiricihttps://orcid.org/0000-0003-0773-2100, and Ifan E. L. Stephens*Ifan E. L. StephensMore by Ifan E. L. StephensCite this: ACS Catal. 2024, 14, XXX, 3169–3170Publication Date (Web):February 14, 2024Publication History Received29 January 2024Published online14 February 2024https://doi.org/10.1021/acscatal.4c00448© 2024 The Authors. Published by American Chemical Society. This publication is licensed under CC-BY 4.0. License Summary*You are free to share (copy and redistribute) this article in any medium or format and to adapt (remix, transform, and build upon) the material for any purpose, even commercially within the parameters below:Creative Commons (CC): This is a Creative Commons license.Attribution (BY): Credit must be given to the creator.View full license*DisclaimerThis summary highlights only some of the key features and terms of the actual license. It is not a license and has no legal value. Carefully review the actual license before using these materials. This publication is Open Access under the license indicated. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (1 MB) Get e-AlertscloseSupporting Info (1)»Supporting Information Supporting Information SUBJECTS:Binding energy,Electrical energy,Elements,Metals,Nitrides Get e-Alerts    

    

* RuO2–CeO2 Lattice Matching Strategy Enables Robust Water Oxidation Electrocatalysis in Acidic Media via Two Distinct Oxygen Evolution Mechanisms  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391836369
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06182")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391836369"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391836369"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391836369"))][Get cited by]]

OpenAlex: https://openalex.org/W4391836369 (Open access: False)
    
[[https://openalex.org/A5010471250][Haoqiang Song]], [[https://openalex.org/A5053714754][Xue Yong]], [[https://openalex.org/A5044592235][Geoffrey I. N. Waterhouse]], [[https://openalex.org/A5000696036][Jingkun Yu]], [[https://openalex.org/A5015576369][Hao Wang]], [[https://openalex.org/A5052291064][Jinmeng Cai]], [[https://openalex.org/A5067430528][Zhiyong Tang]], [[https://openalex.org/A5000046177][Bai Yang]], [[https://openalex.org/A5071937806][Jiangwei Chang]], [[https://openalex.org/A5085836074][Siyu Lu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06182 
     
The discovery of acid-stable and highly active electrocatalysts for the oxygen evolution reaction (OER) is crucial in the quest for high-performance water-splitting technologies. Herein, a heterostructured RuO2–CeO2 electrocatalyst was constructed by using a lattice-matching strategy. The interfacial Ru–O–Ce bridge structure provided a channel for electron transfer between Ru and Ce, creating a lattice stress that distorts the local structure of RuO2. The resulting RuO2–CeO2 catalyst exhibited attractive stability with negligible decay after 1000 h of the OER in 0.5 M H2SO4, along with high activity with an overpotential of only 180 mV at 10 mA cm–2. In situ attenuated total reflectance surface-enhanced infrared absorption spectroscopy (ATR-SEIRAS), in situ differential electrochemical mass spectrometry (DEMS), and density functional theory (DFT) calculations were used to reveal that the interface and noninterface RuO2 sites enabled an oxide path mechanism (OPM) and the enhanced adsorbate evolution mechanism (AEM-plus), respectively, during the OER. The simultaneous and independent OER pathways accessible by lattice matching guides improved electrocatalyst design for the OER in acidic media.    

    

* Sustainable Electrosynthesis of Cyclohexanone Oxime through Nitrate Reduction on a Zn–Cu Alloy Catalyst  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391839397
:TOPICS: Ammonia Synthesis and Electrocatalysis, Content-Centric Networking for Information Delivery, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05388")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391839397"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391839397"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391839397"))][Get cited by]]

OpenAlex: https://openalex.org/W4391839397 (Open access: True)
    
[[https://openalex.org/A5065267485][Jonathan O. Sharp]], [[https://openalex.org/A5050193781][Anna Ciotti]], [[https://openalex.org/A5057093468][Hayley Andrews]], [[https://openalex.org/A5093542676][Shaktiswaran R. Udayasurian]], [[https://openalex.org/A5049133522][Max García‐Melchor]], [[https://openalex.org/A5062286247][Tengfei Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05388  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05388][pdf]])
     
Cyclohexanone oxime is an important precursor for Nylon-6 and is typically synthesized via the nucleophilic addition–elimination of hydroxylamine with cyclohexanone. Current technologies for hydroxylamine production are, however, not environment-friendly due to the requirement of harsh reaction conditions. Here, we report an electrochemical method for the one-pot synthesis of cyclohexanone oxime under ambient conditions with aqueous nitrate as the nitrogen source. A series of Zn–Cu alloy catalysts are developed to drive the electrochemical reduction of nitrate, where the hydroxylamine intermediate formed in the electroreduction process can undergo a chemical reaction with the cyclohexanone present in the electrolyte to produce the corresponding oxime. The best performance is achieved on a Zn93Cu7 electrocatalyst with a 97% yield and a 27% Faradaic efficiency for cyclohexanone oxime at 100 mA/cm2. By analyzing the catalytic activities/selectivities of the different Zn–Cu alloys and conducting in-depth mechanistic studies via in situ Raman spectroscopy and theoretical calculations, we demonstrate that the adsorption of nitrogen species plays a central role in catalytic performance. Overall, this work provides an attractive strategy to build the C–N bond in oxime and drive organic synthesis through electrochemical nitrate reduction, while highlighting the importance of controlling surface adsorption for product selectivity in electrosynthesis.    

    

* Enantiocovergent Cross-Coupling Reaction with 1,4-Dihydropyridine Derivatives via Photoinduced Nickel Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391839433
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05521")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391839433"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391839433"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391839433"))][Get cited by]]

OpenAlex: https://openalex.org/W4391839433 (Open access: False)
    
[[https://openalex.org/A5003462637][Tongtong Li]], [[https://openalex.org/A5047170949][Luo Liu]], [[https://openalex.org/A5037829758][Xiaokai Cheng]], [[https://openalex.org/A5070489845][Zhan Lu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05521 
     
Herein, we reported the enantioconvergent Csp3–Csp2 cross-coupling reaction with 1,4-dihydropyridine (DHP) derivatives via photoredox/nickel dual catalysis to access chiral products with good yield and enantioselectivity. The operationally simple reaction was carried out under mild conditions with good functional group tolerance. Due to the use of a stoichiometric equivalent of aryl/alkenyl halides as coupling partners, the sequential and iterative synthesis could be achieved smoothly in one pot for the synthesis of position isomers and stereoisomers. In the proposed mechanism, kinetic experiments and mechanistic studies indicated that the radical generation, depended on the excited photocatalyst and DHP, was the rate-determining step.    

    

* Oxygen-Vacancy-Induced Built-In Electric Field across MoCo Dual-Atomic Site Catalyst for Promoting Hydrogen Spillover in Hydrocracking and Hydrodesulfurization  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391842855
:TOPICS: Desulfurization Technologies for Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05911")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391842855"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391842855"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391842855"))][Get cited by]]

OpenAlex: https://openalex.org/W4391842855 (Open access: False)
    
[[https://openalex.org/A5055093981][Guangxun Sun]], [[https://openalex.org/A5047385323][Dongyuan Liu]], [[https://openalex.org/A5003849123][Hongfu Shi]], [[https://openalex.org/A5030640908][Junxi Li]], [[https://openalex.org/A5041898714][Liting Yang]], [[https://openalex.org/A5057254434][Fengyu Tian]], [[https://openalex.org/A5070110088][Yuchen Cui]], [[https://openalex.org/A5041230019][Chunlin Wang]], [[https://openalex.org/A5027352459][Feiyang Li]], [[https://openalex.org/A5022388959][Tiansheng Zhao]], [[https://openalex.org/A5061556681][Houyu Zhu]], [[https://openalex.org/A5048826252][Bin Liu]], [[https://openalex.org/A5062331341][Yong‐Ming Chai]], [[https://openalex.org/A5090056849][Yunqi Liu]], [[https://openalex.org/A5046844071][Yuan Pan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05911 
     
The design and construction of highly efficient catalytic active sites for promoting hydrogen spillover are of great significance for improving hydrocracking (HCK) and hydrodesulfurization (HDS) performance in slurry-phase hydrogenation of vacuum residue (VR) but are still challenging. Herein, we report a carbon-supported MoCo dual-atomic site catalyst (MoCo DAC/C) and propose an oxygen-vacancy-induced built-in electric field (BIEF) regulation mechanism for promoting hydrogen spillover in HCK and HDS. It was found that the coordination structure of the MoCo dual-atomic was reconstructed and formed O vacancies in situ during hydrogenation process. The formation of O vacancies not only provided macromolecular adsorption sites but also broke the electronic balance and formed a weak BIEF between the Mo and Co atoms. Meanwhile, H2 was activated at the Mo sites to form active hydrogen species. The formation of BIEF promoted the active hydrogen spillover from Mo to Co sites by a Mo–C–Co bridging bond, thus improving the hydrogenation performance greatly. In HCK of VR, the MoCo DAC/C demonstrates remarkable catalytic hydrogenation activity with TOFT calculated for total metals up to 0.77 s–1 (two times enhancement than that of Mo single atoms (SAs)/C), the per pass conversion of VR of 76 wt %, liquid product yield of 92 wt %, and coke content of only 0.55 wt %. It also shows robust HDS performance with dibenzothiophene (DBT) conversion of 70 wt %. Density functional theory reveals that the formation of the O vacancies leads to the discrepancy of Bader charge between Mo and Co atoms, and the resulting local electric field can favor the diffusion of the positively charged (+0.10 e−) H atom. This work proposes an oxygen-vacancy-induced BIEF regulation mechanism from an atomic scale for enhancing the catalytic reaction process by promoting hydrogen spillover, which provided novel insights for the design and development of high-performance hydrogenation catalysts.    

    

* Indium-Catalyzed Reductive Coupling Enabled Efficient Synthesis of Acylphosphine Oxides and Diphosphines  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391843736
:TOPICS: Homogeneous Catalysis with Transition Metals, Peptide Synthesis and Drug Discovery, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05947")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391843736"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391843736"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391843736"))][Get cited by]]

OpenAlex: https://openalex.org/W4391843736 (Open access: False)
    
[[https://openalex.org/A5017282649][Dongdong Xu]], [[https://openalex.org/A5054639707][Ming Yu Jin]], [[https://openalex.org/A5052676364][Yu Chen]], [[https://openalex.org/A5050369958][Daoqing Han]], [[https://openalex.org/A5005480296][Lizhi Tao]], [[https://openalex.org/A5037305819][Xiangyou Xing]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05947 
     
The unique low level of the ionization potential of indium(0) to indium(I) makes it an appealing metal for organic synthesis. Here, we present an indium-catalyzed reductive cross-coupling between chlorophosphines (R2PCl) or dichlorophosphines (RPCl2) with acyl chlorides (RCOCl). This one-pot approach, using indium-catalysis followed by oxidation, generates a variety of mono- or bis-acylphosphine oxides in good yields. Additionally, this protocol offers a convenient pathway to obtain the photoinitiators, Luricin TPO and IRGACURE 819, that are widely used in the industry. Experimental and computational studies indicate the intermediacy of phosphorus-based radical species that dimerize to diphosphines, which then couple with acyl chlorides through a four-membered transition state. Furthermore, we also explore indium-catalyzed reductive homocoupling of R2PCl or RPCl2, which provides facile access to various P–P bond formations.    

    

* Distinct Site Motifs Activate O2 and H2 on Supported Au Nanoparticles in Liquid Water  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391843796
:TOPICS: Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05072")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391843796"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391843796"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391843796"))][Get cited by]]

OpenAlex: https://openalex.org/W4391843796 (Open access: True)
    
[[https://openalex.org/A5034220884][Jason S. Adams]], [[https://openalex.org/A5063982253][H Chen]], [[https://openalex.org/A5042057899][Tomas Ricciardulli]], [[https://openalex.org/A5067363580][Sucharita Vijayaraghavan]], [[https://openalex.org/A5062993129][Abinaya Sampath]], [[https://openalex.org/A5062793974][David W. Flaherty]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05072  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05072][pdf]])
     
Au nanoparticles catalyze the activation and conversion of small molecules with rates and kinetic barriers that depend on the dimensions of the nanoparticle, composition of the support, and presence of catalytically culpable water molecules that solvate these interfaces. Here, molecular interpretations of steady-state rate measurements, kinetic isotope effects, and structural characterizations reveal how the interface of Au nanoparticles, liquid water, and metal oxide supports mediate the kinetically relevant activation of H2 and sequential reduction of O2-derived intermediates during the formation of H2O2 and H2O. Rates of H2 consumption are 10–100 fold greater on Au nanoparticles supported on metal oxides (e.g., titania) compared to more inert and hydrophobic materials (carbon, boron nitride). Similarly, Au nanoparticles on reducible and Lewis acidic supports (e.g., lanthana) bind dioxygen intermediates more strongly and present lower barriers (<22 kJ mol–1) for O–O bond dissociation than inert interfaces formed with silica (>70 kJ mol–1). Selectivities for H2O2 formation increase significantly as the diameters of the Au nanoparticles increase because differences in nanoparticle size change the relative fractions of exposed sites that exist at Au–support interfaces. In contrast, site-normalized rates and barriers for H2 activation depend weakly on the size of Au nanoparticles and the associated differences in active site motifs. These findings suggest that H2O aids the activation of H2 at sites present across all surface Au atoms when nanoparticles are solvated by water. However, molecular O2 preferentially binds and dissociates at Au–support interfaces, leading to greater structure sensitivity for barriers of O–O dissociation across different support identities and sizes of Au nanoparticles. These insights differ from prior knowledge from studies of gas-phase reactions of H2 and O2 upon Au nanoparticle catalysts within dilute vapor pressures of water (10–4 to 0.1 kPa H2O), in which catalysis occurs at the perimeter of the Au–support interface. In contrast, contacting Au catalysts with liquid water (55.5 M H2O) expands catalysis to all surface Au atoms and enables appreciable H2O2 formation.    

    

* Catch-and-Release: The Assembly, Immobilization, and Recycling of Redox-Reversible Artificial Metalloenzymes  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391846627
:TOPICS: Catalytic Reduction of Nitro Compounds, Structural and Functional Study of Noble Metal Nanoclusters, Enzyme Immobilization Techniques
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05294")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391846627"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391846627"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391846627"))][Get cited by]]

OpenAlex: https://openalex.org/W4391846627 (Open access: True)
    
[[https://openalex.org/A5084609790][Alex Henrique Miller]], [[https://openalex.org/A5024647487][E.V. Blagova]], [[https://openalex.org/A5083153708][Benjamin Large]], [[https://openalex.org/A5082534426][Rosalind L. Booth]], [[https://openalex.org/A5041541957][K.S. Wilson]], [[https://openalex.org/A5018756784][Anne‐Kathrin Duhme‐Klair]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05294  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05294][pdf]])
     
Technologies to improve the applicability of artificial metalloenzymes (ArMs) are gaining considerable interest; one such approach is the immobilization of these biohybrid catalysts on support materials to enhance stability and enable their retention, recovery, and reuse. Here, we describe the immobilization of polyhistidine-tagged ArMs that allow the redox-controlled replacement of catalytic cofactors that have lost activity, e.g., due to poisoning or decomposition, on immobilized metal affinity chromatography resins. By using periplasmic siderophore-binding protein scaffolds that originate from thermophilic bacteria (GstCeuE and PthCeuE) in combination with a siderophore-linked imine reduction catalyst, reaction rates were achieved that are about 3.5 times faster than those previously obtained with CjCeuE, the analogous protein of Campylobacter jejuni. Upon immobilization, the GstCeuE-derived ArM showed a decrease in turnover frequency in the reduction of dehydrosalsolidine by 3.4-fold, while retaining enantioselectivity (36%) and showing improved stability that allowed repeat recovery and recycling cycles. Catalytic activity was preserved over the initial four cycles. In subsequent cycles, a gradual reduction of activity was evident. Once the initial activity decreased to around 40% of the initial activity (23rd recycling cycle), the redox-triggered artificial cofactor release permitted the subsequent recharging of the immobilized protein scaffold with fresh, active cofactor, thereby restoring the initial catalytic activity of the immobilized ArM and allowing its reuse for several more cycles. Furthermore, the ArM could be assembled directly from protein present in crude cell extracts, avoiding time-consuming and costly protein purification steps. Overall, this study demonstrates that the immobilization of redox-reversible ArMs facilitates their “catch-and-release” assembly and disassembly and the recycling of their components, improving their potential commercial viability and environmental footprint.    

    

* Size and Structure Effects of Carbon-Supported Ruthenium Nanoparticles on Waste Polypropylene Hydrogenolysis Activity, Selectivity, and Product Microstructure  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391847083
:TOPICS: Microplastic Pollution in Marine and Terrestrial Environments, Global E-Waste Recycling and Management, Biodegradable Polymers as Biomaterials and Packaging
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05927")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391847083"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391847083"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391847083"))][Get cited by]]

OpenAlex: https://openalex.org/W4391847083 (Open access: False)
    
[[https://openalex.org/A5004746873][Jessie A. Sun]], [[https://openalex.org/A5007133096][Pavel A. Kots]], [[https://openalex.org/A5036961843][Zachary R. Hinton]], [[https://openalex.org/A5039759620][Nebojša Marinković]], [[https://openalex.org/A5010163365][Lu Ma]], [[https://openalex.org/A5091749773][Steven N. Ehrlich]], [[https://openalex.org/A5015640857][Weiqing Zheng]], [[https://openalex.org/A5088151231][Thomas H. Epps]], [[https://openalex.org/A5023698177][LaShanda T. J. Korley]], [[https://openalex.org/A5066110304][Dionisios G. Vlachos]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05927 
     
Hydrogenolysis of plastic waste using Ru-based catalysts is promising for deconstructing polyolefins into lower molecular weight products. Yet, the effect of catalyst atomic structure and size on activity and product selectivity is poorly understood. Herein, we expose the effect of metal particle size and atomic structure on isotactic-polypropylene (i-PP) hydrogenolysis over Ru supported on carbon. Despite similar molecular weight distributions of solid and liquid products, their physical properties are distinct due to different chain regio-irregular CH3 sequences of steric pentads containing racemo configurations. We propose that i-PP hydrogenolysis entails an interplay of C–C bond scission and stereoisomerization. The active site’s local electronic environment and structure dictate the former, whereas polymer–catalyst surface interactions creating suitable polymer conformations control the latter. C–C scission and stereoisomerization are structure-sensitive. Small, disordered nanoclusters are effective in C–C bond scission, whereas larger metal nanoparticles promote stereoisomerization. We hypothesize that a heterogeneous distribution of metal active sites is essential for deconstruction and product (lubricant base oil) quality control.    

    

* Twin Heterostructure Engineering and Facet Effect Boosts Efficient Reduction CO2-to-Ethanol at Low Potential on Cu2O@Cu2S Catalysts  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391847445
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05857")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391847445"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391847445"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391847445"))][Get cited by]]

OpenAlex: https://openalex.org/W4391847445 (Open access: False)
    
[[https://openalex.org/A5067951425][Jing Li]], [[https://openalex.org/A5012124301][Rong Cai]], [[https://openalex.org/A5017290775][Haiqiang Mu]], [[https://openalex.org/A5034285520][Jia-Xing Guo]], [[https://openalex.org/A5031589981][Xing Zhong]], [[https://openalex.org/A5067788077][Jianguo Wang]], [[https://openalex.org/A5089842784][Xin Du]], [[https://openalex.org/A5007962016][Jie Zhang]], [[https://openalex.org/A5063909163][Feng Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05857 
     
Copper oxide (Cu2O) is considered a promising catalyst that can effectively reduce the overpotential of the CO2 reduction reaction (CO2 RR) and increase the selectivity for C2+ products. However, developing high-performance and stable of CO2-to-ethanol (C2H5OH) based-Cu2O electrocatalysts remains challenging. In this work, Cu2O@Cu2S twin heterojunction catalysts with multitwin boundaries are designed to afford C2H5OH productivity at low potential through the electrocatalytic CO2 RR, and the C2H5OH selectivity is highly dependent on the facet of Cu2O@Cu2S with nanocubes outperforming octahedra. Detailed electrochemical experiments, density functional theory (DFT) calculations and in situ infrared spectroscopy reveals that the introduction of Cu2S boosts the high coverage of *CO, which can easily spillover to the twin boundaries to generate C2H5OH through the *CHOH_*CO coupling reaction pathway. A C2H5OH production begins at an ultralow potential of −0.45 V vs RHE and reaches 34 and 43.9% Faradaic efficiencies (FE) at −0.65 V vs RHE in an H-cell and a flow cell, respectively. Meanwhile, this heterojunction constructed with an interface coherent structure and suitable band structure can facilitate electron transfer from Cu2O to Cu2S, leading to the stability of Cu+ valence states. This work provides an avenue to precisely design C2H5OH production catalysts by regulating the interface configuration.    

    

* Uncovering the On-Pathway Reaction Intermediates for Metal-Free Atom Transfer Radical Addition to Olefins through Photogenerated Phenalenyl Radical Anion  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391874588
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Electrochemical Reduction of CO2 to Fuels, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05688")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391874588"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391874588"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391874588"))][Get cited by]]

OpenAlex: https://openalex.org/W4391874588 (Open access: False)
    
[[https://openalex.org/A5035315938][Paramita Datta]], [[https://openalex.org/A5065668551][D. Roy]], [[https://openalex.org/A5056917563][Divya Jain]], [[https://openalex.org/A5047643700][Shiv Datt Kumar]], [[https://openalex.org/A5085324549][Swagata Sil]], [[https://openalex.org/A5024283290][Anup Bhunia]], [[https://openalex.org/A5064885330][Jyotishman Dasgupta]], [[https://openalex.org/A5071640196][Swadhin K. Mandal]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05688 
     
No abstract    

    

* Unveiling the Catalytic Merits of LaV3O9 over Conventional LaVO4 Polymorphs to Boost Desired Kinetics of Humid NOX Reduction and Poison Disintegration  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391879043
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Sulfur Compounds Removal Technologies
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04828")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391879043"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391879043"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391879043"))][Get cited by]]

OpenAlex: https://openalex.org/W4391879043 (Open access: False)
    
[[https://openalex.org/A5049793744][Seokhyun Lee]], [[https://openalex.org/A5073768405][Jeongeun Choi]], [[https://openalex.org/A5044320760][Heon Phil Ha]], [[https://openalex.org/A5087337598][Jung Hyun Lee]], [[https://openalex.org/A5089095318][Jongwook Park]], [[https://openalex.org/A5074896786][Jongsik Kim]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04828 
     
SOZ2– (Z = 3–4)-functionalized metal vanadates vary with the type of metal cations (Mn+) for the Mn+-O2–-V5+ channels that fragment to impart Brönsted acidic bonds (BA–-H+; SOZ2–-H+) and labile/mobile oxygens (OL/OM) with distinct populations and affinities for NOX/O2/H2O/SO2. SOZ2–-modified Mn+-O2–-V5+ fragments bind with NH3 to activate Eley–Rideal (ER)-type selective catalytic NOX reduction (SCR), yet, hardly enable OL coordination with NOX and are often hydrophilic, thereby limiting the activities of SCR or ammonium (bi)sulfate (AS/ABS) fragmentation, as gauged by the NOX consumption (-rNOX) and AS/ABS degradation rates (-rAS/ABS), respectively. Here, we justified the use of nonreducible La3+-containing La3+-O2–-V5+ channels, whose merits in accelerating SCR and AS/ABS fragmentation were found to be more pronounced for SOZ2–-modified LaV3O9 (LaV3O9-S) than for conventional/polymorphic LaVO4 analogues (LaVO4-S). Besides activating the ER-type SCR, LaV3O9-S bound with NO and activated Langmuir–Hinshelwood-type SCR, as opposed to LaVO4-S. The pre-exponential factor (k′APP,0) and -rNOX were thus higher for LaV3O9-S than for LaVO4-S and were coupled with the greater amount of OM in the former, leading to superior SCR performance under wet gases. Moreover, compared to LaV3O9-S, its Sb2O5-promoted analogue (LaV3O9-Sb2O5-S) provided a larger number of NH3-accessible BA–-H+ bonds to achieve higher k′APP,0/-rNOX alongside higher OM mobility. Furthermore, the LaV3O9-S and Sb2O5-S of LaV3O9-Sb2O5-S elevated the hydrophobicity and number of ABS-accessible BA–-H+ bonds, respectively. LaV3O9-Sb2O5-S thus revealed a lower energy barrier and higher k′APP,0 in AS/ABS pyrolysis than a commercial control (V2O5-WO3-S), resulting in a higher -rAS/ABS for the former. Consequently, LaV3O9-Sb2O5-S displayed superior SCR performance and greater hydrothermal resistance under SO2-containing wet gases in comparison with V2O5-WO3-S.    

    

* Revealing the Impact of Pulsed Laser-Produced Single-Pd Nanoparticles on a Bimetallic NiCo2O4 Electrocatalyst for Energy-Saving Hydrogen Production via Hybrid Water Electrolysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391879183
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05051")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391879183"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391879183"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391879183"))][Get cited by]]

OpenAlex: https://openalex.org/W4391879183 (Open access: False)
    
[[https://openalex.org/A5058019178][Raja Arumugam Senthil]], [[https://openalex.org/A5025931538][Sieon Jung]], [[https://openalex.org/A5000061857][Ahreum Min]], [[https://openalex.org/A5087525540][Anuj Kumar]], [[https://openalex.org/A5011667598][Cheol Joo Moon]], [[https://openalex.org/A5020253291][M N Singh]], [[https://openalex.org/A5067975222][Myong Yong Choi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05051 
     
Nowadays, the assembling of hybrid water electrolysis using a hydrazine oxidation reaction (HzOR) instead of a slow anodic oxygen evolution reaction (OER) has been established as a favorable technology for efficient hydrogen (H2) production. Nevertheless, it is still critical to develop highly effective bifunctional electrocatalysts for both hydrogen evolution reaction (HER) and HzOR. In this work, we propose a facile approach for the design and synthesis of single-Pd-nanoparticles-decorated bimetallic NiCo2O4 nanoplates as a bifunctional electrocatalyst for both HER and HzOR. Initially, the NiCo2O4 nanoplates are synthesized by a combination of hydrothermal reaction and high-temperature calcination. Subsequently, single-Pd nanoparticles with varying proportions are decorated on NiCo2O4 nanoplates via facile pulsed laser irradiation (PLI), leading to the formation of Pd/NiCo2O4 composites. The optimized Pd/NiCo2O4 composite shows a remarkable electrocatalytic ability with a low overpotential of 294 mV for the HER and an ultrasmall working potential of −6 mV (vs RHE) for the HzOR at 10 mA cm–2 in a 1 M KOH electrolyte. Thus, an overall hydrazine splitting (OHzS) electrolyzer with the Pd/NiCo2O4∥Pd/NiCo2O4 system presents the current densities of 10 and 100 mA cm–2 at respective low cell voltages of 0.35 and 0.94 V. Notably, in situ/operando Raman spectroscopy confirms the surface formation of α-Co(OH)2 during the HER and γ-NiOOH during the HzOR. Furthermore, the density function theory (DFT) calculations demonstrate that the decoration of Pd onto NiCo2O4 facilitates the optimization of both the hydrogen adsorption free energy (ΔGH*) and enhancement of hydrazine dehydrogenation kinetics. This work introduces a facile strategy for fabricating bifunctional electrocatalysts, potentially useful in energy-saving H2 production.    

    

* Dual Photoredox/Cobalt-Catalyzed Reductive Cyclization of Alkynals  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391879203
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06206")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391879203"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391879203"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391879203"))][Get cited by]]

OpenAlex: https://openalex.org/W4391879203 (Open access: False)
    
[[https://openalex.org/A5075836590][Kento Nakamura]], [[https://openalex.org/A5093941521][Hina Nishigaki]], [[https://openalex.org/A5005663108][Yoshihiro Sato]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06206 
     
Substituted cyclic alcohol is one of the pharmaceutically essential scaffolds. Here, we report photoredox/cobalt-catalyzed reductive cyclization of alkynals using H2O for the catalyst turnover. This method was applied to aliphatic and aromatic aldehydes for five-, six-, and seven-membered (heterocyclic) ring formation with various substitutions on alkyne units. This H2O-added protocol was further developed into a one-pot transformation from acetals through in situ generated aldehydes, which shortened the synthetic path of the reaction.    

    

* Reply to Comment on “Heterogeneous Catalyst–Microbiome Hybrids for Efficient CO-Driven C6 Carboxylic Acid Synthesis via Metabolic Pathway Manipulation”  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391879335
:TOPICS: Homogeneous Catalysis with Transition Metals, Enzyme Immobilization Techniques, Droplet Microfluidics Technology
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05832")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391879335"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391879335"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391879335"))][Get cited by]]

OpenAlex: https://openalex.org/W4391879335 (Open access: True)
    
[[https://openalex.org/A5028296024][Chao Liu]], [[https://openalex.org/A5043795340][Jiacheng Ji]], [[https://openalex.org/A5063911013][Yi Zhang]], [[https://openalex.org/A5053538639][Wen Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05832  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05832][pdf]])
     
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVCorrespondence/Rebut...Correspondence/RebuttalNEXTReply to Comment on “Heterogeneous Catalyst–Microbiome Hybrids for Efficient CO-Driven C6 Carboxylic Acid Synthesis via Metabolic Pathway Manipulation”Chao LiuChao LiuCollege of Chemical Engineering, Beijing University of Chemical Technology, Beijing 100029, ChinaBiomass Energy and Environmental Engineering Research Center, Beijing University of Chemical Technology, Beijing 100029, ChinaMore by Chao Liu, Jiacheng JiJiacheng JiCollege of Chemical Engineering, Beijing University of Chemical Technology, Beijing 100029, ChinaMore by Jiacheng Ji, Yi Zhang*Yi ZhangCollege of Chemical Engineering, Beijing University of Chemical Technology, Beijing 100029, China*Email: [email protected] (Y. Zhang); Tel: +86-010-64436991.More by Yi Zhang, and Wen Wang*Wen WangCollege of Chemical Engineering, Beijing University of Chemical Technology, Beijing 100029, ChinaBiomass Energy and Environmental Engineering Research Center, Beijing University of Chemical Technology, Beijing 100029, China*Email: [email protected] (W. Wang); Tel: +86-010-64429591.More by Wen Wanghttps://orcid.org/0000-0002-5100-8315Cite this: ACS Catal. 2024, 14, XXX, 2981–2984Publication Date (Web):February 16, 2024Publication History Received30 November 2023Accepted25 January 2024Revised11 January 2024Published online16 February 2024https://doi.org/10.1021/acscatal.3c05832© 2024 American Chemical SocietyRequest reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (792 KB) Get e-AlertscloseSUBJECTS:Bacteria,Catalysts,Chemical reactions,Fourier transforms,Iron Get e-Alerts    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391879670
:TOPICS: 
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i004_1771303")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391879670"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391879670"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391879670"))][Get cited by]]

OpenAlex: https://openalex.org/W4391879670 (Open access: True)
    
, ACS Catalysis. 14(4)] 2024. https://doi.org/10.1021/csv014i004_1771303  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i004_1771303][pdf]])
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391882672
:TOPICS: 
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i004_1771304")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391882672"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391882672"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391882672"))][Get cited by]]

OpenAlex: https://openalex.org/W4391882672 (Open access: True)
    
, ACS Catalysis. 14(4)] 2024. https://doi.org/10.1021/csv014i004_1771304  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i004_1771304][pdf]])
     
No abstract    

    

* Discovery of Toxin-Degrading Enzymes with Positive Unlabeled Deep Learning  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391883895
:TOPICS: Mycotoxins and Their Impact, Computational Methods in Drug Discovery, Natural Products as Sources of New Drugs
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04461")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391883895"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391883895"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391883895"))][Get cited by]]

OpenAlex: https://openalex.org/W4391883895 (Open access: False)
    
[[https://openalex.org/A5006275258][Dachuan Zhang]], [[https://openalex.org/A5059599249][Huadong Xing]], [[https://openalex.org/A5003816728][Dongliang Li]], [[https://openalex.org/A5003999551][Mengying Han]], [[https://openalex.org/A5071379782][Pengli Cai]], [[https://openalex.org/A5054772627][Huikang Lin]], [[https://openalex.org/A5072835438][Yu Tian]], [[https://openalex.org/A5079122086][Y. Jay Guo]], [[https://openalex.org/A5028594091][Bin Sun]], [[https://openalex.org/A5058727059][Yingying Le]], [[https://openalex.org/A5088657051][Ye Tian]], [[https://openalex.org/A5011532820][Aibo Wu]], [[https://openalex.org/A5054348304][Qian-Nan Hu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04461 
     
Identifying functional enzymes for the catalysis of specific biochemical reactions is a major bottleneck in the de novo design of biosynthesis and biodegradation pathways. Conventional methods based on microbial screening and functional metagenomics require long verification periods and incur high experimental costs; recent data-driven methods apply only to a few common substrates. To enable rapid and high-throughput identification of enzymes for complex and less-studied substrates, we propose a robust enzyme’s substrate promiscuity prediction model based on positive unlabeled learning. Using this model, we identified 15 new degrading enzymes specific for the mycotoxins ochratoxin A and zearalenone, of which six could degrade >90% mycotoxin content within 3 h. We anticipate that this model will serve as a useful tool for identifying new functional enzymes and understanding the nature of biocatalysis, thereby advancing the fields of synthetic biology, metabolic engineering, and pollutant biodegradation.    

    
