#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sat Feb 17 00:43:04 2024

Found 25 results from 2024-02-10 to 2024-02-17
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Toward High CO Selectivity and Oxidation Resistance Solid Oxide Electrolysis Cell with High-Entropy Alloy  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391679800
:TOPICS: Solid Oxide Fuel Cells, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05972")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391679800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391679800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391679800"))][Get cited by]]

OpenAlex: https://openalex.org/W4391679800 (Open access: False)
    
[[https://openalex.org/A5024280063][Jun Tang]], [[https://openalex.org/A5075626239][Na Ni]], [[https://openalex.org/A5010878103][Baowen Zhou]], [[https://openalex.org/A5015927446][Chen Yang]], [[https://openalex.org/A5041129333][Kolan Madhav Reddy]], [[https://openalex.org/A5012980325][Heng Tu]], [[https://openalex.org/A5002038517][Yu-Si Liu]], [[https://openalex.org/A5057876953][Zhe Tan]], [[https://openalex.org/A5030172940][Longkai Xiang]], [[https://openalex.org/A5015353382][Haozhen Li]], [[https://openalex.org/A5050803462][Xing Zhang]], [[https://openalex.org/A5086509214][Yunyi Zhang]], [[https://openalex.org/A5089669072][Yixin Li]], [[https://openalex.org/A5064982569][Hanchao Zhang]], [[https://openalex.org/A5050980529][Lei Zhu]], [[https://openalex.org/A5087875241][Zhen Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05972 
     
Ni-based cermet materials still persist as pronounced challenges for electrocatalysts in solid oxide electrolysis cells (SOECs), due to their insufficient CO2 catalytic efficiency and inferior resistance to oxidation. In this paper, a (Fe,Co,Ni,Cu,Mo) quinary high-entropy alloy is explored as an alternative cathode material, offering enhanced performance in the co-electrolysis of H2O and CO2 for renewable syngas production. In comparison to traditional nickel-based cathodes, an assembled SOEC employing the as-designed quinary high-entropy alloy exhibits a remarkable increase in CO2 conversion capacity and significantly enhanced oxidation resistance. In addition, the electrolysis current density increases by 18%, and a stability test for more than 110 h reveals no degradation. Moreover, the stability can be maintained for up to 40 h even without any protective gas. Morphological and spectroscopic analyses, coupled with density functional theory (DFT) calculations, elucidate that the high-entropy effect facilitates surface electron redistribution, which in turn contributes to the measurable activity by reducing the energy barrier of CO2 activation. Notably, the superior resistance to oxidation primarily originates from the in situ-formed spinel phase under oxidation conditions. This study demonstrates the satisfying performance of high-entropy alloys as cathode materials in SOEC, validating their high application potential in this field.    

    

* Dehydrogenation and Transfer Hydrogenation of Alkenones to Phenols and Ketones on Carbon-Supported Noble Metals  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391681918
:TOPICS: Homogeneous Catalysis with Transition Metals, Carbon Dioxide Utilization for Chemical Synthesis, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-02-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04849")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391681918"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391681918"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391681918"))][Get cited by]]

OpenAlex: https://openalex.org/W4391681918 (Open access: True)
    
[[https://openalex.org/A5010415616][Katja Li]], [[https://openalex.org/A5065641804][H. Ray Kelly]], [[https://openalex.org/A5080850986][José Armando L. da Silva]], [[https://openalex.org/A5089129603][Víctor S. Batista]], [[https://openalex.org/A5047406603][Eszter Baráth]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04849  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c04849][pdf]])
     
The catalytic dehydrogenation of substituted alkenones on noble metal catalysts supported on carbon (Pt/C, Pd/C, Rh/C, and Ru/C) was investigated in an organic phase under inert conditions. The dehydrogenation and semihydrogenation of the enone starting materials resulted in aromatic compounds (primary products), saturated cyclic ketones (secondary products), and cyclic alcohols (minor products). Pd/C exhibits the highest catalytic activity, followed by Pt/C and Rh/C. Aromatic compounds remain the primary products, even in the presence of hydrogen donors. Joint experimental and theoretical analyses showed that the four catalytic materials stabilize a common dienol intermediate on the metal surfaces, formed by keto–enol tautomerization. This intermediate subsequently forms aromatic products upon dehydrogenation. The binding orientation of the enone reactants on the catalytic surface is strongly metal-dependent, as the M–O bond distance changes substantially according to the metal. The longer M–O bonds (Pt: 2.84 Å > Pd: 2.23 Å > Rh: 2.17 Å > Ru: 2.07 Å) correlate with faster reaction rates and more favorable keto–enol tautomerization, as shorter distances correspond to a more stabilized starting material. Tautomerization is shown to occur via a stepwise surface-assisted pathway. Overall, each of the studied metals exhibits a distinct balance of enthalpy and entropy of activation (ΔH°‡, ΔS°‡), offering unique possibilities in the realm of enone dehydrogenation reactions that can be achieved by suitable selection of catalytic materials.    

    

* Unveiling the Dynamic Evolution of Single-Atom Co Sites in Covalent Triazine Frameworks for Enhanced H2O2 Photosynthesis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391685024
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Content-Centric Networking for Information Delivery, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04439")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391685024"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391685024"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391685024"))][Get cited by]]

OpenAlex: https://openalex.org/W4391685024 (Open access: False)
    
[[https://openalex.org/A5080637240][Chao Zhu]], [[https://openalex.org/A5063115287][Yanchi Yao]], [[https://openalex.org/A5000714277][Qile Fang]], [[https://openalex.org/A5045577703][Lingxiangyu Li]], [[https://openalex.org/A5090741037][Baoliang Chen]], [[https://openalex.org/A5043170120][Yi Shen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04439 
     
Unraveling the structural evolution and mechanism of active sites in single-atom catalysts (SACs) during H2O2 production under operational conditions remains challenging due to the transient and elusive nature of the underlying reaction processes. Herein, we employ operando X-ray absorption spectroscopy and ab initio molecular dynamics simulations to unveil the dynamic reconstruction behavior of the Co single atom-loaded covalent triazine framework (CoSA/Py-CTF) during photocatalytic H2O2 production. The unique Py-CTF substrate provides reasonable structural flexibility to the single atom Co site. Under light irradiation and O2 adsorption, single Co atoms are dynamically released from the Py-CTF substrate and then form transient atom-pairs with neighboring Co atoms, serving as the authentic active site. The dynamic shuttling of Co subnanometer domains between single-atoms and atom-pairs facilitates the transition of the O2 adsorption configurations from Pauling type to Yeager type, resulting in a record photocatalytic H2O2 yield (2898.3 μmol·h–1·g–1). These findings provide insightful observations into the dynamic photochemical behavior of SACs and present an fresh paradigm for the design of intelligent “adaptive catalysts”.    

    

* Iridium-Catalyzed Tandem Dehydrogenation/Hydroarylation Approach to Synthetically Versatile C2-Alkenyl N–H Indoles  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391691736
:TOPICS: Homogeneous Catalysis with Transition Metals, Transition-Metal-Catalyzed C–H Bond Functionalization, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05841")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391691736"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391691736"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391691736"))][Get cited by]]

OpenAlex: https://openalex.org/W4391691736 (Open access: False)
    
[[https://openalex.org/A5039597979][Carlos Lázaro‐Milla]], [[https://openalex.org/A5061612775][José L. Mascareñas]], [[https://openalex.org/A5008725332][Fernando Fernández López]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05841 
     
Readily available N-carbamoyl indolines can be converted into highly valuable 2-alkenyl and 2-alkyl indoles in a one-pot reaction, through an autotandem catalytic cascade promoted by an iridium complex. The process entails a dehydrogenation reaction initiated by an iridium-promoted C(sp3)–H activation, the addition of the resulting indole to an alkyne -or alkene-partner, and a spontaneous loss of the carbamoyl directing group. Interestingly, the resulting C2-alkenyl indoles can participate in a variety of metal-catalyzed annulations initiated by C–H activation, including formal [4 + 1] and [4 + 2] cycloadditions, as well as cross-dehydrogenative cyclizations, thus enabling a divergent access to a collection of functionally rich nitrogen-containing heterocycles.    

    

* Size-Dependent Structural Features of Subnanometer PtSn Catalysts Encapsulated in Zeolite for Alkane Dehydrogenation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391692005
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Accelerating Materials Innovation through Informatics, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00314")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391692005"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391692005"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391692005"))][Get cited by]]

OpenAlex: https://openalex.org/W4391692005 (Open access: False)
    
[[https://openalex.org/A5015682712][Xiao-Meng Dou]], [[https://openalex.org/A5035374461][Wenying Li]], [[https://openalex.org/A5012236511][Kun Zhang]], [[https://openalex.org/A5010975567][Haiyun Hou]], [[https://openalex.org/A5016683809][Zhe He]], [[https://openalex.org/A5004537680][Chaofeng Zhu]], [[https://openalex.org/A5078151020][Débora Motta Meira]], [[https://openalex.org/A5047021710][Miguel López‐Haro]], [[https://openalex.org/A5042332021][Zhaoming Xia]], [[https://openalex.org/A5081266339][Peng He]], [[https://openalex.org/A5023546157][Hai Xiao]], [[https://openalex.org/A5014361961][Lichen Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00314 
     
Identification of the most efficient configuration of subnanometer bimetallic clusters is of great importance for the rational design of bimetallic catalysts but remains challenging due to the difficulty to construct the appropriate model systems. Here, we have accommodated subnanometer Pt/Sn sites, spanning from metal single atoms to bimetallic clusters in the 10MR sinusoidal channels of pure-silica MFI-type zeolite, which are employed as model catalysts to identify the optimal configuration of subnanometer PtSn sites for catalyzing an alkane dehydrogenation reaction. According to the electron microscopy and spectroscopy characterization results, the structural configuration of the bimetallic PtSn species in MFI zeolite varies with the Pt loading, which influences their catalytic performances for the propane dehydrogenation reaction. Furthermore, theoretical calculations are performed to understand the structural features of various PtSn species and their catalytic behavior for propane dehydrogenation, providing insights into the structure–reactivity relationships of subnanometer PtSn catalysts confined in zeolite structures.    

    

* A Remarkable Influence of La(III)/N,N′-Dioxide Structure on Asymmetric Formal Substitution of 3-Bromo-3-substituted Oxindoles with TMSCN  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391719372
:TOPICS: Asymmetric Catalysis, Homogeneous Catalysis with Transition Metals, Organometallic Chemistry and Metalation
:PUBLICATION_DATE: 2024-02-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06130")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391719372"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391719372"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391719372"))][Get cited by]]

OpenAlex: https://openalex.org/W4391719372 (Open access: False)
    
[[https://openalex.org/A5085034156][Zi Zeng]], [[https://openalex.org/A5044748407][Longqing Yang]], [[https://openalex.org/A5002318539][Xiao Zhang]], [[https://openalex.org/A5012324763][Long Chen]], [[https://openalex.org/A5073484937][Ziwei Zhong]], [[https://openalex.org/A5011208812][Fei Wang]], [[https://openalex.org/A5050151425][Xiaohua Liu]], [[https://openalex.org/A5081426782][Shujuan Dong]], [[https://openalex.org/A5077217676][Xiaoming Feng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06130 
     
The structural elucidation of chiral rare-earth-based catalysts in asymmetric reactions holds significant importance as it is crucial for comprehending their operational mechanisms and for broadening their applications in the realm of asymmetric synthesis. Herein, a LaIII/(L3-RaMe3)2 complex was identified to be more active and enantioselective than LaIII/L3-RaMe3 in the asymmetric formal substitution of racemic 3-bromo-3-substituted oxindoles with TMSCN. The experimental studies and theoretical calculations disclosed that the partial dissociation of the chiral N,N′-dioxide ligand was involved in the catalytic process with LaIII/(L3-RaMe3)2. These insights provided a rationale for the remarkable effect of catalyst structures on the results and nonlinear effect observed in the current reaction system. This protocol offers a straightforward and efficient pathway to synthesize various chiral 3-cyano-3-substituted oxindoles (53 examples, up to 99% yield, 98% ee). In addition, the synthesis of a bioactive compound CRTH2 receptor antagonist and obvious inhibitory effect of several products on the viability of cancer cells demonstrate the potential utility of this methodology.    

    

* Surface Strain Effect on Electrocatalytic Hydrogen Evolution Reaction of Pt-Based Intermetallics  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391738668
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06291")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391738668"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391738668"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391738668"))][Get cited by]]

OpenAlex: https://openalex.org/W4391738668 (Open access: False)
    
[[https://openalex.org/A5060920420][Z.Y. Zhong]], [[https://openalex.org/A5010811558][Yuanhua Tu]], [[https://openalex.org/A5019925257][Longhai Zhang]], [[https://openalex.org/A5076364504][Ke Jiang]], [[https://openalex.org/A5041745010][Chengzhi Zhong]], [[https://openalex.org/A5003316836][Wei Tan]], [[https://openalex.org/A5064023616][Lingyu Wang]], [[https://openalex.org/A5029153042][Jiaxi Zhang]], [[https://openalex.org/A5018142547][Hui‐Hua Song]], [[https://openalex.org/A5062744012][Li Du]], [[https://openalex.org/A5023031181][Zhiming Cui]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06291 
     
Elucidating the relationship between electrocatalytic activity and surface strain is pivotal for designing highly efficient electrocatalysts for the acidic hydrogen evolution reaction (HER). However, a general correlation is currently absent due to the lack of ideal catalytic materials platforms with well-defined structures and components. Herein, we select L10 and L12 Pt-based intermetallic compounds as model materials to construct a series of core–shell catalysts with strained Pt skins (IMC@Pt) and establish the correlation between surface strain and HER performance. Density functional theory calculations were performed to determine the surface strain degree, d-band center, and key descriptor ΔGH* of the catalysts for HER. By combining theoretical and experimental data, we propose a volcano-type trend between surface strain and the HER activity of IMC@Pt with an apex at 4% compressive strain. In addition, we demonstrate a class of highly active and durable IMC@Pt catalysts for acidic HER. Among them, the Pt3V@Pt catalyst exhibits the highest intrinsic HER activity with a specific activity of 4.24 mA cmPt–2 at an overpotential of 20 mV, which is 4 times higher than that of Pt. This work provides a solid understanding of the essential nature of PtM alloy catalysts and can guide the design of high-performance HER catalysts for water electrolyzers.    

    

* From Functional Plasticity of Two Diterpene Synthases (IrTPS2/IrKSL3a) to Enzyme Evolution  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391745873
:TOPICS: Biosynthesis and Engineering of Terpenoids, Role of Oxidative Stress in Health and Disease, Natural Products as Sources of New Drugs
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05918")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391745873"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391745873"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391745873"))][Get cited by]]

OpenAlex: https://openalex.org/W4391745873 (Open access: False)
    
[[https://openalex.org/A5035287462][Baolong Jin]], [[https://openalex.org/A5046952431][Kangwei Xu]], [[https://openalex.org/A5031777682][Juan Guo]], [[https://openalex.org/A5012233067][Ying Ma]], [[https://openalex.org/A5049421341][Jian Yang]], [[https://openalex.org/A5037793321][Nianhang Chen]], [[https://openalex.org/A5012066268][Tao Zeng]], [[https://openalex.org/A5077713586][Jian Wang]], [[https://openalex.org/A5091242731][Jianing Liu]], [[https://openalex.org/A5080623504][Ming Tian]], [[https://openalex.org/A5008725104][Qing Ma]], [[https://openalex.org/A5071683625][Haiyan Zhang]], [[https://openalex.org/A5010759973][Reuben J. Peters]], [[https://openalex.org/A5060789335][Guanghong Cui]], [[https://openalex.org/A5090084906][Ruibo Wu]], [[https://openalex.org/A5074678706][Luqi Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05918 
     
Terpenoids are an intriguing class of natural products with diverse structures and biological activities whose complexity stems in large part from terpene synthases (TPSs). These enzymes catalyze carbocationic cascade reactions wherein the groups responsible for quenching the final carbocation are generally not well-known. IrKSL3a and IrTPS2 from Isodon rubescens share 98% sequence homology but use distinct quenching strategies, with IrKSL3a catalyzing direct deprotonation to generate the olefin isopimaradiene while IrTPS2 adds water to yield the hydroxylated nezukol. In this work, we discovered a threonine and serine that hydrogen-bond the water to be added in IrTPS2. Site-directed mutagenesis and multiscale QM/MM simulations of modeled structures further reveal that the binding of this water is blocked by the introduction of a β-methyl-containing side chain in a neighboring residue. From these insights, it was then possible to engineer IrKSL3a to generate nezukol, with other new hydroxylated products also observed. Inspired by these mechanistic insights into the functional plasticity of IrKSL3a and IrTPS2, we explored the plausible evolutionary relationship of these kaurene synthase-like (KSL) TPSs, as well as prospective utilization of these plasticity sites discovered in IrTPS2/IrKSL3a. Such experiments with a variety of more phylogenetically distant KSLs demonstrated that these residues are necessary but not sufficient to efficiently introduce such an addition of water, emphasizing the selective pressure underlying the extended evolutionary process for the production of nezukol by IrTPS2.    

    

* Tandem Chemical Depolymerization and Photoreforming of Waste PET Plastic to High-Value-Added Chemicals  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391745876
:TOPICS: Microplastic Pollution in Marine and Terrestrial Environments, Global E-Waste Recycling and Management, Biodegradable Polymers as Biomaterials and Packaging
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05535")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391745876"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391745876"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391745876"))][Get cited by]]

OpenAlex: https://openalex.org/W4391745876 (Open access: False)
    
[[https://openalex.org/A5009884211][Mei Li]], [[https://openalex.org/A5083826274][Shengbo Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05535 
     
Photoreforming of poly(ethylene terephthalate) (PET) wastes to high-value-added chemicals is an emerging and promising approach. Nonetheless, a major obstacle is the harsh alkaline pretreatment (COH– = 5–10 M) to depolymerize PET, resulting in a surge in processing costs and also posing great challenges to subsequent photocatalytic devices, catalysts, and photocatalytic efficiency. Herein, we introduce a tandem process of chemical depolymerization and photoreforming of waste PET plastics. Depolymerization of PET to monomers is achieved through an intramolecular hydrolysis mechanism on a binuclear zinc catalyst under mild conditions (COH– ≤ 0.1 M and T ≤ 60 °C). Compared with the traditional harsh alkali pretreatment, the depolymerization rate can be increased by nearly an order of magnitude due to the proximity effect of the bimetallic sites. Technoeconomic analysis shows that processing 50,000 tons of plastic annually can save 15.2 million USD. The photoreforming of PET to formic acid and H2 with an impressive production rate of 2000 μmol gcat–1 h–1 was achieved on an ultrasmall carbon nitride nanosphere photocatalyst, which is nearly 5-fold higher than the corresponding strong alkali pretreatment system. Mechanism research reveals high photocatalytic activity thanks to the mild PET pretreatment and the efficient electron–hole separation caused by the ultrasmall carbon nitride nanosphere size structure and the electron capture effect of metal Pt. We also demonstrate a gram-scale integrated process for real-world PET plastic wastes including water bottles, clothing fibers, towels, carpets, and mixed plastics containing PET. Our study establishes a new concept of tandem catalysis to reduce the harsh pretreatment of PET by using a synthetic catalyst in polyester plastic photoreforming technology.    

    

* Oxygen Dynamics in Lean Propylene Catalytic Combustion over CeO2 and Pr6O11: Roles and Interplay between Lattice and Adsorbed Oxygen Species  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391748560
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Kinetic Analysis of Thermal Processes in Materials
:PUBLICATION_DATE: 2024-02-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05556")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391748560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391748560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391748560"))][Get cited by]]

OpenAlex: https://openalex.org/W4391748560 (Open access: False)
    
[[https://openalex.org/A5054271792][Xiwei Gao]], [[https://openalex.org/A5055626454][L. Li]], [[https://openalex.org/A5050065759][Yuquan Liu]], [[https://openalex.org/A5000696502][Zheng Chen]], [[https://openalex.org/A5060633377][Wei Liu]], [[https://openalex.org/A5052024256][Min Li]], [[https://openalex.org/A5004299496][Xiaodong Wu]], [[https://openalex.org/A5064821504][Shuang Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05556 
     
In 1954, Mars and van Krevelen proposed the famous “redox” mechanism to rationalize the oxidation of hydrocarbons (HCs) over vanadium oxide catalysts. According to this mechanism, the reduction of oxide catalysts (hydrogen abstraction, dehydroxylation, and metal–oxygen bond cleavage) are kinetically relevant in most cases, and oxides with high reducibility can be made into catalysts with high activity for HC (deep) oxidation. Such a framework, however, cannot explain the fact that Pr6O11 with the most liable lattice oxygen among lanthanide oxides is a worse low-temperature propylene oxidizer than CeO2. In this article, by comparing the kinetic/isotopic performance and the reduction/reoxidation behavior of rod-like CeO2 and Pr6O11 counterparts during lean propylene catalytic combustion, it was suggested that both these lanthanide oxides ignited propylene via a classical redox mechanism, while the reactive oxygen species involved in their following reactions were quite different. Specifically, the reactions over Pr6O11 were limited by the replenishment of lattice oxygen─the consistent workhorse reactive phase of this catalyst, and could be effectively accelerated at elevated temperature with a drastic dropping in the apparent activation energy (Eaapp, from 75.9 to 60.1 kJ/mol). In contrast, due to the relatively low electrochemical reduction potential of Ce4+/Ce3+ (1.74 eV) than that of Pr4+/Pr3+ (3.2 eV), the propylene-induced defective sites (e.g., Ce3+–VO) on CeO2–x readily donated Ce3+ 4f1 electrons to adsorbed O2 during the reoxidation steps in the redox cycles, giving rise to adsorbed oxygen species like O22– and O–. These electrophilic Oxn– species played active roles in the following reduction steps. Benefited from the “shallow” reactive region and therefore multiplied redox cycles of CeO2, such an “Oxn–-assisted” Mars–van Krevelen mechanism led to low Eaapp (∼43 kJ/mol) values close to those obtained on platinum catalysts.    

    

* Synergistic Combination of Inorganic and Organic Promoters on Palladium Catalysts for Effective Acetylene Partial Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391754932
:TOPICS: Homogeneous Catalysis with Transition Metals, Droplet Microfluidics Technology, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05474")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391754932"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391754932"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391754932"))][Get cited by]]

OpenAlex: https://openalex.org/W4391754932 (Open access: False)
    
[[https://openalex.org/A5022255903][Kyunglim Hyun]], [[https://openalex.org/A5040045316][Seongho Yun]], [[https://openalex.org/A5041659236][Minkee Choi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05474 
     
Selective acetylene partial hydrogenation in an ethylene-rich stream plays a crucial industrial role in removing acetylene impurities from ethylene produced through hydrocarbon cracking. In this study, we investigated the distinct promotional effects of Ag and amorphous polyphenylene sulfide (Am-PPS) on Pd catalysts. The addition of Ag increased the electron density of Pd and reduced the size of the Pd ensemble, effectively inhibiting undesired side reactions, such as the overhydrogenation of ethylene to ethane and the hydro-oligomerization of acetylene into C4 and heavier paraffins (green oil). However, alloying with inactive Ag resulted in a reduced number of surface-exposed active Pd atoms, leading to a significant decrease in catalytic activity. On the other hand, surface modification of Pd with Am-PPS was very effective in suppressing ethylene overhydrogenation without compromising acetylene hydrogenation activity. Furthermore, it facilitated the removal of green oil from the catalyst surface before its transformation into coke, significantly retarding the catalyst deactivation. This can be attributed to the rapid cleaning of ethylene and green oil from the Pd surface through the competitive adsorption of the Am-PPS polymer chains. The advantages of each promoter can be synergistically combined through dual promotion. The resulting catalyst exhibited moderate activity, along with exceptionally high ethylene selectivity, and suppressed formation of carbonaceous deposits (both green oil and coke). These findings demonstrate the unique potential to design advanced selective hydrogenation catalysts by leveraging the advantages of both inorganic and organic promoters.    

    

* Unraveling Rigidified Superexchange Couplings in Organic Donor–Acceptor Polymers for Boosting the Photocatalytic Reduction of Nitrate  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391755214
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05937")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391755214"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391755214"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391755214"))][Get cited by]]

OpenAlex: https://openalex.org/W4391755214 (Open access: False)
    
[[https://openalex.org/A5018527073][Haiyan Peng]], [[https://openalex.org/A5021563384][Yuhui Liu]], [[https://openalex.org/A5053065365][Yi Wang]], [[https://openalex.org/A5051422356][Meiyang Song]], [[https://openalex.org/A5083399632][Henghui Song]], [[https://openalex.org/A5012901518][Peng Chen]], [[https://openalex.org/A5086761727][Shuang‐Feng Yin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05937 
     
Regulating the spatial twist angle of flexible geometry is an effective strategy to enhance the spatial overlap in organic semiconductors and provide transfer channels for electron transfer. However, the internal migration rates of macromolecular polymers with flexible geometries and complex compositions are severely restricted, making them elusive and easily overlooked. Here, different configurations of donor–acceptor (D–A)-based perylene diimide (PDI) polymers have been elaborately designed and prepared. In fact, the high crystallinity and molecular polarity of coplanar semiconductors lead to a differentiated charge distribution and carrier transfer site, which opens the prelude for charge transfer and exciton dissociation. More importantly, the unique π-conjugated D–A configuration not only provides a smooth carrier transfer channel for promoting intermolecular electron transfer rates but is also conducive to the adsorption, diffusion, and charge exchange and activation of nitric acid as well as reduces the hydrogenation energy barrier. Ultimately, the coplanar configuration of PDI-connected 3,3-diaminobenzidine polymers (D-PDI) exhibited efficient photocatalytic nitrate reduction activity without the use of a cocatalyst and sacrificial agent. Our work provides fresh insights into molecular structure regulation to develop efficient photocatalysts for solving environmental problems.    

    

* Copper-Mediated Radical Fluorine-Atom Transfer to Sulfonyl Radical: A Dramatic 4-Methoxypyridine 1-Oxide Ligand Effect  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391771428
:TOPICS: Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05154")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391771428"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391771428"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391771428"))][Get cited by]]

OpenAlex: https://openalex.org/W4391771428 (Open access: False)
    
[[https://openalex.org/A5044717571][Hongwei Zhang]], [[https://openalex.org/A5056197830][Xiaoxiao Sun]], [[https://openalex.org/A5058075528][Cheng Ma]], [[https://openalex.org/A5043330057][Chuang Li]], [[https://openalex.org/A5059146006][Yuxiang Ni]], [[https://openalex.org/A5022683172][Yi Yu]], [[https://openalex.org/A5058527652][Yuanqing Xu]], [[https://openalex.org/A5083249296][Shao‐Fei Ni]], [[https://openalex.org/A5069715660][Zhong‐Yan Cao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05154 
     
Although the transition metal-catalyzed radical fluorine atom transfer (FAT) strategy has emerged as a powerful tool for the construction of C–F bonds, to our knowledge, this approach has rarely been applied to the formation of S–F bonds. Here, we report that 4-methoxypyridine 1-oxide can serve as an inexpensive and simple yet effective ligand and thus promote the transformation of the copper-mediated challengeable radical FAT to sulfonyl radicals, paving the way for the assembly of an FSO2 group. Based on this concept, three Cu(I)-catalyzed protocols involving site-selective intra- and intermolecular fluorosulfonylation of inert C(sp3)–H bonds and 1,2-aminofluorosulfonylation of inactivated alkenes have been developed, enabling the preparation of C(sp3)-rich aliphatic sulfonyl fluorides that cannot be easily synthesized by known methods. These practical and operationally simple methods result in high functional group tolerance under mild conditions and can be applied to the modification of bioactive derivatives and preparation of highly valued molecules. Detailed mechanistic studies indicate the unique role of the 4-methoxypyridine 1-oxide ligand in facilitating the formation of such rare radical FATs via an outer-sphere pathway.    

    

* Evolution of Phosphorylase Activity in an Ancestral Glycosyltransferase  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391772272
:TOPICS: Glycosylation in Health and Disease, Microbial Enzymes and Biotechnological Applications, Chemical Glycobiology and Therapeutic Applications
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05819")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391772272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391772272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391772272"))][Get cited by]]

OpenAlex: https://openalex.org/W4391772272 (Open access: False)
    
[[https://openalex.org/A5032037405][Jorick Franceus]], [[https://openalex.org/A5093918745][José Pablo Rivas-Fernández]], [[https://openalex.org/A5020235932][Jolien Lormans]], [[https://openalex.org/A5081831378][Carme Rovira]], [[https://openalex.org/A5003247377][Tom Desmet]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05819 
     
The reconstruction of ancestral sequences can offer a glimpse into the fascinating process of molecular evolution by exposing the adaptive pathways that shape the proteins found in nature today. Here, we track the evolution of the carbohydrate-active enzymes responsible for the synthesis and turnover of mannogen, a critical carbohydrate reserve in Leishmania parasites. Biochemical characterization of resurrected enzymes demonstrated that mannoside phosphorylase activity emerged in an ancestral bacterial mannosyltransferase, and later disappeared in the process of horizontal gene transfer and gene duplication in Leishmania. By shuffling through plausible historical sequence space in an ancestral mannosyltransferase, we found that mannoside phosphorylase activity could be toggled on through various combinations of mutations at positions outside of the active site. Molecular dynamics simulations showed that such mutations can affect loop rigidity and shield the active site from water molecules that disrupt key interactions, allowing α-mannose 1-phosphate to adopt a catalytically productive conformation. These findings highlight the importance of subtle distal mutations in protein evolution and suggest that the vast collection of natural glycosyltransferases may be a promising source of engineering templates for the design of tailored phosphorylases.    

    

* Snapshots of the Reaction Coordinate of a Thermophilic 2′-Deoxyribonucleoside/ribonucleoside Transferase  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391772277
:TOPICS: Nucleotide Metabolism and Enzyme Regulation, Efficacy and Safety of Antiretroviral Therapy for HIV, RNA Methylation and Modification in Gene Expression
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06260")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391772277"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391772277"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391772277"))][Get cited by]]

OpenAlex: https://openalex.org/W4391772277 (Open access: True)
    
[[https://openalex.org/A5015768922][Ping Tang]], [[https://openalex.org/A5086003658][Christopher John Harding]], [[https://openalex.org/A5060331025][Alison Dickson]], [[https://openalex.org/A5044599733][Rafael G. da Silva]], [[https://openalex.org/A5064922783][David J. Harrison]], [[https://openalex.org/A5023789984][Clarissa Melo Czekster]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06260  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06260][pdf]])
     
Nucleosides are ubiquitous to life and are required for the synthesis of DNA, RNA, and other molecules crucial for cell survival. Despite the notoriously difficult organic synthesis of nucleosides, 2′-deoxynucleoside analogues can interfere with natural DNA replication and repair and are successfully employed as anticancer, antiviral, and antimicrobial compounds. Nucleoside 2′-deoxyribosyltransferase (dNDT) enzymes catalyze transglycosylation via a covalent 2′-deoxyribosylated enzyme intermediate with retention of configuration, having applications in the biocatalytic synthesis of 2′-deoxynucleoside analogues in a single step. Here, we characterize the structure and function of a thermophilic dNDT, the protein from Chroococcidiopsis thermalis (CtNDT). We combined enzyme kinetics with structural and biophysical studies to dissect mechanistic features in the reaction coordinate, leading to product formation. Bell-shaped pH-rate profiles demonstrate activity in a broad pH range of 5.5–9.5, with two very distinct pKa values. A pronounced viscosity effect on the turnover rate indicates a diffusional step, likely product (nucleobase1) release, to be rate-limiting. Temperature studies revealed an extremely curved profile, suggesting a large negative activation heat capacity. We trapped a 2′-fluoro-2′-deoxyarabinosyl-enzyme intermediate by mass spectrometry and determined high-resolution structures of the protein in its unliganded, substrate-bound, ribosylated, 2′-difluoro-2′-deoxyribosylated, and in complex with probable transition-state analogues. We reveal key features underlying (2′-deoxy)ribonucleoside selection, as CtNDT can also use ribonucleosides as substrates, albeit with a lower efficiency. Ribonucleosides are the building blocks of RNA and other key intracellular metabolites participating in energy and metabolism, expanding the scope of use of CtNDT in biocatalysis.    

    

* Structure Sensitivity of ZnZrOx Catalysts in CO2 Hydrogenation to Methanol: Significance of Surface Oxygen Content and Synthesis Strategy  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391776630
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06327")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391776630"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391776630"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391776630"))][Get cited by]]

OpenAlex: https://openalex.org/W4391776630 (Open access: False)
    
[[https://openalex.org/A5031363647][Kyungho Lee]], [[https://openalex.org/A5017390847][Maxim Park Dickieson]], [[https://openalex.org/A5081246791][Minkyung Jung]], [[https://openalex.org/A5043177677][Yan Yang]], [[https://openalex.org/A5075696165][Ning Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06327 
     
Understanding the relationship between catalyst structure and activity is crucial to advancing catalytic processes such as CO2 hydrogenation to methanol. In this study, we investigated the impact of various synthesis conditions on the structural properties and catalytic activity of ZnO–ZrO2 solid solution (ZnZrOx) catalysts. By systematically adjusting the drying method, calcination temperature, postsynthesis ball-milling time, and use of additives, we synthesized a series of ZnZrOx catalysts with varying surface area (4.5–106 m2 g–1) and surface oxygen content [O/(Zn + Zr) = 1.60–2.04] and similar surface Zn content [Zn/(Zn + Zr) = ca. 0.20]. Our experimental and computational studies revealed that methanol synthesis over ZnZrOx catalysts is structure-sensitive and that area-normalized activity is positively correlated with the oxygen content on the catalyst surface. The surface lattice oxygen (O2–) played a crucial role in H2 activation, which is the rate-determining step for methanol formation; therefore, oxygen-rich regimes serve as the main active sites for CO2 hydrogenation to methanol. From a fundamental point of view, this study highlights the importance of surface oxygen content for catalytic activity, which has been previously overlooked. From an engineering standpoint, our investigations suggest that ZnZrOx catalysts bearing oxygen-rich surfaces combined with high surface areas can exhibit desirable catalytic activity, thus guiding the rational synthesis strategy to the development of oxide-based hydrogenation catalysts.    

    

* Facile Synthesis of Vinyl Boronate Esters via Dehydrogenative Borylation of Alkenes Enabled by a Co-MOF Catalyst: An Additive-Free Approach  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391776709
:TOPICS: Frustrated Lewis Pairs Chemistry, Chemistry and Applications of Metal-Organic Frameworks, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05742")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391776709"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391776709"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391776709"))][Get cited by]]

OpenAlex: https://openalex.org/W4391776709 (Open access: False)
    
[[https://openalex.org/A5085820939][Suma Basappa]], [[https://openalex.org/A5001458814][Aishwarya Prakash]], [[https://openalex.org/A5093881181][Sanjana S. Talekar]], [[https://openalex.org/A5061653732][Manoj V. Mane]], [[https://openalex.org/A5053302759][Shubhankar Kumar Bose]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05742 
     
No abstract    

    

* The Effects of ≡Ti–OH Site Distortion and Product Adsorption on the Mechanism and Kinetics of Cyclohexene Epoxidation over Ti/SiO2  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391777161
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06073")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391777161"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391777161"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391777161"))][Get cited by]]

OpenAlex: https://openalex.org/W4391777161 (Open access: False)
    
[[https://openalex.org/A5083844609][Branden E. Leonhardt]], [[https://openalex.org/A5015311244][Martin Head‐Gordon]], [[https://openalex.org/A5087957929][Alexis T. Bell]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06073 
     
No abstract    

    

* Construction of Surface Synergetic Oxygen Vacancies on CuMn2O4 Spinel for Enhancing NO Reduction with CO  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391777530
:TOPICS: Catalytic Nanomaterials, Gas Sensing Technology and Materials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05337")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391777530"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391777530"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391777530"))][Get cited by]]

OpenAlex: https://openalex.org/W4391777530 (Open access: False)
    
[[https://openalex.org/A5010240435][Xiaolin Xu]], [[https://openalex.org/A5080940833][Xueqing Liu]], [[https://openalex.org/A5041550151][Liang Ma]], [[https://openalex.org/A5005275225][Ningning Liang]], [[https://openalex.org/A5000180953][Shan Yang]], [[https://openalex.org/A5045027403][Hao Liu]], [[https://openalex.org/A5053484557][Jingfang Sun]], [[https://openalex.org/A5004948530][Fang Huang]], [[https://openalex.org/A5064575734][Chuanzhi Sun]], [[https://openalex.org/A5073123246][Lin Dong]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05337 
     
The effectiveness of surface synergetic oxygen vacancy (SSOV) on a catalyst has been proposed in the selective reduction of NO to N2 by CO. In this work, we prepared fresh CuMn2O4 spinel catalyst using the freeze-assisted sol–gel method, and then engineered SSOVs through CO pretreatment (CO–CuMn2O4) at 250 °C. The catalytic performance of the CO–CuMn2O4 catalyst showed significant improvement, attributed to the presence of SSOVs, in comparison to that of the fresh CuMn2O4 sample. Additionally, our findings elucidated the limited reactivity of surface oxygen vacancies (SOVs) on a single metal oxide, emphasizing the crucial role played by SSOVs. Experimental results, including NO temperature-programmed desorption-mass spectrometry and in situ diffuse reflectance infrared Fourier transform spectroscopy, provided further insights by suggesting that SSOVs facilitate the formation of N2O and its subsequent decomposition into N2. Density functional theory calculations have unveiled the pivotal role of SSOV in stabilizing the nitrogen atom derived from gaseous NO, facilitating the NO + CO → N* + CO2 reaction. Notably, the energy barrier for this process is only 0.54 eV, which is the rate-determining step of the NO + CO reaction. In stark contrast, this reaction scarcely occurs on the SOVs of single CuO and Mn2O3 surfaces. Furthermore, the presence of SSOVs considerably lowers the energy barrier for the conversion of N2O to N2, with a minimal barrier of 0.12 eV. In contrast, the reduction of N2O by CO without SSOV assistance necessitates a significantly higher energy barrier of 2.77 eV. Extending our investigation, we engineered SSOVs on the CuFe2O4 spinel catalyst and observed similar SSOV-mediated effects in the NO + CO reaction. Our research offers a comprehensive understanding of atomic-level role of SSOV, thereby offering valuable insights for the design of efficient NO + CO catalysts.    

    

* Design and Applications of Cyclopropenium Chalcogen Dihalides in Catalysis via C(sp3)–H···X Interactions  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391778595
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis, Click Chemistry in Chemical Biology and Drug Development
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00087")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391778595"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391778595"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391778595"))][Get cited by]]

OpenAlex: https://openalex.org/W4391778595 (Open access: True)
    
[[https://openalex.org/A5053185512][Junjie Yang]], [[https://openalex.org/A5040092039][Yabin Zhang]], [[https://openalex.org/A5034103172][Henry Wong]], [[https://openalex.org/A5087658293][Jingxian Huang]], [[https://openalex.org/A5061946299][Ying‐Lung Steve Tse]], [[https://openalex.org/A5016128867][Ying‐Yeung Yeung]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00087  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00087][pdf]])
     
No abstract    

    

* Ir Single Atom-Doped Ni2P Anchored by Carbonized Polymer Dots for Robust Overall Water Splitting  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391780168
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05901")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391780168"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391780168"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391780168"))][Get cited by]]

OpenAlex: https://openalex.org/W4391780168 (Open access: False)
    
[[https://openalex.org/A5045168110][Da Yue]], [[https://openalex.org/A5055262287][Tanglue Feng]], [[https://openalex.org/A5016257287][Zhicheng Zhu]], [[https://openalex.org/A5085836074][Siyu Lu]], [[https://openalex.org/A5000046177][Bai Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05901 
     
Developing high-performance bifunctional electrocatalysts for hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) is imperative in facilitating large-scale production of hydrogen. Herein, we develop an atomically dispersed catalyst, Ir–Ni2P/CPDs, in which iridium single atoms are dual-anchored by both carbonized polymer dots (CPDs) and Ni2P. CPDs serve as electronic bridges, which facilitate the construction of high-density oxygen bridge structures, leading to high loading of isolated Ir atoms that act as the principal active sites for HER and OER. The resultant Ir–Ni2P/CPD catalyst demonstrates low overpotentials of only 25 ± 1 and 240 ± 2 mV at 10 mA cm–2 for HER and OER in 1.0 M KOH solution, respectively, surpassing those of commercial Pt/C and IrO2 catalysts. Moreover, it exhibits robust long-term catalytic stability. The experimental and theoretical results demonstrate that the bonding environment of dual-anchored isolated Ir sites plays an essential role in optimizing the adsorption and desorption kinetics of hydrogen/oxygen intermediates. This work extends a strategy for the design of high-loaded metal single-atom electrocatalysts for greatly facilitating HER and OER activities.    

    

* Peroxygenase-Catalyzed Allylic Oxidation Unlocks Telescoped Synthesis of (1S,3R)-3-Hydroxycyclohexanecarbonitrile  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391785338
:TOPICS: Enzyme Immobilization Techniques, Chiral Separation in Chromatography, Drug Metabolism and Pharmacogenomics
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00177")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391785338"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391785338"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391785338"))][Get cited by]]

OpenAlex: https://openalex.org/W4391785338 (Open access: True)
    
[[https://openalex.org/A5025739763][Christian M. Heckmann]], [[https://openalex.org/A5092931390][Moritz Bürgler]], [[https://openalex.org/A5091020378][Caroline E. Paul]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00177  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00177][pdf]])
     
The unmatched chemo-, regio-, and stereoselectivity of enzymes renders them powerful catalysts in the synthesis of chiral active pharmaceutical ingredients (APIs). Inspired by the discovery route toward the LPA1-antagonist BMS-986278, access to the API building block (1S,3R)-3-hydroxycyclohexanecarbonitrile was envisaged using an ene reductase (ER) and alcohol dehydrogenase (ADH) to set both stereocenters. Starting from the commercially available cyclohexene-1-nitrile, a C–H oxyfunctionalization step was required to introduce the ketone functional group, yet several chemical allylic oxidation strategies proved unsuccessful. Enzymatic strategies for allylic oxidation are underdeveloped, with few examples on selected substrates with cytochrome P450s and unspecific peroxygenases (UPOs). In this case, UPOs were found to catalyze the desired allylic oxidation with high chemo- and regioselectivity, at substrate loadings of up to 200 mM, without the addition of organic cosolvents, thus enabling the subsequent ER and ADH steps in a three-step one-pot cascade. UPOs even displayed unreported enantioselective oxyfunctionalization and overoxidation of the substituted cyclohexene. After screening of enzyme panels, the final product was obtained at titers of 85% with 97% ee and 99% de, with a substrate loading of 50 mM, the ER being the limiting step. This synthetic approach provides the first example of a three-step, one-pot UPO-ER-ADH cascade and highlights the potential for UPOs to catalyze diverse enantioselective allylic hydroxylations and oxidations that are otherwise difficult to achieve.    

    

* Computational Discovery of Codoped Single-Atom Catalysts for Methane-to-Methanol Conversion  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391785393
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05506")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391785393"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391785393"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391785393"))][Get cited by]]

OpenAlex: https://openalex.org/W4391785393 (Open access: False)
    
[[https://openalex.org/A5034971788][Haojun Jia]], [[https://openalex.org/A5029457626][Chenru Duan]], [[https://openalex.org/A5009462742][Ilia Kevlishvili]], [[https://openalex.org/A5038652876][Aditya Nandy]], [[https://openalex.org/A5084041903][Mingjie Liu]], [[https://openalex.org/A5050671822][Heather J. Kulik]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05506 
     
The absence of a synthetic catalyst that can selectively oxidize methane to methanol motivates extensive study of single-site catalysts that possess a high degree of tunability in their coordination environments and share similarities with natural enzymes that can catalyze this reaction. Single-atom catalysts (SACs), in particular doped graphitic SACs, have emerged as a promising family of materials due to their high atom economy and scalability, but SACs are yet to be exhaustively screened for methane-to-methanol conversion. Modulating the coordination environment near single metal sites by means of codopants, we carry out a large-scale high-throughput virtual screen of 2048 transition metal (i.e., Mn, Fe, Co, and Ru) SACs codoped with various elements (i.e., N, O, P, and S) in numerous spin and oxidation (i.e., M(II)/M(III)) states for the challenging conversion of methane to methanol. We identify that the ground-state preference is metal- and oxidation-state-dependent. We observe a weak negative correlation between the oxo formation energy (ΔE(oxo)) and the energy of hydrogen atom transfer (ΔE(HAT)), thanks to the high variability in the coordination environment. Therefore, codoped SACs demonstrate flexible tunability that disrupts linear free energy relationships in a manner similar to that of homogeneous catalysts without losing the scalability of heterogeneous catalysts. We identify energetically favorable catalyst candidates along the Pareto frontier of ΔE(oxo) and ΔE(HAT). Further kinetic analysis reveals an intermediate-spin Fe(II) SAC and a low-spin Ru(II) SAC as promising candidates that merit further experimental exploration.    

    

* Carbon Materials Containing Single-Atom Co–N4 Sites Enable Near-Infrared Photooxidation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391786312
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Upconversion Nanoparticles
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05441")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391786312"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391786312"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391786312"))][Get cited by]]

OpenAlex: https://openalex.org/W4391786312 (Open access: False)
    
[[https://openalex.org/A5036824294][Longjian Li]], [[https://openalex.org/A5033737778][Junhui Wang]], [[https://openalex.org/A5052585046][Qinhua Zhang]], [[https://openalex.org/A5006901857][Shuai Wang]], [[https://openalex.org/A5033444314][Hangkai Zhang]], [[https://openalex.org/A5022433710][Tao Xing]], [[https://openalex.org/A5012870141][Mingqing Wang]], [[https://openalex.org/A5063554744][Mingbo Wu]], [[https://openalex.org/A5057425584][Zhenxing Wang]], [[https://openalex.org/A5080124839][Wenting Wu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05441 
     
Near-infrared light occupies 54.3% of the solar spectrum and has greater penetration depth, and its effective utilization is of great significance in the practical application of photocatalysis on a larger scale. However, the development of catalysts that can directly utilize near-infrared light is still a huge challenge. This paper proposes a strategy to directly utilize near-infrared light (excitation wavelength extending to 850 nm) by creating carbon material doped with a high-spin-state Co(II)-Nx single-atom site. In the near-infrared-light-irradiated photooxidation of 1,5-dihydroxynaphthalene, the yield of juglone can reach 45% without a significant decrease, even when the catalytic volume is increased by 20 times, which was much higher than that irradiated by 460 nm wavelength (reduced by about 23%). Our study sets the stage for fabricating stable NIR photocatalysts and provides a solution to directly enhance NIR photooxidation in a large-scale manner.    

    

* A Water-Promoted Mars−van Krevelen Reaction Dominates Low-Temperature CO Oxidation over Au-Fe2O3 but Not over Au-TiO2  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391806007
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05978")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391806007"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391806007"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391806007"))][Get cited by]]

OpenAlex: https://openalex.org/W4391806007 (Open access: True)
    
[[https://openalex.org/A5013981591][Alexander Holm]], [[https://openalex.org/A5045357923][Bernadette Davies]], [[https://openalex.org/A5026383153][Sara Boscolo Bibi]], [[https://openalex.org/A5000887640][Félix Moncada]], [[https://openalex.org/A5092656027][Joakim Halldin-Stenlid]], [[https://openalex.org/A5092656028][Laurynas Paškevičius]], [[https://openalex.org/A5092656029][Vincent Claman]], [[https://openalex.org/A5004773873][Adam Slabon]], [[https://openalex.org/A5034520322][Cheuk‐Wai Tai]], [[https://openalex.org/A5007728343][Egon Campos dos Santos]], [[https://openalex.org/A5048699879][Sergey Koroidov]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05978  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05978][pdf]])
     
No abstract    

    
