#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Mon Feb 26 00:45:04 2024

Found 25 results from 2024-02-19 to 2024-02-26
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Near-Infrared Photoredox Catalyzed Fluoroalkylation Strategy for Protein Labeling in Complex Tissue Environments  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391923508
:TOPICS: Click Chemistry in Chemical Biology and Drug Development, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Therapeutic Antibodies: Development, Engineering, and Applications
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00447")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391923508"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391923508"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391923508"))][Get cited by]]

OpenAlex: https://openalex.org/W4391923508 (Open access: False)
    
[[https://openalex.org/A5091564568][Keun Ah Ryu]], [[https://openalex.org/A5024757326][Tamara Reyes‐Robles]], [[https://openalex.org/A5013377903][Thomas P. Wyche]], [[https://openalex.org/A5039265534][Tyler J. Bechtel]], [[https://openalex.org/A5061974174][Jayde M. Bertoch]], [[https://openalex.org/A5085429602][Ziliang Jin]], [[https://openalex.org/A5091071427][Christopher May]], [[https://openalex.org/A5093952691][Cody Scandore]], [[https://openalex.org/A5093952692][Noah Dephoure]], [[https://openalex.org/A5075921743][Sharon Wilhelm]], [[https://openalex.org/A5026076840][Ishtiaque Quasem]], [[https://openalex.org/A5003459682][Annika Yau]], [[https://openalex.org/A5088823053][Sampat Ingale]], [[https://openalex.org/A5066277037][Andrew Szendrey]], [[https://openalex.org/A5050276726][Margaret Duich]], [[https://openalex.org/A5073194775][Rob C. Oslund]], [[https://openalex.org/A5037325947][Olugbeminiyi O. Fadeyi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00447 
     
The chemical transformation of aromatic amino acids has emerged as an attractive alternative to nonselective lysine or cysteine labeling for the modification of biomolecules. However, this strategy has largely been limited by the scope of functional groups and the biocompatible reaction conditions available. Herein, we report the implementation of near-infrared-activatable photocatalysts, TTMAPP and n-Pr-DMQA+, capable of generating fluoroalkyl radicals for peptide functionalization and protein labeling within simple and complex biological systems. At the peptide level, a diverse set of iodoperfluoroalkyl reagents were used in the functionalization and stapling of tryptophan residues. Using this photoredox catalyzed perfluoroalkylation technology, we achieved biotinylation of intracellular proteins in live cells. Notably, given the inherent tissue penetrant nature of near-infrared light, we further demonstrated the utility of this technology to achieve photocatalytic protein fluoroalkylation in patient-derived normal and tumor tissue for downstream confocal imaging and mass spectrometry-based proteomic analysis.    

    

* Strong Hydrogen-Bonded Interfacial Water Inhibiting Hydrogen Evolution Kinetics to Promote Electrochemical CO2 Reduction to C2+  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391926255
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05880")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391926255"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391926255"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391926255"))][Get cited by]]

OpenAlex: https://openalex.org/W4391926255 (Open access: False)
    
[[https://openalex.org/A5078232760][Yang Wang]], [[https://openalex.org/A5039365969][Jianrui Zhang]], [[https://openalex.org/A5009225446][Jianyun Zhao]], [[https://openalex.org/A5042449935][Yuantao Wei]], [[https://openalex.org/A5032988244][Shenghua Chen]], [[https://openalex.org/A5023780872][Hongyang Zhao]], [[https://openalex.org/A5013121247][Yaqiong Su]], [[https://openalex.org/A5065434610][Shujiang Ding]], [[https://openalex.org/A5049259092][Chunhui Xiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05880 
     
Interfacial water is an important participant in electrochemical CO2 reduction (CO2RR), directly affecting the kinetics of hydrogenation steps occurring in the CO2RR and competitive hydrogen evolution reaction (HER). However, its structural composition and dynamic evolution are difficult to investigate due to bulk water interference and the bias dependence. Herein, we adopt electrochemical in situ vibration spectroscopy combined with molecular dynamics simulations to probe the dynamic change of interfacial water structure on an electrified hydrophobic electrode surface and further explore the mechanism origin of suppressed HER activity and enhanced multicarbon products’ selectivity. We reveal that interfacial water near the hydrophobic electrode surface exhibits rigid intermolecular hydrogen bonding interaction, and the degree of which increases with a bias potential. The strong intermolecular hydrogen bond makes it hard for water reorientation leading to a longer metal–H distance, which inhibits water dissociation and decreases *H coverage. Moderate *H coverage not only inhibits hydrogen evolution but also ensures hydrogenation of intermediates realizing promoted C–C dimerization. A faradaic efficiency of 75.2% for CO2 reduction to multicarbon products was ultimately achieved. Our results provide insights into understanding the role of interfacial water structure in controlling reaction selectivity in CO2RR.    

    

* Ultrathin and Conformal TiOx Overlayers on WO3 Photoelectrodes for Simultaneous Surface Trap Passivation and Heterojunction Formation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391931816
:TOPICS: Emergent Phenomena at Oxide Interfaces, Gas Sensing Technology and Materials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05876")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391931816"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391931816"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391931816"))][Get cited by]]

OpenAlex: https://openalex.org/W4391931816 (Open access: False)
    
[[https://openalex.org/A5066711967][Anchen Wang]], [[https://openalex.org/A5076157080][Dapeng Cao]], [[https://openalex.org/A5060032896][Fuyang Zhang]], [[https://openalex.org/A5037446400][Yaru Chen]], [[https://openalex.org/A5076151179][Jianyong Feng]], [[https://openalex.org/A5068288947][Dong Fang]], [[https://openalex.org/A5011436888][Baoxiu Mi]], [[https://openalex.org/A5006671043][Zhiqiang Gao]], [[https://openalex.org/A5061375599][Zhaosheng Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05876 
     
Nanoporous structures facilitate the exposure of active sites and allow a high ratio of the space charge region to the bulk in water-splitting photoelectrodes. However, unfavorable surface defects may develop on nanoporous photoelectrodes, which deteriorate the band bending (built-in electric field) and trigger serious charge carrier recombination. To maximize the advantages of nanoporous structures in photoelectrodes, one common strategy is the introduction of ultrathin overlayers to passivate undesirable surface defects and traps, which usually require advanced deposition technologies such as atomic layer deposition. In this study, a process of drop-casting followed by O2 plasma treatment is employed to realize ultrathin and conformal TiOx overlayers on WO3 photoelectrodes. Notably, the ultrathin TiOx overlayer demonstrates dual effects of surface trap passivation and heterojunction formation on WO3 photoelectrodes, which result in suppressed surface charge recombination and enhanced band bending. The as-derived TiOx-modified WO3 photoanode shows an increase in water-splitting photocurrent (increased by 81% at 1.6 V vs the reversible hydrogen electrode), along with a 160 mV cathodic shift in photocurrent onset potential. The proposed approach here provides valuable insights into the room-temperature fabrication of uniform and ultrathin overlayers for nanostructure modification.    

    

* Strain-Engineered Ru-NiCr LDH Nanosheets Boosting Alkaline Hydrogen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391933113
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05550")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391933113"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391933113"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391933113"))][Get cited by]]

OpenAlex: https://openalex.org/W4391933113 (Open access: False)
    
[[https://openalex.org/A5051262214][Jun Yang]], [[https://openalex.org/A5078376139][Shi Chun Yang]], [[https://openalex.org/A5036448935][Liwei An]], [[https://openalex.org/A5055911393][Jiang Zhu]], [[https://openalex.org/A5038128096][Junwu Xiao]], [[https://openalex.org/A5072939924][Xu Zhao]], [[https://openalex.org/A5088757374][Deli Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05550 
     
Ruthenium (Ru) has been considered as a promising candidate for alkaline hydrogen evolution reaction (HER); however, the hydrogen adsorption on Ru needs to be optimized to enhance the electrocatalytic activity. Strain engineering is an effective method to regulate the hydrogen adsorption, while the systematic study of the strain effect over hydrogen adsorption of Ru remains a challenge. Herein, Ru-incorporated nickel–chromium-layered double hydroxide (LDH) nanosheets with different levels of compressive strain are constructed to tune the hydrogen adsorption. The strain-engineered Ru-NiCr LDH exhibits a low overpotential of 30 mV at 100 mA cm–2 and good stability over 10,000 potential cycles for HER. When the cathode catalysts are assembled in an anion exchange membrane water electrolyzer (AEMWE), the cell delivers high current densities of 640 and 1940 mA cm–2 at 1.8 V when fed with pure water and 1 M KOH solution, respectively. The enhanced electrocatalytic performance of Ru-NiCr LDH is attributed to the weakened hydrogen adsorption caused by a downshift of the d-band center, which is induced by the strain effect. This work demonstrates the effectiveness of strain engineering in designing active catalysts for hydrogen production.    

    

* Facet-Dependent Oxygen Mobility and Reaction Pathways for Oxidative Dehydrogenation of 1-Butene over Bi2MoO6  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391954093
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391954093"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391954093"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391954093"))][Get cited by]]

OpenAlex: https://openalex.org/W4391954093 (Open access: False)
    
[[https://openalex.org/A5066740638][Qinyang Zhao]], [[https://openalex.org/A5054555763][Xinglin Hou]], [[https://openalex.org/A5037414724][Xiaoling Liu]], [[https://openalex.org/A5046837708][Mingben Chong]], [[https://openalex.org/A5057307441][Dang-guo Cheng]], [[https://openalex.org/A5078614480][Fengqiu Chen]], [[https://openalex.org/A5054301490][Xiaoli Zhan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00014 
     
The crystal facet effect is a critical factor for catalytic reactions on metal oxides due to the different atomic arrangements and physicochemical properties of diverse facets. Based on a series of combined experimental and theoretical measurements, this work investigates facet-dependent oxygen mobility and reaction pathways for the oxidation dehydrogenation (ODH) of 1-butene to 1,3-butadiene on Bi2MoO6, which exposes the {001} and {010} facets (BMO-001 and BMO-010). The results show that the oxygen mobility of BMO-001 overwhelmingly outperforms that of BMO-010, reflecting the better capacities for selective abstraction of H from 1-butene, oxygen replenishment, and bulk lattice oxygen migration. Density functional theory (DFT) calculations indicate that the rate-determining step on the {001} facet is the abstraction of the first H in 1-butene and the abstraction of the second H on the {010} facet. The existence of the [Bi2O2]2+ layer provides a favorable channel with a low-energy barrier for bulk lattice oxygen migration toward the {001} facet. Besides, complex side reactions occur on the {010} facet, including the nonselective oxidation of 1-butene, aromatization of 1-butene, and the generation of CO and subsequent formates. The total oxidation and decomposition of byproducts result in extra CO2 formation pathways. Lattice and gaseous oxygen play different roles in the above reactions. The superior oxygen mobility contributes to the high 1,3-butadiene yield for BMO-001, while the extra CO2 formation pathways lead to an abnormally high CO2 yield for BMO-010. The generated aromatic coke and formates affect the catalytic stability of BMO-010. The facet-dependent oxygen mobility and reaction pathways result in a distinct catalytic performance for 1-butene ODH.    

    

* Reactant-Induced Dynamic Stabilization of Highly Dispersed Pt Catalysts on Ceria Dictating the Reactivity of CO Oxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391960667
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05590")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391960667"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391960667"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391960667"))][Get cited by]]

OpenAlex: https://openalex.org/W4391960667 (Open access: False)
    
[[https://openalex.org/A5063253432][Chen Chen]], [[https://openalex.org/A5065179197][J. H. Chen]], [[https://openalex.org/A5042754358][Feng Li]], [[https://openalex.org/A5053866420][Jianyu Hu]], [[https://openalex.org/A5049686530][Xuting Chai]], [[https://openalex.org/A5083885267][Jin‐Xun Liu]], [[https://openalex.org/A5055160391][Wei‐Xue Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05590 
     
No abstract    

    

* Selective Light Hydrocarbon Production from CO2 Hydrogenation over Na/ZnFe2O4 and CHA-Zeolite Hybrid Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391962385
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Carbon Dioxide Hydrogenation, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00099")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391962385"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391962385"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391962385"))][Get cited by]]

OpenAlex: https://openalex.org/W4391962385 (Open access: False)
    
[[https://openalex.org/A5010426528][Eun Cheol]], [[https://openalex.org/A5015699501][Kwang Hyun Kim]], [[https://openalex.org/A5030105303][Ju Hyeong Lee]], [[https://openalex.org/A5011263889][Sejin Jang]], [[https://openalex.org/A5033294084][Hyo Eun Kim]], [[https://openalex.org/A5091323069][Jin Ho Lee]], [[https://openalex.org/A5074132019][Eun Hyup Kim]], [[https://openalex.org/A5069395205][Haneul Kim]], [[https://openalex.org/A5020130636][Ja Hun Kwak]], [[https://openalex.org/A5010021409][Jin Ho Lee]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00099 
     
Carbon dioxide hydrogenation to value-added fuels and chemicals has been studied widely as a means to recycle the most-troublesome greenhouse gas. The reaction produces hundreds of different chemicals, and therefore, selectivity control toward specific desired products is of paramount importance. In this study, a hybrid catalyst system consisting of Na/ZnFe2O4 (ZFO) and a CHA-zeolite (SSZ-13 or SAPO-34) is developed to maximize C2–C4 light hydrocarbon production. Utilizing the compact 3.8 Å pore size of CHA-zeolites, the Na/ZnFe2O4 catalyst-produced long-chain hydrocarbons are efficiently shortened to C2–C4 hydrocarbons with over 55% selectivity in the hybrid systems. Notably, ZFO + SAPO-34 shows a preference for light olefins, while ZFO + SSZ-13 uniquely enhances selectivity for C3 products. The difference is attributed to the much stronger acid sites present in SSZ-13 than in SAPO-34, which promote hydrogenation of olefins and the ethylene-to-propane conversion reaction in particular. Further modification of SSZ-13 with steam treatment leads to the dealumination of its framework and an enhanced activity of the ethylene-to-propane reaction, yielding 32.8% of C3-selectivity. Accordingly, a hybrid catalytic system combining a CO2 Fischer–Tropsch catalyst with a CHA-zeolite is a promising route to produce light hydrocarbons from CO2 hydrogenation more selectively than single catalysts. This work also demonstrates that acidity control could be a powerful tool to manipulate the reaction pathway that occurs on zeolite catalysts.    

    

* Influence of Solvents on Catalytic C–H Bond Oxidation by a Copper(II)–Alkylperoxo Complex  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391966230
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Catalytic Oxidation of Alcohols, Role of Porphyrins and Phthalocyanines in Materials Chemistry
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05643")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391966230"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391966230"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391966230"))][Get cited by]]

OpenAlex: https://openalex.org/W4391966230 (Open access: False)
    
[[https://openalex.org/A5071287711][Yuri Lee]], [[https://openalex.org/A5071819181][Bohee Kim]], [[https://openalex.org/A5037676293][S.C. Kim]], [[https://openalex.org/A5032928208][Elvis Wang Hei Ng]], [[https://openalex.org/A5026169219][Shinya Ariyasu]], [[https://openalex.org/A5073588774][Shoji Okada]], [[https://openalex.org/A5088135920][Sungho Yoon]], [[https://openalex.org/A5048588199][Hajime Hirao]], [[https://openalex.org/A5023832222][Jaeheung Cho]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05643 
     
Oxidation of unactivated alkanes, which requires substantial energy for conversion to valuable organic chemicals, is a major challenge in both industry and academia. Herein, we describe how solvents affect and improve the catalytic oxidation ability of a mononuclear copper(II)–alkylperoxo complex, [CuII(iPr3-tren)(OOC(CH3)2Ph)]+ (1, iPr3-tren = tris[2-(isopropylamino)ethyl]amine), toward hydrocarbon substrates. 1 was prepared by adding cumene hydroperoxide and triethylamine to the solution of [Cu(iPr3-tren)(CH3CN)]2+, which was characterized using various physicochemical methods. Product analyses, along with theoretical calculations, indicate that homolytic O–O bond cleavage occurs during the thermal decomposition of 1 at 60 °C in various solvents such as CH3CN, CH3COCH3, C6H5CF3, and C6H6. Both experimental results and density functional theory (DFT) calculations supported variations in the catalytic activity of 1 depending on solvents. In CH3CN and CH3COCH3, 1 activates weak C–H bonds (bond dissociation energy (BDE) ≤ ∼81.6 kcal mol–1), while 1 in C6H5CF3 and C6H6 can oxidize slightly stronger C–H bonds with a BDE of up to 84.5 kcal mol–1. In supercritical carbon dioxide (SC-CO2), 1 can oxidize alkanes with strong C–H bonds, such as cyclohexane (99.5 kcal mol–1). The enhanced C–H bond oxidation of 1 in C6H5CF3, C6H6, and SC-CO2 was generally attributed to two different factors: (a) the nonpolarity of the solvent and (b) the absence of C(sp3)–H bonds in the solvent. Interestingly, in CH2Cl2, a nonpolar solvent with C(sp3)–H bonds, 1 exhibited similar reactivity to that in C6H5CF3, indicating that nonpolar solvents enhance the catalytic ability of copper(II)–cumylperoxo complex to abstract hydrogen atoms from substrates, regardless of the presence of C(sp3)–H bonds in solvent molecules. DFT calculations employing an implicit solvent model further supported the enhanced reactivity, without the need to account for the presence of a C(sp3)–H bond. The reactivity of the different possible reactive intermediates arising from the catalytic oxidation was also explored using DFT calculations. This study provides a perspective on how solvents can be utilized to modulate the catalytic effects on C–H bond activation.    

    

* Design of Ancestral Sortase E that is Applicable in Protein Biomaterial Synthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391970017
:TOPICS: Cyclotide Bioengineering and Protein Anchoring Mechanisms
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00487")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391970017"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391970017"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391970017"))][Get cited by]]

OpenAlex: https://openalex.org/W4391970017 (Open access: False)
    
[[https://openalex.org/A5003209535][Azusa Miyata]], [[https://openalex.org/A5037242367][Taichi Chisuga]], [[https://openalex.org/A5007397302][Akira Kambe]], [[https://openalex.org/A5034123646][Ryo Miyata]], [[https://openalex.org/A5074729200][Yui Kawamura]], [[https://openalex.org/A5078618329][Hiroyuki Takeda]], [[https://openalex.org/A5037114896][Sohei Ito]], [[https://openalex.org/A5068648492][Shogo Nakano]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00487 
     
Protein biomaterials would have the potential to address global challenges in health and environment. Numerous production methods of the biomaterials exist, with sortase-mediated ligation (SML) being one of the representative technique. SML facilitates the site-specific conjugation of two compounds: donor peptides or proteins with a cell wall sorting signal at their C-terminus and nucleophiles that have oligoglycine at their N-terminal. In our research, we reconstructed an ancestral sortase E, named AcSE5, through a combination of sequence data mining and ancestral sequence reconstruction. AcSE5, a Ca2+ independent sortase, recognizes donors with LAETG at their C-termini and can employ both peptides bearing GGG- or GAA-at N-terminus and straight-chained alkylamines as nucleophiles. The enzyme can achieve efficient peptide conjugation, exceeding 70% under optimal conditions. With AcSE5, we synthesized two protein conjugates: Venus-conjugated shark variable new antigen receptor (VNAR) and dual-conjugated VNAR via poly(ethylene) glycol diamine. Direct enzyme immobilization to amino-terminated polystyrene beads was also achieved using AcSE5. The resultant beads, when conjugated with hyper-thermostable ancestral l-amino acid oxidases (HTAncLAAO2), can be employed for deracemization of various racemic amino acids into d-form. For three of phenylalanine derivatives, preparative-scale (100 mg scale) deracemization can be achieved. This process provides high enantiopurity (>99% ee) and isolation yields (>64%) through chemoenzymatic reactions. The immobilized HTAncLAAO2 showed complete resistance to 10 repeated reactions for a total of 240 h. AcSE5 is an excellent enzyme for SML applications.    

    

* Alanyl-tRNA Synthetase-like Enzyme-Catalyzed Aminoacylation in Nucleoside Sulfamate Ascamycin Biosynthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391972423
:TOPICS: Peptide Synthesis and Drug Discovery, Nucleotide Metabolism and Enzyme Regulation, Ribosome Structure and Translation Mechanisms
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05667")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391972423"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391972423"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391972423"))][Get cited by]]

OpenAlex: https://openalex.org/W4391972423 (Open access: False)
    
[[https://openalex.org/A5079670930][Yu Zheng]], [[https://openalex.org/A5070694863][Naoko Morita]], [[https://openalex.org/A5050788544][Hiroshi Takagi]], [[https://openalex.org/A5004540211][Yumi Shiozaki-Sato]], [[https://openalex.org/A5080908654][Jun Ishikawa]], [[https://openalex.org/A5055131198][Kazuo Shin‐ya]], [[https://openalex.org/A5021597347][Shunji Takahashi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05667 
     
The adenosine 5′-monophosphate-mimicking nucleoside sulfamates are pharmaceutically important compounds that target aminoacyl-tRNA synthetases (aaRSs) and other adenylate-forming enzymes. Ascamycin (1) is a unique naturally occurring alanyl adenosine sulfamate isolated from Streptomyces sp. 80H647. In this study, we successfully enhanced the in vivo conversion of dealanylascamycin (2) to ascamycin by constitutively expressing an extra copy of bldA and adpA regulatory genes. More importantly, we performed gene expression analysis and protein structure–function prediction to identify alanyl-tRNA synthetase (AlaRS)-like enzymes: AcmF and AcmD. AcmF efficiently catalyzes the aminoacylation reaction during ascamycin biosynthesis, and this reaction is dependent on the Ala-tRNAAla supplied by AcmD. AcmF is a truncated AlaRS-like enzyme containing only the aminoacylation and tRNA recognition domains, whereas AcmD has an intact AlaRS-like architecture that efficiently supports AcmF activity by exhibiting resistance to the AcmF-produced ascamycin. In addition, we have produced the glycyl- and seryl-derivatives of ascamycin using the AcmD-AcmF enzyme pair. The mechanistic study identified Glu232 and several residues that play important roles in AcmF catalysis. To the best of our knowledge, AcmF is a representative class II aaRS-like enzyme catalyzing tRNA-dependent aminoacylation during natural product biosynthesis. These findings provide a potential chemoenzymatic approach for the synthesis of aminoacyl nucleoside sulfamates.    

    

* Designing Local Electron Delocalization in 2D Covalent Organic Frameworks for Enhanced Sunlight-Driven Photocatalytic Activity  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391972463
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Photocatalytic Materials for Solar Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05648")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391972463"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391972463"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391972463"))][Get cited by]]

OpenAlex: https://openalex.org/W4391972463 (Open access: False)
    
[[https://openalex.org/A5088406552][Xiaochen Zhang]], [[https://openalex.org/A5015123614][Xianhui Xu]], [[https://openalex.org/A5088557025][Kangna Zhang]], [[https://openalex.org/A5049328355][Zhiyong Li]], [[https://openalex.org/A5027696701][Jianji Wang]], [[https://openalex.org/A5088406552][Xiaochen Zhang]], [[https://openalex.org/A5003078964][Jikuan Qiu]], [[https://openalex.org/A5027696701][Jianji Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05648 
     
Electron delocalization is a versatile method to tune the electronic structure of materials for maximizing their maximizing performances. Herein, TPBD covalent organic frameworks (COFs) with controlled electron-delocalization characteristics (denoted as TPBD-R-COF, R = H, F, CN, and NO2) were synthesized by molecular engineering to systematically investigate the effect of electron delocalization on photocatalytic performance. We found that the photocatalytic performance can be enhanced by modulating local electron delocalization in COFs. The photocatalytic activity of TPBD-CN-COF is more than 12 times greater than that of TPBD-H-COF in oxidative coupling of amines to imines, where the yield of product was increased from 8 to 99%. The experimental results and theoretical calculations revealed that TPBD-CN-COF with the optimal electron-attracting group of −CN shows the highest charge separation efficiency and electron transport rate, while excessive electron delocalization is not better for such properties. Our findings provide a strategy to design and optimize the photocatalytic performance of COF-based catalysts.    

    

* Atomically Dispersed Palladium Driving Reductive Catalytic Fractionation of Lignocellulose into Alkene-Functionalized Phenols  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391980645
:TOPICS: Catalytic Valorization of Lignin for Renewable Chemicals, Catalytic Conversion of Biomass to Fuels and Chemicals, Nanocellulose: Properties, Production, and Applications
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05461")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391980645"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391980645"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391980645"))][Get cited by]]

OpenAlex: https://openalex.org/W4391980645 (Open access: False)
    
[[https://openalex.org/A5003492672][Shuizhong Wang]], [[https://openalex.org/A5003654383][Xiancheng Li]], [[https://openalex.org/A5020773915][Chao Fu]], [[https://openalex.org/A5026345769][Helong Li]], [[https://openalex.org/A5016601068][Guoyong Song]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05461 
     
No abstract    

    

* Selective Cascading Hydroboration of N-Heteroarenes via Cobalt Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391983174
:TOPICS: Homogeneous Catalysis with Transition Metals, Frustrated Lewis Pairs Chemistry, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06208")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391983174"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391983174"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391983174"))][Get cited by]]

OpenAlex: https://openalex.org/W4391983174 (Open access: False)
    
[[https://openalex.org/A5042232273][Ruibin Wang]], [[https://openalex.org/A5089080509][Dongwook Kim]], [[https://openalex.org/A5067309414][Sehoon Park]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06208 
     
No abstract    

    

* Coverage-Induced Cation Dehydration and Migration for Enhanced CO–CO Coupling on Cu Electrocatalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391983620
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05812")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391983620"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391983620"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391983620"))][Get cited by]]

OpenAlex: https://openalex.org/W4391983620 (Open access: False)
    
[[https://openalex.org/A5001220614][Huimin Yan]], [[https://openalex.org/A5004503548][Zisheng Zhang]], [[https://openalex.org/A5077960687][Yang‐Gang Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05812 
     
No abstract    

    

* Influence of Carbon Nanotube Support on Electrochemical Nitrate Reduction Catalyzed by Cobalt Phthalocyanine Molecules  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391983621
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05540")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391983621"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391983621"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391983621"))][Get cited by]]

OpenAlex: https://openalex.org/W4391983621 (Open access: False)
    
[[https://openalex.org/A5034761109][Nia J. Harmon]], [[https://openalex.org/A5046499103][Jingchao Li]], [[https://openalex.org/A5039366865][Bernie T. Wang]], [[https://openalex.org/A5050967989][Yuanzuo Gao]], [[https://openalex.org/A5049541666][Hailiang Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05540 
     
No abstract    

    

* Highly Selectively Methane Photooxidation to CH3OH and HCHO over an Integrated Fe2O3/WO3 Heterojunction Greatly Promoted by Iron(III) Chloride  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391984254
:TOPICS: Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05391")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391984254"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391984254"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391984254"))][Get cited by]]

OpenAlex: https://openalex.org/W4391984254 (Open access: False)
    
[[https://openalex.org/A5014561688][Wen‐Hao Zhou]], [[https://openalex.org/A5049768020][Yongqing Ma]], [[https://openalex.org/A5013295789][Congshan Zhu]], [[https://openalex.org/A5023500346][M. Wang]], [[https://openalex.org/A5002771918][Ganhong Zheng]], [[https://openalex.org/A5027781308][Yue Lü]], [[https://openalex.org/A5010484877][Meiling Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05391 
     
No abstract    

    

* Designing an Efficient Biocatalyst for the Phosphoribosylation of Antiviral Pyrazine-2-carboxamide Derivatives  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391991668
:TOPICS: Nucleotide Metabolism and Enzyme Regulation, Synthesis and Biological Activities of Oxazolones, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05059")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391991668"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391991668"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391991668"))][Get cited by]]

OpenAlex: https://openalex.org/W4391991668 (Open access: False)
    
[[https://openalex.org/A5020289297][Evgeniy A. Zayats]], [[https://openalex.org/A5080133403][Ilja V. Fateev]], [[https://openalex.org/A5011734229][Yu. A. Abramchik]], [[https://openalex.org/A5008792789][М. А. Костромина]], [[https://openalex.org/A5049066124][В. И. Тимофеев]], [[https://openalex.org/A5030149407][Daria O. Yurovskaya]], [[https://openalex.org/A5093861229][Andrey A. Karanov]], [[https://openalex.org/A5040926273][Irina D. Konstantinova]], [[https://openalex.org/A5028667873][Andrey V. Golovin]], [[https://openalex.org/A5052930403][Р. С. Есипов]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05059 
     
The development of technologies for the efficient synthesis of innovative antiviral compounds remains an important challenge for modern biotechnology, especially in the context of the recent COVID-19 pandemic. One of the drugs that is currently in the research spotlight for potential anti-SARS-CoV-2 activity is the purine mimetic prodrug compound T-705, also known as favipiravir. Along with a similar compound, T-1105, the activation of T-705 is limited by the low rate of phosphoribosylation, mediated by an enzyme named hypoxanthine-guanine phosphoribosyltransferase (HGPRT). Therefore, the synthesis of phosphoribosylated/ribosylated derivatives of these prodrugs is a viable direction for the discovery and development of antiviral pharmaceuticals. However, the chemical synthesis of such compounds is a complex and laborious process, whereas enzymatic cascades are not feasible because of the narrow HGPRT substrate specificity. Here, we report the successful rational design of an efficient biocatalyst for T-705/T-1105 phosphoribosylation. With two rounds of Thermus thermophilus HB27 HGPRT active site optimization, we have achieved a 325-fold increase in kcat toward the compound T-705 and a 125-fold increase toward T-1105 accompanied by a multifold decrease in KM. The practical applicability of the designed mutant was illustrated through the preparative synthesis of T-705/T-1105 nucleotide derivatives. Our engineered biocatalyst can become a basis for the technologies of enzymatic and chemoenzymatic synthesis of various T-705/T-1105 derivatives with proven antiviral activity. Moreover, our results provide insight into the molecular mechanism of T-705/T-1105 phosphoribosylation, including the experimental evidence explaining the reasons behind the low activity of HGPRT toward these compounds.    

    

* High-Entropy Effect Promoting Self-Healing Behavior of Two-Dimensional Metal Oxide Electrocatalysts for Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391991674
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05870")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391991674"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391991674"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391991674"))][Get cited by]]

OpenAlex: https://openalex.org/W4391991674 (Open access: False)
    
[[https://openalex.org/A5051788822][Dongdong Gao]], [[https://openalex.org/A5021658618][Wenxiang Zhu]], [[https://openalex.org/A5087269163][Jinxin Chen]], [[https://openalex.org/A5008126805][Keyang Qin]], [[https://openalex.org/A5074338325][Mengjie Ma]], [[https://openalex.org/A5025849211][Jie Shi]], [[https://openalex.org/A5013134577][Qun Wang]], [[https://openalex.org/A5061980234][Zhenglong Fan]], [[https://openalex.org/A5065985607][Qi Shao]], [[https://openalex.org/A5043301652][Fan Liao]], [[https://openalex.org/A5057299366][Mingwang Shao]], [[https://openalex.org/A5071907213][Zhenhui Kang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05870 
     
No abstract    

    

* Integrating Atomically Dispersed Ir Sites in MnCo2O4.5 for Highly Stable Acidic Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391992130
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06243")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391992130"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391992130"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391992130"))][Get cited by]]

OpenAlex: https://openalex.org/W4391992130 (Open access: False)
    
[[https://openalex.org/A5072004374][Hua Ke]], [[https://openalex.org/A5004808990][Xiaoke Li]], [[https://openalex.org/A5025107745][Rui Zhang]], [[https://openalex.org/A5018679788][Xiao Duan]], [[https://openalex.org/A5055283292][Yongkang Wu]], [[https://openalex.org/A5043023473][Xiaodong Pi]], [[https://openalex.org/A5090900131][Jia Li]], [[https://openalex.org/A5055152383][Jianguo Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06243 
     
Industrial water electrolysis requires oxygen evolution reaction (OER) catalysts that exhibit both high activity and adaptability to high current densities. However, single Ir atoms of the OER catalysts often show high performance in the three-electrode system but are limited to low current densities in proton exchange membrane water electrolyzers (PEMWE). The high oxidation potential and catalyst shedding caused by oxygen bubble desorption have hindered the stability, resulting in unsatisfactory PEMWE performance. Achieving high catalytic stability under high current density conditions still presents a significant challenge for all of the OER catalysts. In this study, an efficient and stable catalytic system for OER is constructed by a doping strategy, which consists of atomically dispersed Ir sites in MnCo2O4.5. The integrated Ir–MnCo2O4.5 catalyst demonstrates remarkable OER activity, with a low overpotential of 238 mV at 10 mA/cm2. It exhibits long-term stability, maintaining this high activity for 700 h at 20 mA/cm2 with a degradation rate of 0.025 mV/h. Impressively, the PEMWE with the integrated Ir–MnCo2O4.5 as the anode remains stable even after nearly 100 h at 200 mA/cm2, outperforming most previously reported single-iridium atom-based PEMWEs. Density functional theory calculations show that the redistribution of charges brought by the introduction of Ir and Mn not only effectively reduces the dissolution of lattice oxygen and Ir active sites but also lowers the energy barrier of the rate-determining step, thereby significantly improving the stability and activity of Ir–MnCo2O4.5 under high current density.    

    

* Photoinduced, Palladium-Catalyzed Enantioselective 1,2-Alkylsulfonylation of 1,3-Dienes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391993117
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Innovations in Organic Synthesis Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00470")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391993117"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391993117"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391993117"))][Get cited by]]

OpenAlex: https://openalex.org/W4391993117 (Open access: False)
    
[[https://openalex.org/A5039851941][Zhilin Liu]], [[https://openalex.org/A5045832851][Zhipeng Ye]], [[https://openalex.org/A5055498163][Zihao Liao]], [[https://openalex.org/A5090498632][Weidong Lu]], [[https://openalex.org/A5049594674][Jianping Guan]], [[https://openalex.org/A5055603180][Zhongli Gao]], [[https://openalex.org/A5074447615][Kai Chen]], [[https://openalex.org/A5014195139][Xiao‐Qing Chen]], [[https://openalex.org/A5070637699][Hao-Yue Xiang]], [[https://openalex.org/A5065499122][Hua Ye]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00470 
     
The chiral allylic sulfonylated group is a unique structural motif embedded in a range of natural products and pharmaceuticals. Notably, the synthesis of structurally diverse chiral allylic sulfonylated derivatives via alkylsulfonylation of 1,3-dienes remains underexplored because of its inherent challenges in stereocontrol and regioselectivity. Herein, photoinduced, palladium-catalyzed enantioselective 1,2-alkylsulfonylation of conjugated 1,3-dienes is described. A wide variety of alkyl bromides, 1,3-dienes, and sodium sulfinates could be facilely coupled to generate value-added chiral allylic sulfonylated derivatives with high enantioselectivity. Finally, the utility of this enantioselective difunctionalization protocol was demonstrated in pharmaceutical analogue synthesis.    

    

* Structure and Reactivity of Binuclear Cu Active Sites in Cu-CHA Zeolites for Stoichiometric Partial Methane Oxidation to Methanol  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391996262
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06181")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391996262"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391996262"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391996262"))][Get cited by]]

OpenAlex: https://openalex.org/W4391996262 (Open access: False)
    
[[https://openalex.org/A5034225594][Laura N. Wilcox]], [[https://openalex.org/A5033077129][José Rebolledo-Oyarce]], [[https://openalex.org/A5039687304][Andrew D. Mikes]], [[https://openalex.org/A5006415472][Yujia Wang]], [[https://openalex.org/A5062009633][William F. Schneider]], [[https://openalex.org/A5072511676][Rajamani Gounder]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06181 
     
Aluminosilicate zeolites exchanged with copper ions facilitate partial methane oxidation (PMO) to methanol in stoichiometric oxidation and reduction cycles, yet the identities of active Cu sites and details of the reaction mechanism remain debated. Here, we use the high-symmetry chabazite (CHA) zeolite framework as a model support to probe the relationship between bulk composition, Cu speciation, and response to various oxidizing and reducing treatments. Density functional theory and first-principles thermodynamics combined with statistical models reveal that Cu speciation and composition depend strongly on Al configuration and external gas conditions. Cu-CHA samples were synthesized to survey broad regions of Si/Al and Cu/Al composition space and framework Al proximity. Characterization by in situ X-ray absorption and UV–visible spectroscopy during exposure to different oxidation conditions reveal that the extent of Cu oxidation is sensitive to activation conditions and thus that both kinetic and thermodynamic factors influence Cu oxidizability in a given material. Similar characterizations during CO reduction reveal that CO titrates Cu2+ in amounts suggesting the presence of both O- and O2-bridged species. In contrast, CH4 and autoreduction (He) treatments reduce similar but smaller numbers of Cu sites than CO, implicating O2-bridged Cu dimers as a potential common intermediate in the former reduction pathways. A systematic increase in methanol yields (per Cu) in stoichiometric PMO cycles increase with the fraction of binuclear Ox-bridged Cu sites suggests these species as active sites, as depicted in an updated PMO reaction mechanism.    

    

* Dynamic Docking-Assisted Engineering of Hydrolases for Efficient PET Depolymerization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391997686
:TOPICS: Global E-Waste Recycling and Management, Biodegradable Polymers as Biomaterials and Packaging, Recycling Technologies for Carbon Fiber Composites
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00400")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391997686"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391997686"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391997686"))][Get cited by]]

OpenAlex: https://openalex.org/W4391997686 (Open access: False)
    
[[https://openalex.org/A5066167884][Yi Zheng]], [[https://openalex.org/A5025167872][Qingbin Li]], [[https://openalex.org/A5075370591][Pan Liu]], [[https://openalex.org/A5084545842][Yingbo Yuan]], [[https://openalex.org/A5060247019][Longyang Dian]], [[https://openalex.org/A5092164942][Qian Wang]], [[https://openalex.org/A5067975624][Quanfeng Liang]], [[https://openalex.org/A5028881300][Tianyuan Su]], [[https://openalex.org/A5059844098][Qingsheng Qi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00400 
     
No abstract    

    

* Photoinduced Regioselective Sulfonylsulfination of Alkenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392004197
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Innovations in Organic Synthesis Reactions, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00049")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392004197"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392004197"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392004197"))][Get cited by]]

OpenAlex: https://openalex.org/W4392004197 (Open access: False)
    
[[https://openalex.org/A5038883899][Helian Li]], [[https://openalex.org/A5082889999][Yongxin Zhang]], [[https://openalex.org/A5076602989][Xiaoyong Zou]], [[https://openalex.org/A5005205790][Xiaoxiao Yang]], [[https://openalex.org/A5045685496][Pan Zhou]], [[https://openalex.org/A5065055275][Xinyue Ma]], [[https://openalex.org/A5044388938][Shaoping Lu]], [[https://openalex.org/A5011249790][Qing Sun]], [[https://openalex.org/A5079144903][Chao Shu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00049 
     
Regioselective 1,2-dichalcogenation of alkenes has attracted significant attention in modern organic synthetic chemistry. While there are a plethora of methods to access alkene dichalcogenated architectures, sulfonylsulfination of alkenes is extremely challenging due to the inherent characteristics of the sulfur atom. Herein, a multicomponent fragment coupling of alkenes, sulfinates, and DABSO was developed to construct densely functionalized sulfonylsulfinated products, which are otherwise challenging to access, with broad substrate scope and group tolerance under mild and operationally simple conditions, using an inexpensive 100–1000 ppm organic photocatalyst. In addition, the protocol was applied to the late-stage functionalization of complex molecules, and the obtained products were converted into diverse downstream transformations to demonstrate their synthetic potential. Experimental and theoretical mechanistic investigations suggest that these reactions proceed through sequential sulfonyl and sulfinyl oxygen radical mutual transformations and radical–polar crossover coupling. This strategy provides access to previously inaccessible alkene sulfonylsulfinated products in good-to-high regio- and stereoselectivity, along with opening up previously unexplored synthetic directions.    

    

* Atroposelective Synthesis of Axially Chiral Diaryl Ethers by Copper-Catalyzed Enantioselective Alkyne–Azide Cycloaddition  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392004251
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Chiroptical Spectroscopy in Organic Compound Analysis, Sphingolipid Signalling and Metabolism in Health and Disease
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06148")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392004251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392004251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392004251"))][Get cited by]]

OpenAlex: https://openalex.org/W4392004251 (Open access: True)
    
[[https://openalex.org/A5014475523][X Han]], [[https://openalex.org/A5011267819][Lan Chen]], [[https://openalex.org/A5073177245][Yong Yan]], [[https://openalex.org/A5012757324][Yanyang Zhao]], [[https://openalex.org/A5011404596][Aijun Lin]], [[https://openalex.org/A5006095272][Shang Gao]], [[https://openalex.org/A5052874928][Hequan Yao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06148  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06148][pdf]])
     
Diaryl ethers are important structural motifs widely found in bioactive natural products, ligands, and catalysts. While there are a variety of methods available to generate diaryl ethers, progress on the construction of axially chiral diaryl ethers has been slow. We report herein an atroposelective copper-catalyzed cycloaddition between bisalkynes and azides. With an indane-fused BOX ligand used, a diverse array of C–O atropisomers are obtained with up to 97% yield and 99% ee. Control experiments showed that a sequential enantioselective desymmetrization–kinetic resolution process is involved, and the former plays a major role. In addition, an asymmetric depletion is observed for this catalytic synthesis by nonlinear effect studies. By thermal racemization experiments, the rotational barrier of the C–O axis of 3aa is calculated to be 35.9 kcal/mol, which lays the foundation for its isolation, as well as further applications.    

    

* Combined Hydrogen and Alkane Production by Photocatalytic Decarboxylative C–C Homocoupling of Fatty Acid by Constructing a Hydrogen-Deficient Catalytic Interface  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392004426
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Polyoxometalate Clusters and Materials, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06070")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392004426"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392004426"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392004426"))][Get cited by]]

OpenAlex: https://openalex.org/W4392004426 (Open access: False)
    
[[https://openalex.org/A5035388503][Xucheng Li]], [[https://openalex.org/A5088693897][Peng Yang]], [[https://openalex.org/A5017988818][Zhipeng Huang]], [[https://openalex.org/A5065217556][Gang Feng]], [[https://openalex.org/A5082042466][Leo Lingchun Kong]], [[https://openalex.org/A5089946640][Haiwei Jiang]], [[https://openalex.org/A5031655322][Weiran Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06070 
     
Decarboxylation of biomass-derived fatty acids provides an important method for the production of value-added alkane fuels and chemicals. Here, selective decarboxylative C–C homocoupling of fatty acids to obtain long-chain alkanes was achieved by heterogeneous photocatalysis under mild conditions. Hydrogen was cogenerated as the potential energy source. The high selectivity for the coupling product was realized by constructing a hydrogen-deficient catalytic interface through the combined action of Ru nanoparticles supported on TiO2 and continuous N2 blow, which can inhibit the hydrogenation of alkyl radicals and enhance the C–C coupling of alkyl radicals. C2n–2 saturated alkanes (as high as 93%) and hydrogen (as high as 20.3 μmol·mL–1) are produced from bioderived C4–C12 fatty acids in high yields under mild reaction conditions (25 °C, N2 blow). Furthermore, low-value industrial fatty acid mixtures such as coconut oil and Cinnamomum camphora seed kernel oil can be directly applied in this catalytic system and selectively yield long-chain alkanes (up to 80%) in a solvent-free system. Density functional theory (DFT) calculations and various analytical methods were applied to elucidate the possible catalytic mechanism.    

    
