#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sat Apr  6 00:43:24 2024

Found 25 results from 2024-03-30 to 2024-04-06
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Axially Chiral Copper Catalyst for Asymmetric Synthesis of Valuable Diversely Substituted BINOLs  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393308838
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Chiroptical Spectroscopy in Organic Compound Analysis, Aromaticity in Organic Molecules and Materials
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00726")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393308838"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393308838"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393308838"))][Get cited by]]

OpenAlex: https://openalex.org/W4393308838 (Open access: False)
    
[[https://openalex.org/A5086976460][Jun Gao]], [[https://openalex.org/A5080077246][P.L. Wang]], [[https://openalex.org/A5071298608][Ahui Shen]], [[https://openalex.org/A5037358505][Xueyan Yang]], [[https://openalex.org/A5067090172][Shouyi Cen]], [[https://openalex.org/A5022807400][Zhipeng Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00726 
     
Optically pure BINOL (1,1′-bi-2-naphthol) and diversely substituted BINOLs are highly valuable chiral motifs featuring axial chirality widely applied in various fields. Although unsubstituted BINOL is commercially available, the catalytic asymmetric synthesis of optically pure diversely substituted BINOLs is still very challenging. Herein, we report the development of a highly enantioselective dinuclear copper catalyst for oxidative homo- and cross-coupling of a variety of 2-naphthols to provide access to a broad range of highly valuable diversely substituted C2- and C1-symmetric BINOLs in up to 92% yield with high enantioselectivities (up to 99.5:0.5 er).    

    

* Choose Your Own Adventure: A Comprehensive Database of Reactions Catalyzed by Cytochrome P450 BM3 Variants  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393311212
:TOPICS: Drug Metabolism and Pharmacogenomics, Homogeneous Catalysis with Transition Metals, Computational Methods in Drug Discovery
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00086")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393311212"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393311212"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393311212"))][Get cited by]]

OpenAlex: https://openalex.org/W4393311212 (Open access: True)
    
[[https://openalex.org/A5064757543][Douglas J. Fansher]], [[https://openalex.org/A5046459245][Jonathan N. Besna]], [[https://openalex.org/A5071852582][Ali Fendri]], [[https://openalex.org/A5024277895][Joelle N. Pelletier]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00086  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00086][pdf]])
     
No abstract    

    

* General, Modular Access toward Immobilized Chiral Phosphoric Acid Catalysts and Their Application in Flow Chemistry  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393316637
:TOPICS: Droplet Microfluidics Technology, Homogeneous Catalysis with Transition Metals, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00985")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393316637"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393316637"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393316637"))][Get cited by]]

OpenAlex: https://openalex.org/W4393316637 (Open access: True)
    
[[https://openalex.org/A5078412901][Michael Laue]], [[https://openalex.org/A5078656621][Maximilian Schneider]], [[https://openalex.org/A5035158328][Markus G. Gebauer]], [[https://openalex.org/A5009489291][Winfried Böhlmann]], [[https://openalex.org/A5035784012][Roger Gläser]], [[https://openalex.org/A5005127669][Christoph Schneider]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00985  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00985][pdf]])
     
Chiral phosphoric acids (CPAs) are among the most frequently used organocatalysts, with an ever-increasing number of applications. However, these catalysts are only obtained in a multistep synthesis and are poorly recyclable, which significantly deteriorates their environmental and economic performance. We herein report a conceptually different, general strategy for the direct immobilization of CPAs on a broad scope of solid supports including silica, polystyrene, and aluminum oxide. Solid-state catalysts were obtained in high yields and thoroughly characterized with elemental analysis by inductively coupled plasma-optical emission spectrometry (ICP-OES), nitrogen sorption measurements, thermogravimetric analysis, scanning transmission electron microscopy/energy-dispersive X-ray spectroscopy (STEM/EDX) images, and solid-state NMR spectroscopy. Further, the immobilized catalysts were applied to a variety of synthetically valuable, highly stereoselective transformations under batch and flow conditions including transfer hydrogenations, a Friedländer condensation/transfer hydrogenation sequence, and Mannich reactions under cryogenic flow conditions. Generally, high yields and stereoselectivities were observed along with robust catalyst stability and reusability. After being used for 10 runs under batch conditions, no loss of selectivity or catalytic activity was observed. Under continuous-flow conditions, the heterogeneous system was in operation for 19 h and the high enantioselectivity remained unchanged throughout the entire process. We expect our approach to extend the applicability of CPAs to a higher level, with a focus on flow chemistry and a more environmentally friendly and resource-efficient use of these powerful catalysts.    

    

* Modeling Complex Ligands for High Oxidation State Catalysis: Titanium Hydroamination with Unsymmetrical Ligands  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393316892
:TOPICS: Transition Metal Catalysis, Homogeneous Catalysis with Transition Metals, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05658")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393316892"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393316892"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393316892"))][Get cited by]]

OpenAlex: https://openalex.org/W4393316892 (Open access: True)
    
[[https://openalex.org/A5086536041][Zhilin Hou]], [[https://openalex.org/A5091300507][Rashmi Jena]], [[https://openalex.org/A5011415802][Tanner J. McDaniel]], [[https://openalex.org/A5000702642][Brennan S. Billow]], [[https://openalex.org/A5045654916][Seokjoo Lee]], [[https://openalex.org/A5043497566][Hannah I. Barr]], [[https://openalex.org/A5082247410][Aaron L. Odom]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05658  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05658][pdf]])
     
A method for modeling high oxidation state catalysts is used on precatalysts with unsymmetrical and symmetrical bidentate ligands to get a more detailed understanding of how changes to ancillary ligands affect the hydroamination of alkynes catalyzed by titanium. To model the electronic donor ability, the ligand donor parameter (LDP) was used, and to model the steric effects, percent buried volume (% Vbur) was employed. For the modeling study, 7 previously unpublished unsymmetrical Ti(XX′)(NMe2)2 precatalysts were prepared, where XX′ is a chelating ligand with pyrrolyl/indolyl linkages. The rates of these unsymmetrical and 10 previously reported symmetrical precatalysts were used with the model kobs = a + b(LDP)1 + c(LDP)2 + d(% Vbur)1 + e(% Vbur)2, where a–e were found through least-squares refinement. The model suggests that (1) the two attachment points of the bidentate ligand XX′ are in different environments on the metal (e.g., axial and equatorial in a trigonal bipyramidal or square pyramidal structure), (2) the position of the unsymmetrical ligand on the metal is determined by the electronics of the ligand rather than the sterics, and (3) that one side of the chelating ligand's electronics strongly influences the rate, while the other side's sterics more strongly influences the rate. From these studies, we were able to generate catalysts fitting to this model with rate constants larger than the fastest symmetrical catalyst tested.    

    

* Benzylic C(sp3)–H Functionalization via Copper-Catalyzed [3+3] Radical Cycloaddition  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393317410
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00637")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393317410"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393317410"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393317410"))][Get cited by]]

OpenAlex: https://openalex.org/W4393317410 (Open access: False)
    
[[https://openalex.org/A5082496097][Junsheng Shi]], [[https://openalex.org/A5005759312][Xiong-Jiang Li]], [[https://openalex.org/A5067645447][Shu-Yun Jiang]], [[https://openalex.org/A5011461470][Wei Wu]], [[https://openalex.org/A5066293769][Hai Ren]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00637 
     
The development of benzylic C(sp3)–H functionalization methods for the assembly of benzylic derivatives has been extensively explored in recent years. However, the engagement of benzylic carbon and its adjacent C=C bond as a C3 synthon in the cycloaddition reaction via direct benzylic C–H activation is rare. Herein, we report a copper-catalyzed [3+3] radical cycloaddition reaction through benzylic C–H bond functionalization to construct six-membered cyclohexane-type rings. In this reaction, the 2-benzylic C–H bond of an indole is selectively activated and the indole serves as a C3 synthon that reacts through highly chemoselective intermolecular self-[3+3] and cross-[3+3] cycloaddition pathways. Multiple symmetric and nonsymmetric polycyclic hexahydrocarbazole scaffolds with hexacyclic 6/5/5/6/5/5/6 and pentacyclic 6/5/5/6/5/6 ring systems are synthesized with high efficiency and chemoselectivity using this strategy. Inspired by the unique radical addition pathway of cross-[3+3] cycloaddition, a highly controllable benzylic C–H functionalization for the construction of C3a-alkylated pyrroloindolines was also developed.    

    

* Rare-Earth-Catalyzed Regiodivergent Hydrosilylation of Aryl Alkenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393317760
:TOPICS: Frustrated Lewis Pairs Chemistry, Homogeneous Catalysis with Transition Metals, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05747")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393317760"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393317760"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393317760"))][Get cited by]]

OpenAlex: https://openalex.org/W4393317760 (Open access: False)
    
[[https://openalex.org/A5075128272][Wufeng Chen]], [[https://openalex.org/A5077386687][N. Zhang]], [[https://openalex.org/A5051879914][Zhengqi Chai]], [[https://openalex.org/A5033889166][Junnian Wei]], [[https://openalex.org/A5046378812][Gen Luo]], [[https://openalex.org/A5029642484][Wen‐Xiong Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05747 
     
While transition-metal catalysts have shown the ability to regulate the Markovnikov or anti-Markovnikov regioselective hydrosilylation of aryl alkenes, the selective control of anti-Markovnikov hydrosilylation of aryl alkenes is still a huge challenge in rare-earth catalyst systems. In this study, we report the rare-earth-catalyzed regiodivergent hydrosilylation of aryl alkenes. Specifically, we achieved the highly regioselective anti-Markovnikov hydrosilylation of aryl alkenes with a scandium alkyl complex Cp*AmtBuScCH2SiMe3 (Cp* = pentamethylcyclopentadienyl, AmtBu = tBuNC(Me)NtBu, tBu = t-butyl) as a catalyst. Two key intermediates, e.g., the scandium hydride and scandium phenethyl complex for anti-Markovnikov hydrosilylation, were characterized. Guided by density functional theory (DFT) calculations, we successfully achieved the selective inversion of aryl alkenes in Markovnikov hydrosilylation using a neodymium halide complex [Cp*AmiPrNdCl]2 (AmiPr = iPrNC(Me)NiPr, iPr = isopropyl) with the larger ion radius and reduced steric hindrance in conjunction with LiCH2SiMe3. Interestingly, our study has demonstrated the significant influence of gradually increasing rare-earth ion radii on controlling the increasing Markovnikov selectivity of hydrosilylation reactions, possibly due to the enlargement of the coordination space around rare-earth metal ions. Furthermore, through a comparison of computational and experimental data, we have observed a high level of consistency, reaffirming the potential of using calculations to predict experimental outcomes and providing researchers with valuable insights.    

    

* Regulation of Catalyst Immediate Environment Enables Acidic Electrochemical Benzyl Alcohol Oxidation to Benzaldehyde  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393319141
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00476")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393319141"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393319141"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393319141"))][Get cited by]]

OpenAlex: https://openalex.org/W4393319141 (Open access: True)
    
[[https://openalex.org/A5075812681][G. Shiva Shanker]], [[https://openalex.org/A5086461939][Arnab Ghatak]], [[https://openalex.org/A5005608415][Shahar Binyamin]], [[https://openalex.org/A5094278970][Rotem Balilty]], [[https://openalex.org/A5085963150][Ran Shimoni]], [[https://openalex.org/A5041755694][Itamar Liberman]], [[https://openalex.org/A5014582181][Idan Hod]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00476  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00476][pdf]])
     
Electrocatalytic alcohol oxidation in acid offers a promising alternative to the kinetically sluggish water oxidation reaction toward low-energy H2 generation. However, electrocatalysts driving active and selective acidic alcohol electrochemical transformation are still scarce. In this work, we demonstrate efficient alcohol-to-aldehyde conversion achieved by reticular chemistry-based modification of the catalyst's immediate environment. Specifically, coating a Bi-based electrocatalyst with a thin layer of metal–organic framework (MOF) substantially improves its performance toward benzyl alcohol electro-oxidation to benzaldehyde in a 0.1 M H2SO4 electrolyte. Detailed analysis reveals that the MOF adlayer influences catalysis by increasing the reactivity of surface hydroxides as well as weakening the catalyst-benzaldehyde binding strength. In turn, low-potential (0.65 V) cathodic H2 evolution was obtained through coupling it with anodic benzyl alcohol electro-oxidation. Consequently, the presented approach could be implemented in a wide range of electrocatalytic oxidation reactions for energy-conversion application.    

    

* Enlarging the Three-Phase Boundary to Raise CO2/CH4 Conversions on Exsolved Ni–Fe Alloy Perovskite Catalysts by Minimal Rh Doping  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393319453
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00151")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393319453"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393319453"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393319453"))][Get cited by]]

OpenAlex: https://openalex.org/W4393319453 (Open access: True)
    
[[https://openalex.org/A5006264721][Xueli Yao]], [[https://openalex.org/A5068697796][Qingpeng Cheng]], [[https://openalex.org/A5075558687][Xueqin Bai]], [[https://openalex.org/A5015654220][Bambar Davaasuren]], [[https://openalex.org/A5065521871][Georgian Melinte]], [[https://openalex.org/A5070190889][Natalia Morlanés]], [[https://openalex.org/A5069291762][José Luis Cerrillo]], [[https://openalex.org/A5030367733][Vijay Kumar Velisoju]], [[https://openalex.org/A5053107002][Hend Omar Mohamed]], [[https://openalex.org/A5004116629][Pewee Datoo Kolubah]], [[https://openalex.org/A5065268874][Lirong Zheng]], [[https://openalex.org/A5002349598][Yu Han]], [[https://openalex.org/A5015619826][Osman M. Bakr]], [[https://openalex.org/A5058113997][Jorge Gascón]], [[https://openalex.org/A5011280331][Pedro Castaño]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00151  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00151][pdf]])
     
Exsolved Ni–Fe alloy perovskite catalysts exhibit remarkable coking resistance during C–H and C–O activation. However, metallic utilization is typically incomplete, resulting in relatively low catalytic activity. Herein, we investigated minimal doping with Rh to boost the catalytic activity in the dry reforming of methane by promoting exsolution and enlargement of the three-phase boundary between the alloy, support, and reactants. The Rh influences the formation of the Ni–Fe alloy, as revealed by X-ray diffraction, and promotes the individual and collective CH4 and CO2 conversions, as revealed by packed bed reactor runs, temperature-programmed surface reactions, and in situ infrared spectroscopy. A minimal 0.21 wt % Rh addition enlarges the three-phase boundary while improving oxygen mobility and storage. The oxygen mobility is responsible for promoting CH4 dissociation and dynamic removal of carbon-containing intermediates, such that the catalyst remains stable for over 100 h under both 1 and 14 bar.    

    

* Tuning Strong Metal–Support Interactions via Synergistic Alloying  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393345356
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Accelerating Materials Innovation through Informatics, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-03-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06171")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393345356"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393345356"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393345356"))][Get cited by]]

OpenAlex: https://openalex.org/W4393345356 (Open access: False)
    
[[https://openalex.org/A5050613147][Yunlong Wang]], [[https://openalex.org/A5010949964][Xiaobo Chen]], [[https://openalex.org/A5075446655][Chaoran Li]], [[https://openalex.org/A5086708025][Yaguang Zhu]], [[https://openalex.org/A5012677271][Jing Li]], [[https://openalex.org/A5080482655][Shiyao Shan]], [[https://openalex.org/A5061621593][Adrian Hunt]], [[https://openalex.org/A5053922026][Iradwikanari Waluyo]], [[https://openalex.org/A5070392626][J. Anibal Boscoboinik]], [[https://openalex.org/A5026877218][Chuan‐Jian Zhong]], [[https://openalex.org/A5009173681][Guangwen Zhou]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06171 
     
The encapsulation phenomenon associated with a strong metal–support interactions (SMSI) has been largely restricted to catalyst systems consisting of group VIII metals with high surface energy and reducible transition metal oxide supports with low surface energy. Here, we demonstrate an encapsulation phenomenon that, while sharing morphological similarities with conventional SMSI, follows a distinctive pathway. This is shown by the encapsulation of CuAu nanoparticles (NPs) supported on a highly ordered pyrolytic graphite (HOPG). Through dynamic monitoring of Cu, Au, and Cu50Au50 NPs in an oxidizing atmosphere using ambient-pressure X-ray photoelectron spectroscopy, we show that this spontaneous encapsulation is achieved through the synergistic effect of the alloying elements. Specifically, the surface segregation of Cu promotes dissociative O2 adsorption, leading to the formation of atomic O species, while the subsurface enrichment of Au hinders O incorporation of oxygen into the bulk of CuAu NPs. Consequently, O spillover onto the graphite support occurs, resulting in the oxidation of the HOPG surface into graphitic oxide species. The higher affinity of the graphitic oxide species toward the Cu-segregated surface prompts their migration from the HOPG support to encapsulate the CuAu NPs. These results transcend the conventional SMSI and bear practical implications for the design and development of heterogeneous catalysts, particularly in carbon-supported alloy systems.    

    

* Molecular Engineering of Electrocatalytic Nanomaterials for Hydrogen Evolution: The Impact of Structural and Electronic Modifications of Anchoring Linkers on Electrocatalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393305578
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00336")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393305578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393305578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393305578"))][Get cited by]]

OpenAlex: https://openalex.org/W4393305578 (Open access: False)
    
[[https://openalex.org/A5068400290][Andrew J. Bagnall]], [[https://openalex.org/A5092760919][Matthieu Haake]], [[https://openalex.org/A5071474652][Sergi Grau]], [[https://openalex.org/A5025011392][Tatiana Straistari]], [[https://openalex.org/A5008192334][Matthieu Koepf]], [[https://openalex.org/A5008669299][Navid Jameei Moghaddam]], [[https://openalex.org/A5027825269][Carolina Gimbert‐Suriñach]], [[https://openalex.org/A5003571345][Jordi Benet‐Buchholz]], [[https://openalex.org/A5005120127][Antoni Llobet]], [[https://openalex.org/A5009538487][Murielle Chavarot‐Kerlidou]], [[https://openalex.org/A5020577271][Bertrand Reuillard]], [[https://openalex.org/A5047933845][Vincent Artero]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00336 
     
The anticipated shortage of an increasing number of critical elements, especially metals, requires a shift toward molecularly defined materials with low metal loadings. More particularly, surface-anchored molecular catalysts are attractive to prospectively enable cost-effective electrochemical hydrogen evolution. However, the design of ligands integrating specific anchoring unit(s) for the immobilization of molecular catalysts can be challenging and has direct consequences for the intrinsic properties of the grafted complex. In this work, two cobalt tetraazamacrocyclic complexes bearing pyrene anchoring groups at different positions on the macrocyclic ligands were synthesized. The pyrene unit allows for simple immobilization and electrochemical characterization of the two complexes on multi-walled carbon nanotube-based electrodes. Thorough electrochemical and electrocatalytic investigation demonstrates important differences between the two closely related catalysts in terms of catalyst loading, catalytic response, and stability over time, with a significantly higher stability observed at pH 7 than at pH 2.    

    

* How Micropore Topology Influences the Structure and Location of Coke in Zeolite Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393309555
:TOPICS: Zeolite Chemistry and Catalysis, Chemistry and Applications of Metal-Organic Frameworks, Mesoporous Materials
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00025")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393309555"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393309555"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393309555"))][Get cited by]]

OpenAlex: https://openalex.org/W4393309555 (Open access: True)
    
[[https://openalex.org/A5011286202][Przemysław Rzepka]], [[https://openalex.org/A5058790744][Denis Sheptyakov]], [[https://openalex.org/A5055838753][Chao Wang]], [[https://openalex.org/A5054120563][Jeroen A. van Bokhoven]], [[https://openalex.org/A5059144530][Vladimir Paunović]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00025  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00025][pdf]])
     
Zeolite catalysts exhibit microporous structures, akin to the pockets in naturally occurring enzyme catalysts, which enable the confinement of reaction intermediates, thus facilitating chemical transformations. Nonetheless, the micropores also influence the formation of coke species, which is the main source of catalytic activity loss. Unveiling the relationships between the micropore topology and the internal structure and location of deactivating coke compounds is of high relevance for comprehending the deactivation mechanisms. In this study, we used an approach exploiting powder neutron diffraction to assess the location of coke and determine the dominating structures in the topologically distinct ZSM-5 (MFI topology), ZSM-35 (FER), and SSZ-13 (CHA) zeolite catalysts deactivated in industrially relevant methanol-to-hydrocarbon (MTH) conversion. In ZSM-5 and ZSM-35 catalysts, coke resides along the straight 10-membered ring (MR) channels and exhibits the highest concentration in their intersecting regions with sinusoidal 10 MR and straight 8 MR pores, respectively. In the SSZ-13 catalyst, coke is not only located in cages but also protrudes through their 8 MR windows, suggesting the interconnectivity of coke molecules between the large cavities. Notably, the coke-associated signals in the ZSM-5 and ZSM-35 catalysts show a strong planar arrangement that can be fitted by polycyclic and monocyclic arene structures, respectively. These averaged coke structures are consistent with the composition of coke assessed by gas chromatography–mass spectrometry, 13C and two-dimensional 1H double-quantum single-quantum magic-angle spinning nuclear magnetic resonance, and operando diffuse reflectance ultraviolet–visible spectroscopic analysis. The findings evidence that the pore topology directs the confinement and structure of coke, wherein the largest void zones of the micropore space are the most susceptible to coking.    

    

* Harnessing the Synergistic Power of Ce2S3/TiO2 S-Scheme Heterojunctions for Profound C–O Bond Cleavage in Lignin Model Compounds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393316547
:TOPICS: Desulfurization Technologies for Fuels, Photocatalytic Materials for Solar Energy Conversion, Catalytic Valorization of Lignin for Renewable Chemicals
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00297")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393316547"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393316547"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393316547"))][Get cited by]]

OpenAlex: https://openalex.org/W4393316547 (Open access: False)
    
[[https://openalex.org/A5045922800][Hongwu Liao]], [[https://openalex.org/A5003098842][Yanmin Zhou]], [[https://openalex.org/A5017825677][Zhuo Chen]], [[https://openalex.org/A5056411651][Swellam W. Sharshir]], [[https://openalex.org/A5022798909][Sameh M. Osman]], [[https://openalex.org/A5007803202][Chong Wang]], [[https://openalex.org/A5055500155][Meng An]], [[https://openalex.org/A5037509120][Yusuke Yamauchi]], [[https://openalex.org/A5085415818][Yusuke Asakura]], [[https://openalex.org/A5069831567][Zhanhui Yuan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00297 
     
In the context of achieving carbon neutrality, converting lignin-derived molecules into high-value products through photocatalytic technology provides an environmentally friendly pathway. Establishing energy-efficient processes for converting lignin derivatives requires the construction of highly active and selective photocatalysts. However, enhancing the efficiency and selectivity of photocatalysts for lignin degradation poses an ongoing challenge due to discrepancies in the redox potential and the rapid recombination of photogenerated carriers. To address these significant obstacles, we devised an innovative strategy by developing a Ce2S3 nanoparticle-anchored TiO2 nanorod (Ce2S3/TiO2). This advanced photocatalyst with the S-scheme heterojunction, enabling simultaneous control of carrier dynamics and band structure, was used to study the photocatalytic degradation of the lignin model compound 2-phenoxy-1-acetophenone. Moreover, the photocatalyst can cleave the Cβ-O-4 bond selectively to convert the lignin model compound 2-phenoxy-1-acetophenone into phenol and acetophenone under visible-light irradiation. The yields are up to 94 and 80%, respectively, and 94 or 1.4 times greater than those obtained by pure TiO2 or Ce2S3 individually. In addition, our study for the increased activity in Ce2S3/TiO2 based on density functional theory calculations emphasizes the pivotal role of the S-scheme heterojunction generated between Ce2S3 and TiO2. This heterojunction significantly enhances carrier separation efficiency, thereby augmenting the efficacy of the photocatalytic process. The findings furnish valuable insights for developing advanced photocatalytic systems tailored to the efficient depolymerization of Cβ-O-4 bonds in lignin.    

    

* Tunable Divergent Reactivity of Aziridinium Ylides in the Synthesis of Complex Piperidines and Azetidines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393372078
:TOPICS: Catalytic C-H Amination Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06173")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393372078"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393372078"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393372078"))][Get cited by]]

OpenAlex: https://openalex.org/W4393372078 (Open access: False)
    
[[https://openalex.org/A5063494151][Mahzad Dehghany]], [[https://openalex.org/A5033112655][Giuliana Pavaneli]], [[https://openalex.org/A5093551048][Jacob W. Kailing]], [[https://openalex.org/A5087213395][Olivia M. Duke]], [[https://openalex.org/A5040701048][Ilia A. Guzei]], [[https://openalex.org/A5069102842][Caroline Da Ros Montes D’Oca]], [[https://openalex.org/A5009883474][Israel Fernández]], [[https://openalex.org/A5047518130][Jennifer M. Schomaker]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06173 
     
Nitrogenated heterocycles comprise the cores of a number of synthetically useful compounds, including pharmaceuticals, bioactive natural products, agrochemicals, and other drug-like molecules. The widespread interest in methods to increase the fraction of sp3 carbon atoms (Fsp3) of drug-like scaffolds in a stereocontrolled manner, while enabling explorations of unusual amine chemical space, inspired our efforts to tune the reactivity of aziridinium ylides. A sequential nitrene–carbene transfer of simple allenes leads to divergent product outcomes depending on the nature of the carbene precursor, furnishing products of different ring sizes. In addition, the catalyst control over the ring size via proposed hydrogen-bonding interactions between the catalyst and substrate was explored. Computational studies were employed to gain insight into the major features of substrates and catalysts that influence the tunable reactivity of aziridinium ylide intermediates formed in this chemistry.    

    

* Efficient Visible-Light-Driven Water Oxidation by a Carbon Nitride Modified with Cobalt Polyoxometalate Molecular Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393373284
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00627")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393373284"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393373284"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393373284"))][Get cited by]]

OpenAlex: https://openalex.org/W4393373284 (Open access: False)
    
[[https://openalex.org/A5007596741][Yoshihiko Tomita]], [[https://openalex.org/A5044251519][Natsuki Taira]], [[https://openalex.org/A5066627191][Ken Sakai]], [[https://openalex.org/A5051285636][Hidetoshi Ozawa]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00627 
     
No abstract    

    

* Competing Mechanisms in Palladium-Catalyzed Alkoxycarbonylation of Styrene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393375769
:TOPICS: Transition Metal Catalysis, Homogeneous Catalysis with Transition Metals, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00966")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393375769"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393375769"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393375769"))][Get cited by]]

OpenAlex: https://openalex.org/W4393375769 (Open access: True)
    
[[https://openalex.org/A5008238212][Jaya Mehara]], [[https://openalex.org/A5066130884][Mariarosa Anania]], [[https://openalex.org/A5084478574][Pavel Kočovský]], [[https://openalex.org/A5021283178][Jana Roithová]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00966  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00966][pdf]])
     
No abstract    

    

* Active Hydrogen-Switchable Dynamic Oxygen Vacancies in MoO3–x upon Ru Nanoparticle Decoration for Boosting Photocatalytic Ammonia Synthesis Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393376514
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05633")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393376514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393376514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393376514"))][Get cited by]]

OpenAlex: https://openalex.org/W4393376514 (Open access: False)
    
[[https://openalex.org/A5070961992][Lulu Zhang]], [[https://openalex.org/A5081675173][Rui Li]], [[https://openalex.org/A5076944433][Lijun Guo]], [[https://openalex.org/A5028973201][Longzhe Cui]], [[https://openalex.org/A5056249472][Xiaochao Zhang]], [[https://openalex.org/A5035024640][Yawen Wang]], [[https://openalex.org/A5023466237][Yunfang Wang]], [[https://openalex.org/A5053777989][Xuan Jian]], [[https://openalex.org/A5049164708][Xiaoming Gao]], [[https://openalex.org/A5056458711][Caimei Fan]], [[https://openalex.org/A5000168358][Jiancheng Wang]], [[https://openalex.org/A5032796616][Jianxin Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05633 
     
No abstract    

    

* Promoting Electrocatalytic Semihydrogenation of Alkynols to Alkenols over a Bimetallic CuAu Alloy Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393377866
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05928")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393377866"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393377866"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393377866"))][Get cited by]]

OpenAlex: https://openalex.org/W4393377866 (Open access: False)
    
[[https://openalex.org/A5018042445][Qinghui Ren]], [[https://openalex.org/A5077447092][Leilei Hao]], [[https://openalex.org/A5042488059][Jiangrong Yang]], [[https://openalex.org/A5074608575][Mengyu Lv]], [[https://openalex.org/A5063892110][Hua Zhou]], [[https://openalex.org/A5079317579][Zhenhua Li]], [[https://openalex.org/A5066410903][Haohong Duan]], [[https://openalex.org/A5062633224][Mingfei Shao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05928 
     
Electrocatalytic semihydrogenation of alkynols to alkenols under ambient conditions using H2O as a hydrogen source is highly attractive in synthetic chemistry. However, it is still challenging to achieve a high Faradaic efficiency (FE) in a wide potential window. Herein, we reported a bimetallic Cu3Au alloy as an efficient catalyst for electrocatalytic semihydrogenation of alkynols to alkenols. Specifically, during semihydrogenation of 2-butyne-1,4-diol (BYD) to 2-butene-1,4-diol (BED), the Cu3Au catalyst achieves 12.6-fold greater reaction rate and higher FE compared with pure Cu (99 vs 63%). Moreover, the Cu3Au maintains >96% FEs in a wide potential window from −0.19 to −0.59 V vs RHE. We demonstrate that the competitive adsorptions of reactive hydrogen (H*) and BYD greatly influence the semihydrogenation processes. The presence of Au in Cu3Au facilitates H* formation and reduces BYD adsorption on Cu, thus enhancing the BYD hydrogenation performance. The Cu3Au catalyst affords a broad substrate scope from alkynols to aromatic alkynes, producing the corresponding alkenes in good selectivities. Finally, we coupled BYD semihydrogenation with glycerol oxidation to replace oxygen evolution reaction in a two-electrode system, showing 40% energy saving at 200 mA for BED production and coproduction of valuable formate at the anode, demonstrating an economical manner.    

    

* Boosting Carrier Separation on a BiOBr/Bi4O5Br2 Direct Z-Scheme Heterojunction for Superior Photocatalytic Nitrogen Fixation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393381136
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06169")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393381136"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393381136"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393381136"))][Get cited by]]

OpenAlex: https://openalex.org/W4393381136 (Open access: False)
    
[[https://openalex.org/A5060888510][Huiqing Wang]], [[https://openalex.org/A5023677466][Zhuohua Chen]], [[https://openalex.org/A5000546225][Yaru Shang]], [[https://openalex.org/A5069916990][Chade Lv]], [[https://openalex.org/A5047452249][Xuhan Zhang]], [[https://openalex.org/A5081362412][Fei Li]], [[https://openalex.org/A5084680669][Qunzeng Huang]], [[https://openalex.org/A5049402435][Xiaodi Liu]], [[https://openalex.org/A5048645240][Wenmin Liu]], [[https://openalex.org/A5085868420][Liang Zhao]], [[https://openalex.org/A5009243555][Liqun Ye]], [[https://openalex.org/A5048668242][Hongmei Xie]], [[https://openalex.org/A5031653081][Xiaoli Jin]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06169 
     
Photocatalytic dinitrogen (N2) fixation is regarded as an achievable technology for ammonia (NH3) production. However, the poor separation efficiency of the photoinduced carriers and ineffective N2 activation remain grand obstacles to high-performance NH3 photosynthesis. Designing advanced heterostructured systems to accelerate charge separation and activate the N2 molecule is a feasible strategy to optimize the photocatalytic N2 fixation activity. Herein, a direct Z-scheme configuration is established between BiOBr and Bi4O5Br2 through a facile one-step solvothermal reaction. This configuration enables effective spatial separation of electron–hole pairs and preserves the robust redox ability of carriers, concurrently promoting N≡N bond activation and diminishing the energy barrier for the rate-determining step. The formation of direct Z-scheme BiOBr/Bi4O5Br2 heterojunctions is mostly attributed to the similarities in their lattice structures and crystal growth conditions. As a result, the direct Z-scheme BiOBr/Bi4O5Br2 heterojunction exhibits a high NH3 yield of 66.87 μmol g–1 h–1 without using sacrificing reagents, surpassing that of the pristine BiOBr and Bi4O5Br2 by approximately 3.3 and 5.6 times, respectively. This study provides an achievable approach to construct direct Z-scheme heterojunction systems for implementing high-performance N2 fixation under mild conditions.    

    

* Recent Advances in Catalytic Nitrogen–Nitrogen Bond Formation Reactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393385196
:TOPICS: Ammonia Synthesis and Electrocatalysis, Homogeneous Catalysis with Transition Metals, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00718")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393385196"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393385196"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393385196"))][Get cited by]]

OpenAlex: https://openalex.org/W4393385196 (Open access: False)
    
[[https://openalex.org/A5070559660][Jianglin Hu]], [[https://openalex.org/A5069099445][Yichen Wu]], [[https://openalex.org/A5088454186][Ying Gao]], [[https://openalex.org/A5036752566][Yinglei Wang]], [[https://openalex.org/A5081452514][Peng Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00718 
     
The lack of effective strategies for direct construction of nitrogen–nitrogen bonds has hampered developments in the synthesis and application of molecules containing hydrazine or azo motifs. Attracted by their properties both in material science and in medicinal chemistry, more and more attention has been drawn to this area, resulting in fast growth in the design and synthesis of azaheterocycles and substituted hydrazines. This review focuses on efficient catalytic approaches toward the formation of N–N and N═N bonds through different strategies, including oxidative dehydrogenation, nitrene-transfer reaction, reductive coupling, and some other recently developed methods.    

    

* General Reaction Network Exploration Scheme Based on Graph Theory Representation and Depth First Search Applied to CO2 Hydrogenation on Pd2Cu Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393385723
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00067")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393385723"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393385723"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393385723"))][Get cited by]]

OpenAlex: https://openalex.org/W4393385723 (Open access: False)
    
[[https://openalex.org/A5058688901][Hui Guo]], [[https://openalex.org/A5052109054][Hong Zhu]], [[https://openalex.org/A5080845219][Guan-Zhang Liu]], [[https://openalex.org/A5010412191][Zhao-Xu Chen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00067 
     
Reaction mechanisms are at the core of understanding reaction systems and designing high-performance catalysts. A complex reaction system often involves various species and elementary reactions, posing a great challenge to determining the reaction mechanism. Here, we proposed a scheme to automatically generate reaction intermediates and elementary reactions to construct a complete reaction network represented by graph theory and employed a depth first search algorithm in the scheme to prune the reaction network to reduce the complexity of the network. With this scheme, microkinetic simulations of CO2 hydrogenation on Pd2Cu using the barriers predicted with the linear thermodynamics–kinetics relations were performed on the network to determine the mechanism and rate- and selectivity-controlling steps of CO2 hydrogenation to ethanol and methanol. Analysis shows that the simulated selectivity of ethanol and methanol agrees well with the experimental results. CO2 + H → COOH is the rate-controlling step, and CHOH + H → CH + H2O, CH2OH + H → CH2 + H2O, and CH2OH + H → CH3OH dominate the ethanol selectivity. Both ethanol and methanol are generated via multiple reaction pathway mechanisms. Investigations of the pruned networks show that quantitatively correct results can be obtained from the pruned or pseudocomplete reaction network, as long as the key pathways are embodied in the network. 94% ethanol selectivity of the complete network can be obtained with the pruned network composed of 60 elementary steps, compared to 176 steps of the complete network. The present work articulates graph theory representation, depth first search algorithm, linear thermodynamics–kinetics relations, and microkinetic simulations to approach complicated heterogeneous reaction systems and exemplifies their comprehensive roles in exploring complex reaction networks.    

    

* Spin Selectivity Induced by the Interface Effect for Boosted Water Oxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393386676
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00142")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393386676"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393386676"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393386676"))][Get cited by]]

OpenAlex: https://openalex.org/W4393386676 (Open access: False)
    
[[https://openalex.org/A5001486972][Zhigao Xue]], [[https://openalex.org/A5024191579][Biao Wu]], [[https://openalex.org/A5088888083][Zheng Zhang]], [[https://openalex.org/A5080998702][Ching-Yu Lin]], [[https://openalex.org/A5022974076][Xiaopeng Li]], [[https://openalex.org/A5056768519][Qiuju Zhang]], [[https://openalex.org/A5085180749][Kai Tao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00142 
     
Creating highly effective electrocatalysts for the oxygen evolution reaction (OER) holds paramount importance in advancing carbon-neutral hydrogen production through water electrolysis. Recent research highlights the crucial role of spin effects on the OER, emphasizing that the manipulation of spin polarization is a promising strategy to augment the OER kinetics. Here, we present a core–shell heterostructure electrocatalyst, which leverages the strong coupling of the interface between antiferromagnetic Co3O4 and NiFe-layered double hydroxide (NiFe-LDH) to trigger a spontaneous magnetic response enhancement, which suggests the strong double exchange interaction at the interface of the core–shell heterostructure. This electrocatalyst displays a 26-fold increase in intrinsic OER activity compared to pristine NiFe-LDH at an overpotential of 0.25 V. Through experimental and computational analyses, we find that the strong double exchange interaction within the heterostructure creates polarized spin conduction channels at the interface, which enables efficient accumulation of electrons with appropriate spin states, thereby lowering the energy barrier for the generation of triplet O2. Our work presents a promising approach to designing high-performance OER catalysts by introducing spin selectivity in traditional metal oxide electrocatalysts.    

    

* Reductive Aminomethylation Using Ammonium Formate and Methanol as N1 and C1 Source: Direct Synthesis of Mono- and Di-Methylated Amines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393409196
:TOPICS: Homogeneous Catalysis with Transition Metals, Carbon Dioxide Utilization for Chemical Synthesis, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00346")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393409196"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393409196"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393409196"))][Get cited by]]

OpenAlex: https://openalex.org/W4393409196 (Open access: False)
    
[[https://openalex.org/A5016156494][Ishani Borthakur]], [[https://openalex.org/A5073045807][S. K. Nandi]], [[https://openalex.org/A5094305289][Yuvraj Bilora]], [[https://openalex.org/A5042696274][Biswajit Sadhu]], [[https://openalex.org/A5070370920][Sabuj Kundu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00346 
     
No abstract    

    

* Hydrophobic Surface Modification of Cu-Based Catalysts for Enhanced Semihydrogenation of Acetylene in Excess Ethylene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393409197
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05466")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393409197"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393409197"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393409197"))][Get cited by]]

OpenAlex: https://openalex.org/W4393409197 (Open access: False)
    
[[https://openalex.org/A5064968189][Ting Liu]], [[https://openalex.org/A5005831427][Jinqi Xiong]], [[https://openalex.org/A5052747544][Qian Luo]], [[https://openalex.org/A5017864467][Shanjun Mao]], [[https://openalex.org/A5030325177][Yong Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05466 
     
No abstract    

    

* Revealing Catalyst Self-Adjustment in C–S Cross-Coupling through Multiscale Liquid-Phase Electron Microscopy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393500093
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06258")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393500093"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393500093"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393500093"))][Get cited by]]

OpenAlex: https://openalex.org/W4393500093 (Open access: False)
    
[[https://openalex.org/A5047280120][Alexey S. Kashin]], [[https://openalex.org/A5022848358][D. M. Arkhipova]], [[https://openalex.org/A5009374050][Liliya T. Sahharova]], [[https://openalex.org/A5030204094][Julia V. Burykina]], [[https://openalex.org/A5053135866][Valentine P. Ananikov]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06258 
     
Carbon–carbon and carbon–heteroatom bond formation mediated by transition metals is a powerful and convenient methodology for organic synthesis. To effectively meet the demands of catalyst design, an in-depth understanding of the reaction mechanisms and pathways of active species evolution is essential. Advances in electron microscopy now offer unprecedented multilevel visualization of liquid-phase chemical systems, providing a powerful tool for mechanistic studies. In this work, we found that the use of either nickel- or copper-based catalyst precursors with preinstalled thiolate groups in combination with pyridinium ionic liquid as the reaction medium leads to a positive synergistic effect, resulting in the formation of transition metal species with high catalytic activity in the C–S cross-coupling reaction between aryl halides and thiols or disulfides. Through multiscale in situ and operando electron microscopy in the liquid phase, we elucidated the self-adjustment of the catalytic system and revealed the simultaneous emergence of metallic nanoparticles and corresponding thiolate species, leading to the independent activation of the C- and S-substrates and the subsequent elimination of the product via organic group metathesis. The proposed methodology for the catalytic preparation of aromatic organosulfides was used for the design of synthetic routes to pharmacologically important substances.    

    

* Cu–Sn Bimetallic Activated Carbon–Carbon Coupling for Efficient Furfural Electroreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393536047
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06346")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393536047"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393536047"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393536047"))][Get cited by]]

OpenAlex: https://openalex.org/W4393536047 (Open access: False)
    
[[https://openalex.org/A5026108994][Xiaofeng Liu]], [[https://openalex.org/A5058040690][Yuhan Sun]], [[https://openalex.org/A5041301033][Hao Ren]], [[https://openalex.org/A5041151940][Yuan Lin]], [[https://openalex.org/A5063554744][Mingbo Wu]], [[https://openalex.org/A5016932552][Zhong-Tao Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06346 
     
Electrochemically driven carbon–carbon coupling utilizing renewable electricity under ambient conditions has emerged as an innovative approach for synthesizing high-value chemicals, which still faces inherent challenges such as low conversion rates and poor selectivity. While electroreducing furfural to hydrofuroin can produce high-quality biofuel, its efficiency need to be promoted. Herein, Cu–Sn bimetallic catalyst has been developed with a conversion rate of furfural of >97% and hydrofuroin selectivity of >67% through equilibrium of the interfacial intermediate *H and *fur-CHOH, which exhibits the greatest state-of-the-art overall performance. Characterization and theoretical calculation reveal that Cu serves as the active site for generating *fur-CHOH, whose electron density can be decreased by introducing Sn, and results in a higher *fur-CHOH coverage and a lower energy barrier of dimerization. Moreover, adding Sn also enables sluggish *H formation to balance interfacial *fur-CHOH and *H, leading to reduced hydrogenation byproducts. The as-developed approach provides valuable insights for optimizing other C–C electrocoupling reactions for the synthesis of high-value chemicals.    

    
