#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Fri Jun 28 01:09:04 2024

Found 40 results from 2024-06-21 to 2024-06-28
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Synthesis of Highly Active GaN:ZnO Photocatalysts Applicable to Z-Scheme Overall Water Splitting Systems  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399848526
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices, Zinc Oxide Nanostructures
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399848526"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399848526"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399848526"))][Get cited by]]

OpenAlex: https://openalex.org/W4399848526 (Open access: False)
    
[[https://openalex.org/A5012469540][Kaiwei Liu]], [[https://openalex.org/A5038087166][Boyang Zhang]], [[https://openalex.org/A5085186808][Jiaming Zhang]], [[https://openalex.org/A5077084592][Yao Xu]], [[https://openalex.org/A5072552402][Jifang Zhang]], [[https://openalex.org/A5053815236][Zihao Zhang]], [[https://openalex.org/A5073697986][Shaoyong Ke]], [[https://openalex.org/A5068560635][Ningning Wang]], [[https://openalex.org/A5014485852][Shanshan Chen]], [[https://openalex.org/A5007957054][Guijun Ma]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02172 
     
The Z-scheme system, integrating an oxygen evolution photocatalyst (OEP) with a hydrogen evolution photocatalyst (HEP), is an ideal strategy for photocatalytic overall water splitting (OWS), in which the development of an efficient OEP remains a challenge. Herein, the GaN:ZnO photocatalyst was synthesized by an ammonium halide-based process to perform a recorded apparent quantum yield of 30% at 420 nm for oxygen evolution from water. It made the GaN:ZnO a remarkable OEP for the construction of three distinct Z-scheme OWS systems, including an unbiased-photoelectrochemical sheet, direct collision, and redox-ion-mediated electron shuttle. The features and parameters of each Z-scheme system were discussed in relation to water splitting, and the most efficient one was established by employing [Fe(CN)6]3–/[Fe(CN)6]4– as an electron shuttle and SrTiO3:Rh as an HEP. This work not only provides a methodology for synthesizing an efficient GaN:ZnO photocatalyst but also highlights its great potential as an OEP applicable to constructing various Z-scheme OWS systems.    

    

* Machine Learning Accelerated First-Principles Study of the Hydrodeoxygenation of Propanoic Acid  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399848574
:TOPICS: Desulfurization Technologies for Fuels, Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01419")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399848574"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399848574"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399848574"))][Get cited by]]

OpenAlex: https://openalex.org/W4399848574 (Open access: False)
    
[[https://openalex.org/A5029181893][Wen‐Bin Yang]], [[https://openalex.org/A5064355644][Kareem Abdelfatah]], [[https://openalex.org/A5087840955][Shrishnu Kumar Kundu]], [[https://openalex.org/A5020788235][Biplab Rajbanshi]], [[https://openalex.org/A5012528456][Gabriel Terejanu]], [[https://openalex.org/A5063674208][Andreas Heyden]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01419 
     
The complex reaction network of catalytic biomass conversions often involves hundreds of surface intermediates and thousands of reaction steps, greatly hindering the rational design of metal catalysts for these conversions. Here, we present a framework of machine learning (ML)-accelerated first-principles studies for the hydrodeoxygenation (HDO) of propanoic acid over transition metal surfaces. The microkinetic model (MKM) is initially parametrized by ML-predicted energies and iteratively improved by identifying the rate-determining species and steps (RDS), computing their energies by density functional theory (DFT), and reparameterizing the MKM until all the RDS are computed by DFT. The Gaussian process (GP) model performs significantly better than the linear ridge regression model for predicting both the adsorption free energies and transition state free energies. Parameterized with energies from the GP model, only 5–20% of the full reaction network has to be computed by DFT for the MKM to possess DFT-level accuracy for the TOF and dominant reaction pathway. While the linear ridge regression model performs worse than the GP model, its performance is greatly improved when only transition states are predicted by the regression model and adsorption energies are computed by DFT. Overall, we find that a high accuracy in adsorption free energies is more important for a reliable MKM than a high accuracy in TS free energies. Finally, based on the GP model with GOH and GCHCHCO as catalyst descriptors, we build two-dimensional volcano plots in activity and selectivity that can help design promising alloy catalysts for HDO reactions of organic acids.    

    

* Mechanistic Insights into the Electrochemical Oxidation of 5-Hydroxymethylfurfural on a Thin-Film Ni Anode  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399853867
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01448")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399853867"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399853867"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399853867"))][Get cited by]]

OpenAlex: https://openalex.org/W4399853867 (Open access: False)
    
[[https://openalex.org/A5049586249][Aditya Prajapati]], [[https://openalex.org/A5023895763][Nitish Govindarajan]], [[https://openalex.org/A5028727210][Wenyu Sun]], [[https://openalex.org/A5075996643][Jiayi Huang]], [[https://openalex.org/A5045214290][Hossein Bemana]], [[https://openalex.org/A5068592301][Jeremy T. Feaster]], [[https://openalex.org/A5042139840][Sneha A. Akhade]], [[https://openalex.org/A5018580006][Nikolay Kornienko]], [[https://openalex.org/A5051674745][Christopher Hahn]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01448 
     
The electrochemical oxidation of alcohols is being explored as a favorable substitute for the oxygen evolution reaction owing to its capability to generate high-value products and lower overpotentials. Herein, we present a systematic investigation into the electrochemical oxidation of 5-hydroxymethylfurfural (HMF), a model biomass platform chemical, on a thin-film nickel catalyst, aiming to investigate the underlying reaction mechanism and shed light on the role of the catalyst's microenvironment and phase on activity and product selectivity. Utilizing a combined experimental and computational approach, we demonstrate that NiOOH is the active phase for HMF oxidation. Additionally, we find a substantial impact of the electrochemical environment, particularly the electrolyte pH, on the reaction. Under highly alkaline conditions (pH = 13), higher activity for HMF oxidation is observed, accompanied by an increased selectivity toward 2,5-furandicarboxylic acid (FDCA) production. Conversely, a less alkaline environment (pH = 11) results in diminished HMF oxidation activity and a higher preference for the partial oxidation product 2,5-diformylfuran (DFF). Mechanistic insights from DFT studies reveal that geminal diols that are present under highly alkaline conditions undergo hydride transfer via HMFCA, while a shift to an alkoxide route occurs at a lower pH, favoring the DFF pathway. Hydride transfer energetics are also strongly affected by the surface Ni oxidation state. This integrated approach, bridging experimental and computational insights, provides a general framework for investigating the electrochemical oxidation of aldehydes and alcohols, thereby advancing rational design strategies in electrocatalysts for alcohol electro-oxidation reactions.    

    

* Accelerating Semihydrogenation of Cinnamaldehyde by Water over a Au/α-MoC Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399854204
:TOPICS: Catalytic Nanomaterials, Desulfurization Technologies for Fuels, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02448")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399854204"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399854204"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399854204"))][Get cited by]]

OpenAlex: https://openalex.org/W4399854204 (Open access: False)
    
[[https://openalex.org/A5075135602][Y. P. Lu]], [[https://openalex.org/A5062983920][Qiao Chen]], [[https://openalex.org/A5057377195][Yunlong Zhang]], [[https://openalex.org/A5088892322][Wei Yan]], [[https://openalex.org/A5036673165][Xiaohui Hou]], [[https://openalex.org/A5004055137][Rui Huang]], [[https://openalex.org/A5022049240][Dehui Deng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02448 
     
Replacing H2 with H2O as the hydrogen source for the water-involved selective hydrogenation of cinnamaldehyde to cinnamyl alcohol (WSHCC) is very attractive yet is underdeveloped by a much lower H2O conversion rate than H2. Here, we report the realization of a high-efficiency WSHCC process by a synergy of CO adsorption and H2O dissociation over a Au/α-MoC1–x boundary. It shows a specific molar rate of 60.86 mol molAu–1 h–1 to cinnamyl alcohol at 96 °C, which is nearly 12-fold that reported earlier, and maintains a high conversion of over 99% and a high selectivity of 77%. Mechanistic studies indicate that the Au/α-MoC1–x boundary accommodates atomically dispersed Auδ+ sites for adsorbing CO, vacating oxygen-covered α-MoC1–x and thereby creating isolated Mo sites for the preferred adsorption and hydrogenation of C═O bonds over that of C═C bonds. This provides a catalyst design strategy for high-efficiency C═O hydrogenation by water.    

    

* MOR-Type Titanosilicate with Specific Ti Location in Defective T3 Sites for Efficient Cyclohexanone Ammoximation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399855782
:TOPICS: Zeolite Chemistry and Catalysis, Mesoporous Materials, Novel Methods for Cesium Removal from Wastewater
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01914")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399855782"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399855782"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399855782"))][Get cited by]]

OpenAlex: https://openalex.org/W4399855782 (Open access: False)
    
[[https://openalex.org/A5067296919][Zhipeng Wan]], [[https://openalex.org/A5085851044][Jing-Yi Tan]], [[https://openalex.org/A5053686959][Wei Chen]], [[https://openalex.org/A5038416644][Longkang Zhang]], [[https://openalex.org/A5075201929][Xianchen Gong]], [[https://openalex.org/A5036574856][Chengwei Zhai]], [[https://openalex.org/A5042987873][Hengyong Xu]], [[https://openalex.org/A5084204775][Anming Zheng]], [[https://openalex.org/A5018681961][Peng Wu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01914 
     
Controlling the location and microenvironment of active centers in the zeolite framework is critical for understanding the in-depth structure–performance relationships of catalytic systems and constructing highly efficient catalysts. Herein, we have developed an MOR-type titanosilicate (denoted as 6M-Ti-M360) with an extremely low framework Ti content (Si/Ti = 300), exhibiting not only ultrahigh catalyst weight-based conversion (81%) but also a record-breaking turnover number (TON = 5845) per Ti site in batchwise ammoximation of cyclohexanone. Its highly isolated and active Ti species took the specific position of defective T3 sites within the eight-member ring side pockets of the MOR topology, evidenced by molecular dimension-dependent shape-selective experiments and theoretical evaluation of the catalytic activation ability of the different crystallographic Ti sites at the molecular level. Despite an extremely low Ti content but with the most active Ti on the defective T3 sites, the 6M-Ti-M360 catalyst maintained the cyclohexanone conversion and cyclohexanone oxime selectivity both as high as 99% for a long lifetime (314 h) in a continuous slurry bed reactor, capable of producing 1100 kg of oxime per gram of Ti. The clarification of the location and local microenvironment of Ti active sites may provide new insights into the exploration and construction of highly active sites in zeolitic catalysts.    

    

* Beyond the Chemical Step: The Role of Substrate Access in Acyltransferase from Mycobacterium smegmatis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399860420
:TOPICS: Macromolecular Crystallography Techniques, Nucleotide Metabolism and Enzyme Regulation, Glycosylation in Health and Disease
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00812")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399860420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399860420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399860420"))][Get cited by]]

OpenAlex: https://openalex.org/W4399860420 (Open access: False)
    
[[https://openalex.org/A5007722925][Henrique F. Carvalho]], [[https://openalex.org/A5084338770][Luuk Mestrom]], [[https://openalex.org/A5035234231][Ulf Hanefeld]], [[https://openalex.org/A5067406221][Jürgen Pleiss]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00812 
     
Acyltransferase from Mycobacterium smegmatis is a versatile enzyme, which catalyzes the transesterification of esters in aqueous media due to a kinetic preference of the synthesis reaction over the thermodynamically favored hydrolysis reaction. In the active octamer, the active site is deeply buried and connected to the protein surface by long and hydrophobic substrate access channels. The role of the access channel in controlling catalytic activity and substrate specificity was investigated by molecular dynamics simulations and Markov-state models, and the thermodynamics and kinetics of binding of acyl donors, acceptors, and water were compared. Despite the hydrophobic nature of the substrate access channel, water is present in the channel and competes with the acyl acceptors for access to the active site. The binding free energy profiles in the access channel and the flux of butyl and benzyl alcohol and vinyl acetate were analyzed in the concentration range between 10 and 500 mM and compared to water. The flux showed a maximum at an alcohol concentration of 50–100 mM, in agreement with experimental observations. At the maximum, the flux of alcohol approaches 50% of the flux of water, which explains the high transesterification rate as compared to hydrolysis. The molecular origin of this effect is due to the accumulation of alcohol molecules along the access channel. Extensive molecular dynamics simulations and analysis of trajectories by a Markov-state model provided insights into the role of the access channel in activity and specificity by controlling access and binding of competing substrates.    

    

* Tuning Selectivity of CO2 Hydrogenation via Support Composition Modification Adjusted the Activity Reduction of H Species over Ce1–xPrxO2−δ-Supported Metal (Ru, Rh) Nanoclusters  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399871818
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01201")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399871818"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399871818"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399871818"))][Get cited by]]

OpenAlex: https://openalex.org/W4399871818 (Open access: False)
    
[[https://openalex.org/A5044266671][De‐Jiu Wang]], [[https://openalex.org/A5034651849][Xiaochen Sun]], [[https://openalex.org/A5066996921][Hai‐Jing Yin]], [[https://openalex.org/A5050592208][Hao Dong]], [[https://openalex.org/A5089739373][Haichao Liu]], [[https://openalex.org/A5045398749][Yawen Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01201 
     
Selectivity control of supported metal catalysts, which are most widely utilized in the field of heterogeneous catalysis, is of great scientific significance to obtaining the desired chemical product in a multipath reaction but has remained a grand challenging issue. In this work, we demonstrate that the selectivity of CO2 hydrogenation from CH4 to CO can be tuned by a robust and unique support doping strategy by changing the reduction activity of H species over M/Ce1–xPrxO2−δ (M = Ru, Rh) in which metal (M) nanoclusters showed the same existence form on differently doped ceria nanorod supports. The CH4 selectivity of the catalyst decreased with an increase in the Pr content in the support. The selectivity of CH4 on Ru/CeO2 was higher than 90%, while on Ru/Ce0.2Pr0.8O2−δ, the selectivity of CO reached 80%. A variety of techniques, including steady-state isotope transient kinetic analysis (SSITKA) type in situ diffuse reflectance infrared Fourier transform spectroscopy (DRIFTS)–mass spectrum (MS), temperature-programmed desorption (TPD) and temperature-programmed surface reaction (TPSR), had been applied in this work to analyze the structure–activity relationship between the doping of Pr and the selectivity of the CO2 hydrogenation reaction. Ru sites were not directly involved in the hydrogenation of carbon-containing intermediate species (including bicarbonate and formate) during the CO2 hydrogenation reaction. The active H species on the support sites, which are incorporated in RE3+–OH, directly contacted and reacted with the carbon-containing intermediate species. The introduction of Pr in the support weakened the reducing ability of the support, thus decreasing the reducing ability of H species on the surface of the catalyst, which further hindered the conversion of formate into CH4, resulting in the declined CH4 selectivity. Our study clearly revealed the important role of support in the CO2 hydrogenation reaction and proposed a strategy to modulate the reaction selectivity via support doping. By changing the redox performance of the support, the activity of H species on the support can be adjusted. Thus, the conversion of important reaction intermediates (such as formate) can be affected, so as to achieve precise regulation of the reaction products. We have provided a broader perspective for the selective catalyst design of heterogeneous catalysis and the reaction mechanism study of supported metal catalysts.    

    

* Photochemical Reductive Carboxylation of N-Benzoyl Imines with Oxalate Accelerated by Formation of EDA Complexes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399871819
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399871819"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399871819"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399871819"))][Get cited by]]

OpenAlex: https://openalex.org/W4399871819 (Open access: False)
    
[[https://openalex.org/A5065971725][Wen Liu]], [[https://openalex.org/A5088737849][Pei Xu]], [[https://openalex.org/A5023430107][H. Jiang]], [[https://openalex.org/A5019513406][Menglei Li]], [[https://openalex.org/A5027464022][Tian-Zi Hao]], [[https://openalex.org/A5017969411][Yiqin Liu]], [[https://openalex.org/A5016727969][Shaolin Zhu]], [[https://openalex.org/A5020447705][Kun-Xiao Zhang]], [[https://openalex.org/A5012627436][Xu Zhu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02007 
     
No abstract    

    

* An Enzyme Catalyzing the Oxidative Maturation of Reduced Prenylated-FMN to Form the Active Coenzyme  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399879371
:TOPICS: Biotechnological Production of Vanillin, Metabolic Engineering and Synthetic Biology, Chemistry of Quinone Methides
:PUBLICATION_DATE: 2024-06-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02747")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399879371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399879371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399879371"))][Get cited by]]

OpenAlex: https://openalex.org/W4399879371 (Open access: False)
    
[[https://openalex.org/A5058094440][Daniel A. DiRocco]], [[https://openalex.org/A5075100011][Pronay Roy]], [[https://openalex.org/A5031037227][Anushree Mondal]], [[https://openalex.org/A5089860875][Prathamesh M. Datar]], [[https://openalex.org/A5057584218][E. Neil G. Marsh]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02747 
     
No abstract    

    

* Formal Decarbonylation of 1,2-Diketones Enabled by Synergistic Catalysis of Lewis Acid–Base Pairs and Redox Properties in CeO2  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399885909
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-06-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02493")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399885909"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399885909"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399885909"))][Get cited by]]

OpenAlex: https://openalex.org/W4399885909 (Open access: False)
    
[[https://openalex.org/A5090814416][Takehiro Matsuyama]], [[https://openalex.org/A5013371769][Takafumi Yatabe]], [[https://openalex.org/A5006226044][Kazuya Yamaguchi]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02493 
     
Various decarbonylation reactions via oxidative addition of carbonyl compounds to metal catalysts can be applied to late-stage modification and have been actively studied to date; however, several inherent problems derived from the oxidative addition are difficult to solve, such as toxic CO production, deactivation of catalysts by CO adsorption, intolerance of some functional groups, or air-sensitivity of catalysts. In this context, formal decarbonylation, which eliminates CO as other compounds without involving oxidative addition, is attractive but hardly reported, especially using heterogeneous catalysts. Herein, formal decarbonylation of diaryl 1,2-diketones to afford monoketones using CeO2 as a reusable heterogeneous catalyst and O2 in the air as the terminal oxidant was developed, generating CO2 as the only byproduct. The results revealed that the reaction was enabled by the synergistic catalytic effect of the Lewis acid–base pairs and redox properties in CeO2.    

    

* Efficient H2 Production from Biomass-Based HCO2H by Cooperation of Quantum Dots Photocatalysts with Weak HCHO Adsorption and In Situ Generated Ni0  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399896204
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-06-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01708")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399896204"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399896204"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399896204"))][Get cited by]]

OpenAlex: https://openalex.org/W4399896204 (Open access: False)
    
[[https://openalex.org/A5022391449][Wenxin Niu]], [[https://openalex.org/A5008734353][Wanghui Zhao]], [[https://openalex.org/A5049187274][Kaiwen Feng]], [[https://openalex.org/A5054449606][Fu-Jia Tang]], [[https://openalex.org/A5062351268][Tao Wang]], [[https://openalex.org/A5009902978][Kaixuan Wang]], [[https://openalex.org/A5002470838][Shaohua Shen]], [[https://openalex.org/A5014927466][Yang Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01708 
     
Efficient hydrogen (H2) production from renewable resources, such as biomass, one of the largest renewable resources on the earth, instead of fossil resources, is highly desirable. Making it via HCO2H as an intermediate for H2 production from biomass both facilitates efficient H2 production and can avoid the issues of H2 storage. Herein, we report efficient H2 production from raw biomass-based formic acid (HCO2H) by a noble-metal-free catalysis system under mild conditions, enabled by cooperation of CdS/ZnS-S2– quantum dots photocatalysts with weak formaldehyde (HCHO) adsorption and in situ generated Ni0, resulting in H2 with a 94% yield in 3.5 h, with a 99.7% selectivity and a 537 ± 14 mol mg–1 h–1 average rate at 50 °C under visible-light irradiation. This study should promote the exploration of catalytic systems for streamlined H2 production from renewable biomass for practical application.    

    

* Amino Acid Synthesis through C–N Coupling between α-Ketoacids and Hydroxylamine from Nitrate Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399896383
:TOPICS: Ammonia Synthesis and Electrocatalysis, Homogeneous Catalysis with Transition Metals, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01793")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399896383"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399896383"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399896383"))][Get cited by]]

OpenAlex: https://openalex.org/W4399896383 (Open access: False)
    
[[https://openalex.org/A5041344732][Yiyang Zhou]], [[https://openalex.org/A5083764797][Ruizhi Duan]], [[https://openalex.org/A5043532509][Qinge Huang]], [[https://openalex.org/A5014014148][Chunmei Ding]], [[https://openalex.org/A5011065863][Can Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01793 
     
The artificial synthesis of amino acids is an important yet challenging subject. Electrocatalytic C–N coupling from organic acids and nitrogen sources provides an opportunity for this target but with the difficulty of C–N bond formation toward the production of amino acids. Herein, we report the synthesis of amino acids (alanine, glutamic acid, glycine, leucine, valine) from nitrate and α-ketoacids with a hybrid catalyst, cobalt phthalocyanine immobilized on carbon nanotubes (CoPc/CNT). The Faradaic efficiency for alanine production with CoPc/CNT is as high as 61%. The CoPc catalyst integrated with CNTs can catalyze nitrate reduction to hydroxylamine, which is switched from a thermodynamically uphill to a downhill process. The hydroxylamine intermediate attacks the α-carbon of an α-ketoacid to form an oxime. Amino acids are produced by the reduction of oximes catalyzed by CNTs. The bifunctionality of CoPc/CNT steers the tandem catalytic reaction toward the efficient production of amino acids in one pot. This work identifies that enhancing the reduction of nitrate to hydroxylamine is the key to C–N bond formation in amino acid synthesis.    

    

* Synergizing Amino Tethering and Carbon Shell Confinement Enables Confinement Synthesis of PtCo Intermetallic Catalysts for Highly Durable Fuel Cells  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399896671
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01202")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399896671"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399896671"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399896671"))][Get cited by]]

OpenAlex: https://openalex.org/W4399896671 (Open access: False)
    
[[https://openalex.org/A5049785358][Kechuang Wan]], [[https://openalex.org/A5023433080][Chuanqi Luo]], [[https://openalex.org/A5039422700][Jue Wang]], [[https://openalex.org/A5067653842][Haitao Chen]], [[https://openalex.org/A5032122445][Jingjing Zhang]], [[https://openalex.org/A5024831032][Bing Li]], [[https://openalex.org/A5087120666][Maorong Chai]], [[https://openalex.org/A5088011909][Pingwen Ming]], [[https://openalex.org/A5078891674][Cunman Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01202 
     
Intermetallic compounds possess superior catalytic performance over their disordered alloy counterparts, while their synthesis usually requires high-temperature treatment, which causes the sintering of catalysts. This work demonstrates the high-temperature confinement synthesis (HTCS) of PtCo intermetallic compounds for oxygen reduction reaction (ORR) by integrating ultrathin nitrogen-doped carbon shell (NCS) confined PtCo alloy into −NH2 functionalized black pearls 2000 carbon architectures (PtCo@NCS/BP-NH2). Benefiting from amino tethering and carbon shell confinement, high-temperature sintering behavior is effectively inhibited. PtCo@NCS/BP-NH2 possesses outstanding ORR performance, and the assembled single cell exhibits a small peak power density loss rate of 4% after the accelerated durability test (ADT), outperforming PtCo/BP (12.5%) and commercial Pt/C (18.9%). Theoretical calculations along with experiments reveal that PtCo and NCS synergically optimize the electronic structure, weaken the Pt–O dipole effect, and lower the reaction barrier for ORR. The study provides insight into the HTCS of catalysts and unveils intrinsic electronic interaction for ORR.    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399897740
:TOPICS: 
:PUBLICATION_DATE: 2024-06-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i012_1814477")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399897740"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399897740"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399897740"))][Get cited by]]

OpenAlex: https://openalex.org/W4399897740 (Open access: True)
    
, ACS catalysis. 14(12)] 2024. https://doi.org/10.1021/csv014i012_1814477  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i012_1814477][pdf]])
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399897753
:TOPICS: 
:PUBLICATION_DATE: 2024-06-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i012_1814478")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399897753"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399897753"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399897753"))][Get cited by]]

OpenAlex: https://openalex.org/W4399897753 (Open access: True)
    
, ACS catalysis. 14(12)] 2024. https://doi.org/10.1021/csv014i012_1814478  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i012_1814478][pdf]])
     
No abstract    

    

* Structure and Reactivity of Active Oxygen Species on Silver Surfaces for Ethylene Epoxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399908109
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-06-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01566")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399908109"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399908109"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399908109"))][Get cited by]]

OpenAlex: https://openalex.org/W4399908109 (Open access: True)
    
[[https://openalex.org/A5000351917][Minjie Guo]], [[https://openalex.org/A5034695775][Nanchen Dongfang]], [[https://openalex.org/A5037289525][Marcella Iannuzzi]], [[https://openalex.org/A5054120563][Jeroen A. van Bokhoven]], [[https://openalex.org/A5014379900][Luca Artiglia]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01566  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01566][pdf]])
     
The epoxidation of ethylene stands as one of the most important industrial catalytic reactions, and silver-based catalysts show superior activity and selectivity. Oxygen is activated on the surface of silver during the reaction and exerts a substantial impact on product selectivity. Notably, the oxygen species residing in the topmost atomic layers profoundly influence the reactivity of a catalyst. However, their characterization under in situ reaction conditions remains a huge challenge, and specific structures have not been identified yet. In this study, we employ in situ X-ray photoelectron spectroscopy and density functional theory calculations to determine the oxygen species formed at the topmost atomic layers of a silver foil and to assign them a structure. Three different groups of oxygen species activated on silver are identified: (i) surface lattice oxygen and two oxygen species originating from associatively adsorbed dioxygen and (ii) top and (iii) subsurface oxygen. Transient in situ photoelectron spectroscopy experiments are carried out to reveal the dynamic evolution and thus reactivity of the different oxygen species under ethylene epoxidation reaction environments. The top oxygen atom from the adsorbed associated dioxygen is the most active. Meanwhile, a frequency-selective data analysis method, developed to process time-resolved data, provides insights into the evolving trends of peak intensities for different oxygen species. The versatility of this method suggests its potential application in future time-resolved characterization studies.    

    

* Asymmetric Oxygen Vacancy-Promoted Synthesis of Aminoarenes from Nitroarenes Using Waste H2S as a “Hydrogen Donor”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399916695
:TOPICS: Catalytic Reduction of Nitro Compounds, Homogeneous Catalysis with Transition Metals, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-06-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02478")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399916695"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399916695"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399916695"))][Get cited by]]

OpenAlex: https://openalex.org/W4399916695 (Open access: False)
    
[[https://openalex.org/A5085266092][Xiaohai Zheng]], [[https://openalex.org/A5084615025][Bang Li]], [[https://openalex.org/A5003637819][Rui Huang]], [[https://openalex.org/A5019208828][Weiping Jiang]], [[https://openalex.org/A5040990019][Lijuan Shen]], [[https://openalex.org/A5053199253][Ganchang Lei]], [[https://openalex.org/A5014506962][Shiping Wang]], [[https://openalex.org/A5076466524][Shiping Wang]], [[https://openalex.org/A5053219554][Lilong Jiang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02478 
     
The conversion of H2S to high-value-added products is appealing for alleviating environmental pollution and realizing resource utilization. Herein, we report the reduction of nitrobenzene to aniline using waste H2S as a "hydrogen donor" over the catalyst of FeCeO2−δ with abundant oxygen vacancies (Ov), especially an asymmetric oxygen vacancy (ASOv). The electron-rich nature of the ASOv sites facilitates electron transfer to the electron-deficient nitro group, promoting the adsorption and activation of Ph–NO2 through the elongation and cleavage of the N–O bond. Benefiting from the formation of abundant ASOv sites, the resulting FeCeO2−δ achieves an impressive 85.6% Ph–NO2 conversion and 81.9% Ph–NH2 selectivity at 1.5 MPa and 90 °C, which surpasses that of pure CeO2 with flower and rod morphologies. In situ FT-IR measurements combined with density functional theory calculations have elucidated a plausible reaction mechanism and a rate-limiting step in the hydrogenation of Ph–NO2 by H2S.    

    

* The Conundrum of “Pair Sites” in Langmuir–Hinshelwood Reaction Kinetics in Heterogeneous Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399916760
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-06-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02813")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399916760"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399916760"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399916760"))][Get cited by]]

OpenAlex: https://openalex.org/W4399916760 (Open access: True)
    
[[https://openalex.org/A5028323119][Daniyal Kiani]], [[https://openalex.org/A5066491588][Israel E. Wachs]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02813  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c02813][pdf]])
     
No abstract    

    

* Structural Aspects of MoSx Prepared by Atomic Layer Deposition for Hydrogen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399858629
:TOPICS: Electrocatalysis for Energy Conversion, Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Two-Dimensional Materials
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01445")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399858629"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399858629"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399858629"))][Get cited by]]

OpenAlex: https://openalex.org/W4399858629 (Open access: True)
    
[[https://openalex.org/A5038649954][Miika Mattinen]], [[https://openalex.org/A5017541508][Wei Chen]], [[https://openalex.org/A5070451493][Rebecca A. Dawley]], [[https://openalex.org/A5048719407][Marcel A. Verheijen]], [[https://openalex.org/A5084285140][Emiel J. M. Hensen]], [[https://openalex.org/A5018346857][W. M. M. Kessels]], [[https://openalex.org/A5079178929][Ageeth A. Bol]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01445  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01445][pdf]])
     
Molybdenum sulfides (MoSx) in both crystalline and amorphous forms are promising earth-abundant electrocatalysts for hydrogen evolution reaction (HER) in acid. Plasma-enhanced atomic layer deposition was used to prepare thin films of both amorphous MoSx with adjustable S/Mo ratio (2.8–4.7) and crystalline MoS2 with tailored crystallinity, morphology, and electrical properties. All the amorphous MoSx films transform into highly HER-active amorphous MoS2 (overpotential 210–250 mV at 10 mA/cm2 in 0.5 M H2SO4) after electrochemical activation at approximately −0.3 V vs reversible hydrogen electrode. However, the initial film stoichiometry affects the structure and consequently the HER activity and stability. The material changes occurring during activation are studied using ex situ and quasi in situ X-ray photoelectron spectroscopy. Possible structures of as-deposited and activated catalysts are proposed. In contrast to amorphous MoSx, no changes in the structure of crystalline MoS2 catalysts are observed. The overpotentials of the crystalline films range from 300 to 520 mV at 10 mA/cm2, being the lowest for the most defective catalysts. This work provides a practical method for deposition of tailored MoSx HER electrocatalysts as well as new insights into their activity and structure.    

    

* Electroreductive C–C Coupling of Furfural to Jet Fuel Precursors in Neutral Media via Synergistic Catalysis of the Polyoxotungstate and Cu Complex  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399864928
:TOPICS: Polyoxometalate Clusters and Materials, Catalytic Oxidation of Alcohols, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-06-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02524")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399864928"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399864928"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399864928"))][Get cited by]]

OpenAlex: https://openalex.org/W4399864928 (Open access: False)
    
[[https://openalex.org/A5086424066][Weijie Geng]], [[https://openalex.org/A5030611214][Di Zhang]], [[https://openalex.org/A5037930437][Ni Zhen]], [[https://openalex.org/A5079931590][Jianshi Du]], [[https://openalex.org/A5018854741][Jing Dong]], [[https://openalex.org/A5022584534][Chengpeng Liu]], [[https://openalex.org/A5083328254][Shi‐Lu Chen]], [[https://openalex.org/A5022773758][Yingnan Chi]], [[https://openalex.org/A5034018070][Changwen Hu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02524 
     
The electrochemical coupling of biomass platform molecules to biofuels provides a promising method for addressing energy crises and environmental issues. However, achieving high yields of C–C coupling products under ambient conditions remains a challenge. Herein, we present a highly efficient electrocatalyst, [Cu(pz)]3[PW12O40] (Cu-PW12), fabricated by combining a Cu-pz complex (pz = pyrazine), a redox catalytic center, with Keggin-type PW12O40, and an electron sponge. Cu-PW12 exhibits remarkable catalytic activity for the electroreductive C–C coupling of furfural (FF), a bulk and low-cost biomass platform chemical, to produce a jet fuel precursor, hydrofuroin (HDF). Under neutral and ambient conditions, over 99% of FF is converted and the selectivity of HDF reaches 91.2%. Furthermore, experimental and theoretical studies, including control experiments, kinetic isotope studies, electrochemical and spectral analyses, and DFT calculations, reveal a synergistic catalysis effect between Cu center and PW12. The introduction of PW12 not only facilitates electron transfer, improving FF conversion, but also changes the rate-determining step, favoring the formation of HDF. Under turnover conditions, the Cu-PW12 catalyst is initially reduced and then FF is reduced by the Cu center to ketyl radical after protonation on the electrode surface. Finally, the self-coupling of two ketyl radicals in solution leads to the generation of HDF.    

    

* Copper-Catalyzed Dearomative trans-1,2-Carboamination  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399872712
:TOPICS: Homogeneous Catalysis with Transition Metals, Gold Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02656")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399872712"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399872712"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399872712"))][Get cited by]]

OpenAlex: https://openalex.org/W4399872712 (Open access: False)
    
[[https://openalex.org/A5086701434][Charles W. Davis]], [[https://openalex.org/A5071149622][Yanrong Li]], [[https://openalex.org/A5071773009][Yu Zhang]], [[https://openalex.org/A5028711961][Zohaib Siddiqi]], [[https://openalex.org/A5021833788][Peng Liu]], [[https://openalex.org/A5058389691][David Šarlah]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02656 
     
We have achieved the arenophile-mediated, copper-catalyzed dearomative trans-1,2-carboamination of nonactivated arenes with alkyl organometallic nucleophiles. This simple and practical procedure was used to prepare diverse, stereochemically rich alkylated cyclohexadienes from readily available arenes. Synthetic utility was demonstrated through the rapid preparation of complex small molecules difficult to access by conventional routes. Finally, we conducted DFT studies to explore the catalytic process, including a study of the reaction pathway and an examination of the divergent regioselectivity observed with substituted arenes.    

    

* Photochemical Tuning of Tricoordinated Nitrogen Deficiency in Carbon Nitride to Create Delocalized π Electron Clouds for Efficient CO2 Photoreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399891463
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-06-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01636")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399891463"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399891463"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399891463"))][Get cited by]]

OpenAlex: https://openalex.org/W4399891463 (Open access: False)
    
[[https://openalex.org/A5014114077][Lei Li]], [[https://openalex.org/A5004966861][Huanhuan Lu]], [[https://openalex.org/A5049567901][Cungui Cheng]], [[https://openalex.org/A5008609658][Xinyan Dai]], [[https://openalex.org/A5065710684][Fang Chen]], [[https://openalex.org/A5089866628][Jiqiang Ning]], [[https://openalex.org/A5088025824][Wentao Wang]], [[https://openalex.org/A5004880276][Yong Hu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01636 
     
Precisely engineering point defects holds promise for the development of state-of-the-art photocatalysts for CO2 conversion. This study demonstrates the controllable creation of nitrogen vacancies (VNs) in the centers of heptazine rings of graphitic carbon nitrides (g-C3N4) via a photochemical-assisted nitrogen etching strategy. Spectroscopic analyses and theoretical simulations elucidate the photochemical process to hydrogenate the nitrogen situated at the center of the g-C3N4 heptazine ring and then release an ammonia molecule, accompanied by the photooxidation of the sacrificial agents. The catalyst with an optimal VNs concentration achieves a CO generation rate of 35.2 μmol g–1 h–1 with nearly 100% selectivity, comparable to the performance of the reported g-C3N4 materials. The remarkably improved photoactivity is due to the adjustments of the electronic structures and the midgap states of g-C3N4 by the delocalized π electron cloud created in the 12-membered ring surrounding the VN, which maximizes the light-harvesting efficiencies and suppresses the recombination of photogenerated electrons and holes. The VNs also activates the neighboring catalytic carbon centers to reduce the energy barrier for CO2 reduction. This work provides a good design concept to regulate catalytic activity by engineering point defects.    

    

* CuOx Nanopatches Positioned at Lewis Acidic Sites of TiO2 for Propylene Epoxidation Using Molecular Oxygen  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399896664
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01749")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399896664"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399896664"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399896664"))][Get cited by]]

OpenAlex: https://openalex.org/W4399896664 (Open access: False)
    
[[https://openalex.org/A5022537013][Zun-Ren Lv]], [[https://openalex.org/A5060000312][Leilei Kang]], [[https://openalex.org/A5014023117][Xiaoli Pan]], [[https://openalex.org/A5020530505][Yang Su]], [[https://openalex.org/A5054863233][Hua Wang]], [[https://openalex.org/A5089015352][Lin Li]], [[https://openalex.org/A5055302562][Xiao Yan Liu]], [[https://openalex.org/A5053108670][Aiqin Wang]], [[https://openalex.org/A5040895512][Tao Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01749 
     
Controlling the precise placement of active metals on supports is highly desirable yet challenging, which governs both the reaction pathway and the ultimate outcomes of catalytic reactions. Herein, the Cu species are positioned to the Lewis acidic sites created by the ultrahigh-temperature calcination of TiO2, where the atomic structures of the Lewis acids are identified as five-coordinated Ti4+ cations bound to three-coordinated O2– anions (Lβ sites) by in situ characterizations. Owing to the robust chemical affinity, CuOx manifests itself as a nanopatch. The Cu/TiO2 catalyst without any modifications exhibits a propylene oxide (PO) formation rate of 44 mmol gCu–1 h–1 for direct epoxidation of propylene using molecular oxygen (DEP). The PO yield on Cu/TiO2 can be efficiently correlated with the quantity of the decreased Lewis acids, which demonstrates that the intimated interaction between the Cu species and Lewis acids should be responsible for PO production. Furthermore, density functional theory calculations suggest that Cu+ in the Ti–O–Cu interface formed at the Lβ sites is the active site of the DEP reaction, with the aid of the adjacent Cu atom. This study provides a Cu-based catalyst for the DEP reaction.    

    

* Selective Hydrogenation of Quinizarins to Leuco-quinizarins and Their Direct Derivatization Using Flow-Batch-Separator Unified Reactors under Continuous-Flow Conditions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399933284
:TOPICS: Droplet Microfluidics Technology, Origins and Future of Microfluidics, State-of-the-Art in Process Optimization under Uncertainty
:PUBLICATION_DATE: 2024-06-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02955")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399933284"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399933284"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399933284"))][Get cited by]]

OpenAlex: https://openalex.org/W4399933284 (Open access: True)
    
[[https://openalex.org/A5088285820][Hiroyuki Miyamura]], [[https://openalex.org/A5082440766][Aditya Sharma]], [[https://openalex.org/A5000298674][Masasuke Takata]], [[https://openalex.org/A5041947507][Rokuro Kajiyama]], [[https://openalex.org/A5049553063][Shū Kobayashi]], [[https://openalex.org/A5066414781][Yoshihiro Kon]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02955  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c02955][pdf]])
     
Anthraquinone derivatives are classes of compounds employed in the production of valuable materials. Leuco-quinizarin, the 2-electron-reduced form of quinizarin (1,4-dihydroxy-anthraquinone), is a highly active and useful reactant for the synthesis of variety of anthraquinone derivatives. However, conventional methods of leuco-quinizarin synthesis require stoichiometric amounts of inorganic reductants and acids or bases. We developed Pt/DMPSi-Al2O3 and Pt-Ni/DMPSi-Al2O3 as highly active and selective heterogeneous catalysts for the hydrogenation of quinizarins to leuco-quinizarins under neutral and continuous-flow conditions. Remarkably, bimetallic effects of Ni and Pt nanoparticle systems were highlighted in the selective hydrogenation of the substituted quinizarin. In addition, the continuous-flow synthesis of leuco-quinizarin and its derivatization reaction were integrated to be a fully continuous process using flow-batch-separator unified reactors.    

    

* Hexa-Fe(III) Carboxylate Complexes Facilitate Aerobic Hydrocarbon Oxidative Functionalization: Rh Catalyzed Oxidative Coupling of Benzene and Ethylene to Form Styrene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399938552
:TOPICS: Catalytic Oxidation of Alcohols, Transition-Metal-Catalyzed C–H Bond Functionalization, Dioxygen Activation at Metalloenzyme Active Sites
:PUBLICATION_DATE: 2024-06-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02355")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399938552"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399938552"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399938552"))][Get cited by]]

OpenAlex: https://openalex.org/W4399938552 (Open access: True)
    
[[https://openalex.org/A5056362371][Marc T. Bennett]], [[https://openalex.org/A5068505755][K. Park]], [[https://openalex.org/A5087057269][Charles B. Musgrave]], [[https://openalex.org/A5099431706][Jack W. Brubaker]], [[https://openalex.org/A5019581925][Diane A. Dickie]], [[https://openalex.org/A5035627473][William A. Goddard]], [[https://openalex.org/A5017765544][T. Brent Gunnoe]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02355 
     
No abstract    

    

* Synergy between Brønsted Acid Sites and Carbonaceous Deposits during Skeletal 1-Butene Isomerization over Ferrierite  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399970689
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-06-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01898")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399970689"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399970689"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399970689"))][Get cited by]]

OpenAlex: https://openalex.org/W4399970689 (Open access: True)
    
[[https://openalex.org/A5025006045][Karoline L. Hebisch]], [[https://openalex.org/A5038314713][Risha Goel]], [[https://openalex.org/A5059240584][Kinga Gołą̨bek]], [[https://openalex.org/A5093007599][Pawel A. Chmielniak]], [[https://openalex.org/A5088976109][Carsten Sievers]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01898 
     
No abstract    

    

* Micellar N-Heterocyclic Carbene-like Organic Catalysis from Polymeric Nanoreactors Immobilizing Benzimidazolium Acetate Motifs in Their Core  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399977853
:TOPICS: N-Heterocyclic Carbenes in Catalysis and Materials Chemistry, Transition Metal-Catalyzed Cross-Coupling Reactions, Microwave-Assisted Chemistry in Organic Synthesis
:PUBLICATION_DATE: 2024-06-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00259")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399977853"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399977853"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399977853"))][Get cited by]]

OpenAlex: https://openalex.org/W4399977853 (Open access: False)
    
[[https://openalex.org/A5003736750][Anne-Laure Wirotius]], [[https://openalex.org/A5058862047][Romain Lambert]], [[https://openalex.org/A5099437929][Thomas Dardé]], [[https://openalex.org/A5010776490][Simon Harrisson]], [[https://openalex.org/A5013580225][Daniel Taton]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00259 
     
No abstract    

    

* Efficient and Stable Production of Long-Chain Hydrocarbons over Hydrophobic Carbon-Encapsulated TiO2-Supported Ru Catalyst in Fischer–Tropsch Synthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400000990
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Desulfurization Technologies for Fuels, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02979")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400000990"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400000990"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400000990"))][Get cited by]]

OpenAlex: https://openalex.org/W4400000990 (Open access: False)
    
[[https://openalex.org/A5070071735][Yunhao Liu]], [[https://openalex.org/A5067943858][Xincheng Li]], [[https://openalex.org/A5068697796][Qingpeng Cheng]], [[https://openalex.org/A5054278618][Ye Tian]], [[https://openalex.org/A5034511665][Yingtian Zhang]], [[https://openalex.org/A5022960964][Tao Ding]], [[https://openalex.org/A5067783441][Song Song]], [[https://openalex.org/A5005078126][Kepeng Song]], [[https://openalex.org/A5014659532][Xingang Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02979 
     
No abstract    

    

* Alleviating Charge Recombination Caused by Unfavorable interaction of P and Sn in Hematite for Photoelectrochemical Water Oxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400001152
:TOPICS: Solar Water Splitting Technology, Photocatalytic Materials for Solar Energy Conversion, Acid Mine Drainage Remediation and Biogeochemistry
:PUBLICATION_DATE: 2024-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01150")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400001152"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400001152"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400001152"))][Get cited by]]

OpenAlex: https://openalex.org/W4400001152 (Open access: False)
    
[[https://openalex.org/A5064374729][Ji-Hun Kang]], [[https://openalex.org/A5029152694][Balaji G. Ghule]], [[https://openalex.org/A5099472105][Seung Gyu Gyeong]], [[https://openalex.org/A5021707167][Seong‐Ji Ha]], [[https://openalex.org/A5046112894][Ji‐Hyun Jang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01150 
     
No abstract    

    

* A Three-Dimensional Azo-Bridged Porous Porphyrin Framework Supported Silver Nanoparticles as the State-of-the-Art Catalyst for the Carboxylative Cyclization of Propargylic Alcohols with CO2 under Ambient Conditions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400002724
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02391")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400002724"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400002724"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400002724"))][Get cited by]]

OpenAlex: https://openalex.org/W4400002724 (Open access: False)
    
[[https://openalex.org/A5064527610][Yiying Yang]], [[https://openalex.org/A5053287022][Yingyin Li]], [[https://openalex.org/A5026623896][Yinghua Lu]], [[https://openalex.org/A5074754590][Zhiyuan Chen]], [[https://openalex.org/A5001319369][Rongchang Luo]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02391 
     
No abstract    

    

* Electrochemical NADH Regeneration Mediated by Pyridine Amidate Iridium Complexes Interconverting 1,4- and 1,6-NADH  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400007176
:TOPICS: Homogeneous Catalysis with Transition Metals, Fuel Cell Membrane Technology, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02548")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400007176"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400007176"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400007176"))][Get cited by]]

OpenAlex: https://openalex.org/W4400007176 (Open access: False)
    
[[https://openalex.org/A5043309794][Caterina Trotta]], [[https://openalex.org/A5052592745][Gabriel Menendez Rodriguez]], [[https://openalex.org/A5062509948][Cristiano Zuccaccia]], [[https://openalex.org/A5046771754][Alceo Macchioni]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02548 
     
No abstract    

    

* Enhancing CO2 Electroreduction Performance through Si-Doped CuO: Stabilization of Cu+/Cu0 Sites and Improved C2 Product Selectivity  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400010017
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400010017"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400010017"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400010017"))][Get cited by]]

OpenAlex: https://openalex.org/W4400010017 (Open access: False)
    
[[https://openalex.org/A5062964912][Long Cheng]], [[https://openalex.org/A5034037107][Rong Wang]], [[https://openalex.org/A5065039738][Wenzhe Si]], [[https://openalex.org/A5043647024][Yanxi Deng]], [[https://openalex.org/A5044717730][Junhua Li]], [[https://openalex.org/A5063483273][Yue Peng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01961 
     
No abstract    

    

* Mass-Transfer Enhancement in the CO2 Oxidative Dehydrogenation of Propane over GaN Supported on Zeolite Nanosheets with a Short b-Axis and Hierarchical Pores  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400019116
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02599")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400019116"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400019116"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400019116"))][Get cited by]]

OpenAlex: https://openalex.org/W4400019116 (Open access: False)
    
[[https://openalex.org/A5012021917][Zhan‐Jun Zhu]], [[https://openalex.org/A5090737269][Zhen‐Hong He]], [[https://openalex.org/A5080899164][Yajie Tian]], [[https://openalex.org/A5076886276][Sen-Wang Wang]], [[https://openalex.org/A5028746034][Yongchang Sun]], [[https://openalex.org/A5054296228][Kuan Wang]], [[https://openalex.org/A5040760076][Weitao Wang]], [[https://openalex.org/A5047819189][Zhifang Zhang]], [[https://openalex.org/A5044887427][Jiajie Liu]], [[https://openalex.org/A5027821063][Zhao‐Tie Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02599 
     
The CO2 oxidative dehydrogenation of propane (CO2–ODHP) is a highly important reaction for not only producing large amounts of propylene but also consuming the CO2 resource. GaN/zeolite catalysts deliver preferable activity in the reaction. However, similar to Pt- and Cr-based catalysts, there are shortcomings such as poor stability and coke accumulation, especially when operated at temperatures higher than 550 °C. Generally, carbon deposition is one of the main reasons for catalyst deactivation. The limited mass transfer greatly aggravates the deposited carbon formation, since carbon precursors could not be removed in time. In the present work, we modified zeolites with a short b-axis and hierarchical pores, which could offer a shorter diffusion distance and pore-rich structure to enhance the mass transfer. Thanks to this enhancement, the catalyst offers an initial propane conversion of 68.0% with a yield of 39.4% to propylene, surpassing other reported GaN/zeolite catalysts to data. Importantly, the catalyst showed a low loss rate of activity and a low amount of deposited carbon, which was easily regenerated compared with those of other catalysts without a short b-axis or hierarchical pores. Density functional theory (DFT) calculations and in situ diffuse reflectance infrared Fourier transform spectroscopy (DRIFTS) confirmed that the reaction involves a coupling reaction of direct dehydrogenation and CO2 reduction via reverse water–gas shift reaction, and CO2 participates in the reaction. The present work sheds light on designing an efficient catalyst for CO2–ODHP via a mass transfer-boosted strategy and, importantly, is expected to provide inspiration in constructing a zeolite with a short b-axis and hierarchical pores.    

    

* Substrate Turnover Dynamics Guide Ketol-Acid Reductoisomerase Redesign for Increased Specific Activity  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400026423
:TOPICS: Metabolic Engineering and Synthetic Biology, Enzyme Immobilization Techniques, Protein Structure Prediction and Analysis
:PUBLICATION_DATE: 2024-06-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01446")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400026423"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400026423"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400026423"))][Get cited by]]

OpenAlex: https://openalex.org/W4400026423 (Open access: False)
    
[[https://openalex.org/A5065083595][Elijah Karvelis]], [[https://openalex.org/A5011328944][Carl V. Swanson]], [[https://openalex.org/A5028186526][Bruce Tidor]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01446 
     
No abstract    

    

* Kinetics and Mechanism of Integrated Catalytic Ammonolysis and Dehydration from Methyl Salicylate over ZnAl2O4 Spinel  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400030614
:TOPICS: Catalytic Reduction of Nitro Compounds, Ammonia Synthesis and Electrocatalysis, Defect Identification using Positron Annihilation Spectroscopy
:PUBLICATION_DATE: 2024-06-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01477")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400030614"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400030614"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400030614"))][Get cited by]]

OpenAlex: https://openalex.org/W4400030614 (Open access: False)
    
[[https://openalex.org/A5084300114][Wei Yu]], [[https://openalex.org/A5010154255][Zhuo-Ling Xie]], [[https://openalex.org/A5003673833][Zhen Zeng]], [[https://openalex.org/A5004343457][Chengcheng Li]], [[https://openalex.org/A5019877215][J. M. An]], [[https://openalex.org/A5044551083][Qingqing Hao]], [[https://openalex.org/A5034953387][Huibin Ge]], [[https://openalex.org/A5086350588][Huiyong Chen]], [[https://openalex.org/A5046146875][Xiaoxun Ma]], [[https://openalex.org/A5086564001][Qun‐Xing Luo]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01477 
     
No abstract    

    

* A Direct Z-Scheme Single-Atom MOC/COF Piezo-Photocatalytic System for Overall Water Splitting  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400031336
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-06-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02243")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400031336"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400031336"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400031336"))][Get cited by]]

OpenAlex: https://openalex.org/W4400031336 (Open access: False)
    
[[https://openalex.org/A5085895064][Zizhan Liang]], [[https://openalex.org/A5049549324][Xinao Li]], [[https://openalex.org/A5045397113][Qing Chen]], [[https://openalex.org/A5048943029][Xiaotian Wang]], [[https://openalex.org/A5006308487][Peiyang Su]], [[https://openalex.org/A5071909292][Jianfeng Huang]], [[https://openalex.org/A5052814903][Yecheng Zhou]], [[https://openalex.org/A5069732463][Limin Xiao]], [[https://openalex.org/A5028810874][Jun‐Min Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02243 
     
No abstract    

    

* Efficient Electrochemical Nitrate Reduction to Ammonia Driven by a Few Nanometer-Confined Built-In Electric Field  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400037159
:TOPICS: Ammonia Synthesis and Electrocatalysis, Content-Centric Networking for Information Delivery, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02317")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400037159"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400037159"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400037159"))][Get cited by]]

OpenAlex: https://openalex.org/W4400037159 (Open access: False)
    
[[https://openalex.org/A5030451437][Maolin Zhang]], [[https://openalex.org/A5035786530][Zedong Zhang]], [[https://openalex.org/A5012852934][Shaolong Zhang]], [[https://openalex.org/A5014611868][Zechao Zhuang]], [[https://openalex.org/A5005078126][Kepeng Song]], [[https://openalex.org/A5099517570][Karthik Paramaiah]], [[https://openalex.org/A5039405568][Moyu Yi]], [[https://openalex.org/A5081967126][Hao Huang]], [[https://openalex.org/A5042841794][Dingsheng Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02317 
     
No abstract    

    

* How Luminescence Performances of Silicon-Doped Carbon Dots Contribute to Copper-Catalyzed photoATRP?  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400041360
:TOPICS: Synthesis and Applications of Carbon Quantum Dots, Aggregation-Induced Emission in Fluorescent Materials, Upconversion Nanoparticles
:PUBLICATION_DATE: 2024-06-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02203")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400041360"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400041360"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400041360"))][Get cited by]]

OpenAlex: https://openalex.org/W4400041360 (Open access: False)
    
[[https://openalex.org/A5026603299][Mengjie Zhou]], [[https://openalex.org/A5070794981][Su Xu]], [[https://openalex.org/A5053924384][Wenjie Zhang]], [[https://openalex.org/A5036151297][Ge Shi]], [[https://openalex.org/A5025782883][Yanjie He]], [[https://openalex.org/A5075007444][Xiaoguang Qiao]], [[https://openalex.org/A5036928991][Xinchang Pang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02203 
     
No abstract    

    

* Cine-Substitution of Enolates: Enolate Dance/Coupling of Cycloalkenyl Pivalates by Nickel Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400047375
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-06-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02707")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400047375"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400047375"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400047375"))][Get cited by]]

OpenAlex: https://openalex.org/W4400047375 (Open access: False)
    
[[https://openalex.org/A5096911248][Eito Moriya]], [[https://openalex.org/A5062322683][Kei Muto]], [[https://openalex.org/A5040867141][Junichiro Yamaguchi]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02707 
     
No abstract    

    

* CO2 Capture and Electrochemical Reduction of Low-Concentration CO2 Using a Re(I)-Complex Catalyst in Ethanol  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4400051414
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01120")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400051414"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400051414"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400051414"))][Get cited by]]

OpenAlex: https://openalex.org/W4400051414 (Open access: False)
    
[[https://openalex.org/A5081548063][Masahiko Miyaji]], [[https://openalex.org/A5085783586][Yusuke Tamaki]], [[https://openalex.org/A5052932251][Kei Kamogawa]], [[https://openalex.org/A5099524877][Yuto Abiru]], [[https://openalex.org/A5087548495][Manabu Abe]], [[https://openalex.org/A5070733375][Osamu Ishitani]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01120 
     
No abstract    

    
