#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Tue Feb 13 00:44:13 2024

Found 25 results from 2024-02-06 to 2024-02-13
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Photoelectrochemical Urea Synthesis from Nitrate and Carbon Dioxide on GaN Nanowires  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391543013
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04264")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391543013"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391543013"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391543013"))][Get cited by]]

OpenAlex: https://openalex.org/W4391543013 (Open access: False)
    
[[https://openalex.org/A5005809281][Wan Jae Dong]], [[https://openalex.org/A5005426309][Jan Paul Menzel]], [[https://openalex.org/A5037803284][Zhengwei Ye]], [[https://openalex.org/A5041280269][Ishtiaque Ahmed Navid]], [[https://openalex.org/A5047600031][Peng Zhou]], [[https://openalex.org/A5010438957][Ke Yang]], [[https://openalex.org/A5089129603][Víctor S. Batista]], [[https://openalex.org/A5070775523][Zetian Mi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04264 
     
Semiconductor photoelectrodes can be used to synthesize urea from carbon dioxide and nitrate under solar light. We find that GaN nanowires (NWs) have inherent catalytic activity for nitrate conversion to nitrite, while Ag cocatalysts loaded onto GaN NWs further promote the performance of photoelectrochemical urea synthesis. Under optimized conditions, a high faradaic efficiency of 75.6 ± 2.6% was achieved at a potential of −0.3 vs reversible hydrogen electrode. Control experiments and theoretical calculations suggest that the high selectivity of urea originates from the facilitated C–N coupling between key intermediates of NO2 and COO– at an early stage of the reduction reaction. This work demonstrates the potential of GaN NWs with loaded Ag cocatalysts to achieve solar-powered urea synthesis with an efficiency higher than that of previously reported methods.    

    

* 9-(4-Halo-2,6-xylyl)-10-methylacridinium Ion as an Effective Photoredox Catalyst for Oxygenation and Trifluoromethylation of Toluene Derivatives  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391558510
:TOPICS: Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Applications of Photoredox Catalysis in Organic Synthesis, Chemistry of Noble Gas Compounds and Interactions
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06111")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391558510"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391558510"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391558510"))][Get cited by]]

OpenAlex: https://openalex.org/W4391558510 (Open access: False)
    
[[https://openalex.org/A5084268749][Kei Ohkubo]], [[https://openalex.org/A5009596447][Sakiko Matsumoto]], [[https://openalex.org/A5010296653][Haruyasu Asahara]], [[https://openalex.org/A5066193981][Shunichi Fukuzumi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06111 
     
9-(2,6-Dimethylphenyl)-10-methylacridinium perchlorate ([Acr+–Xyl]ClO4–), 9-(4-chloro-2,6-dimethylphenyl)-10-methylacridinium perchlorate ([Acr+–XylCl]ClO4–), and 9-(4-fluoro-2,6-dimethylphenyl)-10-methylacridinium perchlorate ([Acr+–XylF]ClO4–) were synthesized by the Grignard reaction. The one-electron reduction potentials (Ered vs SCE) of Acr+–Xyl, Acr+–XylCl, and Acr+–XylF in deaerated acetonitrile (MeCN) were determined by cyclic voltammetry to be nearly the same as −0.55, −0.53, and −0.53 V, respectively. On the other hand, the one-electron oxidation potentials (Eox vs SCE) of Acr+–Xyl, Acr+–XylF, and Acr+–XylCl were determined by the second-harmonic alternative current voltammetric method to be +2.15, +2.20, and +2.21 V, respectively. The Eox value of Acr+–XylCl is higher than the Eox value of toluene (+2.20 V). Thus, photocatalytic oxygenation of toluene with oxygen occurs efficiently via electron transfer from toluene to the XylCl•+ moiety of the triplet electron-transfer state of Acr+–XylCl under photoirradiation of Acr+–XylCl in oxygen-saturated MeCN. By contrast, no oxygenation of toluene occurred with the 9-mesityl-10-methylacridinium ion (Acr+–Mes) used as a photocatalyst due to the lack of oxidizing ability to oxidize toluene. The metal-free trifluoromethylation of toluene derivatives has also been made possible by using Acr+–XylCl as a photocatalyst and S-(trifluoromethyl)dibenzothiophenium (CF3DBT+) as a trifluoromethyl source. The photocatalytic reaction mechanism was clarified by transient absorption and electrochemical measurements.    

    

* Organobismuth Compounds as Aryl Radical Precursors via Light-Driven Single-Electron Transfer  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391558560
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Catalytic Oxidation of Alcohols, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05598")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391558560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391558560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391558560"))][Get cited by]]

OpenAlex: https://openalex.org/W4391558560 (Open access: False)
    
[[https://openalex.org/A5062170356][Nicholas D. Chiappini]], [[https://openalex.org/A5089961340][Eric P. Geunes]], [[https://openalex.org/A5093868945][Ethan T. Bodak]], [[https://openalex.org/A5034006875][Robert R. Knowles]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05598 
     
A light-driven method for the generation of aryl radicals from triarylbismuth(III) and (V) reagents is described. Aryl radical generation is proposed to occur through the ligand-assisted mesolytic cleavage of an organobismuth(IV) intermediate generated from either oxidation of BiIII or reduction of BiV. This mode of aryl radical generation is demonstrated to be compatible with a range of bimolecular radical arylations, including hydroarylation of electron-deficient olefins and arylation of diboronates, disulfides, sulfonyl cyanides, phosphites, and isocyanides. The intermediacy of an aryl radical is supported by radical trapping and radical clock experiments, and BiIV–aryl mesolysis is supported computationally.    

    

* Chemoinformatic Catalyst Selection Methods for the Optimization of Copper–Bis(oxazoline)-Mediated, Asymmetric, Vinylogous Mukaiyama Aldol Reactions  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391559651
:TOPICS: Asymmetric Catalysis, Catalytic Oxidation of Alcohols, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05903")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391559651"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391559651"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391559651"))][Get cited by]]

OpenAlex: https://openalex.org/W4391559651 (Open access: False)
    
[[https://openalex.org/A5082818239][Casey L. Olen]], [[https://openalex.org/A5082026865][Andrew F. Zahrt]], [[https://openalex.org/A5061055809][Sean W. Reilly]], [[https://openalex.org/A5077988861][Danielle M. Schultz]], [[https://openalex.org/A5050525158][Khateeta M. Emerson]], [[https://openalex.org/A5040767670][David A. Candito]], [[https://openalex.org/A5058010200][Xiao Wang]], [[https://openalex.org/A5036948355][Neil A. Strotman]], [[https://openalex.org/A5060673018][Scott E. Denmark]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05903 
     
No abstract    

    

* Designing Highly Enantioselective Heterogeneous Pt Catalysts: Selective Exposure of Active Sites via Surface Modification Using Amines  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391574285
:TOPICS: Engineering of Surface Nanostructures, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00040")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391574285"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391574285"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391574285"))][Get cited by]]

OpenAlex: https://openalex.org/W4391574285 (Open access: False)
    
[[https://openalex.org/A5008737710][Byeongju Song]], [[https://openalex.org/A5070559681][Dongmin Lee]], [[https://openalex.org/A5044561633][Hyunjun Jeong]], [[https://openalex.org/A5042027893][Minji Yun]], [[https://openalex.org/A5050368068][Yongju Yun]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00040 
     
Surface modification of metal nanoparticles (NPs) with organic molecules has attracted considerable attention as an effective methodology for designing highly selective heterogeneous catalysts. In this paper, we propose a simple post-treatment strategy involving the mixing of bare Pt/Al2O3 with amines and subsequent heat treatment for preparing highly enantioselective heterogeneous catalysts for the hydrogenation of α-keto esters. Notably, treating the Pt catalyst with oleylamine (OAm) yielded a catalyst possessing considerably enhanced catalytic activity and enantioselectivity under various hydrogen pressure conditions. The OAm-treated Pt catalyst also showed high enantioselectivity over 10 consecutive cycles. Under the optimized reaction conditions, the OAm-treated Pt catalyst exhibited an enantiomeric excess (ee) of 95%, which was 15% higher than that of an unmodified Pt catalyst. Surface characterization revealed that the ratio of active sites exposed on the Pt surface can be controlled by varying the amount of the added OAm during the treatment. Specifically, the preferential passivation of under-coordinated sites of Pt NPs by the remaining OAm residues after heat treatment increased the ratio of exposed well-coordinated Pt sites, which are suitable for the stable adsorption of a chiral modifier (cinchonidine). Quantitative site fraction analysis using infrared spectroscopic studies revealed a positive linear correlation between the ee and the ratio of exposed terrace Pt sites, confirming the promoting effect of the OAm treatment on enantioselectivity. Moreover, the versatility of this strategy was demonstrated for the Pt catalysts treated with a variety of amines in enantioselective hydrogenation. These findings provide a direction for regulating the selective exposure of specific active sites using simple surface treatment to develop highly efficient heterogeneous catalysts.    

    

* Selective Oxidation of Hydrocarbons by Molecular Iron Catalysts Based on Molecular Recognition through π–π Interaction in Aqueous Medium  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391574892
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Platinum-Based Cancer Chemotherapy
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05118")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391574892"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391574892"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391574892"))][Get cited by]]

OpenAlex: https://openalex.org/W4391574892 (Open access: False)
    
[[https://openalex.org/A5032294525][Hiroto Fujisaki]], [[https://openalex.org/A5010354588][Tomoya Ishizuka]], [[https://openalex.org/A5010888790][Hiroaki Kotani]], [[https://openalex.org/A5044357340][Takahiko Kojima]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05118 
     
Oxidation enzymes possess finely organized structures to recognize specific substrates, leading to the efficient catalysis of selective oxidation reactions to generate the desired products. Inspired by such enzymes, molecular catalysts with substrate-recognition sites have been developed for decades. Here, we report the highly selective oxidation of aromatic substrates in aqueous media by catalysis with an FeII complex featuring a hydrophobic second coordination sphere (SCS) constructed by four anthracenyl groups. The FeII catalyst showed a much higher turnover frequency for the benzene-to-phenol oxidation (1.0 × 104 h–1) than for the cyclohexane-to-cyclohexanol oxidation (12 h–1). The SCS of the FeII complex works as a trapping site of aromatic substrates through π–π interaction and assists the release of the hydrophilic oxidized products to the aqueous media. A “recognition-and-release” approach also allowed the selective formation of anthracen-9-ol and 1-naphthol by direct oxidation of anthracene and naphthalene, respectively.    

    

* Mechanistic Study of Electrocatalytic Perchlorate Reduction using an Oxorhenium Complex Supported on a Ti4O7 Support  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391574966
:TOPICS: Perchlorate Contamination and Health Effects, Electrochemical Detection of Heavy Metal Ions, Battery Recycling and Rare Earth Recovery
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05680")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391574966"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391574966"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391574966"))][Get cited by]]

OpenAlex: https://openalex.org/W4391574966 (Open access: False)
    
[[https://openalex.org/A5013585682][Soroush Almassi]], [[https://openalex.org/A5049156632][Changxu Ren]], [[https://openalex.org/A5043270824][Naveen Dandu]], [[https://openalex.org/A5038104182][Anh T. Ngo]], [[https://openalex.org/A5037074212][Jinyong Liu]], [[https://openalex.org/A5074898160][Brian P. Chaplin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05680 
     
Developing a stable and active catalyst for ClO4– reduction at nonacidic pH has presented a significant challenge to the catalysis field. Previous research has demonstrated that by depositing an organometallic Re catalyst onto a Ti4O7 support (Re/Ti4O7), it was possible to stabilize the catalyst and obtain active electrocatalytic ClO4– reduction at circumneutral pH. Thus, the focus of this work was on elucidating the mechanisms of electrocatalytic ClO4– reduction in water with the Re/Ti4O7 system. Density functional theory (DFT) simulations indicated that the adsorption of the Re catalyst was exothermic on Ti4O7, and X-ray photoelectron spectroscopy (XPS) characterization indicated that Re adsorption caused a net reduction of the Ti oxidation state on the Ti4O7 surface. After ClO4– reduction experiments, XPS results indicated the presence of Ti(0)/Ti(II) surface sites. Cyclic voltammetry experiments in an acetonitrile solvent provided supporting evidence that these surface sites were electroactive and likely participated in the ClO4– reduction reaction. Analysis of batch reduction experiments in acetonitrile via kinetic modeling estimated a catalyst turnover number of 332 ± 23, which provided further evidence that the reduced Ti sites could regenerate the Re catalyst. However, these reduced Ti sites were finite in number and required the production of adsorbed hydrogen via water reduction to facilitate continuous ClO4– reduction. DFT results indicated that the reduction of ClO4– to Cl– was exothermic and that reduced Ti sites participated in the reduction reaction. The experimental and DFT results allowed a preliminary mechanism for ClO4– reduction on Re/Ti4O7 to be proposed.    

    

* Red-Light-Based Effective Photocatalysis of a Photosensitive Covalent Organic Framework Triggered Singlet Oxygen  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391576893
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Photocatalytic Materials for Solar Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05454")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391576893"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391576893"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391576893"))][Get cited by]]

OpenAlex: https://openalex.org/W4391576893 (Open access: False)
    
[[https://openalex.org/A5019310869][Kaijun Niu]], [[https://openalex.org/A5024278129][Tian‐Xiang Luan]], [[https://openalex.org/A5040232281][Jing Chen]], [[https://openalex.org/A5044301848][Hui Liu]], [[https://openalex.org/A5011669276][Ling‐Bao Xing]], [[https://openalex.org/A5056554030][Pei‐Zhou Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05454 
     
The direct application of low-energy red light for photochemical transformations is synthetically appealing but practically challenging. Covalent organic frameworks (COFs) exhibit significant potential within this domain, owing to their broad spectrum of absorption and their prevalence in photochemical reactions, despite the fact that these photocatalysts are now mainly focused on using ultraviolet (UV) and blue light. In this study, an imidazole-linked porphyrin-based COF, PyPor-COF, which exhibits a wide absorption band ranging from 200 to 700 nm, especially strong red light absorption from 630 to 700 nm, is expected to be applied in red light photocatalytic reactions. PyPor-COF possesses the capacity to selectively generate singlet oxygen (1O2) with a high efficiency, which renders it an efficient photosensitizer for photocatalytic reactions of olefin cleavages and thioanisole photooxidation under red light. The present study demonstrates the intriguing prospect of photoactive COFs with red light absorption as a type II photosensitizer with high potential for utilization in red light photocatalyses.    

    

* Mechanochemical Coupling of Catalysis and Motion in a Cellulose-Degrading Multienzyme Nanomachine  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391578933
:TOPICS: Nanocellulose: Properties, Production, and Applications, Mesoporous Materials, Liquid Crystal Research
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05653")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391578933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391578933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391578933"))][Get cited by]]

OpenAlex: https://openalex.org/W4391578933 (Open access: True)
    
[[https://openalex.org/A5006514846][Krisztina Zajki-Zechmeister]], [[https://openalex.org/A5083353886][Manuel Eibinger]], [[https://openalex.org/A5004942064][Gaurav Singh Kaira]], [[https://openalex.org/A5051203357][Bernd Nidetzky]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05653  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05653][pdf]])
     
The cellulosome is a megadalton-size protein complex that functions as a biological nanomachine of cellulosic fiber degradation. We show that the cellulosome behaves as a Brownian ratchet that rectifies protein motions on the cellulose surface into a propulsion mechanism by coupling to the hydrolysis of cellulose chains. Movement on cellulose fibrils is unidirectional and results from “macromolecular crawl” composed of dynamic switches between elongated and compact spatial arrangements of enzyme subunits. Deletion of the main exocellulase Cel48S eliminates conformational bias for aligning the subunits to the long fibril axis, which we reveal as crucial for optimum coupling between directional movement and substrate degradation. Implications of the cellulosome acting as a mechanochemical motor suggest a distinct mechanism of enzymatic machinery in the deconstruction of cellulose assemblies.    

    

* Mechanism and Kinetics of Propane and n-Butane Dehydrogenation over Isolated and Nested ≡SiOZn–OH Sites Grafted onto Silanol Nests of Dealuminated Beta Zeolite  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391593970
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Zeolite Chemistry and Catalysis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05605")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391593970"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391593970"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391593970"))][Get cited by]]

OpenAlex: https://openalex.org/W4391593970 (Open access: False)
    
[[https://openalex.org/A5054856418][Y. Zhang]], [[https://openalex.org/A5071668095][Liang Qi]], [[https://openalex.org/A5000365597][Danna Nozik]], [[https://openalex.org/A5062045086][Chaochao Dun]], [[https://openalex.org/A5007458786][Jeffrey J. Urban]], [[https://openalex.org/A5087957929][Alexis T. Bell]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05605 
     
No abstract    

    

* Theoretical Study on Bismuth(III) Catalysts for Synthesis of Phenylsulfonyl Fluoride: Reasons of Their Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391594799
:TOPICS: Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Innovations in Organic Synthesis Reactions, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04874")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391594799"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391594799"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391594799"))][Get cited by]]

OpenAlex: https://openalex.org/W4391594799 (Open access: False)
    
[[https://openalex.org/A5071468873][Yu Tian]], [[https://openalex.org/A5003405142][Shigeyoshi Sakaki]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04874 
     
Bismuth(III) complex with diarylsulfone ligand (diAr-SO2) is a non-transition metal catalyst reported recently for the synthesis of arylsulfonyl fluorides. We investigated this catalytic reaction using DFT and SCS-MP2 calculations for geometries and energies, respectively. This catalytic reaction occurs through transmetalation between (BF4)Bi(diAr-SO2) and phenylboronic acid (PhB(OH)2), SO2 insertion into the Bi–Ph bond of (Ph)Bi(diAr-SO2), and fluorination of the PhOSO group of (PhOSO)Bi(diAr-SO2) by Selectfluor. The rate-determining step is the transmetalation for diAr-SO2 with (CH3, CH3) and (CF3, CF3) but either the transmetalation or fluorination for diAr-SO2 with (CH3, CF3), where (R1, R2) means diAr-SO2 has R1 and R2 substituents on its aryl groups. The activation energy (ΔG°‡) of the rate-determining step increases in the order (CH3, CF3) < (CH3, CH3) < (CF3, CF3). This increasing order is consistent with the experimentally observed substituent effects on catalytic activity. The transmetalation is difficult to occur in the absence of potassium phosphate (K3PO4) but occurs with moderate activation energy in the presence of K3PO4 because K3PO4 activates the B–Ph σ-bond of phenylboronic acid and stabilizes the dissociating B(OH)2 moiety through electrostatic interaction. The substituents on diAr-SO2 play an important role in the transmetalation; when diAr-SO2 has (CF3, CF3), K3PO4 strongly interacts with the Bi(diAr-SO2) species to form an overly stable adduct to enlarge considerably the ΔG°‡ value. When diAr-SO2 has either (CH3, CF3) or (CH3, CH3), the stabilization energy of the adduct is similar to each other, but the energy destabilization occurs more largely upon going to the asymmetric transition state from the adduct in the (CH3, CH3) case than in the (CH3, CF3) case. Thus, the use of diAr-SO2 with (CH3, CF3) is favorable for the transmetalation. The SO2 insertion into the Bi–Ph bond of (Ph)Bi(diAr-SO2) occurs with a moderate ΔG°‡ value, whereas the SO2 insertion is difficult to occur when the sulfone (SO2) group of diAr-SO2 is replaced with a CH2 group. The SO2 insertion occurs via a nucleophilic attack of the Ph group to SO2. However, (Ph)Bi(diAr-SO2) with (CH3, CH3) is not the most reactive because not only the HOMO energy of (Ph)Bi(diAr-SO2) but also factors such as the Biδ+–(C6H3R)δ− (R = CH3 or CF3) bond dipole moment and the Bi–C6H3R bond strength participate in determining the reactivity of (Ph)Bi(diAr-SO2) for the SO2 insertion where C6H3R is the aryl part of diArSO2. The fluorination occurs with a moderate ΔG°‡ value and an extremely negative ΔG° value. Its ΔG°‡ value hardly depends on the substituents of diAr-SO2. The presence of K3PO4 and the use of diAr-SO2 ligand with (CH3, CF3) are key for the catalytic activity of the bismuth catalyst.    

    

* Visible-Light Photocatalytic H2O2 Production Boosted by Frustrated Lewis Pairs in Defected Polymeric Carbon Nitride Nanosheets  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391594826
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Aggregation-Induced Emission in Fluorescent Materials
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05360")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391594826"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391594826"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391594826"))][Get cited by]]

OpenAlex: https://openalex.org/W4391594826 (Open access: False)
    
[[https://openalex.org/A5078796092][Lixia Ma]], [[https://openalex.org/A5035062124][Yaping Gao]], [[https://openalex.org/A5063236179][Baoqiang Wei]], [[https://openalex.org/A5043882558][Luo Huang]], [[https://openalex.org/A5037214616][Nan Zhang]], [[https://openalex.org/A5003131258][Qiang Weng]], [[https://openalex.org/A5044757881][Lu Zhang]], [[https://openalex.org/A5091362073][Shengzhong Liu]], [[https://openalex.org/A5056918742][Ruibin Jiang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05360 
     
Frustrated Lewis pairs (FLPs) with a unique “push–pull” effect can effectively activate many types of molecules to obtain unanticipated catalytic activity. Herein, FLPs are introduced into polymeric carbon nitride (CN), and their functions in the photocatalytic synthesis of H2O2 are studied. The FLPs in B-doped CN (BCN) are constituted by electron-deficient boron as Lewis acid sites and nitrogen neighbored with cyano groups as Lewis base sites. The formation of FLPs can improve the light absorption ability and the separation of photogenerated carriers. The FLPs afford strong adsorption of O2, but cannot produce H2O2 directly because the strong activation of oxygen bonds leads to oxygen bond scission during reduction. The FLPs enhance H2O2 production through the effective activation of ethanol (ETOH) by the “push–pull” effect of FLPs. The reduction of O2 to H2O2 is found through •O2– and 1O2 species. The photocatalytic H2O2 production rate on BCN can reach 51,008 μM g–1 h–1, which is over 12 times that of pristine CN (4113 μM g–1 h–1). This study not only provides an effective approach for enhancing photocatalytic H2O2 production but also deepens the understanding of the role of FLPs in molecule activation.    

    

* From CO2 to Methanol on Cu/ZnO/Al2O3 Industrial Catalyst. What Do We Know about the Active Phase and the Reaction Mechanism?  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391600545
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05669")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391600545"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391600545"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391600545"))][Get cited by]]

OpenAlex: https://openalex.org/W4391600545 (Open access: False)
    
[[https://openalex.org/A5018929838][Gianfranco Pacchioni]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05669 
     
No abstract    

    

* Promotion Effect of Pd in the Ru/C-Catalyzed Hydrogenation of Benzofurans  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391602174
:TOPICS: Homogeneous Catalysis with Transition Metals, Catalytic Reduction of Nitro Compounds, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05429")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391602174"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391602174"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391602174"))][Get cited by]]

OpenAlex: https://openalex.org/W4391602174 (Open access: False)
    
[[https://openalex.org/A5020011033][Miao Guo]], [[https://openalex.org/A5020370082][Huicong Dai]], [[https://openalex.org/A5004719521][Qihua Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05429 
     
No abstract    

    

* FAIR Data and Software: Improving Efficiency and Quality of Biocatalytic Science  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391603087
:TOPICS: Management and Reproducibility of Scientific Workflows, Data Sharing and Stewardship in Science, Biomedical Ontologies and Text Mining
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06337")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391603087"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391603087"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391603087"))][Get cited by]]

OpenAlex: https://openalex.org/W4391603087 (Open access: False)
    
[[https://openalex.org/A5067406221][Jürgen Pleiss]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06337 
     
Biocatalysis is entering a promising era as a data-driven science. High-throughput experimentation generates a rapidly increasing stream of biocatalytic data, which is the raw material for mechanistic and data-driven modeling to design improved biocatalysts and bioprocesses. However, our laboratory routines and our scientific practice of communicating scientific results are insufficient to ensure the reproducibility and scalability of experiments, and data management has become a bottleneck to progress in biocatalysis. In order to take full advantage of rapid progress in experimental and computational technologies, biocatalytic data should be findable, accessible, interoperable, and reusable (FAIR). FAIRification of data and software is achieved by developing standardized data exchange formats and ontologies, by electronic lab notebooks for data acquisition and documentation of experimentation, collaborative platforms for developing software and analyzing data, and repositories for publishing results together with raw data. The EnzymeML platform provides reusable and extensible tools and formats for FAIR and scalable data management in biocatalysis. FAIRification of data and software and the digitalization of biocatalysis are expected to improve the efficiency of research by automation and to guarantee the quality of biocatalytic science by reproducibility. Most of all, they foster reasoning and creating hypotheses by enabling the reanalysis of previously published data, and thus promote disruptive research and innovation.    

    

* Shield Machine-like Substrate Walking Strategy-Based Pocket Engineering of F-Amine Dehydrogenase for Accessing Structurally Diverse Fused-Ring and Linked-Ring Aryl Ketones  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391612989
:TOPICS: Nucleotide Metabolism and Enzyme Regulation, Enzyme Immobilization Techniques, Amino Acid Transport and Metabolism in Health and Disease
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00068")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391612989"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391612989"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391612989"))][Get cited by]]

OpenAlex: https://openalex.org/W4391612989 (Open access: False)
    
[[https://openalex.org/A5018736180][Tao Wu]], [[https://openalex.org/A5034094966][Yan Xu]], [[https://openalex.org/A5087324294][Yao Nie]], [[https://openalex.org/A5062611477][Xiaoqing Mu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00068 
     
Although amine dehydrogenases (AmDHs) are emerging as attractive biocatalysts for chiral amine synthesis, their synthetic application in structurally diverse arylamines remains challenging, given the limited substrate acceptance. Substrate walking is an effective coevolution strategy to confer targeted substrate acceptance to an enzyme through a stepwise mutagenesis landscape adaptation. Here, based on the conventional substrate walking strategy, we report a shield machine-like substrate walking strategy to quickly evolve F-BbAmDH from Bacillus badius for accessing the difficult-to-aminate fused-ring and linked-ring aryl ketones. A set of monoring aryl ketone homologues with the benzene ring located at the end of the side-chain and regularly extended carbon skeletons was rationally selected as the transition substrates. A superior mutant library with expanded target fused-ring and linked-ring aryl ketone acceptance was identified based on the activity and specificity enhancement of the transition substrates, enabling the synthesis of pharmaceuticals and bioactive compound-related arylamines with up to 94% yield and 99% ee (R) or 99:1 cis/trans. Structure-based computational results provided molecular insights into the source of the expanded substrate acceptance. Our work demonstrates a concise engineering workflow for the collective acceptance evolution of enzymes for structurally diverse substrate panels and has promising prospects in enzyme engineering.    

    

* First-Principles-Based Kinetic Monte Carlo Model of Hydrogen Evolution Reaction under Realistic Conditions: Solvent, Hydrogen Coverage and Electric Field Effects  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391614041
:TOPICS: Electrocatalysis for Energy Conversion, Advancements in Density Functional Theory, Quantum Coherence in Photosynthesis and Aqueous Systems
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04588")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391614041"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391614041"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391614041"))][Get cited by]]

OpenAlex: https://openalex.org/W4391614041 (Open access: False)
    
[[https://openalex.org/A5070169953][Yuhong Luo]], [[https://openalex.org/A5035781997][Yani Guan]], [[https://openalex.org/A5013752220][Guihua Liu]], [[https://openalex.org/A5007948614][Yanji Wang]], [[https://openalex.org/A5083687798][Jingde Li]], [[https://openalex.org/A5043725286][Luis Ricardez–Sandoval]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04588 
     
The hydrogen evolution reaction (HER) plays an important role in electrocatalytic water splitting. Despite the progress on the development of HER catalysts, the dynamic evolution of HER reaction under realistic electrochemical conditions considering the electric field, solvent, and hydrogen coverage effects is still unclear. In this study, a first-principles-based H surface coverage and potential-dependent kinetic Monte Carlo (KMC) HER model on the Pt (111)/Pt (100) surface is presented. The reaction kinetics and electronic structure analysis of HER on Pt surfaces in the presence of dihydrated proton (H5O2+) and H surface coverage is investigated using density functional theory (DFT). The HER KMC model was developed based on the DFT-calculated energetics. The KMC simulation results showed that consideration of H5O2+ species and dynamic evolution of H coverage is essential for accurate description of HER reaction on the Pt catalyst, which fits well with HER polarization data. Moreover, sensitivity analysis shows that HER on Pt (111) is mainly affected by the Tafel step. On the Pt(100) surface, HER is primarily governed by the Heyrovsky pathway. Surface species evolution analysis demonstrates that the high working potential accelerated the formation of [Pt-2H] species, leading to increased H coverage and accelerating the HER process. The predicted weakened H binding strength and increased H coverage at high HER working potential was verified by in situ attenuated total reflection Fourier transformed infrared spectroscopy analysis. Overall, the proposed DFT-KMC model represents the state-of-art dynamic simulation of catalytic HER reaction, providing important insights into the evolution of HER under realistic operation conditions.    

    

* Copper-Catalyzed Asymmetric Yne-Allylic Substitution Using Electron-Rich Arenes  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391616495
:TOPICS: Gold Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06146")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391616495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391616495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391616495"))][Get cited by]]

OpenAlex: https://openalex.org/W4391616495 (Open access: False)
    
[[https://openalex.org/A5027501129][Defu Luo]], [[https://openalex.org/A5041089138][Shengtong Niu]], [[https://openalex.org/A5056420587][Fan Gong]], [[https://openalex.org/A5006348865][Chao Xu]], [[https://openalex.org/A5017215755][Shouang Lan]], [[https://openalex.org/A5028923357][Jinggong Liu]], [[https://openalex.org/A5071468018][Shuang Yang]], [[https://openalex.org/A5017247181][Xinqiang Fang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06146 
     
Remote stereocontrol in transition-metal catalysis is a challenging but interesting research topic. In this work, we achieved copper-catalyzed asymmetric yne-allylic substitution using electron-rich arenes and acyclic carbonates through remote enantioselectivity control. The reaction delivers a variety of enantioenriched products that contain a diverse set of valuable moieties, such as conjugated enynes, indoles, indolizines, allenes, and dihydrofurans, which are widely used in organic synthesis and act as key units in bioactive molecules and natural products. The synthetic value of this protocol has been demonstrated in a series of further transformations, and mechanistic studies have been conducted to gain more insight into the reaction.    

    

* Selecting between Ammonia and Water Oxidation: Electrochemical Oxidation of Ammonia in Water Using an Organometallic–Inorganic Hybrid Anode  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391637546
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Novel Methods for Cesium Removal from Wastewater
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05899")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391637546"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391637546"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391637546"))][Get cited by]]

OpenAlex: https://openalex.org/W4391637546 (Open access: False)
    
[[https://openalex.org/A5085101592][Han-Yu Liu]], [[https://openalex.org/A5092900821][Josephine A. Jayworth]], [[https://openalex.org/A5032962378][Robert H. Crabtree]], [[https://openalex.org/A5064040856][Gary W. Brudvig]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05899 
     
Electrocatalytic ammonia oxidation (AO) under ambient conditions in an aqueous solvent enables an ecofriendly production of nitrite and nitrate. Conventional formation of nitrite and nitrate by AO on noble metals often yields undesired dinitrogen and leads to detrimental nitride surface poisoning. We now find that our previously reported “Blue Layer” (BL), an organometallic–inorganic hybrid anode based on [IrO2]x nanoclusters (x ∼ 5), is active for selective AO in aqueous solution. Through adjustment of both pH and applied potential (Eapp), we identified optimal operating conditions (pH 8.0, 1.00 V) for AO, where BL achieves optimum selectivity toward nitrate (90.5%), effectively minimizing competitive water oxidation while maintaining activity against ammonia-induced degradation of the electrode.    

    

* Unveiling the Structure–Property Relationship of MgO-Supported Ni Ammonia Decomposition Catalysts from Bulk to Atomic Structure by In Situ/Operando Studies  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391642373
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Nanomaterials, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05629")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391642373"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391642373"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391642373"))][Get cited by]]

OpenAlex: https://openalex.org/W4391642373 (Open access: True)
    
[[https://openalex.org/A5066808865][T. H. Ulucan]], [[https://openalex.org/A5063689857][Jihao Wang]], [[https://openalex.org/A5025489001][E Onur]], [[https://openalex.org/A5022896242][Shilong Chen]], [[https://openalex.org/A5000126422][Malte Behrens]], [[https://openalex.org/A5076366179][Claudia Weidenthaler]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05629  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05629][pdf]])
     
Ammonia is currently being studied intensively as a hydrogen carrier in the context of the energy transition. The endothermic decomposition reaction requires the use of suitable catalysts. In this study, transition metal Ni on MgO as a support is investigated with respect to its catalytic properties. The synthesis method and the type of activation process contribute significantly to the catalytic properties. Both methods, coprecipitation (CP) and wet impregnation (WI), lead to the formation of Mg1–xNixO solid solutions as catalyst precursors. X-ray absorption studies reveal that CP leads to a more homogeneous distribution of Ni2+ cations in the solid solution, which is advantageous for a homogeneous distribution of active Ni catalysts on the MgO support. Activation in hydrogen at 900 °C reduces nickel, which migrates to the support surface and forms metal nanoparticles between 6 nm (CP) and 9 nm (WI), as shown by ex situ STEM. Due to the homogeneously distributed Ni2+ cations in the solid solution structure, CP samples are more difficult to activate and require harsher conditions to reduce the Ni. The combination of in situ X-ray diffraction (XRD) and operando total scattering experiments allows a structure–property investigation of the bulk down to the atomic level during the catalytic reaction. Activation in H2 at 900 °C for 2 h leads to the formation of large Ni particles (20–30 nm) for the samples synthesized by the WI method, whereas Ni stays significantly smaller for the CP samples (10–20 nm). Sintering has a negative influence on the catalytic conversion of the WI samples, which is significantly lower compared to the conversion observed for the CP samples. Interestingly, metallic Ni redisperses during cooling and becomes invisible for conventional XRD but can still be detected by total scattering methods. The conditions of activation in NH3 at 650 °C are not suitable to form enough reduced Ni nanoparticles from the solid solution and are, therefore, not a suitable activation procedure. The activity steadily increases in the samples activated at 650 °C in NH3 (Group 1) compared to the samples activated at 650 °C in H2 and then reaches the best activity in the samples activated at 900 °C in H2. Only the combination of complementary in situ and ex situ characterization methods provides enough information to identify important structure–property relationships among these promising ammonia decomposition catalysts.    

    

* Stereoselective gem-Difunctionalization of Diazo Compounds with Vinyl Sulfoxonium Ylides and Thiols via Metalloradical Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391653535
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06098")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391653535"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391653535"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391653535"))][Get cited by]]

OpenAlex: https://openalex.org/W4391653535 (Open access: False)
    
[[https://openalex.org/A5068051558][Srashti Bhardwaj]], [[https://openalex.org/A5014736511][Dinesh Kumar Gopalakrishnan]], [[https://openalex.org/A5092908924][Shalu Deshwal]], [[https://openalex.org/A5062504886][Raju Sen]], [[https://openalex.org/A5058101968][Vikas Tiwari]], [[https://openalex.org/A5052249622][Tarak Karmakar]], [[https://openalex.org/A5069454776][Janakiram Vaitla]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06098 
     
Multicomponent reactions that involve carbenes with nucleophiles and electrophiles have demonstrated broad applications in synthetic chemistry. However, because of the high reactivity of transient carbenes, reactions involving two carbene precursors with the nucleophile in the presence of a metal catalyst remain unexplored. Herein, a three-component stereoselective gem-difunctionalization of diazo compounds with thiols and vinyl sulfoxonium ylide is disclosed via Co(II)-based metalloradical catalysis. The key aspect of the present strategy is to exploit the intrinsic difference in the reactivity of vinyl sulfoxonium ylides and diazo compounds with thiol and metal catalysts. The present Doyle–Kirmse rearrangement of a sulfonium ylide involves a convergent assembly of two in situ-generated intermediates, such as allyl sulfide and α- metalloalkyl radical complex, to provide expeditious access to tertiary sulfide scaffolds. Combined experimental and quantum chemical calculations unveil the intricate mechanism of this three-component reaction. Furthermore, theoretical studies on noncovalent interactions of selectivity-determining transition states explain the origin of the experimentally obtained diastereoselectivity.    

    

* Amorphous Cu–W Alloys as Stable and Efficient Electrocatalysts for Hydrogen Evolution  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391656368
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05820")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391656368"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391656368"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391656368"))][Get cited by]]

OpenAlex: https://openalex.org/W4391656368 (Open access: False)
    
[[https://openalex.org/A5022529391][Xiying Jian]], [[https://openalex.org/A5005798301][Wenbiao Zhang]], [[https://openalex.org/A5088190932][Yaxiong Yang]], [[https://openalex.org/A5030336185][Zhenglong Li]], [[https://openalex.org/A5053786338][Hongge Pan]], [[https://openalex.org/A5044287015][Qingsheng Gao]], [[https://openalex.org/A5090512624][Huaijun Lin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05820 
     
Cu and W are completely immiscible in equilibrium conditions, and neither of them is a good catalytic element for the electrochemical hydrogen evolution reaction (HER) due to their hydrogen adsorption Gibbs free energy (ΔGH) being too positive or negative, respectively. However, the combination of Cu with W could potentially result in a moderate ΔGH. In this study, a series of binary amorphous Cu–W alloys are fabricated via a magnetron sputtering method. The optimal HER catalytic performance is demonstrated when the nominal component is Cu50W50, showing an overpotential of only 65 mV at 10 mA cm–2 in 1 M KOH. Accordingly, density functional theory calculations show that the amorphous Cu50W50 alloy has a close-to-zero ΔGH compared to the pure Cu and W metals, accounting for its HER activity. In addition, the amorphous Cu50W50 alloy shows no obvious degradation at 100 mA cm–2 for 200 h, highlighting its long-term durability. This work provides a versatile strategy for the preparation of amorphous alloys with completely immiscible components and insights into the compositional design of nonprecious metal electrocatalysts for widespread applications.    

    

* Toward High CO Selectivity and Oxidation Resistance Solid Oxide Electrolysis Cell with High-Entropy Alloy  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391679800
:TOPICS: Solid Oxide Fuel Cells, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05972")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391679800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391679800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391679800"))][Get cited by]]

OpenAlex: https://openalex.org/W4391679800 (Open access: False)
    
[[https://openalex.org/A5024280063][Jun Tang]], [[https://openalex.org/A5075626239][Na Ni]], [[https://openalex.org/A5010878103][Baowen Zhou]], [[https://openalex.org/A5015927446][Chen Yang]], [[https://openalex.org/A5041129333][Kolan Madhav Reddy]], [[https://openalex.org/A5012980325][Heng Tu]], [[https://openalex.org/A5002038517][Yu-Si Liu]], [[https://openalex.org/A5057876953][Zhe Tan]], [[https://openalex.org/A5030172940][Longkai Xiang]], [[https://openalex.org/A5015353382][Haozhen Li]], [[https://openalex.org/A5050803462][Xing Zhang]], [[https://openalex.org/A5086509214][Yunyi Zhang]], [[https://openalex.org/A5089669072][Yixin Li]], [[https://openalex.org/A5064982569][Hanchao Zhang]], [[https://openalex.org/A5050980529][Lei Zhu]], [[https://openalex.org/A5087875241][Zhen Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05972 
     
Ni-based cermet materials still persist as pronounced challenges for electrocatalysts in solid oxide electrolysis cells (SOECs), due to their insufficient CO2 catalytic efficiency and inferior resistance to oxidation. In this paper, a (Fe,Co,Ni,Cu,Mo) quinary high-entropy alloy is explored as an alternative cathode material, offering enhanced performance in the co-electrolysis of H2O and CO2 for renewable syngas production. In comparison to traditional nickel-based cathodes, an assembled SOEC employing the as-designed quinary high-entropy alloy exhibits a remarkable increase in CO2 conversion capacity and significantly enhanced oxidation resistance. In addition, the electrolysis current density increases by 18%, and a stability test for more than 110 h reveals no degradation. Moreover, the stability can be maintained for up to 40 h even without any protective gas. Morphological and spectroscopic analyses, coupled with density functional theory (DFT) calculations, elucidate that the high-entropy effect facilitates surface electron redistribution, which in turn contributes to the measurable activity by reducing the energy barrier of CO2 activation. Notably, the superior resistance to oxidation primarily originates from the in situ-formed spinel phase under oxidation conditions. This study demonstrates the satisfying performance of high-entropy alloys as cathode materials in SOEC, validating their high application potential in this field.    

    

* Dehydrogenation and Transfer Hydrogenation of Alkenones to Phenols and Ketones on Carbon-Supported Noble Metals  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391681918
:TOPICS: Homogeneous Catalysis with Transition Metals, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04849")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391681918"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391681918"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391681918"))][Get cited by]]

OpenAlex: https://openalex.org/W4391681918 (Open access: True)
    
[[https://openalex.org/A5010415616][Katja Li]], [[https://openalex.org/A5065641804][H. Ray Kelly]], [[https://openalex.org/A5080850986][José Armando L. da Silva]], [[https://openalex.org/A5089129603][Víctor S. Batista]], [[https://openalex.org/A5047406603][Eszter Baráth]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04849  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c04849][pdf]])
     
The catalytic dehydrogenation of substituted alkenones on noble metal catalysts supported on carbon (Pt/C, Pd/C, Rh/C, and Ru/C) was investigated in an organic phase under inert conditions. The dehydrogenation and semihydrogenation of the enone starting materials resulted in aromatic compounds (primary products), saturated cyclic ketones (secondary products), and cyclic alcohols (minor products). Pd/C exhibits the highest catalytic activity, followed by Pt/C and Rh/C. Aromatic compounds remain the primary products, even in the presence of hydrogen donors. Joint experimental and theoretical analyses showed that the four catalytic materials stabilize a common dienol intermediate on the metal surfaces, formed by keto–enol tautomerization. This intermediate subsequently forms aromatic products upon dehydrogenation. The binding orientation of the enone reactants on the catalytic surface is strongly metal-dependent, as the M–O bond distance changes substantially according to the metal. The longer M–O bonds (Pt: 2.84 Å > Pd: 2.23 Å > Rh: 2.17 Å > Ru: 2.07 Å) correlate with faster reaction rates and more favorable keto–enol tautomerization, as shorter distances correspond to a more stabilized starting material. Tautomerization is shown to occur via a stepwise surface-assisted pathway. Overall, each of the studied metals exhibits a distinct balance of enthalpy and entropy of activation (ΔH°‡, ΔS°‡), offering unique possibilities in the realm of enone dehydrogenation reactions that can be achieved by suitable selection of catalytic materials.    

    

* Unveiling the Dynamic Evolution of Single-Atom Co Sites in Covalent Triazine Frameworks for Enhanced H2O2 Photosynthesis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391685024
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Content-Centric Networking for Information Delivery, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04439")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391685024"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391685024"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391685024"))][Get cited by]]

OpenAlex: https://openalex.org/W4391685024 (Open access: False)
    
[[https://openalex.org/A5080637240][Chao Zhu]], [[https://openalex.org/A5063115287][Yanchi Yao]], [[https://openalex.org/A5000714277][Qile Fang]], [[https://openalex.org/A5045577703][Lingxiangyu Li]], [[https://openalex.org/A5090741037][Baoliang Chen]], [[https://openalex.org/A5043170120][Yi Shen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04439 
     
Unraveling the structural evolution and mechanism of active sites in single-atom catalysts (SACs) during H2O2 production under operational conditions remains challenging due to the transient and elusive nature of the underlying reaction processes. Herein, we employ operando X-ray absorption spectroscopy and ab initio molecular dynamics simulations to unveil the dynamic reconstruction behavior of the Co single atom-loaded covalent triazine framework (CoSA/Py-CTF) during photocatalytic H2O2 production. The unique Py-CTF substrate provides reasonable structural flexibility to the single atom Co site. Under light irradiation and O2 adsorption, single Co atoms are dynamically released from the Py-CTF substrate and then form transient atom-pairs with neighboring Co atoms, serving as the authentic active site. The dynamic shuttling of Co subnanometer domains between single-atoms and atom-pairs facilitates the transition of the O2 adsorption configurations from Pauling type to Yeager type, resulting in a record photocatalytic H2O2 yield (2898.3 μmol·h–1·g–1). These findings provide insightful observations into the dynamic photochemical behavior of SACs and present an fresh paradigm for the design of intelligent “adaptive catalysts”.    

    
