#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Thu Feb  8 00:43:10 2024

Found 25 results from 2024-02-01 to 2024-02-08
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Nitrogenation and Oxygenation of an Unstrained C–C Bond Enabled by the Merger of Visible-Light and Cu-Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391379480
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05701")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391379480"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391379480"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391379480"))][Get cited by]]

OpenAlex: https://openalex.org/W4391379480 (Open access: False)
    
[[https://openalex.org/A5079594267][Yu Wang]], [[https://openalex.org/A5011975977][Huan Meng]], [[https://openalex.org/A5066598051][Sifan Li]], [[https://openalex.org/A5030583530][Wei Shu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05701 
     
Unstrained carbon–carbon bonds are among the most prevalent and inert chemical bonds. Thus, developing synthetic transformations directly from unstrained carbon–carbon bonds under mild conditions is ideal yet challenging due to the inertness and steric hindrance. Here, a visible-light and copper-catalyzed azidation and etherification of a remote and unstrained C–C bond of amines via 1,4-aryl migration have been reported. This redox-neutral protocol shows exquisite site-selectivity, broad scope, and good functional group tolerance, directly transforming unstrained C–C bonds to C–N and C–O bonds at room temperature. Facile derivatizations of benzyl azide products into free amines, triazoles, and phosphamides highlight the potential utility of this method for target molecule synthesis and medicinal chemistry.    

    

* Flavin-Mediated Photocatalysis Provides a General Platform for Sulfide C–H Functionalization  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391381968
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Catalytic C-H Amination Reactions, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05785")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391381968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391381968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391381968"))][Get cited by]]

OpenAlex: https://openalex.org/W4391381968 (Open access: True)
    
[[https://openalex.org/A5093827907][Alex S. Anderton]], [[https://openalex.org/A5078112212][Oliver Knowles]], [[https://openalex.org/A5000065563][James A. Rossi‐Ashton]], [[https://openalex.org/A5040225377][David J. Procter]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05785  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05785][pdf]])
     
Functionalized sulfides are important in many areas of science, ranging from chemical biology through drug discovery to organic materials chemistry. Sulfides bearing pendant reactive groups in the α-position are particularly useful; however, methods for the selective valorization of simple sulfides or the late-stage functionalization of complex sulfides by the convenient addition of valuable functionality are underexplored. Here we exemplify a general reaction platform for sulfide functionalization by showcasing three modes of α-sulfur C–H functionalization; cyanation, alkenylation, and alkynylation. Using inexpensive and commercially available riboflavin tetraacetate and visible light, decoration of both feedstock and complex sulfides proceeds in a good yield and with high selectivity. Methionine-containing peptides can also be selectively functionalized and a tolerance screen using amino-acid dopants suggests that the platform is compatible with most amino-acid side chains and thus is a potential tool for bioconjugation.    

    

* Oxygen-18 Labeling Defines a Ferric Peroxide (Compound 0) Mechanism in the Oxidative Deformylation of Aldehydes by Cytochrome P450 2B4  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391383010
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Drug Metabolism and Pharmacogenomics, Metabolic Reprogramming in Cancer Biology
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00106")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391383010"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391383010"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391383010"))][Get cited by]]

OpenAlex: https://openalex.org/W4391383010 (Open access: False)
    
[[https://openalex.org/A5080246471][Yasuhiro Tateishi]], [[https://openalex.org/A5042518092][Kevin D. McCarty]], [[https://openalex.org/A5088708740][Martha V. Martin]], [[https://openalex.org/A5058389506][F. Peter Guengerich]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00106 
     
No abstract    

    

* Constructing a Highly Active Pd Atomically Dispersed Catalyst for Cinnamaldehyde Hydrogenation: Synergistic Catalysis between Pd–N3 Single Atoms and Fully Exposed Pd Clusters  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391386420
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05883")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391386420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391386420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391386420"))][Get cited by]]

OpenAlex: https://openalex.org/W4391386420 (Open access: False)
    
[[https://openalex.org/A5022526821][Xin Li]], [[https://openalex.org/A5045960607][Jiaqi Liu]], [[https://openalex.org/A5062636173][Jian Wu]], [[https://openalex.org/A5076495171][Lipeng Zhang]], [[https://openalex.org/A5001966929][Dong Cao]], [[https://openalex.org/A5006520119][Daojian Cheng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05883 
     
No abstract    

    

* Ni-Catalyzed Cyanation of (Hetero)aryl Halides with Acetonitrile as Cyano Source  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391401203
:TOPICS: Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:PUBLICATION_DATE: 2024-01-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05836")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391401203"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391401203"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391401203"))][Get cited by]]

OpenAlex: https://openalex.org/W4391401203 (Open access: False)
    
[[https://openalex.org/A5052209030][M. Siddique]], [[https://openalex.org/A5077470082][Bing Zeng]], [[https://openalex.org/A5092336971][Ruqiya Qasim]], [[https://openalex.org/A5051769353][Dandan Zheng]], [[https://openalex.org/A5015957505][Qing Zhang]], [[https://openalex.org/A5000254862][Yi Jiang]], [[https://openalex.org/A5016834374][Qifeng Wang]], [[https://openalex.org/A5029086223][Kamel Meguellati]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05836 
     
We present a highly efficient method for cyanating challenging substrates with a specific focus on aryl fluorides. This innovative methodology has been successfully expanded to encompass a diverse array of aryl halides, underscoring its versatility and broad applicability. The nickel-catalyzed protocol utilizes acetonitrile under mild temperature conditions, providing a clean and safe alternative for cyanation. Notably, it employs a nonhazardous, nongaseous, metal-free cyanide source and demonstrates a wide substrate scope, accommodating aryl chlorides, fluorides, bromides, and iodides. The reaction is particularly effective with acetonitrile. This catalytic cyanation process serves as a valuable route for synthesizing pharmaceuticals such as letrozole, citalopram, and other NNRTI drugs. Mechanistically, we propose that a catalytic cycle involving zerovalent nickel and divalent nickel is more plausible for this reaction.    

    

* Design of Advanced Thin-Film Catalysts for Electrooxidation of Formic Acid  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391404712
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05520")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391404712"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391404712"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391404712"))][Get cited by]]

OpenAlex: https://openalex.org/W4391404712 (Open access: False)
    
[[https://openalex.org/A5034117811][Dušan Tripković]], [[https://openalex.org/A5063735085][Dragana Milošević]], [[https://openalex.org/A5016216807][Sanja Stevanović]], [[https://openalex.org/A5027372824][K.Dj. Popović]], [[https://openalex.org/A5080898167][Vladan Jovanović]], [[https://openalex.org/A5050235192][Pietro Papa Lopes]], [[https://openalex.org/A5055560859][Pedro Farinazzo Bergamo Dias Martins]], [[https://openalex.org/A5005598291][Vojislav R. Stamenković]], [[https://openalex.org/A5063468691][Dušan Strmčnik]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05520 
     
Successful development of catalysts for electrochemical formic acid oxidation (FAO) requires finding an optimal balance between catalytic performance (activity, stability, and selectivity) and catalyst cost. While platinum is one of the most active catalyst materials for FAO, it suffers from performance loss at low overpotentials due to poisoning with CO, which is one of the intermediates formed in the so-called indirect path of FAO. In this work, we explored the synergistic effects of the supporting material and annealing temperature on the performance of Pt thin films for FAO in acidic media. Compared to the as-prepared Pt films, the annealed films show up to 5-fold and 15-fold improvement for FAO on Pt@Ni and Pt@Cr, respectively. While the most active Pt@Ni thin film shows the lowest stability, the most active Pt@Cr thin film is also the most stable, challenging conventional trade-offs in electrocatalysis and providing a promising candidate for FAO nanocatalyst synthesis.    

    

* Carbon-Interacted AlF3 Clusters as Robust Catalyst for Dehydrofluorination Reaction with Enhanced Undercoordination and Stability  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391420358
:TOPICS: Chemistry of Noble Gas Compounds and Interactions, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05921")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391420358"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391420358"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391420358"))][Get cited by]]

OpenAlex: https://openalex.org/W4391420358 (Open access: False)
    
[[https://openalex.org/A5006850220][Yiwei Sun]], [[https://openalex.org/A5071437727][Xiaoli Wei]], [[https://openalex.org/A5087241265][Wei Zhang]], [[https://openalex.org/A5065058975][Zhen Wang]], [[https://openalex.org/A5025783802][Jianhai Jiang]], [[https://openalex.org/A5011880351][Fangcao Liu]], [[https://openalex.org/A5014528965][Bing Liu]], [[https://openalex.org/A5032441946][Wenfeng Han]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05921 
     
No abstract    

    

* Selective Catalytic Reduction of CO2 to CO by a Single-Site Heterobimetallic Iron–Potassium Complex Supported on Alumina  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391449260
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04989")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391449260"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391449260"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391449260"))][Get cited by]]

OpenAlex: https://openalex.org/W4391449260 (Open access: False)
    
[[https://openalex.org/A5062083258][A. A. Isah]], [[https://openalex.org/A5090881499][Oluwatosin A Ohiro]], [[https://openalex.org/A5027475930][Li Li]], [[https://openalex.org/A5013535790][Y. Nasiru]], [[https://openalex.org/A5019349020][Kaï C. Szeto]], [[https://openalex.org/A5052522375][Pierre‐Yves Dugas]], [[https://openalex.org/A5039985056][Anass Benayad]], [[https://openalex.org/A5024002693][Aimery De Mallmann]], [[https://openalex.org/A5029871622][Susannah L. Scott]], [[https://openalex.org/A5026770434][Bryan R. Goldsmith]], [[https://openalex.org/A5032643129][Mostafa Taoufik]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04989 
     
CO2 has attracted much attention as a C1 feedstock for synthetic fuels via its selective catalytic hydrogenation to liquid hydrocarbons. One strategy is the catalytic reduction of CO2 to CO through the reverse water–gas shift (RWGS) reaction, followed by the hydrogenation of CO. In this work, potassium tris(tert-butoxy)ferrate, [{(THF)2KFe(OtBu)3}2], was supported on alumina that had been partially dehydroxylated at 500 °C (Al2O3–500), and the resulting catalyst was investigated in the selective reduction of CO2 to CO. The active site precursor was identified as [(THF)K(AlsO)Fe(OtBu)2(OHAl)] (i.e., [(THF)KFe(OtBu)2]/Al2O3–500), denoted 2-K, based on elemental analysis, diffuse reflectance infrared Fourier transform (DRIFT) spectroscopy, scanning electron microscopy with energy-dispersive X-ray spectroscopy (high-resolution transmission electron microscopy (HRTEM) and EDS), X-ray photoelectron spectroscopy, and X-ray absorption spectroscopy. Under the reaction conditions, the precursor becomes an active, stable, and selective RWGS catalyst (100% selectivity to CO at 22.5% CO2 conversion). The reaction mechanism was studied by operando DRIFT spectroscopy and density functional theory (DFT) modeling. The results are consistent with a mechanism involving H2 activation by K[(AlsO)2FeOH], leading to K[(AlsO)2FeH]. CO2 insertion gives hydroxycarbonyl intermediate K[(AlsO)2FeCOOH], followed by liberation of CO to regenerate K[(AlsO)2FeOH].    

    

* Overturning CO2 Hydrogenation Selectivity via Strong Metal–Support Interaction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391449336
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05527")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391449336"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391449336"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391449336"))][Get cited by]]

OpenAlex: https://openalex.org/W4391449336 (Open access: False)
    
[[https://openalex.org/A5068495374][Wenzhe Zhang]], [[https://openalex.org/A5073828443][Hui Lin]], [[https://openalex.org/A5087759183][Wei Yao]], [[https://openalex.org/A5057214714][Xuan Zhou]], [[https://openalex.org/A5016992819][Yunlei An]], [[https://openalex.org/A5029828499][Yuanyuan Dai]], [[https://openalex.org/A5072202821][Qiang Niu]], [[https://openalex.org/A5090614196][Tiejun Lin]], [[https://openalex.org/A5022840101][Liangshu Zhong]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05527 
     
Strong metal–support interaction (SMSI) is commonly observed for platinum-group metals on reducible oxide supports upon a high-temperature reduction (≥500 °C). Herein, we show that the SMSI state can be constructed over a Ru/anatase-TiO2 catalyst using the CO2 hydrogenation reaction gas at a low temperature of ∼210 °C, which could overturn the CO2 hydrogenation selectivity from 100% CH4 to >99% CO. It is revealed that the exposed metallic Ru nanoparticles promote CH4 formation via formate intermediates at temperatures <200 °C. Elevating the temperature under a H2-containing atmosphere causes the evolution of active TiOx suboxide to form an encapsulated structure of Ru@TiOx, which changes the surface intermediate from formate to carboxy species during CO2 hydrogenation, thus leading to exclusive CO formation with long-term catalytic stability. The O2-containing gas treatment of encapsulated Ru@TiOx could achieve the cyclic switch of product selectivity between CO and CH4. This work provides an effective strategy to modulate the SMSI state at a very low temperature.    

    

* Recent Advances in Theoretical Studies on Cu-Mediated Bond Formation Mechanisms Involving Radicals  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391451464
:TOPICS: Molecular Electronic Devices and Systems, Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06042")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391451464"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391451464"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391451464"))][Get cited by]]

OpenAlex: https://openalex.org/W4391451464 (Open access: False)
    
[[https://openalex.org/A5088854097][Ji-Ren Liu]], [[https://openalex.org/A5022942675][Guo-Xiong Xu]], [[https://openalex.org/A5076035934][Li-Gao Liu]], [[https://openalex.org/A5049010282][Shuo‐Qing Zhang]], [[https://openalex.org/A5009790777][Xin Hong]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06042 
     
Copper-catalyzed radical transformations establish a powerful toolkit to construct versatile complex organic compounds. The copper-mediated bond formation step of radicals plays a critical role in controlling chemo- and stereoselectivity of copper-catalyzed radical transformation reactions. This bond formation step involves three possible pathways: ion-type bond formation, radical substitution, and reductive elimination. This review highlights the recent advances in theoretical studies on mechanisms and controlling models on the selectivity of Cu-mediated radical-involved bond formation, providing a general mechanistic comprehension of this key elementary step in copper catalysis.    

    

* Unlocking the Potential of 5-Hydroxy-2(5H)-furanone as a Platform for Bio-Based Four Carbon Chemicals  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391472682
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Enzyme Immobilization Techniques, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04872")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391472682"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391472682"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391472682"))][Get cited by]]

OpenAlex: https://openalex.org/W4391472682 (Open access: False)
    
[[https://openalex.org/A5077107342][Yayati Naresh Palai]], [[https://openalex.org/A5051687801][Atsushi Fukuoka]], [[https://openalex.org/A5090337296][Abhijit Shrotri]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04872 
     
No abstract    

    

* Revealing the Size Effect of Ceria Nanocube-Supported Platinum Nanoparticles in Complete Propane Oxidation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391473249
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06139")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391473249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391473249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391473249"))][Get cited by]]

OpenAlex: https://openalex.org/W4391473249 (Open access: False)
    
[[https://openalex.org/A5085640519][Shasha Ge]], [[https://openalex.org/A5041535237][Wei Fan]], [[https://openalex.org/A5064104167][Xiaoping Tang]], [[https://openalex.org/A5027626134][Yao Cui]], [[https://openalex.org/A5033936824][Dong Wang]], [[https://openalex.org/A5085852346][Xue‐Qing Gong]], [[https://openalex.org/A5031493683][Sheng Dai]], [[https://openalex.org/A5012006645][Yang Lou]], [[https://openalex.org/A5034676524][Jie Tang]], [[https://openalex.org/A5080435466][Yanglong Guo]], [[https://openalex.org/A5058391979][Zhan Wang]], [[https://openalex.org/A5059830462][Li Wang]], [[https://openalex.org/A5032176049][Yun Guo]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06139 
     
The elimination of propane is one of the key tasks in reducing volatile organic compounds (VOCs) and automotive exhaust emissions. The platinum nanoparticle (NP) is a promising catalyst for propane oxidation, while the study of its structural characteristics and functionality remains in its infancy. In this work, we synthesized the nanocubes CeO2 with a well-defined (100) facet supporting Pt NPs with various sizes, from 1.3 to 7 nm, and systematically investigated the effect of the Pt size on complete propane oxidation efficiency. In particular, CeO2(100) supported Pt NPs smaller than 4 nm promote the formation of positively charged Pt sites, which hinder the adsorption and activation of propane and reduce the intrinsic activity for propane oxidation. Consequently, within this size range, the catalytic performance is primarily influenced by the electronic state of the Pt species, with metallic Pt being identified as the active site for the reaction. Conversely, as the particle size exceeds 4 nm, metallic Pt particles become dominant and the geometric structure starts to influence the activity as well. Such entanglement of electronic and geometric factors gives rise to a volcano relationship between reaction rates and Pt particle sizes ranging from 1.3 to 7 nm, while an increased correlation can be observed between the turnover frequencies and the particle sizes in this range. This knowledge can guide the synthesis of highly active catalysts, enabling the efficient oxidation of VOCs with reduced precious metal loadings.    

    

* N-Heterocyclic Carbene-Carbodiimide (NHC-CDI) Betaines as Organocatalysts for β-Butyrolactone Polymerization: Synthesis of Green PHB Plasticizers with Tailored Molecular Weights  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391473810
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Transition Metal Catalysis, Biodegradable Polymers as Biomaterials and Packaging
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05357")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391473810"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391473810"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391473810"))][Get cited by]]

OpenAlex: https://openalex.org/W4391473810 (Open access: True)
    
[[https://openalex.org/A5046769905][David Sánchez-Roa]], [[https://openalex.org/A5044974820][Valentina Sessini]], [[https://openalex.org/A5011679409][Marta E. G. Mosquera]], [[https://openalex.org/A5041336405][Juan Cámpora]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05357  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05357][pdf]])
     
The manufacture of poly(3-hydroxybutyrate) (PHB) stands out as a promising alternative to traditional plastics. This polymer is usually produced by bacteria-based biotechnology or metal-catalyzed ring-opening polymerization (ROP) of β-butyrolactone (β-BL). Nevertheless, commercial PHB suffers from different issues, from poor processability to high production costs. Herein, we report the chemical synthesis of PHB from the ROP of rac-β-butyrolactone promoted by a zwitterionic organocatalyst, an N-heterocyclic carbene-carbodiimide (NHC-CDI) betaine adduct. This reaction has been investigated by a combination of experimental and computational methods. The catalyst cleaves the β-BL via nucleophilic displacement of the C–O(carboxyl) bond followed by intramolecular elimination to give protonated betaine–crotonate ion pairs, the active polymerization initiators. Polymer growth is propagated and controlled by these betaine ion pairs, which render amorphous low-molecular-weight PHBs by an unusual mechanism with rapid chain transfer to the monomer regime, analogous to the well-known mechanism of ethylene oligomerization with late transition-metal catalysts. The resulting material is suitable as a biodegradable and biocompatible plasticizer for commercial bacterial or synthetic PHB. Perfect compatibility between the matrix and the additive and a significant reduction of the crystallinity resulted in a more flexible and resilient material.    

    

* Assembled Quantum Dot Porous Clusters for Enhanced Photocatalytic Reduction of Quinone to Hydroquinone  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391475441
:TOPICS: Applications of Quantum Dots in Nanotechnology, Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-01-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04492")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391475441"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391475441"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391475441"))][Get cited by]]

OpenAlex: https://openalex.org/W4391475441 (Open access: False)
    
[[https://openalex.org/A5005132094][Yufeng Qin]], [[https://openalex.org/A5041477172][Xiang Cheng]], [[https://openalex.org/A5009441078][Zhuo Zhao]], [[https://openalex.org/A5080850908][Chaodan Pu]], ACS Catalysis. 14(3)] 2024. https://doi.org/10.1021/acscatal.3c04492 
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391476187
:TOPICS: 
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i003_1766342")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391476187"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391476187"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391476187"))][Get cited by]]

OpenAlex: https://openalex.org/W4391476187 (Open access: True)
    
, ACS Catalysis. 14(3)] 2024. https://doi.org/10.1021/csv014i003_1766342  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i003_1766342][pdf]])
     
ADVERTISEMENT RETURN TO ISSUEPREVArticleNEXTIssue Editorial MastheadCite this: ACS Catal. 2024, 14, 3, XXX-XXXPublication Date (Web):February 2, 2024Publication History Published online2 February 2024Published inissue 2 February 2024https://doi.org/10.1021/csv014i003_1766342Copyright © 2024 American Chemical SocietyRequest reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (198 KB) Get e-Alertsclose Get e-Alerts    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391476423
:TOPICS: 
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i003_1766341")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391476423"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391476423"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391476423"))][Get cited by]]

OpenAlex: https://openalex.org/W4391476423 (Open access: True)
    
, ACS Catalysis. 14(3)] 2024. https://doi.org/10.1021/csv014i003_1766341  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i003_1766341][pdf]])
     
ADVERTISEMENT RETURN TO ISSUEPREVArticleIssue Publication InformationCite this: ACS Catal. 2024, 14, 3, XXX-XXXPublication Date (Web):February 2, 2024Publication History Published online2 February 2024Published inissue 2 February 2024https://doi.org/10.1021/csv014i003_1766341Copyright © 2024 American Chemical SocietyRequest reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (153 KB) Get e-Alertsclose Get e-Alerts    

    

* Insight into Selectivity Differences of Glycerol Electro-Oxidation on Pt(111) and Ag(111)  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391484173
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05551")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391484173"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391484173"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391484173"))][Get cited by]]

OpenAlex: https://openalex.org/W4391484173 (Open access: False)
    
[[https://openalex.org/A5061862591][Zhongjie Meng]], [[https://openalex.org/A5011352251][David Tran]], [[https://openalex.org/A5074226300][Johan Hjelm]], [[https://openalex.org/A5028337707][Henrik H. Kristoffersen]], [[https://openalex.org/A5083668074][Jan Rossmeisl]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05551 
     
Electro-oxidation is a way to utilize glycerol, a byproduct of biodiesel production, to produce fuels and feedstock chemicals for the chemical industry. A significant challenge is to get products with high selectivity, so it is desirable to understand the glycerol oxidation mechanisms in further detail. Using density functional theory calculations, we investigated possible glycerol oxidation intermediates on Pt(111) and Ag(111). We find that the different adsorption preferences of the intermediates on Pt (adsorption via carbon atoms) and Ag (adsorption via oxygen atoms) lead to different preferred reaction pathways, resulting in different products. The reaction pathways on both surfaces involve glyceraldehyde as a key intermediate; however, upon further oxidation, Pt(111) preferentially produces glyceric acid (CH2OH–CHOH–COOH), while on Ag(111) C–C bonds are broken, which leads to the production of glycolaldehyde and formic acid (CH2OH–CHO and HCOOH). These predictions agree well with the experimental outcome of the electro-oxidation of glycerol on Pt and Ag surfaces. Our study therefore provides useful insights for optimizing the selectivity of glycerol oxidation and improving the utilization of glycerol.    

    

* Metal–Support Interaction between Titanium Oxynitride and Pt Nanoparticles Enables Efficient Low-Pt-Loaded High-Performance Electrodes at Relevant Oxygen Reduction Reaction Current Densities  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391484257
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03883")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391484257"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391484257"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391484257"))][Get cited by]]

OpenAlex: https://openalex.org/W4391484257 (Open access: True)
    
[[https://openalex.org/A5035921159][Armin Hrnjić]], [[https://openalex.org/A5026019396][Ana Rebeka Kamšek]], [[https://openalex.org/A5093435006][Lazar Bijelić]], [[https://openalex.org/A5067506046][Anja Lončar]], [[https://openalex.org/A5002824921][Nik Maselj]], [[https://openalex.org/A5023655269][Milutin Smiljanić]], [[https://openalex.org/A5025812387][Jan Trputec]], [[https://openalex.org/A5053380398][Nikolay Vovk]], [[https://openalex.org/A5057907379][Luka Pavko]], [[https://openalex.org/A5035475331][Francisco Ruiz-Zepeda]], [[https://openalex.org/A5059203752][Marjan Bele]], [[https://openalex.org/A5079953428][Primož Jovanovič]], [[https://openalex.org/A5065843632][Nejc Hodnik]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c03883  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c03883][pdf]])
     
In the present work, we report on a synergistic relationship between platinum nanoparticles and a titanium oxynitride support (TiOxNy/C) in the context of oxygen reduction reaction (ORR) catalysis. As demonstrated herein, this composite configuration results in significantly improved electrocatalytic activity toward the ORR relative to platinum dispersed on carbon support (Pt/C) at high overpotentials. Specifically, the ORR performance was assessed under an elevated mass transport regime using the modified floating electrode configuration, which enabled us to pursue the reaction closer to PEMFC-relevant current densities. A comprehensive investigation attributes the ORR performance increase to a strong interaction between platinum and the TiOxNy/C support. In particular, according to the generated strain maps obtained via scanning transmission electron microscopy (STEM), the Pt-TiOxNy/C analogue exhibits a more localized strain in Pt nanoparticles in comparison to that in the Pt/C sample. The altered Pt structure could explain the measured ORR activity trend via the d-band theory, which lowers the platinum surface coverage with ORR intermediates. In terms of the Pt particle size effect, our observation presents an anomaly as the Pt-TiOxNy/C analogue, despite having almost two times smaller nanoparticles (2.9 nm) compared to the Pt/C benchmark (4.8 nm), manifests higher specific activity. This provides a promising strategy to further lower the Pt loading and increase the ECSA without sacrificing the catalytic activity under fuel cell-relevant potentials. Apart from the ORR, the platinum-TiOxNy/C interaction is of a sufficient magnitude not to follow the typical particle size effect also in the context of other reactions such as CO stripping, hydrogen oxidation reaction, and water discharge. The trend for the latter is ascribed to the lower oxophilicity of Pt-based on electrochemical surface coverage analysis. Namely, a lower surface coverage with oxygenated species is found for the Pt-TiOxNy/C analogue. Further insights were provided by performing a detailed STEM characterization via the identical location mode (IL-STEM) in particular, via 4DSTEM acquisition. This disclosed that Pt particles are partially encapsulated within a thin layer of TiOxNy origin.    

    

* Selective Hydrogenation of Alkyne by Atomically Precise Pd6 Nanocluster Catalysts: Accurate Construction of the Coplanar and Specific Active Sites  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391484269
:TOPICS: Structural and Functional Study of Noble Metal Nanoclusters, Catalytic Reduction of Nitro Compounds, Plasmonic Nanoparticles: Synthesis, Properties, and Applications
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05833")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391484269"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391484269"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391484269"))][Get cited by]]

OpenAlex: https://openalex.org/W4391484269 (Open access: False)
    
[[https://openalex.org/A5034676524][Jie Tang]], [[https://openalex.org/A5060107836][Kun Jia]], [[https://openalex.org/A5091816086][Ruiqi Zhang]], [[https://openalex.org/A5055920244][Chao Liu]], [[https://openalex.org/A5086193630][Xinzhang Lin]], [[https://openalex.org/A5065838284][Tingting Ge]], [[https://openalex.org/A5011085153][Xiaorui Liu]], [[https://openalex.org/A5070736386][Qiao Zhao]], [[https://openalex.org/A5013434268][Wei Liu]], [[https://openalex.org/A5055822249][Ding Ma]], [[https://openalex.org/A5081854327][Hongjun Fan]], [[https://openalex.org/A5066309957][Jiahui Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05833 
     
Atomically precise nanoclusters are promising model catalysts to understand the relationship between structure and catalytic activity. However, designing efficient active sites remains challenging because the highly covered ligands obscure the metal sites. Herein, we reported a Pd6(S-Adm)6(PPh3)(PPh) nanocluster, which shows high selectivity in the semihydrogenation of aromatic alkyne. The Pd6 nanocluster has a unique chair structure, where the pan is composed of the coplanar Pd atoms, the back is composed of two S-Adm ligands, and the legs are composed of four S-Adm, one PPh3, and one PPh ligands. Experiments reveal that the high selectivity of intact Pd6 nanocluster is attributed to the synergistic effect of thiols and phosphines, modulating the electron properties and benefiting the proper hydrogen dissociation ability and desorption of product. Interestingly, it was found that the exposed coplanar Pd atoms could provide specific active sites for the adsorption of C≡C and benzene ring. DFT calculations show that phenylacetylene and styrene adsorb on the coplanar Pd6 much weaker than on the Pd(111) surface, allowing the styrene to be desorbed before further hydrogenation. The phenyl adsorption constrains that the hydrogenation can occur only on the coplanar Pd6, which is more facile for phenylacetylene than for styrene, and results in semihydrogenation.    

    

* Tailoring the Olefin Selectivity in Catalytic Oxidative Dehydrogenation of Light Alkane by the Isolation Strategy  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391485473
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05419")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391485473"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391485473"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391485473"))][Get cited by]]

OpenAlex: https://openalex.org/W4391485473 (Open access: False)
    
[[https://openalex.org/A5042063600][Yicong Chai]], [[https://openalex.org/A5074446754][Yanliang Zhou]], [[https://openalex.org/A5016546361][Sen Lin]], [[https://openalex.org/A5068754344][Xiaodong Wang]], [[https://openalex.org/A5047617959][Jin Lin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05419 
     
Olefins are important building blocks that have been extensively used to produce diverse consumer products in petrochemical industry. Owing to the requirement of low-carbon-footprint processes and the increasing use of light alkanes sourced from shale gas, an environmentally friendly and economic route alternative to the state-of-the-art steam cracking of crude oil has been investigated for olefin production. The oxidative dehydrogenation (ODH) of alkanes to olefins has attracted wide attention due to the absence of thermodynamic limitations and coke formation. However, excessive oxidation of olefin is prone to occur in this process. Developing a suitable ODH catalyst with high performance, particularly with enhanced selectivity, is more and more urgent but still remains a challenge. In this Review, we talk about the representative currently developed isolation strategies to optimize the selectivity of olefins via the ODH process, particularly for the conversion of ethane to ethylene, which include the dispersion regulation of metal oxide, the isolation of metal and nonmetal sites, the construction of dual functional sites to isolate dehydrogenation and oxidation steps, and the adoption of selective oxygen species with the promotion of soft oxidants as reactants. Furthermore, the mechanistic aspects about the activation of ethane and the participation of oxygen species for tailoring the selectivity are then classified and discussed in detail. Finally, the perspectives and the emerging technologies for the ODH process are listed and evaluated.    

    

* The Role of Adsorbed Species in 1-Butene Isomerization: Parahydrogen-Induced Polarization NMR of Pd–Au Catalyzed Butadiene Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391485519
:TOPICS: NMR Spectroscopy Techniques, Advancements in Density Functional Theory, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05968")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391485519"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391485519"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391485519"))][Get cited by]]

OpenAlex: https://openalex.org/W4391485519 (Open access: False)
    
[[https://openalex.org/A5081085463][Weiyu Wang]], [[https://openalex.org/A5063295957][Richard J. Lewis]], [[https://openalex.org/A5053116259][Bin Lü]], [[https://openalex.org/A5030863883][Qiang Wang]], [[https://openalex.org/A5020068159][Graham J. Hutchings]], [[https://openalex.org/A5016344450][Jun Xu]], [[https://openalex.org/A5055850550][Feng Deng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05968 
     
Isomerization of 1-butene critically influences product distributions in 1,3-butadiene hydrogenation. However, distinguishing between the isomerization and hydrogenation pathways is challenging. Here, we employ parahydrogen-induced polarization (PHIP) NMR spectroscopy to determine the extent of the isomerization pathway when using Pd–Au bimetallic nanoparticles synthesized via a colloidal protocol in the presence or absence of a polyvinylpyrrolidone (PVP) stabilizing ligand and immobilized on TiO2. Residual additives, in particular, sulfur, are observed to considerably influence the pairwise hydrogenation and 1-butene isomerization pathways. PHIP NMR analysis reveals that the PVP ligand can induce strong polarized signals, likely due to restricted proton migration, but minimally impact 1-butene isomerization. In contrast, removing surface sulfur species introduced during catalyst synthesis profoundly enhances 1-butene isomerization by reducing the hydrogen concentration at the nanoparticle surface. This work elucidates how residual species can modulate key reaction pathways such as isomerization during 1,3-butadiene hydrogenation, with implications for rational catalyst design.    

    

* Tailoring Metal-Ion-Doped Carbon Nitrides for Photocatalytic Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391486029
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391486029"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391486029"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391486029"))][Get cited by]]

OpenAlex: https://openalex.org/W4391486029 (Open access: False)
    
[[https://openalex.org/A5006958502][Shanping Liu]], [[https://openalex.org/A5080802270][Valentín Díez-Cabanes]], [[https://openalex.org/A5069062661][Dong Fan]], [[https://openalex.org/A5080107062][Peixiang Lu]], [[https://openalex.org/A5027738164][Yuanxing Fang]], [[https://openalex.org/A5075963769][Markus Antonietti]], [[https://openalex.org/A5087859676][Guillaume Maurin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05961 
     
Poly(heptazine imides) (PHIs) have emerged as prominent layered carbon nitride-based materials with potential oxygen evolution reaction (OER) catalytic activity owing to their strong VIS light absorption, long excited-state lifetimes, high surface-to-volume ratios, and the possibility of tuning their properties via hosting different metal ions in their pores. A series of metal-ion-doped PHI-M (M = K+, Rb+, Mg2+, Zn2+, Mn2+, and Co2+) were first systematically explored using density functional theory calculations. These simulations led an in-depth understanding of the microscopic OER mechanism in these systems and identified PHI-Co2+ as the best OER catalyst of this family of PHIs, whereas PHI-Mn2+ can be an alternative promising OER catalyst. This level of performance was attributed to a thermodynamically favorable formation of the reaction intermediates as well as its red-shifted absorption in the VIS region involving the population of long-lived states, as revealed by time-dependent density functional theory calculations. We further demonstrated that the electronic properties of the *OH intermediates (Bader population, crystal orbital Hamilton population analysis, and adsorption energies) are reliable descriptors to anticipate the OER activity of this family of PHIs. This rational analysis paved the way toward the prediction of the OER performance of another PHI-M derivative, i.e., PHI-Fe2+. The computationally explored PHI-Fe2+, PHI-Mn2+, and PHI-Co2+ systems were then synthesized alongside PHI-K+, and their photocatalytic OER activities were assessed. These experimental findings confirmed the best photocatalytic OER performance for PHI-Co2+ with an oxygen production of 31.2 μmol·h–1 that is 60 times higher than the pristine g-C3N4 (0.5 μmol·h–1), whereas PHI-Fe2+ and PHI-Mn2+ are seen as alternative OER catalysts with attractive oxygen production of 11.20 and 4.69 μmol·h–1, respectively. Decisively, this joint experimental–computational study reveals PHI-Co2+ to be among the best of the OER catalysts so far reported in the literature including some perovskites.    

    

* Highly Selective Upgrading of Polyethylene into Light Aromatics via a Low-Temperature Melting-Catalysis Strategy  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391486048
:TOPICS: Microplastic Pollution in Marine and Terrestrial Environments, Global E-Waste Recycling and Management, Polymer Crystallization and Properties
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05098")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391486048"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391486048"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391486048"))][Get cited by]]

OpenAlex: https://openalex.org/W4391486048 (Open access: False)
    
[[https://openalex.org/A5008788445][Zhe Zhang]], [[https://openalex.org/A5078632164][Huan Chen]], [[https://openalex.org/A5033895107][Guixiang Li]], [[https://openalex.org/A5067744419][Weigang Hu]], [[https://openalex.org/A5059445221][Bo Niu]], [[https://openalex.org/A5070718341][Donghui Long]], [[https://openalex.org/A5010941700][Yayun Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05098 
     
The selective upgrading of polyethylene waste into light aromatics is hampered by relatively high C–C bond cleavage temperatures and low product selectivity. Herein, we report a low-temperature melting-catalysis strategy that directly upgrades low-density polyethylene (LDPE) into light aromatics over commercial ZSM-5 zeolite under mild conditions, eliminating the need for precious metals, solvent, or external H2. Experimental results combined with DFT calculations and molecular dynamics simulations revealed that the molten LDPE microenvironment facilitates intimate LDPE-catalyst contact, promoting primary C–C cleavage while suppressing olefin intermediates diffusion out of pores. This feature increases the residence time for subsequent direct olefin cyclization within the confined micropores. Moreover, online mass spectra confirmed that the in situ generated hydrogen from cyclization and dehydroaromatization reactions plays a vital role in C–C bond scission. By optimizing the reaction conditions, a light aromatic yield of 50.6 wt % with an impressive selectivity of 90.9% toward benzene, toluene, and xylenes was achieved at 280 °C for 1 h. This strategy is not limited to the model polyethylene but also demonstrates remarkable efficiency in the depolymerization of various widely used polyethylene-rich plastics, enabling an economically viable and environmentally benign chemical recycling path for plastic wastes.    

    

* Ultrastable and Phosphoric Acid-Resistant PtRhCu@Pt Oxygen Reduction Electrocatalyst for High-Temperature Polymer Electrolyte Fuel Cells  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391509433
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04488")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391509433"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391509433"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391509433"))][Get cited by]]

OpenAlex: https://openalex.org/W4391509433 (Open access: False)
    
[[https://openalex.org/A5088459641][An Zhao]], [[https://openalex.org/A5054722093][Huanqiao Li]], [[https://openalex.org/A5091381220][Xiaoming Zhang]], [[https://openalex.org/A5012104204][Zhangxun Xia]], [[https://openalex.org/A5069849278][Hong Zhang]], [[https://openalex.org/A5078357872][Wenling Chu]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5000140137][Suli Wang]], [[https://openalex.org/A5039323596][Gongquan Sun]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04488 
     
No abstract    

    

* Photoredox-Driven Three-Component Coupling of Aryl Halides, Olefins, and O2  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391522091
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05988")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391522091"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391522091"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391522091"))][Get cited by]]

OpenAlex: https://openalex.org/W4391522091 (Open access: True)
    
[[https://openalex.org/A5060466975][Mark C. Maust]], [[https://openalex.org/A5031746021][Simon B. Blakey]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05988  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05988][pdf]])
     
Modern organic synthesis requires methodologies that bring together abundant feedstock chemicals in a mild and efficient manner. To aid in this effort, we have developed a multicomponent radical hydroxyarylation reaction that utilizes aryl halides, olefins, and O2 as the reaction components. Crucial to this advance was an oxidative, rather than a reductive, approach to aryl radical generation, which enables reaction tolerance to O2. This methodology displays a broad functional group tolerance with a variety of functionalized aryl halides and a broad array of olefins. Development of this methodology enables rapid access to biologically relevant hydroxyaryl products from simple, commercially available starting materials.    

    
