#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Mon Apr 22 01:05:00 2024

Found 45 results from 2024-04-15 to 2024-04-22
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Hydrogen Peroxide as an Ideal Electron Donor for Long-Lasting Fenton Chemistry: Strong Enhancement of Fe(III) Activity by Heteroatom-Doped Nanocarbons  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394797401
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Advanced Oxidation Processes for Water Treatment
:PUBLICATION_DATE: 2024-04-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00048")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394797401"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394797401"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394797401"))][Get cited by]]

OpenAlex: https://openalex.org/W4394797401 (Open access: False)
    
[[https://openalex.org/A5079801565][Yiming Sun]], [[https://openalex.org/A5062249713][Peng Zhou]], [[https://openalex.org/A5086727767][Minglu Sun]], [[https://openalex.org/A5066097652][Yuchen Zhang]], [[https://openalex.org/A5058010200][Xiao Wang]], [[https://openalex.org/A5005394920][Chenying Zhou]], [[https://openalex.org/A5088024077][Yang Liu]], [[https://openalex.org/A5010128689][Chuan-Shu He]], [[https://openalex.org/A5060591453][Bo Lai]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00048 
     
Heteroatom doping has been demonstrated to be an effective strategy to improve the catalytic activity of carbon materials. Herein, heteroatom-doped nanocarbons were found to be environmental protection cocatalysts for promoting Fenton oxidation. Nitrogen-doped reduced graphene oxide (N-rGO) exhibited better catalytic activity than sulfur-, boron-, and phosphorus-doped rGO for enhancing Fenton oxidation. Unlike classical electron sacrificial agents, H2O2 was employed as an electron donor to enhance Fenton oxidation during the catalysis of N-rGO. Electrochemical analysis and nitrogen molecular model tests indicated the oxidation potential of Fe(III) increased with improvement in the N atom content (R2 = 0.97), revealing that the Fe atoms of FeOH2+ on the N-rGO surface are more likely to abstract electrons from H2O2. In addition, the delocalized π electron is one of the active sites in N-rGO-boosted Fenton oxidation, and N-rGO could facilitate electron transfer from H2O2 to Fe(III) along the C–C/C═C structures due to the improvement of the conductivity ability and the oxidation potential of Fe(III). Moreover, density functional theory (DFT) calculations suggest that the pyrrole N species of N-rGO is the best catalytic activity site, resulting from the pyrrole N species with higher adsorption energy stretching the Fe–O bond of FeOH2+ to increase the activity of Fe(III) species. Therefore, the study findings provide insight into designing stable and efficient metal-free catalysts to enhance Fe(III) reactivity in overcoming the inherent drawbacks of the Fenton system.    

    

* Structural and Functional Analysis of Heparosan Synthase 2 from Pasteurella multocida to Improve the Synthesis of Heparin  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394800995
:TOPICS: Role of Extracellular Matrix in Biological Signaling, Glycosylation in Health and Disease, Chemical Glycobiology and Therapeutic Applications
:PUBLICATION_DATE: 2024-04-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00677")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394800995"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394800995"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394800995"))][Get cited by]]

OpenAlex: https://openalex.org/W4394800995 (Open access: False)
    
[[https://openalex.org/A5089389648][Eduardo Stancanelli]], [[https://openalex.org/A5091539133][J.M. Krahn]], [[https://openalex.org/A5020705232][Elizabeth Viverette]], [[https://openalex.org/A5019789402][Robert Dutcher]], [[https://openalex.org/A5008760115][Vijayakanth Pagadala]], [[https://openalex.org/A5038092347][Mario J. Borgnia]], [[https://openalex.org/A5021426830][Jian Liu]], [[https://openalex.org/A5008923312][Lars C. Pedersen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00677 
     
Heparin is a widely used drug to treat thrombotic disorders in hospitals. Heparosan synthase 2 from Pasteurella multocida (PmHS2) is a key enzyme used for the chemoenzymatic synthesis of heparin oligosaccharides. It has both activities: glucosaminyl transferase activity and glucuronyl transferase activity; however, the mechanism to carry out the glyco-oligomerization is unknown. Here, we report crystal structures of PmHS2 constructs with bound uridine diphosphate (UDP) and a cryo-EM structure of PmHS2 in complex with UDP and a heptasaccharide (NS 7-mer) substrate. Using a liquid chromatography–mass spectrometry analytical method, we discovered that the enzyme displays both a two-step concerted oligomerization mode and a distributive oligomerization mode depending on the nonreducing end of the starting oligosaccharide primer. Removal of seven amino acid residues from the C-terminus results in an enzymatically active monomer instead of a dimer and loses the concerted oligomerization mode of activity. In addition, the monomer construct can transfer N-acetyl glucosamine at a substrate concentration that is ∼7-fold higher than a wildtype enzyme. It was also determined that an F529A mutant can transfer an N-sulfoglucosamine (GlcNS) saccharide from a previously inactive UDP-GlcNS donor. Performing the glyco-transfer reaction at a high substrate concentration and the capability of using unnatural donors are desirable to simplifying the chemoenzymatic synthesis to prepare heparin-based therapeutics.    

    

* Catalytic Dinitrogen Reduction to Silylamines by Molybdenum Nitride Complexes Bearing a Diphenolate N-Heterocyclic Carbene Ligand  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394804794
:TOPICS: Ammonia Synthesis and Electrocatalysis, N-Heterocyclic Carbenes in Catalysis and Materials Chemistry, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-04-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00307")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394804794"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394804794"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394804794"))][Get cited by]]

OpenAlex: https://openalex.org/W4394804794 (Open access: False)
    
[[https://openalex.org/A5060854826][Zhaoxin Li]], [[https://openalex.org/A5004243344][Chenrui Liu]], [[https://openalex.org/A5035297011][Jing An]], [[https://openalex.org/A5013471192][Xi Wu]], [[https://openalex.org/A5088871411][Shaowei Hu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00307 
     
Despite substantial strides in the catalytic silylation of N2 employing phosphine-ligated transition metal complexes, further development has been impeded by the low reaction yields (based on reducing or silylating reagents). Here we present a series of Mo(VI) nitride complexes featuring a robust tridentate diphenolate N-heterocyclic carbene (OCO) ligand that serves as efficient catalysts for the reduction of N2 to silylamines, producing 57.3 equiv of tris(trimethylsilyl)amine with a yield of as high as 86%. Reductive silylation of Mo nitride complexes resulted in the isolation of a molybdenum silylimide intermediate. Our findings showed that the enhanced efficiency of the system could be ascribed to the high activity of catalysts and the suppression of side reactions, indicating that the OCO ligand plays a crucial role in stabilizing the Mo center across in high- and low-oxidation states in catalysis.    

    

* Palladium-Catalyzed Annulations via Sequential C–H Activations of C(sp2)–H/C(sp3)–H or C(sp3)–H/C(sp3)–H Bonds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394809512
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Transition Metal-Catalyzed Cross-Coupling Reactions, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-04-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01243")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394809512"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394809512"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394809512"))][Get cited by]]

OpenAlex: https://openalex.org/W4394809512 (Open access: True)
    
[[https://openalex.org/A5033493148][Wan‐Xu Wei]], [[https://openalex.org/A5029770937][Mateusz Czajkowski]], [[https://openalex.org/A5043507347][Yangjin Kuang]], [[https://openalex.org/A5011825967][Tu-Anh V. Nguyen]], [[https://openalex.org/A5030540576][Bo Qin]], [[https://openalex.org/A5001470938][Martin Tomanik]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01243  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01243][pdf]])
     
Palladium-catalyzed C–H annulation reactions represent a compelling strategy to construct complex ring systems with high step economy. While there are many approaches to annulate structures by activation of a single C–H bond, transformations that proceed by activation of multiple C–H bonds are less explored. This is especially true for examples where one of the reacting C–H bonds is located at an sp3 center. However, exciting developments in palladium-catalyzed C–H activation continue to expand the scope of these transformations and provide innovative strategies to construct challenging carbon–carbon bonds. From these discoveries, sequential C–H activations have emerged as a powerful tool to access complex ring systems through the activation of C(sp2)–H/C(sp3)–H or C(sp3)–H/C(sp3)–H bonds. In this Perspective, we showcase recent examples that use this strategy in order to highlight the synthetic potential of C–H activation-enabled annulations and inspire future use of these disconnections for diverse scaffold synthesis.    

    

* Site-Selective Bimetallic Heterogeneous Nanostructures for Plasmon-Enhanced Photocatalysis of Nitrobenzene Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394821192
:TOPICS: Catalytic Reduction of Nitro Compounds, Photocatalytic Materials for Solar Energy Conversion, Structural and Functional Study of Noble Metal Nanoclusters
:PUBLICATION_DATE: 2024-04-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394821192"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394821192"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394821192"))][Get cited by]]

OpenAlex: https://openalex.org/W4394821192 (Open access: False)
    
[[https://openalex.org/A5029299515][Yaqin Wang]], [[https://openalex.org/A5091347153][Jinjin Zheng]], [[https://openalex.org/A5085028455][Qi Liu]], [[https://openalex.org/A5009838803][Yuqiang Shi]], [[https://openalex.org/A5090613639][Huijie Liu]], [[https://openalex.org/A5033486450][Zheng Huang]], [[https://openalex.org/A5078789709][Jun Yi]], [[https://openalex.org/A5006880897][Ye Yang]], [[https://openalex.org/A5063820443][Qin Kuang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00024 
     
Nitrobenzene hydrogenation, a critical pathway for synthesizing aniline, typically requires a high temperature and pressurized hydrogen for effective and selective reduction. It is of great significance to find a catalyst with a favorable reaction rate toward the selective hydrogenation of nitroaromatics. Herein, anisotropic Au–Pd tipped NPs were specially synthesized and found to exhibit efficient plasmon-enhanced hydrogenation of nitrobenzene to aniline. Under light, Au–Pd tipped NPs exhibited a TOF of 166 h–1 with high selectivity (>92%). Simulation results demonstrated that site-selective bimetallic heterogeneous nanostructures maintain a strong electromagnetic field, which further promotes the generation and transfer of energetic hot electrons for photocatalysis. Meanwhile, in situ X-ray photoelectron spectroscopy and quasi-in situ electron paramagnetic resonance revealed that the movement of hot electrons facilitates the enhanced participation of hot holes in the oxidation of the hydrogen donor. Our findings underscore that the rational design of bimetallic structures not only exposes rich active sites for incoming reactants but also prolongs the lifetime of hot carriers for efficient transfer and injection.    

    

* Nitrogen, Sulfur Co-doped Hollow Carbon-Encapsulated Cu/Co2P for Selective Oxidation Esterification of Furfurals  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394822901
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Desulfurization Technologies for Fuels, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01035")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394822901"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394822901"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394822901"))][Get cited by]]

OpenAlex: https://openalex.org/W4394822901 (Open access: False)
    
[[https://openalex.org/A5027667185][Yuanji Dong]], [[https://openalex.org/A5007294352][Xianhai Zeng]], [[https://openalex.org/A5058785364][Xiongxiong Zuo]], [[https://openalex.org/A5073122482][Jiaran Li]], [[https://openalex.org/A5003350925][Yu Jia]], [[https://openalex.org/A5005303316][Ge Zhang]], [[https://openalex.org/A5069713206][Junhua Kuang]], [[https://openalex.org/A5066467095][Işıl Akpınar]], [[https://openalex.org/A5029242069][Peng Li]], [[https://openalex.org/A5083899530][Xing Tang]], [[https://openalex.org/A5039771921][Jin‐Chao Dong]], [[https://openalex.org/A5059884717][Lin Liu]], [[https://openalex.org/A5078907574][Pengbo Lyu]], [[https://openalex.org/A5042323150][Shuliang Yang]], [[https://openalex.org/A5038135164][Jian‐Feng Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01035 
     
With the remarkable capability of encapsulating multifunctional active sites inside, carbon-based materials play vital roles in multifarious chemical transformations such as hydrogenation reactions, oxidation reactions, esterification reactions, etc. Herein, we propose an efficient and facile approach to construct a Cu/Co2P@C-NS catalyst, which consists of nitrogen–sulfur co-doped carbon (C-NS) encapsulated cobalt phosphide (Co2P) and copper double active sites. This approach focuses on the design and preparation of core–shell materials, that is, the ZIF-67 core is coated with an adhesive poly(cyclotriphosphazene-co-4,4′-sulfonyldiphenol) (PZS) polymer shell. The ZIF-67 core possesses a highly porous structure, coexistence of carbon and nitrogen elements, and uniform dispersion of Co species, making it an ideal template. The heteroatomic PZS polymer with decent coating ability makes it a promising coating material for creating core–shell structures. Additionally, nitrogen species in the PZS polymer could coordinate with Cu2+ to introduce extra Cu sites into the system. The Cu/Co2P@C-NS catalyst prepared from the pyrolysis of the precursor redistributes the surface charge of Co2P by additionally incorporating Cu, which effectively enhances substrate adsorption. As a result, the Cu/Co2P@C-NS catalyst demonstrates good catalytic performance in the oxidative esterification of furfuryl aldehydes. This study presents a reliable and straightforward method for preparing a non-noble-metal catalyst that exhibits high efficiency and activity in the one-pot oxidation and esterification of furfurals to methyl furoates.    

    

* Arginine Kinase Activates Arginine for Phosphorylation by Pyramidalization and Polarization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394834991
:TOPICS: Protein Arginine Methylation in Mammals, Polyamines and Biogenic Amines in Biology and Health, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00380")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394834991"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394834991"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394834991"))][Get cited by]]

OpenAlex: https://openalex.org/W4394834991 (Open access: True)
    
[[https://openalex.org/A5045450767][Fabio Falcioni]], [[https://openalex.org/A5058696234][Robert W. Molt]], [[https://openalex.org/A5025936216][Yi Jin]], [[https://openalex.org/A5039216518][Jonathan P. Waltho]], [[https://openalex.org/A5059752371][Sam Hay]], [[https://openalex.org/A5033047262][Nigel G. J. Richards]], [[https://openalex.org/A5030862337][G. Michael Blackburn]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00380  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00380][pdf]])
     
Arginine phosphorylation plays numerous roles throughout biology. Arginine kinase (AK) catalyzes the delivery of an anionic phosphoryl group (PO3–) from ATP to a planar, trigonal nitrogen in a guanidinium cation. Density functional theory (DFT) calculations have yielded a model of the transition state (TS) for the AK-catalyzed reaction. They reveal a network of over 50 hydrogen bonds that delivers unprecedented pyramidalization and out-of-plane polarization of the arginine guanidinium nitrogen (Nη2) and aligns the electron density on Nη2 with the scissile P–O bond, leading to in-line phosphoryl transfer via an associative mechanism. In the reverse reaction, the hydrogen-bonding network enforces the conformational distortion of a bound phosphoarginine substrate to increase the basicity of Nη2. This enables Nη2 protonation, which triggers PO3– migration to generate ATP. This polarization–pyramidalization of nitrogen in the arginine side chain is likely a general phenomenon that is exploited by many classes of enzymes mediating the post-translational modification of arginine.    

    

* Construction of Diazo Compounds via Catalytic [3 + 2] Annulation of Vinyldiazoacetates and Their Synthetic Applications  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394835029
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Gold Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01291")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394835029"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394835029"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394835029"))][Get cited by]]

OpenAlex: https://openalex.org/W4394835029 (Open access: False)
    
[[https://openalex.org/A5034305271][Ming Bao]], [[https://openalex.org/A5028306574][Diana Victoria Navarrete Carriola]], [[https://openalex.org/A5009053117][Daniel J. Wherritt]], [[https://openalex.org/A5058847615][Michael P. Doyle]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01291 
     
Highly selective formal [3 + 2]-cycloaddition of vinyldiazoacetates with quinone ketals and quinoneimine ketals has been accomplished at room temperature with catalytic amounts of the Brønsted acid triflimide, leading to highly functionalized diazoacetates in good yields. The vinyldiazonium ion generated by electrophilic addition to the vinylogous position of the reactant vinyldiazo compound is the key intermediate in this selective transformation. Both oximidovinyldiazoacetates and those with other vinyl substituents undergo cycloaddition reactions with quinone ketals whose products, after extended reaction times, undergo substrate-dependent 1,2-migration; catalysis by Rh2(OAc)4, HNTf2, and Sc(OTf)3 effects these 1,2-migrations to the same products. However, the products from HNTf2-catalyzed reactions between quinoneimine and oximidovinyldiazoacetates undergo Rh2(OAc)4-catalyzed 1,3-C–H insertion. 1,3-Difunctionalization products are obtained for electrophilic reactions of Eschenmoser's salt with selected vinyldiazoacetates, but with α-dibenzylaminomethyl ether, 1,6-hydride transfer reactions are observed with oximidovinyldiazoacetates.    

    

* Steric Effects on the Oxygen Reduction Reaction with Cobalt Porphyrin Atropisomers  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394835036
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Platinum-Based Cancer Chemotherapy
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01295")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394835036"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394835036"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394835036"))][Get cited by]]

OpenAlex: https://openalex.org/W4394835036 (Open access: False)
    
[[https://openalex.org/A5024693945][Chang-Jiu Li]], [[https://openalex.org/A5032545858][Haonan Qin]], [[https://openalex.org/A5004269762][Yiping Xu]], [[https://openalex.org/A5058975098][Xinyang Peng]], [[https://openalex.org/A5020575254][Wei Zhang]], [[https://openalex.org/A5023594276][Rui Cao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01295 
     
The steric effects on the oxygen reduction reaction (ORR) have been rarely studied because O2 is small in size and ORR catalysts with the only difference in steric hindrance are difficult to be designed and synthesized. Herein, we report on homogeneous ORR catalyzed by four Co porphyrin atropisomers in tetrahydrofuran with decamethylferrocene and HClO4 at 298 K. All four atropisomers are active and selective for the 2H+/2e– ORR with an activity order αααα > αααβ > ααββ > αβαβ. Kinetic studies revealed that the four atropisomers have the same ORR mechanism with proton-coupled O2 binding as the rate-determining step.    

    

* CsPbBr3 Perovskite Polyhedral Nanocrystal Photocatalysts for Decarboxylative Alkylation via Csp3–H Bond Activation of Unactivated Ethers  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394835419
:TOPICS: Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01643")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394835419"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394835419"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394835419"))][Get cited by]]

OpenAlex: https://openalex.org/W4394835419 (Open access: False)
    
[[https://openalex.org/A5089992231][Soumya Mondal]], [[https://openalex.org/A5037269746][Souvik Banerjee]], [[https://openalex.org/A5004653339][Suman Bera]], [[https://openalex.org/A5025306777][Subal Mondal]], [[https://openalex.org/A5049819018][Siba P. Midya]], [[https://openalex.org/A5050504579][Rajkumar Jana]], [[https://openalex.org/A5060178234][Rakesh Kumar Behera]], [[https://openalex.org/A5068360992][Ayan Datta]], [[https://openalex.org/A5077141160][Narayan Pradhan]], [[https://openalex.org/A5040559083][Pradyut Ghosh]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01643 
     
Halide perovskite nanocrystals have recently emerged as high-performance light-harvesting materials. They are also extensively studied for the fabrication of both light-emitting and photovoltaic devices. In comparison, their implementation as photocatalysts to trigger different organic reactions is limited. To add more diversity in catalysis, herein, different shapes and heterostructures of CsPbBr3 perovskite polyhedral nanocrystals are explored for visible-light-mediated room temperature photocatalytic Csp3–H bond-activated alkylation of cyclic ether using feedstock α,β-unsaturated acids as the keto-alkyl source. It started with the decarboxylative coupling of cinnamic acid at the α-position of tetrahydrofuran (THF) and extended to several derivatives. The facets of nanocrystals matter, and hence, differently shaped nanocrystals showed variable rates of catalytic activities. With density functional theory calculation, the surface-adsorption-induced charge carrier transfer mechanism to facilitate such reactions is established. Different semiconductors and noble metal heterostructures that quenched the emission are also compared, and their inactiveness in catalysis was also correlated to the proposed mechanism. Combining all these observations, the roles of light, catalytic surfaces, oxygen, the nature of hosts, and coupling with other material heterostructures are analyzed in detail and reported. Such reactions with Csp3–H bond activation can lead to complex chemical scaffolds, unveiling an underexplored domain of heterogeneous photocatalytic organic reactions for Csp3–Csp3 cross-coupling.    

    

* Enantioselective Synthesis of Axially Chiral Diaryl Ethers through Chiral Phosphoric Acid-Catalyzed Desymmetric Acylation with Azlactones  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394836288
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Chiroptical Spectroscopy in Organic Compound Analysis, Pharmacology of Kratom Alkaloids and Related Compounds
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01489")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394836288"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394836288"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394836288"))][Get cited by]]

OpenAlex: https://openalex.org/W4394836288 (Open access: False)
    
[[https://openalex.org/A5020281355][Jiawei Xu]], [[https://openalex.org/A5022328909][Wei Lin]], [[https://openalex.org/A5019926319][Hanliang Zheng]], [[https://openalex.org/A5005815311][Xin Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01489 
     
C–O axially chiral diaryl ethers play important roles in natural products and bioactive molecules, but because of the low rotational barrier and strict steric hindrance requirements, the catalytic asymmetric construction of axially chiral diaryl ethers still remains a challenge. Herein, we devised a strategy employing achiral azlactone for the desymmetrization of prochiral diamines under the catalysis of chiral phosphoric acid. The targeted C–O axially chiral diaryl ethers were obtained in very good yields (up to 98%) and high enantioselectivities (up to >99.5:0.5 er). The synthetic utility was demonstrated through large-scale reaction and transformations of the products. Moreover, DFT calculations were conducted to probe the origins of enantioselectivity.    

    

* Catalytic Consequences of Protons in Methanol Oxidative Dehydrogenation on Molybdenum-Based Polyoxometalate Clusters  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394837492
:TOPICS: Polyoxometalate Clusters and Materials, Chemistry and Applications of Metal-Organic Frameworks, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00440")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394837492"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394837492"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394837492"))][Get cited by]]

OpenAlex: https://openalex.org/W4394837492 (Open access: False)
    
[[https://openalex.org/A5087791506][Gui‐Xin Cai]], [[https://openalex.org/A5039229575][Ya-Huei Cathy Chin]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00440 
     
This study unravels the catalytic effects of adjacent protons in redox catalysis of bifunctional Keggin-type phosphomolybdic acid clusters (H3PMo12O40). Isolated redox sites (O*) and Brønsted acid-redox site pairs (OH/O*) catalyze methanol oxidative dehydrogenation (ODH), a redox reaction, via the identical elementary steps and the formation of the kinetically relevant [HOCH2···H···O*]‡ and [OH···HOCH2···H···O*]‡ transition states, but with different kinetic requirements, established from selective site inactivation, product tracking, dynamic pyridine/2,6-di-tert-butylpyridine titrations, and kinetic assessments. The presence of adjacent protons interacts with and stabilizes the methanol precursor in the OH···HOCH2–H···O* adsorbed state through additional H-bonding interactions by 57 kJ mol–1 in adsorption enthalpy and by 144 J mol–1 K–1 in adsorption entropy. These additional interactions, stabilizing the [OH···HOCH2···H···O*]‡ transition state, lead to a decrease in apparent methanol activation enthalpy of 50 kJ mol–1 and in activation entropy of 97 J mol–1 K–1, resulting in an overall increase in methanol ODH turnovers. The kinetic consequences of protons established here enable the rationalization of the redox reactivity on bifunctional POM clusters and display a nontraditional confinement effect to stabilize transition state energies.    

    

* Photocatalytic Regeneration of Reactive Cofactors with InP Quantum Dots for the Continuous Chemical Synthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394839944
:TOPICS: Applications of Quantum Dots in Nanotechnology, Photocatalytic Materials for Solar Energy Conversion, DNA Nanotechnology and Bioanalytical Applications
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00817")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394839944"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394839944"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394839944"))][Get cited by]]

OpenAlex: https://openalex.org/W4394839944 (Open access: False)
    
[[https://openalex.org/A5084115461][I. N. Chakraborty]], [[https://openalex.org/A5020408679][Vanshika Jain]], [[https://openalex.org/A5001758744][Pradyut Roy]], [[https://openalex.org/A5034642948][Pawan Kumar]], [[https://openalex.org/A5075584403][C. P. Vinod]], [[https://openalex.org/A5086614294][Pramod P. Pillai]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00817 
     
The shuttling of redox-active nicotinamide cofactors between the light and dark cycles is the key to the continuous production of biomass in photosynthesis. The replication of such processes in artificial photosynthetic systems demands fast photoregeneration as well as simultaneous integration of these nicotinamide cofactors into the dark cycle. Here, we report the design of an artificial photosynthetic system for the continuous production of butanol via the constant photoregeneration and consumption of nicotinamide cofactors, powered by an indium phosphide quantum dot (InP QD) photocatalyst and alcohol dehydrogenase (ADH) enzyme, respectively. A strong electrostatic attraction between the oppositely charged InP QDs and electron mediators significantly enhanced the charge extraction and utilization processes, enabling a fast (∼30 min, with a turn over frequency of ∼1333 h–1), quantitative (>99%), and selective photoregeneration of enzymatically active nicotinamide cofactors in the light cycle. These photoregenerated nicotinamide cofactors were further coupled in the dark cycle to trigger the ADH oxidoreductase enzyme for the production of butanol, via sequential as well as simultaneous light–dark cycles. The amount of butanol produced under simultaneous light–dark cycles was higher than the stoichiometric limit, proving the constant regeneration and consumption of nicotinamide cofactors in light and dark cycles, respectively. Thus, a proper design and integration of the InP QD-based photocatalytic cycle with the enzymatic cycle led to the effective electron shuttling between light and dark cycles, as seen in photosynthesis.    

    

* Synergistic Organoboron/Palladium Cocatalyzed Dehydrative Couplings of Azoles with Allylic Alcohols: A Combined Experimental and Computational Mechanistic Investigation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394840719
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Homogeneous Catalysis with Transition Metals, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01010")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394840719"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394840719"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394840719"))][Get cited by]]

OpenAlex: https://openalex.org/W4394840719 (Open access: False)
    
[[https://openalex.org/A5066370264][Matthew T. Zambri]], [[https://openalex.org/A5065875231][Teh Ren Hou]], [[https://openalex.org/A5053723702][Sofia Jdanova]], [[https://openalex.org/A5078189430][Mark S. Taylor]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01010 
     
In the presence of Pd(Xantphos) and an electron-deficient arylboronic acid cocatalyst, azoles such as pyrazoles, triazoles, tetrazoles, and purines undergo regioselective, dehydrative allylations with allylic alcohols. The boronic acid has a significant effect on both the rate and the regioselectivity of these reactions. Herein, a combined experimental and computational mechanistic study of the synergistic organoboron- and palladium-catalyzed allylation of azoles is described. Kinetic analysis and an evaluation of the effects of arylboronic acid substitution on the reaction rate point toward turnover-limiting ionization of the allylic alcohol, with Lewis acid activation by the boronic acid. Computational modeling of the reaction pathway with density functional theory indicates that allylic alcohol ionization is also the regioselectivity-determining step and that the resulting ion pair undergoes C–N bond formation through an outer-sphere mechanism. An unexpected observation of autocatalysis that emerged from the kinetic analysis motivated a study of the effects of additives, leading to the development of an improved protocol.    

    

* Photoenzymatic Redox-Neutral Radical Hydrosulfonylation Initiated by FMN  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394840950
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Applications of Photoredox Catalysis in Organic Synthesis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00350")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394840950"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394840950"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394840950"))][Get cited by]]

OpenAlex: https://openalex.org/W4394840950 (Open access: False)
    
[[https://openalex.org/A5072659443][Linye Jiang]], [[https://openalex.org/A5018100593][Dannan Zheng]], [[https://openalex.org/A5091820672][Xiaoyang Chen]], [[https://openalex.org/A5010374736][Dong Cui]], [[https://openalex.org/A5006042730][Xinyu Duan]], [[https://openalex.org/A5036036937][Zhiguo Wang]], [[https://openalex.org/A5021110763][Jingyan Ge]], [[https://openalex.org/A5035749492][Jian Xu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00350 
     
The photoinduced unnatural reactions catalyzed by flavin-dependent enzymes usually proceed through reduction pathways, which required the use of electron-sacrificial reagents. Herein, we developed a photoenzymatic redox-neutral radical hydrosulfonylation induced by oxidated flavin (FMN) with sulfinates or sulfonyl hydrazines as radical precursors. The reaction involved the excited FMN acquiring an electron from the substrate, and the resulting sulfuryl radical was captured by an alkene. It is then stereoselectively quenched by flavin semiquinone (FMNsq) through hydrogen atom transfer. This study circumvents the need for NADPH recycling systems and expands the potential reaction patterns in photobiocatalysis.    

    

* Asymmetric Photoenolization/Diels–Alder Reaction of 2-Methylbenzaldehydes and 2-Alkylbenzophenones with Chromones  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394843038
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Catalytic Oxidation of Alcohols, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01264")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394843038"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394843038"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394843038"))][Get cited by]]

OpenAlex: https://openalex.org/W4394843038 (Open access: False)
    
[[https://openalex.org/A5009580688][Yuhao Mo]], [[https://openalex.org/A5005196435][Lichao Ning]], [[https://openalex.org/A5015992117][Zhe Liu]], [[https://openalex.org/A5058580582][Liangkun Yang]], [[https://openalex.org/A5012773922][Ting Shi]], [[https://openalex.org/A5081426782][Shujuan Dong]], [[https://openalex.org/A5075038156][Qi‐Lin Zhou]], [[https://openalex.org/A5077217676][Xiaoming Feng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01264 
     
The asymmetric photoenolization/Diels–Alder reaction provides a straightforward and atom-economical route to complex chiral polycyclic rings. In comparison with well-developed transformations of 2-alkylbenzophenones, the enantioselective photoenolization/Diels–Alder reaction of 2-methylbenzaldehydes was challenging due to the shorter-lived and unstable photoenol intermediates. Herein, we present a highly enantioselective photoenolization/Diels–Alder reaction of 2-methylbenzaldehydes with chromones. Chiral N,N′-dioxide/ScIII and YbIII complexes were found to interact with both photoenol intermediates and chromones simultaneously, accelerating the Diels–Alder reaction in an efficient and stereoselective manner. Experimental studies and DFT calculations were carried out to understand the reaction mechanism and the origin of stereoselectivity. In addition, 2-alkylbenzophenones were suitable substrates. A series of chiral fused polycyclic rings with vicinal multisubstituted stereocenters were afforded in good yields and high diastereo- and enantioselectivities.    

    

* Sensitized and Self-Sensitized Photocatalytic CO2 Reduction to HCO2– and CO under Visible Light with Ni(II) CNC-Pincer Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394843717
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-04-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03787")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394843717"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394843717"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394843717"))][Get cited by]]

OpenAlex: https://openalex.org/W4394843717 (Open access: False)
    
[[https://openalex.org/A5028441979][Sonya Y. Manafe]], [[https://openalex.org/A5049477917][Nghia Le]], [[https://openalex.org/A5086937532][Ethan C. Lambert]], [[https://openalex.org/A5088330975][Christine Curiac]], [[https://openalex.org/A5031279128][Dinesh Nugegoda]], [[https://openalex.org/A5031715781][Sanjit Das]], [[https://openalex.org/A5090099495][Leigh Anna Hunt]], [[https://openalex.org/A5069899755][Fengrui Qu]], [[https://openalex.org/A5032057054][Logan M. Whitt]], [[https://openalex.org/A5026725542][Igor Fedin]], [[https://openalex.org/A5056058720][Nathan I. Hammer]], [[https://openalex.org/A5022402955][Charles Edwin Webster]], [[https://openalex.org/A5088797545][Jared H. Delcamp]], [[https://openalex.org/A5063607848][Elizabeth T. Papish]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c03787 
     
Robust earth-abundant transition metal-based photocatalysts are needed for photocatalytic CO2 reduction. A series of six Ni(II) complexes have been synthesized with a tridentate CNC pincer ligand composed of two imidazole or benzimidazole-derived N-heterocyclic carbene (NHC) rings and a pyridyl ring with different R substituents (R = OMe, Me, H) para to N of the pyridine ring. These complexes have been characterized by using spectroscopic, analytic, and crystallographic methods. The electrochemical properties of all complexes were studied by cyclic voltammetry under N2 and CO2 atmospheres. Photocatalytic reduction of CO2 to CO and HCO2– was analyzed using all of the complexes in the presence and absence of an external photosensitizer (PS). All of these complexes are active as photocatalysts for CO2 reduction with and without the presence of an external PS with appreciable turnover numbers (TONs) for formate (HCO2–) production and typically lower amounts of CO. Notably, all Ni(II) CNC-pincer complexes in this series are also active as self-sensitized photocatalysts. Complex 4Me with a benzimidazole-derived CNC pincer ligand was found to be the most active self-sensitized photocatalyst. Ultrafast transient absorption spectroscopy (TAS) experiments and computational studies were performed to understand the mechanism of these catalysts. Whereas sensitized catalysis involves halide loss to produce more active complexes, self-sensitized catalysis requires some halide to remain coordinated to allow for favorable electron transfer between the excited nickel complex and the sacrificial electron donor. This then allows the nickel complex to undergo CO2 reduction catalysis via NiI or Ni0 catalytic cycles. The two active species (NiI and Ni0) demonstrate distinct reactivity and selectivity which influences the formation of CO vs formate as the product.    

    

* Coupling Cu+ Species and Zr Single Atoms for Synergetic Catalytic Transfer Hydrodeoxygenation of 5-Hydroxymethylfurfural  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394854514
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Desulfurization Technologies for Fuels, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00763")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394854514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394854514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394854514"))][Get cited by]]

OpenAlex: https://openalex.org/W4394854514 (Open access: False)
    
[[https://openalex.org/A5022245889][Lincai Peng]], [[https://openalex.org/A5088668183][Yi Yu]], [[https://openalex.org/A5062753625][Shenghan Gao]], [[https://openalex.org/A5017261400][Miaomiao Wang]], [[https://openalex.org/A5034921129][Junhua Zhang]], [[https://openalex.org/A5001298516][Rui Zhang]], [[https://openalex.org/A5027136770][Wenlong Jia]], [[https://openalex.org/A5039154269][Yong Sun]], [[https://openalex.org/A5054925056][Huai Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00763 
     
The formation and stabilization of Cu+ species are important to develop efficient Cu-based catalysts for the catalytic transfer hydrodeoxygenation (CTHDO) of renewable biomass to value-added products but challenging. Herein, we demonstrate that the introduction of atomically dispersed Zr species into a CuOx matrix (Cu10Zr0.39Ox) greatly promoted its catalytic activity and stability for the CTHDO of 5-hydroxymethylfurfural (HMF) into 2,5-dimethylfuran (DMF). In particular, almost quantitative DMF yield could be implemented over Cu10Zr0.39Ox accompanied by an impressive DMF formation rate of 8.1 mmolDMF·gcat–1·h–1, which outperforms the existing works for the CTHDO of HMF to DMF. Experimental and theoretical observations revealed that the electronic interactions between the doped Zr atom species and CuOx enabled the generation of ample and stable Cu+ species. The single-atom Zr species also promoted the adsorption and activation of the substrates and worked synergistically with Cu+ species to boost the CTHDO of HMF by reducing the reaction energy barriers.    

    

* Halide Perovskites for Photoelectrochemical Water Splitting and CO2 Reduction: Challenges and Opportunities  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394854758
:TOPICS: Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-04-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06040")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394854758"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394854758"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394854758"))][Get cited by]]

OpenAlex: https://openalex.org/W4394854758 (Open access: True)
    
[[https://openalex.org/A5048463882][Krzysztof Bieńkowski]], [[https://openalex.org/A5065175422][Renata Solarska]], [[https://openalex.org/A5010758740][Linh Trinh]], [[https://openalex.org/A5001771649][Justyna Widera-Kalinowska]], [[https://openalex.org/A5042184842][Basheer Al‐Anesi]], [[https://openalex.org/A5014069014][Maning Liu]], [[https://openalex.org/A5064188565][G. Krishnamurthy Grandhi]], [[https://openalex.org/A5032638918][Paola Vivo]], [[https://openalex.org/A5054854930][Burcu Oral]], [[https://openalex.org/A5046670213][Beyza Yılmaz]], [[https://openalex.org/A5083517243][Ramazan Yıldırım]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06040  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06040][pdf]])
     
Photoelectrochemical water splitting and CO2 reduction provide an attractive route to produce solar fuels while reducing the level of CO2 emissions. Metal halide perovskites (MHPs) have been extensively studied for this purpose in recent years due to their suitable optoelectronic properties. In this review, we survey the recent achievements in the field. After a brief introduction to photoelectrochemical (PEC) processes, we discussed the properties, synthesis, and application of MHPs in this context. We also survey the state-of-the-art findings regarding significant achievements in performance, and developments in addressing the major challenges of toxicity and instability toward water. Efforts have been made to replace the toxic Pb with less toxic materials like Sn, Ge, Sb, and Bi. The stability toward water has been also improved by using various methods such as compositional engineering, 2D/3D perovskite structures, surface passivation, the use of protective layers, and encapsulation. In the last part, considering the experience gained in photovoltaic applications, we provided our perspective for the future challenges and opportunities. We place special emphasis on the improvement of stability as the major challenge and the potential contribution of machine learning to identify the most suitable formulation for halide perovskites with desired properties.    

    

* Coupling Waste Plastic Upgrading and CO2 Photoreduction to High-Value Chemicals by a Binuclear Re–Ru Heterogeneous Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394857095
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00444")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394857095"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394857095"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394857095"))][Get cited by]]

OpenAlex: https://openalex.org/W4394857095 (Open access: False)
    
[[https://openalex.org/A5009884211][Mei Li]], [[https://openalex.org/A5083826274][Shengbo Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00444 
     
Photocatalytically converting waste plastic to high-value chemicals is an energy-efficient and promising approach. Nonetheless, the limited photocatalytic efficiency due to the extremely low water solubility of the plastic and the excessive release of CO2 caused by overoxidation during the reaction seriously restricts its practical application. Herein, we propose a tandem process of waste Poly(ethylene terephthalate) (PET) plastic degradation and CO2 photoreduction on a chelating-ligand-anchored binuclear Re–Ru molecular heterogeneous catalyst. Specifically, waste PET plastics are depolymerized and photo-oxidized to monomers and formic acid on the molecular Ru sites, while the CO2 gas externally purged and generated in situ is photoreduced to CO with an impressive TON of 115 on the molecular Re sites. Compared with the corresponding homogeneous catalyst, the product selectivity is significantly improved from 65 to 95% in water-containing systems, and the TON is also greatly increased by nearly 19 times. Experiments and density functional theory calculations reveal that the high photocatalytic performance is attributed to the significantly enhanced light-capture capability, efficient photogenerated electron transfer between bimetallic Re–Ru sites, and substantially enhanced CO2-trapping capacity by finely regulating the chelating-ligand-based organosilica nanotube framework structure. The real-world application in nature seawater indicates that this work will provide a practical and feasible technical route for the disposal of waste plastics and mitigating carbon emissions under environmental conditions.    

    

* Key Role of CO Coverage for Chain Growth in Co-Based Fischer–Tropsch Synthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394857187
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Conversion of Biomass to Fuels and Chemicals, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04844")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394857187"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394857187"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394857187"))][Get cited by]]

OpenAlex: https://openalex.org/W4394857187 (Open access: False)
    
[[https://openalex.org/A5031688661][Konstantijn Tom Rommens]], [[https://openalex.org/A5045374317][G. T. Kasun Kalhara Gunasooriya]], [[https://openalex.org/A5047450222][Mark Saeys]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04844 
     
Fischer–Tropsch synthesis converts CO and H2 to long-chain hydrocarbons. The reaction mechanism, a combination of C–O scission, C–C coupling, and hydrogenation steps, and the nature of the active sites remain intensely debated. In this work, we report a comprehensive, dual-site microkinetic model including more than 600 reversible reactions. Our model explicitly accounts for the high CO surface coverage under the reaction conditions by including a CO saturation coverage in the underlying DFT calculations. The model predictions match experimental kinetic observations with a methane selectivity of 18%, a chain growth probability of 0.83, a turnover frequency of 0.084 s–1, and an activation energy of 107 kJ/mol. A degree of rate control analysis identifies 12 rate-controlling steps, highlighting the challenges in building compact kinetic models based on one or two rate controlling steps. In the dominant reaction mechanism, CO is activated both at B5 step sites and at the terrace sites via H- and hydroxyl-assisted pathways. Chain growth occurs on the crowded terraces predominantly via CH coupling to alkylidine chains. While B5 step sites facilitate CO activation, a small concentration of 5% is sufficient to establish a quasi-equilibrium CH coverage on the terraces and higher concentrations do not notably change the model predictions.    

    

* Plasma Catalysis for Hydrogen Production: A Bright Future for Decarbonization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394857812
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Nanomaterials, Applications of Plasma in Medicine and Biology
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05434")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394857812"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394857812"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394857812"))][Get cited by]]

OpenAlex: https://openalex.org/W4394857812 (Open access: True)
    
[[https://openalex.org/A5056416945][Ni Wang]], [[https://openalex.org/A5060530620][Hope O. Otor]], [[https://openalex.org/A5083158007][Gerardo Rivera-Castro]], [[https://openalex.org/A5043778579][Jason C. Hicks]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05434  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05434][pdf]])
     
Thermal approaches have played a dominant role in driving chemical reactions within the chemicals and fuels industries, benefiting from ongoing enhancements in efficiency via heat integration, catalyst development, and process intensification. Nevertheless, these traditional thermal approaches remain heavily reliant on fossil fuels, and there exists an urgent demand for the implementation of renewable energy technologies to synthesize fuels, commodity chemicals, and specialty chemicals. Nonthermal plasmas have gained considerable attention in recent years as a promising solution, and the prospects of combining plasmas with suitable catalysts have become even more appealing. Moreover, the evolution of nonthermal plasma catalysis approaches for the generation of clean hydrogen could be transformative in reducing greenhouse gas emissions. This comprehensive review highlights the influential contributions in plasma catalysis for hydrogen production, discusses recent advancements, and provides future prospects for researchers aiming to advance the production of clean hydrogen.    

    

* Water-Mediated Photocatalytic Coproduction of Diesel Fuel Additives and Hydrogen from Dimethyl Ether  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394869098
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01132")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394869098"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394869098"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394869098"))][Get cited by]]

OpenAlex: https://openalex.org/W4394869098 (Open access: False)
    
[[https://openalex.org/A5010933182][Shiyang Liu]], [[https://openalex.org/A5056836615][Yike Huang]], [[https://openalex.org/A5029421795][Nengchao Luo]], [[https://openalex.org/A5057209439][Jian Zhang]], [[https://openalex.org/A5050056700][Botao Qiao]], [[https://openalex.org/A5005440152][Feng Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01132 
     
Dimethyl ether (DME) coupling via prior C–H bond scission affords H2 and long-chain oxygenates that can be used as diesel fuel additives. However, the C–H bond of DME is recalcitrant, requiring activation by oxidants for subsequent C–C bond coupling, and overoxidation to CO2 by nonselective oxidants is inevitable. Here, by establishing a channel for hole transfer from the Pt/TiO2 photocatalyst to DME, the C–H bond of DME is broken, affording H2 and diesel fuel additives consisting of glycol dimethyl ether (GDE) and oligomers. Adsorbed water on Pt/TiO2 fosters hole transfer by forming hydrogen bonds with both Pt/TiO2 surface and DME. Because of the hydrogen bonding, photogenerated holes are extracted from Pt/TiO2 by water and eventually transferred to DME. As a result, the productivities of the diesel fuel and H2 are increased by 8.7 and 12.4 folds, respectively. This work provides a route to produce two kinds of fuels from an abundant feedstock.    

    

* Differentiating Plasmon-Enhanced Chemical Reactions on AgPd Hollow Nanoplates through Surface-Enhanced Raman Spectroscopy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394890917
:TOPICS: Plasmonic Nanoparticles: Synthesis, Properties, and Applications, Formation and Properties of Nanocrystals and Nanostructures, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06253")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394890917"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394890917"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394890917"))][Get cited by]]

OpenAlex: https://openalex.org/W4394890917 (Open access: True)
    
[[https://openalex.org/A5082771845][Sulin Jiao]], [[https://openalex.org/A5023697086][Kun Dai]], [[https://openalex.org/A5070469692][Lucas V. Besteiro]], [[https://openalex.org/A5038694989][Gao H]], [[https://openalex.org/A5054889888][Chuang Xuan]], [[https://openalex.org/A5004624473][Weichao Wang]], [[https://openalex.org/A5065069775][Yuan Zhang]], [[https://openalex.org/A5047178915][Chuntai Liu]], [[https://openalex.org/A5029068307][Ignacio Pérez‐Juste]], [[https://openalex.org/A5039188733][Jorge Pérez‐Juste]], [[https://openalex.org/A5017320817][Isabel Pastoriza‐Santos]], [[https://openalex.org/A5029572437][Guangchao Zheng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06253  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06253][pdf]])
     
Plasmonic photocatalysis demonstrates great potential for efficiently harnessing light energy. However, the underlying mechanisms remain enigmatic due to the transient nature of the reaction processes. Typically, plasmonic photocatalysis relies on the excitation of surface plasmon resonance (SPR) in plasmonic materials, such as metal nanoparticles, leading to the generation of high-energy or "hot electrons", albeit accompanied by photothermal heating or Joule effect. The ability of hot electrons to participate in chemical reactions is one of the key mechanisms, underlying the enhanced photocatalytic activity observed in plasmonic photocatalysis. Interestingly, surface-enhanced Raman scattering (SERS) spectroscopy allows the analysis of chemical reactions driven by hot electrons, as both SERS and hot electrons stem from the decay of SPR and occur at the hot spots. Herein, we propose a highly efficient SERS substrate based on cellulose paper loaded with either Ag nanoplates (Ag NPs) or AgPd hollow nanoplates (AgPd HNPs) for the in situ monitoring of C–C homocoupling reactions. The data analysis allowed us to disentangle the impact of hot electrons and the Joule effect on plasmon-enhanced photocatalysis. Computational simulations revealed an increase in the rate of excitation of hot carriers from single/isolated AgPd HNPs to an in-plane with a vertical stacking assembly, suggesting its promise as a photocatalyst under broadband light. In addition, the results suggest that the incorporation of Pd into an alloy with plasmonic properties may enhance its catalytic performance under light irradiation due to the collection of plasmon-excitation-induced hot electrons. This work has demonstrated the performance-oriented synthesis of hybrid nanostructures, providing a unique route to uncover the mechanism of plasmon-enhanced photocatalysis.    

    

* Functional Enhancement of Flavin-Containing Monooxygenase through Machine Learning Methodology  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394907924
:TOPICS: Electrochemical Biosensor Technology, Enzyme Immobilization Techniques, Advances in Metabolomics Research
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00826")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394907924"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394907924"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394907924"))][Get cited by]]

OpenAlex: https://openalex.org/W4394907924 (Open access: False)
    
[[https://openalex.org/A5007561814][Takuma Matsushita]], [[https://openalex.org/A5059879383][Shinji Kishimoto]], [[https://openalex.org/A5090095604][Kodai Hara]], [[https://openalex.org/A5075427398][Hiroshi Hashimoto]], [[https://openalex.org/A5048937697][Hideki Yamaguchi]], [[https://openalex.org/A5076300103][Yutaka Saitō]], [[https://openalex.org/A5035244813][Kenji Watanabe]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00826 
     
Directed evolution of enzymes often fails to obtain desirable variants because of the difficulty in exploring a huge sequence space. To obtain active variants from a very limited number of variants available at the laboratory scale, machine learning (ML)-guided engineering of enzymes is becoming an attractive methodology. However, as far as we know, there is no example of an ML-guided functional modification of flavin-containing monooxygenase (FMO). FMOs are known to catalyze a variety of oxidative reactions and are involved in the biosynthesis of many natural products (NPs). Therefore, it is expected that the ML-guided functional enhancement of FMO can contribute to the efficient development of NP derivatives. In this research, we focused on p-hydroxybenzoate hydroxylase (PHBH), a model FMO, and altered only four amino acid residues around the substrate binding site. ML models were trained with a small initial library covering only approximately 0.1% of the whole sequence space, and the ML-predicted second library was enriched with active variants. The variant with the highest activity in the second library was PHBH-MWNL (V47M, W185, L199N, and L210), whose activity was more than 100 times that of the wild-type PHBH. For elucidation of the mechanism of the observed activity enhancement, the crystal structure of PHBH-MWNL in complex with 4-hydroxy-3-methyl benzoic acid was determined. In the PHBH-MWNL crystal structure, the missing water molecule WAT2 was observed due to N199 hydrogen-bonding to WAT2, indicating that the L199N mutation contributed to the observed functional improvement by stabilizing the proton relay network proposed to be important in catalysis.    

    

* Unraveling Two Pathways for Electrocatalytic Acetonitrile Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394908661
:TOPICS: Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00621")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394908661"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394908661"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394908661"))][Get cited by]]

OpenAlex: https://openalex.org/W4394908661 (Open access: False)
    
[[https://openalex.org/A5083026796][Qi Zhang]], [[https://openalex.org/A5049982483][Zunjian Ke]], [[https://openalex.org/A5052304188][Deyan He]], [[https://openalex.org/A5075777579][Chaoning Huang]], [[https://openalex.org/A5011505911][Huan Dai]], [[https://openalex.org/A5007866518][Chaoliang Tang]], [[https://openalex.org/A5054240369][Boling Liu]], [[https://openalex.org/A5014658419][Xiangheng Xiao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00621 
     
Electrocatalytic hydrogenation (ECH) of organics offers a promising route for producing value-added chemicals. However, a deeper understanding of the reaction mechanism limits the efficient design of the catalysts. Herein, the two mechanisms are essentially identified on the Ni-based catalysts for acetonitrile hydrogenation, with a deeper understanding of their characteristics in view of their different performances. On this basis, an insight into the shift of the mechanism is proposed. Meanwhile, the optimization strategy of ECH is discovered, and the construction of Tafel sites (Ni/NiO interfaces) can greatly accelerate the kinetics, in addition to increasing the reactant coverage on the catalysts by modulating the electronic structures. Understanding the underlying mechanisms helps in manipulating the design of more efficient ECH catalysts.    

    

* Improving the Catalytic Efficiency of a GH5 Processive Endoglucanase by a Combinatorial Strategy Using Consensus Mutagenesis and Loop Engineering  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394908851
:TOPICS: Technologies for Biofuel Production from Biomass, Enzyme Immobilization Techniques, Chemical Glycobiology and Therapeutic Applications
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01083")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394908851"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394908851"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394908851"))][Get cited by]]

OpenAlex: https://openalex.org/W4394908851 (Open access: False)
    
[[https://openalex.org/A5004019691][Kemin Lv]], [[https://openalex.org/A5045787579][Xiaozhou Li]], [[https://openalex.org/A5068259214][Kequan Chen]], [[https://openalex.org/A5050197186][Bin Wu]], [[https://openalex.org/A5015789087][Bingfang He]], [[https://openalex.org/A5026257435][Gerhard Schenk]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01083 
     
No abstract    

    

* Interplay between Catalyst Corrosion and Homogeneous Reactive Oxygen Species in Electrochemical Ozone Production  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394909286
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01317")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394909286"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394909286"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394909286"))][Get cited by]]

OpenAlex: https://openalex.org/W4394909286 (Open access: False)
    
[[https://openalex.org/A5036496872][Rayan Alaufey]], [[https://openalex.org/A5002876419][Lingyan Zhao]], [[https://openalex.org/A5072256821][Andrew Lindsay]], [[https://openalex.org/A5044244066][Tana Siboonruang]], [[https://openalex.org/A5046911338][Qin Wu]], [[https://openalex.org/A5007577939][John A. Keith]], [[https://openalex.org/A5018545425][Ezra C. Wood]], [[https://openalex.org/A5024800819][Maureen H. Tang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01317 
     
Electrochemical ozone production (EOP), a six-electron water oxidation reaction, offers promising avenues for creating value-added oxidants and disinfectants. However, progress in this field is slowed by a dearth of understanding of fundamental reaction mechanisms. In this work, we combine experimental electrochemistry, spectroscopic detection of reactive oxygen species (ROS), oxygen-anion chemical ionization mass spectrometry, and computational quantum chemistry calculations to determine a plausible reaction mechanism on nickel- and antimony-doped tin oxide (Ni/Sb–SnO2, NATO), one of the most selective EOP catalysts. Antimony doping is shown to increase the conductivity of the catalyst, leading to improved electrochemical performance. Spectroscopic analysis and electrochemical experiments combined with quantum chemistry predictions reveal that hydrogen peroxide (H2O2) is a critical reaction intermediate. We propose that leached Ni4+ cations catalyze hydrogen peroxide into solution phase hydroperoxyl radicals (•OOH); these radicals are subsequently oxidized to ozone. Isotopic product analysis shows that ozone is generated catalytically from water and corrosively from the catalyst oxide lattice without regeneration of lattice oxygens. Further quantum chemistry calculations and thermodynamic analysis suggest that the electrochemical corrosion of tin oxide itself might generate hydrogen peroxide, which is then catalyzed to ozone. The proposed pathways explain both the roles of dopants in NATO and its lack of stability. Our study interrogates the possibility that instability and electrochemical activity are intrinsically linked through the formation of ROS. In doing so, we provide the first mechanism for EOP that is consistent with computational and experimental results and highlight the central challenge of instability as a target for future research efforts.    

    

* Ce4+/Ce3+ Redox-Promoted Electron Transfer for Efficient Neutral H2O2 Electrosynthesis from Two-Electron Oxygen Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394913837
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00625")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394913837"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394913837"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394913837"))][Get cited by]]

OpenAlex: https://openalex.org/W4394913837 (Open access: False)
    
[[https://openalex.org/A5058355869][Sohee Kim]], [[https://openalex.org/A5087341192][Young Jin]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00625 
     
No abstract    

    

* Mapping of the Reaction Trajectory Catalyzed by Class I Ketol-Acid Reductoisomerase  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394924580
:TOPICS: Nucleotide Metabolism and Enzyme Regulation, Macromolecular Crystallography Techniques, Metabolic Engineering and Synthetic Biology
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00958")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394924580"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394924580"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394924580"))][Get cited by]]

OpenAlex: https://openalex.org/W4394924580 (Open access: False)
    
[[https://openalex.org/A5049585978][Xin Lin]], [[https://openalex.org/A5021336171][Thierry Lonhienne]], [[https://openalex.org/A5069255829][You Lv]], [[https://openalex.org/A5048934664][Julia L. Kurz]], [[https://openalex.org/A5055730964][Ross P. McGeary]], [[https://openalex.org/A5026257435][Gerhard Schenk]], [[https://openalex.org/A5079853523][L.W. Guddat]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00958 
     
No abstract    

    

* Substantial Impact of Spin State Evolution in OER/ORR Catalyzed by Fe–N–C  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394925248
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06122")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394925248"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394925248"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394925248"))][Get cited by]]

OpenAlex: https://openalex.org/W4394925248 (Open access: False)
    
[[https://openalex.org/A5019317928][Mingyuan Yu]], [[https://openalex.org/A5022512191][Ang Li]], [[https://openalex.org/A5048140096][Erjun Kan]], [[https://openalex.org/A5086126693][Caimao Zhan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06122 
     
The Fe-embedded N-doped graphene (Fe–N–C) is the most representative single atom catalyst (SAC) that has shown great potentiality in electrocatalysis, such as oxygen reduction reaction (ORR) and oxygen evolution reaction (OER). However, the active moiety of Fe–N–C is still elusive due to contradictory experimental results. Moreover, early simulations mainly focus on the thermodynamic potential of adsorbates, while the effect of spin multiplicity receives little attention. To explore the role of spin multiplicity in electrocatalysis, we employ the constant-potential density functional theory (DFT) to systematically study the structural evolution of the high-spin (HS) and intermediate-spin (IS) FeN4 site (marked by FeN4HS/IS) in OER and ORR processes. With the consideration of spin multiplicity, our simulation shows spontaneous oxidation from Fe(II)N4IS to Fe(III)N4HS at potential U = 0.4 V versus SHE. Further simulation indicates that the FeN4IS site undergoes a sequential adsorption of *OH and *OOH along with U increase, which leads to the spin state transition from IS to HS. According to the constant-potential free energy analysis, the FeN4HS*OOH is confirmed to be the practical active centers of OER, while the FeN4HS*OH and FeN4IS are assigned to the active center of ORR in low and high overpotentials. The predicted ORR activity of FeN4HS*OH agrees with the in situ X-ray absorption near-edge spectroscopy (XANES) and 57Fe Mössbauer spectroscopy measurement by Xiao et al. [Microporous Framework Induced Synthesis of Single-Atom Dispersed Fe-NC Acidic ORR Catalyst and its In Situ Reduced Fe-N4 Active Site Identification Revealed by X-Ray Absorption Spectroscopy. ACS Catal. 2018, 8, 2824–2832]. Based on the geometry and orbital analysis, the bond length of Fe–N and coordination number of Fe center are found to have a significant impact on the d orbital splitting energy and thus induce the turnover of HS/IS stability in the OER/ORR intermediates. Our study brings comprehensive insights into the evolution of coordination and spin state in Fe–N–C, which reveals the significance of spin multiplicity in electrocatalysis and benefits further theoretical design of SACs from the perspective of spin effects.    

    

* Atroposelective Synthesis of N–N Axially Chiral Indoles and Pyrroles via NHC-Catalyzed Diastereoselective (3 + 3) Annulation Strategy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394933767
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Chiroptical Spectroscopy in Organic Compound Analysis, Cluster Algebras and Triangulated Categories
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00513")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394933767"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394933767"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394933767"))][Get cited by]]

OpenAlex: https://openalex.org/W4394933767 (Open access: False)
    
[[https://openalex.org/A5092628864][Sowmya Shree Ranganathappa]], [[https://openalex.org/A5095773612][Bhabani Sankar Dehury]], [[https://openalex.org/A5011855581][Girij Pal Singh]], [[https://openalex.org/A5024176628][Sayan Shee]], [[https://openalex.org/A5055710900][Akkattu T. Biju]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00513 
     
The synthesis of N–N axially chiral molecules in the enantiopure form has emerged as an interesting research topic primarily due to the significance and intricacy in synthesizing these molecules, especially bearing heterocyclic motifs. Herein, we disclose a method for the introduction of N–N axial chirality along with a point chiral center via the N-heterocyclic carbene (NHC)-catalyzed atroposelective synthesis of dihydropyridinone-containing indoles and pyrroles. The reaction follows a (3 + 3) annulation approach by the interception of indole/pyrrole-derived enamines with α,β-unsaturated aldehydes under oxidative NHC catalysis proceeding via the α,β-unsaturated acylazoliums. The N–N axially chiral indoles/pyrroles were formed under mild conditions in broad scope with high selectivity. In addition, preliminary DFT studies of the N–N rotational barrier of the axially chiral products were performed.    

    

* Catalytic N-Acylation for Access to N–N Atropisomeric N-Aminoindoles: Choice of Acylation Reagents and Mechanistic Insights  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394934073
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Asymmetric Catalysis, Chiroptical Spectroscopy in Organic Compound Analysis
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00720")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394934073"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394934073"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394934073"))][Get cited by]]

OpenAlex: https://openalex.org/W4394934073 (Open access: False)
    
[[https://openalex.org/A5071933599][Chaoyang Song]], [[https://openalex.org/A5074082034][Chao Pang]], [[https://openalex.org/A5022369506][Youlin Deng]], [[https://openalex.org/A5085320391][Hongneng Cai]], [[https://openalex.org/A5047164982][Xiuhai Gan]], [[https://openalex.org/A5056403313][Yonggui Robin]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00720 
     
The synthesis of N–N axial compounds containing aromatic acyl amides using common acylation reagents remains challenging. We describe a highly atropenantioselective synthesis of N-aminoindoles containing N–N axes. A chiral cyclic isothiourea is used as the sole organic catalyst in the atropenantioselective transformation of the N-acylation reaction. Aroyl chlorides have been used as acylation reagents to construct atropisomeric compounds through N-acylation. The N-aminoindole products, which bear stereogenic N–N axes, were synthesized with high yields and enantioselectivities. Some of the enantiopure N-aminoindole products exhibited promising antibacterial activities against plant pathogens.    

    

* Rational Design of Heteroatom-Doped Fe–N–C Single-Atom Catalysts for Oxygen Reduction Reaction via Simple Descriptor  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394934259
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01377")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394934259"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394934259"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394934259"))][Get cited by]]

OpenAlex: https://openalex.org/W4394934259 (Open access: False)
    
[[https://openalex.org/A5006250732][Jin Liu]], [[https://openalex.org/A5000128804][Jing Zhu]], [[https://openalex.org/A5042206403][Hanhui Xu]], [[https://openalex.org/A5006520119][Daojian Cheng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01377 
     
The coordination engineering of Fe–N–C single-atom catalysts (SACs) through introducing heteroatom dopants has attracted widespread attention in the oxygen reduction reaction (ORR). However, the common regularity for tuning the ORR activity by coordinated and environmental heteroatoms has not been sufficiently studied. Herein, we study the ORR activity on 100 Fe–N–C SACs with S, P, and B heteroatoms in diverse coordination shells by density functional theory calculations. Based on the energy level distribution of frontier orbits and molecular orbital theory, it is found that the origin of Fe–N–C ORR activity is the hybridization of molecular orbitals of Fe 3dz2, 3dyz (3dxz), and O2*/OH* intermediates, where hybrid orbitals are adjusted by coordinated and environmental S, P, and B heteroatoms, and then the protonation process of O2* or OH* intermediate is determined. Moreover, we found that the Fe–O bond length, the d-orbital gap of spin states, the d-orbital center, and the valence state of the Fe site can be used as structural descriptors to predict the ORR activity governed by the protonation of O2* or OH* intermediate as potential-determining steps. Our structural descriptors rationalize the superior ORR performance of Fe–N–C with S or B atoms doped in the second coordination shell to those in the first coordination shell, as well as the fact that the P heteroatom is more suitable as a coordinated atom than the environmental atom to enhance the ORR activity of Fe–N–C, in available experimental references. Thanks to structural descriptors, the codoping synergistic effect between P in the first coordination shell and S in the second coordination shell is predicted and confirmed to greatly enhance the ORR activity. This study provides a unified mechanistic understanding on the ORR activity trend among Fe–N–C SACs regulated by coordinated and environmental heteroatoms.    

    

* Exploring the High-Entropy Oxide Composition Space: Insights through Comparing Experimental with Theoretical Models for the Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394934324
:TOPICS: Electrocatalysis for Energy Conversion, Emergent Phenomena at Oxide Interfaces, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05915")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394934324"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394934324"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394934324"))][Get cited by]]

OpenAlex: https://openalex.org/W4394934324 (Open access: True)
    
[[https://openalex.org/A5040605968][Vladislav A. Mints]], [[https://openalex.org/A5059818244][Katrine L. Svane]], [[https://openalex.org/A5083668074][Jan Rossmeisl]], [[https://openalex.org/A5064384920][Matthias Arenz]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05915  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05915][pdf]])
     
The oxygen evolution reaction (OER) is key for the transition to a hydrogen-based energy economy. The observed activity of the OER catalysts arises from the combined effects of surface area, intrinsic activity, and stability. Therefore, alloys provide an effective platform to search for catalysts that balance these factors. In particular, high-entropy oxides provide a vast material composition space that could contain catalysts with optimal OER performance. In this work, the OER performance of the AuIrOsPdPtReRhRu composition space was modeled using an experimentally obtained dataset of 350 nanoparticles. This machine-learned model based on experimental data found the optimal catalyst to be a mixture of AuIrOsPdRu. However, as a "black-box model", it cannot explain the underlying chemistry. Therefore, density functional theory (DFT) calculations were performed to provide a complementary theoretical model with defined assumptions and, hence, a physical interpretation through comparison with the experimental model. The DFT calculations suggest that the majority of the activity originates from Ru and Ir active sites and that the addition of Pd improves the performance of these sites. However, the DFT calculation did not find the experimentally observed beneficial effects of Au and Os. Therefore, we hypothesize that the Os contributed to the performance of the tested catalysts by roughening the surface, whereas Au fulfilled the role of a structural support. Overall, it is demonstrated how machine learning can help accelerate catalyst discovery, and combining machine-learned models obtained from experimental data with models based on DFT calculations can provide important insights into the complex chemistry of OER catalysts.    

    

* Revealing Formaldehyde-Mediated Methanol-to-Aromatics Reactions over Zn-Modified Zeolites by Observing the Oxygenated and Polyunsaturated Intermediates  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394945572
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00020")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394945572"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394945572"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394945572"))][Get cited by]]

OpenAlex: https://openalex.org/W4394945572 (Open access: False)
    
[[https://openalex.org/A5035010166][Tianci Xiao]], [[https://openalex.org/A5066043510][Jinsong Luo]], [[https://openalex.org/A5058440438][Weixiong Huang]], [[https://openalex.org/A5055105861][Linfeng Lu]], [[https://openalex.org/A5031824581][Chengyuan Liu]], [[https://openalex.org/A5077453562][Yang Pan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00020 
     
No abstract    

    

* Cyclic(alkyl)(amino)carbene-Stabilized Gold Nanoparticles for Selective CO2 Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394947823
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, N-Heterocyclic Carbenes in Catalysis and Materials Chemistry
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05727")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394947823"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394947823"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394947823"))][Get cited by]]

OpenAlex: https://openalex.org/W4394947823 (Open access: False)
    
[[https://openalex.org/A5066129789][Moushakhi Ghosh]], [[https://openalex.org/A5077916079][Paramita Saha]], [[https://openalex.org/A5018495199][Sumit Roy]], [[https://openalex.org/A5008497963][Sudip Barman]], [[https://openalex.org/A5086614294][Pramod P. Pillai]], [[https://openalex.org/A5013392233][Abhishek Dey]], [[https://openalex.org/A5058082364][Shabana Khan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05727 
     
N-heterocyclic carbenes (NHCs) have recently gained significant attention as capping ligands for gold nanoparticles due to their strong σ-donation properties. It has already been established that the strong σ-donation of NHCs enriches the surface of the gold nanoparticles, which controls the catalytic activity of the metal nanoparticles. Cyclic (alkyl)(amino)carbene (CAAC) is a special class of carbene that offers stronger σ-donation than NHCs. This extremely electron-rich nature of CAAC projects it as a better surface capping ligand upon extrapolation on the Au(0) surface. In this work, we have isolated stable CAAC-stabilized AuNPs via a ligand exchange method and studied their catalytic behavior toward electrochemical CO2 reduction. These newly synthesized CAAC-stabilized AuNPs furnish a remarkable faradaic efficiency (FE) of 94% [at pH 6.3 for 2 h of controlled potential electrolysis at −0.7 V vs NHE (normal hydrogen electrode)] toward selective CO formation. Our work sets the platform for CAAC as a robust main group ligand on the surface of different metal nanoparticles, bridging the gap between main group ligands and surface chemistry.    

    

* Catalytic Bias and Redox-Driven Inactivation of the Group B FeFe Hydrogenase CpIII  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394951090
:TOPICS: Biological and Synthetic Hydrogenases: Mechanisms and Applications, Electrocatalysis for Energy Conversion, Platinum-Based Cancer Chemotherapy
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01352")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394951090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394951090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394951090"))][Get cited by]]

OpenAlex: https://openalex.org/W4394951090 (Open access: False)
    
[[https://openalex.org/A5056304450][Andrea Fasano]], [[https://openalex.org/A5007299928][Aurore Jacq‐Bailly]], [[https://openalex.org/A5012477969][Jeremy Wozniak]], [[https://openalex.org/A5064825044][Vincent Fourmond]], [[https://openalex.org/A5040444990][Christophe Léger]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01352 
     
No abstract    

    

* Boosting Hydrogen Adsorption via Manipulating the d-Band Center of Ferroferric Oxide for Anion Exchange Membrane-Based Seawater Electrolysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394953389
:TOPICS: Fuel Cell Membrane Technology, Science and Technology of Capacitive Deionization for Water Desalination, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00267")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394953389"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394953389"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394953389"))][Get cited by]]

OpenAlex: https://openalex.org/W4394953389 (Open access: False)
    
[[https://openalex.org/A5071116473][Lihui Song]], [[https://openalex.org/A5087332040][Lili Guo]], [[https://openalex.org/A5060974161][Jianfeng Mao]], [[https://openalex.org/A5017709527][Zhipeng Li]], [[https://openalex.org/A5071157860][Jiawei Zhu]], [[https://openalex.org/A5072157142][Jianping Lai]], [[https://openalex.org/A5032135658][Jing‐Qi Chi]], [[https://openalex.org/A5010746973][Lei Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00267 
     
No abstract    

    

* Effect of 6,6′-Substituents on Bipyridine-Ligated Ni Catalysts for Cross-Electrophile Coupling  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394953706
:TOPICS: Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed Sulfur Chemistry, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00827")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394953706"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394953706"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394953706"))][Get cited by]]

OpenAlex: https://openalex.org/W4394953706 (Open access: False)
    
[[https://openalex.org/A5078523497][Hanfeng Huang]], [[https://openalex.org/A5016764823][Jose L. Alvarez-Hernandez]], [[https://openalex.org/A5062709693][Nilay Hazari]], [[https://openalex.org/A5038732109][Brandon Q. Mercado]], [[https://openalex.org/A5091106686][Mycah R. Uehling]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00827 
     
A family of 4,4′-tBu2-2,2′-bipyridine (tBubpy) ligands with substituents in either the 6-position, 4,4′-tBu2-6-Me-bpy (tBubpyMe), or 6 and 6′-positions, 4,4′-tBu2-6,6′-R2-bpy (tBubpyR2; R = Me, iPr, sBu, Ph, or Mes), was synthesized. These ligands were used to prepare Ni complexes in the 0, I, and II oxidation states. We observed that the substituents in the 6 and 6′-positions of the tBubpy ligand impact the properties of the Ni complexes. For example, bulkier substituents in the 6,6′-positions of tBubpy better stabilized (tBubpyR2)NiICl species and resulted in a cleaner reduction from (tBubpyR2)NiIICl2. However, bulkier substituents hindered or prevented the coordination of tBubpyR2 ligands to Ni0(cod)2. In addition, by using complexes of the type (tBubpyMe)NiCl2 and (tBubpyR2)NiCl2 as precatalysts for different XEC reactions, we demonstrated that the 6 or 6,6′-substituents lead to major differences in the catalytic performance. Specifically, while (tBubpyMe)NiIICl2 is one of the most active catalysts reported to date for XEC and can facilitate XEC reactions at room temperature, lower turnover frequencies were observed for catalysts containing tBubpyR2 ligands. A detailed study on the catalytic intermediates (tBubpy)Ni(Ar)I and (tBubpyMe2)Ni(Ar)I revealed several factors that likely contributed to the differences in the catalytic activity. For example, whereas complexes of the type (tBubpy)Ni(Ar)I are low spin and relatively stable, complexes of the type (tBubpyMe2)Ni(Ar)I are high-spin and less stable. Furthermore, (tBubpyMe2)Ni(Ar)I captures primary and benzylic alkyl radicals more slowly than (tBubpy)Ni(Ar)I, consistent with the lower activity of the former in catalysis. Our findings will assist in the design of tailor-made ligands for Ni-catalyzed transformations.    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394961569
:TOPICS: 
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i008_1792869")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394961569"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394961569"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394961569"))][Get cited by]]

OpenAlex: https://openalex.org/W4394961569 (Open access: True)
    
, ACS catalysis. 14(8)] 2024. https://doi.org/10.1021/csv014i008_1792869  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i008_1792869][pdf]])
     
No abstract    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394961663
:TOPICS: 
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i008_1792868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394961663"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394961663"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394961663"))][Get cited by]]

OpenAlex: https://openalex.org/W4394961663 (Open access: True)
    
, ACS catalysis. 14(8)] 2024. https://doi.org/10.1021/csv014i008_1792868  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i008_1792868][pdf]])
     
No abstract    

    

* Christina Li, Serge Ruccolo, and Christo Sevov Selected to Receive the 2024 ACS Catalysis Lectureship for the Advancement of Catalytic Science  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394961800
:TOPICS: Enzyme Immobilization Techniques, Chemistry of Actinide and Lanthanide Elements, Role of Porphyrins and Phthalocyanines in Materials Chemistry
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01956")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394961800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394961800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394961800"))][Get cited by]]

OpenAlex: https://openalex.org/W4394961800 (Open access: True)
    
[[https://openalex.org/A5048301965][Cathleen M. Crudden]], ACS catalysis. 14(8)] 2024. https://doi.org/10.1021/acscatal.4c01956  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01956][pdf]])
     
ADVERTISEMENT RETURN TO ISSUEEditorialNEXTChristina Li, Serge Ruccolo, and Christo Sevov Selected to Receive the 2024 ACS Catalysis Lectureship for the Advancement of Catalytic ScienceCathleen CruddenCathleen CruddenMore by Cathleen Cruddenhttps://orcid.org/0000-0003-2154-8107Cite this: ACS Catal. 2024, 14, 8, 5987–5988Publication Date (Web):April 19, 2024Publication History Received1 April 2024Published online19 April 2024Published inissue 19 April 2024https://doi.org/10.1021/acscatal.4c01956Copyright © 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (818 KB) Get e-AlertscloseSUBJECTS:Catalysis,Catalysts,Copper,Peptides and proteins,Redox reactions Get e-Alerts    

    

* Multimodal Acridine Photocatalysis Enables Direct Access to Thiols from Carboxylic Acids and Elemental Sulfur  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394962813
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Innovations in Organic Synthesis Reactions, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01289")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394962813"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394962813"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394962813"))][Get cited by]]

OpenAlex: https://openalex.org/W4394962813 (Open access: False)
    
[[https://openalex.org/A5045502270][Arka Porey]], [[https://openalex.org/A5093030788][Seth Fremin]], [[https://openalex.org/A5077825028][Sachchida Nand]], [[https://openalex.org/A5077981619][Ramon Trevino]], [[https://openalex.org/A5036919128][William B. Hughes]], [[https://openalex.org/A5093030789][Shree Krishna Dhakal]], [[https://openalex.org/A5072745266][Việt Dũng Nguyễn]], [[https://openalex.org/A5069523960][Samuel G. Greco]], [[https://openalex.org/A5067988249][Hadi D. Arman]], [[https://openalex.org/A5039928327][Oleg V. Larionov]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01289 
     
Development of photocatalytic systems that facilitate mechanistically divergent steps in complex catalytic manifolds by distinct activation modes can enable previously inaccessible synthetic transformations. However, multimodal photocatalytic systems remain understudied, impeding their implementation in catalytic methodology. We report herein a photocatalytic access to thiols that directly merges the structural diversity of carboxylic acids with the ready availability of elemental sulfur without substrate preactivation. The photocatalytic transformation provides a direct radical-mediated segue to one of the most biologically important and synthetically versatile organosulfur functionalities, whose synthetic accessibility remains largely dominated by two-electron-mediated processes based on toxic and uneconomical reagents and precursors. The two-phase radical process is facilitated by a multimodal catalytic reactivity of acridine photocatalysis that enables both singlet excited state PCET-mediated decarboxylative carbon–sulfur bond formation and previously unknown radical reductive disulfur bond cleavage by a photoinduced hydrogen atom transfer process in the silane–triplet acridine system. The study points to a significant potential of multimodal photocatalytic systems in providing unexplored directions to previously inaccessible transformations.    

    

* Pt–Pyrrole Complex-Assisted Synthesis of Carbon-Supported Pt Intermetallics for Oxygen Reduction in Proton Exchange Membrane Fuel Cells  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394963378
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05471")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394963378"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394963378"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394963378"))][Get cited by]]

OpenAlex: https://openalex.org/W4394963378 (Open access: False)
    
[[https://openalex.org/A5057532203][Yuting Jiang]], [[https://openalex.org/A5025851882][Qing Zhang]], [[https://openalex.org/A5011770639][Jiajia Qian]], [[https://openalex.org/A5016112203][Yameng Wang]], [[https://openalex.org/A5008002256][Yongbiao Mu]], [[https://openalex.org/A5053402281][Zhiyuan Zhang]], [[https://openalex.org/A5060335470][Zheng Li]], [[https://openalex.org/A5085086661][Tianshou Zhao]], [[https://openalex.org/A5068424935][Bilu Liu]], [[https://openalex.org/A5022926692][Lin Zeng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05471 
     
Nanosized intermetallic Pt-transition metal alloys with high catalytic activity and stability are considered as promising catalysts for the oxygen reduction reaction (ORR). However, the preparation of intermetallic Pt alloy nanoparticles remains a dilemma due to their pronounced tendency for sintering at high synthesizing temperatures. Here, we have synthesized several Pt intermetallics with an average size of 4 nm by employing carbon-supported Pt–-pyrrole complex and transition metal (TM = Fe, Co, Ni) salts as precursors. Transmission electron microscope (TEM) results indicate that not only the uniform pregrowth of the Pt–pyrrole complex onto the carbon support but also the subsequently derived N-doped carbon shells (<1 nm) on the nanoparticles during annealing contribute to the formation of the nanosized intermetallics. Additional characterization suggests that the intermetallic alloy structure endows the catalyst (PtCo@Pt/C-6) with a downshifted Pt d-band center, which implies the weakened adsorption of the ORR intermediates on the Pt alloy, thus facilitating the ORR kinetics. The fuel cell with the as-prepared PtCo@Pt/C-6 catalyst displays a rated peak power density of 1.1 W/cm2 at 0.67 V (H2/air) and a mass activity of 0.49 A/mgPt at 0.9 V, exceeding the targets of the US Department of Energy (1.0 W/cm2 and 0.44 A/mgPt, respectively). This method demonstrates great potentials for the scalable synthesis of PtTM/C catalysts with high ORR performance and promoting their applications in PEMFCs.    

    
