#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sun Dec 22 01:27:07 2024

Found 39 results from 2024-12-15 to 2024-12-22
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Discovery and Synthetic Applications of a NAD(P)H-Dependent Reductive Aminase from Rhodococcus erythropolis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405431243
:TOPICS: Amino Acid Enzymes and Metabolism, Biochemical and Molecular Research, Chemical Reactions and Isotopes
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04935")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405431243"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405431243"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405431243"))][Get cited by]]

OpenAlex: https://openalex.org/W4405431243 (Open access: True)
    
[[https://openalex.org/A5082420951][Ewald P. J. Jongkind]], [[https://openalex.org/A5110114882][J. Domenech]], [[https://openalex.org/A5115459782][Arthur Govers]], [[https://openalex.org/A5015527534][Marcel van den Broek]], [[https://openalex.org/A5033414409][Jean‐Marc Daran]], [[https://openalex.org/A5003700886][Gideon Grogan]], [[https://openalex.org/A5091020378][Caroline E. Paul]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04935 
     
Reductive amination is one of the most synthetically direct routes to access chiral amines. Several Imine Reductases (IREDs) have been discovered to catalyze reductive amination (Reductive Aminases or RedAms), yet they are dependent on the expensive phosphorylated nicotinamide adenine dinucleotide cofactor NADPH and usually more active at basic pH. Here, we describe the discovery and synthetic potential of an IRED from Rhodococcus erythropolis (RytRedAm) that catalyzes reductive amination between a series of medium to large carbonyl and amine compounds with conversions of up to >99% and 99% enantiomeric excess at neutral pH. RytRedAm catalyzes the formation of a substituted γ-lactam and N-methyl-1-phenylethanamine with stereochemistry opposite to that of fungal RedAms, giving the (S)-enantiomer. This enzyme remarkably uses both NADPH and NADH cofactors with KM values of 15 and 247 μM and turnover numbers kcat of 3.6 and 9.0 s–1, respectively, for the reductive amination of hexanal with allylamine. The crystal structure obtained provides insights into the flexibility to also accept NADH, with residues R35 and I69 diverging from that of other IREDs/RedAms in the otherwise conserved Rossmann fold. RytRedAm thus represents a subfamily of enzymes that enable synthetic applications using NADH-dependent reductive amination to access complementary chiral amine products.    

    

* Construction of Chiral C2-Quaternary Indolines via Palladium-Catalyzed Decarboxylative Asymmetric Amination  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405431372
:TOPICS: Asymmetric Hydrogenation and Catalysis, Catalytic C–H Functionalization Methods, Asymmetric Synthesis and Catalysis
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05763")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405431372"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405431372"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405431372"))][Get cited by]]

OpenAlex: https://openalex.org/W4405431372 (Open access: False)
    
[[https://openalex.org/A5028071791][Mingjun Lv]], [[https://openalex.org/A5102485257][Xinhui Yu]], [[https://openalex.org/A5089618971][Jitian Liu]], [[https://openalex.org/A5001092337][Xiaoxun Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05763 
     
No abstract    

    

* Chemically Bonded Schottky Junction for Efficient N2 Photofixation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405431397
:TOPICS: Ammonia Synthesis and Nitrogen Reduction, CO2 Reduction Techniques and Catalysts, Catalytic Processes in Materials Science
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04443")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405431397"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405431397"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405431397"))][Get cited by]]

OpenAlex: https://openalex.org/W4405431397 (Open access: False)
    
[[https://openalex.org/A5113264380][Yin Bi]], [[https://openalex.org/A5040559566][Yuan Fang]], [[https://openalex.org/A5108582360][Ling Yuan]], [[https://openalex.org/A5100343408][Jiaxin Li]], [[https://openalex.org/A5061724324][Chaoqi Zhang]], [[https://openalex.org/A5030440986][Pengyue Shan]], [[https://openalex.org/A5051585157][Xinchan Zhang]], [[https://openalex.org/A5038072194][Chao Liu]], [[https://openalex.org/A5009277202][Chengzhong Yu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04443 
     
No abstract    

    

* Balancing Activity and Stability through Compositional Engineering of Ternary PtNi–Au Alloy ORR Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405439103
:TOPICS: Electrocatalysts for Energy Conversion, Catalytic Processes in Materials Science, Catalysis and Hydrodesulfurization Studies
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05269")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405439103"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405439103"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405439103"))][Get cited by]]

OpenAlex: https://openalex.org/W4405439103 (Open access: True)
    
[[https://openalex.org/A5037568967][Xianxian Xie]], [[https://openalex.org/A5028984197][Valentín Briega‐Martos]], [[https://openalex.org/A5067024627][Pere Alemany]], [[https://openalex.org/A5003898057][Athira Lekshmi Mohandas Sandhya]], [[https://openalex.org/A5079336887][Tomáš Škála]], [[https://openalex.org/A5006021426][Miquel Gamón Rodríguez]], [[https://openalex.org/A5007700085][Jaroslava Nováková]], [[https://openalex.org/A5019731183][Milan Dopita]], [[https://openalex.org/A5043951136][Michael Vorochta]], [[https://openalex.org/A5061069452][Albert Bruix]], [[https://openalex.org/A5073666601][Serhiy Cherevko]], [[https://openalex.org/A5032114586][Konstantin M. Neyman]], [[https://openalex.org/A5101902616][Iva Matolı́nová]], [[https://openalex.org/A5039409285][Ivan Khalakhan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05269 
     
No abstract    

    

* Biocatalytic Cleavage of para-Acetoxy Benzyl Ethers: Application to Protecting Group Chemistry  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443211
:TOPICS: Microbial Metabolic Engineering and Bioproduction, Enzyme Catalysis and Immobilization, Microbial bioremediation and biosurfactants
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04257")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443211"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443211"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443211"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443211 (Open access: True)
    
[[https://openalex.org/A5036178758][Ben Ashley]], [[https://openalex.org/A5115464954][Chiara Demingo]], [[https://openalex.org/A5005328052][H.J. Rozeboom]], [[https://openalex.org/A5115464955][Niccoló Bianciardi]], [[https://openalex.org/A5095837864][Tomás Dunleavy]], [[https://openalex.org/A5035141073][Jacob‐Jan Haaksma]], [[https://openalex.org/A5017006950][Yiming Guo]], [[https://openalex.org/A5083203989][Marco W. Fraaije]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04257 
     
Aryl ethers are ubiquitous protecting groups of alcohols and amines in organic chemistry. This is owed to the simplicity of their appendage to molecules and the robust protection afforded. However, aryl ethers and amines can be challenging to cleave, often requiring harsh and unselective reductive conditions. We report the structure-based engineering of a promiscuous, ether-cleaving vanillyl alcohol oxidase-type biocatalyst for activity on a wide range of para-hydroxy benzyl ethers. Two superior quadruple mutants are identified with improved kinetics and substrate scope. One evolved variant and two predecessors are crystallized, and their structures resolved to 2.8–1.5 Å, revealing a significant increase in the volume and flexibility of the active site cavity. To illustrate the potential usefulness of the engineered biocatalysts, one is later coupled with another biocatalyst in a cascade reaction to catalyze the selective cleavage of an uncommon aryl ether protecting group, para-acyloxy benzyl ethers, in good yield and under mild conditions.    

    

* DFT-Assisted Atroposelective Construction of Indole-Fused N-Heteroaromatic Frameworks through Palladium-Catalyzed C–H Imidoylation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443243
:TOPICS: Axial and Atropisomeric Chirality Synthesis, Molecular spectroscopy and chirality, Sphingolipid Metabolism and Signaling
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06720")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443243"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443243"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443243"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443243 (Open access: False)
    
[[https://openalex.org/A5100632471][Xilong Wang]], [[https://openalex.org/A5102812134][Jiali Xu]], [[https://openalex.org/A5037361855][Yu Luo]], [[https://openalex.org/A5112876938][Yuanyu Wang]], [[https://openalex.org/A5046926733][Jun Huang]], [[https://openalex.org/A5108264438][Qiang Zhu]], [[https://openalex.org/A5019882694][Shuang Luo]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06720 
     
No abstract    

    

* Electronic Structure Modulated by B-Doped Cu Promotes Electrocatalytic Nitrate Reduction for Ammonia Production  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443274
:TOPICS: Ammonia Synthesis and Nitrogen Reduction, Caching and Content Delivery, Advanced Photocatalysis Techniques
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05954")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443274"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443274"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443274"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443274 (Open access: False)
    
[[https://openalex.org/A5019708174][Jia-Jia Wang]], [[https://openalex.org/A5102616845][Zhuodong Ou]], [[https://openalex.org/A5068274551][Chenglin Dong]], [[https://openalex.org/A5090722028][Mengying Su]], [[https://openalex.org/A5029454973][Amjad Ali]], [[https://openalex.org/A5087272960][Artem V. Kuklin]], [[https://openalex.org/A5053665869][Hans Ågren]], [[https://openalex.org/A5072409817][Glib Baryshnikov]], [[https://openalex.org/A5100355901][Yang Liu]], [[https://openalex.org/A5057904713][Xue Zhao]], [[https://openalex.org/A5039480955][Haibo Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05954 
     
No abstract    

    

* Fine-Tuning the Active Phases of CoFe Alloy Carbides for Boosting Olefin Synthesis from CO2 Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443281
:TOPICS: Catalysts for Methane Reforming, Catalysis and Hydrodesulfurization Studies, Catalysis for Biomass Conversion
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06112")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443281"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443281"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443281"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443281 (Open access: False)
    
[[https://openalex.org/A5100389784][Na Liu]], [[https://openalex.org/A5019080822][Qixiang Fan]], [[https://openalex.org/A5072413669][Jian Wei]], [[https://openalex.org/A5100459824][Guanghui Zhang]], [[https://openalex.org/A5100742185][Jian Sun]], [[https://openalex.org/A5100339868][Wenhui Li]], [[https://openalex.org/A5100439357][Chunshan Song]], [[https://openalex.org/A5108083619][Xinwen Guo]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06112 
     
The rational design of highly efficient Co–Fe bimetallic catalysts is highly desirable for CO2 hydrogenation to olefins as an important alternative for traditional petroleum cracking technology. The treatment of carburization to construct the active phases stands out. Herein, the composition of active CoFe alloy carbide catalysts consisting of χ-(CoxFe1–x)5C2 and θ-(CoxFe1–x)3C phases was fine-tuned by altering the carburization environment. The synergistic effect between the dual components was optimized to improve the CO2 activation and C–C coupling capacity. The appropriate carburization degree and phase composition of CoFe alloy carbides are favorable for enhancing the space-time yield (STY) of C2+ olefins, up to 328.1 mg gcat–1 h–1 on the CoFe catalyst carburized in H2/CO = 2 at 320 °C for 8 h. This work provides useful guidelines for regulating product distribution in the design and synthesis of highly efficient catalysts.    

    

* Manipulating Metal Cations Microenvironment for Highly Selective Electrochemical Water Oxidation to Hydrogen Peroxide  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443310
:TOPICS: Electrocatalysts for Energy Conversion, Electrochemical Analysis and Applications, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06189")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443310"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443310"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443310"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443310 (Open access: False)
    
[[https://openalex.org/A5000832086][Lanke Luo]], [[https://openalex.org/A5100365304][Mingxuan Li]], [[https://openalex.org/A5109726017][Haohai Dong]], [[https://openalex.org/A5046902345][Haomin Jiang]], [[https://openalex.org/A5111258789][Huatian Chen]], [[https://openalex.org/A5108951122][Jiongjun Wu]], [[https://openalex.org/A5069744702][Peiyuan Su]], [[https://openalex.org/A5100319948][Xinyue Zhang]], [[https://openalex.org/A5100443726][Lin Chen]], [[https://openalex.org/A5008007560][Zemin Sun]], [[https://openalex.org/A5086427768][Liu Lin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06189 
     
No abstract    

    

* Ag/Co-Bimetallic Cooperation in the C–H Functionalization of Aliphatic Amides with Propiolic Acids  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443360
:TOPICS: Catalytic C–H Functionalization Methods, Asymmetric Hydrogenation and Catalysis, Coordination Chemistry and Organometallics
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05918")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443360"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443360"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443360"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443360 (Open access: False)
    
[[https://openalex.org/A5000963221][Andrés García‐Viada]], [[https://openalex.org/A5115465000][Emma Duro]], [[https://openalex.org/A5098215784][Celia Sánchez‐González]], [[https://openalex.org/A5064338968][Inés Alonso]], [[https://openalex.org/A5049477986][Nuria Rodríguez]], [[https://openalex.org/A5014883363][Javier Adrio]], [[https://openalex.org/A5065650028][Juan C. Carretero]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05918 
     
We herein describe the high-valent cobalt-catalyzed C(sp3)–H functionalization of amide derivatives with silver acetylides generated in situ. The reaction proceeds under kinetic control at 60 °C, with a catalyst loading of 5 mol %. These extraordinarily mild conditions for Co-catalysis enable the synthesis of 5-(Z)-ethylidene pyrrolidin-2-one derivatives in good yield and selectivity. Density functional theory calculations have revealed a unique mechanism involving Co–Ag bimetallic species, rationalizing the nature of the catalytically active species and the role of each additive.    

    

* Interfacial Synergy of Ni Single Atom/Clusters and MXene Enabling Semiconductor Quantum Dots Based Superior Photoredox Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443444
:TOPICS: MXene and MAX Phase Materials, Advanced Photocatalysis Techniques, Nanocluster Synthesis and Applications
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05842")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443444"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443444"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443444"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443444 (Open access: False)
    
[[https://openalex.org/A5086250289][Ming–Yu Qi]], [[https://openalex.org/A5114229268][Wei-Yun Xiao]], [[https://openalex.org/A5072397552][Marco Conte]], [[https://openalex.org/A5066033097][Zi‐Rong Tang]], [[https://openalex.org/A5026347224][Yi‐Jun Xu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05842 
     
No abstract    

    

* Unraveling the Impact of Niobia Promotion on Pt/Al2O3 for Enhanced Catalytic Performance in Benzyltoluene Reactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443456
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Hydrodesulfurization Studies, Catalysis and Oxidation Reactions
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03543")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443456"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443456"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443456"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443456 (Open access: False)
    
[[https://openalex.org/A5114048532][Jun Ki Yoo]], [[https://openalex.org/A5000810626][Seok-Ho Lee]], [[https://openalex.org/A5112136704][Tae In Park]], [[https://openalex.org/A5100398118][Jeong Yong Lee]], [[https://openalex.org/A5076133938][Kwan‐Young Lee]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03543 
     
No abstract    

    

* Understanding the Unique Selectivity of Cobalt Phthalocyanine in Multielectron Reduction of Carbon Dioxide  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443459
:TOPICS: CO2 Reduction Techniques and Catalysts, Catalytic Processes in Materials Science, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05744")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443459"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443459"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443459"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443459 (Open access: False)
    
[[https://openalex.org/A5100780082][Hengyu Li]], [[https://openalex.org/A5102946528][Yangfan Shao]], [[https://openalex.org/A5032631479][Zhichao Zhang]], [[https://openalex.org/A5107050925][Muhammad N. Tahir]], [[https://openalex.org/A5079936107][Tingzheng Hou]], [[https://openalex.org/A5051784756][Lin Gan]], [[https://openalex.org/A5041275599][Feng Ding]], [[https://openalex.org/A5070982282][Jia Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05744 
     
No abstract    

    

* Facet-Controlled Pt3M Alloys as Enhanced Catalysts for Ammonia Oxidation Reaction: A Combined Theoretical and Experimental Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405443460
:TOPICS: Ammonia Synthesis and Nitrogen Reduction, Catalytic Processes in Materials Science, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05857")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405443460"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405443460"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405443460"))][Get cited by]]

OpenAlex: https://openalex.org/W4405443460 (Open access: False)
    
[[https://openalex.org/A5103159795][Jaeyoung Yoo]], [[https://openalex.org/A5017443019][Jungwoo Choi]], [[https://openalex.org/A5103029139][Su-Yeon Choi]], [[https://openalex.org/A5101696473][Changsoo Lee]], [[https://openalex.org/A5007750616][Hyuck Mo Lee]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05857 
     
No abstract    

    

* Photothermal-Enhanced H2 Generation and Lignin Upgrading to Jet Fuel Precursor over Lignin–Carbon-Bridged Pt/NixP  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405457504
:TOPICS: Catalysis and Hydrodesulfurization Studies, Catalytic Processes in Materials Science, Lignin and Wood Chemistry
:PUBLICATION_DATE: 2024-12-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04888")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405457504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405457504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405457504"))][Get cited by]]

OpenAlex: https://openalex.org/W4405457504 (Open access: False)
    
[[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5063418082][Jiawen Liao]], [[https://openalex.org/A5071160405][Xueqing Qiu]], [[https://openalex.org/A5079837697][Xuliang Lin]], [[https://openalex.org/A5103110216][Yanlin Qin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04888 
     
Merging efficient H2 generation with high-value utilization of biomass via a solar-driven catalytic redox technology presents a promising strategy for overall biorefinery. As the most abundant aromatic polymer in nature, lignin is considered an ideal sacrificial agent to enhance the reductive H2 evolution, coproducing high-value aromatic chemicals/fuels instead of waste carbon oxides. However, the development of an energy-efficient and productive photocatalysis system remains challenging. Herein, a photothermal cocatalytic technology was developed for synergistic enhancement on the redox activities. A feasible synthesis method was proposed to precisely construct a light-sensitive heterojunction between active Pt and NixP, bridged by technical lignin–carbon. Benefiting from the advanced modulation effect of lignin–carbon, accelerated electron transfer and active structural rearrangement were realized on the defective catalyst surface. Combining an optimized band gap structure, H2 evolution efficiency was boosted under photothermal cocatalysis and showed a splendid H2 evolution rate of 10.7 mmol·gcat–1·h–1 based on a lignin-derived monomer (vanillyl alcohol), 15-fold higher than either photocatalysis or thermocatalysis alone. The H2 evolution obtained from technical lignin (2.9 mmol·gcat–1·h–1) surpassed the existing level of biomass. Meanwhile, the controllable coupling of lignin or its derived monomers was enhanced simultaneously, yielding C13–C16 dimers (43.8% yield) from the lignin-derived monomer via Cα node, which act as ideal precursors for jet fuel. This work advances lignin upgrading for hydrogen energy and biofuels.    

    

* Oxygen Reduction Reaction on Pyridinic Nitrogen-Functionalized Carbon: Active Site Quantification and Effects of Lewis Basicity  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405464001
:TOPICS: Electrocatalysts for Energy Conversion, Fuel Cells and Related Materials, Semiconductor materials and devices
:PUBLICATION_DATE: 2024-12-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05289")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405464001"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405464001"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405464001"))][Get cited by]]

OpenAlex: https://openalex.org/W4405464001 (Open access: False)
    
[[https://openalex.org/A5011995432][Zhongyao Zhang]], [[https://openalex.org/A5054620175][Feiting Zhang]], [[https://openalex.org/A5036686064][Zhongxin Song]], [[https://openalex.org/A5100433989][Lei Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05289 
     
Metal-free carbon materials functionalized with pyridinic nitrogen groups exhibit promising electrocatalytic activity for the oxygen reduction reaction (ORR). However, not all pyridinic nitrogen groups are equally active for the ORR, which remains ambiguous and requires rigorous quantification and differentiation by their basicity. Here, we introduce the potentiometric titration method for identifying and quantifying nitrogen-containing groups on carbon materials by their Lewis basicity and reactivity in characteristic tests. Various carbon materials are functionalized with nitrogen heteroatoms. Potentiometric titration, X-ray photoelectron spectroscopy (XPS), and elemental analysis suggest that a significant amount of pyridinic nitrogen groups are buried within the bulk structures and cannot be accessed by protons and oxygen molecules. Besides, pyridinic nitrogen functions located adjacent to other nitrogen atoms exhibit weaker basicity due to strong inductive or resonance effects, resulting in a negligible contribution to the ORR activity. ORR measurements under alkaline conditions suggest that the titratable pyridinic nitrogen groups are essential for the active site (or site pair), and kinetic current density is directly proportional to the density of titratable pyridinic nitrogen groups. Furthermore, the turnover frequency for the ORR increases with the Lewis basicity of the pyridinic nitrogen groups for all investigated carbon materials in alkaline and acidic conditions. Density functional theory (DFT) calculations suggest that the ORR occurs on the carbon atoms adjacent to pyridinic nitrogen groups. Pyridinic nitrogen with a higher Lewis basicity can affect adjacent carbon atoms more efficiently, which stabilizes the key intermediates for the ORR and decreases the activation barrier. This work provides an informative and convenient way for characterizing nitrogen-containing groups on carbon materials, especially in quantifying the active pyridinic nitrogen sites for the ORR.    

    

* Sustainable H2 Production from Lignocellulosic Biomass over MoS2 Modified Sulfur Vacancy Enriched ZnIn2S4 Photocatalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405474939
:TOPICS: Advanced Photocatalysis Techniques, Electrocatalysts for Energy Conversion, Catalysis and Hydrodesulfurization Studies
:PUBLICATION_DATE: 2024-12-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05707")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405474939"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405474939"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405474939"))][Get cited by]]

OpenAlex: https://openalex.org/W4405474939 (Open access: False)
    
[[https://openalex.org/A5040707894][Jiping Tang]], [[https://openalex.org/A5101435389][Yan Chen]], [[https://openalex.org/A5101627513][Ziyi Wang]], [[https://openalex.org/A5114225143][Yun-Hui Hu]], [[https://openalex.org/A5100329212][Jiahao Wang]], [[https://openalex.org/A5085458165][Liang Bao]], [[https://openalex.org/A5059995024][Zong‐Yan Zhao]], [[https://openalex.org/A5028369122][Yong‐Jun Yuan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05707 
     
Exploring visible-light-responsive photocatalysts for photocatalytic lignocellulosic biomass-to-H2 conversion remains a glamorous but challenging goal because the photogenerated holes cannot directly transfer to biomass owing to the absence of a charge transfer channel. Herein, we design ZnIn2S4 nanosheets with abundant sulfur vacancy (VS-ZnIn2S4) as visible light responsive photocatalysts for photocatalytic H2 production from lignocellulosic biomass in the presence of MoS2 as the cocatalyst. In this smartly designed photocatalysts, the sulfur vacancy in ZnIn2S4 reduces the energy barrier of •OH generation reaction and results in the fast dynamics for the generation of •OH, which acts as the crucial species for the oxygenolysis of lignocellulosic biomass. As expected, the H2 generation rate of the optimized MoS2/VS-ZnIn2S4 photocatalyst in α-cellulose and bamboo powder aqueous solution achieves 1572 and 133 μmol·g–1·h–1, respectively. This study validates the feasibility of sulfur vacancy to boost visible light photocatalytic conversion of lignocellulosic biomass into H2 fuel.    

    

* Recent Developments and Challenges in the Enzymatic Formation of Nitrogen–Nitrogen Bonds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405486704
:TOPICS: Enzyme Catalysis and Immobilization, Amino Acid Enzymes and Metabolism, Polyamine Metabolism and Applications
:PUBLICATION_DATE: 2024-12-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05268")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405486704"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405486704"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405486704"))][Get cited by]]

OpenAlex: https://openalex.org/W4405486704 (Open access: True)
    
[[https://openalex.org/A5115512755][Charitomeni Angeli]], [[https://openalex.org/A5115512756][Sara Atienza-Sanz]], [[https://openalex.org/A5102773313][Simon Schröder]], [[https://openalex.org/A5103250669][Alexander Hein]], [[https://openalex.org/A5100405250][Yongxin Li]], [[https://openalex.org/A5115512757][Alexander Argyrou]], [[https://openalex.org/A5026323739][Angelina Osipyan]], [[https://openalex.org/A5031922781][Henrik Terholsen]], [[https://openalex.org/A5030580114][Sandy Schmidt]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05268 
     
The biological formation of nitrogen–nitrogen (N–N) bonds represents intriguing reactions that have attracted much attention in the past decade. This interest has led to an increasing number of N–N bond-containing natural products (NPs) and related enzymes that catalyze their formation (referred to in this review as NNzymes) being elucidated and studied in greater detail. While more detailed information on the biosynthesis of N–N bond-containing NPs, which has only become available in recent years, provides an unprecedented source of biosynthetic enzymes, their potential for biocatalytic applications has been minimally explored. With this review, we aim not only to provide a comprehensive overview of both characterized NNzymes and hypothetical biocatalysts with putative N–N bond forming activity, but also to highlight the potential of NNzymes from a biocatalytic perspective. We also present and compare conventional synthetic approaches to linear and cyclic hydrazines, hydrazides, diazo- and nitroso-groups, triazenes, and triazoles to allow comparison with enzymatic routes via NNzymes to these N–N bond-containing functional groups. Moreover, the biosynthetic pathways as well as the diversity and reaction mechanisms of NNzymes are presented according to the direct functional groups currently accessible to these enzymes.    

    

* Reactivity and Mechanism of Recoverable Pd1@C3N4 Single-Atom Catalyst in Buchwald–Hartwig Aminations  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405494682
:TOPICS: Catalytic Cross-Coupling Reactions, Nanomaterials for catalytic reactions, Catalytic C–H Functionalization Methods
:PUBLICATION_DATE: 2024-12-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05134")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405494682"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405494682"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405494682"))][Get cited by]]

OpenAlex: https://openalex.org/W4405494682 (Open access: True)
    
[[https://openalex.org/A5003291079][Georgios Giannakakis]], [[https://openalex.org/A5066101988][Marc‐Eduard Usteri]], [[https://openalex.org/A5041768941][Aram L. Bugaev]], [[https://openalex.org/A5060916943][Andrea Ruiz‐Ferrando]], [[https://openalex.org/A5081644765][Dario Faust Akl]], [[https://openalex.org/A5100605805][Núria López]], [[https://openalex.org/A5014594623][Serena Fantasia]], [[https://openalex.org/A5083525289][Kurt Püntener]], [[https://openalex.org/A5007349453][Javier Pérez‐Ramírez]], [[https://openalex.org/A5012059689][Sharon Mitchell]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05134 
     
Buchwald–Hartwig (BH) aminations are crucial for synthesizing arylamine motifs in numerous bioactive molecules and fine chemicals. While homogeneous palladium complexes can be effective catalysts, their high costs and environmental impact motivate the search for alternative approaches. Heterogeneous palladium single-atom catalysts (SAC) offer promising recoverable alternatives in C–C cross-couplings. Yet their use in C–N couplings remains unexplored, and mechanistic insights into amine coupling with aryl halides over solid surfaces that could guide catalyst design are lacking. Here, we demonstrate that palladium atoms coordinated to well-defined heptazinic cavities of graphitic carbon nitride (Pd1@C3N4) deliver practically relevant yields for BH couplings across various aryl halides and amines, exhibiting persistent activity and negligible leaching over several cycles. Notably, Pd1@C3N4 shows comparable or superior activity with certain aryl chlorides to bromides, alongside high chemoselectivity for amines over amides. In situ X-ray absorption spectroscopy analyses supported by density functional theory simulations identify the concerted role of the ligand and the C3N4 host in determining the performance, with a Pd(II) nominal oxidation state observed under all coupling conditions. Complementary structural and kinetic studies highlight a distinct reaction mechanism than that typically reported for homogeneous catalysts. These findings offer key insights for designing recyclable SAC for BH coupling, setting the basis for extending the scope toward more complex industrial targets.    

    

* Dynamics of Fe Adsorption and Desorption from CoOxHy During Oxygen Evolution Reaction Electrocatalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405500679
:TOPICS: Electrocatalysts for Energy Conversion, Advanced battery technologies research, Electrochemical Analysis and Applications
:PUBLICATION_DATE: 2024-12-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04777")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405500679"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405500679"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405500679"))][Get cited by]]

OpenAlex: https://openalex.org/W4405500679 (Open access: False)
    
[[https://openalex.org/A5100396456][Lu Liu]], [[https://openalex.org/A5004141512][Liam Twight]], [[https://openalex.org/A5031292832][Shibo Xi]], [[https://openalex.org/A5014526265][Yingqing Ou]], [[https://openalex.org/A5032458792][Shannon W. Boettcher]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04777 
     
Iron plays a central and critical role in the water oxidation mechanism and the activity of transition-metal oxides and (oxy)hydroxides. Tracking Fe dynamics (deposition/dissolution/electrolyte transport) and unraveling the chemistries of various Fe active sites under oxygen-evolution reaction (OER) conditions are important for catalyst design, particularly for applications in alkaline electrolysis. Here, we use CoOxHy thin films as a platform to investigate Fe transport and reactivity at the catalyst-electrolyte interface and its impact on OER activity. We find that the deposition/dissolution of the surface-absorbed Fe species is governed by the transport of soluble Fe species and applied potential. Soluble Fe species in the electrolyte adsorb on CoOxHy under stirred electrolyte conditions. Accelerated Fe desorption is observed with a more-positive OER potential. The surface-localized Fe sites generated by absorption from soluble Fe species have a higher OER turnover frequency (TOFFe) compared to Fe in codeposited CoFeOxHy films. Operando X-ray absorption spectroscopy shows structural similarity between reference Fe oxyhydroxides and surface Fe sites on CoOxHy, contrasting with Fe sites within the CoOxHy structure made by codeposition, where Fe shows a different apparent X-ray absorption edge energy. The OER activity of the surface-absorbed Fe decreased by Fe desorption but was recoverable by redepositing Fe species under non-OER conditions.    

    

* Combined Kinetic and Computational Analysis of the Palladium-Catalyzed Formylation of Aryl Bromides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405508167
:TOPICS: Chemical Reactions and Isotopes, Asymmetric Hydrogenation and Catalysis, Catalytic Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05324")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405508167"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405508167"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405508167"))][Get cited by]]

OpenAlex: https://openalex.org/W4405508167 (Open access: True)
    
[[https://openalex.org/A5069856610][Georgina Rai]], [[https://openalex.org/A5081093844][Lee J. Edwards]], [[https://openalex.org/A5085043324][Rebecca L. Greenaway]], [[https://openalex.org/A5045368482][Philip W. Miller]], [[https://openalex.org/A5020862367][Katherine M. P. Wheelhouse]], [[https://openalex.org/A5034836508][Mark R. Crimmin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05324 
     
Aryl aldehydes are key synthetic intermediates in the manufacturing of active pharmaceutical ingredients. They are generated on scale (>1000 kg) through the palladium-catalyzed formylation of aryl bromides using syngas (CO/H2). The best-in-class catalyst system for this reaction employs di-1-adamantyl-n-butylphosphine (cataCXium A), palladium(II) acetate, and tetramethylethylenediamine. Despite nearly 20 years since its initial report, a mechanistic understanding of this system remains incomplete. Here, we use automation, kinetic analysis, and DFT calculations to develop a mechanistic model for this best-in-class catalyst. We suggest that a combination of the migratory insertion step and dihydrogen activation step is likely involved in the turnover-limiting sequence. The reaction kinetics are responsive to the nature of the substrate, with electron-rich aryl bromides reacting faster and more selectively than their electron-poor counterparts due to the influence of electronics in the migratory insertion step. Our findings add additional insight into the proposed mechanism of palladium-catalyzed formylation of aryl bromides.    

    

* Ni-Catalyzed Enantioconvergent Kumada–Corriu Cross-Coupling between β-Bromostyrenes and Secondary Grignard Reagents: Reaction Development, Scope and Mechanistic Investigations  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405512891
:TOPICS: Catalytic C–H Functionalization Methods, Radical Photochemical Reactions, Catalytic Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06360")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405512891"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405512891"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405512891"))][Get cited by]]

OpenAlex: https://openalex.org/W4405512891 (Open access: False)
    
[[https://openalex.org/A5102819888][Kaidi Li]], [[https://openalex.org/A5045506896][Baptiste Leforestier]], [[https://openalex.org/A5035660661][Amalia I. Poblador‐Bahamonde]], [[https://openalex.org/A5062650755][Céline Besnard]], [[https://openalex.org/A5011143075][Laure Guénée]], [[https://openalex.org/A5088895349][Svetlana Kucher]], [[https://openalex.org/A5053472767][Clément Mazet]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06360 
     
A Ni-catalyzed enantioconvergent cross-coupling between β-bromostyrenes and secondary Grignard reagents is reported. This C(sp2)–C(sp3) cross-coupling is applicable to a broad range of electrophilic and nucleophilic partners and affords the products in good to high levels of enantio-induction. Experimental mechanistic investigations revealed an unexpected binding mode of the chiral (P,N) ligand and support a radical rebound mechanism involving in-cage radicals. Kinetic experiments provide evidence for an off-cycle resting state featuring dinuclear species. Computational analyses are in line with this hypothesis and coherent with a catalytic cycle proceeding via a Ni(I)/Ni(III) manifold. They further suggest an enantio-determining radical capture event and shed light on the origin of the Dynamic Kinetic Resolution process.    

    

* Chiral Triazole-Substituted Iodonium Salts in Enantioselective Halogen Bond Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405516340
:TOPICS: Fluorine in Organic Chemistry, Vanadium and Halogenation Chemistry, Oxidative Organic Chemistry Reactions
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06895")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405516340"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405516340"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405516340"))][Get cited by]]

OpenAlex: https://openalex.org/W4405516340 (Open access: True)
    
[[https://openalex.org/A5056798745][Mattis Damrath]], [[https://openalex.org/A5072375748][Tarek Scheele]], [[https://openalex.org/A5018569507][Daniel Duvinage]], [[https://openalex.org/A5037929085][Tim Stauch]], [[https://openalex.org/A5084678547][Boris J. Nachtsheim]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06895 
     
No abstract    

    

* Organizational and Mechanistic Modulation of ORR/OER Activity in M1M2–N–C Bimetallic Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405529735
:TOPICS: Electrocatalysts for Energy Conversion, Catalytic Processes in Materials Science, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06280")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405529735"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405529735"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405529735"))][Get cited by]]

OpenAlex: https://openalex.org/W4405529735 (Open access: False)
    
[[https://openalex.org/A5052934313][Xinge Wu]], [[https://openalex.org/A5101268139][Zhaoying Yang]], [[https://openalex.org/A5100368347][Decheng Li]], [[https://openalex.org/A5089879316][Shuai Shao]], [[https://openalex.org/A5079960421][Gaowu Qin]], [[https://openalex.org/A5008454078][Xiangying Meng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06280 
     
No abstract    

    

* Hydrothermally Stable Zeolite-Encapsulated Metal Catalyst Promoted by Framework Sn Species  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405534973
:TOPICS: Catalytic Processes in Materials Science, Nanomaterials for catalytic reactions, Catalysis and Hydrodesulfurization Studies
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05458")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405534973"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405534973"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405534973"))][Get cited by]]

OpenAlex: https://openalex.org/W4405534973 (Open access: False)
    
[[https://openalex.org/A5100449160][Xiaoyu Li]], [[https://openalex.org/A5014361961][Lichen Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05458 
     
Hydrothermal stability is a vital performance criterion considered in the design of heterogeneous metal catalysts for practical applications because of the widespread presence of moisture in the reaction feeds or the products. In this work, we substantially promote the hydrothermal stability of the Pt-zeolite catalyst by incorporating Sn into the zeolite framework. Pt species are stabilized as small nanoparticles, and the MFI zeolite structure is well preserved even after hydrothermal treatment at 850 °C in a mixed atmosphere (CO + O2 + H2O). Adding Sn into Pt-MFI not only heals the defect sites in pure-silica MFI zeolite to promote its structural stability during hydrothermal treatment but also stabilizes the mobile PtOx species via the Sn–O–Pt interaction. The remarkably high stability of the Pt particles encapsulated in the Sn-promoted MFI zeolite is reflected in the CO oxidation reaction in which Pt particles stabilized in the Sn-promoted MFI zeolite exhibit much higher stability than the nonpromoted Pt-MFI catalyst. The stabilization effect of Sn is further extended to a Pd-MFI zeolite catalyst in which the average size of the Pd particles remains below 2 nm after the harsh hydrothermal treatments at 850 °C.    

    

* Operando Surface-Enhanced Infrared Spectroscopy Connects Interfacial Dynamics with Reaction Kinetics During Electrochemical CO2 Reduction on Copper  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405539425
:TOPICS: CO2 Reduction Techniques and Catalysts, Ionic liquids properties and applications, Advanced Thermoelectric Materials and Devices
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05532")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405539425"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405539425"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405539425"))][Get cited by]]

OpenAlex: https://openalex.org/W4405539425 (Open access: False)
    
[[https://openalex.org/A5104667539][Jesse E. Matthews]], [[https://openalex.org/A5073188790][Jaime E. Avilés Acosta]], [[https://openalex.org/A5100360895][Sang‐Won Lee]], [[https://openalex.org/A5020707671][Dongrak Oh]], [[https://openalex.org/A5068663944][Tiras Y. Lin]], [[https://openalex.org/A5035155573][Kyra M. K. Yap]], [[https://openalex.org/A5032135184][Junjie Chen]], [[https://openalex.org/A5061624173][Ji‐Wook Jang]], [[https://openalex.org/A5103119004][Dong Un Lee]], [[https://openalex.org/A5051904251][Adam C. Nielander]], [[https://openalex.org/A5078810774][Thomas F. Jaramillo]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05532 
     
The reaction microenvironment plays a key role in dictating the selectivity of electrochemical CO2 reduction. However, understanding the chemical nature of this microenvironment under operating conditions remains a substantial challenge. We employed attenuated total reflectance surface-enhanced infrared absorption spectroscopy (ATR-SEIRAS) in operando for simultaneous measurements of reaction kinetics and concentrations of reactants and intermediates at the reaction interface, all under controlled mass transport conditions. These operando measurements enable direct correlations between the reaction microenvironment, mass transport, and kinetics for a Cu electrocatalyst, such as higher local concentrations of CO2 under faster mass transport corresponding to higher rates of CO2 reduction. We observed that faster mass transport decreased the *CO coverage at less negative potentials (−0.6 VRHE) and increased the *CO coverage at more negative potentials (−1.1 VRHE). We developed a transport-coupled kinetic model that captures these spectroscopic observations and provides insight into the processes controlling interfacial concentrations of reactants and intermediates, aiding future efforts toward tailoring reaction microenvironments.    

    

* Revealing the Jahn–Teller Mitigating Complexity of Se-Anchored Mn Oxides for Superior SO2 Resistance in Gaseous Molecular Oxygen Activation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405546278
:TOPICS: Catalytic Processes in Materials Science, Gas Sensing Nanomaterials and Sensors, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06268")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405546278"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405546278"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405546278"))][Get cited by]]

OpenAlex: https://openalex.org/W4405546278 (Open access: False)
    
[[https://openalex.org/A5073552078][Haomiao Xu]], [[https://openalex.org/A5087755412][Qinyuan Hong]], [[https://openalex.org/A5029372480][Jia’nan Wang]], [[https://openalex.org/A5100769155][Jun Lei]], [[https://openalex.org/A5100347511][Mingming Wang]], [[https://openalex.org/A5100636534][Jiaxing Li]], [[https://openalex.org/A5100358866][Zhisong Liu]], [[https://openalex.org/A5106481340][Menggai Jiao]], [[https://openalex.org/A5030077298][Wenjun Huang]], [[https://openalex.org/A5013833309][Zan Qu]], [[https://openalex.org/A5020501565][Naiqiang Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06268 
     
Manganese oxides have emerged as promising catalysts for the low-temperature activation of molecular oxygen (O2), crucial for the catalytic oxidation and removal of gaseous pollutants. However, the undesired Jahn–Teller (J-T) effects associated with the Mniv/Mniii redox couple, particularly under SO2 poisoning, led to the effectiveness of Mn oxides in applications. Herein, we construct a highly covalent Seiv-O-Mniii structure via the introduction of selenium into α-MnO2. Such a structure features high-valence Seiv anchored on the oxygen-terminated (110) plane of α-MnO2, facilitates the generation of more active oxygen species, and maintains the continuous cycling of oxygen-linked Mniv/Mniii. Such dynamics are pivotal for stabilizing manganese activation and mitigating the J-T effect. Through a combination of experimental investigations and theoretical calculations, we demonstrate that the Seiv-O-Mniii configuration, characterized by a high degree of Mn–O hybridization, significantly enhances CO oxidation, NH3 oxidation, and elemental mercury (Hg0) removal performances, and exhibits resistance to SO2. This study paves the way for the development of efficient low-temperature O2 activation processes for the removal of gaseous pollutants in real-world applications.    

    

* Reactant-Induced Dynamic Active Sites on Cu Catalysts during the Water–Gas Shift Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405546397
:TOPICS: Catalytic Processes in Materials Science, Catalysts for Methane Reforming, Catalysis and Oxidation Reactions
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05338")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405546397"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405546397"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405546397"))][Get cited by]]

OpenAlex: https://openalex.org/W4405546397 (Open access: False)
    
[[https://openalex.org/A5101791435][Pengfei Hou]], [[https://openalex.org/A5017725939][Qi Yu]], [[https://openalex.org/A5068247094][Feng Luo]], [[https://openalex.org/A5100608982][Jincheng Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05338 
     
Adsorbates can trigger surface reconstruction on metal surfaces, a common yet highly important phenomenon in heterogeneous catalysis that has not been fully explored. Here, we develop a reliable Cu–C–O machine learning force field (MLFF) with ab initio accuracy, providing insights into the reconstruction mechanism and distribution of active sites on the Cu surface under a CO atmosphere through state-of-the-art deep potential molecular dynamics (DPMD). Combining statistical cluster analysis with microkinetic modeling, we establish a strategy to quantitatively assess the turnover frequency (TOF) of catalyst surfaces during the dynamic catalytic process. Our findings reveal that edge Cu atoms undergo rearrangement, ejection, diffusion, and aggregation under a CO atmosphere, leading to the formation of cluster active sites. These small clusters in dynamic equilibrium are identified as the origin of the high catalytic activity of Cu-based catalysts for a low-temperature water–gas shift reaction (WGSR). This work not only elucidates intrinsic activity in metal catalysis and the dynamic catalysis theory but also offers valuable insights for computational catalysis methods to identify effective catalysts for practical applications.    

    

* Unraveling Alcohol Additive Effects on Hypervalent Iodine(III)-Catalyzed Asymmetric Phenolic Dearomatization: Ligand Substitution and Low-Barrier Hydrogen Bonds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405546575
:TOPICS: Oxidative Organic Chemistry Reactions, Chemical Synthesis and Reactions, Vanadium and Halogenation Chemistry
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06557")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405546575"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405546575"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405546575"))][Get cited by]]

OpenAlex: https://openalex.org/W4405546575 (Open access: False)
    
[[https://openalex.org/A5019926319][Hanliang Zheng]], [[https://openalex.org/A5100645952][Cai Liu]], [[https://openalex.org/A5080162755][Xiaoyu Lai]], [[https://openalex.org/A5083726075][Muhammet Uyanik]], [[https://openalex.org/A5061232778][Kazuaki Ishihara]], [[https://openalex.org/A5058629788][Xiao‐Song Xue]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06557 
     
Despite the widespread use of hexafluoropropanol (HFIP) as a "magic" solvent or additive in organic synthesis, its fundamental mechanisms lag far behind. This study presents mechanistic insights into the puzzling alcohol additive effects observed in Ishihara's conformationally flexible C2-symmetric iodoarene-catalyzed asymmetric phenolic dearomatization through density functional theory calculations. The results reveal that due to the "booster effect" of fluorinated alcohols, HFIP assembles a trimeric hydrogen bond cluster that displaces a ligand from the active iodine(III) catalyst and forms a low-barrier hydrogen bond with the substrate, which significantly enhances the oxidizing power of the iodine(III) center, thus facilitating the dearomatization of electron-deficient phenols. Conversely, methanol is found to promote the dearomatization of electron-rich phenols via a formally similar yet distinct mechanism, thus highlighting the unique role of HFIP as an additive. The insights gained from this investigation advance our molecular-level understanding of the synergistic interactions between catalysts and additives, potentially guiding the design of catalytic systems that exploit these effects for broader applications.    

    

* New Insights into CO2 Electroreduction in Acidic Seawater  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405569566
:TOPICS: CO2 Reduction Techniques and Catalysts, Electrochemical Analysis and Applications, Ionic liquids properties and applications
:PUBLICATION_DATE: 2024-12-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05816")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405569566"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405569566"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405569566"))][Get cited by]]

OpenAlex: https://openalex.org/W4405569566 (Open access: False)
    
[[https://openalex.org/A5101791707][Peng Chen]], [[https://openalex.org/A5075533679][Haifeng Shen]], [[https://openalex.org/A5021037658][Min Zheng]], [[https://openalex.org/A5065693067][Mietek Jaroniec]], [[https://openalex.org/A5028236459][Yao Zheng]], [[https://openalex.org/A5032628543][Shi Zhang Qiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05816 
     
No abstract    

    

* Autonomous Exploitation of Reaction Pathways for Electrochemical C–N Coupling on Single-Atom Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405591654
:TOPICS: Ammonia Synthesis and Nitrogen Reduction, CO2 Reduction Techniques and Catalysts, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05751")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405591654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405591654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405591654"))][Get cited by]]

OpenAlex: https://openalex.org/W4405591654 (Open access: False)
    
[[https://openalex.org/A5101858494][Junjie Pan]], [[https://openalex.org/A5111592288][Haowen Ding]], [[https://openalex.org/A5107952334][Xiaoling Yang]], [[https://openalex.org/A5079298233][Xianhui Liang]], [[https://openalex.org/A5048397048][Shanglin Wu]], [[https://openalex.org/A5004026148][Mingzheng Zhang]], [[https://openalex.org/A5021329144][Shunning Li]], [[https://openalex.org/A5067840867][Shisheng Zheng]], [[https://openalex.org/A5055477551][Feng Pan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05751 
     
Electrochemical C–N coupling between CO2 and N-containing small molecules is a promising strategy to close both the carbon and nitrogen loops to support the establishment of a net-zero carbon economy. However, the intricate reaction network and the contentious C–N coupling mechanism hinder the development of efficient electrocatalysts for industrial applications. Herein, we develop a graph-based approach to enable autonomous analysis of the C–N coupling mechanism for coreduction of CO2 and NO3– on single-atom catalysts (SACs). 1400 potential intermediates and 2490 C–N coupling modes are investigated based on the Cu-N4-C prototypical catalyst. We demonstrate that N-containing species with a higher reduction degree are more likely to undergo C–N coupling and the initial coupling of the C–N bond tends to occur on CO2. It is revealed that the hydrogenation energies of *NH2 and CO2, as well as their coupling energies, can serve as key indicators for catalyst recommendation. Using this approach, SACs with Mo, W, or Sb metal centers are identified as promising electrocatalysts for C–N coupling. This work presents a paradigm for automatically exploring the mechanisms of complex electrocatalytic reactions and offers a strategy for predicting highly active and selective SACs.    

    

* Decoding the Role of Adsorbates Entropy in the Reactivity of Single-Atom Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405592086
:TOPICS: Catalytic Processes in Materials Science, Electrocatalysts for Energy Conversion, Catalysis and Oxidation Reactions
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04472")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405592086"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405592086"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405592086"))][Get cited by]]

OpenAlex: https://openalex.org/W4405592086 (Open access: False)
    
[[https://openalex.org/A5008067244][Elena Simone]], [[https://openalex.org/A5087324262][Gianvito Vilé]], [[https://openalex.org/A5087412983][Giovanni Di Liberto]], [[https://openalex.org/A5018929838][Gianfranco Pacchioni]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04472 
     
Single-atom catalysts (SACs) are rapidly gaining attention as a versatile class of materials that combine the advantages of both homogeneous and heterogeneous catalysis. A growing number of studies aim to identify potential new SACs or to describe their structure and reactivity through ab initio quantum chemical simulations. While many computational studies primarily address reactions involving small molecules, such as water splitting or CO2 reduction, the application scope of SACs is rapidly broadening to include the production of fine chemicals and the conversion of biomass-derived platform molecules, processes that involve larger, more complex reactants. Using density-functional theory (DFT) simulations, we demonstrate that, while an approximate treatment of entropy is acceptable for molecules with up to three atoms, it introduces substantial errors in reactions involving more complex molecules. Our results reveal a linear correlation between the entropy of adsorbed molecules and that of the corresponding isolated species, mirroring trends observed on extended catalytic surfaces. For the largest systems investigated in this study, the entropy of the free molecule is reduced by approximately 10–20% upon adsorption; for small molecules, this reduction can range from 50 to 70%. This disparity arises because, on SACs, the translational entropy is effectively zero, the rotational entropy is minimal, and the vibrational entropy increases with the size of the molecule. Moreover, the entropy of adsorbates scales linearly with the number of atoms in the molecule, allowing for the prediction of entropic contributions of adsorbates on SACs without additional computational cost. Using propyne hydrogenation as a test, we demonstrate that the reaction energy profile computed with current approximate approaches for estimating the entropy of adsorbates differs significantly from the profile where entropy is explicitly included. These findings highlight the importance of considering adsorbate entropy for accurately predicting the catalytic activity of SACs, particularly for reactions involving complex molecules.    

    

* One-Pot Chemoenzymatic Synthesis of Arsinothricin and the Mechanistic Insights into the Noncanonical Radical SAM Enzyme ArsL  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405595613
:TOPICS: Radical Photochemical Reactions, bioluminescence and chemiluminescence research, Pesticide and Herbicide Environmental Studies
:PUBLICATION_DATE: 2024-12-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04938")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405595613"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405595613"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405595613"))][Get cited by]]

OpenAlex: https://openalex.org/W4405595613 (Open access: False)
    
[[https://openalex.org/A5101292336][Li He]], [[https://openalex.org/A5034159418][Fen‐Er Chen]], [[https://openalex.org/A5100608631][Wei Ding]], [[https://openalex.org/A5100360362][Qi Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04938 
     
Arsinothricin (AST) is a broad-spectrum arsenic-containing antibiotic with promising pharmaceutical properties. In this study, we report the one-pot chemoenzymatic synthesis of AST starting from methylarsenate, a commonly used agricultural herbicide. Although a single point mutation in the C-terminal region of ArsL completely abolished its activity toward the natural substrate inorganic arsenite, this mutation unexpectedly enhanced its activity toward methylarsenate by over 50-fold, enabling subgram scale production of AST in a cell-free system. These findings offer valuable mechanistic insights into ArsL and highlight the significant potential of manipulating the radical SAM superfamily enzymes in synthetic applications.    

    

* Pd Nanoparticles Decorated by Oxidized Ru Clusters for Efficient C–H/C–H Coupling of Arenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405600947
:TOPICS: Catalytic C–H Functionalization Methods, Nanomaterials for catalytic reactions, Asymmetric Hydrogenation and Catalysis
:PUBLICATION_DATE: 2024-12-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05551")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405600947"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405600947"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405600947"))][Get cited by]]

OpenAlex: https://openalex.org/W4405600947 (Open access: False)
    
[[https://openalex.org/A5046493438][Shingo Hasegawa]], [[https://openalex.org/A5110977155][Shunta Tokutake]], [[https://openalex.org/A5006106507][Koji Harano]], [[https://openalex.org/A5031367549][Ken Motokura]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05551 
     
Oxidative homocoupling of arenes is a challenging but attractive method for converting nonactivated aromatics into biaryl compounds. Applications and the mechanistic understanding of bimetallic nanocatalysts for arene C–H bond activation are limited at present. In this study, we found that a Pd–Ru bimetallic catalyst supported on Al2O3 showed remarkably high catalytic activity for the oxidative homocoupling of arenes owing to the synergistic effect between Pd and Ru. Structural analyses by high-angle annular dark-field scanning transmission electron microscopy with energy-dispersive X-ray spectroscopy and X-ray absorption spectroscopy revealed that the Pd nanoparticles were decorated by partially oxidized Ru clusters. Mechanistic studies indicated that the arene C–H bond cleavage was the rate-determining step and proceeded by a concerted metalation–deprotonation mechanism. It was proposed that the role of Ru is promoting the C–H activation step by generating electron-deficient Pd sites, which was supported by DFT calculations. The Ru-decorated Pd nanoparticles showed large turnover numbers for simple arenes.    

    

* Controlling Co 3d/O 2p Orbital Hybridization in LaCoO3 by Modulating the Co–O–Co Bond Angle for Enhanced Oxygen Evolution Reaction Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405601758
:TOPICS: Electrocatalysts for Energy Conversion, Catalytic Processes in Materials Science, Advanced battery technologies research
:PUBLICATION_DATE: 2024-12-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05479")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405601758"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405601758"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405601758"))][Get cited by]]

OpenAlex: https://openalex.org/W4405601758 (Open access: False)
    
[[https://openalex.org/A5042311174][Baoxin Ge]], [[https://openalex.org/A5006405871][Pengyang Jiang]], [[https://openalex.org/A5047896605][Biyi Chen]], [[https://openalex.org/A5082756368][Caijin Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05479 
     
The orbital hybridization between metal and oxygen of perovskite catalysts can lower the overpotential and enhance the oxygen evolution reaction (OER) activity. This study combines density functional theory with experiments to clarify how Sr/Fe codoping modulates orbital hybridization and enhances OER catalytic activity of LaCoO3. The as-prepared La0.50Sr0.50Co0.75Fe0.25O3 shows remarkable performance with a low overpotential of 310 mV at 10 mA cm–2 current density and a 107.03 mV dec–1 Tafel slope, outperforming most state-of-the-art perovskite-based OER electrocatalysts. The experimental results confirm that Sr/Fe codoping enhances the expansion of Co–O–Co bond angles and strengthens the covalency of the Co–O bond in LaCoO3, leading to enhanced electrocatalytic activity. Moreover, increasing Sr doping reduces the distance between the Co 3d/O 2p center and the Fermi level, decreasing the energy difference between them and enhancing the degree of orbital hybridization between Co 3d and O 2p. As the degree of Co 3d/O 2p orbital hybridization increases, a higher charge transfer was found between the active center and intermediate product, OOH, reducing the energy barrier of the rate-determining step while lowering the overpotential. This study provides thorough insight into the rational design of OER catalysts based on orbital hybridization.    

    

* Pincer-Ruthenium-Catalyzed Direct Formation of Fuel-Grade Alkanes via a Net-Decarboxylative Coupling of Alcohols  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405630608
:TOPICS: Asymmetric Hydrogenation and Catalysis, Catalysis for Biomass Conversion, Carbon dioxide utilization in catalysis
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05826")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405630608"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405630608"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405630608"))][Get cited by]]

OpenAlex: https://openalex.org/W4405630608 (Open access: False)
    
[[https://openalex.org/A5113219645][Pran Gobinda Nandi]], [[https://openalex.org/A5115562423][Pabitra Maity]], [[https://openalex.org/A5012177920][Akshai Kumar]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05826 
     
No abstract    

    

* Promoted *OH Adsorption Facilitates C–C Bond Cleavage for Efficient Electrochemical Upcycling of Polyethylene Terephthalate  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405640218
:TOPICS: Recycling and Waste Management Techniques, Conducting polymers and applications, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05352")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405640218"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405640218"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405640218"))][Get cited by]]

OpenAlex: https://openalex.org/W4405640218 (Open access: False)
    
[[https://openalex.org/A5041538055][Jinyong Sun]], [[https://openalex.org/A5103580598][Binkai Shi]], [[https://openalex.org/A5039106340][Shuixing Dai]], [[https://openalex.org/A5041988024][Lei Chu]], [[https://openalex.org/A5023689555][Huanlei Wang]], [[https://openalex.org/A5037398992][Minghua Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05352 
     
No abstract    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405650379
:TOPICS: 
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i024_1880616")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405650379"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405650379"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405650379"))][Get cited by]]

OpenAlex: https://openalex.org/W4405650379 (Open access: False)
    
, ACS Catalysis. 14(24)] 2024. https://doi.org/10.1021/csv014i024_1880616 
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405661059
:TOPICS: 
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i024_1880617")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405661059"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405661059"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405661059"))][Get cited by]]

OpenAlex: https://openalex.org/W4405661059 (Open access: False)
    
, ACS Catalysis. 14(24)] 2024. https://doi.org/10.1021/csv014i024_1880617 
     
No abstract    

    
