#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Wed Jan  8 01:21:18 2025

Found 20 results from 2025-01-01 to 2025-01-08
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Bioinspired Molecular Catalyst for Photocatalytic Semihydrogenation of Acetylene with Water as a Proton Source  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406025784
:TOPICS: Metal-Organic Frameworks: Synthesis and Applications, Advanced Photocatalysis Techniques, Inorganic Fluorides and Related Compounds
:PUBLICATION_DATE: 2025-01-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04763")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406025784"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406025784"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406025784"))][Get cited by]]

OpenAlex: https://openalex.org/W4406025784 (Open access: False)
    
[[https://openalex.org/A5068438745][Yangguang Hu]], [[https://openalex.org/A5115602084][Song Wang]], [[https://openalex.org/A5057575735][Zifan Jiang]], [[https://openalex.org/A5024035040][Wanbing Gong]], [[https://openalex.org/A5072596068][Aobo Chen]], [[https://openalex.org/A5013832329][Qiaoxi Liu]], [[https://openalex.org/A5063171821][Guangyu Liu]], [[https://openalex.org/A5018116732][Zhiqiang Shen]], [[https://openalex.org/A5013361199][Jingxiang Low]], [[https://openalex.org/A5034779317][Jun Ma]], [[https://openalex.org/A5100619997][Jun Jiang]], [[https://openalex.org/A5063814734][Chao Gao]], [[https://openalex.org/A5087717847][Yujie Xiong]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c04763 
     
Selective semihydrogenation of acetylene to ethylene in ethylene-rich gas streams is a significant industrial process for obtaining high-quality polyethylene products. The conventional thermal hydrogenation route requires high temperature (>100 °C), excess H2, and noble metal Pd to achieve satisfactory conversion efficiency. Therefore, the development of a more efficient and economical low-energy method for acetylene semihydrogenation is greatly desired yet challenging. Here, we report a noble-metal-free molecular system consisting of a bioinspired [CoII(N4S2)](ClO4)2 catalyst and a copper photosensitizer, which achieves photocatalytic semihydrogenation of acetylene to ethylene with over 96% selectivity and 96–99.9% conversion under ambient conditions for both pure acetylene and industrially relevant ethylene cofeed (containing 1% acetylene) conditions using water as a proton source. In addition, our catalytic system in deuterium oxide exhibits ability for deuterated ethylene production, which is an important building block for various deuterated polyolefins and chemicals.    

    

* Mechanistic Insights into Nitrile and Alkyne Covalent Inhibitors of the SARS-CoV-2 Main Protease  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406091634
:TOPICS: Computational Drug Discovery Methods, Click Chemistry and Applications, Synthesis and biological activity
:PUBLICATION_DATE: 2025-01-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06020")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406091634"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406091634"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406091634"))][Get cited by]]

OpenAlex: https://openalex.org/W4406091634 (Open access: False)
    
[[https://openalex.org/A5010387708][Ashim Nandi]], [[https://openalex.org/A5046676481][Mojgan Asadi]], [[https://openalex.org/A5001140607][Aoxuan Zhang]], [[https://openalex.org/A5110110180][Zhen T. Chu]], [[https://openalex.org/A5088665303][Arieh Warshel]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06020 
     
The treatment of SARS-CoV-2 can be accomplished by effective suppression of its 3CL protease (3CLpro), also known as the main protease (Mpro) and nonstructural protein 5 (nsp5). Covalent inhibitors can irreversibly and selectively disable the protease, particularly when they are highly exothermic. Herein we investigated the distinct kinetic behaviors exhibited by two covalently linked SARS-CoV-2 inhibitors. One of these inhibitors features a nitrile reactive group, while the other has this group replaced by an alkyne group, a less reactive electrophile. Our investigations involve the assessment of the free energy surfaces of the key feasible mechanisms: that is, direct and water-assisted mechanisms involved in the rate-determining proton-transfer nucleophilic attack step through the utilization of both ab initio and empirical valence bond (EVB) simulations. The calculated free energy profiles show that substituting the nitrile group with alkyne increases the chemical barrier but leads to very exothermic reaction energy and is an irreversible process as opposed to nitrile, which is moderately exothermic and reversible. We also examine the time dependence of IC50 inhibition by applying an innovative kinetic simulation approach, which is particularly important in studies of covalent inhibitors with a very exothermic bonding step. Our computational approach provides a good agreement between the calculated and observed values of the time dependence results for the nitrile and alkyne inhibitors. Our approach, which is rather unique in combining calculations of the chemical barriers and the binding energy is likely to be very effective in studies of the effectiveness of other covalent inhibitors related cases.    

    

* Inducing Cu Charge Redistribution by Modulating Proximity with Zr(OH)4 for Selective Synthesis of Imines and Secondary Amines with Stoichiometric Benzyl Alcohol and Nitrobenzene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406093746
:TOPICS: Asymmetric Hydrogenation and Catalysis, Nanomaterials for catalytic reactions, Innovative Microfluidic and Catalytic Techniques Innovation
:PUBLICATION_DATE: 2025-01-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05785")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406093746"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406093746"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406093746"))][Get cited by]]

OpenAlex: https://openalex.org/W4406093746 (Open access: False)
    
[[https://openalex.org/A5100649077][Jie Song]], [[https://openalex.org/A5100935179][Chunxia Che]], [[https://openalex.org/A5079399790][Yiwei Dai]], [[https://openalex.org/A5050284480][Jiaheng Qin]], [[https://openalex.org/A5101335462][Cong Yang]], [[https://openalex.org/A5086843496][Ziqiu Chen]], [[https://openalex.org/A5101650068][Kexin Ma]], [[https://openalex.org/A5041314524][Yuhui Han]], [[https://openalex.org/A5091099530][Yu Long]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05785 
     
No abstract    

    

* Triethoxysilane-Catalyzed Single and Sequential Regioselective Hydroboration of Terminal Alkynes: Sustainable Access to E-Alkenylboronate and Alkyl Gem-Diboronate Esters by Non-Covalent Interactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405973307
:TOPICS: Organoboron and organosilicon chemistry, Chemical Synthesis and Analysis, Asymmetric Hydrogenation and Catalysis
:PUBLICATION_DATE: 2025-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06845")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405973307"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405973307"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405973307"))][Get cited by]]

OpenAlex: https://openalex.org/W4405973307 (Open access: False)
    
[[https://openalex.org/A5111032542][Harleen Kaur]], [[https://openalex.org/A5037730598][Himani Ahuja]], [[https://openalex.org/A5016064847][Rebeca Arévalo]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06845 
     
No abstract    

    

* Regulating Heteroatom Doping-Induced Embedded Pt-M Bimetallic Sites Coupled with Ce3+-OVs for Efficient Low-Temperature Methanol Steam Reforming  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405991185
:TOPICS: Catalytic Processes in Materials Science, Catalysts for Methane Reforming, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05507")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405991185"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405991185"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405991185"))][Get cited by]]

OpenAlex: https://openalex.org/W4405991185 (Open access: False)
    
[[https://openalex.org/A5101624169][Wei Zheng]], [[https://openalex.org/A5090847139][Shengfang Shi]], [[https://openalex.org/A5068536978][Fei Dong]], [[https://openalex.org/A5076254456][Hekun Jia]], [[https://openalex.org/A5107657755][Zhiling Chen]], [[https://openalex.org/A5003538933][Bifeng Yin]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05507 
     
No abstract    

    

* Hydrogen Evolution and Oxygen Reduction on OH/F-Terminated Titanium Nitride MXene Reveal the Role of the Surface Termination Group in Electrocatalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405994823
:TOPICS: MXene and MAX Phase Materials, Advanced Photocatalysis Techniques, Advanced Memory and Neural Computing
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05247")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405994823"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405994823"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405994823"))][Get cited by]]

OpenAlex: https://openalex.org/W4405994823 (Open access: True)
    
[[https://openalex.org/A5075083911][Eugenie Pranada]], [[https://openalex.org/A5019655814][Bright Ngozichukwu]], [[https://openalex.org/A5038104345][Ray Yoo]], [[https://openalex.org/A5023017337][Denis Johnson]], [[https://openalex.org/A5031920355][Mark A. Barteau]], [[https://openalex.org/A5038398773][Ahmed Abdel‐Wahab]], [[https://openalex.org/A5021880950][Abdoulaye Djire]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05247 
     
No abstract    

    

* Dehydrogenase versus Oxidase Function: The Interplay between Substrate Binding and Flavin Microenvironment  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406017818
:TOPICS: Amino Acid Enzymes and Metabolism, Photosynthetic Processes and Mechanisms, Enzyme Structure and Function
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05944")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406017818"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406017818"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406017818"))][Get cited by]]

OpenAlex: https://openalex.org/W4406017818 (Open access: False)
    
[[https://openalex.org/A5099297323][Teresa Benedetta Guerriere]], [[https://openalex.org/A5115752339][Alessandro Vancheri]], [[https://openalex.org/A5115752340][Ilaria Ricotti]], [[https://openalex.org/A5087676999][Stefano A. Serapian]], [[https://openalex.org/A5060936314][Daniel Eggerichs]], [[https://openalex.org/A5001303954][Dirk Tischler]], [[https://openalex.org/A5046491394][Giorgio Colombo]], [[https://openalex.org/A5027633851][María Laura Mascotti]], [[https://openalex.org/A5083203989][Marco W. Fraaije]], [[https://openalex.org/A5017449175][Andrea Mattevi]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05944 
     
Redox enzymes, mostly equipped with metal or organic cofactors, can vary their reactivity with oxygen by orders of magnitude. Understanding how oxygen reactivity is controlled by the protein milieu remains an open issue, with broad implications for mechanistic enzymology and enzyme design. Here, we address this problem by focusing on a widespread group of flavoenzymes that oxidize phenolic compounds derived from microbial lignin degradation, using either oxygen or cytochrome c as an electron acceptor. A comprehensive phylogenetic analysis revealed conserved amino acid motifs in the flavin-binding site. Using a combination of kinetic, mutagenesis, structural, and computational methods, we examined the role of these residues. Our results demonstrate that subtle and localized changes in the flavin environment can drastically impact oxygen reactivity. These effects are afforded through the creation or blockade of pathways for oxygen diffusion. Substrate binding plays a crucial role by potentially obstructing oxygen access to the flavin, thus influencing the enzyme's reactivity. The switch between oxidase and dehydrogenase functionalities is thereby achieved through targeted, site-specific amino acid replacements that finely tune the microenvironment around the flavin. Our findings explain how very similar enzymes can exhibit distinct functional properties, operating as oxidases or dehydrogenases. They further provide valuable insights for the rational design and engineering of enzymes with tailored functions.    

    

* Poly(triazine imide) Crystals for Efficient CO2 Photoreduction: Surface Pyridine Nitrogen Dominates the Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406018026
:TOPICS: Advanced Photocatalysis Techniques, Covalent Organic Framework Applications, CO2 Reduction Techniques and Catalysts
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06685")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406018026"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406018026"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406018026"))][Get cited by]]

OpenAlex: https://openalex.org/W4406018026 (Open access: False)
    
[[https://openalex.org/A5100415286][Feng Liu]], [[https://openalex.org/A5005731325][Jing Deng]], [[https://openalex.org/A5111181163][Bo Su]], [[https://openalex.org/A5108911811][Kang‐Shun Peng]], [[https://openalex.org/A5101686093][Kunlong Liu]], [[https://openalex.org/A5049356478][Xiahui Lin]], [[https://openalex.org/A5060265950][Sung‐Fu Hung]], [[https://openalex.org/A5100770697][Xiong Chen]], [[https://openalex.org/A5089758650][Xue Feng Lu]], [[https://openalex.org/A5027738164][Yuanxing Fang]], [[https://openalex.org/A5043430188][Guigang Zhang]], [[https://openalex.org/A5100736051][Sibo Wang]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06685 
     
Polymeric carbon nitrides (PCNs), usually the melon phase, have been extensively applied as photocatalysts for CO2 reduction; however, their performance is still unsatisfactory. The condensed allotrope, namely, poly(triazine imide) (PTI) with extended conjugation and a crystallized structure, indeed holds more favorable compositional and structural advantages for photocatalytic CO2 reduction but remains to be fully exploited. Herein, hexagonal prism-shaped PTI crystals were synthesized and developed as a high-performance photocatalyst for CO2 reduction. With Co(bpy)32+ as a cocatalyst, the PTI crystals exhibit a CO evolution rate of 44 μmol h–1 (i.e., 1467 μmol g–1 h–1) with 93% selectivity, markedly superior to that of the melon counterpart. Moreover, PTI crystals manifest an apparent quantum efficiency of 12.9% at 365 nm, representing the state-of-the-art value by PCN photocatalysts for CO2-to-CO reduction without using noble metals. The surface pyridine N species of PTI are exposed as active sites to dominate CO2 activation and conversion, which, together with the high crystallinity to facilitate charge separation and transport, endows high CO2 reduction efficiency. In situ diffuse reflectance infrared Fourier transform spectroscopy determines the key intermediates during the CO2 reduction reaction and, consequently, constructs the possible reaction mechanism.    

    

* Biocatalytic Efficient and Enantiocomplementary Synthesis of 3-Hydroxy-3-hydroxymethyloxindoles by Combining Halohydrin Dehalogenase and Epoxide Hydrolase  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406020045
:TOPICS: Enzyme Catalysis and Immobilization, Pharmacogenetics and Drug Metabolism, Biochemical Acid Research Studies
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07482")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406020045"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406020045"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406020045"))][Get cited by]]

OpenAlex: https://openalex.org/W4406020045 (Open access: False)
    
[[https://openalex.org/A5031019455][Run‐Ping Miao]], [[https://openalex.org/A5100375636][Haixia Zhang]], [[https://openalex.org/A5072833759][Ke Lü]], [[https://openalex.org/A5090619187][Taotao Lu]], [[https://openalex.org/A5100371080][Huihui Wang]], [[https://openalex.org/A5111039970][Yong‐Zheng Chen]], [[https://openalex.org/A5086122647][Nan‐Wei Wan]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c07482 
     
No abstract    

    

* Construction of Highly Active Fe5C2–FeCo Interfacial Sites for Oriented Synthesis of Light Olefins from CO2 Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406021378
:TOPICS: Catalysts for Methane Reforming, Catalytic Processes in Materials Science, Carbon dioxide utilization in catalysis
:PUBLICATION_DATE: 2025-01-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06001")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406021378"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406021378"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406021378"))][Get cited by]]

OpenAlex: https://openalex.org/W4406021378 (Open access: False)
    
[[https://openalex.org/A5100416757][Teng Li]], [[https://openalex.org/A5063276383][Heng Zhao]], [[https://openalex.org/A5081444687][Lisheng Guo]], [[https://openalex.org/A5082352652][Guangbo Liu]], [[https://openalex.org/A5029884312][Jinhu Wu]], [[https://openalex.org/A5022433710][Tao Xing]], [[https://openalex.org/A5107859114][Tao Li]], [[https://openalex.org/A5100409455][Qiang Liu]], [[https://openalex.org/A5110056501][Jiancai Sui]], [[https://openalex.org/A5100657898][Yitong Han]], [[https://openalex.org/A5019238601][Jiaming Liang]], [[https://openalex.org/A5028463150][Yingluo He]], [[https://openalex.org/A5054090836][Noritatsu Tsubaki]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06001 
     
The hydrogenation of CO2 into high-value chemistry is seen as one of the viable strategies for solving the energy crisis of the future. Light olefins have attracted considerable attention as basic feedstocks in the industry. In this work, a series of Fe–Co bimetallic active site catalysts were constructed by a typical sol–gel strategy. The synergistic regulation layout of the Fe–Co bimetallic active site catalyst constructed highly active interfaces and exhibited high conversion (56.9%) of CO2, low CO selectivity (3.6%), high selectivity (40.5%) of light olefins, and remarkable light olefins yield (22.2%). The results of the associated characterization analysis indicate that the high activity interfaces formed by the synergistic regulation layout of the Fe–Co bimetallic active sites are the fundamental reason for the high yield of light olefins. The high activity interfaces formed by the introduction of cobalt drive the RWGS reaction forward (Le Chatelier's Principle), which further enhances the CO2 conversion. In addition, the dynamic evolution of the physical phase structure, elemental composition and valence, CO2 and H2 adsorption ability, and the formation process of light olefins during the reaction of Fe–Co bimetallic catalysts were analyzed by in situ DRIFT spectra and other characterizations, and a potential mechanism for the high selectivity of CO2 hydrogenation to light olefins is further proposed. This work provides an effective and rational design strategy for the synergistic regulation layout of Fe–Co bimetals with highly active interfaces to promote efficient hydrogenation of CO2 for the oriented synthesis of light olefins.    

    

* Highly Active and Stable Al-Doped NiFe Self-Supported Oxygen Evolution Reaction Electrode for Alkaline Water Electrolysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406022367
:TOPICS: Electrocatalysts for Energy Conversion, Advanced battery technologies research, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2025-01-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04393")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406022367"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406022367"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406022367"))][Get cited by]]

OpenAlex: https://openalex.org/W4406022367 (Open access: False)
    
[[https://openalex.org/A5025410165][Byung‐Jo Lee]], [[https://openalex.org/A5086156640][Sang‐Mun Jung]], [[https://openalex.org/A5070656535][Guoliang Yu]], [[https://openalex.org/A5022855850][Hyun-Yup Kim]], [[https://openalex.org/A5006645538][Jaesub Kwon]], [[https://openalex.org/A5067204985][Kyu‐Su Kim]], [[https://openalex.org/A5064545838][Jaeik Kwak]], [[https://openalex.org/A5101592904][Wooseok Lee]], [[https://openalex.org/A5001151989][Dong Hyeon Mok]], [[https://openalex.org/A5058710447][Seoin Back]], [[https://openalex.org/A5100658302][Yong‐Tae Kim]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c04393 
     
Alkaline water electrolysis (AWE), a predominant technology for large-scale industrial hydrogen production, faces limitations in commercialization owing to the inadequate catalytic activity and stability of oxygen evolution reaction (OER) electrocatalysts. This study introduces a NiFeAl self-supported electrode characterized by high activity and stability for the OER and outlines a rational design strategy for NiFe (oxy)hydroxide-based self-supported electrodes. The introduction of Al, a ternary dopant with relatively low electronegativity and a small ionic radius, into the NiFe electrode effectively controls the adsorption energy of O-intermediates and facilitates the deprotonation of adsorbed OH*, thereby accelerating the OER. Remarkably, the NiFeAl self-supported electrode demonstrates approximately 50% enhanced operational activity (0.71 A cm–2 at 1.8 V) compared to NiFe alongside exceptional stability (>72 h at 0.6 A cm–2) in OER within an AWE single cell. These findings highlight the significant potential of the NiFeAl electrode for application in AWE for efficient, large-scale hydrogen production.    

    

* Advancing the Synthesis for Perdeuterated Small Organic Chemicals via Electrochemical CO2 Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406025115
:TOPICS: Chemical Reactions and Isotopes, Ammonia Synthesis and Nitrogen Reduction, Asymmetric Hydrogenation and Catalysis
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06353")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406025115"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406025115"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406025115"))][Get cited by]]

OpenAlex: https://openalex.org/W4406025115 (Open access: False)
    
[[https://openalex.org/A5066304038][Bjørt Óladóttir Joensen]], [[https://openalex.org/A5071336039][Qiucheng Xu]], [[https://openalex.org/A5043034054][Kasper Enemark‐Rasmussen]], [[https://openalex.org/A5068583891][Victoria L. Frankland]], [[https://openalex.org/A5027925977][Arun Prakash Periasamy]], [[https://openalex.org/A5007782967][John R. Varcoe]], [[https://openalex.org/A5090008029][Ib Chorkendorff]], [[https://openalex.org/A5082009908][Brian Seger]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06353 
     
High deuteration yields are difficult to attain with conventional chemical synthesis methods. In this work, we demonstrate that deuterated chemicals can be produced using electrochemical CO2 reduction in the presence of D2O. The absence of H2O enables deuteration yields over 99% for products such as ethanol-d6 and formate-d. With a D2O solvent, the competing D2 evolution reaction is completely suppressed at low current densities while being kept <10% at a higher 300 mA/cm2.    

    

* Boosting the Water Gas Shift Reaction Rate on Au Nanocatalysts through Collaborative Synthesis of Warm and Cold Plasmas  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406025145
:TOPICS: Catalytic Processes in Materials Science, Nanomaterials for catalytic reactions, Copper-based nanomaterials and applications
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05657")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406025145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406025145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406025145"))][Get cited by]]

OpenAlex: https://openalex.org/W4406025145 (Open access: False)
    
[[https://openalex.org/A5028254222][Ye-Cheng Li]], [[https://openalex.org/A5100689329][Xiaosong Li]], [[https://openalex.org/A5101844058][Jinglin Liu]], [[https://openalex.org/A5005209343][Bin Zhu]], [[https://openalex.org/A5100459824][Guanghui Zhang]], [[https://openalex.org/A5100765513][Dongdong Liu]], [[https://openalex.org/A5100431810][Wei Liu]], [[https://openalex.org/A5108083619][Xinwen Guo]], [[https://openalex.org/A5050304281][Ai‐Min Zhu]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05657 
     
TiO2-supported Au nanocatalysts are highly attractive for the water gas shift (WGS) reaction due to their high catalytic activity at low temperatures. Herein, the (Au/TiO2–x)OP catalyst synthesized by the combination of warm and cold plasmas exhibits a high WGS reaction rate of 1.63 mol·gAu–1·h–1 at 120 °C, being one of the highest WGS rates among Au/TiO2 catalysts. The warm plasma generates a large amount of oxygen vacancies, while the cold plasma treatment generates small Au nanoparticles and interfacial sites. The (Au/TiO2–x)OP catalyst features two kinds of abundant active sites including Auδ+-Oδ−-Ti4+ and Au0-Ov-Ti3+, which accelerate the WGS reaction simultaneously along the intermediate and redox reaction pathways, respectively.    

    

* Dynamic Kinetic Reductive Grignard-Type Addition for the Construction of Axial and Central Chirality  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406028498
:TOPICS: Axial and Atropisomeric Chirality Synthesis, Molecular spectroscopy and chirality, Asymmetric Synthesis and Catalysis
:PUBLICATION_DATE: 2025-01-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406028498"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406028498"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406028498"))][Get cited by]]

OpenAlex: https://openalex.org/W4406028498 (Open access: False)
    
[[https://openalex.org/A5056301509][Ya-Ping Shao]], [[https://openalex.org/A5115603764][Yong‐Min Liang]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c07172 
     
This study describes a photoredox/cobalt dual-catalyzed asymmetric Grignard-type addition reaction, enabling the synthesis of axially chiral hexatomic (six–six) N-heterobiaryls bearing the extra chiral secondary alcohol unit via an efficient dynamic kinetic asymmetric transformation of racemic N-heterobiaryl triflate substrates. The conversion facilitated via both photoredox and classical reductive reaction conditions exhibits good functional group tolerance, a broad substrate scope, and satisfactory stereoselectivity. Furthermore, control experiments and density functional theory calculations provide preliminary mechanistic insights.    

    

* Developing Dual-Atom Catalysts with Tunable Electron Synergistic Effect via Photoinduced Ligand Exchange Strategy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406037761
:TOPICS: Advanced Photocatalysis Techniques, Electrocatalysts for Energy Conversion, CO2 Reduction Techniques and Catalysts
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06059")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406037761"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406037761"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406037761"))][Get cited by]]

OpenAlex: https://openalex.org/W4406037761 (Open access: False)
    
[[https://openalex.org/A5102554074][Yamei Pang]], [[https://openalex.org/A5100437302][Xu Zhang]], [[https://openalex.org/A5100339754][Pengfei Li]], [[https://openalex.org/A5066878588][Guang‐Jie Xia]], [[https://openalex.org/A5067168903][Xupeng Zong]], [[https://openalex.org/A5060116133][Yichang Liu]], [[https://openalex.org/A5071165258][Dan Qu]], [[https://openalex.org/A5100641962][Kun Zheng]], [[https://openalex.org/A5100670445][Li An]], [[https://openalex.org/A5017550339][Xiayan Wang]], [[https://openalex.org/A5029360926][Zaicheng Sun]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06059 
     
No abstract    

    

* Shaping the Future of Green Hydrogen Production: Overcoming Conventional Challenges with Molecular Catalysts, Immobilization, and Scalable Electrolyzers  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406037839
:TOPICS: Hybrid Renewable Energy Systems, Electrocatalysts for Energy Conversion, Hydrogen Storage and Materials
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05986")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406037839"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406037839"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406037839"))][Get cited by]]

OpenAlex: https://openalex.org/W4406037839 (Open access: False)
    
[[https://openalex.org/A5013387611][Suhana Karim]], [[https://openalex.org/A5086489696][Niharika Tanwar]], [[https://openalex.org/A5084631584][Srewashi Das]], [[https://openalex.org/A5115759224][Rounak Ranjit]], [[https://openalex.org/A5022904963][Anwesha Banerjee]], [[https://openalex.org/A5115759225][Gulafshan]], [[https://openalex.org/A5101722250][Anirban Gupta]], [[https://openalex.org/A5012177920][Akshai Kumar]], [[https://openalex.org/A5005081322][Arnab Dutta]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05986 
     
No abstract    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406037958
:TOPICS: 
:PUBLICATION_DATE: 2025-01-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv015i001_1883749")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406037958"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406037958"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406037958"))][Get cited by]]

OpenAlex: https://openalex.org/W4406037958 (Open access: False)
    
, ACS Catalysis. 15(1)] 2025. https://doi.org/10.1021/csv015i001_1883749 
     
No abstract    

    

* B/g-C3N4 for Selectively Regulating Oxygen-Guided Photocatalytic Oxidation of Cinnamaldehyde to Benzaldehyde: Effects of Boron Sources  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406037985
:TOPICS: Advanced Photocatalysis Techniques, Covalent Organic Framework Applications, Gas Sensing Nanomaterials and Sensors
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05427")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406037985"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406037985"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406037985"))][Get cited by]]

OpenAlex: https://openalex.org/W4406037985 (Open access: False)
    
[[https://openalex.org/A5003893515][Xuan Luo]], [[https://openalex.org/A5100375960][Bingbing Li]], [[https://openalex.org/A5031230952][Tongming Su]], [[https://openalex.org/A5101045882][Xinling Xie]], [[https://openalex.org/A5082617917][Zuzeng Qin]], [[https://openalex.org/A5034228364][Hongbing Ji]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05427 
     
No abstract    

    

* Elucidating the Reaction Mechanism and Deactivation of CO2-Assisted Propane Oxidative Dehydrogenation over VOx/TiO2 Catalysts: A Multiple Operando Spectroscopic Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405944424
:TOPICS: Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science, Oxidative Organic Chemistry Reactions
:PUBLICATION_DATE: 2024-12-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04900")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405944424"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405944424"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405944424"))][Get cited by]]

OpenAlex: https://openalex.org/W4405944424 (Open access: False)
    
[[https://openalex.org/A5045824959][Leon Schumacher]], [[https://openalex.org/A5048343148][Kathrin Hofmann]], [[https://openalex.org/A5028546703][Christian Heß]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04900 
     
The CO2-assisted oxidative dehydrogenation (ODH) of propane is of great technical importance and enables the use (and thus removal from the atmosphere) of CO2, a greenhouse gas, in a value-adding process. Supported vanadium oxide (VOx) catalysts are a promising alternative to more active but toxic chromium oxide catalysts. Despite its common use, TiO2 has not been investigated as a support material for VOx in the CO2–ODH of propane. In this study, we elucidate the interaction between titania (P25) and vanadia in the reaction mechanism by analyzing the reaction network and investigating the catalyst using X-ray diffraction (XRD), multiwavelength Raman, UV–vis and diffuse reflectance IR Fourier transform (DRIFT) spectroscopy. Besides direct and indirect ODH reaction pathways, propane dry reforming (PDR) is identified as a side reaction, which is more prominent on bare titania. The presence of VOx enhances the stability and the selectivity toward propylene by participating in the redox cycle, activating CO2 and leading to a higher rate of regeneration. Additionally, VOx catalyzes the conversion of anatase to rutile, which facilitates CO2 activation, thereby leading to an encapsulation of vanadium. At higher loadings, reducible VOx oligomers are present on the surface, facilitating some PDR, but less than on bare P25. As the main deactivation mechanisms of the catalyst system, we propose the reduction of the titania lattice and the consumption of vanadium, while carbon formation appears to be less relevant. Our results highlight the importance of analyzing the CO2–ODH reaction network and applying a multispectroscopic approach to obtain a detailed mechanistic understanding of CO2-assisted propane ODH over supported VOx catalysts.    

    

* Expedited Synthesis of Axially Chiral 3-Monosilyl and 3,3′-Bis-silyl Biphenols, Binaphthols, and Phosphoramidites Enabled by Catalytic Two-Fold C–H Silylation with a Traceless Acetal Directing Group  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405963253
:TOPICS: Axial and Atropisomeric Chirality Synthesis, Asymmetric Synthesis and Catalysis, Asymmetric Hydrogenation and Catalysis
:PUBLICATION_DATE: 2024-12-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05927")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405963253"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405963253"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405963253"))][Get cited by]]

OpenAlex: https://openalex.org/W4405963253 (Open access: False)
    
[[https://openalex.org/A5057084692][Hiep H. Nguyen]], [[https://openalex.org/A5107376498][Suman Das Adhikary]], [[https://openalex.org/A5111332695][Yao Chung Chang]], [[https://openalex.org/A5115732211][Peter Zotor]], [[https://openalex.org/A5004384865][Junha Jeon]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05927 
     
The design and development of supporting ligands have significantly propelled the discovery of new catalytic reactions and the improvement of existing ones. Among these, axially chiral biphenols and 1,1′-binaphthalene-2,2′-diol (BINOL) are some of the most privileged ligands used in a wide array of enantioselective reactions. Despite the well-established benefits of structural modifications to biphenol and BINOL scaffolds, particularly at their 3,3′-positions─for enhancing reactivity and stereofidelity in catalytic asymmetric transformations─only a limited number of 3,3′-bis-functionalized biphenols and BINOLs are currently available. Here, we report a unified strategy to rapidly access a range of axially chiral 3-monosilyl and 3,3′ bis-silyl-substituted and biphenols and BINOLs as well as their corresponding 3-monosilyl and 3,3′ bis-silyl BINOL-based phosphoramidites. This approach involves traceless acetal-directed, catalytic two-fold C–H silylation of axially chiral biaryls, coupled with selective monoprotodesilylation, expanding the versatility of catalytic C–H functionalization in ligand design and development. Scope studies on the augmentation of the topological space of potentially stereoselectivity-amplifying 3,3′-bis-silyl substituents in axially chiral biphenols and BINOLs were achieved through C–H silylation of biphenols and BINOLs using various dihydrosilanes, as well as the derivatization of 3,3′-silanes, leading to functionalized silane-substituted biphenols and BINOLs. Lastly, the phosphoramidation of newly synthesized 3-monosilyl and 3,3′ bis-silyl BINOL and biphenols with dichlorophosphinamine provided a series of 3-monosilyl and 3,3′ bis-silyl BINOL-based phosphoramidites. The efficiency of this synthetic approach is underscored by its short synthetic steps, expedited reaction times, and minimal purification, making it versatile for the synthesis of a wide array of organosilicon-functionalized axially chiral biaryls and phosphoramidites.    

    
