#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Created on Thu Jan 18 00:41:16 2024

Found 22 results from 2024-01-04 to 2024-01-18
** Structural Insights into a Side Chain Cross-Linking Biarylitide P450 from RiPP Biosynthesis   
:PROPERTIES:
:ID: https://openalex.org/W4390537464
:DOI: https://doi.org/10.1021/acscatal.3c05417
:AUTHORS: Mathias Henning Hansen, Angus B. Keto, Maxine Treisman, Vishnu Mini Sasi, Laura Coe, Yongwei Zhao, Leo Padva, Caroline Heß, Victor Leichthammer, Daniel L. Machell, Ralf B. Schittenhelm, Colin J. Jackson, Julien Tailhades, Max Crüsemann, James J. De Voss, Elizabeth H. Krenske, Max J. Cryle
:HOST: ACS Catalysis
:END:

Mathias Henning Hansen, Angus B. Keto, Maxine Treisman, Vishnu Mini Sasi, Laura Coe, Yongwei Zhao, Leo Padva, Caroline Heß, Victor Leichthammer, Daniel L. Machell, Ralf B. Schittenhelm, Colin J. Jackson, Julien Tailhades, Max Crüsemann, James J. De Voss, Elizabeth H. Krenske, Max J. Cryle, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05417")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390537464"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390537464"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390537464"))][Get cited by]]

OpenAlex: https://openalex.org/W4390537464
    
Mathias Henning Hansen, Angus B. Keto, Maxine Treisman, Vishnu Mini Sasi, Laura Coe, Yongwei Zhao, Leo Padva, Caroline Heß, Victor Leichthammer, Daniel L. Machell, Ralf B. Schittenhelm, Colin J. Jackson, Julien Tailhades, Max Crüsemann, James J. De Voss, Elizabeth H. Krenske, Max J. Cryle, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05417
    
Peptide side chain cross-linking is an important feature of many natural products, with an increasing number of examples catalyzed by cytochrome P450s being reported from ribosomal biosynthesis pathways in addition to well-known examples from nonribosomal peptide antibiotics. Despite the dramatic recent increase in the number of enzymes and reactions catalyzed, substrate bound structures of such P450s have proven elusive to date. Here, we report the structural characterization of the biarylitide cross-linking enzyme P450Blt in complex with its pentapeptide substrate MRYLH. This structure, in combination with computational and biochemical experiments, shows the importance of key I-helix residues in this P450 in coordinating to the histidine residue of the substrate and further that this appears to be central to the specificity of this enzyme for generating a C–N link between the tyrosine and histidine residues in the MRYLH substrate. The structure of the P450Blt-MRYLH complex provides the first insight into how peptide substrates can be accommodated within P450s and offers insights into how other examples of related P450s can accept the varied substrates that have recently been identified using bioinformatic methods.    

    

** Surface-Modified S═O Microenvironment Boosts Catalyzed Oxidation of Alcohol <i>via</i> Hydrogen Bond Interactions   
:PROPERTIES:
:ID: https://openalex.org/W4390539334
:DOI: https://doi.org/10.1021/acscatal.3c04779
:AUTHORS: Feng Xiao, Song Shi, Guozhi Zhu, Yinwei Wang, Jieqi Cao, Jie Xu
:HOST: ACS Catalysis
:END:

Feng Xiao, Song Shi, Guozhi Zhu, Yinwei Wang, Jieqi Cao, Jie Xu, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04779")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390539334"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390539334"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390539334"))][Get cited by]]

OpenAlex: https://openalex.org/W4390539334
    
Feng Xiao, Song Shi, Guozhi Zhu, Yinwei Wang, Jieqi Cao, Jie Xu, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04779
    
Enzymes have unique structures, with various amino acid residues encapsulating metal active sites. Their high performance is mainly achieved via weak interactions between the functional groups and the substrate. Inspired by the enzyme structure, we designed an encapsulated catalyst (E-S═O) wherein AuPd nanoparticles were encapsulated by porous organic frameworks (POFs) modified with S═O groups. The alcohol reaction rate of E-S═O increased 2-fold compared with the control catalyst without S═O groups. The hydrogen bond was formed between alcohol and S═O groups, which was confirmed via 1H NMR and inverse-phase gas chromatography (IGC) tests. Further insight including adsorption isotherm, in situ diffuse reflective infrared Fourier transform spectroscopy (DRIFTS), and the kinetics data confirmed the hydrogen bond could account for the rate enhancement. The proposed catalyst preparation strategy through precise microenvironment control via hydrogen bonds with substrates paves a new way for high-performance catalyst design.    

    

** Mechanistic Investigation on C–C Bond Cleavage of Anthraquinone Catalyzed by an Atypical Nonheme Iron-Dependent Dioxygenase BTG13   
:PROPERTIES:
:ID: https://openalex.org/W4390539809
:DOI: https://doi.org/10.1021/acscatal.3c04053
:AUTHORS: Zhiwei Deng, Hao Su, Xiaodong Hou, Huibin Xu, Zhenbo Yuan, Xiang Sheng, Yijian Rao
:HOST: ACS Catalysis
:END:

Zhiwei Deng, Hao Su, Xiaodong Hou, Huibin Xu, Zhenbo Yuan, Xiang Sheng, Yijian Rao, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04053")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390539809"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390539809"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390539809"))][Get cited by]]

OpenAlex: https://openalex.org/W4390539809
    
Zhiwei Deng, Hao Su, Xiaodong Hou, Huibin Xu, Zhenbo Yuan, Xiang Sheng, Yijian Rao, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04053
    
An atypical nonheme iron-dependent dioxygenase BTG13 with a rare iron coordination of four histidine residues and a carboxylated-lysine (Kcx) was recently reported to catalyze the C4a–C10 bond cleavage of anthraquinone. However, the reaction mechanism of BTG13 remains elusive. Herein, the detailed mechanism of BTG13 is studied using molecular dynamics simulations and density functional theory calculations. The comprehensive mechanistic study shows that the most favorable pathway for the C–C bond cleavage of anthraquinone involves two unusual steps: (1) a hydrogen atom abstraction (HAA) from an sp3-hybridized carbon of the substrate by FeIII–O2•– and (2) an oxygen rebound to the substrate radical via homolytic O–O bond cleavage, which activates FeIII–OOH to form FeIV═O species. Furthermore, our results reveal that Kcx could increase the electron-donating ability of the ferrous iron, thereby boosting the activation of dioxygen to form FeIII–O2•– species and facilitating the following HAA and O–O bond cleavage processes. This study advances the current knowledge of reactions catalyzed by iron-dependent oxygenases.    

    

** Pulsing the Applied Potential in Electrochemical CO<sub>2</sub> Reduction Enhances the C<sub>2</sub> Activity by Modulating the Dynamic Competitive Binding of *CO and *H   
:PROPERTIES:
:ID: https://openalex.org/W4390543597
:DOI: https://doi.org/10.1021/acscatal.3c04224
:AUTHORS: Rileigh Casebolt DiDomenico, Kelsey Levine, Colin R. Bundschu, Laila Reimanis, Tomás Arias, Tobias Hanrath
:HOST: ACS Catalysis
:END:

Rileigh Casebolt DiDomenico, Kelsey Levine, Colin R. Bundschu, Laila Reimanis, Tomás Arias, Tobias Hanrath, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04224")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390543597"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390543597"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390543597"))][Get cited by]]

OpenAlex: https://openalex.org/W4390543597
    
Rileigh Casebolt DiDomenico, Kelsey Levine, Colin R. Bundschu, Laila Reimanis, Tomás Arias, Tobias Hanrath, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04224
    
We explore dynamic electrocatalysis by pulsing the applied potential to modulate the temporal microenvironment during the electrochemical reduction of CO2. We focus on copper electrodes by virtue of their unique ability to bind *CO intermediates and enable C–C coupling to form high-value C2 products, such as ethylene or ethanol. We examine the well-known competition between *CO and *H for active sites, as their relative coverage is crucial for enhancing the formation of C2 products. We found that pulsing the applied potential can significantly enhance the electrocatalytic activity of C–C coupling, increasing the turnover frequency of C2 products by up to 33-fold compared to potentiostatic electrolysis. We interpret this improvement in the context of oscillating surface coverage and the transient dynamics of the *CO/*H coverage during the cathodic pulse. Through a combination of experimental and computational methods, we investigate how pulse frequency influences the turnover frequency of CO2 to C2 products on Cu. Our study not only validates recent theoretical predictions about the potential of dynamic (electro)catalysis to surpass the limitations imposed by the Sabatier limit but also uncovers scientific and mechanistic insights into dynamic processes within the electrical double layer. These insights are instrumental in formulating design principles for pulsed CO2 electrolysis with enhanced C2 activity. The outcomes of this study lay a foundational framework for future advances in programmable CO2 electrolysis with improved activity, selectivity, and durability.    

    

** Synergy of Single-Atom Fe<sub>1</sub> and Ce–O<sub>v</sub> Sites on Mesoporous CeO<sub>2</sub>–Al<sub>2</sub>O<sub>3</sub> for Efficient Selective Catalytic Reduction of NO with CO   
:PROPERTIES:
:ID: https://openalex.org/W4390545888
:DOI: https://doi.org/10.1021/acscatal.3c04682
:AUTHORS: Y. Bai, Xupeng Zong, Jin Chen, Shu-Dong Wang, Sheng Wang
:HOST: ACS Catalysis
:END:

Y. Bai, Xupeng Zong, Jin Chen, Shu-Dong Wang, Sheng Wang, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04682")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390545888"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390545888"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390545888"))][Get cited by]]

OpenAlex: https://openalex.org/W4390545888
    
Y. Bai, Xupeng Zong, Jin Chen, Shu-Dong Wang, Sheng Wang, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04682
    
Nonprecious transition-metal oxides, especially Fe-, Cu-, Co-, and Mn-containing mixed oxides, have been regarded as promising alternatives for noble metal catalysts for the abatement of NOx contamination. However, the identification of the real catalytically active sites for these mixed oxides remains unclear in most cases, which limits our in-depth understanding of the intrinsic mechanism. Here, we comprehensively investigated an iron–cerium–aluminum oxide (Fe1/CeO2–Al2O3) prepared with a co-precipitation method. Structural identification confirmed that Fe sites are atomically dispersed, bonding with four O atoms in the first coordination shell and with two Ce atoms in the second shell on average. Highly efficient removal of NO with 100% selectivity toward N2 has been achieved over these sites at a temperature as low as 250 °C. In situ characterizations and computational studies revealed that the high activity and N2 selectivity of Fe1/CeO2–Al2O3 can be attributed to the synergetic effect of the single-atomic Fe1 site and surrounding Ce–Ov, which intensively promotes the adsorption of NO molecules and N2O intermediates. Subsequently, Ce–Ov facilitates the N–O dissociation toward N2 and then is regenerated with CO, forming CO2 as a product. The present results provide valuable insights into the mechanism of transition-metal oxide catalysts for the NO–CO reaction and offer useful guidance for designing catalysts with high activity and selectivity.    

    

** Substrate-Specific Evolution of Amine Dehydrogenases for Accessing Structurally Diverse Enantiopure (<i>R</i>)-β-Amino Alcohols   
:PROPERTIES:
:ID: https://openalex.org/W4390546864
:DOI: https://doi.org/10.1021/acscatal.3c04995
:AUTHORS: Xinjian Yin, Wenzhong Gong, Yuping Zeng, Hulin Qiu, Lan Liu, Frank Hollmann, Bi‐Shuang Chen
:HOST: ACS Catalysis
:END:

Xinjian Yin, Wenzhong Gong, Yuping Zeng, Hulin Qiu, Lan Liu, Frank Hollmann, Bi‐Shuang Chen, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04995")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390546864"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390546864"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390546864"))][Get cited by]]

OpenAlex: https://openalex.org/W4390546864
    
Xinjian Yin, Wenzhong Gong, Yuping Zeng, Hulin Qiu, Lan Liu, Frank Hollmann, Bi‐Shuang Chen, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04995
    
The biocatalytic oxidative deamination of β-amino alcohols holds significant practical potential in kinetic resolution and/or deracemization process to access (R)-β-amino alcohols. This study exemplifies a notable instance of acquisition and utilization of this valuable oxidative deamination activity. Initially, the mutation N261M (M0) was identified to endow a native valine dehydrogenase with oxidative deamination activity toward a few (S)-β-amino alcohols. Subsequently, a phylogenetic analysis-guided, double-code saturation mutagenesis strategy was proposed to engineer M0's side-chain binding site. This strategy facilitated the substrate-specific evolution of M0, resulting in the creation of a panel of mutants (M1–M4) with noteworthy oxidative deamination activity toward structurally diverse (S)-β-amino alcohols. Using these engineered amine dehydrogenases, termed as β-amino alcohol dehydrogenases (β-AADHs), the complete kinetic resolution and even deracemization of a range of β-amino alcohols have been achieved. This work reports distinct biocatalysts and a synthetic strategy for the synthesis of enantiopure (R)-β-amino alcohols and offers an innovative approach for substrate-specificity engineering of enzymes.    

    

** Anode Engineering for Proton Exchange Membrane Water Electrolyzers   
:PROPERTIES:
:ID: https://openalex.org/W4390578014
:DOI: https://doi.org/10.1021/acscatal.3c05162
:AUTHORS: Chao Qiu, Zikai Xu, Feng-Yang Chen, Haotian Wang
:HOST: ACS Catalysis
:END:

Chao Qiu, Zikai Xu, Feng-Yang Chen, Haotian Wang, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05162")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390578014"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390578014"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390578014"))][Get cited by]]

OpenAlex: https://openalex.org/W4390578014
    
Chao Qiu, Zikai Xu, Feng-Yang Chen, Haotian Wang, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05162
    
Sustainable hydrogen (H2) production via water electrolysis is one of the most critical pathways to decarbonize the chemical industry. Among various electrolyzer technologies, proton exchange membrane (PEM) water electrolyzer (PEMWE) is widely regarded as having a great advantage and promise for large-scale H2 production given its high efficiency, reliable stability, and high output pressure. Though state-of-the-art iridium-based catalysts exhibit satisfying activity and stability for oxygen evolution reaction at the anode, their high loadings, as well as the precious metal coating and titanium bulk of porous transport layer (PTL) and bipolar plates, significantly add to the capital cost of the PEMWE stack. The respective optimization and integration of PTL, catalyst layer (CL) and PEM is critical for enhancing charge transfer, mass transport, and catalyst utilization to lower the operation and capital cost, yet it has not received adequate attention. In this review, anode engineering strategies to rationally design PTL, PTL/CL interface and PEM/CL interface for performance improvement and cost reduction are summarized. Current understandings on PTL material, structure, and two-phase transport properties are first gathered, followed by the discussion of anode interface engineering methods and catalyst coating techniques. Given the raising attention to large-scale water electrolyzers operating at high current densities, this review provides a practical and comprehensive direction for next-generation PEMWE anode design by addressing the integration of key components related to the cost, efficiency and stability issues in PEMWE.    

    

** Investigating the Potency of a Phenalenyl-Based Photocatalyst under the Photoelectrochemical Condition for Intramolecular C–S Bond Formation   
:PROPERTIES:
:ID: https://openalex.org/W4390579743
:DOI: https://doi.org/10.1021/acscatal.3c05500
:AUTHORS: Parimal C. Sen, N. K. SAHA, Sudipta Raha Roy
:HOST: ACS Catalysis
:END:

Parimal C. Sen, N. K. SAHA, Sudipta Raha Roy, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05500")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390579743"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390579743"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390579743"))][Get cited by]]

OpenAlex: https://openalex.org/W4390579743
    
Parimal C. Sen, N. K. SAHA, Sudipta Raha Roy, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05500
    
Implementation of an organic molecular photocatalyst for photoelectrochemical (PEC) transformations has been a highly demanding aspect that has not yet been mapped out extensively. Herein, we have unveiled the efficacy of a phenalenyl-based organic photocatalyst toward photoelectrochemical intramolecular C–S bond construction reactions under mild conditions. This phenalenyl core, which contains a vacant NBMO, acts as an electron reservoir, thereby facilitating the formation of a contact ion pair with electron-rich organic systems through intramolecular electron transfer under photoexcitation and aiding in catalytic regeneration by anodic oxidation in a single pot. Detailed mechanistic investigation by using UV–visible spectral analysis, cyclic voltammetry experiments, and computational calculations revealed that the prior formation of an EDA complex between the phenalenyl-based photocatalyst and substrate triggers this PEC process. This unified strategy was successfully implemented in six different intramolecular C–S bond formation reactions to synthesize different heterocycles and make this protocol appealing for the synthesis of C–S bonds.    

    

** A First-Principles Approach to Modeling Surface Site Stabilities on Multimetallic Catalysts   
:PROPERTIES:
:ID: https://openalex.org/W4390580294
:DOI: https://doi.org/10.1021/acscatal.3c04337
:AUTHORS: Shikha Saini, Joakim Halldin Stenlid, Shyam Deo, Philipp N. Pleßow, Frank Abild‐Pedersen
:HOST: ACS Catalysis
:END:

Shikha Saini, Joakim Halldin Stenlid, Shyam Deo, Philipp N. Pleßow, Frank Abild‐Pedersen, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04337")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390580294"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390580294"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390580294"))][Get cited by]]

OpenAlex: https://openalex.org/W4390580294
    
Shikha Saini, Joakim Halldin Stenlid, Shyam Deo, Philipp N. Pleßow, Frank Abild‐Pedersen, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04337
    
The study of multimetallic alloys and the multitude of possible surface compositions have sparked a tremendous interest in engineering low-cost materials with high activity and selectivity in heterogeneous catalysis. Multimetallic systems provide complementary functionalities and an unprecedented tunability when designing catalyst formulations. However, due to their immense structural and compositional complexity, the investigation and identification of an optimal catalyst is a tedious and time-consuming process, both experimentally and theoretically. Therefore, theoretical design principles are highly desirable to accelerate the screening of catalyst structures across the vast compositional space. In this paper, we introduce a simple and general model for predicting the site stability of multimetallic surfaces and nanoparticles, which is based on physical principles. The model requires only a small set of density functional theory (DFT) calculations of metal atom binding energies on monometallic and dilute alloy surface slabs to optimize the parameters in the simple model. The resulting model allows for the quantification of the stability of any particular atom site in any conceivable chemical environment across a wide range of morphologies, sizes, and arrangements by interpolating the derived parameters from a monometallic system to a completely diluted alloyed system. Herein, we demonstrate the robustness of the model across an extensive data set of transition metal alloy surfaces and 147-atoms cuboctahedral nanoparticles (NPs) composed of IrRhRu and PtPdRu. Our approach yields mean absolute errors of ≈0.15 (IrRhRu), 0.20 (PtPdRu), 0.19 (IrRhRu NP), and 0.26 (PtPdRu NP) eV relative to site binding energies calculated using DFT.    

    

** Modulation of the Phase Transformation of Fe<sub>2</sub>O<sub>3</sub> for Enhanced Water Oxidation under a Magnetic Field   
:PROPERTIES:
:ID: https://openalex.org/W4390582441
:DOI: https://doi.org/10.1021/acscatal.3c05032
:AUTHORS: Guangjian Song, Wei Mao, Jing Zhou, Liuhua Mu, Sanzhao Song
:HOST: ACS Catalysis
:END:

Guangjian Song, Wei Mao, Jing Zhou, Liuhua Mu, Sanzhao Song, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05032")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390582441"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390582441"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390582441"))][Get cited by]]

OpenAlex: https://openalex.org/W4390582441
    
Guangjian Song, Wei Mao, Jing Zhou, Liuhua Mu, Sanzhao Song, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05032
    
Ferromagnetic catalysts in the presence of an external magnetic field can promote the reaction kinetics of the oxygen evolution reaction (OER) by enhancing spin-selective electron transfer as intermediates and products confer spin-dependent behavior. It has been found that γ-Fe2O3 with ferromagnetism exhibits an enhanced performance for the OER activity, but its preparation is limited. Herein, we report an adsorption-pyrolysis process in air in which the transformation of α-Fe2O3 into γ-Fe2O3 is precisely regulated by controlling the content of Co ions. Interestingly, a small, constant external magnetic field (∼200 mT) was applied at the anode, resulting in a significant impact on the OER performance of the obtained series of catalysts with different contents of γ-Fe2O3 under alkaline conditions. Theoretical results reveal that the same spin configuration of Fe and O atoms in γ-Fe2O3 provides a spin conduction channel, which enhances the ability to selectively remove spin-oriented electrons from the reactants and accelerates the accumulation of triplet oxygen molecules during the OER process, thereby promoting the OER. These findings provide a strategy toward the controllable phase transformation of Fe2O3 and deep insights for understanding the OER behavior of Fe-based electrocatalysts under magnetic fields.    

    

** Highly Efficient Hydrogenation of α,β-Unsaturated Aldehydes to Unsaturated Alcohols over Defective MOF-808 with Constructed Frustrated Lewis Pairs   
:PROPERTIES:
:ID: https://openalex.org/W4390588887
:DOI: https://doi.org/10.1021/acscatal.3c03624
:AUTHORS: Linhao Zhong, Xiaoqing Liao, Haishuai Cui, He’an Luo, Yang Lv, Pingle Liu
:HOST: ACS Catalysis
:END:

Linhao Zhong, Xiaoqing Liao, Haishuai Cui, He’an Luo, Yang Lv, Pingle Liu, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03624")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390588887"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390588887"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390588887"))][Get cited by]]

OpenAlex: https://openalex.org/W4390588887
    
Linhao Zhong, Xiaoqing Liao, Haishuai Cui, He’an Luo, Yang Lv, Pingle Liu, ACS Catalysis. https://doi.org/10.1021/acscatal.3c03624
    
Solid frustrated Lewis pair (FLP) catalysts have received much attention. In this work, MOF-808 with rich defects was constructed using a facile monocarboxylic acid modulator-induced defect strategy and applied in the transfer hydrogenation of α,β-unsaturated aldehydes to unsaturated alcohol using cyclohexanol as the hydrogen source. MOF-808 was prepared from different zirconium precursors, and it was found that MOF-808-ZT obtained from ZrCl4 and H3BTC forms abundant surface hydroxyl groups (Zr–OH, base sites). Moreover, MOF-808-PA with missing linker defects was constructed by introducing monocarboxylic acid to preoccupy the coordination sites of MOF-808-ZT, leading to abundant Zr–OH2. The coordinated water molecules are removed by the dehydration of MOF-808-PA at 180 °C, and the underlying coordinatively unsaturated Zr4+ (Zr-CUS) is exposed and acts as a Lewis acid site. Characterizations and DFT calculations show that the Zr-CUS/Zr–OH FLPs sites can efficiently activate the C═O of aldehydes and −OH of cyclohexanol and reduce their activation energy barrier, thus exhibiting good catalytic performance. Moreover, these FLP sites can easily easily dissociate the H–H bond with a lower activation energy of 0.15 eV, thereby achieving a better catalytic reactivity in the direct hydrogenation of α,β-unsaturated aldehydes to unsaturated alcohols. A possible reaction mechanism was proposed based on in situ DRIFT, vacuum FTIR, and DFT calculations.    

    

** Insights into CeO<sub>2</sub> Particle Size Dependent Selectivity Control for CO<sub>2</sub> Hydrogenation Using Co/CeO<sub>2</sub> Catalysts   
:PROPERTIES:
:ID: https://openalex.org/W4390589350
:DOI: https://doi.org/10.1021/acscatal.3c05139
:AUTHORS: Rena Oh, Xiaoyang Huang, James Hayward, Yanping Zheng, Mingshu Chen, Gyeong-Su Park, Graham J. Hutchings, Seong Keun Kim
:HOST: ACS Catalysis
:END:

Rena Oh, Xiaoyang Huang, James Hayward, Yanping Zheng, Mingshu Chen, Gyeong-Su Park, Graham J. Hutchings, Seong Keun Kim, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05139")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390589350"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390589350"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390589350"))][Get cited by]]

OpenAlex: https://openalex.org/W4390589350
    
Rena Oh, Xiaoyang Huang, James Hayward, Yanping Zheng, Mingshu Chen, Gyeong-Su Park, Graham J. Hutchings, Seong Keun Kim, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05139
    
The particle size of CeO2 was controlled to study the selectivity toward CO production in CO2 hydrogenation over Co/CeO2 catalysts using ambient-pressure conditions. CeO2 was selected as a typical catalyst support, and it was pretreated by calcination at 450, 750, 900, and 1000 °C, which increases the CeO2 particle size prior to impregnation to prepare a series of 5 wt % Co/CeO2. As a result of catalytic testing, it was found that the CO selectivity can be promoted from 24 ± 2% to 49 ± 1% when the CeO2 is calcined at 1000 °C. We propose that the CeO2 calcination at high temperatures improved its reducibility, strengthened CO adsorption, and weakened H adsorption over the surface of the impregnated Co nanoparticles. Our proposed explanation toward the increased CO selectivity was supported using in situ techniques, i.e., in situ CO DRIFTS and in situ XPS and TEM characterization. This work provides distinctive insight into the relationship between metal–support interaction and the controlled product selectivity in CO2 hydrogenation.    

    

** Theoretical Insights into H<sub>2</sub> Activation over Anatase TiO<sub>2</sub> Supported Metal Adatoms   
:PROPERTIES:
:ID: https://openalex.org/W4390589917
:DOI: https://doi.org/10.1021/acscatal.3c04201
:AUTHORS: Qiang Li, George Yan, Dionisios G. Vlachos
:HOST: ACS Catalysis
:END:

Qiang Li, George Yan, Dionisios G. Vlachos, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04201")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390589917"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390589917"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390589917"))][Get cited by]]

OpenAlex: https://openalex.org/W4390589917
    
Qiang Li, George Yan, Dionisios G. Vlachos, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04201
    
H2 activation is fundamental in catalysis. Single-atom catalysts (SACs) can be highly selective hydrogenation catalysts due to their tunable geometric and electronic properties. In this work, H2 activation (adsorption, splitting, and diffusion) on the anatase TiO2-supported SAC has been modeled in detail. The stable configurations of 14 transition metals from 3d to 5d (Fe, Co, Ni, Cu, Zn, Ru, Rh, Pd, Ag, Cd, Os, Ir, Pt, and Au) and Sn have been screened. We compared H and H2 adsorption and H2 heterolytic and homolytic splitting on SA/TiO2. H on the SAC in neutral, hydridic, and proton forms and the preferred H2 dissociation paths are revealed. We found that the metal adatoms strengthen the Brønsted acids via forming the SA-O bonds and promote the H adsorption on Ti sites via forming the Ti3+ sites. The electronic descriptor using the energy level of the frontier d orbital, referenced to vacuum, can predict the single H and H2 dissociative adsorption energies on the metal site. As the SA-Hδ- interaction is stronger than Ti-Hδ-, the activation barriers for heterolytic paths over SA-O sites are lower than over Ti-O sites. H2 adsorption is activated on Au, Ru, Rh, Pd, and Ir in a dihydrogen complex structure with an elongated H-H bond. Homolytic splitting over SA sites is favored thermodynamically and kinetically on Rh, Pd, Os, Ir, and Pt. In contrast, for the remaining SA/TiO2, H-H splitting at the SA-O is kinetically favored compared to the Ti-O sites, but the products are less thermodynamically favored.    

    

** Metal-Mediated Catalytic Polarization Transfer from <i>para</i> Hydrogen to 3,5-Dihalogenated Pyridines   
:PROPERTIES:
:ID: https://openalex.org/W4390603393
:DOI: https://doi.org/10.1021/acscatal.3c05378
:AUTHORS: Ben. J. Tickner, Marcus Dennington, Brian A. Collins, Callum A. Gater, Theo Tanner, Adrian C. Whitwood, Peter J. Rayner, D. P. Watts, Simon B. Duckett
:HOST: ACS Catalysis
:END:

Ben. J. Tickner, Marcus Dennington, Brian A. Collins, Callum A. Gater, Theo Tanner, Adrian C. Whitwood, Peter J. Rayner, D. P. Watts, Simon B. Duckett, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05378")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390603393"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390603393"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390603393"))][Get cited by]]

OpenAlex: https://openalex.org/W4390603393
    
Ben. J. Tickner, Marcus Dennington, Brian A. Collins, Callum A. Gater, Theo Tanner, Adrian C. Whitwood, Peter J. Rayner, D. P. Watts, Simon B. Duckett, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05378
    
The neutral catalysts [IrCl(H)2(NHC)(substrate)2] or [IrCl(H)2(NHC)(substrate)(sulfoxide)] are used to transfer polarization from para hydrogen (pH2) to 3,5-dichloropyridine and 3,5-dibromopyridine substrates. This is achieved in a rapid, reversible, and low-cost process that relies on ligand exchange within the active catalyst. Notably, the sulfoxide-containing catalyst systems produced NMR signal enhancements between 1 and 2 orders of magnitude larger than its unmodified counterpart. Consequently, this signal amplification by reversible exchange hyperpolarization method can boost the 1H, 13C, and 15N nuclear magnetic resonance (NMR) signal intensities by factors up to 4350, 1550, and 46,600, respectively (14.0, 1.3, and 15.4% polarization). In this paper, NMR and X-ray crystallography are used to map the evolution of catalytically important species and provide mechanistic rational for catalytic efficiency. Furthermore, applications in spontaneous radiofrequency amplification by stimulated emission and NMR reaction monitoring are also shown.    

    

** Organocatalytic Asymmetric Synthesis of Si-Stereogenic Siloxanols   
:PROPERTIES:
:ID: https://openalex.org/W4390605731
:DOI: https://doi.org/10.1021/acscatal.3c03932
:AUTHORS: J. Dalton, Adolfo Sánchez, Austin T. Kelly, James C. Fettinger, Annaliese K. Franz
:HOST: ACS Catalysis
:END:

J. Dalton, Adolfo Sánchez, Austin T. Kelly, James C. Fettinger, Annaliese K. Franz, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03932")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390605731"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390605731"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390605731"))][Get cited by]]

OpenAlex: https://openalex.org/W4390605731
    
J. Dalton, Adolfo Sánchez, Austin T. Kelly, James C. Fettinger, Annaliese K. Franz, ACS Catalysis. https://doi.org/10.1021/acscatal.3c03932
    
We report the organocatalytic synthesis of Si-stereogenic compounds via desymmetrization of a prochiral silanediol with a chiral imidazole-containing catalyst. This metal-free silylation method affords high yields with enantioselectivity up to 98:2 for various silanediol and silyl chloride substrate combinations (including secondary alkyl, vinyl, and H groups), accessing products with potential for further elaboration. NMR and X-ray studies reveal insight into the H-bonding interactions between the imidazole organocatalyst and the silanediol and the dual activating role of the Lewis basic imidazole to account for the high enantioselectivity.    

    

** Issue Editorial Masthead   
:PROPERTIES:
:ID: https://openalex.org/W4390608796
:DOI: https://doi.org/10.1021/csv014i001_1756349
:AUTHORS: 
:HOST: ACS Catalysis
:END:

, ACS Catalysis. 14(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i001_1756349")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390608796"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390608796"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390608796"))][Get cited by]]

OpenAlex: https://openalex.org/W4390608796
    
, ACS Catalysis. https://doi.org/10.1021/csv014i001_1756349
    
ADVERTISEMENT RETURN TO ISSUEPREVArticleNEXTIssue Editorial MastheadCite this: ACS Catal. 2024, 14, 1, XXX-XXXPublication Date (Web):January 5, 2024Publication History Published online5 January 2024Published inissue 5 January 2024https://doi.org/10.1021/csv014i001_1756349Copyright © 2024 American Chemical SocietyRequest reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InReddit PDF (198 KB) Get e-Alertsclose Get e-Alerts    

    

** Issue Publication Information   
:PROPERTIES:
:ID: https://openalex.org/W4390612348
:DOI: https://doi.org/10.1021/csv014i001_1756348
:AUTHORS: 
:HOST: ACS Catalysis
:END:

, ACS Catalysis. 14(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i001_1756348")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390612348"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390612348"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390612348"))][Get cited by]]

OpenAlex: https://openalex.org/W4390612348
    
, ACS Catalysis. https://doi.org/10.1021/csv014i001_1756348
    
ADVERTISEMENT RETURN TO ISSUEPREVArticleIssue Publication InformationCite this: ACS Catal. 2024, 14, 1, XXX-XXXPublication Date (Web):January 5, 2024Publication History Published online5 January 2024Published inissue 5 January 2024https://doi.org/10.1021/csv014i001_1756348Copyright © 2024 American Chemical SocietyRequest reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InReddit PDF (153 KB) Get e-Alertsclose Get e-Alerts    

    

** Selective Photocatalytic Oxidation of Methane to Methanol by Constructing a Rapid O<sub>2</sub> Conversion Pathway over Au–Pd/ZnO   
:PROPERTIES:
:ID: https://openalex.org/W4390614279
:DOI: https://doi.org/10.1021/acscatal.3c04374
:AUTHORS: Qiang Zhang, Xiaojie Tan, Xinyu Wang, Qinhua Zhang, Chong Qi, Hao Yang, Zhengqiu He, Tao Xing, Mingqing Wang, Mingbo Wu, Wenting Wu
:HOST: ACS Catalysis
:END:

Qiang Zhang, Xiaojie Tan, Xinyu Wang, Qinhua Zhang, Chong Qi, Hao Yang, Zhengqiu He, Tao Xing, Mingqing Wang, Mingbo Wu, Wenting Wu, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04374")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390614279"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390614279"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390614279"))][Get cited by]]

OpenAlex: https://openalex.org/W4390614279
    
Qiang Zhang, Xiaojie Tan, Xinyu Wang, Qinhua Zhang, Chong Qi, Hao Yang, Zhengqiu He, Tao Xing, Mingqing Wang, Mingbo Wu, Wenting Wu, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04374
    
Photocatalytic oxidation of methane to methanol is an attractive process under mild conditions, nevertheless confronting significant challenges in achieving high conversion and selectivity simultaneously. Herein, we propose a strategy for the direct and rapid generation of hydroxyl radicals (•OH) from O2 (O2 → *OOH → •OH) by rational design of Au–Pd/ZnO photocatalyst, skipping water-soluble H2O2 and avoiding H2O2 diffusion. For photocatalytic methane oxidation at ambient temperature, the yield and selectivity of CH3OH over the optimized 1.0% AuPd0.5/ZnO catalyst were as high as 81.0 μmol·h–1 and 88.2%, respectively, exceeding that of most reported systems. The formation of Au–Pd alloys could improve the O2 adsorption and the cleavage of the O–O bond in *OOH, facilitating the efficient direct formation of •OH and increasing the CH3OH yield and selectivity. This work provides some guidance for the delicate design of composite photocatalysts for efficient selective photocatalytic methane oxidation and O2 utilization.    

    

** Advances in Single-Atom-Catalyzed Acetylene Hydrochlorination   
:PROPERTIES:
:ID: https://openalex.org/W4390617627
:DOI: https://doi.org/10.1021/acscatal.3c04495
:AUTHORS: Zhibing Chen, Saisai Wang, Jia Zhao, Ronghe Lin
:HOST: ACS Catalysis
:END:

Zhibing Chen, Saisai Wang, Jia Zhao, Ronghe Lin, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04495")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390617627"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390617627"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390617627"))][Get cited by]]

OpenAlex: https://openalex.org/W4390617627
    
Zhibing Chen, Saisai Wang, Jia Zhao, Ronghe Lin, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04495
    
The growing demand for polyvinyl chloride (PVC) calls for a cleaner technology for its production. Nonetheless, acetylene hydrochlorination, an industrially relevant technology for the manufacture of vinyl chloride monomer of PVC, is hampered by the use of toxic and volatile mercury chloride catalysts that pose severe threads to human health and the environments. This stimulated numerous research studies in the past decades on hunting alternative candidates to replace the mercury catalysts. Among the large numbers of catalyst families, distinct single-atom metal catalysts have been predicted or demonstrated as promising catalytic systems in the hydrochlorination chemistry, thus stimulating a wave in the broader explorations of this distinctive catalyst group in the last five years. In this Review, we summarize the recent advances of single-atom catalysts in acetylene hydrochlorination with the focus on their synthesis methods, catalytic performance, and reaction mechanism. The catalyst categories include single metal atoms of Au, Pt, Pd, Ru, Cu, and Fe and diatomic systems. Perspectives on the challenges and directions for future development regarding the innovation of synthetic strategies, recognition of performance descriptors, and developments of on-site characterization techniques are provided.    

    

** Broad Spectrum Enantioselective Amide Bond Synthetase from <i>Streptoalloteichus hindustanus</i>   
:PROPERTIES:
:ID: https://openalex.org/W4390636492
:DOI: https://doi.org/10.1021/acscatal.3c05656
:AUTHORS: Qingyun Tang, Mark Petchey, Benjamin Rowlinson, Thomas J. Burden, Ian J. S. Fairlamb, Gideon Grogan
:HOST: ACS Catalysis
:END:

Qingyun Tang, Mark Petchey, Benjamin Rowlinson, Thomas J. Burden, Ian J. S. Fairlamb, Gideon Grogan, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05656")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390636492"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390636492"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390636492"))][Get cited by]]

OpenAlex: https://openalex.org/W4390636492
    
Qingyun Tang, Mark Petchey, Benjamin Rowlinson, Thomas J. Burden, Ian J. S. Fairlamb, Gideon Grogan, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05656
    
The synthesis of amide bonds is one of the most frequently performed reactions in pharmaceutical synthesis, but the requirement for stoichiometric quantities of coupling agents and activated substrates in established methods has prompted interest in biocatalytic alternatives. Amide Bond Synthetases (ABSs) actively catalyze both the ATP-dependent adenylation of carboxylic acid substrates and their subsequent amidation using an amine nucleophile, both within the active site of the enzyme, enabling the use of only a small excess of the amine partner. We have assessed the ability of an ABS from Streptoalloteichus hindustanus (ShABS) to couple a range of carboxylic acid substrates and amines to form amine products. ShABS displayed superior activity to a previously studied ABS, McbA, and a remarkable complementary substrate specificity that included the enantioselective formation of a library of amides from racemic acid and amine coupling partners. The X-ray crystallographic structure of ShABS has permitted mutational mapping of the carboxylic acid and amine binding sites, revealing key roles for L207 and F246 in determining the enantioselectivity of the enzyme with respect to chiral acid and amine substrates. ShABS was applied to the synthesis of pharmaceutical amides, including ilepcimide, lazabemide, trimethobenzamide, and cinepazide, the last with 99% conversion and 95% isolated yield. These findings provide a blueprint for enabling a contemporary pharmaceutical synthesis of one of the most significant classes of small molecule drugs using biocatalysis.    

    

** Anaerobic Ammodehydrogenation of Ethane to Acetonitrile over Ga-Loaded H-FER Zeolite Catalysts   
:PROPERTIES:
:ID: https://openalex.org/W4390640476
:DOI: https://doi.org/10.1021/acscatal.3c05286
:AUTHORS: M. J. Huang, Xiaoming Hu, Duotian Chen, Zen Maeno, Nao Tsunoji, Takashi Toyao, Ken‐ichi Shimizu
:HOST: ACS Catalysis
:END:

M. J. Huang, Xiaoming Hu, Duotian Chen, Zen Maeno, Nao Tsunoji, Takashi Toyao, Ken‐ichi Shimizu, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05286")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390640476"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390640476"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390640476"))][Get cited by]]

OpenAlex: https://openalex.org/W4390640476
    
M. J. Huang, Xiaoming Hu, Duotian Chen, Zen Maeno, Nao Tsunoji, Takashi Toyao, Ken‐ichi Shimizu, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05286
    
A reaction of ethane (C2H6) with ammonia (NH3) over metal-loaded zeolites to yield acetonitrile (CH3CN) under the O2-free conditions was studied. Among the various metal-loaded zeolites, Ga/HFER with a Ga/Al ratio of 1.0 afforded the highest CH3CN yield. A Ga-free HFER and a Ga-loaded K-exchanged FER (Ga/KFER) were nearly inactive for the ammodehydrogenation of C2H6, indicating that both Ga and Brønsted acid sites are indispensable. Extended X-ray absorption fine structure (EXAFS) results show that the Ga2O3 species in the as-prepared Ga/HFER catalyst are converted to isolated Ga cations after C2H6 ammodehydrogenation at 650 °C, while the Ga2O3 species in Ga/KFER remained unchanged after the reaction. The results indicate that the Brønsted acid sites (exchangeable H+ sites) of HFER act as the anchoring site of the isolated Ga cations, possibly formed by reductive solid-state ion exchange during the reaction, and the isolated Ga sites act as active sites for C2H6 ammodehydrogenation. Kinetic analysis suggests that CH3CN is produced via a consecutive reaction pathway: the dehydrogenation of C2H6 to ethylene (C2H4), which reacts with NH3 to give CH3CN. The co-feeding of O2 to C2H6 + NH3 significantly decreased the CH3CN yield and formation of CO2 and CO as the main products, suggesting the importance of reductive conditions in the current catalytic system.    

    

** Evidence for Exclusive Direct Mechanism of Urea Electro-Oxidation Driven by <i>In Situ-</i>Generated Resilient Active Species on a Rare-Earth Nickelate   
:PROPERTIES:
:ID: https://openalex.org/W4390647001
:DOI: https://doi.org/10.1021/acscatal.3c04967
:AUTHORS: Nikhil N. Rao, Chandraraj Alex, Moumita Mukherjee, Subir Roy, Akhil Tayal, Ayan Datta, Neena S. John
:HOST: ACS Catalysis
:END:

Nikhil N. Rao, Chandraraj Alex, Moumita Mukherjee, Subir Roy, Akhil Tayal, Ayan Datta, Neena S. John, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04967")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390647001"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390647001"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390647001"))][Get cited by]]

OpenAlex: https://openalex.org/W4390647001
    
Nikhil N. Rao, Chandraraj Alex, Moumita Mukherjee, Subir Roy, Akhil Tayal, Ayan Datta, Neena S. John, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04967
    
Stabilization of active NiOOH species for achieving exclusive operation of the direct mechanism of the urea electro-oxidation reaction (UOR) presents a formidable challenge. Despite the extensive repertoire of UOR electrocatalysts developed so far, the sustenance of active NiOOH species throughout the reaction remains unaccomplished due to the predominant operation of the indirect mechanism that involves the reduction of NiOOH into Ni(OH)2 during electrocatalysis. The capability of a UOR electrocatalyst to retain the active species is of paramount importance as it ensures the optimal engagement of the maximum pool of active Ni centers in the electrocatalytic process, resulting in enhanced activity with reduced Ni mass loading. In this context, the present study unveils the electrocatalytic UOR capability of a rare-earth nickelate, NdNiO3, showcasing high UOR activity with a reduced burden of Ni mass loading. From the detailed cyclic voltammetry studies, in situ X-ray absorption spectroscopy, and impedance analyses, it has been substantiated that NdNiO3 triggers the UOR to proceed through the unconventional direct mechanism, obviating the need for catalyst regeneration during UOR. The adsorption free energy calculation of reactants such as urea, OH– ions, and product CO2 reveals that NdNiO3 effectively interacts with the reactants, and its surface is highly tolerant toward COx poison when compared to NiO. The preferential direct mechanism of UOR, enhanced mass activity, and commendable resistance against COx poisons emanate from the more facile formation and effective stabilization of active NiOOH species on NdNiO3.    

    
