#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Wed Jun 12 01:08:48 2024

Found 4 results from 2024-06-05 to 2024-06-12
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Lattice Oxygen Activation Triggered by Ultrasonic Shock Significantly Improves NO Selective Catalytic Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399320398
:TOPICS: Catalytic Nanomaterials, Gas Sensing Technology and Materials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02400")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399320398"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399320398"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399320398"))][Get cited by]]

OpenAlex: https://openalex.org/W4399320398 (Open access: False)
    
[[https://openalex.org/A5062755510][Wei Wang]], [[https://openalex.org/A5048705700][Baoli Zhu]], [[https://openalex.org/A5007189808][Songil Sin]], [[https://openalex.org/A5009232540][Zhiqiang Zhang]], [[https://openalex.org/A5019998681][Chong Tan]], [[https://openalex.org/A5081365566][Zhiwen Gu]], [[https://openalex.org/A5008346918][Song Wang]], [[https://openalex.org/A5025583524][Chunkai Huang]], [[https://openalex.org/A5077934134][Min Tao]], [[https://openalex.org/A5051618631][Chenghua Zhang]], [[https://openalex.org/A5065664936][Changjin Tang]], [[https://openalex.org/A5073123246][Lin Dong]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02400 
     
The precise regulation of lattice oxygen is crucial for many redox reactions, but it still remains a formidable challenge. Herein, we reported a facile strategy to induce generation of bulk phase defects in hematite (α-Fe2O3) by ultrasonic treatment, thus achieving exclusive lattice oxygen activation without additional alternation of surface adsorbed oxygen species. This kind of unique lattice oxygen activation afforded negligible disturbance of NH3 adsorption but significant influence on NO2 generation via accelerated oxygen diffusion, resulting in enhanced activity contribution from the Fast-SCR reaction pathway. Particularly, the generation of bulk-phase defects was also found to be conducive to create thermally instable and chemically reactive surface nitrate species, which played a decisive role in activating NO reactant. Accordingly, a triple increment in the deNOx performance of the α-Fe2O3 catalyst for the reaction of selective catalytic reduction of NO with NH3 (NH3–SCR) was achieved.    

    

* Photocatalytic Reductive Functionalization of Aryl Alkynes via Alkyne Radical Anions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399322479
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02638")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399322479"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399322479"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399322479"))][Get cited by]]

OpenAlex: https://openalex.org/W4399322479 (Open access: False)
    
[[https://openalex.org/A5064380782][Xiaogang Tong]], [[https://openalex.org/A5052777600][Zugen Wu]], [[https://openalex.org/A5078764952][Hwee Ting Ang]], [[https://openalex.org/A5010126241][Yinxing Miao]], [[https://openalex.org/A5066554626][Yixin Lü]], [[https://openalex.org/A5038927058][Jie Wu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02638 
     
The direct reductive functionalization of alkynes under mild conditions presents a promising yet challenging avenue for accessing value-added molecules. Alkyne radical anions represent a distinct class of reactive intermediates characterized by both a charge and an unpaired electron, thus holding great potential for facilitating diverse bond formations, particularly in alkyne reductive functionalization. However, the synthetic utility of alkyne radical anions is limited, primarily due to the difficulty in their generation and the formation of highly unstable vinyl radical intermediates. In this study, we accomplished the direct generation of alkyne radical anions from aryl alkyne feedstocks via single electron transfer (SET) reduction with photogenerated CO2 radical anion (CO2•–), enabling reductive hydroalkylation, arylalkenylation, and hydrocarboxylation of aryl alkynes. Our photocatalytic strategy features metal-free catalysis, mild reaction conditions, employment of a traceless reductant, good functional group compatibility, step- and atom-economy, and high regioselectivity. This study not only paves the way for leveraging the underexplored alkyne radical anions but also catalyzes the ongoing exploration of the bifunctional CO2•– species in synthetic chemistry.    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399440714
:TOPICS: 
:PUBLICATION_DATE: 2024-06-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i011_1809724")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399440714"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399440714"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399440714"))][Get cited by]]

OpenAlex: https://openalex.org/W4399440714 (Open access: False)
    
, ACS catalysis. 14(11)] 2024. https://doi.org/10.1021/csv014i011_1809724 
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399440731
:TOPICS: 
:PUBLICATION_DATE: 2024-06-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i011_1809725")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399440731"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399440731"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399440731"))][Get cited by]]

OpenAlex: https://openalex.org/W4399440731 (Open access: False)
    
, ACS catalysis. 14(11)] 2024. https://doi.org/10.1021/csv014i011_1809725 
     
No abstract    

    
