#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sat Aug 31 01:15:07 2024

Found 8 results from 2024-08-24 to 2024-08-31
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* On the pH Dependency of the Catalysis by a Lytic Polysaccharide Monooxygenase from the Fungus Trichoderma reesei  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401801713
:TOPICS: Technologies for Biofuel Production from Biomass, Microbial Enzymes and Biotechnological Applications, Metabolic Engineering and Synthetic Biology
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03041")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401801713"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401801713"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401801713"))][Get cited by]]

OpenAlex: https://openalex.org/W4401801713 (Open access: True)
    
[[https://openalex.org/A5016853558][Silja Kuusk]], [[https://openalex.org/A5010770781][Maarja Lipp]], [[https://openalex.org/A5081196995][Surabhi Mahajan]], [[https://openalex.org/A5069713400][Priit Väljamäe]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03041 
     
Lytic polysaccharide monooxygenases (LPMOs) catalyze the oxidative cleavage of glycosidic bonds in industrially important polysaccharides like cellulose. The activity of these monocopper enzymes depends on the presence of H2O2 cosubstrate and reductant. Besides the polysaccharide peroxygenase reaction, LPMOs catalyze reductant oxidase and peroxidase side reactions. The multiplicity and interplay between different LPMO reactions hamper the interpretation of the kinetic data, which is best reflected by the scarcity of the studies of the pH dependency of the LPMO catalysis. Here, we studied the pH dependency of the reductant oxidase/peroxidase as well as the cellulose peroxygenase reactions of TrAA9A, an LPMO from the fungus Trichoderma reesei. The pH dependency of reductant oxidase/peroxidase reaction was governed by the rate-limiting step (reduction of LPMO-Cu(II) or reoxidation of LPMO-Cu(I)) depending on the experimental conditions. The pH dependency of the kcat and Km(H2O2) of the cellulose peroxygenase reaction was best described by the single base catalysis with pKa around 3.5–4.0. Experiments made in D2O showed isotope effects but only at pD values below 5.0. The conserved second coordination sphere histidine (His163) is the most probable candidate responsible for shaping the pH dependency of the TrAA9A peroxygenase reaction. We propose that the double protonation of His163 at acidic pH alters its conformation to the catalytically incompetent one. However, the little pH dependency of the kcat/Km(H2O2) of the cellulose peroxygenase reaction suggests that at very low H2O2 concentrations, TrAA9A may be efficient catalyst also in the acidic conditions that prevail in fungal habitats.    

    

* Regioselective Enzymatic Galactosylation Enabled Divergent Synthesis of Asymmetrical Biantennary Human Milk Oligosaccharides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401811657
:TOPICS: Composition and Health Effects of Human Milk, Chemical Glycobiology and Therapeutic Applications, Glycosylation in Health and Disease
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03373")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401811657"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401811657"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401811657"))][Get cited by]]

OpenAlex: https://openalex.org/W4401811657 (Open access: False)
    
[[https://openalex.org/A5080791772][Hui Xia]], [[https://openalex.org/A5075894101][Kan Zhong]], [[https://openalex.org/A5100655153][Yun Li]], [[https://openalex.org/A5039458434][Jinfeng Ye]], [[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5077907557][Chao Cai]], [[https://openalex.org/A5085774449][Wanmeng Mu]], [[https://openalex.org/A5065426391][Changcheng Liu]], [[https://openalex.org/A5050152196][Hongzhi Cao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03373 
     
Human milk oligosaccharides (HMOs) are essential nutritional and bioactive components of human breast milk, conferring numerous beneficial effects on neonatal health. The HMO repertoire comprises over 200 unique glycan structures, and more than half of them are branched oligosaccharides. Owing to the structural diversity and complexity, the synthesis of branched HMOs remains challenging, which significantly hinders their functional study. We herein present a highly efficient biomimetic approach for the rapid and scaled-up chemoenzymatic synthesis of asymmetrical biantennary HMOs. Taking advantage of the inherent regioselectivity of a panel of bacterial galactosyltransferases, two asymmetrical branched pentasaccharide intermediates were obtained through the regioselective enzymatic β1,3- or β1,4-galactosylation of a readily available chemically synthesized biantennary symmetrical tetrasaccharide precursor. The two asymmetrical pentasaccharide intermediates were further diversified by sequential multienzyme cascade reactions to afford a library of over 20 structurally well-defined asymmetrical biantennary lacto-N-hexaose (LNH) and lacto-N-neo-hexaose (LNnH) series HMOs in less than 5 linear steps.    

    

* Computational Insights for Electrocatalytic Synthesis of Glycine  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401813492
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04263")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401813492"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401813492"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401813492"))][Get cited by]]

OpenAlex: https://openalex.org/W4401813492 (Open access: False)
    
[[https://openalex.org/A5102812336][Jian Lin]], [[https://openalex.org/A5030617408][Jun Long]], [[https://openalex.org/A5102669510][Xiaoyan Fu]], [[https://openalex.org/A5027648567][Dong Luan]], [[https://openalex.org/A5102537365][Pu Guo]], [[https://openalex.org/A5051717534][Huijuan Jing]], [[https://openalex.org/A5100319216][Huan Li]], [[https://openalex.org/A5004947752][Jianping Xiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04263 
     
No abstract    

    

* Photochemical Asymmetric Palladium-Catalyzed Allylation Reaction: Expeditious Entry to Chiral 1,2-Amino Alcohols and 1,2-Diamines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401821535
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-08-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04209")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401821535"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401821535"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401821535"))][Get cited by]]

OpenAlex: https://openalex.org/W4401821535 (Open access: False)
    
[[https://openalex.org/A5048668242][Hui Xie]], [[https://openalex.org/A5038196911][Haohua Chen]], [[https://openalex.org/A5009073078][Uttam Dutta]], [[https://openalex.org/A5061000219][Yu Lan]], [[https://openalex.org/A5067624195][Bernhard Breit]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04209 
     
The construction of diverse alkyl amines is of importance in drug discovery and natural product synthesis. Herein, we report an efficient photoredox/palladium dual catalysis for the construction of protected 1,2-amino alcohols and 1,2-diamines via the asymmetric allylation of α-silyl amines with heteroatom-substituted allenes and 1,3-dienes. This protocol is characterized by its mild conditions, high regio- and enantioselectivities, and wide substrate scope, including aliphatic amines or N-heterocyclic substrates especially. Computational and experimental mechanistic studies indicate that the reaction proceeds through a sequence of oxidative addition of the Pd(0) catalyst by PPTS, allene insertion, outer-sphere radical substitution-type C–C bond formation, and reduction of Pd(I) by Ir(II). Thereinto, the outer-sphere radical substitution is the enantio- and regioselectivity determining step.    

    

* Nitrogen-Rich Carbon Dots as Effective Catalysts in the 1,4-Reduction of α,β-Unsaturated Aldehydes via Ion Pair Asymmetric Nano-Organocatalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401844482
:TOPICS: Aromaticity in Organic Molecules and Materials, Engineering of Surface Nanostructures, Synthesis and Applications of Carbon Quantum Dots
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03532")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401844482"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401844482"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401844482"))][Get cited by]]

OpenAlex: https://openalex.org/W4401844482 (Open access: False)
    
[[https://openalex.org/A5092689902][Alessio Carioscia]], [[https://openalex.org/A5084092290][Emanuele Cocco]], [[https://openalex.org/A5077619653][Maria Edith Casacchia]], [[https://openalex.org/A5032908255][Giuseppe Gentile]], [[https://openalex.org/A5030617180][Martina Mamone]], [[https://openalex.org/A5075714745][Giuliana Giorgianni]], [[https://openalex.org/A5106702204][Elena Incerto]], [[https://openalex.org/A5074191348][Maurizio Prato]], [[https://openalex.org/A5011629137][Fabio Pesciaioli]], [[https://openalex.org/A5080131431][Giacomo Filippini]], [[https://openalex.org/A5051354092][Armando Carlone]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03532 
     
The development of nanostructured organocatalysts is emerging as a prominent field in materials science. To this purpose, nitrogen-doped carbon dots (CDs) have been effectively employed in enantioselective enamine organocatalysis. On the other hand, enantioselective iminium ion nano-organocatalysis is much less explored. In this Letter, the use of CDs in asymmetric iminium ion catalysis via asymmetric counteranion-directed catalysis (ACDC) is disclosed. Nonchiral CDs bearing butylenediamine residues proved to be the most effective ones, in combination with (S)-TRIP as a chiral phosphoric acid (CPA). A correlation between the features of the CDs' surfaces and their catalytic performance was shown, and the catalytic activity of the employed CDs proved to be higher than that of simple molecular amines. An extensive reaction optimization allowed the reduction of different α,β-unsatured aldehydes in good yield and ee, using a low catalyst loading.    

    

* Confined Intermediates Boost C2+ Selectivity in CO2 Electroreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401804406
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02823")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401804406"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401804406"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401804406"))][Get cited by]]

OpenAlex: https://openalex.org/W4401804406 (Open access: False)
    
[[https://openalex.org/A5076563007][Wanhe Li]], [[https://openalex.org/A5018648007][Yahui Chen]], [[https://openalex.org/A5001719072][Chengqi Guo]], [[https://openalex.org/A5090614452][Shuhan Jia]], [[https://openalex.org/A5008204312][Yiying Zhou]], [[https://openalex.org/A5104324143][Zhonghuan Liu]], [[https://openalex.org/A5045685070][Enhui Jiang]], [[https://openalex.org/A5086071359][Xiaoke Chen]], [[https://openalex.org/A5101745373][Yue Zou]], [[https://openalex.org/A5000294498][Pengwei Huo]], [[https://openalex.org/A5100769787][Yongsheng Yan]], [[https://openalex.org/A5102776020][Zhi Zhu]], [[https://openalex.org/A5018028838][Yun Hau Ng]], [[https://openalex.org/A5048175359][Yanjun Gong]], [[https://openalex.org/A5017414280][John C. Crittenden]], [[https://openalex.org/A5024670135][Yan Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02823 
     
Addressing the efficient electrochemical conversion of CO2 (CO2RR) into valuable multicarbon (C2+) products necessitates innovative strategies to boost carbon (C1) intermediate coupling on catalyst surfaces. In this work, we introduce a surface-confinement strategy on Cu2O nanoparticles by long alkyl chain grafting to create a spatially confined environment, impeding C1 intermediate detachment and promoting C–C coupling in the CO2RR. The optimized C12–Cu2O sample exhibits a Faradaic efficiency (FE) over 63.0% for C2H4, more than double the yield of pristine Cu2O (FE = 25.7%). In situ ATR-FTIR spectroscopy provides direct evidence of rapid C1 intermediate enrichment and restricted diffusion within the surface-confined environment. Molecular dynamics simulations further support these findings by identifying a prolonged residency time that is proportionate to the alkyl chain length, thereby maximizing C2+ selectivity. This surface-confinement approach marks a previously overlooked but immensely promising paradigm in the catalyst design for the CO2RR.    

    

* Highly Stereoselective Biocatalytic One-Pot Synthesis of Chiral Saturated Oxygen Heterocycles by Integration of a Biosynthetic Heterocyclase into Multiple-Enzyme Cascades  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401805036
:TOPICS: Enzyme Immobilization Techniques, Olefin Metathesis Chemistry, Natural Products as Sources of New Drugs
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03692")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401805036"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401805036"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401805036"))][Get cited by]]

OpenAlex: https://openalex.org/W4401805036 (Open access: True)
    
[[https://openalex.org/A5106676089][Theresa Roß-Taschner]], [[https://openalex.org/A5023822759][Sebastian Derra]], [[https://openalex.org/A5011904429][Jörg Stang]], [[https://openalex.org/A5038826554][Luca Schlotte]], [[https://openalex.org/A5106676090][Anthony Putratama]], [[https://openalex.org/A5047800381][Frank Hahn]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03692  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c03692][pdf]])
     
The secondary metabolism is a rich source of enzymes with new synthetically attractive activities that have not yet been integrated into the toolbox of biocatalysis. Chiral saturated oxygen heterocycles (CSOHs) are abundant structural elements of natural products and other value-added compounds. We present a biocatalytic method for the synthesis of CSOHs from readily accessible precursors that combines an intramolecular oxa-Michael addition (IMOMA)-catalyzing cyclase (CYC) from a biosynthetic pathway with alcohol dehydrogenases (ADHs) and thioester-derivatizing enzymes. The one-pot ADH–CYC reaction enables access to various tetrahydropyran (THP) and tetrahydrofuran thioesters under control of up to four stereocenters. These products are readily convertible into useful CSOH ketone, amide, aldehyde/alcohol, ester, and carboxylic acid building blocks by chemical and enzymatic means. The extendibility to more complex multienzyme cascades was demonstrated by the addition of a thioesterase and a carboxylic acid reductase, allowing the straightforward chemoenzymatic synthesis of the natural product (−)-civet, a new derivative, and a THP alcohol. The integration of IMOMA cyclases into enzymatic cascades allows better exploitation of the high synthetic potential of this new group of ring-forming enzymes and expands the repertoire for the synthesis of pharmacologically relevant CSOHs as a highly selective and versatile alternative. This approach will be adaptable for the synthesis of a wide range of CSOHs by varying ADHs, IMOMA cyclases, and modifying enzymes.    

    

* A Career in Catalysis: Mark E. Davis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401813537
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Mesoporous Materials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03617")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401813537"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401813537"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401813537"))][Get cited by]]

OpenAlex: https://openalex.org/W4401813537 (Open access: True)
    
[[https://openalex.org/A5091311605][Juan P. Arhancet]], [[https://openalex.org/A5010159566][Cong-Yan Chen]], [[https://openalex.org/A5069088464][Viktor J. Cybulskis]], [[https://openalex.org/A5072511676][Rajamani Gounder]], [[https://openalex.org/A5017416587][Suk Bong Hong]], [[https://openalex.org/A5052807182][Christopher W. Jones]], [[https://openalex.org/A5076816392][Jong Hun Kang]], [[https://openalex.org/A5100635639][Yoshihiro Kubota]], [[https://openalex.org/A5100695063][Hyunjoo Lee]], [[https://openalex.org/A5040695374][Marat Orazov]], [[https://openalex.org/A5016487357][Yuriy Román‐Leshkov]], [[https://openalex.org/A5018333095][Joel E. Schmidt]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03617 
     
Mark E. Davis led an independent research program from 1981 to 2023, beginning at the Virginia Polytechnic Institute and State University (VPI) and then transitioning to the California Institute of Technology (Caltech). His research program was marked by exceptional creativity, breadth, and depth. With classical training in reaction engineering, Davis developed expertise in experimental heterogeneous catalysis and led work in this discipline for more than 40 years. His name is synonymous with zeolites, and today, he is one of the most widely recognized experts in zeolite synthesis, characterization, and catalysis in the world. Early work at the VPI focused on zeolites and catalysis with supported metal coordination complexes. His creativity was evident at the earliest stages of his career, with the development of supported aqueous phase catalysts and the world's first crystalline, extra-large pore molecular sieve, both reported in the late 1980s. A move to Caltech saw a significant expansion of his zeolite synthesis program and the rapid acceleration of a multidecade collaboration with Dr. Stacey I. Zones of Chevron. At Caltech, his work expanded to include studies of molecular recognition and catalysis with organic/inorganic hybrid materials, and he developed a large, parallel program in drug delivery. His work on catalysis heavily emphasized zeolite catalysis, including major thrusts on the conversion of sugars in the liquid phase and methanol in the gas phase. Numerous new zeolites and molecular sieves were discovered throughout the four decades of the Davis laboratory, highlighted by a successful, multidecade quest to prepare a chiral zeolite with enantioselective catalytic properties. Davis is one of the most decorated researchers of the last four decades. He is one of only 21 living people currently elected to all of the US National Academies (Engineering, Science, Medicine) and elected as a Fellow of the National Academy of Inventors. He was the first engineer to win the NSF's Alan T. Waterman Award and is one of only two researchers (to date) to win the International Zeolite Association's Donald Breck Award twice (1989, 2019). Awards from the ACS (Ipatieff, Murphree, and Somorjai Awards), AIChE (Colburn, Professional Progress Awards), and North American Catalysis Society (Emmett Award) are among his accolades.    

    
