#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Thu Jan 16 01:18:45 2025

Found 19 results from 2025-01-09 to 2025-01-16
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* A New Look at Catalyst Surfaces at Work: Introducing Mixed Isotope Operando Infrared Spectroscopy (MIOIRS)  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406170106
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Catalysts for Methane Reforming
:PUBLICATION_DATE: 2025-01-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06308")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406170106"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406170106"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406170106"))][Get cited by]]

OpenAlex: https://openalex.org/W4406170106 (Open access: True)
    
[[https://openalex.org/A5004127604][Matteo Monai]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06308 
     
This Perspective focuses on the characterization of supported metal catalysts by operando and CO infrared (IR) spectroscopy. CO IR spectroscopy is a powerful technique for probing catalyst surfaces and is used to identify single-atom catalysts, estimate metal surface availability to the gas phase, and measure catalyst Lewis acidity. However, the interpretation of CO IR spectra on metal surfaces is not trivial and is influenced by dipole–dipole interactions among CO molecules at medium to high coverage. Such a phenomenon results in spectral distortions, such as intensity transfer among IR bands, the appearance of spurious bands, and shifts in band position. Dipole–dipole interactions were widely investigated and understood from the 1950s to 1990s, but the implications for operando spectroscopy have been seemingly overlooked in the literature, with a few exceptions. Inspired by seminal studies in the field, I propose here the use of mixed isotopic streams, such as diluted 13CO in 12CO, to reduce dipole coupling effects and retrieve more information from operando IR spectra in reactions involving CO, such as CO oxidation or hydrogenation reactions. Similarly, mixed 13CO2/12CO2 streams may be applied in CO2 hydrogenation, where adsorbed CO is commonly observed. The proposed name of the technique is Mixed Isotope Operando IR Spectroscopy, MIOIRS. In this Perspective, I will first summarize the nature of dipole–dipole interactions in adsorbed CO layers and their effects on CO IR spectra. Then, I will briefly describe how diluted isotopic mixtures of CO can partially break the coupling among adsorbates and reduce spectral distortion. In both sections, I will give a few showcases of the implications of vibrational coupling in the characterization of heterogeneous catalysts. Finally, I will discuss the possible implications of MIOIRS for the detection and quantification of defect and surface sites on metal nanoparticles, the characterization of bimetallic nanoparticles surfaces, and the kinetics of CO intermediates adsorbed on different active sites. Notably, MIOIRS may be expanded to other reactions in which adsorbates have strong permanent dipoles, such as in self-catalytic reduction for NOx abatement.    

    

* New Insights into the Roles of Surface and Lattice Hydrogen in Electrocatalytic Hydrogen Oxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406183003
:TOPICS: Electrocatalysts for Energy Conversion, Fuel Cells and Related Materials, Catalytic Processes in Materials Science
:PUBLICATION_DATE: 2025-01-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06133")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406183003"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406183003"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406183003"))][Get cited by]]

OpenAlex: https://openalex.org/W4406183003 (Open access: False)
    
[[https://openalex.org/A5054938102][Pengcheng Zhao]], [[https://openalex.org/A5101841629][Li Deng]], [[https://openalex.org/A5067485627][Chang Sun]], [[https://openalex.org/A5100674281][Xiang Li]], [[https://openalex.org/A5101433644][Xiaoyu Tian]], [[https://openalex.org/A5090464557][Zhuo Li]], [[https://openalex.org/A5035964409][Wenchao Sheng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06133 
     
No abstract    

    

* Decorating Cu Nanoparticles with Pd Clusters for Enhanced Nitrile Electro-Hydrogenation to Primary Amines by Effective Hydrogen Spillover  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406187801
:TOPICS: Nanomaterials for catalytic reactions, Ammonia Synthesis and Nitrogen Reduction, Advanced Photocatalysis Techniques
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06206")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406187801"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406187801"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406187801"))][Get cited by]]

OpenAlex: https://openalex.org/W4406187801 (Open access: False)
    
[[https://openalex.org/A5101524851][Peipei Zhu]], [[https://openalex.org/A5103175383][Mingzhu Shi]], [[https://openalex.org/A5025223993][Bing Wu]], [[https://openalex.org/A5016300822][Xunfan Liao]], [[https://openalex.org/A5026978305][Mengning Ding]], [[https://openalex.org/A5088447996][Longbin Li]], [[https://openalex.org/A5079785501][Yiwang Chen]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06206 
     
The H2O-participating electrochemical hydrogenation (ECH) of benzonitrile represents a mild and efficient method for benzylamine synthesis, but the kinetics and Faraday efficiency are still limited. Herein, the developed Pd clusters dispersed Cu nanoparticles encapsulated in porous carbon (Pdn-Cu@C) achieves efficient ECH of benzonitrile (C6H5CN) to benzylamines (C6H5CH2NH2). In situ infrared spectroscopy and theoretical studies reveal that the Pd/Cu interface functions as the active site for active hydrogen (*H) generated by H2O dissociation, enhances the adsorption of C6H5CN, and weakens the adsorption of C6H5CH2NH2. Moreover, the Gibbs free energy barriers for *H spillover are much lower than that of *H self-coupling. As expected, Pdn-Cu@C exhibits efficient electro-hydrogenation of C6H5CN with the conversion of 97.42%, a high C6H5CH2NH2 selectivity of 97.21%, and Faradaic efficiency of 92.10% under a specific voltage. This finding blazes a feasible trail to suppress the competitive *H self-coupling and offers insights for multistep protonation ECH reactions.    

    

* Reactions of Surface Peroxides Contribute to Rates and Selectivities for C2H4 Epoxidation on Silver  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406196996
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Advanced Photocatalysis Techniques
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06945")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406196996"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406196996"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406196996"))][Get cited by]]

OpenAlex: https://openalex.org/W4406196996 (Open access: True)
    
[[https://openalex.org/A5060751897][Ching‐Tien Chen]], [[https://openalex.org/A5039715757][Anna Sviripa]], [[https://openalex.org/A5061073595][Sandeep Verma]], [[https://openalex.org/A5034428503][Christopher Paolucci]], [[https://openalex.org/A5062793974][David W. Flaherty]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06945 
     
Partial oxidation of ethylene over silver catalysts produces more than 30 million metric tons of ethylene oxide (EO) annually. However, the form of active silver surfaces, reactive oxygen species, and dominant pathways of this chemical reaction remains controversial despite decades of research. Here, we use operando Raman spectroscopy and transient kinetic measurements to demonstrate that higher coverages of peroxide species, present only upon Ag oxide surfaces that form in situ, correlate with greater selectivities to EO. Ab initio calculations reveal that the reconstructed Ag oxides preferentially stabilize diatomic oxygen species (peroxide and superoxide) under relevant conditions, and these species contribute to the selective formation of EO. The dominant reaction pathways change with surface coverages; however, bound O2 consistently activates by reaction with C2H4, and products form subsequently through peroxo- and oxometallacycle surface complexes. Taken together, density functional theory calculations and kinetic and transient experimental measurements show that the formation of peroxide intermediates requires oxidation of the Ag surface (via subsurface oxygen), and an increase in surface peroxides coincides with the highest EO selectivity for the unpromoted Ag catalyst. These findings suggest that the promoters ubiquitous for ethylene epoxidation (e.g., chlorine, transition metals, and alkali metals) may succeed by oxidation of Ag and increasing coverages of peroxides at industrial conditions.    

    

* Pendant Catechol Group Improves the Performance of Iron Porphyrin CO2 Reduction Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406199451
:TOPICS: CO2 Reduction Techniques and Catalysts, Metal-Catalyzed Oxygenation Mechanisms, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05531")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406199451"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406199451"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406199451"))][Get cited by]]

OpenAlex: https://openalex.org/W4406199451 (Open access: False)
    
[[https://openalex.org/A5032471432][Ana Sonea]], [[https://openalex.org/A5000268359][Jeffrey J. Warren]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05531 
     
No abstract    

    

* Hydrogen-Assisted Dissociation of N2: Prevalence and Consequences for Ammonia Synthesis on Supported Ru Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406201945
:TOPICS: Ammonia Synthesis and Nitrogen Reduction, Caching and Content Delivery, Nanomaterials for catalytic reactions
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06966")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406201945"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406201945"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406201945"))][Get cited by]]

OpenAlex: https://openalex.org/W4406201945 (Open access: False)
    
[[https://openalex.org/A5102283975][Yukun Bai]], [[https://openalex.org/A5078898024][Yuanbao Zhang]], [[https://openalex.org/A5100781690][Jianhua Hu]], [[https://openalex.org/A5101444480][Li Jiang]], [[https://openalex.org/A5039790894][Shaolong Wan]], [[https://openalex.org/A5045372639][Jingdong Lin]], [[https://openalex.org/A5100424488][Yong Wang]], [[https://openalex.org/A5100328291][Shuai Wang]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06966 
     
Understanding the roles of coadsorbates on crowded catalytic surfaces is critical to optimizing industrial catalysts that are generally employed under high-pressure conditions. For ammonia synthesis from N2 hydrogenation (i.e., the Haber–Bosch process), it is well-known that supported Ru catalysts tend to be highly covered by atomic H species, while the impact of these H species on N2 activation is still under controversy. Herein, kinetic assessment, isotopic labeling experiments, and in situ spectroscopic characterization were combined to investigate the mechanism of ammonia synthesis on Ru/CeO2 catalysts with their structure tuned via thermal treatments. Our experimental approaches reveal that the dominant H* surface species limit the availability of vacant Ru sites for the widely proposed direct N2 dissociation route but instead lead to the prevalence of the H-assisted N2 dissociation route with the N–N cleavage in N2H* intermediates as a kinetically relevant step. Effects of Ru particle size and Ru–CeO2 interaction on the catalytic activity were kinetically deconvoluted in accordance with this H-assisted mechanism, unveiling their decisive influences on intrinsic activity and surface coverage, respectively. Driven by these fundamental insights gained from the working conditions, superior ammonia formation rates were achieved for supported Ru catalysts via optimizing Ru particle size and metal–support interaction collaboratively.    

    

* Manipulating the Adjacent Microenvironment of Atomically Dispersed FeN4 Sites via Cross-Link-Induced 3D Carbon Nest for Efficient Oxygen Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406210421
:TOPICS: Electrocatalysts for Energy Conversion, Advanced Photocatalysis Techniques, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06546")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406210421"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406210421"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406210421"))][Get cited by]]

OpenAlex: https://openalex.org/W4406210421 (Open access: False)
    
[[https://openalex.org/A5037064171][Tonghui Zhao]], [[https://openalex.org/A5102751314][Guangjin Wang]], [[https://openalex.org/A5101846257][Dongdong Xiao]], [[https://openalex.org/A5103217976][Min Young Song]], [[https://openalex.org/A5050705685][Yanmin Hu]], [[https://openalex.org/A5017926967][Tingting Chao]], [[https://openalex.org/A5100404467][Yapeng Li]], [[https://openalex.org/A5035786530][Zedong Zhang]], [[https://openalex.org/A5019388394][Yun Lu]], [[https://openalex.org/A5022215689][Mingxing Gong]], [[https://openalex.org/A5100611244][Tao Shen]], [[https://openalex.org/A5100780460][Deli Wang]], [[https://openalex.org/A5060906740][Huile Jin]], [[https://openalex.org/A5042841794][Dingsheng Wang]], [[https://openalex.org/A5100344483][Wei Chen]], [[https://openalex.org/A5100348455][Yadong Li]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06546 
     
Electronic perturbation induced by the microenvironment regulation adjacent to the FeN4 sites anchored on metal–N–C materials will accelerate its oxygen reduction reaction (ORR) kinetics. Herein, we report a fine-tuning in the charge configuration of FeN4 sites through a defect-rich N/S-doped carbon nest derived from the chemically cross-linked pyrrole/thiophene copolymer (CCPPT) with a sp3-hybridized cross-linker. Compared with the pyrrole/thiophene copolymer (PPT) without the cross-linker, CCPPT with a knitted three-dimensional (3D) network delivers higher defect density and ∼2-fold sulfur retention after pyrolysis. The structural characterizations combined with theoretical calculations suggest that adjacent vacancy defects (Cvd) and FeN4/S2 moiety together induce the charge redistribution of the FeN4 sites on the resultant CC-Fe1/NSC from CCPPT, reducing the adsorption strength of the oxygen-containing intermediates and the energy barrier of ORR. As expected, CC-Fe1/NSC shows an impressive half-wave potential of ∼0.91 V vs reversible hydrogen electrode (RHE), surpassing both the PPT-derived Fe1/NSC (0.88 V) and the commercial Pt/C (0.86 V). This work provides a distinctive path to manipulate the adjacent microenvironment of the single-atom catalysts toward ORR or even beyond.    

    

* Recent Advances in Catalytic Asymmetric Ketone Allylations and Their Applications  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406210431
:TOPICS: Asymmetric Synthesis and Catalysis, Asymmetric Hydrogenation and Catalysis, Synthetic Organic Chemistry Methods
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07194")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406210431"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406210431"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406210431"))][Get cited by]]

OpenAlex: https://openalex.org/W4406210431 (Open access: False)
    
[[https://openalex.org/A5115592240][Lie Wang]], [[https://openalex.org/A5044342332][Ruoshi Jin]], [[https://openalex.org/A5059049464][Yiyuan Peng]], [[https://openalex.org/A5005159477][Qiuping Ding]], [[https://openalex.org/A5080607495][Xing‐Ping Zeng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c07194 
     
No abstract    

    

* Brønsted Acid-Facilitated Thioetherification Cross-Coupling Reactions with Nickel and Visible Light  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406210452
:TOPICS: Sulfur-Based Synthesis Techniques, Radical Photochemical Reactions, Catalytic C–H Functionalization Methods
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06734")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406210452"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406210452"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406210452"))][Get cited by]]

OpenAlex: https://openalex.org/W4406210452 (Open access: True)
    
[[https://openalex.org/A5102946169][Maksim Nikitin]], [[https://openalex.org/A5040335780][Sándor B. Ötvös]], [[https://openalex.org/A5055386575][Indrajit Ghosh]], [[https://openalex.org/A5115671617][Maximilian Philipp]], [[https://openalex.org/A5045155782][Ruth M. Gschwind]], [[https://openalex.org/A5063134639][C. Oliver Kappe]], [[https://openalex.org/A5067475475][Burkhard Koenig]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06734 
     
Transition metal-catalyzed cross-coupling reactions are essential in modern organic synthesis, facilitating the rapid creation of complex molecular structures. Traditionally, these reactions rely heavily on conventional bases, with only a few exceptions reported. Recently, we developed adaptive dynamic homogeneous catalysis (AD-HoC), a method that enables C(sp2)–S cross-couplings without needing traditional ligands, bases, or additives. Given the growing demand for protocols compatible with acidic conditions in metal-catalyzed cross-couplings, we revisited AD-HoC to pioneer acid-facilitated transition metal-catalyzed thioetherification. Our method enables the swift synthesis of thioethers using nickel and visible light, with a substoichiometric amount of Brønsted acid acting as an enabler. NMR kinetic studies indicate that in the absence of acid, the system displays an induction period characteristic of autocatalysis. Introducing the acid as a simple additive eliminates this induction period and significantly accelerates the reaction. Moreover, the protocol has been successfully scaled to gram-level synthesis using continuous flow technology, achieving productivities of over 100 g per hour in a commercially available lab-scale photoreactor. This highlights the method's robustness and scalability, making it a powerful tool for large-scale applications.    

    

* Exceptionally Low-Coordinated Bismuth–Oxygen Vacancy Defect Clusters for Generating Black In2O3 Photocatalysts with Superb CO2 Reduction Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406217331
:TOPICS: Advanced Photocatalysis Techniques, Electronic and Structural Properties of Oxides, Copper-based nanomaterials and applications
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03491")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406217331"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406217331"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406217331"))][Get cited by]]

OpenAlex: https://openalex.org/W4406217331 (Open access: False)
    
[[https://openalex.org/A5018208592][Farzin Nekouei]], [[https://openalex.org/A5020585665][Christopher J. Pollock]], [[https://openalex.org/A5100399648][Tianyi Wang]], [[https://openalex.org/A5067645114][Zhong Zheng]], [[https://openalex.org/A5103114439][Yanzhao Zhang]], [[https://openalex.org/A5067924346][Zelio Fusco]], [[https://openalex.org/A5036060356][Huanyu Jin]], [[https://openalex.org/A5049687965][Thrinathreddy Ramireddy]], [[https://openalex.org/A5090264758][Ary Anggara Wibowo]], [[https://openalex.org/A5081363234][Teng Lü]], [[https://openalex.org/A5035776152][Shahram Nekouei]], [[https://openalex.org/A5076537001][Farzaneh Keshtpour]], [[https://openalex.org/A5070722227][Julien Langley]], [[https://openalex.org/A5063221300][Elwy H. Abdelkader]], [[https://openalex.org/A5033536093][Nicholas J. Cox]], [[https://openalex.org/A5074090421][Zongyou Yin]], [[https://openalex.org/A5074340406][Hieu T. Nguyen]], [[https://openalex.org/A5030881231][Alexey M. Glushenkov]], [[https://openalex.org/A5033971536][Siva Krishna Karuturi]], [[https://openalex.org/A5038590827][Zongwen Liu]], [[https://openalex.org/A5100454543][Wei Li]], [[https://openalex.org/A5100348631][Hao Li]], [[https://openalex.org/A5100603066][Yun Liu]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c03491 
     
No abstract    

    

* Electrocatalytic Enantioselective Tandem C–H Indolization toward Biindolyl Atropisomers: Reaction Development and Mechanistic Insight  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406218794
:TOPICS: Axial and Atropisomeric Chirality Synthesis, Alkaloids: synthesis and pharmacology, Catalytic C–H Functionalization Methods
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06594")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406218794"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406218794"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406218794"))][Get cited by]]

OpenAlex: https://openalex.org/W4406218794 (Open access: False)
    
[[https://openalex.org/A5007641634][Zhi‐Huan Peng]], [[https://openalex.org/A5074407812][Ping Huang]], [[https://openalex.org/A5018210433][Ao-Long Li]], [[https://openalex.org/A5109707826][Mingkai Yang]], [[https://openalex.org/A5101696409][Zhikang Li]], [[https://openalex.org/A5100384450][Yuanyuan Li]], [[https://openalex.org/A5100568209][Qin Shi]], [[https://openalex.org/A5090758772][Jiating Cai]], [[https://openalex.org/A5028576201][Shengdong Wang]], [[https://openalex.org/A5035680195][Zhi Zhou]], [[https://openalex.org/A5089356883][Wei Yi]], [[https://openalex.org/A5038199259][Hui Gao]], [[https://openalex.org/A5001623372][Zhongyi Zeng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06594 
     
The electrochemical methods for asymmetric indolization are still elusive and pose a significant challenge. Taking advantage of 2-alkynylanilines as electrochemically compatible indolyl equivalents, we herein represent a mild and highly enantioselective electrocatalytic process for tandem C–H indolization to form 2,3′-biindolyl atropisomers along with hydrogen evolution reaction. Integrated experimental and computational mechanistic studies revealed that a sequential C–H metalation/nucleophilic cyclization/reductive elimination/anodic oxidation sequence involving a RhIII–RhI–RhIII catalytic cycle accounts for the established transformation.    

    

* Controlled Growth of Silver Nanoparticles by Metal–Support Interaction for Enhanced Tandem Catalytic Oxidation of HCHO at Low Temperature  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406219352
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, nanoparticles nucleation surface interactions
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05879")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406219352"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406219352"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406219352"))][Get cited by]]

OpenAlex: https://openalex.org/W4406219352 (Open access: False)
    
[[https://openalex.org/A5026077466][Yue Ding]], [[https://openalex.org/A5056775642][Hui Wang]], [[https://openalex.org/A5032094982][Bin Huang]], [[https://openalex.org/A5101733311][Yuchun Chang]], [[https://openalex.org/A5038411990][Hua Yang]], [[https://openalex.org/A5017052045][Zhenping Qu]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05879 
     
No abstract    

    

* Lowering the Kinetic Barrier via the Synergistic Catalysis of N-CNTs Supported RhP Subnanoclusters and Confined Co Nanoparticles for Olefins Hydroformylation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406219626
:TOPICS: Catalysis and Hydrodesulfurization Studies, Nanomaterials for catalytic reactions, Organometallic Complex Synthesis and Catalysis
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06822")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406219626"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406219626"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406219626"))][Get cited by]]

OpenAlex: https://openalex.org/W4406219626 (Open access: False)
    
[[https://openalex.org/A5109719922][Jiamei Wei]], [[https://openalex.org/A5059142323][Peng Gao]], [[https://openalex.org/A5100377078][Shen Wang]], [[https://openalex.org/A5091735030][Yue Ma]], [[https://openalex.org/A5001966929][Dong Cao]], [[https://openalex.org/A5006520119][Daojian Cheng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06822 
     
No abstract    

    

* Electrocatalytic CO2 Reduction to Methanol on Pt(111) Modified with a Pd Monolayer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406259351
:TOPICS: CO2 Reduction Techniques and Catalysts, Ammonia Synthesis and Nitrogen Reduction, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2025-01-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05442")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406259351"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406259351"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406259351"))][Get cited by]]

OpenAlex: https://openalex.org/W4406259351 (Open access: True)
    
[[https://openalex.org/A5036920326][Aleksandra Wawrzyniak]], [[https://openalex.org/A5028485156][Marc T. M. Koper]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05442 
     
Electrochemical carbon dioxide (CO2) conversion to value-added, highly reduced chemicals such as methanol (CH3OH) is a promising possibility for producing renewable fuel and simultaneous CO2 recycling. However, this process remains a challenge, with only a few selective electrocatalysts known. Here, we present a study of a palladium monolayer on a platinum (111) single crystal (PdML/Pt(111)) as an electrocatalyst for CO2 conversion to CH3OH. A custom-made setup was employed in order to detect and quantify gaseous and liquid CO2 reduction products in sufficient concentrations despite the limitations of working with a single-crystalline electrode. Under ambient reaction conditions, a Faradaic efficiency (FE) of 1.5% at −0.9 V vs reversible hydrogen electrode (RHE) was obtained while using CO2 as the reactant. Other reaction intermediates, carbon monoxide (CO) and formaldehyde (HCHO) were subsequently used as reactants, leading to FEs of 1.8 and 2.5%, respectively, whereas formic acid is not reduced. The corresponding mechanism concluded from our work is compared to the literature. The electrocatalyst introduced here, with a highly well-defined structure for CO2 conversion to CH3OH, opens up possibilities for further catalytic explorations.    

    

* Access to Axially Chiral Biaryl Benzylamines via Ancestral Enzyme-Enabled Reductive Amination Desymmetrization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406275770
:TOPICS: Axial and Atropisomeric Chirality Synthesis, Molecular spectroscopy and chirality, Alkaloids: synthesis and pharmacology
:PUBLICATION_DATE: 2025-01-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06881")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406275770"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406275770"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406275770"))][Get cited by]]

OpenAlex: https://openalex.org/W4406275770 (Open access: False)
    
[[https://openalex.org/A5091809743][W. Jim Zheng]], [[https://openalex.org/A5101960257][Xinxin Zhu]], [[https://openalex.org/A5111379905][Zheng Zhu]], [[https://openalex.org/A5066817609][Teng Yang]], [[https://openalex.org/A5108445153][Lian Zheng]], [[https://openalex.org/A5100638023][Rui Pan]], [[https://openalex.org/A5033002485][Shenlin Wang]], [[https://openalex.org/A5008977627][Lixin Zhang]], [[https://openalex.org/A5100340174][Qi Chen]], [[https://openalex.org/A5102188430][Jian-He Xu]], [[https://openalex.org/A5113822396][Yongtao Xie]], [[https://openalex.org/A5026230284][Gao‐Wei Zheng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06881 
     
Axially chiral biaryl benzylamines are present in numerous natural products, pharmaceuticals, chiral ligands, and catalysts. However, the direct catalytic synthesis of these functional molecules using a robust strategy remains a formidable challenge. Reductive amination desymmetrization of biaryl dialdehydes offers a powerful approach for the construction of axially chiral biaryl benzylamines but suffers from extensive undesirable side reactions. Herein, we engineered ancestral imine reductases to enable reductive amination desymmetrization of biaryl dialdehydes, allowing the construction of a wide range of axially chiral biaryl benzylamines with up to 99% conversion and 99% enantiomeric excess (ee). The ratio of the product to byproducts was up to 97:3 and over 90:10 in most cases. This work presents an alternative strategy for accessing axially chiral biaryl benzylamines and will stimulate the development of associated bioactive molecules and catalysts/ligands.    

    

* Pd-Catalyzed Dehydrogenation Enhanced by Charge Transfer from MoOx Promoter  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406317251
:TOPICS: Catalytic Processes in Materials Science, Electrocatalysts for Energy Conversion, Catalysis and Oxidation Reactions
:PUBLICATION_DATE: 2025-01-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04684")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406317251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406317251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406317251"))][Get cited by]]

OpenAlex: https://openalex.org/W4406317251 (Open access: False)
    
[[https://openalex.org/A5010584378][Byung Gwan Park]], [[https://openalex.org/A5001170097][Jihyeon Lee]], [[https://openalex.org/A5100657005][Yoojin Lee]], [[https://openalex.org/A5028501194][Hyeongeon Lee]], [[https://openalex.org/A5101563699][Jueun Kim]], [[https://openalex.org/A5068765684][Eonu Nam]], [[https://openalex.org/A5101771881][Jong‐Seong Bae]], [[https://openalex.org/A5033014275][Jeong Woo Han]], [[https://openalex.org/A5034804943][Kwangjin An]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c04684 
     
No abstract    

    

* Water-Controlled Coking Dynamics during High-Pressure Methanol-to-Olefins Reaction over SAPO-34  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406321093
:TOPICS: Zeolite Catalysis and Synthesis, Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science
:PUBLICATION_DATE: 2025-01-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06239")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406321093"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406321093"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406321093"))][Get cited by]]

OpenAlex: https://openalex.org/W4406321093 (Open access: False)
    
[[https://openalex.org/A5100767831][Chengwei Zhang]], [[https://openalex.org/A5100910751][Xinqiang Wu]], [[https://openalex.org/A5101614675][Yanan Zhang]], [[https://openalex.org/A5100336102][Li Wang]], [[https://openalex.org/A5057612246][Yan Jin]], [[https://openalex.org/A5014923308][Mingbin Gao]], [[https://openalex.org/A5100682785][Mao Ye]], [[https://openalex.org/A5058202114][Yingxu Wei]], [[https://openalex.org/A5100660725][Zhongmin Liu]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06239 
     
No abstract    

    

* Substrate Promiscuity Engineering of ScALDO Enables a Versatile Minimized Enzyme Cascade for Efficient Utilization of Various Sugars  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406327422
:TOPICS: Enzyme Catalysis and Immobilization, Biofuel production and bioconversion, Microbial Metabolic Engineering and Bioproduction
:PUBLICATION_DATE: 2025-01-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07497")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406327422"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406327422"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406327422"))][Get cited by]]

OpenAlex: https://openalex.org/W4406327422 (Open access: False)
    
[[https://openalex.org/A5086542659][Shiming Tang]], [[https://openalex.org/A5015884379][Z Y Zhang]], [[https://openalex.org/A5069042619][Daocheng Liao]], [[https://openalex.org/A5110074404][Ying Lin]], [[https://openalex.org/A5052443619][Yuan‐Yuan Huang]], [[https://openalex.org/A5073266499][Suiping Zheng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c07497 
     
No abstract    

    

* Evolutionary Specialization of a Promiscuous Designer Enzyme  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406328950
:TOPICS: Enzyme Catalysis and Immobilization, Microbial Metabolic Engineering and Bioproduction, Protein Hydrolysis and Bioactive Peptides
:PUBLICATION_DATE: 2025-01-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06409")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406328950"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406328950"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406328950"))][Get cited by]]

OpenAlex: https://openalex.org/W4406328950 (Open access: True)
    
[[https://openalex.org/A5022469888][Reuben B. Leveson‐Gower]], [[https://openalex.org/A5043880857][Laura Tiessler‐Sala]], [[https://openalex.org/A5005328052][H.J. Rozeboom]], [[https://openalex.org/A5087468780][A.M.W.H. Thunnissen]], [[https://openalex.org/A5076914476][Jean‐Didier Maréchal]], [[https://openalex.org/A5032880385][Gérard Roelfes]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06409  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c06409?ref=article_openPDF][pdf]])
     
The evolution of a promiscuous enzyme for its various activities often results in catalytically specialized variants. This is an important natural mechanism to ensure the proper functioning of natural metabolic networks. It also acts as both a curse and blessing for enzyme engineers, where enzymes that have undergone directed evolution may exhibit exquisite selectivity at the expense of a diminished overall catalytic repertoire. We previously performed two independent directed evolution campaigns on a promiscuous designer enzyme that leverages the unique properties of a noncanonical amino acid (ncAA) para-aminophenylalanine (pAF) as catalytic residue, resulting in two evolved variants which are both catalytically specialized. Here, we combine mutagenesis, crystallography, and computation to reveal the molecular basis of the specialization phenomenon. In one evolved variant, an unexpected change in quaternary structure biases substrate dynamics to promote enantioselective catalysis, while the other demonstrates synergistic cooperation between natural side chains and the pAF residue to form semisynthetic catalytic machinery.    

    
