#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Fri Aug 23 01:12:47 2024

Found 26 results from 2024-08-16 to 2024-08-23
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Stereoselective Fe-Catalyzed Decoupled Cross-Couplings: Chiral Vinyl Oxazolidinones as Effective Radical Lynchpins for Diastereoselective C(sp2)–C(sp3) Bond Formation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401611031
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-08-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04568")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401611031"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401611031"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401611031"))][Get cited by]]

OpenAlex: https://openalex.org/W4401611031 (Open access: True)
    
[[https://openalex.org/A5012541428][Tapas Maity]], [[https://openalex.org/A5046224682][Ángel Rentería‐Gómez]], [[https://openalex.org/A5038942712][Osvaldo Gutiérrez]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04568 
     
No abstract    

    

* Grignard Reagent Addition to Pyridinium Salts: A Catalytic Approach to Chiral 1,4-Dihydropyridines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401613110
:TOPICS: Asymmetric Catalysis, Organometallic Chemistry and Metalation, Chemistry of Pyrrolobenzodiazepines
:PUBLICATION_DATE: 2024-08-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03520")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401613110"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401613110"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401613110"))][Get cited by]]

OpenAlex: https://openalex.org/W4401613110 (Open access: True)
    
[[https://openalex.org/A5028901741][Siriphong Somprasong]], [[https://openalex.org/A5052232106][Marta Castiñeira Reis]], [[https://openalex.org/A5012293576][Syuzanna R. Harutyunyan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03520 
     
No abstract    

    

* Benchtop-Stable Carbyl Iminopyridyl NiII Complexes for Olefin Polymerization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401629582
:TOPICS: Transition Metal Catalysis, Carbon Dioxide Utilization for Chemical Synthesis, Chemistry of Main Group Elements and Compounds
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02708")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401629582"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401629582"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401629582"))][Get cited by]]

OpenAlex: https://openalex.org/W4401629582 (Open access: True)
    
[[https://openalex.org/A5090769339][Hasaan Rauf]], [[https://openalex.org/A5100671448][Yu‐Sheng Liu]], [[https://openalex.org/A5106560081][Muhammad Arslan]], [[https://openalex.org/A5060701151][Surya Pratap S. Solanki]], [[https://openalex.org/A5063346563][Éric Deydier]], [[https://openalex.org/A5073644685][Rinaldo Poli]], [[https://openalex.org/A5029991019][Lars C. Grabow]], [[https://openalex.org/A5007452156][Eva Harth]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02708 
     
No abstract    

    

* P-Block Elements Activate Pt Surfaces for the Electrooxidation of Alcohols and Polyols When Promoting the −OH formation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401633729
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02443")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401633729"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401633729"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401633729"))][Get cited by]]

OpenAlex: https://openalex.org/W4401633729 (Open access: True)
    
[[https://openalex.org/A5101457128][Matheus B. C. de Souza]], [[https://openalex.org/A5074344486][Gabriela Soffiati]], [[https://openalex.org/A5082446014][Victor S. Lemos]], [[https://openalex.org/A5040455786][Victor Y. Yukuhiro]], [[https://openalex.org/A5004496213][Miguel A. San‐Miguel]], [[https://openalex.org/A5101581911][Pablo S. Fernández]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02443 
     
No abstract    

    

* Reconstitution of Myoglobin with Iron Porphycene Generates an Artificial Aldoxime Dehydratase with Expanded Catalytic Activities  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401647230
:TOPICS: Molecular Mechanisms of Heme Biosynthesis and Related Disorders, Biological Methane Utilization and Metabolism, Hemoglobin Function and Regulation in Vertebrates
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03220")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401647230"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401647230"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401647230"))][Get cited by]]

OpenAlex: https://openalex.org/W4401647230 (Open access: True)
    
[[https://openalex.org/A5101618410][Shunsuke Kato]], [[https://openalex.org/A5023480711][Masatoshi Abe]], [[https://openalex.org/A5077386505][Harald Gröger]], [[https://openalex.org/A5021407407][Takashi Hayashi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03220 
     
No abstract    

    

* Hydrogenation of CO2 by a Tripodal Palladium Pincer Complex  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401660020
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-08-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02523")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401660020"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401660020"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401660020"))][Get cited by]]

OpenAlex: https://openalex.org/W4401660020 (Open access: True)
    
[[https://openalex.org/A5022355698][Nandita Biswas]], [[https://openalex.org/A5075409783][Peter Lönnecke]], [[https://openalex.org/A5010301750][E. Kirillov]], [[https://openalex.org/A5078900901][Dmitri Gelman]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02523 
     
No abstract    

    

* Alkene Isomerization Catalyzed by a Mn(I) Bisphosphine Borohydride Complex  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401660026
:TOPICS: Homogeneous Catalysis with Transition Metals, Olefin Metathesis Chemistry, Frustrated Lewis Pairs Chemistry
:PUBLICATION_DATE: 2024-08-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03364")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401660026"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401660026"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401660026"))][Get cited by]]

OpenAlex: https://openalex.org/W4401660026 (Open access: True)
    
[[https://openalex.org/A5031505385][Ines Blaha]], [[https://openalex.org/A5071469908][Stefan Weber]], [[https://openalex.org/A5099525009][Robin Dülger]], [[https://openalex.org/A5046772276][Luı́s F. Veiros]], [[https://openalex.org/A5047476885][Karl Kirchner]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03364 
     
No abstract    

    

* Highly Selective Dual-Atom Pd Heterogeneous Catalyst Prepared by Size-Selected Cluster Beam  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401606577
:TOPICS: Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials, Structural and Functional Study of Noble Metal Nanoclusters
:PUBLICATION_DATE: 2024-08-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02500")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401606577"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401606577"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401606577"))][Get cited by]]

OpenAlex: https://openalex.org/W4401606577 (Open access: False)
    
[[https://openalex.org/A5046863535][Wenka Zhu]], [[https://openalex.org/A5101962097][Wen Wu Xu]], [[https://openalex.org/A5033926331][Xingen Lin]], [[https://openalex.org/A5101659241][S.F. Hu]], [[https://openalex.org/A5102547330][Sichen Tang]], [[https://openalex.org/A5045284604][Syed Adil Shah]], [[https://openalex.org/A5101213568][Zixiang Zhao]], [[https://openalex.org/A5100768241][Yongxin Zhang]], [[https://openalex.org/A5013262767][Siqi Lu]], [[https://openalex.org/A5027629406][X. F. Lu]], [[https://openalex.org/A5101650984][J. G. Wan]], [[https://openalex.org/A5101962097][Wen Wu Xu]], [[https://openalex.org/A5011982705][Huang Zhou]], [[https://openalex.org/A5055199008][Kuo‐Juei Hu]], [[https://openalex.org/A5087862339][Zhongkang Han]], [[https://openalex.org/A5022989538][Yuen Wu]], [[https://openalex.org/A5055941645][Fengqi Song]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02500 
     
Atomic dispersed heterogeneous catalysts have emerged as a prominent research focus in catalysis due to their exceptional atom utilization, robust activity, and remarkable selectivity. However, the design and synthesis of catalysts with a precisely defined atomic number and exceptional dispersion still pose significant challenges. In this study, we employed a magnetron sputtering cluster source equipped with a mass selector to selectively fabricate single-atom, dual-atom, and clusters with precise atomic numbers catalysts supported on mesoporous graphitic carbon nitride (mpg-C3N4). This method provides a universally applicable approach for synthesizing highly pure diatomic catalysts. Furthermore, the dual-atom Pd catalyst exhibits an outstanding turnover frequency of 5819 h–1 in the hydrogenation of nitrobenzene, surpassing that of both single-atom Pd and Pd2057 clusters. Density functional theory calculations reveal that excellent hydrogenation performance benefits from the easier dissociation of H–H bonds at the atomic geminal Pd2 sites in the hydrogenation process of nitrobenzene compared to that of single-atom Pd and Pd clusters. This work presents a universal synthetic strategy for precisely constructing multimetal atomic centers, showcasing the advantages of geminal metal sites in catalyzing multimolecule-involved reactions.    

    

* Rhodium-Catalyzed Asymmetric Hydroselenation of 1-Alkynylindoles for Atroposelective Synthesis of Vinyl Selenoethers  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401608966
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Chiroptical Spectroscopy in Organic Compound Analysis, Aromaticity in Organic Molecules and Materials
:PUBLICATION_DATE: 2024-08-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03710")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401608966"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401608966"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401608966"))][Get cited by]]

OpenAlex: https://openalex.org/W4401608966 (Open access: False)
    
[[https://openalex.org/A5013313471][Yu-Long Kang]], [[https://openalex.org/A5100752623][Fen Wang]], [[https://openalex.org/A5061667297][Xingwei Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03710 
     
Catalytic asymmetric hydrofunctionalization of π-bonds has been extensively studied, but the asymmetric hydrofunctionalization of alkynes that affords atropoisometric products remains heavily underexplored. We herein report [Rh(COD)OAc]2/Mg(NTf2)2-catayzed highly atroposelective hydroselenation of two classes of 1-alkynylindoles using selenophenols, where the Mg(II) salt both activates the Rh catalyst and provides a key NTf2 anion essential for the catalytic activity and enantioselectivity, affording C–N axially chiral trisubstituted olefins that bear a relatively low racemization barrier (ΔG‡ ∼ 27 kcal/mol). The catalytic system features high activity, mild reaction conditions, good functional group tolerance, and high regio-, (E)-, and enantioselectivity. The selenoether moiety in the product framework can be readily functionalized to give synthetically useful products.    

    

* Two-Electron or Four-Electron Nanocatalysis for Aerobic Glucose Oxidation: A Mechanism-Driven Prediction Model  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401611661
:TOPICS: Nanomaterials with Enzyme-Like Characteristics, Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-08-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03226")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401611661"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401611661"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401611661"))][Get cited by]]

OpenAlex: https://openalex.org/W4401611661 (Open access: False)
    
[[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5088455541][Qiao-Zhi Li]], [[https://openalex.org/A5080159973][Jia‐Jia Zheng]], [[https://openalex.org/A5057337824][Xingfa Gao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03226 
     
The nanomaterial-catalyzed oxidation of glucose can produce H2O2 or H2O as the oxygen reduction products. However, the theoretical model predicting the selection between H2O2 and H2O products is still lacking, which limits the rational design of aerobic glucose oxidation nanocatalysts for H2O2-targeted applications in disease diagnoses and therapies. In this work, a mechanism-driven prediction model that can predict whether a nanocatalyst preferably undergoes the 2e-catalysis to produce H2O2 or the 4e-catalysis to produce H2O is developed. The development of the model is first based on the reaction thermodynamics, and then a correction constant is introduced in conjunction with experimental reports to compensate to some extent for the lack of consideration of other influencing factors such as the reaction kinetics. The predictive power of the model is verified by density functional theory investigations on the mechanisms and kinetics of the experimentally reported noble metal nanocatalysts. Using the model, binary alloy nanomaterials, which preferably undergo 2e-catalysis to produce H2O2, have been predicted. This work provides theoretical guidelines for the rational design of aerobic glucose oxidation nanocatalysts capable of producing H2O2 and facilitates their application in H2O2-targeted biomedicine.    

    

* Acid–Base Bifunctional Catalysis of the Lewis Acidic Isolated Co(OH)2 and Basic N Anion Generated from CeO2 and 2-Cyanopyridine  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401613654
:TOPICS: Catalytic Reduction of Nitro Compounds, Chemistry and Applications of Metal-Organic Frameworks, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-08-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02378")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401613654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401613654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401613654"))][Get cited by]]

OpenAlex: https://openalex.org/W4401613654 (Open access: False)
    
[[https://openalex.org/A5074282622][Masazumi Tamura]], [[https://openalex.org/A5009823089][Masanobu Haga]], [[https://openalex.org/A5005601022][Anchalee Junkaew]], [[https://openalex.org/A5087295336][Daiki Asada]], [[https://openalex.org/A5023402348][Riko Ichikawa]], [[https://openalex.org/A5008012900][Ryo Toyoshima]], [[https://openalex.org/A5106262571][Akira Nakayama]], [[https://openalex.org/A5041562042][Hiroshi Kondoh]], [[https://openalex.org/A5053881651][Yoshinao Nakagawa]], [[https://openalex.org/A5053906254][Keiichi Tomishige]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02378 
     
Acid–base bifunctional catalysts, which have both acid and base sites that are arranged at an appropriate distance, are one of the effective catalyst categories and have been extensively studied as a simple and effective method for designing heterogeneous and homogeneous catalysts in both the laboratories and industry. Recently, we found that a heterogeneous–homogeneous hybrid strong base site of N– was constructed only by mixing 2-cyanopyridine and CeO2 in the solution, where the N– site was formed by the covalent bonding between the lattice O atom of CeO2 and the C atom of the CN group in 2-cyanopyridine. Herein, an effective acid–base bifunctional catalyst with proximal sites of the heterogeneous–homogeneous hybrid base site and metal species-derived Lewis acid site is presented. The introduction of Co species into CeO2 forms isolated Co(OH)2 on CeO2, and further introduction of 2-cyanopyridine generates the heterogeneous–homogeneous hybrid base site of N– near the Co(OH)2 without the interference of these sites. The acid–base bifunctional sites work cooperatively to provide about 10-fold higher activity to the hydromethoxylation of acrylonitrile than the heterogeneous–homogeneous hybrid base site alone. Catalyst characterizations such as XRD, TEM, UV–vis, NO adsorption, XPS, Raman, XAS, NH3-TPD and in situ XPS, DFT calculations, and kinetic studies show that acrylonitrile and methanol are activated by the Lewis acidic Co(OH)2 and the hybrid base site, respectively, and the cooperative work results in the large rate enhancement.    

    

* Confinement Effect and Application in Catalytic Oxidation–Reduction Reaction of Confined Single-Atom Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401614499
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-08-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02113")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401614499"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401614499"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401614499"))][Get cited by]]

OpenAlex: https://openalex.org/W4401614499 (Open access: False)
    
[[https://openalex.org/A5103508715][X.‐B. Fan]], [[https://openalex.org/A5100607527][Donghao Li]], [[https://openalex.org/A5079426674][Yuanxiang Shu]], [[https://openalex.org/A5103113889][Yimeng Feng]], [[https://openalex.org/A5100611624][Fengxiang Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02113 
     
Single-atom catalysts (SACs) exhibit remarkable 100% atomic economy, making them highly efficient in various fields, including production processes, energy systems, and environmental remediation. However, the migration and agglomeration of single atoms significantly diminish reactivity and increase the operating cost of the catalyst. Due to the size effect, the space confinement effect, and the electron confinement effect, the single atoms are stabilized, and overall catalytic performance is also improved. The confinement effect can be enhanced by modifying the supporting materials with ordered and regular pore structures and improving the binding mode between the support and the single atom. In this Review, the confined functional structure will be explained for the synthesis of confined SACs. It elucidates mechanisms for the formation of the confinement effect and elaborates how the confinement effect improves catalytic performance. This Review is helpful for better understanding, controlling, and utilizing the confinement effect to design confined SACs with impressive catalytic performance.    

    

* Synergistic Cooperation of Dual-Phase Redox Catalysts in Chemical Looping Oxidative Coupling of Methane  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401628374
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Chemical-Looping Technologies
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03001")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401628374"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401628374"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401628374"))][Get cited by]]

OpenAlex: https://openalex.org/W4401628374 (Open access: False)
    
[[https://openalex.org/A5087288709][Leo Brody]], [[https://openalex.org/A5036437960][Bar Mosevitzky Lis]], [[https://openalex.org/A5072485858][Abigail Pérez Ortiz]], [[https://openalex.org/A5066686606][Mohammadreza Kosari]], [[https://openalex.org/A5037267949][Kyle Vogt‐Lowell]], [[https://openalex.org/A5064788542][Sam Portillo]], [[https://openalex.org/A5021619062][Reinhard Schomäcker]], [[https://openalex.org/A5066491588][Israel E. Wachs]], [[https://openalex.org/A5081461600][Fanxing Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03001 
     
Chemical looping oxidative coupling of methane (CL-OCM) presents a promising route for light olefin production, offering a simpler alternative to conventional methane steam reforming approaches. The selection of the redox catalyst used in CL-OCM is critical since it must achieve high C2+ yields (>25%) while maintaining longevity in harsh reaction environments. We present a comprehensive performance evaluation and characterization of an understudied, yet highly effective redox catalyst capable of achieving and maintaining a C2+ yield of 26.8% at 840 °C. Through extensive ex situ and in situ analyses, including X-ray diffraction, near-ambient pressure X-ray photoelectron spectroscopy (NAP-XPS), and Raman spectroscopy, we have characterized the catalyst and identified two distinct bulk, crystalline phases: cubic LixMg6–xMnO8 and orthorhombic Mg3–xMnx(BO3)O2. Calcination at 1200 °C, as opposed to a typical calcination temperature of 900 °C, increased the orthoborate oxide phase to ∼45 wt % while reducing the BET surface area by 65%. By investigating performance differences between these catalysts in their "sintered" and "presintered" states, we have unveiled surprising cooperative effects between the two phases. Experiments with physical mixing of these two phases (granular stacking and mortar mixing) revealed that observed differences in CL-OCM efficacy cannot be solely due to sintering-induced loss of surface area but are also the result of synergistic, dual-phase interactions that enhance overall C2+ yield. H2-temperature programmed reduction measurements and ex situ XPS analysis demonstrate that the sintered catalyst has a lower average Mn-oxidation state, enabling more selective lattice oxygen release and limiting overoxidation to COx species. Additionally, NAP-XPS and in situ Raman characterization suggest that boron–oxygen coordinated sites (BOx) may also play a role in improving selectivity. Leveraging insights from our phase mixture CL-OCM performance tests, steady-state experiments with cofed O2, and corroborative in situ characterizations, we propose that the synergistic interplay between LixMg6–xMnO8 and Mg3–xMnx(BO3)O2 may be the result of facile oxygen release from the more redox-active LixMg6–xMnO8 phase combined with Li+ migration to the orthoborate oxide phase.    

    

* Unraveling the Effect of Dopants in Zirconia-Based Catalysts for CO2 Hydrogenation to Methanol  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401631981
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03206")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401631981"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401631981"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401631981"))][Get cited by]]

OpenAlex: https://openalex.org/W4401631981 (Open access: False)
    
[[https://openalex.org/A5022902169][Raffaele Cheula]], [[https://openalex.org/A5086377289][Tuan Anh Tran]], [[https://openalex.org/A5060065812][Mie Andersen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03206 
     
The doping of zirconia to enhance its activity and selectivity for the hydrogenation of CO2 to methanol has been studied intensively in experiments, but a thorough theoretical understanding of the factors that decide whether a dopant has a positive or negative influence on the reactivity is lacking. In this work, we conduct a mechanistic investigation using density functional theory and microkinetic modeling, considering the ZrO2(101) surface doped with 16 different metals. This analysis elucidates the following two criteria for enhanced reactivity. One, the ability of the surface to facilitate the dissociation of H2 and provide the H* species necessary for the catalytic reaction is deemed a necessary but not sufficient criterion. Two, dopants that are thermodynamically stable under reaction conditions in a 2+ or 3+ oxidation state are beneficial, since this entails the introduction of O vacancies, which stabilize O-containing reaction intermediates such as formate and lower key transition states. We construct linear scaling relations that can reliably predict transition state energies in terms of less computationally costly adsorption energies. It is revealed that dopants that are stable in the 4+ state (e.g., Ti), and thereby lack O vacancies, follow a different scaling relation with a higher intercept for formate formation, which can explain their reduced reactivity. Overall, our microkinetic models can successfully predict the trends for dopants that have been found active in experiments (Zn2+, Cd2+, Ga3+, In3+) and not. Together with the established reactivity criteria, this paves the way for computational screening of oxides for the important CO2-to-methanol process.    

    

* Intermolecular Anti-Markovnikov Hydroamination of Alkenes with Sulfonamides, Sulfamides, and Sulfamates  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401635760
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03960")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401635760"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401635760"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401635760"))][Get cited by]]

OpenAlex: https://openalex.org/W4401635760 (Open access: False)
    
[[https://openalex.org/A5103280654][A. T. Lin]], [[https://openalex.org/A5106561684][Mathis J. Karrasch]], [[https://openalex.org/A5055184008][Qiaolin Yan]], [[https://openalex.org/A5060242168][Jacob M. Ganley]], [[https://openalex.org/A5082512160][Benjamin G. Hejna]], [[https://openalex.org/A5034006875][Robert R. Knowles]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03960 
     
A general method for the light-driven intermolecular anti-Markovnikov hydroamination of alkenes with primary sulfonamides, sulfamides, and sulfamates is presented. The reaction is mediated by a ternary catalyst system composed of an iridium(III) chromophore, a fluorinated alkoxide base, and a thiol H-atom donor. We hypothesize that the reactions proceed via a proton-coupled electron transfer (PCET) mechanism wherein implementation of the alkoxide base imparts additional thermochemical driving force for the homolytic activation of strong N–H bonds that were previously inaccessible using this methodology. This furnishes electrophilic N-centered radicals that subsequently interface with a wide range of unactivated alkenes for C–N bond formation. This protocol exhibits a broad substrate scope and great functional group tolerance, further highlighting the advantages of excited-state PCET as a platform for catalytic radical generation from common organic functional groups.    

    

* Highly Dispersed Cu Atoms Induce Alternating Surface Microstrain in PtCu Concave Octahedral Nanoparticles Accelerating Oxygen Reduction Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401643081
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02973")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401643081"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401643081"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401643081"))][Get cited by]]

OpenAlex: https://openalex.org/W4401643081 (Open access: False)
    
[[https://openalex.org/A5042007663][Xiashuang Luo]], [[https://openalex.org/A5081523003][Cehuang Fu]], [[https://openalex.org/A5053450604][Shuiyun Shen]], [[https://openalex.org/A5050144802][Xiaohui Yan]], [[https://openalex.org/A5048609660][Junliang Zhang]], [[https://openalex.org/A5048609660][Junliang Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02973 
     
A comprehensive understanding of the intricate surface environments of practical nanocatalysts at the atomic level is essential for advancing our knowledge of catalytic mechanisms. In this study, we investigate PtCu octahedral nanoparticles with varying microstrains engineered by Cu dispersion. A detailed analysis of the atom configuration and corresponding microstrain is conducted. The intimate mixing of Cu and Pt results in increased randomness in atom displacement within the lattice and a more pronounced distribution of alternating microstrain on the surfaces. Specifically, we observe that the PtCu concave octahedral nanoparticles with alternating microstrain demonstrate a substantial oxygen reduction reaction (ORR) activity of 3.95 mA cm–2 in area-specific activity. The significant impact of shear microstrain is further underscored, as evidenced by an 86.9% decrease in the ORR activity upon the removal of the alternating shear microstrain. This study sheds light on the effects of microstrain toward the ORR and provides valuable insights into designing advanced Pt-based electrocatalysts.    

    

* Structural and Chemical Origin of Dual-Atom Sites for Enhanced Oxygen Electroreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401647130
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-08-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03068")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401647130"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401647130"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401647130"))][Get cited by]]

OpenAlex: https://openalex.org/W4401647130 (Open access: False)
    
[[https://openalex.org/A5026670698][Xiannong Tang]], [[https://openalex.org/A5100683497][Yuqin Zhang]], [[https://openalex.org/A5071613190][Shaobin Tang]], [[https://openalex.org/A5046398623][Dirk Lützenkirchen‐Hecht]], [[https://openalex.org/A5037878083][Kai Yuan]], [[https://openalex.org/A5079785501][Yiwang Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03068 
     
Dual-atom catalysts have garnered widespread attention for the oxygen reduction reaction (ORR), yet achieving an in-depth comprehension of the reaction mechanism and the structure–activity relationship remains challenging. Herein, carbon nanosheets with FeCo–N6 active sites (FeCo-NCNS) are prepared via a straightforward self-sacrificing template and cascade anchoring strategy. Delicate structural control enables hierarchical porosity, providing adequate active site density (2.5 × 1019 sites g–1) and fast mass transfer, as revealed by in situ scanning electrochemical microscopy. Moreover, the structural and chemical origin of the dual-atom site for enhanced ORR activity is uncovered. FeCo–N6 can be spontaneously transformed to an oxygen-bridging structure (FeCo–N6–O) in the KOH electrolyte, triggering improved charge polarization, downshifted d-band center, and optimized adsorption behavior for oxygen-intermediates, thereby reducing the free energy barrier. Therefore, the FeCo-NCNS exhibits enhanced ORR activity regarding the half-wave potential (0.90 V), mass specific kinetic current density (9.54 A g–1), turnover frequency (2.35 e– site–1 s–1), and improved stability. This work not only provides an effective methodology to construct efficient electrocatalysts for energy conversation but also highlights the dynamic structural evolution and charge polarization in improving the electrocatalytic activity of dual-atom sites.    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401650251
:TOPICS: 
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i016_1834783")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401650251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401650251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401650251"))][Get cited by]]

OpenAlex: https://openalex.org/W4401650251 (Open access: True)
    
, ACS Catalysis. 14(16)] 2024. https://doi.org/10.1021/csv014i016_1834783  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i016_1834783][pdf]])
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401652163
:TOPICS: 
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i016_1834784")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401652163"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401652163"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401652163"))][Get cited by]]

OpenAlex: https://openalex.org/W4401652163 (Open access: True)
    
, ACS Catalysis. 14(16)] 2024. https://doi.org/10.1021/csv014i016_1834784  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i016_1834784][pdf]])
     
No abstract    

    

* Bidirectional Electron Transfer Strategies for Anti-Markovnikov Olefin Aminofunctionalization via Arylamine Radicals  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401658377
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-08-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04110")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401658377"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401658377"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401658377"))][Get cited by]]

OpenAlex: https://openalex.org/W4401658377 (Open access: True)
    
[[https://openalex.org/A5003070688][Pritam Roychowdhury]], [[https://openalex.org/A5036869372][Samya Samanta]], [[https://openalex.org/A5049208087][Lauren R. Brown]], [[https://openalex.org/A5092597708][Saim Waheed]], [[https://openalex.org/A5083255496][David C. Powers]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04110  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c04110][pdf]])
     
Arylamines are common structural motifs in pharmaceuticals, natural products, and materials precursors. While olefin aminofunctionalization chemistry can provide entry to arylamines, classical polar reactions typically afford Markovnikov products. Nitrogen-centered radical intermediates provide the opportunity to access anti-Markovnikov selectivity; however, anti-Markovnikov arylamination is unknown in large part due to the lack of arylamine radical precursors. Here, we introduce bidirectional electron transfer processes to generate arylamine radical intermediates from N-pyridinium arylamines: Single-electron oxidation provides arylamine radicals that engage in anti-Markovnikov olefin aminopyridylation; single-electron reduction unveils arylamine radicals that engage in anti-Markovnikov olefin aminofunctionalization. The development of bidirectional redox processes complements classical design principles for radical precursors, which typically function via a single redox manifold. Demonstration of both oxidative and reductive mechanisms to generate arylamine radicals from a common N-aminopyridinium precursor provides complementary methods to rapidly construct and diversify arylamine scaffolds from readily available radical precursors.    

    

* Uncovering the Parallel Biosynthetic Pathways of the Cyclohexanone and Phenol Rings in Cycloheximide and Actiphenol by Tailoring Redox Enzymes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401658412
:TOPICS: Natural Products as Sources of New Drugs, Nucleotide Metabolism and Enzyme Regulation, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-08-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03332")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401658412"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401658412"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401658412"))][Get cited by]]

OpenAlex: https://openalex.org/W4401658412 (Open access: False)
    
[[https://openalex.org/A5053837836][Jun Tang]], [[https://openalex.org/A5018548208][Xiaowei Guo]], [[https://openalex.org/A5101764185][Jing Yang]], [[https://openalex.org/A5101807810][Yongjiang Wang]], [[https://openalex.org/A5101244435][Jianying Luo]], [[https://openalex.org/A5067846870][Min Yin]], [[https://openalex.org/A5080595301][Yijun Yan]], [[https://openalex.org/A5049451705][Sheng‐Xiong Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03332 
     
The eukaryotic translation inhibitor cycloheximide (CHX) and its analogue actiphenol (APN) feature a glutarimide moiety and a six-membered carbocyclic ring system. The biosynthesis of CHX and APN is not yet fully understood, particularly with respect to the mechanism of formation of the fully reduced cyclohexanone ring in CHX and the aromatic phenol ring in APN. In this work, a combination of gene inactivation, chemical synthesis, and in vitro biochemical experiments highlighted an ensemble of three tailoring redox enzymes as being responsible for the biosynthesis of the six-membered carbocyclic ring systems. Specifically, two redox enzymes (ChxJ and ChxI) alone can generate an active intermediate that undergoes a cascade of non-enzymatic transformations to create APN, while a reductive enzyme (ChxG) acts as a gatekeeper, directing the same intermediate down a different pathway toward CHX. Finally, the full nature of each biosynthetic pathway was established in detail, including the formation mechanisms of six-membered carbocyclic rings.    

    

* Copper-Catalyzed Site-Selective C(sp2)–H Alkynylation of Allenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401691251
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Gold Catalysis in Organic Synthesis, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-08-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03688")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401691251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401691251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401691251"))][Get cited by]]

OpenAlex: https://openalex.org/W4401691251 (Open access: False)
    
[[https://openalex.org/A5101361114][Duan Xiu]], [[https://openalex.org/A5072681321][Qihao Jin]], [[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5061976148][Yifan Sun]], [[https://openalex.org/A5020749993][Youhao Wei]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5044234477][Jiang‐Kai Qiu]], [[https://openalex.org/A5100612547][Kai Guo]], [[https://openalex.org/A5061720627][Xiaoguang Bao]], [[https://openalex.org/A5041846457][Xinxin Wu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03688 
     
No abstract    

    

* Controllable Multihalogenation of a Non-native Substrate by the SyrB2 Iron Halogenase  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401694293
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Nanoscale Zero-Valent Iron Applications and Remediation, Molecular Mechanisms of Heme Biosynthesis and Related Disorders
:PUBLICATION_DATE: 2024-08-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02816")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401694293"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401694293"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401694293"))][Get cited by]]

OpenAlex: https://openalex.org/W4401694293 (Open access: False)
    
[[https://openalex.org/A5038324099][R. Hunter Wilson]], [[https://openalex.org/A5072396493][Sourav Chatterjee]], [[https://openalex.org/A5017881340][Elizabeth R. Smithwick]], [[https://openalex.org/A5042015280][Anoop R. Damodaran]], [[https://openalex.org/A5048655684][Ambika Bhagi‐Damodaran]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02816 
     
No abstract    

    

* Photocatalytic Oxyalkynylation of Unactivated Alkenes Enabled by Hypervalent Iodine(III) Reagents  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401697138
:TOPICS: Catalytic Oxidation of Alcohols, Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-08-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02977")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401697138"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401697138"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401697138"))][Get cited by]]

OpenAlex: https://openalex.org/W4401697138 (Open access: False)
    
[[https://openalex.org/A5067909390][Hanzhang Qin]], [[https://openalex.org/A5101793858][Zhengyi Liu]], [[https://openalex.org/A5100351201][Yixin Zhang]], [[https://openalex.org/A5046806152][Yiyun Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02977 
     
No abstract    

    

* Enantioselective N-Heterocyclic Carbene-Catalyzed Hauser-Kraus Annulations for the Construction of C–N Axially Chiral Phthalimde Derivatives  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401701297
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, N-Heterocyclic Carbenes in Catalysis and Materials Chemistry, Olefin Metathesis Chemistry
:PUBLICATION_DATE: 2024-08-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03263")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401701297"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401701297"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401701297"))][Get cited by]]

OpenAlex: https://openalex.org/W4401701297 (Open access: False)
    
[[https://openalex.org/A5090102834][Panlong Ren]], [[https://openalex.org/A5100365847][Qing Zhao]], [[https://openalex.org/A5100440745][Kang Xu]], [[https://openalex.org/A5049108106][Tingshun Zhu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03263 
     
No abstract    

    

* Anion-Doping-Mediated Metal–Support Interactions in CeO2-Supported Pd Catalysts for CO2 Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401707800
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-08-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02874")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401707800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401707800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401707800"))][Get cited by]]

OpenAlex: https://openalex.org/W4401707800 (Open access: False)
    
[[https://openalex.org/A5059456132][Luyang Qiao]], [[https://openalex.org/A5073916217][Xi-guang Wang]], [[https://openalex.org/A5008824073][Shanshan Zong]], [[https://openalex.org/A5040025789][Zhi Gao Huang]], [[https://openalex.org/A5048710212][Zhangfeng Zhou]], [[https://openalex.org/A5079808010][Maohong Fan]], [[https://openalex.org/A5006305984][Yuan‐Gen Yao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02874 
     
No abstract    

    
