#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sun Sep  1 01:26:56 2024

Found 1 results from 2024-08-25 to 2024-09-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Nitrogen-Rich Carbon Dots as Effective Catalysts in the 1,4-Reduction of α,β-Unsaturated Aldehydes via Ion Pair Asymmetric Nano-Organocatalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401844482
:TOPICS: Aromaticity in Organic Molecules and Materials, Engineering of Surface Nanostructures, Synthesis and Applications of Carbon Quantum Dots
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03532")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401844482"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401844482"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401844482"))][Get cited by]]

OpenAlex: https://openalex.org/W4401844482 (Open access: False)
    
[[https://openalex.org/A5092689902][Alessio Carioscia]], [[https://openalex.org/A5084092290][Emanuele Cocco]], [[https://openalex.org/A5077619653][Maria Edith Casacchia]], [[https://openalex.org/A5032908255][Giuseppe Gentile]], [[https://openalex.org/A5030617180][Martina Mamone]], [[https://openalex.org/A5075714745][Giuliana Giorgianni]], [[https://openalex.org/A5106702204][Elena Incerto]], [[https://openalex.org/A5074191348][Maurizio Prato]], [[https://openalex.org/A5011629137][Fabio Pesciaioli]], [[https://openalex.org/A5080131431][Giacomo Filippini]], [[https://openalex.org/A5051354092][Armando Carlone]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03532 
     
The development of nanostructured organocatalysts is emerging as a prominent field in materials science. To this purpose, nitrogen-doped carbon dots (CDs) have been effectively employed in enantioselective enamine organocatalysis. On the other hand, enantioselective iminium ion nano-organocatalysis is much less explored. In this Letter, the use of CDs in asymmetric iminium ion catalysis via asymmetric counteranion-directed catalysis (ACDC) is disclosed. Nonchiral CDs bearing butylenediamine residues proved to be the most effective ones, in combination with (S)-TRIP as a chiral phosphoric acid (CPA). A correlation between the features of the CDs' surfaces and their catalytic performance was shown, and the catalytic activity of the employed CDs proved to be higher than that of simple molecular amines. An extensive reaction optimization allowed the reduction of different α,β-unsatured aldehydes in good yield and ee, using a low catalyst loading.    

    
