#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Mon Jan 29 11:38:19 2024

Found 25 results from 2024-01-15 to 2024-01-29
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

** Insights into the Palladium(II)-Catalyzed Wacker-Type Oxidation of Styrene with Hydrogen Peroxide and tert-Butyl Hydroperoxide   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05630")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390901486"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390901486"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390901486"))][Get cited by]]

OpenAlex: https://openalex.org/W4390901486 (Open access: True)
    
[[https://openalex.org/A5072010770][Manting Mu]], [[https://openalex.org/A5061421429][Katherine L. Walker]], [[https://openalex.org/A5035955276][Goar Sánchez‐Sanz]], [[https://openalex.org/A5009737401][Robert M. Waymouth]], [[https://openalex.org/A5022698705][Cristina Trujillo]], [[https://openalex.org/A5048314462][Mark J. Muldoon]], [[https://openalex.org/A5049133522][Max García‐Melchor]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05630  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05630][pdf]])
     
Wacker oxidations are ubiquitous in the direct synthesis of carbonyl compounds from alkenes. While the reaction mechanism has been widely studied under aerobic conditions, much less is known about such processes promoted with peroxides. Here, we report an exhaustive mechanistic investigation of the Wacker oxidation of styrene using hydrogen peroxide (H2O2) and tert-butyl hydroperoxide (TBHP) as oxidants by combining density functional theory and microkinetic modeling. Our results with H2O2 uncover a previously unreported reaction pathway that involves an intermolecular proton transfer assisted by the counterion [OTf]− present in the reaction media. Furthermore, we show that when TBHP is used as an oxidant instead of H2O2, the reaction mechanism switches to an intramolecular protonation sourced by the HOtBu moiety generated in situ. Importantly, these two mechanisms are predicted to outcompete the 1,2-hydride shift pathway previously proposed in the literature and account for the level of D incorporation in the product observed in labeling experiments with α-d-styrene and D2O2. We envision that these insights will pave the way for the rational design of more efficient catalysts for the industrial production of chemical feedstocks and fine chemicals.    

    

** Palladium-Catalyzed Aminations in Flow ... on Water   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05257")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390907051"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390907051"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390907051"))][Get cited by]]

OpenAlex: https://openalex.org/W4390907051 (Open access: False)
    
[[https://openalex.org/A5046408989][Madison J Wong]], [[https://openalex.org/A5071091326][Erfan Oftadeh]], [[https://openalex.org/A5054669574][John Saunders]], [[https://openalex.org/A5037636630][Alex B. Wood]], [[https://openalex.org/A5089736452][Bruce H. Lipshutz]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05257 
     
Aminations can be efficiently run, under plug flow conditions on water, catalyzed by low levels of a recyclable palladium precatalyst. General protocols to couple amines, both aryl and aliphatic, with aryl/heteroaryl bromides have been developed. Further highlights include “on water” conditions, short reaction times, recycling of the reaction medium, low levels of residual Pd in the isolated products, and low E factors as a green metric, all of these features showcasing this alternative to amination reactions typically run in batch mode.    

    

** Influence of Reaction Parameters on Nanogold-Catalyzed Glucose and Xylose Oxidation: A Joint Experimental and DFT Study   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04929")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390907077"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390907077"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390907077"))][Get cited by]]

OpenAlex: https://openalex.org/W4390907077 (Open access: False)
    
[[https://openalex.org/A5025557747][Jay Pee Oña]], [[https://openalex.org/A5047700117][Laura Laverdure]], [[https://openalex.org/A5075270869][Rose-Marie Latonen]], [[https://openalex.org/A5025539571][Narendra Kumar]], [[https://openalex.org/A5091192374][Markus Peurla]], [[https://openalex.org/A5046977601][Ilari Angervo]], [[https://openalex.org/A5022884606][Karoliina Honkala]], [[https://openalex.org/A5052786782][Henrik Grénman]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04929 
     
The electrocatalytic oxidation (ECO) of glucose on gold requires alkaline conditions and relatively high potentials (>0.3 VRHE). Although the adsorption of hydroxide ions (OHads) is also known to occur under these conditions, the generally accepted proton-coupled electron transfer mechanism for sugar ECO does not explicitly state the role of OHads in the sugar adsorption or oxidation steps. To investigate this, we carried out a combined experimental and density functional theory (DFT) study on the ECO of glucose and xylose over a nanogold catalyst under temperature and pH control. Grand canonical DFT (GC-DFT) was used to identify the preferred reaction mechanism in which OHads facilitates the thermodynamically feasible formation of gluconic and xylonic acid. Calculated results also showed that OHads plays a role in improving the acid selectivity. Constant-potential electrolyses in sugar solutions were performed using mesoporous (Sibunit) carbon-supported Au nanoparticles (AuNPs) with an average cluster size of 4.7 nm. Experimental results showed that the highest conversions for glucose (57.7%) and xylose (49.4%) were obtained at 25 °C and pH 12.5, with gluconic and xylonic acid selectivity of 81.5 and 87.8%, respectively. The catalytic activities were high considering the low Au loading (∼0.1% wt). Higher pH led to a decrease in the ECO rate possibly due to excess hydroxide ions blocking active sites for sugar adsorption. Our results highlight the importance of computational studies in elucidating reaction mechanisms for sugar ECO where sugar acids are the main oxidation products. This is crucial in designing reaction systems for the viable production of these value-added chemicals from biomass.    

    

** Ligands Defect-Induced Structural Self-Reconstruction of Fe–Ni–Co-Hydroxyl Oxides with Crystalline/Amorphous Heterophase from a 2D Metal–Organic Framework for an Efficient Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05314")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390907090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390907090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390907090"))][Get cited by]]

OpenAlex: https://openalex.org/W4390907090 (Open access: False)
    
[[https://openalex.org/A5091300678][Hongqi Chu]], [[https://openalex.org/A5044789787][Rujin Li]], [[https://openalex.org/A5000139851][Panpan Feng]], [[https://openalex.org/A5086890929][Dongyan Wang]], [[https://openalex.org/A5046884970][Chunxiang Li]], [[https://openalex.org/A5028136131][Yanling Yu]], [[https://openalex.org/A5048237780][Min Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05314 
     
The two-dimensional (2D) Fe–Ni–Co-MOF is synthesized using a simple double ligand strategy at room temperature. The surface reconstruction process transforms it into a crystalline–amorphous heterojunction composed of polycrystalline metal (oxy)hydroxide (MOOH) and amorphous metal oxides/hydroxides with terephthalic acid (TPA) by coordination covalent bonding. In situ Raman spectroscopy discloses the dynamic structure conversion. Density functional theory (DFT), Fourier transform infrared spectroscopy (FTIR), and solid-state nuclear magnetic resonance (SSNMR) reveal the induction of the ligand defects on surface reconstruction and the enhancing effect of TPA on the oxygen evolution reaction (OER) performance through a covalent interaction. The amorphous–crystalline heterojunction of Fe–Ni–CoOOH-TPA has numerous structural defects and high electrical conductivity, resulting in an efficient and stable OER performance with overpotentials of 236 mV at 10 mA cm–2. It has also been observed that the catalyst processes self-healing in an idle state, arising from the reversible conversion of MOOH to M(OH)2. This work reveals the structural and compositional transformation of the 2D Fe–Ni–Co-MOF during surface reconstruction, elucidating the relationship between electrocatalytic reconstruction and water-splitting performance of metal–organic framework (MOF)-based catalysts. It has been proven that appropriate covalent interactions enhance the OER of electrocatalysts.    

    

** Regio- and Diastereoselective Highly Strained Alkylidenecyclobutane Isomerization/Hydroacylation: Synthesis of Multisubstituted Cyclobutanes with Consecutive Stereocenters   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05616")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390909403"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390909403"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390909403"))][Get cited by]]

OpenAlex: https://openalex.org/W4390909403 (Open access: False)
    
[[https://openalex.org/A5020320041][Kai-Qiang Tian]], [[https://openalex.org/A5035342344][Shi-Jiao Zhang]], [[https://openalex.org/A5025562702][Jing‐Tai Zhao]], [[https://openalex.org/A5079009312][Guiyun Duan]], [[https://openalex.org/A5012302576][Qiaoling Wang]], [[https://openalex.org/A5034683730][Guihua Cui]], [[https://openalex.org/A5064016159][R.T. Guo]], [[https://openalex.org/A5021398635][Hong-Shuang Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05616 
     
The regio- and diastereoselective alkene isomerization and hydrofunctionalization sequence enabled by transition-metal complexes allows rapid activation and assembly of the C(sp3)–H bond that is either adjacent or distal to the initial double bond, which has been a longstanding challenge in this field. Herein, we develop unusual rhodium-catalyzed isomerization of alkylidenecyclobutanes with subsequent hydroacylation reaction to provide multisubstituted cyclobutanes with continuous stereocenters. Note that this tandem process features a good regio- and diastereoselectivity profile. Isotopic labeling experiments support the “exo to endo” migration of the double bond to a coordinated cyclobutene that is responsible for the deuterium incorporation observed in the cyclobutane product.    

    

** Evolution of Methanol Molecules within Pyridine-Modified Mordenite Unveiled by Solid-State NMR Spectroscopy   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04494")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390909571"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390909571"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390909571"))][Get cited by]]

OpenAlex: https://openalex.org/W4390909571 (Open access: False)
    
[[https://openalex.org/A5025489995][Yuting Sun]], [[https://openalex.org/A5036873735][Pan Gao]], [[https://openalex.org/A5054267512][Yi Ji]], [[https://openalex.org/A5017178424][Kuizhi Chen]], [[https://openalex.org/A5005414489][Guangjin Hou]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04494 
     
Pyridine modified Mordenite (Py-MOR) has been successfully applied in multiple methanol-related catalytic reactions, e.g., carbonylation and methanol-to-hydrocarbon conversions, etc.; however, the fundamental insights into the methanol molecules within its interconnected micropores remain elusive. Herein, we comprehensively studied the adsorption and evolution of methanol on Py-MOR under thermal treatment by employing solid-state NMR spectroscopy. An interesting evolution route of methanol (8-MR) → dimethyl ether → methanol (12-MR) is observed when increasing the reaction temperature up to 573 K, while no carbon–carbon bond can be formed in the 8-MR and 12-MR channels, possibly due to the confinement effect on methanol either from the narrow 8-MR pores or pyridine partially occupied 12-MR channels. More importantly, the vigorous competitive adsorption on the Bro̷nsted acid site for methanol versus pyridine is experimentally verified by 1H MAS NMR and two-dimensional hetero- and homonuclear correlation NMR spectra. The pyridine-H+ bond of the pyridinium ions in the 8-MR side pockets easily breaks upon methanol adsorption, even at room temperature, while the strongly bonded pyridine-H+ moiety in the 12-MR channel breaks only at elevated temperatures up to 523–573 K, due to the competitive adsorption of methanol. We further show that the CO carbonylation reaction occurs for methanol residing in 8-MR pores of Py-MOR, while the methanol within the 12-MR is “locked” by the pyridine molecules. These fundamental findings are critical for a more comprehensive understanding of the methanol-related reactions on Py-MOR.    

    

** Poisoning of Pt/γ-Al2O3 Aqueous Phase Reforming Catalysts by Ketone and Diketone-Derived Surface Species   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04774")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390910531"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390910531"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390910531"))][Get cited by]]

OpenAlex: https://openalex.org/W4390910531 (Open access: True)
    
[[https://openalex.org/A5029376991][Bryan J. Hare]], [[https://openalex.org/A5057662539][Ricardo A. García Cárcamo]], [[https://openalex.org/A5049941485][Luke L. Daemen]], [[https://openalex.org/A5033156106][Yongqiang Cheng]], [[https://openalex.org/A5085121177][Rachel B. Getman]], [[https://openalex.org/A5088976109][Carsten Sievers]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04774  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c04774][pdf]])
     
Strong adsorption of ketone and diketone byproducts and their fragmentation products during the aqueous phase reforming of biomass derived oxygenates is believed to be responsible for the deactivation of supported Pt catalysts. This study involves a combined experimental and theoretical approach to demonstrate the interactions of several model di/ketone poisons with Pt/γ-Al2O3 catalysts. Particular di/ketones were selected to reveal the effects of hydroxyl groups (acetone, hydroxyacetone), conjugation with C═C bonds (mesityl oxide), intramolecular distance between carbonyls in diketones (2,3-butanedione, 2,4-pentanedione), and length of terminal alkyl chains (3,4-hexanedione). The formation of adsorbed carbon monoxide (1900–2100 cm–1) as a decarbonylation product was probed using infrared spectroscopy and to calculate the extent of poisoning during subsequent methanol dehydrogenation based on the reduction of the ν(C≡O) band integral relative to experiments in which only methanol was dosed. Small Pt particles appeared less active in decarbonylation and were perhaps poisoned by strongly adsorbed di/ketones on undercoordinated metal sites and bulky conjugated species formed on the γ-Al2O3 support from aldol self-condensation. Larger Pt particles were more resistant to di/ketone poisoning due to higher decarbonylation activity yet still fell short of the expected yield of adsorbed CO from subsequent methanol activity. Vibrational spectra acquired using inelastic neutron scattering showed evidence for strongly binding methyl and acyl groups resulting from di/ketone decarbonylation on a Pt sponge at 250 °C. Adsorption energies and molecular configurations were obtained for di/ketones on a Pt(111) slab using density functional theory, revealing potential descriptors for predicting decarbonylation activity on highly coordinated metal sites. Calculated reaction energies suggest it is energetically favorable to reform surface methyl groups into adsorbed CO and H. However, the rate of this surface reaction is limited by a high activation barrier indicating that either improved APR catalyst designs or regeneration procedures may be necessary.    

    

** Iron-Catalyzed Regioselective Reductive Fluoroalkylalkenylation of Unactivated Alkenes   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05690")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390929188"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390929188"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390929188"))][Get cited by]]

OpenAlex: https://openalex.org/W4390929188 (Open access: False)
    
[[https://openalex.org/A5025904134][Siyu Wang]], [[https://openalex.org/A5024997511][Baochuan Guo]], [[https://openalex.org/A5001546485][Tong Mu]], [[https://openalex.org/A5041637427][Zhengli Liu]], [[https://openalex.org/A5069888386][Yun He]], [[https://openalex.org/A5058629788][Xiao‐Song Xue]], [[https://openalex.org/A5044657310][Zhihai Feng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05690 
     
The example of iron-catalyzed reductive fluoroalkylalkenylation of unactivated alkenes has been disclosed, affording the stereodefined homoallylic fluoroalkanes with high efficiency and regioselectivity. This three-component cross-electrophile coupling features directing groups free, good functional group tolerance, broad substrate scope, and late-stage difunctionalization of biorelevant molecules. Moreover, this protocol sheds light on the distinct reactivity disparities between fluoroalkyl and nonfluoroalkyl radicals in three-component reductive cross-coupling reactions, highlighting the unique nature of iron/B2pin2 systems.    

    

** Two Distinct Gold-Catalyzed Oxidative Annulations of 1,5-Allenynes with Nitrones to Yield 1-Naphthol Derivatives Bearing 2,3- versus 3,4-Fused Nitroxy Rings   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05620")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390932792"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390932792"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390932792"))][Get cited by]]

OpenAlex: https://openalex.org/W4390932792 (Open access: False)
    
[[https://openalex.org/A5061612567][Debashis Barik]], [[https://openalex.org/A5012654271][Chandrima Maitra]], [[https://openalex.org/A5046755560][Chi-Tien Hsieh]], [[https://openalex.org/A5035653592][Mu‐Jeng Cheng]], [[https://openalex.org/A5070651625][Rai‐Shung Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05620 
     
No abstract    

    

** Indole Synthesis by Cobalt-Catalyzed Intramolecular Amidation via the Oxidatively Induced Reductive Elimination Pathway   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05706")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390938469"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390938469"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390938469"))][Get cited by]]

OpenAlex: https://openalex.org/W4390938469 (Open access: False)
    
[[https://openalex.org/A5065151951][Aleksandrs Cizikovs]], [[https://openalex.org/A5069503005][Emils E. Basens]], [[https://openalex.org/A5010660890][Paula A. Zagorska]], [[https://openalex.org/A5018720752][Artis Kinēns]], [[https://openalex.org/A5005968710][Liene Grigorjeva]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05706 
     
C–H bond activation and functionalization using high-valent cobalt catalysis typically involves a Co(III)/Co(I) catalytic cycle. Because of the lack of evidence and challenges associated with the high reactivity and instability of Co(IV) intermediates, reports on the C–H functionalization mechanism investigation involving Co(IV) intermediacy are still underexplored. Herein, we report an efficient synthesis of indole-2-carboxylic esters via intramolecular amidation of α-amidoacrylates and experimental and computational studies of the reaction mechanism, which involves oxidatively induced reductive elimination from Co(IV) species.    

    

** Understanding the Hydrothermal Stability of Potential NH3-SCR Catalyst Cu-KFI Zeolite   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05155")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390938490"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390938490"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390938490"))][Get cited by]]

OpenAlex: https://openalex.org/W4390938490 (Open access: False)
    
[[https://openalex.org/A5007773511][Zhongqi Liu]], [[https://openalex.org/A5062580577][Yu Fu]], [[https://openalex.org/A5035913873][Yulong Shan]], [[https://openalex.org/A5043858864][Tongliang Zhang]], [[https://openalex.org/A5026641797][Yingjie Wang]], [[https://openalex.org/A5069770947][Junjie Du]], [[https://openalex.org/A5035823162][Yangyang Sun]], [[https://openalex.org/A5046772439][Guo‐Zhong He]], [[https://openalex.org/A5042633367][Hong He]], [[https://openalex.org/A5066289187][Yunbo Yu]], [[https://openalex.org/A5042633367][Hong He]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05155 
     
Al-rich Cu-KFI was found to withstand hydrothermal aging (HTA) at 800 °C, while Cu-CHA with a similar Si/Al ratio was deactivated since a much higher energy barrier was required to transform Cu2+ ions to CuOx during HTA in KFI. Specifically, the rate-determining step is the hydrolysis of Cu2+ in KFI but the cross-cage migration of Cu(OH)2 in CHA. Therefore, the inclusion of two Cu2+ ions in one repeat unit of KFI does not significantly promote CuOx production. However, the accumulated CuOx cannot be completely avoided under such severe hydrothermal aging. It may originate from Cu2+ in the same cage or adjacent cages. This shorter diffusion effectively mitigated the structural integrity deterioration of KFI in comparison to CHA. Nevertheless, HTA reduced the number as well as the reactivity of residual Cu2+ ions in Cu-KFI zeolite catalysts. Quantitative results determined that the activity and stability of the catalyst were maximized when the average lta cage contained about 1.4 Cu2+ ions.    

    

** Controlling Bond Scission Pathways of Isopropanol on Fe- and Pt-Modified Mo2N Model Surfaces and Powder Catalysts   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04700")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390939862"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390939862"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390939862"))][Get cited by]]

OpenAlex: https://openalex.org/W4390939862 (Open access: False)
    
[[https://openalex.org/A5060526552][William N. Porter]], [[https://openalex.org/A5012436789][Hilda Mera]], [[https://openalex.org/A5050541240][Wenjie Liao]], [[https://openalex.org/A5005584952][Zhexi Lin]], [[https://openalex.org/A5064944001][Ping Liu]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5034358731][Jingguang G. Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04700 
     
Biomass valorization can be used to produce value-added chemicals and fuels from renewable biomass resources by upgrading them via selective bond scission while retaining certain functional groups. Specifically, upgrading biomass through the dehydrogenation of alcohols to carbonyl compounds has gained interest as a method of utilizing biomass-derived alcohols while additionally producing H2. In this work, isopropanol was used as a probe molecule to control bond scission selectivity over Fe- and Pt-modified molybdenum nitride (Mo2N) model surfaces and powder catalysts. Trends in the selectivity toward dehydration and dehydrogenation were dependent on both the type and coverage of the metal overlayer on model surfaces. These results were then extended to the corresponding powder catalysts to demonstrate how model surface studies can inform the design of supported catalysts. Density functional theory calculations provided insights into controlling the dehydration and dehydrogenation pathways. This work shows that a fundamental understanding of the reactivity and intermediates on Mo2N-based model surfaces can be applied to understand the catalytic performance of metal-modified Mo2N powder catalysts, and also demonstrates that Mo2N-based catalysts are potentially promising materials for upgrading biomass-derived oxygenates.    

    

** Impact of Point Defects, External Surfaces Sites, and Si/Al Ratio on Al–O Bonds Hydrolysis Kinetics at the Initiation of Faujasite Dealumination   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05517")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390940164"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390940164"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390940164"))][Get cited by]]

OpenAlex: https://openalex.org/W4390940164 (Open access: False)
    
[[https://openalex.org/A5079354447][Thomas Jarrin]], [[https://openalex.org/A5027199996][Theodorus de Bruin]], [[https://openalex.org/A5014892353][Céline Chizallet]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05517 
     
Faujasite is one of the most industrially employed zeolite material, mainly for catalytic applications. Its properties are dependent on its pore network, which can be tuned by dealumination upon steaming. Previous theoretical studies on the subject based on the density functional theory identified plausible dealumination mechanisms for simple bulk structures of faujasite, but to gain a more complete understanding of dealumination, and to be able to compare to experimental situations, theoretical studies must be performed on more realistic and complex systems. In this article, we identify the intermediates and transition states for the first Al–O bond hydrolysis initiating dealumination in the bulk of faujasite for various Si/Al ratios, in the presence of silanol nests defects, and at the external surface of faujasite. We find that Al–O bond breaking is made easier from a kinetic perspective on some sites of the external surface of the material, considering the water adsorbed state as the reference. Moreover, the presence of defects and a decrease of the Si/Al ratio also lower the free energy barriers necessary to dealuminate. These trends are less clear when considering apparent free energy barrier, when the water desorbed state has been taken as a reference. Subtle local effects enter into play explaining the barrier rankings, including a participation of the hydrogen bond network strengthening at the outermost surface of the zeolite, which significantly stabilizes the highest free energy transition state in some cases. These hydrogen bonds make Brønsted–Evans–Polanyi relationships blurrier at the surface than at the bulk sites, suggesting that local effects on the stabilization of the transition states need to be explicitly considered.    

    

** Understanding the Synergistic Catalysis in Hydrogenation of Carbonyl Groups on Cu-Based Catalysts   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04740")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390944700"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390944700"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390944700"))][Get cited by]]

OpenAlex: https://openalex.org/W4390944700 (Open access: False)
    
[[https://openalex.org/A5062189559][Qing‐Nan Wang]], [[https://openalex.org/A5083764797][Ruizhi Duan]], [[https://openalex.org/A5006084923][Zhendong Feng]], [[https://openalex.org/A5042973046][Ying Zhang]], [[https://openalex.org/A5074562260][Peng Luan]], [[https://openalex.org/A5000732757][Zhaochi Feng]], [[https://openalex.org/A5091246787][Jijie Wang]], [[https://openalex.org/A5011065863][Can Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04740 
     
Understanding the synergy of Cu0 and Cu+ in hydrogenation reactions is indispensable for reasonably modulating the product distributions and improving the catalyst design. Herein, we investigated the hydrogenation of dimethyl oxalate on CeZrOx-supported Cu with varying molar ratios of nCu+/nCu0. A volcano-type correlation of structure and activity indicates that the selectivity of ethylene glycol is strongly dependent on the nCu+/nCu0 ratio, arising from the matching of rates for the activation of carbonyl group-included reactants and H2 on Cu+ and Cu0, respectively. The maximal selectivity toward ethylene glycol is achieved at a ratio of 0.15; deviating from this value leads to the favorable formation of methyl glycolate, a primary product. Results obtained from temperature-programmed surface reactions indicate that the presence of Cu+ and oxygen vacancies (OV) reduces the reaction temperature for the hydrogenation of carbonyl groups. Theoretical data show that the OV located at the copper–ceria interface induces a downward-directed adsorption configuration of the reaction intermediate adsorbed at the Cu+ site, compared to the presence of an upward-directed counterpart at the Cu0–Cu+ center. This change leads to a reduction in the kinetic barrier for the subsequent hydrogenation step, which consumes active *H species transferred from adjacent Cu0 via a hydrogen spillover process. Manipulating the Cu valence state and oxygen vacancies via interfacial engineering offers a viable strategy for governing product distributions, serving as an inspiration for the design of selective hydrogenation catalysts.    

    

** Unusual Facet-Dependent Sintering in Pd–TiO2 Catalysts Revealed by Theory and Experiment   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05367")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390946598"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390946598"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390946598"))][Get cited by]]

OpenAlex: https://openalex.org/W4390946598 (Open access: False)
    
[[https://openalex.org/A5037882381][Songda Li]], [[https://openalex.org/A5030461176][Yidong Xia]], [[https://openalex.org/A5088898962][Yang Ou]], [[https://openalex.org/A5064963854][Zhen Wu]], [[https://openalex.org/A5059078547][Jun‐Jie Zhu]], [[https://openalex.org/A5021559449][Liang Wang]], [[https://openalex.org/A5008716820][Xiangju Meng]], [[https://openalex.org/A5087862339][Zhongkang Han]], [[https://openalex.org/A5002935799][Wentao Yuan]], [[https://openalex.org/A5005771611][Ying Jiang]], [[https://openalex.org/A5022301289][David J. Wales]], [[https://openalex.org/A5068576964][Hangsheng Yang]], [[https://openalex.org/A5007502406][Yong Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05367 
     
Engineering of support facet and metal valence states is recognized as an effective strategy for manipulating the sintering and dispersion of metal nanoparticles (NPs). Here, we report an unusual valence state-independent but facet-dependent effect of sintering/dispersion behaviors of Pd NPs on anatase TiO2 surfaces, which is confirmed by density functional theory (DFT) calculation and in situ environmental scanning transmission electron microscopy (ESTEM). All the Pd species, including Pd atoms and Pd2+ ions, sintered on the TiO2 (100) surface through both the particle migration coalescence (PMC) and Ostwald ripening (OR), while dispersed into single atoms/ions rapidly on the TiO2 anatase (001) surface. Further dynamical simulations revealed the specific interactions between Pd, surface lattice O, and the surface oxygen vacancies in the supports, responsible for the mobility of Pd NPs and diffusion barriers for Pd adatoms/ions. Our results contrast with the conventional understanding of relationships between the valence state of noble metal and the intrinsic facet-dependent effects and suggest an avenue for the rational design of targeted catalysts under different reaction conditions.    

    

** Single Ru–P Site Catalyst Coupling N Sites in a Flexible Polymeric Framework for Efficient CO2 Hydrogenation to Formate   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05214")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390949748"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390949748"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390949748"))][Get cited by]]

OpenAlex: https://openalex.org/W4390949748 (Open access: False)
    
[[https://openalex.org/A5002969943][Guangjun Ji]], [[https://openalex.org/A5066965669][Cunyao Li]], [[https://openalex.org/A5040573133][Benhan Fan]], [[https://openalex.org/A5011057377][Guoqing Wang]], [[https://openalex.org/A5055207901][Zhao Sun]], [[https://openalex.org/A5007944987][Miao Jiang]], [[https://openalex.org/A5044819827][Lei Ma]], [[https://openalex.org/A5006816805][Yan Li]], [[https://openalex.org/A5064371893][Yunjie Ding]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05214 
     
Hydrogenation of CO2, an abundant C1 resource, into formate, is one of the most charming utilization routes of CO2. Herein, a series of single Ru–P site catalysts coupling N sites (denoted as Ru/P&N-POPs) were designed and applied in the highly effective hydrogenation of CO2 to formate. The Ru (II) ions were firmly anchored and finely regulated by P sites in the polymeric skeleton, while the original N species surrounding single Ru–P active sites enriched and activated CO2. Besides, 13C{1H} R-type RF irradiation and two-dimensional separated local field (2D R-SLF) experiments proved the good flexibility of P&N-POPs frameworks, which were beneficial for optimizing the orientation of functional sites and the synergy of abundant Ru–P active species and N species. As a result, a ca. 2000 h–1 TOF of CO2 and at least 5 recycles were achieved in the formate synthesis under 393 K and 6.0 MPa (CO2/H2 = 1:1). Multiple characterization methods including mass nuclear magnetic resonance, extended X-ray absorption fine structure, scanning transmission electron microscopy, in situ Fourier transform infrared, etc. were employed to reveal the mechanism for the catalytic performance of Ru/P&N-POPs.    

    

** Coupling Cross-Dimensional Ru1–Run Sites in Confined Nanoislands to Overcome the Limitation of Coadsorption and Diffusion in Tandem Reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05112")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390954297"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390954297"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390954297"))][Get cited by]]

OpenAlex: https://openalex.org/W4390954297 (Open access: False)
    
[[https://openalex.org/A5057113152][Huilu Wu]], [[https://openalex.org/A5046225712][Qian Wang]], [[https://openalex.org/A5018543280][Yang Zhao]], [[https://openalex.org/A5089589779][Zhexi Gao]], [[https://openalex.org/A5042324395][Yanjun Lin]], [[https://openalex.org/A5047244598][Lirong Zheng]], [[https://openalex.org/A5066904777][Dianqing Li]], [[https://openalex.org/A5031411023][Junting Feng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05112 
     
Integrating different reaction sites offers prospects to address the difficulties in single-atom catalysis and helps overcome the limitation of scaling relations for coadsorption. Here, we coupled different dimensional Ru1 and Run active sites on confined Co nanoislands for the reductive amination of 5-hydroxymethylfurfural (5-HMF) to 5-aminomethyl-2-furanyl alcohol (AMF), constrained by the disequilibrium in the adsorption of NH3/H2. Ru clusters trigger an ensemble effect by multipoint-bonding with NH3 and thus become more conductive to dissociate NH3 to NH2* than Ru1 both thermodynamically and kinetically, which releases Ru1 for activating H2 to enhance local H* coverage. Furthermore, intimate active sites in confined spaces enable the timely diffusion of NH2*/H* to react with imine intermediates adsorbed on nanoislands in the di-σC,N configuration. With confined cross-dimensional sites overcoming the limitations of competitive adsorption and diffusion, Ru1+n@Co/MMO exhibits a record-high AMF production rate (295 g·gRu–1 h–1) without the requirement of high NH3/H2 feeding, and it exhibits a mass specific activity even higher than that of single-atom Ru1@Co/MMO.    

    

** Kinetic Modeling of Erythritol Deoxydehydration and Consecutive Hydrogenation over the ReOx-Pd/CeO2 Catalyst   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04785")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390954643"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390954643"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390954643"))][Get cited by]]

OpenAlex: https://openalex.org/W4390954643 (Open access: False)
    
[[https://openalex.org/A5087102640][Ji Cao]], [[https://openalex.org/A5005271476][Savitri Larasati]], [[https://openalex.org/A5001517975][Mizuho Yabushita]], [[https://openalex.org/A5053881651][Yoshinao Nakagawa]], [[https://openalex.org/A5027222471][Johan Wärnå]], [[https://openalex.org/A5013993469][Dmitry Yu. Murzin]], [[https://openalex.org/A5087295336][Daiki Asada]], [[https://openalex.org/A5076818771][Akira Nakayama]], [[https://openalex.org/A5053906254][Keiichi Tomishige]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04785 
     
The reaction kinetics of deoxydehydration + hydrogenation (DODH + HG; didehydroxylation) of erythritol to butanediols and n-butane over the ReOx-Pd/CeO2 catalyst was investigated. Competitive adsorption of polyols and catalyst deactivation during the DODH + HG reaction were necessary to be considered in the kinetics. The order of the adsorption strength on the catalyst surface was erythritol >1,2-butanediol > water >1,4-butanediol and monoalcohols. The deactivation during the reaction was investigated with two models: time-dependent and conversion-dependent ones. The conversion-dependent model better fitted both the activities of reused catalysts and the time-course data. The deactivated catalysts were characterized with TG-DTA and Raman spectroscopy. The weight loss and the temperature for the combustion of deposited organic species in TG-DTA did not correlate with the deactivation degree. On the other hand, a growing signal at around 910 cm–1 was observed in Raman spectroscopy in line with deactivation, which can be explained by the formation of aggregated ReOx species. The low activity of aggregated ReOx species was supported by DFT calculations showing that the activation energy of dimeric Re2OxHy/CeO2 catalyst species for the cleavage of two C–O bonds is higher than that of monomeric ReOxHy/CeO2 species.    

    

** Decoupling Active Sites Enables Low-Temperature Semihydrogenation of Acetylene   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05508")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390960141"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390960141"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390960141"))][Get cited by]]

OpenAlex: https://openalex.org/W4390960141 (Open access: False)
    
[[https://openalex.org/A5033870660][Zhengwen Li]], [[https://openalex.org/A5001541516][Jiajun Zhang]], [[https://openalex.org/A5072434234][Jiaming Tian]], [[https://openalex.org/A5033303258][Kai Feng]], [[https://openalex.org/A5061140388][Yuxin Chen]], [[https://openalex.org/A5035339773][Xiao Li]], [[https://openalex.org/A5025884387][Zhihe Zhang]], [[https://openalex.org/A5043570145][Shuairen Qian]], [[https://openalex.org/A5000053135][Bin Yang]], [[https://openalex.org/A5015415276][Dong Su]], [[https://openalex.org/A5069636973][Kai H. Luo]], [[https://openalex.org/A5047133857][Binhang Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05508 
     
No abstract    

    

** Structurally Well-Defined PC(sp3)P Osmium Pincer Catalysts for Methylation of Alcohols, Indoles, Phenols, and Sulfonamides Using Methanol as a C1 Source   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390961649"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390961649"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390961649"))][Get cited by]]

OpenAlex: https://openalex.org/W4390961649 (Open access: True)
    
[[https://openalex.org/A5022355698][Nandita Biswas]], [[https://openalex.org/A5078900901][Dmitri Gelman]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05062  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05062][pdf]])
     
No abstract    

    

** Iron(I) and Iron(II) Amido-imidazolin-2-imine Complexes as Catalysts for H/D Exchange in Hydrosilanes   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05355")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390966679"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390966679"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390966679"))][Get cited by]]

OpenAlex: https://openalex.org/W4390966679 (Open access: True)
    
[[https://openalex.org/A5015680661][Noor U Din Reshi]], [[https://openalex.org/A5047299792][Dirk Bockfeld]], [[https://openalex.org/A5032109714][Dirk Baabe]], [[https://openalex.org/A5047389618][Lars Denker]], [[https://openalex.org/A5042008991][José Luis García Martínez]], [[https://openalex.org/A5065184964][Bartosz Trzaskowski]], [[https://openalex.org/A5056138136][René Frank]], [[https://openalex.org/A5036558577][Matthias Tamm]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05355  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05355][pdf]])
     
The unsymmetrical amino-imidazolin-2-imine ligand [HAmIm, 1,2-(DippNH)–C6H4–N=C(NiPrCMe)2] is employed in the synthesis of the iron(I) arene complex [(AmIm)Fe(η6-C6H6)] and the iron(II) neosilyl complex [(AmIm)Fe(CH2SiMe3)]. These compounds are highly efficient precatalysts in H/D exchange reactions with deuterium (D2) in hydrosilanes. The scope comprises primary to tertiary silanes at a catalyst loading of 1 mol % at ambient temperature. In-depth mechanistic studies including various control experiments and the syntheses of isolated iron-hydride and iron-silyl compounds are performed. These studies reveal that the activation of both Fe(I) and Fe(II) complexes generates Fe–H/D species as key catalytic intermediates. An alternative catalytic pathway involving an iron-silyl intermediate, although shown to be less feasible by DFT calculations, may also be operative.    

    

** Platinum–Nickel Alloy Nanowire Electrocatalysts Transform into Pt-Skin Beads-on-Nanowires Keeping Oxygen Reduction Reaction Activity During Potential Cycling   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04709")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390966737"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390966737"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390966737"))][Get cited by]]

OpenAlex: https://openalex.org/W4390966737 (Open access: False)
    
[[https://openalex.org/A5056385527][Yu Zhou]], [[https://openalex.org/A5075163783][Yoshimi Iguchi]], [[https://openalex.org/A5084674713][Tianchi Li]], [[https://openalex.org/A5029441798][Masaru Kato]], [[https://openalex.org/A5066119313][Yasir Arafat Hutapea]], [[https://openalex.org/A5004724008][Akari Hayashi]], [[https://openalex.org/A5053994773][Takeshi Watanabe]], [[https://openalex.org/A5013277240][Ichizo Yagi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04709 
     
We synthesized PtNi alloy nanowires (PtNi NWs) at three different temperatures of 433, 494, and 533 K (NW433 K, NW494 K, and NW533 K, respectively) and then investigated their catalytic activity and durability for the oxygen reduction reaction (ORR) in acidic media. Ni contents in the PtNi NWs increase as the synthesis temperatures increase from below 5 at. % for NW433 K up to about 15 at. % for NW493 K and NW553 K. PtNi nanoparticles (PtNi NPs), which are the unconsumed intermediate during the NW growth, also coexist for NW433 K and NW494 K but not for NW533 K. NW494 K and NW533 K show similar initial activity for the ORR but higher than NW433 K, suggesting that higher Ni contents are critical to achieving higher initial ORR activity. Accelerated durability tests (ADTs) show that NW493 K is the most durable, suggesting that the copresence of PtNi NPs is critical to durability. Only NW493 K, with a high Ni content of 15 at. % and coexisting PtNi NPs, gave better results in both cases. Scanning transmission electron microscopy and energy dispersive X-ray spectroscopy of PtNi NWs reveal a structural transformation of NW493 K into Pt-skin beads-on-nanowires, involving the Ostwald ripening of coexisting PtNi NPs. This structural transformation is coupled with changes in surface composition and surface electronic structure, as confirmed by the CO stripping voltammogram and in situ X-ray absorption spectroscopy, resulting in high durability and suppression of Pt and Ni dissolution. Understanding such structural transformation during potential cycling will help us to design and develop highly active and durable Pt-based electrocatalysts.    

    

** Asymmetric Cascade Cyclization of Enynamides with Photogenerated Ketenes via Relay Gold and N-Oxide Catalysis   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05731")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390974006"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390974006"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390974006"))][Get cited by]]

OpenAlex: https://openalex.org/W4390974006 (Open access: False)
    
[[https://openalex.org/A5006012404][Dan Liŭ]], [[https://openalex.org/A5003415923][Zhen‐Cao Shu]], [[https://openalex.org/A5018409196][Zhihan Zhang]], [[https://openalex.org/A5087045090][Ze-Tian Wang]], [[https://openalex.org/A5060310187][Liang Wang]], [[https://openalex.org/A5081137661][Ming‐Sheng Xie]], [[https://openalex.org/A5089663065][Hai‐Ming Guo]], [[https://openalex.org/A5029146832][Liang‐Qiu Lu]], [[https://openalex.org/A5044960680][Wen‐Jing Xiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05731 
     
An asymmetric cascade cyclization of enynamides and α-diazoketones to produce chiral bicyclic lactams bearing chiral all-carbon quaternary stereocenters is realized with up to 95% yield, 98% ee, and >19:1 dr. The combination of visible light photoactivation and the relay of gold and N-oxide catalysis in a cascade process enabled the facile generation and controlled assembly of two reactive intermediates, ketene and aza-o-quinone methide. Theoretical calculations revealed a stepwise [4 + 2] cycloaddition mechanism, with the stereochemistry controlled by the amide group of the catalyst. Remarkably, this study presents the first example of chiral N-oxides serving as catalysts for asymmetric ketene cycloaddition and illustrates how a cascade strategy could be a promising means to access significant chiral heterocyclic scaffolds.    

    

** Vanadium-Containing Chloroperoxidase-Catalyzed Versatile Valorization of Phenols and Phenolic Acids   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05333")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390974179"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390974179"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390974179"))][Get cited by]]

OpenAlex: https://openalex.org/W4390974179 (Open access: False)
    
[[https://openalex.org/A5011068248][Huanhuan Li]], [[https://openalex.org/A5008785904][Pei-Gao Duan]], [[https://openalex.org/A5085129889][Yue Huang]], [[https://openalex.org/A5060836006][Chengsen Cui]], [[https://openalex.org/A5039285985][Frank Hollmann]], [[https://openalex.org/A5035240739][Yunjian Ma]], [[https://openalex.org/A5070629226][Yonghua Wang]], [[https://openalex.org/A5073501391][Jie Zhang]], [[https://openalex.org/A5010058813][Weidong Liu]], [[https://openalex.org/A5054052897][Wuyuan Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05333 
     
The downstream product transformation of lignin depolymerization is of great interest in the production of high-value aromatic chemicals. However, this transformation is often impeded by chemical oxidation under harsh reaction conditions. In this study, we demonstrate that hypohalites generated in situ by the vanadium-containing chloroperoxidase from Curvularia inaequalis (CiVCPO) can halogenate various electron-rich and electron-poor phenol and phenolic acid substrates. Specifically, CiVCPO enabled decarboxylative halogenation, deformylative halogenation, halogenation, and direct oxidation reactions. The versatile transformation routes for the valorization of phenolic compounds showed up to 99% conversion and 99% selectivity, with a turnover number of 60,700 and a turnover frequency of 60 s–1 for CiVCPO. This study potentially expands the biocatalytic toolbox for lignin valorization.    

    

** Single Pd Atom–In2O3 Catalyzes Production of CH3CH2OH from Atom-Economic C–C Coupling of HCHO and CH4   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05163")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390974718"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390974718"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390974718"))][Get cited by]]

OpenAlex: https://openalex.org/W4390974718 (Open access: False)
    
[[https://openalex.org/A5046089711][Yuntao Zhao]], [[https://openalex.org/A5093736625][Natalie Fontillas]], [[https://openalex.org/A5054863233][Hua Wang]], [[https://openalex.org/A5036620975][Xinli Zhu]], [[https://openalex.org/A5051658453][Donghai Mei]], [[https://openalex.org/A5011150326][Qingfeng Ge]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05163 
     
Using methane as a reagent to synthesize high-value chemicals and high-energy density fuels through C–C coupling has attracted intense attention in recent decades, as it avoids completely breaking all C–H bonds in CH4. In the present study, we demonstrated that the coupling of HCHO with the CH3 species from CH4 activation to produce ethanol can be accomplished on the single Pd atom–In2O3 catalyst based on the results of density functional theory (DFT) calculations. The results show that the supported single Pd atom stabilizes the CH3 species following the activation of one C–H bond of CH4, while HCHO adsorbs on the neighboring In site. Facile C–C coupling of HCHO with the methyl species is achieved with an activation barrier of 0.56 eV. We further examined the C–C coupling on other single metal atoms, including Ni, Rh, Pt, and Ag, supported on In2O3 by following a similar pathway and found that a balance of the three key steps for ethanol formation, i.e., CH4 activation, C–C coupling, and ethoxy hydrogenation, was achieved on Pd/In2O3. Taking the production of acetaldehyde and ethylene on the Pd/In2O3 catalyst into consideration, the DFT-based microkinetic analysis indicates that ethanol is the dominant product on the Pd/In2O3 catalyst. The facile C–C coupling between HCHO and dissociated CH4 makes formaldehyde a potential C1 source in the conversion and utilization of methane through an energy- and atom-efficient process.    

    
