#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Mon Apr  1 00:50:21 2024

Found 3 results from 2024-03-25 to 2024-04-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Switchable Synthesis of Ethylene/Acrylate Copolymers by a Dinickel Catalyst: Evidence for Chain Growth on Both Nickel Centers and Concepts of Cation Exchange Polymerization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393157067
:TOPICS: Transition Metal Catalysis, Carbon Dioxide Utilization for Chemical Synthesis, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00156")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393157067"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393157067"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393157067"))][Get cited by]]

OpenAlex: https://openalex.org/W4393157067 (Open access: True)
    
[[https://openalex.org/A5026299588][Shuoyan Xiong]], [[https://openalex.org/A5086755096][Heather A. Spinney]], [[https://openalex.org/A5064960434][Brad C. Bailey]], [[https://openalex.org/A5032003715][Briana S. Henderson]], [[https://openalex.org/A5094240674][Adjeoda A. Tekpor]], [[https://openalex.org/A5016107902][Matthew R. Espinosa]], [[https://openalex.org/A5077916079][Paramita Saha]], [[https://openalex.org/A5004911977][Theodor Agapie]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00156  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00156][pdf]])
     
A dinickel complex, X-Ni2, was developed and demonstrated to have a high performance in ethylene/acrylate copolymerization. Further mechanistic studies revealed that X-Ni2 performs acrylate insertion at both Ni centers at distinct rates. Addition of NaBArF24 to X-Ni2 leads to 1:1 binding and serves as a switch for tuning catalytic activity, copolymer MW and acrylate incorporation. NMR studies of cation binding, when present in substoichiometric amounts, suggest a dynamic process involving cation exchange. This phenomenon provides an alternative strategy for controlling chain growth in polar polyolefin synthesis and was probed herein.    

    

* Ketyl Radical Generation by Photoexcited Palladium and Development of Organopalladium-Type Reactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393162411
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00510")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393162411"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393162411"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393162411"))][Get cited by]]

OpenAlex: https://openalex.org/W4393162411 (Open access: False)
    
[[https://openalex.org/A5008092092][Kosaku Tanaka]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00510 
     
Enabling reactions of traditional substrates that are inert to Pd catalysts has the potential for further advancements in the field of Pd chemistry. In this study, we developed a method for generating ketyl radicals through the reaction of a photoexcited Pd species with ketones. Upon subsequent reaction with olefins, the ketyl radicals generated through this method yielded Pd-specific reductive and Heck-type coupling products. Mechanistic studies indicated that the proposed radical generation method exhibits characteristics distinct from those of traditional methods such as SmI2 reduction and photoredox-catalyzed reactions.    

    

* Promoting Photocatalytic CO2 Methanation by the Construction of Cooperative Copper Dual-Active Sites  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393164230
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00060")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393164230"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393164230"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393164230"))][Get cited by]]

OpenAlex: https://openalex.org/W4393164230 (Open access: False)
    
[[https://openalex.org/A5063982212][Minghui Zhang]], [[https://openalex.org/A5090099599][Yuyin Mao]], [[https://openalex.org/A5043423601][Xiaolei Bao]], [[https://openalex.org/A5073772846][Peng Wang]], [[https://openalex.org/A5064686033][Yuanyuan Liu]], [[https://openalex.org/A5005994132][Zhaoke Zheng]], [[https://openalex.org/A5055777639][Hefeng Cheng]], [[https://openalex.org/A5071337833][Ying Dai]], [[https://openalex.org/A5071494860][Zeyan Wang]], [[https://openalex.org/A5026904646][Baibiao Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00060 
     
Selective photocatalytic CO2 methanation provides an attractive avenue to address energy and environmental issues. However, impediments such as the sluggish adsorption and activation of CO2 and H2O molecules, along with unexpected intermediate desorption, greatly restrict the activity and selectivity of photocatalytic CO2 methanation. To address these issues, we devised a dual-active site catalyst comprising Cu single atoms (SAs) and nanoclusters (NCs) supported on defective TiO2 (Cu1+NCs/BT). As a result, a remarkable CH4 selectivity of 98% with a yield of 19.63 μmol gcat.–1 h–1 can be obtained over the as-prepared Cu1+NCs/BT in pure water. Mechanistic studies reveal the enhanced performance could be ascribed to the synergistic effect of the Cu dual-active sites, where Cu SAs adsorb and activate CO2, while Cu NCs boost H2O adsorption and dissociation for *H coverage. Additionally, the adjacent Cu dual-active site could jointly stabilize the *CO intermediate and reduce the energy barrier for *CO protonation, promoting the multielectron transfer process.    

    
