#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Thu Jan 18 18:31:11 2024

Found 50 results from 2024-01-11 to 2024-01-18
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]
** The Relevance of the Interfacial Water Reactivity for Electrochemical CO Reduction on Copper Single Crystals   
:PROPERTIES:
:ID: https://openalex.org/W4390659412
:DOI: https://doi.org/10.1021/acscatal.3c02700
:AUTHORS: Daniel Winkler, Matthias Leitner, Andrea Auer, Julia Kunze‐Liebhäuser
:HOST: ACS Catalysis
:END:

Daniel Winkler, Matthias Leitner, Andrea Auer, Julia Kunze‐Liebhäuser, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c02700")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390659412"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390659412"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390659412"))][Get cited by]]

OpenAlex: https://openalex.org/W4390659412
    
Daniel Winkler, Matthias Leitner, Andrea Auer, Julia Kunze‐Liebhäuser, ACS Catalysis. https://doi.org/10.1021/acscatal.3c02700
    
The electrochemical reduction of CO2 is an important electrolysis reaction that enables the conversion of a waste gas to fuels or value-added chemicals. To make this reaction viable, a profound understanding of central intermediate steps, such as the CO electroreduction, is required. On Cu, the CO reduction reaction (CORR) is intimately linked to the hydrogen evolution reaction (HER) that proceeds via the reduction of water in alkaline or neutral electrolytes. Here, we demonstrate that the interaction of water or more specifically the water reduction kinetics on differently smooth Cu(100) and Cu(111) surfaces during the CORR in alkaline media significantly governs the CORR. On Cu(111), faster HER kinetics and the highest CORR activity are observed, even though HER and CORR onsets are more negative. While on Cu(100) small Cu ad-island clusters form in the cathodic potential range only when CO is present, structural changes appear on a larger length scale on Cu(111) both under CORR conditions and when no CO is present. These differences in the reconstruction characteristics may be attributed to the dominance of either the CORR and its intermediates or the HER on the different Cu surfaces. Therefore, the interfacial water reactivity is considered an essential activity descriptor for the CORR on Cu in alkaline media.    

    

** Surface States Governing the Activity and Selectivity of Pt-Based Ammonia Slip Catalysts for Selective Ammonia Oxidation   
:PROPERTIES:
:ID: https://openalex.org/W4390659955
:DOI: https://doi.org/10.1021/acscatal.3c05019
:AUTHORS: Vasyl Marchuk, Dmitry I. Sharapa, Jan‐Dierk Grunwaldt, Dmitry E. Doronkin
:HOST: ACS Catalysis
:END:

Vasyl Marchuk, Dmitry I. Sharapa, Jan‐Dierk Grunwaldt, Dmitry E. Doronkin, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390659955"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390659955"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390659955"))][Get cited by]]

OpenAlex: https://openalex.org/W4390659955
    
Vasyl Marchuk, Dmitry I. Sharapa, Jan‐Dierk Grunwaldt, Dmitry E. Doronkin, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05019
    
Selective oxidation of ammonia to nitrogen over Pt/Al2O3 was studied in order to determine active Pt species for the activity and selectivity of Pt under conditions close to those of realistic emission control applications. For this purpose, reaction rates and apparent activation energies were measured at different compositions of the reaction feed. Additionally, in situ diffuse reflectance infrared Fourier transform spectroscopy (DRIFTS) and operando X-ray absorption spectroscopy (XAS) including its interpretation based on theoretical XAS calculations were applied. Three main chemically different states of Pt were detected. The predominance of each of them correlated with the different performance of the catalyst at distinct temperature ranges. At low temperatures (<150 °C), the Pt surface was covered by oxygen species, which poisoned the catalyst. They needed to be removed by heating in the reaction mixture to start with a light off. At 150–300 °C, Pt was covered with NHx species, which provided the maximal selectivity to N2. At higher temperatures, when full ammonia conversion was reached, the Pt surface again became available for oxidation by the O species, resulting in both surface chemisorbed and subsurface O. This high-temperature state possessed high oxidation activity and high selectivity to undesired N2O and NOx.    

    

** Oxygen Vacancy Enhanced Proton Transfer to Boost Carbamate Decomposition Kinetics with Tunable Heterostructure Ni/NiO   
:PROPERTIES:
:ID: https://openalex.org/W4390661630
:DOI: https://doi.org/10.1021/acscatal.3c03852
:AUTHORS: Xing Li, Lei Xing, Guo‐Dong Zhan, Zhoulan Huang, Zhen Chen, Huazhen Chang, Junhua Li
:HOST: ACS Catalysis
:END:

Xing Li, Lei Xing, Guo‐Dong Zhan, Zhoulan Huang, Zhen Chen, Huazhen Chang, Junhua Li, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03852")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390661630"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390661630"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390661630"))][Get cited by]]

OpenAlex: https://openalex.org/W4390661630
    
Xing Li, Lei Xing, Guo‐Dong Zhan, Zhoulan Huang, Zhen Chen, Huazhen Chang, Junhua Li, ACS Catalysis. https://doi.org/10.1021/acscatal.3c03852
    
Catalytic carbamate decomposition is a feasible option for reducing the heat duty of amine solvent regeneration during the chemisorption of CO2 capture; advanced material with excellent proton transfer and exchange performance is crucial to boost the decomposition kinetics in an alkaline environment. Here, we prepared magnetic heterostructure Ni/NiO nanocatalysts with tunable Ni(0) nanoparticles and NiO support. The heterointerface of the proposed materials creates abundant surface oxygen vacancies (OVs) and offers abundant reactive active sites ascribed to the special electron transfer scheme of Ni0–NiO. The generated surface hydroxyls and unsaturated coordinated Ni, respectively, provide transferable protons and electrons, involved in the deprotonation of RNH3+ and C–N break of RNHCOO–. Thus, the obtained nanomaterials achieved considerably improved CO2 desorption of up to 3 mmol/min for a CO2-saturated monoethanolamine solvent, representing a substantial (approximately 50%) increase over the catalyst-free case. The reinforcement mechanism of OV generation by the Ni/NiO heterostructure and the induced proton transfer were revealed through in situ spectroscopic measurement and theoretical calculations. The results verified that the OVs stimulate the production of surface hydroxyls and water-assisted proton hopping, providing an advantageous condition for carbamate decomposition.    

    

** Design of High-Efficiency Hydrogen Evolution Catalysts in a Chiral Crystal   
:PROPERTIES:
:ID: https://openalex.org/W4390663619
:DOI: https://doi.org/10.1021/acscatal.3c03086
:AUTHORS: Jiasui Zhan, Yuliang Cao, Junwen Lai, Jiangxu Li, Hui Ma, Song Li, Peitao Liu, Xing‐Qiu Chen, Yan Sun
:HOST: ACS Catalysis
:END:

Jiasui Zhan, Yuliang Cao, Junwen Lai, Jiangxu Li, Hui Ma, Song Li, Peitao Liu, Xing‐Qiu Chen, Yan Sun, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03086")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390663619"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390663619"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390663619"))][Get cited by]]

OpenAlex: https://openalex.org/W4390663619
    
Jiasui Zhan, Yuliang Cao, Junwen Lai, Jiangxu Li, Hui Ma, Song Li, Peitao Liu, Xing‐Qiu Chen, Yan Sun, ACS Catalysis. https://doi.org/10.1021/acscatal.3c03086
    
The design of highly efficient hydrogen evolution reaction (HER) catalysts is one of the most important tasks for electrochemical water splitting in the field of renewable energy resources. In this work, via an effective combination of topologically trivial electronic intensity and the topologically nontrivial energy window, we predicted high catalytic performance in chiral material SiTc, with a close-to-zero hydrogen adsorption Gibbs free energy (−0.062 eV). With both a large intrinsic projected Berry phase and close-to-zero Gibbs free energy, SiTc provides a promising candidate for the HER catalysis reaction. In addition, this work offers an effective strategy for designing more potentially high activity topological electrocatalysts via the combination of topological states and high electronic intensity in metals.    

    

** Catalytic Stereoselective 1,2-<i>cis</i>-Furanosylations Enabled by Enynal-Derived Copper Carbenes   
:PROPERTIES:
:ID: https://openalex.org/W4390670725
:DOI: https://doi.org/10.1021/acscatal.3c05237
:AUTHORS: B. N. Ghosh, Adam Alber, Chance Lander, Yihan Shao, Kenneth M. Nicholas, Indrajeet Sharma
:HOST: ACS Catalysis
:END:

B. N. Ghosh, Adam Alber, Chance Lander, Yihan Shao, Kenneth M. Nicholas, Indrajeet Sharma, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05237")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390670725"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390670725"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390670725"))][Get cited by]]

OpenAlex: https://openalex.org/W4390670725
    
B. N. Ghosh, Adam Alber, Chance Lander, Yihan Shao, Kenneth M. Nicholas, Indrajeet Sharma, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05237
    
1,2-cis-Furanosides are present in various biomedically relevant glycosides, and their stereoselective synthesis remains a significant challenge. In this vein, we have developed a stereoselective approach to 1,2-cis-furanosylations using earth-abundant copper catalysis. This protocol proceeds under mild conditions at room temperature and employs readily accessible benchtop stable enynal-derived furanose donors. This chemistry accommodates a variety of alcohols, including primary, secondary, and tertiary, as well as mannosyl alcohol acceptors, which have been incompatible with most known methods of furanosylation. The resulting 1,2-cis-furanoside products exhibit high yields and anomeric selectivity with both the ribose and arabinose series. Furthermore, the anomeric selectivity is independent of the C2 oxygen-protecting group and the anomeric configuration of the starting donor. Experimental evidence and computational studies support our hypothesis that copper chelation between the C2 oxygen of the furanose donor and an incoming alcohol nucleophile is responsible for the observed 1,2-cis-stereoselectivity.    

    

** Exploiting Multimetallic Cooperativity in the Ring-Opening Polymerization of Cyclic Esters and Ethers   
:PROPERTIES:
:ID: https://openalex.org/W4390673532
:DOI: https://doi.org/10.1021/acscatal.3c05103
:AUTHORS: Utku Yolsal, Peter J. Shaw, Phoebe A. Lowy, Raju Chambenahalli, Jennifer A. Garden
:HOST: ACS Catalysis
:END:

Utku Yolsal, Peter J. Shaw, Phoebe A. Lowy, Raju Chambenahalli, Jennifer A. Garden, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05103")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390673532"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390673532"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390673532"))][Get cited by]]

OpenAlex: https://openalex.org/W4390673532
    
Utku Yolsal, Peter J. Shaw, Phoebe A. Lowy, Raju Chambenahalli, Jennifer A. Garden, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05103
    
The use of multimetallic complexes is a rapidly advancing route to enhance catalyst performance in the ring-opening polymerization of cyclic esters and ethers. Multimetallic catalysts often outperform their monometallic analogues in terms of reactivity and/or polymerization control, and these improvements are typically attributed to “multimetallic cooperativity”. Yet the origins of multimetallic cooperativity often remain unclear. This review explores the key factors underpinning multimetallic cooperativity, including metal–metal distances, the flexibility, electronics and conformation of the ligand framework, and the coordination environment of the metal centers. Emerging trends are discussed to provide insights into why cooperativity occurs and how to harness cooperativity for the development of highly efficient multimetallic catalysts.    

    

** Functional Characterization and Protein Engineering of a Glycosyltransferase GcCGT to Produce Flavone 6,8-Di-<i>C</i>- and 6-<i>C</i>-4′-<i>O</i>-Glycosides   
:PROPERTIES:
:ID: https://openalex.org/W4390674506
:DOI: https://doi.org/10.1021/acscatal.3c05252
:AUTHORS: Yang-Oujie Bao, Meng Zhang, Haoran Li, Zilong Wang, Jiajing Zhou, Yi Yang, Fudong Li, Lei Ye, Hongye Li, Hongwei Jin, Chao He, Min Ye
:HOST: ACS Catalysis
:END:

Yang-Oujie Bao, Meng Zhang, Haoran Li, Zilong Wang, Jiajing Zhou, Yi Yang, Fudong Li, Lei Ye, Hongye Li, Hongwei Jin, Chao He, Min Ye, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05252")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390674506"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390674506"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390674506"))][Get cited by]]

OpenAlex: https://openalex.org/W4390674506
    
Yang-Oujie Bao, Meng Zhang, Haoran Li, Zilong Wang, Jiajing Zhou, Yi Yang, Fudong Li, Lei Ye, Hongye Li, Hongwei Jin, Chao He, Min Ye, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05252
    
Herein, we discovered an efficient flavone 6-C-glycosyltransferase GcCGT from the medicinal plant Gentiana crassicaulis. GcCGT could catalyze consecutive two-step 6-C/4′-O-glycosylation of flavonoids. Homology modeling and site-directed mutagenesis yielded mutant F387K, which could catalyze the unprecedented 6-C-glycosylation of flavone 8-C-glycosides to produce 6,8-di-C-glycosides. To elucidate the catalytic mechanisms, the crystal structures of GcCGT-apo (2.10 Å) and GcCGT/UDP (2.40 Å) were resolved. Structural analysis and molecular dynamics simulations indicated that the lack of π–π stacking interaction for F387 changed the protein conformation and expanded the entrance of the substrate binding pocket. This work provided an efficient method to synthesize flavone 6,8-di-C- and 6-C-4′-O-glycosides.    

    

** Direct Oxidation of Methanol to Polyoxymethylene Dimethyl Ethers over FeMo@HZSM-5 Core–Shell Catalyst   
:PROPERTIES:
:ID: https://openalex.org/W4390675373
:DOI: https://doi.org/10.1021/acscatal.3c04941
:AUTHORS: Xiaqing Wang, Xiujuan Gao, Faen Song, Xiaoxing Wang, Guozhong Cao, Junfeng Zhang, Yizhuo Han, Qingde Zhang
:HOST: ACS Catalysis
:END:

Xiaqing Wang, Xiujuan Gao, Faen Song, Xiaoxing Wang, Guozhong Cao, Junfeng Zhang, Yizhuo Han, Qingde Zhang, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04941")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390675373"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390675373"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390675373"))][Get cited by]]

OpenAlex: https://openalex.org/W4390675373
    
Xiaqing Wang, Xiujuan Gao, Faen Song, Xiaoxing Wang, Guozhong Cao, Junfeng Zhang, Yizhuo Han, Qingde Zhang, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04941
    
Direct oxidation of methanol to polyoxymethylene dimethyl ethers (PODEn) with longer C–O chains faces a challenge due to difficult matching of active sites. Herein, a core–shell catalyst composed of an iron molybdenum core and a zeolite shell has been designed, successfully realizing methanol oxidation to PODEn. The PODE2–6 selectivity reaches 41.0% at 85.6% methanol conversion over the FeMo@HZSM-5 catalyst. Combined with the designed experiments and characterizations, the special core–shell structure and the synergy between acid sites with different strengths and redox sites are the pivotal factors for promoting the chain growth of the C–O bond.    

    

** Dual and Triple Atom Electrocatalysts for Energy Conversion (CO<sub>2</sub>RR, NRR, ORR, OER, and HER): Synthesis, Characterization, and Activity Evaluation   
:PROPERTIES:
:ID: https://openalex.org/W4390685826
:DOI: https://doi.org/10.1021/acscatal.3c05000
:AUTHORS: Adam M. Roth-Zawadzki, Alexander J. Nielsen, Rikke Plougmann, Jakob Kibsgaard
:HOST: ACS Catalysis
:END:

Adam M. Roth-Zawadzki, Alexander J. Nielsen, Rikke Plougmann, Jakob Kibsgaard, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05000")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390685826"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390685826"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390685826"))][Get cited by]]

OpenAlex: https://openalex.org/W4390685826
    
Adam M. Roth-Zawadzki, Alexander J. Nielsen, Rikke Plougmann, Jakob Kibsgaard, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05000
    
Dual and triple atom catalysts (DACs and TACs) are an emerging field of heterogeneous catalysis research. They share properties with single atom catalysts (SACs), such as maximizing dispersion of metals and the ability to circumvent the traditional scaling relations that limit extended surfaces. DACs and TACs additionally provide adjacent sites that are necessary for certain reaction mechanisms and add to the tunability of the electronic structure and binding energies. DACs and TACs are, however, inherently difficult to selectively synthesize and characterize. Characterization and activity evaluation are prone to misinterpretation, adding confusion to the already complex field. In this review, we investigate the current progress of DACs for important electrochemical reactions in energy conversion and storage. We further discuss current and future synthesis methods for DACs and TACs and focus on common pitfalls in characterization and activity evaluation.    

    

** Elucidating the Mechanism for Oxidative Coupling of Methane Catalyzed by La<sub>2</sub>O<sub>3</sub>: Experimental and Microkinetic Modeling Studies   
:PROPERTIES:
:ID: https://openalex.org/W4390694581
:DOI: https://doi.org/10.1021/acscatal.3c04714
:AUTHORS: Zaili Xiong, Jijun Guo, Yuwen Deng, Bingzhi Liu, Hao Lou, Meirong Zeng, Zhandong Wang, Zhongyue Zhou, Wenhao Yuan, Fei Qi
:HOST: ACS Catalysis
:END:

Zaili Xiong, Jijun Guo, Yuwen Deng, Bingzhi Liu, Hao Lou, Meirong Zeng, Zhandong Wang, Zhongyue Zhou, Wenhao Yuan, Fei Qi, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04714")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390694581"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390694581"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390694581"))][Get cited by]]

OpenAlex: https://openalex.org/W4390694581
    
Zaili Xiong, Jijun Guo, Yuwen Deng, Bingzhi Liu, Hao Lou, Meirong Zeng, Zhandong Wang, Zhongyue Zhou, Wenhao Yuan, Fei Qi, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04714
    
Oxidative coupling of methane (OCM) has been widely proposed to be one of the most promising methods for the direct conversion of methane to C2 products, such as ethane and ethene. Highly active free radicals play a crucial role, while accurate identifications are limited. To probe these free radicals and reveal their reactions, experiments focused on the OCM catalyzed by La2O3 were designed to be carried out in a packed bed reactor at low-pressure conditions over a wide temperature range. Dozens of species, including methyl radical, ethyl radical, and formaldehyde, were observed by using synchrotron vacuum ultraviolet photoionization mass spectrometry (SVUV-PIMS). A microkinetic model that coupled a detailed gas-phase and surface mechanism was developed and validated against the experimental results, especially to reveal the crucial roles of free radicals in the formation of C2 products as well as the oxygenated intermediates. The prediction results of the kinetic model agreed well with the experimental measurements. Rate of production and sensitivity analysis were performed to reveal the complex reaction network and key reactions of the OCM. Methyl was confirmed to play a key role based on both experimental and modeling perspectives, while ethyl is crucial in the transformation of C2 species and the formation of C3–C4 species. This indicates that the selective regulation of free radicals such as methyl and ethyl in OCM is worth paying attention to. The present work provides more detailed chemistry of OCM reactions, which would be helpful to improve product selectivity of OCM.    

    

** Electrochemical Monitoring of Heterogeneous Peroxygenase Reactions Unravels LPMO Kinetics   
:PROPERTIES:
:ID: https://openalex.org/W4390697114
:DOI: https://doi.org/10.1021/acscatal.3c05194
:AUTHORS: Lorenz Schwaiger, Florian Csarman, Hui S. Chang, Ole Golten, Vincent G. H. Eijsink, Roland Ludwig
:HOST: ACS Catalysis
:END:

Lorenz Schwaiger, Florian Csarman, Hui S. Chang, Ole Golten, Vincent G. H. Eijsink, Roland Ludwig, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05194")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390697114"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390697114"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390697114"))][Get cited by]]

OpenAlex: https://openalex.org/W4390697114
    
Lorenz Schwaiger, Florian Csarman, Hui S. Chang, Ole Golten, Vincent G. H. Eijsink, Roland Ludwig, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05194
    
Biological conversion of plant biomass depends on peroxygenases and peroxidases acting on insoluble polysaccharides and lignin. Among these are cellulose- and hemicellulose-degrading lytic polysaccharide monooxygenases (LPMOs), which have revolutionized our concept of biomass degradation. Major obstacles limiting mechanistic and functional understanding of these unique peroxygenases are their complex and insoluble substrates and the hard-to-measure H2O2 consumption, resulting in the lack of suitable kinetic assays. We report a versatile and robust electrochemical method for real-time monitoring and kinetic characterization of LPMOs and other H2O2-dependent interfacial enzymes based on a rotating disc electrode for the sensitive and selective quantitation of H2O2 at biologically relevant concentrations. The H2O2 sensor works in suspensions of insoluble substrates as well as in homogeneous solutions. Our characterization of multiple LPMOs provides unprecedented insights into the substrate specificity, kinetics, and stability of these enzymes. High turnover and total turnover numbers demonstrate that LPMOs are fast and durable biocatalysts.    

    

** Correction to “Brønsted Acid Strength Does Not Change for Bulk and External Sites of MFI Except for Al Substitution Where Silanol Groups Form”   
:PROPERTIES:
:ID: https://openalex.org/W4390701188
:DOI: https://doi.org/10.1021/acscatal.3c06041
:AUTHORS: Haliey Balcom, Alexander J. Hoffman, Huston Locht, David Hibbitts
:HOST: ACS Catalysis
:END:

Haliey Balcom, Alexander J. Hoffman, Huston Locht, David Hibbitts, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06041")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390701188"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390701188"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390701188"))][Get cited by]]

OpenAlex: https://openalex.org/W4390701188
    
Haliey Balcom, Alexander J. Hoffman, Huston Locht, David Hibbitts, ACS Catalysis. https://doi.org/10.1021/acscatal.3c06041
    
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVCorrectionNEXTORIGINAL ARTICLEThis notice is a correctionCorrection to “Brønsted Acid Strength Does Not Change for Bulk and External Sites of MFI Except for Al Substitution Where Silanol Groups Form”Haliey BalcomHaliey BalcomMore by Haliey Balcom, Alexander J. HoffmanAlexander J. HoffmanMore by Alexander J. Hoffmanhttps://orcid.org/0000-0002-1337-9297, Huston LochtHuston LochtMore by Huston Lochthttps://orcid.org/0009-0004-9654-0884, and David Hibbitts*David HibbittsMore by David Hibbittshttps://orcid.org/0000-0001-8606-7000Cite this: ACS Catal. 2024, 14, XXX, 1231Publication Date (Web):January 9, 2024Publication History Received12 December 2023Published online9 January 2024https://doi.org/10.1021/acscatal.3c06041© 2024 American Chemical SocietyRequest reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InReddit PDF (670 KB) Get e-AlertscloseSUBJECTS:Adsorption,Brønsted acid,Energy,Materials,Zeolites Get e-Alerts    

    

** Rational Design of Alloy Catalysts for Alkyne Semihydrogenation via Descriptor-Based High-Throughput Screening   
:PROPERTIES:
:ID: https://openalex.org/W4390701504
:DOI: https://doi.org/10.1021/acscatal.3c02398
:AUTHORS: Jiayi Wang, Haoxiang Xu, Jian Wu, Fengyu Zhang, Chi‐Ming Che, Jing Zhu, Junting Feng, Daojian Cheng
:HOST: ACS Catalysis
:END:

Jiayi Wang, Haoxiang Xu, Jian Wu, Fengyu Zhang, Chi‐Ming Che, Jing Zhu, Junting Feng, Daojian Cheng, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c02398")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390701504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390701504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390701504"))][Get cited by]]

OpenAlex: https://openalex.org/W4390701504
    
Jiayi Wang, Haoxiang Xu, Jian Wu, Fengyu Zhang, Chi‐Ming Che, Jing Zhu, Junting Feng, Daojian Cheng, ACS Catalysis. https://doi.org/10.1021/acscatal.3c02398
    
Although alloying is a common approach to developing catalysts for alkyne selective hydrogenation, the geometric and electronic effects of active sites on the kinetics of alkyne selective hydrogenation are still ambiguous, hindering rational design of alloy catalysts. Herein, we construct structural descriptors to categorize and reorganize the roles of electronic and geometric factors in the kinetics of acetylene semihydrogenation. The prediction model based on our proposed structural descriptors successfully elucidates the activity and selectivity trends among Pd-based alloys and can also be extended to rationalize the kinetics trend among single-atom alloys and Ni-based alloys for semihydrogenation of acetylene and even other alkynes, in good agreement with available experimental references. Aided by thermodynamic stability analysis and structural descriptors, 489 Pd-based bimetallic alloys via a high-throughput screening protocol were evaluated, and finally, Pd1Nb3 and Pd1Hf3 were identified with a high yield of ethylene and inexpensive cost and validated by our experimental studies.    

    

** Visible-Light Photocatalyzed C3–H Alkylation of 2<i>H</i>-Indazoles/Indoles with Sulfoxonium Ylides via Diversified Mechanistic Pathways   
:PROPERTIES:
:ID: https://openalex.org/W4390701516
:DOI: https://doi.org/10.1021/acscatal.3c04729
:AUTHORS: Altman Yuzhu Peng, Yujing Wang, Kaifeng Wang, Qi Sun, Xiaoguang Bao
:HOST: ACS Catalysis
:END:

Altman Yuzhu Peng, Yujing Wang, Kaifeng Wang, Qi Sun, Xiaoguang Bao, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04729")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390701516"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390701516"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390701516"))][Get cited by]]

OpenAlex: https://openalex.org/W4390701516
    
Altman Yuzhu Peng, Yujing Wang, Kaifeng Wang, Qi Sun, Xiaoguang Bao, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04729
    
Herein, the C3–H alkylation of 2H-indazoles and indoles with sulfoxonium ylides is developed under visible-light photocatalysis. This protocol employs easily accessible reagents, and a wide range of 2H-indazoles, indoles, and sulfoxonium ylides are suitable for this reaction to afford the desired products under benign conditions. Synergistic experimental and computational studies suggest that the sulfoxonium ylides involving C3–H alkylation of 2H-indazoles and indoles under visible-light photocatalysis could proceed via different mechanistic pathways. For the C3-alkylation of 2H-indazoles, a triplet energy transfer mechanistic pathway of 2H-indazoles is proposed for quenching the excited photocatalyst. Subsequently, the formed excited triplet state of 2H-indazoles could undergo radical attack on the C═S moiety of sulfoxonium ylides. After the dissociation of DMSO and 1,2-H migration, the final product of C3-alkylation of 2H-indazoles could be yielded. However, such a mechanistic pathway is not applicable for indoles. Instead, sulfoxonium ylides could be converted to a C-centered radical in the presence of KH2PO4 under visible-light photoredox conditions. The formed C-centered radical can attack the C3-site of indoles and thus lead to the C3-alkylation product of indoles.    

    

** How Does Structural Disorder Impact Heterogeneous Catalysts? The Case of Ammonia Decomposition on Non-stoichiometric Lithium Imide   
:PROPERTIES:
:ID: https://openalex.org/W4390703617
:DOI: https://doi.org/10.1021/acscatal.3c05376
:AUTHORS: Francesco Mambretti, Umberto Raucci, Manyi Yang, Michele Parrinello
:HOST: ACS Catalysis
:END:

Francesco Mambretti, Umberto Raucci, Manyi Yang, Michele Parrinello, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05376")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390703617"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390703617"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390703617"))][Get cited by]]

OpenAlex: https://openalex.org/W4390703617
    
Francesco Mambretti, Umberto Raucci, Manyi Yang, Michele Parrinello, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05376
    
Among the many catalysts suggested for ammonia decomposition, Li2NH has been shown to be quite promising. In the recent past, we have performed extensive ab initio-quality simulations to explain the workings of this unusual catalyst. In the complex scenario that has emerged, surface dynamics and structural disorder enhanced by the interaction with the reacting ammonia molecules have played crucial roles. Non-stoichiometric lithium imide (Li2–x(NH2)x(NH)1–x) has been reported to have better catalytic performances than pure lithium imide. Stimulated by these findings, we follow up our previous study simulating the ammonia decomposition on such non-stoichiometric compounds. We attribute the enhanced reactivity to the fact that the compositional disorder further enhances the fluctuations in the topmost layers of the catalyst, strengthening our dynamic picture of this catalytic process.    

    

** Screening Cu-Zeolites for Methane Activation Using Curriculum-Based Training   
:PROPERTIES:
:ID: https://openalex.org/W4390703624
:DOI: https://doi.org/10.1021/acscatal.3c05275
:AUTHORS: Jiawei Guo, Tyler Sours, Sam Holton, Chenghan Sun, Ambarish Kulkarni
:HOST: ACS Catalysis
:END:

Jiawei Guo, Tyler Sours, Sam Holton, Chenghan Sun, Ambarish Kulkarni, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05275")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390703624"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390703624"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390703624"))][Get cited by]]

OpenAlex: https://openalex.org/W4390703624
    
Jiawei Guo, Tyler Sours, Sam Holton, Chenghan Sun, Ambarish Kulkarni, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05275
    
Machine learning (ML), when used synergistically with atomistic simulations, has recently emerged as a powerful tool for accelerated catalyst discovery. However, the application of these techniques has been limited by the lack of interpretable and transferable ML models. In this work, we propose a curriculum-based training (CBT) philosophy to systematically develop reactive machine learning potentials (rMLPs) for high-throughput screening of zeolite catalysts. Our CBT approach combines several different types of calculations to gradually teach the ML model about the relevant regions of the reactive potential energy surface. The resulting rMLPs are accurate, transferable, and interpretable. We further demonstrate the effectiveness of this approach by exhaustively screening thousands of [CuOCu]2+ sites across hundreds of Cu-zeolites for the industrially relevant methane activation reaction. Specifically, this large-scale analysis of the entire International Zeolite Association (IZA) database identifies a set of previously unexplored zeolites (i.e., MEI, ATN, EWO, and CAS) that show the highest ensemble-averaged rates for [CuOCu]2+-catalyzed methane activation. We believe that this CBT philosophy can be generally applied to other zeolite-catalyzed reactions and, subsequently, to other types of heterogeneous catalysts. Thus, this represents an important step toward overcoming the long-standing barriers within the computational heterogeneous catalysis community.    

    

** Deciphering the Unconventional Reduction of C═N Bonds by Old Yellow Enzymes Using QM/MM   
:PROPERTIES:
:ID: https://openalex.org/W4390704303
:DOI: https://doi.org/10.1021/acscatal.3c04362
:AUTHORS: Amit Singh, Nakia Polidori, Wolfgang Kroutil, Karl Gruber
:HOST: ACS Catalysis
:END:

Amit Singh, Nakia Polidori, Wolfgang Kroutil, Karl Gruber, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04362")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390704303"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390704303"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390704303"))][Get cited by]]

OpenAlex: https://openalex.org/W4390704303
    
Amit Singh, Nakia Polidori, Wolfgang Kroutil, Karl Gruber, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04362
    
The reduction of C═X (X = N, O) bonds is a cornerstone in both synthetic organic chemistry and biocatalysis. Conventional reduction mechanisms usually involve a hydride ion targeting the less electronegative carbon atom. In a departure from this paradigm, our investigation into Old Yellow Enzymes (OYEs) reveals a mechanism involving transfer of hydride to the formally more electronegative nitrogen atom within a C═N bond. Beyond their known ability to reduce electronically activated C═C double bonds, e.g., in α, β-unsaturated ketones, these enzymes have recently been shown to reduce α-oximo-β-ketoesters to the corresponding amines. It has been proposed that this transformation involves two successive reduction steps and proceeds via imine intermediates formed by the reductive dehydration of the oxime moieties. We employ advanced quantum mechanics/molecular mechanics (QM/MM) simulations, enriched by a two-tiered approach incorporating QM/MM (UB3LYP-6-31G*/OPLS2005) geometry optimization, QM/MM (B3LYP-6-31G*/amberff19sb) steered molecular dynamics simulations, and detailed natural-bond-orbital analyses to decipher the unconventional hydride transfer to nitrogen in both reduction steps and to delineate the role of active site residues as well as of substituents present in the substrates. Our computational results confirm the proposed mechanism and agree well with experimental mutagenesis and enzyme kinetics data. According to our model, the catalysis of OYE involves hydride transfer from the flavin cofactor to the nitrogen atom in oximoketoesters as well as iminoketoesters followed by protonation at the adjacent oxygen or carbon atoms by conserved tyrosine residues and active site water molecules. Two histidine residues play a key role in the polarization and activation of the C═N bond, and conformational changes of the substrate observed along the reaction coordinate underline the crucial importance of dynamic electron delocalization for efficient catalysis.    

    

** Highly Active MnCoO<sub><i>x</i></sub> Catalyst toward CO Preferential Oxidation   
:PROPERTIES:
:ID: https://openalex.org/W4390704389
:DOI: https://doi.org/10.1021/acscatal.3c04654
:AUTHORS: Jun Yu, Yusen Yang, Meng Zhang, Boyu Song, Yu Han, Si Wang, Zhihao Ren, Lei Wang, Ping Yin, Lirong Zheng, Xin Zhang, Min Wei
:HOST: ACS Catalysis
:END:

Jun Yu, Yusen Yang, Meng Zhang, Boyu Song, Yu Han, Si Wang, Zhihao Ren, Lei Wang, Ping Yin, Lirong Zheng, Xin Zhang, Min Wei, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04654")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390704389"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390704389"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390704389"))][Get cited by]]

OpenAlex: https://openalex.org/W4390704389
    
Jun Yu, Yusen Yang, Meng Zhang, Boyu Song, Yu Han, Si Wang, Zhihao Ren, Lei Wang, Ping Yin, Lirong Zheng, Xin Zhang, Min Wei, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04654
    
Preferential oxidation of CO (CO-PROX) is an efficient method to eliminate residual CO in the feed stream to avoid Pt poisoning in proton-exchange-membrane fuel cells (PEMFCs), in which the development of high-performance, low-cost catalysts remains a big challenge. Herein, we report highly active spinel-like MnCoOx catalysts derived from layered double hydroxide (LDH) precursors, which are featured with abundant octahedron-distorted lattice oxygen. Impressively, the optimal catalyst MnCoOx-300 achieves the selective and complete removal of CO from a H2-rich stream at 80 °C, within a wide operation temperature window (80–200 °C, matching well with PEMFCs) at a rather high space velocity (80,000 h–1). This performance, to the best of our knowledge, outperforms previously reported non-noble metal catalysts and even exceeds the state-of-the-art CuO/CeO2 system in the CO-PROX technology. A comprehensive investigation based on in situ Raman, in situ XAFS, in situ TPD-Mass, and in situ DRIFTS reveals that the Cooct3+–O2––Mnoct4+ structure in MnCoOx-300 serves as the intrinsic active site that facilitates preferential oxidation: the lattice oxygen participates in the oxidation of CO to produce CO2 and oxygen vacancy (Ov), followed by the replenishment of oxygen species from aerial oxygen (the rate-determining step) to regenerate Cooct3+–O2––Mnoct4+. Isotopic 18O kinetic studies and in situ DRIFTS substantiate that the reaction temperature plays a crucial role in the competitive oxidation of CO vs H2 at the same active site. This work provides a successful paradigm for the design and preparation of transition metal oxide catalysts toward the CO-PROX reaction, which shows potential applications in hydrogen purification for PEMFCs.    

    

** Iron-Carbene Initiated O–H Insertion/Aldol Cascade for the Stereoselective Synthesis of Functionalized Tetrahydrofurans   
:PROPERTIES:
:ID: https://openalex.org/W4390718518
:DOI: https://doi.org/10.1021/acscatal.3c05040
:AUTHORS: Prakash Kafle, B. N. Ghosh, Arianne C. Hunter, Rishav Mukherjee, Kenneth M. Nicholas, Indrajeet Sharma
:HOST: ACS Catalysis
:END:

Prakash Kafle, B. N. Ghosh, Arianne C. Hunter, Rishav Mukherjee, Kenneth M. Nicholas, Indrajeet Sharma, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05040")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390718518"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390718518"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390718518"))][Get cited by]]

OpenAlex: https://openalex.org/W4390718518
    
Prakash Kafle, B. N. Ghosh, Arianne C. Hunter, Rishav Mukherjee, Kenneth M. Nicholas, Indrajeet Sharma, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05040
    
Given its earth abundance, cost-effectiveness, and ecofriendly qualities, iron serves as a promising alternative to precious metals in catalysis. This article presents an iron carbene-initiated cascade approach for synthesizing highly substituted tetrahydrofurans at the gram scale. This cascade reaction utilizes readily accessible β-hydroxyketones and diazo compounds and works with iron catalyst loading as low as 5 mol %. This reaction proceeds through an O–H insertion into diazo-derived iron carbenes, followed by an intramolecular aldol reaction to access functionalized tetrahydrofurans in high yields and diastereoselectivity. The versatile nature of this domino sequence accommodates diverse β-hydroxyketones and diazo compounds, streamlining access to synthetically challenging spiroethers. Furthermore, this cascade process offers a route to enantiopure tetrahydrofurans by utilizing a diazo ester bearing a chiral auxiliary, 8-phenylmenthol. Postmodifications of the tetrahydrofuran product provide access to various analogues, including a medicinally relevant oxetane motif. Density functional theory (DFT) calculations substantiate a stereospecific mechanism wherein the intramolecular aldol reaction proceeds via a fused six- and five-membered iron–oxygen transition-state complex, yielding the contrathermodynamic cis-aldol product.    

    

** Enantioselective Synthesis of “NO<sub>2</sub>···NH” Hydrogen Bond-Stabilized C–N Axially Chiral Diarylamines   
:PROPERTIES:
:ID: https://openalex.org/W4390724252
:DOI: https://doi.org/10.1021/acscatal.3c04775
:AUTHORS: Wei Lin, Yuanhu Shao, Zeyang Hao, Zhe Huang, Zhiyuan Ren, Li Chen, Xin Li
:HOST: ACS Catalysis
:END:

Wei Lin, Yuanhu Shao, Zeyang Hao, Zhe Huang, Zhiyuan Ren, Li Chen, Xin Li, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04775")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390724252"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390724252"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390724252"))][Get cited by]]

OpenAlex: https://openalex.org/W4390724252
    
Wei Lin, Yuanhu Shao, Zeyang Hao, Zhe Huang, Zhiyuan Ren, Li Chen, Xin Li, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04775
    
Herein, N-nucleophilic tandem oxidation–N-arylation–oxidation reaction and C-nucleophilic bromination reaction of substituted anilines have been developed using chiral phosphoric acid catalysis, enabling access to axially chiral diarylamines. The key feature of this strategy is that the “NO2···H–N” hydrogen bond was successfully introduced into acyclic diaryl secondary amines, which contain two potential contiguous atropisomeric C–N axes, to stabilize one of the planar axial conformations. This methodology provided a series of optically pure diarylamine atropisomers containing this new hydrogen bond type in good yields (up to 99%) and high enantiomeric ratios (up to 99.5:0.5 e.r.). The synthetic utility was demonstrated through large-scale reactions and transformations of the products. Plausible models were proposed to explain the enantioselectivity of the products.    

    

** Manipulating the Morphology and Electronic State of a Two-Dimensional Coordination Polymer as a Hydrogen Evolution Cocatalyst Enhances Photocatalytic Overall Water Splitting   
:PROPERTIES:
:ID: https://openalex.org/W4390728497
:DOI: https://doi.org/10.1021/acscatal.3c04389
:AUTHORS: Jingyan Guan, Kazuma Koizumi, Naoya Fukui, Hajime Suzuki, Kantaro Murayama, Ryojun Toyoda, Hiroaki Maeda, Kazuhide Kamiya, Keitaro Ohashi, Shinya Takaishi, Osamu Tomita, Akinori Saeki, Hiroshi Nishihara, Hiroshi Kageyama, Ryu Abe, Ryota Sakamoto
:HOST: ACS Catalysis
:END:

Jingyan Guan, Kazuma Koizumi, Naoya Fukui, Hajime Suzuki, Kantaro Murayama, Ryojun Toyoda, Hiroaki Maeda, Kazuhide Kamiya, Keitaro Ohashi, Shinya Takaishi, Osamu Tomita, Akinori Saeki, Hiroshi Nishihara, Hiroshi Kageyama, Ryu Abe, Ryota Sakamoto, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04389")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390728497"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390728497"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390728497"))][Get cited by]]

OpenAlex: https://openalex.org/W4390728497
    
Jingyan Guan, Kazuma Koizumi, Naoya Fukui, Hajime Suzuki, Kantaro Murayama, Ryojun Toyoda, Hiroaki Maeda, Kazuhide Kamiya, Keitaro Ohashi, Shinya Takaishi, Osamu Tomita, Akinori Saeki, Hiroshi Nishihara, Hiroshi Kageyama, Ryu Abe, Ryota Sakamoto, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04389
    
To achieve efficacious photocatalytic overall water splitting, surface modification of photocatalysts with proficient cocatalysts for hydrogen evolution reaction (HER) is imperative. NiBHT, a conductive two-dimensional coordination polymer (2D CP), or a 2D metal–organic framework (2D MOF), endowed with remarkable chemical stability and HER selectivity, emerged as a promising candidate for an HER cocatalyst. However, the bulky morphology of NiBHT hampered its performance. Here, we demonstrate a strategy to miniaturize NiBHT by incorporating the benzene-1,2-dithiol (BDT) ligand, yielding NiBHT nanoparticles (NiBHT-NP). Beyond morphology, empirical evidence unveiled alterations in the electronic state and catalytic activity of NiBHT-NP, and the ramifications of BDT modulation on intrinsic characteristics are elucidated through density functional theory (DFT) calculations. As a model system, CoOx/SrTiO3:Al photocatalyst with NiBHT-NP modification exhibited an apparent quantum efficiency (AQE) of 10.3% at 365 nm for overall water splitting. This pioneering work showcases that a modulator ligand may manipulate the morphology, electronic state, and catalytic behavior of 2D CPs, holding prodigious potential for developing more effective CP-based HER cocatalysts.    

    

** Shape Selectivity of AEL Channels for Anomalously Facilitating Biojet Fuel Production from Long-Chain <i>n</i>-Alkane Hydrocracking   
:PROPERTIES:
:ID: https://openalex.org/W4390732536
:DOI: https://doi.org/10.1021/acscatal.3c04465
:AUTHORS: Chao Mu, Junhao Sun, Chuang Xie, Jianming Bao, Xuan Guo, Haozhe Zhang, Yujun Zhao, Shengping Wang, Xinbin Ma
:HOST: ACS Catalysis
:END:

Chao Mu, Junhao Sun, Chuang Xie, Jianming Bao, Xuan Guo, Haozhe Zhang, Yujun Zhao, Shengping Wang, Xinbin Ma, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04465")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390732536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390732536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390732536"))][Get cited by]]

OpenAlex: https://openalex.org/W4390732536
    
Chao Mu, Junhao Sun, Chuang Xie, Jianming Bao, Xuan Guo, Haozhe Zhang, Yujun Zhao, Shengping Wang, Xinbin Ma, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04465
    
Hydrocracking of long-chain n-alkanes from hydrotreating of vegetable oil is critical for biojet fuel production and requires selective C–C cleavage near the long-chain alkane end. Due to preferential cracking near the carbon chain end in AEL channels, SAPO-11 optionally produces heavy jet fuel fractions in hydrocracking of the model reactant n-C16. Also, the weak acidity of SAPO-11 promotes olefin desorption and markedly reduces the second cracking of jet fuel fractions formed. Compared to 10-MR Si–Al ZSM-22, ZSM-23, ZSM-5, and ZSM-35 zeolites, SAPO-11 significantly improves the jet fuel production performance. Surprisingly,10-membered rings (10-MR) SAPO-11 exhibits higher jet fuel yields than 12-membered rings (12-MR) HUSY (FAU topology), contrary to the general belief that larger pores are more conducive to heavy cracking product production. Further, theoretical molar cracking product distributions of C15–C18 fractions are proposed, highlighting the superior performance of SAPO-11 over that of HUSY and delineating the yield limits for jet fuel production. Higher than those of commercial biojet fuels, the isomer content of jet fuel fractions exceeds 89% at cracking yield above 70%. It indicates that weakly acidic SAPO-11 has potential for specific cracking reactions near the long-chain alkane end, which enriches the understanding of selective C–C cleavage by zeolites for high-value cracking products.    

    

** Electronic and Electrochemical Control of Isostructural Ruthenium Hydricities and the Implications for Catalytic Overpotentials   
:PROPERTIES:
:ID: https://openalex.org/W4390732717
:DOI: https://doi.org/10.1021/acscatal.3c04589
:AUTHORS: Zong-Heng Wang, Brian N. DiMarco, Mehmed Z. Ertem, Renato N. Sampaio, Gerald F. Manbeck
:HOST: ACS Catalysis
:END:

Zong-Heng Wang, Brian N. DiMarco, Mehmed Z. Ertem, Renato N. Sampaio, Gerald F. Manbeck, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04589")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390732717"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390732717"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390732717"))][Get cited by]]

OpenAlex: https://openalex.org/W4390732717
    
Zong-Heng Wang, Brian N. DiMarco, Mehmed Z. Ertem, Renato N. Sampaio, Gerald F. Manbeck, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04589
    
Electronic tuning of metal hydrides enables precise control over potentials, mechanisms, selectivity, and rates of electrocatalytic reactions by regulating bond dissociation free energies such as the hydricity (ΔGH–°) and pKa of the catalyst. Here, we investigate a series of electronically tuned ruthenium hydrido complexes that are isostructural at the metal center: [Ru(4,4′-R2-bpy)2(CO)H]+ (R = CF3, Cl, H, CH3, and CH3O; bpy = 2,2′-bipyridine) (denoted as (R)Ru–H+). A substantial 22 kcal mol–1 hydricity range is available across five complexes in three stable oxidation states: (R)Ru–H+, (R)Ru–H0, and (R)Ru–H–. Thermodynamic and mechanistic predictions of electrocatalytic proton reduction were tested experimentally by reducing protons from weak acids to H2. Two mechanisms are observed, depending on the acid strength and the catalyst hydricity. The rate constants for hydride transfer and protonation of the catalyst were, in some cases, extracted from the analysis of cyclic voltammetry data. A key finding is a 400 mV decrease in the catalytic overpotential for H2 production by using a doubly reduced electron-poor metal hydride instead of a singly reduced electron-rich metal hydride. The former also exhibits a higher rate constant for hydride transfer, representing a strategy to disconnect rate and free energy relationships.    

    

** Insight into the Structure of Mn-NiS<sub>2</sub> during Urea Oxidation Using Combined In Situ X-ray Absorption Spectroscopy and Attenuated Total Reflectance Surface-Enhanced Infrared Absorption Spectroscopy   
:PROPERTIES:
:ID: https://openalex.org/W4390734560
:DOI: https://doi.org/10.1021/acscatal.3c05369
:AUTHORS: Niangao Duan, Tianxin Hou, Wei Zheng, Yafei Qu, Peichen Wang, Jun Yang, Yang Yang, Dongdong Wang, Jitang Chen, Qianwang Chen
:HOST: ACS Catalysis
:END:

Niangao Duan, Tianxin Hou, Wei Zheng, Yafei Qu, Peichen Wang, Jun Yang, Yang Yang, Dongdong Wang, Jitang Chen, Qianwang Chen, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05369")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390734560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390734560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390734560"))][Get cited by]]

OpenAlex: https://openalex.org/W4390734560
    
Niangao Duan, Tianxin Hou, Wei Zheng, Yafei Qu, Peichen Wang, Jun Yang, Yang Yang, Dongdong Wang, Jitang Chen, Qianwang Chen, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05369
    
The urea electrocatalytic oxidation reaction (UOR) has enormous potential as an ideal alternative anode reaction for water splitting owing to its lower thermodynamic equilibrium potential of 0.37 V versus reversible hydrogen electrode (vs RHE). Nickel-based materials, especially NiOOH, are considered to be one of the most promising non-noble metal catalysts for UOR due to their inexpensive cost and rich abundance. However, NiOOH displays a high overpotential and poor long-term stability. Herein, our density functional theory calculations show that the rate-determining step for UOR is desorption of CO2 on NiOOH, and Mn-doped NiOOH has the lowest energy for CO2 desorption. Hence, we prepared a Mn-NiS2 precatalyst that would transform into the active form of Mn-NiOOH during the electrochemical process. The catalyst exhibits good performance for UOR, achieving 100 mA cm–2 at 1.426 V (vs RHE, without IR correction) for 200 h with no significant voltage change, which is rarely reported for nonprecious-metal UOR catalysts. X-ray absorption near-edge spectroscopy and X-ray diffraction characterization show the transformation from sulfide to oxyhydroxide when a voltage is applied, while in situ attenuated total reflectance surface-enhanced infrared absorption spectroscopy (ATR-SEIRAS) proves that Mn-NiOOH accelerates the desorption of CO2 compared to NiOOH.    

    

** Iron-Catalyzed 5-Endo-Dig Synthetic Approach to Indenes and Its Bidirectional Extension to Narrow Bandgap π-Systems   
:PROPERTIES:
:ID: https://openalex.org/W4390734752
:DOI: https://doi.org/10.1021/acscatal.3c04961
:AUTHORS: Mengqing Chen, Yuki Itabashi, Shota Fukuma, Rui Shang, Eiichi Nakamura
:HOST: ACS Catalysis
:END:

Mengqing Chen, Yuki Itabashi, Shota Fukuma, Rui Shang, Eiichi Nakamura, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390734752"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390734752"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390734752"))][Get cited by]]

OpenAlex: https://openalex.org/W4390734752
    
Mengqing Chen, Yuki Itabashi, Shota Fukuma, Rui Shang, Eiichi Nakamura, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04961
    
The indene skeleton is a key structure in a variety of compounds, with applications in medicinal and materials science. Traditional syntheses often require harsh conditions or reactive intermediates due to the temporary disruption of the aromaticity of the developing indene ring. To circumvent this problem, we have investigated iron-catalyzed 5-endo-dig cyclization for the construction of the five-membered carbocycle component of indene, which does not interrupt the benzene ring’s aromaticity. A reduced iron reactive species generated by the reduction of FeCl2 with metallic magnesium is a key reactive species that effectively cleaves the C–O bond in the starting material to generate a dormant radical-stabilized iron, which smoothly undergoes the 5-endo-dig closure of an indene ring. The synthetic conditions are so mild that we synthesized a high highest occupied molecular orbital (HOMO), narrow bandgap conjugated compound that has a HOMO level as high as −4.59 eV and an optical bandgap of 1.50 eV; hence, it is unstable even under air.    

    

** The Relevance of the Interfacial Water Reactivity for Electrochemical CO Reduction on Copper Single Crystals   
:PROPERTIES:
:ID: https://openalex.org/W4390659412
:DOI: https://doi.org/10.1021/acscatal.3c02700
:AUTHORS: Daniel Winkler, Matthias Leitner, Andrea Auer, Julia Kunze‐Liebhäuser
:HOST: ACS Catalysis
:END:

Daniel Winkler, Matthias Leitner, Andrea Auer, Julia Kunze‐Liebhäuser, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c02700")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390659412"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390659412"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390659412"))][Get cited by]]

OpenAlex: https://openalex.org/W4390659412
    
Daniel Winkler, Matthias Leitner, Andrea Auer, Julia Kunze‐Liebhäuser, ACS Catalysis. https://doi.org/10.1021/acscatal.3c02700
    
The electrochemical reduction of CO2 is an important electrolysis reaction that enables the conversion of a waste gas to fuels or value-added chemicals. To make this reaction viable, a profound understanding of central intermediate steps, such as the CO electroreduction, is required. On Cu, the CO reduction reaction (CORR) is intimately linked to the hydrogen evolution reaction (HER) that proceeds via the reduction of water in alkaline or neutral electrolytes. Here, we demonstrate that the interaction of water or more specifically the water reduction kinetics on differently smooth Cu(100) and Cu(111) surfaces during the CORR in alkaline media significantly governs the CORR. On Cu(111), faster HER kinetics and the highest CORR activity are observed, even though HER and CORR onsets are more negative. While on Cu(100) small Cu ad-island clusters form in the cathodic potential range only when CO is present, structural changes appear on a larger length scale on Cu(111) both under CORR conditions and when no CO is present. These differences in the reconstruction characteristics may be attributed to the dominance of either the CORR and its intermediates or the HER on the different Cu surfaces. Therefore, the interfacial water reactivity is considered an essential activity descriptor for the CORR on Cu in alkaline media.    

    

** Surface States Governing the Activity and Selectivity of Pt-Based Ammonia Slip Catalysts for Selective Ammonia Oxidation   
:PROPERTIES:
:ID: https://openalex.org/W4390659955
:DOI: https://doi.org/10.1021/acscatal.3c05019
:AUTHORS: Vasyl Marchuk, Dmitry I. Sharapa, Jan‐Dierk Grunwaldt, Dmitry E. Doronkin
:HOST: ACS Catalysis
:END:

Vasyl Marchuk, Dmitry I. Sharapa, Jan‐Dierk Grunwaldt, Dmitry E. Doronkin, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390659955"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390659955"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390659955"))][Get cited by]]

OpenAlex: https://openalex.org/W4390659955
    
Vasyl Marchuk, Dmitry I. Sharapa, Jan‐Dierk Grunwaldt, Dmitry E. Doronkin, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05019
    
Selective oxidation of ammonia to nitrogen over Pt/Al2O3 was studied in order to determine active Pt species for the activity and selectivity of Pt under conditions close to those of realistic emission control applications. For this purpose, reaction rates and apparent activation energies were measured at different compositions of the reaction feed. Additionally, in situ diffuse reflectance infrared Fourier transform spectroscopy (DRIFTS) and operando X-ray absorption spectroscopy (XAS) including its interpretation based on theoretical XAS calculations were applied. Three main chemically different states of Pt were detected. The predominance of each of them correlated with the different performance of the catalyst at distinct temperature ranges. At low temperatures (<150 °C), the Pt surface was covered by oxygen species, which poisoned the catalyst. They needed to be removed by heating in the reaction mixture to start with a light off. At 150–300 °C, Pt was covered with NHx species, which provided the maximal selectivity to N2. At higher temperatures, when full ammonia conversion was reached, the Pt surface again became available for oxidation by the O species, resulting in both surface chemisorbed and subsurface O. This high-temperature state possessed high oxidation activity and high selectivity to undesired N2O and NOx.    

    

** Oxygen Vacancy Enhanced Proton Transfer to Boost Carbamate Decomposition Kinetics with Tunable Heterostructure Ni/NiO   
:PROPERTIES:
:ID: https://openalex.org/W4390661630
:DOI: https://doi.org/10.1021/acscatal.3c03852
:AUTHORS: Xing Li, Lei Xing, Guo‐Dong Zhan, Zhoulan Huang, Zhen Chen, Huazhen Chang, Junhua Li
:HOST: ACS Catalysis
:END:

Xing Li, Lei Xing, Guo‐Dong Zhan, Zhoulan Huang, Zhen Chen, Huazhen Chang, Junhua Li, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03852")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390661630"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390661630"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390661630"))][Get cited by]]

OpenAlex: https://openalex.org/W4390661630
    
Xing Li, Lei Xing, Guo‐Dong Zhan, Zhoulan Huang, Zhen Chen, Huazhen Chang, Junhua Li, ACS Catalysis. https://doi.org/10.1021/acscatal.3c03852
    
Catalytic carbamate decomposition is a feasible option for reducing the heat duty of amine solvent regeneration during the chemisorption of CO2 capture; advanced material with excellent proton transfer and exchange performance is crucial to boost the decomposition kinetics in an alkaline environment. Here, we prepared magnetic heterostructure Ni/NiO nanocatalysts with tunable Ni(0) nanoparticles and NiO support. The heterointerface of the proposed materials creates abundant surface oxygen vacancies (OVs) and offers abundant reactive active sites ascribed to the special electron transfer scheme of Ni0–NiO. The generated surface hydroxyls and unsaturated coordinated Ni, respectively, provide transferable protons and electrons, involved in the deprotonation of RNH3+ and C–N break of RNHCOO–. Thus, the obtained nanomaterials achieved considerably improved CO2 desorption of up to 3 mmol/min for a CO2-saturated monoethanolamine solvent, representing a substantial (approximately 50%) increase over the catalyst-free case. The reinforcement mechanism of OV generation by the Ni/NiO heterostructure and the induced proton transfer were revealed through in situ spectroscopic measurement and theoretical calculations. The results verified that the OVs stimulate the production of surface hydroxyls and water-assisted proton hopping, providing an advantageous condition for carbamate decomposition.    

    

** Design of High-Efficiency Hydrogen Evolution Catalysts in a Chiral Crystal   
:PROPERTIES:
:ID: https://openalex.org/W4390663619
:DOI: https://doi.org/10.1021/acscatal.3c03086
:AUTHORS: Jiasui Zhan, Yuliang Cao, Junwen Lai, Jiangxu Li, Hui Ma, Song Li, Peitao Liu, Xing‐Qiu Chen, Yan Sun
:HOST: ACS Catalysis
:END:

Jiasui Zhan, Yuliang Cao, Junwen Lai, Jiangxu Li, Hui Ma, Song Li, Peitao Liu, Xing‐Qiu Chen, Yan Sun, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03086")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390663619"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390663619"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390663619"))][Get cited by]]

OpenAlex: https://openalex.org/W4390663619
    
Jiasui Zhan, Yuliang Cao, Junwen Lai, Jiangxu Li, Hui Ma, Song Li, Peitao Liu, Xing‐Qiu Chen, Yan Sun, ACS Catalysis. https://doi.org/10.1021/acscatal.3c03086
    
The design of highly efficient hydrogen evolution reaction (HER) catalysts is one of the most important tasks for electrochemical water splitting in the field of renewable energy resources. In this work, via an effective combination of topologically trivial electronic intensity and the topologically nontrivial energy window, we predicted high catalytic performance in chiral material SiTc, with a close-to-zero hydrogen adsorption Gibbs free energy (−0.062 eV). With both a large intrinsic projected Berry phase and close-to-zero Gibbs free energy, SiTc provides a promising candidate for the HER catalysis reaction. In addition, this work offers an effective strategy for designing more potentially high activity topological electrocatalysts via the combination of topological states and high electronic intensity in metals.    

    

** Catalytic Stereoselective 1,2-<i>cis</i>-Furanosylations Enabled by Enynal-Derived Copper Carbenes   
:PROPERTIES:
:ID: https://openalex.org/W4390670725
:DOI: https://doi.org/10.1021/acscatal.3c05237
:AUTHORS: B. N. Ghosh, Adam Alber, Chance Lander, Yihan Shao, Kenneth M. Nicholas, Indrajeet Sharma
:HOST: ACS Catalysis
:END:

B. N. Ghosh, Adam Alber, Chance Lander, Yihan Shao, Kenneth M. Nicholas, Indrajeet Sharma, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05237")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390670725"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390670725"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390670725"))][Get cited by]]

OpenAlex: https://openalex.org/W4390670725
    
B. N. Ghosh, Adam Alber, Chance Lander, Yihan Shao, Kenneth M. Nicholas, Indrajeet Sharma, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05237
    
1,2-cis-Furanosides are present in various biomedically relevant glycosides, and their stereoselective synthesis remains a significant challenge. In this vein, we have developed a stereoselective approach to 1,2-cis-furanosylations using earth-abundant copper catalysis. This protocol proceeds under mild conditions at room temperature and employs readily accessible benchtop stable enynal-derived furanose donors. This chemistry accommodates a variety of alcohols, including primary, secondary, and tertiary, as well as mannosyl alcohol acceptors, which have been incompatible with most known methods of furanosylation. The resulting 1,2-cis-furanoside products exhibit high yields and anomeric selectivity with both the ribose and arabinose series. Furthermore, the anomeric selectivity is independent of the C2 oxygen-protecting group and the anomeric configuration of the starting donor. Experimental evidence and computational studies support our hypothesis that copper chelation between the C2 oxygen of the furanose donor and an incoming alcohol nucleophile is responsible for the observed 1,2-cis-stereoselectivity.    

    

** Exploiting Multimetallic Cooperativity in the Ring-Opening Polymerization of Cyclic Esters and Ethers   
:PROPERTIES:
:ID: https://openalex.org/W4390673532
:DOI: https://doi.org/10.1021/acscatal.3c05103
:AUTHORS: Utku Yolsal, Peter J. Shaw, Phoebe A. Lowy, Raju Chambenahalli, Jennifer A. Garden
:HOST: ACS Catalysis
:END:

Utku Yolsal, Peter J. Shaw, Phoebe A. Lowy, Raju Chambenahalli, Jennifer A. Garden, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05103")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390673532"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390673532"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390673532"))][Get cited by]]

OpenAlex: https://openalex.org/W4390673532
    
Utku Yolsal, Peter J. Shaw, Phoebe A. Lowy, Raju Chambenahalli, Jennifer A. Garden, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05103
    
The use of multimetallic complexes is a rapidly advancing route to enhance catalyst performance in the ring-opening polymerization of cyclic esters and ethers. Multimetallic catalysts often outperform their monometallic analogues in terms of reactivity and/or polymerization control, and these improvements are typically attributed to “multimetallic cooperativity”. Yet the origins of multimetallic cooperativity often remain unclear. This review explores the key factors underpinning multimetallic cooperativity, including metal–metal distances, the flexibility, electronics and conformation of the ligand framework, and the coordination environment of the metal centers. Emerging trends are discussed to provide insights into why cooperativity occurs and how to harness cooperativity for the development of highly efficient multimetallic catalysts.    

    

** Functional Characterization and Protein Engineering of a Glycosyltransferase GcCGT to Produce Flavone 6,8-Di-<i>C</i>- and 6-<i>C</i>-4′-<i>O</i>-Glycosides   
:PROPERTIES:
:ID: https://openalex.org/W4390674506
:DOI: https://doi.org/10.1021/acscatal.3c05252
:AUTHORS: Yang-Oujie Bao, Meng Zhang, Haoran Li, Zilong Wang, Jiajing Zhou, Yi Yang, Fudong Li, Lei Ye, Hongye Li, Hongwei Jin, Chao He, Min Ye
:HOST: ACS Catalysis
:END:

Yang-Oujie Bao, Meng Zhang, Haoran Li, Zilong Wang, Jiajing Zhou, Yi Yang, Fudong Li, Lei Ye, Hongye Li, Hongwei Jin, Chao He, Min Ye, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05252")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390674506"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390674506"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390674506"))][Get cited by]]

OpenAlex: https://openalex.org/W4390674506
    
Yang-Oujie Bao, Meng Zhang, Haoran Li, Zilong Wang, Jiajing Zhou, Yi Yang, Fudong Li, Lei Ye, Hongye Li, Hongwei Jin, Chao He, Min Ye, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05252
    
Herein, we discovered an efficient flavone 6-C-glycosyltransferase GcCGT from the medicinal plant Gentiana crassicaulis. GcCGT could catalyze consecutive two-step 6-C/4′-O-glycosylation of flavonoids. Homology modeling and site-directed mutagenesis yielded mutant F387K, which could catalyze the unprecedented 6-C-glycosylation of flavone 8-C-glycosides to produce 6,8-di-C-glycosides. To elucidate the catalytic mechanisms, the crystal structures of GcCGT-apo (2.10 Å) and GcCGT/UDP (2.40 Å) were resolved. Structural analysis and molecular dynamics simulations indicated that the lack of π–π stacking interaction for F387 changed the protein conformation and expanded the entrance of the substrate binding pocket. This work provided an efficient method to synthesize flavone 6,8-di-C- and 6-C-4′-O-glycosides.    

    

** Direct Oxidation of Methanol to Polyoxymethylene Dimethyl Ethers over FeMo@HZSM-5 Core–Shell Catalyst   
:PROPERTIES:
:ID: https://openalex.org/W4390675373
:DOI: https://doi.org/10.1021/acscatal.3c04941
:AUTHORS: Xiaqing Wang, Xiujuan Gao, Faen Song, Xiaoxing Wang, Guozhong Cao, Junfeng Zhang, Yizhuo Han, Qingde Zhang
:HOST: ACS Catalysis
:END:

Xiaqing Wang, Xiujuan Gao, Faen Song, Xiaoxing Wang, Guozhong Cao, Junfeng Zhang, Yizhuo Han, Qingde Zhang, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04941")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390675373"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390675373"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390675373"))][Get cited by]]

OpenAlex: https://openalex.org/W4390675373
    
Xiaqing Wang, Xiujuan Gao, Faen Song, Xiaoxing Wang, Guozhong Cao, Junfeng Zhang, Yizhuo Han, Qingde Zhang, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04941
    
Direct oxidation of methanol to polyoxymethylene dimethyl ethers (PODEn) with longer C–O chains faces a challenge due to difficult matching of active sites. Herein, a core–shell catalyst composed of an iron molybdenum core and a zeolite shell has been designed, successfully realizing methanol oxidation to PODEn. The PODE2–6 selectivity reaches 41.0% at 85.6% methanol conversion over the FeMo@HZSM-5 catalyst. Combined with the designed experiments and characterizations, the special core–shell structure and the synergy between acid sites with different strengths and redox sites are the pivotal factors for promoting the chain growth of the C–O bond.    

    

** Dual and Triple Atom Electrocatalysts for Energy Conversion (CO<sub>2</sub>RR, NRR, ORR, OER, and HER): Synthesis, Characterization, and Activity Evaluation   
:PROPERTIES:
:ID: https://openalex.org/W4390685826
:DOI: https://doi.org/10.1021/acscatal.3c05000
:AUTHORS: Adam M. Roth-Zawadzki, Alexander J. Nielsen, Rikke Plougmann, Jakob Kibsgaard
:HOST: ACS Catalysis
:END:

Adam M. Roth-Zawadzki, Alexander J. Nielsen, Rikke Plougmann, Jakob Kibsgaard, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05000")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390685826"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390685826"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390685826"))][Get cited by]]

OpenAlex: https://openalex.org/W4390685826
    
Adam M. Roth-Zawadzki, Alexander J. Nielsen, Rikke Plougmann, Jakob Kibsgaard, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05000
    
Dual and triple atom catalysts (DACs and TACs) are an emerging field of heterogeneous catalysis research. They share properties with single atom catalysts (SACs), such as maximizing dispersion of metals and the ability to circumvent the traditional scaling relations that limit extended surfaces. DACs and TACs additionally provide adjacent sites that are necessary for certain reaction mechanisms and add to the tunability of the electronic structure and binding energies. DACs and TACs are, however, inherently difficult to selectively synthesize and characterize. Characterization and activity evaluation are prone to misinterpretation, adding confusion to the already complex field. In this review, we investigate the current progress of DACs for important electrochemical reactions in energy conversion and storage. We further discuss current and future synthesis methods for DACs and TACs and focus on common pitfalls in characterization and activity evaluation.    

    

** Elucidating the Mechanism for Oxidative Coupling of Methane Catalyzed by La<sub>2</sub>O<sub>3</sub>: Experimental and Microkinetic Modeling Studies   
:PROPERTIES:
:ID: https://openalex.org/W4390694581
:DOI: https://doi.org/10.1021/acscatal.3c04714
:AUTHORS: Zaili Xiong, Jijun Guo, Yuwen Deng, Bingzhi Liu, Hao Lou, Meirong Zeng, Zhandong Wang, Zhongyue Zhou, Wenhao Yuan, Fei Qi
:HOST: ACS Catalysis
:END:

Zaili Xiong, Jijun Guo, Yuwen Deng, Bingzhi Liu, Hao Lou, Meirong Zeng, Zhandong Wang, Zhongyue Zhou, Wenhao Yuan, Fei Qi, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04714")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390694581"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390694581"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390694581"))][Get cited by]]

OpenAlex: https://openalex.org/W4390694581
    
Zaili Xiong, Jijun Guo, Yuwen Deng, Bingzhi Liu, Hao Lou, Meirong Zeng, Zhandong Wang, Zhongyue Zhou, Wenhao Yuan, Fei Qi, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04714
    
Oxidative coupling of methane (OCM) has been widely proposed to be one of the most promising methods for the direct conversion of methane to C2 products, such as ethane and ethene. Highly active free radicals play a crucial role, while accurate identifications are limited. To probe these free radicals and reveal their reactions, experiments focused on the OCM catalyzed by La2O3 were designed to be carried out in a packed bed reactor at low-pressure conditions over a wide temperature range. Dozens of species, including methyl radical, ethyl radical, and formaldehyde, were observed by using synchrotron vacuum ultraviolet photoionization mass spectrometry (SVUV-PIMS). A microkinetic model that coupled a detailed gas-phase and surface mechanism was developed and validated against the experimental results, especially to reveal the crucial roles of free radicals in the formation of C2 products as well as the oxygenated intermediates. The prediction results of the kinetic model agreed well with the experimental measurements. Rate of production and sensitivity analysis were performed to reveal the complex reaction network and key reactions of the OCM. Methyl was confirmed to play a key role based on both experimental and modeling perspectives, while ethyl is crucial in the transformation of C2 species and the formation of C3–C4 species. This indicates that the selective regulation of free radicals such as methyl and ethyl in OCM is worth paying attention to. The present work provides more detailed chemistry of OCM reactions, which would be helpful to improve product selectivity of OCM.    

    

** Electrochemical Monitoring of Heterogeneous Peroxygenase Reactions Unravels LPMO Kinetics   
:PROPERTIES:
:ID: https://openalex.org/W4390697114
:DOI: https://doi.org/10.1021/acscatal.3c05194
:AUTHORS: Lorenz Schwaiger, Florian Csarman, Hui S. Chang, Ole Golten, Vincent G. H. Eijsink, Roland Ludwig
:HOST: ACS Catalysis
:END:

Lorenz Schwaiger, Florian Csarman, Hui S. Chang, Ole Golten, Vincent G. H. Eijsink, Roland Ludwig, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05194")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390697114"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390697114"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390697114"))][Get cited by]]

OpenAlex: https://openalex.org/W4390697114
    
Lorenz Schwaiger, Florian Csarman, Hui S. Chang, Ole Golten, Vincent G. H. Eijsink, Roland Ludwig, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05194
    
Biological conversion of plant biomass depends on peroxygenases and peroxidases acting on insoluble polysaccharides and lignin. Among these are cellulose- and hemicellulose-degrading lytic polysaccharide monooxygenases (LPMOs), which have revolutionized our concept of biomass degradation. Major obstacles limiting mechanistic and functional understanding of these unique peroxygenases are their complex and insoluble substrates and the hard-to-measure H2O2 consumption, resulting in the lack of suitable kinetic assays. We report a versatile and robust electrochemical method for real-time monitoring and kinetic characterization of LPMOs and other H2O2-dependent interfacial enzymes based on a rotating disc electrode for the sensitive and selective quantitation of H2O2 at biologically relevant concentrations. The H2O2 sensor works in suspensions of insoluble substrates as well as in homogeneous solutions. Our characterization of multiple LPMOs provides unprecedented insights into the substrate specificity, kinetics, and stability of these enzymes. High turnover and total turnover numbers demonstrate that LPMOs are fast and durable biocatalysts.    

    

** Correction to “Brønsted Acid Strength Does Not Change for Bulk and External Sites of MFI Except for Al Substitution Where Silanol Groups Form”   
:PROPERTIES:
:ID: https://openalex.org/W4390701188
:DOI: https://doi.org/10.1021/acscatal.3c06041
:AUTHORS: Haliey Balcom, Alexander J. Hoffman, Huston Locht, David Hibbitts
:HOST: ACS Catalysis
:END:

Haliey Balcom, Alexander J. Hoffman, Huston Locht, David Hibbitts, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06041")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390701188"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390701188"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390701188"))][Get cited by]]

OpenAlex: https://openalex.org/W4390701188
    
Haliey Balcom, Alexander J. Hoffman, Huston Locht, David Hibbitts, ACS Catalysis. https://doi.org/10.1021/acscatal.3c06041
    
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVCorrectionNEXTORIGINAL ARTICLEThis notice is a correctionCorrection to “Brønsted Acid Strength Does Not Change for Bulk and External Sites of MFI Except for Al Substitution Where Silanol Groups Form”Haliey BalcomHaliey BalcomMore by Haliey Balcom, Alexander J. HoffmanAlexander J. HoffmanMore by Alexander J. Hoffmanhttps://orcid.org/0000-0002-1337-9297, Huston LochtHuston LochtMore by Huston Lochthttps://orcid.org/0009-0004-9654-0884, and David Hibbitts*David HibbittsMore by David Hibbittshttps://orcid.org/0000-0001-8606-7000Cite this: ACS Catal. 2024, 14, XXX, 1231Publication Date (Web):January 9, 2024Publication History Received12 December 2023Published online9 January 2024https://doi.org/10.1021/acscatal.3c06041© 2024 American Chemical SocietyRequest reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InReddit PDF (670 KB) Get e-AlertscloseSUBJECTS:Adsorption,Brønsted acid,Energy,Materials,Zeolites Get e-Alerts    

    

** Rational Design of Alloy Catalysts for Alkyne Semihydrogenation via Descriptor-Based High-Throughput Screening   
:PROPERTIES:
:ID: https://openalex.org/W4390701504
:DOI: https://doi.org/10.1021/acscatal.3c02398
:AUTHORS: Jiayi Wang, Haoxiang Xu, Jian Wu, Fengyu Zhang, Chi‐Ming Che, Jing Zhu, Junting Feng, Daojian Cheng
:HOST: ACS Catalysis
:END:

Jiayi Wang, Haoxiang Xu, Jian Wu, Fengyu Zhang, Chi‐Ming Che, Jing Zhu, Junting Feng, Daojian Cheng, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c02398")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390701504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390701504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390701504"))][Get cited by]]

OpenAlex: https://openalex.org/W4390701504
    
Jiayi Wang, Haoxiang Xu, Jian Wu, Fengyu Zhang, Chi‐Ming Che, Jing Zhu, Junting Feng, Daojian Cheng, ACS Catalysis. https://doi.org/10.1021/acscatal.3c02398
    
Although alloying is a common approach to developing catalysts for alkyne selective hydrogenation, the geometric and electronic effects of active sites on the kinetics of alkyne selective hydrogenation are still ambiguous, hindering rational design of alloy catalysts. Herein, we construct structural descriptors to categorize and reorganize the roles of electronic and geometric factors in the kinetics of acetylene semihydrogenation. The prediction model based on our proposed structural descriptors successfully elucidates the activity and selectivity trends among Pd-based alloys and can also be extended to rationalize the kinetics trend among single-atom alloys and Ni-based alloys for semihydrogenation of acetylene and even other alkynes, in good agreement with available experimental references. Aided by thermodynamic stability analysis and structural descriptors, 489 Pd-based bimetallic alloys via a high-throughput screening protocol were evaluated, and finally, Pd1Nb3 and Pd1Hf3 were identified with a high yield of ethylene and inexpensive cost and validated by our experimental studies.    

    

** Visible-Light Photocatalyzed C3–H Alkylation of 2<i>H</i>-Indazoles/Indoles with Sulfoxonium Ylides via Diversified Mechanistic Pathways   
:PROPERTIES:
:ID: https://openalex.org/W4390701516
:DOI: https://doi.org/10.1021/acscatal.3c04729
:AUTHORS: Altman Yuzhu Peng, Yujing Wang, Kaifeng Wang, Qi Sun, Xiaoguang Bao
:HOST: ACS Catalysis
:END:

Altman Yuzhu Peng, Yujing Wang, Kaifeng Wang, Qi Sun, Xiaoguang Bao, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04729")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390701516"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390701516"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390701516"))][Get cited by]]

OpenAlex: https://openalex.org/W4390701516
    
Altman Yuzhu Peng, Yujing Wang, Kaifeng Wang, Qi Sun, Xiaoguang Bao, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04729
    
Herein, the C3–H alkylation of 2H-indazoles and indoles with sulfoxonium ylides is developed under visible-light photocatalysis. This protocol employs easily accessible reagents, and a wide range of 2H-indazoles, indoles, and sulfoxonium ylides are suitable for this reaction to afford the desired products under benign conditions. Synergistic experimental and computational studies suggest that the sulfoxonium ylides involving C3–H alkylation of 2H-indazoles and indoles under visible-light photocatalysis could proceed via different mechanistic pathways. For the C3-alkylation of 2H-indazoles, a triplet energy transfer mechanistic pathway of 2H-indazoles is proposed for quenching the excited photocatalyst. Subsequently, the formed excited triplet state of 2H-indazoles could undergo radical attack on the C═S moiety of sulfoxonium ylides. After the dissociation of DMSO and 1,2-H migration, the final product of C3-alkylation of 2H-indazoles could be yielded. However, such a mechanistic pathway is not applicable for indoles. Instead, sulfoxonium ylides could be converted to a C-centered radical in the presence of KH2PO4 under visible-light photoredox conditions. The formed C-centered radical can attack the C3-site of indoles and thus lead to the C3-alkylation product of indoles.    

    

** How Does Structural Disorder Impact Heterogeneous Catalysts? The Case of Ammonia Decomposition on Non-stoichiometric Lithium Imide   
:PROPERTIES:
:ID: https://openalex.org/W4390703617
:DOI: https://doi.org/10.1021/acscatal.3c05376
:AUTHORS: Francesco Mambretti, Umberto Raucci, Manyi Yang, Michele Parrinello
:HOST: ACS Catalysis
:END:

Francesco Mambretti, Umberto Raucci, Manyi Yang, Michele Parrinello, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05376")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390703617"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390703617"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390703617"))][Get cited by]]

OpenAlex: https://openalex.org/W4390703617
    
Francesco Mambretti, Umberto Raucci, Manyi Yang, Michele Parrinello, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05376
    
Among the many catalysts suggested for ammonia decomposition, Li2NH has been shown to be quite promising. In the recent past, we have performed extensive ab initio-quality simulations to explain the workings of this unusual catalyst. In the complex scenario that has emerged, surface dynamics and structural disorder enhanced by the interaction with the reacting ammonia molecules have played crucial roles. Non-stoichiometric lithium imide (Li2–x(NH2)x(NH)1–x) has been reported to have better catalytic performances than pure lithium imide. Stimulated by these findings, we follow up our previous study simulating the ammonia decomposition on such non-stoichiometric compounds. We attribute the enhanced reactivity to the fact that the compositional disorder further enhances the fluctuations in the topmost layers of the catalyst, strengthening our dynamic picture of this catalytic process.    

    

** Screening Cu-Zeolites for Methane Activation Using Curriculum-Based Training   
:PROPERTIES:
:ID: https://openalex.org/W4390703624
:DOI: https://doi.org/10.1021/acscatal.3c05275
:AUTHORS: Jiawei Guo, Tyler Sours, Sam Holton, Chenghan Sun, Ambarish Kulkarni
:HOST: ACS Catalysis
:END:

Jiawei Guo, Tyler Sours, Sam Holton, Chenghan Sun, Ambarish Kulkarni, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05275")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390703624"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390703624"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390703624"))][Get cited by]]

OpenAlex: https://openalex.org/W4390703624
    
Jiawei Guo, Tyler Sours, Sam Holton, Chenghan Sun, Ambarish Kulkarni, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05275
    
Machine learning (ML), when used synergistically with atomistic simulations, has recently emerged as a powerful tool for accelerated catalyst discovery. However, the application of these techniques has been limited by the lack of interpretable and transferable ML models. In this work, we propose a curriculum-based training (CBT) philosophy to systematically develop reactive machine learning potentials (rMLPs) for high-throughput screening of zeolite catalysts. Our CBT approach combines several different types of calculations to gradually teach the ML model about the relevant regions of the reactive potential energy surface. The resulting rMLPs are accurate, transferable, and interpretable. We further demonstrate the effectiveness of this approach by exhaustively screening thousands of [CuOCu]2+ sites across hundreds of Cu-zeolites for the industrially relevant methane activation reaction. Specifically, this large-scale analysis of the entire International Zeolite Association (IZA) database identifies a set of previously unexplored zeolites (i.e., MEI, ATN, EWO, and CAS) that show the highest ensemble-averaged rates for [CuOCu]2+-catalyzed methane activation. We believe that this CBT philosophy can be generally applied to other zeolite-catalyzed reactions and, subsequently, to other types of heterogeneous catalysts. Thus, this represents an important step toward overcoming the long-standing barriers within the computational heterogeneous catalysis community.    

    

** Deciphering the Unconventional Reduction of C═N Bonds by Old Yellow Enzymes Using QM/MM   
:PROPERTIES:
:ID: https://openalex.org/W4390704303
:DOI: https://doi.org/10.1021/acscatal.3c04362
:AUTHORS: Amit Singh, Nakia Polidori, Wolfgang Kroutil, Karl Gruber
:HOST: ACS Catalysis
:END:

Amit Singh, Nakia Polidori, Wolfgang Kroutil, Karl Gruber, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04362")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390704303"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390704303"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390704303"))][Get cited by]]

OpenAlex: https://openalex.org/W4390704303
    
Amit Singh, Nakia Polidori, Wolfgang Kroutil, Karl Gruber, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04362
    
The reduction of C═X (X = N, O) bonds is a cornerstone in both synthetic organic chemistry and biocatalysis. Conventional reduction mechanisms usually involve a hydride ion targeting the less electronegative carbon atom. In a departure from this paradigm, our investigation into Old Yellow Enzymes (OYEs) reveals a mechanism involving transfer of hydride to the formally more electronegative nitrogen atom within a C═N bond. Beyond their known ability to reduce electronically activated C═C double bonds, e.g., in α, β-unsaturated ketones, these enzymes have recently been shown to reduce α-oximo-β-ketoesters to the corresponding amines. It has been proposed that this transformation involves two successive reduction steps and proceeds via imine intermediates formed by the reductive dehydration of the oxime moieties. We employ advanced quantum mechanics/molecular mechanics (QM/MM) simulations, enriched by a two-tiered approach incorporating QM/MM (UB3LYP-6-31G*/OPLS2005) geometry optimization, QM/MM (B3LYP-6-31G*/amberff19sb) steered molecular dynamics simulations, and detailed natural-bond-orbital analyses to decipher the unconventional hydride transfer to nitrogen in both reduction steps and to delineate the role of active site residues as well as of substituents present in the substrates. Our computational results confirm the proposed mechanism and agree well with experimental mutagenesis and enzyme kinetics data. According to our model, the catalysis of OYE involves hydride transfer from the flavin cofactor to the nitrogen atom in oximoketoesters as well as iminoketoesters followed by protonation at the adjacent oxygen or carbon atoms by conserved tyrosine residues and active site water molecules. Two histidine residues play a key role in the polarization and activation of the C═N bond, and conformational changes of the substrate observed along the reaction coordinate underline the crucial importance of dynamic electron delocalization for efficient catalysis.    

    

** Highly Active MnCoO<sub><i>x</i></sub> Catalyst toward CO Preferential Oxidation   
:PROPERTIES:
:ID: https://openalex.org/W4390704389
:DOI: https://doi.org/10.1021/acscatal.3c04654
:AUTHORS: Jun Yu, Yusen Yang, Meng Zhang, Boyu Song, Yu Han, Si Wang, Zhihao Ren, Lei Wang, Ping Yin, Lirong Zheng, Xin Zhang, Min Wei
:HOST: ACS Catalysis
:END:

Jun Yu, Yusen Yang, Meng Zhang, Boyu Song, Yu Han, Si Wang, Zhihao Ren, Lei Wang, Ping Yin, Lirong Zheng, Xin Zhang, Min Wei, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04654")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390704389"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390704389"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390704389"))][Get cited by]]

OpenAlex: https://openalex.org/W4390704389
    
Jun Yu, Yusen Yang, Meng Zhang, Boyu Song, Yu Han, Si Wang, Zhihao Ren, Lei Wang, Ping Yin, Lirong Zheng, Xin Zhang, Min Wei, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04654
    
Preferential oxidation of CO (CO-PROX) is an efficient method to eliminate residual CO in the feed stream to avoid Pt poisoning in proton-exchange-membrane fuel cells (PEMFCs), in which the development of high-performance, low-cost catalysts remains a big challenge. Herein, we report highly active spinel-like MnCoOx catalysts derived from layered double hydroxide (LDH) precursors, which are featured with abundant octahedron-distorted lattice oxygen. Impressively, the optimal catalyst MnCoOx-300 achieves the selective and complete removal of CO from a H2-rich stream at 80 °C, within a wide operation temperature window (80–200 °C, matching well with PEMFCs) at a rather high space velocity (80,000 h–1). This performance, to the best of our knowledge, outperforms previously reported non-noble metal catalysts and even exceeds the state-of-the-art CuO/CeO2 system in the CO-PROX technology. A comprehensive investigation based on in situ Raman, in situ XAFS, in situ TPD-Mass, and in situ DRIFTS reveals that the Cooct3+–O2––Mnoct4+ structure in MnCoOx-300 serves as the intrinsic active site that facilitates preferential oxidation: the lattice oxygen participates in the oxidation of CO to produce CO2 and oxygen vacancy (Ov), followed by the replenishment of oxygen species from aerial oxygen (the rate-determining step) to regenerate Cooct3+–O2––Mnoct4+. Isotopic 18O kinetic studies and in situ DRIFTS substantiate that the reaction temperature plays a crucial role in the competitive oxidation of CO vs H2 at the same active site. This work provides a successful paradigm for the design and preparation of transition metal oxide catalysts toward the CO-PROX reaction, which shows potential applications in hydrogen purification for PEMFCs.    

    

** Iron-Carbene Initiated O–H Insertion/Aldol Cascade for the Stereoselective Synthesis of Functionalized Tetrahydrofurans   
:PROPERTIES:
:ID: https://openalex.org/W4390718518
:DOI: https://doi.org/10.1021/acscatal.3c05040
:AUTHORS: Prakash Kafle, B. N. Ghosh, Arianne C. Hunter, Rishav Mukherjee, Kenneth M. Nicholas, Indrajeet Sharma
:HOST: ACS Catalysis
:END:

Prakash Kafle, B. N. Ghosh, Arianne C. Hunter, Rishav Mukherjee, Kenneth M. Nicholas, Indrajeet Sharma, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05040")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390718518"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390718518"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390718518"))][Get cited by]]

OpenAlex: https://openalex.org/W4390718518
    
Prakash Kafle, B. N. Ghosh, Arianne C. Hunter, Rishav Mukherjee, Kenneth M. Nicholas, Indrajeet Sharma, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05040
    
Given its earth abundance, cost-effectiveness, and ecofriendly qualities, iron serves as a promising alternative to precious metals in catalysis. This article presents an iron carbene-initiated cascade approach for synthesizing highly substituted tetrahydrofurans at the gram scale. This cascade reaction utilizes readily accessible β-hydroxyketones and diazo compounds and works with iron catalyst loading as low as 5 mol %. This reaction proceeds through an O–H insertion into diazo-derived iron carbenes, followed by an intramolecular aldol reaction to access functionalized tetrahydrofurans in high yields and diastereoselectivity. The versatile nature of this domino sequence accommodates diverse β-hydroxyketones and diazo compounds, streamlining access to synthetically challenging spiroethers. Furthermore, this cascade process offers a route to enantiopure tetrahydrofurans by utilizing a diazo ester bearing a chiral auxiliary, 8-phenylmenthol. Postmodifications of the tetrahydrofuran product provide access to various analogues, including a medicinally relevant oxetane motif. Density functional theory (DFT) calculations substantiate a stereospecific mechanism wherein the intramolecular aldol reaction proceeds via a fused six- and five-membered iron–oxygen transition-state complex, yielding the contrathermodynamic cis-aldol product.    

    

** Enantioselective Synthesis of “NO<sub>2</sub>···NH” Hydrogen Bond-Stabilized C–N Axially Chiral Diarylamines   
:PROPERTIES:
:ID: https://openalex.org/W4390724252
:DOI: https://doi.org/10.1021/acscatal.3c04775
:AUTHORS: Wei Lin, Yuanhu Shao, Zeyang Hao, Zhe Huang, Zhiyuan Ren, Li Chen, Xin Li
:HOST: ACS Catalysis
:END:

Wei Lin, Yuanhu Shao, Zeyang Hao, Zhe Huang, Zhiyuan Ren, Li Chen, Xin Li, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04775")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390724252"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390724252"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390724252"))][Get cited by]]

OpenAlex: https://openalex.org/W4390724252
    
Wei Lin, Yuanhu Shao, Zeyang Hao, Zhe Huang, Zhiyuan Ren, Li Chen, Xin Li, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04775
    
Herein, N-nucleophilic tandem oxidation–N-arylation–oxidation reaction and C-nucleophilic bromination reaction of substituted anilines have been developed using chiral phosphoric acid catalysis, enabling access to axially chiral diarylamines. The key feature of this strategy is that the “NO2···H–N” hydrogen bond was successfully introduced into acyclic diaryl secondary amines, which contain two potential contiguous atropisomeric C–N axes, to stabilize one of the planar axial conformations. This methodology provided a series of optically pure diarylamine atropisomers containing this new hydrogen bond type in good yields (up to 99%) and high enantiomeric ratios (up to 99.5:0.5 e.r.). The synthetic utility was demonstrated through large-scale reactions and transformations of the products. Plausible models were proposed to explain the enantioselectivity of the products.    

    

** Manipulating the Morphology and Electronic State of a Two-Dimensional Coordination Polymer as a Hydrogen Evolution Cocatalyst Enhances Photocatalytic Overall Water Splitting   
:PROPERTIES:
:ID: https://openalex.org/W4390728497
:DOI: https://doi.org/10.1021/acscatal.3c04389
:AUTHORS: Jingyan Guan, Kazuma Koizumi, Naoya Fukui, Hajime Suzuki, Kantaro Murayama, Ryojun Toyoda, Hiroaki Maeda, Kazuhide Kamiya, Keitaro Ohashi, Shinya Takaishi, Osamu Tomita, Akinori Saeki, Hiroshi Nishihara, Hiroshi Kageyama, Ryu Abe, Ryota Sakamoto
:HOST: ACS Catalysis
:END:

Jingyan Guan, Kazuma Koizumi, Naoya Fukui, Hajime Suzuki, Kantaro Murayama, Ryojun Toyoda, Hiroaki Maeda, Kazuhide Kamiya, Keitaro Ohashi, Shinya Takaishi, Osamu Tomita, Akinori Saeki, Hiroshi Nishihara, Hiroshi Kageyama, Ryu Abe, Ryota Sakamoto, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04389")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390728497"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390728497"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390728497"))][Get cited by]]

OpenAlex: https://openalex.org/W4390728497
    
Jingyan Guan, Kazuma Koizumi, Naoya Fukui, Hajime Suzuki, Kantaro Murayama, Ryojun Toyoda, Hiroaki Maeda, Kazuhide Kamiya, Keitaro Ohashi, Shinya Takaishi, Osamu Tomita, Akinori Saeki, Hiroshi Nishihara, Hiroshi Kageyama, Ryu Abe, Ryota Sakamoto, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04389
    
To achieve efficacious photocatalytic overall water splitting, surface modification of photocatalysts with proficient cocatalysts for hydrogen evolution reaction (HER) is imperative. NiBHT, a conductive two-dimensional coordination polymer (2D CP), or a 2D metal–organic framework (2D MOF), endowed with remarkable chemical stability and HER selectivity, emerged as a promising candidate for an HER cocatalyst. However, the bulky morphology of NiBHT hampered its performance. Here, we demonstrate a strategy to miniaturize NiBHT by incorporating the benzene-1,2-dithiol (BDT) ligand, yielding NiBHT nanoparticles (NiBHT-NP). Beyond morphology, empirical evidence unveiled alterations in the electronic state and catalytic activity of NiBHT-NP, and the ramifications of BDT modulation on intrinsic characteristics are elucidated through density functional theory (DFT) calculations. As a model system, CoOx/SrTiO3:Al photocatalyst with NiBHT-NP modification exhibited an apparent quantum efficiency (AQE) of 10.3% at 365 nm for overall water splitting. This pioneering work showcases that a modulator ligand may manipulate the morphology, electronic state, and catalytic behavior of 2D CPs, holding prodigious potential for developing more effective CP-based HER cocatalysts.    

    

** Shape Selectivity of AEL Channels for Anomalously Facilitating Biojet Fuel Production from Long-Chain <i>n</i>-Alkane Hydrocracking   
:PROPERTIES:
:ID: https://openalex.org/W4390732536
:DOI: https://doi.org/10.1021/acscatal.3c04465
:AUTHORS: Chao Mu, Junhao Sun, Chuang Xie, Jianming Bao, Xuan Guo, Haozhe Zhang, Yujun Zhao, Shengping Wang, Xinbin Ma
:HOST: ACS Catalysis
:END:

Chao Mu, Junhao Sun, Chuang Xie, Jianming Bao, Xuan Guo, Haozhe Zhang, Yujun Zhao, Shengping Wang, Xinbin Ma, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04465")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390732536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390732536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390732536"))][Get cited by]]

OpenAlex: https://openalex.org/W4390732536
    
Chao Mu, Junhao Sun, Chuang Xie, Jianming Bao, Xuan Guo, Haozhe Zhang, Yujun Zhao, Shengping Wang, Xinbin Ma, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04465
    
Hydrocracking of long-chain n-alkanes from hydrotreating of vegetable oil is critical for biojet fuel production and requires selective C–C cleavage near the long-chain alkane end. Due to preferential cracking near the carbon chain end in AEL channels, SAPO-11 optionally produces heavy jet fuel fractions in hydrocracking of the model reactant n-C16. Also, the weak acidity of SAPO-11 promotes olefin desorption and markedly reduces the second cracking of jet fuel fractions formed. Compared to 10-MR Si–Al ZSM-22, ZSM-23, ZSM-5, and ZSM-35 zeolites, SAPO-11 significantly improves the jet fuel production performance. Surprisingly,10-membered rings (10-MR) SAPO-11 exhibits higher jet fuel yields than 12-membered rings (12-MR) HUSY (FAU topology), contrary to the general belief that larger pores are more conducive to heavy cracking product production. Further, theoretical molar cracking product distributions of C15–C18 fractions are proposed, highlighting the superior performance of SAPO-11 over that of HUSY and delineating the yield limits for jet fuel production. Higher than those of commercial biojet fuels, the isomer content of jet fuel fractions exceeds 89% at cracking yield above 70%. It indicates that weakly acidic SAPO-11 has potential for specific cracking reactions near the long-chain alkane end, which enriches the understanding of selective C–C cleavage by zeolites for high-value cracking products.    

    

** Electronic and Electrochemical Control of Isostructural Ruthenium Hydricities and the Implications for Catalytic Overpotentials   
:PROPERTIES:
:ID: https://openalex.org/W4390732717
:DOI: https://doi.org/10.1021/acscatal.3c04589
:AUTHORS: Zong-Heng Wang, Brian N. DiMarco, Mehmed Z. Ertem, Renato N. Sampaio, Gerald F. Manbeck
:HOST: ACS Catalysis
:END:

Zong-Heng Wang, Brian N. DiMarco, Mehmed Z. Ertem, Renato N. Sampaio, Gerald F. Manbeck, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04589")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390732717"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390732717"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390732717"))][Get cited by]]

OpenAlex: https://openalex.org/W4390732717
    
Zong-Heng Wang, Brian N. DiMarco, Mehmed Z. Ertem, Renato N. Sampaio, Gerald F. Manbeck, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04589
    
Electronic tuning of metal hydrides enables precise control over potentials, mechanisms, selectivity, and rates of electrocatalytic reactions by regulating bond dissociation free energies such as the hydricity (ΔGH–°) and pKa of the catalyst. Here, we investigate a series of electronically tuned ruthenium hydrido complexes that are isostructural at the metal center: [Ru(4,4′-R2-bpy)2(CO)H]+ (R = CF3, Cl, H, CH3, and CH3O; bpy = 2,2′-bipyridine) (denoted as (R)Ru–H+). A substantial 22 kcal mol–1 hydricity range is available across five complexes in three stable oxidation states: (R)Ru–H+, (R)Ru–H0, and (R)Ru–H–. Thermodynamic and mechanistic predictions of electrocatalytic proton reduction were tested experimentally by reducing protons from weak acids to H2. Two mechanisms are observed, depending on the acid strength and the catalyst hydricity. The rate constants for hydride transfer and protonation of the catalyst were, in some cases, extracted from the analysis of cyclic voltammetry data. A key finding is a 400 mV decrease in the catalytic overpotential for H2 production by using a doubly reduced electron-poor metal hydride instead of a singly reduced electron-rich metal hydride. The former also exhibits a higher rate constant for hydride transfer, representing a strategy to disconnect rate and free energy relationships.    

    

** Insight into the Structure of Mn-NiS<sub>2</sub> during Urea Oxidation Using Combined In Situ X-ray Absorption Spectroscopy and Attenuated Total Reflectance Surface-Enhanced Infrared Absorption Spectroscopy   
:PROPERTIES:
:ID: https://openalex.org/W4390734560
:DOI: https://doi.org/10.1021/acscatal.3c05369
:AUTHORS: Niangao Duan, Tianxin Hou, Wei Zheng, Yafei Qu, Peichen Wang, Jun Yang, Yang Yang, Dongdong Wang, Jitang Chen, Qianwang Chen
:HOST: ACS Catalysis
:END:

Niangao Duan, Tianxin Hou, Wei Zheng, Yafei Qu, Peichen Wang, Jun Yang, Yang Yang, Dongdong Wang, Jitang Chen, Qianwang Chen, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05369")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390734560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390734560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390734560"))][Get cited by]]

OpenAlex: https://openalex.org/W4390734560
    
Niangao Duan, Tianxin Hou, Wei Zheng, Yafei Qu, Peichen Wang, Jun Yang, Yang Yang, Dongdong Wang, Jitang Chen, Qianwang Chen, ACS Catalysis. https://doi.org/10.1021/acscatal.3c05369
    
The urea electrocatalytic oxidation reaction (UOR) has enormous potential as an ideal alternative anode reaction for water splitting owing to its lower thermodynamic equilibrium potential of 0.37 V versus reversible hydrogen electrode (vs RHE). Nickel-based materials, especially NiOOH, are considered to be one of the most promising non-noble metal catalysts for UOR due to their inexpensive cost and rich abundance. However, NiOOH displays a high overpotential and poor long-term stability. Herein, our density functional theory calculations show that the rate-determining step for UOR is desorption of CO2 on NiOOH, and Mn-doped NiOOH has the lowest energy for CO2 desorption. Hence, we prepared a Mn-NiS2 precatalyst that would transform into the active form of Mn-NiOOH during the electrochemical process. The catalyst exhibits good performance for UOR, achieving 100 mA cm–2 at 1.426 V (vs RHE, without IR correction) for 200 h with no significant voltage change, which is rarely reported for nonprecious-metal UOR catalysts. X-ray absorption near-edge spectroscopy and X-ray diffraction characterization show the transformation from sulfide to oxyhydroxide when a voltage is applied, while in situ attenuated total reflectance surface-enhanced infrared absorption spectroscopy (ATR-SEIRAS) proves that Mn-NiOOH accelerates the desorption of CO2 compared to NiOOH.    

    

** Iron-Catalyzed 5-Endo-Dig Synthetic Approach to Indenes and Its Bidirectional Extension to Narrow Bandgap π-Systems   
:PROPERTIES:
:ID: https://openalex.org/W4390734752
:DOI: https://doi.org/10.1021/acscatal.3c04961
:AUTHORS: Mengqing Chen, Yuki Itabashi, Shota Fukuma, Rui Shang, Eiichi Nakamura
:HOST: ACS Catalysis
:END:

Mengqing Chen, Yuki Itabashi, Shota Fukuma, Rui Shang, Eiichi Nakamura, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390734752"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390734752"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390734752"))][Get cited by]]

OpenAlex: https://openalex.org/W4390734752
    
Mengqing Chen, Yuki Itabashi, Shota Fukuma, Rui Shang, Eiichi Nakamura, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04961
    
The indene skeleton is a key structure in a variety of compounds, with applications in medicinal and materials science. Traditional syntheses often require harsh conditions or reactive intermediates due to the temporary disruption of the aromaticity of the developing indene ring. To circumvent this problem, we have investigated iron-catalyzed 5-endo-dig cyclization for the construction of the five-membered carbocycle component of indene, which does not interrupt the benzene ring’s aromaticity. A reduced iron reactive species generated by the reduction of FeCl2 with metallic magnesium is a key reactive species that effectively cleaves the C–O bond in the starting material to generate a dormant radical-stabilized iron, which smoothly undergoes the 5-endo-dig closure of an indene ring. The synthetic conditions are so mild that we synthesized a high highest occupied molecular orbital (HOMO), narrow bandgap conjugated compound that has a HOMO level as high as −4.59 eV and an optical bandgap of 1.50 eV; hence, it is unstable even under air.    

    
