#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Wed Mar  6 00:43:34 2024

Found 3 results from 2024-02-28 to 2024-03-06
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Impact of Potential and Active-Site Environment on Single-Iron-Atom-Catalyzed Electrochemical CO2 Reduction from Accurate Quantum Many-Body Simulations  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392185788
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05999")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392185788"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392185788"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392185788"))][Get cited by]]

OpenAlex: https://openalex.org/W4392185788 (Open access: False)
    
[[https://openalex.org/A5050711213][Jincheng Lei]], [[https://openalex.org/A5038038703][Tianyu Zhu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05999 
     
Single iron atoms supported on nitrogen-doped graphene (Fe–N–C) have shown promise in catalyzing electrochemical reduction of CO2 to CO with low overpotential and high selectivity. However, the nature of its rate-limiting step and the effect of active-site environment on catalytic activity are still under debate. Previous theoretical studies exclusively rely on density functional theory (DFT), but their predictions are limited by inherent errors in DFT functionals, leading to diverging conclusions on catalytic mechanisms. Herein, we employ an efficient quantum embedding strategy to enable high-level coupled-cluster (CCSD(T)) simulations of the thermodynamics of Fe–N–C-catalyzed CO2 reduction reaction (CO2RR) and its competing hydrogen evolution reaction. Our calculations accurately predict experimental CO binding energy, onset potential, and potential of maximal Faradaic efficiency (FE) with FeN4 as the catalytic active site. We find that the thermodynamic-limiting step is the formation of a *COOH intermediate at low overpotential, which becomes CO2 adsorption and CO desorption at higher overpotential. Our simulation reveals that the potential-dependent high selectivity of FeN4 originates from the higher charge capacity of *COOH compared to *H. Furthermore, our calculations elucidate distinct roles of active-site environments, including vacancy defect and nitrogen doping. Particularly, graphitic nitrogen doping simultaneously lowers the CO2RR onset potential and allows a wider potential range for high CO FE. This work highlights the importance of robust many-body quantum chemical simulations in achieving quantitative understanding of multistep electrocatalytic reaction mechanisms.    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392354997
:TOPICS: 
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i005_1776148")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392354997"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392354997"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392354997"))][Get cited by]]

OpenAlex: https://openalex.org/W4392354997 (Open access: True)
    
, ACS Catalysis. 14(5)] 2024. https://doi.org/10.1021/csv014i005_1776148  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i005_1776148][pdf]])
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392385097
:TOPICS: 
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i005_1776149")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392385097"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392385097"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392385097"))][Get cited by]]

OpenAlex: https://openalex.org/W4392385097 (Open access: False)
    
, ACS Catalysis. 14(5)] 2024. https://doi.org/10.1021/csv014i005_1776149 
     
No abstract    

    
