#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Mon May 27 01:07:30 2024

Found 27 results from 2024-05-20 to 2024-05-27
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Optimizing Selectivity in VOx/TiO2 Catalysts for Ammoxidation: Insights from Structure–Performance Relationships  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398130912
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02141")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398130912"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398130912"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398130912"))][Get cited by]]

OpenAlex: https://openalex.org/W4398130912 (Open access: False)
    
[[https://openalex.org/A5068863304][Haojie Yu]], [[https://openalex.org/A5017864467][Shanjun Mao]], [[https://openalex.org/A5014528965][Bing Liu]], [[https://openalex.org/A5016829733][H. H. Wang]], [[https://openalex.org/A5041161037][Zhiyong Xie]], [[https://openalex.org/A5091275109][Menghui Qi]], [[https://openalex.org/A5069636831][Ruqi Gao]], [[https://openalex.org/A5030325177][Yong Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02141 
     
Multicomponent reactions such as ammoxidation are highly desirable for chemical synthesis. The complicated reaction network and catalytic active sites involved, however, make it rather challenging for extensive structure–performance relationship investigations and subsequent rational design of an efficient catalyst. In this work, efficient VOx/TiO2 catalysts with concise components and exquisite structure design demonstrated 95% selectivity at 98% conversion under 2070 h–1 for 3-picoline ammoxidation. After clarifying that the oxidative dehydrogenation process is rate-limiting, we assumed that the abundance of reactive surface lattice oxygen at the interface of vanadium–titanium is the key to high productivity and suppression of oxidation side reactions since low reaction temperature is beneficial for enlarging the difference in rates of different energy barriers. In addition, rather than applying the traditional neutralization method with alkaline components, in situ formed V2O5 crystallite was subtly to cover the strong acid sites on VOx/TiO2 catalysts in that the strong adsorption of pyridine nitrogen in 3-cyanopyridine on strong acid sites can lead to severe hydrolysis side reactions.    

    

* Non-Oxidative Propane Dehydrogenation by a Well-Defined Ga Catalyst Prepared by Surface Organometallic Chemistry  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398135666
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01118")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398135666"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398135666"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398135666"))][Get cited by]]

OpenAlex: https://openalex.org/W4398135666 (Open access: False)
    
[[https://openalex.org/A5001329661][Jessy Abou Nakad]], [[https://openalex.org/A5019349020][Kaï C. Szeto]], [[https://openalex.org/A5024002693][Aimery De Mallmann]], [[https://openalex.org/A5023777772][Li Li]], [[https://openalex.org/A5029871622][Susannah L. Scott]], [[https://openalex.org/A5042769927][Laurent Delevoye]], [[https://openalex.org/A5069074061][Régis M. Gauvin]], [[https://openalex.org/A5032643129][Mostafa Taoufik]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01118 
     
Ga ions dispersed on alumina catalyze propane dehydrogenation (PDH). Their reactivity has been attributed to the presence of isolated Ga sites, while aggregation to GaOx oligomers and reduction to GaI are reported to be responsible for catalyst deactivation. In this study, we present the preparation and characterization of a highly active and stable single-site catalyst for propane dehydrogenation, consisting of fully dispersed GaIII ions on γ-alumina. The catalyst was synthesized using a surface organometallic chemistry route. Grafting [Ga(OtBu)3]2 onto Al2O3–500 results in the formation of monopodal [(AlsO)Ga(OtBu)2] (I). The controlled thermal treatment of (I) at 300 °C removes the alkoxide ligands and converts (I) into tetracoordinated [(AlsO)3Ga(AlsO-X), X = Als or H] (II). The structures of the intermediate species (I) and the active species (II) were confirmed through elemental analysis, diffuse reflectance infrared Fourier transform spectroscopy (DRIFTS), solid-state NMR, and X-ray absorption spectroscopy (XAS). Material (II) was tested in PDH at 540 °C and exhibited high activity and stability compared to its silica-supported counterpart [(≡SiO)3Ga], suggesting that the isolated nature and robust attachment of (II) onto γ-alumina limit its deactivation.    

    

* Identifying the Active Phase on Atomically Dispersed Catalysts for Propane Dehydrogenation: Positively Charged vs Metallic Transition Metals  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398139287
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-05-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01372")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398139287"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398139287"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398139287"))][Get cited by]]

OpenAlex: https://openalex.org/W4398139287 (Open access: False)
    
[[https://openalex.org/A5052776807][Ping Hu]], [[https://openalex.org/A5068442915][Ming Lei]], [[https://openalex.org/A5067153584][Zhi‐Jun Sui]], [[https://openalex.org/A5042349571][Xinggui Zhou]], [[https://openalex.org/A5025506719][De Chen]], [[https://openalex.org/A5085673398][Yi‐An Zhu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01372 
     
Atomically dispersed transition-metal catalysts have received increasing research interest in heterogeneous catalysis. However, the nature of the real active phase, specifically how the oxidation state of active species may affect the catalytic performance, remains elusive. In this work, ab initio molecular dynamics and large-scale molecular dynamics simulations based on neural network potentials have been employed to assess the structural stability of 52 single- and dual-atom catalysts with transition metals including Mn–Cu, Ru–Ag, and Os–Au embedded in the metal or oxygen vacancies on the defective TiO2 surface. On the thermodynamically stable surfaces, microkinetic analysis combined with results from DFT calculations indicates the metal atoms stabilized in the Ti vacancies with a positive oxidation state generally promote propane dehydrogenation (PDH) with the assistance of adjacent O sites, whereas those in the O vacancies exhibiting metallic properties act as a sole active site for C–H bond activation. The scaling relations established show that the adsorption energies of H and H&H can be used as two simple but effective PDH activity descriptors across both positively charged and metallic metal-doped surfaces. The calculated TOF under the realistic experimental conditions reaches a maximum at a slightly negative oxidation state, implying the Pt and Ir in the metallic state would dominate the kinetics of PDH. Moreover, a high selectivity toward propylene may be attained because the scaling relation between the activation energies for the C–H bond breaking in propane and propylene is broken in the absence of multiple metallic metal–metal sites on the atomically dispersed catalysts. An understanding of this structure–activity relationship is of vital importance for the rational design and optimization of heterogeneous catalysts for light alkane dehydrogenation.    

    

* Precisely Designed Nitrogen-Doped Mesoporous Carbon Sphere-Confined Electron-Deficient Pd Nanoclusters with Enhanced Catalytic Hydrogenation Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398139306
:TOPICS: Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02348")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398139306"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398139306"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398139306"))][Get cited by]]

OpenAlex: https://openalex.org/W4398139306 (Open access: False)
    
[[https://openalex.org/A5035380029][Huacheng Zhao]], [[https://openalex.org/A5005792080][Chuang Liu]], [[https://openalex.org/A5042284357][Yuanzhou Zheng]], [[https://openalex.org/A5031292351][Shuwen Li]], [[https://openalex.org/A5033375004][Yan Gao]], [[https://openalex.org/A5076293642][Qing Ma]], [[https://openalex.org/A5045789022][Fushan Wang]], [[https://openalex.org/A5087289556][Zhengping Dong]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02348 
     
The controlled fabrication of metal nanocluster-based catalysts with high catalytic performance and stability is currently a research hotspot, while it is still a research challenge. Herein, nitrogen-doped mesoporous carbon spheres (CS-N) with a regular and open structure were precisely designed and prepared. Pd nanoclusters with an average size of 1.44 nm were highly dispersed and stably confined in the radial mesoporous structure of CS-N, forming Pd/CS-N catalysts. The obtained Pd/CS-N catalysts showed high catalytic performance in the hydrogenation of phenol to cyclohexanone and hydrogenation of benzoic acid to cyclohexanecarboxylic acid (yield of almost 99%) under mild reaction conditions, outperforming most reported Pd nanoparticle-based catalysts. Theoretical calculation illustrates that the Pd nanocluster exists as an electron-deficient state on Pd/CS-N, thus can efficiently facilitate reactant preadsorption and activation, and also reduce the Gibbs free energy of the rate-determining step of the hydrogenation reactions. Moreover, the Pd/CS-N catalyst exhibited good reusability and stability. Thus, this work will promote the precise construction of stable metal nanocluster-based catalysts, enabling highly efficient catalytic hydrogenation reactions.    

    

* Supported Organochromium Ethylene Oligomerization Enabled by Surface Lithiation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398142351
:TOPICS: Lithium-ion Battery Technology, Battery Recycling and Rare Earth Recovery, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01672")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398142351"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398142351"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398142351"))][Get cited by]]

OpenAlex: https://openalex.org/W4398142351 (Open access: False)
    
[[https://openalex.org/A5001821736][Uddhav Kanbur]], [[https://openalex.org/A5034027190][Jacklyn N. Hall]], [[https://openalex.org/A5027042391][Yu Lim Kim]], [[https://openalex.org/A5040522837][Jens Niklas]], [[https://openalex.org/A5014669390][Oleg G. Poluektov]], [[https://openalex.org/A5060587255][Cong Liu]], [[https://openalex.org/A5010945358][A. Jeremy Kropf]], [[https://openalex.org/A5054572356][Massimiliano Delferro]], [[https://openalex.org/A5024573620][David M. Kaphan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01672 
     
In this work, supported organochromium ethylene polymerization catalysts have been tuned to mediate ethylene oligomerization via surface lithiation, which provides a generalizable protocol to control stereoelectronics and redox states of surface organometallic active sites. The homoleptic chromium(IV) alkyl complex Cr(CH2SiMe3)4 was grafted on high-surface-area anatase titania (TiO2) nanoparticles as well as on silica to produce Cr/TiO2 and Cr/SiO2, respectively. Treatment of these materials with excess n-butyllithium led to the reduced chromium complexes Cr/LixTiO2 and Cr/Li/SiO2, each of which still retains one hydrocarbyl ligand on chromium. A set of heterogeneous complexes were studied by electron paramagnetic resonance and X-ray absorption spectroscopy, which indicate a reduction in the oxidation state of the major chromium species to CrII upon lithiation. Cr/LixTiO2 converts ethylene to hexenes with a high selectivity (>80%), which was persistent over 10 days at 80 °C, achieving >950 turnovers. The exclusive formation of C4 and C6 olefins, preferring the trimerization product, without a statistical (Flory–Schulz) distribution is characteristic of the oxidative cyclization oligomerization mechanism rather than the traditional Cossee–Arlman mechanism, whereas Cr/Li/SiO2 produced a mixture of trimerization and polymerization products, suggesting site heterogeneity in the silica-based material. On the other hand, the unreduced chromium(IV) materials as well as low lithium-containing Cr/LixTiO2 (x < 0.16) exclusively produced ultrahigh molecular weight polyethylene, determined by differential scanning calorimetry and gel permeation chromatography analysis, likely formed via a linear-insertion mechanism, with a crossover from the polymerization to oligomerization regime observed at ∼16% Li intercalation.    

    

* Photocatalyzed H2-Acceptorless Dehydrogenative Borylation by Using Amine Borane  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398142757
:TOPICS: Frustrated Lewis Pairs Chemistry, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00401")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398142757"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398142757"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398142757"))][Get cited by]]

OpenAlex: https://openalex.org/W4398142757 (Open access: False)
    
[[https://openalex.org/A5035180071][Haowen Jiang]], [[https://openalex.org/A5006124276][Wancong Yu]], [[https://openalex.org/A5035557326][Dong Wang]], [[https://openalex.org/A5012000152][Peng‐Fei Xu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00401 
     
Catalytic dehydrogenative borylation of alkenes is arguably the most straightforward approach for synthesizing alkenyl boronates, as it eliminates the need for alkene or boranes prefunctionalizion. While transition-metal catalysis has conventionally been employed for this transformation, competitive side reactions including hydroborylation, overborylation, and regioisomer formation always exist. In this study, we present a radical approach for catalytic dehydrogenative borylation, which involves the synergistic merger of photoredox/HAT/cobalt catalysis, thereby circumventing the necessity for noble metals, sacrificial hydrogen acceptors, and high temperatures. This method employs stable and cost-effective amine borane reagents as feedstocks, resulting in the sole byproduct of H2. This dehydrogenative borylation methodology facilitates the conversion of a diverse array of functionalized alkenes into valuable organoboron reagents. Furthermore, the late-stage borylation of complex molecules demonstrates high levels of site selectivity.    

    

* Photocatalysis toward Microplastics Conversion: A Critical Review  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398143102
:TOPICS: Microplastic Pollution in Marine and Terrestrial Environments, Global E-Waste Recycling and Management, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01449")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398143102"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398143102"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398143102"))][Get cited by]]

OpenAlex: https://openalex.org/W4398143102 (Open access: False)
    
[[https://openalex.org/A5013790248][Ganghua Zhou]], [[https://openalex.org/A5037489490][Hui Xu]], [[https://openalex.org/A5048706086][Hao Song]], [[https://openalex.org/A5025274259][Jianjian Yi]], [[https://openalex.org/A5086657866][Xiaozhi Wang]], [[https://openalex.org/A5044243872][Zupeng Chen]], [[https://openalex.org/A5007599540][Xingwang Zhu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01449 
     
Microplastics (MPs, particle size < 5 mm) have become increasingly ubiquitous on Earth due to the cleavage and degradation of the heavy use of plastics. MPs have recently been reported to be detected in human blood, alveoli, breast milk, embryos, and other organs, raising concerns about their environmental risks. Photocatalysis has been identified as a potential means for MPs conversion, which utilizes solar energy to stimulate a semiconductor photocatalyst. However, the study of photocatalytic conversion of MPs is still in the incubation period. This review overviews the current state-of-the-art technologies for MPs conversion. Then, the fundamental principles, challenges, analytical techniques, and evaluation indexes of photocatalytic MPs reforming are highlighted. We have systematically summarized the recent advances in the photocatalytic conversion of MPs and identified the key factors influencing photocatalytic performance. Finally, we propose some perspectives for developing efficient photocatalytic systems for reforming MPs. This review will provide a guideline for developing and applying photocatalytic technology for reforming MPs, which will significantly contribute to developing this emerging research field.    

    

* Measuring Adsorbate Profiles in Heterogeneous Catalytic Reactors by Iso-Potential Operando DRIFTS Applied to CO2 Methanation on Ni  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398143495
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00536")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398143495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398143495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398143495"))][Get cited by]]

OpenAlex: https://openalex.org/W4398143495 (Open access: False)
    
[[https://openalex.org/A5098710879][Sebastian Sichert]], [[https://openalex.org/A5060326670][Sarah-Franziska Stahl]], [[https://openalex.org/A5013654589][Oliver Korup]], [[https://openalex.org/A5061718643][Raimund Horn]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00536 
     
The development and improvement of catalytic processes require a detailed understanding of catalyst dynamics, reaction mechanisms, and structure–activity relationships inside catalytic reactors, from the laboratory to production scale. This paper presents the methodology of iso-potential operando DRIFTS for measuring the profiles of surface adsorbates inside catalytic reactors. Iso-potential operando spectroscopy (IPOS) in general and iso-potential operando DRIFTS in particular separate the functionality "catalytic reactor" and "spectroscopic cell" from each other. The catalytic reactor is equipped with a mechanism of spatial sampling and spatial temperature measurement. A small fraction of the reaction mixture is sampled locally in the reactor and transferred continuously into a spectroscopic cell containing a very small amount of the same catalyst as in the reactor. The temperature is set to the same value as is locally measured in the reactor. In this way, the catalyst in the spectroscopic cell is exposed to the same chemical potential as that locally in the catalytic reactor. It is hypothesized that it takes on the same structure, the same surface adsorbates, and shows the same reactivity. IPO DRIFTS is applied to CO2 methanation on Ni/γ-Al2O3 catalysts. Two surface adsorbate species, adsorbed carbonyl (*COads) and adsorbed formate (*HCOOads), are detected. The band intensity of *HCOOads decreases along the catalyst bed with the CO2 concentration in the gas phase, identifying surface formate as a kinetically relevant intermediate. This finding is in line with an associative mechanism where CO2 adsorbs on γ-Al2O3 forming carbonate or bicarbonate, being rapidly hydrogenated to formate. Formate reduction is the rate-determining step, with all subsequent hydrogenation steps to CH4 being fast. The band intensity of *COads does not change, irrespective of position in the catalyst bed. This invariance of *COads can be interpreted in two ways. *COads could be a spectator species that is present at the catalyst surface but not involved in any kinetically relevant reaction channel. Alternatively, *COads could be formed by rapid dissociative adsorption of CO2 at the surface of the Ni nanoparticles with a high adsorption equilibrium constant, leading to an almost constant *COads coverage within the investigated CO2 conversion range. If the rate-determining step in the reaction sequence to CH4 would then occur after the formation of *COads, e.g., *COads → *Cads + *Oads or *COads + *Hads → *HCOads, an almost constant *COads signal would result as well.    

    

* Spin Crossover and Exchange Effects on Oxygen Evolution Reaction Catalyzed by Bimetallic Metal Organic Frameworks  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398145641
:TOPICS: Electrocatalysis for Energy Conversion, Perovskite Solar Cell Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01091")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398145641"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398145641"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398145641"))][Get cited by]]

OpenAlex: https://openalex.org/W4398145641 (Open access: True)
    
[[https://openalex.org/A5067593932][Guangsheng Liu]], [[https://openalex.org/A5029818968][Fajun Xie]], [[https://openalex.org/A5074421390][Xu Cai]], [[https://openalex.org/A5045963921][Jingyun Ye]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01091  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01091][pdf]])
     
Bimetallic metal–organic frameworks (BMOFs) have shown a superior oxygen evolution reaction (OER) performance, attributed to the synergistic effects of dual metal sites. However, the significant role of these dual-metal synergies in the OER is not yet fully understood. In this study, we employed density functional theory to systematically investigate the OER performance of NiAl- and NiFe-based BMOFs by examining all possible spin states of each intermediate across diverse external potentials and pH environments. We found that the spin state featuring a shallow hole trap state and Ni ions with a higher oxidation state serve as strong oxidizing agents, promoting the OER. An external potential-induced spin crossover was observed in each intermediate, resulting in significant changes in the overall reaction and activation energies due to altered energy levels. Combining the constant potential method and the electrochemical nudged elastic band method, we mapped the minimum free energy barriers of the OER under varied external potential and pH by considering the spin crossover effect for both NiAl and NiFe BMOFs. The results showed that NiFe exhibits better OER thermodynamics and kinetics, which is in good agreement with experimentally measured OER polarization curves and Tafel plots. Moreover, we found that the improved OER kinetics of NiFe not only is attributed to lower barriers but also is a result of improved electrical conductivity arising from the synergistic effects of Ni–Fe dual-metal sites. Specifically, replacing the second metal Al with Fe leads to two significant outcomes: a reduction in both the band gap and the effective hole mass compared to NiAl, and the initiation of super- and double-exchange interactions within the Ni–F–Fe chain, thereby enhancing electron transfer and hopping and leading to the improved OER kinetics.    

    

* Selective Electrosynthesis of Ethanol via Asymmetric C–C Coupling in Tandem CO2 Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398159967
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01579")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398159967"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398159967"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398159967"))][Get cited by]]

OpenAlex: https://openalex.org/W4398159967 (Open access: False)
    
[[https://openalex.org/A5074562260][Peng Luan]], [[https://openalex.org/A5002524555][Xue Dong]], [[https://openalex.org/A5025734756][Linqi Liu]], [[https://openalex.org/A5004947752][Jianping Xiao]], [[https://openalex.org/A5066863522][Pengfei Zhang]], [[https://openalex.org/A5000201876][Jie Zhang]], [[https://openalex.org/A5058298755][Haibo Chi]], [[https://openalex.org/A5053863846][Qingnan Wang]], [[https://openalex.org/A5014014148][Chunmei Ding]], [[https://openalex.org/A5080416058][Rengui Li]], [[https://openalex.org/A5085201914][Fengyuan Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01579 
     
Selective electroreduction of CO2 to ethanol has economic value and environmental significance. However, the activity and selectivity of CO2 reduction toward ethanol are still low due to the sluggish kinetics of C–C coupling and the intense competition of hydrocarbon production. Herein, we report a layered tandem catalyst consisting of Cu nanosheets with a Cu(111)-oriented surface and Ag nanoparticles, which can effectively shift the selectivity from hydrocarbons to ethanol. The Faradaic efficiency of ethanol was improved from less than 30% on bare Cu(111) to 56.5 ± 2.6% on the layered Cu/Ag tandem catalysts, with a partial current density of 356.7 ± 9.5 mA cm–2. In situ Raman spectroscopy results and density functional theory calculations suggest that the high selectivity toward ethanol can be attributed to the asymmetric *CH2–CO coupling mechanism, which is facilitated by the selective generation of *CH2 species on (111)-facet-exposed Cu nanosheets and the high local CO concentration supplied by the Ag catalyst.    

    

* Atmosphere-Dependent Strong Metal–Support Interactions in Au/ZnO Catalysts and Their Overlayer Permeability  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398162683
:TOPICS: Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02124")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398162683"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398162683"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398162683"))][Get cited by]]

OpenAlex: https://openalex.org/W4398162683 (Open access: False)
    
[[https://openalex.org/A5009089098][Guandong Wu]], [[https://openalex.org/A5077702921][Yiwei Jiang]], [[https://openalex.org/A5014923511][Yiming Niu]], [[https://openalex.org/A5088842976][Bingsen Zhang]], [[https://openalex.org/A5089015352][Lin Li]], [[https://openalex.org/A5077140649][Guoji Liu]], [[https://openalex.org/A5052932306][Yufei He]], [[https://openalex.org/A5055663516][Junhu Wang]], [[https://openalex.org/A5066904777][Dianqing Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02124 
     
The oxidative strong metal–support interaction (O-SMSI) emerges as a pioneering approach for promoting the formation of overlayers, which has garnered significant interest in the exploration of the synthesis of O-SMSI materials. However, the manipulation of the overlayer is rarely discussed and presents a challenge due to its trace presence on the nanoparticle (NP) surface, which impedes the development and utilization of the O-SMSI. In this work, we demonstrate a strong correlation between the treatment atmosphere and the state of the permeable overlayer in the Au/ZnO catalyst. The ZnO overlayer can be formed in both oxidative and inert atmospheres, but the permeability of the overlayer occurs under an oxidative atmosphere. The difference in the permeabilities of the overlayer, at similar particle sizes, leads to a reaction rate difference of approximately 1.4 times. While the permeability of the ZnO overlayer is improved by an oxidative atmosphere treatment, it is also accompanied by an increase in the geometric strain in the ZnO matrix. The permeable ZnO formation is related to the process of gold species insertion into the ZnO matrix, as indicated by density functional theory calculations. This study is the first to describe the role of O2 in manipulating the O-SMSI and suboxide overlayers, offering a potential method for surface engineering.    

    

* Chemosphere-Inspired Irradiation Reallocation Strategy Based on Mie Theory for Stable CO2 Photoreduction over Cu2O  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398164278
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Zinc Oxide Nanostructures
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05802")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398164278"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398164278"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398164278"))][Get cited by]]

OpenAlex: https://openalex.org/W4398164278 (Open access: False)
    
[[https://openalex.org/A5031675164][Tongyu Wang]], [[https://openalex.org/A5089306036][Kuan Deng]], [[https://openalex.org/A5005264493][Hailing Huo]], [[https://openalex.org/A5057441318][Chelsea X. Huang]], [[https://openalex.org/A5091838363][Yiqin Du]], [[https://openalex.org/A5022631289][Ming-Yuan Yu]], [[https://openalex.org/A5042228449][Jingjing Ma]], [[https://openalex.org/A5048140096][Erjun Kan]], [[https://openalex.org/A5022512191][Ang Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05802 
     
No abstract    

    

* Mechanistic and Kinetic Insights into Intermolecular [2+2] Photocycloadditions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398164282
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01678")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398164282"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398164282"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398164282"))][Get cited by]]

OpenAlex: https://openalex.org/W4398164282 (Open access: False)
    
[[https://openalex.org/A5061326292][Gina Quach]], [[https://openalex.org/A5019894293][Hasti Iranmanesh]], [[https://openalex.org/A5063410577][Ena T. Luis]], [[https://openalex.org/A5048562511][Jason B. Harper]], [[https://openalex.org/A5069934510][Jonathon E. Beves]], [[https://openalex.org/A5057877864][Evan G. Moore]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01678 
     
No abstract    

    

* Enantioselective Synthesis of Cyclopropanes via CuH-Catalyzed Intramolecular Hydroalkylation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398172089
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Homogeneous Catalysis with Transition Metals, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-05-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02119")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398172089"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398172089"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398172089"))][Get cited by]]

OpenAlex: https://openalex.org/W4398172089 (Open access: False)
    
[[https://openalex.org/A5014423647][Giovanni Lonardi]], [[https://openalex.org/A5066181785][Santiago Franco]], [[https://openalex.org/A5098732689][Mattia Sartorello]], [[https://openalex.org/A5035489826][Carla De Faveri]], [[https://openalex.org/A5089734852][Mariano Stivanello]], [[https://openalex.org/A5069328269][Giulia Licini]], [[https://openalex.org/A5078857322][Manuel Orlandi]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02119 
     
No abstract    

    

* Synthesis of Chiral Polycyclic Indoles via Pd(II)-Catalyzed Sequential Cyclization and Carbonylation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398176145
:TOPICS: Homogeneous Catalysis with Transition Metals, Transition-Metal-Catalyzed C–H Bond Functionalization, Asymmetric Catalysis
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01325")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398176145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398176145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398176145"))][Get cited by]]

OpenAlex: https://openalex.org/W4398176145 (Open access: False)
    
[[https://openalex.org/A5012324763][Long Chen]], [[https://openalex.org/A5040332516][Hongyou Zhou]], [[https://openalex.org/A5000876494][Yuan Xue]], [[https://openalex.org/A5075372754][Lingyu Kong]], [[https://openalex.org/A5029667848][Yi Wang]], [[https://openalex.org/A5014475523][Xuyao Han]], [[https://openalex.org/A5052874928][Hequan Yao]], [[https://openalex.org/A5011404596][Aijun Lin]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01325 
     
No abstract    

    

* Secondary Alcohol-Driven α-Olefination and α-Alkylation of Nitriles: Introducing a Heterogeneous Ru–Fe Bimetallic Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398210898
:TOPICS: Homogeneous Catalysis with Transition Metals, Carbon Dioxide Utilization for Chemical Synthesis, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-05-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01383")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398210898"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398210898"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398210898"))][Get cited by]]

OpenAlex: https://openalex.org/W4398210898 (Open access: False)
    
[[https://openalex.org/A5073242162][Tianyu Li]], [[https://openalex.org/A5098756034][Yue-Yi Da]], [[https://openalex.org/A5029393445][Jing Chen]], [[https://openalex.org/A5055640837][Zongyan Ma]], [[https://openalex.org/A5016514981][Yu Jin]], [[https://openalex.org/A5075279956][Jiantai Ma]], [[https://openalex.org/A5059149996][Rong Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01383 
     
No abstract    

    

* Synergistic Excited State Photocatalysis: Divergent Energy Transfer vs Lewis Acid Mediated Phototransformations  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398211034
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-05-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01185")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398211034"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398211034"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398211034"))][Get cited by]]

OpenAlex: https://openalex.org/W4398211034 (Open access: False)
    
[[https://openalex.org/A5018185474][Jayachandran Parthiban]], [[https://openalex.org/A5077614006][Dipti Garg]], [[https://openalex.org/A5030892205][Sapna Ahuja]], [[https://openalex.org/A5024642648][Steffen Jockusch]], [[https://openalex.org/A5069274449][Angel Ugrinov]], [[https://openalex.org/A5065746943][Jayaraman Sivaguru]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01185 
     
No abstract    

    

* Chemoenzymatic Sequential Catalysis with Carbonic Anhydrase for the Synthesis of Chiral Alcohols from Alkanes, Alkenes, and Alkynes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398222184
:TOPICS: Enzyme Immobilization Techniques, Droplet Microfluidics Technology, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02481")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398222184"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398222184"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398222184"))][Get cited by]]

OpenAlex: https://openalex.org/W4398222184 (Open access: False)
    
[[https://openalex.org/A5012982494][Zhenzhong Li]], [[https://openalex.org/A5047464957][Zhonghui Wan]], [[https://openalex.org/A5062755510][Wei Wang]], [[https://openalex.org/A5061568119][Lihong Chen]], [[https://openalex.org/A5001300155][Pengfei Ji]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02481 
     
Chiral alcohols are important intermediates for various fine chemicals and pharmaceuticals. Integrating chemical catalysis and efficient enzyme catalysis in sequential systems for the synthesis of chiral alcohols is considered an ecofriendly and promising approach. Herein, employing a highly selective carbonic anhydrase II and different chemical catalysts, we constructed three general chemoenzymatic sequential systems for chiral alcohol compound synthesis from alkanes, alkenes, and alkynes, respectively. Compared to classical approaches, the combination of chemical catalysis and promiscuous carbonic anhydrase catalysis is simple and efficient since it requires only mild reaction conditions and avoids expensive chiral ligands and cumbersome operation steps. In this integrated approach, a wide variety of readily available aryl alkanes, alkenes, and alkynes are transformed into valuable chiral alcohols with excellent enantioselectivity of up to 99% (nearly all above 90%). This unified strategy of combining enzymatic and chemical catalyses advances the general chemoenzymatic process for powerful and important chemical transformations.    

    

* β-Silicon Effect Enables Metal-Free Site-Selective Intermolecular Allylic C–H Amination  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398248046
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-05-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02393")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398248046"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398248046"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398248046"))][Get cited by]]

OpenAlex: https://openalex.org/W4398248046 (Open access: False)
    
[[https://openalex.org/A5069073778][Shuang Lin]], [[https://openalex.org/A5046214153][Yuan Liu]], [[https://openalex.org/A5076357697][Gao Kun-yu]], [[https://openalex.org/A5015399496][Zhihao Chen]], [[https://openalex.org/A5005256858][Jiasheng Qian]], [[https://openalex.org/A5081417229][Xiaobin Liu]], [[https://openalex.org/A5003413443][Qingjiang Li]], [[https://openalex.org/A5081906849][Honggen Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02393 
     
No abstract    

    

* Atomically Precise Control of Silver Species Encaged in Zeolite Catalysts with Minimal Loading for Maximal Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398249717
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-05-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01972")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398249717"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398249717"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398249717"))][Get cited by]]

OpenAlex: https://openalex.org/W4398249717 (Open access: False)
    
[[https://openalex.org/A5033719592][Mengxi Han]], [[https://openalex.org/A5087380102][Yi He]], [[https://openalex.org/A5002101897][Tongwen Yu]], [[https://openalex.org/A5024412052][Pai Peng]], [[https://openalex.org/A5060375527][Jiangwei Shi]], [[https://openalex.org/A5071985886][Hongxia Liu]], [[https://openalex.org/A5008050723][Lei Liu]], [[https://openalex.org/A5032351385][Chenliang Ye]], [[https://openalex.org/A5084185268][Qiang Chen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01972 
     
No abstract    

    

* Cation Effects on the Adsorbed Intermediates of CO2 Electroreduction Are Systematic and Predictable  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398251204
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-05-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00727")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398251204"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398251204"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398251204"))][Get cited by]]

OpenAlex: https://openalex.org/W4398251204 (Open access: True)
    
[[https://openalex.org/A5049396523][Elizabeth Sargeant]], [[https://openalex.org/A5033853790][Paramaconi Rodríguez]], [[https://openalex.org/A5020956698][Federico Calle‐Vallejo]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00727  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00727][pdf]])
     
No abstract    

    

* Mechanistic Understanding of Anthracene Hydrocracking over HY Zeolite Encapsulated Single-Atom Pt Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398251226
:TOPICS: Desulfurization Technologies for Fuels, Zeolite Chemistry and Catalysis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-05-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01706")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398251226"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398251226"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398251226"))][Get cited by]]

OpenAlex: https://openalex.org/W4398251226 (Open access: False)
    
[[https://openalex.org/A5014344328][Wenru Zhao]], [[https://openalex.org/A5039371818][Hui Yu]], [[https://openalex.org/A5067039132][Shaozhong Peng]], [[https://openalex.org/A5055173491][Wei Liu]], [[https://openalex.org/A5035752959][Weiwei Zhang]], [[https://openalex.org/A5051658453][Donghai Mei]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01706 
     
No abstract    

    

* Low-Temperature Thermocatalytic Coupling of CH4 and CO2 to Ethanol over Zn–Ce/ZSM-5 by a Stepwise Technique  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398251514
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-05-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00863")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398251514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398251514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398251514"))][Get cited by]]

OpenAlex: https://openalex.org/W4398251514 (Open access: False)
    
[[https://openalex.org/A5011802940][Yongjun Liu]], [[https://openalex.org/A5073906099][Chaoyu Zhang]], [[https://openalex.org/A5060609860][Ruijia Wang]], [[https://openalex.org/A5064146459][Yixiao Wu]], [[https://openalex.org/A5004400094][Xueyu Zan]], [[https://openalex.org/A5009019093][Tao Shen]], [[https://openalex.org/A5021718138][Wei Huang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00863 
     
No abstract    

    

* Enhancement of Electrochemical Nitrogen Reduction Activity and Suppression of Hydrogen Evolution Reaction for Transition Metal Oxide Catalysts: The Role of Proton Intercalation and Heteroatom Doping  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398764852
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-05-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00223")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398764852"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398764852"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398764852"))][Get cited by]]

OpenAlex: https://openalex.org/W4398764852 (Open access: False)
    
[[https://openalex.org/A5091619107][Qingdong Li]], [[https://openalex.org/A5052939050][Oguz Kaan Kucukosman]], [[https://openalex.org/A5069676941][Qingquan Ma]], [[https://openalex.org/A5079225445][Junjie Ouyang]], [[https://openalex.org/A5079204061][Pavel Kucheryavy]], [[https://openalex.org/A5066076827][Hengfei Gu]], [[https://openalex.org/A5025704358][Conor Long]], [[https://openalex.org/A5034344571][Z. Y. Zhang]], [[https://openalex.org/A5035667249][Joshua Young]], [[https://openalex.org/A5084487002][Jenny V. Lockard]], [[https://openalex.org/A5044534355][Eric Garfunkel]], [[https://openalex.org/A5047994766][Jianan Gao]], [[https://openalex.org/A5073547367][Zhang Wen]], [[https://openalex.org/A5041355919][Huixin He]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00223 
     
During the electrochemical nitrogen reduction reaction (eNRR) and hydrogen evolution reaction (HER), interstitial proton intercalation readily occurs in some transition metal oxide (TMO) catalysts and changes their d-band electronic structure. This work fabricated phosphorus (P)-doped tungsten oxide (WO3) with enriched oxygen vacancies (OVs) to study the impact of proton intercalation and heteroatom doping on eNRR and HER. Our results demonstrated that the electronic structure of the P-OV-WO3 catalyst was altered by in situ proton intercalation as indicated by the greater negative onset potential of eNRR at −0.05 V compared to the proton intercalation potential of 0.3 V versus reversible hydrogen electrode (RHE). Compared to the non-P-doped WO3, the introduction of P doping in WO3 (e.g., 4.8 at. %) led to a reduction of more than 36% in proton intercalation. As a result, the HER activity of the P-OV-WO3 was significantly suppressed, as demonstrated by a considerably negative shift of the onset HER potential from −0.06 to −0.15 V and a slower HER kinetics with the Tafel slope increased from 129.0 to 343.1 mV/dec. Density functional theory calculations revealed the synergy of the proton intercalation, substitutional P doping, and the associated OVs in the improvement of N2 activation and hydrogenation in eNRR. The increased eNRR and the suppressed HER led to a high Faradaic efficiency (FE) of 64.1% and the NH3 yield of 24.5 μg·mg cat–1 h–1 at −0.15 V versus RHE in H2SO4 (pH = 2) as the electrolyte. The specific NH3 yield is more than 20 times higher than that of C-WO3 (1.1 μg·mg cat–1 h–1 with a FE of 20%). The results exceed most of the reported eNRR performances for TMO-based catalysts. Thus, the synergistic proton intercalation and P doping could lead to newer designs and applications of TMO-based catalysts for improved eNRR while suppressing the competing HER.    

    

* Single Transition Metal Atom Catalyst for a High-Performance Li–S Battery with a Graphdiyne–Graphene Heterostructure Host: A DFT Investigation + ML Predictions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398778565
:TOPICS: Lithium-ion Battery Technology, Lithium Battery Technologies, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02066")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398778565"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398778565"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398778565"))][Get cited by]]

OpenAlex: https://openalex.org/W4398778565 (Open access: False)
    
[[https://openalex.org/A5072535948][V G Abhijitha]], [[https://openalex.org/A5003850818][Rohit Batra]], [[https://openalex.org/A5000182570][B. R. K. Nanda]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02066 
     
Shuttling of lithium polysulfides (LiPSs) and slow kinetics of the sulfur reduction reaction (SRR) are considered as the major roadblocks for achieving high-performance lithium–sulfur batteries (LSBs). The solution lies in optimizing the binding strength of LiPSs and catalyzing the SRR. In this work, with the aid of density functional theory calculations, ab initio molecular dynamics simulation, and machine learning (ML), we show that a heterostructure made out of graphene (Gra) and transition metal (TM) atom-anchored graphdiyne (GDY) effectively addresses both these issues. Our results show that the large triangular pores of GDY allow easy penetration of Li+ ions into the sulfur-intercalated TM-GDY/Gra heterostructures and result in LiPSs. The sparsely distributed TM atoms on the GDY surface tune the binding strength of LiPSs and act as catalysts for SRR. Based on the binding strength of LiPSs, TM atom catalysts are categorized into strong, moderate, and weak. Gibbs's free-energy calculations reveal that heterostructures with moderate binding strength are best suited for SRR catalytic activity with barriers smaller than ∼0.4 eV. Furthermore, a Li2S decomposition barrier for the charging process is 3 times lower in the moderate class compared to pristine Gra. Feature importance analysis based on a gradient boosting regression ML model shows that the binding strength of LiPSs in the heterostructures is closely related to intrinsic electronic properties of TM and sulfur atoms, i.e., valence electronic configuration of the TM atom, electronegativity ratio of S to TM atom, and ionic radii of TM and S atoms. Furthermore, it also reveals that the energy barriers for the elementary steps of the SRR are related to the difference in the binding strength of LiPSs corresponding to the conversion step. This study elucidates the suitability of moderate binding heterostructures for LSBs; Fe, Co, Mn, and Rh are preferred single-atom catalysts to serve the purpose.    

    

* Regulating Adsorption of Intermediates via the Sulfur Modulating Dual-Atomic Sites for Boosting CO2RR  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4398783341
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Capture and Storage Technologies, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-05-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02098")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398783341"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398783341"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398783341"))][Get cited by]]

OpenAlex: https://openalex.org/W4398783341 (Open access: False)
    
[[https://openalex.org/A5025611870][Kai Huang]], [[https://openalex.org/A5047778449][Ru Li]], [[https://openalex.org/A5011881849][Qi Hu]], [[https://openalex.org/A5090717104][Shuai Yang]], [[https://openalex.org/A5047486213][Shuhao An]], [[https://openalex.org/A5023414498][Cheng Lian]], [[https://openalex.org/A5069765087][Qing Xu]], [[https://openalex.org/A5067332215][Honglai Liu]], [[https://openalex.org/A5054789376][Jun Hu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02098 
     
The formation of dual-atom catalysts or heteroatom ligand modulation is the most promising strategy for optimizing single–atom catalysts (SACs) for the more efficient conversion of CO2 to valuable chemicals. However, heteroatom ligands introduced into the dual-atomic sites are expected but still under-explored. In this study, a dual-atom Fe–Ni pair electrocatalyst with N– and S–coordination in porous carbon nanosheets was conceptually predicted for electrocatalytic CO2 reduction to CO (CO2RR). In contrast to SACs and traditional diatomic catalysts (DACs), joined S–coordination can balance the cooperative activities of Fe and Ni sites, making the CO2 adsorption configuration bidentate at both Fe–Ni sites. This regulation leads to a substantial change in CO* adsorption from Fe to Ni sites, facilitating CO desorption and boosting the electrocatalytic CO2RR. Experimental results demonstrate that the obtained FeNi–NSC catalyst achieves high selectivity with the Faradaic efficiencies for CO of 96.1%, and a remarkable activity with the turnover frequency of 6526.9 h–1 at −1.0 V, which were over 4.5 and 2.5 times of those from the single Fe or Ni sites. This work gives us insight into designing highly effective catalysts guided by theoretical calculation.    

    

* Biocatalytic Heteroaromatic Amide Formation in Water Enabled by a Catalytic Tetrad and Two Access Tunnels  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399010432
:TOPICS: Peptide Synthesis and Drug Discovery, Enzyme Immobilization Techniques, Olefin Metathesis Chemistry
:PUBLICATION_DATE: 2024-05-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01268")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399010432"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399010432"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399010432"))][Get cited by]]

OpenAlex: https://openalex.org/W4399010432 (Open access: True)
    
[[https://openalex.org/A5085249086][E. Zukic]], [[https://openalex.org/A5093970075][Daniel Mokos]], [[https://openalex.org/A5020247247][Minéia Weber]], [[https://openalex.org/A5010345470][Niklas Stix]], [[https://openalex.org/A5077268915][Klaus Ditrich]], [[https://openalex.org/A5051013236][Virgilio F. Ferrario]], [[https://openalex.org/A5059212484][Henrik Müller]], [[https://openalex.org/A5034558449][Christian Willrodt]], [[https://openalex.org/A5027940353][Karl Gruber]], [[https://openalex.org/A5066897001][Bastian Daniel]], [[https://openalex.org/A5009412615][Wolfgang Kroutil]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01268  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01268][pdf]])
     
No abstract    

    
