#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sat Apr 27 01:02:36 2024

Found 25 results from 2024-04-20 to 2024-04-27
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Catalytic Bias and Redox-Driven Inactivation of the Group B FeFe Hydrogenase CpIII  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394951090
:TOPICS: Biological and Synthetic Hydrogenases: Mechanisms and Applications, Electrocatalysis for Energy Conversion, Platinum-Based Cancer Chemotherapy
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01352")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394951090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394951090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394951090"))][Get cited by]]

OpenAlex: https://openalex.org/W4394951090 (Open access: False)
    
[[https://openalex.org/A5056304450][Andrea Fasano]], [[https://openalex.org/A5007299928][Aurore Jacq‐Bailly]], [[https://openalex.org/A5012477969][Jeremy Wozniak]], [[https://openalex.org/A5064825044][Vincent Fourmond]], [[https://openalex.org/A5040444990][Christophe Léger]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01352 
     
No abstract    

    

* Boosting Hydrogen Adsorption via Manipulating the d-Band Center of Ferroferric Oxide for Anion Exchange Membrane-Based Seawater Electrolysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394953389
:TOPICS: Fuel Cell Membrane Technology, Science and Technology of Capacitive Deionization for Water Desalination, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00267")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394953389"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394953389"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394953389"))][Get cited by]]

OpenAlex: https://openalex.org/W4394953389 (Open access: False)
    
[[https://openalex.org/A5071116473][Lihui Song]], [[https://openalex.org/A5087332040][Lili Guo]], [[https://openalex.org/A5060974161][Jianfeng Mao]], [[https://openalex.org/A5017709527][Zhipeng Li]], [[https://openalex.org/A5071157860][Jiawei Zhu]], [[https://openalex.org/A5072157142][Jianping Lai]], [[https://openalex.org/A5032135658][Jing‐Qi Chi]], [[https://openalex.org/A5010746973][Lei Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00267 
     
No abstract    

    

* Effect of 6,6′-Substituents on Bipyridine-Ligated Ni Catalysts for Cross-Electrophile Coupling  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394953706
:TOPICS: Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed Sulfur Chemistry, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00827")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394953706"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394953706"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394953706"))][Get cited by]]

OpenAlex: https://openalex.org/W4394953706 (Open access: False)
    
[[https://openalex.org/A5078523497][Hanfeng Huang]], [[https://openalex.org/A5016764823][Jose L. Alvarez-Hernandez]], [[https://openalex.org/A5062709693][Nilay Hazari]], [[https://openalex.org/A5038732109][Brandon Q. Mercado]], [[https://openalex.org/A5091106686][Mycah R. Uehling]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00827 
     
A family of 4,4′-tBu2-2,2′-bipyridine (tBubpy) ligands with substituents in either the 6-position, 4,4′-tBu2-6-Me-bpy (tBubpyMe), or 6 and 6′-positions, 4,4′-tBu2-6,6′-R2-bpy (tBubpyR2; R = Me, iPr, sBu, Ph, or Mes), was synthesized. These ligands were used to prepare Ni complexes in the 0, I, and II oxidation states. We observed that the substituents in the 6 and 6′-positions of the tBubpy ligand impact the properties of the Ni complexes. For example, bulkier substituents in the 6,6′-positions of tBubpy better stabilized (tBubpyR2)NiICl species and resulted in a cleaner reduction from (tBubpyR2)NiIICl2. However, bulkier substituents hindered or prevented the coordination of tBubpyR2 ligands to Ni0(cod)2. In addition, by using complexes of the type (tBubpyMe)NiCl2 and (tBubpyR2)NiCl2 as precatalysts for different XEC reactions, we demonstrated that the 6 or 6,6′-substituents lead to major differences in the catalytic performance. Specifically, while (tBubpyMe)NiIICl2 is one of the most active catalysts reported to date for XEC and can facilitate XEC reactions at room temperature, lower turnover frequencies were observed for catalysts containing tBubpyR2 ligands. A detailed study on the catalytic intermediates (tBubpy)Ni(Ar)I and (tBubpyMe2)Ni(Ar)I revealed several factors that likely contributed to the differences in the catalytic activity. For example, whereas complexes of the type (tBubpy)Ni(Ar)I are low spin and relatively stable, complexes of the type (tBubpyMe2)Ni(Ar)I are high-spin and less stable. Furthermore, (tBubpyMe2)Ni(Ar)I captures primary and benzylic alkyl radicals more slowly than (tBubpy)Ni(Ar)I, consistent with the lower activity of the former in catalysis. Our findings will assist in the design of tailor-made ligands for Ni-catalyzed transformations.    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394961569
:TOPICS: 
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i008_1792869")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394961569"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394961569"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394961569"))][Get cited by]]

OpenAlex: https://openalex.org/W4394961569 (Open access: True)
    
, ACS catalysis. 14(8)] 2024. https://doi.org/10.1021/csv014i008_1792869  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i008_1792869][pdf]])
     
No abstract    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394961663
:TOPICS: 
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i008_1792868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394961663"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394961663"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394961663"))][Get cited by]]

OpenAlex: https://openalex.org/W4394961663 (Open access: True)
    
, ACS catalysis. 14(8)] 2024. https://doi.org/10.1021/csv014i008_1792868  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i008_1792868][pdf]])
     
No abstract    

    

* Christina Li, Serge Ruccolo, and Christo Sevov Selected to Receive the 2024 ACS Catalysis Lectureship for the Advancement of Catalytic Science  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394961800
:TOPICS: Enzyme Immobilization Techniques, Chemistry of Actinide and Lanthanide Elements, Role of Porphyrins and Phthalocyanines in Materials Chemistry
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01956")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394961800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394961800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394961800"))][Get cited by]]

OpenAlex: https://openalex.org/W4394961800 (Open access: True)
    
[[https://openalex.org/A5048301965][Cathleen M. Crudden]], ACS catalysis. 14(8)] 2024. https://doi.org/10.1021/acscatal.4c01956  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01956][pdf]])
     
ADVERTISEMENT RETURN TO ISSUEEditorialNEXTChristina Li, Serge Ruccolo, and Christo Sevov Selected to Receive the 2024 ACS Catalysis Lectureship for the Advancement of Catalytic ScienceCathleen CruddenCathleen CruddenMore by Cathleen Cruddenhttps://orcid.org/0000-0003-2154-8107Cite this: ACS Catal. 2024, 14, 8, 5987–5988Publication Date (Web):April 19, 2024Publication History Received1 April 2024Published online19 April 2024Published inissue 19 April 2024https://doi.org/10.1021/acscatal.4c01956Copyright © 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (818 KB) Get e-AlertscloseSUBJECTS:Catalysis,Catalysts,Copper,Peptides and proteins,Redox reactions Get e-Alerts    

    

* Multimodal Acridine Photocatalysis Enables Direct Access to Thiols from Carboxylic Acids and Elemental Sulfur  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394962813
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Innovations in Organic Synthesis Reactions, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01289")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394962813"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394962813"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394962813"))][Get cited by]]

OpenAlex: https://openalex.org/W4394962813 (Open access: False)
    
[[https://openalex.org/A5045502270][Arka Porey]], [[https://openalex.org/A5093030788][Seth Fremin]], [[https://openalex.org/A5077825028][Sachchida Nand]], [[https://openalex.org/A5077981619][Ramon Trevino]], [[https://openalex.org/A5036919128][William B. Hughes]], [[https://openalex.org/A5093030789][Shree Krishna Dhakal]], [[https://openalex.org/A5072745266][Việt Dũng Nguyễn]], [[https://openalex.org/A5069523960][Samuel G. Greco]], [[https://openalex.org/A5067988249][Hadi D. Arman]], [[https://openalex.org/A5039928327][Oleg V. Larionov]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01289 
     
Development of photocatalytic systems that facilitate mechanistically divergent steps in complex catalytic manifolds by distinct activation modes can enable previously inaccessible synthetic transformations. However, multimodal photocatalytic systems remain understudied, impeding their implementation in catalytic methodology. We report herein a photocatalytic access to thiols that directly merges the structural diversity of carboxylic acids with the ready availability of elemental sulfur without substrate preactivation. The photocatalytic transformation provides a direct radical-mediated segue to one of the most biologically important and synthetically versatile organosulfur functionalities, whose synthetic accessibility remains largely dominated by two-electron-mediated processes based on toxic and uneconomical reagents and precursors. The two-phase radical process is facilitated by a multimodal catalytic reactivity of acridine photocatalysis that enables both singlet excited state PCET-mediated decarboxylative carbon–sulfur bond formation and previously unknown radical reductive disulfur bond cleavage by a photoinduced hydrogen atom transfer process in the silane–triplet acridine system. The study points to a significant potential of multimodal photocatalytic systems in providing unexplored directions to previously inaccessible transformations.    

    

* Pt–Pyrrole Complex-Assisted Synthesis of Carbon-Supported Pt Intermetallics for Oxygen Reduction in Proton Exchange Membrane Fuel Cells  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394963378
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05471")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394963378"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394963378"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394963378"))][Get cited by]]

OpenAlex: https://openalex.org/W4394963378 (Open access: False)
    
[[https://openalex.org/A5057532203][Yuting Jiang]], [[https://openalex.org/A5025851882][Qing Zhang]], [[https://openalex.org/A5011770639][Jiajia Qian]], [[https://openalex.org/A5016112203][Yameng Wang]], [[https://openalex.org/A5008002256][Yongbiao Mu]], [[https://openalex.org/A5053402281][Zhiyuan Zhang]], [[https://openalex.org/A5060335470][Zheng Li]], [[https://openalex.org/A5085086661][Tianshou Zhao]], [[https://openalex.org/A5068424935][Bilu Liu]], [[https://openalex.org/A5022926692][Lin Zeng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05471 
     
Nanosized intermetallic Pt-transition metal alloys with high catalytic activity and stability are considered as promising catalysts for the oxygen reduction reaction (ORR). However, the preparation of intermetallic Pt alloy nanoparticles remains a dilemma due to their pronounced tendency for sintering at high synthesizing temperatures. Here, we have synthesized several Pt intermetallics with an average size of 4 nm by employing carbon-supported Pt–-pyrrole complex and transition metal (TM = Fe, Co, Ni) salts as precursors. Transmission electron microscope (TEM) results indicate that not only the uniform pregrowth of the Pt–pyrrole complex onto the carbon support but also the subsequently derived N-doped carbon shells (<1 nm) on the nanoparticles during annealing contribute to the formation of the nanosized intermetallics. Additional characterization suggests that the intermetallic alloy structure endows the catalyst (PtCo@Pt/C-6) with a downshifted Pt d-band center, which implies the weakened adsorption of the ORR intermediates on the Pt alloy, thus facilitating the ORR kinetics. The fuel cell with the as-prepared PtCo@Pt/C-6 catalyst displays a rated peak power density of 1.1 W/cm2 at 0.67 V (H2/air) and a mass activity of 0.49 A/mgPt at 0.9 V, exceeding the targets of the US Department of Energy (1.0 W/cm2 and 0.44 A/mgPt, respectively). This method demonstrates great potentials for the scalable synthesis of PtTM/C catalysts with high ORR performance and promoting their applications in PEMFCs.    

    

* Enhancing the Imine Reductase Activity of a Promiscuous Glucose Dehydrogenase for Scalable Manufacturing of a Chiral Neprilysin Inhibitor Precursor  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394996413
:TOPICS: Enzyme Immobilization Techniques, Droplet Microfluidics Technology, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-04-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05615")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394996413"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394996413"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394996413"))][Get cited by]]

OpenAlex: https://openalex.org/W4394996413 (Open access: False)
    
[[https://openalex.org/A5034348483][Yang Xiang]], [[https://openalex.org/A5038342709][Florian Kleinbeck]], [[https://openalex.org/A5012553136][Charlene Ching]], [[https://openalex.org/A5095829057][Lorita Boghospor]], [[https://openalex.org/A5051684032][Shaiany Sabrina Lopes Gomes]], [[https://openalex.org/A5078461356][Oscar Alvizo]], [[https://openalex.org/A5047905474][Thomas Allmendinger]], [[https://openalex.org/A5005360671][Jason S. Fell]], [[https://openalex.org/A5050627661][Nandhitha Subramanian]], [[https://openalex.org/A5082199987][Michelle Li]], [[https://openalex.org/A5064470458][Ravi Garcia]], [[https://openalex.org/A5091039069][James N. Riggins]], [[https://openalex.org/A5080990349][David A. Entwistle]], [[https://openalex.org/A5078100589][Yvonne Richter]], [[https://openalex.org/A5029415379][Daniel A. Gschwend]], [[https://openalex.org/A5095829056][Liam Lauener]], [[https://openalex.org/A5018005926][T.S. Peat]], [[https://openalex.org/A5026207221][Hélène Lebhar]], [[https://openalex.org/A5007682869][Thierry Schlama]], [[https://openalex.org/A5077097670][Thomas Ruch]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05615 
     
Imine reductases (IREDs) have been identified as an important class of biocatalysts to synthesize chiral amines with substantial promise for industrial application. Here, we report the promiscuous imine reductase activity of a glucose dehydrogenase (GDH). Starting from enzyme GDH Rd1bb, a commercial glucose dehydrogenase variant typically used for NAD(P)H regeneration, eight rounds of directed evolution were used to convert this enzyme into a highly active IRED for the chemo- and stereoselective manufacture of a chiral neprilysin inhibitor precursor, improved NADH cofactor specificity, and superior thermal stability. The evolved variant GDH Rd6bb achieved high productivity, with 99% conversion over 3 h at 50 g/L keto substrate concentration and 10% enzyme loading with respect to the keto substrate. Early process development studies at multigram scale provided the product in 94% yield with >99% purity as a single stereoisomer with an er of >99.9:0.1 and a dr of >99.9:0.1.    

    

* Multifunctional Glucose Dehydrogenase Enabled Synthesis of Chiral-Bridged Bicyclic Nitrogen Heterocycles  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394997118
:TOPICS: Enzyme Immobilization Techniques, Droplet Microfluidics Technology, Catalytic Carbene Chemistry in Organic Synthesis
:PUBLICATION_DATE: 2024-04-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00825")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394997118"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394997118"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394997118"))][Get cited by]]

OpenAlex: https://openalex.org/W4394997118 (Open access: False)
    
[[https://openalex.org/A5058112632][Guangde Jiang]], [[https://openalex.org/A5056183755][J. Lu]], [[https://openalex.org/A5086707099][Megan Zhou]], [[https://openalex.org/A5057920936][Wesley Harrison]], [[https://openalex.org/A5014465828][Huimin Zhao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00825 
     
Herein, we report that enzymatic cascade reactions using a glucose dehydrogenase (GDH) and an ene-reductase (ERED) can be utilized for the synthesis of chiral 3-substituted cyclic alcohols and chiral-bridged bicyclic nitrogen heterocycles. The crucial step in these cascade reactions is a kinetic resolution reaction by the multifunctional GDH mutant BsGDH_Q252K. This reaction selectively reduces the R-enantiomers of racemic ketone substrates, yielding enantiopure alcohols with high enantiomeric excess (ee) values of the remaining S-enantiomers. When the reaction is coupled with an ERED-promoted dehydrocyclization reaction, chiral-bridged bicyclic nitrogen heterocycles with a configuration of (1S, 5R) can be conveniently synthesized in one pot. Meanwhile, the chiral alcohol products generated from the kinetic resolution reactions can be further converted to the R-enantiomers of the racemic ketone substrates through the cyclohexanol dehydrogenase activity of BsGDH_Q252K when coupled with an NAD(P)H oxidase. When the oxidase is replaced by an ERED, chiral-bridged bicyclic nitrogen heterocycles with a configuration of (1R, 5S) can also be efficiently synthesized in one pot. Mechanistic studies revealed key amino acid residues in BsGDH_Q252K for the kinetic resolution reaction. Subsequent rational design of BmGDH, a homolog of BsGDH, yielded can also enable a quintuple mutant capable of performing this reaction, while the wild type BmGDH cannot.    

    

* Overcoming Pd Catalyst Deactivation in the C–H Coupling of Tryptophan Residues in Water Using Air as the Oxidant  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394997156
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Transition Metal-Catalyzed Cross-Coupling Reactions, Neuroimmune Interaction in Psychiatric Disorders
:PUBLICATION_DATE: 2024-04-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01699")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394997156"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394997156"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394997156"))][Get cited by]]

OpenAlex: https://openalex.org/W4394997156 (Open access: True)
    
[[https://openalex.org/A5087931439][Igor Beckers]], [[https://openalex.org/A5022695991][Christophe Vos]], [[https://openalex.org/A5009295415][Hendrik Van Dessel]], [[https://openalex.org/A5064330488][A Lauwers]], [[https://openalex.org/A5030896411][Wouter Stuyck]], [[https://openalex.org/A5004923425][Oleg A. Usoltsev]], [[https://openalex.org/A5038742958][Alina A. Skorynina]], [[https://openalex.org/A5041768941][Aram L. Bugaev]], [[https://openalex.org/A5077238999][Dirk De Vos]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01699  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01699][pdf]])
     
No abstract    

    

* Influence of Water on the Catalytic Oxidation of Ethane on IrO2(110)  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394997366
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00956")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394997366"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394997366"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394997366"))][Get cited by]]

OpenAlex: https://openalex.org/W4394997366 (Open access: False)
    
[[https://openalex.org/A5087317159][Jovenal Jamir]], [[https://openalex.org/A5006390334][Connor Pope]], [[https://openalex.org/A5077547495][S. Ramasubramanian]], [[https://openalex.org/A5055611152][Vikram Mehar]], [[https://openalex.org/A5058633059][Junjie Shi]], [[https://openalex.org/A5010210029][Jason F. Weaver]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00956 
     
No abstract    

    

* Highly Efficient Layered Double Hydroxide-Derived Bimetallic Cu–Co Alloy Catalysts for the Reverse Water–Gas Shift Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395003169
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-04-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01249")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395003169"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395003169"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395003169"))][Get cited by]]

OpenAlex: https://openalex.org/W4395003169 (Open access: False)
    
[[https://openalex.org/A5077401920][Kwang Young Kim]], [[https://openalex.org/A5076755615][Wonsik Jang]], [[https://openalex.org/A5086825154][Woo‐Jin Byun]], [[https://openalex.org/A5000627464][Jun-Young Lee]], [[https://openalex.org/A5040284400][Miri Kim]], [[https://openalex.org/A5030105303][Ju Hyeong Lee]], [[https://openalex.org/A5044574588][Geun Bae Rhim]], [[https://openalex.org/A5089059117][Myung-Joong Youn]], [[https://openalex.org/A5059351725][Dong Hyun Chun]], [[https://openalex.org/A5066671677][Seok Ki Kim]], [[https://openalex.org/A5004903584][Seungho Cho]], [[https://openalex.org/A5010021409][Jin Ho Lee]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01249 
     
Bimetallic alloy catalysts with finely controlled composition and atomic mixing of the two active metals are vital for maximizing their synergistic effect in enhancing catalytic performances. Herein, we report the design and synthetic strategy of bimetallic Cu–Co alloy catalysts well dispersed on Al2O3 from a CuCoAl-layered double hydroxide (LDH) for boosting the reverse water–gas shift (RWGS) performance by controlling the composition and textural properties of Cu–Co alloy particles. An optimized Cu9Co1/Al2O3 catalyst exhibits a remarkably high CO2 to CO conversion rate (∼0.247 mol h–1 gcat–1) with ∼99.4% of CO selectivity at a relatively low reaction temperature of 400 °C, which outperforms a monometallic Cu/Al2O3 catalyst and a reference Cu9Co1/Al2O3 catalyst prepared by a conventional impregnation method. A combined experimental and theoretical study reveals that the superior activity of the Cu9Co1/Al2O3 catalyst is attributed to two factors: (i) a modified electronic structure due to the Cu–Co alloy formation that facilitates CO2 activation and CO desorption and (ii) formation of well-dispersed alloy nanoparticles by using LDHs as the catalyst precursors.    

    

* Rhenium in Heterogeneous Catalysis: A Rising Star for Hydrogenation Reactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395011012
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Homogeneous Catalysis with Transition Metals, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00298")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395011012"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395011012"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395011012"))][Get cited by]]

OpenAlex: https://openalex.org/W4395011012 (Open access: False)
    
[[https://openalex.org/A5037858031][Jingjie Luo]], [[https://openalex.org/A5014316928][Changhai Liang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00298 
     
Rhenium has a special existence in precious metals. In current catalysis, nanoscale Re(Ox) is appreciated by researchers and used to design effective catalyst systems for a variety of hydrogenation reactions, which are widely applied in the fields of petroleum refining, industrial chemical production, and biomass conversion. Current reports focus on the shining characteristics of Re with changeable chemical valences and high oxophilicity. Re-based catalyst provides an essential electronic environment in bimetallic catalysts or behaves as the main reactive center with efficiency. Regardless, there are still limited research works on rhenium compared to other traditional metal catalysts. Herein, investigations concerning Re catalysis during the past decade are summarized. As a burgeoning star, the essential roles of Re sites as a decorator and even the main centers are interpreted in this Review. The advantages of Re in bimetallic and monometallic catalysts, the available-tuned surface and geometric structure, the factors influencing their catalytic behaviors, and the typical heterogeneous reaction models are expressed thoroughly. This Review may shed light on those researchers who are anxious to find more strategies to conquer a tough task and those who are just stepping into the world of rhenium catalysis.    

    

* Correction to “Reductive Enzyme Cascades for Valorization of Polyethylene Terephthalate Deconstruction Products”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395011899
:TOPICS: Microplastic Pollution in Marine and Terrestrial Environments
:PUBLICATION_DATE: 2024-04-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01671")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395011899"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395011899"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395011899"))][Get cited by]]

OpenAlex: https://openalex.org/W4395011899 (Open access: True)
    
[[https://openalex.org/A5019144205][Madan R. Gopal]], [[https://openalex.org/A5042261971][Roman M. Dickey]], [[https://openalex.org/A5076237990][Neil D. Butler]], [[https://openalex.org/A5026235147][Michael R. Talley]], [[https://openalex.org/A5071710693][Daniel T. Nakamura]], [[https://openalex.org/A5019166614][Ashlesha Mohapatra]], [[https://openalex.org/A5091228545][Mary P. Watson]], [[https://openalex.org/A5041423708][Wilfred Chen]], [[https://openalex.org/A5061341492][Aditya M. Kunjapur]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01671  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01671][pdf]])
     
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVAddition/CorrectionNEXTORIGINAL ARTICLEThis notice is a correctionCorrection to "Reductive Enzyme Cascades for Valorization of Polyethylene Terephthalate Deconstruction Products"Madan R. GopalMadan R. GopalDepartment of Chemical & Biomolecular Engineering, University of Delaware, Newark, Delaware 19716, United StatesCenter for Plastics Innovation, University of Delaware, Newark, Delaware 19716, United StatesMore by Madan R. Gopal, Roman M. DickeyRoman M. DickeyDepartment of Chemical & Biomolecular Engineering, University of Delaware, Newark, Delaware 19716, United StatesCenter for Plastics Innovation, University of Delaware, Newark, Delaware 19716, United StatesMore by Roman M. Dickey, Neil D. ButlerNeil D. ButlerDepartment of Chemical & Biomolecular Engineering, University of Delaware, Newark, Delaware 19716, United StatesMore by Neil D. Butler, Michael R. TalleyMichael R. TalleyDepartment of Chemistry and Biochemistry, University of Delaware, Newark, Delaware 19716, United StatesCenter for Plastics Innovation, University of Delaware, Newark, Delaware 19716, United StatesMore by Michael R. Talley, Daniel T. NakamuraDaniel T. NakamuraCenter for Plastics Innovation, University of Delaware, Newark, Delaware 19716, United StatesMore by Daniel T. Nakamura, Ashlesha MohapatraAshlesha MohapatraDepartment of Chemical & Biomolecular Engineering, University of Delaware, Newark, Delaware 19716, United StatesMore by Ashlesha Mohapatra, Mary P. WatsonMary P. WatsonDepartment of Chemistry and Biochemistry, University of Delaware, Newark, Delaware 19716, United StatesCenter for Plastics Innovation, University of Delaware, Newark, Delaware 19716, United StatesMore by Mary P. Watsonhttps://orcid.org/0000-0002-1879-5257, Wilfred ChenWilfred ChenDepartment of Chemical & Biomolecular Engineering, University of Delaware, Newark, Delaware 19716, United StatesCenter for Plastics Innovation, University of Delaware, Newark, Delaware 19716, United StatesMore by Wilfred Chenhttps://orcid.org/0000-0002-6386-6958, and Aditya M. Kunjapur*Aditya M. KunjapurDepartment of Chemical & Biomolecular Engineering, University of Delaware, Newark, Delaware 19716, United StatesCenter for Plastics Innovation, University of Delaware, Newark, Delaware 19716, United StatesMore by Aditya M. Kunjapurhttps://orcid.org/0000-0001-6869-9530Cite this: ACS Catal. 2024, 14, XXX, 7050–7051Publication Date (Web):April 22, 2024Publication History Received18 March 2024Published online22 April 2024https://doi.org/10.1021/acscatal.4c01671© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (1 MB) Get e-Alertsclose Get e-Alerts    

    

* Tuning Acid-Metal Synergy in m-Cresol Hydrodeoxygenation over Bifunctional Pt/Aluminosilicate Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395012109
:TOPICS: Desulfurization Technologies for Fuels, Catalytic Nanomaterials, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-04-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00402")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395012109"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395012109"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395012109"))][Get cited by]]

OpenAlex: https://openalex.org/W4395012109 (Open access: False)
    
[[https://openalex.org/A5010562177][James A. Hunns]], [[https://openalex.org/A5045742486][Lee J. Durndell]], [[https://openalex.org/A5006549163][Xingguang Zhang]], [[https://openalex.org/A5005589369][Muxina Konarova]], [[https://openalex.org/A5060198588][Adam Lee]], [[https://openalex.org/A5038843370][Karen Wilson]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00402 
     
Strong synergy between proximate Bro̷nsted acid and metal sites over a Pt/amorphous silica–alumina (ASA) catalyst confers striking activity and selectivity enhancements for m-cresol hydrodeoxygenation to methylcyclohexane, a fuel additive and potential liquid organic hydrogen carrier for storing renewable energy. Molecular shuttling back and forth between cooperative acid and metal sites activates m-cresol for consecutive tautomerization, ring hydrogenation, and dehydration, ensuing eventual hydrogenation to methylcyclohexane with a fourfold yield enhancement compared to a physical mix of solid acid and Pt/SiO2.    

    

* Revealing the Interaction between Cu and MgO in Cu/MgO Catalysts for CO Hydrogenation to CH3OH  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395013096
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-04-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00077")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395013096"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395013096"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395013096"))][Get cited by]]

OpenAlex: https://openalex.org/W4395013096 (Open access: False)
    
[[https://openalex.org/A5070575311][Wenqi Liu]], [[https://openalex.org/A5065402659][Shanshan Dang]], [[https://openalex.org/A5079527944][Sifan Cheng]], [[https://openalex.org/A5087597269][Zhenzhou Zhang]], [[https://openalex.org/A5034924979][Xiao Ding]], [[https://openalex.org/A5039315799][Yanling Shi]], [[https://openalex.org/A5051084267][Pengfei Ren]], [[https://openalex.org/A5057500762][Weifeng Tu]], [[https://openalex.org/A5057242677][Yi‐Fan Han]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00077 
     
In this work, the structure–performance relationship of Cu/MgO catalysts was established to unravel the role of MgO and the active sites for CO hydrogenation to CH3OH synthesis, by intrinsic kinetics, chemical titration, and a series of in situ (operando) spectroscopic characterizations. The turnover rates of CH3OH formation on Cu/MgO catalysts, especially when the Mg/(Mg + Cu) atomic ratio is 0.67, were significantly higher than that on monometallic Cu particles. We have demonstrated that the rates were insensitive to the particle size of Cu but depended linearly on the quantity of Cu–MgO interfacial sites. The interaction between Cu and MgO particles improved the dispersion of Cu particles and formed more highly active Cu–MgO interfacial sites as identified by precise characterization. Moreover, this study has also unraveled that both the HCO* and HCOO* species are predominantly reactive intermediates, and their sequential hydrogenation occurs concurrently for CH3OH formation over Cu/MgO catalysts during the CO–H2 reaction.    

    

* Kinetic Insights into a Surface-Designed Au1@Pt8/CeO2 Catalyst in the Base-Free Oxidation of Biomass-Derived Tetrahydrofuran-2,5-dimethanol  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395027949
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00168")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395027949"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395027949"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395027949"))][Get cited by]]

OpenAlex: https://openalex.org/W4395027949 (Open access: False)
    
[[https://openalex.org/A5062881637][Enhui Du]], [[https://openalex.org/A5062881637][Enhui Du]], [[https://openalex.org/A5031877307][Panpan Hao]], [[https://openalex.org/A5029886716][Jie Yang]], [[https://openalex.org/A5024604696][Liyuan Huai]], [[https://openalex.org/A5043271589][Guoxin Chen]], [[https://openalex.org/A5043271589][Guoxin Chen]], [[https://openalex.org/A5088105435][C. T. Chen]], [[https://openalex.org/A5088105435][C. T. Chen]], [[https://openalex.org/A5049864837][Jian Zhang]], [[https://openalex.org/A5049864837][Jian Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00168 
     
No abstract    

    

* Solvent-Free Hydroxylation of Unactivated C–H Bonds in Small Molecules and Macromolecules by a Fe Complex  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395030697
:TOPICS: Catalytic Oxidation of Alcohols, Dioxygen Activation at Metalloenzyme Active Sites, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-04-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00775")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395030697"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395030697"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395030697"))][Get cited by]]

OpenAlex: https://openalex.org/W4395030697 (Open access: False)
    
[[https://openalex.org/A5082763762][Debasmita Chatterjee]], [[https://openalex.org/A5074650493][Amritha Sajeevan]], [[https://openalex.org/A5088807420][Sandipan Jana]], [[https://openalex.org/A5079036568][Rajkumar S. Birajdar]], [[https://openalex.org/A5022630161][Samir H. Chikkali]], [[https://openalex.org/A5087313026][Swaminathan Sivaram]], [[https://openalex.org/A5067265421][Sayam Sen Gupta]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00775 
     
One approach to mitigate the crisis of plastic waste is "chemical upcycling", in which waste plastic is either converted into products with higher economic value or depolymerized to its constituent monomer(s). Toward this goal, several metal-catalyzed postfunctionalizations of polymers have been reported, with variable success, mostly on account of a lack of selectivity, the use of harsh reaction conditions, and the use of environmentally unfriendly solvents. We herein demonstrate the selective hydroxylation of the backbone 3° C–H bonds in synthetic macromolecules (polyolefin and polystyrene) using the in-house developed (Et4N)2[FeIII-(Ph,Me-bTAML)] (3) complex and solid Na2CO3·1.5H2O2 (SPC; sodium percarbonate) under solvent-free mechanochemical conditions. The reaction only employs simple mechanochemical grinding or ball milling at room temperature. The polar functional group –OH was successfully incorporated into the polymer backbone without any chain degradation and cross-linking. The same reaction conditions were also employed to selectively hydroxylate small organic molecules including complex natural products. The rate and selectivity of the reaction toward 3° C–H bonds far exceed that performed under homogeneous conditions. Mechanistic investigation indicates the formation of the well-characterized oxoiron(V) intermediate upon mechanical grinding of 3 and SPC. The high selectivity observed under solvent-free conditions is due to the elimination of the solvent-induced side reaction of this intermediate. This reaction represents an environment-friendly process since it uses environmentally benign reagents (iron complex, "oxygen bleach") and eliminates the use of hazardous solvents. The workup protocol involves simple washing with water, where both the spent catalyst and the oxidant are soluble. Selective mechanochemical oxidation of alkyl and benzylic 3° C–H bonds often found in commercial polymers, such as polyolefin and polystyrene, may offer a potentially useful method to generate oxyfunctionalized material and also provide routes for the deconstruction of macromolecules with strong C–C bonds under mild conditions.    

    

* Electric Fields Are a Key Determinant of Carbapenemase Activity in Class A β-Lactamases  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395030775
:TOPICS: Global Challenge of Antibiotic Resistance in Bacteria, Bacterial Biofilms and Quorum Sensing Mechanisms, Dynamics and Pathogenesis of Cholera Bacteria
:PUBLICATION_DATE: 2024-04-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05302")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395030775"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395030775"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395030775"))][Get cited by]]

OpenAlex: https://openalex.org/W4395030775 (Open access: True)
    
[[https://openalex.org/A5031602513][Hira Jabeen]], [[https://openalex.org/A5033720191][Michael Beer]], [[https://openalex.org/A5033720191][Michael Beer]], [[https://openalex.org/A5037611984][James Spencer]], [[https://openalex.org/A5021710523][Marc W. van der Kamp]], [[https://openalex.org/A5021710523][Marc W. van der Kamp]], [[https://openalex.org/A5055553442][H. Adrian Bunzel]], [[https://openalex.org/A5055553442][H. Adrian Bunzel]], [[https://openalex.org/A5044048108][Adrian J. Mulholland]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05302  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05302][pdf]])
     
Resistance to antibiotics is a public health crisis. Although carbapenems are less susceptible to resistance than other β-lactam antibiotics, β-lactamases mediating resistance against these drugs are spreading. Here, we dissect the contributions of electric fields to carbapenemase activity in class A β-lactamases. We perform QM/MM molecular dynamics simulations of meropenem acyl-enzyme hydrolysis that correctly discriminate carbapenemases. Electric field analysis shows that active-site fields in the deacylation transition state and tetrahedral intermediate are important determinants of activity. The active-site fields identify several residues, some distal, that distinguish efficient carbapenemases. Our field analysis script (www.github.com/bunzela/FieldTools) may help in understanding and combating antibiotic resistance.    

    

* Remote Activation of H–H Bonds by Platinum in Dilute Alloy Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395037408
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-04-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00886")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395037408"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395037408"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395037408"))][Get cited by]]

OpenAlex: https://openalex.org/W4395037408 (Open access: True)
    
[[https://openalex.org/A5047919336][Tongxin Han]], [[https://openalex.org/A5056691399][Yuanyuan Li]], [[https://openalex.org/A5085775947][Tao Wu]], [[https://openalex.org/A5078151020][Débora Motta Meira]], [[https://openalex.org/A5078151020][Débora Motta Meira]], [[https://openalex.org/A5077944578][Shuting Xiang]], [[https://openalex.org/A5084047416][Yueqiang Cao]], [[https://openalex.org/A5084047416][Yueqiang Cao]], [[https://openalex.org/A5016394333][Ilkeun Lee]], [[https://openalex.org/A5042349571][Xinggui Zhou]], [[https://openalex.org/A5031199152][De‐en Jiang]], [[https://openalex.org/A5049177403][Anatoly I. Frenkel]], [[https://openalex.org/A5049177403][Anatoly I. Frenkel]], [[https://openalex.org/A5074539493][Francisco Zaera]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00886  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00886][pdf]])
     
No abstract    

    

* Mechanism of Hydrogen Spillover on Metal-Doped Carbon Materials: Surface Carboxylic Groups Are Key  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395042772
:TOPICS: Materials and Methods for Hydrogen Storage, Advancements in Density Functional Theory, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395042772"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395042772"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395042772"))][Get cited by]]

OpenAlex: https://openalex.org/W4395042772 (Open access: False)
    
[[https://openalex.org/A5018495666][Javier Navarro‐Ruiz]], [[https://openalex.org/A5000542312][Jérémy Audevard]], [[https://openalex.org/A5046504358][M. Vidal]], [[https://openalex.org/A5067261862][Cristian H. Campos]], [[https://openalex.org/A5045082437][Iker del Rosal]], [[https://openalex.org/A5068898215][Philippe Serp]], [[https://openalex.org/A5005086485][Iann C. Gerber]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00293 
     
Hydrogen spillover (H-spillover) is the surface migration of activated hydrogen atoms from a metallic particle on which they are generated onto a support. The phenomenon has been widely studied because of its implication in hydrogen storage and in catalytic reactions involving hydrogen. Its existence on carbon materials is well established, but questions remain regarding its mechanism and the involvement of surface oxygen groups. In this study, we combined experimental work with chemical modeling to study the mechanisms of H-spillover on a representative system, including a carbon material presenting basal and prismatic surfaces: oxidized carbon nanotubes doped with Pd. The experimental results, supported by those of modeling, show that the surface carboxylic acid groups are the key species, allowing the spillover of hydrogen on carbon materials to take place. The carboxylic groups can also work in combination with phenol groups to facilitate H-spillover. If the concentration of these groups is too low, then the H-spillover does not operate, except in the case of the addition of water, which serves as a shuttle for the protons. This study leads to a deeper understanding of the long-debated issue of H-spillover on carbon materials and provides insight into designing systems with enhanced properties.    

    

* Mechanistic Origin of Ligand Effects on Exhaustive Functionalization During Pd-Catalyzed Cross-Coupling of Dihaloarenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395042864
:TOPICS: Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00646")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395042864"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395042864"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395042864"))][Get cited by]]

OpenAlex: https://openalex.org/W4395042864 (Open access: False)
    
[[https://openalex.org/A5053710201][Nathaniel G. Larson]], [[https://openalex.org/A5075093016][Jacob P. Norman]], [[https://openalex.org/A5087575581][Sharon R. Neufeldt]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00646 
     
No abstract    

    

* Revealing the Dynamics of Oxygen Vacancy in ZnO1–x/Cu during Robust Methanol Synthesis from CO2  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395048468
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-04-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01648")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395048468"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395048468"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395048468"))][Get cited by]]

OpenAlex: https://openalex.org/W4395048468 (Open access: False)
    
[[https://openalex.org/A5010868208][Fanxing Zhang]], [[https://openalex.org/A5065154024][Boyang Li]], [[https://openalex.org/A5082778481][Qianqian Xu]], [[https://openalex.org/A5026906414][Ke Wang]], [[https://openalex.org/A5089763380][XU Jia-ye]], [[https://openalex.org/A5002848694][Tiantian Wu]], [[https://openalex.org/A5030336185][Zhenglong Li]], [[https://openalex.org/A5030336185][Zhenglong Li]], [[https://openalex.org/A5005798114][Yan Mao]], [[https://openalex.org/A5028214517][Shoujie Liu]], [[https://openalex.org/A5080069508][Yi He]], [[https://openalex.org/A5080069508][Yi He]], [[https://openalex.org/A5079351308][Yao Shi]], [[https://openalex.org/A5013121247][Yaqiong Su]], [[https://openalex.org/A5051365489][Pengfei Xie]], [[https://openalex.org/A5051365489][Pengfei Xie]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01648 
     
The extensive investigation regarding the active site of the Cu/ZnO/Al2O3 catalyst gradually recognizes the paramount importance of the oxygen vacancy in the hydrogenation of CO2 to methanol. However, it is challenging to probe the nature of oxygen vacancy during methanol synthesis and understand its role in the enhancement of reactivity at the molecule level. Here, the inversed ZnO1–x/Cu catalysts with abundant oxygen vacancies are prepared by simple ball milling. The interfacial transformations between ZnO1–x and Cu during material preparation and reaction are elucidated by the correlations of geometrical and chemical states with mechanical energies. The dynamics of the oxygen vacancy during the reaction are revealed as well. The ZnO1–x/Cu with more oxygen vacancy exhibits a superior CH3OH productivity of 1.2 gMeOH g–1 h–1 at 240 °C and a selectivity above 90%. The mechanistic studies reveal that oxygen vacancy promotes the activation of CO2 to formate and significantly reduces the barrier of the hydrogenation from *HCOO to *H2COO intermediates.    

    

* Boosting N-Heterocyclic Carbene Radical Organocatalysis with Nickel Chemistry: A Rational Mechanistic Study-Based Approach  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4395049498
:TOPICS: N-Heterocyclic Carbenes in Catalysis and Materials Chemistry, Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01253")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395049498"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395049498"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395049498"))][Get cited by]]

OpenAlex: https://openalex.org/W4395049498 (Open access: False)
    
[[https://openalex.org/A5039457179][Ludivine Delfau]], [[https://openalex.org/A5042258973][Ernesto Di Mauro]], [[https://openalex.org/A5023111046][Jacques Pécaut]], [[https://openalex.org/A5009617769][David Martín]], [[https://openalex.org/A5025100690][Eder Tomás‐Mendivil]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01253 
     
A cooperative NHC/nickel catalytic methodology has been developed for the synthesis of ketones employing aromatic aldehydes and tertiary alkyl iodides. All key steps of the postulated catalytic cycle were validated with comprehensive stoichiometric and electrochemical studies, including reduction of NiII by the deprotonated Breslow intermediate, Ni0 promoted halogen-atom abstraction to generate transient tertiary alkyl radicals, and coupling between the latter with the persistent acyl thiazolium radical intermediate. Such a broadly proposed and accepted, yet elusive, acyl thiazolium radical intermediate has been isolated and studied by a single-crystal X-ray diffraction study.    

    
