#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Fri Dec 27 01:20:34 2024

Found 31 results from 2024-12-20 to 2024-12-27
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* New Insights into CO2 Electroreduction in Acidic Seawater  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405569566
:TOPICS: CO2 Reduction Techniques and Catalysts, Advanced battery technologies research, Ionic liquids properties and applications
:PUBLICATION_DATE: 2024-12-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05816")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405569566"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405569566"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405569566"))][Get cited by]]

OpenAlex: https://openalex.org/W4405569566 (Open access: False)
    
[[https://openalex.org/A5101791707][Peng Chen]], [[https://openalex.org/A5075533679][Haifeng Shen]], [[https://openalex.org/A5021037658][Min Zheng]], [[https://openalex.org/A5065693067][Mietek Jaroniec]], [[https://openalex.org/A5028236459][Yao Zheng]], [[https://openalex.org/A5032628543][Shi Zhang Qiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05816 
     
The electrochemical CO2 reduction reaction (CO2RR) is of great importance to produce valuable chemicals. In conventional alkaline and "acid + salts"-based CO2RR, the aqueous electrolyte normally needs to be refreshed due to the gradually more neutral feature of pH during electrolysis operation. Therefore, both solutes and deionized (DI) water in electrolytes are required to be regenerated regularly. In this work, acidic seawater (pH < 2) was used as a low-cost but efficient electrolyte for CO2RR without salt addition. The Faradaic efficiencies (FEs) and partial current densities of C2+ on typical copper in the "H2SO4 in raw seawater" electrolyte are comparable with those for conventional "KOH in DI water" and much higher than those for "H2SO4 + salts" systems. Moreover, single-pass carbon efficiencies (SPCEs) in acidic seawater are significantly higher than the values in alkaline DI water. Such an abnormal phenomenon was also demonstrated for CO and HCOOH generation on typical silver and tin catalysts, respectively. In situ Raman spectroscopy and controlled experiments revealed that metal (denoted as M) cations in seawater ensure a higher concentration of M·H2O species, which improve interactions with *CO2–, while Cl– anions enhance the adsorption strength of key CO2RR intermediates (namely, *CO on copper, *COO– on silver, and *OCHO on tin). Through these interactions with water molecules and CO2RR intermediates, such free but functional ions in seawater play a highly important role in promoting selectivity and activity for CO2RR, as well as SPCE in acidic seawater. Furthermore, using acidic seawater as an alternative CO2RR electrolyte has significant economic and ecological benefits compared with traditional alkaline DI water electrolytes.    

    

* Autonomous Exploitation of Reaction Pathways for Electrochemical C–N Coupling on Single-Atom Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405591654
:TOPICS: Ammonia Synthesis and Nitrogen Reduction, CO2 Reduction Techniques and Catalysts, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05751")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405591654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405591654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405591654"))][Get cited by]]

OpenAlex: https://openalex.org/W4405591654 (Open access: False)
    
[[https://openalex.org/A5101858494][Junjie Pan]], [[https://openalex.org/A5111592288][Haowen Ding]], [[https://openalex.org/A5107952334][Xiaoling Yang]], [[https://openalex.org/A5079298233][Xianhui Liang]], [[https://openalex.org/A5048397048][Shanglin Wu]], [[https://openalex.org/A5004026148][Mingzheng Zhang]], [[https://openalex.org/A5021329144][Shunning Li]], [[https://openalex.org/A5067840867][Shisheng Zheng]], [[https://openalex.org/A5055477551][Feng Pan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05751 
     
Electrochemical C–N coupling between CO2 and N-containing small molecules is a promising strategy to close both the carbon and nitrogen loops to support the establishment of a net-zero carbon economy. However, the intricate reaction network and the contentious C–N coupling mechanism hinder the development of efficient electrocatalysts for industrial applications. Herein, we develop a graph-based approach to enable autonomous analysis of the C–N coupling mechanism for coreduction of CO2 and NO3– on single-atom catalysts (SACs). 1400 potential intermediates and 2490 C–N coupling modes are investigated based on the Cu-N4-C prototypical catalyst. We demonstrate that N-containing species with a higher reduction degree are more likely to undergo C–N coupling and the initial coupling of the C–N bond tends to occur on CO2. It is revealed that the hydrogenation energies of *NH2 and CO2, as well as their coupling energies, can serve as key indicators for catalyst recommendation. Using this approach, SACs with Mo, W, or Sb metal centers are identified as promising electrocatalysts for C–N coupling. This work presents a paradigm for automatically exploring the mechanisms of complex electrocatalytic reactions and offers a strategy for predicting highly active and selective SACs.    

    

* Decoding the Role of Adsorbates Entropy in the Reactivity of Single-Atom Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405592086
:TOPICS: Catalytic Processes in Materials Science, Electrocatalysts for Energy Conversion, Catalysis and Oxidation Reactions
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04472")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405592086"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405592086"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405592086"))][Get cited by]]

OpenAlex: https://openalex.org/W4405592086 (Open access: False)
    
[[https://openalex.org/A5008067244][Elena Simone]], [[https://openalex.org/A5087324262][Gianvito Vilé]], [[https://openalex.org/A5087412983][Giovanni Di Liberto]], [[https://openalex.org/A5018929838][Gianfranco Pacchioni]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04472 
     
Single-atom catalysts (SACs) are rapidly gaining attention as a versatile class of materials that combine the advantages of both homogeneous and heterogeneous catalysis. A growing number of studies aim to identify potential new SACs or to describe their structure and reactivity through ab initio quantum chemical simulations. While many computational studies primarily address reactions involving small molecules, such as water splitting or CO2 reduction, the application scope of SACs is rapidly broadening to include the production of fine chemicals and the conversion of biomass-derived platform molecules, processes that involve larger, more complex reactants. Using density-functional theory (DFT) simulations, we demonstrate that, while an approximate treatment of entropy is acceptable for molecules with up to three atoms, it introduces substantial errors in reactions involving more complex molecules. Our results reveal a linear correlation between the entropy of adsorbed molecules and that of the corresponding isolated species, mirroring trends observed on extended catalytic surfaces. For the largest systems investigated in this study, the entropy of the free molecule is reduced by approximately 10–20% upon adsorption; for small molecules, this reduction can range from 50 to 70%. This disparity arises because, on SACs, the translational entropy is effectively zero, the rotational entropy is minimal, and the vibrational entropy increases with the size of the molecule. Moreover, the entropy of adsorbates scales linearly with the number of atoms in the molecule, allowing for the prediction of entropic contributions of adsorbates on SACs without additional computational cost. Using propyne hydrogenation as a test, we demonstrate that the reaction energy profile computed with current approximate approaches for estimating the entropy of adsorbates differs significantly from the profile where entropy is explicitly included. These findings highlight the importance of considering adsorbate entropy for accurately predicting the catalytic activity of SACs, particularly for reactions involving complex molecules.    

    

* One-Pot Chemoenzymatic Synthesis of Arsinothricin and the Mechanistic Insights into the Noncanonical Radical SAM Enzyme ArsL  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405595613
:TOPICS: Radical Photochemical Reactions, bioluminescence and chemiluminescence research, Pesticide and Herbicide Environmental Studies
:PUBLICATION_DATE: 2024-12-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04938")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405595613"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405595613"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405595613"))][Get cited by]]

OpenAlex: https://openalex.org/W4405595613 (Open access: False)
    
[[https://openalex.org/A5101292336][Li He]], [[https://openalex.org/A5034159418][Fen‐Er Chen]], [[https://openalex.org/A5100608631][Wei Ding]], [[https://openalex.org/A5100360362][Qi Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04938 
     
Arsinothricin (AST) is a broad-spectrum arsenic-containing antibiotic with promising pharmaceutical properties. In this study, we report the one-pot chemoenzymatic synthesis of AST starting from methylarsenate, a commonly used agricultural herbicide. Although a single point mutation in the C-terminal region of ArsL completely abolished its activity toward the natural substrate inorganic arsenite, this mutation unexpectedly enhanced its activity toward methylarsenate by over 50-fold, enabling subgram scale production of AST in a cell-free system. These findings offer valuable mechanistic insights into ArsL and highlight the significant potential of manipulating the radical SAM superfamily enzymes in synthetic applications.    

    

* Pd Nanoparticles Decorated by Oxidized Ru Clusters for Efficient C–H/C–H Coupling of Arenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405600947
:TOPICS: Catalytic C–H Functionalization Methods, Nanomaterials for catalytic reactions, Asymmetric Hydrogenation and Catalysis
:PUBLICATION_DATE: 2024-12-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05551")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405600947"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405600947"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405600947"))][Get cited by]]

OpenAlex: https://openalex.org/W4405600947 (Open access: False)
    
[[https://openalex.org/A5046493438][Shingo Hasegawa]], [[https://openalex.org/A5110977155][Shunta Tokutake]], [[https://openalex.org/A5006106507][Koji Harano]], [[https://openalex.org/A5031367549][Ken Motokura]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05551 
     
Oxidative homocoupling of arenes is a challenging but attractive method for converting nonactivated aromatics into biaryl compounds. Applications and the mechanistic understanding of bimetallic nanocatalysts for arene C–H bond activation are limited at present. In this study, we found that a Pd–Ru bimetallic catalyst supported on Al2O3 showed remarkably high catalytic activity for the oxidative homocoupling of arenes owing to the synergistic effect between Pd and Ru. Structural analyses by high-angle annular dark-field scanning transmission electron microscopy with energy-dispersive X-ray spectroscopy and X-ray absorption spectroscopy revealed that the Pd nanoparticles were decorated by partially oxidized Ru clusters. Mechanistic studies indicated that the arene C–H bond cleavage was the rate-determining step and proceeded by a concerted metalation–deprotonation mechanism. It was proposed that the role of Ru is promoting the C–H activation step by generating electron-deficient Pd sites, which was supported by DFT calculations. The Ru-decorated Pd nanoparticles showed large turnover numbers for simple arenes.    

    

* Controlling Co 3d/O 2p Orbital Hybridization in LaCoO3 by Modulating the Co–O–Co Bond Angle for Enhanced Oxygen Evolution Reaction Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405601758
:TOPICS: Electrocatalysts for Energy Conversion, Advanced battery technologies research, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2024-12-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05479")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405601758"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405601758"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405601758"))][Get cited by]]

OpenAlex: https://openalex.org/W4405601758 (Open access: False)
    
[[https://openalex.org/A5042311174][Baoxin Ge]], [[https://openalex.org/A5006405871][Pengyang Jiang]], [[https://openalex.org/A5047896605][Biyi Chen]], [[https://openalex.org/A5082756368][Caijin Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05479 
     
The orbital hybridization between metal and oxygen of perovskite catalysts can lower the overpotential and enhance the oxygen evolution reaction (OER) activity. This study combines density functional theory with experiments to clarify how Sr/Fe codoping modulates orbital hybridization and enhances OER catalytic activity of LaCoO3. The as-prepared La0.50Sr0.50Co0.75Fe0.25O3 shows remarkable performance with a low overpotential of 310 mV at 10 mA cm–2 current density and a 107.03 mV dec–1 Tafel slope, outperforming most state-of-the-art perovskite-based OER electrocatalysts. The experimental results confirm that Sr/Fe codoping enhances the expansion of Co–O–Co bond angles and strengthens the covalency of the Co–O bond in LaCoO3, leading to enhanced electrocatalytic activity. Moreover, increasing Sr doping reduces the distance between the Co 3d/O 2p center and the Fermi level, decreasing the energy difference between them and enhancing the degree of orbital hybridization between Co 3d and O 2p. As the degree of Co 3d/O 2p orbital hybridization increases, a higher charge transfer was found between the active center and intermediate product, OOH, reducing the energy barrier of the rate-determining step while lowering the overpotential. This study provides thorough insight into the rational design of OER catalysts based on orbital hybridization.    

    

* Pincer-Ruthenium-Catalyzed Direct Formation of Fuel-Grade Alkanes via a Net-Decarboxylative Coupling of Alcohols  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405630608
:TOPICS: Asymmetric Hydrogenation and Catalysis, Catalysis for Biomass Conversion, Carbon dioxide utilization in catalysis
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05826")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405630608"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405630608"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405630608"))][Get cited by]]

OpenAlex: https://openalex.org/W4405630608 (Open access: False)
    
[[https://openalex.org/A5113219645][Pran Gobinda Nandi]], [[https://openalex.org/A5115562423][Pabitra Maity]], [[https://openalex.org/A5012177920][Akshai Kumar]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05826 
     
No abstract    

    

* Promoted *OH Adsorption Facilitates C–C Bond Cleavage for Efficient Electrochemical Upcycling of Polyethylene Terephthalate  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405640218
:TOPICS: Recycling and Waste Management Techniques, Conducting polymers and applications, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05352")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405640218"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405640218"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405640218"))][Get cited by]]

OpenAlex: https://openalex.org/W4405640218 (Open access: False)
    
[[https://openalex.org/A5041538055][Jinyong Sun]], [[https://openalex.org/A5103580598][Binkai Shi]], [[https://openalex.org/A5039106340][Shuixing Dai]], [[https://openalex.org/A5041988024][Lei Chu]], [[https://openalex.org/A5023689555][Huanlei Wang]], [[https://openalex.org/A5037398992][Minghua Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05352 
     
No abstract    

    

* Enantioselective Intermolecular Benzylic C–H Amination under Chiral Paddle-Wheel Diruthenium Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405643309
:TOPICS: Synthesis and Catalytic Reactions, Catalytic C–H Functionalization Methods, Asymmetric Hydrogenation and Catalysis
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06504")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405643309"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405643309"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405643309"))][Get cited by]]

OpenAlex: https://openalex.org/W4405643309 (Open access: False)
    
[[https://openalex.org/A5065547400][Kotoko Makino]], [[https://openalex.org/A5108827952][Kohei Mori]], [[https://openalex.org/A5045083056][Shoichi Kiryu]], [[https://openalex.org/A5089822862][Taku Miyazawa]], [[https://openalex.org/A5084305316][Yuhei Kumagai]], [[https://openalex.org/A5001107116][Kosuke Higashida]], [[https://openalex.org/A5087150556][M. Kojima]], [[https://openalex.org/A5012058996][Tatsuhiko Yoshino]], [[https://openalex.org/A5103177232][Shigeki Matsunaga]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06504 
     
A catalytic asymmetric intermolecular benzylic C–H amination was achieved under paddle-wheel diruthenium catalysis. A chiral diruthenium catalyst incorporating (S)-TPPTTL (tetraphenylphthaloyl-(S)-tert-leucine) ligand exhibited notable enantioselectivity, and aminated products were obtained with up to 99% ee. Unique chemoselectivity of the chiral diruthenium catalyst was also found for allylbenzene and alkyl-naphthalene substrates, demonstrating the complementary synthetic utility of chiral paddle-wheel Ru(II)–Ru(III) catalysts to Rh(II) counterparts.    

    

* ML-Accelerated Automatic Process Exploration Reveals Facile O-Induced Pd Step-Edge Restructuring on Catalytic Time Scales  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405644769
:TOPICS: Machine Learning in Materials Science, Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06414")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405644769"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405644769"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405644769"))][Get cited by]]

OpenAlex: https://openalex.org/W4405644769 (Open access: True)
    
[[https://openalex.org/A5083349408][Patricia Poths]], [[https://openalex.org/A5017081585][King C. Lai]], [[https://openalex.org/A5024901288][Francesco Cannizzaro]], [[https://openalex.org/A5004695040][Christoph Scheurer]], [[https://openalex.org/A5056647986][Sebastian Matera]], [[https://openalex.org/A5024866637][Karsten Reuter]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06414 
     
No abstract    

    

* Synthesis of Axially Chiral Vinyl Halides via Cu(I)-Catalyzed Enantioselective Radical 1,2-Halofunctionalization of Terminal Alkynes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405644944
:TOPICS: Axial and Atropisomeric Chirality Synthesis, Catalytic C–H Functionalization Methods, Molecular spectroscopy and chirality
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06672")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405644944"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405644944"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405644944"))][Get cited by]]

OpenAlex: https://openalex.org/W4405644944 (Open access: False)
    
[[https://openalex.org/A5000113087][Jun-Bin Tang]], [[https://openalex.org/A5085137689][Jun-Qian Bian]], [[https://openalex.org/A5058484299][Zhihan Zhang]], [[https://openalex.org/A5043102434][Yong‐Feng Cheng]], [[https://openalex.org/A5100438933][Qin Li]], [[https://openalex.org/A5088566937][Qiang‐Shuai Gu]], [[https://openalex.org/A5025860351][Peiyuan Yu]], [[https://openalex.org/A5018797487][Zhong‐Liang Li]], [[https://openalex.org/A5100670336][Xin‐Yuan Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06672 
     
Organohalides are crucial in modern organic synthesis, thanks to their robust and versatile reactivity in cross-coupling and other key transformations. However, catalytic asymmetric methods for producing enantioenriched organohalides, particularly axially chiral vinyl halides, remain underdeveloped. Here, we present a Cu(I)-catalyzed, highly enantioselective radical alkyne 1,2-halofunctionalization, utilizing custom-designed tridentate anionic N,N,N-ligands with bulky peripheral substituents. This method efficiently employs (hetero)aryl and alkyl sulfonyl chlorides, as well as α-carbonyl alkyl bromides, as radical precursors and utilizes a diverse range of 2-amino and 2-oxy aryl terminal alkynes as substrates to produce highly enantioenriched axially chiral vinyl halides. The reaction is scalable to gram quantities, and the vinyl halides can be further transformed into axially chiral thiourea, pyridyl carboxamide, and quinolyl sulfonamide compounds, some of which show significant potential in asymmetric catalysis. Both experimental and theoretical mechanistic studies support an enantioselective halogen atom transfer mechanism. This method opens an avenue for accessing axially chiral organohalides, facilitating their broad applications in various related fields.    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405650379
:TOPICS: 
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i024_1880616")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405650379"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405650379"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405650379"))][Get cited by]]

OpenAlex: https://openalex.org/W4405650379 (Open access: False)
    
, ACS Catalysis. 14(24)] 2024. https://doi.org/10.1021/csv014i024_1880616 
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405661059
:TOPICS: 
:PUBLICATION_DATE: 2024-12-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i024_1880617")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405661059"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405661059"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405661059"))][Get cited by]]

OpenAlex: https://openalex.org/W4405661059 (Open access: False)
    
, ACS Catalysis. 14(24)] 2024. https://doi.org/10.1021/csv014i024_1880617 
     
No abstract    

    

* Optimizing Oxygen Vacancies through p-Band Center Modulation of Oxygen in the Li2WO4/Mg6MnO8 Catalyst for Enhanced Oxidative Coupling of Methane: An Experimental and Theoretical Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405697614
:TOPICS: Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science, Advancements in Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-12-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06709")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405697614"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405697614"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405697614"))][Get cited by]]

OpenAlex: https://openalex.org/W4405697614 (Open access: False)
    
[[https://openalex.org/A5007519843][Rohan Singh Pal]], [[https://openalex.org/A5029310873][Rubina Khatun]], [[https://openalex.org/A5049997771][Jyotishman Kaishyop]], [[https://openalex.org/A5081971044][Sachin Kumar Sharma]], [[https://openalex.org/A5024972322][Swati Rana]], [[https://openalex.org/A5101726722][Shivani Singh]], [[https://openalex.org/A5090140960][Anil Chandra Kothari]], [[https://openalex.org/A5003911688][Tuhin Suvra Khan]], [[https://openalex.org/A5036395433][Shailendra Tripathi]], [[https://openalex.org/A5086370168][Suman Sarkar]], [[https://openalex.org/A5032217227][Rajaram Bal]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06709 
     
Herein, we demonstrate a one-pot sol–gel-assisted procedure to prepare a defect-rich Li2WO4/Mg6MnO8 catalyst having surface oxygen vacancies, which facilitates the adsorption of O2 molecules to generate active oxygen species (O2–, O22–) by incorporating Li and W into the Mg6MnO8 lattice. These active oxygen species serve as primary active sites, selectively dissociating CH4 into CH3• and promoting CH3• coupling into C2H6, while hindering excessive oxidation of CH3• into COx. Various analytical methods such as XPS, O2-TPD, EPR, CH4-TPSR, in situ DRIFTS, and in situ Raman spectroscopy studies demonstrated that surface reactive oxygen species are more active and selective than lattice oxygen toward the formation of C2 products. The controlled addition of Li and W plays a crucial role in stabilizing surface Li species through the formation of Li–O–W bonds by forming the Li2WO4 phase, ensuring stable catalyst performance up to 100 h. DOS analysis shows a positive shift in the p-band center, which effectively promotes the formation of oxygen vacancies. Analytical studies confirmed that surface active oxygen species are more active and selective than lattice oxygen in forming C2 hydrocarbons. The Li2WO4/Mg6MnO8 catalyst exhibited superior performance, achieving ∼82% C2 selectivity and ∼25% C2 yield at 700 °C. We found that the stable formation of active oxygen species (O2–) and a high Mn4+/Mn3+ ratio over the surface are the key factors for achieving high C2 selectivity and yield during OCM. DFT results show that the concentration of oxygen defect sites is higher on the surface of the Li2WO4/Mg6MnO8 catalyst, which synergistically binds Li2WO4 and Mg6MnO8, in comparison with pure Mg6MnO8 surfaces. Furthermore, DFT calculations also indicate that oxygen vacancies are energetically more favorable on the surface of the Li2WO4/Mg6MnO8 catalyst rather than in its subsurface. In situ XRD and in situ Raman analysis demonstrated that Li2WO4 undergoes a reversible phase change, transitioning into a molten state at higher temperatures, potentially forming Li2O2 species that may serve as active centers during the reaction.    

    

* Ancestral Sequence Reconstruction Reveals Determinants of Regioselectivity in C(sp3)-H Oxyfunctionalization Reactions by CYP505Es  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405702888
:TOPICS: Pharmacogenetics and Drug Metabolism, Eicosanoids and Hypertension Pharmacology, Synthesis and Catalytic Reactions
:PUBLICATION_DATE: 2024-12-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06260")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405702888"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405702888"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405702888"))][Get cited by]]

OpenAlex: https://openalex.org/W4405702888 (Open access: True)
    
[[https://openalex.org/A5058758434][Ana C. Ebrecht]], [[https://openalex.org/A5067119082][Jasmin C. Aschenbrenner]], [[https://openalex.org/A5022958013][Yosephine Gumulya]], [[https://openalex.org/A5051424650][Martha S. Smit]], [[https://openalex.org/A5055261840][Diederik J. Opperman]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06260 
     
Regioselective C–H functionalization of fatty acids and alcohols is a challenging reaction, especially in-chain/midchain hydroxylation. These hydroxy fatty acids or diols offer a synthetic route to valuable δ- and γ-lactones. Although terminal and subterminal hydroxylation of fatty acids and alcohols by cytochrome P450 monooxygenases have been extensively explored, the molecular determinants of in-chain hydroxylation are unknown. Here we performed ancestral sequence reconstruction (ASR) of the subfamily of CYP505Es, able to perform in-chain hydroxylation, together with their closest related subterminal hydroxylases. Three ancestors were resurrected, which represented the in-chain and subterminal hydroxylases, as well as their common ancestor, which displayed little regioselectivity. Mutations were introduced to investigate the divergence in regioselectivity observed in the natural evolution. Whereas subterminal hydroxylation appears to be through multiple additive mutations in the active site, in-chain hydroxylation was greatly affected by the BC-loop. ASR provides not only insight for directed evolution studies but also more promiscuous ancestors as templates for the starting point for laboratory evolution.    

    

* Bis(oxazoline) Iron Complexes Enable Tuning of Lewis Acidity for Catalytic Carbonyl–Olefin Metathesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405703780
:TOPICS: Synthetic Organic Chemistry Methods, Organoboron and organosilicon chemistry, Asymmetric Synthesis and Catalysis
:PUBLICATION_DATE: 2024-12-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04684")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405703780"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405703780"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405703780"))][Get cited by]]

OpenAlex: https://openalex.org/W4405703780 (Open access: False)
    
[[https://openalex.org/A5071609115][Jessica L. Gomez-Lopez]], [[https://openalex.org/A5013478746][Ashlee J. Davis]], [[https://openalex.org/A5109696083][Timothy J. McClure]], [[https://openalex.org/A5064694117][Mina Son]], [[https://openalex.org/A5018802746][Daniel C. Steigerwald]], [[https://openalex.org/A5040142464][Rebecca B. Watson]], [[https://openalex.org/A5030203661][Mu‐Hyun Baik]], [[https://openalex.org/A5049025148][Corinna S. Schindler]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04684 
     
Carbonyl–olefin metathesis reactions are powerful transformations for carbon–carbon bond formation. Despite recent progress, limitations exist that hamper the synthetic generality of the reported approaches. Catalytic systems that will enable tuning of their Lewis acidity and consequently the selective activation of specific substrate classes are expected to greatly enhance the current scope. We herein report the development of cationic iron-bis(oxazoline) complexes as powerful catalysts that enable the alteration of Lewis acidity to efficiently convert substrate types that were previously found to be incompatible with existing catalytic systems in carbonyl–olefin ring-closing metathesis.    

    

* Tuning the Spatial Distribution and Chemical Nature of Acid Sites in MCM-22 Zeolite by Atomically Dispersed Lanthanum Species for Alkylation of 2-Methylnaphthalene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405706656
:TOPICS: Zeolite Catalysis and Synthesis, Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science
:PUBLICATION_DATE: 2024-12-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07304")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405706656"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405706656"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405706656"))][Get cited by]]

OpenAlex: https://openalex.org/W4405706656 (Open access: False)
    
[[https://openalex.org/A5083425534][Yaxing Li]], [[https://openalex.org/A5100449160][Xiaoyu Li]], [[https://openalex.org/A5048066604][Haotian Zhang]], [[https://openalex.org/A5060184702][Jiayi He]], [[https://openalex.org/A5064504602][K.‐X. Su]], [[https://openalex.org/A5101579763][Tianxiang Chen]], [[https://openalex.org/A5077883678][Ruolin Zhang]], [[https://openalex.org/A5066006114][Hua‐Jian Xu]], [[https://openalex.org/A5101433403][Yuchao Wu]], [[https://openalex.org/A5001301417][Weishen Yang]], [[https://openalex.org/A5014361961][Lichen Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c07304 
     
Rare-earth-promoted zeolites have broad applications in the petrochemical industry because modifying zeolites with rare-earth elements can remarkably improve hydrothermal stability and tune the physicochemical properties of the acid sites, resulting in substantial promotion in catalytic selectivity and long-term stability. However, for a specific reaction, it remains a challenge to elaborate the coordination environment of rare-earth elements within the zeolite structure and establish the structure–reactivity of rare-earth-promoted zeolite catalysts. In this work, we have employed multiple spectroscopy and electron microscopy techniques to elucidate the spatial location and coordination environment of atomically dispersed La species in MCM-22 concertedly. In particular, we have attempted to clarify the variation of the chemical nature of the acid sites in MCM-22 zeolite in response to the introduction of La promotor. By appropriately controlling the spatial distribution and chemical nature of the acid sites, we have obtained a La-modified MCM-22 catalyst with high activity, selectivity, and long-term stability (>800 h) for alkylation of 2-methylnaphthalene with methanol for the production of 2,6-dimethyl-naphthalene under industrially relevant conditions.    

    

* Identifying Reactive Trends in Glycerol Electro-Oxidation Using an Automated Screening Approach: 28 Ways to Electrodeposit an Au Electrocatalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405712743
:TOPICS: Electrocatalysts for Energy Conversion, Machine Learning in Materials Science, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2024-12-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04190")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405712743"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405712743"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405712743"))][Get cited by]]

OpenAlex: https://openalex.org/W4405712743 (Open access: True)
    
[[https://openalex.org/A5071397633][Raghuram Gaddam]], [[https://openalex.org/A5106484298][Zirui Wang]], [[https://openalex.org/A5111248857][Yichen Li]], [[https://openalex.org/A5088812818][Lauren C. Harris]], [[https://openalex.org/A5078697577][Michael A. Pence]], [[https://openalex.org/A5053806720][Estefanía Guerrero]], [[https://openalex.org/A5057868460][Paul J. A. Kenis]], [[https://openalex.org/A5021345935][Andrew A. Gewirth]], [[https://openalex.org/A5007986677][Joaquín Rodríguez‐López]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04190 
     
No abstract    

    

* Highly Stable Subnanometric Pt Clusters in All Silica K-Doped Zeolites: Implications for the CO Oxidation Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405720936
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Machine Learning in Materials Science
:PUBLICATION_DATE: 2024-12-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04758")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405720936"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405720936"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405720936"))][Get cited by]]

OpenAlex: https://openalex.org/W4405720936 (Open access: False)
    
[[https://openalex.org/A5048986975][Benjamin Bohigues]], [[https://openalex.org/A5085035152][Isabel Millet]], [[https://openalex.org/A5073126664][Patricia Concepción]], [[https://openalex.org/A5000454699][Avelino Corma]], [[https://openalex.org/A5066850049][Manuel Moliner]], [[https://openalex.org/A5074013662][Pedro Serna]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04758 
     
No abstract    

    

* Catalytic Resonance Theory: Turnover Efficiency and the Resonance Frequency  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405723598
:TOPICS: Electrocatalysts for Energy Conversion, Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science
:PUBLICATION_DATE: 2024-12-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06623")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405723598"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405723598"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405723598"))][Get cited by]]

OpenAlex: https://openalex.org/W4405723598 (Open access: False)
    
[[https://openalex.org/A5114138320][Jesse Canavan]], [[https://openalex.org/A5080549016][J. Hopkins]], [[https://openalex.org/A5070789014][Brandon Foley]], [[https://openalex.org/A5022932212][Omar Abdelrahman]], [[https://openalex.org/A5003718847][Paul J. Dauenhauer]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06623 
     
No abstract    

    

* Modulating Lattice Oxygen through an Alkaline Earth Metal Promoter for Chemical Looping Oxidative Dehydrogenation of Propane  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405724721
:TOPICS: Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science, Chemical Looping and Thermochemical Processes
:PUBLICATION_DATE: 2024-12-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06614")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405724721"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405724721"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405724721"))][Get cited by]]

OpenAlex: https://openalex.org/W4405724721 (Open access: False)
    
[[https://openalex.org/A5100392063][Wei Wang]], [[https://openalex.org/A5101865777][Sai Chen]], [[https://openalex.org/A5090810357][Jiachen Sun]], [[https://openalex.org/A5100389139][Ziyi Li]], [[https://openalex.org/A5100601687][Xianhui Wang]], [[https://openalex.org/A5104229893][Yiyi Xu]], [[https://openalex.org/A5038427980][Zelin Wu]], [[https://openalex.org/A5069288643][Donglong Fu]], [[https://openalex.org/A5100326690][Chunlei Pei]], [[https://openalex.org/A5084194253][Zhi‐Jian Zhao]], [[https://openalex.org/A5047030779][Jinlong Gong]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06614 
     
No abstract    

    

* Cu-Catalyzed Diastereo- and Enantioselective Synthesis of Homopropargyl Amines Bearing All-Carbon Quaternary Stereocenters via Chirality Transfer of Hindered Allenylcopper Species  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405725214
:TOPICS: Asymmetric Synthesis and Catalysis, Catalytic Alkyne Reactions, Catalytic C–H Functionalization Methods
:PUBLICATION_DATE: 2024-12-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06631")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405725214"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405725214"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405725214"))][Get cited by]]

OpenAlex: https://openalex.org/W4405725214 (Open access: False)
    
[[https://openalex.org/A5085754149][Jing He]], [[https://openalex.org/A5088145073][Wan Seok Yoon]], [[https://openalex.org/A5037018542][Jaesook Yun]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06631 
     
The construction of congested acyclic stereocenters with high stereoselectivity is a significant challenge in synthetic chemistry. Herein, we report an efficient method for diastereo- and enantioselective C–C coupling of 1,3-disubstituted enynes with imines for the asymmetric construction of vicinal stereogenic centers, including an all-carbon quaternary center. This coupling was accomplished by chirality transfer from axial-to-central of fully substituted axially chiral allenylcopper intermediates formed in situ from branched enynes with concomitant diastereoselective formation of an additional stereocenter in imine addition enabled by a chiral C1-symmetric N-heterocyclic carbene (NHC) copper catalyst. DFT calculations provided an enhanced understanding of the silyl effect of allenylcopper nucleophiles on reactivity and the origin of stereoselectivity. Synthetic versatility of the resulting products bearing densely functionalized groups could amplify the significance of the current method.    

    

* Elementary Steps, Site Requirements, and Support Effects in Methylcyclohexane Dehydrogenation Reactions on Dispersed Pd Nanoparticles  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405734974
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Asymmetric Hydrogenation and Catalysis
:PUBLICATION_DATE: 2024-12-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07240")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405734974"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405734974"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405734974"))][Get cited by]]

OpenAlex: https://openalex.org/W4405734974 (Open access: False)
    
[[https://openalex.org/A5011995432][Zhongyao Zhang]], [[https://openalex.org/A5101865777][Sai Chen]], [[https://openalex.org/A5020330398][Trenton Otto]], [[https://openalex.org/A5086150545][Enrique Iglesia]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c07240 
     
No abstract    

    

* Synergistic Dual-Atom Catalysts on Ceria for Enhanced CO Preferential Oxidation: Insights from High-Throughput First-Principles Microkinetics  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405734978
:TOPICS: Catalytic Processes in Materials Science, Electrocatalysts for Energy Conversion, Catalysis and Oxidation Reactions
:PUBLICATION_DATE: 2024-12-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05779")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405734978"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405734978"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405734978"))][Get cited by]]

OpenAlex: https://openalex.org/W4405734978 (Open access: False)
    
[[https://openalex.org/A5100709009][Zhang Liu]], [[https://openalex.org/A5043433583][Yanwei Wen]], [[https://openalex.org/A5086671763][Zhaojie Wang]], [[https://openalex.org/A5063687804][Limin Guo]], [[https://openalex.org/A5100418999][Rong Chen]], [[https://openalex.org/A5100656435][Aimin Zhang]], [[https://openalex.org/A5084795179][Bin Shan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05779 
     
No abstract    

    

* ABO4 as an Active Catalyst Structure for Direct Partial CH4 Oxidation as Identified through Screening of Supported Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405738399
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Catalysts for Methane Reforming
:PUBLICATION_DATE: 2024-12-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06376")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405738399"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405738399"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405738399"))][Get cited by]]

OpenAlex: https://openalex.org/W4405738399 (Open access: False)
    
[[https://openalex.org/A5023127226][Junya Ohyama]], [[https://openalex.org/A5036471630][Yuriko Yoshioka]], [[https://openalex.org/A5030581735][Masato TSUKAMOTO]], [[https://openalex.org/A5034502562][Ryota Kuroki]], [[https://openalex.org/A5028191830][Daichi Takahashi]], [[https://openalex.org/A5063143560][Keisuke Awaya]], [[https://openalex.org/A5013139214][Masato Machida]], [[https://openalex.org/A5083848806][Kotaro Higashi]], [[https://openalex.org/A5103395202][Tomoya Uruga]], [[https://openalex.org/A5086036089][Naomi Kawamura]], [[https://openalex.org/A5009715855][Shun Nishimura]], [[https://openalex.org/A5021890207][Keisuke Takahashi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06376 
     
In the present study, 76 different metal-oxide-supported-transition-metal catalysts were prepared using 11 different metal oxides (MgO, Al2O3, SiO2, TiO2, V2O5, ZrO2, Nb2O5, MoO3, Ta2O5, WO3, and La2O3) and seven 3d metals (V, Mn, Fe, Co, Ni, Cu, and Zn). The 76 supported catalysts, along with 11 single metal oxides, were screened to identify catalytically active lattice oxygen structures for the partial oxidation of CH4 to formaldehyde and methanol. Fe/MoO3, Fe/V2O5, and particularly Fe/Nb2O5 were found to be highly effective. Structural analysis of the active Fe sites in the 11 supported Fe catalysts was performed using high-energy-resolution-fluorescence-detected Fe K-edge X-ray absorption near-edge structure spectroscopy, revealing that FeNbO4, FeMoO4, and FeVO4 species in Fe/Nb2O5, Fe/MoO3, and Fe/V2O5, respectively, are responsible for their partial-oxidation activities. In contrast, Fe2O3 species formed in Fe/Al2O3, Fe/SiO2, Fe/Ta2O5, and Fe/WO3 were found to be active for complete oxidation to CO2 than partial oxidation, as were the MgFe2O4, LaFeO3, and TiFe2O5 species formed in Fe/MgO, Fe/La2O3, and Fe/TiO2, respectively, and the interstitial solid solution of Fe3+ in ZrO2 generated in Fe/ZrO2. Furthermore, while the Fe2O3 species in Fe/WO4 are ineffective for partial oxidation, FeWO4 prepared by a hydrothermal method exhibits high selectivity for partial oxidation. Additionally, previous studies have shown that CuWO4 and CuMoO4 are active for partial CH4 oxidation. Accordingly, the ABO4 structure (where A is a 3d metal and B is a group 5 or 6 metal) is indicated as a viable design basis for the development of catalysts for partial CH4 oxidation.    

    

* Pincer-(NHC)Mn(I) Complex-Catalyzed Selective α-Alkylation of Ketones and Nitriles Using Unactivated Alkenyl Alcohols  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405740302
:TOPICS: Asymmetric Hydrogenation and Catalysis, Carbon dioxide utilization in catalysis, Catalytic C–H Functionalization Methods
:PUBLICATION_DATE: 2024-12-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05889")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405740302"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405740302"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405740302"))][Get cited by]]

OpenAlex: https://openalex.org/W4405740302 (Open access: False)
    
[[https://openalex.org/A5059151708][Adarsha Mandal]], [[https://openalex.org/A5088423569][Manoj Pradhan]], [[https://openalex.org/A5012668077][C.R. Mitra]], [[https://openalex.org/A5113157959][Srabani Nandi]], [[https://openalex.org/A5042696274][Biswajit Sadhu]], [[https://openalex.org/A5070370920][Sabuj Kundu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05889 
     
No abstract    

    

* Origin of Stereoselectivity in Ring Opening Metathesis Polymerization with Cationic Molybdenum Imido Alkylidene CAAC Complexes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405741897
:TOPICS: Synthetic Organic Chemistry Methods, Organometallic Complex Synthesis and Catalysis, Chemical Synthesis and Analysis
:PUBLICATION_DATE: 2024-12-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07610")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405741897"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405741897"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405741897"))][Get cited by]]

OpenAlex: https://openalex.org/W4405741897 (Open access: False)
    
[[https://openalex.org/A5058306278][Koushani Kundu]], [[https://openalex.org/A5027100582][S. Haid]], [[https://openalex.org/A5007312468][Moritz R. Schäfer]], [[https://openalex.org/A5090471164][Wolfgang Frey]], [[https://openalex.org/A5056979833][Johannes Kästner]], [[https://openalex.org/A5016791337][Michael R. Buchmeiser]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c07610 
     
Stereoselective ring opening metathesis polymerization (ROMP) of enantiomerically pure 2,3-dicarbomethoxynorborn-5-ene ((+)-DCMNBE) was accomplished by the action of cationic tetra- and pentacoordinated molybdenum imido alkylidene cyclic alkyl amino carbene (CAAC) complexes that are chiral at molybdenum. The same catalysts were also utilized to perform the ROMP of 2,3-dimethoxymethylnorborn-5-ene ((+)-DMMNBE). All complexes were moderately to highly active and showed high trans-isoselectivity, offering up to 97% trans-isotactic (it) repeat units. In all cases, tetracoordinated complexes were the active species, resulting in pentacoordinated transition states. A theoretical model was elaborated using the buried volume (% Vbur) values of all ligands from single-crystal X-ray analysis together with the structures of the density functional theory (DFT) generated molybdacyclobutane intermediates. The model demonstrates the steric effects of all ligands at molybdenum on the trans-isoselectivity of the reaction, as predicted by the turnstile mechanism, and includes a positive correlation between the bulky CAAC ligand with high values of % Vbur of the other ligands and a high trans-isoselectivity. It was also successfully extended to molybdenum imido alkylidene N-heterocyclic carbene (NHC) complexes, proved to be of sufficient accuracy with a root mean squared error (RMSE) of 6.19% and was verified by Monte Carlo cross-validation (MCCV).    

    

* Dopant-Tuned Restructuring Kinetic for the Formation of Heterophase-Confined Metal-Nonmetal Diatomic Sites for Efficient Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405751831
:TOPICS: Electrocatalysts for Energy Conversion, Catalytic Processes in Materials Science, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2024-12-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03060")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405751831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405751831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405751831"))][Get cited by]]

OpenAlex: https://openalex.org/W4405751831 (Open access: False)
    
[[https://openalex.org/A5100370260][Xinyi Li]], [[https://openalex.org/A5101964950][Feiyan Liu]], [[https://openalex.org/A5110689502][Wenting Lu]], [[https://openalex.org/A5017534802][Huafeng Fan]], [[https://openalex.org/A5073215457][Meiling Xiao]], [[https://openalex.org/A5086736710][Xiaoqiang Cui]], [[https://openalex.org/A5100606021][Lu Li]], [[https://openalex.org/A5046104594][Xiaoxin Zou]], [[https://openalex.org/A5108050913][Weitao Zheng]], [[https://openalex.org/A5058184619][Xiao Zhao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03060 
     
No abstract    

    

* The On/Off pH-Dependent Electrocatalytic Activity of the Perfluorinated Iron Phthalocyanine for the Oxygen Reduction Reaction and Electrochemical Hardness as a Reactivity Descriptor: Experimental and Theoretical Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405755151
:TOPICS: Electrochemical Analysis and Applications, Electrocatalysts for Energy Conversion, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2024-12-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06957")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405755151"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405755151"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405755151"))][Get cited by]]

OpenAlex: https://openalex.org/W4405755151 (Open access: False)
    
[[https://openalex.org/A5115632326][Luis Acuña-Saavedra]], [[https://openalex.org/A5013122167][Ana María Méndez‐Torres]], [[https://openalex.org/A5007798531][Gloria Cárdenas‐Jirón]], [[https://openalex.org/A5054608379][Rubén Oñate]], [[https://openalex.org/A5115632327][Benjamín Sánchez-Allende]], [[https://openalex.org/A5083628069][Ricardo Venegas]], [[https://openalex.org/A5086506639][Roberto Bernal]], [[https://openalex.org/A5079391179][Francisco Melo]], [[https://openalex.org/A5055888489][Elizabeth Imbarack]], [[https://openalex.org/A5043992472][José H. Zagal]], [[https://openalex.org/A5010033297][Ingrid Ponce]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06957 
     
No abstract    

    

* Expeditious Synthesis of Highly Functional 4-Trifluoromethyl-Substituted Oxazoles Enabled by Cobalt(II) Metalloradical Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405775871
:TOPICS: Fluorine in Organic Chemistry, Cyclopropane Reaction Mechanisms, Synthesis and Reactions of Organic Compounds
:PUBLICATION_DATE: 2024-12-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07209")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405775871"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405775871"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405775871"))][Get cited by]]

OpenAlex: https://openalex.org/W4405775871 (Open access: False)
    
[[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5018335704][Qingyun Duan]], [[https://openalex.org/A5089813280][Baiquan Wang]], [[https://openalex.org/A5100365280][Bin Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c07209 
     
No abstract    

    

* Enhancing Acidic Water Electrolysis via Local Electronic Regulation of Ru/TiOx Catalyst with Oxygen Coordination Unsaturated Ti Sites  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405783804
:TOPICS: Electrocatalysts for Energy Conversion, Advanced battery technologies research, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2024-12-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06836")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405783804"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405783804"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405783804"))][Get cited by]]

OpenAlex: https://openalex.org/W4405783804 (Open access: False)
    
[[https://openalex.org/A5053858441][Wei Xia]], [[https://openalex.org/A5088890150][Kai Yuan]], [[https://openalex.org/A5071631246][Xuejie Cao]], [[https://openalex.org/A5039881332][Hongye Qin]], [[https://openalex.org/A5005782269][Guangliang Lin]], [[https://openalex.org/A5100648796][Jinyang Zhang]], [[https://openalex.org/A5100661546][Ting Jin]], [[https://openalex.org/A5037415051][Qing‐Lun Wang]], [[https://openalex.org/A5014197896][Lifang Jiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06836 
     
No abstract    

    
