#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Thu Mar 14 00:43:21 2024

Found 25 results from 2024-03-07 to 2024-03-14
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Correction to “Facile Synthesis of Vinyl Boronate Esters via Dehydrogenative Borylation of Alkenes Enabled by Co-MOF Catalyst: An Additive Free Approach”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392499978
:TOPICS: Frustrated Lewis Pairs Chemistry, Homogeneous Catalysis with Transition Metals, Innovations in Organic Synthesis Reactions
:PUBLICATION_DATE: 2024-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01116")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392499978"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392499978"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392499978"))][Get cited by]]

OpenAlex: https://openalex.org/W4392499978 (Open access: True)
    
[[https://openalex.org/A5085820939][Suma Basappa]], [[https://openalex.org/A5001458814][Aishwarya Prakash]], [[https://openalex.org/A5093881181][Sanjana S. Talekar]], [[https://openalex.org/A5061653732][Manoj V. Mane]], [[https://openalex.org/A5053302759][Shubhankar Kumar Bose]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01116  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01116][pdf]])
     
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVCorrectionNEXTORIGINAL ARTICLEThis notice is a correctionCorrection to “Facile Synthesis of Vinyl Boronate Esters via Dehydrogenative Borylation of Alkenes Enabled by Co-MOF Catalyst: An Additive Free Approach”Suma BasappaSuma BasappaCentre for Nano and Material Sciences (CNMS), JAIN (Deemed-to-be University), Jain Global Campus, Bangalore-562112, IndiaMore by Suma Basappa, Aishwarya PrakashAishwarya PrakashCentre for Nano and Material Sciences (CNMS), JAIN (Deemed-to-be University), Jain Global Campus, Bangalore-562112, IndiaMore by Aishwarya Prakash, Sanjana S. TalekarSanjana S. TalekarCentre for Nano and Material Sciences (CNMS), JAIN (Deemed-to-be University), Jain Global Campus, Bangalore-562112, IndiaMore by Sanjana S. Talekar, Manoj V. Mane*Manoj V. ManeCentre for Nano and Material Sciences (CNMS), JAIN (Deemed-to-be University), Jain Global Campus, Bangalore-562112, India*Email: [email protected]More by Manoj V. Mane, and Shubhankar Kumar Bose*Shubhankar Kumar BoseCentre for Nano and Material Sciences (CNMS), JAIN (Deemed-to-be University), Jain Global Campus, Bangalore-562112, India*Email: [email protected]More by Shubhankar Kumar Bosehttps://orcid.org/0000-0002-1057-2403Cite this: ACS Catal. 2024, 14, XXX, 4301–4302Publication Date (Web):March 6, 2024Publication History Received20 February 2024Published online6 March 2024https://doi.org/10.1021/acscatal.4c01116© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (725 KB) Get e-AlertscloseSUBJECTS:Borylation,Catalysts,Hydrocarbons,Hydrogenation,Organic compounds Get e-Alerts    

    

* Copper-Catalyzed Chemoselective (Amino)fluorosulfonylation of Hydrocarbons via Intramolecular Fluorine-Atom Transfer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392503323
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Innovations in Organic Synthesis Reactions
:PUBLICATION_DATE: 2024-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00116")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392503323"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392503323"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392503323"))][Get cited by]]

OpenAlex: https://openalex.org/W4392503323 (Open access: False)
    
[[https://openalex.org/A5016736936][Shiyao Qu]], [[https://openalex.org/A5029533535][Xiao Xi Li]], [[https://openalex.org/A5061667297][Xingwei Li]], [[https://openalex.org/A5053275663][Lin Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00116 
     
Sulfonyl fluorides have found increasing applications as functional molecules in chemistry and biology. We herein report a copper-catalyzed atom-economical access to two categories of sulfonyl fluorides through a radical relay strategy in the presence of an SO2 surrogate. The aliphatic C(sp3)–H bond in N-fluoro-N-alkyl sulfonamides reacted via a 1,5-hydrogen atom transfer (HAT) process, affording alkanesulfonyl fluorides with a proximal amino group. On the other hand, utilizing substrates containing a proper C═C double bond resulted in intramolecular olefin aminofluorosulfonylation, allowing the synthesis of fluorosulfonyl-functionalized pyrrolidines and piperidines via atom-transfer radical addition (ATRA). Both reaction systems proceeded under mild conditions, requiring no additional fluorine source. Experimental and computational studies suggest that S–F coupling is likely achieved through an intramolecular radical-rebound pathway. By taking advantage of the SuFEx chemistry and multifunctionality of the products, the method is applicable to the late-stage modification of bioactive compounds, drug ligation chemistry, and organic synthesis.    

    

* Iron-Catalyzed Intramolecular C(sp3)-H Lactonization of Hydroxamate Derivatives Promoted by a 1,5-HAT  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392503558
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Homogeneous Catalysis with Transition Metals, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04900")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392503558"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392503558"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392503558"))][Get cited by]]

OpenAlex: https://openalex.org/W4392503558 (Open access: False)
    
[[https://openalex.org/A5094079327][Hugo Esteves]], [[https://openalex.org/A5015902391][Tania Xavier]], [[https://openalex.org/A5046569010][Sonia Lajnef]], [[https://openalex.org/A5084976373][Fabienne Peyrot]], [[https://openalex.org/A5021299818][Guillaume Lefèvre]], [[https://openalex.org/A5031620212][Guillaume Prestat]], [[https://openalex.org/A5083778303][Farouk Berhal]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04900 
     
An iron-catalyzed lactonization reaction via intramolecular C(sp3)-H functionalization is described. The process employs easily accessible hydroxamate derivatives from which the noncommon insertion of the oxygen occurred through a 1,5-hydrogen atom transfer. A mixture of water and hexafluoroisopropanol as solvent appeared to be the key parameter of this transformation to reach a high selectivity and efficiency.    

    

* Stabilization of the Active Ruthenium Oxycarbonate Phase for Low-Temperature CO2 Methanation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392517574
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-03-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05679")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392517574"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392517574"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392517574"))][Get cited by]]

OpenAlex: https://openalex.org/W4392517574 (Open access: True)
    
[[https://openalex.org/A5089580288][Carmen Tébar-Soler]], [[https://openalex.org/A5079824914][Vlad Martin‐Diaconescu]], [[https://openalex.org/A5018172983][Laura Simonelli]], [[https://openalex.org/A5079393657][Alexander Missyul]], [[https://openalex.org/A5030683006][Virgínia Pérez-Dieste]], [[https://openalex.org/A5069531697][Ignacio J. Villar‐García]], [[https://openalex.org/A5086322000][Daviel Gómez]], [[https://openalex.org/A5019340238][Jean‐Blaise Brubach]], [[https://openalex.org/A5003198132][Pascale Le Roy]], [[https://openalex.org/A5000454699][Avelino Corma]], [[https://openalex.org/A5073126664][Patricia Concepción]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05679  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05679][pdf]])
     
Interstitial carbon-doped RuO2 catalyst with the newly reported ruthenium oxycarbonate phase is a key component for low-temperature CO2 methanation. However, a crucial factor is the stability of interstitial carbon atoms, which can cause catalyst deactivation when removed during the reaction. In this work, the stabilization mechanism of the ruthenium oxycarbonate active phase under reaction conditions is studied by combining advanced operando spectroscopic tools with catalytic studies. Three sequential processes: carbon diffusion, metal oxide reduction, and decomposition of the oxycarbonate phase and their influence by the reaction conditions, are discussed. We present how the reaction variables and catalyst composition can promote carbon diffusion, stabilizing the oxycarbonate catalytically active phase under steady-state reaction conditions and maintaining catalyst activity and stability over long operation times. In addition, insights into the reaction mechanism and a detailed analysis of the catalyst composition that identifies an adequate balance between the two phases, i.e., ruthenium oxycarbonate and ruthenium metal, are provided to ensure an optimum catalytic behavior.    

    

* Adjusting the Operational Potential Window as a Tool for Prolonging the Durability of Carbon-Supported Pt-Alloy Nanoparticles as Oxygen Reduction Reaction Electrocatalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392520370
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06251")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392520370"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392520370"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392520370"))][Get cited by]]

OpenAlex: https://openalex.org/W4392520370 (Open access: True)
    
[[https://openalex.org/A5025273941][Tina Đukić]], [[https://openalex.org/A5086588496][Léonard Moriau]], [[https://openalex.org/A5093093339][Iva Klofutar]], [[https://openalex.org/A5074073109][Martin Šala]], [[https://openalex.org/A5057907379][Luka Pavko]], [[https://openalex.org/A5033818689][Francisco Javier González López]], [[https://openalex.org/A5077081602][Francisco Ruíz-Zepeda]], [[https://openalex.org/A5041407843][Andraž Pavlišič]], [[https://openalex.org/A5093093340][Miha Hotko]], [[https://openalex.org/A5073443270][Matija Gatalo]], [[https://openalex.org/A5065843632][Nejc Hodnik]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06251  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06251][pdf]])
     
A current trend in the investigation of state-of-the-art Pt-alloys as proton exchange membrane fuel cell (PEMFC) electrocatalysts is to study their long-term stability as a bottleneck for their full commercialization. Although many parameters have been appropriately addressed, there are still certain issues that must be considered. Here, the stability of an experimental Pt-Co/C electrocatalyst is investigated by high-temperature accelerated degradation tests (HT-ADTs) in a high-temperature disk electrode (HT-DE) setup, allowing the imitation of close-to-real operational conditions in terms of temperature (60 °C). Although the US Department of Energy (DoE) protocol has been chosen as the basis of the study (30,000 trapezoidal wave cycling steps between 0.6 and 0.95 VRHE with a 3 s hold time at both the lower potential limit (LPL) and the upper potential limit (UPL)), this works demonstrates that limiting both the LPL and UPL (from 0.6–0.95 to 0.7–0.85 VRHE) can dramatically reduce the degradation rate of state-of-the-art Pt-alloy electrocatalysts. This has been additionally confirmed with the use of an electrochemical flow cell coupled to inductively coupled plasma mass spectrometry (EFC-ICP-MS), which enables real-time monitoring of the dissolution mechanisms of Pt and Co. In line with the HT-DE methodology observations, a dramatic decrease in the total dissolution of Pt and Co has once again been observed upon narrowing the potential window to 0.7–0.85 VRHE rather than 0.6–0.95 VRHE. Additionally, the effect of the potential hold time at both LPL and UPL on metal dissolution has also been investigated. The findings demonstrate that the dissolution rate of both metals is proportional to the hold time at UPL regardless of the applied potential window, whereas the hold time at the LPL does not appear to be as detrimental to the stability of metals.    

    

* Electrocatalytic CO2 Reduction with Atomically Precise Au13 Nanoclusters: Effect of Ligand Shell on Catalytic Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392550903
:TOPICS: Structural and Functional Study of Noble Metal Nanoclusters, Nanomaterials with Enzyme-Like Characteristics, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-03-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06114")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392550903"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392550903"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392550903"))][Get cited by]]

OpenAlex: https://openalex.org/W4392550903 (Open access: True)
    
[[https://openalex.org/A5029638131][Tetyana I. Levchenko]], [[https://openalex.org/A5086411156][Hong Yi]], [[https://openalex.org/A5043310485][Mark D. Aloisio]], [[https://openalex.org/A5012960880][Ngoc Kim Dang]], [[https://openalex.org/A5037820228][Guofu Gao]], [[https://openalex.org/A5090568547][Sachil Sharma]], [[https://openalex.org/A5012487063][Cao-Thang Dinh]], [[https://openalex.org/A5048301965][Cathleen M. Crudden]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06114  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06114][pdf]])
     
Supported gold nanoclusters of the formula [Au13(L)5Cl2]3+ where L = N-heterocyclic carbene (NHC) or phosphine ligands are examined in the electrocatalytic CO2 reduction reaction (eCO2RR) in a membrane electrode assembly cell configuration. Gold nanoclusters bearing bisNHC ligands are shown to exhibit improved catalytic performance compared with diphosphine-stabilized nanoclusters after activation at the optimum treatment temperatures. The thermal properties of the nanoclusters are shown to have a significant impact on their catalytic activity. Thermogravimetric analysis, UV–vis absorption spectroscopy, and X-ray photoelectron spectroscopy revealed that thermal treatment of [Au13(diphosphine)5Cl2]3+ nanoclusters results in complete loss of diphosphine ligands while [Au13(bisNHC)5Cl2]3+ nanoclusters show stepwise and partial removal of bisNHC ligands. We propose that the partial removal of bisNHC ligands enables efficient activation of [Au13(bisNHC)5Cl2]3+ clusters while conserving the core structure. This leads to the implication that intact clusters retaining at least some ligands in their coordination environment are more active than ligand-free clusters.    

    

* Revving up a Designed Copper Nitrite Reductase Using Noncoded Active Site Ligands  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392551437
:TOPICS: Biological and Synthetic Hydrogenases: Mechanisms and Applications, Dioxygen Activation at Metalloenzyme Active Sites, Platinum-Based Cancer Chemotherapy
:PUBLICATION_DATE: 2024-03-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06159")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392551437"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392551437"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392551437"))][Get cited by]]

OpenAlex: https://openalex.org/W4392551437 (Open access: False)
    
[[https://openalex.org/A5064197479][Winston C Pitts]], [[https://openalex.org/A5054564985][Aniruddha Deb]], [[https://openalex.org/A5083519149][James E. Penner‐Hahn]], [[https://openalex.org/A5084987684][Vincent L. Pecoraro]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06159 
     
No abstract    

    

* Sulfite-Enhanced Aerobic Methane Oxidation to Methanol over Reduced Phosphomolybdate  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392551491
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Innovations in Organic Synthesis Reactions, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-03-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00234")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392551491"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392551491"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392551491"))][Get cited by]]

OpenAlex: https://openalex.org/W4392551491 (Open access: False)
    
[[https://openalex.org/A5042365006][Sikai Wang]], [[https://openalex.org/A5036903664][Hua An]], [[https://openalex.org/A5076804358][Max J. Hülsey]], [[https://openalex.org/A5063093801][Geng Sun]], [[https://openalex.org/A5051694258][Qian He]], [[https://openalex.org/A5075696165][Ning Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00234 
     
No abstract    

    

* Accelerated Dual Activation of Lattice Oxygen and Molecule Oxygen over CoMn2O4 Catalysts for VOC Oxidation: Promoting the Role of Oxygen Vacancies  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392552229
:TOPICS: Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-03-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06237")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392552229"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392552229"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392552229"))][Get cited by]]

OpenAlex: https://openalex.org/W4392552229 (Open access: False)
    
[[https://openalex.org/A5078931487][Yewei Ren]], [[https://openalex.org/A5046731703][Caixia Song]], [[https://openalex.org/A5056775642][Hui Wang]], [[https://openalex.org/A5017052045][Zhenping Qu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06237 
     
No abstract    

    

* Enhanced Charge Transfer via Heterogeneous Doping Promotes Hematite Photoelectrodes for Efficient Solar H2O2 Synthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392564717
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Solar Water Splitting Technology, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06110")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392564717"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392564717"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392564717"))][Get cited by]]

OpenAlex: https://openalex.org/W4392564717 (Open access: False)
    
[[https://openalex.org/A5042654076][Fang Guo]], [[https://openalex.org/A5012243269][Jinwei Bai]], [[https://openalex.org/A5036327118][Rui‐Ting Gao]], [[https://openalex.org/A5081765995][Kai Su]], [[https://openalex.org/A5028936579][Yang Yang]], [[https://openalex.org/A5080100993][Xianhu Liu]], [[https://openalex.org/A5079455306][Limin Wu]], [[https://openalex.org/A5071476964][Lei Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06110 
     
Photoelectrochemical (PEC) water splitting into hydrogen peroxide (H2O2) and hydrogen (H2) is a promising alternative to energy and environmentally intensive production. Bulk electronic and surface structures affect the charge transport efficiency and catalytic activity of the photoelectrode. Herein, we design and investigate a hematite (Fe2O3) nanorod photoelectrode with hafnium and titanium binary dopants for highly selective H2O2 production. The resultant photoanode shows a H2O2 yield of 0.41 μmol min–1 cm–2 at 1.5 VRHE with a Faradaic efficiency of 72.2%. Experimental investigations and theoretical calculations demonstrate the synergistic effect of Hf and gradient Ti doping on the hematite for the promising H2O2 performance. Hf doping effectively improves the crystallinity of Fe2O3, which favors improving the charge transport and reducing the charge recombination. Gradient Ti doping inhibits the collapse of the nanorod structure, increases the specific surface area, and introduces a large number of active sites on the surface. Ti- and Hf-codoped Ti/Hf:Fe2O3 photoanode improves the kinetics of H2O2 generation, leading to the high selectivity for H2O2 production and suppression of O2 production. This work provides the importance of hematite-based photoanodes toward the regulation of competition reactions for H2O2 production.    

    

* Nickel as Electrocatalyst for CO(2) Reduction: Effect of Temperature, Potential, Partial Pressure, and Electrolyte Composition  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392578646
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-03-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00009")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392578646"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392578646"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392578646"))][Get cited by]]

OpenAlex: https://openalex.org/W4392578646 (Open access: True)
    
[[https://openalex.org/A5088127644][Rafaël E. Vos]], [[https://openalex.org/A5028485156][Marc T. M. Koper]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00009  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00009][pdf]])
     
No abstract    

    

* Cooperative Conformational Transitions Underpin the Activation Heat Capacity in the Temperature Dependence of Enzyme Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392597789
:TOPICS: Protein Structure Prediction and Analysis, Macromolecular Crystallography Techniques, Metabolic Engineering and Synthetic Biology
:PUBLICATION_DATE: 2024-03-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05584")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392597789"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392597789"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392597789"))][Get cited by]]

OpenAlex: https://openalex.org/W4392597789 (Open access: False)
    
[[https://openalex.org/A5044588414][Emma J. Walker]], [[https://openalex.org/A5022870690][Carlin J. Hamill]], [[https://openalex.org/A5072569899][Rory Crean]], [[https://openalex.org/A5081105337][Michael S. Connolly]], [[https://openalex.org/A5062691683][Annmaree K. Warrender]], [[https://openalex.org/A5007889613][Kirsty L. Kraakman]], [[https://openalex.org/A5029829379][Erica J. Prentice]], [[https://openalex.org/A5046090227][Alistair Steyn-Ross]], [[https://openalex.org/A5065890445][Moira L. Steyn-Ross]], [[https://openalex.org/A5081272550][Christopher R. Pudney]], [[https://openalex.org/A5021710523][Marc W. van der Kamp]], [[https://openalex.org/A5082123408][Louis A. Schipper]], [[https://openalex.org/A5044048108][Adrian J. Mulholland]], [[https://openalex.org/A5027997186][Vickery L. Arcus]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05584 
     
Many enzymes display non-Arrhenius behavior with curved Arrhenius plots in the absence of denaturation. There has been significant debate about the origin of this behavior and recently the role of the activation heat capacity (ΔCP⧧) has been widely discussed. If enzyme-catalyzed reactions occur with appreciable negative values of ΔCP⧧ (arising from narrowing of the conformational space along the reaction coordinate), then curved Arrhenius plots are a consequence. To investigate these phenomena in detail, we have collected high precision temperature-rate data over a wide temperature interval for a model glycosidase enzyme MalL, and a series of mutants that change the temperature-dependence of the enzyme-catalyzed rate. We use these data to test a range of models including macromolecular rate theory (MMRT) and an equilibrium model. In addition, we have performed extensive molecular dynamics (MD) simulations to characterize the conformational landscape traversed by MalL in the enzyme–substrate complex and an enzyme-transition state complex. We have crystallized the enzyme in a transition state-like conformation in the absence of a ligand and determined an X-ray crystal structure at very high resolution (1.10 Å). We show (using simulation) that this enzyme-transition state conformation has a more restricted conformational landscape than the wildtype enzyme. We coin the term “transition state-like conformation (TLC)” to apply to this state of the enzyme. Together, these results imply a cooperative conformational transition between an enzyme–substrate conformation (ES) and a transition-state-like conformation (TLC) that precedes the chemical step. We present a two-state model as an extension of MMRT (MMRT-2S) that describes the data along with a convenient approximation with linear temperature dependence of the activation heat capacity (MMRT-1L) that can be used where fewer data points are available. Our model rationalizes disparate behavior seen for MalL and previous results for a thermophilic alcohol dehydrogenase and is consistent with a raft of data for other enzymes. Our model can be used to characterize the conformational changes required for enzyme catalysis and provides insights into the role of cooperative conformational changes in transition state stabilization that are accompanied by changes in heat capacity for the system along the reaction coordinate. TLCs are likely to be of wide importance in understanding the temperature dependence of enzyme activity and other aspects of enzyme catalysis.    

    

* Enantioselective Directed Nickel-Catalyzed Three-Component Reductive Arylalkylation of Alkenes via the Carbometalation/Radical Cross-Coupling Sequence  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392600216
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Transition Metal-Catalyzed Cross-Coupling Reactions, Frustrated Lewis Pairs Chemistry
:PUBLICATION_DATE: 2024-03-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00477")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392600216"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392600216"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392600216"))][Get cited by]]

OpenAlex: https://openalex.org/W4392600216 (Open access: False)
    
[[https://openalex.org/A5008360561][Zhan Dong]], [[https://openalex.org/A5030097695][Changyu Xu]], [[https://openalex.org/A5016137233][Jianchao Chang]], [[https://openalex.org/A5083528390][Sitian Zhou]], [[https://openalex.org/A5030601090][Peipei Sun]], [[https://openalex.org/A5055664612][Yuqiang Li]], [[https://openalex.org/A5033735258][Liang‐An Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00477 
     
Asymmetric reductive three-component arylalkylation of alkenes via the radical relay method has been well established, while asymmetric arylalkylation via the migratory insertion strategy remains unexplored. We report enantioselective nickel-catalyzed cross-electrophile arylalkylation of alkenes with aryl- and alkyl halides via an integrated Heck carbometalation/radical cross-coupling sequence. This protocol employing a chiral Ni/PHOX catalytic system allows terminal and internal alkenes to successfully engage the arylalkylation with exquisite control of regio-, chemo-, and stereoselectivity. More importantly, this reductive arylalkylation undergoes regio- and enantioselective arylnickelation followed by radical cross-coupling via Csp3–Csp3 reductive elimination, thus exhibiting reverse regioselectivity to the radical relay method. Mild reaction conditions and exceptional functional group tolerance facilitate this method’s compatibility with bioactive motifs and the modular synthesis of biologically active compounds. The control experiments and density functional theory calculations provide insights into the mechanism and origin of regio- and stereoselectivity, and the hemilabile nature of the PHOX ligand is critical for achieving this enantioselective arylalkylation.    

    

* Glycyl Radical Enzymes Catalyzing the Dehydration of Two Isomers of N-Methyl-4-hydroxyproline  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392601584
:TOPICS: Biological and Synthetic Hydrogenases: Mechanisms and Applications, Dioxygen Activation at Metalloenzyme Active Sites, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-03-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392601584"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392601584"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392601584"))][Get cited by]]

OpenAlex: https://openalex.org/W4392601584 (Open access: False)
    
[[https://openalex.org/A5088147882][Li Jiang]], [[https://openalex.org/A5068243303][Yiqian Yang]], [[https://openalex.org/A5063237763][Lin Huang]], [[https://openalex.org/A5066342455][Yan Zhang]], [[https://openalex.org/A5002719628][Jingkun An]], [[https://openalex.org/A5042390620][Yu Zheng]], [[https://openalex.org/A5018409483][Yiwei Chen]], [[https://openalex.org/A5032159057][Yanhong Liu]], [[https://openalex.org/A5079155203][Jianhui Huang]], [[https://openalex.org/A5066292409][Ee Lui Ang]], [[https://openalex.org/A5088898460][Suwen Zhao]], [[https://openalex.org/A5014465828][Huimin Zhao]], [[https://openalex.org/A5013109310][Rong‐Zhen Liao]], [[https://openalex.org/A5013596658][Yifeng Wei]], [[https://openalex.org/A5066342455][Yan Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00216 
     
The various isomers of hydroxyproline (HP) are widely distributed in nature, serving as key components of structural proteins, while their quaternized betaine derivatives function as osmoprotectants in many organisms. Aerobic bacteria degrade HPs through a variety of well-studied mechanisms. Recent studies show that certain anaerobic bacteria degrade HPs through distinct mechanisms, involving the O2-sensitive glycyl radical enzymes (GREs) t4L-HP dehydratase (HypD) and t4D-HP C–N lyase (HplG). Here, we report the discovery of two more GREs, N-methyl c4L-HP dehydratase (HpyG) and N-methyl c4D-HP dehydratase (HpzG), which catalyze radical-mediated dehydration of the two N-methyl-c4HP enantiomers, while also displaying significant activities toward their unmethylated substrates. Both GREs are associated with homologues of pyrroline-5-carboxylate reductase, which catalyze reduction of their products N-methyl-pyrroline-5-carboxylate to form N-methyl-proline. Crystal structures of HpyG and HpzG in complex with their substrates revealed active site architectures distinct from that of HypD and provided insights into the mechanism of enantioselective radical-mediated dehydration. Our research further expands the repertoire of diverse chemical mechanisms involved in the bacterial metabolism of highly prevalent HP isomers and derivatives in the anaerobic biosphere.    

    

* Fundamental Insights on the Electrochemical Nitrogen Oxidation over Metal Oxides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392602509
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05307")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392602509"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392602509"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392602509"))][Get cited by]]

OpenAlex: https://openalex.org/W4392602509 (Open access: False)
    
[[https://openalex.org/A5040007989][J. V. P. Long]], [[https://openalex.org/A5027648567][Dong Luan]], [[https://openalex.org/A5089524415][Xihong Fu]], [[https://openalex.org/A5011392170][Huan Li]], [[https://openalex.org/A5051717534][Huijuan Jing]], [[https://openalex.org/A5004947752][Jianping Xiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05307 
     
Electrocatalytic nitrogen oxidation reaction (eN2OR) has emerged as a sustainable strategy for nitrogen fixation. In this work, density functional theory calculations were performed to rationalize the reaction mechanisms, activity, and selectivity of eN2OR on metal dioxides. The anatase (101), anatase (100), and rutile (110) surfaces were investigated to obtain more generalized insights. Based on the reaction phase diagram analysis, the thermochemical mechanisms were identified as most energetically favorable for N2 and *N2O oxidation, and a theoretical activity map was constructed for eN2OR, explaining well the experimental activity trend. Anatase PtO2(100) was screened as the most active catalyst for nitrate production, which could be covered by a monolayer of *OH under the reaction conditions according to the Pourbaix diagram. A method of electric field controlling constant potential was used to calculate the electrochemical barriers on anatase PtO2(100). It was found that the electrochemical barriers of the oxygen evolution reaction will increase with the decrease of potential, while the thermochemical limiting step of the eN2OR is insensitive to potential. Thus, the eN2OR selectivity can be improved by lowering the applied potential. This work unveils fundamental insights into eN2OR and provides a unified understanding to experiments.    

    

* Surface Decoration of Platinum Catalysts by ZrO2–x Nanoclusters for Durable Fuel Cell Applications  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392615762
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05297")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392615762"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392615762"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392615762"))][Get cited by]]

OpenAlex: https://openalex.org/W4392615762 (Open access: False)
    
[[https://openalex.org/A5087281203][Nagappan Ramaswamy]], [[https://openalex.org/A5029671045][Zixiao Shi]], [[https://openalex.org/A5047812570][Barr Zulevi]], [[https://openalex.org/A5013202937][Geoff McCool]], [[https://openalex.org/A5026378876][Nathan P. Mellott]], [[https://openalex.org/A5052342263][Anusorn Kongkanand]], [[https://openalex.org/A5085019775][Swami Kumaraguru]], [[https://openalex.org/A5041487145][Michele L. Ostraat]], [[https://openalex.org/A5042016235][David A. Muller]], [[https://openalex.org/A5002130574][Nancy N. Kariuki]], [[https://openalex.org/A5073046881][Deborah J. Myers]], [[https://openalex.org/A5010945358][A. Jeremy Kropf]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05297 
     
No abstract    

    

* Improved Oxygen Evolution Reaction Kinetics with Titanium Incorporated Nickel Ferrite for Efficient Anion Exchange Membrane Electrolysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392622761
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05761")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392622761"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392622761"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392622761"))][Get cited by]]

OpenAlex: https://openalex.org/W4392622761 (Open access: False)
    
[[https://openalex.org/A5035658742][Ki-Yong Yoon]], [[https://openalex.org/A5037937178][Kyung‐Bok Lee]], [[https://openalex.org/A5051461491][Jaehoon Jeong]], [[https://openalex.org/A5089096028][Myung‐Jun Kwak]], [[https://openalex.org/A5004040977][Dohyung Kim]], [[https://openalex.org/A5031554355][Hyunchul Roh]], [[https://openalex.org/A5041248271][Ji-Hoon Lee]], [[https://openalex.org/A5091482435][Sung Mook Choi]], [[https://openalex.org/A5022099174][Hosik Lee]], [[https://openalex.org/A5088908902][Juchan Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05761 
     
No abstract    

    

* Maximizing Thiophene–Sulfur Functional Groups in Carbon Catalysts for Highly Selective H2O2 Electrosynthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392645655
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00419")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392645655"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392645655"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392645655"))][Get cited by]]

OpenAlex: https://openalex.org/W4392645655 (Open access: False)
    
[[https://openalex.org/A5032588552][Rong-Hui Xie]], [[https://openalex.org/A5069312764][Chuanqi Cheng]], [[https://openalex.org/A5040727266][Ruguang Wang]], [[https://openalex.org/A5080694011][Jisi Li]], [[https://openalex.org/A5035642078][Erling Zhao]], [[https://openalex.org/A5024938458][Zhao Yang]], [[https://openalex.org/A5020877890][Yunlong Liu]], [[https://openalex.org/A5063185577][Jiaxin Guo]], [[https://openalex.org/A5034248727][Pengfei Yin]], [[https://openalex.org/A5063986077][Tao Ling]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00419 
     
No abstract    

    

* Pt/Fe-TiO2-Catalyzed Selective Carbonyl Hydrogenation: Fe-Promoted Hydrogen Spillover  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392649076
:TOPICS: Homogeneous Catalysis with Transition Metals, Catalytic Reduction of Nitro Compounds, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05478")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392649076"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392649076"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392649076"))][Get cited by]]

OpenAlex: https://openalex.org/W4392649076 (Open access: False)
    
[[https://openalex.org/A5070144089][Zhenchao Zhao]], [[https://openalex.org/A5081640064][Xiang Li]], [[https://openalex.org/A5021687717][Xin Liu]], [[https://openalex.org/A5049629115][Hongxia Gao]], [[https://openalex.org/A5017364023][Aiping Jia]], [[https://openalex.org/A5002873170][Songhai Xie]], [[https://openalex.org/A5000265322][Xiaojing Song]], [[https://openalex.org/A5004349988][Xiaoyan Liu]], [[https://openalex.org/A5016532688][Yang Fa]], [[https://openalex.org/A5004719521][Qihua Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05478 
     
No abstract    

    

* Siteselective and Enantiocomplementary C(sp3)–H Oxyfunctionalization for Synthesis of α-Hydroxy Acids  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392658327
:TOPICS: Catalytic C-H Amination Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00398")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392658327"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392658327"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392658327"))][Get cited by]]

OpenAlex: https://openalex.org/W4392658327 (Open access: False)
    
[[https://openalex.org/A5027467469][Xin Lian]], [[https://openalex.org/A5028161422][Yingle Mao]], [[https://openalex.org/A5018206556][Zunyun Fu]], [[https://openalex.org/A5030681379][Weijie Zhang]], [[https://openalex.org/A5058071351][Jia-Yan Chen]], [[https://openalex.org/A5092224606][Dan Zhuo]], [[https://openalex.org/A5075749706][Mingyue Zheng]], [[https://openalex.org/A5064221165][Jiunn‐Tzong Wu]], [[https://openalex.org/A5004928664][Cangsong Liao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00398 
     
Oxyfunctionalization of abundant carboxylic acids represents a direct approach to synthesizing α-hydroxy acids, which are valuable intermediates of various active pharmaceutical ingredients. Although ideal, the transformation is yet to be accomplished. Herein, enantiocomplementary C(sp3)–H oxyfunctionalization for the synthesis of α-hydroxy acids was realized by a cooperative strategy of substrate engineering, homologue screening and protein engineering of α-ketoglutarate-dependent nonheme iron aryloxyalkanoate dioxygenases. The reaction provided concise synthetic routes toward three types of 67 α-hydroxy acids with high efficiency and selectivity (yield up to 90% and ee up to >99%). The distinctive complementary reactions add to a growing repertoire of biocatalytic oxyfunctionalization reactions.    

    

* Expedient Synthesis of Axially and Centrally Chiral Diaryl Ethers via Cobalt-Catalyzed Photoreductive Desymmetrization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392682464
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Chiroptical Spectroscopy in Organic Compound Analysis, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00001")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392682464"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392682464"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392682464"))][Get cited by]]

OpenAlex: https://openalex.org/W4392682464 (Open access: False)
    
[[https://openalex.org/A5069332742][Yishou Wang]], [[https://openalex.org/A5051272053][Ruijie Mi]], [[https://openalex.org/A5082881031][Songjie Yu]], [[https://openalex.org/A5061667297][Xingwei Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00001 
     
No abstract    

    

* Recent Advances in Doping Strategies to Improve Electrocatalytic Hydrogen Evolution Performance of Molybdenum Disulfide  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392693992
:TOPICS: Electrocatalysis for Energy Conversion, Thin-Film Solar Cell Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05053")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392693992"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392693992"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392693992"))][Get cited by]]

OpenAlex: https://openalex.org/W4392693992 (Open access: False)
    
[[https://openalex.org/A5069543971][Yuehan Jia]], [[https://openalex.org/A5066097652][Yuchen Zhang]], [[https://openalex.org/A5042441491][Huibin Xu]], [[https://openalex.org/A5033673973][Jia Li]], [[https://openalex.org/A5007232564][Ming Gao]], [[https://openalex.org/A5010431648][Xiaotian Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05053 
     
The exhaustion of fossil fuels and resultant pollution issues have prompted the world to look to clean, nonpolluting hydrogen energy. The promising approach of the electrocatalytic hydrogen evolution reaction (HER) presents a solution for addressing energy and environmental challenges. Consequently, creating high-performance and cost-effective electrocatalysts is essential for the efficient decomposition of water. Molybdenum disulfide (MoS2) has emerged as the most promising among potential electrocatalysts to replace platinum. However, only the edge-site of MoS2 is active for HER due to the MoS2 semiconductive nature and large inactive basal planes. Doping various substances, which significantly improves HER activity, can enhance MoS2's physical and chemical properties. Our Review encapsulates the latest strategies and research advancements in choosing heteroatomic-doped MoS2 for hydrogen production. Various doping elements impart unique physical and chemical properties to MoS2. Specifically, doping with noble metals (e.g., Ag, Pt, Ru, Pd, Rh) and transition metals (e.g., Fe, V, Ni, Mn, Co, Zn, W), as well as codoping with multiple metal atoms (e.g., Cu-Pd, Pt-Te, Co-Nb, Ni-Co), can significantly enhance conductivity and introduce new active sites. These dopants are recognized for activating the basal plane of MoS2, thereby enhancing the HER activity. Furthermore, doping with nonmetallic elements (e.g., N, F, P, An, O) and their codoping combinations (e.g., O-P, N-F, Se-O), as well as the codoping of nonmetal and metal atoms (e.g., Co-Se, Co-P, N-Pt, Ru-O), is crucial for inducing phase conversions and improving stability. Each dopant contributes distinctively, either by enhancing the stability of MoS2, serving as a catalytic site, or broadening the pH range for effective HER. In this discussion, we further explore the current challenges and outlook of this promising area. Furthermore, we discuss existing challenges and promising guidelines for future research on the MoS2-based catalyst, offering advice to translation from laboratory research to large-scale industrial hydrogen production.    

    

* Solar-Driven Highly Effective Biomass-Derived Alcohols C–C Coupling Integrated with H2 Production by CdS Quantum Dots Modified Zn2In2S5 Nanosheets  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392697716
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05826")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392697716"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392697716"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392697716"))][Get cited by]]

OpenAlex: https://openalex.org/W4392697716 (Open access: False)
    
[[https://openalex.org/A5090435812][Zongyi Huang]], [[https://openalex.org/A5009066967][Pengfei Sun]], [[https://openalex.org/A5031458979][Huizhen Zhang]], [[https://openalex.org/A5087450865][Haikun Zhang]], [[https://openalex.org/A5063612918][Shuhong Zhang]], [[https://openalex.org/A5045122395][Zhou Chen]], [[https://openalex.org/A5062526485][Xiaodong Yi]], [[https://openalex.org/A5026338239][Shunji Xie]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05826 
     
No abstract    

    

* Confined Trinuclear Ru Sites in Phosphine-Incorporated Porous Organic Polymers for the Direct Synthesis of Alcohols from Reductive Hydroformylation of Alkenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392697742
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Chemistry and Applications of Metal-Organic Frameworks, Innovations in Organic Synthesis Reactions
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06221")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392697742"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392697742"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392697742"))][Get cited by]]

OpenAlex: https://openalex.org/W4392697742 (Open access: False)
    
[[https://openalex.org/A5014698881][Yuchuan Zhu]], [[https://openalex.org/A5078319852][Zhaozhan Wang]], [[https://openalex.org/A5066239611][Yuanjun Zhao]], [[https://openalex.org/A5001744159][Xin Zhou]], [[https://openalex.org/A5046692026][Yan Zhang]], [[https://openalex.org/A5000648383][Yong Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06221 
     
No abstract    

    

* Kinetics of Redox Half-Cycles on Bi2O3 for the Selective Catalytic Combustion of Hydrogen  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392697744
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Kinetic Analysis of Thermal Processes in Materials
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05585")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392697744"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392697744"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392697744"))][Get cited by]]

OpenAlex: https://openalex.org/W4392697744 (Open access: False)
    
[[https://openalex.org/A5025021152][Mark Jacob]], [[https://openalex.org/A5014100196][Huy Hoàng Nguyễn]], [[https://openalex.org/A5010884148][Matthew Neurock]], [[https://openalex.org/A5019481513][Aditya Bhan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05585 
     
No abstract    

    
