#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Tue Jan 14 01:17:54 2025

Found 29 results from 2025-01-07 to 2025-01-14
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Mechanistic Insights into Nitrile and Alkyne Covalent Inhibitors of the SARS-CoV-2 Main Protease  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406091634
:TOPICS: Computational Drug Discovery Methods, Click Chemistry and Applications, Synthesis and biological activity
:PUBLICATION_DATE: 2025-01-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06020")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406091634"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406091634"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406091634"))][Get cited by]]

OpenAlex: https://openalex.org/W4406091634 (Open access: False)
    
[[https://openalex.org/A5010387708][Ashim Nandi]], [[https://openalex.org/A5046676481][Mojgan Asadi]], [[https://openalex.org/A5001140607][Aoxuan Zhang]], [[https://openalex.org/A5110110180][Zhen T. Chu]], [[https://openalex.org/A5088665303][Arieh Warshel]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06020 
     
The treatment of SARS-CoV-2 can be accomplished by effective suppression of its 3CL protease (3CLpro), also known as the main protease (Mpro) and nonstructural protein 5 (nsp5). Covalent inhibitors can irreversibly and selectively disable the protease, particularly when they are highly exothermic. Herein we investigated the distinct kinetic behaviors exhibited by two covalently linked SARS-CoV-2 inhibitors. One of these inhibitors features a nitrile reactive group, while the other has this group replaced by an alkyne group, a less reactive electrophile. Our investigations involve the assessment of the free energy surfaces of the key feasible mechanisms: that is, direct and water-assisted mechanisms involved in the rate-determining proton-transfer nucleophilic attack step through the utilization of both ab initio and empirical valence bond (EVB) simulations. The calculated free energy profiles show that substituting the nitrile group with alkyne increases the chemical barrier but leads to very exothermic reaction energy and is an irreversible process as opposed to nitrile, which is moderately exothermic and reversible. We also examine the time dependence of IC50 inhibition by applying an innovative kinetic simulation approach, which is particularly important in studies of covalent inhibitors with a very exothermic bonding step. Our computational approach provides a good agreement between the calculated and observed values of the time dependence results for the nitrile and alkyne inhibitors. Our approach, which is rather unique in combining calculations of the chemical barriers and the binding energy is likely to be very effective in studies of the effectiveness of other covalent inhibitors related cases.    

    

* Inducing Cu Charge Redistribution by Modulating Proximity with Zr(OH)4 for Selective Synthesis of Imines and Secondary Amines with Stoichiometric Benzyl Alcohol and Nitrobenzene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406093746
:TOPICS: Asymmetric Hydrogenation and Catalysis, Nanomaterials for catalytic reactions, Catalysis for Biomass Conversion
:PUBLICATION_DATE: 2025-01-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05785")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406093746"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406093746"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406093746"))][Get cited by]]

OpenAlex: https://openalex.org/W4406093746 (Open access: False)
    
[[https://openalex.org/A5100649077][Jie Song]], [[https://openalex.org/A5100935179][Chunxia Che]], [[https://openalex.org/A5079399790][Yiwei Dai]], [[https://openalex.org/A5050284480][Jiaheng Qin]], [[https://openalex.org/A5101335462][Cong Yang]], [[https://openalex.org/A5086843496][Ziqiu Chen]], [[https://openalex.org/A5101650068][Kexin Ma]], [[https://openalex.org/A5041314524][Yuhui Han]], [[https://openalex.org/A5091099530][Yu Long]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05785 
     
The one-pot synthesis of amines from benzyl alcohol (BA) and nitrobenzene (NB) represents a step-economic method. However, reported works typically require more than 3 equiv of BA to complete the transfer hydrogenation of NB, and few studies can achieve selective synthesis of imines and secondary amines. In our previous work, Zr(OH)4 demonstrated both hydrogenation and dehydrogenation capabilities. Building on this, another component Cu was introduced to enhance its catalytic performance for catalyzing coupling reaction between stoichiometric BA and NB under a H2 atmosphere. The physical hybrid catalyst Cu + Zr(OH)4 selectively produced imines, while the supported catalyst Cu/Zr(OH)4 yielded secondary amines. Characterization and mechanism experiments revealed that modulating the proximity between Cu and Zr(OH)4 leads to (1) different adsorption abilities of the catalyst for N-benzylideneaniline (NBA) and (2) interactions between Zr(OH)4 and Cu in close contact, which stabilized the electronic structure of Cu forming more Cu+/Cu0 ion pairs with strong H2 activation ability. This work presents a catalyst design strategy and offers an approach for the selective preparation of N-benzylideneaniline and N-benzylaniline.    

    

* AuCu Nanodendrite for Enhancing Electrocatalytic Nitrate Reduction Applications via Two-stage Microfluidic Fabrication Strategy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406115611
:TOPICS: Ammonia Synthesis and Nitrogen Reduction, Caching and Content Delivery, Nanomaterials for catalytic reactions
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06559")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406115611"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406115611"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406115611"))][Get cited by]]

OpenAlex: https://openalex.org/W4406115611 (Open access: False)
    
[[https://openalex.org/A5101430705][Hengyuan Liu]], [[https://openalex.org/A5111006289][Yongqi Jia]], [[https://openalex.org/A5016306575][Xintong Huang]], [[https://openalex.org/A5078704875][Yingzhe Liu]], [[https://openalex.org/A5101776247][Qiang Yang]], [[https://openalex.org/A5100345056][Zhuo Chen]], [[https://openalex.org/A5034331950][Jianhong Xu]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06559 
     
No abstract    

    

* C(sp3)–H Carboxylation via Carbene/Photoredox Cooperative Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406119626
:TOPICS: Radical Photochemical Reactions, Catalytic C–H Functionalization Methods, Fluorine in Organic Chemistry
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06791")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406119626"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406119626"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406119626"))][Get cited by]]

OpenAlex: https://openalex.org/W4406119626 (Open access: False)
    
[[https://openalex.org/A5027788561][Cullen R. Schull]], [[https://openalex.org/A5101499747][Jing Cao]], [[https://openalex.org/A5096740287][Sophia R. Mitton-Fry]], [[https://openalex.org/A5108998163][Mara Mrksich]], [[https://openalex.org/A5041041100][Karl A. Scheidt]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06791 
     
No abstract    

    

* Efficient Synthesis of Glycodiversified Nucleoside Analogues by a Thermophilic Promiscuous Glycosyltransferase  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406124998
:TOPICS: Biochemical and Molecular Research, CRISPR and Genetic Engineering, Carbohydrate Chemistry and Synthesis
:PUBLICATION_DATE: 2025-01-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06506")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406124998"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406124998"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406124998"))][Get cited by]]

OpenAlex: https://openalex.org/W4406124998 (Open access: False)
    
[[https://openalex.org/A5054920721][Zhuqing Wang]], [[https://openalex.org/A5100462957][Jiahui Li]], [[https://openalex.org/A5062410995][Xueyun Wang]], [[https://openalex.org/A5060620859][Bo Jin]], [[https://openalex.org/A5084841107][Liwei Zhou]], [[https://openalex.org/A5102383496][Zili Zhao]], [[https://openalex.org/A5020709314][Meijia Gu]], [[https://openalex.org/A5036190073][Xuemin Song]], [[https://openalex.org/A5100684692][Jiahong Wang]], [[https://openalex.org/A5100781047][Zixin Deng]], [[https://openalex.org/A5025332853][Shuwen Wu]], [[https://openalex.org/A5100601494][Zhengyu Zhang]], [[https://openalex.org/A5100628712][Wenqing Chen]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06506 
     
3′-O-β-Glucosyl purine-related nucleosides are actinobacterial natural products with intricate structures, in which the glucosyl attachment to a nucleoside scaffold is governed by a glycosyltransferase. However, the molecular logic and engineered application of the glycosyltransferase have nearly remained unexplored. Here, we report the discovery, characterization, and exploitation of the thermophilic glycosyltransferase ScaGT. We uncover that ScaGT and its homologue AvpGT indicate prominent promiscuity against both sugar donors and a variety of nucleosides. Remarkably, we have solved the ternary complex structure of AvpGT, unveiling that it employs an unpreceded "twin-tyrosine gate" mechanism for substrate recognition and promiscuity, and we have also realized directed biosynthesis of diversified purine nucleoside analogues with unexpectedly enhanced titer via introduction of the external scaGT or avpGT. Moreover, we reveal that 3′-O-β-glucosyl ribavirin exhibits significantly enhanced antiviral activities, thereof showing its promising application potentials. Finally, we have further achieved the gram-scale production of 3′-O-β-glucosyl ribavirin by both biocatalytic and fermentation-feeding strategies. These findings expand the biochemical repertoire regarding glycosyltransferase reactions and provide the basis for rapid mining and rational engineering of more related glycosyltransferases toward synthetic biology applications.    

    

* Dynamic Catalysis Multiscale Simulations for Nonoxidative Coupling of Methane Using Light and Heat  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406125357
:TOPICS: Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science, Catalysts for Methane Reforming
:PUBLICATION_DATE: 2025-01-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04312")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406125357"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406125357"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406125357"))][Get cited by]]

OpenAlex: https://openalex.org/W4406125357 (Open access: True)
    
[[https://openalex.org/A5016788814][Juganta K. Roy]], [[https://openalex.org/A5076027956][Mona Abdelgaid]], [[https://openalex.org/A5041128128][Henrik Grönbeck]], [[https://openalex.org/A5066394844][Giannis Mpourmpakis]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c04312  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c04312?ref=article_openPDF][pdf]])
     
Methane (CH4) activation and conversion under mild reaction conditions are a great challenge for the chemical industry. Photocatalysis is attractive for activating inert C–H bonds of CH4 at room temperature. Specifically, photocatalytic nonoxidative coupling of CH4 (NOCM) is a promising process to produce ethane (C2-hydrocarbon) and H2. Different oxide-based photocatalysts have been used for room-temperature NOCM, and TiO2 is a potential photocatalyst with a bandgap that can capture photons in the UV region. However, a fundamental understanding of the NOCM mechanism on TiO2 is still missing. Herein, we apply multiscale modeling, combining density functional theory (DFT) calculations with kinetic Monte Carlo (kMC) simulations to investigate the photocatalytic NOCM on a rutile TiO2(110) surface. DFT calculations revealed that the photogenerated holes mediate the homolytic activation of CH4 via the formation of methyl radicals with an activation barrier that is 70% lower than that of the conventional thermocatalytic route. The generated methyl radicals further recombine to form ethane. The detailed reaction pathway energetics investigated with DFT-based kMC simulations revealed that ethane can be formed at 315.15 K, but the dissociated hydrogens poison the catalyst surface. Further thermocatalytic simulations revealed that increasing the temperature by thermal heating (ca. 690.15 K) facilitated H2 formation and catalyst regeneration. Importantly, we demonstrate how photo- and thermocatalytic modes can be combined, facilitating NOCM on TiO2 and a route to enable dynamic catalysis simulations through multiscale modeling, opening alternative avenues in computational catalyst discovery.    

    

* Modeling-Assisted Elucidation of the Organosolv Lignin Depolymerization: Lessons Learned from β-Ether Cleavage over Ni/C  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406125366
:TOPICS: Lignin and Wood Chemistry, Enzyme-mediated dye degradation, Catalysis and Hydrodesulfurization Studies
:PUBLICATION_DATE: 2025-01-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06058")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406125366"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406125366"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406125366"))][Get cited by]]

OpenAlex: https://openalex.org/W4406125366 (Open access: True)
    
[[https://openalex.org/A5092077882][Tina Ročnik Kozmelj]], [[https://openalex.org/A5025438862][Edita Jasiukaitytė-Grojzdek]], [[https://openalex.org/A5010167321][Matej Huš]], [[https://openalex.org/A5034183968][Miha Grilc]], [[https://openalex.org/A5015913196][Blaž Likozar]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06058  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c06058?ref=article_openPDF][pdf]])
     
No abstract    

    

* Pt–Co Single-Atom Alloy toward Furfural Hydrogenation–Rearrangement Tandem Reaction in the Aqueous Phase  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406125406
:TOPICS: Nanomaterials for catalytic reactions, Catalysis and Hydrodesulfurization Studies, Catalysis for Biomass Conversion
:PUBLICATION_DATE: 2025-01-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07190")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406125406"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406125406"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406125406"))][Get cited by]]

OpenAlex: https://openalex.org/W4406125406 (Open access: False)
    
[[https://openalex.org/A5101608723][Yuanjing Zhang]], [[https://openalex.org/A5053929645][Guanyi Zhang]], [[https://openalex.org/A5036334968][Quandong Hou]], [[https://openalex.org/A5108994830][Shiquan Zhao]], [[https://openalex.org/A5110969177][Si Wang]], [[https://openalex.org/A5023534280][Enze Xu]], [[https://openalex.org/A5100436007][Lei Wang]], [[https://openalex.org/A5100333386][Xin Zhang]], [[https://openalex.org/A5100448864][Feng Li]], [[https://openalex.org/A5017313282][Yusen Yang]], [[https://openalex.org/A5084055697][Min Wei]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c07190 
     
No abstract    

    

* Catalytic Conversion of Carbon Dioxide to Propylene Carbonate: Catalyst Design and Industrialization Progress  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406133755
:TOPICS: Carbon dioxide utilization in catalysis, CO2 Reduction Techniques and Catalysts, Carbon Dioxide Capture Technologies
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06638")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406133755"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406133755"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406133755"))][Get cited by]]

OpenAlex: https://openalex.org/W4406133755 (Open access: False)
    
[[https://openalex.org/A5100696276][Jun Wu]], [[https://openalex.org/A5071717370][Yaxuan Du]], [[https://openalex.org/A5016185530][Xiejun Wang]], [[https://openalex.org/A5101054008][Fuying Zhao]], [[https://openalex.org/A5091774768][Mingxuan Zhu]], [[https://openalex.org/A5089996806][Jing Ma]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06638 
     
Converting CO2 into valuable chemicals is an effective way to alleviate the high level of global CO2. The cycloaddition reaction of CO2 and propylene oxide (PO) has atomic economy and has the advantage of environmental friendliness compared with the traditional phosgene method of propylene carbonate (PC). Due to the chemical inertness of CO2, catalysts are needed to make the reaction proceed smoothly. Through rational design, a multifunctional catalyst that combines the activation sites and attack sites of PO and the adsorption sites of CO2 can be formed. At the same time, the use of harmful substances can be reduced by catalyst design, making the catalytic process more environmentally friendly. In this work, we discuss the research progress of the synthesis of PC from CO2 and PO. Starting from the reaction mechanism, the catalytic system of the reaction is summarized from the perspective of catalyst design. In homogeneous catalysts, the focus is on the effect of catalyst composition on catalytic performance. In heterogeneous catalysts, the focus is on the process of heterogenization (preparation methods), including supported, confined, and polymerized heterogeneous catalysts. In addition, the promising photocatalysis and biomass catalysis are especially introduced. Finally, in order to make the experimental results move toward industrial production, several problems existing in the industrialization are discussed, including production equipment, the influence of the CO2 source, and product/catalyst separation.    

    

* Dearomative 1,4-Difunctionalization of Non-Activated Arenes Enabled by Boryl Radical-Mediated Halogen-Atom Transfer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406134178
:TOPICS: Radical Photochemical Reactions, Catalytic C–H Functionalization Methods, Oxidative Organic Chemistry Reactions
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06628")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406134178"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406134178"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406134178"))][Get cited by]]

OpenAlex: https://openalex.org/W4406134178 (Open access: False)
    
[[https://openalex.org/A5102960771][Chengliang Deng]], [[https://openalex.org/A5068084181][Hao Wu]], [[https://openalex.org/A5100359830][Sheng Li]], [[https://openalex.org/A5100369852][Chen Li]], [[https://openalex.org/A5067983689][Xiaozu Liu]], [[https://openalex.org/A5101625362][Peijun Liu]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06628 
     
No abstract    

    

* Structural Insights into the N–N Bond-Formation Mechanism of the Heme-Dependent Piperazate Synthase KtzT  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406140994
:TOPICS: Enzyme Structure and Function, Biochemical and Molecular Research, Metal-Catalyzed Oxygenation Mechanisms
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06124")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406140994"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406140994"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406140994"))][Get cited by]]

OpenAlex: https://openalex.org/W4406140994 (Open access: False)
    
[[https://openalex.org/A5103428648][Yunyun Yang]], [[https://openalex.org/A5009011499][Yanling Li]], [[https://openalex.org/A5008396710][Licheng Yao]], [[https://openalex.org/A5043256081][Kaoshan Dai]], [[https://openalex.org/A5101163632][Xiaolong Fu]], [[https://openalex.org/A5112965800][Anming Ge]], [[https://openalex.org/A5101646732][Jian‐Wen Huang]], [[https://openalex.org/A5017609052][Rey‐Ting Guo]], [[https://openalex.org/A5100629596][Chun‐Chi Chen]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06124 
     
N–N bond formation plays a critical role in the synthesis of organic compounds and has broad applications in producing dyes, pharmaceuticals, and functional materials. However, N–N bond formation is challenging due to the nucleophilicity of nitrogen. Here, we determined the crystal structures of a heme-dependent enzyme, KtzT, which catalyzes the cyclization of l-N5-hydroxyornithine (l-N5-OH-Orn) to yield l-piperazate (l-piz) by linking two intramolecular nitrogen atoms. The complex structure of KtzTC197A with l-N5-OH-Orn reveals the substrate-interaction network, validated through mutagenesis experiments. Notably, the N5 atom of the substrate directly coordinates with the heme iron, precluding oxygen binding. This supports prior knowledge that KtzT catalyzes an oxygen-independent reaction. Intriguingly, the substrate exhibits two distinct conformations in our crystals. Based on the distance between the intramolecular nitrogen atoms and the product accommodation pose in the KtzTC197A/l-piz structure, conformation 2 is likely the productive pose, while the more extended conformation 1 may be a transient state facilitating entry into the catalytic tunnel. A potential catalytic pathway is also proposed. These findings offer structural insights for developing bio- and metal-catalyzed methods for N–N bond formation.    

    

* Homolytic versus Heterolytic Methane Hydroxylation in Copper Zeolites  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406141889
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, CO2 Reduction Techniques and Catalysts
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06246")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406141889"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406141889"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406141889"))][Get cited by]]

OpenAlex: https://openalex.org/W4406141889 (Open access: False)
    
[[https://openalex.org/A5017511441][Quan Manh Phung]], [[https://openalex.org/A5002069874][Takeshi Yanai]], [[https://openalex.org/A5079720980][Dieter Plessers]], [[https://openalex.org/A5045224053][Bert F. Sels]], [[https://openalex.org/A5020359281][Robert A. Schoonheydt]], [[https://openalex.org/A5043852315][Kristine Pierloot]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06246 
     
Oxygen-activated copper zeolites are capable of selectively converting methane to methanol at mild conditions, using a mono-oxygen bridged Cu(II) site [CuOCu]2+ as the active core. Based on previous DFT reports on the [CuOCu]2+ + CH4 reaction a general consensus was reached concerning the methane oxidation mechanism, where the rate-limiting step involves homolytic C–H bond cleavage to form [Cu(OH)Cu]2+ with a physisorbed •CH3. An alternative possibility, i.e. heterolytic H-abstraction passing through a four-center transition state to give an intermediate with a Cu–CH3 bond, was given consideration only in a few recent DFT studies, but was found less favorable than radical C–H activation. In this contribution methane-to-methanol conversion by Cu–CHA is investigated using large cluster models and employing either DFT, with an extensive list of 97 functionals, or the high-level correlated DMRG/cu(4)-CASPT2 method. In all cases homolytic C–H dissociation most favorably proceeds via a (S = 1) transition state TS1r, whereas the transition state of heterolytic H-abstraction, TS1n, has an (S = 0) ground state. The DMRG/cu(4)-CASPT2 results convincingly point to the heterolytic route, with a calculated activation enthalpy of 12.3 kcal/mol, as compared to 21.1 kcal/mol for homolytic C–H dissociation. In contrast, the results obtained with DFT are strongly functional dependent. Conform with previous DFT studies, homolytic H-abstraction is preferred by the B3LYP functional (almost exclusively used in previous cluster model studies). However, many other functionals, hybrid meta-GGA functionals in particular, agree with DMRG/cu(4)-CASPT2 on heterolytic C–H activation. The present results reopen the debate on the general validity of the radical rebound mechanism for methane hydroxylation by a [CuOCu]2+ core in copper zeolites and also highlight the need for caution when relying on a specific DFT functional to elucidate oxidation reaction mechanisms in metal-based catalytic systems.    

    

* Highly Efficient Rutile TiO2 Endowed by Electron-Capturing Center and Plasma Effect for Enhanced Solar Water Splitting  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406143470
:TOPICS: Solar-Powered Water Purification Methods, TiO2 Photocatalysis and Solar Cells, Advanced Photocatalysis Techniques
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04380")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406143470"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406143470"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406143470"))][Get cited by]]

OpenAlex: https://openalex.org/W4406143470 (Open access: False)
    
[[https://openalex.org/A5004458229][Xin Tao]], [[https://openalex.org/A5040762208][Yihai Zhou]], [[https://openalex.org/A5071718089][Meng Pan]], [[https://openalex.org/A5101710542][Shenghui Liu]], [[https://openalex.org/A5074136896][Yong Zhou]], [[https://openalex.org/A5069416690][Renchun Yang]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c04380 
     
No abstract    

    

* An Asynchronous, Concerted Mechanism for Cytochrome P450-Catalyzed Dehydrogenation: A Combined Deuterium Labeling and QM/MM Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406155163
:TOPICS: Chemical Reactions and Isotopes, Pharmacogenetics and Drug Metabolism, Epigenetics and DNA Methylation
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06278")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406155163"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406155163"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406155163"))][Get cited by]]

OpenAlex: https://openalex.org/W4406155163 (Open access: False)
    
[[https://openalex.org/A5029487868][Alicia M. Kirk]], [[https://openalex.org/A5021830895][Jeanette E. Stok]], [[https://openalex.org/A5020026543][Siew Hoon Wong]], [[https://openalex.org/A5018514154][Tom Coleman]], [[https://openalex.org/A5022601733][Victoria L. Challinor]], [[https://openalex.org/A5061456185][Joel N. Herring]], [[https://openalex.org/A5059039218][J.B. Bruning]], [[https://openalex.org/A5057319709][Paul V. Bernhardt]], [[https://openalex.org/A5027128497][Stephen G. Bell]], [[https://openalex.org/A5000188305][Elizabeth H. Krenske]], [[https://openalex.org/A5018549180][James J. De Voss]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06278 
     
Cytochromes P450 (P450s) commonly catalyze hydroxylation but can also be responsible for dehydrogenation reactions, important in drug metabolism and biosynthesis; the mechanism of the latter transformation remains poorly understood. The well-characterized bacterial CYP199A4 catalyzes both hydroxylation and dehydrogenation of p-alkylbenzoic acids and thus provides an ideal model system in which to investigate the mechanism of P450-catalyzed aliphatic dehydrogenation. Through use of enantioselectively deuterated probes, metabolite analysis, protein crystallography, molecular dynamics simulations and QM/MM (ONIOM) modeling, CYP199A4-catalyzed dehydrogenation was found to be completely enantioselective and postulated to occur through an asynchronous proton coupled electron transfer. No definitive evidence of a cationic intermediate was uncovered but instead, the positioning of the substrate was postulated to be key in directing the chemoselectivity of the reaction i.e., dehydrogenation versus hydroxylation. This knowledge could be exploited to control dehydrogenation in other P450s and helps explain the common occurrence of P450-desaturated drug metabolites alongside hydroxylated ones.    

    

* A New Look at Catalyst Surfaces at Work: Introducing Mixed Isotope Operando Infrared Spectroscopy (MIOIRS)  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406170106
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Catalysts for Methane Reforming
:PUBLICATION_DATE: 2025-01-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06308")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406170106"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406170106"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406170106"))][Get cited by]]

OpenAlex: https://openalex.org/W4406170106 (Open access: True)
    
[[https://openalex.org/A5004127604][Matteo Monai]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06308 
     
This Perspective focuses on the characterization of supported metal catalysts by operando and CO infrared (IR) spectroscopy. CO IR spectroscopy is a powerful technique for probing catalyst surfaces and is used to identify single-atom catalysts, estimate metal surface availability to the gas phase, and measure catalyst Lewis acidity. However, the interpretation of CO IR spectra on metal surfaces is not trivial and is influenced by dipole–dipole interactions among CO molecules at medium to high coverage. Such a phenomenon results in spectral distortions, such as intensity transfer among IR bands, the appearance of spurious bands, and shifts in band position. Dipole–dipole interactions were widely investigated and understood from the 1950s to 1990s, but the implications for operando spectroscopy have been seemingly overlooked in the literature, with a few exceptions. Inspired by seminal studies in the field, I propose here the use of mixed isotopic streams, such as diluted 13CO in 12CO, to reduce dipole coupling effects and retrieve more information from operando IR spectra in reactions involving CO, such as CO oxidation or hydrogenation reactions. Similarly, mixed 13CO2/12CO2 streams may be applied in CO2 hydrogenation, where adsorbed CO is commonly observed. The proposed name of the technique is Mixed Isotope Operando IR Spectroscopy, MIOIRS. In this Perspective, I will first summarize the nature of dipole–dipole interactions in adsorbed CO layers and their effects on CO IR spectra. Then, I will briefly describe how diluted isotopic mixtures of CO can partially break the coupling among adsorbates and reduce spectral distortion. In both sections, I will give a few showcases of the implications of vibrational coupling in the characterization of heterogeneous catalysts. Finally, I will discuss the possible implications of MIOIRS for the detection and quantification of defect and surface sites on metal nanoparticles, the characterization of bimetallic nanoparticles surfaces, and the kinetics of CO intermediates adsorbed on different active sites. Notably, MIOIRS may be expanded to other reactions in which adsorbates have strong permanent dipoles, such as in self-catalytic reduction for NOx abatement.    

    

* New Insights into the Roles of Surface and Lattice Hydrogen in Electrocatalytic Hydrogen Oxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406183003
:TOPICS: Electrocatalysts for Energy Conversion, Fuel Cells and Related Materials, Catalytic Processes in Materials Science
:PUBLICATION_DATE: 2025-01-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06133")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406183003"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406183003"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406183003"))][Get cited by]]

OpenAlex: https://openalex.org/W4406183003 (Open access: False)
    
[[https://openalex.org/A5054938102][Pengcheng Zhao]], [[https://openalex.org/A5101841629][Li Deng]], [[https://openalex.org/A5067485627][Chang Sun]], [[https://openalex.org/A5100674281][Xiang Li]], [[https://openalex.org/A5101433644][Xiaoyu Tian]], [[https://openalex.org/A5090464557][Zhuo Li]], [[https://openalex.org/A5035964409][Wenchao Sheng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06133 
     
No abstract    

    

* Decorating Cu Nanoparticles with Pd Clusters for Enhanced Nitrile Electro-Hydrogenation to Primary Amines by Effective Hydrogen Spillover  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406187801
:TOPICS: Nanomaterials for catalytic reactions, Ammonia Synthesis and Nitrogen Reduction, Advanced Photocatalysis Techniques
:PUBLICATION_DATE: 2025-01-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06206")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406187801"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406187801"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406187801"))][Get cited by]]

OpenAlex: https://openalex.org/W4406187801 (Open access: False)
    
[[https://openalex.org/A5101524851][Peipei Zhu]], [[https://openalex.org/A5103175383][Mingzhu Shi]], [[https://openalex.org/A5025223993][Bing Wu]], [[https://openalex.org/A5016300822][Xunfan Liao]], [[https://openalex.org/A5026978305][Mengning Ding]], [[https://openalex.org/A5088447996][Longbin Li]], [[https://openalex.org/A5079785501][Yiwang Chen]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06206 
     
The H2O-participating electrochemical hydrogenation (ECH) of benzonitrile represents a mild and efficient method for benzylamine synthesis, but the kinetics and Faraday efficiency are still limited. Herein, the developed Pd clusters dispersed Cu nanoparticles encapsulated in porous carbon (Pdn-Cu@C) achieves efficient ECH of benzonitrile (C6H5CN) to benzylamines (C6H5CH2NH2). In situ infrared spectroscopy and theoretical studies reveal that the Pd/Cu interface functions as the active site for active hydrogen (*H) generated by H2O dissociation, enhances the adsorption of C6H5CN, and weakens the adsorption of C6H5CH2NH2. Moreover, the Gibbs free energy barriers for *H spillover are much lower than that of *H self-coupling. As expected, Pdn-Cu@C exhibits efficient electro-hydrogenation of C6H5CN with the conversion of 97.42%, a high C6H5CH2NH2 selectivity of 97.21%, and Faradaic efficiency of 92.10% under a specific voltage. This finding blazes a feasible trail to suppress the competitive *H self-coupling and offers insights for multistep protonation ECH reactions.    

    

* Reactions of Surface Peroxides Contribute to Rates and Selectivities for C2H4 Epoxidation on Silver  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406196996
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, Advanced Photocatalysis Techniques
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06945")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406196996"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406196996"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406196996"))][Get cited by]]

OpenAlex: https://openalex.org/W4406196996 (Open access: True)
    
[[https://openalex.org/A5060751897][Ching‐Tien Chen]], [[https://openalex.org/A5039715757][Anna Sviripa]], [[https://openalex.org/A5061073595][Sandeep Verma]], [[https://openalex.org/A5034428503][Christopher Paolucci]], [[https://openalex.org/A5062793974][David W. Flaherty]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06945 
     
Partial oxidation of ethylene over silver catalysts produces more than 30 million metric tons of ethylene oxide (EO) annually. However, the form of active silver surfaces, reactive oxygen species, and dominant pathways of this chemical reaction remains controversial despite decades of research. Here, we use operando Raman spectroscopy and transient kinetic measurements to demonstrate that higher coverages of peroxide species, present only upon Ag oxide surfaces that form in situ, correlate with greater selectivities to EO. Ab initio calculations reveal that the reconstructed Ag oxides preferentially stabilize diatomic oxygen species (peroxide and superoxide) under relevant conditions, and these species contribute to the selective formation of EO. The dominant reaction pathways change with surface coverages; however, bound O2 consistently activates by reaction with C2H4, and products form subsequently through peroxo- and oxometallacycle surface complexes. Taken together, density functional theory calculations and kinetic and transient experimental measurements show that the formation of peroxide intermediates requires oxidation of the Ag surface (via subsurface oxygen), and an increase in surface peroxides coincides with the highest EO selectivity for the unpromoted Ag catalyst. These findings suggest that the promoters ubiquitous for ethylene epoxidation (e.g., chlorine, transition metals, and alkali metals) may succeed by oxidation of Ag and increasing coverages of peroxides at industrial conditions.    

    

* Pendant Catechol Group Improves the Performance of Iron Porphyrin CO2 Reduction Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406199451
:TOPICS: CO2 Reduction Techniques and Catalysts, Metal-Catalyzed Oxygenation Mechanisms, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05531")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406199451"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406199451"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406199451"))][Get cited by]]

OpenAlex: https://openalex.org/W4406199451 (Open access: False)
    
[[https://openalex.org/A5032471432][Ana Sonea]], [[https://openalex.org/A5000268359][Jeffrey J. Warren]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05531 
     
No abstract    

    

* Hydrogen-Assisted Dissociation of N2: Prevalence and Consequences for Ammonia Synthesis on Supported Ru Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406201945
:TOPICS: Ammonia Synthesis and Nitrogen Reduction, Caching and Content Delivery, Nanomaterials for catalytic reactions
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06966")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406201945"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406201945"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406201945"))][Get cited by]]

OpenAlex: https://openalex.org/W4406201945 (Open access: False)
    
[[https://openalex.org/A5102283975][Yukun Bai]], [[https://openalex.org/A5078898024][Yuanbao Zhang]], [[https://openalex.org/A5100781690][Jianhua Hu]], [[https://openalex.org/A5101444480][Li Jiang]], [[https://openalex.org/A5039790894][Shaolong Wan]], [[https://openalex.org/A5045372639][Jingdong Lin]], [[https://openalex.org/A5100424488][Yong Wang]], [[https://openalex.org/A5100328291][Shuai Wang]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06966 
     
Understanding the roles of coadsorbates on crowded catalytic surfaces is critical to optimizing industrial catalysts that are generally employed under high-pressure conditions. For ammonia synthesis from N2 hydrogenation (i.e., the Haber–Bosch process), it is well-known that supported Ru catalysts tend to be highly covered by atomic H species, while the impact of these H species on N2 activation is still under controversy. Herein, kinetic assessment, isotopic labeling experiments, and in situ spectroscopic characterization were combined to investigate the mechanism of ammonia synthesis on Ru/CeO2 catalysts with their structure tuned via thermal treatments. Our experimental approaches reveal that the dominant H* surface species limit the availability of vacant Ru sites for the widely proposed direct N2 dissociation route but instead lead to the prevalence of the H-assisted N2 dissociation route with the N–N cleavage in N2H* intermediates as a kinetically relevant step. Effects of Ru particle size and Ru–CeO2 interaction on the catalytic activity were kinetically deconvoluted in accordance with this H-assisted mechanism, unveiling their decisive influences on intrinsic activity and surface coverage, respectively. Driven by these fundamental insights gained from the working conditions, superior ammonia formation rates were achieved for supported Ru catalysts via optimizing Ru particle size and metal–support interaction collaboratively.    

    

* Manipulating the Adjacent Microenvironment of Atomically Dispersed FeN4 Sites via Cross-Link-Induced 3D Carbon Nest for Efficient Oxygen Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406210421
:TOPICS: Electrocatalysts for Energy Conversion, Advanced Photocatalysis Techniques, Fuel Cells and Related Materials
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06546")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406210421"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406210421"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406210421"))][Get cited by]]

OpenAlex: https://openalex.org/W4406210421 (Open access: False)
    
[[https://openalex.org/A5037064171][Tonghui Zhao]], [[https://openalex.org/A5102751314][Guangjin Wang]], [[https://openalex.org/A5101846257][Dongdong Xiao]], [[https://openalex.org/A5103217976][Min Young Song]], [[https://openalex.org/A5050705685][Yanmin Hu]], [[https://openalex.org/A5017926967][Tingting Chao]], [[https://openalex.org/A5100404467][Yapeng Li]], [[https://openalex.org/A5035786530][Zedong Zhang]], [[https://openalex.org/A5019388394][Yun Lu]], [[https://openalex.org/A5022215689][Mingxing Gong]], [[https://openalex.org/A5100611244][Tao Shen]], [[https://openalex.org/A5100780460][Deli Wang]], [[https://openalex.org/A5060906740][Huile Jin]], [[https://openalex.org/A5042841794][Dingsheng Wang]], [[https://openalex.org/A5100344483][Wei Chen]], [[https://openalex.org/A5100348455][Yadong Li]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06546 
     
Electronic perturbation induced by the microenvironment regulation adjacent to the FeN4 sites anchored on metal–N–C materials will accelerate its oxygen reduction reaction (ORR) kinetics. Herein, we report a fine-tuning in the charge configuration of FeN4 sites through a defect-rich N/S-doped carbon nest derived from the chemically cross-linked pyrrole/thiophene copolymer (CCPPT) with a sp3-hybridized cross-linker. Compared with the pyrrole/thiophene copolymer (PPT) without the cross-linker, CCPPT with a knitted three-dimensional (3D) network delivers higher defect density and ∼2-fold sulfur retention after pyrolysis. The structural characterizations combined with theoretical calculations suggest that adjacent vacancy defects (Cvd) and FeN4/S2 moiety together induce the charge redistribution of the FeN4 sites on the resultant CC-Fe1/NSC from CCPPT, reducing the adsorption strength of the oxygen-containing intermediates and the energy barrier of ORR. As expected, CC-Fe1/NSC shows an impressive half-wave potential of ∼0.91 V vs reversible hydrogen electrode (RHE), surpassing both the PPT-derived Fe1/NSC (0.88 V) and the commercial Pt/C (0.86 V). This work provides a distinctive path to manipulate the adjacent microenvironment of the single-atom catalysts toward ORR or even beyond.    

    

* Recent Advances in Catalytic Asymmetric Ketone Allylations and Their Applications  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406210431
:TOPICS: Asymmetric Synthesis and Catalysis, Asymmetric Hydrogenation and Catalysis, Synthetic Organic Chemistry Methods
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07194")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406210431"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406210431"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406210431"))][Get cited by]]

OpenAlex: https://openalex.org/W4406210431 (Open access: False)
    
[[https://openalex.org/A5115592240][Lie Wang]], [[https://openalex.org/A5044342332][Ruoshi Jin]], [[https://openalex.org/A5059049464][Yiyuan Peng]], [[https://openalex.org/A5005159477][Qiuping Ding]], [[https://openalex.org/A5080607495][Xing‐Ping Zeng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c07194 
     
No abstract    

    

* Brønsted Acid-Facilitated Thioetherification Cross-Coupling Reactions with Nickel and Visible Light  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406210452
:TOPICS: Sulfur-Based Synthesis Techniques, Radical Photochemical Reactions, Catalytic C–H Functionalization Methods
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06734")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406210452"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406210452"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406210452"))][Get cited by]]

OpenAlex: https://openalex.org/W4406210452 (Open access: True)
    
[[https://openalex.org/A5102946169][Maksim Nikitin]], [[https://openalex.org/A5040335780][Sándor B. Ötvös]], [[https://openalex.org/A5055386575][Indrajit Ghosh]], [[https://openalex.org/A5115671617][Maximilian Philipp]], [[https://openalex.org/A5045155782][Ruth M. Gschwind]], [[https://openalex.org/A5063134639][C. Oliver Kappe]], [[https://openalex.org/A5067475475][Burkhard Koenig]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06734 
     
Transition metal-catalyzed cross-coupling reactions are essential in modern organic synthesis, facilitating the rapid creation of complex molecular structures. Traditionally, these reactions rely heavily on conventional bases, with only a few exceptions reported. Recently, we developed adaptive dynamic homogeneous catalysis (AD-HoC), a method that enables C(sp2)–S cross-couplings without needing traditional ligands, bases, or additives. Given the growing demand for protocols compatible with acidic conditions in metal-catalyzed cross-couplings, we revisited AD-HoC to pioneer acid-facilitated transition metal-catalyzed thioetherification. Our method enables the swift synthesis of thioethers using nickel and visible light, with a substoichiometric amount of Brønsted acid acting as an enabler. NMR kinetic studies indicate that in the absence of acid, the system displays an induction period characteristic of autocatalysis. Introducing the acid as a simple additive eliminates this induction period and significantly accelerates the reaction. Moreover, the protocol has been successfully scaled to gram-level synthesis using continuous flow technology, achieving productivities of over 100 g per hour in a commercially available lab-scale photoreactor. This highlights the method's robustness and scalability, making it a powerful tool for large-scale applications.    

    

* Exceptionally Low-Coordinated Bismuth–Oxygen Vacancy Defect Clusters for Generating Black In2O3 Photocatalysts with Superb CO2 Reduction Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406217331
:TOPICS: Advanced Photocatalysis Techniques, Electronic and Structural Properties of Oxides, Copper-based nanomaterials and applications
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03491")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406217331"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406217331"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406217331"))][Get cited by]]

OpenAlex: https://openalex.org/W4406217331 (Open access: False)
    
[[https://openalex.org/A5018208592][Farzin Nekouei]], [[https://openalex.org/A5020585665][Christopher J. Pollock]], [[https://openalex.org/A5100399648][Tianyi Wang]], [[https://openalex.org/A5067645114][Zhong Zheng]], [[https://openalex.org/A5103114439][Yanzhao Zhang]], [[https://openalex.org/A5067924346][Zelio Fusco]], [[https://openalex.org/A5036060356][Huanyu Jin]], [[https://openalex.org/A5049687965][Thrinathreddy Ramireddy]], [[https://openalex.org/A5090264758][Ary Anggara Wibowo]], [[https://openalex.org/A5081363234][Teng Lü]], [[https://openalex.org/A5035776152][Shahram Nekouei]], [[https://openalex.org/A5076537001][Farzaneh Keshtpour]], [[https://openalex.org/A5070722227][Julien Langley]], [[https://openalex.org/A5063221300][Elwy H. Abdelkader]], [[https://openalex.org/A5033536093][Nicholas J. Cox]], [[https://openalex.org/A5074090421][Zongyou Yin]], [[https://openalex.org/A5074340406][Hieu T. Nguyen]], [[https://openalex.org/A5030881231][Alexey M. Glushenkov]], [[https://openalex.org/A5033971536][Siva Krishna Karuturi]], [[https://openalex.org/A5038590827][Zongwen Liu]], [[https://openalex.org/A5100454543][Wei Li]], [[https://openalex.org/A5100348631][Hao Li]], [[https://openalex.org/A5100603066][Yun Liu]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c03491 
     
No abstract    

    

* Electrocatalytic Enantioselective Tandem C–H Indolization toward Biindolyl Atropisomers: Reaction Development and Mechanistic Insight  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406218794
:TOPICS: Axial and Atropisomeric Chirality Synthesis, Catalytic C–H Functionalization Methods, Molecular spectroscopy and chirality
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06594")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406218794"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406218794"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406218794"))][Get cited by]]

OpenAlex: https://openalex.org/W4406218794 (Open access: False)
    
[[https://openalex.org/A5007641634][Zhi‐Huan Peng]], [[https://openalex.org/A5074407812][Ping Huang]], [[https://openalex.org/A5018210433][Ao-Long Li]], [[https://openalex.org/A5109707826][Mingkai Yang]], [[https://openalex.org/A5101696409][Zhikang Li]], [[https://openalex.org/A5100384450][Yuanyuan Li]], [[https://openalex.org/A5100568209][Qin Shi]], [[https://openalex.org/A5090758772][Jiating Cai]], [[https://openalex.org/A5028576201][Shengdong Wang]], [[https://openalex.org/A5035680195][Zhi Zhou]], [[https://openalex.org/A5089356883][Wei Yi]], [[https://openalex.org/A5038199259][Hui Gao]], [[https://openalex.org/A5001623372][Zhongyi Zeng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06594 
     
No abstract    

    

* Controlled Growth of Silver Nanoparticles by Metal–Support Interaction for Enhanced Tandem Catalytic Oxidation of HCHO at Low Temperature  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406219352
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Oxidation Reactions, nanoparticles nucleation surface interactions
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05879")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406219352"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406219352"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406219352"))][Get cited by]]

OpenAlex: https://openalex.org/W4406219352 (Open access: False)
    
[[https://openalex.org/A5026077466][Yue Ding]], [[https://openalex.org/A5056775642][Hui Wang]], [[https://openalex.org/A5032094982][Bin Huang]], [[https://openalex.org/A5101733311][Yuchun Chang]], [[https://openalex.org/A5038411990][Hua Yang]], [[https://openalex.org/A5017052045][Zhenping Qu]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05879 
     
No abstract    

    

* Lowering the Kinetic Barrier via the Synergistic Catalysis of N-CNTs Supported RhP Subnanoclusters and Confined Co Nanoparticles for Olefins Hydroformylation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406219626
:TOPICS: Catalysis and Hydrodesulfurization Studies, Nanomaterials for catalytic reactions, Organometallic Complex Synthesis and Catalysis
:PUBLICATION_DATE: 2025-01-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06822")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406219626"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406219626"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406219626"))][Get cited by]]

OpenAlex: https://openalex.org/W4406219626 (Open access: False)
    
[[https://openalex.org/A5109719922][Jiamei Wei]], [[https://openalex.org/A5059142323][Peng Gao]], [[https://openalex.org/A5100377078][Shen Wang]], [[https://openalex.org/A5091735030][Yue Ma]], [[https://openalex.org/A5001966929][Dong Cao]], [[https://openalex.org/A5006520119][Daojian Cheng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06822 
     
No abstract    

    

* Electrocatalytic CO2 Reduction to Methanol on Pt(111) Modified with a Pd Monolayer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406259351
:TOPICS: CO2 Reduction Techniques and Catalysts, Ammonia Synthesis and Nitrogen Reduction, Electrocatalysts for Energy Conversion
:PUBLICATION_DATE: 2025-01-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05442")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406259351"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406259351"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406259351"))][Get cited by]]

OpenAlex: https://openalex.org/W4406259351 (Open access: True)
    
[[https://openalex.org/A5036920326][Aleksandra Wawrzyniak]], [[https://openalex.org/A5028485156][Marc T. M. Koper]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c05442 
     
Electrochemical carbon dioxide (CO2) conversion to value-added, highly reduced chemicals such as methanol (CH3OH) is a promising possibility for producing renewable fuel and simultaneous CO2 recycling. However, this process remains a challenge, with only a few selective electrocatalysts known. Here, we present a study of a palladium monolayer on a platinum (111) single crystal (PdML/Pt(111)) as an electrocatalyst for CO2 conversion to CH3OH. A custom-made setup was employed in order to detect and quantify gaseous and liquid CO2 reduction products in sufficient concentrations despite the limitations of working with a single-crystalline electrode. Under ambient reaction conditions, a Faradaic efficiency (FE) of 1.5% at −0.9 V vs reversible hydrogen electrode (RHE) was obtained while using CO2 as the reactant. Other reaction intermediates, carbon monoxide (CO) and formaldehyde (HCHO) were subsequently used as reactants, leading to FEs of 1.8 and 2.5%, respectively, whereas formic acid is not reduced. The corresponding mechanism concluded from our work is compared to the literature. The electrocatalyst introduced here, with a highly well-defined structure for CO2 conversion to CH3OH, opens up possibilities for further catalytic explorations.    

    

* Access to Axially Chiral Biaryl Benzylamines via Ancestral Enzyme-Enabled Reductive Amination Desymmetrization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4406275770
:TOPICS: Axial and Atropisomeric Chirality Synthesis, Molecular spectroscopy and chirality, Alkaloids: synthesis and pharmacology
:PUBLICATION_DATE: 2025-01-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06881")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406275770"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406275770"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406275770"))][Get cited by]]

OpenAlex: https://openalex.org/W4406275770 (Open access: False)
    
[[https://openalex.org/A5091809743][W. Jim Zheng]], [[https://openalex.org/A5101960257][Xinxin Zhu]], [[https://openalex.org/A5111379905][Zheng Zhu]], [[https://openalex.org/A5066817609][Teng Yang]], [[https://openalex.org/A5108445153][Lian Zheng]], [[https://openalex.org/A5100638023][Rui Pan]], [[https://openalex.org/A5033002485][Shenlin Wang]], [[https://openalex.org/A5008977627][Lixin Zhang]], [[https://openalex.org/A5100340174][Qi Chen]], [[https://openalex.org/A5102188430][Jian-He Xu]], [[https://openalex.org/A5113822396][Yongtao Xie]], [[https://openalex.org/A5026230284][Gao‐Wei Zheng]], ACS Catalysis. None(None)] 2025. https://doi.org/10.1021/acscatal.4c06881 
     
Axially chiral biaryl benzylamines are present in numerous natural products, pharmaceuticals, chiral ligands, and catalysts. However, the direct catalytic synthesis of these functional molecules using a robust strategy remains a formidable challenge. Reductive amination desymmetrization of biaryl dialdehydes offers a powerful approach for the construction of axially chiral biaryl benzylamines but suffers from extensive undesirable side reactions. Herein, we engineered ancestral imine reductases to enable reductive amination desymmetrization of biaryl dialdehydes, allowing the construction of a wide range of axially chiral biaryl benzylamines with up to 99% conversion and 99% enantiomeric excess (ee). The ratio of the product to byproducts was up to 97:3 and over 90:10 in most cases. This work presents an alternative strategy for accessing axially chiral biaryl benzylamines and will stimulate the development of associated bioactive molecules and catalysts/ligands.    

    
