#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Fri Jun 21 01:07:54 2024

Found 29 results from 2024-06-14 to 2024-06-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Synergistic Catalytic Asymmetric Decarboxylative Mannich Reaction of β-Ketoacids with Acyclic α-Arylenamides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399605336
:TOPICS: Asymmetric Catalysis, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis
:PUBLICATION_DATE: 2024-06-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02238")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399605336"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399605336"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399605336"))][Get cited by]]

OpenAlex: https://openalex.org/W4399605336 (Open access: False)
    
[[https://openalex.org/A5088540180][Xiaodong Tang]], [[https://openalex.org/A5075524038][Yongjiang Hou]], [[https://openalex.org/A5086730309][Xing-Fa Tan]], [[https://openalex.org/A5069846711][Jing Nie]], [[https://openalex.org/A5033622056][Chi Wai Cheung]], [[https://openalex.org/A5040829256][Jun‐An Ma]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02238 
     
No abstract    

    

* Diversification of Pharmaceutical Manufacturing Processes: Taking the Plunge into the Non-PGM Catalyst Pool  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399609048
:TOPICS: Droplet Microfluidics Technology, Biodegradable Polymers as Biomaterials and Packaging, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-06-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01809")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399609048"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399609048"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399609048"))][Get cited by]]

OpenAlex: https://openalex.org/W4399609048 (Open access: False)
    
[[https://openalex.org/A5066014272][Hui Zhao]], [[https://openalex.org/A5088876286][Anne K. Ravn]], [[https://openalex.org/A5047992379][Michael C. Haibach]], [[https://openalex.org/A5045820274][Keary M. Engle]], [[https://openalex.org/A5030351313][Carin C. C. Johansson Seechurn]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01809 
     
No abstract    

    

* CO2-Assisted Dehydrogenation of Propane by Atomically Dispersed Pt on MXenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399610150
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Ammonia Synthesis and Electrocatalysis, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01473")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399610150"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399610150"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399610150"))][Get cited by]]

OpenAlex: https://openalex.org/W4399610150 (Open access: False)
    
[[https://openalex.org/A5049256333][Chih‐Peng Chu]], [[https://openalex.org/A5047815320][Baoyu Chen]], [[https://openalex.org/A5060106897][Yan He]], [[https://openalex.org/A5083832109][Guiyuan Jiang]], [[https://openalex.org/A5083689063][Xingying Lan]], [[https://openalex.org/A5070993582][Shenggang Li]], [[https://openalex.org/A5021675906][Changning Wu]], [[https://openalex.org/A5006923150][Daofan Cao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01473 
     
No abstract    

    

* Manipulating Activity and Chemoselectivity of a Benzaldehyde Lyase for Efficient Synthesis of α-Hydroxymethyl Ketones and One-Pot Enantio-Complementary Conversion to 1,2-Diols  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399631113
:TOPICS: Chemical Glycobiology and Therapeutic Applications, Peptide Synthesis and Drug Discovery, Asymmetric Catalysis
:PUBLICATION_DATE: 2024-06-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01804")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399631113"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399631113"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399631113"))][Get cited by]]

OpenAlex: https://openalex.org/W4399631113 (Open access: False)
    
[[https://openalex.org/A5021172073][Yifan Zhang]], [[https://openalex.org/A5040547872][Liang Yu]], [[https://openalex.org/A5073363679][Yangyang Chen]], [[https://openalex.org/A5010058813][Weidong Liu]], [[https://openalex.org/A5066780886][Qi Zhao]], [[https://openalex.org/A5050109962][Jinhui Feng]], [[https://openalex.org/A5089761282][Peiyuan Yao]], [[https://openalex.org/A5071884128][Qingping Wu]], [[https://openalex.org/A5007433138][Dunming Zhu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01804 
     
The α-hydroxymethyl ketone motif has been widely found in many pharmaceutically important molecules and used as a key intermediate in the synthesis of various fine chemicals and natural products. Hydroxymethylation of aldehydes with formaldehyde catalyzed by thiamine diphosphate (ThDP)-dependent enzymes is considered a highly valuable approach in terms of atom economics and sustainability, while low activity and chemoselectivity restricted its widespread application. In this study, a benzaldehyde lyase (BAL) with high activity and catalytic efficiency was acquired by enzyme screening and engineering, which catalyzed the hydroxymethylation of furfural at the concentration of 700 mM. Crystal structural analysis and molecular dynamics studies revealed that the activity and chemoselectivity of BAL were improved by reshaping the conformation of the substrate entrance tunnel. Furthermore, a one-pot concurrent enzymatic process involving BAL-catalyzed hydroxymethylation of aldehydes and subsequent asymmetric reduction with carbonyl reductase was developed, offering a highly efficient way to produce chiral 1,2-diols from simple aldehydes, with high ee values (97–99%) in good yields (52–97%). The significantly improved activity and chemoselectivity demonstrated the potential of the engineered BAL in the industrial production of α-hydroxymethyl ketones, which could readily enable the synthesis of other high-value-added chemicals from simple aldehydes and formaldehyde.    

    

* Deconvoluting Substrates, Support, and Temperature Effects on Leaching and Deactivation of Pd Catalysts: An In Situ Study in Flow  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399646842
:TOPICS: Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02028")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399646842"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399646842"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399646842"))][Get cited by]]

OpenAlex: https://openalex.org/W4399646842 (Open access: True)
    
[[https://openalex.org/A5051476157][Oliver J. Newton]], [[https://openalex.org/A5092558582][Matthew J. Takle]], [[https://openalex.org/A5081725515][Jeffery Richardson]], [[https://openalex.org/A5023116561][Klaus Hellgardt]], [[https://openalex.org/A5019713145][King Kuok Hii]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02028  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c02028][pdf]])
     
Leaching behavior of three different Pd heterogeneous catalysts (PdEnCat 30, FibreCat FC1001, and Pd/Al2O3) during the Heck reaction of iodobenzene and methyl acrylate, in the presence of triethylamine, was compared using a tandem flow reactor. While leaching was observed in all three cases, Pd/Al2O3 appeared to be the most robust, showing little/no leaching at ambient temperature. The leached Pd species also appear to display different catalytic activities. With a slight modification of the reactor, the leaching caused by individual components of the reaction mixture can be assessed separately. For the polymer-supported catalysts, triethylamine caused the largest amount of leaching, even at 30 °C. In contrast, the leaching from Pd/Al2O3 was observed only in the presence of iodobenzene at 90 °C. Variations in leaching behavior were ascribed to differences in Pd species and immobilization methods.    

    

* Solvent-Modulated Multiple Active Hydrogen Species in Furfural Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399663719
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Reduction of Nitro Compounds, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01364")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399663719"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399663719"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399663719"))][Get cited by]]

OpenAlex: https://openalex.org/W4399663719 (Open access: False)
    
[[https://openalex.org/A5073267812][Min Dong]], [[https://openalex.org/A5020646881][Sen Luan]], [[https://openalex.org/A5032819201][Yuxuan Wu]], [[https://openalex.org/A5088324347][Bin Zhang]], [[https://openalex.org/A5013035066][Ye Liu]], [[https://openalex.org/A5046040180][Huizhen Liu]], [[https://openalex.org/A5047044498][Buxing Han]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01364 
     
Unveiling the mechanism behind catalyst-dependent solvent effects for hydrogenation reactions is critically important yet presents significant challenges. In this work, focusing on furfural hydrogenation over Pd-based catalysts, we observe that distinct active hydrogen species present on Pd/MgO and Pd/TiO2 exhibit different responses to solvation environments, consequently influencing the selectivity in diverse solvents. Product distribution over Pd/MgO remains unaffected by the solvents used that tetrahydrofurfural (THFAL) emerged as the primary product in both organic solvents and water. Conversely, product distribution over Pd/TiO2 highly depends on the solvents; THFAL dominates in organic solvents, whereas furfural alcohol (FOL) becomes the primary product in water. The disparate selectivity upon alteration of supports and solvents is demonstrated by neural network-enhanced molecular dynamics simulations and microkinetic modeling. The active hydrogen species on the support are stabilized in water by water-mediated charge reconstructions, facilitating the hydrogenation of C═O to produce FOL. A spillover pathway where hydrogen species transfer to supports directly without involving hydrogen bond networks is dynamically preferred in both water and organic solvents.    

    

* Engineering Escherichia coli Pyruvate Metabolism to Generate Noncanonical Reducing Power  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399670296
:TOPICS: Macromolecular Crystallography Techniques, Metabolic Engineering and Synthetic Biology, ATP Synthase Function and Regulation
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02131")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399670296"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399670296"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399670296"))][Get cited by]]

OpenAlex: https://openalex.org/W4399670296 (Open access: False)
    
[[https://openalex.org/A5041733718][Derek Aspacio]], [[https://openalex.org/A5001893316][Emma Luu]], [[https://openalex.org/A5040263032][Suphanida Worakaensai]], [[https://openalex.org/A5022953852][Youtian Cui]], [[https://openalex.org/A5034082839][Sarah Maxel]], [[https://openalex.org/A5007342740][Edward J. King]], [[https://openalex.org/A5099128536][Raine Hagerty]], [[https://openalex.org/A5058618539][Alexander L. Chu]], [[https://openalex.org/A5099128537][Derek Minn]], [[https://openalex.org/A5076521371][Justin B. Siegel]], [[https://openalex.org/A5005490470][Han Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02131 
     
The future of biomanufacturing is dependent on rewiring biological systems to establish an alternative approach to our current chemical industries. However, a key limitation in biomanufacturing is that desired processes must rely on the same two redox cofactors as natural metabolism, nicotinamide adenine dinucleotide (phosphate) NAD(P)+, to shuttle electrons energy. Thus, competition of resources with natural reactions within host cells is nearly unavoidable. One strategy to overcome redox cofactor resource competition is the implementation of a third, noncanonical redox cofactor, such as nicotinamide mononucleotide (NMN+), which supports specific electron delivery to desired reactions. Here, we redesign the Escherichia coli pyruvate dehydrogenase multienzyme complex (PDHc) to specially utilize NMN+ by engineering its E3 subunit (Lpd). Through rational design, we discover a cofactor promiscuous variant Lpd Penta (G182R-I186T-M206E-E205W-I271L) with an ∼2500-fold improvement in NMN+ apparent turnover number. We tailor the enzyme to exclusively use NMN+ through computational design and construct Lpd Ortho (Penta-R292E-Q317L) with a 2.4 × 105-fold cofactor specificity improvement toward NMN+ compared to the wild type. Molecular simulation allowed tracking of the cofactor's alternative binding poses that emerge as the enzyme evolves, which was crucial to precisely guide engineering. We demonstrate that the engineered NMN+-specific PDHc functions in E. coli cells to sustain the life-essential pyruvate metabolism, in an NMN+-dependent manner. These results expand the available NMN+ toolkit to include the high flux and nearly irreversible reaction of PDHc as an insulated electron source.    

    

* Electrocatalysts for Inorganic and Organic Waste Nitrogen Conversion  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399670819
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01398")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399670819"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399670819"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399670819"))][Get cited by]]

OpenAlex: https://openalex.org/W4399670819 (Open access: True)
    
[[https://openalex.org/A5056482560][Danae A. Chipoco Haro]], [[https://openalex.org/A5073039652][Luisa Barrera]], [[https://openalex.org/A5011968024][Haldrian Iriawan]], [[https://openalex.org/A5055020562][Antonia Herzog]], [[https://openalex.org/A5087917712][Nianhan Tian]], [[https://openalex.org/A5036197373][Andrew J. Medford]], [[https://openalex.org/A5072645578][Yang Shao‐Horn]], [[https://openalex.org/A5020859438][Faisal M. Alamgir]], [[https://openalex.org/A5014967427][Marta C. Hatzell]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01398  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01398][pdf]])
     
Anthropogenic activities have disrupted the natural nitrogen cycle, increasing the level of nitrogen contaminants in water. Nitrogen contaminants are harmful to humans and the environment. This motivates research on advanced and decarbonized treatment technologies that are capable of removing or valorizing nitrogen waste found in water. In this context, the electrocatalytic conversion of inorganic- and organic-based nitrogen compounds has emerged as an important approach that is capable of upconverting waste nitrogen into valuable compounds. This approach differs from state-of-the-art wastewater treatment, which primarily converts inorganic nitrogen to dinitrogen, and organic nitrogen is sent to landfills. Here, we review recent efforts related to electrocatalytic conversion of inorganic- and organic-based nitrogen waste. Specifically, we detail the role that electrocatalyst design (alloys, defects, morphology, and faceting) plays in the promotion of high-activity and high-selectivity electrocatalysts. We also discuss the impact of wastewater constituents. Finally, we discuss the critical product analyses required to ensure that the reported performance is accurate.    

    

* Chemodivergent Tandem Hydroalkylation and Hydroalkenoxylation of Conjugated Enynes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399672490
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Gold Catalysis in Organic Synthesis, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02377")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399672490"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399672490"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399672490"))][Get cited by]]

OpenAlex: https://openalex.org/W4399672490 (Open access: False)
    
[[https://openalex.org/A5085804362][Bowei Xie]], [[https://openalex.org/A5042616865][Zhi‐Tao He]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02377 
     
Due to the instability and weak O-nucleophilicity of enol, carbonyl compounds prefer to function as C-nucleophiles instead of O-nucleophiles in the extensively studied transition metal-catalyzed hydrofunctionalizations of unsaturated bonds. The corresponding hydroalkenoxylation reaction has thus long been unexplored. Here, we describe a chemodivergent protocol for the challenging hydroalkenoxylation reactions. Dictated by the Pd catalyst bearing different ligands, both 5-exo-trig and 6-endo-trig hydroalkenoxylation processes are demonstrated to be feasible between the reaction of 1,3-enynes and ketoesters, and polysubstituted hydrofurans and hydropyrans are achieved in good yields and excellent chemoselectivities. In addition, the enantioselective hydroalkenoxylation reaction is also explored under an Rh catalyst in moderate efficiency but with high stereoselectivities. Mechanistic studies corroborate the designed tandem hydroalkylation and hydroalkenoxylation processes and uncover that a ligand-to-ligand hydrogen transfer process might be involved as the turnover-limiting step in the 5-exo-trig hydroalkenoxylation.    

    

* Defect-Mediated Cu–S Pair Active Sites Modulating Proton Supply to Facilitate Overall CO2 Photoreduction with H2O  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399677145
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02857")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399677145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399677145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399677145"))][Get cited by]]

OpenAlex: https://openalex.org/W4399677145 (Open access: False)
    
[[https://openalex.org/A5079800526][Heng Cao]], [[https://openalex.org/A5038541786][Xiaodi Zhu]], [[https://openalex.org/A5001720256][Jiawei Xue]], [[https://openalex.org/A5033862876][Ruyang Wang]], [[https://openalex.org/A5035134262][Jiusi Shang]], [[https://openalex.org/A5063955135][Peiyu Ma]], [[https://openalex.org/A5031824581][Chengyuan Liu]], [[https://openalex.org/A5086265105][Jun Bao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02857 
     
Precise design of photocatalysts with the demanded active surface structure for highly efficient and selective CO2 photoreduction is crucial but challenging. Here, by taking CdS as a prototype, single-atom Cu is successfully constructed on Cd-deficient CdS (Cd1–xS) to improve the performance of CO2 photoreduction with H2O as proton donor. The optimal Cu/Cd1–xS with Cd vacancies (VCd)-mediated single-atom Cu exhibits nearly 100% selective CO production and a more than three-fold higher CO evolution rate compared to that of Cd1–xS. Both experimental identification and DFT theoretical simulation unveil that the VCd-mediated single-atom Cu render Cu–S pair sites to function as more catalytically active sites for dissociating H2O and promoting the corresponding proton supply, which favors the subsequent protonation of the adsorbed CO2 at the adjacent Cd sites via the two-proton coupled two-electron transfer pathway. This work demonstrates the importance of modulating proton supply from the oxidation half-reaction for facilitating the overall CO2 photoreduction, advocating an overall-reaction perspective for the design and development of highly efficient and selective CO2 conversion photocatalysts.    

    

* Microkinetic Molecular Volcano Plots for Enhanced Catalyst Selectivity and Activity Predictions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399722609
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-06-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01175")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399722609"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399722609"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399722609"))][Get cited by]]

OpenAlex: https://openalex.org/W4399722609 (Open access: True)
    
[[https://openalex.org/A5033499565][Thanapat Worakul]], [[https://openalex.org/A5047408024][Rubén Laplaza]], [[https://openalex.org/A5091094440][Shubhajit Das]], [[https://openalex.org/A5076317766][Matthew D. Wodrich]], [[https://openalex.org/A5007563039][Clémence Corminbœuf]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01175  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01175][pdf]])
     
Molecular volcano plots, which facilitate the rapid prediction of the activity and selectivity of prospective catalysts, have emerged as powerful tools for computational catalysis. Here, we integrate microkinetic modeling into the volcano plot framework to develop "microkinetic molecular volcano plots". The resulting unified computational framework allows the influence of important reaction parameters, including temperature, reaction time, and concentration, to be quickly incorporated and more complex situations, such as off-cycle resting states and coupled catalytic cycles, to be tackled. Compared to previous generations of molecular volcanoes, these microkinetic counterparts offer a more comprehensive understanding of catalytic behavior, in which selectivity and product ratios can be explicitly determined by tracking the evolution of each product concentration over time. This is demonstrated by examining two case studies, rhodium-catalyzed hydroformylation and metal-catalyzed hydrosilylation, in which the unique insights provided by microkinetic modeling, as well as the ability to simultaneously screen catalysts and reaction conditions, are highlighted. To facilitate the construction of these plots/maps, we introduce mikimo, a Python program that seamlessly integrates with our previously developed automated volcano builder, volcanic.    

    

* Rational Design of Catalysts with Spinel Nanostructures for Thermal-Driven C1 Conversion  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399730295
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-06-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01138")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399730295"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399730295"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399730295"))][Get cited by]]

OpenAlex: https://openalex.org/W4399730295 (Open access: False)
    
[[https://openalex.org/A5091368247][Xiaoxue Han]], [[https://openalex.org/A5068233553][Dan Guo]], [[https://openalex.org/A5038325575][Yong Wang]], [[https://openalex.org/A5075318509][Shouying Huang]], [[https://openalex.org/A5041578170][Mei‐Yan Wang]], [[https://openalex.org/A5065841119][Yue Wang]], [[https://openalex.org/A5025279081][Maoshuai Li]], [[https://openalex.org/A5026063784][Shengping Wang]], [[https://openalex.org/A5043956105][Xinbin Ma]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01138 
     
The oriented conversion of C1 molecules including CO, CO2, CH4, and CH3OH has received great attention in the past few decades because of its essential role in sustainable chemistry. Spinel oxides with fine hardness, great thermal stability, and tunable chemical properties are advantageous catalysts or precursors in the activation of inert C1 molecules for the production of high-value-added chemicals. This review provides a thorough overview of the recent developments in spinel-structured nanocatalysts for the processes of thermal-driven C1 conversion, highlighting the spinel-structured advantages in deriving active metals, stabilizing metal cations, constructing adjacent synergic sites, and tuning oxygen vacancies. Finally, the potential challenges and development directions are discussed for the application of spinel-structured catalysts in thermal-driven C1 conversion reactions.    

    

* Atomically Dispersed Metal–Nitrogen–Carbon Catalysts for Electrochemical Nitrogen Transformations to Ammonia and Beyond  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399730682
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-06-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02717")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399730682"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399730682"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399730682"))][Get cited by]]

OpenAlex: https://openalex.org/W4399730682 (Open access: False)
    
[[https://openalex.org/A5021919589][Eamonn Murphy]], [[https://openalex.org/A5053518193][Yuanchao Liu]], [[https://openalex.org/A5010504692][Baiyu Sun]], [[https://openalex.org/A5025163492][Yuhan Chen]], [[https://openalex.org/A5035028180][Shengyuan Guo]], [[https://openalex.org/A5080704605][Plamen Atanassov]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02717 
     
No abstract    

    

* Theoretical Exploration of the Origin of Alkaline Dependence in the Oxidation of 5-Hydroxymethylfurfural Catalyzed by NiO2Hx  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399760359
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Desulfurization Technologies for Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-06-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00940")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399760359"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399760359"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399760359"))][Get cited by]]

OpenAlex: https://openalex.org/W4399760359 (Open access: False)
    
[[https://openalex.org/A5025818509][Si Wang]], [[https://openalex.org/A5038092047][Haisong Feng]], [[https://openalex.org/A5007836409][Tianyong Liu]], [[https://openalex.org/A5063733227][Yuan Deng]], [[https://openalex.org/A5026532264][Meng Zhang]], [[https://openalex.org/A5044492107][Sylvia Zhao]], [[https://openalex.org/A5044954885][Juan Han]], [[https://openalex.org/A5010723453][Xin Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00940 
     
Alkaline dependence is a common phenomenon in the electrochemical oxidation of biomass, and investigating the influence of alkalinity on the oxidation mechanisms is crucial for enhancing both the activity and the selectivity of biomass oxidation. Herein, we constructed five NiO2Hx catalysts under different alkaline environments (pH ≈ 9–13) and employed density functional theory methods to investigate the reaction mechanisms of the selective oxidation of the biomass platform molecule 5-hydroxymethylfurfural (HMF). The origin of alkaline dependence in HMF electrochemical oxidation was analyzed, and the results indicate that the catalyst alkalinity determines the oxidation pathway of HMF to 2,5-furandicarboxylic acid: under weak alkalinity (pH ≈ 9–11), the adsorption and activation of the alcohol group in HMF are more favorable, resulting in preferential oxidation of the alcohol group; under strong alkalinity (pH ≈ 11–13), the aldehyde group of HMF is more prone to adsorb and activate on the catalyst surface, resulting in a predominant aldehyde oxidation. With the increase in the alkalinity of NiO2Hx, there is a decrease of H atom coverage and an increase in the valence state of Ni, resulting in a transformation in the preferential oxidation pathway of HMF from the alcohol group to the aldehyde group as well as a transition in the oxidation mechanism from direct oxidation to indirect oxidation. NiOOH under moderately alkaline environment effectively reduces the Gibbs free energy change for C–H/O–H bonds cleavage, lowering the reaction energy. It significantly enhances the oxidation ability of alcohol and aldehyde groups, exhibiting the highest catalytic performance in the conversion of HMF to FDCA. The study not only provide a comprehensive explanation for the alkaline dependence of HMF oxidation but also offer guidance on how to rationally design catalysts for improving oxidative performance through alkalinity adjustments.    

    

* CeO2/Ni Inverse Catalyst as a Highly Active and Stable Ru-free Catalyst for Ammonia Decomposition  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399766265
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02313")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399766265"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399766265"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399766265"))][Get cited by]]

OpenAlex: https://openalex.org/W4399766265 (Open access: False)
    
[[https://openalex.org/A5022644703][Hongwang Liu]], [[https://openalex.org/A5053209536][Rongrong Zhang]], [[https://openalex.org/A5047101692][Sibao Liu]], [[https://openalex.org/A5018069202][Guozhu Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02313 
     
Catalytic ammonia decomposition is an efficient way to produce clean hydrogen, but the design of ammonia decomposition catalysts is limited by the high cost of noble metals and the low activity. Herein, we report a CeO2/Ni inverse catalyst prepared by the coprecipitation method, exhibiting a high hydrogen production rate of 79.6 mmol gcat–1 min–1 at 500 °C, which is better than traditional supported Ni-based catalysts and even many of the Ru-based catalysts reported in the literature. In addition, this inverse catalyst showed catalytic stability for 100 h continuous reaction at 600 °C. Systematic catalyst characterizations revealed that the inverse CeO2/Ni catalyst exhibits small cerium oxide nanoparticle islands supported on the Ni nanoparticles. The inverse structure confers enhanced metal–support interaction and abundant Ni-CeO2 interface sites, which facilitate the generation of highly concentrated oxygen vacancies and abundant electron-rich Ni atoms at the interface under reduction conditions. These features endow the CeO2/Ni inverse configuration possessing increased number of adsorption sites for NH3 molecules, enhancing N–H bond breaking, and facilitating the recombination desorption of N and H adatoms, thereby accelerating the reaction rate. This work highlights the significance of constructing a rational configuration between the active metal nanoparticles and oxides to enhance the catalytic efficiency for NH3 decomposition.    

    

* Ultrafast Electronic and Vibrational Spectroscopy of Electrochemical Transformations on a Metal-Oxide Surface during Oxygen Evolution Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399767385
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Quantum Coherence in Photosynthesis and Aqueous Systems
:PUBLICATION_DATE: 2024-06-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05931")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399767385"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399767385"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399767385"))][Get cited by]]

OpenAlex: https://openalex.org/W4399767385 (Open access: False)
    
[[https://openalex.org/A5066895569][Tanja Cuk]], [[https://openalex.org/A5012639606][Michael Paolino]], [[https://openalex.org/A5082056990][Suryansh Singh]], [[https://openalex.org/A5060242817][James J. P. Stewart]], [[https://openalex.org/A5054037567][Xihan Chen]], [[https://openalex.org/A5088201110][Ilya Vinogradov]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05931 
     
Oxygen evolution catalysis fuels the planet through photosynthesis and is a primary means for hydrogen storage in energy technologies. Yet the detection of intermediates of the oxygen evolution reaction (OER) central to the catalytic mechanism has been an ongoing challenge. This tutorial and minireview covers the relevance of ultrafast electronic and vibrational spectroscopy of the electrochemical transformations of a metal-oxide surface undergoing OER. Here, we highlight the ultrafast trigger and probes of the electron-doped SrTiO3/electrolyte as the primary example in which light probes across the electromagnetic spectrum have detected intermediate forms. We compare the results to other early transition-metal-oxide surfaces when they exist for select probes and longer timescales. The first part covers how the catalytic reaction is triggered by ultrafast light pulses, describing the semiconducting depletion and electrolyte Helmholtz layers. The second part covers the detection of the intermediates that occur upon electron and proton transfer from an adsorbed water species by transient spectroscopy. Their detection by a broadband visible probe, a mid-infrared evanescent wave, and a coherent acoustic wave respectively targets electronic states, vibrational levels, and lattice strain respectively. One of the aims is a tutorial on how these measurements are made and to what extent they allow for the interpretation of experimental spectra by intermediate configurations predicted by theory. Another aim is to describe what these experiments directly recommend in terms of future efforts to visualize the OER intermediates and their dynamics.    

    

* Rational Control of Oxygen Vacancy Density in In2O3 to Boost Methanol Synthesis from CO2 Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399771091
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-06-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01929")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399771091"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399771091"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399771091"))][Get cited by]]

OpenAlex: https://openalex.org/W4399771091 (Open access: False)
    
[[https://openalex.org/A5073634925][Wenhang Wang]], [[https://openalex.org/A5038223483][Keke Huo]], [[https://openalex.org/A5017535932][Yang Wang]], [[https://openalex.org/A5009524011][Jinghao Xie]], [[https://openalex.org/A5039749395][Xu Sun]], [[https://openalex.org/A5028463150][Yingluo He]], [[https://openalex.org/A5091917438][Meng Li]], [[https://openalex.org/A5019017874][Jie Liang]], [[https://openalex.org/A5053277179][Xinhua Gao]], [[https://openalex.org/A5067123324][Guohui Yang]], [[https://openalex.org/A5002152678][Si‐Min Lin]], [[https://openalex.org/A5082279771][Fuyang Cao]], [[https://openalex.org/A5052437298][Jian Hu]], [[https://openalex.org/A5063554744][Mingbo Wu]], [[https://openalex.org/A5054090836][Noritatsu Tsubaki]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01929 
     
Oxygen vacancies (Ov) in reducible metal oxides are the vital active sites for methanol synthesis via a CO2 hydrogenation technology. However, the relationship between the density of Ov and the methanol synthesis performance is still ambiguous, and it still shows a lack of a versatile strategy to precisely tailor the number of Ov. In this study, with In2O3 as a representatively catalytic component, the density functional theory computation confirms that the Ov property, especially Ov density, is pivotal to enhancing methanol selectivity of CO2 hydrogenation by suppressing the undesirable reverse water–gas shift reaction for CO formation, which is attributed to the unique electronic density of In atoms around Ov. To verify the theoretical results, we report a protocol to optimize the concentration of Ov on In2O3 by sequential carbonization and oxidation (SCO) treatments of In-based metal–organic frameworks, during which the consumption of carbon species and the structural reconstruction of the In2O3 crystal regulated the particle size and Ov concentration of In2O3 by varying the oxidation temperature. The In2O3-5 catalyst carbonized and oxidized at 500 °C exhibits good methanol selectivity (72.3%) at a CO2 conversion of 9.9% under 330 °C, 3 MPa, and high space velocity of 12,000 L–1 kgcat–1 h–1. Multiple in situ characterizations clarify that the proposed Ov property regulating the SCO strategy is convenient to boost methanol synthesis by altering the CO2 hydrogenation process to the HCOO* intermediate-dominated pathway. Our work provides the catalyst design strategy and will shed light on the rational design of reducible metal oxide-based catalysts with a controllable Ov density.    

    

* One-Step Hydrothermal Synthesis of Sn-Doped Sb2Se3 for Solar Hydrogen Production  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399771389
:TOPICS: Thin-Film Solar Cell Technology, Formation and Properties of Nanocrystals and Nanostructures, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-06-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01762")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399771389"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399771389"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399771389"))][Get cited by]]

OpenAlex: https://openalex.org/W4399771389 (Open access: True)
    
[[https://openalex.org/A5037685122][Zhenbin Wang]], [[https://openalex.org/A5044053298][Sanghyun Bae]], [[https://openalex.org/A5017423404][Miloš Baljozović]], [[https://openalex.org/A5056185071][Pardis Adams]], [[https://openalex.org/A5017830410][David Yong]], [[https://openalex.org/A5009532756][Erin Service]], [[https://openalex.org/A5027849717][Thomas Moehl]], [[https://openalex.org/A5000887480][Wenzhe Niu]], [[https://openalex.org/A5024625560][S. David Tilley]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01762  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01762][pdf]])
     
No abstract    

    

* Impact of Adsorbed CO on the Conversion of CO2 to Ethylene on 4,5-Dicyanoimidazole Coordinated Cu  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399773474
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-06-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02042")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399773474"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399773474"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399773474"))][Get cited by]]

OpenAlex: https://openalex.org/W4399773474 (Open access: False)
    
[[https://openalex.org/A5058003997][Yuhang Jiang]], [[https://openalex.org/A5034972191][Yating Wang]], [[https://openalex.org/A5017541508][Wei Chen]], [[https://openalex.org/A5035363465][Rongzhen Chen]], [[https://openalex.org/A5091738441][Yu Hang Li]], [[https://openalex.org/A5009144836][Chunzhong Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02042 
     
Upgrading carbon dioxide (CO2) into multicarbon products by using renewable electricity provides a pathway to producing fuel and chemicals. In fact, input CO2 in alkaline and neutral reactors forms carbonates with hydroxide, resulting in lower carbon efficiency, so acidic electrolytes are considered as a strategy to solve this problem. However, hydrogen evolution reaction competition and lower Faradaic efficiency (FE) of the target product limit the development of acidic electrolytes. Here, we report an accessible composite catalyst of a commercial copper (Cu) powder modified by a small molecule 4,5-dicyanoimidazole (DCI) that can maintain a high FE for ethylene (C2H4) even in strong acids with pH ≤ 1. We achieve CO2 electroreduction on the DCI–Cu catalyst with an FE of 57% toward C2H4 at a current density of 200 mA cm–2 at pH 1. By in situ attenuated total reflectance surface-enhanced infrared absorption spectroscopy measurements, compressed bonding of the *CO intermediate has been observed, which leads to more C–C bonding. The density functional theory calculation results further prove that the adsorbed *CO intermediates on the DCI–Cu catalyst are closer to the reaction sites. Unfortunately, this catalyst still requires improvement in terms of long-term operation. However, we anticipate that this may be generalized to enable molecular strategies to complement metal-based catalysts designed for strong acidic conditions by stabilizing intermediates.    

    

* QM/MM MD Study on the Reaction Mechanism of Thymidine Phosphorylation Catalyzed by the Enzyme Thermotoga maritima Thymidine Kinase 1  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399783848
:TOPICS: Nucleotide Metabolism and Enzyme Regulation, The p53 Signaling Network in Cancer Research, Macromolecular Crystallography Techniques
:PUBLICATION_DATE: 2024-06-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01867")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399783848"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399783848"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399783848"))][Get cited by]]

OpenAlex: https://openalex.org/W4399783848 (Open access: True)
    
[[https://openalex.org/A5052238101][Samanta Makurat]], [[https://openalex.org/A5035051171][Rui P. P. Neves]], [[https://openalex.org/A5048088473][Maria J. Ramos]], [[https://openalex.org/A5058691299][Janusz Rak]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01867  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01867][pdf]])
     
Here, we report mechanistic studies on type II thymidine kinase, Thermotoga maritima TmTK, aiming to predict barriers for the enzyme-catalyzed reaction. Extensive umbrella sampling QM/MM MD simulations (PBE/GPW/DZVP-GTH-PBE:AMBER) resulted in a free energy barrier for the phosphorylation reaction's rate-limiting step of 16.6 kcal·mol–1, which is in an excellent agreement with the experimentally reported value. An atomistic picture provided by our simulations reveals that the reaction follows a concerted, dissociative SN2 reaction mechanism in which the 5′-oxygen of the ribose moiety in thymidine is phosphorylated by the γ-phosphate of ATP, while assisted by an asynchronous deprotonation of the 5′-hydroxyl by a GLU84 base. The reaction was calculated to be endergonic, with a reaction free energy of 10.8 kcal·mol–1, and it can be followed by low-barrier processes that promote the unbinding of the phosphorylated thymidine product, namely, the deprotonation of the GLU84 by the thymidine-phosphate that is accompanied by a weaker binding of the product to the Mg2+ ion.    

    

* Bottom-Up Synthesis of Platinum Dual-Atom Catalysts on Cerium Oxide  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399783895
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-06-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01840")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399783895"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399783895"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399783895"))][Get cited by]]

OpenAlex: https://openalex.org/W4399783895 (Open access: True)
    
[[https://openalex.org/A5006779485][Martijn J. Mekkering]], [[https://openalex.org/A5059492051][Petrus C. M. Laan]], [[https://openalex.org/A5072929835][Alessandro Troglia]], [[https://openalex.org/A5046319779][Roland Bliem]], [[https://openalex.org/A5086866413][Ali Can Kızılkaya]], [[https://openalex.org/A5077972241][Gadi Rothenberg]], [[https://openalex.org/A5060681396][Ning Yan]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01840  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01840][pdf]])
     
No abstract    

    

* Formation of (Rh–Fe)–FeOx Complex Sites Enables Methanol Synthesis from CO2  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399803165
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-06-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00339")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399803165"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399803165"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399803165"))][Get cited by]]

OpenAlex: https://openalex.org/W4399803165 (Open access: False)
    
[[https://openalex.org/A5042430533][Yifeng Zhu]], [[https://openalex.org/A5071348910][Ran Luo]], [[https://openalex.org/A5003811344][Honghong Shi]], [[https://openalex.org/A5076133961][Katherine Koh]], [[https://openalex.org/A5059318117][Libor Kovařík]], [[https://openalex.org/A5069926157][John L. Fulton]], [[https://openalex.org/A5057378771][Johannes A. Lercher]], [[https://openalex.org/A5084194253][Zhi‐Jian Zhao]], [[https://openalex.org/A5047030779][Jinlong Gong]], [[https://openalex.org/A5073071572][Oliver Y. Gutiérrez]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00339 
     
We addressed the challenges of designing catalysts for selective CO2 hydrogenation by incorporating Fe oxide species onto Rh nanoparticles. Nanoscopic FeOx domains created a "reverse catalyst" structure (i.e., a metal oxide supported on a metal) that increased the density of interfacial sites compared to traditional supported catalysts. The contact between the metal nanoparticle and the oxide overlayer induced the formation of a surface Rh–Fe alloy that stabilized methoxy groups while suppressing hydrogenolysis to methane. Sites at FeOx–metal interfaces interact with CO2 much stronger than sites on metal surfaces, show larger energy barriers to cleave the C–O bonds, and offer a barrierless pathway for the hydrogenation of methoxy species to methanol. Consequently, the multifunctional sites over FeOx/Rh–Fe catalysts highlight and meet the requirements of a selective methanol catalyst: strong interaction with CO2 to ensure a high density of transition states, metal sites to activate and make hydrogen available to surface intermediates, and high energy barriers for C–O bond cleavage to form carbides. These synthetic and catalytic chemistries, demonstrated for Rh–Fe–FeOx interfaces, enable us to overcome the limitations to the design of methanol production catalysts.    

    

* Crucial Effect of Subsurface Hydrogen on Low-Barrier Hydrogenation and Keto–Enol Tautomerization of Carbonyl Compounds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399804824
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-06-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01441")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399804824"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399804824"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399804824"))][Get cited by]]

OpenAlex: https://openalex.org/W4399804824 (Open access: True)
    
[[https://openalex.org/A5084069145][Philipp A. Haugg]], [[https://openalex.org/A5024876786][Jan Smyczek]], [[https://openalex.org/A5016097713][P. Hubert]], [[https://openalex.org/A5009247208][Carsten Schröder]], [[https://openalex.org/A5057749007][Swetlana Schauermann]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01441  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01441][pdf]])
     
Hydrogenation of a normally highly stable carbonyl group is an important step in many technological applications, including emerging molecular systems for reversible hydrogen storage. In this report, we present a mechanistic study of low-temperature hydrogenation of carbonyl compounds over Pd, proceeding via keto–enol tautomerization in the first step. The specific focus of this study is on the role of subsurface hydrogen absorbed in the nearest region below the Pd surface. Employing a combination of real space microscopic and operando spectroscopic surface sensitive techniques, as well as molecular beams, we show that subsurface H plays a crucial role in both keto–enol tautomerization and hydrogenation of the carbonyl compound acetylpyridine on the Pd(111) model catalyst. We demonstrate that a growing amount of subsurface H results in an enhanced abundance of enol species followed by hydrogenation already at cryogenic temperatures. In contrast, if only H adsorbed on the surface is present, no hydrogenation occurs, and substantially smaller amounts of enol species are formed. The population of subsurface H is also accompanied by a change in the mechanism of enol stabilization via hydrogen bonding: while in the presence of subsurface H specific enol-containing dimers are predominately formed, which strongly interact via the enol-acetyl or enol–enol groups, in the absence of subsurface H, a weaker interaction between the adsorbates occurs, which is realized mainly via the enol group of one molecule with a H atom belonging to the pyridine ring of the neighboring adsorbate. The observed strongly correlated behavior between the growing concentration of subsurface H, enhanced abundance of the enol form of acetylpyridine, and the onset of hydrogenation prove the crucial role of subsurface H species in the low-barrier hydrogenation pathway of carbonyl compounds. The obtained atomistic-level insights offer a prospect of controllable low-temperature hydrogenation of carbonyl compounds by tuning the abundance of subsurface H, which has not been available so far.    

    

* Cobalt(II) Nanoclusters Incorporated in Ordered Mesoporous Al2O3 for Stable and Coke-Resistant Propane Dehydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399806935
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-06-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02067")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399806935"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399806935"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399806935"))][Get cited by]]

OpenAlex: https://openalex.org/W4399806935 (Open access: True)
    
[[https://openalex.org/A5027684063][Fabian Ebert]], [[https://openalex.org/A5044980923][Piyush Ingale]], [[https://openalex.org/A5070027451][Sarah Vogl]], [[https://openalex.org/A5039386673][Sebastian Praetz]], [[https://openalex.org/A5034033016][Christopher Schlesiger]], [[https://openalex.org/A5099070494][Nils Pfister]], [[https://openalex.org/A5021426343][Raoul Naumann d’Alnoncourt]], [[https://openalex.org/A5065326930][Beatriz Roldán Cuenya]], [[https://openalex.org/A5085044596][Arne Thomas]], [[https://openalex.org/A5054371064][Esteban Gioria]], [[https://openalex.org/A5061251166][Frank Rosowski]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02067  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c02067][pdf]])
     
Due to their availability, low cost, and activity, cobalt-based catalysts are a promising alternative to platinum for the industrial propane dehydrogenation processes. However, their low stability due to sintering, phase transformation, and coke deposition leads to severe deactivation. In this work, the synthesis of amorphous, ordered mesoporous alumina with stabilized Co2+ nanoclusters (Co-m-Al2O3) via an evaporation-induced self-assembly synthesis route is presented. The ordered mesoporous alumina is characterized for containing a large amount of defective pentacoordinate Al3+ sites and a small amount of strong acid sites. The incorporation of Co2+ clusters within the m-Al2O3 structure enhances the dispersion and stability and preserves their reduction even after prolonged time on stream. This leads to a highly selective and steady catalytic performance in the propane dehydrogenation reaction under industrial-relevant conditions. A significantly low deactivation rate of 0.53 d–1 with stable propylene selectivity of 95% is observed after 23 h, resulting in a 117% higher space–time yield toward propylene compared to the state-of-the-art impregnated Co/γ-Al2O3 catalyst. Furthermore, Co-m-Al2O3 leads to 4.6 times less coke formation, measured in situ for the first time. The detailed study of the nature of the cobalt sites, together with the acidic properties of the alumina supports, provides a deeper understanding of cobalt-based catalysts for dehydrogenation reactions.    

    

* Overcoming Electron Bias in Hydroarylation of Phenylpropiolic Acid Derivatives To Enable Highly Reversed Regio- and Stereoselectivity via Steric and Transient Post Addition Coordination  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399812225
:TOPICS: Asymmetric Catalysis, Transition Metal-Catalyzed Cross-Coupling Reactions, Olefin Metathesis Chemistry
:PUBLICATION_DATE: 2024-06-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01944")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399812225"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399812225"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399812225"))][Get cited by]]

OpenAlex: https://openalex.org/W4399812225 (Open access: False)
    
[[https://openalex.org/A5058872290][Hui Li]], [[https://openalex.org/A5050098291][Xu Tian]], [[https://openalex.org/A5051162913][Qin-Qin Dang]], [[https://openalex.org/A5026068732][Jing Zhang]], [[https://openalex.org/A5044192562][Zhen‐Kang Wen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01944 
     
The regio- and stereoselective hydroarylation of internal alkynes via transition-metal catalysis offers a direct approach for designing highly stereodefined multifunctionalized olefins. Through recognition of electronic bias, β-syn-hydroarylation of electronic poor alkynes with arylboronic acids has been well studied. However, from the same starting materials, achieving the opposite α-selective and highly anti-stereoselective hydroarylation remains a significant challenge due to these inherent biases. Therefore, an alternative synthetic pathway to trisubstituted alkenes with reversed positioning and configuration of substituents is highly desirable. Based on steric repulsion-induced regioselectivity and transient post-addition coordination-directed stereoselectivity, we report herein an α-hydroarylation method for phenylpropiolic esters using a nickel catalyst that promotes a formal anti-addition pathway. A broad range of organoboronic acids and phenylpropiolic acid derivatives are compatible with this hydroarylation protocol, offering an alternative selectivity to traditional β-syn-hydroarylation reactions. The distinct advantages of our method include precise control over selectivity, reduced catalyst loading, and broad tolerance toward functional groups. These features highlight the potential of our approach in the synthesis of multifunctionalized alkenes and in the late-stage modification of alkyne-based drug intermediates, showcasing its versatility and applicability in organic synthesis.    

    

* Engineering Durable Anion Exchange Membrane Water Electrolyzers through Suppressed Electrochemical Corrosion of a NiFe–Graphitic Carbon Shell Anode Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399812294
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-06-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02696")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399812294"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399812294"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399812294"))][Get cited by]]

OpenAlex: https://openalex.org/W4399812294 (Open access: False)
    
[[https://openalex.org/A5038503974][Young Sang Park]], [[https://openalex.org/A5046362505][Gwan Hyun Choi]], [[https://openalex.org/A5040293632][Jiyoon Jung]], [[https://openalex.org/A5000050008][Cheol‐Hee Ahn]], [[https://openalex.org/A5079878705][Seung Sang Hwang]], [[https://openalex.org/A5066013260][Myeong Gyun Nam]], [[https://openalex.org/A5008459970][Pil J. Yoo]], [[https://openalex.org/A5045453831][Albert S. Lee]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02696 
     
Anion exchange membrane water electrolysis (AEMWE) shows potential for hydrogen production using cost-effective nonplatinum group metal (non-PGM) catalysts, achieving high current density performance. However, challenges remain in developing materials, including stable membranes and ionomers under alkaline conditions and non-PGM catalysts that are both high-performing and durable for the anodic oxygen evolution reaction (OER). This study presents an approach for synthesizing highly crystalline carbon-encapsulated metal nanoparticle networks using a polyphenolic tannic acid precursor and non-PGM NiFe metal cores, creating a durable OER catalyst. The simplified synthetic process introduces graphitic carbon layers (GCLs) to encompass the NiFe catalytic nanoparticles. Rigorous testing over 1100 h of continuous current operation demonstrates the stability of the catalysts, which is attributed to the robust interaction between the catalyst and the carbon support. The enhanced durability is further confirmed through theoretical calculations, showing greater resistance to corrosion in graphitic carbon compared to defective carbon. This study highlights the importance of highly crystalline carbon structures for achieving both high performance and durability in OER catalysts, which are vital for cost-effective AEMWE technologies. The findings contribute significantly to understanding the role of regulating carbon crystalline properties in developing efficient and durable non-PGM OER electrocatalysts.    

    

* Palladium-Catalyzed Allylic Alkylation Reactions of Nucleophilic Allenones: Asymmetric Allylic Alkylation, Z/E Divergent Allylic Alkylation, and [5 + 2] Annulation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399812307
:TOPICS: Asymmetric Catalysis, Transition-Metal-Catalyzed C–H Bond Functionalization, Gold Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-06-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01460")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399812307"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399812307"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399812307"))][Get cited by]]

OpenAlex: https://openalex.org/W4399812307 (Open access: False)
    
[[https://openalex.org/A5091348611][Wang Wang]], [[https://openalex.org/A5015011136][Yimin Hu]], [[https://openalex.org/A5060531768][Kuan Li]], [[https://openalex.org/A5066002275][Jiajia Xu]], [[https://openalex.org/A5083760774][Cheng Zhang]], [[https://openalex.org/A5074030044][Leijie Zhou]], [[https://openalex.org/A5047780178][Lihan Zhu]], [[https://openalex.org/A5010360845][Wangyu Shi]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01460 
     
Metal-catalyzed allenylic substitution reactions where allenes serve as electrophilic precursors have been recognized as a rapid way for novel allene construction. On the contrary, the chemistry in which allenes act as nucleophiles has been far less investigated, especially in a powerful platform such as metal-catalyzed allylic alkylation reactions. We herein describe two unprecedented palladium-catalyzed allylic alkylation reactions of an allene nucleophile. In the first reaction, using vinyloxazolidinones as the allyl precursor, the palladium-catalyzed asymmetric allylation of trisubstituted allenones worked well to prepare an array of axially chiral tetrasubstituted allenes. Mechanistic studies and density functional theory (DFT) calculations indicated that weak hydrogen-bonding interaction between the acidic C(sp2)–H of allenone and the nitrogen anion of chiral π-azaallyl-Pd species is key to the success of stereocontrol. This reaction revealed the intriguing reactivity of nucleophilic allenones in a metal-catalyzed asymmetric allylation reaction for the first time. In the second reaction, with the use of allenylethylene carbonates as π-oxyallyl-Pd precursors, the palladium-catalyzed allylic alkylation reaction of allenone presented unique reactivity under different reaction conditions to provide divergent synthetic access to (E)- and (Z)-allenyl diene products. Interestingly, the subsequent sequential intramolecular cyclization/isomerization reaction of the (Z)-product delivered dihydrooxepine derivatives as [5 + 2] annulation products.    

    

* Fast Photocatalytic Hydrogen Peroxide Generation by Singlet Oxygen-Engaged Sequential Excitation Energy and Electron-Transfer Process  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399812367
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Photocatalysis and Solar Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-06-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01591")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399812367"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399812367"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399812367"))][Get cited by]]

OpenAlex: https://openalex.org/W4399812367 (Open access: False)
    
[[https://openalex.org/A5086835198][Xiangkang Zeng]], [[https://openalex.org/A5051149614][Tianyi Wang]], [[https://openalex.org/A5027050367][Zhuyuan Wang]], [[https://openalex.org/A5007987712][Mike Tebyetekerwa]], [[https://openalex.org/A5001937247][Yue Liu]], [[https://openalex.org/A5003685331][Zhuoyue Liu]], [[https://openalex.org/A5088166724][Gen Wang]], [[https://openalex.org/A5090264758][Ary Anggara Wibowo]], [[https://openalex.org/A5012271607][Gregory K. Pierens]], [[https://openalex.org/A5006873671][Qinfen Gu]], [[https://openalex.org/A5038750020][Xiwang Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01591 
     
Sequential excitation energy and electron transfer (ET) are ubiquitous pathways for converting solar energy to chemical energy in photosynthesis. Mimicking this unique process for chemical synthesis is promising yet still a big challenge. Herein, taking photosynthesis as an inspiration, we demonstrate an interesting pathway for oxygen reduction to hydrogen peroxide (H2O2), an important and valuable commodity chemical. The proposed route was verified on a biomimetic photocatalyst, i.e., an aluminum porphyrin metal–organic framework nanosheet (Al–TCPP). Experimental investigations and theoretical calculations reveal that the dioxygen molecule is first converted to a highly active singlet oxygen intermediate through an excitation energy transfer (EET) and then reduced to H2O2 via the photogenerated electrons with a reduced barrier over Al–TCPP. Consequently, Al–TCPP shows a 32 times higher H2O2 evolution rate than that of the pristine TCPP counterpart, wherein excitation energy transfer mainly exists. This study presents a paradigm to mimic the photosynthetic sequential excitation energy and electron-transfer process for improved synthesis of valuable commodity chemicals.    

    

* Oxygen Vacancy-Induced Interfacial Lanthanum Hydride and Hydroxide Bifunctional Sites for Selective Hydrogenolysis of Furanic Compounds to Alkyl Diols  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4399830090
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Desulfurization Technologies for Fuels, Mesoporous Materials
:PUBLICATION_DATE: 2024-06-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01266")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399830090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399830090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399830090"))][Get cited by]]

OpenAlex: https://openalex.org/W4399830090 (Open access: False)
    
[[https://openalex.org/A5035085609][Yongsheng Zhang]], [[https://openalex.org/A5046186974][Hongxia Xue]], [[https://openalex.org/A5084492372][Mengqing Cheng]], [[https://openalex.org/A5005227650][Xiaomeng Yang]], [[https://openalex.org/A5084228359][Zhen Zhang]], [[https://openalex.org/A5047835492][Xinbao Zhao]], [[https://openalex.org/A5031187213][Armin Rezayan]], [[https://openalex.org/A5018271860][Dandan Han]], [[https://openalex.org/A5090936368][Dan Wu]], [[https://openalex.org/A5024699864][Chunbao Xu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01266 
     
Selective hydrogenolysis of C–O bonds in biomass-derived oxygenated molecules is of great significance for the conversion of biomass to chemicals and fuels, especially for the inert C–O–C bonds in tetrahydrofuran rings. However, the lack of precise active sites results in the low activity of this reaction. In this work, the metal–support interfacial structure of the Ni–La2O3 catalyst was well-controlled by reducing LaNiO3 perovskite at different temperatures. During the reduction, the exsolution and segregation of Ni in the LaNiO3 perovskite led to the formation of metallic Ni nanoparticles and interfacial oxygen-vacant Ni2+-Ov-La3+ sites. Hydrogen spillover from Ni nanoparticles to the interface promoted the in situ generation of La–OH species under reaction conditions. At the same time, the oxygen vacancies at the interfacial Ni2+-Ov-La3+ sites can accommodate the spilled H, inducing the formation of the La–H species. The hydroxyl group in tetrahydrofurfuryl alcohol (THFA) interacted with La–OH through a metal alkoxide intermediate, which was subsequently hydrogenolyzed by the La–H to produce 1,5-pentanediol (1,5-PeD). The intimate La–H and La–OH bifunctional sites on the metal–support interface have a strong synergistic effect, endowing the Ni–La2O3 catalyst with a high THFA hydrogenolysis activity. The proposed interfacial La–H assisted C–O bond hydrogenolysis provides an idea for the design of efficient hydrodeoxygenation catalysts for biomass upgrading.    

    
