#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Wed Aug 28 01:14:47 2024

Found 17 results from 2024-08-21 to 2024-08-28
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Tailoring and Visualizing Macropores of the Zeolite Monolith to Reveal the Coke Resistance Performance for Bio-oil Hydrodeoxygenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401732939
:TOPICS: Desulfurization Technologies for Fuels, Mesoporous Materials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-08-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02914")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401732939"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401732939"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401732939"))][Get cited by]]

OpenAlex: https://openalex.org/W4401732939 (Open access: False)
    
[[https://openalex.org/A5023215914][Fengli Gan]], [[https://openalex.org/A5100705051][Xia Jiang]], [[https://openalex.org/A5020872993][Ziheng Jin]], [[https://openalex.org/A5031845348][Mingwu Tan]], [[https://openalex.org/A5104225318][Xindi Xie]], [[https://openalex.org/A5023655660][Qinjun Peng]], [[https://openalex.org/A5030467601][Guang‐Mei Cao]], [[https://openalex.org/A5101685178][Shenggui Ma]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02914 
     
Mass transport in conventional microporous zeolite catalysts can be enhanced by introducing secondary mesopores during hydrodeoxygenation (HDO). However, the impact of the macropore architecture with intrinsic mass transfer advantages over mesopores on HDO performance remains elusive. In this study, a macroporous zeolite monolith catalyst without a template and binder was synthesized using a crystal space-confined growth method. This catalyst exhibited a 1.3 times higher macropore volume (0.566 m3/g) than a conventional zeolite catalyst, while the microporous structure was similar. Moreover, the high degree macropore connectivity was directly visualized and quantified with an advanced nanocomputed tomography technique. The macroporous catalyst achieved a higher guaiacol conversion rate of 93% and better coke resistance (3.2 wt % coke) than the conventional zeolite catalyst, which showed a 90% guaiacol conversion rate and 5.6 wt % coke. This improvement was primarily due to faster diffusion rates and an increased number of acid sites in the macropores.    

    

* Stereocomplementary Unspecific Peroxygenases for Asymmetric Anti-Markovnikov Wacker-Type Oxidation and Epoxidation of Styrenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401733354
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Catalytic Oxidation of Alcohols, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-08-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02169")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401733354"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401733354"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401733354"))][Get cited by]]

OpenAlex: https://openalex.org/W4401733354 (Open access: True)
    
[[https://openalex.org/A5068953844][Alexander Swoboda]], [[https://openalex.org/A5092059447][Zerina Duhović]], [[https://openalex.org/A5106635513][Isabella E. E. Kroschel]], [[https://openalex.org/A5092931390][Moritz Bürgler]], [[https://openalex.org/A5074940796][Katharina Ebner]], [[https://openalex.org/A5046566413][Anton Glieder]], [[https://openalex.org/A5009412615][Wolfgang Kroutil]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02169 
     
The Wacker reaction gives access to carbonyls from olefins and is traditionally relying on metals, mostly palladium. Here, unspecific peroxygenases (UPOs) are spotlighted as palladium-free biocatalysts for asymmetric anti-Markovnikov Wacker-type oxidation of styrenes, moving them beyond their traditional role in C–H oxidation and stereoselective epoxidation. Screening 53 wild-type UPOs for the oxidation of styrene and derivatives revealed examples of high reaction selectivity leading mostly to the epoxide with an epoxide selectivity of up to >99%. For selected UPOs and styrene derivatives, aldehyde formation was found with an aldehyde selectivity of up to 86%. Conversions of up to 89% were reached (preferring epoxidation). Stereocomplementary UPOs were identified for the epoxidation, giving access to the (R)- and (S)-epoxides with ee values of up to 94%. Also, for the anti-Markovnikov Wacker-type oxidation of α-methylstyrene, stereocomplementary enzymes were identified, leading to an excess of either the (R)- or (S)-enantiomer of 2-phenylpropanal. Most interestingly, it was found that the absolute configuration of the aldehyde formed does not necessarily correlate with the absolute configuration of the epoxide; thus, aldehyde and epoxide may have the same or the opposite absolute configurations.    

    

* Atomic Carbon Equivalent: Design and Application to Diversity-Generating Skeletal Editing from Indoles to 3-Functionalized Quinolines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401733426
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-08-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401733426"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401733426"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401733426"))][Get cited by]]

OpenAlex: https://openalex.org/W4401733426 (Open access: False)
    
[[https://openalex.org/A5074843530][Fu‐Peng Wu]], [[https://openalex.org/A5056128769][Jasper L. Tyler]], [[https://openalex.org/A5034751002][Constantin G. Daniliuc]], [[https://openalex.org/A5017167322][Frank Glorius]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03868 
     
No abstract    

    

* Investigating Alloy-Induced Modifications in the Oxygen Reduction Reaction Mechanism on PtPd Single Crystals  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401733612
:TOPICS: Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-08-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03565")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401733612"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401733612"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401733612"))][Get cited by]]

OpenAlex: https://openalex.org/W4401733612 (Open access: True)
    
[[https://openalex.org/A5066156698][Pepe Jordá-Faus]], [[https://openalex.org/A5089866638][Rubén Rizo]], [[https://openalex.org/A5005047028][Enrique Herrero]], [[https://openalex.org/A5058030839][Rosa M. Arán‐Ais]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03565 
     
No abstract    

    

* Photoinduced Surface Oxidation of GaN Nanowires Facilitates Hydrogen Evolution  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401733800
:TOPICS: Gallium Oxide (Ga2O3) Semiconductor Materials and Devices, Zinc Oxide Nanostructures, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-08-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00308")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401733800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401733800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401733800"))][Get cited by]]

OpenAlex: https://openalex.org/W4401733800 (Open access: False)
    
[[https://openalex.org/A5005426309][Jan Paul Menzel]], [[https://openalex.org/A5005809281][Wan Jae Dong]], [[https://openalex.org/A5106653817][Elijah Gruszecki]], [[https://openalex.org/A5010438957][Ke Yang]], [[https://openalex.org/A5070775523][Zetian Mi]], [[https://openalex.org/A5089129603][Víctor S. Batista]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00308 
     
Gallium nitride nanowires (GaN NWs) have shown great potential in applications to photocatalysis, including photocatalytic hydrogen evolution for solar energy storage. Previous studies have shown that GaN NWs can undergo self-improvement under light irradiation, which is attributed to surface oxidation, forming gallium oxynitride (GaON). However, the exact oxidation pathways and the effect of surface oxidation on catalytic performance remain to be understood at the molecular level. In this study, we combine computational modeling at the density functional theory (DFT) level with linear sweep voltammetry and chronoamperometric measurements to investigate the photoinduced surface oxidation of GaN NWs. We find that the oxidation of GaN to GaON is competitive with water oxidation. The oxidized surface shows almost no change in its water oxidation capabilities, although the potential required for hydrogen evolution is significantly reduced. Oxidation of the surface also leads to changes in the electronic structure, shifting the valence band edge states toward the surface adsorbed hydroxide, making hole localization there more likely. Calculations are consistent with the observation of shifts in the onset potential for photoelectrochemical hydrogen evolution toward more positive potentials over an extended 18 h period. The reported findings on the mechanism of photoinduced surface oxidation of GaN NWs and the effect of surface oxidation on hydrogen evolution provide valuable insights for the development of more efficient GaN NW-based photocatalytic surfaces for hydrogen evolution.    

    

* Copper-Catalyzed Enantioselective O,S-Rearrangement of Propargylic Xanthates: Efficient Synthesis of Chiral Propargylic Sulfur Compounds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401733990
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Innovations in Organic Synthesis Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-08-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04509")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401733990"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401733990"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401733990"))][Get cited by]]

OpenAlex: https://openalex.org/W4401733990 (Open access: False)
    
[[https://openalex.org/A5100730519][Cheng Wang]], [[https://openalex.org/A5022818689][Mengwu Xiao]], [[https://openalex.org/A5100640331][Wei Li]], [[https://openalex.org/A5027064569][Li‐Jie Cheng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04509 
     
No abstract    

    

* Chiral Brønsted Acid-Catalyzed Regio-, Diastereo-, and Enantioselective Formal [2 + 2 + 2] Cycloaddition of 3-Vinyl-1H-indoles with Nitrosobenzenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401734759
:TOPICS: Catalytic C-H Amination Reactions, Asymmetric Catalysis, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-08-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05041")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401734759"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401734759"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401734759"))][Get cited by]]

OpenAlex: https://openalex.org/W4401734759 (Open access: False)
    
[[https://openalex.org/A5101541464][Lei Yu]], [[https://openalex.org/A5000975362][Jorge Aurelio Díaz]], [[https://openalex.org/A5045881368][Asja A. Kroeger]], [[https://openalex.org/A5083158068][Michelle L. Coote]], [[https://openalex.org/A5039408031][Philip Wai Hong Chan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05041 
     
No abstract    

    

* Effects of Local Structural Changes of Orthorhombic Mo3VOx Induced by High-Temperature Heat Treatment on Catalytic Ammoxidation of Propane  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401742552
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-08-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02923")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401742552"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401742552"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401742552"))][Get cited by]]

OpenAlex: https://openalex.org/W4401742552 (Open access: False)
    
[[https://openalex.org/A5088504570][Kosuke Shimoda]], [[https://openalex.org/A5012589233][Satoshi Ishikawa]], [[https://openalex.org/A5101436764][Ken‐ichi Shimizu]], [[https://openalex.org/A5008300693][Wataru Ueda]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02923 
     
The orthorhombic Mo3VOx (MoVO) crystal catalyst has a crystal structure analogous to that of the industrial catalyst for propane ammoxidation. However, it has been observed that MoVO exhibits poor selectivity for the formation of acrylonitrile (AN). Here, we found that a higher AN yield was attainable over the MoVO heat-treated at higher temperatures (600 °C) in a pure nitrogen stream. Structural analyses revealed that high-temperature heat treatment caused local structural changes through the migration and the segregation of VO2+ without altering the basic crystal structure of MoVO. This resulted in the change in the chemical formula from Mo30.66V11.34O114 to Mo30.66V7.22O104. The kinetic analysis revealed that the local structure after the segregation of VO2+ exhibited improved catalytic activity for the ammoxidation of propylene as the primary product for this reaction, resulting in a high AN yield in the propane ammoxidation. The obtained results offer a new insight into the catalytically active structure of the Mo–V-based mixed metal oxide for the ammoxidation of propane.    

    

* Asymmetric Clicking of Alkynyl Dipolarophiles and Nitrones Catalyzed by a Well-Defined Chiral Iron Complex  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401793206
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Asymmetric Catalysis, Catalytic Carbene Chemistry in Organic Synthesis
:PUBLICATION_DATE: 2024-08-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03508")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401793206"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401793206"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401793206"))][Get cited by]]

OpenAlex: https://openalex.org/W4401793206 (Open access: False)
    
[[https://openalex.org/A5082482425][Zhen‐Ni Zhao]], [[https://openalex.org/A5076578556][Fengkai He]], [[https://openalex.org/A5100370117][Yuhao Wang]], [[https://openalex.org/A5071231776][Yichao Li]], [[https://openalex.org/A5046785243][Zi‐Han Li]], [[https://openalex.org/A5100435418][Xiaoyu Yang]], [[https://openalex.org/A5051985200][Uwe Schneider]], [[https://openalex.org/A5024383687][Yiyong Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03508 
     
The enantioselective 1,3-dipolar cycloaddition of alkynes and α-aliphatic nitrones has long been recognized as an important challenge, while considerable progress has been made for the alkenes and aromatic nitrones. We herein report an example of an earth-abundant iron-catalyzed enantioselective click-approach 1,3-dipolar cycloaddition of nonterminal alkynyl imides and α-aliphatic nitrones, and highly functionalized chiral 4-isoxazolines having a 3-alkyl-substituted stereogenic carbon center are modularly generated in up to >99% yield and 98% ee (54 examples). Although the steric bulk substituent on the nitrone plays a key role in achieving effective enantiocontrol, the challenge of steric bias differentiation between linear alkyl chain (Me, Et, etc.) and H of nitrones is also successfully overcome. The enantioface discrimination is presumably rooted in the well-defined octahedral mononuclear ferrous complex containing dual tridentate ligands (L*·Fe(OTf)2·L*, L* = (R,R)-DBFOX-Ph) and possible dual-mode σ,π-binding activation, which is evidenced by ESI-HRMS and single crystal X-ray analysis, as well as the L*/Fe ratio effect and DFT calculations. Arguably, the most interesting aspect is that the chiral iron complex can induce a superpositive nonlinear effect and the chiral bisoxazoline ligand with a low enantiopurity of 22% ee results in an 84% ee for the cycloadduct. Practicability and utility are demonstrated by the gram-scale synthesis and ready downstream functionalization based on the chiral 4-isoxazoline core and imide functional group.    

    

* On the pH Dependency of the Catalysis by a Lytic Polysaccharide Monooxygenase from the Fungus Trichoderma reesei  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401801713
:TOPICS: Technologies for Biofuel Production from Biomass, Microbial Enzymes and Biotechnological Applications, Metabolic Engineering and Synthetic Biology
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03041")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401801713"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401801713"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401801713"))][Get cited by]]

OpenAlex: https://openalex.org/W4401801713 (Open access: True)
    
[[https://openalex.org/A5016853558][Silja Kuusk]], [[https://openalex.org/A5010770781][Maarja Lipp]], [[https://openalex.org/A5081196995][Surabhi Mahajan]], [[https://openalex.org/A5069713400][Priit Väljamäe]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03041 
     
Lytic polysaccharide monooxygenases (LPMOs) catalyze the oxidative cleavage of glycosidic bonds in industrially important polysaccharides like cellulose. The activity of these monocopper enzymes depends on the presence of H2O2 cosubstrate and reductant. Besides the polysaccharide peroxygenase reaction, LPMOs catalyze reductant oxidase and peroxidase side reactions. The multiplicity and interplay between different LPMO reactions hamper the interpretation of the kinetic data, which is best reflected by the scarcity of the studies of the pH dependency of the LPMO catalysis. Here, we studied the pH dependency of the reductant oxidase/peroxidase as well as the cellulose peroxygenase reactions of TrAA9A, an LPMO from the fungus Trichoderma reesei. The pH dependency of reductant oxidase/peroxidase reaction was governed by the rate-limiting step (reduction of LPMO-Cu(II) or reoxidation of LPMO-Cu(I)) depending on the experimental conditions. The pH dependency of the kcat and Km(H2O2) of the cellulose peroxygenase reaction was best described by the single base catalysis with pKa around 3.5–4.0. Experiments made in D2O showed isotope effects but only at pD values below 5.0. The conserved second coordination sphere histidine (His163) is the most probable candidate responsible for shaping the pH dependency of the TrAA9A peroxygenase reaction. We propose that the double protonation of His163 at acidic pH alters its conformation to the catalytically incompetent one. However, the little pH dependency of the kcat/Km(H2O2) of the cellulose peroxygenase reaction suggests that at very low H2O2 concentrations, TrAA9A may be efficient catalyst also in the acidic conditions that prevail in fungal habitats.    

    

* Regioselective Enzymatic Galactosylation Enabled Divergent Synthesis of Asymmetrical Biantennary Human Milk Oligosaccharides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401811657
:TOPICS: Composition and Health Effects of Human Milk, Chemical Glycobiology and Therapeutic Applications, Glycosylation in Health and Disease
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03373")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401811657"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401811657"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401811657"))][Get cited by]]

OpenAlex: https://openalex.org/W4401811657 (Open access: False)
    
[[https://openalex.org/A5080791772][Hui Xia]], [[https://openalex.org/A5075894101][Kan Zhong]], [[https://openalex.org/A5100655153][Yun Li]], [[https://openalex.org/A5039458434][Jinfeng Ye]], [[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5077907557][Chao Cai]], [[https://openalex.org/A5085774449][Wanmeng Mu]], [[https://openalex.org/A5065426391][Changcheng Liu]], [[https://openalex.org/A5050152196][Hongzhi Cao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03373 
     
Human milk oligosaccharides (HMOs) are essential nutritional and bioactive components of human breast milk, conferring numerous beneficial effects on neonatal health. The HMO repertoire comprises over 200 unique glycan structures, and more than half of them are branched oligosaccharides. Owing to the structural diversity and complexity, the synthesis of branched HMOs remains challenging, which significantly hinders their functional study. We herein present a highly efficient biomimetic approach for the rapid and scaled-up chemoenzymatic synthesis of asymmetrical biantennary HMOs. Taking advantage of the inherent regioselectivity of a panel of bacterial galactosyltransferases, two asymmetrical branched pentasaccharide intermediates were obtained through the regioselective enzymatic β1,3- or β1,4-galactosylation of a readily available chemically synthesized biantennary symmetrical tetrasaccharide precursor. The two asymmetrical pentasaccharide intermediates were further diversified by sequential multienzyme cascade reactions to afford a library of over 20 structurally well-defined asymmetrical biantennary lacto-N-hexaose (LNH) and lacto-N-neo-hexaose (LNnH) series HMOs in less than 5 linear steps.    

    

* Computational Insights for Electrocatalytic Synthesis of Glycine  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401813492
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04263")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401813492"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401813492"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401813492"))][Get cited by]]

OpenAlex: https://openalex.org/W4401813492 (Open access: False)
    
[[https://openalex.org/A5102812336][Jian Lin]], [[https://openalex.org/A5030617408][Jun Long]], [[https://openalex.org/A5102669510][Xiaoyan Fu]], [[https://openalex.org/A5027648567][Dong Luan]], [[https://openalex.org/A5102537365][Pu Guo]], [[https://openalex.org/A5051717534][Huijuan Jing]], [[https://openalex.org/A5100319216][Huan Li]], [[https://openalex.org/A5004947752][Jianping Xiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04263 
     
No abstract    

    

* Photochemical Asymmetric Palladium-Catalyzed Allylation Reaction: Expeditious Entry to Chiral 1,2-Amino Alcohols and 1,2-Diamines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401821535
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-08-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04209")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401821535"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401821535"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401821535"))][Get cited by]]

OpenAlex: https://openalex.org/W4401821535 (Open access: False)
    
[[https://openalex.org/A5048668242][Hui Xie]], [[https://openalex.org/A5038196911][Haohua Chen]], [[https://openalex.org/A5009073078][Uttam Dutta]], [[https://openalex.org/A5061000219][Yu Lan]], [[https://openalex.org/A5067624195][Bernhard Breit]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04209 
     
The construction of diverse alkyl amines is of importance in drug discovery and natural product synthesis. Herein, we report an efficient photoredox/palladium dual catalysis for the construction of protected 1,2-amino alcohols and 1,2-diamines via the asymmetric allylation of α-silyl amines with heteroatom-substituted allenes and 1,3-dienes. This protocol is characterized by its mild conditions, high regio- and enantioselectivities, and wide substrate scope, including aliphatic amines or N-heterocyclic substrates especially. Computational and experimental mechanistic studies indicate that the reaction proceeds through a sequence of oxidative addition of the Pd(0) catalyst by PPTS, allene insertion, outer-sphere radical substitution-type C–C bond formation, and reduction of Pd(I) by Ir(II). Thereinto, the outer-sphere radical substitution is the enantio- and regioselectivity determining step.    

    

* Nitrogen-Rich Carbon Dots as Effective Catalysts in the 1,4-Reduction of α,β-Unsaturated Aldehydes via Ion Pair Asymmetric Nano-Organocatalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401844482
:TOPICS: Aromaticity in Organic Molecules and Materials, Engineering of Surface Nanostructures, Synthesis and Applications of Carbon Quantum Dots
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03532")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401844482"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401844482"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401844482"))][Get cited by]]

OpenAlex: https://openalex.org/W4401844482 (Open access: False)
    
[[https://openalex.org/A5092689902][Alessio Carioscia]], [[https://openalex.org/A5084092290][Emanuele Cocco]], [[https://openalex.org/A5077619653][Maria Edith Casacchia]], [[https://openalex.org/A5032908255][Giuseppe Gentile]], [[https://openalex.org/A5030617180][Martina Mamone]], [[https://openalex.org/A5075714745][Giuliana Giorgianni]], [[https://openalex.org/A5106702204][Elena Incerto]], [[https://openalex.org/A5074191348][Maurizio Prato]], [[https://openalex.org/A5011629137][Fabio Pesciaioli]], [[https://openalex.org/A5080131431][Giacomo Filippini]], [[https://openalex.org/A5051354092][Armando Carlone]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03532 
     
The development of nanostructured organocatalysts is emerging as a prominent field in materials science. To this purpose, nitrogen-doped carbon dots (CDs) have been effectively employed in enantioselective enamine organocatalysis. On the other hand, enantioselective iminium ion nano-organocatalysis is much less explored. In this Letter, the use of CDs in asymmetric iminium ion catalysis via asymmetric counteranion-directed catalysis (ACDC) is disclosed. Nonchiral CDs bearing butylenediamine residues proved to be the most effective ones, in combination with (S)-TRIP as a chiral phosphoric acid (CPA). A correlation between the features of the CDs' surfaces and their catalytic performance was shown, and the catalytic activity of the employed CDs proved to be higher than that of simple molecular amines. An extensive reaction optimization allowed the reduction of different α,β-unsatured aldehydes in good yield and ee, using a low catalyst loading.    

    

* Confined Intermediates Boost C2+ Selectivity in CO2 Electroreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401804406
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02823")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401804406"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401804406"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401804406"))][Get cited by]]

OpenAlex: https://openalex.org/W4401804406 (Open access: False)
    
[[https://openalex.org/A5076563007][Wanhe Li]], [[https://openalex.org/A5018648007][Yahui Chen]], [[https://openalex.org/A5001719072][Chengqi Guo]], [[https://openalex.org/A5090614452][Shuhan Jia]], [[https://openalex.org/A5008204312][Yiying Zhou]], [[https://openalex.org/A5104324143][Zhonghuan Liu]], [[https://openalex.org/A5045685070][Enhui Jiang]], [[https://openalex.org/A5086071359][Xiaoke Chen]], [[https://openalex.org/A5101745373][Yue Zou]], [[https://openalex.org/A5000294498][Pengwei Huo]], [[https://openalex.org/A5100769787][Yongsheng Yan]], [[https://openalex.org/A5102776020][Zhi Zhu]], [[https://openalex.org/A5018028838][Yun Hau Ng]], [[https://openalex.org/A5048175359][Yanjun Gong]], [[https://openalex.org/A5017414280][John C. Crittenden]], [[https://openalex.org/A5024670135][Yan Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02823 
     
Addressing the efficient electrochemical conversion of CO2 (CO2RR) into valuable multicarbon (C2+) products necessitates innovative strategies to boost carbon (C1) intermediate coupling on catalyst surfaces. In this work, we introduce a surface-confinement strategy on Cu2O nanoparticles by long alkyl chain grafting to create a spatially confined environment, impeding C1 intermediate detachment and promoting C–C coupling in the CO2RR. The optimized C12–Cu2O sample exhibits a Faradaic efficiency (FE) over 63.0% for C2H4, more than double the yield of pristine Cu2O (FE = 25.7%). In situ ATR-FTIR spectroscopy provides direct evidence of rapid C1 intermediate enrichment and restricted diffusion within the surface-confined environment. Molecular dynamics simulations further support these findings by identifying a prolonged residency time that is proportionate to the alkyl chain length, thereby maximizing C2+ selectivity. This surface-confinement approach marks a previously overlooked but immensely promising paradigm in the catalyst design for the CO2RR.    

    

* Highly Stereoselective Biocatalytic One-Pot Synthesis of Chiral Saturated Oxygen Heterocycles by Integration of a Biosynthetic Heterocyclase into Multiple-Enzyme Cascades  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401805036
:TOPICS: Enzyme Immobilization Techniques, Olefin Metathesis Chemistry, Natural Products as Sources of New Drugs
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03692")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401805036"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401805036"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401805036"))][Get cited by]]

OpenAlex: https://openalex.org/W4401805036 (Open access: True)
    
[[https://openalex.org/A5106676089][Theresa Roß-Taschner]], [[https://openalex.org/A5023822759][Sebastian Derra]], [[https://openalex.org/A5011904429][Jörg Stang]], [[https://openalex.org/A5038826554][Luca Schlotte]], [[https://openalex.org/A5106676090][Anthony Putratama]], [[https://openalex.org/A5047800381][Frank Hahn]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03692  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c03692][pdf]])
     
The secondary metabolism is a rich source of enzymes with new synthetically attractive activities that have not yet been integrated into the toolbox of biocatalysis. Chiral saturated oxygen heterocycles (CSOHs) are abundant structural elements of natural products and other value-added compounds. We present a biocatalytic method for the synthesis of CSOHs from readily accessible precursors that combines an intramolecular oxa-Michael addition (IMOMA)-catalyzing cyclase (CYC) from a biosynthetic pathway with alcohol dehydrogenases (ADHs) and thioester-derivatizing enzymes. The one-pot ADH–CYC reaction enables access to various tetrahydropyran (THP) and tetrahydrofuran thioesters under control of up to four stereocenters. These products are readily convertible into useful CSOH ketone, amide, aldehyde/alcohol, ester, and carboxylic acid building blocks by chemical and enzymatic means. The extendibility to more complex multienzyme cascades was demonstrated by the addition of a thioesterase and a carboxylic acid reductase, allowing the straightforward chemoenzymatic synthesis of the natural product (−)-civet, a new derivative, and a THP alcohol. The integration of IMOMA cyclases into enzymatic cascades allows better exploitation of the high synthetic potential of this new group of ring-forming enzymes and expands the repertoire for the synthesis of pharmacologically relevant CSOHs as a highly selective and versatile alternative. This approach will be adaptable for the synthesis of a wide range of CSOHs by varying ADHs, IMOMA cyclases, and modifying enzymes.    

    

* A Career in Catalysis: Mark E. Davis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401813537
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Mesoporous Materials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03617")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401813537"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401813537"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401813537"))][Get cited by]]

OpenAlex: https://openalex.org/W4401813537 (Open access: True)
    
[[https://openalex.org/A5091311605][Juan P. Arhancet]], [[https://openalex.org/A5010159566][Cong-Yan Chen]], [[https://openalex.org/A5069088464][Viktor J. Cybulskis]], [[https://openalex.org/A5072511676][Rajamani Gounder]], [[https://openalex.org/A5017416587][Suk Bong Hong]], [[https://openalex.org/A5052807182][Christopher W. Jones]], [[https://openalex.org/A5076816392][Jong Hun Kang]], [[https://openalex.org/A5100635639][Yoshihiro Kubota]], [[https://openalex.org/A5100695063][Hyunjoo Lee]], [[https://openalex.org/A5040695374][Marat Orazov]], [[https://openalex.org/A5016487357][Yuriy Román‐Leshkov]], [[https://openalex.org/A5018333095][Joel E. Schmidt]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03617 
     
Mark E. Davis led an independent research program from 1981 to 2023, beginning at the Virginia Polytechnic Institute and State University (VPI) and then transitioning to the California Institute of Technology (Caltech). His research program was marked by exceptional creativity, breadth, and depth. With classical training in reaction engineering, Davis developed expertise in experimental heterogeneous catalysis and led work in this discipline for more than 40 years. His name is synonymous with zeolites, and today, he is one of the most widely recognized experts in zeolite synthesis, characterization, and catalysis in the world. Early work at the VPI focused on zeolites and catalysis with supported metal coordination complexes. His creativity was evident at the earliest stages of his career, with the development of supported aqueous phase catalysts and the world's first crystalline, extra-large pore molecular sieve, both reported in the late 1980s. A move to Caltech saw a significant expansion of his zeolite synthesis program and the rapid acceleration of a multidecade collaboration with Dr. Stacey I. Zones of Chevron. At Caltech, his work expanded to include studies of molecular recognition and catalysis with organic/inorganic hybrid materials, and he developed a large, parallel program in drug delivery. His work on catalysis heavily emphasized zeolite catalysis, including major thrusts on the conversion of sugars in the liquid phase and methanol in the gas phase. Numerous new zeolites and molecular sieves were discovered throughout the four decades of the Davis laboratory, highlighted by a successful, multidecade quest to prepare a chiral zeolite with enantioselective catalytic properties. Davis is one of the most decorated researchers of the last four decades. He is one of only 21 living people currently elected to all of the US National Academies (Engineering, Science, Medicine) and elected as a Fellow of the National Academy of Inventors. He was the first engineer to win the NSF's Alan T. Waterman Award and is one of only two researchers (to date) to win the International Zeolite Association's Donald Breck Award twice (1989, 2019). Awards from the ACS (Ipatieff, Murphree, and Somorjai Awards), AIChE (Colburn, Professional Progress Awards), and North American Catalysis Society (Emmett Award) are among his accolades.    

    
