#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Wed Nov 27 01:26:42 2024

Found 30 results from 2024-11-20 to 2024-11-27
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Expanding the Reaction Network of Ethylene Epoxidation on Partially Oxidized Silver Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404513109
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04521")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404513109"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404513109"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404513109"))][Get cited by]]

OpenAlex: https://openalex.org/W4404513109 (Open access: False)
    
[[https://openalex.org/A5008667355][Adhika Setiawan]], [[https://openalex.org/A5079636509][Tiancheng Pu]], [[https://openalex.org/A5066491588][Israel E. Wachs]], [[https://openalex.org/A5070042353][Srinivas Rangarajan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04521 
     
No abstract    

    

* Construction of a Pore-Confined Catalyst in a Vinylene-Linked Covalent Organic Framework for the Oxygen Reduction Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404519758
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05827")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404519758"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404519758"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404519758"))][Get cited by]]

OpenAlex: https://openalex.org/W4404519758 (Open access: False)
    
[[https://openalex.org/A5100441266][Xuewen Li]], [[https://openalex.org/A5100784279][Shuai Yang]], [[https://openalex.org/A5032456464][Xiubei Yang]], [[https://openalex.org/A5108312160][Shuang Zheng]], [[https://openalex.org/A5069765087][Qing Xu]], [[https://openalex.org/A5028394871][Gaofeng Zeng]], [[https://openalex.org/A5038741162][Zheng Jiang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05827 
     
Two-dimensional metal-containing covalent organic frameworks (COFs) have been employed as electrocatalysts. However, the metal sites were stacked within the layers with strong interactions, which hindered mass transport to them in the catalytic process. Herein, we constructed a pore-confined catalyst in a vinylene-linked COF for the oxygen reduction reaction (ORR) via the Katritzky reaction. By anchoring the catalytic sites along the pore walls with covalent bonds, the catalytic units were well-exposed during the catalytic process and retained crystallinity and porosity, facilitating mass access to the metal sites. In addition, the electron/charge transported from the framework to the metal units modulated the electronic states, thus improving the catalytic activity. The catalytic COF exhibited a half-wave potential of 0.85 V and a mass activity of 109.7 A g–1, which are better than those of other reported COFs. Theoretical calculations revealed that the interaction between the framework and metal sites contributed to the easy formation of OOH* and OH*, resulting in high activity. This work provides insights into designing catalytic COFs based on C═C linkages.    

    

* Correlated Operando Electron Microscopy and Photoemission Spectroscopy in Partial Oxidation of Ethylene over Nickel  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404522986
:TOPICS: Surface Analysis and Electron Spectroscopy Techniques, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04437")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404522986"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404522986"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404522986"))][Get cited by]]

OpenAlex: https://openalex.org/W4404522986 (Open access: True)
    
[[https://openalex.org/A5055099002][Claudiu Colbea]], [[https://openalex.org/A5064864784][Milivoj Plodinec]], [[https://openalex.org/A5103539982][Man Guo]], [[https://openalex.org/A5014379900][Luca Artiglia]], [[https://openalex.org/A5054120563][Jeroen A. van Bokhoven]], [[https://openalex.org/A5055099002][Claudiu Colbea]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04437 
     
The production of syngas from light hydrocarbons is a viable way of converting under-utilized hydrocarbon sources into valuable products until a full transition to renewable energy sources is achieved. However, current heterogeneous catalysts for syngas production suffer from deactivation, either by coking or oxidation. Here, we report on the behavior of model nickel catalysts within the context of ethylene partial oxidation and observe the catalyst-environment interaction as a function of reactant feed and temperature. Using a combination of operando microscopy and spectroscopy and focusing on a reaction regime characterized by synchronized self-sustained oscillatory dynamics, we are able to gain additional insights into the dynamic interplay between reactive species and active catalyst surfaces of varying reactivity. Real-time secondary electron imaging coupled with online mass spectrometry and thermal data shows that the oscillatory behavior is characterized by a highly active half-period during which the surface of the nickel catalyst is metallic and a less active half-period during which the surface is oxidized. Complementing the direct surface imaging, operando X-ray photoelectron spectroscopy provides missing information about the alternating chemical state of the catalyst surface in the oscillating reaction regime. It reveals that changes in the gas phase composition (C2H4/O2 ratio) alter the population of reaction intermediates (e.g., carbides) on the nickel surface, which in turn drives the selectivity of the reaction toward different products. The observed chemical dynamics involve changes in gas-phase composition, rate-dependent heat of reaction, the chemical state of the catalyst, and the formation of reaction products, all of which are interconnected. Ultimately, the complex oscillations and catalytic behavior are attributed to a multistep mechanism that involves complete ethylene oxidation, dry and wet reforming of ethylene, and the reverse water gas shift reaction.    

    

* Promoted Electrochemical Ammonia Synthesis from Nitrate at the Ag–Cu Biphasic Interface  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404522993
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05465")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404522993"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404522993"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404522993"))][Get cited by]]

OpenAlex: https://openalex.org/W4404522993 (Open access: False)
    
[[https://openalex.org/A5020951968][Xinyang Gao]], [[https://openalex.org/A5037587672][Chenyuan Zhu]], [[https://openalex.org/A5035847622][Chunlei Yang]], [[https://openalex.org/A5064269604][Guoshuai Shi]], [[https://openalex.org/A5031317695][Qinshang Xu]], [[https://openalex.org/A5100461464][Liming Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05465 
     
Electrochemical nitrate reduction (NO3–R) presents a promising pathway for carbon-neutral ammonia (NH3) synthesis. Enhancing NH3 selectivity through a tandem process can be achieved by combining Cu with a secondary metal, which allows for an adjustable binding energy between the bimetallic catalyst and key nitrogen intermediates. Herein, we developed a biphasic Ag–Cu heterostructure with a controllable elemental composition, which significantly improved NH3 production through tandem NO3–R. In-situ infrared spectroscopy and finite element simulations revealed that Ag serves as the active site for converting NO3– to NO2–, leading to a high localized concentration of NO2–, which is subsequently reduced to NH3 on adjacent Cu sites. Density functional theory calculations further confirmed the critical role of the Ag–Cu biphasic interface in promoting tandem NH3 production. This work offers valuable insights into the tandem NO3–R pathway in bimetallic heterostructures, providing a foundation for optimizing catalysts and advancing large-scale sustainable NH3 synthesis.    

    

* Correction to “Functional Nucleic Acid Enzymes: Nucleic Acid-Based Catalytic Factories”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404523123
:TOPICS: DNA Nanotechnology and Bioanalytical Applications, G-Quadruplex DNA Structures and Functions, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06741")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404523123"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404523123"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404523123"))][Get cited by]]

OpenAlex: https://openalex.org/W4404523123 (Open access: False)
    
[[https://openalex.org/A5090654075][Min Yang]], [[https://openalex.org/A5112950523][Yushi Xie]], [[https://openalex.org/A5109354509][Longjiao Zhu]], [[https://openalex.org/A5100341794][Xiangyang Li]], [[https://openalex.org/A5049623429][Wentao Xu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06741 
     
InfoMetricsFiguresRef. ACS CatalysisASAPArticle This publication is free to access through this site. Learn More CiteCitationCitation and abstractCitation and referencesMore citation options ShareShare onFacebookX (Twitter)WeChatLinkedInRedditEmailJump toExpandCollapse ORIGINAL ARTICLE. This notice is a correction.Addition/CorrectionNovember 19, 2024Correction to "Functional Nucleic Acid Enzymes: Nucleic Acid-Based Catalytic Factories"Click to copy article linkArticle link copied!Min YangMin YangMore by Min YangYushi XieYushi XieMore by Yushi XieLongjiao ZhuLongjiao ZhuMore by Longjiao ZhuXiangyang LiXiangyang LiMore by Xiangyang LiWentao Xu*Wentao XuMore by Wentao Xuhttps://orcid.org/0000-0002-8572-8257Open PDFACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 17879Click to copy citationCitation copied!https://pubs.acs.org/doi/10.1021/acscatal.4c06741https://doi.org/10.1021/acscatal.4c06741Published November 19, 2024 Publication History Received 5 November 2024Published online 19 November 2024correction© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsThis publication is licensed for personal use by The American Chemical Society. ACS Publications© 2024 American Chemical SocietyThe caption for Figure 2 should read as follows:Figure 2. Classifications and applications of FNAzymes.P 16394, the last sentence of the first paragraph of section 2 should read as follows:In general, catalytic functions of ribozymes could be divided into these categories: cleaving, splicing, ligation, polymerization and others.Author InformationClick to copy section linkSection link copied!Corresponding AuthorWentao Xu; https://orcid.org/0000-0002-8572-8257; Email: AuthorsMin YangYushi XieLongjiao ZhuXiangyang LiCited By Click to copy section linkSection link copied!This article has not yet been cited by other publications.Download PDFFiguresReferences Get e-AlertsGet e-AlertsACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 17879Click to copy citationCitation copied!https://doi.org/10.1021/acscatal.4c06741Published November 19, 2024 Publication History Received 5 November 2024Published online 19 November 2024© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsArticle Views-Altmetric-Citations-Learn about these metrics closeArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated.Recommended Articles FiguresReferencesThis publication has no figures.This publication has no References.    

    

* Geometrically Constrained Cofacial Bi-Titanium Olefin Polymerization Catalysts: Tuning and Enhancing Comonomer Incorporation Density  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404531727
:TOPICS: Transition Metal Catalysis, Carbon Dioxide Utilization for Chemical Synthesis, Olefin Metathesis Chemistry
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05888")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404531727"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404531727"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404531727"))][Get cited by]]

OpenAlex: https://openalex.org/W4404531727 (Open access: False)
    
[[https://openalex.org/A5010992519][Junhui Bao]], [[https://openalex.org/A5101743373][Yufang Li]], [[https://openalex.org/A5030730368][Chun‐Ming Chan]], [[https://openalex.org/A5046687235][Kwok-Chung Law]], [[https://openalex.org/A5012005897][Shek‐Man Yiu]], [[https://openalex.org/A5027075522][Michael C. W. Chan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05888 
     
A series of shape-persistent bis-[C(sp3)-chelating] Ti2 (plus Zr2 and Hf2) complexes with a rigid linker component (xanthene or dibenzofuran) are presented. These structurally diverse assemblies display limited yet different conformational flexibility, and crucially, such geometric constraints confer access to a range of intermetallic separations and orientations to potentially enhance catalytic activity and cooperative effects. For ethylene polymerizations, the Ti2 catalysts (in conjunction with trityl borate) exhibit greater efficiencies and produced polymers with higher Mw than mononuclear controls, which is significant considering the more crowded environment for cofacial bimetallic sites. Proficient 1-hexene incorporations were observed for ethylene-(α-olefin) copolymerization reactions. The F-substituted m-aryl/dibenzofuran-linked catalyst (5), which is revealed by NMR analysis to be conformationally dissimilar to its F-absent congener, produced copolymers with higher Mw and elevated 1-hexene incorporation levels (up to 44%), when compared with its mono-Ti control (19%). These results suggest that catalyst frameworks with suitably adjustable conformations and Ti···Ti distances can facilitate bimetallic enchainment interactions with α-olefin substrates and their insertion.    

    

* Exploring the Mechanism of Biomimetic Arene Hydroxylation: When a Diiron Metal Center Meets a Sulfur-Containing Ligand  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404539817
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04662")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404539817"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404539817"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404539817"))][Get cited by]]

OpenAlex: https://openalex.org/W4404539817 (Open access: False)
    
[[https://openalex.org/A5100673010][Yu Sheng]], [[https://openalex.org/A5037117630][Bo Bi]], [[https://openalex.org/A5041968492][Lu Cheng]], [[https://openalex.org/A5100757735][Wei Han]], [[https://openalex.org/A5100334211][Hui Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04662 
     
No abstract    

    

* Ancestral Sequence Reconstruction Meets Machine Learning: Ene Reductase Thermostabilization Yields Enzymes with Improved Reactivity Profiles  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404541678
:TOPICS: Enzyme Immobilization Techniques, Advances in Metabolomics Research, Macromolecular Crystallography Techniques
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03738")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404541678"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404541678"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404541678"))][Get cited by]]

OpenAlex: https://openalex.org/W4404541678 (Open access: False)
    
[[https://openalex.org/A5081482981][Caroline K. Brennan]], [[https://openalex.org/A5011950010][Jovan Livada]], [[https://openalex.org/A5082363308][Carlos Alberto Martínez]], [[https://openalex.org/A5051704741][Russell D. Lewis]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03738 
     
No abstract    

    

* Catalytic Combustion of Methane over Noble Metal Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404551760
:TOPICS: Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05650")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404551760"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404551760"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404551760"))][Get cited by]]

OpenAlex: https://openalex.org/W4404551760 (Open access: False)
    
[[https://openalex.org/A5045460215][Huimei Duan]], [[https://openalex.org/A5101448533][Fanxin Kong]], [[https://openalex.org/A5002542603][Xinze Bi]], [[https://openalex.org/A5100333579][Lei Chen]], [[https://openalex.org/A5013084576][Hangrong Chen]], [[https://openalex.org/A5101567103][Dongjiang Yang]], [[https://openalex.org/A5100639761][Weixin Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05650 
     
As one of the cleanest fossil fuel resources, methane is also the second largest greenhouse gas after CO2 owing to its strong greenhouse effect. The direct emission of large quantities of trace and unburned methane causes a serious energy loss and greenhouse effect. Catalytic methane combustion is a promising strategy in eliminating methane slip to address the urgent environmental issue. However, the current methane abatement catalysts still face great challenges in thermal stability, water resistance, and sulfur tolerance. In this review, we focus on the popular noble metal-based catalysts, discuss the distinct reaction mechanisms including the Langmuir–Hinshelwood model, Eley–Rideal model, Mars–van Krevelen model, and two-term mechanisms. The deactivation mechanisms induced by sintering, sulfur, and water on popular Pd-based catalysts are then analyzed. Then, we outline the promotion strategies from two aspects, i.e., construction of a core–shell structure and electronic engineering of the active phase to improve thermal stability and poisoning resistance. Finally, a summary and prospects with an emphasis on the newly developed oxide-metal interfaces and photothermal catalysis for highly efficient methane combustion are addressed.    

    

* Photoelectrochemical Synthesis of Benzo[b]phosphole Oxides via Sequential P–H/C–H Bond Functionalizations  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404563322
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06292")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404563322"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404563322"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404563322"))][Get cited by]]

OpenAlex: https://openalex.org/W4404563322 (Open access: True)
    
[[https://openalex.org/A5007654596][N. K. SAHA]], [[https://openalex.org/A5067475475][Burkhard Koenig]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06292 
     
Benzo[b]phosphole oxides are important P-heterocycles that find applications in optoelectronics due to their inherent photophysical properties. Traditional routes for the synthesis of such molecules from readily available precursors require stoichiometric amounts of transition metal salts, bases, oxidants, and additives, thereby lacking efficiency. Photochemical pathways still need a terminal oxidant to complement the photocatalytic cycle, whereas electricity may be a viable oxidant. Hence, photoelectrochemistry (PEC), combining photocatalysis and synthetic organic electrochemistry, was used to simplify the synthetic protocols. We use the potency of 4CzIPN for the consecutive P–H/C–H bond functionalizations for preparing benzo[b]phosphole oxides from secondary phosphine oxides and nonactivated internal alkynes with up to 93% yields and with good functional group tolerance. Detailed mechanistic investigations confirm an intermolecular electron transfer between 4CzIPN and aryl secondary phosphine oxides upon photoexcitation. The photocatalyst is regenerated by anodic oxidation.    

    

* Organocatalytic Asymmetric Electrophilic Amination of Allylic Boronates  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404563337
:TOPICS: Frustrated Lewis Pairs Chemistry, Asymmetric Catalysis, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05237")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404563337"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404563337"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404563337"))][Get cited by]]

OpenAlex: https://openalex.org/W4404563337 (Open access: False)
    
[[https://openalex.org/A5077730496][Giovanni Centonze]], [[https://openalex.org/A5114728219][Arianna Grandi]], [[https://openalex.org/A5076223736][Andrea Pellegrini]], [[https://openalex.org/A5085857744][Paolo Righi]], [[https://openalex.org/A5049944494][Chiara Portolani]], [[https://openalex.org/A5076128769][Giorgio Bencivenni]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05237 
     
The asymmetric addition of allylic boronates to electrophiles is a powerful method for preparing chiral molecules bearing synthetically valuable allylic moieties. While effective catalytic methods exist, they have so far been limited to the enantioselective allyl- and crotyl-boration of carbonyl compounds and imines, thereby forming C–C bonds. Here, we present a strategy that expands the scope of this catalytic asymmetric platform to include the stereoselective formation of C–N bonds. We have identified an inexpensive and readily available chiral diol that catalyzes the addition of allylic boronates to azodicarboxylates, affording chiral allylic hydrazides with high stereocontrol. This electrophilic amination chemistry shows a broad substrate scope and requires mild conditions, proceeding at ambient temperature. Mechanistic studies reveal that the chiral diol catalyst facilitates the formation of a chiral allylic boronate through the reversible exchange of the boron's achiral alkoxy ligand. By coordination with the electrophilic azodicarboxylate, the substrates mutually activate each other, allowing for the stereoselective transfer of the allyl group.    

    

* SiOx Interfacial Engineering of UV/Ozone Oxidation for an Efficient Water-Reduction Metal–Insulator–Semiconductor Silicon Photocathode  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404563346
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05792")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404563346"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404563346"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404563346"))][Get cited by]]

OpenAlex: https://openalex.org/W4404563346 (Open access: False)
    
[[https://openalex.org/A5028227271][Chenxiao Jiang]], [[https://openalex.org/A5057937956][Siqin Zhou]], [[https://openalex.org/A5076856796][Jinlu Han]], [[https://openalex.org/A5031860089][Guancai Xie]], [[https://openalex.org/A5033246962][Jian Gong]], [[https://openalex.org/A5042664703][Juan Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05792 
     
A metal–insulator–semiconductor (MIS) structure is an attractive interfacial structure for efficient photoelectrochemical (PEC) water-splitting reactions. However, developing a cost-effective and highly active photoelectrode for the PEC water-splitting reaction is still a major challenge. In this study, we use an easy-to-operate and economical UV/ozone (UV/O3) oxidation process to prepare ultrathin SiOx oxide as an insulating layer, which is integrated with the bilayer non-precious-metal collector Al/Ni serving as the catalyst and the p-Si semiconductor to obtain a cost-effective and efficient MIS structure photocathode. The outcomes demonstrate that the ultrathin SiOx insulation layer significantly improves the PEC hydrogen evolution reaction (HER), through comparing the photovoltage and photocurrent density of the MIS system. The inner metal Al in the bilayer collector Al/Ni regulates the degree of band bending at the semiconductor–metal interface. Additionally, the presence of the ultrathin Al2O3 insulation layer effectively reduces Fermi-level pinning, which promotes the efficient transfer of photoelectrons to electrolytes. These were confirmed through photoelectric performance testing of the MIS system. The generation of a photocurrent of 15 mA cm–2 at a potential level of 0 V (vs reversible hydrogen electrode) has been obtained by optimizing the thickness of the SiOx and bilayer non-precious-metal collector. This study presents an economical and efficient strategy for enhancing PEC-HER performance in silicon-based photocathodes using an MIS structure.    

    

* {TiO2/TiO2(B)} Quantum Dot Hybrids: A Comprehensible Route toward High-Performance [>0.1 mol gr–1 h–1] Photocatalytic H2 Production from H2O  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404567183
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05001")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404567183"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404567183"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404567183"))][Get cited by]]

OpenAlex: https://openalex.org/W4404567183 (Open access: True)
    
[[https://openalex.org/A5080050755][Christos Dimitriou]], [[https://openalex.org/A5019048238][Loukas Belles]], [[https://openalex.org/A5050545965][Nikos Boukos]], [[https://openalex.org/A5070708239][Yiannis Deligiannakis]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05001 
     
Industrial-scale photocatalytic H2 production from H2O is a forward-looking aim in research and technology. To this end, understanding the key properties of TiO2 as a reference H2 production photocatalyst paves the way. Herein, we explore the TiO2 nanosize limits, in conjunction with the TiO2(B) nanophase, as a strategy to enhance the photocatalytic H2 production at >150 mmol/g/h. We present a targeted engineering realm on the synthesis of quantum dots (QDs) of TiO2 consisting of an anatase core (3 nm) interfaced with a nanometric shell of the TiO2(B) phase, synthesized through a modified flame spray pyrolysis (FSP) process. The {TiO2-anatase/TiO2(B)} core–shell QDs, with high specific surface area SSA = 360 m2/gr, achieve a milestone H2 production yield of 156 mmol/g/h and solar-to-H2 efficiency nSTH = 24.2%. We demonstrate that diligent control of the TiO2-anatase/TiO2(B) heterojunction, in tandem with lattice microstrain, are key factors that contribute to the superior H2 production, i.e., not only the high SSA of the QDs. At these quantum-size limits, the formation of lattice dislocations and interstitial Ti centers enhances photon absorption at ∼2.3 eV (540 nm), resulting in the generation of midgap states around the Fermi energy. EPR spectroscopy provides direct evidence that the photoinduced holes are preferentially localized on the TiO2(B) shell, while the photoinduced electrons accumulate on the anatase nanophase. Combined electrochemical and photocatalytic analyses demonstrate that the presence of an optimal TiO2(B) phase is significant for the photoactivity of TiO2 in all QD materials. High SSA does contribute to enhanced photocatalytic H2 production; however, its role is not the key-determinant. TiO2 lattice-dislocations in QDs provide extra DOS that can additionally assist in the photon utilization efficiency. Overall, the present work reveals a general concept, that is, at the quantum-size scale, lattice microstrain engineering and interstitial-states' formation are spontaneously facilitated by nanolattice physics. Diligent optimization of these properties offers a pathway toward high-end photocatalytic efficacy.    

    

* Cofactor-Inspired Quinone Catalysis Following a One-Electron Hydrogen Atom Transfer Pathway  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404572577
:TOPICS: Role of Porphyrins and Phthalocyanines in Materials Chemistry, Dioxygen Activation at Metalloenzyme Active Sites, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-11-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05988")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404572577"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404572577"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404572577"))][Get cited by]]

OpenAlex: https://openalex.org/W4404572577 (Open access: False)
    
[[https://openalex.org/A5020953774][Amreen K. Bains]], [[https://openalex.org/A5110605417][Harshit Jain]], [[https://openalex.org/A5086765861][Abhishek Kundu]], [[https://openalex.org/A5108606659][Rahul Singh]], [[https://openalex.org/A5019108600][Sudha Yadav]], [[https://openalex.org/A5026191696][Yadav Ankit]], [[https://openalex.org/A5081346085][Debashis Adhikari]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05988 
     
Alcohol dehydrogenation catalysts in an aerobic atmosphere are often inspired by biological cofactors, which play a major role in controlling the redox chemistry. A large body of work mimicking quinone-containing cofactors established two major mechanistic routes, addition–elimination or transamination. Both of these pathways are completely regulated by two-electron processes, despite the possibility of the cofactor motif being reduced by one electron. In stark contrast to the established mechanisms, we demonstrate a one-electron pathway in quinone catalysis toward dehydrogenating alcohols. The described pyrene dione molecule is efficient in catalytic dehydrogenation of primary, secondary, and aliphatic alcohols. The process starts with the photoexcitation of the dione motif which becomes photoreduced by KOtBu to generate a persistent semiquinonate radical. The substrate alcohol interacts with the quinone backbone to forge a hydrogen-bonded intermediate, which leads to a crucial hydrogen atom transfer (HAT) step, to accomplish the dehydrogenation reaction. A series of kinetic experiments including Bell–Evans–Polanyi correlation with the bond dissociation enthalpy firmly establish HAT to be rate-determining during dehydrogenation reactions. A kinetic isotope effect measured for the dehydrogenation process at 30 °C is 7.7 ± 0.9. Interception of a series of intermediates by a radical quencher in conjunction with a radical-probe substrate further affirms the radical-mediated, one-electron pathway to be operative that is in striking contrast to two-electron-driven quinone catalysis established so far.    

    

* Electrochemical Promotion of Catalysis by Lithium-Ion  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404579251
:TOPICS: Lithium-ion Battery Technology, Electrocatalysis for Energy Conversion, Electrochemical Reduction in Molten Salts
:PUBLICATION_DATE: 2024-11-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04622")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404579251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404579251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404579251"))][Get cited by]]

OpenAlex: https://openalex.org/W4404579251 (Open access: False)
    
[[https://openalex.org/A5100648239][Ju Wang]], [[https://openalex.org/A5028150563][Shuo Yan]], [[https://openalex.org/A5079471616][Kholoud E. Salem]], [[https://openalex.org/A5045865860][Christopher Panaritis]], [[https://openalex.org/A5054037157][Mohamed S.E. Houache]], [[https://openalex.org/A5078262597][Yaser Abu‐Lebdeh]], [[https://openalex.org/A5044827415][Drew Higgins]], [[https://openalex.org/A5044206105][Elena A. Baranova]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04622 
     
No abstract    

    

* Dynamic Molybdate Oxyanion Boosts Self-Optimization and Self-Healing on the NiMoFe Heterostructure for Water Splitting in Alkaline Media  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404609586
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-11-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05108")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404609586"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404609586"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404609586"))][Get cited by]]

OpenAlex: https://openalex.org/W4404609586 (Open access: False)
    
[[https://openalex.org/A5100358805][Qing Zhang]], [[https://openalex.org/A5072870711][Wei Xiao]], [[https://openalex.org/A5019046581][Jia Shi]], [[https://openalex.org/A5109485589][Jing Lei]], [[https://openalex.org/A5017619210][Qi Xiao]], [[https://openalex.org/A5035390246][Hong Qun Luo]], [[https://openalex.org/A5029750679][Nian Bing Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05108 
     
NiMo-based alloys and NiFe layered double hydroxides (NiFe-LDHs) are the most promising nonprecious-metal electrocatalysts for hydrogen and oxygen evolution reactions (HER and OER) under alkaline conditions. However, the ready leaching of Mo and Fe during electrolysis may cause dynamic variation of the surface composition and structure of the catalysts. Here, we developed a NiMoFe heterostructure consisting of NiMoFe alloy and MoO42–-intercalated NiFe-LDH (NiMoFe HI), which enables self-optimization of HER and self-healing of OER through the dynamic exchange of MoO42– species. During the HER process, the leaching and readsorption of MoO42– optimizes the electronic structure of NiFe-LDH, facilitating H2O adsorption and dissociation. Simultaneously, the repulsion of OH– by accumulated MoO42– in the electric double layer can more rapidly drive the transfer kinetics of *OH + e ⇌ OH– to promote the desorption of *OH from the active sites, thus continuously enhancing the HER activity. During the OER process, the dynamic equilibrium of MoO42– facilitates the readsorption of active Fe(OH)x species on the NiFeOOH surface and reduces the energy barrier of the OER rate-determining step, achieving self-healing of the OER activity. Benefiting from the self-optimization and self-healing properties for HER and OER, NiMoFe LDH exhibits promising performance in alkaline water splitting, with a low cell voltage of 1.528 V at 10 mA·cm–2 and stable operation at a high current density of 100 mA·cm–2 for 150 h.    

    

* Selective Monoalkylation or Dialkylation of Indenes with Alcohols by Bis-N-Heterocyclic Carbene Manganese  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404616756
:TOPICS: Homogeneous Catalysis with Transition Metals, Carbon Dioxide Utilization for Chemical Synthesis, Transition Metal Catalysis
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05200")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404616756"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404616756"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404616756"))][Get cited by]]

OpenAlex: https://openalex.org/W4404616756 (Open access: False)
    
[[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5059248880][Yinwu Li]], [[https://openalex.org/A5100457743][Zhe Chen]], [[https://openalex.org/A5021086726][Cunyuan Zhao]], [[https://openalex.org/A5022393729][Zhuofeng Ke]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05200 
     
No abstract    

    

* Copper(I)-Catalyzed α,β-Dehydrogenative [2 + 3] Heteroannulation of Saturated Amines with Diaziridinone via Hydrogen Atom Transfer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404625202
:TOPICS: Catalytic C-H Amination Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05973")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404625202"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404625202"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404625202"))][Get cited by]]

OpenAlex: https://openalex.org/W4404625202 (Open access: False)
    
[[https://openalex.org/A5108765053][Zihang Du]], [[https://openalex.org/A5100445503][Jiahao Zhang]], [[https://openalex.org/A5085082124][Xueli Lv]], [[https://openalex.org/A5078975514][Kun Zhang]], [[https://openalex.org/A5056653009][Wei Ji]], [[https://openalex.org/A5102728277][Minyan Wang]], [[https://openalex.org/A5049924738][Su Jing]], [[https://openalex.org/A5018608098][Jiefeng Hu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05973 
     
The site-selective functionalization of carbon(sp3)–hydrogen bonds in saturated amines remains a persistent challenge owing to their intrinsic electronic deficiency, particularly in activating the α and β positions simultaneously for annulation reactions. Herein, we report a copper(I)-catalyzed dehydrogenation and [2 + 3] cycloaddition of commercially available amines with diaziridinone, which facilitated the direct synthesis of highly valuable imidazolidone derivatives. Operationally simple methodology has a broad substrate scope and convenient scalability, providing an effective and complementary platform for the rapid incorporation of N-heterocycles into amine molecules. Furthermore, comprehensive mechanistic investigations and computational studies indicated the pathway of the radical-type hydrogen atom transfer and [2 + 3] cycloaddition, which were promoted by a four-membered copper(III) species.    

    

* Interface Engineering on Heterostructural Nanosheets for Efficient Electrocatalytic-Paired Upcycling of Waste Plastics and Nitrate  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404627302
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Global E-Waste Recycling and Management
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05434")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404627302"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404627302"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404627302"))][Get cited by]]

OpenAlex: https://openalex.org/W4404627302 (Open access: False)
    
[[https://openalex.org/A5091903755][Junhua Wu]], [[https://openalex.org/A5025637935][Xiaoxiao Cheng]], [[https://openalex.org/A5072579187][Yun Tong]], [[https://openalex.org/A5101758085][Zhangjing Yu]], [[https://openalex.org/A5001207260][Lin Cong]], [[https://openalex.org/A5100721030][Nan Zhang]], [[https://openalex.org/A5100432090][Lu Chen]], [[https://openalex.org/A5078040238][Pengzuo Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05434 
     
No abstract    

    

* Photoenhanced Electrochemical Conversion of Nitrate to Ammonia Via Sulfur Vacancy-Rich Exfoliated MoS2  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404633846
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05730")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404633846"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404633846"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404633846"))][Get cited by]]

OpenAlex: https://openalex.org/W4404633846 (Open access: False)
    
[[https://openalex.org/A5016963397][Manan Guragain]], [[https://openalex.org/A5053424679][Alankar Kafle]], [[https://openalex.org/A5089967637][Qasim Adesope]], [[https://openalex.org/A5100279848][Mohammad K. Altafi]], [[https://openalex.org/A5100279849][Stella C. Amagbor]], [[https://openalex.org/A5022773093][V. V. Mesilov]], [[https://openalex.org/A5007169587][Jeffry A. Kelber]], [[https://openalex.org/A5030200062][Thomas R. Cundari]], [[https://openalex.org/A5062868414][Francis D’Souza]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05730 
     
Nitrate ion is a common pollutant in surface and groundwater. Hence, its catalytic conversion into ammonia at ambient conditions by electrochemical and photoelectrochemical pathways is an attractive alternative to current ammonia production from the energy-intensive and high-carbon-featuring Haber-Bosch process. As such, developing highly active and product-selective catalysts with good durability and cost-effectiveness is highly desired. In this work, exfoliated MoS2-x is reported as a highly active and selective electrocatalyst and a photoelectrocatalyst for nitrate reduction to ammonia. Exfoliation via the acid treatment of bulk MoS2 results in exfoliated MoS2-x, which is only a few layers thick and has a high degree of sulfur vacancies (ca. 12−13%). Electrochemical studies and electrolysis product analysis reveal promising nitrate reduction activity, which is found to be highly enhanced by the application of visible light illumination. The exfoliated MoS2-x achieves a Faradaic efficiency of 69% with an ammonia yield rate of 5.56 mmol gcat–1 h–1 in the absence of a light source, which is enhanced to 80% with an ammonia yield of 7.48 mmol gcat–1 h–1 upon visible light illumination. DFT calculations support the binding of nitrate and other NOx species to the sulfur vacancies, resulting in the formation of *N, which is then reduced to ammonia.    

    

* Artificially Created UDP-Glucose 2-Epimerase Enables Concise UDP/GDP-Mannose Production via the Synthase–Epimerase Route  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404637444
:TOPICS: Pancreatic Islet Dysfunction and Regeneration, Macromolecular Crystallography Techniques, Role of AMP-Activated Protein Kinase in Cellular Metabolism
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06698")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404637444"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404637444"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404637444"))][Get cited by]]

OpenAlex: https://openalex.org/W4404637444 (Open access: False)
    
[[https://openalex.org/A5100951735][Zhongbao Ma]], [[https://openalex.org/A5110530600][Liting Zhao]], [[https://openalex.org/A5100417382][Qiong Wang]], [[https://openalex.org/A5070308560][Yu Shen]], [[https://openalex.org/A5061322206][Mengmeng Xu]], [[https://openalex.org/A5100333458][Lei Chen]], [[https://openalex.org/A5034246486][Guiyang Shi]], [[https://openalex.org/A5001229547][Zhongyang Ding]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06698 
     
Uridine/guanosine diphosphate-mannose (UDP/GDP-Man) is the major mannosyl donor in producing mannose-containing oligo/polysaccharides. Its acquisition is greatly limited by its complex and costly synthetic process, which requires multiple substrates and enzymes. The natural UDP/GDP-glucose 2-epimerase functioning C2 epimerization between UDP/GDP-Glc and UDP/GDP-Man remains unreported which is the main hurdle to realize concise production of UDP/GDP-Man. Here, the UDP-glucose 2-epimerase (Glc2E), which behaves like a naturally evolved enzyme, is created and exhibits high-efficient catalysis in producing UDP-Man. Multidimensional engineering, including redesigning the nucleobase recognition region, displacement of the substrate tunnel entrance, and expansion of space for sugar ring rotation, is employed to develop Glc2E from CDP-tyvelose 2-epimerase. Glc2E converts 55.63% of UDP-Glc to UDP-Man, a trace value for the initial enzyme, stTyvE, and its aptitude for GDP-Glc epimerization evolves from unobserved activity to 23.94% conversion. Coupling sucrose synthase with Glc2E achieves the theoretical synthase–epimerase route for UDP/GDP-Man production from inexpensive sucrose. The space-time-yield of UDP-Man is maximized to 8.05 g/L/h within 2.5 h, with a final titer of 22.54 g/L, demonstrating competitive application potential. Moreover, the GDP-Man is synthesized successfully at a titer of 3.49 g/L. Our work inspires the enzyme engineering for epimerases and glycosyltransferases that catalyze nucleotide sugars. The application of Glc2E in the synthase–epimerase route unlocks a concise and feasible synthetic approach for producing cost-competitive mannosyl donors.    

    

* Strategies for Designing Advanced Transition Metal-Based Electrocatalysts for Alkaline Water/Seawater Splitting at Ampere-Level Current Densities  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404639546
:TOPICS: Electrocatalysis for Energy Conversion, Science and Technology of Capacitive Deionization for Water Desalination, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06509")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404639546"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404639546"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404639546"))][Get cited by]]

OpenAlex: https://openalex.org/W4404639546 (Open access: False)
    
[[https://openalex.org/A5100438872][Xian Zhang]], [[https://openalex.org/A5068671808][Ziteng Zuo]], [[https://openalex.org/A5077747966][Chengzhu Liao]], [[https://openalex.org/A5084555852][Feifei Jia]], [[https://openalex.org/A5080674562][Chun Cheng]], [[https://openalex.org/A5102137665][Zhiguang Guo]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06509 
     
No abstract    

    

* Shapeshifting Ligands Mask Lewis Acidity of Dicationic Palladium(II)  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404639741
:TOPICS: Transition Metal Catalysis, Homogeneous Catalysis with Transition Metals, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06539")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404639741"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404639741"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404639741"))][Get cited by]]

OpenAlex: https://openalex.org/W4404639741 (Open access: False)
    
[[https://openalex.org/A5049613175][Karli Sipps]], [[https://openalex.org/A5113143672][Wyatt Gibbs]], [[https://openalex.org/A5064263858][Elvira R. Sayfutyarova]], [[https://openalex.org/A5001390883][Jonathan L. Kuo]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06539 
     
Supporting ligands limit the degree of electrophilic activation for any substrate because they also reduce the Lewis acidity of the transition metal ion. Here, we temporarily mask the Lewis acidity of dicationic Pd(II) by using "shapeshifting" bidentate pyrimidine/olefin ligands L1 and L2. These ligands delocalize/relocalize charge via reversible C–N bond formation. So, although ligated dicationic Pd compounds [1]2+ and [2]2+ appear charge separated (distributed across Pd and ligand), they react comparably to a solvated Pd(II) dication. Despite reacting like strong Lewis acids, the complexes are tolerant of polar functional groups (Lewis bases that often inhibit electrophilic catalysis). We propose that this property originates from the installation of a more nucleophilic (charge separated) state. This case study suggests that catalysts featuring reversible dynamics can be advantageous relative to their structurally static counterparts.    

    

* Comparison of Low Temperature Methanol Aqueous Phase Reforming Catalysts─Definition of Standardized Reaction Conditions and Considerations toward Applications  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404644315
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05489")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404644315"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404644315"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404644315"))][Get cited by]]

OpenAlex: https://openalex.org/W4404644315 (Open access: True)
    
[[https://openalex.org/A5004595589][H. KEMPF]], [[https://openalex.org/A5007038220][Henrik Junge]], [[https://openalex.org/A5005182277][Matthias Beller]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05489  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c05489?ref=article_openPDF][pdf]])
     
A comparison of state-of-the-art catalysts for low temperature aqueous phase reforming (APR) of methanol is presented. To facilitate future applications, catalyst tests under two standardized sets of reaction conditions are proposed.    

    

* Fine Ru-Ru2P Heterostructure Enables Highly Active and Selective CO2 Hydrogenation to CO  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404645067
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-11-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05369")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404645067"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404645067"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404645067"))][Get cited by]]

OpenAlex: https://openalex.org/W4404645067 (Open access: False)
    
[[https://openalex.org/A5071314714][Shidong Bao]], [[https://openalex.org/A5100985710][Lanqing Yang]], [[https://openalex.org/A5022382869][Heyun Fu]], [[https://openalex.org/A5054639150][Xiaolei Qu]], [[https://openalex.org/A5088022479][Shourong Zheng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05369 
     
No abstract    

    

* Understanding the Role of the Surface Acidity of MFI Zeolites during LDPE Cracking: Decomposition Temperature and Product Distribution  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404645079
:TOPICS: Global E-Waste Recycling and Management, Zeolite Chemistry and Catalysis, Microplastic Pollution in Marine and Terrestrial Environments
:PUBLICATION_DATE: 2024-11-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06190")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404645079"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404645079"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404645079"))][Get cited by]]

OpenAlex: https://openalex.org/W4404645079 (Open access: False)
    
[[https://openalex.org/A5110996826][Soshi Tsubota]], [[https://openalex.org/A5048171931][Shinya Kokuryo]], [[https://openalex.org/A5015714653][Koji Miyake]], [[https://openalex.org/A5034128142][Yoshiaki Uchida]], [[https://openalex.org/A5017875070][Atsushi Mizusawa]], [[https://openalex.org/A5071666227][Tadashi Kubo]], [[https://openalex.org/A5109491127][Norikazu Nishiyama]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06190 
     
No abstract    

    

* Anionic Surfactant-Tuned Interfacial Water Reactivity Promoting Electrocatalytic CO2 Reduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404646427
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-11-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05541")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404646427"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404646427"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404646427"))][Get cited by]]

OpenAlex: https://openalex.org/W4404646427 (Open access: False)
    
[[https://openalex.org/A5065419997][Wangxin Ge]], [[https://openalex.org/A5067580654][Yihua Zhu]], [[https://openalex.org/A5100354474][Haiyan Wang]], [[https://openalex.org/A5087914705][Hongliang Jiang]], [[https://openalex.org/A5009144836][Chunzhong Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05541 
     
The effects of the electrical double layer (EDL), which pertain to the compositions and interactions among electrolyte species, significantly impact the catalytic process. There is a pressing need to investigate the role of electrolyte components and to deepen our understanding of EDL effects. In this study, we tune the water activity within a range of anionic surfactants featuring different functional groups to adjust H2 evolution activity and CO2 reduction selectivity. We demonstrate that these anionic surfactants are active in the local reaction environment under a cathodic potential. The enhanced selectivity of CO2 to CO can be attributed to the robust interfacial hydrogen-bonding network reformed by the anionic surfactants. This network diminishes the water dissociation activity and promotes the hydrogenation step in CO2 reduction. Notably, the electrolyte incorporating anionic surfactants improves the CO2 reduction performance, registering CO Faradaic efficiencies of 89.7% (RSO3–, SDS), 97.5% (RSO4–, SLS), 98.4% (RPO42–, SMP), and 98.9% (RCOO–, SL) at −1.2 V versus RHE, thereby outperforming the blank KHCO3 electrolyte (53.1%). This research underscores the crucial influence of anionic additives in the CO2RR.    

    

* C–H Activation and Sequential Addition to Dienes and Imines: Synthesis of Amines with β-Quaternary Centers and Mechanistic Studies on the Complex Interplay Between the Catalyst and Three Reactants  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404650722
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Homogeneous Catalysis with Transition Metals, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05866")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404650722"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404650722"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404650722"))][Get cited by]]

OpenAlex: https://openalex.org/W4404650722 (Open access: False)
    
[[https://openalex.org/A5114761851][Ramsey M. Goodner]], [[https://openalex.org/A5055983740][Daniel S. Brandes]], [[https://openalex.org/A5093463348][Gabriel N. Morais]], [[https://openalex.org/A5102803349][Tao Qin]], [[https://openalex.org/A5083889671][Joseph P. Tassone]], [[https://openalex.org/A5038732109][Brandon Q. Mercado]], [[https://openalex.org/A5100644316][Shuming Chen]], [[https://openalex.org/A5012406363][Jonathan A. Ellman]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05866 
     
No abstract    

    

* Halloysite Clay Nanotubes for Catalytic Conversion of Biomass: Synergy between Computational Modeling and Experimental Studies  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404678088
:TOPICS: Applications of Clay Nanotubes in Various Fields, Solar Water Splitting Technology, Layered Double Hydroxide Nanomaterials
:PUBLICATION_DATE: 2024-11-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05907")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404678088"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404678088"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404678088"))][Get cited by]]

OpenAlex: https://openalex.org/W4404678088 (Open access: False)
    
[[https://openalex.org/A5058782253][Lorenzo Lisuzzo]], [[https://openalex.org/A5094305418][Ludovico Guercio]], [[https://openalex.org/A5090172326][Giuseppe Cavallaro]], [[https://openalex.org/A5016999361][Dario Duca]], [[https://openalex.org/A5003110091][Francesco Ferrante]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05907 
     
Halloysite clay nanotubes (HNTs) are emerging nanomaterials for numerous environmental applications, including catalysis and biomass valorization. The efficacy of halloysite as a nanoplatform for the catalytic conversion of biomass can be accurately evaluated by combined approaches based on experimental investigations and computational modeling. Recently, many efforts have been made to properly describe the most peculiar features of halloysite by focusing on its structural and interfacial features through computational studies, which are challenging for natural clay nanoparticles yet crucial for the design of novel catalysts to be exploited in biomass conversion. Within this framework, this review critically and extensively discusses recent advancements related to the use of halloysite in different catalytic processes, such as enzymatic reactions, precious- and nonprecious-metal- and alloy-catalyzed reactions, and acid-activated mechanisms. The research gap on the computational modeling of biomass chemical conversion occurring on halloysite surfaces is highlighted throughout this review, together with the latest experimental achievements. To optimize the catalytic efficiency of halloysite-based materials for biomass valorization, future efforts should focus on the implementation of experimental data with calculations provided by proper models in a synergistic approach.    

    

* Generation of Nickel Siloxycarbene Complexes from Acylsilanes for the Catalytic Synthesis of Silyl Enol Ethers  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404685890
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-11-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06272")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404685890"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404685890"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404685890"))][Get cited by]]

OpenAlex: https://openalex.org/W4404685890 (Open access: False)
    
[[https://openalex.org/A5071463894][Akihisa Matsuura]], [[https://openalex.org/A5078161608][Yuri Ito]], [[https://openalex.org/A5083054687][Tetsuya Inagaki]], [[https://openalex.org/A5068368402][Takuya Kodama]], [[https://openalex.org/A5001454525][Mamoru Tobisu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06272 
     
A catalytic protocol has been developed to access Fischer carbene nickel complexes using acylsilanes as stable and readily available precursors. The as-generated Fischer carbene complexes exhibit versatile reactivity, including cyclopropanation with alkenes, α-C–H insertion reactions, and two-component C–H addition to norbornene, which demonstrates the broad utility of the nickel(0)/acylsilane system for the catalytic applications of Fischer carbene complexes.    

    
