#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sun Feb  4 14:23:20 2024

Found 25 results from 2024-01-21 to 2024-02-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Photoexcited Nickel-Catalyzed Carbohalogenation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391096631
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05994")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391096631"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391096631"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391096631"))][Get cited by]]

OpenAlex: https://openalex.org/W4391096631 (Open access: False)
    
[[https://openalex.org/A5070646877][Ramon Arora]], [[https://openalex.org/A5044555614][Mark Lautens]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05994 
     
A nickel/blue light-catalyzed carbohalogenation reaction is reported. A nickel catalyst and an inexpensive phosphine ligand promote the reaction of aryl iodides and aryl bromides with π systems to enable the construction of a library of halogenated heterocyclic scaffolds. Mechanistic studies provide insight regarding fundamental steps of the catalytic cycle, including the reversible C–X bond formation via deuterium labeling and EPR experiments, while preliminary enantioselective results suggest a two-electron migratory insertion.    

    

* Atomic Single-Layer Ir Clusters Enabling 100% Selective Chlorine Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391096719
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05738")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391096719"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391096719"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391096719"))][Get cited by]]

OpenAlex: https://openalex.org/W4391096719 (Open access: False)
    
[[https://openalex.org/A5061084605][Shuang Li]], [[https://openalex.org/A5040981831][Xu Guo]], [[https://openalex.org/A5086532814][Xiaofang Liu]], [[https://openalex.org/A5017390855][Jianglan Shui]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05738 
     
The exclusive selectivity of the chlorine evolution reaction (CER) is crucial for the chlor-alkali industry to obtain pure chlorine gas and avoid the cost of separating the byproduct oxygen. However, 100% CER selectivity remains a challenge for the currently known CER catalysts. Here, we report a catalyst of atomic single-layer Ir clusters on CeO2 nanorods (IrSL/CeO2). Under the strong metal/support interaction, IrSL has a strong adsorption to oxygen, thereby suppressing the oxygen evolution reaction. Coupled with the uniform active sites of the single-layer Ir clusters, IrSL/CeO2 achieves almost 100% CER selectivity in acidic NaCl solution ranging from open circuit potential to practical current density levels. In addition, IrSL/CeO2 exhibits 1.7 times higher catalytic activity than its single-atom counterparts, and its noble metal efficiency is 84 times higher than that of commercial anodes (DSAs). Our finding provides a solution to the selective catalysis of chlor-alkali electrolysis.    

    

* Correction to “Iterative Dual-Metal and Energy Transfer Catalysis Enables Stereodivergence in Alkyne Difunctionalization: Carboboration as Case Study”  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391096721
:TOPICS: Frustrated Lewis Pairs Chemistry, Accelerating Materials Innovation through Informatics, Peptide Synthesis and Drug Discovery
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00200")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391096721"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391096721"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391096721"))][Get cited by]]

OpenAlex: https://openalex.org/W4391096721 (Open access: True)
    
[[https://openalex.org/A5057405142][Javier Corpas]], [[https://openalex.org/A5056234005][Miguel Gomez‐Mendoza]], [[https://openalex.org/A5061447263][Enrique M. Arpa]], [[https://openalex.org/A5084324626][Víctor A. de la Peña O’Shea]], [[https://openalex.org/A5071658976][Bo Durbeej]], [[https://openalex.org/A5065650028][Juan C. Carretero]], [[https://openalex.org/A5073576671][Pablo Mauleón]], [[https://openalex.org/A5051017883][Ramón Goméz Arrayás]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00200  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00200][pdf]])
     
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVCorrectionNEXTORIGINAL ARTICLEThis notice is a correctionCorrection to “Iterative Dual-Metal and Energy Transfer Catalysis Enables Stereodivergence in Alkyne Difunctionalization: Carboboration as Case Study”Javier CorpasJavier CorpasMore by Javier Corpashttps://orcid.org/0000-0002-8598-578X, Miguel Gomez-MendozaMiguel Gomez-MendozaMore by Miguel Gomez-Mendoza, Enrique M. ArpaEnrique M. ArpaMore by Enrique M. Arpahttps://orcid.org/0000-0003-1288-6059, Víctor A. de la Peña O’SheaVíctor A. de la Peña O’SheaMore by Víctor A. de la Peña O’Sheahttps://orcid.org/0000-0001-5762-4787, Bo DurbeejBo DurbeejMore by Bo Durbeejhttps://orcid.org/0000-0001-5847-1196, Juan C. CarreteroJuan C. CarreteroMore by Juan C. Carreterohttps://orcid.org/0000-0003-4822-5447, Pablo Mauleón*Pablo MauleónMore by Pablo Mauleónhttps://orcid.org/0000-0002-3116-2534, and Ramón Gómez Arrayás*Ramón Gómez ArrayásMore by Ramón Gómez Arrayáshttps://orcid.org/0000-0002-5665-0905Cite this: ACS Catal. 2024, 14, XXX, 1976Publication Date (Web):January 22, 2024Publication History Received10 January 2024Published online22 January 2024https://doi.org/10.1021/acscatal.4c00200© 2024 The Authors. Published by American Chemical Society. This publication is licensed under CC-BY 4.0. License Summary*You are free to share (copy and redistribute) this article in any medium or format and to adapt (remix, transform, and build upon) the material for any purpose, even commercially within the parameters below:Creative Commons (CC): This is a Creative Commons license.Attribution (BY): Credit must be given to the creator.View full license*DisclaimerThis summary highlights only some of the key features and terms of the actual license. It is not a license and has no legal value. Carefully review the actual license before using these materials. This publication is Open Access under the license indicated. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InReddit PDF (567 KB) Get e-AlertscloseSUBJECTS:Catalysis,Energy transfer,Hydrocarbons,Stereodivergence Get e-Alerts    

    

* Subsurface Mo Vacancy in Bismuth Molybdate Promotes Photocatalytic Oxidation of Lactate to Pyruvate  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391096818
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05263")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391096818"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391096818"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391096818"))][Get cited by]]

OpenAlex: https://openalex.org/W4391096818 (Open access: False)
    
[[https://openalex.org/A5011353374][Haijun Chen]], [[https://openalex.org/A5016434653][Ruohan Xu]], [[https://openalex.org/A5078465675][Dan Chen]], [[https://openalex.org/A5003515526][Tianliang Lu]], [[https://openalex.org/A5058250981][H. Li]], [[https://openalex.org/A5038241246][Min Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05263 
     
Disclosing the role of subsurface metal defects in photocatalysts remains challenging, although defect engineering has been a fundamental method for manipulating the photocatalytic transformation performance. Herein, the subsurface Mo vacancy-rich Bi2MoO6 was prepared and the role of its effects on photocatalysis was revealed. The presence of metal vacancy enhances the separation efficiency of photogenerated carriers through both the holes captured by the oxygen atoms neighboring the Mo vacancy and the generation of an internal electric field, which is revealed by experimental results and density functional theory calculations. The boosted separation efficiency of electron–hole pairs improves the generation of 1O2, which is the final active species for photocatalytic oxidation of ethyl lactate. The conversion of ethyl lactate reaches to >99% over the subsurface Mo vacancy-rich Bi2MoO6 after 3 h of illumination, much higher than that of bulk Bi2MoO6, which gives only 28.6%. Meanwhile, the yield of ethyl pyruvate is 90.2%, which is the highest value in heterogeneous systems using molecular oxygen as oxidant. Moreover, the catalyst is rather stable and can be applied for the selective oxidation of other hydroxyl compounds. This work unveils the role of metal defects engineering in affecting electron–hole separation, highlighting possible opportunities for highly efficient photocatalytic organic transformation.    

    

* Boosting Artificial Photosynthesis: CO2 Chemisorption and S-Scheme Charge Separation via Anchoring Inorganic QDs on COFs  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391101394
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00026")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391101394"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391101394"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391101394"))][Get cited by]]

OpenAlex: https://openalex.org/W4391101394 (Open access: False)
    
[[https://openalex.org/A5085724938][Yuehui He]], [[https://openalex.org/A5057304484][Peiyu Hu]], [[https://openalex.org/A5028576381][J.C. Zhang]], [[https://openalex.org/A5077280830][Guijie Liang]], [[https://openalex.org/A5065418938][Yuanyuan Wang]], [[https://openalex.org/A5004139159][Fei Xu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00026 
     
Photocatalytic conversion of CO2 into valuable hydrocarbon fuels holds great promise in addressing emerging energy shortages and environmental crises while fulfilling pressing societal and national development demands. Nonetheless, its efficiency is hindered by restricted CO2 chemisorption, rapid electron–hole recombination, and weak redox capability. Drawing inspiration from the distinctive characteristics of Schiff-based covalent organic frameworks (COFs), including substantial specific surface area, unique pore structure, and an abundance of weakly alkaline nitrogen elements, we employ the TPA-COF to enhance the chemisorption and activation of acidic CO2 molecules, as validated by the CO2-temperature-programmed desorption analysis. Furthermore, anchoring CsPbBr3 quantum dots (QDs) onto the COF facilitates the effective spatial separation of photoinduced charge carriers with strong redox capability, resulting from the formation of S-scheme heterojunctions between the COF and QDs as substantiated by in situ irradiation X-ray photoelectron spectroscopy, femtosecond transient absorption spectroscopy, and density functional theory simulations. As anticipated, the optimized COF/QDs heterostructures exhibit remarkable enhancements in CO2 photoreduction performance in the absence of any molecule cocatalyst or scavenger, yielding CO and CH4 at rates of 41.2 and 13.7 μmol g–1, respectively. This work provides valuable insights into the development of novel organic/inorganic heterojunction photocatalysts with CO2 chemisorption and S-scheme charge separation, offering great potential for sustainable artificial photosynthesis.    

    

* Unraveling Hydrogenation Kinetic Behavior of Transition Metal Oxides via Decoupling Dihydrogen Dissociation and Substrate Activation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391101416
:TOPICS: Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05175")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391101416"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391101416"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391101416"))][Get cited by]]

OpenAlex: https://openalex.org/W4391101416 (Open access: False)
    
[[https://openalex.org/A5018575667][Daowei Gao]], [[https://openalex.org/A5018575667][Daowei Gao]], [[https://openalex.org/A5089414995][Yipin Lv]], [[https://openalex.org/A5081193140][Changxu Wang]], [[https://openalex.org/A5063319137][Jianyu Ren]], [[https://openalex.org/A5035137918][Peng Zheng]], [[https://openalex.org/A5024283781][Lianghao Song]], [[https://openalex.org/A5073931528][Aijun Duan]], [[https://openalex.org/A5074059492][Xilong Wang]], [[https://openalex.org/A5019425961][Guozhu Chen]], [[https://openalex.org/A5042785211][Xu Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05175 
     
Both noble metals and transition metal oxides are recognized as active centers for alkyne hydrogenation. However, it is still a “black box” how the catalytic behavior of oxides evolves upon the catalytic intervention of noble metals. Herein, we report a modularized strategy to track the hydrogenation mechanism of oxides (e.g., TiO2, CeO2, and ZrO2) using a core–shell micromesoporous zeolite as a structure model, in which the oxide and noble metal (Pt) are functionally separated within a mesopore shell and a micropore core (TS-1 zeolite), respectively. The Pt species are atomically distributed and stabilized by the oxygen atoms of five-membered rings in TS-1 zeolite, which facilitates the heterolytic activation of dihydrogen over Ptδ+···O2– units. The active hydrogen species, i.e., H+ and Hδ−, migrate to the oxide surface, where the adsorbed reactants are activated for hydrogenation. Mechanistic studies reveal that TiO2, CeO2, and ZrO2 possess efficient hydrogenation properties at near-room temperature with the assistance of spillover hydrogen species, demonstrating dihydrogen dissociation as the main rate-limiting step for pure oxide. Impressively, the adsorbed H2O molecule on TiO2, ZrO2, and CeO2 not only acts as a bridge of hydrogen spillover in reducing the proton diffusion barrier but also forms H3O+ species on the TiO2 (100) surface and endows TiO2 with extraordinary hydrogenation properties. This work opens the “black box” for the hydrogenation behavior of transition metal oxides and develops a molecule-assisted strategy for the rational design of hydrogenation catalysts.    

    

* Vacancy Optimized Coordination on Nickel Oxide for Selective Electrocatalytic Oxidation of Glycerol  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391101830
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04568")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391101830"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391101830"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391101830"))][Get cited by]]

OpenAlex: https://openalex.org/W4391101830 (Open access: False)
    
[[https://openalex.org/A5087905494][Zhongcheng Xia]], [[https://openalex.org/A5002167538][Chongyang Ma]], [[https://openalex.org/A5003974306][Yun Fan]], [[https://openalex.org/A5049726262][Yuxuan Lu]], [[https://openalex.org/A5080759059][Yu‐Cheng Huang]], [[https://openalex.org/A5041164393][Yuping Pan]], [[https://openalex.org/A5031014591][Yandong Wu]], [[https://openalex.org/A5035965198][Qingyu Luo]], [[https://openalex.org/A5071476959][Yuanqing He]], [[https://openalex.org/A5047174251][Chung‐Li Dong]], [[https://openalex.org/A5042902756][Shuangyin Wang]], [[https://openalex.org/A5037963525][Yuqin Zou]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04568 
     
The production of high-value-added organics by the glycerol oxidation reaction (GOR) holds significant research importance for addressing the surplus production of glycerol and mitigating the energy crisis. In this study, we report a vacancy optimized coordination on nickel oxide for the selective electrocatalytic oxidation of glycerol. Using in situ Raman and electron paramagnetic resonance spectroscopy, the formation of vacancies was traced during the cationic leaching process. Subsequently, in situ attenuated total reflection surface-enhanced IR absorption spectroscopy and density functional theory calculations revealed a significantly enhanced adsorption capacity and optimized co-adsorption process of OH– and organics. Consequently, NiCrO with vacancies (NiCrO-VCr,O) exhibited GOR performance with conversion, formic acid selectivity, and faradaic efficiency values of 99%, 98%, and 96%, respectively. Notably, the conversion and selectivity in the flow electrolyzer remained above 90% during long-time continuous electrolysis, highlighting its industrial applicability. This study provides constructive guidance for the design of electrocatalysts, the optimization of the catalyst ligand environment, and the development of high-performance, metal-based catalysts for glycerol electro-oxidation.    

    

* In Situ Restructuring of ZnCr2O4 Spinel Catalyst Alters Elementary Surface Reaction Kinetics and Catalytic Selectivity in CO Hydrogenation Reaction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391102226
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05739")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391102226"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391102226"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391102226"))][Get cited by]]

OpenAlex: https://openalex.org/W4391102226 (Open access: False)
    
[[https://openalex.org/A5074267018][Qiulin Nie]], [[https://openalex.org/A5057420080][Jieqiong Ding]], [[https://openalex.org/A5037176334][Dongdong Wang]], [[https://openalex.org/A5038931702][Yang Liu]], [[https://openalex.org/A5008776627][Wei Xiong]], [[https://openalex.org/A5042377211][Yong Yang]], [[https://openalex.org/A5019823705][Weixin Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05739 
     
The CO hydrogenation reaction catalyzed by the ZnCr2O4 catalyst is studied using quasi-in situ XPS, temperature-programmed reaction spectroscopy, and temporal in situ diffuse reflectance Fourier transform infrared spectroscopy. At 573 K, the ZnCr2O4 catalyst selectively catalyzes the CH3OH formation reaction, in which the hydrogenation reaction of monodentate formate species is the rate-limiting step with an activation energy of approximately 60.5 kJ/mol. As the temperature increases to 673 K, CO2 and CH4 are produced at the expense of CH3OH, which can be attributed to in situ partial reduction of the ZnCr2O4 catalyst into metallic Zn. On one hand, the CO disproportionation reaction into CO2 and atomic carbon species occurs on the resulting metallic Zn, and the atomic carbon species is subsequently hydrogenated predominantly into CH4; on the other hand, the rate-limiting step of methanol synthesis on the resulting partially reduced ZnCr2O4 catalyst becomes the hydrogenation of the methoxy group with an activation energy of approximately 120.3 kJ/mol, considerably reducing the CH3OH formation rate. These results unveil that the changes in the elementary surface reaction network and the kinetics induced by in situ restructuring of the ZnCr2O4 catalyst in the CO hydrogenation reaction lead to the changes in catalytic selectivity.    

    

* Amorphous Ruthenium–Selenium Nanoparticles as a pH-Universal Catalyst for Enhanced Hydrogen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391105420
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04498")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391105420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391105420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391105420"))][Get cited by]]

OpenAlex: https://openalex.org/W4391105420 (Open access: False)
    
[[https://openalex.org/A5076636884][Ting Zhu]], [[https://openalex.org/A5083086913][Junnan Han]], [[https://openalex.org/A5087472646][Teng Sun]], [[https://openalex.org/A5017004383][Junhua Zhao]], [[https://openalex.org/A5043023473][Xiaodong Pi]], [[https://openalex.org/A5071195238][Jun Xu]], [[https://openalex.org/A5086257118][Kunji Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04498 
     
In order to broaden the applications of water splitting for hydrogen production, it is highly desired to develop an ideal catalyst, which can operate in a wide pH range. In this work, we proposed amorphous RuSex nanoparticles (NPs) with a highly disordered structure to introduce abundant surface defects, which contribute to the enhanced HER activity. The optimized RuSe1.5 NPs exhibited the pH-universal activity, which only require an overpotential of 24, 30, and 12 mV to reach a current density of 10 mA cm–2 in 0.5 M H2SO4 (pH = 0), 1 M PBS (pH = 7), and 1 M KOH (pH = 14), respectively. By capitalizing on the synergistic effect between Ru and Se, we have successfully achieved a balance in the strong adsorption of reaction intermediates on Ru sites and significantly improved the performance of HER. This work highlights the crucial role of understanding and harnessing the elemental synergies in the development of optimized HER catalysts and paves the way for the advancement of hydrogen production.    

    

* A Comprehensive Analysis of the Overpotential Losses in Polymer Electrolyte Fuel Cells  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391106654
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04797")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391106654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391106654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391106654"))][Get cited by]]

OpenAlex: https://openalex.org/W4391106654 (Open access: False)
    
[[https://openalex.org/A5086548322][Meriem Fikry]], [[https://openalex.org/A5003084717][Álvaro García-Padilla]], [[https://openalex.org/A5015235383][Juan Herranz]], [[https://openalex.org/A5017983630][Pavel Khavlyuk]], [[https://openalex.org/A5045801140][Alexander Eychmüller]], [[https://openalex.org/A5084722596][Thomas J. Schmidt]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04797 
     
Polymer electrolyte fuel cells (PEFCs) are expected to play a pivotal role in heavy-duty transportation, but careful benchmarking of the kinetics of the O2-reduction reaction (ORR) and mass transport properties dictating their performance is needed to render them market-competitive. This assessment generally relies on the extrapolation of the kinetic behavior observed at low current densities to the high currents at which mass transport limitations become significant. However, this kinetic regime is generally assumed to obey a simple Tafel law that does not consider the impact of the relative humidity (RH) on the availability of ORR-active sites. To shed light on the implications of this simplified approach, in this study, we compare the ORR parameters and mass transport losses derived from it with those computed using a more complex kinetic model that incorporates site-availability effects. Our results provide an original insight on the impact of the relative humidity on the ORR-performance of catalysts with different active site distributions and show that the mass transport resistances derived by these two quantification procedures are essentially identical as long as the slope of the kinetic Tafel line is adjusted according to the RH.    

    

* Cobalt/Organophotoredox Dual-Catalysis-Enabled Cyclization of 1,5,10-Enediynes Involving Metallole-Mediated Remote C(sp3)–H Bond Activation Leading to Axially Chiral Aryl Alkenes  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391127033
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Atroposelective Synthesis of Axially Chiral Compounds, Gold Catalysis in Organic Synthesis
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05848")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391127033"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391127033"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391127033"))][Get cited by]]

OpenAlex: https://openalex.org/W4391127033 (Open access: False)
    
[[https://openalex.org/A5047751068][Keiji Yamada]], [[https://openalex.org/A5021992456][Nobuaki Koga]], [[https://openalex.org/A5046468786][Takeshi Yasui]], [[https://openalex.org/A5067407925][Yoshihiko Yamamoto]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05848 
     
Transition-metal-catalyzed C(sp3)–H functionalization has been much less investigated compared to C(sp2)–H functionalization because the site-selectivity control in C(sp3)–H bond activation is much more challenging than that in C(sp2)–H bond activation. Site-selective C(sp3)–H functionalization without the assistance of directing groups is highly desirable, because the installation and removal of directing groups are not required. Hence, cycloaddition through a site-selective C–H bond activation triggered by the formation of metallacycles, such as metalloles, is a highly atom- and step-economical method for synthesizing complex carbo- and heterocycles from simple unsaturated substrates. Herein, we report the cobalt/photoredox dual-catalysis-enabled cyclization of 1,5,10-enediynes via remote C(sp3)–H bond activation triggered by metallole formation, affording axially chiral aryl alkenes. Several control experiments and theoretical calculations suggest that the C(sp3)–H bond cleavage proceeds through σ-complex-assisted metathesis (σ-CAM) in the metallole intermediate.    

    

* Cooperative Interplay of Micropores/Mesopores of Hierarchical Zeolite in Chemical Production  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391131566
:TOPICS: Zeolite Chemistry and Catalysis, Mesoporous Materials, Catalytic Nanomaterials
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05170")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391131566"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391131566"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391131566"))][Get cited by]]

OpenAlex: https://openalex.org/W4391131566 (Open access: False)
    
[[https://openalex.org/A5024536636][Susung Lee]], [[https://openalex.org/A5024611426][Younghwan Park]], [[https://openalex.org/A5041659236][Minkee Choi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05170 
     
Zeolites are crystalline microporous aluminosilicates that play a crucial role as solid acid catalysts in refinery and petrochemical processes. Over the past decades, hierarchical zeolites containing secondary mesopores in addition to micropores have been extensively investigated to mitigate the mass transfer limitations of conventional zeolites and improve the catalytic activity, selectivity, and longevity. The hierarchical structuring of zeolites not only improves mass transfer but also changes the distribution of acid sites and adsorption of reaction intermediates, which collectively affect the final catalytic properties of zeolites. In this Perspective, we will discuss the distinctive structural features of hierarchical zeolites compared to conventional ones, as well as their catalytic consequences in industrially relevant reactions for efficient fuel and chemical production.    

    

* Deep Insight into Characterizing the Metal–Support Interface in Heterogeneous Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391136449
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04930")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391136449"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391136449"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391136449"))][Get cited by]]

OpenAlex: https://openalex.org/W4391136449 (Open access: False)
    
[[https://openalex.org/A5000835247][Junhong Liu]], [[https://openalex.org/A5085145270][Liwei Chen]], [[https://openalex.org/A5075495928][Xi Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04930 
     
Supported metal species are widely used as catalysts in heterogeneous catalysis. Apart from the extended metal surfaces, metal–support interfaces also play a crucial role in catalytic performance due to their distinct electronic and geometric structures. However, the complexity and diversity of the metal–support interfaces hinder further understanding of the nature of the active sites for catalytic reactions. Fortunately, recent advancements in characterization techniques have uncovered deeper insights. This Perspective aims to comprehensively summarize recent breakthroughs in characterizing metal–support interfaces in heterogeneous catalysts. This summary facilitates the interpretation of these interfaces from both macroscopic and microscopic aspects, ultimately contributing to a fundamental understanding of the structure–activity relationship.    

    

* Modular Synthesis of Complex Benzoxaboraheterocycles through Chelation-Assisted Rh-Catalyzed [2 + 2 + 2] Cycloaddition  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391157080
:TOPICS: Frustrated Lewis Pairs Chemistry, Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391157080"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391157080"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391157080"))][Get cited by]]

OpenAlex: https://openalex.org/W4391157080 (Open access: True)
    
[[https://openalex.org/A5050756096][John M. Halford-McGuff]], [[https://openalex.org/A5025865092][Marek Varga]], [[https://openalex.org/A5027145763][David B. Cordes]], [[https://openalex.org/A5030357365][Aidan P. McKay]], [[https://openalex.org/A5006881457][Allan J. B. Watson]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05766  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05766][pdf]])
     
Benzoxaboraheterocycles (BOBs) are moieties of increasing interest in the pharmaceutical industry; however, the synthesis of these compounds is often difficult or impractical due to the sensitivity of the boron moiety, the requirement for metalation–borylation protocols, and lengthy syntheses. We report a straightforward, modular approach that enables access to complex examples of the BOB framework through a Rh-catalyzed [2 + 2 + 2] cycloaddition using MIDA-protected alkyne boronic acids. The key to the development of this methodology was overcoming the steric barrier to catalysis by leveraging chelation assistance. We show the utility of the method through synthesis of a broad range of BOB scaffolds, mechanistic information on the chelation effect, intramolecular alcohol-assisted BMIDA hydrolysis, and linear/cyclic BOB limits as well as comparative binding affinities of the product BOB frameworks for ribose-derived biomolecules.    

    

* Switching the Oxygen Reduction Route on Pt Using S through d–p Hybridization  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391166858
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Perovskite Solar Cell Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05362")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391166858"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391166858"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391166858"))][Get cited by]]

OpenAlex: https://openalex.org/W4391166858 (Open access: False)
    
[[https://openalex.org/A5012605722][Maosong Huang]], [[https://openalex.org/A5049950193][Zipei Cui]], [[https://openalex.org/A5090464557][Zhuo Li]], [[https://openalex.org/A5035964409][Wenchao Sheng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05362 
     
The development of electrocatalysts capable of selective two-electron oxygen reduction reactions (ORRs) has become a major obstacle in the electrochemical synthesis of H2O2. Herein, a series of platinum sulfide catalysts with different sulfur contents were synthesized by a chemical vapor deposition method. The two-electron ORR performance exhibited a “volcano” plot relationship with the sulfur content of the catalysts. The PtS1.38/C catalyst with optimal sulfur content achieved a two-electron ORR selectivity of 92% at near zero overpotential and a mass activity of 70.5 A gPt–1 [0.65 V vs reversible hydrogen electrode (RHE)]. Combined spectroscopic studies and density functional theory calculations showed that the introduction of sulfur changed the d band structure of the Pt surface and in turn the binding energy of oxygen-containing species. The PtS1.38/C catalyst was capable of stable batch electrosynthesis of hydrogen peroxide in an H-cell, maintaining a high productivity of 992 mmolH2O2 g–1cat h–1 (0.2 V vs RHE), which has great potential for practical applications.    

    

* Steric Effects on CO2 Reduction with Substituted Mn(bpy)(CO)3X-Type Catalysts on Multiwalled Carbon Nanotubes Reveal Critical Mechanistic Details  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391166871
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05771")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391166871"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391166871"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391166871"))][Get cited by]]

OpenAlex: https://openalex.org/W4391166871 (Open access: False)
    
[[https://openalex.org/A5088168220][Emile E. DeLuca]], [[https://openalex.org/A5057399487][Thomas C. K. Chan]], [[https://openalex.org/A5042511391][James M. Taylor]], [[https://openalex.org/A5078060582][Byunghoon Lee]], [[https://openalex.org/A5084951895][Rajiv Ramanujam Prabhakar]], [[https://openalex.org/A5000007576][Clifford P. Kubiak]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05771 
     
A series of Mn(bpy-R)(CO)3Br (bpy-R = 4,4′-R-2,2′-bipyridine) complexes with systematic substituent variations (R = H, –Me, –Et, tBu, and –Ph) are immobilized on multiwalled carbon nanotubes (MWCNTs) and investigated as electrocatalysts for CO2 reduction to study substituent effects on heterogenized molecular electrocatalysis. The electrochemical response and catalytic activity of each heterogenized complex are characterized, unveiling clear trends across the series investigated. Mn(bpy-Ph)(CO)3Br/MWCNT exhibited the best catalytic performance, producing CO with a Faradaic efficiency of 72% and a current density (JCO) of 7.0 mA/cm2 at low overpotential (η = 0.65 V). Adding steric bulk to the bpy ligands is shown to restrict Mn0–Mn0 dimerization and cause a shift to two-electron reduction occurring at less negative potentials. The apparent quantity of electroactive catalyst scales inversely with steric bulk, where Mn(bpy-Ph)(CO)3Br exhibits no distinguishable Faradaic features in CV under normal conditions. These results indicate that catalytic performance is optimized by the confinement of electroactive species to the MWCNT interface.    

    

* [Fe]-Hydrogenase-Inspired Proton-Shuttle Installation in a Molecular Cobalt Complex for High-Efficiency H2 Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391170584
:TOPICS: Biological and Synthetic Hydrogenases: Mechanisms and Applications, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04879")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391170584"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391170584"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391170584"))][Get cited by]]

OpenAlex: https://openalex.org/W4391170584 (Open access: False)
    
[[https://openalex.org/A5023698422][Sanajit Kumar Mandal]], [[https://openalex.org/A5073695387][Chandana Sunil]], [[https://openalex.org/A5042658817][Joyanta Choudhury]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04879 
     
Developing efficient H2-evolution artificial electrocatalysts often takes inspiration from the active sites of [FeFe]/[NiFe]-hydrogenases to incorporate smartly designed amine/thiolato-based proton-shuttle motifs. Interestingly, [Fe]-hydrogenase (the third type of hydrogenases) consists of an Fe-bound adjacent pyridinol/pyridinone proton shuttle, which assists in reversible heterolytic H2-cleavage during its operation. However, so far, this type of proton-shuttle functionality has not been exploited to develop H2-evolution electrocatalysts. We reckoned that installing such a proton-shuttle motif in a suitable redox-active transition-metal-based complex can facilitate electrocatalytic H2 generation via easy hydride/proton coupling, through proper positioning of the electrochemically generated metal-hydride and the “protonated” pyridinol form of the proton shuttle. To demonstrate this idea, a rationally designed Co-based complex Co–NHCU, containing an anionic uracil nucleobase, connected with a strong sigma-donor N-heterocyclic carbene (NHC) ligand, has been developed, wherein the anionic uracil motif offers a pyridinone-type proton-responsive site adjacent to the Co center. Gratifyingly, Co–NHCU acts as a high-efficiency H2-generation electrocatalyst with variable proton sources, achieving maximum turnover frequency (TOFmax) values in the range of 5000–13 700 s–1 (from cyclic voltammetry) or ∼2200–7360 s–1 (from controlled potential electrolysis) with Faradaic efficiencies of 93%–98%, at the overpotential range of 0.50–0.78 V. This system delivered the highest TOFmax values achieved to date by any cobalt electrocatalyst in a nonaqueous medium: 10 200–13 700 s–1 with CF3COOH and Et3NHBF4 as proton sources. This work could provide insights into the future design principles of homogeneous HER catalysts via capitalizing the power of pyridinone/pyridinol-based proton shuttle motifs coupled with Earth-abundant transition metals.    

    

* Nickel-Catalyzed Modular Four-Component 1,4-Alkylcarbonylation of 1,3-Enynes to Tetra-Substituted CF3–Allenyl Ketones  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391214823
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed Sulfur Chemistry
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05776")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391214823"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391214823"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391214823"))][Get cited by]]

OpenAlex: https://openalex.org/W4391214823 (Open access: False)
    
[[https://openalex.org/A5026130049][Qi-Chao Shan]], [[https://openalex.org/A5001764400][Yan Zhao]], [[https://openalex.org/A5076607259][Shutao Wang]], [[https://openalex.org/A5043862074][Hongfei Liu]], [[https://openalex.org/A5045093754][Xin‐Hua Duan]], [[https://openalex.org/A5014851241][Li Guo]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05776 
     
The modular four-component carbonylation of unsaturated hydrocarbons represents an elegant strategy for the one-pot synthesis of complex carbonyl compounds. However, this strategy is currently focused on the 1,2-difunctionalization of olefins or alkynes, and the 1,4-alkylcarbonylation of 1,3-enynes remains unexplored. In this study, we report a Ni-catalyzed 1,4-alkylcarbonylation of CF3-containing 1,3-enynes under 1 atm of CO, which affords the tetra-substituted CF3-allenyl ketones with good yields and selectivity. This protocol features mild conditions, broad substrate scope, and acceptable functional group compatibility. Control experiments revealed that the reactivity of oxime esters (regulated by leaving groups) and polarity matching are crucial for the success of this four-component cascade. Preliminary mechanistic studies suggest that the acyl nickel complex is a key intermediate in this transformation.    

    

* Unlocking Birch Lignin Hydrocracking through Tandem Catalysis: Unraveling the Role of Moderate Hydrogen Spillover  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391231402
:TOPICS: Catalytic Valorization of Lignin for Renewable Chemicals, Lignin Degradation by Enzymes in Bioremediation, Desulfurization Technologies for Fuels
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04721")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391231402"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391231402"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391231402"))][Get cited by]]

OpenAlex: https://openalex.org/W4391231402 (Open access: False)
    
[[https://openalex.org/A5063343992][Zhongqiu Liu]], [[https://openalex.org/A5051170599][Yuanyuan Yu]], [[https://openalex.org/A5031014951][Yujing Liu]], [[https://openalex.org/A5057176422][Anguo Ying]], [[https://openalex.org/A5059787769][Xiaolong Zhang]], [[https://openalex.org/A5065592637][Ye Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04721 
     
The trade-off between intensity of hydrogen spillover and efficient production of aromatics poses an insurmountable obstacle to the depolymerization of lignin into monomeric phenols (MPs), as effectively harnessing hydrogen spillover for degradating lignin into MPs while avoiding excessive hydrogenation of aromatic rings remains a formidable challenge. Herein, a Ni–Cu/Nb2O5@Fe3O4 composite with Ni–Cu alloy and oxygen vacancies (OVs) has been fabricated for birch lignin valorization. The interspecies electron transfer within the alloy significantly improves intrinsic catalytic inertness of Cu species while simultaneously reducing intrinsic catalytic activity of Ni species toward moderate hydrogen spillover. Moreover, the mutual alloying of Ni and Cu generates moderately strong Lewis acidic sites (LASs). This resulting moderate hydrogen spillover and LASs collaboratively promote the depolymerization of lignin into crude MPs with varying degrees of methoxy substituents. Subsequently, the coupling of O atom-specific OVs recognition with LASs profoundly facilitates Ph–OMe bond dissociation, ultimately leading to the one-step generation of MPs. The tandem catalysis of moderate hydrogen spillover and specific recognition results in a high yield of MPs (up to 58 wt %) in birch lignin depolymerization, which is approximately twice as high as the reported optimum heterogeneous catalysts. Both experimental and calculation results suggest that the presence of Cu species induces an unusual electron-donating ability of Ni species during the alloying process, which successively reconstitutes their intrinsic catalytic performance and Lewis acid property, and the specific recognition of OVs is mediated by an O atom electron-effect, giving rise to a rare tandem catalysis for harvesting lignin based-MPs.    

    

* Theoretical Insights into H2 Activation and Hydrogen Spillover on Near-Surface Alloys with Embedded Single Pt Atoms  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391253549
:TOPICS: Materials and Methods for Hydrogen Storage, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05660")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391253549"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391253549"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391253549"))][Get cited by]]

OpenAlex: https://openalex.org/W4391253549 (Open access: False)
    
[[https://openalex.org/A5042788784][Zefu Tan]], [[https://openalex.org/A5046810720][Jun Chen]], [[https://openalex.org/A5016546361][Sen Lin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05660 
     
Despite extensive studies of hydrogen spillover on single-atom alloy surfaces, a thorough understanding of the structure–activity relationship is still lacking. Here, we investigate H2 dissociation and diffusion of the dissociated H species on the near-surface alloys embedded with single Pt atoms using density functional theory (DFT) calculations and ab initio molecular dynamics (AIMD) simulations. The DFT results indicate that subsurface alloying with early transition metals (X) (Pt1-X/Cu(111)) can generally promote the initial hydrogen spillover but suppress the H2 dissociation process, showing an intractable trade-off effect. While the DFT-calculated H2 dissociation barrier on Pt1-Co/Cu(111) is higher than that on Pt1-Ni/Cu(111), the AIMD results show that the H2 dissociation probability on the Pt1-Co/Cu(111) surface is much higher than that on Pt1-Ni/Cu(111). The trajectory analysis shows that H2 molecules on Pt1-Co/Cu(111) can adopt a more convenient conformation for dissociation when approaching the so-called close-range physisorption zone (CPZ) due to the relatively flat topography of the potential energy surface, thus increasing the H2 dissociation probability compared to the case on Pt1-Ni/Cu(111). This work provides a clear picture for understanding the structure–activity relationships of H2 activation and hydrogen spillover over single-atom catalysts. More importantly, it highlights an overlooked but essential role of the dynamic orientation of the reactant in heterogeneous catalysis.    

    

* Aerobic Alcohol Oxidation with a Cerium–Phenanthrolinedione Complex: A Mimic of Lanthanide-Based Methanol Dehydrogenase  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391254069
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Biological Methane Utilization and Metabolism, Biological and Synthetic Hydrogenases: Mechanisms and Applications
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05428")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391254069"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391254069"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391254069"))][Get cited by]]

OpenAlex: https://openalex.org/W4391254069 (Open access: False)
    
[[https://openalex.org/A5030020949][Duyi Shen]], [[https://openalex.org/A5017654858][Ting Ren]], [[https://openalex.org/A5008148923][Haixing Zhang]], [[https://openalex.org/A5025033841][Mianran Chao]], [[https://openalex.org/A5063357603][Cheng Sun]], [[https://openalex.org/A5069778212][Peiwei Gong]], [[https://openalex.org/A5088180194][Shumiao Zhang]], [[https://openalex.org/A5069214483][Yong Min Lee]], [[https://openalex.org/A5066193981][Shunichi Fukuzumi]], [[https://openalex.org/A5081854202][Wonwoo Nam]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05428 
     
No abstract    

    

* The Missing Link for Electrochemical CO2 Reduction: Classification of CO vs HCOOH Selectivity via PCA, Reaction Pathways, and Coverage Analysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391255963
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04851")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391255963"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391255963"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391255963"))][Get cited by]]

OpenAlex: https://openalex.org/W4391255963 (Open access: False)
    
[[https://openalex.org/A5014378699][Oliver Christensen]], [[https://openalex.org/A5061339044][Alexander Bagger]], [[https://openalex.org/A5083668074][Jan Rossmeisl]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04851 
     
No abstract    

    

* Hydrazine Oxidation Electrocatalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391310056
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05657")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391310056"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391310056"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391310056"))][Get cited by]]

OpenAlex: https://openalex.org/W4391310056 (Open access: False)
    
[[https://openalex.org/A5032610635][Tomer Y. Burshtein]], [[https://openalex.org/A5056010516][Yakov Yasman]], [[https://openalex.org/A5093810554][Lisa Muñoz-Moene]], [[https://openalex.org/A5043992472][José H. Zagal]], [[https://openalex.org/A5041536711][David Eisenberg]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05657 
     
The electro-oxidation of hydrazine is important for direct hydrazine fuel cells and for fundamental understanding of electrocatalysis in the nitrogen cycle. In this Review, we discuss electrocatalysis of the hydrazine oxidation reaction (HzOR), spanning a vast range of metal surfaces, nanoparticles, atomically dispersed ions, organometallic macrocycles, and enzymes. Emphasis is given to structure–activity correlations and reactivity descriptors, including the formulation of the Zagal principle, an electrochemical corollary of the Sabatier principle. In addition, we identify overarching themes that span the different subfields of HzOR electrocatalysis, hoping to inspire cross-disciplinary research avenues.    

    

* Harnessing the “Methyl Effect” in the Development of Novel meta-Directing Template for C–H Cyanation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391318030
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic C-H Amination Reactions, Deuterium Incorporation in Pharmaceutical Research
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04953")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391318030"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391318030"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391318030"))][Get cited by]]

OpenAlex: https://openalex.org/W4391318030 (Open access: False)
    
[[https://openalex.org/A5090848241][Trisha Bhattacharya]], [[https://openalex.org/A5061971502][Chitrala Teja]], [[https://openalex.org/A5034740343][Nikunj Kumar]], [[https://openalex.org/A5088542301][Kanhaiya Kumar Bhagat]], [[https://openalex.org/A5062826786][Goutam Kumar Lahiri]], [[https://openalex.org/A5021247800][Puneet Gupta]], [[https://openalex.org/A5028537817][Sameer Tyagi]], [[https://openalex.org/A5051885484][Debabrata Maiti]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04953 
     
The significance of chelation-assisted C–H functionalization stands upon the superior site-selectivity, easy synthesis, and diverse product utility. In this work, we design a meta-directing scaffold by tuning the side chain of a pyrimidine-based template to attain unconventional site-selectivity in anilines. A simple methyl substitution at the side chain enhances the directing group (DG) efficacy significantly, leading to an almost exclusive meta-selectivity. The current DG further enables a meta-selective cyanation of aniline and its higher homologues irrespective of the substrate electronic bias. The synthetic impact of the methodology is further highlighted with late-stage functionalizations of two very popular local anesthetics butamben and benzocaine. A thorough experimental and in silico study further unfolds the importance of the substitution effect in attaining superior site-selectivity and the role of silver carbonate in the mechanistic cycle.    

    

* Mechanistic Insights into Enantiocontrolling of Styrene Monooxygenase-Catalyzed Epoxidation of Olefins  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391322724
:TOPICS: Enzyme Immobilization Techniques, Metabolic Engineering and Synthetic Biology, Drug Metabolism and Pharmacogenomics
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06328")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391322724"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391322724"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391322724"))][Get cited by]]

OpenAlex: https://openalex.org/W4391322724 (Open access: False)
    
[[https://openalex.org/A5044594907][Hui Lin]], [[https://openalex.org/A5035081565][Shunyan Fang]], [[https://openalex.org/A5037275451][Hang Gao]], [[https://openalex.org/A5074093712][Zhi-lie QIN]], [[https://openalex.org/A5084848491][Donglin Fan]], [[https://openalex.org/A5031315906][Na Li]], [[https://openalex.org/A5033691855][Zhong‐Liu Wu]], [[https://openalex.org/A5062177930][Hongge Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06328 
     
Although styrene monooxygenases (SMOs) are widely used in the production of (S)- or (R)-enantiopure epoxides, the underlying enantiocontrol mechanism of SMO-catalyzed epoxidation remains elusive. Herein, we observed that the substrate-binding pose in the catalytic center, which was codetermined by the residues in the catalytic center and size of the alkyl moiety in the substrates, governed the enantioselectivity of the StyA-catalyzed epoxidation. The mutagenesis of the aromatic residue at site 73 into a nonaromatic residue or that of the nonaromatic residue at site 211 into aromatic residues resulted in the inversion of the enantioselectivity. The variants Y73V, V211F, V211Y, Y73V/V211F, and Y73V/V211Y of the (S)-selective StyA exhibited reversible enantioselectivity during the catalyzed epoxidation of 1-phenylcyclohexene derivatives, yielding the corresponding (R)-epoxides with high enantioselectivity (68–85% ee). Moreover, the (R)-selective variants catalyzed the olefins that harbored large hydrophobic groups, such as 1-phenylcyclohexene derivatives, into their corresponding (R)-epoxides with high enantioselectivity (up to >99% ee). However, these (R)-selective variants retained (S)-selectivity for the epoxidation of styrene, trans-β-methylstyrene, and trans-β-ethylstyrene. The elucidation of the enantiocontrolling mechanism of SMOs would thus be valuable for creating efficient styrene monooxygenases with different enantioselectivities.    

    
