#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Wed Feb 21 00:44:02 2024

Found 25 results from 2024-02-14 to 2024-02-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Copper-Mediated Radical Fluorine-Atom Transfer to Sulfonyl Radical: A Dramatic 4-Methoxypyridine 1-Oxide Ligand Effect  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391771428
:TOPICS: Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05154")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391771428"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391771428"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391771428"))][Get cited by]]

OpenAlex: https://openalex.org/W4391771428 (Open access: False)
    
[[https://openalex.org/A5044717571][Hongwei Zhang]], [[https://openalex.org/A5056197830][Xiaoxiao Sun]], [[https://openalex.org/A5058075528][Cheng Ma]], [[https://openalex.org/A5043330057][Chuang Li]], [[https://openalex.org/A5059146006][Yuxiang Ni]], [[https://openalex.org/A5022683172][Yi Yu]], [[https://openalex.org/A5058527652][Yuanqing Xu]], [[https://openalex.org/A5083249296][Shao‐Fei Ni]], [[https://openalex.org/A5069715660][Zhong‐Yan Cao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05154 
     
Although the transition metal-catalyzed radical fluorine atom transfer (FAT) strategy has emerged as a powerful tool for the construction of C–F bonds, to our knowledge, this approach has rarely been applied to the formation of S–F bonds. Here, we report that 4-methoxypyridine 1-oxide can serve as an inexpensive and simple yet effective ligand and thus promote the transformation of the copper-mediated challengeable radical FAT to sulfonyl radicals, paving the way for the assembly of an FSO2 group. Based on this concept, three Cu(I)-catalyzed protocols involving site-selective intra- and intermolecular fluorosulfonylation of inert C(sp3)–H bonds and 1,2-aminofluorosulfonylation of inactivated alkenes have been developed, enabling the preparation of C(sp3)-rich aliphatic sulfonyl fluorides that cannot be easily synthesized by known methods. These practical and operationally simple methods result in high functional group tolerance under mild conditions and can be applied to the modification of bioactive derivatives and preparation of highly valued molecules. Detailed mechanistic studies indicate the unique role of the 4-methoxypyridine 1-oxide ligand in facilitating the formation of such rare radical FATs via an outer-sphere pathway.    

    

* Evolution of Phosphorylase Activity in an Ancestral Glycosyltransferase  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391772272
:TOPICS: Glycosylation in Health and Disease, Microbial Enzymes and Biotechnological Applications, Chemical Glycobiology and Therapeutic Applications
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05819")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391772272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391772272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391772272"))][Get cited by]]

OpenAlex: https://openalex.org/W4391772272 (Open access: False)
    
[[https://openalex.org/A5032037405][Jorick Franceus]], [[https://openalex.org/A5093918745][José Pablo Rivas-Fernández]], [[https://openalex.org/A5020235932][Jolien Lormans]], [[https://openalex.org/A5081831378][Carme Rovira]], [[https://openalex.org/A5003247377][Tom Desmet]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05819 
     
The reconstruction of ancestral sequences can offer a glimpse into the fascinating process of molecular evolution by exposing the adaptive pathways that shape the proteins found in nature today. Here, we track the evolution of the carbohydrate-active enzymes responsible for the synthesis and turnover of mannogen, a critical carbohydrate reserve in Leishmania parasites. Biochemical characterization of resurrected enzymes demonstrated that mannoside phosphorylase activity emerged in an ancestral bacterial mannosyltransferase, and later disappeared in the process of horizontal gene transfer and gene duplication in Leishmania. By shuffling through plausible historical sequence space in an ancestral mannosyltransferase, we found that mannoside phosphorylase activity could be toggled on through various combinations of mutations at positions outside of the active site. Molecular dynamics simulations showed that such mutations can affect loop rigidity and shield the active site from water molecules that disrupt key interactions, allowing α-mannose 1-phosphate to adopt a catalytically productive conformation. These findings highlight the importance of subtle distal mutations in protein evolution and suggest that the vast collection of natural glycosyltransferases may be a promising source of engineering templates for the design of tailored phosphorylases.    

    

* Snapshots of the Reaction Coordinate of a Thermophilic 2′-Deoxyribonucleoside/ribonucleoside Transferase  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391772277
:TOPICS: Nucleotide Metabolism and Enzyme Regulation, Efficacy and Safety of Antiretroviral Therapy for HIV, RNA Methylation and Modification in Gene Expression
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06260")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391772277"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391772277"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391772277"))][Get cited by]]

OpenAlex: https://openalex.org/W4391772277 (Open access: True)
    
[[https://openalex.org/A5015768922][Ping Tang]], [[https://openalex.org/A5086003658][Christopher John Harding]], [[https://openalex.org/A5060331025][Alison Dickson]], [[https://openalex.org/A5044599733][Rafael G. da Silva]], [[https://openalex.org/A5064922783][David J. Harrison]], [[https://openalex.org/A5023789984][Clarissa Melo Czekster]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06260  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06260][pdf]])
     
Nucleosides are ubiquitous to life and are required for the synthesis of DNA, RNA, and other molecules crucial for cell survival. Despite the notoriously difficult organic synthesis of nucleosides, 2′-deoxynucleoside analogues can interfere with natural DNA replication and repair and are successfully employed as anticancer, antiviral, and antimicrobial compounds. Nucleoside 2′-deoxyribosyltransferase (dNDT) enzymes catalyze transglycosylation via a covalent 2′-deoxyribosylated enzyme intermediate with retention of configuration, having applications in the biocatalytic synthesis of 2′-deoxynucleoside analogues in a single step. Here, we characterize the structure and function of a thermophilic dNDT, the protein from Chroococcidiopsis thermalis (CtNDT). We combined enzyme kinetics with structural and biophysical studies to dissect mechanistic features in the reaction coordinate, leading to product formation. Bell-shaped pH-rate profiles demonstrate activity in a broad pH range of 5.5–9.5, with two very distinct pKa values. A pronounced viscosity effect on the turnover rate indicates a diffusional step, likely product (nucleobase1) release, to be rate-limiting. Temperature studies revealed an extremely curved profile, suggesting a large negative activation heat capacity. We trapped a 2′-fluoro-2′-deoxyarabinosyl-enzyme intermediate by mass spectrometry and determined high-resolution structures of the protein in its unliganded, substrate-bound, ribosylated, 2′-difluoro-2′-deoxyribosylated, and in complex with probable transition-state analogues. We reveal key features underlying (2′-deoxy)ribonucleoside selection, as CtNDT can also use ribonucleosides as substrates, albeit with a lower efficiency. Ribonucleosides are the building blocks of RNA and other key intracellular metabolites participating in energy and metabolism, expanding the scope of use of CtNDT in biocatalysis.    

    

* Structure Sensitivity of ZnZrOx Catalysts in CO2 Hydrogenation to Methanol: Significance of Surface Oxygen Content and Synthesis Strategy  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391776630
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06327")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391776630"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391776630"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391776630"))][Get cited by]]

OpenAlex: https://openalex.org/W4391776630 (Open access: False)
    
[[https://openalex.org/A5031363647][Kyungho Lee]], [[https://openalex.org/A5017390847][Maxim Park Dickieson]], [[https://openalex.org/A5081246791][Minkyung Jung]], [[https://openalex.org/A5043177677][Yan Yang]], [[https://openalex.org/A5075696165][Ning Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06327 
     
Understanding the relationship between catalyst structure and activity is crucial to advancing catalytic processes such as CO2 hydrogenation to methanol. In this study, we investigated the impact of various synthesis conditions on the structural properties and catalytic activity of ZnO–ZrO2 solid solution (ZnZrOx) catalysts. By systematically adjusting the drying method, calcination temperature, postsynthesis ball-milling time, and use of additives, we synthesized a series of ZnZrOx catalysts with varying surface area (4.5–106 m2 g–1) and surface oxygen content [O/(Zn + Zr) = 1.60–2.04] and similar surface Zn content [Zn/(Zn + Zr) = ca. 0.20]. Our experimental and computational studies revealed that methanol synthesis over ZnZrOx catalysts is structure-sensitive and that area-normalized activity is positively correlated with the oxygen content on the catalyst surface. The surface lattice oxygen (O2–) played a crucial role in H2 activation, which is the rate-determining step for methanol formation; therefore, oxygen-rich regimes serve as the main active sites for CO2 hydrogenation to methanol. From a fundamental point of view, this study highlights the importance of surface oxygen content for catalytic activity, which has been previously overlooked. From an engineering standpoint, our investigations suggest that ZnZrOx catalysts bearing oxygen-rich surfaces combined with high surface areas can exhibit desirable catalytic activity, thus guiding the rational synthesis strategy to the development of oxide-based hydrogenation catalysts.    

    

* Facile Synthesis of Vinyl Boronate Esters via Dehydrogenative Borylation of Alkenes Enabled by a Co-MOF Catalyst: An Additive-Free Approach  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391776709
:TOPICS: Frustrated Lewis Pairs Chemistry, Chemistry and Applications of Metal-Organic Frameworks, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05742")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391776709"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391776709"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391776709"))][Get cited by]]

OpenAlex: https://openalex.org/W4391776709 (Open access: False)
    
[[https://openalex.org/A5085820939][Suma Basappa]], [[https://openalex.org/A5001458814][Aishwarya Prakash]], [[https://openalex.org/A5093881181][Sanjana S. Talekar]], [[https://openalex.org/A5061653732][Manoj V. Mane]], [[https://openalex.org/A5053302759][Shubhankar Kumar Bose]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05742 
     
No abstract    

    

* The Effects of ≡Ti–OH Site Distortion and Product Adsorption on the Mechanism and Kinetics of Cyclohexene Epoxidation over Ti/SiO2  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391777161
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06073")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391777161"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391777161"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391777161"))][Get cited by]]

OpenAlex: https://openalex.org/W4391777161 (Open access: False)
    
[[https://openalex.org/A5083844609][Branden E. Leonhardt]], [[https://openalex.org/A5015311244][Martin Head‐Gordon]], [[https://openalex.org/A5087957929][Alexis T. Bell]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06073 
     
No abstract    

    

* Construction of Surface Synergetic Oxygen Vacancies on CuMn2O4 Spinel for Enhancing NO Reduction with CO  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391777530
:TOPICS: Catalytic Nanomaterials, Gas Sensing Technology and Materials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05337")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391777530"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391777530"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391777530"))][Get cited by]]

OpenAlex: https://openalex.org/W4391777530 (Open access: False)
    
[[https://openalex.org/A5010240435][Xiaolin Xu]], [[https://openalex.org/A5080940833][Xueqing Liu]], [[https://openalex.org/A5041550151][Liang Ma]], [[https://openalex.org/A5005275225][Ningning Liang]], [[https://openalex.org/A5000180953][Shan Yang]], [[https://openalex.org/A5045027403][Hao Liu]], [[https://openalex.org/A5053484557][Jingfang Sun]], [[https://openalex.org/A5004948530][Fang Huang]], [[https://openalex.org/A5064575734][Chuanzhi Sun]], [[https://openalex.org/A5073123246][Lin Dong]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05337 
     
The effectiveness of surface synergetic oxygen vacancy (SSOV) on a catalyst has been proposed in the selective reduction of NO to N2 by CO. In this work, we prepared fresh CuMn2O4 spinel catalyst using the freeze-assisted sol–gel method, and then engineered SSOVs through CO pretreatment (CO–CuMn2O4) at 250 °C. The catalytic performance of the CO–CuMn2O4 catalyst showed significant improvement, attributed to the presence of SSOVs, in comparison to that of the fresh CuMn2O4 sample. Additionally, our findings elucidated the limited reactivity of surface oxygen vacancies (SOVs) on a single metal oxide, emphasizing the crucial role played by SSOVs. Experimental results, including NO temperature-programmed desorption-mass spectrometry and in situ diffuse reflectance infrared Fourier transform spectroscopy, provided further insights by suggesting that SSOVs facilitate the formation of N2O and its subsequent decomposition into N2. Density functional theory calculations have unveiled the pivotal role of SSOV in stabilizing the nitrogen atom derived from gaseous NO, facilitating the NO + CO → N* + CO2 reaction. Notably, the energy barrier for this process is only 0.54 eV, which is the rate-determining step of the NO + CO reaction. In stark contrast, this reaction scarcely occurs on the SOVs of single CuO and Mn2O3 surfaces. Furthermore, the presence of SSOVs considerably lowers the energy barrier for the conversion of N2O to N2, with a minimal barrier of 0.12 eV. In contrast, the reduction of N2O by CO without SSOV assistance necessitates a significantly higher energy barrier of 2.77 eV. Extending our investigation, we engineered SSOVs on the CuFe2O4 spinel catalyst and observed similar SSOV-mediated effects in the NO + CO reaction. Our research offers a comprehensive understanding of atomic-level role of SSOV, thereby offering valuable insights for the design of efficient NO + CO catalysts.    

    

* Design and Applications of Cyclopropenium Chalcogen Dihalides in Catalysis via C(sp3)–H···X Interactions  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391778595
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis, Click Chemistry in Chemical Biology and Drug Development
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00087")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391778595"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391778595"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391778595"))][Get cited by]]

OpenAlex: https://openalex.org/W4391778595 (Open access: True)
    
[[https://openalex.org/A5053185512][Junjie Yang]], [[https://openalex.org/A5040092039][Yabin Zhang]], [[https://openalex.org/A5034103172][Henry Wong]], [[https://openalex.org/A5087658293][Jingxian Huang]], [[https://openalex.org/A5061946299][Ying‐Lung Steve Tse]], [[https://openalex.org/A5016128867][Ying‐Yeung Yeung]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00087  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00087][pdf]])
     
No abstract    

    

* Ir Single Atom-Doped Ni2P Anchored by Carbonized Polymer Dots for Robust Overall Water Splitting  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391780168
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05901")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391780168"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391780168"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391780168"))][Get cited by]]

OpenAlex: https://openalex.org/W4391780168 (Open access: False)
    
[[https://openalex.org/A5045168110][Da Yue]], [[https://openalex.org/A5055262287][Tanglue Feng]], [[https://openalex.org/A5016257287][Zhicheng Zhu]], [[https://openalex.org/A5085836074][Siyu Lu]], [[https://openalex.org/A5000046177][Bai Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05901 
     
Developing high-performance bifunctional electrocatalysts for hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) is imperative in facilitating large-scale production of hydrogen. Herein, we develop an atomically dispersed catalyst, Ir–Ni2P/CPDs, in which iridium single atoms are dual-anchored by both carbonized polymer dots (CPDs) and Ni2P. CPDs serve as electronic bridges, which facilitate the construction of high-density oxygen bridge structures, leading to high loading of isolated Ir atoms that act as the principal active sites for HER and OER. The resultant Ir–Ni2P/CPD catalyst demonstrates low overpotentials of only 25 ± 1 and 240 ± 2 mV at 10 mA cm–2 for HER and OER in 1.0 M KOH solution, respectively, surpassing those of commercial Pt/C and IrO2 catalysts. Moreover, it exhibits robust long-term catalytic stability. The experimental and theoretical results demonstrate that the bonding environment of dual-anchored isolated Ir sites plays an essential role in optimizing the adsorption and desorption kinetics of hydrogen/oxygen intermediates. This work extends a strategy for the design of high-loaded metal single-atom electrocatalysts for greatly facilitating HER and OER activities.    

    

* Peroxygenase-Catalyzed Allylic Oxidation Unlocks Telescoped Synthesis of (1S,3R)-3-Hydroxycyclohexanecarbonitrile  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391785338
:TOPICS: Enzyme Immobilization Techniques, Chiral Separation in Chromatography, Drug Metabolism and Pharmacogenomics
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00177")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391785338"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391785338"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391785338"))][Get cited by]]

OpenAlex: https://openalex.org/W4391785338 (Open access: True)
    
[[https://openalex.org/A5025739763][Christian M. Heckmann]], [[https://openalex.org/A5092931390][Moritz Bürgler]], [[https://openalex.org/A5091020378][Caroline E. Paul]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00177  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00177][pdf]])
     
The unmatched chemo-, regio-, and stereoselectivity of enzymes renders them powerful catalysts in the synthesis of chiral active pharmaceutical ingredients (APIs). Inspired by the discovery route toward the LPA1-antagonist BMS-986278, access to the API building block (1S,3R)-3-hydroxycyclohexanecarbonitrile was envisaged using an ene reductase (ER) and alcohol dehydrogenase (ADH) to set both stereocenters. Starting from the commercially available cyclohexene-1-nitrile, a C–H oxyfunctionalization step was required to introduce the ketone functional group, yet several chemical allylic oxidation strategies proved unsuccessful. Enzymatic strategies for allylic oxidation are underdeveloped, with few examples on selected substrates with cytochrome P450s and unspecific peroxygenases (UPOs). In this case, UPOs were found to catalyze the desired allylic oxidation with high chemo- and regioselectivity, at substrate loadings of up to 200 mM, without the addition of organic cosolvents, thus enabling the subsequent ER and ADH steps in a three-step one-pot cascade. UPOs even displayed unreported enantioselective oxyfunctionalization and overoxidation of the substituted cyclohexene. After screening of enzyme panels, the final product was obtained at titers of 85% with 97% ee and 99% de, with a substrate loading of 50 mM, the ER being the limiting step. This synthetic approach provides the first example of a three-step, one-pot UPO-ER-ADH cascade and highlights the potential for UPOs to catalyze diverse enantioselective allylic hydroxylations and oxidations that are otherwise difficult to achieve.    

    

* Computational Discovery of Codoped Single-Atom Catalysts for Methane-to-Methanol Conversion  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391785393
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05506")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391785393"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391785393"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391785393"))][Get cited by]]

OpenAlex: https://openalex.org/W4391785393 (Open access: False)
    
[[https://openalex.org/A5034971788][Haojun Jia]], [[https://openalex.org/A5029457626][Chenru Duan]], [[https://openalex.org/A5009462742][Ilia Kevlishvili]], [[https://openalex.org/A5038652876][Aditya Nandy]], [[https://openalex.org/A5084041903][Mingjie Liu]], [[https://openalex.org/A5050671822][Heather J. Kulik]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05506 
     
The absence of a synthetic catalyst that can selectively oxidize methane to methanol motivates extensive study of single-site catalysts that possess a high degree of tunability in their coordination environments and share similarities with natural enzymes that can catalyze this reaction. Single-atom catalysts (SACs), in particular doped graphitic SACs, have emerged as a promising family of materials due to their high atom economy and scalability, but SACs are yet to be exhaustively screened for methane-to-methanol conversion. Modulating the coordination environment near single metal sites by means of codopants, we carry out a large-scale high-throughput virtual screen of 2048 transition metal (i.e., Mn, Fe, Co, and Ru) SACs codoped with various elements (i.e., N, O, P, and S) in numerous spin and oxidation (i.e., M(II)/M(III)) states for the challenging conversion of methane to methanol. We identify that the ground-state preference is metal- and oxidation-state-dependent. We observe a weak negative correlation between the oxo formation energy (ΔE(oxo)) and the energy of hydrogen atom transfer (ΔE(HAT)), thanks to the high variability in the coordination environment. Therefore, codoped SACs demonstrate flexible tunability that disrupts linear free energy relationships in a manner similar to that of homogeneous catalysts without losing the scalability of heterogeneous catalysts. We identify energetically favorable catalyst candidates along the Pareto frontier of ΔE(oxo) and ΔE(HAT). Further kinetic analysis reveals an intermediate-spin Fe(II) SAC and a low-spin Ru(II) SAC as promising candidates that merit further experimental exploration.    

    

* Carbon Materials Containing Single-Atom Co–N4 Sites Enable Near-Infrared Photooxidation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391786312
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Upconversion Nanoparticles
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05441")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391786312"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391786312"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391786312"))][Get cited by]]

OpenAlex: https://openalex.org/W4391786312 (Open access: False)
    
[[https://openalex.org/A5036824294][Longjian Li]], [[https://openalex.org/A5033737778][Junhui Wang]], [[https://openalex.org/A5052585046][Qinhua Zhang]], [[https://openalex.org/A5006901857][Shuai Wang]], [[https://openalex.org/A5033444314][Hangkai Zhang]], [[https://openalex.org/A5022433710][Tao Xing]], [[https://openalex.org/A5012870141][Mingqing Wang]], [[https://openalex.org/A5063554744][Mingbo Wu]], [[https://openalex.org/A5057425584][Zhenxing Wang]], [[https://openalex.org/A5080124839][Wenting Wu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05441 
     
Near-infrared light occupies 54.3% of the solar spectrum and has greater penetration depth, and its effective utilization is of great significance in the practical application of photocatalysis on a larger scale. However, the development of catalysts that can directly utilize near-infrared light is still a huge challenge. This paper proposes a strategy to directly utilize near-infrared light (excitation wavelength extending to 850 nm) by creating carbon material doped with a high-spin-state Co(II)-Nx single-atom site. In the near-infrared-light-irradiated photooxidation of 1,5-dihydroxynaphthalene, the yield of juglone can reach 45% without a significant decrease, even when the catalytic volume is increased by 20 times, which was much higher than that irradiated by 460 nm wavelength (reduced by about 23%). Our study sets the stage for fabricating stable NIR photocatalysts and provides a solution to directly enhance NIR photooxidation in a large-scale manner.    

    

* A Water-Promoted Mars−van Krevelen Reaction Dominates Low-Temperature CO Oxidation over Au-Fe2O3 but Not over Au-TiO2  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391806007
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05978")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391806007"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391806007"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391806007"))][Get cited by]]

OpenAlex: https://openalex.org/W4391806007 (Open access: True)
    
[[https://openalex.org/A5013981591][Alexander Holm]], [[https://openalex.org/A5045357923][Bernadette Davies]], [[https://openalex.org/A5026383153][Sara Boscolo Bibi]], [[https://openalex.org/A5000887640][Félix Moncada]], [[https://openalex.org/A5092656027][Joakim Halldin-Stenlid]], [[https://openalex.org/A5092656028][Laurynas Paškevičius]], [[https://openalex.org/A5092656029][Vincent Claman]], [[https://openalex.org/A5004773873][Adam Slabon]], [[https://openalex.org/A5034520322][Cheuk‐Wai Tai]], [[https://openalex.org/A5007728343][Egon Campos dos Santos]], [[https://openalex.org/A5048699879][Sergey Koroidov]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05978  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05978][pdf]])
     
No abstract    

    

* Subnanometer Cu Clusters on Porous Ag Enhancing Ethanol Production in Electrochemical CO2 Reduction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391806039
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03469")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391806039"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391806039"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391806039"))][Get cited by]]

OpenAlex: https://openalex.org/W4391806039 (Open access: False)
    
[[https://openalex.org/A5052152711][Jiwon Park]], [[https://openalex.org/A5073948306][Chaehwa Jeong]], [[https://openalex.org/A5083175433][Moony Na]], [[https://openalex.org/A5043026627][Yusik Oh]], [[https://openalex.org/A5078186897][Kug‐Seung Lee]], [[https://openalex.org/A5060842309][Yongsoo Yang]], [[https://openalex.org/A5063790278][Hye Ryung Byon]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c03469 
     
Controlling the electrochemical CO2 reduction process for multicarbon production is challenging. Ethanol is typically produced with lower selectivity compared to ethylene. In addition, ill-defined catalytic active sites and elusive mechanisms of C–C coupling further hinder the enhancement of ethanol generation. Here, we carefully regulated the quantity of the Cu atoms and deposited them onto a Ag inverse-opal structure (AgIOs) using the pulse-electrodeposition method. Subnanometer Cu clusters demonstrated a 2.5 times higher Faradaic efficiency for ethanol production compared to that for ethylene at −1.05 V vs RHE. Conversely, as the size of Cu increased to nanometers, ethylene became the dominant product. Excessive adsorption of CO on Cu clusters, which migrates from the Ag surface, is attributed to the improved ethanol production. Abundant Ag/Cu boundaries and adjacent spacing between Ag and Cu clusters may enhance the surface migration of CO. In contrast, the preferential site-selective CO adsorption on large Cu nanoparticles is associated with solution-mediated CO migration. Operando shell-isolated nanoparticle-enhanced Raman spectroscopy (SHINERS) revealed a high coverage of the CO on the Cu clusters. The initial intermediate *OCCOH by C–C coupling appeared for both Cu clusters and nanoparticles. However, Cu clusters accommodated more carbonaceous intermediates, highlighting the critical role of CO and intermediate coverages on Cu in ethanol production.    

    

* Energy-Transfer-Enabled Radical Acylation Using Free Alkyl Boronic Acids through Photo and NHC Dual Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391807503
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06027")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391807503"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391807503"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391807503"))][Get cited by]]

OpenAlex: https://openalex.org/W4391807503 (Open access: False)
    
[[https://openalex.org/A5038338910][W.–B. Liu]], [[https://openalex.org/A5031804038][Xiang Zhang]], [[https://openalex.org/A5078143614][Lin Chen]], [[https://openalex.org/A5075090862][Rong Zeng]], [[https://openalex.org/A5042492943][Yu Tian]], [[https://openalex.org/A5021727268][Ernest Ma]], [[https://openalex.org/A5052878834][Yapeng Wang]], [[https://openalex.org/A5046881277][Bin Zhang]], [[https://openalex.org/A5053163012][Jun‐Long Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06027 
     
No abstract    

    

* New Mechanistic Insights into CO2/CO Electroreduction to Acetate by Combining Computations and Experiments  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391807606
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05825")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391807606"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391807606"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391807606"))][Get cited by]]

OpenAlex: https://openalex.org/W4391807606 (Open access: False)
    
[[https://openalex.org/A5073327563][Xiaowan Bai]], [[https://openalex.org/A5075203986][Ming He]], [[https://openalex.org/A5048798891][Yifei Xu]], [[https://openalex.org/A5073687384][Bingjun Xu]], [[https://openalex.org/A5032451131][Qi Lü]], [[https://openalex.org/A5020585562][Jinlan Wang]], [[https://openalex.org/A5007388482][Chongyi Ling]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05825 
     
No abstract    

    

* Beyond Hydrogen Storage: Metal Hydrides for Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391812707
:TOPICS: Materials and Methods for Hydrogen Storage, Ammonia Synthesis and Electrocatalysis, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05696")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391812707"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391812707"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391812707"))][Get cited by]]

OpenAlex: https://openalex.org/W4391812707 (Open access: False)
    
[[https://openalex.org/A5008530846][Haoming Yu]], [[https://openalex.org/A5042080363][Xingguo Li]], [[https://openalex.org/A5053175805][Jianlong Zheng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05696 
     
Metal hydrides (MHs) are featured for their reversible hydrogen absorption and desorption properties, which are conventionally used as hydrogen storage materials. MHs can also be used for catalysis, particularly for chemical reactions that involve hydrogen. This Review summarizes the historical and recent progress in the catalytic application of MHs. The focus topic is how the reversible hydrogen absorption and desorption properties of MHs enable their catalytic effect in hydrogen involving chemical reactions. We start with the basic properties of MHs, and their applications in hydrogen storage and related fields. The application of MHs in four important catalytic reactions: olefin hydrogenation, reversible hydrogen storage in liquid organic hydrogen carriers, CO2 hydrogenation, and NH3 synthesis are discussed. Finally, we compare MH-based catalysts with their analogues, including hydrogen spillover, oxyhydrides, mixed-anion hydrides, and electrides in catalysis. The Review demonstrates the inherent relationship between MH catalysis and their intrinsic hydrogen absorption and desorption properties, providing insights into diverse applications of MHs beyond hydrogen storage.    

    

* Importance of Site Diversity and Connectivity in Electrochemical CO Reduction on Cu  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391821487
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Analysis of Brain Functional Connectivity Networks
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05904")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391821487"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391821487"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391821487"))][Get cited by]]

OpenAlex: https://openalex.org/W4391821487 (Open access: True)
    
[[https://openalex.org/A5044316913][Chansol Kim]], [[https://openalex.org/A5023895763][Nitish Govindarajan]], [[https://openalex.org/A5093526280][Sydney Hemenway]], [[https://openalex.org/A5060549590][Jun Ho Park]], [[https://openalex.org/A5093526281][Anya Zoraster]], [[https://openalex.org/A5091102586][Calton J. Kong]], [[https://openalex.org/A5084951895][Rajiv Ramanujam Prabhakar]], [[https://openalex.org/A5089128933][Joel B. Varley]], [[https://openalex.org/A5002468117][Hee‐Tae Jung]], [[https://openalex.org/A5051674745][Christopher Hahn]], [[https://openalex.org/A5070081966][Joel W. Ager]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05904  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05904][pdf]])
     
Electrochemical CO2 reduction on Cu is a promising approach to produce value-added chemicals using renewable feedstocks, yet various Cu preparations have led to differences in activity and selectivity toward single and multicarbon products. Here, we find, surprisingly, that the effective catalytic activity toward ethylene improves when there is a larger fraction of less active sites acting as reservoirs of *CO on the surface of Cu nanoparticle electrocatalysts. In an adaptation of chemical transient kinetics to electrocatalysis, we measure the dynamic response of a gas diffusion electrode (GDE) cell when the feed gas is abruptly switched between Ar (inert) and CO. When switching from Ar to CO, CO reduction (COR) begins promptly, but when switching from CO to Ar, COR can be maintained for several seconds (delay time) despite the absence of the CO reactant in the gas phase. A three-site microkinetic model captures the observed dynamic behavior and shows that Cu catalysts exhibiting delay times have a less active *CO reservoir that exhibits fast diffusion to active sites. The observed delay times and the estimated *CO reservoir sizes are affected by catalyst preparation, applied potential, and microenvironment (electrolyte cation identity, electrolyte pH, and CO partial pressure). Notably, we estimate that the *CO reservoir surface coverage can be as high as 88 ± 7% on oxide-derived Cu (OD-Cu) at high overpotentials (−1.52 V vs SHE) and this increases in reservoir coverage coincide with increased turnover frequencies to ethylene. We also estimate that *CO can travel substantial distances (up to 10s of nm) prior to desorption or reaction. It appears that active C–C coupling sites by themselves do not control selectivity to C2+ products in electrochemical COR; the supply of CO to those sites is also a crucial factor. More generally, the overall activity of Cu electrocatalysts cannot be approximated from linear combinations of individual site activities. Future designs must consider the diversity of the catalyst network and account for intersite transportation pathways.    

    

* Tuning the CO2 Hydrogenation Activity via Regulating the Strong Metal–Support Interactions of the Ni/Sm2O3 Catalyst  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391823363
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06345")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391823363"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391823363"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391823363"))][Get cited by]]

OpenAlex: https://openalex.org/W4391823363 (Open access: False)
    
[[https://openalex.org/A5034913146][Jianxiong Zhao]], [[https://openalex.org/A5074896161][Xiaozhi Liu]], [[https://openalex.org/A5033870660][Zhengwen Li]], [[https://openalex.org/A5033303258][Kai Feng]], [[https://openalex.org/A5025390487][Yue Pan]], [[https://openalex.org/A5045088389][Pengxiang Ji]], [[https://openalex.org/A5048901189][Kangning Zhao]], [[https://openalex.org/A5047133857][Binhang Yan]], [[https://openalex.org/A5014058024][Dan Zhou]], [[https://openalex.org/A5015415276][Dong Su]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06345 
     
Strong metal–support interactions (SMSIs), characterized by the encapsulation of metal nanoparticles by the support oxide, have a significant impact on various heterogeneous catalytic reactions. In this study, we present our investigations on tuning the catalytic performance of CO2 hydrogenation through regulating the SMSI in a Ni/Sm2O3 catalyst. Our results demonstrate that the complete encapsulation of Ni nanoparticles with amorphous Sm2O3, achieved through H2 reduction, leads to nearly full selectivity to CO. In contrast, with controlled in situ thermal postannealing in an H2/CO2/N2 mixture, the encapsulated Sm2O3 layer can be partially removed and crystallized, as revealed by atomic-resolution transmission electron microscopy analyses, which results in enhanced activity and a full selectivity toward CH4. In addition, the prolonged postannealing durations completely remove the Sm2O3 overlayer, causing a decline in CO2 methanation activity. These findings underscore the critical role of the SMSI effect in CO2 hydrogenation activity and offer valuable insights for regulating SMSI to produce targeted value-added chemicals.    

    

* Correction to “Searching for the Rules of Electrochemical Nitrogen Fixation”  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391823418
:TOPICS: Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00448")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391823418"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391823418"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391823418"))][Get cited by]]

OpenAlex: https://openalex.org/W4391823418 (Open access: True)
    
[[https://openalex.org/A5061575652][Romain Tort]], [[https://openalex.org/A5061339044][Alexander Bagger]], [[https://openalex.org/A5046040902][Olivia Westhead]], [[https://openalex.org/A5033416410][Yasuyuki Kondo]], [[https://openalex.org/A5092649448][Artem Khobnya]], [[https://openalex.org/A5086013761][Anna Winiwarter]], [[https://openalex.org/A5081900881][Bethan J. V. Davies]], [[https://openalex.org/A5035797693][Aron Walsh]], [[https://openalex.org/A5059373986][Yu Katayama]], [[https://openalex.org/A5041044598][Yuki Yamada]], [[https://openalex.org/A5038499496][Mary P. Ryan]], [[https://openalex.org/A5075732110][Maria‐Magdalena Titirici]], [[https://openalex.org/A5039064548][Ifan E. L. Stephens]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00448  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00448][pdf]])
     
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVCorrectionNEXTORIGINAL ARTICLEThis notice is a correctionCorrection to “Searching for the Rules of Electrochemical Nitrogen Fixation”Romain TortRomain TortMore by Romain Tort, Alexander Bagger*Alexander BaggerMore by Alexander Baggerhttps://orcid.org/0000-0002-6394-029X, Olivia WestheadOlivia WestheadMore by Olivia Westhead, Yasuyuki KondoYasuyuki KondoMore by Yasuyuki Kondohttps://orcid.org/0000-0003-1103-3329, Artem KhobnyaArtem KhobnyaMore by Artem Khobnya, Anna WiniwarterAnna WiniwarterMore by Anna Winiwarter, Bethan J. V. DaviesBethan J. V. DaviesMore by Bethan J. V. Davieshttps://orcid.org/0000-0002-3789-8462, Aron WalshAron WalshMore by Aron Walshhttps://orcid.org/0000-0001-5460-7033, Yu KatayamaYu KatayamaMore by Yu Katayamahttps://orcid.org/0000-0002-7842-2938, Yuki YamadaYuki YamadaMore by Yuki Yamadahttps://orcid.org/0000-0002-7191-7129, Mary P. RyanMary P. RyanMore by Mary P. Ryanhttps://orcid.org/0000-0001-8582-3003, Maria-Magdalena TitiriciMaria-Magdalena TitiriciMore by Maria-Magdalena Titiricihttps://orcid.org/0000-0003-0773-2100, and Ifan E. L. Stephens*Ifan E. L. StephensMore by Ifan E. L. StephensCite this: ACS Catal. 2024, 14, XXX, 3169–3170Publication Date (Web):February 14, 2024Publication History Received29 January 2024Published online14 February 2024https://doi.org/10.1021/acscatal.4c00448© 2024 The Authors. Published by American Chemical Society. This publication is licensed under CC-BY 4.0. License Summary*You are free to share (copy and redistribute) this article in any medium or format and to adapt (remix, transform, and build upon) the material for any purpose, even commercially within the parameters below:Creative Commons (CC): This is a Creative Commons license.Attribution (BY): Credit must be given to the creator.View full license*DisclaimerThis summary highlights only some of the key features and terms of the actual license. It is not a license and has no legal value. Carefully review the actual license before using these materials. This publication is Open Access under the license indicated. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (1 MB) Get e-AlertscloseSupporting Info (1)»Supporting Information Supporting Information SUBJECTS:Binding energy,Electrical energy,Elements,Metals,Nitrides Get e-Alerts    

    

* RuO2–CeO2 Lattice Matching Strategy Enables Robust Water Oxidation Electrocatalysis in Acidic Media via Two Distinct Oxygen Evolution Mechanisms  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391836369
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06182")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391836369"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391836369"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391836369"))][Get cited by]]

OpenAlex: https://openalex.org/W4391836369 (Open access: False)
    
[[https://openalex.org/A5010471250][Haoqiang Song]], [[https://openalex.org/A5053714754][Xue Yong]], [[https://openalex.org/A5044592235][Geoffrey I. N. Waterhouse]], [[https://openalex.org/A5000696036][Jingkun Yu]], [[https://openalex.org/A5015576369][Hao Wang]], [[https://openalex.org/A5052291064][Jinmeng Cai]], [[https://openalex.org/A5067430528][Zhiyong Tang]], [[https://openalex.org/A5000046177][Bai Yang]], [[https://openalex.org/A5071937806][Jiangwei Chang]], [[https://openalex.org/A5085836074][Siyu Lu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06182 
     
The discovery of acid-stable and highly active electrocatalysts for the oxygen evolution reaction (OER) is crucial in the quest for high-performance water-splitting technologies. Herein, a heterostructured RuO2–CeO2 electrocatalyst was constructed by using a lattice-matching strategy. The interfacial Ru–O–Ce bridge structure provided a channel for electron transfer between Ru and Ce, creating a lattice stress that distorts the local structure of RuO2. The resulting RuO2–CeO2 catalyst exhibited attractive stability with negligible decay after 1000 h of the OER in 0.5 M H2SO4, along with high activity with an overpotential of only 180 mV at 10 mA cm–2. In situ attenuated total reflectance surface-enhanced infrared absorption spectroscopy (ATR-SEIRAS), in situ differential electrochemical mass spectrometry (DEMS), and density functional theory (DFT) calculations were used to reveal that the interface and noninterface RuO2 sites enabled an oxide path mechanism (OPM) and the enhanced adsorbate evolution mechanism (AEM-plus), respectively, during the OER. The simultaneous and independent OER pathways accessible by lattice matching guides improved electrocatalyst design for the OER in acidic media.    

    

* Sustainable Electrosynthesis of Cyclohexanone Oxime through Nitrate Reduction on a Zn–Cu Alloy Catalyst  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391839397
:TOPICS: Ammonia Synthesis and Electrocatalysis, Content-Centric Networking for Information Delivery, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05388")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391839397"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391839397"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391839397"))][Get cited by]]

OpenAlex: https://openalex.org/W4391839397 (Open access: True)
    
[[https://openalex.org/A5065267485][Jonathan O. Sharp]], [[https://openalex.org/A5050193781][Anna Ciotti]], [[https://openalex.org/A5057093468][Hayley Andrews]], [[https://openalex.org/A5093542676][Shaktiswaran R. Udayasurian]], [[https://openalex.org/A5049133522][Max García‐Melchor]], [[https://openalex.org/A5062286247][Tengfei Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05388  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05388][pdf]])
     
Cyclohexanone oxime is an important precursor for Nylon-6 and is typically synthesized via the nucleophilic addition–elimination of hydroxylamine with cyclohexanone. Current technologies for hydroxylamine production are, however, not environment-friendly due to the requirement of harsh reaction conditions. Here, we report an electrochemical method for the one-pot synthesis of cyclohexanone oxime under ambient conditions with aqueous nitrate as the nitrogen source. A series of Zn–Cu alloy catalysts are developed to drive the electrochemical reduction of nitrate, where the hydroxylamine intermediate formed in the electroreduction process can undergo a chemical reaction with the cyclohexanone present in the electrolyte to produce the corresponding oxime. The best performance is achieved on a Zn93Cu7 electrocatalyst with a 97% yield and a 27% Faradaic efficiency for cyclohexanone oxime at 100 mA/cm2. By analyzing the catalytic activities/selectivities of the different Zn–Cu alloys and conducting in-depth mechanistic studies via in situ Raman spectroscopy and theoretical calculations, we demonstrate that the adsorption of nitrogen species plays a central role in catalytic performance. Overall, this work provides an attractive strategy to build the C–N bond in oxime and drive organic synthesis through electrochemical nitrate reduction, while highlighting the importance of controlling surface adsorption for product selectivity in electrosynthesis.    

    

* Enantiocovergent Cross-Coupling Reaction with 1,4-Dihydropyridine Derivatives via Photoinduced Nickel Catalysis  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391839433
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05521")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391839433"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391839433"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391839433"))][Get cited by]]

OpenAlex: https://openalex.org/W4391839433 (Open access: False)
    
[[https://openalex.org/A5003462637][Tongtong Li]], [[https://openalex.org/A5047170949][Luo Liu]], [[https://openalex.org/A5037829758][Xiaokai Cheng]], [[https://openalex.org/A5070489845][Zhan Lu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05521 
     
Herein, we reported the enantioconvergent Csp3–Csp2 cross-coupling reaction with 1,4-dihydropyridine (DHP) derivatives via photoredox/nickel dual catalysis to access chiral products with good yield and enantioselectivity. The operationally simple reaction was carried out under mild conditions with good functional group tolerance. Due to the use of a stoichiometric equivalent of aryl/alkenyl halides as coupling partners, the sequential and iterative synthesis could be achieved smoothly in one pot for the synthesis of position isomers and stereoisomers. In the proposed mechanism, kinetic experiments and mechanistic studies indicated that the radical generation, depended on the excited photocatalyst and DHP, was the rate-determining step.    

    

* Oxygen-Vacancy-Induced Built-In Electric Field across MoCo Dual-Atomic Site Catalyst for Promoting Hydrogen Spillover in Hydrocracking and Hydrodesulfurization  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391842855
:TOPICS: Desulfurization Technologies for Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05911")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391842855"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391842855"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391842855"))][Get cited by]]

OpenAlex: https://openalex.org/W4391842855 (Open access: False)
    
[[https://openalex.org/A5055093981][Guangxun Sun]], [[https://openalex.org/A5047385323][Dongyuan Liu]], [[https://openalex.org/A5003849123][Hongfu Shi]], [[https://openalex.org/A5030640908][Junxi Li]], [[https://openalex.org/A5041898714][Liting Yang]], [[https://openalex.org/A5057254434][Fengyu Tian]], [[https://openalex.org/A5070110088][Yuchen Cui]], [[https://openalex.org/A5041230019][Chunlin Wang]], [[https://openalex.org/A5027352459][Feiyang Li]], [[https://openalex.org/A5022388959][Tiansheng Zhao]], [[https://openalex.org/A5061556681][Houyu Zhu]], [[https://openalex.org/A5048826252][Bin Liu]], [[https://openalex.org/A5062331341][Yong‐Ming Chai]], [[https://openalex.org/A5090056849][Yunqi Liu]], [[https://openalex.org/A5046844071][Yuan Pan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05911 
     
The design and construction of highly efficient catalytic active sites for promoting hydrogen spillover are of great significance for improving hydrocracking (HCK) and hydrodesulfurization (HDS) performance in slurry-phase hydrogenation of vacuum residue (VR) but are still challenging. Herein, we report a carbon-supported MoCo dual-atomic site catalyst (MoCo DAC/C) and propose an oxygen-vacancy-induced built-in electric field (BIEF) regulation mechanism for promoting hydrogen spillover in HCK and HDS. It was found that the coordination structure of the MoCo dual-atomic was reconstructed and formed O vacancies in situ during hydrogenation process. The formation of O vacancies not only provided macromolecular adsorption sites but also broke the electronic balance and formed a weak BIEF between the Mo and Co atoms. Meanwhile, H2 was activated at the Mo sites to form active hydrogen species. The formation of BIEF promoted the active hydrogen spillover from Mo to Co sites by a Mo–C–Co bridging bond, thus improving the hydrogenation performance greatly. In HCK of VR, the MoCo DAC/C demonstrates remarkable catalytic hydrogenation activity with TOFT calculated for total metals up to 0.77 s–1 (two times enhancement than that of Mo single atoms (SAs)/C), the per pass conversion of VR of 76 wt %, liquid product yield of 92 wt %, and coke content of only 0.55 wt %. It also shows robust HDS performance with dibenzothiophene (DBT) conversion of 70 wt %. Density functional theory reveals that the formation of the O vacancies leads to the discrepancy of Bader charge between Mo and Co atoms, and the resulting local electric field can favor the diffusion of the positively charged (+0.10 e−) H atom. This work proposes an oxygen-vacancy-induced BIEF regulation mechanism from an atomic scale for enhancing the catalytic reaction process by promoting hydrogen spillover, which provided novel insights for the design and development of high-performance hydrogenation catalysts.    

    

* Indium-Catalyzed Reductive Coupling Enabled Efficient Synthesis of Acylphosphine Oxides and Diphosphines  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391843736
:TOPICS: Homogeneous Catalysis with Transition Metals, Peptide Synthesis and Drug Discovery, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05947")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391843736"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391843736"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391843736"))][Get cited by]]

OpenAlex: https://openalex.org/W4391843736 (Open access: False)
    
[[https://openalex.org/A5017282649][Dongdong Xu]], [[https://openalex.org/A5054639707][Ming Yu Jin]], [[https://openalex.org/A5052676364][Yu Chen]], [[https://openalex.org/A5050369958][Daoqing Han]], [[https://openalex.org/A5005480296][Lizhi Tao]], [[https://openalex.org/A5037305819][Xiangyou Xing]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05947 
     
The unique low level of the ionization potential of indium(0) to indium(I) makes it an appealing metal for organic synthesis. Here, we present an indium-catalyzed reductive cross-coupling between chlorophosphines (R2PCl) or dichlorophosphines (RPCl2) with acyl chlorides (RCOCl). This one-pot approach, using indium-catalysis followed by oxidation, generates a variety of mono- or bis-acylphosphine oxides in good yields. Additionally, this protocol offers a convenient pathway to obtain the photoinitiators, Luricin TPO and IRGACURE 819, that are widely used in the industry. Experimental and computational studies indicate the intermediacy of phosphorus-based radical species that dimerize to diphosphines, which then couple with acyl chlorides through a four-membered transition state. Furthermore, we also explore indium-catalyzed reductive homocoupling of R2PCl or RPCl2, which provides facile access to various P–P bond formations.    

    
