#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Mon Apr 15 03:23:17 2024

Found 26 results from 2024-04-08 to 2024-04-15
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Assessment of the Reaction Location of Skeletal 1-Butene Isomerization over Ferrierite  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394566285
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Dehydrogenation of Light Alkanes, Characterization and Behavior of Nuclear Graphite Materials
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00786")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394566285"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394566285"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394566285"))][Get cited by]]

OpenAlex: https://openalex.org/W4394566285 (Open access: True)
    
[[https://openalex.org/A5093007599][Pawel A. Chmielniak]], [[https://openalex.org/A5025006045][Karoline L. Hebisch]], [[https://openalex.org/A5035794316][Urim Pearl Kim]], [[https://openalex.org/A5069105128][Jeffrey Kenvin]], [[https://openalex.org/A5088976109][Carsten Sievers]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00786  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00786][pdf]])
     
No abstract    

    

* Oxidative Redispersion-Derived Single-Site Ru/CeO2 Catalysts with Mobile Ru Complexes Trapped by Surface Hydroxyls Instead of Oxygen Vacancies  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394566556
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01230")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394566556"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394566556"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394566556"))][Get cited by]]

OpenAlex: https://openalex.org/W4394566556 (Open access: False)
    
[[https://openalex.org/A5037077755][Pengfei Liu]], [[https://openalex.org/A5000696502][Zheng Chen]], [[https://openalex.org/A5060633377][Wei Liu]], [[https://openalex.org/A5004299496][Xiaodong Wu]], [[https://openalex.org/A5064821504][Shuang Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01230 
     
No abstract    

    

* Fluorinated Biphenyl Phosphine Ligands for Accelerated [Au(I)]-Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394567969
:TOPICS: Gold Catalysis in Organic Synthesis, Transition Metal Catalysis, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00593")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394567969"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394567969"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394567969"))][Get cited by]]

OpenAlex: https://openalex.org/W4394567969 (Open access: False)
    
[[https://openalex.org/A5031838921][Riccardo Pedrazzani]], [[https://openalex.org/A5003292804][Sofia Kiriakidi]], [[https://openalex.org/A5083086799][Magda Monari]], [[https://openalex.org/A5066784317][Irene Lazzarini]], [[https://openalex.org/A5019212035][Giulio Bertuzzi]], [[https://openalex.org/A5058546077][Carlos Silva López]], [[https://openalex.org/A5077034819][Marco Bandini]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00593 
     
Fluorinated JohnPhos-type ligands are proposed as accelerating tools in homogeneous gold(I) catalysis, with PedroPhosAuCl (Cat1) as the most efficient one. The ligands as well as the corresponding gold complexes were synthesized in high yields and fully characterized also via single-crystal X-ray diffraction. A secondary interaction between the distal phenyl ring of the phosphane ligand and the metal center is identified as key for the fine-tuning of the overall catalytic performance of the complexes. In particular, kinetic as well as computational analysis revealed that by accommodating F atoms on the biphenyl pendant of the ligand, more reactive organo-gold intermediates are realized toward subsequent nucleophilic condensations. The gold-catalyzed indole-hydroarylation of 1,6-enynes and the intramolecular hydroindolynation of alkynes have been adopted as benchmark reactions to exemplify these accelerating effects.    

    

* Electrifying Energy and Chemical Transformations with Single-Atom Alloy Nanoparticle Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394576674
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-04-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00365")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394576674"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394576674"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394576674"))][Get cited by]]

OpenAlex: https://openalex.org/W4394576674 (Open access: True)
    
[[https://openalex.org/A5035090837][Qiang Gao]], [[https://openalex.org/A5038027282][Xue Han]], [[https://openalex.org/A5024914236][Yuanqi Liu]], [[https://openalex.org/A5087106141][Huiyuan Zhu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00365  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00365][pdf]])
     
Single-atom alloys (SAAs) have attracted considerable attention as promising electrocatalysts in reactions central to energy conversion and chemical transformation. In contrast to monometallic nanocrystals and metal alloys, SAAs possess unique and intriguing physicochemical properties, positioning them as ideal model systems for studying structure–property relationships. However, the field is still in its early stages. In this Perspective, we first review and summarize rational synthesis methods and advanced characterization techniques for SAA nanoparticle catalysts. We then emphasize the extensive applications of SAAs in a range of electrocatalytic reactions, including fuel cell reactions, water splitting, and carbon dioxide and nitrate reductions. Finally, we provide insights into existing challenges and prospects associated with the controlled synthesis, characterization, and design of SAA catalysts.    

    

* Research Progress on Preparation of Metal Oxide Catalysts with Porous Structure and Their Catalytic Purification of Diesel Engine Exhausts Gases  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394578929
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00323")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394578929"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394578929"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394578929"))][Get cited by]]

OpenAlex: https://openalex.org/W4394578929 (Open access: False)
    
[[https://openalex.org/A5008476939][Shian Zhou]], [[https://openalex.org/A5016660396][Lanyi Wang]], [[https://openalex.org/A5084746751][Siyu Gao]], [[https://openalex.org/A5078226849][Xinyu Chen]], [[https://openalex.org/A5088059015][Chunlei Zhang]], [[https://openalex.org/A5038450038][Di Yu]], [[https://openalex.org/A5067365795][Xiaoqiang Fan]], [[https://openalex.org/A5045949335][Xin Yu]], [[https://openalex.org/A5065361552][Zhao Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00323 
     
Because of their special physicochemical properties, pore-structured metal oxide catalysts are widely used in environmental catalysis, energy chemicals, fuel cells, medicine, and other related fields. In recent years, these oxides have also been increasingly studied in the catalytic purification of diesel engine exhaust gases. In this paper, the research progresses of preparation methods of porous metal oxide catalysts and their application in the catalytic purification of diesel engine exhaust were reviewed. The advantages and disadvantages of different methods for the synthesis of porous metal oxide catalysts were elaborated, as well as the mechanism comparison of different types of porous metal oxide catalysts in catalytic purification of diesel engine exhaust pollutants. Finally, the current issues on the preparation of porous metal oxide catalysts and their development trends in application of diesel engine exhaust purification were summarized and discussed. The pore-structured metal oxide catalysts are beneficial for improving the contact efficiency between catalysts and pollutants, which can enhance the catalytic purification efficiency of catalysts. Meanwhile, the intrinsic activity is the most fundamental factor for determining their catalytic activity except for porous structure effects. In addition, this paper can help researchers to deeply understand the important effect of porous metal oxide catalysts in the treatment of diesel engine exhaust pollutants and provide theoretical guidance for the design and development of high-efficiency catalysts.    

    

* An Overview on Dynamic Phase Transformation and Surface Reconstruction of Iron Catalysts for Catalytic Hydrogenation of COx for Hydrocarbons  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394579619
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05854")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394579619"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394579619"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394579619"))][Get cited by]]

OpenAlex: https://openalex.org/W4394579619 (Open access: False)
    
[[https://openalex.org/A5000821238][Xiaoxu Ding]], [[https://openalex.org/A5052454489][Minghui Zhu]], [[https://openalex.org/A5008837035][Bo Sun]], [[https://openalex.org/A5017547546][Zixu Yang]], [[https://openalex.org/A5057242677][Yi‐Fan Han]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05854 
     
Catalytic hydrogenation of COx (CO and CO2) with renewable H2 represents a feasible practice for carbon capture and utilization and synthesis of chemical commodities, such as olefins, aromatics, and higher alcohols as well as liquid fuels. Direct synthesis via Fischer–Tropsch Synthesis (FTS) is considered as one of the most promising processes. Iron-based catalysts have been recognized as efficient candidates for catalytic hydrogenation of both CO and CO2 to value-added hydrocarbons due to their superior activities for C–O bond dissociative activation, reverse/water gas shift reaction, and C–C chain growth. The structural complexity and dynamic evolution of iron-based catalysts under COx-FTS conditions impose challenges on the understanding of the reaction mechanisms, the dynamic structure of active sites and further improvements of the catalytic performance. In this Review, we discussed the recent developments in characterization techniques for identifying the structural evolution of iron-based catalysts under reaction conditions. We also summarized feasible strategies to manipulate the process of the structural change via promoter interfacing, catalyst pretreating protocols, and application of external physical fields. Finally, we concluded the review by identifying current challenges and opportunities for the next generation of COx catalytic hydrogenation process with an emphasis on the combinatorial contributions from in situ/operando characterizations, chemometrics and machine learning.    

    

* Structural Evolution of Oxide-Derived Nanostructured Silver Electrocatalysts during CO2 Electroreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394579662
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00217")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394579662"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394579662"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394579662"))][Get cited by]]

OpenAlex: https://openalex.org/W4394579662 (Open access: False)
    
[[https://openalex.org/A5067922425][Mengying Yang]], [[https://openalex.org/A5059630698][Jingjing Wu]], [[https://openalex.org/A5050556980][Yue Li]], [[https://openalex.org/A5060188714][Haitao Pan]], [[https://openalex.org/A5071407794][Hongbo Cui]], [[https://openalex.org/A5035794202][Xianglong Lu]], [[https://openalex.org/A5002911869][Xiaohong Tang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00217 
     
Oxide-derived (OD) metals have been demonstrated as a kind of promising catalyst with superior catalytic activity for carbon dioxide electroreduction. Here we fabricate OD nanoporous silver by a simple, cost-effective electrochemical oxidation–reduction treatment, which enables reducing carbon dioxide to carbon monoxide with a Faradaic efficiency of 87% at −0.8 V vs RHE, significantly higher than that of untreated silver foil under the same conditions. Electron backscattered diffraction analysis reveals that there is a distinct grain refining during the initial CO2 electrochemical reduction from Ag oxide to OD-Ag. Experiment results indicated that the catalytic activity and selectivity are closely linked to the grain boundary and nanoporous structure on the surface, which has also been proven by theoretical calculation. However, after a long catalysis time (12 h), it was found that the surface grain coarsened and the thickness of the nanostructured layer reduced, resulting in the deactivation of the OD-Ag electrode. A dissolution–redeposition mechanism was proposed to govern the degradation of OD-Ag. The catalytic activity can be regenerated again by applying electrochemical oxidation–reduction treatment, which can increase the thickness of the porous layer and electrochemical active surface area significantly.    

    

* Biocatalytic Enantioselective Reduction of Cyclopropenyl Esters and Ketones Using Ene-Reductases  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394581090
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Enzyme Immobilization Techniques, Click Chemistry in Chemical Biology and Drug Development
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00899")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394581090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394581090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394581090"))][Get cited by]]

OpenAlex: https://openalex.org/W4394581090 (Open access: False)
    
[[https://openalex.org/A5045482234][Tomohiro Yasukawa]], [[https://openalex.org/A5083465305][Pierre Gilles]], [[https://openalex.org/A5035382136][Juliette Martin]], [[https://openalex.org/A5069511260][Julien Boutet]], [[https://openalex.org/A5040685904][Janine Cossy]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00899 
     
Enantioselective reduction of cyclopropenyl esters and ketones to optically active cyclopropanes has been achieved by using whole-cell-overexpressing ene-reductases (EREDs). By using these enzymes, trans-cyclopropanes were isolated in good yield and high enantiomeric excess. A wide range of optically active cyclopropane esters and ketones were obtained, and a variety of substituent patterns on the cyclopropenes were tolerated.    

    

* Ene-Reductase-Catalyzed Enantioselective Desymmetrization of Cyclohexadienones: Straightforward Access to All-Carbon Quaternary Stereocenters  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394581211
:TOPICS: Olefin Metathesis Chemistry, Homogeneous Catalysis with Transition Metals, Asymmetric Catalysis
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00239")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394581211"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394581211"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394581211"))][Get cited by]]

OpenAlex: https://openalex.org/W4394581211 (Open access: False)
    
[[https://openalex.org/A5037955329][Xiaofan Wu]], [[https://openalex.org/A5069352060][Lin Yang]], [[https://openalex.org/A5045267855][Zhigang Liu]], [[https://openalex.org/A5030064573][Ke Zhang]], [[https://openalex.org/A5015046053][Zedu Huang]], [[https://openalex.org/A5001652506][Fen‐Er Chen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00239 
     
An unprecedented enzyme-catalyzed enantioselective desymmetrization of achiral 2,5-cyclohexadienones has been reported. Using ene-reductases as the biocatalysts, a variety of γ,γ-disubstituted cyclohexadienones were reduced to the respective chiral cyclohexenones bearing an all-carbon quaternary stereocenter in high yields (up to 96%) along with low levels of over-reduction (less than 4% cyclohexanones in most cases) and good enantioselectivities (mostly 99% ee), which are superior to the enantioselectivities obtained with the chemocatalysis. A mutagenesis study indicated residue Q232 was likely important for NCR in providing cyclohexenones selectively over cyclohexanones, and molecular dynamics (MD) simulations were performed to rationalize the good enantioselectivity and low level of over-reduction observed for this enzyme. The deuterium-labeling experiment suggested the hydrogen at the N5 atom of the reduced flavin cofactor added to the face of the substrate 1a that has the bulkier phenyl group facing toward it. The current work expands the substrate scope of ene-reductases, providing an efficient, stereoselective access to valuable chiral γ,γ-disubstituted cyclohexenones, and will stimulate the development of other classes of enzyme-catalyzed enantioselective desymmetrization of cyclohexadienones.    

    

* Enzymatic Fluoroethylation by a Fluoroethyl Selenium Analogue of S-Adenosylmethionine  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394603197
:TOPICS: Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Role of Homocysteine in Health and Disease, Amino Acid Transport and Metabolism in Health and Disease
:PUBLICATION_DATE: 2024-04-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01112")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394603197"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394603197"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394603197"))][Get cited by]]

OpenAlex: https://openalex.org/W4394603197 (Open access: False)
    
[[https://openalex.org/A5065908524][Neng-Wei Yu]], [[https://openalex.org/A5014465828][Huimin Zhao]], [[https://openalex.org/A5004952405][Wenrui Wang]], [[https://openalex.org/A5073267812][Min Dong]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01112 
     
Fluorine is a unique element with important roles in medicinal chemistry, agrochemistry, and materials chemistry. The fluoroethyl group is an important fluoroalkyl functional unit that is widely used in clinical drugs, 19F probes and 18F PET diagnostic drugs. Chemo- and regioselective fluoroethylation is difficult in chemical synthesis. To date, no enzymatic reaction for selective fluoroethylation has been reported. Based on the widespread natural methyl donor S-adenosine-l-methionine (SAM), we designed and synthesized a fluoroethyl SAM analogue (FEt-SAM). A stability study revealed that FEt-SAM was very labile under physiological conditions and gave the fluorine-elimination product vinyl-SAM. We circumvented this problem by replacing the S in FEt-SAM with Se to give fluoroethyl Se-adenosyl-l-selenomethionine (FEt-SeAM). By using halide methyltransferase (HMT) and its mutant for the in situ production of FEt-SeAM, we created cascade reactions of the HMT mutant with methyltransferases and fluoroethylated several O-, N-, S-, and C-nucleophiles. For methyltransferases that did not recognize FEt-SeAM well, such as DnrK and NovO, simple mutagenesis of the conserved hydrophobic residues (Leu and Ile) in the SAM binding pocket to smaller amino acids significantly increased the activities. Therefore, we have provided a useful tool for the late-stage fluoroethylation of natural products and drugs. This method could also be used to enzymatically prepare probes for 19F NMR and 18F PET tests.    

    

* Self-Reconstruction of Core–Shell Structured Electrocatalysts for Tailoring Reaction Pathways Revealed by Electrochemical Surface-Enhanced Raman Spectroscopy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394605271
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00269")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394605271"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394605271"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394605271"))][Get cited by]]

OpenAlex: https://openalex.org/W4394605271 (Open access: False)
    
[[https://openalex.org/A5032411718][Zhixuan Lu]], [[https://openalex.org/A5060479752][Yajun Huang]], [[https://openalex.org/A5013191926][Ningyu Chen]], [[https://openalex.org/A5002314156][Chuan Liu]], [[https://openalex.org/A5033792704][Xiang Wang]], [[https://openalex.org/A5016139257][Bin Ren]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00269 
     
The electrocatalysts undergo structural reconstruction during electrocatalytic reactions, accompanied by significant variations in the catalytic activity and selectivity. However, it is still challenging to track in situ structural evolution and reaction process simultaneously to further figure out the origin of the surface reconstruction and its correlation to the electrocatalytic performance. By utilizing the species involved in formic acid electrooxidation reaction (FAER) as probe molecules, we employed electrochemical surface-enhanced Raman spectroscopy (EC-SERS) to reveal that the surface reconstruction process occurred on Au core-Pt shell nanoparticles (Au@Pt NPs). Via potential-dependent Raman features, we clearly revealed that the Au atoms from the Au core can migrate to the ultrathin Pt shell during FAER. Importantly, in situ SERS spectra showed that the reconstruction of Au@Pt NPs originated from the CO produced during the electrocatalytic process. We further showed that this structural transformation reduces the CO binding strength on Pt surfaces and tailors the reaction pathways of the FAER, thus facilitating the pathway of direct dehydrogenation of formic acid to CO2 by 2.6 times. This work demonstrates the importance of structural evolution of electrocatalysts during the reaction process to the catalytic performance, providing insight for designing highly efficient and robust electrocatalysts.    

    

* Correction to “N-Heterocyclic Carbene-Carbodiimide (NHC-CDI) Betaines as Organocatalysts for β-Butyrolactone Polymerization: Synthesis of Green PHB Plasticizers with Tailored Molecular Weights”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394620060
:TOPICS: Transition Metal Catalysis, Carbon Dioxide Utilization for Chemical Synthesis, Biodegradable Polymers as Biomaterials and Packaging
:PUBLICATION_DATE: 2024-04-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01882")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394620060"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394620060"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394620060"))][Get cited by]]

OpenAlex: https://openalex.org/W4394620060 (Open access: True)
    
[[https://openalex.org/A5046769905][David Sánchez-Roa]], [[https://openalex.org/A5044974820][Valentina Sessini]], [[https://openalex.org/A5011679409][Marta E. G. Mosquera]], [[https://openalex.org/A5041336405][Juan Cámpora]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01882  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01882][pdf]])
     
ADVERTISEMENT RETURN TO ARTICLES ASAPPREVAddition/CorrectionNEXTORIGINAL ARTICLEThis notice is a correctionCorrection to "N-Heterocyclic Carbene-Carbodiimide (NHC-CDI) Betaines as Organocatalysts for β-Butyrolactone Polymerization: Synthesis of Green PHB Plasticizers with Tailored Molecular Weights"David Sánchez-RoaDavid Sánchez-RoaDepartamento de Química Orgánica y Química Inorgánica, Instituto de Investigación en Química "Andrés M. del Río" (IQAR) Universidad de Alcalá, Campus Universitario, Alcalá de Henares, Madrid 28871, SpainMore by David Sánchez-Roa, Valentina SessiniValentina SessiniDepartamento de Química Orgánica y Química Inorgánica, Instituto de Investigación en Química "Andrés M. del Río" (IQAR) Universidad de Alcalá, Campus Universitario, Alcalá de Henares, Madrid 28871, SpainMore by Valentina Sessinihttps://orcid.org/0000-0003-1205-4586, Marta E. G. Mosquera*Marta E. G. MosqueraDepartamento de Química Orgánica y Química Inorgánica, Instituto de Investigación en Química "Andrés M. del Río" (IQAR) Universidad de Alcalá, Campus Universitario, Alcalá de Henares, Madrid 28871, Spain*Email: [email protected]More by Marta E. G. Mosquerahttps://orcid.org/0000-0003-2248-3050, and Juan Cámpora*Juan CámporaInstituto de Investigaciones Químicas, CSIC-Universidad de Sevilla, Sevilla 41092, Spain*Email: [email protected]More by Juan Cámporahttps://orcid.org/0000-0001-7305-1296Cite this: ACS Catal. 2024, 14, XXX, 6203Publication Date (Web):April 9, 2024Publication History Received28 March 2024Published online9 April 2024https://doi.org/10.1021/acscatal.4c01882© 2024 The Authors. Published by American Chemical Society. This publication is licensed under CC-BY 4.0. License Summary*You are free to share (copy and redistribute) this article in any medium or format and to adapt (remix, transform, and build upon) the material for any purpose, even commercially within the parameters below:Creative Commons (CC): This is a Creative Commons license.Attribution (BY): Credit must be given to the creator.View full license*DisclaimerThis summary highlights only some of the key features and terms of the actual license. It is not a license and has no legal value. Carefully review the actual license before using these materials. This publication is Open Access under the license indicated. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (812 KB) Get e-Alertsclose Get e-Alerts    

    

* PhotoROMP: The Future Is Bright  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394680291
:TOPICS: Nanotechnology and Imaging for Cancer Therapy and Diagnosis, Paper-Based Diagnostic Devices, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-04-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00972")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394680291"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394680291"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394680291"))][Get cited by]]

OpenAlex: https://openalex.org/W4394680291 (Open access: True)
    
[[https://openalex.org/A5086256993][Andrew J. Greenlee]], [[https://openalex.org/A5083727609][Raymond A. Weitekamp]], [[https://openalex.org/A5054366623][Jeffrey C. Foster]], [[https://openalex.org/A5025262217][Samuel Leguizamon]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00972  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00972][pdf]])
     
Since the earliest investigations of olefin metathesis catalysis, light has been the choice for controlling the catalyst activity on demand. From the perspective of energy efficiency, temporal and spatial control, and selectivity, photochemistry is not only an attractive alternative to traditional thermal manufacturing techniques but also arguably a superior manifold for advanced applications like additive manufacturing (AM). In the last three decades, pioneering work in the field of ring-opening metathesis polymerization (ROMP) has broadened the scope of material properties achievable through AM, particularly using light as both an activating and deactivating stimulus. In this Perspective, we explore trends in photocontrolled ROMP systems with an emphasis on approaches to photoinduced activation and deactivation of metathesis catalysts. Recent work has yielded a myriad of commercial and synthetically accessible photosensitive catalyst systems, although comparatively little attention has been paid to achieving precise control over polymer morphology using light. Metal-free, photophysical, and living ROMP systems have also been relatively underexplored. To take fuller advantage of both the thermomechanical properties of ROMP polymers and the operational simplicity of photocontrol, clear directions for the field are to improve the reversibility of activation and deactivation strategies as well as to further develop photocontrolled approaches to tuning cross-link density and polymer tacticity.    

    

* Diastereo- and Enantioselective Dearomative Reductive Aryl-Fluoroalkenylation of Indoles by Nickel Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394707978
:TOPICS: Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-04-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00560")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394707978"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394707978"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394707978"))][Get cited by]]

OpenAlex: https://openalex.org/W4394707978 (Open access: False)
    
[[https://openalex.org/A5022420223][Xinmiao Huang]], [[https://openalex.org/A5057465629][Min Ou]], [[https://openalex.org/A5052087102][Liu Hong]], [[https://openalex.org/A5040165987][Wenjie Qin]], [[https://openalex.org/A5033059956][Yuanhong Ma]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00560 
     
Herein, we disclose a nickel-catalyzed dearomative reductive aryl-fluoroalkenylation of indoles by defluorinative coupling with gem-difluoroalkenes. The catalytic protocol affords a facile assembly of various monofluoroalkene-containing polycyclic fused indolines bearing two contiguous carbon stereocenters in high diastereo- and enantioselectivities with tolerance of diverse functional groups.    

    

* Double Catalytic Activity Unveiled: Synthesis, Characterization, and Catalytic Applications of Iridium Complexes in Transfer Hydrogenation and Photomediated Transformations  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394714242
:TOPICS: Homogeneous Catalysis with Transition Metals, Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-04-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394714242"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394714242"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394714242"))][Get cited by]]

OpenAlex: https://openalex.org/W4394714242 (Open access: True)
    
[[https://openalex.org/A5049976689][Laura Blanco]], [[https://openalex.org/A5095370245][Andrea Uroz]], [[https://openalex.org/A5062147723][Kevin Gutiérrez]], [[https://openalex.org/A5088630779][Silvia Cabrera]], [[https://openalex.org/A5011696529][Alba Collado]], [[https://openalex.org/A5021511340][José V. Alemán]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00673  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00673][pdf]])
     
Iridium complexes have been demonstrated to be highly active catalysts for a wide variety of transformations. Their unique photophysical and photochemical properties render them as one of the most established photocatalysts. Moreover, iridium complexes are widely acknowledged for their efficiency in transfer hydrogenation reactions. However, the development of iridium complexes able to promote both traditional organometallic catalysis and photocatalysis is scarce. Thus, the design of iridium-based catalysts is still an active area of research. In this context, we targeted the synthesis of a family of Ir-Cp* systems to explore their (photo)catalytic applications. Here, we describe the synthesis, structural characterization, and photophysical properties of iridium complexes of formula [IrCp*Cl(N^O)]. These complexes have been applied with a double catalytic function, in transfer hydrogenation for carbonyl reduction and in different photomediated transformations.    

    

* Rhodium(II)-Catalyzed Asymmetric Cyclopropanation and Desymmetrization of [2.2]Paracyclophanes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394714316
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Homogeneous Catalysis with Transition Metals, Transition Metal Catalysis
:PUBLICATION_DATE: 2024-04-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01292")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394714316"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394714316"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394714316"))][Get cited by]]

OpenAlex: https://openalex.org/W4394714316 (Open access: True)
    
[[https://openalex.org/A5089196988][Duc Ly]], [[https://openalex.org/A5022526517][John Bacsa]], [[https://openalex.org/A5083948798][Huw M. L. Davies]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01292  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c01292][pdf]])
     
Chiral [2.2]paracyclophane derivatives are of considerable interest because of their potential in asymmetric catalysis and the development of chiral materials. This study describes the scope of rhodium-catalyzed reactions of aryldiazoacetates with [2.2]paracyclophanes. The reaction with the parent [2.2]paracyclophane resulted in cyclopropanation at two positions, the ratio of which is catalyst-controlled. Because of the strain in the system, one of the cyclopropanes exists primarily as the norcaradiene structure, whereas the other preferentially exists as the cycloheptatriene conformer. In contrast, the reaction with [3.3]paracyclophane results in benzylic C–H functionalization. The reactions with substituted [2.2]paracyclophanes using chiral catalysts can result in either kinetic resolution or desymmetrization. The Rh2(S-p-PhTPCP)]4-catalyzed reaction of monosubstituted paracyclophanes results in kinetic resolution with a selectivity (s) factor of up to 20, whereas reactions on C2v-symmetric disubstituted [2.2]paracyclophanes with Rh2(S-TPPTTL)4 [TPPTTL = 2-(1,3-dioxo-4,5,6,7-tetraphenylisoindolin-2-yl)-3,3-dimethylbutanoate] results in effective desymmetrization to form cycloheptatriene-incorporated paracyclophanes in 78–98% ee.    

    

* New and Revised Aspects of the Electrochemical Synthesis of Hydrogen Peroxide: From Model Electrocatalytic Systems to Scalable Materials  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394716632
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-04-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394716632"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394716632"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394716632"))][Get cited by]]

OpenAlex: https://openalex.org/W4394716632 (Open access: False)
    
[[https://openalex.org/A5016970585][Marco Mazzucato]], [[https://openalex.org/A5041917393][Alessandro Facchin]], [[https://openalex.org/A5006373707][Mattia Parnigotto]], [[https://openalex.org/A5071952903][Christian Durante]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01011 
     
No abstract    

    

* Enzymatic Stereodivergent Access to Fluorinated β-Lactam Pharmacophores via Triple-Parameter Engineered Ketoreductases  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394720109
:TOPICS: Synthesis and Applications of ß-Lactams, Catalytic Carbene Chemistry in Organic Synthesis, Catalytic C-H Amination Reactions
:PUBLICATION_DATE: 2024-04-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00945")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394720109"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394720109"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394720109"))][Get cited by]]

OpenAlex: https://openalex.org/W4394720109 (Open access: False)
    
[[https://openalex.org/A5002897872][Zelong Mei]], [[https://openalex.org/A5083906120][Congcong Li]], [[https://openalex.org/A5013698242][Xu Han]], [[https://openalex.org/A5054278618][Ye Tian]], [[https://openalex.org/A5019503783][Shuo-Han Li]], [[https://openalex.org/A5010058813][Weidong Liu]], [[https://openalex.org/A5070281910][Ge Qu]], [[https://openalex.org/A5036565267][Manfred T. Reetz]], [[https://openalex.org/A5061586791][Zhoutong Sun]], [[https://openalex.org/A5040829256][Jun‐An Ma]], [[https://openalex.org/A5018857438][Fa‐Guang Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00945 
     
No abstract    

    

* CN22– Vacancies Enhance Ammonia Synthesis over Air-Durable Alkaline Earth Metal Cyanamide-Supported Cobalt Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394720578
:TOPICS: Ammonia Synthesis and Electrocatalysis, Materials and Methods for Hydrogen Storage, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-04-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00830")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394720578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394720578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394720578"))][Get cited by]]

OpenAlex: https://openalex.org/W4394720578 (Open access: False)
    
[[https://openalex.org/A5025531298][Yihao Jiang]], [[https://openalex.org/A5018578223][Masayoshi Miyazaki]], [[https://openalex.org/A5018885998][Kiichi Miyashita]], [[https://openalex.org/A5008598013][Masato Sasase]], [[https://openalex.org/A5038018666][Kazuhisa Kishida]], [[https://openalex.org/A5007812423][Hideo Hosono]], [[https://openalex.org/A5079050204][Masaaki Kitano]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00830 
     
No abstract    

    

* Nickel-Based Catalysts for the Selective Monoarylation of Dichloropyridines: Ligand Effects and Mechanistic Insights  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394728071
:TOPICS: Transition Metal-Catalyzed Cross-Coupling Reactions, Homogeneous Catalysis with Transition Metals, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-04-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00648")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394728071"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394728071"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394728071"))][Get cited by]]

OpenAlex: https://openalex.org/W4394728071 (Open access: False)
    
[[https://openalex.org/A5057744441][Geraldo Duran-Camacho]], [[https://openalex.org/A5003455653][Douglas C. Bland]], [[https://openalex.org/A5077847382][Fangzheng Li]], [[https://openalex.org/A5087575581][Sharon R. Neufeldt]], [[https://openalex.org/A5028785945][Melanie S. Sanford]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00648 
     
This report describes a detailed study of Ni phosphine catalysts for the Suzuki–Miyaura coupling of dichloropyridines with halogen-containing (hetero)aryl boronic acids. With most phosphine ligands, these transformations afford mixtures of mono- and diarylated cross-coupling products as well as competing oligomerization of the boronic acid. However, a ligand screen revealed that PPh2Me and PPh3 afford high yield and selectivity for monoarylation over diarylation as well as minimal competing oligomerization of the boronic acid. Several key observations were made regarding the selectivity of these reactions, including: (1) phosphine ligands that afford high selectivity for monoarylation fall within a narrow range of Tolman cone angles (between 136 and 157°); (2) more electron-rich trialkylphosphines afford predominantly diarylated products, while less electron-rich di- and triarylphosphines favor monoarylation; (3) diarylation proceeds via intramolecular oxidative addition; and (4) the solvent (MeCN) plays a crucial role in achieving high monoarylation selectivity. Experimental and density functional theory studies suggest that all of these data can be explained based on the reactivity of a key intermediate: a Ni0–π complex of the monoarylated product. With larger, more electron-rich trialkylphosphine ligands, this π complex undergoes intramolecular oxidative addition faster than ligand substitution by the MeCN solvent, leading to selective diarylation. In contrast, with relatively small di- and triarylphosphine ligands, associative ligand substitution by MeCN is competitive with oxidative addition, resulting in the selective formation of monoarylated products. The generality of this method is demonstrated with a variety of dichloropyridines and chloro-substituted aryl boronic acids. Furthermore, the optimal ligand (PPh2Me) and solvent (MeCN) are leveraged to achieve Ni-catalyzed monoarylation of a broader set of dichloroarene substrates.    

    

* Supported Catalytically Active Liquid Metal Solutions: Liquid Metal Catalysis with Ternary Alloys, Enhancing Activity in Propane Dehydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394728272
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01282")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394728272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394728272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394728272"))][Get cited by]]

OpenAlex: https://openalex.org/W4394728272 (Open access: False)
    
[[https://openalex.org/A5071253993][Michael J. Moritz]], [[https://openalex.org/A5005267120][Sven Maisel]], [[https://openalex.org/A5019224120][Narayanan Raman]], [[https://openalex.org/A5020096826][Haiko Wittkämper]], [[https://openalex.org/A5055039669][Christoph Wichmann]], [[https://openalex.org/A5069993975][Mathias Grabau]], [[https://openalex.org/A5016293166][Deniz Kahraman]], [[https://openalex.org/A5054255871][Julien Steffen]], [[https://openalex.org/A5001718718][Nicola Taccardi]], [[https://openalex.org/A5067224843][Andreas Görling]], [[https://openalex.org/A5040845269][Marco Haumann]], [[https://openalex.org/A5039726667][Peter Wasserscheid]], [[https://openalex.org/A5035111702][Hans‐Peter Steinrück]], [[https://openalex.org/A5071842639][Christian Papp]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01282 
     
The research and optimization of catalysts are instrumental in revolutionizing chemical processes and making them viable in terms of energy and resources. Supported catalytically active liquid metal solutions (SCALMS) are highly active and stable in the harsh environment of the dehydrogenation reaction of alkanes. This is attributed to their liquid and dynamic nature and their isolated catalytically active single-atom sites. SCALMS consists of a liquid metal matrix (gallium) in which a catalytically active transition metal (platinum, rhodium, palladium, or nickel) is dissolved. Binary SCALMS systems are the subject of extensive research, aiming at a better understanding for achieving optimal performance. This work uses a combined multidisciplinary approach to examine ternary systems of the active transition metal platinum with mixtures of gallium with either tin or indium. Reaction engineering and surface chemical analysis by X-ray photoelectron spectroscopy are combined with density functional theory (DFT) and machine learning force field (ML-FF) simulations. Introducing a third metal into the mixture alters the reactivity, surface composition, and concentration gradient in the liquid metal catalyst. We demonstrate that changes in catalytic reactivity correlate with changes in the surface concentration of the active transition metal platinum and of the position of the d-band center. These findings hold great promise for future research directions as they offer potential starting points for developing SCALMS systems.    

    

* Theoretical Insights into the Reaction Mechanism of Direct Hydrogenation of Maleic Anhydride to Produce 1,4-Butanediol on the Cu–ZnO Surface  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394742732
:TOPICS: Catalytic Nanomaterials, Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-04-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00745")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394742732"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394742732"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394742732"))][Get cited by]]

OpenAlex: https://openalex.org/W4394742732 (Open access: False)
    
[[https://openalex.org/A5027111894][Xinyue Guan]], [[https://openalex.org/A5035684276][Yingzhe Yu]], [[https://openalex.org/A5045872393][Minhua Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00745 
     
No abstract    

    

* Nickel-Catalyzed Deoxygenative Disulfuration of Alcohols to Access Unsymmetrical Disulfides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394761010
:TOPICS: Polyoxometalate Clusters and Materials, Innovations in Organic Synthesis Reactions, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-04-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00814")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394761010"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394761010"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394761010"))][Get cited by]]

OpenAlex: https://openalex.org/W4394761010 (Open access: False)
    
[[https://openalex.org/A5007760530][X. Chen]], [[https://openalex.org/A5040590254][Wang Shao]], [[https://openalex.org/A5088322277][Guo‐Jun Deng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00814 
     
Given the abundance of alcohol feedstocks and the significance of disulfides, we herein report a nickel-catalyzed direct deoxygenative disulfuration of alcohols with trisulfide dioxides to access a wide range of disulfide molecules without the cumbersome decoration of coupling partners. The use of readily available dicyclohexylcarbodiimide to form transient isoureas provides the activation of the high bond dissociation energy of the C–O bond, which facilitates the straightforward conversion of nonderivatized alcohols to forge a C–SS bond. Notably, this method obviates a preactivation multistep procedure and provides a catalytic turnover under exogenous ligand and base-free conditions, featuring a broad substrate scope and functional group compatibility. It thus offers a robust alternative to existing methods for the precise construction of versatile disulfide compounds from more abundant and commercially available substrates. The synthetic utility of the method was further showcased by successful gram-scale experiments and disulfuration of structurally complex pharmaceuticals.    

    

* Practical Machine Learning-Assisted Design Protocol for Protein Engineering: Transaminase Engineering for the Conversion of Bulky Substrates  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394766668
:TOPICS: Production of Recombinant Pharmaceuticals in Plants, Metabolic Engineering and Synthetic Biology, Enzyme Immobilization Techniques
:PUBLICATION_DATE: 2024-04-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00987")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394766668"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394766668"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394766668"))][Get cited by]]

OpenAlex: https://openalex.org/W4394766668 (Open access: False)
    
[[https://openalex.org/A5015362914][Marian J. Menke]], [[https://openalex.org/A5018895869][Yu‐Fei Ao]], [[https://openalex.org/A5031181844][Uwe T. Bornscheuer]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00987 
     
Protein engineering is essential for improving the catalytic performance of enzymes for applications in biocatalysis, in which machine learning provides an emerging approach for variant design. Transaminases are powerful biocatalysts for the stereoselective synthesis of chiral amines but one major challenge is their limited substrate scope. We present a general and practical variant design protocol for protein engineering to combine the advantages of three strategies, including directed evolution, rational design, and machine learning, and demonstrate the application of the protocol in the protein engineering of transaminases with higher activity toward bulky substrates. A high-quality data set was obtained by rational design of selected key positions, which was then applied to create a machine learning model for transaminase activity. This model was applied for the data-assisted design of optimized variants, which showed improved activity (up to 3-fold over parent) for three bulky substrates, maintaining enantioselectivity of the starting enzyme scaffold as well as improving the enantiomeric excess (up to >99%ee).    

    

* Solar Gas-Phase CO2 Hydrogenation by Multifunctional UiO-66 Photocatalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394769808
:TOPICS: Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-04-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00266")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394769808"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394769808"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394769808"))][Get cited by]]

OpenAlex: https://openalex.org/W4394769808 (Open access: True)
    
[[https://openalex.org/A5028368933][Celia M. Rueda-Navarro]], [[https://openalex.org/A5070783312][Zahraa Abou Khalil]], [[https://openalex.org/A5005075051][Arianna Melillo]], [[https://openalex.org/A5082289008][Belén Ferrer]], [[https://openalex.org/A5010717182][Raúl Montero]], [[https://openalex.org/A5045347277][Asier Longarte]], [[https://openalex.org/A5005985227][Marco Daturi]], [[https://openalex.org/A5027029783][Ignacio Vayá]], [[https://openalex.org/A5081422662][Mohamad El‐Roz]], [[https://openalex.org/A5008104839][Virginia Martínez‐Martínez]], [[https://openalex.org/A5017828473][Herme G. Baldoví]], [[https://openalex.org/A5020689564][Sergio Navalón]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00266  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00266][pdf]])
     
Solar-assisted CO2 conversion into fuels and chemical products involves a range of technologies aimed at driving industrial decarbonization methods. In this work, we report on the development of a series of multifunctional metal–organic frameworks (MOFs) based on nitro- or amino-functionalized UiO-66(M) (M: Zr or Zr/Ti) supported RuOx NPs as photocatalysts, having different energy band level diagrams, for CO2 hydrogenation under simulated concentrated sunlight irradiation. RuOx(1 wt %; 2.2 ± 0.9 nm)@UiO-66(Zr/Ti)-NO2 was found to be a reusable photocatalyst, to be selective for CO2 methanation (5.03 mmol g–1 after 22 h;, apparent quantum yield at 350, 400, and 600 nm of 1.67, 0.25, and 0.01%, respectively), and to show about 3–6 times activity compared with previous investigations. The photocatalysts were characterized by advanced spectroscopic techniques like femto- and nanosecond transient absorption, spin electron resonance, and photoluminescence spectroscopies together with (photo)electrochemical measurements. The photocatalytic CO2 methanation mechanism was assessed by operando FTIR spectroscopy. The results indicate that the most active photocatalyst operates under a dual photochemical and photothermal mechanism. This investigation shows the potential of multifunctional MOFs as photocatalysts for solar-driven CO2 recycling.    

    

* Generation of Sulfamoyl Radical for the Modular Synthesis of Sulfonamides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4394783336
:TOPICS: Biological Activities of Phenothiazines and Related Compounds, Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry
:PUBLICATION_DATE: 2024-04-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01560")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394783336"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394783336"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394783336"))][Get cited by]]

OpenAlex: https://openalex.org/W4394783336 (Open access: False)
    
[[https://openalex.org/A5070217781][Haiping Lv]], [[https://openalex.org/A5027811414][Xinzhou Chen]], [[https://openalex.org/A5025996303][Xuemei Zhang]], [[https://openalex.org/A5041087516][Steven L. Kramer]], [[https://openalex.org/A5065425419][Zhong Lian]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01560 
     
Efficient synthesis of sulfonamides has long been pursued by chemists due to their frequent occurrence in pharmaceuticals, especially in anti-inflammatory medicines. The traditional assembly from sulfonyl chlorides and amines, as well as the recently developed one-step synthesis of sulfonamides involving sulfur dioxide, still faces challenges such as poor substrate compatibility and/or stringent reaction conditions. Herein, we present a strategy for the in situ generation of sulfamoyl radicals for the one-step modular synthesis of both alkenyl and alkyl sulfonamides with wide substrate applicability (>100 examples), mild reaction conditions, and easily accessible starting materials. This method is successfully applied to the late-stage modification of drug molecules (23 examples), the one-step synthesis of the drug molecule naratriptan, and the 15N-labeling of sulfonamides.    

    
