#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Mon Sep  2 01:17:06 2024

Found 8 results from 2024-08-26 to 2024-09-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Alcohols as Alkyl Synthons Enabled by Photoredox-Catalyzed Deoxygenative Activation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401894447
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-08-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03560")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401894447"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401894447"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401894447"))][Get cited by]]

OpenAlex: https://openalex.org/W4401894447 (Open access: False)
    
[[https://openalex.org/A5028442064][Tanumoy Mandal]], [[https://openalex.org/A5038796931][Samrat Mallick]], [[https://openalex.org/A5101320118][Malekul Islam]], [[https://openalex.org/A5030434402][Suman De Sarkar]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03560 
     
Alcohols are abundant with versatile structural variety and have ample use as pivotal functional groups in numerous organic processes. Because of their frequent occurrence in enumerable natural products, bioactive molecules, and medicinal components, alcohol functionalities provide a promising scope of research to advance the operational diversity for improving clinical success. Recent years have witnessed the design of modern C–C and C–heteroatom bond-forming approaches with easily accessible and commercially available unactivated aliphatic alcohols as native adaptive sp3 handles, hence offering groundbreaking transformative pathways for the functionalization of complex molecular architectures. The judicial application of appropriate activating groups to generate the alkyl radical from the alcohol through sp3 C–O bond fragmentation and employ it as a potential alkylating agent unfolds unique synthetic strategies, thereby replacing the obvious requirement of alkyl halides. This review elaborately discusses the recent trends regarding using alcohols as the C(sp3)-centered alkylating agent in various chemical transformations by exploiting different activation modes for the disrupter of the C–O bond under photoredox catalysis. The presentation is organized by the nature of the activation of the alcohol scaffolds, the kind of bond formation, and the progress achieved in this domain since the original discovery by providing illustrative examples with mechanistic details, with a focus on difficulties and future prospects.    

    

* Stable Ultrahighly Branched Polyethylene Synthesis via Externally Robust Chain-Walking Polymerization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401913517
:TOPICS: Transition Metal Catalysis, Olefin Metathesis Chemistry, Living Radical Polymerization
:PUBLICATION_DATE: 2024-08-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02385")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401913517"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401913517"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401913517"))][Get cited by]]

OpenAlex: https://openalex.org/W4401913517 (Open access: False)
    
[[https://openalex.org/A5072645221][Huijun Fan]], [[https://openalex.org/A5054994208][Xiaohui Kang]], [[https://openalex.org/A5061611597][Shengyu Dai]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02385 
     
Recently, late-transition-metal-catalyzed chain-walking polymerization has emerged as a promising method for synthesizing a range of polyethylenes, including linear, branched, and hyperbranched structures, solely from ethylene feedstock. The spatial configuration of the catalyst is a crucial factor in determining the branching patterns observed in the resulting polyethylene. In this study, we designed and employed a series of stereoscopically bulky α-diimine Ni(II) and Pd(II) complexes featuring axial flexible cycloalkyl substituents and an equatorial rigid dibenzobarrelene backbone for ethylene (co)polymerization. These Ni(II) complexes exhibited high catalytic activity, reaching up to 106 g/(mol Ni·h), and yielded very-high-molecular-weight polyethylene with extremely narrow molecular weight distributions (1.00–1.27) and very high branching densities (105–153/1000C) in a living ethylene polymerization behavior under various polymerization temperatures. Most interestingly, the branching density of polyethylene from the cyclohexyl-substituted Ni(II) complex is almost independent of the polymerization conditions and ultrahighly branched polyethylene with ultrahigh molecular weight (up to 1097 kg/mol) can be accessed. On the other hand, the corresponding Pd(II) complexes also demonstrated moderate catalytic activity, achieving up to 105 g/(mol Pd·h), and yielded highly branched polyethylene with high molecular weights ranging from 160.8 to 511.9 kg/mol. Moreover, these Pd(II) complexes were capable of generating high-molecular-weight E-MA copolymers with adjustable incorporation ratios (0.85–2.77 mol %) and high branching densities (106–117/1000C). Through a comparative analysis of single-crystal structures and DFT calculations, we found that the axial flexible cycloalkyl substituents and equatorial rigid dibenzobarrelene backbone of these complexes create an interesting ligand environment that favors chain walking over chain propagation in the nickel-catalyzed ethylene polymerization system. This finding provides valuable insights into the design of more efficient and controllable catalysts for the synthesis of polyethylenes with tailored properties.    

    

* Reversed Charge Transfer Enables Dual Active Sites on Ir/hBN for Synergistic N2O Valorization and Propane Selective Oxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401920318
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-08-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03697")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401920318"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401920318"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401920318"))][Get cited by]]

OpenAlex: https://openalex.org/W4401920318 (Open access: False)
    
[[https://openalex.org/A5041214364][Y.M. Wu]], [[https://openalex.org/A5100873472][Yuxin Sun]], [[https://openalex.org/A5068824319][Xuanhao Wu]], [[https://openalex.org/A5101843569][Haiqiang Wang]], [[https://openalex.org/A5037873853][Zhongbiao Wu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03697 
     
Valorization of nitrous oxide (N2O) as a mild oxygen source for light alkanes presents a promising and economical method for mitigating global warming. However, activating N2O and alkane together often leads to overoxidation and poor selectivity of the products. To disentangle the trade-off between activity and selectivity, herein, an Ir-based hexagonal boron nitride (hBN) catalyst was synthesized to obtain a reversed charge transfer (RCT) from the support to metal centers, forming dual active sites on Ir clusters and the separation of redox centers, as determined via operando near-ambient-pressure X-ray photoelectron spectroscopy (NAP-XPS) and density functional theory (DFT) calculations. Ir/hBN demonstrated a high N2O conversion (99.5%) and syngas yield (95.9 mol of CO kgcat–1 h–1 and 41.9 mol of H2 kgcat–1 h–1) during the selective oxidation of propane (C3H8) at 450 °C. The electron-rich Ir interfacial perimeter sites (Irδ−) enhance N2O adsorption and N–O bond dissociation to produce active O*; however, facial metallic Ir0 sites effectively facilitate C3H8 activation, including dehydrogenation and cracking. The separation of H* and O* intermediates, along with the frustrated H*/O* spillover, effectively facilitates the formation of H2. The *CH2 intermediate from C3H8 breakage migrates and reacts with O* bound to Ir interfacial sites, where it is oxidized to CO32– and subsequently liberates CO. This study provides mechanistic insights into the O element valorization from N2O with synergetic enhancement in selective oxidation of light alkanes.    

    

* Influence of Extra-Framework Aluminum Species on the Catalytic Properties of Acidic USY Zeolite in (Hydro)cracking Reactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401943162
:TOPICS: Zeolite Chemistry and Catalysis, Mesoporous Materials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-08-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03269")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401943162"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401943162"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401943162"))][Get cited by]]

OpenAlex: https://openalex.org/W4401943162 (Open access: False)
    
[[https://openalex.org/A5106801701][Sohrab Askarli]], [[https://openalex.org/A5043281751][Ildar Mukhambetov]], [[https://openalex.org/A5023228106][Sang‒Ho Chung]], [[https://openalex.org/A5071024706][Mohammad Awwad]], [[https://openalex.org/A5088878327][José Almeida]], [[https://openalex.org/A5017278097][Sarah Komaty]], [[https://openalex.org/A5035975994][Juan Carlos Navarro de Miguel]], [[https://openalex.org/A5100416764][Teng Li]], [[https://openalex.org/A5051034025][Javier Ruiz‐Martínez]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03269 
     
Extra-framework aluminum (EFAl) species are known to alter the acidic nature of zeolites and therefore their catalytic properties. Although it has been reported that the formation of such species leads to a change in the concentration and strength of acidity, the influence of those on hydrocracking warrants further exploration. To investigate these concepts, faujasite zeolite (ultrastable Y, USY) samples with various SiO2/Al2O3 ratios were steamed at different conditions until they showed similar hydrocracking activity to the reference USY sample. The steaming process results in zeolite samples with similar catalytic activity and selectivity but different levels of EFAl. Hexane cracking tests and pentylamine adsorption followed by two-dimensional 1H–27Al heteronuclear nuclear magnetic resonance spectroscopy show that samples with a high number of EFAl sites have a larger number of those species in close proximity to the Brønsted acid site (BAS). After the extensive characterization, we concluded that the catalytic activity and product selectivity in hydrocracking is unrelated to both Brønsted acid strength and EFAl species near BAS, leaving the number of BAS as the main activity descriptor.    

    

* Formation of Chiral All-Carbon Quaternary Stereocenters by Photoinduced Cobalt-Catalyzed Enantioselective Radical Coupling  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401952585
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-08-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04249")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401952585"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401952585"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401952585"))][Get cited by]]

OpenAlex: https://openalex.org/W4401952585 (Open access: False)
    
[[https://openalex.org/A5002811594][Yue Jia]], [[https://openalex.org/A5100323915][Kai Zhang]], [[https://openalex.org/A5029146832][Liang‐Qiu Lu]], [[https://openalex.org/A5051697029][Ying Cheng]], [[https://openalex.org/A5044960680][Wen‐Jing Xiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04249 
     
Photoinduced enantioselective strategies provide an efficient way to access chiral all-carbon quaternary stereocenters. Compared with the well-developed metal-catalyzed asymmetric conjugate addition of organometallic reagents to enones, the construction of chiral all-carbon quaternary stereocenters through a radical process still remains challenging, especially for the acyclic enones due to their enhanced conformational mobility. Herein, we disclose a photoinduced cobalt-catalyzed asymmetric radical coupling of α,β-unsaturated 2-acyl imidazoles and α-silylamines to give β,β-disubstituted γ-amino acid derivatives with acyclic quaternary carbon stereocenters. The facile protocol shows good functional group tolerance and a broad substrate scope. The corresponding chiral products were obtained in generally good yields (up to 96%) with high enantioselectivities (up to 99:1 e.r.).    

    

* Cationic Bis(η6-arene) Cobalt(I) Complexes: Enabling Catalyst Discovery by High-Throughput Experimentation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4401976037
:TOPICS: Homogeneous Catalysis with Transition Metals, Transition Metal Catalysis, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-08-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03843")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401976037"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401976037"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401976037"))][Get cited by]]

OpenAlex: https://openalex.org/W4401976037 (Open access: False)
    
[[https://openalex.org/A5090932079][Maya J. Lebowitz]], [[https://openalex.org/A5058908729][Connor S. MacNeil]], [[https://openalex.org/A5010961434][Lauren N. Mendelsohn]], [[https://openalex.org/A5061305059][Michael Shevlin]], [[https://openalex.org/A5084018341][Matthew V. Pecoraro]], [[https://openalex.org/A5024024488][Gabriele Hierlmeier]], [[https://openalex.org/A5087910041][Paul J. Chirik]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03843 
     
Cationic, 20-electron bis(η6-arene)Co(I) complexes have been synthesized and evaluated as precursors for the generation of bis(phosphine) cobalt(I) η6-arene precatalysts. The arenes and anions in the precursors were varied, with isolated examples, including [Al(pftb)4]− (pftb = (CF3)3CO), [BArF4]− (tetrakis[3,5-bis(trifluoromethyl)phenyl]borate), and [SbF6]−. Treatment of the isolated precursors with a series bis(phosphines) resulted in arene displacement and isolation of well-defined [(bis(phosphine))Co(η6-arene)][X] (X = Al(pftb)4– and SbF6–; arene = C6H6, C6H5Me, and C6H5Et) complexes in 84–99% yield. This ligand substitution enabled unprecedented generation of catalyst libraries using high-throughput experimentation (HTE) for asymmetric alkene hydrogenation, as well as formal [2 + 2] cycloaddition, hydroboration, and C(sp2)–H functionalization. These versatile precursors simplify increasingly complex chemical transformations by introducing single-component, well-defined precatalysts through general ligand substitution.    

    

* Synergistic Effects of Complex Cu Species in Cu–MgO Catalysts for the Water Gas Shift Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4402031423
:TOPICS: Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04064")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402031423"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402031423"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402031423"))][Get cited by]]

OpenAlex: https://openalex.org/W4402031423 (Open access: False)
    
[[https://openalex.org/A5073956048][Mei‐Yao Wu]], [[https://openalex.org/A5034786834][Shanqing Li]], [[https://openalex.org/A5062640350][Wei-Wei Wang]], [[https://openalex.org/A5068667116][Chun‐Jiang Jia]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04064 
     
No abstract    

    

* Cobalt-Catalyzed Additive-Free Dehydrogenation of Neat Formic Acid  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4402079016
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Homogeneous Catalysis with Transition Metals, Transition Metal Catalysis
:PUBLICATION_DATE: 2024-08-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04109")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402079016"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402079016"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402079016"))][Get cited by]]

OpenAlex: https://openalex.org/W4402079016 (Open access: False)
    
[[https://openalex.org/A5029483451][Bedraj Pandey]], [[https://openalex.org/A5040305041][Jeanette A. Krause]], [[https://openalex.org/A5062126454][Hairong Guan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04109 
     
Dehydrogenation of formic acid without using additives and solvents is a challenging research problem in base metal catalysis. In this study, cobalt complexes of the type (iPrPPRP)CoH(PMe3) (iPrPPRP = (o-iPr2PC6H4)2PR; R = H or Me) are shown to catalyze the additive-free dehydrogenation of neat formic acid to carbon dioxide. The iPrPPMeP-ligated cobalt hydride is particularly effective, giving catalytic turnover numbers of up to 7122 with a single load of formic acid and 10,338 with a continuous addition of formic acid. Mechanistic investigation focusing on (iPrPPMeP)CoH(PMe3) reveals that the hydride complex is initially converted to [(iPrPPMeP)CoH2(PMe3)]+ and then to "(iPrPPMeP)Co(OCHO)" as the key intermediates for releasing H2 and CO2, respectively. As the catalytic reaction proceeds, decarbonylation of formic acid produces CO, which transforms the intermediates to [(iPrPPMeP)Co(CO)(PMe3)]+ and (iPrPPMeP)Co(CO)H as the less active forms of the catalyst. Further degradation to [(iPrPPMeP)Co(CO)2]+, protonated phosphine ligands, and cobalt formate ends the catalyst's life. Contrary to many other catalytic systems, the cobalt catalysts described here are more active in neat formic acid than in formic acid solutions, which can be attributed to the removal of PMe3 from the coordination sphere (via phosphine protonation) to generate a more reactive intermediate.    

    
