#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Fri Dec  6 01:27:07 2024

Found 24 results from 2024-11-29 to 2024-12-06
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Photocatalytic Conversion of Biomass and Nitrate into Glycine  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404799850
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-11-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05235")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404799850"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404799850"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404799850"))][Get cited by]]

OpenAlex: https://openalex.org/W4404799850 (Open access: False)
    
[[https://openalex.org/A5004242502][Peifeng Li]], [[https://openalex.org/A5058707346][Biaobiao Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05235 
     
No abstract    

    

* Kinetic Analysis of Cyclization by the Substrate-Tolerant Lanthipeptide Synthetase ProcM  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404834790
:TOPICS: Natural Products as Sources of New Drugs, Ribosome Structure and Translation Mechanisms, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-11-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404834790"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404834790"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404834790"))][Get cited by]]

OpenAlex: https://openalex.org/W4404834790 (Open access: False)
    
[[https://openalex.org/A5021271255][Emily K. Desormeaux]], [[https://openalex.org/A5114876563][Garrett J. Barksdale]], [[https://openalex.org/A5067523147][Wilfred A. van der Donk]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06216 
     
No abstract    

    

* Comprehensive Investigations of MUC1 O-Glycosylation Process Reveal Initial Site Preference by the Polypeptide GalNAc Transferases  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404843611
:TOPICS: Glycosylation in Health and Disease, Chemical Glycobiology and Therapeutic Applications, Nucleotide Metabolism and Enzyme Regulation
:PUBLICATION_DATE: 2024-11-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05719")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404843611"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404843611"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404843611"))][Get cited by]]

OpenAlex: https://openalex.org/W4404843611 (Open access: False)
    
[[https://openalex.org/A5100399297][Han Zhang]], [[https://openalex.org/A5077812141][Kaiyuan Song]], [[https://openalex.org/A5104337377][Yihan Liu]], [[https://openalex.org/A5102905625][Fang Yang]], [[https://openalex.org/A5040806192][Congcong Lu]], [[https://openalex.org/A5113300033][Rumeng Wei]], [[https://openalex.org/A5024972473][Zhijue Xu]], [[https://openalex.org/A5008414706][Xia Zou]], [[https://openalex.org/A5075529271][Liang Lin]], [[https://openalex.org/A5108406881][Ting Shi]], [[https://openalex.org/A5075688047][Lin‐Tai Da]], [[https://openalex.org/A5100456242][Yan Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05719 
     
No abstract    

    

* Tailoring Surface and Penetrating Carbon in Fe-Based Catalysts to Balance the Activity and Stability of Fischer–Tropsch Synthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404857137
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Desulfurization Technologies for Fuels, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-11-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404857137"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404857137"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404857137"))][Get cited by]]

OpenAlex: https://openalex.org/W4404857137 (Open access: False)
    
[[https://openalex.org/A5091368247][Xiaoxue Han]], [[https://openalex.org/A5075318509][Shouying Huang]], [[https://openalex.org/A5012547244][Chongyang Wei]], [[https://openalex.org/A5016211182][Haoting Liang]], [[https://openalex.org/A5101730489][Jing Lv]], [[https://openalex.org/A5065841119][Yue Wang]], [[https://openalex.org/A5041578170][Mei‐Yan Wang]], [[https://openalex.org/A5038325575][Yong Wang]], [[https://openalex.org/A5100689682][Xinbin Ma]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06014 
     
No abstract    

    

* Enantioselective Transformation of Hydrazones via Remote NHC Catalysis: Activation Across C═N and N–N Bonds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404877553
:TOPICS: N-Heterocyclic Carbenes in Catalysis and Materials Chemistry, Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-11-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404877553"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404877553"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404877553"))][Get cited by]]

OpenAlex: https://openalex.org/W4404877553 (Open access: False)
    
[[https://openalex.org/A5008560620][Jiamiao Jin]], [[https://openalex.org/A5110163098][Ya Lv]], [[https://openalex.org/A5071961275][Wenli Tang]], [[https://openalex.org/A5070239905][Kunpeng Teng]], [[https://openalex.org/A5102115055][Yixian Huang]], [[https://openalex.org/A5101073339][Jingxin Ding]], [[https://openalex.org/A5100416500][Tingting Li]], [[https://openalex.org/A5101487052][Guanjie Wang]], [[https://openalex.org/A5056403313][Yonggui Robin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06029 
     
The catalytic asymmetric transformation of nitrogen atoms to prepare heterocyclic molecules is of significant value in organic synthesis and biological applications. Here, we disclose the activation of the nitrogen atom in hydrazine-derived hydrazone via an N-heterocyclic carbene (NHC) organic catalyst for highly enantioselective formal cycloaddition reactions. The range of NHC catalysis extends across several (carbon and hetero) atoms and diverse chemical bonds (C═N and N–N bonds) to activate nitrogen atoms at remote sites with excellent reactivity and (stereo)selectivity control. Our strategy for nitrogen atom activation, along with the NHC-bound diaza-diene intermediate generated during the catalytic process, offers alternative solutions for organic synthesis.    

    

* Correction to “Uncovering Hydroxynitrile Lyase Variants with Promiscuous Diastereoselective Nitroaldolase Activity toward the Highly Stereocontrolled Synthesis of Anti β-Nitroalcohols”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404905332
:TOPICS: Chemical Glycobiology and Therapeutic Applications, Amino Acid Transport and Metabolism in Health and Disease, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06888")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404905332"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404905332"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404905332"))][Get cited by]]

OpenAlex: https://openalex.org/W4404905332 (Open access: True)
    
[[https://openalex.org/A5114944281][Ayon Chaterjee]], [[https://openalex.org/A5107869341][G. Priyanka]], [[https://openalex.org/A5017053564][N. Prakash Prabhu]], [[https://openalex.org/A5019648537][Santosh Kumar Padhi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06888  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c06888?ref=article_openPDF][pdf]])
     
InfoMetricsFiguresRef.SI ACS CatalysisASAPArticle This publication is free to access through this site. Learn More CiteCitationCitation and abstractCitation and referencesMore citation options ShareShare onFacebookX (Twitter)WeChatLinkedInRedditEmailJump toExpandCollapse ORIGINAL ARTICLE. This notice is a correction.Addition/CorrectionDecember 2, 2024Correction to "Uncovering Hydroxynitrile Lyase Variants with Promiscuous Diastereoselective Nitroaldolase Activity toward the Highly Stereocontrolled Synthesis of Anti β-Nitroalcohols"Click to copy article linkArticle link copied!Ayon ChaterjeeAyon ChaterjeeMore by Ayon ChaterjeeG. PriyankaG. PriyankaMore by G. PriyankaN. Prakash PrabhuN. Prakash PrabhuMore by N. Prakash Prabhuhttps://orcid.org/0000-0002-3024-1142Santosh Kumar Padhi*Santosh Kumar PadhiMore by Santosh Kumar Padhihttps://orcid.org/0000-0001-5202-6702Open PDFSupporting Information (1)ACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 18406–18407Click to copy citationCitation copied!https://pubs.acs.org/doi/10.1021/acscatal.4c06888https://doi.org/10.1021/acscatal.4c06888Published December 2, 2024 Publication History Received 8 November 2024Published online 2 December 2024correction© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsThis publication is licensed for personal use by The American Chemical Society. ACS Publications© 2024 American Chemical SocietyIt has come to our attention that the kinetic parameters were erroneously calculated during the change of their units from the data presented in the Supporting Information to the main article. While the Supporting Information correctly represented the kinetic parameters (Figure S76 and Figure S77), the units (KM in mM, kcat in min–1, and kcat /KM in min–1 mM–1) are different from those in the main article (Table 1, Page 12626). The corrected Table 1 and its corresponding description (Kinetic Studies, Page 12629) (corrections are in bold) as well as the corrected sections of the Supporting Information (Figure S76 and Figure S77) are provided with this Correction. It is important to note that these modified parameters do not impact any of the conclusions drawn in the original article.In addition, we erroneously typed T14 to represent the Y14 in Figure S85A and Figure S86A of the Supporting Information. The corrected figures are provided in the Supporting Information with this Correction.Kinetic StudiesClick to copy section linkSection link copied!In order to gain insights of kinetics information about the DHR, both the variants, Y14C and Y14A, along with the wild-type enzyme were taken for evaluation. The steady-state kinetic parameters of Y14C toward the synthesis of (1R,2S)-1a were determined by measuring the initial velocities against different concentrations of 1. In comparison to the wild-type, Y14C exhibited >88-fold improved kcat, and ∼3-fold reduced KM (Table 1, Figure S77A,B). The single variant elicited a remarkable increase in catalytic efficiency of >250-fold than the wild-type, as kcat/KM of Y14C and the wild-type were found to be 5.01 and 0.02 s–1 M–1, respectively. The kinetic parameters for Y14A toward (1R,2S)-9b were kcat = 0.06 s–1, KM = 40.2 mM (Table 1, Figure S77C). Selection of 9 for this study was based on the highest catalytic activity and stereoselectivity of Y14A achieved during asymmetric addition of 1-nitropropane to this substrate (Figure 4). Unfortunately, the kinetic data of the wild-type was not possible to measure toward the synthesis of 9b due to its extremely low activity. The catalytic efficiency (kcat/KM) of Y14A was found to be 1.49 s–1 M–1. Even though it is unfair to compare, the catalytic efficiency of Y14A toward (1R,2S)-9b, which is assumed to be highest among the molecules of Figure 4, appeared to be ∼3.5-fold less than the catalytic efficiency of Y14C toward the synthesis of 1a. The former case has demonstrated a ∼2-fold reduced kcat along with increased KM compared with data for the latter. This explains the overall reduced biocatalytic conversion to 1-nitropropane based β-nitroalcohols as compared to nitroethane based β-nitroalcohols. Due to lack of similar data the kinetics parameters could not be compared with other HNLs. However, the catalytic efficiency (kcat/KM) of Y14C catalyzed synthesis of 1a is >580-fold and Y14A catalyzed synthesis of 9b is >720-fold lower than the catalytic efficiency of one of the best AtHNL variants (F179N) toward nitromethane addition to 1 or 9.70 This suggests that stereoselective addition of longer nitroalkanes remains a challenge despite the use of the same aldehyde, 1 in the asymmetric Henry reaction.Table 1. Kinetic Data of Wild-Type AtHNL and Variants toward 1a and 9b SynthesisaEnzymeAldehydeNucleophilepHKM (mM)kcat (s–1)kcat/KM (s–1 M–1)wild-type1a5.570.12 ± 5.931.4 × 10–3 ± 7.6 × 10–50.02 ± 0.001Y14C1a5.525.14 ± 3.470.126 ± 0.0195.01 ± 0.16Wild-type1a8.276.85 ± 2.665.2 × 10–4 ± 7 × 10–50.0068 ± 0.0009Y14C1a8.256.87 ± 3.820.38 ± 0.0426.6 ± 0.73Wild-type9b5.5ndndndY14A9b5.540.2 ± 2.880.06 ± 0.0041.49 ± 0.1aThe Michaelis–Menten plots are shown in Figures S77 and S78. Each value represents the average of three independent measurements. nd: not determined.Supporting InformationClick to copy section linkSection link copied!The Supporting Information is available free of charge at https://pubs.acs.org/doi/10.1021/acscatal.4c06888.Corrected versions of Figures S77, S78, S85, and S86 (PDF)cs4c06888_si_001.pdf (125.89 kb) Terms & Conditions Most electronic Supporting Information files are available without a subscription to ACS Web Editions. Such files may be downloaded by article for research use (if there is a public use license linked to the relevant article, that license may permit other uses). Permission may be obtained from ACS for other uses through requests via the RightsLink permission system: http://pubs.acs.org/page/copyright/permissions.html. Author InformationClick to copy section linkSection link copied!Corresponding AuthorSantosh Kumar Padhi; https://orcid.org/0000-0001-5202-6702; Email: AuthorsAyon ChaterjeeG. PriyankaN. Prakash Prabhu; https://orcid.org/0000-0002-3024-1142Cited By Click to copy section linkSection link copied!This article has not yet been cited by other publications.Download PDFFiguresReferencesSupporting Information Get e-AlertsGet e-AlertsACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 18406–18407Click to copy citationCitation copied!https://doi.org/10.1021/acscatal.4c06888Published December 2, 2024 Publication History Received 8 November 2024Published online 2 December 2024© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsArticle Views-Altmetric-Citations-Learn about these metrics closeArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated.Recommended Articles FiguresReferencesSupporting InfoThis publication has no figures.This publication has no References.Supporting InformationSupporting InformationThe Supporting Information is available free of charge at https://pubs.acs.org/doi/10.1021/acscatal.4c06888.Corrected versions of Figures S77, S78, S85, and S86 (PDF)cs4c06888_si_001.pdf (125.89 kb) Terms & Conditions Most electronic Supporting Information files are available without a subscription to ACS Web Editions. Such files may be downloaded by article for research use (if there is a public use license linked to the relevant article, that license may permit other uses). Permission may be obtained from ACS for other uses through requests via the RightsLink permission system: http://pubs.acs.org/page/copyright/permissions.html.    

    

* Controlling Cubic versus Octahedral Morphology in Plasmonic Aluminum Nanoparticle Synthesis with Titanocene Catalysts: A Systematic Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404913495
:TOPICS: Plasmonic Nanoparticles: Synthesis, Properties, and Applications, Formation and Properties of Nanocrystals and Nanostructures, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06286")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404913495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404913495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404913495"))][Get cited by]]

OpenAlex: https://openalex.org/W4404913495 (Open access: False)
    
[[https://openalex.org/A5012050880][Jae‐Kwan Kim]], [[https://openalex.org/A5047514009][Christian R. Jacobson]], [[https://openalex.org/A5069086177][Naomi J. Halas]], [[https://openalex.org/A5083700647][Ian A. Tonks]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06286 
     
Ti precatalysts containing the titanocene moiety (Cp2Ti–, Cp = cyclopentadienyl) can, under certain conditions, selectively produce cubic Al nanocrystals through the dehydrocoupling of alane amine adducts such as AlH3·NMe2Et. A systematic study of reaction conditions reveals that cubic Al nanoparticle formation occurs at a higher temperature (e.g., 65 °C) and/or higher catalyst-concentration conditions (e.g., 0.5 mol % [Ti]). Kinetic studies reveal that under these conditions nanoparticle formation and alane consumption are much faster, and cubic nanoparticle formation takes place under kinetically controlled conditions. On the other hand, employing a wide suite of TiX4 (X = anionic ligand)-type precatalysts yielded only octahedral-shaped aluminum nanoparticles regardless of conditions. Finally, we report the synthesis of a hydride-bridged Ti–Al heterobimetallic compound from the reaction of Cp2TiCl2 with AlH3·NMe2Et and characterized it to show that it is a reaction intermediate in the Ti-catalyzed aluminum nanoparticle synthesis.    

    

* Effectively Regulating Electrooxidation of Formic Acid over Bimetallic PtCo Alloys via the Integration of Theory and Experiment  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404831841
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-11-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06198")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404831841"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404831841"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404831841"))][Get cited by]]

OpenAlex: https://openalex.org/W4404831841 (Open access: False)
    
[[https://openalex.org/A5089966981][Zhikeng Zheng]], [[https://openalex.org/A5107948717][Bin Liu]], [[https://openalex.org/A5087450897][Jiaxiang Qiu]], [[https://openalex.org/A5025279061][Shaojun Xu]], [[https://openalex.org/A5108137949][Yuchen Wang]], [[https://openalex.org/A5100353061][Man Zhang]], [[https://openalex.org/A5100343468][Ke Li]], [[https://openalex.org/A5049586106][Zhongti Sun]], [[https://openalex.org/A5100728531][Ziang Li]], [[https://openalex.org/A5060400342][Yangyang Wan]], [[https://openalex.org/A5042572313][C. Richard A. Catlow]], [[https://openalex.org/A5063084241][Kai Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06198 
     
No abstract    

    

* Tailoring the Coordination Environment of Cu Single Atoms for Achieving Regioselective C–C Bond Activation of Amides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404917578
:TOPICS: Homogeneous Catalysis with Transition Metals, Peptide Synthesis and Drug Discovery, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05223")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404917578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404917578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404917578"))][Get cited by]]

OpenAlex: https://openalex.org/W4404917578 (Open access: False)
    
[[https://openalex.org/A5007958844][Wunengerile Zhang]], [[https://openalex.org/A5004470604][Chaolumen Bai]], [[https://openalex.org/A5100326883][Dan Liu]], [[https://openalex.org/A5075440492][Agula Bao]], [[https://openalex.org/A5029620953][Tegshi Muschin]], [[https://openalex.org/A5064108348][Yong‐Sheng Bao]], [[https://openalex.org/A5006099744][Jin Xie]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05223 
     
C–C bond activation can provide a direct reconstruction strategy of carbon skeletons to furnish a number of structurally diverse molecules. In general, regioselectivity represents the state-of-the-art owing to the existence of several different carbon–carbon bonds, having a high BDE, ∼90 kcal/mol. Here, we report a directed strategy for amides for the concise synthesis of a range of urea derivatives and carbamates via regioselective C–C bond activation enabled by the heterogeneous single-atom copper catalyst (Cu-SAC), with a turnover frequency of 249 h–1, which is 19 times higher than that of the analogous homogeneous copper catalyst. Multitechnique characterization data show that single-atom Cu species are associated with an unsaturated coordination structure and plentiful oxygen vacancies on γ-Al2O3 that facilitate the adsorption of multiple coordinated amides and dioxygen, leading to high catalytic activity and selectivity. It would offer opportunities to speed up the heterogenized process of homogeneous catalysts in regioselective inert-bond activation reactions.    

    

* Ru(II)-Catalyzed [1,4]-Sigmatropic Rearrangement and Intramolecular Concerted SNAr of Aryl and Heteroarylthio Derivatives using Quinoid Carbene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404917688
:TOPICS: Catalytic Carbene Chemistry in Organic Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05272")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404917688"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404917688"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404917688"))][Get cited by]]

OpenAlex: https://openalex.org/W4404917688 (Open access: False)
    
[[https://openalex.org/A5085524549][Subarna Pan]], [[https://openalex.org/A5099986984][Md. Saimuddin Sk]], [[https://openalex.org/A5111203598][B. SANYAL]], [[https://openalex.org/A5053449233][Lisa Roy]], [[https://openalex.org/A5004014371][Rajarshi Samanta]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05272 
     
A Ru(II)-catalyzed straightforward and efficient strategy has been developed to construct O-alkylated arylnaphthyl thioether derivatives using arylthioacetates/arylalkylthioethers with diazonaphthoquinone via a [1,4]-oxa sigmatropic rearrangement. In a complementary method, heteroaryl thioacetate/heteroaryl alkylthioethers offer O-heteroaryl alkylnaphthyl thioether derivatives via an interesting concerted intramolecular SNAr-type reaction. Both of these methods proceed through the formation of Ru-based quinoid carbene and sulfur ylide, respectively. A detailed mechanistic study and DFT calculations reveal that the reaction is going via a concerted manner. Postsynthetic modifications of the synthesized compounds led to sulfur-containing polyaromatic heterocycles.    

    

* Photocatalytic Carboxylation of Terminal Alkynes with CO2 over Metal–Porphyrin Framework Nanosheets  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404920674
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06006")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404920674"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404920674"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404920674"))][Get cited by]]

OpenAlex: https://openalex.org/W4404920674 (Open access: False)
    
[[https://openalex.org/A5083141761][Yanyue Wang]], [[https://openalex.org/A5102006388][Jianling Zhang]], [[https://openalex.org/A5100608375][Sha Wang]], [[https://openalex.org/A5016948713][Zhonghao Tan]], [[https://openalex.org/A5022371906][Yisen Yang]], [[https://openalex.org/A5013241583][Yingzhe Zhao]], [[https://openalex.org/A5112805144][Buxing Han]], [[https://openalex.org/A5100340669][Qian Li]], [[https://openalex.org/A5064648986][Junfeng Xiang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06006 
     
To develop an environmentally benign and efficient route for converting CO2 into value-added chemicals is of great importance. Here, we demonstrate the photocatalytic carboxylation of terminal alkynes with CO2 at room temperature and atmospheric pressure, by copper-based porphyrinic framework photocatalysts Cu2TCPP(M) (TCPP = 5,10,15,20-tetrakis(4-carboxyphenyl)porphyrin; M = Fe, Co, Ni, Cu). The Cu2TCPP(Cu) nanosheets (with a small thickness of ∼5.1 nm) exhibit an extremely high performance for the reaction of 1-ethynylbenzene with CO2 to produce 3-phenylpropiolic acid. The turnover frequency is up to 3.33 mmol g–1 h–1 at 10 h, which is much higher than those of the photothermally and thermally driven routes that are usually adopted for the carboxylation reactions catalyzed by metal–organic frameworks. The mechanism for the superior activity of Cu2TCPP(Cu) nanosheets was investigated by a series of experiments and theoretical calculations. It is revealed that the Cu2TCPP(Cu) nanosheets not only possess good photoelectronic properties but have desired molecular structure for boosting CO2 activation, alkyne activation, and carboxylation reactions.    

    

* Disrupted Spin Degeneracy Promoted C≡C Triple Bond Activation for Efficient Electrochemical Acetylene Semihydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404924221
:TOPICS: Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06191")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404924221"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404924221"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404924221"))][Get cited by]]

OpenAlex: https://openalex.org/W4404924221 (Open access: False)
    
[[https://openalex.org/A5086662186][Menglei Yuan]], [[https://openalex.org/A5024214452][Hongyu Jiang]], [[https://openalex.org/A5112783857][Ruyi Jiang]], [[https://openalex.org/A5035758335][Zhao Wang]], [[https://openalex.org/A5100762170][Zhihao Zhao]], [[https://openalex.org/A5022972481][Bao‐Lian Su]], [[https://openalex.org/A5100409923][Jian Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06191 
     
Disrupting the spin degeneracy of the electrocatalyst and further manipulating the related orbital electron arrangement are highly desirable for activating acetylene molecules. Herein, a squarate cobalt-based metal–organic framework (Co-MOF) ([Co3(C4O4)2(OH)2]·3H2O) is post-treated to accelerate the evolution from CoO6 octahedron to CoO5 pentahedron and further utilized for the electrochemical acetylene semihydrogenation reaction. Comprehensive analyses corroborate that the disrupted spin degeneracy of active sites originated from the breakage of the Co–O bond, which promotes the cleavage of the orbital energy level and the rearrangement of the d-orbital electron. The newly emerged half-occupied dx2–y2 orbitals and empty dz2 orbitals in CoO5 pentahedron concerted interplay with the bonding and antibonding orbitals of acetylene, which reduces the adsorption energy of acetylene and facilitates the activation of the inert C≡C triple bond. Thus, the defective Co-MOF exhibits the superior ethylene Faradaic efficiency of 96% and partial current density of 128 mA cm–2 at −1.0 V vs RHE compared to that of pristine Co-MOF (FEC2H4: 60%; JC2H4: 66 mA cm–2). This work delivers inspiration for spin-state regulation of active sites and sparks renewed interest in designing highly efficient electrocatalysts.    

    

* Artificial Intelligence-Driven Development of Nickel-Catalyzed Enantioselective Cross-Coupling Reactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404941646
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Transition Metal-Catalyzed Cross-Coupling Reactions, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-12-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04277")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404941646"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404941646"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404941646"))][Get cited by]]

OpenAlex: https://openalex.org/W4404941646 (Open access: False)
    
[[https://openalex.org/A5020503704][Yadong Gao]], [[https://openalex.org/A5009307008][Kunjun Hu]], [[https://openalex.org/A5047983120][Jianhang Rao]], [[https://openalex.org/A5108264438][Qiang Zhu]], [[https://openalex.org/A5033384728][Kuangbiao Liao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04277 
     
The conventional approach to developing asymmetric synthetic methods relies heavily on empirical optimization. However, the integration of artificial intelligence (AI) and high-throughput experimentation (HTE) technology presents a paradigm shift with immense potential to revolutionize the discovery and optimization of asymmetric reactions. In this study, we present an efficient workflow for the development of a series of nickel-catalyzed asymmetric cross-coupling reactions, leveraging AI and HTE technology. Many nickel-catalyzed enantioselective cross-coupling reactions share a common Ni(III) intermediate, which dictates the enantioselectivity. To harness this mechanistic insight, we embarked on developing a predictive model for nickel-catalyzed enantioselective coupling reactions, elucidating the general rules governing enantioselectivity. Through the application of data science tools and HTE technology, we curated a data set to construct an AI-based model. This model was subsequently utilized to facilitate the discovery of efficient nickel hydride-catalyzed enantioselective and regioselective cross-coupling reactions. Employing AI-assisted virtual ligand screening and HTE-enabled condition optimization, we successfully identified optimal ligands for eight coupling reactions. Consequently, a series of chiral sp3 C–C bonds were synthesized with high yield and enantioselectivity.    

    

* Controlling Product Selectivity in Photochemical CO2 Reduction with the Redox Potential of the Photosensitizer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404944465
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Droplet Microfluidics Technology
:PUBLICATION_DATE: 2024-12-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03845")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404944465"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404944465"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404944465"))][Get cited by]]

OpenAlex: https://openalex.org/W4404944465 (Open access: False)
    
[[https://openalex.org/A5108049818][Lei Zhang]], [[https://openalex.org/A5011977174][Andressa V. Müller]], [[https://openalex.org/A5075691616][Sai Puneet Desai]], [[https://openalex.org/A5004375411][David C. Grills]], [[https://openalex.org/A5083979016][Dmitry E. Polyansky]], [[https://openalex.org/A5006832213][Renato N. Sampaio]], [[https://openalex.org/A5080197399][Javier J. Concepcion]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03845 
     
No abstract    

    

* Boron Designer Enzyme with a Hybrid Catalytic Dyad  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404961214
:TOPICS: Enzyme Immobilization Techniques, Electrospun Nanofibers in Biomedical Applications, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-12-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06052")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404961214"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404961214"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404961214"))][Get cited by]]

OpenAlex: https://openalex.org/W4404961214 (Open access: True)
    
[[https://openalex.org/A5032959008][Lars Longwitz]], [[https://openalex.org/A5028183720][Marijn D. Kamer]], [[https://openalex.org/A5060375530][Bart Brouwer]], [[https://openalex.org/A5087468780][A.M.W.H. Thunnissen]], [[https://openalex.org/A5032880385][Gérard Roelfes]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06052 
     
No abstract    

    

* Using Enzymes for Catalysis under Industrial Conditions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404974317
:TOPICS: Enzyme Immobilization Techniques, Metabolic Engineering and Synthetic Biology, Technologies for Biofuel Production from Biomass
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05265")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404974317"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404974317"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404974317"))][Get cited by]]

OpenAlex: https://openalex.org/W4404974317 (Open access: False)
    
[[https://openalex.org/A5086466356][Elif Erdem]], [[https://openalex.org/A5036903025][John M. Woodley]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05265 
     
No abstract    

    

* Deciphering Faujasite Zeolite Dealumination at the Atomic Scale  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404974759
:TOPICS: Zeolite Chemistry and Catalysis, Catalytic Nanomaterials, Novel Methods for Cesium Removal from Wastewater
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03036")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404974759"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404974759"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404974759"))][Get cited by]]

OpenAlex: https://openalex.org/W4404974759 (Open access: False)
    
[[https://openalex.org/A5043145785][Zhuoran Wang]], [[https://openalex.org/A5079354447][Thomas Jarrin]], [[https://openalex.org/A5010028411][Mickaël Rivallan]], [[https://openalex.org/A5078414887][Isabelle Clémençon]], [[https://openalex.org/A5074419428][Emmanuel Soyer]], [[https://openalex.org/A5027199996][Theodorus de Bruin]], [[https://openalex.org/A5088922603][L. Lemaître]], [[https://openalex.org/A5047261367][Virgile Rouchon]], [[https://openalex.org/A5085506972][David Gajan]], [[https://openalex.org/A5013812058][Gerhard D. Pirngruber]], [[https://openalex.org/A5014892353][Céline Chizallet]], [[https://openalex.org/A5023874849][Anne Lesage]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03036 
     
No abstract    

    

* Engineering Conjugation of Covalent Organic Frameworks for Carbon Dioxide Reduction Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404990562
:TOPICS: Covalent Organic Framework Applications, CO2 Reduction Techniques and Catalysts, Metal-Organic Frameworks: Synthesis and Applications
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03742")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404990562"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404990562"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404990562"))][Get cited by]]

OpenAlex: https://openalex.org/W4404990562 (Open access: False)
    
[[https://openalex.org/A5101741759][Shuang Zheng]], [[https://openalex.org/A5113124915][Shuai Xia]], [[https://openalex.org/A5044605278][Zhaofeng Ouyang]], [[https://openalex.org/A5009058201][Shuai Bi]], [[https://openalex.org/A5015297626][Yubin Fu]], [[https://openalex.org/A5040261155][Guojuan Liu]], [[https://openalex.org/A5100322900][Yan Wang]], [[https://openalex.org/A5069765087][Qing Xu]], [[https://openalex.org/A5028394871][Gaofeng Zeng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03742 
     
No abstract    

    

* Correction to “Mixed Silver–Bismuth Oxides: A Robust Oxygen Evolution Catalyst Operating at Low pH and Elevated Temperatures”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404991001
:TOPICS: Catalytic Processes in Materials Science, Electrocatalysts for Energy Conversion, Electronic and Structural Properties of Oxides
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c07007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404991001"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404991001"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404991001"))][Get cited by]]

OpenAlex: https://openalex.org/W4404991001 (Open access: False)
    
[[https://openalex.org/A5014780715][Darcy Simondson]], [[https://openalex.org/A5033971776][Manjunath Chatti]], [[https://openalex.org/A5079752274][James L. Gardiner]], [[https://openalex.org/A5069370180][Brittany Kerr]], [[https://openalex.org/A5089189830][Dijon A. Hoogeveen]], [[https://openalex.org/A5082353134][Pavel V. Cherepanov]], [[https://openalex.org/A5031911397][Inga Kuschnerus]], [[https://openalex.org/A5042031508][Tam D. Nguyen]], [[https://openalex.org/A5042673824][Bernt Johannessen]], [[https://openalex.org/A5015023372][Shery L. Y. Chang]], [[https://openalex.org/A5017109393][Douglas R. MacFarlane]], [[https://openalex.org/A5002235771][Rosalie K. Hocking]], [[https://openalex.org/A5062733036][Alexandr N. Simonov]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c07007 
     
No abstract    

    

* Dual Nickel/Photoredox-Catalyzed Aryl Etherification Enabled by an Oxidative Near-Infrared-to-Blue Triplet–Triplet Annihilation Upconversion System Leveraging Spin-Forbidden Excitation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404995780
:TOPICS: Radical Photochemical Reactions, Sulfur-Based Synthesis Techniques, Catalytic C–H Functionalization Methods
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06084")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404995780"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404995780"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404995780"))][Get cited by]]

OpenAlex: https://openalex.org/W4404995780 (Open access: False)
    
[[https://openalex.org/A5067437484][Logan R. Beck]], [[https://openalex.org/A5027086641][Katherine A. Xie]], [[https://openalex.org/A5019978169][Brendan C. Lainhart]], [[https://openalex.org/A5046082892][Trevor C. Sherwood]], [[https://openalex.org/A5088370687][Eric R. Welin]], [[https://openalex.org/A5044707223][Candice L. Joe]], [[https://openalex.org/A5074994681][Tomislav Rovis]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06084 
     
No abstract    

    

* Pd and Fe Cocatalyzed Synthesis of Remotely Borylated Aza-Heterocycles  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404998360
:TOPICS: Catalytic C–H Functionalization Methods, Catalytic Cross-Coupling Reactions, Radical Photochemical Reactions
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05702")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404998360"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404998360"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404998360"))][Get cited by]]

OpenAlex: https://openalex.org/W4404998360 (Open access: False)
    
[[https://openalex.org/A5002090481][Shreeja Bhatt]], [[https://openalex.org/A5092457737][Aja M. Nicely]], [[https://openalex.org/A5068741247][Camila U. Powell]], [[https://openalex.org/A5075594838][Marylin C. Huff]], [[https://openalex.org/A5054755565][Stefan Jon Thibodeaux]], [[https://openalex.org/A5010750871][Ya‐Nong Wang]], [[https://openalex.org/A5071047360][Serhii Vasylevskyi]], [[https://openalex.org/A5053697725][Kami L. Hull]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05702 
     
No abstract    

    

* Pd-Catalyzed Difluoroalkylation of Alkenes Using Chlorodifluoroalkanes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405002150
:TOPICS: Fluorine in Organic Chemistry, Inorganic Fluorides and Related Compounds
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06842")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405002150"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405002150"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405002150"))][Get cited by]]

OpenAlex: https://openalex.org/W4405002150 (Open access: False)
    
[[https://openalex.org/A5100378437][Jing Wang]], [[https://openalex.org/A5101101078][Qixin Zhou]], [[https://openalex.org/A5020457126][Liejin Zhou]], [[https://openalex.org/A5067205564][Zuxiao Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06842 
     
No abstract    

    

* Oxidation State of Single-Atom Re/TiO2 Hydrogenation Catalysts: A Computational Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405008567
:TOPICS: Catalytic Processes in Materials Science, Catalysis and Hydrodesulfurization Studies, Nanomaterials for catalytic reactions
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05697")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405008567"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405008567"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405008567"))][Get cited by]]

OpenAlex: https://openalex.org/W4405008567 (Open access: True)
    
[[https://openalex.org/A5035603699][A. Sreenithya]], [[https://openalex.org/A5066349037][Alexander A. Kolganov]], [[https://openalex.org/A5013737627][In Won Yeu]], [[https://openalex.org/A5114994105][Muhammad Helmi Risansyauqi]], [[https://openalex.org/A5074252826][Evgeny A. Pidko]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05697 
     
No abstract    

    

* Electronic Interactions between Anchored Molecular Catalyst and Support  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4405023659
:TOPICS: Catalysis and Oxidation Reactions, Catalytic Processes in Materials Science, Surface Chemistry and Catalysis
:PUBLICATION_DATE: 2024-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05947")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405023659"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405023659"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405023659"))][Get cited by]]

OpenAlex: https://openalex.org/W4405023659 (Open access: False)
    
[[https://openalex.org/A5032407202][Stephanie A. Johnson]], [[https://openalex.org/A5006690638][James R. Wilkes]], [[https://openalex.org/A5040290819][Dunwei Wang]], [[https://openalex.org/A5086992939][Jeffery A. Byers]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05947 
     
Immobilizing molecular catalysts on surfaces introduces spatial control of catalysis and promises improved stability and recyclability of the catalyst. The interplays between the support and the immobilized molecular species, however, remain underexplored. Using Ni as a prototypical support, here we report a study on how the electronic interactions between the support and the molecular catalyst impacts the reactivity. This work was built upon our previous successes in switching the reactivity of iron bis(iminopyridine) alkoxide complexes through redox toggling, where the anchored iron(II) complex polymerizes lactide, and its cationic iron(III) counterpart polymerizes epoxides. It was found that Ni as a metal support could readily oxidize the complex to exhibit catalytic activity toward epoxide polymerization. The charge transfer between Ni and the Fe complex could be modulated by either electrochemical reduction or adding a layer of TiO2. The results are expected to have major implications for research efforts aimed at converging homogeneous and heterogeneous catalysis.    

    
