#+filetags: ACS_Catalysis
#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sat Feb 10 00:42:27 2024

Found 25 results from 2024-02-03 to 2024-02-10
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Unlocking the Potential of 5-Hydroxy-2(5H)-furanone as a Platform for Bio-Based Four Carbon Chemicals  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391472682
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Enzyme Immobilization Techniques, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04872")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391472682"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391472682"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391472682"))][Get cited by]]

OpenAlex: https://openalex.org/W4391472682 (Open access: False)
    
[[https://openalex.org/A5077107342][Yayati Naresh Palai]], [[https://openalex.org/A5051687801][Atsushi Fukuoka]], [[https://openalex.org/A5090337296][Abhijit Shrotri]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04872 
     
No abstract    

    

* Revealing the Size Effect of Ceria Nanocube-Supported Platinum Nanoparticles in Complete Propane Oxidation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391473249
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06139")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391473249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391473249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391473249"))][Get cited by]]

OpenAlex: https://openalex.org/W4391473249 (Open access: False)
    
[[https://openalex.org/A5085640519][Shasha Ge]], [[https://openalex.org/A5041535237][Wei Fan]], [[https://openalex.org/A5064104167][Xiaoping Tang]], [[https://openalex.org/A5027626134][Yao Cui]], [[https://openalex.org/A5033936824][Dong Wang]], [[https://openalex.org/A5085852346][Xue‐Qing Gong]], [[https://openalex.org/A5031493683][Sheng Dai]], [[https://openalex.org/A5012006645][Yang Lou]], [[https://openalex.org/A5034676524][Jie Tang]], [[https://openalex.org/A5080435466][Yanglong Guo]], [[https://openalex.org/A5058391979][Zhan Wang]], [[https://openalex.org/A5059830462][Li Wang]], [[https://openalex.org/A5032176049][Yun Guo]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06139 
     
The elimination of propane is one of the key tasks in reducing volatile organic compounds (VOCs) and automotive exhaust emissions. The platinum nanoparticle (NP) is a promising catalyst for propane oxidation, while the study of its structural characteristics and functionality remains in its infancy. In this work, we synthesized the nanocubes CeO2 with a well-defined (100) facet supporting Pt NPs with various sizes, from 1.3 to 7 nm, and systematically investigated the effect of the Pt size on complete propane oxidation efficiency. In particular, CeO2(100) supported Pt NPs smaller than 4 nm promote the formation of positively charged Pt sites, which hinder the adsorption and activation of propane and reduce the intrinsic activity for propane oxidation. Consequently, within this size range, the catalytic performance is primarily influenced by the electronic state of the Pt species, with metallic Pt being identified as the active site for the reaction. Conversely, as the particle size exceeds 4 nm, metallic Pt particles become dominant and the geometric structure starts to influence the activity as well. Such entanglement of electronic and geometric factors gives rise to a volcano relationship between reaction rates and Pt particle sizes ranging from 1.3 to 7 nm, while an increased correlation can be observed between the turnover frequencies and the particle sizes in this range. This knowledge can guide the synthesis of highly active catalysts, enabling the efficient oxidation of VOCs with reduced precious metal loadings.    

    

* N-Heterocyclic Carbene-Carbodiimide (NHC-CDI) Betaines as Organocatalysts for β-Butyrolactone Polymerization: Synthesis of Green PHB Plasticizers with Tailored Molecular Weights  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391473810
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Transition Metal Catalysis, Biodegradable Polymers as Biomaterials and Packaging
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05357")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391473810"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391473810"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391473810"))][Get cited by]]

OpenAlex: https://openalex.org/W4391473810 (Open access: True)
    
[[https://openalex.org/A5046769905][David Sánchez-Roa]], [[https://openalex.org/A5044974820][Valentina Sessini]], [[https://openalex.org/A5011679409][Marta E. G. Mosquera]], [[https://openalex.org/A5041336405][Juan Cámpora]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05357  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05357][pdf]])
     
The manufacture of poly(3-hydroxybutyrate) (PHB) stands out as a promising alternative to traditional plastics. This polymer is usually produced by bacteria-based biotechnology or metal-catalyzed ring-opening polymerization (ROP) of β-butyrolactone (β-BL). Nevertheless, commercial PHB suffers from different issues, from poor processability to high production costs. Herein, we report the chemical synthesis of PHB from the ROP of rac-β-butyrolactone promoted by a zwitterionic organocatalyst, an N-heterocyclic carbene-carbodiimide (NHC-CDI) betaine adduct. This reaction has been investigated by a combination of experimental and computational methods. The catalyst cleaves the β-BL via nucleophilic displacement of the C–O(carboxyl) bond followed by intramolecular elimination to give protonated betaine–crotonate ion pairs, the active polymerization initiators. Polymer growth is propagated and controlled by these betaine ion pairs, which render amorphous low-molecular-weight PHBs by an unusual mechanism with rapid chain transfer to the monomer regime, analogous to the well-known mechanism of ethylene oligomerization with late transition-metal catalysts. The resulting material is suitable as a biodegradable and biocompatible plasticizer for commercial bacterial or synthetic PHB. Perfect compatibility between the matrix and the additive and a significant reduction of the crystallinity resulted in a more flexible and resilient material.    

    

* Assembled Quantum Dot Porous Clusters for Enhanced Photocatalytic Reduction of Quinone to Hydroquinone  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391475441
:TOPICS: Applications of Quantum Dots in Nanotechnology, Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-01-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04492")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391475441"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391475441"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391475441"))][Get cited by]]

OpenAlex: https://openalex.org/W4391475441 (Open access: False)
    
[[https://openalex.org/A5005132094][Yufeng Qin]], [[https://openalex.org/A5041477172][Xiang Cheng]], [[https://openalex.org/A5009441078][Zhuo Zhao]], [[https://openalex.org/A5080850908][Chaodan Pu]], ACS Catalysis. 14(3)] 2024. https://doi.org/10.1021/acscatal.3c04492 
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391476187
:TOPICS: 
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i003_1766342")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391476187"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391476187"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391476187"))][Get cited by]]

OpenAlex: https://openalex.org/W4391476187 (Open access: True)
    
, ACS Catalysis. 14(3)] 2024. https://doi.org/10.1021/csv014i003_1766342  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i003_1766342][pdf]])
     
ADVERTISEMENT RETURN TO ISSUEPREVArticleNEXTIssue Editorial MastheadCite this: ACS Catal. 2024, 14, 3, XXX-XXXPublication Date (Web):February 2, 2024Publication History Published online2 February 2024Published inissue 2 February 2024https://doi.org/10.1021/csv014i003_1766342Copyright © 2024 American Chemical SocietyRequest reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (198 KB) Get e-Alertsclose Get e-Alerts    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391476423
:TOPICS: 
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i003_1766341")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391476423"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391476423"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391476423"))][Get cited by]]

OpenAlex: https://openalex.org/W4391476423 (Open access: True)
    
, ACS Catalysis. 14(3)] 2024. https://doi.org/10.1021/csv014i003_1766341  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i003_1766341][pdf]])
     
ADVERTISEMENT RETURN TO ISSUEPREVArticleIssue Publication InformationCite this: ACS Catal. 2024, 14, 3, XXX-XXXPublication Date (Web):February 2, 2024Publication History Published online2 February 2024Published inissue 2 February 2024https://doi.org/10.1021/csv014i003_1766341Copyright © 2024 American Chemical SocietyRequest reuse permissions This publication is free to access through this site. Learn MoreArticle Views-Altmetric-Citations-LEARN ABOUT THESE METRICSArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated. Share Add toView InAdd Full Text with ReferenceAdd Description ExportRISCitationCitation and abstractCitation and referencesMore Options Share onFacebookTwitterWechatLinked InRedditEmail PDF (153 KB) Get e-Alertsclose Get e-Alerts    

    

* Insight into Selectivity Differences of Glycerol Electro-Oxidation on Pt(111) and Ag(111)  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391484173
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05551")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391484173"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391484173"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391484173"))][Get cited by]]

OpenAlex: https://openalex.org/W4391484173 (Open access: False)
    
[[https://openalex.org/A5061862591][Zhongjie Meng]], [[https://openalex.org/A5011352251][David Tran]], [[https://openalex.org/A5074226300][Johan Hjelm]], [[https://openalex.org/A5028337707][Henrik H. Kristoffersen]], [[https://openalex.org/A5083668074][Jan Rossmeisl]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05551 
     
Electro-oxidation is a way to utilize glycerol, a byproduct of biodiesel production, to produce fuels and feedstock chemicals for the chemical industry. A significant challenge is to get products with high selectivity, so it is desirable to understand the glycerol oxidation mechanisms in further detail. Using density functional theory calculations, we investigated possible glycerol oxidation intermediates on Pt(111) and Ag(111). We find that the different adsorption preferences of the intermediates on Pt (adsorption via carbon atoms) and Ag (adsorption via oxygen atoms) lead to different preferred reaction pathways, resulting in different products. The reaction pathways on both surfaces involve glyceraldehyde as a key intermediate; however, upon further oxidation, Pt(111) preferentially produces glyceric acid (CH2OH–CHOH–COOH), while on Ag(111) C–C bonds are broken, which leads to the production of glycolaldehyde and formic acid (CH2OH–CHO and HCOOH). These predictions agree well with the experimental outcome of the electro-oxidation of glycerol on Pt and Ag surfaces. Our study therefore provides useful insights for optimizing the selectivity of glycerol oxidation and improving the utilization of glycerol.    

    

* Metal–Support Interaction between Titanium Oxynitride and Pt Nanoparticles Enables Efficient Low-Pt-Loaded High-Performance Electrodes at Relevant Oxygen Reduction Reaction Current Densities  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391484257
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c03883")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391484257"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391484257"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391484257"))][Get cited by]]

OpenAlex: https://openalex.org/W4391484257 (Open access: True)
    
[[https://openalex.org/A5035921159][Armin Hrnjić]], [[https://openalex.org/A5026019396][Ana Rebeka Kamšek]], [[https://openalex.org/A5093435006][Lazar Bijelić]], [[https://openalex.org/A5067506046][Anja Lončar]], [[https://openalex.org/A5002824921][Nik Maselj]], [[https://openalex.org/A5023655269][Milutin Smiljanić]], [[https://openalex.org/A5025812387][Jan Trputec]], [[https://openalex.org/A5053380398][Nikolay Vovk]], [[https://openalex.org/A5057907379][Luka Pavko]], [[https://openalex.org/A5035475331][Francisco Ruiz-Zepeda]], [[https://openalex.org/A5059203752][Marjan Bele]], [[https://openalex.org/A5079953428][Primož Jovanovič]], [[https://openalex.org/A5065843632][Nejc Hodnik]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c03883  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c03883][pdf]])
     
In the present work, we report on a synergistic relationship between platinum nanoparticles and a titanium oxynitride support (TiOxNy/C) in the context of oxygen reduction reaction (ORR) catalysis. As demonstrated herein, this composite configuration results in significantly improved electrocatalytic activity toward the ORR relative to platinum dispersed on carbon support (Pt/C) at high overpotentials. Specifically, the ORR performance was assessed under an elevated mass transport regime using the modified floating electrode configuration, which enabled us to pursue the reaction closer to PEMFC-relevant current densities. A comprehensive investigation attributes the ORR performance increase to a strong interaction between platinum and the TiOxNy/C support. In particular, according to the generated strain maps obtained via scanning transmission electron microscopy (STEM), the Pt-TiOxNy/C analogue exhibits a more localized strain in Pt nanoparticles in comparison to that in the Pt/C sample. The altered Pt structure could explain the measured ORR activity trend via the d-band theory, which lowers the platinum surface coverage with ORR intermediates. In terms of the Pt particle size effect, our observation presents an anomaly as the Pt-TiOxNy/C analogue, despite having almost two times smaller nanoparticles (2.9 nm) compared to the Pt/C benchmark (4.8 nm), manifests higher specific activity. This provides a promising strategy to further lower the Pt loading and increase the ECSA without sacrificing the catalytic activity under fuel cell-relevant potentials. Apart from the ORR, the platinum-TiOxNy/C interaction is of a sufficient magnitude not to follow the typical particle size effect also in the context of other reactions such as CO stripping, hydrogen oxidation reaction, and water discharge. The trend for the latter is ascribed to the lower oxophilicity of Pt-based on electrochemical surface coverage analysis. Namely, a lower surface coverage with oxygenated species is found for the Pt-TiOxNy/C analogue. Further insights were provided by performing a detailed STEM characterization via the identical location mode (IL-STEM) in particular, via 4DSTEM acquisition. This disclosed that Pt particles are partially encapsulated within a thin layer of TiOxNy origin.    

    

* Selective Hydrogenation of Alkyne by Atomically Precise Pd6 Nanocluster Catalysts: Accurate Construction of the Coplanar and Specific Active Sites  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391484269
:TOPICS: Structural and Functional Study of Noble Metal Nanoclusters, Catalytic Reduction of Nitro Compounds, Plasmonic Nanoparticles: Synthesis, Properties, and Applications
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05833")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391484269"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391484269"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391484269"))][Get cited by]]

OpenAlex: https://openalex.org/W4391484269 (Open access: False)
    
[[https://openalex.org/A5034676524][Jie Tang]], [[https://openalex.org/A5060107836][Kun Jia]], [[https://openalex.org/A5091816086][Ruiqi Zhang]], [[https://openalex.org/A5055920244][Chao Liu]], [[https://openalex.org/A5086193630][Xinzhang Lin]], [[https://openalex.org/A5065838284][Tingting Ge]], [[https://openalex.org/A5011085153][Xiaorui Liu]], [[https://openalex.org/A5070736386][Qiao Zhao]], [[https://openalex.org/A5013434268][Wei Liu]], [[https://openalex.org/A5055822249][Ding Ma]], [[https://openalex.org/A5081854327][Hongjun Fan]], [[https://openalex.org/A5066309957][Jiahui Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05833 
     
Atomically precise nanoclusters are promising model catalysts to understand the relationship between structure and catalytic activity. However, designing efficient active sites remains challenging because the highly covered ligands obscure the metal sites. Herein, we reported a Pd6(S-Adm)6(PPh3)(PPh) nanocluster, which shows high selectivity in the semihydrogenation of aromatic alkyne. The Pd6 nanocluster has a unique chair structure, where the pan is composed of the coplanar Pd atoms, the back is composed of two S-Adm ligands, and the legs are composed of four S-Adm, one PPh3, and one PPh ligands. Experiments reveal that the high selectivity of intact Pd6 nanocluster is attributed to the synergistic effect of thiols and phosphines, modulating the electron properties and benefiting the proper hydrogen dissociation ability and desorption of product. Interestingly, it was found that the exposed coplanar Pd atoms could provide specific active sites for the adsorption of C≡C and benzene ring. DFT calculations show that phenylacetylene and styrene adsorb on the coplanar Pd6 much weaker than on the Pd(111) surface, allowing the styrene to be desorbed before further hydrogenation. The phenyl adsorption constrains that the hydrogenation can occur only on the coplanar Pd6, which is more facile for phenylacetylene than for styrene, and results in semihydrogenation.    

    

* Tailoring the Olefin Selectivity in Catalytic Oxidative Dehydrogenation of Light Alkane by the Isolation Strategy  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391485473
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05419")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391485473"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391485473"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391485473"))][Get cited by]]

OpenAlex: https://openalex.org/W4391485473 (Open access: False)
    
[[https://openalex.org/A5042063600][Yicong Chai]], [[https://openalex.org/A5074446754][Yanliang Zhou]], [[https://openalex.org/A5016546361][Sen Lin]], [[https://openalex.org/A5068754344][Xiaodong Wang]], [[https://openalex.org/A5047617959][Jin Lin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05419 
     
Olefins are important building blocks that have been extensively used to produce diverse consumer products in petrochemical industry. Owing to the requirement of low-carbon-footprint processes and the increasing use of light alkanes sourced from shale gas, an environmentally friendly and economic route alternative to the state-of-the-art steam cracking of crude oil has been investigated for olefin production. The oxidative dehydrogenation (ODH) of alkanes to olefins has attracted wide attention due to the absence of thermodynamic limitations and coke formation. However, excessive oxidation of olefin is prone to occur in this process. Developing a suitable ODH catalyst with high performance, particularly with enhanced selectivity, is more and more urgent but still remains a challenge. In this Review, we talk about the representative currently developed isolation strategies to optimize the selectivity of olefins via the ODH process, particularly for the conversion of ethane to ethylene, which include the dispersion regulation of metal oxide, the isolation of metal and nonmetal sites, the construction of dual functional sites to isolate dehydrogenation and oxidation steps, and the adoption of selective oxygen species with the promotion of soft oxidants as reactants. Furthermore, the mechanistic aspects about the activation of ethane and the participation of oxygen species for tailoring the selectivity are then classified and discussed in detail. Finally, the perspectives and the emerging technologies for the ODH process are listed and evaluated.    

    

* The Role of Adsorbed Species in 1-Butene Isomerization: Parahydrogen-Induced Polarization NMR of Pd–Au Catalyzed Butadiene Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391485519
:TOPICS: NMR Spectroscopy Techniques, Advancements in Density Functional Theory, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05968")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391485519"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391485519"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391485519"))][Get cited by]]

OpenAlex: https://openalex.org/W4391485519 (Open access: False)
    
[[https://openalex.org/A5081085463][Weiyu Wang]], [[https://openalex.org/A5063295957][Richard J. Lewis]], [[https://openalex.org/A5053116259][Bin Lü]], [[https://openalex.org/A5030863883][Qiang Wang]], [[https://openalex.org/A5020068159][Graham J. Hutchings]], [[https://openalex.org/A5016344450][Jun Xu]], [[https://openalex.org/A5055850550][Feng Deng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05968 
     
Isomerization of 1-butene critically influences product distributions in 1,3-butadiene hydrogenation. However, distinguishing between the isomerization and hydrogenation pathways is challenging. Here, we employ parahydrogen-induced polarization (PHIP) NMR spectroscopy to determine the extent of the isomerization pathway when using Pd–Au bimetallic nanoparticles synthesized via a colloidal protocol in the presence or absence of a polyvinylpyrrolidone (PVP) stabilizing ligand and immobilized on TiO2. Residual additives, in particular, sulfur, are observed to considerably influence the pairwise hydrogenation and 1-butene isomerization pathways. PHIP NMR analysis reveals that the PVP ligand can induce strong polarized signals, likely due to restricted proton migration, but minimally impact 1-butene isomerization. In contrast, removing surface sulfur species introduced during catalyst synthesis profoundly enhances 1-butene isomerization by reducing the hydrogen concentration at the nanoparticle surface. This work elucidates how residual species can modulate key reaction pathways such as isomerization during 1,3-butadiene hydrogenation, with implications for rational catalyst design.    

    

* Tailoring Metal-Ion-Doped Carbon Nitrides for Photocatalytic Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391486029
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391486029"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391486029"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391486029"))][Get cited by]]

OpenAlex: https://openalex.org/W4391486029 (Open access: False)
    
[[https://openalex.org/A5006958502][Shanping Liu]], [[https://openalex.org/A5080802270][Valentin Diez‐Cabanes]], [[https://openalex.org/A5069062661][Dong Fan]], [[https://openalex.org/A5080107062][Peixiang Lu]], [[https://openalex.org/A5027738164][Yuanxing Fang]], [[https://openalex.org/A5075963769][Markus Antonietti]], [[https://openalex.org/A5087859676][Guillaume Maurin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05961 
     
Poly(heptazine imides) (PHIs) have emerged as prominent layered carbon nitride-based materials with potential oxygen evolution reaction (OER) catalytic activity owing to their strong VIS light absorption, long excited-state lifetimes, high surface-to-volume ratios, and the possibility of tuning their properties via hosting different metal ions in their pores. A series of metal-ion-doped PHI-M (M = K+, Rb+, Mg2+, Zn2+, Mn2+, and Co2+) were first systematically explored using density functional theory calculations. These simulations led an in-depth understanding of the microscopic OER mechanism in these systems and identified PHI-Co2+ as the best OER catalyst of this family of PHIs, whereas PHI-Mn2+ can be an alternative promising OER catalyst. This level of performance was attributed to a thermodynamically favorable formation of the reaction intermediates as well as its red-shifted absorption in the VIS region involving the population of long-lived states, as revealed by time-dependent density functional theory calculations. We further demonstrated that the electronic properties of the *OH intermediates (Bader population, crystal orbital Hamilton population analysis, and adsorption energies) are reliable descriptors to anticipate the OER activity of this family of PHIs. This rational analysis paved the way toward the prediction of the OER performance of another PHI-M derivative, i.e., PHI-Fe2+. The computationally explored PHI-Fe2+, PHI-Mn2+, and PHI-Co2+ systems were then synthesized alongside PHI-K+, and their photocatalytic OER activities were assessed. These experimental findings confirmed the best photocatalytic OER performance for PHI-Co2+ with an oxygen production of 31.2 μmol·h–1 that is 60 times higher than the pristine g-C3N4 (0.5 μmol·h–1), whereas PHI-Fe2+ and PHI-Mn2+ are seen as alternative OER catalysts with attractive oxygen production of 11.20 and 4.69 μmol·h–1, respectively. Decisively, this joint experimental–computational study reveals PHI-Co2+ to be among the best of the OER catalysts so far reported in the literature including some perovskites.    

    

* Highly Selective Upgrading of Polyethylene into Light Aromatics via a Low-Temperature Melting-Catalysis Strategy  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391486048
:TOPICS: Microplastic Pollution in Marine and Terrestrial Environments, Global E-Waste Recycling and Management, Polymer Crystallization and Properties
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05098")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391486048"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391486048"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391486048"))][Get cited by]]

OpenAlex: https://openalex.org/W4391486048 (Open access: False)
    
[[https://openalex.org/A5008788445][Zhe Zhang]], [[https://openalex.org/A5078632164][Huan Chen]], [[https://openalex.org/A5033895107][Guixiang Li]], [[https://openalex.org/A5067744419][Weigang Hu]], [[https://openalex.org/A5059445221][Bo Niu]], [[https://openalex.org/A5070718341][Donghui Long]], [[https://openalex.org/A5010941700][Yayun Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05098 
     
The selective upgrading of polyethylene waste into light aromatics is hampered by relatively high C–C bond cleavage temperatures and low product selectivity. Herein, we report a low-temperature melting-catalysis strategy that directly upgrades low-density polyethylene (LDPE) into light aromatics over commercial ZSM-5 zeolite under mild conditions, eliminating the need for precious metals, solvent, or external H2. Experimental results combined with DFT calculations and molecular dynamics simulations revealed that the molten LDPE microenvironment facilitates intimate LDPE-catalyst contact, promoting primary C–C cleavage while suppressing olefin intermediates diffusion out of pores. This feature increases the residence time for subsequent direct olefin cyclization within the confined micropores. Moreover, online mass spectra confirmed that the in situ generated hydrogen from cyclization and dehydroaromatization reactions plays a vital role in C–C bond scission. By optimizing the reaction conditions, a light aromatic yield of 50.6 wt % with an impressive selectivity of 90.9% toward benzene, toluene, and xylenes was achieved at 280 °C for 1 h. This strategy is not limited to the model polyethylene but also demonstrates remarkable efficiency in the depolymerization of various widely used polyethylene-rich plastics, enabling an economically viable and environmentally benign chemical recycling path for plastic wastes.    

    

* Ultrastable and Phosphoric Acid-Resistant PtRhCu@Pt Oxygen Reduction Electrocatalyst for High-Temperature Polymer Electrolyte Fuel Cells  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391509433
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04488")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391509433"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391509433"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391509433"))][Get cited by]]

OpenAlex: https://openalex.org/W4391509433 (Open access: False)
    
[[https://openalex.org/A5088459641][An Zhao]], [[https://openalex.org/A5054722093][Huanqiao Li]], [[https://openalex.org/A5091381220][Xiaoming Zhang]], [[https://openalex.org/A5012104204][Zhangxun Xia]], [[https://openalex.org/A5069849278][Hong Zhang]], [[https://openalex.org/A5078357872][Wenling Chu]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5000140137][Suli Wang]], [[https://openalex.org/A5039323596][Gongquan Sun]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04488 
     
No abstract    

    

* Photoredox-Driven Three-Component Coupling of Aryl Halides, Olefins, and O2  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391522091
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05988")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391522091"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391522091"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391522091"))][Get cited by]]

OpenAlex: https://openalex.org/W4391522091 (Open access: True)
    
[[https://openalex.org/A5060466975][Mark C. Maust]], [[https://openalex.org/A5031746021][Simon B. Blakey]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05988  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05988][pdf]])
     
Modern organic synthesis requires methodologies that bring together abundant feedstock chemicals in a mild and efficient manner. To aid in this effort, we have developed a multicomponent radical hydroxyarylation reaction that utilizes aryl halides, olefins, and O2 as the reaction components. Crucial to this advance was an oxidative, rather than a reductive, approach to aryl radical generation, which enables reaction tolerance to O2. This methodology displays a broad functional group tolerance with a variety of functionalized aryl halides and a broad array of olefins. Development of this methodology enables rapid access to biologically relevant hydroxyaryl products from simple, commercially available starting materials.    

    

* Photoelectrochemical Urea Synthesis from Nitrate and Carbon Dioxide on GaN Nanowires  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391543013
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04264")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391543013"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391543013"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391543013"))][Get cited by]]

OpenAlex: https://openalex.org/W4391543013 (Open access: False)
    
[[https://openalex.org/A5005809281][Wan Jae Dong]], [[https://openalex.org/A5005426309][Jan Paul Menzel]], [[https://openalex.org/A5037803284][Zhengwei Ye]], [[https://openalex.org/A5041280269][Ishtiaque Ahmed Navid]], [[https://openalex.org/A5047600031][Peng Zhou]], [[https://openalex.org/A5010438957][Ke Yang]], [[https://openalex.org/A5089129603][Víctor S. Batista]], [[https://openalex.org/A5070775523][Zetian Mi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04264 
     
Semiconductor photoelectrodes can be used to synthesize urea from carbon dioxide and nitrate under solar light. We find that GaN nanowires (NWs) have inherent catalytic activity for nitrate conversion to nitrite, while Ag cocatalysts loaded onto GaN NWs further promote the performance of photoelectrochemical urea synthesis. Under optimized conditions, a high faradaic efficiency of 75.6 ± 2.6% was achieved at a potential of −0.3 vs reversible hydrogen electrode. Control experiments and theoretical calculations suggest that the high selectivity of urea originates from the facilitated C–N coupling between key intermediates of NO2 and COO– at an early stage of the reduction reaction. This work demonstrates the potential of GaN NWs with loaded Ag cocatalysts to achieve solar-powered urea synthesis with an efficiency higher than that of previously reported methods.    

    

* 9-(4-Halo-2,6-xylyl)-10-methylacridinium Ion as an Effective Photoredox Catalyst for Oxygenation and Trifluoromethylation of Toluene Derivatives  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391558510
:TOPICS: Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Applications of Photoredox Catalysis in Organic Synthesis, Chemistry of Noble Gas Compounds and Interactions
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06111")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391558510"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391558510"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391558510"))][Get cited by]]

OpenAlex: https://openalex.org/W4391558510 (Open access: False)
    
[[https://openalex.org/A5084268749][Kei Ohkubo]], [[https://openalex.org/A5009596447][Sakiko Matsumoto]], [[https://openalex.org/A5010296653][Haruyasu Asahara]], [[https://openalex.org/A5066193981][Shunichi Fukuzumi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06111 
     
9-(2,6-Dimethylphenyl)-10-methylacridinium perchlorate ([Acr+–Xyl]ClO4–), 9-(4-chloro-2,6-dimethylphenyl)-10-methylacridinium perchlorate ([Acr+–XylCl]ClO4–), and 9-(4-fluoro-2,6-dimethylphenyl)-10-methylacridinium perchlorate ([Acr+–XylF]ClO4–) were synthesized by the Grignard reaction. The one-electron reduction potentials (Ered vs SCE) of Acr+–Xyl, Acr+–XylCl, and Acr+–XylF in deaerated acetonitrile (MeCN) were determined by cyclic voltammetry to be nearly the same as −0.55, −0.53, and −0.53 V, respectively. On the other hand, the one-electron oxidation potentials (Eox vs SCE) of Acr+–Xyl, Acr+–XylF, and Acr+–XylCl were determined by the second-harmonic alternative current voltammetric method to be +2.15, +2.20, and +2.21 V, respectively. The Eox value of Acr+–XylCl is higher than the Eox value of toluene (+2.20 V). Thus, photocatalytic oxygenation of toluene with oxygen occurs efficiently via electron transfer from toluene to the XylCl•+ moiety of the triplet electron-transfer state of Acr+–XylCl under photoirradiation of Acr+–XylCl in oxygen-saturated MeCN. By contrast, no oxygenation of toluene occurred with the 9-mesityl-10-methylacridinium ion (Acr+–Mes) used as a photocatalyst due to the lack of oxidizing ability to oxidize toluene. The metal-free trifluoromethylation of toluene derivatives has also been made possible by using Acr+–XylCl as a photocatalyst and S-(trifluoromethyl)dibenzothiophenium (CF3DBT+) as a trifluoromethyl source. The photocatalytic reaction mechanism was clarified by transient absorption and electrochemical measurements.    

    

* Organobismuth Compounds as Aryl Radical Precursors via Light-Driven Single-Electron Transfer  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391558560
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Catalytic Oxidation of Alcohols, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05598")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391558560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391558560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391558560"))][Get cited by]]

OpenAlex: https://openalex.org/W4391558560 (Open access: False)
    
[[https://openalex.org/A5062170356][Nicholas D. Chiappini]], [[https://openalex.org/A5089961340][Eric P. Geunes]], [[https://openalex.org/A5093868945][Ethan T. Bodak]], [[https://openalex.org/A5034006875][Robert R. Knowles]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05598 
     
A light-driven method for the generation of aryl radicals from triarylbismuth(III) and (V) reagents is described. Aryl radical generation is proposed to occur through the ligand-assisted mesolytic cleavage of an organobismuth(IV) intermediate generated from either oxidation of BiIII or reduction of BiV. This mode of aryl radical generation is demonstrated to be compatible with a range of bimolecular radical arylations, including hydroarylation of electron-deficient olefins and arylation of diboronates, disulfides, sulfonyl cyanides, phosphites, and isocyanides. The intermediacy of an aryl radical is supported by radical trapping and radical clock experiments, and BiIV–aryl mesolysis is supported computationally.    

    

* Chemoinformatic Catalyst Selection Methods for the Optimization of Copper–Bis(oxazoline)-Mediated, Asymmetric, Vinylogous Mukaiyama Aldol Reactions  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391559651
:TOPICS: Asymmetric Catalysis, Catalytic Oxidation of Alcohols, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05903")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391559651"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391559651"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391559651"))][Get cited by]]

OpenAlex: https://openalex.org/W4391559651 (Open access: False)
    
[[https://openalex.org/A5082818239][Casey L. Olen]], [[https://openalex.org/A5082026865][Andrew F. Zahrt]], [[https://openalex.org/A5061055809][Sean W. Reilly]], [[https://openalex.org/A5077988861][Danielle M. Schultz]], [[https://openalex.org/A5050525158][Khateeta M. Emerson]], [[https://openalex.org/A5040767670][David A. Candito]], [[https://openalex.org/A5058010200][Xiao Wang]], [[https://openalex.org/A5036948355][Neil A. Strotman]], [[https://openalex.org/A5060673018][Scott E. Denmark]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05903 
     
No abstract    

    

* Designing Highly Enantioselective Heterogeneous Pt Catalysts: Selective Exposure of Active Sites via Surface Modification Using Amines  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391574285
:TOPICS: Engineering of Surface Nanostructures, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00040")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391574285"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391574285"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391574285"))][Get cited by]]

OpenAlex: https://openalex.org/W4391574285 (Open access: False)
    
[[https://openalex.org/A5008737710][Byeongju Song]], [[https://openalex.org/A5070559681][Dongmin Lee]], [[https://openalex.org/A5044561633][Hyunjun Jeong]], [[https://openalex.org/A5042027893][Minji Yun]], [[https://openalex.org/A5050368068][Yongju Yun]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00040 
     
Surface modification of metal nanoparticles (NPs) with organic molecules has attracted considerable attention as an effective methodology for designing highly selective heterogeneous catalysts. In this paper, we propose a simple post-treatment strategy involving the mixing of bare Pt/Al2O3 with amines and subsequent heat treatment for preparing highly enantioselective heterogeneous catalysts for the hydrogenation of α-keto esters. Notably, treating the Pt catalyst with oleylamine (OAm) yielded a catalyst possessing considerably enhanced catalytic activity and enantioselectivity under various hydrogen pressure conditions. The OAm-treated Pt catalyst also showed high enantioselectivity over 10 consecutive cycles. Under the optimized reaction conditions, the OAm-treated Pt catalyst exhibited an enantiomeric excess (ee) of 95%, which was 15% higher than that of an unmodified Pt catalyst. Surface characterization revealed that the ratio of active sites exposed on the Pt surface can be controlled by varying the amount of the added OAm during the treatment. Specifically, the preferential passivation of under-coordinated sites of Pt NPs by the remaining OAm residues after heat treatment increased the ratio of exposed well-coordinated Pt sites, which are suitable for the stable adsorption of a chiral modifier (cinchonidine). Quantitative site fraction analysis using infrared spectroscopic studies revealed a positive linear correlation between the ee and the ratio of exposed terrace Pt sites, confirming the promoting effect of the OAm treatment on enantioselectivity. Moreover, the versatility of this strategy was demonstrated for the Pt catalysts treated with a variety of amines in enantioselective hydrogenation. These findings provide a direction for regulating the selective exposure of specific active sites using simple surface treatment to develop highly efficient heterogeneous catalysts.    

    

* Selective Oxidation of Hydrocarbons by Molecular Iron Catalysts Based on Molecular Recognition through π–π Interaction in Aqueous Medium  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391574892
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Platinum-Based Cancer Chemotherapy
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05118")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391574892"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391574892"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391574892"))][Get cited by]]

OpenAlex: https://openalex.org/W4391574892 (Open access: False)
    
[[https://openalex.org/A5032294525][Hiroto Fujisaki]], [[https://openalex.org/A5010354588][Tomoya Ishizuka]], [[https://openalex.org/A5010888790][Hiroaki Kotani]], [[https://openalex.org/A5044357340][Takahiko Kojima]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05118 
     
Oxidation enzymes possess finely organized structures to recognize specific substrates, leading to the efficient catalysis of selective oxidation reactions to generate the desired products. Inspired by such enzymes, molecular catalysts with substrate-recognition sites have been developed for decades. Here, we report the highly selective oxidation of aromatic substrates in aqueous media by catalysis with an FeII complex featuring a hydrophobic second coordination sphere (SCS) constructed by four anthracenyl groups. The FeII catalyst showed a much higher turnover frequency for the benzene-to-phenol oxidation (1.0 × 104 h–1) than for the cyclohexane-to-cyclohexanol oxidation (12 h–1). The SCS of the FeII complex works as a trapping site of aromatic substrates through π–π interaction and assists the release of the hydrophilic oxidized products to the aqueous media. A “recognition-and-release” approach also allowed the selective formation of anthracen-9-ol and 1-naphthol by direct oxidation of anthracene and naphthalene, respectively.    

    

* Mechanistic Study of Electrocatalytic Perchlorate Reduction using an Oxorhenium Complex Supported on a Ti4O7 Support  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391574966
:TOPICS: Perchlorate Contamination and Health Effects, Electrochemical Detection of Heavy Metal Ions, Battery Recycling and Rare Earth Recovery
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05680")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391574966"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391574966"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391574966"))][Get cited by]]

OpenAlex: https://openalex.org/W4391574966 (Open access: False)
    
[[https://openalex.org/A5013585682][Soroush Almassi]], [[https://openalex.org/A5049156632][Changxu Ren]], [[https://openalex.org/A5043270824][Naveen Dandu]], [[https://openalex.org/A5038104182][Anh T. Ngo]], [[https://openalex.org/A5037074212][Jinyong Liu]], [[https://openalex.org/A5074898160][Brian P. Chaplin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05680 
     
Developing a stable and active catalyst for ClO4– reduction at nonacidic pH has presented a significant challenge to the catalysis field. Previous research has demonstrated that by depositing an organometallic Re catalyst onto a Ti4O7 support (Re/Ti4O7), it was possible to stabilize the catalyst and obtain active electrocatalytic ClO4– reduction at circumneutral pH. Thus, the focus of this work was on elucidating the mechanisms of electrocatalytic ClO4– reduction in water with the Re/Ti4O7 system. Density functional theory (DFT) simulations indicated that the adsorption of the Re catalyst was exothermic on Ti4O7, and X-ray photoelectron spectroscopy (XPS) characterization indicated that Re adsorption caused a net reduction of the Ti oxidation state on the Ti4O7 surface. After ClO4– reduction experiments, XPS results indicated the presence of Ti(0)/Ti(II) surface sites. Cyclic voltammetry experiments in an acetonitrile solvent provided supporting evidence that these surface sites were electroactive and likely participated in the ClO4– reduction reaction. Analysis of batch reduction experiments in acetonitrile via kinetic modeling estimated a catalyst turnover number of 332 ± 23, which provided further evidence that the reduced Ti sites could regenerate the Re catalyst. However, these reduced Ti sites were finite in number and required the production of adsorbed hydrogen via water reduction to facilitate continuous ClO4– reduction. DFT results indicated that the reduction of ClO4– to Cl– was exothermic and that reduced Ti sites participated in the reduction reaction. The experimental and DFT results allowed a preliminary mechanism for ClO4– reduction on Re/Ti4O7 to be proposed.    

    

* Red-Light-Based Effective Photocatalysis of a Photosensitive Covalent Organic Framework Triggered Singlet Oxygen  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391576893
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Photocatalytic Materials for Solar Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05454")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391576893"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391576893"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391576893"))][Get cited by]]

OpenAlex: https://openalex.org/W4391576893 (Open access: False)
    
[[https://openalex.org/A5019310869][Kaijun Niu]], [[https://openalex.org/A5024278129][Tian‐Xiang Luan]], [[https://openalex.org/A5040232281][Jing Chen]], [[https://openalex.org/A5044301848][Hui Liu]], [[https://openalex.org/A5011669276][Ling‐Bao Xing]], [[https://openalex.org/A5056554030][Pei‐Zhou Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05454 
     
The direct application of low-energy red light for photochemical transformations is synthetically appealing but practically challenging. Covalent organic frameworks (COFs) exhibit significant potential within this domain, owing to their broad spectrum of absorption and their prevalence in photochemical reactions, despite the fact that these photocatalysts are now mainly focused on using ultraviolet (UV) and blue light. In this study, an imidazole-linked porphyrin-based COF, PyPor-COF, which exhibits a wide absorption band ranging from 200 to 700 nm, especially strong red light absorption from 630 to 700 nm, is expected to be applied in red light photocatalytic reactions. PyPor-COF possesses the capacity to selectively generate singlet oxygen (1O2) with a high efficiency, which renders it an efficient photosensitizer for photocatalytic reactions of olefin cleavages and thioanisole photooxidation under red light. The present study demonstrates the intriguing prospect of photoactive COFs with red light absorption as a type II photosensitizer with high potential for utilization in red light photocatalyses.    

    

* Mechanochemical Coupling of Catalysis and Motion in a Cellulose-Degrading Multienzyme Nanomachine  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391578933
:TOPICS: Nanocellulose: Properties, Production, and Applications, Mesoporous Materials, Liquid Crystal Research
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05653")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391578933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391578933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391578933"))][Get cited by]]

OpenAlex: https://openalex.org/W4391578933 (Open access: True)
    
[[https://openalex.org/A5006514846][Krisztina Zajki-Zechmeister]], [[https://openalex.org/A5083353886][Manuel Eibinger]], [[https://openalex.org/A5004942064][Gaurav Singh Kaira]], [[https://openalex.org/A5051203357][Bernd Nidetzky]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05653  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c05653][pdf]])
     
The cellulosome is a megadalton-size protein complex that functions as a biological nanomachine of cellulosic fiber degradation. We show that the cellulosome behaves as a Brownian ratchet that rectifies protein motions on the cellulose surface into a propulsion mechanism by coupling to the hydrolysis of cellulose chains. Movement on cellulose fibrils is unidirectional and results from “macromolecular crawl” composed of dynamic switches between elongated and compact spatial arrangements of enzyme subunits. Deletion of the main exocellulase Cel48S eliminates conformational bias for aligning the subunits to the long fibril axis, which we reveal as crucial for optimum coupling between directional movement and substrate degradation. Implications of the cellulosome acting as a mechanochemical motor suggest a distinct mechanism of enzymatic machinery in the deconstruction of cellulose assemblies.    

    

* Mechanism and Kinetics of Propane and n-Butane Dehydrogenation over Isolated and Nested ≡SiOZn–OH Sites Grafted onto Silanol Nests of Dealuminated Beta Zeolite  :ACS_Catalysis:
:PROPERTIES:
:ID: https://openalex.org/W4391593970
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Zeolite Chemistry and Catalysis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05605")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391593970"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391593970"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391593970"))][Get cited by]]

OpenAlex: https://openalex.org/W4391593970 (Open access: False)
    
[[https://openalex.org/A5054856418][Y. Zhang]], [[https://openalex.org/A5071668095][Liang Qi]], [[https://openalex.org/A5000365597][Danna Nozik]], [[https://openalex.org/A5062045086][Chaochao Dun]], [[https://openalex.org/A5007458786][Jeffrey J. Urban]], [[https://openalex.org/A5087957929][Alexis T. Bell]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05605 
     
No abstract    

    
