#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Sat Nov 23 01:22:52 2024

Found 34 results from 2024-11-16 to 2024-11-23
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Reactive Oxygen Species-Mediated Photooxidation in a Full-Space Electric Field Catalyst: Selectivity and Activity Control of Intramolecular Alcohol Hydroxyl and Aldehyde Groups  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404410867
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Oxidation of Alcohols, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04687")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404410867"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404410867"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404410867"))][Get cited by]]

OpenAlex: https://openalex.org/W4404410867 (Open access: False)
    
[[https://openalex.org/A5103937843][Yi‐Wen Han]], [[https://openalex.org/A5100812994][Yu-Ting Chu]], [[https://openalex.org/A5100328600][Lei Ye]], [[https://openalex.org/A5049677180][Tian‐Jun Gong]], [[https://openalex.org/A5100719200][Yao Fu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04687 
     
No abstract    

    

* Computational Design-Enabled Divergent Modification of Monoterpene Synthases for Terpenoid Hyperproduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404412681
:TOPICS: Biosynthesis and Engineering of Terpenoids, Biological Activities of Triterpenoids and Saponins, Role of Oxidative Stress in Health and Disease
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05863")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404412681"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404412681"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404412681"))][Get cited by]]

OpenAlex: https://openalex.org/W4404412681 (Open access: False)
    
[[https://openalex.org/A5007968908][Liqiu Su]], [[https://openalex.org/A5101887980][Pi Liu]], [[https://openalex.org/A5100687142][Weidong Liu]], [[https://openalex.org/A5100453148][Qi Liu]], [[https://openalex.org/A5072536151][Jian Gao]], [[https://openalex.org/A5109402585][Qiaohua Zhao]], [[https://openalex.org/A5061220842][Kai‐Zhi Jia]], [[https://openalex.org/A5024722452][Xiang Sheng]], [[https://openalex.org/A5023379069][Hongwu Ma]], [[https://openalex.org/A5016303261][Qinhong Wang]], [[https://openalex.org/A5101875311][Zongjie Dai]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05863 
     
No abstract    

    

* Molecular Electrochemical Mediator for Oxidative Multi-Site Proton Coupled Electron Transfer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404412879
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Dioxygen Activation at Metalloenzyme Active Sites, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05832")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404412879"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404412879"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404412879"))][Get cited by]]

OpenAlex: https://openalex.org/W4404412879 (Open access: False)
    
[[https://openalex.org/A5109645791][Tarisha Gupta]], [[https://openalex.org/A5114660219][Yati]], [[https://openalex.org/A5080317177][Sanyam Sanyam]], [[https://openalex.org/A5085923557][Anirban Mondal]], [[https://openalex.org/A5020610169][Biswajit Mondal]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05832 
     
No abstract    

    

* Electrochemical Insights into Hydrogen Peroxide Generation on Carbon Electrodes: Influence of Defects, Oxygen Functional Groups, and Alkali Metals in the Electrolyte  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404412919
:TOPICS: Electrochemical Biosensor Technology, Advances in Chemical Sensor Technologies, Conducting Polymer Research
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04734")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404412919"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404412919"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404412919"))][Get cited by]]

OpenAlex: https://openalex.org/W4404412919 (Open access: True)
    
[[https://openalex.org/A5004899785][André Olean‐Oliveira]], [[https://openalex.org/A5114660237][Najeeb Hasnain]], [[https://openalex.org/A5008862433][Ricardo Martínez‐Hincapié]], [[https://openalex.org/A5074048659][Ulrich Hagemann]], [[https://openalex.org/A5041070012][Adarsh Jain]], [[https://openalex.org/A5062824606][Doris Segets]], [[https://openalex.org/A5034471811][Ioannis Spanos]], [[https://openalex.org/A5026566541][Viktor Čolić]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04734 
     
No abstract    

    

* Low-Temperature Magnetic Field-Assisted Synthesis of Highly Crystalline Fe(OH)x and Its Directed Carrier Transfer Effect under Optical-Magnetic Fields  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404413495
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04283")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404413495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404413495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404413495"))][Get cited by]]

OpenAlex: https://openalex.org/W4404413495 (Open access: False)
    
[[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5103069210][Yuan Dong]], [[https://openalex.org/A5020554421][Jie Ying]], [[https://openalex.org/A5101872143][Yuan Feng]], [[https://openalex.org/A5007458023][Ziheng Zhu]], [[https://openalex.org/A5009260936][Yuxuan Xiao]], [[https://openalex.org/A5060387948][Ge Tian]], [[https://openalex.org/A5043084585][Ling Shen]], [[https://openalex.org/A5100379837][Wei Geng]], [[https://openalex.org/A5034132713][Yi Lu]], [[https://openalex.org/A5102697287][Si‐Ming Wu]], [[https://openalex.org/A5100435418][Xiaoyu Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04283 
     
No abstract    

    

* Manganese-Catalyzed Asymmetric Hydrogenation for Atroposelective Dynamic Kinetic Resolution of Heterobiaryl Ketone N-Oxides  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404414560
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Chiroptical Spectroscopy in Organic Compound Analysis, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04979")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404414560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404414560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404414560"))][Get cited by]]

OpenAlex: https://openalex.org/W4404414560 (Open access: False)
    
[[https://openalex.org/A5022529324][Yin-Bo Wan]], [[https://openalex.org/A5084501389][Xiang‐Ping Hu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04979 
     
No abstract    

    

* Dual N-Heterocyclic Carbene/Photoredox-Catalyzed Coupling of Acyl Fluorides and Alkyl Silanes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404416146
:TOPICS: N-Heterocyclic Carbenes in Catalysis and Materials Chemistry, Transition Metal-Catalyzed Cross-Coupling Reactions, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03103")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404416146"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404416146"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404416146"))][Get cited by]]

OpenAlex: https://openalex.org/W4404416146 (Open access: True)
    
[[https://openalex.org/A5022647501][Michael Jakob]], [[https://openalex.org/A5062763572][Luca Steiner]], [[https://openalex.org/A5114661390][Marius Göbel]], [[https://openalex.org/A5039249176][Jan P. Götze]], [[https://openalex.org/A5022829750][Matthew N. Hopkinson]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03103 
     
No abstract    

    

* Enhanced Photocatalytic Production of Hydrogen Peroxide by Covalent Triazine Frameworks with Stepwise Electron Transfer  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404417009
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Photocatalytic Materials for Solar Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05328")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404417009"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404417009"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404417009"))][Get cited by]]

OpenAlex: https://openalex.org/W4404417009 (Open access: False)
    
[[https://openalex.org/A5100397032][Hao Zhang]], [[https://openalex.org/A5034045320][Wenxin Wei]], [[https://openalex.org/A5017919922][Kai Chi]], [[https://openalex.org/A5088200752][Yong Zheng]], [[https://openalex.org/A5005904436][Xin Ying Kong]], [[https://openalex.org/A5009243555][Liqun Ye]], [[https://openalex.org/A5100758533][Yan Zhao]], [[https://openalex.org/A5079019316][Kai A. I. Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05328 
     
No abstract    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404418735
:TOPICS: 
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i022_1868022")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404418735"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404418735"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404418735"))][Get cited by]]

OpenAlex: https://openalex.org/W4404418735 (Open access: False)
    
, ACS Catalysis. 14(22)] 2024. https://doi.org/10.1021/csv014i022_1868022 
     
No abstract    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404419249
:TOPICS: 
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i022_1868023")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404419249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404419249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404419249"))][Get cited by]]

OpenAlex: https://openalex.org/W4404419249 (Open access: False)
    
, ACS Catalysis. 14(22)] 2024. https://doi.org/10.1021/csv014i022_1868023 
     
No abstract    

    

* Generating Cationic Nickel Clusters over Oxygen-Functionalized Boron Nitride to Boost Methane Dry Reforming  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404420889
:TOPICS: Catalytic Nanomaterials, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-11-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05957")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404420889"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404420889"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404420889"))][Get cited by]]

OpenAlex: https://openalex.org/W4404420889 (Open access: False)
    
[[https://openalex.org/A5100568670][Fan Jie]], [[https://openalex.org/A5053312733][Wen‐Cui Li]], [[https://openalex.org/A5101865587][Lei He]], [[https://openalex.org/A5011306017][Bowen He]], [[https://openalex.org/A5063218196][Fan Tang]], [[https://openalex.org/A5011424663][Zhankai Liu]], [[https://openalex.org/A5086386273][Dongqi Wang]], [[https://openalex.org/A5100450813][Xi Liu]], [[https://openalex.org/A5102401820][Liwei Chen]], [[https://openalex.org/A5012152061][An‐Hui Lu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05957 
     
No abstract    

    

* Thermochemical Correlations of Redox and Brønsted Sites on Bifunctional Polyoxometalate Clusters and Their Kinetic Consequences in Methanol-O2 Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404436420
:TOPICS: Polyoxometalate Clusters and Materials, Chemistry and Applications of Metal-Organic Frameworks, Innovations in Organic Synthesis Reactions
:PUBLICATION_DATE: 2024-11-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04745")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404436420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404436420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404436420"))][Get cited by]]

OpenAlex: https://openalex.org/W4404436420 (Open access: False)
    
[[https://openalex.org/A5067244216][Guangming Cai]], [[https://openalex.org/A5039229575][Ya-Huei Cathy Chin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04745 
     
No abstract    

    

* Bacterial Biosynthesis of Nitrile-Containing Natural Products: Basis for Recognition of Diversified Substrates  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404449383
:TOPICS: Natural Products as Sources of New Drugs, Marine Microbial Diversity and Biogeography, Metabolic Engineering and Synthetic Biology
:PUBLICATION_DATE: 2024-11-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06581")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404449383"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404449383"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404449383"))][Get cited by]]

OpenAlex: https://openalex.org/W4404449383 (Open access: False)
    
[[https://openalex.org/A5101691865][Ming Peng]], [[https://openalex.org/A5014980152][Qiaoling Wu]], [[https://openalex.org/A5100578533][Lele Ma]], [[https://openalex.org/A5082988741][Zhao‐Jie Teng]], [[https://openalex.org/A5038166418][Xuben Hou]], [[https://openalex.org/A5077847368][Hongjie Zhu]], [[https://openalex.org/A5028227890][Jianhua Ju]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06581 
     
No abstract    

    

* Activation of Lattice Oxygen in Nitrogen-Doped High-Entropy Oxide Nanosheets for Highly Efficient Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404459898
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Advanced Materials for Smart Windows
:PUBLICATION_DATE: 2024-11-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05997")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404459898"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404459898"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404459898"))][Get cited by]]

OpenAlex: https://openalex.org/W4404459898 (Open access: False)
    
[[https://openalex.org/A5009729201][Shengqin Guan]], [[https://openalex.org/A5100711147][Baoen Xu]], [[https://openalex.org/A5109737361][Xingbo Yu]], [[https://openalex.org/A5044016858][Yong‐Hong Ye]], [[https://openalex.org/A5100364308][Yuting Liu]], [[https://openalex.org/A5048224087][Taotao Guan]], [[https://openalex.org/A5100703660][Yang Yu]], [[https://openalex.org/A5051728653][Jiali Gao]], [[https://openalex.org/A5080856996][Kaixi Li]], [[https://openalex.org/A5100666573][Jianlong Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05997 
     
No abstract    

    

* In(OTf)3-Catalyzed (3 + 3) Dipolar Cyclization of Bicyclo[1.1.0]butanes with N-Nucleophilic 1,3-Dipoles: Access to 2,3-Diazabicyclo[3.1.1]heptanes, 2,3-Diazabicyclo[3.1.1]heptenes, and Enantiopure 2-Azabicyclo[3.1.1]heptanes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404474976
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Catalytic Carbene Chemistry in Organic Synthesis, Asymmetric Catalysis
:PUBLICATION_DATE: 2024-11-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05622")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404474976"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404474976"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404474976"))][Get cited by]]

OpenAlex: https://openalex.org/W4404474976 (Open access: False)
    
[[https://openalex.org/A5100410113][Jian Zhang]], [[https://openalex.org/A5013440240][Jia-Yi Su]], [[https://openalex.org/A5019926319][Hanliang Zheng]], [[https://openalex.org/A5033255955][Hao Li]], [[https://openalex.org/A5052528253][Wei‐Ping Deng]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05622 
     
The investigation into the synthesis of azabicyclo[3.1.1]heptanes (azaBCHeps) as bioisosteres to flat aza-aromatics has garnered increasing attention, while it encounters significant challenges. Herein, we have demonstrated the In(OTf)3-catalyzed (3 + 3) dipolar cyclization of bicyclo[1.1.0]butanes (BCBs) with hydrazones and π-allyl-iridium 1,3-dipoles, engendering a diverse array of azaBCHeps. The cyclization of hydrazones and BCBs furnished densely substituted 2,3-diazabicyclo[3.1.1]heptanes and 2,3-diazabicyclo[3.1.1]heptenes under nitrogen and oxygen atmospheres, respectively. A combination of experimental and computational investigations lends robust support for the proton-transfer-interposed sequential mechanism. More importantly, by integrating In(OTf)3/iridium relay catalysis, enantiopure 2-azabicyclo[3.1.1]heptanes were constructed through the (3 + 3) cyclization of BCBs with aza-π-allyl-iridium 1,3-dipoles, in situ generated from N-allyl carbonates. Both methodologies exhibit mild reaction conditions and good tolerance for various functional groups. Moreover, the copious derivatization of products highlights the utility of the newly synthesized heterobicyclic motifs as versatile building blocks in synthetic chemistry.    

    

* Efficient Dehydrogenation of Propane to Propene over PtIn Nanoclusters Encapsulated in Hollow-Structured Silicalite-1  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404483179
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Zeolite Chemistry and Catalysis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-11-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05135")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404483179"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404483179"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404483179"))][Get cited by]]

OpenAlex: https://openalex.org/W4404483179 (Open access: False)
    
[[https://openalex.org/A5100680487][Shiying Li]], [[https://openalex.org/A5100368347][Decheng Li]], [[https://openalex.org/A5104245933][Baichao Li]], [[https://openalex.org/A5100373751][Xiao Chen]], [[https://openalex.org/A5015965034][Hongbin Wu]], [[https://openalex.org/A5100350748][Sen Wang]], [[https://openalex.org/A5002713112][Mei Dong]], [[https://openalex.org/A5100336336][Jianguo Wang]], [[https://openalex.org/A5079821348][Weibin Fan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05135 
     
Pt-based catalysts have been widely used for propane dehydrogenation to propene. However, the high reaction temperature generally induces serious sintering and agglomeration of metal species, thus leading to rapid deactivation of the catalysts. Herein, PtIn nanoclusters (NCs) encapsulated in hollow-structured silicalite-1 (designated as PtIn@S1–H) was prepared using recrystallization method. This material shows high catalytic performance in propane dehydrogenation. The propane conversion and propene selectivity reach ∼45–47.5% and ∼99%, respectively, at 547 °C at least within 167.6 h. As a result, it displays a significantly higher specific activity for C3H6 formation (0.37–0.59 s–1) than Pt@S1, Pt@S1–H, and other reported Pt-based catalysts. Notably, its catalytic performance is well maintained for more than 3600 h, with propane conversion of ∼31–34% and propene selectivity of ∼91–95%, when pure propane is fed. More interestingly, this catalyst can be reused through regeneration. EXAFS, HAADF-STEM and DFT calculation, and AIMD simulation results show that hollow-structured silicalite-1 crystal morphology not only facilitates the formation of Pt5In3 alloy NCs but also inhibits NC aggregation and growth. PtIn@S1–H showed a TON ≥ 38996 in contrast to 5367, 4928, 798, and 542 obtained on PtIn@S1, PtSn@S1, PtSn/Al2O3, and PtIn/Al2O3, respectively, if the catalysts were considered to be deactivated when the propane conversion was decreased by 15%. This is because alloying of In into Pt NCs weakens the interaction of C3H7* intermediates with metallic Pt NCs and the adsorption of C3H6 on the catalyst surface, thus suppressing the C3H7* cleavage reaction and enhancing propane activation and propene selectivity.    

    

* Iridium Photoredox-Catalyzed Stereoselective C-Glycosylation with Tetrafluoropyridin-4-yl Thioglycosides: A Facile Synthesis of C-α/β-Glucogallins and Their Antioxidant Activity  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404486254
:TOPICS: Chemical Glycobiology and Therapeutic Applications, Chromones and Flavonoids in Medicinal Chemistry, Click Chemistry in Chemical Biology and Drug Development
:PUBLICATION_DATE: 2024-11-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05257")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404486254"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404486254"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404486254"))][Get cited by]]

OpenAlex: https://openalex.org/W4404486254 (Open access: False)
    
[[https://openalex.org/A5101953091][Shenghao Li]], [[https://openalex.org/A5100617197][Han Ding]], [[https://openalex.org/A5007536117][Ruge Cao]], [[https://openalex.org/A5031867459][Xiao-Lin Zhang]], [[https://openalex.org/A5049507373][Jingxin Li]], [[https://openalex.org/A5026078987][Xingchun Sun]], [[https://openalex.org/A5008273613][Yaying Li]], [[https://openalex.org/A5075894101][Kan Zhong]], [[https://openalex.org/A5100396159][Peng Wang]], [[https://openalex.org/A5077907557][Chao Cai]], [[https://openalex.org/A5050152196][Hongzhi Cao]], [[https://openalex.org/A5101574923][Ming Li]], [[https://openalex.org/A5100662239][Xue‐Wei Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05257 
     
We demonstrate an efficient, scalable, and stereoselective C-glycosylation with thioglycosides possessing a unique photoactive tetrafluoropyridin-4-yl (TFPy) thio radical leaving group, affording editable and medicinally and biologically essential C-α-glucogallin derivatives. In the presence of silyl enol ether acceptors, the desulfurative coupling reaction performs smoothly under mild conditions upon exposure to blue light irradiation. This versatile protocol permits the synthesis of sugar-drug chimeras by C1 ketonylation of complex drug-derived silyl enol ethers. The scale-up synthesis, anomeric epimerization, and post-C-glycosylation modification of ketone sugars showcase the reaction's potential utilities. Furthermore, the reaction could be applied to direct carbohydrate skeleton editing by equipping the leaving group on the nonanomeric position. The ketonylation is viable for unprotected TFPy thioglycoside, affording a direct route to unprotected ketonyl sugars. The concise six-step assembly of both configurated C-glucogallins from commercially cheap glucose pentaacetate and their antioxidant reactivity investigations underline the promising medicinal relevance of our current protocols. The reaction mechanism was investigated through a radical trapping experiment, an oxocarbenium trapping experiment, a fluorescence quenching experiment, and Stern–Volmer analysis, confirming that the major glycosyl radical intermediates are generated from the thioglycoside donors, whose tetrafluoropyridin-4-yl thio group could effectively quench the fluorescence of excited Ir(ppy)3 through an oxidative quenching process, and C-glycosylation with oxocarbenium is a complementary route to the product, accounting for examples with moderate selectivities.    

    

* Asymmetric Associate Configuration of Nb Single Atoms Coupled Bi–O Vacancy Pairs Boosting CO2 Photoreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404486667
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-11-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04407")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404486667"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404486667"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404486667"))][Get cited by]]

OpenAlex: https://openalex.org/W4404486667 (Open access: False)
    
[[https://openalex.org/A5058123550][Jun Di]], [[https://openalex.org/A5074479934][Yao Wu]], [[https://openalex.org/A5087508399][Jun Xiong]], [[https://openalex.org/A5063417159][Hongwei Shou]], [[https://openalex.org/A5026399204][Ran Long]], [[https://openalex.org/A5100603637][Hailong Chen]], [[https://openalex.org/A5047600031][Peng Zhou]], [[https://openalex.org/A5100364064][Peng Zhang]], [[https://openalex.org/A5025050242][Xingzhong Cao]], [[https://openalex.org/A5100448217][Li Song]], [[https://openalex.org/A5009452553][Wei Jiang]], [[https://openalex.org/A5100423704][Zheng Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04407 
     
Precisely designing the atomic coordination structure of the catalytic center is highly desired to lower the energy barrier of CO2 photoreduction. The present work shows that engineering Nb single atom coupled Bi–O vacancy pairs (VBi–O) into Bi24O31Br10 (BOB) atomic layers can create a preferential local asymmetric structure. This configuration can result in a stronger local polarization electric field and thus prolong the carrier lifetime, as proved by ultrafast transient absorption spectroscopy. Meantime, this unique Nb SA-VBi–O associate favors the formation of strong chemical interaction between key *COOH intermediate and catalytic center, thus lowering the energy barrier of the rate-limiting step. Benefiting from these features, a high CO generation rate of 76.4 μmol g–1 h–1 for CO2 photoreduction can be achieved over Nb SA-VBi–O BOB atomic layers in pure water, roughly 5.4 and 92.7 times higher than those of BOB atomic layers or bulk BOB, respectively. This work discloses an important paradigm for designing single atom coupled defect associates to optimize photocatalysis performance.    

    

* Unraveling the Key Factors on Structure–Property–Activity Correlations for Photocatalytic Hydrogen Production of Covalent Organic Frameworks  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404488626
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Photocatalytic Materials for Solar Energy Conversion, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-11-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04968")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404488626"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404488626"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404488626"))][Get cited by]]

OpenAlex: https://openalex.org/W4404488626 (Open access: False)
    
[[https://openalex.org/A5054538596][Pengyu Dong]], [[https://openalex.org/A5067455936][Cunxia Wang]], [[https://openalex.org/A5101742243][Shouxin Zhang]], [[https://openalex.org/A5066955841][Jinkang Pan]], [[https://openalex.org/A5101684491][Boyuan Zhang]], [[https://openalex.org/A5100602288][Jinlong Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04968 
     
It has been a challenging task to clearly elucidate various structural features and how their interactions affect the photocatalytic hydrogen production performance. In this work, various factors, including crystallinity, specific surface area associated with morphology, energy band gap and energy levels, surface charge, and hydrophilicity, were employed to investigate the structure–property–activity correlations of β-ketoenamine-linked covalent organic framework (TpPa-1-COF) for photocatalytic H2 production, which could influence the light harvesting, charge separation and transfer, and surface catalytic active sites. By using different methods to prepare TpPa-1-COFs, we can regulate these influencing factors to investigate their relationship with activity. It is found that the TpPa-1-COF prepared by a molecular organization method (labeled as TpPa-1 (MO)) exhibits the highest photocatalytic H2 evolution activity compared with the TpPa-1-COF samples prepared by solvothermal methods using acetic acid (HOAc) as a catalyst (TpPa-1 (ST-HOAc)) and KOH solution as a catalyst (TpPa-1 (ST-KOH)), which is associated with the highest crystallinity, the optimal energy levels, the largest BET-specific surface area, and the best hydrophilicity for TpPa-1 (MO). Moreover, our findings suggest that the enhanced total photocatalytic H2 evolution efficiency (ηtotal) of TpPa-1 (MO) may be mainly attributed to the efficient separation and migration of photogenerated charges (η2) and the vibrant surface catalytic active sites (η3). Overall, this work provides some deep insights into the structure–property–activity relation of TpPa-1-COF photocatalysts, which offers valuable inspiration and guidance for the thoughtful design of COF-based photocatalysts for H2 evolution.    

    

* Expanding the Reaction Network of Ethylene Epoxidation on Partially Oxidized Silver Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404513109
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04521")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404513109"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404513109"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404513109"))][Get cited by]]

OpenAlex: https://openalex.org/W4404513109 (Open access: False)
    
[[https://openalex.org/A5008667355][Adhika Setiawan]], [[https://openalex.org/A5079636509][Tiancheng Pu]], [[https://openalex.org/A5066491588][Israel E. Wachs]], [[https://openalex.org/A5070042353][Srinivas Rangarajan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04521 
     
No abstract    

    

* Construction of a Pore-Confined Catalyst in a Vinylene-Linked Covalent Organic Framework for the Oxygen Reduction Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404519758
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05827")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404519758"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404519758"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404519758"))][Get cited by]]

OpenAlex: https://openalex.org/W4404519758 (Open access: False)
    
[[https://openalex.org/A5100441266][Xuewen Li]], [[https://openalex.org/A5100784279][Shuai Yang]], [[https://openalex.org/A5032456464][Xiubei Yang]], [[https://openalex.org/A5108312160][Shuang Zheng]], [[https://openalex.org/A5069765087][Qing Xu]], [[https://openalex.org/A5028394871][Gaofeng Zeng]], [[https://openalex.org/A5038741162][Zheng Jiang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05827 
     
Two-dimensional metal-containing covalent organic frameworks (COFs) have been employed as electrocatalysts. However, the metal sites were stacked within the layers with strong interactions, which hindered mass transport to them in the catalytic process. Herein, we constructed a pore-confined catalyst in a vinylene-linked COF for the oxygen reduction reaction (ORR) via the Katritzky reaction. By anchoring the catalytic sites along the pore walls with covalent bonds, the catalytic units were well-exposed during the catalytic process and retained crystallinity and porosity, facilitating mass access to the metal sites. In addition, the electron/charge transported from the framework to the metal units modulated the electronic states, thus improving the catalytic activity. The catalytic COF exhibited a half-wave potential of 0.85 V and a mass activity of 109.7 A g–1, which are better than those of other reported COFs. Theoretical calculations revealed that the interaction between the framework and metal sites contributed to the easy formation of OOH* and OH*, resulting in high activity. This work provides insights into designing catalytic COFs based on C═C linkages.    

    

* Correlated Operando Electron Microscopy and Photoemission Spectroscopy in Partial Oxidation of Ethylene over Nickel  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404522986
:TOPICS: Surface Analysis and Electron Spectroscopy Techniques, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04437")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404522986"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404522986"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404522986"))][Get cited by]]

OpenAlex: https://openalex.org/W4404522986 (Open access: True)
    
[[https://openalex.org/A5055099002][Claudiu Colbea]], [[https://openalex.org/A5064864784][Milivoj Plodinec]], [[https://openalex.org/A5103539982][Man Guo]], [[https://openalex.org/A5014379900][Luca Artiglia]], [[https://openalex.org/A5054120563][Jeroen A. van Bokhoven]], [[https://openalex.org/A5055099002][Claudiu Colbea]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04437 
     
The production of syngas from light hydrocarbons is a viable way of converting under-utilized hydrocarbon sources into valuable products until a full transition to renewable energy sources is achieved. However, current heterogeneous catalysts for syngas production suffer from deactivation, either by coking or oxidation. Here, we report on the behavior of model nickel catalysts within the context of ethylene partial oxidation and observe the catalyst-environment interaction as a function of reactant feed and temperature. Using a combination of operando microscopy and spectroscopy and focusing on a reaction regime characterized by synchronized self-sustained oscillatory dynamics, we are able to gain additional insights into the dynamic interplay between reactive species and active catalyst surfaces of varying reactivity. Real-time secondary electron imaging coupled with online mass spectrometry and thermal data shows that the oscillatory behavior is characterized by a highly active half-period during which the surface of the nickel catalyst is metallic and a less active half-period during which the surface is oxidized. Complementing the direct surface imaging, operando X-ray photoelectron spectroscopy provides missing information about the alternating chemical state of the catalyst surface in the oscillating reaction regime. It reveals that changes in the gas phase composition (C2H4/O2 ratio) alter the population of reaction intermediates (e.g., carbides) on the nickel surface, which in turn drives the selectivity of the reaction toward different products. The observed chemical dynamics involve changes in gas-phase composition, rate-dependent heat of reaction, the chemical state of the catalyst, and the formation of reaction products, all of which are interconnected. Ultimately, the complex oscillations and catalytic behavior are attributed to a multistep mechanism that involves complete ethylene oxidation, dry and wet reforming of ethylene, and the reverse water gas shift reaction.    

    

* Promoted Electrochemical Ammonia Synthesis from Nitrate at the Ag–Cu Biphasic Interface  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404522993
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05465")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404522993"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404522993"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404522993"))][Get cited by]]

OpenAlex: https://openalex.org/W4404522993 (Open access: False)
    
[[https://openalex.org/A5020951968][Xinyang Gao]], [[https://openalex.org/A5037587672][Chenyuan Zhu]], [[https://openalex.org/A5035847622][Chunlei Yang]], [[https://openalex.org/A5064269604][Guoshuai Shi]], [[https://openalex.org/A5031317695][Qinshang Xu]], [[https://openalex.org/A5100461464][Liming Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05465 
     
Electrochemical nitrate reduction (NO3–R) presents a promising pathway for carbon-neutral ammonia (NH3) synthesis. Enhancing NH3 selectivity through a tandem process can be achieved by combining Cu with a secondary metal, which allows for an adjustable binding energy between the bimetallic catalyst and key nitrogen intermediates. Herein, we developed a biphasic Ag–Cu heterostructure with a controllable elemental composition, which significantly improved NH3 production through tandem NO3–R. In-situ infrared spectroscopy and finite element simulations revealed that Ag serves as the active site for converting NO3– to NO2–, leading to a high localized concentration of NO2–, which is subsequently reduced to NH3 on adjacent Cu sites. Density functional theory calculations further confirmed the critical role of the Ag–Cu biphasic interface in promoting tandem NH3 production. This work offers valuable insights into the tandem NO3–R pathway in bimetallic heterostructures, providing a foundation for optimizing catalysts and advancing large-scale sustainable NH3 synthesis.    

    

* Correction to “Functional Nucleic Acid Enzymes: Nucleic Acid-Based Catalytic Factories”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404523123
:TOPICS: DNA Nanotechnology and Bioanalytical Applications, G-Quadruplex DNA Structures and Functions, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-11-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06741")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404523123"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404523123"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404523123"))][Get cited by]]

OpenAlex: https://openalex.org/W4404523123 (Open access: False)
    
[[https://openalex.org/A5090654075][Min Yang]], [[https://openalex.org/A5112950523][Yushi Xie]], [[https://openalex.org/A5109354509][Longjiao Zhu]], [[https://openalex.org/A5100341794][Xiangyang Li]], [[https://openalex.org/A5049623429][Wentao Xu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06741 
     
InfoMetricsFiguresRef. ACS CatalysisASAPArticle This publication is free to access through this site. Learn More CiteCitationCitation and abstractCitation and referencesMore citation options ShareShare onFacebookX (Twitter)WeChatLinkedInRedditEmailJump toExpandCollapse ORIGINAL ARTICLE. This notice is a correction.Addition/CorrectionNovember 19, 2024Correction to "Functional Nucleic Acid Enzymes: Nucleic Acid-Based Catalytic Factories"Click to copy article linkArticle link copied!Min YangMin YangMore by Min YangYushi XieYushi XieMore by Yushi XieLongjiao ZhuLongjiao ZhuMore by Longjiao ZhuXiangyang LiXiangyang LiMore by Xiangyang LiWentao Xu*Wentao XuMore by Wentao Xuhttps://orcid.org/0000-0002-8572-8257Open PDFACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 17879Click to copy citationCitation copied!https://pubs.acs.org/doi/10.1021/acscatal.4c06741https://doi.org/10.1021/acscatal.4c06741Published November 19, 2024 Publication History Received 5 November 2024Published online 19 November 2024correction© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsThis publication is licensed for personal use by The American Chemical Society. ACS Publications© 2024 American Chemical SocietyThe caption for Figure 2 should read as follows:Figure 2. Classifications and applications of FNAzymes.P 16394, the last sentence of the first paragraph of section 2 should read as follows:In general, catalytic functions of ribozymes could be divided into these categories: cleaving, splicing, ligation, polymerization and others.Author InformationClick to copy section linkSection link copied!Corresponding AuthorWentao Xu; https://orcid.org/0000-0002-8572-8257; Email: AuthorsMin YangYushi XieLongjiao ZhuXiangyang LiCited By Click to copy section linkSection link copied!This article has not yet been cited by other publications.Download PDFFiguresReferences Get e-AlertsGet e-AlertsACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 17879Click to copy citationCitation copied!https://doi.org/10.1021/acscatal.4c06741Published November 19, 2024 Publication History Received 5 November 2024Published online 19 November 2024© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsArticle Views-Altmetric-Citations-Learn about these metrics closeArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated.Recommended Articles FiguresReferencesThis publication has no figures.This publication has no References.    

    

* Geometrically Constrained Cofacial Bi-Titanium Olefin Polymerization Catalysts: Tuning and Enhancing Comonomer Incorporation Density  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404531727
:TOPICS: Transition Metal Catalysis, Carbon Dioxide Utilization for Chemical Synthesis, Olefin Metathesis Chemistry
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05888")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404531727"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404531727"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404531727"))][Get cited by]]

OpenAlex: https://openalex.org/W4404531727 (Open access: False)
    
[[https://openalex.org/A5010992519][Junhui Bao]], [[https://openalex.org/A5101743373][Yufang Li]], [[https://openalex.org/A5030730368][Chun‐Ming Chan]], [[https://openalex.org/A5046687235][Kwok-Chung Law]], [[https://openalex.org/A5012005897][Shek‐Man Yiu]], [[https://openalex.org/A5027075522][Michael C. W. Chan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05888 
     
A series of shape-persistent bis-[C(sp3)-chelating] Ti2 (plus Zr2 and Hf2) complexes with a rigid linker component (xanthene or dibenzofuran) are presented. These structurally diverse assemblies display limited yet different conformational flexibility, and crucially, such geometric constraints confer access to a range of intermetallic separations and orientations to potentially enhance catalytic activity and cooperative effects. For ethylene polymerizations, the Ti2 catalysts (in conjunction with trityl borate) exhibit greater efficiencies and produced polymers with higher Mw than mononuclear controls, which is significant considering the more crowded environment for cofacial bimetallic sites. Proficient 1-hexene incorporations were observed for ethylene-(α-olefin) copolymerization reactions. The F-substituted m-aryl/dibenzofuran-linked catalyst (5), which is revealed by NMR analysis to be conformationally dissimilar to its F-absent congener, produced copolymers with higher Mw and elevated 1-hexene incorporation levels (up to 44%), when compared with its mono-Ti control (19%). These results suggest that catalyst frameworks with suitably adjustable conformations and Ti···Ti distances can facilitate bimetallic enchainment interactions with α-olefin substrates and their insertion.    

    

* Exploring the Mechanism of Biomimetic Arene Hydroxylation: When a Diiron Metal Center Meets a Sulfur-Containing Ligand  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404539817
:TOPICS: Dioxygen Activation at Metalloenzyme Active Sites, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04662")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404539817"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404539817"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404539817"))][Get cited by]]

OpenAlex: https://openalex.org/W4404539817 (Open access: False)
    
[[https://openalex.org/A5100673010][Yu Sheng]], [[https://openalex.org/A5037117630][Bo Bi]], [[https://openalex.org/A5041968492][Lu Cheng]], [[https://openalex.org/A5100757735][Wei Han]], [[https://openalex.org/A5100334211][Hui Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04662 
     
No abstract    

    

* Ancestral Sequence Reconstruction Meets Machine Learning: Ene Reductase Thermostabilization Yields Enzymes with Improved Reactivity Profiles  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404541678
:TOPICS: Enzyme Immobilization Techniques, Advances in Metabolomics Research, Macromolecular Crystallography Techniques
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03738")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404541678"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404541678"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404541678"))][Get cited by]]

OpenAlex: https://openalex.org/W4404541678 (Open access: False)
    
[[https://openalex.org/A5081482981][Caroline K. Brennan]], [[https://openalex.org/A5011950010][Jovan Livada]], [[https://openalex.org/A5082363308][Carlos Alberto Martínez]], [[https://openalex.org/A5051704741][Russell D. Lewis]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03738 
     
No abstract    

    

* Catalytic Combustion of Methane over Noble Metal Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404551760
:TOPICS: Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05650")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404551760"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404551760"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404551760"))][Get cited by]]

OpenAlex: https://openalex.org/W4404551760 (Open access: False)
    
[[https://openalex.org/A5045460215][Huimei Duan]], [[https://openalex.org/A5101448533][Fanxin Kong]], [[https://openalex.org/A5002542603][Xinze Bi]], [[https://openalex.org/A5100333579][Lei Chen]], [[https://openalex.org/A5013084576][Hangrong Chen]], [[https://openalex.org/A5101567103][Dongjiang Yang]], [[https://openalex.org/A5100639761][Weixin Huang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05650 
     
As one of the cleanest fossil fuel resources, methane is also the second largest greenhouse gas after CO2 owing to its strong greenhouse effect. The direct emission of large quantities of trace and unburned methane causes a serious energy loss and greenhouse effect. Catalytic methane combustion is a promising strategy in eliminating methane slip to address the urgent environmental issue. However, the current methane abatement catalysts still face great challenges in thermal stability, water resistance, and sulfur tolerance. In this review, we focus on the popular noble metal-based catalysts, discuss the distinct reaction mechanisms including the Langmuir–Hinshelwood model, Eley–Rideal model, Mars–van Krevelen model, and two-term mechanisms. The deactivation mechanisms induced by sintering, sulfur, and water on popular Pd-based catalysts are then analyzed. Then, we outline the promotion strategies from two aspects, i.e., construction of a core–shell structure and electronic engineering of the active phase to improve thermal stability and poisoning resistance. Finally, a summary and prospects with an emphasis on the newly developed oxide-metal interfaces and photothermal catalysis for highly efficient methane combustion are addressed.    

    

* Photoelectrochemical Synthesis of Benzo[b]phosphole Oxides via Sequential P–H/C–H Bond Functionalizations  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404563322
:TOPICS: Applications of Photoredox Catalysis in Organic Synthesis, Transition-Metal-Catalyzed Sulfur Chemistry, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06292")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404563322"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404563322"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404563322"))][Get cited by]]

OpenAlex: https://openalex.org/W4404563322 (Open access: True)
    
[[https://openalex.org/A5007654596][N. K. SAHA]], [[https://openalex.org/A5067475475][Burkhard Koenig]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06292 
     
Benzo[b]phosphole oxides are important P-heterocycles that find applications in optoelectronics due to their inherent photophysical properties. Traditional routes for the synthesis of such molecules from readily available precursors require stoichiometric amounts of transition metal salts, bases, oxidants, and additives, thereby lacking efficiency. Photochemical pathways still need a terminal oxidant to complement the photocatalytic cycle, whereas electricity may be a viable oxidant. Hence, photoelectrochemistry (PEC), combining photocatalysis and synthetic organic electrochemistry, was used to simplify the synthetic protocols. We use the potency of 4CzIPN for the consecutive P–H/C–H bond functionalizations for preparing benzo[b]phosphole oxides from secondary phosphine oxides and nonactivated internal alkynes with up to 93% yields and with good functional group tolerance. Detailed mechanistic investigations confirm an intermolecular electron transfer between 4CzIPN and aryl secondary phosphine oxides upon photoexcitation. The photocatalyst is regenerated by anodic oxidation.    

    

* Organocatalytic Asymmetric Electrophilic Amination of Allylic Boronates  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404563337
:TOPICS: Frustrated Lewis Pairs Chemistry, Asymmetric Catalysis, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05237")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404563337"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404563337"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404563337"))][Get cited by]]

OpenAlex: https://openalex.org/W4404563337 (Open access: False)
    
[[https://openalex.org/A5077730496][Giovanni Centonze]], [[https://openalex.org/A5114728219][Arianna Grandi]], [[https://openalex.org/A5076223736][Andrea Pellegrini]], [[https://openalex.org/A5085857744][Paolo Righi]], [[https://openalex.org/A5049944494][Chiara Portolani]], [[https://openalex.org/A5076128769][Giorgio Bencivenni]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05237 
     
The asymmetric addition of allylic boronates to electrophiles is a powerful method for preparing chiral molecules bearing synthetically valuable allylic moieties. While effective catalytic methods exist, they have so far been limited to the enantioselective allyl- and crotyl-boration of carbonyl compounds and imines, thereby forming C–C bonds. Here, we present a strategy that expands the scope of this catalytic asymmetric platform to include the stereoselective formation of C–N bonds. We have identified an inexpensive and readily available chiral diol that catalyzes the addition of allylic boronates to azodicarboxylates, affording chiral allylic hydrazides with high stereocontrol. This electrophilic amination chemistry shows a broad substrate scope and requires mild conditions, proceeding at ambient temperature. Mechanistic studies reveal that the chiral diol catalyst facilitates the formation of a chiral allylic boronate through the reversible exchange of the boron's achiral alkoxy ligand. By coordination with the electrophilic azodicarboxylate, the substrates mutually activate each other, allowing for the stereoselective transfer of the allyl group.    

    

* SiOx Interfacial Engineering of UV/Ozone Oxidation for an Efficient Water-Reduction Metal–Insulator–Semiconductor Silicon Photocathode  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404563346
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05792")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404563346"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404563346"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404563346"))][Get cited by]]

OpenAlex: https://openalex.org/W4404563346 (Open access: False)
    
[[https://openalex.org/A5028227271][Chenxiao Jiang]], [[https://openalex.org/A5057937956][Siqin Zhou]], [[https://openalex.org/A5076856796][Jinlu Han]], [[https://openalex.org/A5031860089][Guancai Xie]], [[https://openalex.org/A5033246962][Jian Gong]], [[https://openalex.org/A5042664703][Juan Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05792 
     
A metal–insulator–semiconductor (MIS) structure is an attractive interfacial structure for efficient photoelectrochemical (PEC) water-splitting reactions. However, developing a cost-effective and highly active photoelectrode for the PEC water-splitting reaction is still a major challenge. In this study, we use an easy-to-operate and economical UV/ozone (UV/O3) oxidation process to prepare ultrathin SiOx oxide as an insulating layer, which is integrated with the bilayer non-precious-metal collector Al/Ni serving as the catalyst and the p-Si semiconductor to obtain a cost-effective and efficient MIS structure photocathode. The outcomes demonstrate that the ultrathin SiOx insulation layer significantly improves the PEC hydrogen evolution reaction (HER), through comparing the photovoltage and photocurrent density of the MIS system. The inner metal Al in the bilayer collector Al/Ni regulates the degree of band bending at the semiconductor–metal interface. Additionally, the presence of the ultrathin Al2O3 insulation layer effectively reduces Fermi-level pinning, which promotes the efficient transfer of photoelectrons to electrolytes. These were confirmed through photoelectric performance testing of the MIS system. The generation of a photocurrent of 15 mA cm–2 at a potential level of 0 V (vs reversible hydrogen electrode) has been obtained by optimizing the thickness of the SiOx and bilayer non-precious-metal collector. This study presents an economical and efficient strategy for enhancing PEC-HER performance in silicon-based photocathodes using an MIS structure.    

    

* {TiO2/TiO2(B)} Quantum Dot Hybrids: A Comprehensible Route toward High-Performance [>0.1 mol gr–1 h–1] Photocatalytic H2 Production from H2O  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404567183
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-11-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05001")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404567183"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404567183"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404567183"))][Get cited by]]

OpenAlex: https://openalex.org/W4404567183 (Open access: True)
    
[[https://openalex.org/A5080050755][Christos Dimitriou]], [[https://openalex.org/A5019048238][Loukas Belles]], [[https://openalex.org/A5050545965][Nikos Boukos]], [[https://openalex.org/A5070708239][Yiannis Deligiannakis]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05001 
     
Industrial-scale photocatalytic H2 production from H2O is a forward-looking aim in research and technology. To this end, understanding the key properties of TiO2 as a reference H2 production photocatalyst paves the way. Herein, we explore the TiO2 nanosize limits, in conjunction with the TiO2(B) nanophase, as a strategy to enhance the photocatalytic H2 production at >150 mmol/g/h. We present a targeted engineering realm on the synthesis of quantum dots (QDs) of TiO2 consisting of an anatase core (3 nm) interfaced with a nanometric shell of the TiO2(B) phase, synthesized through a modified flame spray pyrolysis (FSP) process. The {TiO2-anatase/TiO2(B)} core–shell QDs, with high specific surface area SSA = 360 m2/gr, achieve a milestone H2 production yield of 156 mmol/g/h and solar-to-H2 efficiency nSTH = 24.2%. We demonstrate that diligent control of the TiO2-anatase/TiO2(B) heterojunction, in tandem with lattice microstrain, are key factors that contribute to the superior H2 production, i.e., not only the high SSA of the QDs. At these quantum-size limits, the formation of lattice dislocations and interstitial Ti centers enhances photon absorption at ∼2.3 eV (540 nm), resulting in the generation of midgap states around the Fermi energy. EPR spectroscopy provides direct evidence that the photoinduced holes are preferentially localized on the TiO2(B) shell, while the photoinduced electrons accumulate on the anatase nanophase. Combined electrochemical and photocatalytic analyses demonstrate that the presence of an optimal TiO2(B) phase is significant for the photoactivity of TiO2 in all QD materials. High SSA does contribute to enhanced photocatalytic H2 production; however, its role is not the key-determinant. TiO2 lattice-dislocations in QDs provide extra DOS that can additionally assist in the photon utilization efficiency. Overall, the present work reveals a general concept, that is, at the quantum-size scale, lattice microstrain engineering and interstitial-states' formation are spontaneously facilitated by nanolattice physics. Diligent optimization of these properties offers a pathway toward high-end photocatalytic efficacy.    

    

* Cofactor-Inspired Quinone Catalysis Following a One-Electron Hydrogen Atom Transfer Pathway  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404572577
:TOPICS: Role of Porphyrins and Phthalocyanines in Materials Chemistry, Dioxygen Activation at Metalloenzyme Active Sites, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-11-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05988")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404572577"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404572577"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404572577"))][Get cited by]]

OpenAlex: https://openalex.org/W4404572577 (Open access: False)
    
[[https://openalex.org/A5020953774][Amreen K. Bains]], [[https://openalex.org/A5110605417][Harshit Jain]], [[https://openalex.org/A5086765861][Abhishek Kundu]], [[https://openalex.org/A5108606659][Rahul Singh]], [[https://openalex.org/A5019108600][Sudha Yadav]], [[https://openalex.org/A5026191696][Yadav Ankit]], [[https://openalex.org/A5081346085][Debashis Adhikari]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05988 
     
Alcohol dehydrogenation catalysts in an aerobic atmosphere are often inspired by biological cofactors, which play a major role in controlling the redox chemistry. A large body of work mimicking quinone-containing cofactors established two major mechanistic routes, addition–elimination or transamination. Both of these pathways are completely regulated by two-electron processes, despite the possibility of the cofactor motif being reduced by one electron. In stark contrast to the established mechanisms, we demonstrate a one-electron pathway in quinone catalysis toward dehydrogenating alcohols. The described pyrene dione molecule is efficient in catalytic dehydrogenation of primary, secondary, and aliphatic alcohols. The process starts with the photoexcitation of the dione motif which becomes photoreduced by KOtBu to generate a persistent semiquinonate radical. The substrate alcohol interacts with the quinone backbone to forge a hydrogen-bonded intermediate, which leads to a crucial hydrogen atom transfer (HAT) step, to accomplish the dehydrogenation reaction. A series of kinetic experiments including Bell–Evans–Polanyi correlation with the bond dissociation enthalpy firmly establish HAT to be rate-determining during dehydrogenation reactions. A kinetic isotope effect measured for the dehydrogenation process at 30 °C is 7.7 ± 0.9. Interception of a series of intermediates by a radical quencher in conjunction with a radical-probe substrate further affirms the radical-mediated, one-electron pathway to be operative that is in striking contrast to two-electron-driven quinone catalysis established so far.    

    

* Electrochemical Promotion of Catalysis by Lithium-Ion  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404579251
:TOPICS: Lithium-ion Battery Technology, Electrocatalysis for Energy Conversion, Electrochemical Reduction in Molten Salts
:PUBLICATION_DATE: 2024-11-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04622")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404579251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404579251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404579251"))][Get cited by]]

OpenAlex: https://openalex.org/W4404579251 (Open access: False)
    
[[https://openalex.org/A5100648239][Ju Wang]], [[https://openalex.org/A5028150563][Shuo Yan]], [[https://openalex.org/A5079471616][Kholoud E. Salem]], [[https://openalex.org/A5045865860][Christopher Panaritis]], [[https://openalex.org/A5054037157][Mohamed S.E. Houache]], [[https://openalex.org/A5078262597][Yaser Abu‐Lebdeh]], [[https://openalex.org/A5044827415][Drew Higgins]], [[https://openalex.org/A5044206105][Elena A. Baranova]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04622 
     
No abstract    

    
