#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Thu Feb 29 00:43:18 2024

Found 25 results from 2024-02-22 to 2024-02-29
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Designing an Efficient Biocatalyst for the Phosphoribosylation of Antiviral Pyrazine-2-carboxamide Derivatives  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391991668
:TOPICS: Nucleotide Metabolism and Enzyme Regulation, Synthesis and Biological Activities of Oxazolones, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05059")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391991668"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391991668"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391991668"))][Get cited by]]

OpenAlex: https://openalex.org/W4391991668 (Open access: False)
    
[[https://openalex.org/A5020289297][Evgeniy A. Zayats]], [[https://openalex.org/A5080133403][Ilja V. Fateev]], [[https://openalex.org/A5011734229][Yu. A. Abramchik]], [[https://openalex.org/A5008792789][М. А. Костромина]], [[https://openalex.org/A5049066124][В. И. Тимофеев]], [[https://openalex.org/A5030149407][Daria O. Yurovskaya]], [[https://openalex.org/A5093861229][Andrey A. Karanov]], [[https://openalex.org/A5040926273][Irina D. Konstantinova]], [[https://openalex.org/A5028667873][Andrey V. Golovin]], [[https://openalex.org/A5052930403][Р. С. Есипов]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05059 
     
The development of technologies for the efficient synthesis of innovative antiviral compounds remains an important challenge for modern biotechnology, especially in the context of the recent COVID-19 pandemic. One of the drugs that is currently in the research spotlight for potential anti-SARS-CoV-2 activity is the purine mimetic prodrug compound T-705, also known as favipiravir. Along with a similar compound, T-1105, the activation of T-705 is limited by the low rate of phosphoribosylation, mediated by an enzyme named hypoxanthine-guanine phosphoribosyltransferase (HGPRT). Therefore, the synthesis of phosphoribosylated/ribosylated derivatives of these prodrugs is a viable direction for the discovery and development of antiviral pharmaceuticals. However, the chemical synthesis of such compounds is a complex and laborious process, whereas enzymatic cascades are not feasible because of the narrow HGPRT substrate specificity. Here, we report the successful rational design of an efficient biocatalyst for T-705/T-1105 phosphoribosylation. With two rounds of Thermus thermophilus HB27 HGPRT active site optimization, we have achieved a 325-fold increase in kcat toward the compound T-705 and a 125-fold increase toward T-1105 accompanied by a multifold decrease in KM. The practical applicability of the designed mutant was illustrated through the preparative synthesis of T-705/T-1105 nucleotide derivatives. Our engineered biocatalyst can become a basis for the technologies of enzymatic and chemoenzymatic synthesis of various T-705/T-1105 derivatives with proven antiviral activity. Moreover, our results provide insight into the molecular mechanism of T-705/T-1105 phosphoribosylation, including the experimental evidence explaining the reasons behind the low activity of HGPRT toward these compounds.    

    

* High-Entropy Effect Promoting Self-Healing Behavior of Two-Dimensional Metal Oxide Electrocatalysts for Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391991674
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05870")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391991674"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391991674"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391991674"))][Get cited by]]

OpenAlex: https://openalex.org/W4391991674 (Open access: False)
    
[[https://openalex.org/A5051788822][Dongdong Gao]], [[https://openalex.org/A5021658618][Wenxiang Zhu]], [[https://openalex.org/A5087269163][Jinxin Chen]], [[https://openalex.org/A5008126805][Keyang Qin]], [[https://openalex.org/A5074338325][Mengjie Ma]], [[https://openalex.org/A5025849211][Jie Shi]], [[https://openalex.org/A5013134577][Qun Wang]], [[https://openalex.org/A5061980234][Zhenglong Fan]], [[https://openalex.org/A5065985607][Qi Shao]], [[https://openalex.org/A5043301652][Fan Liao]], [[https://openalex.org/A5057299366][Mingwang Shao]], [[https://openalex.org/A5071907213][Zhenhui Kang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05870 
     
No abstract    

    

* Integrating Atomically Dispersed Ir Sites in MnCo2O4.5 for Highly Stable Acidic Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391992130
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06243")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391992130"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391992130"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391992130"))][Get cited by]]

OpenAlex: https://openalex.org/W4391992130 (Open access: False)
    
[[https://openalex.org/A5072004374][Hua Ke]], [[https://openalex.org/A5004808990][Xiaoke Li]], [[https://openalex.org/A5025107745][Rui Zhang]], [[https://openalex.org/A5018679788][Xiao Duan]], [[https://openalex.org/A5055283292][Yongkang Wu]], [[https://openalex.org/A5043023473][Xiaodong Pi]], [[https://openalex.org/A5090900131][Jia Li]], [[https://openalex.org/A5055152383][Jianguo Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06243 
     
Industrial water electrolysis requires oxygen evolution reaction (OER) catalysts that exhibit both high activity and adaptability to high current densities. However, single Ir atoms of the OER catalysts often show high performance in the three-electrode system but are limited to low current densities in proton exchange membrane water electrolyzers (PEMWE). The high oxidation potential and catalyst shedding caused by oxygen bubble desorption have hindered the stability, resulting in unsatisfactory PEMWE performance. Achieving high catalytic stability under high current density conditions still presents a significant challenge for all of the OER catalysts. In this study, an efficient and stable catalytic system for OER is constructed by a doping strategy, which consists of atomically dispersed Ir sites in MnCo2O4.5. The integrated Ir–MnCo2O4.5 catalyst demonstrates remarkable OER activity, with a low overpotential of 238 mV at 10 mA/cm2. It exhibits long-term stability, maintaining this high activity for 700 h at 20 mA/cm2 with a degradation rate of 0.025 mV/h. Impressively, the PEMWE with the integrated Ir–MnCo2O4.5 as the anode remains stable even after nearly 100 h at 200 mA/cm2, outperforming most previously reported single-iridium atom-based PEMWEs. Density functional theory calculations show that the redistribution of charges brought by the introduction of Ir and Mn not only effectively reduces the dissolution of lattice oxygen and Ir active sites but also lowers the energy barrier of the rate-determining step, thereby significantly improving the stability and activity of Ir–MnCo2O4.5 under high current density.    

    

* Photoinduced, Palladium-Catalyzed Enantioselective 1,2-Alkylsulfonylation of 1,3-Dienes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391993117
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Innovations in Organic Synthesis Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00470")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391993117"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391993117"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391993117"))][Get cited by]]

OpenAlex: https://openalex.org/W4391993117 (Open access: False)
    
[[https://openalex.org/A5039851941][Zhilin Liu]], [[https://openalex.org/A5045832851][Zhipeng Ye]], [[https://openalex.org/A5055498163][Zihao Liao]], [[https://openalex.org/A5090498632][Weidong Lu]], [[https://openalex.org/A5049594674][Jianping Guan]], [[https://openalex.org/A5055603180][Zhongli Gao]], [[https://openalex.org/A5074447615][Kai Chen]], [[https://openalex.org/A5014195139][Xiao‐Qing Chen]], [[https://openalex.org/A5070637699][Hao-Yue Xiang]], [[https://openalex.org/A5065499122][Hua Ye]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00470 
     
The chiral allylic sulfonylated group is a unique structural motif embedded in a range of natural products and pharmaceuticals. Notably, the synthesis of structurally diverse chiral allylic sulfonylated derivatives via alkylsulfonylation of 1,3-dienes remains underexplored because of its inherent challenges in stereocontrol and regioselectivity. Herein, photoinduced, palladium-catalyzed enantioselective 1,2-alkylsulfonylation of conjugated 1,3-dienes is described. A wide variety of alkyl bromides, 1,3-dienes, and sodium sulfinates could be facilely coupled to generate value-added chiral allylic sulfonylated derivatives with high enantioselectivity. Finally, the utility of this enantioselective difunctionalization protocol was demonstrated in pharmaceutical analogue synthesis.    

    

* Structure and Reactivity of Binuclear Cu Active Sites in Cu-CHA Zeolites for Stoichiometric Partial Methane Oxidation to Methanol  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391996262
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Mesoporous Materials
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06181")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391996262"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391996262"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391996262"))][Get cited by]]

OpenAlex: https://openalex.org/W4391996262 (Open access: False)
    
[[https://openalex.org/A5034225594][Laura N. Wilcox]], [[https://openalex.org/A5033077129][José Rebolledo-Oyarce]], [[https://openalex.org/A5039687304][Andrew D. Mikes]], [[https://openalex.org/A5006415472][Yujia Wang]], [[https://openalex.org/A5062009633][William F. Schneider]], [[https://openalex.org/A5072511676][Rajamani Gounder]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06181 
     
Aluminosilicate zeolites exchanged with copper ions facilitate partial methane oxidation (PMO) to methanol in stoichiometric oxidation and reduction cycles, yet the identities of active Cu sites and details of the reaction mechanism remain debated. Here, we use the high-symmetry chabazite (CHA) zeolite framework as a model support to probe the relationship between bulk composition, Cu speciation, and response to various oxidizing and reducing treatments. Density functional theory and first-principles thermodynamics combined with statistical models reveal that Cu speciation and composition depend strongly on Al configuration and external gas conditions. Cu-CHA samples were synthesized to survey broad regions of Si/Al and Cu/Al composition space and framework Al proximity. Characterization by in situ X-ray absorption and UV–visible spectroscopy during exposure to different oxidation conditions reveal that the extent of Cu oxidation is sensitive to activation conditions and thus that both kinetic and thermodynamic factors influence Cu oxidizability in a given material. Similar characterizations during CO reduction reveal that CO titrates Cu2+ in amounts suggesting the presence of both O- and O2-bridged species. In contrast, CH4 and autoreduction (He) treatments reduce similar but smaller numbers of Cu sites than CO, implicating O2-bridged Cu dimers as a potential common intermediate in the former reduction pathways. A systematic increase in methanol yields (per Cu) in stoichiometric PMO cycles increase with the fraction of binuclear Ox-bridged Cu sites suggests these species as active sites, as depicted in an updated PMO reaction mechanism.    

    

* Dynamic Docking-Assisted Engineering of Hydrolases for Efficient PET Depolymerization  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4391997686
:TOPICS: Global E-Waste Recycling and Management, Biodegradable Polymers as Biomaterials and Packaging, Recycling Technologies for Carbon Fiber Composites
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00400")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391997686"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391997686"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391997686"))][Get cited by]]

OpenAlex: https://openalex.org/W4391997686 (Open access: False)
    
[[https://openalex.org/A5066167884][Yi Zheng]], [[https://openalex.org/A5025167872][Qingbin Li]], [[https://openalex.org/A5075370591][Pan Liu]], [[https://openalex.org/A5084545842][Yingbo Yuan]], [[https://openalex.org/A5060247019][Longyang Dian]], [[https://openalex.org/A5092164942][Qian Wang]], [[https://openalex.org/A5067975624][Quanfeng Liang]], [[https://openalex.org/A5028881300][Tianyuan Su]], [[https://openalex.org/A5059844098][Qingsheng Qi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00400 
     
No abstract    

    

* Photoinduced Regioselective Sulfonylsulfination of Alkenes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392004197
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Innovations in Organic Synthesis Reactions, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00049")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392004197"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392004197"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392004197"))][Get cited by]]

OpenAlex: https://openalex.org/W4392004197 (Open access: False)
    
[[https://openalex.org/A5038883899][Helian Li]], [[https://openalex.org/A5082889999][Yongxin Zhang]], [[https://openalex.org/A5076602989][Xiaoyong Zou]], [[https://openalex.org/A5005205790][Xiaoxiao Yang]], [[https://openalex.org/A5045685496][Pan Zhou]], [[https://openalex.org/A5065055275][Xinyue Ma]], [[https://openalex.org/A5044388938][Shaoping Lu]], [[https://openalex.org/A5011249790][Qing Sun]], [[https://openalex.org/A5079144903][Chao Shu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00049 
     
Regioselective 1,2-dichalcogenation of alkenes has attracted significant attention in modern organic synthetic chemistry. While there are a plethora of methods to access alkene dichalcogenated architectures, sulfonylsulfination of alkenes is extremely challenging due to the inherent characteristics of the sulfur atom. Herein, a multicomponent fragment coupling of alkenes, sulfinates, and DABSO was developed to construct densely functionalized sulfonylsulfinated products, which are otherwise challenging to access, with broad substrate scope and group tolerance under mild and operationally simple conditions, using an inexpensive 100–1000 ppm organic photocatalyst. In addition, the protocol was applied to the late-stage functionalization of complex molecules, and the obtained products were converted into diverse downstream transformations to demonstrate their synthetic potential. Experimental and theoretical mechanistic investigations suggest that these reactions proceed through sequential sulfonyl and sulfinyl oxygen radical mutual transformations and radical–polar crossover coupling. This strategy provides access to previously inaccessible alkene sulfonylsulfinated products in good-to-high regio- and stereoselectivity, along with opening up previously unexplored synthetic directions.    

    

* Atroposelective Synthesis of Axially Chiral Diaryl Ethers by Copper-Catalyzed Enantioselective Alkyne–Azide Cycloaddition  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392004251
:TOPICS: Atroposelective Synthesis of Axially Chiral Compounds, Chiroptical Spectroscopy in Organic Compound Analysis, Sphingolipid Signalling and Metabolism in Health and Disease
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06148")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392004251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392004251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392004251"))][Get cited by]]

OpenAlex: https://openalex.org/W4392004251 (Open access: True)
    
[[https://openalex.org/A5014475523][X Han]], [[https://openalex.org/A5011267819][Lan Chen]], [[https://openalex.org/A5073177245][Yong Yan]], [[https://openalex.org/A5012757324][Yanyang Zhao]], [[https://openalex.org/A5011404596][Aijun Lin]], [[https://openalex.org/A5006095272][Shang Gao]], [[https://openalex.org/A5052874928][Hequan Yao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06148  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.3c06148][pdf]])
     
Diaryl ethers are important structural motifs widely found in bioactive natural products, ligands, and catalysts. While there are a variety of methods available to generate diaryl ethers, progress on the construction of axially chiral diaryl ethers has been slow. We report herein an atroposelective copper-catalyzed cycloaddition between bisalkynes and azides. With an indane-fused BOX ligand used, a diverse array of C–O atropisomers are obtained with up to 97% yield and 99% ee. Control experiments showed that a sequential enantioselective desymmetrization–kinetic resolution process is involved, and the former plays a major role. In addition, an asymmetric depletion is observed for this catalytic synthesis by nonlinear effect studies. By thermal racemization experiments, the rotational barrier of the C–O axis of 3aa is calculated to be 35.9 kcal/mol, which lays the foundation for its isolation, as well as further applications.    

    

* Combined Hydrogen and Alkane Production by Photocatalytic Decarboxylative C–C Homocoupling of Fatty Acid by Constructing a Hydrogen-Deficient Catalytic Interface  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392004426
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Polyoxometalate Clusters and Materials, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06070")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392004426"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392004426"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392004426"))][Get cited by]]

OpenAlex: https://openalex.org/W4392004426 (Open access: False)
    
[[https://openalex.org/A5035388503][Xucheng Li]], [[https://openalex.org/A5088693897][Peng Yang]], [[https://openalex.org/A5017988818][Zhipeng Huang]], [[https://openalex.org/A5065217556][Gang Feng]], [[https://openalex.org/A5082042466][Leo Lingchun Kong]], [[https://openalex.org/A5089946640][Haiwei Jiang]], [[https://openalex.org/A5031655322][Weiran Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06070 
     
Decarboxylation of biomass-derived fatty acids provides an important method for the production of value-added alkane fuels and chemicals. Here, selective decarboxylative C–C homocoupling of fatty acids to obtain long-chain alkanes was achieved by heterogeneous photocatalysis under mild conditions. Hydrogen was cogenerated as the potential energy source. The high selectivity for the coupling product was realized by constructing a hydrogen-deficient catalytic interface through the combined action of Ru nanoparticles supported on TiO2 and continuous N2 blow, which can inhibit the hydrogenation of alkyl radicals and enhance the C–C coupling of alkyl radicals. C2n–2 saturated alkanes (as high as 93%) and hydrogen (as high as 20.3 μmol·mL–1) are produced from bioderived C4–C12 fatty acids in high yields under mild reaction conditions (25 °C, N2 blow). Furthermore, low-value industrial fatty acid mixtures such as coconut oil and Cinnamomum camphora seed kernel oil can be directly applied in this catalytic system and selectively yield long-chain alkanes (up to 80%) in a solvent-free system. Density functional theory (DFT) calculations and various analytical methods were applied to elucidate the possible catalytic mechanism.    

    

* Boosting the Bifunctionality and Durability of Cobalt-Fluoride-Oxide Nanosheets for Alkaline Water Splitting Through Nitrogen-Plasma-Promoted Electronic Regulation and Structural Reconstruction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392016577
:TOPICS: Electrocatalysis for Energy Conversion, Atomic Layer Deposition Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00294")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392016577"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392016577"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392016577"))][Get cited by]]

OpenAlex: https://openalex.org/W4392016577 (Open access: False)
    
[[https://openalex.org/A5051434566][Shuo Wang]], [[https://openalex.org/A5020729346][Cheng‐Zong Yuan]], [[https://openalex.org/A5059156645][Yi Zheng]], [[https://openalex.org/A5059804832][Yao Kang]], [[https://openalex.org/A5006729941][K.S. Hui]], [[https://openalex.org/A5041740133][Kaixi Wang]], [[https://openalex.org/A5031098965][Haixing Gao]], [[https://openalex.org/A5027303758][Duc Anh Dinh]], [[https://openalex.org/A5033074084][Y. R. Cho]], [[https://openalex.org/A5011737382][Kwun Nam Hui]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00294 
     
No abstract    

    

* Regulating the Spin Polarization of NiFe Layered Double Hydroxide for the Enhanced Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392018831
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06180")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392018831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392018831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392018831"))][Get cited by]]

OpenAlex: https://openalex.org/W4392018831 (Open access: False)
    
[[https://openalex.org/A5017834536][Wenwu Cao]], [[https://openalex.org/A5068375738][Xianhui Gao]], [[https://openalex.org/A5038747062][Jie Wu]], [[https://openalex.org/A5056746694][Anqi Huang]], [[https://openalex.org/A5015273050][Huan Hu]], [[https://openalex.org/A5091083063][Zhongwei Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06180 
     
No abstract    

    

* Surpassing the Limited Coordination Affinity of Native Amides by Introducing Pyridone-Pd-AgOAc Clusters to Promote Distal γ-C(sp3)–H Arylation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392022653
:TOPICS: Transition-Metal-Catalyzed C–H Bond Functionalization, Transition Metal-Catalyzed Cross-Coupling Reactions, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-02-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392022653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392022653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392022653"))][Get cited by]]

OpenAlex: https://openalex.org/W4392022653 (Open access: False)
    
[[https://openalex.org/A5035962932][Nupur Goswami]], [[https://openalex.org/A5034740343][Nikunj Kumar]], [[https://openalex.org/A5021247800][Puneet Gupta]], [[https://openalex.org/A5051885484][Debabrata Maiti]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06007 
     
The utilization of weak coordination in promoting site-selective C(sp3)–H functionalization is of immense importance. Herein, we report a Pd-catalyzed distal γ-C(sp3)–H arylation that harnesses the weak coordination affinity of keto groups with the native noncoordinating amide moiety. The current protocol overcomes one of the major challenges associated with the diversification of synthetic modular frameworks of quaternary centers: controlling the mono- vs difunctionalization of chemically equivalent C–H bonds. The developed condition overrides the interference of the acidic α-hydrogen for possible side reactions of amides and delivers the exclusive formation of the γ-monoarylated product. The association of 2-hydroxy pyridine ligands bearing electron-withdrawing substituents demonstrated the best partnership with the Pd–Ag hetero-bimetallic complex to achieve this distal γ-C(sp3)–H activation of a range of noncoordinating aliphatic amides in the absence of any other exogenous ligand. Here, an array of mechanistic measurements helped us to realize the role of the ligand. A density functional theory (DFT) study was performed on four different computational models to elucidate the working principle of a single pyridone ligand in the absence of any externally installed strong chelating donor motifs. The reaction proceeds sequentially through three primary stages: initial C–H activation of the γ-C(sp3)–H bond of the amide, succeeded by the oxidative addition of the aryl halide, culminating in reductive elimination, which facilitates the C(sp2)–C(sp3) coupling between the aryl and the aliphatic amide moieties. The role of the silver salt remained essential not only for successful C–H activation but also for turning over the catalytic cycle.    

    

* Flexible Units Induced Three-Dimensional Covalent Organic Frameworks with a Heteromotif Molecular Junction for Photocatalytic H2O2 Production  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392038453
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Chemistry and Applications of Metal-Organic Frameworks, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06078")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392038453"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392038453"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392038453"))][Get cited by]]

OpenAlex: https://openalex.org/W4392038453 (Open access: False)
    
[[https://openalex.org/A5031303790][Jia-Peng Liao]], [[https://openalex.org/A5036897639][Mi Zhang]], [[https://openalex.org/A5088520193][Pei Huang]], [[https://openalex.org/A5033346425][Long‐Zhang Dong]], [[https://openalex.org/A5051237661][Tiantian Ma]], [[https://openalex.org/A5076445689][Guo‐Zhang Huang]], [[https://openalex.org/A5087095278][Yu-Fei Liu]], [[https://openalex.org/A5023725539][Meng Lu]], [[https://openalex.org/A5000509449][Shun-Li Li]], [[https://openalex.org/A5003081708][Ya‐Qian Lan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06078 
     
In recent years, significant progress has been achieved in the field of three-dimensional covalent organic frameworks (3D COFs). However, there is still a great challenge to use flexible building units to synthesize high-connectivity 3D COFs. In this work, we showed that [6 + 3] 3D COFs could be constructed by inducing highly flexible planar building blocks from C3 antitriangular prismed 3D building blocks. Herein, two 3D COFs with spn topology based on flexible cyclotriphosphazene units were constructed and denoted as TAA/TAB-CTP-COF, and their redox ability and photophysical features can be finely regulated by the coupled functional group, such as benzene and triazine groups. As a result, the redox heteromotif molecular junction TAA-CTP-COF with fully exposed active sites achieved high photocatalytic production of hydrogen peroxide (H2O2) with a yield of 1041 μM h–1 without any additional photosensitizers, organic scavengers, or cocatalysts. Furthermore, in the presence of an electron donor, the production rate of H2O2 could reach up to 2221 μM h–1, exhibiting one of the best performances for photocatalytic H2O2 production in the field of crystalline materials. This work showcases the potential of using flexible building blocks in building 3D COFs and highlights the versatility and efficacy of metal-free COFs in solar energy conversion.    

    

* Effect of Mixing Order of Si and Al Sources on the Inner Architecture and Catalytic Performance of ZSM-5 Zeolites  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392044042
:TOPICS: Zeolite Chemistry and Catalysis, Mesoporous Materials, Glass Science and Technology
:PUBLICATION_DATE: 2024-02-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00262")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392044042"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392044042"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392044042"))][Get cited by]]

OpenAlex: https://openalex.org/W4392044042 (Open access: False)
    
[[https://openalex.org/A5078511712][Yongjia Shen]], [[https://openalex.org/A5005587950][Shang Zhang]], [[https://openalex.org/A5086387355][Zhengxing Qin]], [[https://openalex.org/A5086043321][Antoine Beuque]], [[https://openalex.org/A5039064903][Ludovic Pinard]], [[https://openalex.org/A5000750902][Shunsuke Asahina]], [[https://openalex.org/A5078914737][Naoki Asano]], [[https://openalex.org/A5003393009][Ruizhe Zhang]], [[https://openalex.org/A5031124649][Jiaqi Zhao]], [[https://openalex.org/A5011639404][Fan Yang]], [[https://openalex.org/A5071363074][Xinmei Liu]], [[https://openalex.org/A5086664284][Yan Zhang]], [[https://openalex.org/A5027944064][Svetlana Mintova]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00262 
     
The performance of zeolites in catalysis and adsorption is closely related to their inner architecture beneath the crystal surface, which however remains less studied due to characterization limitations. Here we report the synthesis of two ZSM-5 zeolite samples by changing only the order of mixing of Si and Al sources, resulting not only in morphological differences of the zeolite crystals but most importantly in defined distinction in their inner architecture. The spatial Si and Al distributions and structural properties of the ZSM-5 zeolite crystals were characterized by high-resolution microscopy under chemically unbiased defect-selective NH4F etching. The Al-zoning and structural features in the ZSM-5 zeolite crystals were explained by the biased nucleation in the Si-rich aluminosilicate amorphous precursor followed by multistage crystal growth in a heterogeneous feedstock. This observation was associated with the different solubility and reactivity of the microscopic aluminosilicate domains with various Si/Al ratios in the amorphous precursors. The zeolites with diverse structural properties showed a high cracking activity in n-hexane cracking reaction and different activity, stability, and product selectivity in the ethylene dehydroaromatization (EDA) reaction. The comprehensive understanding of the zeolite synthesis history and their performance in the EDA reaction revealed the chemical mixing-dependent synthesis–structure–performance correlation of the zeolite catalyst.    

    

* Supervised AI and Deep Neural Networks to Evaluate High-Entropy Alloys as Reduction Catalysts in Aqueous Environments  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392044082
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Atom Probe Tomography Research
:PUBLICATION_DATE: 2024-02-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05017")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392044082"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392044082"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392044082"))][Get cited by]]

OpenAlex: https://openalex.org/W4392044082 (Open access: True)
    
[[https://openalex.org/A5060552376][Rafael B. Araujo]], [[https://openalex.org/A5056174579][Tomas Edvinsson]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05017 
     
No abstract    

    

* Catalytic Enantioselective Cycloaddition Transformation of Tricyclic Arenes Enabled by a Dual-Role Chiral Cage-Reactor  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392049487
:TOPICS: Self-Assembly and Molecular Recognition in Chemistry, Peptide Synthesis and Drug Discovery, Noncovalent Interactions in Molecular Crystals and Supramolecular Chemistry
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06361")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392049487"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392049487"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392049487"))][Get cited by]]

OpenAlex: https://openalex.org/W4392049487 (Open access: False)
    
[[https://openalex.org/A5010479652][Jie Chen]], [[https://openalex.org/A5037215225][Xueyuan Wu]], [[https://openalex.org/A5031722825][Huang Sisi]], [[https://openalex.org/A5002828878][Jie Yang]], [[https://openalex.org/A5083424283][Yu‐Lin Lu]], [[https://openalex.org/A5008346135][Zhiwei Jiao]], [[https://openalex.org/A5002170896][Cheng‐Yong Su]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06361 
     
No abstract    

    

* Ultrathin Holey Pt–M Alloy Nanosheets via Sequential Kinetic–Thermodynamic Metal Reduction Control  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392078691
:TOPICS: Electrocatalysis for Energy Conversion, Ice Nucleation and Melting Phenomena, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05806")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392078691"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392078691"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392078691"))][Get cited by]]

OpenAlex: https://openalex.org/W4392078691 (Open access: False)
    
[[https://openalex.org/A5034416833][Heon Chul Kim]], [[https://openalex.org/A5004515260][Respati K. Pramadewandaru]], [[https://openalex.org/A5055068849][Mrinal Kanti Kabiraz]], [[https://openalex.org/A5092359573][Ghufran Aulia Bin Azizar]], [[https://openalex.org/A5030417545][Hafidatul Wahidah]], [[https://openalex.org/A5000965572][Youngmin Kim]], [[https://openalex.org/A5044344225][Su‐Un Lee]], [[https://openalex.org/A5087136199][Ho‐Jeong Chae]], [[https://openalex.org/A5026994173][Sang‐Il Choi]], [[https://openalex.org/A5038083964][Jong Wook Hong]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05806 
     
No abstract    

    

* Investigation of the Relationship between Metal Loading and Acidic Oxygen Evolution Reaction Activity in Single-Atom Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392084683
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06263")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392084683"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392084683"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392084683"))][Get cited by]]

OpenAlex: https://openalex.org/W4392084683 (Open access: False)
    
[[https://openalex.org/A5035223262][Bing Tang]], [[https://openalex.org/A5059787769][Xiaolong Zhang]], [[https://openalex.org/A5020016810][Qianqian Ji]], [[https://openalex.org/A5017197771][Gao Min]], [[https://openalex.org/A5036519850][Huijuan Wang]], [[https://openalex.org/A5067669061][Ruiqi Liu]], [[https://openalex.org/A5017430213][Peng Jiang]], [[https://openalex.org/A5005402696][Hengjie Liu]], [[https://openalex.org/A5055838753][Chao Wang]], [[https://openalex.org/A5069910699][Hao Tan]], [[https://openalex.org/A5052333339][Wensheng Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06263 
     
No abstract    

    

* Synergistic Dual Catalysis in Stereodivergent Synthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392095563
:TOPICS: Homogeneous Catalysis with Transition Metals, Olefin Metathesis Chemistry, Asymmetric Catalysis
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06267")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392095563"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392095563"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392095563"))][Get cited by]]

OpenAlex: https://openalex.org/W4392095563 (Open access: False)
    
[[https://openalex.org/A5071261513][Liang Wei]], [[https://openalex.org/A5086781782][Chu-Li Fu]], [[https://openalex.org/A5064765338][Zuo-Fei Wang]], [[https://openalex.org/A5028556048][Hai‐Yan Tao]], [[https://openalex.org/A5014921160][Chun‐Jiang Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06267 
     
No abstract    

    

* Fast Kinetics of Hydrogen Oxidation Reaction on Single-Atom Ce-Alloyed Ru in Alkaline Electrolytes  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392130607
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05954")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392130607"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392130607"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392130607"))][Get cited by]]

OpenAlex: https://openalex.org/W4392130607 (Open access: False)
    
[[https://openalex.org/A5031779825][Zhiyu Cheng]], [[https://openalex.org/A5050709202][Yang Yang]], [[https://openalex.org/A5011694527][Fangcai Zheng]], [[https://openalex.org/A5021077043][Shi Chen]], [[https://openalex.org/A5008620166][Peichen Wang]], [[https://openalex.org/A5044971912][Pengcheng Wang]], [[https://openalex.org/A5053505040][Hao Huang]], [[https://openalex.org/A5084793778][Changlai Wang]], [[https://openalex.org/A5052077971][Dongdong Wang]], [[https://openalex.org/A5014087781][Qianwang Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05954 
     
The kinetics of anodic hydrogen oxidation reaction (HOR) in alkaline media, even catalyzed by the state-of-the-art Pt catalysts, is much lower than that in acidic electrolytes, which is a significant barrier for the development of high-performance anion-exchange membrane fuel cells (AEMFCs). Based on the difference in catalytic mechanism under alkaline and acidic conditions, we suggest that the sluggish HOR in alkaline media is due to the involvement of hydroxyl in Heyrovsky or Volmer steps, and this can be improved by forcing HOR on active sites via the mechanism like that in acidic media. Herein, we prepared a single-atom Ce-alloyed Ru catalyst (Ce1Ru/C) in which Ce atoms could adsorb abundant OH– owing to its much stronger oxophilicity compared to that of Ru. Therefore, the nearest neighbor Ru atoms around Ce atoms become the adsorption sites for Had which would react with the surrounding adsorbed water to form H3O+ad. A key H3O+ad intermediate on the surface of Ce1Ru/C during HOR in alkaline media was detected by in situ Raman spectroscopy, providing direct evidence for the HOR in alkaline media occurring via steps similar to those in acidic media. Even at 30 mV overpotential, Ce1Ru/C still displays rapid reaction kinetics with high mass and specific activity about 27/59 and 5/12 times higher than those of Pt/C and PtRu/C. The activity of our catalyst is the best among various alkaline HOR electrocatalysts reported so far. Moreover, Ce1Ru/C demonstrates high electrochemical stability and CO tolerance, taking a giant step forward toward the commercialization of AEMFCs.    

    

* Tailoring Cu–Zn Dual-Atom Sites with Reordering d-Orbital Splitting Manner for Highly Efficient Acetylene Semihydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392151390
:TOPICS: Catalytic Nanomaterials, Chemistry and Applications of Metal-Organic Frameworks, Advancements in Density Functional Theory
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05779")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392151390"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392151390"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392151390"))][Get cited by]]

OpenAlex: https://openalex.org/W4392151390 (Open access: False)
    
[[https://openalex.org/A5041925870][Yuxue Yue]], [[https://openalex.org/A5043076197][Bolin Wang]], [[https://openalex.org/A5003840280][Chunxiao Jin]], [[https://openalex.org/A5042557504][Kaixin Huang]], [[https://openalex.org/A5082830043][Qi Zhou]], [[https://openalex.org/A5070649067][Renqin Chang]], [[https://openalex.org/A5039823100][Saisai Wang]], [[https://openalex.org/A5081603750][Zhiyan Pan]], [[https://openalex.org/A5081362621][Jia Zhao]], [[https://openalex.org/A5013409727][Xiaonian Li]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05779 
     
The design of inexpensive, nontoxic, and abundant transition metal catalysts for the selective hydrogenation of alkynes remains a significant challenge faced by both the industrial and academic communities. Here, we report a novel catalyst comprising a well-defined Cu–Zn dual-atom catalyst supported on defective pyrolyzed ZIF-8 material (CuZn/NC2), resulting in enhanced d-electron domination near the Fermi level and reordered d-orbital Splitting manner. This catalyst exhibited outstanding performance in the selective hydrogenation of acetylene to ethylene, demonstrating high conversion rates (97%), remarkable selectivity (97.5%), and excellent stability (over 70 h). The unique structural characteristics of Cu–Zn dual-atom sites, anchored to the carrier through Cu–N3&Zn–N3 configurations, ensured effective acetylene activation and easy desorption of ethylene. These features are pivotal to the catalyst’s exceptional activity and selectivity. This work presents a new approach to the design of nonprecious metal catalysts for the selective hydrogenation of acetylene.    

    

* Unraveling the Catalytic Mechanism of Taxadiene-5α-hydroxylase from Crystallography and Computational Analyses  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392153563
:TOPICS: Chemotherapy-Induced Peripheral Neuropathy in Cancer Treatment, Macromolecular Crystallography Techniques, Dioxygen Activation at Metalloenzyme Active Sites
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05807")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392153563"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392153563"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392153563"))][Get cited by]]

OpenAlex: https://openalex.org/W4392153563 (Open access: False)
    
[[https://openalex.org/A5058387546][Xitong Song]], [[https://openalex.org/A5046225712][Qian Wang]], [[https://openalex.org/A5018246468][Xianfang Zhu]], [[https://openalex.org/A5048633322][Wenhan Fang]], [[https://openalex.org/A5088610294][Xiaonan Liu]], [[https://openalex.org/A5075232788][Chao Shi]], [[https://openalex.org/A5044629554][Zhenzhan Chang]], [[https://openalex.org/A5035488620][Huifeng Jiang]], [[https://openalex.org/A5091278358][Binju Wang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05807 
     
Paclitaxel is a famous chemotherapeutic agent, but its microbial production poses a long-standing challenge due to its poor product selectivity. Taxadiene-5α-hydroxylase (CYP725A4) plays a crucial role in the biosynthesis of paclitaxel, catalyzing the oxidation of taxadiene and iso-taxadiene. This process yields several products, including the byproducts 5(12)-oxa-3(11)-cyclotaxane (OCT) and 5(11)-oxa-3(11)-cyclotaxane (iso-OCT), as well as the target compound taxadien-5α-ol (T5OH). Despite extensive studies, the molecular mechanism of CYP725A4-catalyzed transformations is still elusive, which could impede our understanding of further engineering of the paclitaxel biosynthetic pathway. In this study, the crystal structure of CYP725A4 in complex with taxadiene is elucidated. Through comprehensive computational analyses, the catalytic mechanisms of CYP725A4 in the biosynthesis of natural paclitaxel are deciphered. Our calculations indicate that the oxidation of taxadiene affords a zwitterion intermediate, which can undergo two competing transformation routes. One involves the formation of epoxide, which further undergoes the water-mediated rearrangement to form the T5OH product. In the alternative pathway, protonation of the oxygen in the zwitterion intermediate facilitates subsequent hydride transfer and carbon–oxygen coupling, resulting in the side products OCT/iso-OCT. Contrary to taxadiene, hydroxylation at C5 of iso-taxadiene directly yields the target product T5OH. These crystallographic studies and computational analyses have yielded valuable insights into the catalytic mechanisms of CYP725A4 and laid the foundation for the further engineering of CYP725A4.    

    

* Friedel–Crafts Alkylation of Toluene by Methyl Mercaptan: Effect of Topology and Acidity of Zeolite Catalysts  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392162425
:TOPICS: Zeolite Chemistry and Catalysis, Desulfurization Technologies for Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06088")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392162425"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392162425"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392162425"))][Get cited by]]

OpenAlex: https://openalex.org/W4392162425 (Open access: False)
    
[[https://openalex.org/A5083873232][Abdelilah Bayout]], [[https://openalex.org/A5031682083][Claudia Cammarano]], [[https://openalex.org/A5014041459][Izabel C. Medeiros-Costa]], [[https://openalex.org/A5043136293][Gleb Veryasov]], [[https://openalex.org/A5031046889][Vasile Hulea]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06088 
     
The catalytic behaviors of zeolites with MFI, FAU, BEA, MOR, and MWW topologies and Si/Al ratios between 10 and 19 were examined in the toluene alkylation by methyl mercaptan (CH3SH). Over all catalysts, at 375 °C, the reagents have been primarily consumed in alkylation reactions, and only less than 2% of CH3SH led to the formation of light hydrocarbons. Based on extensive experiments, we showed that the crucial variables affecting the activity, the selectivity, and the deactivation of the catalysts were their pore size/architecture and the amount of the acid sites. ZSM-5 (MFI, Si/Al = 15) outperformed the other zeolites, exhibiting higher selectivity in alkylation and substantially higher resistance to the deactivation.    

    

* Phosphines on Colloidal Nickel Nanocatalysts to Lower the Onset Temperature of Terminal Alkynes Hydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392162453
:TOPICS: Homogeneous Catalysis with Transition Metals, Catalytic Reduction of Nitro Compounds, Engineering of Surface Nanostructures
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00054")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392162453"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392162453"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392162453"))][Get cited by]]

OpenAlex: https://openalex.org/W4392162453 (Open access: False)
    
[[https://openalex.org/A5057941203][Karim Azouzi]], [[https://openalex.org/A5087178810][Anthony Ropp]], [[https://openalex.org/A5088702558][Sophie Carenco]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00054 
     
Catalysis by colloidal suspensions of metal nanoparticles (NPs) is becoming more and more attractive as it may combine mild reaction conditions with the use of organic ligands as surface modifiers. While most examples focus on increasing the selectivity of the catalytic process, there is also an opportunity to use the ligands to boost the conversion and trigger the onset of activity at a temperature where NPs alone would not be active. This may be achieved because the ligands modify the electronic and steric environments at the surface active site. In this work, we show that phosphines with adequate steric hindrance (e.g., PnBu3 and PiBu3) lower the onset temperature for phenylacetylene hydrogenation by nickel NPs under 7 bar of H2, by ca 10 to 20 °C depending on the NP diameter. This result is not expected to have practical repercussions for the reaction at stake, as it is already well-mastered; yet, it is of conceptual value because the hydrogenation may have been driven by the frustrated Lewis pair (FLP) between the Lewis basic phosphine and the Lewis acid nickel surface, forming a so-called “NanoFLP”. We investigated this proposal using 10 phosphines and used a stereoelectronic map to rationalize their ability to boost the conversion, showing that moderately hindered and fairly donating phosphines are most adequate. Moreover, we demonstrated that less than 2 phosphines per Ni surface atom are enough for the effect to arise. We showed that other terminal alkynes, like 1-octyne, can be hydrogenated with this method. Lastly, a comparison of conversions for 5 para-substituted phenylacetylenes was used to discuss the effects of electronic donation and steric hindrance at the surface active site.    

    

* Regulation of Oxygen Activation Pathways to Optimize Photocatalytic Methane Oxidative Coupling Selectivity  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4392164219
:TOPICS: Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06016")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392164219"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392164219"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392164219"))][Get cited by]]

OpenAlex: https://openalex.org/W4392164219 (Open access: False)
    
[[https://openalex.org/A5065195802][Jiangjie Zhang]], [[https://openalex.org/A5089384187][Junhui Zhang]], [[https://openalex.org/A5082881286][Jinni Shen]], [[https://openalex.org/A5041519507][Dongmiao Li]], [[https://openalex.org/A5066416838][Jinlin Long]], [[https://openalex.org/A5048886876][Wenxin Dai]], [[https://openalex.org/A5041955281][Xuxu Wang]], [[https://openalex.org/A5066639664][Zizhong Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06016 
     
Photocatalytic oxidative coupling of methane (POCM) is a direct way for the methane transformation into ≥C2 alkanes. However, the typical oxygen activation path often leads to the formation of strong oxidizing superoxide radical (O2–) species, which makes the whole reaction face serious selectivity problems. Herein, we constructed N and oxygen vacancy dual active sites on TiO2{001} nanosheets (TiO2–NVo) to regulate the oxygen activation pathway and achieve a high activity and selectivity of photocatalytic OCM. Compared with ordinary Au/TiO2{001} nanosheets, the alkane yields of Au/TiO2–NVo are increased from 16 μmol h–1 to 32 μmol h–1, and the selectivity of alkanes increased from 61% to 93%. The performance is superior when compared with the reported till date in photocatalytic OCM in batch reactors. The superior performance originates from the unique N–Vo dual active sites for synergistically cleaving the detrimental O2– into desirable mono-oxygen active species (O·–) to suppress undesired overoxidation reaction. The formed O·– species from O2– dissociation, in turn, is active for the selective H abstraction of CH4 into •CH3 to improve the subsequent C–C coupling reaction on the Au nanocluster surface. This work provides a new approach of O2 dissociation to address the overoxidation of methane in an aerobic environment for achieving highly selective CH4 conversion.    

    
