#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Wed Dec  4 01:28:03 2024

Found 16 results from 2024-11-27 to 2024-12-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Developing Robust Ceria-Supported Catalysts for Catalytic NO Reduction and CO/Hydrocarbon Oxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404711520
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-11-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04433")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404711520"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404711520"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404711520"))][Get cited by]]

OpenAlex: https://openalex.org/W4404711520 (Open access: False)
    
[[https://openalex.org/A5039031267][Inhak Song]], [[https://openalex.org/A5108616466][Libor Kovarik]], [[https://openalex.org/A5103242318][Mark Engelhard]], [[https://openalex.org/A5076149777][János Szanyi]], [[https://openalex.org/A5100424548][Yong Wang]], [[https://openalex.org/A5065623016][Konstantin Khivantsev]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04433 
     
No abstract    

    

* Synthesis of Unsymmetrical Disulfides via Photocatalytic Hydrodisulfuration  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404718408
:TOPICS: Transition-Metal-Catalyzed Sulfur Chemistry, Innovations in Organic Synthesis Reactions, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-11-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06457")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404718408"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404718408"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404718408"))][Get cited by]]

OpenAlex: https://openalex.org/W4404718408 (Open access: False)
    
[[https://openalex.org/A5113336481][Qi-Rui Dong]], [[https://openalex.org/A5004999983][Yisen Wang]], [[https://openalex.org/A5054904297][Juan Zhang]], [[https://openalex.org/A5104306118][Honghong Chang]], [[https://openalex.org/A5101703606][Jun Tian]], [[https://openalex.org/A5071861864][Wen‐Chao Gao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06457 
     
No abstract    

    

* Pulsed Electrolysis in Membrane Electrode Assembly Architecture for Enhanced Electrochemical Nitrate Reduction Reaction to Ammonia  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404718420
:TOPICS: Ammonia Synthesis and Electrocatalysis, Materials and Methods for Hydrogen Storage, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-11-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05225")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404718420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404718420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404718420"))][Get cited by]]

OpenAlex: https://openalex.org/W4404718420 (Open access: False)
    
[[https://openalex.org/A5022239473][Ramireddy Boppella]], [[https://openalex.org/A5110308171][Maryam Ahmadi]], [[https://openalex.org/A5112828743][B Arndt]], [[https://openalex.org/A5028610828][Danielle R. Lustig]], [[https://openalex.org/A5086722511][Mohammadreza Nazemi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05225 
     
No abstract    

    

* Insight into Roles of Rare-Earth Metals in Heterobimetallic Ni–Y Bifunctional Catalysis for Alkyne Semihydrogenation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404738907
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Transition Metal Catalysis, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-11-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05093")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404738907"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404738907"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404738907"))][Get cited by]]

OpenAlex: https://openalex.org/W4404738907 (Open access: False)
    
[[https://openalex.org/A5003145603][Peifeng Su]], [[https://openalex.org/A5029680733][Huayu Liang]], [[https://openalex.org/A5059248880][Yinwu Li]], [[https://openalex.org/A5022393729][Zhuofeng Ke]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05093 
     
Due to the unique properties of rare-earth (RE) metals, RE catalysts demonstrate distinctive catalytic performance in hydrogenation and related transformations. In typical RE catalytic systems, the roles and function modes have been studied and are relevant to ligands. In recent years, heterobimetallic catalytic systems have emerged for efficient hydrogenation and related transformations. Among these systems, heterobimetallic catalysts with transition metal (TM)-RE combinations integrate the characteristics of TM catalysis and RE catalysis, exhibiting a TM-RE bifunctional effect with remarkable activity and selectivity. However, the roles of RE metals in TM-RE bifunctional catalysis remain ambiguous. This theoretical study takes the Ni–Y system as a study case, aiming to elucidate the significant roles of the RE center in the TM-RE bifunctional effect on catalytic alkyne semihydrogenation. The results suggest that dynamic coordination can occur at the Y center due to its large size and coordination ability, which accepts the binding of phosphine groups of the ligand. The dynamic coordination of phosphine groups to the large-size RE center assists the Ni center in releasing vacant sites for substrate in-cage binding and reduces the steric effect on the Ni center. Meanwhile, the Lewis acidic RE center can stabilize the bridging hydride, which is crucial for H2 activation and hydrogenation. The TM-RE bifunctional effect promotes the reaction. During the H2 activation stage, due to the stabilization of nickel hydrides by yttrium, the fac-pathway is more favored. The Ni–H–Y bridging structure is maintained during the initial hydride insertion in the semihydrogenation stage, which is crucial for the reaction. Additionally, the use of the more active terminal hydride makes the terminal hydride pathway a more plausible mechanism. Benefiting from the capability of yttrium to accept the dynamic coordination of phosphine groups, thereby releasing steric hindrance and stabilizing the bridging hydride concurrently, (Z)/(E)-isomerization can proceed to achieve (E)-selectivity through the H2-assisted Ni–Y bifunctional pathway with a relatively low energy barrier. Owing to the RE-bridging hydride stabilization effect, the thermodynamic properties of intermediates are closely related to the size of the RE metal center, thereby influencing the activity and the (Z)/(E)-selectivity. These results underscore the important roles of the RE center in TM-RE bifunctional catalysis, offering valuable insights into the future design of effective bifunctional TM-RE catalysts.    

    

* Effective Synthesis of 5-Amino-1-pentanol via Selective Hydrogenolysis of Biomass-Derived Furfurylamine on Supported Platinum Catalysts at Ambient Temperature  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404740052
:TOPICS: Catalytic Conversion of Biomass to Fuels and Chemicals, Homogeneous Catalysis with Transition Metals, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-11-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05122")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404740052"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404740052"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404740052"))][Get cited by]]

OpenAlex: https://openalex.org/W4404740052 (Open access: False)
    
[[https://openalex.org/A5100451569][Guoliang Li]], [[https://openalex.org/A5100450964][Tong Wang]], [[https://openalex.org/A5046743641][Cheng‐Bin Hong]], [[https://openalex.org/A5100782473][Haichao Liu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05122 
     
5-Amino-1-pentanol (APO) is an important nitrogen-containing chemical with versatile applications. However, its synthesis is still not efficient. Here, we report the synthesis of APO from biomass-derived furfurylamine (FAM) via the direct cleavage of its α–C–O bond neighboring the −CH2NH2 group at ambient temperature. Pt/TiO2 catalysts exhibited high efficiency and stability in the FAM hydrogenolysis to APO, affording a high yield of 85.4% at 30 °C and 2.0 MPa of H2 in water. The high efficiency of Pt/TiO2 was found to be related to its superior activity for the cleavage of the α–C–O bond in FAM, relative to the hydrogenation of the furan ring on the corner and edge sites of the Pt surfaces. This work provides a viable approach for the precise cleavage of the α–C–O bond neighboring the −CH2NH2 group in the furan ring under mild conditions toward the efficient production of APO and its derivatives.    

    

* Boosting Catalytic Hydrogen Transfer Cascade Reactions via Tandem Catalyst Design by Coupling Co Single Atoms with Adjacent Co Clusters  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404749349
:TOPICS: Homogeneous Catalysis with Transition Metals, Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-11-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05569")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404749349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404749349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404749349"))][Get cited by]]

OpenAlex: https://openalex.org/W4404749349 (Open access: False)
    
[[https://openalex.org/A5014020324][Zhanwei Chen]], [[https://openalex.org/A5060113464][Shaowei Yang]], [[https://openalex.org/A5013850621][Jie Yang]], [[https://openalex.org/A5079869008][Bo Zhang]], [[https://openalex.org/A5064335105][Hao Jiang]], [[https://openalex.org/A5112995046][Runze Gao]], [[https://openalex.org/A5057284055][Tianshuai Wang]], [[https://openalex.org/A5100653692][Qiuyu Zhang]], [[https://openalex.org/A5101820889][Hepeng Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05569 
     
The catalytic hydrogen transfer (CHT) cascade reaction coupling alcohols with nitro compounds to synthesize imines is highly significant due to its remarkable efficiency and atom economy. However, the complicated multistep reaction process makes single-site catalysts exhibit unsatisfactory catalytic performance for the CHT cascade reaction. Herein, inspired by the findings of DFT calculations that Co nanocluster (CoNC) and Co single atom (CoSA) can act as the optimal active sites for alcohol oxidation and nitro reduction, respectively, one dual-active site catalyst (CoSA-CoNC/CN), containing CoSA and CoNC sites, was synthesized by a two-step vacuum pyrolysis strategy. Benefiting from the relay-like tandem catalysis of CoNC and CoSA, CoSA-CoNC/CN achieved an impressive 93% nitrobenzene conversion and 99% imine selectivity at 160 °C in 4 h, with a record turnover frequency of 20.9 h–1. This work provides insights into the functions of single-atom and nanocluster active sites in the CHT cascade reaction and sheds light on the rational preparation of tandem catalysts.    

    

* Catalytic Mechanism of SARS-CoV-2 3-Chymotrypsin-Like Protease as Determined by Steady-State and Pre-Steady-State Kinetics  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404762047
:TOPICS: Computational Methods in Drug Discovery, Protein Structure Prediction and Analysis, Applications of Calorimetry in Scientific Research
:PUBLICATION_DATE: 2024-11-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c04695")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404762047"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404762047"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404762047"))][Get cited by]]

OpenAlex: https://openalex.org/W4404762047 (Open access: True)
    
[[https://openalex.org/A5033301027][Jiyun Zhu]], [[https://openalex.org/A5112014009][A. Kemp]], [[https://openalex.org/A5012183857][Balachandra Chenna]], [[https://openalex.org/A5100713291][Vivek Kumar]], [[https://openalex.org/A5058154405][Andrew Rademacher]], [[https://openalex.org/A5010140916][Sangho Yun]], [[https://openalex.org/A5040763385][Arthur Laganowsky]], [[https://openalex.org/A5047649241][Thomas D. Meek]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c04695 
     
No abstract    

    

* The Corrosive Cl–-Induced Rapid Surface Reconstruction of Amorphous NiFeCoP Enables Efficient Seawater Splitting  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404772438
:TOPICS: Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-11-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05704")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404772438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404772438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404772438"))][Get cited by]]

OpenAlex: https://openalex.org/W4404772438 (Open access: False)
    
[[https://openalex.org/A5105140561][Yang Yu]], [[https://openalex.org/A5010613556][Wei Zhou]], [[https://openalex.org/A5016504923][Xiaohan Zhou]], [[https://openalex.org/A5111358811][Junshu Yuan]], [[https://openalex.org/A5087336958][Xuewei Zhang]], [[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5100379859][Jingyu Li]], [[https://openalex.org/A5103225231][Xiaoxiao Meng]], [[https://openalex.org/A5046799805][Fei Sun]], [[https://openalex.org/A5088144354][Jihui Gao]], [[https://openalex.org/A5102280725][Guangbo Zhao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05704 
     
No abstract    

    

* Photocatalytic Conversion of Biomass and Nitrate into Glycine  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404799850
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-11-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05235")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404799850"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404799850"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404799850"))][Get cited by]]

OpenAlex: https://openalex.org/W4404799850 (Open access: False)
    
[[https://openalex.org/A5004242502][Peifeng Li]], [[https://openalex.org/A5058707346][Biaobiao Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05235 
     
No abstract    

    

* Effectively Regulating Electrooxidation of Formic Acid over Bimetallic PtCo Alloys via the Integration of Theory and Experiment  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404831841
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-11-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06198")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404831841"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404831841"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404831841"))][Get cited by]]

OpenAlex: https://openalex.org/W4404831841 (Open access: False)
    
[[https://openalex.org/A5089966981][Zhikeng Zheng]], [[https://openalex.org/A5107948717][Bin Liu]], [[https://openalex.org/A5087450897][Jiaxiang Qiu]], [[https://openalex.org/A5025279061][Shaojun Xu]], [[https://openalex.org/A5108137949][Yuchen Wang]], [[https://openalex.org/A5100353061][Man Zhang]], [[https://openalex.org/A5100343468][Ke Li]], [[https://openalex.org/A5049586106][Zhongti Sun]], [[https://openalex.org/A5100728531][Ziang Li]], [[https://openalex.org/A5060400342][Yangyang Wan]], [[https://openalex.org/A5042572313][C. Richard A. Catlow]], [[https://openalex.org/A5063084241][Kai Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06198 
     
No abstract    

    

* Kinetic Analysis of Cyclization by the Substrate-Tolerant Lanthipeptide Synthetase ProcM  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404834790
:TOPICS: Natural Products as Sources of New Drugs, Ribosome Structure and Translation Mechanisms, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-11-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404834790"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404834790"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404834790"))][Get cited by]]

OpenAlex: https://openalex.org/W4404834790 (Open access: False)
    
[[https://openalex.org/A5021271255][Emily K. Desormeaux]], [[https://openalex.org/A5114876563][Garrett J. Barksdale]], [[https://openalex.org/A5067523147][Wilfred A. van der Donk]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06216 
     
No abstract    

    

* Comprehensive Investigations of MUC1 O-Glycosylation Process Reveal Initial Site Preference by the Polypeptide GalNAc Transferases  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404843611
:TOPICS: Glycosylation in Health and Disease, Chemical Glycobiology and Therapeutic Applications, Nucleotide Metabolism and Enzyme Regulation
:PUBLICATION_DATE: 2024-11-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c05719")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404843611"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404843611"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404843611"))][Get cited by]]

OpenAlex: https://openalex.org/W4404843611 (Open access: False)
    
[[https://openalex.org/A5100399297][Han Zhang]], [[https://openalex.org/A5077812141][Kaiyuan Song]], [[https://openalex.org/A5104337377][Yihan Liu]], [[https://openalex.org/A5102905625][Fang Yang]], [[https://openalex.org/A5040806192][Congcong Lu]], [[https://openalex.org/A5113300033][Rumeng Wei]], [[https://openalex.org/A5024972473][Zhijue Xu]], [[https://openalex.org/A5008414706][Xia Zou]], [[https://openalex.org/A5075529271][Liang Lin]], [[https://openalex.org/A5108406881][Ting Shi]], [[https://openalex.org/A5075688047][Lin‐Tai Da]], [[https://openalex.org/A5100456242][Yan Zhang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c05719 
     
No abstract    

    

* Tailoring Surface and Penetrating Carbon in Fe-Based Catalysts to Balance the Activity and Stability of Fischer–Tropsch Synthesis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404857137
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Desulfurization Technologies for Fuels, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-11-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404857137"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404857137"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404857137"))][Get cited by]]

OpenAlex: https://openalex.org/W4404857137 (Open access: False)
    
[[https://openalex.org/A5091368247][Xiaoxue Han]], [[https://openalex.org/A5075318509][Shouying Huang]], [[https://openalex.org/A5012547244][Chongyang Wei]], [[https://openalex.org/A5016211182][Haoting Liang]], [[https://openalex.org/A5101730489][Jing Lv]], [[https://openalex.org/A5065841119][Yue Wang]], [[https://openalex.org/A5041578170][Mei‐Yan Wang]], [[https://openalex.org/A5038325575][Yong Wang]], [[https://openalex.org/A5100689682][Xinbin Ma]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06014 
     
No abstract    

    

* Enantioselective Transformation of Hydrazones via Remote NHC Catalysis: Activation Across C═N and N–N Bonds  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404877553
:TOPICS: N-Heterocyclic Carbenes in Catalysis and Materials Chemistry, Transition Metal-Catalyzed Cross-Coupling Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization
:PUBLICATION_DATE: 2024-11-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404877553"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404877553"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404877553"))][Get cited by]]

OpenAlex: https://openalex.org/W4404877553 (Open access: False)
    
[[https://openalex.org/A5008560620][Jiamiao Jin]], [[https://openalex.org/A5110163098][Ya Lv]], [[https://openalex.org/A5071961275][Wenli Tang]], [[https://openalex.org/A5070239905][Kunpeng Teng]], [[https://openalex.org/A5102115055][Yixian Huang]], [[https://openalex.org/A5101073339][Jingxin Ding]], [[https://openalex.org/A5100416500][Tingting Li]], [[https://openalex.org/A5101487052][Guanjie Wang]], [[https://openalex.org/A5056403313][Yonggui Robin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06029 
     
The catalytic asymmetric transformation of nitrogen atoms to prepare heterocyclic molecules is of significant value in organic synthesis and biological applications. Here, we disclose the activation of the nitrogen atom in hydrazine-derived hydrazone via an N-heterocyclic carbene (NHC) organic catalyst for highly enantioselective formal cycloaddition reactions. The range of NHC catalysis extends across several (carbon and hetero) atoms and diverse chemical bonds (C═N and N–N bonds) to activate nitrogen atoms at remote sites with excellent reactivity and (stereo)selectivity control. Our strategy for nitrogen atom activation, along with the NHC-bound diaza-diene intermediate generated during the catalytic process, offers alternative solutions for organic synthesis.    

    

* Correction to “Uncovering Hydroxynitrile Lyase Variants with Promiscuous Diastereoselective Nitroaldolase Activity toward the Highly Stereocontrolled Synthesis of Anti β-Nitroalcohols”  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404905332
:TOPICS: Chemical Glycobiology and Therapeutic Applications, Amino Acid Transport and Metabolism in Health and Disease, Role of Fluorine in Medicinal Chemistry and Pharmaceuticals
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06888")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404905332"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404905332"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404905332"))][Get cited by]]

OpenAlex: https://openalex.org/W4404905332 (Open access: True)
    
[[https://openalex.org/A5114944281][Ayon Chaterjee]], [[https://openalex.org/A5107869341][G. Priyanka]], [[https://openalex.org/A5017053564][N. Prakash Prabhu]], [[https://openalex.org/A5019648537][Santosh Kumar Padhi]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06888  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c06888?ref=article_openPDF][pdf]])
     
InfoMetricsFiguresRef.SI ACS CatalysisASAPArticle This publication is free to access through this site. Learn More CiteCitationCitation and abstractCitation and referencesMore citation options ShareShare onFacebookX (Twitter)WeChatLinkedInRedditEmailJump toExpandCollapse ORIGINAL ARTICLE. This notice is a correction.Addition/CorrectionDecember 2, 2024Correction to "Uncovering Hydroxynitrile Lyase Variants with Promiscuous Diastereoselective Nitroaldolase Activity toward the Highly Stereocontrolled Synthesis of Anti β-Nitroalcohols"Click to copy article linkArticle link copied!Ayon ChaterjeeAyon ChaterjeeMore by Ayon ChaterjeeG. PriyankaG. PriyankaMore by G. PriyankaN. Prakash PrabhuN. Prakash PrabhuMore by N. Prakash Prabhuhttps://orcid.org/0000-0002-3024-1142Santosh Kumar Padhi*Santosh Kumar PadhiMore by Santosh Kumar Padhihttps://orcid.org/0000-0001-5202-6702Open PDFSupporting Information (1)ACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 18406–18407Click to copy citationCitation copied!https://pubs.acs.org/doi/10.1021/acscatal.4c06888https://doi.org/10.1021/acscatal.4c06888Published December 2, 2024 Publication History Received 8 November 2024Published online 2 December 2024correction© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsThis publication is licensed for personal use by The American Chemical Society. ACS Publications© 2024 American Chemical SocietyIt has come to our attention that the kinetic parameters were erroneously calculated during the change of their units from the data presented in the Supporting Information to the main article. While the Supporting Information correctly represented the kinetic parameters (Figure S76 and Figure S77), the units (KM in mM, kcat in min–1, and kcat /KM in min–1 mM–1) are different from those in the main article (Table 1, Page 12626). The corrected Table 1 and its corresponding description (Kinetic Studies, Page 12629) (corrections are in bold) as well as the corrected sections of the Supporting Information (Figure S76 and Figure S77) are provided with this Correction. It is important to note that these modified parameters do not impact any of the conclusions drawn in the original article.In addition, we erroneously typed T14 to represent the Y14 in Figure S85A and Figure S86A of the Supporting Information. The corrected figures are provided in the Supporting Information with this Correction.Kinetic StudiesClick to copy section linkSection link copied!In order to gain insights of kinetics information about the DHR, both the variants, Y14C and Y14A, along with the wild-type enzyme were taken for evaluation. The steady-state kinetic parameters of Y14C toward the synthesis of (1R,2S)-1a were determined by measuring the initial velocities against different concentrations of 1. In comparison to the wild-type, Y14C exhibited >88-fold improved kcat, and ∼3-fold reduced KM (Table 1, Figure S77A,B). The single variant elicited a remarkable increase in catalytic efficiency of >250-fold than the wild-type, as kcat/KM of Y14C and the wild-type were found to be 5.01 and 0.02 s–1 M–1, respectively. The kinetic parameters for Y14A toward (1R,2S)-9b were kcat = 0.06 s–1, KM = 40.2 mM (Table 1, Figure S77C). Selection of 9 for this study was based on the highest catalytic activity and stereoselectivity of Y14A achieved during asymmetric addition of 1-nitropropane to this substrate (Figure 4). Unfortunately, the kinetic data of the wild-type was not possible to measure toward the synthesis of 9b due to its extremely low activity. The catalytic efficiency (kcat/KM) of Y14A was found to be 1.49 s–1 M–1. Even though it is unfair to compare, the catalytic efficiency of Y14A toward (1R,2S)-9b, which is assumed to be highest among the molecules of Figure 4, appeared to be ∼3.5-fold less than the catalytic efficiency of Y14C toward the synthesis of 1a. The former case has demonstrated a ∼2-fold reduced kcat along with increased KM compared with data for the latter. This explains the overall reduced biocatalytic conversion to 1-nitropropane based β-nitroalcohols as compared to nitroethane based β-nitroalcohols. Due to lack of similar data the kinetics parameters could not be compared with other HNLs. However, the catalytic efficiency (kcat/KM) of Y14C catalyzed synthesis of 1a is >580-fold and Y14A catalyzed synthesis of 9b is >720-fold lower than the catalytic efficiency of one of the best AtHNL variants (F179N) toward nitromethane addition to 1 or 9.70 This suggests that stereoselective addition of longer nitroalkanes remains a challenge despite the use of the same aldehyde, 1 in the asymmetric Henry reaction.Table 1. Kinetic Data of Wild-Type AtHNL and Variants toward 1a and 9b SynthesisaEnzymeAldehydeNucleophilepHKM (mM)kcat (s–1)kcat/KM (s–1 M–1)wild-type1a5.570.12 ± 5.931.4 × 10–3 ± 7.6 × 10–50.02 ± 0.001Y14C1a5.525.14 ± 3.470.126 ± 0.0195.01 ± 0.16Wild-type1a8.276.85 ± 2.665.2 × 10–4 ± 7 × 10–50.0068 ± 0.0009Y14C1a8.256.87 ± 3.820.38 ± 0.0426.6 ± 0.73Wild-type9b5.5ndndndY14A9b5.540.2 ± 2.880.06 ± 0.0041.49 ± 0.1aThe Michaelis–Menten plots are shown in Figures S77 and S78. Each value represents the average of three independent measurements. nd: not determined.Supporting InformationClick to copy section linkSection link copied!The Supporting Information is available free of charge at https://pubs.acs.org/doi/10.1021/acscatal.4c06888.Corrected versions of Figures S77, S78, S85, and S86 (PDF)cs4c06888_si_001.pdf (125.89 kb) Terms & Conditions Most electronic Supporting Information files are available without a subscription to ACS Web Editions. Such files may be downloaded by article for research use (if there is a public use license linked to the relevant article, that license may permit other uses). Permission may be obtained from ACS for other uses through requests via the RightsLink permission system: http://pubs.acs.org/page/copyright/permissions.html. Author InformationClick to copy section linkSection link copied!Corresponding AuthorSantosh Kumar Padhi; https://orcid.org/0000-0001-5202-6702; Email: AuthorsAyon ChaterjeeG. PriyankaN. Prakash Prabhu; https://orcid.org/0000-0002-3024-1142Cited By Click to copy section linkSection link copied!This article has not yet been cited by other publications.Download PDFFiguresReferencesSupporting Information Get e-AlertsGet e-AlertsACS CatalysisCite this: ACS Catal. 2024, 14, XXX, 18406–18407Click to copy citationCitation copied!https://doi.org/10.1021/acscatal.4c06888Published December 2, 2024 Publication History Received 8 November 2024Published online 2 December 2024© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsArticle Views-Altmetric-Citations-Learn about these metrics closeArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated.Recommended Articles FiguresReferencesSupporting InfoThis publication has no figures.This publication has no References.Supporting InformationSupporting InformationThe Supporting Information is available free of charge at https://pubs.acs.org/doi/10.1021/acscatal.4c06888.Corrected versions of Figures S77, S78, S85, and S86 (PDF)cs4c06888_si_001.pdf (125.89 kb) Terms & Conditions Most electronic Supporting Information files are available without a subscription to ACS Web Editions. Such files may be downloaded by article for research use (if there is a public use license linked to the relevant article, that license may permit other uses). Permission may be obtained from ACS for other uses through requests via the RightsLink permission system: http://pubs.acs.org/page/copyright/permissions.html.    

    

* Controlling Cubic versus Octahedral Morphology in Plasmonic Aluminum Nanoparticle Synthesis with Titanocene Catalysts: A Systematic Study  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4404913495
:TOPICS: Plasmonic Nanoparticles: Synthesis, Properties, and Applications, Formation and Properties of Nanocrystals and Nanostructures, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c06286")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404913495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404913495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404913495"))][Get cited by]]

OpenAlex: https://openalex.org/W4404913495 (Open access: False)
    
[[https://openalex.org/A5012050880][Jae‐Kwan Kim]], [[https://openalex.org/A5047514009][Christian R. Jacobson]], [[https://openalex.org/A5069086177][Naomi J. Halas]], [[https://openalex.org/A5083700647][Ian A. Tonks]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c06286 
     
Ti precatalysts containing the titanocene moiety (Cp2Ti–, Cp = cyclopentadienyl) can, under certain conditions, selectively produce cubic Al nanocrystals through the dehydrocoupling of alane amine adducts such as AlH3·NMe2Et. A systematic study of reaction conditions reveals that cubic Al nanoparticle formation occurs at a higher temperature (e.g., 65 °C) and/or higher catalyst-concentration conditions (e.g., 0.5 mol % [Ti]). Kinetic studies reveal that under these conditions nanoparticle formation and alane consumption are much faster, and cubic nanoparticle formation takes place under kinetically controlled conditions. On the other hand, employing a wide suite of TiX4 (X = anionic ligand)-type precatalysts yielded only octahedral-shaped aluminum nanoparticles regardless of conditions. Finally, we report the synthesis of a hydride-bridged Ti–Al heterobimetallic compound from the reaction of Cp2TiCl2 with AlH3·NMe2Et and characterized it to show that it is a reaction intermediate in the Ti-catalyzed aluminum nanoparticle synthesis.    

    
