#+TITLE: ACS Catalysis
Description: Articles from ACS Catalysis
Created on Mon Apr  8 15:20:39 2024

Found 25 results from 2024-04-01 to 2024-04-08
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=primary_location.source.id%3Ahttps%3A//openalex.org/S37391459]]

* Tunable Divergent Reactivity of Aziridinium Ylides in the Synthesis of Complex Piperidines and Azetidines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393372078
:TOPICS: Catalytic C-H Amination Reactions, Transition-Metal-Catalyzed C–H Bond Functionalization, Catalytic Carbene Chemistry in Organic Synthesis
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06173")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393372078"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393372078"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393372078"))][Get cited by]]

OpenAlex: https://openalex.org/W4393372078 (Open access: False)
    
[[https://openalex.org/A5063494151][Mahzad Dehghany]], [[https://openalex.org/A5033112655][Giuliana Pavaneli]], [[https://openalex.org/A5093551048][Jacob W. Kailing]], [[https://openalex.org/A5087213395][Olivia M. Duke]], [[https://openalex.org/A5040701048][Ilia A. Guzei]], [[https://openalex.org/A5069102842][Caroline Da Ros Montes D’Oca]], [[https://openalex.org/A5009883474][Israel Fernández]], [[https://openalex.org/A5047518130][Jennifer M. Schomaker]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06173 
     
Nitrogenated heterocycles comprise the cores of a number of synthetically useful compounds, including pharmaceuticals, bioactive natural products, agrochemicals, and other drug-like molecules. The widespread interest in methods to increase the fraction of sp3 carbon atoms (Fsp3) of drug-like scaffolds in a stereocontrolled manner, while enabling explorations of unusual amine chemical space, inspired our efforts to tune the reactivity of aziridinium ylides. A sequential nitrene–carbene transfer of simple allenes leads to divergent product outcomes depending on the nature of the carbene precursor, furnishing products of different ring sizes. In addition, the catalyst control over the ring size via proposed hydrogen-bonding interactions between the catalyst and substrate was explored. Computational studies were employed to gain insight into the major features of substrates and catalysts that influence the tunable reactivity of aziridinium ylide intermediates formed in this chemistry.    

    

* Efficient Visible-Light-Driven Water Oxidation by a Carbon Nitride Modified with Cobalt Polyoxometalate Molecular Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393373284
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00627")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393373284"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393373284"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393373284"))][Get cited by]]

OpenAlex: https://openalex.org/W4393373284 (Open access: False)
    
[[https://openalex.org/A5007596741][Yoshihiko Tomita]], [[https://openalex.org/A5044251519][Natsuki Taira]], [[https://openalex.org/A5066627191][Ken Sakai]], [[https://openalex.org/A5051285636][Hidetoshi Ozawa]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00627 
     
No abstract    

    

* Competing Mechanisms in Palladium-Catalyzed Alkoxycarbonylation of Styrene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393375769
:TOPICS: Transition Metal Catalysis, Homogeneous Catalysis with Transition Metals, Transition Metal-Catalyzed Cross-Coupling Reactions
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00966")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393375769"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393375769"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393375769"))][Get cited by]]

OpenAlex: https://openalex.org/W4393375769 (Open access: True)
    
[[https://openalex.org/A5008238212][Jaya Mehara]], [[https://openalex.org/A5066130884][Mariarosa Anania]], [[https://openalex.org/A5084478574][Pavel Kočovský]], [[https://openalex.org/A5021283178][Jana Roithová]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00966  ([[https://pubs.acs.org/doi/pdf/10.1021/acscatal.4c00966][pdf]])
     
No abstract    

    

* Active Hydrogen-Switchable Dynamic Oxygen Vacancies in MoO3–x upon Ru Nanoparticle Decoration for Boosting Photocatalytic Ammonia Synthesis Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393376514
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05633")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393376514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393376514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393376514"))][Get cited by]]

OpenAlex: https://openalex.org/W4393376514 (Open access: False)
    
[[https://openalex.org/A5070961992][Lulu Zhang]], [[https://openalex.org/A5081675173][Rui Li]], [[https://openalex.org/A5076944433][Lijun Guo]], [[https://openalex.org/A5028973201][Longzhe Cui]], [[https://openalex.org/A5056249472][Xiaochao Zhang]], [[https://openalex.org/A5035024640][Yawen Wang]], [[https://openalex.org/A5023466237][Yunfang Wang]], [[https://openalex.org/A5053777989][Xuan Jian]], [[https://openalex.org/A5049164708][Xiaoming Gao]], [[https://openalex.org/A5056458711][Caimei Fan]], [[https://openalex.org/A5000168358][Jiancheng Wang]], [[https://openalex.org/A5032796616][Jianxin Liu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05633 
     
No abstract    

    

* Promoting Electrocatalytic Semihydrogenation of Alkynols to Alkenols over a Bimetallic CuAu Alloy Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393377866
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05928")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393377866"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393377866"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393377866"))][Get cited by]]

OpenAlex: https://openalex.org/W4393377866 (Open access: False)
    
[[https://openalex.org/A5018042445][Qinghui Ren]], [[https://openalex.org/A5077447092][Leilei Hao]], [[https://openalex.org/A5042488059][Jiangrong Yang]], [[https://openalex.org/A5074608575][Mengyu Lv]], [[https://openalex.org/A5063892110][Hua Zhou]], [[https://openalex.org/A5079317579][Zhenhua Li]], [[https://openalex.org/A5066410903][Haohong Duan]], [[https://openalex.org/A5062633224][Mingfei Shao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05928 
     
Electrocatalytic semihydrogenation of alkynols to alkenols under ambient conditions using H2O as a hydrogen source is highly attractive in synthetic chemistry. However, it is still challenging to achieve a high Faradaic efficiency (FE) in a wide potential window. Herein, we reported a bimetallic Cu3Au alloy as an efficient catalyst for electrocatalytic semihydrogenation of alkynols to alkenols. Specifically, during semihydrogenation of 2-butyne-1,4-diol (BYD) to 2-butene-1,4-diol (BED), the Cu3Au catalyst achieves 12.6-fold greater reaction rate and higher FE compared with pure Cu (99 vs 63%). Moreover, the Cu3Au maintains >96% FEs in a wide potential window from −0.19 to −0.59 V vs RHE. We demonstrate that the competitive adsorptions of reactive hydrogen (H*) and BYD greatly influence the semihydrogenation processes. The presence of Au in Cu3Au facilitates H* formation and reduces BYD adsorption on Cu, thus enhancing the BYD hydrogenation performance. The Cu3Au catalyst affords a broad substrate scope from alkynols to aromatic alkynes, producing the corresponding alkenes in good selectivities. Finally, we coupled BYD semihydrogenation with glycerol oxidation to replace oxygen evolution reaction in a two-electrode system, showing 40% energy saving at 200 mA for BED production and coproduction of valuable formate at the anode, demonstrating an economical manner.    

    

* Boosting Carrier Separation on a BiOBr/Bi4O5Br2 Direct Z-Scheme Heterojunction for Superior Photocatalytic Nitrogen Fixation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393381136
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06169")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393381136"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393381136"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393381136"))][Get cited by]]

OpenAlex: https://openalex.org/W4393381136 (Open access: False)
    
[[https://openalex.org/A5060888510][Huiqing Wang]], [[https://openalex.org/A5023677466][Zhuohua Chen]], [[https://openalex.org/A5000546225][Yaru Shang]], [[https://openalex.org/A5069916990][Chade Lv]], [[https://openalex.org/A5047452249][Xuhan Zhang]], [[https://openalex.org/A5081362412][Fei Li]], [[https://openalex.org/A5084680669][Qunzeng Huang]], [[https://openalex.org/A5049402435][Xiaodi Liu]], [[https://openalex.org/A5048645240][Wenmin Liu]], [[https://openalex.org/A5085868420][Liang Zhao]], [[https://openalex.org/A5009243555][Liqun Ye]], [[https://openalex.org/A5048668242][Hongmei Xie]], [[https://openalex.org/A5031653081][Xiaoli Jin]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06169 
     
Photocatalytic dinitrogen (N2) fixation is regarded as an achievable technology for ammonia (NH3) production. However, the poor separation efficiency of the photoinduced carriers and ineffective N2 activation remain grand obstacles to high-performance NH3 photosynthesis. Designing advanced heterostructured systems to accelerate charge separation and activate the N2 molecule is a feasible strategy to optimize the photocatalytic N2 fixation activity. Herein, a direct Z-scheme configuration is established between BiOBr and Bi4O5Br2 through a facile one-step solvothermal reaction. This configuration enables effective spatial separation of electron–hole pairs and preserves the robust redox ability of carriers, concurrently promoting N≡N bond activation and diminishing the energy barrier for the rate-determining step. The formation of direct Z-scheme BiOBr/Bi4O5Br2 heterojunctions is mostly attributed to the similarities in their lattice structures and crystal growth conditions. As a result, the direct Z-scheme BiOBr/Bi4O5Br2 heterojunction exhibits a high NH3 yield of 66.87 μmol g–1 h–1 without using sacrificing reagents, surpassing that of the pristine BiOBr and Bi4O5Br2 by approximately 3.3 and 5.6 times, respectively. This study provides an achievable approach to construct direct Z-scheme heterojunction systems for implementing high-performance N2 fixation under mild conditions.    

    

* Recent Advances in Catalytic Nitrogen–Nitrogen Bond Formation Reactions  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393385196
:TOPICS: Ammonia Synthesis and Electrocatalysis, Homogeneous Catalysis with Transition Metals, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00718")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393385196"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393385196"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393385196"))][Get cited by]]

OpenAlex: https://openalex.org/W4393385196 (Open access: False)
    
[[https://openalex.org/A5070559660][Jianglin Hu]], [[https://openalex.org/A5069099445][Yichen Wu]], [[https://openalex.org/A5088454186][Ying Gao]], [[https://openalex.org/A5036752566][Yinglei Wang]], [[https://openalex.org/A5081452514][Peng Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00718 
     
The lack of effective strategies for direct construction of nitrogen–nitrogen bonds has hampered developments in the synthesis and application of molecules containing hydrazine or azo motifs. Attracted by their properties both in material science and in medicinal chemistry, more and more attention has been drawn to this area, resulting in fast growth in the design and synthesis of azaheterocycles and substituted hydrazines. This review focuses on efficient catalytic approaches toward the formation of N–N and N═N bonds through different strategies, including oxidative dehydrogenation, nitrene-transfer reaction, reductive coupling, and some other recently developed methods.    

    

* General Reaction Network Exploration Scheme Based on Graph Theory Representation and Depth First Search Applied to CO2 Hydrogenation on Pd2Cu Catalyst  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393385723
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00067")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393385723"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393385723"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393385723"))][Get cited by]]

OpenAlex: https://openalex.org/W4393385723 (Open access: False)
    
[[https://openalex.org/A5058688901][Hui Guo]], [[https://openalex.org/A5052109054][Hong Zhu]], [[https://openalex.org/A5080845219][Guan-Zhang Liu]], [[https://openalex.org/A5010412191][Zhao-Xu Chen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00067 
     
Reaction mechanisms are at the core of understanding reaction systems and designing high-performance catalysts. A complex reaction system often involves various species and elementary reactions, posing a great challenge to determining the reaction mechanism. Here, we proposed a scheme to automatically generate reaction intermediates and elementary reactions to construct a complete reaction network represented by graph theory and employed a depth first search algorithm in the scheme to prune the reaction network to reduce the complexity of the network. With this scheme, microkinetic simulations of CO2 hydrogenation on Pd2Cu using the barriers predicted with the linear thermodynamics–kinetics relations were performed on the network to determine the mechanism and rate- and selectivity-controlling steps of CO2 hydrogenation to ethanol and methanol. Analysis shows that the simulated selectivity of ethanol and methanol agrees well with the experimental results. CO2 + H → COOH is the rate-controlling step, and CHOH + H → CH + H2O, CH2OH + H → CH2 + H2O, and CH2OH + H → CH3OH dominate the ethanol selectivity. Both ethanol and methanol are generated via multiple reaction pathway mechanisms. Investigations of the pruned networks show that quantitatively correct results can be obtained from the pruned or pseudocomplete reaction network, as long as the key pathways are embodied in the network. 94% ethanol selectivity of the complete network can be obtained with the pruned network composed of 60 elementary steps, compared to 176 steps of the complete network. The present work articulates graph theory representation, depth first search algorithm, linear thermodynamics–kinetics relations, and microkinetic simulations to approach complicated heterogeneous reaction systems and exemplifies their comprehensive roles in exploring complex reaction networks.    

    

* Spin Selectivity Induced by the Interface Effect for Boosted Water Oxidation  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393386676
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00142")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393386676"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393386676"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393386676"))][Get cited by]]

OpenAlex: https://openalex.org/W4393386676 (Open access: False)
    
[[https://openalex.org/A5001486972][Zhigao Xue]], [[https://openalex.org/A5024191579][Biao Wu]], [[https://openalex.org/A5088888083][Zheng Zhang]], [[https://openalex.org/A5080998702][Ching-Yu Lin]], [[https://openalex.org/A5022974076][Xiaopeng Li]], [[https://openalex.org/A5056768519][Qiuju Zhang]], [[https://openalex.org/A5085180749][Kai Tao]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00142 
     
Creating highly effective electrocatalysts for the oxygen evolution reaction (OER) holds paramount importance in advancing carbon-neutral hydrogen production through water electrolysis. Recent research highlights the crucial role of spin effects on the OER, emphasizing that the manipulation of spin polarization is a promising strategy to augment the OER kinetics. Here, we present a core–shell heterostructure electrocatalyst, which leverages the strong coupling of the interface between antiferromagnetic Co3O4 and NiFe-layered double hydroxide (NiFe-LDH) to trigger a spontaneous magnetic response enhancement, which suggests the strong double exchange interaction at the interface of the core–shell heterostructure. This electrocatalyst displays a 26-fold increase in intrinsic OER activity compared to pristine NiFe-LDH at an overpotential of 0.25 V. Through experimental and computational analyses, we find that the strong double exchange interaction within the heterostructure creates polarized spin conduction channels at the interface, which enables efficient accumulation of electrons with appropriate spin states, thereby lowering the energy barrier for the generation of triplet O2. Our work presents a promising approach to designing high-performance OER catalysts by introducing spin selectivity in traditional metal oxide electrocatalysts.    

    

* Reductive Aminomethylation Using Ammonium Formate and Methanol as N1 and C1 Source: Direct Synthesis of Mono- and Di-Methylated Amines  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393409196
:TOPICS: Homogeneous Catalysis with Transition Metals, Carbon Dioxide Utilization for Chemical Synthesis, Peptide Synthesis and Drug Discovery
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00346")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393409196"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393409196"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393409196"))][Get cited by]]

OpenAlex: https://openalex.org/W4393409196 (Open access: False)
    
[[https://openalex.org/A5016156494][Ishani Borthakur]], [[https://openalex.org/A5073045807][S. K. Nandi]], [[https://openalex.org/A5094305289][Yuvraj Bilora]], [[https://openalex.org/A5042696274][Biswajit Sadhu]], [[https://openalex.org/A5070370920][Sabuj Kundu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00346 
     
No abstract    

    

* Hydrophobic Surface Modification of Cu-Based Catalysts for Enhanced Semihydrogenation of Acetylene in Excess Ethylene  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393409197
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05466")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393409197"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393409197"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393409197"))][Get cited by]]

OpenAlex: https://openalex.org/W4393409197 (Open access: False)
    
[[https://openalex.org/A5064968189][Ting Liu]], [[https://openalex.org/A5005831427][Jinqi Xiong]], [[https://openalex.org/A5052747544][Qian Luo]], [[https://openalex.org/A5017864467][Shanjun Mao]], [[https://openalex.org/A5030325177][Yong Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05466 
     
No abstract    

    

* Revealing Catalyst Self-Adjustment in C–S Cross-Coupling through Multiscale Liquid-Phase Electron Microscopy  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393500093
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06258")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393500093"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393500093"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393500093"))][Get cited by]]

OpenAlex: https://openalex.org/W4393500093 (Open access: False)
    
[[https://openalex.org/A5047280120][Alexey S. Kashin]], [[https://openalex.org/A5022848358][D. M. Arkhipova]], [[https://openalex.org/A5009374050][Liliya T. Sahharova]], [[https://openalex.org/A5030204094][Julia V. Burykina]], [[https://openalex.org/A5053135866][Valentine P. Ananikov]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06258 
     
Carbon–carbon and carbon–heteroatom bond formation mediated by transition metals is a powerful and convenient methodology for organic synthesis. To effectively meet the demands of catalyst design, an in-depth understanding of the reaction mechanisms and pathways of active species evolution is essential. Advances in electron microscopy now offer unprecedented multilevel visualization of liquid-phase chemical systems, providing a powerful tool for mechanistic studies. In this work, we found that the use of either nickel- or copper-based catalyst precursors with preinstalled thiolate groups in combination with pyridinium ionic liquid as the reaction medium leads to a positive synergistic effect, resulting in the formation of transition metal species with high catalytic activity in the C–S cross-coupling reaction between aryl halides and thiols or disulfides. Through multiscale in situ and operando electron microscopy in the liquid phase, we elucidated the self-adjustment of the catalytic system and revealed the simultaneous emergence of metallic nanoparticles and corresponding thiolate species, leading to the independent activation of the C- and S-substrates and the subsequent elimination of the product via organic group metathesis. The proposed methodology for the catalytic preparation of aromatic organosulfides was used for the design of synthetic routes to pharmacologically important substances.    

    

* Cu–Sn Bimetallic Activated Carbon–Carbon Coupling for Efficient Furfural Electroreduction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393536047
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06346")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393536047"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393536047"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393536047"))][Get cited by]]

OpenAlex: https://openalex.org/W4393536047 (Open access: False)
    
[[https://openalex.org/A5026108994][Xiaofeng Liu]], [[https://openalex.org/A5058040690][Yuhan Sun]], [[https://openalex.org/A5041301033][Hao Ren]], [[https://openalex.org/A5041151940][Yuan Lin]], [[https://openalex.org/A5063554744][Mingbo Wu]], [[https://openalex.org/A5016932552][Zhong-Tao Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06346 
     
Electrochemically driven carbon–carbon coupling utilizing renewable electricity under ambient conditions has emerged as an innovative approach for synthesizing high-value chemicals, which still faces inherent challenges such as low conversion rates and poor selectivity. While electroreducing furfural to hydrofuroin can produce high-quality biofuel, its efficiency need to be promoted. Herein, Cu–Sn bimetallic catalyst has been developed with a conversion rate of furfural of >97% and hydrofuroin selectivity of >67% through equilibrium of the interfacial intermediate *H and *fur-CHOH, which exhibits the greatest state-of-the-art overall performance. Characterization and theoretical calculation reveal that Cu serves as the active site for generating *fur-CHOH, whose electron density can be decreased by introducing Sn, and results in a higher *fur-CHOH coverage and a lower energy barrier of dimerization. Moreover, adding Sn also enables sluggish *H formation to balance interfacial *fur-CHOH and *H, leading to reduced hydrogenation byproducts. The as-developed approach provides valuable insights for optimizing other C–C electrocoupling reactions for the synthesis of high-value chemicals.    

    

* Electrochemical Activation of Surface Oxygen for Efficient Oxidative Dehydrogenation Reaction at Elevated Temperatures  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393543441
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04731")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393543441"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393543441"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393543441"))][Get cited by]]

OpenAlex: https://openalex.org/W4393543441 (Open access: False)
    
[[https://openalex.org/A5046495634][Xiang Sun]], [[https://openalex.org/A5036055521][Heejae Yang]], [[https://openalex.org/A5013355878][Benchi Chen]], [[https://openalex.org/A5063043078][Min-Bo Zhou]], [[https://openalex.org/A5039519827][Yongjian Ye]], [[https://openalex.org/A5032155655][Xiaobao Li]], [[https://openalex.org/A5065795687][Hui Zhang]], [[https://openalex.org/A5026318943][Bo Yu]], [[https://openalex.org/A5033510515][Yifeng Li]], [[https://openalex.org/A5086565285][Jeong Woo Han]], [[https://openalex.org/A5017365002][Yan Chen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04731 
     
Oxidative dehydrogenation (ODH) of alkane with CO2 as the oxidant has attracted worldwide attention as a promising approach for simultaneously producing valuable alkenes and greenhouse gas utilization. The selectivity and yield of the produced alkene, nevertheless, require further enhancement for practical applications. In this work, taking Sr2Ti0.8Co0.6Fe0.6O6-δ (STCF) as the electrode material, we demonstrate that a solid oxide electrolysis cell (SOEC) can efficiently catalyze the ODH of ethane to ethylene on the anode and reduce CO2 to CO at the cathode. The optimal yield of ethylene reached 66.3% at 800 °C, which is among the highest values reported in the literature. Such ethane ODH activity is attributed to the activation of surface oxygen on the STCF anode by electrolytic voltage, as revealed experimentally by advanced spectroscopic techniques. The density functional theory calculation further implied that the electrochemically driven formation of active oxygen species on the STCF surface upshifts the O 2p-band center, facilitates electron transfer, and enhances surface adsorption, leading to a strongly promoted dehydrogenation process. The results clarify the critical role of oxygen activity in determining the electrochemical ODH performance and can guide the rational design of catalysts for other electrosynthesis processes.    

    

* In Situ Nitrogen Infiltration into an Ordered Pt3Co Alloy with sp–d Hybridization to Boost Fuel Cell Performance  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393715758
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06223")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393715758"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393715758"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393715758"))][Get cited by]]

OpenAlex: https://openalex.org/W4393715758 (Open access: False)
    
[[https://openalex.org/A5016071139][Mengzhao Zhu]], [[https://openalex.org/A5064487127][Huijuan Zhang]], [[https://openalex.org/A5015285184][Yanjun Hu]], [[https://openalex.org/A5009732893][Fangyao Zhou]], [[https://openalex.org/A5007104709][Xiaoping Gao]], [[https://openalex.org/A5011819769][Dayin He]], [[https://openalex.org/A5002050316][Xuyan Zhao]], [[https://openalex.org/A5021429869][Chao Zhao]], [[https://openalex.org/A5037677450][Jing Wang]], [[https://openalex.org/A5032881562][Wenan Tie]], [[https://openalex.org/A5020470912][Tian Xia]], [[https://openalex.org/A5024893590][Bo Wang]], [[https://openalex.org/A5073368369][Takeshi Yao]], [[https://openalex.org/A5090113007][Huang Zhou]], [[https://openalex.org/A5090331942][Zhe Wang]], [[https://openalex.org/A5018244700][Jin Wang]], [[https://openalex.org/A5022002423][Wenxin Guo]], [[https://openalex.org/A5022989538][Yuen Wu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06223 
     
No abstract    

    

* Advances in Bridging Homogeneous and Heterogeneous Water Oxidation Catalysis by Insolubilized Polyoxometalate Clusters  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393855529
:TOPICS: Polyoxometalate Clusters and Materials, Nanomaterials with Enzyme-Like Characteristics, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-04-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00201")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393855529"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393855529"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393855529"))][Get cited by]]

OpenAlex: https://openalex.org/W4393855529 (Open access: False)
    
[[https://openalex.org/A5051874318][Qiyu Hu]], [[https://openalex.org/A5014925611][Hongshan Zhou]], [[https://openalex.org/A5074556294][Yong Ding]], [[https://openalex.org/A5041032133][Thomas Wågberg]], [[https://openalex.org/A5000078893][Xiuxiu Han]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00201 
     
No abstract    

    

* Tuning the d-Band Center of Co3O4 via Octahedral and Tetrahedral Codoping for Oxygen Evolution Reaction  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393857012
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-04-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06256")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393857012"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393857012"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393857012"))][Get cited by]]

OpenAlex: https://openalex.org/W4393857012 (Open access: False)
    
[[https://openalex.org/A5032458772][Xiaotian Wu]], [[https://openalex.org/A5010486916][Zhiyu Shao]], [[https://openalex.org/A5024436776][Qian Zhu]], [[https://openalex.org/A5028141359][Xiangyan Hou]], [[https://openalex.org/A5039287086][Chao Wang]], [[https://openalex.org/A5068006098][Jianrong Zeng]], [[https://openalex.org/A5058587719][Keke Huang]], [[https://openalex.org/A5017830810][Shouhua Feng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06256 
     
No abstract    

    

* Controllable Diverse Construction of gem-Difluoroallylated Bicyclo[1.1.1]pentanes and Cyclobutanes from [1.1.1]Propellane via Copper Catalysis  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393858800
:TOPICS: Role of Fluorine in Medicinal Chemistry and Pharmaceuticals, Chemistry of Noble Gas Compounds and Interactions, Advancements in Density Functional Theory
:PUBLICATION_DATE: 2024-04-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00281")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393858800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393858800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393858800"))][Get cited by]]

OpenAlex: https://openalex.org/W4393858800 (Open access: False)
    
[[https://openalex.org/A5052949479][Xiao-Tian Feng]], [[https://openalex.org/A5014946456][Qiao‐Qiao Min]], [[https://openalex.org/A5058438929][Xiangfeng Zeng]], [[https://openalex.org/A5048977776][Hang Zhao]], [[https://openalex.org/A5089046226][Xingang Zhang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00281 
     
No abstract    

    

* Regeneration of NAD(P)H and its Analogues by Photocatalysis with Ionized Carbon Nitride  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393859085
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00841")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393859085"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393859085"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393859085"))][Get cited by]]

OpenAlex: https://openalex.org/W4393859085 (Open access: False)
    
[[https://openalex.org/A5056387482][Zaixiang Xu]], [[https://openalex.org/A5009976133][Zhongwei Fan]], [[https://openalex.org/A5070032604][Hanchi Chen]], [[https://openalex.org/A5067788077][Jianguo Wang]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00841 
     
The regeneration of NAD(P)H and its analogues is crucial for biocatalytic processes. However, despite the efficiency of enzymatic catalysis in regenerating NAD(P)H, the sustainability of enzymes is often compromised, particularly under extreme catalytic conditions. Moreover, artificial cofactors may present advantages in certain reactions due to their stability and versatility, yet the substrate specificity of enzymes poses significant challenges to their regeneration through the enzymatic method. Therefore, it is imperative to develop a highly stable regeneration method that can be adapted to both natural and artificial cofactors. In this work, employing potassium-ion-doped carbon nitride (ionCN-0.2) as a catalyst not only achieves high-efficiency photocatalytic regeneration of NAD(P)H, comparable to that of glucose dehydrogenase (GDH), but also a remarkable ability to regenerate nicotinamide analogues. This enhanced performance stems from the tunable negative ζ-potential, which effectively adsorbs the positively charged [Cp*Rh(bpy)H2O]2+ mediator, resulting in enhanced regeneration kinetics of the nicotinamide moiety. The catalyst demonstrates superior performance compared to the reported systems; the optimal regeneration rate reaches 0.55 mmol L–1 gcat–1 min–1 and approaches enzymatic regeneration efficiency. Expanding the reaction conditions to a wider temperature and pH range also confirms the effectiveness and sufficient stability of this photocatalytic system, offering a promising strategy for stable cofactor regeneration in biocatalytic processes.    

    

* Local Electronic Structure Modulation of Interfacial Oxygen Vacancies Promotes the Oxygen Activation Capacity of Pt/Ce1–xMxO2−δ  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393862387
:TOPICS: Catalytic Nanomaterials, Emergent Phenomena at Oxide Interfaces, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06234")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393862387"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393862387"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393862387"))][Get cited by]]

OpenAlex: https://openalex.org/W4393862387 (Open access: False)
    
[[https://openalex.org/A5005800194][Weiping Yang]], [[https://openalex.org/A5054946985][Fuyuan Qi]], [[https://openalex.org/A5021639941][Wei An]], [[https://openalex.org/A5064848623][Haochen Yu]], [[https://openalex.org/A5032099135][Shutong Liu]], [[https://openalex.org/A5028397478][Peipei Ma]], [[https://openalex.org/A5053453125][Rui Chen]], [[https://openalex.org/A5056087233][Shuangxi Liu]], [[https://openalex.org/A5035624053][Lan‐Lan Lou]], [[https://openalex.org/A5000303630][Kai Yu]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06234 
     
No abstract    

    

* Rational Design of Pd-Based Alloys for 1,3-Butadiene Selective Hydrogenation via Equilibrium Models of Nanoparticles  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393870438
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01076")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393870438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393870438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393870438"))][Get cited by]]

OpenAlex: https://openalex.org/W4393870438 (Open access: False)
    
[[https://openalex.org/A5006250732][Jin Liu]], [[https://openalex.org/A5038878717][Yihao Zhang]], [[https://openalex.org/A5054148119][Jiao Wei]], [[https://openalex.org/A5000128804][Jing Zhu]], [[https://openalex.org/A5062678004][Haoxiang Xu]], [[https://openalex.org/A5006520119][Daojian Cheng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01076 
     
No abstract    

    

* ZnO Nanowire Arrays Decorated with Cu Nanoparticles for High-Efficiency Nitrate to Ammonia Conversion  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393898872
:TOPICS: Ammonia Synthesis and Electrocatalysis, Content-Centric Networking for Information Delivery, Distributed Storage Systems and Network Coding
:PUBLICATION_DATE: 2024-04-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04398")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393898872"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393898872"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393898872"))][Get cited by]]

OpenAlex: https://openalex.org/W4393898872 (Open access: False)
    
[[https://openalex.org/A5057372027][Anlin Feng]], [[https://openalex.org/A5019180285][Yunxia Hu]], [[https://openalex.org/A5080236384][Xiaoxuan Yang]], [[https://openalex.org/A5090512624][Huaijun Lin]], [[https://openalex.org/A5046225712][Qian Wang]], [[https://openalex.org/A5011792514][Jie Xu]], [[https://openalex.org/A5080979034][Anmin Liu]], [[https://openalex.org/A5005384003][Gang Wu]], [[https://openalex.org/A5077141294][Qingyang Li]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c04398 
     
The electrocatalytic transformation of waste nitrate into useful ammonia is a "one stone, two birds" strategy, which is commendatory from the viewpoint of the environment. In this vein, developing catalysts with high efficiency, selectivity, and stability is desired to make the attractive technology viable. Herein, we synthesized an economical and scalable electrocatalyst of Cu nanoparticles dispersed onto ZnO nanowire arrays (Cu@ZnO NWA) for nitrate reduction reaction (NO3–RR). This catalyst constructed on the Cu foam achieved a high ammonia yield of ∼6.03 mg cm–2 h–1, a Faradaic efficiency of ∼89.14%, and good stability for the NO3–RR in the Ar-saturated 0.1 M KOH electrolyte with the presence of 0.05 M KNO3, superior to most Cu-based catalysts reported in the literature. According to electrochemical measurements and density functional theory calculations, ZnO nanowires offer stable support to accomplish uniform dispersion of Cu nanoparticles and provide a synergy to boost electrocatalytic properties of Cu catalysts. This synergistic effect may originate from the electronic localization at the interface of Cu nanoparticles and ZnO nanowires, resulting in the electron deficiency of the Cu@ZnO NWA surface. Therefore, the promotional mechanisms are associated with enhanced adsorption of the electronegative nitrate ions and boosted charge transfer during the NO3–RR process. Notably, the Cu@ZnO NWA catalyst can be synthesized on most conductor surfaces through a flexible combination of electrodeposition and hydrothermal techniques, showing good commonality and scalability, thus having a vast industrialization potential for practical application.    

    

* Realizing the 4e–/2e– Pathway Transition of O2 Reduction on Co–N4–C Catalysts by Regulating the Chemical Structures beyond the Second Coordination Shells  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393940834
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-04-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c00781")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393940834"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393940834"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393940834"))][Get cited by]]

OpenAlex: https://openalex.org/W4393940834 (Open access: False)
    
[[https://openalex.org/A5091348611][Wang Wang]], [[https://openalex.org/A5038320521][Yunzi Hu]], [[https://openalex.org/A5001120009][Peng Li]], [[https://openalex.org/A5039374096][Yucheng Liu]], [[https://openalex.org/A5034911893][Shengli Chen]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c00781 
     
The catalytic performance of single-atom catalysts (SACs) is vitally determined by their coordination environments. So far, the catalytic manipulation of SACs has been mainly focused on the first and second nearest coordination structures of the center atoms. We herein demonstrate that the chemical environments beyond the second coordination shells also significantly influence the catalytic behaviors of SACs. Our findings reveal that the presence of graphitic nitrogen can induce a shift of the O2 reduction pathway on CoN4C sites from an energy-conversion favorite 4e– pathway to a H2O2-production desirable 2e– pathway. The remote graphitic N tunes the electronic structure of Co from the lower-spin state to the higher-spin state, as proved by the zero-field cooling (ZFC) temperature-dependent magnetic susceptibility, which weakens the adsorption of O2/*OOH, ultimately enhancing the selectivity toward H2O2. It is further revealed that the catalytic influence of graphitic N may be universally present in other SACs such as FeN4C and MnN4C. Impressively, the graphitic N-doped CoN4C exhibits a high H2O2 Faraday efficiency (82%) in a flow cell, with a remarkable H2O2 yield of 0.096 mmol cm–2 h–1 for 200 h at 0.358 V (vs RHE), which is sufficient for many applications such as the electro-Fenton-like degradation of the malachite green and demonstrated the feasibility of H2O2 electrosynthesis.    

    

* Issue Editorial Masthead  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393982452
:TOPICS: 
:PUBLICATION_DATE: 2024-04-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i007_1787822")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393982452"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393982452"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393982452"))][Get cited by]]

OpenAlex: https://openalex.org/W4393982452 (Open access: True)
    
, ACS catalysis. 14(7)] 2024. https://doi.org/10.1021/csv014i007_1787822  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i007_1787822][pdf]])
     
No abstract    

    

* Issue Publication Information  :ACS_Catalysis:
:PROPERTIES:
:UUID: https://openalex.org/W4393990563
:TOPICS: 
:PUBLICATION_DATE: 2024-04-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/csv014i007_1787821")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393990563"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393990563"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393990563"))][Get cited by]]

OpenAlex: https://openalex.org/W4393990563 (Open access: True)
    
, ACS catalysis. 14(7)] 2024. https://doi.org/10.1021/csv014i007_1787821  ([[https://pubs.acs.org/doi/pdf/10.1021/csv014i007_1787821][pdf]])
     
No abstract    

    
