#+TITLE: authors
Description: List of authors
Created on Tue Nov  5 01:19:12 2024

Found 2 results from 2024-10-29 to 2024-11-05
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5003442464]]

* Enumeration of surface site nuclearity and shape in a database of intermetallic low-index surface facets  :authors:
:PROPERTIES:
:UUID: https://openalex.org/W4403909596
:TOPICS: Accelerating Materials Innovation through Informatics, Atom Probe Tomography Research, Powder Diffraction Analysis
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcat.2024.115795")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403909596"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403909596"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403909596"))][Get cited by]]

OpenAlex: https://openalex.org/W4403909596 (Open access: False)
    
[[https://openalex.org/A5034884349][Unnatti Sharma]], [[https://openalex.org/A5112922494][A.L. Nguyen]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5024574386][Zachary W. Ulissi]], [[https://openalex.org/A5031735060][Michael J. Janik]], Journal of Catalysis. None(None)] 2024. https://doi.org/10.1016/j.jcat.2024.115795 
     
No abstract    

    

* Accessing Numerical Energy Hessians with Graph Neural Network Potentials   and Their Application in Heterogeneous Catalysis  :authors:
:PROPERTIES:
:UUID: https://openalex.org/W4403928590
:TOPICS: Memristive Devices for Neuromorphic Computing, Accelerating Materials Innovation through Informatics, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2410.01650")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403928590"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403928590"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403928590"))][Get cited by]]

OpenAlex: https://openalex.org/W4403928590 (Open access: True)
    
[[https://openalex.org/A5029824000][Brook Wander]], [[https://openalex.org/A5035368167][Joseph Musielewicz]], [[https://openalex.org/A5022902169][Raffaele Cheula]], [[https://openalex.org/A5003442464][John R. Kitchin]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2410.01650  ([[http://arxiv.org/pdf/2410.01650][pdf]])
     
Access to the potential energy Hessian enables determination of the Gibbs free energy, and certain approaches to transition state search and optimization. Here, we demonstrate that off-the-shelf pretrained Open Catalyst Project (OCP) machine learned potentials (MLPs) determine the Hessian with great success (58 cm$^{-1}$ mean absolute error (MAE)) for intermediates adsorbed to heterogeneous catalyst surfaces. This enables the use of OCP models for the aforementioned applications. The top performing model, with a simple offset correction, gives good estimations of the vibrational entropy contribution to the Gibbs free energy with an MAE of 0.042 eV at 300 K. The ability to leverage models to capture the translational entropy was also explored. It was determined that 94% of randomly sampled systems had a translational entropy greater than 0.1 eV at 300 K. This underscores the need to go beyond the harmonic approximation to consider the entropy introduced by adsorbate translation, which increases with temperature. Lastly, we used MLP determined Hessian information for transition state search and found we were able to reduce the number of unconverged systems by 65% to 93% overall convergence, improving on the baseline established by CatTSunami.    

    
