#+TITLE: authors
Description: List of authors
Created on Tue Jun 25 01:08:31 2024

Found 1 results from 2024-06-18 to 2024-06-25
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5003442464]]

* Exploratory mapping of tumor associated macrophage nanoparticle article abstracts using an eLDA topic modeling machine learning approach  :authors:
:PROPERTIES:
:UUID: https://openalex.org/W4399769525
:TOPICS: Exosome Biology and Function in Intercellular Communication, Macrophage Activation and Polarization, Mechanisms and Implications of Ferroptosis in Cancer
:PUBLICATION_DATE: 2024-06-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1371/journal.pone.0304505")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399769525"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399769525"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399769525"))][Get cited by]]

OpenAlex: https://openalex.org/W4399769525 (Open access: True)
    
[[https://openalex.org/A5091373951][Chloe Brown]], [[https://openalex.org/A5088916982][Colette Bilynsky]], [[https://openalex.org/A5075051633][Melanie Gainey]], [[https://openalex.org/A5077592017][Sarah Young]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5074066993][Elizabeth Wayne]], PloS one. 19(6)] 2024. https://doi.org/10.1371/journal.pone.0304505  ([[https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0304505&type=printable][pdf]])
     
The role of macrophages in regulating the tumor microenvironment has spurned the exponential generation of nanoparticle targeting technologies. With the large amount of literature and the speed at which it is generated it is difficult to remain current with the most up-to-date literature. In this study we performed a topic modeling analysis of 854 abstracts of peer-reviewed literature for the most common usages of nanoparticle targeting of tumor associated macrophages (TAMs) in solid tumors. The data spans 20 years of literature, providing a broad perspective of the nanoparticle strategies. Our topic model found 6 distinct topics: Immune and TAMs, Nanoparticles, Imaging, Gene Delivery and Exosomes, Vaccines, and Multi-modal Therapies. We also found distinct nanoparticle usage, tumor types, and therapeutic trends across these topics. Moreover, we established that the topic model could be used to assign new papers into the existing topics, thereby creating a Living Review. This type of “birds-eye-view” analysis provides a useful assessment tool for exploring new and emerging themes within a large field.    

    
