#+TITLE: authors
Description: List of authors
Created on Sun Jul 21 01:15:59 2024

Found 1 results from 2024-07-14 to 2024-07-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5003442464]]

* Rotationally Invariant Latent Distances for Uncertainty Estimation of   Relaxed Energy Predictions by Graph Neural Network Potentials  :authors:
:PROPERTIES:
:UUID: https://openalex.org/W4400720071
:TOPICS: Accelerating Materials Innovation through Informatics, Natural Language Processing, Modeling and Control of Multidimensional Systems
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2407.10844")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400720071"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400720071"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400720071"))][Get cited by]]

OpenAlex: https://openalex.org/W4400720071 (Open access: True)
    
[[https://openalex.org/A5035368167][Joseph Musielewicz]], [[https://openalex.org/A5000075355][Janice Lan]], [[https://openalex.org/A5010182611][Matt Uyttendaele]], [[https://openalex.org/A5003442464][John R. Kitchin]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2407.10844  ([[https://arxiv.org/pdf/2407.10844][pdf]])
     
Graph neural networks (GNNs) have been shown to be astonishingly capable models for molecular property prediction, particularly as surrogates for expensive density functional theory calculations of relaxed energy for novel material discovery. However, one limitation of GNNs in this context is the lack of useful uncertainty prediction methods, as this is critical to the material discovery pipeline. In this work, we show that uncertainty quantification for relaxed energy calculations is more complex than uncertainty quantification for other kinds of molecular property prediction, due to the effect that structure optimizations have on the error distribution. We propose that distribution-free techniques are more useful tools for assessing calibration, recalibrating, and developing uncertainty prediction methods for GNNs performing relaxed energy calculations. We also develop a relaxed energy task for evaluating uncertainty methods for equivariant GNNs, based on distribution-free recalibration and using the Open Catalyst Project dataset. We benchmark a set of popular uncertainty prediction methods on this task, and show that latent distance methods, with our novel improvements, are the most well-calibrated and economical approach for relaxed energy calculations. Finally, we demonstrate that our latent space distance method produces results which align with our expectations on a clustering example, and on specific equation of state and adsorbate coverage examples from outside the training dataset.    

    
