#+TITLE: authors
Description: List of authors
Created on Thu Mar 28 00:44:18 2024

Found 1 results from 2024-03-21 to 2024-03-28
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5003442464]]

* Surface Segregation Studies in Ternary Noble Metal Alloys: Comparing DFT and Machine Learning with Experimental Data  :authors:
:PROPERTIES:
:UUID: https://openalex.org/W4393066436
:TOPICS: Ice Nucleation and Melting Phenomena, Surface Analysis and Electron Spectroscopy Techniques
:PUBLICATION_DATE: 2024-03-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cphc.202400073")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393066436"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393066436"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393066436"))][Get cited by]]

OpenAlex: https://openalex.org/W4393066436 (Open access: False)
    
[[https://openalex.org/A5088846020][Kirby Broderick]], [[https://openalex.org/A5094217836][Robert Burnely]], [[https://openalex.org/A5040842816][Andrew J. Gellman]], [[https://openalex.org/A5003442464][John R. Kitchin]], ChemPhysChem. None(None)] 2024. https://doi.org/10.1002/cphc.202400073 
     
Surface segregation, whereby the surface composition of an alloy differs systematically from the bulk, has historically been hard to study, because it requires experimental and modeling methods that span alloy composition space. In this work, we study surface segregation in catalytically relevant noble and platinum‐group metal alloys with a focus on three ternary systems: AgAuCu, AuCuPd, and CuPdPt. We develop a data set of 2478 slabs with those compositions including all three low‐index crystallographic orientations relaxed with Density Functional Theory using the PBEsol functional with D3 dispersion corrections. We fine‐tune a machine learning model on this data and use the model in a series of 1800 Monte Carlo simulations spanning ternary composition space for each surface orientation and ternary chemical system. The results of these simulations are validated against prior experimental surface segregation data collected using composition spread alloy films for AgAuCu and AuCuPd. Our findings reveal that simulations conducted using the (110) orientation most closely match experimentally observed surface segregation trends, and while predicted trends qualitatively match observation, biases in the PBEsol functional limit numeric accuracy. This study advances understanding of surface segregation and the utility of computational studies and highlights the need for further improvements in simulation accuracy.    

    
