#+TITLE: authors
Description: List of authors
Created on Thu Jun  6 01:07:11 2024

Found 1 results from 2024-05-30 to 2024-06-06
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5003442464]]

* Pourbaix Machine Learning Framework Identifies Acidic Water Oxidation Catalysts Exhibiting Suppressed Ruthenium Dissolution  :authors:
:PROPERTIES:
:UUID: https://openalex.org/W4399305702
:TOPICS: Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-06-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c01353")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399305702"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399305702"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399305702"))][Get cited by]]

OpenAlex: https://openalex.org/W4399305702 (Open access: False)
    
[[https://openalex.org/A5049493917][Jehad Abed]], [[https://openalex.org/A5062528507][Javier Heras‐Domingo]], [[https://openalex.org/A5071284998][Rohan Yuri Sanspeur]], [[https://openalex.org/A5076838400][Ming Ronnier Luo]], [[https://openalex.org/A5048076397][Wajdi Alnoush]], [[https://openalex.org/A5036126810][Débora Motta Meira]], [[https://openalex.org/A5037413243][Hsiao‐Tsu Wang]], [[https://openalex.org/A5048097208][Jian Wang]], [[https://openalex.org/A5033120840][Jigang Zhou]], [[https://openalex.org/A5052565332][Daojin Zhou]], [[https://openalex.org/A5015913191][Khalid Fatih]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5044827415][Drew Higgins]], [[https://openalex.org/A5024574386][Zachary W. Ulissi]], [[https://openalex.org/A5054680242][Edward H. Sargent]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c01353 
     
The demand for green hydrogen has raised concerns over the availability of iridium used in oxygen evolution reaction catalysts. We identify catalysts with the aid of a machine learning-aided computational pipeline trained on more than 36,000 mixed metal oxides. The pipeline accurately predicts Pourbaix decomposition energy (Gpbx) from unrelaxed structures with a mean absolute error of 77 meV per atom, enabling us to screen 2070 new metallic oxides with respect to their prospective stability under acidic conditions. The search identifies Ru0.6Cr0.2Ti0.2O2 as a candidate having the promise of increased durability: experimentally, we find that it provides an overpotential of 267 mV at 100 mA cm–2 and that it operates at this current density for over 200 h and exhibits a rate of overpotential increase of 25 μV h–1. Surface density functional theory calculations reveal that Ti increases metal–oxygen covalency, a potential route to increased stability, while Cr lowers the energy barrier of the HOO* formation rate-determining step, increasing activity compared to RuO2 and reducing overpotential by 40 mV at 100 mA cm–2 while maintaining stability. In situ X-ray absorption spectroscopy and ex situ ptychography-scanning transmission X-ray microscopy show the evolution of a metastable structure during the reaction, slowing Ru mass dissolution by 20× and suppressing lattice oxygen participation by >60% compared to RuO2.    

    
