#+TITLE: authors
Description: List of authors
Created on Tue Apr  2 00:47:25 2024

Found 1 results from 2024-03-26 to 2024-04-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5003442464]]

* Generalization of Graph-Based Active Learning Relaxation Strategies Across Materials  :authors:
:PROPERTIES:
:UUID: https://openalex.org/W4393189800
:TOPICS: Accelerating Materials Innovation through Informatics, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/2632-2153/ad37f0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393189800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393189800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393189800"))][Get cited by]]

OpenAlex: https://openalex.org/W4393189800 (Open access: True)
    
[[https://openalex.org/A5022967729][Xiaoxiao Wang]], [[https://openalex.org/A5035368167][Joseph Musielewicz]], [[https://openalex.org/A5050564006][Richard Tran]], [[https://openalex.org/A5025104400][Sudheesh Kumar Ethirajan]], [[https://openalex.org/A5015075381][Xiao Fu]], [[https://openalex.org/A5012436789][Hilda Mera]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5065146210][Rachel C. Kurchin]], [[https://openalex.org/A5024574386][Zachary W. Ulissi]], Machine learning: science and technology. None(None)] 2024. https://doi.org/10.1088/2632-2153/ad37f0  ([[https://iopscience.iop.org/article/10.1088/2632-2153/ad37f0/pdf][pdf]])
     
Abstract Although density functional theory (DFT) has aided in accelerating the discovery of new materials, such calculations are computationally expensive, especially for high-throughput efforts. This has prompted an explosion in exploration of machine learning assisted techniques to improve the computational efficiency of DFT. In this study, we present a comprehensive investigation of the broader application of Finetuna, an active learning framework to accelerate structural relaxation in DFT with prior information from Open Catalyst Project pretrained graph neural networks. We explore the challenges associated with out-of-domain systems: alcohol ($C_{>2}$) on metal surfaces as larger adsorbates, metal-oxides with spin polarization, and three-dimensional (3D) structures like zeolites and metal-organic-frameworks. By pre-training machine learning models on large datasets and fine-tuning the model along the simulation, we demonstrate the framework's ability to conduct relaxations with fewer DFT calculations. Depending on the similarity of the test systems to the training systems, a more conservative querying strategy is applied. Our best-performing Finetuna strategy reduces the number of DFT single-point calculations by 80% for alcohols and 3D structures, and 42% for oxide systems.    

    
