#+TITLE: authors
Description: List of authors
Created on Sat May 25 01:04:40 2024

Found 1 results from 2024-05-18 to 2024-05-25
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5003442464]]

* Cyclic Steady-State Simulation and Waveform Design for Dynamic/Programmable Catalysis  :authors:
:PROPERTIES:
:UUID: https://openalex.org/W4398161548
:TOPICS: Catalytic Nanomaterials, Cloud Computing and Big Data Technologies, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-05-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.4c01543")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4398161548"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4398161548"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4398161548"))][Get cited by]]

OpenAlex: https://openalex.org/W4398161548 (Open access: True)
    
[[https://openalex.org/A5029952107][Consiglia Tedesco]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5030631754][Carl D. Laird]], Journal of physical chemistry. C./Journal of physical chemistry. C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.4c01543  ([[https://pubs.acs.org/doi/pdf/10.1021/acs.jpcc.4c01543][pdf]])
     
Dynamic catalysis is a novel and promising approach that aims to improve the catalyst performance by modulating the binding energies of adsorbates to favor different reaction steps periodically. In this work, we investigate a unimolecular dynamic catalytic system, with a focus on methods for simulating the transient behavior and identifying the optimal wave parameters for the modulations. Employing the modeling language Pyomo and the solver IPOPT, we formulate a Boundary Value Problem with limit cycle conditions to obtain results with orders-of-magnitude improvements in computational efficiency when compared to forward integration methods. Leveraging this flexible approach, mathematical optimization was applied to the parameters of piecewise and continuous forcing functions to identify the maximum time-averaged turnover frequency (avTOF). We relate the results to the Extended Sabatier Volcano graphical representation, which provides insight into the behavior and optimal parameters of the target systems. Our results further support the notion that periodic shifts in rate-controlling elementary steps lead to a rate of reaction enhancement beyond the Sabatier limit.    

    
