#+TITLE: authors
Description: List of authors
Created on Sat May 18 01:04:29 2024

Found 1 results from 2024-05-11 to 2024-05-18
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5003442464]]

* AdsorbDiff: Adsorbate Placement via Conditional Denoising Diffusion  :authors:
:PROPERTIES:
:UUID: https://openalex.org/W4396813915
:TOPICS: Neural Network Fundamentals and Applications
:PUBLICATION_DATE: 2024-05-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2405.03962")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396813915"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396813915"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396813915"))][Get cited by]]

OpenAlex: https://openalex.org/W4396813915 (Open access: True)
    
[[https://openalex.org/A5017163658][Adeesh Kolluru]], [[https://openalex.org/A5003442464][John R. Kitchin]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2405.03962  ([[https://arxiv.org/pdf/2405.03962][pdf]])
     
Determining the optimal configuration of adsorbates on a slab (adslab) is pivotal in the exploration of novel catalysts across diverse applications. Traditionally, the quest for the lowest energy adslab configuration involves placing the adsorbate onto the slab followed by an optimization process. Prior methodologies have relied on heuristics, problem-specific intuitions, or brute-force approaches to guide adsorbate placement. In this work, we propose a novel framework for adsorbate placement using denoising diffusion. The model is designed to predict the optimal adsorbate site and orientation corresponding to the lowest energy configuration. Further, we have an end-to-end evaluation framework where diffusion-predicted adslab configuration is optimized with a pretrained machine learning force field and finally evaluated with Density Functional Theory (DFT). Our findings demonstrate an acceleration of up to 5x or 3.5x improvement in accuracy compared to the previous best approach. Given the novelty of this framework and application, we provide insights into the impact of pre-training, model architectures, and conduct extensive experiments to underscore the significance of this approach.    

    
