#+filetags: CMU_Chemical_Engineering
#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Sun Feb  4 23:59:52 2024

Found 5 results from 2024-01-27 to 2024-02-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Optimal retrofitting of conventional oil refinery into sustainable bio‐refinery under uncertainty  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391308369
:TOPICS: Technologies for Biofuel Production from Biomass, State-of-the-Art in Process Optimization under Uncertainty, Technical Aspects of Biodiesel Production
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aic.18371")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391308369"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391308369"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391308369"))][Get cited by]]

OpenAlex: https://openalex.org/W4391308369 (Open access: False)
    
[[https://openalex.org/A5081847658][L. Zhang]], [[https://openalex.org/A5027983186][Ana I. Torres]], [[https://openalex.org/A5032499618][Bingzhen Chen]], [[https://openalex.org/A5082928023][Zhihong Yuan]], [[https://openalex.org/A5056017028][Ignacio E. Grossmann]], AIChE Journal. None(None)] 2024. https://doi.org/10.1002/aic.18371 
     
Abstract This article focuses on a novel optimization problem to retrofit a conventional fossil‐based refinery into a hybrid biomass‐based refinery. A mixed‐integer linear programming model, which considers a 10‐year‐long retrofit planning along with operational constraints in each year, is formulated. The problem is extended to a multistage stochastic programming model to handle both endogenous and exogenous uncertainties, and solved through a series of two‐stage stochastic programming subproblems. Furthermore, a Lagrangean decomposition algorithm is implemented to solve such a problem. By determining whether to add new units or retrofit existing units to the selected biomass‐based technologies, the results provide flexible design alternatives with consideration of operational constraints for each year. The results show the advantages of the selected biomass‐based technologies and enhance the performance of the final solution under uncertainty.    

    

* Circumventing Data Imbalance in Magnetic Ground State Data for Magnetic Moment Predictions  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391338155
:TOPICS: Accelerating Materials Innovation through Informatics, Natural Language Processing, Advancements in Density Functional Theory
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/2632-2153/ad23fb")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391338155"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391338155"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391338155"))][Get cited by]]

OpenAlex: https://openalex.org/W4391338155 (Open access: True)
    
[[https://openalex.org/A5071284998][Rohan Yuri Sanspeur]], [[https://openalex.org/A5003442464][John R. Kitchin]], Machine Learning: Science and Technology. None(None)] 2024. https://doi.org/10.1088/2632-2153/ad23fb  ([[https://iopscience.iop.org/article/10.1088/2632-2153/ad23fb/pdf][pdf]])
     
Abstract Magnetic materials play a crucial role in the transition to more sustainable forms of energy and electric vehicles. There is an anticipated shortage in magnetic materials in the future, and as a result there is an urgent need to discover and design new magnetic materials. Computational magnetic material design using density functional theory is daunting because of the challenge in identifying magnetic ground states from a combinatorially large set of possibilities. Machine learning offers a path forward by enabling efficient surrogate models that can more readily enumerate these states, but there is a dearth of training data available, and what is available tends to be imbalanced with too much non-magnetic data. In this work we show that the discrete and previously tackled data imbalance that exists at the level of the magnetic ordering leads to an imbalanced continuous distribution with many zeros when the data is unraveled at the atomic magnetic moment level, which subsequently leads to models with low accuracy for magnetic properties. We mitigate this by using a two-part model framework. Our scheme is able to classify atoms into magnetic and non-magnetic with an F1 score and Matthew's Correlation Coefficient (MCC) of $\sim$ 91 \% and then to provide an implicit embedding representation that maps directly onto the magnitude of the magnetic moment with a Mean Absolute Error (MAE) of 0.1 $\mu_{\text{B}}$. Beyond screening for new magnetic materials, we demonstrate an additional practical use case of our scheme: the provision of good initial guesses for magnetic moments in first-principles electronic relaxations. Such initialization is shown to lead to faster convergence to configurations that lie closer to the ground state.    

    

* Characterization and comparison of human and mouse milk cells  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391381333
:TOPICS: Composition and Health Effects of Human Milk, Immunological Mechanisms in Pregnancy and Fetal-Maternal Interface, MicroRNA Regulation in Cancer and Development
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1371/journal.pone.0297821")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391381333"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391381333"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391381333"))][Get cited by]]

OpenAlex: https://openalex.org/W4391381333 (Open access: True)
    
[[https://openalex.org/A5050347382][Rose Doerfler]], [[https://openalex.org/A5075263409][Saigopalakrishna S. Yerneni]], [[https://openalex.org/A5080909957][Alexandra N. Newby]], [[https://openalex.org/A5073121497][Namit Chaudhary]], [[https://openalex.org/A5080914057][Ashley Shu]], [[https://openalex.org/A5087199847][Katherine C. Fein]], [[https://openalex.org/A5040413965][Juliana H. Azambuja]], [[https://openalex.org/A5010666650][Kathryn A. Whitehead]], PLOS ONE. 19(1)] 2024. https://doi.org/10.1371/journal.pone.0297821  ([[https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0297821&type=printable][pdf]])
     
Recent data has characterized human milk cells with unprecedented detail and provided insight into cell populations. While such analysis of freshly expressed human milk has been possible, studies of cell functionality within the infant have been limited to animal models. One commonly used animal model for milk research is the mouse; however, limited data are available describing the composition of mouse milk. In particular, the maternal cells of mouse milk have not been previously characterized in detail, in part due to the difficulty in collecting sufficient volumes of mouse milk. In this study, we have established a method to collect high volumes of mouse milk, isolate cells, and compare the cell counts and types to human milk. Surprisingly, we found that mouse milk cell density is three orders of magnitude higher than human milk. The cell types present in the milk of mice and humans are similar, broadly consisting of mammary epithelial cells and immune cells. These results provide a basis of comparison for mouse and human milk cells and will inform the most appropriate uses of mouse models for the study of human phenomena.    

    

* Physics-informed machine learning with optimization-based guarantees: Applications to AC power flow  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391418533
:TOPICS: Physics-Informed Neural Networks for Scientific Computing, Power System Stability and Control Analysis, Vortex-Induced Vibrations in Fluid Flow
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijepes.2023.109741")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391418533"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391418533"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391418533"))][Get cited by]]

OpenAlex: https://openalex.org/W4391418533 (Open access: True)
    
[[https://openalex.org/A5029553393][Jordan Jalving]], [[https://openalex.org/A5061248955][Michael Eydenberg]], [[https://openalex.org/A5017102691][Logan Blakely]], [[https://openalex.org/A5007259749][Anya Castillo]], [[https://openalex.org/A5078112906][Zachary Kilwein]], [[https://openalex.org/A5077996853][J. Kyle Skolfield]], [[https://openalex.org/A5075167781][Fani Boukouvala]], [[https://openalex.org/A5030631754][Carl D. Laird]], International Journal of Electrical Power & Energy Systems. 157(None)] 2024. https://doi.org/10.1016/j.ijepes.2023.109741 
     
This manuscript presents a complete framework for the development and verification of physics-informed neural networks with application to the alternating-current power flow (ACPF) equations. Physics-informed neural networks (PINN)s have received considerable interest within power systems communities for their ability to harness underlying physical equations to produce simple neural network architectures that achieve high accuracy using limited training data. The methodology developed in this work builds on existing methods and explores new important aspects around the implementation of PINNs including: (i) obtaining operationally relevant training data, (ii) efficiently training PINNs and using pruning techniques to reduce their complexity, and (iii) globally verifying the worst-case predictions given known physical constraints. The methodology is applied to the IEEE-14 and 118 bus systems where PINNs show substantially improved accuracy in a data-limited setting and attain better guarantees with respect to worst-case predictions.    

    

* Does Kaizen Programming need a physic-informed mechanism to improve the search?  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391249853
:TOPICS: Game Artificial Intelligence Research, Swarm Intelligence Optimization Algorithms
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/la-cci58595.2023.10409360")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391249853"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391249853"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391249853"))][Get cited by]]

OpenAlex: https://openalex.org/W4391249853 (Open access: False)
    
[[https://openalex.org/A5073891151][Jimena Ferreira]], [[https://openalex.org/A5027983186][Ana I. Torres]], [[https://openalex.org/A5091770128][Martín Pedemonte]], No host. None(None)] 2023. https://doi.org/10.1109/la-cci58595.2023.10409360 
     
In recent years, the study of physics-informed machine learning has increased. Works that use information about the shape or some characteristic of the expected function, have been used with genetic programming and neural networks. In those studies, it was found that including information about the expected model makes the resulting models better.Motivated by these studies, the goal of this work is the evaluation of the inclusion of information about the shape of the function in Kaizen Programming using a penalty function. In order to answer if the inclusion of this information in the search results in better models. In order to answer that we worked with 13 benchmark functions. The functions have between 2 and 9 input variables, and all have different types of shapes.We found that there is no significant difference in the performance of the models obtained using plain Kazan Programming and the shape-constrained approach.    

    
