#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Fri May  9 01:40:19 2025

Found 1 results from 2025-05-02 to 2025-05-09
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Distributed Control Method for Vehicle Cooperative Rendezvous  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410007158
:TOPICS: Robotic Path Planning Algorithms, Distributed Control Multi-Agent Systems, Robotics and Sensor-Based Localization
:PUBLICATION_DATE: 2025-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2514/1.g008445")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410007158"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410007158"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410007158"))][Get cited by]]

OpenAlex: https://openalex.org/W4410007158 (Open access: False)
    
[[https://openalex.org/A5054103149][Zhenyu Wei]], [[https://openalex.org/A5100886581][Zhijiang Shao]], [[https://openalex.org/A5052825722][Lorenz T. Biegler]], Journal of Guidance Control and Dynamics. None(None)] 2025. https://doi.org/10.2514/1.g008445 
     
Cooperative rendezvous/docking is an enabling technology for future autonomous missions. However, it is still a challenge to design a fully distributed, stability-guaranteed control method for cooperative rendezvous. To address this issue, this paper proposes a distributed control method for an unmanned vehicle cooperative rendezvous mission. First, the cooperative rendezvous process is formulated as an optimal control problem. To decentralize the control framework, a rendezvous parameter is introduced, and the rendezvous parameter optimization algorithm is designed to guarantee the terminal rendezvous of autonomous vehicles while improving the system performance. On this basis, a distributed control framework, based on rendezvous parameter optimization, generates the control commands to achieve cooperative rendezvous. Results demonstrate the effectiveness of the proposed distributed control approach through three simulations.    

    
