#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Sat May  4 01:03:29 2024

Found 4 results from 2024-04-27 to 2024-05-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Iterative MILP algorithm to find alternate solutions in linear programming models  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4395671135
:TOPICS: State-of-the-Art in Process Optimization under Uncertainty, Multi-Objective Transportation Problem Optimization, Numerical Optimization Techniques
:PUBLICATION_DATE: 2024-04-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11081-024-09887-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395671135"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395671135"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395671135"))][Get cited by]]

OpenAlex: https://openalex.org/W4395671135 (Open access: True)
    
[[https://openalex.org/A5013747228][D. Kakkad]], [[https://openalex.org/A5056017028][Ignacio E. Grossmann]], [[https://openalex.org/A5007439406][Bianca Springub]], [[https://openalex.org/A5058221330][Christos Galanopoulos]], [[https://openalex.org/A5082876258][Leonardo Salsano de Assis]], [[https://openalex.org/A5022723188][Nga Tran]], [[https://openalex.org/A5021784779][John M. Wassick]], Optimization and engineering. None(None)] 2024. https://doi.org/10.1007/s11081-024-09887-3 
     
Abstract We address in this paper linear programming (LP) models in which it is desired to find a finite set of alternate optima. An LP may have multiple alternate solutions with the same objective value or with increasing objective values. For many real life applications, it can be interesting to have a pool of solutions to compare what operations should be executed and what is the cost/benefit of doing it. To obtain a specified number of these alternate solutions in the increasing order of objective values, we propose an iterative MILP algorithm in which we successively add integer cuts on inactive constraints. We demonstrate the application and effectiveness of this algorithm on a 2 dimensional LP and on small and large supply chain problems. The proposed iterative MILP algorithm provides an effective approach for finding a specified number of alternate optima in LP models, which provides a useful tool in a variety of applications as for instance in supply chain optimization problems.    

    

* A multiple-timing analysis of temporal ratcheting  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4395696879
:TOPICS: Stochastic Resonance in Nonlinear Systems, Dynamics of Synchronization in Complex Networks, Uncertainty Quantification and Sensitivity Analysis
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1140/epje/s10189-024-00421-y")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395696879"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395696879"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395696879"))][Get cited by]]

OpenAlex: https://openalex.org/W4395696879 (Open access: True)
    
[[https://openalex.org/A5081444645][S. M. H. Hashemi Amrei]], [[https://openalex.org/A5089485668][Edward T. Gilman]], [[https://openalex.org/A5018420940][Aditya S. Khair]], The European physical journal. E, Soft matter and biological physics/The European physical journal. E, Soft matter. 47(4)] 2024. https://doi.org/10.1140/epje/s10189-024-00421-y  ([[https://link.springer.com/content/pdf/10.1140/epje/s10189-024-00421-y.pdf][pdf]])
     
Abstract We develop a two-timing perturbation analysis to provide quantitative insights on the existence of temporal ratchets in an exemplary system of a particle moving in a tank of fluid in response to an external vibration of the tank. We consider two-mode vibrations with angular frequencies $$\omega $$  ω  and $$\alpha \omega $$   α ω   , where $$\alpha $$  α  is a rational number. If $$\alpha $$  α  is a ratio of odd and even integers (e.g., $$\tfrac{2}{1},\,\tfrac{3}{2},\,\tfrac{4}{3}$$     2 1   ,    3 2   ,    4 3     ), the system yields a net response: here, a nonzero time-average particle velocity. Our first-order perturbation solution predicts the existence of temporal ratchets for $$\alpha =2$$   α = 2   . Furthermore, we demonstrate, for a reduced model, that the temporal ratcheting effect for $$\alpha =\tfrac{3}{2}$$   α =   3 2     and $$\tfrac{4}{3}$$    4 3    appears at the third-order perturbation solution. More importantly, we find closed-form formulas for the magnitude and direction of the induced net velocities for these $$\alpha $$  α  values. On a broader scale, our methodology offers a new mathematical approach to study the complicated nature of temporal ratchets in physical systems. Graphic abstract    

    

* Fostering a Holistic Understanding of the Full Volatility Spectrum of Organic Compounds from Benzene Series Precursors through Mechanistic Modeling  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4396543013
:TOPICS: Atmospheric Aerosols and their Impacts, Stratospheric Chemistry and Climate Change Impacts, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.est.3c07128")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396543013"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396543013"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396543013"))][Get cited by]]

OpenAlex: https://openalex.org/W4396543013 (Open access: False)
    
[[https://openalex.org/A5068064234][Dejia Yin]], [[https://openalex.org/A5008718870][Bin Zhao]], [[https://openalex.org/A5055420452][Yafei Wang]], [[https://openalex.org/A5041685684][Neil M. Donahue]], [[https://openalex.org/A5086908350][Bo Feng]], [[https://openalex.org/A5060954259][Xing Chang]], [[https://openalex.org/A5067964464][Qi Chen]], [[https://openalex.org/A5077613536][Xi Cheng]], [[https://openalex.org/A5012066171][Tengyu Liu]], [[https://openalex.org/A5068305914][Chak K. Chan]], [[https://openalex.org/A5038957567][Meredith Schervish]], [[https://openalex.org/A5018728258][Zeqi Li]], [[https://openalex.org/A5001416395][Yuhong He]], [[https://openalex.org/A5085119258][Jiming Hao]], Environmental science & technology. None(None)] 2024. https://doi.org/10.1021/acs.est.3c07128 
     
No abstract    

    

* Diffusiophoretic Transport of Charged Colloids in Ionic Surfactant Gradients Entirely below versus Entirely above the Critical Micelle Concentration  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4396554712
:TOPICS: Theory and Simulations of Polyelectrolytes in Solutions, Nanofluidics and Nanopore Technology, Microfluidic Techniques for Particle Manipulation and Separation
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.langmuir.4c00431")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396554712"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396554712"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396554712"))][Get cited by]]

OpenAlex: https://openalex.org/W4396554712 (Open access: True)
    
[[https://openalex.org/A5073103738][Angela Yang]], [[https://openalex.org/A5087186936][Brian E. McKenzie]], [[https://openalex.org/A5095962168][Benjamin Pavlat]], [[https://openalex.org/A5088184906][Eric S. Johnson]], [[https://openalex.org/A5018420940][Aditya S. Khair]], [[https://openalex.org/A5063229014][Stephen Garoff]], [[https://openalex.org/A5037506064][Robert D. Tilton]], Langmuir. None(None)] 2024. https://doi.org/10.1021/acs.langmuir.4c00431 
     
When placed in an ionic surfactant gradient, charged colloids will undergo diffusiophoresis at a velocity, uDP = MDP∇ ln S, where MDP is the diffusiophoretic mobility and S is the surfactant concentration. The diffusiophoretic mobility depends in part on the charges and diffusivities of the surfactants and their counterions. Since micellization decreases surfactant diffusivity and alters charge distributions in a surfactant solution, MDP of charged colloids in ionic surfactant gradients may differ significantly when surfactant concentrations are above or below the critical micelle concentration (CMC). The role of micelles in driving diffusiophoresis is unclear, and a previously published model that accounts for micellization suggests the possibility of a change in the sign of MDP above the CMC [Warren, P. B.; . Soft Matter 2019, 15, 278-288]. In the current study, microfluidic channels were used to measure the transport of negatively charged polystyrene colloids in sodium dodecyl sulfate (SDS) surfactant gradients established at SDS concentrations that are either fully above or fully below the CMC. Interpretation of diffusiophoresis was aided by measurements of the colloid electrophoretic mobility as a function of SDS concentration. A numerical transport model incorporating the prior diffusiophoretic mobility model for ionic surfactant gradients was implemented to elucidate signatures of positive and negative diffusiophoretic mobilities and compare with experiments. The theoretically predicted sign of the diffusiophoretic mobility below the CMC was determined to be particularly sensitive to uncertainty in colloid and surfactant properties, while above the CMC, the mobility was consistently predicted to be positive in the SDS concentration range considered in the experiments conducted here. In contrast, experiments only showed signatures of a negative diffusiophoretic mobility for these negatively charged colloids with no change of sign. Colloid diffusiophoretic transport measured in micellar solutions was more extensive than that below the CMC with the same ∇ ln S.    

    
