#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Mon May  6 01:05:34 2024

Found 2 results from 2024-04-29 to 2024-05-06
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Fostering a Holistic Understanding of the Full Volatility Spectrum of Organic Compounds from Benzene Series Precursors through Mechanistic Modeling  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4396543013
:TOPICS: Atmospheric Aerosols and their Impacts, Stratospheric Chemistry and Climate Change Impacts, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.est.3c07128")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396543013"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396543013"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396543013"))][Get cited by]]

OpenAlex: https://openalex.org/W4396543013 (Open access: False)
    
[[https://openalex.org/A5068064234][Dejia Yin]], [[https://openalex.org/A5008718870][Bin Zhao]], [[https://openalex.org/A5055420452][Yafei Wang]], [[https://openalex.org/A5041685684][Neil M. Donahue]], [[https://openalex.org/A5086908350][Bo Feng]], [[https://openalex.org/A5060954259][Xing Chang]], [[https://openalex.org/A5067964464][Qi Chen]], [[https://openalex.org/A5077613536][Xi Cheng]], [[https://openalex.org/A5012066171][Tengyu Liu]], [[https://openalex.org/A5068305914][Chak K. Chan]], [[https://openalex.org/A5038957567][Meredith Schervish]], [[https://openalex.org/A5018728258][Zeqi Li]], [[https://openalex.org/A5001416395][Yuhong He]], [[https://openalex.org/A5085119258][Jiming Hao]], Environmental science & technology. None(None)] 2024. https://doi.org/10.1021/acs.est.3c07128 
     
No abstract    

    

* Diffusiophoretic Transport of Charged Colloids in Ionic Surfactant Gradients Entirely below versus Entirely above the Critical Micelle Concentration  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4396554712
:TOPICS: Theory and Simulations of Polyelectrolytes in Solutions, Nanofluidics and Nanopore Technology, Microfluidic Techniques for Particle Manipulation and Separation
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.langmuir.4c00431")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396554712"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396554712"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396554712"))][Get cited by]]

OpenAlex: https://openalex.org/W4396554712 (Open access: True)
    
[[https://openalex.org/A5073103738][Angela Yang]], [[https://openalex.org/A5087186936][Brian E. McKenzie]], [[https://openalex.org/A5095962168][Benjamin Pavlat]], [[https://openalex.org/A5088184906][Eric S. Johnson]], [[https://openalex.org/A5018420940][Aditya S. Khair]], [[https://openalex.org/A5063229014][Stephen Garoff]], [[https://openalex.org/A5037506064][Robert D. Tilton]], Langmuir. None(None)] 2024. https://doi.org/10.1021/acs.langmuir.4c00431 
     
When placed in an ionic surfactant gradient, charged colloids will undergo diffusiophoresis at a velocity, uDP = MDP∇ ln S, where MDP is the diffusiophoretic mobility and S is the surfactant concentration. The diffusiophoretic mobility depends in part on the charges and diffusivities of the surfactants and their counterions. Since micellization decreases surfactant diffusivity and alters charge distributions in a surfactant solution, MDP of charged colloids in ionic surfactant gradients may differ significantly when surfactant concentrations are above or below the critical micelle concentration (CMC). The role of micelles in driving diffusiophoresis is unclear, and a previously published model that accounts for micellization suggests the possibility of a change in the sign of MDP above the CMC [Warren, P. B.; . Soft Matter 2019, 15, 278-288]. In the current study, microfluidic channels were used to measure the transport of negatively charged polystyrene colloids in sodium dodecyl sulfate (SDS) surfactant gradients established at SDS concentrations that are either fully above or fully below the CMC. Interpretation of diffusiophoresis was aided by measurements of the colloid electrophoretic mobility as a function of SDS concentration. A numerical transport model incorporating the prior diffusiophoretic mobility model for ionic surfactant gradients was implemented to elucidate signatures of positive and negative diffusiophoretic mobilities and compare with experiments. The theoretically predicted sign of the diffusiophoretic mobility below the CMC was determined to be particularly sensitive to uncertainty in colloid and surfactant properties, while above the CMC, the mobility was consistently predicted to be positive in the SDS concentration range considered in the experiments conducted here. In contrast, experiments only showed signatures of a negative diffusiophoretic mobility for these negatively charged colloids with no change of sign. Colloid diffusiophoretic transport measured in micellar solutions was more extensive than that below the CMC with the same ∇ ln S.    

    
