#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Sun Feb 23 01:26:25 2025

Found 2 results from 2025-02-16 to 2025-02-23
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* The influence of Amazonian anthropogenic emissions on new particle formation, aerosol, cloud and surface rain  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4407753602
:TOPICS: Environmental and biological studies, Geography and Environmental Studies, Indigenous Health and Education
:PUBLICATION_DATE: 2025-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-2025-132")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4407753602"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4407753602"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4407753602"))][Get cited by]]

OpenAlex: https://openalex.org/W4407753602 (Open access: True)
    
[[https://openalex.org/A5100390606][Xuemei Wang]], [[https://openalex.org/A5061310552][K. S. Carslaw]], [[https://openalex.org/A5028113214][Daniel P. Grosvenor]], [[https://openalex.org/A5086004922][Hamish Gordon]], No host. None(None)] 2025. https://doi.org/10.5194/egusphere-2025-132 
     
Abstract. Anthropogenic emissions have been shown to affect new particle formation, aerosol concentrations, and clouds. Such effects vary with region, environmental conditions and cloud types. In the wet season of Amazonia, anthropogenic emissions emitted from Manaus, Brazil can significantly increase the cloud condensation nuclei (CCN) concentrations compared to the background of mainly natural aerosols. However, the regional response of cloud and rain to anthropogenic emissions in Amazonia remains very uncertain. Here we aim to quantify how new particle formation, aerosol concentration, cloud and rain respond to changes in anthropogenic emissions in the Manaus region and to understand the underlying mechanisms. We ran the atmosphere-only configuration of the HadGEM3 climate model with a nested regional domain that covers most of the rainforest region (720 km by 1200 km with 3 km resolution) under several regional emission scenarios. The 7-day simulations show that, in the areas that are affected by anthropogenic emissions, when aerosol and precursor gas emissions are doubled from the baseline emission inventories, aerosol number concentrations increase by 13 %. The nucleation rate that involves sulfuric acid generally increases with pollution levels. However, near the source of the pollution, nucleation is suppressed due to high primary aerosol emission, resulting in smaller nucleation and Aitken mode aerosol number concentrations. We also found that doubling the anthropogenic emission can increase the cloud droplet number concentrations (Nd) by 9 %, but cloud water mass and rain mass do not change significantly. Even very strong reductions in aerosol number concentrations by a factor of 4, which is an unrealistic condition, cause only 4 % increase in rain over the domain. If we assume our simulation has fine enough grid resolution and an accurate representation of the relevant atmospheric processes, the simulated weak response of cloud and rain would imply that the Amazonian convective environment is non-linear and resilient to the small changes in Nd that occur in response to localised anthropogenic aerosol emissions.    

    

* Variable aggregation for nonlinear optimization problems  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4407793209
:TOPICS: Water Quality Monitoring and Analysis, Multi-Criteria Decision Making
:PUBLICATION_DATE: 2025-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2502.13869")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4407793209"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4407793209"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4407793209"))][Get cited by]]

OpenAlex: https://openalex.org/W4407793209 (Open access: True)
    
[[https://openalex.org/A5054628015][Sakshi Naik]], [[https://openalex.org/A5052825722][Lorenz T. Biegler]], [[https://openalex.org/A5088880250][Russell Bent]], [[https://openalex.org/A5062143627][Robert Parker]], arXiv (Cornell University). None(None)] 2025. https://doi.org/10.48550/arxiv.2502.13869  ([[http://arxiv.org/pdf/2502.13869][pdf]])
     
Variable aggregation has been largely studied as an important pre-solve algorithm for optimization of linear and mixed-integer programs. Although some nonlinear solvers and algebraic modeling languages implement variable aggregation as a pre-solve, the impact it can have on constrained nonlinear programs is unexplored. In this work, we formalize variable aggregation as a pre-solve algorithm to develop reduced-space formulations of nonlinear programs. A novel approximate maximum variable aggregation strategy is developed to aggregate as many variables as possible. Furthermore, aggregation strategies that preserve the problem structure are compared against approximate maximum aggregation. Our results show that variable aggregation can generally help to improve the convergence reliability of nonlinear programs. It can also help in reducing total solve time. However, Hessian evaluation can become a bottleneck if aggregation significantly increases the number of variables appearing nonlinearly in many constraints.    

    
