#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Mon May 13 01:07:06 2024

Found 3 results from 2024-05-06 to 2024-05-13
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* CatTSunami: Accelerating Transition State Energy Calculations with
  Pre-trained Graph Neural Networks  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4396781988
:TOPICS: Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-05-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2405.02078")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396781988"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396781988"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396781988"))][Get cited by]]

OpenAlex: https://openalex.org/W4396781988 (Open access: True)
    
[[https://openalex.org/A5029824000][Brook Wander]], [[https://openalex.org/A5004640526][Muhammed Shuaibi]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5024574386][Zachary W. Ulissi]], [[https://openalex.org/A5058450549][C. Lawrence Zitnick]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2405.02078  ([[https://arxiv.org/pdf/2405.02078][pdf]])
     
Direct access to transition state energies at low computational cost unlocks the possibility of accelerating catalyst discovery. We show that the top performing graph neural network potential trained on the OC20 dataset, a related but different task, is able to find transition states energetically similar (within 0.1 eV) to density functional theory (DFT) 91% of the time with a 28x speedup. This speaks to the generalizability of the models, having never been explicitly trained on reactions, the machine learned potential approximates the potential energy surface well enough to be performant for this auxiliary task. We introduce the Open Catalyst 2020 Nudged Elastic Band (OC20NEB) dataset, which is made of 932 DFT nudged elastic band calculations, to benchmark machine learned model performance on transition state energies. To demonstrate the efficacy of this approach, we replicated a well-known, large reaction network with 61 intermediates and 174 dissociation reactions at DFT resolution (40 meV). In this case of dense NEB enumeration, we realize even more computational cost savings and used just 12 GPU days of compute, where DFT would have taken 52 GPU years, a 1500x speedup. Similar searches for complete reaction networks could become routine using the approach presented here. Finally, we replicated an ammonia synthesis activity volcano and systematically found lower energy configurations of the transition states and intermediates on six stepped unary surfaces. This scalable approach offers a more complete treatment of configurational space to improve and accelerate catalyst discovery.    

    

* Decomposition methods for multi-horizon stochastic programming  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4396813443
:TOPICS: Robust Optimization for Risk Management and Finance, Multiobjective Optimization in Evolutionary Algorithms, Multi-Objective Transportation Problem Optimization
:PUBLICATION_DATE: 2024-05-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10287-024-00509-y")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396813443"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396813443"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396813443"))][Get cited by]]

OpenAlex: https://openalex.org/W4396813443 (Open access: True)
    
[[https://openalex.org/A5058691896][Hongyu Zhang]], [[https://openalex.org/A5056017028][Ignacio E. Grossmann]], [[https://openalex.org/A5068032633][Asgeir Tomasgård]], Computational management science. 21(1)] 2024. https://doi.org/10.1007/s10287-024-00509-y  ([[https://link.springer.com/content/pdf/10.1007/s10287-024-00509-y.pdf][pdf]])
     
Abstract Multi-horizon stochastic programming includes short-term and long-term uncertainty in investment planning problems more efficiently than traditional multi-stage stochastic programming. In this paper, we exploit the block separable structure of multi-horizon stochastic linear programming, and establish that it can be decomposed by Benders decomposition and Lagrangean decomposition. In addition, we propose parallel Lagrangean decomposition with primal reduction that, (1) solves the scenario subproblems in parallel, (2) reduces the primal problem by keeping one copy for each scenario group at each stage, and (3) solves the reduced primal problem in parallel. We apply the parallel Lagrangean decomposition with primal reduction, Lagrangean decomposition and Benders decomposition to solve a stochastic energy system investment planning problem. The computational results show that: (a) the Lagrangean type decomposition algorithms have better convergence at the first iterations to Benders decomposition, and (b) parallel Lagrangean decomposition with primal reduction is very efficient for solving multi-horizon stochastic programming problems. Based on the computational results, the choice of algorithms for multi-horizon stochastic programming is discussed.    

    

* AdsorbDiff: Adsorbate Placement via Conditional Denoising Diffusion  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4396813915
:TOPICS: Neural Network Fundamentals and Applications
:PUBLICATION_DATE: 2024-05-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2405.03962")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396813915"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396813915"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396813915"))][Get cited by]]

OpenAlex: https://openalex.org/W4396813915 (Open access: True)
    
[[https://openalex.org/A5017163658][Adeesh Kolluru]], [[https://openalex.org/A5003442464][John R. Kitchin]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2405.03962  ([[https://arxiv.org/pdf/2405.03962][pdf]])
     
Determining the optimal configuration of adsorbates on a slab (adslab) is pivotal in the exploration of novel catalysts across diverse applications. Traditionally, the quest for the lowest energy adslab configuration involves placing the adsorbate onto the slab followed by an optimization process. Prior methodologies have relied on heuristics, problem-specific intuitions, or brute-force approaches to guide adsorbate placement. In this work, we propose a novel framework for adsorbate placement using denoising diffusion. The model is designed to predict the optimal adsorbate site and orientation corresponding to the lowest energy configuration. Further, we have an end-to-end evaluation framework where diffusion-predicted adslab configuration is optimized with a pretrained machine learning force field and finally evaluated with Density Functional Theory (DFT). Our findings demonstrate an acceleration of up to 5x or 3.5x improvement in accuracy compared to the previous best approach. Given the novelty of this framework and application, we provide insights into the impact of pre-training, model architectures, and conduct extensive experiments to underscore the significance of this approach.    

    
