#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Sun Mar 23 01:38:26 2025

Found 3 results from 2025-03-16 to 2025-03-23
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Sources of Oxygenated Organic Molecules and Their Impacts on Organic Aerosol in China  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4408487061
:TOPICS: Atmospheric chemistry and aerosols, Air Quality Monitoring and Forecasting
:PUBLICATION_DATE: 2025-03-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-egu25-15281")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4408487061"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4408487061"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4408487061"))][Get cited by]]

OpenAlex: https://openalex.org/W4408487061 (Open access: False)
    
[[https://openalex.org/A5008718870][Bin Zhao]], [[https://openalex.org/A5068064234][Dejia Yin]], [[https://openalex.org/A5100406427][Shuxiao Wang]], [[https://openalex.org/A5001416395][Yicong He]], [[https://openalex.org/A5041685684][Neil M. Donahue]], No host. None(None)] 2025. https://doi.org/10.5194/egusphere-egu25-15281 
     
Oxygenated organic molecules (OOMs), the oxidation products of organic precursors with low volatility and a high oxygen atom number, are an important driver of new particle formation (NPF) and secondary organic aerosols (SOA) formation. The sources and formation processes of OOMs are highly complicated, especially in populous regions (e.g., China) with diverse emissions of anthropogenic and biogenic precursors. However, current models fail to capture OOM formation from different precursors due to the absence of important reaction pathways (e.g., autoxidation, dimerization) and the oversimplified treatment of the oxidation of semi-volatile and intermediate-volatility precursors (I/SVOCs). In this work, we develop a Precursor-resolved Integrated two-dimensional Volatility Basis Set (I2D-VBS) model framework, which simulates the multi-generational ageing of organic emissions in the full volatility range on a precursor level and explicitly tracks irregular radical reactions, including autoxidation, dimerization, and RO isomerization followed by accelerated autoxidation. The parameterizations within the Precursor-resolved I2D-VBS are optimized by simulating chamber and flow-tube experiments measuring OOMs and SOA formed from individual precursors. We then incorporate the Precursor-resolved I2D-VBS in the CMAQ chemical transport model and simulate OOM formation in China. The CMAQ/I2D-VBS model successfully reproduced OOM concentrations at various sites across China, achieving accuracy within &#177;40% for total OOM concentrations and within a factor of 2 for volatility-binned OOM concentrations. The model results reveal that over 60% of total OOM concentrations are from I/SVOC in China; nevertheless, for extremely low-volatility OOMs (logC*70%), followed by autoxidation (~20%). Overall, OOMs contribute around half of SOA concentrations in China, highlighting the critically important role of OOMs in SOA formation.    

    

* Transferable Machine Learning Interatomic Potential for Pd-Catalyzed Cross-Coupling Reactions  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4408546240
:TOPICS: Machine Learning in Materials Science, Asymmetric Hydrogenation and Catalysis, Catalytic Cross-Coupling Reactions
:PUBLICATION_DATE: 2025-03-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2025-n36r6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4408546240"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4408546240"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4408546240"))][Get cited by]]

OpenAlex: https://openalex.org/W4408546240 (Open access: True)
    
[[https://openalex.org/A5042511909][Dylan M. Anstine]], [[https://openalex.org/A5083494710][R.I. Zubatyuk]], [[https://openalex.org/A5014333643][Liliana C. Gallegos]], [[https://openalex.org/A5021610812][Robert S. Paton]], [[https://openalex.org/A5029114040][Olaf Wiest]], [[https://openalex.org/A5081624801][Benjamin Nebgen]], [[https://openalex.org/A5055909996][Travis E. Jones]], [[https://openalex.org/A5048633127][Gabriel dos Passos Gomes]], [[https://openalex.org/A5056150849][Sergei Tretiak]], [[https://openalex.org/A5011932992][Olexandr Isayev]], No host. None(None)] 2025. https://doi.org/10.26434/chemrxiv-2025-n36r6  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/67d7b7f7fa469535b97c021a/original/transferable-machine-learning-interatomic-potential-for-pd-catalyzed-cross-coupling-reactions.pdf][pdf]])
     
Finding efficient substrate-catalyst combinations for palladium-catalyzed cross-coupling reactions remains a critical challenge in synthetic chemistry, with broad implications for pharmaceutical and materials manufacturing. We report AIMNet2-Pd, a machine learned interatomic potential that enables rapid, accurate computational studies of palladium-catalyzed cross-coupling reactions. AIMNet2-Pd replaces computationally expensive electronic structure calculations with a neural network-based model that performs geometry optimization, transition state searches, and energy calculations in seconds while maintaining accuracy within 1-2 kcal mol⁻¹ and ~0.1 Å compared to the reference QM calculations. AIMNet2-Pd makes computational high-throughput catalyst screening and mechanistic studies of realistic systems feasible by providing on-demand thermodynamic and kinetic predictions for each step of a catalytic cycle. Importantly, the applicability of the systems extends beyond the monophosphine ligands in Pd(0)/Pd(II) cycles for which it has been trained on to chemically diverse Pd complexes. This demonstrates AIMNet2-Pd's utility to serve as a general-purpose and high-throughput tool for studying catalytic reactions.    

    

* The impact of the Himalayan aerosol factory: results from high resolution numerical modelling of pure biogenic nucleation over the Himalayan valleys  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4408591658
:TOPICS: Atmospheric chemistry and aerosols, Atmospheric aerosols and clouds, Atmospheric and Environmental Gas Dynamics
:PUBLICATION_DATE: 2025-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4fd00171k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4408591658"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4408591658"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4408591658"))][Get cited by]]

OpenAlex: https://openalex.org/W4408591658 (Open access: True)
    
[[https://openalex.org/A5071131825][Giancarlo Ciarelli]], [[https://openalex.org/A5035425155][Arineh Cholakian]], [[https://openalex.org/A5093784592][Manuel Bettineschi]], [[https://openalex.org/A5015000522][Bruno Vitali]], [[https://openalex.org/A5081559070][Bertrand Bessagnet]], [[https://openalex.org/A5040866867][Victoria A. Sinclair]], [[https://openalex.org/A5065117143][Johannes Mikkola]], [[https://openalex.org/A5080319960][Imad El Haddad]], [[https://openalex.org/A5073745043][Dino Zardi]], [[https://openalex.org/A5033428767][Angela Marinoni]], [[https://openalex.org/A5032180474][Alessandro Bigi]], [[https://openalex.org/A5038903661][Paolo Tuccella]], [[https://openalex.org/A5008805563][Jaana Bäck]], [[https://openalex.org/A5086004922][Hamish Gordon]], [[https://openalex.org/A5015236692][Tuomo Nieminen]], [[https://openalex.org/A5000471665][Markku Kulmala]], [[https://openalex.org/A5026978286][Douglas R. Worsnop]], [[https://openalex.org/A5075179945][Federico Bianchi]], Faraday Discussions. None(None)] 2025. https://doi.org/10.1039/d4fd00171k 
     
A schematic of the “Himalayan aerosol factory”. Courtesy of Sole Lätti (https://kuvittajat.fi/).    

    
