#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Fri Oct 24 01:25:19 2025

Found 2 results from 2025-10-17 to 2025-10-24
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Beyond Force Metrics: Pre-Training MLFFs for Stable MD Simulations  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4415332979
:TOPICS: Simulation Techniques and Applications
:PUBLICATION_DATE: 2025-06-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2506.14850")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4415332979"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4415332979"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4415332979"))][Get cited by]]

OpenAlex: https://openalex.org/W4415332979 (Open access: True)
    
[[https://openalex.org/A5112198707][Shriram Maheshwari]], [[https://openalex.org/A5092741862][Janghoon Ock]], [[https://openalex.org/A5017163658][Adeesh Kolluru]], [[https://openalex.org/A5120057010][Amir Barati Farimani]], [[https://openalex.org/A5003442464][John R. Kitchin]], arXiv (Cornell University). None(None)] 2025. https://doi.org/10.48550/arxiv.2506.14850  ([[http://arxiv.org/pdf/2506.14850][pdf]])
     
Machine-learning force fields (MLFFs) have emerged as a promising solution for speeding up ab initio molecular dynamics (MD) simulations, where accurate force predictions are critical but often computationally expensive. In this work, we employ GemNet-T, a graph neural network model, as an MLFF and investigate two training strategies: (1) direct training on MD17 (10K samples) without pre-training, and (2) pre-training on the large-scale OC20 dataset followed by fine-tuning on MD17 (10K). While both approaches achieve low force mean absolute errors (MAEs), reaching 5 meV/A per atom, we find that lower force errors do not necessarily guarantee stable MD simulations. Notably, the pre-trained GemNet-T model yields significantly improved simulation stability, sustaining trajectories up to three times longer than the model trained from scratch. These findings underscore the value of pre-training on large, diverse datasets to capture complex molecular interactions and highlight that force MAE alone is not always a sufficient metric of MD simulation stability.    

    

* Long‐Read, High‐Resolution Sanger Sequencing by Micelle‐Tagging Electrophoresis  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4415411534
:TOPICS: Microfluidic and Capillary Electrophoresis Applications, Innovative Microfluidic and Catalytic Techniques Innovation, Microfluidic and Bio-sensing Technologies
:PUBLICATION_DATE: 2025-10-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/elps.70047")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4415411534"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4415411534"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4415411534"))][Get cited by]]

OpenAlex: https://openalex.org/W4415411534 (Open access: True)
    
[[https://openalex.org/A5111899237][R. Gamble]], [[https://openalex.org/A5008334952][H. Michael Wenz]], [[https://openalex.org/A5016837981][Bashar Mullah]], [[https://openalex.org/A5028147543][James Schneider]], Electrophoresis. None(None)] 2025. https://doi.org/10.1002/elps.70047 
     
ABSTRACT We demonstrate a gel‐free electrophoretic separation of Sanger sequencing fragments up to 782 bases in length using nonionic wormlike micelles as drag‐tags in micelle‐tagging electrophoresis (MTE). This is an increase of 280 bases over previous MTE methods and a nearly three‐fold improvement over end‐labeled free‐solution electrophoresis (ELFSE) methods that use covalently attached drag‐tags. For MTE, C18 alkane groups are attached to primers prior to their enzymatic extension. This alkane group provides a binding site for wormlike micelles composed of CiEj‐type nonionic surfactants in the running buffer. Transient attachment of micelles to the C18 alkane group provides a highly uniform drag, equal to that of an ssDNA fragment 309 bases long. To account for slight mobility differences among the BigDye chain terminators, we developed a two‐parameter time‐shifting procedure to align the electropherograms for each termination chemistry. The increase in read length for this low‐viscosity buffer (2.1 cP) is attributed to the alignment procedure, the large yet uniform drag, and the small degree of adsorption‐based band broadening.    

    
