#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Mon May 20 01:06:16 2024

Found 4 results from 2024-05-13 to 2024-05-20
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Experimental and Theoretical Evaluation of Feed Flow Collar Design for Shell Fed Hollow Fiber Membrane Modules  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4396974300
:TOPICS: Lattice Boltzmann Method for Complex Flows, Modern Electrostatic Gas Cleaning Technologies and Methods, Microchannel Heat Transfer and Cooling Technology
:PUBLICATION_DATE: 2024-05-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2172/2348930")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396974300"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396974300"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396974300"))][Get cited by]]

OpenAlex: https://openalex.org/W4396974300 (Open access: False)
    
[[https://openalex.org/A5037749425][Thien Tran]], [[https://openalex.org/A5098667099][Maya Schuchert]], [[https://openalex.org/A5041659494][Victor A. Kusuma]], [[https://openalex.org/A5034596712][Lili Sun]], [[https://openalex.org/A5093456232][Comfort Oluleke]], [[https://openalex.org/A5032502544][Nathan Diemler]], [[https://openalex.org/A5002137675][Lingxiang Zhu]], [[https://openalex.org/A5028498558][Grigorios Panagakos]], [[https://openalex.org/A5063620462][G. Glenn Lipscomb]], [[https://openalex.org/A5083623112][David Hui‐Kang]], No host. None(None)] 2024. https://doi.org/10.2172/2348930 
     
An experimental and theoretical study of module collar design is presented here. Hollow fiber membranes are prepared by dip coating a poly(vinylidene) (PVDF) support with a polydimethylsiloxane (PDMS) gutter layer and a Pebax 2533 selective layer. Fiber bundles with a well-defined fiber packing are prepared using a 3D printed module. A parallel fiber bundle consisting of 4-9 uniformly spaced fibers is created with printed tabs that align the fibers and create a tubesheet. The tabs are sealed within a printed case that possesses a series of external ports for gas introduction and removal. Uniquely, both port location and the use of a collar to assist fluid distribution in the shell can be varied for the same fiber bundle. Experimental measurements are compared to computational fluid dynamics (CFD) simulations. The experimental module design allows high-fidelity representation of the fiber bundle and module case in the simulations. Comparisons between experiment and simulation are in good agreement over a broad range of experimental conditions. The detrimental effect of having ports located too close, leading to stagnation regions, is captured as well as the beneficial effects of using a collar for shell-side fluid distribution around the fiber bundle. Such results help validate the use of CFD to develop high-performance module designs.    

    

* Optimization strategies for produced water networks with integrated desalination facilities  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4396978966
:TOPICS: Design and Management of Water Distribution Networks, Integrated Management of Water, Energy, and Food Resources, Advancements in Water Purification Technologies
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.compchemeng.2024.108738")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396978966"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396978966"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396978966"))][Get cited by]]

OpenAlex: https://openalex.org/W4396978966 (Open access: False)
    
[[https://openalex.org/A5054628015][Sakshi Naik]], [[https://openalex.org/A5015881602][Miguel Zamarripa]], [[https://openalex.org/A5048411560][Markus Drouven]], [[https://openalex.org/A5052825722][Lorenz T. Biegler]], Computers & chemical engineering. None(None)] 2024. https://doi.org/10.1016/j.compchemeng.2024.108738 
     
Optimal management and desalination of produced water is a major challenge for U.S. oil and gas development. Integrating rigorous desalination models into multi-period produced water network optimization problems presents several hurdles, which need to be tackled using advanced optimization strategies. In this work, a novel multi-period produced water network formulation with separate solid and liquid flows is introduced to avoid singularities at zero flows. Rigorous steady state desalination models based on mechanical vapor recompression are embedded at the desalination sites in the network model. An integrated optimization formulation is developed to co-optimize the design of desalination units along with the operation of the network. Furthermore, a more robust approach based on the trust region filter method is developed to efficiently integrate complex desalination models into the multi-period planning problem. Both optimization approaches are demonstrated on a produced water network from the PARETO library (Drouven et al., 2022) using thermal desalination units. Our results show that while the TRF and integrated approaches have comparable solve times, the TRF approach has better performance reliability in terms of solver convergence. Furthermore, the optimal solution obtained by embedding rigorous models into the network is significantly different than when desalination costs are approximated using simple cost models, which motivates further research in this field.    

    

* Self-organized Patterns in Predator-Prey Droplet Systems  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4397010234
:TOPICS: Self-Reconfigurable Robotic Systems and Modular Robotics, Theoretical and Computational Physics, Genomic Insights into Social Insects and Symbiosis
:PUBLICATION_DATE: 2024-05-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-15zsd")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397010234"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397010234"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397010234"))][Get cited by]]

OpenAlex: https://openalex.org/W4397010234 (Open access: True)
    
[[https://openalex.org/A5047262526][Yutong Liu]], [[https://openalex.org/A5034160371][R. Kailasham]], [[https://openalex.org/A5011172184][Pepijn G. Moerman]], [[https://openalex.org/A5018420940][Aditya S. Khair]], [[https://openalex.org/A5022036259][Lauren D. Zarzar]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-15zsd  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/6646831b21291e5d1d76a5e1/original/self-organized-patterns-in-predator-prey-droplet-systems.pdf][pdf]])
     
Non-equilibrium patterns are widespread in nature and often arise from the self-organization of constituents through nonreciprocal chemotactic interactions. In this study, we demonstrate how active oil-in-water droplet mixtures with predator-prey interactions can result in a variety of self-organized patterns. By manipulating physical parameters, the droplet diameter ratio and number ratio, we identify distinct classes of patterns within a binary droplet system, rationalize the pattern formation, and quantify motilities. Experimental results are recapitulated in numerical simulations using a minimal computational model that solely incorporates chemotactic interactions and steric repulsion among the constituents. The time evolution of the patterns is investigated and chemically explained. We also investigate how patterns vary with differing interaction strength by altering surfactant composition. Leveraging insights from the binary droplet system, the framework is extended to a ternary droplet mixture composed of multiple chasing droplet pairs to create chemically directed hierarchical organization. Our findings demonstrate how rationalizable, self-organized patterns can be programmed in a chemically minimal system and provide the basis for exploration of emergent organization and higher order complexity in active colloids.    

    

* Highly Permeable Rubbery Thin Film Composite Membranes for CO2 Capture from Steel Mills  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4397020614
:TOPICS: Membrane Gas Separation Technology, Catalytic Carbon Dioxide Hydrogenation, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2172/2349470")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4397020614"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4397020614"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4397020614"))][Get cited by]]

OpenAlex: https://openalex.org/W4397020614 (Open access: False)
    
[[https://openalex.org/A5002137675][Lingxiang Zhu]], [[https://openalex.org/A5037749425][Thien Tran]], [[https://openalex.org/A5076767088][Fangming Xiang]], [[https://openalex.org/A5041659494][Victor A. Kusuma]], [[https://openalex.org/A5093713938][Cheick Dosso]], [[https://openalex.org/A5079899169][Héctor A. Pedrozo]], [[https://openalex.org/A5028498558][Grigorios Panagakos]], [[https://openalex.org/A5098681635][Neil Pergar]], [[https://openalex.org/A5098681636][Brenda Petrilena]], [[https://openalex.org/A5021768097][David Hopkinson]], No host. None(None)] 2024. https://doi.org/10.2172/2349470 
     
This presentation will report the rational design and fabrication of NETL's highly permeable non-aging thin film composite (TFC) membranes for CO2 capture from various industrial point sources. This talk will also cover the design, computational fluid dynamic simulation, 3D printing, and permeation testing of plate-and-frame membrane modules for an upcoming field demonstration at U. S. Steel's Edgar Thomson Plant in Braddock, PA. The field test will demonstrate membrane-based CO2 capture from a blast furnace for decarbonization of steel manufacturing for the first time in the U.S. A mobile gas permeation test unit is currently under design and construction for the field test, which is scheduled to take place in 2025.    

    
