#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Thu Aug 28 01:27:52 2025

Found 2 results from 2025-08-21 to 2025-08-28
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* New Insights into how Electrolyte pH affects the Oxygen Reduction Reaction  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4413367859
:TOPICS: Fuel Cells and Related Materials, Analytical Chemistry and Sensors, Electrochemical sensors and biosensors
:PUBLICATION_DATE: 2025-08-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2025-qg2sr")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4413367859"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4413367859"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4413367859"))][Get cited by]]

OpenAlex: https://openalex.org/W4413367859 (Open access: True)
    
[[https://openalex.org/A5030622040][Jay T. Bender]], [[https://openalex.org/A5071284998][Rohan Yuri Sanspeur]], [[https://openalex.org/A5119366206][Nicolas Bueno Ponce]], [[https://openalex.org/A5106990669][Angel Valles]], [[https://openalex.org/A5106990670][Alyssa Uvodich]], [[https://openalex.org/A5077085087][Delia J. Milliron]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5018687349][Joaquin Resasco]], No host. None(None)] 2025. https://doi.org/10.26434/chemrxiv-2025-qg2sr 
     
Electrolyte pH is known to affect catalytic activity and selectivity for the oxygen reduction reaction (ORR). But a clear understanding of why ORR rates respond more strongly to pH over certain catalysts than others has not been developed. Here, we propose that pH effects on the ORR result from electric field induced changes in the binding energies of intermediates involved in kinetically relevant elementary steps. For strongly binding metals (Pt, Ir, Ru, Pd), whose rates are limited by the proton-coupled electron transfer (PCET) step to form *OOH or remove adsorbed OH (*OH), ORR rates are weakly affected by electrolyte pH. This behavior is observed because the binding energies of the reaction intermediates in these steps are minimally affected by electric field strength. The weak pH dependence is most pronounced for Pt, which shows essentially identical rates in acidic and alkaline electrolytes. For weakly binding metals (Au, Ag), whose rates are limited by non-PCET O2 adsorption, ORR rates increase significantly when moving from acidic to alkaline electrolytes. This strong pH dependence results from the stabilization of adsorbed O2 by the increasingly negative electric field present at the catalyst surface under alkaline conditions. We argue that modifying electrolyte pH does not change the rate-determining elementary step, but does decrease the apparent activation barrier for O2 adsorption over weakly binding catalysts. These arguments are substantiated by a combination of experimental kinetic studies and atomistic simulations.    

    

* Trees are much better at creating clouds and cooling the climate than we thought  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4413666866
:TOPICS: 
:PUBLICATION_DATE: 2016-10-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.64628/ab.fv9q7tsjc")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4413666866"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4413666866"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4413666866"))][Get cited by]]

OpenAlex: https://openalex.org/W4413666866 (Open access: False)
    
[[https://openalex.org/A5086004922][Hamish Gordon]], [[https://openalex.org/A5018704667][Catherine E. Scott]], No host. None(None)] 2016. https://doi.org/10.64628/ab.fv9q7tsjc 
     
No abstract    

    
