#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Sun Aug 24 01:48:02 2025

Found 4 results from 2025-08-17 to 2025-08-24
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Comparison of oxidation products generated from the reaction of α-pinene with hydroxyl radicals, chlorine atoms, and bromine atoms measured using ammonium adduct chemical ionization mass spectrometry  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4413187043
:TOPICS: Water Quality Monitoring and Analysis
:PUBLICATION_DATE: 2025-08-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2025-cpdrt")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4413187043"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4413187043"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4413187043"))][Get cited by]]

OpenAlex: https://openalex.org/W4413187043 (Open access: False)
    
[[https://openalex.org/A5051630368][Andrew T. Lambe]], [[https://openalex.org/A5062687219][Jordan Krechmer]], [[https://openalex.org/A5053220317][Anita M. Avery]], [[https://openalex.org/A5064213945][Mitchell W. Alton]], [[https://openalex.org/A5041685684][Neil M. Donahue]], [[https://openalex.org/A5062166400][Manjula R. Canagaratna]], No host. None(None)] 2025. https://doi.org/10.26434/chemrxiv-2025-cpdrt 
     
Halogen atoms play important but undercharacterized roles in atmospheric oxidation chemistry. Here, we report laboratory measurements of gas- and condensed-phase products formed from the oxidation of α-pinene by hydroxyl radicals (OH), chlorine atoms (Cl), and bromine atoms (Br) in an oxidation flow reactor (OFR). Products were detected using a Vocus proton-transfer time-of-flight reaction mass spectrometer (PTR-ToF-MS) operated with low-pressure ammonium adduct (NH4+) ionization and a Vaporization Inlet for Aerosols (VIA). We applied Positive Matrix Factorization (PMF) to classify precursor and product ions into early and later-generation oxidation products. While some common products were observed across all oxidants, significant compositional differences were also apparent. Vocus:VIA signal ratios were used to estimate volatility trends, revealing that more highly oxygenated compounds and many halogenated products contributed to SOA formation. Cl and Br oxidation led to the formation of oxygenated volatile organic compounds (OVOCs) and secondary organic aerosol (SOA), which retained halogen atoms, with Br-derived products exhibiting the lowest carbon oxidation state and the highest halogen retention. Halogenated oxidation products were less volatile than their non-halogenated counterparts. Photochemical modeling suggests that the fates of organic peroxy radicals (RO2) were primarily influenced by RO2 + HO2 reactions for α-pinene/OH, RO2 + Cl, RO2 + HO2, and potentially RO2 isomerization/autooxidation reactions for α-pinene/Cl, and RO2 + Br reactions for α-pinene/Br.    

    

* Rethinking Environmental Boundaries for Contaminants of Emerging Concern  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4413209924
:TOPICS: Toxic Organic Pollutants Impact, Environmental Justice and Health Disparities, Recycling and Waste Management Techniques
:PUBLICATION_DATE: 2025-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.atmosenv.2025.121492")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4413209924"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4413209924"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4413209924"))][Get cited by]]

OpenAlex: https://openalex.org/W4413209924 (Open access: True)
    
[[https://openalex.org/A5029339098][Ivan Kourtchev]], [[https://openalex.org/A5043418348][Max R. McGillen]], [[https://openalex.org/A5031616608][John Wenger]], [[https://openalex.org/A5041685684][Neil M. Donahue]], Atmospheric Environment. None(None)] 2025. https://doi.org/10.1016/j.atmosenv.2025.121492 
     
No abstract    

    

* Assessing modifications to the Abdul-Razzak and Ghan aerosol activation parameterization (version ARG2000) to improve simulated aerosol–cloud radiative effects in the UK Met Office Unified Model (UM version 13.0)  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4413228393
:TOPICS: Atmospheric chemistry and aerosols, Atmospheric aerosols and clouds, Atmospheric Ozone and Climate
:PUBLICATION_DATE: 2025-08-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/gmd-18-4899-2025")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4413228393"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4413228393"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4413228393"))][Get cited by]]

OpenAlex: https://openalex.org/W4413228393 (Open access: True)
    
[[https://openalex.org/A5005781295][Pratapaditya Ghosh]], [[https://openalex.org/A5079659440][Katherine J. Evans]], [[https://openalex.org/A5028113214][Daniel P. Grosvenor]], [[https://openalex.org/A5015919898][Hyun‐Gyu Kang]], [[https://openalex.org/A5023485909][Salil Mahajan]], [[https://openalex.org/A5014558136][Min Xu]], [[https://openalex.org/A5100441591][Wei Zhang]], [[https://openalex.org/A5086004922][Hamish Gordon]], Geoscientific model development. 18(15)] 2025. https://doi.org/10.5194/gmd-18-4899-2025 
     
Abstract. The representation of aerosol activation is a key source of uncertainty in global composition-climate model simulations of aerosol–cloud interactions. The Abdul-Razzak and Ghan (ARG) activation parameterization is used in several global and regional models that employ modal aerosol microphysics schemes. In this study, we investigate the ability of the ARG parameterization to reproduce simulations with a cloud parcel model and find its performance is sensitive to the geometric standard deviations (widths) of the lognormal aerosol modes. We recommend adjustments to three constant parameters in the ARG equations, which improve the performance of the parameterization for small mode widths and its ability to simulate activation in polluted conditions. For the accumulation mode width of 1.4 used in the Met Office Unified Model (UM), the modifications decrease the mean bias in the activated fraction of aerosols compared to a cloud parcel model from −6.6 % to +1.2 %. We implemented the improvements in the UM and compared simulated global cloud droplet concentrations with satellite observations. The simulated cloud radiative effect changes by −1.43 W m−2 (6 %) and aerosol indirect radiative forcing over the industrial period changes by −0.10 W m−2 (10 %).    

    

* New Insights into how Electrolyte pH affects the Oxygen Reduction Reaction  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4413367859
:TOPICS: Fuel Cells and Related Materials, Analytical Chemistry and Sensors, Electrochemical sensors and biosensors
:PUBLICATION_DATE: 2025-08-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2025-qg2sr")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4413367859"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4413367859"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4413367859"))][Get cited by]]

OpenAlex: https://openalex.org/W4413367859 (Open access: True)
    
[[https://openalex.org/A5030622040][Jay T. Bender]], [[https://openalex.org/A5071284998][Rohan Yuri Sanspeur]], [[https://openalex.org/A5119366206][Nicolas Bueno Ponce]], [[https://openalex.org/A5106990669][Angel E. Valles]], [[https://openalex.org/A5106990670][Alyssa K. Uvodich]], [[https://openalex.org/A5077085087][Delia J. Milliron]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5018687349][Joaquin Resasco]], No host. None(None)] 2025. https://doi.org/10.26434/chemrxiv-2025-qg2sr 
     
Electrolyte pH is known to affect catalytic activity and selectivity for the oxygen reduction reaction (ORR). But a clear understanding of why ORR rates respond more strongly to pH over certain catalysts than others has not been developed. Here, we propose that pH effects on the ORR result from electric field induced changes in the binding energies of intermediates involved in kinetically relevant elementary steps. For strongly binding metals (Pt, Ir, Ru, Pd), whose rates are limited by the proton-coupled electron transfer (PCET) step to form *OOH or remove adsorbed OH (*OH), ORR rates are weakly affected by electrolyte pH. This behavior is observed because the binding energies of the reaction intermediates in these steps are minimally affected by electric field strength. The weak pH dependence is most pronounced for Pt, which shows essentially identical rates in acidic and alkaline electrolytes. For weakly binding metals (Au, Ag), whose rates are limited by non-PCET O2 adsorption, ORR rates increase significantly when moving from acidic to alkaline electrolytes. This strong pH dependence results from the stabilization of adsorbed O2 by the increasingly negative electric field present at the catalyst surface under alkaline conditions. We argue that modifying electrolyte pH does not change the rate-determining elementary step, but does decrease the apparent activation barrier for O2 adsorption over weakly binding catalysts. These arguments are substantiated by a combination of experimental kinetic studies and atomistic simulations.    

    
