#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Fri Sep  6 01:16:02 2024

Found 2 results from 2024-08-30 to 2024-09-06
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Constraining Aerosol-Cloud Adjustments by Uniting Surface Observations with a Perturbed Parameter Ensemble  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4402053303
:TOPICS: Aerosols' Impact on Climate and Hydrological Cycle, Aeolian Geomorphology and Wind Erosion Dynamics, Low-Cost Air Quality Monitoring Systems
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-2024-2158")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402053303"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402053303"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402053303"))][Get cited by]]

OpenAlex: https://openalex.org/W4402053303 (Open access: True)
    
[[https://openalex.org/A5027787343][Anders Mikkelsen]], [[https://openalex.org/A5052404448][Daniel T. McCoy]], [[https://openalex.org/A5076884167][Trude Eidhammer]], [[https://openalex.org/A5016753222][Andrew Gettelman]], [[https://openalex.org/A5103217491][C. H. Song]], [[https://openalex.org/A5086004922][Hamish Gordon]], [[https://openalex.org/A5082829446][Isabel L. McCoy]], No host. None(None)] 2024. https://doi.org/10.5194/egusphere-2024-2158 
     
Abstract. Aerosol-cloud interactions (aci) are the largest source of uncertainty in inferring the magnitude of future warming consistent with the observational record. The effective radiative forcing due to aci (ERFaci) is dominated by liquid clouds and is composed of two terms: the change in cloud albedo due to redistributing liquid over a larger number of cloud droplets (Nd) and the change in cloud macrophysical properties due to changes in cloud microphysics. These terms are respectively referred to as the radiative forcing due to aci (RFaci) and aerosol-cloud adjustments. While the magnitude of RFaci is uncertain, its sign is confidently negative and results in a cooling in the historical record. In contrast, the adjustment of cloud liquid water path (LWP) to enhanced Nd and associated radiative forcing is uncertain in sign. Increased LWP in response to increased Nd is consistent with precipitation suppression while decreased LWP in response to increased Nd is consistent with enhanced evaporation from cloud top. Observational constraints of these processes are poor in part because of causal ambiguity in the relationship between Nd and LWP. To better understand this relationship, precipitation (P), Nd, and LWP surface observations from the Eastern North Atlantic (ENA) atmospheric observatory are combined with the output from a perturbed parameter ensemble (PPE) hosted in the Community Atmosphere Model version 6 (CAM6). This allows causal interpretation of observed covariability. Observations of precipitation and cloud from ENA constrain the range of possible LWP aerosol-cloud adjustments relative to the prior from the PPE by 15 %, resulting in a global value that is confidently positive (a historical cooling) ranging from 2.1 to 6.9 g/m2. It is found that observed covariability between Nd and LWP is dominated by coalescence scavenging and that this observed covariability is not strongly related to aerosol-cloud adjustments.    

    

* The Potential of Zero Total Charge Predicts Cation Effects for the Oxygen Reduction Reaction  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4402230343
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsenergylett.4c01897")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402230343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402230343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402230343"))][Get cited by]]

OpenAlex: https://openalex.org/W4402230343 (Open access: False)
    
[[https://openalex.org/A5030622040][Jay T. Bender]], [[https://openalex.org/A5071284998][Rohan Yuri Sanspeur]], [[https://openalex.org/A5106990669][Angel E. Valles]], [[https://openalex.org/A5106990670][Alyssa K. Uvodich]], [[https://openalex.org/A5077085087][Delia J. Milliron]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5018687349][Joaquin Resasco]], ACS Energy Letters. None(None)] 2024. https://doi.org/10.1021/acsenergylett.4c01897 
     
No abstract    

    
