#+filetags: CMU_Chemical_Engineering
#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Wed Feb 21 00:44:02 2024

Found 1 results from 2024-02-14 to 2024-02-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Utilizing modern computer architectures to solve mathematical optimization problems: A survey  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391848869
:TOPICS: Quantum Computing and Simulation, Parallel Computing and Performance Optimization, Optimization Methods in Machine Learning
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.compchemeng.2024.108627")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391848869"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391848869"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391848869"))][Get cited by]]

OpenAlex: https://openalex.org/W4391848869 (Open access: False)
    
[[https://openalex.org/A5015746295][David E. Bernal Neira]], [[https://openalex.org/A5030631754][Carl D. Laird]], [[https://openalex.org/A5017863327][Laurens Lueg]], [[https://openalex.org/A5020564160][Stuart M. Harwood]], [[https://openalex.org/A5048990981][Dimitar Trenev]], [[https://openalex.org/A5044443085][Davide Venturelli]], Computers & Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.compchemeng.2024.108627 
     
Numerical algorithms to solve mathematical optimization problems efficiently are essential to applications in many areas of engineering and computational science. To solve optimization problems of ever-increasing scale and complexity, we need methods that exploit emerging hardware systems. However, the complexities of specific architectures and their impact on performance can be challenging. This article provides an overview of emerging hardware architectures and how they are used to solve mathematical optimization problems. We focus on parallel high-performance computing architectures, which are well-established yet challenging to employ for optimization, as well as digital quantum computing, which has recently gained attention due to its potential for transformative computational performance. Furthermore, we highlight several other emerging hardware architectures that may become relevant for mathematical optimization. We intend for this review to encourage the optimization and process engineering communities to increasingly consider both hardware and software developments in the pursuit of superior computational performance.    

    
