#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Sun May 18 01:46:39 2025

Found 4 results from 2025-05-11 to 2025-05-18
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Optimal Retrofit of Carbon Capture and Electrification Technologies in Oil Refineries for Reducing Direct CO2 Emissions  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410269108
:TOPICS: Hybrid Renewable Energy Systems, Carbon Dioxide Capture Technologies, Extraction and Separation Processes
:PUBLICATION_DATE: 2025-05-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.iecr.4c04995")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410269108"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410269108"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410269108"))][Get cited by]]

OpenAlex: https://openalex.org/W4410269108 (Open access: True)
    
[[https://openalex.org/A5046238706][S. Chattopadhyay]], [[https://openalex.org/A5086436082][Kaliaperumal Karthikeyan]], [[https://openalex.org/A5021607259][Rahul Gandhi]], [[https://openalex.org/A5056017028][Ignacio E. Grossmann]], [[https://openalex.org/A5027983186][Ana I. Torres]], Industrial & Engineering Chemistry Research. None(None)] 2025. https://doi.org/10.1021/acs.iecr.4c04995 
     
No abstract    

    

* In vitro monitoring of Babesia microti infection dynamics in whole blood microenvironments  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410335725
:TOPICS: Vector-borne infectious diseases, Insect and Pesticide Research, Insect Pest Control Strategies
:PUBLICATION_DATE: 2025-05-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2025.05.07.652765")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410335725"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410335725"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410335725"))][Get cited by]]

OpenAlex: https://openalex.org/W4410335725 (Open access: False)
    
[[https://openalex.org/A5004641821][Chao Li]], [[https://openalex.org/A5117533304][Emily G. Bache]], [[https://openalex.org/A5117533305][Amy L. Apgar]], [[https://openalex.org/A5089697602][Danielle M. Tufts]], [[https://openalex.org/A5044695139][Tagbo H. R. Niepa]], No host. None(None)] 2025. https://doi.org/10.1101/2025.05.07.652765 
     
Babesiosis — a globally emerging tick-borne infectious disease primarily caused by the intraerythrocytic piroplasm parasite, Babesia microti — has traditionally been studied using animal models such as mice. Compared to animal models, microfluidic-based models offer advantages, including direct analysis of human samples (such as patient blood), enhanced assay capacity (including physical/optical access, consistency, and throughput), low costs, and easy adoption. Here, we report an open microfluidic platform named μ–Blood for monitoring B. microti infection dynamics in vitro. Compared to other microfluidic-based models, μ–Blood allows direct examination of infected and uninfected whole blood without preprocessing steps like blood dilution or cell isolation, minimizing observer artifacts and preserving the natural whole blood microenvironment. The system enables extended (days-long) monitoring of infection dynamics, including parasite identification, parasitemia measurement, and parasite-host cell interactions, using label-free phase contrast and fluorescence confocal microscopy. With its open microfluidic configuration, μ-Blood provides an in vitro model for studying blood-borne infections while maintaining integrity of the whole blood microenvironment.    

    

* Design and optimization of circular economy networks—A case study of PET  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410348848
:TOPICS: Sustainable Supply Chain Management, Sustainable Industrial Ecology, Recycling and Waste Management Techniques
:PUBLICATION_DATE: 2025-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.compchemeng.2025.109164")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410348848"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410348848"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410348848"))][Get cited by]]

OpenAlex: https://openalex.org/W4410348848 (Open access: True)
    
[[https://openalex.org/A5111285949][Abdulhakeem Ahmed]], [[https://openalex.org/A5087391017][Anoop N. Nair]], [[https://openalex.org/A5027983186][Ana I. Torres]], Computers & Chemical Engineering. None(None)] 2025. https://doi.org/10.1016/j.compchemeng.2025.109164 
     
No abstract    

    

* Photocatalytic effect of gold-zinc oxide composite nanostructures for the selective and controlled killing of antibiotic-resistant bacteria and the removal of resistant bacterial biofilms from the body  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410358349
:TOPICS: Nanoparticles: synthesis and applications, Nanoplatforms for cancer theranostics, Advanced Nanomaterials in Catalysis
:PUBLICATION_DATE: 2025-05-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1186/s40580-025-00488-z")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410358349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410358349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410358349"))][Get cited by]]

OpenAlex: https://openalex.org/W4410358349 (Open access: True)
    
[[https://openalex.org/A5089195105][Jongjun Park]], [[https://openalex.org/A5008417301][Tae Hui Bae]], [[https://openalex.org/A5101716327][S. Y. Kim]], [[https://openalex.org/A5109162928][Seong-Eun Park]], [[https://openalex.org/A5113936606][Yonghyun Choi]], [[https://openalex.org/A5018575134][Masayoshi Tanaka]], [[https://openalex.org/A5100462888][Jiwon Kim]], [[https://openalex.org/A5109441107][Jaehee Jang]], [[https://openalex.org/A5008435972][J. Yang]], [[https://openalex.org/A5100709327][Heeyoung Lee]], [[https://openalex.org/A5044695139][Tagbo H. R. Niepa]], [[https://openalex.org/A5109995093][Shin Hyuk Kang]], [[https://openalex.org/A5012952224][Jonghoon Choi]], Nano Convergence. 12(1)] 2025. https://doi.org/10.1186/s40580-025-00488-z 
     
Abstract Infections involving antibiotic-resistant bacteria have become a major problem. Pathogenic bacteria use mechanisms such as drug target bypass, target modification, and biofilm formation to evade treatment. To respond to these problems, antibacterial research using metal and metal oxide nanoparticles is currently active. Nanoparticles treat bacterial infections through reactive oxygen species generation or antibacterial ion release. However, their application has faced problems related to human compatibility, as they react non-specifically, targeting both mammalian and bacterial cells. In addition, ZnO nanoparticles show low antibacterial activity against Gram-negative bacteria. Thus, the demand for antibacterial substances with enhanced specificity and improved efficacy is increasing. We bound gold to the surface of ZnO nanoparticles, enabling photocatalytic and photothermal actions through visible light irradiation. To improve bacterial specificity, Concanavalin A (Con A), a lectin that can specifically target bacterial membrane lipopolysaccharides, was conjugated with the nanoparticles. We showed that Con A-conjugated Au/ZnO nanoparticles (Au/ZnO-Con A) exhibit photocatalytic and photothermal effects under white light, enhancing their antibacterial ability, and through enhanced specificity, increased antibacterial and anti-biofilm abilities were confirmed. The developed particles showed the potential to alleviate antibiotic resistance in a bacterial skin infection model, presenting a new platform for treating bacterial infections. Graphical Abstract    

    
