#+filetags: CMU_Chemical_Engineering
#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Fri Feb 16 00:43:01 2024

Found 1 results from 2024-02-09 to 2024-02-16
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Ligand binding kinetics of A2AR nanodiscs using fluorescence anisotropy  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391636753
:TOPICS: Nanoparticle-Based Drug Delivery Systems, Plasmonic Nanoparticles: Synthesis, Properties, and Applications, Click Chemistry in Chemical Biology and Drug Development
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.bpj.2023.11.2084")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391636753"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391636753"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391636753"))][Get cited by]]

OpenAlex: https://openalex.org/W4391636753 (Open access: False)
    
[[https://openalex.org/A5053137050][John M. Pettersen]], [[https://openalex.org/A5053252662][Anne S. Robinson]], Biophysical Journal. 123(3)] 2024. https://doi.org/10.1016/j.bpj.2023.11.2084 
     
G-protein-coupled receptors (GPCRs) make up the largest group of membrane proteins in the human body. Due to their favorable location in the cell membrane, GPCRs are extremely important drug targets, making up around 35% of all FDA-approved drugs. When a ligand binds to the extracellular portion of the GPCR, the protein undergoes a conformational change leading to a downstream signaling cascade that ultimately leads to a physiological change within the cell. Designing ligands to bind to a specific receptor, while also causing the desired physiological changes to occur, is an extremely challenging process. It has been suggested that early determination of ligand binding kinetics, such as, kon, koff, and drug-target residence time (RT) can aid in this design process over just equilibrium measurements. In this work we aimed to determine binding kinetics for labeled and unlabeled ligands using fluorescent anisotropy for the adenosine receptor (A2AR) that had been purified into nanodiscs, a lipid bilayer mimic, while also aiming to characterize nanodiscs as an improved method for evaluating membrane proteins. We determined fluorescent anisotropy serves as an easy and excellent method for determining ligand binding kinetics. We also determined nanodiscs improved the accuracy of ligand binding kinetics for both tracer and unlabeled ligands, increased receptor thermo- and kinetic stability compared to traditional micelle purification. These findings should facilitate further drug development for this class of receptors.    

    
