#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Sun Apr 21 01:07:45 2024

Found 2 results from 2024-04-14 to 2024-04-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* A Novel Mixed-Integer Linear Programming Formulation for Continuous-Time Inventory Routing  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4394788163
:TOPICS: Distributed Coordination in Online Robotics Research, Numerical Optimization Techniques, Vehicle Routing Problem and Variants
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4793503")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394788163"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394788163"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394788163"))][Get cited by]]

OpenAlex: https://openalex.org/W4394788163 (Open access: False)
    
[[https://openalex.org/A5048285644][Akang Wang]], [[https://openalex.org/A5073137913][X. Li]], [[https://openalex.org/A5045208880][Jeffrey E. Arbogast]], [[https://openalex.org/A5043503583][Zachary Wilson]], [[https://openalex.org/A5048485981][Chrysanthos E. Gounaris]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4793503 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Carbon nanomaterials‐based electrically conductive scaffolds for tissue engineering applications  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4394927677
:TOPICS: Biomedical Applications of Graphene Nanomaterials, Electrospun Nanofibers in Biomedical Applications, Neural Interface Technology
:PUBLICATION_DATE: 2024-04-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/mba2.76")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394927677"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394927677"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394927677"))][Get cited by]]

OpenAlex: https://openalex.org/W4394927677 (Open access: True)
    
[[https://openalex.org/A5095772138][Genevieve Abd]], [[https://openalex.org/A5003766948][Raquel Sanchez Diaz]], [[https://openalex.org/A5076052042][Anju Gupta]], [[https://openalex.org/A5044695139][Tagbo H. R. Niepa]], [[https://openalex.org/A5041703687][Kunal Mondal]], [[https://openalex.org/A5077698461][Seeram Ramakrishna]], [[https://openalex.org/A5052056626][Ashutosh Sharma]], [[https://openalex.org/A5082691724][Andrés Díaz Lantada]], [[https://openalex.org/A5071469750][Monsur Islam]], MedComm - Biomaterials and applications. 3(2)] 2024. https://doi.org/10.1002/mba2.76  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/mba2.76][pdf]])
     
Abstract In tissue engineering, the pivotal role of scaffolds is underscored, serving as key elements to emulate the native extracellular matrix. These scaffolds must provide structural integrity and support and supply electrical, mechanical, and chemical cues for cell and tissue growth. Notably, electrical conductivity plays a crucial role when dealing with tissues like bone, spinal, neural, and cardiac tissues. However, the typical materials used as tissue engineering scaffolds are predominantly polymers, which generally characteristically feature poor electrical conductivity. Therefore, it is often necessary to incorporate conductive materials into the polymeric matrix to yield electrically conductive scaffolds and further enable electrical stimulation. Among different conductive materials, carbon nanomaterials have attracted significant attention in developing conductive tissue engineering scaffolds, demonstrating excellent biocompatibility and bioactivity in both in vitro and in vivo settings. This article aims to comprehensively review the current landscape of carbon‐based conductive scaffolds, with a specific focus on their role in advancing tissue engineering for the regeneration and maturation of functional tissues, emphasizing the application of electrical stimulation. This review highlights the versatility of carbon‐based conductive scaffolds and addresses existing challenges and prospects, shedding light on the trajectory of innovative conductive scaffold development in tissue engineering.    

    
