#+filetags: CMU_Chemical_Engineering
#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Fri Jan 19 13:03:22 2024

Found 6 results from 2024-01-05 to 2024-01-19
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]
** Nitrate Radicals Suppress Biogenic New Particle Formation from Monoterpene Oxidation   
:PROPERTIES:
:ID: https://openalex.org/W4390668739
:DOI: https://doi.org/10.1021/acs.est.3c07958
:AUTHORS: Dandan Li, Wei Huang, Dongyu Wang, Mingyi Wang, Joel A. Thornton, Lucía Caudillo, Birte Rörup, Ruby Marten, Wiebke Scholz, Henning Finkenzeller, Guillaume Marie, Urs Baltensperger, David M. Bell, Zoé Brasseur, Joachim Curtius, Lubna Dada, Jonathan Duplissy, X. Gong, Armin Hansel, Xu‐Cheng He, Victoria Hofbauer, Heikki Junninen, Jordan E. Krechmer, Andreas Kürten, Houssni Lamkaddam, Katrianne Lehtipalo, Brandon Lopez, Yingge Ma, Naser G. A. Mahfouz, Hanna E. Manninen, Bernhard Mentler, S. Perrier, Tuukka Petäj̈ä, Joschka Pfeifer, Maxim Philippov, Meredith Schervish, Siegfried Schobesberger, Jiali Shen, Mihnea Surdu, Sophie Tomaz, Rainer Volkamer, Xinke Wang, Stefan K. Weber, André Welti, Douglas R. Worsnop, Yusheng Wu, Chao Yan, Marcel Zauner-Wieczorek, Markku Kulmala, J. Kirkby, Neil M. Donahue, Christian George, Imad El Haddad, Federico Bianchi, Matthieu Riva
:HOST: No host
:END:

Dandan Li, Wei Huang, Dongyu Wang, Mingyi Wang, Joel A. Thornton, Lucía Caudillo, Birte Rörup, Ruby Marten, Wiebke Scholz, Henning Finkenzeller, Guillaume Marie, Urs Baltensperger, David M. Bell, Zoé Brasseur, Joachim Curtius, Lubna Dada, Jonathan Duplissy, X. Gong, Armin Hansel, Xu‐Cheng He, Victoria Hofbauer, Heikki Junninen, Jordan E. Krechmer, Andreas Kürten, Houssni Lamkaddam, Katrianne Lehtipalo, Brandon Lopez, Yingge Ma, Naser G. A. Mahfouz, Hanna E. Manninen, Bernhard Mentler, S. Perrier, Tuukka Petäj̈ä, Joschka Pfeifer, Maxim Philippov, Meredith Schervish, Siegfried Schobesberger, Jiali Shen, Mihnea Surdu, Sophie Tomaz, Rainer Volkamer, Xinke Wang, Stefan K. Weber, André Welti, Douglas R. Worsnop, Yusheng Wu, Chao Yan, Marcel Zauner-Wieczorek, Markku Kulmala, J. Kirkby, Neil M. Donahue, Christian George, Imad El Haddad, Federico Bianchi, Matthieu Riva, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.est.3c07958")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390668739"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390668739"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390668739"))][Get cited by]]

OpenAlex: https://openalex.org/W4390668739
    
Dandan Li, Wei Huang, Dongyu Wang, Mingyi Wang, Joel A. Thornton, Lucía Caudillo, Birte Rörup, Ruby Marten, Wiebke Scholz, Henning Finkenzeller, Guillaume Marie, Urs Baltensperger, David M. Bell, Zoé Brasseur, Joachim Curtius, Lubna Dada, Jonathan Duplissy, X. Gong, Armin Hansel, Xu‐Cheng He, Victoria Hofbauer, Heikki Junninen, Jordan E. Krechmer, Andreas Kürten, Houssni Lamkaddam, Katrianne Lehtipalo, Brandon Lopez, Yingge Ma, Naser G. A. Mahfouz, Hanna E. Manninen, Bernhard Mentler, S. Perrier, Tuukka Petäj̈ä, Joschka Pfeifer, Maxim Philippov, Meredith Schervish, Siegfried Schobesberger, Jiali Shen, Mihnea Surdu, Sophie Tomaz, Rainer Volkamer, Xinke Wang, Stefan K. Weber, André Welti, Douglas R. Worsnop, Yusheng Wu, Chao Yan, Marcel Zauner-Wieczorek, Markku Kulmala, J. Kirkby, Neil M. Donahue, Christian George, Imad El Haddad, Federico Bianchi, Matthieu Riva, No host. https://doi.org/10.1021/acs.est.3c07958
    
Highly oxygenated organic molecules (HOMs) are a major source of new particles that affect the Earth’s climate. HOM production from the oxidation of volatile organic compounds (VOCs) occurs during both the day and night and can lead to new particle formation (NPF). However, NPF involving organic vapors has been reported much more often during the daytime than during nighttime. Here, we show that the nitrate radicals (NO3), which arise predominantly at night, inhibit NPF during the oxidation of monoterpenes based on three lines of observational evidence: NPF experiments in the CLOUD (Cosmics Leaving OUtdoor Droplets) chamber at CERN (European Organization for Nuclear Research), radical chemistry experiments using an oxidation flow reactor, and field observations in a wetland that occasionally exhibits nocturnal NPF. Nitrooxy-peroxy radicals formed from NO3 chemistry suppress the production of ultralow-volatility organic compounds (ULVOCs) responsible for biogenic NPF, which are covalently bound peroxy radical (RO2) dimer association products. The ULVOC yield of α-pinene in the presence of NO3 is one-fifth of that resulting from ozone chemistry alone. Even trace amounts of NO3 radicals, at sub-parts per trillion level, suppress the NPF rate by a factor of 4. Ambient observations further confirm that when NO3 chemistry is involved, monoterpene NPF is completely turned off. Our results explain the frequent absence of nocturnal biogenic NPF in monoterpene (α-pinene)-rich environments.    

    

** <i>Environmental Science: Atmospheres</i> is four and so much more   
:PROPERTIES:
:ID: https://openalex.org/W4390701128
:DOI: https://doi.org/10.1039/d3ea90050a
:AUTHORS: Neil M. Donahue
:HOST: No host
:END:

Neil M. Donahue, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ea90050a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390701128"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390701128"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390701128"))][Get cited by]]

OpenAlex: https://openalex.org/W4390701128
    
Neil M. Donahue, No host. https://doi.org/10.1039/d3ea90050a
    
Editor-in-Chief Neil Donahue reflects on the third year of Environmental Science: Atmospheres and looks ahead at the plans for year 4.    

    

** Formation of secondary organic aerosol from wildfire emissions enhanced by long-time ageing   
:PROPERTIES:
:ID: https://openalex.org/W4390735401
:DOI: https://doi.org/10.1038/s41561-023-01355-4
:AUTHORS: Yuhong He, Bin Zhao, Yafei Wang, Richard Valorso, Xing Chang, Dejia Yin, Bo Feng, M. Camredon, Bernard Aumont, Abraham Dearden, Shantanu H. Jathar, Manish Shrivastava, Z. J. Jiang, C. D. Cappa, L. D. Yee, John H. Seinfeld, Jiming Hao, Neil M. Donahue
:HOST: Nature Geoscience
:END:

Yuhong He, Bin Zhao, Yafei Wang, Richard Valorso, Xing Chang, Dejia Yin, Bo Feng, M. Camredon, Bernard Aumont, Abraham Dearden, Shantanu H. Jathar, Manish Shrivastava, Z. J. Jiang, C. D. Cappa, L. D. Yee, John H. Seinfeld, Jiming Hao, Neil M. Donahue, Nature Geoscience. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41561-023-01355-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390735401"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390735401"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390735401"))][Get cited by]]

OpenAlex: https://openalex.org/W4390735401
    
Yuhong He, Bin Zhao, Yafei Wang, Richard Valorso, Xing Chang, Dejia Yin, Bo Feng, M. Camredon, Bernard Aumont, Abraham Dearden, Shantanu H. Jathar, Manish Shrivastava, Z. J. Jiang, C. D. Cappa, L. D. Yee, John H. Seinfeld, Jiming Hao, Neil M. Donahue, Nature Geoscience. https://doi.org/10.1038/s41561-023-01355-4
    
No abstract    

    

** Controlling Bond Scission Pathways of Isopropanol on Fe- and Pt-Modified Mo<sub>2</sub>N Model Surfaces and Powder Catalysts   
:PROPERTIES:
:ID: https://openalex.org/W4390939862
:DOI: https://doi.org/10.1021/acscatal.3c04700
:AUTHORS: William N. Porter, Hilda Mera, Wenjie Liao, Zhexi Lin, Ping Liu, John R. Kitchin, Jingguang G. Chen
:HOST: ACS Catalysis
:END:

William N. Porter, Hilda Mera, Wenjie Liao, Zhexi Lin, Ping Liu, John R. Kitchin, Jingguang G. Chen, ACS Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c04700")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390939862"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390939862"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390939862"))][Get cited by]]

OpenAlex: https://openalex.org/W4390939862
    
William N. Porter, Hilda Mera, Wenjie Liao, Zhexi Lin, Ping Liu, John R. Kitchin, Jingguang G. Chen, ACS Catalysis. https://doi.org/10.1021/acscatal.3c04700
    
Biomass valorization can be used to produce value-added chemicals and fuels from renewable biomass resources by upgrading them via selective bond scission while retaining certain functional groups. Specifically, upgrading biomass through the dehydrogenation of alcohols to carbonyl compounds has gained interest as a method of utilizing biomass-derived alcohols while additionally producing H2. In this work, isopropanol was used as a probe molecule to control bond scission selectivity over Fe- and Pt-modified molybdenum nitride (Mo2N) model surfaces and powder catalysts. Trends in the selectivity toward dehydration and dehydrogenation were dependent on both the type and coverage of the metal overlayer on model surfaces. These results were then extended to the corresponding powder catalysts to demonstrate how model surface studies can inform the design of supported catalysts. Density functional theory calculations provided insights into controlling the dehydration and dehydrogenation pathways. This work shows that a fundamental understanding of the reactivity and intermediates on Mo2N-based model surfaces can be applied to understand the catalytic performance of metal-modified Mo2N powder catalysts, and also demonstrates that Mo2N-based catalysts are potentially promising materials for upgrading biomass-derived oxygenates.    

    

** A computational investigation of high-flux plate-and-frame membrane stacks for post-combustion carbon capture   
:PROPERTIES:
:ID: https://openalex.org/W4390833787
:DOI: None
:AUTHORS: Cheick Dosso, Lingxiang Zhu, Victor A. Kusuma, David Hui‐Kang, Héctor A. Pedrozo, Lorenz T. Biegler, Grigorios Panagakos
:HOST: OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)
:END:

Cheick Dosso, Lingxiang Zhu, Victor A. Kusuma, David Hui‐Kang, Héctor A. Pedrozo, Lorenz T. Biegler, Grigorios Panagakos, OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information). None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390833787"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390833787"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390833787"))][Get cited by]]

OpenAlex: https://openalex.org/W4390833787
    
Cheick Dosso, Lingxiang Zhu, Victor A. Kusuma, David Hui‐Kang, Héctor A. Pedrozo, Lorenz T. Biegler, Grigorios Panagakos, OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information). None
    
No abstract    

    

** IDAES-PSE 1.13.0 Release   
:PROPERTIES:
:ID: https://openalex.org/W4390690350
:DOI: https://doi.org/10.18141/2278834
:AUTHORS: Andrew Lee, Dan Gunter, K. Beattie, Miguel Zamarripa, Timothy V. Bartholomew, Douglas Allan, Bethany L. Nicholson, Adam Atia, John Eslick, John Daniel Siirola, Brandon Paul, Alexander W. Dowling, Anca Ostace, Alejandro R. Garciadiego, Radhakrishna Tumbalam Gooty, Ludovico Bianchi, Anuja Deshpande, Jaffer Ghouse, Robert B. Parker, P. Yang, Carl D. Laird, Makayla Shepherd, Gao Xian, Quang Minh Le, Oluwamayowa Amusat, Marissa R Engle, Andres J Calderon
:HOST: OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)
:END:

Andrew Lee, Dan Gunter, K. Beattie, Miguel Zamarripa, Timothy V. Bartholomew, Douglas Allan, Bethany L. Nicholson, Adam Atia, John Eslick, John Daniel Siirola, Brandon Paul, Alexander W. Dowling, Anca Ostace, Alejandro R. Garciadiego, Radhakrishna Tumbalam Gooty, Ludovico Bianchi, Anuja Deshpande, Jaffer Ghouse, Robert B. Parker, P. Yang, Carl D. Laird, Makayla Shepherd, Gao Xian, Quang Minh Le, Oluwamayowa Amusat, Marissa R Engle, Andres J Calderon, OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information). None(None)] 2022.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18141/2278834")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390690350"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390690350"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390690350"))][Get cited by]]

OpenAlex: https://openalex.org/W4390690350
    
Andrew Lee, Dan Gunter, K. Beattie, Miguel Zamarripa, Timothy V. Bartholomew, Douglas Allan, Bethany L. Nicholson, Adam Atia, John Eslick, John Daniel Siirola, Brandon Paul, Alexander W. Dowling, Anca Ostace, Alejandro R. Garciadiego, Radhakrishna Tumbalam Gooty, Ludovico Bianchi, Anuja Deshpande, Jaffer Ghouse, Robert B. Parker, P. Yang, Carl D. Laird, Makayla Shepherd, Gao Xian, Quang Minh Le, Oluwamayowa Amusat, Marissa R Engle, Andres J Calderon, OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information). https://doi.org/10.18141/2278834
    
No abstract    

    
