#+filetags: CMU_Chemical_Engineering
#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Mon Feb 12 00:44:23 2024

Found 3 results from 2024-02-05 to 2024-02-12
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* A mixed integer linear programming approach for the design of chemical process families  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391543039
:TOPICS: State-of-the-Art in Process Optimization under Uncertainty, Model Predictive Control in Industrial Processes, Process Fault Detection and Diagnosis in Industries
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.compchemeng.2024.108620")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391543039"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391543039"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391543039"))][Get cited by]]

OpenAlex: https://openalex.org/W4391543039 (Open access: False)
    
[[https://openalex.org/A5007541692][Georgia Stinchfield]], [[https://openalex.org/A5086695747][Josh Morgan]], [[https://openalex.org/A5054628015][Sakshi Naik]], [[https://openalex.org/A5052825722][Lorenz T. Biegler]], [[https://openalex.org/A5054865843][John Eslick]], [[https://openalex.org/A5045412845][C.A. Jacobson]], [[https://openalex.org/A5061592458][David C. Miller]], [[https://openalex.org/A5047681120][John Daniel Siirola]], [[https://openalex.org/A5015881602][Miguel Zamarripa]], [[https://openalex.org/A5034855502][Chen Zhang]], [[https://openalex.org/A5026984704][Qi Zhang]], [[https://openalex.org/A5030631754][Carl D. Laird]], Computers & Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.compchemeng.2024.108620 
     
The need for rapid and widespread deployment of new technologies to address climate change goals (e.g., deep, economy-wide decarbonization) presents new opportunities for advancing modular design strategies. Conventional engineering approaches focus on unique designs for each installation, while missing opportunities for manufacturing standardization. Extending insights from the automotive industry, we optimize a platform of common unit module designs while simultaneously designing an entire family of process variants that make use of that platform. This reduces engineering effort, deployment timelines, and manufacturing costs. We propose a nonlinear generalized disjunctive programming formulation and convert this to an efficient mixed-integer linear programming (MILP) formulation through discretization of the design space. We formulate our optimization in Pyomo with costing from IDAES, and we demonstrate the computational performance and solution quality on a water treatment desalination system from the PARETO framework and a carbon capture system built in Aspen Plus® as part of CCSI2.    

    

* Opyrability: A Python package for process operability analysis  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391573070
:TOPICS: Process Fault Detection and Diagnosis in Industries, Optimization Techniques in Simulation Modeling, Software Reliability Assessment and Prediction
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21105/joss.05966")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391573070"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391573070"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391573070"))][Get cited by]]

OpenAlex: https://openalex.org/W4391573070 (Open access: True)
    
[[https://openalex.org/A5033439256][Victor Alves]], [[https://openalex.org/A5059801671][San Dinh]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5028703671][Vitor Gazzaneo]], [[https://openalex.org/A5049224685][Juan C. Carrasco]], [[https://openalex.org/A5008955099][Fernando V. Lima]], Journal of open source software. 9(94)] 2024. https://doi.org/10.21105/joss.05966  ([[https://joss.theoj.org/papers/10.21105/joss.05966.pdf][pdf]])
     
No abstract    

    

* Ligand binding kinetics of A2AR nanodiscs using fluorescence anisotropy  :CMU_Chemical_Engineering:
:PROPERTIES:
:ID: https://openalex.org/W4391636753
:TOPICS: Nanoparticle-Based Drug Delivery Systems, Plasmonic Nanoparticles: Synthesis, Properties, and Applications, Click Chemistry in Chemical Biology and Drug Development
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.bpj.2023.11.2084")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391636753"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391636753"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391636753"))][Get cited by]]

OpenAlex: https://openalex.org/W4391636753 (Open access: False)
    
[[https://openalex.org/A5053137050][John M. Pettersen]], [[https://openalex.org/A5053252662][Anne S. Robinson]], Biophysical Journal. 123(3)] 2024. https://doi.org/10.1016/j.bpj.2023.11.2084 
     
G-protein-coupled receptors (GPCRs) make up the largest group of membrane proteins in the human body. Due to their favorable location in the cell membrane, GPCRs are extremely important drug targets, making up around 35% of all FDA-approved drugs. When a ligand binds to the extracellular portion of the GPCR, the protein undergoes a conformational change leading to a downstream signaling cascade that ultimately leads to a physiological change within the cell. Designing ligands to bind to a specific receptor, while also causing the desired physiological changes to occur, is an extremely challenging process. It has been suggested that early determination of ligand binding kinetics, such as, kon, koff, and drug-target residence time (RT) can aid in this design process over just equilibrium measurements. In this work we aimed to determine binding kinetics for labeled and unlabeled ligands using fluorescent anisotropy for the adenosine receptor (A2AR) that had been purified into nanodiscs, a lipid bilayer mimic, while also aiming to characterize nanodiscs as an improved method for evaluating membrane proteins. We determined fluorescent anisotropy serves as an easy and excellent method for determining ligand binding kinetics. We also determined nanodiscs improved the accuracy of ligand binding kinetics for both tracer and unlabeled ligands, increased receptor thermo- and kinetic stability compared to traditional micelle purification. These findings should facilitate further drug development for this class of receptors.    

    
