#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Thu May  1 01:46:35 2025

Found 6 results from 2025-04-24 to 2025-05-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Generative machine learning approaches to optimization  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4409750178
:TOPICS: Advanced Data Processing Techniques
:PUBLICATION_DATE: 2025-04-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2025-hk886")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4409750178"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4409750178"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4409750178"))][Get cited by]]

OpenAlex: https://openalex.org/W4409750178 (Open access: False)
    
[[https://openalex.org/A5033439256][Victor Alves]], [[https://openalex.org/A5003442464][John R. Kitchin]], No host. None(None)] 2025. https://doi.org/10.26434/chemrxiv-2025-hk886 
     
Solving optimization problems, especially for nonlinear and constrained systems, is a challenge. Decades of specialized algorithms have been developed for general and special cases of root ﬁnding, minimization (including constraints), for parameter estimation, and mapping connected spaces. These approaches typically require a model, or set of equations, and then analytical, or iterative numerical approaches can be used to ﬁnd a solution, and in some special cases a globally best solution can be found and proven. In this work we present an alternative approach to solving these problems that is based in generative machine learning models. The idea is these models either estimate a joint probability distribution of input and output variables, or are able to transform a distribution of inputs to a distribution of outputs (or vice versa). Then, by suitable conditioning (specifying desired properties of some variables), the solutions to these problems can be obtained by sampling the distribution, or by transformation of a distribution sample to the solution space. We illustrate the approach with Gaussian mixture models, which approximate the joint probability distribution. We show examples in root ﬁnding, unconstrained and constrained optimization, parameter estimation and mapping input and output spaces. This work is intended to be pedagogical to show how a generative model can be used to solve problems in optimization. We discuss some limitations of this approach, but conclude the approach has promise and is diﬀerent than existing approaches.    

    

* Science acceleration and accessibility with self-driving labs  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4409768533
:TOPICS: Scientific Computing and Data Management, Biomedical and Engineering Education, E-Learning and Knowledge Management
:PUBLICATION_DATE: 2025-04-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-025-59231-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4409768533"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4409768533"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4409768533"))][Get cited by]]

OpenAlex: https://openalex.org/W4409768533 (Open access: True)
    
[[https://openalex.org/A5036375800][Richard B. Canty]], [[https://openalex.org/A5009993647][Jeffrey A. Bennett]], [[https://openalex.org/A5001647002][Keith A. Brown]], [[https://openalex.org/A5085344547][Tonio Buonassisi]], [[https://openalex.org/A5048552375][Sergei V. Kalinin]], [[https://openalex.org/A5003442464][John R. Kitchin]], [[https://openalex.org/A5102919383][Benji Maruyama]], [[https://openalex.org/A5004408105][R. G. Moore]], [[https://openalex.org/A5073376584][Joshua Schrier]], [[https://openalex.org/A5031911852][Martin Seifrid]], [[https://openalex.org/A5070476394][Shijing Sun]], [[https://openalex.org/A5083050334][Tejs Vegge]], [[https://openalex.org/A5087390873][Milad Abolhasani]], Nature Communications. 16(1)] 2025. https://doi.org/10.1038/s41467-025-59231-1 
     
No abstract    

    

* Constraining aerosol–cloud adjustments by uniting surface observations with a perturbed parameter ensemble  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4409780216
:TOPICS: Atmospheric aerosols and clouds, Atmospheric chemistry and aerosols, Meteorological Phenomena and Simulations
:PUBLICATION_DATE: 2025-04-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/acp-25-4547-2025")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4409780216"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4409780216"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4409780216"))][Get cited by]]

OpenAlex: https://openalex.org/W4409780216 (Open access: True)
    
[[https://openalex.org/A5115775480][August Mikkelsen]], [[https://openalex.org/A5052404448][Daniel T. McCoy]], [[https://openalex.org/A5076884167][Trude Eidhammer]], [[https://openalex.org/A5016753222][Andrew Gettelman]], [[https://openalex.org/A5103217491][Ci Song]], [[https://openalex.org/A5086004922][Hamish Gordon]], [[https://openalex.org/A5082829446][Isabel L. McCoy]], Atmospheric chemistry and physics. 25(8)] 2025. https://doi.org/10.5194/acp-25-4547-2025 
     
Abstract. Aerosol–cloud interactions (ACIs) are the largest source of uncertainty in inferring the magnitude of future warming consistent with the observational record. The effective radiative forcing due to ACI (ERFaci) is dominated by liquid clouds and is composed of two terms: the change in cloud albedo due to redistributing liquid over a larger number of cloud droplets (Nd) and the change in cloud macrophysical properties due to changes in cloud microphysics. These terms are, respectively, referred to as the radiative forcing due to ACI (RFaci) and aerosol–cloud adjustments. While the magnitude of RFaci is uncertain, its sign is confidently negative and results in a cooling in the historical record. In contrast, the adjustment of cloud liquid water path (LWP) to enhanced Nd and associated radiative forcing is uncertain in sign. Increased LWP in response to increased Nd is consistent with precipitation suppression, while decreased LWP in response to increased Nd is consistent with enhanced evaporation from cloud top. Observational constraints of these processes are poor in part because of causal ambiguity in the relationship between Nd and LWP. To better understand this relationship, precipitation (P), Nd, and LWP surface observations from the Eastern North Atlantic (ENA) atmospheric observatory are combined with the output from a perturbed parameter ensemble (PPE) hosted in the Community Atmosphere Model version 6 (CAM6). This allows for causal interpretation of observed covariability. Observations of precipitation and cloud from ENA constrain the range of possible LWP aerosol–cloud adjustments relative to the prior from the PPE by 15 %, resulting in a global value that is confidently positive (a historical cooling) ranging from 2.1 to 6.9 g m−2. It is found that observed covariability between Nd and LWP is dominated by coalescence scavenging and that this observed covariability is not strongly related to aerosol–cloud adjustments.    

    

* Generative machine learning approaches to optimization  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4409823420
:TOPICS: Advanced Data Processing Techniques
:PUBLICATION_DATE: 2025-04-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2025-hk886-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4409823420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4409823420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4409823420"))][Get cited by]]

OpenAlex: https://openalex.org/W4409823420 (Open access: False)
    
[[https://openalex.org/A5033439256][Victor Alves]], [[https://openalex.org/A5003442464][John R. Kitchin]], No host. None(None)] 2025. https://doi.org/10.26434/chemrxiv-2025-hk886-v2 
     
Solving optimization problems, especially for nonlinear and constrained systems, is a challenge. Decades of specialized algorithms have been developed for general and special cases of root ﬁnding, minimization (including constraints), for parameter estimation, and mapping connected spaces. These approaches typically require a model, or set of equations, and then analytical, or iterative numerical approaches can be used to ﬁnd a solution, and in some special cases a globally best solution can be found and proven. In this work we present an alternative approach to solving these problems that is based in generative machine learning models. The idea is these models either estimate a joint probability distribution of input and output variables, or are able to transform a distribution of inputs to a distribution of outputs (or vice versa). Then, by suitable conditioning (specifying desired properties of some variables), the solutions to these problems can be obtained by sampling the distribution, or by transformation of a distribution sample to the solution space. We illustrate the approach with Gaussian mixture models, which approximate the joint probability distribution. We show examples in root ﬁnding, unconstrained and constrained optimization, parameter estimation and mapping input and output spaces. This work is intended to be pedagogical to show how a generative model can be used to solve problems in optimization. We discuss some limitations of this approach, but conclude the approach has promise and is diﬀerent than existing approaches.    

    

* Hydrophobic Ion Pairing for Simple, Non-Toxic Transfection  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4409903359
:TOPICS: RNA Interference and Gene Delivery
:PUBLICATION_DATE: 2025-04-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2025.04.25.650611")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4409903359"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4409903359"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4409903359"))][Get cited by]]

OpenAlex: https://openalex.org/W4409903359 (Open access: False)
    
[[https://openalex.org/A5026863228][Mikaela A. Gray]], [[https://openalex.org/A5094043004][Michelle Seeler]], [[https://openalex.org/A5068381010][Catalina Montoya]], [[https://openalex.org/A5060132590][Jaeyoung Park]], [[https://openalex.org/A5055570461][D. Linh]], [[https://openalex.org/A5010666650][Kathryn A. Whitehead]], [[https://openalex.org/A5038617325][Julie A. Champion]], No host. None(None)] 2025. https://doi.org/10.1101/2025.04.25.650611 
     
Although biomacromolecules require intracellular delivery for therapeutic effect, existing transfection agents are often characterized by high cost, low efficiency, and/or cytotoxicity. Here, we describe a new transfection approach based on hydrophobic ion pairing (HIP), which involves the simple mixing of a hydrophobic counterion with charged biomacromolecules. Among tested cargoes (proteins, siRNA, and pDNA), the HIP siRNA system performed especially well, achieving silencing in fibroblasts (80%), T cells (90%), and neurons (70%). HIP siRNA was also highly potent in mice, with tropism dependent on the route of administration. Most notably, intraperitoneal administration enabled ~40% LAMP-1 knockdown in the pancreas, and intravenous delivery resulted in a remarkable 80% silencing in the heart. Heart delivery was also highly selectively, with no significant knockdown in the liver. Together, these data demonstrate a new, inexpensive approach to biomacromolecular delivery with the potential to target difficult-to-transfect organs, thus expanding the therapeutic potential of nucleic acids.    

    

* Event constrained programming  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4409907298
:TOPICS: Advanced Control Systems Optimization, Simulation Techniques and Applications, Risk and Portfolio Optimization
:PUBLICATION_DATE: 2025-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.compchemeng.2025.109145")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4409907298"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4409907298"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4409907298"))][Get cited by]]

OpenAlex: https://openalex.org/W4409907298 (Open access: True)
    
[[https://openalex.org/A5067396423][Daniel Ovalle]], [[https://openalex.org/A5117368934][Stefan Mazzadi]], [[https://openalex.org/A5030631754][Carl D. Laird]], [[https://openalex.org/A5056017028][Ignacio E. Grossmann]], [[https://openalex.org/A5036452308][Joshua L. Pulsipher]], Computers & Chemical Engineering. None(None)] 2025. https://doi.org/10.1016/j.compchemeng.2025.109145 
     
No abstract    

    
