#+TITLE: CMU Chemical Engineering
Description: Papers by people in the Department of Chemical Engineering at CMU
Created on Thu May 22 01:41:07 2025

Found 5 results from 2025-05-15 to 2025-05-22
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=author.id%3Ahttps%3A//openalex.org/A5063320716%7Chttps%3A//openalex.org/A5052825722%7Chttps%3A//openalex.org/A5010387303%7Chttps%3A//openalex.org/A5041685684%7Chttps%3A//openalex.org/A5040842816%7Chttps%3A//openalex.org/A5048633127%7Chttps%3A//openalex.org/A5048485981%7Chttps%3A//openalex.org/A5086004922%7Chttps%3A//openalex.org/A5056017028%7Chttps%3A//openalex.org/A5018420940%7Chttps%3A//openalex.org/A5003442464%7Chttps%3A//openalex.org/A5055700187%7Chttps%3A//openalex.org/A5030631754%7Chttps%3A//openalex.org/A5044695139%7Chttps%3A//openalex.org/A5028498558%7Chttps%3A//openalex.org/A5053252662%7Chttps%3A//openalex.org/A5028147543%7Chttps%3A//openalex.org/A5037506064%7Chttps%3A//openalex.org/A5027983186%7Chttps%3A//openalex.org/A5010666650]]

* Photocatalytic effect of gold-zinc oxide composite nanostructures for the selective and controlled killing of antibiotic-resistant bacteria and the removal of resistant bacterial biofilms from the body  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410358349
:TOPICS: Nanoparticles: synthesis and applications, Nanoplatforms for cancer theranostics, Advanced Nanomaterials in Catalysis
:PUBLICATION_DATE: 2025-05-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1186/s40580-025-00488-z")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410358349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410358349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410358349"))][Get cited by]]

OpenAlex: https://openalex.org/W4410358349 (Open access: True)
    
[[https://openalex.org/A5089195105][Jongjun Park]], [[https://openalex.org/A5008417301][Tae Hui Bae]], [[https://openalex.org/A5101716327][S. Y. Kim]], [[https://openalex.org/A5109162928][Seong-Eun Park]], [[https://openalex.org/A5113936606][Yonghyun Choi]], [[https://openalex.org/A5018575134][Masayoshi Tanaka]], [[https://openalex.org/A5100462888][Jiwon Kim]], [[https://openalex.org/A5109441107][Jaehee Jang]], [[https://openalex.org/A5008435972][J. Yang]], [[https://openalex.org/A5100709327][Heeyoung Lee]], [[https://openalex.org/A5044695139][Tagbo H. R. Niepa]], [[https://openalex.org/A5109995093][Shin Hyuk Kang]], [[https://openalex.org/A5012952224][Jonghoon Choi]], Nano Convergence. 12(1)] 2025. https://doi.org/10.1186/s40580-025-00488-z 
     
Abstract Infections involving antibiotic-resistant bacteria have become a major problem. Pathogenic bacteria use mechanisms such as drug target bypass, target modification, and biofilm formation to evade treatment. To respond to these problems, antibacterial research using metal and metal oxide nanoparticles is currently active. Nanoparticles treat bacterial infections through reactive oxygen species generation or antibacterial ion release. However, their application has faced problems related to human compatibility, as they react non-specifically, targeting both mammalian and bacterial cells. In addition, ZnO nanoparticles show low antibacterial activity against Gram-negative bacteria. Thus, the demand for antibacterial substances with enhanced specificity and improved efficacy is increasing. We bound gold to the surface of ZnO nanoparticles, enabling photocatalytic and photothermal actions through visible light irradiation. To improve bacterial specificity, Concanavalin A (Con A), a lectin that can specifically target bacterial membrane lipopolysaccharides, was conjugated with the nanoparticles. We showed that Con A-conjugated Au/ZnO nanoparticles (Au/ZnO-Con A) exhibit photocatalytic and photothermal effects under white light, enhancing their antibacterial ability, and through enhanced specificity, increased antibacterial and anti-biofilm abilities were confirmed. The developed particles showed the potential to alleviate antibiotic resistance in a bacterial skin infection model, presenting a new platform for treating bacterial infections. Graphical Abstract    

    

* Surrogate model optimization: a comparison case study with pooling problems of CO2 point sources  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410472923
:TOPICS: Advanced Multi-Objective Optimization Algorithms, Advanced Control Systems Optimization, Process Optimization and Integration
:PUBLICATION_DATE: 2025-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.compchemeng.2025.109199")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410472923"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410472923"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410472923"))][Get cited by]]

OpenAlex: https://openalex.org/W4410472923 (Open access: False)
    
[[https://openalex.org/A5079899169][Héctor Pedrozo]], [[https://openalex.org/A5015881602][Miguel Zamarripa]], [[https://openalex.org/A5007868705][A. Uribe-Rodríguez]], [[https://openalex.org/A5028498558][Grigorios Panagakos]], [[https://openalex.org/A5042182449][M. Soledad Díaz]], [[https://openalex.org/A5052825722][Lorenz T. Biegler]], Computers & Chemical Engineering. None(None)] 2025. https://doi.org/10.1016/j.compchemeng.2025.109199 
     
No abstract    

    

* Magnetically Responsive Nanocultures for Direct Microbial Assessment in Soil Environments  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410477537
:TOPICS: Magnetic and Electromagnetic Effects
:PUBLICATION_DATE: 2025-05-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2025.05.17.654660")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410477537"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410477537"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410477537"))][Get cited by]]

OpenAlex: https://openalex.org/W4410477537 (Open access: False)
    
[[https://openalex.org/A5006410485][Huda Usman]], [[https://openalex.org/A5080442414][Mehdi Molaei]], [[https://openalex.org/A5073414050][Stephen D. House]], [[https://openalex.org/A5082397792][Martin F. Haase]], [[https://openalex.org/A5089222578][Cindi L. Dennis]], [[https://openalex.org/A5044695139][Tagbo H. R. Niepa]], No host. None(None)] 2025. https://doi.org/10.1101/2025.05.17.654660 
     
Cultivating microorganisms in native-like conditions is vital for bioprospecting and accessing currently unculturable species. However, there remains a gap in scalable tools that can both mimic native microenvironments and enable targeted recovery of microbes from complex settings. Such approaches are essential to advance our understanding of microbial ecology, predict community functions, and discover novel biotherapeutics. We present magnetic nanocultures, a high-throughput microsystem for isolating and growing environmental microbes under near-native conditions. These nanoliter-scale bioreactors are encapsulated in semi-permeable membranes that form magnetic polymeric microcapsules using iron oxide nanoparticles within polydimethylsiloxane-based shells. This design offers mechanical stability and magnetic actuation, enabling efficient retrieval from soil-like environments. The nanocultures are optimized for optical and biological properties to support microbial encapsulation, growth, and sorting. Our study demonstrates the feasibility of using magnetically responsive microenvironments to cultivate elusive microbes, offering a promising platform for discovering previously uncultured or unknown microbial species.    

    

* Advancing aerosol science through early career research  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410485568
:TOPICS: Air Quality Monitoring and Forecasting
:PUBLICATION_DATE: 2025-05-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1080/02786826.2025.2468594")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410485568"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410485568"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410485568"))][Get cited by]]

OpenAlex: https://openalex.org/W4410485568 (Open access: False)
    
[[https://openalex.org/A5055700187][Coty N. Jen]], [[https://openalex.org/A5067019268][James F. Davies]], Aerosol Science and Technology. 59(7)] 2025. https://doi.org/10.1080/02786826.2025.2468594 
     
No abstract    

    

* Synthetic Strategy for mRNA Encapsulation and Gene Delivery with Nanoscale Metal‐Organic Frameworks  :CMU_Chemical_Engineering:
:PROPERTIES:
:UUID: https://openalex.org/W4410507430
:TOPICS: RNA Interference and Gene Delivery, Advanced biosensing and bioanalysis techniques, Metal-Organic Frameworks: Synthesis and Applications
:PUBLICATION_DATE: 2025-05-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202504465")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4410507430"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4410507430"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4410507430"))][Get cited by]]

OpenAlex: https://openalex.org/W4410507430 (Open access: True)
    
[[https://openalex.org/A5012514972][Harrison Lawson]], [[https://openalex.org/A5100729447][Nguyễn Huy Hoàng]], [[https://openalex.org/A5026347472][Keng‐Jung Lee]], [[https://openalex.org/A5050359036][Nattarat Wongsuwan]], [[https://openalex.org/A5095379199][Ayesha Tupe]], [[https://openalex.org/A5110813392][Mengrou Lu]], [[https://openalex.org/A5049474410][Mariah L. Arral]], [[https://openalex.org/A5085559862][Anne Behre]], [[https://openalex.org/A5051529193][Zihan Ling]], [[https://openalex.org/A5010666650][Kathryn A. Whitehead]], [[https://openalex.org/A5086659893][Adam W. Feinberg]], [[https://openalex.org/A5101438045][Xi Ren]], [[https://openalex.org/A5086903169][Siyang Zheng]], Advanced Functional Materials. None(None)] 2025. https://doi.org/10.1002/adfm.202504465 
     
Abstract Metal‐organic frameworks (MOFs) have evolved from uses in catalysis and gas storage to exciting applications in biomedicine, particularly in drug delivery. Initially, MOFs are primarily used to deliver small molecules, recent innovations have shifted focus toward more complex nucleic acids like DNA, short guide RNA (sgRNA), and short interfering RNA (siRNA). Remarkably, no studies to date have demonstrated the encapsulation and delivery of messenger RNA (mRNA) via MOFs in vitro and in vivo. This study addresses that gap by identifying synthetic conditions to encapsulate and deliver mRNA using zeolitic imidazole framework‐8 (ZIF‐8). Early attempts show mRNA loading in ZIF‐8 but loss of mRNA in biological media. To overcome this challenge, polyethyleneimine (PEI) is incorporated into the formulation, forming a robust polymer complex core‐MOF shell particle. This system stabilizes mRNA complexes and delays their release, resulting in effective protein expression in multiple cell lines and mice, performing on par with commercial lipid‐based systems. Here, the first investigation into thermally stable mRNA storage using ZIF‐8 demonstrates successful protein expression after three months of room‐temperature storage in vitro and one month in vivo. These findings broaden the scope of MOF‐based therapeutic delivery and open new avenues for long‐term mRNA storage and transport.    

    
