#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Sat Oct  5 01:19:03 2024

Found 77 results from 2024-09-28 to 2024-10-05
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Review for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934411
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934411"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934411"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934411"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934411 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v1/review2 
     
No abstract    

    

* Decision letter for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935014
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-04-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935014"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935014"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935014"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935014 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v2/decision1 
     
No abstract    

    

* Intrinsic Electron Transfer in Heteronuclear Dual‐Atom Sites Facilitates Selective Electrocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402993961
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202403778")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402993961"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402993961"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402993961"))][Get cited by]]

OpenAlex: https://openalex.org/W4402993961 (Open access: False)
    
[[https://openalex.org/A5101926099][Qi Tang]], [[https://openalex.org/A5101853152][Qi Hao]], [[https://openalex.org/A5086452619][Qian Zhu]], [[https://openalex.org/A5020591091][Junxiu Wu]], [[https://openalex.org/A5058587719][Keke Huang]], [[https://openalex.org/A5100399849][Kai Liu]], [[https://openalex.org/A5100674628][Jun Lü]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202403778 
     
Abstract The metal–metal (M 1 –M 2 ) interactions in heteronuclear dual‐atom catalysts (HNDACs) significantly optimize the electronic properties of the active sites, resulting in the promotion of the reaction kinetics in electrocatalysis. However, the regulation mechanisms in these M 1 –M 2 dual‐atom sites still remain unclear. Herein, the intrinsic electron transfer in Fe–Zn dual‐atom sites are revealed for facilitating electrocatalytic carbon dioxide reduction (ECO 2 R) to carbon monoxide (CO). The electronegativity difference between the Fe and Zn centers induces the specific electron transfer from Zn to Fe, which regulates the electron structures of the active Zn sites, leading to the optimized reaction pathway of CO 2 ‐to‐CO conversion on these sites. The Fe–Zn HNDAC (FeZnNC) exhibits superior ECO 2 R performances than the single‐atom Fe/Zn catalysts (FeNC and ZnNC) in the typical H‐cell system, the maximum CO partial current density on FeZnNC reaches more than 3.3 and 1.8 folds of those on FeNC and ZnNC, respectively. More importantly, in a strongly acidic medium (pH = 1), FeZnNC achieves CO Faradaic efficiencies greater than 94% in the current density range of 100–400 mA cm −2 . This work uncovers the intrinsic electron transfer at the heteronuclear diatomic sites, providing new insights for the rational design of high‐performance HNDACs toward industrial electrocatalysis.    

    

* Ugi's amine based coordination polymers as a synergistic catalysts for electrocatalytic reduction of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403033444
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dt01181c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403033444"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403033444"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403033444"))][Get cited by]]

OpenAlex: https://openalex.org/W4403033444 (Open access: False)
    
[[https://openalex.org/A5090357376][Mikhail Khrizanforov]], [[https://openalex.org/A5107686405][Farida F. Nailieva]], [[https://openalex.org/A5015946707][Kamil Ivshin]], [[https://openalex.org/A5055400630][Almaz Zagidullin]], [[https://openalex.org/A5093839011][Anastasiia P. Samorodnova]], [[https://openalex.org/A5041409633][Ruslan P. Shekurov]], [[https://openalex.org/A5095934822][Polina Milyukova]], [[https://openalex.org/A5065148995][Artem Laskin]], [[https://openalex.org/A5063649629][Alexander S. Novikov]], [[https://openalex.org/A5032894349][Vasili A. Miluykov]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d4dt01181c 
     
The escalating concentration of carbon dioxide in the atmosphere is a pressing environmental concern, necessitating the development of efficient technologies for CO 2 reduction and utilization. In this context, metal-organic frameworks...    

    

* Back Cover: Metal–Organic Framework Supported Low‐Nuclearity Cluster Catalysts for Highly Selective Carbon Dioxide Electroreduction to Ethanol  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403082653
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202416813")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403082653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403082653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403082653"))][Get cited by]]

OpenAlex: https://openalex.org/W4403082653 (Open access: False)
    
[[https://openalex.org/A5100381379][Bing Shao]], [[https://openalex.org/A5010225600][Du Shu Huang]], [[https://openalex.org/A5008056492][Rui‐Kang Huang]], [[https://openalex.org/A5031239250][Xing‐Lu He]], [[https://openalex.org/A5050700483][Yan Luo]], [[https://openalex.org/A5102689986][Yi‐Lei Xiang]], [[https://openalex.org/A5101860097][Linbin Jiang]], [[https://openalex.org/A5042836811][Min Dong]], [[https://openalex.org/A5008199157][Shixiong Li]], [[https://openalex.org/A5100350970][Zhong Zhang]], [[https://openalex.org/A5065774274][Jin Huang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202416813 
     
No abstract    

    

* Review for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934444
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934444"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934444"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934444"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934444 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v1/review1 
     
No abstract    

    

* Decision letter for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934858
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-04-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934858"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934858"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934858"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934858 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v1/decision1 
     
No abstract    

    

* Author response for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934933
:TOPICS: Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-04-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v2/response1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934933"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934933 (Open access: False)
    
[[https://openalex.org/A5041734836][Ryan J. R. Jones]], [[https://openalex.org/A5103079823][Yungchieh Lai]], [[https://openalex.org/A5030566949][Dan Guevarra]], [[https://openalex.org/A5073163389][Kevin Kan]], [[https://openalex.org/A5033925671][Joel A. Haber]], [[https://openalex.org/A5037026533][John M. Gregoire]], No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v2/response1 
     
No abstract    

    

* Graphene-Based Photocatalysts for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403072741
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-3-031-66260-7_29")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403072741"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403072741"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403072741"))][Get cited by]]

OpenAlex: https://openalex.org/W4403072741 (Open access: False)
    
[[https://openalex.org/A5055420228][José M. Barrera‐Andrade]], [[https://openalex.org/A5014043779][Elim Albiter]], [[https://openalex.org/A5076263633][Miguel A. Valenzuela]], [[https://openalex.org/A5063052194][E. Rojas García]], Advanced structured materials. None(None)] 2024. https://doi.org/10.1007/978-3-031-66260-7_29 
     
No abstract    

    

* Tandem electrocatalysis for CO2 reduction to multi-carbons  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403005598
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-09-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11426-024-2144-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403005598"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403005598"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403005598"))][Get cited by]]

OpenAlex: https://openalex.org/W4403005598 (Open access: False)
    
[[https://openalex.org/A5102715021][X. N. Li]], [[https://openalex.org/A5045124309][Tianxiang Yan]], [[https://openalex.org/A5001369399][Yichen Meng]], [[https://openalex.org/A5102665350][Zhanpeng Liang]], [[https://openalex.org/A5000657358][Tianying Zhang]], [[https://openalex.org/A5018909513][Haoyuan Chi]], [[https://openalex.org/A5008104343][Ziting Fan]], [[https://openalex.org/A5008657732][Yifan Jin]], [[https://openalex.org/A5101413103][Haoran Zhang]], [[https://openalex.org/A5100394033][Sheng Zhang]], Science China Chemistry. None(None)] 2024. https://doi.org/10.1007/s11426-024-2144-0 
     
No abstract    

    

* The Electrode/Electrolyte Interface Study during the Electrochemical CO2 Reduction in Acidic Electrolytes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935861
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202415894")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935861"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935861"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935861"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935861 (Open access: False)
    
[[https://openalex.org/A5081466371][Yao Yao]], [[https://openalex.org/A5078369945][Ernest Pahuyo Delmo]], [[https://openalex.org/A5005645517][Minhua Shao]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202415894 
     
Electrochemical CO2 Reduction (CO2R) in acidic electrolytes has gained significant attention owing to higher carbon efficiency and stability than in alkaline counterparts. However, the proton source and the role of alkali cations for CO2R are still under debate. By using rotating ring disk electrode and surface‐enhanced infrared absorption spectroscopy, we find that a neutral/alkaline environment at the interface is necessary for CO2R even in acidic electrolytes. We also confirm that water molecules, rather than protons serve as the proton source for CO2R. Alkali cations in the outer Helmholtz plane activate H2O and promote the desorption of adsorbed carbon monoxide. Additionally, the solvated CO2, or CO2(aq), is the actual reactant for CO2R. This study provides a deeper understanding of the electrode/electrolyte interface during CO2R in acidic electrolytes and sheds light on further performance improvement of this system.    

    

* The Electrode/Electrolyte Interface Study during the Electrochemical CO2 Reduction in Acidic Electrolytes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935594
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202415894")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935594"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935594"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935594"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935594 (Open access: False)
    
[[https://openalex.org/A5103940466][Yulin Yao]], [[https://openalex.org/A5078369945][Ernest Pahuyo Delmo]], [[https://openalex.org/A5006297542][Yu Zhang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202415894 
     
Electrochemical CO2 Reduction (CO2R) in acidic electrolytes has gained significant attention owing to higher carbon efficiency and stability than in alkaline counterparts. However, the proton source and the role of alkali cations for CO2R are still under debate. By using rotating ring disk electrode and surface‐enhanced infrared absorption spectroscopy, we find that a neutral/alkaline environment at the interface is necessary for CO2R even in acidic electrolytes. We also confirm that water molecules, rather than protons serve as the proton source for CO2R. Alkali cations in the outer Helmholtz plane activate H2O and promote the desorption of adsorbed carbon monoxide. Additionally, the solvated CO2, or CO2(aq), is the actual reactant for CO2R. This study provides a deeper understanding of the electrode/electrolyte interface during CO2R in acidic electrolytes and sheds light on further performance improvement of this system.    

    

* CO2 electrochemical reduction to formic acid: An overview of process sustainability  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402999323
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ccst.2024.100308")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402999323"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402999323"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402999323"))][Get cited by]]

OpenAlex: https://openalex.org/W4402999323 (Open access: False)
    
[[https://openalex.org/A5107668608][Zeyad M. Ghazi]], [[https://openalex.org/A5066670339][Dina Ewis]], [[https://openalex.org/A5070862521][Hazim Qiblawey]], [[https://openalex.org/A5011669590][Muftah H. El‐Naas]], Carbon Capture Science & Technology. 13(None)] 2024. https://doi.org/10.1016/j.ccst.2024.100308 
     
No abstract    

    

* Effect of Interfacial Electric Field on 2D Metal/Graphene Electrocatalysts for CO2 Reduction Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402966995
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Thermoelectric Materials
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402966995"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402966995"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402966995"))][Get cited by]]

OpenAlex: https://openalex.org/W4402966995 (Open access: False)
    
[[https://openalex.org/A5052590925][Jinwon Cho]], [[https://openalex.org/A5041107674][Faisal M. Alamgir]], [[https://openalex.org/A5090363901][Seung Soon Jang]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401673 
     
Understanding the influence of local electric fields on electrochemical reactions is crucial for designing highly selective electrocatalysts for CO2 reduction reactions (CO2RR). In this study, we provide a theoretical investigation of the effect of the local electric field induced by the negative‐biased electrode and cations in the electrolyte on the energetics and reaction kinetics of CO2RR on 2D hybrid metal/graphene electrocatalysts. Our findings reveal that the electronic structures of the CO2 molecule undergo substantial modification, resulting in the increased adsorption energy of CO­2 on metal/graphene structures, thus reducing the initial barrier of the CO2RR mechanism. This field‐assisted CO2RR mechanism promotes CO production while suppressing HCOOH production. Our findings highlight the potential of manipulating electric fields to tailor the pathways of CO2RR, providing new avenues designing selective electrocatalysts.    

    

* Strained Cu(111) surface can be catalytic efficient for C–C coupling in CO2 electrochemical reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403032159
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0216818")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403032159"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403032159"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403032159"))][Get cited by]]

OpenAlex: https://openalex.org/W4403032159 (Open access: True)
    
[[https://openalex.org/A5102402335][Yunfang Xu]], [[https://openalex.org/A5105697328][Y. L. Han]], [[https://openalex.org/A5100427812][Lixin Zhang]], AIP Advances. 14(10)] 2024. https://doi.org/10.1063/5.0216818 
     
It is well accepted that the Cu(100) surface is catalytic active for C–C coupling in CO2 reduction. However, the (100) surface is less active for the preceding CO* formation process and, most importantly, less stable than other surfaces. In this work, we investigate the relationship between catalytic effects and general factors such as coordination number and spacing (strain) of the Cu surface atoms. We find that the former affects the CO* formation only and the latter affects both the CO* formation and the subsequent C–C coupling. Among all the strained surfaces with larger atomic spacing, the more stable Cu(111) surface is extraordinary and outperforms Cu(100) and the high index surfaces for CO2 reduction to C2 on Cu.    

    

* Harnessing the Power of Graphene: A Critical Analysis of Graphene-Based Photocatalysts for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402917848
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-3-031-68464-7_18")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402917848"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402917848"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402917848"))][Get cited by]]

OpenAlex: https://openalex.org/W4402917848 (Open access: False)
    
[[https://openalex.org/A5050048610][Mahrukh Khan]], [[https://openalex.org/A5023916972][Mohammad Naeem Khan]], [[https://openalex.org/A5101340229][Mehrab Khan]], [[https://openalex.org/A5103123183][Hafsa Javaid]], [[https://openalex.org/A5075512873][Sara Musaddiq]], Advanced structured materials. None(None)] 2024. https://doi.org/10.1007/978-3-031-68464-7_18 
     
No abstract    

    

* Precise Synthesis of Dual‐single‐atom Electrocatalysts through Pre‐coordination‐directed in situ Confinement for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402962730
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-09-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202415223")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402962730"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402962730"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402962730"))][Get cited by]]

OpenAlex: https://openalex.org/W4402962730 (Open access: False)
    
[[https://openalex.org/A5037156563][Peng Rao]], [[https://openalex.org/A5038939329][Xing‐Qi Han]], [[https://openalex.org/A5043799303][Haochen Sun]], [[https://openalex.org/A5101840025][Fangyuan Wang]], [[https://openalex.org/A5003447105][Ying Liang]], [[https://openalex.org/A5100336948][Jing Li]], [[https://openalex.org/A5053821178][Daoxiong Wu]], [[https://openalex.org/A5003012361][Xiaodong Shi]], [[https://openalex.org/A5079901404][Zhenye Kang]], [[https://openalex.org/A5023491714][Zhengpei Miao]], [[https://openalex.org/A5017687334][Peilin Deng]], [[https://openalex.org/A5024069386][Xinlong Tian]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202415223 
     
Dual‐single‐atom catalysts (DSACs) are the next paradigm shift in single‐atom catalysts because of the enhanced performance brought about by the synergistic effects between adjacent bimetallic pairs. However, there are few methods for synthesizing DSACs with precise bimetallic structures. Herein, a pre‐coordination strategy is proposed to precisely synthesize a library of DSACs. This strategy ensures the selective and effective coordination of two metals via phthalocyanines with specific coordination sites, such as –F– and –OH–. Subsequently, in‐situ confinement inhibits the migration of metal pairs during high‐temperature pyrolysis, and obtains the DSACs with precisely constructed metal pairs. Despite changing synthetic parameters, including transition metal centers, metal pairs, and spatial geometry, the products exhibit similar atomic metal pairs dispersion properties, demonstrating the universality of the strategy. The pre‐coordination strategy synthesized DSACs shows significant CO2 reduction reaction performance in both flow‐cell and practical rechargeable Zn‐CO2 batteries. This work not only provides new insights into the precise synthesis of DSACs, but also offers guidelines for the accelerated discovery of efficient catalysts.    

    

* Precise Synthesis of Dual‐single‐atom Electrocatalysts through Pre‐coordination‐directed in situ Confinement for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402962769
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-09-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202415223")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402962769"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402962769"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402962769"))][Get cited by]]

OpenAlex: https://openalex.org/W4402962769 (Open access: False)
    
[[https://openalex.org/A5037156563][Peng Rao]], [[https://openalex.org/A5038939329][Xing‐Qi Han]], [[https://openalex.org/A5043799303][Haochen Sun]], [[https://openalex.org/A5101840025][Fangyuan Wang]], [[https://openalex.org/A5003447105][Ying Liang]], [[https://openalex.org/A5100336948][Jing Li]], [[https://openalex.org/A5053821178][Daoxiong Wu]], [[https://openalex.org/A5003012361][Xiaodong Shi]], [[https://openalex.org/A5079901404][Zhenye Kang]], [[https://openalex.org/A5023491714][Zhengpei Miao]], [[https://openalex.org/A5017687334][Peilin Deng]], [[https://openalex.org/A5024069386][Xinlong Tian]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202415223 
     
Dual‐single‐atom catalysts (DSACs) are the next paradigm shift in single‐atom catalysts because of the enhanced performance brought about by the synergistic effects between adjacent bimetallic pairs. However, there are few methods for synthesizing DSACs with precise bimetallic structures. Herein, a pre‐coordination strategy is proposed to precisely synthesize a library of DSACs. This strategy ensures the selective and effective coordination of two metals via phthalocyanines with specific coordination sites, such as –F– and –OH–. Subsequently, in‐situ confinement inhibits the migration of metal pairs during high‐temperature pyrolysis, and obtains the DSACs with precisely constructed metal pairs. Despite changing synthetic parameters, including transition metal centers, metal pairs, and spatial geometry, the products exhibit similar atomic metal pairs dispersion properties, demonstrating the universality of the strategy. The pre‐coordination strategy synthesized DSACs shows significant CO2 reduction reaction performance in both flow‐cell and practical rechargeable Zn‐CO2 batteries. This work not only provides new insights into the precise synthesis of DSACs, but also offers guidelines for the accelerated discovery of efficient catalysts.    

    

* Porous nickel-based catalyst doped with fluorine can efficiently electrocatalyze the reduction of CO2 to CO  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402971244
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.176771")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402971244"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402971244"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402971244"))][Get cited by]]

OpenAlex: https://openalex.org/W4402971244 (Open access: False)
    
[[https://openalex.org/A5101335981][Beifang Lu]], [[https://openalex.org/A5048906150][Tianxia Liu]], [[https://openalex.org/A5100668226][Li Jia]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.176771 
     
No abstract    

    

* Z-scheme ZnIn2S4/CuxO heterostructure on flexible substrate for efficient photothermal catalytic CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402980246
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.161369")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402980246"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402980246"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402980246"))][Get cited by]]

OpenAlex: https://openalex.org/W4402980246 (Open access: False)
    
[[https://openalex.org/A5083270177][Jiping Shi]], [[https://openalex.org/A5071810183][Liuqing Hua]], [[https://openalex.org/A5050887627][Lu Ruan]], [[https://openalex.org/A5100635716][Xingjian Zhang]], [[https://openalex.org/A5101635375][Zhengdao Li]], [[https://openalex.org/A5026722987][Fengyun Su]], [[https://openalex.org/A5100353880][Xin Li]], [[https://openalex.org/A5100959252][Haiquan Xie]], [[https://openalex.org/A5074136896][Yong Zhou]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.161369 
     
No abstract    

    

* Zirconium-doped ultrathin copper nanowires for C1 and C2+ products in electrochemical CO2 reduction reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403077551
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.114591")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403077551"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403077551"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403077551"))][Get cited by]]

OpenAlex: https://openalex.org/W4403077551 (Open access: True)
    
[[https://openalex.org/A5014445605][Wuyang Lin]], [[https://openalex.org/A5012436930][Matteo Palma]], [[https://openalex.org/A5076994358][Devis Di Tommaso]], Molecular Catalysis. 569(None)] 2024. https://doi.org/10.1016/j.mcat.2024.114591 
     
No abstract    

    

* Co Cluster-Modified Ni Nanoparticles with Superior Light-Driven Thermocatalytic Co2 Reduction by Ch4  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403093962
:TOPICS: Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels, Advancements in Density Functional Theory
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4976153")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403093962"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403093962"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403093962"))][Get cited by]]

OpenAlex: https://openalex.org/W4403093962 (Open access: False)
    
[[https://openalex.org/A5029731724][Qian Zhang]], [[https://openalex.org/A5100331926][Mei Li]], [[https://openalex.org/A5101769539][Yuhua Zhang]], [[https://openalex.org/A5101705073][Na Sun]], [[https://openalex.org/A5059984618][Dan Cheng]], [[https://openalex.org/A5100601973][Peng Sun]], [[https://openalex.org/A5054075598][Shaowen Wu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4976153 
     
No abstract    

    

* Rare-earth metal neodymium anchored into graphene as a promising CO2 reduction electrocatalyst by regulating the coordination environment  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403044828
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.105203")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403044828"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403044828"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403044828"))][Get cited by]]

OpenAlex: https://openalex.org/W4403044828 (Open access: False)
    
[[https://openalex.org/A5100620150][Siying Liu]], [[https://openalex.org/A5003167045][Huohai Yang]], [[https://openalex.org/A5063446819][Xingbo Ge]], [[https://openalex.org/A5101532301][Yingjie Feng]], [[https://openalex.org/A5032775500][Xiaoyue Fu]], [[https://openalex.org/A5100363117][Xin Chen]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.105203 
     
No abstract    

    

* Life Cycle Assessment of Cement Industry with Co2 Capture and Purification: Environmental Feasibility and Synergistic Emission Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402940883
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Zeolite Chemistry and Catalysis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4970428")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402940883"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402940883"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402940883"))][Get cited by]]

OpenAlex: https://openalex.org/W4402940883 (Open access: False)
    
[[https://openalex.org/A5010702767][Qingchuan Zhao]], [[https://openalex.org/A5023325607][Lin Huang]], [[https://openalex.org/A5091547176][Wenjing Zong]], [[https://openalex.org/A5101993719][Yueling Zhang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4970428 
     
No abstract    

    

* Photoirradiation-enhanced behavior via morphological manipulation of CoFe2O4/g-C3N4 heterojunction for supercapacitor and CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403014884
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.09.211")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403014884"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403014884"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403014884"))][Get cited by]]

OpenAlex: https://openalex.org/W4403014884 (Open access: False)
    
[[https://openalex.org/A5100725418][Wei He]], [[https://openalex.org/A5049690603][Yingpei Liu]], [[https://openalex.org/A5048950682][Liang Liu]], [[https://openalex.org/A5102573353][Huimin Han]], [[https://openalex.org/A5100700402][Zhi‐Xiang Wang]], [[https://openalex.org/A5101667147][Yuguang Li]], [[https://openalex.org/A5024108240][Dong Ji]], [[https://openalex.org/A5058192166][L. Shen]], [[https://openalex.org/A5101770125][Yirong Feng]], [[https://openalex.org/A5101844206][Shuangfei Zhao]], [[https://openalex.org/A5100616156][Jiming Yang]], [[https://openalex.org/A5102216318][Zheng Fang]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5100612547][Kai Guo]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.09.211 
     
No abstract    

    

* Enhanced Catalytic Activity of I-Mxenes for Co2 Reduction Reaction by Ordered Metal Atomic Vacancies: A Dft Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403016594
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4973714")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403016594"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403016594"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403016594"))][Get cited by]]

OpenAlex: https://openalex.org/W4403016594 (Open access: False)
    
[[https://openalex.org/A5000445381][Huichun Xue]], [[https://openalex.org/A5068991083][Yitong Chen]], [[https://openalex.org/A5101519452][Lin Zhu]], [[https://openalex.org/A5037785383][An Du]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4973714 
     
No abstract    

    

* Metal-organic framework (MOF) integrated Ti3C2 MXene composites for CO2 reduction and hydrogen production applications: a review on recent advances and future perspectives  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403046125
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Two-Dimensional Materials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/fchem.2024.1448700")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403046125"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403046125"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403046125"))][Get cited by]]

OpenAlex: https://openalex.org/W4403046125 (Open access: True)
    
[[https://openalex.org/A5088895260][Beenish Tahir]], [[https://openalex.org/A5086907045][Abdulrahman Alraeesi]], [[https://openalex.org/A5100689309][Muhammad Tahir]], Frontiers in Chemistry. 12(None)] 2024. https://doi.org/10.3389/fchem.2024.1448700 
     
Titanium carbide (Ti 3 C 2 ) MXenes due to their structural and optical characteristics rapidly emerged as the preferred material, particularly in catalysis and energy applications. On the other hand, because of its enormous surface/volume ratio and porosity, Metal-organic Frameworks (MOFs) show promise in several areas, including catalysis, delivery, and storage. The potential to increase the applicability of these magic compounds might be achieved by taking advantage of the inherent flexibility in design and synthesis, and optical characteristics of MXenes. Thus, coupling MOF with Ti 3 C 2 MXenes to construct hybrid composites is considered promising in a variety of applications, including energy conversion and storage. This paper presents a systematic discussion of current developments in Ti 3 C 2 MXenes/MOF composites for photocatalytic reduction of CO 2 , and production of hydrogen through water splitting. Initially, the overview and characteristics of MXenes and MOFs are independently discussed and then a detailed investigation of efficiency enhancement is examined. Different strategies such as engineering aspects, construction of binary and ternary composites and their efficiency enhancement mechanism are deliberated. Finally, different strategies to explore further in various other applications are suggested. Although Ti 3 C 2 MXenes/MOF composites have not yet been thoroughly investigated, they are potential photocatalysts for the production of solar fuel and ought to be looked into further for a range of applications.    

    

* Unravelling the Serbian Energy Transition Puzzle: Driving an Electric Vehicle Result in Higher CO2 Emissions than Driving a Traditional Internal Combustion Engine Counterparty  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402974272
:TOPICS: Rebound Effect on Energy Efficiency and Consumption, Energy Supply and Security Issues for Developed Economies, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.46793/eee24-1.22f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402974272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402974272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402974272"))][Get cited by]]

OpenAlex: https://openalex.org/W4402974272 (Open access: True)
    
[[https://openalex.org/A5038125617][Sergey F. Fominykh]], [[https://openalex.org/A5107652997][Dusan Stanar]], Energija Ekonomija Ekologija. XXVI(1)] 2024. https://doi.org/10.46793/eee24-1.22f 
     
his article delves into the intriguing paradox emerging in Serbia's transportation landscape, where electric vehicles (EVs) are projected to generate more carbon dioxide (CO2) emissions than internal combustion engine (ICE) until 2030. Driving an EV within Serbia over the upcoming five years is estimated to contribute to roughly 25% more CO2 emissions compared to ICE vehicles. The study unveils the underlying factors behind this paradox, including Serbia's energy mix dominated by lignite. By contrasting this with the European Union's cleaner energy sources, the article underscores the delayed CO2 emissions reduction from EVs in Serbia. Furthermore, it explores the carbon footprint associated with EV production and highlights the challenges posed by the country's energy infrastructure and vehicle fleet. The article concludes with insights into potential solutions, emphasizing the need for Serbia to accelerate its transition to renewables, aiming to align with 2030 targets, while parity with EU emissions levels is projected by 2040.    

    

* Structural and Reservoir Characteristics of Potential Carbon Dioxide Storage Sites in the Northern South Yellow Sea Basin, Offshore Eastern China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403074530
:TOPICS: Anaerobic Methane Oxidation and Gas Hydrates, Characterization of Shale Gas Pore Structure, Seismic Waveform Inversion in Geophysics
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/jmse12101733")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403074530"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403074530"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403074530"))][Get cited by]]

OpenAlex: https://openalex.org/W4403074530 (Open access: True)
    
[[https://openalex.org/A5031223524][Di Luo]], [[https://openalex.org/A5041615964][Yong Yuan]], [[https://openalex.org/A5100689468][Jianwen Chen]], [[https://openalex.org/A5100404157][Qing Li]], [[https://openalex.org/A5046285032][Jie Liang]], [[https://openalex.org/A5079458065][Hualin Zhao]], Journal of Marine Science and Engineering. 12(10)] 2024. https://doi.org/10.3390/jmse12101733 
     
The geological storage of carbon dioxide (CO2) in offshore saline aquifers stands as a primary option for reducing CO2 emissions in coastal regions. China’s coastal regions, particularly Shandong and Jiangsu provinces, face significant challenges in CO2 reduction. Therefore, evaluating the feasibility of CO2 geological storage in the adjacent seas is critical. To assess the suitability of a CO2 storage site, understanding its structural and reservoir characteristics is essential to mitigate injection and storage risks. In this study, we analyzed the structural characteristics and potential traps of the Yantai Depression in the South Yellow Sea Basin based on seismic data interpretation. We further conducted well logging analysis and post-stack seismic inversion to obtain lithological data, including acoustic impedance and sandstone content percentages from the Cenozoic Funing Formation, Dainan–Sanduo Formation, and Yancheng Formation. Our findings highlight that the Yantai Depression in the South Yellow Sea Basin exhibits diverse structural traps and favorable reservoir–caprock combinations, suggesting promising geological conditions for CO2 storage. This area emerges as a suitable candidate for implementing CO2 geological storage initiatives.    

    

* Empowering sustainable hotels: a guest-centric optimization for vehicle-to-building integration  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402943553
:TOPICS: Implications of Shared Autonomous Vehicle Services, Integration of Electric Vehicles in Power Systems, Influence of Built Environment on Active Travel
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1186/s42162-024-00400-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402943553"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402943553"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402943553"))][Get cited by]]

OpenAlex: https://openalex.org/W4402943553 (Open access: True)
    
[[https://openalex.org/A5057616496][Lynne Valett]], [[https://openalex.org/A5087084762][Jessica Bollenbach]], [[https://openalex.org/A5048831245][Robert Keller]], Energy Informatics. 7(1)] 2024. https://doi.org/10.1186/s42162-024-00400-9 
     
Abstract In light of global warming, hotels account for one of the highest energy demands within the building sector, offering great decarbonization potential. As electrification increases, so does the demand for electric vehicles (EVs) charging stations at hotels and the proportion of Vehicle-to-Building-capable EVs. Therefore, the study explores the potential of guest-centric energy management. To accomplish this, we develop an optimization model for an energy management system that focuses on either cost-efficiency or carbon dioxide equivalents (CO2)-efficiency, grounded in a real-world case study. Through scenario analyses considering seasons as well as different guest mobility behaviors, this study discusses the expenses associated with CO2 savings using digital solutions. It emphasizes the currently perceived conflict between cost reduction and decarbonization goals to achieve a sustainable design of information systems. Thereby, this study highlights the critical importance of individual mobility behavior in enabling sustainable energy management for hotels.    

    

* Biogas as alternative fuel for the road transportation sector in Algeria by 2050: a case study Ouargla  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402941771
:TOPICS: Impact of Oil Palm Expansion on Biodiversity, Technical Aspects of Biodiesel Production, Indoor Air Pollution in Developing Countries
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54021/seesv5n2-261")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402941771"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402941771"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402941771"))][Get cited by]]

OpenAlex: https://openalex.org/W4402941771 (Open access: False)
    
[[https://openalex.org/A5033700468][Bakhta Recioui]], [[https://openalex.org/A5107648890][Mondir Soualeh]], [[https://openalex.org/A5060172774][Djilali Messaoudi]], [[https://openalex.org/A5104013629][Noureddine Settou]], [[https://openalex.org/A5019641066][Rébha Ghedamsi]], [[https://openalex.org/A5022044379][Yasmina Mokhbi]], [[https://openalex.org/A5052278335][Soumia Rahmouni]], STUDIES IN ENGINEERING AND EXACT SCIENCES. 5(2)] 2024. https://doi.org/10.54021/seesv5n2-261 
     
This study aims to integrate the biogas road transport sector in the Ouargla region of Algeria by 2050. The alternative biogas is derived from livestock animals (goats, cows, sheep, and camels), municipal waste, and palm waste. Anaerobic digestion is the process used for producing biogas. Our study adopts a prospective method that integrates two modules: energy modeling and the Geographic Information System (GIS) to evaluate the biogas demand potential in the Algeria’s road transportation sector between 2020 and 2050. We proposed two scenarios to estimate the avoided CO2 emissions by 2050: a voluntary biogas vehicle (VB) and a reference conventional fuel vehicle (CFV) to calculate the environmental impacts both before and after the implementation of biogas as a substitute fuel in the transportation sector. As a result, the total amount of biogas demand would be 488.46 thousand tons until 2050. A significant CO2 reduction is achievable in 2050; the amount of CO2 saving is estimated at 285.78 thousand tons, or 43%. The results of this study showed that the use of biogas in road transport as a substitute fuel serves to protect the environment by reducing carbon dioxide emissions while decreasing energy usage.    

    

* Chemistry-climate feedback of atmospheric methane in a methane emission flux driven chemistry-climate model  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403045913
:TOPICS: Global Methane Emissions and Impacts, Anaerobic Methane Oxidation and Gas Hydrates, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-2024-2938")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403045913"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403045913"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403045913"))][Get cited by]]

OpenAlex: https://openalex.org/W4403045913 (Open access: True)
    
[[https://openalex.org/A5013620281][Laura Stecher]], [[https://openalex.org/A5078307835][Franziska Frank]], [[https://openalex.org/A5040485527][Patrick Jöckel]], [[https://openalex.org/A5074450843][Michael Ponater]], [[https://openalex.org/A5020189451][Mariano Mertens]], [[https://openalex.org/A5078008464][M. Dameris]], No host. None(None)] 2024. https://doi.org/10.5194/egusphere-2024-2938 
     
Abstract. The chemical sink of atmospheric methane (CH4) depends on the temperature and on the chemical composition. Here, we assess the feedback of atmospheric CH4 induced by changes of the chemical sink in a warming climate using a CH4 emission flux driven setup of the chemistry-climate model EMAC, in which the chemical feedback of CH4 mixing ratios can evolve explicitly. We perform idealized perturbation simulations driven either by increased carbon dioxide (CO2) mixing ratios, or by increased CH4 emission fluxes. The CH4 emission flux perturbation leads to a large increase of CH4 mixing ratios. Remarkably, the factor by which the CH4 mixing ratio increases is larger than the increase factor of the emission flux, because the atmospheric lifetime of CH4 is extended. In contrast, the individual effect of the global surface air temperature (GSAT) increase is to shorten the CH4 lifetime, which results in a significant reduction of CH4 mixing ratios in our setup. The corresponding radiative feedback is estimated at -0.041 W/m2/K and -0.089 W/m2/K for the CO2 and CH4 perturbation, respectively. The explicit adaption of CH4 mixing ratios leads to secondary feedbacks of the hydroxyl radical (OH) and ozone (O3). Firstly, the OH response includes the CH4-OH feedback, which enhances the CH4 lifetime change, and, secondly, the formation of tropospheric O3 is reduced. Our CH4 perturbation induces the same response of GSAT per effective radiative forcing (ERF) as the CO2 perturbation, which supports the applicability of the ERF framework for CH4.    

    

* Integrating Active Learning and DFT for Fast-Tracking Single-Atom Alloy Catalysts in CO2-to-Fuel Conversion  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403050550
:TOPICS: Accelerating Materials Innovation through Informatics, Electrocatalysis for Energy Conversion, Droplet Microfluidics Technology
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c11695")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403050550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403050550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403050550"))][Get cited by]]

OpenAlex: https://openalex.org/W4403050550 (Open access: False)
    
[[https://openalex.org/A5044055665][Xin Song]], [[https://openalex.org/A5009988050][Pengxin Pu]], [[https://openalex.org/A5038092047][Haisong Feng]], [[https://openalex.org/A5102482212][Hu Ding]], [[https://openalex.org/A5014079387][Yuan Deng]], [[https://openalex.org/A5100297487][Zhen Ge]], [[https://openalex.org/A5044492107][Sylvia Zhao]], [[https://openalex.org/A5007836409][Tianyong Liu]], [[https://openalex.org/A5017313282][Yusen Yang]], [[https://openalex.org/A5084055697][Min Wei]], [[https://openalex.org/A5100333386][Xin Zhang]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c11695 
     
Electrocatalytic carbon dioxide reduction (CO    

    

* Light-Activated Artificial CO2-Reductase: Structure and Activity  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403027660
:TOPICS: Mass Spectrometry Techniques, Electrochemical Reduction of CO2 to Fuels, Chemical Reactions Involving Quantum Tunneling
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c08927")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403027660"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403027660"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403027660"))][Get cited by]]

OpenAlex: https://openalex.org/W4403027660 (Open access: False)
    
[[https://openalex.org/A5092143087][Raphaël J. Labidi]], [[https://openalex.org/A5070853192][Bruno Faivre]], [[https://openalex.org/A5029338783][Philippe Carpentier]], [[https://openalex.org/A5058132875][Julien Pérard]], [[https://openalex.org/A5001485043][Philipp Gotico]], [[https://openalex.org/A5100369239][Yun Li]], [[https://openalex.org/A5076426241][Mohamed Atta]], [[https://openalex.org/A5062221634][Marc Fontecave]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c08927 
     
Light-dependent reduction of carbon dioxide (CO    

    

* Spatial-temporal differences and convergence analysis of residential building carbon emission efficiency in China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402917681
:TOPICS: Economic Impact of Environmental Policies and Resources, Life Cycle Assessment and Environmental Impact Analysis, Efficiency Analysis in Production and Resource Allocation
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1371/journal.pone.0311097")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402917681"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402917681"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402917681"))][Get cited by]]

OpenAlex: https://openalex.org/W4402917681 (Open access: True)
    
[[https://openalex.org/A5023691587][Yong-Kun Wang]], [[https://openalex.org/A5107516074][Na Lu]], [[https://openalex.org/A5100417669][Yan Wang]], PLoS ONE. 19(9)] 2024. https://doi.org/10.1371/journal.pone.0311097 
     
Data indicate that carbon dioxide emissions from residential buildings in China constitute 60% of the country’s total, making carbon reduction efforts in residential construction crucial for achieving dual carbon goals. From the perspective of eight major economic regions, this paper selects energy consumption, per capita residential area, and residential population as input indicators, per capita disposable income as the output indicator, and carbon dioxide emissions as the undesired output indicator. It employs the super-efficiency model based on the directional distance (super-DDF) function and the Malmquist-Luenberger (ML) index to measure the static and dynamic carbon emission efficiencies of residential buildings (RBCEE) during their operational phase from 2010 to 2020. After analyzing the differences and equity in RBCEE among regions using the Theil index and Gini coefficient, the σ-convergence, absolute β-convergence, and conditional β-convergence methods are utilized to explore the changing trends of RBCEE across the eight major economic regions. Results show that the static RBCEE in China is at a medium level; dynamic efficiency has improved across all eight regions, though at varying rates; overall, RBCEE exhibits poor equity and significant differences, with intra-group differences being a major cause. In terms of convergence, all eight economic regions display significant absolute β-convergence and conditional β-convergence. Finally, based on the research findings, this paper proposes corresponding emission reduction recommendations for the eight major economic regions.    

    

* Life Cycle Analysis of a Renovation Project for Old Housing in Tashkent to Reduce Greenhouse Gas Emissions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403048210
:TOPICS: Water Resource Management and Agricultural Technology, Evolution of Water Technologies in Ancient Civilizations
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/e3sconf/202457405007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403048210"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403048210"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403048210"))][Get cited by]]

OpenAlex: https://openalex.org/W4403048210 (Open access: True)
    
[[https://openalex.org/A5107692252][Elyor Makhmudov]], [[https://openalex.org/A5073803986][Anna Zavaleeva]], [[https://openalex.org/A5067130825][Ilya Zavaleev]], [[https://openalex.org/A5093273476][Akmal Berdimurodov]], E3S Web of Conferences. 574(None)] 2024. https://doi.org/10.1051/e3sconf/202457405007 
     
The shift towards economic decarbonization through the reduction of carbon dioxide emissions has led to a focus on renovating and modernizing the existing buildings rather than constructing new ones. This research emphasizes the critical differences between the construction of new buildings and the modernization of the existing structures, specifically in the context of Uzbekistan. The country lacks a comprehensive methodology for accounting for the embodied carbon of building materials used in modernization projects. This research aims to bridge this gap by conducting a life cycle analysis (LCA) of a project focused on enhancing the thermal performance of the enclosing structures of a three to five-story multifamily residential building, commonly referred to as “Khrushchevka”. The analysis found that retrofitting buildings reduced greenhouse gas emissions by 13.5% through improved energy efficiency, despite the increase in initial emissions associated with the production and installation of insulation materials. The total reduction in carbon emissions over the entire life cycle of the reconstructed building was 24% (or 43.2 tons of CO₂), including emissions associated with the production of insulation. The payback period for emissions, which offsets the initial emissions during reconstruction, is 17 years.    

    

* A novel optimization approach for the design of a hybrid energy system based on a modified version of a subtraction-average-based optimizing method  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402918654
:TOPICS: Hydrogen Energy Systems and Technologies, Integration of Renewable Energy Systems in Power Grids, Demand Response in Smart Grids
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/ijlct/ctae117")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402918654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402918654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402918654"))][Get cited by]]

OpenAlex: https://openalex.org/W4402918654 (Open access: True)
    
[[https://openalex.org/A5101023299][Wu Nan]], [[https://openalex.org/A5101612762][Ning Sun]], [[https://openalex.org/A5103108189][Saeid Razmjooy]], International Journal of Low-Carbon Technologies. 19(None)] 2024. https://doi.org/10.1093/ijlct/ctae117 
     
Abstract A critical challenge lies in developing an energy-efficient and eco-friendly power supply system. Despite the enhanced energy efficiency offered by combined cooling, heating, and power (CCHP) systems, optimizing them poses challenges due to conflicting goals like reducing fuel consumption and carbon dioxide emissions while maximizing cost savings. To address these issues, this research suggests a solution that merges a modified subtraction-average-based optimizer with a multiobjective optimization strategy. This proposed framework attains a superior equilibrium among competing objectives compared to three existing optimization algorithms. It leads to a 12% decrease in fuel consumption, a 15% drop in carbon dioxide emissions, and a 10% cost reduction for shopping center proprietors. Moreover, the optimized CCHP system outperforms a stand-alone production system and a nonoptimized CCHP system, yielding 20% and 15% fuel savings annually, respectively. By offering a more comprehensive and balanced approach to CCHP system optimization, the proposed framework contributes to the progression of energy system optimizer, fostering the creation of more sustainable and environmentally friendly energy systems of shopping centers.    

    

* Statistical Measurement and Economic Effect Research on Green New Energy Industry in Yangtze River Delta  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402937173
:TOPICS: Environmental Impact on Lake Baikal Ecosystem, Rural Revitalization Strategy in China
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.62051/ijgem.v4n2.22")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402937173"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402937173"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402937173"))][Get cited by]]

OpenAlex: https://openalex.org/W4402937173 (Open access: False)
    
[[https://openalex.org/A5036523776][Qingliang Tang]], [[https://openalex.org/A5100371335][Sheng Wang]], International Journal of Global Economics and Management. 4(2)] 2024. https://doi.org/10.62051/ijgem.v4n2.22 
     
With the rapid development of economy, human activities have caused great impact on the ecological environment. Achieving peak carbon dioxide emissions, carbon neutrality has become the goal to be completed. Taking the new energy industry in the Yangtze River Delta region as the research subject, this paper explores the relationship between the development of new energy and social economy, scientifically accounts for and evaluates the emission reduction potential of the new energy industry, conducts coupling and coordinated development research on the new energy industry and the regional low-carbon economic integration development, and provides scientific suggestions for the realization of "peak carbon dioxide emissions, carbon neutrality". Focusing on the above purpose, this paper firstly synthesizes the literature, clarifies the relevant concepts of low-carbon economy and the evaluation indicators of the development level of new energy industry, and combs the interaction between the two, providing theoretical support for the subsequent analysis. Secondly, it constructs a multi-dimensional measurement index to explore the green new energy industry, selects the relevant data of three provinces and one city in the Yangtze River Delta region from 2011 to 2019, and uses the TOPSIS entropy method to quantify various indicators of the new energy industry. Then, the unit root test is carried out on the data of different indicators of the new energy industry to judge whether these variable data have stationarity, and then the strength and direction of the relationship between the variables of different indicators are judged through the co-integration test. At last, the PSTR model is applied to take economic growth as the conversion variable, to examine the nonlinear effect of explanatory variables such as economic growth on the development of new energy, to conduct empirical analysis and draw conclusions.    

    

* Regulating the Magnetic Domain of Nickle for Enhanced CO2 Electrochemical Reduction Driven by External Magnetic Field  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402929856
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202403624")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402929856"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402929856"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402929856"))][Get cited by]]

OpenAlex: https://openalex.org/W4402929856 (Open access: False)
    
[[https://openalex.org/A5033498857][Zhaozhao Zhu]], [[https://openalex.org/A5024831364][Wu Tang]], [[https://openalex.org/A5100395804][Junjie Wang]], [[https://openalex.org/A5101064739][Yingxi Lin]], [[https://openalex.org/A5036131297][Zhao Li]], [[https://openalex.org/A5013407292][Haiyuan Chen]], [[https://openalex.org/A5100366524][Zihao Song]], [[https://openalex.org/A5074894656][Jun Song Chen]], [[https://openalex.org/A5087031805][Rui Wu]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202403624 
     
Abstract Electrochemical reduction of carbon dioxide (CO 2 RR) into valuable fuels and chemicals is a highly desirable approach for achieving carbon neutrality, but it faces substantial technical hurdles. Herein, a novel ferromagnetic Ni@NC electrocatalyst is reported, composed of nickel nanoparticles embedded within a nitrogen‐doped carbon matrix. The optimal Ni@NC catalyst displays a fourfold increase in current density at 140 versus 0 mT in H‐type cell and achieves nearly 100% CO Faradaic efficiency (FE CO ) across a wide potential range with minimal overpotential in flow cell. Quantum diamond atomic force microscopy (QDAFM) directly demonstrates the orderly magnetic moments of the Ni@NC catalyst under the external magnetic field. Further theoretical calculations reveal that the orderly magnetic moments induced by the external magnetic field facilitate the formation of Ni–O–Ni and reduce the energy barriers of COOH * intermediates. This study underscores the potential of applying magnetic field modulation to not only enhance the catalytic efficiencies but also extend this strategy to other catalytic systems.    

    

* Slip flow of SWCNT–H2O, TiO2–H2O, MWCNT–H2O, and GO–H2O nanofluids between two spinning circular disks  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935795
:TOPICS: Heat Transfer Enhancement in Nanofluids, Heat Transfer in Porous Media and Packed Beds, Lattice Boltzmann Method for Complex Flows
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/zamm.202301015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935795"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935795 (Open access: False)
    
[[https://openalex.org/A5084330974][Tanvi Singla]], [[https://openalex.org/A5072563406][Mark Haid]], [[https://openalex.org/A5090382285][B. Kumar]], ZAMM ‐ Journal of Applied Mathematics and Mechanics / Zeitschrift für Angewandte Mathematik und Mechanik. None(None)] 2024. https://doi.org/10.1002/zamm.202301015 
     
Abstract The heat transfer and flow properties of nanofluids are studied using two co‐axial, stretched, and rotating disks containing the porous media and slip boundary conditions. The water‐based nanofluid is formed by using SWCNT (single‐walled carbon nanotubes), (titanium dioxide), MWCNT (multiwalled carbon nanotubes), GO (graphene oxide) as nanoparticles. The nonlinear PDEs are converted into ODEs using the Von Karman similarity transformation. The finite difference method is used to solve the transformed equations. The velocity profiles in the axial, radial, and tangential directions and the temperature profiles are analyzed through graphs, accompanied by interpretations based on physical principles. The energy equation is modeled using the Cattaneo–Christov heat flux model. When the velocity slip parameter rises, axial velocity decreases near the lower disk but increases near the end of the upper disk, while there is a reduction in radial velocity near the end of both disks. The skin friction coefficient and Nusselt number are computed in the present study for governing parameters.    

    

* Impacts of climate change on phenology, yield, and water productivity of wheat in a semi-arid region of India using the CERES-Wheat model  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403026224
:TOPICS: Adaptation to Climate Change in Agriculture
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2166/wcc.2024.139")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403026224"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403026224"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403026224"))][Get cited by]]

OpenAlex: https://openalex.org/W4403026224 (Open access: True)
    
[[https://openalex.org/A5059330709][Himani Bisht]], [[https://openalex.org/A5060042376][S.S. Punia]], [[https://openalex.org/A5104157929][Bipin Kumar]], [[https://openalex.org/A5016049562][Jitendra Rajput]], [[https://openalex.org/A5088051819][D. K. Singh]], [[https://openalex.org/A5043152175][Lata Vishnoi]], [[https://openalex.org/A5101926604][Rajvir Singh]], [[https://openalex.org/A5002946730][Manisha Tamta]], [[https://openalex.org/A5085314552][Shweta Gautam]], Journal of Water and Climate Change. None(None)] 2024. https://doi.org/10.2166/wcc.2024.139 
     
ABSTRACT In the present study, the Crop Environment Resource Synthesis (CERES)-Wheat model was used to study the impacts of climate change on phenology, yield, and water productivity of wheat. The model was run with the baseline period (1980–2010) and three future periods, namely, the 2030s, 2050s, and 2070s under two representative concentration pathway (RCP) scenarios, namely, RCP 4.5 and RCP 8.5. The results indicated a substantial decline in phenology, grain yield, biomass, and crop water productivity (CWP) under both scenarios. The grain yield of wheat showed a decline by 12.3, 20.5, and 19.8% during the 2030s, 2050s, and 2070s, respectively, under RCP 4.5 at baseline CO2 concentration, while at elevated concentration of CO2, the reduction was 10.2, 15.7, and 14.9%, respectively. Under RCP 8.5, the yield reduction was 18.8, 26.5, and 27.3% during the 2030s, 2050s, and 2070s, respectively, with baseline concentration of CO2, while with increased CO2 the yield reduction was 7, 12.6, and 8.9%, respectively. CWP decreased at baseline CO2 by 9, 17.6, and 18.3% for RCP 4.5 and 10.6, 20.6, and 22.6% for RCP 8.5 during the 2030s, 2050s, and 2070s, respectively. However, beneficial impact of CO2 fertilization on CWP was noticed in both RCP scenarios, resulting in relatively less reduction under future CO2 concentration.    

    

* The role of procurement activities in reducing the hydrocarbon footprint in the Arctic zone of the Russian Federation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402993335
:TOPICS: Arctic Shipping and Governance, Future Development of China's Coal Industry, Socio-Economic Development and Global Economic Challenges
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.24147/1812-3988.2024.22(1).50-60")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402993335"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402993335"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402993335"))][Get cited by]]

OpenAlex: https://openalex.org/W4402993335 (Open access: False)
    
[[https://openalex.org/A5046064748][Alexandra A. Saitova]], [[https://openalex.org/A5107666108][Enver R. Dzhemilev]], [[https://openalex.org/A5107666109][Tatyana P. Bozhikova]], Herald of Omsk University Series Economics. 22(1)] 2024. https://doi.org/10.24147/1812-3988.2024.22(1).50-60 
     
One of the main tasks of the modern energy industry is not only to maximize the efficient use of natural energy resources and preserve their diversity, but also to increase the potential of this sector in the stable growth of the state's economy, improving the quality of life of the population and maintaining a favorable environmental situation in the country. Decarbonization, which implies a reduction in carbon dioxide (CO<sub>2</sub>) and methane emissions, is a key challenge facing the global energy industry. The purpose of this study is to assess greenhouse gas emissions produced as a result of the activities of the largest energy companies operating in the Arctic zone of the Russian Federation, namely PJSC LUKOIL and PJSC NOVATEK through the analysis of their policies and measures to reduce the carbon footprint, preserve biological diversity and develop the northern region of Russia, identify links between the conduct of procurement activities and support for the sustainable development of the enterprise, including in the environmental field. In the course of the work, a comparative analysis of the activities of companies in the Arctic zone was carried out, their current and prospective projects were described, data on greenhouse gas emissions of the enterprises in question were structured by year, their procurement policy, the necessary requirements for potential suppliers, implemented educational programs and activities for the development of professional skills of personnel were considered, and additional tools were proposed that they will be able to contribute not only to improving the sustainable development of companies in the Arctic, but also, as a result, conservation of natural diversity in the northern part of the Russian Federation.    

    

* The Biochemistry of Artificial CO2-Fixation Pathways: The Exploitation of Carboxylase Enzymes Alternative to Rubisco  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403006956
:TOPICS: Metabolic Engineering and Synthetic Biology, Role of Lipoic Acid in Metabolism and Health, Enzyme Immobilization Techniques
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14100679")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403006956"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403006956"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403006956"))][Get cited by]]

OpenAlex: https://openalex.org/W4403006956 (Open access: True)
    
[[https://openalex.org/A5017636644][Immacolata Tommasi]], Catalysts. 14(10)] 2024. https://doi.org/10.3390/catal14100679 
     
The last decade has registered a rapid development of new artificial CO2-bioconversion processes mirroring natural CO2-fixation by carboxylation and/or reduction reactions. The development of artificial pathways has shown that we have sufficient tools to design and implement, both in vitro and in vivo, complex reaction sequences pointing to construct microbial cell-factories to produce target chemicals at scale. This review is aimed to focus on the most efficient artificial CO2-fixing autotrophic cycles based on the use of carboxylase enzymes that, similarly to Rubisco enzyme, build a C–CO2 bond by reacting an enediolate or an enolate anion with CO2. The development of artificial CO2-fixing autotrophic cycles encompasses the analysis of the complete library of natural carboxylase enzymes taking part in the so called “central” and “assimilation” metabolism to select only those enzymes characterized by high catalytic efficiency, great stability, high substrate affinity, and oxygen tolerability. The review analyzes the biochemistry of the most efficient artificial CO2-fixation pathways implemented up today, evidencing the biosynthetic strategies adopted, the development of replenishing routes, and their integration with cell metabolism.    

    

* A New Approach for Improving Flame Retardancy of Automotive Interior Upholstery  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403074905
:TOPICS: Flame Retardant Polymer Materials, Fire Safety in Tunnel Fires, Inverse Radiative Heat Transfer Analysis
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21605/cukurovaumfd.1559895")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403074905"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403074905"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403074905"))][Get cited by]]

OpenAlex: https://openalex.org/W4403074905 (Open access: False)
    
[[https://openalex.org/A5003241982][Özlem Erdem Yılmaz]], [[https://openalex.org/A5068006582][Ali Can Yılmaz]], [[https://openalex.org/A5023710707][Ahmet Çoşgun]], Çukurova Üniversitesi Mühendislik Fakültesi Dergisi. None(None)] 2024. https://doi.org/10.21605/cukurovaumfd.1559895 
     
This study presents the flame retardant (FR) performance of chemically treated automotive upholstery fabrics using two different impregnation methods of Resin Transfer Molding (RTM) and supercritical carbon dioxide (scCO2). Referring to the related standards, untreated seat fabric obtained from seat upholstery of a bus (neat fabric, NF) and treated fabric samples underwent burning rate (BR) and limiting oxygen index (LOI) tests to compare effect of treatment and impregnation methods on FR performance. Thermal analysis was also conducted on the samples considering onset degradation temperatures and char yields. The results showed that BR and LOI of all samples were in acceptable range and treatment provided enhancement in FR performance of NF. The treated sample using scCO2 method gave the highest LOI value of 32% and the lowest BR of 21 mm/min subtending to 18.5% increase in LOI and 30% reduction in BR compared to those of NF. The performance of treatment in RTM was worse than that of scCO2 and better than that of NF. The results confirm that both treatment and methods used in this study give promising results for safety against fire in transportation vehicles.    

    

* Adsorption and Catalytic Reduction of Nitrogen Oxides (NO, N2O) on Disulfide Cluster Complexes of Cobalt and Iron—A Density Functional Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402990736
:TOPICS: Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ma17194764")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402990736"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402990736"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402990736"))][Get cited by]]

OpenAlex: https://openalex.org/W4402990736 (Open access: True)
    
[[https://openalex.org/A5090426636][Ellie L. Uzunova]], [[https://openalex.org/A5088933747][Ivelina Georgieva]], Materials. 17(19)] 2024. https://doi.org/10.3390/ma17194764 
     
The reactivity of nitrogen oxide, NO, as a ligand in complexes with [Fe2-S2] and [Co2-S2] non-planar rhombic cores is examined by density functional theory (DFT). The cobalt-containing nitrosyl complexes are less stable than the iron complexes because the Co-S bonds in the [Co2-S2] core are weakened upon NO coordination. Various positions of NO were examined, including its binding to sulfur centers. The release of NO molecules can be monitored photochemically. The ability of NO to form a (NO)2 dimer provides a favorable route of electrochemical reduction, as protonation significantly stabilizes the dimeric species over the monomers. The quasilinear dimer ONNO, with trans-orientation of oxygen atoms, gains higher stability under protonation and reduction via proton–electron transfer. The first two reduction steps lead to an N2O intermediate, whose reduction is more energy demanding: in the two latter reaction steps the highest energy barrier for Co2S2(CO)6 is 109 kJ mol−1, and for Fe2S2(CO)6, it is 133 kJ mol−1. Again, the presence of favorable light absorption bands allows for a photochemical route to overcome these energy barriers. All elementary steps are exothermic, and the final products are molecular nitrogen and water.    

    

* Photocatalytic CO2 Reduction to CO Catalysed by Lanthanide Complexes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403005889
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cc03175j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403005889"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403005889"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403005889"))][Get cited by]]

OpenAlex: https://openalex.org/W4403005889 (Open access: False)
    
[[https://openalex.org/A5013241583][Yingzhe Zhao]], [[https://openalex.org/A5088758006][Jianling Zhang]], [[https://openalex.org/A5101687637][Haoxiang Wang]], [[https://openalex.org/A5087866064][Renjie Zhang]], [[https://openalex.org/A5102689999][Yunan Teng]], [[https://openalex.org/A5100714696][Meiling Li]], [[https://openalex.org/A5055988117][Yi Song]], [[https://openalex.org/A5016948713][Zhonghao Tan]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d4cc03175j 
     
Here we demonstrate the efficient CO2 reduction to CO catalysed by lanthanide-based complexes under light irradiation, by which the highest CO evolution rate can reach 78±8 μmol g-1 h-1 in...    

    

* Vaporizing temperate peatlands  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402907098
:TOPICS: Carbon Dynamics in Peatland Ecosystems
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5463/thesis.811")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402907098"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402907098"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402907098"))][Get cited by]]

OpenAlex: https://openalex.org/W4402907098 (Open access: False)
    
[[https://openalex.org/A5055608561][Jim Boonman]], No host. None(None)] 2024. https://doi.org/10.5463/thesis.811 
     
Peat decomposition causes soil subsidence and is responsible for greenhouse gas emissions. Peat forms under wet conditions, but in the Netherlands peatlands have been drained (by humans) for about a thousand years. The drained peat pastures are mainly being used for dairy production. In the drained peat soils with lower groundwater levels, oxygen enables high rates of peat decomposition. This peat decomposition has caused most peatlands to sink below sea level, and currently, these peatlands are still subsiding (on average 6 mm per year). Peat decomposition is also a major source of greenhouse gas emissions: in the Netherlands, about 4% of greenhouse gas emissions emerge from vaporizing peatlands. Rewetting peat could reduce decomposition rates and associated greenhouse gas emissions. This dissertation focuses on the effects of rewetting peatlands using water infiltration systems. Here, peatland hydrology, CO2 emissions and microbial soil processes are play a central role. Is a resilient future for peatlands within close reach? Under normal conditions, the hydraulic conductivity of peat is too low to maintain steady groundwater levels by ditch water infiltration during drier periods. The aforementioned water infiltration systems consist of underground drainage pipes that transport ditch water to the centre of a peat pasture. In this dissertation it is demonstrated that under certain conditions and to a certain extent, these water infiltration systems (1) successfully raise groundwater levels, (2) substantially reduce CO2 emissions from peat, and (3) influence microbial decomposition processes in the soil. Also, the thesis presents (1) the foundation for a new, national model to estimate peat degradation under aerobic conditions, (2) an accessible method to measure microbial decomposition processes in the soil, (3) a high-frequency dataset of CO2 fluxes from peat pastures determined using automatic flux chambers, and (4) new relationships to estimate annual CO2 fluxes based on average groundwater levels. The chapters in this thesis may contribute to improving the monitoring of greenhouse gases from peat. Throughout the dissertation, the automatic chambers play a major role in measuring emissions from peat. The thesis also discusses how alternative methods could be used to improve the understanding of peat degradation processes and the associated emissions. For example, the second chapter lays the foundation for a national model (SOMERS) to estimate greenhouse gas emissions from peat (and emission reductions), the third chapter lays the foundation for a direct measurement method for degradation processes and emissions at different soil depths, and the fifth chapter shows how groundwater levels can be used as an indicator for emissions. Furthermore, the insights presented on emission reduction may help in practical decision-making by provinces and water boards. The Dutch government has decided in the Climate Agreement that CO2 emissions from peatlands must be reduced by one megaton (25%) by 2030. The results in the thesis illustrate to what extent the implementation of water infiltration systems can contribute to this reduction. Besides water infiltration systems, other solutions are also available that lead to emission reductions (e.g., wet crops and nature restoration), each having their pros and cons. For policymaking, not only the reduction of peat degradation, soil subsidence and CO2 emissions play a role, but also economic feasibility, farmers' interests, biodiversity, soil contamination, water quality, water availability, nitrogen emissions and landscape culture should be taken into account. Towards harmony in (agri)culture and peat preservation! This PhD thesis is part of the Netherlands Research Program on Greenhouse Gas Dynamics in Peatlands and Organic Soils (NOBV). Within this program, high-tech peatland measurement locations have been set up to quantify peatland greenhouse gas emissions, and effects of different (land management and/or hydrological) treatments on these emissions.    

    

* Regional impacts of solar radiation modification on surface temperature and precipitation in Mainland Southeast Asia and the adjacent oceans  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402982875
:TOPICS: Solar Physics and Space Weather, Stratospheric Chemistry and Climate Change Impacts, Geoengineering and Climate Ethics
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41598-024-73149-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402982875"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402982875"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402982875"))][Get cited by]]

OpenAlex: https://openalex.org/W4402982875 (Open access: True)
    
[[https://openalex.org/A5001927660][Pornampai Narenpitak]], [[https://openalex.org/A5045183820][Siriwat Kongkulsiri]], [[https://openalex.org/A5004990734][Saifhon Tomkratoke]], [[https://openalex.org/A5067929195][Sirod Sirisup]], Scientific Reports. 14(1)] 2024. https://doi.org/10.1038/s41598-024-73149-6 
     
Solar radiation modification (SRM) has been proposed to temporarily reduce anthropogenic warming. This study presents an assessment of the regional impacts of SRM via solar dimming and stratospheric aerosol injection (SAI) on temperature and precipitation over 0°-30° N and 90° E-110° E, covering Mainland Southeast Asia and adjacent oceans. Using data from the Geoengineering Model Intercomparison Project Phase 6 (GeoMIP6), we examine regional impacts of SRM using three SRM experiments: (1) G6Sulfur, which reduces radiative forcing from the high-emission SSP5-8.5 scenario to the moderate-emission SSP2-4.5 scenario by injecting sulfate aerosols; (2) G6Solar, which similarly reduces radiative forcing from the high-emission to moderate-emission scenarios but by uniformly reducing the solar constant; and (3) G1ext, which reduces radiative forcing from a quadrupled carbon dioxide concentration to pre-industrial levels by uniform solar constant reduction. Our findings show that higher greenhouse gas emissions increase overall precipitation, along with tendencies to have extreme rainfall events and more dry episodes in between. While SRM can partially cool down the surface temperature warming caused by increased greenhouse gas emissions, its effects on precipitation are complex: Solar dimming in G6Solar and G1ext tends to reduce overall precipitation, and tropical sulfate injection in G6Sulfur could lead to further drying in the tropics because of the stratospheric warming associated with the injected aerosols. Different SRM strategies might result in different responses on precipitation.    

    

* Modeling Exhaust Emissions in Older Vehicles in the Era of New Technologies  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403027898
:TOPICS: Estimating Vehicle Fuel Consumption and Emissions, Low-Cost Air Quality Monitoring Systems, Health Effects of Air Pollution
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17194924")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403027898"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403027898"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403027898"))][Get cited by]]

OpenAlex: https://openalex.org/W4403027898 (Open access: True)
    
[[https://openalex.org/A5059564093][Maksymilian Mądziel]], Energies. 17(19)] 2024. https://doi.org/10.3390/en17194924 
     
In response to increasing environmental demands, modeling emissions from older vehicles presents a significant challenge. This paper introduces an innovative methodology that takes advantage of advanced AI and machine learning techniques to develop precise emission models for older vehicles. This study analyzed data from road tests and the OBDII diagnostic interface, focusing on CO2, CO, THC, and NOx emissions under both cold and warm engine conditions. The key results showed that random forest regression provided the best predictions for THC in a cold engine (R2: 0.76), while polynomial regression excelled for CO2 (R2: 0.93). For warm engines, polynomial regression performed best for CO2 (R2: 0.95), and gradient boosting delivered results for THC (R2: 0.66). Although prediction accuracy varied by emission compound and engine state, the models consistently demonstrated high precision, offering a robust tool for managing emissions from aging vehicle fleets. These models offer valuable information for transportation policy and pollution reduction strategies, particularly in urban areas.    

    

* A-124 Sustainable Transport: Assessing Environmental Impact in Medical Sample Transit via Drones and Vehicles  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403071790
:TOPICS: Impact of Climate Change on Human Health
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/clinchem/hvae106.123")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403071790"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403071790"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403071790"))][Get cited by]]

OpenAlex: https://openalex.org/W4403071790 (Open access: False)
    
[[https://openalex.org/A5096910016][Noel Rouven Stierlin]], [[https://openalex.org/A5096941573][A Hemmerle]], [[https://openalex.org/A5084754410][Martin Risch]], [[https://openalex.org/A5049354618][Lorenz Risch]], Clinical Chemistry. 70(Supplement_1)] 2024. https://doi.org/10.1093/clinchem/hvae106.123 
     
Abstract Background This research explores the ecological implications associated with different methods of transporting medical samples, specifically focusing on drones, combustion cars, and electric cars within two laboratories in central European countries. With the primary goal of assessing and comparing CO2 consumption, delivery time, and overall environmental impact, the study aims to provide a basis for adopting sustainable practices in healthcare logistics. Methods The transportation of medical samples occurred between two laboratories in the Principality of Liechtenstein and Switzerland, utilizing authorized aerial and road routes. Various weather conditions and distances were considered for sample transports using different vehicles (8 combustion cars, two electric cars, and one drone model). Energy consumption was documented, and the CO2 footprint was calculated based on data from the Swiss Federal Office for the Environment (FOEN) for both imported and renewable electricity. Comparative analyses were conducted to quantify the environmental impact of each transportation method. Results In terms of CO2 footprint, combustion cars exhibited a CO2 release of 159.5 g/km, while electric cars showed 3.43g (2.15 to 4.08% of combustion cars). Drones demonstrated a minimal 0.09g CO2 emission per kilometer (0.066% of combustion car CO2 emission; 2.6% of electric car CO2 emission). The distance traveled by drones was significantly shorter (16.7% to 50%). Additionally, the efficiency of drone transport was emphasized by its ability to avoid traffic jams and associated detours, resulting in time savings ranging from 31.25 to 50% per delivery when comparing transport times during rush hour and regular hours in the selected setting. Conclusions The integration of drone technology emerges as a crucial strategy for establishing a “green laboratory.” The substantial reduction in CO2 emissions and enhanced delivery efficiency position drone transport as a sustainable and operationally effective solution for medical sample logistics, offering shorter delivery times. These findings highlight the potential for transformative change in healthcare logistics, aligning with the global shift towards sustainability and green practices.    

    

* Assessing Drought Impacts on Gross Primary Productivity of Rubber Plantations Using Flux Observations and Remote Sensing in China and Thailand  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402995540
:TOPICS: Rice Water Management and Productivity Enhancement, Drivers and Impacts of Tropical Deforestation, Impact of Oil Palm Expansion on Biodiversity
:PUBLICATION_DATE: 2024-09-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/f15101732")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402995540"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402995540"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402995540"))][Get cited by]]

OpenAlex: https://openalex.org/W4402995540 (Open access: True)
    
[[https://openalex.org/A5100393226][Weiguang Li]], [[https://openalex.org/A5001964018][Meiting Hou]], [[https://openalex.org/A5100358850][Shaojun Liu]], [[https://openalex.org/A5101730910][Jinghong Zhang]], [[https://openalex.org/A5034318393][Haiping Zou]], [[https://openalex.org/A5047124828][Xiaomin Chen]], [[https://openalex.org/A5006577214][Rui Bai]], [[https://openalex.org/A5068301972][Run Lv]], [[https://openalex.org/A5104010914][Wei Hou]], Forests. 15(10)] 2024. https://doi.org/10.3390/f15101732 
     
Rubber (Hevea brasiliensis Muell.) plantations are vital agricultural ecosystems in tropical regions. These plantations provide key industrial raw materials and sequester large amounts of carbon dioxide, playing a vital role in the global carbon cycle. Climate change has intensified droughts in Southeast Asia, negatively affecting rubber plantation growth. Limited in situ observations and short monitoring periods hinder accurate assessment of drought impacts on the gross primary productivity (GPP) of rubber plantations. This study used GPP data from flux observations at four rubber plantation sites in China and Thailand, along with solar-induced chlorophyll fluorescence (SIF), enhanced vegetation index (EVI), normalized difference vegetation index (NDVI), near-infrared reflectance of vegetation (NIRv), and photosynthetically active radiation (PAR) indices, to develop a robust GPP estimation model. The model reconstructed eight-day interval GPP data from 2001 to 2020 for the four sites. Finally, the study analyzed the seasonal drought impacts on GPP in these four regions. The results indicate that the GPP prediction model developed using SIF, EVI, NDVI, NIRv, and PAR has high accuracy and robustness. The model’s predictions have a relative root mean square error (rRMSE) of 0.22 compared to flux-observed GPP, with smaller errors in annual GPP predictions than the MOD17A3HGF model, thereby better reflecting the interannual variability in the GPP of rubber plantations. Drought significantly affects rubber plantation GPP, with impacts varying by region and season. In China and northern Thailand (NR site), short-term (3 months) and long-term (12 months) droughts during cool and warm dry seasons cause GPP declines of 4% to 29%. Other influencing factors may alleviate or offset GPP reductions caused by drought. During the rainy season across all four regions and the cool dry season with adequate rainfall in southern Thailand (SR site), mild droughts have negligible effects on GPP and may even slightly increase GPP values due to enhanced PAR. Overall, the study shows that drought significantly impacts rubber the GPP of rubber plantations, with effects varying by region and season. When assessing drought’s impact on rubber plantation GPP or carbon sequestration, it is essential to consider differences in drought thresholds within the climatic context.    

    

* Exploring the Effect of Ionic Liquid Conformation on the Selective CO2 Capture of Supported Ionic Liquid-Phase Adsorbents Based on ZIFs  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402983609
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ma17194829")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402983609"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402983609"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402983609"))][Get cited by]]

OpenAlex: https://openalex.org/W4402983609 (Open access: True)
    
[[https://openalex.org/A5064208391][Charitomeni M. Veziri]], [[https://openalex.org/A5001412190][George V. Theodorakopoulos]], [[https://openalex.org/A5059860743][K. Beltsios]], [[https://openalex.org/A5076240526][George E. Romanos]], Materials. 17(19)] 2024. https://doi.org/10.3390/ma17194829 
     
The CO2 adsorption capacity and the CO2/N2 selectivity of a series of Supported Ionic Liquid-Phase adsorbents (SILPs), including the novel inversely structured SILP “Inverse SILPs”, are thoroughly investigated. ZIF-8, ZIF-69 and ZIF-70 were involved as the solid matrix, while ILs, having tricyanomethanide (TCM) as an anion and alkyl-methylimidazolium of different alkyl chain lengths (C2, C6, C8) as a cation, were used as the liquid constituents of the SILPs. The ultimate target of the work was to ratify a few recently reported cases of enhanced CO2 absorptivity in ILs due to their incorporation in ZIFs and to corroborate phenomena of CO2/N2 selectivity improvements in ZIFs, due to the presence of ILs. This ambiguity originates from the vague assumption that the pores of the ZIF are filled with the IL phase, and the free pore volume of a SILP is almost zero. Yet, through the integration of theoretical predictions with N2 porosimetry analysis of an actual sample, it is suggested that a thin layer of IL covered the exterior surface of a ZIF crystal. This layer could act as an impermeable barrier for N2, inhibiting the gas molecules from reaching the empty cavities laying underneath the liquid film during porosimetry analysis. This consideration is based on the fact that the solubility of N2 in the IL is very low, and the diffusivity at 77 K is negligible. In this context, the observed result reflects an averaged adsorptivity of both the IL phase and the empty pores of the ZIF. Therefore, it is incorrect to attribute the adsorption capacity of the SILP solely to the mass of the IL that ‘hypothetically’ nests inside the pore cavities. In fact, the CO2 adsorption capacity of SILPs is always less than the average adsorptivity of an ideal ZIF/IL mixture, where the two phases do not interact. This reduction occurs because some ZIF pores may become inaccessible, particularly when the IL forms a layer on the pore walls, leaving only a small empty core accessible to CO2 molecules. Additionally, the IL layer masks the active sites on the ZIF’s pore walls. It should also be noted that the CO2/N2 selectivity increases only when the ZIF’s pores are completely filled with the IL phase. This is because ILs have a higher CO2/N2 selectivity compared to the bare ZIF.    

    

* Two‐Dimensional Silver–Isocyanide Frameworks  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403024022
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Self-Assembly and Biomaterial Design, Polyoxometalate Clusters and Materials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202417658")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403024022"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403024022"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403024022"))][Get cited by]]

OpenAlex: https://openalex.org/W4403024022 (Open access: False)
    
[[https://openalex.org/A5077459472][Kaiyue Jiang]], [[https://openalex.org/A5060201476][Pu Yan]], [[https://openalex.org/A5101997579][Pengfei Shi]], [[https://openalex.org/A5075460158][Jichao Zhang]], [[https://openalex.org/A5050942599][Xinyu Chai]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5057665432][Chenhui Zhu]], [[https://openalex.org/A5100535765][Chongqing Yang]], [[https://openalex.org/A5029903067][Chenbao Lu]], [[https://openalex.org/A5100330523][Yi Liu]], [[https://openalex.org/A5069271154][Kecheng Cao]], [[https://openalex.org/A5006485558][Xiaodong Zhuang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202417658 
     
Metal‐organic frameworks (MOFs) have been widely studied due to their versatile applications and easily tunable structures. However, heteroatom‐metal coordination dominates the MOFs community, and the rational synthesis of carbon–metal coordination‐based MOFs remains a significant challenge. Herein, two‐dimensional (2D) MOFs based on silver–carbon linkages are synthesized through the coordination between silver(I) salt and isocyanide‐based monomers at ambient condition. The as‐synthesized 2D MOFs possess well‐defined crystalline structures and a staggered AB stacking mode. Most interestingly, these 2D MOFs, without π–π stacking between layers, exhibit narrow bandgaps down to 1.42 eV. As electrochemical catalysts for converting CO2 to CO, such 2D MOFs demonstrate Faradaic efficiency over 92%. Surprisingly, the CO2 reduction catalyzed by these MOFs indicates favorable adsorption of CO2 and *COOH on the active carbon sites of the isocyanide groups rather than on silver sites. This is attributed to the critical σ donor role of isocyanides and the corresponding ligand‐to‐metal charge–transfer effect. This work not only paves the way toward a new family of MOFs based on metal–isocyanide coordination but also offers a rare platform for understanding the electrocatalysis processes on strongly polarized carbon species.    

    

* Two‐Dimensional Silver–Isocyanide Frameworks  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403080791
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202417658")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403080791"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403080791"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403080791"))][Get cited by]]

OpenAlex: https://openalex.org/W4403080791 (Open access: False)
    
[[https://openalex.org/A5077459472][Kaiyue Jiang]], [[https://openalex.org/A5057451591][Pu Yan]], [[https://openalex.org/A5101997579][Pengfei Shi]], [[https://openalex.org/A5075460158][Jichao Zhang]], [[https://openalex.org/A5050942599][Xinyu Chai]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5057665432][Chenhui Zhu]], [[https://openalex.org/A5100535765][Chongqing Yang]], [[https://openalex.org/A5029903067][Chenbao Lu]], [[https://openalex.org/A5100330523][Yi Liu]], [[https://openalex.org/A5069271154][Kecheng Cao]], [[https://openalex.org/A5006485558][Xiaodong Zhuang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202417658 
     
Metal‐organic frameworks (MOFs) have been widely studied due to their versatile applications and easily tunable structures. However, heteroatom‐metal coordination dominates the MOFs community, and the rational synthesis of carbon–metal coordination‐based MOFs remains a significant challenge. Herein, two‐dimensional (2D) MOFs based on silver–carbon linkages are synthesized through the coordination between silver(I) salt and isocyanide‐based monomers at ambient condition. The as‐synthesized 2D MOFs possess well‐defined crystalline structures and a staggered AB stacking mode. Most interestingly, these 2D MOFs, without π–π stacking between layers, exhibit narrow bandgaps down to 1.42 eV. As electrochemical catalysts for converting CO2 to CO, such 2D MOFs demonstrate Faradaic efficiency over 92%. Surprisingly, the CO2 reduction catalyzed by these MOFs indicates favorable adsorption of CO2 and *COOH on the active carbon sites of the isocyanide groups rather than on silver sites. This is attributed to the critical σ donor role of isocyanides and the corresponding ligand‐to‐metal charge–transfer effect. This work not only paves the way toward a new family of MOFs based on metal–isocyanide coordination but also offers a rare platform for understanding the electrocatalysis processes on strongly polarized carbon species.    

    

* Road construction in arid zones: valuation of local materials  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402941806
:TOPICS: Land-Use Suitability Assessment Using GIS
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54021/seesv5n2-259")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402941806"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402941806"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402941806"))][Get cited by]]

OpenAlex: https://openalex.org/W4402941806 (Open access: False)
    
[[https://openalex.org/A5021810395][Adam Mustapha]], [[https://openalex.org/A5107587920][Abdeldjalil M’hammed]], [[https://openalex.org/A5089239910][Moulay Omar Hassan]], [[https://openalex.org/A5107421911][Djaafari Driss]], [[https://openalex.org/A5005654965][Bennacer Lyacine]], [[https://openalex.org/A5015655652][Mohammed Abbou]], [[https://openalex.org/A5107627223][Belaidi Khedidja]], STUDIES IN ENGINEERING AND EXACT SCIENCES. 5(2)] 2024. https://doi.org/10.54021/seesv5n2-259 
     
The materials constituting the pavement bodies, until today, have been limited to certain so-called noble materials (rolled sands, aggregates, etc.), but these are in the process of being exhausted under the effect of intensive exploitation and the scarcity of quality quarries. With the objective of preserving the deposits of aggregates in the process of exhaustion for future generations and of exploiting the aeolian sands in abundance in the regions of southern Algeria, we aim to enhance the latter in the body of the roadway mixed with the tuffs, this would imply a reduction in construction costs (use of local aggregates of lower quality available in large quantities, reduction in transport costs). From an environmental point of view, this would limit the impacts with a reduction in CO2 emissions linked to transport. In this work, we applied a new approach based on the technique of mixtures to valorize and exploit the sand of dunes existing in abundance, with the treatment in hydraulic binders, which allowed us to go up to 20% of sand dunes.    

    

* Effect of Customized Fertilizer Formulations on Brinjal (Solanum melongena L.) under Sodic Soil  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402991788
:TOPICS: Management of Soil Fertility and Crop Productivity, Deficit Irrigation for Agricultural Water Management, Factors Affecting Maize Yield and Lodging Resistance
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.9734/ajsspn/2024/v10i4391")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402991788"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402991788"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402991788"))][Get cited by]]

OpenAlex: https://openalex.org/W4402991788 (Open access: True)
    
[[https://openalex.org/A5083553064][Sherene Jenita Rajammal]], [[https://openalex.org/A5103665465][A. Kaleeswari T]], [[https://openalex.org/A5081381388][S. Maragatham]], [[https://openalex.org/A5012762880][R. Arulmozhian]], Asian Journal of Soil Science and Plant Nutrition. 10(4)] 2024. https://doi.org/10.9734/ajsspn/2024/v10i4391 
     
The Customized Fertilizer Formulation (CFF) applications on growth and yield of Brinjal (Solanum melongena L.) varieties Manaparai local and CO-2 under sodic soils were studied with eleven CFF combinations. No Significant observations in growth yield and yield parameter was recorded due to the combined application of CFF and organic amendments on sodic soils. The symptoms of salt injury were well pronounced in brinjal cv. Manaparai local when compared to brinjal cv. CO2 though the sodic soil reclamation was done with gypsum @1.1 t/Ha. The salt injury was further confirmed with electrolyte leakage study conducted at field level. However, the treatment T11 i.e. CFF2 100% macro nutrients as straight fertilizers, liquid micronutrient formulation and composted Press mud @ 5 t/ha was found to have the brinjal fruit yield of 1.39 t/ha in cv. CO2 which was not a desirable yield. This might be due to the yield reduction per unit increase in salt content.    

    

* Numerical Investigation of CO and NO Production from Premixed Hydrogen/Methane Fuel Blends  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402939147
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Power Generation and Energy Systems
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1115/1.4066701")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402939147"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402939147"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402939147"))][Get cited by]]

OpenAlex: https://openalex.org/W4402939147 (Open access: False)
    
[[https://openalex.org/A5073331547][Sarbjit Singh]], [[https://openalex.org/A5088837000][Harish Rajagopalan]], [[https://openalex.org/A5028739615][Benjamin Emerson]], [[https://openalex.org/A5077986149][David R. Noble]], [[https://openalex.org/A5005647340][Robert C. Steele]], [[https://openalex.org/A5082528509][Tim Lieuwen]], Journal of Engineering for Gas Turbines and Power. None(None)] 2024. https://doi.org/10.1115/1.4066701 
     
Abstract There is significant interest in utilizing hydrogen as an energy carrier in a net-zero carbon energy economy. A variety of fundamental and practical issues associated with premixed hydrogen/methane combustion must be addressed, particularly flame flashback, combustion instabilities, and NOx emissions. Significantly less attention has been given to CO emissions from hydrogen blending. However, recent H2 blending engine tests have clearly noted major reductions in CO emissions, reductions which substantially exceed what would be expected based upon C atom mass balances in the fuel. Moreover, NOx, CO, and combustor operability always tradeoff with each other, and so for example, these CO reductions can also enable operational or design modifications to reduce NOx emissions and/or wider operability windows. This paper addresses H2 blending effects on CO emissions, addressing both the direct influences on CO emissions, as well as how it influences NOx-CO tradeoffs. The paper presents computations that differentiate between the kinetic and equilibrium effects of H2 blending, as well as how H2 blending can lead to reductions in both NOx and CO by moving the Pareto front downward. Finally, this work suggests that H2 blending, in addition to its CO2 reductions, can also increase plant operational flexibility and so provide additional value propositions to an evolving electricity market.    

    

* Dynamic Adaptation of Active Site Driven by Dual‐side Adsorption in Single‐Atomic Catalysts During CO2 Electroreduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403041985
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Molecular Electronic Devices and Systems, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202411765")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403041985"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403041985"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403041985"))][Get cited by]]

OpenAlex: https://openalex.org/W4403041985 (Open access: False)
    
[[https://openalex.org/A5059260162][Nam V. Tran]], [[https://openalex.org/A5100657882][Jiyuan Liu]], [[https://openalex.org/A5074258793][Shuzhou Li]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202411765 
     
Single‐atom iron embedded in N‐doped carbon (Fe‐N‐C) is among the most representative single‐atomic catalysts (SACs) for electrochemical CO2 reduction reaction (CO2RR). Despite the simplicity of the active site, the CO2‐to‐CO mechanism on Fe‐N‐C remains controversial. Firstly, there is a long debate regarding the rate‐determining step (RDS) of the reactions. Secondly, recent computational and experimental studies are puzzled by the fact that the CO‐poisoned Fe centers still remain highly active at high potentials. Thirdly, there are ongoing challenges in elucidating the high selectivity of hydrogen evolution reaction (HER) over CO2RR at high potentials. In this work, we introduce a novel CO2RR mechanism on Fe‐N‐C, which was inspired by the dynamic of active sites in biological systems. By employing grand‐canonical density functional theory and kinetic Monte‐Carlo, we found that the RDS is not fixed but changes with the applied potential. We demonstrated that our proposed dual‐side mechanisms could clarify the reason behind the high catalytic activity of CO‐poisoned metal centers, as well as the high selectivity of HER over CO2RR at high potential. This study provides a fundamental explanation for long‐standing puzzles of an important catalyst and calls for the importance of considering the dynamic of active sites in reaction mechanisms.    

    

* Dynamic Adaptation of Active Site Driven by Dual‐side Adsorption in Single‐Atomic Catalysts During CO2 Electroreduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403043003
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202411765")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403043003"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403043003"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403043003"))][Get cited by]]

OpenAlex: https://openalex.org/W4403043003 (Open access: False)
    
[[https://openalex.org/A5059260162][Nam V. Tran]], [[https://openalex.org/A5100657882][Jiyuan Liu]], [[https://openalex.org/A5074258793][Shuzhou Li]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202411765 
     
Single‐atom iron embedded in N‐doped carbon (Fe‐N‐C) is among the most representative single‐atomic catalysts (SACs) for electrochemical CO2 reduction reaction (CO2RR). Despite the simplicity of the active site, the CO2‐to‐CO mechanism on Fe‐N‐C remains controversial. Firstly, there is a long debate regarding the rate‐determining step (RDS) of the reactions. Secondly, recent computational and experimental studies are puzzled by the fact that the CO‐poisoned Fe centers still remain highly active at high potentials. Thirdly, there are ongoing challenges in elucidating the high selectivity of hydrogen evolution reaction (HER) over CO2RR at high potentials. In this work, we introduce a novel CO2RR mechanism on Fe‐N‐C, which was inspired by the dynamic of active sites in biological systems. By employing grand‐canonical density functional theory and kinetic Monte‐Carlo, we found that the RDS is not fixed but changes with the applied potential. We demonstrated that our proposed dual‐side mechanisms could clarify the reason behind the high catalytic activity of CO‐poisoned metal centers, as well as the high selectivity of HER over CO2RR at high potential. This study provides a fundamental explanation for long‐standing puzzles of an important catalyst and calls for the importance of considering the dynamic of active sites in reaction mechanisms.    

    

* A novel approach to estimate building electric power consumption based on machine learning method: toward net-zero energy, low carbon and smart buildings  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402932603
:TOPICS: Electricity Price and Load Forecasting Methods, Building Energy Efficiency and Thermal Comfort Optimization, Machine Learning Methods for Solar Radiation Forecasting
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/ijlct/ctae084")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402932603"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402932603"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402932603"))][Get cited by]]

OpenAlex: https://openalex.org/W4402932603 (Open access: True)
    
[[https://openalex.org/A5013561618][Badr Saad Alotaibi]], [[https://openalex.org/A5023045589][Mohammed Awad Abuhussain]], [[https://openalex.org/A5083803962][Yakubu Aminu Dodo]], [[https://openalex.org/A5047459537][Nedhal Al-Tamimi]], [[https://openalex.org/A5088861253][Ammar Maghrabi]], [[https://openalex.org/A5029183147][Henry Ojobo]], [[https://openalex.org/A5067899491][Ahmad Usman Naibi]], [[https://openalex.org/A5107587036][Natei Ermias Benti]], International Journal of Low-Carbon Technologies. 19(None)] 2024. https://doi.org/10.1093/ijlct/ctae084 
     
Abstract The modern era has witnessed a surge in energy consumption and its dependence on fossil fuels, which are harmful to the environment, prompting researchers to examine techniques for regulating energy usage in buildings, specifically with regard to residential electricity consumption. The pursuit of net-zero energy consumption and low carbon emission buildings is a significant undertaking that nations across the globe are actively endeavoring to accomplish. In order to accomplish this goal, the structure in question must efficiently oversee its overall energy usage while concurrently capitalizing on sustainable energy sources. The precise estimation of future electricity usage in buildings is an essential element in the process of energy efficiency planning and optimization. The present study introduces a soft computing methodology and data decomposition as approaches for evaluating the energy usage of residential structures. An innovative machine learning approach is introduced for the purpose of estimating the initial cost required to construct a green structure that consumes no net energy. By utilizing wavelet decomposition, it is possible to determine how to transform the structure into one that is intelligent and energy efficient. Following wavelet parallel converter analysis, the data were processed with an estimator model based on an ideal neural network. The results indicate that the mean estimation errors for recurrent neural network, Autoregressive fractionally integrated moving average (ARFIMA), and gene expression programming (GEP) were reduced by 72%, 65%, and 77%, respectively, using this method. Conversely, when the proposed methodology is applied to the smart management of building energy consumption, the examined structures experience an average reduction of 8% in energy consumption. Moreover, the outcomes of CO2 gas emissions demonstrate that the suggested model possesses the capability to accurately forecast CO2 emissions. The study highlights the necessity of employing innovative techniques such as machine learning to decrease building energy usage and CO2 emissions. The discovery of these results can assist policymakers and stakeholders in the energy sector in advancing the adoption of smart building technologies.    

    

* A Quantum Mechanical MP2 Study of the Electronic Effect of Nonplanarity on the Carbon Pyramidalization of Fullerene C60  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402994082
:TOPICS: Chemistry and Applications of Fullerenes, Carbon Nanotubes and their Applications, Graphene: Properties, Synthesis, and Applications
:PUBLICATION_DATE: 2024-09-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/nano14191576")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402994082"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402994082"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402994082"))][Get cited by]]

OpenAlex: https://openalex.org/W4402994082 (Open access: True)
    
[[https://openalex.org/A5084924196][Yuemin Liu]], [[https://openalex.org/A5008618886][Yunxiang Gao]], [[https://openalex.org/A5001151503][Tariq Altalhi]], [[https://openalex.org/A5017861528][Di‐Jia Liu]], [[https://openalex.org/A5003665485][Boris I. Yakobson]], Nanomaterials. 14(19)] 2024. https://doi.org/10.3390/nano14191576 
     
Among C60’s diverse functionalities, its potential application in CO2 sequestration has gained increasing interest. However, the processes involved are sensitive to the molecule’s electronic structure, aspects of which remain debated and require greater precision. To address this, we performed structural optimization of fullerene C60 using the QM MP2/6–31G* method. The nonplanarity of the optimized icosahedron is characterized by two types of dihedral angles: 138° and 143°. The 120 dihedrals of 138° occur between two hexagons intersecting at C–C bonds of 1.42 Å, while the 60 dihedrals of 143° are observed between hexagons and pentagons at C–C bonds of 1.47 Å. NBO analysis reveals less pyramidal sp1.78 hybridization for carbons at the 1.42 Å bonds and more pyramidal sp2.13 hybridization for the 1.47 Å bonds. Electrostatic potential charges range from −0.04 a.u. to 0.04 a.u. on the carbon atoms. Second-order perturbation analysis indicates that delocalization interactions in the C–C bonds of 1.42 Å (143.70 kcal/mol) and 1.47 Å (34.98 kcal/mol) are 22% and 38% higher, respectively, than those in benzene. MP2/Def2SVP calculations yield a correlation energy of 13.49 kcal/mol per electron for C60, slightly higher than the 11.68 kcal/mol for benzene. However, the results from HOMO-LUMO calculations should be interpreted with caution. This study may assist in the rational design of fullerene C60 derivatives for CO2 reduction systems.    

    

* Study of The Energy, Economic, Environmental, and Thermal Comfort Impact of The Integration of Hemp Concrete and Hemp Plaster in a Residential Building Envelope in Morocco  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403062885
:TOPICS: Sustainable Earth Construction Materials and Techniques, Urban Design and Cultural Heritage Conservation, Solar Chimney Systems
:PUBLICATION_DATE: 2024-09-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.37934/arnht.23.1.127")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403062885"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403062885"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403062885"))][Get cited by]]

OpenAlex: https://openalex.org/W4403062885 (Open access: False)
    
[[https://openalex.org/A5044354908][H. Kaddouri]], [[https://openalex.org/A5097821511][Abderrahim Abidouche]], [[https://openalex.org/A5018436716][Mohamed Saidi Hassani Alaoui]], [[https://openalex.org/A5013207882][I. Driouch]], [[https://openalex.org/A5089190461][Said Hamdaoui]], [[https://openalex.org/A5103822243][Abdelouahad Ait Msaad]], Journal of Advanced Research in Numerical Heat Transfer. 23(1)] 2024. https://doi.org/10.37934/arnht.23.1.127 
     
In the building sector, the majority of efforts are aimed at achieving greater energy efficiency, a low carbon footprint, and optimum thermal comfort to make buildings more efficient, more sustainable, and more pleasant to live in. In this context, this paper aims to assess the impact of integrating environmentally friendly and green materials (lime-hemp plaster and hemp concrete) into the envelope of an existing residential building. A numerical simulation study was carried out using TRNSYS 18, in four Moroccan climates: Mediterranean, cold semi-arid, hot semi-arid, and hot and dry desert, to study the energy, economic, and environmental impact, as well as that of the thermal comfort. The proposed construction scenarios are compared with the reference scenario in terms of heating and cooling requirements, electricity bills, carbon footprint, and percentage of annual thermal discomfort. The results show that energy savings are highest in the cold semi-arid climate (Oujda) at around 24%. Hemp concrete construction is more effective in reducing heating requirements, with a reduction of up to 39.4%. For cooling, the reduction is only 15.5%. The economic and environmental study shows that using materials such as hemp concrete in an optimal construction and climatic context can reduce electricity bills by 25% and CO2 emissions by around 23.7%. However, the reduction in terms of hours of discomfort is not yet significant enough. Hence the need to combine this technique with other strategies based on bioclimatic design. The use of hemp plaster and concrete for renovating existing buildings or constructing new ones represents a very promising alternative from several points of view: energy, economic, and environmental.    

    

* Managing Regional Development In The Area of Renewable Energy Sources In Poland  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403039097
:TOPICS: Energy Transition and Renewable Resources Integration, Energy Supply and Security Issues for Developed Economies, Integration of Renewable Energy Systems in Power Grids
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5171/2024.4314224")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403039097"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403039097"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403039097"))][Get cited by]]

OpenAlex: https://openalex.org/W4403039097 (Open access: False)
    
[[https://openalex.org/A5019317544][M. Filipowicz]], Communications of International Proceedings. None(None)] 2024. https://doi.org/10.5171/2024.4314224 
     
This article examines the challenges of power grid congestion in a municipality located in central Poland and presents potential solutions in the form of a photovoltaic farm project or prosumer group installation. In the context of growing demand for electricity and an increasing number of households producing energy from renewable sources, there is a need to upgrade the energy infrastructure to meet the needs of the local community. A planned photovoltaic farm or group prosumer installations are not only a way to relieve stressed grids, but also a step towards sustainable energy production and reduction of CO2 emissions. In the article, I also discuss the economic, social and environmental aspects of implementing these projects and the possible benefits for the municipality and its residents. My analysis indicates the potential for solar energy development in the region and presents effective tools that can help modernize energy infrastructure and promote sustainable development in local communities.    

    

* Size‐dependent Copper Nanoparticles Supported on Carbon Nanotubes with Balanced Cu+ and Cu0 Dual Sites for the Selective Hydrogenation of Ethylene Carbonate  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403081561
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202402699")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403081561"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403081561"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403081561"))][Get cited by]]

OpenAlex: https://openalex.org/W4403081561 (Open access: False)
    
[[https://openalex.org/A5101583020][Wanghua Chen]], [[https://openalex.org/A5036155652][Dahye Ji]], [[https://openalex.org/A5100349284][Yanfei Zhang]], [[https://openalex.org/A5101764594][Yuanyuan Cui]], [[https://openalex.org/A5049833038][Yinfeng Cheng]], [[https://openalex.org/A5100714539][Songlin Wang]], [[https://openalex.org/A5073522891][Wei‐Lin Dai]], Chemistry - A European Journal. None(None)] 2024. https://doi.org/10.1002/chem.202402699 
     
Cyclic carbonate hydrogenation offers an alternative for the efficient indirect CO2 utilization. In this study, a series of carbon nanotubes (CNTs) supported xCu/CNTs catalysts with different Cu loadings were fabricated using a convenient impregnation method, and exhibited excellent catalytic activity for the hydrogenation of ethylene carbonate to methanol and ethylene glycol. The structural and physicochemical properties revealed that acid treatment of CNTs resulted in plentiful oxygen‐containing functional groups, providing sufficient anchoring sites for copper species. The calcination process conducted under an inert atmosphere resulted in the formation of ternary CuO, Cu2O, and Cu composites, enhancing the metal‐support interaction and facilitating the formation of balanced Cu0 and Cu+ dual sites as well as high active surface area after reduction. Contributed to the synergetic effect of balanced Cu+ and Cu0 species proved by density functional theory calculation and the electron‐rich CNTs surface, the 40Cu/CNTs catalyst achieved strengthened catalytic performance with methanol yield of 83%, ethylene glycol yield of 99% at ethylene carbonate conversion of >99%, and 150 h of long‐term running stability. Consequently, CNTs supported Cu serve as efficient non‐silica based catalyst for ester hydrogenation.    

    

* Research progress of high‐entropy oxides for electrocatalytic oxygen evolution reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403073360
:TOPICS: Electrocatalysis for Energy Conversion, Emergent Phenomena at Oxide Interfaces, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401663")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403073360"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403073360"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403073360"))][Get cited by]]

OpenAlex: https://openalex.org/W4403073360 (Open access: False)
    
[[https://openalex.org/A5101742243][Qian Zhang]], [[https://openalex.org/A5091806162][Xuexue Wang]], [[https://openalex.org/A5050327114][Xiaomeng Lv]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401663 
     
High‐entropy oxides (HEOs), similar to high‐entropy materials (HEMs), have "four‐core effects", i.e., high‐entropy effect, delayed diffusion effect, lattice distortion effect and cocktail effect, which have attracted more and more attention in the scientific field of renewable energy technology due to their unique structural characteristics, variable chemical composition and corresponding functional properties. HEOs have become potential candidates for electrocatalytic oxygen evolution reaction (OER), which is a key half reaction for electrolytic CO2, nitrogen reduction, and water electrolysis. However, the precise synthesis of HEOs with a wide range of components and structures is challenging, not to mention their active and stable operation for OER. In this paper, we review the recent advancements in the electrocatalytic oxygen evolution facilitated by HEOs in water electrolysis. We analyze these developments from the perspectives of activity and stability in acid and alkaline conditions, respectively. Furthermore, we summarize the design from the aspect of element composition, structure, morphology, and catalyst‐support interactions, along with related reaction mechanism of HEOs. Additionally, we discuss the current challenges faced by HEOs in the field of OER and suggest potential directions for the future development of HEOs beyond water electrolysis application.    

    

* Energy Efficiency and Sustainability in Food Retail Buildings: Introducing a Novel Assessment Framework  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402964044
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization, Sustainable Construction and Green Building, Impact of Workspace Environment on Work Performance
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17194882")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402964044"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402964044"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402964044"))][Get cited by]]

OpenAlex: https://openalex.org/W4402964044 (Open access: True)
    
[[https://openalex.org/A5092187752][Simone Forastiere]], [[https://openalex.org/A5050106530][Cristina Piselli]], [[https://openalex.org/A5095886883][Andrea Silei]], [[https://openalex.org/A5026880138][Fabio Sciurpi]], [[https://openalex.org/A5038114517][Anna Laura Pisello]], [[https://openalex.org/A5067111142][Franco Cotana]], [[https://openalex.org/A5070746225][Carla Balocco]], Energies. 17(19)] 2024. https://doi.org/10.3390/en17194882 
     
One of the primary global objectives is to decrease building energy consumption to promote energy efficiency and environmental sustainability. The large-scale food retail trade sector accounts for over 15% of total primary energy consumption in Europe, posing a significant challenge to the transition towards green energy. This study proposes a simple method for energy efficiency, environmental sustainability, and cost-saving assessment and improvement in large-scale food retail trade buildings. It aims to analyze the energy and environmental performance of building–plant systems, establishing an interactive network to assess intervention potential for the energy transition. The investigation focuses on the proper selection and analysis of the benefits of retrofit solution implementation, emphasizing potential energy savings in current and future climate change scenarios. Dynamic simulation with the Building Energy Model (BEM) was used to evaluate the impacts of building–plant system retrofit solutions, such as high thermal insulation, photovoltaic (PV) panels, Light Emitting Diode (LED) installation, waste heat recovery, and improvement in refrigeration units. The results show a reduction in annual energy consumption for the PV panel installation by up to 29% and lighting systems with high-quality LED to 60%. Additionally, CO2 emissions can be decreased by up to 41% by combining these two strategies.    

    

* Extended emission footprint analysis of dispatchable gas-based power generation technologies with exhaust aftertreatment technologies  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403007972
:TOPICS: Integration of Electric Vehicles in Power Systems
:PUBLICATION_DATE: 2024-09-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.33737/gpps24-tc-088")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403007972"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403007972"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403007972"))][Get cited by]]

OpenAlex: https://openalex.org/W4403007972 (Open access: False)
    
[[https://openalex.org/A5044884645][Christian Goßrau]], [[https://openalex.org/A5023839322][Nils Holger Petersen]], [[https://openalex.org/A5003572868][L. de la Cruz-May]], [[https://openalex.org/A5005350540][Manfred Wirsum]], [[https://openalex.org/A5107672289][Alexander Lampkowski]], [[https://openalex.org/A5014925020][Ariel Schönberger Alvarez]], [[https://openalex.org/A5076463194][J. Classen]], [[https://openalex.org/A5042106002][Stefan Pischinger]], Proceedings. None(None)] 2024. https://doi.org/10.33737/gpps24-tc-088 
     
The mitigation of climate change poses severe pressure on the rapid replacement of conventional power generation technologies by renewables. Due to the inherent volatility of renewable power generation technologies, dispatchable power generation units, such as gas turbines (GT) and gas-based reciprocating internal combustion engines (RICE), must be operated to maintain grid stability. While RICE are equipped with exhaust aftertreatment (EAT) technologies as standard to meet regulatory emission limits, this may also become important for GT in the near future. The present study therefore investigates the influence of EAT on emissions, taking into account oxidation catalysts (OC) and selective catalytic reduction (SCR) catalysts. Single-cycle power plant configurations for both technologies are studied under different operation scenarios, with emphasis on start-ups and partial load operation. Emissions are assessed as “generated mass per electrical output” (g=kWhel), considering both greenhouse gases and local pollutants. To holistically assess the environmental footprint, emissions are converted into impact categories such as Global Warming Potential (GWP), Respiratory Inorganics (RI), Photochemical Ozone Formation (POF) and Human Toxicity Potential (HTP). The increasing variability of operation demands of gas-based power generation technologies leads to a significant increase of emissions and environmental impact without EAT, highlighting the overall need for EAT systems to meet regulatory limits in the future. Both technologies show a significant reduction in the environmental impact factors (RI: > 46 %, POF: > 87 %, HTP: > 86 %) with EAT deployment in all load profile scenarios. With CO2 largely unaffected by EAT, RICE has a lower GWP100 than GT for all load scenarios (-2.6 to -11.4 %) because of the higher average plant efficiency. Due to their modularity, RICE plants can be operated over most of the plant load range without excessive emissions, whereas GT plants are limited to operation above 30 %.    

    

* Adaptive investment behaviours enable earlier carbon peak in low-carbon electricity transition  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402923944
:TOPICS: Global Energy Transition and Fossil Fuel Depletion
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-5075643/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402923944"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402923944"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402923944"))][Get cited by]]

OpenAlex: https://openalex.org/W4402923944 (Open access: False)
    
[[https://openalex.org/A5062602992][Hongyang Zou]], [[https://openalex.org/A5013271776][Huibin Du]], [[https://openalex.org/A5026676538][Jian Zuo]], [[https://openalex.org/A5007307922][Gang He]], [[https://openalex.org/A5049493168][Kuishuang Feng]], [[https://openalex.org/A5072261499][Yuting Yang]], [[https://openalex.org/A5101409236][Chengshan Wang]], [[https://openalex.org/A5080304378][Lixin Tang]], [[https://openalex.org/A5090675889][Marilyn A. Brown]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-5075643/v1 
     
Abstract Electricity planning often employs average production costs and efficiencies, assuming that energy companies are homogeneous. In reality, firms are heterogeneous in the scale, cost and efficiency of their power generation, leading to various adaptive behaviours such as differentiated investments in CO2 reductions and offsets. This has resulted in misjudgments about climate tipping points and unanticipated delays in phasing out coal-fired technology. Here we develop an agent-based model using company-level technology-specific installed capacity, cost and efficiency within China’s electricity sector. We estimate renewable energy expansion and carbon peaks by simulating companies’ adaptive behaviours. The results indicate that if such behaviours focused on technology stock and return-on-investment, China’s electricity sector could have reached carbon peak by 2019-2020, ahead of the national 2030 target. By analyzing adaptive investment behaviours, we pinpoint distinct profit strategies for companies with varying technology capacities. This enables tailored incentives, avoiding the fiscal inefficiencies of one-size-fits-all policies like uniform feed-in-tariffs. Our behavioural analysis further illustrates that the delayed phase-out of coal-fired technology, due to lock-in effects, could result in coal power overcapacity and hinder the operation of renewable energy generation. Policies to accelerate the phase-out of coal capacity are becoming increasingly imperative relative to incentivizing the scale-up of renewables.    

    

* Monitoring and adjustments of combustion parameters in reheating furnaces using a digital tool  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402964415
:TOPICS: Power Generation and Energy Systems, Coal Water Slurry Technology and Utilization, Inverse Radiative Heat Transfer Analysis
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.70342/dyin3512")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402964415"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402964415"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402964415"))][Get cited by]]

OpenAlex: https://openalex.org/W4402964415 (Open access: False)
    
[[https://openalex.org/A5072017433][Kássio Nogueira Cançado]], [[https://openalex.org/A5013913599][Aristides Almeida Rocha]], [[https://openalex.org/A5107630316][Rafaela Rapalo]], [[https://openalex.org/A5004967609][Paula Pomaro]], [[https://openalex.org/A5052506374][Lis Nunes Soares]], No host. 1(2)] 2024. https://doi.org/10.70342/dyin3512 
     
Improving the energy efficiency of a reheating furnace is not a simple task because it involves a large number of parameters that, most of the time, are connected in a complex way. To be feasible, the evaluation of such a vast number of variables must be supported by digital tools that are embedded with artificial intelligence. The SMS group has developed a digital tool that effectively supports operators and engineers in enhancing energy efficiency within the reheating furnaces of hot rolling mills. This paper presents a quick study case of the use of Viridis Performance, an application of Viridis Energy & Sustainability Suite, in the analysis and correction of the deviations in the air-gas ratio of a reheating furnace. In this study, a production period of 8 hours was evaluated, during which the air-gas ratio presented a significant deviation. Analysis showed that the probable cause of the deviation was a production stoppage where the furnace control was set to manual mode. A reduction potential of 0.26 Gcal/h and a 13 kg/h decrease in CO2 emissions were identified. Viridis Performance would support the process by guiding the decisions of the operator in a way that energy losses would be avoided or minimized. The potential economic savings were also quantified. This task is performed in the system by Viridis Moneybox, which is another application of Viridis Energy & Sustainability Suite. The results showed potential savings of 13 US $/h. In addition to the gains and savings outlined in this study, the utilization of Viridis Performance encompasses numerous other advantages, such as enhanced operational standardization and improved process capability, to name just a few.    

    

* Selenium Biofortification of Pleurotus Mushrooms and Utilization of Spent Waste for Vermicomposting: A Sustainable Approach for Circular Agriculture  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402928621
:TOPICS: Medicinal Mushrooms: Antitumor and Immunomodulating Properties, Mycorrhizal Fungi and Plant Interactions, Plant-Parasitic Nematodes in Molecular Plant Pathology
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18805/ag.d-6060")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402928621"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402928621"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402928621"))][Get cited by]]

OpenAlex: https://openalex.org/W4402928621 (Open access: True)
    
[[https://openalex.org/A5107553834][H. Abinaya]], [[https://openalex.org/A5091140709][M. Haritha]], [[https://openalex.org/A5074923062][SINDHU SINDHU]], [[https://openalex.org/A5107586520][C.A. Annaporani]], [[https://openalex.org/A5061444657][D. Lavanya]], Agricultural Science Digest - A Research Journal. None(Of)] 2024. https://doi.org/10.18805/ag.d-6060 
     
Background: Agro-wastes represent valuable resources for mushroom cultivation, particularly Pleurotus species, which offer significant nutritional benefits and are grown using cost-effective methods. Selenium (Se), an essential micronutrient crucial for human health, is vital for preventing various diseases. Sodium selenite has emerged as an effective method for increasing selenium levels in mushrooms, thereby enhancing their nutritional quality. Additionally, utilizing biofortified spent mushroom waste for vermicomposting presents a sustainable solution for recycling organic waste and improving soil fertility. Methods: This study examines the biofortification of three Pleurotus species by applying sodium selenite in paddy straw substrate. The research investigates selenium accumulation and its impact on yield and biological efficiency, in addition to assessing various biochemical parameters. Furthermore, the study explores the influence of selenium-biofortified spent mushroom waste on the growth of earthworms during the vermicomposting process. Result: Our investigation into the biofortification of mushrooms with selenium revealed that incorporating 5% of sodium selenite into the substrate significantly enhanced the selenium content of Pleurotus ulmarius (CO2), Pleurotus florida and Pleurotus eous (APK1). However, increasing selenium content in the substrate correlated with decreased biological efficiency. Selenium biofortification resulted in a noteworthy increase in protein content alongside a reduction in carbohydrate levels. Moreover, utilizing selenium-biofortified spent mushroom waste (SeSMS) at a concentration of 2.5% in combination with cow dung (1:10) yielded favorable outcomes, including enhanced cocoon production and the presence of young and adult worms during vermicomposting on both the 60th and 90th day.    

    

* Accelerated training of deep learning surrogate models for surface   displacement and flow, with application to MCMC-based history matching of CO2   storage operations  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403007308
:TOPICS: Advanced Techniques in Reservoir Management, Pore-scale Imaging and Enhanced Oil Recovery, Carbon Dioxide Sequestration in Geological Formations
:PUBLICATION_DATE: 2024-08-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2408.10717")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403007308"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403007308"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403007308"))][Get cited by]]

OpenAlex: https://openalex.org/W4403007308 (Open access: True)
    
[[https://openalex.org/A5055381891][Yifu Han]], [[https://openalex.org/A5047662931][François P. Hamon]], [[https://openalex.org/A5002057296][Louis J. Durlofsky]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2408.10717  ([[http://arxiv.org/pdf/2408.10717][pdf]])
     
Deep learning surrogate modeling shows great promise for subsurface flow applications, but the training demands can be substantial. Here we introduce a new surrogate modeling framework to predict CO2 saturation, pressure and surface displacement for use in the history matching of carbon storage operations. Rather than train using a large number of expensive coupled flow-geomechanics simulation runs, training here involves a large number of inexpensive flow-only simulations combined with a much smaller number of coupled runs. The flow-only runs use an effective rock compressibility, which is shown to provide accurate predictions for saturation and pressure for our system. A recurrent residual U-Net architecture is applied for the saturation and pressure surrogate models, while a new residual U-Net model is introduced to predict surface displacement. The surface displacement surrogate accepts, as inputs, geomodel quantities along with saturation and pressure surrogate predictions. Median relative error for a diverse test set is less than 4% for all variables. The surrogate models are incorporated into a hierarchical Markov chain Monte Carlo history matching workflow. Surrogate error is included using a new treatment involving the full model error covariance matrix. A high degree of prior uncertainty, with geomodels characterized by uncertain geological scenario parameters (metaparameters) and associated realizations, is considered. History matching results for a synthetic true model are generated using in-situ monitoring-well data only, surface displacement data only, and both data types. The enhanced uncertainty reduction achieved with both data types is quantified. Posterior saturation and surface displacement fields are shown to correspond well with the true solution.    

    

* B-031 A new Ready to use Bio-Rad Quality Control to Streamline Daily Workflow  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403048859
:TOPICS: Management and Reproducibility of Scientific Workflows
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/clinchem/hvae106.395")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403048859"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403048859"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403048859"))][Get cited by]]

OpenAlex: https://openalex.org/W4403048859 (Open access: False)
    
[[https://openalex.org/A5093369284][A M Yagoot]], [[https://openalex.org/A5041872360][Hassan A. Khalil]], [[https://openalex.org/A5101760929][Mohammed A. Alharbi]], [[https://openalex.org/A5096913865][G. Almalayo]], [[https://openalex.org/A5018917563][Anwar Borai]], Clinical Chemistry. 70(Supplement_1)] 2024. https://doi.org/10.1093/clinchem/hvae106.395 
     
Abstract Background A comprehensive Quality Management System starts with performing a daily Quality Control (Q.C.) process. The daily Q.C. process monitors the Instrument’s optimal performance and detects shifts and trends. However, the existing traditional daily Q.C. process is not only prone to manual errors, but also time consuming, costly and labor intensive. We evaluated a Bio-Rad InteliQTM Load and go Quality Control that comes in a barcoded tube ready to be loaded. We monitored the workflow efficiency gained in comparison to the traditional quality control material that comes in glass vials. Methods We evaluated the new quality control material ready to load on the instrument. This new Q.C. (Bio-Rad InteliQ Assayed Multiqual Control - 3 levels) were processed in parallel with our routine Q.C. (Bio-Rad Assayed Chemistry Lyphocheck vials - 2 levels). We performed the evaluation on Abbott Architect c8000 Chemistry analyzers in our central Laboratory (NGHA-Jeddah). The Q.C. was stored frozen. Before testing it was thawed at room temperature as per the insert instruction. Over a 5 days period, in parallel with our routine quality control, we run the new Q.C. Two times per day for 33 analytes. We monitored the processing time difference between the new and current approaches. We monitored the stability of all the analytes in the tube after Two days and again after Five days. We also monitored the cost effectiveness, labor intensiveness, probability of operator error and the overall improvement in workflow and Turn Around Time. Results Over the evaluation period, we observed the following: - Saving 40 minutes in average per week only for chemistry Q.C (time spent in reconstituting, mixing and aliquoting old Q.C) - 100% reduction in waste of plastic consumables such as pipette and plastic tubes. - Save an average of 1.0 ml dead volume in every 5.0 ml old Q.C. vial (20% of the volume, hence saving 20% of the total Q.C. cost). The dead volume wasted due to aliquoting step using the old Q.C. - 100% Eliminated delays caused by operator error such as wrong reconstitution, inadequate mixing and wrong Q.C. aliquoting. Not needed for the InteliQ. - High score of staff satisfaction. - Stability of the 32 analytes was excellent except that of Co2, which deteriorated by 14% after Two days as indicated in the insert package. Co2 day five result deteriorated by 34%. Conclusions Bio-Rad InteliQ is easy to use. It saves time and cost. When combined with Unity Q.C. data management solution it can streamline Q.C. workflow, eliminate operator errors, reduce T.A.T. and increase the overall laboratory performance. It may also work optimally with Instruments that have on-board fridge for Q.C.    

    

* Sex-Based Differences in Pulmonary Function and Cardiopulmonary Response 30 Months Post-COVID-19: A Brazilian Multicentric Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402922794
:TOPICS: Neurological Manifestations of COVID-19 Infection, Standardisation and Management of COPD, Mechanical Ventilation in Respiratory Failure and ARDS
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ijerph21101293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402922794"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402922794"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402922794"))][Get cited by]]

OpenAlex: https://openalex.org/W4402922794 (Open access: True)
    
[[https://openalex.org/A5039532567][Cássia da Luz Goulart]], [[https://openalex.org/A5069879811][Guilherme Peixoto Tinoco Arêas]], [[https://openalex.org/A5024411477][Maurício Milani]], [[https://openalex.org/A5102635301][Fernanda Facioli dos Reis Borges]], [[https://openalex.org/A5076761841][Juliana Ribeiro Magalhães]], [[https://openalex.org/A5054551749][Guilherme Dionir Back]], [[https://openalex.org/A5049345749][Audrey Borghi‐Silva]], [[https://openalex.org/A5081034199][Luciano Fonseca Lemos de Oliveira]], [[https://openalex.org/A5075126774][André Paula]], [[https://openalex.org/A5085354071][Carolina Coimbra Marinho]], [[https://openalex.org/A5084896439][Déborah Pereira Prado]], [[https://openalex.org/A5073523967][Celso Nascimento de Almeida]], [[https://openalex.org/A5040274413][Cristiane Maria Carvalho Costa Dias]], [[https://openalex.org/A5043883445][Viní­cius Afonso Gomes]], [[https://openalex.org/A5039460964][Luiz Eduardo Fonteles Ritt]], [[https://openalex.org/A5030339093][Leandro Tolfo Franzoni]], [[https://openalex.org/A5033199964][Ricardo Stein]], [[https://openalex.org/A5010257239][Mansueto Gomes Neto]], [[https://openalex.org/A5013672770][Gerson Cipriano]], [[https://openalex.org/A5077065332][Fernando Val]], International Journal of Environmental Research and Public Health. 21(10)] 2024. https://doi.org/10.3390/ijerph21101293 
     
Aim: (I) to verify if there are sex differences in respiratory function, respiratory muscle strength, and effort limitation in individuals recovered from severe acute COVID-19 30 months after the initial infection, and (II) to evaluate the influence of length of stay on cardiorespiratory capacity among men and women. Methods: Cross-sectional observational multicentric study with participants from five Brazilian states (São Paulo, Amazonas, Minas Gerais, Bahia, and Brasília). We assessed lung function and respiratory muscle strength by maximum inspiratory pressure (MIP), maximum expiratory pressure (MEP), and cardiorespiratory fitness by cardiopulmonary exercise test (CPET). Results: 86 individuals were stratified by sex (48 women and 38 men). Females had significantly longer hospitalization for acute COVID-19 (p < 0.05) and showed a marked reduction in MIP (cmH2O and % predicted). Regarding the CPET, women presented lower V˙O2% predicted, O2 pulse, and oxygen uptake efficiency slope (OUES, % predicted) (p < 0.05). In addition, women also had greater abnormal combinations between RER < 1.10, OUES < 80% predicted, VE/VVM < 15% [3 (6.2%)] and V˙O2% predicted < 80%, V˙E/V˙CO2 slope and V˙O2/workload < 8.4 mL/min/W [8 (17%)]. The regression analysis showed a significant influence of age, length of hospitalization (< and >10 days), and FEV1/FVC (%) on the V˙O2 peak (mL·kg−1·min−1). Secondarily, we found that women hospitalized for more than 10 days had worse O2 pulse (p = 0.03), OUES % predicted (p < 0.001), and worse V˙O2% predicted (p < 0.009). Conclusion: Women exhibited more pronounced impairments in several key indicators of cardiopulmonary function 30 months post-infection.    

    

* A-198 ESG Opportunities Harnessed During Pathology Transformation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403071086
:TOPICS: Advancements in Biomedical Science and Health Research
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/clinchem/hvae106.196")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403071086"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403071086"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403071086"))][Get cited by]]

OpenAlex: https://openalex.org/W4403071086 (Open access: False)
    
[[https://openalex.org/A5063554177][T Ellison]], [[https://openalex.org/A5042030924][Louise Hughes]], [[https://openalex.org/A5077475299][R. F. G. Booth]], [[https://openalex.org/A5024936437][Garry M. Walsh]], [[https://openalex.org/A5005895944][David Dunn]], Clinical Chemistry. 70(Supplement_1)] 2024. https://doi.org/10.1093/clinchem/hvae106.196 
     
Abstract Background Synnovis (a SYNLAB business) is in the process of delivering one of the largest Pathology transformation programmes in the UK, moving to a seven-site hub and spoke model from 89 laboratories over a dispersed geography. This remit also presented an opportunity for SYNLAB to deliver on its Environmental Social Governance (ESG) ambitions, by embedding ESG principles into programme delivery. There are several examples within each ESG pillar that demonstrate the benefits to be leveraged during transformation. Methods SYNLAB’s vision is to deliver sustainable diagnostic services. The integration of ESG into both the decision-making process and transformation structure ties these ambitions into programme benefits realisation. As well as setting performance level targets, the delivery of ESG benefits provide measures of success throughout the transformation journey, motivating stakeholders and building confidence along the way. Results Environment: The efficient use of space and LEAN principle design has consolidated the fragmented laboratory services spanning 15,000m2 into a bespoke, cutting-edge Pathology Hub with 6 spokes (hospital based services). The new hub building was designed to achieve BREEAM Excellent standards which measure performance against criteria such as energy management and efficiency, sustainable design and materials. The hub’s energy is from renewable-backed sources, and we will achieve a 47% reduction in CO2 equivalent (CO2e) emissions by unifying a significant proportion of its legacy footprint in this way. Further energy savings will be achieved through the associated analytical equipment consolidation, including a decrease from 50 to 14 microtomes, a decrease of 29 to 15 ventilated benches and a reduction of over 200 fridges and freezers across the service. In addition, substantial CO2e emissions savings are also being delivered by moving to a greener logistics provider, utilising electric vehicles and bikes. 2023 saw such emissions fall by 60% across Synnovis, helping to keep London’s air cleaner. Social: The transformation programme enables the hand back of over 6,000m2 of real estate to Synnovis’ NHS partners to use for critical hospital services (the equivalent of over 150 operating theatres). Governance Both internally and externally, ESG is integrated within the Synnovis organisational culture. For example, internally it applies mandatory sustainability metrics to its solution selection processes. These influenced the selection of Abbott’s Indexor solution to support the transformation of Blood Sciences, delivering a saving of over 2.8 million plastic sample bags every year. Externally, SYNLAB works with its partners to manage this substantial and complex transformation programme. Risk management is assured through transparency, securing confidence in the good use of public funds, ensuring responsiveness to customer and partner feedback, and ensuring accountability for and the delivery of targeted healthcare outcomes. Conclusions The integration of SYNLAB’s ESG strategy within the transformation programme is delivering tangible benefits across all ESG pillars. It has highlighted that in addition to the core outcome of services transformation, there are many more opportunities that can be realised as a result of making ESG an integral part of the pathology transformation programme.    

    

* INTEGRAÇÃO DE ÍNDICES ESPECTRAIS NA ESTIMATIVA DE BIOMASSA E CARBONO EM FLORESTAS DE Eucalyptus Grandis: UM ESTUDO DE CASO COM NDVI E CO2FLUX  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402923578
:TOPICS: Estimation of Forest Biomass and Carbon Stocks, Utilization of Forest Biomass for Various Applications
:PUBLICATION_DATE: 2024-09-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5016/geociencias.v43i3.18171")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402923578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402923578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402923578"))][Get cited by]]

OpenAlex: https://openalex.org/W4402923578 (Open access: False)
    
[[https://openalex.org/A5046556745][Sidnei Fonseca Guerreiro]], [[https://openalex.org/A5019441487][Rosane Maria Kaspary]], [[https://openalex.org/A5007065062][Flávia Luize Pereira de Souza]], [[https://openalex.org/A5086539847][Martha Santana Martins]], [[https://openalex.org/A5070658612][V. Campos]], [[https://openalex.org/A5046556745][Sidnei Fonseca Guerreiro]], Geociências. 43(3)] 2024. https://doi.org/10.5016/geociencias.v43i3.18171 
     
RESUMO - As florestas plantadas são alternativas para redução dos gases de efeito estufa, pelo acúmulo de biomassa em sua estrutura no ciclo do carbono e pelo serviço ambiental prestado no sequestro do gás, que necessita ser estimado por meio de tecnologias que possam medir sua eficiência e estoque. Este trabalho tem o propósito de estimar os valores de dois índices espectrais (NDVI e CO2Flux), com dados de biomassa em floresta plantada da espécie Eucalyptus grandis. Adotou-se três cenas do satélite Landsat-8 da órbita/ponto 221/076 com resolução espacial de 30 metros. Os pontos amostrais foram obtidos através do Inventário Florestal ocorridos em dezembro de 2016, em uma área total de 2050 ha, contabilizando 119.498 indivíduos arbóreos em seis fazendas instaladas entre os municípios de Borebi e Iaras no estado de São Paulo, pertencentes a empresa Lwarcel Celulose. Os resultados apresentaram os valores de escala alto dos índices NDVI e CO2Flux, para o NDVI valores próximos a 1 indicam vegetação densa e saudável, como os talhões de reflorestamento objeto de estudo, já os valores altos de CO2Flux indica que a vegetação está absorvendo mais CO2 do que está liberando, o que é positivo para o sequestro de carbono. O estudo demonstra a viabilidade de adoção dos índices para análises completa dos dados, agregando e integrando o modelo de inventário florestal difundido pelo IPCC com os de sensoriamento remoto para avaliação dinâmica do setor florestal. Palavras-chave: NDVI. CO2Flux. Sensoriamento Remoto. Eucalipto. ABSTRACT - Planted forests offer alternatives for reducing greenhouse gases by accumulating biomass in their structure in the carbon cycle and providing the environmental service of carbon sequestration. This reduction needs to be estimated using technologies that can measure the efficiency of these forests and the carbon stock they contain. The purpose of this study was to estimate the values of two spectral indices (NDVI and CO2Flux), using biomass data from a planted forest of Eucalyptus grandis. Three Landsat-8 satellite images taken at orbit/point 221/076 with a spatial resolution of 30 meters were used. The sample points were obtained from a forest inventory conducted in December 2016, covering a total area of 2050 ha, which contained 119,498 trees on six farms located between the municipalities of Borebi and Iaras in the state of São Paulo, belonging to the company Lwarcel Celulose. The results showed high NDVI and CO2Flux indices. NDVI values close to 1 indicate dense, healthy vegetation, such as the reforestation area under study, while high CO2Flux values indicate that the vegetation is absorbing more CO2 than it is releasing, which is positive for carbon sequestration. The study demonstrates the feasibility of adopting the indices for complete data analysis, aggregating and integrating the forest inventory model disseminated by the IPCC with remote sensing for a dynamic assessment of the forestry sector. Keywords: NDVI. CO2Flux. Remote Sensing. Eucalyptus.    

    

* Making of an Indigenous and Efficient Powertrains for EV, HEV & FCEV’s  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403077243
:TOPICS: Integration of Electric Vehicles in Power Systems, State of the Art in Electric and Hybrid Vehicles, Lithium-ion Battery Management in Electric Vehicles
:PUBLICATION_DATE: 2024-08-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.37285/ajmt.4.3.0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403077243"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403077243"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403077243"))][Get cited by]]

OpenAlex: https://openalex.org/W4403077243 (Open access: False)
    
[[https://openalex.org/A5000757204][S. S. Ramdasi]], ARAI Journal of Mobility Technology. 4(3)] 2024. https://doi.org/10.37285/ajmt.4.3.0 
     
Rise in greenhouse gas emissions which is resulting into ozone layer depletion and global warming effect is alarming to control CO2 emissions by drastically reducing fossil fuel consumption from the vehicles. This need has already started trend towards extreme downsizing and down speeding of Internal Combustion Engines (ICE) for making them highly efficient. In addition to this use of after treatment devices viz. Diesel Oxidation Catalyst (DOC), Diesel Particulate Filter (DPF), Lean NOx Catalyst (LNT), Selective Catalytic Reduction (SCR) are helping to a great extent for meeting emission norms till Euro - VI for automotive sector, Tier–IV F and Stage V for Off Highway Power sector. However, to address present greenhouse effect along with exponential decay of fossil fuels, there is need to achieve CO2 emissions less than 100 g/km or to achieve practically zero carbon footprint using an alternate powertrain. Electrification is one of the promising solutions and which is three-fold in present situation. The first level of electrification comes in the form of Hybrid Electric Vehicle (HEV) technology followed by Battery Electric Vehicles and Fuel Cell Electric Vehicles as second and third level of electrification respectively. In all these technologies a common thread is running in the form of an efficient electric drive train. Several efforts have been taken to improve torque per unit ampere by use of efficient motor and motor control algorithms viz PMSM powered with FOC, by developing controls which take care of parametric variations and external force disturbances by use of back stepping techniques which are based on rotor resistance estimation by fuzzy logic, FOC techniques based on adaptive input-output feedback linearization, by shifting towards high voltage systems, by going for higher switching frequencies for inverters which uses silicon carbide based MOSFET switches, by exploring use of multilevel inverters for Total Harmonic Distortion (THD) control etc. Use of E Axle based powertrains in EV, HEV and FCEV offers additional complimentary benefits apart from technology options described above. E Axle based powertrains offers flexibility in generating three variants of vehicle using one electric drive train architecture viz. making EV, HEV & FCEV. Compactness, modularity, scalability, flexibility along with efficient cooling system management and control over active current losses due to use of bus bars are the implicit advantages of E Axle based powertrains. These advantages further get multiplies if we go for 3 in 1 (gearbox + Stator housing + Inverter) architectures which are predominantly used in independent suspension-based vehicles. Lot of efforts are going on to inherit this technology for rigid axle suspension based commercial vehicles. Research in this area is getting further extended to make 5 in 1 E Axles where there will addition of DC - DC converter and On-Board Charger (OBC) apart from components present in 3 in 1 configuration. Two major challenges need to be addressed and to be resolved while designing E Axle based powertrains by doing concurrent vehicle engineering. This is mainly due to increased unsprang weight that need to be handled by suspension system and exposed electric drive components to excitation loads coming from roads. Fig: Indigenously Developed E Axle Based Powertrain for Small Commercial VehiclesBy proper lay outing for effective vehicle mass distribution and required CG location which is essential from overall vehicle dynamics, more space can be offered by E Axle based powertrains for increasing battery energy density for getting more electric range in case of BEV’s. This add on space benefit extend help in packaging of hydrogen fuel cell integrated with power cells in case of FCEV’s. Thus, E Axle based powertrains proves to be modern and most efficient way of making EV, HEV & FCEV’s.    

    

* Comments: Global Implications and Challenges of Electrification  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402970937
:TOPICS: Indoor Air Pollution in Developing Countries
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2118/1024-0014-jpt")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402970937"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402970937"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402970937"))][Get cited by]]

OpenAlex: https://openalex.org/W4402970937 (Open access: False)
    
[[https://openalex.org/A5069367188][Pam Boschee]], Journal of Petroleum Technology. 76(10)] 2024. https://doi.org/10.2118/1024-0014-jpt 
     
_ Electrification is widely seen as crucial for decarbonization. To be successful on a global scale, a mix of complex challenges require coordinated efforts across the diversification of the energy mix, technology development, infrastructure investment, policy support, and regional planning. The International Energy Agency’s (IEA) Net Zero Emissions by 2050 Scenario suggests electricity should account for nearly 30% of final energy consumption by 2030, up from an estimated 20% in 2023, to progress to net zero. Are net zero emissions achievable by 2050? SPE President Olivier Houzé delves into the IEA’s three main energy transition scenarios in this month’s vodcast and column. Among his conclusions: “Beyond 2050, the anticipation is a decline of around 50% for oil and 25% for gas in the following 20 years. The one thing everybody agrees on is that no one really knows.” The following updates offer a glimpse at efforts to electrify oil and gas assets and bring clean energy solutions to remote and underserved communities. Norway’s Offshore Success Electrifying upstream oil and gas production facilities using renewable energy or otherwise flared natural gas could reduce emissions by more than 80%. Rystad Energy’s recent analysis highlighted Norway as currently leading the way, thanks to its wealth of renewable resources and production sites’ proximity to them. Electrification of rigs and other assets on Norway’s Continental Shelf (NCS) has resulted in a drop from 8.4 kg to 1.2 kg CO2/BOE—an 86% reduction in the same assets’ emissions before electrification. Norway’s literal powerhouse is hydroelectric energy, tallying more than 1,500 hydropower plants, normally producing 133 TWh annually, or 96% of the country’s total power production. This supply has made the transition of many of its offshore facilities to cleaner energy more feasible than in other regions of the world, particularly for power-from-shore projects such as Troll A, Martin Linge, and Johan Sverdrup. As of 2 years ago, Norway had seven fields fully or partially electrified from shore. Onshore Electrification—Drilling With Clean(er) Energy Other players in the industry grapple with less advantageous scenarios, facing hurdles such as facilities located far from renewable energy sources, which may be limited, and inadequate grid infrastructure. SPE 218649, presented at the SPE Conference at Oman Petroleum & Energy Show in April, discussed using electrical utility power in drilling operations. The authors noted that a drilling rig typically consumes 6 to 50 MWh of energy per day, averaging around 20 MWh. Diesel-powered rigs emit about 1.0 metric tonne of CO2e/MWh, totaling roughly 20 metric tonnes of CO2e per day. In contrast, grid-powered rigs emit about 0.39 metric tonnes of CO2e/MWh, less than half the emissions of diesel-powered rigs. An example from the paper illustrates how incremental changes can reduce emissions intensity, even when the solution is a step toward “cleaner” energy, though not yet fully aligned with ideal clean energy standards. Comparing drilling operations in North Dakota, where 57% of the state’s power generation uses coal, to Texas where 18% uses coal, the authors noted that the “emissions intensity on a North Dakota rig tied to the grid is higher than that of an electrified rig working in Texas but is still notably lower than the intensity of an average drilling rig powered by a diesel generator, which is approximately 1.0 metric tonnes CO2e/MWh.” Broader Implications and Challenges of Electrification The upfront costs of electrification are substantial, especially for entities in remote areas with limited grid access. This challenge affects not only the oil and gas industry but also efforts to bring electricity to underserved communities. A paper presented at the SPE Nigeria Annual International Conference and Exhibition in August (SPE 221709) studied the viability and impact of solar mini-grid systems for electrification of rural communities in Sub-Saharan Africa where approximately 600 million people lack electricity, and around 690 million lack access to clean cooking stoves. The authors wrote, “In Nigeria, about 45% of the population, more than 90 million people, do not have electricity, with 60% of these individuals residing in rural areas. Nigeria also has one of the lowest per capita electricity generation rates globally, with an installed grid-connected capacity of about 13,000 MW but an average actual output of just 4,000 MW.” The authors included a table showing a cost summary including capital, the cost of installation, and other specifications for an 87.5-kWp (kilowatt peak) solar-power system. They calculated a levelized cost of electricity of 47.1 cents/kWh over the system’s estimated lifetime of 25 years—approximately six times that of a US residential solar system and roughly three times more than an average US residential utility rate of 16 cents/kWh (although this varies significantly by state and region). In the end, achieving a more electrified and sustainable energy future depends on a combination of factors: strategic investment, robust infrastructure, accessible energy resources, collaboration among key stakeholders, ongoing technological innovation, and supportive policy frameworks.    

    
