#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Thu Aug  1 01:17:21 2024

Found 63 results from 2024-07-25 to 2024-08-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Highly dispersed atomic-level Ni active sites confined in defects for efficient electrocatalytic reduction of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400948919
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.07.018")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400948919"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400948919"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400948919"))][Get cited by]]

OpenAlex: https://openalex.org/W4400948919 (Open access: False)
    
[[https://openalex.org/A5100447803][Wenjun Zhang]], [[https://openalex.org/A5062912950][Zhao Chen]], [[https://openalex.org/A5100397372][Yang Yang]], [[https://openalex.org/A5036966752][Ruotong Chen]], [[https://openalex.org/A5100625845][Yue Wu]], [[https://openalex.org/A5078014774][Jiaqi Dai]], [[https://openalex.org/A5100607873][Yuxing Zhang]], [[https://openalex.org/A5101397363][Huajie Liu]], [[https://openalex.org/A5100443412][Mingyang Liu]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.07.018 
     
No abstract    

    

* Research Progress on Electrocatalysts for Electrocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400959287
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/e3sconf/202455301005")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400959287"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400959287"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400959287"))][Get cited by]]

OpenAlex: https://openalex.org/W4400959287 (Open access: True)
    
[[https://openalex.org/A5057062760][Yongping Liao]], E3S Web of Conferences. 553(None)] 2024. https://doi.org/10.1051/e3sconf/202455301005 
     
Electrochemical CO2 reduction reaction (CO2RR) is a vital strategy for achieving carbon neutrality by converting CO2 into high-energy-density, valuable chemical products, thereby facilitating carbon resource recycling and addressing environmental challenges. Herein, this paper emphasizes the role of CO2RR in diminishing the greenhouse effect through the transformation of CO2, with a particular focus on the latest advancements in Cu-based nanocatalysts, metal-organic framework (MOF)-based catalysts, and heteroatom-doped carbon materials, which are key innovations in achieving enhanced photoelectric conversion efficiency and steering CO2 conversion pathways. The paper also outlines the electrochemical principles of CO2RR, and the spectrum of potential reduction products, and navigates through the challenges of stability and production costs. The paper proposes strategies to surmount these hurdles, highlighting the critical role of industrial collaborations and breakthroughs in materials science. Future research should aim to pinpoint cost-effective, efficient catalysts for CO2RR, contributing significantly to mitigating the greenhouse effect and propelling forward sustainable energy solutions.    

    

* Origin of Carbon Monoxide Formation in the Oxidative Dehydrogenation of Propane Using Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400982774
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Mesoporous Materials
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02628")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400982774"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400982774"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400982774"))][Get cited by]]

OpenAlex: https://openalex.org/W4400982774 (Open access: True)
    
[[https://openalex.org/A5090923288][James Carter]], [[https://openalex.org/A5049203228][Tongqi Ye]], [[https://openalex.org/A5056229798][Daniel G. Hewes]], [[https://openalex.org/A5105065349][Ahlam Almoteiry]], [[https://openalex.org/A5059168773][Kieran J. Aggett]], [[https://openalex.org/A5014755874][Bart D. Vandegehuchte]], [[https://openalex.org/A5051694258][Qian He]], [[https://openalex.org/A5029440147][Stuart H. Taylor]], [[https://openalex.org/A5020068159][Graham J. Hutchings]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02628 
     
No abstract    

    

* Amorphous Nanomaterials: Emerging Catalysts for Electrochemical Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400991715
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202402424")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400991715"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400991715"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400991715"))][Get cited by]]

OpenAlex: https://openalex.org/W4400991715 (Open access: False)
    
[[https://openalex.org/A5040391460][Miaomiao Tan]], [[https://openalex.org/A5009468452][Biao Huang]], [[https://openalex.org/A5062006962][Lina Su]], [[https://openalex.org/A5091712567][Xiaojin Jiao]], [[https://openalex.org/A5101313304][Fukai Feng]], [[https://openalex.org/A5101906993][Yixuan Gao]], [[https://openalex.org/A5064121761][Qianli Huang]], [[https://openalex.org/A5103191012][Zhiqi Huang]], [[https://openalex.org/A5053762044][Yiyao Ge]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202402424 
     
Abstract In the past decades, the rapid depletion of non‐renewable energy sources has caused growing energy crisis and increasing emissions of carbon dioxide (CO 2 ), which aggravates global warming and catastrophic climate change. Electrocatalysis is regarded as an effective method for consuming atmospheric CO 2 and simultaneously alleviating the energy problem by converting CO 2 into high value‐added chemicals. Amorphous nanomaterials with long‐range disordered structures possess abundant highly unsaturated atomic sites and dangling bonds on their surfaces, thus providing a large number of active sites, and show unique electronic structures compared to their crystalline counterparts due to the distinct atomic arrangements. Therefore, amorphous nanomaterials are recently demonstrated as highly efficient catalysts for diverse electrocatalytic reactions, including electrocatalytic CO 2 reduction reaction (CO 2 RR). Here the rational synthesis and electrocatalytic performance of newly emerging amorphous nanomaterials will be outlined for electrocatalytic CO 2 RR. Importantly, the intrinsic merits of these amorphous catalysts in CO 2 RR processes will be summarized and highlighted. Finally, these perspectives on the remaining challenges and some potential future directions in this emerging field will also be provided.    

    

* Carbon monoxide synthesis from carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401012803
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Hydrogen Energy Systems and Technologies, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/b978-0-443-19235-7.00006-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401012803"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401012803"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401012803"))][Get cited by]]

OpenAlex: https://openalex.org/W4401012803 (Open access: False)
    
[[https://openalex.org/A5022042020][D. Santos]], [[https://openalex.org/A5017625619][Alexandre Mendonça Teixeira]], [[https://openalex.org/A5044740636][Stefano Ferrari Interlenghi]], [[https://openalex.org/A5059822653][Gabriel S. Bassani]], [[https://openalex.org/A5075269005][Rita M.B. Alves]], Elsevier eBooks. None(None)] 2024. https://doi.org/10.1016/b978-0-443-19235-7.00006-3 
     
No abstract    

    

* Three-dimensional reconstruction of porous CeO2 single crystal for effective electrolysis of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027649
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235088")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027649"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027649"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027649"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027649 (Open access: False)
    
[[https://openalex.org/A5050650726][Jiaming Ma]], [[https://openalex.org/A5010438441][Mengmeng Miao]], [[https://openalex.org/A5016445881][Kui Xie]], [[https://openalex.org/A5016445881][Kui Xie]], Journal of Power Sources. 615(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235088 
     
No abstract    

    

* Chapter 14 The sonochemical reduction of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400964498
:TOPICS: Applications of Ultrasound in Nanostructured Materials Synthesis
:PUBLICATION_DATE: 2024-07-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1515/9783111137940-014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400964498"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400964498"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400964498"))][Get cited by]]

OpenAlex: https://openalex.org/W4400964498 (Open access: False)
    
[[https://openalex.org/A5105022247][Kaouther Kerboua]], De Gruyter eBooks. None(None)] 2024. https://doi.org/10.1515/9783111137940-014 
     
This chapter tackles the topic of the sonochemical reduction of CO2, starting from the fundamentals of the process, that is, the acoustic cavitation bubble, its oscillation, its collapse, and the evolution toward the adequate conditions for CO2 reduction. It also sheds light on the chemical mechanism susceptible to emerge within the acoustic cavitation bubble to explain the reduction of CO2 and its eventual conversions. Most importantly, the chapter reports the major findings of research works retrieved in the literature and highlights the debate around the use of ultrasounds as a promising technique from CO2 reduction, by presenting the most plausible explanations of the sonochemical process of CO2 reduction, both in terms of possibilities and limitations.    

    

* Synergy of Tm-Based Dual-Atom Catalysts Supported by B,N-Doped Biphenylene for Carbon Dioxide Reduction Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027800
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4906500")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027800"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027800 (Open access: False)
    
[[https://openalex.org/A5014323700][Maryam Fallahzadeh]], [[https://openalex.org/A5068516261][Alireza Kokabi]], [[https://openalex.org/A5084449137][Zahra Nasiri]], [[https://openalex.org/A5088679046][Mina Fayazi]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4906500 
     
No abstract    

    

* How the nature of inequality reduction matters for CO2 emissions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400941659
:TOPICS: Rebound Effect on Energy Efficiency and Consumption, Economic Implications of Climate Change Policies, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4881463")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400941659"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400941659"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400941659"))][Get cited by]]

OpenAlex: https://openalex.org/W4400941659 (Open access: False)
    
[[https://openalex.org/A5064521283][T. S. Shiny Angel]], [[https://openalex.org/A5062478656][Alexandre Berthe]], [[https://openalex.org/A5006215387][Valeria Costantini]], [[https://openalex.org/A5003505386][Mariagrazia D’Angeli]], SSRN Electronic Journal. None(None)] 2024. https://doi.org/10.2139/ssrn.4881463 
     
No abstract    

    

* Surface Defects Induced Polarization Manipulation in Cu2SnS3 for Boosting Electrochemical CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401032296
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04092a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401032296"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401032296"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401032296"))][Get cited by]]

OpenAlex: https://openalex.org/W4401032296 (Open access: False)
    
[[https://openalex.org/A5100717474][Haihua Wang]], [[https://openalex.org/A5090340144][Wen Ning]], [[https://openalex.org/A5100334817][Yupeng Li]], [[https://openalex.org/A5047695454][Xiuling Jiao]], [[https://openalex.org/A5103244018][Yuguo Xia]], [[https://openalex.org/A5072207899][Dairong Chen]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta04092a 
     
Controlling the electrocatalyst's surface polarization is crucial for the interfacial CO2 electrolysis that takes place. Here, we propose an efficient way to increase the electrochemical reduction of CO2 to formate...    

    

* Engineering Strategies in Rational Design of Cu-Based Catalysts for Electrochemical CO2 Reduction: From Doping of Elements to Defects creation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401033694
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ma00321g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401033694"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401033694"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401033694"))][Get cited by]]

OpenAlex: https://openalex.org/W4401033694 (Open access: True)
    
[[https://openalex.org/A5006935349][Sheraz Yousaf]], [[https://openalex.org/A5074780725][Iqbal Ahmad]], [[https://openalex.org/A5089324736][Muhammad Farooq Warsi]], [[https://openalex.org/A5057878200][Asad Ali]], Materials Advances. None(None)] 2024. https://doi.org/10.1039/d4ma00321g 
     
The rational design of copper (Cu)-based catalysts for electrochemical carbon dioxide (CO2) reduction has garnered substantial attention due to its potential to mitigate climate change by converting CO2 into valuable...    

    

* Improved Production Rates of Hydrogen Generation and Carbon Dioxide Reduction Using Gallium Nitride with Nickel Oxide Nanofilm Capping Layer as Photoelectrodes for Photoelectrochemical Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027697
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsomega.4c03729")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027697"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027697"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027697"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027697 (Open access: True)
    
[[https://openalex.org/A5056478968][Chin Yin Sheu]], [[https://openalex.org/A5047589446][Shang-Ju Tu]], [[https://openalex.org/A5075283086][Shao‐Chi Chang]], ACS Omega. None(None)] 2024. https://doi.org/10.1021/acsomega.4c03729 
     
No abstract    

    

* Electronic perturbation of Cu nanowire surfaces with functionalized graphdiyne for enhanced CO2 reduction reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401008216
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/nsr/nwae253")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401008216"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401008216"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401008216"))][Get cited by]]

OpenAlex: https://openalex.org/W4401008216 (Open access: True)
    
[[https://openalex.org/A5037340591][Haiyuan Zou]], [[https://openalex.org/A5028424510][Dongfang Cheng]], [[https://openalex.org/A5010019518][Chao Tang]], [[https://openalex.org/A5079295506][Wen Luo]], [[https://openalex.org/A5079946479][Huatian Xiong]], [[https://openalex.org/A5074364344][Hui‐Fen Dong]], [[https://openalex.org/A5100373596][Fan Li]], [[https://openalex.org/A5029772385][Tao Song]], [[https://openalex.org/A5024686369][Sai Shu]], [[https://openalex.org/A5065585691][Hao Dai]], [[https://openalex.org/A5101273787][Ziang Cui]], [[https://openalex.org/A5027800643][Zhouguang Lu]], [[https://openalex.org/A5047901288][Lele Duan]], National Science Review. None(None)] 2024. https://doi.org/10.1093/nsr/nwae253 
     
Abstract Electronic perturbation of Cu catalysts surface is crucial for optimizing electrochemical CO2 reduction activity, yet still poses great challenges. Herein, nanostructured Cu nanowires (NW) with fine-tuned surface electronic structure are achieved via surface encapsulation with electron-withdrawing (–F) and -donating (–Me) group-functionalized graphdiynes (R-GDY, R = –F and –Me), and the resulting catalysts, denoted as R-GDY/Cu NW, display distinct CO2 reduction performances. In-situ electrochemical spectroscopy revealed that the *CO (a key intermediate of the CO2 reduction reaction) binding affinity and consequent *CO coverage positively correlate to the Cu surface oxidation state, leading to the favorable C–C coupling on F-GDY/Cu NW over Me-GDY/Cu NW. Electrochemical measurements corroborate the favorable C2H4 production with an optimum C2+ selectivity of 73.15% ± 2.5% observed for F-GDY/Cu NW, while the predominant CH4 production is favored by Me-GDY/Cu NW. Furthermore, leveraging the *Cu–OH/*CO ratio as a descriptor, mechanistic investigation reveals that the protonation of distinct adsorbed *CO facilitated by *Cu–OH is crucial for the selective generation of C2H4 and CH4 on F-GDY/Cu NW and Me-GDY/Cu NW, respectively.    

    

* Atomically dispersed Ru on Cu3N for electrocatalytic reduction of CO2 and nitrite to urea  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400942748
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.154256")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400942748"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400942748"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400942748"))][Get cited by]]

OpenAlex: https://openalex.org/W4400942748 (Open access: False)
    
[[https://openalex.org/A5100418976][Hongyan Zhao]], [[https://openalex.org/A5063107365][Zhuohang Li]], [[https://openalex.org/A5025335702][Jiaqi Xiang]], [[https://openalex.org/A5102034333][Wenyu Du]], [[https://openalex.org/A5033274823][Ke Chu]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.154256 
     
No abstract    

    

* Electrolyte Composition‐Dependent Product Selectivity in CO2 Reduction with a Porphyrinic Metal‐Organic Framework Catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401022814
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202411766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401022814"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401022814"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401022814"))][Get cited by]]

OpenAlex: https://openalex.org/W4401022814 (Open access: False)
    
[[https://openalex.org/A5089568090][Shiliang Pu]], [[https://openalex.org/A5025077602][Tao Huang]], [[https://openalex.org/A5035202372][Duan‐Hui Si]], [[https://openalex.org/A5079968989][Meng-Jiao Sun]], [[https://openalex.org/A5100768915][Wenwen Wang]], [[https://openalex.org/A5100372524][Teng Zhang]], [[https://openalex.org/A5027181760][Rong Cao]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202411766 
     
A copper porphyrin-derived metal-organic framework electrocatalyst, FICN-8, was synthesized and its catalytic activity for CO2 reduction reaction (CO2RR) was investigated. FICN-8 selectively catalyzed electrochemical reduction of CO2 to CO in anhydrous acetonitrile electrolyte. However, formic acid became the dominant CO2RR product with the addition of a proton source to the system. Mechanistic studies revealed the change of major reduction pathway upon proton source addition, while catalyst-bound hydride (*H) species was proposed as the key intermediate for formic acid production. This work highlights the importance of electrolyte composition on CO2RR product selectivity.    

    

* A REVIEW OF THE SYNTHESIS, CHARACTERIZATION, AND MECHANISM OF BIMETALLIC CATALYSTS FOR ELECTROCATALYTIC CO2 REDUCTION  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400937635
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.carbon.2024.119341")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400937635"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400937635"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400937635"))][Get cited by]]

OpenAlex: https://openalex.org/W4400937635 (Open access: False)
    
[[https://openalex.org/A5100597632][Yin-li Liao]], [[https://openalex.org/A5045080046][Heng-bo Huang]], [[https://openalex.org/A5102658226][Ru-yu Zou]], [[https://openalex.org/A5022544540][Shuling Shen]], [[https://openalex.org/A5001126288][Xin-juan Liu]], [[https://openalex.org/A5101636502][Zhihong Tang]], Carbon. 228(None)] 2024. https://doi.org/10.1016/j.carbon.2024.119341 
     
No abstract    

    

* Electrolyte Composition‐Dependent Product Selectivity in CO2 Reduction with a Porphyrinic Metal‐Organic Framework Catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401022535
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202411766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401022535"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401022535"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401022535"))][Get cited by]]

OpenAlex: https://openalex.org/W4401022535 (Open access: False)
    
[[https://openalex.org/A5089568090][Shiliang Pu]], [[https://openalex.org/A5025077602][Tao Huang]], [[https://openalex.org/A5035202372][Duan‐Hui Si]], [[https://openalex.org/A5079968989][Meng-Jiao Sun]], [[https://openalex.org/A5100768915][Wenwen Wang]], [[https://openalex.org/A5100372524][Teng Zhang]], [[https://openalex.org/A5027181760][Rong Cao]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202411766 
     
A copper porphyrin‐derived metal‐organic framework electrocatalyst, FICN‐8, was synthesized and its catalytic activity for CO2 reduction reaction (CO2RR) was investigated. FICN‐8 selectively catalyzed electrochemical reduction of CO2 to CO in anhydrous acetonitrile electrolyte. However, formic acid became the dominant CO2RR product with the addition of a proton source to the system. Mechanistic studies revealed the change of major reduction pathway upon proton source addition, while catalyst‐bound hydride (*H) species was proposed as the key intermediate for formic acid production. This work highlights the importance of electrolyte composition on CO2RR product selectivity.    

    

* Advanced progress in constructing carbon-coated metal materials for electrocatalytic CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400943666
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.175705")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400943666"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400943666"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400943666"))][Get cited by]]

OpenAlex: https://openalex.org/W4400943666 (Open access: False)
    
[[https://openalex.org/A5100597848][Qinyun Yan]], [[https://openalex.org/A5003202153][Wei Wen]], [[https://openalex.org/A5101124548][Lan Qiang]], [[https://openalex.org/A5100689892][Chunmei Liu]], [[https://openalex.org/A5013605837][Yang Gao]], [[https://openalex.org/A5071911528][Jiamin Ma]], [[https://openalex.org/A5005560656][Peipei Zhao]], [[https://openalex.org/A5009521836][He Xiao]], [[https://openalex.org/A5005014456][Junwei Wu]], [[https://openalex.org/A5019779253][Man Zhao]], [[https://openalex.org/A5089859351][Jianfeng Jia]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.175705 
     
No abstract    

    

* Zn-Cu Bimetallic Gas Diffusion Electrodes for Electrochemical Reduction of CO2 to Ethylene  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401007616
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144723")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401007616"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401007616"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401007616"))][Get cited by]]

OpenAlex: https://openalex.org/W4401007616 (Open access: False)
    
[[https://openalex.org/A5061145215][Munzir H. Suliman]], [[https://openalex.org/A5105370707][Hussain Al Naji]], [[https://openalex.org/A5090138718][Muhammad Usman]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144723 
     
No abstract    

    

* Pre-reduction of Nchwaning manganese ore in CO/CO2, H2/H2O, and H2 atmospheres  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401026636
:TOPICS: Reduction Kinetics in Ironmaking Processes, Biohydrometallurgical Processes for Metal Extraction, Thermochemical Software and Databases in Metallurgy
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mineng.2024.108854")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401026636"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401026636"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401026636"))][Get cited by]]

OpenAlex: https://openalex.org/W4401026636 (Open access: True)
    
[[https://openalex.org/A5086250478][Mathilde Ernst]], [[https://openalex.org/A5086748509][Merete Tangstad]], [[https://openalex.org/A5071118055][S.P. du Preez]], Minerals Engineering. 216(None)] 2024. https://doi.org/10.1016/j.mineng.2024.108854 
     
No abstract    

    

* Mechanism Investigation of Direct Electrochemical Reduction of Co2-Loaded 2-(Ethylamino)Ethanol Solution into Co  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400933626
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4904833")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400933626"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400933626"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400933626"))][Get cited by]]

OpenAlex: https://openalex.org/W4400933626 (Open access: False)
    
[[https://openalex.org/A5083506223][Ru‐Ping Dai]], [[https://openalex.org/A5100444043][Lijuan Zhang]], [[https://openalex.org/A5063565829][Khuyen Viet Bao Tran]], [[https://openalex.org/A5010443303][Suchada Sirisomboonchai]], [[https://openalex.org/A5079570169][Hiroshi Machida]], [[https://openalex.org/A5067993290][Koyo Norinaga]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4904833 
     
No abstract    

    

* Dual nanoparticles with rich Ni–CeO2 interfaces for efficient photothermal catalytic CO2 reduction by CH4  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400960353
:TOPICS: Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.278")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400960353"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400960353"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400960353"))][Get cited by]]

OpenAlex: https://openalex.org/W4400960353 (Open access: False)
    
[[https://openalex.org/A5032035216][Guanrui Ji]], [[https://openalex.org/A5101416147][Lingxin Meng]], [[https://openalex.org/A5103047994][Qian Gong]], [[https://openalex.org/A5046151830][Ying-Lian Jia]], [[https://openalex.org/A5054075598][Shaowen Wu]], [[https://openalex.org/A5052752750][Qian Zhang]], [[https://openalex.org/A5004877274][Jian Tian]], International Journal of Hydrogen Energy. 81(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.278 
     
No abstract    

    

* Greening the ironmaking industry: Biomass fuel reduces CO2 emissions and enhances iron ore reduction efficiency  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400940259
:TOPICS: Reduction Kinetics in Ironmaking Processes, Underground Coal Gasification: Fundamentals and Applications, Biohydrometallurgical Processes for Metal Extraction
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0218066")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400940259"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400940259"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400940259"))][Get cited by]]

OpenAlex: https://openalex.org/W4400940259 (Open access: False)
    
[[https://openalex.org/A5036320552][Ariany Zulkania]], [[https://openalex.org/A5059929096][Muslikhin Hidayat]], [[https://openalex.org/A5045858399][Rochmadi Rochmadi]], [[https://openalex.org/A5001067825][Rochim Bakti Cahyono]], AIP conference proceedings. None(None)] 2024. https://doi.org/10.1063/5.0218066 
     
No abstract    

    

* MXene quantum dots decorated g-C3N4/BiOI heterojunction photocatalyst for efficient NO deep oxidation and CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401022868
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.128961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401022868"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401022868"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401022868"))][Get cited by]]

OpenAlex: https://openalex.org/W4401022868 (Open access: False)
    
[[https://openalex.org/A5058882524][Junli Nie]], [[https://openalex.org/A5060770482][Xingmao Zhang]], [[https://openalex.org/A5014907619][Ming‐Sheng Wang]], [[https://openalex.org/A5070431364][Yucheng Ou]], [[https://openalex.org/A5009555060][Shiping Li]], [[https://openalex.org/A5052832631][Peng Zhong]], [[https://openalex.org/A5100333147][Weiwei Wang]], [[https://openalex.org/A5008523475][Gangqiang Zhu]], [[https://openalex.org/A5100321027][Xiaohua Ma]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.128961 
     
No abstract    

    

* Charge transfer regulates electrocatalytic CO2 reduction on one-dimensional carbon nanotube/boron nitride nanotube heterostructures  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401022912
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Thermoelectric Materials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.128981")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401022912"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401022912"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401022912"))][Get cited by]]

OpenAlex: https://openalex.org/W4401022912 (Open access: False)
    
[[https://openalex.org/A5033673698][Qigang Chen]], [[https://openalex.org/A5003167045][Yang Huohai]], [[https://openalex.org/A5100396067][Peng Wang]], [[https://openalex.org/A5020862263][Qiang Ke]], [[https://openalex.org/A5063446819][Xingbo Ge]], [[https://openalex.org/A5024977426][Xin Chen]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.128981 
     
No abstract    

    

* N,S co-doped SnO2 catalysts in gas-liquid interface dielectric barrier discharge for formate formation via CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400953638
:TOPICS: Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels, Applications of Plasma in Medicine and Biology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124446")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400953638"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400953638"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400953638"))][Get cited by]]

OpenAlex: https://openalex.org/W4400953638 (Open access: False)
    
[[https://openalex.org/A5100388270][Yi Zhang]], [[https://openalex.org/A5025636922][Fangying Li]], [[https://openalex.org/A5084157854][Shiying Yang]], [[https://openalex.org/A5026242179][Yupei Long]], [[https://openalex.org/A5053509144][Yiping Shen]], [[https://openalex.org/A5076384717][Fuqiang Huang]], [[https://openalex.org/A5047087548][Jiani Lu]], [[https://openalex.org/A5047700095][Yanqing Cong]], [[https://openalex.org/A5078986449][Boqiong Jiang]], [[https://openalex.org/A5100611004][Yuhai Sun]], Applied Catalysis B Environment and Energy. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124446 
     
No abstract    

    

* In Situ Studies of Cu Catalyzed CO2 Electro-Reduction by Soft X-ray Scanning Transmission X-ray Microscopy and Soft X-ray Spectro-Ptychography  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401000088
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/mam/ozae044.855")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401000088"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401000088"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401000088"))][Get cited by]]

OpenAlex: https://openalex.org/W4401000088 (Open access: False)
    
[[https://openalex.org/A5053413006][Adam P. Hitchcock]], [[https://openalex.org/A5063184743][Chunyang Zhang]], [[https://openalex.org/A5042189271][Haytham Eraky]], [[https://openalex.org/A5044827415][Drew Higgins]], Microscopy and Microanalysis. 30(Supplement_1)] 2024. https://doi.org/10.1093/mam/ozae044.855 
     
No abstract    

    

* Sr(Ti0·3Fe0.7)O3−δ-based perovskite with in-situ exsolved Fe–Ru nanoparticles: A highly stable fuel electrode material for solid oxide electrochemical cells with efficient electrocatalytic CO2 reduction ability and preferential selectivity  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027580
:TOPICS: Solid Oxide Fuel Cells, Chemical-Looping Technologies, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235087")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027580"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027580"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027580"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027580 (Open access: False)
    
[[https://openalex.org/A5005161657][Fang-Ze Han]], [[https://openalex.org/A5010211660][Yongshan Wan]], [[https://openalex.org/A5087020669][Cheng‐Xin Li]], [[https://openalex.org/A5042561898][Shan-Lin Zhang]], Journal of Power Sources. 615(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235087 
     
No abstract    

    

* Alkali-promoted indium oxide as highly active and selective catalyst for the photo-thermal CO2 hydrogenation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401025425
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04387a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401025425"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401025425"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401025425"))][Get cited by]]

OpenAlex: https://openalex.org/W4401025425 (Open access: True)
    
[[https://openalex.org/A5052460109][Xiupeng Wang]], [[https://openalex.org/A5079894139][Alejandra Rendón‐Patiño]], [[https://openalex.org/A5077388484][Jean Marcel R. Gallo]], [[https://openalex.org/A5047085423][Diego Mateo]], [[https://openalex.org/A5058113997][Jorge Gascón]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta04387a 
     
Photo-thermal carbon dioxide (CO2) reduction has recently gained significant attention as a strategy to harness solar energy and address environmental challenges. Among other photo-thermal catalysts, indium oxide (In2O3) has emerged...    

    

* An Analysis of Greenhouse Gas Emissions in Electrolysis for Certifying Clean Hydrogen  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401015106
:TOPICS: Hydrogen Energy Systems and Technologies, Ammonia Synthesis and Electrocatalysis, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17153698")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401015106"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401015106"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401015106"))][Get cited by]]

OpenAlex: https://openalex.org/W4401015106 (Open access: True)
    
[[https://openalex.org/A5059901009][Yunji Kim]], [[https://openalex.org/A5015586692][In Ki Min]], [[https://openalex.org/A5100347348][Ji Eun Lee]], [[https://openalex.org/A5076975762][Heena Yang]], Energies. 17(15)] 2024. https://doi.org/10.3390/en17153698 
     
The drive for carbon neutrality has led to legislative measures targeting reduced greenhouse gas emissions across the transportation, construction, and industry sectors. Renewable energy sources, especially solar and wind power, play a pivotal role in this transition. However, their intermittent nature necessitates effective storage solutions. Green hydrogen and ammonia have gained attention for their potential to store renewable energy while producing minimal emissions. Despite their theoretical promise of zero greenhouse gas emissions during production, real-world emissions vary based on system configurations and lifecycle assessments, highlighting the need for detailed evaluations of their environmental impact. Therefore, in this study, calculations were performed for the actual amount of produced greenhouse gas emissions that are associated with the production of green hydrogen using electrolysis, from raw material extraction and processing to hydrogen production, with these assessed from well-to-gate emission estimates. Emissions were also evaluated based on various types of renewable energy sources in South Korea, as well as hydrogen production volumes, capacities, and types. Using these data, the following factors were examined in this study: carbon dioxide emissions from the manufacturing stage of electrolysis equipment production, the correlation between materials and carbon dioxide emissions, and process emissions. Current grades of clean hydrogen were verified, and the greenhouse gas reduction effects of green hydrogen were confirmed. These findings are significant against the backdrop of a country such as South Korea, where the proportion of renewable energy in total electricity production is very low at 5.51%. Based on the domestic greenhouse gas emission efficiency standard of 55 kWh/kgH2, it was found that producing 1 kg of hydrogen emits 0.076 kg of carbon dioxide for hydropower, 0.283 kg for wind power, and 0.924 kg for solar power. The carbon dioxide emissions for AWE and PEM stacks were 8434 kg CO2 and 3695 kg CO2, respectively, demonstrating that an alkaline water electrolysis (AWE) system emits about 2.3 times more greenhouse gasses than a proton exchange membrane (PEM) system. This indicates that the total carbon dioxide emissions of green hydrogen are significantly influenced by the type of renewable energy and the type of electrolysis used.    

    

* Mitigating Built Environment Air Pollution by Green Systems: An In-Depth Review  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400981343
:TOPICS: Health Effects of Air Pollution, Estimating Vehicle Fuel Consumption and Emissions, Low-Cost Air Quality Monitoring Systems
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/app14156487")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400981343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400981343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400981343"))][Get cited by]]

OpenAlex: https://openalex.org/W4400981343 (Open access: True)
    
[[https://openalex.org/A5099594090][Serena Vitaliano]], [[https://openalex.org/A5072842540][Stefano Cascone]], [[https://openalex.org/A5083532106][Provvidenza Rita D’Urso]], Applied Sciences. 14(15)] 2024. https://doi.org/10.3390/app14156487 
     
Air pollution is a critical issue impacting urban environments, leading to severe health problems and environmental degradation. This comprehensive review examines the potential of green systems—specifically green walls, active green walls, and urban greenery systems—to mitigate atmospheric pollutants such as particulate matter (PM), volatile organic compounds (VOCs), and carbon dioxide (CO2). By systematically analyzing 44 recent studies, this review highlights the pollutant capture efficiency of various green technologies and plant species in both indoor and outdoor settings. Active green walls, particularly those utilizing plant species such as Chlorophytum comosum and Sansevieria trifasciata, were found to be highly effective, with VOC reduction efficiencies of up to 96.34%, PM reductions of 65.42%, and CO2 reduction rates reaching 4.8% under optimal conditions. This review identifies key strengths in current research, including diverse experimental setups and the use of sophisticated measurement techniques, but also notes significant limitations such as variability in experimental conditions and a lack of long-term performance data. This study underscores the importance of proper maintenance to sustain green systems’ efficacy and highlights the potential issue of pollutant resuspension, which remains under-researched. Practical implications for urban planning are discussed, advocating for the integration of effective green systems into urban infrastructure to enhance air quality and public health. Recommendations for future research include the need for standardized metrics, long-term studies, economic feasibility analyses, and real-world validation of simulation models to better understand and optimize green systems for urban air pollution mitigation.    

    

* Research progress in home energy management systems consideration of comfort  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401032867
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization, Demand Response in Smart Grids
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54254/2755-2721/70/20240995")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401032867"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401032867"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401032867"))][Get cited by]]

OpenAlex: https://openalex.org/W4401032867 (Open access: False)
    
[[https://openalex.org/A5011353807][R. H. Yuan]], Applied and Computational Engineering. 70(1)] 2024. https://doi.org/10.54254/2755-2721/70/20240995 
     
According to statistics, the carbon dioxide emissions from Chinas power industry account for about 40% of the total energy consumption and carbon dioxide emissions, while residential electricity consumption accounts for 36.6% of the total social electricity consumption. However, ordinary households have low electricity efficiency and serious waste. In the context of the national strategy of carbon peak and carbon neutrality, the Home Energy Management System (HEMS) has been introduced to improve household electricity efficiency, reduce electricity consumption, and achieve energy conservation and emission reduction while ensuring the comfort of residents. This article introduces the current research status of home energy management systems that take into account user comfort, and shows some optimization models for home energy management systems that take into account user comfort. It specifically elaborates on the optimization models for household appliances and comfort, briefly outlines the relatively trendy load prediction and scheduling optimization models, and proposes some suggestions and prospects for popularizing knowledge related to home energy management systems for family members using smart homes and temperature comfort modeling based on the current development status.    

    

* The Effect of Additives on Microcellular PVC Foams: Part 1 - Effect on Processing and Microstructure  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400989097
:TOPICS: Polymer Foaming with Supercritical Carbon Dioxide, Poly(vinyl chloride) Plasticizers and Stabilizers, Colloidal Particles in Complex Systems
:PUBLICATION_DATE: 1998-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1177/0262489319981704003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400989097"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400989097"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400989097"))][Get cited by]]

OpenAlex: https://openalex.org/W4400989097 (Open access: False)
    
[[https://openalex.org/A5071323218][Mark R. Holl]], [[https://openalex.org/A5031608682][Mingliang Ma]], [[https://openalex.org/A5072720747][Vipin Kumar]], [[https://openalex.org/A5099106872][Robert R. Kwapisz]], Cellular Polymers. 17(4)] 1998. https://doi.org/10.1177/0262489319981704003 
     
The effect of the presence of commonly used additives on the processing and structure of microcellular PVC foams was investigated. It was found that the presence of additives leads to a polydisperse cell structure with large variations in cell sizes. The solubility of carbon dioxide in the additives and in the lubricants was found to be lower than in the PVC matrix. The presence of additives showed no adverse effect on the overall foam growth dynamics. It appears that target reductions in density of PVC can be achieved at lower processing temperatures when additives and processing aids are present.    

    

* Carbon reduction options for churches using oil for heating  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400989593
:TOPICS: Influence of Religion on Environmental Concern and Activism
:PUBLICATION_DATE: 2023-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.69554/ksqv2514")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400989593"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400989593"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400989593"))][Get cited by]]

OpenAlex: https://openalex.org/W4400989593 (Open access: False)
    
[[https://openalex.org/A5036358951][Donald E McNaughton]], No host. None(None)] 2023. https://doi.org/10.69554/ksqv2514 
     
To limit global warming, a rapid reduction in the carbon emissions from our buildings is required. Heating buildings contributed to 17 per cent of the UK overall carbon emissions in 2018 which is why it is important we look to decarbonise the heating systems that serve our buildings. In 2020, only 7.9 per cent of the energy to heat our buildings came from renewable sources. In the UK, existing heating is predominantly by natural gas. The most significant challenge is the rural buildings that are not served by mains gas but have oil supplies, due to the high carbon content of this fuel. The Diocese of Gloucester was invited to participate in a research project carried out by Historic England into viable methods of low and zero carbon heating in churches and their associated buildings. The focus of this research explores oil-fired heating systems as this fuel produces more carbon dioxide emissions than other fuels used to heat buildings. The key finding from this research is that no single heating technology is recommended for either all historic buildings or even each historic building type. Across the six case studies, air source heat pumps, biomass and electric heating were recommended in an equal proportion of cases. It is not possible to determine the most viable heating technology without carrying out a detailed technical feasibility study at the early concept stage of a project. The recommended heating technology depends on many factors including the building’s site and location, the size and form of the buildings, the use and operation of the buildings, the condition of the existing heating system and the existing utility infrastructure. The wider background to this research includes the 2030 net zero carbon target set by the Church of England and the UK government’s 2050 net zero carbon target.    

    

* Pathways and Reflections on ESG and Carbon Neutral Realization  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400960652
:TOPICS: Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.61360/bonighss242016490605")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400960652"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400960652"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400960652"))][Get cited by]]

OpenAlex: https://openalex.org/W4400960652 (Open access: False)
    
[[https://openalex.org/A5057096116][Zhaozhao Lv]], [[https://openalex.org/A5100425970][Qian Ma]], Global Humanities and Social Sciences. 5(6)] 2024. https://doi.org/10.61360/bonighss242016490605 
     
With the acceleration of industrialization, the massive use of fossil fuels has led to a sharp increase in the emission of greenhouse gases (GHGs) such as carbon dioxide, triggering a series of environmental problems such as rising global temperatures, the frequency of extreme weather events and the degradation of ecosystems, which have had far-reaching impacts on the health of human societies, economic development, and natural ecosystems. To cope with this global problem, the international community has been actively seeking solutions. The 1997 Kyoto Protocol and the 2015 Paris Agreement have made clear the international commitment to reduce greenhouse gas emissions and emphasized the importance of controlling the rise in global average temperature. Carbon neutrality has become one of the key strategies to achieve the goals of these agreements, meaning reaching a net-zero goal for carbon emissions through emissions reduction and carbon offset activities. ESG (Environmental, Social, and Governance) practices reflect the social responsibility of corporations and governments, and by integrating ESG principles, all parties can reduce their carbon footprints more efficiently, improve resource efficiency, and achieve sustainable development. This paper will explore the intersection of ESG and carbon-neutral strategies, analyze the effectiveness of their implementation in different subjects, and put forward specific recommendations for achieving the global carbon-neutral goal.    

    

* Will Hydrogen Be a New Natural Gas? Hydrogen Integration in Natural Gas Grids  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400933334
:TOPICS: Hydrogen Energy Systems and Technologies, Integration of Renewable Energy Sources in Europe, Energy Supply and Security Issues for Developed Economies
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1146/annurev-chembioeng-100522-110306")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400933334"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400933334"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400933334"))][Get cited by]]

OpenAlex: https://openalex.org/W4400933334 (Open access: False)
    
[[https://openalex.org/A5069143489][Gerald Linke]], Annual Review of Chemical and Biomolecular Engineering. 15(1)] 2024. https://doi.org/10.1146/annurev-chembioeng-100522-110306 
     
Hydrogen is similar to natural gas in terms of its physical and chemical properties but does not release carbon dioxide when burnt. This makes hydrogen an energy carrier of great importance in climate policy, especially as an enabler of increasing integration of volatile renewable energy, progressive electrification, and effective emission reductions in the hard-to-decarbonize sectors. Leaving aside the problems of transporting hydrogen as a liquid, technological challenges along the entire supply chain can be considered as solved in principle, as shown in the experimental findings of the Hydrogen Innovation Program of the German Technical and Scientific Association for Gas and Water. By scaling up production and end-use capacities and, most importantly, producing hydrogen in regions with abundant renewable energy, hydrogen and its applications can displace natural gas at affordable prices in the medium term. However, this substitution will take place at different rates in different regions and with different levels of added value, all of which must be understood for hydrogen uptake to be successful.    

    

* How to maintain environmental integrity when using state support and the VCM to co-finance BECCS projects - a Swedish case study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401038408
:TOPICS: Success Factors in Project Management, Sustainable Construction and Green Building, Life Cycle Costing in Construction and Infrastructure Projects
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/fenvs.2024.1387138")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401038408"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401038408"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401038408"))][Get cited by]]

OpenAlex: https://openalex.org/W4401038408 (Open access: True)
    
[[https://openalex.org/A5086304587][Mylène Dufour]], [[https://openalex.org/A5081022748][Kenneth Möllersten]], [[https://openalex.org/A5103516508][Lars Zetterberg]], Frontiers in Environmental Science. 12(None)] 2024. https://doi.org/10.3389/fenvs.2024.1387138 
     
Limiting global warming to close to 1.5°C by 2100 requires deep and rapid greenhouse gas emission reductions and carbon dioxide removals (CDR) on a massive scale, presenting a remarkable scaling challenge. This paper focuses on the financing of bioenergy with carbon capture and storage (BECCS) in Sweden. BECCS is one of the most prominent CDR methods in 1.5°C-compatible global emission scenarios and has been assigned a specific role in Swedish policy for net-zero. A Swedish state support system for BECCS based on results-based payments is planned. Furthermore, demand for CDR-based carbon credits is on the rise on the voluntary carbon markets (VCM) for use towards voluntary mitigation targets. Risks involved with the current Swedish policies are analysed, specifically for the co-financing of BECCS by the planned state support and revenues from the VCM. We find that with the current policies, state support systems will subsidise carbon credit prices on the VCM. We argue that such subsidisation can lower decarbonisation efforts by lowering the internal carbon price set by actors, thus undermining environmental integrity. It is concluded that proportional attribution should be applied, i.e., attributing mitigation outcomes to the state support and VCM revenue in proportion to their financial contribution to the CDR achieved. The attribution analysis should be accompanied by adjustments in national greenhouse gas accounting so that mitigation outcomes that are issued as carbon credits and used for offsetting are not double claimed (i.e., not used by both a nation and a non-state actor on the VCM towards their respective mitigation targets). If proportional attribution and adjustments in national GHG accounting are not implemented, the credibility and environmental integrity of offsetting claims made by carbon credit users are eroded. We recommend that action is taken to operationalise and implement proportional attribution to allow for co-financing of BECCS projects while maintaining environmental integrity. Wider implications for our recommendations beyond the case of Swedish BECCS are also analysed.    

    

* Spatial–Temporal Evolution and Driving Factors of Agricultural Green Development in China: Evidence from Panel Quantile Approaches  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400941569
:TOPICS: Economic Impact of Environmental Policies and Resources, Global Analysis of Ecosystem Services and Land Use, Discrete Choice Models in Economics and Health Care
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16156345")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400941569"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400941569"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400941569"))][Get cited by]]

OpenAlex: https://openalex.org/W4400941569 (Open access: True)
    
[[https://openalex.org/A5005482343][Fanghui Pan]], [[https://openalex.org/A5059517920][Haonan Deng]], [[https://openalex.org/A5054224705][Miao Chen]], [[https://openalex.org/A5101776552][Lijuan Zhao]], [[https://openalex.org/A5004633928][Wei Qian]], [[https://openalex.org/A5088098693][Xiangrong Wan]], Sustainability. 16(15)] 2024. https://doi.org/10.3390/su16156345 
     
Agricultural green development has become essential for sustainable agriculture and the reduction of carbon dioxide emissions. This study evaluates the total index of agricultural green development by applying the entropy method; it then examines the spatial–temporal evolution of agricultural green development and finally uses the panel quantile model to examine the driving factors of agricultural green development in China. The results indicate that the level of agricultural green development is rising with time, and the differences among the regions have not changed, showing an increasing direction from west to east. The results from the panel quantile regression with nonadditive fixed effects show that the driving factors have different impacts on agricultural green development across quantiles. Industrial structure upgrading, rural informatization, and agricultural marketization have more significant effects in provinces with higher agricultural green development; agricultural finance and the per capita GDP have greater impacts in provinces at a moderate level of agricultural green development; and technology development, rural informatization, and the urbanization rate play a more important role in provinces at a lower level of agricultural green development. Thus, each province should devise policies according to its level of agricultural green development, which would be beneficial in improving the policies’ effectiveness.    

    

* Retrofit assessment: Getting it right from the start  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400989752
:TOPICS: Quality and Practices in Nursing Home Care
:PUBLICATION_DATE: 2023-12-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.69554/zwvi1586")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400989752"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400989752"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400989752"))][Get cited by]]

OpenAlex: https://openalex.org/W4400989752 (Open access: False)
    
[[https://openalex.org/A5105082305][Richard Fitton]], [[https://openalex.org/A5076001888][William Swan]], No host. None(None)] 2023. https://doi.org/10.69554/zwvi1586 
     
The UK has some of the oldest buildings in Europe. They are also some of the worst performing in terms of energy performance. In tandem with these issues the UK has committed to making a substantial reduction in CO2 emissions. UK homes are currently responsible for almost 20 per cent of CO2 emissions. This leaves little option other than to make considerable progress with the retrofitting of homes to improve their energy performance. This is a technical process, however, and can introduce risks to building and their occupants. Examples exist of homes being retrofitted with disastrous consequences. Some of these issues can be due to the lack of thorough examination of a home before it undergoes a retrofit. This paper proposes a method that provides a detailed pre-retrofit assessment of a home, to fall in line with PAS 2035, a standard that provides guidance around publicly funded retrofit in the UK.    

    

* Supply chain as key driver for sustainability  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400992417
:TOPICS: Conceptualizing the Circular Economy and Sustainable Supply Chains, Developing Evidence-Informed Supply Chain Management Knowledge
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.69554/xmjp4140")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400992417"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400992417"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400992417"))][Get cited by]]

OpenAlex: https://openalex.org/W4400992417 (Open access: False)
    
[[https://openalex.org/A5058150988][Torsten Becker]], No host. None(None)] 2024. https://doi.org/10.69554/xmjp4140 
     
As the importance of sustainability is rising on the corporate agenda, companies need to provide environmental impact reduction plans to shareholders, banks and other stakeholders. The Paris Agreement urges companies to reduce carbon emissions to net zero by 2050, to achieve the goal of maximum 1.5°C temperature increase. A benchmarking study of sustainability performance was conducted on the environmental reports of 59 companies, and their plans for emission reductions were analysed. From the results, a framework to define CO2 reduction targets to achieve net zero has been devised for companies, starting from now.    

    

* A novel approach to integrate CCHP systems with desalination for sustainable energy and water solutions in educational buildings  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401019919
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization, Solar-Powered Water Desalination Technologies, Advancements in Water Purification Technologies
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2166/wst.2024.257")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401019919"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401019919"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401019919"))][Get cited by]]

OpenAlex: https://openalex.org/W4401019919 (Open access: True)
    
[[https://openalex.org/A5013878022][Faizah Mohammed Bashir]], [[https://openalex.org/A5094200523][Emmanuel Falude]], [[https://openalex.org/A5093016062][Ibtihaj Saad Rashed Alsadun]], [[https://openalex.org/A5001360030][Hakim Hamdoun]], [[https://openalex.org/A5024684683][Mohamed Ahmed Said Mohamed]], [[https://openalex.org/A5090156213][Nahla M. Shannan]], [[https://openalex.org/A5067899491][Ahmad Usman Naibi]], Water Science & Technology. None(None)] 2024. https://doi.org/10.2166/wst.2024.257 
     
ABSTRACT This study presents a novel approach to integrating combined cooling, heating, and power (CCHP) systems with water desalination for enhanced energy and water management in educational buildings. Two distinct layouts for CCHP and desalination systems are introduced: one prioritizing efficient power generation to meet electricity demands while providing waste heat for desalination, and the other focusing on balancing cooling and heating loads alongside water desalination. Both layouts are tailored to meet the building's energy and water demands while considering operational efficiency. Optimization of these layouts against traditional systems using the bat search algorithm emphasizes economic viability and the gas engine's operational flexibility, which are crucial for partial load operation. In addition, an environmental assessment compares the proposed CCHP-desalination systems with conventional setups, assessing CO2 emission reductions and overall sustainability. The evaluation encompasses key environmental metrics, such as resource consumption and the integration of renewable energy sources. Results highlight significant CO2 emission reductions across various gas engine capacities, with notable enhancements in economic and environmental performance achieved by selecting a 3,250 kW gas engine within the CCHP-desalination system. This choice not only maximizes the annual profit but also reduces CO2 emissions by 57% compared to conventional systems, underscoring the system's sustainability benefits.    

    

* АSSESSING THE EFFECTIVENESS OF AN INVESTMENT PROJECT TO REDUCE THE CARBON FOOTPRINT IN THE ENERGY SECTOR  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401019753
:TOPICS: Global Energy Transition and Fossil Fuel Depletion, Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-01-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.34925/eip.2023.161.12.141")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401019753"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401019753"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401019753"))][Get cited by]]

OpenAlex: https://openalex.org/W4401019753 (Open access: False)
    
[[https://openalex.org/A5105014731][Н.С. ЛЮЛЬЧЕНКО]], [[https://openalex.org/A5012890197][Р. В. Зайцев]], [[https://openalex.org/A5041507013][Anna Terekhova]], [[https://openalex.org/A5105050220][С.Р. ТАШОВА]], Экономика и предпринимательство. None(12(161))] 2024. https://doi.org/10.34925/eip.2023.161.12.141 
     
В рамках статьи в теоретическом и практическом ключе рассмотрены вопросы оценки инвестиционного проекта, связанного с снижением эмиссии CO2 в атмосферу связанную с деятельностью объектов энергетики. Особый фокус сделан на природе эмиссии CO2 и возможностях борьбы с ним в рамках зеленой энергетики. В работе рассмотрен как исторический опыт так и перспективные проекты в сфере концепции нулевых выбросов. Оценивается вклад ВИЭ в мировую энергетику и важность дальнейшей работы в сфере зеленой электрогенерации. Within the framework of articles on theoretical and practical key issues in assessing an investment project related to the reduction of CO2 emissions into the atmosphere associated with energy facilities. Particular focus is placed on CO2 emissions into the environment and the possibilities of combating them within the framework of green energy. The work includes both historical experience and promising projects in the field of the concept of the UK zero. The contribution of renewable energy sources to the global energy sector and further work in the field of green electricity generation are assessed.    

    

* Utilizing Limestone Alone for Integrated CO2 Capture and Reverse Water-Gas Reaction in a Fixed Bed Reactor: Employing Mass and Gas Signal Analysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400941480
:TOPICS: Advanced Techniques in Reservoir Management, Pore-scale Imaging and Enhanced Oil Recovery, Bioreactor Scale-up and Oxygen Transfer in Microbial Processes
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/pr12081548")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400941480"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400941480"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400941480"))][Get cited by]]

OpenAlex: https://openalex.org/W4400941480 (Open access: True)
    
[[https://openalex.org/A5046594420][Iwei Wang]], [[https://openalex.org/A5100671525][Shihui Wang]], [[https://openalex.org/A5058500620][Zhenshan Li]], Processes. 12(8)] 2024. https://doi.org/10.3390/pr12081548 
     
The integrated CO2 capture and utilization coupled with the reverse water-gas shift reaction (ICCU-RWGS) presents an alternative pathway for converting captured CO2 into CO in situ. This study investigates the effectiveness of three calcium-based materials (natural limestone, sol-gel CaCO3, and commercial CaCO3) as dual-functional materials (DFMs) for the ICCU-RWGS process at intermediate temperatures (650–750 °C). Our approach involves a fixed-bed reactor coupled with mass spectrometry and in situ Fourier transform infrared (FTIR) measurements to examine cyclic CO2 capture behavior, detailed physical and chemical properties, and morphology. The in situ FTIR results revealed the dominance of the RWGS route and exhibited self-catalytic activity across all calcium-based materials. Particularly, the natural limestone demonstrated a CO yield of 12.7 mmol g−1 with 100% CO selectivity and 81% CO2 conversion. Over the 20th cycle, a decrease in CO2 capture capacity was observed: sol-gel CaCO3, natural limestone, and commercial CaCO3 showed reductions of 44%, 61%, and 59%, respectively. This suggests inevitable deactivation during cyclic reactions in the ICCU-RWGS process, while the skeleton structure effectively prevents agglomeration in Ca-based materials, particularly in sol-gel CaCO3. These insights, coupled with the cost-effectiveness of CaO-alone DFMs, offer promising avenues for efficient and economically viable ICCU-RWGS processes.    

    

* Formate Dehydrogenase: Recent Developments for NADH and NADPH Recycling in Biocatalysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400982189
:TOPICS: Amino Acid Transport and Metabolism in Health and Disease, Enzyme Immobilization Techniques, Pancreatic Islet Dysfunction and Regeneration
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202401021")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400982189"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400982189"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400982189"))][Get cited by]]

OpenAlex: https://openalex.org/W4400982189 (Open access: False)
    
[[https://openalex.org/A5059230884][Artur Maier]], [[https://openalex.org/A5105049829][Lindelo M. Mguni]], [[https://openalex.org/A5055809666][Anna Ngo]], [[https://openalex.org/A5001303954][Dirk Tischler]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202401021 
     
Formate dehydrogenases (FDHs) catalyze the oxidation of formate to CO2 while reducing NAD(P)+ to NAD(P)H and are classified into two main classes: metal‐dependent (Mo‐ or W‐containing) and metal‐independent FDHs. The latter are oxygen‐tolerant and relevant as a cofactor regeneration system for various bioprocesses and gained more and more attention due to their ability to catalyze the reverse CO2 reduction. This review gives an overview of metal‐independent FDHs, the recent advances made in this field, and their relevance for future applications in biocatalysis. This includes the exploitation of novel FDHs which have altered co‐substrate specificity as well as enzyme engineering approaches to improve process stability and general performance.    

    

* Asymmetric Cu−N1O3 Sites Coupling Atop‐type and Bridge‐type Adsorbed *C1 for Electrocatalytic CO2‐to‐C2 Conversion  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400964714
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Engineering of Surface Nanostructures
:PUBLICATION_DATE: 2024-07-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202411216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400964714"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400964714"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400964714"))][Get cited by]]

OpenAlex: https://openalex.org/W4400964714 (Open access: False)
    
[[https://openalex.org/A5100665687][Changli Wang]], [[https://openalex.org/A5102347822][Zunhang Lv]], [[https://openalex.org/A5046249498][Yarong Liu]], [[https://openalex.org/A5101986799][Lu Dai]], [[https://openalex.org/A5101359178][Rui Liu]], [[https://openalex.org/A5101259967][Caiting Sun]], [[https://openalex.org/A5100768141][Weiyi Liu]], [[https://openalex.org/A5100706062][Xiao Feng]], [[https://openalex.org/A5064928999][Wenxiu Yang]], [[https://openalex.org/A5100408029][Bo Wang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202411216 
     
2D functional porous frameworks offer a platform for studying the structure‐activity relationships during electrocatalytic CO2 reduction reaction (CO2RR). Yet challenges still exist to breakthrough key limitations on site configuration (typical M–O4 or M–N4 units) and product selectivity (common CO2‐to‐CO conversion). Herein, a novel 2D metal‐organic framework (MOF) with planar asymmetric N/O mixed coordinated Cu–N1O3 unit is constructed, labeled as BIT‐119. When applied to CO2RR, BIT‐119 could reach a CO2‐to‐C2 conversion with C2 partial current density ranging from 36.9 to 165.0 mA cm−2 in flow cell. Compared to the typical symmetric Cu–O4 units, asymmetric Cu–N1O3 units lead to the re‐distribution of local electron structure, regulating the adsorption strength of several key adsorbates and the following catalytic selectivity. From experimental and theoretical analyses, Cu−N1O3 sites could simultaneously couple the atop‐type (on Cu site) and bridge‐type (on Cu–N site) adsorption of *C1 species to reach the CO2‐to‐C2 conversion. This work broadens the feasible C−C coupling mechanism on 2D functional porous frameworks.    

    

* Asymmetric Cu−N1O3 Sites Coupling Atop‐type and Bridge‐type Adsorbed *C1 for Electrocatalytic CO2‐to‐C2 Conversion  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400964871
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-07-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202411216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400964871"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400964871"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400964871"))][Get cited by]]

OpenAlex: https://openalex.org/W4400964871 (Open access: False)
    
[[https://openalex.org/A5100665687][Changli Wang]], [[https://openalex.org/A5102347822][Zunhang Lv]], [[https://openalex.org/A5046249498][Yarong Liu]], [[https://openalex.org/A5101986799][Lu Dai]], [[https://openalex.org/A5100448332][Rui Liu]], [[https://openalex.org/A5101259967][Caiting Sun]], [[https://openalex.org/A5100768141][Weiyi Liu]], [[https://openalex.org/A5100706062][Xiao Feng]], [[https://openalex.org/A5064928999][Wenxiu Yang]], [[https://openalex.org/A5092077531][Bo Wang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202411216 
     
2D functional porous frameworks offer a platform for studying the structure‐activity relationships during electrocatalytic CO2 reduction reaction (CO2RR). Yet challenges still exist to breakthrough key limitations on site configuration (typical M–O4 or M–N4 units) and product selectivity (common CO2‐to‐CO conversion). Herein, a novel 2D metal‐organic framework (MOF) with planar asymmetric N/O mixed coordinated Cu–N1O3 unit is constructed, labeled as BIT‐119. When applied to CO2RR, BIT‐119 could reach a CO2‐to‐C2 conversion with C2 partial current density ranging from 36.9 to 165.0 mA cm−2 in flow cell. Compared to the typical symmetric Cu–O4 units, asymmetric Cu–N1O3 units lead to the re‐distribution of local electron structure, regulating the adsorption strength of several key adsorbates and the following catalytic selectivity. From experimental and theoretical analyses, Cu−N1O3 sites could simultaneously couple the atop‐type (on Cu site) and bridge‐type (on Cu–N site) adsorption of *C1 species to reach the CO2‐to‐C2 conversion. This work broadens the feasible C−C coupling mechanism on 2D functional porous frameworks.    

    

* Hyperspectral Characteristics and SPAD Estimation of Wheat Leaves under CO2 Microleakage Stress  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400951050
:TOPICS: Chemometrics in Analytical Chemistry and Food Technology, On-line Monitoring of Wastewater Quality, Optoelectronic Systems for Measurement and Detection
:PUBLICATION_DATE: 2024-07-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/s24154776")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400951050"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400951050"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400951050"))][Get cited by]]

OpenAlex: https://openalex.org/W4400951050 (Open access: True)
    
[[https://openalex.org/A5083861220][Liuya Zhang]], [[https://openalex.org/A5051457436][Debao Yuan]], [[https://openalex.org/A5101384174][Yuqing Fan]], [[https://openalex.org/A5101997988][Renshu Yang]], Sensors. 24(15)] 2024. https://doi.org/10.3390/s24154776 
     
To non-destructively and rapidly monitor the chlorophyll content of winter wheat leaves under CO2 microleakage stress, and to establish the quantitative relationship between chlorophyll content and sensitive bands in the winter wheat growing season from 2023 to 2024, the leakage rate was set to 1 L/min, 3 L/min, 5 L/min, and 0 L/min through field experiments. The dimensional reduction was realized, fractional differential processing of a wheat canopy spectrum was carried out, a multiple linear regression (MLR) and partial least squares regression (PLSR) estimation model was constructed using a SPA selection band, and the model’s accuracy was evaluated. The optimal model for hyperspectral estimation of wheat SPAD under CO2 microleakage stress was screened. The results show that the spectral curves of winter wheat leaves under CO2 microleakage stress showed a “red shift” of the green peak and a “blue shift” of the red edge. Compared with 1 L/min and 3 L/min, wheat leaves were more affected by CO2 at 5 L/min. Evaluation of the accuracy of the MLR and PLSR models shows that the MLR model is better, where the MLR estimation model based on 1.1, 1.8, 0.4, and 1.7 differential SPAD is the best for leakage rates of 1 L/min, 3 L/min, 5 L/min, and 0 L/min, with validation set R² of 0.832, 0.760, 0.928, and 0.773, which are 11.528, 14.2, 17.048, and 37.3% higher than the raw spectra, respectively. This method can be used to estimate the chlorophyll content of winter wheat leaves under CO2 trace-leakage stress and to dynamically monitor CO2 trace-leakage stress in crops.    

    

* Hydrogen Blending in Natural Gas Grid: Energy, Environmental, and Economic Implications in the Residential Sector  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400948837
:TOPICS: Hydrogen Energy Systems and Technologies, Cryogenic Fluid Storage and Management, Indoor Air Pollution in Developing Countries
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/buildings14082284")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400948837"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400948837"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400948837"))][Get cited by]]

OpenAlex: https://openalex.org/W4400948837 (Open access: True)
    
[[https://openalex.org/A5092589561][Domiziana Vespasiano]], [[https://openalex.org/A5092350907][Antonio Sgaramella]], [[https://openalex.org/A5007624704][Gianluigi Lo Basso]], [[https://openalex.org/A5013269733][Livio de Santoli]], [[https://openalex.org/A5091498216][Lorenzo Mario Pastore]], Buildings. 14(8)] 2024. https://doi.org/10.3390/buildings14082284 
     
The forthcoming implementation of national policies towards hydrogen blending into the natural gas grid will affect the technical and economic parameters that must be taken into account in the design of building heating systems. This study evaluates the implications of using hydrogen-enriched natural gas (H2NG) blends in condensing boilers and Gas Adsorption Heat Pumps (GAHPs) in a residential building in Rome, Italy. The analysis considers several parameters, including non-renewable primary energy consumption, CO2 emissions, Levelized Cost of Heat (LCOH), and Carbon Abatement Cost (CAC). The results show that a 30% hydrogen blend achieves a primary energy consumption reduction of 12.05% and 11.19% in boilers and GAHPs, respectively. The presence of hydrogen in the mixture exerts a more pronounced influence on the reduction in fossil primary energy and CO2 emissions in condensing boilers, as it enhances combustion efficiency. The GAHP system turns out to be more cost-effective due to its higher efficiency. At current hydrogen costs, the LCOH of both technologies increases as the volume fraction of hydrogen increases. The forthcoming cost reduction in hydrogen will reduce the LCOH and the decarbonization cost for both technologies. At low hydrogen prices, the CAC for boilers is lower than for GAHPs; therefore, replacing boilers with other gas technologies rather than electric heat pumps increases the risk of creating stranded assets. In conclusion, blending hydrogen into the gas grid can be a useful policy to reduce emissions from the overall natural gas consumption during the process of end-use electrification, while stimulating the development of a hydrogen economy.    

    

* Do Technological Innovation and Environmental Regulation Reduce Carbon Dioxide Emissions? Evidence from China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400960997
:TOPICS: Economic Impact of Environmental Policies and Resources, Rebound Effect on Energy Efficiency and Consumption, Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.30955/gnj.06291")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400960997"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400960997"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400960997"))][Get cited by]]

OpenAlex: https://openalex.org/W4400960997 (Open access: False)
    
, Global NEST Journal. None(None)] 2024. https://doi.org/10.30955/gnj.06291 
     
<p style="text-indent:0cm; text-align:justify"><span style="font-size:12pt"><span style="line-height:150%"><span style="font-family:&quot;Times New Roman&quot;,serif">The Chinese industry holds a significant position in the national economy. However, industrial carbon dioxide (CO<sub>2</sub>) emissions account for a large proportion of the total CO<sub>2</sub> emissions, which has a negative impact on the environment. To identify the factors affecting industrial CO<sub>2</sub> emissions, a vector autoregressive (VAR) model system is established to empirically test the factors influencing industrial CO<sub>2</sub> emissions, using data on industrial technology innovation (TI), environmental regulation, and CO<sub>2</sub> emissions from 2000 to 2023 in China. The results show that there is a cointegration relationship between industrial technological innovation, environmental regulation and CO<sub>2</sub> emissions. Each unit increase in environmental regulation will reduce 2.132 units of CO<sub>2</sub> emissions. Meanwhile, each unit increase in technological innovation results in a decrease of 0.067 units of CO<sub>2</sub> emissions. Compared with TI, environmental regulation has a greater impact on CO<sub>2</sub> emission reduction. The effects of the impulses of the stochastic perturbation terms of industrial TI, environmental regulation, and CO<sub>2</sub> emissions on the current and future values of industrial TI, environmental regulation, and CO<sub>2</sub> emissions in the VAR system are de-picted through the VAR impulse response function. The contribution of each new interest shock to the change of industrial TI, environmental regulation and CO<sub>2</sub> emissions is analyzed by variance decomposition. This paper enriches the application of institutional theory and technological in-novation theory in CO<sub>2</sub> emission reduction and also provides a reference for relevant departments to formulate emission reduction policies and industrial technological innovation.</span></span></span></p>    

    

* Dual Electron Donating Metal‐Boron Reaction Center Boosts Electrocatalytic Urea Synthesis from N2 and CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401039536
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400304")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401039536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401039536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401039536"))][Get cited by]]

OpenAlex: https://openalex.org/W4401039536 (Open access: False)
    
[[https://openalex.org/A5059644018][Nuttapon Yodsin]], [[https://openalex.org/A5083240495][Poobodin Mano]], [[https://openalex.org/A5086087324][Kaito Takahashi]], [[https://openalex.org/A5077457552][supawadee namuangruk]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400304 
     
Urea (NH2CONH2) production by electrosynthesis at mild conditions has been hampered due to the lack of systematic evaluation of pathways in effectively activating inert N2 and CO2 molecules and facilitating the formation of C‐N bonds. This work, we evaluated 16 transition metal (M) atoms anchored on a carbon nitride nanosheet with boron (B) doping (M‐B@C2N) for boosting urea production by theoretical calculations. All possible urea synthesis pathways, (i) CO2 pathway, (ii) OCOH pathway, (iii) CO pathway, and (iv) NCON pathway, were comparatively studied on Cu, Fe, Co, Ni‐B@C2N. This systematic calculation identified that the first reduction of *N2 is the key step for urea synthesis. We found that the bond index of *N2 shows a strong correlation with ΔG*N2®*NNH, so they are promising descriptors for screening. Through the screening, we found that Nb‐ and Mo‐B@C2N show a low limiting potential of ‐0.56 and ‐0.53 V. Although previous studies found that spin could promote C‐C bond formation on M‐B@C2N, we found that for C‐N coupling, such effects by spin were only active for Nb‐B@C2N. Combining boron and early transition metal atoms allows for neighboring reaction sites that simultaneously donate electrons to activate inert N2 and CO2 for efficient urea synthesis.    

    

* Estrategias para Mejorar la Eficiencia Energética en Edificios de servicios públicos, en una Zona Climática Calurosa y Húmeda: Caso de Estudio en Guayaquil, Ecuador  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400977319
:TOPICS: Sustainable Construction and Green Building, Energy, Climate Change, and Environmental Impact Assessment
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.37116/revistaenergia.v21.n1.2024.651")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400977319"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400977319"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400977319"))][Get cited by]]

OpenAlex: https://openalex.org/W4400977319 (Open access: True)
    
[[https://openalex.org/A5051087502][E. Catalina Vallejo-Coral]], [[https://openalex.org/A5005944050][Luis Godoy-Vaca]], [[https://openalex.org/A5065720508][Francis Vásquez]], [[https://openalex.org/A5045752365][Geovanna Villacreses]], [[https://openalex.org/A5014063220][Marco Orozco]], [[https://openalex.org/A5021381139][Santiago Albero Navarro]], Revista Técnica Energía. 21(1)] 2024. https://doi.org/10.37116/revistaenergia.v21.n1.2024.651 
     
Since 2010, there has been an approximate annual increase of 1% in CO2 emissions due to buildings. The reduction of energy consumption and consequently the mitigation of Greenhouse Gases are global goals due to the global issue of climate change. A key step in achieving these goals is to improve the energy performance of buildings, thereby reducing energy consumption and emissions generated by the built environment. In this regard, the present research focuses on identifying and estimating strategies to reduce energy consumption in buildings known as Community Police Units (UPCs) located in the city of Guayaquil, which corresponds to a very hot and humid climate zone. The study consists of statistical analysis of the historical energy performance of 43 buildings sharing the same architectural design. Additionally, the selection of a representative building was made for energy use monitoring and energy simulation. The results revealed a potential saving of 16 000 kWh per year by reducing the control temperature of the air conditioning system by 1°C and adjusting the on/off schedule. This is equivalent to 1 150 USD and 5 metric tons of CO2 emissions.    

    

* Decarbonization of Heating and Cooling Systems of Buildings Located Nearby Surface Water Sources: Case Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400973982
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17153673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400973982"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400973982"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400973982"))][Get cited by]]

OpenAlex: https://openalex.org/W4400973982 (Open access: True)
    
[[https://openalex.org/A5056127547][Adriana Tokar]], [[https://openalex.org/A5074014125][Daniel Muntean]], [[https://openalex.org/A5084842362][Dănuț Tokar]], [[https://openalex.org/A5066339339][Daniel Bisorca]], Energies. 17(15)] 2024. https://doi.org/10.3390/en17153673 
     
The study was carried out to evaluate theoretically and in laboratory conditions the capacity of a hybrid heating and cooling system that sustainably uses thermal energy extracted from surface waters in order to decarbonize buildings located near water sources. The novelty of the research consists in the realization of two experimental systems, one for the rapid evaluation of the performance of the water–water heat pump heating system and one for the evaluation of the operating behavior of a cooling system with fan coil units. Starting with the heating and cooling demand, and the climatic and hydrological local characteristics, a hybrid system model for the heating and cooling of the analyzed building was established and implemented. The forecasted energy consumption and CO2 emissions for the operation of the new equipment were compared with the historical values of the old systems with which the building was equipped (thermal energy supply from the district heating and cooling system with an air conditioning unit). Also, the results were extrapolated for forecasting the energy potential of the surface waters. The study highlights a percentage reduction in annual energy consumption of 67.71% and CO2 emissions of 80.13% through the implementation of the hybrid system.    

    

* THE ECONOMY OF CARBON NEUTRALITY IN THE PARADIGM OF SUSTAINABLE DEVELOPMENT: THE ESSENCE, FEATURES, PREREQUISITES FOR THE FORMATION OF  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400960882
:TOPICS: Socio-Economic Development and Global Economic Challenges
:PUBLICATION_DATE: 2023-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.34925/eip.2023.154.5.003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400960882"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400960882"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400960882"))][Get cited by]]

OpenAlex: https://openalex.org/W4400960882 (Open access: False)
    
[[https://openalex.org/A5046606437][Elena Molchanova]], [[https://openalex.org/A5062079394][Н.В. ПУЧКОВА]], Экономика и предпринимательство. None(5(154))] 2023. https://doi.org/10.34925/eip.2023.154.5.003 
     
Одной из ключевых целей, включенных в Повестку в области устойчивого развития на период 2030 года, является принятие срочных мер по борьбе с изменением климата и его последствиями. В статье проанализированы сущность, особенности, предпосылки формирования тренда на низкоуглеродную экономику и необходимость ограничения глобального потепления на 1,5°C, что, в свою очередь, невозможно без немедленного и глубокого сокращения выбросов во всех секторах. При этом в настоящее время многие национальные и субнациональные юрисдикции и компании ищут новые методы сокращения выбросов парниковых газов, прежде всего CO2, стремясь одновременно решить две задачи, которые противоречат друг другу: снизить воздействие на климат планеты и сохранить экономическую конкурентоспособность. One of the key goals included in the 2030 Agenda for Sustainable Development is to take urgent action to combat climate change and its impacts. The article analyzes the essence, features, prerequisites for the formation of a trend towards a low-carbon economy and the need to limit global warming by 1.5°C, which, in turn, is impossible without an immediate and deep reduction in emissions in all sectors. At the same time, many national and subnational jurisdictions and companies are currently looking for new methods to reduce greenhouse gas emissions, primarily CO2, trying to simultaneously solve two problems that contradict each other: reduce the impact on the planet's climate and maintain economic competitiveness.    

    

* Has the EU Emissions Trading System Worked Properly?  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400984854
:TOPICS: Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17153651")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400984854"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400984854"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400984854"))][Get cited by]]

OpenAlex: https://openalex.org/W4400984854 (Open access: True)
    
[[https://openalex.org/A5002729048][Chia‐Lin Chang]], [[https://openalex.org/A5089722184][Jukka Ilomäki]], [[https://openalex.org/A5006877478][Hannu Laurila]], Energies. 17(15)] 2024. https://doi.org/10.3390/en17153651 
     
Climate change poses an unprecedented global challenge, which prompts nations to adopt new strategies to mitigate greenhouse gas emissions. The European Union emissions trading system (EU ETS) is a cornerstone of the EU’s efforts towards a cost-effective fight against climate change. This study examines the effectiveness of the EU ETS by analyzing monthly data from December 2008 to December 2021, with the focus on CO2 emission allowance futures prices, renewable energy indices, coal prices, oil prices, and fossil energy indices. The key findings are as follows: The CO2 emission allowance futures prices have averaged EUR 14.83 per ton, ranging from EUR 2.87 to EUR 76.81, which shows a significant upward trend. The renewable energy index also demonstrated strong growth, with a mean 1562.07 and maximum 4571.96. Coal prices have averaged EUR 65.32 per ton, while Brent oil prices averaged EUR 59.85 per barrel. A cointegration analysis revealed a long-run equilibrium relationship between these variables. The Vector Error Correction model (VECM) revealed significant negative responses to long-run equilibrium deviations of the renewable energy index (−0.0155) and oil prices (−0.0236), a significant negative short-run response of CO2 prices to their own lagged values (−0.223), and a significant positive short-run effect of oil prices on the fossil energy index (0.254). These results suggest the EU ETS has created significant linkages between carbon, energy, and financial markets. The study concludes that while the EU ETS has made progress in motivating emissions reductions and promoting renewable energy, the system’s efficacy still needs improvement.    

    

* Catalytic composition and fuel influence on anodic processes characteristics of solid polymer electrolyte fuel cells  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027802
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2008-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18500/1608-4039-2008-8-1-33-39")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027802"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027802"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027802"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027802 (Open access: False)
    
[[https://openalex.org/A5042546780][Н. В. Кулешов]], [[https://openalex.org/A5010839364][S. V. Grigoriev]], Electrochemical Energetics. 8(1)] 2008. https://doi.org/10.18500/1608-4039-2008-8-1-33-39 
     
It was studied an influence of prior carbon treatment (temperature and gas conditions, mass content of waterproofing agent) on activity of platinum catalyst, synthesized on disperse carbon carrier. It was shown that characteristics of anodic processes depend on quantity of solid polymer electrolyte in catalytic composition. Optimal content of ion exchange polymer under varied degree of carbon carrier waterproofing (used for synthesis of platinum catalyst) is not equal. In a case of platinum catalyst synthesized on a base of carbon carrier with the addition of waterproofing agent (10 mass %), the highest current density of fuel cell functioning on pure oxygen corresponds to 15-20 mass % of polymer content in a layer and in a case of air – 10-15 mass %. Impurity of carbonic gas in anodic fuel leads to decrease of current density on fuel cell withdrawal not only because of partial pressure decrease. The reason of parameter worsening is partial platinum poisoning with CO, appearing after CO2 reduction.    

    

* Dynamics of Plant Water Uptake under Modified Environment  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400954119
:TOPICS: Global Forest Drought Response and Climate Change, Plant Responses to Flooding Stress, Impacts of Elevated CO2 and Ozone on Plant Physiology
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5772/intechopen.109421")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400954119"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400954119"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400954119"))][Get cited by]]

OpenAlex: https://openalex.org/W4400954119 (Open access: False)
    
[[https://openalex.org/A5027956630][Saurav Saha]], [[https://openalex.org/A5037566375][B. U. Choudhury]], [[https://openalex.org/A5041081967][Bappa Das]], [[https://openalex.org/A5042680294][Prashant Pandey]], IntechOpen eBooks. None(None)] 2024. https://doi.org/10.5772/intechopen.109421 
     
The environmental control of crop physiology increases relative sensitivity of crop water movement within the soil plant atmosphere continuum (SPAC), so as the dynamics of crop water usage under modified climate. The variable environmental conditions determine the relative direction of change. Elevated CO2 exposure depressed the water movement of transpiration flux through reduced stomatal conductance and facilitated partial stomatal closure. However, the net impact may not be ensued the significant reduction in crop water usage at the end of crop season due to modified leaf area dynamics, but with obvious rise in crop water use efficiency (WUE). Thermal stresses are often combined with drought events depressed crop WUE beyond a threshold sourced from adverse impact on total dry matter production under elevated temperature condition. The pathogenic role of O3 exposure induced stomatal sluggishness and reduction in dry matter accumulation (or yield) are sourced from reduced photosynthetic assimilation and aberration in stomatal conductance and thereby reduction in crop WUE under well-watered condition. However, the protective roles of other co-existing abiotic stress factors are subjected to more explanatory research. However, the genetic resilience toward such climate change induced abiotic stress factors and supportive field management options will provide our future facets of sustainable crop production with higher WUE crop under variable environmental conditions.    

    

* Severe Spaceflight-Associated Neuro-Ocular Syndrome in an Astronaut With 2 Predisposing Factors  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400978364
:TOPICS: Physiological Effects of Space Travel and Microgravity, Genetic and Physiological Adaptations to High-Altitude Environments, Patent Foramen Ovale and Cerebrovascular Events
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1001/jamaophthalmol.2024.2385")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400978364"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400978364"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400978364"))][Get cited by]]

OpenAlex: https://openalex.org/W4400978364 (Open access: False)
    
[[https://openalex.org/A5075990703][Tyson Brunstetter]], [[https://openalex.org/A5014977670][Sara R. Zwart]], [[https://openalex.org/A5003574926][Keith Brandt]], [[https://openalex.org/A5102897222][David M. Brown]], [[https://openalex.org/A5085421865][S. J. Clemett]], [[https://openalex.org/A5075932993][Grace L. Douglas]], [[https://openalex.org/A5063216533][Charles R. Gibson]], [[https://openalex.org/A5037131236][Steven S. Laurie]], [[https://openalex.org/A5027507681][Andrew G. Lee]], [[https://openalex.org/A5022200003][Brandon R. Macias]], [[https://openalex.org/A5051466856][Thomas H. Mader]], [[https://openalex.org/A5052826562][Sara S. Mason]], [[https://openalex.org/A5064406408][Jessica U. Meir]], [[https://openalex.org/A5084390618][Andrew Morgan]], [[https://openalex.org/A5056614821][Mayra Nelman]], [[https://openalex.org/A5044769585][Nimesh B. Patel]], [[https://openalex.org/A5103390147][Clarence F. Sams]], [[https://openalex.org/A5102839281][Rahul Suresh]], [[https://openalex.org/A5017664835][William J. Tarver]], [[https://openalex.org/A5092653716][Ann Tsung]], [[https://openalex.org/A5037315341][Mary G. Van Baalen]], [[https://openalex.org/A5075879804][Scott M. Smith]], JAMA Ophthalmology. None(None)] 2024. https://doi.org/10.1001/jamaophthalmol.2024.2385 
     
Importance Understanding potential predisposing factors associated with spaceflight-associated neuro-ocular syndrome (SANS) may influence its management. Objective To describe a severe case of SANS associated with 2 potentially predisposing factors. Design, Setting, and Participants Ocular testing of and blood collections from a female astronaut were completed preflight, inflight, and postflight in the setting of the International Space Station (ISS). Exposure Weightlessness throughout an approximately 6-month ISS mission. Mean carbon dioxide (CO 2 ) partial pressure decreased from 2.6 to 1.3 mm Hg weeks before the astronaut’s flight day (FD) 154 optical coherence tomography (OCT) session. In response to SANS, 4 B-vitamin supplements (vitamin B 6 , 100 mg; L-methylfolate, 5 mg; vitamin B 12 , 1000 μg; and riboflavin, 400 mg) were deployed, unpacked on FD153, consumed daily through FD169, and then discontinued due to gastrointestinal discomfort. Main Outcomes and Measures Refraction, distance visual acuity (DVA), optic nerve, and macular assessment on OCT. Results Cycloplegic refraction was −1.00 diopter in both eyes preflight and +0.50 − 0.25 × 015 in the right eye and +1.00 diopter in the left eye 3 days postflight. Uncorrected DVA was 20/30 OU preflight, 20/16 or better by FD90, and 20/15 OU 3 days postflight. Inflight peripapillary total retinal thickness (TRT) peaked between FD84 and FD126 (right eye, 401 μm preflight, 613 μm on FD84; left eye, 404 μm preflight, 636 μm on FD126), then decreased. Peripapillary choroidal folds, quantified by surface roughness, peaked at 12.7 μm in the right eye on FD154 and 15.0 μm in the left eye on FD126, then decreased. Mean choroidal thickness increased throughout the mission. Genetic analyses revealed 2 minor alleles for MTRR 66 and 2 major alleles for SHMT1 1420 (ie, 4 of 4 SANS risk alleles). One-week postflight, lumbar puncture opening pressure was normal, at 19.4 cm H 2 O. Conclusions and Relevance To the authors’ knowledge, no other report of SANS documented as large of a change in peripapillary TRT or hyperopic shift during a mission as in this astronaut, and this was only 1 of 4 astronauts to experience chorioretinal folds approaching the fovea. This case showed substantial inflight improvement greater than the sensitivity of the measure, possibly associated with B-vitamin supplementation and/or reduction in cabin CO 2 . However, as a single report, such improvement could be coincidental to these interventions, warranting further evaluation.    

    

* Comparison of the Temperature, Radiation, and Heat Flux Distribution of a Hydrogen and a Methane Flame in a Crucible Furnace Using Numerical Simulation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400974180
:TOPICS: Inverse Radiative Heat Transfer Analysis, Dynamics of Turbulent Combustion Systems, Chemical Kinetics of Combustion Processes
:PUBLICATION_DATE: 2024-07-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/hydrogen5030026")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400974180"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400974180"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400974180"))][Get cited by]]

OpenAlex: https://openalex.org/W4400974180 (Open access: True)
    
[[https://openalex.org/A5068308844][Alexander Mages]], [[https://openalex.org/A5037568055][Alexander Sauer]], Hydrogen. 5(3)] 2024. https://doi.org/10.3390/hydrogen5030026 
     
Sustainable technologies to replace current fossil solutions are essential to meet future CO2 emission reduction targets. Therefore, this paper compares key performance indicators of a hydrogen- and a methane-flame-fired crucible furnace with computational fluid dynamics simulations at identical firing powers, aiming to fully decarbonize the process. Validated numerical models from the literature were used to compare temperatures, radiation fields, radiation parameters and heat transfer characteristics. As a result, we observed higher combustion temperatures and a 19.0% higher fuel utilization rate in the hydrogen case, indicating more efficient operating modes, which could be related to the increased radiant heat flux and temperature ranges above 1750 K. Furthermore, higher scattering of the heat flux distribution on the crucible surface could be determined indicating more uneven melt bath temperatures. Further research could focus on quantifying the total fuel consumption required for the heating up of the furnace, for which a transient numerical model could be developed.    

    

* Exploring biofilm-forming bacteria for integration into BioCircuit wastewater treatment  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400972910
:TOPICS: Microbial Fuel Cells and Electrogenic Bacteria Technology, Microbial Nitrogen Cycling in Wastewater Treatment Systems, Biohydrometallurgical Processes for Metal Extraction
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.62063/ecb-28")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400972910"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400972910"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400972910"))][Get cited by]]

OpenAlex: https://openalex.org/W4400972910 (Open access: False)
    
[[https://openalex.org/A5017493652][Chontisa Sukkasem]], The European Chemistry and Biotechnology Journal. None(2)] 2024. https://doi.org/10.62063/ecb-28 
     
This study aimed to investigate the presence of biofilm-forming bacteria within high sulfide sludge obtained from a rubber wastewater treatment plant and assess their suitability for application within a BioCircuit System (BCS) as a symbiotic community for treating nutrient-rich wastewater. The sludge samples were collected and subjected to microbial culture techniques, wherein pure cultures were isolated based on morphological characteristics observed under a light microscope, followed by assessment of motility using swarm agar. Subsequent identification was conducted utilizing the 16S rRNA gene sequencing method, and the isolated bacteria were introduced into the BCS. A 12 mL microbial fuel cell test was conducted to evaluate their power generation capabilities. The wastewater treatment process involved inoculating the BCS with 20% crude rubber wastewater sludge, and the system was initiated at a flow rate of 0.5 L/min for a month. Upon achieving an open-circuit voltage exceeding 50 mV, the BCS was operated at incremental flow rates (0.5-1.0, 1.0-1.5, and 1.5-2.0 mL/ min) over a period of 6 months. Real-time monitoring of voltage, flow rate, and energy consumption was facilitated through an internet-of-things online program. Weekly sampling and analysis of influent and effluent, focusing on chemical oxygen demand (COD), sulfate, and sulfide concentrations, were conducted. Additionally, the BioCircuit voltage was recorded every 5 minutes. The results revealed the presence of six group-forming shaped bacteria identified as Bacillus tequilensis, Bacillus sp., Ferribacterium limneticum, Bacillus weihenstephanesis, and Mycobacterium sp., respectively. The optimal flow rate of 1.5 L/min yielded a maximum voltage of 1.2 V and demonstrated high wastewater treatment efficiency. Economically, the BCS operation exhibited a power consumption rate of 0.257 kWhr/m3 of treated wastewater, leading to an 88.90% reduction in carbon footprint compared to aerated lagoon treatment, equivalent to 50.94 kg CO2/m3 of treated wastewater or 183,384 kg CO2/yr for a 10 m3 plant. These findings underscore the potential of the BCS in conjunction with group-forming shaped bacteria communities for various industrial wastewater treatment applications.    

    

* Comparison of Exhaust Gas Emissions of a Vehicle with an Internal Combustion Engine in High and Low Vehicular Congestion for a High Altitude City  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401036584
:TOPICS: Estimating Vehicle Fuel Consumption and Emissions, Chemical Kinetics of Combustion Processes, Health Effects of Air Pollution
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18502/espoch.v3i3.16623")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401036584"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401036584"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401036584"))][Get cited by]]

OpenAlex: https://openalex.org/W4401036584 (Open access: True)
    
[[https://openalex.org/A5046858313][Jorge Lema]], ESPOCH Congresses The Ecuadorian Journal of S T E A M. None(None)] 2024. https://doi.org/10.18502/espoch.v3i3.16623 
     
Pollution generated by the automotive sector is one of the biggest concerns in the city of Quito. This is due to the fact that the majority of vehicles in the automotive fleet use fossil fuels as a source of propulsion energy. In addition, the heterogeneity of the technologies of the fuel injection systems means that the control of polluting emissions is highly limited. On the other hand, due to the high number of vehicles and the topographical characteristics of the city, high traffic congestion is generated during rush hours, producing abrupt changes in acceleration and reduction of stoichiometric mixtures. Based on the above, it was pertinent to compare the exhaust gas emissions that are produced in high and low vehicular congestion for a vehicle with an internal combustion engine Likewise, the correlations of the gases for both scenarios were determined. To do this, emissions were measured in a Mazda 3 vehicle on a major city route during rush hours and on weekends. A Kane Autoplus gas analyzer was used for exhaust gas measurement, and data logging was done on the Kane Live app. The results showed that in rush hours, the vehicle emits higher amounts of CO2, CO, and HC up to 0.7%; 128.5%; and 65.5%, respectively. There are moderate and strong correlations of O2-CO2 and CO-HC in high and low vehicular congestion, with Pearson’s correlation values greater than 0.5. Keywords: exhaust gases, internal combustion engine, pollution, route, rush hours, traffic. Resumen La contaminación generada por el sector automotriz, es uno de los mayores problemas que enfrenta la ciudad de Quito. Esto se debe a que la mayoría de vehículos del parque automotor, utilizan combustibles fósiles como fuente de energía de propulsión. Además, la heterogeneidad de las tecnologías de los sistemas de inyección de combustible, hace que el control de emisiones contaminantes se limite considerablemente. Por otro lado, debido al elevado número de vehículos y a las características topográficas de la ciudad, se genera una elevada congestión vehicular en horas pico, produciendo cambios abruptos de aceleraciones y reducción de las mezclas estequiométricas. Con base a lo expuesto, fue pertinente comparar las emisiones de gases de escape que se producen en alta y baja congestión vehicular para un vehículo con motor de combustión interna, y así mismo, se determinó las correlaciones de los gases para ambos escenarios. Para ello, se midió las emisiones en un vehículo Mazda 3 sobre una ruta importante de la ciudad en horas pico y fines de semana. Se utilizó un analizador de gases Kane Autoplus para la medición de los gases de escape, y el registro de datos se efectuó en la aplicación Kane Live. Los resultados mostraron que en horas pico, el vehículo emite mayores cantidades de CO2, CO, HC de hasta el 0,77%; 6,66%; 94,69%, respectivamente. Existen moderadas y fuertes correlaciones de O2-CO2 y CO-HC en alta y baja congestión vehicular, con valores de correlación de Pearson superior a 0,5. Palabras Clave: contaminación, gases de escape, horas pico, motor de combustión interna, ruta, tráfico.    

    

* Evaluation of the Effect of MiR-206 on the Expression of Toll-like Receptor 2 and TLR4 in the Melanoma A-375 Cells  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400955722
:TOPICS: Immunobiology of Dendritic Cells, Mechanisms and Applications of RNA Interference, Antimicrobial Peptides in Host Defense and Therapy
:PUBLICATION_DATE: 2023-12-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.34172/biomedrb.2023.25")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400955722"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400955722"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400955722"))][Get cited by]]

OpenAlex: https://openalex.org/W4400955722 (Open access: False)
    
[[https://openalex.org/A5105018798][Mojtaba Gholinezhad]], [[https://openalex.org/A5105032508][Bahareh Sartipi]], [[https://openalex.org/A5105018799][Babak Sandoghchian Shotorbani]], Biomedical Research Bulletin. 1(4)] 2023. https://doi.org/10.34172/biomedrb.2023.25 
     
Background: Melanoma is one of the most deadly skin cancers in humanity, which imposes extensive costs on governments. Fortunately, the death rate has decreased despite the increasing incidence of melanoma. Various treatment methods, including surgery, chemotherapy, radiotherapy, targeted therapy, and the like, are used to treat this disease. However, despite recent advances in diagnosis and treatment, melanoma remains one of the leading causes of death in the world. One of the new treatment methods is based on microRNAs, one of which is miRNA 206. The aim of this study was to determine the effect of MIR-206 on Toll-like receptor 2 (TLR2) and TLR4 in the melanoma cell line (A-375). Methods: The present in vitro study was performed on melanoma cancer cells in RPMI640 culture medium containing 10% fetal calf serum at 37 ° C and 5% CO2 . After counting and dividing the cells, the cells inside the plate were stimulated in over time with the MIR-206 protein. Incubation was performed. After 48 hours, the cells were collected, the total mRNA was extracted, and the expression levels of TLR2 and TLR4 were examined by real-time polymerase chain reaction. Results: The results demonstrated that the expression of TLR2 and TLR4 IL6 decreased in the melanoma cell line (A-375) in exposure to MIR-206. The results also showed the expression of nuclear factor kappa B in the melanoma cell line. Conclusion: The findings confirmed the role of MIR-206 as a tumor suppressor in melanoma cancer. These results suggest that MIR-206 may be a new treatment for melanoma in the near future. Accordingly, MIR-206 can be considered a potential target in the gene therapy of patients with melanoma cancer, and one of the advantages of MIR-206 gene therapy in melanoma cancer over chemotherapy is the reduction of cytotoxicity and its invasiveness.    

    

* Switching off Competing Hydrogen Formation in CO2 Electroreduction via Substrate Defect Engineering  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401000461
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Engineering of Surface Nanostructures
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4772767/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401000461"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401000461"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401000461"))][Get cited by]]

OpenAlex: https://openalex.org/W4401000461 (Open access: True)
    
[[https://openalex.org/A5100435866][Lei Wang]], [[https://openalex.org/A5007921737][Haozhou Yang]], [[https://openalex.org/A5048313381][Na Guo]], [[https://openalex.org/A5031292832][Shibo Xi]], [[https://openalex.org/A5037340591][Haiyuan Zou]], [[https://openalex.org/A5100609074][Jiayi Chen]], [[https://openalex.org/A5022239454][Lei Fan]], [[https://openalex.org/A5023257092][Yukun Xiao]], [[https://openalex.org/A5051694258][Qian He]], [[https://openalex.org/A5047901288][Lele Duan]], [[https://openalex.org/A5030557634][Pengfei Wei]], [[https://openalex.org/A5020450516][Guoxiong Wang]], [[https://openalex.org/A5100763540][Chun Zhang]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4772767/v1  ([[https://www.researchsquare.com/article/rs-4772767/latest.pdf][pdf]])
     
Abstract Carbon nanotubes (CNTs) have emerged as effective substrates for immobilizing molecular catalysts towards many electrocatalytic reactions, such as CO2 reduction (CO2R). However, despite the prevailing notion of strong π-π stackings between the molecular catalyst and CNTs, our understanding of their interactions remains inadequate. Here, we employ functionalized nickel phthalocyanines (NiPc), established CO2R catalysts, immobilized on CNTs as a model system to investigate the catalyst/substrate interactions. Firstly, we find that NiPc-catalysts preferentially anchor on the defects on CNTs rather than adhering via π-π interaction with the ideal graphene-like CNT surface, a finding further validated by theoretical simulations. Consequently, we observe the least uniform NiPc-catalysts distributions on CNTs when the defect-content is the lowest. Notably, this combination exhibits the highest CO2R selectivity and activity despite the non-uniform catalyst distributions. Through operando X-ray adsorption spectroscopy and theoretical simulations, we reveal that high CNT defect-contents tend to induce substantial D4h symmetry breaking of the NiPc plane under cathodic potential, consequently resulting in reduced CO2R selectivity and activity. Therefore, maintaining a low to moderate defect level on CNTs is critical. Guided by this understanding, we fine-tune the defect-level of CNTs through graphitization, achieving an unprecedently high selectivity for CO2 to CO conversion (CO to H2 molar ratio exceeding 16100:1, a remarkable suppression of hydrogen evolution by three orders of magnitude) and improved intrinsic-activity (turnover frequency of 1072 s−1 at −0.60 V vs. reversible hydrogen electrode) on an optimized Ni-Pc/CNTs composite. Furthermore, we achieved practical relevant CO production in a zero-gap electrolyzer (electrode size of 100 cm-2), reaching high current (up to 50 A), with high CO selectivity (> 95%) and reasonably low cell voltage (approximately 3.5 V), substantially outperforming the state-of-the-art silver catalyst. Moreover, we extend this knowledge to a Co-based molecular catalyst, achieving a high Faradaic efficiency (over 50%) towards methanol production with a high partial current density over 150 mA cm−2. Overall, our findings underscore the significance of tuning defect levels on CNT substrates for achieving desired performance for immobilized molecular catalysts.    

    

* The metabolic pathways of carbon assimilation and polyhydroxyalkanoate production by Rhodospirillum rubrum in response to different atmospheric fermentation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400947112
:TOPICS: Biodegradable Polymers as Biomaterials and Packaging, Enzyme Immobilization Techniques, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1371/journal.pone.0306222")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400947112"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400947112"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400947112"))][Get cited by]]

OpenAlex: https://openalex.org/W4400947112 (Open access: True)
    
[[https://openalex.org/A5067747192][Min Tang]], [[https://openalex.org/A5080657784][Xin Zhen]], [[https://openalex.org/A5034155842][Guoqiang Zhao]], [[https://openalex.org/A5040155377][Shuang Wu]], [[https://openalex.org/A5100296146][Wei Hua]], [[https://openalex.org/A5066453183][Jun Qiang]], [[https://openalex.org/A5101938511][Yanling Cheng]], [[https://openalex.org/A5036914361][W. Wang]], PLoS ONE. 19(7)] 2024. https://doi.org/10.1371/journal.pone.0306222 
     
The purple nonsulfur bacteria, Rhodospirillum rubrum, is recognized as a potential strain for PHAs bioindustrial processes since they can assimilate a broad range of carbon sources, such as syngas, to allow reduction of the production costs. In this study, we comparatively analyzed the biomass and PHA formation behaviors of R. rubrum under 100% CO and 50% CO gas atmosphere and found that pure CO promoted the PHA synthesis (PHA content up to 23.3% of the CDW). Hydrogen addition facilitated the uptake and utilization rates of CO and elevated 3-HV monomers content (molar proportion of 3-HV up to 9.2% in the presence of 50% H2). To elucidate the genetic events culminating in the CO assimilation process, we performed whole transcriptome analysis of R. rubrum grown under 100% CO or 50% CO using RNA sequencing. Transcriptomic analysis indicated different CO2 assimilation strategy was triggered by the presence of H2, where the CBB played a minor role. An increase in BCAA biosynthesis related gene abundance was observed under 50% CO condition. Furthermore, we detected the α-ketoglutarate (αKG) synthase, converting fumarate to αKG linked to the αKG-derived amino acids synthesis, and series of threonine-dependent isoleucine synthesis enzymes were significantly induced. Collectively, our results suggested that those amino acid synthesis pathways represented a key way for carbon assimilation and redox potential maintenance by R. rubrum growth under syngas condition, which could partly replace the PHA production and affect its monomer composition in copolymers. Finally, a fed-batch fermentation of the R. rubrum in a 3-l bioreactor was carried out and proved H2 addition indeed increased the PHA accumulation rate, yielding 20% ww-1 PHA production within six days.    

    
