#+filetags: CO2RR
#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Sun Feb 11 00:48:02 2024

Found 28 results from 2024-02-04 to 2024-02-11
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Modulation of active center distance of hybrid perovskite for boosting photocatalytic reduction of carbon dioxide to ethylene  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391527790
:TOPICS: Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1073/pnas.2318970121")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391527790"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391527790"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391527790"))][Get cited by]]

OpenAlex: https://openalex.org/W4391527790 (Open access: False)
    
[[https://openalex.org/A5060340851][Linjuan Li]], [[https://openalex.org/A5018013187][Dong Xu]], [[https://openalex.org/A5042815155][Xiankui Xu]], [[https://openalex.org/A5085521958][Zheng Tian]], [[https://openalex.org/A5069616452][Xue Zhou]], [[https://openalex.org/A5077769841][Shenbo Yang]], [[https://openalex.org/A5011328145][Zhonghai Zhang]], Proceedings of the National Academy of Sciences of the United States of America. 121(7)] 2024. https://doi.org/10.1073/pnas.2318970121 
     
Solar-driven photocatalytic CO 2 reduction is an energy-efficient and sustainable strategy to mitigate CO 2 levels in the atmosphere. However, efficient and selective conversion of CO 2 into multi-carbon products, like C 2 H 4 , remains a great challenge due to slow multi-electron-proton transfer and sluggish C–C coupling. Herein, a two-dimensional thin-layered hybrid perovskite is fabricated through filling of oxygen into iodine vacancy in pristine DMASnI 3 (DMA = dimethylammonium). The rational-designed DMASnI 3 (O) induces shrinkage of active sites distance and facilitates dimerization of C–C coupling of intermediates. Upon simulated solar irradiation, the DMASnI 3 (O) photocatalyst achieves a high selectivity of 74.5%, corresponding to an impressive electron selectivity of 94.6%, for CO 2 to C 2 H 4 conversion and an effective C 2 H 4 yield of 11.2 μmol g −1 h −1 . In addition, the DMASnI 3 (O) inherits excellent water stability and implements long-term photocatalytic CO 2 reduction to C 2 H 4 in a water medium. This work establishes a unique paradigm to convert CO 2 to C 2+ hydrocarbons in a perovskite-based photocatalytic system.    

    

* Electrochemical reduction of carbon dioxide to produce formic acid coupled with oxidative conversion of biomass  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391560295
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.01.062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391560295"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391560295"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391560295"))][Get cited by]]

OpenAlex: https://openalex.org/W4391560295 (Open access: False)
    
[[https://openalex.org/A5075320040][Jiashuai Liu]], [[https://openalex.org/A5025761344][Yifan Wang]], [[https://openalex.org/A5040497392][Zhiwei Dai]], [[https://openalex.org/A5014377577][Daihong Gao]], [[https://openalex.org/A5013713303][Xuebing Zhao]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.01.062 
     
Electrochemical reduction of CO2 (CO2RR) has become a research hot spot in recent years in the context of carbon neutrality. HCOOH is one of the most promising products obtained by electrochemical reduction of CO2 due to its high energy value as estimated by market price per energy unit and wide application in chemical industry. Biomass is the most abundant renewable resource in the natural world. Coupling biomass oxidative conversion with CO2RR driven by renewable electricity would well achieve carbon negativity. In this work, we comprehensively reviewed the current research progress on CO2RR to produce HCOOH and coupled system for conversion of biomass and its derivatives to produce value-added products. Sn- and Bi-based electrocatalysts are discussed for CO2RR with regards to the structure of the catalyst and reaction mechanisms. Electro-oxidation reactions of biomass derived sugars, alcohols, furan aldehydes and even polymeric components of lignocellulose were reviewed as alternatives to replace oxygen evolution reaction (OER) in the conventional electrolysis process. It was recommended that to further improve the efficiency of the coupled system, future work should be focused on the development of more efficient and stable catalysts, careful design of the electrolytic cells for improving the mass transfer and development of environment-friendly processes for recovering the formed formate and biomass oxidation products.    

    

* Efficient visible‐light‐driven carbon dioxide reduction by a bioinspired Nickel molecular catalyst  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391597293
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Role of Porphyrins and Phthalocyanines in Materials Chemistry
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202301892")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391597293"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391597293"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391597293"))][Get cited by]]

OpenAlex: https://openalex.org/W4391597293 (Open access: False)
    
[[https://openalex.org/A5012051639][Jing Zhang]], [[https://openalex.org/A5066076190][Ping She]], [[https://openalex.org/A5080328342][Qi Xu]], [[https://openalex.org/A5010693249][Fengkun Tian]], [[https://openalex.org/A5009799106][Heng Rao]], [[https://openalex.org/A5088751445][Jun‐Sheng Qin]], [[https://openalex.org/A5020281878][Julien Bonin]], [[https://openalex.org/A5078358071][Marc Robert]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202301892 
     
Inspired by natural enzymes, this study presents a nickel‐based molecular catalyst, [Ni‖(N2S2)]Cl2 (N2S2 = 2,11‐dithia[3,3](2,6)pyridinophane), for the photochemical catalytic reduction of CO2 under visible light. The catalyst was synthesized and characterized using various techniques, including liquid chromatography‐high resolution mass spectrometry (LC‐HRMS), UV‐Visible spectroscopy, and X‐ray crystallography. The crystallographic analysis revealed a slightly distorted octahedral coordination geometry with a mononuclear Ni2+ cation, two nitrogen atoms and two sulfur atoms. Photocatalytic CO2 reduction experiments were performed in homogeneous conditions using the catalyst in combination with [Ru(bpy)3]Cl2 (bpy = 2,2’‐bipyridine) as a photosensitizer and 1,3‐dimethyl‐2‐phenyl‐2,3‐dihydro‐1H‐benzo[d]imidazole (BIH) as a sacrificial electron donor. The catalyst achieved a high selectivity of 89% towards CO and a remarkable turnover number (TON) of 7991 during 8 h of visible light irradiation under CO2 in the presence of phenol as a co‐substrate. The turnover frequency (TOF) in the initial 6 h was 1079 h‐1, with an apparent quantum yield (AQY) of 1.08%. Controlled experiments confirmed the dependency on the catalyst, light, and sacrificial electron donor for the CO2 reduction process. These findings demonstrate this bioinspired nickel molecular catalyst could be effective for fast and efficient photochemical catalytic reduction of CO2 to CO.    

    

* Covalent Organic Frameworks as Promising Platforms for Efficient Electrochemical Reduction of Carbon Dioxide: A Review  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391611409
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/sstr.202300495")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391611409"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391611409"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391611409"))][Get cited by]]

OpenAlex: https://openalex.org/W4391611409 (Open access: True)
    
[[https://openalex.org/A5071836973][Zihao Chen]], [[https://openalex.org/A5015105154][Nan Li]], [[https://openalex.org/A5027994683][Qichun Zhang]], Small structures. None(None)] 2024. https://doi.org/10.1002/sstr.202300495  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/sstr.202300495][pdf]])
     
In current research, achieving carbon neutrality has become a primary focus through the utilization of various conversion technologies that transform carbon dioxide (CO 2 ) into valuable chemicals or fuels. Covalent organic frameworks (COFs), as emerging crystalline organic polymers, offer distinct advantages in CO 2 conversion compared to other materials. These advantages include controllable nanoscale pores, predefined functional units, editable framework structures, and rich conjugated systems. The unique characteristics of COFs make them highly promising electrocatalysts for CO 2 conversion. This review provides a comprehensive overview of pioneering works and recent research on the utilization of COF‐based materials as electrocatalysts for electrochemical CO 2 reduction reaction. This review offers a comprehensive analysis of the design principles for various reactive sites, skeleton structures, pore functionalities, 3D frameworks, morphologies, and composite materials of COFs, aiming to enhance electrocatalysis. Finally, this review presents some recommendations for material design, reaction mechanisms, and theoretical computations to enhance the understanding of reaction mechanisms further and facilitate the design of high‐performance COF‐based electrocatalysts.    

    

* Synergistic Effect of Phthalocyanine and Pyrochlore-type Oxide Catalysts to Enhance Activity of Electrochemical Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391614705
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/chemle/upae029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391614705"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391614705"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391614705"))][Get cited by]]

OpenAlex: https://openalex.org/W4391614705 (Open access: True)
    
[[https://openalex.org/A5012735404][Riichiroh Maruyama]], [[https://openalex.org/A5001488454][Satoko Takase]], [[https://openalex.org/A5019250083][Youichi Shimizu]], Chemistry Letters. None(None)] 2024. https://doi.org/10.1093/chemle/upae029  ([[https://academic.oup.com/chemlett/advance-article-pdf/doi/10.1093/chemle/upae029/56609787/upae029.pdf][pdf]])
     
Abstract Electrochemical CO2 reduction has been attracting attention due to its impact on the environment. In this study, we found the combination of Co-phthalocyanine and pyrochlore-type Bi2Sn2O7 catalyst gave high catalytic activity for CO2 reduction, and devised a new electrocatalyst that combines them for their synergistic effects.    

    

* Fe0-dependent carbon dioxide reduction to methane via diverse electron transfer pathway in methanogenic community  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391615959
:TOPICS: Microbial Fuel Cells and Electrogenic Bacteria Technology, Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.crsus.2024.100019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391615959"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391615959"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391615959"))][Get cited by]]

OpenAlex: https://openalex.org/W4391615959 (Open access: True)
    
[[https://openalex.org/A5033296587][Tianyu Gao]], [[https://openalex.org/A5016543543][Lichao Xia]], [[https://openalex.org/A5015762746][Hanmin Zhang]], [[https://openalex.org/A5075257427][Ahmed Tawfik]], [[https://openalex.org/A5088311812][Fangang Meng]], Cell Reports Sustainability. None(None)] 2024. https://doi.org/10.1016/j.crsus.2024.100019 
     
In natural and engineered environments, iron biocorrosion is an energy reservoir for growth of methanogens. However, how archaea accept electrons from metallic iron remains enigmatic. Here, we report that a Methanothrix-dominated methanogenic community from anaerobic granular sludge can reduce carbon dioxide (CO2) to methane (CH4) via electron uptake from zero-valent iron (ZVI). Through the batch experiments, a maximum CH4 yield of 40.8 ± 0.6 μeequiv/day and an electron recovery from ZVI oxidation to CH4 generation of 69.7% ± 6.1% are observed. Metagenome analysis and inhibition experiments indicate that electrons released by corrosive bacteria are utilized by Methanothrix for accomplishing CO2-to-CH4 conversion via potential intracellular and extracellular electron transfer. The results of activity tests of four electron donors (i.e., ZVI, stainless steel, H2, and acetate) suggest that the ZVI-dependent methanogenesis dominate the overall CH4 generation compared with hydrogenotrophic and acetoclastic methanogenesis, which provides a new insight into autotrophic metabolism of methanogens.    

    

* Research on photoelectrocatalytic carbon dioxide reduction based on carbon wood photothermal cathode  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391655667
:TOPICS: Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1117/12.3024972")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391655667"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391655667"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391655667"))][Get cited by]]

OpenAlex: https://openalex.org/W4391655667 (Open access: False)
    
[[https://openalex.org/A5071672663][Jun Zhang]], [[https://openalex.org/A5027416449][Tao Li]], [[https://openalex.org/A5091192043][Xiaotian Li]], [[https://openalex.org/A5058908515][Aiqi Fang]], No host. None(None)] 2024. https://doi.org/10.1117/12.3024972 
     
A photothermal electrode was prepared using carbon wood as the substrate and carbon-nitrogen-iron as the catalyst, harnessing the excellent photothermal properties of carbon wood to facilitate CO2 reduction. First, we analyzed the structural features of carbon wood. It possesses an abundance of vertical microchannels that favor material transport. Additionally, its high surface area and mesoporous structure provide suitable sites for the reaction. Secondly, the photothermal properties of carbon wood were investigated, showing its efficient light absorption and photothermal conversion capabilities, allowing effective utilization of solar energy. Finally, a photothermal-assisted CO2 reduction system was constructed, using titanium dioxide as the photoanode and carbon wood loaded with carbon-nitrogen-iron as the photothermal cathode. Solar irradiation effectively increased the reaction temperature, enabling the carbon-nitrogen-iron catalyst, which exhibits a thermal response effect, to perform more efficiently. Further studies revealed that rapid evaporation of the solution at the carbon wood cathode created a favorable three-phase interfacial microenvironment for CO2 reduction, enhancing the reaction efficiency. As a result, the CO yield reached 40.8 μmol cm-2 h-1, which was 5.9 times higher than that achieved under non-photothermal conditions.    

    

* Novel lead-free halide perovskite KMgI3 for photocatalytic hydrogen evolution (HER) and carbon dioxide reduction reaction (CO2RR)  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391667291
:TOPICS: Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.136066")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391667291"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391667291"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391667291"))][Get cited by]]

OpenAlex: https://openalex.org/W4391667291 (Open access: False)
    
[[https://openalex.org/A5046737855][E. Luévano-Hipólito]], [[https://openalex.org/A5092207100][Mayte G. Fabela-Cedillo]], [[https://openalex.org/A5019849239][Leticia M. Torres-Martı́nez]], Materials Letters. 361(None)] 2024. https://doi.org/10.1016/j.matlet.2024.136066 
     
Lead-free magnesium iodide (KMgI3) perovskite films were obtained by ink-jet printing. The halide perovskites were printed in different supports: mica, magnesium oxychloride, and glass. The printed samples were evaluated in photocatalytic hydrogen evolution (HER) and carbon dioxide reduction reaction (CO2RR) to produce alternative solar based fuels, e.g., formic acid (HCOOH) and hydrogen (H2) under visible light. The KMgI3 printed on mica exhibited the highest activity to produce both HCOOH and H2, with apparent quantum yields of 1.02 and 7.86 % at 550 nm, respectively. This result was associated with an enhanced adhesion of the perovskite to mica due to the K+ affinity and a better interaction of the C atom possible due to the depletion of the layer of K+, leading to the exposure of aluminosilicate sheets. The stability of the perovskite was corroborated after three consecutive cycles.    

    

* Two-Dimensional Carbon Nitride as a Support of Single Metal Atom for Carbon Dioxide Reduction Reaction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391637868
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542607mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391637868"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391637868"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391637868"))][Get cited by]]

OpenAlex: https://openalex.org/W4391637868 (Open access: False)
    
[[https://openalex.org/A5075097508][Sergio Posada‐Pérez]], [[https://openalex.org/A5089940148][Anna Vidal López]], [[https://openalex.org/A5035251076][Miquel Solà]], [[https://openalex.org/A5091859825][Albert Poater]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542607mtgabs 
     
Electrochemical conversion of CO 2 into added-value chemicals is an important approach to recycle CO 2 . Heterogeneous catalysis is widely used in industrial applications because of the possibility of facile separation, which reduces the operating costs, although heterogeneous catalysts often have limited selectivity. In contrast, homogeneous catalysts are very selective although they have limited industrial applications due to their cost, the use of precious metals, and the difficulty in separating and recovering the catalysts. Currently, the research community is trying to combine the properties of homogeneous and heterogeneous catalysts. From the heterogeneous catalyst perspective, research has been focused on creating smaller and dispersed catalyst particles. Single-atom catalysts (SACs), which comprise atoms of metal species dispersed on a solid support, are expected to bridge the homogeneous and heterogeneous catalyst properties. The work described herein explores, by means of density functional simulations, the electrocatalytic CO 2 reduction reaction (CO 2 RR) using several single transition metal atoms anchored in 2D graphitic carbon nitride (g-C 3 N 4 ), 1 focusing on the group XI transition metals since they include Cu, the only transition metal capable of reducing CO 2 to hydrocarbons and alcohols with acceptable faradaic efficiencies. Moreover, the Cu 1 /g-C 3 N 4 system has been experimentally evaluated as CO 2 RR electrocatalysts. 2D g-C 3 N 4 has been demonstrated to be a competitive candidate for electrocatalytic CO 2 reduction since it can act as an active support for single metal-atom catalysts, mainly Cu, Pd, and Pt, and the deposition of Au single atom was experimentally characterized. The computational hydrogen electrode model has been used to explore the suitability of several transition metals atoms anchored to C 3 N 4 , showing that single atoms enhance the catalytic activity of the system as the first proton–electron transfer is thermodynamically favored in comparison to bare carbon nitride support. Our theoretical interpretations are consistent with the experimental results using Cu 1 /g-C 3 N 4 , 2 revealing that the competitive H 2 generation is favored due to the strong CO binding energies. This fact reinforced the capability of our computational models to predict the behavior of several single metal atom electrocatalysts to reduce CO 2 , for instance, predicting that Au can promote the methane formation after eight electron-proton transfer processes. Our computational study paves the road to finding suitable metals that catalyze the first proton–electron transfer in the carbon dioxide reduction reaction. Posada-Pérez, A. Vidal-López, M. Solà, and A. Poater, 2023, Phys. Chem. Chem. Phys, 25, 8574. Cometto, A. Ugolotti, E. Grazietti, A. Moretto, G. Bottaro, L. Armelao, C. Di Valentin, L. Calvillo and G. A. Granozzi, npj 2D Mater. Appl. , 2021, 5 , 63. Figure 1    

    

* (Invited) Electrocatalytic Reduction of Carbon Dioxide over Aluminum-Added Coppor Oxide Gas Diffusion Electrode  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391638189
:TOPICS: Gas Sensing Technology and Materials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472364mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638189"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638189"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638189"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638189 (Open access: False)
    
[[https://openalex.org/A5082711943][Tsutomu Minegishi]], [[https://openalex.org/A5017675862][Daisuke Komori]], [[https://openalex.org/A5007438676][H. Ebe]], [[https://openalex.org/A5071307251][Hiromu Kumagai]], [[https://openalex.org/A5043130875][Masakazu Sugiyama]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472364mtgabs 
     
Electrochemical cells are the key technologies for construction of carbon neutral society to produce hydrogen from water and produce useful chemicals from carbon dioxide utilizing renewable energy. Copper species are the unique catalysts for electrochemical carbon dioxide reduction reaction (CO 2 RR) with capable of producing C2+ products such as ethanol and ethylene. Selective production of target chemical is one of the most important requirements for the catalysts, and addition of different elements and surface modifications have been reported to be beneficial for the selective production. In the present study, copper oxides-based catalysts prepared with electroless plating techniques were examined for electrochemical CO 2 RR. To conduct CO 2 RR at relatively high current densities, the catalysts were examined in the form of gas diffusion electrode (GDE). The Cu 2 O based GDE was prepared by the combination of physical vapor deposition and electroless plating on hydrophobized carbon paper coated with mesoporous carbon layer. After the electroless plating treatment, the metal precursors were successfully converted to core-shell structured electrocatalyst with Cu 2 O shell and Cu core. By introducing different elements such as aluminum to the precursor, metallic Cu, the different element added catalysts were successfully prepared in the shape of GDE. Addition of different element significantly improved durability of the core-shell structured catalysts and, as a result, faradaic efficiency of ethylene of 24 hours after starting electrolysis was increase from 32% to 47% under applying cathodic current of 260 mAcm -2 . Further surface modifications with Nafion enhanced the durability and the faradaic efficiency of ethylene maintained >50% for over 48 hours and reached about 60% in maximum. In the presentation, we will discuss about the detailed structure of the electrocatalysts, results of full-cell test, and longer durability test over 100 hours.    

    

* Fabrication of Cu-Single Atom Catalyst Supported on Unique 2D Graphdiyne Analogue-Based Porphyrin Metal Covalent Organic Frameworks for Carbon Dioxide Reduction Application  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391638252
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02572760mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638252"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638252"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638252"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638252 (Open access: False)
    
[[https://openalex.org/A5069237191][Zubair Masaud]], [[https://openalex.org/A5019631104][Haibao Huang]], [[https://openalex.org/A5093888127][Lars Eric-Roseng]], [[https://openalex.org/A5057176376][Kaiying Wang]], ECS Meeting Abstracts. MA2023-02(57)] 2023. https://doi.org/10.1149/ma2023-02572760mtgabs 
     
Excessive burning of fossil fuels for energy production has led to an exponential increase in CO 2 concentrations in the atmosphere, which is the core of universal problems such as global warming and climate change. One of the new approaches to reducing CO 2 emissions is to think of CO 2 as a useful raw material and convert this compound into useful products. Moreover, electrocatalytic carbon dioxide reduction (eCO 2 R) can be conveniently utilized to establish a zero-emission carbon cycle and utilize this CO 2 for energy-dense fuels and other chemical raw materials [1]. However, exploring novel catalysts is the ultimate need of the hour for an effective and efficient eCO 2 R. Heterogeneous single-atom catalysts (SAC) containing isolated metal species on an atomic level are gaining the increasing attention of the scientific community owing to their high metal utilization sites and superior catalytic properties[2]. The SACs are put into the full effect of catalysis by scattering it over conductive support. Therefore, in this work, the copper SACs are supported over a unique porphyrin-based graphdiyne (SAC-PG) with a π-conjugated structure (Figure 1). Graphdiyne possesses two acetylenic linkages between the aromatic rings and is responsible for not only displaying exceptional electronic conductivity but when coupled with the metalloporphyrin network provides numerous active sites for catalysis[3]. This SAC-PG analogue is achieved by a Glaser-Hay coupling reaction on Cu foam or foil. Moreover, SEM analysis is performed in combination with SEM-EDX and elemental mapping to investigate the morphology of the fabricated catalyst (Figure 2). In addition, this unique copper-based SAC-PG is evaluated as a catalyst for eCO 2 R in a customized H-cell with 0.1M/0.5M KHCO 3 as an electrolyte and Pt as a counter electrode. Nafion 117 proton exchange membrane is used for separation between the cathodic and anodic compartments while an Ag/AgCl (3M KCl) was used as a reference electrode. Under these eCO 2 R conditions, the copper SAC-PG catalyst displayed extremely high current densities (32 – 75 mA/cm 2 ) over a range of voltages (1.0-1.2 V vs RHE) and acceptable faradaic efficiencies for the carbon products (with maximum FE over 60% in total for all carbon products). In conclusion, a 2D metal covalent organic framework containing a repeating unit of Cu-porphyrin linked by butadiyne linkages was established. This unique structure showed effective CO 2 R catalysis due to its nanoporous structure, high electronic conductivity, and abundant metal cites utilization. Further optimization and constriction of these easily adjustable catalysts open up various possibilities of further exploration in the field of eCO 2 R. Acknowledgement : The author Zubair Masaud acknowledges support from the Norwegian Micro- and Nano-Fabrication Facility (NorFab, No. 245963/F50) The author Hao Huang acknowledges Marie Skłodowska-Curie Actions individual fellowship CarbonChem 101024758. References [1] I. Ganesh, “Electrochemical conversion of carbon dioxide into renewable fuel chemicals - The role of nanomaterials and the commercialization,” Renew. Sustain. Energy Rev. , vol. 59, pp. 1269–1297, 2016, doi: 10.1016/j.rser.2016.01.026. [2] X. Yang, A. Wang, B. Qiao, and J. U. N. Li, “Single-Atom Catalysts : A New Frontier,” vol. 46, no. 8, 2013. [3] C. Huang et al. , “Progress in Research into 2D Graphdiyne-Based Materials,” Chem. Rev. , vol. 118, no. 16, pp. 7744–7803, 2018, doi: 10.1021/acs.chemrev.8b00288. Figure 1    

    

* (Invited) Electrocatalysts and Processes for Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391638389
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472365mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638389"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638389"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638389"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638389 (Open access: False)
    
[[https://openalex.org/A5038549187][Astrid M. Müller]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472365mtgabs 
     
Efficient and robust electrocatalytic processes that convert climate-damaging carbon dioxide into useful fuels and chemicals are essential to decarbonize our economy. The accelerated discovery of effective catalysts critically depends on rational materials design, predicated on mechanistic and structural understanding of catalysts, electrode–electrolyte interfaces, and mass transport and catalytic processes. New synthetic methods are needed that enable the preparation of tailored multimetallic nanomaterials with precisely controlled properties, for which pulsed laser in liquids synthesis is an ideal tool. Laser-made catalysts are intrinsically more active than analogs made by conventional equilibrium methods.[1] For electrolyzer devices, nanoparticulate catalysts must be immobilized on inert, high surface area carbon substrates for electrocatalysis in aqueous electrolytes. We solved this challenge by preparing carbon fiber paper with intact mesostructures and long-lasting hydrophilicity by a green chemistry process.[2] We developed novel copper-free trimetallic electrocatalysts for aqueous carbon dioxide reduction [3] that produced C–C-coupled products. Systematic variation of metal ratios revealed trends in product distributions. We also assessed gold nanoparticle–hydrophilic carbon fiber paper assemblies with ionomer overlayers for clean syngas generation. Our laser-made catalysts together with the newly developed ability to use them on high surface area electrode supports provide the foundation towards the realization of viable successor technologies. References: [1] R.C. Forsythe, C.P. Cox, M.K. Wilsey, A.M. Müller. Pulsed Laser in Liquids Made Nanomaterials for Catalysis. Chem. Rev. 2021 , 121 , 7568-7637. [2] M.K. Wilsey, K.R. Watson, O.C. Fasusi, B.P. Yegela, C.P. Cox, P.R. Raffaelle, L. Cai, A.M. Müller. Selective Hydroxylation of Carbon Fiber Paper for Long-Lasting Hydrophilicity by a Green Chemistry Process. Adv. Mater. Interfaces 2023 , 10 , 2201684. [3] M.K. Wilsey, C.P. Cox, R.C. Forsythe, L.R. McCarney, A.M. Müller. Selective CO2 reduction towards a single upgraded product: a minireview on multi-elemental copper-free electrocatalysts. Catal. Sci. Technol. 2021 , 11 , 416-424.    

    

* Carbon Supported Pd Nanostructures for Electrochemical Reduction of Carbon Dioxide – Effects of Ozonation  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391638664
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472396mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638664"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638664"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638664"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638664 (Open access: False)
    
[[https://openalex.org/A5055467658][Milla Suominen]], [[https://openalex.org/A5004390138][Lilian Moumaneix]], [[https://openalex.org/A5048774839][Anna A. Kobets]], [[https://openalex.org/A5078947642][Tanja Kallio]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472396mtgabs 
     
Out of the transition metals capable of electrochemical carbon dioxide reduction, Pd is interesting as it can convert carbon dioxide electrochemically into formate or carbon monoxide depending on the applied potential. In fact, it is capable of producing formate at the most positive known potentials that are close to zero overpotentials although at an unfortunately low activity and at the cost of deactivation by carbon monoxide poisoning. One aim is to improve the activity and stability of Pd-based electrocatalysts towards formate production in low overpotentials. As Pd is a critical raw material, we also wish to decrease the amount of Pd required while maintaining high carbon dioxide electroreduction capability. These goals can be achieved by nanostructuring and supporting the Pd catalyst. Here, we have employed a simple wet impregnation synthesis approach to prepare small nanoparticles and nanowires of Pd supported on single walled carbon nanotubes and tested the optimum loading of Pd to obtain high formate yield with improved activity and stability. Reactive sites can be created on the carbon support by subjecting it to ozonation prior to supporting the metal, which may help certain interesting nanostructures, such as nanowires, to grow. Additionally, the oxygen functional groups on the carbon surface are expected to affect the wettability of the electrode which is important for achieving an efficient carbon dioxide electroreduction and a longer-term stability of the reaction. Therefore, we also studied the effects of ozonation of the carbon supports on the electrochemical reduction of carbon dioxide into both formate and syngas (mixture of hydrogen and carbon monoxide) on Pd. Carbon atoms inevitably participate in hydrogen evolution reaction and, thus, in syngas production on Pd-supported catalysts at higher overpotentials. Our results show that ozonation greatly enhances the activity of the catalyst material and improves its stability when applying low overpotentials for formate formation in comparison to the pristine carbon support. The current density on Pd supported ozone treated carbon nanotube material remains stable over 4h of carbon dioxide electrolysis at an applied potential of -0.45 V (vs. RHE) while Pd on pristine carbon support deactivates during the initial 30 min of the experiment. Longer electrolysis times do reveal slow changes in product distribution although activity on ozone-treated single walled carbon nanotube-supported catalyst is excellent. Additionally, the different support materials cause interesting changes in product selectivity upon applying higher overpotentials for the production of syngas. Pd supported on pristine nanotubes produces syngas with carbon monoxide-to-hydrogen ratios of 0.72 and 1.38 at applied potentials of -0.85 V (vs. RHE) and -0.95 V (vs. RHE), respectively, while ozone treated material produces less than 10% of carbon monoxide. Through physico-chemical characterizations of the materials we aim at understanding the observed changes in electrochemical reduction of carbon dioxide on carbon supported Pd nanostructures.    

    

* (Invited) Stabilization and Activation of Copper(I)-Oxide-Semiconducting Interfaces for Photoelectrochemical Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391639053
:TOPICS: Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472360mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391639053"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391639053"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391639053"))][Get cited by]]

OpenAlex: https://openalex.org/W4391639053 (Open access: False)
    
[[https://openalex.org/A5006230670][Paweł J. Kulesza]], [[https://openalex.org/A5012977856][Iwona A. Rutkowska]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472360mtgabs 
     
Electroreduction of carbon dioxide to simple organic fuels and chemicals is a topic of growing scientific and technological interest. The reaction provides means for both reducing emissions of CO 2 into atmosphere and storing renewable energy. The presentation will address low-temperature CO 2 -conversion processes based on electrocatalytic and photoelectrochemical approaches. Among important issues are choice of the catalytic or semiconducting materials, their morphology and operating conditions including temperature, solvent, electrolyte, pH etc. There is a need to improve the reaction dynamics and selectivity toward specific products. In practical electrolysis cells, the CO 2 -reduction (at cathode) is accompanied by water oxidation (at anode or photoanode). Recently, we have concentrated on the development of hybrid materials by utilizing combination of metal oxide semiconductors thus capable of effective photoelectrochemical reduction of carbon dioxide. For example, the combination of conducting polymers, or titanium (IV) oxide, and copper (I) oxide has been considered before and after sunlight illumination. Application of the hybrid system composed of both above-mentioned oxides resulted in high current densities originating from photoelectrochemical reduction of carbon dioxide mostly to methanol (CH 3 OH) as demonstrated upon identification of final products. Among important issue is intentional stabilization, activation, and functionalization of the mixed-metal-oxide-based photoelectrochemcal interface toward better long-term performance and selectivity production of small organic molecules (C1-C4) and other chemicals. In this respect, ultra-thin films of conducting polymers (simple or polyoxometallate-derivatized) and supramolecular complexes (with nitrogen containing ligands and certain transition metal sites), sub-monolayers of metals (Cu, Au), networks of noble metal (Au, Ag) nanoparticles or layers of robust bacterial biofilms have been considered. The photobiocathode utilizing robust biofilms have also been demonstrated to stabilize copper(I) oxide surfaces and to induce the system’s activity toward reduction of carbon dioxide under illuminations with visible light. In the presentation, special attention will be paid to the mechanistic aspects of electroreduction of carbon dioxide, fabrication and characterization of highly selective and durable semiconductor photoelectrode materials and to the importance of the reaction conditions.    

    

* (Invited) Application of Metal Oxide Active Supports for Enhancement of Electrocatalytic Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391663491
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02582797mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663491"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663491"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663491"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663491 (Open access: False)
    
[[https://openalex.org/A5012977856][Iwona A. Rutkowska]], [[https://openalex.org/A5048173874][Anna Chmielnicka]], [[https://openalex.org/A5093893791][Olena Siamuk]], [[https://openalex.org/A5045669575][Karolina Sobkowicz]], [[https://openalex.org/A5022047274][Beata Rytelewska]], [[https://openalex.org/A5006230670][Paweł J. Kulesza]], ECS Meeting Abstracts. MA2023-02(58)] 2023. https://doi.org/10.1149/ma2023-02582797mtgabs 
     
Of particular interest to the preparation of advanced catalytic materials is efficient utilization of catalytic sites (metal and metal oxide nanostructures, their stabilization and intentional activation, as well as organization into two-dimensional arrays, ultra-thin films or three-dimensional networks (e.g. through sequential deposition) on electrode surfaces. They can form nanosized materials with well-defined composition, structure and thickness that exhibit desirable electrocatalytic properties (e.g. toward reduction of CO 2 ). We explore here the ability of polynuclear inorganic metal oxo systems to stabilize and functionalize metal (e.g. copper) nanostructures. Here certain nanostructured metal oxides of zirconium, titanium, zinc or tungsten have been demonstrated to influence supported metal (e.g. Cu, Fe, Ag) centers in ways other than simple dispersion over electrode area. Evidence is presented that the support can modify activity (presumably electronic nature) of the above mentioned catalytic metal nanocenters thus affecting their chemisorptive and catalytic properties. Metal oxide cocatalysts can generate –OH groups at low potentials that induce proton mobility at the photo(electro)chemical interface. Our research interests concern development of systems for the electrocatalytic reduction of carbon dioxide not only in neutral but also in acid media. For example, nanosized Cu or Fe catalytic centers immobilized within ultra-thin films of tungsten oxide or mixed ZrO 2 -WO 3 films have been considered and demonstrated to exhibit synergism during CO 2 -reduction. Selectivity of the catalytic systems largely depends on the activing adsorptive (CO 2 ) phenomena and the affinity of catalytic centers to the adsorbed carbon monoxide (CO) type intermediates leading to their protonation or hydrogenation. Reduction of carbon dioxide begins now at less negative potentials and is accompanied by significant enhancement of the CO 2 -reduction current densities relative to the competitive hydrogen evolution. Among other important issues is the ability of certain metal oxides (e.g., WO 3 ) to affect hydrogen via intra-structural sorption of hydrogen molecules or atoms.    

    

* Sustainable Strategies for Solar Electrochemical Reduction of Carbon Dioxide to Fuels  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391682884
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Fuel Cell Membrane Technology, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2020-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54499/sfrh/bd/147219/2019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391682884"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391682884"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391682884"))][Get cited by]]

OpenAlex: https://openalex.org/W4391682884 (Open access: False)
    
, No host. None(None)] 2020. https://doi.org/10.54499/sfrh/bd/147219/2019 
     
No abstract    

    

* Selective Ethanol Synthesis from Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391606664
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Carbon Dioxide Capture and Storage Technologies, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 1997-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1595/003214097x414166170")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391606664"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391606664"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391606664"))][Get cited by]]

OpenAlex: https://openalex.org/W4391606664 (Open access: False)
    
[[https://openalex.org/A5076484143][Yasuo Izumi]], Platinum Metals Review. 41(4)] 1997. https://doi.org/10.1595/003214097x414166170 
     
Work on the synthesis of ethanol from carbon dioxide over a rhodium-selenium catalyst is reported, and related reactions and characterisation studies are briefly reviewed. In order to inhibit the formation of methane (complete reduction of carbon dioxide) and simultaneously activate carbon-carbon bond formation by the reaction of CH x with carbonyl derivatives, it is necessary to control the active rhodium sites. Based on a study of single crystal rhodium surfaces it is proposed that acetyl and acetate intermediates are formed. Recently it has been discovered that supported Rh/TiO 2 , promoted by selenium from inside the rhodium metal sites, is a potential catalyst for ethanol synthesis from carbon dioxide. The action of this catalyst is compared to related studies.    

    

* Reduction of Carbon Dioxide with Platinum Metals Electrocatalysts  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391626263
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 1989-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1595/003214089x33129")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391626263"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391626263"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391626263"))][Get cited by]]

OpenAlex: https://openalex.org/W4391626263 (Open access: False)
    
[[https://openalex.org/A5002697085][B. Patrick Sullivan]], Platinum Metals Review. 33(1)] 1989. https://doi.org/10.1595/003214089x33129 
     
The reduction of carbon dioxide to fuels and chemicals can be accomplished by the use of electrocatalysts of the platinum group metals. Worthwhile products include carbon monoxide, formate, methanol, methane, oxalate and even higher hydrocarbons depending on the catalyst type and environment. Three classes of electrocatalysts have been identified: catalytic metal surfaces, monomeric solution complexes, and chemically modified electrodes; the latter being a novel hybrid of solid state, surface and homogeneous solution chemistry.    

    

* Carbon Dioxide Reduction on Alloyed Galinstan  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391663508
:TOPICS: Structural Analysis and Design Optimization in Engineering
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472400mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663508"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663508"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663508"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663508 (Open access: False)
    
[[https://openalex.org/A5059375955][Aya Gomaa Abdelkader Mohamed]], [[https://openalex.org/A5017548688][Peter Bogdanoff]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472400mtgabs 
     
Solar powered electrochemical CO₂ reduction to disposable products is presently being developed as one of negative carbon emission technologies 1 . State-of-the-art electrocatalysts are mainly developed for the CO 2 reduction to hydrogen rich products or chemical feedstock materials while for the above-mentioned application solid carbon-rich products are desired (best pure carbon). Even though the formation of solid products is sometimes observed on catalysts (coking effect), this usually leads to an undesirable irreversible deactivation of their solid interfaces. Thus, the development of next generation CO 2 electrocatalysts is demanded based on liquid metal alloys such as galinstan (GaInSn). The advantage of using liquid phase electrodes is to eliminate coking and coarsening limitations that are associated with solid catalysts. For example, it has been reported that ceria-supported liquid galinstan can electrochemically produce carbonaceous materials from CO 2 gas 2 . This shows, that doping with additional active elements can change the CO 2 reduction activity of GaInSn in the direction of other desired products. Our work investigates the activity of galinstan for the electroreduction of CO 2 depending on alloying with additional metals (such as Ce, Ag, Pb). While pure GaInSn shows a predominant activity for the formation of C1 products (CO, HCOOH) in DMF/H 2 O electrolyte, we are mainly interested in the formation of solid carbon or oxalate. Therefore, our investigations aim at finding suitable modifications of GaInSn that achieve high selectivity for these products. Electrochemical analysis coupled with in-line gas chromatography and in-line mass spectroscopy are used to characterize the reactivity. Furthermore, the influence of the water content of the organic electrolyte on the product selectivity will be investigated. In particular, to suppress the observed low hydrogen evolution as a by-product even more efficiently. May, M. M.; Rehfeld, K., Negative Emissions as the New Frontier of Photoelectrochemical CO 2 Reduction. Advanced Energy Materials 2022, 2103801. Esrafilzadeh, D.; Zavabeti, A.; Jalili, R.; Atkin, P.; Choi, J.; Carey, B. J.; Brkljača, R.; O’Mullane, A. P.; Dickey, M. D.; Officer, D. L.; MacFarlane, D. R.; Daeneke, T.; Kalantar-Zadeh, K., Room Temperature CO 2 Reduction to Solid Carbon Species on Liquid Metals Featuring Atomically Thin Ceria Interfaces. Nature Communications 2019, 10 (1), 865. Figure 1    

    

* Biocatalytical reduction of carbon dioxide for sustainable biofuel production  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391681969
:TOPICS: Technologies for Biofuel Production from Biomass, Metabolic Engineering and Synthetic Biology, Enzyme Immobilization Techniques
:PUBLICATION_DATE: 2021-11-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54499/covid/bd/151766/2021")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391681969"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391681969"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391681969"))][Get cited by]]

OpenAlex: https://openalex.org/W4391681969 (Open access: False)
    
, No host. None(None)] 2021. https://doi.org/10.54499/covid/bd/151766/2021 
     
No abstract    

    

* Applications of X-ray Spectroscopy in Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391537296
:TOPICS: Characterization of Shale Gas Pore Structure, Powder Diffraction Analysis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1142/9789811284649_0005")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391537296"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391537296"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391537296"))][Get cited by]]

OpenAlex: https://openalex.org/W4391537296 (Open access: False)
    
[[https://openalex.org/A5055601807][Indrajit Shown]], [[https://openalex.org/A5064071602][Wei-Fu Chen]], [[https://openalex.org/A5059407034][Kuei‐Hsien Chen]], [[https://openalex.org/A5061993606][Li‐Chyong Chen]], World scientific series in nanoscience and nanotechnology. None(None)] 2024. https://doi.org/10.1142/9789811284649_0005 
     
No abstract    

    

* Intercalated Zirconium Phosphate Promotes Reductive Amination of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391686357
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acssuschemeng.3c06479")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391686357"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391686357"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391686357"))][Get cited by]]

OpenAlex: https://openalex.org/W4391686357 (Open access: False)
    
[[https://openalex.org/A5087166125][Huiying Liao]], [[https://openalex.org/A5055700427][Yongjun Jiang]], [[https://openalex.org/A5049066725][Xinjia Wei]], [[https://openalex.org/A5045350805][Xueyan Zhao]], [[https://openalex.org/A5090780152][Lai Wei]], [[https://openalex.org/A5050074954][Ning An]], [[https://openalex.org/A5091735030][Yue Ma]], [[https://openalex.org/A5031493683][Sheng Dai]], [[https://openalex.org/A5023180240][Zhenshan Hou]], ACS Sustainable Chemistry & Engineering. None(None)] 2024. https://doi.org/10.1021/acssuschemeng.3c06479 
     
No abstract    

    

* Computational examination of transition metal-salen complexes for the reduction of CO2  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391706993
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.113819")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391706993"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391706993"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391706993"))][Get cited by]]

OpenAlex: https://openalex.org/W4391706993 (Open access: False)
    
[[https://openalex.org/A5016781296][Gavin McCarver]], [[https://openalex.org/A5077586408][Taner Yildirim]], [[https://openalex.org/A5035646855][Wei Zhou]], Molecular Catalysis. 556(None)] 2024. https://doi.org/10.1016/j.mcat.2024.113819 
     
In this comprehensive study, we investigated the catalytic potential of seven transition metal-salen (TM-salen) complexes for the reduction of carbon dioxide (CO2) using ab initio methods. Our findings revealed distinct catalytic behavior among the TM-salen complexes, driven by their electronic and geometric properties. The reduction of hydrogen to H2 was most favorable on Mn-salen and Cu-salen complexes, indicating potential competition with CO2 reduction. Notably, later TM-salen complexes (Co, Ni, Cu, Zn) exhibited higher energy requirements for the initial CO2 reduction, whereas Mn- and Fe-salen complexes demonstrated potential-controlled selectivity, favoring CO2 reduction beyond HCOOH at specific thresholds. Our results highlight Cr-salen and Fe-salen complexes as promising candidates for the CO2 reduction reaction (CO2RR) catalysts due to their reduced competition with hydrogen reduction and low limiting potentials for CO2 reduction. Furthermore, the distinct reaction profiles of TM-salen complexes offer valuable insights for the design and development of efficient catalysts for sustainable CO2 conversion and other chemical transformations. These findings provide a foundation for further exploration and optimization of TM-salen complexes as viable catalysts in environmental and energy-related applications.    

    

* Development of carbon based materials for CO2 electrochemical reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391704728
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2020-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54499/sfrh/bd/143490/2019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391704728"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391704728"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391704728"))][Get cited by]]

OpenAlex: https://openalex.org/W4391704728 (Open access: False)
    
, No host. None(None)] 2020. https://doi.org/10.54499/sfrh/bd/143490/2019 
     
No abstract    

    

* Metal-organic framework composites for electrochemical CO2 reduction reaction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391515522
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.126532")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391515522"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391515522"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391515522"))][Get cited by]]

OpenAlex: https://openalex.org/W4391515522 (Open access: False)
    
[[https://openalex.org/A5068670506][Kayode Adesina Adegoke]], [[https://openalex.org/A5008185576][Joshua O. Ighalo]], [[https://openalex.org/A5000341829][Jeanet Conradie]], [[https://openalex.org/A5091087628][Chinemerem Ruth Ohoro]], [[https://openalex.org/A5002534407][James F. Amaku]], [[https://openalex.org/A5019730915][Kabir O. Oyedotun]], [[https://openalex.org/A5041855090][Nobanathi Wendy Maxakato]], [[https://openalex.org/A5042386386][Kovo G. Akpomie]], [[https://openalex.org/A5057047276][Emmanuel Sunday Okeke]], [[https://openalex.org/A5018863848][Chijioke Olisah]], [[https://openalex.org/A5021557399][Alhadji Malloum]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.126532 
     
Carbon dioxide (CO2) levels in the atmosphere are quickly increasing as a consequence of anthropogenic activities, which present grave hazards and dangerous circumstances to not only humanity but also the ecosystem. Currently, electrochemical CO2 conversion to chemical/fuels remains one of the best methods for minimizing CO2 concentrations. Metal-organic frameworks (MOFs) composite materials have been considered as new class of highly-performed electrocatalysts for CO2 reduction reaction (CO2RR) due to their wide surface area, higher porosity, chemical tunability and excellent stability. This article presents major approaches for electrochemical CO2RR to value-added product. These were followed by discussing the recent advancements in MOF composite electrocatalysts for CO2RR including active sites MOF-supported electrocatalysts, metal-nanoparticles-supported MOFs, conductive supported MOFs composites, and polyoxometalate-based MOF composites. Lastly, some challenges currently facing MOF composites for CO2RR as well as anticipated future advances were discussed. Research hotspot lies in the creation of highly effective CO2RR electrocatalyst such as ligand engineering in MOFs. It is believed that the current study will contribute to accelerating the fabrication of efficient MOF composite materials for abating the CO2 emission in the ecosystem and to highlight the necessity for further research to address significant environmental sustainability concerns.    

    

* Efficient reduction of CO2 to CO by CdAl-LDHs nanostructured electrocatalysts in ionic liquids  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391543242
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jphotochem.2024.115518")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391543242"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391543242"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391543242"))][Get cited by]]

OpenAlex: https://openalex.org/W4391543242 (Open access: False)
    
[[https://openalex.org/A5029837106][Fang Tan]], [[https://openalex.org/A5031213658][Tianxia Liu]], [[https://openalex.org/A5088260235][Jian Ping Zhang]], Journal of Photochemistry and Photobiology A: Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jphotochem.2024.115518 
     
Layered bimetallic hydroxides are at the forefront of current research in electrocatalytic materials. Although there is considerable research on various bimetallic hydroxides, the study of bimetallic hydroxides for electrocatalytic reduction of carbon dioxide is limited. In this paper, cadmium-aluminum layered bimetallic hydroxide nanoparticles (CdAl-LDHs) were prepared using a simple electrochemical deposition method. The prepared CdAl-LDHs was characterized in detail, and its potential application as an electrocatalyst was discussed. CdAl-LDHs prepared using different methods showed different selectivity in the electrocatalytic reduction of CO2 to CO. The nanomaterial exhibits excellent CO selectivity in a reaction chamber using 2 %-BMIM(PF6)(1-butyl-3-methylimidazolium hexafluorophosphate)/DMF(N-N dimethyl formamide) as the electrolyte. The CdAl-LDHs prepared by electrochemical deposition exhibited a maximum CO partial current density of 22.13 mA cm−2 with a remarkable CO Faraday efficiency (FE) of 99.71 %, which is comparable to or even higher than that of noble metal catalysts. This high selectivity for CO indicates its potential as an alternative to expensive noble metal catalysts. Moreover, the catalyst demonstrated high stability over 30 h of continuous operation with stable FE of around 99 % and a current density of around 10.5 mA cm−2, with minimal degradation during the entire reaction cycle. In addition, the catalyst showed a low HER current density of less than 0.1 mA cm−2 at all tested potentials, indicating that the catalyst maintains a high level of CO2 conversion over the entire range of tested potentials. This suggests its great potential for industrial applications.    

    

* Beyond C–C coupling in CO2 reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391642660
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s44286-023-00019-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391642660"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391642660"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391642660"))][Get cited by]]

OpenAlex: https://openalex.org/W4391642660 (Open access: False)
    
[[https://openalex.org/A5079572594][Yuting Xu]], [[https://openalex.org/A5072657571][Fanglin Che]], Nature Chemical Engineering. 1(2)] 2024. https://doi.org/10.1038/s44286-023-00019-9 
     
No abstract    

    

* (Keynote) Reversible CO2 Reduction Electrocatalysis in Solar-Powered Chemistry  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391639103
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02522517mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391639103"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391639103"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391639103"))][Get cited by]]

OpenAlex: https://openalex.org/W4391639103 (Open access: False)
    
[[https://openalex.org/A5026491082][Erwin Reisner]], ECS Meeting Abstracts. MA2023-02(52)] 2023. https://doi.org/10.1149/ma2023-02522517mtgabs 
     
Semi-artificial photosynthesis interfaces biological catalysts with synthetic materials such as electrodes or light absorbers to overcome limitations in natural and artificial photosynthesis. The benefit of using biocatalysts in electrocatalytic CO2 reduction is their electrochemical reversibility that enables their operation at very low overpotentials with high selectivity. This presentation will summarise my research group’s progress in integrating the CO2 reducing enzyme formate dehydrogenase into bespoke hierarchical 3D electrode scaffolds and the exploitation in solar-powered catalysis. I will present the electrochemical features and characterisation of the biocatalyst-material interface and provide my team's understanding of the electrochemical properties of the immobilised formate dehydrogenase. This insight allows the wiring of the biocatalyst into electrocatalytic schemes, photoelectrochemical devices and photocatalytic systems for unique CO2 utilisation reactions. The fundamental insights gained by integrating isolated formate dehydrogenase in electrodes will be presented and the case be made that this enzyme allows opening a solar-to-chemical conversion space that is currently not accessible with purly synthetic or biological catalysts (see uploaded Image as example). Recent publications: (1) Lam et al., Angew. Chem. Int. Ed., 2023, in print. (2) Bhattacharjee et al., Nat. Synth., 2023, 2, 182-92. (3) Badiani et al., J. Am. Chem. Soc., 2022, 144, 14207-16. (4) Cobb et al., Nat. Chem., 2022, 14, 417-24. (5) Edwardes Moore et al., Proc. Natl. Acad. Sci. USA, 2022, 119, e2114097199. (6) Anton Garcia et al., Nat. Synth. 2022, 1, 77-86. Reviews: (1) Fang et al., Chem. Soc. Rev., 2020, 49, 4926–52. (2) Zhang & Reisner, Nature Rev. Chem., 2020, 4, 6–21. (3) Kornienko et al., Acc. Chem. Res., 2019, 52, 1439–44. (4) Kornienko et al., Nature Nanotech., 2018, 13, 890–99    

    
