#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Fri Apr  5 00:45:01 2024

Found 32 results from 2024-03-29 to 2024-04-05
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Recent Progress on the Surface and Bulk Modification of Carbon Nitrides for Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393276940
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ente.202400136")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393276940"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393276940"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393276940"))][Get cited by]]

OpenAlex: https://openalex.org/W4393276940 (Open access: False)
    
[[https://openalex.org/A5059973732][Sisi Ma]], [[https://openalex.org/A5034242615][Shuaipeng Wang]], [[https://openalex.org/A5029403476][Xin Wang]], [[https://openalex.org/A5043018151][Songcan Wang]], Energy technology (Weinheim. Print). None(None)] 2024. https://doi.org/10.1002/ente.202400136 
     
Photocatalytic CO 2 reduction has been considered as a green and sustainable approach to solve energy and environmental problems. However, the CO 2 reduction efficiency of various types of semiconductor photocatalysts studied at this stage is far from realizing practical applications. The challenge of photocatalytic CO 2 reduction is to design photocatalysts with excellent catalytic performance. This article summarizes the carbon nitride materials for efficient CO 2 reduction and obtaining high value‐added products. The physicochemical properties of carbon nitride materials are discussed in terms of the photocatalytic mechanisms (bandgap tuning, high specific surface area, shorter electron–hole transmission paths, increasing the number of active sites, etc.). The present review provides the latest research progress of carbon nitride modification strategies. The prospects and challenges for the application of carbon nitride materials for CO 2 reduction are presented. This review article will provide useful guidance for further research on carbon nitride materials for efficient photocatalytic CO 2 reduction.    

    

* Electronic Structure Design of Transition Metal-Based Catalysts for Electrochemical Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393277737
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Thermoelectric Materials
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.4c01456")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393277737"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393277737"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393277737"))][Get cited by]]

OpenAlex: https://openalex.org/W4393277737 (Open access: True)
    
[[https://openalex.org/A5066488748][Liang Guo]], [[https://openalex.org/A5025709244][Jingwen Zhou]], [[https://openalex.org/A5041781809][Fu Liu]], [[https://openalex.org/A5005566472][Xiangchuan Meng]], [[https://openalex.org/A5085300962][Yangbo Ma]], [[https://openalex.org/A5052246820][Fengkun Hao]], [[https://openalex.org/A5011847790][Yi Xiong]], [[https://openalex.org/A5065739319][Zhanxi Fan]], ACS nano. None(None)] 2024. https://doi.org/10.1021/acsnano.4c01456  ([[https://pubs.acs.org/doi/pdf/10.1021/acsnano.4c01456][pdf]])
     
No abstract    

    

* Ladder type covalent organic frameworks constructed with natural units for the oxygen and carbon dioxide reduction reactions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393282347
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Chemistry and Applications of Metal-Organic Frameworks, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150812")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393282347"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393282347"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393282347"))][Get cited by]]

OpenAlex: https://openalex.org/W4393282347 (Open access: False)
    
[[https://openalex.org/A5060008686][Minghao Liu]], [[https://openalex.org/A5090717104][Shuai Yang]], [[https://openalex.org/A5015297626][Yubin Fu]], [[https://openalex.org/A5032456464][Xiubei Yang]], [[https://openalex.org/A5076573585][Xuewen Li]], [[https://openalex.org/A5048468640][Jun He]], [[https://openalex.org/A5069765087][Qing Xu]], [[https://openalex.org/A5028394871][Gaofeng Zeng]], Chemical engineering journal (1996. Print). None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150812 
     
Covalent organic frameworks (COFs) constructed with metallocyclophane units and organic linkers have found application as electrocatalytic systems. Nevertheless, the majority of linkers within COFs necessitate intricate design and synthesis. Conversely, the potential utilization of natural building blocks in COF construction remains largely unexplored. In this study, we constructed a natural COF (CoPc-EA-COF) by employing a natural phenolic molecule (ellagic acid (EA)) as the linker and Co-hexadecafluorophthalocyanine (CoPc) as blocks. This framework serves as an electrocatalyst for both the oxygen reduction reaction (ORR) and carbon dioxide reduction reaction (CO2RR). The incorporation of EA units imparts the CoPc-EA-COF with elevated electronic conductivity, enhanced CO2 binding affinity, and superior reductive capacity compared to the controlled COF lacking EA units. The CoPc-EA-COF demonstrated enhanced performance in the ORR, as evidenced by a half-wave potential of 0.80 V. Moreover, it showcased elevated activity and selectivity in the CO2RR, achieving a maximum CO faradic efficiency of 97.32 % at − 0.8 V, along with turnover frequency (TOF) values reaching 2092 h−1. Theoretical calculations revealed that the presence of EA units facilitated the generation of OOH* and COOH* species, which are pivotal in the rate-determining stages of both ORR and CO2RR processes. The contribution of EA units significantly bolstered the overall catalytic activity.    

    

* The reduction mechanism of C1 product from carbon dioxide catalyzed by Ni-doped g-C3N4  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393305887
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.114064")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393305887"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393305887"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393305887"))][Get cited by]]

OpenAlex: https://openalex.org/W4393305887 (Open access: False)
    
[[https://openalex.org/A5060962249][Shuwei Zhang]], [[https://openalex.org/A5051223797][Hai Feng]], [[https://openalex.org/A5022640003][Chenyu Li]], [[https://openalex.org/A5081363438][Xihua Cao]], [[https://openalex.org/A5055839024][Hui Li]], [[https://openalex.org/A5059819025][Yang Wu]], Molecular catalysis (Online). 559(None)] 2024. https://doi.org/10.1016/j.mcat.2024.114064 
     
This work employs density functional theory (DFT) to scrutinize the catalytic efficacy of nano nickel (Ni) clusters supported by graphitic carbon nitride (Nin@g-C3N4, where n ranges from 1 to 6) in the context of the CO2 reduction reaction (CO2RR). Structural examination revealed that Nin@g-C3N4 possesses a substantial binding energy (-1.63 eV to -7.72 eV), confirming the structural stability of the catalyst in the CO2RR. Electronic structure analysis revealed a pronounced orbital overlap near the Fermi level between the 3d orbital of Ni atoms and the 2p orbital of adjacent cavity nitrogen atoms in Nin@g-C3N4. Further insights are gleaned from the calculations of the Bader charge and energy band, indicating significant charge transfer and band gap alteration, suggesting enhanced conductivity due to Ni doping on g-C3N4. The catalytic performance in the CO2RR is predominantly influenced by the size of the doped Ni clusters. The Ni4@g-C3N4 cluster demonstrated optimal efficiency in producing formic acid (HCOOH) with a limiting potential of -0.12 V. In contrast, the Ni5@g-C3N4 cluster excels in methane (CH4) formation, with a limiting potential of -0.35 V. Additionally, these catalysts exhibit marked inhibition of the hydrogen evolution reaction, further underscoring their potential in CO2RR applications.    

    

* Investigation of iron oxide supported on activated coke for catalytic reduction of sulfur dioxide by carbon monoxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393306954
:TOPICS: Desulfurization Technologies for Fuels, Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jaap.2024.106488")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393306954"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393306954"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393306954"))][Get cited by]]

OpenAlex: https://openalex.org/W4393306954 (Open access: False)
    
[[https://openalex.org/A5016354285][Shanchuan Li]], [[https://openalex.org/A5076273742][Tai Feng]], [[https://openalex.org/A5044451841][Qiwen Kong]], [[https://openalex.org/A5027835055][Jun Li]], [[https://openalex.org/A5031500475][Peiyi Liu]], [[https://openalex.org/A5090322041][Peng Ni]], [[https://openalex.org/A5046573151][Cuiping Wang]], Journal of analytical and applied pyrolysis (Print). None(None)] 2024. https://doi.org/10.1016/j.jaap.2024.106488 
     
In view of the low utilization rate of by-product in limestone-gypsum wet flue gas desulfurization process, a method of catalytic reduction of SO2 to elemental sulfur was proposed. In this work, supported iron catalyst using activated coke as supporter was prepared and characterized. Moreover, the performance of SO2 reduction using CO as reducing agent at various Fe loadings, temperatures, gaseous hourly space velocities and CO/SO2 molar ratios was studied. Research shows that, compared with other metals, the highest catalytic activity is achieved over Fe-based catalyst. The iron sulfide is the main active component during the catalytic reduction reaction, hence the catalyst needs to be presulfided before use. The micropores of activated coke become more abundant after loading Fe, whereas excessive increase of Fe loading may bloke the mesopores and weaken the catalytic activity. Higher reaction temperature, lower GHSV and a stoichiometric molar ratio are conducive to the improvement of SO2 conversion and S yield. The catalytic performance at lower temperatures was further improved by loading Co. When the Co loading is 4 wt.%, the SO2 conversion rate reaches 90.9% at 400 °C because loading Co enhances the redox performance of the catalyst surface. The findings are instructive for the development of cost-effective carbon-based catalysts for resource recovery of sulfur.    

    

* Membrane contactor-photocatalytic hybrid system for carbon dioxide capture and conversion to formic acid  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393359313
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.rineng.2024.102085")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393359313"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393359313"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393359313"))][Get cited by]]

OpenAlex: https://openalex.org/W4393359313 (Open access: True)
    
[[https://openalex.org/A5011994599][Andi Rina Ayu Astuti]], [[https://openalex.org/A5036754998][Wibawa Hendra Saputera]], [[https://openalex.org/A5085718408][Danu Ariono]], [[https://openalex.org/A5057233335][I Gede Wenten]], [[https://openalex.org/A5015596389][Dwiwahju Sasongko]], Results in engineering. None(None)] 2024. https://doi.org/10.1016/j.rineng.2024.102085 
     
The escalating demand for Carbon Capture and Utilization (CCU) schemes to mitigate CO2 emissions has propelled research into more efficient methods of CO2 conversion, such as the production of formic acid. While traditional approaches often require harsh operating conditions and substantial energy inputs, photocatalysis offers a promising alternative by harnessing CO2, water, and light for formic acid production. This study evaluates the performance and reaction kinetics of CO2 capture and conversion to formic acid using an integrated membrane contactor and photocatalytic process. Investigation into various CO2 absorbents and reduction catalysts reveals that TEA achieves a CO2 loading of 0.957 moles of CO2/mole of solvent, while NaOH achieves 0.75 moles of CO2/mole of solvent over a 4-hour operation period. Subsequent photoreduction of CO2 results in formic acid concentration of 15.89 ppm using ZnO and 10.16 ppm using TiO2 within the same 4-hour operation period at a gas flow rate of 800 ml/min. The rate of CO2 photoreduction to formic acid emerges as the limiting factor in this integrated process, indicating a need for further optimization. Key parameters identified for optimal performance include a UV source of 500 W, a medium pH of 10, and a catalyst loading of 0.5 g/L. This study contributes to the advancement of CCU technologies by demonstrating the feasibility of integrating CO2 capture and photoreduction using membrane contactors and photocatalytic systems, paving the way for sustainable formic acid production.    

    

* Supported Tetra-Atom Clusters on G-Cn as Catalysts for Electrochemical Reduction of Carbon Dioxide: A Computational Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393376349
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4780685")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393376349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393376349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393376349"))][Get cited by]]

OpenAlex: https://openalex.org/W4393376349 (Open access: False)
    
[[https://openalex.org/A5090183816][Wenjing Zhou]], [[https://openalex.org/A5054752343][Xuxin Kang]], [[https://openalex.org/A5039404041][Shan Gao]], [[https://openalex.org/A5000121893][Xiangmei Duan]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4780685 
     
No abstract    

    

* Size‐Dependent Multi‐Electron Donation in Metal‐Complex Quantum Dots Hybrid Catalyst for Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393436393
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202315734")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393436393"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393436393"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393436393"))][Get cited by]]

OpenAlex: https://openalex.org/W4393436393 (Open access: True)
    
[[https://openalex.org/A5086692009][Qian Zhao]], [[https://openalex.org/A5051698444][Mohamed Abdellah]], [[https://openalex.org/A5028237878][Yuehan Cao]], [[https://openalex.org/A5085838387][Jie Meng]], [[https://openalex.org/A5071070148][Xianshao Zou]], [[https://openalex.org/A5043034054][Kasper Enemark‐Rasmussen]], [[https://openalex.org/A5077056504][Weihua Lin]], [[https://openalex.org/A5064842058][Yang Li]], [[https://openalex.org/A5005806536][Yijiang Chen]], [[https://openalex.org/A5024334337][Hengli Duan]], [[https://openalex.org/A5071062593][Qinying Pan]], [[https://openalex.org/A5071872950][Ying Zhou]], [[https://openalex.org/A5026895728][Tönu Pullerits]], [[https://openalex.org/A5065493202][Hong Xu]], [[https://openalex.org/A5058674838][Sophie E. Canton]], [[https://openalex.org/A5022908218][Yuran Niu]], [[https://openalex.org/A5045655676][Kaibo Zheng]], Advanced functional materials (Print). None(None)] 2024. https://doi.org/10.1002/adfm.202315734  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/adfm.202315734][pdf]])
     
Abstract The effective conversion of carbon dioxide (CO 2 ) into valuable chemical fuels relies significantly on the donation of multiple electrons. Its efficiency is closely linked to both the density and lifetime of excited charge carriers. In this study, a hybrid catalyst system comprising covalently bonded InP/ZnS quantum dots (QDs) and Re‐complexes is showcased. The electronic band alignment between the QDs and the Re‐complexes is revealed to dominate the multi‐electron transfer process for photocatalytic conversion to methane (CH 4 ). Notably, the size of the QDs is found to be a determining parameter. Among the three QD sizes investigated, transient absorption spectroscopy studies unveil that rapid multi‐electron transfer from the QDs to the Re‐catalyst occurs in smaller QDs (2.3 nm) due to the substantial driving force. Consequently, the photocatalytic conversion of CO 2 to CH 4 is significantly enhanced with a turnover number of 6, corresponding to the overall apparent quantum yield of ≈1%. This research underscores the possibilities of engineering multi‐electron transfer by manipulating the electronic band alignment within a catalytic system. This can serve as a guide for optimizing photocatalytic CO 2 reduction.    

    

* Efficient Electrochemical Co‐Reduction of Carbon Dioxide and Nitrate to Urea with High Faradaic Efficiency on Cobalt‐Based Dual‐Sites  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393549453
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202401221")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393549453"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393549453"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393549453"))][Get cited by]]

OpenAlex: https://openalex.org/W4393549453 (Open access: False)
    
[[https://openalex.org/A5003667516][Xiaoya Fan]], [[https://openalex.org/A5043749799][Chaozhen Liu]], [[https://openalex.org/A5027180761][Xun He]], [[https://openalex.org/A5084960189][Zixiao Li]], [[https://openalex.org/A5085471409][Luchao Yue]], [[https://openalex.org/A5055127644][Wenxi Zhao]], [[https://openalex.org/A5027835055][Jun Li]], [[https://openalex.org/A5003642180][Yan Wang]], [[https://openalex.org/A5049557574][Tingshuai Li]], [[https://openalex.org/A5087989980][Yongsong Luo]], [[https://openalex.org/A5035861129][Dewen Zheng]], [[https://openalex.org/A5086150710][Shengjun Sun]], [[https://openalex.org/A5000510528][Qian Liu]], [[https://openalex.org/A5072563150][Luming Li]], [[https://openalex.org/A5056008057][Wei Chu]], [[https://openalex.org/A5077262940][Feng Gong]], [[https://openalex.org/A5039028486][Bo Tang]], [[https://openalex.org/A5084708809][Yongchao Yao]], [[https://openalex.org/A5073001285][Xuping Sun]], Advanced materials (Weinheim. Print). None(None)] 2024. https://doi.org/10.1002/adma.202401221 
     
Abstract Renewable electricity‐powered nitrate/carbon dioxide co‐reduction reaction toward urea production paves an attractive alternative to industrial urea processes and offers a clean on‐site approach to closing the global nitrogen cycle. However, its large‐scale implantation is severely impeded by challenging C‐N coupling and requires electrocatalysts with high activity/selectivity. Here, cobalt‐nanoparticles anchored on carbon nanosheet (Co NPs@C) is proposed as a catalyst electrode to boost yield and Faradaic efficiency (FE) toward urea electrosynthesis with enhanced C‐N coupling. Such Co NPs@C renders superb urea‐producing activity with a high FE reaching 54.3% and a urea yield of 2217.5 μg h –1 mg cat. –1 , much superior to the Co NPs and C nanosheet counterparts, and meanwhile shows strong stability. The Co NPs@C affords rich catalytically active sites, fast reactants diffusion, and sufficient catalytic surfaces‐electrolyte contacts with favored charge and ion transfer efficiencies. The theoretical calculations reveal that the high‐rate formation of *CO and *NH 2 intermediates is crucial for facilitating urea synthesis. This article is protected by copyright. All rights reserved    

    

* Recent advances and perspectives in carbon nanotube production from the electrochemical conversion of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393854161
:TOPICS: Electrochemical Reduction in Molten Salts, Electrochemical Reduction of CO2 to Fuels, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcou.2024.102745")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393854161"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393854161"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393854161"))][Get cited by]]

OpenAlex: https://openalex.org/W4393854161 (Open access: True)
    
[[https://openalex.org/A5094354270][I Ketut Rai Asmara Dipta]], [[https://openalex.org/A5004886231][Chan Woo Lee]], Journal of CO2 utilization (Print). 82(None)] 2024. https://doi.org/10.1016/j.jcou.2024.102745 
     
No abstract    

    

* Data from: Role of mass transport in electrochemical carbon dioxide reduction to methanol using immobilized cobalt phthalocyanine  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393669259
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2023-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.10251835")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393669259"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393669259"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393669259"))][Get cited by]]

OpenAlex: https://openalex.org/W4393669259 (Open access: True)
    
[[https://openalex.org/A5057399487][Thomas Chan]], [[https://openalex.org/A5091102586][Calton Kong]], [[https://openalex.org/A5083305786][Alex J. King]], [[https://openalex.org/A5000440178][Rajiv Prabhakar]], [[https://openalex.org/A5037047569][Finn Babbe]], [[https://openalex.org/A5000007576][Clifford P. Kubiak]], [[https://openalex.org/A5070081966][Joel W. Ager]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2023. https://doi.org/10.5281/zenodo.10251835 
     
Cell files.zip .dwg files of the pocket for the cathode and anode chamber. .dwg files of the gasket design Experimental data.zip (>60 experiments) Chronoamperometry data Each experiment has a mpr and txt file. The .mpr file can be read by EC-lab software, while the txt file has the raw data. H-NMR data Each experiment has its own folder, then another folder with the experiment number. Within that experiment number folder is .fid file needed to view the H-NMR data. Gas Chromatography data Each experiment has its own folder. the files can be opened using SRI proprietary software. There are also .log files which contain the results of each experiment as the raw data.    

    

* Data from: Role of mass transport in electrochemical carbon dioxide reduction to methanol using immobilized cobalt phthalocyanine  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393724552
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2023-12-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.10251836")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393724552"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393724552"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393724552"))][Get cited by]]

OpenAlex: https://openalex.org/W4393724552 (Open access: True)
    
[[https://openalex.org/A5057399487][Thomas Chan]], [[https://openalex.org/A5091102586][Calton Kong]], [[https://openalex.org/A5083305786][Alex J. King]], [[https://openalex.org/A5000440178][Rajiv Prabhakar]], [[https://openalex.org/A5037047569][Finn Babbe]], [[https://openalex.org/A5000007576][Clifford P. Kubiak]], [[https://openalex.org/A5070081966][Joel W. Ager]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2023. https://doi.org/10.5281/zenodo.10251836 
     
Cell files.zip .dwg files of the pocket for the cathode and anode chamber. .dwg files of the gasket design Experimental data.zip (>60 experiments) Chronoamperometry data Each experiment has a mpr and txt file. The .mpr file can be read by EC-lab software, while the txt file has the raw data. H-NMR data Each experiment has its own folder, then another folder with the experiment number. Within that experiment number folder is .fid file needed to view the H-NMR data. Gas Chromatography data Each experiment has its own folder. the files can be opened using SRI proprietary software. There are also .log files which contain the results of each experiment as the raw data.    

    

* Photo-electrochemical reduction of Water and Carbon Dioxide enhanced by molecular catalysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393407690
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Microbial Fuel Cells and Electrogenic Bacteria Technology
:PUBLICATION_DATE: 2016-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393407690"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393407690"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393407690"))][Get cited by]]

OpenAlex: https://openalex.org/W4393407690 (Open access: False)
    
[[https://openalex.org/A5032211592][A. Villagra]], HAL (Le Centre pour la Communication Scientifique Directe). None(None)] 2016. None 
     
No abstract    

    

* Selective electrocatalytic reduction of carbon dioxide on gas diffusion electrodes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393712356
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2014-10-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393712356"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393712356"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393712356"))][Get cited by]]

OpenAlex: https://openalex.org/W4393712356 (Open access: True)
    
[[https://openalex.org/A5035287118][Ziad Bitar]], No host. None(None)] 2014. None  ([[https://theses.hal.science/tel-01555683/document][pdf]])
     
No abstract    

    

* Synthesis, study and characterization of new molecular catalysts for reduction of carbon dioxide with a view to use it as a carbon source.  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393356945
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2012-11-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393356945"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393356945"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393356945"))][Get cited by]]

OpenAlex: https://openalex.org/W4393356945 (Open access: False)
    
[[https://openalex.org/A5058725002][Marc Bourrez]], HAL (Le Centre pour la Communication Scientifique Directe). None(None)] 2012. None 
     
No abstract    

    

* Poly-Amide Modified Copper Foam Electrodes For Enhanced Electrochemical Reduction Of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393481976
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Materials for Electrochemical Supercapacitors, Conducting Polymer Research
:PUBLICATION_DATE: 2018-03-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.1183430")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393481976"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393481976"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393481976"))][Get cited by]]

OpenAlex: https://openalex.org/W4393481976 (Open access: True)
    
[[https://openalex.org/A5087770508][Sunyhik D. Ahn]], [[https://openalex.org/A5028614270][Konstantin Klyukin]], [[https://openalex.org/A5020312033][Russell J. Wakeham]], [[https://openalex.org/A5072254299][Jennifer A. Rudd]], [[https://openalex.org/A5005190526][Aled R. Lewis]], [[https://openalex.org/A5066970619][Shirin Alexander]], [[https://openalex.org/A5010329143][Francesco Carlà]], [[https://openalex.org/A5018264718][Vitaly Alexandrov]], [[https://openalex.org/A5007335678][Enrico Andreoli]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2018. https://doi.org/10.5281/zenodo.1183430 
     
Dataset for the paper "Poly-Amide Modified Copper Foam Electrodes for Enhanced Electrochemical Reduction of Carbon Dioxide". It includes data from: Electrochemistry, Gas Chromatography, Scanning Electron Microscopy/Energy-Dispersive X-ray Spectroscopy, X-Ray Photoelectron Spectroscopy, Nuclear Magnetic Resonance Spectroscopy, Ex-situ and In-situ Synchrotron X-Ray Diffraction, and DFT computations.    

    

* Poly-Amide Modified Copper Foam Electrodes For Enhanced Electrochemical Reduction Of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393503201
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Materials for Electrochemical Supercapacitors, Conducting Polymer Research
:PUBLICATION_DATE: 2018-03-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.1183429")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393503201"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393503201"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393503201"))][Get cited by]]

OpenAlex: https://openalex.org/W4393503201 (Open access: True)
    
[[https://openalex.org/A5087770508][Sunyhik D. Ahn]], [[https://openalex.org/A5028614270][Konstantin Klyukin]], [[https://openalex.org/A5020312033][Russell J. Wakeham]], [[https://openalex.org/A5072254299][Jennifer A. Rudd]], [[https://openalex.org/A5005190526][Aled R. Lewis]], [[https://openalex.org/A5066970619][Shirin Alexander]], [[https://openalex.org/A5010329143][Francesco Carlà]], [[https://openalex.org/A5018264718][Vitaly Alexandrov]], [[https://openalex.org/A5007335678][Enrico Andreoli]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2018. https://doi.org/10.5281/zenodo.1183429 
     
Dataset for the paper "Poly-Amide Modified Copper Foam Electrodes for Enhanced Electrochemical Reduction of Carbon Dioxide". It includes data from: Electrochemistry, Gas Chromatography, Scanning Electron Microscopy/Energy-Dispersive X-ray Spectroscopy, X-Ray Photoelectron Spectroscopy, Nuclear Magnetic Resonance Spectroscopy, Ex-situ and In-situ Synchrotron X-Ray Diffraction, and DFT computations.    

    

* Data from: Operando Proton Transfer Reaction-Time of Flight-Mass Spectrometry of Carbon Dioxide Reduction Electrocatalysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393616536
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2022-08-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.7047052")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393616536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393616536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393616536"))][Get cited by]]

OpenAlex: https://openalex.org/W4393616536 (Open access: True)
    
[[https://openalex.org/A5086912699][Hangjuan Ren]], [[https://openalex.org/A5081433980][Mikhail Kovalev]], [[https://openalex.org/A5070552556][Zhaoyue Weng]], [[https://openalex.org/A5048307849][Marsha Zakir Muhamad]], [[https://openalex.org/A5075705776][Yuan Sheng]], [[https://openalex.org/A5048054881][Libo Sun]], [[https://openalex.org/A5055050649][J. Wang]], [[https://openalex.org/A5068425730][Simon Rihm]], [[https://openalex.org/A5048688434][Hongyang Ma]], [[https://openalex.org/A5017507847][Wanfeng Yang]], [[https://openalex.org/A5046757416][Alexei A. Lapkin]], [[https://openalex.org/A5070081966][Joel W. Ager]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2022. https://doi.org/10.5281/zenodo.7047052 
     
Seven top-level folders GC-PTR-TOF-MS - Raw data and Jupyter Notebook used for analysis of GC-PTR-TOF-MS data LSV-PTR-TOF-MS - Raw data and Jupyter Notebook used for analysis of PTR-TOF-MS data under linear sweep voltammetry MSCP-PTR-TOF-MS - Raw data and Jupyter Notebook used for analysis of PTR-TOF-MS data under multi-step chronopotentiometry PTR-TOF-MS-Calibration - Raw data and Jupyter Notebook used for analysis of PTR-TOF-MS calibration data SEM - Raw images from scanning electron microscope Stability - Raw data of electrochemical stability TEM - Raw images from transmission electron microscopy    

    

* Data from: Operando Proton Transfer Reaction-Time of Flight-Mass Spectrometry of Carbon Dioxide Reduction Electrocatalysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393769430
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2022-04-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.6419994")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393769430"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393769430"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393769430"))][Get cited by]]

OpenAlex: https://openalex.org/W4393769430 (Open access: True)
    
[[https://openalex.org/A5086912699][Hangjuan Ren]], [[https://openalex.org/A5081433980][Mikhail Kovalev]], [[https://openalex.org/A5070552556][Zhaoyue Weng]], [[https://openalex.org/A5048307849][Marsha Zakir Muhamad]], [[https://openalex.org/A5075705776][Yuan Sheng]], [[https://openalex.org/A5048054881][Libo Sun]], [[https://openalex.org/A5055050649][J. Wang]], [[https://openalex.org/A5068425730][Simon Rihm]], [[https://openalex.org/A5048688434][Hongyang Ma]], [[https://openalex.org/A5017507847][Wanfeng Yang]], [[https://openalex.org/A5046757416][Alexei A. Lapkin]], [[https://openalex.org/A5070081966][Joel W. Ager]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2022. https://doi.org/10.5281/zenodo.6419994 
     
GC-PTR-TOF-MS - Raw data and Jupyter Notebook used for analysis of Cu-1 at 0.8 and 1.0 ampere per square centimeter LSV-PTR-TOF-MS - Raw data and Jupyter Notebook used for analysis of Cu-1 and Cu-2 under linear sweep voltammetry MSCP-PTR-TOF-MS - Raw data and Jupyter Notebook used for analysis of Cu-1 and Ni-doped Cu-1 under multi-step chronopotentiometry SEM - Raw images from scanning electron microscope Stability - Electrochemical stability TEM - Raw images from transmission electron microscopy    

    

* Solvation Procedures Assessment of Borohydride Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393887620
:TOPICS: Materials and Methods for Hydrogen Storage, Catalytic Carbon Dioxide Hydrogenation, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2020-12-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.4323457")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393887620"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393887620"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393887620"))][Get cited by]]

OpenAlex: https://openalex.org/W4393887620 (Open access: True)
    
[[https://openalex.org/A5010763163][Alex M. Maldonado]], [[https://openalex.org/A5005524440][Satoshi Hagiwara]], [[https://openalex.org/A5053938289][Tae Hoon Choi]], [[https://openalex.org/A5002298087][Frank Eckert]], [[https://openalex.org/A5072085044][Kathleen Schwarz]], [[https://openalex.org/A5049722503][Ravishankar Sundararaman]], [[https://openalex.org/A5035293042][Minoru Otani]], [[https://openalex.org/A5007577939][John A. Keith]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2020. https://doi.org/10.5281/zenodo.4323457 
     
Pathways, structures, gas-phase and solvation energies of aqueous borohydride reduction of carbon dioxide. Contents data Computational chemistry output files for gas-phase electronic energies, solvation energies, and QM/MM MD simulations are provided. They are organized by the method used to seek the reaction pathway. neb: contains computations involved with the g-SSNEB pathway from Groenenboom and Keith. gsm: contains computations either in preparation or execution of growing string method (GSM) calculations. The lego module of ABCluster was used to generate candidate starting structures. other: contains miscellaneous computations for additional analyses. scripts: contains all Python code used to generate Chemical JSON and CSV files. qmmm: contains GAMESS QM/MM MD trajectories and WHAM analyses. figures Contains Python scripts and figures made with matplotlib. Python files are named according to the data they use; for example, figure-neb.py is the code for figures that plot the various g-SSNEB pathways. Figures are organized according to where they appear: directly in the article (article/) or as supplemental information (si/). structures XYZ files relevant to this study organized by the chain-of-states method.    

    

* Solvation Procedures Assessment of Borohydride Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393426326
:TOPICS: Materials and Methods for Hydrogen Storage, Catalytic Carbon Dioxide Hydrogenation, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2020-12-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.4336730")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393426326"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393426326"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393426326"))][Get cited by]]

OpenAlex: https://openalex.org/W4393426326 (Open access: True)
    
[[https://openalex.org/A5010763163][Alex M. Maldonado]], [[https://openalex.org/A5005524440][Satoshi Hagiwara]], [[https://openalex.org/A5053938289][Tae Hoon Choi]], [[https://openalex.org/A5002298087][Frank Eckert]], [[https://openalex.org/A5072085044][Kathleen Schwarz]], [[https://openalex.org/A5049722503][Ravishankar Sundararaman]], [[https://openalex.org/A5035293042][Minoru Otani]], [[https://openalex.org/A5007577939][John A. Keith]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2020. https://doi.org/10.5281/zenodo.4336730 
     
Pathways, structures, gas-phase and solvation energies of aqueous borohydride reduction of carbon dioxide. Contents data Computational chemistry output files for gas-phase electronic energies, solvation energies, and QM/MM MD simulations are provided. They are organized by the method used to seek the reaction pathway. neb: contains computations involved with the g-SSNEB pathway from Groenenboom and Keith. gsm: contains computations either in preparation or execution of growing string method (GSM) calculations. The lego module of ABCluster was used to generate candidate starting structures. other: contains miscellaneous computations for additional analyses. scripts: contains all Python code used to generate Chemical JSON and CSV files. qmmm: contains GAMESS QM/MM MD trajectories and WHAM analyses. Note: the QM/MM MD data is in the zip with the "qmmm" suffix. Everything else is in the other zip. figures Contains Python scripts and figures made with matplotlib. Python files are named according to the data they use; for example, figure-neb.py is the code for figures that plot the various g-SSNEB pathways. Figures are organized according to where they appear: directly in the article (article/) or as supplemental information (si/). structures XYZ files relevant to this study organized by the chain-of-states method.    

    

* Solvation Procedures Assessment of Borohydride Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393895013
:TOPICS: Materials and Methods for Hydrogen Storage, Catalytic Carbon Dioxide Hydrogenation, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2020-12-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.4323456")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393895013"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393895013"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393895013"))][Get cited by]]

OpenAlex: https://openalex.org/W4393895013 (Open access: True)
    
[[https://openalex.org/A5010763163][Alex M. Maldonado]], [[https://openalex.org/A5005524440][Satoshi Hagiwara]], [[https://openalex.org/A5053938289][Tae Hoon Choi]], [[https://openalex.org/A5002298087][Frank Eckert]], [[https://openalex.org/A5072085044][Kathleen Schwarz]], [[https://openalex.org/A5049722503][Ravishankar Sundararaman]], [[https://openalex.org/A5035293042][Minoru Otani]], [[https://openalex.org/A5007577939][John A. Keith]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2020. https://doi.org/10.5281/zenodo.4323456 
     
Pathways, structures, gas-phase and solvation energies of aqueous borohydride reduction of carbon dioxide. Contents data Computational chemistry output files for gas-phase electronic energies, solvation energies, and QM/MM MD simulations are provided. They are organized by the method used to seek the reaction pathway. neb: contains computations involved with the g-SSNEB pathway from Groenenboom and Keith. gsm: contains computations either in preparation or execution of growing string method (GSM) calculations. The lego module of ABCluster was used to generate candidate starting structures. other: contains miscellaneous computations for additional analyses. scripts: contains all Python code used to generate Chemical JSON and CSV files. qmmm: contains GAMESS QM/MM MD trajectories and WHAM analyses. Note: the QM/MM MD data is in the zip with the "qmmm" suffix. Everything else is in the other zip. figures Contains Python scripts and figures made with matplotlib. Python files are named according to the data they use; for example, figure-neb.py is the code for figures that plot the various g-SSNEB pathways. Figures are organized according to where they appear: directly in the article (article/) or as supplemental information (si/). structures XYZ files relevant to this study organized by the chain-of-states method.    

    

* Improved estimates of carbon dioxide emissions from drained peatlands support a reduction in emission factor  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393749257
:TOPICS: Carbon Dynamics in Peatland Ecosystems
:PUBLICATION_DATE: 2023-11-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.10069468")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393749257"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393749257"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393749257"))][Get cited by]]

OpenAlex: https://openalex.org/W4393749257 (Open access: True)
    
[[https://openalex.org/A5042645271][Hongxing He]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2023. https://doi.org/10.5281/zenodo.10069468 
     
Summary of published carbon dioxide field emission data and their influence factors used for generating Tier 1 emission factor of peat extractions in IPCC 2013 Wetland Supplementary and extra data published after IPCC (2014). The dataset is supplementary to the published paper "Improved estimates of carbon dioxide emissions from drained peatlands support a reduction in emission factor" By Hongxing He and Nigel Roulet: He, H., Roulet, N.T. Improved estimates of carbon dioxide emissions from drained peatlands support a reduction in emission factor. Commun Earth Environ 4, 436 (2023). https://doi.org/10.1038/s43247-023-01091-y.    

    

* Improved estimates of carbon dioxide emissions from drained peatlands support a reduction in emission factor  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393709502
:TOPICS: Carbon Dynamics in Peatland Ecosystems
:PUBLICATION_DATE: 2023-11-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.10069469")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393709502"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393709502"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393709502"))][Get cited by]]

OpenAlex: https://openalex.org/W4393709502 (Open access: True)
    
[[https://openalex.org/A5042645271][Hongxing He]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2023. https://doi.org/10.5281/zenodo.10069469 
     
Summary of published carbon dioxide field emission data and their influence factors used for generating Tier 1 emission factor of peat extractions in IPCC 2013 Wetland Supplementary and extra data published after IPCC (2014). The dataset is supplementary to the published paper "Improved estimates of carbon dioxide emissions from drained peatlands support a reduction in emission factor" By Hongxing He and Nigel Roulet: He, H., Roulet, N.T. Improved estimates of carbon dioxide emissions from drained peatlands support a reduction in emission factor. Commun Earth Environ 4, 436 (2023). https://doi.org/10.1038/s43247-023-01091-y.    

    

* Data for: "Carbon dioxide reduction by lanthanide(III) complexes supported by redox-active Schiff base ligands"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393810733
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2020-08-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.7295464")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393810733"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393810733"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393810733"))][Get cited by]]

OpenAlex: https://openalex.org/W4393810733 (Open access: True)
    
[[https://openalex.org/A5077089637][Nadir Jori]], [[https://openalex.org/A5004880474][Davide Toniolo]], [[https://openalex.org/A5007919105][Bang C. Huynh]], [[https://openalex.org/A5033332794][Rosario Scopelliti]], [[https://openalex.org/A5051819146][Marinella Mazzanti]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2020. https://doi.org/10.5281/zenodo.7295464 
     
RAW DATA FOR ARTICLE DATE: NOVEMBER 2022 TITLE: Carbon dioxide reduction by lanthanide(III) complexes supported by redox-active Schiff base ligands AUTHORS: Nadir Jori, Davide Toniolo, Bang C. Huynh, Rosario Scopelliti, and Marinella Mazzanti* JOURNAL: Inorganic Chemistry Frontiers (RSC) 2020 DOI: 10.1039/D0QI00801J    

    

* Data for: "Carbon dioxide reduction by lanthanide(III) complexes supported by redox-active Schiff base ligands"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393645692
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2020-08-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.7295465")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393645692"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393645692"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393645692"))][Get cited by]]

OpenAlex: https://openalex.org/W4393645692 (Open access: True)
    
[[https://openalex.org/A5077089637][Nadir Jori]], [[https://openalex.org/A5004880474][Davide Toniolo]], [[https://openalex.org/A5007919105][Bang C. Huynh]], [[https://openalex.org/A5033332794][Rosario Scopelliti]], [[https://openalex.org/A5051819146][Marinella Mazzanti]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2020. https://doi.org/10.5281/zenodo.7295465 
     
RAW DATA FOR ARTICLE DATE: NOVEMBER 2022 TITLE: Carbon dioxide reduction by lanthanide(III) complexes supported by redox-active Schiff base ligands AUTHORS: Nadir Jori, Davide Toniolo, Bang C. Huynh, Rosario Scopelliti, and Marinella Mazzanti* JOURNAL: Inorganic Chemistry Frontiers (RSC) 2020 DOI: 10.1039/D0QI00801J    

    

* Reduction of Iron Oxides for CO2 Capture Materials  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393388356
:TOPICS: Reduction Kinetics in Ironmaking Processes, Chemical-Looping Technologies, Battery Recycling and Rare Earth Recovery
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17071673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393388356"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393388356"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393388356"))][Get cited by]]

OpenAlex: https://openalex.org/W4393388356 (Open access: True)
    
[[https://openalex.org/A5072736187][Antonio Fabozzi]], [[https://openalex.org/A5034273464][Francesca Cerciello]], [[https://openalex.org/A5076148122][Osvalda Senneca]], Energies (Basel). 17(7)] 2024. https://doi.org/10.3390/en17071673  ([[https://www.mdpi.com/1996-1073/17/7/1673/pdf?version=1711949729][pdf]])
     
The iron industry is the largest energy-consuming manufacturing sector in the world, emitting 4–5% of the total carbon dioxide (CO2). The development of iron-based systems for CO2 capture and storage could effectively contribute to reducing CO2 emissions. A wide set of different iron oxides, such as hematite (Fe2O3), magnetite (Fe3O4), and wüstite (Fe(1−y)O) could in fact be employed for CO2 capture at room temperature and pressure upon an investigation of their capturing properties. In order to achieve the most functional iron oxide form for CO2 capture, starting from Fe2O3, a reducing agent such as hydrogen (H2) or carbon monoxide (CO) can be employed. In this review, we present the state-of-the-art and recent advances on the different iron oxide materials employed, as well as on their reduction reactions with H2 and CO.    

    

* CO2 Reduction Tafel Dataset for Bayesian Data Analysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393480639
:TOPICS: Low-Cost Air Quality Monitoring Systems, Gaussian Processes in Machine Learning, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2020-08-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.3995020")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393480639"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393480639"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393480639"))][Get cited by]]

OpenAlex: https://openalex.org/W4393480639 (Open access: True)
    
[[https://openalex.org/A5013533800][Aditya Limaye]], [[https://openalex.org/A5060667836][Joy S. Zeng]], [[https://openalex.org/A5087104793][Adam P. Willard]], [[https://openalex.org/A5028764974][Karthish Manthiram]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2020. https://doi.org/10.5281/zenodo.3995020 
     
This dataset contains 344 different digitized and tagged Tafel slope datasets from the CO2 reduction literature. We re-analyze this data with a Bayesian data analysis procedure that estimates a Tafel slope and yields distributional uncertainty information about its value. We are releasing this dataset along with our study to facilitate re-analyzing and refitting our data using different models and approaches.    

    

* Raw data for the journal article "Cracks as efficient tools to mitigate flooding in gas diffusion electrodes used for the electrochemical reduction of carbon dioxide"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393675517
:TOPICS: Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2022-04-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.6421141")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393675517"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393675517"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393675517"))][Get cited by]]

OpenAlex: https://openalex.org/W4393675517 (Open access: True)
    
[[https://openalex.org/A5067190406][Ying Kong]], [[https://openalex.org/A5002376696][Menglong Liu]], [[https://openalex.org/A5043117737][Huifang Hu]], [[https://openalex.org/A5022762260][Yuhui Hou]], [[https://openalex.org/A5010965814][Soma Vesztergom]], [[https://openalex.org/A5075269204][María de Jesús Gálvez‐Vázquez]], [[https://openalex.org/A5073252151][Ivan Montiel]], [[https://openalex.org/A5020987120][Viliam Kolivoška]], [[https://openalex.org/A5002095391][Peter Broekmann]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2022. https://doi.org/10.5281/zenodo.6421141 
     
This data set corresponds to the article by Kong et al. entitled "Cracks as efficient tools to mitigate flooding in gas diffusion electrodes used for the electrochemical reduction of carbon dioxide", published in Small Methods    

    

* Raw data for the journal article "Cracks as efficient tools to mitigate flooding in gas diffusion electrodes used for the electrochemical reduction of carbon dioxide"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393699209
:TOPICS: Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2022-04-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.6421142")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393699209"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393699209"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393699209"))][Get cited by]]

OpenAlex: https://openalex.org/W4393699209 (Open access: True)
    
[[https://openalex.org/A5067190406][Ying Kong]], [[https://openalex.org/A5002376696][Menglong Liu]], [[https://openalex.org/A5043117737][Huifang Hu]], [[https://openalex.org/A5022762260][Yuhui Hou]], [[https://openalex.org/A5010965814][Soma Vesztergom]], [[https://openalex.org/A5075269204][María de Jesús Gálvez‐Vázquez]], [[https://openalex.org/A5073252151][Ivan Montiel]], [[https://openalex.org/A5020987120][Viliam Kolivoška]], [[https://openalex.org/A5002095391][Peter Broekmann]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2022. https://doi.org/10.5281/zenodo.6421142 
     
This data set corresponds to the article by Kong et al. entitled "Cracks as efficient tools to mitigate flooding in gas diffusion electrodes used for the electrochemical reduction of carbon dioxide", published in Small Methods    

    

* Dataset to "Hydride Formation Diminishes CO2 Reduction Rate on Palladium"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393873967
:TOPICS: Ammonia Synthesis and Electrocatalysis, Materials and Methods for Hydrogen Storage, Catalytic Nanomaterials
:PUBLICATION_DATE: 2018-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.6828104")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393873967"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393873967"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393873967"))][Get cited by]]

OpenAlex: https://openalex.org/W4393873967 (Open access: True)
    
[[https://openalex.org/A5028426858][Emanuel Billeter]], [[https://openalex.org/A5009932749][Terreni Jasmin]], [[https://openalex.org/A5088521783][Andreas Borgschulte]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2018. https://doi.org/10.5281/zenodo.6828104 
     
Dataset to "Hydride Formation Diminishes CO2 Reduction Rate on Palladium" as published in ChemPhysChem, 20 (2019), 1398-1403    

    

* Dataset to "Hydride Formation Diminishes CO2 Reduction Rate on Palladium"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393474634
:TOPICS: Ammonia Synthesis and Electrocatalysis, Materials and Methods for Hydrogen Storage, Catalytic Nanomaterials
:PUBLICATION_DATE: 2018-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.6828103")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393474634"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393474634"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393474634"))][Get cited by]]

OpenAlex: https://openalex.org/W4393474634 (Open access: True)
    
[[https://openalex.org/A5028426858][Emanuel Billeter]], [[https://openalex.org/A5009932749][Terreni Jasmin]], [[https://openalex.org/A5088521783][Andreas Borgschulte]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2018. https://doi.org/10.5281/zenodo.6828103 
     
Dataset to "Hydride Formation Diminishes CO2 Reduction Rate on Palladium" as published in ChemPhysChem, 20 (2019), 1398-1403    

    
