#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Fri Aug  2 01:11:02 2024

Found 51 results from 2024-07-26 to 2024-08-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Origin of Carbon Monoxide Formation in the Oxidative Dehydrogenation of Propane Using Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400982774
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Mesoporous Materials
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02628")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400982774"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400982774"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400982774"))][Get cited by]]

OpenAlex: https://openalex.org/W4400982774 (Open access: True)
    
[[https://openalex.org/A5090923288][James Carter]], [[https://openalex.org/A5049203228][Tongqi Ye]], [[https://openalex.org/A5056229798][Daniel G. Hewes]], [[https://openalex.org/A5105065349][Ahlam Almoteiry]], [[https://openalex.org/A5059168773][Kieran J. Aggett]], [[https://openalex.org/A5014755874][Bart D. Vandegehuchte]], [[https://openalex.org/A5051694258][Qian He]], [[https://openalex.org/A5029440147][Stuart H. Taylor]], [[https://openalex.org/A5020068159][Graham J. Hutchings]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02628 
     
No abstract    

    

* Amorphous Nanomaterials: Emerging Catalysts for Electrochemical Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400991715
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202402424")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400991715"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400991715"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400991715"))][Get cited by]]

OpenAlex: https://openalex.org/W4400991715 (Open access: False)
    
[[https://openalex.org/A5040391460][Miaomiao Tan]], [[https://openalex.org/A5009468452][Biao Huang]], [[https://openalex.org/A5062006962][Lina Su]], [[https://openalex.org/A5091712567][Xiaojin Jiao]], [[https://openalex.org/A5101313304][Fukai Feng]], [[https://openalex.org/A5101906993][Yixuan Gao]], [[https://openalex.org/A5064121761][Qianli Huang]], [[https://openalex.org/A5103191012][Zhiqi Huang]], [[https://openalex.org/A5053762044][Yiyao Ge]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202402424 
     
Abstract In the past decades, the rapid depletion of non‐renewable energy sources has caused growing energy crisis and increasing emissions of carbon dioxide (CO 2 ), which aggravates global warming and catastrophic climate change. Electrocatalysis is regarded as an effective method for consuming atmospheric CO 2 and simultaneously alleviating the energy problem by converting CO 2 into high value‐added chemicals. Amorphous nanomaterials with long‐range disordered structures possess abundant highly unsaturated atomic sites and dangling bonds on their surfaces, thus providing a large number of active sites, and show unique electronic structures compared to their crystalline counterparts due to the distinct atomic arrangements. Therefore, amorphous nanomaterials are recently demonstrated as highly efficient catalysts for diverse electrocatalytic reactions, including electrocatalytic CO 2 reduction reaction (CO 2 RR). Here the rational synthesis and electrocatalytic performance of newly emerging amorphous nanomaterials will be outlined for electrocatalytic CO 2 RR. Importantly, the intrinsic merits of these amorphous catalysts in CO 2 RR processes will be summarized and highlighted. Finally, these perspectives on the remaining challenges and some potential future directions in this emerging field will also be provided.    

    

* Carbon monoxide synthesis from carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401012803
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Hydrogen Energy Systems and Technologies, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/b978-0-443-19235-7.00006-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401012803"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401012803"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401012803"))][Get cited by]]

OpenAlex: https://openalex.org/W4401012803 (Open access: False)
    
[[https://openalex.org/A5022042020][D. Santos]], [[https://openalex.org/A5017625619][Alexandre Mendonça Teixeira]], [[https://openalex.org/A5044740636][Stefano Ferrari Interlenghi]], [[https://openalex.org/A5059822653][Gabriel S. Bassani]], [[https://openalex.org/A5075269005][Rita M.B. Alves]], Elsevier eBooks. None(None)] 2024. https://doi.org/10.1016/b978-0-443-19235-7.00006-3 
     
No abstract    

    

* Three-dimensional reconstruction of porous CeO2 single crystal for effective electrolysis of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027649
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235088")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027649"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027649"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027649"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027649 (Open access: False)
    
[[https://openalex.org/A5050650726][Jiaming Ma]], [[https://openalex.org/A5010438441][Mengmeng Miao]], [[https://openalex.org/A5016445881][Kui Xie]], [[https://openalex.org/A5016445881][Kui Xie]], Journal of Power Sources. 615(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235088 
     
No abstract    

    

* Synergy of Tm-Based Dual-Atom Catalysts Supported by B,N-Doped Biphenylene for Carbon Dioxide Reduction Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027800
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4906500")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027800"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027800 (Open access: False)
    
[[https://openalex.org/A5014323700][Maryam Fallahzadeh]], [[https://openalex.org/A5068516261][Alireza Kokabi]], [[https://openalex.org/A5084449137][Zahra Nasiri]], [[https://openalex.org/A5088679046][Mina Fayazi]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4906500 
     
No abstract    

    

* Surface Defects Induced Polarization Manipulation in Cu2SnS3 for Boosting Electrochemical CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401032296
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04092a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401032296"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401032296"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401032296"))][Get cited by]]

OpenAlex: https://openalex.org/W4401032296 (Open access: False)
    
[[https://openalex.org/A5100717474][Haihua Wang]], [[https://openalex.org/A5090340144][Wen Ning]], [[https://openalex.org/A5100334817][Yupeng Li]], [[https://openalex.org/A5047695454][Xiuling Jiao]], [[https://openalex.org/A5103244018][Yuguo Xia]], [[https://openalex.org/A5072207899][Dairong Chen]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta04092a 
     
Controlling the electrocatalyst's surface polarization is crucial for the interfacial CO2 electrolysis that takes place. Here, we propose an efficient way to increase the electrochemical reduction of CO2 to formate...    

    

* Engineering Strategies in Rational Design of Cu-Based Catalysts for Electrochemical CO2 Reduction: From Doping of Elements to Defects creation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401033694
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ma00321g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401033694"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401033694"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401033694"))][Get cited by]]

OpenAlex: https://openalex.org/W4401033694 (Open access: True)
    
[[https://openalex.org/A5006935349][Sheraz Yousaf]], [[https://openalex.org/A5074780725][Iqbal Ahmad]], [[https://openalex.org/A5089324736][Muhammad Farooq Warsi]], [[https://openalex.org/A5057878200][Asad Ali]], Materials Advances. None(None)] 2024. https://doi.org/10.1039/d4ma00321g 
     
The rational design of copper (Cu)-based catalysts for electrochemical carbon dioxide (CO2) reduction has garnered substantial attention due to its potential to mitigate climate change by converting CO2 into valuable...    

    

* Improved Production Rates of Hydrogen Generation and Carbon Dioxide Reduction Using Gallium Nitride with Nickel Oxide Nanofilm Capping Layer as Photoelectrodes for Photoelectrochemical Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027697
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsomega.4c03729")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027697"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027697"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027697"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027697 (Open access: True)
    
[[https://openalex.org/A5056478968][Chin Yin Sheu]], [[https://openalex.org/A5047589446][Shang-Ju Tu]], [[https://openalex.org/A5075283086][Shao‐Chi Chang]], ACS Omega. None(None)] 2024. https://doi.org/10.1021/acsomega.4c03729 
     
No abstract    

    

* Electronic perturbation of Cu nanowire surfaces with functionalized graphdiyne for enhanced CO2 reduction reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401008216
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/nsr/nwae253")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401008216"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401008216"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401008216"))][Get cited by]]

OpenAlex: https://openalex.org/W4401008216 (Open access: True)
    
[[https://openalex.org/A5037340591][Haiyuan Zou]], [[https://openalex.org/A5028424510][Dongfang Cheng]], [[https://openalex.org/A5010019518][Chao Tang]], [[https://openalex.org/A5079295506][Wen Luo]], [[https://openalex.org/A5079946479][Huatian Xiong]], [[https://openalex.org/A5074364344][Hui‐Fen Dong]], [[https://openalex.org/A5100373596][Fan Li]], [[https://openalex.org/A5029772385][Tao Song]], [[https://openalex.org/A5024686369][Sai Shu]], [[https://openalex.org/A5065585691][Hao Dai]], [[https://openalex.org/A5101273787][Ziang Cui]], [[https://openalex.org/A5027800643][Zhouguang Lu]], [[https://openalex.org/A5047901288][Lele Duan]], National Science Review. None(None)] 2024. https://doi.org/10.1093/nsr/nwae253 
     
Abstract Electronic perturbation of Cu catalysts surface is crucial for optimizing electrochemical CO2 reduction activity, yet still poses great challenges. Herein, nanostructured Cu nanowires (NW) with fine-tuned surface electronic structure are achieved via surface encapsulation with electron-withdrawing (–F) and -donating (–Me) group-functionalized graphdiynes (R-GDY, R = –F and –Me), and the resulting catalysts, denoted as R-GDY/Cu NW, display distinct CO2 reduction performances. In-situ electrochemical spectroscopy revealed that the *CO (a key intermediate of the CO2 reduction reaction) binding affinity and consequent *CO coverage positively correlate to the Cu surface oxidation state, leading to the favorable C–C coupling on F-GDY/Cu NW over Me-GDY/Cu NW. Electrochemical measurements corroborate the favorable C2H4 production with an optimum C2+ selectivity of 73.15% ± 2.5% observed for F-GDY/Cu NW, while the predominant CH4 production is favored by Me-GDY/Cu NW. Furthermore, leveraging the *Cu–OH/*CO ratio as a descriptor, mechanistic investigation reveals that the protonation of distinct adsorbed *CO facilitated by *Cu–OH is crucial for the selective generation of C2H4 and CH4 on F-GDY/Cu NW and Me-GDY/Cu NW, respectively.    

    

* Electrolyte Composition‐Dependent Product Selectivity in CO2 Reduction with a Porphyrinic Metal‐Organic Framework Catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401022814
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202411766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401022814"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401022814"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401022814"))][Get cited by]]

OpenAlex: https://openalex.org/W4401022814 (Open access: False)
    
[[https://openalex.org/A5089568090][Shiliang Pu]], [[https://openalex.org/A5025077602][Tao Huang]], [[https://openalex.org/A5035202372][Duan‐Hui Si]], [[https://openalex.org/A5079968989][Meng-Jiao Sun]], [[https://openalex.org/A5100768915][Wenwen Wang]], [[https://openalex.org/A5100372524][Teng Zhang]], [[https://openalex.org/A5027181760][Rong Cao]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202411766 
     
A copper porphyrin-derived metal-organic framework electrocatalyst, FICN-8, was synthesized and its catalytic activity for CO2 reduction reaction (CO2RR) was investigated. FICN-8 selectively catalyzed electrochemical reduction of CO2 to CO in anhydrous acetonitrile electrolyte. However, formic acid became the dominant CO2RR product with the addition of a proton source to the system. Mechanistic studies revealed the change of major reduction pathway upon proton source addition, while catalyst-bound hydride (*H) species was proposed as the key intermediate for formic acid production. This work highlights the importance of electrolyte composition on CO2RR product selectivity.    

    

* Electrolyte Composition‐Dependent Product Selectivity in CO2 Reduction with a Porphyrinic Metal‐Organic Framework Catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401022535
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202411766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401022535"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401022535"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401022535"))][Get cited by]]

OpenAlex: https://openalex.org/W4401022535 (Open access: False)
    
[[https://openalex.org/A5089568090][Shiliang Pu]], [[https://openalex.org/A5025077602][Tao Huang]], [[https://openalex.org/A5035202372][Duan‐Hui Si]], [[https://openalex.org/A5079968989][Meng-Jiao Sun]], [[https://openalex.org/A5100768915][Wenwen Wang]], [[https://openalex.org/A5100372524][Teng Zhang]], [[https://openalex.org/A5027181760][Rong Cao]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202411766 
     
A copper porphyrin‐derived metal‐organic framework electrocatalyst, FICN‐8, was synthesized and its catalytic activity for CO2 reduction reaction (CO2RR) was investigated. FICN‐8 selectively catalyzed electrochemical reduction of CO2 to CO in anhydrous acetonitrile electrolyte. However, formic acid became the dominant CO2RR product with the addition of a proton source to the system. Mechanistic studies revealed the change of major reduction pathway upon proton source addition, while catalyst‐bound hydride (*H) species was proposed as the key intermediate for formic acid production. This work highlights the importance of electrolyte composition on CO2RR product selectivity.    

    

* Zn-Cu Bimetallic Gas Diffusion Electrodes for Electrochemical Reduction of CO2 to Ethylene  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401007616
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144723")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401007616"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401007616"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401007616"))][Get cited by]]

OpenAlex: https://openalex.org/W4401007616 (Open access: False)
    
[[https://openalex.org/A5061145215][Munzir H. Suliman]], [[https://openalex.org/A5105370707][Hussain Al Naji]], [[https://openalex.org/A5090138718][Muhammad Usman]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144723 
     
No abstract    

    

* Evaluating the Selectivity of CO2 Reduction Reaction on Elementary Metal Particles with DFT Calculations  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401009030
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Thermoelectric Materials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104866")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401009030"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401009030"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401009030"))][Get cited by]]

OpenAlex: https://openalex.org/W4401009030 (Open access: False)
    
[[https://openalex.org/A5100366986][Qiang Wang]], [[https://openalex.org/A5100454297][Jia Li]], [[https://openalex.org/A5100330605][Yi Liu]], [[https://openalex.org/A5024681732][Pi-Guey Su]], [[https://openalex.org/A5101595171][Zhaohui Zhou]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104866 
     
No abstract    

    

* Review for "Surface Defects Induced Polarization Manipulation in Cu2SnS3 for Boosting Electrochemical CO2 Reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401044114
:TOPICS: Gas Sensing Technology and Materials, Electrochemical Reduction of CO2 to Fuels, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04092a/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401044114"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401044114"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401044114"))][Get cited by]]

OpenAlex: https://openalex.org/W4401044114 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04092a/v1/review2 
     
No abstract    

    

* Contribution of Coal Electricity to Global CO2 Emissions: The Existing Situation and Current Trends of Their Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401046875
:TOPICS: Power Generation and Energy Systems, Future Development of China's Coal Industry, Technological Development in Mineral Resource Sector
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1134/s0040601524700125")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401046875"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401046875"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401046875"))][Get cited by]]

OpenAlex: https://openalex.org/W4401046875 (Open access: False)
    
[[https://openalex.org/A5010139023][А. Н. Тугов]], Thermal Engineering. 71(7)] 2024. https://doi.org/10.1134/s0040601524700125 
     
No abstract    

    

* Review for "Surface Defects Induced Polarization Manipulation in Cu2SnS3 for Boosting Electrochemical CO2 Reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401044521
:TOPICS: Gas Sensing Technology and Materials, Electrochemical Reduction of CO2 to Fuels, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04092a/v2/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401044521"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401044521"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401044521"))][Get cited by]]

OpenAlex: https://openalex.org/W4401044521 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04092a/v2/review2 
     
No abstract    

    

* Pre-reduction of Nchwaning manganese ore in CO/CO2, H2/H2O, and H2 atmospheres  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401026636
:TOPICS: Reduction Kinetics in Ironmaking Processes, Biohydrometallurgical Processes for Metal Extraction, Thermochemical Software and Databases in Metallurgy
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mineng.2024.108854")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401026636"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401026636"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401026636"))][Get cited by]]

OpenAlex: https://openalex.org/W4401026636 (Open access: True)
    
[[https://openalex.org/A5086250478][Mathilde Ernst]], [[https://openalex.org/A5086748509][Merete Tangstad]], [[https://openalex.org/A5071118055][S.P. du Preez]], Minerals Engineering. 216(None)] 2024. https://doi.org/10.1016/j.mineng.2024.108854 
     
No abstract    

    

* Review for "Surface Defects Induced Polarization Manipulation in Cu2SnS3 for Boosting Electrochemical CO2 Reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401044226
:TOPICS: Gas Sensing Technology and Materials, Electrochemical Reduction of CO2 to Fuels, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04092a/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401044226"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401044226"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401044226"))][Get cited by]]

OpenAlex: https://openalex.org/W4401044226 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04092a/v1/review1 
     
No abstract    

    

* Review for "Surface Defects Induced Polarization Manipulation in Cu2SnS3 for Boosting Electrochemical CO2 Reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401044177
:TOPICS: Gas Sensing Technology and Materials, Electrochemical Reduction of CO2 to Fuels, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04092a/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401044177"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401044177"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401044177"))][Get cited by]]

OpenAlex: https://openalex.org/W4401044177 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04092a/v2/review1 
     
No abstract    

    

* Decision letter for "Surface Defects Induced Polarization Manipulation in Cu2SnS3 for Boosting Electrochemical CO2 Reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401044607
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04092a/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401044607"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401044607"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401044607"))][Get cited by]]

OpenAlex: https://openalex.org/W4401044607 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04092a/v1/decision1 
     
No abstract    

    

* Decision letter for "Surface Defects Induced Polarization Manipulation in Cu2SnS3 for Boosting Electrochemical CO2 Reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401044124
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04092a/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401044124"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401044124"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401044124"))][Get cited by]]

OpenAlex: https://openalex.org/W4401044124 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04092a/v2/decision1 
     
No abstract    

    

* MXene quantum dots decorated g-C3N4/BiOI heterojunction photocatalyst for efficient NO deep oxidation and CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401022868
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.128961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401022868"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401022868"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401022868"))][Get cited by]]

OpenAlex: https://openalex.org/W4401022868 (Open access: False)
    
[[https://openalex.org/A5058882524][Junli Nie]], [[https://openalex.org/A5060770482][Xingmao Zhang]], [[https://openalex.org/A5014907619][Ming‐Sheng Wang]], [[https://openalex.org/A5070431364][Yucheng Ou]], [[https://openalex.org/A5009555060][Shiping Li]], [[https://openalex.org/A5052832631][Peng Zhong]], [[https://openalex.org/A5100333147][Weiwei Wang]], [[https://openalex.org/A5008523475][Gangqiang Zhu]], [[https://openalex.org/A5100321027][Xiaohua Ma]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.128961 
     
No abstract    

    

* Charge transfer regulates electrocatalytic CO2 reduction on one-dimensional carbon nanotube/boron nitride nanotube heterostructures  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401022912
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Thermoelectric Materials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.128981")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401022912"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401022912"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401022912"))][Get cited by]]

OpenAlex: https://openalex.org/W4401022912 (Open access: False)
    
[[https://openalex.org/A5033673698][Qigang Chen]], [[https://openalex.org/A5003167045][Huohai Yang]], [[https://openalex.org/A5100396067][Peng Wang]], [[https://openalex.org/A5020862263][Qiang Ke]], [[https://openalex.org/A5063446819][Xingbo Ge]], [[https://openalex.org/A5024977426][Xin Chen]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.128981 
     
No abstract    

    

* In Situ Studies of Cu Catalyzed CO2 Electro-Reduction by Soft X-ray Scanning Transmission X-ray Microscopy and Soft X-ray Spectro-Ptychography  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401000088
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/mam/ozae044.855")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401000088"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401000088"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401000088"))][Get cited by]]

OpenAlex: https://openalex.org/W4401000088 (Open access: False)
    
[[https://openalex.org/A5053413006][Adam P. Hitchcock]], [[https://openalex.org/A5063184743][Chunyang Zhang]], [[https://openalex.org/A5042189271][Haytham Eraky]], [[https://openalex.org/A5044827415][Drew Higgins]], Microscopy and Microanalysis. 30(Supplement_1)] 2024. https://doi.org/10.1093/mam/ozae044.855 
     
No abstract    

    

* Sr(Ti0·3Fe0.7)O3−δ-based perovskite with in-situ exsolved Fe–Ru nanoparticles: A highly stable fuel electrode material for solid oxide electrochemical cells with efficient electrocatalytic CO2 reduction ability and preferential selectivity  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027580
:TOPICS: Solid Oxide Fuel Cells, Chemical-Looping Technologies, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235087")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027580"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027580"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027580"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027580 (Open access: False)
    
[[https://openalex.org/A5005161657][Fang-Ze Han]], [[https://openalex.org/A5010211660][Yongshan Wan]], [[https://openalex.org/A5087020669][Cheng‐Xin Li]], [[https://openalex.org/A5042561898][Shan-Lin Zhang]], Journal of Power Sources. 615(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235087 
     
No abstract    

    

* Alkali-promoted indium oxide as highly active and selective catalyst for the photo-thermal CO2 hydrogenation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401025425
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04387a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401025425"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401025425"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401025425"))][Get cited by]]

OpenAlex: https://openalex.org/W4401025425 (Open access: True)
    
[[https://openalex.org/A5052460109][Xiupeng Wang]], [[https://openalex.org/A5079894139][Alejandra Rendón‐Patiño]], [[https://openalex.org/A5077388484][Jean Marcel R. Gallo]], [[https://openalex.org/A5047085423][Diego Mateo]], [[https://openalex.org/A5058113997][Jorge Gascón]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta04387a 
     
Photo-thermal carbon dioxide (CO2) reduction has recently gained significant attention as a strategy to harness solar energy and address environmental challenges. Among other photo-thermal catalysts, indium oxide (In2O3) has emerged...    

    

* An Analysis of Greenhouse Gas Emissions in Electrolysis for Certifying Clean Hydrogen  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401015106
:TOPICS: Hydrogen Energy Systems and Technologies, Ammonia Synthesis and Electrocatalysis, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17153698")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401015106"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401015106"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401015106"))][Get cited by]]

OpenAlex: https://openalex.org/W4401015106 (Open access: True)
    
[[https://openalex.org/A5059901009][Yunji Kim]], [[https://openalex.org/A5015586692][In Ki Min]], [[https://openalex.org/A5100347348][Ji Eun Lee]], [[https://openalex.org/A5076975762][Heena Yang]], Energies. 17(15)] 2024. https://doi.org/10.3390/en17153698 
     
The drive for carbon neutrality has led to legislative measures targeting reduced greenhouse gas emissions across the transportation, construction, and industry sectors. Renewable energy sources, especially solar and wind power, play a pivotal role in this transition. However, their intermittent nature necessitates effective storage solutions. Green hydrogen and ammonia have gained attention for their potential to store renewable energy while producing minimal emissions. Despite their theoretical promise of zero greenhouse gas emissions during production, real-world emissions vary based on system configurations and lifecycle assessments, highlighting the need for detailed evaluations of their environmental impact. Therefore, in this study, calculations were performed for the actual amount of produced greenhouse gas emissions that are associated with the production of green hydrogen using electrolysis, from raw material extraction and processing to hydrogen production, with these assessed from well-to-gate emission estimates. Emissions were also evaluated based on various types of renewable energy sources in South Korea, as well as hydrogen production volumes, capacities, and types. Using these data, the following factors were examined in this study: carbon dioxide emissions from the manufacturing stage of electrolysis equipment production, the correlation between materials and carbon dioxide emissions, and process emissions. Current grades of clean hydrogen were verified, and the greenhouse gas reduction effects of green hydrogen were confirmed. These findings are significant against the backdrop of a country such as South Korea, where the proportion of renewable energy in total electricity production is very low at 5.51%. Based on the domestic greenhouse gas emission efficiency standard of 55 kWh/kgH2, it was found that producing 1 kg of hydrogen emits 0.076 kg of carbon dioxide for hydropower, 0.283 kg for wind power, and 0.924 kg for solar power. The carbon dioxide emissions for AWE and PEM stacks were 8434 kg CO2 and 3695 kg CO2, respectively, demonstrating that an alkaline water electrolysis (AWE) system emits about 2.3 times more greenhouse gasses than a proton exchange membrane (PEM) system. This indicates that the total carbon dioxide emissions of green hydrogen are significantly influenced by the type of renewable energy and the type of electrolysis used.    

    

* Mitigating Built Environment Air Pollution by Green Systems: An In-Depth Review  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400981343
:TOPICS: Health Effects of Air Pollution, Estimating Vehicle Fuel Consumption and Emissions, Low-Cost Air Quality Monitoring Systems
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/app14156487")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400981343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400981343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400981343"))][Get cited by]]

OpenAlex: https://openalex.org/W4400981343 (Open access: True)
    
[[https://openalex.org/A5099594090][Serena Vitaliano]], [[https://openalex.org/A5072842540][Stefano Cascone]], [[https://openalex.org/A5083532106][Provvidenza Rita D’Urso]], Applied Sciences. 14(15)] 2024. https://doi.org/10.3390/app14156487 
     
Air pollution is a critical issue impacting urban environments, leading to severe health problems and environmental degradation. This comprehensive review examines the potential of green systems—specifically green walls, active green walls, and urban greenery systems—to mitigate atmospheric pollutants such as particulate matter (PM), volatile organic compounds (VOCs), and carbon dioxide (CO2). By systematically analyzing 44 recent studies, this review highlights the pollutant capture efficiency of various green technologies and plant species in both indoor and outdoor settings. Active green walls, particularly those utilizing plant species such as Chlorophytum comosum and Sansevieria trifasciata, were found to be highly effective, with VOC reduction efficiencies of up to 96.34%, PM reductions of 65.42%, and CO2 reduction rates reaching 4.8% under optimal conditions. This review identifies key strengths in current research, including diverse experimental setups and the use of sophisticated measurement techniques, but also notes significant limitations such as variability in experimental conditions and a lack of long-term performance data. This study underscores the importance of proper maintenance to sustain green systems’ efficacy and highlights the potential issue of pollutant resuspension, which remains under-researched. Practical implications for urban planning are discussed, advocating for the integration of effective green systems into urban infrastructure to enhance air quality and public health. Recommendations for future research include the need for standardized metrics, long-term studies, economic feasibility analyses, and real-world validation of simulation models to better understand and optimize green systems for urban air pollution mitigation.    

    

* The Effect of Additives on Microcellular PVC Foams: Part 1 - Effect on Processing and Microstructure  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400989097
:TOPICS: Polymer Foaming with Supercritical Carbon Dioxide, Poly(vinyl chloride) Plasticizers and Stabilizers, Colloidal Particles in Complex Systems
:PUBLICATION_DATE: 1998-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1177/0262489319981704003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400989097"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400989097"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400989097"))][Get cited by]]

OpenAlex: https://openalex.org/W4400989097 (Open access: False)
    
[[https://openalex.org/A5071323218][Mark R. Holl]], [[https://openalex.org/A5031608682][Mingliang Ma]], [[https://openalex.org/A5072720747][Vipin Kumar]], [[https://openalex.org/A5099106872][Robert R. Kwapisz]], Cellular Polymers. 17(4)] 1998. https://doi.org/10.1177/0262489319981704003 
     
The effect of the presence of commonly used additives on the processing and structure of microcellular PVC foams was investigated. It was found that the presence of additives leads to a polydisperse cell structure with large variations in cell sizes. The solubility of carbon dioxide in the additives and in the lubricants was found to be lower than in the PVC matrix. The presence of additives showed no adverse effect on the overall foam growth dynamics. It appears that target reductions in density of PVC can be achieved at lower processing temperatures when additives and processing aids are present.    

    

* Research progress in home energy management systems consideration of comfort  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401032867
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization, Demand Response in Smart Grids
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54254/2755-2721/70/20240995")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401032867"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401032867"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401032867"))][Get cited by]]

OpenAlex: https://openalex.org/W4401032867 (Open access: False)
    
[[https://openalex.org/A5011353807][R. H. Yuan]], Applied and Computational Engineering. 70(1)] 2024. https://doi.org/10.54254/2755-2721/70/20240995 
     
According to statistics, the carbon dioxide emissions from Chinas power industry account for about 40% of the total energy consumption and carbon dioxide emissions, while residential electricity consumption accounts for 36.6% of the total social electricity consumption. However, ordinary households have low electricity efficiency and serious waste. In the context of the national strategy of carbon peak and carbon neutrality, the Home Energy Management System (HEMS) has been introduced to improve household electricity efficiency, reduce electricity consumption, and achieve energy conservation and emission reduction while ensuring the comfort of residents. This article introduces the current research status of home energy management systems that take into account user comfort, and shows some optimization models for home energy management systems that take into account user comfort. It specifically elaborates on the optimization models for household appliances and comfort, briefly outlines the relatively trendy load prediction and scheduling optimization models, and proposes some suggestions and prospects for popularizing knowledge related to home energy management systems for family members using smart homes and temperature comfort modeling based on the current development status.    

    

* Carbon reduction options for churches using oil for heating  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400989593
:TOPICS: Influence of Religion on Environmental Concern and Activism
:PUBLICATION_DATE: 2023-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.69554/ksqv2514")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400989593"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400989593"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400989593"))][Get cited by]]

OpenAlex: https://openalex.org/W4400989593 (Open access: False)
    
[[https://openalex.org/A5036358951][Donald E McNaughton]], No host. None(None)] 2023. https://doi.org/10.69554/ksqv2514 
     
To limit global warming, a rapid reduction in the carbon emissions from our buildings is required. Heating buildings contributed to 17 per cent of the UK overall carbon emissions in 2018 which is why it is important we look to decarbonise the heating systems that serve our buildings. In 2020, only 7.9 per cent of the energy to heat our buildings came from renewable sources. In the UK, existing heating is predominantly by natural gas. The most significant challenge is the rural buildings that are not served by mains gas but have oil supplies, due to the high carbon content of this fuel. The Diocese of Gloucester was invited to participate in a research project carried out by Historic England into viable methods of low and zero carbon heating in churches and their associated buildings. The focus of this research explores oil-fired heating systems as this fuel produces more carbon dioxide emissions than other fuels used to heat buildings. The key finding from this research is that no single heating technology is recommended for either all historic buildings or even each historic building type. Across the six case studies, air source heat pumps, biomass and electric heating were recommended in an equal proportion of cases. It is not possible to determine the most viable heating technology without carrying out a detailed technical feasibility study at the early concept stage of a project. The recommended heating technology depends on many factors including the building’s site and location, the size and form of the buildings, the use and operation of the buildings, the condition of the existing heating system and the existing utility infrastructure. The wider background to this research includes the 2030 net zero carbon target set by the Church of England and the UK government’s 2050 net zero carbon target.    

    

* How to maintain environmental integrity when using state support and the VCM to co-finance BECCS projects - a Swedish case study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401038408
:TOPICS: Success Factors in Project Management, Sustainable Construction and Green Building, Life Cycle Costing in Construction and Infrastructure Projects
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/fenvs.2024.1387138")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401038408"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401038408"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401038408"))][Get cited by]]

OpenAlex: https://openalex.org/W4401038408 (Open access: True)
    
[[https://openalex.org/A5086304587][Mylène Dufour]], [[https://openalex.org/A5081022748][Kenneth Möllersten]], [[https://openalex.org/A5103516508][Lars Zetterberg]], Frontiers in Environmental Science. 12(None)] 2024. https://doi.org/10.3389/fenvs.2024.1387138 
     
Limiting global warming to close to 1.5°C by 2100 requires deep and rapid greenhouse gas emission reductions and carbon dioxide removals (CDR) on a massive scale, presenting a remarkable scaling challenge. This paper focuses on the financing of bioenergy with carbon capture and storage (BECCS) in Sweden. BECCS is one of the most prominent CDR methods in 1.5°C-compatible global emission scenarios and has been assigned a specific role in Swedish policy for net-zero. A Swedish state support system for BECCS based on results-based payments is planned. Furthermore, demand for CDR-based carbon credits is on the rise on the voluntary carbon markets (VCM) for use towards voluntary mitigation targets. Risks involved with the current Swedish policies are analysed, specifically for the co-financing of BECCS by the planned state support and revenues from the VCM. We find that with the current policies, state support systems will subsidise carbon credit prices on the VCM. We argue that such subsidisation can lower decarbonisation efforts by lowering the internal carbon price set by actors, thus undermining environmental integrity. It is concluded that proportional attribution should be applied, i.e., attributing mitigation outcomes to the state support and VCM revenue in proportion to their financial contribution to the CDR achieved. The attribution analysis should be accompanied by adjustments in national greenhouse gas accounting so that mitigation outcomes that are issued as carbon credits and used for offsetting are not double claimed (i.e., not used by both a nation and a non-state actor on the VCM towards their respective mitigation targets). If proportional attribution and adjustments in national GHG accounting are not implemented, the credibility and environmental integrity of offsetting claims made by carbon credit users are eroded. We recommend that action is taken to operationalise and implement proportional attribution to allow for co-financing of BECCS projects while maintaining environmental integrity. Wider implications for our recommendations beyond the case of Swedish BECCS are also analysed.    

    

* Burning question: Rethinking organohalide degradation strategy for bioremediation applications  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401151712
:TOPICS: Impact of Persistent Organic Pollutants on Environment and Health, Perchlorate Contamination and Health Effects, Occurrence and Health Effects of Drinking Water Disinfection By-Products
:PUBLICATION_DATE: 2024-07-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/1751-7915.14539")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401151712"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401151712"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401151712"))][Get cited by]]

OpenAlex: https://openalex.org/W4401151712 (Open access: True)
    
[[https://openalex.org/A5039943970][Qihong Lu]], [[https://openalex.org/A5072972481][Qi Liang]], [[https://openalex.org/A5032416933][Zhiwei Liang]], Microbial Biotechnology. 17(8)] 2024. https://doi.org/10.1111/1751-7915.14539 
     
Abstract Organohalides are widespread pollutants that pose significant environmental hazards due to their high degree of halogenation and elevated redox potentials, making them resistant to natural attenuation. Traditional bioremediation approaches, primarily relying on bioaugmentation and biostimulation, often fall short of achieving complete detoxification. Furthermore, the emergence of complex halogenated pollutants, such as per‐ and polyfluoroalkyl substances (PFASs), further complicates remediation efforts. Therefore, there is a pressing need to reconsider novel approaches for more efficient remediation of these recalcitrant pollutants. This review proposes novel redox‐potential‐mediated hybrid bioprocesses, tailored to the physicochemical properties of pollutants and their environmental contexts, to achieve complete detoxification of organohalides. The possible scenarios for the proposed bioremediation approaches are further discussed. In anaerobic environments, such as sediment and groundwater, microbial reductive dehalogenation coupled with fermentation and methanogenesis can convert organohalides into carbon dioxide and methane. In environments with anaerobic‐aerobic alternation, such as paddy soil and wetlands, a synergistic process involving reduction and oxidation can facilitate the complete mineralization of highly halogenated organic compounds. Future research should focus on in‐depth exploration of microbial consortia, the application of ecological principles‐guided strategies, and the development of bioinspired‐designed techniques. This paper contributes to the academic discourse by proposing innovative remediation strategies tailored to the complexities of organohalide pollution.    

    

* The impact of greenhouse gases, regions, and sectors on future temperature anomaly with the FaIR model  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401088442
:TOPICS: Global Methane Emissions and Impacts, Integration of Renewable Energy Systems in Power Grids
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.59720/24-067")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401088442"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401088442"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401088442"))][Get cited by]]

OpenAlex: https://openalex.org/W4401088442 (Open access: False)
    
[[https://openalex.org/A5105914311][Tej Kosaraju]], [[https://openalex.org/A5044918740][Paul Griffiths]], No host. None(None)] 2024. https://doi.org/10.59720/24-067 
     
Greenhouse gas emissions from industrial activities have resulted in global warming, threatening the human way of life. Climate modeling is crucial to the effort to combat climate change by determining the potential impacts of anthropogenic emissions and thus identifying where emission reduction efforts should focus. In this study, we hypothesized that various economic sectors, geographic regions, and greenhouse gas species could impact the future global mean surface temperature (GMST) anomaly in ways that deviate from the historical and present norm. We used the Finite Amplitude Impulse Response (FaIR) model, a reduced complexity climate model, as well as four of the Shared Socioeconomic Pathways (SSPs), SSP126, SSP245, SSP370 and SSP585, to test our hypothesis. We determined that the future impact of specific economic sectors, geographic regions, and greenhouse gas species deviates from their historical impact. We found that Asia and Africa will contribute to a greater share of the GMST anomaly in the future. We also determined that the warming from most of the greenhouse gas species, excluding carbon dioxide, is highest under the SSP370 scenario (the climate scenario that emphasizes regional rivalries related to climate policy). We concluded that the industrial sector would become more important under the SSPs that represent a lower degree of warming. This research augments the SSPs by considering specific variables not represented in the general SSP scenarios, determining the precise climate impacts of said variables. Additionally, this research helps to determine what emission reduction strategies can most efficiently reduce the GMST anomaly.    

    

* Retrofit assessment: Getting it right from the start  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400989752
:TOPICS: Quality and Practices in Nursing Home Care
:PUBLICATION_DATE: 2023-12-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.69554/zwvi1586")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400989752"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400989752"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400989752"))][Get cited by]]

OpenAlex: https://openalex.org/W4400989752 (Open access: False)
    
[[https://openalex.org/A5105082305][Richard Fitton]], [[https://openalex.org/A5076001888][William Swan]], No host. None(None)] 2023. https://doi.org/10.69554/zwvi1586 
     
The UK has some of the oldest buildings in Europe. They are also some of the worst performing in terms of energy performance. In tandem with these issues the UK has committed to making a substantial reduction in CO2 emissions. UK homes are currently responsible for almost 20 per cent of CO2 emissions. This leaves little option other than to make considerable progress with the retrofitting of homes to improve their energy performance. This is a technical process, however, and can introduce risks to building and their occupants. Examples exist of homes being retrofitted with disastrous consequences. Some of these issues can be due to the lack of thorough examination of a home before it undergoes a retrofit. This paper proposes a method that provides a detailed pre-retrofit assessment of a home, to fall in line with PAS 2035, a standard that provides guidance around publicly funded retrofit in the UK.    

    

* Supply chain as key driver for sustainability  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400992417
:TOPICS: Conceptualizing the Circular Economy and Sustainable Supply Chains, Developing Evidence-Informed Supply Chain Management Knowledge
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.69554/xmjp4140")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400992417"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400992417"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400992417"))][Get cited by]]

OpenAlex: https://openalex.org/W4400992417 (Open access: False)
    
[[https://openalex.org/A5058150988][Torsten Becker]], No host. None(None)] 2024. https://doi.org/10.69554/xmjp4140 
     
As the importance of sustainability is rising on the corporate agenda, companies need to provide environmental impact reduction plans to shareholders, banks and other stakeholders. The Paris Agreement urges companies to reduce carbon emissions to net zero by 2050, to achieve the goal of maximum 1.5°C temperature increase. A benchmarking study of sustainability performance was conducted on the environmental reports of 59 companies, and their plans for emission reductions were analysed. From the results, a framework to define CO2 reduction targets to achieve net zero has been devised for companies, starting from now.    

    

* A novel approach to integrate CCHP systems with desalination for sustainable energy and water solutions in educational buildings  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401019919
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization, Solar-Powered Water Desalination Technologies, Advancements in Water Purification Technologies
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2166/wst.2024.257")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401019919"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401019919"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401019919"))][Get cited by]]

OpenAlex: https://openalex.org/W4401019919 (Open access: True)
    
[[https://openalex.org/A5013878022][Faizah Mohammed Bashir]], [[https://openalex.org/A5094200523][Emmanuel Falude]], [[https://openalex.org/A5093016062][Ibtihaj Saad Rashed Alsadun]], [[https://openalex.org/A5001360030][Hakim Hamdoun]], [[https://openalex.org/A5024684683][Mohamed Ahmed Said Mohamed]], [[https://openalex.org/A5090156213][Nahla M. Shannan]], [[https://openalex.org/A5067899491][Ahmad Usman Naibi]], Water Science & Technology. None(None)] 2024. https://doi.org/10.2166/wst.2024.257 
     
ABSTRACT This study presents a novel approach to integrating combined cooling, heating, and power (CCHP) systems with water desalination for enhanced energy and water management in educational buildings. Two distinct layouts for CCHP and desalination systems are introduced: one prioritizing efficient power generation to meet electricity demands while providing waste heat for desalination, and the other focusing on balancing cooling and heating loads alongside water desalination. Both layouts are tailored to meet the building's energy and water demands while considering operational efficiency. Optimization of these layouts against traditional systems using the bat search algorithm emphasizes economic viability and the gas engine's operational flexibility, which are crucial for partial load operation. In addition, an environmental assessment compares the proposed CCHP-desalination systems with conventional setups, assessing CO2 emission reductions and overall sustainability. The evaluation encompasses key environmental metrics, such as resource consumption and the integration of renewable energy sources. Results highlight significant CO2 emission reductions across various gas engine capacities, with notable enhancements in economic and environmental performance achieved by selecting a 3,250 kW gas engine within the CCHP-desalination system. This choice not only maximizes the annual profit but also reduces CO2 emissions by 57% compared to conventional systems, underscoring the system's sustainability benefits.    

    

* АSSESSING THE EFFECTIVENESS OF AN INVESTMENT PROJECT TO REDUCE THE CARBON FOOTPRINT IN THE ENERGY SECTOR  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401019753
:TOPICS: Global Energy Transition and Fossil Fuel Depletion, Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-01-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.34925/eip.2023.161.12.141")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401019753"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401019753"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401019753"))][Get cited by]]

OpenAlex: https://openalex.org/W4401019753 (Open access: False)
    
[[https://openalex.org/A5105014731][Н.С. ЛЮЛЬЧЕНКО]], [[https://openalex.org/A5012890197][Р. В. Зайцев]], [[https://openalex.org/A5041507013][Anna Terekhova]], [[https://openalex.org/A5105050220][С.Р. ТАШОВА]], Экономика и предпринимательство. None(12(161))] 2024. https://doi.org/10.34925/eip.2023.161.12.141 
     
В рамках статьи в теоретическом и практическом ключе рассмотрены вопросы оценки инвестиционного проекта, связанного с снижением эмиссии CO2 в атмосферу связанную с деятельностью объектов энергетики. Особый фокус сделан на природе эмиссии CO2 и возможностях борьбы с ним в рамках зеленой энергетики. В работе рассмотрен как исторический опыт так и перспективные проекты в сфере концепции нулевых выбросов. Оценивается вклад ВИЭ в мировую энергетику и важность дальнейшей работы в сфере зеленой электрогенерации. Within the framework of articles on theoretical and practical key issues in assessing an investment project related to the reduction of CO2 emissions into the atmosphere associated with energy facilities. Particular focus is placed on CO2 emissions into the environment and the possibilities of combating them within the framework of green energy. The work includes both historical experience and promising projects in the field of the concept of the UK zero. The contribution of renewable energy sources to the global energy sector and further work in the field of green electricity generation are assessed.    

    

* Formate Dehydrogenase: Recent Developments for NADH and NADPH Recycling in Biocatalysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400982189
:TOPICS: Amino Acid Transport and Metabolism in Health and Disease, Enzyme Immobilization Techniques, Pancreatic Islet Dysfunction and Regeneration
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202401021")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400982189"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400982189"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400982189"))][Get cited by]]

OpenAlex: https://openalex.org/W4400982189 (Open access: False)
    
[[https://openalex.org/A5059230884][Artur Maier]], [[https://openalex.org/A5105049829][Lindelo M. Mguni]], [[https://openalex.org/A5055809666][Anna Ngo]], [[https://openalex.org/A5001303954][Dirk Tischler]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202401021 
     
Formate dehydrogenases (FDHs) catalyze the oxidation of formate to CO2 while reducing NAD(P)+ to NAD(P)H and are classified into two main classes: metal‐dependent (Mo‐ or W‐containing) and metal‐independent FDHs. The latter are oxygen‐tolerant and relevant as a cofactor regeneration system for various bioprocesses and gained more and more attention due to their ability to catalyze the reverse CO2 reduction. This review gives an overview of metal‐independent FDHs, the recent advances made in this field, and their relevance for future applications in biocatalysis. This includes the exploitation of novel FDHs which have altered co‐substrate specificity as well as enzyme engineering approaches to improve process stability and general performance.    

    

* Dual Electron Donating Metal‐Boron Reaction Center Boosts Electrocatalytic Urea Synthesis from N2 and CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401039536
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400304")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401039536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401039536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401039536"))][Get cited by]]

OpenAlex: https://openalex.org/W4401039536 (Open access: False)
    
[[https://openalex.org/A5059644018][Nuttapon Yodsin]], [[https://openalex.org/A5083240495][Poobodin Mano]], [[https://openalex.org/A5086087324][Kaito Takahashi]], [[https://openalex.org/A5077457552][supawadee namuangruk]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400304 
     
Urea (NH2CONH2) production by electrosynthesis at mild conditions has been hampered due to the lack of systematic evaluation of pathways in effectively activating inert N2 and CO2 molecules and facilitating the formation of C‐N bonds. This work, we evaluated 16 transition metal (M) atoms anchored on a carbon nitride nanosheet with boron (B) doping (M‐B@C2N) for boosting urea production by theoretical calculations. All possible urea synthesis pathways, (i) CO2 pathway, (ii) OCOH pathway, (iii) CO pathway, and (iv) NCON pathway, were comparatively studied on Cu, Fe, Co, Ni‐B@C2N. This systematic calculation identified that the first reduction of *N2 is the key step for urea synthesis. We found that the bond index of *N2 shows a strong correlation with ΔG*N2®*NNH, so they are promising descriptors for screening. Through the screening, we found that Nb‐ and Mo‐B@C2N show a low limiting potential of ‐0.56 and ‐0.53 V. Although previous studies found that spin could promote C‐C bond formation on M‐B@C2N, we found that for C‐N coupling, such effects by spin were only active for Nb‐B@C2N. Combining boron and early transition metal atoms allows for neighboring reaction sites that simultaneously donate electrons to activate inert N2 and CO2 for efficient urea synthesis.    

    

* Estrategias para Mejorar la Eficiencia Energética en Edificios de servicios públicos, en una Zona Climática Calurosa y Húmeda: Caso de Estudio en Guayaquil, Ecuador  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400977319
:TOPICS: Sustainable Construction and Green Building, Energy, Climate Change, and Environmental Impact Assessment
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.37116/revistaenergia.v21.n1.2024.651")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400977319"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400977319"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400977319"))][Get cited by]]

OpenAlex: https://openalex.org/W4400977319 (Open access: True)
    
[[https://openalex.org/A5051087502][E. Catalina Vallejo-Coral]], [[https://openalex.org/A5005944050][Luis Godoy-Vaca]], [[https://openalex.org/A5065720508][Francis Vásquez]], [[https://openalex.org/A5045752365][Geovanna Villacreses]], [[https://openalex.org/A5014063220][Marco Orozco]], [[https://openalex.org/A5021381139][Santiago Albero Navarro]], Revista Técnica Energía. 21(1)] 2024. https://doi.org/10.37116/revistaenergia.v21.n1.2024.651 
     
Since 2010, there has been an approximate annual increase of 1% in CO2 emissions due to buildings. The reduction of energy consumption and consequently the mitigation of Greenhouse Gases are global goals due to the global issue of climate change. A key step in achieving these goals is to improve the energy performance of buildings, thereby reducing energy consumption and emissions generated by the built environment. In this regard, the present research focuses on identifying and estimating strategies to reduce energy consumption in buildings known as Community Police Units (UPCs) located in the city of Guayaquil, which corresponds to a very hot and humid climate zone. The study consists of statistical analysis of the historical energy performance of 43 buildings sharing the same architectural design. Additionally, the selection of a representative building was made for energy use monitoring and energy simulation. The results revealed a potential saving of 16 000 kWh per year by reducing the control temperature of the air conditioning system by 1°C and adjusting the on/off schedule. This is equivalent to 1 150 USD and 5 metric tons of CO2 emissions.    

    

* Decarbonization of Heating and Cooling Systems of Buildings Located Nearby Surface Water Sources: Case Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400973982
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17153673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400973982"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400973982"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400973982"))][Get cited by]]

OpenAlex: https://openalex.org/W4400973982 (Open access: True)
    
[[https://openalex.org/A5056127547][Adriana Tokar]], [[https://openalex.org/A5074014125][Daniel Muntean]], [[https://openalex.org/A5084842362][Dănuț Tokar]], [[https://openalex.org/A5066339339][Daniel Bisorca]], Energies. 17(15)] 2024. https://doi.org/10.3390/en17153673 
     
The study was carried out to evaluate theoretically and in laboratory conditions the capacity of a hybrid heating and cooling system that sustainably uses thermal energy extracted from surface waters in order to decarbonize buildings located near water sources. The novelty of the research consists in the realization of two experimental systems, one for the rapid evaluation of the performance of the water–water heat pump heating system and one for the evaluation of the operating behavior of a cooling system with fan coil units. Starting with the heating and cooling demand, and the climatic and hydrological local characteristics, a hybrid system model for the heating and cooling of the analyzed building was established and implemented. The forecasted energy consumption and CO2 emissions for the operation of the new equipment were compared with the historical values of the old systems with which the building was equipped (thermal energy supply from the district heating and cooling system with an air conditioning unit). Also, the results were extrapolated for forecasting the energy potential of the surface waters. The study highlights a percentage reduction in annual energy consumption of 67.71% and CO2 emissions of 80.13% through the implementation of the hybrid system.    

    

* Optimal Combination of Net-Zero Pathways for Minimum Energy, Land, and Water Consumption in Chemical Production  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401078439
:TOPICS: Integrated Management of Water, Energy, and Food Resources, State-of-the-Art in Process Optimization under Uncertainty, Integration of Renewable Energy Systems in Power Grids
:PUBLICATION_DATE: 2024-07-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.iecr.4c01649")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401078439"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401078439"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401078439"))][Get cited by]]

OpenAlex: https://openalex.org/W4401078439 (Open access: True)
    
[[https://openalex.org/A5087723417][Paolo Gabrielli]], [[https://openalex.org/A5100495088][Hanne Goericke]], [[https://openalex.org/A5027453034][Lorenzo Rosa]], Industrial & Engineering Chemistry Research. None(None)] 2024. https://doi.org/10.1021/acs.iecr.4c01649 
     
Net-zero chemical production can be achieved through electrification, biomass-based processes, and carbon capture, utilization, and storage. However, these net-zero pathways require more resources than business-as-usual processes. One possibility to produce net-zero chemicals at a lower resource consumption is the combination of net-zero pathways based on locally available resources. This study determines the optimal combinations of net-zero pathways for producing chemicals with net-zero emissions that minimize the use of renewable energy, land, and water while complying with local waste biomass and CO2 storage availability. Waste biomass is defined as residue biomass that does not compete for land and water with other sectors. The analysis is performed worldwide at the country level and considers the production of ammonia, methanol, and plastics, which, when combined, account for ∼5% of the global CO2 emissions. Findings show that, when considering net-zero pathways individually, waste biomass is preferably used for producing ammonia and methanol, whereas carbon capture and storage is preferably deployed for plastics production. At the same time, a mixed strategy using carbon capture, utilization, and storage, and waste biomass, allows one to achieve a net-zero chemical industry with a nearly 60% reduction in energy consumption and 90% reduction in land and water consumption, with respect to single-pathway strategies. Finally, we find that adopting a net-zero portfolio that minimizes water allows water consumption to be reduced by more than 90% and land consumption to be reduced by more than 70% at the cost of an energy increase of only 5%, when compared to the minimum-energy portfolio.    

    

* Has the EU Emissions Trading System Worked Properly?  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400984854
:TOPICS: Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17153651")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400984854"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400984854"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400984854"))][Get cited by]]

OpenAlex: https://openalex.org/W4400984854 (Open access: True)
    
[[https://openalex.org/A5002729048][Chia‐Lin Chang]], [[https://openalex.org/A5089722184][Jukka Ilomäki]], [[https://openalex.org/A5006877478][Hannu Laurila]], Energies. 17(15)] 2024. https://doi.org/10.3390/en17153651 
     
Climate change poses an unprecedented global challenge, which prompts nations to adopt new strategies to mitigate greenhouse gas emissions. The European Union emissions trading system (EU ETS) is a cornerstone of the EU’s efforts towards a cost-effective fight against climate change. This study examines the effectiveness of the EU ETS by analyzing monthly data from December 2008 to December 2021, with the focus on CO2 emission allowance futures prices, renewable energy indices, coal prices, oil prices, and fossil energy indices. The key findings are as follows: The CO2 emission allowance futures prices have averaged EUR 14.83 per ton, ranging from EUR 2.87 to EUR 76.81, which shows a significant upward trend. The renewable energy index also demonstrated strong growth, with a mean 1562.07 and maximum 4571.96. Coal prices have averaged EUR 65.32 per ton, while Brent oil prices averaged EUR 59.85 per barrel. A cointegration analysis revealed a long-run equilibrium relationship between these variables. The Vector Error Correction model (VECM) revealed significant negative responses to long-run equilibrium deviations of the renewable energy index (−0.0155) and oil prices (−0.0236), a significant negative short-run response of CO2 prices to their own lagged values (−0.223), and a significant positive short-run effect of oil prices on the fossil energy index (0.254). These results suggest the EU ETS has created significant linkages between carbon, energy, and financial markets. The study concludes that while the EU ETS has made progress in motivating emissions reductions and promoting renewable energy, the system’s efficacy still needs improvement.    

    

* Catalytic composition and fuel influence on anodic processes characteristics of solid polymer electrolyte fuel cells  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401027802
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2008-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18500/1608-4039-2008-8-1-33-39")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027802"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027802"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027802"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027802 (Open access: False)
    
[[https://openalex.org/A5042546780][Н. В. Кулешов]], [[https://openalex.org/A5010839364][S. V. Grigoriev]], Electrochemical Energetics. 8(1)] 2008. https://doi.org/10.18500/1608-4039-2008-8-1-33-39 
     
It was studied an influence of prior carbon treatment (temperature and gas conditions, mass content of waterproofing agent) on activity of platinum catalyst, synthesized on disperse carbon carrier. It was shown that characteristics of anodic processes depend on quantity of solid polymer electrolyte in catalytic composition. Optimal content of ion exchange polymer under varied degree of carbon carrier waterproofing (used for synthesis of platinum catalyst) is not equal. In a case of platinum catalyst synthesized on a base of carbon carrier with the addition of waterproofing agent (10 mass %), the highest current density of fuel cell functioning on pure oxygen corresponds to 15-20 mass % of polymer content in a layer and in a case of air – 10-15 mass %. Impurity of carbonic gas in anodic fuel leads to decrease of current density on fuel cell withdrawal not only because of partial pressure decrease. The reason of parameter worsening is partial platinum poisoning with CO, appearing after CO2 reduction.    

    

* Stability of Nitrogen-Doped Activated Carbon as an Electrocatalyst for the Oxygen Reduction Reaction in Various Storage Media  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401106446
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-07-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29153611")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401106446"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401106446"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401106446"))][Get cited by]]

OpenAlex: https://openalex.org/W4401106446 (Open access: True)
    
[[https://openalex.org/A5100375904][Tao Zhang]], [[https://openalex.org/A5051619042][Songlin Zuo]], Molecules. 29(15)] 2024. https://doi.org/10.3390/molecules29153611 
     
Besides outstanding catalytic performance, the stability of nitrogen-doped carbon materials during storage is equally crucial for practical applications. Therefore, we conducted the first investigation into the stability of highly nitrogen-doped activated carbon (AC-NC-T) obtained by modifying activated carbon with CO2/NH3 in different storage media (air, vacuum and N2). The results of the catalysis of the oxygen reduction reaction and the activation of peroxymonosulfate for degrading bisphenol A by AC-NC-T show that the catalytic activity of AC-NC-T stored in air decays most prominently, while the performance attenuated only marginally when stored in vacuum and N2. The results from N2 adsorption isotherms, Raman spectroscopy, elemental and X-ray photoelectron spectroscopy indicate that the decline in catalytic activity is due to the presence of oxygen in the environment, causing a decrease in absolute contents of pyridinic N (N-6) and graphitic nitrogen (N-Q). After being stored in an air atmosphere for 28 days, the absolute contents of N-6 and N-Q in AC-NC-950 decreased by 19.3% and 12.1%, respectively. However, when stored in a vacuum or N2, the reduction in both was less than 7%. This study demonstrates that reducing oxygen concentration during storage is crucial for preserving high catalytic activity of nitrogen-containing carbon materials.    

    

* Severe Spaceflight-Associated Neuro-Ocular Syndrome in an Astronaut With 2 Predisposing Factors  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400978364
:TOPICS: Physiological Effects of Space Travel and Microgravity, Genetic and Physiological Adaptations to High-Altitude Environments, Patent Foramen Ovale and Cerebrovascular Events
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1001/jamaophthalmol.2024.2385")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400978364"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400978364"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400978364"))][Get cited by]]

OpenAlex: https://openalex.org/W4400978364 (Open access: False)
    
[[https://openalex.org/A5075990703][Tyson Brunstetter]], [[https://openalex.org/A5014977670][Sara R. Zwart]], [[https://openalex.org/A5003574926][Keith Brandt]], [[https://openalex.org/A5102897222][David M. Brown]], [[https://openalex.org/A5085421865][S. J. Clemett]], [[https://openalex.org/A5075932993][Grace L. Douglas]], [[https://openalex.org/A5063216533][Charles R. Gibson]], [[https://openalex.org/A5037131236][Steven S. Laurie]], [[https://openalex.org/A5027507681][Andrew G. Lee]], [[https://openalex.org/A5022200003][Brandon R. Macias]], [[https://openalex.org/A5051466856][Thomas H. Mader]], [[https://openalex.org/A5052826562][Sara S. Mason]], [[https://openalex.org/A5064406408][Jessica U. Meir]], [[https://openalex.org/A5084390618][Andrew Morgan]], [[https://openalex.org/A5056614821][Mayra Nelman]], [[https://openalex.org/A5044769585][Nimesh B. Patel]], [[https://openalex.org/A5103390147][Clarence F. Sams]], [[https://openalex.org/A5102839281][Rahul Suresh]], [[https://openalex.org/A5017664835][William J. Tarver]], [[https://openalex.org/A5092653716][Ann Tsung]], [[https://openalex.org/A5037315341][Mary G. Van Baalen]], [[https://openalex.org/A5075879804][Scott M. Smith]], JAMA Ophthalmology. None(None)] 2024. https://doi.org/10.1001/jamaophthalmol.2024.2385 
     
Importance Understanding potential predisposing factors associated with spaceflight-associated neuro-ocular syndrome (SANS) may influence its management. Objective To describe a severe case of SANS associated with 2 potentially predisposing factors. Design, Setting, and Participants Ocular testing of and blood collections from a female astronaut were completed preflight, inflight, and postflight in the setting of the International Space Station (ISS). Exposure Weightlessness throughout an approximately 6-month ISS mission. Mean carbon dioxide (CO 2 ) partial pressure decreased from 2.6 to 1.3 mm Hg weeks before the astronaut’s flight day (FD) 154 optical coherence tomography (OCT) session. In response to SANS, 4 B-vitamin supplements (vitamin B 6 , 100 mg; L-methylfolate, 5 mg; vitamin B 12 , 1000 μg; and riboflavin, 400 mg) were deployed, unpacked on FD153, consumed daily through FD169, and then discontinued due to gastrointestinal discomfort. Main Outcomes and Measures Refraction, distance visual acuity (DVA), optic nerve, and macular assessment on OCT. Results Cycloplegic refraction was −1.00 diopter in both eyes preflight and +0.50 − 0.25 × 015 in the right eye and +1.00 diopter in the left eye 3 days postflight. Uncorrected DVA was 20/30 OU preflight, 20/16 or better by FD90, and 20/15 OU 3 days postflight. Inflight peripapillary total retinal thickness (TRT) peaked between FD84 and FD126 (right eye, 401 μm preflight, 613 μm on FD84; left eye, 404 μm preflight, 636 μm on FD126), then decreased. Peripapillary choroidal folds, quantified by surface roughness, peaked at 12.7 μm in the right eye on FD154 and 15.0 μm in the left eye on FD126, then decreased. Mean choroidal thickness increased throughout the mission. Genetic analyses revealed 2 minor alleles for MTRR 66 and 2 major alleles for SHMT1 1420 (ie, 4 of 4 SANS risk alleles). One-week postflight, lumbar puncture opening pressure was normal, at 19.4 cm H 2 O. Conclusions and Relevance To the authors’ knowledge, no other report of SANS documented as large of a change in peripapillary TRT or hyperopic shift during a mission as in this astronaut, and this was only 1 of 4 astronauts to experience chorioretinal folds approaching the fovea. This case showed substantial inflight improvement greater than the sensitivity of the measure, possibly associated with B-vitamin supplementation and/or reduction in cabin CO 2 . However, as a single report, such improvement could be coincidental to these interventions, warranting further evaluation.    

    

* Comparison of the Temperature, Radiation, and Heat Flux Distribution of a Hydrogen and a Methane Flame in a Crucible Furnace Using Numerical Simulation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400974180
:TOPICS: Inverse Radiative Heat Transfer Analysis, Dynamics of Turbulent Combustion Systems, Chemical Kinetics of Combustion Processes
:PUBLICATION_DATE: 2024-07-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/hydrogen5030026")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400974180"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400974180"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400974180"))][Get cited by]]

OpenAlex: https://openalex.org/W4400974180 (Open access: True)
    
[[https://openalex.org/A5068308844][Alexander Mages]], [[https://openalex.org/A5037568055][Alexander Sauer]], Hydrogen. 5(3)] 2024. https://doi.org/10.3390/hydrogen5030026 
     
Sustainable technologies to replace current fossil solutions are essential to meet future CO2 emission reduction targets. Therefore, this paper compares key performance indicators of a hydrogen- and a methane-flame-fired crucible furnace with computational fluid dynamics simulations at identical firing powers, aiming to fully decarbonize the process. Validated numerical models from the literature were used to compare temperatures, radiation fields, radiation parameters and heat transfer characteristics. As a result, we observed higher combustion temperatures and a 19.0% higher fuel utilization rate in the hydrogen case, indicating more efficient operating modes, which could be related to the increased radiant heat flux and temperature ranges above 1750 K. Furthermore, higher scattering of the heat flux distribution on the crucible surface could be determined indicating more uneven melt bath temperatures. Further research could focus on quantifying the total fuel consumption required for the heating up of the furnace, for which a transient numerical model could be developed.    

    

* Exploring biofilm-forming bacteria for integration into BioCircuit wastewater treatment  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400972910
:TOPICS: Microbial Fuel Cells and Electrogenic Bacteria Technology, Microbial Nitrogen Cycling in Wastewater Treatment Systems, Biohydrometallurgical Processes for Metal Extraction
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.62063/ecb-28")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400972910"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400972910"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400972910"))][Get cited by]]

OpenAlex: https://openalex.org/W4400972910 (Open access: False)
    
[[https://openalex.org/A5017493652][Chontisa Sukkasem]], The European Chemistry and Biotechnology Journal. None(2)] 2024. https://doi.org/10.62063/ecb-28 
     
This study aimed to investigate the presence of biofilm-forming bacteria within high sulfide sludge obtained from a rubber wastewater treatment plant and assess their suitability for application within a BioCircuit System (BCS) as a symbiotic community for treating nutrient-rich wastewater. The sludge samples were collected and subjected to microbial culture techniques, wherein pure cultures were isolated based on morphological characteristics observed under a light microscope, followed by assessment of motility using swarm agar. Subsequent identification was conducted utilizing the 16S rRNA gene sequencing method, and the isolated bacteria were introduced into the BCS. A 12 mL microbial fuel cell test was conducted to evaluate their power generation capabilities. The wastewater treatment process involved inoculating the BCS with 20% crude rubber wastewater sludge, and the system was initiated at a flow rate of 0.5 L/min for a month. Upon achieving an open-circuit voltage exceeding 50 mV, the BCS was operated at incremental flow rates (0.5-1.0, 1.0-1.5, and 1.5-2.0 mL/ min) over a period of 6 months. Real-time monitoring of voltage, flow rate, and energy consumption was facilitated through an internet-of-things online program. Weekly sampling and analysis of influent and effluent, focusing on chemical oxygen demand (COD), sulfate, and sulfide concentrations, were conducted. Additionally, the BioCircuit voltage was recorded every 5 minutes. The results revealed the presence of six group-forming shaped bacteria identified as Bacillus tequilensis, Bacillus sp., Ferribacterium limneticum, Bacillus weihenstephanesis, and Mycobacterium sp., respectively. The optimal flow rate of 1.5 L/min yielded a maximum voltage of 1.2 V and demonstrated high wastewater treatment efficiency. Economically, the BCS operation exhibited a power consumption rate of 0.257 kWhr/m3 of treated wastewater, leading to an 88.90% reduction in carbon footprint compared to aerated lagoon treatment, equivalent to 50.94 kg CO2/m3 of treated wastewater or 183,384 kg CO2/yr for a 10 m3 plant. These findings underscore the potential of the BCS in conjunction with group-forming shaped bacteria communities for various industrial wastewater treatment applications.    

    

* Comparison of Exhaust Gas Emissions of a Vehicle with an Internal Combustion Engine in High and Low Vehicular Congestion for a High Altitude City  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401036584
:TOPICS: Estimating Vehicle Fuel Consumption and Emissions, Chemical Kinetics of Combustion Processes, Health Effects of Air Pollution
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18502/espoch.v3i3.16623")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401036584"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401036584"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401036584"))][Get cited by]]

OpenAlex: https://openalex.org/W4401036584 (Open access: True)
    
[[https://openalex.org/A5046858313][Jorge Lema]], ESPOCH Congresses The Ecuadorian Journal of S T E A M. None(None)] 2024. https://doi.org/10.18502/espoch.v3i3.16623 
     
Pollution generated by the automotive sector is one of the biggest concerns in the city of Quito. This is due to the fact that the majority of vehicles in the automotive fleet use fossil fuels as a source of propulsion energy. In addition, the heterogeneity of the technologies of the fuel injection systems means that the control of polluting emissions is highly limited. On the other hand, due to the high number of vehicles and the topographical characteristics of the city, high traffic congestion is generated during rush hours, producing abrupt changes in acceleration and reduction of stoichiometric mixtures. Based on the above, it was pertinent to compare the exhaust gas emissions that are produced in high and low vehicular congestion for a vehicle with an internal combustion engine Likewise, the correlations of the gases for both scenarios were determined. To do this, emissions were measured in a Mazda 3 vehicle on a major city route during rush hours and on weekends. A Kane Autoplus gas analyzer was used for exhaust gas measurement, and data logging was done on the Kane Live app. The results showed that in rush hours, the vehicle emits higher amounts of CO2, CO, and HC up to 0.7%; 128.5%; and 65.5%, respectively. There are moderate and strong correlations of O2-CO2 and CO-HC in high and low vehicular congestion, with Pearson’s correlation values greater than 0.5. Keywords: exhaust gases, internal combustion engine, pollution, route, rush hours, traffic. Resumen La contaminación generada por el sector automotriz, es uno de los mayores problemas que enfrenta la ciudad de Quito. Esto se debe a que la mayoría de vehículos del parque automotor, utilizan combustibles fósiles como fuente de energía de propulsión. Además, la heterogeneidad de las tecnologías de los sistemas de inyección de combustible, hace que el control de emisiones contaminantes se limite considerablemente. Por otro lado, debido al elevado número de vehículos y a las características topográficas de la ciudad, se genera una elevada congestión vehicular en horas pico, produciendo cambios abruptos de aceleraciones y reducción de las mezclas estequiométricas. Con base a lo expuesto, fue pertinente comparar las emisiones de gases de escape que se producen en alta y baja congestión vehicular para un vehículo con motor de combustión interna, y así mismo, se determinó las correlaciones de los gases para ambos escenarios. Para ello, se midió las emisiones en un vehículo Mazda 3 sobre una ruta importante de la ciudad en horas pico y fines de semana. Se utilizó un analizador de gases Kane Autoplus para la medición de los gases de escape, y el registro de datos se efectuó en la aplicación Kane Live. Los resultados mostraron que en horas pico, el vehículo emite mayores cantidades de CO2, CO, HC de hasta el 0,77%; 6,66%; 94,69%, respectivamente. Existen moderadas y fuertes correlaciones de O2-CO2 y CO-HC en alta y baja congestión vehicular, con valores de correlación de Pearson superior a 0,5. Palabras Clave: contaminación, gases de escape, horas pico, motor de combustión interna, ruta, tráfico.    

    

* Switching off Competing Hydrogen Formation in CO2 Electroreduction via Substrate Defect Engineering  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4401000461
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Engineering of Surface Nanostructures
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4772767/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401000461"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401000461"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401000461"))][Get cited by]]

OpenAlex: https://openalex.org/W4401000461 (Open access: True)
    
[[https://openalex.org/A5100435866][Lei Wang]], [[https://openalex.org/A5007921737][Haozhou Yang]], [[https://openalex.org/A5048313381][Na Guo]], [[https://openalex.org/A5031292832][Shibo Xi]], [[https://openalex.org/A5037340591][Haiyuan Zou]], [[https://openalex.org/A5100609074][Jiayi Chen]], [[https://openalex.org/A5022239454][Lei Fan]], [[https://openalex.org/A5023257092][Yukun Xiao]], [[https://openalex.org/A5051694258][Qian He]], [[https://openalex.org/A5047901288][Lele Duan]], [[https://openalex.org/A5030557634][Pengfei Wei]], [[https://openalex.org/A5020450516][Guoxiong Wang]], [[https://openalex.org/A5100763540][Chun Zhang]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4772767/v1  ([[https://www.researchsquare.com/article/rs-4772767/latest.pdf][pdf]])
     
Abstract Carbon nanotubes (CNTs) have emerged as effective substrates for immobilizing molecular catalysts towards many electrocatalytic reactions, such as CO2 reduction (CO2R). However, despite the prevailing notion of strong π-π stackings between the molecular catalyst and CNTs, our understanding of their interactions remains inadequate. Here, we employ functionalized nickel phthalocyanines (NiPc), established CO2R catalysts, immobilized on CNTs as a model system to investigate the catalyst/substrate interactions. Firstly, we find that NiPc-catalysts preferentially anchor on the defects on CNTs rather than adhering via π-π interaction with the ideal graphene-like CNT surface, a finding further validated by theoretical simulations. Consequently, we observe the least uniform NiPc-catalysts distributions on CNTs when the defect-content is the lowest. Notably, this combination exhibits the highest CO2R selectivity and activity despite the non-uniform catalyst distributions. Through operando X-ray adsorption spectroscopy and theoretical simulations, we reveal that high CNT defect-contents tend to induce substantial D4h symmetry breaking of the NiPc plane under cathodic potential, consequently resulting in reduced CO2R selectivity and activity. Therefore, maintaining a low to moderate defect level on CNTs is critical. Guided by this understanding, we fine-tune the defect-level of CNTs through graphitization, achieving an unprecedently high selectivity for CO2 to CO conversion (CO to H2 molar ratio exceeding 16100:1, a remarkable suppression of hydrogen evolution by three orders of magnitude) and improved intrinsic-activity (turnover frequency of 1072 s−1 at −0.60 V vs. reversible hydrogen electrode) on an optimized Ni-Pc/CNTs composite. Furthermore, we achieved practical relevant CO production in a zero-gap electrolyzer (electrode size of 100 cm-2), reaching high current (up to 50 A), with high CO selectivity (> 95%) and reasonably low cell voltage (approximately 3.5 V), substantially outperforming the state-of-the-art silver catalyst. Moreover, we extend this knowledge to a Co-based molecular catalyst, achieving a high Faradaic efficiency (over 50%) towards methanol production with a high partial current density over 150 mA cm−2. Overall, our findings underscore the significance of tuning defect levels on CNT substrates for achieving desired performance for immobilized molecular catalysts.    

    
