#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Wed Oct  9 01:19:43 2024

Found 72 results from 2024-10-02 to 2024-10-09
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Ugi's amine based coordination polymers as a synergistic catalysts for electrocatalytic reduction of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403033444
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dt01181c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403033444"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403033444"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403033444"))][Get cited by]]

OpenAlex: https://openalex.org/W4403033444 (Open access: False)
    
[[https://openalex.org/A5090357376][Mikhail Khrizanforov]], [[https://openalex.org/A5107686405][Farida F. Nailieva]], [[https://openalex.org/A5015946707][Kamil Ivshin]], [[https://openalex.org/A5055400630][Almaz Zagidullin]], [[https://openalex.org/A5093839011][Anastasiia P. Samorodnova]], [[https://openalex.org/A5041409633][Ruslan P. Shekurov]], [[https://openalex.org/A5095934822][Polina Milyukova]], [[https://openalex.org/A5065148995][Artem Laskin]], [[https://openalex.org/A5063649629][Alexander S. Novikov]], [[https://openalex.org/A5032894349][Vasili A. Miluykov]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d4dt01181c 
     
The escalating concentration of carbon dioxide in the atmosphere is a pressing environmental concern, necessitating the development of efficient technologies for CO 2 reduction and utilization. In this context, metal-organic frameworks...    

    

* Simultaneous electrochemical upgrading of Polyethylene Terephthalate plastic and carbon dioxide into valuable chemicals  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403077498
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Energy Consumption in Mobile Devices and Networks, Global E-Waste Recycling and Management
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124667")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403077498"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403077498"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403077498"))][Get cited by]]

OpenAlex: https://openalex.org/W4403077498 (Open access: False)
    
[[https://openalex.org/A5100434459][Hongxia Liu]], [[https://openalex.org/A5038582533][Ziqing Wang]], [[https://openalex.org/A5100930786][Yanan He]], [[https://openalex.org/A5101916473][Xin Hu]], [[https://openalex.org/A5100349500][Lei Liu]], Applied Catalysis B Environment and Energy. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124667 
     
No abstract    

    

* Back Cover: Metal–Organic Framework Supported Low‐Nuclearity Cluster Catalysts for Highly Selective Carbon Dioxide Electroreduction to Ethanol  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403082653
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202416813")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403082653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403082653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403082653"))][Get cited by]]

OpenAlex: https://openalex.org/W4403082653 (Open access: False)
    
[[https://openalex.org/A5100381379][Bing Shao]], [[https://openalex.org/A5010225600][Du Shu Huang]], [[https://openalex.org/A5008056492][Rui‐Kang Huang]], [[https://openalex.org/A5031239250][Xing‐Lu He]], [[https://openalex.org/A5050700483][Yan Luo]], [[https://openalex.org/A5102689986][Yi‐Lei Xiang]], [[https://openalex.org/A5101860097][Linbin Jiang]], [[https://openalex.org/A5042836811][Min Dong]], [[https://openalex.org/A5008199157][Shixiong Li]], [[https://openalex.org/A5100350970][Zhong Zhang]], [[https://openalex.org/A5065774274][Jin Huang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202416813 
     
No abstract    

    

* Back Cover: Metal–Organic Framework Supported Low‐Nuclearity Cluster Catalysts for Highly Selective Carbon Dioxide Electroreduction to Ethanol  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403082707
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202416813")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403082707"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403082707"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403082707"))][Get cited by]]

OpenAlex: https://openalex.org/W4403082707 (Open access: False)
    
[[https://openalex.org/A5100381379][Bing Shao]], [[https://openalex.org/A5010225600][Du Shu Huang]], [[https://openalex.org/A5008056492][Rui‐Kang Huang]], [[https://openalex.org/A5031239250][Xing‐Lu He]], [[https://openalex.org/A5050700483][Yan Luo]], [[https://openalex.org/A5102689986][Yi‐Lei Xiang]], [[https://openalex.org/A5101860097][Linbin Jiang]], [[https://openalex.org/A5042836811][Min Dong]], [[https://openalex.org/A5008199157][Shixiong Li]], [[https://openalex.org/A5100350970][Zhong Zhang]], [[https://openalex.org/A5065774274][Jin Huang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202416813 
     
No abstract    

    

* The Role of Surfactant in Electrocatalytic Carbon Dioxide Reduction in the Absence of Metal Cations  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403084997
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-10-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acselectrochem.4c00040")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403084997"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403084997"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403084997"))][Get cited by]]

OpenAlex: https://openalex.org/W4403084997 (Open access: True)
    
[[https://openalex.org/A5070399861][Hansaem Jang]], [[https://openalex.org/A5007746313][Adrian M. Gardner]], [[https://openalex.org/A5039937783][Lucy Jayne Walters]], [[https://openalex.org/A5027363723][Alex R. Neale]], [[https://openalex.org/A5039774913][Laurence J. Hardwick]], [[https://openalex.org/A5103513668][J.S. Roberts]], No host. None(None)] 2024. https://doi.org/10.1021/acselectrochem.4c00040 
     
No abstract    

    

* A Highly Conjugated Nickel(II)‐Acetylide Framework for Efficient Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403129175
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202418269")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403129175"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403129175"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403129175"))][Get cited by]]

OpenAlex: https://openalex.org/W4403129175 (Open access: False)
    
[[https://openalex.org/A5081215511][Yingying Qin]], [[https://openalex.org/A5101934276][Yang Wang]], [[https://openalex.org/A5073851246][Jian Lu]], [[https://openalex.org/A5041540316][Linli Xu]], [[https://openalex.org/A5006003842][Wai‐Yeung Wong]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202418269 
     
The incorporation of transition‐metal single atoms as molecular functional entities into the skeleton of graphdiyne (GDY) to construct novel two‐dimensional (2D) metal‐acetylide frameworks, known as metalated graphynes (MGYs), is a promising strategy for developing efficient catalysts, which can combine the tunable charge transfer of GDY frameworks, the catalytic activity of metal and the precise distribution of single metallic centers. Herein, four highly conjugated MGY photocatalysts based on NiII, PdII, PtII, and HgII were synthesized for the first time using the ‘bottom‐up’ strategy through the use of M–C bonds (–C≡C–M–C≡C–). Remarkably, the NiII‐based graphyne (TEPY‐Ni‐GY) exhibited the highest CO generation rate of 18.3 mmol g‐1 h‐1 and a selectivity of 98.8%. This superior performance is attributed to the synergistic effects of pyrenyl and –C≡C–Ni(PBu3)2–C≡C– moieties. The pyrenyl block functions as an intramolecular π‐conjugation channel, facilitating kinetically favorable electron transfer, while the –C≡C–Ni(PBu3)2–C≡C– moiety serves as the catalytic site that enhances CO2 adsorption and activation, thereby suppressing competitive hydrogen evolution. This study provides a new perspective on MGY‐based photocatalysts for developing highly active and low‐cost catalysts for CO2 reduction.    

    

* Carbon Dioxide and Nitrate Reduction Reactions Tailoring Kinetics Over Cu2o with Mesoporous Carbon Channels for Boosting Electrocatalytic Urea Synthesis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403183577
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4978955")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403183577"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403183577"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403183577"))][Get cited by]]

OpenAlex: https://openalex.org/W4403183577 (Open access: False)
    
[[https://openalex.org/A5100709035][Jiamin Zhao]], [[https://openalex.org/A5019381699][Ying Yuan]], [[https://openalex.org/A5104339006][Meimei Kou]], [[https://openalex.org/A5074336795][Jinsheng Zhao]], [[https://openalex.org/A5103152647][Wei Lin]], [[https://openalex.org/A5074336795][Jinsheng Zhao]], [[https://openalex.org/A5047349369][Panagiotis Tsiakaras]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4978955 
     
No abstract    

    

* Effect of urban vegetation cover on CO2 reduction in the city  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403140935
:TOPICS: Global Methane Emissions and Impacts, Applications of Remote Sensing in Geoscience and Agriculture, Estimating Vehicle Fuel Consumption and Emissions
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.31705/cers.2024.28")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403140935"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403140935"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403140935"))][Get cited by]]

OpenAlex: https://openalex.org/W4403140935 (Open access: False)
    
[[https://openalex.org/A5107763076][H.K.P. Chanika]], [[https://openalex.org/A5092061121][Nilanka Harshani Weerasinghe]], [[https://openalex.org/A5075098117][R.U. Halwatura]], No host. None(None)] 2024. https://doi.org/10.31705/cers.2024.28 
     
Rising urban carbon dioxide levels have emerged as a critical issue due to their adverse effects on public health and the environment. Trees are a natural and sustainable solution to mitigate urban carbon dioxide (CO2) concentrations, as they absorb CO2 from the atmosphere through photosynthesis. However, the specific relationship between tree density and CO2 concentration within cities is unclear. The main objectives of this research are to determine the relationship between tree density and CO2 concentration reduction in cities and to identify the optimum tree density to reduce the CO2 level in the city to obtain the required CO2 level. For this study, data were collected in the densely urbanized city of Colombo and various urban areas within the Hambantota district. Tree densities and CO2 concentration reduction data were collected from 300 sample plots, each with a fixed size of 50m x 50m, near roads in selected urban areas. When calculating tree density, it is important to calculate canopy volumes of trees. It depends on canopy height, crown diameter and canopy shape. The tree density of the sample plot was calculated by dividing the total canopy volume by the area of the sample plot. A digital portable CO2 meter was used to measure the CO2 level. First the CO2 concentration was measured at the centre of the road and then the CO2 concentration was measured at the centre of the sample plot. The reduction in CO2 level was calculated by the difference between these two readings. By analysing tree densities and CO2 concentration data collected through field data studies, a linear relationship was obtained between tree density and CO2 concentration reduction in urban areas. The plotted line got a R2 value of 0.8806 indicating a well-fitting model. Therefore, this linear plotted line can be described as a reasonable fitted line representing all collected data. Also, the data was classified based on the CO2 concentration in the centre of the road and the behaviour of the CO2 concentration reduction Vs tree density relationship was studied in each range. A linear relationship was obtained in each of those ranges. When all the collected data were classified as residential and non-residential based on the usage of the sample plots, the R2 values obtained from those graphs were higher than the R2 value of the graph drawn without classification. The R2 value of the graph for non-residential areas has increased relative to the value of the graph for residential areas. Accordingly, classifying in this manner led to an increase in the accuracy of the relationship. Using these relationships, the optimum tree density required to obtain the required CO2 reduction in urban areas can be identified. The results of this study will be valuable for policymakers and urban planners looking for ways to improve air quality and create more sustainable urban environments.    

    

* Understanding the Electrochemical Carbon Dioxide Reduction Reaction Mechanism of Lattice Tuning of Copper by Silver Single‐Crystal Surface  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403140632
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cphc.202400757")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403140632"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403140632"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403140632"))][Get cited by]]

OpenAlex: https://openalex.org/W4403140632 (Open access: False)
    
[[https://openalex.org/A5025848770][Tao Zheng]], [[https://openalex.org/A5008191380][Xia‐Guang Zhang]], ChemPhysChem. None(None)] 2024. https://doi.org/10.1002/cphc.202400757 
     
Intermolecular interactions and adsorbate coverage on a metal electrode's surface/interface play an important role in CO2 reduction reaction (CO2RR). Herein, the activity and selectivity of CO2RR on bimetallic electrode, where a full monoatomic Cu layer covers on Ag surface (CuML/Ag) are investigated by using density functional theory calculations. The surface geometric and electronic structure results indicate that there is high electrocatalytic activity for CO2RR on the CuML/Ag electrode. Specifically, the CuML/Ag surface can accelerate the H2O and CO2 adsorption and hydrogenation while lowering the reaction energy of the rate‐determining step. The structure parameters of chemisorbed CO2 with and without H2O demonstrate that activated H2O not only promotes the C‐O dissociation but also provides the protons required for CO2RR on the CuML/Ag electrode surface. Furthermore, the various reaction mechanism diagrams indicate that the CuML/Ag electrode has high selectivity for CO2RR, and the efficiency of products can be regulated by modulating the reaction's electric potential.    

    

* Graphene-Based Photocatalysts for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403072741
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-3-031-66260-7_29")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403072741"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403072741"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403072741"))][Get cited by]]

OpenAlex: https://openalex.org/W4403072741 (Open access: False)
    
[[https://openalex.org/A5055420228][José M. Barrera‐Andrade]], [[https://openalex.org/A5014043779][Elim Albiter]], [[https://openalex.org/A5076263633][Miguel A. Valenzuela]], [[https://openalex.org/A5063052194][E. Rojas García]], Advanced structured materials. None(None)] 2024. https://doi.org/10.1007/978-3-031-66260-7_29 
     
No abstract    

    

* Mechanistic Study of the Electrochemical Reduction of CO2 in Aprotic Ionic Liquid in Air  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403140372
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401832")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403140372"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403140372"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403140372"))][Get cited by]]

OpenAlex: https://openalex.org/W4403140372 (Open access: False)
    
[[https://openalex.org/A5085350531][Go Iijima]], [[https://openalex.org/A5037589641][Kazumitsu Sugiura]], [[https://openalex.org/A5088783282][Kazuhiko Morishita]], [[https://openalex.org/A5051420489][Hajime Shingai]], [[https://openalex.org/A5055114575][Junichi Naruse]], [[https://openalex.org/A5101683322][Atsushi Yamamoto]], [[https://openalex.org/A5043263625][Yuki Fujita]], [[https://openalex.org/A5073315241][Hiroaki Yoto]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401832 
     
The capture and electrochemical conversion of dilute CO2 in air is a promising approach to mitigate global warming. Aiming to increase the efficiency of the electrochemical reduction of CO2, we fabricated electrodes and developed a custom‐designed sealed electrochemical reaction system to study the mechanism of this conversion. The performance of three metal electrodes, Ag, Cu, and SUS 316L, was compared in an aprotic ionic liquid as the electrolyte to monitor the CO2 concentration and chemical reactions using a CO2 sensor and diffuse reflectance infrared Fourier transform spectroscopy and Raman spectroscopy in CO2/N2 (400 ppm CO2 and 99.96% N2) or synthetic air (400 ppm CO2, 21% O2, and 79% N2). The CO2 concentration decreased at negative potentials and was more drastic in synthetic air than in CO2/N2. At negative potential in synthetic air, IR revealed carbon monoxide, carbonate, or peroxydicarbonate on the Ag, Cu, or SUS 316L electrodes, respectively. Reaction intermediates were identified using Raman spectroscopy. Superoxide (O2•−), produced by the reduction of O2 on each electrode, promotes the electrochemical reduction of CO2 whose reduction potential is higher on the negative side than that of O2. This research deepens our understanding of the electrochemical capture/release and conversion of dilute CO2.    

    

* Research progress of copper-based catalysts for CO2 electrochemical reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403030261
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.09.304")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403030261"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403030261"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403030261"))][Get cited by]]

OpenAlex: https://openalex.org/W4403030261 (Open access: False)
    
[[https://openalex.org/A5101594062][Yan Jia]], [[https://openalex.org/A5101255757][Weixiu Song]], [[https://openalex.org/A5046453708][Zhenli Zhao]], [[https://openalex.org/A5088566307][Manyu Zhang]], [[https://openalex.org/A5081183685][Yan Jing Wu]], [[https://openalex.org/A5056345181][Lianhong Zhang]], International Journal of Hydrogen Energy. 89(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.09.304 
     
No abstract    

    

* Cu-Modified Nb2o5 Photocatalysts for High Performance of Co2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403069376
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4974364")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403069376"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403069376"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403069376"))][Get cited by]]

OpenAlex: https://openalex.org/W4403069376 (Open access: False)
    
[[https://openalex.org/A5054850801][Junli Chen]], [[https://openalex.org/A5100453381][Tao Wang]], [[https://openalex.org/A5101421738][Ziqi Yang]], [[https://openalex.org/A5030729128][Pan Gao]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4974364 
     
No abstract    

    

* Strained Cu(111) surface can be catalytic efficient for C–C coupling in CO2 electrochemical reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403032159
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0216818")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403032159"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403032159"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403032159"))][Get cited by]]

OpenAlex: https://openalex.org/W4403032159 (Open access: True)
    
[[https://openalex.org/A5102402335][Yunfang Xu]], [[https://openalex.org/A5105697328][Y. L. Han]], [[https://openalex.org/A5100427812][Lixin Zhang]], AIP Advances. 14(10)] 2024. https://doi.org/10.1063/5.0216818 
     
It is well accepted that the Cu(100) surface is catalytic active for C–C coupling in CO2 reduction. However, the (100) surface is less active for the preceding CO* formation process and, most importantly, less stable than other surfaces. In this work, we investigate the relationship between catalytic effects and general factors such as coordination number and spacing (strain) of the Cu surface atoms. We find that the former affects the CO* formation only and the latter affects both the CO* formation and the subsequent C–C coupling. Among all the strained surfaces with larger atomic spacing, the more stable Cu(111) surface is extraordinary and outperforms Cu(100) and the high index surfaces for CO2 reduction to C2 on Cu.    

    

* A DFT and microkinetic modeling study of pressure effects on electroreduction reduction of CO2 to ethanol  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403117340
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.161421")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403117340"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403117340"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403117340"))][Get cited by]]

OpenAlex: https://openalex.org/W4403117340 (Open access: False)
    
[[https://openalex.org/A5031624398][Xiaowen Wang]], [[https://openalex.org/A5087000964][Fei Ma]], [[https://openalex.org/A5023261675][Haiqiao Wei]], [[https://openalex.org/A5101942399][Jiaying Pan]], [[https://openalex.org/A5100660669][Wenjia Li]], [[https://openalex.org/A5100530177][Jun Zhao]], [[https://openalex.org/A5002224809][Xiaotao Yang]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.161421 
     
No abstract    

    

* Air pollution mitigation and CO2 emission reduction effects of heterogeneous enterprises synergistic agglomeration  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403170973
:TOPICS: Economic Impact of Environmental Policies and Resources, Spatial Economics and Agglomeration Theory, Impact of Infrastructure and Taxation on Economic Growth
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10668-024-05497-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403170973"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403170973"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403170973"))][Get cited by]]

OpenAlex: https://openalex.org/W4403170973 (Open access: False)
    
[[https://openalex.org/A5100327223][Jiamin Liu]], [[https://openalex.org/A5039772760][Xiaoyu Ma]], [[https://openalex.org/A5062966512][Jiaoning Zhang]], [[https://openalex.org/A5073728540][Chiqun Hu]], [[https://openalex.org/A5068545546][Qiuqiu Guo]], Environment Development and Sustainability. None(None)] 2024. https://doi.org/10.1007/s10668-024-05497-2 
     
No abstract    

    

* Zirconium-doped ultrathin copper nanowires for C1 and C2+ products in electrochemical CO2 reduction reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403077551
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.114591")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403077551"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403077551"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403077551"))][Get cited by]]

OpenAlex: https://openalex.org/W4403077551 (Open access: True)
    
[[https://openalex.org/A5014445605][Wuyang Lin]], [[https://openalex.org/A5012436930][Matteo Palma]], [[https://openalex.org/A5076994358][Devis Di Tommaso]], Molecular Catalysis. 569(None)] 2024. https://doi.org/10.1016/j.mcat.2024.114591 
     
No abstract    

    

* Co Cluster-Modified Ni Nanoparticles with Superior Light-Driven Thermocatalytic Co2 Reduction by Ch4  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403093962
:TOPICS: Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels, Advancements in Density Functional Theory
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4976153")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403093962"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403093962"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403093962"))][Get cited by]]

OpenAlex: https://openalex.org/W4403093962 (Open access: False)
    
[[https://openalex.org/A5029731724][Qian Zhang]], [[https://openalex.org/A5100331926][Mei Li]], [[https://openalex.org/A5101769539][Yuhua Zhang]], [[https://openalex.org/A5101705073][Na Sun]], [[https://openalex.org/A5059984618][Dan Cheng]], [[https://openalex.org/A5100601973][Peng Sun]], [[https://openalex.org/A5054075598][Shaowen Wu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4976153 
     
No abstract    

    

* Electrodeposited Cu2o@Cu Hierarchical Structures for Electrocatalytic Co2 Reduction: Morphological Tuning and Copper Mediation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403176058
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4979269")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403176058"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403176058"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403176058"))][Get cited by]]

OpenAlex: https://openalex.org/W4403176058 (Open access: False)
    
[[https://openalex.org/A5100626308][Wang Zhen]], [[https://openalex.org/A5032386955][Yanmin Zhao]], [[https://openalex.org/A5028786427][Weirui Chen]], [[https://openalex.org/A5018986225][Gaozu Liao]], [[https://openalex.org/A5101797518][Laisheng Li]], [[https://openalex.org/A5100378635][Jing Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4979269 
     
No abstract    

    

* Rare-earth metal neodymium anchored into graphene as a promising CO2 reduction electrocatalyst by regulating the coordination environment  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403044828
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.105203")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403044828"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403044828"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403044828"))][Get cited by]]

OpenAlex: https://openalex.org/W4403044828 (Open access: False)
    
[[https://openalex.org/A5100620150][Siying Liu]], [[https://openalex.org/A5003167045][Huohai Yang]], [[https://openalex.org/A5063446819][Xingbo Ge]], [[https://openalex.org/A5101532301][Yingjie Feng]], [[https://openalex.org/A5032775500][Xiaoyue Fu]], [[https://openalex.org/A5100363117][Xin Chen]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.105203 
     
No abstract    

    

* Fabrication of mesoporous sulfated ZnO-modified g-C3N4 and TiO2 photocatalysts for CO2 reduction in gas phase  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403157643
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cattod.2024.115089")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403157643"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403157643"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403157643"))][Get cited by]]

OpenAlex: https://openalex.org/W4403157643 (Open access: False)
    
[[https://openalex.org/A5039200898][L.A. Al-Hajji]], [[https://openalex.org/A5087857810][Adel A. Ismail]], [[https://openalex.org/A5052431130][M. Alsaidi]], [[https://openalex.org/A5082555423][Ahmed Abdel Nazeer]], [[https://openalex.org/A5053395832][Ahmed Mohamed El‐Toni]], [[https://openalex.org/A5107769307][S.F. Al-Ruwayeh]], [[https://openalex.org/A5103869609][S.A. Ahmed]], [[https://openalex.org/A5107769308][T. Al-Sharrah]], Catalysis Today. None(None)] 2024. https://doi.org/10.1016/j.cattod.2024.115089 
     
No abstract    

    

* Photoirradiation-enhanced behavior via morphological manipulation of CoFe2O4/g-C3N4 heterojunction for supercapacitor and CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403014884
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.09.211")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403014884"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403014884"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403014884"))][Get cited by]]

OpenAlex: https://openalex.org/W4403014884 (Open access: False)
    
[[https://openalex.org/A5100725418][Wei He]], [[https://openalex.org/A5049690603][Yingpei Liu]], [[https://openalex.org/A5048950682][Liang Liu]], [[https://openalex.org/A5102573353][Huimin Han]], [[https://openalex.org/A5100700402][Zhi‐Xiang Wang]], [[https://openalex.org/A5101667147][Yuguang Li]], [[https://openalex.org/A5024108240][Dong Ji]], [[https://openalex.org/A5058192166][L. Shen]], [[https://openalex.org/A5101770125][Yirong Feng]], [[https://openalex.org/A5101844206][Shuangfei Zhao]], [[https://openalex.org/A5100616156][Jiming Yang]], [[https://openalex.org/A5102216318][Zheng Fang]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5100612547][Kai Guo]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.09.211 
     
No abstract    

    

* Enhanced Catalytic Activity of I-Mxenes for Co2 Reduction Reaction by Ordered Metal Atomic Vacancies: A Dft Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403016594
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4973714")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403016594"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403016594"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403016594"))][Get cited by]]

OpenAlex: https://openalex.org/W4403016594 (Open access: False)
    
[[https://openalex.org/A5000445381][Huichun Xue]], [[https://openalex.org/A5068991083][Yitong Chen]], [[https://openalex.org/A5101519452][Lin Zhu]], [[https://openalex.org/A5037785383][An Du]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4973714 
     
No abstract    

    

* Divergent Activity Shifts of Sn-Based Catalysts for Electrochemical CO2 Reduction: pH-Dependent Behavior of Single-Atom vs. Polyatomic Structures  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403082874
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-10-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-38nl4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403082874"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403082874"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403082874"))][Get cited by]]

OpenAlex: https://openalex.org/W4403082874 (Open access: False)
    
[[https://openalex.org/A5100449583][Yuhang Wang]], [[https://openalex.org/A5100366363][Di Zhang]], [[https://openalex.org/A5065063876][Bin Sun]], [[https://openalex.org/A5062034767][Xue Jia]], [[https://openalex.org/A5052046431][Linda Zhang]], [[https://openalex.org/A5055777639][Hefeng Cheng]], [[https://openalex.org/A5100761733][Jun Fan]], [[https://openalex.org/A5100348631][Hao Li]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-38nl4 
     
Tin (Sn)-based catalysts have been widely studied for electrochemical CO2 reduction reaction (CO2RR) to produce formic acid, but the intricate influence of the structural sensitivity in single-atom Sn (e.g., Sn-N-C) and polyatomic Sn (e.g., SnOx and SnSx; x=1,2) on their pH-dependent performance remains enigmatic. Herein, we integrate large-scale data mining (with >2,300 CO2RR catalysts from available experimental literature during the past decade), ab initio computations, machine learning force field accelerated molecular dynamic simulations, and pH-field coupled microkinetic modelling to unravel their pH dependence. We reveal a fascinating contrast: the electric field response of the binding strength of *OCHO on Sn-N4-C and polyatomic Sn exhibits opposite behaviors due to their differing dipole moment changes upon *OCHO formation. Such response leads to an intriguing opposite pH-dependent volcano evolution for Sn-N4-C and polyatomic Sn. Subsequent experimental validations of turnover frequency and current density under both neutral and alkaline conditions well aligned with our theoretical predictions. Most importantly, our analysis suggests the necessity of distinct optimization strategies for *OCHO binding energy on different types of Sn-based catalysts.    

    

* Metal-organic framework (MOF) integrated Ti3C2 MXene composites for CO2 reduction and hydrogen production applications: a review on recent advances and future perspectives  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403046125
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Two-Dimensional Materials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/fchem.2024.1448700")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403046125"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403046125"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403046125"))][Get cited by]]

OpenAlex: https://openalex.org/W4403046125 (Open access: True)
    
[[https://openalex.org/A5088895260][Beenish Tahir]], [[https://openalex.org/A5086907045][Abdulrahman Alraeesi]], [[https://openalex.org/A5100689309][Muhammad Tahir]], Frontiers in Chemistry. 12(None)] 2024. https://doi.org/10.3389/fchem.2024.1448700 
     
Titanium carbide (Ti 3 C 2 ) MXenes due to their structural and optical characteristics rapidly emerged as the preferred material, particularly in catalysis and energy applications. On the other hand, because of its enormous surface/volume ratio and porosity, Metal-organic Frameworks (MOFs) show promise in several areas, including catalysis, delivery, and storage. The potential to increase the applicability of these magic compounds might be achieved by taking advantage of the inherent flexibility in design and synthesis, and optical characteristics of MXenes. Thus, coupling MOF with Ti 3 C 2 MXenes to construct hybrid composites is considered promising in a variety of applications, including energy conversion and storage. This paper presents a systematic discussion of current developments in Ti 3 C 2 MXenes/MOF composites for photocatalytic reduction of CO 2 , and production of hydrogen through water splitting. Initially, the overview and characteristics of MXenes and MOFs are independently discussed and then a detailed investigation of efficiency enhancement is examined. Different strategies such as engineering aspects, construction of binary and ternary composites and their efficiency enhancement mechanism are deliberated. Finally, different strategies to explore further in various other applications are suggested. Although Ti 3 C 2 MXenes/MOF composites have not yet been thoroughly investigated, they are potential photocatalysts for the production of solar fuel and ought to be looked into further for a range of applications.    

    

* Important structural parameter for curvature effect of TM-N4 embeded C70 fullerenes as electrocatalysts for CO2 reduction interpreted with machine learning and first-principles calculations  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403168428
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.105233")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403168428"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403168428"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403168428"))][Get cited by]]

OpenAlex: https://openalex.org/W4403168428 (Open access: False)
    
[[https://openalex.org/A5009783384][Aling Ma]], [[https://openalex.org/A5012102127][Zongpeng Ding]], [[https://openalex.org/A5102634533][YuShan Pang]], [[https://openalex.org/A5038934588][Guohong Fan]], [[https://openalex.org/A5017163237][Hong Xu]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.105233 
     
No abstract    

    

* Carbon Capture and Storage Via Electrochemical and Bioelectrochemical Techniques: A Review  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403103147
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-09-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.4314/cajost.v6i2.3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403103147"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403103147"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403103147"))][Get cited by]]

OpenAlex: https://openalex.org/W4403103147 (Open access: False)
    
[[https://openalex.org/A5085535317][John Tsado Mathew]], [[https://openalex.org/A5062698417][Abel Inobeme]], [[https://openalex.org/A5027622259][Yakubu Azeh]], [[https://openalex.org/A5019284131][Musah Monday]], [[https://openalex.org/A5102814551][Abdullahi Abdulkadir]], [[https://openalex.org/A5043282915][Elijah Yanda Shaba]], [[https://openalex.org/A5043095884][M. B. Etsuyankpa]], [[https://openalex.org/A5078905516][Tanko S. Musa]], [[https://openalex.org/A5045091973][A. I. Muhammad]], [[https://openalex.org/A5031970670][Hina Ismail]], [[https://openalex.org/A5104939874][Abubakar Mohammed Kanwa]], [[https://openalex.org/A5042677157][Amos Mamman]], [[https://openalex.org/A5104954257][Jonathan Hussaini]], Caliphate Journal of Science and Technology. 6(2)] 2024. https://doi.org/10.4314/cajost.v6i2.3 
     
The urgent need to mitigate climate change has spurred innovative research in carbon capture and storage (CCS) technologies. Electrochemical approaches utilize electrocatalysis and electrochemical reduction to capture carbon dioxide (CO2) from industrial emissions, demonstrating high selectivity and enabling the production of valuable chemicals and fuels from captured CO2. Bioelectrochemical techniques leverage microorganisms to convert CO2 into biomass or biofuels, enhancing carbon capture efficiency through biological and electrochemical synergy. Integrating bioelectrochemical systems with renewable energy sources provides a carbon-negative pathway, aiding industry decarbonization. This review underscores the transformative potential of these techniques in revolutionizing CCS strategies, emphasizing their role in addressing climate change while fostering a sustainable, circular economy.    

    

* INTEGRATED TECHNOLOGY OF BIOGAS UTILIZATION OF SOLID HOUSEHOLD WASTE LANDFILLS WITH THE PRODUCTION OF ELECTROCITY, HEAT AND CARBON DIOXIDE  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403167145
:TOPICS: Energy Transition and Renewable Resources Integration, Mechanical Engineering and Optimization Techniques, Wireless Sensor Networks for Data Analysis
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.33070/etars.3.2024.04")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403167145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403167145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403167145"))][Get cited by]]

OpenAlex: https://openalex.org/W4403167145 (Open access: True)
    
[[https://openalex.org/A5028585095][Yu.V. Ivanov]], [[https://openalex.org/A5024576741][Serhii Krushnevych]], [[https://openalex.org/A5042431894][H.V. Zhuk]], [[https://openalex.org/A5079699978][Л.Р. Онопа]], [[https://openalex.org/A5107787365][O.V. Verbovskyi]], [[https://openalex.org/A5029606240][Dmitrii Komissarenko]], Energy Technologies & Resource Saving. 80(3)] 2024. https://doi.org/10.33070/etars.3.2024.04  ([[https://etars-journal.org/index.php/journal/article/download/403/336][pdf]])
     
The presence of carbon dioxyl as a non-combustible admixture in the landfill biogas of solid household waste and the absorption of ambient air into the layer of landfill waste, and therefore its entry into the landfill gas, significantly reduces the concentration of methane in it, which affects the efficient operation of the gas piston engine of the power plant and the reduction of volumes electricity generation. With the use of computer modeling for the composition of biogas with an increased content of N2 and a reduced concentration of CH4 £ 32 %, calculations were made on the enrichment of biogas to concentrations of CH4 in it of 36–44 % due to the use of CO2 amine absorption technologies, in which the costs for the regeneration of the absorbent are compensated by the produced thermal energy of the gas piston engine of the power plant. The removal of carbon dioxide from biogas makes it possible to simultaneously increase the concentration of methane in it at the input to the heat engine, which contributes to the stable and efficient operation of the gas piston engine of the power plant and the increase in the amount of electricity generation as a result of energy utilization of landfill gas. The use of complex biogas utilization technology in the cogeneration mode allows obtaining not only electricity, but also heat, which can be used in absorption amine technologies for CO2 extraction from biogas and thus reducing carbon dioxide emissions into the atmosphere. Bibl. 17, Fig. 9, Tab. 3.    

    

* Structural and Reservoir Characteristics of Potential Carbon Dioxide Storage Sites in the Northern South Yellow Sea Basin, Offshore Eastern China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403074530
:TOPICS: Anaerobic Methane Oxidation and Gas Hydrates, Characterization of Shale Gas Pore Structure, Seismic Waveform Inversion in Geophysics
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/jmse12101733")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403074530"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403074530"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403074530"))][Get cited by]]

OpenAlex: https://openalex.org/W4403074530 (Open access: True)
    
[[https://openalex.org/A5031223524][Di Luo]], [[https://openalex.org/A5041615964][Yong Yuan]], [[https://openalex.org/A5100689468][Jianwen Chen]], [[https://openalex.org/A5100404157][Qing Li]], [[https://openalex.org/A5046285032][Jie Liang]], [[https://openalex.org/A5079458065][Hualin Zhao]], Journal of Marine Science and Engineering. 12(10)] 2024. https://doi.org/10.3390/jmse12101733 
     
The geological storage of carbon dioxide (CO2) in offshore saline aquifers stands as a primary option for reducing CO2 emissions in coastal regions. China’s coastal regions, particularly Shandong and Jiangsu provinces, face significant challenges in CO2 reduction. Therefore, evaluating the feasibility of CO2 geological storage in the adjacent seas is critical. To assess the suitability of a CO2 storage site, understanding its structural and reservoir characteristics is essential to mitigate injection and storage risks. In this study, we analyzed the structural characteristics and potential traps of the Yantai Depression in the South Yellow Sea Basin based on seismic data interpretation. We further conducted well logging analysis and post-stack seismic inversion to obtain lithological data, including acoustic impedance and sandstone content percentages from the Cenozoic Funing Formation, Dainan–Sanduo Formation, and Yancheng Formation. Our findings highlight that the Yantai Depression in the South Yellow Sea Basin exhibits diverse structural traps and favorable reservoir–caprock combinations, suggesting promising geological conditions for CO2 storage. This area emerges as a suitable candidate for implementing CO2 geological storage initiatives.    

    

* Chemistry-climate feedback of atmospheric methane in a methane emission flux driven chemistry-climate model  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403045913
:TOPICS: Global Methane Emissions and Impacts, Anaerobic Methane Oxidation and Gas Hydrates, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-2024-2938")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403045913"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403045913"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403045913"))][Get cited by]]

OpenAlex: https://openalex.org/W4403045913 (Open access: True)
    
[[https://openalex.org/A5013620281][Laura Stecher]], [[https://openalex.org/A5078307835][Franziska Frank]], [[https://openalex.org/A5040485527][Patrick Jöckel]], [[https://openalex.org/A5074450843][Michael Ponater]], [[https://openalex.org/A5020189451][Mariano Mertens]], [[https://openalex.org/A5078008464][M. Dameris]], No host. None(None)] 2024. https://doi.org/10.5194/egusphere-2024-2938 
     
Abstract. The chemical sink of atmospheric methane (CH4) depends on the temperature and on the chemical composition. Here, we assess the feedback of atmospheric CH4 induced by changes of the chemical sink in a warming climate using a CH4 emission flux driven setup of the chemistry-climate model EMAC, in which the chemical feedback of CH4 mixing ratios can evolve explicitly. We perform idealized perturbation simulations driven either by increased carbon dioxide (CO2) mixing ratios, or by increased CH4 emission fluxes. The CH4 emission flux perturbation leads to a large increase of CH4 mixing ratios. Remarkably, the factor by which the CH4 mixing ratio increases is larger than the increase factor of the emission flux, because the atmospheric lifetime of CH4 is extended. In contrast, the individual effect of the global surface air temperature (GSAT) increase is to shorten the CH4 lifetime, which results in a significant reduction of CH4 mixing ratios in our setup. The corresponding radiative feedback is estimated at -0.041 W/m2/K and -0.089 W/m2/K for the CO2 and CH4 perturbation, respectively. The explicit adaption of CH4 mixing ratios leads to secondary feedbacks of the hydroxyl radical (OH) and ozone (O3). Firstly, the OH response includes the CH4-OH feedback, which enhances the CH4 lifetime change, and, secondly, the formation of tropospheric O3 is reduced. Our CH4 perturbation induces the same response of GSAT per effective radiative forcing (ERF) as the CO2 perturbation, which supports the applicability of the ERF framework for CH4.    

    

* Integrating Active Learning and DFT for Fast-Tracking Single-Atom Alloy Catalysts in CO2-to-Fuel Conversion  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403050550
:TOPICS: Accelerating Materials Innovation through Informatics, Electrocatalysis for Energy Conversion, Droplet Microfluidics Technology
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c11695")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403050550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403050550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403050550"))][Get cited by]]

OpenAlex: https://openalex.org/W4403050550 (Open access: False)
    
[[https://openalex.org/A5044055665][Xin Song]], [[https://openalex.org/A5009988050][Pengxin Pu]], [[https://openalex.org/A5038092047][Haisong Feng]], [[https://openalex.org/A5102482212][Hu Ding]], [[https://openalex.org/A5014079387][Yuan Deng]], [[https://openalex.org/A5100297487][Zhen Ge]], [[https://openalex.org/A5044492107][Sylvia Zhao]], [[https://openalex.org/A5007836409][Tianyong Liu]], [[https://openalex.org/A5017313282][Yusen Yang]], [[https://openalex.org/A5084055697][Min Wei]], [[https://openalex.org/A5100333386][Xin Zhang]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c11695 
     
Electrocatalytic carbon dioxide reduction (CO    

    

* Light-Activated Artificial CO2-Reductase: Structure and Activity  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403027660
:TOPICS: Mass Spectrometry Techniques, Electrochemical Reduction of CO2 to Fuels, Chemical Reactions Involving Quantum Tunneling
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c08927")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403027660"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403027660"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403027660"))][Get cited by]]

OpenAlex: https://openalex.org/W4403027660 (Open access: False)
    
[[https://openalex.org/A5092143087][Raphaël J. Labidi]], [[https://openalex.org/A5070853192][Bruno Faivre]], [[https://openalex.org/A5029338783][Philippe Carpentier]], [[https://openalex.org/A5058132875][Julien Pérard]], [[https://openalex.org/A5001485043][Philipp Gotico]], [[https://openalex.org/A5100369239][Yun Li]], [[https://openalex.org/A5076426241][Mohamed Atta]], [[https://openalex.org/A5062221634][Marc Fontecave]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c08927 
     
Light-dependent reduction of carbon dioxide (CO    

    

* The Reduction in the Number of CO2 Defects in the Process of Obtaining Breathing Air for Hyperbaric Oxygen Conditions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403162272
:TOPICS: Mechanical Ventilation in Respiratory Failure and ARDS
:PUBLICATION_DATE: 2023-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2478/phr-2023-0001")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403162272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403162272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403162272"))][Get cited by]]

OpenAlex: https://openalex.org/W4403162272 (Open access: False)
    
[[https://openalex.org/A5070264803][Arkadiusz Woźniak]], Polish Hyperbaric Research. 82(1)] 2023. https://doi.org/10.2478/phr-2023-0001 
     
Abstract Maintaining a stable carbon dioxide content in the process of obtaining breathing air is essential for safe underwater operations and the reduction of the cost of losses resulting from a poor quality product. The paper addresses the modification of the hyperbaric breathing air production process in terms of eliminating harmful carbon dioxide contaminants. It presents the effects of the modifications made to the process in order to minimise the proportion of defects. A description is given of the status of the process before and after the correction in terms of the identified areas of improvement leading to the achievement of the defined critical requirements of the process. Achievement of the objective to rationalise the breathing air production process was confirmed by results of tests carried out at KTPP AMW 1 based on the compressed air supply system of the DGKN - 120 complex 2 .    

    

* Biomass Loss and Land Use Land Cover from Habitat Conversion in Kahe Forest Reserve, Northern Tanzania  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403132622
:TOPICS: Drivers and Impacts of Tropical Deforestation, Rangeland Degradation and Pastoral Livelihoods, Climate Change Impacts on Forest Carbon Sequestration
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.9734/ijecc/2024/v14i104500")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403132622"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403132622"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403132622"))][Get cited by]]

OpenAlex: https://openalex.org/W4403132622 (Open access: True)
    
[[https://openalex.org/A5076559339][Adili Y. Zella]], [[https://openalex.org/A5039210884][Luzabeth J. Kitali]], International Journal of Environment and Climate Change. 14(10)] 2024. https://doi.org/10.9734/ijecc/2024/v14i104500 
     
This paper offers a less known biomass depletion and atmospheric carbon emissions due to habitat alteration in the Kahe Forest Reserve (KFR), Northern Tanzania, during a two-decade span (2003–2023). The paper measures biomass depletion, carbon emissions, carbon dioxide emissions, and the consequent economic effects due to losses in carbon trading. The study used the NAFORMA methodology alongside geospatial analysis to evaluate the ecological and economic impacts of land-use and land-cover alterations inside the reserve. The findings indicate a significant biomass reduction of roughly 23,019.6 tonnes, with corresponding carbon emissions totaling 10,819.2 tonnes. The study quantifies carbon dioxide emissions at 39,706.46 tonnes and assesses a carbon trade loss amounting to US$ 158,825.83. The data underscore the considerable environmental issues confronting KFR, intensified by a 141.4% surge in the human population in the adjacent districts from 1967 to 2022. This demographic pressure has resulted in unlawful agricultural encroachment, although existing protective restrictions, undermining the forest's ecological integrity and carbon sequestration potential. The results highlight the immediate necessity for action to prevent additional habitat deterioration and biodiversity decline. The study concludes with multiple policy recommendations, such as strengthened enforcement of forest protection measures, enhanced community engagement and education, promotion of sustainable agricultural practices beyond the reserve, restoration initiatives, and the incorporation of KFR into global carbon markets. These measures are essential for preserving the ecological integrity of the reserve and guaranteeing the sustainable stewardship of the region's natural resources.    

    

* Life Cycle Analysis of a Renovation Project for Old Housing in Tashkent to Reduce Greenhouse Gas Emissions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403048210
:TOPICS: Water Resource Management and Agricultural Technology, Evolution of Water Technologies in Ancient Civilizations
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/e3sconf/202457405007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403048210"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403048210"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403048210"))][Get cited by]]

OpenAlex: https://openalex.org/W4403048210 (Open access: True)
    
[[https://openalex.org/A5107692252][Elyor Makhmudov]], [[https://openalex.org/A5073803986][Anna Zavaleeva]], [[https://openalex.org/A5067130825][Ilya Zavaleev]], [[https://openalex.org/A5093273476][Akmal Berdimurodov]], E3S Web of Conferences. 574(None)] 2024. https://doi.org/10.1051/e3sconf/202457405007 
     
The shift towards economic decarbonization through the reduction of carbon dioxide emissions has led to a focus on renovating and modernizing the existing buildings rather than constructing new ones. This research emphasizes the critical differences between the construction of new buildings and the modernization of the existing structures, specifically in the context of Uzbekistan. The country lacks a comprehensive methodology for accounting for the embodied carbon of building materials used in modernization projects. This research aims to bridge this gap by conducting a life cycle analysis (LCA) of a project focused on enhancing the thermal performance of the enclosing structures of a three to five-story multifamily residential building, commonly referred to as “Khrushchevka”. The analysis found that retrofitting buildings reduced greenhouse gas emissions by 13.5% through improved energy efficiency, despite the increase in initial emissions associated with the production and installation of insulation materials. The total reduction in carbon emissions over the entire life cycle of the reconstructed building was 24% (or 43.2 tons of CO₂), including emissions associated with the production of insulation. The payback period for emissions, which offsets the initial emissions during reconstruction, is 17 years.    

    

* Impacts of Land Use and Land Cover Changes on Biomass and Carbon Sequestration in Coastal Kinondoni, Tanzania  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403137310
:TOPICS: Drivers and Impacts of Tropical Deforestation
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.9734/ijecc/2024/v14i104498")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403137310"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403137310"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403137310"))][Get cited by]]

OpenAlex: https://openalex.org/W4403137310 (Open access: True)
    
[[https://openalex.org/A5039210884][Luzabeth J. Kitali]], [[https://openalex.org/A5076559339][Adili Y. Zella]], International Journal of Environment and Climate Change. 14(10)] 2024. https://doi.org/10.9734/ijecc/2024/v14i104498 
     
This study analyzes the impact of land use and land cover (LULC) alterations on biomass depletion and carbon sequestration in Kinondoni, Tanzania, over a 30-year period from 1993 to 2023. This study employs the National Forest Resources Monitoring and Assessment (NAFORMA) models and geospatial analysis to quantify the environmental and economic effects of urbanization, agricultural growth, and infrastructural development on local ecosystems. The deterioration of mangrove forests, essential for carbon sequestration, has resulted in an estimated biomass reduction of 65,600 tonnes, with mangroves representing 93.1% of the overall losses. This deterioration has markedly diminished the region's carbon storage capacity, leading to the emission of 30,830 tonnes of carbon, which is equivalent to 113,150 tonnes of carbon dioxide (CO₂). The economic impact of this decrease in carbon sequestration capacity is estimated at around US$ 452,610, signifying a lost opportunity for carbon trading. The degradation of mangroves is recognized as the principal cause of these losses. The study highlights the critical necessity for conservation and restoration measures, specifically aimed at mangrove ecosystems, to alleviate additional environmental and economic deterioration. It promotes sustainable land use regulations and the incorporation of ecosystem services valuation in decision-making processes to improve resilience in coastal Tanzania.    

    

* The Effects on Climate Change Due to Kitchen Waste Composting and Emissions of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403154375
:TOPICS: 
:PUBLICATION_DATE: 2024-02-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.70436/nuijb.v3i02.198")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403154375"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403154375"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403154375"))][Get cited by]]

OpenAlex: https://openalex.org/W4403154375 (Open access: False)
    
[[https://openalex.org/A5043105108][Nora’aini Ali]], [[https://openalex.org/A5107767888][Riaz Husnain]], [[https://openalex.org/A5107767889][Munir Baber Bakht]], [[https://openalex.org/A5107767890][Iqbal Tasawar]], No host. 03(ICCC(special))] 2024. https://doi.org/10.70436/nuijb.v3i02.198 
     
The emission of greenhouse gases into the atmosphere due to anthropogenic activities, including the disposal of large quantities of organic kitchen waste into the environment. There is currently no evidence suggesting the likelihood of a future reversal or pause in emissions. The process of carbon sequestration serves to mitigate the emission of greenhouse gases from kitchen organic waste through the creation of compost. Composting is proposed as a potentially effective and cost-efficient solution to address the issue production of kitchen organic waste, which is contributing to environmental pollution. The escalation in complete carbon dioxide and microbial biomass carbon emissions can be attributed to a concurrent reduction in the levels of dissolved organic carbon as the treatments experienced a noteworthy decrease in dissolved organic carbon concentrations. The application of banana and potato compost has been found to have a positive impact on the macro aggregates of soil, leading to an increase in soil stability due to the compost's ability to stabilize soil particles. The study indicate that composting represents the most effective approach for mitigating greenhouse gas emissions originating from kitchen organic waste, while also enhancing the biological and physicochemical characteristics of soil.    

    

* Development of Sustainable Goals Emissions Reduction Value to Measure Climate Change  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403122357
:TOPICS: Economic Implications of Climate Change Policies, Discrete Choice Models in Economics and Health Care, Measurement and Evaluation of Sustainable Development
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.4018/979-8-3693-7230-2.ch007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403122357"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403122357"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403122357"))][Get cited by]]

OpenAlex: https://openalex.org/W4403122357 (Open access: False)
    
[[https://openalex.org/A5107743204][J. Bala Murugan]], [[https://openalex.org/A5107743221][L. Priya Dharsini]], [[https://openalex.org/A5080609977][C. Prabakaran]], [[https://openalex.org/A5076970010][P. S. Ranjit]], [[https://openalex.org/A5069695739][S. Menaka]], [[https://openalex.org/A5016552396][R. Senthamil Selvan]], Practice, progress, and proficiency in sustainability. None(None)] 2024. https://doi.org/10.4018/979-8-3693-7230-2.ch007 
     
The Sustainable Development Goals, or SDGs, goal indicators and the steps taken to slow down climate change have trade-offs and synergies. Although some research has evaluated these linkages, nothing is known about how much of an interaction there is. This section illustrates how reducing CO2 emissions relates to the SDGs. They created the “marginal SDG-emissions-reduction values (MSVs),” which show how a unit decrease in CO2 emissions affects certain SDG indicators on a marginal basis. This measure was utilised and may be used for national evaluations. They discovered significant correlations between rates of CO2 emission reduction and several SDG objectives. For example, a 1% reduction in CO2 may save 0.57% of premature deaths linked to air pollution (SDG3), whereas the same CO2 reduction can result in a 0.026% drop in mean species richness (SDG15) (excluding the effects of climate change). Our results help evaluate the implications of CO2 emissions reduction objectives for the SDGs, which will assist in informing national climate strategies.    

    

* Impacts of climate change on phenology, yield, and water productivity of wheat in a semi-arid region of India using the CERES-Wheat model  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403026224
:TOPICS: Adaptation to Climate Change in Agriculture
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2166/wcc.2024.139")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403026224"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403026224"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403026224"))][Get cited by]]

OpenAlex: https://openalex.org/W4403026224 (Open access: True)
    
[[https://openalex.org/A5059330709][Himani Bisht]], [[https://openalex.org/A5060042376][S.S. Punia]], [[https://openalex.org/A5104157929][Bipin Kumar]], [[https://openalex.org/A5016049562][Jitendra Rajput]], [[https://openalex.org/A5088051819][D. K. Singh]], [[https://openalex.org/A5043152175][Lata Vishnoi]], [[https://openalex.org/A5101926604][Rajvir Singh]], [[https://openalex.org/A5002946730][Manisha Tamta]], [[https://openalex.org/A5085314552][Shweta Gautam]], Journal of Water and Climate Change. None(None)] 2024. https://doi.org/10.2166/wcc.2024.139 
     
ABSTRACT In the present study, the Crop Environment Resource Synthesis (CERES)-Wheat model was used to study the impacts of climate change on phenology, yield, and water productivity of wheat. The model was run with the baseline period (1980–2010) and three future periods, namely, the 2030s, 2050s, and 2070s under two representative concentration pathway (RCP) scenarios, namely, RCP 4.5 and RCP 8.5. The results indicated a substantial decline in phenology, grain yield, biomass, and crop water productivity (CWP) under both scenarios. The grain yield of wheat showed a decline by 12.3, 20.5, and 19.8% during the 2030s, 2050s, and 2070s, respectively, under RCP 4.5 at baseline CO2 concentration, while at elevated concentration of CO2, the reduction was 10.2, 15.7, and 14.9%, respectively. Under RCP 8.5, the yield reduction was 18.8, 26.5, and 27.3% during the 2030s, 2050s, and 2070s, respectively, with baseline concentration of CO2, while with increased CO2 the yield reduction was 7, 12.6, and 8.9%, respectively. CWP decreased at baseline CO2 by 9, 17.6, and 18.3% for RCP 4.5 and 10.6, 20.6, and 22.6% for RCP 8.5 during the 2030s, 2050s, and 2070s, respectively. However, beneficial impact of CO2 fertilization on CWP was noticed in both RCP scenarios, resulting in relatively less reduction under future CO2 concentration.    

    

* Electrokinetic Analysis‐Driven Promotion of Electrocatalytic CO Reduction to n‐Propanol  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403109751
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202406345")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403109751"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403109751"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403109751"))][Get cited by]]

OpenAlex: https://openalex.org/W4403109751 (Open access: False)
    
[[https://openalex.org/A5064270074][Yaqin Yan]], [[https://openalex.org/A5073681779][Kunhao Liu]], [[https://openalex.org/A5006812397][Chao Yang]], [[https://openalex.org/A5045304582][Yangshen Chen]], [[https://openalex.org/A5046867944][Ximeng Lv]], [[https://openalex.org/A5043850612][Cejun Hu]], [[https://openalex.org/A5100444043][Lijuan Zhang]], [[https://openalex.org/A5100727026][Gengfeng Zheng]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202406345 
     
Abstract The electrocatalytic carbon dioxide or carbon monoxide reduction reaction (CO 2 RR or CORR) features a sustainable method for reducing carbon emissions and producing value‐added chemicals. However, the generation of C 3 products with higher energy density and market values, such as n‐propanol, remains highly challenging, which is attributed to the unclear formation mechanism of C 3+ versus C 2 products. In this work, by the Tafel slope analysis, electrolyte pH correlation exploration, and the kinetic analysis of CO partial pressure fitting, it is identified that both n‐propanol and C 2 products share the same rate‐determining step, which is the coupling of two C 1 intermediates via the derivation of the Butler–Volmer equation. In addition, inspired by the mechanistic study, it is proposed that a high OH ─ concentration and a water‐limited environment are beneficial for promoting the subsequent *C 2 –*C 1 coupling to n‐propanol. At 5.0 m [OH − ], the partial current density of producing n‐propanol ( j n‐propanol ) reached 45 mA cm −2 , which is 35 and 1.3 times higher than that at 0.01 m [OH − ] and 1.0 m [OH − ], respectively. This study provides a comprehensive kinetic analysis of n‐propanol production and suggests opportunities for designing new catalytic systems for promoting the C 3 production.    

    

* Dynamical channel coupling in strong-field ionization of CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403065622
:TOPICS: Attosecond Physics and Optics, Mass Spectrometry Techniques, Advancements in Density Functional Theory
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1364/oe.537980")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403065622"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403065622"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403065622"))][Get cited by]]

OpenAlex: https://openalex.org/W4403065622 (Open access: True)
    
[[https://openalex.org/A5034096230][Yalei Zhu]], [[https://openalex.org/A5019231303][Zeyu Jiang]], [[https://openalex.org/A5067650874][Zhongxue Ren]], [[https://openalex.org/A5062272283][Guangru Bai]], [[https://openalex.org/A5100460513][Xiaowei Wang]], [[https://openalex.org/A5101766118][Dongwen Zhang]], [[https://openalex.org/A5101624057][Jinlei Liu]], [[https://openalex.org/A5004653714][Jing Zhao]], [[https://openalex.org/A5016773116][Zengxiu Zhao]], Optics Express. 32(21)] 2024. https://doi.org/10.1364/oe.537980 
     
We present a theoretical study employing the time-dependent density functional theory (TDDFT) to explore the effects of angle-resolved channel coupling in strong field ionization of carbon dioxide (CO 2 ) molecules. Our results reveal significant angular sensitivity of both the channel-resolved ionization probabilities and the effects of laser-induced channel couplings. By applying a linearly polarized two-color field scheme, we demonstrate the ability to significantly modify the strength of the laser-induced coupling, evidenced by the changes in the population distributions among the ionic states induced by the strong-field ionization. Importantly, the two-color field optimally modulates the coupling strength at the alignment angle where ionization of the highest occupied molecular orbital (HOMO) electrons is most efficient. This optimization is attributed to the reduction of the electron shielding effect. Our research provides valuable insights into the coherent manipulation of electron distribution within the cation, paving the way for the precise control of ultrafast electron dynamics during strong-field ionization processes.    

    

* Advanced Energy Management System for Generator–Battery Hybrid Power System in Ships: A Novel Approach with Optimal Control Algorithms  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403112671
:TOPICS: Environmental Impact of Maritime Transportation Emissions, Hydrogen Energy Systems and Technologies, Lithium-ion Battery Management in Electric Vehicles
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/jmse12101755")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403112671"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403112671"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403112671"))][Get cited by]]

OpenAlex: https://openalex.org/W4403112671 (Open access: True)
    
[[https://openalex.org/A5034632932][EunMi Choi]], [[https://openalex.org/A5018271820][Heemoon Kim]], Journal of Marine Science and Engineering. 12(10)] 2024. https://doi.org/10.3390/jmse12101755 
     
Advancements in the reduction of carbon dioxide emissions from ships are driving the development of more efficient onboard power systems. The proposed non-equivalent parallel running operation system is explored in this study, which improves the efficiency of the main power generation source compared with traditional equal load-sharing methods used in power management systems. However, the asymmetric method reduces the efficiency of the auxiliary power sources. To address this issue, we propose a control method that integrates a battery system with an efficiency-based algorithm to optimize the overall system performance. The proposed approach involves establishing operation command values based on the characteristics of the power generation source and adjusting these commands according to the battery’s state of charge (SOC). MATLAB/Simulink simulations confirmed the effectiveness of this method across various operating modes and revealed no operational issues. When applied to a ship’s operating profile over 222 h, the method reduced fuel consumption by approximately 2.98 tons (5.57%) compared with conventional systems. Over 38 annual voyages, this reduction equates to savings of 115.96 tons of fuel or approximately 96.47 million Korean won. This study demonstrates that integrating an optimal efficiency algorithm into the energy management system significantly enhances both the propulsion and overall energy efficiency of ships.    

    

* A New Approach for Improving Flame Retardancy of Automotive Interior Upholstery  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403074905
:TOPICS: Flame Retardant Polymer Materials, Fire Safety in Tunnel Fires, Recycling Technologies for Carbon Fiber Composites
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21605/cukurovaumfd.1559895")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403074905"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403074905"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403074905"))][Get cited by]]

OpenAlex: https://openalex.org/W4403074905 (Open access: False)
    
[[https://openalex.org/A5003241982][Özlem Erdem Yılmaz]], [[https://openalex.org/A5068006582][Ali Can Yılmaz]], [[https://openalex.org/A5023710707][Ahmet Çoşgun]], Çukurova Üniversitesi Mühendislik Fakültesi Dergisi. None(None)] 2024. https://doi.org/10.21605/cukurovaumfd.1559895 
     
This study presents the flame retardant (FR) performance of chemically treated automotive upholstery fabrics using two different impregnation methods of Resin Transfer Molding (RTM) and supercritical carbon dioxide (scCO2). Referring to the related standards, untreated seat fabric obtained from seat upholstery of a bus (neat fabric, NF) and treated fabric samples underwent burning rate (BR) and limiting oxygen index (LOI) tests to compare effect of treatment and impregnation methods on FR performance. Thermal analysis was also conducted on the samples considering onset degradation temperatures and char yields. The results showed that BR and LOI of all samples were in acceptable range and treatment provided enhancement in FR performance of NF. The treated sample using scCO2 method gave the highest LOI value of 32% and the lowest BR of 21 mm/min subtending to 18.5% increase in LOI and 30% reduction in BR compared to those of NF. The performance of treatment in RTM was worse than that of scCO2 and better than that of NF. The results confirm that both treatment and methods used in this study give promising results for safety against fire in transportation vehicles.    

    

* Performance Evaluation of CO2 + SiCl4 Binary Mixture in Recompression Brayton Cycle for Warm Climates  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403106930
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Waste Heat Recovery for Power Generation and Cogeneration, Supercritical Fluid Extraction and Processing
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/pr12102155")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403106930"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403106930"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403106930"))][Get cited by]]

OpenAlex: https://openalex.org/W4403106930 (Open access: True)
    
[[https://openalex.org/A5030409287][Muhammad Ehtisham Siddiqui]], [[https://openalex.org/A5091854456][Khalid H. Almitani]], Processes. 12(10)] 2024. https://doi.org/10.3390/pr12102155 
     
This work demonstrates the potential of CO2 + SiCl4 binary mixture as a working fluid for power generation cycle. Recompression Brayton cycle configuration is considered due to its proven record of high performance for medium- to high-temperature sources. The objective of this study is to assess the thermodynamic performance of a recompression Brayton cycle using a CO2 + SiCl4 binary mixture as a working fluid, particularly under warm climate conditions. The cycle is simulated using the Peng–Robinson equation of state in Aspen Hysys (v11) software, and the model is validated by comparing VLE data against experimental data from the literature. The analysis involves the assessment of cycle’s thermal efficiency and exergy efficiency under warm climatic conditions, with a minimum cycle temperature of 40 °C. The results demonstrate a notable improvement in the cycle’s thermodynamic performance with CO2 + SiCl4 binary mixture compared to pure CO2. A small concentration (5%) of SiCl4 in CO2 increases the thermal efficiency of the cycle from 41.7% to 43.4%. Moreover, irreversibility losses in the cooler and the heat recovery unit are significantly lower with the CO2 + SiCl4 binary mixture than with pure CO2. This improvement enhances the overall exergy efficiency of the cycle, increasing it from 62.1% to 70.2%. The primary reason for this enhancement is the substantial reduction in irreversibility losses in both the cooler and the HTR. This study reveals that when using a CO2 + SiCl4 mixture, the concentration must be optimized to avoid condensation in the compressor, which can cause physical damage to the compressor blades and other components, as well as increase power input. This issue arises from the higher glide temperature of the mixture at increased SiCl4 concentrations and the limited heat recovery from the cycle.    

    

* The Effect of Climate Change on Plant Parasitic Nematodes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403108794
:TOPICS: Plant-Parasitic Nematodes in Molecular Plant Pathology, Impacts of Elevated CO2 and Ozone on Plant Physiology
:PUBLICATION_DATE: 2024-06-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.69860/nobel.9786053359449.12")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403108794"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403108794"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403108794"))][Get cited by]]

OpenAlex: https://openalex.org/W4403108794 (Open access: False)
    
[[https://openalex.org/A5010384826][Betül GÜRKAN]], [[https://openalex.org/A5046732968][Tolga GÜRKAN]], No host. None(None)] 2024. https://doi.org/10.69860/nobel.9786053359449.12 
     
Climate change is defined as permanent changes in the Earth’s weather conditions, such as temperature, precipitation, and wind. The main impacts of climate change include global warming, increase in weather events, sea level rise, damage to ecosystems, melting of glaciers, negative impacts on agriculture, water resources and human health. The biology and physiology of plant parasitic nematodes are regulated by environmental factors, (such as temperature, humidity, precipitation, and soil CO2 levels). which is one of the indicators of climate change. Climate change weather extremes such as increased temperature due to global warming, drought, forest fires, high CO2 conditions, increased rainfall, humidity conditions and storms affect the biodiversity, distribution, reproduction, survival and parasitic potential of plant parasitic nematodes. Since changes in CO2, temperature and precipitation levels caused by climate change will increase the proliferation, distribution and damage potential of plant parasitic nematode populations, there is a need to develop appropriate strategies for the control of nematodes that will be effective in situations of global warming in order to prevent significant reductions in crop yields in the future.    

    

* Modeling Exhaust Emissions in Older Vehicles in the Era of New Technologies  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403027898
:TOPICS: Estimating Vehicle Fuel Consumption and Emissions, Low-Cost Air Quality Monitoring Systems, Health Effects of Air Pollution
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17194924")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403027898"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403027898"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403027898"))][Get cited by]]

OpenAlex: https://openalex.org/W4403027898 (Open access: True)
    
[[https://openalex.org/A5059564093][Maksymilian Mądziel]], Energies. 17(19)] 2024. https://doi.org/10.3390/en17194924 
     
In response to increasing environmental demands, modeling emissions from older vehicles presents a significant challenge. This paper introduces an innovative methodology that takes advantage of advanced AI and machine learning techniques to develop precise emission models for older vehicles. This study analyzed data from road tests and the OBDII diagnostic interface, focusing on CO2, CO, THC, and NOx emissions under both cold and warm engine conditions. The key results showed that random forest regression provided the best predictions for THC in a cold engine (R2: 0.76), while polynomial regression excelled for CO2 (R2: 0.93). For warm engines, polynomial regression performed best for CO2 (R2: 0.95), and gradient boosting delivered results for THC (R2: 0.66). Although prediction accuracy varied by emission compound and engine state, the models consistently demonstrated high precision, offering a robust tool for managing emissions from aging vehicle fleets. These models offer valuable information for transportation policy and pollution reduction strategies, particularly in urban areas.    

    

* A-124 Sustainable Transport: Assessing Environmental Impact in Medical Sample Transit via Drones and Vehicles  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403071790
:TOPICS: Impact of Climate Change on Human Health
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/clinchem/hvae106.123")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403071790"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403071790"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403071790"))][Get cited by]]

OpenAlex: https://openalex.org/W4403071790 (Open access: False)
    
[[https://openalex.org/A5096910016][Noel Rouven Stierlin]], [[https://openalex.org/A5096941573][A Hemmerle]], [[https://openalex.org/A5084754410][Martin Risch]], [[https://openalex.org/A5049354618][Lorenz Risch]], Clinical Chemistry. 70(Supplement_1)] 2024. https://doi.org/10.1093/clinchem/hvae106.123 
     
Abstract Background This research explores the ecological implications associated with different methods of transporting medical samples, specifically focusing on drones, combustion cars, and electric cars within two laboratories in central European countries. With the primary goal of assessing and comparing CO2 consumption, delivery time, and overall environmental impact, the study aims to provide a basis for adopting sustainable practices in healthcare logistics. Methods The transportation of medical samples occurred between two laboratories in the Principality of Liechtenstein and Switzerland, utilizing authorized aerial and road routes. Various weather conditions and distances were considered for sample transports using different vehicles (8 combustion cars, two electric cars, and one drone model). Energy consumption was documented, and the CO2 footprint was calculated based on data from the Swiss Federal Office for the Environment (FOEN) for both imported and renewable electricity. Comparative analyses were conducted to quantify the environmental impact of each transportation method. Results In terms of CO2 footprint, combustion cars exhibited a CO2 release of 159.5 g/km, while electric cars showed 3.43g (2.15 to 4.08% of combustion cars). Drones demonstrated a minimal 0.09g CO2 emission per kilometer (0.066% of combustion car CO2 emission; 2.6% of electric car CO2 emission). The distance traveled by drones was significantly shorter (16.7% to 50%). Additionally, the efficiency of drone transport was emphasized by its ability to avoid traffic jams and associated detours, resulting in time savings ranging from 31.25 to 50% per delivery when comparing transport times during rush hour and regular hours in the selected setting. Conclusions The integration of drone technology emerges as a crucial strategy for establishing a “green laboratory.” The substantial reduction in CO2 emissions and enhanced delivery efficiency position drone transport as a sustainable and operationally effective solution for medical sample logistics, offering shorter delivery times. These findings highlight the potential for transformative change in healthcare logistics, aligning with the global shift towards sustainability and green practices.    

    

* Two‐Dimensional Silver–Isocyanide Frameworks  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403024022
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Self-Assembly and Biomaterial Design, Polyoxometalate Clusters and Materials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202417658")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403024022"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403024022"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403024022"))][Get cited by]]

OpenAlex: https://openalex.org/W4403024022 (Open access: False)
    
[[https://openalex.org/A5077459472][Kaiyue Jiang]], [[https://openalex.org/A5060201476][Pu Yan]], [[https://openalex.org/A5101997579][Pengfei Shi]], [[https://openalex.org/A5075460158][Jichao Zhang]], [[https://openalex.org/A5050942599][Xinyu Chai]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5057665432][Chenhui Zhu]], [[https://openalex.org/A5100535765][Chongqing Yang]], [[https://openalex.org/A5029903067][Chenbao Lu]], [[https://openalex.org/A5100330523][Yi Liu]], [[https://openalex.org/A5069271154][Kecheng Cao]], [[https://openalex.org/A5006485558][Xiaodong Zhuang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202417658 
     
Metal‐organic frameworks (MOFs) have been widely studied due to their versatile applications and easily tunable structures. However, heteroatom‐metal coordination dominates the MOFs community, and the rational synthesis of carbon–metal coordination‐based MOFs remains a significant challenge. Herein, two‐dimensional (2D) MOFs based on silver–carbon linkages are synthesized through the coordination between silver(I) salt and isocyanide‐based monomers at ambient condition. The as‐synthesized 2D MOFs possess well‐defined crystalline structures and a staggered AB stacking mode. Most interestingly, these 2D MOFs, without π–π stacking between layers, exhibit narrow bandgaps down to 1.42 eV. As electrochemical catalysts for converting CO2 to CO, such 2D MOFs demonstrate Faradaic efficiency over 92%. Surprisingly, the CO2 reduction catalyzed by these MOFs indicates favorable adsorption of CO2 and *COOH on the active carbon sites of the isocyanide groups rather than on silver sites. This is attributed to the critical σ donor role of isocyanides and the corresponding ligand‐to‐metal charge–transfer effect. This work not only paves the way toward a new family of MOFs based on metal–isocyanide coordination but also offers a rare platform for understanding the electrocatalysis processes on strongly polarized carbon species.    

    

* Two‐Dimensional Silver–Isocyanide Frameworks  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403080791
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202417658")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403080791"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403080791"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403080791"))][Get cited by]]

OpenAlex: https://openalex.org/W4403080791 (Open access: False)
    
[[https://openalex.org/A5077459472][Kaiyue Jiang]], [[https://openalex.org/A5057451591][Pu Yan]], [[https://openalex.org/A5101997579][Pengfei Shi]], [[https://openalex.org/A5075460158][Jichao Zhang]], [[https://openalex.org/A5050942599][Xinyu Chai]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5057665432][Chenhui Zhu]], [[https://openalex.org/A5100535765][Chongqing Yang]], [[https://openalex.org/A5029903067][Chenbao Lu]], [[https://openalex.org/A5100330523][Yi Liu]], [[https://openalex.org/A5069271154][Kecheng Cao]], [[https://openalex.org/A5006485558][Xiaodong Zhuang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202417658 
     
Metal‐organic frameworks (MOFs) have been widely studied due to their versatile applications and easily tunable structures. However, heteroatom‐metal coordination dominates the MOFs community, and the rational synthesis of carbon–metal coordination‐based MOFs remains a significant challenge. Herein, two‐dimensional (2D) MOFs based on silver–carbon linkages are synthesized through the coordination between silver(I) salt and isocyanide‐based monomers at ambient condition. The as‐synthesized 2D MOFs possess well‐defined crystalline structures and a staggered AB stacking mode. Most interestingly, these 2D MOFs, without π–π stacking between layers, exhibit narrow bandgaps down to 1.42 eV. As electrochemical catalysts for converting CO2 to CO, such 2D MOFs demonstrate Faradaic efficiency over 92%. Surprisingly, the CO2 reduction catalyzed by these MOFs indicates favorable adsorption of CO2 and *COOH on the active carbon sites of the isocyanide groups rather than on silver sites. This is attributed to the critical σ donor role of isocyanides and the corresponding ligand‐to‐metal charge–transfer effect. This work not only paves the way toward a new family of MOFs based on metal–isocyanide coordination but also offers a rare platform for understanding the electrocatalysis processes on strongly polarized carbon species.    

    

* How teacher behaviors and perceptions, air change rates, and portable air purifiers affect indoor air quality in naturally ventilated schools  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403102704
:TOPICS: Indoor Air Quality and Health Effects, Building Energy Efficiency and Thermal Comfort Optimization, Airborne Transmission of Respiratory Viruses
:PUBLICATION_DATE: 2024-10-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/fpubh.2024.1427116")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403102704"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403102704"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403102704"))][Get cited by]]

OpenAlex: https://openalex.org/W4403102704 (Open access: True)
    
[[https://openalex.org/A5001324666][Tian Xia]], [[https://openalex.org/A5033801906][Julia Raneses]], [[https://openalex.org/A5107736248][Brixon Schmiesing]], [[https://openalex.org/A5055616491][Raquel García‐Esteban]], [[https://openalex.org/A5107736249][Alison Walding]], [[https://openalex.org/A5107736250][Richardo DeMajo]], [[https://openalex.org/A5019792741][Amy J. Schulz]], [[https://openalex.org/A5052172551][Stuart Batterman]], Frontiers in Public Health. 12(None)] 2024. https://doi.org/10.3389/fpubh.2024.1427116 
     
Introduction Many school buildings have inadequate ventilation, rudimentary if any air filtration, and aging and poorly maintained mechanical systems, all of which can lead to poor indoor air quality (IAQ). These issues are especially acute in environmental justice (EJ) communities where schools are located in polluted areas. This community-based participatory research examines how IAQ in naturally ventilated school buildings is affected by the use of air purifiers, air change rates, outdoor pollution levels, and teacher and staff behavior. Methods IAQ assessments were performed at two schools in Detroit, Michigan, which included building walk-through inspections and continuous indoor and outdoor measurements of black carbon (BC), particulate matter (PM 10 and PM 2.5 ), carbon dioxide (CO 2 ), air change rates (ACRs), temperature, humidity, and sound pressure levels. Air purifiers with usage monitors were then installed, and the IAQ assessments were repeated. Teachers were surveyed before and after purifier deployment. Results At baseline, classrooms had low ACRs (0.58–1.38 h −1 ), moderate PM 2.5 levels (2.8–8.9 μg/m 3 ), highly variable PM 10 concentrations (4.7–37.5 μg/m 3 ), and elevated BC levels (0.3–0.7 μg/m 3 ), reflecting emissions from local traffic, industry and other sources. The installation and use of purifiers reduced pollutant levels and the overall performance matched the predictions of a single compartment model. However, daily reductions varied widely among classrooms, reflecting differences in teacher behavior regarding the frequency of opening windows and the operation of purifiers, including differences in purifier fan speed settings and whether purifiers were used at night. Survey responses indicated that many teachers were aware of IAQ problems. The higher rates reported for health symptoms and dissatisfaction at one school may have lowered the teachers’ tolerance to noise and reduced purifier use. Discussion The study helps explain the variation reported in prior studies using purifiers, and it reinforces the need to monitor IAQ and purifier use, use enhanced filtration and increase ventilation, and engage with teachers and school staff to support and maintain IAQ programs in schools.    

    

* Hemodynamic Disorders in Alcohol Withdrawal Syndrome  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403135275
:TOPICS: Diagnosis and Management of Wernicke-Korsakoff Syndrome, Pathogenesis and Treatment of Alcoholic Liver Disease, Hyperglycemic Chorea and Basal Ganglia Lesions
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.17816/pavlovj623055")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403135275"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403135275"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403135275"))][Get cited by]]

OpenAlex: https://openalex.org/W4403135275 (Open access: False)
    
[[https://openalex.org/A5044093708][S.I. Utkin]], [[https://openalex.org/A5006781008][О. Ж. Бузик]], I P Pavlov Russian Medical Biological Herald. 32(3)] 2024. https://doi.org/10.17816/pavlovj623055 
     
INTRODUCTION: The introduction of the study is determined by a high prevalence of alcoholism and a high incidence of complications from the cardiovascular system. AIM: To study the features of hemodynamics in patients with uncomplicated alcohol withdrawal syndrome (AWS) and in those with alcohol withdrawal delirium (delirium tremens). MATERIALS AND METHODS: The study enrolled 116 men, 58 of them with uncomplicated AWS, 78 with AWS and delirium. Basic hemodynamic parameters were studied: heart rate (HR), blood pressure (BP), and integral parameters — cardiac index (CI), total peripheral resistance (TPR), shock index (SI). Comparisons between the groups and correlation analysis were conducted to find relationships between hemodynamic parameters and clinical data. RESULTS: In patients with alcoholic delirium, hemodynamic parameters were statistically significantly higher than in patients with uncomplicated AWS: HR (р = 0.003), systolic BP (р = 0.02) and diastolic BP (р = 0.04), while no statistically significant differences in the integral parameters (CI, TPR, SI) were found between the groups. In patients of both groups, CI linearly decreased with age (p 0.0001). The same linearly CI decreased with increase in the duration of alcoholism (p = 0.02). With an increase in the amount of consumed alcohol during the binge period, a linear growth of CI was observed in withdrawal state (p = 0.001). The value of TPR increased with age (p = 0.005). Only in patients with delirium tremens, there was an inverse relationship between SI and partial tension of carbon dioxide in venous blood (r = -0.4; p = 0.014). Besides, only in patients with delirium tremens, by the 7th day of withdrawal, a direct relationship was established between the cardiac index and blood potassium level (r = 0.36; p = 0.03). CONCLUSIONS: There was no significant difference between hemodynamic parameters in uncomplicated AWS and in delirium tremens. CI in patients with uncomplicated AWS and in those with DT decreased with age and with increase in the alcohol load. The vessel tone was inversely proportional to CI throughout the entire period of observation. With the development of delirium, a correlation was noted between a decrease in the level of energy metabolism and the probability for decompensation of systemic circulation. At the stage of reduction of delirium tremens, a correlation was noted between CI and the blood potassium level that reflected the exhaustion of the cardiovascular system and reduction of its compensatory capacities.    

    

* Comparative study of alternative fuels for sustainable IC engine operation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403079034
:TOPICS: Catalytic Nanomaterials, Technical Aspects of Biodiesel Production
:PUBLICATION_DATE: 2021-10-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.30574/wjarr.2021.12.1.0407")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403079034"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403079034"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403079034"))][Get cited by]]

OpenAlex: https://openalex.org/W4403079034 (Open access: False)
    
[[https://openalex.org/A5107694818][BHASKARA]], World Journal of Advanced Research and Reviews. 12(1)] 2021. https://doi.org/10.30574/wjarr.2021.12.1.0407 
     
The increasing environmental concerns, coupled with the rapid depletion of conventional fossil fuels, have prompted the automotive industry to explore alternative energy sources that can support the continued operation of internal combustion (IC) engines in a more sustainable manner. The need to mitigate greenhouse gas emissions, reduce dependence on finite fossil resources, and meet stringent environmental regulations has led to extensive research and development efforts in identifying viable alternative fuels. These fuels must not only align with the performance requirements of modern IC engines but also minimize their environmental footprint.This paper presents a comprehensive comparative analysis of various alternative fuels, including biodiesel, ethanol, hydrogen, natural gas, and synthetic fuels, each of which offers unique advantages and challenges. The study evaluates these fuels across key parameters, such as fuel availability, energy content, emissions profile, required engine modifications, and overall sustainability. The analysis takes into consideration the economic feasibility and infrastructure requirements for large-scale adoption of each fuel.Furthermore, the paper highlights the technological advancements and modifications necessary to optimize IC engines for these alternative fuels. This includes the impact of alternative fuels on engine efficiency, power output, fuel economy, and maintenance requirements. Special attention is given to emissions reduction strategies, with a focus on how each fuel contributes to lowering carbon dioxide (CO₂), nitrogen oxides (NOₓ), and particulate matter (PM) emissions.In addition to evaluating the current state of alternative fuels, the paper addresses the challenges associated with their adoption, including production scalability, distribution infrastructure, and compatibility with existing vehicle technologies. Finally, the future prospects of integrating these fuels into automotive applications are explored, considering the rapid rise of electric vehicles and other emerging technologies that may further influence the role of IC engines in the transition to sustainable transportation.The findings of this study suggest that while no single alternative fuel is likely to fully replace conventional gasoline and diesel in the near future, a combination of fuels, along with continued innovation in fuel production, engine technology, and policy support, will be necessary to achieve sustainable IC engine operation. The paper concludes by outlining the critical research areas and policy initiatives needed to promote the wider adoption of alternative fuels in the automotive sector.    

    

* Insights into the Effect of Crystal Facets and Sulfur Defects on the Product Selectivity of Various CdS Configurations for CO2 Photoreduction: A DFT Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403084362
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Applications of Quantum Dots in Nanotechnology, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-10-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14100688")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403084362"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403084362"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403084362"))][Get cited by]]

OpenAlex: https://openalex.org/W4403084362 (Open access: True)
    
[[https://openalex.org/A5019624996][Shuai Liu]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5046045888][Yu Zhong]], [[https://openalex.org/A5020146176][Leiping Wang]], [[https://openalex.org/A5086597691][Ding‐Ming Xue]], [[https://openalex.org/A5063107775][Lei Tong]], [[https://openalex.org/A5100671934][Honglei Zhang]], [[https://openalex.org/A5043100976][Tao Wu]], [[https://openalex.org/A5102729565][Guangsuo Yu]], [[https://openalex.org/A5072659014][Hang Xiao]], Catalysts. 14(10)] 2024. https://doi.org/10.3390/catal14100688 
     
CO2 photoreduction into valuable hydrocarbons, such as CO, CH4, and C2H4, delivers a promising approach to address both environmental and energy challenges. Transition metal chalcogenides, particularly cadmium sulfide (CdS), have emerged as prominent candidates due to their tunable electronic properties and availability. This study delves into a comprehensive investigation of how CdS crystalline facets and sulfur-deficient surfaces modulate the product selectivity. Through employing density functional theory (DFT), we unravel the catalytic performance of various CdS crystal orientations and sulfur vacancy configurations. The results have shown that different CdS facets exhibit unique electronic characteristics and surface energetics, which influence the adsorption dynamics and reaction pathways. The introduction of sulfur vacancies further modulates the nature of active sites, leading to substantial shifts in product selectivity. A detailed investigation on the reaction mechanisms unveils that specific facets preferentially facilitate the formation of CO, while others are more conducive to the generation of hydrocarbons such as CH4 and C2H4, due to the variations in activation barriers and intermediate stabilities. These findings underscore the importance of crystal facet engineering and defect manipulation in tailoring catalyst performance thus providing valuable insights for the rational design of efficient and selective CO2 reduction metal catalysts.    

    

* Dynamic Adaptation of Active Site Driven by Dual‐side Adsorption in Single‐Atomic Catalysts During CO2 Electroreduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403041985
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Molecular Electronic Devices and Systems, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202411765")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403041985"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403041985"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403041985"))][Get cited by]]

OpenAlex: https://openalex.org/W4403041985 (Open access: False)
    
[[https://openalex.org/A5059260162][Nam V. Tran]], [[https://openalex.org/A5100657882][Jiyuan Liu]], [[https://openalex.org/A5074258793][Shuzhou Li]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202411765 
     
Single‐atom iron embedded in N‐doped carbon (Fe‐N‐C) is among the most representative single‐atomic catalysts (SACs) for electrochemical CO2 reduction reaction (CO2RR). Despite the simplicity of the active site, the CO2‐to‐CO mechanism on Fe‐N‐C remains controversial. Firstly, there is a long debate regarding the rate‐determining step (RDS) of the reactions. Secondly, recent computational and experimental studies are puzzled by the fact that the CO‐poisoned Fe centers still remain highly active at high potentials. Thirdly, there are ongoing challenges in elucidating the high selectivity of hydrogen evolution reaction (HER) over CO2RR at high potentials. In this work, we introduce a novel CO2RR mechanism on Fe‐N‐C, which was inspired by the dynamic of active sites in biological systems. By employing grand‐canonical density functional theory and kinetic Monte‐Carlo, we found that the RDS is not fixed but changes with the applied potential. We demonstrated that our proposed dual‐side mechanisms could clarify the reason behind the high catalytic activity of CO‐poisoned metal centers, as well as the high selectivity of HER over CO2RR at high potential. This study provides a fundamental explanation for long‐standing puzzles of an important catalyst and calls for the importance of considering the dynamic of active sites in reaction mechanisms.    

    

* Dynamic Adaptation of Active Site Driven by Dual‐side Adsorption in Single‐Atomic Catalysts During CO2 Electroreduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403043003
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202411765")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403043003"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403043003"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403043003"))][Get cited by]]

OpenAlex: https://openalex.org/W4403043003 (Open access: False)
    
[[https://openalex.org/A5059260162][Nam V. Tran]], [[https://openalex.org/A5100657882][Jiyuan Liu]], [[https://openalex.org/A5074258793][Shuzhou Li]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202411765 
     
Single‐atom iron embedded in N‐doped carbon (Fe‐N‐C) is among the most representative single‐atomic catalysts (SACs) for electrochemical CO2 reduction reaction (CO2RR). Despite the simplicity of the active site, the CO2‐to‐CO mechanism on Fe‐N‐C remains controversial. Firstly, there is a long debate regarding the rate‐determining step (RDS) of the reactions. Secondly, recent computational and experimental studies are puzzled by the fact that the CO‐poisoned Fe centers still remain highly active at high potentials. Thirdly, there are ongoing challenges in elucidating the high selectivity of hydrogen evolution reaction (HER) over CO2RR at high potentials. In this work, we introduce a novel CO2RR mechanism on Fe‐N‐C, which was inspired by the dynamic of active sites in biological systems. By employing grand‐canonical density functional theory and kinetic Monte‐Carlo, we found that the RDS is not fixed but changes with the applied potential. We demonstrated that our proposed dual‐side mechanisms could clarify the reason behind the high catalytic activity of CO‐poisoned metal centers, as well as the high selectivity of HER over CO2RR at high potential. This study provides a fundamental explanation for long‐standing puzzles of an important catalyst and calls for the importance of considering the dynamic of active sites in reaction mechanisms.    

    

* Towards a Synthetic Positive Energy District (PED) in İstanbul: Balancing Cost, Mobility, and Environmental Impact  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403107776
:TOPICS: Hydrogen Energy Systems and Technologies, Integration of Renewable Energy Systems in Power Grids, Indoor Air Pollution in Developing Countries
:PUBLICATION_DATE: 2024-10-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/buildings14103153")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403107776"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403107776"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403107776"))][Get cited by]]

OpenAlex: https://openalex.org/W4403107776 (Open access: True)
    
[[https://openalex.org/A5049358939][Mi̇ne Sertsöz]], Buildings. 14(10)] 2024. https://doi.org/10.3390/buildings14103153 
     
The influence of mobility modes within Positive Energy Districts (PEDs) has gained limited attention, despite their crucial role in reducing energy consumption and greenhouse gas emissions. Buildings in the European Union (EU) account for 40% of energy consumption and 36% of greenhouse gas emissions. In comparison, transport contributes 28% of energy use and 25% of emissions, with road transport responsible for 72% of these emissions. This study aims to design and optimize a synthetic PED in Istanbul that integrates renewable energy sources and public mobility systems to address these challenges. The renewable energy sources integrated into the synthetic PED model include solar energy, hydrogen energy, and regenerative braking energy from a tram system. Solar panels provided a substantial portion of the energy, while hydrogen energy contributed to additional electricity generation. Regenerative braking energy from the tram system was also utilized to further optimize energy production within the district. This system powers a middle school, 10 houses, a supermarket, and the tram itself. Optimization techniques, including Linear Programming (LP) for economic purposes and the Weighted Sum Method (WSM) for environmental goals, were applied to balance cost and CO2 emissions. The LP method identified that the PED model can achieve cost competitiveness with conventional energy grids when hydrogen costs are below $93.16/MWh. Meanwhile, the WSM approach demonstrated that achieving a minimal CO2 emission level of 5.74 tons requires hydrogen costs to be $32.55/MWh or lower. Compared to a conventional grid producing 97 tons of CO2 annually, the PED model achieved reductions of up to 91.26 tons. This study contributes to the ongoing discourse on sustainable urban energy systems by addressing key research gaps related to the integration of mobility modes within PEDs and offering insights into the optimization of renewable energy sources for reducing emissions and energy consumption.    

    

* Renewable Energy Credits Transforming Market Dynamics  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403101705
:TOPICS: Indoor Air Pollution in Developing Countries, Rebound Effect on Energy Efficiency and Consumption, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-10-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16198602")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403101705"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403101705"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403101705"))][Get cited by]]

OpenAlex: https://openalex.org/W4403101705 (Open access: True)
    
[[https://openalex.org/A5004894444][Bankole I. Oladapo]], [[https://openalex.org/A5084529772][Mattew A. Olawumi]], [[https://openalex.org/A5003790244][Francis T. Omigbodun]], Sustainability. 16(19)] 2024. https://doi.org/10.3390/su16198602 
     
This research uses advanced statistical methods to examine climate change mitigation policies’ economic and environmental impacts. The primary objective is to assess the effectiveness of carbon pricing, renewable energy subsidies, emission trading schemes, and regulatory standards in reducing CO2 emissions, fostering economic growth, and promoting employment. A mixed-methods approach was employed, combining regression analysis, cost–benefit analysis (CBA), and computable general equilibrium (CGE) models. Data were collected from national and global databases, and sensitivity analyses were conducted to ensure the robustness of the findings. Key findings revealed a statistically significant reduction in CO2 emissions by 0.45% for each unit increase in carbon pricing (p < 0.01). Renewable energy subsidies were positively correlated with a 3.5% increase in employment in the green sector (p < 0.05). Emission trading schemes were projected to increase GDP by 1.2% over a decade (p < 0.05). However, chi-square tests indicated that carbon pricing disproportionately affects low-income households (p < 0.05), highlighting the need for compensatory policies. The study concluded that a balanced policy mix, tailored to national contexts, can optimise economic and environmental outcomes while addressing social equity concerns. Error margins in GDP projections remained below ±0.3%, confirming the models’ reliability.    

    

* Ionomer and Membrane Designs for Low‐Temperature CO2 and CO Electrolysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403146014
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Fuel Cell Membrane Technology, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-10-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401728")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403146014"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403146014"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403146014"))][Get cited by]]

OpenAlex: https://openalex.org/W4403146014 (Open access: False)
    
[[https://openalex.org/A5030347659][Huihua Deng]], [[https://openalex.org/A5100345056][Zhuo Chen]], [[https://openalex.org/A5100322864][Li Wang]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401728 
     
Low‐temperature electroreduction of CO2 and CO (CO(2)RR) into valuable chemicals and fuels offers a promising pathway to reduce greenhouse gas emissions and achieve carbon neutrality. Today's low‐temperature CO(2)RR technology relies on the use of ionomers, polymers with ionized groups, primarily as catalyst layer (CL) additives. In the meantime, ionomers can assemble into ion‐exchange membranes (IEMs), serving as important components of electrolyzers. According to the ion‐exchange functions, ionomer additives are classified as cation‐exchange ionomers (CEIs) and anion‐exchange ionomers (AEIs); similarly, IEMs are divided into cation‐exchange membranes (CEMs) and anion‐exchange membranes (AEMs), as well as the multilayer polymer electrolytes (MPEs). Recent studies show that ionomer additives can regulate the catalytic microenvironment and thereby enhance performance towards desired products. This Review discusses the roles of ionomer additives and IEMs in CO2 and CO reduction reactions, highlighting the latest mechanistic insights and performance advances. It outlines challenges in designing ionomer additives and IEMs to improve product selectivity, energy efficiency (EE), and operational lifetime of CO(2)RR electrolyzers, while also providing perspectives on future research directions. The aim is to connect the current status of ionomer and membrane development with performance metrics analysis, offering insights for the advancement of commercially relevant low‐temperature CO(2)RR electrolyzers.    

    

* A Highly Conjugated Nickel(II)‐Acetylide Framework for Efficient Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403129176
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202418269")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403129176"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403129176"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403129176"))][Get cited by]]

OpenAlex: https://openalex.org/W4403129176 (Open access: False)
    
[[https://openalex.org/A5081215511][Yingying Qin]], [[https://openalex.org/A5101934276][Yang Wang]], [[https://openalex.org/A5100341536][Jian Lü]], [[https://openalex.org/A5013976694][Linli Xu]], [[https://openalex.org/A5006003842][Wai‐Yeung Wong]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202418269 
     
The incorporation of transition‐metal single atoms as molecular functional entities into the skeleton of graphdiyne (GDY) to construct novel two‐dimensional (2D) metal‐acetylide frameworks, known as metalated graphynes (MGYs), is a promising strategy for developing efficient catalysts, which can combine the tunable charge transfer of GDY frameworks, the catalytic activity of metal and the precise distribution of single metallic centers. Herein, four highly conjugated MGY photocatalysts based on NiII, PdII, PtII, and HgII were synthesized for the first time using the ‘bottom‐up’ strategy through the use of M–C bonds (–C≡C–M–C≡C–). Remarkably, the NiII‐based graphyne (TEPY‐Ni‐GY) exhibited the highest CO generation rate of 18.3 mmol g‐1 h‐1 and a selectivity of 98.8%. This superior performance is attributed to the synergistic effects of pyrenyl and –C≡C–Ni(PBu3)2–C≡C– moieties. The pyrenyl block functions as an intramolecular π‐conjugation channel, facilitating kinetically favorable electron transfer, while the –C≡C–Ni(PBu3)2–C≡C– moiety serves as the catalytic site that enhances CO2 adsorption and activation, thereby suppressing competitive hydrogen evolution. This study provides a new perspective on MGY‐based photocatalysts for developing highly active and low‐cost catalysts for CO2 reduction.    

    

* The Impact of Hydrogen on Flame Characteristics and Pollutant Emissions in Natural Gas Industrial Combustion Systems  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403140808
:TOPICS: Chemical Kinetics of Combustion Processes, Global Impact of Gas Flaring, Estimating Vehicle Fuel Consumption and Emissions
:PUBLICATION_DATE: 2024-10-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17194959")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403140808"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403140808"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403140808"))][Get cited by]]

OpenAlex: https://openalex.org/W4403140808 (Open access: True)
    
[[https://openalex.org/A5082256677][Yamei Lan]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5013851053][Jingxiang Xu]], [[https://openalex.org/A5103075380][Yi Wang]], Energies. 17(19)] 2024. https://doi.org/10.3390/en17194959 
     
To improve energy savings and emission reduction in industrial heating furnaces, this study investigated the impact of various molar fractions of hydrogen on natural gas combustion and compared the results of the Non-Premixed Combustion Model with the Eddy Dissipation Combustion Model. Initially, natural gas combustion in an industrial heating furnace was investigated experimentally, and these results were used as boundary conditions for CFD simulations. The diffusion flame and combustion characteristics of natural gas were simulated using both the non-premixed combustion model and the Eddy Dissipation Combustion Model. The results indicated that the Non-Premixed Combustion Model provided simulations more consistent with experimental data, within acceptable error margins, thus validating the accuracy of the numerical simulations. Additionally, to analyze the impact of hydrogen doping on the performance of an industrial gas heater, four gas mixtures with varying hydrogen contents (15% H2, 30% H2, 45% H2, and 60% H2) were studied while maintaining constant fuel inlet temperature and flow rate. The results demonstrate that the Non-Premixed Combustion Model more accurately simulates complex flue gas flow and chemical reactions during combustion. Moreover, hydrogen-doped natural gas significantly reduces CO and CO2 emissions compared to pure natural gas combustion. Specifically, at 60% hydrogen content, CO and CO2 levels decrease by 70% and 37.5%, respectively, while NO emissions increase proportionally; at this hydrogen content, NO concentration in the furnace chamber rises by 155%.    

    

* Study of The Energy, Economic, Environmental, and Thermal Comfort Impact of The Integration of Hemp Concrete and Hemp Plaster in a Residential Building Envelope in Morocco  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403062885
:TOPICS: Sustainable Earth Construction Materials and Techniques, Urban Design and Cultural Heritage Conservation, Solar Chimney Systems
:PUBLICATION_DATE: 2024-09-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.37934/arnht.23.1.127")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403062885"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403062885"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403062885"))][Get cited by]]

OpenAlex: https://openalex.org/W4403062885 (Open access: False)
    
[[https://openalex.org/A5044354908][H. Kaddouri]], [[https://openalex.org/A5097821511][Abderrahim Abidouche]], [[https://openalex.org/A5018436716][Mohamed Saidi Hassani Alaoui]], [[https://openalex.org/A5013207882][I. Driouch]], [[https://openalex.org/A5089190461][Said Hamdaoui]], [[https://openalex.org/A5103822243][Abdelouahad Ait Msaad]], Journal of Advanced Research in Numerical Heat Transfer. 23(1)] 2024. https://doi.org/10.37934/arnht.23.1.127 
     
In the building sector, the majority of efforts are aimed at achieving greater energy efficiency, a low carbon footprint, and optimum thermal comfort to make buildings more efficient, more sustainable, and more pleasant to live in. In this context, this paper aims to assess the impact of integrating environmentally friendly and green materials (lime-hemp plaster and hemp concrete) into the envelope of an existing residential building. A numerical simulation study was carried out using TRNSYS 18, in four Moroccan climates: Mediterranean, cold semi-arid, hot semi-arid, and hot and dry desert, to study the energy, economic, and environmental impact, as well as that of the thermal comfort. The proposed construction scenarios are compared with the reference scenario in terms of heating and cooling requirements, electricity bills, carbon footprint, and percentage of annual thermal discomfort. The results show that energy savings are highest in the cold semi-arid climate (Oujda) at around 24%. Hemp concrete construction is more effective in reducing heating requirements, with a reduction of up to 39.4%. For cooling, the reduction is only 15.5%. The economic and environmental study shows that using materials such as hemp concrete in an optimal construction and climatic context can reduce electricity bills by 25% and CO2 emissions by around 23.7%. However, the reduction in terms of hours of discomfort is not yet significant enough. Hence the need to combine this technique with other strategies based on bioclimatic design. The use of hemp plaster and concrete for renovating existing buildings or constructing new ones represents a very promising alternative from several points of view: energy, economic, and environmental.    

    

* Managing Regional Development In The Area of Renewable Energy Sources In Poland  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403039097
:TOPICS: Energy Transition and Renewable Resources Integration, Energy Supply and Security Issues for Developed Economies, Integration of Renewable Energy Systems in Power Grids
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5171/2024.4314224")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403039097"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403039097"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403039097"))][Get cited by]]

OpenAlex: https://openalex.org/W4403039097 (Open access: False)
    
[[https://openalex.org/A5019317544][M. Filipowicz]], Communications of International Proceedings. None(None)] 2024. https://doi.org/10.5171/2024.4314224 
     
This article examines the challenges of power grid congestion in a municipality located in central Poland and presents potential solutions in the form of a photovoltaic farm project or prosumer group installation. In the context of growing demand for electricity and an increasing number of households producing energy from renewable sources, there is a need to upgrade the energy infrastructure to meet the needs of the local community. A planned photovoltaic farm or group prosumer installations are not only a way to relieve stressed grids, but also a step towards sustainable energy production and reduction of CO2 emissions. In the article, I also discuss the economic, social and environmental aspects of implementing these projects and the possible benefits for the municipality and its residents. My analysis indicates the potential for solar energy development in the region and presents effective tools that can help modernize energy infrastructure and promote sustainable development in local communities.    

    

* Implementation of Energy-saving Technologies in House construction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403088596
:TOPICS: Sustainable Urban Development and Construction Practices, Building Information Modeling in Construction Industry, Innovation Economics and Economic Development
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21822/2073-6185-2024-51-3-189-194")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403088596"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403088596"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403088596"))][Get cited by]]

OpenAlex: https://openalex.org/W4403088596 (Open access: True)
    
[[https://openalex.org/A5021773412][E. I. Krupnov]], [[https://openalex.org/A5023685908][Irina A. Zaytseva]], [[https://openalex.org/A5102859542][Svetlana Andreyevna Loginova]], [[https://openalex.org/A5104702983][Aleksandr Vladimirovich Simagin]], Herald of Dagestan State Technical University Technical Sciences. 51(3)] 2024. https://doi.org/10.21822/2073-6185-2024-51-3-189-194 
     
Objective. Over the past decades, heat pumps have gained great popularity due to their advantages in energy efficiency and environmental friendliness, becoming one of the most attractive alternatives to replace traditional heating systems running on fossil fuels. Heat pump efficiency is a decisive factor that should be taken into account when selecting and optimizing a heat pump system. The aim of the study was to evaluate the efficiency of air source heat pumps of the air-to-water system in the climatic conditions typical of the regions of the Central Federal District. Method . To evaluate the efficiency of air source heat pumps, a mathematical model is used that takes into account the multifactorial nature of the process under study. Result. To adequately compare the obtained research results with the passport performance indicators, the transformation coefficient (COP) was used, showing the ratio of the energy received to the expended work. As a result, the method of heating rooms with an air source heat pump with a combined operation mode was recognized as more preferable. Conclusion. Currently, the potential of heat pumps in the field of energy saving and CO2 emission reduction remains largely untapped, which sets the vector for further research.    

    

* Size‐dependent Copper Nanoparticles Supported on Carbon Nanotubes with Balanced Cu+ and Cu0 Dual Sites for the Selective Hydrogenation of Ethylene Carbonate  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403081561
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Conversion of Biomass to Fuels and Chemicals, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202402699")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403081561"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403081561"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403081561"))][Get cited by]]

OpenAlex: https://openalex.org/W4403081561 (Open access: False)
    
[[https://openalex.org/A5101583020][Wanghua Chen]], [[https://openalex.org/A5036155652][Dahye Ji]], [[https://openalex.org/A5100349284][Yanfei Zhang]], [[https://openalex.org/A5101764594][Yuanyuan Cui]], [[https://openalex.org/A5049833038][Yinfeng Cheng]], [[https://openalex.org/A5100714539][Songlin Wang]], [[https://openalex.org/A5073522891][Wei‐Lin Dai]], Chemistry - A European Journal. None(None)] 2024. https://doi.org/10.1002/chem.202402699 
     
Cyclic carbonate hydrogenation offers an alternative for the efficient indirect CO2 utilization. In this study, a series of carbon nanotubes (CNTs) supported xCu/CNTs catalysts with different Cu loadings were fabricated using a convenient impregnation method, and exhibited excellent catalytic activity for the hydrogenation of ethylene carbonate to methanol and ethylene glycol. The structural and physicochemical properties revealed that acid treatment of CNTs resulted in plentiful oxygen‐containing functional groups, providing sufficient anchoring sites for copper species. The calcination process conducted under an inert atmosphere resulted in the formation of ternary CuO, Cu2O, and Cu composites, enhancing the metal‐support interaction and facilitating the formation of balanced Cu0 and Cu+ dual sites as well as high active surface area after reduction. Contributed to the synergetic effect of balanced Cu+ and Cu0 species proved by density functional theory calculation and the electron‐rich CNTs surface, the 40Cu/CNTs catalyst achieved strengthened catalytic performance with methanol yield of 83%, ethylene glycol yield of 99% at ethylene carbonate conversion of >99%, and 150 h of long‐term running stability. Consequently, CNTs supported Cu serve as efficient non‐silica based catalyst for ester hydrogenation.    

    

* Research progress of high‐entropy oxides for electrocatalytic oxygen evolution reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403073360
:TOPICS: Electrocatalysis for Energy Conversion, Emergent Phenomena at Oxide Interfaces, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401663")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403073360"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403073360"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403073360"))][Get cited by]]

OpenAlex: https://openalex.org/W4403073360 (Open access: False)
    
[[https://openalex.org/A5101742243][Qian Zhang]], [[https://openalex.org/A5091806162][Xuexue Wang]], [[https://openalex.org/A5050327114][Xiaomeng Lv]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401663 
     
High‐entropy oxides (HEOs), similar to high‐entropy materials (HEMs), have "four‐core effects", i.e., high‐entropy effect, delayed diffusion effect, lattice distortion effect and cocktail effect, which have attracted more and more attention in the scientific field of renewable energy technology due to their unique structural characteristics, variable chemical composition and corresponding functional properties. HEOs have become potential candidates for electrocatalytic oxygen evolution reaction (OER), which is a key half reaction for electrolytic CO2, nitrogen reduction, and water electrolysis. However, the precise synthesis of HEOs with a wide range of components and structures is challenging, not to mention their active and stable operation for OER. In this paper, we review the recent advancements in the electrocatalytic oxygen evolution facilitated by HEOs in water electrolysis. We analyze these developments from the perspectives of activity and stability in acid and alkaline conditions, respectively. Furthermore, we summarize the design from the aspect of element composition, structure, morphology, and catalyst‐support interactions, along with related reaction mechanism of HEOs. Additionally, we discuss the current challenges faced by HEOs in the field of OER and suggest potential directions for the future development of HEOs beyond water electrolysis application.    

    

* Amorphous Nanobelts for Efficient Electrocatalytic Ammonia Production  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403140466
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Content-Centric Networking for Information Delivery
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202416878")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403140466"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403140466"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403140466"))][Get cited by]]

OpenAlex: https://openalex.org/W4403140466 (Open access: False)
    
[[https://openalex.org/A5001070807][Ziming Su]], [[https://openalex.org/A5100340517][Xiangyu Chen]], [[https://openalex.org/A5104180415][Mingke Sun]], [[https://openalex.org/A5058342388][Xiuyi Yang]], [[https://openalex.org/A5100447386][Jianxin Kang]], [[https://openalex.org/A5058443202][Zhi Cai]], [[https://openalex.org/A5100629806][Xiaotian Wang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202416878 
     
One‐dimensional (1D) amorphous nanomaterials combine the advantages of high active site concentration of amorphous structure, high specific surface area and efficient charge transfer and mass transport of 1D materials, so they present promising opportunities for catalysis. However, a significant challenge involves achieving a balance between the high orientation of 1D morphology and the isotropy of amorphous structure, which severely obstructs the controllable preparation of 1D amorphous materials. Guided by the hard‐soft acids‐bases theory, here we develop a general strategy for preparing 1D amorphous nanomaterials through the precise modulation of bond strength between metal ions and organic ligands for a moderated fastness. The soft base dodecanethiol (DT) is multifunctionally served as both structure‐regulating agent and morphology‐directing agent. Compared with the borderline acids (e.g. Fe2+, Co2+, Ni2+) to construct amorphous structure, soft acid of Cu+ which produced crystalline nanobelts can still be amorphized by reducing the hardness of Cu ions through redox reaction to weak Cu‐SR bond. Due to the combined advantages of amorphous structure and one‐dimensional morphology, amorphous CuDT nanobelts exhibited excellent electrocatalytic activity in electrochemical nitrate reduction, outperformed the most of the reported Cu‐based catalysts. This work will effectively bridge the gap between traditional 1D crystalline nanomaterials and amorphization preparation.    

    

* Amorphous Nanobelts for Efficient Electrocatalytic Ammonia Production  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403141185
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Reduction of Nitro Compounds, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202416878")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403141185"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403141185"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403141185"))][Get cited by]]

OpenAlex: https://openalex.org/W4403141185 (Open access: False)
    
[[https://openalex.org/A5001070807][Ziming Su]], [[https://openalex.org/A5035573035][Xiang‐Yu Chen]], [[https://openalex.org/A5104180415][Mingke Sun]], [[https://openalex.org/A5058342388][Xiuyi Yang]], [[https://openalex.org/A5100447380][Jianxin Kang]], [[https://openalex.org/A5075989623][Zhi Cai]], [[https://openalex.org/A5102772793][Lin Guo]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202416878 
     
One‐dimensional (1D) amorphous nanomaterials combine the advantages of high active site concentration of amorphous structure, high specific surface area and efficient charge transfer and mass transport of 1D materials, so they present promising opportunities for catalysis. However, a significant challenge involves achieving a balance between the high orientation of 1D morphology and the isotropy of amorphous structure, which severely obstructs the controllable preparation of 1D amorphous materials. Guided by the hard‐soft acids‐bases theory, here we develop a general strategy for preparing 1D amorphous nanomaterials through the precise modulation of bond strength between metal ions and organic ligands for a moderated fastness. The soft base dodecanethiol (DT) is multifunctionally served as both structure‐regulating agent and morphology‐directing agent. Compared with the borderline acids (e.g. Fe2+, Co2+, Ni2+) to construct amorphous structure, soft acid of Cu+ which produced crystalline nanobelts can still be amorphized by reducing the hardness of Cu ions through redox reaction to weak Cu‐SR bond. Due to the combined advantages of amorphous structure and one‐dimensional morphology, amorphous CuDT nanobelts exhibited excellent electrocatalytic activity in electrochemical nitrate reduction, outperformed the most of the reported Cu‐based catalysts. This work will effectively bridge the gap between traditional 1D crystalline nanomaterials and amorphization preparation.    

    

* B-031 A new Ready to use Bio-Rad Quality Control to Streamline Daily Workflow  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403048859
:TOPICS: Management and Reproducibility of Scientific Workflows
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/clinchem/hvae106.395")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403048859"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403048859"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403048859"))][Get cited by]]

OpenAlex: https://openalex.org/W4403048859 (Open access: False)
    
[[https://openalex.org/A5093369284][A M Yagoot]], [[https://openalex.org/A5041872360][Hassan A. Khalil]], [[https://openalex.org/A5101760929][Mohammed A. Alharbi]], [[https://openalex.org/A5096913865][G. Almalayo]], [[https://openalex.org/A5018917563][Anwar Borai]], Clinical Chemistry. 70(Supplement_1)] 2024. https://doi.org/10.1093/clinchem/hvae106.395 
     
Abstract Background A comprehensive Quality Management System starts with performing a daily Quality Control (Q.C.) process. The daily Q.C. process monitors the Instrument’s optimal performance and detects shifts and trends. However, the existing traditional daily Q.C. process is not only prone to manual errors, but also time consuming, costly and labor intensive. We evaluated a Bio-Rad InteliQTM Load and go Quality Control that comes in a barcoded tube ready to be loaded. We monitored the workflow efficiency gained in comparison to the traditional quality control material that comes in glass vials. Methods We evaluated the new quality control material ready to load on the instrument. This new Q.C. (Bio-Rad InteliQ Assayed Multiqual Control - 3 levels) were processed in parallel with our routine Q.C. (Bio-Rad Assayed Chemistry Lyphocheck vials - 2 levels). We performed the evaluation on Abbott Architect c8000 Chemistry analyzers in our central Laboratory (NGHA-Jeddah). The Q.C. was stored frozen. Before testing it was thawed at room temperature as per the insert instruction. Over a 5 days period, in parallel with our routine quality control, we run the new Q.C. Two times per day for 33 analytes. We monitored the processing time difference between the new and current approaches. We monitored the stability of all the analytes in the tube after Two days and again after Five days. We also monitored the cost effectiveness, labor intensiveness, probability of operator error and the overall improvement in workflow and Turn Around Time. Results Over the evaluation period, we observed the following: - Saving 40 minutes in average per week only for chemistry Q.C (time spent in reconstituting, mixing and aliquoting old Q.C) - 100% reduction in waste of plastic consumables such as pipette and plastic tubes. - Save an average of 1.0 ml dead volume in every 5.0 ml old Q.C. vial (20% of the volume, hence saving 20% of the total Q.C. cost). The dead volume wasted due to aliquoting step using the old Q.C. - 100% Eliminated delays caused by operator error such as wrong reconstitution, inadequate mixing and wrong Q.C. aliquoting. Not needed for the InteliQ. - High score of staff satisfaction. - Stability of the 32 analytes was excellent except that of Co2, which deteriorated by 14% after Two days as indicated in the insert package. Co2 day five result deteriorated by 34%. Conclusions Bio-Rad InteliQ is easy to use. It saves time and cost. When combined with Unity Q.C. data management solution it can streamline Q.C. workflow, eliminate operator errors, reduce T.A.T. and increase the overall laboratory performance. It may also work optimally with Instruments that have on-board fridge for Q.C.    

    

* 12201 Ketogenic-diet As A Trigger Of First Episode Diabetic Ketoacidosis In A Woman Living With Type 1 Diabetes Mellitus  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403153887
:TOPICS: Effects of Ketogenic Diet on Health, Brown Adipose Tissue Function and Physiology, Genetics and Pathogenesis of Type 1 Diabetes
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1210/jendso/bvae163.826")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403153887"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403153887"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403153887"))][Get cited by]]

OpenAlex: https://openalex.org/W4403153887 (Open access: True)
    
[[https://openalex.org/A5060989480][Margarida Cruz]], [[https://openalex.org/A5022612153][Alex N Gonzalez Bossolo]], [[https://openalex.org/A5030452799][Gabriel Jose Mora Osoria]], Journal of the Endocrine Society. 8(Supplement_1)] 2024. https://doi.org/10.1210/jendso/bvae163.826 
     
Abstract Disclosure: M.E. Chacon Cruz: None. A.N. Gonzalez Bossolo: None. G.J. Mora Osoria: None. A number of dietary patterns have been proposed as an effective method for weight reduction. A keto diet is a strict low-carbohydrate and high-fat diet. The reduction in carbohydrates enables the body to rely on fat as a predominant energy source leading to a state of ketosis. However, a serious but rare complication of the ketogenic diet is ketoacidosis associated with low carbohydrate intake, which should be cautiously monitored in people with a predisposition to the condition, such patient with diabetes mellitus type 1. We report the case of a female patient living with type 1 diabetes mellitus female who developed her first episodes of diabetic ketoacidosis (DKA) as the following the course of ketogenic diet. A 53 y/o Female patient with past medical history diabetes mellitus type 1 and pernicious anemia went emergency department complaining pelvic pain associated with weakness, nausea and vomiting for about 1 day of evolution. Patient also refers that during the past 2 weeks she has been doing a detox and taking some herbal and tea. Other physical examinations were unremarkable except for moderate dehydration. The initial testing revealed patients meet criteria for severe diabetes ketoacidosis (DKA) with a pH: 7.04, CO2 15, serum central bicarbonate in 6 mmol/L and elevated blood glucose in 504 mg/dl and positive urine and serum ketones, C-Peptide less than 0.02 ng/ml. and glycosylated hemoglobin in 8.25%. She was admitted to the intensive care unit and treated with intravenous saline, intravenous insulin infusion, and electrolyte repletion. Blood glucose levels and metabolic acidosis improved. After DKA resolved patient refers that week started with Keto-diet and was restricting carbohydrates. Patient was discharge home with multiple injection insulin and followed by Endocrinologist services in the external clinic for a follow up. This case illustrates the challenges and the importance of dietary history providing clues to the diagnosis. If we had never asked her about her diet, we would not have found the reason that brought her to the DKA. This case demonstrates the development of DKA following ketogenic diet in a patient with type 1 diabetes. It is important for physicians to be aware of this rare potential complication of ketogenic diet which is infrequently reported in literature. Therefore, physicians should be cognizant of the complications and risks, and benefits of the ketogenic diet. Risks and benefits of the ketogenic diet should be discussed with patients before initiation of this diet. The patient was followed in an outpatient clinic with Endocrinologist service for evaluation for an insulin pump. Presentation: 6/1/2024    

    

* A Novel Hybrid Physics/Data-Driven Model for Fractured Reservoir Simulation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403091249
:TOPICS: Hydraulic Fracturing in Shale Gas Reservoirs, Advanced Techniques in Reservoir Management, Seismic Waveform Inversion in Geophysics
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2118/219110-pa")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403091249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403091249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403091249"))][Get cited by]]

OpenAlex: https://openalex.org/W4403091249 (Open access: False)
    
[[https://openalex.org/A5015738141][Billal Aslam]], [[https://openalex.org/A5081032657][Bicheng Yan]], [[https://openalex.org/A5040515504][Knut–Andreas Lie]], [[https://openalex.org/A5003792251][Stein Krogstad]], [[https://openalex.org/A5066325589][Olav Møyner]], [[https://openalex.org/A5009325358][Xupeng He]], SPE Journal. None(None)] 2024. https://doi.org/10.2118/219110-pa 
     
Summary Fractured reservoir simulation plays a crucial role in understanding various subsurface geo-energy recovery and storage processes, including shale gas/oil extraction, enhanced geothermal systems, and CO2 sequestration in basaltic rocks. However, such simulations often entail significant computational expenses due to the high contrast in permeability and pore volume (PV) between matrix and fractures. To address this challenge, we introduce a reduced-order model (ROM) tailored for fractured reservoir simulation that offers flexible fracture representations by generating coarse matrix nodes based on reservoir outlines and adding extra diagonal connections between unconnected matrix nodes, whose corresponding volumes are intersected by fractures. This approach avoids the need for additional fracture nodes, effectively reducing computational costs. Dimensionality reduction methods, such as principal component analysis (PCA), are used to give quality priors for sampling matrix transmissibility and PV arrays. Tuning to well observation data, such as flow rates and bottomhole pressures (BHPs), is achieved through a gradient-based optimization method within a general automatic-differentiable simulator framework. Our results demonstrate robust calibration using synthetic well observation data from a fine-scale reference simulation model. Incorporating dominant flow physics, such as water breakthrough, from observation data improves history-matching (HM) convergence and prediction accuracy. Additionally, PCA for parameterization enhances the convergence rate of model calibration compared with random initialization. Calibrated transmissibilities align with high-connectivity regions from the fine-scale reference model, rendering the model interpretable in terms of reservoir connectivity or geology. This feature enables our method to be used effectively for reservoir HM and optimization using field observation data.    

    

* A-198 ESG Opportunities Harnessed During Pathology Transformation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403071086
:TOPICS: Advancements in Biomedical Science and Health Research
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/clinchem/hvae106.196")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403071086"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403071086"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403071086"))][Get cited by]]

OpenAlex: https://openalex.org/W4403071086 (Open access: False)
    
[[https://openalex.org/A5063554177][T Ellison]], [[https://openalex.org/A5042030924][Louise Hughes]], [[https://openalex.org/A5077475299][R. F. G. Booth]], [[https://openalex.org/A5024936437][Garry M. Walsh]], [[https://openalex.org/A5005895944][David Dunn]], Clinical Chemistry. 70(Supplement_1)] 2024. https://doi.org/10.1093/clinchem/hvae106.196 
     
Abstract Background Synnovis (a SYNLAB business) is in the process of delivering one of the largest Pathology transformation programmes in the UK, moving to a seven-site hub and spoke model from 89 laboratories over a dispersed geography. This remit also presented an opportunity for SYNLAB to deliver on its Environmental Social Governance (ESG) ambitions, by embedding ESG principles into programme delivery. There are several examples within each ESG pillar that demonstrate the benefits to be leveraged during transformation. Methods SYNLAB’s vision is to deliver sustainable diagnostic services. The integration of ESG into both the decision-making process and transformation structure ties these ambitions into programme benefits realisation. As well as setting performance level targets, the delivery of ESG benefits provide measures of success throughout the transformation journey, motivating stakeholders and building confidence along the way. Results Environment: The efficient use of space and LEAN principle design has consolidated the fragmented laboratory services spanning 15,000m2 into a bespoke, cutting-edge Pathology Hub with 6 spokes (hospital based services). The new hub building was designed to achieve BREEAM Excellent standards which measure performance against criteria such as energy management and efficiency, sustainable design and materials. The hub’s energy is from renewable-backed sources, and we will achieve a 47% reduction in CO2 equivalent (CO2e) emissions by unifying a significant proportion of its legacy footprint in this way. Further energy savings will be achieved through the associated analytical equipment consolidation, including a decrease from 50 to 14 microtomes, a decrease of 29 to 15 ventilated benches and a reduction of over 200 fridges and freezers across the service. In addition, substantial CO2e emissions savings are also being delivered by moving to a greener logistics provider, utilising electric vehicles and bikes. 2023 saw such emissions fall by 60% across Synnovis, helping to keep London’s air cleaner. Social: The transformation programme enables the hand back of over 6,000m2 of real estate to Synnovis’ NHS partners to use for critical hospital services (the equivalent of over 150 operating theatres). Governance Both internally and externally, ESG is integrated within the Synnovis organisational culture. For example, internally it applies mandatory sustainability metrics to its solution selection processes. These influenced the selection of Abbott’s Indexor solution to support the transformation of Blood Sciences, delivering a saving of over 2.8 million plastic sample bags every year. Externally, SYNLAB works with its partners to manage this substantial and complex transformation programme. Risk management is assured through transparency, securing confidence in the good use of public funds, ensuring responsiveness to customer and partner feedback, and ensuring accountability for and the delivery of targeted healthcare outcomes. Conclusions The integration of SYNLAB’s ESG strategy within the transformation programme is delivering tangible benefits across all ESG pillars. It has highlighted that in addition to the core outcome of services transformation, there are many more opportunities that can be realised as a result of making ESG an integral part of the pathology transformation programme.    

    

* Making of an Indigenous and Efficient Powertrains for EV, HEV & FCEV’s  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403077243
:TOPICS: Integration of Electric Vehicles in Power Systems, State of the Art in Electric and Hybrid Vehicles, Lithium-ion Battery Management in Electric Vehicles
:PUBLICATION_DATE: 2024-08-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.37285/ajmt.4.3.0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403077243"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403077243"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403077243"))][Get cited by]]

OpenAlex: https://openalex.org/W4403077243 (Open access: False)
    
[[https://openalex.org/A5000757204][S. S. Ramdasi]], ARAI Journal of Mobility Technology. 4(3)] 2024. https://doi.org/10.37285/ajmt.4.3.0 
     
Rise in greenhouse gas emissions which is resulting into ozone layer depletion and global warming effect is alarming to control CO2 emissions by drastically reducing fossil fuel consumption from the vehicles. This need has already started trend towards extreme downsizing and down speeding of Internal Combustion Engines (ICE) for making them highly efficient. In addition to this use of after treatment devices viz. Diesel Oxidation Catalyst (DOC), Diesel Particulate Filter (DPF), Lean NOx Catalyst (LNT), Selective Catalytic Reduction (SCR) are helping to a great extent for meeting emission norms till Euro - VI for automotive sector, Tier–IV F and Stage V for Off Highway Power sector. However, to address present greenhouse effect along with exponential decay of fossil fuels, there is need to achieve CO2 emissions less than 100 g/km or to achieve practically zero carbon footprint using an alternate powertrain. Electrification is one of the promising solutions and which is three-fold in present situation. The first level of electrification comes in the form of Hybrid Electric Vehicle (HEV) technology followed by Battery Electric Vehicles and Fuel Cell Electric Vehicles as second and third level of electrification respectively. In all these technologies a common thread is running in the form of an efficient electric drive train. Several efforts have been taken to improve torque per unit ampere by use of efficient motor and motor control algorithms viz PMSM powered with FOC, by developing controls which take care of parametric variations and external force disturbances by use of back stepping techniques which are based on rotor resistance estimation by fuzzy logic, FOC techniques based on adaptive input-output feedback linearization, by shifting towards high voltage systems, by going for higher switching frequencies for inverters which uses silicon carbide based MOSFET switches, by exploring use of multilevel inverters for Total Harmonic Distortion (THD) control etc. Use of E Axle based powertrains in EV, HEV and FCEV offers additional complimentary benefits apart from technology options described above. E Axle based powertrains offers flexibility in generating three variants of vehicle using one electric drive train architecture viz. making EV, HEV & FCEV. Compactness, modularity, scalability, flexibility along with efficient cooling system management and control over active current losses due to use of bus bars are the implicit advantages of E Axle based powertrains. These advantages further get multiplies if we go for 3 in 1 (gearbox + Stator housing + Inverter) architectures which are predominantly used in independent suspension-based vehicles. Lot of efforts are going on to inherit this technology for rigid axle suspension based commercial vehicles. Research in this area is getting further extended to make 5 in 1 E Axles where there will addition of DC - DC converter and On-Board Charger (OBC) apart from components present in 3 in 1 configuration. Two major challenges need to be addressed and to be resolved while designing E Axle based powertrains by doing concurrent vehicle engineering. This is mainly due to increased unsprang weight that need to be handled by suspension system and exposed electric drive components to excitation loads coming from roads. Fig: Indigenously Developed E Axle Based Powertrain for Small Commercial VehiclesBy proper lay outing for effective vehicle mass distribution and required CG location which is essential from overall vehicle dynamics, more space can be offered by E Axle based powertrains for increasing battery energy density for getting more electric range in case of BEV’s. This add on space benefit extend help in packaging of hydrogen fuel cell integrated with power cells in case of FCEV’s. Thus, E Axle based powertrains proves to be modern and most efficient way of making EV, HEV & FCEV’s.    

    
