#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Tue Apr  2 00:47:28 2024

Found 29 results from 2024-03-26 to 2024-04-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Highly Efficient Carbon Dioxide Electroreduction via DNA-Directed Catalyst Immobilization  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393150984
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacsau.3c00823")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393150984"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393150984"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393150984"))][Get cited by]]

OpenAlex: https://openalex.org/W4393150984 (Open access: True)
    
[[https://openalex.org/A5079948886][Gang Fan]], [[https://openalex.org/A5003707206][Nathan Corbin]], [[https://openalex.org/A5002058691][Minju Chung]], [[https://openalex.org/A5040466056][Thomas M. Gill]], [[https://openalex.org/A5057877864][Evan G. Moore]], [[https://openalex.org/A5003630361][Amruta A. Karbelkar]], [[https://openalex.org/A5018653043][Ariel L. Furst]], JACS Au. None(None)] 2024. https://doi.org/10.1021/jacsau.3c00823  ([[https://pubs.acs.org/doi/pdf/10.1021/jacsau.3c00823][pdf]])
     
No abstract    

    

* Engineered Escherichia coli Whole Cell-Mediated Electro-Biocatalysis for Carbon Dioxide to Formic Acid Conversion  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393164149
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Microbial Fuel Cells and Electrogenic Bacteria Technology, Metabolic Engineering and Synthetic Biology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acssuschemeng.3c08129")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393164149"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393164149"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393164149"))][Get cited by]]

OpenAlex: https://openalex.org/W4393164149 (Open access: False)
    
[[https://openalex.org/A5091670895][Hongbo Shi]], [[https://openalex.org/A5008802175][Meng-Xi Fu]], [[https://openalex.org/A5048080197][Shu Yuan]], [[https://openalex.org/A5011678003][Yao Lu]], [[https://openalex.org/A5058942307][Yang Zhuan]], [[https://openalex.org/A5040924648][Chao Ye]], [[https://openalex.org/A5042596783][Lunguang Yao]], [[https://openalex.org/A5064910193][Chuang Xue]], [[https://openalex.org/A5077458103][Cun-Duo Tang]], ACS Sustainable Chemistry & Engineering. None(None)] 2024. https://doi.org/10.1021/acssuschemeng.3c08129 
     
The conversion of CO2 into a valuable chemical fuel could help reduce its effect on global warming. However, the utilization of CO2 by biological transformations is challenging because of the lack of enzymes exhibiting high catalytic activity toward CO2 reduction. In this work, three NAD+/W-containing formate dehydrogenases (FDHs) were discovered, expressed, and characterized. In addition, we used PbFDH, which displays high catalytic activity toward CO2 reduction, as a biocatalyst to convert CO2 to formic acid through whole-cell biocatalysis and electro-biocatalysis. The specific activities of DaFDH, PbFDH, and CsFDH increased by 68.1, 100.0, and 18.7 times, respectively, compared with that of ClFDH reported with high catalytic efficiency. Furthermore, this paper presents a preliminary discussion of the catalytic mechanism of FDHs for CO2 reduction based on their structures. The yield of formic acid obtained from CO2 reduction using electro-biocatalysis under aerobic conditions reaches up to 4.1 mmol/L/h, without any cofactor NADH and hydrogen gas. This study also demonstrates and compares the performances of NAD+/W-containing and NAD+-dependent FDHs in whole-cell biocatalysis and electro-biocatalysis. The findings of this study provide a meaningful foundation for the conversion of CO2 into a value-added chemical fuel.    

    

* Gas Diffusion Electrodes (GDEs) for Carbon Dioxide (CO2) Reduction in Microfluidic Cells: Towards a Fluid Dynamics Assisted Rational Design  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393164782
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Origins and Future of Microfluidics, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/1945-7111/ad377f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393164782"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393164782"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393164782"))][Get cited by]]

OpenAlex: https://openalex.org/W4393164782 (Open access: True)
    
[[https://openalex.org/A5057129833][Melanie Colet-Lagrille]], [[https://openalex.org/A5038054687][Sergio González-Poggini]], [[https://openalex.org/A5094242020][Carol Salazar-Espinoza]], [[https://openalex.org/A5028200010][Benito Sánchez]], Journal of The Electrochemical Society. None(None)] 2024. https://doi.org/10.1149/1945-7111/ad377f 
     
Abstract The electrochemical reduction of carbon dioxide (CO2) for the generation of multicarbon (C2+) products with high commercial value – e.g., ethanol and ethylene – is gaining growing interest due to the successful implementation of laboratory scale technologies that can reach high current densities (>500 mA cm-2) and Faradaic efficiencies (>60%), using a simplified approach in terms of configuration and cost. This is the case of microfluidic cells, low-temperature electrochemical flow systems which optimal operation sustains on the enhancement of the mass and charge transfer phenomena taking place at the gas diffusion electrode (GDE) | aqueous electrolyte interface where CO2 molecules are selectively transformed at the surface of the catalyst layer. &#xD;This work presents an up-to-date overview of materials and operational conditions for microfluidic-type systems, providing significant enlightenment on the effects that the phenomena occurring at the GDE | electrolyte interface have over the CO2 reduction reaction kinetics towards the generation of C2+ products. It is shown that the integration of computational methods (particularly, density functional theory and computational fluid dynamics) to conventional experimental approaches is an effective strategy to elucidate the reactions mechanisms and mass/charge transfer trends determining the enhanced design of GDEs and the GDE | electrolyte interface.    

    

* Recent Progress on the Surface and Bulk Modification of Carbon Nitrides for Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393276940
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ente.202400136")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393276940"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393276940"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393276940"))][Get cited by]]

OpenAlex: https://openalex.org/W4393276940 (Open access: False)
    
[[https://openalex.org/A5059973732][Sisi Ma]], [[https://openalex.org/A5034242615][Shuaipeng Wang]], [[https://openalex.org/A5029403476][Xin Wang]], [[https://openalex.org/A5043018151][Songcan Wang]], Energy technology (Weinheim. Print). None(None)] 2024. https://doi.org/10.1002/ente.202400136 
     
Photocatalytic CO 2 reduction has been considered as a green and sustainable approach to solve energy and environmental problems. However, the CO 2 reduction efficiency of various types of semiconductor photocatalysts studied at this stage is far from realizing practical applications. The challenge of photocatalytic CO 2 reduction is to design photocatalysts with excellent catalytic performance. This article summarizes the carbon nitride materials for efficient CO 2 reduction and obtaining high value‐added products. The physicochemical properties of carbon nitride materials are discussed in terms of the photocatalytic mechanisms (bandgap tuning, high specific surface area, shorter electron–hole transmission paths, increasing the number of active sites, etc.). The present review provides the latest research progress of carbon nitride modification strategies. The prospects and challenges for the application of carbon nitride materials for CO 2 reduction are presented. This review article will provide useful guidance for further research on carbon nitride materials for efficient photocatalytic CO 2 reduction.    

    

* Electronic Structure Design of Transition Metal-Based Catalysts for Electrochemical Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393277737
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Thermoelectric Materials
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.4c01456")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393277737"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393277737"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393277737"))][Get cited by]]

OpenAlex: https://openalex.org/W4393277737 (Open access: True)
    
[[https://openalex.org/A5066488748][Liang Guo]], [[https://openalex.org/A5025709244][Jingwen Zhou]], [[https://openalex.org/A5041781809][Fu Liu]], [[https://openalex.org/A5005566472][Xiangchuan Meng]], [[https://openalex.org/A5085300962][Yangbo Ma]], [[https://openalex.org/A5052246820][Fengkun Hao]], [[https://openalex.org/A5011847790][Yi Xiong]], [[https://openalex.org/A5065739319][Zhanxi Fan]], ACS nano. None(None)] 2024. https://doi.org/10.1021/acsnano.4c01456  ([[https://pubs.acs.org/doi/pdf/10.1021/acsnano.4c01456][pdf]])
     
No abstract    

    

* Ladder type covalent organic frameworks constructed with natural units for the oxygen and carbon dioxide reduction reactions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393282347
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Chemistry and Applications of Metal-Organic Frameworks, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150812")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393282347"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393282347"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393282347"))][Get cited by]]

OpenAlex: https://openalex.org/W4393282347 (Open access: False)
    
[[https://openalex.org/A5060008686][Minghao Liu]], [[https://openalex.org/A5090717104][Shuai Yang]], [[https://openalex.org/A5015297626][Yubin Fu]], [[https://openalex.org/A5032456464][Xiubei Yang]], [[https://openalex.org/A5076573585][Xuewen Li]], [[https://openalex.org/A5048468640][Jun He]], [[https://openalex.org/A5069765087][Qing Xu]], [[https://openalex.org/A5028394871][Gaofeng Zeng]], Chemical engineering journal (1996. Print). None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150812 
     
Covalent organic frameworks (COFs) constructed with metallocyclophane units and organic linkers have found application as electrocatalytic systems. Nevertheless, the majority of linkers within COFs necessitate intricate design and synthesis. Conversely, the potential utilization of natural building blocks in COF construction remains largely unexplored. In this study, we constructed a natural COF (CoPc-EA-COF) by employing a natural phenolic molecule (ellagic acid (EA)) as the linker and Co-hexadecafluorophthalocyanine (CoPc) as blocks. This framework serves as an electrocatalyst for both the oxygen reduction reaction (ORR) and carbon dioxide reduction reaction (CO2RR). The incorporation of EA units imparts the CoPc-EA-COF with elevated electronic conductivity, enhanced CO2 binding affinity, and superior reductive capacity compared to the controlled COF lacking EA units. The CoPc-EA-COF demonstrated enhanced performance in the ORR, as evidenced by a half-wave potential of 0.80 V. Moreover, it showcased elevated activity and selectivity in the CO2RR, achieving a maximum CO faradic efficiency of 97.32 % at − 0.8 V, along with turnover frequency (TOF) values reaching 2092 h−1. Theoretical calculations revealed that the presence of EA units facilitated the generation of OOH* and COOH* species, which are pivotal in the rate-determining stages of both ORR and CO2RR processes. The contribution of EA units significantly bolstered the overall catalytic activity.    

    

* The reduction mechanism of C1 product from carbon dioxide catalyzed by Ni-doped g-C3N4  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393305887
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.114064")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393305887"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393305887"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393305887"))][Get cited by]]

OpenAlex: https://openalex.org/W4393305887 (Open access: False)
    
[[https://openalex.org/A5060962249][Shuwei Zhang]], [[https://openalex.org/A5051223797][Hai Feng]], [[https://openalex.org/A5022640003][Chenyu Li]], [[https://openalex.org/A5081363438][Xihua Cao]], [[https://openalex.org/A5055839024][Hui Li]], [[https://openalex.org/A5059819025][Yang Wu]], Molecular catalysis (Online). 559(None)] 2024. https://doi.org/10.1016/j.mcat.2024.114064 
     
This work employs density functional theory (DFT) to scrutinize the catalytic efficacy of nano nickel (Ni) clusters supported by graphitic carbon nitride (Nin@g-C3N4, where n ranges from 1 to 6) in the context of the CO2 reduction reaction (CO2RR). Structural examination revealed that Nin@g-C3N4 possesses a substantial binding energy (-1.63 eV to -7.72 eV), confirming the structural stability of the catalyst in the CO2RR. Electronic structure analysis revealed a pronounced orbital overlap near the Fermi level between the 3d orbital of Ni atoms and the 2p orbital of adjacent cavity nitrogen atoms in Nin@g-C3N4. Further insights are gleaned from the calculations of the Bader charge and energy band, indicating significant charge transfer and band gap alteration, suggesting enhanced conductivity due to Ni doping on g-C3N4. The catalytic performance in the CO2RR is predominantly influenced by the size of the doped Ni clusters. The Ni4@g-C3N4 cluster demonstrated optimal efficiency in producing formic acid (HCOOH) with a limiting potential of -0.12 V. In contrast, the Ni5@g-C3N4 cluster excels in methane (CH4) formation, with a limiting potential of -0.35 V. Additionally, these catalysts exhibit marked inhibition of the hydrogen evolution reaction, further underscoring their potential in CO2RR applications.    

    

* Investigation of iron oxide supported on activated coke for catalytic reduction of sulfur dioxide by carbon monoxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393306954
:TOPICS: Desulfurization Technologies for Fuels, Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jaap.2024.106488")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393306954"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393306954"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393306954"))][Get cited by]]

OpenAlex: https://openalex.org/W4393306954 (Open access: False)
    
[[https://openalex.org/A5016354285][Shanchuan Li]], [[https://openalex.org/A5076273742][Tai Feng]], [[https://openalex.org/A5044451841][Qiwen Kong]], [[https://openalex.org/A5027835055][Jun Li]], [[https://openalex.org/A5031500475][Peiyi Liu]], [[https://openalex.org/A5090322041][Peng Ni]], [[https://openalex.org/A5046573151][Cuiping Wang]], Journal of analytical and applied pyrolysis (Print). None(None)] 2024. https://doi.org/10.1016/j.jaap.2024.106488 
     
In view of the low utilization rate of by-product in limestone-gypsum wet flue gas desulfurization process, a method of catalytic reduction of SO2 to elemental sulfur was proposed. In this work, supported iron catalyst using activated coke as supporter was prepared and characterized. Moreover, the performance of SO2 reduction using CO as reducing agent at various Fe loadings, temperatures, gaseous hourly space velocities and CO/SO2 molar ratios was studied. Research shows that, compared with other metals, the highest catalytic activity is achieved over Fe-based catalyst. The iron sulfide is the main active component during the catalytic reduction reaction, hence the catalyst needs to be presulfided before use. The micropores of activated coke become more abundant after loading Fe, whereas excessive increase of Fe loading may bloke the mesopores and weaken the catalytic activity. Higher reaction temperature, lower GHSV and a stoichiometric molar ratio are conducive to the improvement of SO2 conversion and S yield. The catalytic performance at lower temperatures was further improved by loading Co. When the Co loading is 4 wt.%, the SO2 conversion rate reaches 90.9% at 400 °C because loading Co enhances the redox performance of the catalyst surface. The findings are instructive for the development of cost-effective carbon-based catalysts for resource recovery of sulfur.    

    

* Reduction of Cofed Carbon Dioxide Modifies the Local Coordination Environment of Zeolite-Supported, Atomically Dispersed Chromium to Promote Ethane Dehydrogenation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393308679
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Chemistry of Actinide and Lanthanide Elements
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c00995")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393308679"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393308679"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393308679"))][Get cited by]]

OpenAlex: https://openalex.org/W4393308679 (Open access: True)
    
[[https://openalex.org/A5094241352][Wenqi Zhou]], [[https://openalex.org/A5061752204][Noah Felvey]], [[https://openalex.org/A5024583086][Jiawei Guo]], [[https://openalex.org/A5045854318][Adam S. Hoffman]], [[https://openalex.org/A5047493092][Simon R. Bare]], [[https://openalex.org/A5042039275][Ambarish Kulkarni]], [[https://openalex.org/A5065439644][Ron C. Runnebaum]], [[https://openalex.org/A5022071918][Coleman X. Kronawitter]], Journal of the American Chemical Society (Print). None(None)] 2024. https://doi.org/10.1021/jacs.4c00995  ([[https://pubs.acs.org/doi/pdf/10.1021/jacs.4c00995][pdf]])
     
No abstract    

    

* Membrane contactor-photocatalytic hybrid system for carbon dioxide capture and conversion to formic acid  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393359313
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.rineng.2024.102085")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393359313"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393359313"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393359313"))][Get cited by]]

OpenAlex: https://openalex.org/W4393359313 (Open access: True)
    
[[https://openalex.org/A5011994599][Andi Rina Ayu Astuti]], [[https://openalex.org/A5036754998][Wibawa Hendra Saputera]], [[https://openalex.org/A5085718408][Danu Ariono]], [[https://openalex.org/A5057233335][I Gede Wenten]], [[https://openalex.org/A5015596389][Dwiwahju Sasongko]], Results in engineering. None(None)] 2024. https://doi.org/10.1016/j.rineng.2024.102085 
     
The escalating demand for Carbon Capture and Utilization (CCU) schemes to mitigate CO2 emissions has propelled research into more efficient methods of CO2 conversion, such as the production of formic acid. While traditional approaches often require harsh operating conditions and substantial energy inputs, photocatalysis offers a promising alternative by harnessing CO2, water, and light for formic acid production. This study evaluates the performance and reaction kinetics of CO2 capture and conversion to formic acid using an integrated membrane contactor and photocatalytic process. Investigation into various CO2 absorbents and reduction catalysts reveals that TEA achieves a CO2 loading of 0.957 moles of CO2/mole of solvent, while NaOH achieves 0.75 moles of CO2/mole of solvent over a 4-hour operation period. Subsequent photoreduction of CO2 results in formic acid concentration of 15.89 ppm using ZnO and 10.16 ppm using TiO2 within the same 4-hour operation period at a gas flow rate of 800 ml/min. The rate of CO2 photoreduction to formic acid emerges as the limiting factor in this integrated process, indicating a need for further optimization. Key parameters identified for optimal performance include a UV source of 500 W, a medium pH of 10, and a catalyst loading of 0.5 g/L. This study contributes to the advancement of CCU technologies by demonstrating the feasibility of integrating CO2 capture and photoreduction using membrane contactors and photocatalytic systems, paving the way for sustainable formic acid production.    

    

* Synthesis, study and characterization of new molecular catalysts for reduction of carbon dioxide with a view to use it as a carbon source.  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393356945
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2012-11-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393356945"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393356945"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393356945"))][Get cited by]]

OpenAlex: https://openalex.org/W4393356945 (Open access: False)
    
[[https://openalex.org/A5058725002][Marc Bourrez]], HAL (Le Centre pour la Communication Scientifique Directe). None(None)] 2012. None 
     
No abstract    

    

* Photoelectrochemical Catalytic Co2 Reduction Enhanced by In-Doped Gan and Combined with Vibration Energy Harvester Driving Co2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393143337
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4772115")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393143337"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393143337"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393143337"))][Get cited by]]

OpenAlex: https://openalex.org/W4393143337 (Open access: False)
    
[[https://openalex.org/A5090374198][Mingxiang Zhang]], [[https://openalex.org/A5041362389][Li Wen]], [[https://openalex.org/A5072981099][Shanghao Gu]], [[https://openalex.org/A5058741911][Weihan Xu]], [[https://openalex.org/A5027800643][Zhouguang Lu]], [[https://openalex.org/A5010016722][Fei Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4772115 
     
No abstract    

    

* Theoretical Prediction Leads to Synthesize GDY Supported InOx Quantum Dots for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393314672
:TOPICS: Gas Sensing Technology and Materials, Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202318080")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393314672"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393314672"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393314672"))][Get cited by]]

OpenAlex: https://openalex.org/W4393314672 (Open access: False)
    
[[https://openalex.org/A5042996042][Feng He]], [[https://openalex.org/A5070876781][Xi Chen]], [[https://openalex.org/A5002918131][Yurui Xue]], [[https://openalex.org/A5074134616][Yuliang Li]], Angewandte Chemie (Print). None(None)] 2024. https://doi.org/10.1002/ange.202318080 
     
The preparation of formic acid by direct reduction of carbon dioxide is an important basis for the future chemical industry and is of great significance. Due to the serious shortage of highly active and selective electrocatalysts leading to the development of direct reduction of carbon dioxide is limited. Herein the target catalysts with high CO2RR activity and selectivity were identified by integrating DFT calculations and high‐throughput screening and by using graphdiyne (GDY) supported metal oxides quantum dots (QDs) as the ideal model. It is theoretically predicted that GDY supported indium oxide QDs (i.e., InOx/GDY) is a new heterostructure electrocatalyst candidate with optimal CO2RR performance. The interfacial electronic strong interactions effectively regulate the surface charge distribution of QDs and affect the adsorption/desorption behavior of HCOO* intermediate during CO2RR to achieve highly efficient CO2 conversion. Based on the predicted composition and structure, we synthesized the advanced catalytic system, and demonstrates superior CO2‐to‐HCOOH conversion performance. The study presents an effective strategy for rational design of highly efficient heterostructure electrocatalysts to promote green chemical production.    

    

* Theoretical Prediction Leads to Synthesize GDY Supported InOx Quantum Dots for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393314720
:TOPICS: Gas Sensing Technology and Materials, Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202318080")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393314720"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393314720"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393314720"))][Get cited by]]

OpenAlex: https://openalex.org/W4393314720 (Open access: False)
    
[[https://openalex.org/A5042996042][Feng He]], [[https://openalex.org/A5070876781][Xi Chen]], [[https://openalex.org/A5002918131][Yurui Xue]], [[https://openalex.org/A5074134616][Yuliang Li]], Angewandte Chemie (International ed. Print). None(None)] 2024. https://doi.org/10.1002/anie.202318080 
     
The preparation of formic acid by direct reduction of carbon dioxide is an important basis for the future chemical industry and is of great significance. Due to the serious shortage of highly active and selective electrocatalysts leading to the development of direct reduction of carbon dioxide is limited. Herein the target catalysts with high CO2RR activity and selectivity were identified by integrating DFT calculations and high‐throughput screening and by using graphdiyne (GDY) supported metal oxides quantum dots (QDs) as the ideal model. It is theoretically predicted that GDY supported indium oxide QDs (i.e., InOx/GDY) is a new heterostructure electrocatalyst candidate with optimal CO2RR performance. The interfacial electronic strong interactions effectively regulate the surface charge distribution of QDs and affect the adsorption/desorption behavior of HCOO* intermediate during CO2RR to achieve highly efficient CO2 conversion. Based on the predicted composition and structure, we synthesized the advanced catalytic system, and demonstrates superior CO2‐to‐HCOOH conversion performance. The study presents an effective strategy for rational design of highly efficient heterostructure electrocatalysts to promote green chemical production.    

    

* Hydrogen in aviation: A simulation of demand, price dynamics, and CO2 emission reduction potentials  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393349720
:TOPICS: Aviation's Impact on Global Climate Change, Estimating Vehicle Fuel Consumption and Emissions, Air Traffic Management and Conflict Resolution
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.241")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393349720"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393349720"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393349720"))][Get cited by]]

OpenAlex: https://openalex.org/W4393349720 (Open access: True)
    
[[https://openalex.org/A5071692130][Katrin Oesingmann]], [[https://openalex.org/A5007740725][Wolfgang Grimme]], [[https://openalex.org/A5084292086][Janina Scheelhaase]], International journal of hydrogen energy. 64(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.241 
     
Aviation contributes to anthropogenic climate change by emitting both carbon dioxide (CO2) and non-CO2 emissions through the combustion of fossil fuels. One approach to reduce the climate impact of aviation is the use of hydrogen as an alternative fuel. Two distinct technological options are presently under consideration for the implementation of hydrogen in aviation: hydrogen fuel cell architectures and the direct combustion of hydrogen. In this study, a hydrogen demand model is developed that considers anticipated advancements in liquid hydrogen aircraft technologies, forecasted aviation demand, and aircraft startup and retirement cycles. The analysis indicates that global demand for liquid hydrogen in aviation could potentially reach 17 million tons by 2050, leading to a 9% reduction in CO2 emissions from global aviation. Thus, the total potential of hydrogen in aviation extends beyond this, considering that the total market share of hydrogen aircraft on suitable routes in the model is projected to be only 27% in 2050 due to aircraft retirement cycles. Additionally, it is shown, that achieving the potential demand for hydrogen in aviation depends on specific market prices. With anticipated declines in current production costs, hydrogen fuel costs would need to reach about 70 EUR/MWh by 2050 to fulfill full demand in aviation, assuming biofuels provide the cheapest option for decarbonization alongside hydrogen. If e-fuels are the sole option for decarbonization alongside hydrogen, which is the more probable scenario, the entire hydrogen demand potential in aviation would be satisfied according to this study's estimates at significantly higher hydrogen prices, approximately 180 EUR/MWh.    

    

* Experimental study and equilibrium analysis on thermal reduction of CO2 by CFB gasification  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393281964
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Biomass Pyrolysis and Conversion Technologies, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.joei.2024.101623")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393281964"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393281964"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393281964"))][Get cited by]]

OpenAlex: https://openalex.org/W4393281964 (Open access: False)
    
[[https://openalex.org/A5031668694][Siyuan Zhang]], [[https://openalex.org/A5034901029][Chen Liang]], [[https://openalex.org/A5071030446][Xiaofang Wang]], [[https://openalex.org/A5028228263][Zhengwang Zhu]], Journal of the Energy Institute (Print). None(None)] 2024. https://doi.org/10.1016/j.joei.2024.101623 
     
CO2 can be involved in the CFB gasification process as one of the gasifying agents and be reduced to CO. In this paper, the feasibility of using CFB gasification process to reduce CO2 was investigated by using a bench-scale CFB gasifier. The effect of gasifying agent parameters including the CO2 substitution for N2, the O2 concentration and O2/C were studied. The result of experiments was compared with the chemical equilibrium calculations. The experimental result shows that the reduction of CO2 can be realized in CFB gasification, and the yield of CO in O2/CO2 atmosphere is higher than that that in air atmosphere. When the O2 concentration is 30%, the CO2 conversion reached the maximum of 0.017 Nm3(CO2)/kg(coal). However, the conversion of CO2 is limited by temperature and char reactivity at higher CO2 concentration. The gradual increase in CO2 yield with increasing O2/C suggests that at approximate temperature, the increase in O2/C enhances the oxidation of C and CO. When O2/C is greater than 0.45, the gasification results reach equilibrium. Under other conditions, the gasification results differ from the chemical equilibrium significantly. This is due to the change in the dominant reaction of the gasification process from the combustion reactions to the Boudouard reaction.    

    

* Operando Studies for CO2/CO Reduction in Flow‐Based Devices  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393191149
:TOPICS: Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cnma.202400070")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393191149"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393191149"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393191149"))][Get cited by]]

OpenAlex: https://openalex.org/W4393191149 (Open access: True)
    
[[https://openalex.org/A5029202084][Zih‐Yi Lin]], [[https://openalex.org/A5061136455][Yu‐Chia Chang]], [[https://openalex.org/A5091632977][Yiyu Chen]], [[https://openalex.org/A5004296726][Yao Jane Hsu]], [[https://openalex.org/A5081952140][Kang-Lin Peng]], [[https://openalex.org/A5060265950][Sung‐Fu Hung]], ChemNanoMat (Weinheim). None(None)] 2024. https://doi.org/10.1002/cnma.202400070  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cnma.202400070][pdf]])
     
Electrocatalytic CO2 reduction reaction (CO2RR) conducted in a flow‐based device exhibits a substantial enhancement in Faradaic efficiency and catalytic current density compared to a conventional H‐type configuration. This highlights the distinct catalytic environment and behavior inherent in flow cells as opposed to H cells. To investigate the authentic properties of a catalyst within a flow‐based device, customized flow cells have been specifically devised for operando techniques during CO2RR and CORR, rather than resorting to an in‐situ three‐electrode H‐type configuration with its disparate catalytic environment and performance. This approach ensures a catalytic environment identical to that employed in electrochemical measurements. This review delineates the disparities between H‐type and flow‐based cells as well as the operando techniques tailored for flow‐based devices, including X‐ray absorption spectroscopy and Raman spectroscopy, preserving a consistent catalytic environment. It also compiles recent findings on copper‐based systems using operando flow‐based devices. The operando insights reveal a significant augmentation in catalytic current density, impacting both chemical properties and crystal structures. Furthermore, the observation of various catalytic intermediates enriches our comprehension. In essence, the application of operando techniques to flow‐based devices furnishes a comprehensive understanding of the catalytic behavior exhibited by diverse systems, propelling progress toward achieving Net Zero emissions.    

    

* Dynamics of bulk and surface oxide evolution in copper foams for electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393270447
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s42004-024-01151-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393270447"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393270447"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393270447"))][Get cited by]]

OpenAlex: https://openalex.org/W4393270447 (Open access: True)
    
[[https://openalex.org/A5018619642][Fan Yang]], [[https://openalex.org/A5033970065][Shan Jiang]], [[https://openalex.org/A5008232261][Si Liu]], [[https://openalex.org/A5014687937][Paul Beyer]], [[https://openalex.org/A5025002760][Stefan Mebs]], [[https://openalex.org/A5008932544][Michael Haumann]], [[https://openalex.org/A5031585159][Christina Roth]], [[https://openalex.org/A5054018303][Holger Dau]], Communications chemistry. 7(1)] 2024. https://doi.org/10.1038/s42004-024-01151-0  ([[https://www.nature.com/articles/s42004-024-01151-0.pdf][pdf]])
     
Abstract Oxide-derived copper (OD-Cu) materials exhibit extraordinary catalytic activities in the electrochemical carbon dioxide reduction reaction (CO 2 RR), which likely relates to non-metallic material constituents formed in transitions between the oxidized and the reduced material. In time-resolved operando experiment, we track the structural dynamics of copper oxide reduction and its re-formation separately in the bulk of the catalyst material and at its surface using X-ray absorption spectroscopy and surface-enhanced Raman spectroscopy. Surface-species transformations progress within seconds whereas the subsurface (bulk) processes unfold within minutes. Evidence is presented that electroreduction of OD-Cu foams results in kinetic trapping of subsurface (bulk) oxide species, especially for cycling between strongly oxidizing and reducing potentials. Specific reduction-oxidation protocols may optimize formation of bulk-oxide species and thereby catalytic properties. Together with the Raman-detected surface-adsorbed *OH and C-containing species, the oxide species could collectively facilitate *CO adsorption, resulting an enhanced selectivity towards valuable C 2+ products during CO 2 RR.    

    

* Synthesis of complexes inspired from formate dehydrogenases : Application to the homogeneous catalysis of CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393355905
:TOPICS: Enzyme Immobilization Techniques, Electrochemical Reduction of CO2 to Fuels, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2018-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393355905"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393355905"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393355905"))][Get cited by]]

OpenAlex: https://openalex.org/W4393355905 (Open access: True)
    
[[https://openalex.org/A5070461684][Thibault Fogeron]], HAL (Le Centre pour la Communication Scientifique Directe). None(None)] 2018. None  ([[https://tel.archives-ouvertes.fr/tel-02922949/document][pdf]])
     
No abstract    

    

* Structure Sensitivity and Catalyst Restructuring for CO2 Electro-reduction on Copper  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393200362
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions, Electrochemical Reduction in Molten Salts
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-z3dlp")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393200362"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393200362"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393200362"))][Get cited by]]

OpenAlex: https://openalex.org/W4393200362 (Open access: True)
    
[[https://openalex.org/A5028424510][Dongfang Cheng]], [[https://openalex.org/A5057527246][Khanh‐Ly C. Nguyen]], [[https://openalex.org/A5027458673][Vaidish Sumaria]], [[https://openalex.org/A5069720141][Ziyang Wei]], [[https://openalex.org/A5004503548][Zisheng Zhang]], [[https://openalex.org/A5094018472][Winston Gee]], [[https://openalex.org/A5067025277][Yichen Li]], [[https://openalex.org/A5074179289][Carlos G. Morales‐Guio]], [[https://openalex.org/A5010534105][Markus Heyde]], [[https://openalex.org/A5065326930][Beatriz Roldán Cuenya]], [[https://openalex.org/A5000151397][Anastassia N. Alexandrova]], [[https://openalex.org/A5025258970][Philippe Sautet]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-z3dlp  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65fa4d0ce9ebbb4db911a0ef/original/structure-sensitivity-and-catalyst-restructuring-for-co2-electro-reduction-on-copper.pdf][pdf]])
     
Cu is the most promising metal catalyst for CO2 electroreduction (CO2RR) to multi-carbon products, but the structure sensitivity of the reaction and the stability versus restructuring of the catalyst surface under reaction conditions are still controversial. Here, atomic scale simulations of surface energies and reaction pathway kinetics supported by experimental evidence unveil that CO2RR does not take place on perfect planar Cu(111) and Cu(100) surfaces but rather on steps or kinks defects, and that these planar surfaces tend to restructure in reaction conditions to the active stepped surfaces. By combining basin hopping global sampling and grand canonical density functional theory, we show that the extremely low CO coverage on (111) and (100) surfaces, originating from sluggish CO2 conversion and unfavorable CO binding, limits the ability of these surfaces to reduce CO2 to multi-carbon products. Steps and kinks at surfaces, despite the lack of decrease in C-C coupling barriers on these sites, exhibit a significant increase in activity arising from beneficial CO2 activation and higher CO coverage. Notably, the square motifs adjacent to defects, not the defects themselves, are the active sites for CO2RR via synergistic effect. In addition, the strong binding of CO on defective sites acts as a thermodynamic driving force for the restructuring of planar surfaces to active stepped terminations under reactive conditions. We evaluate these mechanisms against experiments of CO2RR on UHV-prepared ultraclean Cu surfaces. Overall, our findings highlight the structural sensitivity in steering CO2RR and elucidate the origin of in situ restructuring of Cu catalysts during the reaction. We furthermore feature that the active sites for CO2RR are created under reaction conditions.    

    

* Analysis of CO2 Emission Reduction in Aviation Using Mix of 2,4% Biofuel  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393343580
:TOPICS: Aviation's Impact on Global Climate Change, Estimating Vehicle Fuel Consumption and Emissions
:PUBLICATION_DATE: 2024-01-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.61306/icaneat.v1i1.203")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393343580"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393343580"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393343580"))][Get cited by]]

OpenAlex: https://openalex.org/W4393343580 (Open access: True)
    
[[https://openalex.org/A5008257511][Ratih Sekartadji]], [[https://openalex.org/A5022754181][Ali Musyafa]], [[https://openalex.org/A5064306483][Lalu Muhamad Jaelani]], [[https://openalex.org/A5043738862][Ervina Ahyudanari]], No host. 1(1)] 2024. https://doi.org/10.61306/icaneat.v1i1.203  ([[https://ejournal.icpa-banyuwangi.ac.id/index.php/icaneat/article/download/203/102][pdf]])
     
The activities of flight have an impact on the environment. Combustion from aircraft fuel produces chemical products that have been emitted from the high-speed aircraft engine. Aircraft engines produce emissions that are similar to other emissions resulting from fossil fuel combustion. The transportation sector include land and air transportation produced 22,4 % from all energy sector. To reduce aircraft emissions while maintaining healthy economic growth, the aviation sector needs to reduce the use of fossil jet fuel by using sustainable aviation fuel. The use of biofuel in airplanes does not completely replace the fuel we use today, but gradually starting with a mixture of 10 % or 20 %. Several European countries and China have used biofuels made from waste in each country. Likewise in Indonesia, Pertamina collaborates with ITB, producing aircraft fuel from palm oil. The flight test using a Garuda Boeing 737 aircraft was successful using a mixture of 2.4% biofuel in October 2023. The CO2 emission estimation calculations at three large airports in Indonesia, Soekarno-Hatta International Airport Jakarta, Juanda International Airport Surabaya and Sultan Hasanuddin International Airport Makassar that using aviation fuel and a mix of aviation fuel with 2.4 % biofuel, reduce by 2.83 % - 2.95 %.    

    

* Indoor CO2 capture-driven passive cooling for photovoltaics with ventilation energy reduction utilizing amine-functionalized adsorbents  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393332891
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Refrigeration Systems and Technologies, Thermochemical Energy Storage and Sorption Technologies
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.enconman.2024.118351")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393332891"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393332891"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393332891"))][Get cited by]]

OpenAlex: https://openalex.org/W4393332891 (Open access: False)
    
[[https://openalex.org/A5038447144][Seonggon Kim]], [[https://openalex.org/A5014774941][Minjae Kim]], [[https://openalex.org/A5001522933][Kwangjin Jang]], [[https://openalex.org/A5008016189][Sam S. Yoon]], [[https://openalex.org/A5024370138][Wonjoon Choi]], [[https://openalex.org/A5067695971][Hoseong Lee]], [[https://openalex.org/A5001838991][Joon Hyung Shim]], [[https://openalex.org/A5016749808][Yong Tae Kang]], Energy conversion and management. 307(None)] 2024. https://doi.org/10.1016/j.enconman.2024.118351 
     
In carbon capture, utilization, and storage processes, CO2 capture consumes 80 % of total energy consumption, reaching 3–8 MJ/kg which poses a formidable challenge. Conversely, buildings are responsible for approximately 40 % of final energy consumption and contribute over 30 % of CO2 emissions, highlighting the urgent need to reduce the building energy. In this work, a sustainable indoor CO2 capture-driven passive cooling system is developed for building-integrated photovoltaics with ventilation energy reduction by coating amine-impregnated mesoporous silica (PEI/MCM-41) to the rear of PV cells using supersonic cold spraying method. During nighttime, it effectively mitigates indoor CO2 concentration increase due to human respiration by capturing 1.64 mmol/g of CO2, enabling a reduction of 180 MJ/kg-thermal in winter and 30.4 MJ/kg-electric in summer within the building. In daylight hours, PV cells generate electricity, and the supplied radiant solar heat is consumed for CO2 desorption (latent cooling), lowering the average temperature of the PV cells and improving the power efficiency. PEI/MCM-41 achieves a remarkable cooling energy density of 242 J/g and average cooling power of 357 W/m2. It has been demonstrated that the present system can simultaneously reduce the building energy consumption and CO2 emission.    

    

* Development of Mn/Cu Bi-metallic MOF for electrochemical CO2 reduction into valuable products  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393192117
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10008-024-05859-w")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393192117"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393192117"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393192117"))][Get cited by]]

OpenAlex: https://openalex.org/W4393192117 (Open access: False)
    
[[https://openalex.org/A5039128929][Usman Raza]], [[https://openalex.org/A5023469241][Naseem Iqbal]], [[https://openalex.org/A5045593961][Tayyaba Nооr]], [[https://openalex.org/A5069766766][Awais Ahmad]], Journal of solid state electrochemistry (Print). None(None)] 2024. https://doi.org/10.1007/s10008-024-05859-w 
     
No abstract    

    

* Hydrogen‐Bonded Organic Framework Supporting Atomic Bi−N2O2 Sites for High‐Efficiency Electrocatalytic CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393192087
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202404015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393192087"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393192087"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393192087"))][Get cited by]]

OpenAlex: https://openalex.org/W4393192087 (Open access: False)
    
[[https://openalex.org/A5032529955][Changli Wang]], [[https://openalex.org/A5068532993][Zengtao Lv]], [[https://openalex.org/A5046249498][Yarong Liu]], [[https://openalex.org/A5081675173][Rui Li]], [[https://openalex.org/A5046175815][Chia‐Chung Sun]], [[https://openalex.org/A5039851264][Jinming Wang]], [[https://openalex.org/A5075837486][Liuhua Li]], [[https://openalex.org/A5069182588][Xiangjian Liu]], [[https://openalex.org/A5051932876][Xiao Feng]], [[https://openalex.org/A5064928999][Wenxiu Yang]], [[https://openalex.org/A5056168495][Bo Wang]], Angewandte Chemie (International ed. Print). None(None)] 2024. https://doi.org/10.1002/anie.202404015 
     
Single atomic catalysts (SACs) offer a superior platform for studying the structure‐activity relationships during electrocatalytic CO2 reduction reaction (CO2RR). Yet challenges still exist to obtain well‐defined and novel site configuration owing to the uncertainty of functional framework‐derived SACs through calcination. Herein, a novel Bi−N2O2 site supported on the (1 1 0) plane of hydrogen‐bonded organic framework (HOF) is reported directly for CO2RR. In flow cell, the target catalyst Bi1‐HOF maintains a faradaic efficiency (FE) HCOOH of over 90% at a wide potential window of 1.4 V. The corresponding partial current density ranges from 113.3 to 747.0 mA cm−2. And, Bi1‐HOF exhibits a long‐term stability of over 30 h under a successive potential‐step test with a current density of 100~400 mA cm−2. Density function theory (DFT) calculations illustrate that the novel Bi−N2O2 site supported on the (1 1 0) plane of HOF effectively induces the oriented electron transfer from Bi center to CO2 molecule, reaching an enhanced CO2 activation and reduction. Besides, this study offers a versatile method to reach series of M−N2O2 sites with regulable metal centers via the same intercalation mechanism, broadening the platform for studying the structure‐activity relationships during CO2RR.    

    

* Hydrogen‐Bonded Organic Framework Supporting Atomic Bi−N2O2 Sites for High‐Efficiency Electrocatalytic CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393200334
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202404015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393200334"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393200334"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393200334"))][Get cited by]]

OpenAlex: https://openalex.org/W4393200334 (Open access: False)
    
[[https://openalex.org/A5032529955][Changli Wang]], [[https://openalex.org/A5068532993][Zengtao Lv]], [[https://openalex.org/A5046249498][Yarong Liu]], [[https://openalex.org/A5081675173][Rui Li]], [[https://openalex.org/A5046175815][Chia‐Chung Sun]], [[https://openalex.org/A5039851264][Jinming Wang]], [[https://openalex.org/A5075837486][Liuhua Li]], [[https://openalex.org/A5069182588][Xiangjian Liu]], [[https://openalex.org/A5051932876][Xiao Feng]], [[https://openalex.org/A5064928999][Wenxiu Yang]], [[https://openalex.org/A5024893590][Bo Wang]], Angewandte Chemie (Print). None(None)] 2024. https://doi.org/10.1002/ange.202404015 
     
Single atomic catalysts (SACs) offer a superior platform for studying the structure‐activity relationships during electrocatalytic CO2 reduction reaction (CO2RR). Yet challenges still exist to obtain well‐defined and novel site configuration owing to the uncertainty of functional framework‐derived SACs through calcination. Herein, a novel Bi−N2O2 site supported on the (1 1 0) plane of hydrogen‐bonded organic framework (HOF) is reported directly for CO2RR. In flow cell, the target catalyst Bi1‐HOF maintains a faradaic efficiency (FE) HCOOH of over 90% at a wide potential window of 1.4 V. The corresponding partial current density ranges from 113.3 to 747.0 mA cm−2. And, Bi1‐HOF exhibits a long‐term stability of over 30 h under a successive potential‐step test with a current density of 100~400 mA cm−2. Density function theory (DFT) calculations illustrate that the novel Bi−N2O2 site supported on the (1 1 0) plane of HOF effectively induces the oriented electron transfer from Bi center to CO2 molecule, reaching an enhanced CO2 activation and reduction. Besides, this study offers a versatile method to reach series of M−N2O2 sites with regulable metal centers via the same intercalation mechanism, broadening the platform for studying the structure‐activity relationships during CO2RR.    

    

* Photothermal-driven CO2 reduction over Nd2O3/TiO2 heterojunction catalysts in aqueous medium  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393216610
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.114078")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393216610"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393216610"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393216610"))][Get cited by]]

OpenAlex: https://openalex.org/W4393216610 (Open access: False)
    
[[https://openalex.org/A5012887882][Si-Meng Zhang]], [[https://openalex.org/A5090737269][Zhen‐Hong He]], [[https://openalex.org/A5040604862][Jiaojiao Shi]], [[https://openalex.org/A5076886276][Sen-Wang Wang]], [[https://openalex.org/A5044887427][Jiajie Liu]], [[https://openalex.org/A5052596733][Kuan Wang]], [[https://openalex.org/A5040760076][Weitao Wang]], [[https://openalex.org/A5088420709][Gang Yang]], [[https://openalex.org/A5012328539][Huan Wang]], [[https://openalex.org/A5027821063][Zhao‐Tie Liu]], Molecular catalysis (Online). 559(None)] 2024. https://doi.org/10.1016/j.mcat.2024.114078 
     
No abstract    

    

* Photoelectrothermocatalytic reduction of CO2 to glycol via Cu2S/MoS2-Vs octahedral heterostructure with synergistic mechanism  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393230090
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393230090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393230090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393230090"))][Get cited by]]

OpenAlex: https://openalex.org/W4393230090 (Open access: False)
    
[[https://openalex.org/A5022472965][Youzhi Cao]], [[https://openalex.org/A5016501540][Changwan Zhuang]], [[https://openalex.org/A5025867093][Bing wang]], [[https://openalex.org/A5031990549][Jianhua Wang]], [[https://openalex.org/A5030458072][Si Chen]], [[https://openalex.org/A5074786130][Qiaolan Zhang]], [[https://openalex.org/A5028592088][Weichun Ye]], [[https://openalex.org/A5053792317][Huanwang Jing]], Journal of colloid and interface science (Print). None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.172 
     
No abstract    

    

* A freestanding rotating triboelectric nanogenerator with large area and high efficiency for triboelectric plasma CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393256267
:TOPICS: Wearable Nanogenerator Technology, Materials for Electrochemical Supercapacitors, Conducting Polymer Research
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150798")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393256267"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393256267"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393256267"))][Get cited by]]

OpenAlex: https://openalex.org/W4393256267 (Open access: False)
    
[[https://openalex.org/A5027405294][Hongjie Cao]], [[https://openalex.org/A5082758354][Qinglong Ru]], [[https://openalex.org/A5075694868][Dongyang Fang]], [[https://openalex.org/A5091022894][Sumin Li]], [[https://openalex.org/A5072698553][Nannan Liu]], [[https://openalex.org/A5062770272][Jian Wei]], [[https://openalex.org/A5005885008][Hui Huang]], [[https://openalex.org/A5057856773][Yanting Yang]], [[https://openalex.org/A5065700798][Guangqin Gu]], [[https://openalex.org/A5042012998][Zhenan Bao]], [[https://openalex.org/A5058038850][Gang Cheng]], [[https://openalex.org/A5005104147][Sanjun Yang]], [[https://openalex.org/A5026428761][Shaoning Pang]], [[https://openalex.org/A5000145759][Zongliang Du]], Chemical engineering journal (1996. Print). None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150798 
     
No abstract    

    

* A Causal Analysis of CO2 Reduction Strategies in Electricity Markets
  Through Machine Learning-Driven Metalearners  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4393212279
:TOPICS: Economic Impact of Environmental Policies and Resources, Models and Dynamics of Technology Diffusion, Energy Efficiency in Manufacturing and Industry Sector
:PUBLICATION_DATE: 2024-03-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2403.15499")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393212279"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393212279"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393212279"))][Get cited by]]

OpenAlex: https://openalex.org/W4393212279 (Open access: True)
    
[[https://openalex.org/A5063990360][Iman Emtiazi Naeini]], [[https://openalex.org/A5071032032][Zahra Saberi]], [[https://openalex.org/A5089188577][Khadijeh Hassanzadeh]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2403.15499  ([[https://arxiv.org/pdf/2403.15499][pdf]])
     
This study employs the Causal Machine Learning (CausalML) statistical method to analyze the influence of electricity pricing policies on carbon dioxide (CO2) levels in the household sector. Investigating the causality between potential outcomes and treatment effects, where changes in pricing policies are the treatment, our analysis challenges the conventional wisdom surrounding incentive-based electricity pricing. The study's findings suggest that adopting such policies may inadvertently increase CO2 intensity. Additionally, we integrate a machine learning-based meta-algorithm, reflecting a contemporary statistical approach, to enhance the depth of our causal analysis. The study conducts a comparative analysis of learners X, T, S, and R to ascertain the optimal methods based on the defined question's specified goals and contextual nuances. This research contributes valuable insights to the ongoing dialogue on sustainable development practices, emphasizing the importance of considering unintended consequences in policy formulation.    

    
