#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Sun Sep 29 01:26:05 2024

Found 5 results from 2024-09-22 to 2024-09-29
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Pengaruh Modifikasi Permukaan Piston terhadap Emisi Gas Buang Motor Bakar Kapasitas 100 cc  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402788974
:TOPICS: Principles of Production Management and Operations
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.55606/jtmei.v3i3.4108")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402788974"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402788974"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402788974"))][Get cited by]]

OpenAlex: https://openalex.org/W4402788974 (Open access: False)
    
[[https://openalex.org/A5107476802][Gennarki Dini Setyawan Putra]], [[https://openalex.org/A5021716770][Khambali Khambali]], JURNAL TEKNIK MESIN INDUSTRI ELEKTRO DAN INFORMATIKA. 3(3)] 2024. https://doi.org/10.55606/jtmei.v3i3.4108 
     
Technological advances in motorized transportation are progressing rapidly, making motorized vehicles the main mode of transportation. The increasing number of motorized vehicles in society results in a significant increase in exhaust emissions. Combustion in vehicle engines is not always perfect, producing exhaust gases containing compounds harmful to human health, such as carbon monoxide (CO), hydrocarbons (HC), carbon dioxide (CO2), and nitrogen oxides (NOx). This study investigates the effect of variations in piston dome shape on exhaust emissions in a 100cc internal combustion engine using RON 90 fuel. The goal is to find the optimal compression ratio to produce cleaner exhaust emissions. The research data are presented in tabular form and analyzed using one-way ANOVA and graphs. The results showed a significant reduction in CO and HC emissions at all engine speeds (1000, 2000, 4000, and 5000 rpm) with variations in piston dome shape. The reduction in CO emissions ranged from 55.07% to 85.73%, while the reduction in HC emissions ranged from 54.14% to 86.10%. These results suggest that variations in piston dome shape can be an effective solution to minimize harmful exhaust emissions in internal combustion engines.    

    

* The Geochemical imaging Technique for CO2 Monitoring in the Saline Aquifer of Krechba Field Algeria  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402752359
:TOPICS: Carbon Dioxide Sequestration in Geological Formations, Characterization of Shale Gas Pore Structure, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-5122014/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402752359"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402752359"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402752359"))][Get cited by]]

OpenAlex: https://openalex.org/W4402752359 (Open access: False)
    
[[https://openalex.org/A5009394185][Zeboudj Fayçal]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-5122014/v1 
     
Abstract As part of the reduction and elimination of anthropogenic emissions, carbon capture, and storage (CCS) has been applied in recent decades. One option for reducing greenhouse gas emissions GHG is to store carbon dioxide CO2 in deep saline aquifers. Due to their abundance and large capacity, deep saline aquifers make excellent storage sites due to their potential for long-term sequestration. In early 2006, in Salah Gas Krechba field in Algeria became the world's first onshore saline aquifer to begin sequestration. This paper will focus on new insights into surface CO2 monitoring. We will discuss the introduction of geochemical imaging as an emerging surface technique to monitor CO2, recently adopted to investigate and detect tracer gases leaks injected in 2007 from neighboring wells and the cap rock. In the following few pages, we will summarize the geochemical imaging survey process from the implementation design, samples signature measurement to chemical analysis using the sophisticated statistical geo-chemical methods in the final interpretation stage. As a conclusion, the comprehensive analysis of the geochemical data has allowed the Krechba team to investigate the CO2 leakage areas in the field and demonstrates to be an efficient valuable, and accurate method for CO2 monitoring    

    

* The Impact of Economic Factors on Changing Carbon Emission Landscape in ASEAN With ARDL Approach  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402849537
:TOPICS: Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.24002/kinerja.v28i2.8583")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402849537"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402849537"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402849537"))][Get cited by]]

OpenAlex: https://openalex.org/W4402849537 (Open access: True)
    
[[https://openalex.org/A5003264851][Hasbi Hasbi]], KINERJA. 28(2)] 2024. https://doi.org/10.24002/kinerja.v28i2.8583 
     
This study aims to analyze the factors influencing carbon emissions in the member countries of the Association of Southeast Asian Nations (ASEAN). The data used in this study covers the period from 1990 to 2021, utilizing the Autoregressive Distributed Lag (ARDL) analysis method. All independent variables show a significant impact on carbon emissions in both the short and long term. This research provides evidence that factors such as urbanization, foreign direct investment, population, and economic growth significantly contribute to the increase in carbon emissions in ASEAN countries. The findings also validate the Environmental Kuznets Curve hypothesis for carbon emissions in ASEAN countries. In other words, economic growth leads to a reduction in carbon emissions. The ASEAN region has experienced substantial economic growth over the past few decades. However, carbon dioxide (CO2) remains a socio-economic issue in the ASEAN region. The results of this study can be highly beneficial for policymakers in the region regarding sustainability and economic development.    

    

* Experimental investigation of emissions from a single-cylinder diesel engine using methanol–diesel blends  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402722556
:TOPICS: Catalytic Nanomaterials, Chemical Kinetics of Combustion Processes, Technical Aspects of Biodiesel Production
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/fenrg.2024.1449652")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402722556"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402722556"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402722556"))][Get cited by]]

OpenAlex: https://openalex.org/W4402722556 (Open access: True)
    
[[https://openalex.org/A5099589609][Mohammed Qays Kadhim]], [[https://openalex.org/A5024861937][P. P. Oshchepkov]], Frontiers in Energy Research. 12(None)] 2024. https://doi.org/10.3389/fenrg.2024.1449652 
     
This study examines the effects of methanol–diesel blends on the emissions of a diesel engine, concentrating on carbon monoxide (CO), carbon dioxide (CO 2 ), nitrogen oxides (NOx), hydrocarbons (HCs), and particulate matter (PM). Using a single-cylinder four-stroke diesel engine at varying torque settings (2 N m–6 N m), significant reductions in CO, CO 2 , HC, and PM emissions were observed with increasing methanol content. CO emissions reduced by up to 81.8%, CO 2 by up to 64.2%, HC by up to 80.4%, and PM by up to 23.5% with the MD11 blend. NOx emissions initially increased but decreased by up to 20% at higher torques with the same blend. These results highlight the environmental benefits of methanol–diesel blends and the need for effective NOx reduction strategies.    

    

* Role of Green Building Materials in Reducing Environmental and Human Health Impacts Using VIKOR Method  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402788835
:TOPICS: Comprehensive Survey of Big Data Mining Approaches, Applications and Challenges of IoT, Smart Systems and IoT Applications
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.46632/tfe/2/3/1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402788835"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402788835"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402788835"))][Get cited by]]

OpenAlex: https://openalex.org/W4402788835 (Open access: False)
    
, Trends in Finance and Economics. 2(3)] 2024. https://doi.org/10.46632/tfe/2/3/1 
     
Green Building Materials (GBMs) are construction materials Green building materials (GBMs), sustainable building practices, resource conservation, energy efficiency, indoor air quality, environmental impact reduction, and renewable and recyclable materials. The drive to adopt GBMs is fueled by the need to reduce energy consumption, cut greenhouse gas emissions, and preserve natural resources. By incorporating renewable, recyclable, and non-toxic elements, GBMs are integral to sustainable building practices, ensuring a balance between development and environmental responsibility. Growing awareness of environmental challenges and the emphasis on sustainable development have made green building materials a central focus in contemporary construction. Environmental Impact Reduction: GBMs help decrease the environmental footprint of construction by cutting waste, cutting greenhouse gas emissions, and using less energy. These minerals are essential for maintaining ecosystems and halting climate change. Health & Well-Being: Research on GBMs makes it easier to create materials that improve indoor air quality and reduce exposure to dangerous pollutants, which benefits building occupants' comfort and health. Resource Conservation: This study promotes the use of recyclable and renewable materials, helping to preserve the planet's finite natural resources and encouraging the building sector to implement circular economy principles. Alternatives taken as Bamboo, Recycled Steel, Cork, Rammed Earth, Hempcrete, Straw Bale. Evaluation Parameters taken as Thermal Insulation (Benefit), Sustainability Score (Benefit), Cost per Square Meter (Non-Benefit), CO2 Emissions during Production (Non-Benefit). The results indicate that Recycled Steel achieved the highest rank, while Straw Bale had the lowest rank being attained. “The value of the dataset for Green Building Materials, according to the VIKOR, Recycled Steel achieves the highest ranking.”    

    
