#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Sun Jun 16 01:13:46 2024

Found 72 results from 2024-06-09 to 2024-06-16
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Universal Formation of Single Atoms from Molten Salt for Facilitating Selective CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399476800
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202406380")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399476800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399476800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399476800"))][Get cited by]]

OpenAlex: https://openalex.org/W4399476800 (Open access: False)
    
[[https://openalex.org/A5066468525][Hao Qi]], [[https://openalex.org/A5075596275][Cheng Zhang]], [[https://openalex.org/A5018523807][Tao Qi]], [[https://openalex.org/A5019530155][Jiazhi Wang]], [[https://openalex.org/A5063955135][Peiyu Ma]], [[https://openalex.org/A5026592308][Jialing Wu]], [[https://openalex.org/A5028432371][Tianyang Wang]], [[https://openalex.org/A5082528284][Dongxue Liu]], [[https://openalex.org/A5079180248][Linxuan Xie]], [[https://openalex.org/A5039967716][Xiao Liu]], [[https://openalex.org/A5003306574][Minghong Gu]], [[https://openalex.org/A5078307783][Michael R. Hoffmann]], [[https://openalex.org/A5035770052][Gang Yu]], [[https://openalex.org/A5027938056][Kai Liu]], [[https://openalex.org/A5036668774][Jun Lü]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202406380 
     
Abstract Clarifying the formation mechanism of single‐atom sites guides the design of emerging single‐atom catalysts (SACs) and facilitates the identification of the active sites at atomic scale. Herein, we develop a molten‐salt atomization strategy for synthesizing zinc (Zn) SACs with temperature universality from 400 to 1000/1100 °C and an evolved coordination from Zn‐N 2 Cl 2 to Zn‐N 4 . The electrochemical tests and in‐situ attenuated total reflectance‐surface‐enhanced infrared absorption spectroscopy confirm that the Zn‐N 4 atomic sites are active for electrochemical carbon dioxide (CO 2 ) conversion to carbon monoxide (CO). In a strongly acidic medium (0.2 M K 2 SO 4 , pH°=°1), the Zn SAC formed at 1000 °C (Zn 1 NC) containing Zn‐N 4 sites enables highly selective CO 2 electroreduction to CO, with nearly 100% selectivity toward CO product in a wide current density range of 100 to 600 mA cm −2 . During a 50‐h continuous electrolysis at the industrial current density of 200 mA cm −2 , Zn 1 NC achieves Faradaic efficiencies greater than 95% for CO product. Our work presents a temperature‐universal formation of single‐atom sites, which provides a novel platform for unraveling the active sites in Zn SACs for CO 2 electroreduction and extends the synthesis of SACs with controllable coordination sites. This article is protected by copyright. All rights reserved    

    

* Visible-Light-Driven Carbon Dioxide Reduction Catalyzed by Iron Schiff-Base Complexes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399524109
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01639")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399524109"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399524109"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399524109"))][Get cited by]]

OpenAlex: https://openalex.org/W4399524109 (Open access: False)
    
[[https://openalex.org/A5098704577][Iulia Cocosila]], [[https://openalex.org/A5086372340][Albert Solé‐Daura]], [[https://openalex.org/A5001485043][Philipp Gotico]], [[https://openalex.org/A5015346820][Jérémy Forté]], [[https://openalex.org/A5015561102][Yun Li]], [[https://openalex.org/A5062221634][Marc Fontecave]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01639 
     
No abstract    

    

* Study of Ni-Co-ZrO2/Al2O3 Catalysts for Carbon Dioxide Reforming of Methane at Low CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399551383
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-05-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48048/tis.2024.7788")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399551383"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399551383"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399551383"))][Get cited by]]

OpenAlex: https://openalex.org/W4399551383 (Open access: False)
    
[[https://openalex.org/A5083050561][Tanakorn Ratana]], [[https://openalex.org/A5099095789][Lucksamon Thongdee]], [[https://openalex.org/A5099095790][Sittichart Sawansombut]], [[https://openalex.org/A5068362602][Wassachol Sumarasingha]], [[https://openalex.org/A5099095791][Threeraphat Chutimaskul]], [[https://openalex.org/A5005712519][Monrudee Phongaksorn]], Trends in Sciences. 21(7)] 2024. https://doi.org/10.48048/tis.2024.7788 
     
This work studied the composition of Ni-Co-ZrO2/Al2O3 catalyst on properties and efficiency of catalysts for carbon dioxide reforming of methane (CMR) when CO2 was fed as the limiting reagent and CH4 as the excess reactant. 9wt%Ni-1wt%ZrO2/Al2O3, 4.5wt%Ni-4.5%wtCo-1wt%ZrO2/Al2O3, 9wt%Co-1wt%ZrO2/Al2O3 and 7wt%Co-3wt%ZrO2/Al2O3 catalysts were prepared by wet impregnation method. The physicochemical properties of present catalysts were characterized by XRD, N2 adsorption-desorption H2-TPR and CO2-TPD. The CRM performance was determined in a tubular fixed-bed reactor at 600 °C for 6 h with limiting of carbon dioxide. The carbon deposition on spent catalysts were examined by TGA. The results showed that Co-ZrO2 catalysts provided greater activities, selectivity toward H2 and stability than Ni-ZrO2 and Ni-Co-ZrO2 catalysts. 9wt%Co-1wt%ZrO2/Al2O3 provided higher reactant conversions and H2/CO ratio than 7wt%Co-3wt%ZrO2/Al2O3 while the minimum coke formation was observed on spent 7wt%Co-3wt%ZrO2/Al2O3. It is because oxophilic properties and oxygen vacancy sites in Co-ZrO2 increase CO2 dissociative adsorption as well as oxygen transport on the catalyst surface. HIGHLIGHTS This work developed Ni-Co-ZrO2/Al2O3 catalysts for carbon dioxide reforming of methane (CMR) when CO2 is fed as the limiting reagent demonstrated petroleum refinery application. Remarkable points of this work are revealed below. Co-ZrO2 catalysts provided greater reactant activities, selectivity toward H2 and stability than Ni-ZrO2 and Ni-Co-ZrO2 The oxophilic property accompanied with oxygen vacancy sites in Co-ZrO2 increase CO2 dissociative absorption and oxygen transport on the catalyst surface. 9wt%Co-1wt%ZrO2/Al2O3 provided relative highest reactant conversions and highest H2/CO ratio. 7wt%Co-3wt%ZrO2/Al2O3 presented the minimum coke formation. GRAPHICAL ABSTRACT    

    

* Research of Carbon Dioxide Reduction in New Energy Applications  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399615969
:TOPICS: Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54097/21b5jn25")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399615969"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399615969"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399615969"))][Get cited by]]

OpenAlex: https://openalex.org/W4399615969 (Open access: False)
    
[[https://openalex.org/A5077038811][Yuzhou Zhao]], Highlights in science, engineering and technology. 83(None)] 2024. https://doi.org/10.54097/21b5jn25 
     
Carbon dioxide is a significant byproduct from the usage of fossil fuels. Due to the rapid development of industry and the swift growth of urban populations, carbon dioxide has been accumulating in large quantities over the past decades. In terms of new energy research, carbon dioxide reduction has been given significant attention due to its non-toxic nature and the high utility of the products from its reduction. Electrochemical reduction, in particularly, has been highlighted for its notable benefits. This paper introduces the mechanism of electrochemical carbon dioxide reduction, its current shortcomings, and methods of improvement, summarizing the recent deficiencies and advancements in electrochemical carbon dioxide reduction. The current belief is that refining the electrolytes like ionic liquids and using catalysts such as graphene and its derivatives can enhance the electrochemical reduction of carbon dioxide. This paper looks forward to research findings that will discover better electrolytes and catalysts to address the current deficiencies in carbon dioxide reduction and hopes to promote the full potential of electrochemical carbon dioxide reduction in future new energy applications.    

    

* Research Progress in Photo functional Materials for Catalytic Carbon Dioxide Reduction Reactions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399655076
:TOPICS: Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54097/q9zcxs49")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399655076"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399655076"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399655076"))][Get cited by]]

OpenAlex: https://openalex.org/W4399655076 (Open access: False)
    
[[https://openalex.org/A5062651272][Zhixiang Chang]], Highlights in science, engineering and technology. 83(None)] 2024. https://doi.org/10.54097/q9zcxs49 
     
Since the turn of the twenty-first century, the need to find new energy sources to create a low-carbon society has grown urgently due to the ongoing rise in greenhouse gas emissions, which are mostly caused by CO2. The technique that uses solar energy to convert CO2 into hydrocarbon fuels can produce high-value hydrocarbon fuels like methane, methanol, formic acid, or C2+. This is a promising method of achieving global carbon balance. One of the key elements influencing the process of photocatalytic CO2 reduction is the presence of materials having photocatalytic properties. Therefore, exploring and developing efficient photocatalytic functional materials is the main direction of research today. This article first introduces the development history of photo-functional materials and analyzes their mechanisms in photocatalytic reactions. Then, different types of optical functional materials were classified and introduced in detail. Finally, the development trend of photo-functional materials in the catalytic reduction of CO2 was emphasized.    

    

* Novel pyrochlore type europium stannate – tungsten disulfide heterostructure for light driven carbon dioxide reduction and nitrogen fixation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399509439
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.envres.2024.119372")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399509439"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399509439"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399509439"))][Get cited by]]

OpenAlex: https://openalex.org/W4399509439 (Open access: False)
    
[[https://openalex.org/A5028649909][K. Yogesh Kumar]], [[https://openalex.org/A5092034571][Fahd Alharethy]], [[https://openalex.org/A5092034571][Fahd Alharethy]], [[https://openalex.org/A5092034571][Fahd Alharethy]], [[https://openalex.org/A5092034571][Fahd Alharethy]], [[https://openalex.org/A5092034571][Fahd Alharethy]], [[https://openalex.org/A5014056343][L. Parashuram]], Environmental research. 257(None)] 2024. https://doi.org/10.1016/j.envres.2024.119372 
     
The reduction of carbon dioxide (CO    

    

* Local-strain-induced CO2 adsorption geometries and electrochemical reduction pathway shift  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399476049
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-06-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/nsr/nwae191")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399476049"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399476049"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399476049"))][Get cited by]]

OpenAlex: https://openalex.org/W4399476049 (Open access: True)
    
[[https://openalex.org/A5078952009][Chuhao Liu]], [[https://openalex.org/A5070181057][Yue Bu]], [[https://openalex.org/A5048798891][Yifei Xu]], [[https://openalex.org/A5070768020][Azhar Mahmood]], [[https://openalex.org/A5062343194][Jisheng Xie]], [[https://openalex.org/A5069515960][Yuan Fu]], [[https://openalex.org/A5042136634][Hengling Wei]], [[https://openalex.org/A5078198855][Pengfei Cheng]], [[https://openalex.org/A5082308749][Yongbo Wu]], [[https://openalex.org/A5075169323][Xiao Liang]], [[https://openalex.org/A5052216921][Ruilong Zong]], [[https://openalex.org/A5020721427][Wan‐Lu Li]], [[https://openalex.org/A5066474434][Jihan Zhou]], [[https://openalex.org/A5073687384][Bingjun Xu]], [[https://openalex.org/A5054584536][Li Niu]], [[https://openalex.org/A5001303987][Mufan Li]], National Science Review/National science review. None(None)] 2024. https://doi.org/10.1093/nsr/nwae191 
     
Abstract Unravelling the influence of strain and geometric effects on the electrochemical reduction of carbon dioxide (CO2RR) on Cu-based (or Pd-based) alloys remains challenging due to complex local microenvironment variables. Herein, we employ two PdCu alloys (nanoparticles and nanodendrites) to demonstrate how CO2RR selectivity can shift from CO to HCOO−. Despite sharing consistent phases, exposed crystal facets, and overall oxidative states, these alloys exhibit different local strain profiles due to their distinct geometries. By integrating experimental data, in-situ spectroscopy, and density functional theory calculations, we revealed that CO2 prefers adsorption on tensile-strained areas with carbon-side geometry, following a *COOH-to-CO pathway. Conversely, on some compressive-strained regions induced by the dendrites-like morphology, CO2 adopts an oxygen-side geometry, favouring an *OCHO-to-HCOO pathway due to the downshift of the d-band centre. Notably, our findings elucidate a dominant *OCHO-to-HCOO− pathway in catalysts when featuring both adsorption geometries. This research provides a comprehensive model for local environment of bimetallic alloys, and establishes a clear relationship between the CO2RR pathway shift and variation in local strain environments of PdCu alloys.    

    

* Automated Load and Dump Detection for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399543743
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Demand Response in Smart Grids
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5617/nmi.10535")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399543743"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399543743"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399543743"))][Get cited by]]

OpenAlex: https://openalex.org/W4399543743 (Open access: False)
    
[[https://openalex.org/A5099093105][Eleonora Piersanti]], [[https://openalex.org/A5099093106][Naeeme Danesh Moghaddam]], Nordic machine intelligence. 3(3)] 2024. https://doi.org/10.5617/nmi.10535 
     
In this paper, we detail our methodology for addressing the challenge of reducing CO2 emissions in road construction from construction machines in a Norwegian construction site. In particular, we focus on the automatic detection of load and dump locations from various data sources    

    

* S-Scheme Heterojunction Photocatalysts for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399572221
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14060374")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399572221"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399572221"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399572221"))][Get cited by]]

OpenAlex: https://openalex.org/W4399572221 (Open access: True)
    
[[https://openalex.org/A5024467762][Mingli Li]], [[https://openalex.org/A5069013809][Canfei He]], [[https://openalex.org/A5034128349][Yi Zhao]], [[https://openalex.org/A5077731514][Shunli Li]], [[https://openalex.org/A5032579515][Jiabo Wang]], [[https://openalex.org/A5091228890][Kai Ge]], [[https://openalex.org/A5066825255][Yongfang Yang]], Catalysts. 14(6)] 2024. https://doi.org/10.3390/catal14060374 
     
Photocatalytic technology, which is regarded as a green route to transform solar energy into chemical fuels, plays an important role in the fields of energy and environmental protection. An emerging S-scheme heterojunction with the tightly coupled interface, whose photocatalytic efficiency exceeds those of conventional type II and Z-scheme photocatalysts, has received much attention due to its rapid charge carrier separation and strong redox capacity. This review provides a systematic description of S-scheme heterojunction in the photocatalysis, including its development, reaction mechanisms, preparation, and characterization methods. In addition, S-scheme photocatalysts for CO2 reduction are described in detail by categorizing them as 0D/1D, 0D/2D, 0D/3D, 2D/2D, and 2D/3D. Finally, some defects of S-scheme heterojunctions are pointed out, and the future development of S-scheme heterojunctions is proposed.    

    

* Regulating CO2 adsorption and mass transfer in electrochemical bicarbonate reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399626057
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.joule.2024.05.015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399626057"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399626057"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399626057"))][Get cited by]]

OpenAlex: https://openalex.org/W4399626057 (Open access: False)
    
[[https://openalex.org/A5050550539][Tengfei Li]], Joule. None(None)] 2024. https://doi.org/10.1016/j.joule.2024.05.015 
     
No abstract    

    

* Progress and Perspective of Single-atom Catalysts for the Electrochemical CO2 Reduction Reaction for Fuels and Chemicals  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399654489
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54097/qxv1jb25")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399654489"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399654489"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399654489"))][Get cited by]]

OpenAlex: https://openalex.org/W4399654489 (Open access: False)
    
[[https://openalex.org/A5015439597][Bin Liu]], Highlights in science, engineering and technology. 83(None)] 2024. https://doi.org/10.54097/qxv1jb25 
     
Electrochemical CO2 Reduction Reaction (CO2RR) presents a transformative approach for the sustainable synthesis of fuels and chemicals to address pressing environmental challenges. The efficiency and selectivity of the CO2RR largely depend on the catalyst. Among which, Single-Atom Catalysts (SACs) have surfaced as a prominent design for this reaction, offering exceptional activity and selectivity. This paper delves into the progress and perspectives of SACs in CO2RR, tracing their historical evolution, unique advantages, and underlying mechanisms. The superior atomic utilization, distinct electronic configurations, and enhanced product specificity of SACs over traditional catalysts have opened novel pathways for more efficient conversion of CO2 to potent resources. However, challenges particularly concerning the stability, scalability, and product diversity of these catalysts constitutes as major impediments. Recent innovations, from advanced characterization techniques to novel synthesis methods, are spotlighted, showcasing the strides the scientific community has made. Looking forward, this paper underscores the potential of SACs in bridging sustainable energy sources with green chemical production and discuss prospective strategies to overcome existing limitations.    

    

* Bimetallic oxide electrocatalyst with interfacial structure for enhanced electrocatalytic CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399660382
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.175192")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399660382"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399660382"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399660382"))][Get cited by]]

OpenAlex: https://openalex.org/W4399660382 (Open access: False)
    
[[https://openalex.org/A5025864600][Luyao Wang]], [[https://openalex.org/A5022715872][Xinxin Xu]], [[https://openalex.org/A5077156040][Jiahui Wang]], [[https://openalex.org/A5009277601][Yanjun Xue]], [[https://openalex.org/A5013492103][Xinyu Wang]], [[https://openalex.org/A5029674464][Ming Ma]], [[https://openalex.org/A5004877274][Jian Tian]], [[https://openalex.org/A5081215511][Yingying Qin]], Journal of alloys and compounds. 1001(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.175192 
     
No abstract    

    

* Efficient Photoelectrocatalytic Co2 Reduction to Formate by Bivo4/Zif-8 Heterojunction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399552328
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4860624")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399552328"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399552328"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399552328"))][Get cited by]]

OpenAlex: https://openalex.org/W4399552328 (Open access: False)
    
[[https://openalex.org/A5037700967][Zhi Yang]], [[https://openalex.org/A5021087622][Huimin Yang]], [[https://openalex.org/A5027496978][Fanfan Gao]], [[https://openalex.org/A5038100088][Nan Cheng]], [[https://openalex.org/A5053453125][Rui Chen]], [[https://openalex.org/A5044544424][Yi Zhang]], [[https://openalex.org/A5016812043][Jiaqi Yang]], [[https://openalex.org/A5042225153][Xuemei Gao]], [[https://openalex.org/A5054817301][Yue Yuan]], [[https://openalex.org/A5059309459][Yuanjing Yang]], [[https://openalex.org/A5024592447][Yibo Jia]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4860624 
     
No abstract    

    

* Chromium Complexes with Benzanellated N‐heterocyclic Phosphenium Ligands – Synthesis, Reactivity and Application in Catalytic CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399525034
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202401714")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399525034"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399525034"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399525034"))][Get cited by]]

OpenAlex: https://openalex.org/W4399525034 (Open access: False)
    
[[https://openalex.org/A5060589805][Nicholas Birchall]], [[https://openalex.org/A5099087466][Fridolin Hennhöfer]], [[https://openalex.org/A5043452704][Martin Nieger]], [[https://openalex.org/A5091668895][Dietrich Gudat]], Chemistry. None(None)] 2024. https://doi.org/10.1002/chem.202401714 
     
A chromium complex carrying two benzanellated N‐heterocyclic phosphenium (bzNHP) ligands was prepared by a salt metathesis approach. Spectroscopic studies suggest that the anellation enhances the π‐acceptor ability of the NHP‐units, which is confirmed by the facile electrochemical reduction of the complex to a spectroscopically characterized radical anion. Co‐photolysis with H2 allowed extensive conversion into a σ‐H2‐complex, which shows a diverse reactivity towards donors and isomerizes under H–H bond fission and shift of a hydride to a P‐ligand. The product carrying phosphenium, phosphine and hydride ligands was also synthesized independently and reacts reversibly with CO and MeCN to yield bis‐phosphine complexes under concomitant Cr‐to‐P‐shift of a hydride. In contrast, CO2 was not only bound but reduced to give an isolable formato complex, which reacted with ammonia borane under partial recovery of the metal hydride and production of formate. Further elaboration of the reactions of the chromium complexes with CO2 and NH3BH3 allowed to demonstrate the feasibility of a Cr‐catalyzed transfer hydrogenation of CO2 to methanol. The various complexes described were characterized spectroscopically and in several cases by XRD studies. Further insights in reactivity patterns were provided through (spectro)electrochemical studies and DFT calculations.    

    

* Electrocatalytic reduction of CO2 to C2H4 by monometallic Cu4 cluster supported on CeO2(110) surface  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399466754
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.06.060")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399466754"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399466754"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399466754"))][Get cited by]]

OpenAlex: https://openalex.org/W4399466754 (Open access: False)
    
[[https://openalex.org/A5077153113][Ping Liu]], [[https://openalex.org/A5018580893][Zhu Hai-yan]], [[https://openalex.org/A5088073450][Baiyue Li]], [[https://openalex.org/A5072254497][Chen Wu]], [[https://openalex.org/A5050065678][Jia Shi]], [[https://openalex.org/A5008133679][Bingbing Suo]], [[https://openalex.org/A5086719383][Wenli Zou]], [[https://openalex.org/A5036891682][Yawei Li]], International journal of hydrogen energy. 73(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.06.060 
     
No abstract    

    

* Electrochemical reduction of CO2: A roadmap to formic and acetic acid synthesis for efficient hydrogen storage  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399665908
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.enconman.2024.118601")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399665908"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399665908"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399665908"))][Get cited by]]

OpenAlex: https://openalex.org/W4399665908 (Open access: True)
    
[[https://openalex.org/A5045279024][M. Orlić]], [[https://openalex.org/A5062871844][Christoph Hochenauer]], [[https://openalex.org/A5036651221][Rajesh Nagpal]], [[https://openalex.org/A5005389515][Vanja Subotić]], Energy conversion and management. 314(None)] 2024. https://doi.org/10.1016/j.enconman.2024.118601 
     
No abstract    

    

* Electro-reductive carboxylation of C Cl bonds in unactivated alkyl chlorides and polyvinyl chloride with CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399458567
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cclet.2024.110104")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399458567"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399458567"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399458567"))][Get cited by]]

OpenAlex: https://openalex.org/W4399458567 (Open access: False)
    
[[https://openalex.org/A5027475930][Li Li]], [[https://openalex.org/A5070179676][Zhang Yan]], [[https://openalex.org/A5016487582][Chuan‐Kun Ran]], [[https://openalex.org/A5012332972][Yi Liu]], [[https://openalex.org/A5082924617][Shuo Zhang]], [[https://openalex.org/A5038573469][Ting Gao]], [[https://openalex.org/A5073515488][Long‐Fei Dai]], [[https://openalex.org/A5028215675][Li‐Li Liao]], [[https://openalex.org/A5059599037][Jian‐Heng Ye]], [[https://openalex.org/A5016358859][Da‐Gang Yu]], Chinese Chemical Letters/Chinese chemical letters. None(None)] 2024. https://doi.org/10.1016/j.cclet.2024.110104 
     
No abstract    

    

* Efficient reduction of CO2 and inhibition of hydrogen precipitation by polymetallic oxalate photocatalysts modified with the metal Mn  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399533032
:TOPICS: Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nr00097h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399533032"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399533032"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399533032"))][Get cited by]]

OpenAlex: https://openalex.org/W4399533032 (Open access: False)
    
[[https://openalex.org/A5049295617][Guifeng Li]], [[https://openalex.org/A5005772570][Yuan Gu]], [[https://openalex.org/A5059625822][Rui Ren]], [[https://openalex.org/A5054306494][Sitan Li]], [[https://openalex.org/A5021605160][Huiping Zhu]], [[https://openalex.org/A5035514014][Dongmei Xue]], [[https://openalex.org/A5078727917][Xiangyi Kong]], [[https://openalex.org/A5067835739][Zhaoqiang Zheng]], [[https://openalex.org/A5070952300][Nuo Liu]], [[https://openalex.org/A5023494462][Bei Li]], [[https://openalex.org/A5084434322][Jiangwei Zhang]], Nanoscale. None(None)] 2024. https://doi.org/10.1039/d4nr00097h 
     
Photocatalytic reduction of CO2 to chemical fuels is attractive for solving both the greenhouse effect and the energy crisis, but the key challenge is to design and synthesize photocatalysts with...    

    

* Deciphering the role of aromatic cations in electrochemical CO2 reduction: interfacial ion assembly governs reaction pathways  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399529132
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta02903h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399529132"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399529132"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399529132"))][Get cited by]]

OpenAlex: https://openalex.org/W4399529132 (Open access: False)
    
[[https://openalex.org/A5023801260][Wenxiao Guo]], [[https://openalex.org/A5053624693][Beichen Liu]], [[https://openalex.org/A5084561647][S. Anderson]], [[https://openalex.org/A5050957143][S. Johnstone]], [[https://openalex.org/A5063200082][Matthew A. Gebbie]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta02903h 
     
The accumulation of ions at electrochemical interfaces governs the local chemical environment, which in turn determines the reaction pathways and rates of electrocatalytic processes, including electrochemical CO 2 reduction. Imidazolium cations...    

    

* Creation of intrinsic defects on ZIF-8 particles to facilitate electrochemical reduction of CO2 over Fe single-atom catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399556108
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.153073")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399556108"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399556108"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399556108"))][Get cited by]]

OpenAlex: https://openalex.org/W4399556108 (Open access: False)
    
[[https://openalex.org/A5035870630][Lianzhong Shen]], [[https://openalex.org/A5040686790][Wei Lin]], [[https://openalex.org/A5046701096][Yan Yu]], [[https://openalex.org/A5033636135][Zhuowei Li]], [[https://openalex.org/A5031657754][Qizhou Dai]], Chemical engineering journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.153073 
     
No abstract    

    

* Coupling regulation of boron doping and morphology in nano-floral CuO using one pot method for electrocatalytic CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399629089
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Formation and Properties of Nanocrystals and Nanostructures, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.128326")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399629089"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399629089"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399629089"))][Get cited by]]

OpenAlex: https://openalex.org/W4399629089 (Open access: False)
    
[[https://openalex.org/A5059692744][Zhixiu Yang]], [[https://openalex.org/A5030420487][Xianghong Guo]], [[https://openalex.org/A5011288772][Yong Chen]], [[https://openalex.org/A5071865524][Lijing Gao]], [[https://openalex.org/A5034509638][Ruiping Wei]], [[https://openalex.org/A5088430992][Guomin Xiao]], Separation and purification technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.128326 
     
No abstract    

    

* Molybdenum diselenide/polymeric carbon nitride dual-homojunction photocatalyst with multi-step charge transfer for efficient catalytic CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399562847
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.06.050")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399562847"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399562847"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399562847"))][Get cited by]]

OpenAlex: https://openalex.org/W4399562847 (Open access: False)
    
[[https://openalex.org/A5058837217][Ruizhi Yang]], [[https://openalex.org/A5020712927][Xiangli Shi]], [[https://openalex.org/A5017632282][Qianjin Ye]], [[https://openalex.org/A5075080019][Qin Li]], [[https://openalex.org/A5056002024][Qiong Zhang]], [[https://openalex.org/A5048533850][Di Li]], [[https://openalex.org/A5091071159][Deli Jiang]], Journal of colloid and interface science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.06.050 
     
No abstract    

    

* Theoretical Investigation on the Structural Characteristics and Electrocatalytic Co2 Reduction Mechanism of G-C3n4 Supported Ag/Au Single Atom Catalysts  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399657986
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4865428")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399657986"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399657986"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399657986"))][Get cited by]]

OpenAlex: https://openalex.org/W4399657986 (Open access: False)
    
[[https://openalex.org/A5081679759][Hui-Ling Shui]], [[https://openalex.org/A5013566518][Xin Wei]], [[https://openalex.org/A5002675645][Chao Fu]], [[https://openalex.org/A5089677738][Dong-Heng Li]], [[https://openalex.org/A5047708304][Xiaoqin Liang]], [[https://openalex.org/A5051363890][Kai Li]], [[https://openalex.org/A5024867236][Laicai Li]], [[https://openalex.org/A5035956405][Yan Zheng]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4865428 
     
No abstract    

    

* Novel iodide-modified bismuth molybdate quantum dot/monolayer graphene (0D/2D) heterojunction for efficient photothermal catalytic reduction of CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399627216
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jgsce.2024.205383")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399627216"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399627216"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399627216"))][Get cited by]]

OpenAlex: https://openalex.org/W4399627216 (Open access: False)
    
[[https://openalex.org/A5068170537][Mingnv Guo]], [[https://openalex.org/A5007595314][Jiahao Liu]], [[https://openalex.org/A5011590420][Jiaqi Qiu]], [[https://openalex.org/A5074586582][Ziqi Wang]], [[https://openalex.org/A5072787821][Zhongqing Yang]], Gas science and engineering. None(None)] 2024. https://doi.org/10.1016/j.jgsce.2024.205383 
     
No abstract    

    

* Preparation, activity and mechanism of metallic Cu/TiO2 nanotube arrays catalyst by fast solar drying method for photothermal CO2 reduction under concentrating light  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399517295
:TOPICS: Formation and Properties of Nanocrystals and Nanostructures, Gas Sensing Technology and Materials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cy00175c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399517295"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399517295"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399517295"))][Get cited by]]

OpenAlex: https://openalex.org/W4399517295 (Open access: False)
    
[[https://openalex.org/A5059863277][Zekai Zhang]], [[https://openalex.org/A5081472333][Wei Yan]], [[https://openalex.org/A5063691681][Ying Wang]], [[https://openalex.org/A5033142329][Guokai Cui]], [[https://openalex.org/A5066000911][Hanfeng Lu]], Catalysis science & technology. None(None)] 2024. https://doi.org/10.1039/d4cy00175c 
     
Photocatalytic reduction of CO2 with solar energy can realize carbon cycle and ultimately solve the CO2 emission problem, while it suffers a low energy conversion efficiency. In this paper, metallic...    

    

* High-throughput screening of single-atom catalysts on 1 T-TMD for highly active and selective CO2 reduction reaction: Computational and machine learning insights  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399662000
:TOPICS: Accelerating Materials Innovation through Informatics, Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcat.2024.115610")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399662000"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399662000"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399662000"))][Get cited by]]

OpenAlex: https://openalex.org/W4399662000 (Open access: False)
    
[[https://openalex.org/A5043467632][Xi Shen]], [[https://openalex.org/A5090127624][Peng Zhao]], [[https://openalex.org/A5008473333][Cheng He]], [[https://openalex.org/A5080205613][W. Zhang]], Journal of catalysis. None(None)] 2024. https://doi.org/10.1016/j.jcat.2024.115610 
     
No abstract    

    

* Research Progress in Electrochemical Technology for Reducing Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399654420
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Solid Oxide Fuel Cells, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54097/cepkpn24")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399654420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399654420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399654420"))][Get cited by]]

OpenAlex: https://openalex.org/W4399654420 (Open access: False)
    
[[https://openalex.org/A5010781132][Jiaxuan Li]], Highlights in science, engineering and technology. 83(None)] 2024. https://doi.org/10.54097/cepkpn24 
     
With the elevated carbon dioxide (CO2) emissions and the need for green and sustainable development, the need for electrochemical CO2 reduction technology is becoming more and more urgent. However, the electrochemical reduction technology still has difficulties and has not yet met the high requirements for large-scale industrialized production. In this paper, the field of electrochemical reduction of carbon dioxide is deeply explored from the perspectives of technological features and applications, and the progress in this field is discussed in terms of cathode materials, anode materials, and electrolytes, and the application of electrochemical technology in the field of carbon dioxide reduction is investigated concerning the differences in the generating material and loading voltage. Electrochemical carbon dioxide reduction technology can reduce carbon dioxide into utilizable industrial products by loading load voltage, and can selectively generate products such as formic acid, methanol, and methane by choosing different electrode materials and electrolytes, the selection of electrode materials and electrolytes and the selection of suitable load voltage are also the technical difficulties and the key points to realize industrial production. The electrochemical reduction of carbon dioxide technology has a wide range of applications in industrial production and energy saving and emission reduction, and this paper provides ideas for the understanding and further development of electrochemical reduction of carbon dioxide technolog.    

    

* Carbon Dioxide Gasification of Biochar: A Sustainable Way of Utilizing Captured CO2 to Mitigate Greenhouse Gas Emission  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399626239
:TOPICS: Biomass Pyrolysis and Conversion Technologies, Indoor Air Pollution in Developing Countries, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-06-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16125044")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399626239"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399626239"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399626239"))][Get cited by]]

OpenAlex: https://openalex.org/W4399626239 (Open access: True)
    
[[https://openalex.org/A5099116689][Nnamdi Ofuani]], [[https://openalex.org/A5039767584][Prakash Bhoi]], Sustainability. 16(12)] 2024. https://doi.org/10.3390/su16125044 
     
This study proposes CO2 gasification of biochar as a potential carbon utilization pathway for greenhouse gas emission reduction. It aims to evaluate the effects of CO2 concentration on carbon and CO2 conversion and output CO yield. It also performs kinetic analysis, using the volume reaction model, to determine the activation energy and pre-exponential factor. The operating conditions utilized include gasification temperatures of 700, 800, and 900 °C; inlet CO2 concentrations of 15%, 30%, 45%, and 60% by volume (N2 balance); and a CO2 flow rate of 5 L/min. Carbon dioxide gasification of biochar was performed in a fixed bed batch reactor, and the composition of the output gases was analyzed. Increases in the temperature and inlet CO2 concentration both resulted in an increase in carbon conversion, with the maximum carbon conversion of 57.1% occurring at 900 °C and a 60% inlet CO2 concentration. The results also showed that CO2 conversion increased against temperature but decreased with an increasing inlet CO2 concentration. The maximum CO2 conversion of 76% was observed at 900 °C and a 15% inlet CO2 concentration. An activation energy in the range of 109 to 117 kJ/mol and a pre-exponential factor in the range of 63 to 253 s−1 were determined in this study.    

    

* Oxygen‐tolerant CO2 Electrocatalysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399465290
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-06-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400659")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399465290"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399465290"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399465290"))][Get cited by]]

OpenAlex: https://openalex.org/W4399465290 (Open access: False)
    
[[https://openalex.org/A5036968098][Hongfei Zhu]], [[https://openalex.org/A5084772771][Hui Guo]], [[https://openalex.org/A5027181760][Rong Cao]], [[https://openalex.org/A5047300245][Yuan–Biao Huang]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400659 
     
The electrochemical carbon dioxide reduction reaction (CO2RR) to generate high‐value products is considered to be a promising approach to reduce the atmospheric concentration of CO2. However, the pure CO2 gas is generally required in the most of the reported CO2RR system, which brings tedious capture and separation procedures and high cost. The utilization of realistic CO2 emission directly such as flue gas for the CO2RR is highly desirable. However, the gas impurities in the real CO2 sources such as oxygen could seriously affect the activity and selectivity of the CO2RR. This concept summarizes the recently reported works about CO2RR studies in the presence of O2 and highlights the physical and chemical strategies to boost CO2 electroreduction performance. We further discuss the implications of these strategies for future progress in this emerging field.    

    

* Facet-switching of rate-determining step on copper in CO 2 -to-ethylene electroreduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399480959
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1073/pnas.2400546121")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399480959"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399480959"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399480959"))][Get cited by]]

OpenAlex: https://openalex.org/W4399480959 (Open access: True)
    
[[https://openalex.org/A5089180994][Yu-Cai Zhang]], [[https://openalex.org/A5059787769][Xiaolong Zhang]], [[https://openalex.org/A5016707388][Zhi-Zheng Wu]], [[https://openalex.org/A5083454521][Zhuang‐Zhuang Niu]], [[https://openalex.org/A5062645020][Li‐Ping Chi]], [[https://openalex.org/A5010084472][Fei‐Yue Gao]], [[https://openalex.org/A5059425296][Peng‐Peng Yang]], [[https://openalex.org/A5039342550][Ye-Hua Wang]], [[https://openalex.org/A5050025864][Peiping Yu]], [[https://openalex.org/A5022387512][Jing-Wen DuanMu]], [[https://openalex.org/A5062967630][Shuping Sun]], [[https://openalex.org/A5018140110][Min‐Rui Gao]], Proceedings of the National Academy of Sciences of the United States of America. 121(25)] 2024. https://doi.org/10.1073/pnas.2400546121 
     
Reduction of carbon dioxide (CO    

    

* Probing Metal/High-Entropy Perovskite Heterointerface for Efficient and Sustainable CO2 Electroreduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399693680
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Solid Oxide Fuel Cells, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta02372b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399693680"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399693680"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399693680"))][Get cited by]]

OpenAlex: https://openalex.org/W4399693680 (Open access: False)
    
[[https://openalex.org/A5073685573][Yan Zhu]], [[https://openalex.org/A5009318195][Nan Zhang]], [[https://openalex.org/A5081086386][Wenyu Zhang]], [[https://openalex.org/A5008449115][Yun Gong]], [[https://openalex.org/A5092374784][Rui Wang]], [[https://openalex.org/A5059823291][Huanwen Wang]], [[https://openalex.org/A5002421098][Jiaqi Jin]], [[https://openalex.org/A5076658761][Liancheng Zhao]], [[https://openalex.org/A5079220797][Bo He]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta02372b 
     
Solid oxide electrolysis cells (SOECs) are increasingly recognized for their great potential in carbon dioxide reduction reaction (CO2RR). However, the sluggish kinetics of CO2RR impedes their widespread commercialization. Here, a...    

    

* Ethylene Electrosynthesis via Selective CO2 Reduction: Fundamental Considerations, Strategies, and Challenges  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399533802
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202401558")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399533802"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399533802"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399533802"))][Get cited by]]

OpenAlex: https://openalex.org/W4399533802 (Open access: False)
    
[[https://openalex.org/A5099089350][Thomas O' Carroll]], [[https://openalex.org/A5080236384][Xiaoxuan Yang]], [[https://openalex.org/A5044324875][Kenneth J. Gordon]], [[https://openalex.org/A5019871052][Ling Fei]], [[https://openalex.org/A5003842479][Gang Wu]], Advanced energy materials. None(None)] 2024. https://doi.org/10.1002/aenm.202401558 
     
Abstract The electrochemical carbon dioxide reduction reaction (CO 2 RR) is a promising approach for reducing atmospheric carbon dioxide (CO 2 ) emissions, allowing harmful CO 2 to be converted into more valuable carbon‐based products. On one hand, single carbon (C 1 ) products have been obtained with high efficiency and show great promise for industrial CO 2 capture. However, multi‐carbon (C 2+ ) products possess high market value and have demonstrated significant promise as potential products for CO 2 RR. Due to CO 2 RR's multiple pathways with similar equilibrium potentials, the extended reaction mechanisms necessary to form C 2+ products continue to reduce the overall selectivity of CO 2 ‐to‐C 2+ electroconversion. Meanwhile, CO 2 RR as a whole faces many challenges relating to system optimization, owing to an intolerance for low surface pH, systemic stability and utilization issues, and a competing side reaction in the form of the H 2 evolution reaction (HER). Ethylene (C 2 H 4 ) remains incredibly valuable within the chemical industry; however, the current established method for producing ethylene (steam cracking) contributes to the emission of CO 2 into the atmosphere. Thus, strategies to significantly increase the efficiency of this technology are essential. This review will discuss the vital factors influencing CO 2 RR in forming C 2 H 4 products and summarize the recent advancements in ethylene electrosynthesis.    

    

* Research on the decoupling effect and driving factors of carbon emissions in Hubei province's industry：based on the perspective of developing new quality productive forces  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399665349
:TOPICS: Life Cycle Assessment and Environmental Impact Analysis
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4513461/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399665349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399665349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399665349"))][Get cited by]]

OpenAlex: https://openalex.org/W4399665349 (Open access: False)
    
[[https://openalex.org/A5031662805][Hongxing Tu]], [[https://openalex.org/A5038511853][XU Song-tao]], [[https://openalex.org/A5089968630][Po‐An Tu]], [[https://openalex.org/A5087647138][Xu Xiao]], No host. None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4513461/v1 
     
Abstract Under the "dual carbon" goal, the new productive forces in the industrial energy sector will become an important force in promoting the green and high-quality development of the economy and society in Hubei Province. The article comprehensively applies the Tapio decoupling model and LMDI decomposition method, and uses panel data of the industrial industry in Hubei Province from 2005 to 2021 to empirically analyze the decoupling effect of industrial carbon emissions in Hubei Province and its driving factors. Our research has found that the industrial economic growth and carbon emissions in Hubei Province roughly exhibit a complex process of changes from strong decoupling to weak decoupling, then to strong decoupling, and finally to recessive decoupling. For a considerable period of time in the future, the industrial economic growth and carbon emissions in Hubei Province will still be weakly decoupled. From the decomposition results, it can be seen that the changes in the energy intensity index and carbon intensity index are basically consistent. The decrease in energy intensity has the greatest contribution to carbon dioxide reduction, becoming a key factor driving the reduction of industrial carbon intensity in Hubei. However, the dividends brought by structural effects are still not significant. On this basis, the article proposes relevant policy recommendations, providing theoretical basis and policy basis for the high-quality development of Hubei's industry and the construction of new productive forces in the post epidemic era.    

    

* Late Eocene to early Oligocene productivity events in the proto-Southern Ocean and correlation to climate change  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399686581
:TOPICS: Climate Change and Paleoclimatology, Paleoredox and Paleoproductivity Proxies, Geological Evolution of the Arctic Region
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/cp-20-1327-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399686581"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399686581"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399686581"))][Get cited by]]

OpenAlex: https://openalex.org/W4399686581 (Open access: True)
    
[[https://openalex.org/A5079727237][Gabrielle Rodrigues de Faria]], [[https://openalex.org/A5006505569][David Lazarus]], [[https://openalex.org/A5047904712][Johan Renaudie]], [[https://openalex.org/A5002450210][Jessica A. Stammeier]], [[https://openalex.org/A5050199397][Volkan Özen]], [[https://openalex.org/A5020494833][Ulrich Struck]], Climate of the past. 20(6)] 2024. https://doi.org/10.5194/cp-20-1327-2024 
     
Abstract. The Eocene–Oligocene transition (EOT, ca. 40–33 Ma) marks a transformation from a largely ice-free to an icehouse climate mode that is well recorded by oxygen-stable isotopes and sea surface temperature proxies. Opening of the Southern Ocean gateways and decline in atmospheric carbon dioxide levels have been considered as factors in this global environmental transformation and the growth of ice sheets in Antarctica during the Cenozoic. A more comprehensive understanding is still needed of the interplay between forcing versus response, the correlation among environmental changes, and the involved feedback mechanisms. In this study, we investigate the spatio-temporal variation in export productivity using biogenic Ba (bio-Ba) from Ocean Drilling Program (ODP) sites in the Southern Ocean, focusing on possible mechanisms that controlled them as well as the correlation of export productivity changes to changes in the global carbon cycle. We document two high export productivity events in the Southern Ocean during the late Eocene (ca. 37 and 33.5 Ma) that correlate to proposed gateway-driven changes in regional circulation and to changes in global atmospheric pCO2 levels. Our findings suggest that paleoceanographic changes following Southern Ocean gateway openings, along with more variable increases in circulation driven by episodic Antarctic ice sheet expansion, enhanced export production in the Southern Ocean from the late Eocene through early Oligocene. These factors may have played a role in episodic atmospheric carbon dioxide reduction, contributing to Antarctic glaciation during the Eocene–Oligocene transition.    

    

* Evaluating the effect of the accountability audit of natural resources on carbon emissions reduction in China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399524116
:TOPICS: Energy Efficiency in Manufacturing and Industry Sector, Economic Implications of Climate Change Policies, Life Cycle Assessment and Environmental Impact Analysis
:PUBLICATION_DATE: 2024-06-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/fenvs.2024.1342321")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399524116"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399524116"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399524116"))][Get cited by]]

OpenAlex: https://openalex.org/W4399524116 (Open access: True)
    
[[https://openalex.org/A5024560174][Liyang Xiong]], [[https://openalex.org/A5085925098][Yiyi Shu]], [[https://openalex.org/A5051862250][Xuefeng Li]], Frontiers in environmental science. 12(None)] 2024. https://doi.org/10.3389/fenvs.2024.1342321 
     
The accountability audit of natural resources (AANR) is a major institutional arrangement for advancing the construction of an ecological civilization in China. Based on the panel data of 271 cities in China from 2005 to 2017, this paper investigates the relationship between the AANR and carbon dioxide (CO 2 ) emissions using a multi-period difference-in-differences (DID) model. The results show that AANR significantly increases the CO 2 emission reduction rate by 0.009 units at the 5% significance level. The results still hold after a series of robustness tests. Given all else being equal, this significant effect is 0.001. Further analyses show that AANR improves pilot cities’ CO 2 emission reduction rates mainly by enhancing their green innovation capability. The mediating effect of cities’ green technology innovation capability accounts for 96.00%, while the AANR’s direct effect only accounts for 4.00%. The AANR has significantly positive effects of 0.017% and 0.029% for western cities and cities with high fiscal pressure at the 5% and 1% significance levels, respectively. Therefore, strengthening AANR implementation by enhancing the mediating efficiency of cities’ green technology innovations and implementing dynamically differentiated AANR policies in Chinese meso-cities will contribute to the achievement of China’s carbon peaking and carbon neutrality targets.    

    

* Innovative Biomaterials in Green Construction: Economic Benefits and Challenges  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399647469
:TOPICS: Sustainable Development in Knowledge Economy Era, Interdependence in Science and Society
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/e3sconf/202453706011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399647469"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399647469"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399647469"))][Get cited by]]

OpenAlex: https://openalex.org/W4399647469 (Open access: True)
    
[[https://openalex.org/A5076776708][Е. А. Козлова]], [[https://openalex.org/A5050537377][Alena Pavlovna Demidova]], [[https://openalex.org/A5099120029][Lyalya Edilsultanova]], E3S web of conferences. 537(None)] 2024. https://doi.org/10.1051/e3sconf/202453706011 
     
The integration of biotechnology in green building represents a cutting-edge approach that harnesses biological processes to enhance sustainability and efficiency in construction practices. This abstract explores modern strategies and provides examples of how biotechnology is revolutionizing green building. Biotechnology offers innovative solutions to traditional challenges in green building, leveraging biological systems to optimize resource utilization, energy efficiency, and waste reduction. By integrating living organisms, biomaterials, and biological processes into building design and construction, biotechnology enables the development of structures that are not only environmentally friendly but also adaptive and resilient.One modern approach involves incorporating living organisms such as algae, bacteria, and fungi into building materials to enhance their performance. For example, algae can be used in bio-facades to capture carbon dioxide and produce oxygen, contributing to improved indoor air quality and reducing the building's carbon footprint. Similarly, bacteria can be embedded in concrete to repair cracks autonomously, increasing the durability and lifespan of structures while minimizing maintenance needs.    

    

* Life time of Reinforced Concrete floors of industrial buildings, connected with the use of chlorine  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399548396
:TOPICS: Reinforcement Corrosion in Concrete Structures, Geopolymer and Alternative Cementitious Materials, Synthesis and Applications of Sulfur Nanoparticles
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/e3sconf/202453501012")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399548396"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399548396"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399548396"))][Get cited by]]

OpenAlex: https://openalex.org/W4399548396 (Open access: True)
    
[[https://openalex.org/A5005164787][Ashot Tamrazyan]], E3S web of conferences. 535(None)] 2024. https://doi.org/10.1051/e3sconf/202453501012 
     
The article deals with the issues of durability (Life time) of floors of industrial buildings associated with the presence of chlorine. It is shown that, together with carbon dioxide, chlorine forms well-soluble hygroscopic layers in the form of calcium chloride. The movement of chlorine salts causes corrosion of the reinforcement and penetrates deep into the concrete. Therefore, the service life of reinforced concrete elements when exposed to an external aggressive environment is reduced due to corrosion of reinforcement and concrete. Experimental data and analytical dependences of the advance of the front of chloride concentrations dangerous for reinforcement and destruction of concrete under the action of the considered aggressive environment are presented. A formula is derived for the design service life of reinforced concrete structures by the factor of the passivating action of the protective layer of concrete. An empirical dependence of the service life of the structure on the depth of corrosion (diameter reduction) of the reinforcement was also obtained. The coefficient of corrosive wear of reinforcement for rectangular and tee sections bending reinforced concrete elements is calculated.    

    

* Under‐Ice Oxygen Depletion and Greenhouse Gas Supersaturation in North Temperate Urban Ponds  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399645223
:TOPICS: Arctic Permafrost Dynamics and Climate Change, Impacts of Climate Change on Glaciers and Water Availability, Arctic Sea Ice Variability and Decline
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1029/2024jg008120")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399645223"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399645223"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399645223"))][Get cited by]]

OpenAlex: https://openalex.org/W4399645223 (Open access: True)
    
[[https://openalex.org/A5027469070][Adrianna L. Gorsky]], [[https://openalex.org/A5087937289][Hilary A. Dugan]], [[https://openalex.org/A5039044615][Grace M. Wilkinson]], [[https://openalex.org/A5080951776][Emily H. Stanley]], Journal of geophysical research. Biogeosciences. 129(6)] 2024. https://doi.org/10.1029/2024jg008120 
     
Abstract Stormwater ponds are common features in urbanized landscapes because they enhance flood reduction and nutrient retention. With shallow depths and high inputs of organic matter, these systems can be highly productive with rapid oxygen depletion when thermally stratified or ice‐covered. However, most of our understanding of the biogeochemistry of stormwater ponds comes from the open water period. We explored under‐ice oxygen dynamics in 20 stormwater ponds in Madison, WI (USA) that were ice covered from late December to early March to investigate the drivers of bottom water oxygen saturation and the impact on the accumulation of carbon dioxide (CO 2 ) and methane (CH 4 ). Winter anoxia was driven by ice transmissivity, winter nutrient concentrations, and precedent summer productivity. Oxygen depletion led to overall higher concentrations of greenhouse gases in pond surface waters. This research enhances our understanding of winter pond biogeochemistry and its links to summer productivity.    

    

* The Role and Application of Redox Potential in Wine Technology  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399571412
:TOPICS: Microbial Interactions in Wine Production and Flavor, Antioxidants and Free Radicals in Health and Disease, Genetic and Environmental Factors in Grapevine Cultivation
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/fermentation10060312")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399571412"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399571412"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399571412"))][Get cited by]]

OpenAlex: https://openalex.org/W4399571412 (Open access: True)
    
[[https://openalex.org/A5011326609][Marin Berovič]], Fermentation. 10(6)] 2024. https://doi.org/10.3390/fermentation10060312 
     
In wine technology, the on-line measurement of redox potential is a fast, accurate, and reliable measurement that provides insight into the metabolism of Saccharomyces cerevisiae, its microbial activity, and the oxidation and reduction state of wine, as well as insight into its quality and stability. The significance of the redox potential measurement and control in wine technology as well as the maintenance and regulation of fermentation redox potential using temperature and carbon dioxide fluxes are discussed. Redox potential levels from Eh 100 to 180 mV are typical for non-oxidized wine that is bottling-ready, while levels of Eh 270 to 460 mV represent oxidized wines with typical failures. The relevance of redox potential measurement during the 2-year maturation of Blau Fränkisch wine in 225 L oak barrels at six levels at a temperature 15 °C is presented. The measurement of the redox potential, expressing heterogeneity in redox layers during wine maturation in oak barrels, is represented in various oxido-reductive fermentation zones. On the contrary, the end of the maturation process is indicated by the homogeneity of redox zones, where the matured wine shows no differences in redox measurement on all levels. Using redox potential as a key scale-up criteria ensures comparable and reproducible amounts of the final product even in geometrically non-similar fermenter systems.    

    

* FERMENTATION TECHNOLOGY  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399594262
:TOPICS: Microbial Production of Polyglutamic Acid
:PUBLICATION_DATE: 2024-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.58532/v3bgbt2p1ch7")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399594262"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399594262"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399594262"))][Get cited by]]

OpenAlex: https://openalex.org/W4399594262 (Open access: False)
    
[[https://openalex.org/A5014793451][N. Akila]], No host. None(None)] 2024. https://doi.org/10.58532/v3bgbt2p1ch7 
     
Fermentation is a complex process that involves molecular oxidation or reduction mechanisms driven by selective microorganisms under anaerobic conditions. This transformative process results in the production of various bioactive molecules, which offer significant health benefits. The fundamental principle of fermentation technology entails cultivating organisms under ideal conditions, providing them with essential raw materials like carbon, nitrogen, salts, trace elements, and vitamins. The primary function of fermentation lies in the conversion of NADH back into the coenzyme NAD+, allowing it to be utilized again in glycolysis. During fermentation, an organic electron acceptor (e.g., pyruvate or acetaldehyde) interacts with NADH to produce NAD+, yielding by products such as carbon dioxide and ethanol (as seen in ethanol fermentation) or lactate (in lactic acid fermentation). The metabolically derived end products, formed over the life span of microorganisms, are released into the surrounding medium. These products are then extracted for various human applications, holding significant commercial value. Based on the specific end product generated, fermentation can be categorized into four types: lactic acid fermentation, alcohol fermentation, acetic acid fermentation, and butyric acid fermentation. To facilitate the fermentation process, a fermenter or bioreactor is employed. This device is designed for the cultivation of microorganisms and contains all the necessary components for the large-scale synthesis of various compounds, including antibiotics, enzymes, and beverages across different industries. The microorganisms within the fermented are cultivated in a manner that maximizes the yield of the product while minimizing the required resources.    

    

* Novel Nanocomposite Electrolytes for Sustainable Fuel Cells  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399646883
:TOPICS: Fuel Cell Membrane Technology, Lithium Battery Technologies, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/e3sconf/202453707013")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399646883"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399646883"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399646883"))][Get cited by]]

OpenAlex: https://openalex.org/W4399646883 (Open access: True)
    
[[https://openalex.org/A5049812453][Soosan Chhabra]], [[https://openalex.org/A5021916342][Ankita Joshi]], [[https://openalex.org/A5002007488][Suyash Mishra]], [[https://openalex.org/A5040665859][Amanveer Singh]], [[https://openalex.org/A5060230427][B. Sankara Babu]], [[https://openalex.org/A5040896430][Shivani Kampani]], [[https://openalex.org/A5040895333][Kaushal Kumar]], E3S web of conferences. 537(None)] 2024. https://doi.org/10.1051/e3sconf/202453707013 
     
An investigation has been conducted to determine whether or not novel nanocomposite electrolytes have the potential to improve the efficiency and longevity of fuel cell technology. In this investigation, nanocomposite electrolytes were manufactured by using a methodical methodology. The nanoparticles were included into polymer matrices in order to enhance the ion conductivity and mechanical strength of the electrolytes developed. The composition of nanocomposite electrolytes was improved by altering the amount of nanoparticles and polymers that were present. When compared to traditional electrolytes, the introduction of nanoparticles resulted in considerable improvements in the characteristics of the material. These enhancements included a 15% increase in ion conductivity and a 10% increase in mechanical strength. Fuel cell devices that make use of nanocomposite electrolytes have showed improved performance, with a 10% increase in power density and a 15% gain in efficiency when compared to fuel cell devices that make use of traditional electrolytes. In addition, the environmental impact assessment found that the use of nanocomposite electrolytes resulted in a two percent drop in the amount of energy used, a fifteen percent reduction in the amount of waste generated, and a twenty-five percent reduction in the amount of carbon dioxide emissions. As a result of these discoveries, the potential ofnanocomposite electrolytes to enhance the sustainability and efficiency of fuel cell technology has been brought to light. This opens the door for the creation of next-generation fuel cells that have increased performance and decreased their effect on the environment.    

    

* Feasibility and Techno-Economic Assessment of a 128kWp Grid-Tied SPV System using HOMER Pro  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399681222
:TOPICS: Lithium-ion Battery Management in Electric Vehicles, Integration of Electric Vehicles in Power Systems, Control and Synchronization in Microgrid Systems
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1742-6596/2777/1/012008")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399681222"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399681222"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399681222"))][Get cited by]]

OpenAlex: https://openalex.org/W4399681222 (Open access: True)
    
[[https://openalex.org/A5056993195][Akhlaque Ahmad Khan]], [[https://openalex.org/A5047740133][Ahmad Faiz Minai]], [[https://openalex.org/A5072439690][Mohammad Atif Siddiqui]], Journal of physics. Conference series. 2777(1)] 2024. https://doi.org/10.1088/1742-6596/2777/1/012008 
     
Abstract A substantial amount of the world’s annual CO 2 emissions are attributable to the continued consumption of electricity from the grid that is generated from burning fossil fuels. Renewable energy sources could strengthen grid reliability and lessen their effect on the environment, especially in high-demand regions prone to power failures. Investigating the viability of erecting solar power plants in a subtropical area to provide the necessary electricity for an educational building that operates mainly during daylight hours is the main intent of the present study. The purpose of this investigation is to demonstrate and validate a model for enormous-scale commercial HRES applications (such as an educational institution) utilising the HOMER programme to figure out the optimal size. Minimising emissions of carbon dioxide, the main greenhouse gas responsible for accelerating global warming, is also of the utmost importance. Based on the simulation findings, the optimal system configuration consisted of a 120 kW converter and 400 PV arrays (each with 320 Wp = 128 kWp). For regional power generation, the most cost-effective choice is still a combination of solar panels and the grid. Findings show that a HRES can be economically feasible for installation in educational institutions at an initial capital cost of USD $0.068 million with annual operating expenses of USD $0.0447 million—a reduction of 44.11% compared to the existing system. The expected payback for this endeavour is five years. Other locations with identical climates could benefit from these results when considering the deployment of comparable technology. In order to help achieve a zero-carbon target, financial rewards could encourage governments to adopt similar schemes.    

    

* In–Situ Characterization Techniques for Mechanism Studies of CO2 Hydrogenation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399475691
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-06-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cplu.202300511")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399475691"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399475691"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399475691"))][Get cited by]]

OpenAlex: https://openalex.org/W4399475691 (Open access: False)
    
[[https://openalex.org/A5005210320][Rasmeet Singh]], [[https://openalex.org/A5048681505][Lizhuo Wang]], [[https://openalex.org/A5015226338][Jun Huang]], ChemPlusChem. None(None)] 2024. https://doi.org/10.1002/cplu.202300511 
     
The paramount concerns of global warming, fossil fuel depletion, and energy crises have prompted the need of hydrocarbons productions via CO2 conversion. In order to achieve global carbon neutrality, much attention needs to be diverted towards CO2 management. Catalytic hydrogenation of CO2 is an exciting opportunity to curb the increasing CO2 and produce value-added products. However, the comprehensive understanding of CO2 hydrogenation is still a matter of discussion due to its complex reaction mechanism and involvement of various species. This review comprehensively discusses three processes: reverse water gas shift (RWGS) reaction, modified Fischer Tropsch synthesis (MFTS), and methanol-mediated route (MeOH) for CO2 hydrogenation to hydrocarbons. It is also very important to understand the real-time evolvement of catalytic process and reaction intermediates by employing in-situ characterization techniques. Subsequently, in second part of this review, we provided a systematic analysis of advancements in in-situ techniques aimed to monitor the evolution of catalysts during CO2 reduction process. The section also highlights the key components of in-situ cells, their working principles, and applications in identifying reaction mechanisms for CO2 hydrogenation. Finally, by reviewing respective achievements in the field, we identify key gaps and present some future directions for CO2 hydrogenation and in-situ studies.    

    

* A Synergic investigation of Experimental and Computational Dual Atom Electrocatalysis for CO2 Conversion to C1 and C2+ products  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399667876
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta02860k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399667876"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399667876"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399667876"))][Get cited by]]

OpenAlex: https://openalex.org/W4399667876 (Open access: False)
    
[[https://openalex.org/A5088690230][Saurabh Vinod Parmar]], [[https://openalex.org/A5046723865][Dalbir Kaur]], [[https://openalex.org/A5038787425][Vidya Avasare]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta02860k 
     
This review delves into the promising field of dual atom catalysts (DACs) for the electrochemical reduction of CO2 to yield a diverse array of Cn (n = 1, 2, and...    

    

* The Thermodynamic Change Laws of CO2-Coupled ractured Rock  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399634168
:TOPICS: Study on Rock Mechanics in Deep Mining Engineering, Carbon Dioxide Sequestration in Geological Formations, Rock Mechanics and Engineering
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/app14125122")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399634168"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399634168"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399634168"))][Get cited by]]

OpenAlex: https://openalex.org/W4399634168 (Open access: True)
    
[[https://openalex.org/A5076883991][Yu Fei]], [[https://openalex.org/A5084052494][Deng Guang-zhe]], Applied sciences. 14(12)] 2024. https://doi.org/10.3390/app14125122 
     
Under the background of the “dual carbon” target, exploring the pathway of efficient geological storage and high energy utilization of CO2 is a hot issue in CO2 emission reduction research. Under the coupling effect of high geopathic stress in deep rock layers and thermal stress generated during the geological sequestration of CO2, CO2 infiltration into coal rock changes the ambient temperature around the rock, while thermal diffusion effects cause damage to the rock and influence fracture expansion. In the present study, CO2-water–rock coupling test system and characterization of fissure surface roughness were conducted to analyze the rock’s mechanical properties, damage, and fracture evolution. Modeling of the equivalent fissure was employed to reveal the heat transfer mechanism between the rock matrix and CO2. The results obtained illustrate that the rock samples coupled with CO2 exhibited remarkable changes in mechanical properties. These changes include an increase in the number of pores, enhanced inter-pore connectivity, and a planar type of surface roughness in the fissures, ultimately resulting in an increase in conductivity. Conversely, the remaining rock samples displayed poor mechanical properties and surface fracture connectivity. As pressure decreased, the heat transfer coefficient decreased from 86.9 W/m2·K to 57.5 W/m2·K, accompanied by a temperature drop from 33.6 °C to 30.6 °C, demonstrating a proportional relationship between pressure and the heat transfer coefficient. Furthermore, the flow rate gradually increased with the rise in CO2 pressure, indicating denser flow lines with faster flow rates. At 15 MPa, CO2 exhibits enhanced mobility.    

    

* Electrochemical Reduction of Nitrate to Ammonia on Ultra-Stable Amorphous Co-P Electrocatalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399681582
:TOPICS: Ammonia Synthesis and Electrocatalysis, Materials and Methods for Hydrogen Storage, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta02299h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399681582"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399681582"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399681582"))][Get cited by]]

OpenAlex: https://openalex.org/W4399681582 (Open access: False)
    
[[https://openalex.org/A5078824905][Jinlong Fan]], [[https://openalex.org/A5038895478][Shengbo Liu]], [[https://openalex.org/A5074511281][Mingliang Chen]], [[https://openalex.org/A5003219713][Zhangxiong Wu]], [[https://openalex.org/A5061371784][Sheng-Peng Sun]], [[https://openalex.org/A5071956527][Yaoyin Lou]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta02299h 
     
Electrocatalytic reduction of nitrate (NO3–) to ammonia (NH3) is garnering increasing interest due to its potential to reduce CO2 emissions as a substitute for the Haber-Bosch process, while also mitigating...    

    

* LNG VERSUS CONVENTIONAL FUEL POWERED VESSELS: ENVIRONMENTAL IMPACT OF ROPAX SHIPS  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399515293
:TOPICS: Environmental Impact of Maritime Transportation Emissions
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5821/mt.13202")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399515293"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399515293"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399515293"))][Get cited by]]

OpenAlex: https://openalex.org/W4399515293 (Open access: True)
    
[[https://openalex.org/A5055401125][Alvaro Herrero Martinez]], [[https://openalex.org/A5016956637][Carlos González-Gutiérrez]], [[https://openalex.org/A5066724634][Andrés Ortega-Piris]], [[https://openalex.org/A5040082456][Emma Díaz Ruiz de Navamuel]], [[https://openalex.org/A5012736058][Miguel A. Guitierrez]], [[https://openalex.org/A5045556615][Alfonso-Isidro López-Diaz]], No host. None(None)] 2024. https://doi.org/10.5821/mt.13202 
     
Decarbonization and environmental respect have become pillars of European government policies. As a result of this direction and given that 80% of global freight transportation is carried out by ships, maritime transport emerges as one of the target sectors for these eco measures. Numerous initiatives, projects, and new technologies focused on this field exist. This paper examines the potential reduction of CO2 emissions by using LNG as a fuel either in combination with or instead of conventional fuel on RO-Pax ships. Taking advantage of the fact that we are facing a 'mature' technology already being applied in many ships. Emissions from a fleet of about 30 ships have been studied during the years 2019, 2020, 2021,2022 and 2023 where progressively adding LNG powered vessels from 4 up to 11 during 2023. Based on their annual consumptions’ reports (HFO, MGO and LNG) total tons of polluted CO2 have been quantified together with the ratio tons of CO2 per sailed mile. On the other hand, known daily burned marine fuels of one of those vessels sailing Balearic Islands-Mainland Spain route and due to high increase of gas prices during 2021 and beginning of 2022 (about 350%) a study was conducted: consuming LNG for 265 days whenever possible and avoiding this fuel for 143 days. Therefore, based on the same ship/route, a particular comparison of CO2 emissions per nautical mile is obtained. Finally, using above results, hypothetical study is carried out in which emissions are estimated based on the sailed miles during years 2017 to 2021: Potential emissions in case of LNG versus conventional fuel powered. The 5-year result shows about 17.08% potential reduction. Approximately 32700 tons of CO2 only for 1 vessel highlighting the huge importance of the LNG powered vessels to reduce the environmental impact and the great importance of the investments on Research, Development and Innovation.    

    

* Lasers for the treatment of nail psoriasis: a systematic review  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399516376
:TOPICS: Epidemiology and Management of Fungal Skin Infections, Pathogenesis and Treatment of Pemphigoid Diseases, Classification and Treatment of Cutaneous Lymphomas
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/ijd.17304")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399516376"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399516376"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399516376"))][Get cited by]]

OpenAlex: https://openalex.org/W4399516376 (Open access: False)
    
[[https://openalex.org/A5092051567][Dana Jaalouk]], [[https://openalex.org/A5042326689][Yanci A. Algarin]], [[https://openalex.org/A5044937699][Anika Pulumati]], [[https://openalex.org/A5093823081][Jasmine Humeda]], [[https://openalex.org/A5007101679][Keyvan Nouri]], International Journal of Dermatology. None(None)] 2024. https://doi.org/10.1111/ijd.17304 
     
Abstract This systematic review assesses the evidence concerning laser treatments for nail psoriasis (NP), a prevalent condition among individuals with cutaneous psoriasis that notably affects their quality of life. Traditional treatments have limitations in terms of drug delivery and poor patient adherence, leading to interest in laser therapies for their targeted approach, extended treatment intervals, and the potential to enhance topical medication effectiveness. The MEDLINE, Embase, Web of Science, and Cochrane Library databases were searched. English‐language randomized and non‐randomized controlled trials with full‐text availability were included. Data on the laser type, treatment protocol, Nail Psoriasis Severity Index (NAPSI) outcomes, and adverse events were extracted, and nail bed and matrix features and patient satisfaction were assessed. The primary effect measure was a percentage reduction in NAPSI scores from baseline. Nineteen studies involving the pulse dye laser (PDL), long‐pulsed neodymium:yttrium aluminum garnet (Nd:YAG) laser and fractional carbon dioxide laser (FCL) were identified. Lasers, particularly those used in conjunction with topical agents, have shown favorable results. PDL effectively lowered NAPSI scores, and the Nd:YAG laser had comparable effectiveness but more discomfort. FCL also shows promise, particularly for topical drug delivery. PDL and Nd:YAG laser treatment were more effective at reducing nail bed features, whereas FCL was effective at reducing both nail bed and matrix features. Overall, lasers are promising treatment alternatives for NP, with similar NAPSI outcomes to topical therapies and intralesional injections.    

    

* Best practices and innovations in carbon capture and storage (CCS) for effective CO2 storage  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399652834
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Carbon Dioxide Sequestration in Geological Formations
:PUBLICATION_DATE: 2024-06-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.51594/ijarss.v6i6.1212")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399652834"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399652834"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399652834"))][Get cited by]]

OpenAlex: https://openalex.org/W4399652834 (Open access: False)
    
[[https://openalex.org/A5099121967][Andrew Emuobosa Esiri]], [[https://openalex.org/A5096171639][Dazok Donald Jambol]], [[https://openalex.org/A5098735408][Chinwe Ozowe]], International journal of applied research in social sciences. 6(6)] 2024. https://doi.org/10.51594/ijarss.v6i6.1212 
     
Carbon capture and storage (CCS) has emerged as a critical technology in the fight against climate change, offering a viable pathway to mitigate CO2 emissions from industrial processes and power generation. This review explores the best practices and innovations in CCS for effective CO2 storage, highlighting key strategies and advancements that optimize storage capacity, enhance storage security, and minimize environmental risks. The review begins by delineating the importance of CCS in reducing greenhouse gas emissions and meeting global climate targets. It underscores the urgency of deploying CCS technologies at scale to address the dual challenge of decarbonizing energy systems and ensuring energy security. Drawing upon recent research and industry developments, the review elucidates best practices in CO2 capture, transport, and storage, emphasizing the importance of integrated and holistic approaches. It discusses advancements in CO2 capture technologies, including post-combustion capture, pre-combustion capture, and oxy-fuel combustion, highlighting efficiency improvements and cost reduction strategies. Furthermore, the review delves into innovations in CO2 storage techniques, such as geological storage, ocean storage, and mineralization, evaluating their respective advantages, challenges, and scalability. It explores best practices for site selection, characterization, and monitoring, emphasizing the need for robust risk assessment frameworks and regulatory oversight to ensure the safety and integrity of storage sites. Moreover, the review examines emerging trends and innovations in CCS, including enhanced oil recovery (EOR) using CO2, direct air capture (DAC) technologies, and carbon utilization and storage (CCUS) initiatives. It discusses the potential synergies between CCS and renewable energy technologies, highlighting integrated solutions that leverage CCS to enable the decarbonization of hard-to-abate sectors such as heavy industry and aviation. The review underscores the pivotal role of CCS in achieving deep decarbonization and transitioning to a low-carbon economy. It calls for continued research, investment, and collaboration to unlock the full potential of CCS technologies and accelerate their deployment at scale. By embracing best practices and fostering innovation, stakeholders can pave the way for effective CO2 storage and contribute to global efforts to combat climate change. Keywords: Best Practices, Innovation, Carbon, Capture, Storage, CO2.    

    

* How much methane removal is required to avoid overshooting 1.5°C?  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399659359
:TOPICS: Anaerobic Methane Oxidation and Gas Hydrates, Carbon Dioxide Sequestration in Geological Formations, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1748-9326/ad5853")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399659359"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399659359"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399659359"))][Get cited by]]

OpenAlex: https://openalex.org/W4399659359 (Open access: True)
    
[[https://openalex.org/A5021058724][Christopher J. Smith]], [[https://openalex.org/A5049034719][Camilla Mathison]], Environmental research letters. None(None)] 2024. https://doi.org/10.1088/1748-9326/ad5853 
     
Abstract Methane is the second most important anthropogenic greenhouse gas after carbon dioxide. With an atmospheric lifetime of around a decade, methane mitigation starting immediately has the potential to avoid substantial levels of additional warming by mid-century. In addition to the methane emissions reductions that are necessary to limit warming, we address the question of whether technological methane removal can provide additional benefits by avoiding global mean surface temperatures exceeding 1.5°C above pre-industrial---the high-ambition Paris Agreement climate goal. Using an adaptive emissions methane removal routine in a simple climate model, we successfully limit peak warming to 1.5°C for overshoots of up to around 0.3°C. For substantially higher overshoots, methane removal alone is unable to limit warming to 1.5°C, but in an extreme scenario could limit peak warming by an ensemble median 0.7°C if all atmospheric methane was removed, requiring huge levels of net removal on the order of tens of petagrams cumulatively. The efficacy of methane removal depends on many emergent properties of the climate system, including climate sensitivity, aerosol forcing, and the committed warming after net zero CO$_2$ (zero emissions commitment). To avoid overshooting 1.5°C in the low-overshoot, strong-mitigation SSP1-1.9 scenario, a median cumulative methane removal of 1.2 Pg CH$_4$ is required, though this may be much higher if climate sensitivity is high or the zero emissions commitment is positive, and in these cases may require ongoing methane removal long after peak warming in order to stabilise warming below 1.5°C.    

    

* Prioritizing Target Motorcycle Owners to Promote Electric Vehicles Among Motorcycle Taxi Drivers in Bangkok  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399571013
:TOPICS: Integration of Electric Vehicles in Power Systems, Implications of Shared Autonomous Vehicle Services, Rebound Effect on Energy Efficiency and Consumption
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54028/nj202423409")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399571013"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399571013"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399571013"))][Get cited by]]

OpenAlex: https://openalex.org/W4399571013 (Open access: False)
    
[[https://openalex.org/A5058811724][Ornicha Anuchitchanchai]], [[https://openalex.org/A5028794985][Saksith Chalermpong]], Nakhara : Journal of Environmental Design and Planning. 23(2)] 2024. https://doi.org/10.54028/nj202423409 
     
Governments in many countries have announced their own emission targets and launched several measures to mitigate transport-sourced air pollution, including policies to promote the use of electric vehicles (EVs). However, electrifying a fleet of vehicles requires high investment and it is difficult to fully implement all at once. Therefore, this research aims to develop a framework to help prioritize locations to promote EVs using motorcycle taxis in Bangkok as a case study. The surveyed data was collected from 406 motorcycle taxi drivers around Bangkok. The proposed framework is based on two aspects. One is the impact on CO2 emission reduction while another is the difficulty of EV deployment. The study's findings yield a potential matrix for EV deployment, which classifies locations into four priority groups. The study concludes that prioritizing locations with high CO2 reduction impact and low deployment difficulty is crucial for efficient EV promotion. Subsequently, recommendations are offered to assist authorities and automobile firms in effectively allocating resources for EV promotion. Policy recommendations highlight the significance of targeted interventions and enhancing public awareness to facilitate the widespread adoption of electric motorcycle. Implications from this study will help the authorities and automobile firms to prioritize areas and allocate budgets for promoting EVs efficiently.    

    

* Vehicle greenhouse gas emission factors based on multi-dimensional Bin interval mode  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399503982
:TOPICS: Estimating Vehicle Fuel Consumption and Emissions, Low-Cost Air Quality Monitoring Systems, Health Effects of Air Pollution
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/e3sconf/202453601009")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399503982"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399503982"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399503982"))][Get cited by]]

OpenAlex: https://openalex.org/W4399503982 (Open access: True)
    
[[https://openalex.org/A5087647886][Rui Wu]], [[https://openalex.org/A5049341927][Hao Zhang]], [[https://openalex.org/A5003011137][Di Yang]], [[https://openalex.org/A5034531352][Yu Liu]], [[https://openalex.org/A5085779445][Hanzhengnan Yu]], [[https://openalex.org/A5008893566][X. Zhang]], [[https://openalex.org/A5080991050][Xueyin An]], [[https://openalex.org/A5073744521][Kunqi Ma]], [[https://openalex.org/A5018530246][Yongkai Liang]], [[https://openalex.org/A5068672758][Hang Xu]], E3S web of conferences. 536(None)] 2024. https://doi.org/10.1051/e3sconf/202453601009 
     
The emission factors of greenhouse gases from motor vehicles are of significant importance for low-carbon and environmentally friendly initiatives. This paper focuses on greenhouse gas emission factors of heavy-duty vehicles. The multi-dimensional Bin interval mode are proposed, which considers multiple parameters such as vehicle speed, acceleration, torque, and rotational speed. Based on this, the emission characteristics of greenhouse gases from heavy-duty vehicles. are investigated under different parameter conditions. The results indicate that as the VSPA value or the engine torque increases, the CO2 emission factor also increases accordingly. The CO2 emission factor is lower at medium to high rotational speeds, while it tends to increase at low rotational speeds. The research findings provide support for monitoring and evaluating greenhouse gas emissions and offer scientific guidance for formulating specific carbon reduction policies, emission targets, and plans.    

    

* Electrochemistry in Action: Iron and Steel Manufacturing  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399685375
:TOPICS: Hydrogen Embrittlement in Metals and Alloys
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/2.f06242if")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399685375"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399685375"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399685375"))][Get cited by]]

OpenAlex: https://openalex.org/W4399685375 (Open access: True)
    
[[https://openalex.org/A5024672881][Trevor Michael Braun]], [[https://openalex.org/A5082501161][Camilla Wallace]], [[https://openalex.org/A5024694634][Quoc Pham]], [[https://openalex.org/A5088686262][Sumit Nijhawan]], [[https://openalex.org/A5011047139][Christopher L. Alexander]], The Electrochemical Society interface. 33(2)] 2024. https://doi.org/10.1149/2.f06242if 
     
Steel is one of the most manufactured materials in modern society, with 1.9 billion metric tons produced annually for use in building materials, vehicles, wind-turbines, and appliances, among many other applications. As you might expect for something so ubiquitous, the technology used to manufacture steel is also quite mature, having been first identified over 4,000 years ago and heavily industrialized in the 19th century. The general approach is to mine iron ore from the earth’s crust and refine that ore to metallic iron (i.e., ironmaking) which is then combined with carbon and other elements to make steel products (i.e., steelmaking). However, conventional steel manufacturing relies primarily on carbon-based fuels, such as coal, to create the high temperatures (≈ 1600°C) required for the process and can emit as much as 2.2 tons of CO2 per ton of crude steel produced.1 The iron ore reduction step accounts for 90% of CO2 emissions associated with steel production. The heightened effort to decarbonize industrial process and reverse climate change is putting pressure on this 600+ year-old technology to shift to lowcarbon alternatives, especially considering that the steel industry is responsible for ≈ 7% of all global CO2 emissions annually.    

    

* The Electrochemical Peroxydisulfate-Oxalate Autocatalytic Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399632679
:TOPICS: Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-3149c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399632679"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399632679"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399632679"))][Get cited by]]

OpenAlex: https://openalex.org/W4399632679 (Open access: False)
    
[[https://openalex.org/A5031904115][Jordyn Janusz]], [[https://openalex.org/A5066171617][Joshua A. Beeler]], [[https://openalex.org/A5052306072][Seyyedamirhossein Hosseini]], [[https://openalex.org/A5029145907][Mayank Tanwar]], [[https://openalex.org/A5005365457][Rui Zeng]], [[https://openalex.org/A5026900457][Hongsen Wang]], [[https://openalex.org/A5042053197][Héctor D. Abruña]], [[https://openalex.org/A5010884148][Matthew Neurock]], [[https://openalex.org/A5057065781][Henry White]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-3149c 
     
Aqueous solutions containing both the strong oxidant, peroxydisulfate (S2O82‒), and the strong reductant, oxalate (C2O42‒), are thermodynamically unstable due to the highly exothermic homogeneous redox reaction: S2O82‒ + C2O42‒ ® 2 SO42‒ + 2 CO2 (DG0 = −490 kJ/mol). However, at room temperature, this reaction does not occur to a significant extent over the timescale of a day due to its inherently slow kinetics. We demonstrate that the S2O82‒/C2O42‒ redox reaction occurs rapidly, once initiated by the Ru(NH3)62+-mediated 1e– reduction of S2O82‒ to form S2O83•‒ at a glassy carbon electrode. Theoretically, the mediated electrochemical generation of a single molecule of S2O83•‒ is capable of initiating an autocatalytic cycle that consumes both S2O82‒ and C2O42‒ in bulk solution. Several experimental demonstrations of S2O82‒/C2O42‒ autocatalysis are presented. Differential electrochemical mass spectrometry measurements demonstrate that CO2 is generated in solution for at least 10 minutes following a 30-s initiation step during which S2O83•‒ is generated. Quantitative bulk electrolysis of S2O82‒ in solutions containing excess C2O42‒ is initiated by electrogeneration of immeasurably small quantities of S2O83•‒. Capture of CO2 as BaCO3 during electrolysis additionally confirms the autocatalytic generation of CO2. First- principles density functional theory calculations, ab initio molecular dynamics simulations, and finite difference simulations of cyclic voltammetric responses are presented that support and provide additional insights into the initiation and mechanism of the S2O82‒/C2O42‒ autocatalytic reaction. Preliminary evidence indicates that autocatalysis also results in a chemical traveling reaction front that propagates into the solution normal to the planar electrode surface.    

    

* The Electrochemical Peroxydisulfate-Oxalate Autocatalytic Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399687361
:TOPICS: Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-3149c-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399687361"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399687361"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399687361"))][Get cited by]]

OpenAlex: https://openalex.org/W4399687361 (Open access: False)
    
[[https://openalex.org/A5031904115][Jordyn Janusz]], [[https://openalex.org/A5066171617][Joshua A. Beeler]], [[https://openalex.org/A5052306072][Seyyedamirhossein Hosseini]], [[https://openalex.org/A5029145907][Mayank Tanwar]], [[https://openalex.org/A5005365457][Rui Zeng]], [[https://openalex.org/A5026900457][Hongsen Wang]], [[https://openalex.org/A5042053197][Héctor D. Abruña]], [[https://openalex.org/A5010884148][Matthew Neurock]], [[https://openalex.org/A5057065781][Henry White]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-3149c-v2 
     
Aqueous solutions containing both the strong oxidant, peroxydisulfate (S2O82‒), and the strong reductant, oxalate (C2O42‒), are thermodynamically unstable due to the highly exothermic homogeneous redox reaction: S2O82‒ + C2O42‒ ® 2 SO42‒ + 2 CO2 (DG0 = −490 kJ/mol). However, at room temperature, this reaction does not occur to a significant extent over the timescale of a day due to its inherently slow kinetics. We demonstrate that the S2O82‒/C2O42‒ redox reaction occurs rapidly, once initiated by the Ru(NH3)62+-mediated 1e– reduction of S2O82‒ to form S2O83•‒ at a glassy carbon electrode. Theoretically, the mediated electrochemical generation of a single molecule of S2O83•‒ is capable of initiating an autocatalytic cycle that consumes both S2O82‒ and C2O42‒ in bulk solution. Several experimental demonstrations of S2O82‒/C2O42‒ autocatalysis are presented. Differential electrochemical mass spectrometry measurements demonstrate that CO2 is generated in solution for at least 10 minutes following a 30-s initiation step during which S2O83•‒ is generated. Quantitative bulk electrolysis of S2O82‒ in solutions containing excess C2O42‒ is initiated by electrogeneration of immeasurably small quantities of S2O83•‒. Capture of CO2 as BaCO3 during electrolysis additionally confirms the autocatalytic generation of CO2. First- principles density functional theory calculations, ab initio molecular dynamics simulations, and finite difference simulations of cyclic voltammetric responses are presented that support and provide additional insights into the initiation and mechanism of the S2O82‒/C2O42‒ autocatalytic reaction. Preliminary evidence indicates that autocatalysis also results in a chemical traveling reaction front that propagates into the solution normal to the planar electrode surface.    

    

* Comparison of Performance and Efficiency of Different Refrigerants at High Load Conditions and their Impact on CO2eq Emissions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399595578
:TOPICS: Refrigeration Systems and Technologies, Waste Heat Recovery for Power Generation and Cogeneration, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.4271/2024-37-0029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399595578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399595578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399595578"))][Get cited by]]

OpenAlex: https://openalex.org/W4399595578 (Open access: False)
    
[[https://openalex.org/A5095934300][Christian Macrì]], [[https://openalex.org/A5050864446][Andrés León]], [[https://openalex.org/A5027903640][Felix Flohr]], SAE technical papers on CD-ROM/SAE technical paper series. None(None)] 2024. https://doi.org/10.4271/2024-37-0029 
     
<div class="section abstract"><div class="htmlview paragraph">For battery-electric vehicles (BEVs), the climate control and the driving range are crucial criteria in the ongoing electrification of automobiles in Europe towards the targeted carbon neutrality of the automotive industry. The thermal management system makes an important contribution to the energy efficiency and the cabin comfort of the vehicle. In addition to the system architecture, the refrigerant is crucial to achieve high cooling and heating performance while maintaining high efficiency and thus low energy consumption. Due to the high efficiency requirements for the vehicle, future system architectures will largely be heat pump systems.</div><div class="htmlview paragraph">The alternative refrigerant R-474A based on the molecule R-1132(E) achieved top performance for both parameters in various system and vehicle tests. An own-built energy efficiency tool was used to determine the possible energy reduction of R-474A in comparison to refrigerant alternatives that can be translated in a CO2 reduction of the thermal management as part of the overall vehicle CO2 footprint reduction.</div><div class="htmlview paragraph">The results served as the basis for an efficiency study comparing the refrigerant R-474A against systems with pure R-1234yf and R-744 in a BEV in both cooling mode (AC mode) and heating mode (HP mode). The analysis was carried out with a focus on the performance and efficiency of thermal management under different climatic conditions and considering different driving cycles. The results of the most recent investigations and the study will be presented in this paper.</div></div>    

    

* Ocean Acidification trends and Carbonate System dynamics in the North Atlantic Subpolar Gyre during 2009–2019  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399533413
:TOPICS: Impact of Ocean Acidification on Marine Ecosystems, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-2024-1388")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399533413"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399533413"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399533413"))][Get cited by]]

OpenAlex: https://openalex.org/W4399533413 (Open access: True)
    
[[https://openalex.org/A5044330844][David Curbelo-Hernández]], [[https://openalex.org/A5065552337][Fiz F. Pérèz]], [[https://openalex.org/A5050840322][Melchor González‐Dávila]], [[https://openalex.org/A5084744370][С. В. Гладышев]], [[https://openalex.org/A5069001766][Aridane G. González]], [[https://openalex.org/A5017893385][David González-Santana]], [[https://openalex.org/A5026465833][A. Velo]], [[https://openalex.org/A5001832077][Alexey Sokov]], [[https://openalex.org/A5040667699][J. Magdalena Santana-Casiano]], No host. None(None)] 2024. https://doi.org/10.5194/egusphere-2024-1388 
     
Abstract. The CO2-carbonate system dynamics in the North Atlantic Subpolar Gyre (NASPG) were evaluated between 2009 and 2019. Data was collected aboard eight summer cruises through the CLIVAR 59.5º N section. The Ocean Acidification (OA) patterns and the reduction in the saturation state of calcite (ΩCa) and aragonite (ΩArag) in response to the increasing anthropogenic CO2 (Cant) were assessed within the Irminger, Iceland and Rockall basins during a poorly-assessed decade in which the physical patterns reversed in comparison with previous well-known periods. The observed cooling, freshening and enhanced ventilation increased the interannual rate of accumulation of Cant in the interior ocean by 50–86 % and the OA rates by close to 10 %. The OA trends were 0.0013–0.0032 units yr-1 in the Irminger and Iceland basin and 0.0006–0.0024 units yr-1 in the Rockall Trough, causing a decline in ΩCa and ΩArag of 0.004–0.021 and 0.003–0.0013 units yr-1, respectively. The Cant-driven rise in total inorganic carbon (CT) was the main driver of the OA (contributed by 53–68 % in upper layers and >82 % toward the interior ocean) and the reduction in ΩCa and ΩArag (>64 %). The transient decrease in temperature, salinity and AT collectively counteracts the CT-driven acidification by 45–85 % in the upper layers and in the shallow Rockall Trough and by <10 % in the interior ocean. The present investigation reports the acceleration of the OA within the NASPG and expands knowledge about the future state of the ocean.    

    

* Performance assessment of large-scale rooftop solar PV system: a case study in a Malaysian Public University  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399664327
:TOPICS: Machine Learning Methods for Solar Radiation Forecasting, Photovoltaic Maximum Power Point Tracking Techniques, Demand Response in Smart Grids
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s42452-024-06007-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399664327"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399664327"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399664327"))][Get cited by]]

OpenAlex: https://openalex.org/W4399664327 (Open access: True)
    
[[https://openalex.org/A5074413904][Logeswaran Govindarajan]], [[https://openalex.org/A5077379711][Mohd Faizal Bin Mohideen Batcha]], [[https://openalex.org/A5003220559][Mohammad Kamil Bin Abdullah]], Deleted Journal. 6(6)] 2024. https://doi.org/10.1007/s42452-024-06007-9 
     
Abstract Adopting rooftop solar PV systems in various domestic and non-domestic sectors (including commercial, industrial, and agricultural) exhibits their commitment to green energy ventures. This study intends to evaluate the effectiveness of a grid-connected solar system that has been installed so far: a 6.9 MW p photovoltaic (PV) system implemented at University Tun Hussein Onn (UTHM) in Batu Pahat, Johor. This green energy system was installed as a part of the Self-Consumption (SELCO) program utilizing a Supply Agreement for Renewable Energy (SARE) contract. To assess the mounted energy system's efficiency, performance monitoring was carried out between December 2021 and November 2022. By evaluating the enactment of the 6.9 MW p solar system at UTHM, this present work has attempted to compile the achievement of implementation of self-consumption in terms of performance analysis and financial benefits to consumer. Based on International Electrotechnical Commission (IEC) 61724 standard, this study also investigates several performance characteristics of the PV system, such as final yield, clearness index (CI), array yield, PV module efficiency, inverter efficiency, reference yield, and capacity factor (CF) performance ratio (PR). Moreover, an assessment of Carbon Dioxide ( $${CO}_{2})$$     CO  2   )    avoidance was also conducted to quantify the amount of $${CO}_{2}$$    CO  2   reduction achieved. In addition, the self-consumption ratio and self-sufficiency ratio pattern for solar power plant in UTHM has been assessed. The monthly clearness index at the project location from December 2021 to November 2022 ranges from 0.63 to 0.66. The PV system was monitored throughout this time and generated 8529 MWh of energy. The installed PV system has shown an efficiency of 11.86%, a final yield of 108.28%, and a PR of 0.78, respectively. Further, the installed 6.9 MW p PV system at UTHM will cut $${CO}_{2}$$    CO  2   emissions by 5450 tons annually. The 6.9 MWp solar PV system is also estimated to reduce 25.1 RM mil in 25 years. Making the system larger to 6.9 MW p would reduce the consumption from the grid during the week, makes it possible to achieve self-consumption levels of up to 100% and self-sufficiency of this solar plant is relatively low ranges from 22 to 35%. The research finding bridges the gap between policy makers, investors, and the public regarding acceptance of the large-scale Self-Consumption (SELCO) and strengthen the strategic collaborations between solar service provider and educational bodies to support of the government’s agenda to achieve carbon emission intensity reduction in Malaysia. Graphical Abstract    

    

* Long-Term Forecast of Energy Demand towards a Sustainable Future in Renewable Energies Focused on Geothermal Energy in Peru (2020–2050): A LEAP Model Application  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399549406
:TOPICS: Global Energy Transition and Fossil Fuel Depletion, Electricity Price and Load Forecasting Methods, Rebound Effect on Energy Efficiency and Consumption
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16124964")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399549406"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399549406"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399549406"))][Get cited by]]

OpenAlex: https://openalex.org/W4399549406 (Open access: True)
    
[[https://openalex.org/A5073487939][D. Torres]], [[https://openalex.org/A5049759654][Luis Felipe Mazadiego]], [[https://openalex.org/A5026422831][David Bolonio]], [[https://openalex.org/A5042111418][Ramón Rodríguez Pons-Esparver]], Sustainability. 16(12)] 2024. https://doi.org/10.3390/su16124964 
     
The present study aims to describe the potential sources of energy in Peru with the purpose of implementing them to achieve a sustainable system, taking advantage of the natural resources in the Peruvian land. To achieve this, three alternative scenarios have been defined and analyzed using the LEAP (Long-range Energy Alternatives Planning) software [Software Version: 2020.1.112]. The scenarios are as follows: the first one, the Business-as-Usual scenario, is based on normal trends according to historical data and referencing projections made by Peruvian state entities; the second one is focused on Energy Efficiency, the highlighted characteristic is taking into consideration the efficient conditions in transmission and distribution of electric energy; and the third one, centered on Geothermal Energy, focused on the development of this type of energy source and prioritizing it. The primary purpose of this analysis is to identify the advantages and disadvantages inherent in each scenario in order to obtain the best out of each one. In this way, the intention is to propose solutions based on Peru’s national reality or possible uses of the country’s energy potential to supply its energy demand. Currently, Peru’s energy demand relies on fossil fuels, hydraulic, and thermal energy. However, there is the possibility of transforming this system into a sustainable one by strengthening existing and growing energy sources such as solar and wind energy and new technologies for hydraulic and thermal energy, in addition to considering geothermal energy as the main energy source in the third scenario. The new system mentioned satisfactorily indicates that the CO2 equivalent emissions decrease significantly in the third scenario, with a 15.8% reduction compared to the first scenario and a 9.7% reduction in comparison to the second. On the other hand, the second scenario shows a 5.6% decrease in CO2 emissions compared to the first, resulting from improvements in technology and energy efficiency without requiring significant modifications or considerable investments, as in the third scenario.    

    

* Popularity-based Alternative Routing  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399554778
:TOPICS: Content-Centric Networking for Information Delivery, Scalable Peer-to-Peer Network Architectures, Cooperative Diversity in Wireless Networks
:PUBLICATION_DATE: 2024-06-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2406.05388")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399554778"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399554778"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399554778"))][Get cited by]]

OpenAlex: https://openalex.org/W4399554778 (Open access: True)
    
[[https://openalex.org/A5081445152][Giuliano Cornacchia]], [[https://openalex.org/A5099097159][Ludovico Lemma]], [[https://openalex.org/A5068819495][Luca Pappalardo]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2406.05388  ([[https://arxiv.org/pdf/2406.05388][pdf]])
     
Alternative routing is crucial to minimize the environmental impact of urban transportation while enhancing road network efficiency and reducing traffic congestion. Existing methods neglect information about road popularity, possibly leading to unintended consequences such as increasing emissions and congestion. This paper introduces Polaris, an alternative routing algorithm that exploits road popularity to optimize traffic distribution and reduce CO2 emissions. Polaris leverages the novel concept of K-road layers, which mitigates the feedback loop effect where redirecting vehicles to less popular roads could increase their popularity in the future. We conduct experiments in three cities to evaluate Polaris against state-of-the-art alternative routing algorithms. Our results demonstrate that Polaris significantly reduces the overuse of highly popular road edges and traversed regulated intersections, showcasing its ability to generate efficient routes and distribute traffic more evenly. Furthermore, Polaris achieves substantial CO2 reductions, outperforming existing alternative routing strategies. Finally, we compare Polaris to an algorithm that coordinates vehicles centrally to distribute them more evenly on the road network. Our findings reveal that Polaris performs comparably well, even with much less information, highlighting its potential as an efficient and sustainable solution for urban traffic management.    

    

* A Review of Coupled Geochemical–Geomechanical Impacts in Subsurface CO2, H2, and Air Storage Systems  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399674927
:TOPICS: Carbon Dioxide Sequestration in Geological Formations, Anaerobic Methane Oxidation and Gas Hydrates, Groundwater Flow and Transport Modeling
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17122928")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399674927"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399674927"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399674927"))][Get cited by]]

OpenAlex: https://openalex.org/W4399674927 (Open access: True)
    
[[https://openalex.org/A5047887437][Zhongyuan Shi]], [[https://openalex.org/A5052938557][Dejene Legesse Driba]], [[https://openalex.org/A5044230029][Nora Lopez Rivera]], [[https://openalex.org/A5099129745][Mohammad Kariminasab]], [[https://openalex.org/A5076624104][Lauren E. Beckingham]], Energies. 17(12)] 2024. https://doi.org/10.3390/en17122928 
     
Increased demand for decarbonization and renewable energy has led to increasing interest in engineered subsurface storage systems for large-scale carbon reduction and energy storage. In these applications, a working fluid (CO2, H2, air, etc.) is injected into a deep formation for permanent sequestration or seasonal energy storage. The heterogeneous nature of the porous formation and the fluid–rock interactions introduce complexity and uncertainty in the fate of the injected component and host formations in these applications. Interactions between the working gas, native brine, and formation mineralogy must be adequately assessed to evaluate the efficiency, risk, and viability of a particular storage site and operational regime. This study reviews the current state of knowledge about coupled geochemical–geomechanical impacts in geologic carbon sequestration (GCS), underground hydrogen storage (UHS), and compressed air energy storage (CAES) systems involving the injection of CO2, H2, and air. Specific review topics include (1) existing injection induced geochemical reactions in these systems; (2) the impact of these reactions on the porosity and permeability of host formation; (3) the impact of these reactions on the mechanical properties of host formation; and (4) the investigation of geochemical-geomechanical process in pilot scale GCS. This study helps to facilitate an understanding of the potential geochemical–geomechanical risks involved in different subsurface energy storage systems and highlights future research needs.    

    

* Cooperative Effects Associated with High Electrolyte Concentrations in Driving the Conversion of CO2 to C2H4 on Copper  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399687053
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-03mmk")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399687053"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399687053"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399687053"))][Get cited by]]

OpenAlex: https://openalex.org/W4399687053 (Open access: False)
    
[[https://openalex.org/A5076931064][Shupeng Lin]], [[https://openalex.org/A5032718016][Yuval Fishler]], [[https://openalex.org/A5065096122][Soonho Kwon]], [[https://openalex.org/A5083167782][Annette Böhme]], [[https://openalex.org/A5049208393][Weixuan Nie]], [[https://openalex.org/A5072433173][Matthias H. Richter]], [[https://openalex.org/A5012227349][Moon Young Yang]], [[https://openalex.org/A5038044828][Jesse E. Matthews]], [[https://openalex.org/A5024067271][Zachery W. B. Iton]], [[https://openalex.org/A5082975824][Brian C. Lee]], [[https://openalex.org/A5078810774][Thomas F. Jaramillo]], [[https://openalex.org/A5082887836][Harry A. Atwater]], [[https://openalex.org/A5035627473][William A. Goddard]], [[https://openalex.org/A5033181239][Wilson A. Smith]], [[https://openalex.org/A5049886971][Kimberly A. See]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-03mmk 
     
Increasing the product selectivity and decreasing the cost of product separation is critical for large scale application of electrochemical CO2 reduction (ECO2R). We hypothesize that highly concentrated aqueous electrolytes can tune the microenvironment of the catalyst/electrolyte interface and improve product selectivity. Compared to a conventional electrolyte concentration of 1 M HCOOK, the use of a 7.1 M HCOOK electrolyte increases the FE ratio of C2H4/CO from 2.2 ± 0.3 to 18.3 ± 4.8 at -1.08 V vs RHE on a Cu gas diffusion electrode. Based on electrochemical analysis and AIMD simulation, the identity and concentration of the cation and anion play more important roles in controlling the CO2R reaction pathway than the bulk CO2 solubility and the bulk pH of electrolytes. In-situ ATR-SEIRAS suggests that, unlike 1 M HCOOK, the *CO-bridge binding mode on Cu is dominant in 7.1 M HCOOK electrolyte, which potentially results in less CO release and higher yield of C2H4. This study demonstrates that while we can tailor the electrolyte composition to shift product selectivity, the factors that control the product selectivity are numerous and cannot be distilled down into one correlated property-reactivity relationship. Thus, when CO2R conditions are changed, care must be taken to understand their effects on the bulk electrolyte properties and the electrode-electrolyte interface.    

    

* Investigating the effect of silicate- and calcium-based ocean alkalinity enhancement on diatom silicification  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399577788
:TOPICS: Biomimetic Nanotechnology in Material Synthesis and Assembly, Paleoredox and Paleoproductivity Proxies, Marine Biogeochemistry and Ecosystem Dynamics
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/bg-21-2777-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399577788"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399577788"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399577788"))][Get cited by]]

OpenAlex: https://openalex.org/W4399577788 (Open access: True)
    
[[https://openalex.org/A5058513768][Aaron Ferderer]], [[https://openalex.org/A5091734550][Kai G. Schulz]], [[https://openalex.org/A5005675240][Ulf Riebesell]], [[https://openalex.org/A5064341925][Kirralee G. Baker]], [[https://openalex.org/A5008038356][Zanna Chase]], [[https://openalex.org/A5044360827][Lennart T. Bach]], Biogeosciences. 21(11)] 2024. https://doi.org/10.5194/bg-21-2777-2024 
     
Abstract. Gigatonne-scale atmospheric carbon dioxide removal (CDR) will almost certainly be needed to supplement the emission reductions required to keep global warming between 1.5–2 °C. Ocean alkalinity enhancement (OAE) is an emerging marine CDR method with the addition of pulverised minerals to the surface ocean being one widely considered approach. A concern of this approach is the potential for dissolution products released from minerals to impact phytoplankton communities. We conducted an experiment with 10 pelagic mesocosms (M1–M10) in Raunefjorden, Bergen, Norway, to assess the implications of simulated silicate- and calcium-based mineral OAE on a coastal plankton community. Five mesocosms (M1, M3, M5, M7, and M9) were enriched with silicate (∼ 75 µmol L−1 Na2SiO3), alkalinity along a gradient from 0 to ∼ 600 µmol kg−1, and magnesium in proportion to alkalinity additions. The other five mesocosms (M2, M4, M6, M8, M10) were enriched with alkalinity along the same gradient and calcium in proportion to alkalinity additions. The experiment explored many components of the plankton community, from microbes to fish larvae, and here we report on the influence of simulated mineral based OAE on diatom silicification. Macronutrients (nitrate and phosphate) limited silicification at the onset of the experiment until nutrient additions on day 26. Silicification was significantly greater in the silicate-based mineral treatment, with all genera except Cylindrotheca displaying an increase in silicification as a result of the increased concentration of dissolved silicate. In contrast to the effect of differences in dissolved silicate concentrations between the two mineral treatments, increases in alkalinity only influenced the silicification of two genera, Pseudo-nitzschia and Nitzschia. The four other genera (Arcocellulus, Cylindrotheca, Skeletonema, and Thalassiosira) investigated here displayed no significant changes in silicification as a result of alkalinity increases between 0 and 600 µmol kg−1 above natural levels. In summary, our findings illustrate that the enhancement of alkalinity via simulated silicate- and calcium-based methods has limited genus-specific impacts on the silicification of diatoms. This research underscores the importance of understanding the full breadth of different OAE approaches, their risks, co-benefits, and potential for interactive effects.    

    

* Pursuing Optimization Using Multimodal Transportation System: A Strategic Approach to Minimizing Costs and CO2 Emissions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399580807
:TOPICS: Implications of Shared Autonomous Vehicle Services, Understanding Attitudes Towards Public Transport and Private Car, Vehicle Routing Problem and Variants
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/jmse12060976")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399580807"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399580807"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399580807"))][Get cited by]]

OpenAlex: https://openalex.org/W4399580807 (Open access: True)
    
[[https://openalex.org/A5079737344][Iván Dérpich]], [[https://openalex.org/A5084028209][Claudia Durán]], [[https://openalex.org/A5067154685][Raúl Carrasco]], [[https://openalex.org/A5038559230][Fabricio Moreno]], [[https://openalex.org/A5052149736][Christian Fernández‐Campusano]], [[https://openalex.org/A5084647245][Leonardo Espinosa-Leal]], Journal of marine science and engineering. 12(6)] 2024. https://doi.org/10.3390/jmse12060976 
     
The core problem of a multimodal transportation system is integrating various transportation modes into a cohesive, efficient, and user-friendly network. This study introduces a novel centralized load concentration approach for regions facing geographic challenges. The principal aim is improving multimodal transportation systems by mitigating CO2 emissions and improving operational efficiency. This will significantly reduce high logistics costs and the environmental impact caused by greenhouse gas emissions, particularly in land transportation, aligning with the global sustainable development goals and offering a promising path towards a more sustainable future. The proposed method implicates direct cargo transportation from its origin to the export ports without passing through intermediate centers. The mathematical model determines the most efficient means of transportation for each route, considering variables such as distance, volume, and type of cargo. Research results indicate that multiple hubs may not be necessary in scenarios with high freight concentration, which could streamline transportation and logistics operations. The modal preferences vary depending on regional dynamics and cargo characteristics, with rail and sea transport emerging as preferable options in specific circumstances, outperforming road transport. The proposed model shows reductions in logistics costs and CO2 emissions compared to road-focused scenarios. This study provides an adaptable framework for optimizing multimodal transportation systems in regions with similar geographic and logistical attributes. It offers a versatile solution to various contexts and needs. Lastly, the strategic integration of multiple modes of transportation is fundamental to improving efficiency and sustainability.    

    

* The Reusage of Different Wastes by Using the Multiple’s Effect Technique for Sustainable Gasoline Production  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399623909
:TOPICS: Inverse Radiative Heat Transfer Analysis, Applications of Infrared Thermography in Non-Destructive Testing
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.17344/acsi.2024.8714")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399623909"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399623909"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399623909"))][Get cited by]]

OpenAlex: https://openalex.org/W4399623909 (Open access: False)
    
[[https://openalex.org/A5047238174][Anita Kovač Kralj]], Acta chimica slovenica. 71(2)] 2024. https://doi.org/10.17344/acsi.2024.8714 
     
The unused garbage which is accumulating the landfills, such as raw materials, could be reused for synthetic gasoline production. This study presents the multiple’s effect technique, which is based on the reusage of different non, party and sorted municipal solid wastes (MSW), or biogas for syngas, converted into synthetic gasoline. The novelties of this technique include a basic multiple’s effect parameter (MUW), which present a level of waste sorting, an effect of oxygen inhibition into different wastes, a simplified mathematical model and simulation with an Aspen Plus® simulator using the retrofitted methanol plan converted into the synthetic gasoline production. This technique includes a circular economy by using a circulated purified flue gas as raw material, co-products of hydrogen and water. This technique was tested on an existing methanol process, replacing natural gas with different alternatives of wastes or biogas for the synthetic gasoline production. The best alternative was the sorted MSW, which could generate an additional profit of 4.8 MEUR/a, including the garbage and CO2 emission reductions of 0.106·106 t/a and of 0.084 ·106 t/a.    

    

* Reduced A–B super exchange interaction in zirconium doped cobalt ferrite due to laser irradiation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399518339
:TOPICS: Synthesis and Applications of Ferrite Nanoparticles, Mechanical Properties of Metallic Glasses, Magneto-Optical Devices for Integrated Photonics
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1402-4896/ad56db")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399518339"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399518339"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399518339"))][Get cited by]]

OpenAlex: https://openalex.org/W4399518339 (Open access: False)
    
[[https://openalex.org/A5084406171][Ebtesam E. Ateia]], [[https://openalex.org/A5089402536][Nahla Fangary]], [[https://openalex.org/A5094002087][Dalia N. Ghafar]], Physica scripta. None(None)] 2024. https://doi.org/10.1088/1402-4896/ad56db 
     
Abstract The impact of Nd:YAG laser irradiation and the addition of zirconium ions (Zr4+) on the physical properties of CoFe2O4 spinel nano-ferrites has been studied. The co-precipitation method was used to synthesize the samples. Xray diffraction (XRD) and high-resolution transmission electron microscopy (HRTEM) were employed to examine the structure and morphology. The decrease in the Curie temperature Tc is due to the laser irradiation and the increase in the Zr content of the sample. The difference in the Tc between the non irradiated and the irradiated samples is about 7%, 43% and 34% for CoFe2O4, Co1.1Zr0.1Fe1.8O4, and Co1.3Zr0.3Fe1.4O4, respectively. The decrease in the Tc is due to an increase in the canting of the spins, resulting in a decreased thermal energy required to compensate for the spin alignment. The decrease in the coercivity of the laser irradiated sample is due to a reduction in the magnetic anisotropy and an altered distribution of the cations (Co2+, Fe3+, Zr4+). The observed trend indicates that laser irradiation, and Zr substitution, can be used to modify the magnetic hardness of the samples. The low coercivity of irradiated Co1.1Zr0.1Fe1.8O4 makes it suitable for a range of applications. The high-frequency response of the Co1+xZrxFe2-2xO4 NPs shows that they can operate within the frequency range of 7.5 GHz–11.56 GHz.&#xD;    

    

* Apolipoproteins and Its Association with Dengue Virus Serotype 2 (DENV-2) Infectivity in Human Hepatoma Cell Line (Huh7)  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399546028
:TOPICS: Hepatitis C Infection and Treatment, Epidemiology and Management of NAFLD
:PUBLICATION_DATE: 2024-04-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48048/tis.2024.7674")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399546028"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399546028"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399546028"))][Get cited by]]

OpenAlex: https://openalex.org/W4399546028 (Open access: False)
    
[[https://openalex.org/A5090896822][Rohani Ahmad]], [[https://openalex.org/A5082174679][Fadzilah Mohd Nor]], [[https://openalex.org/A5039806067][Seok Mui Wang]], [[https://openalex.org/A5059996506][Aletza Mohd Ismail]], [[https://openalex.org/A5099093998][Julina@Azimah Md Noor]], [[https://openalex.org/A5081597818][Thuhairah Hasrah Abdul Rahman]], Trends in Sciences. 21(7)] 2024. https://doi.org/10.48048/tis.2024.7674 
     
Introduction: Previous studies have shown that lipid components are involved in the internalization of Dengue virus (DENV), however, this mechanism has been hypothesized mostly through clinical studies correlating between dengue severity and lipid levels. This study aimed to determine DENV-2 internalization in the presence of apolipoprotein A1 (apoA1), B (apoB) or E (apoE) in human hepatoma cell line (Huh7). Materials and methods: Tetrazolium reduction assays were used to assess the cytotoxicity of apolipoproteins on Huh7. DENV-2 at MOI of 1 with 2 µg/mL apoA1, apoB and apoE, respectively were introduced into the confluent Huh7 cells and incubated for an hour (internalization) and 72 h (replication) at 37 °C, 5 % CO2. The replication experiments were repeated after SR-B1 siRNA treatment. Samples collected were subjected to qPCR for viral load determination. Differences between groups were assessed by ANOVA and independent T-Test. Results and discussion: Treatment with apoA1 and apoB demonstrated significant increment in DENV-2 internalization and replication compared to apoE (internalization: p = 0.022 and p = 0.323 vs p = 0.878, respectively; replication: p = 0.004 and p = 0.016 vs p = 0.897, respectively). A significant reduction of DENV2 infectivity was seen in apoA1 treated cells with SR-B1 down-regulation/silencing (35.2 % reduction, p = 0.013). Conclusions: apoA1 and apoB, enhanced initial attachment of DENV-2 to cell surface, suggesting their role in DENV internalization and infectivity. HIGHLIGHTS This research determined the effects of apolipoproteins on dengue virus serotype 2 (DENV-2) internalization in vitro using the human hepatoma cell line (Huh7) apoA1 and apoB enhance the initial attachment of DENV-2 to the cell surface Knockdown of SR-B1 receptors reduces apoA1-treated DENV-2 internalization, suggesting the role of SR-B1 as a route of entry for DENV-2 Knockdown of SR-B1 receptors had no effect on apoB-treated DENV-2 internalization, suggesting it uses another entry pathway GRAPHICAL ABSTRACT    

    

* Influence of Intake Charge Temperature and EGR Rate on the Combustion and Emission Characteristics of Ammonia/Diesel Dual-Fuel Engine  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399596225
:TOPICS: Chemical Kinetics of Combustion Processes, Estimating Vehicle Fuel Consumption and Emissions, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.4271/2024-37-0025")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399596225"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399596225"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399596225"))][Get cited by]]

OpenAlex: https://openalex.org/W4399596225 (Open access: False)
    
[[https://openalex.org/A5062465919][Marziyeh Hoseinpour]], [[https://openalex.org/A5003214578][Rahim Karami]], [[https://openalex.org/A5021792048][Mohammad Mahdi Salahi]], [[https://openalex.org/A5061889308][Amin Mahmoudzadeh Andwari]], [[https://openalex.org/A5001911763][Ayat Gharehghani]], [[https://openalex.org/A5070416857][Antonio G. Garcı́a]], SAE technical papers on CD-ROM/SAE technical paper series. None(None)] 2024. https://doi.org/10.4271/2024-37-0025 
     
<div class="section abstract"><div class="htmlview paragraph">Ammonia has emerged as a promising carbon-free alternative fuel for internal combustion engines (ICE), particularly in large-bore engine applications. However, integrating ammonia into conventional engines presents challenges, prompting the exploration of innovative combustion strategies like dual-fuel combustion. Nitrous oxide (N<sub>2</sub>O) emissions have emerged as a significant obstacle to the widespread adoption of ammonia in ICE. Various studies suggest that combining exhaust gas recirculation (EGR) with adjustments in inlet temperature and diesel injection timing can effectively mitigate nitrogen oxides (NO<sub>x</sub>) emissions across diverse operating conditions in dual-fuel diesel engines. This study conducts a numerical investigation into the impact of varying inlet charge temperatures (330K, 360K, and 390K) and EGR rates (0%, 10%, and 20%) on the combustion and emission characteristics of an ammonia/diesel dual-fuel engine operating under high-load conditions, while considering different shares of ammonia energy. Computational fluid dynamics (CFD) simulations are executed using Converge software. Subsequently, multi-linear regression models are developed, utilizing ammonia share, inlet charge temperature, and EGR rate as independent variables, and emission parameters as dependent variables. The best-fitted regression model can be employed to analyze the response surface of performance parameters. The optimal CO2 reduction, approximately 30%, is observed under the conditions of (390K, 40% NH<sub>3</sub>, and EGR20), as indicated by the results. Furthermore, under the conditions of (360K, 20% NH<sub>3</sub>, and EGR20), the findings indicate a notable reduction of NO<sub>2</sub>, approximately 65% compared to diesel. Additionally, the findings suggest that NH<sub>3</sub> reduction peaks at higher temperatures, with approximately a 50% decrease observed.</div></div>    

    

* A Comprehensive Overview of Recycled Glass as Mineral Admixture for Circular UHPC Solutions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399670215
:TOPICS: Geopolymer and Alternative Cementitious Materials, Utilization of Waste Materials in Construction and Ceramics, Fiber Reinforced Concrete in Civil Engineering
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16125077")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399670215"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399670215"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399670215"))][Get cited by]]

OpenAlex: https://openalex.org/W4399670215 (Open access: True)
    
[[https://openalex.org/A5099128512][N. Marcela Redondo-Pérez]], [[https://openalex.org/A5076334070][Jesús D. Redondo-Mosquera]], [[https://openalex.org/A5006737973][Joaquín Abellán García]], Sustainability. 16(12)] 2024. https://doi.org/10.3390/su16125077 
     
This review article analyzes the influence of recycled glass (as sand and powder) beyond the durability, rheology and compressive strength of plain UHPC, even exploring flexural and direct tensile performance in fiber-reinforced UHPC. Interactions with other mineral admixtures like limestone powder, rice husk ash, fly ash, FC3R, metakaolin and slags, among others, are analyzed. Synergy with limestone powder improves rheology, reducing superplasticizer usage. Research highlights waste glass–UHPC mixtures with reduced silica fume and cement content by over 50% and nearly 30%, respectively, with compressive strengths exceeding 150 MPa, cutting costs and carbon footprints. Furthermore, with the proper fiber dosage, waste glass–UHPC reported values for strain and energy absorption capacity, albeit lower than those of traditional UHPC formulations with high cement, silica fume and quartz powder content, surpassing requirements for demanding applications such as seismic reinforcement of structures. Moreover, durability remains comparable to that of traditional UHPC. In addition, the reported life cycle analysis found that the utilization of glass powder in UHPC allows a greater reduction of embedded CO2 than other mineral additions in UHPC without jeopardizing its properties. In general, the review study presented herein underscores recycled glass’s potential in UHPC, offering economic and performance advantages in sustainable construction.    

    

* Binary and Ternary Blended Portland Cements Containing Different Types of Rice Husk Ash  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399670703
:TOPICS: Characterization and Behavior of Nuclear Graphite Materials, 3D Concrete Printing Technology, Geopolymer and Alternative Cementitious Materials
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ma17122923")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399670703"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399670703"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399670703"))][Get cited by]]

OpenAlex: https://openalex.org/W4399670703 (Open access: True)
    
[[https://openalex.org/A5039867334][Luis Miguel Ordoñez]], [[https://openalex.org/A5050610898][M.V. Borrachero]], [[https://openalex.org/A5015051539][J. Monzó]], [[https://openalex.org/A5032063816][Lourdes Soriano]], [[https://openalex.org/A5053728933][J. Payá]], Materials. 17(12)] 2024. https://doi.org/10.3390/ma17122923 
     
Rice husk ash (RHA) is agricultural waste with high silica content that has exhibited proven technical feasibility as a pozzolanic material since the 1970s. Notwithstanding, its use in mortars and concrete is limited by the standards currently utilized in some countries where RHA production is high and the aforementioned pozzolanic material is not standardized. This is the case in Spain, one of the main rice producers in Europe. Nowadays, the high pressure placed on the Portland cement production sector to reduce its energy use and CO2 emissions has given rise to a keen interest in mineral admixtures for cement manufacturing. In this research, we intended to establish the contributions of different RHA types to the final blended Portland cement properties (“H” is used to identify RHA in standardized cements). The experimental results demonstrated that RHA with good pozzolanic properties (large specific surface and high amorphous silica content) had to be limited to 10% cement replacement because of the severe reduction in workability at higher replacement percentages. RHA with lower reactivity, such as crystalline RHA, or fly ash (FA) can be used to prepare binary and ternary blended cements with reactive RHA. It is possible to design the following cements: CEM II/A-H and CEM II/A-(H-V). It would also be possible to design cement (CEM II/B-(H-V) with replacement values of up to 30% and the same 28-day mechanical performance as observed for the Portland cement without mineral addition.    

    

* Interannual Evolution Characteristics of the Carbon and Nitrogen Footprints of Maize Production in Inner Mongolia  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399644943
:TOPICS: Soil Carbon Dynamics and Nutrient Cycling in Ecosystems, Meta-analysis in Ecology and Agriculture Research
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/agronomy14061273")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399644943"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399644943"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399644943"))][Get cited by]]

OpenAlex: https://openalex.org/W4399644943 (Open access: True)
    
[[https://openalex.org/A5043317691][Hongwei Liang]], [[https://openalex.org/A5059435172][Zhipeng Cheng]], [[https://openalex.org/A5010030040][Ran Zhao]], [[https://openalex.org/A5032047058][Fugui Wang]], [[https://openalex.org/A5084673041][Haibo Shi]], [[https://openalex.org/A5066841303][Y.H. Li]], [[https://openalex.org/A5062985674][Zhen Wang]], [[https://openalex.org/A5067005020][Lanfang Bai]], [[https://openalex.org/A5038714931][Yongqiang Wang]], [[https://openalex.org/A5034294746][Jing Zhang]], [[https://openalex.org/A5089855815][Xiaoling Jin]], [[https://openalex.org/A5038127795][Zhigang Wang]], Agronomy. 14(6)] 2024. https://doi.org/10.3390/agronomy14061273 
     
As the third-largest maize-producing province in China and a typical arid and semi-arid region, quantitatively evaluating the carbon and nitrogen footprints of maize production and their dominant factors is of great significance in guiding the high-yield, low-carbon, and sustainable development of maize production in the Inner Mongolia Autonomous Region. This study quantitatively evaluated the interannual evolution characteristics of the carbon and nitrogen footprints in maize production and their dominant factors in Inner Mongolia from 2003 to 2022 based on statistical yearbook data and emission parameter models. The results showed that from 2003 to 2022, the maize planting area, yield, and total yield in Inner Mongolia all increased, with an average annual increase of 97 kg ha−1 in yield and 1.23 × 106 Mg in total yield. The carbon and nitrogen footprints of Inner Mongolia maize production over the past 20 years had overall decreasing trends, while the nitrogen fertilizer bias productivity, net ecosystem carbon balance, and sustainability index had increasing trends. Carbon footprint reduced by an average of 5.2 kg CO2 eq Mg−1 per year, and nitrogen footprint reduced by an average of 0.21 g N eq kg−1 per year. Currently, the transportation and production of fertilizer and field application of N fertilizer are the main controlling factors of GHG emissions from maize production. NO3−-N, NH4+-N leaching, and NH3 volatilization from field application of N fertilizer are the main sources of reactive N losses. The application of simplified processes, such as phased regulation of nitrogen and controlled-release fertilizers, as well as conservation tillage, have broad prospects for emission reduction in maize production in Inner Mongolia.    

    

* 1512-P: Brown Adipose NMNAT1 Is Necessary for Maintaining NAD+ Levels but Dispensable for Systemic Energy Metabolism  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4399692621
:TOPICS: Effects of Ketogenic Diet on Health
:PUBLICATION_DATE: 2024-06-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2337/db24-1512-p")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399692621"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399692621"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399692621"))][Get cited by]]

OpenAlex: https://openalex.org/W4399692621 (Open access: False)
    
[[https://openalex.org/A5006869577][Xizhong Shen]], [[https://openalex.org/A5041860600][Wook Song]], [[https://openalex.org/A5066853006][Yang Cao]], [[https://openalex.org/A5020730237][Xiuxiang Jiao]], [[https://openalex.org/A5074231648][Youwen Zhu]], [[https://openalex.org/A5008816660][Cholsoon Jang]], [[https://openalex.org/A5008735436][Qin Yang]], Diabetes. 73(Supplement_1)] 2024. https://doi.org/10.2337/db24-1512-p 
     
Brown adipose tissue (BAT) is rich in mitochondria and expresses high levels of uncoupling protein 1 (UCP1), enabling it to regulate thermogenesis and system energy expenditure. NAD+ (nicotinamide adenine dinucleotide) is a key cofactor for maintaining mitochondrial function by serving as a redox carrier and signaling molecule. To investigate the regulation and function of NAD+ in BAT, we measured the expression of genes involved in NAD+ synthesis and catabolism in mice under room temperature, cold challenge, and thermoneutral conditions. We found that the expression of nicotinamide nucleotide adenylyltransferase 1 (NMNAT1), the final enzyme for NAD+ synthesis, was suppressed by thermoneutrality and increased by cold challenge in BAT. We, therefore, generated brown adipocyte-specific NMNAT1 knockout mice (NMNAT1-bKO) by crossing the NMNAT1 flox/flox mice to the UCP1-Cre mice. NMNAT1 deletion reduced NAD+ levels by approximately 50%, accompanied by the accumulated precursors, including NMN and NaMN in BAT. Despite the significant reduction of BAT NAD+, NMNAT1-bKO mice showed comparable body weight, normal glucose tolerance and insulin sensitivity, and unchanged systemic energy metabolism, including O2 consumption, CO2 production, and RER in the metabolic cage studies. Further cold challenges and high-fat diet feeding did not induce any differences in the metabolic phenotype. RNA-seq analysis of BAT from NMNAT1-bKO and control mice under cold challenge revealed enrichment of genes involved in mitochondrial function and lipid metabolic process. These results show that BAT NMNAT1 is necessary for maintaining NAD+ levels but dispensable for systemic energy metabolism, possibly due to compensatory upregulation of mitochondrial genes. Disclosure X. Shen: None. W. Song: None. Y. Cao: None. X. Jiao: None. Y. Zhu: None. C. Jang: None. Q. Yang: None. Funding National Institutes of Health (R01DK121146)    

    
