#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Thu Oct  3 01:20:12 2024

Found 75 results from 2024-09-26 to 2024-10-03
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Nickel (II) Tetradentate Complexes Bearing NHC-Pyridyl Derived Ligands for Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402845611
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-f9djd")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402845611"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402845611"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402845611"))][Get cited by]]

OpenAlex: https://openalex.org/W4402845611 (Open access: False)
    
[[https://openalex.org/A5028441979][Sonya Y. Manafe]], [[https://openalex.org/A5099161410][Gbolagade Olajide]], [[https://openalex.org/A5015730401][Chance M. Boudreaux]], [[https://openalex.org/A5069899755][Fengrui Qu]], [[https://openalex.org/A5032057054][Logan M. Whitt]], [[https://openalex.org/A5107506021][Patrick D. Pridemore]], [[https://openalex.org/A5078519756][James Fletcher Hall]], [[https://openalex.org/A5075727054][Tibor Szilvási]], [[https://openalex.org/A5063607848][Elizabeth T. Papish]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-f9djd 
     
Nickel (II) complexes bearing tetradentate NCCN ligands comprised of optionally protic pyridine and N-heterocyclic carbene (NHC) donors have been synthesized and used as catalysts for carbon dioxide reduction. These complexes were synthesized bearing OMe, OBn, or OH substituents on the pyridine rings and were characterized by 1H NMR, 13C NMR, UV-Vis, IR, HR-MS, and single crystal X-ray diffraction. The OH substituent was partially deprotonated as shown by the crystal structure. Electrochemical studies show that these nickel complexes undergo two electron reduction events prior to CO2 reduction. Catalytic current enhancement under CO2 relative to N2 is not observed under dry conditions, but the addition of proton sources leads to modest current enhancement (icat/ip < 2). Visible light driven photochemical CO2 reduction with a photosensitizer (Ir(ppy)3 where ppy = 2-phenylpyridine) and sacrificial electron and proton donors was studied, and formate is the major product with ~10:1 formate to CO production. Electron donor groups (OMe, OBn, OH) do not enhance formate production (relative to H analog), and CO production is only slightly enhanced. Overall with Ni(II), the tetradentate ligands are comparable to recently published pincer ligands for sensitized CO2 reduction, but pincer ligands offer a clear advantage in self-sensitized catalysis.    

    

* Heterometallic Transition Metal Oxides Containing Lewis Acids as Molecular Catalysts for the Reduction of Carbon Dioxide to Carbon Monoxide with Bimodal Activity  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402857418
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c10412")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402857418"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402857418"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402857418"))][Get cited by]]

OpenAlex: https://openalex.org/W4402857418 (Open access: True)
    
[[https://openalex.org/A5029669152][Dima Azaiza‐Dabbah]], [[https://openalex.org/A5061595404][Fei Wang]], [[https://openalex.org/A5105520601][E. Sideras Haddad]], [[https://openalex.org/A5086372340][Albert Solé‐Daura]], [[https://openalex.org/A5082386529][Raanan Carmieli]], [[https://openalex.org/A5006581201][Josep M. Poblet]], [[https://openalex.org/A5080469156][Charlotte Vogt]], [[https://openalex.org/A5034097419][Ronny Neumann]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c10412 
     
Electrocatalytic CO    

    

* Data-Driven Design of Single-Atom Electrocatalysts with Intrinsic Descriptors for Carbon Dioxide Reduction Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402890700
:TOPICS: Accelerating Materials Innovation through Informatics, Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12209-024-00413-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402890700"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402890700"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402890700"))][Get cited by]]

OpenAlex: https://openalex.org/W4402890700 (Open access: True)
    
[[https://openalex.org/A5019002136][Xiaoyun Lin]], [[https://openalex.org/A5091222265][Shiyu Zhen]], [[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5028095147][Lyudmila V. Moskaleva]], [[https://openalex.org/A5101742243][Qian Zhang]], [[https://openalex.org/A5084194253][Zhi‐Jian Zhao]], [[https://openalex.org/A5084194253][Zhi‐Jian Zhao]], Transactions of Tianjin University. None(None)] 2024. https://doi.org/10.1007/s12209-024-00413-1 
     
Abstract The strategic manipulation of the interaction between a central metal atom and its coordinating environment in single-atom catalysts (SACs) is crucial for catalyzing the CO 2 reduction reaction (CO 2 RR). However, it remains a major challenge. While density-functional theory calculations serve as a powerful tool for catalyst screening, their time-consuming nature poses limitations. This paper presents a machine learning (ML) model based on easily accessible intrinsic descriptors to enable rapid, cost-effective, and high-throughput screening of efficient SACs in complex systems. Our ML model comprehensively captures the influences of interactions between 3 and 5d metal centers and 8 C, N-based coordination environments on CO 2 RR activity and selectivity. We reveal the electronic origin of the different activity trends observed in early and late transition metals during coordination with N atoms. The extreme gradient boosting regression model shows optimal performance in predicting binding energy and limiting potential for both HCOOH and CO production. We confirm that the product of the electronegativity and the valence electron number of metals, the radius of metals, and the average electronegativity of neighboring coordination atoms are the critical intrinsic factors determining CO 2 RR activity. Our developed ML models successfully predict several high-performance SACs beyond the existing database, demonstrating their potential applicability to other systems. This work provides insights into the low-cost and rational design of high-performance SACs.    

    

* Review for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934411
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934411"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934411"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934411"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934411 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v1/review2 
     
No abstract    

    

* Decision letter for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935014
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-04-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935014"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935014"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935014"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935014 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v2/decision1 
     
No abstract    

    

* Intrinsic Electron Transfer in Heteronuclear Dual‐Atom Sites Facilitates Selective Electrocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402993961
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202403778")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402993961"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402993961"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402993961"))][Get cited by]]

OpenAlex: https://openalex.org/W4402993961 (Open access: False)
    
[[https://openalex.org/A5101926099][Qi Tang]], [[https://openalex.org/A5101853152][Qi Hao]], [[https://openalex.org/A5086452619][Qian Zhu]], [[https://openalex.org/A5020591091][Junxiu Wu]], [[https://openalex.org/A5058587719][Keke Huang]], [[https://openalex.org/A5100399849][Kai Liu]], [[https://openalex.org/A5100674628][Jun Lü]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202403778 
     
Abstract The metal–metal (M 1 –M 2 ) interactions in heteronuclear dual‐atom catalysts (HNDACs) significantly optimize the electronic properties of the active sites, resulting in the promotion of the reaction kinetics in electrocatalysis. However, the regulation mechanisms in these M 1 –M 2 dual‐atom sites still remain unclear. Herein, the intrinsic electron transfer in Fe–Zn dual‐atom sites are revealed for facilitating electrocatalytic carbon dioxide reduction (ECO 2 R) to carbon monoxide (CO). The electronegativity difference between the Fe and Zn centers induces the specific electron transfer from Zn to Fe, which regulates the electron structures of the active Zn sites, leading to the optimized reaction pathway of CO 2 ‐to‐CO conversion on these sites. The Fe–Zn HNDAC (FeZnNC) exhibits superior ECO 2 R performances than the single‐atom Fe/Zn catalysts (FeNC and ZnNC) in the typical H‐cell system, the maximum CO partial current density on FeZnNC reaches more than 3.3 and 1.8 folds of those on FeNC and ZnNC, respectively. More importantly, in a strongly acidic medium (pH = 1), FeZnNC achieves CO Faradaic efficiencies greater than 94% in the current density range of 100–400 mA cm −2 . This work uncovers the intrinsic electron transfer at the heteronuclear diatomic sites, providing new insights for the rational design of high‐performance HNDACs toward industrial electrocatalysis.    

    

* Review for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934444
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934444"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934444"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934444"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934444 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v1/review1 
     
No abstract    

    

* Decision letter for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934858
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-04-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934858"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934858"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934858"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934858 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v1/decision1 
     
No abstract    

    

* Author response for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934933
:TOPICS: Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-04-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v2/response1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934933"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934933 (Open access: False)
    
[[https://openalex.org/A5041734836][Ryan J. R. Jones]], [[https://openalex.org/A5103079823][Yungchieh Lai]], [[https://openalex.org/A5030566949][Dan Guevarra]], [[https://openalex.org/A5073163389][Kevin Kan]], [[https://openalex.org/A5033925671][Joel A. Haber]], [[https://openalex.org/A5037026533][John M. Gregoire]], No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v2/response1 
     
No abstract    

    

* Tandem electrocatalysis for CO2 reduction to multi-carbons  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403005598
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-09-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11426-024-2144-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403005598"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403005598"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403005598"))][Get cited by]]

OpenAlex: https://openalex.org/W4403005598 (Open access: False)
    
[[https://openalex.org/A5102715021][X. N. Li]], [[https://openalex.org/A5045124309][Tianxiang Yan]], [[https://openalex.org/A5001369399][Yichen Meng]], [[https://openalex.org/A5102665350][Zhanpeng Liang]], [[https://openalex.org/A5000657358][Tianying Zhang]], [[https://openalex.org/A5018909513][Haoyuan Chi]], [[https://openalex.org/A5008104343][Ziting Fan]], [[https://openalex.org/A5008657732][Yifan Jin]], [[https://openalex.org/A5101413103][Haoran Zhang]], [[https://openalex.org/A5100394033][Sheng Zhang]], Science China Chemistry. None(None)] 2024. https://doi.org/10.1007/s11426-024-2144-0 
     
No abstract    

    

* Solar Power and Demand Response for Greening Indian Lignite Power Plants: A CO2 Reduction Initiative  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402831005
:TOPICS: Integration of Renewable Energy Systems in Power Grids, Global Energy Transition and Fossil Fuel Depletion, Energy Transition and Renewable Resources Integration
:PUBLICATION_DATE: 2024-09-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.4025/actascitechnol.v46i1.69511")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402831005"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402831005"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402831005"))][Get cited by]]

OpenAlex: https://openalex.org/W4402831005 (Open access: True)
    
[[https://openalex.org/A5069317752][Vivek Saxena]], [[https://openalex.org/A5053124619][Saurabh Kumar Rajput]], Acta Scientiarum. Technology/Acta scientiarum. Technology. 46(1)] 2024. https://doi.org/10.4025/actascitechnol.v46i1.69511 
     
This research paper delves into the prospect of curbing carbon dioxide (CO2) emissions by strategically deploying solar photovoltaic (PV) systems and orchestrating demand response (DR) mechanisms within Indian lignite power plants (LPP). The study responds to the critical imperative of mitigating greenhouse gas (GHG) emissions originating from coal-based electricity generation, a matter of substantial consequence in the context of climate change. In pursuit of optimal solar PV system allocation, this research employs the particle swarm optimization (PSO) technique, considering a spectrum of factors including solar resource availability, electricity demand patterns, and the CO2 intensity associated with coal power generation. The primary objective is to minimize CO2 emissions while maximizing the integration of solar PV and curtailing power losses, all while accounting for the intermittent nature of solar power and the dynamic nature of demand. The proposed approach is rigorously tested on the IEEE 33 bus system, supplied by the LPP. The results convincingly demonstrate a remarkable reduction in CO2 emissions, amounting to 29.69%, following the implementation of the proposed approach. This research presents a concrete step towards a more sustainable and environmentally friendly energy landscape, offering valuable insights for policymakers and stakeholders in the energy sector.    

    

* The Electrode/Electrolyte Interface Study during the Electrochemical CO2 Reduction in Acidic Electrolytes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935861
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202415894")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935861"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935861"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935861"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935861 (Open access: False)
    
[[https://openalex.org/A5081466371][Yao Yao]], [[https://openalex.org/A5078369945][Ernest Pahuyo Delmo]], [[https://openalex.org/A5005645517][Minhua Shao]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202415894 
     
Electrochemical CO2 Reduction (CO2R) in acidic electrolytes has gained significant attention owing to higher carbon efficiency and stability than in alkaline counterparts. However, the proton source and the role of alkali cations for CO2R are still under debate. By using rotating ring disk electrode and surface‐enhanced infrared absorption spectroscopy, we find that a neutral/alkaline environment at the interface is necessary for CO2R even in acidic electrolytes. We also confirm that water molecules, rather than protons serve as the proton source for CO2R. Alkali cations in the outer Helmholtz plane activate H2O and promote the desorption of adsorbed carbon monoxide. Additionally, the solvated CO2, or CO2(aq), is the actual reactant for CO2R. This study provides a deeper understanding of the electrode/electrolyte interface during CO2R in acidic electrolytes and sheds light on further performance improvement of this system.    

    

* The Electrode/Electrolyte Interface Study during the Electrochemical CO2 Reduction in Acidic Electrolytes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935594
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202415894")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935594"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935594"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935594"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935594 (Open access: False)
    
[[https://openalex.org/A5103940466][Yulin Yao]], [[https://openalex.org/A5078369945][Ernest Pahuyo Delmo]], [[https://openalex.org/A5006297542][Yu Zhang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202415894 
     
Electrochemical CO2 Reduction (CO2R) in acidic electrolytes has gained significant attention owing to higher carbon efficiency and stability than in alkaline counterparts. However, the proton source and the role of alkali cations for CO2R are still under debate. By using rotating ring disk electrode and surface‐enhanced infrared absorption spectroscopy, we find that a neutral/alkaline environment at the interface is necessary for CO2R even in acidic electrolytes. We also confirm that water molecules, rather than protons serve as the proton source for CO2R. Alkali cations in the outer Helmholtz plane activate H2O and promote the desorption of adsorbed carbon monoxide. Additionally, the solvated CO2, or CO2(aq), is the actual reactant for CO2R. This study provides a deeper understanding of the electrode/electrolyte interface during CO2R in acidic electrolytes and sheds light on further performance improvement of this system.    

    

* CO2 electrochemical reduction to formic acid: An overview of process sustainability  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402999323
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ccst.2024.100308")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402999323"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402999323"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402999323"))][Get cited by]]

OpenAlex: https://openalex.org/W4402999323 (Open access: False)
    
[[https://openalex.org/A5107668608][Zeyad M. Ghazi]], [[https://openalex.org/A5066670339][Dina Ewis]], [[https://openalex.org/A5070862521][Hazim Qiblawey]], [[https://openalex.org/A5011669590][Muftah H. El‐Naas]], Carbon Capture Science & Technology. 13(None)] 2024. https://doi.org/10.1016/j.ccst.2024.100308 
     
No abstract    

    

* Effect of Interfacial Electric Field on 2D Metal/Graphene Electrocatalysts for CO2 Reduction Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402966995
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Thermoelectric Materials
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402966995"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402966995"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402966995"))][Get cited by]]

OpenAlex: https://openalex.org/W4402966995 (Open access: False)
    
[[https://openalex.org/A5052590925][Jinwon Cho]], [[https://openalex.org/A5041107674][Faisal M. Alamgir]], [[https://openalex.org/A5090363901][Seung Soon Jang]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401673 
     
Understanding the influence of local electric fields on electrochemical reactions is crucial for designing highly selective electrocatalysts for CO2 reduction reactions (CO2RR). In this study, we provide a theoretical investigation of the effect of the local electric field induced by the negative‐biased electrode and cations in the electrolyte on the energetics and reaction kinetics of CO2RR on 2D hybrid metal/graphene electrocatalysts. Our findings reveal that the electronic structures of the CO2 molecule undergo substantial modification, resulting in the increased adsorption energy of CO­2 on metal/graphene structures, thus reducing the initial barrier of the CO2RR mechanism. This field‐assisted CO2RR mechanism promotes CO production while suppressing HCOOH production. Our findings highlight the potential of manipulating electric fields to tailor the pathways of CO2RR, providing new avenues designing selective electrocatalysts.    

    

* Microenvironment tailoring for electrocatalytic CO2 reduction: Effects of interfacial structure on controlling activity and selectivity  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402845317
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-bx32v")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402845317"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402845317"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402845317"))][Get cited by]]

OpenAlex: https://openalex.org/W4402845317 (Open access: False)
    
[[https://openalex.org/A5045395488][Yaqi Cheng]], [[https://openalex.org/A5107495676][Muhammad Iskandar B. Salaman]], [[https://openalex.org/A5056307895][Qixun Li]], [[https://openalex.org/A5021087364][Chaolong Wei]], [[https://openalex.org/A5070630688][Qilun Wang]], [[https://openalex.org/A5022857550][Xuehu Ma]], [[https://openalex.org/A5100395496][Bin Liu]], [[https://openalex.org/A5022787483][Andrew Barnabas Wong]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-bx32v 
     
The performance of the electrocatalytic CO2 reduction reaction (CO2RR) is highly dependent on the microenvironment around the cathode. Despite efforts to optimize the microenvironment by modifying nanostructured catalysts or microporous gas diffusion electrodes, their inherent disorder presents a significant challenge to understanding how interfacial structure arrangement within the electrode governs the microenvironment for CO2RR. This knowledge gap limits fundamental understanding of CO2RR while also hindering efforts to enhance CO2RR selectivity and activity. In this work, we investigate this knowledge gap using a tunable system featuring hierarchical Cu nanowire arrays that possess adjustable microgroove dimensions. Adjusting the NAM structure tunes multiple synergistic effects in the microenvironment, which include stabilization of the microwetting state, confinement of CO*, improvement to local CO2 concentration, and modulation of the local pH. Notably, using mass transport modeling, we quantify the role of the gas-liquid-solid interface in boosting local CO2 concentrations within several microns of the interface itself. Leveraging these effects, we elucidate how CO* and H* competitively occupy active sites, influencing reaction pathways toward multicarbon products based on tuning the microenvironment. Consequently, we provide new insights into why the optimized configuration significantly increased CO2RR activity by 690% (as normalized by electrochemical active surface area), C2+ product selectivity by 72%, and Faradaic efficiency by 36%, compared to CO2RR with hydrophobic Cu foil. Based on these insights, our findings unlock new opportunities to engineer the CO2RR microenvironment through the rational organization of hierarchical interface materials in gas diffusion electrodes towards improved CO2RR selectivity and activity.    

    

* Harnessing the Power of Graphene: A Critical Analysis of Graphene-Based Photocatalysts for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402917848
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-3-031-68464-7_18")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402917848"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402917848"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402917848"))][Get cited by]]

OpenAlex: https://openalex.org/W4402917848 (Open access: False)
    
[[https://openalex.org/A5050048610][Mahrukh Khan]], [[https://openalex.org/A5023916972][Mohammad Naeem Khan]], [[https://openalex.org/A5101340229][Mehrab Khan]], [[https://openalex.org/A5103123183][Hafsa Javaid]], [[https://openalex.org/A5075512873][Sara Musaddiq]], Advanced structured materials. None(None)] 2024. https://doi.org/10.1007/978-3-031-68464-7_18 
     
No abstract    

    

* Precise Synthesis of Dual‐single‐atom Electrocatalysts through Pre‐coordination‐directed in situ Confinement for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402962730
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-09-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202415223")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402962730"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402962730"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402962730"))][Get cited by]]

OpenAlex: https://openalex.org/W4402962730 (Open access: False)
    
[[https://openalex.org/A5037156563][Peng Rao]], [[https://openalex.org/A5038939329][Xing‐Qi Han]], [[https://openalex.org/A5043799303][Haochen Sun]], [[https://openalex.org/A5101840025][Fangyuan Wang]], [[https://openalex.org/A5003447105][Ying Liang]], [[https://openalex.org/A5100336948][Jing Li]], [[https://openalex.org/A5053821178][Daoxiong Wu]], [[https://openalex.org/A5003012361][Xiaodong Shi]], [[https://openalex.org/A5079901404][Zhenye Kang]], [[https://openalex.org/A5023491714][Zhengpei Miao]], [[https://openalex.org/A5017687334][Peilin Deng]], [[https://openalex.org/A5024069386][Xinlong Tian]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202415223 
     
Dual‐single‐atom catalysts (DSACs) are the next paradigm shift in single‐atom catalysts because of the enhanced performance brought about by the synergistic effects between adjacent bimetallic pairs. However, there are few methods for synthesizing DSACs with precise bimetallic structures. Herein, a pre‐coordination strategy is proposed to precisely synthesize a library of DSACs. This strategy ensures the selective and effective coordination of two metals via phthalocyanines with specific coordination sites, such as –F– and –OH–. Subsequently, in‐situ confinement inhibits the migration of metal pairs during high‐temperature pyrolysis, and obtains the DSACs with precisely constructed metal pairs. Despite changing synthetic parameters, including transition metal centers, metal pairs, and spatial geometry, the products exhibit similar atomic metal pairs dispersion properties, demonstrating the universality of the strategy. The pre‐coordination strategy synthesized DSACs shows significant CO2 reduction reaction performance in both flow‐cell and practical rechargeable Zn‐CO2 batteries. This work not only provides new insights into the precise synthesis of DSACs, but also offers guidelines for the accelerated discovery of efficient catalysts.    

    

* Precise Synthesis of Dual‐single‐atom Electrocatalysts through Pre‐coordination‐directed in situ Confinement for CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402962769
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-09-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202415223")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402962769"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402962769"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402962769"))][Get cited by]]

OpenAlex: https://openalex.org/W4402962769 (Open access: False)
    
[[https://openalex.org/A5037156563][Peng Rao]], [[https://openalex.org/A5038939329][Xing‐Qi Han]], [[https://openalex.org/A5043799303][Haochen Sun]], [[https://openalex.org/A5101840025][Fangyuan Wang]], [[https://openalex.org/A5003447105][Ying Liang]], [[https://openalex.org/A5100336948][Jing Li]], [[https://openalex.org/A5053821178][Daoxiong Wu]], [[https://openalex.org/A5003012361][Xiaodong Shi]], [[https://openalex.org/A5079901404][Zhenye Kang]], [[https://openalex.org/A5023491714][Zhengpei Miao]], [[https://openalex.org/A5017687334][Peilin Deng]], [[https://openalex.org/A5024069386][Xinlong Tian]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202415223 
     
Dual‐single‐atom catalysts (DSACs) are the next paradigm shift in single‐atom catalysts because of the enhanced performance brought about by the synergistic effects between adjacent bimetallic pairs. However, there are few methods for synthesizing DSACs with precise bimetallic structures. Herein, a pre‐coordination strategy is proposed to precisely synthesize a library of DSACs. This strategy ensures the selective and effective coordination of two metals via phthalocyanines with specific coordination sites, such as –F– and –OH–. Subsequently, in‐situ confinement inhibits the migration of metal pairs during high‐temperature pyrolysis, and obtains the DSACs with precisely constructed metal pairs. Despite changing synthetic parameters, including transition metal centers, metal pairs, and spatial geometry, the products exhibit similar atomic metal pairs dispersion properties, demonstrating the universality of the strategy. The pre‐coordination strategy synthesized DSACs shows significant CO2 reduction reaction performance in both flow‐cell and practical rechargeable Zn‐CO2 batteries. This work not only provides new insights into the precise synthesis of DSACs, but also offers guidelines for the accelerated discovery of efficient catalysts.    

    

* Porous nickel-based catalyst doped with fluorine can efficiently electrocatalyze the reduction of CO2 to CO  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402971244
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.176771")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402971244"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402971244"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402971244"))][Get cited by]]

OpenAlex: https://openalex.org/W4402971244 (Open access: False)
    
[[https://openalex.org/A5101335981][Beifang Lu]], [[https://openalex.org/A5048906150][Tianxia Liu]], [[https://openalex.org/A5100668226][Li Jia]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.176771 
     
No abstract    

    

* Z-scheme ZnIn2S4/CuxO heterostructure on flexible substrate for efficient photothermal catalytic CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402980246
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.161369")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402980246"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402980246"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402980246"))][Get cited by]]

OpenAlex: https://openalex.org/W4402980246 (Open access: False)
    
[[https://openalex.org/A5083270177][Jiping Shi]], [[https://openalex.org/A5071810183][Liuqing Hua]], [[https://openalex.org/A5050887627][Lu Ruan]], [[https://openalex.org/A5100635716][Xingjian Zhang]], [[https://openalex.org/A5101635375][Zhengdao Li]], [[https://openalex.org/A5026722987][Fengyun Su]], [[https://openalex.org/A5100353880][Xin Li]], [[https://openalex.org/A5100959252][Haiquan Xie]], [[https://openalex.org/A5074136896][Yong Zhou]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.161369 
     
No abstract    

    

* A Universal Strategy for Synthesis of Transition Metal Single Atom Catalysts toward Electrochemical CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402854519
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cc04213a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402854519"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402854519"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402854519"))][Get cited by]]

OpenAlex: https://openalex.org/W4402854519 (Open access: False)
    
[[https://openalex.org/A5100387298][Bowen Li]], [[https://openalex.org/A5102752014][Yan Liang]], [[https://openalex.org/A5041878300][Yinlong Zhu]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d4cc04213a 
     
Herein, a pyrolysis induced precursor transformation strategy has been proposed. Using pre-synthesized PDA-M as precursor, production of transiton metal single atom catalysts (SACs) has been achieved, with compositional flexibility at...    

    

* Coupling pretreatment of lignocellulosic biomass for enzymatic hydrolysis with electrochemical reduction of CO2 for production of formic acid  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402837549
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.gce.2024.09.008")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402837549"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402837549"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402837549"))][Get cited by]]

OpenAlex: https://openalex.org/W4402837549 (Open access: True)
    
[[https://openalex.org/A5075320040][Jiashuai Liu]], [[https://openalex.org/A5012184772][Fangqian Wang]], [[https://openalex.org/A5046576031][Yongrong Li]], [[https://openalex.org/A5013713303][Xuebing Zhao]], Green Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.gce.2024.09.008 
     
No abstract    

    

* Catalyst-Free Reduction of Co2: Achieved by Spontaneous Generation of Hydrogen Radicals Through Nanobubbles-Water System  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402889903
:TOPICS: Nanobubbles in Water Treatment
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4968656")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402889903"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402889903"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402889903"))][Get cited by]]

OpenAlex: https://openalex.org/W4402889903 (Open access: False)
    
[[https://openalex.org/A5100409681][Jia Liu]], [[https://openalex.org/A5103104470][Ben Niu]], [[https://openalex.org/A5048890655][Gaodong Yang]], [[https://openalex.org/A5039484229][Aosheng Chang]], [[https://openalex.org/A5100329716][Wenbin Wang]], [[https://openalex.org/A5008995033][Zhibing Zhang]], [[https://openalex.org/A5079785501][Yiwang Chen]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4968656 
     
No abstract    

    

* Life Cycle Assessment of Cement Industry with Co2 Capture and Purification: Environmental Feasibility and Synergistic Emission Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402940883
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Zeolite Chemistry and Catalysis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4970428")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402940883"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402940883"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402940883"))][Get cited by]]

OpenAlex: https://openalex.org/W4402940883 (Open access: False)
    
[[https://openalex.org/A5010702767][Qingchuan Zhao]], [[https://openalex.org/A5023325607][Lin Huang]], [[https://openalex.org/A5091547176][Wenjing Zong]], [[https://openalex.org/A5101993719][Yueling Zhang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4970428 
     
No abstract    

    

* Enhancing formate yield through electrochemical CO2 reduction using BiOCl and g-C3N4 Hybrid catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402879434
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ica.2024.122395")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402879434"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402879434"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402879434"))][Get cited by]]

OpenAlex: https://openalex.org/W4402879434 (Open access: True)
    
[[https://openalex.org/A5052253461][Smritirekha Talukdar]], [[https://openalex.org/A5078747289][Manuela Bevilacqua]], [[https://openalex.org/A5041499161][Enqi Bu]], [[https://openalex.org/A5012260820][Lapo Gabellini]], [[https://openalex.org/A5107551583][Lapo Querci]], [[https://openalex.org/A5062814647][Juan J. Delgado]], [[https://openalex.org/A5059551907][Matteo Mannini]], [[https://openalex.org/A5042229475][Paolo Fornasiero]], [[https://openalex.org/A5033020300][Tiziano Montini]], Inorganica Chimica Acta. None(None)] 2024. https://doi.org/10.1016/j.ica.2024.122395 
     
No abstract    

    

* Enhanced Catalytic Activity of I-Mxenes for Co2 Reduction Reaction by Ordered Metal Atomic Vacancies: A Dft Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403016594
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4973714")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403016594"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403016594"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403016594"))][Get cited by]]

OpenAlex: https://openalex.org/W4403016594 (Open access: False)
    
[[https://openalex.org/A5000445381][Huichun Xue]], [[https://openalex.org/A5068991083][Yitong Chen]], [[https://openalex.org/A5101519452][Lin Zhu]], [[https://openalex.org/A5037785383][An Du]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4973714 
     
No abstract    

    

* Water-induced Switching in Selectivity and Steric Control of Activity in Photochemical CO2 Reduction Catalyzed by RhCp*(bpy) Derivatives  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402852228
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-t3ltd-v3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402852228"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402852228"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402852228"))][Get cited by]]

OpenAlex: https://openalex.org/W4402852228 (Open access: False)
    
[[https://openalex.org/A5063894173][Dongseb Lee]], [[https://openalex.org/A5039693008][Kosei Yamauchi]], [[https://openalex.org/A5066627191][Ken Sakai]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-t3ltd-v3 
     
Photocatalytic reduction of CO2 to formic acid (HCOOH) was investigated in either organic or aqueous/organic media by employing three water-soluble [RhIIICp*(LH2)Cl]+ (LH2 = n,n’-dihydroxy-2,2’-bipyridine; n = 4, 5, or 6) in the presence of [Ru(bpy)3]2+, 1,3-dimethyl-2-phenyl-2,3-dihydro-1H-benzo[d]imidazole (BIH) and triethanolamine (TEOA). Through studying the electron-donating effects of two hydroxyl groups introduced to the bipyridyl ligand, we found that the substituent positions greatly affect both the catalytic efficiency and selectivity in CO2 reduction. More importantly, the HCOOH selectivity shows a dramatic increase from 14% to 83% upon switching the solvent media from pure organic to aqueous/organic mixture, where the H2 selectivity shows a reverse phenomenon. The enhanced HCOOH selectivity and the drastic decrease in the H2 yield are well rationalized by the fact that the catalytic CO2 hydrogenation is not only driven photochemically via the attack of RhIII(H)Cp*(LH2-•) on CO2 but also partly bypassed by a dark H2 addition reaction yielding [RhIII(H)Cp*(L)]- from [RhIIICp*(L)Cl]+, which was also separately investigated under the dark conditions. Combination of experimental and theoretical approaches were made to clarify the pKa values of catalyst intermediates together with the abundant species responsible for the major catalytic processes. Our DFT studies unveil that the exceptionally large structural strain given by the steric contacts between the 6,6’-dihydroxyl groups and the Cp* moiety plays a significant role in bringing about an outstanding catalytic performance of the 6,6’-subsituted derivative. The intrinsic reaction coordinate calculations were carried out to clarify the mechanism of hydride transfer steps leading to generate formate together the heterolytic H2 cleavage steps leading to afford the key hydridorhodium intermediates. This study represents the first report on the water-induced high selectivity in CO2-to-HCOOH conversion, shedding a new light on the strategy to control the efficiency and selectivity in the catalysis of CO2 reduction.    

    

* Transition metal-loaded C2N catalysts for selective CO2 reduction to CH4: Insights from first-principles calculations  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402903769
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.133267")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402903769"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402903769"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402903769"))][Get cited by]]

OpenAlex: https://openalex.org/W4402903769 (Open access: False)
    
[[https://openalex.org/A5100442643][Shun Li]], [[https://openalex.org/A5059222667][Shitao Peng]], [[https://openalex.org/A5011110685][Zhigang Qi]], [[https://openalex.org/A5085016100][Likai Tong]], Fuel. 381(None)] 2024. https://doi.org/10.1016/j.fuel.2024.133267 
     
No abstract    

    

* Mathematical modeling for hydrogen blending in natural gas pipelines moving towards industrial decarbonization: Economic feasibility and CO2 reduction analysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402900170
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Hydrogen Energy Systems and Technologies, Integration of Renewable Energy Systems in Power Grids
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.09.083")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402900170"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402900170"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402900170"))][Get cited by]]

OpenAlex: https://openalex.org/W4402900170 (Open access: False)
    
[[https://openalex.org/A5066811869][Daniela Fernanda Ruiz Diaz]], [[https://openalex.org/A5102657024][Jun Zhao]], [[https://openalex.org/A5051742817][John Pham]], [[https://openalex.org/A5007355587][Christopher Ramirez]], [[https://openalex.org/A5061953615][Huiting Qin]], [[https://openalex.org/A5041819894][A Jimenez]], [[https://openalex.org/A5107552540][Akhil Muthappa Pulianda]], [[https://openalex.org/A5107584066][Chelsea Choudhary]], [[https://openalex.org/A5032059471][Vince McDonell]], [[https://openalex.org/A5021287108][G.P. Li]], International Journal of Hydrogen Energy. 88(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.09.083 
     
No abstract    

    

* Optimizing CO2 Photoreduction Through Metal-Organic Frameworks: The Impact of Metal Selection and Composite Structures  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402851762
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.70251/hyjr2348.235560")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402851762"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402851762"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402851762"))][Get cited by]]

OpenAlex: https://openalex.org/W4402851762 (Open access: False)
    
[[https://openalex.org/A5065333843][Baoru Sun]], [[https://openalex.org/A5009395657][Ke Xie]], No host. None(None)] 2024. https://doi.org/10.70251/hyjr2348.235560 
     
The rising atmospheric carbon dioxide (CO2) concentration poses significant environmental challenges, including global warming and associated climate change. Metal-organic frameworks (MOFs) have emerged as promising materials for addressing and mitigating CO2 levels due to their high surface area, tunable pore sizes, and customizable metal nodes. This review focuses on the influence of metal selection and MOF composites on the efficiency and stability of MOFs in CO2 photoreduction reactions. The findings underscore the potential of MOF-based catalysts in developing sustainable solutions for CO2 reduction, offering a pathway to mitigate environmental impacts while advancing renewable energy technologies.    

    

* Unravelling the Serbian Energy Transition Puzzle: Driving an Electric Vehicle Result in Higher CO2 Emissions than Driving a Traditional Internal Combustion Engine Counterparty  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402974272
:TOPICS: Rebound Effect on Energy Efficiency and Consumption, Energy Supply and Security Issues for Developed Economies, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.46793/eee24-1.22f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402974272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402974272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402974272"))][Get cited by]]

OpenAlex: https://openalex.org/W4402974272 (Open access: True)
    
[[https://openalex.org/A5038125617][Sergey F. Fominykh]], [[https://openalex.org/A5107652997][Dusan Stanar]], Energija Ekonomija Ekologija. XXVI(1)] 2024. https://doi.org/10.46793/eee24-1.22f 
     
his article delves into the intriguing paradox emerging in Serbia's transportation landscape, where electric vehicles (EVs) are projected to generate more carbon dioxide (CO2) emissions than internal combustion engine (ICE) until 2030. Driving an EV within Serbia over the upcoming five years is estimated to contribute to roughly 25% more CO2 emissions compared to ICE vehicles. The study unveils the underlying factors behind this paradox, including Serbia's energy mix dominated by lignite. By contrasting this with the European Union's cleaner energy sources, the article underscores the delayed CO2 emissions reduction from EVs in Serbia. Furthermore, it explores the carbon footprint associated with EV production and highlights the challenges posed by the country's energy infrastructure and vehicle fleet. The article concludes with insights into potential solutions, emphasizing the need for Serbia to accelerate its transition to renewables, aiming to align with 2030 targets, while parity with EU emissions levels is projected by 2040.    

    

* The Impact of Economic Factors on Changing Carbon Emission Landscape in ASEAN With ARDL Approach  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402849537
:TOPICS: Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.24002/kinerja.v28i2.8583")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402849537"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402849537"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402849537"))][Get cited by]]

OpenAlex: https://openalex.org/W4402849537 (Open access: True)
    
[[https://openalex.org/A5003264851][Hasbi Hasbi]], KINERJA. 28(2)] 2024. https://doi.org/10.24002/kinerja.v28i2.8583 
     
This study aims to analyze the factors influencing carbon emissions in the member countries of the Association of Southeast Asian Nations (ASEAN). The data used in this study covers the period from 1990 to 2021, utilizing the Autoregressive Distributed Lag (ARDL) analysis method. All independent variables show a significant impact on carbon emissions in both the short and long term. This research provides evidence that factors such as urbanization, foreign direct investment, population, and economic growth significantly contribute to the increase in carbon emissions in ASEAN countries. The findings also validate the Environmental Kuznets Curve hypothesis for carbon emissions in ASEAN countries. In other words, economic growth leads to a reduction in carbon emissions. The ASEAN region has experienced substantial economic growth over the past few decades. However, carbon dioxide (CO2) remains a socio-economic issue in the ASEAN region. The results of this study can be highly beneficial for policymakers in the region regarding sustainability and economic development.    

    

* Empowering sustainable hotels: a guest-centric optimization for vehicle-to-building integration  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402943553
:TOPICS: Implications of Shared Autonomous Vehicle Services, Integration of Electric Vehicles in Power Systems, Influence of Built Environment on Active Travel
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1186/s42162-024-00400-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402943553"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402943553"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402943553"))][Get cited by]]

OpenAlex: https://openalex.org/W4402943553 (Open access: True)
    
[[https://openalex.org/A5057616496][Lynne Valett]], [[https://openalex.org/A5087084762][Jessica Bollenbach]], [[https://openalex.org/A5048831245][Robert Keller]], Energy Informatics. 7(1)] 2024. https://doi.org/10.1186/s42162-024-00400-9 
     
Abstract In light of global warming, hotels account for one of the highest energy demands within the building sector, offering great decarbonization potential. As electrification increases, so does the demand for electric vehicles (EVs) charging stations at hotels and the proportion of Vehicle-to-Building-capable EVs. Therefore, the study explores the potential of guest-centric energy management. To accomplish this, we develop an optimization model for an energy management system that focuses on either cost-efficiency or carbon dioxide equivalents (CO2)-efficiency, grounded in a real-world case study. Through scenario analyses considering seasons as well as different guest mobility behaviors, this study discusses the expenses associated with CO2 savings using digital solutions. It emphasizes the currently perceived conflict between cost reduction and decarbonization goals to achieve a sustainable design of information systems. Thereby, this study highlights the critical importance of individual mobility behavior in enabling sustainable energy management for hotels.    

    

* Biogas as alternative fuel for the road transportation sector in Algeria by 2050: a case study Ouargla  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402941771
:TOPICS: Impact of Oil Palm Expansion on Biodiversity, Technical Aspects of Biodiesel Production, Indoor Air Pollution in Developing Countries
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54021/seesv5n2-261")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402941771"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402941771"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402941771"))][Get cited by]]

OpenAlex: https://openalex.org/W4402941771 (Open access: False)
    
[[https://openalex.org/A5033700468][Bakhta Recioui]], [[https://openalex.org/A5107648890][Mondir Soualeh]], [[https://openalex.org/A5060172774][Djilali Messaoudi]], [[https://openalex.org/A5104013629][Noureddine Settou]], [[https://openalex.org/A5019641066][Rébha Ghedamsi]], [[https://openalex.org/A5022044379][Yasmina Mokhbi]], [[https://openalex.org/A5052278335][Soumia Rahmouni]], STUDIES IN ENGINEERING AND EXACT SCIENCES. 5(2)] 2024. https://doi.org/10.54021/seesv5n2-261 
     
This study aims to integrate the biogas road transport sector in the Ouargla region of Algeria by 2050. The alternative biogas is derived from livestock animals (goats, cows, sheep, and camels), municipal waste, and palm waste. Anaerobic digestion is the process used for producing biogas. Our study adopts a prospective method that integrates two modules: energy modeling and the Geographic Information System (GIS) to evaluate the biogas demand potential in the Algeria’s road transportation sector between 2020 and 2050. We proposed two scenarios to estimate the avoided CO2 emissions by 2050: a voluntary biogas vehicle (VB) and a reference conventional fuel vehicle (CFV) to calculate the environmental impacts both before and after the implementation of biogas as a substitute fuel in the transportation sector. As a result, the total amount of biogas demand would be 488.46 thousand tons until 2050. A significant CO2 reduction is achievable in 2050; the amount of CO2 saving is estimated at 285.78 thousand tons, or 43%. The results of this study showed that the use of biogas in road transport as a substitute fuel serves to protect the environment by reducing carbon dioxide emissions while decreasing energy usage.    

    

* f‐π* Back Bonding Orbital Induced by Lutetium‐Based Conducting MOF Promotes Highly Selective CO 2 to CH 4 at Low Potential  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402852998
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Electrochemical Reduction of CO2 to Fuels, Negative Thermal Expansion in Materials
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202416467")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402852998"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402852998"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402852998"))][Get cited by]]

OpenAlex: https://openalex.org/W4402852998 (Open access: False)
    
[[https://openalex.org/A5065705442][Fuqing Yu]], [[https://openalex.org/A5017487959][Guangyao Zhang]], [[https://openalex.org/A5075927434][Minxing Shu]], [[https://openalex.org/A5040593287][Hongming Wang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202416467 
     
The research on electrocatalytic carbon dioxide reduction (ECR) catalysts using renewable energy is particularly crucial in energy conversion studies, especially for viable hydrocarbon production. This study employs density functional theory calculations to screen a series of non‐radioactive lanthanide two‐dimensional metal‐organic frameworks (MOFs) for product selectivity in ECR. Based on theoretical screening, our focus is on a lutetium (Lu)‐based conducting MOF (Lu‐HHTP), which exhibits a Faradaic efficiency of approximately 77% for methane (CH4) production and maintains a stable current density of ‐280 mA/cm2 at ‐1.1 V vs. RHE. In situ electrochemical experiments and material characterization demonstrate that the Lu sites possess high coordination stability and structural recoverability during catalytic CO2 reduction, attributed to the overlap between Lu's f‐orbitals and the π*‐orbitals of the ligand O, and the formation of back bonding orbitals between the f‐orbitals of Lu and the π* orbitals of CO contribute increasing CH₄ selectivity and lowering the potential. This study leverages rare‐earth MOF‐type materials, offering a novel approach to addressing low conductivity and stabilizing rare‐earth materials, thereby establishing a theoretical framework for the conversion of linearly adsorbed *CO into hydrocarbons.    

    

* f‐π* Back Bonding Orbital Induced by Lutetium‐Based Conducting MOF Promotes Highly Selective CO 2 to CH 4 at Low Potential  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402852999
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis, Coexistence of Ferromagnetism and Metallic Conductivity in Organic Molecular Metals
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202416467")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402852999"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402852999"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402852999"))][Get cited by]]

OpenAlex: https://openalex.org/W4402852999 (Open access: False)
    
[[https://openalex.org/A5065705442][Fuqing Yu]], [[https://openalex.org/A5101742243][Qian Zhang]], [[https://openalex.org/A5075927434][Minxing Shu]], [[https://openalex.org/A5040593287][Hongming Wang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202416467 
     
The research on electrocatalytic carbon dioxide reduction (ECR) catalysts using renewable energy is particularly crucial in energy conversion studies, especially for viable hydrocarbon production. This study employs density functional theory calculations to screen a series of non‐radioactive lanthanide two‐dimensional metal‐organic frameworks (MOFs) for product selectivity in ECR. Based on theoretical screening, our focus is on a lutetium (Lu)‐based conducting MOF (Lu‐HHTP), which exhibits a Faradaic efficiency of approximately 77% for methane (CH4) production and maintains a stable current density of ‐280 mA/cm2 at ‐1.1 V vs. RHE. In situ electrochemical experiments and material characterization demonstrate that the Lu sites possess high coordination stability and structural recoverability during catalytic CO2 reduction, attributed to the overlap between Lu's f‐orbitals and the π*‐orbitals of the ligand O, and the formation of back bonding orbitals between the f‐orbitals of Lu and the π* orbitals of CO contribute increasing CH₄ selectivity and lowering the potential. This study leverages rare‐earth MOF‐type materials, offering a novel approach to addressing low conductivity and stabilizing rare‐earth materials, thereby establishing a theoretical framework for the conversion of linearly adsorbed *CO into hydrocarbons.    

    

* Rectifying Heterointerface Facilitated C‐N Coupling Dynamics Enables Efficient Urea Electrosynthesis Under Ultralow Potentials  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402849954
:TOPICS: Ammonia Synthesis and Electrocatalysis, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202413534")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402849954"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402849954"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402849954"))][Get cited by]]

OpenAlex: https://openalex.org/W4402849954 (Open access: False)
    
[[https://openalex.org/A5056502443][Mingyu Cheng]], [[https://openalex.org/A5005990956][Wei Shao]], [[https://openalex.org/A5077311986][Zhifeng Dai]], [[https://openalex.org/A5008759729][Jing Xia]], [[https://openalex.org/A5002479303][Bocheng Zhang]], [[https://openalex.org/A5102030247][Pingyi Feng]], [[https://openalex.org/A5043069426][Yin Zhu]], [[https://openalex.org/A5100383241][Yangyang Zhang]], [[https://openalex.org/A5001740473][Genqiang Zhang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202413534 
     
Electrocatalytic C‐N coupling for urea synthesis from carbon dioxide (CO2) and nitrate (NO3‐) offers a sustainable alternative to the traditional Bosch‐Meiser method. However, the complexity of intermediates in co‐reduction hampers simultaneous improvement in urea yield and Faradaic efficiency (FE). Herein, we developed a Cu/Cu2O Mott‐Schottky catalyst with nanoscale rectifying heterointerfaces through precise controllable in‐situ electroreduction of Cu2O nanowires, achieving notable FE (32.6‐47.0%) and substantial yields (6.08‐30.4 μmol h‐1 cm‐2) across a broad range of ultralow applied potentials (0 to ‐0.3 V vs. RHE). Operando synchrotron radiation‐Fourier transform infrared spectroscopy (SR‐FTIR) confirmed the formation of *CO intermediates and C‐N bonds, subsequently density functional theory (DFT) calculations deciphered that the Cu/Cu2O rectifying heterointerface modulated *CO adsorption, significantly enhancing subsequent C‐N coupling dynamics between *CO and *NOH intermediates. This work not only provides a groundbreaking and advanced pathway for C‐N coupling, but also offers deep insights into copper‐based heterointerface catalysts for urea synthesis.    

    

* Rectifying Heterointerface Facilitated C‐N Coupling Dynamics Enables Efficient Urea Electrosynthesis Under Ultralow Potentials  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402850851
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202413534")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402850851"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402850851"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402850851"))][Get cited by]]

OpenAlex: https://openalex.org/W4402850851 (Open access: False)
    
[[https://openalex.org/A5056502443][Mingyu Cheng]], [[https://openalex.org/A5005990956][Wei Shao]], [[https://openalex.org/A5077311986][Zhifeng Dai]], [[https://openalex.org/A5008759729][Jing Xia]], [[https://openalex.org/A5002479303][Bocheng Zhang]], [[https://openalex.org/A5102030247][Pingyi Feng]], [[https://openalex.org/A5091228324][Yin Zhu]], [[https://openalex.org/A5100383241][Yangyang Zhang]], [[https://openalex.org/A5001740473][Genqiang Zhang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202413534 
     
Electrocatalytic C‐N coupling for urea synthesis from carbon dioxide (CO2) and nitrate (NO3‐) offers a sustainable alternative to the traditional Bosch‐Meiser method. However, the complexity of intermediates in co‐reduction hampers simultaneous improvement in urea yield and Faradaic efficiency (FE). Herein, we developed a Cu/Cu2O Mott‐Schottky catalyst with nanoscale rectifying heterointerfaces through precise controllable in‐situ electroreduction of Cu2O nanowires, achieving notable FE (32.6‐47.0%) and substantial yields (6.08‐30.4 μmol h‐1 cm‐2) across a broad range of ultralow applied potentials (0 to ‐0.3 V vs. RHE). Operando synchrotron radiation‐Fourier transform infrared spectroscopy (SR‐FTIR) confirmed the formation of *CO intermediates and C‐N bonds, subsequently density functional theory (DFT) calculations deciphered that the Cu/Cu2O rectifying heterointerface modulated *CO adsorption, significantly enhancing subsequent C‐N coupling dynamics between *CO and *NOH intermediates. This work not only provides a groundbreaking and advanced pathway for C‐N coupling, but also offers deep insights into copper‐based heterointerface catalysts for urea synthesis.    

    

* Visible‐Light‐Promoted Reduction of Nitroarenes with Formate Salts as Reductants  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402872000
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Reduction of Nitro Compounds, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202402870")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402872000"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402872000"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402872000"))][Get cited by]]

OpenAlex: https://openalex.org/W4402872000 (Open access: False)
    
[[https://openalex.org/A5060294264][Jason Wu]], [[https://openalex.org/A5010957051][Yizao Wan]], [[https://openalex.org/A5049903522][Yu Shao]], [[https://openalex.org/A5065584299][Le‐Wu Zhan]], [[https://openalex.org/A5007828251][Bindong Li]], [[https://openalex.org/A5030636768][Jing Hou]], Chemistry - A European Journal. None(None)] 2024. https://doi.org/10.1002/chem.202402870 
     
A visible‐light‐promoted reduction of nitrobenzenes using formate salts as the reductant was developed. A wide range of nitrobenzenes can be converted into aniline products in a transition metal free fashion. Mechanistic studies revealed that radical species (carbon dioxide radical anion and thiol radical) are key intermediates for the transformation. We anticipate that this method will provide a valuable and green strategy for the reduction of nitrobenzenes.    

    

* An Overview of Exploitation and Utilization of Shallow Geothermal Energy in Northwest China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402892708
:TOPICS: Fundamentals and Applications of Finite Element Analysis, Geothermal Energy Technology and Applications, Integration of Renewable Energy Systems in Power Grids
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.62051/trh2e430")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402892708"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402892708"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402892708"))][Get cited by]]

OpenAlex: https://openalex.org/W4402892708 (Open access: False)
    
[[https://openalex.org/A5101595191][Chang Sun]], [[https://openalex.org/A5030840360][Xiaolei Ju]], Deleted Journal. 2(None)] 2024. https://doi.org/10.62051/trh2e430 
     
Geothermal energy, as a non-carbon-based energy, serves as a crucial way to achieve the goal for “carbon reductions in two stages”, namely the target of peaking carbon dioxide emissions by 2030 and achieving carbon neutrality by 2060. China is a large country with abundant mesothermal-epithermal geothermal resources. Its national potential geothermal resources account for nearly 8% of those in the world, and geothermal resources have been developed and utilized for nearly 50 years in China. According to incomplete statistics, the geothermal fields in Northwest China accounts for 10% of those in the country, and the stored thermal energy in Northwest China accounts for 3.34% of the total in the country. In order to probe into the potential of geothermal resources in Northwest China and their value in the goal for “carbon reductions in two stages”, this paper summarizes the shallow geothermal energy resource endowment in Northwest China, briefly introduces the status quo of shallow geothermal energy exploitation and utilization and existing problems.    

    

* Spatial-temporal differences and convergence analysis of residential building carbon emission efficiency in China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402917681
:TOPICS: Economic Impact of Environmental Policies and Resources, Life Cycle Assessment and Environmental Impact Analysis, Efficiency Analysis in Production and Resource Allocation
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1371/journal.pone.0311097")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402917681"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402917681"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402917681"))][Get cited by]]

OpenAlex: https://openalex.org/W4402917681 (Open access: True)
    
[[https://openalex.org/A5023691587][Yong-Kun Wang]], [[https://openalex.org/A5107516074][Na Lu]], [[https://openalex.org/A5100417669][Yan Wang]], PLoS ONE. 19(9)] 2024. https://doi.org/10.1371/journal.pone.0311097 
     
Data indicate that carbon dioxide emissions from residential buildings in China constitute 60% of the country’s total, making carbon reduction efforts in residential construction crucial for achieving dual carbon goals. From the perspective of eight major economic regions, this paper selects energy consumption, per capita residential area, and residential population as input indicators, per capita disposable income as the output indicator, and carbon dioxide emissions as the undesired output indicator. It employs the super-efficiency model based on the directional distance (super-DDF) function and the Malmquist-Luenberger (ML) index to measure the static and dynamic carbon emission efficiencies of residential buildings (RBCEE) during their operational phase from 2010 to 2020. After analyzing the differences and equity in RBCEE among regions using the Theil index and Gini coefficient, the σ-convergence, absolute β-convergence, and conditional β-convergence methods are utilized to explore the changing trends of RBCEE across the eight major economic regions. Results show that the static RBCEE in China is at a medium level; dynamic efficiency has improved across all eight regions, though at varying rates; overall, RBCEE exhibits poor equity and significant differences, with intra-group differences being a major cause. In terms of convergence, all eight economic regions display significant absolute β-convergence and conditional β-convergence. Finally, based on the research findings, this paper proposes corresponding emission reduction recommendations for the eight major economic regions.    

    

* Analysis of China's provincial carbon peak path based on LSTM neural network  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402886211
:TOPICS: Life Cycle Assessment and Environmental Impact Analysis, Application of Grey System Theory in Forecasting, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.59782/sidr.v1i1.31")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402886211"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402886211"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402886211"))][Get cited by]]

OpenAlex: https://openalex.org/W4402886211 (Open access: False)
    
[[https://openalex.org/A5107582567][Zhang Gaomin]], [[https://openalex.org/A5101579470][Teng Wang]], [[https://openalex.org/A5107551804][Lou Yuanyu]], [[https://openalex.org/A5107532880][Guan Zhongcheng]], [[https://openalex.org/A5078699093][Zheng Haijun]], [[https://openalex.org/A5100430045][Qiang Li]], [[https://openalex.org/A5107621711][Wu Jiaqian]], No host. 1(1)] 2024. https://doi.org/10.59782/sidr.v1i1.31 
     
As the world's largest carbon emitter and the second largest economy, China has pledged that its carbon dioxide emissions will peak around 2030, when the intensity of carbon dioxide emissions will be lower than in 2005. However, there is great heterogeneity among provinces in China, and their carbon peak paths cannot be cut off in one size fits all. Based on the "14th Five-Year Plan" of each province, this paper designs three scenarios: baseline, green development, and high-speed development. The LSTM neural network is used to dynamically predict the carbon peak paths of China and its provinces from 2020 to 2040, and the appropriate peak paths are analyzed based on the three factors of carbon emission intensity, cumulative carbon emissions, and peak time of each province. The results show that: China will achieve the carbon peak target before 2030 under different scenarios, with a peak level of 10884-11792 million tons; 24 provinces and regions can achieve the carbon peak target before 2030 under at least one scenario, and most provinces and regions show the characteristics of early peak time and low peak value under low-speed scenario, and late peak time and high peak value under high-speed scenario; Beijing, Shanghai, Fujian, Zhejiang and other provinces and regions can achieve negative carbon after 2035. The research results have important reference value for China to reasonably formulate carbon peak path measures in 2030 and coordinate the allocation of emission reduction tasks.    

    

* A novel optimization approach for the design of a hybrid energy system based on a modified version of a subtraction-average-based optimizing method  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402918654
:TOPICS: Hydrogen Energy Systems and Technologies, Integration of Renewable Energy Systems in Power Grids, Demand Response in Smart Grids
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/ijlct/ctae117")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402918654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402918654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402918654"))][Get cited by]]

OpenAlex: https://openalex.org/W4402918654 (Open access: True)
    
[[https://openalex.org/A5101023299][Wu Nan]], [[https://openalex.org/A5101612762][Ning Sun]], [[https://openalex.org/A5103108189][Saeid Razmjooy]], International Journal of Low-Carbon Technologies. 19(None)] 2024. https://doi.org/10.1093/ijlct/ctae117 
     
Abstract A critical challenge lies in developing an energy-efficient and eco-friendly power supply system. Despite the enhanced energy efficiency offered by combined cooling, heating, and power (CCHP) systems, optimizing them poses challenges due to conflicting goals like reducing fuel consumption and carbon dioxide emissions while maximizing cost savings. To address these issues, this research suggests a solution that merges a modified subtraction-average-based optimizer with a multiobjective optimization strategy. This proposed framework attains a superior equilibrium among competing objectives compared to three existing optimization algorithms. It leads to a 12% decrease in fuel consumption, a 15% drop in carbon dioxide emissions, and a 10% cost reduction for shopping center proprietors. Moreover, the optimized CCHP system outperforms a stand-alone production system and a nonoptimized CCHP system, yielding 20% and 15% fuel savings annually, respectively. By offering a more comprehensive and balanced approach to CCHP system optimization, the proposed framework contributes to the progression of energy system optimizer, fostering the creation of more sustainable and environmentally friendly energy systems of shopping centers.    

    

* Statistical Measurement and Economic Effect Research on Green New Energy Industry in Yangtze River Delta  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402937173
:TOPICS: Environmental Impact on Lake Baikal Ecosystem, Rural Revitalization Strategy in China
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.62051/ijgem.v4n2.22")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402937173"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402937173"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402937173"))][Get cited by]]

OpenAlex: https://openalex.org/W4402937173 (Open access: False)
    
[[https://openalex.org/A5036523776][Qingliang Tang]], [[https://openalex.org/A5100371335][Sheng Wang]], International Journal of Global Economics and Management. 4(2)] 2024. https://doi.org/10.62051/ijgem.v4n2.22 
     
With the rapid development of economy, human activities have caused great impact on the ecological environment. Achieving peak carbon dioxide emissions, carbon neutrality has become the goal to be completed. Taking the new energy industry in the Yangtze River Delta region as the research subject, this paper explores the relationship between the development of new energy and social economy, scientifically accounts for and evaluates the emission reduction potential of the new energy industry, conducts coupling and coordinated development research on the new energy industry and the regional low-carbon economic integration development, and provides scientific suggestions for the realization of "peak carbon dioxide emissions, carbon neutrality". Focusing on the above purpose, this paper firstly synthesizes the literature, clarifies the relevant concepts of low-carbon economy and the evaluation indicators of the development level of new energy industry, and combs the interaction between the two, providing theoretical support for the subsequent analysis. Secondly, it constructs a multi-dimensional measurement index to explore the green new energy industry, selects the relevant data of three provinces and one city in the Yangtze River Delta region from 2011 to 2019, and uses the TOPSIS entropy method to quantify various indicators of the new energy industry. Then, the unit root test is carried out on the data of different indicators of the new energy industry to judge whether these variable data have stationarity, and then the strength and direction of the relationship between the variables of different indicators are judged through the co-integration test. At last, the PSTR model is applied to take economic growth as the conversion variable, to examine the nonlinear effect of explanatory variables such as economic growth on the development of new energy, to conduct empirical analysis and draw conclusions.    

    

* Regulating the Magnetic Domain of Nickle for Enhanced CO2 Electrochemical Reduction Driven by External Magnetic Field  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402929856
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202403624")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402929856"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402929856"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402929856"))][Get cited by]]

OpenAlex: https://openalex.org/W4402929856 (Open access: False)
    
[[https://openalex.org/A5033498857][Zhaozhao Zhu]], [[https://openalex.org/A5024831364][Wu Tang]], [[https://openalex.org/A5100395804][Junjie Wang]], [[https://openalex.org/A5101064739][Yingxi Lin]], [[https://openalex.org/A5036131297][Zhao Li]], [[https://openalex.org/A5013407292][Haiyuan Chen]], [[https://openalex.org/A5100366524][Zihao Song]], [[https://openalex.org/A5074894656][Jun Song Chen]], [[https://openalex.org/A5087031805][Rui Wu]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202403624 
     
Abstract Electrochemical reduction of carbon dioxide (CO 2 RR) into valuable fuels and chemicals is a highly desirable approach for achieving carbon neutrality, but it faces substantial technical hurdles. Herein, a novel ferromagnetic Ni@NC electrocatalyst is reported, composed of nickel nanoparticles embedded within a nitrogen‐doped carbon matrix. The optimal Ni@NC catalyst displays a fourfold increase in current density at 140 versus 0 mT in H‐type cell and achieves nearly 100% CO Faradaic efficiency (FE CO ) across a wide potential range with minimal overpotential in flow cell. Quantum diamond atomic force microscopy (QDAFM) directly demonstrates the orderly magnetic moments of the Ni@NC catalyst under the external magnetic field. Further theoretical calculations reveal that the orderly magnetic moments induced by the external magnetic field facilitate the formation of Ni–O–Ni and reduce the energy barriers of COOH * intermediates. This study underscores the potential of applying magnetic field modulation to not only enhance the catalytic efficiencies but also extend this strategy to other catalytic systems.    

    

* Slip flow of SWCNT–H2O, TiO2–H2O, MWCNT–H2O, and GO–H2O nanofluids between two spinning circular disks  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935795
:TOPICS: Heat Transfer Enhancement in Nanofluids, Heat Transfer in Porous Media and Packed Beds, Lattice Boltzmann Method for Complex Flows
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/zamm.202301015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935795"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935795 (Open access: False)
    
[[https://openalex.org/A5084330974][Tanvi Singla]], [[https://openalex.org/A5072563406][Mark Haid]], [[https://openalex.org/A5090382285][B. Kumar]], ZAMM ‐ Journal of Applied Mathematics and Mechanics / Zeitschrift für Angewandte Mathematik und Mechanik. None(None)] 2024. https://doi.org/10.1002/zamm.202301015 
     
Abstract The heat transfer and flow properties of nanofluids are studied using two co‐axial, stretched, and rotating disks containing the porous media and slip boundary conditions. The water‐based nanofluid is formed by using SWCNT (single‐walled carbon nanotubes), (titanium dioxide), MWCNT (multiwalled carbon nanotubes), GO (graphene oxide) as nanoparticles. The nonlinear PDEs are converted into ODEs using the Von Karman similarity transformation. The finite difference method is used to solve the transformed equations. The velocity profiles in the axial, radial, and tangential directions and the temperature profiles are analyzed through graphs, accompanied by interpretations based on physical principles. The energy equation is modeled using the Cattaneo–Christov heat flux model. When the velocity slip parameter rises, axial velocity decreases near the lower disk but increases near the end of the upper disk, while there is a reduction in radial velocity near the end of both disks. The skin friction coefficient and Nusselt number are computed in the present study for governing parameters.    

    

* Influence of Different Dissolved Gases on Electrocatalytic Nitrate Sensing Performance at Cu‐Modified Au Electrode  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402838303
:TOPICS: Electrochemical Biosensor Technology, Advances in Chemical Sensor Technologies, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/slct.202402986")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402838303"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402838303"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402838303"))][Get cited by]]

OpenAlex: https://openalex.org/W4402838303 (Open access: False)
    
[[https://openalex.org/A5005724333][M. Islam]], [[https://openalex.org/A5100779730][Mohammad Imran Hossain]], [[https://openalex.org/A5093990117][Nazmul Hosen]], [[https://openalex.org/A5010126005][Mostafizur Rahaman]], [[https://openalex.org/A5013084778][Nayan Ranjan Singha]], [[https://openalex.org/A5004758377][Kyoko Aoki]], [[https://openalex.org/A5059630659][Yuki Nagao]], [[https://openalex.org/A5049652049][Mohammad A. Hasnat]], ChemistrySelect. 9(36)] 2024. https://doi.org/10.1002/slct.202402986 
     
Abstract The present study investigates the electrocatalytic nitrate reduction reaction (NRR) on a Cu/Au electrode surface in a neutral pH potassium chloride (KCl) environment saturated with nitrogen, oxygen, and carbon dioxide, three of the most abundant atmospheric gases. The electrode was characterized using OCP, EIS, SEM, EDX, XPS, and XRD to assess its electrochemical properties, catalytic feasibility, and surface morphology. Results indicated that nitrate ions undergo a consecutive reduction process ( → → ) on the Cu/Au electrode. O 2 saturated environment impeded the NRR process through O 2 adsorption on the electrode surface prior to the → conversion. In contrast, CO 2 saturated condition enhanced the reaction by neutralizing the NRR byproduct ions, thus accelerating the overall NRR kinetics. Under CO 2 environment the NRR process was found more facile compared to that of other two gases. NRR took place at a peak potential of −0.71 V and −1.06 V for the first and second reduction wave, respectively. Kinetic analysis showed that the reduction reactions in presence of CO 2 followed first‐order, diffusion‐limited kinetics. The Cu/Au electrode exhibited high sensitivity (3.49×10 −1 μA μM −1 ) with an LOD of 0.46 μM for nitrate detection, and finally demonstrated excellent performance in real sample analysis.    

    

* The role of procurement activities in reducing the hydrocarbon footprint in the Arctic zone of the Russian Federation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402993335
:TOPICS: Arctic Shipping and Governance, Future Development of China's Coal Industry, Socio-Economic Development and Global Economic Challenges
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.24147/1812-3988.2024.22(1).50-60")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402993335"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402993335"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402993335"))][Get cited by]]

OpenAlex: https://openalex.org/W4402993335 (Open access: False)
    
[[https://openalex.org/A5046064748][Alexandra A. Saitova]], [[https://openalex.org/A5107666108][Enver R. Dzhemilev]], [[https://openalex.org/A5107666109][Tatyana P. Bozhikova]], Herald of Omsk University Series Economics. 22(1)] 2024. https://doi.org/10.24147/1812-3988.2024.22(1).50-60 
     
One of the main tasks of the modern energy industry is not only to maximize the efficient use of natural energy resources and preserve their diversity, but also to increase the potential of this sector in the stable growth of the state's economy, improving the quality of life of the population and maintaining a favorable environmental situation in the country. Decarbonization, which implies a reduction in carbon dioxide (CO<sub>2</sub>) and methane emissions, is a key challenge facing the global energy industry. The purpose of this study is to assess greenhouse gas emissions produced as a result of the activities of the largest energy companies operating in the Arctic zone of the Russian Federation, namely PJSC LUKOIL and PJSC NOVATEK through the analysis of their policies and measures to reduce the carbon footprint, preserve biological diversity and develop the northern region of Russia, identify links between the conduct of procurement activities and support for the sustainable development of the enterprise, including in the environmental field. In the course of the work, a comparative analysis of the activities of companies in the Arctic zone was carried out, their current and prospective projects were described, data on greenhouse gas emissions of the enterprises in question were structured by year, their procurement policy, the necessary requirements for potential suppliers, implemented educational programs and activities for the development of professional skills of personnel were considered, and additional tools were proposed that they will be able to contribute not only to improving the sustainable development of companies in the Arctic, but also, as a result, conservation of natural diversity in the northern part of the Russian Federation.    

    

* Effect of CO2 Concentration on the Performance of Polymer-Enhanced Foam at the Steam Front  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402868795
:TOPICS: Polymer Foaming with Supercritical Carbon Dioxide, Petroleum Chemistry and Analysis, Epoxy Resin Technology
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/polym16192726")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402868795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402868795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402868795"))][Get cited by]]

OpenAlex: https://openalex.org/W4402868795 (Open access: True)
    
[[https://openalex.org/A5103064863][Mingxuan Wu]], [[https://openalex.org/A5042731276][Binfei Li]], [[https://openalex.org/A5101224219][Liwei Ruan]], [[https://openalex.org/A5060048116][Chao Zhang]], [[https://openalex.org/A5037839739][Yongqiang Tang]], [[https://openalex.org/A5078319914][Zhaomin Li]], Polymers. 16(19)] 2024. https://doi.org/10.3390/polym16192726 
     
This study examines the impact of CO2 concentration on the stability and plugging performance of polymer-enhanced foam (PEF) under high-temperature and high-pressure conditions representative of the steam front in heavy oil reservoirs. Bulk foam experiments were conducted to analyze the foam performance, interfacial properties, and rheological behavior of CHSB surfactant and Z364 polymer in different CO2 and N2 gas environments. Additionally, core flooding experiments were performed to investigate the plugging performance of PEF in porous media and the factors influencing it. The results indicate that a reduction in CO2 concentration in the foam, due to the lower solubility of N2 in water and the reduced permeability of the liquid film, enhances foam stability and flow resistance in porous media. The addition of polymers was found to significantly improve the stability of the liquid film and the flow viscosity of the foam, particularly under high-temperature conditions, effectively mitigating the foam strength degradation caused by CO2 dissolution. However, at 200 °C, a notable decrease in foam stability and a sharp reduction in the resistance factor were observed. Overall, the study elucidates the effects of gas type, temperature, and polymer concentration on the flow and plugging performance of PEF in porous media, providing reference for fluid mobility control at the steam front in heavy oil recovery.    

    

* The Biochemistry of Artificial CO2-Fixation Pathways: The Exploitation of Carboxylase Enzymes Alternative to Rubisco  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403006956
:TOPICS: Metabolic Engineering and Synthetic Biology, Role of Lipoic Acid in Metabolism and Health, Enzyme Immobilization Techniques
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14100679")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403006956"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403006956"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403006956"))][Get cited by]]

OpenAlex: https://openalex.org/W4403006956 (Open access: True)
    
[[https://openalex.org/A5017636644][Immacolata Tommasi]], Catalysts. 14(10)] 2024. https://doi.org/10.3390/catal14100679 
     
The last decade has registered a rapid development of new artificial CO2-bioconversion processes mirroring natural CO2-fixation by carboxylation and/or reduction reactions. The development of artificial pathways has shown that we have sufficient tools to design and implement, both in vitro and in vivo, complex reaction sequences pointing to construct microbial cell-factories to produce target chemicals at scale. This review is aimed to focus on the most efficient artificial CO2-fixing autotrophic cycles based on the use of carboxylase enzymes that, similarly to Rubisco enzyme, build a C–CO2 bond by reacting an enediolate or an enolate anion with CO2. The development of artificial CO2-fixing autotrophic cycles encompasses the analysis of the complete library of natural carboxylase enzymes taking part in the so called “central” and “assimilation” metabolism to select only those enzymes characterized by high catalytic efficiency, great stability, high substrate affinity, and oxygen tolerability. The review analyzes the biochemistry of the most efficient artificial CO2-fixation pathways implemented up today, evidencing the biosynthetic strategies adopted, the development of replenishing routes, and their integration with cell metabolism.    

    

* Integrating Fuzzy MCDM Methods and ARDL Approach for Circular Economy Strategy Analysis in Romania  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402855456
:TOPICS: Multi-Criteria Decision Making, Conceptualizing the Circular Economy and Sustainable Supply Chains, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/math12192997")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402855456"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402855456"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402855456"))][Get cited by]]

OpenAlex: https://openalex.org/W4402855456 (Open access: True)
    
[[https://openalex.org/A5024081062][Camelia Delcea]], [[https://openalex.org/A5006579036][Ionuț Nica]], [[https://openalex.org/A5014427304][Irina Georgescu]], [[https://openalex.org/A5000409680][Nora Chiriță]], [[https://openalex.org/A5038908084][Cristian Ciurea]], Mathematics. 12(19)] 2024. https://doi.org/10.3390/math12192997 
     
This study investigates the factors influencing CO2 emissions in Romania from 1990 to 2023 using the Autoregressive Distributed Lag (ARDL) model. Before the ARDL model, we identified a set of six policies that were ranked using Fuzzy Electre, Topsis, DEMATEL, and Vikor. The multi-criteria decision-making (MCDM) methods have highlighted the importance of a circular policy on CO2 emission reduction, which should be a central focus for policymakers. The results of the ARDL model indicate that, in the long term, renewable energy production reduces CO2 emissions, showing a negative relationship. Conversely, an increase in patent applications and urbanization contributes to higher CO2 emissions, reflecting a positive impact. In total, five key factors were analyzed: CO2 emissions per capita, patent applications, gross domestic product, share of energy production from renewables, and urbanization. Notably, GDP does not significantly explain CO2 emissions in the long run, suggesting that economic growth alone is not a direct driver of CO2 emission levels in Romania. This decoupling might result from improvements in energy efficiency, shifts towards less carbon-intensive industries, and the increased adoption of renewable energy sources. Romania has implemented effective environmental regulations and policies that mitigate the impact of economic growth on CO2 emissions.    

    

* Adsorption and Catalytic Reduction of Nitrogen Oxides (NO, N2O) on Disulfide Cluster Complexes of Cobalt and Iron—A Density Functional Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402990736
:TOPICS: Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ma17194764")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402990736"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402990736"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402990736"))][Get cited by]]

OpenAlex: https://openalex.org/W4402990736 (Open access: True)
    
[[https://openalex.org/A5090426636][Ellie L. Uzunova]], [[https://openalex.org/A5088933747][Ivelina Georgieva]], Materials. 17(19)] 2024. https://doi.org/10.3390/ma17194764 
     
The reactivity of nitrogen oxide, NO, as a ligand in complexes with [Fe2-S2] and [Co2-S2] non-planar rhombic cores is examined by density functional theory (DFT). The cobalt-containing nitrosyl complexes are less stable than the iron complexes because the Co-S bonds in the [Co2-S2] core are weakened upon NO coordination. Various positions of NO were examined, including its binding to sulfur centers. The release of NO molecules can be monitored photochemically. The ability of NO to form a (NO)2 dimer provides a favorable route of electrochemical reduction, as protonation significantly stabilizes the dimeric species over the monomers. The quasilinear dimer ONNO, with trans-orientation of oxygen atoms, gains higher stability under protonation and reduction via proton–electron transfer. The first two reduction steps lead to an N2O intermediate, whose reduction is more energy demanding: in the two latter reaction steps the highest energy barrier for Co2S2(CO)6 is 109 kJ mol−1, and for Fe2S2(CO)6, it is 133 kJ mol−1. Again, the presence of favorable light absorption bands allows for a photochemical route to overcome these energy barriers. All elementary steps are exothermic, and the final products are molecular nitrogen and water.    

    

* Vaporizing temperate peatlands  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402907098
:TOPICS: Carbon Dynamics in Peatland Ecosystems
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5463/thesis.811")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402907098"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402907098"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402907098"))][Get cited by]]

OpenAlex: https://openalex.org/W4402907098 (Open access: False)
    
[[https://openalex.org/A5055608561][Jim Boonman]], No host. None(None)] 2024. https://doi.org/10.5463/thesis.811 
     
Peat decomposition causes soil subsidence and is responsible for greenhouse gas emissions. Peat forms under wet conditions, but in the Netherlands peatlands have been drained (by humans) for about a thousand years. The drained peat pastures are mainly being used for dairy production. In the drained peat soils with lower groundwater levels, oxygen enables high rates of peat decomposition. This peat decomposition has caused most peatlands to sink below sea level, and currently, these peatlands are still subsiding (on average 6 mm per year). Peat decomposition is also a major source of greenhouse gas emissions: in the Netherlands, about 4% of greenhouse gas emissions emerge from vaporizing peatlands. Rewetting peat could reduce decomposition rates and associated greenhouse gas emissions. This dissertation focuses on the effects of rewetting peatlands using water infiltration systems. Here, peatland hydrology, CO2 emissions and microbial soil processes are play a central role. Is a resilient future for peatlands within close reach? Under normal conditions, the hydraulic conductivity of peat is too low to maintain steady groundwater levels by ditch water infiltration during drier periods. The aforementioned water infiltration systems consist of underground drainage pipes that transport ditch water to the centre of a peat pasture. In this dissertation it is demonstrated that under certain conditions and to a certain extent, these water infiltration systems (1) successfully raise groundwater levels, (2) substantially reduce CO2 emissions from peat, and (3) influence microbial decomposition processes in the soil. Also, the thesis presents (1) the foundation for a new, national model to estimate peat degradation under aerobic conditions, (2) an accessible method to measure microbial decomposition processes in the soil, (3) a high-frequency dataset of CO2 fluxes from peat pastures determined using automatic flux chambers, and (4) new relationships to estimate annual CO2 fluxes based on average groundwater levels. The chapters in this thesis may contribute to improving the monitoring of greenhouse gases from peat. Throughout the dissertation, the automatic chambers play a major role in measuring emissions from peat. The thesis also discusses how alternative methods could be used to improve the understanding of peat degradation processes and the associated emissions. For example, the second chapter lays the foundation for a national model (SOMERS) to estimate greenhouse gas emissions from peat (and emission reductions), the third chapter lays the foundation for a direct measurement method for degradation processes and emissions at different soil depths, and the fifth chapter shows how groundwater levels can be used as an indicator for emissions. Furthermore, the insights presented on emission reduction may help in practical decision-making by provinces and water boards. The Dutch government has decided in the Climate Agreement that CO2 emissions from peatlands must be reduced by one megaton (25%) by 2030. The results in the thesis illustrate to what extent the implementation of water infiltration systems can contribute to this reduction. Besides water infiltration systems, other solutions are also available that lead to emission reductions (e.g., wet crops and nature restoration), each having their pros and cons. For policymaking, not only the reduction of peat degradation, soil subsidence and CO2 emissions play a role, but also economic feasibility, farmers' interests, biodiversity, soil contamination, water quality, water availability, nitrogen emissions and landscape culture should be taken into account. Towards harmony in (agri)culture and peat preservation! This PhD thesis is part of the Netherlands Research Program on Greenhouse Gas Dynamics in Peatlands and Organic Soils (NOBV). Within this program, high-tech peatland measurement locations have been set up to quantify peatland greenhouse gas emissions, and effects of different (land management and/or hydrological) treatments on these emissions.    

    

* Regional impacts of solar radiation modification on surface temperature and precipitation in Mainland Southeast Asia and the adjacent oceans  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402982875
:TOPICS: Solar Physics and Space Weather, Stratospheric Chemistry and Climate Change Impacts, Geoengineering and Climate Ethics
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41598-024-73149-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402982875"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402982875"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402982875"))][Get cited by]]

OpenAlex: https://openalex.org/W4402982875 (Open access: True)
    
[[https://openalex.org/A5001927660][Pornampai Narenpitak]], [[https://openalex.org/A5045183820][Siriwat Kongkulsiri]], [[https://openalex.org/A5004990734][Saifhon Tomkratoke]], [[https://openalex.org/A5067929195][Sirod Sirisup]], Scientific Reports. 14(1)] 2024. https://doi.org/10.1038/s41598-024-73149-6 
     
Solar radiation modification (SRM) has been proposed to temporarily reduce anthropogenic warming. This study presents an assessment of the regional impacts of SRM via solar dimming and stratospheric aerosol injection (SAI) on temperature and precipitation over 0°-30° N and 90° E-110° E, covering Mainland Southeast Asia and adjacent oceans. Using data from the Geoengineering Model Intercomparison Project Phase 6 (GeoMIP6), we examine regional impacts of SRM using three SRM experiments: (1) G6Sulfur, which reduces radiative forcing from the high-emission SSP5-8.5 scenario to the moderate-emission SSP2-4.5 scenario by injecting sulfate aerosols; (2) G6Solar, which similarly reduces radiative forcing from the high-emission to moderate-emission scenarios but by uniformly reducing the solar constant; and (3) G1ext, which reduces radiative forcing from a quadrupled carbon dioxide concentration to pre-industrial levels by uniform solar constant reduction. Our findings show that higher greenhouse gas emissions increase overall precipitation, along with tendencies to have extreme rainfall events and more dry episodes in between. While SRM can partially cool down the surface temperature warming caused by increased greenhouse gas emissions, its effects on precipitation are complex: Solar dimming in G6Solar and G1ext tends to reduce overall precipitation, and tropical sulfate injection in G6Sulfur could lead to further drying in the tropics because of the stratospheric warming associated with the injected aerosols. Different SRM strategies might result in different responses on precipitation.    

    

* Promoting the sustainable construction: A scientometric review on the utilization of waste glass in concrete  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402865645
:TOPICS: Influence of Recycled Aggregate Concrete on Construction, Geopolymer and Alternative Cementitious Materials, Fiber Reinforced Concrete in Civil Engineering
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1515/rams-2024-0036")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402865645"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402865645"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402865645"))][Get cited by]]

OpenAlex: https://openalex.org/W4402865645 (Open access: True)
    
[[https://openalex.org/A5085624916][Amir Qayyum]], [[https://openalex.org/A5058875606][Muhammad Faisal Javed]], [[https://openalex.org/A5090455166][Raheel Asghar]], [[https://openalex.org/A5024669392][Ammar Iqtidar]], [[https://openalex.org/A5023000265][Hisham Alabduljabbar]], [[https://openalex.org/A5073427380][Mohsin Ali Khan]], [[https://openalex.org/A5021896593][Mujahid Ali]], REVIEWS ON ADVANCED MATERIALS SCIENCE. 63(1)] 2024. https://doi.org/10.1515/rams-2024-0036 
     
Abstract Concrete is the second-most used material globally and significantly impacts the environment by emitting a large amount of carbon dioxide (CO 2 ). This scientometric review investigates the sustainable use of waste glass (WG) in concrete. Our study examines the impact of waste glass powder (WGP) on the mechanical and fresh characteristics of concrete and its environmental implications, enhanced by a machine learning prediction model. We observed a progressive increase in research activity on WGP-based concrete since 2000, indicating the growing interest in this area. The primary focus areas are engineering and material science, reflecting the application potential, structural performance, and material properties of WGP-based concrete. Our discussions highlight the significant benefits of WGP in concrete, including its potential to reduce landfill usage, environmental pollution, and enhance properties such as strength, sulfate resistance, alkali–silica reaction resistance, and freeze–thaw resistance. The review also explores the microstructure of glass powder (GP)-based concrete, illuminating the complex interactions between glass particles and the concrete matrix, which influence the material’s overall performance. Environmental impact assessments underscore the necessity for sustainable construction practices and waste reduction. Utilizing machine learning prediction models helps optimize the composition of GP-based concrete, thus enhancing material performance and durability. This review provides a comprehensive analysis of using WG in concrete, contributing to the field’s understanding and informing future research and innovations to optimize WG use in concrete applications.    

    

* Phytoplankton as CO2 Sinks: Redirecting the Carbon Cycle  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402856285
:TOPICS: Microalgae as a Source for Biofuels Production, Marine Biogeochemistry and Ecosystem Dynamics, Impact of Ocean Acidification on Marine Ecosystems
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/app14198657")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402856285"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402856285"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402856285"))][Get cited by]]

OpenAlex: https://openalex.org/W4402856285 (Open access: True)
    
[[https://openalex.org/A5036461789][Basilio Zafrilla]], [[https://openalex.org/A5018576694][Laura Matarredona]], [[https://openalex.org/A5001519037][María‐José Bonete]], [[https://openalex.org/A5068543560][Guillermo Zafrilla]], [[https://openalex.org/A5071156581][Julia Esclapez]], Applied Sciences. 14(19)] 2024. https://doi.org/10.3390/app14198657 
     
Since the Industrial Revolution, nearly 700 Gt of carbon (GtC) have been emitted into the atmosphere as CO2 derived from human activities, of which 292 GtC remain uncontrolled. By the end of this century, the atmospheric CO2 concentration is predicted to surpass 700 ppm. The effects of this sudden carbon release on the worldwide biogeochemical cycles and balances are not yet fully understood, but global warming and climate change are undeniable, with this gas playing a starring role. Governmental policies and international agreements on emission reduction are not producing results quickly enough, and the deadline to act is running out. Biological CO2 capture is a fast-acting carbon cycle component capable of sequestering over 115 GtC annually through photosynthesis. This study analyses a hypothetical scenario in which this biological CO2 capture is artificially enhanced through the large-scale cultivation of phytoplankton in partially natural photobioreactors (PBRs). To develop this approach, the current figures of the carbon cycle have been updated, and the key aspects of phytoplankton cultivation technology have been analysed. Our results show that a global increase of 6.5% in biological capture, along with the subsequent stabilization of the produced biomass, could counteract the current CO2 emission rate and maintain atmospheric levels of this gas at their current levels. Based on a review of the available literature, an average production rate of 17 g/m2·day has been proposed for phytoplankton cultivation in horizontal PBRs. Using this value as a key reference, it is estimated that implementing a large-scale production system would require approximately 2.1 × 106 km2 of the Earth’s surface. From this, a production system model is proposed, and the key technological and political challenges associated with establishing these extensive cultivation areas are discussed.    

    

* 176 Reducing travel distances in Sport – good for people and the planet  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402869250
:TOPICS: Influence of Built Environment on Active Travel
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/eurpub/ckae114.108")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402869250"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402869250"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402869250"))][Get cited by]]

OpenAlex: https://openalex.org/W4402869250 (Open access: True)
    
[[https://openalex.org/A5010664383][Karim Abu‐Omar]], [[https://openalex.org/A5012468659][Derya Özer Kaya]], [[https://openalex.org/A5008881602][Antonina Tcymbal]], [[https://openalex.org/A5065306718][Tobias Volk]], European Journal of Public Health. 34(Supplement_2)] 2024. https://doi.org/10.1093/eurpub/ckae114.108 
     
Abstract Purpose Globally, about 30% of CO2 emissions are caused by travel. In order to comply with calls of the United Nations and the European Commission, the sport sector needs to reduce its emissions caused by travel to tournaments and league games in professional and amateur sport. To this date, no clear mechanisms exists on how to do this. The presentations shows how an algorithm based solution from optimisation science can help sport federations reducing travel distances in any type of league or tournament play. Methods The sport federations of American Football (16 adolescent teams), Biathlon (IBU World Cup Series) and Gymnastics (64 1st and 2nd division Faustball teams) provided data on team locations, league play and tournament formats. Locations of teams and tournaments were mapped with Google Maps, and travel distances (straight-line, by car) were analysed. The algorithm Gurobi from optimisation science was used to optimise league play and tournaments to minimise total travel distances. Results For American Football, 16 adolescent teams travel in total 6329 km (396 km per team) for a season of league play in 2024. The IBU World Cup featuring 10 events for the 2023/24 season results in 13466 km of travel for each participant. In both instances, the optimisation algorithm can propose significant reductions in travel distances. For the IBU World Cup, changing the order of tournaments can reduce travel distances by more than 30%. The analysis of Faustball data is ongoing. Conclusions Travel distances in amateur and professional sport are a significant source of CO2 emissions. Algorithm based optimisation of league and tournament play to reduce travel distances has good potential to put the sport sector more in line with CO2 reduction targets agreed upon in the Paris Agreement. Support/Funding Source No external funds.    

    

* Road construction in arid zones: valuation of local materials  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402941806
:TOPICS: Land-Use Suitability Assessment Using GIS
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54021/seesv5n2-259")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402941806"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402941806"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402941806"))][Get cited by]]

OpenAlex: https://openalex.org/W4402941806 (Open access: False)
    
[[https://openalex.org/A5021810395][Adam Mustapha]], [[https://openalex.org/A5107587920][Abdeldjalil M’hammed]], [[https://openalex.org/A5089239910][Moulay Omar Hassan]], [[https://openalex.org/A5107421911][Djaafari Driss]], [[https://openalex.org/A5005654965][Bennacer Lyacine]], [[https://openalex.org/A5015655652][Mohammed Abbou]], [[https://openalex.org/A5107627223][Belaidi Khedidja]], STUDIES IN ENGINEERING AND EXACT SCIENCES. 5(2)] 2024. https://doi.org/10.54021/seesv5n2-259 
     
The materials constituting the pavement bodies, until today, have been limited to certain so-called noble materials (rolled sands, aggregates, etc.), but these are in the process of being exhausted under the effect of intensive exploitation and the scarcity of quality quarries. With the objective of preserving the deposits of aggregates in the process of exhaustion for future generations and of exploiting the aeolian sands in abundance in the regions of southern Algeria, we aim to enhance the latter in the body of the roadway mixed with the tuffs, this would imply a reduction in construction costs (use of local aggregates of lower quality available in large quantities, reduction in transport costs). From an environmental point of view, this would limit the impacts with a reduction in CO2 emissions linked to transport. In this work, we applied a new approach based on the technique of mixtures to valorize and exploit the sand of dunes existing in abundance, with the treatment in hydraulic binders, which allowed us to go up to 20% of sand dunes.    

    

* Effect of Customized Fertilizer Formulations on Brinjal (Solanum melongena L.) under Sodic Soil  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402991788
:TOPICS: Management of Soil Fertility and Crop Productivity, Deficit Irrigation for Agricultural Water Management, Factors Affecting Maize Yield and Lodging Resistance
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.9734/ajsspn/2024/v10i4391")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402991788"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402991788"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402991788"))][Get cited by]]

OpenAlex: https://openalex.org/W4402991788 (Open access: True)
    
[[https://openalex.org/A5083553064][Sherene Jenita Rajammal]], [[https://openalex.org/A5103665465][A. Kaleeswari T]], [[https://openalex.org/A5081381388][S. Maragatham]], [[https://openalex.org/A5012762880][R. Arulmozhian]], Asian Journal of Soil Science and Plant Nutrition. 10(4)] 2024. https://doi.org/10.9734/ajsspn/2024/v10i4391 
     
The Customized Fertilizer Formulation (CFF) applications on growth and yield of Brinjal (Solanum melongena L.) varieties Manaparai local and CO-2 under sodic soils were studied with eleven CFF combinations. No Significant observations in growth yield and yield parameter was recorded due to the combined application of CFF and organic amendments on sodic soils. The symptoms of salt injury were well pronounced in brinjal cv. Manaparai local when compared to brinjal cv. CO2 though the sodic soil reclamation was done with gypsum @1.1 t/Ha. The salt injury was further confirmed with electrolyte leakage study conducted at field level. However, the treatment T11 i.e. CFF2 100% macro nutrients as straight fertilizers, liquid micronutrient formulation and composted Press mud @ 5 t/ha was found to have the brinjal fruit yield of 1.39 t/ha in cv. CO2 which was not a desirable yield. This might be due to the yield reduction per unit increase in salt content.    

    

* Impacts of ocean acidification and hypoxia on cellular immunity, oxygen consumption and antioxidant status in Mediterranean mussel  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402905650
:TOPICS: Impact of Ocean Acidification on Marine Ecosystems, Impact of Aquaculture on Marine Ecosystems and Food Supply, Metabolic Theory of Ecology and Climate Change Impacts
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fsi.2024.109932")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402905650"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402905650"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402905650"))][Get cited by]]

OpenAlex: https://openalex.org/W4402905650 (Open access: False)
    
[[https://openalex.org/A5027196600][A. Yu. Andreyeva]], [[https://openalex.org/A5020556134][Т. А. Кухарева]], [[https://openalex.org/A5107533843][Olga L Gostyukhina O L]], [[https://openalex.org/A5045058680][O. Yu. Vialova]], [[https://openalex.org/A5065673405][A.A. Tkachuk]], [[https://openalex.org/A5019899684][Э. С. Челебиева]], [[https://openalex.org/A5007795939][Maria S Podolskaya]], [[https://openalex.org/A5069087246][А. Б. Боровков]], [[https://openalex.org/A5036867050][T. V. Gavruseva]], [[https://openalex.org/A5092277092][Daria S. Lavrichenko]], [[https://openalex.org/A5069213275][Е. С. Кладченко]], Fish & Shellfish Immunology. None(None)] 2024. https://doi.org/10.1016/j.fsi.2024.109932 
     
There is growing recognition that the hypoxic regions of the ocean are also becoming more acidic due to increasing levels of global carbon dioxide emissions. The impact of water acidification on marine life is largely unknown, as most previous studies have not taken into account the effects of hypoxia, which may affect how organisms respond to low pH levels. In this study, we experimentally examined the consequences of water acidification in combination with normoxic or hypoxic conditions on cellular immune parameters in Mediterranean mussels. We measured total hemocyte counts in hemolymph, the cellular composition of hemolymph, phagocytosis, reactive oxygen species (ROS) production. General response of the organism was evaluated on the basis of the activity of antioxidant enzymes in the hepatopancreas, as well as respiratory rates over an 8-day exposure period. The mussels were exposed to low pH conditions (7.3), either under normoxic conditions (dissolved oxygen concentration of 8 mg/L) or hypoxic conditions (dissolved oxygen concentration of 2 mg/L). The parameters were assessed at days 1, 3, 6, and 8 of the experiment. Experimental acidification under normoxic conditions reduced THC and ROS production by hemocytes during later stages of exposure, but phagocytic activity (PA) only decreased at day 3 and then recovered. Combined acidification and hypoxia suppressed PA in hemocytes at the beginning of exposure, while hemocyte ROS production and THC decreased by the end of the experiment. The hemolymph cellular composition and activity of antioxidant enzymes were unaffected by acidified conditions under different oxygen regimes, but mussel respiratory rate (RR) decreased with a more significant reduction in oxygen consumption under hypoxia. Mussels showed a relatively high tolerance to acidification in combination with various dissolved oxygen levels, although prolonged acidification exposure led to increased detrimental effects on immunity and metabolism.    

    

* Numerical Investigation of CO and NO Production from Premixed Hydrogen/Methane Fuel Blends  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402939147
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Power Generation and Energy Systems
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1115/1.4066701")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402939147"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402939147"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402939147"))][Get cited by]]

OpenAlex: https://openalex.org/W4402939147 (Open access: False)
    
[[https://openalex.org/A5073331547][Sarbjit Singh]], [[https://openalex.org/A5088837000][Harish Rajagopalan]], [[https://openalex.org/A5028739615][Benjamin Emerson]], [[https://openalex.org/A5077986149][David R. Noble]], [[https://openalex.org/A5005647340][Robert C. Steele]], [[https://openalex.org/A5082528509][Tim Lieuwen]], Journal of Engineering for Gas Turbines and Power. None(None)] 2024. https://doi.org/10.1115/1.4066701 
     
Abstract There is significant interest in utilizing hydrogen as an energy carrier in a net-zero carbon energy economy. A variety of fundamental and practical issues associated with premixed hydrogen/methane combustion must be addressed, particularly flame flashback, combustion instabilities, and NOx emissions. Significantly less attention has been given to CO emissions from hydrogen blending. However, recent H2 blending engine tests have clearly noted major reductions in CO emissions, reductions which substantially exceed what would be expected based upon C atom mass balances in the fuel. Moreover, NOx, CO, and combustor operability always tradeoff with each other, and so for example, these CO reductions can also enable operational or design modifications to reduce NOx emissions and/or wider operability windows. This paper addresses H2 blending effects on CO emissions, addressing both the direct influences on CO emissions, as well as how it influences NOx-CO tradeoffs. The paper presents computations that differentiate between the kinetic and equilibrium effects of H2 blending, as well as how H2 blending can lead to reductions in both NOx and CO by moving the Pareto front downward. Finally, this work suggests that H2 blending, in addition to its CO2 reductions, can also increase plant operational flexibility and so provide additional value propositions to an evolving electricity market.    

    

* Comparative Analysis of the Relationship between Renewable Energy Adoption, Fossil Fuel Energy Consumption, and CO<sub>2</sub> Emission in the United States and China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402884323
:TOPICS: Economic Impact of Environmental Policies and Resources, Life Cycle Assessment and Environmental Impact Analysis, Rebound Effect on Energy Efficiency and Consumption
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21926/aeer.2403018")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402884323"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402884323"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402884323"))][Get cited by]]

OpenAlex: https://openalex.org/W4402884323 (Open access: False)
    
[[https://openalex.org/A5107621559][Christiana Chioma Efe-Onakpojeruo]], [[https://openalex.org/A5081786377][Mehdi Seraj]], [[https://openalex.org/A5036299024][Hüseyin Özdeşer]], Advances in Environmental and Engineering Research. 05(03)] 2024. https://doi.org/10.21926/aeer.2403018 
     
This study addresses the critical issue of carbon dioxide (CO<sub>2</sub>) emissions, focusing on understanding the intricate interplay between four major variables Gross Domestic Product per capita (GDPC), Renewal Energy (RE), Fossil Fuel energy consumption (FF), and Patent application (PTS). This research is crucial due to the emerging negative impacts of climate change, which will create a disastrous future for human beings. It focuses on three decades from 1990 to 2020 and compares the results between the United States and China. Underlying long-run relationships and unit root characteristics of the variables are analyzed with the help of unit root tests, cointegration analysis, descriptive statistics, and an autoregressive distributed lag (ARDL) model. The analysis shows that the examined variables are strongly related and significantly impact CO<sub>2</sub> emission. For example, GDPC and PTS have a positive relationship with CO<sub>2</sub> emissions, Whereas wider use of RE has a negative effect on emissions. The findings, therefore, emphasize the need for country-specific emission reduction policies because of the differences between the Chinese and the American systems. In conclusion, this study detects that the interaction between economic growth and technology and energy utilization are major influential factors that need to be incorporated in developing efficient policies to minimize the emission of CO<sub>2</sub>. It is helpful for policymakers and those interested in environmental conservation as it stresses that combating climate change requires differentiated approaches in distinct countries. This research moves beyond extant literature by adopting a novel comparative methodology to analyze the shifts in the process of CO<sub>2</sub> emission in two of the world’s largest economies. Hence, it captures the interaction of GDPC, RE adoption, FF consumption, and PTS on CO<sub>2</sub> emissions, which is crucial for formulating environmental policies and future emission control strategies.    

    

* A novel approach to estimate building electric power consumption based on machine learning method: toward net-zero energy, low carbon and smart buildings  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402932603
:TOPICS: Electricity Price and Load Forecasting Methods, Building Energy Efficiency and Thermal Comfort Optimization, Machine Learning Methods for Solar Radiation Forecasting
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/ijlct/ctae084")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402932603"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402932603"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402932603"))][Get cited by]]

OpenAlex: https://openalex.org/W4402932603 (Open access: True)
    
[[https://openalex.org/A5013561618][Badr Saad Alotaibi]], [[https://openalex.org/A5023045589][Mohammed Awad Abuhussain]], [[https://openalex.org/A5083803962][Yakubu Aminu Dodo]], [[https://openalex.org/A5047459537][Nedhal Al-Tamimi]], [[https://openalex.org/A5088861253][Ammar Maghrabi]], [[https://openalex.org/A5029183147][Henry Ojobo]], [[https://openalex.org/A5067899491][Ahmad Usman Naibi]], [[https://openalex.org/A5107587036][Natei Ermias Benti]], International Journal of Low-Carbon Technologies. 19(None)] 2024. https://doi.org/10.1093/ijlct/ctae084 
     
Abstract The modern era has witnessed a surge in energy consumption and its dependence on fossil fuels, which are harmful to the environment, prompting researchers to examine techniques for regulating energy usage in buildings, specifically with regard to residential electricity consumption. The pursuit of net-zero energy consumption and low carbon emission buildings is a significant undertaking that nations across the globe are actively endeavoring to accomplish. In order to accomplish this goal, the structure in question must efficiently oversee its overall energy usage while concurrently capitalizing on sustainable energy sources. The precise estimation of future electricity usage in buildings is an essential element in the process of energy efficiency planning and optimization. The present study introduces a soft computing methodology and data decomposition as approaches for evaluating the energy usage of residential structures. An innovative machine learning approach is introduced for the purpose of estimating the initial cost required to construct a green structure that consumes no net energy. By utilizing wavelet decomposition, it is possible to determine how to transform the structure into one that is intelligent and energy efficient. Following wavelet parallel converter analysis, the data were processed with an estimator model based on an ideal neural network. The results indicate that the mean estimation errors for recurrent neural network, Autoregressive fractionally integrated moving average (ARFIMA), and gene expression programming (GEP) were reduced by 72%, 65%, and 77%, respectively, using this method. Conversely, when the proposed methodology is applied to the smart management of building energy consumption, the examined structures experience an average reduction of 8% in energy consumption. Moreover, the outcomes of CO2 gas emissions demonstrate that the suggested model possesses the capability to accurately forecast CO2 emissions. The study highlights the necessity of employing innovative techniques such as machine learning to decrease building energy usage and CO2 emissions. The discovery of these results can assist policymakers and stakeholders in the energy sector in advancing the adoption of smart building technologies.    

    

* Energy Efficiency and Sustainability in Food Retail Buildings: Introducing a Novel Assessment Framework  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402964044
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization, Sustainable Construction and Green Building, Impact of Workspace Environment on Work Performance
:PUBLICATION_DATE: 2024-09-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17194882")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402964044"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402964044"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402964044"))][Get cited by]]

OpenAlex: https://openalex.org/W4402964044 (Open access: True)
    
[[https://openalex.org/A5092187752][Simone Forastiere]], [[https://openalex.org/A5050106530][Cristina Piselli]], [[https://openalex.org/A5095886883][Andrea Silei]], [[https://openalex.org/A5026880138][Fabio Sciurpi]], [[https://openalex.org/A5038114517][Anna Laura Pisello]], [[https://openalex.org/A5067111142][Franco Cotana]], [[https://openalex.org/A5070746225][Carla Balocco]], Energies. 17(19)] 2024. https://doi.org/10.3390/en17194882 
     
One of the primary global objectives is to decrease building energy consumption to promote energy efficiency and environmental sustainability. The large-scale food retail trade sector accounts for over 15% of total primary energy consumption in Europe, posing a significant challenge to the transition towards green energy. This study proposes a simple method for energy efficiency, environmental sustainability, and cost-saving assessment and improvement in large-scale food retail trade buildings. It aims to analyze the energy and environmental performance of building–plant systems, establishing an interactive network to assess intervention potential for the energy transition. The investigation focuses on the proper selection and analysis of the benefits of retrofit solution implementation, emphasizing potential energy savings in current and future climate change scenarios. Dynamic simulation with the Building Energy Model (BEM) was used to evaluate the impacts of building–plant system retrofit solutions, such as high thermal insulation, photovoltaic (PV) panels, Light Emitting Diode (LED) installation, waste heat recovery, and improvement in refrigeration units. The results show a reduction in annual energy consumption for the PV panel installation by up to 29% and lighting systems with high-quality LED to 60%. Additionally, CO2 emissions can be decreased by up to 41% by combining these two strategies.    

    

* Smart Monitoring of Microgrid-Integrated Renewable-Energy-Powered Electric Vehicle Charging Stations Using Synchrophasor Technology  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402824679
:TOPICS: Integration of Electric Vehicles in Power Systems, Lithium-ion Battery Management in Electric Vehicles, Control and Synchronization in Microgrid Systems
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/wevj15100432")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402824679"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402824679"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402824679"))][Get cited by]]

OpenAlex: https://openalex.org/W4402824679 (Open access: True)
    
[[https://openalex.org/A5082228855][B Deepa]], [[https://openalex.org/A5072418821][Santoshkumar Hampannavar]], [[https://openalex.org/A5066076753][Swapna Mansani]], World Electric Vehicle Journal. 15(10)] 2024. https://doi.org/10.3390/wevj15100432 
     
With the growing concern over climate change and energy security, the Government of India expedited enhancing the share of renewable energy (RE) derived from solar, wind and biomass sources within the energy blend. In this paper, a techno-economic and environmental analysis of a microgrid-integrated electric vehicle charging stations fueled by renewable energy is proposed for a typical area in the State of Karnataka, South India. The power transaction with the grid and the sell-back price to the national grid were investigated. Carbon emissions were also assessed, and 128,406 CO2 kg/Yr can be saved in the grid-connected mode. Also, in this work, different scenarios such as injecting active power, reactive power, and active and reactive power, and injecting active and absorbing reactive power to the grid are comprehensively assessed. Out of four types, type 3 (inject real and reactive power) provides significant reduction in power losses by up to 80.99%. The synchrophasor-technology-based monitoring method is adopted in order to enhance the microgrid system’s overall performance. The execution times for different cases with distributed generators (DGs) and electric vehicle charging stations (EVCSs) for conventional systems and micro-phasor measurement units (µPMU) were observed to be 19.07 s and 5.64 s, respectively, which is well accepted in the case of online monitoring.    

    

* The Effects of Rice Husk Ash as Bio-Cementitious Material in Concrete  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402858170
:TOPICS: Geopolymer and Alternative Cementitious Materials, Fiber Reinforced Concrete in Civil Engineering, 3D Concrete Printing Technology
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/constrmater4030034")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402858170"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402858170"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402858170"))][Get cited by]]

OpenAlex: https://openalex.org/W4402858170 (Open access: True)
    
[[https://openalex.org/A5057615757][Mays Mahmoud Alsaed]], [[https://openalex.org/A5085660085][Rizwan Alim Mufti]], Construction Materials. 4(3)] 2024. https://doi.org/10.3390/constrmater4030034 
     
Concrete is one of the most commonly used materials in civil engineering construction, and it continues to have increased production. This puts pressure on the consumption of its constituent materials, including Portland cement and aggregates. There are environmental consequences related to the increased emission of CO2 that are associated with the production process of Portland cement. This has led to the development and use of alternative cementitious materials, mainly in the form of condensed silica fume, pulverised fuel ash, and ground granulated blast furnace slag. All of these are by-products of the silicon, electrical power generation, and iron production industries, respectively. In recent years, attention has turned to the possible use of sustainable bio-waste materials that might contribute to the replacement of Portland cement in concrete. This research investigates the effects of using rice husk ash as cement replacement material on the 1 to 28-day concrete properties, including the compressive strength, workability, and durability of concrete. The findings indicate that including rice husk ash in concrete can improve its strength at 3–28 days for percentage replacements of 5% to 20% (ranging from 2.4% to 18.7% increase) and improvements from 1 day for 20% replacement (with 11.1% increase). Any percentage replacement with rice husk ash also reduced the air permeability by 21.4% and therefore improved the durability, while there was a small reduction in the workability with increased replacement.    

    

* Adaptive investment behaviours enable earlier carbon peak in low-carbon electricity transition  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402923944
:TOPICS: Global Energy Transition and Fossil Fuel Depletion
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-5075643/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402923944"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402923944"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402923944"))][Get cited by]]

OpenAlex: https://openalex.org/W4402923944 (Open access: False)
    
[[https://openalex.org/A5062602992][Hongyang Zou]], [[https://openalex.org/A5013271776][Huibin Du]], [[https://openalex.org/A5026676538][Jian Zuo]], [[https://openalex.org/A5007307922][Gang He]], [[https://openalex.org/A5049493168][Kuishuang Feng]], [[https://openalex.org/A5072261499][Yuting Yang]], [[https://openalex.org/A5101409236][Chengshan Wang]], [[https://openalex.org/A5080304378][Lixin Tang]], [[https://openalex.org/A5090675889][Marilyn A. Brown]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-5075643/v1 
     
Abstract Electricity planning often employs average production costs and efficiencies, assuming that energy companies are homogeneous. In reality, firms are heterogeneous in the scale, cost and efficiency of their power generation, leading to various adaptive behaviours such as differentiated investments in CO2 reductions and offsets. This has resulted in misjudgments about climate tipping points and unanticipated delays in phasing out coal-fired technology. Here we develop an agent-based model using company-level technology-specific installed capacity, cost and efficiency within China’s electricity sector. We estimate renewable energy expansion and carbon peaks by simulating companies’ adaptive behaviours. The results indicate that if such behaviours focused on technology stock and return-on-investment, China’s electricity sector could have reached carbon peak by 2019-2020, ahead of the national 2030 target. By analyzing adaptive investment behaviours, we pinpoint distinct profit strategies for companies with varying technology capacities. This enables tailored incentives, avoiding the fiscal inefficiencies of one-size-fits-all policies like uniform feed-in-tariffs. Our behavioural analysis further illustrates that the delayed phase-out of coal-fired technology, due to lock-in effects, could result in coal power overcapacity and hinder the operation of renewable energy generation. Policies to accelerate the phase-out of coal capacity are becoming increasingly imperative relative to incentivizing the scale-up of renewables.    

    

* Monitoring and adjustments of combustion parameters in reheating furnaces using a digital tool  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402964415
:TOPICS: Power Generation and Energy Systems, Coal Water Slurry Technology and Utilization, Inverse Radiative Heat Transfer Analysis
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.70342/dyin3512")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402964415"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402964415"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402964415"))][Get cited by]]

OpenAlex: https://openalex.org/W4402964415 (Open access: False)
    
[[https://openalex.org/A5072017433][Kássio Nogueira Cançado]], [[https://openalex.org/A5013913599][Aristides Almeida Rocha]], [[https://openalex.org/A5107630316][Rafaela Rapalo]], [[https://openalex.org/A5004967609][Paula Pomaro]], [[https://openalex.org/A5052506374][Lis Nunes Soares]], No host. 1(2)] 2024. https://doi.org/10.70342/dyin3512 
     
Improving the energy efficiency of a reheating furnace is not a simple task because it involves a large number of parameters that, most of the time, are connected in a complex way. To be feasible, the evaluation of such a vast number of variables must be supported by digital tools that are embedded with artificial intelligence. The SMS group has developed a digital tool that effectively supports operators and engineers in enhancing energy efficiency within the reheating furnaces of hot rolling mills. This paper presents a quick study case of the use of Viridis Performance, an application of Viridis Energy & Sustainability Suite, in the analysis and correction of the deviations in the air-gas ratio of a reheating furnace. In this study, a production period of 8 hours was evaluated, during which the air-gas ratio presented a significant deviation. Analysis showed that the probable cause of the deviation was a production stoppage where the furnace control was set to manual mode. A reduction potential of 0.26 Gcal/h and a 13 kg/h decrease in CO2 emissions were identified. Viridis Performance would support the process by guiding the decisions of the operator in a way that energy losses would be avoided or minimized. The potential economic savings were also quantified. This task is performed in the system by Viridis Moneybox, which is another application of Viridis Energy & Sustainability Suite. The results showed potential savings of 13 US $/h. In addition to the gains and savings outlined in this study, the utilization of Viridis Performance encompasses numerous other advantages, such as enhanced operational standardization and improved process capability, to name just a few.    

    

* Selenium Biofortification of Pleurotus Mushrooms and Utilization of Spent Waste for Vermicomposting: A Sustainable Approach for Circular Agriculture  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402928621
:TOPICS: Medicinal Mushrooms: Antitumor and Immunomodulating Properties, Mycorrhizal Fungi and Plant Interactions, Plant-Parasitic Nematodes in Molecular Plant Pathology
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18805/ag.d-6060")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402928621"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402928621"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402928621"))][Get cited by]]

OpenAlex: https://openalex.org/W4402928621 (Open access: True)
    
[[https://openalex.org/A5107553834][H. Abinaya]], [[https://openalex.org/A5091140709][M. Haritha]], [[https://openalex.org/A5074923062][SINDHU SINDHU]], [[https://openalex.org/A5107586520][C.A. Annaporani]], [[https://openalex.org/A5061444657][D. Lavanya]], Agricultural Science Digest - A Research Journal. None(Of)] 2024. https://doi.org/10.18805/ag.d-6060 
     
Background: Agro-wastes represent valuable resources for mushroom cultivation, particularly Pleurotus species, which offer significant nutritional benefits and are grown using cost-effective methods. Selenium (Se), an essential micronutrient crucial for human health, is vital for preventing various diseases. Sodium selenite has emerged as an effective method for increasing selenium levels in mushrooms, thereby enhancing their nutritional quality. Additionally, utilizing biofortified spent mushroom waste for vermicomposting presents a sustainable solution for recycling organic waste and improving soil fertility. Methods: This study examines the biofortification of three Pleurotus species by applying sodium selenite in paddy straw substrate. The research investigates selenium accumulation and its impact on yield and biological efficiency, in addition to assessing various biochemical parameters. Furthermore, the study explores the influence of selenium-biofortified spent mushroom waste on the growth of earthworms during the vermicomposting process. Result: Our investigation into the biofortification of mushrooms with selenium revealed that incorporating 5% of sodium selenite into the substrate significantly enhanced the selenium content of Pleurotus ulmarius (CO2), Pleurotus florida and Pleurotus eous (APK1). However, increasing selenium content in the substrate correlated with decreased biological efficiency. Selenium biofortification resulted in a noteworthy increase in protein content alongside a reduction in carbohydrate levels. Moreover, utilizing selenium-biofortified spent mushroom waste (SeSMS) at a concentration of 2.5% in combination with cow dung (1:10) yielded favorable outcomes, including enhanced cocoon production and the presence of young and adult worms during vermicomposting on both the 60th and 90th day.    

    

* Accelerated training of deep learning surrogate models for surface   displacement and flow, with application to MCMC-based history matching of CO2   storage operations  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403007308
:TOPICS: Advanced Techniques in Reservoir Management, Pore-scale Imaging and Enhanced Oil Recovery, Carbon Dioxide Sequestration in Geological Formations
:PUBLICATION_DATE: 2024-08-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2408.10717")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403007308"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403007308"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403007308"))][Get cited by]]

OpenAlex: https://openalex.org/W4403007308 (Open access: True)
    
[[https://openalex.org/A5055381891][Yifu Han]], [[https://openalex.org/A5047662931][François P. Hamon]], [[https://openalex.org/A5002057296][Louis J. Durlofsky]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2408.10717  ([[http://arxiv.org/pdf/2408.10717][pdf]])
     
Deep learning surrogate modeling shows great promise for subsurface flow applications, but the training demands can be substantial. Here we introduce a new surrogate modeling framework to predict CO2 saturation, pressure and surface displacement for use in the history matching of carbon storage operations. Rather than train using a large number of expensive coupled flow-geomechanics simulation runs, training here involves a large number of inexpensive flow-only simulations combined with a much smaller number of coupled runs. The flow-only runs use an effective rock compressibility, which is shown to provide accurate predictions for saturation and pressure for our system. A recurrent residual U-Net architecture is applied for the saturation and pressure surrogate models, while a new residual U-Net model is introduced to predict surface displacement. The surface displacement surrogate accepts, as inputs, geomodel quantities along with saturation and pressure surrogate predictions. Median relative error for a diverse test set is less than 4% for all variables. The surrogate models are incorporated into a hierarchical Markov chain Monte Carlo history matching workflow. Surrogate error is included using a new treatment involving the full model error covariance matrix. A high degree of prior uncertainty, with geomodels characterized by uncertain geological scenario parameters (metaparameters) and associated realizations, is considered. History matching results for a synthetic true model are generated using in-situ monitoring-well data only, surface displacement data only, and both data types. The enhanced uncertainty reduction achieved with both data types is quantified. Posterior saturation and surface displacement fields are shown to correspond well with the true solution.    

    

* A Short Report on the Effectiveness of Edge Taper Platinum and XP-3D Shaper for the Reduction of Enterococcus faecalis Count in the Root Canal System: An Ex Vivo Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402874996
:TOPICS: Endodontic Research and Practice, Cone-Beam Computed Tomography in Dentistry, Prevalence of Musculoskeletal Disorders in Dentistry
:PUBLICATION_DATE: 2024-06-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.34172/ajdr.1811")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402874996"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402874996"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402874996"))][Get cited by]]

OpenAlex: https://openalex.org/W4402874996 (Open access: True)
    
[[https://openalex.org/A5107551438][Hanie Moaveni]], [[https://openalex.org/A5095888038][Parastou Ghahari]], [[https://openalex.org/A5057596189][Samira Behrad]], [[https://openalex.org/A5022921016][Majid Mirmohammadkhani]], [[https://openalex.org/A5107620997][Sobhan Rashmee]], [[https://openalex.org/A5092682811][Somayeh Teimoori]], Avicenna journal of dental research. 16(2)] 2024. https://doi.org/10.34172/ajdr.1811 
     
Background: Intracanal microorganisms are the main cause of radicular lesions and, therefore, should be removed from the root canal system. Enterococcus faecalis is a resistant bacterium isolated from 30%–90% of endodontically-treated teeth, commonly chosen for in vitro studies on endodontic treatment methods. Different methods have been suggested for removing this bacterium from the root canal system, while none have been approved as the gold standard method. This study aimed to compare the effectiveness of Edge Taper Platinum and XP-endo® shaper rotary files in reducing the number of E. faecalis in the root canal system. Methods: In this ex vivo study, 58 single-rooted single-canal teeth were immersed in formalin for 1 hour, stored in 0.9% saline, and randomly divided into positive control (n=4), negative control (n=4), platinum (n=25), and shaper (n=25). E. faecalis was injected into the root canals of all groups, except for the negative control group. The teeth were then incubated in a CO2 incubator for 24 hours. Primary samples were collected, and the root canals were instrumented using the XP-endo® shaper and Edge Taper Platinum. Secondary samples were collected and cultured, and the number of colonies was counted after 24 hours of incubation. The data were analyzed using the Kruskal-Wallis and Mann-Whitney tests at a P<0.05. Results: A significant difference was observed for the reduction of the E. faecalis colony count in 87.79%, 97.83%, and 14.11% of the XP-endo® shaper (87.79%), Edge Taper Platinum (97.83%), and positive control (14.11%) groups (P<0.05). Conclusion: Both XP-endo® shaper and Edge Taper Platinum files with equal apical sizes effectively reduced the number of E. faecalis colonies in the root canal system. Edge Taper Platinum with a greater taper was more effective.    

    

* Sex-Based Differences in Pulmonary Function and Cardiopulmonary Response 30 Months Post-COVID-19: A Brazilian Multicentric Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402922794
:TOPICS: Neurological Manifestations of COVID-19 Infection, Standardisation and Management of COPD, Mechanical Ventilation in Respiratory Failure and ARDS
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ijerph21101293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402922794"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402922794"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402922794"))][Get cited by]]

OpenAlex: https://openalex.org/W4402922794 (Open access: True)
    
[[https://openalex.org/A5039532567][Cássia da Luz Goulart]], [[https://openalex.org/A5069879811][Guilherme Peixoto Tinoco Arêas]], [[https://openalex.org/A5024411477][Maurício Milani]], [[https://openalex.org/A5102635301][Fernanda Facioli dos Reis Borges]], [[https://openalex.org/A5076761841][Juliana Ribeiro Magalhães]], [[https://openalex.org/A5054551749][Guilherme Dionir Back]], [[https://openalex.org/A5049345749][Audrey Borghi‐Silva]], [[https://openalex.org/A5081034199][Luciano Fonseca Lemos de Oliveira]], [[https://openalex.org/A5075126774][André Paula]], [[https://openalex.org/A5085354071][Carolina Coimbra Marinho]], [[https://openalex.org/A5084896439][Déborah Pereira Prado]], [[https://openalex.org/A5073523967][Celso Nascimento de Almeida]], [[https://openalex.org/A5040274413][Cristiane Maria Carvalho Costa Dias]], [[https://openalex.org/A5043883445][Viní­cius Afonso Gomes]], [[https://openalex.org/A5039460964][Luiz Eduardo Fonteles Ritt]], [[https://openalex.org/A5030339093][Leandro Tolfo Franzoni]], [[https://openalex.org/A5033199964][Ricardo Stein]], [[https://openalex.org/A5010257239][Mansueto Gomes Neto]], [[https://openalex.org/A5013672770][Gerson Cipriano]], [[https://openalex.org/A5077065332][Fernando Val]], International Journal of Environmental Research and Public Health. 21(10)] 2024. https://doi.org/10.3390/ijerph21101293 
     
Aim: (I) to verify if there are sex differences in respiratory function, respiratory muscle strength, and effort limitation in individuals recovered from severe acute COVID-19 30 months after the initial infection, and (II) to evaluate the influence of length of stay on cardiorespiratory capacity among men and women. Methods: Cross-sectional observational multicentric study with participants from five Brazilian states (São Paulo, Amazonas, Minas Gerais, Bahia, and Brasília). We assessed lung function and respiratory muscle strength by maximum inspiratory pressure (MIP), maximum expiratory pressure (MEP), and cardiorespiratory fitness by cardiopulmonary exercise test (CPET). Results: 86 individuals were stratified by sex (48 women and 38 men). Females had significantly longer hospitalization for acute COVID-19 (p < 0.05) and showed a marked reduction in MIP (cmH2O and % predicted). Regarding the CPET, women presented lower V˙O2% predicted, O2 pulse, and oxygen uptake efficiency slope (OUES, % predicted) (p < 0.05). In addition, women also had greater abnormal combinations between RER < 1.10, OUES < 80% predicted, VE/VVM < 15% [3 (6.2%)] and V˙O2% predicted < 80%, V˙E/V˙CO2 slope and V˙O2/workload < 8.4 mL/min/W [8 (17%)]. The regression analysis showed a significant influence of age, length of hospitalization (< and >10 days), and FEV1/FVC (%) on the V˙O2 peak (mL·kg−1·min−1). Secondarily, we found that women hospitalized for more than 10 days had worse O2 pulse (p = 0.03), OUES % predicted (p < 0.001), and worse V˙O2% predicted (p < 0.009). Conclusion: Women exhibited more pronounced impairments in several key indicators of cardiopulmonary function 30 months post-infection.    

    

* INTEGRAÇÃO DE ÍNDICES ESPECTRAIS NA ESTIMATIVA DE BIOMASSA E CARBONO EM FLORESTAS DE Eucalyptus Grandis: UM ESTUDO DE CASO COM NDVI E CO2FLUX  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402923578
:TOPICS: Estimation of Forest Biomass and Carbon Stocks, Utilization of Forest Biomass for Various Applications
:PUBLICATION_DATE: 2024-09-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5016/geociencias.v43i3.18171")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402923578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402923578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402923578"))][Get cited by]]

OpenAlex: https://openalex.org/W4402923578 (Open access: False)
    
[[https://openalex.org/A5046556745][Sidnei Fonseca Guerreiro]], [[https://openalex.org/A5019441487][Rosane Maria Kaspary]], [[https://openalex.org/A5007065062][Flávia Luize Pereira de Souza]], [[https://openalex.org/A5086539847][Martha Santana Martins]], [[https://openalex.org/A5070658612][V. Campos]], [[https://openalex.org/A5046556745][Sidnei Fonseca Guerreiro]], Geociências. 43(3)] 2024. https://doi.org/10.5016/geociencias.v43i3.18171 
     
RESUMO - As florestas plantadas são alternativas para redução dos gases de efeito estufa, pelo acúmulo de biomassa em sua estrutura no ciclo do carbono e pelo serviço ambiental prestado no sequestro do gás, que necessita ser estimado por meio de tecnologias que possam medir sua eficiência e estoque. Este trabalho tem o propósito de estimar os valores de dois índices espectrais (NDVI e CO2Flux), com dados de biomassa em floresta plantada da espécie Eucalyptus grandis. Adotou-se três cenas do satélite Landsat-8 da órbita/ponto 221/076 com resolução espacial de 30 metros. Os pontos amostrais foram obtidos através do Inventário Florestal ocorridos em dezembro de 2016, em uma área total de 2050 ha, contabilizando 119.498 indivíduos arbóreos em seis fazendas instaladas entre os municípios de Borebi e Iaras no estado de São Paulo, pertencentes a empresa Lwarcel Celulose. Os resultados apresentaram os valores de escala alto dos índices NDVI e CO2Flux, para o NDVI valores próximos a 1 indicam vegetação densa e saudável, como os talhões de reflorestamento objeto de estudo, já os valores altos de CO2Flux indica que a vegetação está absorvendo mais CO2 do que está liberando, o que é positivo para o sequestro de carbono. O estudo demonstra a viabilidade de adoção dos índices para análises completa dos dados, agregando e integrando o modelo de inventário florestal difundido pelo IPCC com os de sensoriamento remoto para avaliação dinâmica do setor florestal. Palavras-chave: NDVI. CO2Flux. Sensoriamento Remoto. Eucalipto. ABSTRACT - Planted forests offer alternatives for reducing greenhouse gases by accumulating biomass in their structure in the carbon cycle and providing the environmental service of carbon sequestration. This reduction needs to be estimated using technologies that can measure the efficiency of these forests and the carbon stock they contain. The purpose of this study was to estimate the values of two spectral indices (NDVI and CO2Flux), using biomass data from a planted forest of Eucalyptus grandis. Three Landsat-8 satellite images taken at orbit/point 221/076 with a spatial resolution of 30 meters were used. The sample points were obtained from a forest inventory conducted in December 2016, covering a total area of 2050 ha, which contained 119,498 trees on six farms located between the municipalities of Borebi and Iaras in the state of São Paulo, belonging to the company Lwarcel Celulose. The results showed high NDVI and CO2Flux indices. NDVI values close to 1 indicate dense, healthy vegetation, such as the reforestation area under study, while high CO2Flux values indicate that the vegetation is absorbing more CO2 than it is releasing, which is positive for carbon sequestration. The study demonstrates the feasibility of adopting the indices for complete data analysis, aggregating and integrating the forest inventory model disseminated by the IPCC with remote sensing for a dynamic assessment of the forestry sector. Keywords: NDVI. CO2Flux. Remote Sensing. Eucalyptus.    

    

* Comments: Global Implications and Challenges of Electrification  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402970937
:TOPICS: Indoor Air Pollution in Developing Countries
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2118/1024-0014-jpt")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402970937"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402970937"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402970937"))][Get cited by]]

OpenAlex: https://openalex.org/W4402970937 (Open access: False)
    
[[https://openalex.org/A5069367188][Pam Boschee]], Journal of Petroleum Technology. 76(10)] 2024. https://doi.org/10.2118/1024-0014-jpt 
     
_ Electrification is widely seen as crucial for decarbonization. To be successful on a global scale, a mix of complex challenges require coordinated efforts across the diversification of the energy mix, technology development, infrastructure investment, policy support, and regional planning. The International Energy Agency’s (IEA) Net Zero Emissions by 2050 Scenario suggests electricity should account for nearly 30% of final energy consumption by 2030, up from an estimated 20% in 2023, to progress to net zero. Are net zero emissions achievable by 2050? SPE President Olivier Houzé delves into the IEA’s three main energy transition scenarios in this month’s vodcast and column. Among his conclusions: “Beyond 2050, the anticipation is a decline of around 50% for oil and 25% for gas in the following 20 years. The one thing everybody agrees on is that no one really knows.” The following updates offer a glimpse at efforts to electrify oil and gas assets and bring clean energy solutions to remote and underserved communities. Norway’s Offshore Success Electrifying upstream oil and gas production facilities using renewable energy or otherwise flared natural gas could reduce emissions by more than 80%. Rystad Energy’s recent analysis highlighted Norway as currently leading the way, thanks to its wealth of renewable resources and production sites’ proximity to them. Electrification of rigs and other assets on Norway’s Continental Shelf (NCS) has resulted in a drop from 8.4 kg to 1.2 kg CO2/BOE—an 86% reduction in the same assets’ emissions before electrification. Norway’s literal powerhouse is hydroelectric energy, tallying more than 1,500 hydropower plants, normally producing 133 TWh annually, or 96% of the country’s total power production. This supply has made the transition of many of its offshore facilities to cleaner energy more feasible than in other regions of the world, particularly for power-from-shore projects such as Troll A, Martin Linge, and Johan Sverdrup. As of 2 years ago, Norway had seven fields fully or partially electrified from shore. Onshore Electrification—Drilling With Clean(er) Energy Other players in the industry grapple with less advantageous scenarios, facing hurdles such as facilities located far from renewable energy sources, which may be limited, and inadequate grid infrastructure. SPE 218649, presented at the SPE Conference at Oman Petroleum & Energy Show in April, discussed using electrical utility power in drilling operations. The authors noted that a drilling rig typically consumes 6 to 50 MWh of energy per day, averaging around 20 MWh. Diesel-powered rigs emit about 1.0 metric tonne of CO2e/MWh, totaling roughly 20 metric tonnes of CO2e per day. In contrast, grid-powered rigs emit about 0.39 metric tonnes of CO2e/MWh, less than half the emissions of diesel-powered rigs. An example from the paper illustrates how incremental changes can reduce emissions intensity, even when the solution is a step toward “cleaner” energy, though not yet fully aligned with ideal clean energy standards. Comparing drilling operations in North Dakota, where 57% of the state’s power generation uses coal, to Texas where 18% uses coal, the authors noted that the “emissions intensity on a North Dakota rig tied to the grid is higher than that of an electrified rig working in Texas but is still notably lower than the intensity of an average drilling rig powered by a diesel generator, which is approximately 1.0 metric tonnes CO2e/MWh.” Broader Implications and Challenges of Electrification The upfront costs of electrification are substantial, especially for entities in remote areas with limited grid access. This challenge affects not only the oil and gas industry but also efforts to bring electricity to underserved communities. A paper presented at the SPE Nigeria Annual International Conference and Exhibition in August (SPE 221709) studied the viability and impact of solar mini-grid systems for electrification of rural communities in Sub-Saharan Africa where approximately 600 million people lack electricity, and around 690 million lack access to clean cooking stoves. The authors wrote, “In Nigeria, about 45% of the population, more than 90 million people, do not have electricity, with 60% of these individuals residing in rural areas. Nigeria also has one of the lowest per capita electricity generation rates globally, with an installed grid-connected capacity of about 13,000 MW but an average actual output of just 4,000 MW.” The authors included a table showing a cost summary including capital, the cost of installation, and other specifications for an 87.5-kWp (kilowatt peak) solar-power system. They calculated a levelized cost of electricity of 47.1 cents/kWh over the system’s estimated lifetime of 25 years—approximately six times that of a US residential solar system and roughly three times more than an average US residential utility rate of 16 cents/kWh (although this varies significantly by state and region). In the end, achieving a more electrified and sustainable energy future depends on a combination of factors: strategic investment, robust infrastructure, accessible energy resources, collaboration among key stakeholders, ongoing technological innovation, and supportive policy frameworks.    

    
