#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Mon Sep 23 01:19:51 2024

Found 11 results from 2024-09-16 to 2024-09-23
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Theoretical Design of the Electrocatalytic Urea Synthesis from Carbon Dioxide and Nitric Oxides  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402591482
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03785")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402591482"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402591482"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402591482"))][Get cited by]]

OpenAlex: https://openalex.org/W4402591482 (Open access: False)
    
[[https://openalex.org/A5030617408][Jun Long]], [[https://openalex.org/A5027648567][Dong Luan]], [[https://openalex.org/A5102669510][Xiaoyan Fu]], [[https://openalex.org/A5100319216][Huan Li]], [[https://openalex.org/A5004947752][Jianping Xiao]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03785 
     
No abstract    

    

* Increasing electrochemical carbon dioxide reduction to methane via a novel copper-based conductive metal organic framework  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402550001
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.09.124")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402550001"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402550001"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402550001"))][Get cited by]]

OpenAlex: https://openalex.org/W4402550001 (Open access: False)
    
[[https://openalex.org/A5045160070][Zhongyu Jing]], [[https://openalex.org/A5104273139][Wenli Su]], [[https://openalex.org/A5100744610][Yu Fan]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.09.124 
     
No abstract    

    

* Simplification of clean development mechanism to measure CO2 emission reductions from shifting private transportation to mass rapid transit: a case study of MRT Jakarta Phase 1  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402579361
:TOPICS: Estimating Vehicle Fuel Consumption and Emissions, Understanding Attitudes Towards Public Transport and Private Car, Rebound Effect on Energy Efficiency and Consumption
:PUBLICATION_DATE: 2024-09-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.12688/f1000research.155406.1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402579361"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402579361"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402579361"))][Get cited by]]

OpenAlex: https://openalex.org/W4402579361 (Open access: True)
    
[[https://openalex.org/A5080448160][Nunuj Nurdjanah]], [[https://openalex.org/A5029020060][Tri Edhi Budhi Soesilo]], [[https://openalex.org/A5018784186][K. Mizuno]], [[https://openalex.org/A5065712094][Raldi Hendro Koestoer]], F1000Research. 13(None)] 2024. https://doi.org/10.12688/f1000research.155406.1 
     
Background The Indonesian government built the Mass Rapid Transit (MRT) in Jakarta to reduce traffic congestion and carbon dioxide (CO2) emissions. The objective of this study is to estimate the CO2 emissions reductions from switching from private transport to MRT by using a methodology proposed by the United Nations Convention on Climate Change (UNFCCC) for developing countries, namely the Clean Development Mechanism (CDM) methodology, which generates Certified Emission Reductions (CERs). This methodology is more comprehensive than other available methodologies. However, this method has not been widely used to calculate greenhouse gas (GHG) emission reductions in mass transit projects because it is complex enough to require a lot of data based on primary surveys. Therefore, this research simplifies the CDM formula to make it easier and applicable in Indonesia. Methods The primary data were collected using a questionnaire distributed to 480 MRT Jakarta Phase 1 user respondents in September 2019 (baseline); the secondary data were obtained from The MRT Jakarta. The data were processed using IBM SPSS Statistics 27. The simplified Clean Development Mechanism Approved Consolidated Methodology 0016 (CDM ACM 0016) was the analysis method used. Result The results of this study indicate that 53.75% of MRT Jakarta Phase 1 users are shifting from private transportation, which has reduced CO2 emissions by 2,732.7 tons in 2019 and 6,043.9 tons in 2023. Increasing the number of MRT passengers who switch from private transportation will further reduce CO2 emissions. Conclusion and implications The simplified CDM ACM 0016 formula may be suitable for use in Indonesia. This would enable the measurement of CO2 emission reductions through mitigation actions through MRT development to be certified by the UNFCCC. Applying this method in calculating CO2 emission reductions, implementing strategies to increase MRT passengers, and using renewable energy electricity sources would increase CO2 emission reductions.    

    

* Sn-modified Cu nanosheets catalyze CO2 reduction to C2H4 efficiently by stabilizing CO intermediates and promoting C C coupling  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402550081
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.09.117")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402550081"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402550081"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402550081"))][Get cited by]]

OpenAlex: https://openalex.org/W4402550081 (Open access: False)
    
[[https://openalex.org/A5079077156][Hongfei Wang]], [[https://openalex.org/A5077887658][Fusen Zhang]], [[https://openalex.org/A5089939950][Yang Li]], [[https://openalex.org/A5054744038][Yingping Pang]], [[https://openalex.org/A5100594238][Xiqiang Zhao]], [[https://openalex.org/A5028614042][Zhanlong Song]], [[https://openalex.org/A5100344713][Wenlong Wang]], [[https://openalex.org/A5004056151][Jing Sun]], [[https://openalex.org/A5078703047][Yanpeng Mao]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.09.117 
     
No abstract    

    

* Boosting Ethylene Yield via Synergistic 2D/0D Nanostructured VCu Layered Double Hydroxide/TiO2 Catalyst in Electrochemical CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402578037
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ya00417e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402578037"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402578037"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402578037"))][Get cited by]]

OpenAlex: https://openalex.org/W4402578037 (Open access: True)
    
[[https://openalex.org/A5020344184][Sneha Lavate]], [[https://openalex.org/A5070013777][Rohit Srivastava]], Energy Advances. None(None)] 2024. https://doi.org/10.1039/d4ya00417e 
     
The electrochemical conversion of CO2 into C1 to C2 hydrocarbon such as Methane and ethylene is a promising pathway towards to achieve net zero however due to high activation barrier...    

    

* Electrosynthesis of Methylamine by Co-Reduction of Co2 and No3− with a Series Catalyst Based on O-Doped Metal Phthalocyanine-Porphyrin Two-Dimensional Carbon-Rich Conjugated Framework  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402583930
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4958584")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402583930"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402583930"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402583930"))][Get cited by]]

OpenAlex: https://openalex.org/W4402583930 (Open access: False)
    
[[https://openalex.org/A5100526482][Fengling Luo]], [[https://openalex.org/A5100322864][Li Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4958584 
     
No abstract    

    

* The importance of an informed choice of CO2-equivalence metrics for contrail avoidance  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402552629
:TOPICS: Aviation's Impact on Global Climate Change
:PUBLICATION_DATE: 2024-09-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/acp-24-9401-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402552629"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402552629"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402552629"))][Get cited by]]

OpenAlex: https://openalex.org/W4402552629 (Open access: True)
    
[[https://openalex.org/A5064864063][Audran Borella]], [[https://openalex.org/A5077051671][Oliviér Boucher]], [[https://openalex.org/A5042509503][Keith P. Shine]], [[https://openalex.org/A5022531801][Marc Stettler]], [[https://openalex.org/A5033739527][Katsumasa Tanaka]], [[https://openalex.org/A5019349634][Roger Teoh]], [[https://openalex.org/A5042660117][Nicolas Bellouin]], Atmospheric chemistry and physics. 24(16)] 2024. https://doi.org/10.5194/acp-24-9401-2024 
     
Abstract. One of the proposed ways to reduce the climate impact of civil aviation is rerouting aircraft to minimise the formation of warming contrails. As this strategy may increase fuel consumption, it would only be beneficial if the climate impact reduction from the avoided contrails exceeds the negative impact of any additional carbon dioxide (CO2) emitted by the rerouted flight. In this study, we calculate the surface temperature response of almost half a million flights that crossed the North Atlantic sector in 2019 and compare it to the temperature response of hypothetical rerouted flights. The climate impacts of contrails and CO2 are assessed through the perspective of CO2-equivalence metrics, represented here as nine combinations of different definitions and time horizons. We estimate that the total emitted CO2 and the persistent contrails formed will have warmed the climate by 17.2 µK in 2039, 13.7 µK in 2069, and 14.1 µK in 2119. Under an idealised scenario where 1 % additional carbon dioxide is enough to reroute all contrail-forming flights and avoid contrail formation completely, total warming would decrease by 4.9 (−28 %), 2.6 (−19 %), and 1.9 (−13 %) µK in 2039, 2069, and 2119, respectively. In most rerouting cases, the results based on the nine different CO2-equivalence metrics agree that rerouting leads to a climate benefit, assuming that contrails are avoided as predicted. But the size of that benefit is very dependent on the choice of CO2-equivalence metrics, contrail efficacy and CO2 penalty. Sources of uncertainty not considered here could also heavily influence the perceived benefit. In about 10 % of rerouting cases, the climate damage resulting from contrail avoidance indicated by CO2-equivalence metrics integrated over a 100-year time horizon is not predicted by metrics integrated over a 20-year time horizon. This study highlights, using North Atlantic flights as a case study, the implications of the choice of CO2-equivalence metrics for contrail avoidance, but the choice of metric implies a focus on a specific climate objective, which is ultimately a political decision.    

    

* Carbon dioxide sequestration in brackish water: Principles, techniques and environmental benefits  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402576747
:TOPICS: Carbon Dioxide Sequestration in Geological Formations, Hydrological Modeling and Water Resource Management
:PUBLICATION_DATE: 2024-04-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.61173/1njx1r03")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402576747"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402576747"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402576747"))][Get cited by]]

OpenAlex: https://openalex.org/W4402576747 (Open access: False)
    
[[https://openalex.org/A5107289125][Zuhong Gong]], Science and Technology of Engineering Chemistry and Environmental Protection. 1(6)] 2024. https://doi.org/10.61173/1njx1r03 
     
Carbon dioxide storage is a technology to separate carbon dioxide gas from the atmosphere and inject it into the brackish water layer to achieve the purpose of carbon dioxide emission reduction. In this way, carbon dioxide is dissolved in salt water and then sequestered in deep underground water layers, preventing it from being released into the atmosphere and causing a greenhouse effect. This technology can effectively reduce carbon dioxide emissions, but also can use geological structures for storage, has great potential application prospects. It is important to note that further research and practice is needed to address possible environmental risks and costs.    

    

* Reducing the carbon footprint for a 30-bed haemodialysis unit by changing the delivery of acid concentrate supplied by individual 5 L containers to a central delivery system  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402599258
:TOPICS: Impact of Climate Change on Human Health, Chronic Kidney Disease and Dialysis Treatment, Strategies to Reduce Low-Value Health Care Services
:PUBLICATION_DATE: 2024-09-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40620-024-02073-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402599258"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402599258"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402599258"))][Get cited by]]

OpenAlex: https://openalex.org/W4402599258 (Open access: True)
    
[[https://openalex.org/A5009899542][Gareth Murcutt]], [[https://openalex.org/A5092443799][Rosie Hillson]], [[https://openalex.org/A5040095014][Cate Goodlad]], [[https://openalex.org/A5088913338][Andrew Davenport]], Journal of Nephrology. None(None)] 2024. https://doi.org/10.1007/s40620-024-02073-9 
     
Abstract Background Haemodialysis treatments generate greenhouse gas (GHG) emissions mainly as a result of the equipment, consumables and pharmaceuticals required. An internal audit demonstrated a 33% wastage of acid concentrate when using individual 5.0 L containers at a 1:44 dilution ratio. We therefore investigated whether changing the delivery system for acid concentrate would reduce wastage and any associated greenhouse gas emissions. Methods We calculated the difference for a 30-bed dialysis unit between receiving acid concentrate in single-use 5.0 L plastic containers versus bulk delivery for a central acid delivery system connected to the dialysis machines. Estimates of carbon dioxide equivalent (CO 2 e) emissions were made using the United Kingdom government database and other sources. Results A 30-station dialysis unit functioning at maximum capacity (3 shifts and 6 days/week), switching to bulk delivery and central acid delivery could realise an approximate total reduction of 33,841 kgCO 2 e/year; in reduced product wastage, saving 6192 kgCO 2 e, 5205 kgCO 2 e from fewer deliveries, and 22,444 kgCO 2 e saving from a reduction in packaging and waste generated, which equates approximately to a one tonne reduction in CO 2 e emissions per dialysis station/year. Conclusions Switching from delivering acid concentrate in individual 5.0 L containers to a central acid delivery system can result in substantial reductions in CO 2 e emissions within a dialysis clinic. The emission savings from reducing the single-use plastic packaging greatly outweigh any gains from eliminating wastage of acid concentrate. Dialysis companies and clinicians should consider reviewing the design of current and future dialysis facilities and policies to determine whether reductions in CO 2 e emissions can be made. Graphical Abstract    

    

* Trends in CO, CO<sub>2</sub>, CH<sub>4</sub>, BC, and NO<sub>x </sub>during the first 2020 COVID-19 lockdown: source insights from the WMO/GAW station of Lamezia Terme (Calabria, Southern Italy)  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402559566
:TOPICS: Impact of COVID-19 on Global Environment, Health Effects of Air Pollution, Low-Cost Air Quality Monitoring Systems
:PUBLICATION_DATE: 2024-09-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.20944/preprints202409.0915.v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402559566"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402559566"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402559566"))][Get cited by]]

OpenAlex: https://openalex.org/W4402559566 (Open access: True)
    
[[https://openalex.org/A5101916131][Francesco D’Amico]], [[https://openalex.org/A5085477448][Ivano Ammoscato]], [[https://openalex.org/A5037863048][Daniel Gullì]], [[https://openalex.org/A5003696483][Elenio Avolio]], [[https://openalex.org/A5019248420][Teresa Lo Feudo]], [[https://openalex.org/A5079518186][Mariafrancesca De Pino]], [[https://openalex.org/A5013159030][Paolo Cristofanelli]], [[https://openalex.org/A5099128770][Luana Malacaria]], [[https://openalex.org/A5099128771][Domenico Parise]], [[https://openalex.org/A5102811601][Salvatore Sinopoli]], [[https://openalex.org/A5104971933][Giorgia De Benedetto]], [[https://openalex.org/A5002083226][Claudia Roberta Calidonna]], No host. None(None)] 2024. https://doi.org/10.20944/preprints202409.0915.v2 
     
In 2020, the Covid-19 outbreak led many countries across the globe to introduce lockdowns (LDs) that effectively caused most anthropic activities to either stop completely or be significantly reduced. In Europe, Italy played a pioneeristic role via the early introduction of a strict nationwide LD on March 9th. This study is aimed at evaluating, using both chemical and meteorological data, the environmental response to that occurrence as observed by the Lamezia Terme (LMT) GAW/WMO station in Calabria, Southern Italy. The first 2020 lockdown has therefore been used as a &ldquo;proving ground&rdquo; to assess CO, CO2, CH4, BC, and NOx concentrations in a rather unique context by exploiting the location of LMT in the context of the Mediterranean Basin. In fact, its location on the Tyrrhenian coast of Calabria and local wind circulation both lead to daily cycles where western-seaside winds depleted in anthropogenic pollutants can be easily differentiated from northeastern-continental winds, enriched in anthropogenic outputs. In addition to that, the first Italian LD occurred during the seasonal transition from Winter to Spring and, consequently, Summer, thus providing new insights on emission outputs correlated with seasons. Findings have clearly indicated BC and, in particular, CO as strongly correlated with average daily temperatures, and possibly domestic heating. CO2&rsquo;s reduction during the lockdown and consequent increase in the post-lockdown period, combined with wind data, has allowed to constrain local source of emissions located northeast from LMT. NOx reductions during specific circumstances are consistent with hypotheses from previous research which linked them to rush hour traffic and other forms of transportation emissions. CH4&rsquo;s stable patterns are consistent with livestock, landfills, and other sources assumed to be nearly constant during LD periods.    

    

* Investigation of Plug-In Hybrid Light Duty Commercial Vehicle in Real-World Conditions by Simulation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402588401
:TOPICS: State of the Art in Electric and Hybrid Vehicles, Estimating Vehicle Fuel Consumption and Emissions, Chemical Kinetics of Combustion Processes
:PUBLICATION_DATE: 2024-09-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.4271/2024-24-0016")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402588401"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402588401"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402588401"))][Get cited by]]

OpenAlex: https://openalex.org/W4402588401 (Open access: False)
    
[[https://openalex.org/A5073768559][Ezio Mancaruso]], [[https://openalex.org/A5083501499][Giovanni Meccariello]], [[https://openalex.org/A5022004944][Simona Rossetti]], SAE technical papers on CD-ROM/SAE technical paper series. 1(None)] 2024. https://doi.org/10.4271/2024-24-0016 
     
<div class="section abstract"><div class="htmlview paragraph">Light commercial vehicles are an indispensable element for the transport of people and the delivery of goods, especially on extra-urban and long-distance routes. With a view to sustainable mobility, it is necessary to think about hybridizing these vehicles to reduce the fuel consumption as well as greenhouse gas emissions and particulate matter. These types of vehicles are generally powered by diesel and travel many kilometers a day. On the other hand, the use of light commercial vehicles in battery electric vehicle (BEV) configuration has already been started but is not receiving widespread recognition. In this panorama, starting from a study already developed for the hybridization of a plug-in light commercial vehicle in Worldwide harmonized Light vehicles Test Cycle (WLTC) condition, the simulation analysis has been extended to the plug-in hybrid vehicle (PHEV) operating in real driving emission conditions (RDE). In particular, using Advisor software, a vehicle has been simulated in different plug-in hybrid configurations. The software has been validated with real operation data of a euro 6 diesel engine. The general hypothesis underlying the research consists in the possibility of using these vehicles in totally electric mode in the city and in hybrid mode outside urban centers; with the aim of reducing polluting emissions in populated city but completing the delivery mission during all phases of vehicle operation. The PHEV simulations have been performed on both WLTC and RDE condition. In the latter mode, particular attention has been devoted to the interpretation of data from GPS sensor: like the slope of the route or the presence of tunnels. The success of the simulation depends on a correct and careful reconstruction of the GPS data. Three vehicles with different hybridization factors have been simulated: 0.44, 0.56, and 0.67, respectively, with power equal to that of the base vehicle. The battery packs have been sized for the three hybrid vehicles and simulations were carried out in both Charge Depleting and Charge Sustaining configuration. In charge depleting for the highest hybrid configuration (HF=0.66), the results demonstrate that a reduction of up to 80% and 76% in fuel can be saved While a reduction up to 75% and 45% in NOx emissions can be achieved on WLTC and RDE cycle, respectively. On the other hand, when the battery is discharged, for HF=0.67, although consumption can be reduced by up to 45%, NOx emissions also increase by 183% even if ICE operation mode has to be better optimize for hybrid operation. Finally, even if the hybrid solutions is really convenient if compared to the conventional vehicle in terms of fuel savings and NOx pollutant emissions, about a realistic estimation of the CO2 reduction that can be achieved the use of electrical energy must be take into account.</div></div>    

    
