#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Sat Mar  9 00:42:05 2024

Found 26 results from 2024-03-02 to 2024-03-09
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Toward Rational Design of Nickel Catalysts in Thermocatalytic Decomposition of Methane for Carbon Dioxide‐Free Hydrogen and Value‐Added Carbon Co‐Product: A Review  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392241824
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301629")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392241824"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392241824"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392241824"))][Get cited by]]

OpenAlex: https://openalex.org/W4392241824 (Open access: True)
    
[[https://openalex.org/A5037271399][Robert S. Weber]], [[https://openalex.org/A5061717901][Mengze Xu]], [[https://openalex.org/A5012527581][Juan A. Lopez‐Ruiz]], [[https://openalex.org/A5048420505][Changle Jiang]], [[https://openalex.org/A5079109786][Jianli Hu]], [[https://openalex.org/A5078386311][Robert A. Dagle]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301629  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cctc.202301629][pdf]])
     
Thermocatalytic decomposition of methane provides opportunities for hydrogen (H2) production with no emission of carbon dioxide. However, high‐value carbon products need to be produced for economic deployment of thermocatalytic decomposition and to achieve a minimum H2 selling price below the U.S, Department of Energy target of $1/kg H2. In this review, we re‐evaluate data on catalyst development reported in the literature and propose fundamental correlations between catalyst characteristics, catalytic stability, and properties of carbon co‐products. In the first part of the review, growth mechanisms for carbon nanotubes using state‐of‐the‐art chemical vapor deposition are reviewed to catalog the effects of catalyst characteristics, the influence of carbon sources, interactions between metal particles and supports, and metal particle sizes on carbon growth. In the second part, representative developments in mono‐, bi‐, and tri‐metallic nickel catalysts are highlighted. We present kinetic analysis of reactions catalyzed by mono‐metallic nickel catalysts, which generates a correlation between metal particle size and catalyst stability.    

    

* Electrochemical Carbon Dioxide Reduction in Acidic Media  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392382931
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrochemical Reduction in Molten Salts
:PUBLICATION_DATE: 2024-03-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s41918-024-00210-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392382931"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392382931"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392382931"))][Get cited by]]

OpenAlex: https://openalex.org/W4392382931 (Open access: False)
    
[[https://openalex.org/A5072835490][Zhe Yao]], [[https://openalex.org/A5018931977][Xiaokang He]], [[https://openalex.org/A5072662311][Rui Lin]], Electrochemical Energy Reviews. 7(1)] 2024. https://doi.org/10.1007/s41918-024-00210-3 
     
No abstract    

    

* Highly efficient and selective electrosynthesis of urea via co-reduction of carbon dioxide and nitrate over the TiN catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392474079
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150178")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392474079"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392474079"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392474079"))][Get cited by]]

OpenAlex: https://openalex.org/W4392474079 (Open access: False)
    
[[https://openalex.org/A5030164210][Hongjun Fang]], [[https://openalex.org/A5084967150][Z. Wang]], [[https://openalex.org/A5032785684][Chil-Chyuan Kuo]], [[https://openalex.org/A5031905652][Hainan Yang]], [[https://openalex.org/A5032477554][Xinzhen Feng]], [[https://openalex.org/A5046093473][Weijie Ji]], [[https://openalex.org/A5000720153][Chak Tong Au]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150178 
     
Green and sustainable electrosynthesis of urea at ambient conditions through co-reduction of CO2 and NO3− (CR-CO2/NO3−) is regarded as a new avenue for nitrogen fertilizer production, however, the lack of novel electrocatalysts capable of selective C-N coupling hinders its wide application. Herein we reported a TiNx catalyst (TiN/TiN0.3) prepared by facile electric explosion method for electrocatalytic urea synthesis via CR-CO2/NO3−. The derived catalyst with porous nanostructure and specific active phase (TiN0.3) is more conductive for efficient C-N coupling. Consequently, a faradaic efficiency (FE) of 43.1 ± 3.1 % and a urea formation rate as high as 1488 ± 95 μg h−1 mgcat−1 were reached over the TiNx electrode, outperforming most of the reported CR-CO2/NO3− systems toward urea synthesis. In-situ attenuated total reflection Fourier transformed infrared spectroscopy and isotope-labeling experiments demonstrated the details about electrochemical coupling processes. The simulation study suggested that the TiN0.3 (1 0 0) facet facilitates the electroreduction of CO2 and NO3−, and decreases the energy barrier for generation of the key intermediates (*CO/*NH2), thus leading to the selective formation of urea. This work accomplished highly efficient electrochemical CR-CO2/NO3− toward nitrogen fertilizer production over a novel TiNx electrocatalyst for the target process.    

    

* Enhancing electrochemical carbon dioxide reduction efficiency through heat-induced metamorphosis of copper nanowires into copper oxide/copper nanotubes with tunable surface  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392505152
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392505152"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392505152"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392505152"))][Get cited by]]

OpenAlex: https://openalex.org/W4392505152 (Open access: False)
    
[[https://openalex.org/A5021339296][Harshad A. Bandal]], [[https://openalex.org/A5058562100][Hern Kim]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.007 
     
No abstract    

    

* Porous structure based on Fenton reaction-assisted chemical etching of commercial silicon powder and its application for electrocatalytic reduction of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392505956
:TOPICS: Gas Sensing Technology and Materials, Nanowire Nanosensors for Biomedical and Energy Applications, Porous Silicon Nanoparticles and Nanostructures
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1742-6596/2713/1/012054")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392505956"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392505956"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392505956"))][Get cited by]]

OpenAlex: https://openalex.org/W4392505956 (Open access: True)
    
[[https://openalex.org/A5083553660][Junpeng Li]], [[https://openalex.org/A5013555971][Zi Wang]], Journal of Physics: Conference Series. 2713(1)] 2024. https://doi.org/10.1088/1742-6596/2713/1/012054  ([[https://iopscience.iop.org/article/10.1088/1742-6596/2713/1/012054/pdf][pdf]])
     
Abstract Silicon-based porous nanocomposites are considered promising as electrode materials for the photoelectrochemical reduction of carbon dioxide. However, the high cost of raw materials and tedious processing for building nanostructures may not be conducive to large-scale industrial applications in terms of cost. Herein, we would like to introduce a porous structure prepared by Fenton reaction-assisted chemical etching of low-cost commercial silicon powder in the mixed solution of hydrogen fluoride and hydrogen peroxide. These porous particles are further decorated with silver nanoparticles to explore their feasibility for photoelectrochemical reduction of carbon dioxide. As shown by experimental results, this silicon-based nanocomposite is capable of catalyzing the conversion of carbon dioxide into carbon monoxide. The low cost of commercial silicon powder (~$3000/ton) compared with that of silicon wafers also renders this method potential and feasible for large-scale production of silicon-based porous materials.    

    

* A review of constraints and adjustable parameters in microgrids for cost and carbon dioxide emission reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392520445
:TOPICS: Control and Synchronization in Microgrid Systems, Demand Response in Smart Grids, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.heliyon.2024.e27489")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392520445"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392520445"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392520445"))][Get cited by]]

OpenAlex: https://openalex.org/W4392520445 (Open access: True)
    
[[https://openalex.org/A5087918072][Mohammed Amine Hoummadi]], [[https://openalex.org/A5068153880][Hala Alami Aroussi]], [[https://openalex.org/A5066405683][Badre Bossoufi]], [[https://openalex.org/A5091731246][Mohammed Karim]], [[https://openalex.org/A5068858971][Saleh Mobayen]], [[https://openalex.org/A5026194474][Anton Zhilenkov]], [[https://openalex.org/A5024972038][Thamer A. H. Alghamdi]], Heliyon. None(None)] 2024. https://doi.org/10.1016/j.heliyon.2024.e27489 
     
No abstract    

    

* Review article: Application of integrated electrodes materials for enhancing the electrochemical reduction of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392566863
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0194297")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392566863"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392566863"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392566863"))][Get cited by]]

OpenAlex: https://openalex.org/W4392566863 (Open access: True)
    
[[https://openalex.org/A5081971453][Hary Devianto]], [[https://openalex.org/A5089003468][M. Eviani]], [[https://openalex.org/A5073805388][Tirto Prakoso]], AIP Conference Proceedings. None(None)] 2024. https://doi.org/10.1063/5.0194297  ([[https://pubs.aip.org/aip/acp/article-pdf/doi/10.1063/5.0194297/19714812/020003_1_5.0194297.pdf][pdf]])
     
Carbon dioxide, a "greenhouse gas" resulted from industrial fossil fuels combustion, is a major driver of global warming and climate change. Several works have been pursued to reduce atmospheric concentrations of CO2. The most attractive and feasible approach to address this issue and maintain sustainable energy development for generations is carbon capture and storage or sequestration (CCS) via electrochemical reduction. Electrochemical CO2 reduction (ECO2R) is an integrated step of CO2 capture and electrochemical CO2 conversion, using water and electricity to convert CO2 into fuels and valuable chemicals, especially formic acid. Multiple benefits of CO2 Electrochemical conversion include the ability to regulate reaction rates or selectivity finely through the applied voltage, modularity of electrolytic cells that allows extensive scalability, and effective integration with intermittent renewable energy sources. The efficiency of ECO2R processes can be improved through (i) electrode structure and modification, (ii) electrolytic cell (reactor), (iii) electrolyte selection and pH control, and (iv) operating conditions (pressure and temperature). However, finding suitable electrodes with high selectivity for formic acid formation remains the biggest challenge at the fundamental level. This article provides an overview of recent research on ECO2R electrodes, focusing on the application of different types of integrated electrodes (e.g., metals, metal oxides, alloys) and the effect of adding promoters or/and carbon supports. The synergistic effect of different materials, promoters, and carbon supports in the electrodes is essential for the enhancement of the ECO2R performance.    

    

* Review electrochemical reduction of carbon dioxide into formic acid in various reactors using carbon-based catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392567040
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0194299")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392567040"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392567040"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392567040"))][Get cited by]]

OpenAlex: https://openalex.org/W4392567040 (Open access: True)
    
[[https://openalex.org/A5085371064][Nanda Dwi Jayanti]], [[https://openalex.org/A5081971453][Hary Devianto]], [[https://openalex.org/A5085589412][Pramujo Widiatmoko]], [[https://openalex.org/A5073805388][Tirto Prakoso]], [[https://openalex.org/A5089003468][M. Eviani]], AIP Conference Proceedings. None(None)] 2024. https://doi.org/10.1063/5.0194299  ([[https://pubs.aip.org/aip/acp/article-pdf/doi/10.1063/5.0194299/19714892/100001_1_5.0194299.pdf][pdf]])
     
Climate change as an effect of global warming is an environmental problem that is currently a concern of many parties. The global warming is mainly triggered by emission of CO2 into the atmosphere due to human activities such as usage of fossil fuels as the energy source. Therefore, the energy transition from fossil fuels to renewable energy as well as technology to capture and utilize the CO2 are highly necessary. The electrochemical conversion of CO2 to produce various products, such as formic acid has advantages, due to mild reaction condition, the process is controllable, use minimal chemicals, and the application is relatively easy to scale-up. Formic acid has potential as a source of hydrogen carrier and can replace fossil-based fuels. Products from electroreduction of CO2 depend on electrons transferred during the reaction, which are generated by the configuration of electrode/electrocatalyst, applied potential, and electrolyte. In addition, the type of reactor system or electrolytic cell also plays an important role in the electrochemical reduction of CO2. Carbon-based materials have potential as electrocatalysts for electroreduction of CO2 because of the porous structure, acid-base resistance, stability at high temperature, abundant availability in nature, and environmentally friendly. This mini review will discuss the electroreduction of CO2 in various electrochemical reactor systems using carbon-based electrocatalyst to produce formic acid using the SWOT analysis method.    

    

* Photochemical catalysis of carbon dioxide reduction by iron porphyrins  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392379416
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Catalytic Nanomaterials
:PUBLICATION_DATE: 2014-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392379416"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392379416"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392379416"))][Get cited by]]

OpenAlex: https://openalex.org/W4392379416 (Open access: True)
    
[[https://openalex.org/A5079483662][Mathilde Routier]], No host. None(None)] 2014. None  ([[https://theses.hal.science/tel-01788373/document][pdf]])
     
No abstract    

    

* Research the synergistic carbon reduction effects of sulfur dioxide emissions trading policy  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392247070
:TOPICS: Economic Implications of Climate Change Policies, Life Cycle Assessment and Environmental Impact Analysis, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jclepro.2024.141483")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392247070"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392247070"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392247070"))][Get cited by]]

OpenAlex: https://openalex.org/W4392247070 (Open access: False)
    
[[https://openalex.org/A5029324257][Yang Li]], [[https://openalex.org/A5049907537][Yanan Yang]], [[https://openalex.org/A5054997347][Yiming Zhou]], [[https://openalex.org/A5043482154][Xiaoying Shi]], Journal of Cleaner Production. None(None)] 2024. https://doi.org/10.1016/j.jclepro.2024.141483 
     
Since General Secretary Xi Jinping pledged the “30·60” targets to the world, the importance of pollution reduction and carbon reduction has become increasingly prominent. The previous focus on the pollution reduction effects of emission trading systems, while overlooking their carbon reduction impacts, as well as the limitations of research methods and scope, is no longer suitable for the needs of the new era. Therefore, this paper constructs a CGE model to study the synergistic effects, simulating the synergistic emission reduction effects of sulfur dioxide emission trading policies, and comes to the following conclusions: After the implementation of the sulfur dioxide emission trading mechanism, under different sulfur price scenarios, the synergistic reduction amounts of SO2 and CO2 vary greatly. As the sulfur price increases, the reduction amount becomes larger. In the five sulfur price scenarios set in this paper, the maximum reduction of SO2 can reach about 111,400 tons, and the maximum for CO2 is about 399 million tons. The CO2 reduction rate is approximately 1.0767 times that of SO2. This indicates that the sulfur dioxide emission trading policy is a very effective path for synergistic pollution and carbon reduction, with good reduction effects. In addition, sulfur dioxide emission trading will reduce the consumption of fossil energy, decrease industry output, raise product prices, cause GDP loss, and lead to reduced social welfare to varying degrees.    

    

* Development and Experimental Validation of 3D Computational Fluid Dynamic Model for Carbon Dioxide Reduction Electrolytic Cell  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392502438
:TOPICS: Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2023-10-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/acfpe59335.2023.10455453")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392502438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392502438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392502438"))][Get cited by]]

OpenAlex: https://openalex.org/W4392502438 (Open access: False)
    
[[https://openalex.org/A5066933015][Shuyu Zhu]], [[https://openalex.org/A5089236346][Fengxiang Ma]], [[https://openalex.org/A5051072210][Yunfeng Zhao]], [[https://openalex.org/A5081057106][Jian Cao]], [[https://openalex.org/A5036648385][Yu‐Mei Song]], [[https://openalex.org/A5002419717][Taotao Zhou]], [[https://openalex.org/A5057281614][Xianwen Zhang]], No host. None(None)] 2023. https://doi.org/10.1109/acfpe59335.2023.10455453 
     
No abstract    

    

* Electrolyte engineering for electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392440138
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2021-06-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392440138"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392440138"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392440138"))][Get cited by]]

OpenAlex: https://openalex.org/W4392440138 (Open access: False)
    
[[https://openalex.org/A5078971651][Carlos M. Sánchez‐Sánchez]], No host. None(None)] 2021. None 
     
No abstract    

    

* Carbon dioxide reduction in solid oxide electrolyzer cells utilizing nickel bimetallic alloys infiltrated into Gd0.1Ce0.9O1.95 (GDC10) scaffolds  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392499157
:TOPICS: Solid Oxide Fuel Cells, Electrochemical Reduction in Molten Salts, Chemical-Looping Technologies
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144052")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392499157"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392499157"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392499157"))][Get cited by]]

OpenAlex: https://openalex.org/W4392499157 (Open access: True)
    
[[https://openalex.org/A5066802079][Ahmad Abu Hajer]], [[https://openalex.org/A5090265262][Damilola A. Daramola]], [[https://openalex.org/A5045202746][Jason Trembly]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144052 
     
This study evaluates the electrochemical performance of Gd0.1Ce0.9O1.95 (GDC10) cathodes infiltrated with bimetallic Ni-Co and Ni-Cu alloy electrocatalysts for CO2 electroreduction in solid oxide electrolyzer cells (SOECs). The electrochemical reduction performance of SOECs with cathodes infiltrated with Ni-Co and Ni-Cu alloys were compared to the performance of SOECs having cathodes infiltrated with Ni, Co, and Cu. Electrochemical performance was evaluated at 750, 800, and 850°C. Cells with Co, Ni0.50Co0.50, Ni0.75Co0.25, and Ni infiltrated cathodes displayed a relatively similar CO2 electroreduction performance; however, SOECs having Co infiltrated cathodes had a slightly better catalytic performance towards CO2 reduction as demonstrated by their lower polarization resistance (Rp) values of 8.54, 4.03, and 1.25 Ω·cm2 when measured under open circuit voltage (OCV) at 750, 800, and 850°C, respectively. Cells having Co, Ni0.50Co0.50, Ni0.75Co0.25, and Ni infiltrated cathodes showed a stable long-term CO2 electroreduction performance with Faradaic efficiency values approaching 100% when tested under 0.20 A·cm−2 for 48 hours and at 750°C. Results indicate that SOECs with Ni infiltrated cathodes possessed better short- and long-term CO2 electroreduction performance compared to SOECs featuring cathodes infiltrated with Cu, Ni0.25Cu0.75, and Ni0.50Cu0.50. Increasing Ni percentage within the Ni-Cu alloy structure had a positive impact on the electrochemical performance as cells with Ni0.50Cu0.50 infiltrated cathodes showed relatively close voltage values to those of cells with Ni infiltrated cathodes during short-term galvanostatic tests. Although the SOEC with Ni0.50Cu0.50 infiltrated cathode experienced performance degradation throughout the long-term test period, it demonstrated better electroreduction performance having Faradaic efficiency values approaching 100% compared to cells with Cu and Ni0.25Cu0.75 infiltrated cathodes when evaluated under 0.20 A·cm−2 for 48 hours and at 750°C.    

    

* Correction: Zeolitic imidazolate framework-derived composites with SnO2 and ZnO phase components for electrocatalytic carbon dioxide reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392306599
:TOPICS: Gas Sensing Technology and Materials, Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dt90031f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392306599"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392306599"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392306599"))][Get cited by]]

OpenAlex: https://openalex.org/W4392306599 (Open access: True)
    
[[https://openalex.org/A5065697584][Yayu Guan]], [[https://openalex.org/A5027750805][Yuyu Liu]], [[https://openalex.org/A5014513107][Jin Yi]], [[https://openalex.org/A5029969051][Jiujun Zhang]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d4dt90031f  ([[https://pubs.rsc.org/en/content/articlepdf/2024/dt/d4dt90031f][pdf]])
     
Correction for ‘Zeolitic imidazolate framework-derived composites with SnO 2 and ZnO phase components for electrocatalytic carbon dioxide reduction’ by Yayu Guan et al. , Dalton Trans. , 2022, 51 , 7274–7283, https://doi.org/10.1039/d2dt00906d.    

    

* Environment & Mobility 2050: scenarios for a 75% reduction in CO2 emissions.  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392444369
:TOPICS: Economic Implications of Climate Change Policies, Estimating Vehicle Fuel Consumption and Emissions
:PUBLICATION_DATE: 2009-10-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392444369"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392444369"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392444369"))][Get cited by]]

OpenAlex: https://openalex.org/W4392444369 (Open access: True)
    
[[https://openalex.org/A5045375149][Hector G. Lopez-Ruiz]], No host. None(None)] 2009. None  ([[https://theses.hal.science/tel-00523839/document][pdf]])
     
No abstract    

    

* Hierarchical porous monoliths as supports for the enzymatic reduction of CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392292698
:TOPICS: Enzyme Immobilization Techniques, Electrochemical Reduction of CO2 to Fuels, Droplet Microfluidics Technology
:PUBLICATION_DATE: 2018-10-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392292698"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392292698"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392292698"))][Get cited by]]

OpenAlex: https://openalex.org/W4392292698 (Open access: True)
    
[[https://openalex.org/A5065045233][Mohamed Baccour]], No host. None(None)] 2018. None  ([[https://theses.hal.science/tel-03664635/document][pdf]])
     
No abstract    

    

* Engineered 2D materials for CO2 reduction reaction (CO2 RR)  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392233842
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/978-0-7503-5719-7ch6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392233842"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392233842"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392233842"))][Get cited by]]

OpenAlex: https://openalex.org/W4392233842 (Open access: False)
    
[[https://openalex.org/A5036580436][Abhinandan Patra]], [[https://openalex.org/A5060818209][Chandra Sekhar Rout]], IOP Publishing eBooks. None(None)] 2024. https://doi.org/10.1088/978-0-7503-5719-7ch6 
     
No abstract    

    

* Molybdenum diimine tetracarbonyl complexes for the Electrocatalytic reduction of CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392286505
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2021-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392286505"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392286505"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392286505"))][Get cited by]]

OpenAlex: https://openalex.org/W4392286505 (Open access: True)
    
[[https://openalex.org/A5022762152][Carlos Garcia Bellido]], No host. None(None)] 2021. None  ([[https://theses.hal.science/tel-04021490/document][pdf]])
     
No abstract    

    

* Advancements in electrochemical CO2 reduction reaction: A review on CO2 mass transport enhancement strategies  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392380153
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150169")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392380153"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392380153"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392380153"))][Get cited by]]

OpenAlex: https://openalex.org/W4392380153 (Open access: False)
    
[[https://openalex.org/A5056575431][Zhenhong Yuan]], [[https://openalex.org/A5081217856][Ke Wang]], [[https://openalex.org/A5091191484][Zheng Shi]], [[https://openalex.org/A5026970256][Xiuwen Cheng]], [[https://openalex.org/A5028828408][Yi He]], [[https://openalex.org/A5030329860][Qin Wei]], [[https://openalex.org/A5091009061][Xing Hong Zhang]], [[https://openalex.org/A5068124521][Haixing Chang]], [[https://openalex.org/A5016292565][Nianbing Zhong]], [[https://openalex.org/A5047526167][Xuefeng He]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150169 
     
The imperative to address climate change and CO2 emissions has elicited substantial interest in the field of electrochemical CO2 reduction reaction (eCO2RR) as an avenue to both environmental sustainability and the production of value-added fuels. However, the selectivity and efficiency of eCO2RR remain below the industrial requirement for its implementation at high current density. One pivotal strategy to ameliorate this deficiency involves augmenting the mass transport of CO2 to electrode, thereby alleviating the competing hydrogen evolution reaction and consequently enhancing eCO2RR performance. Herein, we primarily discuss the CO2 mass transport enhancement strategies through electrode and electrolyzer designs, as well as electrolysis conditions. The electrode designs are first presented, including wettability regulation, porous substrates construction, catalyst layer and gas diffusion layer designs. Then, we highlight state-of-the-art electrolyzer designs, including the bipolar membrane structure, interdigitated flow field and in-situ exsolution of CO2 structure. The electrolyzer based gas–liquid Taylor flow is also introduced. Following this, we delve into the impact of various electrolysis conditions, encompassing the electrolyte, electrolysis potentials, CO2 pressure, CO2 flow rate and reaction temperature. Finally, we conclude this review by delineating persisting challenges and potential solutions aimed at advancing CO2 mass transport for the industrial implementation of eCO2RR technology.    

    

* New trends in the development of CO2 electrochemical reduction electrolyzer  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392349915
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jece.2024.112369")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392349915"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392349915"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392349915"))][Get cited by]]

OpenAlex: https://openalex.org/W4392349915 (Open access: False)
    
[[https://openalex.org/A5073568638][Xu Zhang]], [[https://openalex.org/A5076206900][Huixia Lu]], [[https://openalex.org/A5000505470][Yu Miao]], [[https://openalex.org/A5050840588][Yusheng Zhang]], [[https://openalex.org/A5024134455][Jianyou Wang]], Journal of Environmental Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.jece.2024.112369 
     
Climate change due to increasing CO2 emissions has become one of the greatest challenges facing humanity. In order to lessen CO2 emissions and the negative effects of global warming, CO2 utilization and conversion technologies have received more attention in recent years. Among the various carbon utilization and conversion technologies, an innovative technology approach for producing high-value-added products using intermittent renewable energy is CO2 electrochemical reduction (CO2ECR). However, more cost-effective, reliable, and scalable electrolyzer designs, are still required for future commercial CO2ECR. In this review, we summarize current developments in CO2ECR electrolyzers and highlight how the CO2ECR process's efficiency can be enhanced by optimizing internal core components of electrolyzer, including catalyst, electrode, ion exchange membrane (IEM) and flow field design. The aim of this review is to raise awareness among researchers, professionals and policymakers of the potential benefits of using CO2ECR technology for carbon utilization.    

    

* Plasma-assisted synthesis of porous bismuth nanosheets for electrocatalytic CO2-to-formate reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392247480
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.02.023")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392247480"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392247480"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392247480"))][Get cited by]]

OpenAlex: https://openalex.org/W4392247480 (Open access: True)
    
[[https://openalex.org/A5006697392][Liangping Xiao]], [[https://openalex.org/A5007731421][Qizheng Zheng]], [[https://openalex.org/A5033181335][Rusen Zhou]], [[https://openalex.org/A5070605006][Sifan Liu]], [[https://openalex.org/A5012208849][Yifan Zhao]], [[https://openalex.org/A5065692631][Yadong Zhao]], [[https://openalex.org/A5038584289][Renwu Zhou]], [[https://openalex.org/A5013359536][Kostya Ken Ostrikov]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.02.023 
     
The electrochemical carbon dioxide reduction (eCO2RR) to formate, driven by clean energy, is a promising approach for producing renewable chemicals and high-value fuels. Despite its potential, further development faces challenges due to limitations in electrocatalytic activity and durability, especially for non-noble metal-based catalysts. Here, naturally abundant bismuth-based nanosheets that can effectively drive CO2-to-formate electrocatalytic reduction are prepared using the plasma-activated Bi2Se3 followed by a reduction process. Thus-obtained plasma-activated Bi nanosheets (P-BiNS) feature ultrathin structures and high surface areas. Such nanostructures ensure the P-BiNS with outstanding eCO2RR catalytic performance, highlighted by the current density of over 80 mA cm−2 and a formate Faradic efficiency of >90%. Furthermore, P-BiNS catalysts demonstrate excellent durability and stability without deactivation following over 50 h of operation. The selectivity for formate production is also studied by density functional theory (DFT) calculations, validating the importance and efficacy of the stabilization of intermediates (OCHO*) on the P-BiNS surfaces. This study provides a facile plasma-assisted approach for developing high-performance and low-cost electrocatalysts.    

    

* Graphene-based CO2 reduction electrocatalysts: a review  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392564119
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.carbon.2024.118879")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392564119"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392564119"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392564119"))][Get cited by]]

OpenAlex: https://openalex.org/W4392564119 (Open access: False)
    
[[https://openalex.org/A5038427980][Zelin Wu]], [[https://openalex.org/A5009018022][Congwei Wang]], [[https://openalex.org/A5052309941][Xiaoxiang Zhang]], [[https://openalex.org/A5029883974][Quangui Guo]], [[https://openalex.org/A5029316647][Junying Wang]], Carbon. 221(None)] 2024. https://doi.org/10.1016/j.carbon.2024.118879 
     
No abstract    

    

* Introduction of sulfur in Bi2O3 to boost water activation for enhancing the reduction of CO2 to formate  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392528082
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.234298")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392528082"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392528082"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392528082"))][Get cited by]]

OpenAlex: https://openalex.org/W4392528082 (Open access: False)
    
[[https://openalex.org/A5064070730][Qiuyu Zheng]], [[https://openalex.org/A5050079096][Sheng Luan]], [[https://openalex.org/A5047447008][Yun Feng]], [[https://openalex.org/A5038564297][Shi‐Wen Lv]], [[https://openalex.org/A5044544424][Yi Zhang]], [[https://openalex.org/A5047700095][Yanqing Cong]], Journal of Power Sources. 601(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.234298 
     
The reduction of carbon dioxide to produce valuable chemicals offers a sustainable approach towards achieving carbon neutralization. However, the electrochemical carbon dioxide reduction (ECO2RR) using clean electricity faces challenges in terms of high product faradaic efficiency (FE), current density, and stability. In this study, we prepared a S–Bi2O3 nanosheets (NS) catalyst through in-situ structural reconstruction. The S–Bi2O3 NS catalyst exhibited a peak formate FE of 92.05 % at −0.9 V and a high formate formation rate of 497.80 μmol h−1 cm−2 at −1.3 V. The significant improvement in selectivity and activity is attributed to the sulfur modification on Bi2O3 NS catalyst. The sulfur doping enhances the dissociation of water into H* species, facilitating the formation of HCOO* intermediate and promoting formate production. This work presents a simple and effective strategy for developing highly selective Bi-based electrocatalysts for efficient formate production.    

    

* Mechanism of surface oxygen-containing species promoted electrocatalytic CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392455306
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.scib.2024.03.012")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392455306"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392455306"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392455306"))][Get cited by]]

OpenAlex: https://openalex.org/W4392455306 (Open access: False)
    
[[https://openalex.org/A5029332865][Zhanzhao Fu]], [[https://openalex.org/A5054235490][Yixin Ouyang]], [[https://openalex.org/A5019757765][Mingliang Wu]], [[https://openalex.org/A5007388482][Chongyi Ling]], [[https://openalex.org/A5020585562][Jinlan Wang]], Science Bulletin. None(None)] 2024. https://doi.org/10.1016/j.scib.2024.03.012 
     
Oxygen-containing species have been demonstrated to play a key role in facilitating electrocatalytic CO2 reduction (CO2RR), particularly in enhancing the selectivity towards multi-carbon (C2+) products. However, the underlying promotion mechanism is still under debate, which greatly limits the rational optimization of the catalytic performance of CO2RR. Herein, taking CO2 and O2 co-electrolysis over Cu as the prototype, we successfully clarified how O2 boosts CO2RR from a new perspective by employing comprehensive theoretical simulations. Our results demonstrated that O2 in feed gas can be rapidly reduced into *OH, leading to the partial oxidation of Cu surface under reduction conditions. Surface *OH accelerates the formation of quasi-specifically adsorbed K+ due to the electrostatic interaction between *OH and K+ ions, which significantly increases the concentration of K+ near the Cu surface. These quasi-specifically adsorbed K+ ions can not only lower the C–C coupling barriers but also promote the hydrogenation of CO2 to improve the CO yield rate, which are responsible for the remarkably enhanced efficiency of C2+ products. During the whole process, O2 co-electrolysis plays an indispensable role in stabilizing surface *OH. This mechanism can be also adopted to understand the effect of high pH of electrolyte and residual O in oxide-derived Cu (OD-Cu) on the catalytic efficiency towards C2+ products. Therefore, our work provides new insights into strategies for improving C2+ products on the Cu-based catalysts, i.e., maintaining partial oxidation of surface under reduction conditions.    

    

* Electrodeposition of Cuxbi1-X-Mof for Electrochemical Reduction of Co2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392465749
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4747851")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392465749"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392465749"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392465749"))][Get cited by]]

OpenAlex: https://openalex.org/W4392465749 (Open access: False)
    
[[https://openalex.org/A5054852894][Xinlei Cheng]], [[https://openalex.org/A5082899866][Min Wu]], [[https://openalex.org/A5021488560][Yan Xu]], [[https://openalex.org/A5074811994][Shiying Wang]], [[https://openalex.org/A5062755510][Qianqian Wang]], [[https://openalex.org/A5034220138][Wenchang Wang]], [[https://openalex.org/A5014014810][Naotoshi Mitsuzaki]], [[https://openalex.org/A5089061216][Zhidong Chen]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4747851 
     
No abstract    

    

* Experimental Research on the Carbon Dioxides Reduction Potential by Substitution Gasoline with Ethanol and Propane Under Reactivity Controlled Compression Ignition in a Single Cylinder Engine  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392363017
:TOPICS: Chemical Kinetics of Combustion Processes, Estimating Vehicle Fuel Consumption and Emissions, Dynamics of Turbulent Combustion Systems
:PUBLICATION_DATE: 2024-03-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12239-024-00026-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392363017"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392363017"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392363017"))][Get cited by]]

OpenAlex: https://openalex.org/W4392363017 (Open access: True)
    
[[https://openalex.org/A5023940594][Jeongwoo Lee]], [[https://openalex.org/A5046271540][Sanghyun Chu]], [[https://openalex.org/A5074221485][Jieun Kang]], [[https://openalex.org/A5010685701][Kyoungdoug Min]], International Journal of Automotive Technology. None(None)] 2024. https://doi.org/10.1007/s12239-024-00026-6 
     
Abstract In this experiment, it was experimentally investigated the combustion and exhaust characteristics, as well as the thermal efficiency, of RCCI combustion using gasoline, ethanol, and propane as low-reactivity fuels under four operating conditions. For each operating condition, gISNO x was limited to 0.15 g/kWh, and gISSmoke was limited to below 15 mg/kWh. The experiment was conducted by determining the operating conditions that satisfied these limitations and resulted in the highest city thermal efficiency. The low-reactivity fuels were supplied by port injection, while diesel was directly injected into the combustion chamber using a diesel injector. As a result, when gasoline is replaced with low-carbon fuels like ethanol and propane, the reduction in CO 2 emissions occurred. Under maximum power conditions, using ethanol allowed for a maximum reduction in CO 2 emissions of 6.81%. Depending on the driving conditions, ethanol showed a reduction ranging from 3.60 to 6.81%, while propane exhibited a reduction ranging from 3.10 to 5.64%. Additionally, by substituting with ethanol and propane, the GIE could be improved up to 44.73 and 43.56%, respectively.    

    
