#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Thu Mar  7 00:35:40 2024

Found 26 results from 2024-02-29 to 2024-03-07
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Toward Rational Design of Nickel Catalysts in Thermocatalytic Decomposition of Methane for Carbon Dioxide‐Free Hydrogen and Value‐Added Carbon Co‐Product: A Review  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392241824
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301629")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392241824"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392241824"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392241824"))][Get cited by]]

OpenAlex: https://openalex.org/W4392241824 (Open access: True)
    
[[https://openalex.org/A5037271399][Robert S. Weber]], [[https://openalex.org/A5061717901][Mengze Xu]], [[https://openalex.org/A5012527581][Juan A. Lopez‐Ruiz]], [[https://openalex.org/A5048420505][Changle Jiang]], [[https://openalex.org/A5079109786][Jianli Hu]], [[https://openalex.org/A5078386311][Robert A. Dagle]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301629  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cctc.202301629][pdf]])
     
Thermocatalytic decomposition of methane provides opportunities for hydrogen (H2) production with no emission of carbon dioxide. However, high‐value carbon products need to be produced for economic deployment of thermocatalytic decomposition and to achieve a minimum H2 selling price below the U.S, Department of Energy target of $1/kg H2. In this review, we re‐evaluate data on catalyst development reported in the literature and propose fundamental correlations between catalyst characteristics, catalytic stability, and properties of carbon co‐products. In the first part of the review, growth mechanisms for carbon nanotubes using state‐of‐the‐art chemical vapor deposition are reviewed to catalog the effects of catalyst characteristics, the influence of carbon sources, interactions between metal particles and supports, and metal particle sizes on carbon growth. In the second part, representative developments in mono‐, bi‐, and tri‐metallic nickel catalysts are highlighted. We present kinetic analysis of reactions catalyzed by mono‐metallic nickel catalysts, which generates a correlation between metal particle size and catalyst stability.    

    

* Electrochemical Carbon Dioxide Reduction in Acidic Media  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392382931
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrochemical Reduction in Molten Salts
:PUBLICATION_DATE: 2024-03-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s41918-024-00210-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392382931"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392382931"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392382931"))][Get cited by]]

OpenAlex: https://openalex.org/W4392382931 (Open access: False)
    
[[https://openalex.org/A5072835490][Zhe Yao]], [[https://openalex.org/A5018931977][Xiaokang He]], [[https://openalex.org/A5072662311][Rui Lin]], Electrochemical Energy Reviews. 7(1)] 2024. https://doi.org/10.1007/s41918-024-00210-3 
     
No abstract    

    

* Highly efficient and selective electrosynthesis of urea via co-reduction of carbon dioxide and nitrate over the TiN catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392474079
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150178")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392474079"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392474079"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392474079"))][Get cited by]]

OpenAlex: https://openalex.org/W4392474079 (Open access: False)
    
[[https://openalex.org/A5030164210][Hongjun Fang]], [[https://openalex.org/A5084967150][Z. Wang]], [[https://openalex.org/A5032785684][Chil-Chyuan Kuo]], [[https://openalex.org/A5031905652][Hainan Yang]], [[https://openalex.org/A5032477554][Xinzhen Feng]], [[https://openalex.org/A5046093473][Weijie Ji]], [[https://openalex.org/A5000720153][Chak Tong Au]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150178 
     
Green and sustainable electrosynthesis of urea at ambient conditions through co-reduction of CO2 and NO3− (CR-CO2/NO3−) is regarded as a new avenue for nitrogen fertilizer production, however, the lack of novel electrocatalysts capable of selective C-N coupling hinders its wide application. Herein we reported a TiNx catalyst (TiN/TiN0.3) prepared by facile electric explosion method for electrocatalytic urea synthesis via CR-CO2/NO3−. The derived catalyst with porous nanostructure and specific active phase (TiN0.3) is more conductive for efficient C-N coupling. Consequently, a faradaic efficiency (FE) of 43.1 ± 3.1 % and a urea formation rate as high as 1488 ± 95 μg h−1 mgcat−1 were reached over the TiNx electrode, outperforming most of the reported CR-CO2/NO3− systems toward urea synthesis. In-situ attenuated total reflection Fourier transformed infrared spectroscopy and isotope-labeling experiments demonstrated the details about electrochemical coupling processes. The simulation study suggested that the TiN0.3 (1 0 0) facet facilitates the electroreduction of CO2 and NO3−, and decreases the energy barrier for generation of the key intermediates (*CO/*NH2), thus leading to the selective formation of urea. This work accomplished highly efficient electrochemical CR-CO2/NO3− toward nitrogen fertilizer production over a novel TiNx electrocatalyst for the target process.    

    

* Photochemical catalysis of carbon dioxide reduction by iron porphyrins  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392379416
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Catalytic Nanomaterials
:PUBLICATION_DATE: 2014-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392379416"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392379416"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392379416"))][Get cited by]]

OpenAlex: https://openalex.org/W4392379416 (Open access: True)
    
[[https://openalex.org/A5079483662][Mathilde Routier]], No host. None(None)] 2014. None  ([[https://theses.hal.science/tel-01788373/document][pdf]])
     
No abstract    

    

* Research the synergistic carbon reduction effects of sulfur dioxide emissions trading policy  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392247070
:TOPICS: Economic Implications of Climate Change Policies, Life Cycle Assessment and Environmental Impact Analysis, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jclepro.2024.141483")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392247070"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392247070"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392247070"))][Get cited by]]

OpenAlex: https://openalex.org/W4392247070 (Open access: False)
    
[[https://openalex.org/A5029324257][Yang Li]], [[https://openalex.org/A5049907537][Yanan Yang]], [[https://openalex.org/A5054997347][Yiming Zhou]], [[https://openalex.org/A5043482154][Xiaoying Shi]], Journal of Cleaner Production. None(None)] 2024. https://doi.org/10.1016/j.jclepro.2024.141483 
     
Since General Secretary Xi Jinping pledged the “30·60” targets to the world, the importance of pollution reduction and carbon reduction has become increasingly prominent. The previous focus on the pollution reduction effects of emission trading systems, while overlooking their carbon reduction impacts, as well as the limitations of research methods and scope, is no longer suitable for the needs of the new era. Therefore, this paper constructs a CGE model to study the synergistic effects, simulating the synergistic emission reduction effects of sulfur dioxide emission trading policies, and comes to the following conclusions: After the implementation of the sulfur dioxide emission trading mechanism, under different sulfur price scenarios, the synergistic reduction amounts of SO2 and CO2 vary greatly. As the sulfur price increases, the reduction amount becomes larger. In the five sulfur price scenarios set in this paper, the maximum reduction of SO2 can reach about 111,400 tons, and the maximum for CO2 is about 399 million tons. The CO2 reduction rate is approximately 1.0767 times that of SO2. This indicates that the sulfur dioxide emission trading policy is a very effective path for synergistic pollution and carbon reduction, with good reduction effects. In addition, sulfur dioxide emission trading will reduce the consumption of fossil energy, decrease industry output, raise product prices, cause GDP loss, and lead to reduced social welfare to varying degrees.    

    

* Electrolyte engineering for electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392440138
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2021-06-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392440138"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392440138"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392440138"))][Get cited by]]

OpenAlex: https://openalex.org/W4392440138 (Open access: False)
    
[[https://openalex.org/A5078971651][Carlos M. Sánchez‐Sánchez]], No host. None(None)] 2021. None 
     
No abstract    

    

* Correction: Zeolitic imidazolate framework-derived composites with SnO2 and ZnO phase components for electrocatalytic carbon dioxide reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392306599
:TOPICS: Gas Sensing Technology and Materials, Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dt90031f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392306599"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392306599"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392306599"))][Get cited by]]

OpenAlex: https://openalex.org/W4392306599 (Open access: True)
    
[[https://openalex.org/A5065697584][Yayu Guan]], [[https://openalex.org/A5027750805][Yuyu Liu]], [[https://openalex.org/A5014513107][Jin Yi]], [[https://openalex.org/A5029969051][Jiujun Zhang]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d4dt90031f  ([[https://pubs.rsc.org/en/content/articlepdf/2024/dt/d4dt90031f][pdf]])
     
Correction for ‘Zeolitic imidazolate framework-derived composites with SnO 2 and ZnO phase components for electrocatalytic carbon dioxide reduction’ by Yayu Guan et al. , Dalton Trans. , 2022, 51 , 7274–7283, https://doi.org/10.1039/d2dt00906d.    

    

* Environment & Mobility 2050: scenarios for a 75% reduction in CO2 emissions.  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392444369
:TOPICS: Economic Implications of Climate Change Policies, Estimating Vehicle Fuel Consumption and Emissions
:PUBLICATION_DATE: 2009-10-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392444369"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392444369"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392444369"))][Get cited by]]

OpenAlex: https://openalex.org/W4392444369 (Open access: True)
    
[[https://openalex.org/A5045375149][Hector G. Lopez-Ruiz]], No host. None(None)] 2009. None  ([[https://theses.hal.science/tel-00523839/document][pdf]])
     
No abstract    

    

* Hierarchical porous monoliths as supports for the enzymatic reduction of CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392292698
:TOPICS: Enzyme Immobilization Techniques, Electrochemical Reduction of CO2 to Fuels, Droplet Microfluidics Technology
:PUBLICATION_DATE: 2018-10-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392292698"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392292698"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392292698"))][Get cited by]]

OpenAlex: https://openalex.org/W4392292698 (Open access: True)
    
[[https://openalex.org/A5065045233][Mohamed Baccour]], No host. None(None)] 2018. None  ([[https://theses.hal.science/tel-03664635/document][pdf]])
     
No abstract    

    

* Engineered 2D materials for CO2 reduction reaction (CO2 RR)  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392233842
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/978-0-7503-5719-7ch6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392233842"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392233842"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392233842"))][Get cited by]]

OpenAlex: https://openalex.org/W4392233842 (Open access: False)
    
[[https://openalex.org/A5036580436][Abhinandan Patra]], [[https://openalex.org/A5060818209][Chandra Sekhar Rout]], IOP Publishing eBooks. None(None)] 2024. https://doi.org/10.1088/978-0-7503-5719-7ch6 
     
No abstract    

    

* Molybdenum diimine tetracarbonyl complexes for the Electrocatalytic reduction of CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392286505
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2021-06-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392286505"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392286505"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392286505"))][Get cited by]]

OpenAlex: https://openalex.org/W4392286505 (Open access: True)
    
[[https://openalex.org/A5022762152][Carlos Garcia Bellido]], No host. None(None)] 2021. None  ([[https://theses.hal.science/tel-04021490/document][pdf]])
     
No abstract    

    

* Advancements in electrochemical CO2 reduction reaction: A review on CO2 mass transport enhancement strategies  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392380153
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150169")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392380153"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392380153"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392380153"))][Get cited by]]

OpenAlex: https://openalex.org/W4392380153 (Open access: False)
    
[[https://openalex.org/A5056575431][Zhenhong Yuan]], [[https://openalex.org/A5081217856][Ke Wang]], [[https://openalex.org/A5091191484][Zheng Shi]], [[https://openalex.org/A5026970256][Xiuwen Cheng]], [[https://openalex.org/A5028828408][Yi He]], [[https://openalex.org/A5030329860][Qin Wei]], [[https://openalex.org/A5091009061][Xing Hong Zhang]], [[https://openalex.org/A5068124521][Haixing Chang]], [[https://openalex.org/A5016292565][Nianbing Zhong]], [[https://openalex.org/A5047526167][Xuefeng He]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150169 
     
The imperative to address climate change and CO2 emissions has elicited substantial interest in the field of electrochemical CO2 reduction reaction (eCO2RR) as an avenue to both environmental sustainability and the production of value-added fuels. However, the selectivity and efficiency of eCO2RR remain below the industrial requirement for its implementation at high current density. One pivotal strategy to ameliorate this deficiency involves augmenting the mass transport of CO2 to electrode, thereby alleviating the competing hydrogen evolution reaction and consequently enhancing eCO2RR performance. Herein, we primarily discuss the CO2 mass transport enhancement strategies through electrode and electrolyzer designs, as well as electrolysis conditions. The electrode designs are first presented, including wettability regulation, porous substrates construction, catalyst layer and gas diffusion layer designs. Then, we highlight state-of-the-art electrolyzer designs, including the bipolar membrane structure, interdigitated flow field and in-situ exsolution of CO2 structure. The electrolyzer based gas–liquid Taylor flow is also introduced. Following this, we delve into the impact of various electrolysis conditions, encompassing the electrolyte, electrolysis potentials, CO2 pressure, CO2 flow rate and reaction temperature. Finally, we conclude this review by delineating persisting challenges and potential solutions aimed at advancing CO2 mass transport for the industrial implementation of eCO2RR technology.    

    

* New trends in the development of CO2 electrochemical reduction electrolyzer  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392349915
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jece.2024.112369")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392349915"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392349915"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392349915"))][Get cited by]]

OpenAlex: https://openalex.org/W4392349915 (Open access: False)
    
[[https://openalex.org/A5073568638][Xu Zhang]], [[https://openalex.org/A5076206900][Huixia Lu]], [[https://openalex.org/A5000505470][Yu Miao]], [[https://openalex.org/A5050840588][Yusheng Zhang]], [[https://openalex.org/A5024134455][Jianyou Wang]], Journal of Environmental Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.jece.2024.112369 
     
Climate change due to increasing CO2 emissions has become one of the greatest challenges facing humanity. In order to lessen CO2 emissions and the negative effects of global warming, CO2 utilization and conversion technologies have received more attention in recent years. Among the various carbon utilization and conversion technologies, an innovative technology approach for producing high-value-added products using intermittent renewable energy is CO2 electrochemical reduction (CO2ECR). However, more cost-effective, reliable, and scalable electrolyzer designs, are still required for future commercial CO2ECR. In this review, we summarize current developments in CO2ECR electrolyzers and highlight how the CO2ECR process's efficiency can be enhanced by optimizing internal core components of electrolyzer, including catalyst, electrode, ion exchange membrane (IEM) and flow field design. The aim of this review is to raise awareness among researchers, professionals and policymakers of the potential benefits of using CO2ECR technology for carbon utilization.    

    

* Plasma-assisted synthesis of porous bismuth nanosheets for electrocatalytic CO2-to-formate reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392247480
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.02.023")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392247480"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392247480"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392247480"))][Get cited by]]

OpenAlex: https://openalex.org/W4392247480 (Open access: True)
    
[[https://openalex.org/A5006697392][Liangping Xiao]], [[https://openalex.org/A5007731421][Qizheng Zheng]], [[https://openalex.org/A5033181335][Rusen Zhou]], [[https://openalex.org/A5070605006][Sifan Liu]], [[https://openalex.org/A5012208849][Yifan Zhao]], [[https://openalex.org/A5065692631][Yadong Zhao]], [[https://openalex.org/A5038584289][Renwu Zhou]], [[https://openalex.org/A5013359536][Kostya Ken Ostrikov]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.02.023 
     
The electrochemical carbon dioxide reduction (eCO2RR) to formate, driven by clean energy, is a promising approach for producing renewable chemicals and high-value fuels. Despite its potential, further development faces challenges due to limitations in electrocatalytic activity and durability, especially for non-noble metal-based catalysts. Here, naturally abundant bismuth-based nanosheets that can effectively drive CO2-to-formate electrocatalytic reduction are prepared using the plasma-activated Bi2Se3 followed by a reduction process. Thus-obtained plasma-activated Bi nanosheets (P-BiNS) feature ultrathin structures and high surface areas. Such nanostructures ensure the P-BiNS with outstanding eCO2RR catalytic performance, highlighted by the current density of over 80 mA cm−2 and a formate Faradic efficiency of >90%. Furthermore, P-BiNS catalysts demonstrate excellent durability and stability without deactivation following over 50 h of operation. The selectivity for formate production is also studied by density functional theory (DFT) calculations, validating the importance and efficacy of the stabilization of intermediates (OCHO*) on the P-BiNS surfaces. This study provides a facile plasma-assisted approach for developing high-performance and low-cost electrocatalysts.    

    

* Mechanism of surface oxygen-containing species promoted electrocatalytic CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392455306
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.scib.2024.03.012")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392455306"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392455306"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392455306"))][Get cited by]]

OpenAlex: https://openalex.org/W4392455306 (Open access: False)
    
[[https://openalex.org/A5029332865][Zhanzhao Fu]], [[https://openalex.org/A5054235490][Yixin Ouyang]], [[https://openalex.org/A5019757765][Mingliang Wu]], [[https://openalex.org/A5007388482][Chongyi Ling]], [[https://openalex.org/A5020585562][Jinlan Wang]], Science Bulletin. None(None)] 2024. https://doi.org/10.1016/j.scib.2024.03.012 
     
Oxygen-containing species have been demonstrated to play a key role in facilitating electrocatalytic CO2 reduction (CO2RR), particularly in enhancing the selectivity towards multi-carbon (C2+) products. However, the underlying promotion mechanism is still under debate, which greatly limits the rational optimization of the catalytic performance of CO2RR. Herein, taking CO2 and O2 co-electrolysis over Cu as the prototype, we successfully clarified how O2 boosts CO2RR from a new perspective by employing comprehensive theoretical simulations. Our results demonstrated that O2 in feed gas can be rapidly reduced into *OH, leading to the partial oxidation of Cu surface under reduction conditions. Surface *OH accelerates the formation of quasi-specifically adsorbed K+ due to the electrostatic interaction between *OH and K+ ions, which significantly increases the concentration of K+ near the Cu surface. These quasi-specifically adsorbed K+ ions can not only lower the C–C coupling barriers but also promote the hydrogenation of CO2 to improve the CO yield rate, which are responsible for the remarkably enhanced efficiency of C2+ products. During the whole process, O2 co-electrolysis plays an indispensable role in stabilizing surface *OH. This mechanism can be also adopted to understand the effect of high pH of electrolyte and residual O in oxide-derived Cu (OD-Cu) on the catalytic efficiency towards C2+ products. Therefore, our work provides new insights into strategies for improving C2+ products on the Cu-based catalysts, i.e., maintaining partial oxidation of surface under reduction conditions.    

    

* Electrodeposition of Cuxbi1-X-Mof for Electrochemical Reduction of Co2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392465749
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4747851")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392465749"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392465749"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392465749"))][Get cited by]]

OpenAlex: https://openalex.org/W4392465749 (Open access: False)
    
[[https://openalex.org/A5054852894][Xinlei Cheng]], [[https://openalex.org/A5082899866][Min Wu]], [[https://openalex.org/A5021488560][Yan Xu]], [[https://openalex.org/A5074811994][Shiying Wang]], [[https://openalex.org/A5062755510][Qianqian Wang]], [[https://openalex.org/A5034220138][Wenchang Wang]], [[https://openalex.org/A5014014810][Naotoshi Mitsuzaki]], [[https://openalex.org/A5089061216][Zhidong Chen]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4747851 
     
No abstract    

    

* Experimental Research on the Carbon Dioxides Reduction Potential by Substitution Gasoline with Ethanol and Propane Under Reactivity Controlled Compression Ignition in a Single Cylinder Engine  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392363017
:TOPICS: Chemical Kinetics of Combustion Processes, Estimating Vehicle Fuel Consumption and Emissions, Dynamics of Turbulent Combustion Systems
:PUBLICATION_DATE: 2024-03-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12239-024-00026-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392363017"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392363017"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392363017"))][Get cited by]]

OpenAlex: https://openalex.org/W4392363017 (Open access: True)
    
[[https://openalex.org/A5023940594][Jeongwoo Lee]], [[https://openalex.org/A5046271540][Sanghyun Chu]], [[https://openalex.org/A5074221485][Jieun Kang]], [[https://openalex.org/A5010685701][Kyoungdoug Min]], International Journal of Automotive Technology. None(None)] 2024. https://doi.org/10.1007/s12239-024-00026-6 
     
Abstract In this experiment, it was experimentally investigated the combustion and exhaust characteristics, as well as the thermal efficiency, of RCCI combustion using gasoline, ethanol, and propane as low-reactivity fuels under four operating conditions. For each operating condition, gISNO x was limited to 0.15 g/kWh, and gISSmoke was limited to below 15 mg/kWh. The experiment was conducted by determining the operating conditions that satisfied these limitations and resulted in the highest city thermal efficiency. The low-reactivity fuels were supplied by port injection, while diesel was directly injected into the combustion chamber using a diesel injector. As a result, when gasoline is replaced with low-carbon fuels like ethanol and propane, the reduction in CO 2 emissions occurred. Under maximum power conditions, using ethanol allowed for a maximum reduction in CO 2 emissions of 6.81%. Depending on the driving conditions, ethanol showed a reduction ranging from 3.60 to 6.81%, while propane exhibited a reduction ranging from 3.10 to 5.64%. Additionally, by substituting with ethanol and propane, the GIE could be improved up to 44.73 and 43.56%, respectively.    

    

* Composite interface of g-C3N4 fragment loaded on Cu substrate for CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392404687
:TOPICS: Emergent Phenomena at Oxide Interfaces, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cp05818b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392404687"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392404687"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392404687"))][Get cited by]]

OpenAlex: https://openalex.org/W4392404687 (Open access: False)
    
[[https://openalex.org/A5072771171][Qihuang Gong]], [[https://openalex.org/A5090481284][Jianling Xiong]], [[https://openalex.org/A5091705213][Tiangang Zhou]], [[https://openalex.org/A5036026030][Bao Wang]], [[https://openalex.org/A5086086953][Xiuyun Zhang]], [[https://openalex.org/A5018055096][Guiwu Liu]], [[https://openalex.org/A5009584953][Guanjun Qiao]], [[https://openalex.org/A5058002676][Feng Ding]], Physical Chemistry Chemical Physics. None(None)] 2024. https://doi.org/10.1039/d3cp05818b 
     
Designing the electrocatalyst with high efficiency and product selectivity is always crucial for the electrocatalytic CO2 reduction reaction (CO2RR). Inspired by the great progress of the two-dimensional (2D) nanomaterials growing...    

    

* MOFs/COFs hybrids as next-generation materials for electrocatalytic CO2 reduction reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392303421
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150098")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392303421"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392303421"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392303421"))][Get cited by]]

OpenAlex: https://openalex.org/W4392303421 (Open access: False)
    
[[https://openalex.org/A5069271043][Nouraiz Mushtaq]], [[https://openalex.org/A5084782835][Abrar Ahmad]], [[https://openalex.org/A5040200566][Xusheng Wang]], [[https://openalex.org/A5049135577][Usman Khan]], [[https://openalex.org/A5086455686][Junkuo Gao]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150098 
     
The increasing scarcity of fossil fuels and the escalating environmental concerns have heightened the demand for clean and renewable energy resources. Addressing this imperative, the exploration of electrocatalytic materials for CO2 reduction reactions (CO2 RR) presents a tough challenge in achieving efficient energy conversion with high Faradic efficiency (FE). Metal–organic frameworks (MOFs) and covalent-organic frameworks (COFs) represent crystalline materials characterized by hierarchical porous morphology. The rapid advancements in MOFs and COFs hold promising potential for diversifying CO2 RR electrocatalysts. Particularly noteworthy is the growing interest in hybrid materials combining MOFs and COFs, which has sparked considerable attention and is rapidly evolving across various domains. This inclusive review comprehensively discusses the progress and achievements in the design, synthesis, and application of MOFs/COFs hybrid materials for electrocatalytic CO2 RR. It concludes with insights into the evolving trends in structural design, potential applications, and associated challenges facing MOFs/COFs hybrid materials.    

    

* Computational screening of silver-based single-atom alloys catalysts for CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392380728
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0192055")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392380728"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392380728"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392380728"))][Get cited by]]

OpenAlex: https://openalex.org/W4392380728 (Open access: False)
    
[[https://openalex.org/A5054097350][Marionir M. C. B. Neto]], [[https://openalex.org/A5013396298][Lucas G. Verga]], [[https://openalex.org/A5077065362][Juarez L. F. Da Silva]], [[https://openalex.org/A5061185825][Breno R. L. Galvão]], The Journal of Chemical Physics. 160(9)] 2024. https://doi.org/10.1063/5.0192055 
     
Electrocatalytically reducing CO2 into value-added products is a challenging but promising process. Catalysts have been proposed to reduce the potential necessary for the reaction to occur, among which single-atom alloys (SAAs) are particularly promising. Here, we employ density functional theory calculations and the computational electrode model to predict whether silver-based SAAs have the potential to be effective electrocatalysts to convert CO2 into C1 products. We take into account surface defects by using the Ag(211) surface as a model. We also verify whether the proposed materials are prone to OH poisoning or enhance the competing hydrogen evolution reaction. Our calculations predict that these materials show weak mixing between the host and the dopant, characterized by a sharp peak in the density of states near the Fermi energy, except when copper (also a coinage metal) is used as the dopant. This affects the adsorption energy of the different intermediate molecules, yielding different reaction profiles for each substrate. As non-doped silver, copper-doped SAA tends to spontaneously desorb carbon monoxide (CO) instead of proceeding with its reduction. Other elements of the fourth period (Fe, Co, and Ni) tend to bind to the CO molecule but do not favor more reduced products. These metals also tend to enhance the hydrogen evolution reaction. On the contrary, we show that the Ir and Rh dopants have significant potential as electrocatalysts, which favors the reduction of CO over its desorption while also suppressing the hydrogen evolution reaction at potentials lower than those required by copper. They have also been shown to not be prone to poisoning by OH radicals.    

    

* Surface reconstruction of Cu-based bimetallic catalysts for electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392350793
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cjsc.2024.100255")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392350793"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392350793"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392350793"))][Get cited by]]

OpenAlex: https://openalex.org/W4392350793 (Open access: False)
    
[[https://openalex.org/A5010719310][Yufei Jia]], [[https://openalex.org/A5005228021][Fēi Li]], [[https://openalex.org/A5012902307][Ke Fan]], Chinese Journal of Structural Chemistry. None(None)] 2024. https://doi.org/10.1016/j.cjsc.2024.100255 
     
No abstract    

    

* Bipolar Membrane Electrolyzer for CO2 Electro-Reduction to CO in Organic Electrolyte with NaClO Produced as Byproduct  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392370140
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144056")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392370140"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392370140"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392370140"))][Get cited by]]

OpenAlex: https://openalex.org/W4392370140 (Open access: False)
    
[[https://openalex.org/A5048438287][Feng-xia Shen]], [[https://openalex.org/A5029824329][Shuai Wu]], [[https://openalex.org/A5036258236][Pengchong Zhao]], [[https://openalex.org/A5090856797][Yunfei Li]], [[https://openalex.org/A5069546592][Shu Miao]], [[https://openalex.org/A5059385448][Jianxiong Liu]], [[https://openalex.org/A5040834817][David Ostheimer]], [[https://openalex.org/A5031126542][Thomas Hannappel]], [[https://openalex.org/A5039595875][Tian-You Chen]], [[https://openalex.org/A5089046028][Jiangtao Shi]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144056 
     
A novel electrolyzer has been proposed for CO2 reduction to CO, concurrently generating NaClO as a byproduct at the anode. The cell is divided into two compartments by a bipolar membrane, which plays a pivotal role in the dissociation of H2O into H+ and OH−. In the cathode compartment, CO2 is reduced to CO within a neutral organic solution. Simultaneously, in the anode compartment, Cl− undergoes oxidation to form ClO− within a basic aqueous solution. The electrolyzer remains stable during 10 hours of electrolysis, and the current density reaches 76.35 mA cm−2 at a potential of -2.4 V (vs SHE), with the Faradaic efficiency of CO formation stable at 93%. By increasing the product values, CO2 electro-reduction technology can be promoted to industrial applications.    

    

* Ionic liquids’s Co-catalytic Effect on Electrochemical CO2 Reduction Mediated by Model Molecular Catalysts  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392440137
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2021-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392440137"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392440137"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392440137"))][Get cited by]]

OpenAlex: https://openalex.org/W4392440137 (Open access: False)
    
[[https://openalex.org/A5044623874][Elli Vichou]], [[https://openalex.org/A5044181527][Yun Xu-Li]], [[https://openalex.org/A5024792637][María Gómez-Mingot]], [[https://openalex.org/A5062221634][Marc Fontecave]], [[https://openalex.org/A5078971651][Carlos M. Sánchez‐Sánchez]], No host. None(None)] 2021. None 
     
No abstract    

    

* CO2 photoelectrochemical reduction in room-temperature ionic liquids-based media evaluated by Scanning Electrochemical Microscopy  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392440773
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2019-12-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392440773"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392440773"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392440773"))][Get cited by]]

OpenAlex: https://openalex.org/W4392440773 (Open access: False)
    
[[https://openalex.org/A5021541475][Lin Zhang]], [[https://openalex.org/A5044805824][Vincent Vivier]], [[https://openalex.org/A5078971651][Carlos M. Sánchez‐Sánchez]], No host. None(None)] 2019. None 
     
No abstract    

    

* Biological bromate reduction coupled with in situ gas fermentation in H2/CO2-based membrane biofilm reactor  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392302175
:TOPICS: Occurrence and Health Effects of Drinking Water Disinfection By-Products, Toxicology and Environmental Impacts of Mercury Contamination, Nanoscale Zero-Valent Iron Applications and Remediation
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.watres.2024.121402")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392302175"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392302175"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392302175"))][Get cited by]]

OpenAlex: https://openalex.org/W4392302175 (Open access: False)
    
[[https://openalex.org/A5051888029][Zhiqiang Zuo]], [[https://openalex.org/A5020168562][Chenkai Niu]], [[https://openalex.org/A5020264368][Xinyu Zhao]], [[https://openalex.org/A5076416431][Chun-Yu Lai]], [[https://openalex.org/A5077966133][Min Zheng]], [[https://openalex.org/A5005999266][Jianhua Guo]], [[https://openalex.org/A5036070878][Shihu Hu]], [[https://openalex.org/A5028399423][Tao Liu]], Water Research. None(None)] 2024. https://doi.org/10.1016/j.watres.2024.121402 
     
Bromate, a carcinogenic contaminant generated in water disinfection, presents a pressing environmental concern. While biological bromate reduction is an effective remediation approach, its implementation often necessitates the addition of organics, incurring high operational costs. This study demonstrated the efficient biological bromate reduction using H2/CO2 mixture as the feedstock. A membrane biofilm reactor (MBfR) was used for the efficient delivery of gases. Long-term reactor operation showed a high-level bromate removal efficiency of above 95%, yielding harmless bromide as the final product. Corresponding to the short hydraulic retention time of 0.25 d, a high bromate removal rate of 4 mg Br/L/d was achieved. During the long-term operation, in situ production of volatile fatty acids (VFAs) by gas fermentation was observed, which can be regulated by controlling the gas flow. Three sets of in situ batch tests and two groups of ex situ batch tests jointly unravelled the mechanisms underpinning the efficient bromate removal, showing that the microbial bromate reduction was primarily driven by the VFAs produced from in situ gas fermentation. Microbial community analysis showed an increased abundance of Bacteroidota group from 4.0% to 18.5%, which is capable of performing syngas fermentation, and the presence of heterotrophic denitrifiers (e.g., Thauera and Brachymonas), which are known to perform bromate reduction. Together these results for the first time demonstrated the feasibility of using H2/CO2 mixture for bromate removal coupled with in situ VFAs production. The findings can facilitate the development of cost-effective strategies for groundwater and drinking water remediation.    

    

* Magnetic fields promote electrocatalytic CO2 reduction via subtle modulations of magnetic moments and molecular bonding  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392301873
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Thermoelectric Materials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.eehl.2024.02.003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392301873"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392301873"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392301873"))][Get cited by]]

OpenAlex: https://openalex.org/W4392301873 (Open access: True)
    
[[https://openalex.org/A5057892245][Shilin Wei]], [[https://openalex.org/A5036966304][Weiqi Liu]], [[https://openalex.org/A5026004253][Peiyao Bai]], [[https://openalex.org/A5085449230][Chuangchuang Yang]], [[https://openalex.org/A5089367951][Xiao Kong]], [[https://openalex.org/A5035565553][Lang Xu]], Eco-environment & health. None(None)] 2024. https://doi.org/10.1016/j.eehl.2024.02.003 
     
Introducing a magnetic-field gradient into an electrically driven chemical reaction is expected to give rise to intriguing research possibilities. In this work, we elaborate on the modes and mechanisms of electrocatalytic activity (from the perspective of alignment of magnetic moments) and selectivity (at the molecular level) for the CO2 reduction reaction in response to external magnetic fields. We establish a positive correlation between magnetic field strengths and apparent current densities. This correlation can be rationalized by the formation of longer-range ordering of magnetic moments and the resulting decrease in the scattering of conduction electrons and charge-transfer resistances as the field strength increases. Furthermore, aided by the magnetic-field-equipped operando infrared spectroscopy, we find that applied magnetic fields are capable of weakening the C–O bond strength of the key intermediate *COOH and elongating the C–O bond length, thereby increasing the faradaic efficiency for the electroreduction of CO2 to CO.    

    
