#+filetags: CO2RR
#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Sat Jan 20 14:10:59 2024

Found 56 results from 2024-01-13 to 2024-01-20
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Acarbon%20dioxide%20reduction]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aco2%20reduction]]

** Unbiased Photoelectrochemical Carbon Dioxide Reduction Shaping the Future of Solar Fuels   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.123707")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390650933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390650933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390650933"))][Get cited by]]

OpenAlex: https://openalex.org/W4390650933 (Open access: False)
    
[[https://openalex.org/A5066466833][Haijiao Lu]], [[https://openalex.org/A5042282225][Luyao Wang]], Applied Catalysis B: Environmental. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.123707 
     
As atmospheric carbon dioxide (CO2) levels surge due to human activities, addressing this global crisis is paramount. This article delves into the realm of photoelectrochemical (PEC) CO2 reduction, a promising solution that combines solar energy conversion and electrochemical processes to transform CO2 into clean energy fuels. The primary focus of this article lies in the cutting-edge unbiased PEC tandem configurations, specifically reviewing recent breakthroughs in coupling PEC CO2 reduction with the oxygen evolution reaction through water oxidation. By consolidating the latest insights and knowledge, this comprehensive review guides readers through the evolving landscape of advanced PEC technologies. Furthermore, it provides insights into prospective developments in this evolving field, shedding light on the paths toward sustainable energy solutions and climate mitigation.    

    

** A Sulfur‐Doped Copper Catalyst with Efficient Electrocatalytic Formate Generation during the Electrochemical Carbon Dioxide Reduction Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202313858")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390656131"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390656131"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390656131"))][Get cited by]]

OpenAlex: https://openalex.org/W4390656131 (Open access: False)
    
[[https://openalex.org/A5087349574][Yinuo Wang]], [[https://openalex.org/A5022951375][Hongming Xu]], [[https://openalex.org/A5042932900][Yu‐Shen Liu]], [[https://openalex.org/A5043436936][Juhee Jang]], [[https://openalex.org/A5089516306][Xiaoyi Qiu]], [[https://openalex.org/A5078369945][Ernest Pahuyo Delmo]], [[https://openalex.org/A5018366822][Qinglan Zhao]], [[https://openalex.org/A5018528154][Ping Gao]], [[https://openalex.org/A5069700804][Minhua Shao]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202313858 
     
Catalysts involving post‐transition metals have shown almost invincible performance on generating formate in electrochemical CO2 reduction reaction (CO2RR). Conversely, Cu without post‐transition metals have struggled to achieve comparable activity. In this study, a sulfur (S)‐doped‐copper (Cu)‐based catalyst is developed, exhibiting excellent performance in formate generation with a maximum Faradaic efficiency of 92% and a partial current density of 321 mA cm‐2. Ex‐situ structural elucidations reveal the presence of abundant grain boundaries and high retention of S‐S bonds from the covellite phase during CO2RR. Furthermore, thermodynamic calculations demonstrate that S‐S bonds can moderate the binding energies with various intermediates, further improving the activity of the formate pathway. This work is significant in modifying a low‐cost catalyst (Cu) with a non‐metallic substance (S) to achieve comparable performance to mainstream catalysts for formate generation in industrial grade.    

    

** A Sulfur‐Doped Copper Catalyst with Efficient Electrocatalytic Formate Generation during the Electrochemical Carbon Dioxide Reduction Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202313858")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390656198"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390656198"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390656198"))][Get cited by]]

OpenAlex: https://openalex.org/W4390656198 (Open access: False)
    
[[https://openalex.org/A5087349574][Yinuo Wang]], [[https://openalex.org/A5022951375][Hongming Xu]], [[https://openalex.org/A5042932900][Yu‐Shen Liu]], [[https://openalex.org/A5043436936][Juhee Jang]], [[https://openalex.org/A5089516306][Xiaoyi Qiu]], [[https://openalex.org/A5078369945][Ernest Pahuyo Delmo]], [[https://openalex.org/A5018366822][Qinglan Zhao]], [[https://openalex.org/A5056167840][Ping Gao]], [[https://openalex.org/A5069700804][Minhua Shao]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202313858 
     
Catalysts involving post‐transition metals have shown almost invincible performance on generating formate in electrochemical CO2 reduction reaction (CO2RR). Conversely, Cu without post‐transition metals have struggled to achieve comparable activity. In this study, a sulfur (S)‐doped‐copper (Cu)‐based catalyst is developed, exhibiting excellent performance in formate generation with a maximum Faradaic efficiency of 92% and a partial current density of 321 mA cm‐2. Ex‐situ structural elucidations reveal the presence of abundant grain boundaries and high retention of S‐S bonds from the covellite phase during CO2RR. Furthermore, thermodynamic calculations demonstrate that S‐S bonds can moderate the binding energies with various intermediates, further improving the activity of the formate pathway. This work is significant in modifying a low‐cost catalyst (Cu) with a non‐metallic substance (S) to achieve comparable performance to mainstream catalysts for formate generation in industrial grade.    

    

** Nanobubble-Based Carbon Dioxide Massive Dissolution Using Friction Tubes and Real-Time Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-3836511/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390673455"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390673455"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390673455"))][Get cited by]]

OpenAlex: https://openalex.org/W4390673455 (Open access: True)
    
[[https://openalex.org/A5031914965][Taekeun Yoo]], [[https://openalex.org/A5065903349][Y.H. Yoo]], [[https://openalex.org/A5067611739][Seon-Woo Byun]], [[https://openalex.org/A5013952223][A-Ram You]], [[https://openalex.org/A5061924691][Changhee Park]], [[https://openalex.org/A5091770039][Dae-Hyun Choi]], [[https://openalex.org/A5041867415][Woo-Seung Lee]], No host. None(None)] 2024. https://doi.org/10.21203/rs.3.rs-3836511/v1  ([[https://www.researchsquare.com/article/rs-3836511/latest.pdf][pdf]])
     
Abstract To prevent global warming, various technologies are being developed to suppress carbon dioxide emissions. Nanobubbles are useful in various industrial fields. Carbon dioxide capture technology was studied using the property of activating the reaction of nanobubbles. In this study, carbon dioxide capture was attempted using nanobubble generation tubes based on the friction principle. The world has paid attention to carbon capture, utilization, and storage (CCUS) to inhibit and reduce carbon dioxide emissions, which are known as the main cause of global warming. The problem is that the new process that utilizes carbon dioxide must consume less energy and resources than existing alternative processes. To address this problem, research was conducted on the possibility of dissolving carbon dioxide in large quantities at low power consumption using a nanobubble generation system and real-time chemical reactions in this study. In addition, a mass dissolution system was constructed, and real-time neutralization was verified through the reactions of nanobubble carbon dioxide with ammonia water (NH 4 OH) and calcium hydroxide (Ca(OH) 2 ) solution.    

    

** Carbonyl-Linked Cobalt Polyphthalocyanines as High-Selectivity Catalyst for Electrochemical CO2 Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cc05844a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390687040"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390687040"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390687040"))][Get cited by]]

OpenAlex: https://openalex.org/W4390687040 (Open access: False)
    
[[https://openalex.org/A5032418340][Hua Jiang]], [[https://openalex.org/A5068411634][Yajing Di]], [[https://openalex.org/A5033886161][Yunle Gu]], [[https://openalex.org/A5035727547][Yu Chen]], [[https://openalex.org/A5033783993][Meiling Dou]], [[https://openalex.org/A5085462947][Zhengping Zhang]], [[https://openalex.org/A5016670960][Feng Wang]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d3cc05844a 
     
One type of carbonyl-linked cobalt polyphthalocyanine (CL-CoPPc) is synthesised as catalysts for use in electrochemical carbon dioxide (CO2) reduction (ECR). Carbonyl linkages can decrease the intermolecular π-π stacking, and serve as intramolecular "gullies" to impede proton transfer and the hydrogen evolution reaction (HER). Therefore, the CL-CoPPc exhibits highly active and selective CO2 reduction to carbon monoxide (CO).    

    

** Atomic-Disorder-Induced Mass Transport and Charge Transfer Enhancement Effect Boost the Intrinsic Activity of the Electrocatalyst Towards Electrochemical Co2 Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4689859")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390696686"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390696686"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390696686"))][Get cited by]]

OpenAlex: https://openalex.org/W4390696686 (Open access: False)
    
[[https://openalex.org/A5044283271][Xiquan Fu]], [[https://openalex.org/A5049562781][Ziyu Ma]], [[https://openalex.org/A5006328735][L.L. Liu]], [[https://openalex.org/A5027906141][Sajjad Hussain]], [[https://openalex.org/A5067813768][Dongwei Ma]], [[https://openalex.org/A5080944639][Shilong Jiao]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4689859 
     
Electrochemical conversion of carbon dioxide into formic acid has been demonstratedas an efficient approach for closing the carbon cycle. Here, we boost the intrinsicactivity of the Bi-based electrocatalyst through the synergy of enhanced chargetransfer and mass transport process in the electrochemical reactions by generating anatomic disorder in the crystal lattices. The amorphous Bi-based quantum dots (a-BiQDs) serve as promising electrocatalysts toward formate production in a widepotential range with high Faradaic efficiency (FE) and energy efficiency (EE) in boththe conventional H-cell and flow-cell. The maximum FEs of 94.44% and 98.89% areachieved at the potential of -1.0 V vs. RHE in the H-cell and flow-cell, respectively.Furthermore, long-term stability of more than 900 hours is demonstrated in a two-electrode configuration. Combined molecular dynamics and first-principle calculationsascribe the remarkable activity toward formate production to synergistically acceleratedmass transport and charge transfer kinetics .    

    

** Review of electrocatalytic reduction of CO2 on carbon supported films   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.022")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390721078"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390721078"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390721078"))][Get cited by]]

OpenAlex: https://openalex.org/W4390721078 (Open access: False)
    
[[https://openalex.org/A5091844504][Afdhal Yuda]], [[https://openalex.org/A5042313856][Parisa Ebrahimi]], [[https://openalex.org/A5083118237][Josephine Selvaraj]], [[https://openalex.org/A5034418975][Anand Kumar]], [[https://openalex.org/A5009923215][Vaidyanathan Subramanian]], International Journal of Hydrogen Energy. 57(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.01.022 
     
Carbon capture and conversion are becoming increasingly important as atmospheric CO2 concentrations rise and their adverse effects become increasingly evident. CO2 conversion/utilization-related research has gained renewed interest on a variety of platforms, including thermal, solar, biological, photochemical, and electrochemical conversions. Electrochemical routes, using suitable catalysts, are potentially suitable for commercial purposes owing to ease of integration with solvent-based carbon capture processes. This paper summarizes and evaluates the studies conducted within the past decade regarding the feasibility of carbon-based supports utilized in electrocatalytic carbon dioxide reduction. CO2 conversion has been reviewed in a number of reports, focusing on specific sections, such as metallic/bimetallic catalysts, CO2 solubility, and the fabrication of electrodes and electrochemical cells. The number of publications addressing various carbon-based electrocatalysts is increasing, but these materials have not yet been reviewed. Herein, we are focused on three types of electrocatalyst materials: metals, metal-oxides, non-oxides, and combinations thereof with carbon. The scope of this study includes the following: i) carbon-based materials and how they are characterized by distinctive properties, ii) electrocatalytic CO2 conversion techniques, and iii) research cases for carbon allotrope-supported composites used in CO2 reduction. The advancement in analytical tools that provide insight into liquid-phase reactions will benefit the development of catalysts and electrodes that will be effective in converting CO2 into the desired products. Such developments will also be applicable to other systems involving liquid electrolytes or solvents for performing reactions on catalyst surfaces.    

    

** Engineering redox-active electrochemically mediated carbon dioxide capture systems   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s44286-023-00003-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390754419"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390754419"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390754419"))][Get cited by]]

OpenAlex: https://openalex.org/W4390754419 (Open access: False)
    
[[https://openalex.org/A5037389256][Michael Edward Lev Massen-Hane]], [[https://openalex.org/A5019447853][Kyle M. Diederichsen]], [[https://openalex.org/A5046348268][T. Alan Hatton]], No host. 1(1)] 2024. https://doi.org/10.1038/s44286-023-00003-3 
     
With ever-increasing atmospheric carbon dioxide concentrations and commitments to limit global temperatures to less than 1.5 °C above pre-industrial levels, the need for versatile, low-cost carbon dioxide capture technologies is paramount. Electrochemically mediated carbon dioxide separation systems promise low energetics, modular scalability and ease of implementation, with direct integration to renewable energy for net-negative carbon dioxide operations. For these systems to be cost-competitive, key factors around their operation, stability and scaling need to be addressed. Energy penalties associated with redox-active species transport, gas transport and bubble formation limit the volumetric productivity and scaling potential due to their cost and footprint. Here we highlight the importance of engineering approaches towards enhancing the performance of redox-active electrochemically mediated carbon dioxide capture systems to enable their widespread implementation. This Perspective discusses electrochemically mediated carbon dioxide capture systems, which can offer lower energetics than standard thermal methods, with modular scalability. New integrated configurations can further reduce costs and improve unit productivity, while further engineering of existing cell designs will enable more rapid implementation.    

    

** Mechanism of electrocatalytic CO2 reduction reaction by borophene supported bimetallic catalysts   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.051")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390766525"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390766525"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390766525"))][Get cited by]]

OpenAlex: https://openalex.org/W4390766525 (Open access: False)
    
[[https://openalex.org/A5046345736][Meiling Liu]], [[https://openalex.org/A5015144181][Jayaraman Balamurugan]], [[https://openalex.org/A5035654478][Tongxiang Liang]], [[https://openalex.org/A5044538497][Chao Liu]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.051 
     
Bimetal atom catalysts (BACs) hold significant potential for various applications as a result of the synergistic interaction between adjacent metal atoms. This interaction leads to improved catalytic performance, while simultaneously maintaining high atomic efficiency and exceptional selectivity, similar to single atom catalysts (SACs). Bimetallic site catalysts (M2β12) supported by β12-borophene were developed as catalysts for electrocatalytic carbon dioxide reduction reaction (CO2RR). The research on density functional theory (DFT) demonstrates that M2β12 exhibits exceptional stability, conductivity, and catalytic activity. Investigating the most efficient reaction pathway for CO2RR by analyzing the Gibbs free energy (ΔG) during potential determining steps (PDS) and choosing a catalyst with outstanding catalytic performance for CO2RR. The overpotential required for Fe2β12 and Ag2β12 to generate CO is merely 0.05 V. This implies that the conversion of CO2 to CO can be accomplished with minimal additional voltage. The overpotential values for Cu2β12 and Ag2β12 during the formation of HCOOH were merely 0.001 and 0.07 V, respectively. Furthermore, the Rh2β12 catalyst exhibits a relatively low overpotential of 0.51 V for CH3OH and 0.65 V for CH4. The Fe2β12 produces C2H4 through the *CO-*CO pathway, while Ag2β12 generates CH3CH2OH via the *CO-*CHO coupling pathway, with remarkably low overpotentials of 0.84 and 0.60 V, respectively. The study provides valuable insights for the systematic design and screening of electrocatalysts for CO2RR that exhibit exceptional catalytic performance and selectivity.    

    

** Biomass‐Derived Electrocatalysts: Low‐Cost, Robust Materials for Sustainable Electrochemical Energy Conversion   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aesr.202470001")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390777858"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390777858"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390777858"))][Get cited by]]

OpenAlex: https://openalex.org/W4390777858 (Open access: True)
    
[[https://openalex.org/A5054432850][Tengyi Liu]], [[https://openalex.org/A5045153170][Hiroshi Yabu]], No host. 5(1)] 2024. https://doi.org/10.1002/aesr.202470001  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/aesr.202470001][pdf]])
     
Biomass-Derived Electrocatalysts In article number 2300168, Tengyi Liu, and Hiroshi Yabu summarize the latest reports on synthesizing oxygen reduction reaction, oxygen evolution reaction, carbon dioxide reduction reaction, and other electrochemical catalysts from biomass-derived materials. The review provides guidelines for the design and synthesis of electrocatalysts that form catalytic active sites and realize high conductivity, either individually or both, using biomass-derived materials.    

    

** Comparative microwave catalytic pyrolysis of cellulose and lignin in nitrogen and carbon dioxide atmospheres   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jclepro.2024.140750")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390859703"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390859703"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390859703"))][Get cited by]]

OpenAlex: https://openalex.org/W4390859703 (Open access: False)
    
[[https://openalex.org/A5013690081][Yang Liu]], [[https://openalex.org/A5046853311][Chunbao Zhou]], [[https://openalex.org/A5076999164][Asif Ali Siyal]], [[https://openalex.org/A5072331448][Chenglong Liu]], [[https://openalex.org/A5077293966][Yingwen Zhang]], [[https://openalex.org/A5004325054][Jie Fu]], [[https://openalex.org/A5054765827][Huimin Yun]], [[https://openalex.org/A5065911244][Jianjun Dai]], [[https://openalex.org/A5090354103][Xiaotao Bi]], Journal of Cleaner Production. None(None)] 2024. https://doi.org/10.1016/j.jclepro.2024.140750 
     
In this paper, a cleaner pyrolysis strategy combining microwave heating, catalyst and carbon dioxide was explored for converting biomass components into higher quality products. Catalytic pyrolysis was more favorable for the decomposition and conversion of complex biomass structures. For furfural residue pyrolysis, potassium sulfate contained in sample served as the main catalytic component. Potassium sulfate promoted the increase of phenols in bio-oil. Notably, carbon dioxide atmosphere promoted the decomposition of substances and exerted a significant effect on biomass pyrolysis, which increased bio-oil yield and declined gas yield. When the pyrolysis atmosphere was changed from nitrogen to carbon dioxide, the ID/IG ratio decreased from 1.07 to 0.74, indicating that carbon dioxide decreased defect structure in biochar. Carbon dioxide enriched the porous structure and surface roughness of biochar. Also, carbon dioxide as a carrier gas was found to be more effective than nitrogen in improving the heating values of biochar and the acidity of bio-oil under carbon dioxide was lower than that under nitrogen, which was conducive to the subsequent utilization of biochar and bio-oil. Carbon dioxide promoted the production of alcohols, alkenes, and alkanes in bio-oil. Beneficially, the interaction of cellulose and lignin inhibited the release of hydrogen chloride. At last, this study also provides insights into the mechanism of catalyst and CO2 on biomass microwave pyrolysis.    

    

** Tuning Carbon Dioxide Reduction Reaction Selectivity of Bi Single‐Atom Electrocatalysts with Controlled Coordination Environments   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202301452")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390886115"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390886115"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390886115"))][Get cited by]]

OpenAlex: https://openalex.org/W4390886115 (Open access: False)
    
[[https://openalex.org/A5032506444][Saswati Santra]], [[https://openalex.org/A5009979031][Verena Streibel]], [[https://openalex.org/A5044703500][Laura I. Wagner]], [[https://openalex.org/A5021692036][Ningyan Cheng]], [[https://openalex.org/A5038169912][Ding Pan]], [[https://openalex.org/A5004164166][Guanda Zhou]], [[https://openalex.org/A5052076422][Elise Sirotti]], [[https://openalex.org/A5036243978][Ryan Kisslinger]], [[https://openalex.org/A5074605033][Tim Rieth]], [[https://openalex.org/A5026066949][Siyuan Zhang]], [[https://openalex.org/A5067422150][Ian D. Sharp]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202301452 
     
Control over product selectivity of the electrocatalytic CO2 reduction reaction (CO2RR) is a crucial challenge for the sustainable production of carbon-based chemical feedstocks. In this regard, single-atom catalysts (SACs) are promising materials due to their tunable coordination environments, which could enable tailored catalytic activities and selectivities, as well as new insights into structure-activity relationships. However, direct evidence for selectivity control via systematic tuning of the SAC coordination environment is scarce. In this work, we have synthesized two differently coordinated Bi SACs anchored to the same host material (carbon black) and characterized their CO2RR activities and selectivities. We find that oxophilic, oxygen-coordinated Bi atoms produce HCOOH, while nitrogen-coordinated Bi atoms generate CO. Importantly, use of the same support material assured that alternation of the coordination environment is the dominant factor for controlling the CO2RR product selectivity. Overall, this work demonstrates the structure-activity relationship of Bi SACs, which can be utilized to establish control over CO2RR product distributions, and highlights the promise for engineering atomic coordination environments of SACs to tune reaction pathways.    

    

** Highly selective photoelectrochemical CO 2 reduction by crystal phase-modulated nanocrystals without parasitic absorption   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1073/pnas.2316724121")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390935731"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390935731"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390935731"))][Get cited by]]

OpenAlex: https://openalex.org/W4390935731 (Open access: False)
    
[[https://openalex.org/A5089077705][Qingzhen Wang]], [[https://openalex.org/A5010234675][Bin Liu]], [[https://openalex.org/A5001426883][Shujie Wang]], [[https://openalex.org/A5069848293][Peng Zhang]], [[https://openalex.org/A5066370833][Tuo Wang]], [[https://openalex.org/A5047030779][Jinlong Gong]], Proceedings of the National Academy of Sciences of the United States of America. 121(4)] 2024. https://doi.org/10.1073/pnas.2316724121 
     
Photoelectrochemical (PEC) carbon dioxide (CO2) reduction (CO2R) holds the potential to reduce the costs of solar fuel production by integrating CO2 utilization and light harvesting within one integrated device. However, the CO2R selectivity on the photocathode is limited by the lack of catalytic active sites and competition with the hydrogen evolution reaction. On the other hand, serious parasitic light absorption occurs on the front-side-illuminated photocathode due to the poor light transmittance of CO2R cocatalyst films, resulting in extremely low photocurrent density at the CO2R equilibrium potential. This paper describes the design and fabrication of a photocathode consisting of crystal phase-modulated Ag nanocrystal cocatalysts integrated on illumination-reaction decoupled heterojunction silicon (Si) substrate for the selective and efficient conversion of CO2. Ag nanocrystals containing unconventional hexagonal close-packed phases accelerate the charge transfer process in CO2R reaction, exhibiting excellent catalytic performance. Heterojunction Si substrate decouples light absorption from the CO2R catalyst layer, preventing the parasitic light absorption. The obtained photocathode exhibits a carbon monoxide (CO) Faradaic efficiency (FE) higher than 90% in a wide potential range, with the maximum FE reaching up to 97.4% at -0.2 V vs. reversible hydrogen electrode. At the CO2/CO equilibrium potential, a CO partial photocurrent density of -2.7 mA cm-2 with a CO FE of 96.5% is achieved in 0.1 M KHCO3 electrolyte on this photocathode, surpassing the expensive benchmark Au-based PEC CO2R system.    

    

** Challenges in Photocatalytic Carbon Dioxide Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/prechem.3c00112")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390937362"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390937362"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390937362"))][Get cited by]]

OpenAlex: https://openalex.org/W4390937362 (Open access: True)
    
[[https://openalex.org/A5062278897][Guangfu Liao]], [[https://openalex.org/A5083749310][Guixiang Ding]], [[https://openalex.org/A5055594201][Bin Yang]], [[https://openalex.org/A5088434794][Chunxue Li]], Precision Chemistry. None(None)] 2024. https://doi.org/10.1021/prechem.3c00112  ([[https://pubs.acs.org/doi/pdf/10.1021/prechem.3c00112][pdf]])
     
An energy crisis and significant anthropogenic CO2 emissions as a result of rising fossil fuel consumption have caused a rapid increase in global temperature. One of the best solutions to these two issues is thought to be the photocatalytic reduction of CO2 into value-added carbon-containing products. In this aspect, the main challenges mainly include the photocatalytic mechanism, reaction activity, and product selectivity, especially in ambiguous reaction pathways and product selectivity, an unclear charge transfer mechanism, and an overestimate of product yield. Therefore, in this perspective, we attempt to exhibit the discussion and in-depth analysis of the possible reaction pathways and product selectivity, the specific charge transfer mechanism, and the origin of carbon-containing products in phtocatalytic CO2 reduction. Besides, the fundamentals for photocatalytic CO2 reduction are also illustrated. Finally, the state-of-the-art challenges and perspectives in CO2 photoreduction are highlighted and discussed in detail. This perspective is expected to evoke more research attention for the photocatalytic reduction of CO2 into value-added products.    

    

** Molecular Additives Improve the Selectivity of CO2 Photoelectrochemical Reduction over Gold Nanoparticles on Gallium Nitride   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.3c03590")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390943227"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390943227"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390943227"))][Get cited by]]

OpenAlex: https://openalex.org/W4390943227 (Open access: False)
    
[[https://openalex.org/A5034872224][Aisulu Aitbekova]], [[https://openalex.org/A5079861547][Nicholas B. Watkins]], [[https://openalex.org/A5072433173][Matthias H. Richter]], [[https://openalex.org/A5042520017][Phillip Jahelka]], [[https://openalex.org/A5057055428][Jonas C. Peters]], [[https://openalex.org/A5004911977][Theodor Agapie]], [[https://openalex.org/A5082887836][Harry A. Atwater]], Nano Letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.3c03590 
     
Photoelectrochemical CO2 reduction (CO2R) is an appealing solution for converting carbon dioxide into higher-value products. However, CO2R in aqueous electrolytes suffers from poor selectivity due to the competitive hydrogen evolution reaction that is dominant on semiconductor surfaces in aqueous electrolytes. We demonstrate that functionalizing gold/p-type gallium nitride devices with a film derived from diphenyliodonium triflate suppresses hydrogen generation from 90% to 18%. As a result, we observe increases in the Faradaic efficiency and partial current density for carbon monoxide of 50% and 3-fold, respectively. Furthermore, we demonstrate through optical absorption measurements that the molecular film employed herein, regardless of thickness, does not affect the photocathode’s light absorption. Altogether, this study provides a rigorous platform for elucidating the catalytic structure–property relationships to enable engineering of active, stable, and selective materials for photoelectrochemical CO2R.    

    

** Composition effects of electrodeposited Cu-Ag nanostructured electrocatalysts for CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-tfkhh")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390979173"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390979173"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390979173"))][Get cited by]]

OpenAlex: https://openalex.org/W4390979173 (Open access: True)
    
[[https://openalex.org/A5001934074][Elena Plaza-Mayoral]], [[https://openalex.org/A5018856830][Valery Okatenko]], [[https://openalex.org/A5026251278][Kim N. Dalby]], [[https://openalex.org/A5091012326][Hanne Falsig]], [[https://openalex.org/A5090008029][Ib Chorkendorff]], [[https://openalex.org/A5079498717][Paula Sebastián‐Pascual]], [[https://openalex.org/A5026837841][María Escudero‐Escribano]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-tfkhh  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65a796cf9138d231611c2449/original/composition-effects-of-electrodeposited-cu-ag-nanostructured-electrocatalysts-for-co2-reduction.pdf][pdf]])
     
The electrochemical reduction of carbon dioxide (CO2RR) to valuable C2+ liquid fuels and oxygenates, such as ethanol and propanol, is a promising strategy to minimize the carbon footprint and store renewable electricity. In this study, we investigate the CO2RR on electrodeposited Cu-Ag nanostructures obtained using a green choline chloride and urea deep eutectic solvent (DES). We show that Cu-Ag nanostructured electrocatalysts with tunable composition, loadings, and size can be simply prepared in one step, without adding other additives or surfactant agents. We investigate the intrinsic activity and selectivity of the CO2RR by determining the electrochemically active surface area (ECSA) using lead underpotential deposition (UPD). The analysis of the partial current densities normalized by the ECSA shows that the addition of Ag on electrodeposited Cu primarily suppresses the production of hydrogen and methane with respect to Cu nanostructures. At the same time, the production of carbon monoxide (CO) slightly increases but, the partial current of the total C2+ products does not considerably increase. Despite that the production rate of C2+ is similar on Cu and CuAg, the addition of Ag enhances the formation of alcohols and oxygenates over ethylene, in line with previous reports. We highlight the potential of metal electrodeposition from DES as a sustainable and inexpensive strategy for the development of bimetallic Cu-based nanocatalysts towards CO2RR.    

    

** Recent advances in copper-based catalysts for electrocatalytic CO 2 reduction toward multi-carbon products   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26599/nre.2024.9120112")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987371"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987371 (Open access: True)
    
[[https://openalex.org/A5025855204][Rongrong Li]], [[https://openalex.org/A5058501731][Hehe Wei]], [[https://openalex.org/A5077153113][Ping Liu]], [[https://openalex.org/A5071574675][Zixiang Su]], [[https://openalex.org/A5062523981][X. G. Gong]], Nano Research Energy. None(None)] 2024. https://doi.org/10.26599/nre.2024.9120112  ([[https://file.sciopen.com/sciopen_public/1747873898448973825.pdf][pdf]])
     
Electrocatalytic carbon dioxide reduction reaction (CO2RR) holds the promise of both overcoming the greenhouse effect and synthesizing a wealth of chemicals. Electrocatalytic CO2 reduction toward carbon-containing products, including C1 products (carbon monoxide, formic acid, etc), C2 products (ethylene, ethanol, etc.) and multi-carbon products (e.g., npropanol), provides beneficial fuel and chemicals for industrial production. The complexity of the multi-proton transfer processes and difficulties of C-C coupling in electrochemical CO2 reduction toward multi-carbon(C2+) products have attracted increasing concerns on the design of catalysts in comparison with those of C1 products. In this paper, we review the main advances in the syntheses of multi-carbon products through electrocatalytic carbon dioxide reduction in recent years, introduce the basic principles of electrocatalytic CO2RR, and detailly elucidate two widely accepted mechanisms of C-C coupling reactions. Among abundant nanomaterials, copper-based catalysts are outstanding catalysts for the preparation of multi-carbon chemicals in electrochemical CO2RR attributing to effective C-C coupling reactions. Regarding the different selectivity of multi-carbon chemicals but extensively applied copper-based catalysts, we classify and summarize various Cu-based catalysts through separating diverse multi-carbon products, where the modification of spatial and electronic structures is beneficial to increase the coverage of CO or lower the activation energy barrier for forming CC bond to form the key intermediates and increase the production of multi-carbon products. Challenges and prospects involving the fundamental and development of copper-based catalysts in electrochemical CO2 reduction reaction are also proposed.    

    

** MOFs materials as photocatalysts for CO2 reduction: Progress, challenges and perspectives   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ccst.2024.100191")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391019430"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391019430"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391019430"))][Get cited by]]

OpenAlex: https://openalex.org/W4391019430 (Open access: True)
    
[[https://openalex.org/A5049709719][Mazhar Khan]], [[https://openalex.org/A5003303773][Zeeshan Akmal]], [[https://openalex.org/A5003238643][Muhammad Tayyab]], [[https://openalex.org/A5070908155][Seemal Mansoor]], [[https://openalex.org/A5086947282][Adnan Zeb]], [[https://openalex.org/A5068766141][Ziwei Ye]], [[https://openalex.org/A5001457544][Jinlong Zhang]], [[https://openalex.org/A5067320385][Shiqun Wu]], [[https://openalex.org/A5050352409][Lingzhi Wang]], No host. 11(None)] 2024. https://doi.org/10.1016/j.ccst.2024.100191 
     
Photocatalytic reduction of carbon dioxide (CO2) presents a pivotal solution to address meteorological and ecological challenges. Currently, metal-organic frameworks (MOFs) with their crystalline porosity, adjustable structures, and diverse chemical functionalities have garnered significant attention in the realm of photocatalytic CO2 reduction. This review provides a brief introduction to CO2 reduction and MOF material and their applications in CO2 reduction. Then, it undertakes a comprehensive examination of MOFs, summarizing their key attributes, including porosity, large surface area, structural multifunctionalities, and responsiveness to visible light, along with an analysis of heterojunctions and their methods of preparation. Additionally, it elucidates the fundamental principle of photocatalysis and CO2 reduction, encompassing both half and overall reactions. Furthermore, the classification of MOF-based materials is explored, along with the proposed mechanism for CO2 reduction and an update on recent developments in this field. Finally, this review outlines the challenges and potential opportunities for utilizing MOFs in CO2 reduction, offering valuable insights to scholars seeking innovative approaches not only to enhance CO2 reduction but also to advance other photocatalytic processes.    

    

** Monomeric gold hydrides for carbon dioxide reduction: ligand effect on the reactivity   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202303512")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390674634"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390674634"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390674634"))][Get cited by]]

OpenAlex: https://openalex.org/W4390674634 (Open access: False)
    
[[https://openalex.org/A5019871772][Elisa Rossi]], [[https://openalex.org/A5082611443][Diego Sorbelli]], [[https://openalex.org/A5052163219][Paola Belanzoni]], [[https://openalex.org/A5058779678][Leonardo Belpassi]], [[https://openalex.org/A5000460535][Gianluca Ciancaleoni]], No host. None(None)] 2024. https://doi.org/10.1002/chem.202303512 
     
We analyzed the ligand electronic effect in the reaction between a [LAu(I)H]0/‐ hydride species and CO2, leading to a coordinated formate [LAu(HCOO)]0/‐. We explored 20 different ligands, such as carbenes, phosphines and others, carefully selected to cover a wide range of electron‐donor and ‐acceptor properties. We included in the study the only ligand, an NHC‐coordinated diphosphene, that, thus far, experimentally demonstrated facile and reversible reaction between the monomeric gold(I) hydride and carbon dioxide. We elucidated the previously unknown reaction mechanism, which resulted to be concerted and common to all the ligands: the gold‐hydrogen bond attacks the carbon atom of CO2 with one oxygen atom coordinating to the gold center. A correlation between the ligand σ donor ability, which affects the electron density at the reactive site, and the kinetic activation barriers of the reaction has been found. This systematic study offers useful guidelines for the rational design of new ligands for this reaction, while suggesting a few promising and experimentally accessible potential candidates for the stoichiometric or catalytic CO2 activation.    

    

** A Thermodynamic View on the In-situ Carbon Dioxide Reduction by Biomass-derived Hydrogen during Calcium Carbonate Decomposition   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cjche.2023.12.017")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391037978"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391037978"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391037978"))][Get cited by]]

OpenAlex: https://openalex.org/W4391037978 (Open access: False)
    
[[https://openalex.org/A5017430213][Peng Jiang]], [[https://openalex.org/A5049341927][Hao Zhang]], [[https://openalex.org/A5089446069][Guanhan Zhao]], [[https://openalex.org/A5058965019][Lin Li]], [[https://openalex.org/A5022762913][Tuo Ji]], [[https://openalex.org/A5066372594][Liwen Mu]], [[https://openalex.org/A5048052547][Xiaohua Lü]], [[https://openalex.org/A5024790419][Jiahua Zhu]], Chinese Journal of Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.cjche.2023.12.017 
     
In the carbonate industry, deep decarbonization strategies are necessary to effectively remediate CO2. These strategies mainly include both sustainable energy supplies and the conversion of CO2 in downstream processes. This study developed a coupled process of biomass chemical looping H2 production and reductive calcination of CaCO3. Firstly, a mass and energy balance of the coupled process was established in Aspen Plus. Following this, process optimization and energy integration were implemented to provide optimized operation conditions. Lastly, a life cycle assessment was carried out to assess the carbon footprint of the coupled process. Results reveal that the decomposition temperature of CaCO3 in an H2 atmosphere can be reduced to 780 oC (generally around 900 oC), and the conversion of CO2 from CaCO3 decomposition reached 81.33% with an H2:CO ratio of 2.49 in gaseous products. By optimizing systemic energy through heat integration, an energy efficiency of 86.30% was achieved. Additionally, the carbon footprint analysis revealed that the process with energy integration had a low GWP of -2.624 kgCO2-eq·kg-CaO-1. Conclusively, this work performed a systematic analysis of introducing biomass-derived H2 into CaCO3 calcination and demonstrated the positive role of reductive calcination using green H2 in mitigating CO2 emissions within the carbonate industry.    

    

** Carbon dioxide-steam reforming gasification of carbonized biomass pellet for high syngas yield and TAR reduction through CFD modeling   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ces.2024.119716")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390673968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390673968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390673968"))][Get cited by]]

OpenAlex: https://openalex.org/W4390673968 (Open access: False)
    
[[https://openalex.org/A5093694460][Kannie Winston Kuttin]], [[https://openalex.org/A5021859077][Asma Leghari]], [[https://openalex.org/A5078348179][Hai Yu]], [[https://openalex.org/A5071640024][Zihong Xia]], [[https://openalex.org/A5083721182][Lu Ding]], [[https://openalex.org/A5003907985][Guangsuo Yu]], Chemical Engineering Science. None(None)] 2024. https://doi.org/10.1016/j.ces.2024.119716 
     
Experimental and numerical evaluation of steam and carbon dioxide gasification on torrefied palm kernel shell in an updraft fixed bed gasifier is studied. Euler-Lagrangian two-dimensional model with 15 kinetic reactions is developed to investigate tar formation in relation to torrefaction temperature, gasification temperature, and steam-to-carbon-dioxide ratio (S-CO2-R). The combination of steam and CO2 had considerable effect on the tar reduction and also influenced the gaseous composition significantly when the varying parameters were compared. The results show that increasing both gasification temperature and S-CO2-R do enhance the H2 production whiles drastically reducing the tar formation. The tar concentration reduced by 21.4 % and 20.5 % by changing the S-CO2-R from 0.4 to 2.0 and gasification process temperature from 973 and 1173 K respectively. An increase in hydrogen is also observed, from 55.5 % to 60.84 %, when the S-CO2-R is increased to 1.2. Similarly, 29.1 % increase is observed in gasification efficiency as compared to the raw-PKS.    

    

** N-modulated Cu0-Cu+ Sites for C1/C2 Selectivity Regulation of Carbon Dioxide Electrocatalytic Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173488")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390768112"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390768112"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390768112"))][Get cited by]]

OpenAlex: https://openalex.org/W4390768112 (Open access: False)
    
[[https://openalex.org/A5044804439][Wenda Zhang]], [[https://openalex.org/A5007515159][Yizhong Zou]], [[https://openalex.org/A5071785481][Ming Chen]], [[https://openalex.org/A5057775896][Wen Jiang]], [[https://openalex.org/A5052882772][Xiaodong Yan]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.173488 
     
Controlling the valence states of copper is pivotal in determining the selectivity of products in CO2 electroreduction. In this study, we developed a Cu doped carbon catalyst (CuNC) derived from a metal-organic framework (MOFs) through a straightforward solution reaction and calcination method. The N-modulated Cu0-Cu+ sites exhibited adjustable C1 and C2 selectivity in electrocatalytic CO2 reduction (CER). Specifically, the CuNC-700 demonstrated an impressive C2 Faradaic efficiency (FE) of 56.0% at -1.0 V vs reversible hydrogen electrode (RHE), and a remarkable C1 FE of 56.7% with a total current density of 600 mA/cm2 at -1.6 V vs RHE. In the entire potential range, the CuNC-700 consistently maintained high FE values of > 92% for CER, while the FE values for hydrogen evolution reaction is below 8%. This study unveiled the correlation between the selectivity and the valence states of copper. At low applied potentials, the abundance of N-modulated Cu0-Cu+ sites led to the predominant production of the C2 products. The Cu0 played a primary role in activating CO2 and facilitating subsequent electron transfer, while the Cu+ enhanced the adsorption of *CO, further promoting the C-C coupling. Under high applied potentials, both Cu2+ and Cu+ were converted to Cu0, favoring the methanation process. This research paves the way for future design of Cu-based MOF-derived materials, enabling precise regulation of C1/C2 selectivity in CER.    

    

** Mesoporous Ts-1 Zeolite-Confined Metal Oxides Photocathode for Efficient Reduction of Carbon Dioxide to Methanol   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4697343")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390901587"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390901587"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390901587"))][Get cited by]]

OpenAlex: https://openalex.org/W4390901587 (Open access: False)
    
[[https://openalex.org/A5015863205][Haihui Liu]], [[https://openalex.org/A5074378034][Xiaowen Zhou]], [[https://openalex.org/A5032032704][Kangli Xu]], [[https://openalex.org/A5054743377][Heng Zhang]], [[https://openalex.org/A5036723504][Huan Wang]], [[https://openalex.org/A5059995305][Hongqing Zhou]], [[https://openalex.org/A5013084576][Hangrong Chen]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4697343 
     
Excessive CO2 emission has caused serious environmental problems, and converting CO2 to high value-added fuels is attractive for solving energy and environmental crisis. Herein, a novel mesoporous TS-1(mTS-1) zeolite-confined metal oxides nanoclusters Cu-Bi@mTS-1 was developed for efficient photoelectrochemical reduction reaction of CO2 (PEC CO2RR). The catalyst Cu-Bi@mTS-1 as a photocathode showed high activity, achieving a maximum methanol Faraday efficiency (FECH3OH) of 93.4% at -0.7 V vs. RHE. In-situ Raman results indicate the formation of key reaction intermediates *OCH3 and *CHO during the conversion of CO2 to CH3OH. The C2 product ethanol could be also detected at higher potentials during PEC CO2RR. It is believed that the hierarchically porous structure of mTS-1 is conducive to the enrichment of CO2 molecules to increase the reactant concentration, also can promote C-C coupling through photoelectric synergism. This work provides a favorable reference for the rational design of photocathodes by confinement effect of porous structure.    

    

** Energy recovery potential in Bangladesh from elevated temperature textile processing wastewater: an analysis of energy recovery, energy economics and reduction in carbon dioxide emission   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40808-023-01933-w")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390668426"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390668426"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390668426"))][Get cited by]]

OpenAlex: https://openalex.org/W4390668426 (Open access: False)
    
[[https://openalex.org/A5002219158][I. Haque]], [[https://openalex.org/A5036003023][Mohammad Moshiur Rahman]], [[https://openalex.org/A5011709319][Md. Sahil Rafiq]], [[https://openalex.org/A5093693771][Mohammad Shakhawat Hosen Apurba]], [[https://openalex.org/A5057007396][Nadim Reza Khandaker]], Modeling Earth Systems and Environment. None(None)] 2024. https://doi.org/10.1007/s40808-023-01933-w 
     
No abstract    

    

** Design of highly selective and stable CsPbI3 perovskite catalyst for photocatalytic reduction of CO2 to C1 product   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.030")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390753904"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390753904"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390753904"))][Get cited by]]

OpenAlex: https://openalex.org/W4390753904 (Open access: False)
    
[[https://openalex.org/A5019450682][Qiming Zhang]], [[https://openalex.org/A5038889077][Linhao Liu]], [[https://openalex.org/A5059632641][Tong‐Qi Yuan]], [[https://openalex.org/A5050215551][Juan Hou]], [[https://openalex.org/A5035504703][Xiaodong Yang]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.030 
     
Finding efficient photocatalytic carbon dioxide reduction catalysts is one of the core issues in addressing global climate change. Herein, the pristine CsPbI3 perovskite and doped CsPbI3 perovskite were evaluated in carbon dioxide reduction reaction (CO2RR) to C1 products by using density functional theory. Free energy testing and electronic structure analysis methods have shown that doped CsPbI3 exhibits more effective catalytic performance, higher selectivity, and stability than undoped CsPbI3. Additionally, it is discovered that CsPbI3 (100) and (110) crystal surfaces have varied product selectivity. The photo-catalytic effectiveness is increased by the narrower band gap of Bi and Sn doped CsPbI3, which broadens the absorption spectrum of visible light and makes electron transport easier. The calculation results indicate that Bi doped CsPbI3 (100) and CsPbI3 (110) crystal faces exhibit good selectivity towards CH4, with free energy barriers as low as 0.55 eV and 0.58 eV, respectively. Sn doped CsPbI3 (100) and CsPbI3 (110) crystal planes exhibit good selectivity for HCOOH and CH3OH, respectively. The results indicate that the Bi and Sn doped CsPbI3 perovskite catalyst can further improve the CO2 photocatalytic activity and high selectivity for C1 products, making it a suitable substrate material for high-performance CO2RR.    

    

** Synthesis and Electrocatalytic Applications of Layer‐Structured Metal Chalcogenides Composites   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310526")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390884831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390884831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390884831"))][Get cited by]]

OpenAlex: https://openalex.org/W4390884831 (Open access: False)
    
[[https://openalex.org/A5000836661][Yongteng Qian]], [[https://openalex.org/A5066738004][Fangfang Zhang]], [[https://openalex.org/A5026571332][Xingguang Luο]], [[https://openalex.org/A5037880072][Yijun Zhong]], [[https://openalex.org/A5061505485][Dae Joon Kang]], [[https://openalex.org/A5004880276][Yong Hu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202310526 
     
Abstract Featured with the attractive properties such as large surface area, unique atomic layer thickness, excellent electronic conductivity, and superior catalytic activity, layered metal chalcogenides (LMCs) have received considerable research attention in electrocatalytic applications. In this review, the approaches developed to synthesize LMCs‐based electrocatalysts are summarized. Recent progress in LMCs‐based composites for electrochemical energy conversion applications including oxygen reduction reaction, carbon dioxide reduction reaction, oxygen evolution reaction, hydrogen evolution reaction, overall water splitting, and nitrogen reduction reaction is reviewed, and the potential opportunities and practical obstacles for the development of LMCs‐based composites as high‐performing active substances for electrocatalytic applications are also discussed. This review may provide an inspiring guidance for developing high‐performance LMCs for electrochemical energy conversion applications.    

    

** Effect of Co2 Shortage on the Performance of Membrane Electrode Co2 Electrolyzer   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4695651")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390872406"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390872406"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390872406"))][Get cited by]]

OpenAlex: https://openalex.org/W4390872406 (Open access: False)
    
[[https://openalex.org/A5057281614][Xianwen Zhang]], [[https://openalex.org/A5000197949][Feiyue Cao]], [[https://openalex.org/A5088116668][Peng Hao]], [[https://openalex.org/A5051158759][Yang Cao]], [[https://openalex.org/A5002419717][Taotao Zhou]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4695651 
     
To mitigate greenhouse effects, carbon dioxide reduction reaction (CO2RR) has been used as an efficient means of carbon reduction. In CO2 electrolyzer, CO2 shortage can happen and degrade the reaction efficiency. Herein, an efficient and long-lived formic acid three-cell electrolyzer is used to study the effect of CO2 shortage, by operating the electrolyzer from full CO2 supply to CO2 shortage. In addition, the effects of various CO2 fluxes and concentrations on the electrolyzer current, acid concentration and lifetime are investigated. The results demonstrated that the electrolyzer current and the CO to H2 ratio both decreases from full CO2 to CO2 shortage, indicating that the reactivity of converting CO2 into formic acid ions is weakened. On the contrary, the hydrogen evolution reaction is intensified. Long-term CO2 shortage also cause the catalyst to detach and agglomerate in the cathode catalyst layer, reducing its active surface area and overall performance. Compared with the CO2 flux, the CO2 concentration exerts a more pronounced influence. To ensure the electrolysis efficiency, the carbon dioxide concentration should not be less than 80 %.    

    

** Nature AND Nurture: Enabling formate-dependent growth in Methanosarcina acetivorans   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2024.01.08.574737")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390697828"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390697828"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390697828"))][Get cited by]]

OpenAlex: https://openalex.org/W4390697828 (Open access: True)
    
[[https://openalex.org/A5068041035][Jichen Bao]], [[https://openalex.org/A5093472391][Tejas Somvanshi]], [[https://openalex.org/A5045432123][Ying Tian]], [[https://openalex.org/A5093032219][Maxime Gabriel Laird]], [[https://openalex.org/A5014625536][Pierre Garcia]], [[https://openalex.org/A5041347017][Christian Schöne]], [[https://openalex.org/A5072152901][Michael Rother]], [[https://openalex.org/A5025882044][Guillaume Borrel]], [[https://openalex.org/A5052318836][Silvan Scheller]], No host. None(None)] 2024. https://doi.org/10.1101/2024.01.08.574737  ([[https://www.biorxiv.org/content/biorxiv/early/2024/01/09/2024.01.08.574737.full.pdf][pdf]])
     
Methanogens are essential players in the global carbon cycle. Methanosarcinales possess one of the most diverse metabolic repertoires for methanogenesis, but they have never been observed to utilize formate as a substrate. We successfully reprogrammed the primary metabolism of Methanosarcina acetivorans by introducing an exogenous formate dehydrogenase derived from a closely related species. The engineered strains acquired the capacity to harness energy from formate-dependent methanogenesis pathways, including formate-dependent methyl reduction and formate-dependent carbon dioxide reduction. The ability of M. acetivorans to thrive on formate suggests the existence of essential accessory machinery and metabolic redundancy for generating reduced ferredoxins from F420H2. This remarkable plasticity in energy metabolism raises the possibility that an ancestral lineage of Methanosarcinales may have possessed the capacity to utilize formate. By combining this genetically modified strain with a disruption in methyl disproportionation, we have created a novel tool for investigating and manipulating the components of the F420 reduction and methanogenesis pathways independently.    

    

** CO 2 electroreduction on two-dimensional transition metal 1,2,3,4,5,6,7,8,9,10,11,12-perthiolated coronene frameworks: a theoretical investigation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1080/00268976.2024.2303394")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390909288"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390909288"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390909288"))][Get cited by]]

OpenAlex: https://openalex.org/W4390909288 (Open access: False)
    
[[https://openalex.org/A5073754209][Xuelian She]], [[https://openalex.org/A5022808269][Lin Cheng]], [[https://openalex.org/A5018863416][Ying Wang]], [[https://openalex.org/A5051363890][Kai Li]], [[https://openalex.org/A5037586164][Zhijian Wu]], Molecular Physics. None(None)] 2024. https://doi.org/10.1080/00268976.2024.2303394 
     
Developing highly efficient catalysts for carbon dioxide reduction reaction (CO2RR) is significant in producing useful chemicals and alleviating environmental pollution. Herein, a series of two-dimensional TM-PTC (TM = Sc-Zn, PTC = 1,2,3,4,5,6,7,8,9,10,11,12-perthiolated coronene) frameworks as CO2RR electrocatalysts are investigated based on the density functional method. The calculated results showed that the main product is CH4 for TM-PTC (TM = Sc-Mn). However, these catalysts can be poisoned by water molecules due to its strong adsorption on the catalyst surface. To solve the problem, we modified these catalysts by adding axial oxygen (TM-O-PTC). Our study showed that TM-O-PTC (TM = V, Cr) are good catalysts for CO2RR to produce CH4. We expected that this work could provide a useful strategy for developing high-performance CO2RR electrocatalysts.    

    

** Peeking into the Femtosecond Hot-Carrier Dynamics Reveals Unexpected Mechanisms in Plasmonic Photocatalysis   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.3c12470")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390743905"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390743905"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390743905"))][Get cited by]]

OpenAlex: https://openalex.org/W4390743905 (Open access: True)
    
[[https://openalex.org/A5030114701][Giulia Dall’Osto]], [[https://openalex.org/A5034214423][Margherita Marsili]], [[https://openalex.org/A5038585202][Mirko Vanzan]], [[https://openalex.org/A5049528343][Daniele Toffoli]], [[https://openalex.org/A5084612398][Mauro Stener]], [[https://openalex.org/A5078141074][Stefano Corni]], [[https://openalex.org/A5037684430][Emanuele Coccia]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.3c12470  ([[https://pubs.acs.org/doi/pdf/10.1021/jacs.3c12470][pdf]])
     
Plasmonic-driven photocatalysis may lead to reaction selectivity that cannot be otherwise achieved. A fundamental role is played by hot carriers, i.e., electrons and holes generated upon plasmonic decay within the metal nanostructure interacting with molecular species. Understanding the elusive microscopic mechanism behind such selectivity is a key step in the rational design of hot-carrier reactions. To accomplish that, we present state-of-the-art multiscale simulations, going beyond density functional theory, of hot-carrier injections for the rate-determining step of a photocatalytic reaction. We focus on carbon dioxide reduction, for which it was experimentally shown that the presence of a rhodium nanocube under illumination leads to the selective production of methane against carbon monoxide. We show that selectivity is due to a (predominantly) direct hole injection from rhodium to the reaction intermediate CHO. Unexpectedly, such an injection does not promote the selective reaction path by favoring proper bond breaking but rather by promoting bonding of the proper molecular fragment to the surface.    

    

** MXenes as Electrocatalysts for the CO2 Reduction Reaction: Recent Advances and Future Challenges   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202300598")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390829428"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390829428"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390829428"))][Get cited by]]

OpenAlex: https://openalex.org/W4390829428 (Open access: True)
    
[[https://openalex.org/A5080818001][Ling Peng Meng]], [[https://openalex.org/A5013714174][Ebrahim Tayyebi]], [[https://openalex.org/A5004991965][Kai S. Exner]], [[https://openalex.org/A5092197857][Francesc Viñes]], [[https://openalex.org/A5012273051][Francesc Illas]], ChemElectroChem. None(None)] 2024. https://doi.org/10.1002/celc.202300598  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/celc.202300598][pdf]])
     
Abstract Electrochemical carbon dioxide reduction (CO 2 RR) is gaining momentum as an effective process to capture and convert CO 2 into valuable chemicals and fuels, as well as to contribute reducing greenhouse gas emissions. Two‐dimensional transition metal carbides and/or nitrides (MXenes) are increasingly attracting attention as CO 2 RR electrocatalysts due to their enhanced chemical activity and selectivity, overcoming limitations of traditional metal CO 2 RR electrocatalysts, and likely breaking the scaling relations of reaction intermediates toward the desired product. The present concept reviews the state‐of‐the‐art in the computational description of CO 2 RR on MXenes, going from CO 2 activation on pristine models to different surface terminations, and discuss possible ways to tune the catalytic activity and selectivity, including doping, defects, supported single metal atoms, solvent effects, and electric field effects, while putting in the spotlight prospects by including kinetic aspects.    

    

** ATR–SEIRAS Method to Measure Interfacial pH during Electrocatalytic Nitrate Reduction on Cu   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-mb7hn")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390805684"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390805684"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390805684"))][Get cited by]]

OpenAlex: https://openalex.org/W4390805684 (Open access: True)
    
[[https://openalex.org/A5027766501][Elizabeth R. Corson]], [[https://openalex.org/A5065034148][Jinyu Guo]], [[https://openalex.org/A5064386118][William A. Tarpeh]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-mb7hn  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/659ef6939138d23161a0e248/original/atr-seiras-method-to-measure-interfacial-p-h-during-electrocatalytic-nitrate-reduction-on-cu.pdf][pdf]])
     
This study reports the accuracy and applications of an attenuated total reflectance–surface-enhanced infrared absorption spectroscopy (ATR–SEIRAS) technique to indirectly measure the interfacial pH of the electrolyte using the ratio of phosphate species within 10 nm of the electrocatalyst surface. This technique can be used in situ to study aqueous electrochemical reactions with a calibration range from pH 1–13, time resolution down to 4 s, and an average 95% confidence interval of 14% that varies depending on the pH region (acidic, neutral, or basic). The method is applied in this study to electrochemical nitrate reduction at a copper cathode to demonstrate its capabilities, but is broadly applicable to any aqueous electrochemical reaction (such as hydrogen evolution, carbon dioxide reduction, or oxygen evolution) and the electrocatalyst may be any SEIRAS-active thin film (e.g., silver, gold, or copper). The time-resolved results show a dramatic increase in the interfacial pH from pH 2–7 in the first minute of operation during both constant current and pulsed current experiments where the bulk pH is unchanged. Attempts to control the pH polarization at the surface by altering the electrochemical operating conditions—lowering the current or increasing the pulse frequency—showed no significant change, demonstrating the challenge of controlling the interfacial pH.    

    

** Molecular understanding of the critical role of alkali metal cations in initiating CO2 electroreduction on Cu(100) surface   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-44896-x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391022908"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391022908"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391022908"))][Get cited by]]

OpenAlex: https://openalex.org/W4391022908 (Open access: True)
    
[[https://openalex.org/A5032631479][Zhichao Zhang]], [[https://openalex.org/A5088591085][Hengyu Li]], [[https://openalex.org/A5038226323][Yangfan Shao]], [[https://openalex.org/A5051784756][Lin Gan]], [[https://openalex.org/A5055954152][Feiyu Kang]], [[https://openalex.org/A5080132089][Wenhui Duan]], [[https://openalex.org/A5015539284][Heine Anton Hansen]], [[https://openalex.org/A5070982282][Jianbao Li]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-44896-x  ([[https://www.nature.com/articles/s41467-024-44896-x.pdf][pdf]])
     
Abstract Molecular understanding of the solid–liquid interface is challenging but essential to elucidate the role of the environment on the kinetics of electrochemical reactions. Alkali metal cations (M + ), as a vital component at the interface, are found to be necessary for the initiation of carbon dioxide reduction reaction (CO 2 RR) on coinage metals, and the activity and selectivity of CO 2 RR could be further enhanced with the cation changing from Li + to Cs + , while the underlying mechanisms are not well understood. Herein, using ab initio molecular dynamics simulations with explicit solvation and enhanced sampling methods, we systematically investigate the role of M + in CO 2 RR on Cu surface. A monotonically decreasing CO 2 activation barrier is obtained from Li + to Cs + , which is attributed to the different coordination abilities of M + with *CO 2 . Furthermore, we show that the competing hydrogen evolution reaction must be considered simultaneously to understand the crucial role of alkali metal cations in CO 2 RR on Cu surfaces, where H + is repelled from the interface and constrained by M + . Our results provide significant insights into the design of electrochemical environments and highlight the importance of explicitly including the solvation and competing reactions in theoretical simulations of CO 2 RR.    

    

** Electrodeposition of tuneable Cu-Ag nanostructures in a deep eutectic solvent   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-lckq9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390953941"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390953941"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390953941"))][Get cited by]]

OpenAlex: https://openalex.org/W4390953941 (Open access: True)
    
[[https://openalex.org/A5001934074][Elena Plaza-Mayoral]], [[https://openalex.org/A5026251278][Kim N. Dalby]], [[https://openalex.org/A5091012326][Hanne Falsig]], [[https://openalex.org/A5090008029][Ib Chorkendorff]], [[https://openalex.org/A5079498717][Paula Sebastián‐Pascual]], [[https://openalex.org/A5026837841][María Escudero‐Escribano]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-lckq9  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65a173f7e9ebbb4db904762a/original/electrodeposition-of-tuneable-cu-ag-nanostructures-in-a-deep-eutectic-solvent.pdf][pdf]])
     
The green transition requires the preparation of clean, inexpensive, and sustainable strategies to prepare controllable bimetallic and multimetallic nanostructures. Cu-Ag nanostructures, for example, are promising bimetallic catalysts for different electrocatalytic reactions such as carbon monoxide and carbon dioxide reduction. In this work, we present the one-step preparation method of electrodeposited Cu-Ag with tunable composition and morphology from choline chloride plus urea deep eutectic solvent (DES), a non-toxic and green DES. We have assessed how different electrodeposition parameters affect the morphology and composition of our nanostructures. We combine electrochemical methods with ex-situ scanning electron microscopy (SEM), energy dispersive X-ray spectroscopy (EDS) and X-ray photoelectron spectroscopy (XPS) to characterize the nanostructures. We have estimated the electrochemically active surface area (ECSA) and roughness factor (R) by lead underpotential deposition (UPD). The copper/silver ratio in the electrodeposited nanostructures is highly sensitive to the applied potential, bath composition, and loading. We observed that silver-rich nanostructures were less adherent whereas the increase in copper content led to more stable and homogenous films with disperse rounded nanostructures with tiny spikes. These spikes were more stable when the deposition rate was fast enough and the molar ratio of Cu and Ag no greater than approximately two to one.    

    

** A global synthesis of reported urban tree carbon production rates and approaches   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/fevo.2023.1244418")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390695934"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390695934"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390695934"))][Get cited by]]

OpenAlex: https://openalex.org/W4390695934 (Open access: True)
    
[[https://openalex.org/A5028237873][G. Darrel Jenerette]], [[https://openalex.org/A5009121790][Dustin L. Herrmann]], Frontiers in Ecology and Evolution. 11(None)] 2024. https://doi.org/10.3389/fevo.2023.1244418  ([[https://www.frontiersin.org/articles/10.3389/fevo.2023.1244418/pdf?isPublishedV2=False][pdf]])
     
Trees are a prominent feature of urban ecosystems. Urban tree productivity is a key component of urban ecosystem energetics and has been identified as a possible pathway for reducing global greenhouse gas concentrations. Recently, extensive research has been directed to evaluating the carbon dynamics of urban trees in cities throughout the world. Here, we synthesize this research, using results from previous studies from 154 cities to identify the distribution of urban tree productivity globally and the basis for generating urban tree productivity estimates. Reported urban tree productivity shows a strong relationship with estimated tree carbon content and exhibits increases with both temperature and precipitation, with land cover differences influencing the degree of climate sensitivity. Compared with a reference productivity estimate, urban trees showed greatly reduced estimated rates of productivity and the magnitude of reduced productivity was inversely correlated with precipitation but was independent of temperature. Reported rates of productivity across all studies suggest climate restrictions that are more important with less intensively managed land covers. Scaling these results globally suggests a limited opportunity for urban trees to contribute to atmospheric carbon dioxide reductions, especially in the absence of major carbon emission reductions. We found that the majority of results are derived from tree inventories from a single period with rates of productivity estimate through quasi-empirical or allometric models. The majority of studies have been conducted in temperate biomes and North America. These results show that existing urban tree assessments have substantial methodological restrictions and regional biases. Future research of urban tree productivity should look toward improved methods and can use this synthesis as a baseline for comparisons and improvement.    

    

** Unconventional and Emerging Approaches to CO2 Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16020713")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390878076"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390878076"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390878076"))][Get cited by]]

OpenAlex: https://openalex.org/W4390878076 (Open access: True)
    
[[https://openalex.org/A5031060981][Jeffrey G. Bell]], [[https://openalex.org/A5069625825][Thomas Underwood]], Sustainability. 16(2)] 2024. https://doi.org/10.3390/su16020713  ([[https://www.mdpi.com/2071-1050/16/2/713/pdf?version=1705288994][pdf]])
     
This perspective highlights unconventional and emerging approaches to CO2 reduction. These methods encompass the use of topological materials and 3D printing in electrochemistry and the broader fields of plasma- and magneto-electrochemistry. Sustainability in these methods offers a way to convert CO2 into value-added fuels in a circular energy economy. We identify challenges of reducing CO2 along sustainable pathways and detail ways that unconventional approaches can address these challenges. These include achieving high product selectivity toward desirable chemicals, high catalytic durability, high energy efficiency, and high conversion rates of CO2. Finally, we describe emerging impacts and opportunities of these unconventional approaches and key challenges.    

    

** Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390920767"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390920767"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390920767"))][Get cited by]]

OpenAlex: https://openalex.org/W4390920767 (Open access: True)
    
[[https://openalex.org/A5013522313][John Cruz]], [[https://openalex.org/A5043425264][Anna Balog]], [[https://openalex.org/A5030958308][Péter S. Tóth]], [[https://openalex.org/A5090655937][Gábor Bencsik]], [[https://openalex.org/A5001143524][Gergely F. Samu]], [[https://openalex.org/A5075233752][Csaba Janáky]], EES Catalysis. None(None)] 2024. https://doi.org/10.1039/d3ey00222e  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ey/d3ey00222e][pdf]])
     
Photoelectrodes with FTO/Au/Sb2Se3/TiO2/Au architecture were studied in the photoelectrochemical CO2 reduction reaction (PEC CO2RR). The preparation is based on a simple spin-coating technique, where nanorod-like structures were obtained for Sb2Se3,...    

    

** Progress in design and preparation of multi-atom catalysts for photocatalytic CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40843-023-2698-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391035964"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391035964"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391035964"))][Get cited by]]

OpenAlex: https://openalex.org/W4391035964 (Open access: True)
    
[[https://openalex.org/A5034762794][Zhonghao Wang]], [[https://openalex.org/A5078365590][Guojun Zou]], [[https://openalex.org/A5017792494][Jae Hyung Park]], [[https://openalex.org/A5072000825][Kan Zhang]], Science China Materials. None(None)] 2024. https://doi.org/10.1007/s40843-023-2698-5  ([[https://link.springer.com/content/pdf/10.1007/s40843-023-2698-5.pdf][pdf]])
     
Photocatalytic CO2 reduction towards various fuels is of significant interest under the background of mitigating the global warming induced by CO2 emission and lowering the depletion of fossil fuels. However, state-of-the-art photocatalysts still suffer from sluggish reaction dynamics and frustrated product selectivity, especially for C2+ generations, which are of great interest for industrial applications. Over the past decades, comprehensive research on solar-driven CO2 reduction has consistently unveiled some encouraging results in meaningful pathways and architectural design of active sites over photocatalysts. This review highlights the recent advances in boosting photocatalytic CO2 reduction of atomically dispersed catalysts via engineered active sites, including two separated active sites, paired dual-active sites, and nanoclusters based on the configuration of active sites. Both the mechanism of CO2 activation over active sites and advanced characterization methods are discussed in detail. Particularly, in consideration of the wide gap between fundamental research and practical applications, the integrations of experimental and theoretical results are analyzed to realize the underlying structure-activity relationships as well as promising selectivity toward target products. Finally, the remaining challenges in the field are outlined, and inquisitive perspectives with a focus on the rational design of active sites and mechanistic investigation are proposed.    

    

** Boosting effect of encapsulated polyoxometalates in the photocatalytic CO2 reduction activity of MOF-545   
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391010819"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391010819"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391010819"))][Get cited by]]

OpenAlex: https://openalex.org/W4391010819 (Open access: False)
    
[[https://openalex.org/A5007162321][Khouloud Talbi]], [[https://openalex.org/A5088937428][Amanda L. Robinson]], [[https://openalex.org/A5025771580][Youven Benseghir]], [[https://openalex.org/A5024792637][María Gómez-Mingot]], [[https://openalex.org/A5062221634][Marc Fontecave]], [[https://openalex.org/A5039753949][Pierre Mialane]], [[https://openalex.org/A5032549164][Caroline Mellot‐Draznieks]], [[https://openalex.org/A5064073246][Anne Dolbecq]], No host. None(None)] 2023. None 
     
No abstract    

    

** Surfactant-free 2D/2D Pd/g-C3N4 for enhanced photocatalytic CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cy01623d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390760438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390760438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390760438"))][Get cited by]]

OpenAlex: https://openalex.org/W4390760438 (Open access: False)
    
[[https://openalex.org/A5023679657][Zhijun Huang]], [[https://openalex.org/A5075877965][Jie Wang]], [[https://openalex.org/A5009841454][Chunliang Yang]], [[https://openalex.org/A5008434514][Fengqin Yan]], [[https://openalex.org/A5052701690][Guoqing Yuan]], No host. None(None)] 2023. https://doi.org/10.1039/d3cy01623d 
     
Two-dimensional (2D) photocatalysts loaded with metal nanosheets, posessing enhanced charge transfer efficiency between the large 2D/2D interfaces, exhibit unprecedented advantages in photocatalysis. However, the inhibitory influence of surfactants on catalysis...    

    

** Reasonable design pentamerous artificial photosynthesis system for efficient overall CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148656")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390674665"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390674665"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390674665"))][Get cited by]]

OpenAlex: https://openalex.org/W4390674665 (Open access: False)
    
[[https://openalex.org/A5037308715][Chen Qiao]], [[https://openalex.org/A5080102032][Hao Wang]], [[https://openalex.org/A5043473206][Mingzheng Gu]], [[https://openalex.org/A5037272101][Xiaojun Zhang]], [[https://openalex.org/A5041561377][Guangfeng Wang]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.148656 
     
Inspired by the photosynthesis of green plants in nature, an artificial photosynthesis system of MF/Co-BWO/CPB-Cu with “root”, “trunk” and “leaf” is designed in this study, realizing efficient overall photocatalytic CO2 reduction reaction (CO2RR). Melamine foam (MF) with strong hydrophilicity and abundant porosity is selected as “root” and “trunk”, which can store and transfer liquid H2O. For the “leaf” design, Bi2WO6 and CsPbBr3 are selected as oxidation and reduction photocatalysts, respectively, which would generate Bi2WO6/CsPbBr3 S-scheme heterojunction. CuS and CoO as reduction and oxidation centers are also introduced into photosynthesis system, respectively. CuS plays an important role in CO2 adsorption and activation, while CoO could promote H2O oxidation and supply proton. Moreover, Co-BWO/CPB-Cu as “leaf” could trigger the “transpiration” from MF via photo-thermal effect, inducing the formation of gas–solid biphase CO2RR system. As a result, the artificial photosynthesis system of MF/Co-BWO/CPB-Cu exhibits the efficient CO2RR efficiency.    

    

** Adsorption and activation, active site and reaction pathway of photocatalytic CO2 reduction: A review   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148754")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390858622"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390858622"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390858622"))][Get cited by]]

OpenAlex: https://openalex.org/W4390858622 (Open access: False)
    
[[https://openalex.org/A5039768705][Yong‐Xing He]], [[https://openalex.org/A5072741411][Lin Yin]], [[https://openalex.org/A5085683068][Nanci Yuan]], [[https://openalex.org/A5091370242][Gaoke Zhang]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.148754 
     
Photocatalytic CO2 reduction (PCR) technology is one of the potential strategies to mitigate the greenhouse effect, solve the energy crisis and achieve goals of carbon dioxide emissions peak and carbon neutrality. However, it is extremely difficult to adsorb and activate CO2 due to the high dissociation energy of C = O bond in CO2 molecule (750 kJ·mol−1), resulting in poor performance of PCR. In addition, in the heterogeneous reaction process, adsorbing and activating CO2 are closely related to the active sites on the surface of photocatalyst. Therefore, in-depth and detailed exploration of the adsorption and activation of CO2 on active sites is critical to developing high-performance photocatalysts. Herein, this review firstly explores adsorption modes of CO2 on the active sites of photocatalyst, including physisorption and chemisorption, where chemisorption includes oxygen, carbon and mixed adsorption. Secondly, reaction pathways for the formation of different high value-added chemical products are introduced, including formaldehyde, carbene, glyoxal and mixed pathways. Then, strategies for enhancing the adsorption and activation of CO2 are briefly summarized. Finally, the future prospects and challenges of PCR development are discussed. This work provides insights and references for further designing photocatalysts that can enhance the adsorption and activation of CO2 and improve the performance of PCR.    

    

** MAPbBr3/Bi2WO6 Z-scheme-heterojunction photocatalysts for photocatalytic CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10853-023-09220-w")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390813250"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390813250"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390813250"))][Get cited by]]

OpenAlex: https://openalex.org/W4390813250 (Open access: False)
    
[[https://openalex.org/A5045398749][Yawen Zhang]], [[https://openalex.org/A5059820183][Njemuwa Nwaji]], [[https://openalex.org/A5019581469][Longmin Wu]], [[https://openalex.org/A5090982721][Mingliang Jin]], [[https://openalex.org/A5006337656][Lemma Teshome Tufa]], [[https://openalex.org/A5064263084][Guofu Zhou]], [[https://openalex.org/A5056628685][Michael Giersig]], [[https://openalex.org/A5006822602][Xin Wang]], [[https://openalex.org/A5035571884][Tengfei Qiu]], [[https://openalex.org/A5019038885][Eser Metin Akinoglu]], Journal of Materials Science. None(None)] 2024. https://doi.org/10.1007/s10853-023-09220-w 
     
No abstract    

    

** Recent advances in single crystal and facet dependency of copper electrodes on electrochemical CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.coche.2023.100999")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390684607"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390684607"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390684607"))][Get cited by]]

OpenAlex: https://openalex.org/W4390684607 (Open access: True)
    
[[https://openalex.org/A5083596784][Yu Qiao]], [[https://openalex.org/A5082009908][Brian Seger]], Current Opinion in Chemical Engineering. 43(None)] 2024. https://doi.org/10.1016/j.coche.2023.100999 
     
Investigations on electrochemical CO2 reduction reaction (eCO2RR) on copper (Cu) provide instructive information for the understanding and development of Cu-based catalysts and thus help improve their eCO2RR selectivity toward desired products. Although most studies on the reaction mechanism rely on computational simulations, experiments conducted on well-defined single-crystal structures are able to effectively mirror the ideal surfaces employed in simulation studies and thus convey insightful knowledge on the structure–performance correlation of Cu catalysts in eCO2RR. This mini-review provides an overview on state-of-the-art development of Cu single crystals and their facet dependency in eCO2RR in the recent years, followed by an outlook and perspective on what can be expected in the future.    

    

** Electrocatalytic activity of CO2 reduction to CO on cadmium sulfide enhanced by chloride anion doping   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202303422")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391034523"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391034523"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391034523"))][Get cited by]]

OpenAlex: https://openalex.org/W4391034523 (Open access: False)
    
[[https://openalex.org/A5076156463][Mingyan Wang]], [[https://openalex.org/A5090306043][Weiqi Cao]], [[https://openalex.org/A5000696036][Jingkun Yu]], [[https://openalex.org/A5043126719][Dexin Yang]], [[https://openalex.org/A5080528733][Kongsheng Qi]], [[https://openalex.org/A5082445301][Yang Zhao]], [[https://openalex.org/A5088438669][Zhixin Hua]], [[https://openalex.org/A5087742625][Hongping Li]], [[https://openalex.org/A5085836074][Siyu Lu]], No host. None(None)] 2024. https://doi.org/10.1002/chem.202303422 
     
The electrocatalytic CO2 reduction (ECR) to produce valuable fuel is a promising process for addressing atmospheric CO2 emissions and energy shortages. In this study, Cl‐anion doped cadmium sulfide structures were directly fabricated on a nickel foam surface (Cl/CdS‐NF) using an in situ hydrothermal method. The Cl‐anion doping could significantly improve ECR activity for CO production in ionic liquid and acetonitrile mixed solution, compared to pristine CdS. The highest Faradaic efficiency of CO is 98.1% on a Cl/CdS‐NF‐2 cathode with an excellent current density of 137.0 mA cm−2 at −2.25 V versus ferrocene/ferrocenium (Fc/Fc+, all potentials are versus Fc/Fc+ in this study). In particular, CO Faradaic efficiencies remained above 80% in a wide potential range of −2.05 V to −2.45 V and a maximum partial current density (192.6 mA cm−2) was achieved at −2.35 V. The Cl/CdS‐NF‐2, with appropriate Cl anions, displayed abundant active sites and a suitable electronic structure, resulting in outstanding ECR activity. Density functional theory calculations further demonstrated that Cl/CdS is beneficial for increasing the adsorption capacities of *COOH and *H, which can enhance the activity of the ECR toward CO and suppress the hydrogen evolution reaction.    

    

** Facile Construction of Metal–Organic Framework/Topological Insulator Heterostructure for Photothermal Catalytic CO2 Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3tc04332k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390685478"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390685478"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390685478"))][Get cited by]]

OpenAlex: https://openalex.org/W4390685478 (Open access: False)
    
[[https://openalex.org/A5071478549][Jing Sun]], [[https://openalex.org/A5000856133][Xunfeng Yuan]], [[https://openalex.org/A5061735109][Baoying Liu]], [[https://openalex.org/A5068927949][Songde Ma]], [[https://openalex.org/A5037037793][Chengfang Qiao]], Journal of Materials Chemistry C. None(None)] 2024. https://doi.org/10.1039/d3tc04332k 
     
Photothermal catalytic CO2 reduction, which combines the advantages of photocatalysis and photothermal effect, has emerged as one of the most promising strategies to meet the global energy crisis and excessive...    

    

** Studying the cation dependence of CO2 reduction intermediates at Cu by in-situ VSFG spectroscopy   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3sc05295h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390946111"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390946111"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390946111"))][Get cited by]]

OpenAlex: https://openalex.org/W4390946111 (Open access: True)
    
[[https://openalex.org/A5067148398][Liam Banerji]], [[https://openalex.org/A5070399861][Hansaem Jang]], [[https://openalex.org/A5007746313][Adrian M. Gardner]], [[https://openalex.org/A5081021911][Alexander J. Cowan]], Chemical Science. None(None)] 2024. https://doi.org/10.1039/d3sc05295h  ([[https://pubs.rsc.org/en/content/articlepdf/2024/sc/d3sc05295h][pdf]])
     
The nature of the electrolyte cation is known to have a significant impact on electrochemical reduction of CO 2 at catalyst|electrolyte interfaces. An understanding of the underlying mechanism responsible for catalytic...    

    

** Challenges and opportunities of atomic-scales reactive sites in thriving electrochemical CO2 reduction reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nantod.2024.102152")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390848392"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390848392"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390848392"))][Get cited by]]

OpenAlex: https://openalex.org/W4390848392 (Open access: False)
    
[[https://openalex.org/A5011857784][Pengliang Sun]], [[https://openalex.org/A5010032339][Sailin Liu]], [[https://openalex.org/A5028108437][Xiong Zheng]], [[https://openalex.org/A5053355651][Guangzhi Hu]], [[https://openalex.org/A5022142811][Qingran Zhang]], [[https://openalex.org/A5068156145][Xinchao Liu]], [[https://openalex.org/A5039966691][Guoxiang Zheng]], [[https://openalex.org/A5028931040][Yinguang Chen]], Nano Today. 55(None)] 2024. https://doi.org/10.1016/j.nantod.2024.102152 
     
Electrochemical carbon dioxide reduction reaction (ECO2RR) converts CO2 into value-added chemicals or fuels to realize carbon recycling as means to solve the problems of renewable energy shortage and environmental pollution. The development of cost-effective CO2RR catalysts with high activity, stability and selectivity is the key that enables efficient conversion from CO2 to valuable products. It is also important to understand intrinsic mechanisms of the underlying active-site that affect the performances of catalysts, which can, in turn, facilitate the rational design of more active electrocatalysts. In this context, it is particularly important to understand the structure-activity relationship of catalyst active sites during the CO2RR process from different atomic-scales, which inspires to organize this review. Specifically, we focus on the atomic-level construction of active sites from single atoms, dual-site metal, clusters, or/and graphitic carbon materials: key approaches for tailoring coordination configurations to enhance target product selectivity, i.e., optimizing the interplay between the catalytic active center and reactants or intermediates, disrupting the linear correlation of intermediate adsorption energies, and promoting intricate cascading reactions involving multiple intermediates. Highlight the intricate correlation between the structure-activity of CO2RR catalysts, which govern the discerning refinement of catalysts and propel advances in their practical application. Then, the electrocatalytic reactors for ECO2R reactions are critically reviewed. The acquisition of key metrics, the challenges faced, and the most suitable solutions for electrocatalytic CO2RR are proposed. Finally, future research directions and strategies are anticipated to inspire revolutionary advancements.    

    

** Controllable Preparation of Cu2o/Cu-Cutcpp Mof Heterojunction for Enhanced Electrocatalytic Co2 Reduction to C2h4   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4696662")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390910665"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390910665"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390910665"))][Get cited by]]

OpenAlex: https://openalex.org/W4390910665 (Open access: False)
    
[[https://openalex.org/A5040875463][Mingming Sun]], [[https://openalex.org/A5001713310][Xin Xu]], [[https://openalex.org/A5023534256][Shihao Min]], [[https://openalex.org/A5041722972][Jie He]], [[https://openalex.org/A5061431843][K. Li]], [[https://openalex.org/A5046241877][Longtian Kang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4696662 
     
Copper-based metal-organic framework (Cu-MOF) materials with multiple active sites have attracted increasing attention to the electrocatalytic CO2 reduction reaction (ECR), however, face the huge challenge owing to the poor stability and low C2 selectivity. Here, the Cu2O/Cu-CuTCPP heterojunction (Cu2O/CPFs) with three Cu active sites are firstly constructed through in-situ electrodeposition method. The effect of CuSO4 concentration and electrodeposition conditions on ECR is systematically investigated. The optimized Cu2O/CPFs composite achieves the ethylene Faraday efficiency (FEC2H4) of 61.8% at –1.3 V vs. RHE, which is 1.9 and 3.42 times higher than those of CPFs and Cu2O, respectively. Meanwhile, the C2H4 partial current density (jC2H4) of –7.96 mA·cm-2 is 2.91 and 4.68 times higher than those of CPFs and Cu2O. Further experiments reveals that the formation of Cu2+–O–Cu+–O bond between Cu2O and Cu–O4 sites in Cu2O/CPF heterojunction is crucial. Consequently, the hydrogen (H2), formic acid (HCOOH) and methane (CH4) evolution reactions are restricted, the C–C coupling reaction of *CHO and *CO intermediates is significantly enhanced, and the Cu–O4 sites in CPFs are protected. This work provides an effective strategy to stabilize MOF structure and obtain high value-added C2+ products.    

    

** Rich oxygen vacancies in confined heterostructured TiO2@In2S3 hybrid for boosting solar-driven CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.086")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391007154"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391007154"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391007154"))][Get cited by]]

OpenAlex: https://openalex.org/W4391007154 (Open access: False)
    
[[https://openalex.org/A5005436632][Feifei You]], [[https://openalex.org/A5071497962][Tianhao Zhou]], [[https://openalex.org/A5017061461][Jiaxin Li]], [[https://openalex.org/A5053355958][Siqi Huang]], [[https://openalex.org/A5025752853][Chuntao Chang]], [[https://openalex.org/A5086743235][Xiaoyu Fan]], [[https://openalex.org/A5049341927][Hao Zhang]], [[https://openalex.org/A5043956105][Xinbin Ma]], [[https://openalex.org/A5055623679][Dawei Gao]], [[https://openalex.org/A5082699212][Jian Qi]], [[https://openalex.org/A5085296684][Danyang Li]], Journal of Colloid and Interface Science. 660(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.086 
     
Solar energy driving CO2 reduction is a potential strategy that not only mitigates the greenhouse effect caused by high CO2 level in atmosphere, but also yields carbon chemicals/fuels at the same time. Herein, a facile way to design the heterogeneous TiO2@In2S3 hollow structures possessing robust light harvesting in both ultraviolet and visible regions is proposed and exhibits a higher generation rate of 25.35 and 1.24 μmol·g−1·h−1 for photocatalytic CO2 reduction to CO and CH4, respectively. The excellent photocatalytic catalytic performance comes from i) the confined heterostructured TiO2@In2S3 possesses a suitable band structure and a broadband-light absorbing capacity for CO2 photoreduction, ii) the rich interfaces between nanosized TiO2 and In2S3 on the shell can significantly reduce the diffusion length of carriers and enhance the utilization efficiency of photogenerated electron-hole pairs, and iii) enriched surface oxygen vacancies can provide more active sites for CO2 adsorption.    

    

** Facile synthesis of self-nitrogen-doped carbon spheres for high-efficient photocatalytic CO2 reduction to CO   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.135887")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390651239"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390651239"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390651239"))][Get cited by]]

OpenAlex: https://openalex.org/W4390651239 (Open access: False)
    
[[https://openalex.org/A5067808391][Zhiyan Dong]], [[https://openalex.org/A5022950764][Yudong Wang]], [[https://openalex.org/A5082266931][Xiaochao Zhang]], [[https://openalex.org/A5002509420][Xiushuai Guan]], [[https://openalex.org/A5006960343][Changming Zhang]], [[https://openalex.org/A5061069727][Wensheng Wu]], [[https://openalex.org/A5051941911][Caimei Fan]], Materials Letters. None(None)] 2024. https://doi.org/10.1016/j.matlet.2024.135887 
     
In this work, self-nitrogen-doped carbon microsphere photocatalysts were prepared by hydrothermal and carbonation pyrolysis with first application in photocatalytic CO2 reduction. Coupled with relevant characterization, nitrogen-doped carbon microspheres were successfully prepared and the introduction of nitrogen significantly improved the photogenerated charge separation efficiency and CO2 photoreduction to CO activity, leading to the highest photocatalytic reduction activity with a CO yield of 185.71 μmol g−1 (9 h) under simulated sunlight irradiation. More importantly, its performance remains at about 98 % after ten consecutive cycle tests, indicating the excellent active stability of self-nitrogen-doped carbon spheres. Possible mechanisms for photocatalytic reduction and the role of nitrogen in photocatalytic adsorption and reduction processes are analyzed and proposed. The research provides novel strategies for the design of bifunctional catalysts that offer robust adsorption and efficient reduction, enabling the sustainable conversion of CO2.    

    

** Facilely Tunable Dodecahedral POM Framework Loaded with Mono- or Bimetallic Sites for Efficient Photocatalytic CO2 Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.123733")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390858455"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390858455"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390858455"))][Get cited by]]

OpenAlex: https://openalex.org/W4390858455 (Open access: False)
    
[[https://openalex.org/A5087343432][Bonan Li]], [[https://openalex.org/A5076156197][Mengxue Chen]], [[https://openalex.org/A5051874318][Qiyu Hu]], [[https://openalex.org/A5084324182][Jiaqi Zhu]], [[https://openalex.org/A5055313658][Xu Yang]], [[https://openalex.org/A5010201433][Zijing Li]], [[https://openalex.org/A5080592339][Chunlian Hu]], [[https://openalex.org/A5015145045][Yuanyuan Li]], [[https://openalex.org/A5077347142][Peihong Ni]], [[https://openalex.org/A5074556294][Yong Ding]], Applied Catalysis B: Environmental. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.123733 
     
Utilizing solar energy to drive the conversion of CO2 into high-value chemicals emerged as a promising approach to decrease CO2 emission. Yolk-shell or hollow structure have drawn much attention for photocatalytic CO2 reduction, owing to their efficient CO2 trapping and more active sites exposing. In this study, we employed a simple method to regulate the morphological evolution of K3PW12O40 dodecahedra. After annealing, mono-/bimetallic active species are homogeneously dispersed on K3PW12O40 framework forming PW12@Co and PW12@CoNi, which exhibit good CO production rates of 11.2 and 15.1 μmol/h, respectively, with selectivity of 90.7% and 92.6%. The differences in the activity and selectivity of CO2RR are attributed to the morphology variations of POM and the influence of mono-/bimetallic species. These results are confirmed through the analysis of SEM, TEM, N2 and CO2 adsorption/desorption, PL, EIS and SPV characterizations. In-situ DRIFTS and DFT provide further support for the formation and transformation of intermediate products.    

    

** Co-immobilization of a Rh catalyst and a Keggin polyoxometalate in the UiO-67 metal-organic framework: photocatalytic properties for CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391010815"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391010815"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391010815"))][Get cited by]]

OpenAlex: https://openalex.org/W4391010815 (Open access: False)
    
[[https://openalex.org/A5025771580][Youven Benseghir]], [[https://openalex.org/A5086372340][Albert Solé-Daurá]], [[https://openalex.org/A5085164470][Mathis Duguet]], [[https://openalex.org/A5039753949][Pierre Mialane]], [[https://openalex.org/A5024792637][María Gómez-Mingot]], [[https://openalex.org/A5062221634][Marc Fontecave]], [[https://openalex.org/A5064073246][Anne Dolbecq]], [[https://openalex.org/A5032549164][Caroline Mellot‐Draznieks]], No host. None(None)] 2021. None 
     
No abstract    

    

** Binary Junctions Enhance Electron Storage and Potential Difference for Photo-Assisted Electrocatalytic Co2 Reduction to Hcooh   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4689861")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390696832"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390696832"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390696832"))][Get cited by]]

OpenAlex: https://openalex.org/W4390696832 (Open access: False)
    
[[https://openalex.org/A5024964837][Yingnan Cao]], [[https://openalex.org/A5062755510][Qianqian Wang]], [[https://openalex.org/A5026275424][Yunni Liu]], [[https://openalex.org/A5000187214][Ying Tao]], [[https://openalex.org/A5011581422][Jinchen Fan]], [[https://openalex.org/A5065482772][Ming Chen]], [[https://openalex.org/A5082278440][Dieqing Zhang]], [[https://openalex.org/A5082278440][Dieqing Zhang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4689861 
     
Photo-assisted electrocatalytic (PAEC) CO2 conversion is a crucial approach for achieving sustainable carbon neutrality. Here, we have developed a binary-junctions photoanode by integrating SrTiO3 and anatase-rutile TiO2 nanotube arrays (STO/A-R TNTAs), which exhibits exceptional activity and selectivity in converting CO2 to HCOOH. The synergetic effects of the SrTiO3/TiO2 heterogeneous junction and the anatase-rutile TiO2 heterophase junction effectively facilitate photoelectron separation and storage, leading to a potential difference between anode and cathode. The establishment of the electron storage strategy, triggered by hetero- junction/phase interfaces, serves as remarkably efficient electron trapping regions with dam-like characteristics. As a result, the STO/A-R TNTAs achieves a generation rate of 68.24 μmol cm-2 h-1 with 92.25% selectivity and 90.70% Faradic efficiency. This performance is approximately 8 times higher compared to the pristine TiO2 nanotube arrays photoanode. The implementation of the electron storage mechanism presents a promising approach to improve CO2 reduction activity and selectivity.    

    

** Auto-Tandem Co2 Reduction by Reconstructed Cu Imidazole Framework Isomers: Unveiling Pristine Mof-Mediated Co2 Activation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4690201")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390695033"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390695033"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390695033"))][Get cited by]]

OpenAlex: https://openalex.org/W4390695033 (Open access: False)
    
[[https://openalex.org/A5025614175][Xiang-Da Zhang]], [[https://openalex.org/A5036914815][Jian-Mei Huang]], [[https://openalex.org/A5024839012][Xiaorong Zhu]], [[https://openalex.org/A5022256556][Chang Liu]], [[https://openalex.org/A5068336878][Yue Yin]], [[https://openalex.org/A5067239284][Jiayi Huang]], [[https://openalex.org/A5082041084][Ming Xu]], [[https://openalex.org/A5076118607][Yafei Li]], [[https://openalex.org/A5001990602][Zhi‐Yuan Gu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4690201 
     
Cu-based metal-organic frameworks (MOFs) are widely employed in CO2 reduction reactions (CO2RR) because of their unique advantages to convert CO2 into C2+ products. Mostly, Cu-based MOFs are in-situ reconstructed to Cu-based derivatives such as Cu or Cu oxides during CO2RR, which is regarded as the catalytic active center. However, the key role of pristine MOFs and the coordination environment is often ignored in the process of revealing the catalytic mechanism. Here, we propose an auto-tandem mechanism for in-situ reconstructed Cu imidazole framework isomers, namely CuN2 and Cu2N4. During the auto-tandem catalysis process, pristine Cu(imidazole) served to convert CO2 into CO, while the Cu-based derivatives, in this case, Cu(111) sequentially convert the CO to C2+ products. This auto-tandem catalytic mechanism is supported by electrocatalytic performance, TPD-CO, HRTEM, SAED, XPS, in-situ XANES and XES. Besides, in-situ ATR-SEIRAS and DFT computation illustrate that the coordination environment of pristine Cu(imidazole) affects the selectivity of CO and thus determines the selectivity of C2+ products. The auto-tandem catalytic mechanism provides a new route to design Cu-based MOF electrocatalysts for high product selectivity in CO2RR.    

    

** In situ constructed B-CdS/Cd Schottky junctions for efficient photocatalytic CO2 reduction under visible light   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.103926")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987589"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987589"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987589"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987589 (Open access: False)
    
[[https://openalex.org/A5059273355][R. Li]], [[https://openalex.org/A5024123604][Zhenhua Dai]], [[https://openalex.org/A5049119185][Tim Hui-Ming Huang]], [[https://openalex.org/A5019858998][Qianqian Zhang]], [[https://openalex.org/A5002474804][Xunfu Zhou]], [[https://openalex.org/A5060946876][Zhongli Peng]], [[https://openalex.org/A5010021609][Zuotao Liu]], [[https://openalex.org/A5076015543][Yueping Fang]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.103926 
     
CdS with a visible light response and energy band location suitable for CO2 photoreduction has received extensive attention. However, low product selectivity and photocatalytic efficiency limit its application. Here, NaBH4 is used as a reducing agent to generate Cd metal on the surface of CdS nanorods in situ. This leads to the construction of a B-CdS/Cd metal cocatalyst/semiconductor structure. This configuration significantly enhanced the CdS's activity of photocatalytic CO2 reduction. The Cd metal which is on the surface of CdS nanorods promoted the separation and transfer of photogenerated charges and increased both light photosensitivity and CO2 adsorption capabilities. The improved B-CdS/Cd catalyst shows excellent CO2 reduction capabilities by generating CO at a rate of 323.39 μmol g−1 h−1, which is 2.01 times more than pure CdS, owing to the synergistic enhancements. Simultaneously, Cd acts as an active site inhibiting H2 production during the CO2 reduction reaction. This work demonstrates the potential of Cd metal as a metal cocatalyst in photocatalytic CO2 reduction.    

    
