#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Thu Jul 18 01:09:51 2024

Found 77 results from 2024-07-11 to 2024-07-18
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Back Cover Picture: Light‐Induced Dynamic Activation of Copper/Silicon Interface for Highly Selective Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400540527
:TOPICS: Wearable Nanogenerator Technology, Nanotechnology and Imaging for Cancer Therapy and Diagnosis, Nanowire Nanosensors for Biomedical and Energy Applications
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202412574")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400540527"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400540527"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400540527"))][Get cited by]]

OpenAlex: https://openalex.org/W4400540527 (Open access: False)
    
[[https://openalex.org/A5100417456][Jiali Wang]], [[https://openalex.org/A5104348270][Tai Ying Lai]], [[https://openalex.org/A5013371761][Han‐Ting Lin]], [[https://openalex.org/A5022605666][Tsung‐Rong Kuo]], [[https://openalex.org/A5023282498][Hsiao‐Chien Chen]], [[https://openalex.org/A5048898146][Chun‐Sheng Tseng]], [[https://openalex.org/A5091339140][Ching‐Wei Tung]], [[https://openalex.org/A5064513716][Chia‐Ying Chien]], [[https://openalex.org/A5073478852][Hao Ming Chen]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/anie.202412574 
     
No abstract    

    

* Back Cover Picture: Light‐Induced Dynamic Activation of Copper/Silicon Interface for Highly Selective Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400542014
:TOPICS: Wearable Nanogenerator Technology, Nanotechnology and Imaging for Cancer Therapy and Diagnosis, Nanowire Nanosensors for Biomedical and Energy Applications
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202412574")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400542014"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400542014"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400542014"))][Get cited by]]

OpenAlex: https://openalex.org/W4400542014 (Open access: False)
    
[[https://openalex.org/A5100417456][Jiali Wang]], [[https://openalex.org/A5104348270][Tai Ying Lai]], [[https://openalex.org/A5013371761][Han‐Ting Lin]], [[https://openalex.org/A5022605666][Tsung‐Rong Kuo]], [[https://openalex.org/A5023282498][Hsiao‐Chien Chen]], [[https://openalex.org/A5048898146][Chun‐Sheng Tseng]], [[https://openalex.org/A5091339140][Ching‐Wei Tung]], [[https://openalex.org/A5064513716][Chia‐Ying Chien]], [[https://openalex.org/A5073478852][Hao Ming Chen]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202412574 
     
No abstract    

    

* Exploration of Pynaphthyridine and Binaphthyridine Manganese(I) Tricarbonyl Complexes: Influence on Carbon Dioxide Reduction Electrocatalysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400544982
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.organomet.4c00008")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400544982"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400544982"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400544982"))][Get cited by]]

OpenAlex: https://openalex.org/W4400544982 (Open access: False)
    
[[https://openalex.org/A5064529418][Kailyn Y. Cohen]], [[https://openalex.org/A5026912288][Hovnan Simonyan]], [[https://openalex.org/A5024866992][María J. Ortiz]], [[https://openalex.org/A5104348329][Benjamin F. Solomon]], [[https://openalex.org/A5103313431][Luke Simkins]], [[https://openalex.org/A5019772141][Raymond N. Dominey]], [[https://openalex.org/A5058765335][Emma W. Goldman]], [[https://openalex.org/A5019058817][Andrew B. Bocarsly]], Organometallics. None(None)] 2024. https://doi.org/10.1021/acs.organomet.4c00008 
     
No abstract    

    

* Performance evaluation of nonthermal plasma carbon dioxide reduction to fuel with dielectric barrier discharge  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400601775
:TOPICS: Applications of Plasma in Medicine and Biology, Catalytic Nanomaterials, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.elstat.2024.103952")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400601775"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400601775"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400601775"))][Get cited by]]

OpenAlex: https://openalex.org/W4400601775 (Open access: False)
    
[[https://openalex.org/A5017244937][Hiroyuki Wakimoto]], [[https://openalex.org/A5060045300][Hiroyuki Yamasaki]], [[https://openalex.org/A5090266837][Tetsuo Kuroki]], [[https://openalex.org/A5028540027][Masaaki Okubo]], Journal of electrostatics. 130(None)] 2024. https://doi.org/10.1016/j.elstat.2024.103952 
     
No abstract    

    

* CO2 reduction in strong acid  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400657511
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s44160-024-00608-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400657511"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400657511"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400657511"))][Get cited by]]

OpenAlex: https://openalex.org/W4400657511 (Open access: False)
    
[[https://openalex.org/A5017052730][Taito Watanabe]], [[https://openalex.org/A5090212607][Shigeyuki Masaoka]], Nature synthesis. None(None)] 2024. https://doi.org/10.1038/s44160-024-00608-3 
     
No abstract    

    

* Ag-Precipitated CuO Nanospheres for Enhanced Electrochemical Reduction of CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400484824
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16145888")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400484824"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400484824"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400484824"))][Get cited by]]

OpenAlex: https://openalex.org/W4400484824 (Open access: True)
    
[[https://openalex.org/A5100950501][Jinyun Xu]], [[https://openalex.org/A5103286443][Ming Li]], [[https://openalex.org/A5019322147][Liping Zhao]], [[https://openalex.org/A5100703700][Guoqiang Zhong]], [[https://openalex.org/A5100433507][Yu Zhang]], [[https://openalex.org/A5100404400][Ziqi Zhang]], [[https://openalex.org/A5002943130][Yu Sun]], [[https://openalex.org/A5049443641][Xudong Hu]], [[https://openalex.org/A5007771093][Zhé Peng]], [[https://openalex.org/A5005633149][Yicong Wang]], [[https://openalex.org/A5068536737][Chunming Zheng]], [[https://openalex.org/A5103088314][Xiaohong Sun]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16145888 
     
An electrochemical CO2 reduction reaction (CO2RR) is an effective way to reduce greenhouse gases by converting CO2 into high-value-added chemical products using electricity generated from renewable energy. In this paper, a Cu2O spherical catalyst was prepared by ascorbic acid reduction. The precipitated Cu-Ag spherical catalyst (P-CuO-Ag) was successfully prepared by calcining Cu2O-Ag with the introduction of an Ag component as the substrate. During the electrochemical reduction of CO2, the FE of the P-CuO-Ag catalyst for C2H4 at a potential of −1.1 V vs. RHE was as high as 39.8%, which was nearly twice that of the CuO catalyst, while the local current density JC2H4 for C2H4 reached 6 mA cm−2. The incorporation of Ag gives the spherical CuO catalyst higher electrochemical activity and better kinetic performance than the catalyst without Ag.    

    

* Cleaner separation and recovery of valuable metals from spent ternary cathode via carbon dioxide synergetic thermite reduction strategy  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400673266
:TOPICS: Battery Recycling and Rare Earth Recovery, Global E-Waste Recycling and Management, Biohydrometallurgical Processes for Metal Extraction
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jenvman.2024.121853")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400673266"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400673266"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400673266"))][Get cited by]]

OpenAlex: https://openalex.org/W4400673266 (Open access: False)
    
[[https://openalex.org/A5028299718][Cheng Yang]], [[https://openalex.org/A5100417363][Qiong Wang]], [[https://openalex.org/A5101443699][Liang Xu]], [[https://openalex.org/A5018147854][Yongpan Tian]], [[https://openalex.org/A5009441078][Zhuo Zhao]], Journal of environmental management. 366(None)] 2024. https://doi.org/10.1016/j.jenvman.2024.121853 
     
No abstract    

    

* Distinct CO2-run-out regime from steric effect of electric double layer in electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400654483
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0214255")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400654483"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400654483"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400654483"))][Get cited by]]

OpenAlex: https://openalex.org/W4400654483 (Open access: False)
    
[[https://openalex.org/A5069978822][Longfei Chen]], [[https://openalex.org/A5075996632][Hao Feng]], [[https://openalex.org/A5059811239][Ying Zhang]], [[https://openalex.org/A5076270970][Dong Liu]], [[https://openalex.org/A5100429972][Qiang Li]], Applied physics reviews. 11(3)] 2024. https://doi.org/10.1063/5.0214255 
     
The field of electrochemical CO2 reduction reaction (eCO2RR) is pursuing high operating current densities, eventually controlled by CO2 transport. Here, we develop a new multiscale modeling approach that is able to more generally describe the effects of the electric double layer (EDL) on CO2 transport over a wide potential window extending to utmost potentials. By leveraging it, we identify a distinct CO2-run-out regime where the supply of CO2 runs out due to the EDL steric effect from a dense layer of solvated cations with the maximum layer thickness equal to the solvated cation size. Consequently, CO2RR current density drops at a relatively negative transition potential generating a bell-shaped polarization curve, which is in contrast to the CO2-transport-limited regime where the current density reaches a plateau. Furthermore, we develop a graphical method, verified by experimental data, to generally predict the transition to the CO2-run-out regime. This work sheds new light on the EDL effects for catalyst design and electrolyzer engineering.    

    

* Electrochemical CO2 Reduction to Multicarbon Products on Non‐Copper Based Catalysts  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400509915
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401173")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400509915"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400509915"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400509915"))][Get cited by]]

OpenAlex: https://openalex.org/W4400509915 (Open access: False)
    
[[https://openalex.org/A5103129596][Jiayi Huang]], [[https://openalex.org/A5059204360][Qianwen Liu]], [[https://openalex.org/A5014993071][Jianmei Huang]], [[https://openalex.org/A5082041084][Ming Xu]], [[https://openalex.org/A5003323354][Wenchuan Lai]], [[https://openalex.org/A5001990602][Zhi‐Yuan Gu]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401173 
     
Electrochemical CO2 reduction reaction (eCO2RR) to value‐added multicarbon (C2+) products offers a promising approach for achieving carbon neutrality and storing intermittent renewable energy. Copper (Cu)‐based electrocatalysts generally play the predominant role in this process. Yet recently, more and more non‐Cu materials have demonstrated the capability to convert CO2 into C2+, which provides impressive production efficiency even exceeding those on Cu, and a wider variety of C2+ compounds not achievable with Cu counterparts. This motivates us to organize the present review to make a timely and tutorial summary of recent progresses on developing non‐Cu based catalysts for CO2‐to‐C2+. We begin by elucidating the reaction pathways for C2+ formation, with an emphasis on the unique C‐C coupling mechanisms in non‐Cu electrocatalysts. Subsequently, we summarize the typical C2+‐involved non‐Cu catalysts, including ds‐, d‐ and p‐block metals, as well as metal‐free materials, presenting the state‐of‐the‐art design strategies to enhance C2+ efficiency. The system upgrading to promote C2+ productivity on non‐Cu electrodes covering microbial electrosynthesis, electrolyte engineering, regulation of operational conditions, and synergistic co‐electrolysis, is highlighted as well. Our review concludes with an exploration of the challenges and future opportunities in this rapidly evolving field.    

    

* Contact-electro-catalytic CO2 reduction from ambient air  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400601546
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Materials for Electrochemical Supercapacitors, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-50118-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400601546"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400601546"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400601546"))][Get cited by]]

OpenAlex: https://openalex.org/W4400601546 (Open access: True)
    
[[https://openalex.org/A5100774865][Nannan Wang]], [[https://openalex.org/A5101900433][Wenbin Jiang]], [[https://openalex.org/A5067721654][Jing Yang]], [[https://openalex.org/A5038092047][Haisong Feng]], [[https://openalex.org/A5021519126][Youbin Zheng]], [[https://openalex.org/A5100371237][Sheng Wang]], [[https://openalex.org/A5052500444][Bofan Li]], [[https://openalex.org/A5034966598][Jerry Zhi Xiong Heng]], [[https://openalex.org/A5069044440][Wai Chung Ong]], [[https://openalex.org/A5101899474][Hui Ru Tan]], [[https://openalex.org/A5100675809][Yong‐Wei Zhang]], [[https://openalex.org/A5028276045][Daoai Wang]], [[https://openalex.org/A5019225060][Enyi Ye]], [[https://openalex.org/A5100727338][Yupeng Liu]], Nature communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-50118-1 
     
Abstract Traditional catalytic techniques often encounter obstacles in the search for sustainable solutions for converting CO 2 into value-added products because of their high energy consumption and expensive catalysts. Here, we introduce a contact-electro-catalysis approach for CO 2 reduction reaction, achieving a CO Faradaic efficiency of 96.24%. The contact-electro-catalysis is driven by a triboelectric nanogenerator consisting of electrospun polyvinylidene fluoride loaded with single Cu atoms-anchored polymeric carbon nitride (Cu-PCN) catalysts and quaternized cellulose nanofibers (CNF). Mechanistic investigation reveals that the single Cu atoms on Cu-PCN can effectively enrich electrons during contact electrification, facilitating electron transfer upon their contact with CO 2 adsorbed on quaternized CNF. Furthermore, the strong adsorption of CO 2 on quaternized CNF allows efficient CO 2 capture at low concentrations, thus enabling the CO 2 reduction reaction in the ambient air. Compared to the state-of-the-art air-based CO 2 reduction technologies, contact-electro-catalysis achieves a superior CO yield of 33 μmol g −1 h −1 . This technique provides a solution for reducing airborne CO 2 emissions while advancing chemical sustainability strategy.    

    

* Assessing the Impacts of CO2 Reduction and Utilization Technologies on Regional Freshwater Resources  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400597659
:TOPICS: Geological Evolution of the Arctic Region, Coastal Hydrophysical Processes in Shallow Water Basins, Integrated Management of Water, Energy, and Food Resources
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2172/2396748")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400597659"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400597659"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400597659"))][Get cited by]]

OpenAlex: https://openalex.org/W4400597659 (Open access: False)
    
[[https://openalex.org/A5032802547][May Wu]], [[https://openalex.org/A5008786958][Hannah Kim]], No host. None(None)] 2024. https://doi.org/10.2172/2396748 
     
No abstract    

    

* CO2 electrochemical reduction: a state-of-the-art review with economic and environmental analyses  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400612469
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cherd.2024.07.014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400612469"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400612469"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400612469"))][Get cited by]]

OpenAlex: https://openalex.org/W4400612469 (Open access: True)
    
[[https://openalex.org/A5023097254][Grazia Leonzio]], [[https://openalex.org/A5053545382][G. H. Kelsall]], [[https://openalex.org/A5078158219][Nilay Shah]], Process safety and environmental protection/Transactions of the Institution of Chemical Engineers. Part B, Process safety and environmental protection/Chemical engineering research and design/Chemical engineering research & design. None(None)] 2024. https://doi.org/10.1016/j.cherd.2024.07.014 
     
No abstract    

    

* Effect of crystal defects on the electrocatalytic CO2 reduction performance of pure copper  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400496350
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Thermoelectric Materials
:PUBLICATION_DATE: 2024-11-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.scriptamat.2024.116268")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400496350"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400496350"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400496350"))][Get cited by]]

OpenAlex: https://openalex.org/W4400496350 (Open access: False)
    
[[https://openalex.org/A5009715982][Shuai Hao]], [[https://openalex.org/A5089538318][Kaveh Edalati]], [[https://openalex.org/A5044287015][Qingsheng Gao]], [[https://openalex.org/A5090512624][Huaijun Lin]], Scripta materialia. 252(None)] 2024. https://doi.org/10.1016/j.scriptamat.2024.116268 
     
No abstract    

    

* Carbon-Based Materials for Low Concentration Co2 Capture and Electrocatalytic Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400484792
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4891233")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400484792"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400484792"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400484792"))][Get cited by]]

OpenAlex: https://openalex.org/W4400484792 (Open access: False)
    
[[https://openalex.org/A5101395545][Yanxi Hu]], [[https://openalex.org/A5101511381][Yangyang Ding]], [[https://openalex.org/A5068172137][Lily Y. Xie]], [[https://openalex.org/A5048387481][Hanyu Li]], [[https://openalex.org/A5024776929][Yujing Jiang]], [[https://openalex.org/A5104213029][Ke Gong]], [[https://openalex.org/A5019136723][Aidi Zhang]], [[https://openalex.org/A5048251870][Wenlei Zhu]], [[https://openalex.org/A5100778957][Yuanyuan Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4891233 
     
No abstract    

    

* Highthroughput Screening of CuBi Bimetallic Catalyst Array for Electrocatalytic CO2 Reduction Reaction by Scanning Electrochemical Microscope  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400558904
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrochemical Reduction of CO2 to Fuels, Atomic Force Microscopy Techniques
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cphc.202400536")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400558904"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400558904"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400558904"))][Get cited by]]

OpenAlex: https://openalex.org/W4400558904 (Open access: False)
    
[[https://openalex.org/A5033734140][X. Gu]], [[https://openalex.org/A5100422306][Zhen Wang]], [[https://openalex.org/A5100348369][Zhanwen Liu]], [[https://openalex.org/A5088838480][Gang Ni]], [[https://openalex.org/A5100388547][Limin Liu]], [[https://openalex.org/A5018700404][Dongping Zhan]], [[https://openalex.org/A5103120834][Juan Peng]], ChemPhysChem. None(None)] 2024. https://doi.org/10.1002/cphc.202400536 
     
The testing and evaluation of catalysts in CO2 electroreduction is a very tedious process. To study the catalytic system of CO2 reduction more quickly and efficiently, it is necessary to establish a method that can detect multiple catalysts at the same time. Herein, a series of CuBi bimetallic catalysts have been successfully prepared on a single glass carbon electrode by a scanning micropieptte contact method. The application of scanning electrochemical microscopy (SECM) enabled the visualization of the CO2 reduction activity in diverse catalyst micro‐points. The SECM imaging with Substrate generation/tip collection (SG/TC) mode was conducted on CuBi bimetallic micro‐points, revealing that HER reaction emerged as the prevailing reaction when a low overpotential was employed. While the applied potential was lower than ‐1.5 V (vs Ag/AgCl), the reduction of CO2 to formic acid became dominant. Increasing the bismuth proportion in the bimetallic catalyst can inhibit the hydrogen evolution reaction at low potential and enhances the selectivity of the CO product at high cathode overpotential.This research offers a novel approach to examining arrays of catalysts for CO2 reduction.    

    

* High selectivity and abundant active sites in atomically dispersed TM2C12 monolayer for CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400576723
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Thermoelectric Materials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuproc.2024.108106")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400576723"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400576723"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400576723"))][Get cited by]]

OpenAlex: https://openalex.org/W4400576723 (Open access: False)
    
[[https://openalex.org/A5035092988][Shulong Li]], [[https://openalex.org/A5030279813][Song Yu]], [[https://openalex.org/A5073299519][Tian Guo]], [[https://openalex.org/A5100688200][Qiaoling Liu]], [[https://openalex.org/A5062631493][Liang Qiao]], [[https://openalex.org/A5101429075][Yong Zhao]], [[https://openalex.org/A5006186991][Li‐Yong Gan]], Fuel processing technology. 261(None)] 2024. https://doi.org/10.1016/j.fuproc.2024.108106 
     
No abstract    

    

* CO2 and NO Reduction Characteristics from Biomass-Ammonia Co-firing in a Circulating Fluidized Bed Combustor  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400584385
:TOPICS: Biomass Pyrolysis and Conversion Technologies, Coal Water Slurry Technology and Utilization, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-981-97-1868-9_86")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400584385"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400584385"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400584385"))][Get cited by]]

OpenAlex: https://openalex.org/W4400584385 (Open access: False)
    
[[https://openalex.org/A5100323621][Sung Jin Park]], [[https://openalex.org/A5070305159][Seong‐Ju Kim]], [[https://openalex.org/A5033083598][Sung-Ho Jo]], [[https://openalex.org/A5016451254][Jae Goo Lee]], [[https://openalex.org/A5010793423][Tae Young Mun]], Green energy and technology. None(None)] 2024. https://doi.org/10.1007/978-981-97-1868-9_86 
     
No abstract    

    

* Synergistic Augmentation and Fundamental Mechanistic Exploration of β-Ga2O3-rGO Photocatalyst for Efficient CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400663272
:TOPICS: Gallium Oxide (Ga2O3) Semiconductor Materials and Devices, Photocatalytic Materials for Solar Energy Conversion, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4na00408f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400663272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400663272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400663272"))][Get cited by]]

OpenAlex: https://openalex.org/W4400663272 (Open access: True)
    
[[https://openalex.org/A5102945825][Hyein Jeong]], [[https://openalex.org/A5044974638][Hangyeol Choi]], [[https://openalex.org/A5075619909][Yujin Song]], [[https://openalex.org/A5044201544][Jung Han Kim]], [[https://openalex.org/A5002469914][Yohan Yoon]], Nanoscale advances. None(None)] 2024. https://doi.org/10.1039/d4na00408f 
     
We explore the novel photodecomposition capabilities of β-Ga2O3 when augmented with reduced graphene oxide (rGO). Employing real-time spectroscopy, this study unveils the sophisticated mechanisms of photodecomposition, identifying an optimal 1...    

    

* Photothermal-boosted S-scheme heterojunction of α-Fe2O3@NiOx for high-selective reduction of CO2 to CO  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400644913
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.160747")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400644913"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400644913"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400644913"))][Get cited by]]

OpenAlex: https://openalex.org/W4400644913 (Open access: False)
    
[[https://openalex.org/A5013391133][Xiao Liu]], [[https://openalex.org/A5104557517][Bai Kaihui]], [[https://openalex.org/A5078809436][Yuhang Nie]], [[https://openalex.org/A5100721477][Xusheng Wang]], [[https://openalex.org/A5045618171][Lang Pei]], Applied surface science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.160747 
     
No abstract    

    

* Redistributing the local electron density of bismuth via introducing halogen atoms for boosting CO2 reduction to formate  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400652055
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.checat.2024.101057")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400652055"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400652055"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400652055"))][Get cited by]]

OpenAlex: https://openalex.org/W4400652055 (Open access: False)
    
[[https://openalex.org/A5059435868][Haidong Shen]], [[https://openalex.org/A5031539784][H. N. Wang]], [[https://openalex.org/A5057284055][Tianshuai Wang]], [[https://openalex.org/A5100363728][Jiarui Zhang]], [[https://openalex.org/A5060113464][Shaowei Yang]], [[https://openalex.org/A5064335105][Hao Jiang]], [[https://openalex.org/A5100384368][Peng Zhao]], [[https://openalex.org/A5102470886][Runze Gao]], [[https://openalex.org/A5104558319][Xinrui Linghu]], [[https://openalex.org/A5101729594][Ying Guo]], [[https://openalex.org/A5101820889][Hepeng Zhang]], Chem catalysis. None(None)] 2024. https://doi.org/10.1016/j.checat.2024.101057 
     
No abstract    

    

* Water-induced Switching in Selectivity and Steric Control of Activity in Photochemical CO2 Reduction Catalyzed by RhCp*(bpy) Derivatives  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400664492
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-t3ltd-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400664492"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400664492"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400664492"))][Get cited by]]

OpenAlex: https://openalex.org/W4400664492 (Open access: False)
    
[[https://openalex.org/A5063894173][Dongseb Lee]], [[https://openalex.org/A5039693008][Kosei Yamauchi]], [[https://openalex.org/A5066627191][Ken Sakai]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-t3ltd-v2 
     
Photocatalytic reduction of CO2 to formic acid (HCOOH) was investigated in either organic or aqueous/organic media by employing three water-soluble Rh(Cp*)(n,n’-dihydroxy-2,2’-bipyridine) (n = 4, 5, or 6) in the presence of [Ru(bpy)3]2+, 1,3-dimethyl-2-phenyl-2,3-dihydro-1H-benzo[d]imidazole (BIH) and triethanolamine (TEOA). Through studying the electron-donating effects of two hydroxyl groups introduced to the bipyridyl ligand, we found that the substituent positions greatly affect both the catalytic efficiency and selectivity in CO2 reduction. More importantly, the HCOOH selectivity shows a dramatic increase from 14% to 83% upon switching the solvent media from pure organic to aqueous/organic mixture, where the H2 selectivity shows a reverse phenomenon. The enhanced HCOOH selectivity and the drastic decrease in the apparent H2 yield are well rationalized by the fact that the catalytic CO2 hydrogenation by the evolved H2 simultaneously proceeds as a dark catalytic reaction, which was also separately investigated under the dark conditions. Our DFT studies unveil that the exceptionally large structural strain given by the steric contacts between the 6,6’-dihydroxyl groups and the Cp* moiety plays a significant role in bringing about an outstanding catalytic performance of the 6,6’-subsituted derivative. The intrinsic reaction coordinate calculations were carried out to clarify the mechanism of hydride transfer steps leading to generate formate together the heterolytic H2 cleavage steps leading to afford the key hydridorhodium intermediates. This study represents the first report on the water-induced high selectivity in CO2-to-HCOOH conversion, shedding a new light on the strategy to control the efficiency and selectivity in the catalysis of CO2 reduction.    

    

* Independent hybrid energy systems using reliable renewable energy sources for providing sustainable power and CO2 emission reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400490511
:TOPICS: Hydrogen Energy Systems and Technologies, Integration of Electric Vehicles in Power Systems
:PUBLICATION_DATE: 2023-11-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/icteasd57136.2023.10585072")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400490511"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400490511"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400490511"))][Get cited by]]

OpenAlex: https://openalex.org/W4400490511 (Open access: False)
    
[[https://openalex.org/A5014312248][A. Mohamedyaseen]], [[https://openalex.org/A5100497362][R. Ayyappa]], [[https://openalex.org/A5088524198][Muntather Almusawi]], [[https://openalex.org/A5101692489][Kanchan Yadav]], [[https://openalex.org/A5100497363][Allaeva Gulchekhra Jalgasovna]], [[https://openalex.org/A5037897243][M. Murali]], [[https://openalex.org/A5100497364][Takkellapati Venkata Suneetha]], No host. None(None)] 2023. https://doi.org/10.1109/icteasd57136.2023.10585072 
     
No abstract    

    

* Selective scission of glucose molecule by a Pd-modulated Co-based catalyst for efficient CO2 reduction under mild conditions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400645946
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.scib.2024.07.020")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400645946"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400645946"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400645946"))][Get cited by]]

OpenAlex: https://openalex.org/W4400645946 (Open access: False)
    
[[https://openalex.org/A5101964400][Peidong Zhu]], [[https://openalex.org/A5048984134][Jiacong Li]], [[https://openalex.org/A5100397594][Yang Yang]], [[https://openalex.org/A5030447587][Heng Zhong]], [[https://openalex.org/A5000148829][Fangming Jin]], Science Bulletin. None(None)] 2024. https://doi.org/10.1016/j.scib.2024.07.020 
     
No abstract    

    

* Tensile‐Strained Cu Penetration Electrode Boosts Asymmetric C–C Coupling for Ampere‐Level CO2‐to‐C2+ Reduction in Acid  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400658650
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202407612")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400658650"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400658650"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400658650"))][Get cited by]]

OpenAlex: https://openalex.org/W4400658650 (Open access: False)
    
[[https://openalex.org/A5101644090][Shoujie Li]], [[https://openalex.org/A5013842278][Gangfeng Wu]], [[https://openalex.org/A5018878652][Jianing Mao]], [[https://openalex.org/A5058339207][Aohui Chen]], [[https://openalex.org/A5100689578][Xiaohu Liu]], [[https://openalex.org/A5068006098][Jianrong Zeng]], [[https://openalex.org/A5064015289][Yiheng Wei]], [[https://openalex.org/A5078303039][Jiangjiang Wang]], [[https://openalex.org/A5060510648][Haili Zhu]], [[https://openalex.org/A5103494520][Jian‐Bai Xia]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5085611722][Guihua Li]], [[https://openalex.org/A5101891693][Yanfang Song]], [[https://openalex.org/A5006528528][Xiao Dong]], [[https://openalex.org/A5100323723][Wei Wei]], [[https://openalex.org/A5100392071][Wei Wang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/anie.202407612 
     
The synthesis of multicarbon (C2+) products remains a substantial challenge in sustainable CO2 electroreduction owing to the need for sufficient current density and faradaic efficiency alongside carbon efficiency. Herein, we demonstrate ampere‐level high‐efficiency CO2 electroreduction to C2+ products in both neutral and strongly acidic (pH = 1) electrolytes using a hierarchical Cu hollow‐fiber penetration electrode (HPE). High concentration of K+ could concurrently suppress hydrogen evolution reaction and facilitate C–C coupling, thereby promoting C2+ production in strong acid. By optimizing the K+ and H+ concentration and CO2 flow rate, a faradaic efficiency of 84.5% and a partial current density as high as 3.1 A cm–2 for C2+ products, alongside a single‐pass carbon efficiency of 81.5% and stable electrolysis for 240 h were demonstrated in a strong acidic solution of H2SO4 and KCl (pH = 1). Experimental measurements and density functional theory simulations suggested that tensile‐strained Cu HPE enhances the asymmetric C–C coupling to steer the selectivity and activity of C2+ products.    

    

* The Effectiveness of Agricultural Carbon Dioxide Removal using the University of Victoria Earth System Climate Model  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400661486
:TOPICS: Global Methane Emissions and Impacts, Carbon Dioxide Sequestration in Geological Formations, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-2024-1810")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400661486"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400661486"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400661486"))][Get cited by]]

OpenAlex: https://openalex.org/W4400661486 (Open access: True)
    
[[https://openalex.org/A5084958058][Rebecca C. Evans]], [[https://openalex.org/A5051571272][H. Damon Matthews]], No host. None(None)] 2024. https://doi.org/10.5194/egusphere-2024-1810 
     
Abstract. A growing body of evidence suggests that to achieve the temperature goals of the Paris Agreement, carbon dioxide removal (CDR) will likely be required in addition to massive carbon dioxide (CO2) emissions reductions. Nature-based CDR, which includes a range of strategies to sequester carbon in natural reservoirs, could play an important role in efforts to limit climate warming to well below 2 °C above preindustrial levels. Agricultural CDR could enhance soil carbon sequestration, though the climate efficacy of such methods remains uncertain. Here, we use an intermediate complexity climate model to perform simulations of agricultural CDR in the form of soil carbon sequestration at a range of possible rates for different costs under three future emissions scenarios. We found that plausible levels of agricultural CDR were able to reduce CO2 concentration by 5–19 ppm and global surface air temperature by 0.02–0.10 °C by the end of century. This temperature decrease was non-linear with respect to cumulative removals, as any carbon removed remained part of the active carbon cycle, lessening the climate benefit compared to if the removed carbon was permanently stored in geological reservoirs. CDR was found to be more effective at reducing surface air temperature in low emissions scenarios, but less effective at reducing atmospheric CO2, compared to high emissions scenarios. This was because the weaker CO2 sinks in a high CO2 world had a more muted response to removal, so a substantially higher proportion of carbon was removed from the atmosphere for a given amount of CDR in a higher emissions scenario. The enhanced temperature response to CDR in lower emissions scenarios was due to the logarithmic response of radiative effects to changes in CO2, where at low atmospheric CO2 concentrations, small changes in CO2 are more effective at changing the global radiative balance than at higher CO2 concentrations. CDR was substantially more effective when implemented at a higher rate, as CDR makes a proportionally larger difference in a climate with lower cumulative air fraction of CO2. Land and soil carbon responses were driven by the scenario-dependent balances between the impacts of CDR on primary productivity from CO2 fertilization, and the impacts on soil respiration from increased soil carbon availability and global temperatures.    

    

* Quantitative Analysis of Carbon Emissions from Highway Construction Based on Life Cycle Assessment  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400522787
:TOPICS: Impact of Road Salt on Freshwater Salinization
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16145897")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400522787"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400522787"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400522787"))][Get cited by]]

OpenAlex: https://openalex.org/W4400522787 (Open access: True)
    
[[https://openalex.org/A5020906236][Shuohan Gao]], [[https://openalex.org/A5089553750][Xuexin Liu]], [[https://openalex.org/A5059899082][Chunying Lu]], [[https://openalex.org/A5005250918][H Zhang]], [[https://openalex.org/A5100689421][Xinjun Wang]], [[https://openalex.org/A5102299642][Yaping Kong]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16145897 
     
Carbon dioxide (CO2) emissions from the construction of road infrastructure have been of growing interest in recent years. This paper proposes a binary statistical method for highway construction based on project cost control and a construction management system. A quantitative analysis of the CO2 emissions from highway construction activities was also conducted to guide the formulation of a carbon reduction strategy. Taking an expressway in central China as a case study, the CO2 emissions from different construction activities were calculated. The results revealed that the CO2 emissions for the whole construction project reached 10,605.2 t·km−1·lane−1, with the raw material production and on-site construction phases accounting for 95.2% and 4.8%, respectively. The values for bridge and tunnel engineering were much higher than those for other engineering types. In the raw material production phase, steel and cement production contributed the most to emissions (more than 99%). During the on-site construction phase, diesel and electricity consumption contributed 90% to CO2 emissions, especially from earthwork, subgrade protection, bridge engineering, tunnel excavation, and pavement surfacing. Accordingly, efforts should be focused on the key points and directed toward using recycled and low-carbon materials and improving working efficiency, machinery performance, and construction technology.    

    

* Unraveling the hydropower vulnerability to drought in the United States  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400520128
:TOPICS: Optimal Operation of Water Resources Systems, Integrated Management of Water, Energy, and Food Resources, Global Flood Risk Assessment and Management
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1748-9326/ad6200")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400520128"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400520128"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400520128"))][Get cited by]]

OpenAlex: https://openalex.org/W4400520128 (Open access: True)
    
[[https://openalex.org/A5001210406][Pouya Moghaddasi]], [[https://openalex.org/A5026811888][Keyhan Gavahi]], [[https://openalex.org/A5085701082][Hamed Moftakhari]], [[https://openalex.org/A5037342105][Hamid Moradkhani]], Environmental research letters. None(None)] 2024. https://doi.org/10.1088/1748-9326/ad6200 
     
Abstract Drought, a potent natural climatic phenomenon, significantly challenges hydropower systems, bearing adverse consequences for economies, societies, and the environment. This study delves into the profound impact of drought on hydropower generation in the United States, revealing a robust correlation between hydrologic drought and hydroelectricity generation. Our analysis of the period from 2003 to 2020 for the Contiguous United States (CONUS) indicates that drought events led to a considerable decline in hydroelectricity generation, amounting to approximately 300 million MWh, and resulting in an estimated loss of $28 billion to the sector. Moreover, our findings highlight the adverse environmental effect of drought-induced hydropower generation reductions, which are often compensated by increased reliance on natural gas usage, which led to substantial emissions of carbon dioxide (CO2), sulfur dioxide (SO2), and nitrogen oxide (NOX), totaling 161,700 kilotons, 119,9 tons, and 181,977 tons, respectively. In addition to these findings, we assess the state-level vulnerability of hydropower to drought, identifying Washington and California as the most vulnerable states, while Nevada exhibits the least vulnerability. Overall, this study enhances understanding of the multifaceted effects of drought on hydropower, which can assist in informing policies and practices related to drought management and energy production.    

    

* Evaluating the near- and long-term role of carbon dioxide removal in meeting global climate objectives  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400656455
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Economic Implications of Climate Change Policies, Social Acceptance of Renewable Energy Innovation
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s43247-024-01527-z")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400656455"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400656455"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400656455"))][Get cited by]]

OpenAlex: https://openalex.org/W4400656455 (Open access: True)
    
[[https://openalex.org/A5002533374][Gaurav Ganti]], [[https://openalex.org/A5062044999][Thomas Gasser]], [[https://openalex.org/A5089539640][Mai Bui]], [[https://openalex.org/A5016996676][Oliver Geden]], [[https://openalex.org/A5002742682][William F. Lamb]], [[https://openalex.org/A5060648323][Jan C. Minx]], [[https://openalex.org/A5033036905][Carl-Friedrich Schleußner]], [[https://openalex.org/A5012881631][Matthew Gidden]], Communications earth & environment. 5(1)] 2024. https://doi.org/10.1038/s43247-024-01527-z 
     
Abstract The 6th Assessment Report from the Intergovernmental Panel on Climate Change lacked sufficient land-sector scenario information to estimate total carbon dioxide removal deployment. Here, using a dataset of land-based carbon dioxide removal based on the scenarios assessed by the Intergovernmental Panel on Climate Change, we show that removals via afforestation and reforestation play a critical near-term role in mitigation, accounting for around 10% (median) of the net greenhouse gas emission reductions between 2020 and 2030 in scenarios that limit warming to 1.5 °C with limited overshoot. Novel carbon dioxide removal technologies such as direct air carbon capture and storage scale to multi-gigatonne levels by 2050 and beyond to balance residual emissions and draw down warming. We show that reducing fossil fuel and deforestation emissions (gross emissions) accounts for over 80% of net greenhouse gas reductions until global net zero carbon dioxide (CO 2 ) independent of climate objective stringency. We explore the regional distributions of gross emissions and total carbon dioxide removal in cost-effective mitigation pathways and highlight the importance of incorporating fairness and broader sustainability considerations in future assessments of mitigation pathways with carbon dioxide removal.    

    

* Capacity Expansion Planning of Hydrogen-Enabled Industrial Energy Systems for Carbon Dioxide Peaking  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400533623
:TOPICS: Integration of Renewable Energy Systems in Power Grids, Carbon Dioxide Capture and Storage Technologies, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17143400")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400533623"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400533623"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400533623"))][Get cited by]]

OpenAlex: https://openalex.org/W4400533623 (Open access: True)
    
[[https://openalex.org/A5100323951][Kai Zhang]], [[https://openalex.org/A5039059996][Xiangxiang Dong]], [[https://openalex.org/A5100610667][Chaofeng Li]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5100752207][Kun Liu]], Energies. 17(14)] 2024. https://doi.org/10.3390/en17143400 
     
As the main contributor of carbon emissions, the low-carbon transition of the industrial sector is important for achieving the goal of carbon dioxide peaking. Hydrogen-enabled industrial energy systems (HIESs) are a promising way to achieve the low-carbon transition of industrial energy systems, since the hydrogen can be well coordinated with renewable energy sources and satisfy the high and continuous industrial energy demand. In this paper, the long-term capacity expansion planning problem of the HIES is formulated from the perspective of industrial parks, and the targets of carbon dioxide peaking and the gradual decommissioning of existing equipment are considered as constraints. The results show that the targets of carbon dioxide peaking before different years or with different emission reduction targets can be achieved through the developed method, while the economic performance is ensured to some extent. Meanwhile, the overall cost of the strategy based on purchasing emission allowance is three times more than the cost of the strategy obtained by the developed method, while the emissions of the two strategies are same. In addition, long-term carbon reduction policies and optimistic expectations for new energy technologies will help industrial parks build more new energy equipment for clean transformation.    

    

* Highly Selective Electrocatalytic CO2 Conversion to Tailored Products through Precise Regulation of Hydrogenation and C–C Coupling  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400524077
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c07502")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400524077"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400524077"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400524077"))][Get cited by]]

OpenAlex: https://openalex.org/W4400524077 (Open access: False)
    
[[https://openalex.org/A5017108318][Bao Yu Xia]], [[https://openalex.org/A5075133693][Tao Wang]], [[https://openalex.org/A5101408837][Chaohui He]], [[https://openalex.org/A5015154651][Ruijuan Qi]], [[https://openalex.org/A5103844519][Deyu Zhu]], [[https://openalex.org/A5065513785][Ruihu Lu]], [[https://openalex.org/A5011089626][Fumin Li]], [[https://openalex.org/A5100401978][Yu Chen]], [[https://openalex.org/A5032988244][Shenghua Chen]], [[https://openalex.org/A5100599506][Bo You]], [[https://openalex.org/A5100749138][Tao Yao]], [[https://openalex.org/A5019671436][Wei Guo]], [[https://openalex.org/A5010194502][Fei Song]], [[https://openalex.org/A5100744706][Ziyun Wang]], [[https://openalex.org/A5017108318][Bao Yu Xia]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c07502 
     
The electrochemical reduction reaction of carbon dioxide (CO    

    

* Anionic Surfactant–Tailored Interfacial Microenvironment for Boosting Electrochemical CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400484381
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c07258")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400484381"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400484381"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400484381"))][Get cited by]]

OpenAlex: https://openalex.org/W4400484381 (Open access: False)
    
[[https://openalex.org/A5101902867][Xin Yuan]], [[https://openalex.org/A5065419997][Wangxin Ge]], [[https://openalex.org/A5067580654][Yihua Zhu]], [[https://openalex.org/A5100407533][Lei Dong]], [[https://openalex.org/A5087914705][Hongliang Jiang]], [[https://openalex.org/A5009144836][Chunzhong Li]], ACS applied materials & interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c07258 
     
Both the catalyst and electrolyte deeply impact the performance of the carbon dioxide reduction reaction (CO    

    

* Medical hypnosis mitigates laboratory dyspnoea in healthy humans: a randomised, controlled experimental trial  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400532967
:TOPICS: The Relationship Between Music and Anxiety Management, Pediatric Pain Assessment and Management, Empathy Decline and Training in Medical Education
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1183/13993003.00485-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400532967"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400532967"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400532967"))][Get cited by]]

OpenAlex: https://openalex.org/W4400532967 (Open access: False)
    
[[https://openalex.org/A5104089463][Capucine Morélot-Panzini]], [[https://openalex.org/A5104383244][Cécile Arveiller-Carvallo]], [[https://openalex.org/A5056260743][Isabelle Rivals]], [[https://openalex.org/A5059324341][Nicolas Wattiez]], [[https://openalex.org/A5035391048][Sophie Lavault]], [[https://openalex.org/A5065791024][A. Brion]], [[https://openalex.org/A5062465999][Laure Serresse]], [[https://openalex.org/A5085192420][Christian Straus]], [[https://openalex.org/A5010462884][Marie‐Cécile Nierat]], [[https://openalex.org/A5002219202][Thomas Similowski]], European respiratory journal/The European respiratory journal. None(None)] 2024. https://doi.org/10.1183/13993003.00485-2024 
     
Question Dyspnoea persisting despite treatments of underlying causes requires symptomatic approaches. Medical hypnosis could provide relief without the untoward effects of pharmacological approaches. We addressed this question through experimentally induced dyspnoea in healthy humans (inspiratory threshold loading –excessive inspiratory effort– and carbon dioxide stimulation –air hunger–) Material and Methods 20 volunteers (10 women, 21–40) were studied on 4 separate days. The order of the visits was randomised in two steps, firstly “inspiratory threshold loading first” versus “carbon dioxide first” group (n=10 in each group), secondly “medical hypnosis first” versus “visual distraction first” subgroup (n=5 in each subgroup). Each visit comprised three 5-minutes periods (reference, intervention, washout) during which participants used visual analog scales to rate dyspnoea's sensory and affective dimensions and after which they completed the Multidimensional Dyspnea Profile. Results Medical hypnosis reduced both dimensions of dyspnoea significantly more than visual distraction (inspiratory threshold loading: sensory reduction after 5 min 34% of full VAS versus 8% –p=0.0042–; affective reduction 17.6% versus 2.4% –p=0.044–; carbon dioxide; sensory reduction after 5 min 36.9% versus 3% –p=0.0015–; affective reduction 29.1% versus 8.7% –p=0.0023–). The Multidimensional Dyspnea Profile showed more marked sensory effects during inspiratory threshold loading and more marked affective effects during carbon dioxide stimulation. Answer to the question Medical hypnosis was more effective than visual distraction at attenuating the sensory and affective dimensions of experimentally induced dyspnoea. This provides a strong rationale for clinical studies of hypnosis in persistent dyspnoea patients.    

    

* Renewable Energy, Economic Policy Uncertainty and Climate Policy Uncertainty: New Evidence for Environmental Kuznets Curve from Emerging and Developed Countries  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400641011
:TOPICS: Economic Impact of Environmental Policies and Resources, Impact of Oil Price Shocks on Economy, The Political Economy of Resource Curse Hypothesis
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16146049")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400641011"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400641011"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400641011"))][Get cited by]]

OpenAlex: https://openalex.org/W4400641011 (Open access: True)
    
[[https://openalex.org/A5099990279][Canan Özkan]], [[https://openalex.org/A5036852678][Nesrin Okay]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16146049 
     
Recent events, such as the financial crisis, oil price shocks or fluctuations, Brexit, the US–China trade war, the COVID-19 pandemic, the Russia–Ukraine conflict and the subsequent energy crisis, have surged global economic policy uncertainty. As climate change has recently been more pronounced around the globe, discussions about climate policies and related uncertainties have also become a major concern. This study investigates the role of economic policy uncertainty (EPU) and climate policy uncertainty (CPU) on climate change (environmental degradation) for selected emerging and developed economies, expanding the IPAT framework and merging it with the Environmental Kuznets Curve (EKC) hypothesis. The IPAT framework examines the impact (I) of population (P), affluence (A), and technology (T) on the environment, whereas the EKC hypothesis proposes an inverted U-shaped curve between affluence and environmental degradation. Two models were created and tested for emerging and developed countries, namely Model 1 with EPU and Model 2 with CPU. A Pooled Mean Group (PMG) estimator is employed to investigate the interrelation between carbon dioxide (CO2) emissions and selected variables; namely the real Gross Domestic Product (GDP) per capita, squared real GDP per capita, renewable share in consumption, the EPU, the CPU and population. Test results indicate that the EKC hypothesis is verified only in Model 1 and for emerging countries, whereas population escalates climate change in both country groups. Furthermore, in line with the consumption effect theorized earlier in the literature, EPU is negatively related to carbon emissions in emerging countries. Thus, the EPU leads to a decrease in the use of energy and pollution-intensive commodities and mitigates climate change in EMEs. Compatible with our ex-ante expectations, renewable energy consumption alleviates climate change in both country groups in the short term. In Model 2, with CPU, we find no evidence supporting the EKC hypothesis for any country groups. However, we reaffirm that renewable energy consumption decreases CO2 emissions in developed countries, which is in support of the argument that energy transition holds the key to tackling climate change. Finally, CPU is associated with a decrease in CO2 emissions in emerging countries in the short term, potentially leading to a reduction in overall economic activity and alleviating climate change. This might also be attributable to the fact that the decisions of economic agents substantially rely on current and future policy (both economic and climate) expectations. Overall, verifying the EKC hypothesis for emerging countries in Model 1, we might argue that there is good potential for emerging countries to save money and time on environmental costs via the adoption of clean technologies and related policies. Last but not least, on a global scale, energy transition with better utilization of renewable sources holds the key to tackling climate change and reducing emissions.    

    

* Greening the Economy from the Ground Up: How the Minimum Wage Affects Firms’ Pollution Emissions in China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400643532
:TOPICS: Economic Impact of Environmental Policies and Resources, Economic Implications of Climate Change Policies, Rebound Effect on Energy Efficiency and Consumption
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16146020")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400643532"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400643532"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400643532"))][Get cited by]]

OpenAlex: https://openalex.org/W4400643532 (Open access: True)
    
[[https://openalex.org/A5017013506][Haili Ren]], [[https://openalex.org/A5020805958][Ming‐Liang Zhu]], [[https://openalex.org/A5043816646][Baolei Lyu]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16146020 
     
The implications of minimum wage standards have been widely debated, but their effects on firms’ pollution emissions and the underlying mechanisms remain underexplored. This paper finds that the introduction of minimum wage standards significantly reduces emissions of pollutants such as carbon dioxide and sulfur dioxide. Firms respond to rising minimum wages by optimizing their product mix, enhancing technological innovation, and improving managerial efficiency, which collectively curb pollution outputs. Our analysis using a random forest model shows that these effects are most pronounced in regions with higher economic development, stringent environmental regulations, and elevated minimum wage standards. Our findings augment the body of research on minimum wage standards and introduce novel insights for emission reduction strategies for firms.    

    

* Digital Empowerment and Enterprise Carbon Risk Management: Evidence from Manufacturing Sector  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400522918
:TOPICS: Drivers and Impacts of Green Consumer Behavior, Conceptualizing the Circular Economy and Sustainable Supply Chains, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2478/eces-2024-0013")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400522918"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400522918"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400522918"))][Get cited by]]

OpenAlex: https://openalex.org/W4400522918 (Open access: True)
    
[[https://openalex.org/A5100394739][Yan Han]], Ecological Chemistry and Engineering. S. 31(2)] 2024. https://doi.org/10.2478/eces-2024-0013 
     
Abstract The paper addresses the imperative of empowering enterprises to achieve energy savings and emission reductions through digital development amidst the backdrop of peak carbon dioxide emissions and carbon neutrality. This study integrates digital empowerment and enterprise carbon risk management into a unified analytical framework, utilising panel data from listed companies spanning from 2011 to 2020 as research samples. The empirical investigation aims to ascertain whether there exist carbon risks impacting the operational performance of manufacturing enterprises and whether digital empowerment can mitigate these risks. The findings reveal that carbon intensity exerts an inhibitory influence on the enhancement of enterprise performance, indicating the presence of carbon risk issues faced by enterprises. Furthermore, it is observed that these carbon risk challenges escalate over time, a trend supported by robustness tests. Digital empowerment emerges as an effective mechanism in slowing down the carbon risks encountered by enterprises, albeit exhibiting characteristics of time lag. The study identifies notable heterogeneity in the role of digital empowerment in mitigating the carbon risks of enterprises.    

    

* A win-win strategy to enhance the energy transition, improve air quality and reduce associated health threats  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400565045
:TOPICS: Indoor Air Pollution in Developing Countries, Rebound Effect on Energy Efficiency and Consumption
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-plinius18-26")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400565045"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400565045"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400565045"))][Get cited by]]

OpenAlex: https://openalex.org/W4400565045 (Open access: False)
    
[[https://openalex.org/A5102791962][Victoria Gallardo]], [[https://openalex.org/A5078156106][Pedro Jiménez‐Guerrero]], [[https://openalex.org/A5055698210][Sónia Jerez]], No host. None(None)] 2024. https://doi.org/10.5194/egusphere-plinius18-26 
     
This contribution shows the co-benefits of an optimal deployment of renewable energy infrastructure, particularly wind and solar photovoltaics, on air quality and associated health impact. The term "optimal" here specifically refers to leveraging the spatio-temporal complementarity of both resources in order to minimize the fluctuations of their combined electricity production, and so easing their integration in the energy mix. In a previous work by Jerez et al. (2023), the open-access CLIMAX tool was developed for that purpose, and utilized to delineate optimal capacity density scenarios across five European regions. We now show that, under these optimized scenarios, the European CO2-equivalent emissions could decrease by 1%, accompanied by a significant reduction in pollutant emissions from combustion power plants, potentially amounting to hundreds of kilotons of fine particulate matter and nitrogen dioxide saved. Exposure to these contaminants caused approximately three hundred thousands deaths in Europe in 2021, as reported by EEA (2023). In this sense, building upon the methodology employed by Tar&#237;n-Carrasco et al. (2021), our estimates corroborate that implementing the CLIMAX scenarios could substantially avoid human fatalities associated with air pollution. Hence, pursuing carbon neutrality through a judicious energy transition emerges as a win-win strategy. Not only does it contribute to climate change mitigation by curbing greenhouse gas emissions, but it also fosters healthier, more breathable environments, thus preventing premature mortality as it relates to poor air quality. REFERENCES: EEA (2023). Harm to human health from air pollution in Europe: burden of disease 2023. Jerez, S., Barriopedro, D., Garc&#237;a-L&#243;pez, A., Lorente-Plazas, R., Somoza, A. M., Turco, M., Carrillo, J., &amp; Trigo, R. M. (2023). An action-oriented approach to make the most of the wind and solar power complementarity. Earth's Future, 11, e2022EF003332. Tar&#237;n-Carrasco, P., Im, U., Geels, C., Palacios-Pe&#241;a, L., &amp; Jim&#233;nez-Guerrero, P. (2021). Contribution of fine particulate matter to present and future premature mortality over Europe: A non-linear response. Environment International, 153, 106517.    

    

* Plant diversity decreases greenhouse gas emissions by increasing soil and plant carbon storage in terrestrial ecosystems  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400526337
:TOPICS: Soil Carbon Dynamics and Nutrient Cycling in Ecosystems, Carbon Dynamics in Peatland Ecosystems, Impact of Climate Change on Forest Wildfires
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/ele.14469")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400526337"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400526337"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400526337"))][Get cited by]]

OpenAlex: https://openalex.org/W4400526337 (Open access: False)
    
[[https://openalex.org/A5091391331][Pengfei Dang]], [[https://openalex.org/A5100357892][Miaomiao Zhang]], [[https://openalex.org/A5100734697][Han Y. H. Chen]], [[https://openalex.org/A5015141521][Michel Loreau]], [[https://openalex.org/A5000370285][J. Emmett Duffy]], [[https://openalex.org/A5056777409][Xine Li]], [[https://openalex.org/A5087808820][Shuyue Wen]], [[https://openalex.org/A5100662359][Xiaoqing Han]], [[https://openalex.org/A5035800645][Lin Liao]], [[https://openalex.org/A5083936112][Tiantian Huang]], [[https://openalex.org/A5103066162][Chenxi Wan]], [[https://openalex.org/A5017213163][Xiaoliang Qin]], [[https://openalex.org/A5082109205][Kadambot H. M. Siddique]], [[https://openalex.org/A5025353875][Bernhard Schmid]], Ecology letters. 27(7)] 2024. https://doi.org/10.1111/ele.14469 
     
Abstract The decline in global plant diversity has raised concerns about its implications for carbon fixation and global greenhouse gas emissions (GGE), including carbon dioxide (CO 2 ), nitrous oxide (N 2 O) and methane (CH 4 ). Therefore, we conducted a comprehensive meta‐analysis of 2103 paired observations, examining GGE, soil organic carbon (SOC) and plant carbon in plant mixtures and monocultures. Our findings indicate that plant mixtures decrease soil N 2 O emissions by 21.4% compared to monocultures. No significant differences occurred between mixtures and monocultures for soil CO 2 emissions, CH 4 emissions or CH 4 uptake. Plant mixtures exhibit higher SOC and plant carbon storage than monocultures. After 10 years of vegetation development, a 40% reduction in species richness decreases SOC content and plant carbon storage by 12.3% and 58.7% respectively. These findings offer insights into the intricate connections between plant diversity, soil and plant carbon storage and GGE—a critical but previously unexamined aspect of biodiversity–ecosystem functioning.    

    

* The Role of Agroforestry in Ecosystem Services and Mitigation of Climate Change  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400548840
:TOPICS: Agroforestry Systems and Biodiversity Enhancement, Agroforestry Tree Domestication in Africa, Global Analysis of Ecosystem Services and Land Use
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18619/2072-9146-2024-4-111-119")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400548840"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400548840"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400548840"))][Get cited by]]

OpenAlex: https://openalex.org/W4400548840 (Open access: True)
    
[[https://openalex.org/A5101562948][A. Worku]], Ovoŝi Rossii. None(4)] 2024. https://doi.org/10.18619/2072-9146-2024-4-111-119 
     
Relevance. Agroforestry systems are believed to provide a multitude of ecological services. It is thought that agroforestry enhances resilience to the impacts of climate change and aids in adaptation by supporting diverse land use practices, sustainable lifestyles, and income streams, as well as increasing productivity in both forests and agriculture, and reducing weather-related losses in production. Results and Discussion. The aim of this review was to present genuine evidence on the role of agroforestry in ecosystem conservation and mitigation of climate change impacts. Compared to monocropping and open cereal-based agriculture, agroforestry has made a more significant contribution to ecosystem conservation and in reducing carbon dioxide emissions. However, it has been found that agroforestry contributes less to carbon sequestration than natural forests. Carbon sequestration through above-ground and underground biomass, carbon emission reduction from deforestation, and microclimate adjustment are key measures for mitigating climate change. Agroforestry systems provide essential ecosystem services, such as food, fuel wood, fodder, income, and improved soil production, which enable communities to cope better with the impacts of climate change. Therefore, agroforestry must be given significant attention if it is to play a crucial role in ecosystem management.    

    

* Inside Cover Picture  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400655497
:TOPICS: 
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cjoc.202490162")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400655497"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400655497"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400655497"))][Get cited by]]

OpenAlex: https://openalex.org/W4400655497 (Open access: False)
    
, Chinese journal of chemistry. 42(16)] 2024. https://doi.org/10.1002/cjoc.202490162 
     
Copper‐based catalysts are frequently employed for carbon dioxide reduction reactions (CO 2 RR), yet the regulation of pore structure and surface state of electrocatalysts remains a prominent challenge in previous research endeavors. In this study, we introduce a novel technique to produce mesoporous Cu 2 O nanocrystals, with finely tuned pore size and surface amine functionality leveraging the incorporation of various amine compounds during the oxidative process of copper nanocrystals. The synergistic effect of pore structure confinement and surface amine functionalization culminates in an impressive Faradaic efficiency (FE) of 51.9% for the selective production of C 2 H 4 . More details are discussed in the article by Huang et al . on page 1846—1852. image    

    

* Data collection framework for enhanced carbon intensity indicator (CII) in the oil tankers  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400508698
:TOPICS: Environmental Impact of Maritime Transportation Emissions, Subsea Oil and Gas Technology, Cryogenic Fluid Storage and Management
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cjce.25384")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400508698"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400508698"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400508698"))][Get cited by]]

OpenAlex: https://openalex.org/W4400508698 (Open access: True)
    
[[https://openalex.org/A5055413265][Abdullah Sh. Sardar]], [[https://openalex.org/A5050549886][Mohan Anantharaman]], [[https://openalex.org/A5077980685][Rabiul Islam]], [[https://openalex.org/A5079111287][Vikram Garaniya]], Canadian journal of chemical engineering/The Canadian journal of chemical engineering. None(None)] 2024. https://doi.org/10.1002/cjce.25384 
     
Abstract The International Maritime Organization (IMO) aims to reduce greenhouse gas (GHG) emissions by 40% by 2030 compared with 2008. The carbon intensity indicator (CII) calculates the annual reduction factor required to continuously improve a ship's operational carbon intensity at a specific rating level. Verification and documentation of the achieved annual operational CII against the prescribed target are necessary to establish the operational carbon intensity rating. This study focuses on the intricate process of data collection for CII within the oil shipping industry, targeting engineering departments and shipboard management teams. Against the backdrop of the industry's substantial carbon dioxide emissions, the IMO has mandated the calculation of CII values for ships exceeding 5000 gross tons to promote sustainability and reduce environmental impact. We have collected emission data of 20 oil tankers over a period of 2 years using our ship maintenance and operating system (SMOS) and analyzed the data to compare the CII ratings. Our results indicate that a staggering ~63% of the vessels had the lowest CII rating of category E. It is therefore crucial to properly collect, organize, and evaluate data for CII calculation and take necessary measures to improve rating. This paper provides a deeper insight into the evolving CII calculation methodology, emphasizing the incorporation of correction factors and exclusions, and delineates the essential data collection practices needed to facilitate accurate CII calculations.    

    

* Review on Absorption Refrigeration Technology and Its Potential in Energy-Saving and Carbon Emission Reduction in Natural Gas and Hydrogen Liquefaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400523011
:TOPICS: Waste Heat Recovery for Power Generation and Cogeneration, Development and Optimization of Stirling Engines, Refrigeration Systems and Technologies
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17143427")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400523011"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400523011"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400523011"))][Get cited by]]

OpenAlex: https://openalex.org/W4400523011 (Open access: True)
    
[[https://openalex.org/A5027355692][Lisong Wang]], [[https://openalex.org/A5060354520][Linli He]], [[https://openalex.org/A5102190786][Yijian He]], Energies. 17(14)] 2024. https://doi.org/10.3390/en17143427 
     
With the requirement of energy decarbonization, natural gas (NG) and hydrogen (H2) become increasingly important in the world’s energy landscape. The liquefaction of NG and H2 significantly increases energy density, facilitating large-scale storage and long-distance transport. However, conventional liquefaction processes mainly adopt electricity-driven compression refrigeration technology, which generally results in high energy consumption and carbon dioxide emissions. Absorption refrigeration technology (ART) presents a promising avenue for enhancing energy efficiency and reducing emissions in both NG and H2 liquefaction processes. Its ability to utilize industrial waste heat and renewable thermal energy sources over a large temperature range makes it particularly attractive for sustainable energy practices. This review comprehensively analyzes the progress of ART in terms of working pairs, cycle configurations, and heat and mass transfer in main components. To operate under different driven heat sources and refrigeration temperatures, working pairs exhibit a diversified development trend. The environment-friendly and high-efficiency working pairs, in which ionic liquids and deep eutectic solvents are new absorbents, exhibit promising development potential. Through the coupling of heat and mass transfer within the cycle or the addition of sub-components, cycle configurations with higher energy efficiency and a wider range of operational conditions are greatly focused. Additives, ultrasonic oscillations, and mechanical treatment of heat exchanger surfaces efficiently enhance heat and mass transfer in the absorbers and generators of ART. Notably, nanoparticle additives and ultrasonic oscillations demonstrate a synergistic enhancement effect, which could significantly improve the energy efficiency of ART. For the conventional NG and H2 liquefaction processes, the energy-saving and carbon emission reduction potential of ART is analyzed from the perspectives of specific power consumption (SPC) and carbon dioxide emissions (CEs). The results show that ART integrated into the liquefaction processes could reduce the SPC and CE by 10~38% and 10~36% for NG liquefaction processes, and 2~24% and 5~24% for H2 liquefaction processes. ART, which can achieve lower precooling temperatures and higher energy efficiency, shows more attractive perspectives in low carbon emissions of NG and H2 liquefaction.    

    

* Boosting Electrochemical Urea Synthesis via Constructing Ordered Pd–Zn Active Pair  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400658782
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40820-024-01462-w")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400658782"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400658782"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400658782"))][Get cited by]]

OpenAlex: https://openalex.org/W4400658782 (Open access: True)
    
[[https://openalex.org/A5027541982][Weiliang Zhou]], [[https://openalex.org/A5049868081][Chao Feng]], [[https://openalex.org/A5100362356][Xuan Li]], [[https://openalex.org/A5005640447][Xingxing Jiang]], [[https://openalex.org/A5069537889][Lingyan Jing]], [[https://openalex.org/A5102210038][Qi Shuai]], [[https://openalex.org/A5014488148][Qihua Huo]], [[https://openalex.org/A5076813850][Miaoyuan Lv]], [[https://openalex.org/A5029899663][Xinbao Chen]], [[https://openalex.org/A5102620665][T. W. Huang]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5103271655][Na Meng]], [[https://openalex.org/A5009718397][Hengpan Yang]], [[https://openalex.org/A5101453394][Qi Hu]], [[https://openalex.org/A5064805977][Chuanxin He]], Nano-micro letters. 16(1)] 2024. https://doi.org/10.1007/s40820-024-01462-w 
     
Abstract Electrochemical co-reduction of nitrate (NO 3 – ) and carbon dioxide (CO 2 ) has been widely regarded as a promising route to produce urea under ambient conditions, however the yield rate of urea has remained limited. Here, we report an atomically ordered intermetallic pallium-zinc (PdZn) electrocatalyst comprising a high density of PdZn pairs for boosting urea electrosynthesis. It is found that Pd and Zn are responsible for the adsorption and activation of NO 3 – and CO 2 , respectively, and thus the co-adsorption and co-activation NO 3 – and CO 2 are achieved in ordered PdZn pairs. More importantly, the ordered and well-defined PdZn pairs provide a dual-site geometric structure conducive to the key C–N coupling with a low kinetical barrier, as demonstrated on both operando measurements and theoretical calculations. Consequently, the PdZn electrocatalyst displays excellent performance for the co-reduction to generate urea with a maximum urea Faradaic efficiency of 62.78% and a urea yield rate of 1274.42 μg mg –1 h –1 , and the latter is 1.5-fold larger than disordered pairs in PdZn alloys. This work paves new pathways to boost urea electrosynthesis via constructing ordered dual-metal pairs.    

    

* BIOMASS GASIFICATION FOR HYDROGEN PRODUCTION  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400499249
:TOPICS: Biomass Pyrolysis and Conversion Technologies, Catalytic Carbon Dioxide Hydrogenation, Supercritical Water Gasification for Hydrogen Production
:PUBLICATION_DATE: 2023-06-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.51594/estj.v4i2.1289")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400499249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400499249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400499249"))][Get cited by]]

OpenAlex: https://openalex.org/W4400499249 (Open access: False)
    
[[https://openalex.org/A5099400569][Afor Avwioroko]], Engineering science & tecnology journal. 4(2)] 2023. https://doi.org/10.51594/estj.v4i2.1289 
     
Biomass gasification is emerging as a promising technology for producing hydrogen, addressing the dual challenges of sustainable energy supply and environmental conservation. This process converts biomass into syngas—a mixture primarily composed of hydrogen, carbon monoxide, and carbon dioxide—through thermal decomposition in a controlled environment. The syngas is then processed to extract hydrogen, which can serve as a clean fuel for various applications, including transportation and industrial processes. This paper provides an overview of the biomass gasification process, detailing suitable biomass feedstock types and gasifier types, such as fixed-bed, fluidized-bed, and entrained-flow gasifiers. It explores the conversion of syngas to hydrogen, highlighting essential catalytic reforming and purification techniques for producing high-purity hydrogen. The environmental benefits of this technology includes the utilization of renewable resources and reduction of greenhouse gas emissions compared to fossil fuel-based hydrogen production. Economically, biomass gasification offers a feasible pathway for decentralized hydrogen production, potentially lowering transportation costs and enhancing energy security, especially in biomass-rich regions. However, the deployment of biomass gasification technology is not void of challenges – some common challenges with biomass gasification technology include coping with the variability of biomass feedstock, tar formation, and the need for technological advancements to improve efficiency and scalability. This paper also discusses ongoing research and potential innovations aimed at overcoming these obstacles, ensuring biomass gasification's viability as a key player in the future hydrogen economy. Through case studies and real-world applications, this paper illustrates the practical implementation and successes of biomass gasification projects, offering valuable insights into best practices and lessons learned. In conclusion, biomass gasification stands out as a sustainable and economically viable solution for hydrogen production, with the potential to significantly advance global clean energy goals. Keywords: Biomass, Gasification, Hydrogen, Production.    

    

* Operando Studies on Solid Oxide Ceria Electrodes during CO2 Electroreduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400541254
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Solid Oxide Fuel Cells, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-b3lvx-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400541254"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400541254"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400541254"))][Get cited by]]

OpenAlex: https://openalex.org/W4400541254 (Open access: False)
    
[[https://openalex.org/A5047234101][Vipin Kamboj]], [[https://openalex.org/A5090870177][Soham Raychowdhury]], [[https://openalex.org/A5013829218][Chinmoy Ranjan]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-b3lvx-v2 
     
Abstract: CeOx-YSZ electrode performed well for CO2 electro-reduction in both pure CO2 and CO2 (+H2) feeds.. In pure CO2, operando Raman and online mass spectroscopy studies revealed that, upon application of the bias, CO production correlated with the reduction of Ce4+ sites to Ce3+ sites as evidenced by decay in the intensity of the Raman band at 450 cm-1 (α). The electronic conductivity increased with applied bias due to an increase in Ce3+ sites. The addition of H2 (~5%) resulted in reverse Water Gas Shift reaction and an additional Raman band at 480 cm-1 (φ). The CO formation was more facile in presence of H2 at a lower bias compared to the pure CO2 stream. The electronic conductivity showed a slight dip at low biases (5% H2) due to the reoxidation of Ce3+ sites to Ce4+-H- (hydridic) sites. Both H2 and CO2 concentrations positively correlated with CO formation and supressed H2O electrolysis. First principles-based calculations indicate that adsorption of H into bulk makes it easier to create oxygen defect in CeO2 making the creation of Ce3+ sites easier. When adsorbed around oxygen defects the H acquires a hydridic (H-) nature. The φ band is likely to be associated with phonon modes containing H adsorbed around undefective sites. No coking was observed in both pure CO2 and CO2 (+H2) feed streams.    

    

* Global Trends in the Research and Development of Petrochemical Waste Gas from 1981 to 2022  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400578462
:TOPICS: Future Development of China's Coal Industry, Global Methane Emissions and Impacts, Technological Development in Mineral Resource Sector
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16145972")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400578462"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400578462"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400578462"))][Get cited by]]

OpenAlex: https://openalex.org/W4400578462 (Open access: True)
    
[[https://openalex.org/A5041112199][Mengting Wu]], [[https://openalex.org/A5100432020][Wei Liu]], [[https://openalex.org/A5025280962][Zhifei Ma]], [[https://openalex.org/A5023381435][Tian Qin]], [[https://openalex.org/A5066922088][Ying Feng]], [[https://openalex.org/A5100747319][Yalan Zhang]], [[https://openalex.org/A5103257557][Ning Cao]], [[https://openalex.org/A5012168017][Xianchuan Xie]], [[https://openalex.org/A5102681086][Sunlin Chi]], [[https://openalex.org/A5102718620][Jinying Xu]], [[https://openalex.org/A5028541318][一朗 漆崎]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16145972 
     
As a highly energy-intensive and carbon-emitting industry with significant emissions of volatile organic compounds (VOCs), the petroleum and chemical industry is a major contributor to the global greenhouse effect and ozone layer destruction. Improper treatment of petrochemical waste gas (PWG) seriously harms human health and the natural environment. This study uses CiteSpace and VOSviewer to conduct a scientometric analysis of 1384 scholarly works on PWG and carbon sequestration published between 1981 and 2022, revealing the basic characteristics, knowledge base, research topic evolution, and research hotspots of the field. The results show the following: (1) In the early stages of the petrochemical industry, it was processed tail gas, plant leakage waste gas, and combustion flue gas that were investigated in PWG research. (2) Later, green environmental protection technology was widely studied in the field of PWG treatment, such as biotechnology, catalytic oxidation technology, membrane separation technology, etc., in order to achieve efficient, low energy consumption and low emissions of waste gas treatment, and the number of publications related to this topic has increased rapidly. In addition, researchers studied the internet of things and technology integration, such as the introduction of artificial intelligence, big data analysis, and other technologies, to improve the accuracy and efficiency of exhaust gas monitoring, control, and management. (3) The department has focused on how to reduce emissions by optimizing petrochemical process lines or improving energy efficiency. Emission reduction and low-carbon transition in the petrochemical industry will become the main trend in the future. Switching from renewable carbon to feedstock carbon derived from captured carbon dioxide, biomass, or recycled chemicals has become an attractive strategy to help curb emissions from the chemical industry. The results of our analysis can provide funding agencies and research groups with information to better understand the global trends and directions that have emerged in this field from 1981 to 2022 and serve as a reference for future research.    

    

* Hydrochar from Pine Needles as a Green Alternative for Catalytic Electrodes in Energy Applications  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400522909
:TOPICS: Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29143286")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400522909"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400522909"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400522909"))][Get cited by]]

OpenAlex: https://openalex.org/W4400522909 (Open access: True)
    
[[https://openalex.org/A5001983808][Assunta Marrocchi]], [[https://openalex.org/A5092836299][Elisa Cerza]], [[https://openalex.org/A5104347753][Suhas Chandrasekaran]], [[https://openalex.org/A5026150162][Emanuela Sgreccia]], [[https://openalex.org/A5000133415][S. Kačiulis]], [[https://openalex.org/A5056568396][Luigi Vaccaro]], [[https://openalex.org/A5050200451][Suanto Syahputra]], [[https://openalex.org/A5034601766][Florence Vacandio]], [[https://openalex.org/A5054885663][Philippe Knauth]], [[https://openalex.org/A5082179334][Maria Luisa Di Vona]], Molecules/Molecules online/Molecules annual. 29(14)] 2024. https://doi.org/10.3390/molecules29143286 
     
Hydrothermal carbonization (HTC) serves as a sustainable method to transform pine needle waste into nitrogen-doped (N-doped) hydrochars. The primary focus is on evaluating these hydrochars as catalytic electrodes for the oxygen reduction reaction (ORR) and carbon dioxide reduction reaction (CO2RR), which are pivotal processes with significant environmental implications. Hydrochars were synthesized by varying the parameters such as nitrogen loading, temperature, and residence time. These materials were then thoroughly characterized using diverse analytical techniques, including elemental analysis, density measurements, BET surface area analysis, and spectroscopies like Raman, FTIR, and XPS, along with optical and scanning electron microscopies. The subsequent electrochemical assessment involved preparing electrocatalytic inks by combining hydrochars with an anion exchange ionomer (AEI) to leverage their synergistic effects. To the best of our knowledge, there are no previous reports on catalytic electrodes that simultaneously incorporate both a hydrochar and AEI. Evaluation metrics such as current densities, onset and half-wave potentials, and Koutecky–Levich and Tafel plots provided insights into their electrocatalytic performances. Notably, hydrochars synthesized at 230 °C exhibited an onset potential of 0.92 V vs. RHE, marking the highest reported value for a hydrochar. They also facilitated the exchange of four electrons at 0.26 V vs. RHE in the ORR. Additionally, the CO2RR yielded valuable C2 products like acetaldehyde and acetate. These findings highlight the remarkable electrocatalytic activity of the optimized hydrochars, which could be attributed, at least in part, to their optimal porosity.    

    

* Altitude controller influence on environmental and economic performance of NGV fuel-powered engines  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400659711
:TOPICS: Transportation Engineering and Maintenance, Advancements in Automotive Engineering and Fuel Technology, Estimating Vehicle Fuel Consumption and Emissions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/e3sconf/202454907010")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400659711"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400659711"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400659711"))][Get cited by]]

OpenAlex: https://openalex.org/W4400659711 (Open access: True)
    
[[https://openalex.org/A5055770319][A.R. Simonyan]], [[https://openalex.org/A5085115818][Karapet Mosikyan]], [[https://openalex.org/A5070850806][Razmik Balayan]], [[https://openalex.org/A5085749289][V.A. Shaghoyan]], E3S web of conferences. 549(None)] 2024. https://doi.org/10.1051/e3sconf/202454907010 
     
The relevance of research is conditioned by the need to ensure efficient operation of the internal combustion engine ICE on NGV fuel at different altitudes above sea level, where there is atmospheric air rarefaction up to 20÷25%. This direction is dictated by the fact that when transferring the ICE operation from gasoline to gas-engine fuel, the engine power decreases from 5 to 15%, moreover, the atmospheric air rarefaction leads to an even greater reduction in engine power and ultimately reduces the performance of the vehicle. Due to violation of the process of combustion of gas-air charge in the cylinder is formed a large amount of carbon monoxide (CO). Research objective is to develop and propose a method of providing such a stoichiometric, fractional composition of the gas-air charge, which will ensure the restoration of the lost power of ICE and provide the optimal value of traction-dynamic characteristics of the car, without increasing toxic emissions. Research object: Variable crosssectional area of the intake manifold path (ICE), adjustable lumen for atmospheric air intake, atmospheric air pressure sensors adjustable diaphragm with stepper motor. Research methods: analytical modeling of the relationship of the aperture diameter depending on the altitude of the terrain above sea level, on the number of revolutions of the ICE, on the density and temperature of the ambient air. The process of combustion of the gas-air charge in the combustion chamber will be evaluated by the fractional composition of the exhaust, exhaust gases. Research results: Qualitative and quantitative assessment of the application of altitude corrector on the ICE operation mode, stability of the value of excess air ratio at different altitudes above sea level, formation of toxic gas, carbon monoxide, as well as carbon dioxide, hydrocarbon, oxygen, etc. is given.    

    

* Climate Change Impacts on Legume Physiology and Ecosystem Dynamics: A Multifaceted Perspective  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400643467
:TOPICS: Impacts of Elevated CO2 and Ozone on Plant Physiology, Nutritional and Functional Potential of Ancient Grains, Intercropping in Agricultural Systems
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16146026")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400643467"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400643467"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400643467"))][Get cited by]]

OpenAlex: https://openalex.org/W4400643467 (Open access: True)
    
[[https://openalex.org/A5018365780][Kirtan Dave]], [[https://openalex.org/A5101216001][Anand Kumar]], [[https://openalex.org/A5021874704][N.K. Davé]], [[https://openalex.org/A5042106860][Mukul Jain]], [[https://openalex.org/A5064312420][Parmdeep Singh Dhanda]], [[https://openalex.org/A5101735071][Alpa Yadav]], [[https://openalex.org/A5066650872][Prashant Kaushik]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16146026 
     
As valuable sources of plant-based protein, leguminous vegetables (grain legumes) are essential for global food security and contribute to body growth and development in humans as well as animals. Climate change is a major challenge for agriculture development that creates major problems for the growth and development of plants. However, legume productivity is threatened by climate change factors, including rising temperatures, shifting precipitation patterns, increased atmospheric carbon dioxide levels, intensified extreme events, and altered pest/pathogen activity. This review synthesizes approximately 136 studies to assess the climate effects on major legume crops. Under all the global emissions trajectories, the mean temperatures are projected to rise beyond the optimal legume growing thresholds by 2050, carrying yield reductions between 10 and 49% for beans, soybeans, cowpeas, and lentils without adaptation measures. The elevated carbon dioxide may transiently enhance the yields up to 18%, but the benefits dramatically decline above 550 ppm and cannot offset the other climate impacts. Altered rainfall along with recurrent drought and heat waves are also expected to decrease the legume crop yields, seed quality, and soil nitrogen levels worldwide. Furthermore, the proliferation of legume pests and fungal diseases poses significant risks, amplified by climate shifts in 84% of the reviewed studies. These multifaceted impacts threaten the productivity gains in leguminous vegetables essential to sustainably meeting the global protein demand. Realizing resilience will require the accelerated development of heat/drought-tolerant legume varieties, enhanced climate-informed agronomic practices, strong policy interventions, and social safety nets explicitly supporting legume producers, in addition to the policies/steps that governments are taking to address the challenges of the climate crisis. This review highlights the essential adaptations and mechanisms required for legume crops to thrive and fulfill their significant roles in global nutrition. It explores how these crops can be improved to better withstand the environmental stresses, enhance their nutritional profiles, and increase their yields. Additionally, the review discusses the importance of legumes in sustainable agriculture and food security, emphasizing their potential to address the future challenges in feeding the growing global population. By focusing on these critical aspects, the review aims to underscore the importance of legumes in ensuring a healthy and sustainable food supply.    

    

* Decoupling CO2 Effects from Electrochemistry: A Mechanistic Study of Copper Catalyst Degradation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400496653
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-3rbfp")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400496653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400496653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400496653"))][Get cited by]]

OpenAlex: https://openalex.org/W4400496653 (Open access: False)
    
[[https://openalex.org/A5076554343][Rui Serra-Maia]], [[https://openalex.org/A5089128933][Joel B. Varley]], [[https://openalex.org/A5062728883][Stephen E. Weitzner]], [[https://openalex.org/A5038619483][Henry Yu]], [[https://openalex.org/A5082022175][Rongpei Shi]], [[https://openalex.org/A5060567990][J. Biener]], [[https://openalex.org/A5042139840][Sneha A. Akhade]], [[https://openalex.org/A5075870873][Eric A. Stach]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-3rbfp 
     
Copper-based nanoparticles are key electrocatalysts for CO2 electrochemical reduction (CO2 ER) to liquid fuels and other value-added products. However, the copper catalyst can undergo rapid electrochemical corrosion, leading to a loss of catalyst material, fluctuations in the reaction conditions and increasing operational costs. We establish a mechanistic understanding of this detrimental process using in situ electrochemical electron microscopy and density functional theory (DFT). We find that copper corrosion can occur in the presence of CO2 in electroless conditions and before the onset potentials required for CO2 ER. The effects are isolated from pH changes resulting from dissolved CO2. Particles of corroded copper have oxidized surfaces, in contrast to copper surfaces exposed to CO2-free electrolytes. DFT calculations identify multiple routes by which CO2 can behave as a dissolution agent for copper and copper-oxide surfaces and suggest that formate-intermediates are a key driver of corrosion. This study highlights microenvironment-based factors that affect copper performance and degradation, facilitating strategies to inhibit and reverse copper degradation during CO2 ER.    

    

* effectiveness of dolomite and Ni-catalyst mixtures for pure H 2 production by methane steam reforming via CO 2 capture  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400600053
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2007-12-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.62721/diffusion-fundamentals.7.149")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400600053"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400600053"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400600053"))][Get cited by]]

OpenAlex: https://openalex.org/W4400600053 (Open access: False)
    
[[https://openalex.org/A5022363288][N. Zh. Seitkaliyeva]], [[https://openalex.org/A5060614094][Nader Jand]], [[https://openalex.org/A5034886304][Pier Ugo Foscolo]], No host. 7(None)] 2007. https://doi.org/10.62721/diffusion-fundamentals.7.149 
     
High hydrogen yields have been obtained continuously from steam reforming of methane coupled with simultaneous CO2 capture[1], at lower temperature (630oC) and pressure (1 atm) than those typical of traditional processes (800-900oC,15-30 atm), using calcined dolomite and a pulverized commercial Ni catalyst, in a single step. On the other hand, a pure CO2 stream is obtained by subsequent regeneration of the sorbent, which could be stored. A bubbling fluidized bed contained in a quartz vessel was operated batchwise. First, the durability of a dolomite in multi-cycle CO2 sorption/desorption runs has been investigated: a remarkable reduction of dolomite activity is observed after the first calcination, but substantially stable activity was conserved up to the fifth cycle. Then the performance of sorption enhanced catalytic steam reforming of methane to pure hydrogen has been evaluated. Two well distinct operation regimes have been found: before dolomite saturation, H2 concentration in the dry product gas remained stable at 94-96%, and CO2 was completely converted into calcium carbonate; after a short breakthrough period, concentration of H2 at the exit of the reactor reduced its value that became approximately equal to the equilibrium value expected for methane reforming and water gas shift reactions.    

    

* The Impact of Smart Home Technologies on Energy Efficiency, Cost Savings, and Environmental Benefits  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400688412
:TOPICS: Demand Response in Smart Grids, Smart Cities: Innovations and Challenges, Impact of Nighttime Light Data on Various Fields
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.55529/jeet.44.21.32")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400688412"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400688412"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400688412"))][Get cited by]]

OpenAlex: https://openalex.org/W4400688412 (Open access: False)
    
[[https://openalex.org/A5104603533][C. Ukpene Patience]], [[https://openalex.org/A5104603534][Tessy N. Apaokueze]], Journal of energy engineering and thermodynamics. None(44)] 2024. https://doi.org/10.55529/jeet.44.21.32 
     
The results of this study addressed the effectiveness of smart home technologies in terms of energy consumption, cost reduction, and environmental advantages in Nigerian homes. Given the growing energy requirements and concern for the environment, assessing the efficiency of such technologies is critical for socioeconomic development. We collected data using a combination of surveys and statistical analysis in five major Nigerian cities: Lagos, Abuja, Kano, Port Harcourt, and Enugu. We evaluated smart home technologies such as smart thermostats, lighting systems, appliances, plugs, and energy monitoring systems based on their energy savings (%), monthly cost savings (NGN), kilogram of CO2 emissions cut, and percent adoption. We used descriptive analysis and regression modeling to analyze the data collected from the respondents. The introduction of smart technologies reduced general energy use by fifteen to twenty-five percent, with smart appliances recording the highest reduction of up to 25%. This feature demonstrated how monthly cost savings varied depending on the technology and geographical location, resulting in significant increases of up to 4000 NGN per household, each household saw a reduction in CO2 emissions by 500 kg to 700 kg annually, resulting in significant environmental benefits. According to the studies, smart home technologies can help promote energy conservation and therefore reduce CO2 emissions in Nigerian households. However, there are still widely recognized obstacles, like high initial costs and a low level of awareness. offering financial incentives, improving Information Promotion of existing policies and overhauling the distribution systems to increase the pace of uptake and impact returns.    

    

* Modulating the Electrocatalytic CO2-CO Performance by Ag Morphology  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400520478
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/2162-8777/ad620f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400520478"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400520478"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400520478"))][Get cited by]]

OpenAlex: https://openalex.org/W4400520478 (Open access: True)
    
[[https://openalex.org/A5102859143][Guanhua Xu]], [[https://openalex.org/A5104347657][xudong qiu]], [[https://openalex.org/A5104347658][xiaoguang li]], ECS journal of solid state science and technology. None(None)] 2024. https://doi.org/10.1149/2162-8777/ad620f 
     
Abstract Highly selective conversion of CO2 into CO molecules remains a major challenge in electrocatalytic CO2 reduction reactions, and metallic silver-based materials have great potential. However, the selectivity and activity of traditional silver (Ag)-based materials cannot reach the desired level, and the development of new Ag-based materials has become a hot research topic. Here, novel ag-glomerated spore-shaped Ag nanomaterials are reported for the efficient reduction of CO2 to CO. The unique nanostructures endowed with larger specific surface area, and the spore-like dispersed Ag nanoparticles (NPs) have more unsaturated Ag sites, which endowed the catalysts with higher intrinsic activity. Electrochemical tests show that spore-like Ag can obtain a Faraday efficiency (FE) of 95.6% at -1 V vs. RHE, which is much higher than that of Ag nanowires (NWs) (73%) and ordinary Ag NPs (83%) synthesized in the same period. By using the three different morphologies of Ag synthesized as a research platform and statistically comparing the FE in the corresponding voltage interval, we obtained the influence of morphology effect on the selectivity of CO product production by electrocatalytic CO2 production over Ag-based catalysts, which can be further used as a guideline for catalyst development.    

    

* Fabrication and Characterization of PLA/PBAT Blends, Blend-Based Nanocomposites, and Their Supercritical Carbon Dioxide-Induced Foams  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400486574
:TOPICS: Polymer Foaming with Supercritical Carbon Dioxide, Biodegradable Polymers as Biomaterials and Packaging, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/polym16141971")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400486574"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400486574"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400486574"))][Get cited by]]

OpenAlex: https://openalex.org/W4400486574 (Open access: True)
    
[[https://openalex.org/A5039296220][Kartik Behera]], [[https://openalex.org/A5101257061][Chien-Hsing Tsai]], [[https://openalex.org/A5101395607][Xiang-Bo Liao]], [[https://openalex.org/A5038620130][Fang-Chyou Chiu]], Polymers. 16(14)] 2024. https://doi.org/10.3390/polym16141971 
     
In this study, a twin-screw extruder was used to fabricate poly(lactic acid) (PLA)/poly(butylene adipate-co-terephthalate) (PBAT) blends and blend-based nanocomposites with carbon nanotube (CNT) or nanocarbon black (CB) as nanofillers. The fabricated samples were subsequently treated with supercritical carbon dioxide (scCO2) to fabricate the corresponding foams. Bi-phasic morphology and selective distribution of CNTs or CBs in the PBAT phase were observed in the blends/composites through scanning electron microscopy. After the scCO2 treatment, the selective foaming of the PBAT phase in the prepared blends/composites was confirmed. The cellular structure of PBAT phase in scCO2-treated blends is similar to the size/shape of PBAT domains in untreated blends or treated neat PBAT foam. The addition of CNTs or CBs in the blends led to a slight reduction in cell size of the foamed PBAT phase, demonstrating CNT/CB-induced cell nucleation. Differential scanning calorimetry (DSC) results showed that CNTs and CBs played as nucleating agents and increased the initial crystallization temperature up to 14 °C compared with neat PBAT for PBAT in different composites during cooling. The scCO2 treatment induced the bimodal stability of PBAT crystals in different samples, which melted mainly in two temperature regions in DSC studies. Thermogravimetric analyses revealed that compared with parent blends, the addition of CNTs or CBs increased the temperature at 80 wt.% loss (degradation of PBAT portion) up to 6 °C. The electrical resistivity decreased by more than six orders of magnitude for certain CNT- or CB-added composites compared with the parent blends. The hardness of the blends slightly increased after forming the corresponding composites and then declined after the scCO2 treatment.    

    

* Benchmarking ionomers for CO2 electroreduction to multicarbon products in zero-gap electrolyzers  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400570987
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta02332c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400570987"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400570987"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400570987"))][Get cited by]]

OpenAlex: https://openalex.org/W4400570987 (Open access: False)
    
[[https://openalex.org/A5088104427][Fanxin Zeng]], [[https://openalex.org/A5030347659][Huihua Deng]], [[https://openalex.org/A5069799668][Mengjiao Zhuansun]], [[https://openalex.org/A5036016778][Wenzhi Teng]], [[https://openalex.org/A5100449559][Yuhang Wang]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta02332c 
     
Electrochemical CO2 reduction reaction (CO2RR) is an emerging carbon utilization technology. The use of ionomers in fabricating the catalytic electrode was found to exert substantial effects on activity and product...    

    

* Interface Engineering and Oxygen Vacancy Derived from Plasma-treated Cu2O Synergistically Enhancing Electrocatalytic CO2-to-C2+ Conversion  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400640883
:TOPICS: Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta03492a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400640883"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400640883"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400640883"))][Get cited by]]

OpenAlex: https://openalex.org/W4400640883 (Open access: False)
    
[[https://openalex.org/A5100444820][Xiaogang Wang]], [[https://openalex.org/A5100541793][Xue Yao]], [[https://openalex.org/A5014251891][Subhajit Jana]], [[https://openalex.org/A5101605827][Yongzan Zhou]], [[https://openalex.org/A5080363764][Chunlan Qin]], [[https://openalex.org/A5063417159][Hongwei Shou]], [[https://openalex.org/A5084441836][Youchao Teng]], [[https://openalex.org/A5100353673][Hao Chen]], [[https://openalex.org/A5100416420][Lidong Zhang]], [[https://openalex.org/A5077238261][Chandra Veer Singh]], [[https://openalex.org/A5054969550][Zhongchao Tan]], [[https://openalex.org/A5003768009][Yimin A. Wu]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta03492a 
     
Electrocatalytic CO2 reduction (ECR) into value-added chemicals and fuels helps tackle the challenges of the energy crisis and global warming. However, this strategy relies heavily on the rational design of...    

    

* Environmental Policies and Countermeasures for Phase-Out of Ozone-Depleting Substances (ODS) over the Last 30 Years: Case Study in Taiwan  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400686943
:TOPICS: Atmospheric Aerosols and their Impacts
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.20944/preprints202407.1142.v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400686943"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400686943"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400686943"))][Get cited by]]

OpenAlex: https://openalex.org/W4400686943 (Open access: True)
    
[[https://openalex.org/A5087591655][Wen‐Tien Tsai]], No host. None(None)] 2024. https://doi.org/10.20944/preprints202407.1142.v1 
     
It is well established that the reaction cycles involving some halogenated alkanes (so-called ozone-depleting substances, ODS) contribute to the depletion of ozone in the stratosphere, thus causing the Montreal Protocol (initially signed in 1987) and later amendments. The Protocol called for the scheduled phase-out of ODS, including chlorofluorocarbons (CFC), hydrochloro-fluorocarbons (HCFC), carbon tetrachloride (CCl4), halon, methyl chloroform (CH3CCl3), me-thyl chloride (CH3Cl), and even hydrofluorocarbons (HFCs). In view of the urgent importance of ozone layer protection to the globally ecological environment, the Taiwan government took regulatory actions on reducing ODS consumption since 1993 by the joint-venture of the central competent authorities. Under the regulatory requirements and the industry’s efforts by adopt-ing the alternatives to ODS and abatement technologies, the phase-out of some ODS (i.e., CFC, CCl4, halon, and CH3CCl3) have been achieved prior to 2010. The consumptions of HCFCs and methyl chloride have been significantly declined over the past three decades (1993-2022). However, HFC emission indicated a V-type variation during the period. Due to the local pro-duction and extensive use of HFC in Taiwan, its emissions increased from 663 kilotons of carbon dioxide equivalents (CO2eq) in 1993 to 2,330 kilotons of CO2eq in 2001, and then decreased to 373 kilotons of CO2eq in 2011. Since then, the emissions of HFC largely used as the alternatives to ODS showed an upward trend, increasing to 1,555 kilotons of CO2eq in 2022. To be in compliance with the Kigali Amendment (KA-2015) to the Montreal Protocol for mitigating global warming, the Taiwan government has taken regulatory actions in reducing the consumption of some HFC substances with high global warming potential (GWP) under the authorization of the Climate Change Response Act in 2023, aiming at the baseline consumption in 2024 by 80 % reduction by 2045.    

    

* Kinetics Investigation of Copper Ore Oxygen Carrier for Chemical Looping Combustion  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400581486
:TOPICS: Chemical-Looping Technologies, Sulfur Compounds Removal Technologies, Global Impact of Gas Flaring
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/fire7070245")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400581486"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400581486"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400581486"))][Get cited by]]

OpenAlex: https://openalex.org/W4400581486 (Open access: True)
    
[[https://openalex.org/A5024815756][Xin Tian]], [[https://openalex.org/A5065694816][Mingze Su]], [[https://openalex.org/A5040961284][Haibo Zhao]], Fire. 7(7)] 2024. https://doi.org/10.3390/fire7070245 
     
Chemical looping combustion (CLC) has been validated as one of the most promising technologies for fossil fuel combustion, which can produce high-purity CO2 streams ready for capture and sequestration in power production. The selection of an appropriate oxygen carrier is one of the most important issues for the CLC process, and the reduction kinetics investigation of the oxygen carrier with fuel gas can provide the basis for CLC reactor design and simulation optimization. In this study, copper ore was chosen as an oxygen carrier, and the oxygen release property of copper ore under a nitrogen environment at various temperatures (1073–1193 K) was first investigated in a thermogravimetric analyzer (TGA). Subsequently, the reduction kinetics of copper ore with CO and H2 were evaluated by the TGA at temperatures ranging from 773 K to 1073 K, using a continuous stream of 5, 10, 15, 20, 25, and 30 vol. % of CO or H2 balanced by CO2 or N2. It was found that the reaction rates of these reactions accelerated with the increase in temperature and fuel gas concentration in inlet gas. Both the oxygen release process of copper ore and the reduction process of copper ore with reducing gases can be described by the unreacted shrinking core model (USCM). The reaction mechanism function for the oxygen-releasing and reduction process of copper ore oxygen carrier was varied. The activation energy of the oxygen-releasing process, reduction process with CO, and reduction process with H2 were calculated as 99.35, 5.08, and 4.28 kJ/mol, respectively. The pre-exponential factor ranged from 1.96 × 10−1 to 1.84 × 103. The reaction order depended on the fuel gas, which was 1 and 0.86, respectively, for reaction with CO and H2.    

    

* A quantitative study on the impact of a community falls pharmacist role, on medicines optimisation in older people at risk of falls  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400655149
:TOPICS: Polypharmacy and Inappropriate Medication Use in Elderly, Health Economics and Quality of Life Assessment, Gait Analysis and Fall Prevention in Elderly
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1186/s12877-024-05189-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400655149"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400655149"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400655149"))][Get cited by]]

OpenAlex: https://openalex.org/W4400655149 (Open access: True)
    
[[https://openalex.org/A5024197865][Paula Crawford]], [[https://openalex.org/A5016358721][Robert C. Plumb]], [[https://openalex.org/A5030586417][Paula Burns]], [[https://openalex.org/A5022855565][Stephen Flanagan]], [[https://openalex.org/A5001150636][Carole Parsons]], BMC geriatrics. 24(1)] 2024. https://doi.org/10.1186/s12877-024-05189-6 
     
Abstract Background The World Falls guidance includes medication review as part of its recommended multifactorial risk assessment for those at high risk of falling. Use of Falls Risk Increasing Drugs (FRIDs) along with polypharmacy and anticholinergic burden (ACB) are known to increase the risk of falls in older people. Method The impact of a community falls pharmacist within a hospital Trust, working as part of a multi-professional community falls prevention service, was evaluated in 92 people aged 65 years or older, by analysing data before and after pharmacist review, namely: number and type of FRIDs prescribed; anticholinergic burden score using ACBcalc ® ; appropriateness of medicines prescribed; bone health review using an approved too; significance of clinical intervention; cost avoidance, drug cost savings and environmental impact. Results Following pharmacist review, there was a reduction in polypharmacy (mean number of medicines prescribed per patient reduced by 8%; p < 0.05) and anticholinergic burden score (average score per patient reduced by 33%; p < 0.05). Medicines appropriateness improved (Medicines Appropriateness Index score decreased by 56%; p < 0.05). There were 317 clinically significant interventions by the community falls pharmacist. One hundred and one FRIDs were deprescribed. Annual cost avoidance and drug cost savings were £40,689-£82,642 and avoidable carbon dioxide (CO 2 ) emissions from reducing inappropriate prescribing amounted to 941 kg CO 2 . Conclusion The community falls pharmacist role increases prescribing appropriateness in the older population at risk of falls, and is an effective and cost-efficient means to optimise medicines in this population, as well as having a positive impact on the environment.    

    

* Modelling boreal forest's mineral soil and peat C dynamics with the Yasso07 model coupled with the Ricker moisture modifier  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400549125
:TOPICS: Carbon Dynamics in Peatland Ecosystems, Arctic Permafrost Dynamics and Climate Change, Impact of Climate Change on Forest Wildfires
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/gmd-17-5349-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400549125"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400549125"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400549125"))][Get cited by]]

OpenAlex: https://openalex.org/W4400549125 (Open access: True)
    
[[https://openalex.org/A5050075036][Boris Ťupek]], [[https://openalex.org/A5067379306][Aleksi Lehtonen]], [[https://openalex.org/A5056790118][Alla Yurova]], [[https://openalex.org/A5059556259][Rose Abramoff]], [[https://openalex.org/A5070863488][Bertrand Guenet]], [[https://openalex.org/A5090196946][Elisa Bruni]], [[https://openalex.org/A5054011647][Samuli Launiainen]], [[https://openalex.org/A5066424602][Mikko Peltoniemi]], [[https://openalex.org/A5027517395][Shoji Hashimoto]], [[https://openalex.org/A5017791007][Xianglin Tian]], [[https://openalex.org/A5089612595][Juha Heikkinen]], [[https://openalex.org/A5038310275][Kari Minkkinen]], [[https://openalex.org/A5014546224][Raisa Mäkipää]], Geoscientific model development. 17(13)] 2024. https://doi.org/10.5194/gmd-17-5349-2024 
     
Abstract. As soil microbial respiration is the major component of land CO2 emissions, differences in the functional dependence of respiration on soil moisture among Earth system models (ESMs) contributes significantly to the uncertainties in their projections. Using soil organic C (SOC) stocks and CO2 data from a boreal forest–mire ecotone in Finland and Bayesian data assimilation, we revised the original precipitation-based monotonic saturation dependency of the Yasso07 soil carbon model using the non-monotonic Ricker function based on soil volumetric water content. We fit the revised functional dependency of moisture to the observed microbial respiration and SOC stocks and compared its performance against the original Yasso07 model and the version used in the JSBACH land surface model with a reduction constant for decomposition rates in wetlands. The Yasso07 soil C model coupled with the calibrated unimodal Ricker moisture function with an optimum in well-drained soils accurately reconstructed observed SOC stocks and soil CO2 emissions and clearly outperformed previous model versions on paludified organo-mineral soils in forested peatlands and water-saturated organic soils in mires. The best estimate of the posterior moisture response of decomposition used both measurements of SOC stocks and CO2 data from the full range of moisture conditions (from dry and xeric to wet and water-saturated soils). We observed unbiased residuals of SOC and CO2 data modelled with the moisture optimum in well-drained soils, suggesting that this modified function accounts more precisely for the long-term SOC change dependency according to ecosystem properties as well as the contribution of short-term CO2 responses including extreme events. The optimum moisture for decomposition in boreal forests was found in well-drained soils instead of the mid-range between dry and water-saturated conditions as is commonly assumed among soil C and ESMs. Although the unimodal moisture modifier with an optimum in well-drained soils implicitly incorporates robust biogeochemical mechanisms of SOC accumulation and CO2 emissions, it needs further evaluation with large-scale data to determine if its use in land surface models will decrease the uncertainty in projections.    

    

* Sustainable Sludge Management in China: Quantifying GHG Emissions and Exploring Its Reduction Strategies  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400668208
:TOPICS: Solid Waste Management, Phosphorus Recovery and Sustainable Management, Long-term Management of Landfills and Waste
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/pr12071481")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400668208"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400668208"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400668208"))][Get cited by]]

OpenAlex: https://openalex.org/W4400668208 (Open access: True)
    
[[https://openalex.org/A5043903036][Dongming Hu]], [[https://openalex.org/A5102626460][Peng Jiang]], [[https://openalex.org/A5101645463][Yipei Chen]], [[https://openalex.org/A5090125446][Fuyan Gao]], [[https://openalex.org/A5019624996][Shuai Liu]], Processes. 12(7)] 2024. https://doi.org/10.3390/pr12071481 
     
This study aims to evaluate the emissions of greenhouse gases (GHGs) stemming from the sludge treatment sector in China and to investigate the feasibility of novel technologies in curtailing these emissions, with the aim of fostering sustainable sludge management methodologies. Employing a life-cycle assessment (LCA) methodology, the research computed the comprehensive GHG emissions resulting from sludge treatment, taking into consideration diverse elements such as treatment techniques (e.g., landfills, incineration, and land application) and the geographical variations among China’s 660 municipalities. Findings indicate that the total amount of GHG emissions from sludge treatment amounted to 18.54 Mt CO2-eq in 2017, with incineration registering the highest emissions (10,011.53 kg CO2-eq/t dry sludge (DS)), followed by landfills (717.51 kg CO2-eq/t DS) and land application (276.41 kg CO2-eq/t DS). The geographical dispersion of emissions characteristics reveal notable regional disparities, with the top 1% of cities responsible for 34.2% of the overall emissions. The concentration of emissions in the top 1 percent of cities underscores the necessity for tailored mitigation measures that consider localized sustainable development challenges. Principal component analysis (PCA) demonstrates that economic determinants and treatment scales exert substantial influence on emissions, underscoring the imperative of aligning Sustainable Development Goals (SDGs) with economic advancement. To curtail the carbon footprint associated with sludge treatment and enhance sustainability, the study evaluated the emission mitigation potential and expenses of diverse technologies, encompassing thermal conversion, anaerobic digestion, hydrothermal treatment, and wet oxidation. These technologies have the capacity to slash GHG emissions by 0.09–0.46 t CO2-eq/t DS in comparison to traditional approaches, while concurrently advancing resource recuperation and principles of circular economy. For instance, gasification could diminish GHG emissions by 0.33–0.46 t CO2-eq/t DS, whereas anaerobic digestion could yield reductions of 0.09–0.30 t CO2-eq/t DS. The implementation of these innovative technologies across 660 Chinese municipalities could potentially curtail total GHG emissions from sludge treatment by 15–40%. Nevertheless, further enhancements are imperative to refine their environmental and economic efficiency and guarantee enduring sustainability. By deploying these technologies and embracing optimization tactics, China’s sludge treatment sector can make a substantial contribution towards attaining national carbon neutrality objectives and advancing sustainable development.    

    

* Unconventional Electrocatalytic CO Conversion to C2 Products on Single‐Atomic Pd‐Agn Sites  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400581425
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202411194")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400581425"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400581425"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400581425"))][Get cited by]]

OpenAlex: https://openalex.org/W4400581425 (Open access: False)
    
[[https://openalex.org/A5073741641][Yali Ji]], [[https://openalex.org/A5046867944][Ximeng Lv]], [[https://openalex.org/A5018661235][Ruilin Wei]], [[https://openalex.org/A5045520661][Anxiang Guan]], [[https://openalex.org/A5077369965][Chao Yang]], [[https://openalex.org/A5064270074][Yaqin Yan]], [[https://openalex.org/A5102746678][Min Kuang]], [[https://openalex.org/A5100727026][Gengfeng Zheng]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/anie.202411194 
     
The electrochemical reduction of CO or CO2 into C2+ products has mostly been focused on Cu‐based catalysts. Although Ag has also been predicted as a possible catalyst for the CO‐to‐C2+ conversion from the thermodynamic point of view, however, due to its weak CO binding strength, CO rapidly desorbs from the Ag surface rather than participates in deep reduction. In this work, we demonstrate that single‐atomic Pd sites doped in Ag lattice can tune the CO adsorption behavior and promote the deep reduction of CO toward C2 products. The monodispersed Pd‐Agn sites enable the CO adsorption with both Pd‐atop (PdL) and Pd‐Ag bridge (PdAgB) configurations, which can increase the CO coverage and reduce the C−C coupling energy barrier. Under room temperature and ambient pressure, the Pd1Ag10 alloy catalyst exhibited a total CO‐to‐C2 Faradaic efficiency of ~37% at ‒0.83 V, with appreciable current densities and electrochemical stability, thus featuring unconventional non‐Cu electrocatalytic CO‐to‐C2 conversion capability.    

    

* Unconventional Electrocatalytic CO Conversion to C2 Products on Single‐Atomic Pd‐Agn Sites  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400581880
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202411194")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400581880"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400581880"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400581880"))][Get cited by]]

OpenAlex: https://openalex.org/W4400581880 (Open access: False)
    
[[https://openalex.org/A5073741641][Yali Ji]], [[https://openalex.org/A5046867944][Ximeng Lv]], [[https://openalex.org/A5018661235][Ruilin Wei]], [[https://openalex.org/A5045520661][Anxiang Guan]], [[https://openalex.org/A5006812397][Chao Yang]], [[https://openalex.org/A5064270074][Yaqin Yan]], [[https://openalex.org/A5102746678][Min Kuang]], [[https://openalex.org/A5100727026][Gengfeng Zheng]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202411194 
     
The electrochemical reduction of CO or CO2 into C2+ products has mostly been focused on Cu‐based catalysts. Although Ag has also been predicted as a possible catalyst for the CO‐to‐C2+ conversion from the thermodynamic point of view, however, due to its weak CO binding strength, CO rapidly desorbs from the Ag surface rather than participates in deep reduction. In this work, we demonstrate that single‐atomic Pd sites doped in Ag lattice can tune the CO adsorption behavior and promote the deep reduction of CO toward C2 products. The monodispersed Pd‐Agn sites enable the CO adsorption with both Pd‐atop (PdL) and Pd‐Ag bridge (PdAgB) configurations, which can increase the CO coverage and reduce the C−C coupling energy barrier. Under room temperature and ambient pressure, the Pd1Ag10 alloy catalyst exhibited a total CO‐to‐C2 Faradaic efficiency of ~37% at ‒0.83 V, with appreciable current densities and electrochemical stability, thus featuring unconventional non‐Cu electrocatalytic CO‐to‐C2 conversion capability.    

    

* Electrochemical CO2 Reduction on Cu-Based Monatomic Alloys: A DFT Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400651340
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.langmuir.4c01246")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400651340"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400651340"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400651340"))][Get cited by]]

OpenAlex: https://openalex.org/W4400651340 (Open access: False)
    
[[https://openalex.org/A5074043148][Xiaojiao Li]], [[https://openalex.org/A5004763124][Liyun Jiang]], [[https://openalex.org/A5101430072][Yong Zhou]], [[https://openalex.org/A5017725939][Qi Yu]], Langmuir. None(None)] 2024. https://doi.org/10.1021/acs.langmuir.4c01246 
     
In recent years, single-atom alloy catalysts (SAAs) have received much attention due to the combination of structural features of both single-atom and alloy catalysts, as well as their efficient catalytic activity, high selectivity, and high stability in various chemical reactions. In this work, we designed a series of Cu-based SAAs by doping isolated 3d transition metal (TM1) atoms on the surface of Cu(111) (TM1 = Fe, Co, Ru, Rh, Os and Ir), in which Ir1/Cu(111) SAAs are considered to be the most stable among 3d-series SAAs due to their optimal binding energy (Eb). The density of states of SAAs have been systematically investigated to further discuss structural properties. Based on density functional theory calculations, the activity and selectivity of Ir1/Cu(111) SAAs are investigated for electrocatalytic CO2 reduction reaction (CO2RR). The initial hydrogenation of CO2 on Ir1/Cu(111) SAAs can form *CO intermediates, which will be further to CH4 production by the pathway of *CO → *CHO → *CHOH → *CH2OH → *CH2 → *CH3 → CH4. This study provides theoretical insights for the rational design of selective Cu-based monatomic alloy catalysts.    

    

* Polymers and their Use in Ecological Construction Materials  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400492405
:TOPICS: Materials Science and Technology
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.20944/preprints202407.0804.v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400492405"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400492405"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400492405"))][Get cited by]]

OpenAlex: https://openalex.org/W4400492405 (Open access: True)
    
[[https://openalex.org/A5011839224][Adrian Ioana]], [[https://openalex.org/A5097737437][Diana Cristina Labes]], [[https://openalex.org/A5073865642][Nicolae Constantin]], [[https://openalex.org/A5054811649][Augustin Semenescu]], [[https://openalex.org/A5037160343][Roxana Marina Solea]], [[https://openalex.org/A5080237073][Daniela Alice Luta]], [[https://openalex.org/A5062571326][Alexandra Istrate]], No host. None(None)] 2024. https://doi.org/10.20944/preprints202407.0804.v1 
     
This study evaluates the efficiency of biodegradable polyurethane foams as thermal insulation materials compared to conventional materials like expanded polystyrene (EPS). Key parameters analyzed include thermal conductivity, energy savings, CO2 emission reductions, and investment payback periods. Biodegradable polyurethane foams demonstrated a thermal conductivity of 0.022 W/(m·K), significantly lower than EPS&#039;s 0.035 W/(m·K), leading to higher energy savings. Calculations reveal an annual energy saving of 443,820 kWh for polyurethane foams, compared to 441,330 kWh for EPS. Financially, polyurethane foams save approximately €53,258.4 annually, while EPS saves €52,959.6. In terms of environmental impact, polyurethane foams reduce CO2 emissions by 88,764 kg annually, versus 88,266 kg for EPS. Despite the higher initial cost of polyurethane foams (€50/m² compared to €30/m² for EPS), the payback period is remarkably short at 0.094 years (1.13 months) compared to EPS&#039;s 0.057 years (0.68 months). These findings highlight biodegradable polyurethane foams as a superior option for thermal insulation, offering significant energy, financial, and environmental benefits.    

    

* A CRITICAL EXAMINATION OF THE CONSTRUCTION SECTOR IN TURKEY IN TERMS OF SUSTAINABILITY  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400496991
:TOPICS: Sustainable Construction and Green Building, Success Factors in Project Management
:PUBLICATION_DATE: 2024-07-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.47933/ijeir.1491574")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400496991"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400496991"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400496991"))][Get cited by]]

OpenAlex: https://openalex.org/W4400496991 (Open access: False)
    
[[https://openalex.org/A5000016653][Pınar Usta]], [[https://openalex.org/A5100500198][Kamertap Cirik]], [[https://openalex.org/A5022471544][Elifnur Şakalak]], [[https://openalex.org/A5030803651][Ali Ekber SEVER]], International journal of engineering and innovative research. None(None)] 2024. https://doi.org/10.47933/ijeir.1491574 
     
The construction sector is of critical importance for economic growth and employment creation. However, it also has significant environmental impacts, including high energy consumption, extensive use of natural resources, and substantial waste production. Currently, the construction sector in Turkey accounts for 35% of the country’s total energy consumption, making it a significant energy consumer. Research conducted in European Union countries indicates that buildings are responsible for 40% of total energy consumption and 36% of total CO2 emissions. It is believed that a similar situation exists in Turkey. Furthermore, the long lifespan of structures built in the sector is of great importance for sustainability. The contribution of poor-quality and unhealthy structures to environmental stress further highlights the role of the construction sector in sustainability. The study addresses the impacts of strategic goals such as the design and construction of sustainable building models, the recyclability and reuse of building materials, energy efficiency, and the reduction of CO2 emissions on the construction sector. The findings indicate that the integration of energy efficiency and renewable energy technologies is crucial for the Turkish construction sector to move towards a sustainable future. In this context, it is recommended that the Turkish construction sector implement the necessary steps and engage in strategic planning in order to achieve its sustainability goals. The findings of the study emphasise the pivotal role and significance of the construction sector in this regard.    

    

* Integration of Phase-Change Materials in Ventilated Façades: A Review Regarding Fire Safety and Future Challenges  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400581524
:TOPICS: Thermal Energy Storage with Phase Change Materials, Fire Safety in Tunnel Fires, Flame Retardant Polymer Materials
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/fire7070244")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400581524"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400581524"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400581524"))][Get cited by]]

OpenAlex: https://openalex.org/W4400581524 (Open access: True)
    
[[https://openalex.org/A5099293998][Emanuil-Petru Ovadiuc]], [[https://openalex.org/A5032734534][Răzvan Calotă]], [[https://openalex.org/A5021878472][Ilinca Năstase]], [[https://openalex.org/A5068437670][Florin Bode]], Fire. 7(7)] 2024. https://doi.org/10.3390/fire7070244 
     
The increasing concerns about CO2 emissions and climate change have pointed out the urgency of promoting sustainability in the building sector. One promising solution to enhance the energy efficiency of buildings and diminish environmental impact is the integration of phase-change materials (PCMs) into ventilated façade systems. This review article critically examines the current state of research on this innovative approach, with a particular focus on fire safety considerations. The paper explores the integration of PCM into ventilated façades, highlighting the potential for significant improvements in energy consumption, thermal comfort, and reductions in CO2 emissions. However, the flammability of PCMs introduces substantial fire safety challenges that must be addressed to ensure the safe application of this solution. The fire safety of both ventilated façades and PCMs is approached, followed by specific fire safety concerns when PCMs are integrated into ventilated façade systems. The conclusion states that while the integration of PCMs into ventilated façades offers substantial environmental benefits, attention to fire safety is essential. This necessitates the implementation of rigorous fire protection measures during the design and construction phases. By addressing both the environmental advantages and fire safety challenges, this review aims to provide a comprehensive understanding of the potential and limitations of PCM-integrated ventilated façades, offering valuable insights for researchers, engineers, and policymakers in the field of sustainable buildings.    

    

* Roadmap for carbon farming schemes (Road4Schemes) : Deliverable D2.1-2, D2.4-5 : carbon farming schemes throughout Europe, an overall inventory and analysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400559880
:TOPICS: Economic Implications of Climate Change Policies, Life Cycle Assessment and Environmental Impact Analysis, Social Acceptance of Renewable Energy Innovation
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18174/654551")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400559880"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400559880"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400559880"))][Get cited by]]

OpenAlex: https://openalex.org/W4400559880 (Open access: False)
    
[[https://openalex.org/A5074981672][A.B. Smit]], [[https://openalex.org/A5064069061][Martin Hvarregaard Thorsøe]], [[https://openalex.org/A5015143798][J.W.H. van der Kolk]], [[https://openalex.org/A5103318319][K. Nikolaus]], [[https://openalex.org/A5067050195][Laura B. Martínez‐García]], [[https://openalex.org/A5094161014][Ennio Facq]], [[https://openalex.org/A5073795314][Ilaria Falconi]], [[https://openalex.org/A5032646045][Ülfet Erdal]], [[https://openalex.org/A5063567425][Claudia Heidecke]], [[https://openalex.org/A5088549626][Alessandra Martelli]], [[https://openalex.org/A5033074456][Irene Criscuoli]], [[https://openalex.org/A5081760728][Giovanni Dara Guccione]], [[https://openalex.org/A5037201037][Morten Graversgaard]], [[https://openalex.org/A5047696270][Jana Poláková]], [[https://openalex.org/A5103318318][S. Götzinger]], [[https://openalex.org/A5051648044][A. Baumgarten]], [[https://openalex.org/A5041584470][Suzanne Reynders]], [[https://openalex.org/A5004269943][M. Noguès]], No host. None(None)] 2024. https://doi.org/10.18174/654551 
     
Carbon farming is considered as one of the mitigation options to reach the targets of the Paris Agreement and the European Green Deal.The purpose of this report is to assess which carbon farming schemes are available throughout Europe, how they can be characterised and to which extent they deal with principles like additionality, fairness and long-term carbon storage, besides the issues of a proper MRV(monitoring, reporting and verification)-system with acceptable costs and sufficient payments for the farmers.The way in which carbon farming is organised is very different depending on the type of scheme.In this report, a carbon farming scheme is defined as any voluntary agreement in which a farmer or a group of farmers commit themselves to apply carbon farming measures to get a positive balance between soil carbon accumulation and GHG emissions (possibly measured as CO2 equivalents) or reduction of GHG-emissions in return for a payment or compensation in any form.    

    

* Self-Leveling Mortars Produced with Different Types of Cement: Physical–Mechanical Properties and Carbon Emissions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400523218
:TOPICS: Geopolymer and Alternative Cementitious Materials, Fiber Reinforced Concrete in Civil Engineering, 3D Concrete Printing Technology
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16145898")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400523218"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400523218"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400523218"))][Get cited by]]

OpenAlex: https://openalex.org/W4400523218 (Open access: True)
    
[[https://openalex.org/A5002938427][Brenda Maiara Oliveira Alves]], [[https://openalex.org/A5004759645][Mísley Da Cruz Teixeira]], [[https://openalex.org/A5103307129][Karen Suely Martins Bernardo]], [[https://openalex.org/A5009544278][Luciana de Nazaré Pinheiro Cordeiro]], [[https://openalex.org/A5087061644][Edna Possan]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16145898 
     
Self-leveling mortars are a product that stands out in the market for optimizing production. Greater speed of application is achieved due to its high fluidity, and the ability to level without segregation. This paper approaches self-leveling mortars formulated with different types of cement and additions and evaluates these material’s effect on the rheological behavior, physical–mechanical characteristics, and environmental aspects of this type of mortar. The results indicate that rheological aspects can be achieved regardless of the type of cement and addition. With proper proportioning, the normative requirements in terms of mechanical properties are met. When using lower-fineness cement, the risk of cracking and the demand for water and chemicals increases. Mineral additions contributed to the mortars’ cohesion and reduced shrinkage in mixtures with contents of up to 25% metakaolin and 15% silica fume. Regarding the decarbonization process, opting for cement with pozzolanic additions becomes a favorable solution as it presents a reduction in CO2 emissions of around 170 kg per m3 of mortar produced.    

    

* Evaluation of proposals from key suppliers of small-scale photovoltaic installations for single-family homes considering current regulations and environmental and economic criteria—A case study in Malaga, Spain  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400516247
:TOPICS: Social Acceptance of Renewable Energy Innovation, Sustainable Urban Development and Planning, Lifestyle Migration and Retirement Mobility
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.24294/jipd.v8i6.5205")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400516247"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400516247"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400516247"))][Get cited by]]

OpenAlex: https://openalex.org/W4400516247 (Open access: True)
    
[[https://openalex.org/A5078678417][Enrique Navarrete de Gálvez]], [[https://openalex.org/A5100506331][Luis Rodríguez-Passolas Cantal]], [[https://openalex.org/A5103938783][Francisco José Ortíz Zamora]], [[https://openalex.org/A5084530286][Shakir Mohamed]], [[https://openalex.org/A5021734830][Laia Miravet Garret]], Journal of infrastructure, policy and development. 8(6)] 2024. https://doi.org/10.24294/jipd.v8i6.5205 
     
The economic viability of a photovoltaic (PV) installation depends on regulations regarding administrative, technical and economic conditions associated with self-consumption and the sale of surplus production. Royal Decree (RD) 244/2019 is the Spanish legislation of reference for this case study, in which we analyse and compare PV installation offers by key suppliers. The proposals are not optimal in RD 244/2019 terms and appear not to fully contemplate power generation losses and seem to shift a representative percentage of consumption to the production period. In our case study of a residential dwelling, the best option corresponds to a 5 kWp installation with surplus sale to the market, with a payback period of 18 years and CO2 emission reductions of 1026 kg/year. Demand-side management offers a potential improvement of 6%–21.8%. Based on the increase in electricity prices since 2020, the best option offers savings of up to €1507.74 and amortization in 4.24 years. Considering costs and savings, sale to the market could be considered as the only feasible regulatory mechanism for managing surpluses, accompanied by measures to facilitate administrative procedures and guarantees for end users.    

    

* Exploring the potential of Easy Language for enhancing website sustainability  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400534852
:TOPICS: Energy Consumption in Mobile Devices and Networks, The Impact of Digital Media on Public Discourse, Impact of Emoticons on Computer-Mediated Communication
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10209-024-01129-8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400534852"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400534852"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400534852"))][Get cited by]]

OpenAlex: https://openalex.org/W4400534852 (Open access: True)
    
[[https://openalex.org/A5031507069][Mariona González-Sordé]], Universal access in the information society. None(None)] 2024. https://doi.org/10.1007/s10209-024-01129-8 
     
Abstract Sustainable design principles have become increasingly important in website development, mainly focusing on reducing carbon emissions and energy consumption. Easy language (EL) is a simplified language variety that makes websites more accessible to a wider range of users; but there has been no attention given to its usefulness in sustainability efforts. As such, this study is intended to become a starting point for future research in the area. By examining the intersection between EL and website sustainability guidelines and practices, the study highlights the potential for EL to contribute to sustainable website design. Along the paper, the following theory is defended: when adapted to Easy Language, text and interactions in websites are simplified, which makes them require less data transfer, become more efficient and, ultimately, more sustainable. The paper also presents a small comparative analysis of the sustainability of websites in EL and standard language that indicated that EL generally enhanced the sustainability of websites. The nine websites in EL analysed showed a mean reduction of CO2 production of 42% in comparison to their equivalents in standard language ( p = 0.049, F = 2.42). The discussion and results presented open potential solutions for an urgent problem that deserve to be considered and researched further.    

    

* Economic Order Quantity: A State-of-the-Art in the Era of Uncertain Supply Chains  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400578514
:TOPICS: Coordination and Information Sharing in Supply Chains, Scheduling Problems in Manufacturing Systems, Conceptualizing the Circular Economy and Sustainable Supply Chains
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16145965")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400578514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400578514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400578514"))][Get cited by]]

OpenAlex: https://openalex.org/W4400578514 (Open access: True)
    
[[https://openalex.org/A5007231493][Mohammed Alnahhal‬‏]], [[https://openalex.org/A5045706913][Batin Latif Aylak]], [[https://openalex.org/A5053623757][Muataz Hazza Faizi Al Hazza]], [[https://openalex.org/A5005797729][Ahmad Sakhrieh]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16145965 
     
Inventory management is crucial for companies to minimize unnecessary costs associated with overstocking or understocking items. Utilizing the economic order quantity (EOQ) to minimize total costs is a key decision in inventory management, particularly in achieving a sustainable supply chain. The classical EOQ formula is rarely applicable in practice. For example, suppliers may enforce a minimum order quantity (MOQ) that is much larger than the EOQ. Some conditions such as imperfect quality and growing items represent variants of EOQ. Moreover, some requirements, such as the reduction of CO2 emissions, can alter the formula. Moreover, disruptions in the supply chain, such as COVID-19, can affect the formula. This study investigates which requirements must be considered during the calculation of the EOQ. Based on a literature review, 18 requirements that could alter the EOQ formula were identified. The level of coverage for these requirements has been tracked in the literature. Research gaps were presented to be investigated in future research. The analysis revealed that, despite their importance, at least 11 requirements have seldom been explored in the literature. Among these, topics such as EOQ in Industry 4.0, practical EOQ, and resilient EOQ have been identified as promising areas for future research.    

    

* Investigation of Partial Oxidation of Methane at Different Reaction Parameters by Adding Ni to CeO2 and ZrO2 Supported Cordierite Monolith Catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400600073
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/pr12071463")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400600073"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400600073"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400600073"))][Get cited by]]

OpenAlex: https://openalex.org/W4400600073 (Open access: True)
    
[[https://openalex.org/A5065431123][Ilke Ilicak Bayraktar]], [[https://openalex.org/A5005380222][Halit Eren Figen]], Processes. 12(7)] 2024. https://doi.org/10.3390/pr12071463 
     
The climate crisis, driven by increasing CO2 levels in the atmosphere, has heightened the need for new, environmentally friendly energy sources. Hydrogen gas, which can meet our energy needs, has become a particularly intriguing topic. This study investigated the partial oxidation reaction of methane with cordierite monolith catalysts. The Ni-coated catalysts were supported with γ-Al2O3, CeO2, ZrO2, and CeO2-ZrO2. The catalysts were tested at temperatures of 750, 800, and 850 °C with different flow rates and methane feed concentrations (2%, 5%, and 10%). It was demonstrated that catalyst activity varies depending on these parameters. It has been found that high gas hourly space velocity (GHSV) and CH4 feed rates decrease catalyst activity. The obtained reaction results indicated that the optimal reaction parameters were 800 °C, a GHSV of 1.104 h−1, and a CH4 feed concentration of 2%. By optimizing these parameters, catalysts with high CH4 conversion and selectivity for H2 and CO were achieved. The prepared catalysts were characterized using scanning electron microscopy with energy dispersive X-ray analysis (SEM-EDX), X-ray diffraction (XRD), Brunauer-Emmett-Teller (BET), and temperature-programmed reduction (TPR).    

    

* Investigating the effect of dynamic traffic distribution on network-wide traffic emissions: An empirical study in Ningbo, China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400583330
:TOPICS: Estimating Vehicle Fuel Consumption and Emissions, Understanding Attitudes Towards Public Transport and Private Car, Modeling and Control of Traffic Flow Systems
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1371/journal.pone.0305481")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400583330"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400583330"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400583330"))][Get cited by]]

OpenAlex: https://openalex.org/W4400583330 (Open access: True)
    
[[https://openalex.org/A5048155645][Shuichao Zhang]], [[https://openalex.org/A5042919591][Jianan Shi]], [[https://openalex.org/A5022686427][Yizhe Huang]], [[https://openalex.org/A5018531702][Hao Shen]], [[https://openalex.org/A5102279952][He Kangkang]], [[https://openalex.org/A5100767117][Hongjie Chen]], PloS one. 19(7)] 2024. https://doi.org/10.1371/journal.pone.0305481 
     
Urban road traffic is one of the primary sources of carbon emissions. Previous studies have demonstrated the close relationship between traffic flow characteristics and carbon emissions (CO2). However, the impact of dynamic traffic distribution on carbon emissions is rarely empirically studied on the network level. To fill this gap, this study proposes a dynamic network carbon emissions estimation method. The network-level traffic emissions are estimated by combining macroscopic emission models and recent advances in dynamic network traffic flow modeling, namely, Macroscopic Fundamental Diagram. The impact of traffic distribution and the penetration of battery electric vehicles on total network emissions are further investigated using the Monte Carlo method. The results indicate the substantial effect of network traffic distribution on carbon emissions. Using the urban expressway network in Ningbo as an example, in the scenario of 100% internal combustion engine vehicles, increasing the standard deviation of link-level traffic density from 0 to 15 veh/km-ln can result in an 8.9% network capacity drop and a 15.5% reduction in network carbon emissions. This effect can be moderated as the penetration rate of battery electric vehicles increases. Based on the empirical and simulating evidence, different expressway pollution management strategies can be implemented, such as petrol vehicle restrictions, ramp metering, congestion pricing, and perimeter control strategies.    

    

* Understanding the Social Determinants of Household Carbon Emissions for Carbon Mitigation Policies: The Case of Mersin, Turkey  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400644633
:TOPICS: Indoor Air Pollution in Developing Countries, Rebound Effect on Energy Efficiency and Consumption, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-07-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16146012")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400644633"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400644633"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400644633"))][Get cited by]]

OpenAlex: https://openalex.org/W4400644633 (Open access: True)
    
[[https://openalex.org/A5030913473][Ali Cenap Yoloğlu]], [[https://openalex.org/A5104542070][Bulent Halisdemir]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16146012 
     
Households are the main consumer-side source of carbon emissions. In Europe, consumer-based CO2 consumption per capita fell from 10.8 tons to 7.8 tons between 1990 and 2022, but in Turkey, the same data showed a rise from 4 tons to 5 tons. Strategies to reduce carbon emissions have recently shifted their focus from the production side to the consumption side. However, because different social segments have varying levels of price sensitivity and differing levels of necessity regarding consuming different items, a simple tax policy only targeting the consumption side is doomed to fail. This has prompted a discussion of the factors influencing carbon emissions on the consumption side and how those factors affect the amount of emissions. This study aims to identify the social determinants affecting household carbon emission levels and to demonstrate that such differences play an important role in effective and efficient carbon emission reduction strategies. In this case study, an appropriate testing method was used to test whether there are significant differences in dependent variables (carbon emissions) between categories of independent variables (the social determinants of households). As our literature review demonstrates, the social determinants of households and the local context were found to have an impact on carbon emissions in the case study. Nevertheless, we found that the degree of association lessens when the relationship between the dependent variables and the independent variables is re-evaluated while controlling for income level. Consequently, it may be concluded that the primary element influencing carbon emissions is income. In our field study, on the other hand, poverty stood out as another important factor affecting the level of carbon emissions. Poverty affects total household carbon emissions in two different ways, causing both carbon-intensive consumer goods and household appliances with low energy efficiency to be preferred because they are cheap to purchase. Therefore, the fight against poverty should be recognized as an important component of carbon reduction policies in Turkey, and the issue of environmental justice should not be ignored, because we know that 30% of the population was living in poverty (compared to the other 70% receiving the national median income) in 2022.    

    

* The Reconstruction of Bi 2 Te 4 O 11 Nanorods for Efficient and pH‐universal Electrochemical CO 2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400592992
:TOPICS: Gas Sensing Technology and Materials, Electrochemical Reduction of CO2 to Fuels, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202408849")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400592992"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400592992"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400592992"))][Get cited by]]

OpenAlex: https://openalex.org/W4400592992 (Open access: False)
    
[[https://openalex.org/A5082391052][Jiadong Chen]], [[https://openalex.org/A5076545740][Tingjie Mao]], [[https://openalex.org/A5100347436][Juan Wang]], [[https://openalex.org/A5101619598][Jichang Wang]], [[https://openalex.org/A5025466794][Lianghao Yu]], [[https://openalex.org/A5100424610][Shun Wang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202408849 
     
The practical application of electrochemical CO2 reduction reaction (CO2RR) is hindered by the competing CO production, hydrogen evolution reaction (HER), and the lack of pH‐universal catalysts. Here, Te‐modified Bi nanorods (Te‐Bi NRs) were synthesized through in situ reconstruction of Bi2Te4O11 NRs under the CO2RR condition. Our study illustrates that the complex reconstruction process of Bi2Te4O11 NRs during CO2RR could be decoupled into three distinct steps, i.e., the destruction of Bi2Te4O11, the formation of Te/Bi phases, and the dissolution of Te. The thus‐obtained Te‐Bi NRs exhibit remarkably high performance in CO2RR towards formate production, showing high activity, selectivity, and stability across all pH conditions (acidic, neutral, and alkaline). In a flow cell reactor under neutral, alkaline, or acidic conditions, the catalysts achieved HCOOH Faradaic efficiencies of up to 94.3%, 96.4%, and 91.0%, respectively, at a high current density of 300 mA cm‐2. DFT calculations, along with operando spectral measurements, reveal that Te manipulates the Bi sites to an electron‐deficient state, enhancing the adsorption strength of the *OCHO intermediate, and significantly suppressing the competing HER and CO production. This study highlights the substantial influence of catalyst reconstruction under operational conditions and offers insights into designing highly active and stable electrocatalysts towards CO2RR.    

    

* Real-Time LNG Buses Emissions Prediction Based on a Temporal Fusion Trans-Formers Model  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400515183
:TOPICS: Estimating Vehicle Fuel Consumption and Emissions, Structural Analysis and Design Optimization in Engineering
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3808/jei.202400517")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400515183"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400515183"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400515183"))][Get cited by]]

OpenAlex: https://openalex.org/W4400515183 (Open access: False)
    
[[https://openalex.org/A5104347467][Q. C. Liu]], [[https://openalex.org/A5038947507][Fei Gao]], [[https://openalex.org/A5100358009][Jun Zhao]], [[https://openalex.org/A5101571962][Yafei Cai]], [[https://openalex.org/A5100756831][Lei Chen]], [[https://openalex.org/A5100717722][Cheng Lv]], Journal of environmental informatics. None(None)] 2024. https://doi.org/10.3808/jei.202400517 
     
Emissions from transportation are one of the key factors preventing the achievement of carbon peaking and carbon neutrality by 2050, with particular attention to emissions from buses. Specifically, few research has been conducted on the exhaust emissions characteristics of liquified natural gas (LNG) buses under different driving scenarios. This study proposed a framework for predicting exhaust emissions of LNG buses based on the portable emission measurement system and GPS collaborative perception data. Firstly, the emission distribution characteristics of CO2, CO, HC, and NOx from LNG buses in real-world driving were analyzed by visualization methods. Then, the real-time exhaust emissions of LNG buses were predicted based on the temporal fusion transformers model for both urban and suburban sections of Zhenjiang City, and the model validity was verified. The current and past 10 s driving states were used for predicting the emission rate of LNG buses. The results showed that the proposed model outperforms other advanced algorithms in real-time exhaust emissions prediction of LNG buses, with an average R2 value higher than 0.94 and an average MAPE reduction of 14.19%. The error assessment revealed that the emission values and average emission rates are higher when driving in the urban section compared to the suburban section. Among the influencing factors, traffic conditions have the most significant impacts on the exhaust emissions of LNG buses, followed by road conditions and driving states, with relative feature importance of 48.9, 34.8, and 16.3%, respectively. Additionally, the current and past 10 s driving states also significantly influenced real-time predictions. This study provides an essential theoretical reference for reducing exhaust emissions for city buses.    

    

* GOLD ENRICHMENT MECHANISM IN MID-OCEAN RIDGE HYDROTHERMAL SYSTEMS: AN EXAMPLE FROM THE LONGQI HYDROTHERMAL FIELD ON THE ULTRASLOW-SPREADING SOUTHWEST INDIAN RIDGE  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400642729
:TOPICS: Machine Learning for Mineral Prospectivity Mapping, Tectonic and Geochronological Evolution of Orogens, Geochemistry of Manganese Oxides in Sedimentary Environments
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5382/econgeo.5095")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400642729"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400642729"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400642729"))][Get cited by]]

OpenAlex: https://openalex.org/W4400642729 (Open access: False)
    
[[https://openalex.org/A5102754079][Kean Chen]], [[https://openalex.org/A5063191044][Huichao Zhang]], [[https://openalex.org/A5047612204][Nigel J. Cook]], [[https://openalex.org/A5103247739][Tao Wu]], [[https://openalex.org/A5023780582][Fang An]], [[https://openalex.org/A5103843175][Jin Liang]], [[https://openalex.org/A5104076106][Weifang Yang]], Economic geology and the bulletin of the Society of Economic Geologists. None(None)] 2024. https://doi.org/10.5382/econgeo.5095 
     
Abstract In mid-ocean ridge (MOR) hydrothermal systems, the gold grade of sea-floor massive sulfides (SMSs) is negatively correlated with the spreading rate of the ridge. Previous investigations have addressed the distribution of gold in sulfides from hydrothermal fields hosted by ultramafic rocks. In contrast, the gold enrichment mechanisms in sulfides from hydrothermal fields hosted by mafic rocks in ultraslow-spreading ridge environments are less well constrained. The basalt-hosted Longqi hydrothermal field, located on the classic ultraslow-spreading Southwest Indian Ridge, provides an opportunity to examine gold enrichment mechanisms in such an environment. Two ore-forming stages are identified in chimney fragments: anhydrite + barite + colloidal/porous pyrite (Py1) + marcasite + fine-grained sphalerite (stage 1); euhedral-subhedral pyrite (Py2) + coarse-grained sphalerite + chalcopyrite + isocubanite (stage 2). Py1 is usually overgrown by marcasite, which is in turn enclosed by Py2. Py2 coexists with coarse-grained sphalerite and chalcopyrite. Abundant native gold nanoparticles occur in Py1 or at the transition zone between Py1 and Py2. Laser ablation inductively coupled plasma mass spectrometry (LA-ICP-MS) analysis suggests that Py1 contains higher Mo, V, Sn, and Pb and lower As, Co/Ni, and Se/Tl values compared to Py2. In situ LA-multicollector (MC)-ICP-MS analyses show that Py1 has a higher mean δ34S (+7.1‰) value than Py2 (+6.6‰). Sulfur primarily derives from MORB and seawater sulfate, of which the proportion of sulfur from seawater sulfate is between 20.5 and 47.6%. Textures, mineral assemblages, and trace element contents of sulfides indicate that the degree of mixing between hydrothermal fluids and seawater decreases as the chimney grows and is accompanied by a gradual increase in temperature. Based on data compiled from 41 hydrothermal fields hosted by basalt, the large range of sulfide δ34S from slow- and ultraslow-spreading MORs may be attributed to the wide range of sulfur sources (e.g., leaching from MOR basalt, thermochemical reduction of seawater sulfate, magma degassing, and bacterial activity), fluid-basalt interaction, and redox state (CH4/CO2 ratios). Prolonged fluid-basalt interaction and the type of chimneys, such as beehive chimneys, may lead to higher gold grades in hydrothermal fields. Moreover, low H2S content may be an important contributor to gold enrichment in basalt-hosted SMS deposits in ultraslow-spreading MOR environments.    

    
