#+filetags: CO2RR
#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Fri Feb 16 00:42:59 2024

Found 27 results from 2024-02-09 to 2024-02-16
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Research on photoelectrocatalytic carbon dioxide reduction based on carbon wood photothermal cathode  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391655667
:TOPICS: Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1117/12.3024972")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391655667"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391655667"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391655667"))][Get cited by]]

OpenAlex: https://openalex.org/W4391655667 (Open access: False)
    
[[https://openalex.org/A5071672663][Jun Zhang]], [[https://openalex.org/A5027416449][Tao Li]], [[https://openalex.org/A5091192043][Xiaotian Li]], [[https://openalex.org/A5058908515][Aiqi Fang]], No host. None(None)] 2024. https://doi.org/10.1117/12.3024972 
     
A photothermal electrode was prepared using carbon wood as the substrate and carbon-nitrogen-iron as the catalyst, harnessing the excellent photothermal properties of carbon wood to facilitate CO2 reduction. First, we analyzed the structural features of carbon wood. It possesses an abundance of vertical microchannels that favor material transport. Additionally, its high surface area and mesoporous structure provide suitable sites for the reaction. Secondly, the photothermal properties of carbon wood were investigated, showing its efficient light absorption and photothermal conversion capabilities, allowing effective utilization of solar energy. Finally, a photothermal-assisted CO2 reduction system was constructed, using titanium dioxide as the photoanode and carbon wood loaded with carbon-nitrogen-iron as the photothermal cathode. Solar irradiation effectively increased the reaction temperature, enabling the carbon-nitrogen-iron catalyst, which exhibits a thermal response effect, to perform more efficiently. Further studies revealed that rapid evaporation of the solution at the carbon wood cathode created a favorable three-phase interfacial microenvironment for CO2 reduction, enhancing the reaction efficiency. As a result, the CO yield reached 40.8 μmol cm-2 h-1, which was 5.9 times higher than that achieved under non-photothermal conditions.    

    

* Novel lead-free halide perovskite KMgI3 for photocatalytic hydrogen evolution (HER) and carbon dioxide reduction reaction (CO2RR)  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391667291
:TOPICS: Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.136066")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391667291"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391667291"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391667291"))][Get cited by]]

OpenAlex: https://openalex.org/W4391667291 (Open access: False)
    
[[https://openalex.org/A5046737855][E. Luévano-Hipólito]], [[https://openalex.org/A5092207100][Mayte G. Fabela-Cedillo]], [[https://openalex.org/A5019849239][Leticia M. Torres-Martı́nez]], Materials Letters. 361(None)] 2024. https://doi.org/10.1016/j.matlet.2024.136066 
     
Lead-free magnesium iodide (KMgI3) perovskite films were obtained by ink-jet printing. The halide perovskites were printed in different supports: mica, magnesium oxychloride, and glass. The printed samples were evaluated in photocatalytic hydrogen evolution (HER) and carbon dioxide reduction reaction (CO2RR) to produce alternative solar based fuels, e.g., formic acid (HCOOH) and hydrogen (H2) under visible light. The KMgI3 printed on mica exhibited the highest activity to produce both HCOOH and H2, with apparent quantum yields of 1.02 and 7.86 % at 550 nm, respectively. This result was associated with an enhanced adhesion of the perovskite to mica due to the K+ affinity and a better interaction of the C atom possible due to the depletion of the layer of K+, leading to the exposure of aluminosilicate sheets. The stability of the perovskite was corroborated after three consecutive cycles.    

    

* The Influence of the Cu Foam on the Electrochemical Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391753550
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/inorganics12020057")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391753550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391753550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391753550"))][Get cited by]]

OpenAlex: https://openalex.org/W4391753550 (Open access: True)
    
[[https://openalex.org/A5035631045][Yuan-Gee Lee]], [[https://openalex.org/A5016437027][Hui-Hsuan Chiao]], [[https://openalex.org/A5084275546][Yu–Ching Weng]], [[https://openalex.org/A5045826984][Chyi-How Lay]], Inorganics (Basel). 12(2)] 2024. https://doi.org/10.3390/inorganics12020057  ([[https://www.mdpi.com/2304-6740/12/2/57/pdf?version=1707641709][pdf]])
     
Unlike the flat Cu sheet, we employed Cu foam to explore the specific porous effect on the expanding specific area. We found that the foam structure is superior to the sheet feature in the specific location from the morphology investigation. In the practical measurement of surface area, we found that the adsorbate could aptly agglomerate, resulting in a consequential block in the transport path. The specific location of the Cu foam was underestimated because the channels of the deep foam layer were blocked by the agglomerated adsorbate. To explore the protonation process of the electro-reduction, we adopted the carbonate electrolyte as the control group in contrast to the experimental group, the bicarbonate electrolyte. In the carbonate electrolyte, the primary intermediate was shown to be CO molecules, as verified using XPS spectra. In the bicarbonate electrolyte, the intermediate CO disappeared; instead, it was hydrogenated as a hydrocarbon intermediate, CHO*. The bicarbonate ion was also found to suppress electrocatalysis in the deep structure of the Cu foam because its high-molecular-weight intermediates accumulated in the diffusion paths. Furthermore, we found a promotion of the oxidation valence on the electrode from Cu2O to CuO, when the electrode structure transformed from sheet to foam. Cyclic voltammograms demonstrate a succession of electro-reduction consequences: at low reduction potential, hydrogen liberated by the decomposition of water; at elevated reduction potential, formic acid and CO produced; and at high reduction potential, CH4 and C2H4 were formed from −1.4 V to −1.8 V.    

    

* Recent Progress of MXene as a Cocatalyst in Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391760771
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Two-Dimensional Materials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceja.2024.100593")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391760771"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391760771"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391760771"))][Get cited by]]

OpenAlex: https://openalex.org/W4391760771 (Open access: True)
    
[[https://openalex.org/A5082818904][Zhe Wang]], [[https://openalex.org/A5020377897][Samar Al Jitan]], [[https://openalex.org/A5058905109][Inas M. AlNashef]], [[https://openalex.org/A5087660437][Blaise L. Tardy]], [[https://openalex.org/A5035367466][Giovanni Palmisano]], Chemical Engineering Journal Advances. None(None)] 2024. https://doi.org/10.1016/j.ceja.2024.100593 
     
Due to the excessive consumption of fossil fuel resources and the emission of a substantial quantity of CO2 into the environment, it is urgent to develop clean energy solutions. In order to reduce carbon emissions from the source, it is effective approach to convert CO2 into various renewable energy fuels. Inspired by the photosynthesis of green plant, CO2 is converted into clean fuel with the aid of catalysts. Regarding the separation and transfer of photogenerated charge carriers, and inadequate adsorption and activation of CO2 on the surface of catalysts, the current semiconductors utilized in photocatalysis have low efficiency. As a result, the current efficiency of photocatalysts is far from meeting the need for practical industrial demands. MXene materials, for example Ti3C2Tx (9980 S cm−1), have emerged as a promising candidate for CO2 reduction due to the significant number of active sites for functional groups, high conductivity and low defects, large surface areas, and outstanding visible light photoelectronic properties. This review provides a critical overview of the recent progress regarding MXene as a co-catalyst in photocatalytic CO2 reduction systems. We systemically explore the fundamental principles and reaction mechanisms associated with separating and transferring photogenerated charge carriers. Additionally, we investigate the basic properties of MXene as a co-catalyst in the context of CO2 reduction. Furthermore, this review also elucidates the impacts of the microstructure of photocatalysts on enhancing photocatalytic performance. Finally, the challenges and opportunities in using MXene as a co-catalyst for CO2 reduction have been presented to inspire further research in this field.    

    

* Two-Dimensional Carbon Nitride as a Support of Single Metal Atom for Carbon Dioxide Reduction Reaction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391637868
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542607mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391637868"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391637868"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391637868"))][Get cited by]]

OpenAlex: https://openalex.org/W4391637868 (Open access: False)
    
[[https://openalex.org/A5075097508][Sergio Posada‐Pérez]], [[https://openalex.org/A5089940148][Anna Vidal López]], [[https://openalex.org/A5035251076][Miquel Solà]], [[https://openalex.org/A5091859825][Albert Poater]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542607mtgabs 
     
Electrochemical conversion of CO 2 into added-value chemicals is an important approach to recycle CO 2 . Heterogeneous catalysis is widely used in industrial applications because of the possibility of facile separation, which reduces the operating costs, although heterogeneous catalysts often have limited selectivity. In contrast, homogeneous catalysts are very selective although they have limited industrial applications due to their cost, the use of precious metals, and the difficulty in separating and recovering the catalysts. Currently, the research community is trying to combine the properties of homogeneous and heterogeneous catalysts. From the heterogeneous catalyst perspective, research has been focused on creating smaller and dispersed catalyst particles. Single-atom catalysts (SACs), which comprise atoms of metal species dispersed on a solid support, are expected to bridge the homogeneous and heterogeneous catalyst properties. The work described herein explores, by means of density functional simulations, the electrocatalytic CO 2 reduction reaction (CO 2 RR) using several single transition metal atoms anchored in 2D graphitic carbon nitride (g-C 3 N 4 ), 1 focusing on the group XI transition metals since they include Cu, the only transition metal capable of reducing CO 2 to hydrocarbons and alcohols with acceptable faradaic efficiencies. Moreover, the Cu 1 /g-C 3 N 4 system has been experimentally evaluated as CO 2 RR electrocatalysts. 2D g-C 3 N 4 has been demonstrated to be a competitive candidate for electrocatalytic CO 2 reduction since it can act as an active support for single metal-atom catalysts, mainly Cu, Pd, and Pt, and the deposition of Au single atom was experimentally characterized. The computational hydrogen electrode model has been used to explore the suitability of several transition metals atoms anchored to C 3 N 4 , showing that single atoms enhance the catalytic activity of the system as the first proton–electron transfer is thermodynamically favored in comparison to bare carbon nitride support. Our theoretical interpretations are consistent with the experimental results using Cu 1 /g-C 3 N 4 , 2 revealing that the competitive H 2 generation is favored due to the strong CO binding energies. This fact reinforced the capability of our computational models to predict the behavior of several single metal atom electrocatalysts to reduce CO 2 , for instance, predicting that Au can promote the methane formation after eight electron-proton transfer processes. Our computational study paves the road to finding suitable metals that catalyze the first proton–electron transfer in the carbon dioxide reduction reaction. Posada-Pérez, A. Vidal-López, M. Solà, and A. Poater, 2023, Phys. Chem. Chem. Phys, 25, 8574. Cometto, A. Ugolotti, E. Grazietti, A. Moretto, G. Bottaro, L. Armelao, C. Di Valentin, L. Calvillo and G. A. Granozzi, npj 2D Mater. Appl. , 2021, 5 , 63. Figure 1    

    

* (Invited) Electrocatalytic Reduction of Carbon Dioxide over Aluminum-Added Coppor Oxide Gas Diffusion Electrode  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391638189
:TOPICS: Gas Sensing Technology and Materials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472364mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638189"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638189"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638189"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638189 (Open access: False)
    
[[https://openalex.org/A5082711943][Tsutomu Minegishi]], [[https://openalex.org/A5017675862][Daisuke Komori]], [[https://openalex.org/A5007438676][H. Ebe]], [[https://openalex.org/A5071307251][Hiromu Kumagai]], [[https://openalex.org/A5043130875][Masakazu Sugiyama]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472364mtgabs 
     
Electrochemical cells are the key technologies for construction of carbon neutral society to produce hydrogen from water and produce useful chemicals from carbon dioxide utilizing renewable energy. Copper species are the unique catalysts for electrochemical carbon dioxide reduction reaction (CO 2 RR) with capable of producing C2+ products such as ethanol and ethylene. Selective production of target chemical is one of the most important requirements for the catalysts, and addition of different elements and surface modifications have been reported to be beneficial for the selective production. In the present study, copper oxides-based catalysts prepared with electroless plating techniques were examined for electrochemical CO 2 RR. To conduct CO 2 RR at relatively high current densities, the catalysts were examined in the form of gas diffusion electrode (GDE). The Cu 2 O based GDE was prepared by the combination of physical vapor deposition and electroless plating on hydrophobized carbon paper coated with mesoporous carbon layer. After the electroless plating treatment, the metal precursors were successfully converted to core-shell structured electrocatalyst with Cu 2 O shell and Cu core. By introducing different elements such as aluminum to the precursor, metallic Cu, the different element added catalysts were successfully prepared in the shape of GDE. Addition of different element significantly improved durability of the core-shell structured catalysts and, as a result, faradaic efficiency of ethylene of 24 hours after starting electrolysis was increase from 32% to 47% under applying cathodic current of 260 mAcm -2 . Further surface modifications with Nafion enhanced the durability and the faradaic efficiency of ethylene maintained >50% for over 48 hours and reached about 60% in maximum. In the presentation, we will discuss about the detailed structure of the electrocatalysts, results of full-cell test, and longer durability test over 100 hours.    

    

* Fabrication of Cu-Single Atom Catalyst Supported on Unique 2D Graphdiyne Analogue-Based Porphyrin Metal Covalent Organic Frameworks for Carbon Dioxide Reduction Application  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391638252
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02572760mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638252"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638252"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638252"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638252 (Open access: False)
    
[[https://openalex.org/A5069237191][Zubair Masaud]], [[https://openalex.org/A5019631104][Haibao Huang]], [[https://openalex.org/A5093888127][Lars Eric-Roseng]], [[https://openalex.org/A5057176376][Kaiying Wang]], ECS Meeting Abstracts. MA2023-02(57)] 2023. https://doi.org/10.1149/ma2023-02572760mtgabs 
     
Excessive burning of fossil fuels for energy production has led to an exponential increase in CO 2 concentrations in the atmosphere, which is the core of universal problems such as global warming and climate change. One of the new approaches to reducing CO 2 emissions is to think of CO 2 as a useful raw material and convert this compound into useful products. Moreover, electrocatalytic carbon dioxide reduction (eCO 2 R) can be conveniently utilized to establish a zero-emission carbon cycle and utilize this CO 2 for energy-dense fuels and other chemical raw materials [1]. However, exploring novel catalysts is the ultimate need of the hour for an effective and efficient eCO 2 R. Heterogeneous single-atom catalysts (SAC) containing isolated metal species on an atomic level are gaining the increasing attention of the scientific community owing to their high metal utilization sites and superior catalytic properties[2]. The SACs are put into the full effect of catalysis by scattering it over conductive support. Therefore, in this work, the copper SACs are supported over a unique porphyrin-based graphdiyne (SAC-PG) with a π-conjugated structure (Figure 1). Graphdiyne possesses two acetylenic linkages between the aromatic rings and is responsible for not only displaying exceptional electronic conductivity but when coupled with the metalloporphyrin network provides numerous active sites for catalysis[3]. This SAC-PG analogue is achieved by a Glaser-Hay coupling reaction on Cu foam or foil. Moreover, SEM analysis is performed in combination with SEM-EDX and elemental mapping to investigate the morphology of the fabricated catalyst (Figure 2). In addition, this unique copper-based SAC-PG is evaluated as a catalyst for eCO 2 R in a customized H-cell with 0.1M/0.5M KHCO 3 as an electrolyte and Pt as a counter electrode. Nafion 117 proton exchange membrane is used for separation between the cathodic and anodic compartments while an Ag/AgCl (3M KCl) was used as a reference electrode. Under these eCO 2 R conditions, the copper SAC-PG catalyst displayed extremely high current densities (32 – 75 mA/cm 2 ) over a range of voltages (1.0-1.2 V vs RHE) and acceptable faradaic efficiencies for the carbon products (with maximum FE over 60% in total for all carbon products). In conclusion, a 2D metal covalent organic framework containing a repeating unit of Cu-porphyrin linked by butadiyne linkages was established. This unique structure showed effective CO 2 R catalysis due to its nanoporous structure, high electronic conductivity, and abundant metal cites utilization. Further optimization and constriction of these easily adjustable catalysts open up various possibilities of further exploration in the field of eCO 2 R. Acknowledgement : The author Zubair Masaud acknowledges support from the Norwegian Micro- and Nano-Fabrication Facility (NorFab, No. 245963/F50) The author Hao Huang acknowledges Marie Skłodowska-Curie Actions individual fellowship CarbonChem 101024758. References [1] I. Ganesh, “Electrochemical conversion of carbon dioxide into renewable fuel chemicals - The role of nanomaterials and the commercialization,” Renew. Sustain. Energy Rev. , vol. 59, pp. 1269–1297, 2016, doi: 10.1016/j.rser.2016.01.026. [2] X. Yang, A. Wang, B. Qiao, and J. U. N. Li, “Single-Atom Catalysts : A New Frontier,” vol. 46, no. 8, 2013. [3] C. Huang et al. , “Progress in Research into 2D Graphdiyne-Based Materials,” Chem. Rev. , vol. 118, no. 16, pp. 7744–7803, 2018, doi: 10.1021/acs.chemrev.8b00288. Figure 1    

    

* (Invited) Electrocatalysts and Processes for Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391638389
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472365mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638389"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638389"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638389"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638389 (Open access: False)
    
[[https://openalex.org/A5038549187][Astrid M. Müller]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472365mtgabs 
     
Efficient and robust electrocatalytic processes that convert climate-damaging carbon dioxide into useful fuels and chemicals are essential to decarbonize our economy. The accelerated discovery of effective catalysts critically depends on rational materials design, predicated on mechanistic and structural understanding of catalysts, electrode–electrolyte interfaces, and mass transport and catalytic processes. New synthetic methods are needed that enable the preparation of tailored multimetallic nanomaterials with precisely controlled properties, for which pulsed laser in liquids synthesis is an ideal tool. Laser-made catalysts are intrinsically more active than analogs made by conventional equilibrium methods.[1] For electrolyzer devices, nanoparticulate catalysts must be immobilized on inert, high surface area carbon substrates for electrocatalysis in aqueous electrolytes. We solved this challenge by preparing carbon fiber paper with intact mesostructures and long-lasting hydrophilicity by a green chemistry process.[2] We developed novel copper-free trimetallic electrocatalysts for aqueous carbon dioxide reduction [3] that produced C–C-coupled products. Systematic variation of metal ratios revealed trends in product distributions. We also assessed gold nanoparticle–hydrophilic carbon fiber paper assemblies with ionomer overlayers for clean syngas generation. Our laser-made catalysts together with the newly developed ability to use them on high surface area electrode supports provide the foundation towards the realization of viable successor technologies. References: [1] R.C. Forsythe, C.P. Cox, M.K. Wilsey, A.M. Müller. Pulsed Laser in Liquids Made Nanomaterials for Catalysis. Chem. Rev. 2021 , 121 , 7568-7637. [2] M.K. Wilsey, K.R. Watson, O.C. Fasusi, B.P. Yegela, C.P. Cox, P.R. Raffaelle, L. Cai, A.M. Müller. Selective Hydroxylation of Carbon Fiber Paper for Long-Lasting Hydrophilicity by a Green Chemistry Process. Adv. Mater. Interfaces 2023 , 10 , 2201684. [3] M.K. Wilsey, C.P. Cox, R.C. Forsythe, L.R. McCarney, A.M. Müller. Selective CO2 reduction towards a single upgraded product: a minireview on multi-elemental copper-free electrocatalysts. Catal. Sci. Technol. 2021 , 11 , 416-424.    

    

* Carbon Supported Pd Nanostructures for Electrochemical Reduction of Carbon Dioxide – Effects of Ozonation  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391638664
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472396mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638664"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638664"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638664"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638664 (Open access: False)
    
[[https://openalex.org/A5055467658][Milla Suominen]], [[https://openalex.org/A5004390138][Lilian Moumaneix]], [[https://openalex.org/A5048774839][Anna A. Kobets]], [[https://openalex.org/A5078947642][Tanja Kallio]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472396mtgabs 
     
Out of the transition metals capable of electrochemical carbon dioxide reduction, Pd is interesting as it can convert carbon dioxide electrochemically into formate or carbon monoxide depending on the applied potential. In fact, it is capable of producing formate at the most positive known potentials that are close to zero overpotentials although at an unfortunately low activity and at the cost of deactivation by carbon monoxide poisoning. One aim is to improve the activity and stability of Pd-based electrocatalysts towards formate production in low overpotentials. As Pd is a critical raw material, we also wish to decrease the amount of Pd required while maintaining high carbon dioxide electroreduction capability. These goals can be achieved by nanostructuring and supporting the Pd catalyst. Here, we have employed a simple wet impregnation synthesis approach to prepare small nanoparticles and nanowires of Pd supported on single walled carbon nanotubes and tested the optimum loading of Pd to obtain high formate yield with improved activity and stability. Reactive sites can be created on the carbon support by subjecting it to ozonation prior to supporting the metal, which may help certain interesting nanostructures, such as nanowires, to grow. Additionally, the oxygen functional groups on the carbon surface are expected to affect the wettability of the electrode which is important for achieving an efficient carbon dioxide electroreduction and a longer-term stability of the reaction. Therefore, we also studied the effects of ozonation of the carbon supports on the electrochemical reduction of carbon dioxide into both formate and syngas (mixture of hydrogen and carbon monoxide) on Pd. Carbon atoms inevitably participate in hydrogen evolution reaction and, thus, in syngas production on Pd-supported catalysts at higher overpotentials. Our results show that ozonation greatly enhances the activity of the catalyst material and improves its stability when applying low overpotentials for formate formation in comparison to the pristine carbon support. The current density on Pd supported ozone treated carbon nanotube material remains stable over 4h of carbon dioxide electrolysis at an applied potential of -0.45 V (vs. RHE) while Pd on pristine carbon support deactivates during the initial 30 min of the experiment. Longer electrolysis times do reveal slow changes in product distribution although activity on ozone-treated single walled carbon nanotube-supported catalyst is excellent. Additionally, the different support materials cause interesting changes in product selectivity upon applying higher overpotentials for the production of syngas. Pd supported on pristine nanotubes produces syngas with carbon monoxide-to-hydrogen ratios of 0.72 and 1.38 at applied potentials of -0.85 V (vs. RHE) and -0.95 V (vs. RHE), respectively, while ozone treated material produces less than 10% of carbon monoxide. Through physico-chemical characterizations of the materials we aim at understanding the observed changes in electrochemical reduction of carbon dioxide on carbon supported Pd nanostructures.    

    

* (Invited) Stabilization and Activation of Copper(I)-Oxide-Semiconducting Interfaces for Photoelectrochemical Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391639053
:TOPICS: Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472360mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391639053"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391639053"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391639053"))][Get cited by]]

OpenAlex: https://openalex.org/W4391639053 (Open access: False)
    
[[https://openalex.org/A5006230670][Paweł J. Kulesza]], [[https://openalex.org/A5012977856][Iwona A. Rutkowska]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472360mtgabs 
     
Electroreduction of carbon dioxide to simple organic fuels and chemicals is a topic of growing scientific and technological interest. The reaction provides means for both reducing emissions of CO 2 into atmosphere and storing renewable energy. The presentation will address low-temperature CO 2 -conversion processes based on electrocatalytic and photoelectrochemical approaches. Among important issues are choice of the catalytic or semiconducting materials, their morphology and operating conditions including temperature, solvent, electrolyte, pH etc. There is a need to improve the reaction dynamics and selectivity toward specific products. In practical electrolysis cells, the CO 2 -reduction (at cathode) is accompanied by water oxidation (at anode or photoanode). Recently, we have concentrated on the development of hybrid materials by utilizing combination of metal oxide semiconductors thus capable of effective photoelectrochemical reduction of carbon dioxide. For example, the combination of conducting polymers, or titanium (IV) oxide, and copper (I) oxide has been considered before and after sunlight illumination. Application of the hybrid system composed of both above-mentioned oxides resulted in high current densities originating from photoelectrochemical reduction of carbon dioxide mostly to methanol (CH 3 OH) as demonstrated upon identification of final products. Among important issue is intentional stabilization, activation, and functionalization of the mixed-metal-oxide-based photoelectrochemcal interface toward better long-term performance and selectivity production of small organic molecules (C1-C4) and other chemicals. In this respect, ultra-thin films of conducting polymers (simple or polyoxometallate-derivatized) and supramolecular complexes (with nitrogen containing ligands and certain transition metal sites), sub-monolayers of metals (Cu, Au), networks of noble metal (Au, Ag) nanoparticles or layers of robust bacterial biofilms have been considered. The photobiocathode utilizing robust biofilms have also been demonstrated to stabilize copper(I) oxide surfaces and to induce the system’s activity toward reduction of carbon dioxide under illuminations with visible light. In the presentation, special attention will be paid to the mechanistic aspects of electroreduction of carbon dioxide, fabrication and characterization of highly selective and durable semiconductor photoelectrode materials and to the importance of the reaction conditions.    

    

* (Invited) Application of Metal Oxide Active Supports for Enhancement of Electrocatalytic Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391663491
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02582797mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663491"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663491"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663491"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663491 (Open access: False)
    
[[https://openalex.org/A5012977856][Iwona A. Rutkowska]], [[https://openalex.org/A5048173874][Anna Chmielnicka]], [[https://openalex.org/A5093893791][Olena Siamuk]], [[https://openalex.org/A5045669575][Karolina Sobkowicz]], [[https://openalex.org/A5022047274][Beata Rytelewska]], [[https://openalex.org/A5006230670][Paweł J. Kulesza]], ECS Meeting Abstracts. MA2023-02(58)] 2023. https://doi.org/10.1149/ma2023-02582797mtgabs 
     
Of particular interest to the preparation of advanced catalytic materials is efficient utilization of catalytic sites (metal and metal oxide nanostructures, their stabilization and intentional activation, as well as organization into two-dimensional arrays, ultra-thin films or three-dimensional networks (e.g. through sequential deposition) on electrode surfaces. They can form nanosized materials with well-defined composition, structure and thickness that exhibit desirable electrocatalytic properties (e.g. toward reduction of CO 2 ). We explore here the ability of polynuclear inorganic metal oxo systems to stabilize and functionalize metal (e.g. copper) nanostructures. Here certain nanostructured metal oxides of zirconium, titanium, zinc or tungsten have been demonstrated to influence supported metal (e.g. Cu, Fe, Ag) centers in ways other than simple dispersion over electrode area. Evidence is presented that the support can modify activity (presumably electronic nature) of the above mentioned catalytic metal nanocenters thus affecting their chemisorptive and catalytic properties. Metal oxide cocatalysts can generate –OH groups at low potentials that induce proton mobility at the photo(electro)chemical interface. Our research interests concern development of systems for the electrocatalytic reduction of carbon dioxide not only in neutral but also in acid media. For example, nanosized Cu or Fe catalytic centers immobilized within ultra-thin films of tungsten oxide or mixed ZrO 2 -WO 3 films have been considered and demonstrated to exhibit synergism during CO 2 -reduction. Selectivity of the catalytic systems largely depends on the activing adsorptive (CO 2 ) phenomena and the affinity of catalytic centers to the adsorbed carbon monoxide (CO) type intermediates leading to their protonation or hydrogenation. Reduction of carbon dioxide begins now at less negative potentials and is accompanied by significant enhancement of the CO 2 -reduction current densities relative to the competitive hydrogen evolution. Among other important issues is the ability of certain metal oxides (e.g., WO 3 ) to affect hydrogen via intra-structural sorption of hydrogen molecules or atoms.    

    

* Sustainable Strategies for Solar Electrochemical Reduction of Carbon Dioxide to Fuels  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391682884
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Fuel Cell Membrane Technology, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2020-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54499/sfrh/bd/147219/2019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391682884"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391682884"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391682884"))][Get cited by]]

OpenAlex: https://openalex.org/W4391682884 (Open access: False)
    
, No host. None(None)] 2020. https://doi.org/10.54499/sfrh/bd/147219/2019 
     
No abstract    

    

* Carbon Dioxide Reduction on Alloyed Galinstan  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391663508
:TOPICS: Structural Analysis and Design Optimization in Engineering
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472400mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663508"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663508"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663508"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663508 (Open access: False)
    
[[https://openalex.org/A5059375955][Aya Gomaa Abdelkader Mohamed]], [[https://openalex.org/A5017548688][Peter Bogdanoff]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472400mtgabs 
     
Solar powered electrochemical CO₂ reduction to disposable products is presently being developed as one of negative carbon emission technologies 1 . State-of-the-art electrocatalysts are mainly developed for the CO 2 reduction to hydrogen rich products or chemical feedstock materials while for the above-mentioned application solid carbon-rich products are desired (best pure carbon). Even though the formation of solid products is sometimes observed on catalysts (coking effect), this usually leads to an undesirable irreversible deactivation of their solid interfaces. Thus, the development of next generation CO 2 electrocatalysts is demanded based on liquid metal alloys such as galinstan (GaInSn). The advantage of using liquid phase electrodes is to eliminate coking and coarsening limitations that are associated with solid catalysts. For example, it has been reported that ceria-supported liquid galinstan can electrochemically produce carbonaceous materials from CO 2 gas 2 . This shows, that doping with additional active elements can change the CO 2 reduction activity of GaInSn in the direction of other desired products. Our work investigates the activity of galinstan for the electroreduction of CO 2 depending on alloying with additional metals (such as Ce, Ag, Pb). While pure GaInSn shows a predominant activity for the formation of C1 products (CO, HCOOH) in DMF/H 2 O electrolyte, we are mainly interested in the formation of solid carbon or oxalate. Therefore, our investigations aim at finding suitable modifications of GaInSn that achieve high selectivity for these products. Electrochemical analysis coupled with in-line gas chromatography and in-line mass spectroscopy are used to characterize the reactivity. Furthermore, the influence of the water content of the organic electrolyte on the product selectivity will be investigated. In particular, to suppress the observed low hydrogen evolution as a by-product even more efficiently. May, M. M.; Rehfeld, K., Negative Emissions as the New Frontier of Photoelectrochemical CO 2 Reduction. Advanced Energy Materials 2022, 2103801. Esrafilzadeh, D.; Zavabeti, A.; Jalili, R.; Atkin, P.; Choi, J.; Carey, B. J.; Brkljača, R.; O’Mullane, A. P.; Dickey, M. D.; Officer, D. L.; MacFarlane, D. R.; Daeneke, T.; Kalantar-Zadeh, K., Room Temperature CO 2 Reduction to Solid Carbon Species on Liquid Metals Featuring Atomically Thin Ceria Interfaces. Nature Communications 2019, 10 (1), 865. Figure 1    

    

* Biocatalytical reduction of carbon dioxide for sustainable biofuel production  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391681969
:TOPICS: Technologies for Biofuel Production from Biomass, Metabolic Engineering and Synthetic Biology, Enzyme Immobilization Techniques
:PUBLICATION_DATE: 2021-11-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54499/covid/bd/151766/2021")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391681969"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391681969"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391681969"))][Get cited by]]

OpenAlex: https://openalex.org/W4391681969 (Open access: False)
    
, No host. None(None)] 2021. https://doi.org/10.54499/covid/bd/151766/2021 
     
No abstract    

    

* Intercalated Zirconium Phosphate Promotes Reductive Amination of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391686357
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acssuschemeng.3c06479")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391686357"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391686357"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391686357"))][Get cited by]]

OpenAlex: https://openalex.org/W4391686357 (Open access: False)
    
[[https://openalex.org/A5087166125][Huiying Liao]], [[https://openalex.org/A5055700427][Yongjun Jiang]], [[https://openalex.org/A5049066725][Xinjia Wei]], [[https://openalex.org/A5045350805][Xueyan Zhao]], [[https://openalex.org/A5090780152][Lai Wei]], [[https://openalex.org/A5050074954][Ning An]], [[https://openalex.org/A5091735030][Yue Ma]], [[https://openalex.org/A5031493683][Sheng Dai]], [[https://openalex.org/A5023180240][Zhenshan Hou]], ACS Sustainable Chemistry & Engineering. None(None)] 2024. https://doi.org/10.1021/acssuschemeng.3c06479 
     
No abstract    

    

* Graphene-based CO2 reduction electrocatalysts: A review  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391768389
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Thermoelectric Materials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/s1872-5805(24)60839-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391768389"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391768389"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391768389"))][Get cited by]]

OpenAlex: https://openalex.org/W4391768389 (Open access: True)
    
[[https://openalex.org/A5038427980][Zelin Wu]], [[https://openalex.org/A5009018022][Congwei Wang]], [[https://openalex.org/A5052309941][Xiaoxiang Zhang]], [[https://openalex.org/A5029883974][Quangui Guo]], [[https://openalex.org/A5029316647][Junying Wang]], New Carbon Materials. 39(1)] 2024. https://doi.org/10.1016/s1872-5805(24)60839-5 
     
The reduction of carbon dioxide (CO2) by electrochemical methods for the production of fuels and value-added chemicals is an effective strategy for overcoming the global warming problem. Due to the stable molecular structure of CO2, the design of highly selective, energy-efficient and cost-effective electrocatalysts is key. For this reason, graphene and its derivatives are competitive for CO2 electroreduction with their unique and excellent physical, mechanical and electrical properties and relatively low cost. In addition, the surface of graphene-based materials can be modified using different methods, including doping, defect engineering, production of composite structures and wrapped shapes. We first review the fundamental concepts and criteria for evaluating electrochemical CO2 reduction, as well as the catalytic principles and processes. Methods for preparing graphene-based catalysts are briefly introduced, and recent research on them is summarized according to the categories of the catalytic sites. Finally, the future development direction of CO2 electroreduction technology is discussed.    

    

* Computational examination of transition metal-salen complexes for the reduction of CO2  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391706993
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.113819")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391706993"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391706993"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391706993"))][Get cited by]]

OpenAlex: https://openalex.org/W4391706993 (Open access: False)
    
[[https://openalex.org/A5016781296][Gavin McCarver]], [[https://openalex.org/A5077586408][Taner Yildirim]], [[https://openalex.org/A5035646855][Wei Zhou]], Molecular Catalysis. 556(None)] 2024. https://doi.org/10.1016/j.mcat.2024.113819 
     
In this comprehensive study, we investigated the catalytic potential of seven transition metal-salen (TM-salen) complexes for the reduction of carbon dioxide (CO2) using ab initio methods. Our findings revealed distinct catalytic behavior among the TM-salen complexes, driven by their electronic and geometric properties. The reduction of hydrogen to H2 was most favorable on Mn-salen and Cu-salen complexes, indicating potential competition with CO2 reduction. Notably, later TM-salen complexes (Co, Ni, Cu, Zn) exhibited higher energy requirements for the initial CO2 reduction, whereas Mn- and Fe-salen complexes demonstrated potential-controlled selectivity, favoring CO2 reduction beyond HCOOH at specific thresholds. Our results highlight Cr-salen and Fe-salen complexes as promising candidates for the CO2 reduction reaction (CO2RR) catalysts due to their reduced competition with hydrogen reduction and low limiting potentials for CO2 reduction. Furthermore, the distinct reaction profiles of TM-salen complexes offer valuable insights for the design and development of efficient catalysts for sustainable CO2 conversion and other chemical transformations. These findings provide a foundation for further exploration and optimization of TM-salen complexes as viable catalysts in environmental and energy-related applications.    

    

* Defect engineering of carbon-based electrocatalysts for the CO2 reduction reaction: A review  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391768363
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/s1872-5805(24)60833-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391768363"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391768363"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391768363"))][Get cited by]]

OpenAlex: https://openalex.org/W4391768363 (Open access: True)
    
[[https://openalex.org/A5064307398][Youjun Lu]], [[https://openalex.org/A5048657205][B. S. Cheng]], [[https://openalex.org/A5055191809][Hui Zhan]], [[https://openalex.org/A5047600031][Peng Zhou]], New Carbon Materials. 39(1)] 2024. https://doi.org/10.1016/s1872-5805(24)60833-4 
     
Electrocatalytic carbon dioxide (CO2) reduction is an important way to achieve carbon neutrality by converting CO2 into high-value-added chemicals using electric energy. Carbon-based materials are widely used in various electrochemical reactions, including electrocatalytic CO2 reduction, due to their low cost and high activity. In recent years, defect engineering has attracted wide attention by constructing asymmetric defect centers in the materials, which can optimize the physicochemical properties of the material and improve its electrocatalytic activity. This review summarizes the types, methods of formation and defect characterization techniques of defective carbon-based materials. The advantages of defect engineering and the advantages and disadvantages of various defect formation methods and characterization techniques are also evaluated. Finally, the challenges of using defective carbon-based materials in electrocatalytic CO2 reduction are investigated and opportunities for their use are discussed. It is believed that this review will provide suggestions and guidance for developing defective carbon-based materials for CO2 reduction.    

    

* Development of carbon based materials for CO2 electrochemical reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391704728
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2020-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54499/sfrh/bd/143490/2019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391704728"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391704728"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391704728"))][Get cited by]]

OpenAlex: https://openalex.org/W4391704728 (Open access: False)
    
, No host. None(None)] 2020. https://doi.org/10.54499/sfrh/bd/143490/2019 
     
No abstract    

    

* (Keynote) Reversible CO2 Reduction Electrocatalysis in Solar-Powered Chemistry  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391639103
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02522517mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391639103"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391639103"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391639103"))][Get cited by]]

OpenAlex: https://openalex.org/W4391639103 (Open access: False)
    
[[https://openalex.org/A5026491082][Erwin Reisner]], ECS Meeting Abstracts. MA2023-02(52)] 2023. https://doi.org/10.1149/ma2023-02522517mtgabs 
     
Semi-artificial photosynthesis interfaces biological catalysts with synthetic materials such as electrodes or light absorbers to overcome limitations in natural and artificial photosynthesis. The benefit of using biocatalysts in electrocatalytic CO2 reduction is their electrochemical reversibility that enables their operation at very low overpotentials with high selectivity. This presentation will summarise my research group’s progress in integrating the CO2 reducing enzyme formate dehydrogenase into bespoke hierarchical 3D electrode scaffolds and the exploitation in solar-powered catalysis. I will present the electrochemical features and characterisation of the biocatalyst-material interface and provide my team's understanding of the electrochemical properties of the immobilised formate dehydrogenase. This insight allows the wiring of the biocatalyst into electrocatalytic schemes, photoelectrochemical devices and photocatalytic systems for unique CO2 utilisation reactions. The fundamental insights gained by integrating isolated formate dehydrogenase in electrodes will be presented and the case be made that this enzyme allows opening a solar-to-chemical conversion space that is currently not accessible with purly synthetic or biological catalysts (see uploaded Image as example). Recent publications: (1) Lam et al., Angew. Chem. Int. Ed., 2023, in print. (2) Bhattacharjee et al., Nat. Synth., 2023, 2, 182-92. (3) Badiani et al., J. Am. Chem. Soc., 2022, 144, 14207-16. (4) Cobb et al., Nat. Chem., 2022, 14, 417-24. (5) Edwardes Moore et al., Proc. Natl. Acad. Sci. USA, 2022, 119, e2114097199. (6) Anton Garcia et al., Nat. Synth. 2022, 1, 77-86. Reviews: (1) Fang et al., Chem. Soc. Rev., 2020, 49, 4926–52. (2) Zhang & Reisner, Nature Rev. Chem., 2020, 4, 6–21. (3) Kornienko et al., Acc. Chem. Res., 2019, 52, 1439–44. (4) Kornienko et al., Nature Nanotech., 2018, 13, 890–99    

    

* Beyond C–C coupling in CO2 reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391642660
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s44286-023-00019-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391642660"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391642660"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391642660"))][Get cited by]]

OpenAlex: https://openalex.org/W4391642660 (Open access: False)
    
[[https://openalex.org/A5079572594][Yuting Xu]], [[https://openalex.org/A5072657571][Fanglin Che]], Nature Chemical Engineering. 1(2)] 2024. https://doi.org/10.1038/s44286-023-00019-9 
     
No abstract    

    

* How to promote CO2 reduction in urban households from a micro perspective?  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391773165
:TOPICS: Rebound Effect on Energy Efficiency and Consumption, Influence of Built Environment on Active Travel, Spatial Microsimulation Models for Policy Analysis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.energy.2024.130683")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391773165"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391773165"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391773165"))][Get cited by]]

OpenAlex: https://openalex.org/W4391773165 (Open access: False)
    
[[https://openalex.org/A5065256485][Yang Xu]], [[https://openalex.org/A5068884694][Qingsong Wang]], [[https://openalex.org/A5091108483][Suqing Tian]], [[https://openalex.org/A5060392341][Mengyue Liu]], [[https://openalex.org/A5058555426][Yujie Zhang]], [[https://openalex.org/A5053118202][Xueliang Yuan]], [[https://openalex.org/A5087531458][Qiao Ma]], [[https://openalex.org/A5073459047][Chengqing Liu]], Energy. None(None)] 2024. https://doi.org/10.1016/j.energy.2024.130683 
     
Climate change has received widespread international attention. Household CO2 reduction can play an important role in mitigating climate change. Therefore, studying household carbon reduction plans is one of the research hotspots. Using a Survey-Evaluation-Optimization approach, this study constructs a methodology system for urban household CO2 reduction from micro perspective. It is found that the direct household CO2 emissions in the target community are about 1580 kgCO2/(cap·yr). Cooing and heat supply, cooking, hot water heating are stable and important components, accounting for about 70%. In some households, internal measures such as adjusting the temperature of air conditioning, canceling the insulation of water heaters, and changing travel modes show good CO2 reduction effects, reaching up to 650 kgCO2/yr. When the external measures are introduced to implement, the CO2 reduction effect of the internal measures is weakened, but the overall effect is improved. Especially when the low-carbon adjustment of power structure is introduced, the overall CO2 reduction can be increased by 35%. Based on this methodology, decision makers can obtain “one community, one policy” targeted implementation plan for household carbon reduction.    

    

* Improving a highly active tungsten-dependent formate dehydrogenase for biocatalytic reduction of CO2  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391704210
:TOPICS: Enzyme Immobilization Techniques, Biological and Synthetic Hydrogenases: Mechanisms and Applications, Deuterium Incorporation in Pharmaceutical Research
:PUBLICATION_DATE: 2020-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54499/2020.07897.bd")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391704210"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391704210"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391704210"))][Get cited by]]

OpenAlex: https://openalex.org/W4391704210 (Open access: False)
    
, No host. None(None)] 2020. https://doi.org/10.54499/2020.07897.bd 
     
No abstract    

    

* A surface strategy boosting the ethylene selectivity for CO2 reduction and in situ mechanistic insights  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391722107
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-45704-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391722107"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391722107"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391722107"))][Get cited by]]

OpenAlex: https://openalex.org/W4391722107 (Open access: True)
    
[[https://openalex.org/A5026369478][Yinchao Yao]], [[https://openalex.org/A5007250882][Tong Shi]], [[https://openalex.org/A5014698348][Wenxing Chen]], [[https://openalex.org/A5060256814][Jiu Hui Wu]], [[https://openalex.org/A5066609661][Yunying Fan]], [[https://openalex.org/A5029215411][Yichun Liu]], [[https://openalex.org/A5020824627][Liang Cao]], [[https://openalex.org/A5066940770][Zhuo Chen]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-45704-2  ([[https://www.nature.com/articles/s41467-024-45704-2.pdf][pdf]])
     
Abstract Electrochemical reduction of carbon dioxide into ethylene, as opposed to traditional industrial methods, represents a more environmentally friendly and promising technical approach. However, achieving high activity of ethylene remains a huge challenge due to the numerous possible reaction pathways. Here, we construct a hierarchical nanoelectrode composed of CuO treated with dodecanethiol to achieve elevated ethylene activity with a Faradaic efficiency reaching 79.5%. Through on in situ investigations, it is observed that dodecanethiol modification not only facilitates CO 2 transfer and enhances *CO coverage on the catalyst surfaces, but also stabilizes Cu(100) facet. Density functional theory calculations of activation energy barriers of the asymmetrical C–C coupling between *CO and *CHO further support that the greatly increased selectivity of ethylene is attributed to the thiol-stabilized Cu(100). Our findings not only provide an effective strategy to design and construct Cu-based catalysts for highly selective CO 2 to ethylene, but also offer deep insights into the mechanism of CO 2 to ethylene.    

    

* A comparison between 2D and 3D cobalt–organic framework as catalysts for electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391719630
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.heliyon.2024.e26281")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391719630"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391719630"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391719630"))][Get cited by]]

OpenAlex: https://openalex.org/W4391719630 (Open access: True)
    
[[https://openalex.org/A5071460244][Neda Sadat Barekati]], [[https://openalex.org/A5059917325][Hossein Farsi]], [[https://openalex.org/A5057292515][Alireza Farrokhi]], [[https://openalex.org/A5087760602][Shokufeh Moghiminia]], Heliyon. None(None)] 2024. https://doi.org/10.1016/j.heliyon.2024.e26281  ([[http://www.cell.com/article/S2405844024023120/pdf][pdf]])
     
Electrocatalytic CO2 reduction, as an effective way to reduce the CO2 concentration, has gained attention. In this study, we prepared ZIF-67 nanoparticles and nanosheets and investigated them as electrocatalysts for CO2 reduction. It was found that ZIF-67 nanosheets, because of their two–dimensional morphologies, provide more under–coordinated cobalt nodes and have lower overpotentials for both hydrogen evolution and CO2 reduction reactions. Also, the rate–determining step for hydrogen evolution changes from Volmer for ZIF-67 nanoparticles to Hyrovsky for ZIF-67 nanosheets. Also, the presence of Mg2+ ions in solution causes more facile CO2 reduction, especially for ZIF-67 nanosheets.    

    

* Real Time Analysis of the CO2 Reduction Reaction Products in a Cu-Gde Setup  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391663307
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02552690mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663307"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663307"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663307"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663307 (Open access: False)
    
[[https://openalex.org/A5093893773][Urban Sajevic]], [[https://openalex.org/A5065995741][Walter Agustin Agustin Parada Villarroel]], [[https://openalex.org/A5053533082][Pavlo Nikolaienko]], [[https://openalex.org/A5053735446][Karl Johann Jakob Mayrhofer]], ECS Meeting Abstracts. MA2023-02(55)] 2023. https://doi.org/10.1149/ma2023-02552690mtgabs 
     
The electrochemical reduction of CO 2 (CO 2 RR) on copper is widely regarded as one of the most promising topics in green-energy research, due to it´s potential to produce a wide array of building block chemicals while consuming CO 2 and utilizing renewable energy sources. Contrary to traditional electrolysers that utilize dissolved CO 2 , a gas diffusion electrode (GDE) approach is capable of circumventing the CO 2 diffusion dependency and hence reach economically relevant currents of >300 mA/cm². Although GDE brings eventual industrial application closer, such systems suffer from short-lived stability, mostly on account of catalyst layer deactivation and GDE flooding. As a consequence, most GDE based electrolysers are incapable of reaching a true steady-state, rendering batch-based analyses such as gas chromatography less useful when it comes to studying sensitive properties such as on-set potentials, catalyst deactivation and product selectivity shifts. In this work we present a novel set-up capable of exploring GDE-based systems and presenting both qualitative and quantitative response in real time. We base our system of a custom cell-design that is coupled to a proton transfer reaction mass spectrometer (PTR-MS) that analyses the liquid products and quadrupole mass spectrometer (QMS) for gaseous products analysis. As a proof of concept, we evaluate the CO 2 RR performance of copper based GDE´s in various electrolytes, showing how electrolyte´s pH influences properties such as product selectivity and on-set potentials. All experiments were conducted at industry-relevant currents of 200-600 mA/cm².    

    

* SO2-Tolerant Electrocatalytic Reduction of CO2 from Simulated Industrial Flue Gas  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391639141
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Sulfur Compounds Removal Technologies
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472403mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391639141"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391639141"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391639141"))][Get cited by]]

OpenAlex: https://openalex.org/W4391639141 (Open access: False)
    
[[https://openalex.org/A5041635129][Panagiotis Papangelakis]], [[https://openalex.org/A5030406224][Rui Kai Miao]], [[https://openalex.org/A5065513785][Ruihu Lu]], [[https://openalex.org/A5038064212][Adnan Ozden]], [[https://openalex.org/A5032761686][Shijie Liu]], [[https://openalex.org/A5009903384][Ning Sun]], [[https://openalex.org/A5074349896][Colin P. O’Brien]], [[https://openalex.org/A5024517164][Yongfeng Hu]], [[https://openalex.org/A5087437525][Mohsen Shakouri]], [[https://openalex.org/A5086677957][Qunfeng Xiao]], [[https://openalex.org/A5037079447][Mengsha Li]], [[https://openalex.org/A5035091701][Behrooz Khatir]], [[https://openalex.org/A5029170892][Jianan Erick Huang]], [[https://openalex.org/A5014406637][Yakun Wang]], [[https://openalex.org/A5006646798][Yurou Celine Xiao]], [[https://openalex.org/A5081844561][Feng Li]], [[https://openalex.org/A5021261667][Ali Shayesteh]], [[https://openalex.org/A5039837606][Qiang Zhang]], [[https://openalex.org/A5030254909][Pengyu Liu]], [[https://openalex.org/A5027055203][Hanqi Liu]], [[https://openalex.org/A5081771870][Kevin Golovin]], [[https://openalex.org/A5040430480][Jane Y. Howe]], [[https://openalex.org/A5071164168][Ziyun Wang]], [[https://openalex.org/A5027835055][Jun Li]], [[https://openalex.org/A5054680242][Edward H. Sargent]], [[https://openalex.org/A5077667729][David Sinton]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472403mtgabs 
     
The electrochemical reduction of CO 2 using copper-based electrocatalysts offers a route to produce high-value multicarbon (C 2+ ) products from renewable electricity (Nat. Catal. 4, 952-958 (2021); Nature 614, 262-269 (2023)). To date, the efficient electrocatalytic conversion of CO 2 to multicarbon products has only been possible when using impurity-free CO 2 sources, such as from direct air capture. The generation of such high-grade CO 2 streams is expensive, accounting for almost half of the total energy required for both capture and electroreduction processes (Nat. Catal. 4, 952-958 (2021)). Conversely, capturing CO 2 from point sources, such as industrial flue gas, is more efficient due to the higher concentration of CO 2 in the feed. However, trace amounts of sulfur dioxide (10 ~ 400 ppm SO 2 ) inherently present in these streams will significantly degrade the CO 2 conversion process. All previous attempts to convert CO 2 with SO 2 present in the feed have resulted in immediate catalyst poisoning and an irreversible loss of CO 2 conversion activity. In this study, we designed a modified catalyst layer to react a stream of dilute CO 2 containing 400 ppm SO 2 to multicarbon products with high stability and performance metrics that match or exceed those achieved with pure CO 2 streams. Driven by density function theory and COMSOL simulations, we designed an ionomer:copper:polytetrafluoroethylene (PTFE) (ICP) electrode that features both hydrophobic and highly-charged hydrophilic domains to limit water adsorption and promote CO 2 over SO 2 transport near the electrochemically active sites. This deactivates the SO 2 poisoning mechanism, thus enabling stable and efficient CO 2 conversion (see figure). Our approach achieved a sustained C 2+ Faradaic efficiency (FE) of 50% for the initial 160 hours at 100 mA cm-2. In order to improve the overall C 2+ current efficiency (j C2+ ) towards industrial scales, we applied our strategy in high-surface-area copper electrodes. We achieved CO 2 conversion in the presence of 400 ppm SO 2 with a C 2+ FE of 76% at a current density of 700 mA cm-2, surpassing what can be achieved in existing integrated CO 2 capture-electrolysis systems that use pure CO 2 . Overall, our approach provides a fully 140-fold increase in performance (FE C2+ × j C2+ ) compared to the best prior CO 2 conversion systems with added SO 2 (Nat. Nanotechnol. doi: 10.1038/s41565-022-01286-y (2023); J. Am. Chem. Soc. 141, 9902-9909 (2019)). These findings represent an important advancement in the field of CO 2 conversion and highlight the potential of our strategy for industrial-scale applications. Figure 1    

    
