#+filetags: CO2RR
#+TITLE: CO2RR
Created on Thu Jan 18 00:41:15 2024

Found 53 results from 2024-01-04 to 2024-01-18
** Pd–Mo bimetallic catalysts for electrochemical reduction of carbon dioxide to carbon monoxide   
:PROPERTIES:
:ID: https://openalex.org/W4390546350
:DOI: https://doi.org/10.1016/j.jelechem.2023.118007
:AUTHORS: Devina Thasia Wijaya, Chan Woo Lee
:HOST: Journal of Electroanalytical Chemistry
:END:

Devina Thasia Wijaya, Chan Woo Lee, Journal of Electroanalytical Chemistry. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2023.118007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390546350"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390546350"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390546350"))][Get cited by]]

OpenAlex: https://openalex.org/W4390546350
    
Devina Thasia Wijaya, Chan Woo Lee, Journal of Electroanalytical Chemistry. https://doi.org/10.1016/j.jelechem.2023.118007
    
Electrochemical CO2 reduction is considered a promising solution to mitigate the increasing CO2 emissions in the atmosphere. Despite the promising potential of this process, highly active catalysts are needed to enable its efficient operation. Mixed metal oxide (MMO) materials can promote the formation of a dynamic interface between a metal and its oxidized form under applied potential, resulting in a unique interaction with the reaction intermediates. We synthesized a Pd–Mo MMO with controlled size and composition and examined the effect of these properties on CO2 electroreduction. Electron microscopy images confirmed the homogeneous distribution of the synthesized Pd7Mo1 on a ZIF-8-derived porous carbon support, with sizes of ∼1.3 and 4.5 nm for the samples annealed at 200 and 400 °C, respectively. As shown by density functional theory calculations and X-ray photoelectron spectroscopy, adding 12.5 % Mo altered the electronic structure of Pd, enhancing CO desorption, and reducing the potential needed for CO production by up to ∼0.2 V, corresponding to a ∼40 % higher partial CO current density compared to pure Pd. This work demonstrates a facile MMO synthesis enabling particle size and composition control, which will facilitate the development of highly active MMO-derived nanoalloy materials for CO2 electroreduction.    

    

** Ultra‐Fast Pulsed Discharge Preparation of Coordinatively Unsaturated Asymmetric Copper Single‐Atom Catalysts for CO<sub>2</sub> Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390561417
:DOI: https://doi.org/10.1002/adfm.202312589
:AUTHORS: Kaiyuan Liu, Zhaolin Sun, Wenxing Chen, Xiufeng Lang, Xin Gao, Pengwan Chen
:HOST: Advanced Functional Materials
:END:

Kaiyuan Liu, Zhaolin Sun, Wenxing Chen, Xiufeng Lang, Xin Gao, Pengwan Chen, Advanced Functional Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202312589")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390561417"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390561417"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390561417"))][Get cited by]]

OpenAlex: https://openalex.org/W4390561417
    
Kaiyuan Liu, Zhaolin Sun, Wenxing Chen, Xiufeng Lang, Xin Gao, Pengwan Chen, Advanced Functional Materials. https://doi.org/10.1002/adfm.202312589
    
Abstract Single‐atom catalysts possess great potential for applications in electrochemical carbon dioxide reduction reactions. Recently, the fast and low‐cost preparation of highly efficient single‐atom catalysts remains a challenge. Herein, a high‐density current generated by pulsed discharge is employed for the formation of graphene aerogel anchored Cu single atom catalysts perfectly. The Cu atoms decomposed by Cu(NO 3 ) 2 •xH 2 O are fixed on graphene under the local transient high temperature and intense electromagnetic field. The activity and selectivity of formic acid are correlated with the coordinatively unsaturated Cu─N 1 O 1 moieties, reaching an optimal Faradaic efficiency (93.7%) at −0.9 V versus a reversible hydrogen electrode (RHE). In situ characterizations reveal that the asymmetric Cu─N/O structure in a pinched state displays better catalytic activity in CO 2 RR. Density functional theory results indicate that the Cu─N 1 O 1 sites regulate the adsorption configuration of intermediates and lower the energy barrier for the hydrogenation of * OCHO species, thereby promoting CO 2 ‐to‐HCOOH conversion.    

    

** Cu-Based Materials for Enhanced C2+ Product Selectivity in Photo-/Electro-Catalytic CO2 Reduction: Challenges and Prospects   
:PROPERTIES:
:ID: https://openalex.org/W4390588938
:DOI: https://doi.org/10.1007/s40820-023-01276-2
:AUTHORS: Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang
:HOST: Nano-Micro Letters
:END:

Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang, Nano-Micro Letters. 16(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40820-023-01276-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390588938"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390588938"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390588938"))][Get cited by]]

OpenAlex: https://openalex.org/W4390588938
    
Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang, Nano-Micro Letters. https://doi.org/10.1007/s40820-023-01276-2
    
Abstract Carbon dioxide conversion into valuable products using photocatalysis and electrocatalysis is an effective approach to mitigate global environmental issues and the energy shortages. Among the materials utilized for catalytic reduction of CO 2 , Cu-based materials are highly advantageous owing to their widespread availability, cost-effectiveness, and environmental sustainability. Furthermore, Cu-based materials demonstrate interesting abilities in the adsorption and activation of carbon dioxide, allowing the formation of C 2+ compounds through C–C coupling process. Herein, the basic principles of photocatalytic CO 2 reduction reactions (PCO 2 RR) and electrocatalytic CO 2 reduction reaction (ECO 2 RR) and the pathways for the generation C 2+ products are introduced. This review categorizes Cu-based materials into different groups including Cu metal, Cu oxides, Cu alloys, and Cu SACs, Cu heterojunctions based on their catalytic applications. The relationship between the Cu surfaces and their efficiency in both PCO 2 RR and ECO 2 RR is emphasized. Through a review of recent studies on PCO 2 RR and ECO 2 RR using Cu-based catalysts, the focus is on understanding the underlying reasons for the enhanced selectivity toward C 2+ products. Finally, the opportunities and challenges associated with Cu-based materials in the CO 2 catalytic reduction applications are presented, along with research directions that can guide for the design of highly active and selective Cu-based materials for CO 2 reduction processes in the future.    

    

** Carbon dioxide reduction utilizing a bismuth halide perovskite as immobilized photocatalyst in a 3D printed microreactor   
:PROPERTIES:
:ID: https://openalex.org/W4390574119
:DOI: https://doi.org/10.1088/1361-6439/ad1b1c
:AUTHORS: José Francisco Ruiz Cordero, Hannia López Mena, Marisol Ledezma, Leslie W. Pineda, J. Herrera
:HOST: Journal of Micromechanics and Microengineering
:END:

José Francisco Ruiz Cordero, Hannia López Mena, Marisol Ledezma, Leslie W. Pineda, J. Herrera, Journal of Micromechanics and Microengineering. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6439/ad1b1c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390574119"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390574119"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390574119"))][Get cited by]]

OpenAlex: https://openalex.org/W4390574119
    
José Francisco Ruiz Cordero, Hannia López Mena, Marisol Ledezma, Leslie W. Pineda, J. Herrera, Journal of Micromechanics and Microengineering. https://doi.org/10.1088/1361-6439/ad1b1c
    
Abstract The rising concerns about CO 2 levels in the atmosphere and energy dependency on non-renewable sources, such as fossil fuels, could find an integral solution in CO 2 photocatalytic reduction. The present work explores two alternatives to the main hindering factors for this reaction, i.e., the reactor configuration and the photocatalyst utilized. A microreactor was designed and 3D printed, providing a cheap and versatile reaction platform. Three bismuth halide perovskites, Cs 3 Bi 2 Cl 9 , Cs 3 Bi 2 I 9 , and Cs 4 MnBi 2 Cl 12 , were synthesized and characterized by their band gaps (E g ); Cs 3 Bi 2 I 9 presented the lowest E g and was therefore chosen for further evaluation as potential CO 2 -reduction photocatalyst. Aqueous-phase photocatalytic CO 2 reduction was achieved using this perovskite in the microreactor, obtaining CO as a reduction product with maximal production rates of 737 μmol g cat -1 h -1 . The reaction system was evaluated under different flow rates and light intensities. A balance between space-time and reactant feed was found to define the behavior of CO concentration and production in the microreactor. For the light intensity, it was observed that as it increased, both CO production and concentration increased due to generating more electron-hole pairs, favoring the photocatalytic reaction. With these results, Cs 3 Bi 2 I 9 perovskite immobilized in the designed microreactor demonstrates having great potential as an effective CO 2 photocatalytic reduction system.&amp;#xD;    

    

** Full-exposed Cu site of Cu2O-(1 0 0) driven high ethylene selectivity of carbon dioxide reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390640110
:DOI: https://doi.org/10.1016/j.apsusc.2023.159243
:AUTHORS: Youming Dong, Xingcheng Ma, Zhaoyong Jin, Xin Xu, Tianyi Xu, Dantong Zhang, Xiaoqiang Cui
:HOST: Applied Surface Science
:END:

Youming Dong, Xingcheng Ma, Zhaoyong Jin, Xin Xu, Tianyi Xu, Dantong Zhang, Xiaoqiang Cui, Applied Surface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2023.159243")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390640110"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390640110"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390640110"))][Get cited by]]

OpenAlex: https://openalex.org/W4390640110
    
Youming Dong, Xingcheng Ma, Zhaoyong Jin, Xin Xu, Tianyi Xu, Dantong Zhang, Xiaoqiang Cui, Applied Surface Science. https://doi.org/10.1016/j.apsusc.2023.159243
    
Cu2O shows great potential as a catalyst for the electrochemical CO2 reduction reaction (ECO2RR). However, the mechanism behind the formation of different final products from Cu2O nanostructures remains a challenge. In this study, we combine theoretical and experimental approaches to demonstrate that the full-exposed Cu sites in Cu2O (1 0 0) microcubes contribute to superior C2H4 selectivity compared to other microstructures such as Cu2O (1 1 1), (1 1 0), and (3 1 1) facets. Density functional theoretical (DFT) calculations reveal that the stronger orbital splitting between Cu 3d and O 2p orbital of Cu2O (1 0 0) facet facilitates the formation of neighboring and low valence state Cu active site, thereby enhancing *CO adsorption and C2H4 formation. These DFT results are supported by the synthesis of four kinds of Cu2O microparticles (MPs) with different exposed facets, where cubic-Cu2O with the (1 0 0) facet exhibits the highest Faradaic efficiency (61.3 %). This study has significant implications for the structural design and mechanism analysis of innovative catalysts used in ECO2RR.    

    

** Pd–Mo bimetallic catalysts for electrochemical reduction of carbon dioxide to carbon monoxide   
:PROPERTIES:
:ID: https://openalex.org/W4390546350
:DOI: https://doi.org/10.1016/j.jelechem.2023.118007
:AUTHORS: Devina Thasia Wijaya, Chan Woo Lee
:HOST: Journal of Electroanalytical Chemistry
:END:

Devina Thasia Wijaya, Chan Woo Lee, Journal of Electroanalytical Chemistry. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2023.118007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390546350"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390546350"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390546350"))][Get cited by]]

OpenAlex: https://openalex.org/W4390546350
    
Devina Thasia Wijaya, Chan Woo Lee, Journal of Electroanalytical Chemistry. https://doi.org/10.1016/j.jelechem.2023.118007
    
Electrochemical CO2 reduction is considered a promising solution to mitigate the increasing CO2 emissions in the atmosphere. Despite the promising potential of this process, highly active catalysts are needed to enable its efficient operation. Mixed metal oxide (MMO) materials can promote the formation of a dynamic interface between a metal and its oxidized form under applied potential, resulting in a unique interaction with the reaction intermediates. We synthesized a Pd–Mo MMO with controlled size and composition and examined the effect of these properties on CO2 electroreduction. Electron microscopy images confirmed the homogeneous distribution of the synthesized Pd7Mo1 on a ZIF-8-derived porous carbon support, with sizes of ∼1.3 and 4.5 nm for the samples annealed at 200 and 400 °C, respectively. As shown by density functional theory calculations and X-ray photoelectron spectroscopy, adding 12.5 % Mo altered the electronic structure of Pd, enhancing CO desorption, and reducing the potential needed for CO production by up to ∼0.2 V, corresponding to a ∼40 % higher partial CO current density compared to pure Pd. This work demonstrates a facile MMO synthesis enabling particle size and composition control, which will facilitate the development of highly active MMO-derived nanoalloy materials for CO2 electroreduction.    

    

** Regulating CHO* intermediate pathway towards the significant acceleration of photocatalytic CO2 reduction to CH4 through rGO-coated ultrafine Pd nanoparticles   
:PROPERTIES:
:ID: https://openalex.org/W4390587795
:DOI: https://doi.org/10.1016/j.cej.2023.148497
:AUTHORS: Fanlin Kong, Jing Xie, Zhenjiang Lu, Jindou Hu, Yue Feng, Yali Cao
:HOST: Chemical Engineering Journal
:END:

Fanlin Kong, Jing Xie, Zhenjiang Lu, Jindou Hu, Yue Feng, Yali Cao, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2023.148497")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390587795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390587795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390587795"))][Get cited by]]

OpenAlex: https://openalex.org/W4390587795
    
Fanlin Kong, Jing Xie, Zhenjiang Lu, Jindou Hu, Yue Feng, Yali Cao, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2023.148497
    
Tailoring catalytic reaction pathways by using reduced graphene oxide (rGO) to tune the electron-hole separation channels in the active sites of noble metals for achieving ideal yield and selectivity in photocatalytic CO2 reduction of hydrocarbon fuels remains a challenge. Herein, ternary catalyst of rGO-coated SnO2-supported noble metal Pd nanoparticles (Pd4/SnO2@rGO) has been prepared by coassembly between negatively charged graphene oxide and positively charged Pd nanoparticles. By coating with ultrathin rGO, the selectivity can be shifted from CO (44.69 % for Pd4/SnO2) toward CH4 as the prevalent species, in which the Pd nanoparticles acted as catalytic sites and electron capture sites. The rGO coating reduced the recombination of the photogenerated carriers as well as optimized the band gap and reduction potential of the catalyst. The in situ spectroscopic tests and density functional theory calculations revealed that CO2 adsorbed on Pd nanoparticles selectively formed dominant low-energy CHO* intermediates because of the generation of HCOOH* intermediates, thus providing a unique reaction pathway for the reduction of CO2 to CH4. Therefore, under sunlight irradiation, the CH4 selectivity of the catalyst is enhanced to 94.1 % with a production rate of up to 77.8 μmol·g−1·h−1. This work demonstrated the prospect to tune the electronic structure of Pd using rGO, which provided a strategy for enhancing the carbon dioxide reduction reaction and selectively obtaining CH4 products in photocatalytic systems.    

    

** Ultra‐Fast Pulsed Discharge Preparation of Coordinatively Unsaturated Asymmetric Copper Single‐Atom Catalysts for CO<sub>2</sub> Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390561417
:DOI: https://doi.org/10.1002/adfm.202312589
:AUTHORS: Kaiyuan Liu, Zhaolin Sun, Wenxing Chen, Xiufeng Lang, Xin Gao, Pengwan Chen
:HOST: Advanced Functional Materials
:END:

Kaiyuan Liu, Zhaolin Sun, Wenxing Chen, Xiufeng Lang, Xin Gao, Pengwan Chen, Advanced Functional Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202312589")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390561417"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390561417"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390561417"))][Get cited by]]

OpenAlex: https://openalex.org/W4390561417
    
Kaiyuan Liu, Zhaolin Sun, Wenxing Chen, Xiufeng Lang, Xin Gao, Pengwan Chen, Advanced Functional Materials. https://doi.org/10.1002/adfm.202312589
    
Abstract Single‐atom catalysts possess great potential for applications in electrochemical carbon dioxide reduction reactions. Recently, the fast and low‐cost preparation of highly efficient single‐atom catalysts remains a challenge. Herein, a high‐density current generated by pulsed discharge is employed for the formation of graphene aerogel anchored Cu single atom catalysts perfectly. The Cu atoms decomposed by Cu(NO 3 ) 2 •xH 2 O are fixed on graphene under the local transient high temperature and intense electromagnetic field. The activity and selectivity of formic acid are correlated with the coordinatively unsaturated Cu─N 1 O 1 moieties, reaching an optimal Faradaic efficiency (93.7%) at −0.9 V versus a reversible hydrogen electrode (RHE). In situ characterizations reveal that the asymmetric Cu─N/O structure in a pinched state displays better catalytic activity in CO 2 RR. Density functional theory results indicate that the Cu─N 1 O 1 sites regulate the adsorption configuration of intermediates and lower the energy barrier for the hydrogenation of * OCHO species, thereby promoting CO 2 ‐to‐HCOOH conversion.    

    

** Greening China’s development: Background, constraints, and policy strategies   
:PROPERTIES:
:ID: https://openalex.org/W4390709707
:DOI: https://doi.org/10.18356/9789213586112c003
:AUTHORS: 
:HOST: No host
:END:

, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18356/9789213586112c003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390709707"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390709707"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390709707"))][Get cited by]]

OpenAlex: https://openalex.org/W4390709707
    
, No host. https://doi.org/10.18356/9789213586112c003
    
China’s transition to a green, low-carbon economy is among the most essential elements needed to achieve the climate goals set down in the Paris Agreement. China has pledged it “will strive to peak carbon dioxide emissions before 2030 and achieve carbon neutrality before 2060”.1 Given the currently high emissions level in China and an economic structure with significant share of industrial sector and fossil fuel consumption, it remains a formidable challenge to realize such steep emission reduction for the 30-60 goals, as we call them in this paper.    

    

** Mustard ‘Amara’ Benefits from Superelevated CO2 While Adapting to Far-red Light Over Time   
:PROPERTIES:
:ID: https://openalex.org/W4390628599
:DOI: https://doi.org/10.21273/hortsci17522-23
:AUTHORS: Emily J. Kennebeck, Qingguo Meng
:HOST: Hortscience
:END:

Emily J. Kennebeck, Qingguo Meng, Hortscience. 59(2)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21273/hortsci17522-23")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390628599"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390628599"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390628599"))][Get cited by]]

OpenAlex: https://openalex.org/W4390628599
    
Emily J. Kennebeck, Qingguo Meng, Hortscience. https://doi.org/10.21273/hortsci17522-23
    
Compared with the ambient Earth carbon dioxide concentration (≈415 μmol⋅mol –1 ), the International Space Station has superelevated carbon dioxide (≈2800 μmol⋅mol –1 ), which can be a stressor to certain crops. Far-red light can drive plant photosynthesis and increase extension growth and biomass. However, the effects of far-red light under superelevated carbon dioxide are unclear. We grew hydroponic mustard ( Brassica carinata ) ‘Amara’ seedlings in four growth chambers using a randomized complete block design with two carbon dioxide concentrations (415 and 2800 μmol⋅mol –1 ), two lighting treatments, and two blocks at temperature and relative humidity set points of 22 °C and 40%, respectively. Each growth chamber had two lighting treatments at the same total photon flux density of 200 μmol⋅m –2 ⋅s –1 . Under the same blue and green light at 50 μmol⋅m –2 ⋅s –1 each, plants received either red light at 100 μmol⋅m –2 ⋅s –1 or red + far-red light at 50 μmol⋅m –2 ⋅s –1 each. At day 15 after planting, far-red light did not influence shoot fresh or dry mass at 415 μmol⋅mol –1 carbon dioxide, but decreased both parameters by 22% to 23% at 2800 μmol⋅mol –1 carbon dioxide. Increasing the carbon dioxide concentration increased shoot fresh and dry mass 27% to 49%, regardless of the lighting treatment. Far-red light decreased leaf area by 16% at 2800 μmol⋅mol –1 carbon dioxide, but had no effect at 415 μmol⋅mol –1 carbon dioxide. Increasing the carbon dioxide concentration increased leaf area by 21% to 33%, regardless of far-red light. Regardless of the carbon dioxide concentration, far-red light promoted stem elongation and decreased chlorophyll concentrations by 39% to 42%. These responses indicate far-red light elicited a crop-specific shade avoidance response in mustard ‘Amara’, increasing extension growth but decreasing leaf area, thereby reducing light interception and biomass. In addition, carbon dioxide enrichment up to 2800 μmol⋅mol –1 increased the biomass of mustard ‘Amara’ but decreased the biomass of other crops, indicating crop-specific tolerance to superelevated carbon dioxide. In conclusion, mustard ‘Amara’ seedlings benefit from superelevated carbon dioxide, but exhibit growth reduction under far-red light under superelevated carbon dioxide.    

    

** Solar Water Heating: Comprehensive Review, Critical Analysis and Case Study   
:PROPERTIES:
:ID: https://openalex.org/W4390616016
:DOI: https://doi.org/10.52843/cassyni.z0lx6v
:AUTHORS: Amal Herez
:HOST: No host
:END:

Amal Herez, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.52843/cassyni.z0lx6v")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390616016"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390616016"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390616016"))][Get cited by]]

OpenAlex: https://openalex.org/W4390616016
    
Amal Herez, No host. https://doi.org/10.52843/cassyni.z0lx6v
    
The increasing global demand for renewable energy sources underscores the significance of Solar Water Heating Systems (SWHS), emphasizing the need for thorough research and analysis in this domain. SWHS play a pivotal role in addressing energy efficiency and environmental sustainability, making it imperative to conduct in-depth studies on their utilization. Hence, this paper aims to provide a comprehensive overview of SWHS. It starts by explaining the principles behind these systems, including their components and classification. Moreover, this review consolidates various studies that have been conducted on SWHS to highlight both their advantages and disadvantages. Additionally, a case study is conducted in which it takes into consideration important economic and environmental factors. In particular, it focuses on several scenarios present in Lebanon such as family homes, schools, restaurants hotels and gyms to estimate potential cost savings achieved through implementing SWHS as opposed to relying solely on electric heaters. Furthermore, this investigation also examines the corresponding payback period associated with adopting SWHS along with assessing the significant reduction in carbon dioxide emissions possible if these systems were widely implemented. The findings of the study demonstrate that there is a direct correlation between the extent to which SWHS are utilized and both the payback period and reduction in CO2 emissions. It was observed that when SWHS are used more frequently, with a high percentage of time (Pr=0.9), significant advantages can be achieved. For instance, for different types of establishments such as family homes, schools, restaurants, hotels, and gyms, it was estimated that average payback periods would be 14.2 years, 4.6 years, 9.2 years, 4.4 years, and 5.3 years, respectively. These results indicate that adopting a greater dependency on SWHSs not only leads to quicker cost recovery but also significantly contributes towards reducing carbon dioxide emissions. The analysis reveals that the yearly decrease in carbon dioxide emissions per individual is 0.16 t within a household, 0.016 t per student in an educational institution, 0.04 t per customer within a dining establishment, 0.37 t for each occupied bed in a hotel accommodation, and 0.11 t per individual at a gym. This paper serves as guidelines to SWH community. Additionally, it adds a practical insights into economic and environmental issues relevant to both Lebanon and countries with similar climates.    

    

** Influence of tillage methods on carbon dioxide emissions in spring wheat crops   
:PROPERTIES:
:ID: https://openalex.org/W4390539980
:DOI: https://doi.org/10.1051/bioconf/20248206006
:AUTHORS: Evgeniy Demin, Stanislav Miller, Kirill Likhanov
:HOST: BIO web of conferences
:END:

Evgeniy Demin, Stanislav Miller, Kirill Likhanov, BIO web of conferences. 82(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/bioconf/20248206006")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390539980"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390539980"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390539980"))][Get cited by]]

OpenAlex: https://openalex.org/W4390539980
    
Evgeniy Demin, Stanislav Miller, Kirill Likhanov, BIO web of conferences. https://doi.org/10.1051/bioconf/20248206006
    
The agriculture intensification is associated with an increase in anthropogenic load on arable soils. Tillage leads to disruption of the natural process of soil formation in connection with which the soil biota activity changes and the carbon cycle is disrupted. The purpose of the study is to establish the effects of the tillage method on the carbon dioxide emission in spring wheat crops. The emission of carbon dioxide during the growing season of spring wheat varies significantly depending on the soil processing method and temperature. At the beginning of spring wheat development, the daily emission of carbon dioxide during the dump and subsurface tillage method does not exceed 36.0 and 36.2 CO 2 kg/ha using zero technology provides a reduction in production CO 2 production to 27.8 kg/ha*day. With an increase in soil temperature by July 24, the daily emission increases on a dump and subsurface background to 105.5 and 106.0 CO 2 kg/ha*day, on a zero background to 95.4 CO 2 kg/ha*day. In the future, it decreases. The total carbon losses during the dump and subsurface tillage methods are 2829 and 2793 kg/ha, the use of zero tillage technology reduces carbon losses in grain agrocenosis by 18%.    

    

** Research on the coal saving and emission reduction potential of advanced technologies in China's iron and steel industry   
:PROPERTIES:
:ID: https://openalex.org/W4390629371
:DOI: https://doi.org/10.1016/j.esd.2023.101373
:AUTHORS: Hui Huang, Mengyun Guan, Qing Wang, Jun Zhao, Qiong Yang
:HOST: Energy for Sustainable Development
:END:

Hui Huang, Mengyun Guan, Qing Wang, Jun Zhao, Qiong Yang, Energy for Sustainable Development. 78(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.esd.2023.101373")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390629371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390629371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390629371"))][Get cited by]]

OpenAlex: https://openalex.org/W4390629371
    
Hui Huang, Mengyun Guan, Qing Wang, Jun Zhao, Qiong Yang, Energy for Sustainable Development. https://doi.org/10.1016/j.esd.2023.101373
    
The coal-based energy consumption structure has led to high coal consumption and carbon emissions in China's iron and steel industry, and the task of coal saving and carbon reduction in the steel industry is difficult and urgent. The economic viability of various coal-saving and emission-reduction technologies, the extent of their coal-saving and emission-reduction potential, and the guidance on the adoption of advanced technologies are crucial issues that need to be addressed in the Chinese steel industry. This article employs the Energy-Production (E-P) analysis method and the Conservation Supply Curve (CSC) model incorporating coal consumption ratio coefficients to systematically analyze coal consumption and carbon dioxide emissions in the overall iron and steel industry and its sub-processes under different scenarios. It calculates the coal-saving emission reduction costs of 32 technologies, evaluates them comprehensively based on their coal-saving and emission-reduction potentials and cost-effectiveness, and categorizes them accordingly. According to the cost of coal saving and emission reduction as the demarcation point, a total of 19 technologies are cost-effective; according to the coal-saving emission reduction potential and cost division, 32 technologies are divided into 6 categories, among which 6 technologies such as sintering waste heat recovery technology can be used as key technologies for popularization and application. Seven technologies, such as efficient preheating technology of ladle, have high cost and low potential, which can be gradually eliminated or improved and upgraded. After the comprehensive promotion of the 32 technologies, the maximum coal saving potential is about 3.453 billion GJ, the CO2 emission reduction potential is 395 million tons, the total coal consumption of the steel industry can be reduced to about 13.904 billion GJ, and the carbon dioxide emissions can be reduced to 1.179 billion tons.    

    

** Ecological Impact versus Energy Generation by Floating Photovoltaic Power Plant for a Small Romanian Lake   
:PROPERTIES:
:ID: https://openalex.org/W4390549867
:DOI: https://doi.org/10.1109/ciees58940.2023.10378724
:AUTHORS: Gabriela Elena Dumitran, Liana Ioana Vuţă, Bogdan Popa
:HOST: No host
:END:

Gabriela Elena Dumitran, Liana Ioana Vuţă, Bogdan Popa, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/ciees58940.2023.10378724")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390549867"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390549867"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390549867"))][Get cited by]]

OpenAlex: https://openalex.org/W4390549867
    
Gabriela Elena Dumitran, Liana Ioana Vuţă, Bogdan Popa, No host. https://doi.org/10.1109/ciees58940.2023.10378724
    
The development of floating photovoltaic systems in Romania can help to the share of more than 30.7 % of the total energy produced from renewable energy sources set for the year 2030. Floating photovoltaic plants ensure the achievement of overall energy targets without affecting biodiversity and/or agricultural crops. This study evaluates the insolation and the possibility of installing this technology on Lake Făcău, Romania, to benefit from the generation of electricity but also better water quality and reduction of carbon dioxide emissions $\left(\mathrm{CO}_{2}\right)$. The obtained results are promising as Floating photovoltaic plants covering around 0.22 % of the lake surface, provide 26.76 $M W h /$ year and the estimated reduction of CO <inf xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink">2</inf> emission is 7.52 $\mathbf{t C O}_{2 \mathrm{eq}} /$ year.    

    

** Evaluation of Potential Carbon Dioxide Utilization Pathways in Uzbekistan   
:PROPERTIES:
:ID: https://openalex.org/W4390592971
:DOI: https://doi.org/10.3390/asec2023-15503
:AUTHORS: Azizbek Kamolov, Zafar Turakulov, Adham Norkobilov, Miroslav Variny, Marcos Fallanza
:HOST: No host
:END:

Azizbek Kamolov, Zafar Turakulov, Adham Norkobilov, Miroslav Variny, Marcos Fallanza, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/asec2023-15503")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390592971"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390592971"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390592971"))][Get cited by]]

OpenAlex: https://openalex.org/W4390592971
    
Azizbek Kamolov, Zafar Turakulov, Adham Norkobilov, Miroslav Variny, Marcos Fallanza, No host. https://doi.org/10.3390/asec2023-15503
    
Reaching net-zero emissions by the middle of this century requires the implementation of massive carbon dioxide (CO2) emission reduction strategies along with the reduction of other greenhouse gases on both global and country scales. Thus, carbon capture, storage, and utilization (CCSU) is a promising technology in combination with renewable energy transition. Currently, CO2 utilization has attracted much attention from the scientific community worldwide, since it can improve the economic viability of CCSU deployment by creating a market for the recovered CO2 stream. In this study, a brief assessment and comparison of potential CO2 utilization pathways in Uzbekistan, including CO2-to-chemical/fuel conversion, CO2 bio-fixation/mineralization, and the direct use of CO2, such as for enhanced hydrocarbon recovery (EHR), are conducted considering the CO2 stationary sources and site-specific conditions of the country. In addition, possible challenges and opportunities for large-scale CO2 utilization routes are also discussed. According to this assessment, there is great potential for the direct use of CO2 as a process-boosting agent for EHR in more than 22 major natural gas, crude oil, and coal reservoirs. Moreover, methanol and urea production processes can also create huge market demand for recovered CO2 as long as the conventional CO2 production processes are replaced by sustainable ones.    

    

** Cu-Based Materials for Enhanced C2+ Product Selectivity in Photo-/Electro-Catalytic CO2 Reduction: Challenges and Prospects   
:PROPERTIES:
:ID: https://openalex.org/W4390588938
:DOI: https://doi.org/10.1007/s40820-023-01276-2
:AUTHORS: Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang
:HOST: Nano-Micro Letters
:END:

Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang, Nano-Micro Letters. 16(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40820-023-01276-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390588938"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390588938"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390588938"))][Get cited by]]

OpenAlex: https://openalex.org/W4390588938
    
Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang, Nano-Micro Letters. https://doi.org/10.1007/s40820-023-01276-2
    
Abstract Carbon dioxide conversion into valuable products using photocatalysis and electrocatalysis is an effective approach to mitigate global environmental issues and the energy shortages. Among the materials utilized for catalytic reduction of CO 2 , Cu-based materials are highly advantageous owing to their widespread availability, cost-effectiveness, and environmental sustainability. Furthermore, Cu-based materials demonstrate interesting abilities in the adsorption and activation of carbon dioxide, allowing the formation of C 2+ compounds through C–C coupling process. Herein, the basic principles of photocatalytic CO 2 reduction reactions (PCO 2 RR) and electrocatalytic CO 2 reduction reaction (ECO 2 RR) and the pathways for the generation C 2+ products are introduced. This review categorizes Cu-based materials into different groups including Cu metal, Cu oxides, Cu alloys, and Cu SACs, Cu heterojunctions based on their catalytic applications. The relationship between the Cu surfaces and their efficiency in both PCO 2 RR and ECO 2 RR is emphasized. Through a review of recent studies on PCO 2 RR and ECO 2 RR using Cu-based catalysts, the focus is on understanding the underlying reasons for the enhanced selectivity toward C 2+ products. Finally, the opportunities and challenges associated with Cu-based materials in the CO 2 catalytic reduction applications are presented, along with research directions that can guide for the design of highly active and selective Cu-based materials for CO 2 reduction processes in the future.    

    

** ASTM Method for Inclusion Analysis of Prepared Green Steel   
:PROPERTIES:
:ID: https://openalex.org/W4390606734
:DOI: https://doi.org/10.1109/icmeas58693.2023.10379397
:AUTHORS: Maharishi Arvind, A. A. Adeleke, Ammasi Ayyandurai, Temitayo S. Ogedengbe, M Madan
:HOST: No host
:END:

Maharishi Arvind, A. A. Adeleke, Ammasi Ayyandurai, Temitayo S. Ogedengbe, M Madan, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/icmeas58693.2023.10379397")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390606734"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390606734"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390606734"))][Get cited by]]

OpenAlex: https://openalex.org/W4390606734
    
Maharishi Arvind, A. A. Adeleke, Ammasi Ayyandurai, Temitayo S. Ogedengbe, M Madan, No host. https://doi.org/10.1109/icmeas58693.2023.10379397
    
In the present situation, steel-making industries have turned their attention towards producing quality steel, through more feasible routes. One of the routes is the production of green steel, which is a kind of steel produced through a process which reduces the emission of carbon dioxide. Steel produced through traditional methods relies heavily on fossil fuel and coal, emitting large amounts of CO2, resulting in 6 – 7 % of global greenhouse gas emissions. Eventually, steel production using blast furnaces requires coking coal, which has limited reserves in India. An alternative approach to this is the utilization of DRI which consumes either non-coking coal or Hydrogen for its reduction, which significantly reduces carbon emission. To produce clean steel, it is necessary to undergo a complete assessment of the Non-Metallic Inclusions (NMI). Often, Types, sizes and distribution of Non-Metallic Inclusions play a major role in the steel properties. The present study has been performed to investigate the inclusion rating of steel produced from hydrogen-based DRI (HDRI) during steel making in an Induction Furnace (IF) and carbon-based DRI to understand the cleanness of steel as per ASTM E-45 standard. The kinetics of inclusion formation during steel making in induction furnaces has been studied using Classical Nucleation Theory. Thermodynamic modelling of different types of inclusion formation was carried out using the Fact Sage software package and it has been validated experimentally with the inclusion classifier of the SEM/EDS analyzer.    

    

** Pole to Ground Fault Detection Using Leakage Current for DC Distribution System with IT ground   
:PROPERTIES:
:ID: https://openalex.org/W4390563820
:DOI: https://doi.org/10.5207/jieie.2023.37.6.043
:AUTHORS: Kyung-Min Lee, Chul‐Won Park
:HOST: Journal of The Korean Institute of Illuminating and Electrical Installation Engineers
:END:

Kyung-Min Lee, Chul‐Won Park, Journal of The Korean Institute of Illuminating and Electrical Installation Engineers. 37(6)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5207/jieie.2023.37.6.043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390563820"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390563820"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390563820"))][Get cited by]]

OpenAlex: https://openalex.org/W4390563820
    
Kyung-Min Lee, Chul‐Won Park, Journal of The Korean Institute of Illuminating and Electrical Installation Engineers. https://doi.org/10.5207/jieie.2023.37.6.043
    
Recently, policies such as expansion of distributed power sources, and transition to electric vehicles are being promoted to reduce carbon dioxide. Most distributed power sources generate DC power, so when the direct current system is activated, it is effective in many aspects, including power loss reduction, grid connection efficiency, and economic feasibility. As a DC system protection plan is required according to the grounding system, the fault detection method for Pole to Ground Fault is very important. In this paper, we propose a technique using DWT (Discrete Wavelet Transform) for Pole to Ground Fault detection by leakage current in DC distribution system with IT ground system. First, after modeling the IT grounding DC distribution system using PSCAD s/w, Pole to Ground fault simulation is performed while varying the fault point and fault resistance. After implementing the proposed fault detection using MATLAB s/w, the performance is verified by comparing the proposed technique with the traditional technique through insulation resistance measurement.    

    

** Provision of Reliable Power Supply for the First Category of Consumers Because of Renewable Energy Sources   
:PROPERTIES:
:ID: https://openalex.org/W4390541888
:DOI: https://doi.org/10.1007/978-3-031-51127-1_46
:AUTHORS: Irina Kirpichnikova, Sergey Shipilov
:HOST: Lecture notes in electrical engineering
:END:

Irina Kirpichnikova, Sergey Shipilov, Lecture notes in electrical engineering. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-3-031-51127-1_46")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390541888"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390541888"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390541888"))][Get cited by]]

OpenAlex: https://openalex.org/W4390541888
    
Irina Kirpichnikova, Sergey Shipilov, Lecture notes in electrical engineering. https://doi.org/10.1007/978-3-031-51127-1_46
    
This article describes the objects of the first category of power supply in the example of maternity hospital of the clinic of the Medical University of Chelyabinsk. There is a current power Supply Scheme and a group of electric consumers. The costs are calculated for electricity consumption under various schemes of power supply of the facility. It is also shown how the reduction in electricity consumption is associated with a reduction of carbon dioxide emissions into the atmosphere. It was suggested to use renewable energy sources as a way of power supply of the objects of the first category, such as wind turbines and Solar power plants. The cost of the equipment was calculated based on technical characteristics. It was also calculated the cost of savings on electricity consumptions from centralized sources. The benefits and the possibility of application of the renewable energy sources for objects of the first category are shown.    

    

** Effects of Isopropanol Additive on Exhaust Emissions in Gasoline Engines   
:PROPERTIES:
:ID: https://openalex.org/W4390549811
:DOI: https://doi.org/10.1109/ciees58940.2023.10378725
:AUTHORS: Elitsa Nakova, Simeon Iliev, Kiril Hadjiev
:HOST: No host
:END:

Elitsa Nakova, Simeon Iliev, Kiril Hadjiev, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/ciees58940.2023.10378725")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390549811"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390549811"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390549811"))][Get cited by]]

OpenAlex: https://openalex.org/W4390549811
    
Elitsa Nakova, Simeon Iliev, Kiril Hadjiev, No host. https://doi.org/10.1109/ciees58940.2023.10378725
    
The steady increase in transport needs worldwide, especially in areas with dense populations, makes it necessary to seek methods and means of using sustainable alternatives to conventional fuels to reduce the use of fossil fuels and significantly reduce environmental pollution. This study investigated the effectiveness of Isopropanol as a blend with gasoline to improve the environmental performance of internal combustion engines. Besides, as an alternative fuel isopropyl alcohol can also be considered as a renewable source of energy. Alcohols, as an alternative energy source, are considered with priority, building on their characteristics. Isopropanol, as part of the group of alcohols, has been investigated with regard to its potential to improve the mixing and combustion process and also to influence the laminar flame speed as well as the combustion rate compared to conventional gasoline in internal combustion engines. The study focused on its impact on emissions, specifically hydrocarbons, carbon monoxide, carbon dioxide and nitrogen oxides. The study was carried out in a laboratory environment, on a 4-cylinder gasoline engine, for the purpose of the study gasoline and gasoline-Isopropanol mixtures were used in the ratio as follows: 95% gasoline and 5% Isopropanol (IP5), 90% gasoline and 10% Isopropanol (IP10), 85% gasoline and 15% Isopropanol (IP15) and 80% gasoline and 20% Isopropanol (IP20). Due to the properties of Isopropanol there is a reduction of HC, CO, CO2 and NOx emissions, the most favorable for this engine is the fuel mixture with Isopropanol content between 10%-15%.    

    

** A Synergistic Dual-Functional Silver-Manganese Dioxide-CNTs Ternary Composite Electrocatalyst for Solid-State Zinc-Air Battery   
:PROPERTIES:
:ID: https://openalex.org/W4390561537
:DOI: https://doi.org/10.20944/preprints202401.0200.v1
:AUTHORS: Guoqing Zhang, Tuan‐Wu Cao, Peng Zhang, Shuying Kong, Binbin Jin
:HOST: No host
:END:

Guoqing Zhang, Tuan‐Wu Cao, Peng Zhang, Shuying Kong, Binbin Jin, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.20944/preprints202401.0200.v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390561537"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390561537"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390561537"))][Get cited by]]

OpenAlex: https://openalex.org/W4390561537
    
Guoqing Zhang, Tuan‐Wu Cao, Peng Zhang, Shuying Kong, Binbin Jin, No host. https://doi.org/10.20944/preprints202401.0200.v1
    
Exploring effective oxygen reduction reaction (ORR) electrocatalysts is crucial for progress in solid-state alkaline zinc-air batteries (ZAB). In this paper, silver-manganese dioxide-carbon nanotubes (SMC) ternary composites, which function as Electrocatalyst for air Electrodes, was produced via the pyrolysis of silver permanganate under microwave irradiation in one step. A scanning electron microscope (SEM), X-ray diffraction (XRD), and an energy dispersion spectrometer (EDS) have consistently determined that SMC consists of silver and alpha-manganese dioxide, which anchored on the surface of CNTs. Through polarization and chronoamperometery curves, the electrocatalytic activity of SMC for ORR was examined. The results reveal that SMC has higher catalytic activity than the chemically produced electrocatalyst for ORR in alkaline condition. Finally, a solid-state zinc-air cell with an electrocatalyst was constructed and tested. Constant current discharge curve of the zinc-air cell with SMC has a long discharge voltage plateau and a 60.03 mAh capacity at 30 mA &amp;middot; cm&amp;minus;2 . The mechanism of improvement in electrocatalytic activity was also discussed. In a summary, the strategy described in this study and the electrocatalyst produced can be regarded as an effective method for making a robust oxygen reduction catalyst toward solid-state zinc-air batteries.    

    

** Does digital transformation affect carbon performance through talent? The moderating role of employee structure   
:PROPERTIES:
:ID: https://openalex.org/W4390543690
:DOI: https://doi.org/10.1016/j.jclepro.2024.140581
:AUTHORS: Qiuling Chen, Zhiqi Gong, Jingfei Wu, Tianchi Wang
:HOST: Journal of Cleaner Production
:END:

Qiuling Chen, Zhiqi Gong, Jingfei Wu, Tianchi Wang, Journal of Cleaner Production. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jclepro.2024.140581")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390543690"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390543690"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390543690"))][Get cited by]]

OpenAlex: https://openalex.org/W4390543690
    
Qiuling Chen, Zhiqi Gong, Jingfei Wu, Tianchi Wang, Journal of Cleaner Production. https://doi.org/10.1016/j.jclepro.2024.140581
    
Industrial process consumes large amounts of energy and emits substantial carbon dioxide. The implementation of digital transformation is crucial for industrial enterprises to move towards low-carbon transformation. Existing studies on mediating effect between digitization and carbon emissions reduction have not adequately explored the role of talent. By selecting Chinese industrial listed enterprises during 2012–2021 as research samples, we apply the mediation model to investigate the influence of digital transformation on carbon performance and to explore the mediating effect of talent. Moreover, the moderated mediation model is used to detect the moderating effects of excess employee and employee density, named employee structure. We find that digital transformation has a positive impact on carbon performance. Talent performs as a mediating function in the link between digital transformation and carbon performance. The mediating effect of talent can be positively moderated by excess employee and employee density, respectively. This positive mediating effect increases with the decrease of excess employee or the increase of employee density. Our research findings suggest that government should encourage entire industrial sector to implement digital transformation, and enterprises should take full advantage of digital transformation for the low-carbon development.    

    

** The role of financial and trade globalization in enhancing environmental sustainability: Evaluating the effectiveness of carbon taxation and renewable energy in EU member countries   
:PROPERTIES:
:ID: https://openalex.org/W4390587099
:DOI: https://doi.org/10.1016/j.bir.2024.01.004
:AUTHORS: Ayhan Nadiri, Veclal GÜNDÜZ, Tomiwa Sunday Adebayo
:HOST: Borsa Istanbul Review
:END:

Ayhan Nadiri, Veclal GÜNDÜZ, Tomiwa Sunday Adebayo, Borsa Istanbul Review. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.bir.2024.01.004")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390587099"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390587099"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390587099"))][Get cited by]]

OpenAlex: https://openalex.org/W4390587099
    
Ayhan Nadiri, Veclal GÜNDÜZ, Tomiwa Sunday Adebayo, Borsa Istanbul Review. https://doi.org/10.1016/j.bir.2024.01.004
    
The study addresses the pressing issue of environmental degradation, pinpointing carbon dioxide (CO2) emissions as its primary driver, posing a threat to global environmental sustainability, including the member countries of the European Union (EU). Global warming problems persist, but previous studies have not adequately explored the factors that contribute to a reduction in carbon emissions in EU countries. The paper fills the gap by assessing the efficacy of carbon tax and eco-innovation in mitigating CO2 levels from 1994 to 2019, considering the influence of renewable energy and various aspects of globalization. The study establishes long-term associations among the indicators examined using advanced methodologies, including the cross-sectional autoregressive distributed lag approach and the Westerlund cointegration method. Notably, the results highlight that carbon taxes, eco-innovation, renewable energy, and globalization contribute to slowing environmental deterioration, and economic progress plays a role in mitigating environmental sustainability challenges in EU member states. These findings reinforce the importance of robust strategies for reducing CO2 emissions and minimizing adverse environmental impacts.    

    

** Hydrothermal synthesis of MnO2 nanorods for efficient electrochemical detection of environmental anthropogenic pollutants and nitrobenzene   
:PROPERTIES:
:ID: https://openalex.org/W4390611242
:DOI: https://doi.org/10.1016/j.inoche.2023.112015
:AUTHORS: Vasanthi Chellappa, N. Meenakshisundaram, Jamespandi Annaraj, Suresh Sagadevan
:HOST: Inorganic Chemistry Communications
:END:

Vasanthi Chellappa, N. Meenakshisundaram, Jamespandi Annaraj, Suresh Sagadevan, Inorganic Chemistry Communications. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.inoche.2023.112015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390611242"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390611242"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390611242"))][Get cited by]]

OpenAlex: https://openalex.org/W4390611242
    
Vasanthi Chellappa, N. Meenakshisundaram, Jamespandi Annaraj, Suresh Sagadevan, Inorganic Chemistry Communications. https://doi.org/10.1016/j.inoche.2023.112015
    
Glassy carbon (GC) electrodes have been modified/fabricated with nanoscale manganese dioxide (MnO2) rods for efficient detection of the toxic anthropogenic pollutant and nitrobenzene (NB) in real water. The MnO2 nanorods were prepared by a hydrothermal process, and their morphology was confirmed by various characterization techniques. They were used to modify a glassy carbon (MnO2/GCE) electrode surface, which was optimized and developed as an electrochemical detector under different experimental conditions to obtain good sensitivity and selectivity. It has shown excellent electrocatalytic activity for the reduction of NB to phenylhydroxylamine as a product. The calibration plots were constructed using the observed data of the differential pulse voltametric technique between the linear range of 0.03 µM–2 µM with a detection limit of 0.025 μM which displayed great stability and reproducibility as well as the detection of NB in the real water sample.    

    

** Decarbonisation of the steel industry: theoretical and practical approaches with analysis of the situation in the steel sector in Poland   
:PROPERTIES:
:ID: https://openalex.org/W4390678737
:DOI: https://doi.org/10.46544/ams.v28i3.08
:AUTHORS: 
:HOST: Acta Montanistica Slovaca
:END:

, Acta Montanistica Slovaca. 28(v28/i3)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.46544/ams.v28i3.08")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390678737"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390678737"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390678737"))][Get cited by]]

OpenAlex: https://openalex.org/W4390678737
    
, Acta Montanistica Slovaca. https://doi.org/10.46544/ams.v28i3.08
    
Climate change and environmental degradation are nowadays the key challenges of the industries in Europe (according to the European Green Deal). The primary goal is to achieve a climate-neutral in Europe by 2050. Technologies with carbon dioxide (CO2) emissions should be completely stopped in the future. The iron and steel industry is among the manufacturing industries with high CO2 emissions in Europe. In Poland, steel mills produce about 9 million tonnes of steel per year (average for 2000-2021). Steel mills in Poland use two steel production technologies, EAF and BOF. The first technology is highly energy intensive, and the second has high emissions of CO2. There will be no BF technology in zero-emission smelters; this technology will be replaced by DRI (i.e., direct iron reduction) installations, and electric furnaces will be powered by renewable energy. The paper consists of two parts: a theoretical section and a practical section. In the first section, the way the steel industry moves towards climate neutrality was presented. The part of the paper was realized based on European documents and a literature review. The second part was an analysis of the CO2 emission in the steel industry in Poland. The analysis was realized based on data from the Polish Steel Association.    

    

** Reassessing the need for carbon dioxide removal: moral implications of alternative climate target pathways   
:PROPERTIES:
:ID: https://openalex.org/W4390608678
:DOI: https://doi.org/10.1017/sus.2023.21
:AUTHORS: Lieske Voget-Kleschin, Christian Baatz, Clare Heyward, Detlef van Vuuren, Nadine Mengis
:HOST: Global Sustainability
:END:

Lieske Voget-Kleschin, Christian Baatz, Clare Heyward, Detlef van Vuuren, Nadine Mengis, Global Sustainability. 7(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1017/sus.2023.21")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390608678"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390608678"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390608678"))][Get cited by]]

OpenAlex: https://openalex.org/W4390608678
    
Lieske Voget-Kleschin, Christian Baatz, Clare Heyward, Detlef van Vuuren, Nadine Mengis, Global Sustainability. https://doi.org/10.1017/sus.2023.21
    
Abstract Non-technical summary Scenarios compatible with the Paris agreement's temperature goal of 1.5 °C involve carbon dioxide removal measures – measures that actively remove CO 2 from the atmosphere – on a massive scale. Such large-scale implementations raise significant ethical problems. Van Vuuren et al. (2018), as well as the current IPCC scenarios, show that reduction in energy and or food demand could reduce the need for such activities. There is some reluctance to discuss such societal changes. However, we argue that policy measures enabling societal changes are not necessarily ethically problematic. Therefore, they should be discussed alongside techno-optimistic approaches in any kind of discussions about how to respond to climate change. Technical summary The 1.5 °C goal has given impetus to carbon dioxide removal (CDR) measures, such as bioenergy combined with carbon capture and storage, or afforestation. However, land-based CDR options compete with food production and biodiversity protection. Van Vuuren et al. (2018) looked at alternative pathways including lifestyle changes, low-population projections, or non-CO 2 greenhouse gas mitigation, to reach the 1.5 °C temperature objective. Underlined by the recently published IPCC AR6 WGIII report, they show that demand-side management measures are likely to reduce the need for CDR. Yet, policy measures entailed in these scenarios could be associated with ethical problems themselves. In this paper, we therefore investigate ethical implications of four alternative pathways as proposed by Van Vuuren et al. (2018). We find that emission reduction options such as lifestyle changes and reducing population, which are typically perceived as ethically problematic, might be less so on further inspection. In contrast, options associated with less societal transformation and more techno-optimistic approaches turn out to be in need of further scrutiny. The vast majority of emission reduction options considered are not intrinsically ethically problematic; rather everything rests on the precise implementation. Explicitly addressing ethical considerations when developing, advancing, and using integrated assessment scenarios could reignite debates about previously overlooked topics and thereby support necessary societal discourse. Social media summary Policy measures enabling societal changes are not necessarily as ethically problematic as commonly presumed and reduce the need for large-scale CDR.    

    

** Multi-objective genetic algorithm optimization of energy efficiency and biomass concentration of Synechococcus HS-9 cultivation for third-generation biodiesel feedstock   
:PROPERTIES:
:ID: https://openalex.org/W4390637025
:DOI: https://doi.org/10.1016/j.cscee.2024.100614
:AUTHORS: Arif Rahman, Kania Dyah Nastiti, Nining Betawati Prihantini, M.A.M. Oktaufik, Surat Indrijarso, Alfred Kampira Levison, Ridho Irwansyah, Nasruddin Nasruddin
:HOST: Case Studies in Chemical and Environmental Engineering
:END:

Arif Rahman, Kania Dyah Nastiti, Nining Betawati Prihantini, M.A.M. Oktaufik, Surat Indrijarso, Alfred Kampira Levison, Ridho Irwansyah, Nasruddin Nasruddin, Case Studies in Chemical and Environmental Engineering. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cscee.2024.100614")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390637025"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390637025"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390637025"))][Get cited by]]

OpenAlex: https://openalex.org/W4390637025
    
Arif Rahman, Kania Dyah Nastiti, Nining Betawati Prihantini, M.A.M. Oktaufik, Surat Indrijarso, Alfred Kampira Levison, Ridho Irwansyah, Nasruddin Nasruddin, Case Studies in Chemical and Environmental Engineering. https://doi.org/10.1016/j.cscee.2024.100614
    
Microalgae is a sustainable biological resource since it can be used in biodiesel production, pharmaceutical development, nutritional supplements, carbon dioxide sequestration, and wastewater remediation. Due to its high lipid content and low carbon dioxide emissions, microalgae-derived biodiesel can replace fossil fuels. Microalgae biomass production involves cultivation, harvesting, and drying. To develop microalgae and produce high-quality biomass, culture procedures must be optimized. Microalgae cultivation is affected by a range of physical and chemical parameters, including light intensity (I), temperature (T), carbon dioxide (CO2), pH, dissolved oxygen (DO), and oxidation reduction potential (ORP). The objective of this study is to examine the impact of physico-chemical factors on the cultivation process of Synechococcus HS-9 in order to generate dry biomass. ANN and multi-objective genetic algorithms will also be used to optimize cultivation. The five main procedures of this study are: 1) preparation of the cultivation medium; 2) Synechococcus HS-9 inoculum and utilization of a photobioreactor; 3) inoculation; 4) cultivation and physical-chemical parameter data collection; and 5) prediction and optimization. The physico-chemical properties of Synechococcus HS-9 were measured during cultivation. The average values of these parameters were found to be 439 to 325 7 μmol m−2s−1 for light conditions and 190–200 μmol m−2s−1 for dark conditions. During cultivation, T ranged from 29 to 32 °C and CO2 from 82 to 84 ppm. Most pH levels are between 8 and 7.5. The dissolved oxygen (DO) concentration drops from 15 to 3 mg/l. The ORP also fluctuates, dropping from 170 mV to 155 mV and then rising to 180 mV. Based on multi-objective optimization, the optimal values for energy efficiency (ղ) and biomass concentration (C) are 0.043 % and 4.61 × 10−5 mg/ml, respectively. The optimal condition is achieved when the light intensity (I): 254.7 μmol m−2s−1, temperature (T): 29.7 °C, CO2 concentration: 83.4 ppm, pH: 8.6, dissolved oxygen (DO): 6.0 mg/l, and ORP: 149.1 mV.    

    

** Electrocatalytic and Photocatalytic CO2 Methanation: From Reaction Fundamentals to Catalyst Developments   
:PROPERTIES:
:ID: https://openalex.org/W4390614494
:DOI: https://doi.org/10.1002/cctc.202301406
:AUTHORS: Junfeng Tian, Wenqing Xu, Jiajian Gao, Tong Zhu, Guangwen Xu, Ziyi Zhong, Fabing Su
:HOST: ChemCatChem
:END:

Junfeng Tian, Wenqing Xu, Jiajian Gao, Tong Zhu, Guangwen Xu, Ziyi Zhong, Fabing Su, ChemCatChem. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301406")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390614494"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390614494"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390614494"))][Get cited by]]

OpenAlex: https://openalex.org/W4390614494
    
Junfeng Tian, Wenqing Xu, Jiajian Gao, Tong Zhu, Guangwen Xu, Ziyi Zhong, Fabing Su, ChemCatChem. https://doi.org/10.1002/cctc.202301406
    
Transitioning from fossil fuels to renewable energy sources is demanded due to the gradual depletion of petroleum oil/gas and the environmental impact of carbon dioxide (CO2) emissions into the atmosphere. Electrocatalytic and photocatalytic CO2 reduction to methane (CH4) using renewable energy sources is crucial for sustainable chemical/fuel production and greenhouse gas reduction. In recent years, extensive research has focused on understanding the fundamental aspects of the two approaches, such as reaction mechanisms and active sites, and exploring/designing novel catalytic materials. This review initially discusses the reaction fundamentals, including performance evaluation indexes, reactors, and mechanisms, to understand the catalytic reactions. Subsequently, various catalyst preparation strategies and characterization methods are summarized, trying to outline the catalyst design principle based on the obtained understanding of the reaction mechanisms. Finally, research challenges and perspectives for future development in this area are discussed and presented. It is expected to provide a comprehensive understanding of the photo/electrocatalytic CO2 methanation, valuable knowledge to novice researchers, and a helpful reference for future research endeavors.    

    

** Carbon dioxide reduction utilizing a bismuth halide perovskite as immobilized photocatalyst in a 3D printed microreactor   
:PROPERTIES:
:ID: https://openalex.org/W4390574119
:DOI: https://doi.org/10.1088/1361-6439/ad1b1c
:AUTHORS: José Francisco Ruiz Cordero, Hannia López Mena, Marisol Ledezma, Leslie W. Pineda, J. Herrera
:HOST: Journal of Micromechanics and Microengineering
:END:

José Francisco Ruiz Cordero, Hannia López Mena, Marisol Ledezma, Leslie W. Pineda, J. Herrera, Journal of Micromechanics and Microengineering. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6439/ad1b1c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390574119"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390574119"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390574119"))][Get cited by]]

OpenAlex: https://openalex.org/W4390574119
    
José Francisco Ruiz Cordero, Hannia López Mena, Marisol Ledezma, Leslie W. Pineda, J. Herrera, Journal of Micromechanics and Microengineering. https://doi.org/10.1088/1361-6439/ad1b1c
    
Abstract The rising concerns about CO 2 levels in the atmosphere and energy dependency on non-renewable sources, such as fossil fuels, could find an integral solution in CO 2 photocatalytic reduction. The present work explores two alternatives to the main hindering factors for this reaction, i.e., the reactor configuration and the photocatalyst utilized. A microreactor was designed and 3D printed, providing a cheap and versatile reaction platform. Three bismuth halide perovskites, Cs 3 Bi 2 Cl 9 , Cs 3 Bi 2 I 9 , and Cs 4 MnBi 2 Cl 12 , were synthesized and characterized by their band gaps (E g ); Cs 3 Bi 2 I 9 presented the lowest E g and was therefore chosen for further evaluation as potential CO 2 -reduction photocatalyst. Aqueous-phase photocatalytic CO 2 reduction was achieved using this perovskite in the microreactor, obtaining CO as a reduction product with maximal production rates of 737 μmol g cat -1 h -1 . The reaction system was evaluated under different flow rates and light intensities. A balance between space-time and reactant feed was found to define the behavior of CO concentration and production in the microreactor. For the light intensity, it was observed that as it increased, both CO production and concentration increased due to generating more electron-hole pairs, favoring the photocatalytic reaction. With these results, Cs 3 Bi 2 I 9 perovskite immobilized in the designed microreactor demonstrates having great potential as an effective CO 2 photocatalytic reduction system.&amp;#xD;    

    

** Full-exposed Cu site of Cu2O-(1 0 0) driven high ethylene selectivity of carbon dioxide reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390640110
:DOI: https://doi.org/10.1016/j.apsusc.2023.159243
:AUTHORS: Youming Dong, Xingcheng Ma, Zhaoyong Jin, Xin Xu, Tianyi Xu, Dantong Zhang, Xiaoqiang Cui
:HOST: Applied Surface Science
:END:

Youming Dong, Xingcheng Ma, Zhaoyong Jin, Xin Xu, Tianyi Xu, Dantong Zhang, Xiaoqiang Cui, Applied Surface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2023.159243")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390640110"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390640110"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390640110"))][Get cited by]]

OpenAlex: https://openalex.org/W4390640110
    
Youming Dong, Xingcheng Ma, Zhaoyong Jin, Xin Xu, Tianyi Xu, Dantong Zhang, Xiaoqiang Cui, Applied Surface Science. https://doi.org/10.1016/j.apsusc.2023.159243
    
Cu2O shows great potential as a catalyst for the electrochemical CO2 reduction reaction (ECO2RR). However, the mechanism behind the formation of different final products from Cu2O nanostructures remains a challenge. In this study, we combine theoretical and experimental approaches to demonstrate that the full-exposed Cu sites in Cu2O (1 0 0) microcubes contribute to superior C2H4 selectivity compared to other microstructures such as Cu2O (1 1 1), (1 1 0), and (3 1 1) facets. Density functional theoretical (DFT) calculations reveal that the stronger orbital splitting between Cu 3d and O 2p orbital of Cu2O (1 0 0) facet facilitates the formation of neighboring and low valence state Cu active site, thereby enhancing *CO adsorption and C2H4 formation. These DFT results are supported by the synthesis of four kinds of Cu2O microparticles (MPs) with different exposed facets, where cubic-Cu2O with the (1 0 0) facet exhibits the highest Faradaic efficiency (61.3 %). This study has significant implications for the structural design and mechanism analysis of innovative catalysts used in ECO2RR.    

    

** Pd–Mo bimetallic catalysts for electrochemical reduction of carbon dioxide to carbon monoxide   
:PROPERTIES:
:ID: https://openalex.org/W4390546350
:DOI: https://doi.org/10.1016/j.jelechem.2023.118007
:AUTHORS: Devina Thasia Wijaya, Chan Woo Lee
:HOST: Journal of Electroanalytical Chemistry
:END:

Devina Thasia Wijaya, Chan Woo Lee, Journal of Electroanalytical Chemistry. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2023.118007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390546350"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390546350"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390546350"))][Get cited by]]

OpenAlex: https://openalex.org/W4390546350
    
Devina Thasia Wijaya, Chan Woo Lee, Journal of Electroanalytical Chemistry. https://doi.org/10.1016/j.jelechem.2023.118007
    
Electrochemical CO2 reduction is considered a promising solution to mitigate the increasing CO2 emissions in the atmosphere. Despite the promising potential of this process, highly active catalysts are needed to enable its efficient operation. Mixed metal oxide (MMO) materials can promote the formation of a dynamic interface between a metal and its oxidized form under applied potential, resulting in a unique interaction with the reaction intermediates. We synthesized a Pd–Mo MMO with controlled size and composition and examined the effect of these properties on CO2 electroreduction. Electron microscopy images confirmed the homogeneous distribution of the synthesized Pd7Mo1 on a ZIF-8-derived porous carbon support, with sizes of ∼1.3 and 4.5 nm for the samples annealed at 200 and 400 °C, respectively. As shown by density functional theory calculations and X-ray photoelectron spectroscopy, adding 12.5 % Mo altered the electronic structure of Pd, enhancing CO desorption, and reducing the potential needed for CO production by up to ∼0.2 V, corresponding to a ∼40 % higher partial CO current density compared to pure Pd. This work demonstrates a facile MMO synthesis enabling particle size and composition control, which will facilitate the development of highly active MMO-derived nanoalloy materials for CO2 electroreduction.    

    

** Regulating CHO* intermediate pathway towards the significant acceleration of photocatalytic CO2 reduction to CH4 through rGO-coated ultrafine Pd nanoparticles   
:PROPERTIES:
:ID: https://openalex.org/W4390587795
:DOI: https://doi.org/10.1016/j.cej.2023.148497
:AUTHORS: Fanlin Kong, Jing Xie, Zhenjiang Lu, Jindou Hu, Yue Feng, Yali Cao
:HOST: Chemical Engineering Journal
:END:

Fanlin Kong, Jing Xie, Zhenjiang Lu, Jindou Hu, Yue Feng, Yali Cao, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2023.148497")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390587795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390587795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390587795"))][Get cited by]]

OpenAlex: https://openalex.org/W4390587795
    
Fanlin Kong, Jing Xie, Zhenjiang Lu, Jindou Hu, Yue Feng, Yali Cao, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2023.148497
    
Tailoring catalytic reaction pathways by using reduced graphene oxide (rGO) to tune the electron-hole separation channels in the active sites of noble metals for achieving ideal yield and selectivity in photocatalytic CO2 reduction of hydrocarbon fuels remains a challenge. Herein, ternary catalyst of rGO-coated SnO2-supported noble metal Pd nanoparticles (Pd4/SnO2@rGO) has been prepared by coassembly between negatively charged graphene oxide and positively charged Pd nanoparticles. By coating with ultrathin rGO, the selectivity can be shifted from CO (44.69 % for Pd4/SnO2) toward CH4 as the prevalent species, in which the Pd nanoparticles acted as catalytic sites and electron capture sites. The rGO coating reduced the recombination of the photogenerated carriers as well as optimized the band gap and reduction potential of the catalyst. The in situ spectroscopic tests and density functional theory calculations revealed that CO2 adsorbed on Pd nanoparticles selectively formed dominant low-energy CHO* intermediates because of the generation of HCOOH* intermediates, thus providing a unique reaction pathway for the reduction of CO2 to CH4. Therefore, under sunlight irradiation, the CH4 selectivity of the catalyst is enhanced to 94.1 % with a production rate of up to 77.8 μmol·g−1·h−1. This work demonstrated the prospect to tune the electronic structure of Pd using rGO, which provided a strategy for enhancing the carbon dioxide reduction reaction and selectively obtaining CH4 products in photocatalytic systems.    

    

** Ultra‐Fast Pulsed Discharge Preparation of Coordinatively Unsaturated Asymmetric Copper Single‐Atom Catalysts for CO<sub>2</sub> Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390561417
:DOI: https://doi.org/10.1002/adfm.202312589
:AUTHORS: Kaiyuan Liu, Zhaolin Sun, Wenxing Chen, Xiufeng Lang, Xin Gao, Pengwan Chen
:HOST: Advanced Functional Materials
:END:

Kaiyuan Liu, Zhaolin Sun, Wenxing Chen, Xiufeng Lang, Xin Gao, Pengwan Chen, Advanced Functional Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202312589")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390561417"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390561417"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390561417"))][Get cited by]]

OpenAlex: https://openalex.org/W4390561417
    
Kaiyuan Liu, Zhaolin Sun, Wenxing Chen, Xiufeng Lang, Xin Gao, Pengwan Chen, Advanced Functional Materials. https://doi.org/10.1002/adfm.202312589
    
Abstract Single‐atom catalysts possess great potential for applications in electrochemical carbon dioxide reduction reactions. Recently, the fast and low‐cost preparation of highly efficient single‐atom catalysts remains a challenge. Herein, a high‐density current generated by pulsed discharge is employed for the formation of graphene aerogel anchored Cu single atom catalysts perfectly. The Cu atoms decomposed by Cu(NO 3 ) 2 •xH 2 O are fixed on graphene under the local transient high temperature and intense electromagnetic field. The activity and selectivity of formic acid are correlated with the coordinatively unsaturated Cu─N 1 O 1 moieties, reaching an optimal Faradaic efficiency (93.7%) at −0.9 V versus a reversible hydrogen electrode (RHE). In situ characterizations reveal that the asymmetric Cu─N/O structure in a pinched state displays better catalytic activity in CO 2 RR. Density functional theory results indicate that the Cu─N 1 O 1 sites regulate the adsorption configuration of intermediates and lower the energy barrier for the hydrogenation of * OCHO species, thereby promoting CO 2 ‐to‐HCOOH conversion.    

    

** Greening China’s development: Background, constraints, and policy strategies   
:PROPERTIES:
:ID: https://openalex.org/W4390709707
:DOI: https://doi.org/10.18356/9789213586112c003
:AUTHORS: 
:HOST: No host
:END:

, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18356/9789213586112c003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390709707"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390709707"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390709707"))][Get cited by]]

OpenAlex: https://openalex.org/W4390709707
    
, No host. https://doi.org/10.18356/9789213586112c003
    
China’s transition to a green, low-carbon economy is among the most essential elements needed to achieve the climate goals set down in the Paris Agreement. China has pledged it “will strive to peak carbon dioxide emissions before 2030 and achieve carbon neutrality before 2060”.1 Given the currently high emissions level in China and an economic structure with significant share of industrial sector and fossil fuel consumption, it remains a formidable challenge to realize such steep emission reduction for the 30-60 goals, as we call them in this paper.    

    

** Mustard ‘Amara’ Benefits from Superelevated CO2 While Adapting to Far-red Light Over Time   
:PROPERTIES:
:ID: https://openalex.org/W4390628599
:DOI: https://doi.org/10.21273/hortsci17522-23
:AUTHORS: Emily J. Kennebeck, Qingguo Meng
:HOST: Hortscience
:END:

Emily J. Kennebeck, Qingguo Meng, Hortscience. 59(2)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21273/hortsci17522-23")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390628599"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390628599"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390628599"))][Get cited by]]

OpenAlex: https://openalex.org/W4390628599
    
Emily J. Kennebeck, Qingguo Meng, Hortscience. https://doi.org/10.21273/hortsci17522-23
    
Compared with the ambient Earth carbon dioxide concentration (≈415 μmol⋅mol –1 ), the International Space Station has superelevated carbon dioxide (≈2800 μmol⋅mol –1 ), which can be a stressor to certain crops. Far-red light can drive plant photosynthesis and increase extension growth and biomass. However, the effects of far-red light under superelevated carbon dioxide are unclear. We grew hydroponic mustard ( Brassica carinata ) ‘Amara’ seedlings in four growth chambers using a randomized complete block design with two carbon dioxide concentrations (415 and 2800 μmol⋅mol –1 ), two lighting treatments, and two blocks at temperature and relative humidity set points of 22 °C and 40%, respectively. Each growth chamber had two lighting treatments at the same total photon flux density of 200 μmol⋅m –2 ⋅s –1 . Under the same blue and green light at 50 μmol⋅m –2 ⋅s –1 each, plants received either red light at 100 μmol⋅m –2 ⋅s –1 or red + far-red light at 50 μmol⋅m –2 ⋅s –1 each. At day 15 after planting, far-red light did not influence shoot fresh or dry mass at 415 μmol⋅mol –1 carbon dioxide, but decreased both parameters by 22% to 23% at 2800 μmol⋅mol –1 carbon dioxide. Increasing the carbon dioxide concentration increased shoot fresh and dry mass 27% to 49%, regardless of the lighting treatment. Far-red light decreased leaf area by 16% at 2800 μmol⋅mol –1 carbon dioxide, but had no effect at 415 μmol⋅mol –1 carbon dioxide. Increasing the carbon dioxide concentration increased leaf area by 21% to 33%, regardless of far-red light. Regardless of the carbon dioxide concentration, far-red light promoted stem elongation and decreased chlorophyll concentrations by 39% to 42%. These responses indicate far-red light elicited a crop-specific shade avoidance response in mustard ‘Amara’, increasing extension growth but decreasing leaf area, thereby reducing light interception and biomass. In addition, carbon dioxide enrichment up to 2800 μmol⋅mol –1 increased the biomass of mustard ‘Amara’ but decreased the biomass of other crops, indicating crop-specific tolerance to superelevated carbon dioxide. In conclusion, mustard ‘Amara’ seedlings benefit from superelevated carbon dioxide, but exhibit growth reduction under far-red light under superelevated carbon dioxide.    

    

** Solar Water Heating: Comprehensive Review, Critical Analysis and Case Study   
:PROPERTIES:
:ID: https://openalex.org/W4390616016
:DOI: https://doi.org/10.52843/cassyni.z0lx6v
:AUTHORS: Amal Herez
:HOST: No host
:END:

Amal Herez, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.52843/cassyni.z0lx6v")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390616016"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390616016"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390616016"))][Get cited by]]

OpenAlex: https://openalex.org/W4390616016
    
Amal Herez, No host. https://doi.org/10.52843/cassyni.z0lx6v
    
The increasing global demand for renewable energy sources underscores the significance of Solar Water Heating Systems (SWHS), emphasizing the need for thorough research and analysis in this domain. SWHS play a pivotal role in addressing energy efficiency and environmental sustainability, making it imperative to conduct in-depth studies on their utilization. Hence, this paper aims to provide a comprehensive overview of SWHS. It starts by explaining the principles behind these systems, including their components and classification. Moreover, this review consolidates various studies that have been conducted on SWHS to highlight both their advantages and disadvantages. Additionally, a case study is conducted in which it takes into consideration important economic and environmental factors. In particular, it focuses on several scenarios present in Lebanon such as family homes, schools, restaurants hotels and gyms to estimate potential cost savings achieved through implementing SWHS as opposed to relying solely on electric heaters. Furthermore, this investigation also examines the corresponding payback period associated with adopting SWHS along with assessing the significant reduction in carbon dioxide emissions possible if these systems were widely implemented. The findings of the study demonstrate that there is a direct correlation between the extent to which SWHS are utilized and both the payback period and reduction in CO2 emissions. It was observed that when SWHS are used more frequently, with a high percentage of time (Pr=0.9), significant advantages can be achieved. For instance, for different types of establishments such as family homes, schools, restaurants, hotels, and gyms, it was estimated that average payback periods would be 14.2 years, 4.6 years, 9.2 years, 4.4 years, and 5.3 years, respectively. These results indicate that adopting a greater dependency on SWHSs not only leads to quicker cost recovery but also significantly contributes towards reducing carbon dioxide emissions. The analysis reveals that the yearly decrease in carbon dioxide emissions per individual is 0.16 t within a household, 0.016 t per student in an educational institution, 0.04 t per customer within a dining establishment, 0.37 t for each occupied bed in a hotel accommodation, and 0.11 t per individual at a gym. This paper serves as guidelines to SWH community. Additionally, it adds a practical insights into economic and environmental issues relevant to both Lebanon and countries with similar climates.    

    

** Influence of tillage methods on carbon dioxide emissions in spring wheat crops   
:PROPERTIES:
:ID: https://openalex.org/W4390539980
:DOI: https://doi.org/10.1051/bioconf/20248206006
:AUTHORS: Evgeniy Demin, Stanislav Miller, Kirill Likhanov
:HOST: BIO web of conferences
:END:

Evgeniy Demin, Stanislav Miller, Kirill Likhanov, BIO web of conferences. 82(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/bioconf/20248206006")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390539980"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390539980"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390539980"))][Get cited by]]

OpenAlex: https://openalex.org/W4390539980
    
Evgeniy Demin, Stanislav Miller, Kirill Likhanov, BIO web of conferences. https://doi.org/10.1051/bioconf/20248206006
    
The agriculture intensification is associated with an increase in anthropogenic load on arable soils. Tillage leads to disruption of the natural process of soil formation in connection with which the soil biota activity changes and the carbon cycle is disrupted. The purpose of the study is to establish the effects of the tillage method on the carbon dioxide emission in spring wheat crops. The emission of carbon dioxide during the growing season of spring wheat varies significantly depending on the soil processing method and temperature. At the beginning of spring wheat development, the daily emission of carbon dioxide during the dump and subsurface tillage method does not exceed 36.0 and 36.2 CO 2 kg/ha using zero technology provides a reduction in production CO 2 production to 27.8 kg/ha*day. With an increase in soil temperature by July 24, the daily emission increases on a dump and subsurface background to 105.5 and 106.0 CO 2 kg/ha*day, on a zero background to 95.4 CO 2 kg/ha*day. In the future, it decreases. The total carbon losses during the dump and subsurface tillage methods are 2829 and 2793 kg/ha, the use of zero tillage technology reduces carbon losses in grain agrocenosis by 18%.    

    

** Research on the coal saving and emission reduction potential of advanced technologies in China's iron and steel industry   
:PROPERTIES:
:ID: https://openalex.org/W4390629371
:DOI: https://doi.org/10.1016/j.esd.2023.101373
:AUTHORS: Hui Huang, Mengyun Guan, Qing Wang, Jun Zhao, Qiong Yang
:HOST: Energy for Sustainable Development
:END:

Hui Huang, Mengyun Guan, Qing Wang, Jun Zhao, Qiong Yang, Energy for Sustainable Development. 78(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.esd.2023.101373")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390629371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390629371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390629371"))][Get cited by]]

OpenAlex: https://openalex.org/W4390629371
    
Hui Huang, Mengyun Guan, Qing Wang, Jun Zhao, Qiong Yang, Energy for Sustainable Development. https://doi.org/10.1016/j.esd.2023.101373
    
The coal-based energy consumption structure has led to high coal consumption and carbon emissions in China's iron and steel industry, and the task of coal saving and carbon reduction in the steel industry is difficult and urgent. The economic viability of various coal-saving and emission-reduction technologies, the extent of their coal-saving and emission-reduction potential, and the guidance on the adoption of advanced technologies are crucial issues that need to be addressed in the Chinese steel industry. This article employs the Energy-Production (E-P) analysis method and the Conservation Supply Curve (CSC) model incorporating coal consumption ratio coefficients to systematically analyze coal consumption and carbon dioxide emissions in the overall iron and steel industry and its sub-processes under different scenarios. It calculates the coal-saving emission reduction costs of 32 technologies, evaluates them comprehensively based on their coal-saving and emission-reduction potentials and cost-effectiveness, and categorizes them accordingly. According to the cost of coal saving and emission reduction as the demarcation point, a total of 19 technologies are cost-effective; according to the coal-saving emission reduction potential and cost division, 32 technologies are divided into 6 categories, among which 6 technologies such as sintering waste heat recovery technology can be used as key technologies for popularization and application. Seven technologies, such as efficient preheating technology of ladle, have high cost and low potential, which can be gradually eliminated or improved and upgraded. After the comprehensive promotion of the 32 technologies, the maximum coal saving potential is about 3.453 billion GJ, the CO2 emission reduction potential is 395 million tons, the total coal consumption of the steel industry can be reduced to about 13.904 billion GJ, and the carbon dioxide emissions can be reduced to 1.179 billion tons.    

    

** Ecological Impact versus Energy Generation by Floating Photovoltaic Power Plant for a Small Romanian Lake   
:PROPERTIES:
:ID: https://openalex.org/W4390549867
:DOI: https://doi.org/10.1109/ciees58940.2023.10378724
:AUTHORS: Gabriela Elena Dumitran, Liana Ioana Vuţă, Bogdan Popa
:HOST: No host
:END:

Gabriela Elena Dumitran, Liana Ioana Vuţă, Bogdan Popa, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/ciees58940.2023.10378724")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390549867"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390549867"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390549867"))][Get cited by]]

OpenAlex: https://openalex.org/W4390549867
    
Gabriela Elena Dumitran, Liana Ioana Vuţă, Bogdan Popa, No host. https://doi.org/10.1109/ciees58940.2023.10378724
    
The development of floating photovoltaic systems in Romania can help to the share of more than 30.7 % of the total energy produced from renewable energy sources set for the year 2030. Floating photovoltaic plants ensure the achievement of overall energy targets without affecting biodiversity and/or agricultural crops. This study evaluates the insolation and the possibility of installing this technology on Lake Făcău, Romania, to benefit from the generation of electricity but also better water quality and reduction of carbon dioxide emissions $\left(\mathrm{CO}_{2}\right)$. The obtained results are promising as Floating photovoltaic plants covering around 0.22 % of the lake surface, provide 26.76 $M W h /$ year and the estimated reduction of CO <inf xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink">2</inf> emission is 7.52 $\mathbf{t C O}_{2 \mathrm{eq}} /$ year.    

    

** Evaluation of Potential Carbon Dioxide Utilization Pathways in Uzbekistan   
:PROPERTIES:
:ID: https://openalex.org/W4390592971
:DOI: https://doi.org/10.3390/asec2023-15503
:AUTHORS: Azizbek Kamolov, Zafar Turakulov, Adham Norkobilov, Miroslav Variny, Marcos Fallanza
:HOST: No host
:END:

Azizbek Kamolov, Zafar Turakulov, Adham Norkobilov, Miroslav Variny, Marcos Fallanza, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/asec2023-15503")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390592971"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390592971"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390592971"))][Get cited by]]

OpenAlex: https://openalex.org/W4390592971
    
Azizbek Kamolov, Zafar Turakulov, Adham Norkobilov, Miroslav Variny, Marcos Fallanza, No host. https://doi.org/10.3390/asec2023-15503
    
Reaching net-zero emissions by the middle of this century requires the implementation of massive carbon dioxide (CO2) emission reduction strategies along with the reduction of other greenhouse gases on both global and country scales. Thus, carbon capture, storage, and utilization (CCSU) is a promising technology in combination with renewable energy transition. Currently, CO2 utilization has attracted much attention from the scientific community worldwide, since it can improve the economic viability of CCSU deployment by creating a market for the recovered CO2 stream. In this study, a brief assessment and comparison of potential CO2 utilization pathways in Uzbekistan, including CO2-to-chemical/fuel conversion, CO2 bio-fixation/mineralization, and the direct use of CO2, such as for enhanced hydrocarbon recovery (EHR), are conducted considering the CO2 stationary sources and site-specific conditions of the country. In addition, possible challenges and opportunities for large-scale CO2 utilization routes are also discussed. According to this assessment, there is great potential for the direct use of CO2 as a process-boosting agent for EHR in more than 22 major natural gas, crude oil, and coal reservoirs. Moreover, methanol and urea production processes can also create huge market demand for recovered CO2 as long as the conventional CO2 production processes are replaced by sustainable ones.    

    

** Cu-Based Materials for Enhanced C2+ Product Selectivity in Photo-/Electro-Catalytic CO2 Reduction: Challenges and Prospects   
:PROPERTIES:
:ID: https://openalex.org/W4390588938
:DOI: https://doi.org/10.1007/s40820-023-01276-2
:AUTHORS: Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang
:HOST: Nano-Micro Letters
:END:

Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang, Nano-Micro Letters. 16(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40820-023-01276-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390588938"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390588938"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390588938"))][Get cited by]]

OpenAlex: https://openalex.org/W4390588938
    
Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang, Nano-Micro Letters. https://doi.org/10.1007/s40820-023-01276-2
    
Abstract Carbon dioxide conversion into valuable products using photocatalysis and electrocatalysis is an effective approach to mitigate global environmental issues and the energy shortages. Among the materials utilized for catalytic reduction of CO 2 , Cu-based materials are highly advantageous owing to their widespread availability, cost-effectiveness, and environmental sustainability. Furthermore, Cu-based materials demonstrate interesting abilities in the adsorption and activation of carbon dioxide, allowing the formation of C 2+ compounds through C–C coupling process. Herein, the basic principles of photocatalytic CO 2 reduction reactions (PCO 2 RR) and electrocatalytic CO 2 reduction reaction (ECO 2 RR) and the pathways for the generation C 2+ products are introduced. This review categorizes Cu-based materials into different groups including Cu metal, Cu oxides, Cu alloys, and Cu SACs, Cu heterojunctions based on their catalytic applications. The relationship between the Cu surfaces and their efficiency in both PCO 2 RR and ECO 2 RR is emphasized. Through a review of recent studies on PCO 2 RR and ECO 2 RR using Cu-based catalysts, the focus is on understanding the underlying reasons for the enhanced selectivity toward C 2+ products. Finally, the opportunities and challenges associated with Cu-based materials in the CO 2 catalytic reduction applications are presented, along with research directions that can guide for the design of highly active and selective Cu-based materials for CO 2 reduction processes in the future.    

    

** ASTM Method for Inclusion Analysis of Prepared Green Steel   
:PROPERTIES:
:ID: https://openalex.org/W4390606734
:DOI: https://doi.org/10.1109/icmeas58693.2023.10379397
:AUTHORS: Maharishi Arvind, A. A. Adeleke, Ammasi Ayyandurai, Temitayo S. Ogedengbe, M Madan
:HOST: No host
:END:

Maharishi Arvind, A. A. Adeleke, Ammasi Ayyandurai, Temitayo S. Ogedengbe, M Madan, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/icmeas58693.2023.10379397")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390606734"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390606734"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390606734"))][Get cited by]]

OpenAlex: https://openalex.org/W4390606734
    
Maharishi Arvind, A. A. Adeleke, Ammasi Ayyandurai, Temitayo S. Ogedengbe, M Madan, No host. https://doi.org/10.1109/icmeas58693.2023.10379397
    
In the present situation, steel-making industries have turned their attention towards producing quality steel, through more feasible routes. One of the routes is the production of green steel, which is a kind of steel produced through a process which reduces the emission of carbon dioxide. Steel produced through traditional methods relies heavily on fossil fuel and coal, emitting large amounts of CO2, resulting in 6 – 7 % of global greenhouse gas emissions. Eventually, steel production using blast furnaces requires coking coal, which has limited reserves in India. An alternative approach to this is the utilization of DRI which consumes either non-coking coal or Hydrogen for its reduction, which significantly reduces carbon emission. To produce clean steel, it is necessary to undergo a complete assessment of the Non-Metallic Inclusions (NMI). Often, Types, sizes and distribution of Non-Metallic Inclusions play a major role in the steel properties. The present study has been performed to investigate the inclusion rating of steel produced from hydrogen-based DRI (HDRI) during steel making in an Induction Furnace (IF) and carbon-based DRI to understand the cleanness of steel as per ASTM E-45 standard. The kinetics of inclusion formation during steel making in induction furnaces has been studied using Classical Nucleation Theory. Thermodynamic modelling of different types of inclusion formation was carried out using the Fact Sage software package and it has been validated experimentally with the inclusion classifier of the SEM/EDS analyzer.    

    

** Pole to Ground Fault Detection Using Leakage Current for DC Distribution System with IT ground   
:PROPERTIES:
:ID: https://openalex.org/W4390563820
:DOI: https://doi.org/10.5207/jieie.2023.37.6.043
:AUTHORS: Kyung-Min Lee, Chul‐Won Park
:HOST: Journal of The Korean Institute of Illuminating and Electrical Installation Engineers
:END:

Kyung-Min Lee, Chul‐Won Park, Journal of The Korean Institute of Illuminating and Electrical Installation Engineers. 37(6)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5207/jieie.2023.37.6.043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390563820"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390563820"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390563820"))][Get cited by]]

OpenAlex: https://openalex.org/W4390563820
    
Kyung-Min Lee, Chul‐Won Park, Journal of The Korean Institute of Illuminating and Electrical Installation Engineers. https://doi.org/10.5207/jieie.2023.37.6.043
    
Recently, policies such as expansion of distributed power sources, and transition to electric vehicles are being promoted to reduce carbon dioxide. Most distributed power sources generate DC power, so when the direct current system is activated, it is effective in many aspects, including power loss reduction, grid connection efficiency, and economic feasibility. As a DC system protection plan is required according to the grounding system, the fault detection method for Pole to Ground Fault is very important. In this paper, we propose a technique using DWT (Discrete Wavelet Transform) for Pole to Ground Fault detection by leakage current in DC distribution system with IT ground system. First, after modeling the IT grounding DC distribution system using PSCAD s/w, Pole to Ground fault simulation is performed while varying the fault point and fault resistance. After implementing the proposed fault detection using MATLAB s/w, the performance is verified by comparing the proposed technique with the traditional technique through insulation resistance measurement.    

    

** Provision of Reliable Power Supply for the First Category of Consumers Because of Renewable Energy Sources   
:PROPERTIES:
:ID: https://openalex.org/W4390541888
:DOI: https://doi.org/10.1007/978-3-031-51127-1_46
:AUTHORS: Irina Kirpichnikova, Sergey Shipilov
:HOST: Lecture notes in electrical engineering
:END:

Irina Kirpichnikova, Sergey Shipilov, Lecture notes in electrical engineering. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-3-031-51127-1_46")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390541888"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390541888"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390541888"))][Get cited by]]

OpenAlex: https://openalex.org/W4390541888
    
Irina Kirpichnikova, Sergey Shipilov, Lecture notes in electrical engineering. https://doi.org/10.1007/978-3-031-51127-1_46
    
This article describes the objects of the first category of power supply in the example of maternity hospital of the clinic of the Medical University of Chelyabinsk. There is a current power Supply Scheme and a group of electric consumers. The costs are calculated for electricity consumption under various schemes of power supply of the facility. It is also shown how the reduction in electricity consumption is associated with a reduction of carbon dioxide emissions into the atmosphere. It was suggested to use renewable energy sources as a way of power supply of the objects of the first category, such as wind turbines and Solar power plants. The cost of the equipment was calculated based on technical characteristics. It was also calculated the cost of savings on electricity consumptions from centralized sources. The benefits and the possibility of application of the renewable energy sources for objects of the first category are shown.    

    

** Effects of Isopropanol Additive on Exhaust Emissions in Gasoline Engines   
:PROPERTIES:
:ID: https://openalex.org/W4390549811
:DOI: https://doi.org/10.1109/ciees58940.2023.10378725
:AUTHORS: Elitsa Nakova, Simeon Iliev, Kiril Hadjiev
:HOST: No host
:END:

Elitsa Nakova, Simeon Iliev, Kiril Hadjiev, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/ciees58940.2023.10378725")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390549811"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390549811"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390549811"))][Get cited by]]

OpenAlex: https://openalex.org/W4390549811
    
Elitsa Nakova, Simeon Iliev, Kiril Hadjiev, No host. https://doi.org/10.1109/ciees58940.2023.10378725
    
The steady increase in transport needs worldwide, especially in areas with dense populations, makes it necessary to seek methods and means of using sustainable alternatives to conventional fuels to reduce the use of fossil fuels and significantly reduce environmental pollution. This study investigated the effectiveness of Isopropanol as a blend with gasoline to improve the environmental performance of internal combustion engines. Besides, as an alternative fuel isopropyl alcohol can also be considered as a renewable source of energy. Alcohols, as an alternative energy source, are considered with priority, building on their characteristics. Isopropanol, as part of the group of alcohols, has been investigated with regard to its potential to improve the mixing and combustion process and also to influence the laminar flame speed as well as the combustion rate compared to conventional gasoline in internal combustion engines. The study focused on its impact on emissions, specifically hydrocarbons, carbon monoxide, carbon dioxide and nitrogen oxides. The study was carried out in a laboratory environment, on a 4-cylinder gasoline engine, for the purpose of the study gasoline and gasoline-Isopropanol mixtures were used in the ratio as follows: 95% gasoline and 5% Isopropanol (IP5), 90% gasoline and 10% Isopropanol (IP10), 85% gasoline and 15% Isopropanol (IP15) and 80% gasoline and 20% Isopropanol (IP20). Due to the properties of Isopropanol there is a reduction of HC, CO, CO2 and NOx emissions, the most favorable for this engine is the fuel mixture with Isopropanol content between 10%-15%.    

    

** A Synergistic Dual-Functional Silver-Manganese Dioxide-CNTs Ternary Composite Electrocatalyst for Solid-State Zinc-Air Battery   
:PROPERTIES:
:ID: https://openalex.org/W4390561537
:DOI: https://doi.org/10.20944/preprints202401.0200.v1
:AUTHORS: Guoqing Zhang, Tuan‐Wu Cao, Peng Zhang, Shuying Kong, Binbin Jin
:HOST: No host
:END:

Guoqing Zhang, Tuan‐Wu Cao, Peng Zhang, Shuying Kong, Binbin Jin, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.20944/preprints202401.0200.v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390561537"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390561537"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390561537"))][Get cited by]]

OpenAlex: https://openalex.org/W4390561537
    
Guoqing Zhang, Tuan‐Wu Cao, Peng Zhang, Shuying Kong, Binbin Jin, No host. https://doi.org/10.20944/preprints202401.0200.v1
    
Exploring effective oxygen reduction reaction (ORR) electrocatalysts is crucial for progress in solid-state alkaline zinc-air batteries (ZAB). In this paper, silver-manganese dioxide-carbon nanotubes (SMC) ternary composites, which function as Electrocatalyst for air Electrodes, was produced via the pyrolysis of silver permanganate under microwave irradiation in one step. A scanning electron microscope (SEM), X-ray diffraction (XRD), and an energy dispersion spectrometer (EDS) have consistently determined that SMC consists of silver and alpha-manganese dioxide, which anchored on the surface of CNTs. Through polarization and chronoamperometery curves, the electrocatalytic activity of SMC for ORR was examined. The results reveal that SMC has higher catalytic activity than the chemically produced electrocatalyst for ORR in alkaline condition. Finally, a solid-state zinc-air cell with an electrocatalyst was constructed and tested. Constant current discharge curve of the zinc-air cell with SMC has a long discharge voltage plateau and a 60.03 mAh capacity at 30 mA &amp;middot; cm&amp;minus;2 . The mechanism of improvement in electrocatalytic activity was also discussed. In a summary, the strategy described in this study and the electrocatalyst produced can be regarded as an effective method for making a robust oxygen reduction catalyst toward solid-state zinc-air batteries.    

    

** Does digital transformation affect carbon performance through talent? The moderating role of employee structure   
:PROPERTIES:
:ID: https://openalex.org/W4390543690
:DOI: https://doi.org/10.1016/j.jclepro.2024.140581
:AUTHORS: Qiuling Chen, Zhiqi Gong, Jingfei Wu, Tianchi Wang
:HOST: Journal of Cleaner Production
:END:

Qiuling Chen, Zhiqi Gong, Jingfei Wu, Tianchi Wang, Journal of Cleaner Production. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jclepro.2024.140581")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390543690"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390543690"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390543690"))][Get cited by]]

OpenAlex: https://openalex.org/W4390543690
    
Qiuling Chen, Zhiqi Gong, Jingfei Wu, Tianchi Wang, Journal of Cleaner Production. https://doi.org/10.1016/j.jclepro.2024.140581
    
Industrial process consumes large amounts of energy and emits substantial carbon dioxide. The implementation of digital transformation is crucial for industrial enterprises to move towards low-carbon transformation. Existing studies on mediating effect between digitization and carbon emissions reduction have not adequately explored the role of talent. By selecting Chinese industrial listed enterprises during 2012–2021 as research samples, we apply the mediation model to investigate the influence of digital transformation on carbon performance and to explore the mediating effect of talent. Moreover, the moderated mediation model is used to detect the moderating effects of excess employee and employee density, named employee structure. We find that digital transformation has a positive impact on carbon performance. Talent performs as a mediating function in the link between digital transformation and carbon performance. The mediating effect of talent can be positively moderated by excess employee and employee density, respectively. This positive mediating effect increases with the decrease of excess employee or the increase of employee density. Our research findings suggest that government should encourage entire industrial sector to implement digital transformation, and enterprises should take full advantage of digital transformation for the low-carbon development.    

    

** The role of financial and trade globalization in enhancing environmental sustainability: Evaluating the effectiveness of carbon taxation and renewable energy in EU member countries   
:PROPERTIES:
:ID: https://openalex.org/W4390587099
:DOI: https://doi.org/10.1016/j.bir.2024.01.004
:AUTHORS: Ayhan Nadiri, Veclal GÜNDÜZ, Tomiwa Sunday Adebayo
:HOST: Borsa Istanbul Review
:END:

Ayhan Nadiri, Veclal GÜNDÜZ, Tomiwa Sunday Adebayo, Borsa Istanbul Review. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.bir.2024.01.004")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390587099"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390587099"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390587099"))][Get cited by]]

OpenAlex: https://openalex.org/W4390587099
    
Ayhan Nadiri, Veclal GÜNDÜZ, Tomiwa Sunday Adebayo, Borsa Istanbul Review. https://doi.org/10.1016/j.bir.2024.01.004
    
The study addresses the pressing issue of environmental degradation, pinpointing carbon dioxide (CO2) emissions as its primary driver, posing a threat to global environmental sustainability, including the member countries of the European Union (EU). Global warming problems persist, but previous studies have not adequately explored the factors that contribute to a reduction in carbon emissions in EU countries. The paper fills the gap by assessing the efficacy of carbon tax and eco-innovation in mitigating CO2 levels from 1994 to 2019, considering the influence of renewable energy and various aspects of globalization. The study establishes long-term associations among the indicators examined using advanced methodologies, including the cross-sectional autoregressive distributed lag approach and the Westerlund cointegration method. Notably, the results highlight that carbon taxes, eco-innovation, renewable energy, and globalization contribute to slowing environmental deterioration, and economic progress plays a role in mitigating environmental sustainability challenges in EU member states. These findings reinforce the importance of robust strategies for reducing CO2 emissions and minimizing adverse environmental impacts.    

    

** Hydrothermal synthesis of MnO2 nanorods for efficient electrochemical detection of environmental anthropogenic pollutants and nitrobenzene   
:PROPERTIES:
:ID: https://openalex.org/W4390611242
:DOI: https://doi.org/10.1016/j.inoche.2023.112015
:AUTHORS: Vasanthi Chellappa, N. Meenakshisundaram, Jamespandi Annaraj, Suresh Sagadevan
:HOST: Inorganic Chemistry Communications
:END:

Vasanthi Chellappa, N. Meenakshisundaram, Jamespandi Annaraj, Suresh Sagadevan, Inorganic Chemistry Communications. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.inoche.2023.112015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390611242"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390611242"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390611242"))][Get cited by]]

OpenAlex: https://openalex.org/W4390611242
    
Vasanthi Chellappa, N. Meenakshisundaram, Jamespandi Annaraj, Suresh Sagadevan, Inorganic Chemistry Communications. https://doi.org/10.1016/j.inoche.2023.112015
    
Glassy carbon (GC) electrodes have been modified/fabricated with nanoscale manganese dioxide (MnO2) rods for efficient detection of the toxic anthropogenic pollutant and nitrobenzene (NB) in real water. The MnO2 nanorods were prepared by a hydrothermal process, and their morphology was confirmed by various characterization techniques. They were used to modify a glassy carbon (MnO2/GCE) electrode surface, which was optimized and developed as an electrochemical detector under different experimental conditions to obtain good sensitivity and selectivity. It has shown excellent electrocatalytic activity for the reduction of NB to phenylhydroxylamine as a product. The calibration plots were constructed using the observed data of the differential pulse voltametric technique between the linear range of 0.03 µM–2 µM with a detection limit of 0.025 μM which displayed great stability and reproducibility as well as the detection of NB in the real water sample.    

    

** Decarbonisation of the steel industry: theoretical and practical approaches with analysis of the situation in the steel sector in Poland   
:PROPERTIES:
:ID: https://openalex.org/W4390678737
:DOI: https://doi.org/10.46544/ams.v28i3.08
:AUTHORS: 
:HOST: Acta Montanistica Slovaca
:END:

, Acta Montanistica Slovaca. 28(v28/i3)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.46544/ams.v28i3.08")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390678737"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390678737"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390678737"))][Get cited by]]

OpenAlex: https://openalex.org/W4390678737
    
, Acta Montanistica Slovaca. https://doi.org/10.46544/ams.v28i3.08
    
Climate change and environmental degradation are nowadays the key challenges of the industries in Europe (according to the European Green Deal). The primary goal is to achieve a climate-neutral in Europe by 2050. Technologies with carbon dioxide (CO2) emissions should be completely stopped in the future. The iron and steel industry is among the manufacturing industries with high CO2 emissions in Europe. In Poland, steel mills produce about 9 million tonnes of steel per year (average for 2000-2021). Steel mills in Poland use two steel production technologies, EAF and BOF. The first technology is highly energy intensive, and the second has high emissions of CO2. There will be no BF technology in zero-emission smelters; this technology will be replaced by DRI (i.e., direct iron reduction) installations, and electric furnaces will be powered by renewable energy. The paper consists of two parts: a theoretical section and a practical section. In the first section, the way the steel industry moves towards climate neutrality was presented. The part of the paper was realized based on European documents and a literature review. The second part was an analysis of the CO2 emission in the steel industry in Poland. The analysis was realized based on data from the Polish Steel Association.    

    

** Reassessing the need for carbon dioxide removal: moral implications of alternative climate target pathways   
:PROPERTIES:
:ID: https://openalex.org/W4390608678
:DOI: https://doi.org/10.1017/sus.2023.21
:AUTHORS: Lieske Voget-Kleschin, Christian Baatz, Clare Heyward, Detlef van Vuuren, Nadine Mengis
:HOST: Global Sustainability
:END:

Lieske Voget-Kleschin, Christian Baatz, Clare Heyward, Detlef van Vuuren, Nadine Mengis, Global Sustainability. 7(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1017/sus.2023.21")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390608678"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390608678"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390608678"))][Get cited by]]

OpenAlex: https://openalex.org/W4390608678
    
Lieske Voget-Kleschin, Christian Baatz, Clare Heyward, Detlef van Vuuren, Nadine Mengis, Global Sustainability. https://doi.org/10.1017/sus.2023.21
    
Abstract Non-technical summary Scenarios compatible with the Paris agreement's temperature goal of 1.5 °C involve carbon dioxide removal measures – measures that actively remove CO 2 from the atmosphere – on a massive scale. Such large-scale implementations raise significant ethical problems. Van Vuuren et al. (2018), as well as the current IPCC scenarios, show that reduction in energy and or food demand could reduce the need for such activities. There is some reluctance to discuss such societal changes. However, we argue that policy measures enabling societal changes are not necessarily ethically problematic. Therefore, they should be discussed alongside techno-optimistic approaches in any kind of discussions about how to respond to climate change. Technical summary The 1.5 °C goal has given impetus to carbon dioxide removal (CDR) measures, such as bioenergy combined with carbon capture and storage, or afforestation. However, land-based CDR options compete with food production and biodiversity protection. Van Vuuren et al. (2018) looked at alternative pathways including lifestyle changes, low-population projections, or non-CO 2 greenhouse gas mitigation, to reach the 1.5 °C temperature objective. Underlined by the recently published IPCC AR6 WGIII report, they show that demand-side management measures are likely to reduce the need for CDR. Yet, policy measures entailed in these scenarios could be associated with ethical problems themselves. In this paper, we therefore investigate ethical implications of four alternative pathways as proposed by Van Vuuren et al. (2018). We find that emission reduction options such as lifestyle changes and reducing population, which are typically perceived as ethically problematic, might be less so on further inspection. In contrast, options associated with less societal transformation and more techno-optimistic approaches turn out to be in need of further scrutiny. The vast majority of emission reduction options considered are not intrinsically ethically problematic; rather everything rests on the precise implementation. Explicitly addressing ethical considerations when developing, advancing, and using integrated assessment scenarios could reignite debates about previously overlooked topics and thereby support necessary societal discourse. Social media summary Policy measures enabling societal changes are not necessarily as ethically problematic as commonly presumed and reduce the need for large-scale CDR.    

    

** Multi-objective genetic algorithm optimization of energy efficiency and biomass concentration of Synechococcus HS-9 cultivation for third-generation biodiesel feedstock   
:PROPERTIES:
:ID: https://openalex.org/W4390637025
:DOI: https://doi.org/10.1016/j.cscee.2024.100614
:AUTHORS: Arif Rahman, Kania Dyah Nastiti, Nining Betawati Prihantini, M.A.M. Oktaufik, Surat Indrijarso, Alfred Kampira Levison, Ridho Irwansyah, Nasruddin Nasruddin
:HOST: Case Studies in Chemical and Environmental Engineering
:END:

Arif Rahman, Kania Dyah Nastiti, Nining Betawati Prihantini, M.A.M. Oktaufik, Surat Indrijarso, Alfred Kampira Levison, Ridho Irwansyah, Nasruddin Nasruddin, Case Studies in Chemical and Environmental Engineering. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cscee.2024.100614")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390637025"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390637025"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390637025"))][Get cited by]]

OpenAlex: https://openalex.org/W4390637025
    
Arif Rahman, Kania Dyah Nastiti, Nining Betawati Prihantini, M.A.M. Oktaufik, Surat Indrijarso, Alfred Kampira Levison, Ridho Irwansyah, Nasruddin Nasruddin, Case Studies in Chemical and Environmental Engineering. https://doi.org/10.1016/j.cscee.2024.100614
    
Microalgae is a sustainable biological resource since it can be used in biodiesel production, pharmaceutical development, nutritional supplements, carbon dioxide sequestration, and wastewater remediation. Due to its high lipid content and low carbon dioxide emissions, microalgae-derived biodiesel can replace fossil fuels. Microalgae biomass production involves cultivation, harvesting, and drying. To develop microalgae and produce high-quality biomass, culture procedures must be optimized. Microalgae cultivation is affected by a range of physical and chemical parameters, including light intensity (I), temperature (T), carbon dioxide (CO2), pH, dissolved oxygen (DO), and oxidation reduction potential (ORP). The objective of this study is to examine the impact of physico-chemical factors on the cultivation process of Synechococcus HS-9 in order to generate dry biomass. ANN and multi-objective genetic algorithms will also be used to optimize cultivation. The five main procedures of this study are: 1) preparation of the cultivation medium; 2) Synechococcus HS-9 inoculum and utilization of a photobioreactor; 3) inoculation; 4) cultivation and physical-chemical parameter data collection; and 5) prediction and optimization. The physico-chemical properties of Synechococcus HS-9 were measured during cultivation. The average values of these parameters were found to be 439 to 325 7 μmol m−2s−1 for light conditions and 190–200 μmol m−2s−1 for dark conditions. During cultivation, T ranged from 29 to 32 °C and CO2 from 82 to 84 ppm. Most pH levels are between 8 and 7.5. The dissolved oxygen (DO) concentration drops from 15 to 3 mg/l. The ORP also fluctuates, dropping from 170 mV to 155 mV and then rising to 180 mV. Based on multi-objective optimization, the optimal values for energy efficiency (ղ) and biomass concentration (C) are 0.043 % and 4.61 × 10−5 mg/ml, respectively. The optimal condition is achieved when the light intensity (I): 254.7 μmol m−2s−1, temperature (T): 29.7 °C, CO2 concentration: 83.4 ppm, pH: 8.6, dissolved oxygen (DO): 6.0 mg/l, and ORP: 149.1 mV.    

    

** Electrocatalytic and Photocatalytic CO2 Methanation: From Reaction Fundamentals to Catalyst Developments   
:PROPERTIES:
:ID: https://openalex.org/W4390614494
:DOI: https://doi.org/10.1002/cctc.202301406
:AUTHORS: Junfeng Tian, Wenqing Xu, Jiajian Gao, Tong Zhu, Guangwen Xu, Ziyi Zhong, Fabing Su
:HOST: ChemCatChem
:END:

Junfeng Tian, Wenqing Xu, Jiajian Gao, Tong Zhu, Guangwen Xu, Ziyi Zhong, Fabing Su, ChemCatChem. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301406")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390614494"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390614494"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390614494"))][Get cited by]]

OpenAlex: https://openalex.org/W4390614494
    
Junfeng Tian, Wenqing Xu, Jiajian Gao, Tong Zhu, Guangwen Xu, Ziyi Zhong, Fabing Su, ChemCatChem. https://doi.org/10.1002/cctc.202301406
    
Transitioning from fossil fuels to renewable energy sources is demanded due to the gradual depletion of petroleum oil/gas and the environmental impact of carbon dioxide (CO2) emissions into the atmosphere. Electrocatalytic and photocatalytic CO2 reduction to methane (CH4) using renewable energy sources is crucial for sustainable chemical/fuel production and greenhouse gas reduction. In recent years, extensive research has focused on understanding the fundamental aspects of the two approaches, such as reaction mechanisms and active sites, and exploring/designing novel catalytic materials. This review initially discusses the reaction fundamentals, including performance evaluation indexes, reactors, and mechanisms, to understand the catalytic reactions. Subsequently, various catalyst preparation strategies and characterization methods are summarized, trying to outline the catalyst design principle based on the obtained understanding of the reaction mechanisms. Finally, research challenges and perspectives for future development in this area are discussed and presented. It is expected to provide a comprehensive understanding of the photo/electrocatalytic CO2 methanation, valuable knowledge to novice researchers, and a helpful reference for future research endeavors.    

    
