#+filetags: CO2RR
#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Fri Feb  9 00:42:50 2024

Found 27 results from 2024-02-02 to 2024-02-09
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Effective reduction on flame soot via plasma coupled with carbon dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391451084
:TOPICS: Chemical Kinetics of Combustion Processes, Catalytic Nanomaterials, Applications of Plasma in Medicine and Biology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jhazmat.2024.133669")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391451084"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391451084"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391451084"))][Get cited by]]

OpenAlex: https://openalex.org/W4391451084 (Open access: False)
    
[[https://openalex.org/A5035298690][Dandan Qi]], [[https://openalex.org/A5043356374][Mingxiao Chen]], [[https://openalex.org/A5016557228][Kaixuan Yang]], [[https://openalex.org/A5017350291][Tianjiao Li]], [[https://openalex.org/A5004130467][Yaoyao Ying]], [[https://openalex.org/A5071659496][Dong Liu]], Journal of Hazardous Materials. None(None)] 2024. https://doi.org/10.1016/j.jhazmat.2024.133669 
     
This study explored the impact of non-thermal plasma and CO2 on the flame soot characteristics within the diffusion flames. We analyzed on flame structures that were diluted with either CO2 or N2, temperature distributions, and soot characteristics, both in the presence and absence of plasma. Due to the higher specific heat capacity of CO2 compared to N2, the optical observations consistently showed lower temperatures in flames diluted with CO2 as compared to those diluted with N2. The inclusion of plasma and carbon dioxide resulted in the lowest soot concentration, indicating that plasma coupled with CO2 has a synergistic inhibitory effect on soot emissions. The findings revealed that when CO2 was used to dilute the flames and the oxygen concentration was low, the soot nanostructure appeared amorphous. Raman results showed that the level of graphitization observed in soot particles from CO2 dilution flames was lower than that from N2 dilution flames. In the presence of plasma and CO2, the soot obtained exhibited the shortest fringe length and the highest fringe tortuosity. Significant correlations were observed between the nanostructure of soot and its reactivity. The combined application of plasma and CO2 proved to be effective in reducing the soot carbonization degree. Soot particles produced during incomplete combustion not only reduce the performance of the combustion system but also cause significant environmental pollution and health problems. Oxygen-fuel combustion integrated with O2/CO2 as an oxidant instead of O2/N2 has drawn extensive attention due to its unique advantages in reducing soot and NOx generation and combining with CO2 recycling technologies. This topic provides a detailed and profound understanding of the mechanisms behind soot suppression through the combined effects of CO2 addition and plasma activation.    

    

* Understanding the Interplay of the Brønsted Acidity of Catalyst Ancillary Groups and the Solution Components in Iron-porphyrin-Mediated Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391464343
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.3c10127")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391464343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391464343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391464343"))][Get cited by]]

OpenAlex: https://openalex.org/W4391464343 (Open access: False)
    
[[https://openalex.org/A5032471432][Ana Sonea]], [[https://openalex.org/A5093845864][Nicholas R. Crudo]], [[https://openalex.org/A5000268359][Jeffrey J. Warren]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.3c10127 
     
The rapid and efficient conversion of carbon dioxide (CO2) to carbon monoxide (CO) is an ongoing challenge. Catalysts based on iron-porphyrin cores have emerged as excellent electrochemical mediators of the two proton + two electron reduction of CO2 to CO, and many of the design features that promote function are known. Of those design features, the incorporation of Brønsted acids in the second coordination sphere of the iron ion has a significant impact on catalyst turnover kinetics. The Brønsted acids are often in the form of hydroxyphenyl groups. Herein, we explore how the acidity of an ancillary 2-hydroxyphenyl group affects the performance of CO2 reduction electrocatalysts. A series of meso-5,10,15,20-tetraaryl porphyrins were prepared where only the functional group at the 5-meso position has an ionizable proton. A series of cyclic voltammetry (CV) experiments reveal that the complex with −OMe positioned para to the ionizable −OH shows the largest CO2 reduction rate constants in acetonitrile solvent. This is the least acidic −OH of the compounds surveyed. The turnover frequency of the −OMe derivative can be further improved with the addition of 4-trifluoromethylphenol to the solution. In contrast, the iron-porphyrin complex with −CF3 positioned opposite the ionizable −OH shows the smallest CO2 reduction rate constants, and its turnover frequency is less enhanced with the addition of phenols to the reaction solutions. The origin of this effect is rationalized based on kinetic isotope effect experiments and density functional calculations. We conclude that catalysts with weaker internal acids coupled with stronger external acid additives provide superior CO2 reduction kinetics.    

    

* Single-atom catalysts for electrocatalytic carbon dioxide reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391488466
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/b978-0-323-95237-8.00003-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391488466"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391488466"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391488466"))][Get cited by]]

OpenAlex: https://openalex.org/W4391488466 (Open access: False)
    
[[https://openalex.org/A5022870015][Subhash Chandra Shit]], [[https://openalex.org/A5036665795][Indranil Mondal]], Elsevier eBooks. None(None)] 2024. https://doi.org/10.1016/b978-0-323-95237-8.00003-3 
     
The electrochemical CO2 reduction reaction carries tremendous significance to tackle the exponential rising of CO2 level in the atmosphere. The development of different classes of electrocatalyst materials emerged with more understanding of the catalyst features, reaction mechanism, catalytic efficiency, and product selectivity using modern analytical tools (such as in situ techniques). Single-atom catalysts (SACs) are a new class of material that allows atom-by-atom utilization in the catalytic process, thereby influencing the CO2 reduction efficiency and product selectivity in more precise manner. In this chapter, we highlight the fundamental of CO2 electroreduction, including general mechanism for varied product formation, electrolyzer component, operational parameter, and development of SACs electrode material for CO2 reduction.    

    

* Modulation of active center distance of hybrid perovskite for boosting photocatalytic reduction of carbon dioxide to ethylene  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391527790
:TOPICS: Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1073/pnas.2318970121")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391527790"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391527790"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391527790"))][Get cited by]]

OpenAlex: https://openalex.org/W4391527790 (Open access: False)
    
[[https://openalex.org/A5060340851][Linjuan Li]], [[https://openalex.org/A5018013187][Dong Xu]], [[https://openalex.org/A5042815155][Xiankui Xu]], [[https://openalex.org/A5085521958][Zheng Tian]], [[https://openalex.org/A5069616452][Xue Zhou]], [[https://openalex.org/A5077769841][Shenbo Yang]], [[https://openalex.org/A5011328145][Zhonghai Zhang]], Proceedings of the National Academy of Sciences of the United States of America. 121(7)] 2024. https://doi.org/10.1073/pnas.2318970121 
     
Solar-driven photocatalytic CO 2 reduction is an energy-efficient and sustainable strategy to mitigate CO 2 levels in the atmosphere. However, efficient and selective conversion of CO 2 into multi-carbon products, like C 2 H 4 , remains a great challenge due to slow multi-electron-proton transfer and sluggish C–C coupling. Herein, a two-dimensional thin-layered hybrid perovskite is fabricated through filling of oxygen into iodine vacancy in pristine DMASnI 3 (DMA = dimethylammonium). The rational-designed DMASnI 3 (O) induces shrinkage of active sites distance and facilitates dimerization of C–C coupling of intermediates. Upon simulated solar irradiation, the DMASnI 3 (O) photocatalyst achieves a high selectivity of 74.5%, corresponding to an impressive electron selectivity of 94.6%, for CO 2 to C 2 H 4 conversion and an effective C 2 H 4 yield of 11.2 μmol g −1 h −1 . In addition, the DMASnI 3 (O) inherits excellent water stability and implements long-term photocatalytic CO 2 reduction to C 2 H 4 in a water medium. This work establishes a unique paradigm to convert CO 2 to C 2+ hydrocarbons in a perovskite-based photocatalytic system.    

    

* Electrochemical reduction of carbon dioxide to produce formic acid coupled with oxidative conversion of biomass  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391560295
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.01.062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391560295"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391560295"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391560295"))][Get cited by]]

OpenAlex: https://openalex.org/W4391560295 (Open access: False)
    
[[https://openalex.org/A5075320040][Jiashuai Liu]], [[https://openalex.org/A5025761344][Yifan Wang]], [[https://openalex.org/A5040497392][Zhiwei Dai]], [[https://openalex.org/A5014377577][Daihong Gao]], [[https://openalex.org/A5013713303][Xuebing Zhao]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.01.062 
     
Electrochemical reduction of CO2 (CO2RR) has become a research hot spot in recent years in the context of carbon neutrality. HCOOH is one of the most promising products obtained by electrochemical reduction of CO2 due to its high energy value as estimated by market price per energy unit and wide application in chemical industry. Biomass is the most abundant renewable resource in the natural world. Coupling biomass oxidative conversion with CO2RR driven by renewable electricity would well achieve carbon negativity. In this work, we comprehensively reviewed the current research progress on CO2RR to produce HCOOH and coupled system for conversion of biomass and its derivatives to produce value-added products. Sn- and Bi-based electrocatalysts are discussed for CO2RR with regards to the structure of the catalyst and reaction mechanisms. Electro-oxidation reactions of biomass derived sugars, alcohols, furan aldehydes and even polymeric components of lignocellulose were reviewed as alternatives to replace oxygen evolution reaction (OER) in the conventional electrolysis process. It was recommended that to further improve the efficiency of the coupled system, future work should be focused on the development of more efficient and stable catalysts, careful design of the electrolytic cells for improving the mass transfer and development of environment-friendly processes for recovering the formed formate and biomass oxidation products.    

    

* Efficient visible‐light‐driven carbon dioxide reduction by a bioinspired Nickel molecular catalyst  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391597293
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Role of Porphyrins and Phthalocyanines in Materials Chemistry
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202301892")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391597293"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391597293"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391597293"))][Get cited by]]

OpenAlex: https://openalex.org/W4391597293 (Open access: False)
    
[[https://openalex.org/A5012051639][Jing Zhang]], [[https://openalex.org/A5066076190][Ping She]], [[https://openalex.org/A5080328342][Qi Xu]], [[https://openalex.org/A5010693249][Fengkun Tian]], [[https://openalex.org/A5009799106][Heng Rao]], [[https://openalex.org/A5088751445][Jun‐Sheng Qin]], [[https://openalex.org/A5020281878][Julien Bonin]], [[https://openalex.org/A5078358071][Marc Robert]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202301892 
     
Inspired by natural enzymes, this study presents a nickel‐based molecular catalyst, [Ni‖(N2S2)]Cl2 (N2S2 = 2,11‐dithia[3,3](2,6)pyridinophane), for the photochemical catalytic reduction of CO2 under visible light. The catalyst was synthesized and characterized using various techniques, including liquid chromatography‐high resolution mass spectrometry (LC‐HRMS), UV‐Visible spectroscopy, and X‐ray crystallography. The crystallographic analysis revealed a slightly distorted octahedral coordination geometry with a mononuclear Ni2+ cation, two nitrogen atoms and two sulfur atoms. Photocatalytic CO2 reduction experiments were performed in homogeneous conditions using the catalyst in combination with [Ru(bpy)3]Cl2 (bpy = 2,2’‐bipyridine) as a photosensitizer and 1,3‐dimethyl‐2‐phenyl‐2,3‐dihydro‐1H‐benzo[d]imidazole (BIH) as a sacrificial electron donor. The catalyst achieved a high selectivity of 89% towards CO and a remarkable turnover number (TON) of 7991 during 8 h of visible light irradiation under CO2 in the presence of phenol as a co‐substrate. The turnover frequency (TOF) in the initial 6 h was 1079 h‐1, with an apparent quantum yield (AQY) of 1.08%. Controlled experiments confirmed the dependency on the catalyst, light, and sacrificial electron donor for the CO2 reduction process. These findings demonstrate this bioinspired nickel molecular catalyst could be effective for fast and efficient photochemical catalytic reduction of CO2 to CO.    

    

* Covalent Organic Frameworks as Promising Platforms for Efficient Electrochemical Reduction of Carbon Dioxide: A Review  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391611409
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/sstr.202300495")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391611409"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391611409"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391611409"))][Get cited by]]

OpenAlex: https://openalex.org/W4391611409 (Open access: True)
    
[[https://openalex.org/A5071836973][Zihao Chen]], [[https://openalex.org/A5015105154][Nan Li]], [[https://openalex.org/A5027994683][Qichun Zhang]], Small structures. None(None)] 2024. https://doi.org/10.1002/sstr.202300495  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/sstr.202300495][pdf]])
     
In current research, achieving carbon neutrality has become a primary focus through the utilization of various conversion technologies that transform carbon dioxide (CO 2 ) into valuable chemicals or fuels. Covalent organic frameworks (COFs), as emerging crystalline organic polymers, offer distinct advantages in CO 2 conversion compared to other materials. These advantages include controllable nanoscale pores, predefined functional units, editable framework structures, and rich conjugated systems. The unique characteristics of COFs make them highly promising electrocatalysts for CO 2 conversion. This review provides a comprehensive overview of pioneering works and recent research on the utilization of COF‐based materials as electrocatalysts for electrochemical CO 2 reduction reaction. This review offers a comprehensive analysis of the design principles for various reactive sites, skeleton structures, pore functionalities, 3D frameworks, morphologies, and composite materials of COFs, aiming to enhance electrocatalysis. Finally, this review presents some recommendations for material design, reaction mechanisms, and theoretical computations to enhance the understanding of reaction mechanisms further and facilitate the design of high‐performance COF‐based electrocatalysts.    

    

* Synergistic Effect of Phthalocyanine and Pyrochlore-type Oxide Catalysts to Enhance Activity of Electrochemical Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391614705
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/chemle/upae029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391614705"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391614705"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391614705"))][Get cited by]]

OpenAlex: https://openalex.org/W4391614705 (Open access: True)
    
[[https://openalex.org/A5012735404][Riichiroh Maruyama]], [[https://openalex.org/A5001488454][Satoko Takase]], [[https://openalex.org/A5019250083][Youichi Shimizu]], Chemistry Letters. None(None)] 2024. https://doi.org/10.1093/chemle/upae029  ([[https://academic.oup.com/chemlett/advance-article-pdf/doi/10.1093/chemle/upae029/56609787/upae029.pdf][pdf]])
     
Abstract Electrochemical CO2 reduction has been attracting attention due to its impact on the environment. In this study, we found the combination of Co-phthalocyanine and pyrochlore-type Bi2Sn2O7 catalyst gave high catalytic activity for CO2 reduction, and devised a new electrocatalyst that combines them for their synergistic effects.    

    

* Fe0-dependent carbon dioxide reduction to methane via diverse electron transfer pathway in methanogenic community  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391615959
:TOPICS: Microbial Fuel Cells and Electrogenic Bacteria Technology, Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.crsus.2024.100019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391615959"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391615959"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391615959"))][Get cited by]]

OpenAlex: https://openalex.org/W4391615959 (Open access: True)
    
[[https://openalex.org/A5033296587][Tianyu Gao]], [[https://openalex.org/A5016543543][Lichao Xia]], [[https://openalex.org/A5015762746][Hanmin Zhang]], [[https://openalex.org/A5075257427][Ahmed Tawfik]], [[https://openalex.org/A5088311812][Fangang Meng]], Cell Reports Sustainability. None(None)] 2024. https://doi.org/10.1016/j.crsus.2024.100019 
     
In natural and engineered environments, iron biocorrosion is an energy reservoir for growth of methanogens. However, how archaea accept electrons from metallic iron remains enigmatic. Here, we report that a Methanothrix-dominated methanogenic community from anaerobic granular sludge can reduce carbon dioxide (CO2) to methane (CH4) via electron uptake from zero-valent iron (ZVI). Through the batch experiments, a maximum CH4 yield of 40.8 ± 0.6 μeequiv/day and an electron recovery from ZVI oxidation to CH4 generation of 69.7% ± 6.1% are observed. Metagenome analysis and inhibition experiments indicate that electrons released by corrosive bacteria are utilized by Methanothrix for accomplishing CO2-to-CH4 conversion via potential intracellular and extracellular electron transfer. The results of activity tests of four electron donors (i.e., ZVI, stainless steel, H2, and acetate) suggest that the ZVI-dependent methanogenesis dominate the overall CH4 generation compared with hydrogenotrophic and acetoclastic methanogenesis, which provides a new insight into autotrophic metabolism of methanogens.    

    

* Selective Ethanol Synthesis from Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391606664
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Carbon Dioxide Capture and Storage Technologies, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 1997-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1595/003214097x414166170")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391606664"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391606664"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391606664"))][Get cited by]]

OpenAlex: https://openalex.org/W4391606664 (Open access: False)
    
[[https://openalex.org/A5076484143][Yasuo Izumi]], Platinum Metals Review. 41(4)] 1997. https://doi.org/10.1595/003214097x414166170 
     
Work on the synthesis of ethanol from carbon dioxide over a rhodium-selenium catalyst is reported, and related reactions and characterisation studies are briefly reviewed. In order to inhibit the formation of methane (complete reduction of carbon dioxide) and simultaneously activate carbon-carbon bond formation by the reaction of CH x with carbonyl derivatives, it is necessary to control the active rhodium sites. Based on a study of single crystal rhodium surfaces it is proposed that acetyl and acetate intermediates are formed. Recently it has been discovered that supported Rh/TiO 2 , promoted by selenium from inside the rhodium metal sites, is a potential catalyst for ethanol synthesis from carbon dioxide. The action of this catalyst is compared to related studies.    

    

* Reduction of Carbon Dioxide with Platinum Metals Electrocatalysts  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391626263
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 1989-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1595/003214089x33129")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391626263"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391626263"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391626263"))][Get cited by]]

OpenAlex: https://openalex.org/W4391626263 (Open access: False)
    
[[https://openalex.org/A5002697085][B. Patrick Sullivan]], Platinum Metals Review. 33(1)] 1989. https://doi.org/10.1595/003214089x33129 
     
The reduction of carbon dioxide to fuels and chemicals can be accomplished by the use of electrocatalysts of the platinum group metals. Worthwhile products include carbon monoxide, formate, methanol, methane, oxalate and even higher hydrocarbons depending on the catalyst type and environment. Three classes of electrocatalysts have been identified: catalytic metal surfaces, monomeric solution complexes, and chemically modified electrodes; the latter being a novel hybrid of solid state, surface and homogeneous solution chemistry.    

    

* Applications of X-ray Spectroscopy in Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391537296
:TOPICS: Characterization of Shale Gas Pore Structure, Powder Diffraction Analysis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1142/9789811284649_0005")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391537296"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391537296"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391537296"))][Get cited by]]

OpenAlex: https://openalex.org/W4391537296 (Open access: False)
    
[[https://openalex.org/A5055601807][Indrajit Shown]], [[https://openalex.org/A5064071602][Wei-Fu Chen]], [[https://openalex.org/A5059407034][Kuei‐Hsien Chen]], [[https://openalex.org/A5061993606][Li‐Chyong Chen]], World scientific series in nanoscience and nanotechnology. None(None)] 2024. https://doi.org/10.1142/9789811284649_0005 
     
No abstract    

    

* Role of Flexible Operation of a Wastewater Treatment Plant in the Reduction of Its Indirect Carbon Dioxide Emissions—A Case Study  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391432666
:TOPICS: Integration of Renewable Energy Systems in Power Grids, Hydrogen Energy Systems and Technologies, Wireless Sensor Networks for Data Analysis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/w16030483")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391432666"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391432666"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391432666"))][Get cited by]]

OpenAlex: https://openalex.org/W4391432666 (Open access: True)
    
[[https://openalex.org/A5093838468][Nilüfer Topuz]], [[https://openalex.org/A5080809344][Frank Alsmeyer]], [[https://openalex.org/A5037952789][Hasancan Okutan]], [[https://openalex.org/A5036968337][Hermann-Josef Roos]], Water. 16(3)] 2024. https://doi.org/10.3390/w16030483  ([[https://www.mdpi.com/2073-4441/16/3/483/pdf?version=1706841349][pdf]])
     
The increasing share of renewables in electricity grids comes with a challenge of energy surpluses and deficits, which needs be handled by demand side management (DSM) and storage options. Within this approach, wastewater treatment plants (WWTPs), with flexible energy consumption and production processes and storage units, can contribute to stabilizing the grids and integrating more renewables. In this study, the operation of a real WWTP was optimized by mixed integer linear programming (MILP) to minimize its indirect carbon dioxide (CO2) emissions. The operation of the WWTP was shown to be flexible in following the CO2 emission factor of the electricity grid, which was possible with the utilization of the WWTP’s storage units and flexible co-substrate feeding. As a result, by changing only the operational behavior of the WWTP, its indirect CO2 emissions decreased by 4.8% due to the higher share of renewables in the electricity grid. The CO2 emissions were shown to decrease further up to 6.9% by adding virtual storage units.    

    

* Metal-organic framework composites for electrochemical CO2 reduction reaction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391515522
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.126532")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391515522"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391515522"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391515522"))][Get cited by]]

OpenAlex: https://openalex.org/W4391515522 (Open access: False)
    
[[https://openalex.org/A5068670506][Kayode Adesina Adegoke]], [[https://openalex.org/A5008185576][Joshua O. Ighalo]], [[https://openalex.org/A5000341829][Jeanet Conradie]], [[https://openalex.org/A5091087628][Chinemerem Ruth Ohoro]], [[https://openalex.org/A5002534407][James F. Amaku]], [[https://openalex.org/A5019730915][Kabir O. Oyedotun]], [[https://openalex.org/A5041855090][Nobanathi Wendy Maxakato]], [[https://openalex.org/A5042386386][Kovo G. Akpomie]], [[https://openalex.org/A5057047276][Emmanuel Sunday Okeke]], [[https://openalex.org/A5018863848][Chijioke Olisah]], [[https://openalex.org/A5021557399][Alhadji Malloum]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.126532 
     
Carbon dioxide (CO2) levels in the atmosphere are quickly increasing as a consequence of anthropogenic activities, which present grave hazards and dangerous circumstances to not only humanity but also the ecosystem. Currently, electrochemical CO2 conversion to chemical/fuels remains one of the best methods for minimizing CO2 concentrations. Metal-organic frameworks (MOFs) composite materials have been considered as new class of highly-performed electrocatalysts for CO2 reduction reaction (CO2RR) due to their wide surface area, higher porosity, chemical tunability and excellent stability. This article presents major approaches for electrochemical CO2RR to value-added product. These were followed by discussing the recent advancements in MOF composite electrocatalysts for CO2RR including active sites MOF-supported electrocatalysts, metal-nanoparticles-supported MOFs, conductive supported MOFs composites, and polyoxometalate-based MOF composites. Lastly, some challenges currently facing MOF composites for CO2RR as well as anticipated future advances were discussed. Research hotspot lies in the creation of highly effective CO2RR electrocatalyst such as ligand engineering in MOFs. It is believed that the current study will contribute to accelerating the fabrication of efficient MOF composite materials for abating the CO2 emission in the ecosystem and to highlight the necessity for further research to address significant environmental sustainability concerns.    

    

* MXenes for CO2 reduction: a promising choice  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391488885
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/b978-0-323-95515-7.00011-x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391488885"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391488885"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391488885"))][Get cited by]]

OpenAlex: https://openalex.org/W4391488885 (Open access: False)
    
[[https://openalex.org/A5033369944][Saira Ajmal]], [[https://openalex.org/A5087525540][Anuj Kumar]], [[https://openalex.org/A5078487092][Tuan Anh Nguyen]], [[https://openalex.org/A5002637244][Ghulam Yasin]], Elsevier eBooks. None(None)] 2024. https://doi.org/10.1016/b978-0-323-95515-7.00011-x 
     
Fast industrialization and urban growth emit significant amounts of hazardous CO2, which not only produces environmental problems but also causes illness all over the world. Several technologies for purifying air and water have been developed over the last two decades, but they have all failed due to high costs, poor effectiveness, and the creation of secondary contaminants. The photochemical and electrochemical conversion of CO2 into energy-rich molecules is a novel method that can aid in environmental rehabilitation while also meeting the world’s expanding energy demands. These techniques, however, necessitate extremely selective, energetic, and long-lasting catalysts. Scientists have investigated numerous keen and multifunctional materials for the conversion of CO2 pollution into useful compounds in this area. MXenes, a type of two-dimensional (2D) material made of transition metal nitrides, carbides, and carbonitrides, have engrossed attention because of their extraordinary physicochemical, mechanical, and electrochemical properties. This chapter focuses on CO2 conversion by photochemical and electrochemical methods to valuable products, emphasizing MXene-based materials and their catalytic activity, as well as future prospects.    

    

* Efficient reduction of CO2 to CO by CdAl-LDHs nanostructured electrocatalysts in ionic liquids  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391543242
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jphotochem.2024.115518")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391543242"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391543242"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391543242"))][Get cited by]]

OpenAlex: https://openalex.org/W4391543242 (Open access: False)
    
[[https://openalex.org/A5029837106][Fang Tan]], [[https://openalex.org/A5031213658][Tianxia Liu]], [[https://openalex.org/A5088260235][Jian Ping Zhang]], Journal of Photochemistry and Photobiology A: Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jphotochem.2024.115518 
     
Layered bimetallic hydroxides are at the forefront of current research in electrocatalytic materials. Although there is considerable research on various bimetallic hydroxides, the study of bimetallic hydroxides for electrocatalytic reduction of carbon dioxide is limited. In this paper, cadmium-aluminum layered bimetallic hydroxide nanoparticles (CdAl-LDHs) were prepared using a simple electrochemical deposition method. The prepared CdAl-LDHs was characterized in detail, and its potential application as an electrocatalyst was discussed. CdAl-LDHs prepared using different methods showed different selectivity in the electrocatalytic reduction of CO2 to CO. The nanomaterial exhibits excellent CO selectivity in a reaction chamber using 2 %-BMIM(PF6)(1-butyl-3-methylimidazolium hexafluorophosphate)/DMF(N-N dimethyl formamide) as the electrolyte. The CdAl-LDHs prepared by electrochemical deposition exhibited a maximum CO partial current density of 22.13 mA cm−2 with a remarkable CO Faraday efficiency (FE) of 99.71 %, which is comparable to or even higher than that of noble metal catalysts. This high selectivity for CO indicates its potential as an alternative to expensive noble metal catalysts. Moreover, the catalyst demonstrated high stability over 30 h of continuous operation with stable FE of around 99 % and a current density of around 10.5 mA cm−2, with minimal degradation during the entire reaction cycle. In addition, the catalyst showed a low HER current density of less than 0.1 mA cm−2 at all tested potentials, indicating that the catalyst maintains a high level of CO2 conversion over the entire range of tested potentials. This suggests its great potential for industrial applications.    

    

* Haeckelite mediated reduction of CO2 by molecular hydrogen. A DFT study  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391487109
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.comptc.2024.114499")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391487109"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391487109"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391487109"))][Get cited by]]

OpenAlex: https://openalex.org/W4391487109 (Open access: False)
    
[[https://openalex.org/A5050072832][Wilmer Esteban Vallejo Narváez]], [[https://openalex.org/A5035427789][César Gabriel Vera de la Garza]], [[https://openalex.org/A5085613468][Serguei Fomine]], Computational and Theoretical Chemistry. None(None)] 2024. https://doi.org/10.1016/j.comptc.2024.114499 
     
In this study, we conducted a theoretical exploration of haeckelite-mediated CO2 reduction with molecular hydrogen. We used a haeckelite nanoflake (NF) consisting of 96 carbon atoms passivated with hydrogens to elucidate the reaction mechanism on the 2D surface. The most favorable reaction pathway involves the sequential formation of formic acid, formaldehyde, methanol, and ultimately methane. Notably, formic acid formation is favored over carbon monoxide. Haeckelite-mediated reactions exhibit Gibbs-free activation energies 10 to 40 kcal/mol lower compared to processes without a catalyst. This catalytic effect is attributed to the interaction of H2 with the haeckelite surface, which weakens or breaks the HH bond. This theoretical perspective provides significant insights into carbon-based materials and their potential applications in transforming CO2 into fuels and value-added chemicals.    

    

* Uncovering Photoelectronic and Photothermal Effects in Plasmon‐Mediated Electrocatalytic CO2 Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391605656
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202317740")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391605656"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391605656"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391605656"))][Get cited by]]

OpenAlex: https://openalex.org/W4391605656 (Open access: False)
    
[[https://openalex.org/A5088892322][Wei Yan]], [[https://openalex.org/A5007916816][Zijie Mao]], [[https://openalex.org/A5071678703][Tian-Wen Jiang]], [[https://openalex.org/A5014068004][Hong Li]], [[https://openalex.org/A5011686375][Xiao Ma]], [[https://openalex.org/A5069389722][Chao Zhan]], [[https://openalex.org/A5068660364][Wen‐Bin Cai]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202317740 
     
Plasmon‐mediated electrocatalysis that rests on the ability of coupling localized surface plasmon resonance (LSPR) and electrochemical activation, emerges as an intriguing and booming area. However, its development seriously suffers from the entanglement between the photoelectronic and photothermal effects induced by the decay of plasmons, especially under the influence of applied potential. Herein, using LSPR‐mediated CO2 reduction on Ag electrocatalyst as a model system, we quantitatively uncover the dominant photoelectronic effect on CO2 reduction reaction over a wide potential window, in contrast to the leading photothermal effect on H2 evolution reaction at relatively negative potentials. The excitation of LSPR selectively enhances the CO faradaic efficiency (17‐fold at −0.6 VRHE) and partial current density (100‐fold at −0.6 VRHE), suppressing the undesired H2 faradaic efficiency. Furthermore, in situ attenuated total reflection‐surface enhanced infrared absorption spectroscopy (ATR‐SEIRAS) reveals a plasmon‐promoted formation of the bridge‐bonded CO on Ag surface via a carbonyl‐containing C1 intermediate. The present work demonstrates a deep mechanistic understanding of selective regulation of interfacial reactions by coupling plasmons and electrochemistry.    

    

* Uncovering Photoelectronic and Photothermal Effects in Plasmon‐Mediated Electrocatalytic CO2 Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391612687
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202317740")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391612687"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391612687"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391612687"))][Get cited by]]

OpenAlex: https://openalex.org/W4391612687 (Open access: False)
    
[[https://openalex.org/A5088892322][Wei Yan]], [[https://openalex.org/A5007916816][Zijie Mao]], [[https://openalex.org/A5071678703][Tian-Wen Jiang]], [[https://openalex.org/A5014068004][Hong Li]], [[https://openalex.org/A5011686375][Xiao Ma]], [[https://openalex.org/A5069389722][Chao Zhan]], [[https://openalex.org/A5068660364][Wen‐Bin Cai]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202317740 
     
Plasmon‐mediated electrocatalysis that rests on the ability of coupling localized surface plasmon resonance (LSPR) and electrochemical activation, emerges as an intriguing and booming area. However, its development seriously suffers from the entanglement between the photoelectronic and photothermal effects induced by the decay of plasmons, especially under the influence of applied potential. Herein, using LSPR‐mediated CO2 reduction on Ag electrocatalyst as a model system, we quantitatively uncover the dominant photoelectronic effect on CO2 reduction reaction over a wide potential window, in contrast to the leading photothermal effect on H2 evolution reaction at relatively negative potentials. The excitation of LSPR selectively enhances the CO faradaic efficiency (17‐fold at −0.6 VRHE) and partial current density (100‐fold at −0.6 VRHE), suppressing the undesired H2 faradaic efficiency. Furthermore, in situ attenuated total reflection‐surface enhanced infrared absorption spectroscopy (ATR‐SEIRAS) reveals a plasmon‐promoted formation of the bridge‐bonded CO on Ag surface via a carbonyl‐containing C1 intermediate. The present work demonstrates a deep mechanistic understanding of selective regulation of interfacial reactions by coupling plasmons and electrochemistry.    

    

* Boosting photochemical reduction of CO2 to formic acid catalyzed by porphyrinic MOF-545  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391554925
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2021-07-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391554925"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391554925"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391554925"))][Get cited by]]

OpenAlex: https://openalex.org/W4391554925 (Open access: False)
    
[[https://openalex.org/A5025771580][Youven Benseghir]], [[https://openalex.org/A5086372340][Albert Solé‐Daura]], [[https://openalex.org/A5085164470][Mathis Duguet]], [[https://openalex.org/A5039753949][Pierre Mialane]], [[https://openalex.org/A5024792637][María Gómez-Mingot]], [[https://openalex.org/A5062221634][Marc Fontecave]], [[https://openalex.org/A5064073246][Anne Dolbecq]], [[https://openalex.org/A5032549164][Caroline Mellot‐Draznieks]], No host. None(None)] 2021. None 
     
No abstract    

    

* A Bio‐Inspired Bimetallic Fe‐M Catalyst for Electro‐ and Photochemical CO2 Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391537560
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301705")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391537560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391537560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391537560"))][Get cited by]]

OpenAlex: https://openalex.org/W4391537560 (Open access: False)
    
[[https://openalex.org/A5071052075][Yuhang Yao]], [[https://openalex.org/A5065282041][Jiahui Wu]], [[https://openalex.org/A5055399722][Guiyu Liu]], [[https://openalex.org/A5041022925][Ruijing Zhang]], [[https://openalex.org/A5085810240][Zi‐Shu Yang]], [[https://openalex.org/A5039657597][Song Gao]], [[https://openalex.org/A5071430741][Tai‐Chu Lau]], [[https://openalex.org/A5083162509][Junlong Zhang]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301705 
     
The conversion of CO2 into fuels or commodity chemicals by electrochemical or photochemical reduction is a promising strategy to relieve the ongoing energy crisis and increasing environmental pollution. Inspired by naturally occurring bimetalloenzymes, we have designed hetero‐bimetallic CO2 reduction catalysts (FeM) that involve linking an iron tetraphenylporphyrin (FeP) with a tripyridylamine (TPA) moiety, which provides a distal chelating site for Cu2+ or Zn2+. We found that the introduction of Cu2+ or Zn2+ to FeP greatly enhances its efficiency as a catalyst for the electrochemical reduction of CO2. To gain insights into the observed synergistic effect, we performed mechanistic studies together with density functional theory (DFT) calculations. Our results show that Cu2+ or Zn2+ activates CO2 towards reduction due to its Lewis acidity; it also functions as an oxo acceptor from CO2. FeM also functions as an efficient catalyst for the visible‐light‐driven reduction of CO2 using either [Ru(bpy)3]Cl2 or fac‐Ir(ppy)3 (where bpy = 2,2’‐bipyridine, ppy = 2‐phenylpyridine) as photosensitizer and 1,3‐dimethyl‐2‐phenyl‐2,3‐dihydro‐1H‐benzo[d]imidazole (BIH) as sacrificial reductant. Again, the catalytic efficiency is enhanced by the presence Cu2+ or Zn2+. Our results provide a general strategy for the design of a series of hetero‐bimetallic catalysts for the reduction of CO2.    

    

* Coupled Electrochemical Reduction of CO2 and H+ in the Presence of Substituted 2,2'-Bipyridinium Salts  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391550662
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2023-11-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1134/s107042802311009x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391550662"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391550662"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391550662"))][Get cited by]]

OpenAlex: https://openalex.org/W4391550662 (Open access: False)
    
[[https://openalex.org/A5048834107][E. V. Okina]], [[https://openalex.org/A5083682754][L. A. Klimaeva]], [[https://openalex.org/A5075408705][Д. Б. Чугунов]], [[https://openalex.org/A5049624623][S. G. Kostryukov]], [[https://openalex.org/A5087234431][A. S. Kozlov]], [[https://openalex.org/A5067767641][O. V. Tarasova]], [[https://openalex.org/A5023314423][A. D. Yudina]], Russian Journal of Organic Chemistry. 59(11)] 2023. https://doi.org/10.1134/s107042802311009x 
     
No abstract    

    

* Analysis of the effects of EEDI and EEXI implementation on CO2 emissions reduction in ships  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391559475
:TOPICS: Environmental Impact of Maritime Transportation Emissions, Estimating Vehicle Fuel Consumption and Emissions, Integrated Pollution Prevention and Control Techniques
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.oceaneng.2024.116877")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391559475"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391559475"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391559475"))][Get cited by]]

OpenAlex: https://openalex.org/W4391559475 (Open access: False)
    
[[https://openalex.org/A5029682509][S. H. Lee]], Ocean Engineering. 295(None)] 2024. https://doi.org/10.1016/j.oceaneng.2024.116877 
     
No abstract    

    

* DBD-coupled highly dispersed Ni/SiO2 materials for CO2 reduction performance and mechanism study  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391616481
:TOPICS: Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.joei.2024.101552")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391616481"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391616481"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391616481"))][Get cited by]]

OpenAlex: https://openalex.org/W4391616481 (Open access: False)
    
[[https://openalex.org/A5049417366][Jiawen Chi]], [[https://openalex.org/A5049466637][Xue‐Qian Wu]], [[https://openalex.org/A5046586913][Jing Tao]], [[https://openalex.org/A5018974034][Xin Min]], [[https://openalex.org/A5010444377][Zhen Li]], [[https://openalex.org/A5039148281][Songjian Zhao]], Journal of the Energy Institute. None(None)] 2024. https://doi.org/10.1016/j.joei.2024.101552 
     
Climate warming caused by the yearly rise of CO2 emissions has posed a great challenge to the survival and development of human beings. In this study, the active component Ni was combined with mesoporous silica (SiO2) to construct a highly dispersed Ni composite silicon-based catalyst (Nix/Si), which was introduced into the dielectric barrier discharge (DBD) system for the conversion of CO2. The XRD and FTIR analyses confirmed that Ni was successfully introduced into the SiO2 carrier and the SEM results showed that the Ni elements were uniformly distributed. BET and TGA results revealed large specific surface area, stable mesoporous structure, and high thermal stability of the prepared Nix/Si. Further investigation of DBD-coupled Nix/Si performance for CO2 conversion showed significant variations based on different Ni loadings, with optimal CO2 conversion rate, CO yield, and energy efficiency achieved at 3% Ni loading, which increased by 121.8%, 101.5%, and 102.4% respectively compared to the SiO2 support. During the process of reducing CO2, the combination of Nix/Si and DBD exhibited synergistic effects, with Ni0 playing a crucial role in the CO2 reduction. The introduction of Nix/Si enhances charge transfer in the discharge region, improves CO2 adsorption, and reduces the dissociation energy of CO2 bonds. The DBD-coupled Nix/Si developed by this study offers several advantages including low energy consumption, simple operation, and high efficiency, making it a promising solution for CO2 treatment.    

    

* Self-supported copper-based gas diffusion electrodes improve the local CO2 concentration for efficient electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391439692
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11705-024-2392-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391439692"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391439692"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391439692"))][Get cited by]]

OpenAlex: https://openalex.org/W4391439692 (Open access: False)
    
[[https://openalex.org/A5044830523][Azeem Mustafa]], [[https://openalex.org/A5002560306][Bachirou Guene Lougou]], [[https://openalex.org/A5049375655][Yong Shuai]], [[https://openalex.org/A5026704658][Zhijiang Wang]], [[https://openalex.org/A5049094441][Haseeb-ur-Rehman]], [[https://openalex.org/A5020400471][Samia Razzaq]], [[https://openalex.org/A5084139753][Wei Wang]], [[https://openalex.org/A5061893306][Ruming Pan]], [[https://openalex.org/A5014738262][Jiupeng Zhao]], Frontiers of Chemical Science and Engineering. 18(3)] 2024. https://doi.org/10.1007/s11705-024-2392-6 
     
No abstract    

    

* Highly selective electrocatalytic reduction of CO2 to HCOOH over an in-situ derived Ag-loaded Bi2O2CO3 electrocatalyst  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391546693
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3dt04342h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391546693"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391546693"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391546693"))][Get cited by]]

OpenAlex: https://openalex.org/W4391546693 (Open access: True)
    
[[https://openalex.org/A5091351871][Wei Zheng]], [[https://openalex.org/A5084793778][Changlai Wang]], [[https://openalex.org/A5048379858][Jing Chen]], [[https://openalex.org/A5005901099][Chen Shi]], [[https://openalex.org/A5069028297][Zhiyu Lin]], [[https://openalex.org/A5022809443][Minxue Huang]], [[https://openalex.org/A5079879393][Hao Huang]], [[https://openalex.org/A5042856845][Yafei Qu]], [[https://openalex.org/A5008620166][Peichen Wang]], [[https://openalex.org/A5077163216][Haibo Lin]], [[https://openalex.org/A5014087781][Qianwang Chen]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d3dt04342h  ([[https://pubs.rsc.org/en/content/articlepdf/2024/dt/d3dt04342h][pdf]])
     
The electrochemical reduction of CO2 to HCOOH is considered as one of the most appealing routes to alleviate the energy crisis and close the anthropogenic CO2 cycle. However, it remains...    

    

* Highly-exposed copper and ZIF-8 interface enables synthesis of hydrocarbons by electrocatalytic reduction of CO2  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391515357
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.205")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391515357"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391515357"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391515357"))][Get cited by]]

OpenAlex: https://openalex.org/W4391515357 (Open access: False)
    
[[https://openalex.org/A5051918964][Bo Sun]], [[https://openalex.org/A5055556997][Hao Hu]], [[https://openalex.org/A5085590943][Hangchen Liu]], [[https://openalex.org/A5091352802][Jun Guan]], [[https://openalex.org/A5073878947][Kexing Song]], [[https://openalex.org/A5016615882][Changrui Shi]], [[https://openalex.org/A5078897846][Haoyan Cheng]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.205 
     
Electrochemical reduction of CO2 (CO2RR) to fuels and chemicals is a promising route to close the anthropogenic carbon cycle for sustainable society. The Cu-based catalysts in producing high-value hydrocarbons feature unique superiorities, yet challenges remain in achieving high selectivity. In this work, Cu@ZIF-8 NWs with highly-exposed Cu nanowires (Cu NWs) and ZIF-8 interface are synthesized via a surfactant-assisted method. Impressively, Cu@ZIF-8 NWs exhibit excellent stability and a high Faradaic efficiency of 57.5% toward hydrocarbons (CH4 and C2H4) at a potential of -0.7 V versus reversible hydrogen electrode. Computational calculations combining with experiments reveal the formation of Cu and ZIF-8 interface optimizes the adsorption of reaction intermediates, particularly stabilizing the formation of *CHO, thereby enabling efficient preference for hydrocarbons. This work highlights the potential of constructing metals and MOFs heterogeneous interfaces to enhance catalytic properties and offers valuable insights for the design of highly efficient CO2RR catalysts.    

    
