#+filetags: CO2RR
#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Fri Feb 23 00:42:54 2024

Found 29 results from 2024-02-16 to 2024-02-23
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* High selective electrocatalytic reduction of carbon dioxide to ethylene enabled by regulating the microenvironment over Cu-Ag nanowires  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391850244
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.02.028")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391850244"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391850244"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391850244"))][Get cited by]]

OpenAlex: https://openalex.org/W4391850244 (Open access: False)
    
[[https://openalex.org/A5045324032][D. D. Fan]], [[https://openalex.org/A5037700860][Zhang Shi-ji]], [[https://openalex.org/A5086243301][Yumeng Li]], [[https://openalex.org/A5048916799][Bin Hua]], [[https://openalex.org/A5005268469][Ruopeng Li]], [[https://openalex.org/A5025757874][Yaqiang Li]], [[https://openalex.org/A5070825762][Anmin Liu]], [[https://openalex.org/A5089539354][Peixia Yang]], [[https://openalex.org/A5031711386][Jinqiu Zhang]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.02.028 
     
Copper-based tandem catalysts are effective candidates for yielding multi-carbon (C2+) products in electrochemical reduction of carbon dioxide (CO2RR). However, these catalysts still face a significant challenge regarding in the low selectivity for the production of a specific product. In this study, we report a high selectivity of 77.8 %±2% at −1.0 V (vs RHE) for the production of C2H4 by using a Cu88Ag12NW catalyst which is primarily prepared through a combined Cu-Ag co-deposition and wet chemical method, employing an attractive strategy focused on regulating the microenvironment over Cu-Ag nanowires. The experimental and computational studies show that the higher *CO coverage and lower intermediate adsorption energy are important reasons for achieving the high C2H4 selectivity of Cu88Ag12NW catalyst. Comsol simulation results indicate that dense nanowires exhibit a nano-limiting effect on OH− ions, thereby leading to an increase in local pH and promoting coupling reactions. The catalyst demonstrates no noticeable decrease in current density or selectivity even after 12 h of continuous operation. The Cu-Ag nanowire composite exhibits remarkable catalytic activity, superior faradaic efficiency, excellent stability, and easy synthesis, which highlights its significant potential for electro-reducing carbon dioxide into valuable products.    

    

* Surface Termination Dependent Carbon Dioxide Reduction Reaction on Ti3C2 MXene  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391853343
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Accelerating Materials Innovation through Informatics, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00320a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391853343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391853343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391853343"))][Get cited by]]

OpenAlex: https://openalex.org/W4391853343 (Open access: True)
    
[[https://openalex.org/A5080818001][Ling Meng]], [[https://openalex.org/A5087707184][Likai Yan]], [[https://openalex.org/A5012273051][Francesc Illas]], [[https://openalex.org/A5012273051][Francesc Illas]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d4ta00320a  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ta/d4ta00320a][pdf]])
     
The use of two-dimensional (2D) MXene materials as highly efficient electrocatalysts for carbon dioxide reduction reaction (CO 2 RR) has gained considerable attention in the last years. However, current computational studies on...    

    

* Photocatalytic sponges for wastewater treatment, carbon dioxide reduction, and hydrogen production: a review  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391881021
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10311-024-01696-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391881021"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391881021"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391881021"))][Get cited by]]

OpenAlex: https://openalex.org/W4391881021 (Open access: False)
    
[[https://openalex.org/A5023804914][Akash Balakrishnan]], [[https://openalex.org/A5084872777][Meenu Mariam Jacob]], [[https://openalex.org/A5013338055][Mahendra Chinthala]], [[https://openalex.org/A5083688944][Nanditha Dayanandan]], [[https://openalex.org/A5009615295][M. N. Ponnuswamy]], [[https://openalex.org/A5072272612][Dai‐Viet N. Vo]], Environmental Chemistry Letters. None(None)] 2024. https://doi.org/10.1007/s10311-024-01696-5 
     
No abstract    

    

* Benzyl alcohol promoted electrocatalytic reduction of carbon dioxide and C2 production by Cu2O/Cu  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391896197
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149800")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391896197"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391896197"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391896197"))][Get cited by]]

OpenAlex: https://openalex.org/W4391896197 (Open access: False)
    
[[https://openalex.org/A5062755510][Qianqian Wang]], [[https://openalex.org/A5002720688][Xinfa Wei]], [[https://openalex.org/A5038076952][Yan Li]], [[https://openalex.org/A5066895322][Juanjuan Luo]], [[https://openalex.org/A5032212993][Lisong Chen]], [[https://openalex.org/A5085739377][Jianlin Shi]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149800 
     
Oxide-derived copper (OD-Cu)-based materials containing Cuδ+ (0 < δ ≤ 1) have been considered as promising electrocatalysts for electrochemical CO2 reduction reaction (ECO2RR) to produce valuable C2 products, which, however, suffer from poor stability, mainly due to the inevitable reduction of Cuδ+. We report here that the benzyl alcohol (BA) introduced in catholyte presents a markedly positive effect on the durability and C2 selectivity enhancement of ECO2RR when OD-Cu-based material is adopted as cathode electrocatalyst. The critical evidence of ECO2RR intermediates has been provided by in situ Raman and FTIR spectroscopy, which reveals the surface mechanisms of BA-assisted ECO2RR over OD-Cu catalysts. On the one hand, the introduction of BA increases the CO2 supply for ECO2RR by slowing down its neutralizing reaction, which results in the increased intermediate species coverage on the catalytic surface therefore the delayed self-reduction of Cuδ+; On the other hand, the interaction between BA and the intermediate species *CO during ECO2RR brings an enhanced selectivity of C2 products (FE C2 = 85.5 % at −1.38 V vs RHE). Besides, an energy-savings and economic electrolyzer can be achieved by coupling anodic BA oxidation reaction to benzoic acid and ECO2RR to C2 products with much lowered cell voltages.    

    

* Solar fuels design: Porous cathodes modeling for electrochemical carbon dioxide reduction in aqueous electrolytes  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391912845
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.heliyon.2024.e26442")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391912845"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391912845"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391912845"))][Get cited by]]

OpenAlex: https://openalex.org/W4391912845 (Open access: True)
    
[[https://openalex.org/A5078465991][Iva Fernandes]], [[https://openalex.org/A5013274345][Duarte J. Antunes]], [[https://openalex.org/A5088870986][Rodrigo Martins]], [[https://openalex.org/A5090314980][Manuel J. Mendes]], [[https://openalex.org/A5091770973][Ana S. Reis Machado]], Heliyon. None(None)] 2024. https://doi.org/10.1016/j.heliyon.2024.e26442 
     
No abstract    

    

* Strategies to Improve the Activity of Silver‐loaded Calcium Titanate Crystal Photocatalyst for Photocatalytic Reduction of Carbon Dioxide with Water  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391932224
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301736")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391932224"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391932224"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391932224"))][Get cited by]]

OpenAlex: https://openalex.org/W4391932224 (Open access: False)
    
[[https://openalex.org/A5080636617][Hongxuan Qiu]], [[https://openalex.org/A5021171836][Akira Yamamoto]], [[https://openalex.org/A5057290198][Hisao Yoshida]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301736 
     
The rapid increase of carbon dioxide (CO2) in the atmosphere has sparked a global enthusiasm for carbon recycling. Photocatalytic CO2 reduction with water into carbon‐containing products has attracted much attention since it can convert solar energy to the chemical potential of the products and CO2 to valuable compounds at the same time. One of the main products in the photocatalytic reaction system is carbon monoxide (CO), a useful compound for the one‐carbon chemistry and related ones. The current shortage of this system is the low production efficiency, demanding us to improve the activity of the photocatalyst. In this perspective article, by taking a calcium titanate (CaTiO3, CTO) photocatalyst with silver cocatalyst (Ag/CTO) and so on as examples that can promote the selective photocatalytic CO2 reduction with water, we shortly review some strategies to improve the photocatalytic activity such as fabrication of well‐structured crystal photocatalysts, development of the surface property and cocatalyst, improvement of surface CO2 adsorption, and improvement of photoabsorption. These concepts will be widely applied and contribute to further development of photocatalytic systems.    

    

* Role of single-atom alloy catalysts in electrochemical conversion of carbon dioxide: A theoretical study  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391933654
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ces.2024.119910")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391933654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391933654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391933654"))][Get cited by]]

OpenAlex: https://openalex.org/W4391933654 (Open access: False)
    
[[https://openalex.org/A5014030303][Jingnan Wang]], [[https://openalex.org/A5087019504][Keli Zhao]], [[https://openalex.org/A5005325306][Yi Ding]], [[https://openalex.org/A5015906224][Yongan Yang]], [[https://openalex.org/A5013471192][Xi Wu]], Chemical Engineering Science. None(None)] 2024. https://doi.org/10.1016/j.ces.2024.119910 
     
Atomic-scale understanding of C-C coupling in the electrocatalytic conversion of carbon dioxide (CO2) into valuable C2 chemicals remains elusive. Herein, we selected Group VIII and IB transition metals as active sites incorporated into the Cu(1 0 0) surface to construct single-atom alloy catalysts. The stability, selectivity, and activity of a series of catalysts were calculated using density functional theory. Fe, Co, Ni, Ru/Cu(1 0 0) exhibit the potential as candidates to generate C2 products and suppress the hydrogen evolution reaction (HER). The reaction proceeds through the reduction of CO2 to key intermediates *CO and *CHO, which undergoes C-C coupling to generate *CO-CHO, subsequently undergoing different protonation processes to yield diverse C2 products. The rate-determining step for Fe, Co, Ni, and Ru/Cu(1 0 0), is the hydrogenation of *CO, with a comparable energy barrier of 0.8 eV. Moreover, Fe and Co/Cu(1 0 0) favor the formation of C2H4 as the primary product, while Ni and Ru/Cu(1 0 0) predominantly produce CH3COOH.    

    

* Comparative life cycle analysis on ethylene production from electrocatalytic reduction of carbon dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391934036
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Energy Consumption in Mobile Devices and Networks, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jclepro.2024.141348")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391934036"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391934036"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391934036"))][Get cited by]]

OpenAlex: https://openalex.org/W4391934036 (Open access: False)
    
[[https://openalex.org/A5029687537][Taemin Kim]], [[https://openalex.org/A5002326326][Pahola Thathiana Benavides]], Journal of Cleaner Production. None(None)] 2024. https://doi.org/10.1016/j.jclepro.2024.141348 
     
Ethylene is one of the largest greenhouse gas emitters and the most diversly used commodity chemicals globally. Electrocatalytic reduction of CO2 to ethylene received great attention from the research society to decarbonize the ethylene production. In this study, a life-cycle analysis is conducted using the Greenhouse Gases, Regulated Emissions, and Energy use in Technologies (GREET) model on the three electrocatalytic CO2-reduction pathways (or “e-ethylene” pathways): i) cascade conversion via carbon monoxide intermediate; ii) single-step conversion in membrane electrode assembly (MEA); and iii) single-step conversion in alkaline flow cell. The results showed that the electricity consumption is the lowest for the cascade pathway (164 MJ/kg), thus resulting in the lowest cradle-to-gate carbon intensity [18 kgCO2e/kg with United States (US) average grid)] among the three pathways followed by the single-step MEA (32 kgCO2e/kg) and then by the single-step alkaline (56 kgCO2e/kg). However, all three e-ethylene pathways were significantly more carbon-intensive than their fossil-based counterpart (1.1 kgCO2e/kg) due to their excessive energy consumption with the current state of technology. With renewable electricity, all three pathways yielded negative carbon intensity: from −3.1 kgCO2e/kg to −1.6 kgCO2e/kg depending on the source of CO2. The threshold carbon intensity of electricity (TCIE), defined as the upper bound of the carbon intensity of electricity to achieve lower carbon intensity for e-ethylene compared to fossil-based ethylene, is calculated for both current and future state of e-ethylene technologies. The cascade pathway had the highest TCIE out of the three e-ethylene pathways for both current (92 gCO2e/kWh) and future (124 gCO2e/kWh) state of technologies. However, the carbon intensity of average US grid (i.e., 467 and 303 gCO2e/kWh for current and future projections) were higher than the TCIEs of the corresponding timeline. Thus, reducing electricity requirement for e-ethylene pathways and bringing low-carbon generation mix in the United States (US) grid faster than the current projection are both essential to decarbonize ethylene and its downstream chemicals/polymers.    

    

* Recent advances of 2D metal-organic frameworks for electrochemical carbon dioxide reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391969766
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mtcata.2024.100043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391969766"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391969766"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391969766"))][Get cited by]]

OpenAlex: https://openalex.org/W4391969766 (Open access: True)
    
[[https://openalex.org/A5043593230][Xingcheng Ma]], [[https://openalex.org/A5073215457][Meiling Xiao]], [[https://openalex.org/A5056139025][Changpeng Liu]], [[https://openalex.org/A5029851581][Xing Wang]], Materials Today Catalysis. None(None)] 2024. https://doi.org/10.1016/j.mtcata.2024.100043 
     
No abstract    

    

* Promoting hydrophilic cupric oxide electrochemical carbon dioxide reduction to methanol via interfacial engineering modulation  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391980122
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.02.128")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391980122"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391980122"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391980122"))][Get cited by]]

OpenAlex: https://openalex.org/W4391980122 (Open access: False)
    
[[https://openalex.org/A5037110364][Xianan Du]], [[https://openalex.org/A5017375422][Bo Gao]], [[https://openalex.org/A5049259092][Chunhui Xiao]], [[https://openalex.org/A5023780872][Hongyang Zhao]], [[https://openalex.org/A5025953218][Zhongxiao Song]], [[https://openalex.org/A5011336008][Ki Tae Nam]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.02.128 
     
Copper-based catalysts have been extensively investigated in electrochemical carbon dioxide (CO2) reduction to promote carbon products generated by requiring multiple electron transfer. However, hydrophilic electrodes are unfavourable for CO2 mass transfer and preferentially hydrogen (H2) evolution in electrochemical CO2 reduction. In this paper, a hydrophilic cupric oxide (CuO) electrode with a grassy morphology was prepared. CuO-derived Cu was confirmed as the active site for electrochemical CO2 reduction through wettability modulation. To enhance the intrinsic catalytic activity, a metal-oxide heterogeneous interface was created by engineering modulation at the interface, involving the loading of palladium (Pd) on CuO (CuO/Pd). Both the electrochemically active area and the electron transfer rate were enhanced by Pd loading, and significantly the reduced work function further facilitated the electron transfer between the electrode surface and the electrolyte. Consequently, the CuO/Pd electrode exhibited excellent excellent performance in electrochemical CO2 reduction, achieving a 54 % Faraday efficiency at −0.65 V for methanol (CH3OH). The metal-oxide interfacial effect potentially improves the intrinsic catalytic activity of hydrophilic CuO electrodes in electrochemical CO2 reduction, providing a conducive pathway for optimizing hydrophilic oxide electrodes in this process.    

    

* Carbon Dioxide Electroreduction and Formic Acid Oxidation by Formal Nickel(I) Complexes of Di‐isopropylphenyl Bis‐iminoacenaphthene  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391996987
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202400168")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391996987"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391996987"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391996987"))][Get cited by]]

OpenAlex: https://openalex.org/W4391996987 (Open access: False)
    
[[https://openalex.org/A5005398637][Vera V. Khrizanforova]], [[https://openalex.org/A5029544797][Robert R. Fayzullin]], [[https://openalex.org/A5048595722][Sergey Kartashov]], [[https://openalex.org/A5045939832][В. И. Морозов]], [[https://openalex.org/A5090357376][Mikhail Khrizanforov]], [[https://openalex.org/A5053779338][Tatyana Gerasimova]], [[https://openalex.org/A5032597266][Yulia H. Budnikova]], Chemistry - A European Journal. None(None)] 2024. https://doi.org/10.1002/chem.202400168 
     
Processing CO2 into value‐added chemicals and fuels stands as one of the most crucial tasks in addressing the global challenge of the greenhouse effect. In this study, we focused on the complex (dpp‐bian)NiBr2 (where dpp‐bian is di‐isopropylphenyl bis‐iminoacenaphthene) as a precatalyst for the electrochemical reduction of CO2 into CH4 as the sole product. Cyclic voltammetry results indicate that the realization of a catalytically effective pattern requires the three‐electron reduction of (dpp‐bian)NiBr2. The chemically reduced complexes [K(THF)6]+[(dpp‐bian)Ni(COD)]– and [K(THF)6]+[(dpp‐bian)2Ni]– were synthesized and structurally characterized. Analyzing the data from the electron paramagnetic resonance study of the complexes in a solution, along with quantum‐chemical calculations, reveals that the spin density is predominantly localized at their metal centers. The superposition of trajectory maps of the electron density gradient field and the one‐electron electrostatic force field, along with the atomic charges, discloses that, within the first coordination sphere, the interatomic charge transfer occurs from the metal atom to the ligand atoms and that the complex anions can thus be formally described by the general formulas (dpp‐bian)2–Ni+(COD) and (dpp‐bian)2–Ni+. It was shown that the reduced nickel complexes can be oxidized by formic acid; resulting from this reaction, the two‐electron and two‐proton addition product dpp‐bian‐2H is formed.    

    

* Carbon Dioxide Lingual Tonsil Reduction for Obstructive Sleep Apnea: A Feasibility Study  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391907254
:TOPICS: Sleep-Disordered Breathing and Health Outcomes, Neural Mechanisms of Respiratory Control and Homeostasis, Clinical Management of Tracheal and Airway Disorders
:PUBLICATION_DATE: 2024-12-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.23937/2572-4053.1510043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391907254"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391907254"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391907254"))][Get cited by]]

OpenAlex: https://openalex.org/W4391907254 (Open access: True)
    
[[https://openalex.org/A5093948541][Fontenot Andee]], [[https://openalex.org/A5053122964][Chuan Liu]], [[https://openalex.org/A5093948542][Dewan Karuna]], Journal of sleep disorders and management. 9(1)] 2024. https://doi.org/10.23937/2572-4053.1510043  ([[https://clinmedjournals.org/articles/jsdm/journal-of-sleep-disorders-and-management-jsdm-9-043.pdf?jid=jsdm][pdf]])
     
Obstructive sleep apnea (OSA) is characterized by frequent episodes of upper airway collapse during sleep. The lingual tonsil, when hypertrophic, can contribute to airway obstruction. The purpose of this study was to establish the utility and safety of the carbon dioxide (CO2) laser for tonsillar reduction in the management of OSA.    

    

* Gallium Nitride‐Based Artificial Photosynthesis Integrated Devices for Solar Hydrogen Generation and Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391875089
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/9781119600862.ch11")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391875089"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391875089"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391875089"))][Get cited by]]

OpenAlex: https://openalex.org/W4391875089 (Open access: False)
    
[[https://openalex.org/A5010878103][Baowen Zhou]], [[https://openalex.org/A5050902155][Peng Zhou]], [[https://openalex.org/A5061245884][Dong Wu]], [[https://openalex.org/A5070775523][Zetian Mi]], No host. None(None)] 2024. https://doi.org/10.1002/9781119600862.ch11 
     
No abstract    

    

* Analysis of CO2 emissions reduction via by-product hydrogen  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391849200
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.138")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391849200"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391849200"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391849200"))][Get cited by]]

OpenAlex: https://openalex.org/W4391849200 (Open access: False)
    
[[https://openalex.org/A5002099738][Chao Wang]], [[https://openalex.org/A5091103434][Yongqiang Li]], [[https://openalex.org/A5000920240][Junmin Wan]], [[https://openalex.org/A5047421180][Yi Hu]], International Journal of Hydrogen Energy. None(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.138 
     
Hydrogen is a clean energy in the world and by-product hydrogen is an important part of global hydrogen production. The yield of by-product hydrogen accounts for 18% of hydrogen production globally. To analyze the current stage and calculate CO2 emissions reduction of by-product hydrogen, sources, purification technology, utilization models, comparison of by-product hydrogen and other hydrogen resources, reduction of CO2 emissions, prospects of industrial by-product hydrogen were analyzed from the respective of industrial utilization. The resources of by-product hydrogen will get expanded further. It can facilitate the utilization of industrial by-product hydrogen to establish industrial zone with the factories producing by-product hydrogen and the downstream factories utilizing by-product hydrogen under the current technology conditions. By analyzing the relevant data, it is calculated that the utilization of industrial by-product hydrogen can reduce CO2 emissions by 6.11x105 t per year in 2022. With the development of hydrogen purification technology, by-product hydrogen can provide an efficient and economical way to reduce CO2 emissions for global warming migration before the completion of green hydrogen substitution for other hydrogen.    

    

* Sustainability Assessment Of Carbon Dioxide Emission Reduction From Energy Use In Cement Production Via Life Cycle Assessment And Ahp  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391915352
:TOPICS: Influence of Recycled Aggregate Concrete on Construction
:PUBLICATION_DATE: 2024-02-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.46799/ajesh.v3i2.240")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391915352"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391915352"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391915352"))][Get cited by]]

OpenAlex: https://openalex.org/W4391915352 (Open access: False)
    
[[https://openalex.org/A5082055160][Fatimatuz Zahro]], [[https://openalex.org/A5093950340][Irwan Bagyo]], [[https://openalex.org/A5092147931][Feni Eka Juliani]], Asian Journal of Engineering Social and Health. 3(2)] 2024. https://doi.org/10.46799/ajesh.v3i2.240 
     
The cement industry in supporting sustainable development is faced with the challenge of reducing energy consumption, natural resources and emissions generated from its production activities. PT X is one of the cement industries in Indonesia that has a production design capacity of 2.6 million tons/year. PT X's cement production activities use several fossil fuel energy sources and alternative fuels that can produce carbon dioxide emissions that are wasted into the environment. This study aims to identify process units that produce significant impacts to determine alternative environmental improvement scenarios. The method used is Life Cycle Assessment (LCA) as a tool for calculating potential environmental impacts, and AHP as an alternative selection of environmental improvement program scenarios. The scope of the LCA study carried out with the scope of "Cradle to Gate" includes the stages of the raw material extraction process, the production process to the distribution of cement. The resulting potential environmental impact is a total Global Warming Potential (GWP) of 0.20543 tons CO2 eq/ton. The largest potential impact comes from the kiln unit of 0.20221 tons CO2 eq/ton or an impact contribution of 98.43%. Based on the environmental impacts generated, there are 4 alternative programs that can be used to reduce the environmental impacts generated. The selection of alternative program scenarios is based on 3 criteria based on 3 types of respondents. Alternatif program yang memiliki nilai prioritas tertinggi yaitu alternatif program 1 dengan sebesar 35,5%, 38,1%, dan 23,4%.    

    

* Electrochemical CO2 Reduction by Urea Hangman Mn Terpyridine species  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391881952
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202304218")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391881952"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391881952"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391881952"))][Get cited by]]

OpenAlex: https://openalex.org/W4391881952 (Open access: False)
    
[[https://openalex.org/A5008108716][Minghong Li]], [[https://openalex.org/A5004948530][Fang Huang]], [[https://openalex.org/A5055151897][Ping Zhang]], [[https://openalex.org/A5041998803][Ying Xiong]], [[https://openalex.org/A5030775427][Yaping Zhang]], [[https://openalex.org/A5005228021][Fĕi Li]], [[https://openalex.org/A5040730537][Cheng Huang Lin]], Chemistry - A European Journal. None(None)] 2024. https://doi.org/10.1002/chem.202304218 
     
Based on our previous study in chemical subtleties of the proton tunneling distance for metal hydride formation (PTD‐MH) to regulate the selectivity of CO2 reduction reaction (CO2RR), we have developed a family of Mn terpyridine derivatives, in which urea groups functioning as multipoint hydrogen‐bonding hangman to accelerate the reaction rate. We found that such changes to the second coordination sphere significantly increased the turnover frequency (TOF) for CO2 reduction to ca. 360 s‐1 with this family of molecular catalysts while maintaining high selectivity (ca. 100% ± 3) for CO even in the presence of a large amount of phenol as proton source. Notably, the compounds studied in this manuscript all exhibit large value for CO as that achieved by Fe porphyrins derivates, while saving up to 0.55 V in overpotential with respect to the latter.    

    

* Coupling of Electrocatalytic CO2 Reduction and CH4 Oxidation for Efficient Methyl Formate Electrosynthesis  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391854676
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ee00087k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391854676"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391854676"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391854676"))][Get cited by]]

OpenAlex: https://openalex.org/W4391854676 (Open access: False)
    
[[https://openalex.org/A5055720455][Quan Zhang]], [[https://openalex.org/A5045304582][Yangshen Chen]], [[https://openalex.org/A5035054349][Shuai Yan]], [[https://openalex.org/A5046867944][Ximeng Lv]], [[https://openalex.org/A5006812397][Chao Yang]], [[https://openalex.org/A5006596822][Min Kuang]], [[https://openalex.org/A5062325923][Gengfeng Zheng]], Energy and Environmental Science. None(None)] 2024. https://doi.org/10.1039/d4ee00087k 
     
The electrocatalytic carbon dioxide reduction reaction (CO2RR) is promising for converting this greenhouse gas into value-added chemicals, while it suffers from limited energy efficiency and product variability. The direct coupling...    

    

* Photobreeding oxygen vacancy facilitates phtocatalytic reduction of CO2  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391940930
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.126842")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391940930"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391940930"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391940930"))][Get cited by]]

OpenAlex: https://openalex.org/W4391940930 (Open access: False)
    
[[https://openalex.org/A5065912071][Shuai Li]], [[https://openalex.org/A5078251665][Yanfeng Zhang]], [[https://openalex.org/A5071798264][Lei Zhang]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.126842 
     
No abstract    

    

* The implementation of intelligent edification to improve the energy efficiency and CO2 emission’s reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4392008284
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization, Parametric Architecture and Urban Design, Building Information Modeling in Construction Industry
:PUBLICATION_DATE: 2023-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/c358072.2023.10436172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392008284"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392008284"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392008284"))][Get cited by]]

OpenAlex: https://openalex.org/W4392008284 (Open access: False)
    
[[https://openalex.org/A5093973079][Surichaqui Alvarez Sebastian Amulek]], [[https://openalex.org/A5093973080][Castro Casas Alexis Del Piero]], No host. None(None)] 2023. https://doi.org/10.1109/c358072.2023.10436172 
     
No abstract    

    

* Enhancing Cu-Ligand Interaction for Efficient CO2 Reduction towards Multi-carbon Products  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391967024
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cc05972c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391967024"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391967024"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391967024"))][Get cited by]]

OpenAlex: https://openalex.org/W4391967024 (Open access: True)
    
[[https://openalex.org/A5020966645][Jingyi Chen]], [[https://openalex.org/A5034579880][Fan Li]], [[https://openalex.org/A5062736286][Yan Zhao]], [[https://openalex.org/A5007921737][Haozhou Yang]], [[https://openalex.org/A5052304130][Di Wang]], [[https://openalex.org/A5060013088][Bihao Hu]], [[https://openalex.org/A5031292832][Shibo Xi]], [[https://openalex.org/A5061600997][Lei Wang]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d3cc05972c  ([[https://pubs.rsc.org/en/content/articlepdf/2024/cc/d3cc05972c][pdf]])
     
Electrochemical CO2 reduction (CO2R) to valuable products provides a promising strategy to enable CO2 utilization sustainably. Here, we report the strategy of using Cu-DAT (3,5-diamino-1,2,4-triazole) as catalyst precursors for efficient...    

    

* Synergistic Effects of Silica‐Supported Iron‒Cobalt Catalysts for CO2 Reduction to Prebiotic Organics  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391926511
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Electrochemical Reduction of CO2 to Fuels, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301218")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391926511"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391926511"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391926511"))][Get cited by]]

OpenAlex: https://openalex.org/W4391926511 (Open access: True)
    
[[https://openalex.org/A5012991654][Kendra Solveig Belthle]], [[https://openalex.org/A5070827881][William Martin]], [[https://openalex.org/A5060841613][Harun Tüysüz]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301218  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cctc.202301218][pdf]])
     
To test the ability of geochemical surfaces in serpentinizing hydrothermal systems to catalyze reactions from which metabolism arose, we investigated H2‐dependent CO2 reduction toward metabolic intermediates over silica‐supported Co‒Fe catalysts. Supported catalysts converted CO2 to various products at 180 °C and 2.0 MPa. The liquid product phase included formate, acetate, and ethanol, while the gaseous product phase consisted of CH4, CO, methanol, and C2‒C7 linear hydrocarbons. The 1/1 ratio CoFe alloy with the same composition as the natural mineral wairauite yielded the highest concentrations of formate (6.0 mM) and acetate (0.8 mM), which are key intermediates in the acetyl‐coenzyme A (acetyl‐CoA) pathway of CO2 fixation. While Co‐rich catalysts were proficient at hydrogenation, yielding mostly CH4, Fe‐rich catalysts favored the formation of CO and methanol. Mechanistic studies indicated intermediate hydrogenation and C‒C coupling activities of alloyed CoFe, in contrast to physical mixtures of both metals. Co in the active site of Co‒Fe catalysts performed a similar reaction as tetrapyrrole‐coordinated Co in the corrinoid iron‐sulfur (CoFeS) methyl transferase in the acetyl‐CoA pathway. In a temperature range characteristic for deeper regions of serpentinizing systems, oxygenate product formation was favored at lower, more biocompatible temperatures.    

    

* Low‐coordination Nanocrystalline Copper‐based Catalysts through Theory‐guided Electrochemical Restructuring for Selective CO2 Reduction to Ethylene  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391944406
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202319936")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391944406"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391944406"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391944406"))][Get cited by]]

OpenAlex: https://openalex.org/W4391944406 (Open access: False)
    
[[https://openalex.org/A5019889972][Wensheng Fang]], [[https://openalex.org/A5065513785][Ruihu Lu]], [[https://openalex.org/A5035315138][Fu-Min Li]], [[https://openalex.org/A5088222762][Dan Wu]], [[https://openalex.org/A5061211337][Kaihang Yue]], [[https://openalex.org/A5001763605][Cong He]], [[https://openalex.org/A5029786087][Yu Mao]], [[https://openalex.org/A5019671436][Wei Guo]], [[https://openalex.org/A5017108318][Bao Yu Xia]], [[https://openalex.org/A5068295637][Fei Song]], [[https://openalex.org/A5073368369][Takeshi Yao]], [[https://openalex.org/A5005239842][Ziyun Wang]], [[https://openalex.org/A5017108318][Bao Yu Xia]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202319936 
     
Revealing the dynamic reconstruction process and tailoring advanced copper (Cu) catalysts is of paramount significance for promoting the conversion of CO2 into ethylene (C2H4), paving the way for carbon neutralization and facilitating renewable energy storage. In this study, we initially employed density functional theory (DFT) and molecular dynamics (MD) simulations to elucidate the restructuring behavior of a catalyst under electrochemical conditions and delineated its restructuring patterns. Leveraging insights into this restructuring behavior, we devised an efficient, low‐coordination copper‐based catalyst. The resulting synthesized catalyst demonstrated an impressive Faradaic efficiency (FE) exceeding 70% for ethylene generation at a current density of 800 mA cm‐2. Furthermore, it showed robust stability, maintaining consistent performance for 230 hours at a cell voltage of 3.5 V in a full‐cell system. Our research not only deepens the understanding of the active sites involved in designing efficient carbon dioxide reduction reaction (CO2RR) catalysts but also advances CO2 electrolysis technologies for industrial application.    

    

* Low‐coordination Nanocrystalline Copper‐based Catalysts through Theory‐guided Electrochemical Restructuring for Selective CO2 Reduction to Ethylene  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391926647
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202319936")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391926647"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391926647"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391926647"))][Get cited by]]

OpenAlex: https://openalex.org/W4391926647 (Open access: False)
    
[[https://openalex.org/A5019889972][Wensheng Fang]], [[https://openalex.org/A5065513785][Ruihu Lu]], [[https://openalex.org/A5035315138][Fu-Min Li]], [[https://openalex.org/A5088222762][Dan Wu]], [[https://openalex.org/A5061211337][Kaihang Yue]], [[https://openalex.org/A5001763605][Cong He]], [[https://openalex.org/A5029786087][Yu Mao]], [[https://openalex.org/A5019671436][Wei Guo]], [[https://openalex.org/A5017108318][Bao Yu Xia]], [[https://openalex.org/A5068295637][Fei Song]], [[https://openalex.org/A5073368369][Takeshi Yao]], [[https://openalex.org/A5005239842][Ziyun Wang]], [[https://openalex.org/A5017108318][Bao Yu Xia]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202319936 
     
Revealing the dynamic reconstruction process and tailoring advanced copper (Cu) catalysts is of paramount significance for promoting the conversion of CO2 into ethylene (C2H4), paving the way for carbon neutralization and facilitating renewable energy storage. In this study, we initially employed density functional theory (DFT) and molecular dynamics (MD) simulations to elucidate the restructuring behavior of a catalyst under electrochemical conditions and delineated its restructuring patterns. Leveraging insights into this restructuring behavior, we devised an efficient, low‐coordination copper‐based catalyst. The resulting synthesized catalyst demonstrated an impressive Faradaic efficiency (FE) exceeding 70% for ethylene generation at a current density of 800 mA cm‐2. Furthermore, it showed robust stability, maintaining consistent performance for 230 hours at a cell voltage of 3.5 V in a full‐cell system. Our research not only deepens the understanding of the active sites involved in designing efficient carbon dioxide reduction reaction (CO2RR) catalysts but also advances CO2 electrolysis technologies for industrial application.    

    

* A robust and high performance copper silicide catalyst for electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391935036
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ma00633f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391935036"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391935036"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391935036"))][Get cited by]]

OpenAlex: https://openalex.org/W4391935036 (Open access: True)
    
[[https://openalex.org/A5082383640][Vladislav Dřı́nek]], [[https://openalex.org/A5033924676][Pavel Dytrych]], [[https://openalex.org/A5018594029][Radek Fajgаr]], [[https://openalex.org/A5073746337][Mariana Klementová]], [[https://openalex.org/A5059685777][Jaroslav Kupčı́k]], [[https://openalex.org/A5058622627][Jaromı́r Kopeček]], [[https://openalex.org/A5042897885][Petr Svora]], [[https://openalex.org/A5032589036][Martin Koštejn]], [[https://openalex.org/A5020669335][Věra Jandová]], [[https://openalex.org/A5000921563][Karel Soukup]], [[https://openalex.org/A5024676203][Radim Beránek]], Materials advances. None(None)] 2024. https://doi.org/10.1039/d3ma00633f  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ma/d3ma00633f][pdf]])
     
A copper-based catalyst CuxSi (3<x<5) was prepared using chemical vapor deposition (CVD) of butylsilane (BuSiH3) on copper substrates. By varying the precursor flow...    

    

* Engineering stable Cu+-Cu0 sites and oxygen defects in boron-doped copper oxide for electrocatalytic reduction of CO2 to C2+ products  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391848551
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149710")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391848551"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391848551"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391848551"))][Get cited by]]

OpenAlex: https://openalex.org/W4391848551 (Open access: False)
    
[[https://openalex.org/A5065234959][Charles Q. Yang]], [[https://openalex.org/A5022110710][Ruichen Wang]], [[https://openalex.org/A5073326341][Yu Chen]], [[https://openalex.org/A5067760587][Jinhua Xiao]], [[https://openalex.org/A5070233080][Zhiwei Huang]], [[https://openalex.org/A5070144022][Bihong Lv]], [[https://openalex.org/A5035684534][Huawang Zhao]], [[https://openalex.org/A5051976562][Xiaomin Wu]], [[https://openalex.org/A5039243487][Guohua Jing]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149710 
     
Cu-based catalysts inevitably undergo surface reconstruction during the electrochemical carbon dioxide reduction reaction (CO2RR) process. Thus, it is a challenge to construct stable Cu+-Cu0 sites of Cu-based catalysts. In this study, we report a simple and facile engineering strategy for stable Cu+-Cu0 sites and oxygen defects derived from the boron-doped copper oxide (B-CuxO) as an efficient CO2RR electrocatalyst. The 5 % B-CuxO exhibited 48.32 % C2+ products Faraday efficiency (FE) for 12 h at −1.0 V vs reversible hydrogen electrode (RHE) in H-cell, which was far superior to CuxO (23.78 %). Combining density functional theory (DFT) and in situ Attenuated Total Reflection Fourier Transform Infrared spectroscopy (in situ ATR-FTIR), a higher electronic depletion on the catalyst surface inhibited the electrons accumulation around Cu sites, thereby maintaining the positive charge and inhibiting the complete reduction of Cu+. Moreover, the high oxygen defects in 5 % B-CuxO could effectively activate CO2 into *CO. We emphasized that Cu+ functioned as the primary active site by facilitating adsorption and dimerization of *CO, whereas Cu0 assisted in optimizing CO2 activation.    

    

* Reduction of CO2 in the Presence of Light via Excited-state Hydride Transfer Reaction in a NADPH-inspired Derivative  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4392006911
:TOPICS: Perovskite Solar Cell Technology, Electrochemical Reduction of CO2 to Fuels, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cp05635j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392006911"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392006911"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392006911"))][Get cited by]]

OpenAlex: https://openalex.org/W4392006911 (Open access: False)
    
[[https://openalex.org/A5068757149][Bojana Ostojić]], [[https://openalex.org/A5006146774][Branislav Stanković]], [[https://openalex.org/A5026875974][Dragana Đorđević]], [[https://openalex.org/A5071867820][Peter Schwerdtfeger]], Physical Chemistry Chemical Physics. None(None)] 2024. https://doi.org/10.1039/d3cp05635j 
     
The photo-catalytic reduction of CO2 into chemical feedstocks using solar energy has attracted vast interest in environmental science because of global warming. Based on our previous study on the CO2...    

    

* Artificial Intelligence Vision Technology Application of Automatic Steam&Heat Flow Detection Integrated with Carbon Dioxide Reduction and Brackish Water Treatment: A Sustainable Environmental Merit of Carbon Neutrality Through Solar-Driven Distillation Device  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391851772
:TOPICS: Application of Diagnostic Techniques in Oil Wells, Real-time Water Quality Monitoring and Aquaculture Management
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4727259")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391851772"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391851772"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391851772"))][Get cited by]]

OpenAlex: https://openalex.org/W4391851772 (Open access: False)
    
[[https://openalex.org/A5074199759][Shibiao Fang]], [[https://openalex.org/A5059262581][Wenrong Tu]], [[https://openalex.org/A5074319004][Wei Lu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4727259 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Pre-treatment through reductive calcination for CO2 mineralization and selective battery metal extraction from laterites  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391980124
:TOPICS: Carbon Dioxide Sequestration in Geological Formations, Geothermal Energy Technology and Applications, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.126818")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391980124"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391980124"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391980124"))][Get cited by]]

OpenAlex: https://openalex.org/W4391980124 (Open access: False)
    
[[https://openalex.org/A5043270526][Fei Wang]], [[https://openalex.org/A5058125991][David Dreisinger]], [[https://openalex.org/A5048334909][Yuchang Xiao]], Separation and Purification Technology. 340(None)] 2024. https://doi.org/10.1016/j.seppur.2024.126818 
     
The world needs an increasing supply of nickel and cobalt production as battery materials for sustainable development. However, the complexity of laterite deposits and the need to control CO2 emissions challenge the enhanced global supply from laterites. This work investigates the effects of calcination as a pre-treatment for selective battery metal extraction from both limonite laterite and saprolite laterite together with concurrent achievement of CO2 mineralization. Calcination under a reducing atmosphere of CO-N2 or CO-CO2 gas mixtures can significantly enhance the extraction of critical metals from both limonite and saprolite laterites. With calcination, the hydrated silicate minerals and ferric oxides converted to reactive olivine and ferrous oxide. The calcines thus can participate in the CO2 mineralization process to stabilize CO2 as mineral carbonates and release nickel and cobalt arising from the CO2 mineral carbonation into solution as complex ions with a ligand (such as sodium nitrilotriacetate, NTA). The optimum calcination conditions are 20 ∼ 30 % CO in CO-CO2 gas mixture at 700 °C. Beyond the optimum range results in the inadequate conversion of ferric to ferrous at too low CO concentration or over calcination of ferric to metallic iron at too high CO concentration. At the optimum conditions, the nickel & cobalt extraction and CO2 mineralization can reach 90 %, 93 %, and 39 % from laterite. Each tonne saprolite with the pre-treatment of calcination can recover 20.5 kg nickel, 0.59 kg cobalt, and simultaneously sequester 142 kg CO2 as stable mineral carbonates. The pre-treatment through slightly reductive calcination enables the robust suitability of the developed process for all layers of laterites for both critical battery metal recovery and carbon mineralization.    

    

* Three-dimensional N-doped carbon nanosheets loading heterostructured Ni/Ni3ZnC0.7 nanoparticles for Selective and Efficient CO2 Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391934877
:TOPICS: Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3nr05771b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391934877"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391934877"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391934877"))][Get cited by]]

OpenAlex: https://openalex.org/W4391934877 (Open access: False)
    
[[https://openalex.org/A5028858881][Li Liao]], [[https://openalex.org/A5070950860][Chunguang Jia]], [[https://openalex.org/A5087838064][She‐Huang Wu]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5080926762][Zhenhai Wen]], [[https://openalex.org/A5091534599][Suqin Ci]], Nanoscale. None(None)] 2024. https://doi.org/10.1039/d3nr05771b 
     
Electrocatalytic CO2 reduction (CO2RR) has emerged as a promising approach for converting CO2 into valuable chemicals and fuels to achieve a sustainable carbon cycle. However, the development of efficient electrocatalysts...    

    
