#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Tue Oct  1 01:27:13 2024

Found 29 results from 2024-09-24 to 2024-10-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Applications of metal nanoclusters supported by two-dimensional material graphene in electrocatalytic carbon dioxide reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402784535
:TOPICS: Catalytic Nanomaterials, Graphene: Properties, Synthesis, and Applications, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cp03161j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402784535"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402784535"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402784535"))][Get cited by]]

OpenAlex: https://openalex.org/W4402784535 (Open access: False)
    
[[https://openalex.org/A5101672167][Shanlin Chen]], [[https://openalex.org/A5101150302][Haiyan Zhu]], [[https://openalex.org/A5100416450][Tingting Li]], [[https://openalex.org/A5100442336][Ping Liu]], [[https://openalex.org/A5100803131][Chou Wu]], [[https://openalex.org/A5101200034][Shaobo Jia]], [[https://openalex.org/A5100392071][Wei Wang]], [[https://openalex.org/A5008133679][Bingbing Suo]], Physical Chemistry Chemical Physics. None(None)] 2024. https://doi.org/10.1039/d4cp03161j 
     
Metal nanoclusters (MNCs) have been demonstrated to exhibit superior catalytic performance compared to single nanoparticles. This is attributed to their quantized electronic structure, unique geometrical stacking and abundant active sites....    

    

* Heterometallic Transition Metal Oxides Containing Lewis Acids as Molecular Catalysts for the Reduction of Carbon Dioxide to Carbon Monoxide with Bimodal Activity  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402857418
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c10412")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402857418"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402857418"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402857418"))][Get cited by]]

OpenAlex: https://openalex.org/W4402857418 (Open access: True)
    
[[https://openalex.org/A5029669152][Dima Azaiza‐Dabbah]], [[https://openalex.org/A5061595404][Fei Wang]], [[https://openalex.org/A5105520601][E. Sideras Haddad]], [[https://openalex.org/A5086372340][Albert Solé‐Daura]], [[https://openalex.org/A5082386529][Raanan Carmieli]], [[https://openalex.org/A5006581201][Josep M. Poblet]], [[https://openalex.org/A5080469156][Charlotte Vogt]], [[https://openalex.org/A5034097419][Ronny Neumann]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c10412 
     
Electrocatalytic CO    

    

* Review for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934411
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934411"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934411"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934411"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934411 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v1/review2 
     
No abstract    

    

* Decision letter for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935014
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-04-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935014"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935014"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935014"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935014 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v2/decision1 
     
No abstract    

    

* Review for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934444
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934444"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934444"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934444"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934444 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v1/review1 
     
No abstract    

    

* Decision letter for "Accelerated screening of gas diffusion electrodes for carbon dioxide reduction"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402934858
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-04-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dd00061g/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402934858"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402934858"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402934858"))][Get cited by]]

OpenAlex: https://openalex.org/W4402934858 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4dd00061g/v1/decision1 
     
No abstract    

    

* Solar Power and Demand Response for Greening Indian Lignite Power Plants: A CO2 Reduction Initiative  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402831005
:TOPICS: Integration of Renewable Energy Systems in Power Grids, Global Energy Transition and Fossil Fuel Depletion, Energy Transition and Renewable Resources Integration
:PUBLICATION_DATE: 2024-09-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.4025/actascitechnol.v46i1.69511")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402831005"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402831005"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402831005"))][Get cited by]]

OpenAlex: https://openalex.org/W4402831005 (Open access: True)
    
[[https://openalex.org/A5069317752][Vivek Saxena]], [[https://openalex.org/A5053124619][Saurabh Kumar Rajput]], Acta Scientiarum. Technology/Acta scientiarum. Technology. 46(1)] 2024. https://doi.org/10.4025/actascitechnol.v46i1.69511 
     
This research paper delves into the prospect of curbing carbon dioxide (CO2) emissions by strategically deploying solar photovoltaic (PV) systems and orchestrating demand response (DR) mechanisms within Indian lignite power plants (LPP). The study responds to the critical imperative of mitigating greenhouse gas (GHG) emissions originating from coal-based electricity generation, a matter of substantial consequence in the context of climate change. In pursuit of optimal solar PV system allocation, this research employs the particle swarm optimization (PSO) technique, considering a spectrum of factors including solar resource availability, electricity demand patterns, and the CO2 intensity associated with coal power generation. The primary objective is to minimize CO2 emissions while maximizing the integration of solar PV and curtailing power losses, all while accounting for the intermittent nature of solar power and the dynamic nature of demand. The proposed approach is rigorously tested on the IEEE 33 bus system, supplied by the LPP. The results convincingly demonstrate a remarkable reduction in CO2 emissions, amounting to 29.69%, following the implementation of the proposed approach. This research presents a concrete step towards a more sustainable and environmentally friendly energy landscape, offering valuable insights for policymakers and stakeholders in the energy sector.    

    

* High-Quality Foaming and Weight Reduction in Microcellular-Injection-Molded Polycarbonate Using Supercritical Fluid Carbon Dioxide under Gas Counter Pressure  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402750890
:TOPICS: Polymer Foaming with Supercritical Carbon Dioxide, Biodegradable Polymers as Biomaterials and Packaging, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/polym16182674")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402750890"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402750890"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402750890"))][Get cited by]]

OpenAlex: https://openalex.org/W4402750890 (Open access: True)
    
[[https://openalex.org/A5107474898][Yogi Hendra Agustion]], [[https://openalex.org/A5064437160][Shia‐Chung Chen]], [[https://openalex.org/A5026358703][Ching-Te Feng]], [[https://openalex.org/A5000720941][Bermawi P. Iskandar]], Polymers. 16(18)] 2024. https://doi.org/10.3390/polym16182674 
     
Microcellular injection molding (MuCell    

    

* The Electrode/Electrolyte Interface Study during the Electrochemical CO2 Reduction in Acidic Electrolytes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402935861
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202415894")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402935861"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402935861"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402935861"))][Get cited by]]

OpenAlex: https://openalex.org/W4402935861 (Open access: False)
    
[[https://openalex.org/A5081466371][Yao Yao]], [[https://openalex.org/A5078369945][Ernest Pahuyo Delmo]], [[https://openalex.org/A5005645517][Minhua Shao]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202415894 
     
Electrochemical CO2 Reduction (CO2R) in acidic electrolytes has gained significant attention owing to higher carbon efficiency and stability than in alkaline counterparts. However, the proton source and the role of alkali cations for CO2R are still under debate. By using rotating ring disk electrode and surface‐enhanced infrared absorption spectroscopy, we find that a neutral/alkaline environment at the interface is necessary for CO2R even in acidic electrolytes. We also confirm that water molecules, rather than protons serve as the proton source for CO2R. Alkali cations in the outer Helmholtz plane activate H2O and promote the desorption of adsorbed carbon monoxide. Additionally, the solvated CO2, or CO2(aq), is the actual reactant for CO2R. This study provides a deeper understanding of the electrode/electrolyte interface during CO2R in acidic electrolytes and sheds light on further performance improvement of this system.    

    

* Coupling pretreatment of lignocellulosic biomass for enzymatic hydrolysis with electrochemical reduction of CO2 for production of formic acid  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402837549
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.gce.2024.09.008")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402837549"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402837549"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402837549"))][Get cited by]]

OpenAlex: https://openalex.org/W4402837549 (Open access: True)
    
[[https://openalex.org/A5075320040][Jiashuai Liu]], [[https://openalex.org/A5012184772][Fangqian Wang]], [[https://openalex.org/A5046576031][Yongrong Li]], [[https://openalex.org/A5013713303][Xuebing Zhao]], Green Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.gce.2024.09.008 
     
No abstract    

    

* Water-induced Switching in Selectivity and Steric Control of Activity in Photochemical CO2 Reduction Catalyzed by RhCp*(bpy) Derivatives  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402852228
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-t3ltd-v3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402852228"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402852228"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402852228"))][Get cited by]]

OpenAlex: https://openalex.org/W4402852228 (Open access: False)
    
[[https://openalex.org/A5063894173][Dongseb Lee]], [[https://openalex.org/A5039693008][Kosei Yamauchi]], [[https://openalex.org/A5066627191][Ken Sakai]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-t3ltd-v3 
     
Photocatalytic reduction of CO2 to formic acid (HCOOH) was investigated in either organic or aqueous/organic media by employing three water-soluble [RhIIICp*(LH2)Cl]+ (LH2 = n,n’-dihydroxy-2,2’-bipyridine; n = 4, 5, or 6) in the presence of [Ru(bpy)3]2+, 1,3-dimethyl-2-phenyl-2,3-dihydro-1H-benzo[d]imidazole (BIH) and triethanolamine (TEOA). Through studying the electron-donating effects of two hydroxyl groups introduced to the bipyridyl ligand, we found that the substituent positions greatly affect both the catalytic efficiency and selectivity in CO2 reduction. More importantly, the HCOOH selectivity shows a dramatic increase from 14% to 83% upon switching the solvent media from pure organic to aqueous/organic mixture, where the H2 selectivity shows a reverse phenomenon. The enhanced HCOOH selectivity and the drastic decrease in the H2 yield are well rationalized by the fact that the catalytic CO2 hydrogenation is not only driven photochemically via the attack of RhIII(H)Cp*(LH2-•) on CO2 but also partly bypassed by a dark H2 addition reaction yielding [RhIII(H)Cp*(L)]- from [RhIIICp*(L)Cl]+, which was also separately investigated under the dark conditions. Combination of experimental and theoretical approaches were made to clarify the pKa values of catalyst intermediates together with the abundant species responsible for the major catalytic processes. Our DFT studies unveil that the exceptionally large structural strain given by the steric contacts between the 6,6’-dihydroxyl groups and the Cp* moiety plays a significant role in bringing about an outstanding catalytic performance of the 6,6’-subsituted derivative. The intrinsic reaction coordinate calculations were carried out to clarify the mechanism of hydride transfer steps leading to generate formate together the heterolytic H2 cleavage steps leading to afford the key hydridorhodium intermediates. This study represents the first report on the water-induced high selectivity in CO2-to-HCOOH conversion, shedding a new light on the strategy to control the efficiency and selectivity in the catalysis of CO2 reduction.    

    

* Optimizing CO2 Photoreduction Through Metal-Organic Frameworks: The Impact of Metal Selection and Composite Structures  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402851762
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.70251/hyjr2348.235560")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402851762"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402851762"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402851762"))][Get cited by]]

OpenAlex: https://openalex.org/W4402851762 (Open access: False)
    
[[https://openalex.org/A5065333843][Baoru Sun]], [[https://openalex.org/A5009395657][Ke Xie]], No host. None(None)] 2024. https://doi.org/10.70251/hyjr2348.235560 
     
The rising atmospheric carbon dioxide (CO2) concentration poses significant environmental challenges, including global warming and associated climate change. Metal-organic frameworks (MOFs) have emerged as promising materials for addressing and mitigating CO2 levels due to their high surface area, tunable pore sizes, and customizable metal nodes. This review focuses on the influence of metal selection and MOF composites on the efficiency and stability of MOFs in CO2 photoreduction reactions. The findings underscore the potential of MOF-based catalysts in developing sustainable solutions for CO2 reduction, offering a pathway to mitigate environmental impacts while advancing renewable energy technologies.    

    

* Pengaruh Modifikasi Permukaan Piston terhadap Emisi Gas Buang Motor Bakar Kapasitas 100 cc  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402788974
:TOPICS: Principles of Production Management and Operations
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.55606/jtmei.v3i3.4108")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402788974"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402788974"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402788974"))][Get cited by]]

OpenAlex: https://openalex.org/W4402788974 (Open access: False)
    
[[https://openalex.org/A5107476802][Gennarki Dini Setyawan Putra]], [[https://openalex.org/A5021716770][Khambali Khambali]], JURNAL TEKNIK MESIN INDUSTRI ELEKTRO DAN INFORMATIKA. 3(3)] 2024. https://doi.org/10.55606/jtmei.v3i3.4108 
     
Technological advances in motorized transportation are progressing rapidly, making motorized vehicles the main mode of transportation. The increasing number of motorized vehicles in society results in a significant increase in exhaust emissions. Combustion in vehicle engines is not always perfect, producing exhaust gases containing compounds harmful to human health, such as carbon monoxide (CO), hydrocarbons (HC), carbon dioxide (CO2), and nitrogen oxides (NOx). This study investigates the effect of variations in piston dome shape on exhaust emissions in a 100cc internal combustion engine using RON 90 fuel. The goal is to find the optimal compression ratio to produce cleaner exhaust emissions. The research data are presented in tabular form and analyzed using one-way ANOVA and graphs. The results showed a significant reduction in CO and HC emissions at all engine speeds (1000, 2000, 4000, and 5000 rpm) with variations in piston dome shape. The reduction in CO emissions ranged from 55.07% to 85.73%, while the reduction in HC emissions ranged from 54.14% to 86.10%. These results suggest that variations in piston dome shape can be an effective solution to minimize harmful exhaust emissions in internal combustion engines.    

    

* The Geochemical imaging Technique for CO2 Monitoring in the Saline Aquifer of Krechba Field Algeria  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402752359
:TOPICS: Carbon Dioxide Sequestration in Geological Formations, Characterization of Shale Gas Pore Structure, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-5122014/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402752359"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402752359"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402752359"))][Get cited by]]

OpenAlex: https://openalex.org/W4402752359 (Open access: False)
    
[[https://openalex.org/A5009394185][Zeboudj Fayçal]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-5122014/v1 
     
Abstract As part of the reduction and elimination of anthropogenic emissions, carbon capture, and storage (CCS) has been applied in recent decades. One option for reducing greenhouse gas emissions GHG is to store carbon dioxide CO2 in deep saline aquifers. Due to their abundance and large capacity, deep saline aquifers make excellent storage sites due to their potential for long-term sequestration. In early 2006, in Salah Gas Krechba field in Algeria became the world's first onshore saline aquifer to begin sequestration. This paper will focus on new insights into surface CO2 monitoring. We will discuss the introduction of geochemical imaging as an emerging surface technique to monitor CO2, recently adopted to investigate and detect tracer gases leaks injected in 2007 from neighboring wells and the cap rock. In the following few pages, we will summarize the geochemical imaging survey process from the implementation design, samples signature measurement to chemical analysis using the sophisticated statistical geo-chemical methods in the final interpretation stage. As a conclusion, the comprehensive analysis of the geochemical data has allowed the Krechba team to investigate the CO2 leakage areas in the field and demonstrates to be an efficient valuable, and accurate method for CO2 monitoring    

    

* The Impact of Economic Factors on Changing Carbon Emission Landscape in ASEAN With ARDL Approach  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402849537
:TOPICS: Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.24002/kinerja.v28i2.8583")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402849537"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402849537"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402849537"))][Get cited by]]

OpenAlex: https://openalex.org/W4402849537 (Open access: True)
    
[[https://openalex.org/A5003264851][Hasbi Hasbi]], KINERJA. 28(2)] 2024. https://doi.org/10.24002/kinerja.v28i2.8583 
     
This study aims to analyze the factors influencing carbon emissions in the member countries of the Association of Southeast Asian Nations (ASEAN). The data used in this study covers the period from 1990 to 2021, utilizing the Autoregressive Distributed Lag (ARDL) analysis method. All independent variables show a significant impact on carbon emissions in both the short and long term. This research provides evidence that factors such as urbanization, foreign direct investment, population, and economic growth significantly contribute to the increase in carbon emissions in ASEAN countries. The findings also validate the Environmental Kuznets Curve hypothesis for carbon emissions in ASEAN countries. In other words, economic growth leads to a reduction in carbon emissions. The ASEAN region has experienced substantial economic growth over the past few decades. However, carbon dioxide (CO2) remains a socio-economic issue in the ASEAN region. The results of this study can be highly beneficial for policymakers in the region regarding sustainability and economic development.    

    

* Ni–Doped Pr0.7Ba0.3MnO3−δ Cathodes for Enhancing Electrolysis of CO2 in Solid Oxide Electrolytic Cells  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402768298
:TOPICS: Solid Oxide Fuel Cells, Electrochemical Reduction of CO2 to Fuels, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29184492")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402768298"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402768298"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402768298"))][Get cited by]]

OpenAlex: https://openalex.org/W4402768298 (Open access: True)
    
[[https://openalex.org/A5022915696][Fei Shan]], [[https://openalex.org/A5100357815][Tao Chen]], [[https://openalex.org/A5016445881][Kui Xie]], [[https://openalex.org/A5016445881][Kui Xie]], Molecules. 29(18)] 2024. https://doi.org/10.3390/molecules29184492 
     
Solid Oxide Electrolysis Cells (SOECs) can electro-reduce carbon dioxide to carbon monoxide, which not only effectively utilizes greenhouse gases, but also converts excess electrical energy into chemical energy. Perovskite-based oxides with exsolved metal nanoparticles are promising cathode materials for direct electrocatalytic reduction of CO2 through SOECs, and have thus received increasing attention. In this work, we doped Pr0.7Ba0.3MnO3−δ at the B site, and after reduction treatment, metal nanoparticles exsolved and precipitated on the surface of the cathode material, thereby establishing a stable metal–oxide interface structure and significantly improving the electrocatalytic activity of the SOEC cathode materials. Through research, among the Pr0.7Ba0.3Mn1−xNixO3−δ (PBMNx = 0–1) cathode materials, it has been found that the Pr0.7Ba0.3Mn0.9Ni0.1O3−δ (PBMN0.1) electrode material exhibits greater catalytic activity, with a CO yield of 5.36 mL min−1 cm−2 and a Faraday current efficiency of ~99%. After 100 h of long-term testing, the current can still remain stable and there is no significant change in performance. Therefore, the design of this interface has increasing potential for development.    

    

* Smarter and Cleaner? The Carbon Reduction Effect of Smart Cities: A Perspective on Green Technology Progress  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402784349
:TOPICS: Smart Cities: Innovations and Challenges, Understanding Human Mobility Patterns, Impact of Nighttime Light Data on Various Fields
:PUBLICATION_DATE: 2024-09-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16188048")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402784349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402784349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402784349"))][Get cited by]]

OpenAlex: https://openalex.org/W4402784349 (Open access: True)
    
[[https://openalex.org/A5065987736][Xianjuan An]], [[https://openalex.org/A5101705569][Yanjing Yang]], [[https://openalex.org/A5092352057][Xinyu Zhang]], [[https://openalex.org/A5100685076][Xueting Zeng]], Sustainability. 16(18)] 2024. https://doi.org/10.3390/su16188048 
     
In the context of the global climate change problem intensifying due to a dramatic increase in carbon emissions, smart cities, as a topical application of digitalization and intelligence, have become a new urban governance mode for countries, which helps to achieve sustainable development. This research studies the relationship between smart city construction (SCC) and carbon dioxide emissions based on the differences-in-differences model (DID) and propensity score matching (PSM) to promote China to achieve dual carbon goals and high-quality development. The findings are as follows: (a) SCC could promote carbon emission reduction by reducing urban carbon dioxide emissions by an average of 11.4%, which also has significant long-term dynamic effects. Specifically, SCC has more obvious emission reduction effects on activities, such as industrial production and waste treatment. (b) Mechanism verification shows that green technology progress is a significant booster for the carbon reduction effect in SCC. The pilot project can increase output of green patents, which helps transfer production mode and consumption patterns in an environmentally friendly manner. SCC could increase the total factor productivity (TFP) through the rational allocation and efficient use of resources, and thus reducing carbon emissions. (c) Research on city heterogeneity shows that a high level of human capital, material, and financial resources can provide support for smart cities to better achieve the carbon reduction effect. Among them, material resources have the best carbon reduction effect in the process of SCC, which could reduce carbon dioxide emissions by about 6.6–17.7%. This study is useful for policymakers to continuously and dynamically adjust urban development strategies in the future, to achieve a balance between socioeconomic prosperity and environmental sustainability.    

    

* Spatial-temporal differences and convergence analysis of residential building carbon emission efficiency in China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402917681
:TOPICS: Economic Impact of Environmental Policies and Resources, Life Cycle Assessment and Environmental Impact Analysis, Efficiency Analysis in Production and Resource Allocation
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1371/journal.pone.0311097")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402917681"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402917681"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402917681"))][Get cited by]]

OpenAlex: https://openalex.org/W4402917681 (Open access: True)
    
[[https://openalex.org/A5023691587][Yong-Kun Wang]], [[https://openalex.org/A5107516074][Na Lu]], [[https://openalex.org/A5100417669][Yan Wang]], PLoS ONE. 19(9)] 2024. https://doi.org/10.1371/journal.pone.0311097 
     
Data indicate that carbon dioxide emissions from residential buildings in China constitute 60% of the country’s total, making carbon reduction efforts in residential construction crucial for achieving dual carbon goals. From the perspective of eight major economic regions, this paper selects energy consumption, per capita residential area, and residential population as input indicators, per capita disposable income as the output indicator, and carbon dioxide emissions as the undesired output indicator. It employs the super-efficiency model based on the directional distance (super-DDF) function and the Malmquist-Luenberger (ML) index to measure the static and dynamic carbon emission efficiencies of residential buildings (RBCEE) during their operational phase from 2010 to 2020. After analyzing the differences and equity in RBCEE among regions using the Theil index and Gini coefficient, the σ-convergence, absolute β-convergence, and conditional β-convergence methods are utilized to explore the changing trends of RBCEE across the eight major economic regions. Results show that the static RBCEE in China is at a medium level; dynamic efficiency has improved across all eight regions, though at varying rates; overall, RBCEE exhibits poor equity and significant differences, with intra-group differences being a major cause. In terms of convergence, all eight economic regions display significant absolute β-convergence and conditional β-convergence. Finally, based on the research findings, this paper proposes corresponding emission reduction recommendations for the eight major economic regions.    

    

* Emerging Technologies for Decarbonizing Silicon Production  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402759978
:TOPICS: Electrochemical Reduction in Molten Salts, Battery Recycling and Rare Earth Recovery, Reduction Kinetics in Ironmaking Processes
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40831-024-00913-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402759978"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402759978"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402759978"))][Get cited by]]

OpenAlex: https://openalex.org/W4402759978 (Open access: True)
    
[[https://openalex.org/A5023886667][Haley Hoover]], [[https://openalex.org/A5062451704][Robert B. Bell]], [[https://openalex.org/A5107475280][Kerry Rippy]], Journal of Sustainable Metallurgy. None(None)] 2024. https://doi.org/10.1007/s40831-024-00913-3 
     
Abstract Silicon (Si) is an important material for alloying, solar photovoltaics, and electronics. However, current methods of producing silicon require energy consumption of around 11–13 kWh/kg Si and direct carbon emissions are 4.7–5 tons CO 2 per ton Si which conflicts with global efforts to limit climate change. In this work, we discuss several promising methods for reducing or eliminating carbon emissions from the silicon production process. Such methods include using biocarbon, integrating the current process with carbon capture and utilization/storage (CCU/CCS), metallothermic reduction, hydrogen reduction, and molten salt electrolysis. We present the positive aspects and challenges of each approach. Biocarbon coupled with CCU/CCS is the most industrially mature technology and can be carbon–neutral or -negative but is not carbon-free. Hydrogen directly reducing silicon dioxide is not thermodynamically favorable, but it may be viable to use hydrogen in conjunction with other processes to reduce emissions. Metallothermic and electrochemical methods of production are promising and have the potential to create high-purity silicon with no reduction-related carbon emissions but have only been demonstrated at lab scale. Economic viability will likely be the next determining factor for which technologies are more widely researched and implemented. Graphical Abstract    

    

* METHOD FOR PREDICTING THE TECHNICAL CONDITION OF GAS WELL TUBING WITH CORRECTION BASED ON IN-LINE DIAGNOSTICS INFORMATION  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402773584
:TOPICS: Materials Engineering in Industrial Applications, Drilling Fluid Technology and Well Integrity, Technological Development in Mineral Resource Sector
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.14489/td.2024.08.pp.028-034")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402773584"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402773584"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402773584"))][Get cited by]]

OpenAlex: https://openalex.org/W4402773584 (Open access: False)
    
[[https://openalex.org/A5039767551][A.N. Kitabov]], [[https://openalex.org/A5107547668][U. M. Abutalipov]], [[https://openalex.org/A5069862772][A. R. Buranshin]], [[https://openalex.org/A5013821379][А. В. Иванов]], Kontrol Diagnostika. None(314)] 2024. https://doi.org/10.14489/td.2024.08.pp.028-034 
     
The article presents a methodology for monitoring and predicting the technical condition of the suspension of pump-compressor pipes (tubing) of gas wells exposed to carbon dioxide corrosion. The tubing suspension as an object of control and diagnostics is considered, the main loads acting on the object in question are determined, as well as the expression for the equivalent value of the loads. An expression has been obtained for determining the permissible reduction in the tubing wall thickness, provided that the facility remains operational, as well as an expression for determining the total and residual life of the tubing hanger.A comparative analysis of the main methods for determining the corrosion rate of a diagnostic object was carried out, and the optimal method was selected. A method for correcting the results of calculating the corrosion rate using tubing wall thickness values obtained during in-line diagnostics is described.    

    

* Catalyzing green transformation: mitigating oil price impact on CO2 emissions in Saudi Arabia via renewable energy transition  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402782570
:TOPICS: Economic Impact of Environmental Policies and Resources, Rebound Effect on Energy Efficiency and Consumption, Global Energy Transition and Fossil Fuel Depletion
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10018-024-00416-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402782570"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402782570"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402782570"))][Get cited by]]

OpenAlex: https://openalex.org/W4402782570 (Open access: True)
    
[[https://openalex.org/A5019592819][Shahriyar Mukhtarov]], [[https://openalex.org/A5041857767][Mayis Azizov]], [[https://openalex.org/A5033481107][Mustafa Tevfik Kartal]], [[https://openalex.org/A5033969530][Hazi Eynalov]], Environmental Economics and Policy Studies. None(None)] 2024. https://doi.org/10.1007/s10018-024-00416-1 
     
Abstract Exploring the relationship between international oil prices, income, and carbon dioxide (CO 2 ) emissions in Saudi Arabia, this study examines if renewable energy consumption plays a lowering tool in international oil prices' impact on CO 2 emissions, employing conventional econometric methods and the functional coefficient approach. The study reveals that the interaction between renewable energy consumption and international oil prices has a negative and statistically significant impact on CO 2 emissions. This emphasizes the potential for Saudi Arabia to reduce carbon emissions by prioritizing renewable energy projects. In addition, a positive and statistically significant relationship between income and CO 2 emissions is found, emphasizing the need to decouple economic growth from emissions growth. Furthermore, an interesting decoupling effect between oil price elasticity of CO 2 emissions and per capita GDP is noted from the early 2000s–2015. This indicates that economic growth driven by rising oil prices can be managed to mitigate environmental impact, showcasing Saudi Arabia's commitment to sustainable development. Policy recommendations involve intensifying efforts to promote renewable energy implementation, lowering fossil fuel dependence in power generation, and incentivizing emissions reduction for a more sustainable energy future.    

    

* Effect of CO2 Concentration on the Performance of Polymer-Enhanced Foam at the Steam Front  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402868795
:TOPICS: Polymer Foaming with Supercritical Carbon Dioxide, Petroleum Chemistry and Analysis, Epoxy Resin Technology
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/polym16192726")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402868795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402868795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402868795"))][Get cited by]]

OpenAlex: https://openalex.org/W4402868795 (Open access: True)
    
[[https://openalex.org/A5103064863][Mingxuan Wu]], [[https://openalex.org/A5042731276][Binfei Li]], [[https://openalex.org/A5101224219][Liwei Ruan]], [[https://openalex.org/A5060048116][Chao Zhang]], [[https://openalex.org/A5037839739][Yongqiang Tang]], [[https://openalex.org/A5078319914][Zhaomin Li]], Polymers. 16(19)] 2024. https://doi.org/10.3390/polym16192726 
     
This study examines the impact of CO2 concentration on the stability and plugging performance of polymer-enhanced foam (PEF) under high-temperature and high-pressure conditions representative of the steam front in heavy oil reservoirs. Bulk foam experiments were conducted to analyze the foam performance, interfacial properties, and rheological behavior of CHSB surfactant and Z364 polymer in different CO2 and N2 gas environments. Additionally, core flooding experiments were performed to investigate the plugging performance of PEF in porous media and the factors influencing it. The results indicate that a reduction in CO2 concentration in the foam, due to the lower solubility of N2 in water and the reduced permeability of the liquid film, enhances foam stability and flow resistance in porous media. The addition of polymers was found to significantly improve the stability of the liquid film and the flow viscosity of the foam, particularly under high-temperature conditions, effectively mitigating the foam strength degradation caused by CO2 dissolution. However, at 200 °C, a notable decrease in foam stability and a sharp reduction in the resistance factor were observed. Overall, the study elucidates the effects of gas type, temperature, and polymer concentration on the flow and plugging performance of PEF in porous media, providing reference for fluid mobility control at the steam front in heavy oil recovery.    

    

* Using MCFC for capturing CO2 from flue gases and delivering to Sabatier reactor for SNG synthesis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402746605
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-09-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54966/jreen.v1i1.1250")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402746605"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402746605"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402746605"))][Get cited by]]

OpenAlex: https://openalex.org/W4402746605 (Open access: True)
    
[[https://openalex.org/A5039359091][J. Milewski]], [[https://openalex.org/A5090101529][Aliaksandr Martsinchyk]], Journal of Renewable Energies. None(None)] 2024. https://doi.org/10.54966/jreen.v1i1.1250 
     
In contemporary power generation, enhancing efficiency and mitigating environmental contamination are of paramount importance. The imperative to curtail greenhouse gas emissions stands as a preeminent challenge within this sector. Concurrently, there is a marked surge in the exploitation of renewable energy sources, which, due to their intermittent nature, precipitates the imperative for advanced energy storage solutions. This paper introduces an integrated system designed to address both the reduction of CO2 emissions and the storage of energy. The advocated system integrates a Molten Carbonate Fuel Cell (MCFC), Solid Oxide Electrolysis Cell (SOEC), and a Sabatier reactor. The MCFC is employed for its proficient CO2 capture capabilities at the cathode, exhibiting remarkable efficiency, operational flexibility, and a high CO2 separation quotient. The SOEC is recognized for its effective hydrogen production, leveraging high operational temperatures to augment hydrogen output while diminishing electrical energy consumption through thermal energy substitution. The Sabatier reactor is utilized for catalytic methanation, transforming CO2 into Substitute Natural Gas—a compound predominantly comprising methane and hydrogen with minimal CO2 and water traces. This system facilitates the capture and utilization of over 80% of CO2 from exhaust fumes, achieving an overall energy efficiency of 71%. The system's design and off-design operational parameters were meticulously modeled and analyzed.    

    

* High frequency monitoring of carbon (iv) oxide evolution from a tropical soil amended with organomineral fertilizer in a screenhouse Ile-Ife, Nigeria  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402793553
:TOPICS: Machine Learning for Mineral Prospectivity Mapping, Influence of Magnetic Fields on Biological Systems
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.31248/jasp2024.475")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402793553"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402793553"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402793553"))][Get cited by]]

OpenAlex: https://openalex.org/W4402793553 (Open access: True)
    
[[https://openalex.org/A5003165738][Fatai Oladapo Tijani]], [[https://openalex.org/A5106811239][A. S. Okunkenu]], [[https://openalex.org/A5028953201][F. Afolabi]], [[https://openalex.org/A5001290797][Bamikole Peter Akinde]], [[https://openalex.org/A5003403298][D. J. Oyedele]], Journal of Agricultural Science and Practice. 9(4)] 2024. https://doi.org/10.31248/jasp2024.475 
     
The study compared responses of carbon (iv) oxide evolved from an Ultisol sampled at different time scales and the soil properties when amended with organomineral fertilizer (OMF); thus tracking the carbon footprint of the amendment in ambient air. The carbon (iv) oxide efflux was measured titrimetrically in a static chamber set up in a screenhouse at sub-daily, daily and weekly time scales. At the same time, the antecedent soil properties were determined using standard methods. The treatments involved OMF addition at three rates (0 kg OMF, 40 kg Urea-N + 2.5 tons/ha organic fertilizer and 40 kg Urea-N + 5 tons/ha organic fertilizer) based on some Nigerian indigenous vegetable nutrient requirements. The result showed that a more detailed and accurate understanding of CO2 evolution processes was revealed at daily sampling resolution while sub-daily variation occurred in response to sub-daily variation in ambient temperature. Organomineral fertilizer at 40 kg/ha Urea + 2.5 tons/ha OF rate was comparatively safer in C management through the reduction in the CO2 released thus constituting a better alternative in terms of the greenhouse effect. Thus, the study recommends at least daily monitoring for a detailed understanding of CO2 evolution dynamics and management and identifies OMF rate with less CO2 release as a comparatively better alternative in the production of those vegetables in the environmental context.    

    

* 176 Reducing travel distances in Sport – good for people and the planet  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402869250
:TOPICS: Influence of Built Environment on Active Travel
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/eurpub/ckae114.108")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402869250"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402869250"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402869250"))][Get cited by]]

OpenAlex: https://openalex.org/W4402869250 (Open access: True)
    
[[https://openalex.org/A5010664383][Karim Abu‐Omar]], [[https://openalex.org/A5012468659][Derya Özer Kaya]], [[https://openalex.org/A5008881602][Antonina Tcymbal]], [[https://openalex.org/A5065306718][Tobias Volk]], European Journal of Public Health. 34(Supplement_2)] 2024. https://doi.org/10.1093/eurpub/ckae114.108 
     
Abstract Purpose Globally, about 30% of CO2 emissions are caused by travel. In order to comply with calls of the United Nations and the European Commission, the sport sector needs to reduce its emissions caused by travel to tournaments and league games in professional and amateur sport. To this date, no clear mechanisms exists on how to do this. The presentations shows how an algorithm based solution from optimisation science can help sport federations reducing travel distances in any type of league or tournament play. Methods The sport federations of American Football (16 adolescent teams), Biathlon (IBU World Cup Series) and Gymnastics (64 1st and 2nd division Faustball teams) provided data on team locations, league play and tournament formats. Locations of teams and tournaments were mapped with Google Maps, and travel distances (straight-line, by car) were analysed. The algorithm Gurobi from optimisation science was used to optimise league play and tournaments to minimise total travel distances. Results For American Football, 16 adolescent teams travel in total 6329 km (396 km per team) for a season of league play in 2024. The IBU World Cup featuring 10 events for the 2023/24 season results in 13466 km of travel for each participant. In both instances, the optimisation algorithm can propose significant reductions in travel distances. For the IBU World Cup, changing the order of tournaments can reduce travel distances by more than 30%. The analysis of Faustball data is ongoing. Conclusions Travel distances in amateur and professional sport are a significant source of CO2 emissions. Algorithm based optimisation of league and tournament play to reduce travel distances has good potential to put the sport sector more in line with CO2 reduction targets agreed upon in the Paris Agreement. Support/Funding Source No external funds.    

    

* Optimization and Modification of Bacterial Cellulose Membrane from Coconut Juice Residues and Its Application in Carbon Dioxide Removal for Biogas Separation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402764393
:TOPICS: Membrane Gas Separation Technology, Advancements in Water Purification Technologies, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17184750")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402764393"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402764393"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402764393"))][Get cited by]]

OpenAlex: https://openalex.org/W4402764393 (Open access: True)
    
[[https://openalex.org/A5030909756][Wipawee Dechapanya]], [[https://openalex.org/A5107456759][Kamontip Wongsuwan]], [[https://openalex.org/A5089429798][James P. Lewis]], [[https://openalex.org/A5045155800][Attaso Khamwichit]], Energies. 17(18)] 2024. https://doi.org/10.3390/en17184750 
     
Driven by environmental and economic considerations, this study explores the viability of utilizing coconut juice residues (CJRs), a byproduct from coconut milk production, as a carbon source for bacterial cellulose (BC) synthesis in the form of a versatile bio-membrane. This work investigates the use of optimization modeling as a tool to find the optimal conditions for BC cultivation in consideration of waste minimization and resource sustainability. Optimization efforts focused on three parameters, including pH (4–6), cultivation temperature (20–30 °C), and time (6–10 days) using Design Expert (DE) V.13. The maximum yield of 9.31% (g/g) was achieved when the cultivation took place at the optimal conditions (pH 6, 30 °C, and 8 days). This approach aligns with circular economy principles, contributing to sustainable resource management and environmental impact reduction. The experimental and predicted optimal conditions from DE V.13 were in good agreement, validating the study’s outcomes. The predictive model gave the correlations of the optimal conditions in response to the highest yield and maximum eco-efficiency. The use of prediction modeling resulted in a useful tool for forecasting and obtaining guidelines that can assist other researchers in calculating optimal conditions for a desired yield. Acetylation of the BC resulted in cellulose acetate (CA) membranes. The CA membrane exhibited the potential to separate CO2 from a CH4/CO2 mixed gas with a CO2 selectivity of 1.315 in a membrane separation. The promising gas separation results could be further explored to be utilized in biogas purification applications.    

    

* Investigating the Relationship between Energy Consumption and Environmental Degradation with the Moderating Influence of Technological Innovation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402760981
:TOPICS: Economic Impact of Environmental Policies and Resources, Indoor Air Pollution in Developing Countries, Rebound Effect on Energy Efficiency and Consumption
:PUBLICATION_DATE: 2024-09-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/jrfm17090419")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402760981"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402760981"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402760981"))][Get cited by]]

OpenAlex: https://openalex.org/W4402760981 (Open access: True)
    
[[https://openalex.org/A5104617705][Suzan Sameer Issa]], [[https://openalex.org/A5047532391][Mosab I. Tabash]], [[https://openalex.org/A5053922098][Adel Ahmed]], [[https://openalex.org/A5063324086][Hosam Alden Riyadh]], [[https://openalex.org/A5007231493][Mohammed Alnahhal‬‏]], [[https://openalex.org/A5031656708][Manishkumar Varma]], Journal of risk and financial management. 17(9)] 2024. https://doi.org/10.3390/jrfm17090419 
     
Energy consumption (ECON) in BRICS countries is fueled by fossil fuels, mainly coal. Increased environmental degradation (ED) in BRICS countries is mostly driven by coal consumption. This study utilizes quantile regression for the analysis, enabling the development of targeted energy reorganization and emission reduction policies in BRICS countries. This study uses data spanning from 1990 to 2022 to explore the impact of ECON on ED. Additionally, technological innovation was used to create a moderating role in the nexus between ECON and ED. The model focuses on CO2 emissions and the ecological footprint across ten BRICS countries. Among the nations included in the panel, the results indicate a significant dependence on cross-sectional factors. The study shows that ECON has a detrimental impact on ED across all quantiles. However, technological innovation reduces ED. In terms of a moderating role, technological innovation mitigates the negative influence of ECON on ED. Therefore, it is necessary to implement distinct policies in order to accomplish carbon emission reduction goals in various countries.    

    

* Role of Green Building Materials in Reducing Environmental and Human Health Impacts Using VIKOR Method  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402788835
:TOPICS: Comprehensive Survey of Big Data Mining Approaches, Applications and Challenges of IoT, Smart Systems and IoT Applications
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.46632/tfe/2/3/1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402788835"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402788835"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402788835"))][Get cited by]]

OpenAlex: https://openalex.org/W4402788835 (Open access: False)
    
, Trends in Finance and Economics. 2(3)] 2024. https://doi.org/10.46632/tfe/2/3/1 
     
Green Building Materials (GBMs) are construction materials Green building materials (GBMs), sustainable building practices, resource conservation, energy efficiency, indoor air quality, environmental impact reduction, and renewable and recyclable materials. The drive to adopt GBMs is fueled by the need to reduce energy consumption, cut greenhouse gas emissions, and preserve natural resources. By incorporating renewable, recyclable, and non-toxic elements, GBMs are integral to sustainable building practices, ensuring a balance between development and environmental responsibility. Growing awareness of environmental challenges and the emphasis on sustainable development have made green building materials a central focus in contemporary construction. Environmental Impact Reduction: GBMs help decrease the environmental footprint of construction by cutting waste, cutting greenhouse gas emissions, and using less energy. These minerals are essential for maintaining ecosystems and halting climate change. Health & Well-Being: Research on GBMs makes it easier to create materials that improve indoor air quality and reduce exposure to dangerous pollutants, which benefits building occupants' comfort and health. Resource Conservation: This study promotes the use of recyclable and renewable materials, helping to preserve the planet's finite natural resources and encouraging the building sector to implement circular economy principles. Alternatives taken as Bamboo, Recycled Steel, Cork, Rammed Earth, Hempcrete, Straw Bale. Evaluation Parameters taken as Thermal Insulation (Benefit), Sustainability Score (Benefit), Cost per Square Meter (Non-Benefit), CO2 Emissions during Production (Non-Benefit). The results indicate that Recycled Steel achieved the highest rank, while Straw Bale had the lowest rank being attained. “The value of the dataset for Green Building Materials, according to the VIKOR, Recycled Steel achieves the highest ranking.”    

    

* Selenium Biofortification of Pleurotus Mushrooms and Utilization of Spent Waste for Vermicomposting: A Sustainable Approach for Circular Agriculture  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4402928621
:TOPICS: Medicinal Mushrooms: Antitumor and Immunomodulating Properties, Mycorrhizal Fungi and Plant Interactions, Plant-Parasitic Nematodes in Molecular Plant Pathology
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18805/ag.d-6060")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402928621"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402928621"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402928621"))][Get cited by]]

OpenAlex: https://openalex.org/W4402928621 (Open access: True)
    
[[https://openalex.org/A5107553834][H. Abinaya]], [[https://openalex.org/A5091140709][M. Haritha]], [[https://openalex.org/A5074923062][SINDHU SINDHU]], [[https://openalex.org/A5107586520][C.A. Annaporani]], [[https://openalex.org/A5061444657][D. Lavanya]], Agricultural Science Digest - A Research Journal. None(Of)] 2024. https://doi.org/10.18805/ag.d-6060 
     
Background: Agro-wastes represent valuable resources for mushroom cultivation, particularly Pleurotus species, which offer significant nutritional benefits and are grown using cost-effective methods. Selenium (Se), an essential micronutrient crucial for human health, is vital for preventing various diseases. Sodium selenite has emerged as an effective method for increasing selenium levels in mushrooms, thereby enhancing their nutritional quality. Additionally, utilizing biofortified spent mushroom waste for vermicomposting presents a sustainable solution for recycling organic waste and improving soil fertility. Methods: This study examines the biofortification of three Pleurotus species by applying sodium selenite in paddy straw substrate. The research investigates selenium accumulation and its impact on yield and biological efficiency, in addition to assessing various biochemical parameters. Furthermore, the study explores the influence of selenium-biofortified spent mushroom waste on the growth of earthworms during the vermicomposting process. Result: Our investigation into the biofortification of mushrooms with selenium revealed that incorporating 5% of sodium selenite into the substrate significantly enhanced the selenium content of Pleurotus ulmarius (CO2), Pleurotus florida and Pleurotus eous (APK1). However, increasing selenium content in the substrate correlated with decreased biological efficiency. Selenium biofortification resulted in a noteworthy increase in protein content alongside a reduction in carbohydrate levels. Moreover, utilizing selenium-biofortified spent mushroom waste (SeSMS) at a concentration of 2.5% in combination with cow dung (1:10) yielded favorable outcomes, including enhanced cocoon production and the presence of young and adult worms during vermicomposting on both the 60th and 90th day.    

    
