#+filetags: CO2RR
#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Thu Feb  1 00:40:46 2024

Found 55 results from 2024-01-18 to 2024-02-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Acarbon%20dioxide%20reduction]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aco2%20reduction]]

** Composition effects of electrodeposited Cu-Ag nanostructured electrocatalysts for CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-tfkhh")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390979173"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390979173"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390979173"))][Get cited by]]

OpenAlex: https://openalex.org/W4390979173 (Open access: True)
    
[[https://openalex.org/A5001934074][Elena Plaza-Mayoral]], [[https://openalex.org/A5018856830][Valery Okatenko]], [[https://openalex.org/A5026251278][Kim N. Dalby]], [[https://openalex.org/A5091012326][Hanne Falsig]], [[https://openalex.org/A5090008029][Ib Chorkendorff]], [[https://openalex.org/A5079498717][Paula Sebastián‐Pascual]], [[https://openalex.org/A5026837841][María Escudero‐Escribano]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-tfkhh  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65a796cf9138d231611c2449/original/composition-effects-of-electrodeposited-cu-ag-nanostructured-electrocatalysts-for-co2-reduction.pdf][pdf]])
     
The electrochemical reduction of carbon dioxide (CO2RR) to valuable C2+ liquid fuels and oxygenates, such as ethanol and propanol, is a promising strategy to minimize the carbon footprint and store renewable electricity. In this study, we investigate the CO2RR on electrodeposited Cu-Ag nanostructures obtained using a green choline chloride and urea deep eutectic solvent (DES). We show that Cu-Ag nanostructured electrocatalysts with tunable composition, loadings, and size can be simply prepared in one step, without adding other additives or surfactant agents. We investigate the intrinsic activity and selectivity of the CO2RR by determining the electrochemically active surface area (ECSA) using lead underpotential deposition (UPD). The analysis of the partial current densities normalized by the ECSA shows that the addition of Ag on electrodeposited Cu primarily suppresses the production of hydrogen and methane with respect to Cu nanostructures. At the same time, the production of carbon monoxide (CO) slightly increases but, the partial current of the total C2+ products does not considerably increase. Despite that the production rate of C2+ is similar on Cu and CuAg, the addition of Ag enhances the formation of alcohols and oxygenates over ethylene, in line with previous reports. We highlight the potential of metal electrodeposition from DES as a sustainable and inexpensive strategy for the development of bimetallic Cu-based nanocatalysts towards CO2RR.    

    

** Recent advances in copper-based catalysts for electrocatalytic CO 2 reduction toward multi-carbon products   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26599/nre.2024.9120112")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987371"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987371 (Open access: True)
    
[[https://openalex.org/A5025855204][Rongrong Li]], [[https://openalex.org/A5058501731][Hehe Wei]], [[https://openalex.org/A5077153113][Ping Liu]], [[https://openalex.org/A5071574675][Zixiang Su]], [[https://openalex.org/A5062523981][X. G. Gong]], Nano Research Energy. None(None)] 2024. https://doi.org/10.26599/nre.2024.9120112  ([[https://file.sciopen.com/sciopen_public/1747873898448973825.pdf][pdf]])
     
Electrocatalytic carbon dioxide reduction reaction (CO2RR) holds the promise of both overcoming the greenhouse effect and synthesizing a wealth of chemicals. Electrocatalytic CO2 reduction toward carbon-containing products, including C1 products (carbon monoxide, formic acid, etc), C2 products (ethylene, ethanol, etc.) and multi-carbon products (e.g., npropanol), provides beneficial fuel and chemicals for industrial production. The complexity of the multi-proton transfer processes and difficulties of C-C coupling in electrochemical CO2 reduction toward multi-carbon(C2+) products have attracted increasing concerns on the design of catalysts in comparison with those of C1 products. In this paper, we review the main advances in the syntheses of multi-carbon products through electrocatalytic carbon dioxide reduction in recent years, introduce the basic principles of electrocatalytic CO2RR, and detailly elucidate two widely accepted mechanisms of C-C coupling reactions. Among abundant nanomaterials, copper-based catalysts are outstanding catalysts for the preparation of multi-carbon chemicals in electrochemical CO2RR attributing to effective C-C coupling reactions. Regarding the different selectivity of multi-carbon chemicals but extensively applied copper-based catalysts, we classify and summarize various Cu-based catalysts through separating diverse multi-carbon products, where the modification of spatial and electronic structures is beneficial to increase the coverage of CO or lower the activation energy barrier for forming CC bond to form the key intermediates and increase the production of multi-carbon products. Challenges and prospects involving the fundamental and development of copper-based catalysts in electrochemical CO2 reduction reaction are also proposed.    

    

** MOFs materials as photocatalysts for CO2 reduction: Progress, challenges and perspectives   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ccst.2024.100191")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391019430"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391019430"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391019430"))][Get cited by]]

OpenAlex: https://openalex.org/W4391019430 (Open access: True)
    
[[https://openalex.org/A5049709719][Mazhar Khan]], [[https://openalex.org/A5003303773][Zeeshan Akmal]], [[https://openalex.org/A5003238643][Muhammad Tayyab]], [[https://openalex.org/A5070908155][Seemal Mansoor]], [[https://openalex.org/A5086947282][Adnan Zeb]], [[https://openalex.org/A5068766141][Ziwei Ye]], [[https://openalex.org/A5001457544][Jinlong Zhang]], [[https://openalex.org/A5067320385][Shiqun Wu]], [[https://openalex.org/A5050352409][Lingzhi Wang]], No host. 11(None)] 2024. https://doi.org/10.1016/j.ccst.2024.100191 
     
Photocatalytic reduction of carbon dioxide (CO2) presents a pivotal solution to address meteorological and ecological challenges. Currently, metal-organic frameworks (MOFs) with their crystalline porosity, adjustable structures, and diverse chemical functionalities have garnered significant attention in the realm of photocatalytic CO2 reduction. This review provides a brief introduction to CO2 reduction and MOF material and their applications in CO2 reduction. Then, it undertakes a comprehensive examination of MOFs, summarizing their key attributes, including porosity, large surface area, structural multifunctionalities, and responsiveness to visible light, along with an analysis of heterojunctions and their methods of preparation. Additionally, it elucidates the fundamental principle of photocatalysis and CO2 reduction, encompassing both half and overall reactions. Furthermore, the classification of MOF-based materials is explored, along with the proposed mechanism for CO2 reduction and an update on recent developments in this field. Finally, this review outlines the challenges and potential opportunities for utilizing MOFs in CO2 reduction, offering valuable insights to scholars seeking innovative approaches not only to enhance CO2 reduction but also to advance other photocatalytic processes.    

    

** Tuning the CO2 Reduction Activity of Graphitic Carbon Nitride via the Capping-Agent-Free Involvement of Ag Nanocrystals   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.iecr.3c03841")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391111388"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391111388"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391111388"))][Get cited by]]

OpenAlex: https://openalex.org/W4391111388 (Open access: False)
    
[[https://openalex.org/A5028735627][Liang Ma]], [[https://openalex.org/A5044598955][Xiaoyan Cai]], [[https://openalex.org/A5009420754][Zhiqiang Liang]], [[https://openalex.org/A5081903932][Shun Lu]], [[https://openalex.org/A5007181087][Pengxuan Wu]], [[https://openalex.org/A5091240034][Songbai Qiu]], [[https://openalex.org/A5034261218][Qian Zhang]], [[https://openalex.org/A5085293433][Tiejun Wang]], No host. None(None)] 2024. https://doi.org/10.1021/acs.iecr.3c03841 
     
In this work, a facile method to tune the carbon dioxide (CO2) reduction reaction (CRR) activities of graphitic carbon nitride (GCN) was developed via the capping-agent-free involvement of a trace amount of Ag nanocrystals with a decreased size. After the optimization of experimental conditions, the CRR performance investigation confirms that Ag-GCN-0.2 exhibited a superior CRR performance, achieving a faradaic efficiency (FE) of more than 72 ± 1% for CO in a wide potential range from −0.6 to −1.1 V (vs reversible hydrogen electrode (RHE)) and a max FE of 89 ± 1% at an overpotential of 0.9 V with a constant current density and a well-maintained microstructure even after 12 h of electrolysis. This work provides a new route to tune the catalytical performance of GCN and pave the way for the rational design, synthesis, and accurate estimation of the GCN-based catalysts, which will be synthesized on a large scale and utilized in industries.    

    

** Cadmium sulfide nanoparticles compositing with chitosan and metal-organic framework: Enhanced photostability and increased carbon dioxide reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s42114-024-00837-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391276659"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391276659"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391276659"))][Get cited by]]

OpenAlex: https://openalex.org/W4391276659 (Open access: False)
    
[[https://openalex.org/A5042973046][Ying Zhang]], [[https://openalex.org/A5009620553][Hao Liang]], Advanced Composites and Hybrid Materials. 7(1)] 2024. https://doi.org/10.1007/s42114-024-00837-2 
     
No abstract    

    

** Surface gallium oxide hydroxide species adsorbing carbon dioxide to enhance the photocatalytic activity of a silver-loaded calcium titanate for carbon dioxide reduction with water   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3se01390a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391319608"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391319608"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391319608"))][Get cited by]]

OpenAlex: https://openalex.org/W4391319608 (Open access: True)
    
[[https://openalex.org/A5080636617][Hongxuan Qiu]], [[https://openalex.org/A5021171836][Akira Yamamoto]], [[https://openalex.org/A5057290198][Hisao Yoshida]], Sustainable Energy and Fuels. None(None)] 2024. https://doi.org/10.1039/d3se01390a  ([[https://pubs.rsc.org/en/content/articlepdf/2024/se/d3se01390a][pdf]])
     
Photocatalytic conversion of carbon dioxide (CO 2 ) has attracted considerable attention as a new method to build a carbon cycle. Particularly, photocatalytic reduction of CO 2 using water as an electron and...    

    

** Challenges in Photocatalytic Carbon Dioxide Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/prechem.3c00112")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390937362"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390937362"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390937362"))][Get cited by]]

OpenAlex: https://openalex.org/W4390937362 (Open access: True)
    
[[https://openalex.org/A5062278897][Guangfu Liao]], [[https://openalex.org/A5083749310][Guixiang Ding]], [[https://openalex.org/A5055594201][Bin Yang]], [[https://openalex.org/A5088434794][Chunxue Li]], Precision Chemistry. None(None)] 2024. https://doi.org/10.1021/prechem.3c00112  ([[https://pubs.acs.org/doi/pdf/10.1021/prechem.3c00112][pdf]])
     
An energy crisis and significant anthropogenic CO2 emissions as a result of rising fossil fuel consumption have caused a rapid increase in global temperature. One of the best solutions to these two issues is thought to be the photocatalytic reduction of CO2 into value-added carbon-containing products. In this aspect, the main challenges mainly include the photocatalytic mechanism, reaction activity, and product selectivity, especially in ambiguous reaction pathways and product selectivity, an unclear charge transfer mechanism, and an overestimate of product yield. Therefore, in this perspective, we attempt to exhibit the discussion and in-depth analysis of the possible reaction pathways and product selectivity, the specific charge transfer mechanism, and the origin of carbon-containing products in phtocatalytic CO2 reduction. Besides, the fundamentals for photocatalytic CO2 reduction are also illustrated. Finally, the state-of-the-art challenges and perspectives in CO2 photoreduction are highlighted and discussed in detail. This perspective is expected to evoke more research attention for the photocatalytic reduction of CO2 into value-added products.    

    

** Molecular Additives Improve the Selectivity of CO2 Photoelectrochemical Reduction over Gold Nanoparticles on Gallium Nitride   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.3c03590")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390943227"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390943227"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390943227"))][Get cited by]]

OpenAlex: https://openalex.org/W4390943227 (Open access: False)
    
[[https://openalex.org/A5034872224][Aisulu Aitbekova]], [[https://openalex.org/A5079861547][Nicholas B. Watkins]], [[https://openalex.org/A5072433173][Matthias H. Richter]], [[https://openalex.org/A5042520017][Phillip Jahelka]], [[https://openalex.org/A5057055428][Jonas C. Peters]], [[https://openalex.org/A5004911977][Theodor Agapie]], [[https://openalex.org/A5082887836][Harry A. Atwater]], Nano Letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.3c03590 
     
Photoelectrochemical CO2 reduction (CO2R) is an appealing solution for converting carbon dioxide into higher-value products. However, CO2R in aqueous electrolytes suffers from poor selectivity due to the competitive hydrogen evolution reaction that is dominant on semiconductor surfaces in aqueous electrolytes. We demonstrate that functionalizing gold/p-type gallium nitride devices with a film derived from diphenyliodonium triflate suppresses hydrogen generation from 90% to 18%. As a result, we observe increases in the Faradaic efficiency and partial current density for carbon monoxide of 50% and 3-fold, respectively. Furthermore, we demonstrate through optical absorption measurements that the molecular film employed herein, regardless of thickness, does not affect the photocathode’s light absorption. Altogether, this study provides a rigorous platform for elucidating the catalytic structure–property relationships to enable engineering of active, stable, and selective materials for photoelectrochemical CO2R.    

    

** Mechanism of electrochemical carbon dioxide reduction to formate on tin electrode   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148972")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391112540"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391112540"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391112540"))][Get cited by]]

OpenAlex: https://openalex.org/W4391112540 (Open access: False)
    
[[https://openalex.org/A5093764007][Anoop Naikkath]], [[https://openalex.org/A5062981183][Nikhil George Mohan]], [[https://openalex.org/A5041030856][Kothandaraman Ramanujam]], [[https://openalex.org/A5042539944][Surash Ramanathan]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.148972 
     
Carbon dioxide can be electrochemically reduced to formate on tin electrodes. Formate is one of the most economically viable products of CO2 reduction reaction (CO2RR). While CO2 is reduced to formate, hydrogen evolution reaction (HER) occurs concomitantly. The kinetics of CO2RR and HER on the tin electrode was investigated. Potentiodynamic polarization studies were conducted in CO2 saturated and N2 saturated 0.1 M KHCO3 solutions, in the potential range from −0.014 V to −1.59 V vs. RHE. A faradaic efficiency of 93.95 % towards formate production was obtained at −1.09 V vs. RHE. The mass transfer effects and bicarbonate dissociation equilibrium were used to estimate the concentration of the reactants at the electrode surface. Density functional theory calculations indicate that –OCHO intermediate species is thermodynamically favoured, and a four-step reaction with two intermediates is proposed. The proposed mechanism captures the major features of the polarization data. CO2 reduction occurs via two intermediate species, viz. adsorbed H and OCHO species, while HER occurs via Volmer-Heyrovsky steps. The model predicts that in N2 saturated solutions, the fractional surface coverage of adsorbed H reaches a maximum of ∼0.48 at a potential of −0.82 V vs. RHE while in CO2 saturated solutions, the corresponding value is ∼0.29. In addition, the maximum fractional surface coverage of adsorbed OCHO is predicted to be ∼0.12 in CO2 saturated solutions.    

    

** Exploring Carbon Monoxide and Carbon Dioxide Adsorption on (5,5) Aluminum Nitride Nanotubes for Enhanced Sensor Applications: A DFT Study   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29030557")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391136623"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391136623"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391136623"))][Get cited by]]

OpenAlex: https://openalex.org/W4391136623 (Open access: True)
    
[[https://openalex.org/A5038227907][Nafiu Suleiman]], [[https://openalex.org/A5079033541][Vitus A. Apalangya]], [[https://openalex.org/A5078135160][Bismark Mensah]], [[https://openalex.org/A5054039917][Kwabena Kan-Dapaah]], [[https://openalex.org/A5033891258][Abu Yaya]], Molecules. 29(3)] 2024. https://doi.org/10.3390/molecules29030557  ([[https://www.mdpi.com/1420-3049/29/3/557/pdf?version=1706009200][pdf]])
     
This study examined the sensitivity of single-walled (5,5) aluminium nitride nanotubes ((5,5) AlNNTs) to carbon monoxide (CO) and carbon dioxide (CO2) gas molecules by performing DFT calculations using a hybrid functional, specifically, B3LYP (Becke’s three-parameter, Lee-Yang-Parr) exchange-correlation functional at a 6–31G* basis set. This research investigates the adsorption behavior of CO2 and CO molecules on pristine and silicon-doped aluminum nitride nanotubes (AlNNTs) and examines their implications for sensor applications. The study assesses each system’s adsorption energy, sensing potential, and recovery time to gain insights into their binding strength and practical viability. For CO2 adsorption on (5,5) AlNNT, significant adsorption energy of −24.36 kcal/mol was observed, indicating a strong binding to the nanotube surface, with a sensing potential of 8.95%. However, the slow recovery time of approximately 4.964 days may limit its real-time application. Si-(5,5) AlNNT exhibited a CO2 adsorption energy of −19.69 kcal/mol, a sensing potential of 5.40%, and a relatively short recovery time of approximately 2.978 min, making it a promising candidate for CO2 sensing. CO adsorption on (5,5) AlNNT showed an adsorption energy of −25.20 kcal/mol, a sensing potential of 9.095%, but a longer recovery time of approximately 20.130 days. Si-(5,5) AlNNT displayed a high CO adsorption energy of −20.78 kcal/mol, a sensing potential of 4.29%, and a recovery time of approximately 18.320 min. These findings provide insights into the adsorption characteristics of carbon molecules on AlNNTs, highlighting their potential for CO2 and CO sensing applications.    

    

** Steering the Selectivity of Carbon Dioxide Electroreduction from Single-Carbon to Multicarbon Products on Metal–Organic Frameworks via Facet Engineering   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.3c04092")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391160753"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391160753"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391160753"))][Get cited by]]

OpenAlex: https://openalex.org/W4391160753 (Open access: False)
    
[[https://openalex.org/A5087588830][Pengyi Lu]], [[https://openalex.org/A5005078963][Jia Lv]], [[https://openalex.org/A5052676364][Yu Chen]], [[https://openalex.org/A5085300962][Yangbo Ma]], [[https://openalex.org/A5055096182][Yunhao Wang]], [[https://openalex.org/A5066831596][Wei Lyu]], [[https://openalex.org/A5039185984][Jinli Yu]], [[https://openalex.org/A5025709244][Jingwen Zhou]], [[https://openalex.org/A5082799977][Jinwen Yin]], [[https://openalex.org/A5011847790][Yi Xiong]], [[https://openalex.org/A5081825149][Guozhi Wang]], [[https://openalex.org/A5007388482][Chongyi Ling]], [[https://openalex.org/A5031292832][Shibo Xi]], [[https://openalex.org/A5010844416][Daliang Zhang]], [[https://openalex.org/A5065739319][Zhanxi Fan]], Nano Letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.3c04092 
     
Although metal–organic frameworks (MOFs) have attracted more attention for the electrocatalytic CO2 reduction reaction (CO2RR), obtaining multicarbon products with a high Faradaic efficiency (FE) remains challenging, especially under neutral conditions. Here, we report the controlled synthesis of stable Cu(I) 5-mercapto-1-methyltetrazole framework (Cu-MMT) nanostructures with different facets by rationally modulating the reaction solvents. Significantly, Cu-MMT nanostructures with (001) facets are acquired using isopropanol as a solvent, which favor multicarbon production with an FE of 73.75% and a multicarbon:single-carbon ratio of 3.93 for CO2RR in a neutral electrolyte. In sharp contrast, Cu-MMT nanostructures with (100) facets are obtained utilizing water, promoting single-carbon generation with an FE of 63.98% and a multicarbon: single-carbon ratio of only 0.18. Furthermore, this method can be extended to other Cu-MMT nanostructures with different facets in tuning the CO2 reduction selectivity. This work opens up new opportunities for the highly selective and efficient CO2 electroreduction to multicarbon products on MOFs via facet engineering.    

    

** Steering CO2 Electroreduction to C2+ Products via Enhancing Localized *Co Coverage And Local Pressure in Conical Cavity   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202312204")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391212986"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391212986"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391212986"))][Get cited by]]

OpenAlex: https://openalex.org/W4391212986 (Open access: False)
    
[[https://openalex.org/A5009144836][Chunzhong Li]], [[https://openalex.org/A5008008825][Tingting Zhang]], [[https://openalex.org/A5031879384][Heng Liu]], [[https://openalex.org/A5080456024][Zhongyuan Guo]], [[https://openalex.org/A5033283755][Zhongliang Liu]], [[https://openalex.org/A5088451927][Huancong Shi]], [[https://openalex.org/A5054847042][Jialin Cui]], [[https://openalex.org/A5080057012][Hao Li]], [[https://openalex.org/A5013509330][Huihui Li]], [[https://openalex.org/A5009144836][Chunzhong Li]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202312204 
     
Abstract The electrochemical carbon dioxide reduction reaction (CO 2 RR) involves a multistep proton‐coupled electron transfer (PCET) process that generates a variety of intermediates, making it challenging to transform them into target products with high activity and selectivity. Here, we report a catalyst featuring a nanosheets‐stacked sphere structure with numerous open and deep conical cavities (OD‐CCs). Under the guidance of finite‐element method (FEM) simulations and theoretical analysis, we showed that exerting control over the confinement space resulted in diffusion limitation of the carbon intermediates, thereby increasing local pressure and subsequently enhancing localized *CO coverage for dimerization. The nanocavities exhibited a structure‐driven shift in selectivity of multi‐carbon (C 2+ ) product from 41.8% to 81.7% during the CO 2 RR process. This article is protected by copyright. All rights reserved    

    

** Selectively Adsorbed Mercaptoethanesulfonic Acid on Au/TiO2 Enhances the Yield and Selectivity of Photocatalytic Reduction of Carbon Dioxide   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c03093")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391239090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391239090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391239090"))][Get cited by]]

OpenAlex: https://openalex.org/W4391239090 (Open access: False)
    
[[https://openalex.org/A5054525040][Mengdan Guan]], [[https://openalex.org/A5048989648][Junjie Wang]], [[https://openalex.org/A5075682753][Zhongyan Gong]], [[https://openalex.org/A5038210442][Kun Gao]], [[https://openalex.org/A5001997986][Xing Kang]], [[https://openalex.org/A5017795751][Yulong Zhang]], [[https://openalex.org/A5004494857][Chengcheng Zhu]], [[https://openalex.org/A5035535613][Zhihao Lü]], [[https://openalex.org/A5032903415][Xinya Chen]], [[https://openalex.org/A5029884880][Jianguo Lü]], [[https://openalex.org/A5060177975][Qinghua Liu]], [[https://openalex.org/A5082636639][Haonan Chen]], [[https://openalex.org/A5034590754][Liuyingzi Yu]], [[https://openalex.org/A5077289752][Kaili Wang]], [[https://openalex.org/A5078980502][Zhuoyao Li]], [[https://openalex.org/A5020760319][Gang Lü]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.3c03093 
     
No abstract    

    

** Free‐standing Stanene for High Selectivity of Formate in Electrocatalytic Carbon Dioxide Reduction Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202303889")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391280930"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391280930"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391280930"))][Get cited by]]

OpenAlex: https://openalex.org/W4391280930 (Open access: False)
    
[[https://openalex.org/A5072252699][Xuanhao Mei]], [[https://openalex.org/A5081573284][Cong Liu]], [[https://openalex.org/A5024869142][Dezheng Zhang]], [[https://openalex.org/A5030817316][Jing Cao]], [[https://openalex.org/A5040745256][Rile Ge]], [[https://openalex.org/A5055663516][Junhu Wang]], [[https://openalex.org/A5057597603][Weilin Xu]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202303889 
     
Abstract As well‐known electrocatalysts with good catalytic efficiency for carbon dioxide reduction reaction (CO 2 RR) towards the production of formate, tin (Sn)‐based catalysts have aroused broad concern. Here, free‐standing porous stanene is synthesized for the first time by a facile wet chemical method, and its excellent electrocatalytic performance for formate (HCOO − ) formation in CO 2 RR is demonstrated. High Faradaic efficiency (F.E., 93% at −930 mV versus reversible hydrogen electrode (RHE)) can be achieved in the CO 2 RR catalyzed by stanene in 0.5 m KHCO 3 aqueous solution. The in situ Mössbauer spectra reveal that zero‐valent Sn aids in improving the selectivity of formate production. Furthermore, density functional theory calculations suggest that the high selectivity of HCOO − of CO 2 RR on stanene mainly originates from the edge sites on Sn (100). To further explore the practicability of the stanene‐based catalysts for CO 2 RR, stanene decorated by 3 wt% BP‐2000 is prepared, showing an excellent F.E. of 98% at −930 mV versus RHE due to the higher exposure of catalytic active sites. These new findings of the activity origination and reaction mechanism of stanene contribute to the deeper understanding of Sn‐based catalysts for CO 2 RR, which is beneficial for the future designation of highly efficient CO 2 RR catalysts.    

    

** Solvation of oxygen, carbon dioxide, carbon monoxide and nitrous oxide in fluorinated liquids   
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391327398"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391327398"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391327398"))][Get cited by]]

OpenAlex: https://openalex.org/W4391327398 (Open access: False)
    
[[https://openalex.org/A5084109499][Margarida F Costa Gomes]], [[https://openalex.org/A5014671418][A.A.H. Padua J. Deschamps D.-H. Menz]], No host. None(None)] 2005. None 
     
No abstract    

    

** Recent advances in novel materials for photocatalytic carbon dioxide reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cnl2.107")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391102665"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391102665"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391102665"))][Get cited by]]

OpenAlex: https://openalex.org/W4391102665 (Open access: True)
    
[[https://openalex.org/A5015173933][Suye Lü]], [[https://openalex.org/A5070268195][Shengwei Zhang]], [[https://openalex.org/A5055411333][Qi Liu]], [[https://openalex.org/A5061520391][Wen Wang]], [[https://openalex.org/A5058768613][Nanjing Hao]], [[https://openalex.org/A5085963164][Yajun Wang]], [[https://openalex.org/A5084541609][Zhou Li]], [[https://openalex.org/A5060967626][Dan Luo]], Carbon Neutralization. None(None)] 2024. https://doi.org/10.1002/cnl2.107  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cnl2.107][pdf]])
     
Abstract The conversion of CO 2 into chemical fuels, which can be stored and utilized through photocatalysis, represents an effective, environmentally friendly, and sustainable means to address both environmental concerns and energy shortages. CO 2 , as a stable oxidation product, poses challenges for reduction through light energy alone, necessitating the use of catalysts. Thus, a crucial aspect of CO 2 photocatalytic reduction technology lies in the development of effective photocatalysts. Based on the basic principle of PCRR (photocatalytic CO 2 reduction reaction), the review provides a detailed introduction to the core issues in PCRR process, including the relationship between band gap and catalyst reduction performance, effective utilization of photogenerated carriers, product selectivity, and methods for product analysis. Then, the recent research progresses of various photocatalysts are reviewed in the form of research examples combined with the above basic principles. Finally, this review summarizes and provides insights into the effective techniques for enhancing the photocatalytic activity of CO 2 , while also offering future prospects in this field.    

    

** Determining kinetics of electrochemical carbon dioxide reduction to carbon monoxide with scanning electrochemical microscopy   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2024.118061")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391116059"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391116059"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391116059"))][Get cited by]]

OpenAlex: https://openalex.org/W4391116059 (Open access: False)
    
[[https://openalex.org/A5045371783][Qikang Huang]], [[https://openalex.org/A5014441532][Peize Li]], [[https://openalex.org/A5041280820][Mingkui Wang]], [[https://openalex.org/A5003395657][Yan Shen]], Journal of Electroanalytical Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jelechem.2024.118061 
     
This study reports on determining kinetics of electrochemical reduction CO2 to CO on Au catalysts using the substrate generation/tip collection (SG/TC) mode of scanning electrochemical microscopy (SECM). We introduced a simple but effective method based on transient technique to obtain a series of apparent heterogeneous rate constants k based on Fick’s second law by controlling the tip-substrate distance and the voltage of the substrate electrode within the SECM framework. By analysis the transient current recorded during the chronoamperometric characterization, we can successfully determine the apparent rate constant k for the simplified total conversion process of CO2 + 2H+ + 2e- → CO + H2O onto Au catalyst electrode serving as an example, which increases from 5.02 × 10–2 cm⋅s−1 to 7.16 × 10–2 cm⋅s−1 in the low potential range of −2.2 to −2.6 V (vs. Pt/PPy) and decreases to 6.54 × 10-2 cm⋅s−1 at –2.8 V (vs. Pt/PPy). The method proposed here can be applied to quantitatively analyze the kinetic of CO2 electrochemical reduction reaction, and thus provide a useful tool to guide the synthesis of catalyst as well as in-situ performance evaluation.    

    

** Carbon dioxide reduction to methane and ethanol by using boron carbide monolayer as a suitable photocatalyst   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.diamond.2024.110849")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391089745"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391089745"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391089745"))][Get cited by]]

OpenAlex: https://openalex.org/W4391089745 (Open access: False)
    
[[https://openalex.org/A5016779284][Mohamed J. Saadh]], [[https://openalex.org/A5084593121][Saade Abdalkareem Jasim]], [[https://openalex.org/A5010958862][Linda Mariuxi Flores Fiallos]], [[https://openalex.org/A5005025571][Anupam Yadav]], [[https://openalex.org/A5040948370][Louay Saleh]], [[https://openalex.org/A5047607461][Edwin Jácome]], [[https://openalex.org/A5043976657][César Gerardo Mejía Gallegos]], [[https://openalex.org/A5015561046][Yazen M. Alawaideh]], [[https://openalex.org/A5051339559][Yasser Elmasry]], Diamond and Related Materials. None(None)] 2024. https://doi.org/10.1016/j.diamond.2024.110849 
     
A new-type boron carbide material has been used, as an electrocatalyst for the reduction of CO2 to C2 and C1 based on the computational study. Within the current research, DFT was adopted to investigate the BC3 nanoflake as an electrocatalyst for the reduction of CO2. The optoelectronic attributes of the BC3 nanoflake indicated that BC3 nanoflake had a longer visible-light region and its band gap was 2.25 eV. Based on the spatial distribution of the LUMO and the HOMO, the introduction of boron extended the π network of BC3 nanoflake, thereby dramatically increasing the photocatalytic efficiency. Additionally, we estimated the Gibbs free energy of each potential CO2 reaction path onto BC3 nanoflake. Based on the findings, CO2 could reduce into CH4 and CH3CH2OH with low limiting potentials of −0.41 V and −0.53 V, respectively. The current study can provide useful insights into the application of BC3 nanoflake as an encouraging photocatalyst for the reduction reaction CO2.    

    

** A Thermodynamic View on the In-situ Carbon Dioxide Reduction by Biomass-derived Hydrogen during Calcium Carbonate Decomposition   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cjche.2023.12.017")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391037978"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391037978"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391037978"))][Get cited by]]

OpenAlex: https://openalex.org/W4391037978 (Open access: False)
    
[[https://openalex.org/A5017430213][Peng Jiang]], [[https://openalex.org/A5049341927][Hao Zhang]], [[https://openalex.org/A5089446069][Guanhan Zhao]], [[https://openalex.org/A5058965019][Lin Li]], [[https://openalex.org/A5022762913][Tuo Ji]], [[https://openalex.org/A5066372594][Liwen Mu]], [[https://openalex.org/A5048052547][Xiaohua Lü]], [[https://openalex.org/A5024790419][Jiahua Zhu]], Chinese Journal of Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.cjche.2023.12.017 
     
In the carbonate industry, deep decarbonization strategies are necessary to effectively remediate CO2. These strategies mainly include both sustainable energy supplies and the conversion of CO2 in downstream processes. This study developed a coupled process of biomass chemical looping H2 production and reductive calcination of CaCO3. Firstly, a mass and energy balance of the coupled process was established in Aspen Plus. Following this, process optimization and energy integration were implemented to provide optimized operation conditions. Lastly, a life cycle assessment was carried out to assess the carbon footprint of the coupled process. Results reveal that the decomposition temperature of CaCO3 in an H2 atmosphere can be reduced to 780 oC (generally around 900 oC), and the conversion of CO2 from CaCO3 decomposition reached 81.33% with an H2:CO ratio of 2.49 in gaseous products. By optimizing systemic energy through heat integration, an energy efficiency of 86.30% was achieved. Additionally, the carbon footprint analysis revealed that the process with energy integration had a low GWP of -2.624 kgCO2-eq·kg-CaO-1. Conclusively, this work performed a systematic analysis of introducing biomass-derived H2 into CaCO3 calcination and demonstrated the positive role of reductive calcination using green H2 in mitigating CO2 emissions within the carbonate industry.    

    

** Oxygen vacancies synergistic cobalt phosphide electron bridge modulated bismuth oxychloride/carbon nitride Z-scheme junction for efficient carbon dioxide reduction coupled with tetracycline oxidation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.149")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391264958"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391264958"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391264958"))][Get cited by]]

OpenAlex: https://openalex.org/W4391264958 (Open access: False)
    
[[https://openalex.org/A5040035723][Haoyu Sun]], [[https://openalex.org/A5003221894][Xuemei Jia]], [[https://openalex.org/A5066617829][Jing Cao]], [[https://openalex.org/A5002901852][Shifu Chen]], [[https://openalex.org/A5085462851][Yong Chen]], [[https://openalex.org/A5090567072][Haili Lin]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.149 
     
Although great progress has been made with respect to electron bridges, the electron mobility of the state-of-the-art electron bridges is far from satisfactory because of weak electrical conductivity. To overcome the above issue, cobalt phosphide (CoP), as a model electron bridge, was modified with superficial oxygen vacancies (OVs) and embedded into a defective bismuth oxychloride/carbon nitride (BiO1-xCl/g-C3N4) Z-scheme heterojunction to obtain atomic-level insights into the effect of surface OVs on CoP electron bridges. Compared to BiO1-xCl/g-C3N4 and bismuth oxychloride/cobalt phosphide/carbon nitride (BiOCl/CoP/g-C3N4) composites, the defective bismuth oxychloride/cobalt phosphide/carbon nitride (BiO1-xCl/CoP/g-C3N4) heterojunction exhibited remarkable photocatalytic redox performance, indicating that the surface OVs-assisted CoP electron bridge effectively boosted electrical conductivity and yielded ultrafast electron transfer rates. The theoretical and experimental results demonstrate that the surface OVs play a critical role in improving the electrical conductivity of the CoP electron bridge, thereby accelerating electron mobility. This research provides insights into interfacial OVs-modified transition metal phosphide (TMP) electron bridges and their potential application in heterojunctions for energy crisis mitigation and environmental remediation.    

    

** The synergistic role of carbon dioxide removal and emission reductions in achieving the Paris Agreement goal   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.spc.2024.01.004")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391071426"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391071426"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391071426"))][Get cited by]]

OpenAlex: https://openalex.org/W4391071426 (Open access: False)
    
[[https://openalex.org/A5027923888][Humphrey Adun]], [[https://openalex.org/A5044399467][Jeffrey Dankwa Ampah]], [[https://openalex.org/A5057518673][Olusola Bamisile]], [[https://openalex.org/A5037442960][Yihua Hu]], Sustainable Production and Consumption. None(None)] 2024. https://doi.org/10.1016/j.spc.2024.01.004 
     
The limiting global carbon budget underscores the urgent need for effective and ambitious climate mitigation measures across diverse sectors to curb greenhouse gas emissions and prevent further exacerbation of global warming, aligning with international agreements such as the Paris Agreement. The role of carbon dioxide removal (CDR) becomes increasingly crucial in this context, though the extent to which this applies as a complementary measure to mitigation actions still requires careful examination and quantitative analysis. In this study, we carry out an assessment contingent upon the intertwined roles of mitigation actions and the levels of CDR deployment using the Energy-Rapid Overview and Decision-Support (En-ROADS) simulation tool. We develop sectoral emission reduction assumptions and a broad portfolio of CDR archetypes and deployment levels to evaluate their impacts on the intricate climate-land-energy nexus, and global warming temperature. We find that high levels of CDR permit the continual consumption of fossil fuels, though driving substantial renewable energy consumption post-mid-century. We also observe that high levels of CDR negatively impact sustainability factors, such as reduction in agricultural farmland, which is pronounced under high mitigation actions. We observe that the largest share of CDR is in agricultural soil carbon, with its proportion ranging from 27.4 % to 31.3 % across all scenarios. In conclusion, though CDRs are what put the ‘net’ in the ‘net-zero emissions’ goal, they are not a silver bullet but rather a crucial piece in the complex puzzle of climate action. We recommend that CDR should be strategically deployed as complementary options to vigorous emission reduction efforts, as this paves the way towards a sustainable and balanced approach to achieving our global climate objectives.    

    

** Thermodynamic Analysis of Exhaust Gas Waste Heat Recovery with Organic Rankine Cycle for Container Ship   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4703037")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391097601"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391097601"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391097601"))][Get cited by]]

OpenAlex: https://openalex.org/W4391097601 (Open access: False)
    
[[https://openalex.org/A5061457454][Merve GÜL ÇIVGIN]], [[https://openalex.org/A5039497906][Cengiz Deniz]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4703037 
     
Highlights• Thermodynamic analysis of organic rankine cycle using exhaust gas as a heat source was done.• The amount of carbon dioxide reduction obtained using the organic rankine cycle was shown.• The cases where the exhaust gas has different thermal values such as boiler outlet, turbocharger outlet were analyzed.• The selection of working fluid was evaluated according to exhaust gas specifications as a heat source.• The effect of evaporation temperature of working fluid and degree of superheating on the ORC system performance was analyzed.    

    

** プラズマ触媒作用を用いた二酸化炭素還元反応の促進に関する基礎研究   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.7791/jspmee.13.31")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391161005"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391161005"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391161005"))][Get cited by]]

OpenAlex: https://openalex.org/W4391161005 (Open access: True)
    
[[https://openalex.org/A5083610808][Susumu Toko]], [[https://openalex.org/A5065406931][Takamasa Okumura]], [[https://openalex.org/A5079413858][Kunihiro Kamataki]], [[https://openalex.org/A5065576212][Kosuke Takenaka]], [[https://openalex.org/A5074854741][Kazunori KOGA]], [[https://openalex.org/A5026098035][Masaharu Shiratani]], [[https://openalex.org/A5067792196][Yuichi Setsuhara]], No host. 13(1)] 2024. https://doi.org/10.7791/jspmee.13.31  ([[https://www.jstage.jst.go.jp/article/jspmee/13/1/13_31/_pdf][pdf]])
     
Carbon dioxide reduction is one of the key technologies for achieving a sustainable society. In this study, plasma catalysis were used to hydrogenate carbon dioxide to produce methane. Plasma catalysis have attracted attention in recent years as a technology promoting a reaction at lower temperatures by various synergistic effects between plasma and catalysts. In this study, molecular sieve with a pore diameter of 3 Å was used as a catalyst and its role was investigated. The results showed that: 1. molecular and atomic adsorption functions of molecular sieves are useful to inhibit reverse reactions; 2. the influence of molecular sieves becomes stronger at higher pressures, resulting in higher methane production; 3. energetic reactive particles derived from hydrogen deactivate molecular sieves; 4. molecules adsorbed on molecular sieve can be recycled by hydrogen plasma irradiation.    

    

** Plasmonic‐assisted Electrocatalysis for CO2 Reduction Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202300805")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391173783"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391173783"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391173783"))][Get cited by]]

OpenAlex: https://openalex.org/W4391173783 (Open access: True)
    
[[https://openalex.org/A5081184104][Xiu Wang]], [[https://openalex.org/A5013152328][Miao Yu]], [[https://openalex.org/A5005239842][Ziyun Wang]], ChemElectroChem. None(None)] 2024. https://doi.org/10.1002/celc.202300805  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/celc.202300805][pdf]])
     
Abstract Integrating plasmonic features as an emerging strategy for enhancing electrocatalysis for the carbon dioxide reduction reaction (CO 2 RR). The key parameters responsible for the enhanced electrocatalysis performance are the local heating, the hot carriers, and near‐field enhancement induced by localized surface plasmon resonance (LSPR, that is, plasmonic) excitation. This review provides a concise overview of the fundamental mechanism of CO 2 RR, detailing the generation and decay of plasmonic and the energy transfer dynamics between plasmonic nanostructures and adsorbates. It further involves recent progress in plasmonic‐assisted electrocatalysis for CO 2 RR, including experimental and theoretical research to decipher plasmonic mechanisms. Finally, it ends with an insightful discussion of the existing challenges and potential future directions in this field.    

    

** Recent progress of 3d transition metal as single-atom catalysts for electrochemical CO2 reduction to CO   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcou.2024.102690")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391243406"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391243406"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391243406"))][Get cited by]]

OpenAlex: https://openalex.org/W4391243406 (Open access: True)
    
[[https://openalex.org/A5012289270][Song Lu]], [[https://openalex.org/A5004557076][Sachin Chavan]], [[https://openalex.org/A5004580655][Zhixin Yu]], Journal of CO2 Utilization. 80(None)] 2024. https://doi.org/10.1016/j.jcou.2024.102690 
     
Electrochemical carbon dioxide reduction (ECR) presents a promising technology to attain carbon neutrality. Recent studies have indicated that transition metal atoms as single-atom catalysts (SACs) show many advantages in ECR due to their tunable electronic structure, high atom utilization rate, and uniform active site. Among the various reduction products, CO is an important chemical feedstock that can be used in some essential processes such as Fischer-Tropsch, which produces a series of chemicals and fuels. However, few relevant reviews focus on 3d transition atoms as SACs for ECR to CO. In this review, we first emphasize the advantages of SACs and the CO product. Then, we summarize the recent development of SACs (Mn, Fe, Co, Ni, Cu, and Zn) in ECR to CO, focusing on the configurations of the active center. Finally, we briefly propose suggestions for future advancement of transition metal SACs for ECR to CO.    

    

** Interface Engineering of Cu2o/In(Oh)3 for Efficient Solar-Driven Co2 Electrochemical Reduction to Syngas   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4704994")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391178525"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391178525"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391178525"))][Get cited by]]

OpenAlex: https://openalex.org/W4391178525 (Open access: False)
    
[[https://openalex.org/A5018892762][Juan Wang]], [[https://openalex.org/A5041107353][Jinglian Huang]], [[https://openalex.org/A5091947916][Siyuan Dong]], [[https://openalex.org/A5034165158][Shuangyan Li]], [[https://openalex.org/A5042300381][Bingna Zheng]], [[https://openalex.org/A5047646288][Yun Yang]], [[https://openalex.org/A5066213432][Shun Wang]], [[https://openalex.org/A5006346575][Dajie Lin]], [[https://openalex.org/A5076545740][Tingjie Mao]], [[https://openalex.org/A5060906740][Huile Jin]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4704994 
     
Electrochemical carbon dioxide reduction reaction (CO2RR) holds greater promise for converting CO2 into value-added chemicals, but designing and manufacturing efficient CO2RR catalysts remains desirable but challenging. Here, the Cu2O/In(OH)3 with heterojunction interface was prepared as an efficient CO2RR electrocatalysts. The optimized Cu2O/In(OH)3-1:1 stabilizes over a wide range of potentials to generate syngas (hydrogen/carbon monoxide, H2/CO) at a ratio of 2:1, and the total Faraday efficiency (FE) remains close to 100%. However, the ratio of syngas will change to 1:1 when the Cu/In ratio becomes 1:2. In addition, creatively using solar energy to drive the CO2RR system can directly and efficiently achieve the conversion of solar energy to chemical energy (syngas). Moreover, in-situ experiments show that part of Cu+ is converted to Cu during the CO2RR process, and In(OH)3 remains stable. This work highlights an efficient electrocatalyst for producing syngas based on interface engineering.    

    

** Operando Identification of Carbon-confined SnOx Nanodots Dynamics during CO2-to-formate Electrolysis   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-3853964/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391227764"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391227764"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391227764"))][Get cited by]]

OpenAlex: https://openalex.org/W4391227764 (Open access: True)
    
[[https://openalex.org/A5038741162][Zheng Jiang]], [[https://openalex.org/A5018878652][Jianing Mao]], [[https://openalex.org/A5032925772][Bingbao Mei]], [[https://openalex.org/A5090717104][Shuai Yang]], [[https://openalex.org/A5068006098][Jianrong Zeng]], [[https://openalex.org/A5073162955][Fanfei Sun]], [[https://openalex.org/A5081501159][Wei Chen]], [[https://openalex.org/A5010194502][Fei Song]], No host. None(None)] 2024. https://doi.org/10.21203/rs.3.rs-3853964/v1  ([[https://www.researchsquare.com/article/rs-3853964/latest.pdf][pdf]])
     
Abstract Electrocatalytic carbon dioxide reduction reaction (CO2RR) using tin oxide-based catalysts holds significant potential for producing formate products from renewable energy, while obscurely quantification of structure changes in local configuration hinders the development of highly active and robust electrocatalysts. Herein, the operando spectroscopy revealed the quantitatively oxygen-released behavior in tin oxide nanostructure of the graphene confined SnOx nanodots (rGO@SnO x ND) under the reduction potentials, which promotes the SnOx lattice modulation by the Sn cluster and the adsorption of *OCHO intermediate by increasing the charge density. The controllable reduction degree in rGO@SnO x ND among CO2RR facilitates the excellent exceptional performance of the maximum formate partial current density of 567 mA cm −2 with 96.5 % selectivity and a 50 h long-term stability in flow-cell. These findings show that the controllable oxygen vacancies regulation determines the yield of formate, further emphasizing the importance of operando spectrosopy characterization to understand the dynamic surface structure-performance relationship.    

    

** Efficient photocatalytic overall water splitting for hydrogen evolution and CO2 reduction with SiCP4 allotrope monolayers   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159440")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391064993"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391064993"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391064993"))][Get cited by]]

OpenAlex: https://openalex.org/W4391064993 (Open access: False)
    
[[https://openalex.org/A5051449133][Yi-tong Yin]], [[https://openalex.org/A5083167888][Chuan‐Lu Yang]], [[https://openalex.org/A5015983532][Xiaohu Li]], [[https://openalex.org/A5053333192][Yu‐Liang Liu]], [[https://openalex.org/A5067960438][Wenkai Zhao]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159440 
     
Two-dimensional metal-free photocatalysts are catching the attention of researchers. Here, we present several allotrope SiCP4 monolayers with high stability, high carrier mobility, and excellent photocatalytic performance. Using a searching method based on the universal structure predictor evolutionary xtallography, together with assessing the energy and thermodynamic stabilities, and matching the potentials of band edges with the photocatalytic conditions for achieving overall water splitting, we successfully identify 5 highly favorable configurations (including the previously reported one) from a pool of 1056 allotrope SiCP4 monolayers. The results show that the largest solar-to-hydrogen efficiency of the considered monolayers can reach 21.89 %, while a high mobility of 2.7677 × 105 cm2 V−1 s−1 is observed, both are superior to those of the previously reported one. The Gibbs free energies for hydrogen or oxygen evolutions, and CO2 reduction reactions indicate they are thermodynamically feasible. Moreover, the hydrogen evolution reaction can proceed spontaneously with two allotrope SiCP4 monolayers. Therefore, the newfound allotrope SiCP4 monolayers are expected to have potential applications in the field of photocatalytic water splitting for hydrogen generation and carbon dioxide reduction.    

    

** Redox Processes Involving Oxygen: The Surprising Influence of Redox-Inactive Lewis Acids   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacsau.3c00675")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391100399"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391100399"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391100399"))][Get cited by]]

OpenAlex: https://openalex.org/W4391100399 (Open access: True)
    
[[https://openalex.org/A5023555296][Davide Lionetti]], [[https://openalex.org/A5076674179][Sandy Suseno]], [[https://openalex.org/A5037374157][Angela A. Shiau]], [[https://openalex.org/A5002354165][Graham de Ruiter]], [[https://openalex.org/A5004911977][Theodor Agapie]], JACS Au. None(None)] 2024. https://doi.org/10.1021/jacsau.3c00675  ([[https://pubs.acs.org/doi/pdf/10.1021/jacsau.3c00675][pdf]])
     
Metalloenzymes with heteromultimetallic active sites perform chemical reactions that control several biogeochemical cycles. Transformations catalyzed by such enzymes include dioxygen generation and reduction, dinitrogen reduction, and carbon dioxide reduction–instrumental transformations for progress in the context of artificial photosynthesis and sustainable fertilizer production. While the roles of the respective metals are of interest in all these enzymatic transformations, they share a common factor in the transfer of one or multiple redox equivalents. In light of this feature, it is surprising to find that incorporation of redox-inactive metals into the active site of such an enzyme is critical to its function. To illustrate, the presence of a redox-inactive Ca2+ center is crucial in the Oxygen Evolving Complex, and yet particularly intriguing given that the transformation catalyzed by this cluster is a redox process involving four electrons. Therefore, the effects of redox inactive metals on redox processes–electron transfer, oxygen- and hydrogen-atom transfer, and O–O bond cleavage and formation reactions–mediated by transition metals have been studied extensively. Significant effects of redox inactive metals have been observed on these redox transformations; linear free energy correlations between Lewis acidity and the redox properties of synthetic model complexes are observed for several reactions. In this Perspective, these effects and their relevance to multielectron processes will be discussed.    

    

** Molecular understanding of the critical role of alkali metal cations in initiating CO2 electroreduction on Cu(100) surface   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-44896-x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391022908"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391022908"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391022908"))][Get cited by]]

OpenAlex: https://openalex.org/W4391022908 (Open access: True)
    
[[https://openalex.org/A5032631479][Zhichao Zhang]], [[https://openalex.org/A5088591085][Hengyu Li]], [[https://openalex.org/A5038226323][Yangfan Shao]], [[https://openalex.org/A5051784756][Lin Gan]], [[https://openalex.org/A5055954152][Feiyu Kang]], [[https://openalex.org/A5080132089][Wenhui Duan]], [[https://openalex.org/A5015539284][Heine Anton Hansen]], [[https://openalex.org/A5070982282][Jianbao Li]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-44896-x  ([[https://www.nature.com/articles/s41467-024-44896-x.pdf][pdf]])
     
Molecular understanding of the solid-liquid interface is challenging but essential to elucidate the role of the environment on the kinetics of electrochemical reactions. Alkali metal cations (M+), as a vital component at the interface, are found to be necessary for the initiation of carbon dioxide reduction reaction (CO2RR) on coinage metals, and the activity and selectivity of CO2RR could be further enhanced with the cation changing from Li+ to Cs+, while the underlying mechanisms are not well understood. Herein, using ab initio molecular dynamics simulations with explicit solvation and enhanced sampling methods, we systematically investigate the role of M+ in CO2RR on Cu surface. A monotonically decreasing CO2 activation barrier is obtained from Li+ to Cs+, which is attributed to the different coordination abilities of M+ with *CO2. Furthermore, we show that the competing hydrogen evolution reaction must be considered simultaneously to understand the crucial role of alkali metal cations in CO2RR on Cu surfaces, where H+ is repelled from the interface and constrained by M+. Our results provide significant insights into the design of electrochemical environments and highlight the importance of explicitly including the solvation and competing reactions in theoretical simulations of CO2RR.    

    

** Improved Production of Astaxanthin from Haematococcus pluvialis Using a Hybrid Open–Closed Cultivation System   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/app14031104")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391316403"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391316403"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391316403"))][Get cited by]]

OpenAlex: https://openalex.org/W4391316403 (Open access: True)
    
[[https://openalex.org/A5065756625][Young-Il An]], [[https://openalex.org/A5013286196][T.H. Kim]], [[https://openalex.org/A5028160966][Hwa-Kun Byeon]], [[https://openalex.org/A5075430918][Vijay Rayamajhi]], [[https://openalex.org/A5059501045][Ji–Hyun Lee]], [[https://openalex.org/A5036449609][Sang-Mok Jung]], [[https://openalex.org/A5068754390][Hyun Woung Shin]], Applied sciences. 14(3)] 2024. https://doi.org/10.3390/app14031104  ([[https://www.mdpi.com/2076-3417/14/3/1104/pdf?version=1706515086][pdf]])
     
Haematococcus species are rich sources of the antioxidant astaxanthin and have good potential for carbon dioxide reduction. A variety of culture systems for these microalgae are currently in development, but clearly profitable approaches have yet to be reported. Open outdoor culture is currently the only feasible culture system for producing large amounts of biomass. In this study, based on laboratory results, the cultivation of Haematococcus was divided into two stages: a green stage characterised by cell growth, and a red stage characterised by astaxanthin accumulation. For mass culture, we adopted a hybrid open–closed pond system for astaxanthin production. The open culture system was shown to produce approximately 50 kg (dry weight) of biomass per culture at an average rate of 0.51 g L−1, with 0.52 μg mL−1 of astaxanthin content in a 12 -m3 water tank. As large amounts of microalgal bioproducts are in high demand, inexpensive open outdoor culture methods should be adopted as an alternative to costly closed photobioreactors. Although the levels of biomass and astaxanthin production were found to be 30% lower in the field than in the laboratory in this study, the basic data obtained in this research may be useful for lowering astaxanthin production costs.    

    

** Pulse Electrolysis Turns on CO2 Methanation through N‐Confused Cupric Porphyrin   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202315922")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391358933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391358933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391358933"))][Get cited by]]

OpenAlex: https://openalex.org/W4391358933 (Open access: False)
    
[[https://openalex.org/A5088850707][Han‐Xun Wei]], [[https://openalex.org/A5073096623][Xiao Feng Li]], [[https://openalex.org/A5042955462][Zhendong Zheng]], [[https://openalex.org/A5052313810][Huadong Yuan]], [[https://openalex.org/A5005852469][Long Xiao]], [[https://openalex.org/A5019954363][Kun Feng]], [[https://openalex.org/A5018047125][Jingshu Hui]], [[https://openalex.org/A5032261407][Zhao Deng]], [[https://openalex.org/A5038560095][Mutian Ma]], [[https://openalex.org/A5039059630][Jian Cheng]], [[https://openalex.org/A5032562076][Daqi Song]], [[https://openalex.org/A5020812796][Fenglei Lyu]], [[https://openalex.org/A5010968064][Jun Zhong]], [[https://openalex.org/A5089647465][Yang Peng]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202315922 
     
Breaking the D4h symmetry in the square‐planar M‐N4 configuration of macrocycle molecular catalysts has witnessed enhanced electrocatalytic activity, but at the expense of electrochemical stability. Herein, we hypothesize that the lability of the active Cu‐N3 motifs in the N‐confused copper (II) tetraphenylporphyrin (CuNCP) could be overcome by applying pulsed potential electrolysis (PPE) during electrocatalytic carbon dioxide reduction. We find that applying PPE can indeed enhance the CH4 selectivity on CuNCP by 3 folds to reach the partial current density of 170 mA cm‐2 at >60% Faradaic efficiency (FE) in flow cell. However, combined ex‐situ X‐ray diffraction (XRD), transmission electron microscope (TEM), and in‐situ X‐ray absorption spectroscopy (XAS), infrared (IR), Raman, scanning electrochemical microscopy (SECM) characterizations reveal that, in a prolonged time scale, the decomplexation of CuNCP is unavoidable, and the promoted water dissociation under high anodic bias with lowered pH and enriched protons facilitates successive hydrogenation of *CO on the irreversibly reduced Cu nanoparticles, leading to the improved CH4 selectivity. As a key note, this study signifies the adaption of electrolytic protocol to the catalyst structure for tailoring local chemical environment towards efficient CO2 reduction.    

    

** Interfacial microenvironment effects on electrochemical CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148944")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057924"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057924"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057924"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057924 (Open access: False)
    
[[https://openalex.org/A5034321189][Xianlang Chen]], [[https://openalex.org/A5033098099][Chunhua Chen]], [[https://openalex.org/A5058091201][Yuyao Wang]], [[https://openalex.org/A5038379970][Zhengyu Pan]], [[https://openalex.org/A5029892501][Junjie Chen]], [[https://openalex.org/A5074623897][Yuyang Xu]], [[https://openalex.org/A5017195907][Liehuang Zhu]], [[https://openalex.org/A5064322695][Tongyang Song]], [[https://openalex.org/A5025855204][Rongrong Li]], [[https://openalex.org/A5092477785][Liang Chen]], [[https://openalex.org/A5046377738][Ji-Qing Lu]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.148944 
     
Electrochemical reduction of carbon dioxide (ECR) powered by renewable energy has the potential to utilize the intermittent renewable electric energy, alleviate the problem of excessive CO2 emissions and yield high value-added chemicals. Despite the intrinsic activity of the well-designed catalysts, subtle changes in the electrode–electrolyte interface will have a significant impact on the overall reaction. The electrode and its microenvironment together determine the ECR performance. Revealing the relationship between the microenvironment of the catalyst-electrolyte interface and the ECR performance is critical for explaining the reaction mechanism and controlling the reaction process accurately. To maximize the catalytic performance includes the activity, selectivity and stability, the fundamental understanding of the interfacial microenvironment should be clarified as important as the intrinsic properties of the catalyst. Researches on the microenvironment in ECR have been gradually launched while the comprehensive discussion is scarcely. In this review, the interfacial microenvironment changes affected by multiple influence factors including the electrolyte effects (cation effect, anion effect, local pH, electrolyte type and concentration), morphological effects (tip effect, confinement effect), catalyst surface modification (surface hydrophobicity, chemical and electronic state) and electrolyzers improvement (gas diffusion electrode, membrane electrode reaction microenvironment control) are illustrated. Finally, some perspectives are offered on the basis of understanding the connection of catalytic activity and the interfacial microenvironment, these insights obtained can be applied for better control the CO2 reduction and rational design reactors.    

    

** Photocatalytic CO2 reduction co‐catalyzed by ionic liquids   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301454")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391218414"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391218414"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391218414"))][Get cited by]]

OpenAlex: https://openalex.org/W4391218414 (Open access: False)
    
[[https://openalex.org/A5093785956][Lisa Eisele]], [[https://openalex.org/A5093785957][Wilaiwan Chaikhan]], [[https://openalex.org/A5034473563][Samar Batool]], [[https://openalex.org/A5022928359][Alexey Cherevan]], [[https://openalex.org/A5011010095][Dominik Eder]], [[https://openalex.org/A5067964483][Katharina Bica-Schröder]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301454 
     
Efficiently generating C1 building blocks from environmentally friendly carbon sources, such as through photocatalytic CO2 reduction, is essential for fostering a sustainable circular economy. The pursuit of gentle catalytic activation methods has yielded powerful catalysts that can be synergistically employed alongside various reaction media to enhance overall performance. Herein, we elucidate the influence of diverse imidazolium‐based ionic liquids as additives for visible‐light‐driven CO2reduction with ruthenium(II)‐ and rhenium(I)‐bipyridine complexes. Our investigation reveals that incorporating ionic liquids into traditional solvents at concentrations below 10% can markedly boost CO production while suppressing H2 generation. The best results were obtained for the highly basic ionic liquid [C2mim][OAc], resulting in a substantial rise in CO formation from 0.3 µmol/h to 5.4 µmol/h and an increase in turnover number from 3 to 59. This study underscores the cooperative influence of imidazolium‐based ionic liquids on CO2 photoreduction while circumventing their use as primary solvents, thus offering a promising avenue for sustainable chemical synthesis.    

    

** Electrochemical Water Oxidation and CO2 Reduction with a Nickel Molecular Catalyst   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29030578")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391175526"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391175526"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391175526"))][Get cited by]]

OpenAlex: https://openalex.org/W4391175526 (Open access: True)
    
[[https://openalex.org/A5034075774][Hengxin Jian]], [[https://openalex.org/A5009739042][Mengyu Lu]], [[https://openalex.org/A5053269877][Zheng Haowen]], [[https://openalex.org/A5035054349][Shuai Yan]], [[https://openalex.org/A5017467760][M. Wang]], Molecules. 29(3)] 2024. https://doi.org/10.3390/molecules29030578  ([[https://www.mdpi.com/1420-3049/29/3/578/pdf?version=1706102395][pdf]])
     
Mimicking the photosynthesis of green plants to combine water oxidation with CO2 reduction is of great significance for solving energy and environmental crises. In this context, a trinuclear nickel complex, [NiII3(paoH)6(PhPO3)2]·2ClO4 (1), with a novel structure has been constructed with PhPO32− (phenylphosphonate) and paoH (2-pyridine formaldehyde oxime) ligands and possesses a reflection symmetry with a mirror plane revealed by single-crystal X-ray diffraction. Bulk electrocatalysis demonstrates that complex 1 can homogeneously catalyze water oxidation and CO2 reduction simultaneously. It can catalyze water oxidation at a near-neutral condition of pH = 7.45 with a high TOF of 12.2 s−1, and the Faraday efficiency is as high as 95%. Meanwhile, it also exhibits high electrocatalytic activity for CO2 reduction towards CO with a TOF of 7.84 s−1 in DMF solution. The excellent electrocatalytic performance of the water oxidation and CO2 reduction of complex 1 could be attributed to the two unique µ3-PhPO32− bridges as the crucial factor for stabilizing the trinuclear molecule as well as the proton transformation during the catalytic process, while the oxime groups modulate the electronic structure of the metal centers via π back-bonding. Therefore, apart from the cooperation effect of the three Ni centers for catalysis, simultaneously, the two kinds of ligands in complex 1 can also synergistically coordinate the central metal, thereby significantly promoting its catalytic performance. Complex 1 represents the first nickel molecular electrocatalyst for both water oxidation and CO2 reduction. The findings in this work open an avenue for designing efficient molecular electrocatalysts with peculiar ligands.    

    

** Electrochemical CO2 reduction properties of boron-doped diamond powder   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.diamond.2024.110821")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391074415"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391074415"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391074415"))][Get cited by]]

OpenAlex: https://openalex.org/W4391074415 (Open access: False)
    
[[https://openalex.org/A5087328578][Yudai Miyake]], [[https://openalex.org/A5011491287][Takeshi Kondo]], [[https://openalex.org/A5025835486][Atsushi Otake]], [[https://openalex.org/A5054069544][Yasuaki Einaga]], [[https://openalex.org/A5035857145][Takeo Tojo]], [[https://openalex.org/A5058873695][Makoto Yuasa]], Diamond and Related Materials. 142(None)] 2024. https://doi.org/10.1016/j.diamond.2024.110821 
     
The electrochemical CO2 reduction reaction (CO2RR) properties of boron-doped diamond powder (BDDP) were investigated. A BDDP-painted electrode was prepared by casting BDDP ink on the surface of a BDD thin-film electrode as a current collector. The CO2RR properties of the BDDP-painted electrode were compared to those of conventional BDD thin-film electrodes, which were prepared directly on a conductive silicon wafer substrate by the microwave plasma-assisted chemical vapor deposition method. The result of the electrolysis at −1.8 V vs. Ag/AgCl in 0.5 M KCl catholyte showed that the BDDP-painted electrode was superior to the BDD thin-film electrode because it produced a large amount of products (formic acid and carbon monoxide) at a low overpotential. The highest performance of the CO2RR in the BDDP-painted electrode was achieved with the BDDP with high boron doping and high sp2 carbon content. We considered that structural defects, boron doping level, and sp2 carbon content influenced the reactivity for CO2 reduction. Therefore, the BDDP-painted electrodes should be useful not only for the production of a large-size electrode but also for efficient CO2RR.    

    

** Review for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v1/review3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057005"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057005"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057005"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057005 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v1/review3 
     
No abstract    

    

** Review for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v1/review5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057105"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057105"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057105"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057105 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v1/review5 
     
No abstract    

    

** Review for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057004"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057004"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057004"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057004 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v2/review1 
     
No abstract    

    

** Review for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v2/review3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057130"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057130"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057130"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057130 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v2/review3 
     
No abstract    

    

** Review for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v1/review4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057107"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057107"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057107"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057107 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v1/review4 
     
No abstract    

    

** Review for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057123"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057123"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057123"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057123 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v1/review2 
     
No abstract    

    

** Review for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391056983"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391056983"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391056983"))][Get cited by]]

OpenAlex: https://openalex.org/W4391056983 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v1/review1 
     
No abstract    

    

** Review for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v2/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057020"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057020"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057020"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057020 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v2/review2 
     
No abstract    

    

** Boosting the photocatalytic CO2 reduction activity of g-C3N4 by acid modification   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.126577")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391293841"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391293841"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391293841"))][Get cited by]]

OpenAlex: https://openalex.org/W4391293841 (Open access: False)
    
[[https://openalex.org/A5001481325][Licheng Zhou]], [[https://openalex.org/A5060064406][Jianping Ao]], [[https://openalex.org/A5036016529][Zhi Wang]], [[https://openalex.org/A5090883975][Zhenhong Huang]], [[https://openalex.org/A5077865481][Zhaoyi Xu]], [[https://openalex.org/A5043067897][Xiaofeng Wu]], [[https://openalex.org/A5090407065][Zhenmin Cheng]], [[https://openalex.org/A5081915993][Kangle Lv]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.126577 
     
Graphitic carbon nitride (g-C3N4 denoted as CN) is a typical organic polymeric semiconductor photocatalyst for CO2 reduction to produce solar fuels. In this study, the effect of phosphoric acid (H3PO4) modification on the property and photocatalytic performance of CN towards CO2 reduction was systematically studied. It was found that modification of CN with phosphoric acid (CNP photocatalyst) caused a reduced band gap width and negatively shifted conduction band (CB) potential. The photoreactivity of the optimized photocatalyst (CNP0.75) for CO production rate reaches 35.66 μmolg-1h−1, which is 4.38 times higher than that of CN sample with a CO evolution rate of only 8.14 μmolg-1h−1. The enhanced photoreativity of g-C3N4 towards CO2 reduction after phosphoric acid modification is ascribed to the combined effects of enhanced adsorption, stimulated charge separation and improved reduction ability of CB electrons. The positive effect of acid modification on the enhanced photocatalytic activity of CN was further observed by sulfuric acid (H2SO4) modification and hydrochloric acid (HCl) modification, suggesting the versatility of the method. The present study provides a novel way in preparation of high efficient g-C3N4 photocatalyst for CO2 conversion and utilization.    

    

** Progress in design and preparation of multi-atom catalysts for photocatalytic CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40843-023-2698-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391035964"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391035964"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391035964"))][Get cited by]]

OpenAlex: https://openalex.org/W4391035964 (Open access: True)
    
[[https://openalex.org/A5034762794][Zhonghao Wang]], [[https://openalex.org/A5078365590][Guojun Zou]], [[https://openalex.org/A5017792494][Jae Hyung Park]], [[https://openalex.org/A5072000825][Kan Zhang]], Science China Materials. None(None)] 2024. https://doi.org/10.1007/s40843-023-2698-5  ([[https://link.springer.com/content/pdf/10.1007/s40843-023-2698-5.pdf][pdf]])
     
Photocatalytic CO2 reduction towards various fuels is of significant interest under the background of mitigating the global warming induced by CO2 emission and lowering the depletion of fossil fuels. However, state-of-the-art photocatalysts still suffer from sluggish reaction dynamics and frustrated product selectivity, especially for C2+ generations, which are of great interest for industrial applications. Over the past decades, comprehensive research on solar-driven CO2 reduction has consistently unveiled some encouraging results in meaningful pathways and architectural design of active sites over photocatalysts. This review highlights the recent advances in boosting photocatalytic CO2 reduction of atomically dispersed catalysts via engineered active sites, including two separated active sites, paired dual-active sites, and nanoclusters based on the configuration of active sites. Both the mechanism of CO2 activation over active sites and advanced characterization methods are discussed in detail. Particularly, in consideration of the wide gap between fundamental research and practical applications, the integrations of experimental and theoretical results are analyzed to realize the underlying structure-activity relationships as well as promising selectivity toward target products. Finally, the remaining challenges in the field are outlined, and inquisitive perspectives with a focus on the rational design of active sites and mechanistic investigation are proposed.    

    

** Carbon nitride based nanoarchitectonics for nature-inspired photocatalytic CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.pmatsci.2024.101242")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391065107"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391065107"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391065107"))][Get cited by]]

OpenAlex: https://openalex.org/W4391065107 (Open access: True)
    
[[https://openalex.org/A5034611872][Aathira M. Sadanandan]], [[https://openalex.org/A5052047304][Jae‐Hun Yang]], [[https://openalex.org/A5082458137][Vidyasagar Devtade]], [[https://openalex.org/A5083095509][Gurwinder Singh]], [[https://openalex.org/A5067986273][Nithinraj Panangattu Dharmarajan]], [[https://openalex.org/A5081997866][Mohammed Fawaz]], [[https://openalex.org/A5064283824][Jang Mee Lee]], [[https://openalex.org/A5011143396][Ehsan Tavakkoli]], [[https://openalex.org/A5016258825][Chung-Hwan Jeon]], [[https://openalex.org/A5031279154][Prashant Kumar]], [[https://openalex.org/A5043332402][Ajayan Vinu]], Progress in Materials Science. 142(None)] 2024. https://doi.org/10.1016/j.pmatsci.2024.101242 
     
Drawing inspiration from the natural process of photosynthesis found in plant leaves, scientists are exploring the use of photocatalysis to convert carbon dioxide (CO2) into valuable products using solar light and water. Photocatalytic CO2 conversion has emerged as one of the efficient green approaches to revitalize the environment from greenhouse gas pollution. Owing to its visible-range band gap, non-toxicity, ease of synthesis at economic costs and stability under light irradiation, g-C3N4 has emerged as the most explored photocatalyst. However, due to rampant exciton recombination owing to poor electrical conductivity, the efficiency of CO2 reduction falls short for g-C3N4 in its pure/pristine form. Therefore, the structural manoeuvre of g-C3N4 materials using N-rich configurations, heteroatom/single-atom doping and hybridization with various functional materials including metal oxides/sulfides, perovskite halides and metal complexes has been adopted, thereby overcoming their inherent drawbacks in photocatalytic CO2 reduction. In this timely review, we present an overview of the recent advances in surface/interface engineering of carbon nitrides for the conversion of CO2 to fuels and useful chemical by-products. More importance is given to the critical evaluation of surface manipulation in carbon nitrides and how it amplifies and affects their photocatalytic properties in CO2 reduction. Finally, we provide a comprehensive outlook into the future directions of these functionalised carbon nitrides for various applications. We strongly believe that this unique review will offer new knowledge on the surface property relationship of carbon nitride-based materials and their impact on enhancing their performance in various photocatalytic reactions and further create new opportunities for them in various areas.    

    

** Author response for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v2/response1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057062"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057062"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057062"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057062 (Open access: False)
    
[[https://openalex.org/A5013522313][John Cruz]], [[https://openalex.org/A5043425264][Anna Balog]], [[https://openalex.org/A5030958308][Péter S. Tóth]], [[https://openalex.org/A5090655937][Gábor Bencsik]], [[https://openalex.org/A5001143524][Gergely F. Samu]], [[https://openalex.org/A5075233752][Csaba Janáky]], No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v2/response1 
     
No abstract    

    

** Boosting effect of encapsulated polyoxometalates in the photocatalytic CO2 reduction activity of MOF-545   
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391010819"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391010819"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391010819"))][Get cited by]]

OpenAlex: https://openalex.org/W4391010819 (Open access: False)
    
[[https://openalex.org/A5007162321][K. Talbi]], [[https://openalex.org/A5088937428][Amanda L. Robinson]], [[https://openalex.org/A5025771580][Youven Benseghir]], [[https://openalex.org/A5024792637][María Gómez-Mingot]], [[https://openalex.org/A5062221634][Marc Fontecave]], [[https://openalex.org/A5039753949][Pierre Mialane]], [[https://openalex.org/A5032549164][Caroline Mellot‐Draznieks]], [[https://openalex.org/A5064073246][Anne Dolbecq]], No host. None(None)] 2023. None 
     
No abstract    

    

** Decision letter for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057087"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057087"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057087"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057087 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v1/decision1 
     
No abstract    

    

** Decision letter for "Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction"   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057006"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057006"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057006"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057006 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.1039/d3ey00222e/v2/decision1 
     
No abstract    

    

** Hollow cubic TiO2 loaded with copper and gold nanoparticles for photocatalytic CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173589")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391188424"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391188424"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391188424"))][Get cited by]]

OpenAlex: https://openalex.org/W4391188424 (Open access: False)
    
[[https://openalex.org/A5015387098][Xiaowan Mu]], [[https://openalex.org/A5059899541][Qiuhua Xu]], [[https://openalex.org/A5025372320][Yu Xie]], [[https://openalex.org/A5091156984][Yongcun Ma]], [[https://openalex.org/A5081194034][Zhiqi Zhang]], [[https://openalex.org/A5057296315][Zhen Shen]], [[https://openalex.org/A5077857374][Yue Guo]], [[https://openalex.org/A5002529301][Jian Yu]], [[https://openalex.org/A5033369944][Saira Ajmal]], [[https://openalex.org/A5060396142][Wei Zhang]], [[https://openalex.org/A5070902056][Jie Zhao]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.173589 
     
A simple photodeposition method is used to prepare Cu and Au nanoparticles modified TiO2 nanocomposites. The phase composition of the catalyst is determined by x-ray diffraction. The mutual synergistic effects of Cu and Au are analyzed using x-ray photoelectron spectroscopy, photoluminescence spectroscopy and UV diffuse reflectance spectroscopy. The results indicate that the TiO2 is anatase structure with hollow cubic morphology, which enhances the utilization of visible light and improves the photocatalytic performance compared with P25. The Cu0.7Au0.3/TiO2 has the highest carrier separation efficiency and the best photocatalytic performance with a CO yield of 6.08 umol g-1 h-1, which is about four times higher than that of TiO2 (1.56 umol g-1 h-1). The aforementioned results indicate that the photocatalytic activity for CO2 reduction is greatly enhanced by the addition of modest quantities of Cu and Au NPs. During the photocatalytic process, the presence of Au NPs absorbs visible light and modulates the surface structure of electrons, while Cu serves as an electron sink, hence promoting efficient separation of electron-hole pairs. Utilizing the distinct benefits of bimetal and their robust interactions is a viable and efficacious approach for boosting the photocatalytic activity.    

    

** Photocatalytic CO2 reduction activity of nickel-based polyoxometalates and POM@MOF-545 composites   
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391077147"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391077147"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391077147"))][Get cited by]]

OpenAlex: https://openalex.org/W4391077147 (Open access: False)
    
[[https://openalex.org/A5007162321][K. Talbi]], [[https://openalex.org/A5039753949][Pierre Mialane]], [[https://openalex.org/A5042493681][F. Simón Hidalgo]], [[https://openalex.org/A5086372340][Albert Solé‐Daura]], [[https://openalex.org/A5032549164][Caroline Mellot‐Draznieks]], [[https://openalex.org/A5064073246][Anne Dolbecq]], No host. None(None)] 2023. None 
     
No abstract    

    

** Understanding of strain effect on Mo-based MXenes for electrocatalytic CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159501")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391151075"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391151075"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391151075"))][Get cited by]]

OpenAlex: https://openalex.org/W4391151075 (Open access: False)
    
[[https://openalex.org/A5047060524][Dongyue Gao]], [[https://openalex.org/A5043595651][Yue Xu]], [[https://openalex.org/A5023826377][Zhe Li]], [[https://openalex.org/A5016142397][Yadong Yu]], [[https://openalex.org/A5084234940][Caiyan Yu]], [[https://openalex.org/A5054091259][Yi Fang]], [[https://openalex.org/A5023704274][Yang Huang]], [[https://openalex.org/A5022913125][Chengchun Tang]], [[https://openalex.org/A5069736534][Zhonglu Guo]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159501 
     
No abstract    

    

** Supramolecular assemblies of Cu(II) with tetraphenylethene-imidazole ligand for tuning photocatalytic CO2 reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cc05514k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391095667"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391095667"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391095667"))][Get cited by]]

OpenAlex: https://openalex.org/W4391095667 (Open access: False)
    
[[https://openalex.org/A5084146972][Zhao‐Feng Qiu]], [[https://openalex.org/A5049078993][Peng Wang]], [[https://openalex.org/A5063880073][Xiaoyu Zhang]], [[https://openalex.org/A5071844040][Jiaqi Chen]], [[https://openalex.org/A5046531665][Kai-Yang Zhang]], [[https://openalex.org/A5047060569][Xiangyu Lu]], [[https://openalex.org/A5064397304][Yi Zhao]], [[https://openalex.org/A5036287984][Wei‐Yin Sun]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d3cc05514k 
     
Cu(II) supramolecular assemblies [Cu2(tipe)2(H2O)2](NO3)4·2.5H2O (CuN4) and [Cu2Cl4(tipe)(CH3CN)]·H2O (CuN2Cl2) (tipe = 1,1,2,2-tetrakis(4-(imidazole-1-yl)phenyl)ethene) were synthesized and utilized for photocatalytic CO2 reduction. CuN4 exhibits CO production up to 891 μmol gcat-1 with selectivity...    

    
