#+filetags: CO2RR
#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Thu Feb  8 00:43:07 2024

Found 26 results from 2024-02-01 to 2024-02-08
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Effective reduction on flame soot via plasma coupled with carbon dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391451084
:TOPICS: Chemical Kinetics of Combustion Processes, Catalytic Nanomaterials, Applications of Plasma in Medicine and Biology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jhazmat.2024.133669")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391451084"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391451084"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391451084"))][Get cited by]]

OpenAlex: https://openalex.org/W4391451084 (Open access: False)
    
[[https://openalex.org/A5035298690][Dandan Qi]], [[https://openalex.org/A5043356374][Mingxiao Chen]], [[https://openalex.org/A5016557228][Kaixuan Yang]], [[https://openalex.org/A5017350291][Tianjiao Li]], [[https://openalex.org/A5004130467][Yaoyao Ying]], [[https://openalex.org/A5071659496][Dong Liu]], Journal of Hazardous Materials. None(None)] 2024. https://doi.org/10.1016/j.jhazmat.2024.133669 
     
This study explored the impact of non-thermal plasma and CO2 on the flame soot characteristics within the diffusion flames. We analyzed on flame structures that were diluted with either CO2 or N2, temperature distributions, and soot characteristics, both in the presence and absence of plasma. Due to the higher specific heat capacity of CO2 compared to N2, the optical observations consistently showed lower temperatures in flames diluted with CO2 as compared to those diluted with N2. The inclusion of plasma and carbon dioxide resulted in the lowest soot concentration, indicating that plasma coupled with CO2 has a synergistic inhibitory effect on soot emissions. The findings revealed that when CO2 was used to dilute the flames and the oxygen concentration was low, the soot nanostructure appeared amorphous. Raman results showed that the level of graphitization observed in soot particles from CO2 dilution flames was lower than that from N2 dilution flames. In the presence of plasma and CO2, the soot obtained exhibited the shortest fringe length and the highest fringe tortuosity. Significant correlations were observed between the nanostructure of soot and its reactivity. The combined application of plasma and CO2 proved to be effective in reducing the soot carbonization degree. Soot particles produced during incomplete combustion not only reduce the performance of the combustion system but also cause significant environmental pollution and health problems. Oxygen-fuel combustion integrated with O2/CO2 as an oxidant instead of O2/N2 has drawn extensive attention due to its unique advantages in reducing soot and NOx generation and combining with CO2 recycling technologies. This topic provides a detailed and profound understanding of the mechanisms behind soot suppression through the combined effects of CO2 addition and plasma activation.    

    

* Understanding the Interplay of the Brønsted Acidity of Catalyst Ancillary Groups and the Solution Components in Iron-porphyrin-Mediated Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391464343
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.3c10127")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391464343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391464343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391464343"))][Get cited by]]

OpenAlex: https://openalex.org/W4391464343 (Open access: False)
    
[[https://openalex.org/A5032471432][Ana Sonea]], [[https://openalex.org/A5093845864][Nicholas R. Crudo]], [[https://openalex.org/A5000268359][Jeffrey J. Warren]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.3c10127 
     
The rapid and efficient conversion of carbon dioxide (CO2) to carbon monoxide (CO) is an ongoing challenge. Catalysts based on iron-porphyrin cores have emerged as excellent electrochemical mediators of the two proton + two electron reduction of CO2 to CO, and many of the design features that promote function are known. Of those design features, the incorporation of Brønsted acids in the second coordination sphere of the iron ion has a significant impact on catalyst turnover kinetics. The Brønsted acids are often in the form of hydroxyphenyl groups. Herein, we explore how the acidity of an ancillary 2-hydroxyphenyl group affects the performance of CO2 reduction electrocatalysts. A series of meso-5,10,15,20-tetraaryl porphyrins were prepared where only the functional group at the 5-meso position has an ionizable proton. A series of cyclic voltammetry (CV) experiments reveal that the complex with −OMe positioned para to the ionizable −OH shows the largest CO2 reduction rate constants in acetonitrile solvent. This is the least acidic −OH of the compounds surveyed. The turnover frequency of the −OMe derivative can be further improved with the addition of 4-trifluoromethylphenol to the solution. In contrast, the iron-porphyrin complex with −CF3 positioned opposite the ionizable −OH shows the smallest CO2 reduction rate constants, and its turnover frequency is less enhanced with the addition of phenols to the reaction solutions. The origin of this effect is rationalized based on kinetic isotope effect experiments and density functional calculations. We conclude that catalysts with weaker internal acids coupled with stronger external acid additives provide superior CO2 reduction kinetics.    

    

* Single-atom catalysts for electrocatalytic carbon dioxide reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391488466
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/b978-0-323-95237-8.00003-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391488466"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391488466"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391488466"))][Get cited by]]

OpenAlex: https://openalex.org/W4391488466 (Open access: False)
    
[[https://openalex.org/A5022870015][Subhash Chandra Shit]], [[https://openalex.org/A5036665795][Indranil Mondal]], Elsevier eBooks. None(None)] 2024. https://doi.org/10.1016/b978-0-323-95237-8.00003-3 
     
The electrochemical CO2 reduction reaction carries tremendous significance to tackle the exponential rising of CO2 level in the atmosphere. The development of different classes of electrocatalyst materials emerged with more understanding of the catalyst features, reaction mechanism, catalytic efficiency, and product selectivity using modern analytical tools (such as in situ techniques). Single-atom catalysts (SACs) are a new class of material that allows atom-by-atom utilization in the catalytic process, thereby influencing the CO2 reduction efficiency and product selectivity in more precise manner. In this chapter, we highlight the fundamental of CO2 electroreduction, including general mechanism for varied product formation, electrolyzer component, operational parameter, and development of SACs electrode material for CO2 reduction.    

    

* Modulation of active center distance of hybrid perovskite for boosting photocatalytic reduction of carbon dioxide to ethylene  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391527790
:TOPICS: Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1073/pnas.2318970121")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391527790"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391527790"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391527790"))][Get cited by]]

OpenAlex: https://openalex.org/W4391527790 (Open access: False)
    
[[https://openalex.org/A5060340851][Linjuan Li]], [[https://openalex.org/A5018013187][Dong Xu]], [[https://openalex.org/A5042815155][Xiankui Xu]], [[https://openalex.org/A5085521958][Zheng Tian]], [[https://openalex.org/A5069616452][Xue Zhou]], [[https://openalex.org/A5077769841][Shenbo Yang]], [[https://openalex.org/A5011328145][Zhonghai Zhang]], Proceedings of the National Academy of Sciences of the United States of America. 121(7)] 2024. https://doi.org/10.1073/pnas.2318970121 
     
Solar-driven photocatalytic CO 2 reduction is an energy-efficient and sustainable strategy to mitigate CO 2 levels in the atmosphere. However, efficient and selective conversion of CO 2 into multi-carbon products, like C 2 H 4 , remains a great challenge due to slow multi-electron-proton transfer and sluggish C–C coupling. Herein, a two-dimensional thin-layered hybrid perovskite is fabricated through filling of oxygen into iodine vacancy in pristine DMASnI 3 (DMA = dimethylammonium). The rational-designed DMASnI 3 (O) induces shrinkage of active sites distance and facilitates dimerization of C–C coupling of intermediates. Upon simulated solar irradiation, the DMASnI 3 (O) photocatalyst achieves a high selectivity of 74.5%, corresponding to an impressive electron selectivity of 94.6%, for CO 2 to C 2 H 4 conversion and an effective C 2 H 4 yield of 11.2 μmol g −1 h −1 . In addition, the DMASnI 3 (O) inherits excellent water stability and implements long-term photocatalytic CO 2 reduction to C 2 H 4 in a water medium. This work establishes a unique paradigm to convert CO 2 to C 2+ hydrocarbons in a perovskite-based photocatalytic system.    

    

* Electrochemical reduction of carbon dioxide to produce formic acid coupled with oxidative conversion of biomass  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391560295
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.01.062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391560295"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391560295"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391560295"))][Get cited by]]

OpenAlex: https://openalex.org/W4391560295 (Open access: False)
    
[[https://openalex.org/A5075320040][Jiashuai Liu]], [[https://openalex.org/A5025761344][Yifan Wang]], [[https://openalex.org/A5040497392][Zhiwei Dai]], [[https://openalex.org/A5014377577][Daihong Gao]], [[https://openalex.org/A5013713303][Xuebing Zhao]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.01.062 
     
Electrochemical reduction of CO2 (CO2RR) has become a research hot spot in recent years in the context of carbon neutrality. HCOOH is one of the most promising products obtained by electrochemical reduction of CO2 due to its high energy value as estimated by market price per energy unit and wide application in chemical industry. Biomass is the most abundant renewable resource in the natural world. Coupling biomass oxidative conversion with CO2RR driven by renewable electricity would well achieve carbon negativity. In this work, we comprehensively reviewed the current research progress on CO2RR to produce HCOOH and coupled system for conversion of biomass and its derivatives to produce value-added products. Sn- and Bi-based electrocatalysts are discussed for CO2RR with regards to the structure of the catalyst and reaction mechanisms. Electro-oxidation reactions of biomass derived sugars, alcohols, furan aldehydes and even polymeric components of lignocellulose were reviewed as alternatives to replace oxygen evolution reaction (OER) in the conventional electrolysis process. It was recommended that to further improve the efficiency of the coupled system, future work should be focused on the development of more efficient and stable catalysts, careful design of the electrolytic cells for improving the mass transfer and development of environment-friendly processes for recovering the formed formate and biomass oxidation products.    

    

* Applications of X-ray Spectroscopy in Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391537296
:TOPICS: Characterization of Shale Gas Pore Structure, Powder Diffraction Analysis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1142/9789811284649_0005")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391537296"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391537296"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391537296"))][Get cited by]]

OpenAlex: https://openalex.org/W4391537296 (Open access: False)
    
[[https://openalex.org/A5055601807][Indrajit Shown]], [[https://openalex.org/A5064071602][Wei-Fu Chen]], [[https://openalex.org/A5059407034][Kuei‐Hsien Chen]], [[https://openalex.org/A5061993606][Li‐Chyong Chen]], World scientific series in nanoscience and nanotechnology. None(None)] 2024. https://doi.org/10.1142/9789811284649_0005 
     
No abstract    

    

* Recent Progress in Electrochemical CO2 Reduction at Different Electrocatalyst Materials  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391384166
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/pr12020303")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391384166"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391384166"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391384166"))][Get cited by]]

OpenAlex: https://openalex.org/W4391384166 (Open access: True)
    
[[https://openalex.org/A5093224291][Marcela Miranda Barcelos]], [[https://openalex.org/A5008749661][Maria de Lourdes Soprani Vasconcellos]], [[https://openalex.org/A5061398997][Josimar Ribeiro]], Processes. 12(2)] 2024. https://doi.org/10.3390/pr12020303  ([[https://www.mdpi.com/2227-9717/12/2/303/pdf?version=1706698654][pdf]])
     
Given the environmental problems caused by burning fossil fuels, it is believed that converting carbon dioxide (CO2) into chemical inputs is a great ally to generating clean energy. In this way, investigative studies related to electrochemical CO2 reduction (CO2RE) concerning the behavior of metal catalysts have received attention about the processes involved. CO2RE can be an important tool to mitigate the presence of this gas in the Earth’s atmosphere. Given these considerations, in this review, we report the main catalysts used to act as CO2RE. Among them, we emphasize catalysts based on Ni, Zn, and Cu, which encompass the main properties related to the electrochemical conversion of CO2. Regarding the Cu-based catalyst, it presents high conversion efficiency but low selectivity. Furthermore, we also describe the main mechanisms related to the electrochemical conversion of CO2.    

    

* Role of Flexible Operation of a Wastewater Treatment Plant in the Reduction of Its Indirect Carbon Dioxide Emissions—A Case Study  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391432666
:TOPICS: Integration of Renewable Energy Systems in Power Grids, Hydrogen Energy Systems and Technologies, Wireless Sensor Networks for Data Analysis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/w16030483")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391432666"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391432666"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391432666"))][Get cited by]]

OpenAlex: https://openalex.org/W4391432666 (Open access: True)
    
[[https://openalex.org/A5093838468][Nilüfer Topuz]], [[https://openalex.org/A5080809344][Frank Alsmeyer]], [[https://openalex.org/A5037952789][Hasancan Okutan]], [[https://openalex.org/A5036968337][Hermann-Josef Roos]], Water. 16(3)] 2024. https://doi.org/10.3390/w16030483  ([[https://www.mdpi.com/2073-4441/16/3/483/pdf?version=1706841349][pdf]])
     
The increasing share of renewables in electricity grids comes with a challenge of energy surpluses and deficits, which needs be handled by demand side management (DSM) and storage options. Within this approach, wastewater treatment plants (WWTPs), with flexible energy consumption and production processes and storage units, can contribute to stabilizing the grids and integrating more renewables. In this study, the operation of a real WWTP was optimized by mixed integer linear programming (MILP) to minimize its indirect carbon dioxide (CO2) emissions. The operation of the WWTP was shown to be flexible in following the CO2 emission factor of the electricity grid, which was possible with the utilization of the WWTP’s storage units and flexible co-substrate feeding. As a result, by changing only the operational behavior of the WWTP, its indirect CO2 emissions decreased by 4.8% due to the higher share of renewables in the electricity grid. The CO2 emissions were shown to decrease further up to 6.9% by adding virtual storage units.    

    

* Metal-organic framework composites for electrochemical CO2 reduction reaction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391515522
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.126532")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391515522"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391515522"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391515522"))][Get cited by]]

OpenAlex: https://openalex.org/W4391515522 (Open access: False)
    
[[https://openalex.org/A5068670506][Kayode Adesina Adegoke]], [[https://openalex.org/A5008185576][Joshua O. Ighalo]], [[https://openalex.org/A5000341829][Jeanet Conradie]], [[https://openalex.org/A5091087628][Chinemerem Ruth Ohoro]], [[https://openalex.org/A5002534407][James F. Amaku]], [[https://openalex.org/A5019730915][Kabir O. Oyedotun]], [[https://openalex.org/A5041855090][Nobanathi Wendy Maxakato]], [[https://openalex.org/A5042386386][Kovo G. Akpomie]], [[https://openalex.org/A5057047276][Emmanuel Sunday Okeke]], [[https://openalex.org/A5018863848][Chijioke Olisah]], [[https://openalex.org/A5021557399][Alhadji Malloum]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.126532 
     
Carbon dioxide (CO2) levels in the atmosphere are quickly increasing as a consequence of anthropogenic activities, which present grave hazards and dangerous circumstances to not only humanity but also the ecosystem. Currently, electrochemical CO2 conversion to chemical/fuels remains one of the best methods for minimizing CO2 concentrations. Metal-organic frameworks (MOFs) composite materials have been considered as new class of highly-performed electrocatalysts for CO2 reduction reaction (CO2RR) due to their wide surface area, higher porosity, chemical tunability and excellent stability. This article presents major approaches for electrochemical CO2RR to value-added product. These were followed by discussing the recent advancements in MOF composite electrocatalysts for CO2RR including active sites MOF-supported electrocatalysts, metal-nanoparticles-supported MOFs, conductive supported MOFs composites, and polyoxometalate-based MOF composites. Lastly, some challenges currently facing MOF composites for CO2RR as well as anticipated future advances were discussed. Research hotspot lies in the creation of highly effective CO2RR electrocatalyst such as ligand engineering in MOFs. It is believed that the current study will contribute to accelerating the fabrication of efficient MOF composite materials for abating the CO2 emission in the ecosystem and to highlight the necessity for further research to address significant environmental sustainability concerns.    

    

* MXenes for CO2 reduction: a promising choice  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391488885
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/b978-0-323-95515-7.00011-x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391488885"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391488885"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391488885"))][Get cited by]]

OpenAlex: https://openalex.org/W4391488885 (Open access: False)
    
[[https://openalex.org/A5033369944][Saira Ajmal]], [[https://openalex.org/A5087525540][Anuj Kumar]], [[https://openalex.org/A5078487092][Tuan Anh Nguyen]], [[https://openalex.org/A5002637244][Ghulam Yasin]], Elsevier eBooks. None(None)] 2024. https://doi.org/10.1016/b978-0-323-95515-7.00011-x 
     
Fast industrialization and urban growth emit significant amounts of hazardous CO2, which not only produces environmental problems but also causes illness all over the world. Several technologies for purifying air and water have been developed over the last two decades, but they have all failed due to high costs, poor effectiveness, and the creation of secondary contaminants. The photochemical and electrochemical conversion of CO2 into energy-rich molecules is a novel method that can aid in environmental rehabilitation while also meeting the world’s expanding energy demands. These techniques, however, necessitate extremely selective, energetic, and long-lasting catalysts. Scientists have investigated numerous keen and multifunctional materials for the conversion of CO2 pollution into useful compounds in this area. MXenes, a type of two-dimensional (2D) material made of transition metal nitrides, carbides, and carbonitrides, have engrossed attention because of their extraordinary physicochemical, mechanical, and electrochemical properties. This chapter focuses on CO2 conversion by photochemical and electrochemical methods to valuable products, emphasizing MXene-based materials and their catalytic activity, as well as future prospects.    

    

* Efficient reduction of CO2 to CO by CdAl-LDHs nanostructured electrocatalysts in ionic liquids  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391543242
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jphotochem.2024.115518")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391543242"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391543242"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391543242"))][Get cited by]]

OpenAlex: https://openalex.org/W4391543242 (Open access: False)
    
[[https://openalex.org/A5029837106][Fang Tan]], [[https://openalex.org/A5031213658][Tianxia Liu]], [[https://openalex.org/A5088260235][Jian Ping Zhang]], Journal of Photochemistry and Photobiology A: Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jphotochem.2024.115518 
     
Layered bimetallic hydroxides are at the forefront of current research in electrocatalytic materials. Although there is considerable research on various bimetallic hydroxides, the study of bimetallic hydroxides for electrocatalytic reduction of carbon dioxide is limited. In this paper, cadmium-aluminum layered bimetallic hydroxide nanoparticles (CdAl-LDHs) were prepared using a simple electrochemical deposition method. The prepared CdAl-LDHs was characterized in detail, and its potential application as an electrocatalyst was discussed. CdAl-LDHs prepared using different methods showed different selectivity in the electrocatalytic reduction of CO2 to CO. The nanomaterial exhibits excellent CO selectivity in a reaction chamber using 2 %-BMIM(PF6)(1-butyl-3-methylimidazolium hexafluorophosphate)/DMF(N-N dimethyl formamide) as the electrolyte. The CdAl-LDHs prepared by electrochemical deposition exhibited a maximum CO partial current density of 22.13 mA cm−2 with a remarkable CO Faraday efficiency (FE) of 99.71 %, which is comparable to or even higher than that of noble metal catalysts. This high selectivity for CO indicates its potential as an alternative to expensive noble metal catalysts. Moreover, the catalyst demonstrated high stability over 30 h of continuous operation with stable FE of around 99 % and a current density of around 10.5 mA cm−2, with minimal degradation during the entire reaction cycle. In addition, the catalyst showed a low HER current density of less than 0.1 mA cm−2 at all tested potentials, indicating that the catalyst maintains a high level of CO2 conversion over the entire range of tested potentials. This suggests its great potential for industrial applications.    

    

* Haeckelite mediated reduction of CO2 by molecular hydrogen. A DFT study  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391487109
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.comptc.2024.114499")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391487109"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391487109"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391487109"))][Get cited by]]

OpenAlex: https://openalex.org/W4391487109 (Open access: False)
    
[[https://openalex.org/A5050072832][Wilmer Esteban Vallejo Narváez]], [[https://openalex.org/A5035427789][César Gabriel Vera de la Garza]], [[https://openalex.org/A5085613468][Serguei Fomine]], Computational and Theoretical Chemistry. None(None)] 2024. https://doi.org/10.1016/j.comptc.2024.114499 
     
In this study, we conducted a theoretical exploration of haeckelite-mediated CO2 reduction with molecular hydrogen. We used a haeckelite nanoflake (NF) consisting of 96 carbon atoms passivated with hydrogens to elucidate the reaction mechanism on the 2D surface. The most favorable reaction pathway involves the sequential formation of formic acid, formaldehyde, methanol, and ultimately methane. Notably, formic acid formation is favored over carbon monoxide. Haeckelite-mediated reactions exhibit Gibbs-free activation energies 10 to 40 kcal/mol lower compared to processes without a catalyst. This catalytic effect is attributed to the interaction of H2 with the haeckelite surface, which weakens or breaks the HH bond. This theoretical perspective provides significant insights into carbon-based materials and their potential applications in transforming CO2 into fuels and value-added chemicals.    

    

* Boosting photochemical reduction of CO2 to formic acid catalyzed by porphyrinic MOF-545  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391554925
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2021-07-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391554925"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391554925"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391554925"))][Get cited by]]

OpenAlex: https://openalex.org/W4391554925 (Open access: False)
    
[[https://openalex.org/A5025771580][Youven Benseghir]], [[https://openalex.org/A5086372340][Albert Solé‐Daura]], [[https://openalex.org/A5085164470][Mathis Duguet]], [[https://openalex.org/A5039753949][Pierre Mialane]], [[https://openalex.org/A5024792637][María Gómez-Mingot]], [[https://openalex.org/A5062221634][Marc Fontecave]], [[https://openalex.org/A5064073246][Anne Dolbecq]], [[https://openalex.org/A5032549164][Caroline Mellot‐Draznieks]], No host. None(None)] 2021. None 
     
No abstract    

    

* A Bio‐Inspired Bimetallic Fe‐M Catalyst for Electro‐ and Photochemical CO2 Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391537560
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301705")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391537560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391537560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391537560"))][Get cited by]]

OpenAlex: https://openalex.org/W4391537560 (Open access: False)
    
[[https://openalex.org/A5071052075][Yuhang Yao]], [[https://openalex.org/A5065282041][Jiahui Wu]], [[https://openalex.org/A5055399722][Guiyu Liu]], [[https://openalex.org/A5041022925][Ruijing Zhang]], [[https://openalex.org/A5085810240][Zi‐Shu Yang]], [[https://openalex.org/A5039657597][Song Gao]], [[https://openalex.org/A5071430741][Tai‐Chu Lau]], [[https://openalex.org/A5083162509][Junlong Zhang]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301705 
     
The conversion of CO2 into fuels or commodity chemicals by electrochemical or photochemical reduction is a promising strategy to relieve the ongoing energy crisis and increasing environmental pollution. Inspired by naturally occurring bimetalloenzymes, we have designed hetero‐bimetallic CO2 reduction catalysts (FeM) that involve linking an iron tetraphenylporphyrin (FeP) with a tripyridylamine (TPA) moiety, which provides a distal chelating site for Cu2+ or Zn2+. We found that the introduction of Cu2+ or Zn2+ to FeP greatly enhances its efficiency as a catalyst for the electrochemical reduction of CO2. To gain insights into the observed synergistic effect, we performed mechanistic studies together with density functional theory (DFT) calculations. Our results show that Cu2+ or Zn2+ activates CO2 towards reduction due to its Lewis acidity; it also functions as an oxo acceptor from CO2. FeM also functions as an efficient catalyst for the visible‐light‐driven reduction of CO2 using either [Ru(bpy)3]Cl2 or fac‐Ir(ppy)3 (where bpy = 2,2’‐bipyridine, ppy = 2‐phenylpyridine) as photosensitizer and 1,3‐dimethyl‐2‐phenyl‐2,3‐dihydro‐1H‐benzo[d]imidazole (BIH) as sacrificial reductant. Again, the catalytic efficiency is enhanced by the presence Cu2+ or Zn2+. Our results provide a general strategy for the design of a series of hetero‐bimetallic catalysts for the reduction of CO2.    

    

* Coupled Electrochemical Reduction of CO2 and H+ in the Presence of Substituted 2,2'-Bipyridinium Salts  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391550662
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2023-11-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1134/s107042802311009x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391550662"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391550662"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391550662"))][Get cited by]]

OpenAlex: https://openalex.org/W4391550662 (Open access: False)
    
[[https://openalex.org/A5048834107][E. V. Okina]], [[https://openalex.org/A5083682754][L. A. Klimaeva]], [[https://openalex.org/A5075408705][Д. Б. Чугунов]], [[https://openalex.org/A5049624623][S. G. Kostryukov]], [[https://openalex.org/A5087234431][A. S. Kozlov]], [[https://openalex.org/A5067767641][O. V. Tarasova]], [[https://openalex.org/A5023314423][A. D. Yudina]], Russian Journal of Organic Chemistry. 59(11)] 2023. https://doi.org/10.1134/s107042802311009x 
     
No abstract    

    

* Analysis of the effects of EEDI and EEXI implementation on CO2 emissions reduction in ships  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391559475
:TOPICS: Environmental Impact of Maritime Transportation Emissions, Estimating Vehicle Fuel Consumption and Emissions, Integrated Pollution Prevention and Control Techniques
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.oceaneng.2024.116877")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391559475"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391559475"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391559475"))][Get cited by]]

OpenAlex: https://openalex.org/W4391559475 (Open access: False)
    
[[https://openalex.org/A5029682509][S. H. Lee]], Ocean Engineering. 295(None)] 2024. https://doi.org/10.1016/j.oceaneng.2024.116877 
     
No abstract    

    

* Self-supported copper-based gas diffusion electrodes improve the local CO2 concentration for efficient electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391439692
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11705-024-2392-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391439692"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391439692"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391439692"))][Get cited by]]

OpenAlex: https://openalex.org/W4391439692 (Open access: False)
    
[[https://openalex.org/A5044830523][Azeem Mustafa]], [[https://openalex.org/A5002560306][Bachirou Guene Lougou]], [[https://openalex.org/A5049375655][Yong Shuai]], [[https://openalex.org/A5026704658][Zhijiang Wang]], [[https://openalex.org/A5049094441][Haseeb-ur-Rehman]], [[https://openalex.org/A5020400471][Samia Razzaq]], [[https://openalex.org/A5084139753][Wei Wang]], [[https://openalex.org/A5061893306][Ruming Pan]], [[https://openalex.org/A5014738262][Jiupeng Zhao]], Frontiers of Chemical Science and Engineering. 18(3)] 2024. https://doi.org/10.1007/s11705-024-2392-6 
     
No abstract    

    

* Highly selective electrocatalytic reduction of CO2 to HCOOH over an in-situ derived Ag-loaded Bi2O2CO3 electrocatalyst  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391546693
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3dt04342h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391546693"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391546693"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391546693"))][Get cited by]]

OpenAlex: https://openalex.org/W4391546693 (Open access: True)
    
[[https://openalex.org/A5091351871][Wei Zheng]], [[https://openalex.org/A5084793778][Changlai Wang]], [[https://openalex.org/A5048379858][Jing Chen]], [[https://openalex.org/A5005901099][Chen Shi]], [[https://openalex.org/A5069028297][Zhiyu Lin]], [[https://openalex.org/A5022809443][Minxue Huang]], [[https://openalex.org/A5079879393][Hao Huang]], [[https://openalex.org/A5042856845][Yafei Qu]], [[https://openalex.org/A5008620166][Peichen Wang]], [[https://openalex.org/A5077163216][Haibo Lin]], [[https://openalex.org/A5014087781][Qianwang Chen]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d3dt04342h  ([[https://pubs.rsc.org/en/content/articlepdf/2024/dt/d3dt04342h][pdf]])
     
The electrochemical reduction of CO2 to HCOOH is considered as one of the most appealing routes to alleviate the energy crisis and close the anthropogenic CO2 cycle. However, it remains...    

    

* Highly-exposed copper and ZIF-8 interface enables synthesis of hydrocarbons by electrocatalytic reduction of CO2  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391515357
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.205")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391515357"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391515357"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391515357"))][Get cited by]]

OpenAlex: https://openalex.org/W4391515357 (Open access: False)
    
[[https://openalex.org/A5051918964][Bo Sun]], [[https://openalex.org/A5055556997][Hao Hu]], [[https://openalex.org/A5085590943][Hangchen Liu]], [[https://openalex.org/A5091352802][Jun Guan]], [[https://openalex.org/A5073878947][Kexing Song]], [[https://openalex.org/A5016615882][Changrui Shi]], [[https://openalex.org/A5078897846][Haoyan Cheng]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.205 
     
Electrochemical reduction of CO2 (CO2RR) to fuels and chemicals is a promising route to close the anthropogenic carbon cycle for sustainable society. The Cu-based catalysts in producing high-value hydrocarbons feature unique superiorities, yet challenges remain in achieving high selectivity. In this work, Cu@ZIF-8 NWs with highly-exposed Cu nanowires (Cu NWs) and ZIF-8 interface are synthesized via a surfactant-assisted method. Impressively, Cu@ZIF-8 NWs exhibit excellent stability and a high Faradaic efficiency of 57.5% toward hydrocarbons (CH4 and C2H4) at a potential of -0.7 V versus reversible hydrogen electrode. Computational calculations combining with experiments reveal the formation of Cu and ZIF-8 interface optimizes the adsorption of reaction intermediates, particularly stabilizing the formation of *CHO, thereby enabling efficient preference for hydrocarbons. This work highlights the potential of constructing metals and MOFs heterogeneous interfaces to enhance catalytic properties and offers valuable insights for the design of highly efficient CO2RR catalysts.    

    

* CoTCPP integrates with BiOBr microspheres for improved solar-driven CO2 reduction performance  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391482249
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.gee.2024.01.008")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391482249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391482249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391482249"))][Get cited by]]

OpenAlex: https://openalex.org/W4391482249 (Open access: True)
    
[[https://openalex.org/A5024087962][Lina Li]], [[https://openalex.org/A5044544424][Yi Zhang]], [[https://openalex.org/A5012315318][Gaopeng Liu]], [[https://openalex.org/A5019424718][Tiange Wei]], [[https://openalex.org/A5043175640][Junze Zhao]], [[https://openalex.org/A5007372368][Bin Wang]], [[https://openalex.org/A5000411615][Mengxia Ji]], [[https://openalex.org/A5063346330][Yuanbin She]], [[https://openalex.org/A5043452223][Jiexiang Xia]], [[https://openalex.org/A5040665735][Huaming Li]], Green Energy & Environment. None(None)] 2024. https://doi.org/10.1016/j.gee.2024.01.008 
     
CO2 photoreduction into carbon-based chemicals has been considered as an appropriate way to alleviate the energy issue and greenhouse effect. Herein, the 5, 10, 15, 20-tetra (4-carboxyphenyl) porphyrin cobalt(II) (CoTCPP) has been integrated with BiOBr microspheres and formed the CoTCPP/BiOBr composite. The as-prepared CoTCPP/BiOBr-2 shows optimized photocatalytic performance for CO2 conversion into CO and CH4 upon irradiation with 300 W Xe lamp, which is 2.03 and 2.58 times compared to that of BiOBr, respectively. The introduced CoTCPP significantly enhanced light absorption properties, promoted rapid separation of photogenerated carriers and boosted the chemisorption of CO2 molecules. The metal Co2+ at the center of the porphyrin molecules also acts as adsorption center for CO2 molecules, boosting the CO2 convert into CO and CH4. The possible mechanism of CO2 photoreduction was explored by in-situ FT-IR spectra. This work offers a new possibility for the preparation of advance photocatalysts.    

    

* Reduction of CO2 emissions in oil pipelines through conversion of hydraulic energy into electrical energy using an HPRT  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391473709
:TOPICS: Application of Diagnostic Techniques in Oil Wells, Non-Destructive Techniques Based on Eddy Current Testing
:PUBLICATION_DATE: 2023-08-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48072/2447-2069.rpc.2023.066")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391473709"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391473709"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391473709"))][Get cited by]]

OpenAlex: https://openalex.org/W4391473709 (Open access: False)
    
[[https://openalex.org/A5093847985][Jhon Ussa]], [[https://openalex.org/A5093847986][Heidy Monroy]], [[https://openalex.org/A5093847987][Ricardo Oicat]], [[https://openalex.org/A5093847988][Walter Gastelbondo]], No host. None(None)] 2023. https://doi.org/10.48072/2447-2069.rpc.2023.066 
     
No abstract    

    

* Enhanced reduction of CO2 to CH4 by novel mesoporous Ru-Fe3O4/CeOx-SiO2 catalyst in a fixed bed reactor  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391401348
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.22541/au.170669628.88839658/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391401348"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391401348"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391401348"))][Get cited by]]

OpenAlex: https://openalex.org/W4391401348 (Open access: False)
    
[[https://openalex.org/A5038350796][Swarnil Roy]], [[https://openalex.org/A5035330707][Dilip Kumar Mondal]], No host. None(None)] 2024. https://doi.org/10.22541/au.170669628.88839658/v1 
     
A novel mesoporous Ru-Fe3O4/CeOx-SiO2 (Ce3+/Ce4+, x=1.64) catalyst was synthesized via excess solution impregnation of Ru and Fe3O4 nanoparticles (NPs) on ceria-loaded mesoporous SBA-15. The reduction of CO2 to methane was performed in the presence of H2 over the catalyst in a fixed bed reactor. CO2 reduction was found to be 82% at 0.25 wt% ruthenium loading, 2.5 wt% iron loading, 573 K temperature, 20 bar pressure, 3000 mL.g.-1. h-1 gas hour space velocity and H2 to CO2 mole ratio of 5:1. The close contact between ruthenium and Fe3O4 nanoparticles facilitated the reduction of CO2 through hydrogen spill-over effect and ceria NPs acted as a promoter for reduction reaction. The catalysts were characterized thoroughly using CO chemisorption, BET, TPR, TPD, XRD, SEM, HR TEM, ICP-AES and XPS techniques. Optimal process conditions could render much higher CO2 conversion efficacy for selective methane synthesis in comparison with previous scientific investigations.    

    

* Electrocatalytic CO2 reduction enhanced by Sb doping in MOF-derived carbon-supported Bi-based materials  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391470101
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.126520")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391470101"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391470101"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391470101"))][Get cited by]]

OpenAlex: https://openalex.org/W4391470101 (Open access: False)
    
[[https://openalex.org/A5015913918][Shuangchen Ma]], [[https://openalex.org/A5011811503][Kai Wu]], [[https://openalex.org/A5052772891][Shuaijun Fan]], [[https://openalex.org/A5060002817][Ying Liu]], [[https://openalex.org/A5063859389][Chen Ju]], [[https://openalex.org/A5043819511][Jing Ma]], [[https://openalex.org/A5009056923][Lijuan Yang]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.126520 
     
Amidst the myriad catalysts employed in the electrochemical reduction of CO2, bimetallic materials stand out for their augmented catalytic activity and product selectivity. Bismuth (Bi), recognized for its marked selectivity towards formic acid along with attributes of low toxicity, cost-effectiveness, and widespread accessibility, emerges as a highly promising candidate with extensive research underway. Nonetheless, the catalytic attributes of Sb/Bi bimetallic composite materials incorporating antimony (Sb) elements have received limited attention. This study presents a successful synthesis of carbon-supported Sb/Bi bimetallic composite materials via the MOF templating approach, followed by a comprehensive exploration of their electrocatalytic properties for CO2 reduction. The investigation underscores the predominant integration of Sb elements in alloy configuration within the catalytic matrix. Trace Sb doping (≤3.1 %) emerges as a means to effectively suppress the formation of *H species while concurrently promoting *OCHO species, leading to a substantial elevation in the formate selectivity of Bi-based materials. In contrast, excessive Sb doping, by exacerbating *H formation, inadvertently intensifies the HER process, thereby unfavorably influencing formate generation. Promisingly, in comparison to Bi@C materials, Sb/Bi@C materials doped with minute quantities of Sb showcase enhanced electrode stability and an extended catalytic lifespan within the context of electrochemical operating conditions, which can be attributed to the fact that the introduction of Sb can significantly strengthen the spherical physical structure of carbon-borne nanomaterials on the surface of Bi@C materials. Through an amalgamation of empirical characterization and DFT calculations, this inquiry elucidates the pivotal role assumed by Sb incorporation in Bi materials, consequently advancing the realm of CO2RR. The research emphasizes a strategy of phase and structure engineering, which can provide valuable insights for the development of high-performance electrocatalysts not only in CO2RR but also in other fields.    

    

* CO2 reduction and the production of high-value biomaterials using waste medium by Rhodobacter sphaeroides  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391392848
:TOPICS: Microalgae as a Source for Biofuels Production, Biomass and Bioenergy in the Bioeconomy
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.22541/au.170668064.45726075/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391392848"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391392848"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391392848"))][Get cited by]]

OpenAlex: https://openalex.org/W4391392848 (Open access: False)
    
[[https://openalex.org/A5070147321][Juyong Park]], [[https://openalex.org/A5024759593][Jaeyoung Yu]], [[https://openalex.org/A5044603410][Ngoc Nguyen]], [[https://openalex.org/A5033875887][Yang‐Hoon Kim]], [[https://openalex.org/A5072652940][Jiho Min]], No host. None(None)] 2024. https://doi.org/10.22541/au.170668064.45726075/v1 
     
The purple non-sulfur photosynthetic bacteria, Rhodobacter sphaeroides, are capable of growing under a variety of environmental conditions. R. sphaeroides wastewater treatment has received considerable attention, since it can simultaneously realize wastewater purification and biomass recycling. In addition, poly-β-Hydroxybutyrate (PHB), a biopolymer that can be used as a biodegradable thermoplastic material for waste management strategies, and other polyhydroxyalkanoates (PHAs) are accumulated by many bacteria as energy and carbon reserve material. In this study, the used culture media of Escherichia coli and Saccharomyces cerevisiae were reutilized to grow R. sphaeroides to produce PHB and reduce carbon dioxide. Moreover when using used media, photopigments, such as bacteriochlorophyll and carotenoid, was also synthesized. Finally, the co-fermentation of R. sphaeroides and S. cerevisiae showed the potential of enhancing ethanol production with higher yield than the single use of S. cerevisiae. Therefore, this approach provides a low-cost and eco-friendly process that uses waste media to fix carbon dioxide, and produce high-value biomaterials.    

    

* Defect and Nanostructure Engineering of Polymeric Carbon Nitride for Visible-Light-Driven CO2 Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391537483
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cjsc.2024.100245")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391537483"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391537483"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391537483"))][Get cited by]]

OpenAlex: https://openalex.org/W4391537483 (Open access: False)
    
[[https://openalex.org/A5014381445][Ziruo Zhou]], [[https://openalex.org/A5061195656][Wei Guo]], [[https://openalex.org/A5012152145][Tingyu Yang]], [[https://openalex.org/A5051769353][Dandan Zheng]], [[https://openalex.org/A5027738164][Yuanxing Fang]], [[https://openalex.org/A5049356478][Xiahui Lin]], [[https://openalex.org/A5061785514][Yidong Hou]], [[https://openalex.org/A5043430188][Guigang Zhang]], [[https://openalex.org/A5080757684][Sibo Wang]], Chinese Journal of Structural Chemistry. None(None)] 2024. https://doi.org/10.1016/j.cjsc.2024.100245 
     
Sunlight-induced photocatalytic carbon dioxide (CO2) reduction to energy-rich chemicals by metal-free polymeric carbon nitride (CN) semiconductor is a promising tactic for sustained solar fuel production. However, the reaction efficiency of CO2 photoreduction is restrained seriously by the rapid recombination of photogenerated carriers on CN polymer. Herein, we incorporate the 2-aminopyridine molecule with strong electron-withdrawing group into the skeleton edge of CN layers through a facile one-pot thermal polymerization strategy using urea as the precursor, which renders the modified carbon nitride (ACN) with extended optical harvesting, abundant nitrogen defects and ultrathin nanosheet structure. Consequently, the ACN photocatalyst with desirable structural features attains enhanced separation and migration of photoexcited charge carriers. Under visible light irradiation with Co(bpy)32+ as a cocatalyst, the optimized ACN sample manifests a high CO2 deoxygnative reduction activity and high stability, providing a CO yielding rate of 17 μmol·h-1, which is significantly higher than that of pristine CN. The key intermediates engaged in CO2 photoreduction reaction are determined by the in situ diffuse reflectance infrared Fourier transform spectroscopy, which sponsors the construction of the possible photocatalytic CO2 reduction mechanism on the ACN nanosheets.    

    

* Harnessing deep transient testing for reservoir characterization and CO2 emission reduction in challenging geological settings  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391383558
:TOPICS: Advanced Techniques in Reservoir Management, Hydraulic Fracturing in Shale Gas Reservoirs, Drilling Fluid Technology and Well Integrity
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ptlrs.2024.01.014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391383558"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391383558"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391383558"))][Get cited by]]

OpenAlex: https://openalex.org/W4391383558 (Open access: True)
    
[[https://openalex.org/A5088653693][Eghbal Motaei]], [[https://openalex.org/A5054946215][Tarek Al-Arbi Omar Ganat]], [[https://openalex.org/A5093828346][Khairul Azhar]], [[https://openalex.org/A5067559759][Hamoud Al-Hadrami]], Petroleum Research. None(None)] 2024. https://doi.org/10.1016/j.ptlrs.2024.01.014 
     
No abstract    

    
