#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Sun Mar 17 00:47:29 2024

Found 31 results from 2024-03-10 to 2024-03-17
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Improving the Roughness of Copper Working Electrode Through Electroless Deposition for Carbon Dioxide Reduction Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392621229
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4753683")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392621229"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392621229"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392621229"))][Get cited by]]

OpenAlex: https://openalex.org/W4392621229 (Open access: False)
    
[[https://openalex.org/A5064779642][Yu‐Hsu Chang]], [[https://openalex.org/A5094106791][Watsananan T. Thienprasert]], [[https://openalex.org/A5085717612][N. Manjula]], [[https://openalex.org/A5045158889][Ninie Suhana Abdul Manan]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4753683 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Bioinspired Binickel Catalyst for Carbon Dioxide Reduction: The Importance of Metal–ligand Cooperation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392638780
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacsau.4c00047")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392638780"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392638780"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392638780"))][Get cited by]]

OpenAlex: https://openalex.org/W4392638780 (Open access: True)
    
[[https://openalex.org/A5079496622][Yao Xiao]], [[https://openalex.org/A5088851400][Fusheng Xie]], [[https://openalex.org/A5020753697][Zhang Hong-tao]], [[https://openalex.org/A5020808232][Ming‐Tian Zhang]], JACS Au. None(None)] 2024. https://doi.org/10.1021/jacsau.4c00047  ([[https://pubs.acs.org/doi/pdf/10.1021/jacsau.4c00047][pdf]])
     
No abstract    

    

* Accelerated screening of gas diffusion electrodes for carbon dioxide reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392649765
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-m8dtd")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392649765"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392649765"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392649765"))][Get cited by]]

OpenAlex: https://openalex.org/W4392649765 (Open access: True)
    
[[https://openalex.org/A5041734836][Ryan J. R. Jones]], [[https://openalex.org/A5059376070][Ying‐Chih Lai]], [[https://openalex.org/A5030566949][Dan Guevarra]], [[https://openalex.org/A5073163389][Kevin Kan]], [[https://openalex.org/A5033925671][Joel A. Haber]], [[https://openalex.org/A5037026533][John M. Gregoire]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-m8dtd  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65e75705e9ebbb4db9f75bf1/original/accelerated-screening-of-gas-diffusion-electrodes-for-carbon-dioxide-reduction.pdf][pdf]])
     
The electrochemical conversion of carbon dioxide to chemicals and fuels is expected to be a key sustainability technology. Electrochemical carbon dioxide reduction technologies are challenged by several factors, including the limited solubility of carbon dioxide in aqueous electrolyte as well as the difficulty in utilizing polymer electrolytes. These considerations have driven systems designs to incorporate gas diffusion electrodes (GDEs) to bring the electrocatalyst in contact with both a gaseous reactant/product stream as well as a liquid electrolyte. GDE optimization typically results from manual tuning by select experts. Automated preparation and operation of GDE cells could be a watershed for the systematic study of, and ultimately the development of a materials acceleration platform (MAP) for, catalyst discovery and system optimization. Toward this end, we present the automated GDE (AutoGDE) testing system. Given a catalyst-coated GDE, AutoGDE automates the insertion of the GDE into an electrochemical cell, the liquid and gas handling, the quantification of gaseous reaction products via online mass spectroscopy, and the archiving of the liquid electrolyte for subsequent analysis.    

    

* Synergistic promotion for the performance of photocatalytic carbon dioxide reduction by vacancy engineering and N-doped carbon nanotubes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392659274
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.127063")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392659274"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392659274"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392659274"))][Get cited by]]

OpenAlex: https://openalex.org/W4392659274 (Open access: False)
    
[[https://openalex.org/A5015102287][Min Wang]], [[https://openalex.org/A5001935045][Jing Xie]], [[https://openalex.org/A5027671620][Zhenjiang Lu]], [[https://openalex.org/A5010078147][Fanlin Kong]], [[https://openalex.org/A5005466268][Baolin Liu]], [[https://openalex.org/A5075086500][Zhende Wu]], [[https://openalex.org/A5085766817][Yali Cao]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.127063 
     
The structural devise of photocatalytic materials are closely related to the separation of photogenerated carriers and the transport of charge, which is crucial to enhance the performance of photocatalytic carbon dioxide reduction reaction (CO2RR). Here, a photocatalyst (CdS-SV@Co@NCNT) has been successfully prepared by growing cadmium sulfide nanoparticles with sulfur vacancies on N-doped carbon nanotubes through a simple solvothermal method. The intrinsic electronic structure is regulated by sulfur vacancies to promote photocatalytic activity. Meanwhile, a larger specific surface area of Co@NCNT could expose more reaction sites and shorten the transfer distance of photogenerated carriers. Furthermore, the combination with Co@NCNT could effectively suppress the photocorrosion of CdS. The possible photocatalytic CO2RR path is further speculated by in-situ infrared test results, in which CO2 molecules adsorbed on sulfur vacancies preferentially generate important intermediate COOH*, which is then reduced to CO and CH4. Therefore, it exhibits a high CO yield of 263.3 μmol·g−1·h−1 and trace of CH4 while showing excellent stability. This research provides a novel idea for designing the photocatalysts with highly active and stability for CO2RR.    

    

* Scale-Up Study of Electrochemical Carbon Dioxide Reduction Process Through Data-Driven Modelling  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392666560
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4755410")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392666560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392666560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392666560"))][Get cited by]]

OpenAlex: https://openalex.org/W4392666560 (Open access: False)
    
[[https://openalex.org/A5072654050][G.Q. Zhang]], [[https://openalex.org/A5057337284][Xiaoteng Liu]], [[https://openalex.org/A5062468621][Hanhui Lei]], [[https://openalex.org/A5057307061][Yucheng Wang]], [[https://openalex.org/A5093323800][Denise Bildan]], [[https://openalex.org/A5039412958][Xing Liu]], [[https://openalex.org/A5031191155][Xiangqun Zhuge]], [[https://openalex.org/A5054819836][Zhihong Luo]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4755410 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* 1 nm Tin Oxide Cluster for the Electrochemical Conversion of Carbon Dioxide to Formate at Low Overpotential  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392683413
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1155/2024/1367542")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392683413"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392683413"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392683413"))][Get cited by]]

OpenAlex: https://openalex.org/W4392683413 (Open access: True)
    
[[https://openalex.org/A5066751552][Hyungrae Kim]], [[https://openalex.org/A5000885309][Kang-Hyuk Lee]], [[https://openalex.org/A5004886231][Chan Woo Lee]], International Journal of Energy Research. 2024(None)] 2024. https://doi.org/10.1155/2024/1367542  ([[https://downloads.hindawi.com/journals/ijer/2024/1367542.pdf][pdf]])
     
Due to its cost-effectiveness and high product selectivity, tin oxide has been regarded as a promising catalyst for the electrochemical conversion of CO2 to formate. However, formate production is hindered by the high overpotential; there is a need to reduce the overpotential to enhance energy efficiency and lower electricity cost for the implementation of carbon utilization technology. Here, we report a facile synthesis method for 1 nm-sized SnO2 cluster catalysts, which can be used for CO2-to-formate conversion. SnO2 clusters were prepared through impregnation of porous carbon with a tin precursor solution. The SnO2 clusters showed a low overpotential, generating a current density of 10 mA cm-2 at a potential of -0.34 V vs. RHE in 1 M KOH. They also achieved high Faradaic efficiencies of 90.5% and 81.5% at 200 and 300 mA cm−2, respectively. Their electrocatalytic performance was strongly dependent on the annealing conditions, which affected the particle size, electrochemical active surface area, and metal oxidation state. This paper presents a versatile method for synthesizing metal oxide cluster catalysts, apart from providing insights into the catalytic activity for the electrochemical conversion of CO2 to formate.    

    

* Functionalization of copper for enhanced electrocatalytic reduction of carbon dioxide via ultrashort pulse laser surface processing  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392692145
:TOPICS: Laser Ablation Synthesis of Nanoparticles, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1117/12.3000983")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392692145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392692145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392692145"))][Get cited by]]

OpenAlex: https://openalex.org/W4392692145 (Open access: False)
    
[[https://openalex.org/A5033781038][Graham Kaufman]], [[https://openalex.org/A5053541424][Ahmed El‐Harairy]], [[https://openalex.org/A5034832327][Suchit Sarin]], [[https://openalex.org/A5027405483][Siamak Nejati]], [[https://openalex.org/A5051506809][Jeffrey E. Shield]], [[https://openalex.org/A5040129143][Craig Zuhlke]], No host. None(None)] 2024. https://doi.org/10.1117/12.3000983 
     
No abstract    

    

* Size‐Dependent Carbon Dioxide Reduction Activity of Copper Nanoparticle and Nanocluster Electrocatalysts  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392699583
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cnma.202300575")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392699583"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392699583"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392699583"))][Get cited by]]

OpenAlex: https://openalex.org/W4392699583 (Open access: True)
    
[[https://openalex.org/A5081138591][Tokuhisa Kawawaki]], [[https://openalex.org/A5010708479][Tomoshige Okada]], [[https://openalex.org/A5041850401][Kana Takemae]], [[https://openalex.org/A5093839080][Shiho Tomihari]], [[https://openalex.org/A5043613374][Yuichi Negishi]], ChemNanoMat. None(None)] 2024. https://doi.org/10.1002/cnma.202300575  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cnma.202300575][pdf]])
     
The electrochemical carbon dioxide (CO2) reduction reaction (CRR, which can convert CO2 into useful compounds at room temperature and ambient pressure by using electricity derived from renewable energy source), has been attracting attention in recent years. This is because it can convert CO2 into useful compounds, which is pertinent to establishing a next‐generation recycling‐oriented energy society. However, further improvement of the electrocatalyst is required to improve its activity, selectivity, and durability. Among these, copper (Cu) can synthesize various hydrocarbons from CO2 and has been the most studied electrocatalyst for the CRR over many years. In particular, regarding ligand‐protected Cu particles for the CRR, the size, shape, and ligands of Cu particles prepared by chemical reduction can be precisely controlled. In this review, we summarize previous research on the size‐dependence of the CRR by using Cu particles (nanoparticles and nanoclusters) prepared by liquid‐phase reduction, and discuss the current status of these studies for researchers on the electrochemical CRR.    

    

* Research Status, Challenges, and Future Prospects of Carbon Dioxide Reduction Technology  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392705965
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Capture and Storage Technologies, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.energyfuels.3c04591")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392705965"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392705965"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392705965"))][Get cited by]]

OpenAlex: https://openalex.org/W4392705965 (Open access: False)
    
[[https://openalex.org/A5005895044][Hongtao Dang]], [[https://openalex.org/A5060832414][Bin Guan]], [[https://openalex.org/A5085864513][Junyan Chen]], [[https://openalex.org/A5043144206][Zeren Ma]], [[https://openalex.org/A5076807634][Yujun Chen]], [[https://openalex.org/A5061390975][Jinhe Zhang]], [[https://openalex.org/A5031847334][Zelong Guo]], [[https://openalex.org/A5021080505][Lei Chen]], [[https://openalex.org/A5044930631][Jingqiu Hu]], [[https://openalex.org/A5037690611][Yi Chao]], [[https://openalex.org/A5086702541][Shunyu Yao]], [[https://openalex.org/A5087875241][Zhen Huang]], Energy & Fuels. None(None)] 2024. https://doi.org/10.1021/acs.energyfuels.3c04591 
     
No abstract    

    

* Coupling Electrocatalytic Redox-Active Sites in Three-Dimensional Bimetalloporphyrin-based Covalent Organic Framework for Enhancing Carbon Dioxide Reduction and Oxygen Evolution  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392719172
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00998c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392719172"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392719172"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392719172"))][Get cited by]]

OpenAlex: https://openalex.org/W4392719172 (Open access: False)
    
[[https://openalex.org/A5085352453][Jie Liu]], [[https://openalex.org/A5040900307][Yan‐Xi Tan]], [[https://openalex.org/A5085254274][Jiaping Lin]], [[https://openalex.org/A5041437245][Yangyang Feng]], [[https://openalex.org/A5031804038][Xiang Zhang]], [[https://openalex.org/A5063357611][Enle Zhou]], [[https://openalex.org/A5049053873][Daqiang Yuan]], [[https://openalex.org/A5000029372][Yaobing Wang]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d4ta00998c 
     
Constructing bifunctional covalent organic frameworks (COFs) electrocatalysts to mimic photosynthesis independent of natural sunlight is important for the CO2 recycling. We first construct 3D bifunctional Co/Ni-TPNB-COF containing Ni(II)-porphyrin and Co(II)-porphyrin...    

    

* Two‐Dimensional Crystalline Electrocatalysts for Efficient Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392749022
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Thermoelectric Materials
:PUBLICATION_DATE: 2024-03-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202400009")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392749022"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392749022"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392749022"))][Get cited by]]

OpenAlex: https://openalex.org/W4392749022 (Open access: True)
    
[[https://openalex.org/A5074937842][Lu Dai]], [[https://openalex.org/A5090677167][Jie Zong]], [[https://openalex.org/A5055885143][Lisha Liang]], [[https://openalex.org/A5024172607][Pengfei Li]], ChemElectroChem. None(None)] 2024. https://doi.org/10.1002/celc.202400009  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/celc.202400009][pdf]])
     
Abstract The electrochemical carbon dioxide reduction reaction (eCO 2 RR) can achieve carbon recycling through renewable electrical energy. Before releasing the full potential of eCO 2 RR, the electrocatalysts still need improvement in terms of catalytic activity, selectivity, and durability. Two‐dimensional (2D) crystalline materials show a high aspect ratio with well‐defined crystal structures, which are promising electrocatalysts for eCO 2 RR. In this review, we briefly discuss the typical 2D electrocatalysts for eCO 2 RR. Subsequently, we provide a summary of the different strategies to improve the catalytic performance of 2D crystalline electrocatalysts for creating and modulating active sites. Finally, we end this review with the current challenges and future opportunities of 2D crystalline materials in the eCO 2 RR.    

    

* A quadruple transition metal dichalcogenide for variously synergetic electron behaviors during photocatalytic carbon dioxide reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392752845
:TOPICS: Two-Dimensional Materials, Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159887")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392752845"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392752845"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392752845"))][Get cited by]]

OpenAlex: https://openalex.org/W4392752845 (Open access: False)
    
[[https://openalex.org/A5041438685][Pei Liu]], [[https://openalex.org/A5010212263][Hongyu Chen]], [[https://openalex.org/A5083249621][Caiyuan Zhao]], [[https://openalex.org/A5073887432][Deng Long]], [[https://openalex.org/A5054159069][Weijia Chen]], [[https://openalex.org/A5086873107][Miao Lü]], [[https://openalex.org/A5066365433][Xin Yi Chen]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159887 
     
No abstract    

    

* Corrigendum to “Cu2O/SiC photocatalytic reduction of carbon dioxide to methanol using visible light on lnTaO4” [Mater. Sci. Semicond. Process. 174 (2024) 108235]  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392768040
:TOPICS: Formation and Properties of Nanocrystals and Nanostructures, Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mssp.2024.108313")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392768040"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392768040"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392768040"))][Get cited by]]

OpenAlex: https://openalex.org/W4392768040 (Open access: False)
    
[[https://openalex.org/A5089011196][Babalola Aisosa Oni]], [[https://openalex.org/A5091243470][Samuel Eshorame Sanni]], [[https://openalex.org/A5018891267][Olusegun Stanley Tomomewo]], [[https://openalex.org/A5033624313][Shree Om Bade]], Materials Science in Semiconductor Processing. None(None)] 2024. https://doi.org/10.1016/j.mssp.2024.108313 
     
No abstract    

    

* Continuous Production of Ethylene and Hydrogen Peroxide from Paired Electrochemical Carbon Dioxide Reduction and Water Oxidation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392807699
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202304247")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392807699"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392807699"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392807699"))][Get cited by]]

OpenAlex: https://openalex.org/W4392807699 (Open access: True)
    
[[https://openalex.org/A5083446401][Sotirios Mavrikis]], [[https://openalex.org/A5061076707][Michél K. Nieuwoudt]], [[https://openalex.org/A5013472734][Maximilian Göltz]], [[https://openalex.org/A5094152043][Sophie Ehles]], [[https://openalex.org/A5061772643][Andreas Körner]], [[https://openalex.org/A5019937016][Andreas Hutzler]], [[https://openalex.org/A5094152044][Emeric Fossy]], [[https://openalex.org/A5083107535][Andreas Zervas]], [[https://openalex.org/A5094152045][Oshioriamhe Brai]], [[https://openalex.org/A5088513652][Moritz Wegener]], [[https://openalex.org/A5094152041][Florian Doerrfuss]], [[https://openalex.org/A5094152042][Peter Bouwman]], [[https://openalex.org/A5045696926][Stefan Rosiwal]], [[https://openalex.org/A5043587033][Ling Wang]], [[https://openalex.org/A5024067466][Carlos Ponce de León]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202304247  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/aenm.202304247][pdf]])
     
Abstract Paired electrolysis offers an auspicious strategy for the generation of high‐value chemicals, at both the anode and cathode, in an integrated electrochemical reactor. Through efficient electron utilization, routine product misuse at overlooked electrodes can be prevented. Here, an original paired electrosynthetic system is reported that can convert CO 2 to ethylene (C 2 H 4 ) at the cathode, and water to hydrogen peroxide (H 2 O 2 ) at the anode under a single pass of electric charge. Amongst various investigated copper (Cu) nanomorphologies, the bespoke mixed Cu nanowire/nanoparticle catalyst recorded a peak C 2 H 4 Faraday efficiency ( FE ) of 60% following 370 h of electrolysis at 200 mA cm −2 , while the tailored boron‐doped diamond (BDD) anode accumulated an unprecedented ≈1% w/w of H 2 O 2 in 4 m K 2 CO 3 upon applying 300 mA cm −2 for 10 h. When paired, the dual C 2 H 4 ‐H 2 O 2 electrochemical cell attains a combined FE of 120% for 50 h at 200 mA cm −2 , a combined energy efficiency (EE) of 69%, and a 50% decrease in the overall electrical energy consumption (EEC) compared to the individual electrosynthesis of C 2 H 4 and H 2 O 2 .    

    

* Construction of Au-modified CN-based donor-acceptor system coupled with dual photothermal effects for efficient photoreduction of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392820351
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Nanotechnology and Imaging for Cancer Therapy and Diagnosis
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.090")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392820351"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392820351"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392820351"))][Get cited by]]

OpenAlex: https://openalex.org/W4392820351 (Open access: False)
    
[[https://openalex.org/A5024847508][Xianghai Song]], [[https://openalex.org/A5045338371][Dongsheng He]], [[https://openalex.org/A5045429112][Weiqiang Zhou]], [[https://openalex.org/A5082241382][Yuanfeng Wu]], [[https://openalex.org/A5021687717][Xin Liu]], [[https://openalex.org/A5011238951][Zhi Zhu]], [[https://openalex.org/A5000294498][Pengwei Huo]], [[https://openalex.org/A5035322817][Mei Wang]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.090 
     
Conversion of CO2 into high value-added fuels through the photothermal effect is an effective approach for utilizing solar energy. In this study, we prepared the CN-based photocatalyst Py-CTN-Au with both donor-acceptor (D-A) system and dual photothermal effects using a simple two-step method involving calcination and photo-deposition. Real-time monitoring with a thermal imaging camera revealed that Py-CTN-Au0.5 achieved a maximum stable temperature of 180 °C, which was approximately 1.2 times higher than that of Py-CTN (155 °C) and 1.9 times higher than that of g-CN (95 °C) under the same reaction conditions. Under the optimized reaction conditions, Py-CTN-Au0.5 exhibited a CO release rate of 30.59 umol g−1 after 4 h of reaction, which was 7.3 times higher than that of pure g-CN (4.18 umol g−1). The D-A system not only facilitated the separation and transformation of charge carriers but also induced a photothermal effect to accelerate the photoreduction of CO2. Additionally, the cocatalyst Au nanoparticles (Au NPs) further enhanced the charge carrier dynamics and photothermal effect by increasing the built-in electric field intensity and localized surface plasmon resonance (LSPR) effect, respectively. The dual photothermal effects resulting from the non-radiative photon conversion of the D-A structure and the Au NPs LSPR effect, along with the enhanced charge carrier dynamics, catalyzed the efficient photoreduction of CO2. DFT simulations were used to confirm the effect of D-A system and Au NPs. In-situ FTIR results demonstrated that the synergistic photothermal effect promoted the formation of the key intermediate species COOH*, which is beneficial for the photocatalytic reduction of CO2. This study provides valuable insights into the multiple photothermal synergistic effects in photocatalytic reactions.    

    

* Synergistic Promotion for the Performance of Photocatalytic Carbon Dioxide Reduction by Vacancy Engineering and N-Doped Carbon Nanotubes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392839620
:TOPICS: Catalytic Nanomaterials, Gas Sensing Technology and Materials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4728334")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392839620"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392839620"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392839620"))][Get cited by]]

OpenAlex: https://openalex.org/W4392839620 (Open access: False)
    
[[https://openalex.org/A5015102287][Min Wang]], [[https://openalex.org/A5001935045][Jing Xie]], [[https://openalex.org/A5027671620][Zhenjiang Lu]], [[https://openalex.org/A5010078147][Fanlin Kong]], [[https://openalex.org/A5005466268][Baolin Liu]], [[https://openalex.org/A5075086500][Zhende Wu]], [[https://openalex.org/A5085766817][Yali Cao]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4728334 
     
No abstract    

    

* Synthesis of nanocomposites based on graphitic carbon nitride, titanium dioxide and boron nitride for the photo-production of H2 and the photo-reduction of CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392773243
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2023-07-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392773243"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392773243"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392773243"))][Get cited by]]

OpenAlex: https://openalex.org/W4392773243 (Open access: True)
    
[[https://openalex.org/A5019505146][Leila Hammoud]], No host. None(None)] 2023. None  ([[https://theses.hal.science/tel-04257912/document][pdf]])
     
No abstract    

    

* Distribution of Carbon Dioxide Emissions and Potential Consequences for Their Reduction in Louisiana  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392795875
:TOPICS: Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-03-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.31390/gradschool_theses.5821")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392795875"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392795875"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392795875"))][Get cited by]]

OpenAlex: https://openalex.org/W4392795875 (Open access: False)
    
[[https://openalex.org/A5003963085][Mohammad I. Zia]], No host. None(None)] 2024. https://doi.org/10.31390/gradschool_theses.5821 
     
No abstract    

    

* Effect of Carbon Dioxide on Bromantane Syntesis by Reductive Amination without an External Hydrogen Source  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392658822
:TOPICS: Homogeneous Catalysis with Transition Metals, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.32931/io2307a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392658822"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392658822"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392658822"))][Get cited by]]

OpenAlex: https://openalex.org/W4392658822 (Open access: True)
    
[[https://openalex.org/A5094118477][D. Kletnov]], [[https://openalex.org/A5084149613][Klim O. Biriukov]], [[https://openalex.org/A5049091066][А. Е. Николаев]], [[https://openalex.org/A5052276614][Oleg I. Afanasyev]], [[https://openalex.org/A5087933572][Denis Chusov]], ИНЭОС OPEN. None(None)] 2024. https://doi.org/10.32931/io2307a 
     
The effect of carbon dioxide on the reaction of bromantane synthesis by reductive amination using carbon monoxide as a reducing agent has been studied. A nonlinear dependence of the yield of the target product on the ratio of gases was observed. It was found that, depending on the conditions, carbon dioxide could both decrease and increase the yield of bromantane.    

    

* Multi-purpose afforestation scenarios under climate change for carbon dioxide reduction&#160;  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392645629
:TOPICS: Climate Change Impacts on Forest Carbon Sequestration
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-egu24-19777")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392645629"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392645629"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392645629"))][Get cited by]]

OpenAlex: https://openalex.org/W4392645629 (Open access: False)
    
[[https://openalex.org/A5052135651][Florian Kraxner]], [[https://openalex.org/A5059691294][Dmitry Schepaschenko]], [[https://openalex.org/A5011197728][Sabine Fuss]], [[https://openalex.org/A5000752663][Andrey Krasovskiy]], [[https://openalex.org/A5003804635][А. Shvidenko]], [[https://openalex.org/A5055674721][Georg Kindermann]], [[https://openalex.org/A5050291308][Hyun-Woo Jo]], [[https://openalex.org/A5034477242][Woo‐Kyun Lee]], No host. None(None)] 2024. https://doi.org/10.5194/egusphere-egu24-19777 
     
This study aims at identifying the carbon dioxide reduction (CDR) potential of large-scale and multi-purpose afforestation/reforestation at the global level with special emphasis on the Mid-Latitude Region (MLR). Applying a combined remote sensing/GIS approach coupled with biophysical forest and disturbance modeling under various climate change scenarios, we identify potential afforestation locations, inter-alia on abandoned agricultural land and on areas burnt from wild land fires. With the help of IIASA&#8217;s biophysical global forestry model (G4M), we calculate the associated land-based CDR potentials through carbon sequestration in afforested biomass and through climate risk-resilient and sustainable forest management dedicated to the supply of bioenergy plants coupled with carbon capture and storage (BECCS) facilities. Finally, three promising scenarios have been identified including I) afforestation; II) reforestation; and III) BECCS. In all scenarios, priority is put on sustainable forest management and nature/biodiversity conservation. Forest modeling results have been combined with recent data sets which have been overlayed in order to provide a unique basis to estimate the land-based CDR technologies&#8217; potential to mitigate climate change and contribute to reaching the goals of the Paris Agreement. In the case of afforestation, preliminary results indicate a total potential afforestation area greater than 1 billion ha. &#160;The largest area potential for afforestation have been identified in the USA. Given the higher productivity (combined with large area available), Brazil is the country with the highest total CDR potential of close to 500 MtC/yr.    

    

* Amorphous ZnSnOx Hollow Spheres Enable Highly Efficient CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392697772
:TOPICS: Gas Sensing Technology and Materials, Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202301694")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392697772"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392697772"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392697772"))][Get cited by]]

OpenAlex: https://openalex.org/W4392697772 (Open access: False)
    
[[https://openalex.org/A5071554167][Hanjun Li]], [[https://openalex.org/A5047932271][Yao Chen]], [[https://openalex.org/A5026321778][Honggang Huang]], [[https://openalex.org/A5009561241][Zhenxiang Cheng]], [[https://openalex.org/A5012219750][Shuxing Bai]], [[https://openalex.org/A5070873389][Feili Lai]], [[https://openalex.org/A5016175164][Nan Zhang]], [[https://openalex.org/A5018950796][Tianxi Liu]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202301694 
     
Carbon dioxide (CO2) adsorption and electron transport play an important role in CO2 reduction reaction (CO2RR). Herein, we have demonstrated a new class of diverse hollow ZnSnOx (ZSO) through the amorphization of hydroxides to enhance CO2 adsorption and accelerate electron transport. The amorphization is occurred by calcination process, as indicated by Fourier transform infrared spectroscopy and Raman spectra. In particular, the ZnSnOx hollow spheres (ZSO HSs) achieve a high Faradaic efficiency (FE) of HCOOH up to 92.7% at best, outperforming the commercial ZSO (Comm. ZSO, 83.9%). ZSO HSs also exhibit durable stability with negligible activity decay after 10 h of successive electrolysis. In‐situ attenuated total reflectance infrared absorption spectroscopy further reveals strong adsorption of CO2 and rapid intermediate configuration transformation in amorphous ZSO HSs. This work demonstrates the practical application of ZSO for CO2RR and provides a new insight to create efficient CO2RR electrocatalysts.    

    

* Study of layered double hydroxides for the electrocatalytic reduction of CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392773097
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2023-04-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392773097"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392773097"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392773097"))][Get cited by]]

OpenAlex: https://openalex.org/W4392773097 (Open access: True)
    
[[https://openalex.org/A5087757322][A. Tarhini]], No host. None(None)] 2023. None  ([[https://theses.hal.science/tel-04357430/document][pdf]])
     
No abstract    

    

* Electrolyte effect in electrochemical reduction of CO2 on Cu electrode  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392704869
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2023-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.29363/nanoge.matsus.2024.367")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392704869"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392704869"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392704869"))][Get cited by]]

OpenAlex: https://openalex.org/W4392704869 (Open access: False)
    
[[https://openalex.org/A5079766978][Amanda C. Garcia]], No host. None(None)] 2023. https://doi.org/10.29363/nanoge.matsus.2024.367 
     
No abstract    

    

* Carbon-Supported Silver Catalysts for Electrocatalytic Reduction of CO2 to CO  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392835293
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.33540/2122")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392835293"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392835293"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392835293"))][Get cited by]]

OpenAlex: https://openalex.org/W4392835293 (Open access: False)
    
[[https://openalex.org/A5063210714][Francesco Mattarozzi]], No host. None(None)] 2024. https://doi.org/10.33540/2122 
     
The work described in this thesis was aimed at understanding the influence of structural properties of silver catalysts supported on carbon for the electrocatalytic reduction of CO2 to CO. This goal was achieved by rationally designing, characterizing and testing cathode materials. This enabled a correlation between material properties and the catalytic performance. Chapter 1 describes the potential benefits of electrochemistry and electrocatalysis in the context of global warming. The CO2 electrocatalytic reduction to value-added chemicals was described, including the effect of different metal electrodes and buffer electrolytes. Specifically, a background is given on the CO2RR to CO over silver electrocatalysts, and the properties of carbon electrodes, based on literature. In chapter 2, the effect of surface-modification of carbon-based electrodes on the reduction of CO2 to CO is systematically treated. The surface chemistry of the electrodes was characterized with acid-base titration, potentiometric titration and XPS. The basic surface properties (high point of zero charge) of the N functionalized carbon catalyst led to an increased CO production with respect to the O-functionalized and reduced carbon materials. The CO turnover frequency per surface group for pyridinic groups was higher than for O-containing groups. This study demonstrated the possibility to tune the surface properties of carbon materials to enhance the ability of the electrocatalyst to reduce CO2 to CO. In chapter 3, the effect of silver nanoparticle size on the CO2 reduction to CO is discussed. Using the surface modification methods described in chapter 2, control over the ligand-free silver particle size was achieved by tuning the surface properties of the carbon supports. It was demonstrated that the silver particle size, in the range of 10 to 30 nm, decreased by increasing the density of O-containing group on the support. The small nanoparticles (11 nm diameter) effectively steered the selectivity towards CO, even greater than the selectivity achieved by bulk silver electrodes under the same conditions. In chapter 4, the aim was to suppress the hydrogen formation over the high surface area carbon support by functionalizing the surface of the support with alkylamines. The effect of the number of carbon atoms in the alkyl chain on the HER suppression and CO selectivity was investigated. Alkylamine functionalization successfully suppressed H2 evolution, while at the same time promoting CO production. This resulted in a 1 to 2 H2 to CO ratio for the catalyst functionalized with hexylamine, more favorable than for the pristine carbon-based catalyst (benchmark), able to generate only a 3.3 to 1 H2 to CO ratio. In chapter 5, the catalytic properties of oxide-derived silver nanowires, are explored. XRD and XPS analysis confirmed that by selecting the final potential during the oxidation procedure, both different silver oxidations states and different nanowires roughness were achieved as a function of the oxidation potential. This surface-modification procedure enhanced the catalytic properties of the nanowires. The active surface-normalized CO partial current density increased 3.7-times when the pristine nanowires were oxidized to 1.0 V vs Ag/AgCl in basic electrolyte solution.    

    

* The Impact of International Cooperation and Logistics Networks on CO2 Emission Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392735268
:TOPICS: Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2023-12-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18104/kalc.2023.38.4.181")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392735268"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392735268"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392735268"))][Get cited by]]

OpenAlex: https://openalex.org/W4392735268 (Open access: False)
    
[[https://openalex.org/A5085403337][Ming Song]], Korean Academy Of International Commerce. 38(4)] 2023. https://doi.org/10.18104/kalc.2023.38.4.181 
     
Purpose: This study analyzes the causal relationships between CO2 emissions and ODA, logistics, renewable energy, economic growth, and industrialization. Research design, data, and methodology: From 2006 to 2019, panel data related to CO2 emissions, ODA, logistics networks, renewable energy, economic growth, and industrialization were collected from a total of 84 countries. To analyze this model, panel unit root tests and panel co-integration tests were performed to confirm the stability and long-term causal relationships in the data. Subsequently, panel FMOLS and panel DOLS were used to identify variables affecting carbon dioxide, and pairwise panel Granger causality analysis was used to analyze causality between these variables. Results: According to panel FMOLS and panel DOLS analysis, ODA and renewable energy reduce CO2 emissions, but economic growth increases CO2 emissions. Conclusions: As a result of panel FMOLS and panel DOLS analysis, economic growth was identified as a factor in increasing CO2 emissions, and international development cooperation and renewable energy were identified as factors in reducing CO2 emissions.    

    

* Reaction-transport kinetics in the electrochemical reduction of CO2 on copper catalysts  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392704678
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2023-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.29363/nanoge.matsus.2024.418")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392704678"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392704678"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392704678"))][Get cited by]]

OpenAlex: https://openalex.org/W4392704678 (Open access: False)
    
[[https://openalex.org/A5074179289][Carlos G. Morales‐Guio]], No host. None(None)] 2023. https://doi.org/10.29363/nanoge.matsus.2024.418 
     
No abstract    

    

* CuSnBi Catalyst Grown on Copper Foam by Co-Electrodeposition for Efficient Electrochemical Reduction of CO2 to Formate  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392648975
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14030191")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392648975"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392648975"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392648975"))][Get cited by]]

OpenAlex: https://openalex.org/W4392648975 (Open access: True)
    
[[https://openalex.org/A5060151594][Hangxin Xie]], [[https://openalex.org/A5034973415][Li Lv]], [[https://openalex.org/A5036120236][Yuan Sun]], [[https://openalex.org/A5045162736][Chunlai Wang]], [[https://openalex.org/A5035720806][Jialin Xu]], [[https://openalex.org/A5017813339][Min Tang]], Catalysts. 14(3)] 2024. https://doi.org/10.3390/catal14030191  ([[https://www.mdpi.com/2073-4344/14/3/191/pdf?version=1710145813][pdf]])
     
Effective electrochemical reduction of carbon dioxide to formate under mild conditions helps mitigate the energy crisis but requires the use of high-performance catalysts. The addition of a third metal to the binary metal catalyst may further promote the electrochemical reduction of carbon dioxide to formate. Herein, we provided a co-electrodeposition method to grow CuSnBi catalysts on pretreated copper foam and discussed the effects of both pH value and molar ratio of metal ions (Cu2+, Sn2+, and Bi3+) in the electrodeposition solution on the electrocatalytic performance of CO2 to HCOO−. When the pH value of the electrodeposition solution was 8.5 and the molar ratio of Cu2+, Sn2+, and Bi3+ was 1:1:1, the electrode showed the highest FEHCOO− of 91.79% and the formate partial current density of 36.6 mA·cm−2 at −1.12 VRHE. Furthermore, the electrode kept stable for 20 h at −1.12 VRHE, and FEHCOO− was always beyond 85% during the electrolysis process, which is excellent compared to the previously reported ternary metal catalytic electrodes. This work highlights the vital impact of changes (pH value and molar ratio of metal ions) in electrodeposition liquid on catalytic electrodes and their catalytic performance, and refreshing the electrolyte is essential to maintain the activity and selectivity during the electrochemical reduction of CO2 to HCOO−.    

    

* The Prospects of Urea Manufacturing via Electrochemical Co-reduction of CO2 and Nitrates  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392767741
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.coelec.2024.101479")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392767741"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392767741"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392767741"))][Get cited by]]

OpenAlex: https://openalex.org/W4392767741 (Open access: False)
    
[[https://openalex.org/A5018366822][Qinglan Zhao]], [[https://openalex.org/A5082117229][Ye Zhang]], [[https://openalex.org/A5056166029][Dapeng Cao]], [[https://openalex.org/A5059810259][Minhua Shao]], Current Opinion in Electrochemistry. None(None)] 2024. https://doi.org/10.1016/j.coelec.2024.101479 
     
Electrochemical co-reduction of CO2 and nitrates presents a promising alternative for urea production. However, the current electrochemical synthesis of urea faces challenges related to low selectivity and production rates. The development of high-efficiency electrocatalysts is the key to performance improvement of urea electrosynthesis. This minireview primarily focuses on the rational design of catalysts, starting with a mechanistic overview. In addition, the advancement of electrolyzers for urea electrochemical synthesis is also discussed aiming to articulate guiding principles of achieving high-rate production reaching industrial relevant level in the future.    

    

* Constructing Strain in Electrocatalytic Materials for CO2 Reduction Reactions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392813161
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Solid Oxide Fuel Cells, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4gc00514g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392813161"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392813161"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392813161"))][Get cited by]]

OpenAlex: https://openalex.org/W4392813161 (Open access: False)
    
[[https://openalex.org/A5079861099][Junshan Lin]], [[https://openalex.org/A5054418515][Ning Zhang]], Green Chemistry. None(None)] 2024. https://doi.org/10.1039/d4gc00514g 
     
The electrocatalytic conversion of carbon dioxide (CO2) into valuable carbon-based compounds has attracted considerable attention. In the quest for efficient electrocatalysts, strain engineering, characterized by localized relative deformation, emerges as...    

    

* Exploring the Effects of Ligands on Gold Nanoparticles for the Selective Reduction of CO2 to CO  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392704565
:TOPICS: Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2023-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.29363/nanoge.matsus.2024.082")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392704565"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392704565"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392704565"))][Get cited by]]

OpenAlex: https://openalex.org/W4392704565 (Open access: False)
    
[[https://openalex.org/A5053003716][Álvaro Lozano Roche]], [[https://openalex.org/A5094126796][Asia Porceddu]], [[https://openalex.org/A5020337283][Laia Francàs]], [[https://openalex.org/A5080028922][Jordi García‐Antón]], [[https://openalex.org/A5039090961][Xavier Sala]], No host. None(None)] 2023. https://doi.org/10.29363/nanoge.matsus.2024.082 
     
No abstract    

    

* Dynamic Evolution of Single Atom Catalysts during CO2 Electrocatalytic Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392704879
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2023-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.29363/nanoge.matsus.2024.233")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392704879"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392704879"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392704879"))][Get cited by]]

OpenAlex: https://openalex.org/W4392704879 (Open access: False)
    
[[https://openalex.org/A5065326930][Beatriz Roldán Cuenya]], No host. None(None)] 2023. https://doi.org/10.29363/nanoge.matsus.2024.233 
     
No abstract    

    
