#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Mon Jul 22 01:13:18 2024

Found 65 results from 2024-07-15 to 2024-07-22
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Pd doped tin oxide nanostructured catalysts for electrochemical reduction of carbon dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400678732
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4621090/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400678732"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400678732"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400678732"))][Get cited by]]

OpenAlex: https://openalex.org/W4400678732 (Open access: False)
    
[[https://openalex.org/A5035303783][Shuting Tan]], [[https://openalex.org/A5103172999][Zhuo Xiong]], [[https://openalex.org/A5045213944][Zuwei Xu]], [[https://openalex.org/A5100618928][Junying Zhang]], [[https://openalex.org/A5072190323][Yongchun Zhao]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4621090/v1 
     
Abstract Electrocatalytic reduction of CO2 can convert CO2 into a variety of carbon-based fuels and achieve carbon neutrality. Tin oxide (SnO2) electrocatalytic materials have the advantages of low cost and low toxicity, and the electrocatalytic reduction of CO2 to formic acid is highly selective. In this paper, Pd-doped SnO2 nanoparticle materials were synthesized by flame spray pyrolysis and their properties for electrocatalytic reduction of CO2 to formic acid were explored in a gas diffusion electrolytic cell. The results showed that the Pd/SnO2 catalysts could improve the catalytic activity for the conversion of CO2 to formate, and the most superior 0.5 Pd/SnO2 showed a Faraday efficiency of 63% for formate at -1.20 V vs. RHE and a current density of 90.59 mA.cm− 2, which were 1.4 and 2.7 times higher than that of pure SnO2, respectively. The modified catalyst grains were refined, and the charge transfer resistance at the catalyst interface was reduced and the electrochemically active area was increased, generating more catalytically active sites and increasing the contact between CO2, electrolyte, and electrode-catalyst. Density-functional theory calculations showed that the doping of Pd element changed the local structure of SnO2, and the Pd/SnO2 surface was more favorable for the generation of the intermediate products *HCOO− and formate as well as the inhibition of hydrogen precipitation, which was consistent with the experimental results.    

    

* Electrochemical Reduction of Carbon Dioxide to Formate in the Acetylene-Black Gas-Diffusion Electrode with a Tin Catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400737610
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1134/s1023193524700149")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400737610"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400737610"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400737610"))][Get cited by]]

OpenAlex: https://openalex.org/W4400737610 (Open access: False)
    
[[https://openalex.org/A5047897165][G. A. Kolyagin]], [[https://openalex.org/A5070632148][Оxana P. Тaran]], Russian journal of electrochemistry. 60(7)] 2024. https://doi.org/10.1134/s1023193524700149 
     
No abstract    

    

* Polymerized Ionic Liquid Co-Catalysts Driving Photocatalytic Carbon Dioxide Transformation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400740450
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Dehydrogenation of Light Alkanes, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4su00194j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400740450"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400740450"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400740450"))][Get cited by]]

OpenAlex: https://openalex.org/W4400740450 (Open access: True)
    
[[https://openalex.org/A5063989882][Lisa Eisele]], [[https://openalex.org/A5104647046][Bletë Hulaj]], [[https://openalex.org/A5104647047][Francesco Laudani]], [[https://openalex.org/A5073752043][Maximilian Podsednik]], [[https://openalex.org/A5064397330][Pablo Ayala]], [[https://openalex.org/A5022928359][Alexey Cherevan]], [[https://openalex.org/A5009881073][Annette Foelske]], [[https://openalex.org/A5036970781][Andreas Limbeck]], [[https://openalex.org/A5101484593][Dominik Eder]], [[https://openalex.org/A5090183844][Katharina Bica]], RSC sustainability. None(None)] 2024. https://doi.org/10.1039/d4su00194j 
     
Photocatalytic production of CO from CO 2 has the potential for safe and atom-economic production of feedstock chemicals via in-situ carbonylation chemistry. We developed novel ionic liquid-based polymeric materials through radical...    

    

* Improving co-electrocatalytic carbon dioxide reduction by optimizing the relative potentials of the redox mediator and catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400742285
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cc01988a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400742285"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400742285"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400742285"))][Get cited by]]

OpenAlex: https://openalex.org/W4400742285 (Open access: True)
    
[[https://openalex.org/A5023308887][Amelia G. Reid]], [[https://openalex.org/A5104647609][Ethan A. Zelenke]], [[https://openalex.org/A5043747006][Megan E. Moberg]], [[https://openalex.org/A5019581925][Diane A. Dickie]], [[https://openalex.org/A5029623212][Charles W. Machan]], Chemical communications. None(None)] 2024. https://doi.org/10.1039/d4cc01988a 
     
The effects of fixing the redox mediator (RM) reduction potential relative to a series of Cr-centered complexes capable of the reduction of CO    

    

* Improving the energy efficiency and carbon dioxide reduction of a long-haul bus through aerodynamic design optimization  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400741600
:TOPICS: Aerodynamics of High-Speed Trains and Vehicles
:PUBLICATION_DATE: 2024-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.30955/gnj.06173")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400741600"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400741600"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400741600"))][Get cited by]]

OpenAlex: https://openalex.org/W4400741600 (Open access: False)
    
, Global NEST Journal. None(None)] 2024. https://doi.org/10.30955/gnj.06173 
     
<p>Exhaustion of fossil fuel resources, inconsistent fuel costs and the difficulty of adopting electric vehicle technology in commercial vehicles support the idea that there is an opportunity for research in public transit regarding the correlation between energy efficiency and aerodynamic drag. The turbulent external airflow over a bus at high speeds impacts acceleration, speed, and fuel economy. The fundamental bus's design is intended to carry enough passengers for a reasonable run. Envisaging the factors influencing aerodynamic drag is defiant due to the convoluted relationship between the moving bus and the air. Consequently, a comprehensive numerical and experimental exploration is executed on the bodywork of a bus to improve its aerodynamic efficiency. The aerodynamic drag is directly proportional to the variations in the air density, frontal area, freestream velocity and the drag coefficient. Minimal design reforms are performed on a distinctive long-haul bus. The exertion aims to minimize the drag coefficient, thereby improving the flow characteristics of the bus's bodywork. Through the shape optimization of the bus's bodywork, the modified design has attained a forty-five percent reduction in the drag coefficient. This substantial reduction in drag coefficient directly impacts the reduction of drag force, energy efficiency improvement, and carbon emissions reduction.</p>    

    

* CO2 reduction in strong acid  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400657511
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s44160-024-00608-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400657511"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400657511"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400657511"))][Get cited by]]

OpenAlex: https://openalex.org/W4400657511 (Open access: False)
    
[[https://openalex.org/A5017052730][Taito Watanabe]], [[https://openalex.org/A5090212607][Shigeyuki Masaoka]], Nature synthesis. None(None)] 2024. https://doi.org/10.1038/s44160-024-00608-3 
     
No abstract    

    

* Rational design of organic ligands for metal-organic frameworks as electrocatalysts for CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400722259
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cc02635g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400722259"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400722259"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400722259"))][Get cited by]]

OpenAlex: https://openalex.org/W4400722259 (Open access: False)
    
[[https://openalex.org/A5049026772][Ya Zhang]], [[https://openalex.org/A5036287984][Wei‐Yin Sun]], Chemical communications. None(None)] 2024. https://doi.org/10.1039/d4cc02635g 
     
Electrocatalytic carbon dioxide (CO2) reduction to valuable chemical compounds is a sustainable technology with enormous potential to facilitate carbon neutrality by transforming intermittent energy sources into stable fuels. Among various...    

    

* Cleaner separation and recovery of valuable metals from spent ternary cathode via carbon dioxide synergetic thermite reduction strategy  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400673266
:TOPICS: Battery Recycling and Rare Earth Recovery, Global E-Waste Recycling and Management, Biohydrometallurgical Processes for Metal Extraction
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jenvman.2024.121853")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400673266"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400673266"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400673266"))][Get cited by]]

OpenAlex: https://openalex.org/W4400673266 (Open access: False)
    
[[https://openalex.org/A5028299718][Cheng Yang]], [[https://openalex.org/A5100417363][Qiong Wang]], [[https://openalex.org/A5101443699][Liang Xu]], [[https://openalex.org/A5018147854][Yongpan Tian]], [[https://openalex.org/A5009441078][Zhuo Zhao]], Journal of environmental management. 366(None)] 2024. https://doi.org/10.1016/j.jenvman.2024.121853 
     
The low-carbon recycling of spent lithium-ion batteries has become crucial due to the increasing need to address resource shortages and environmental concerns. Herein, a low-carbon, facile, and efficient method was developed to separate and recover Li, Al, and transition metals from spent ternary cathodes. Initially, the cathode materials post-discharge and disassembly do not require pre-sorting. Instead of using carbonaceous materials, the Al foil in the cathode serves as the reducing agent during reduction roasting. The impact of different roasting atmospheres (air, N    

    

* Distinct CO2-run-out regime from steric effect of electric double layer in electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400654483
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0214255")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400654483"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400654483"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400654483"))][Get cited by]]

OpenAlex: https://openalex.org/W4400654483 (Open access: False)
    
[[https://openalex.org/A5069978822][Longfei Chen]], [[https://openalex.org/A5075996632][Hao Feng]], [[https://openalex.org/A5059811239][Ying Zhang]], [[https://openalex.org/A5076270970][Dong Liu]], [[https://openalex.org/A5100429972][Qiang Li]], Applied physics reviews. 11(3)] 2024. https://doi.org/10.1063/5.0214255 
     
The field of electrochemical CO2 reduction reaction (eCO2RR) is pursuing high operating current densities, eventually controlled by CO2 transport. Here, we develop a new multiscale modeling approach that is able to more generally describe the effects of the electric double layer (EDL) on CO2 transport over a wide potential window extending to utmost potentials. By leveraging it, we identify a distinct CO2-run-out regime where the supply of CO2 runs out due to the EDL steric effect from a dense layer of solvated cations with the maximum layer thickness equal to the solvated cation size. Consequently, CO2RR current density drops at a relatively negative transition potential generating a bell-shaped polarization curve, which is in contrast to the CO2-transport-limited regime where the current density reaches a plateau. Furthermore, we develop a graphical method, verified by experimental data, to generally predict the transition to the CO2-run-out regime. This work sheds new light on the EDL effects for catalyst design and electrolyzer engineering.    

    

* Leveraging intramolecular electrostatics to boost electrocatalytic CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400770264
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.checat.2024.101053")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400770264"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400770264"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400770264"))][Get cited by]]

OpenAlex: https://openalex.org/W4400770264 (Open access: False)
    
[[https://openalex.org/A5072645745][David S. Tresp]], [[https://openalex.org/A5045974205][Demyan E. Prokopchuk]], Chem catalysis. 4(7)] 2024. https://doi.org/10.1016/j.checat.2024.101053 
     
No abstract    

    

* Cu into Cu2O/RuAl intermetallic heterojunction for lowering the thermodynamic energy barrier of the CO2 reduction and evolution reactions in Li–CO2 battery  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400673212
:TOPICS: Lithium Battery Technologies, Lithium-ion Battery Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.07.016")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400673212"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400673212"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400673212"))][Get cited by]]

OpenAlex: https://openalex.org/W4400673212 (Open access: False)
    
[[https://openalex.org/A5003113370][Wenqing Ma]], [[https://openalex.org/A5025545118][Jiagang Hou]], [[https://openalex.org/A5100326249][Siyu Liu]], [[https://openalex.org/A5045027532][Tianzhen Jian]], [[https://openalex.org/A5100293791][Jianping Ma]], [[https://openalex.org/A5061391319][Caixia Xu]], [[https://openalex.org/A5101900181][Hong Liu]], Journal of Energy Chemistry/Journal of energy chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.07.016 
     
No abstract    

    

* Synergistic Augmentation and Fundamental Mechanistic Exploration of β-Ga2O3-rGO Photocatalyst for Efficient CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400663272
:TOPICS: Gallium Oxide (Ga2O3) Semiconductor Materials and Devices, Photocatalytic Materials for Solar Energy Conversion, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4na00408f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400663272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400663272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400663272"))][Get cited by]]

OpenAlex: https://openalex.org/W4400663272 (Open access: True)
    
[[https://openalex.org/A5102945825][Hyein Jeong]], [[https://openalex.org/A5044974638][Hangyeol Choi]], [[https://openalex.org/A5075619909][Yujin Song]], [[https://openalex.org/A5044201544][Jung Han Kim]], [[https://openalex.org/A5002469914][Yohan Yoon]], Nanoscale advances. None(None)] 2024. https://doi.org/10.1039/d4na00408f 
     
We explore the novel photodecomposition capabilities of β-Ga2O3 when augmented with reduced graphene oxide (rGO). Employing real-time spectroscopy, this study unveils the sophisticated mechanisms of photodecomposition, identifying an optimal 1...    

    

* Electrochemical CO2 and CO reduction using Au/TiO2 model catalysts for syngas and Fischer-Tropsch chemistry  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400720613
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.184")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400720613"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400720613"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400720613"))][Get cited by]]

OpenAlex: https://openalex.org/W4400720613 (Open access: False)
    
[[https://openalex.org/A5103048014][So Young Kim]], [[https://openalex.org/A5006061264][Seon Young Hwang]], [[https://openalex.org/A5037619736][Gak-Won Yun]], [[https://openalex.org/A5093380486][Yunji Gwon]], [[https://openalex.org/A5102600687][Sooyeon Bae]], [[https://openalex.org/A5062873772][Choong Kyun Rhee]], [[https://openalex.org/A5035286820][Youngku Sohn]], International journal of hydrogen energy. 80(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.184 
     
No abstract    

    

* Photothermal-boosted S-scheme heterojunction of α-Fe2O3@NiOx for high-selective reduction of CO2 to CO  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400644913
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.160747")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400644913"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400644913"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400644913"))][Get cited by]]

OpenAlex: https://openalex.org/W4400644913 (Open access: False)
    
[[https://openalex.org/A5013391133][Xiao Liu]], [[https://openalex.org/A5104557517][Bai Kaihui]], [[https://openalex.org/A5078809436][Yuhang Nie]], [[https://openalex.org/A5100721477][Xusheng Wang]], [[https://openalex.org/A5045618171][Lang Pei]], Applied surface science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.160747 
     
No abstract    

    

* Redistributing the local electron density of bismuth via introducing halogen atoms for boosting CO2 reduction to formate  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400652055
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.checat.2024.101057")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400652055"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400652055"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400652055"))][Get cited by]]

OpenAlex: https://openalex.org/W4400652055 (Open access: False)
    
[[https://openalex.org/A5059435868][Haidong Shen]], [[https://openalex.org/A5031539784][H. N. Wang]], [[https://openalex.org/A5057284055][Tianshuai Wang]], [[https://openalex.org/A5100363728][Jiarui Zhang]], [[https://openalex.org/A5060113464][Shaowei Yang]], [[https://openalex.org/A5064335105][Hao Jiang]], [[https://openalex.org/A5100384368][Peng Zhao]], [[https://openalex.org/A5102470886][Runze Gao]], [[https://openalex.org/A5104558319][Xinrui Linghu]], [[https://openalex.org/A5101729594][Ying Guo]], [[https://openalex.org/A5101820889][Hepeng Zhang]], Chem catalysis. None(None)] 2024. https://doi.org/10.1016/j.checat.2024.101057 
     
No abstract    

    

* Progress in tracking electrochemical CO2 reduction intermediates over single-atom catalysts using operando ATR-SEIRAS  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400806569
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/s1872-2067(24)60068-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400806569"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400806569"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400806569"))][Get cited by]]

OpenAlex: https://openalex.org/W4400806569 (Open access: False)
    
[[https://openalex.org/A5101311630][Jing Yan]], [[https://openalex.org/A5089197572][Jiaqi Ni]], [[https://openalex.org/A5100913740][Hongli Sun]], [[https://openalex.org/A5079209602][Chenliang Su]], [[https://openalex.org/A5100395496][Bin Liu]], Cuihua xuebao/Chinese journal of catalysis. 62(None)] 2024. https://doi.org/10.1016/s1872-2067(24)60068-9 
     
No abstract    

    

* Water-induced Switching in Selectivity and Steric Control of Activity in Photochemical CO2 Reduction Catalyzed by RhCp*(bpy) Derivatives  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400664492
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-t3ltd-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400664492"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400664492"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400664492"))][Get cited by]]

OpenAlex: https://openalex.org/W4400664492 (Open access: False)
    
[[https://openalex.org/A5063894173][Dongseb Lee]], [[https://openalex.org/A5039693008][Kosei Yamauchi]], [[https://openalex.org/A5066627191][Ken Sakai]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-t3ltd-v2 
     
Photocatalytic reduction of CO2 to formic acid (HCOOH) was investigated in either organic or aqueous/organic media by employing three water-soluble Rh(Cp*)(n,n’-dihydroxy-2,2’-bipyridine) (n = 4, 5, or 6) in the presence of [Ru(bpy)3]2+, 1,3-dimethyl-2-phenyl-2,3-dihydro-1H-benzo[d]imidazole (BIH) and triethanolamine (TEOA). Through studying the electron-donating effects of two hydroxyl groups introduced to the bipyridyl ligand, we found that the substituent positions greatly affect both the catalytic efficiency and selectivity in CO2 reduction. More importantly, the HCOOH selectivity shows a dramatic increase from 14% to 83% upon switching the solvent media from pure organic to aqueous/organic mixture, where the H2 selectivity shows a reverse phenomenon. The enhanced HCOOH selectivity and the drastic decrease in the apparent H2 yield are well rationalized by the fact that the catalytic CO2 hydrogenation by the evolved H2 simultaneously proceeds as a dark catalytic reaction, which was also separately investigated under the dark conditions. Our DFT studies unveil that the exceptionally large structural strain given by the steric contacts between the 6,6’-dihydroxyl groups and the Cp* moiety plays a significant role in bringing about an outstanding catalytic performance of the 6,6’-subsituted derivative. The intrinsic reaction coordinate calculations were carried out to clarify the mechanism of hydride transfer steps leading to generate formate together the heterolytic H2 cleavage steps leading to afford the key hydridorhodium intermediates. This study represents the first report on the water-induced high selectivity in CO2-to-HCOOH conversion, shedding a new light on the strategy to control the efficiency and selectivity in the catalysis of CO2 reduction.    

    

* Selective scission of glucose molecule by a Pd-modulated Co-based catalyst for efficient CO2 reduction under mild conditions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400645946
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.scib.2024.07.020")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400645946"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400645946"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400645946"))][Get cited by]]

OpenAlex: https://openalex.org/W4400645946 (Open access: False)
    
[[https://openalex.org/A5101964400][Peidong Zhu]], [[https://openalex.org/A5048984134][Jiacong Li]], [[https://openalex.org/A5100397594][Yang Yang]], [[https://openalex.org/A5030447587][Heng Zhong]], [[https://openalex.org/A5000148829][Fangming Jin]], Science Bulletin. None(None)] 2024. https://doi.org/10.1016/j.scib.2024.07.020 
     
No abstract    

    

* Tensile‐Strained Cu Penetration Electrode Boosts Asymmetric C–C Coupling for Ampere‐Level CO2‐to‐C2+ Reduction in Acid  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400658650
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202407612")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400658650"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400658650"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400658650"))][Get cited by]]

OpenAlex: https://openalex.org/W4400658650 (Open access: False)
    
[[https://openalex.org/A5101644090][Shoujie Li]], [[https://openalex.org/A5013842278][Gangfeng Wu]], [[https://openalex.org/A5018878652][Jianing Mao]], [[https://openalex.org/A5058339207][Aohui Chen]], [[https://openalex.org/A5100689578][Xiaohu Liu]], [[https://openalex.org/A5068006098][Jianrong Zeng]], [[https://openalex.org/A5064015289][Yiheng Wei]], [[https://openalex.org/A5078303039][Jiangjiang Wang]], [[https://openalex.org/A5060510648][Haili Zhu]], [[https://openalex.org/A5103494520][Jian‐Bai Xia]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5085611722][Guihua Li]], [[https://openalex.org/A5101891693][Yanfang Song]], [[https://openalex.org/A5006528528][Xiao Dong]], [[https://openalex.org/A5100323723][Wei Wei]], [[https://openalex.org/A5100392071][Wei Wang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/anie.202407612 
     
The synthesis of multicarbon (C2+) products remains a substantial challenge in sustainable CO2 electroreduction owing to the need for sufficient current density and faradaic efficiency alongside carbon efficiency. Herein, we demonstrate ampere‐level high‐efficiency CO2 electroreduction to C2+ products in both neutral and strongly acidic (pH = 1) electrolytes using a hierarchical Cu hollow‐fiber penetration electrode (HPE). High concentration of K+ could concurrently suppress hydrogen evolution reaction and facilitate C–C coupling, thereby promoting C2+ production in strong acid. By optimizing the K+ and H+ concentration and CO2 flow rate, a faradaic efficiency of 84.5% and a partial current density as high as 3.1 A cm–2 for C2+ products, alongside a single‐pass carbon efficiency of 81.5% and stable electrolysis for 240 h were demonstrated in a strong acidic solution of H2SO4 and KCl (pH = 1). Experimental measurements and density functional theory simulations suggested that tensile‐strained Cu HPE enhances the asymmetric C–C coupling to steer the selectivity and activity of C2+ products.    

    

* DFT and machine learning studies on a multi-functional single-atom catalyst for enhanced oxygen and hydrogen evolution as well as CO2 reduction reactions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400806168
:TOPICS: Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.244")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400806168"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400806168"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400806168"))][Get cited by]]

OpenAlex: https://openalex.org/W4400806168 (Open access: False)
    
[[https://openalex.org/A5028218777][Mohsen Tamtaji]], [[https://openalex.org/A5056911582][Mohammad Kazemeini]], [[https://openalex.org/A5063840052][Jafar Abdi]], International journal of hydrogen energy. 80(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.244 
     
No abstract    

    

* Analysis of carbon dioxide disposal methods to reduce greenhouse gases  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400739758
:TOPICS: Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.37878/2708-0080/2024-2.16")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400739758"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400739758"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400739758"))][Get cited by]]

OpenAlex: https://openalex.org/W4400739758 (Open access: False)
    
[[https://openalex.org/A5017120479][Bolatbek Khussain]], [[https://openalex.org/A5094231241][A. Kenessary]], [[https://openalex.org/A5103009002][E. Narimanov]], [[https://openalex.org/A5038662373][Jamilyam Ismailova]], [[https://openalex.org/A5077210295][Dinara Delikesheva]], Neftʹ i gaz. 140(2)] 2024. https://doi.org/10.37878/2708-0080/2024-2.16 
     
The practice of capturing, storing and utilizing CO2 is becoming key to developing sustainable energy and industrial solutions. The technology promotes the use of fossil fuels, which remain the predominant source of energy worldwide. The effectiveness of the technology is evident in the reduction of CO2 levels in the atmosphere, a significant contribution to the reduction of global greenhouse gas (GHG) emissions and the fight against climate change. However, a notable concern in the realm of geological storage revolves around the potential leakage of CO2 from storage reservoirs. Carbon dioxide has the capability to migrate from the storage site, reaching both the surface and underground formations. Surface leakage presents health risks to humans, animals, and plants. The solution to this problem requires a detailed approach and should be solved through an inverse problem, in which pressure measurements in monitoring wells will be performed frequently to obtain information about the reservoir and possible leaks. Additionally, there are a number of issues with carbon dioxide leakage during oil and gas extraction, as well as various operations at fields. Emphasizing the monitoring of CO2 leakage, this paper underscores the importance of developing an algorithm designed to proactively prevent CO2 leakage in aquifers and depleted reservoirs. Such an initiative is pivotal in the broader context of mitigating greenhouse gas emissions. The paper offers an overview of methodologies for effective monitoring, management and modeling of CO2 leakage and practical approaches to calculation and assessment, contributing to a more complete understanding of the challenges associated with CO2 storage.    

    

* The Effectiveness of Agricultural Carbon Dioxide Removal using the University of Victoria Earth System Climate Model  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400661486
:TOPICS: Global Methane Emissions and Impacts, Carbon Dioxide Sequestration in Geological Formations, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/egusphere-2024-1810")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400661486"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400661486"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400661486"))][Get cited by]]

OpenAlex: https://openalex.org/W4400661486 (Open access: True)
    
[[https://openalex.org/A5084958058][Rebecca C. Evans]], [[https://openalex.org/A5051571272][H. Damon Matthews]], No host. None(None)] 2024. https://doi.org/10.5194/egusphere-2024-1810 
     
Abstract. A growing body of evidence suggests that to achieve the temperature goals of the Paris Agreement, carbon dioxide removal (CDR) will likely be required in addition to massive carbon dioxide (CO2) emissions reductions. Nature-based CDR, which includes a range of strategies to sequester carbon in natural reservoirs, could play an important role in efforts to limit climate warming to well below 2 °C above preindustrial levels. Agricultural CDR could enhance soil carbon sequestration, though the climate efficacy of such methods remains uncertain. Here, we use an intermediate complexity climate model to perform simulations of agricultural CDR in the form of soil carbon sequestration at a range of possible rates for different costs under three future emissions scenarios. We found that plausible levels of agricultural CDR were able to reduce CO2 concentration by 5–19 ppm and global surface air temperature by 0.02–0.10 °C by the end of century. This temperature decrease was non-linear with respect to cumulative removals, as any carbon removed remained part of the active carbon cycle, lessening the climate benefit compared to if the removed carbon was permanently stored in geological reservoirs. CDR was found to be more effective at reducing surface air temperature in low emissions scenarios, but less effective at reducing atmospheric CO2, compared to high emissions scenarios. This was because the weaker CO2 sinks in a high CO2 world had a more muted response to removal, so a substantially higher proportion of carbon was removed from the atmosphere for a given amount of CDR in a higher emissions scenario. The enhanced temperature response to CDR in lower emissions scenarios was due to the logarithmic response of radiative effects to changes in CO2, where at low atmospheric CO2 concentrations, small changes in CO2 are more effective at changing the global radiative balance than at higher CO2 concentrations. CDR was substantially more effective when implemented at a higher rate, as CDR makes a proportionally larger difference in a climate with lower cumulative air fraction of CO2. Land and soil carbon responses were driven by the scenario-dependent balances between the impacts of CDR on primary productivity from CO2 fertilization, and the impacts on soil respiration from increased soil carbon availability and global temperatures.    

    

* Conjugated polyimides modified self-supported carbon electrodes for electrochemical conversion of CO2 to CO  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400787503
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-07-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.20517/energymater.2024.35")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400787503"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400787503"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400787503"))][Get cited by]]

OpenAlex: https://openalex.org/W4400787503 (Open access: True)
    
[[https://openalex.org/A5102205775][Daming Feng]], [[https://openalex.org/A5101551839][Zuo Li]], [[https://openalex.org/A5102323029][Huifang Guo]], [[https://openalex.org/A5011388287][Xiaodong Sun]], [[https://openalex.org/A5101432604][Peng Huang]], [[https://openalex.org/A5100355567][Ying Sun]], [[https://openalex.org/A5100656258][Hui Li]], [[https://openalex.org/A5069632856][Tianyi Ma]], Energy materials. 4(6)] 2024. https://doi.org/10.20517/energymater.2024.35 
     
The electrochemical reduction of carbon dioxide (CO2RR) offers a promising approach to address the dual challenges of energy scarcity and environmental degradation. This study presents a new, cost-effective, and scalable electrocatalyst: self-supporting carbon paper modified with porous conjugated polyimides. This innovative material facilitates efficient CO2 conversion in aqueous media, eliminating the need for a pyrolysis step. The electrocatalyst’s design utilizes a non-metallic organic polymer with a high density of nitrogen atoms, serving as active sites for catalysis. Its unique mesoporous microsphere structure comprises randomly stacked nanosheets that are generated in situ and aligned along the carbon fibers of carbon paper substrate. This architecture enhances both CO2 adsorption and ensures proper electron transportation, facilitated by the conjugated structure of the polymer. Additionally, the inherent hydrophobicity of conjugated polyimides contributes to its robust catalytic performance in selectively reducing CO2, yielding CO as the primary gaseous product with up to 88.7% Faradaic efficiency and 82.0 mmol g-1 h-1 yield rate. Therefore, the proposed electrocatalyst provides a sustainable solution for electrochemical CO2RR catalyzed by non-metal organic materials, combining high efficiency with the advantages of a simple preparation process and the absence of costly materials or steps. This research contributes to the advancement of CO2RR technologies, potentially leading to more environmentally friendly and energy-efficient solutions.    

    

* Carbon Dioxide Oil Repulsion in the Sandstone Reservoirs of Lunnan Oilfield, Tarim Basin  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400728892
:TOPICS: Characterization of Shale Gas Pore Structure, Hydraulic Fracturing in Shale Gas Reservoirs, Pore-scale Imaging and Enhanced Oil Recovery
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17143503")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400728892"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400728892"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400728892"))][Get cited by]]

OpenAlex: https://openalex.org/W4400728892 (Open access: True)
    
[[https://openalex.org/A5018405074][Zangyuan Wu]], [[https://openalex.org/A5100866680][Qihong Feng]], [[https://openalex.org/A5004183194][Liming Lian]], [[https://openalex.org/A5012335321][Xiangjuan Meng]], [[https://openalex.org/A5101714004][Daiyu Zhou]], [[https://openalex.org/A5062383844][Min Luo]], [[https://openalex.org/A5044222261][Hanlie Cheng]], Energies. 17(14)] 2024. https://doi.org/10.3390/en17143503 
     
The Lunnan oilfield, nestled within the Tarim Basin, represents a prototypical extra-low-permeability sandstone reservoir, distinguished by high-quality crude oil characterised by a low viscosity, density, and gel content. The effective exploitation of such reservoirs hinges on the implementation of carbon dioxide (CO2) flooding techniques. This study, focusing on the sandstone reservoirs of Lunnan, delves into the mechanisms of CO2-assisted oil displacement under diverse operational parameters: injection pressures, CO2 concentration levels, and variations in crude oil properties. It integrates analyses on the high-pressure, high-temperature behaviour of CO2, the dynamics of CO2 injection and expansion, prolonged core flood characteristics, and the governing principles of minimum miscible pressure transitions. The findings reveal a nuanced interplay between variables: CO2’s density and viscosity initially surge with escalating injection pressures before stabilising, whereas they experience a gradual decline with increasing temperature. Enhanced CO2 injection correlates with a heightened expansion coefficient, yet the density increment of degassed crude oil remains marginal. Notably, CO2 viscosity undergoes a substantial reduction under stratigraphic pressures. The sequential application of water alternating gas (WAG) followed by continuous CO2 flooding attains oil recovery efficiency surpassing 90%, emphasising the superiority of uninterrupted CO2 injection over processes lacking profiling. The presence of non-miscible hydrocarbon gases in segmented plug drives impedes the oil displacement efficiency, underscoring the importance of CO2 purity in the displacement medium. Furthermore, a marked trend emerges in crude oil recovery rates as the replacement pressure escalates, exhibiting an initial rapid enhancement succeeded by a gradual rise. Collectively, these insights offer a robust theoretical foundation endorsing the deployment of CO2 flooding strategies for enhancing oil recovery from sandstone reservoirs, thereby contributing valuable data to the advancement of enhanced oil recovery (EOR) technologies in challenging, low-permeability environments.    

    

* Evaluating the near- and long-term role of carbon dioxide removal in meeting global climate objectives  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400656455
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Economic Implications of Climate Change Policies, Social Acceptance of Renewable Energy Innovation
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s43247-024-01527-z")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400656455"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400656455"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400656455"))][Get cited by]]

OpenAlex: https://openalex.org/W4400656455 (Open access: True)
    
[[https://openalex.org/A5002533374][Gaurav Ganti]], [[https://openalex.org/A5062044999][Thomas Gasser]], [[https://openalex.org/A5089539640][Mai Bui]], [[https://openalex.org/A5016996676][Oliver Geden]], [[https://openalex.org/A5002742682][William F. Lamb]], [[https://openalex.org/A5060648323][Jan C. Minx]], [[https://openalex.org/A5033036905][Carl-Friedrich Schleußner]], [[https://openalex.org/A5012881631][Matthew Gidden]], Communications earth & environment. 5(1)] 2024. https://doi.org/10.1038/s43247-024-01527-z 
     
Abstract The 6th Assessment Report from the Intergovernmental Panel on Climate Change lacked sufficient land-sector scenario information to estimate total carbon dioxide removal deployment. Here, using a dataset of land-based carbon dioxide removal based on the scenarios assessed by the Intergovernmental Panel on Climate Change, we show that removals via afforestation and reforestation play a critical near-term role in mitigation, accounting for around 10% (median) of the net greenhouse gas emission reductions between 2020 and 2030 in scenarios that limit warming to 1.5 °C with limited overshoot. Novel carbon dioxide removal technologies such as direct air carbon capture and storage scale to multi-gigatonne levels by 2050 and beyond to balance residual emissions and draw down warming. We show that reducing fossil fuel and deforestation emissions (gross emissions) accounts for over 80% of net greenhouse gas reductions until global net zero carbon dioxide (CO 2 ) independent of climate objective stringency. We explore the regional distributions of gross emissions and total carbon dioxide removal in cost-effective mitigation pathways and highlight the importance of incorporating fairness and broader sustainability considerations in future assessments of mitigation pathways with carbon dioxide removal.    

    

* Impact of the digital economy on carbon dioxide emissions in resource-based cities  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400738479
:TOPICS: Rebound Effect on Energy Efficiency and Consumption, Economic Impact of Environmental Policies and Resources, Socio-Economic Development and Global Economic Challenges
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41598-024-66005-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400738479"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400738479"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400738479"))][Get cited by]]

OpenAlex: https://openalex.org/W4400738479 (Open access: True)
    
[[https://openalex.org/A5090207401][Yang Kuang]], [[https://openalex.org/A5027634735][Yaojun Fan]], [[https://openalex.org/A5104665145][Jie Bin]], [[https://openalex.org/A5008457525][Min Fan]], Scientific reports. 14(1)] 2024. https://doi.org/10.1038/s41598-024-66005-0 
     
With the rapid development of the digital economy, its environmental impact, particularly on carbon dioxide emissions in resource-based cities, has emerged as a vital research topic. Resource-based cities, often central to traditional industries, are confronted with the dual challenges of environmental pollution and economic transformation. This study employs empirical analysis to examine the influence of the digital economy on carbon dioxide emissions in these cities. The findings reveal that the digital economy significantly reduces carbon dioxide emissions, with this impact being more pronounced in the early stages of digital economic development and gradually diminishing thereafter. In the mechanism analysis, we found that the digital economy can reduce carbon dioxide emissions in resource-based cities by raising public concern about the environment. Moreover, the study highlights significant variations in carbon reduction effects among different types of resource-based cities, noting that stronger environmental regulations further enhance these effects. These insights not only provide a new theoretical perspective but also offer practical guidance for policymakers in promoting sustainable development within the digital economy.    

    

* Environmental impact assessment of rapeseed production using the LCA method: Part two: Life cycle impact assessment  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400808072
:TOPICS: Life Cycle Assessment and Environmental Impact Analysis, Sustainable Diets and Environmental Impact, Global E-Waste Recycling and Management
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5937/selsem2401035k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400808072"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400808072"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400808072"))][Get cited by]]

OpenAlex: https://openalex.org/W4400808072 (Open access: True)
    
[[https://openalex.org/A5054487440][Ferenc Kiss]], [[https://openalex.org/A5077862802][Nataša Đurišić‐Mladenović]], [[https://openalex.org/A5006870139][Ana Marjanović‐Jeromela]], Selekcija i semenarstvo. 30(1)] 2024. https://doi.org/10.5937/selsem2401035k 
     
This constitutes the second segment of an environmental life cycle assessment (LCA) study on oilseed rape cultivation in the prevalent conditions of Vojvodina, Serbia. The paper presents the results of the life cycle impact assessment (LCIA) phase of the LCA. The functional unit (FU) is one hectare of agricultural land used for winter rapeseed cultivation, with a reference flow of 3,000 kg of seeds, representing the average yield per hectare. The assessment is focused on the rapeseed production chain, concluding with the transportation of oilseeds to regional silos. The environmental impact assessment employed the ReCiPe 2016 (H) LCIA method, using the OpenLCA software. The study found that the total damage to human health was estimated at 0.0048 DALY, while damage due to biodiversity loss was calculated as 0.0001 species per year. Additionally, the damage resulting from the exploitation of geological mineral reserves was determined to be 167 USD per FU. Notably, land occupation was identified as the primary contributor to biodiversity loss, accounting for 90% of the associated damage within the rapeseed production chain. Meanwhile, the life cycle of diesel fuel, the mineral fertilizer production chain, and nitrogen compound emissions from agricultural land collectively accounted for 74% of the damage to human health and 91% of the damage attributed to mineral resource consumption. On the midpoint level, the ReCiPe 2016 (H) LCIA method calculates results within 18 impact categories, including the impact on global warming and fossil fuel depletion. The cumulative impact of greenhouse gases (GHG) emitted in the rapeseed production chain is equivalent to the impact of 1,970 kg of carbon dioxide. The carbon footprint of rapeseed was estimated at 0.65 kg CO2 eq. per kg of rapeseed. In the production chain of 3,000 kg of rapeseed, 454 kg of oil equivalent is consumed, which means that approximately 6.93 MJ of energy from fossil sources is required to produce 1 kg of rapeseed under the prevalent conditions in Vojvodina. The ReCiPe 2016 method identified and assessed the impact of approximately 750 different emissions with adverse effects on the environment, as well as the impact of around 250 different forms of natural resources consumed or used in the rapeseed production chain. However, the results of the LCIA analysis show that only about ten elementary flows are responsible for over 90% of the total damage in specific protection areas. These primarily include air emissions (carbon dioxide, ammonia, nitrogen oxides, nitrous oxide, sulphur dioxide, and suspended particles), emissions of certain heavy metals into water and soil (hexavalent chromium and zinc), as well as the exploitation of some natural resources, notably arable land, natural gas, and crude oil. The results of the LCIA analysis can be utilized to identify processes and emissions where rationalization or improved control can yield the greatest environmental benefits. The most substantial environmental improvements are expected through the reduction of mineral fertilizer consumption per unit yield and the decrease in diesel fuel usage for field and transportation activities. Furthermore, enhanced control over emissions that contribute significantly to the adverse impacts of the rapeseed production chain can also lead to substantial environmental enhancements.    

    

* Renewable Energy, Economic Policy Uncertainty and Climate Policy Uncertainty: New Evidence for Environmental Kuznets Curve from Emerging and Developed Countries  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400641011
:TOPICS: Economic Impact of Environmental Policies and Resources, Impact of Oil Price Shocks on Economy, The Political Economy of Resource Curse Hypothesis
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16146049")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400641011"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400641011"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400641011"))][Get cited by]]

OpenAlex: https://openalex.org/W4400641011 (Open access: True)
    
[[https://openalex.org/A5099990279][Canan Özkan]], [[https://openalex.org/A5036852678][Nesrin Okay]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16146049 
     
Recent events, such as the financial crisis, oil price shocks or fluctuations, Brexit, the US–China trade war, the COVID-19 pandemic, the Russia–Ukraine conflict and the subsequent energy crisis, have surged global economic policy uncertainty. As climate change has recently been more pronounced around the globe, discussions about climate policies and related uncertainties have also become a major concern. This study investigates the role of economic policy uncertainty (EPU) and climate policy uncertainty (CPU) on climate change (environmental degradation) for selected emerging and developed economies, expanding the IPAT framework and merging it with the Environmental Kuznets Curve (EKC) hypothesis. The IPAT framework examines the impact (I) of population (P), affluence (A), and technology (T) on the environment, whereas the EKC hypothesis proposes an inverted U-shaped curve between affluence and environmental degradation. Two models were created and tested for emerging and developed countries, namely Model 1 with EPU and Model 2 with CPU. A Pooled Mean Group (PMG) estimator is employed to investigate the interrelation between carbon dioxide (CO2) emissions and selected variables; namely the real Gross Domestic Product (GDP) per capita, squared real GDP per capita, renewable share in consumption, the EPU, the CPU and population. Test results indicate that the EKC hypothesis is verified only in Model 1 and for emerging countries, whereas population escalates climate change in both country groups. Furthermore, in line with the consumption effect theorized earlier in the literature, EPU is negatively related to carbon emissions in emerging countries. Thus, the EPU leads to a decrease in the use of energy and pollution-intensive commodities and mitigates climate change in EMEs. Compatible with our ex-ante expectations, renewable energy consumption alleviates climate change in both country groups in the short term. In Model 2, with CPU, we find no evidence supporting the EKC hypothesis for any country groups. However, we reaffirm that renewable energy consumption decreases CO2 emissions in developed countries, which is in support of the argument that energy transition holds the key to tackling climate change. Finally, CPU is associated with a decrease in CO2 emissions in emerging countries in the short term, potentially leading to a reduction in overall economic activity and alleviating climate change. This might also be attributable to the fact that the decisions of economic agents substantially rely on current and future policy (both economic and climate) expectations. Overall, verifying the EKC hypothesis for emerging countries in Model 1, we might argue that there is good potential for emerging countries to save money and time on environmental costs via the adoption of clean technologies and related policies. Last but not least, on a global scale, energy transition with better utilization of renewable sources holds the key to tackling climate change and reducing emissions.    

    

* Greening the Economy from the Ground Up: How the Minimum Wage Affects Firms’ Pollution Emissions in China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400643532
:TOPICS: Economic Impact of Environmental Policies and Resources, Economic Implications of Climate Change Policies, Rebound Effect on Energy Efficiency and Consumption
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16146020")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400643532"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400643532"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400643532"))][Get cited by]]

OpenAlex: https://openalex.org/W4400643532 (Open access: True)
    
[[https://openalex.org/A5017013506][Haili Ren]], [[https://openalex.org/A5020805958][Ming‐Liang Zhu]], [[https://openalex.org/A5043816646][Baolei Lyu]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16146020 
     
The implications of minimum wage standards have been widely debated, but their effects on firms’ pollution emissions and the underlying mechanisms remain underexplored. This paper finds that the introduction of minimum wage standards significantly reduces emissions of pollutants such as carbon dioxide and sulfur dioxide. Firms respond to rising minimum wages by optimizing their product mix, enhancing technological innovation, and improving managerial efficiency, which collectively curb pollution outputs. Our analysis using a random forest model shows that these effects are most pronounced in regions with higher economic development, stringent environmental regulations, and elevated minimum wage standards. Our findings augment the body of research on minimum wage standards and introduce novel insights for emission reduction strategies for firms.    

    

* Environmental emission characteristics of diesel engine performance using biodiesel by cotton and pumpkin seed  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400741908
:TOPICS: Technical Aspects of Biodiesel Production
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.30955/gnj.06066")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400741908"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400741908"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400741908"))][Get cited by]]

OpenAlex: https://openalex.org/W4400741908 (Open access: False)
    
, Global NEST Journal. None(None)] 2024. https://doi.org/10.30955/gnj.06066 
     
<p>The hunt for alternative fuels that may be utilized in place of conventional fuels is intensifying quickly since the availability of fossil fuels is dwindling daily. In this work, biodiesel derived from pumpkin and cotton seed oils is presented for use as diesel engine fuel. Related to diesel, the calorific value of this precise biodiesel is low. In a 4-stroke diesel engine, four mixes (B0, B25, B50, B75 and B100) of biodiesel were evaluated. The engine's emissions and combustion results were contrasted with the diesels. When all blended fuels are related to diesel fuel, the test repercussions illustrate a small increase in the thermal efficiency of the brakes and a decrease in the consumption of fuel specifically for the brake. Emissions of Carbon monoxide and the usage of biodiesel subsequent in a reduction in hydrocarbon emissions and an upsurge in carbon dioxide and nitrogen oxide emissions. The experiment's results showed that biodiesel, which is derived from these seed oils, maybe a useful diesel replacement for compression ignition engines.</p>    

    

* Inside Cover Picture  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400655497
:TOPICS: 
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cjoc.202490162")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400655497"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400655497"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400655497"))][Get cited by]]

OpenAlex: https://openalex.org/W4400655497 (Open access: False)
    
, Chinese journal of chemistry. 42(16)] 2024. https://doi.org/10.1002/cjoc.202490162 
     
Copper‐based catalysts are frequently employed for carbon dioxide reduction reactions (CO 2 RR), yet the regulation of pore structure and surface state of electrocatalysts remains a prominent challenge in previous research endeavors. In this study, we introduce a novel technique to produce mesoporous Cu 2 O nanocrystals, with finely tuned pore size and surface amine functionality leveraging the incorporation of various amine compounds during the oxidative process of copper nanocrystals. The synergistic effect of pore structure confinement and surface amine functionalization culminates in an impressive Faradaic efficiency (FE) of 51.9% for the selective production of C 2 H 4 . More details are discussed in the article by Huang et al . on page 1846—1852. image    

    

* Single Entity Electrocatalysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400729701
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.chemrev.3c00723")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400729701"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400729701"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400729701"))][Get cited by]]

OpenAlex: https://openalex.org/W4400729701 (Open access: False)
    
[[https://openalex.org/A5075876774][Thomas B. Clarke]], [[https://openalex.org/A5050396367][Lynn E. Krushinski]], [[https://openalex.org/A5075464940][Kathryn J. Vannoy]], [[https://openalex.org/A5045294386][Guillermo S. Colón-Quintana]], [[https://openalex.org/A5100784924][Kingshuk Roy]], [[https://openalex.org/A5001089172][Jeffrey E. Dick]], [[https://openalex.org/A5048924296][Christophe Renault]], [[https://openalex.org/A5048541110][Myrtle Hill]], [[https://openalex.org/A5001089172][Jeffrey E. Dick]], Chemical reviews. None(None)] 2024. https://doi.org/10.1021/acs.chemrev.3c00723 
     
Making a measurement over millions of nanoparticles or exposed crystal facets seldom reports on reactivity of a single nanoparticle or facet, which may depart drastically from ensemble measurements. Within the past 30 years, science has moved toward studying the reactivity of single atoms, molecules, and nanoparticles, one at a time. This shift has been fueled by the realization that everything changes at the nanoscale, especially important industrially relevant properties like those important to electrocatalysis. Studying single nanoscale entities, however, is not trivial and has required the development of new measurement tools. This review explores a tale of the clever use of old and new measurement tools to study electrocatalysis at the single entity level. We explore in detail the complex interrelationship between measurement method, electrocatalytic material, and reaction of interest (e.g., carbon dioxide reduction, oxygen reduction, hydrazine oxidation, etc.). We end with our perspective on the future of single entity electrocatalysis with a key focus on what types of measurements present the greatest opportunity for fundamental discovery.    

    

* Assessing Hydrogen Embrittlement in Pipeline Steels for Natural Gas-Hydrogen Blends: Implications for Existing Infrastructure  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400674742
:TOPICS: Hydrogen Embrittlement in Metals and Alloys, Degradation of Materials in Gas Pipelines, Corrosion Inhibitors and Protection Mechanisms
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/solids5030025")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400674742"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400674742"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400674742"))][Get cited by]]

OpenAlex: https://openalex.org/W4400674742 (Open access: True)
    
[[https://openalex.org/A5093969719][Hesamedin Ghadiani]], [[https://openalex.org/A5026407706][Zoheir Farhat]], [[https://openalex.org/A5078094498][Tahrim Alam]], [[https://openalex.org/A5039240704][Md. Aminul Islam]], Solids. 5(3)] 2024. https://doi.org/10.3390/solids5030025 
     
Governments worldwide are actively committed to achieving their carbon emission reduction targets, and one avenue under exploration is harnessing the potential of hydrogen. Blending hydrogen with natural gas is emerging as a promising strategy to reduce carbon emissions, as it burns cleanly without emitting carbon dioxide. This blending could significantly contribute to emissions reduction in both residential and commercial settings. However, a critical challenge associated with this approach is the potential for Hydrogen Embrittlement (HE), a phenomenon wherein the mechanical properties of pipe steels degrade due to the infiltration of hydrogen atoms into the metal lattice structure. This can result in sudden and sever failures when the steel is subjected to mechanical stress. To effectively implement hydrogen-natural gas blending, it is imperative to gain a comprehensive understanding of how hydrogen affects the integrity of pipe steel. This necessitates the development of robust experimental methodologies capable of monitoring the presence and impact of hydrogen within the microstructures of steel. Key techniques employed for this assessment include microscopic observation, hydrogen permeation tests, and tensile and fatigue testing. In this study, samples from two distinct types of pipeline steels used in the natural gas distribution network underwent rigorous examination. The findings from this research indicate that charged samples exhibit a discernible decline in fatigue and tensile properties. This deterioration is attributed to embrittlement and reduced ductility stemming from the infiltration of hydrogen into the steel matrix. The extent of degradation in fatigue properties is correlated not only to the hydrogen content but also to the hydrogen permeability and diffusion rate influenced by steel’s microstructural features, with higher charging current densities indicating a more significant presence of hydrogen in the natural gas pipeline blend.    

    

* Boosting Electrochemical Urea Synthesis via Constructing Ordered Pd–Zn Active Pair  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400658782
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40820-024-01462-w")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400658782"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400658782"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400658782"))][Get cited by]]

OpenAlex: https://openalex.org/W4400658782 (Open access: True)
    
[[https://openalex.org/A5027541982][Weiliang Zhou]], [[https://openalex.org/A5049868081][Chao Feng]], [[https://openalex.org/A5100362356][Xuan Li]], [[https://openalex.org/A5005640447][Xingxing Jiang]], [[https://openalex.org/A5069537889][Lingyan Jing]], [[https://openalex.org/A5102210038][Qi Shuai]], [[https://openalex.org/A5014488148][Qihua Huo]], [[https://openalex.org/A5076813850][Miaoyuan Lv]], [[https://openalex.org/A5029899663][Xinbao Chen]], [[https://openalex.org/A5102620665][T. W. Huang]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5103271655][Na Meng]], [[https://openalex.org/A5009718397][Hengpan Yang]], [[https://openalex.org/A5101453394][Qi Hu]], [[https://openalex.org/A5064805977][Chuanxin He]], Nano-micro letters. 16(1)] 2024. https://doi.org/10.1007/s40820-024-01462-w 
     
Abstract Electrochemical co-reduction of nitrate (NO 3 – ) and carbon dioxide (CO 2 ) has been widely regarded as a promising route to produce urea under ambient conditions, however the yield rate of urea has remained limited. Here, we report an atomically ordered intermetallic pallium-zinc (PdZn) electrocatalyst comprising a high density of PdZn pairs for boosting urea electrosynthesis. It is found that Pd and Zn are responsible for the adsorption and activation of NO 3 – and CO 2 , respectively, and thus the co-adsorption and co-activation NO 3 – and CO 2 are achieved in ordered PdZn pairs. More importantly, the ordered and well-defined PdZn pairs provide a dual-site geometric structure conducive to the key C–N coupling with a low kinetical barrier, as demonstrated on both operando measurements and theoretical calculations. Consequently, the PdZn electrocatalyst displays excellent performance for the co-reduction to generate urea with a maximum urea Faradaic efficiency of 62.78% and a urea yield rate of 1274.42 μg mg –1 h –1 , and the latter is 1.5-fold larger than disordered pairs in PdZn alloys. This work paves new pathways to boost urea electrosynthesis via constructing ordered dual-metal pairs.    

    

* CO2‐to‐CO conversion with over 10% efficiency using earth abundant system in a single‐compartment reactor with oxygen tolerant Mn complex catalyst  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400789469
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemical-Looping Technologies, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401082")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400789469"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400789469"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400789469"))][Get cited by]]

OpenAlex: https://openalex.org/W4400789469 (Open access: False)
    
[[https://openalex.org/A5032289572][Shunsuke Sato]], [[https://openalex.org/A5032320602][Teppei Nishi]], [[https://openalex.org/A5003305079][Naonari Sakamoto]], [[https://openalex.org/A5008137526][Keita Sekizawa]], [[https://openalex.org/A5076624018][Takeshi Morikawa]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401082 
     
The direct conversion of CO2 in flue gas to value‐added chemicals is a potentially important cost‐effective solar‐driven CO2 reduction technology. The present work demonstrates the solar‐powered conversion of CO2 to CO with greater than 10% efficiency using a Mn complex cathode and an Fe‐Ni anode in a single‐compartment reactor without an ion exchange membrane in conjunction with a Si solar cell. Reactors separated by ion exchange membranes are typically used to prevent any effects of oxygen generated by the counter electrode. However, the present Mn complex catalyst maintained its activity even in the presence of 15% O2. Operando surface‐enhanced Raman spectroscopy established that the present Mn catalyst preferentially reacted with CO2 without adsorbing O2. This unique characteristic enabled solar‐driven CO2 reduction using a single‐compartment reactor. In contrast, catalytic metals such as Ag tend to lose activity in such systems as a consequence of reaction with oxygen produced at the anode.    

    

* Altitude controller influence on environmental and economic performance of NGV fuel-powered engines  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400659711
:TOPICS: Transportation Engineering and Maintenance, Advancements in Automotive Engineering and Fuel Technology, Estimating Vehicle Fuel Consumption and Emissions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/e3sconf/202454907010")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400659711"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400659711"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400659711"))][Get cited by]]

OpenAlex: https://openalex.org/W4400659711 (Open access: True)
    
[[https://openalex.org/A5055770319][A.R. Simonyan]], [[https://openalex.org/A5085115818][Karapet Mosikyan]], [[https://openalex.org/A5070850806][Razmik Balayan]], [[https://openalex.org/A5085749289][V.A. Shaghoyan]], E3S web of conferences. 549(None)] 2024. https://doi.org/10.1051/e3sconf/202454907010 
     
The relevance of research is conditioned by the need to ensure efficient operation of the internal combustion engine ICE on NGV fuel at different altitudes above sea level, where there is atmospheric air rarefaction up to 20÷25%. This direction is dictated by the fact that when transferring the ICE operation from gasoline to gas-engine fuel, the engine power decreases from 5 to 15%, moreover, the atmospheric air rarefaction leads to an even greater reduction in engine power and ultimately reduces the performance of the vehicle. Due to violation of the process of combustion of gas-air charge in the cylinder is formed a large amount of carbon monoxide (CO). Research objective is to develop and propose a method of providing such a stoichiometric, fractional composition of the gas-air charge, which will ensure the restoration of the lost power of ICE and provide the optimal value of traction-dynamic characteristics of the car, without increasing toxic emissions. Research object: Variable crosssectional area of the intake manifold path (ICE), adjustable lumen for atmospheric air intake, atmospheric air pressure sensors adjustable diaphragm with stepper motor. Research methods: analytical modeling of the relationship of the aperture diameter depending on the altitude of the terrain above sea level, on the number of revolutions of the ICE, on the density and temperature of the ambient air. The process of combustion of the gas-air charge in the combustion chamber will be evaluated by the fractional composition of the exhaust, exhaust gases. Research results: Qualitative and quantitative assessment of the application of altitude corrector on the ICE operation mode, stability of the value of excess air ratio at different altitudes above sea level, formation of toxic gas, carbon monoxide, as well as carbon dioxide, hydrocarbon, oxygen, etc. is given.    

    

* Climate Change Impacts on Legume Physiology and Ecosystem Dynamics: A Multifaceted Perspective  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400643467
:TOPICS: Impacts of Elevated CO2 and Ozone on Plant Physiology, Nutritional and Functional Potential of Ancient Grains, Intercropping in Agricultural Systems
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16146026")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400643467"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400643467"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400643467"))][Get cited by]]

OpenAlex: https://openalex.org/W4400643467 (Open access: True)
    
[[https://openalex.org/A5018365780][Kirtan Dave]], [[https://openalex.org/A5101216001][Anand Kumar]], [[https://openalex.org/A5021874704][N.K. Davé]], [[https://openalex.org/A5042106860][Mukul Jain]], [[https://openalex.org/A5064312420][Parmdeep Singh Dhanda]], [[https://openalex.org/A5101735071][Alpa Yadav]], [[https://openalex.org/A5066650872][Prashant Kaushik]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16146026 
     
As valuable sources of plant-based protein, leguminous vegetables (grain legumes) are essential for global food security and contribute to body growth and development in humans as well as animals. Climate change is a major challenge for agriculture development that creates major problems for the growth and development of plants. However, legume productivity is threatened by climate change factors, including rising temperatures, shifting precipitation patterns, increased atmospheric carbon dioxide levels, intensified extreme events, and altered pest/pathogen activity. This review synthesizes approximately 136 studies to assess the climate effects on major legume crops. Under all the global emissions trajectories, the mean temperatures are projected to rise beyond the optimal legume growing thresholds by 2050, carrying yield reductions between 10 and 49% for beans, soybeans, cowpeas, and lentils without adaptation measures. The elevated carbon dioxide may transiently enhance the yields up to 18%, but the benefits dramatically decline above 550 ppm and cannot offset the other climate impacts. Altered rainfall along with recurrent drought and heat waves are also expected to decrease the legume crop yields, seed quality, and soil nitrogen levels worldwide. Furthermore, the proliferation of legume pests and fungal diseases poses significant risks, amplified by climate shifts in 84% of the reviewed studies. These multifaceted impacts threaten the productivity gains in leguminous vegetables essential to sustainably meeting the global protein demand. Realizing resilience will require the accelerated development of heat/drought-tolerant legume varieties, enhanced climate-informed agronomic practices, strong policy interventions, and social safety nets explicitly supporting legume producers, in addition to the policies/steps that governments are taking to address the challenges of the climate crisis. This review highlights the essential adaptations and mechanisms required for legume crops to thrive and fulfill their significant roles in global nutrition. It explores how these crops can be improved to better withstand the environmental stresses, enhance their nutritional profiles, and increase their yields. Additionally, the review discusses the importance of legumes in sustainable agriculture and food security, emphasizing their potential to address the future challenges in feeding the growing global population. By focusing on these critical aspects, the review aims to underscore the importance of legumes in ensuring a healthy and sustainable food supply.    

    

* The combined effect of the oxidizing agent and its concentration on the oxidative coupling of methane  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400681384
:TOPICS: Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400877")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400681384"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400681384"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400681384"))][Get cited by]]

OpenAlex: https://openalex.org/W4400681384 (Open access: False)
    
[[https://openalex.org/A5045493905][Wei Zhou]], [[https://openalex.org/A5053769959][Pedro S. F. Mendes]], [[https://openalex.org/A5009265197][Parviz Yazdani]], [[https://openalex.org/A5053653307][Christophe Detavernier]], [[https://openalex.org/A5002483470][Joris Thybaut]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400877 
     
The combined use of O2 and CO2 as oxidizing agents in the oxidative coupling of methane (OCM) has been assessed over two representative OCM catalysts, i.e., La‐Sr/CaO and NaMnW/SiO2, under a wide range of inlet O2 and CO2 concentrations. The overall impact of CO2 was found to depend on the operating conditions and the catalyst used. At O2‐rich conditions, a negative effect of CO2 was observed on C2 selectivity. At O2‐lean conditions, a positive effect of CO2 on both catalysts was observed, likely originating from an enhanced dehydrogenation of C2H6 to C2H4 and limited deep oxidation of the involving hydrocarbons and reaction intermediates. The behavior induced by CO2 is attributed to its mild oxidizing ability and interactions with the catalysts. The enhanced dehydrogenation of C2H6 was observed and confirmed by specific tests with a CO2 and C2H6 feed. Well‐controlled CO2 addition improved the value of the OCM product mixture, mainly due to a 9% increase in C2H4 and a 19% increase in CO selectivity, resulting in a 25% reduction of CO2 at the outlet over the La‐Sr/CaO catalyst. These findings provide new insight into the CO2 effect on OCM and the data to translate this research into OCM process alternatives.    

    

* Clumped Isotope Signatures of Abiotic Methane: The Role of the Combinatorial Isotope Effect  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400735353
:TOPICS: Anaerobic Methane Oxidation and Gas Hydrates, Characterization of Shale Gas Pore Structure, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1029/2023jb028194")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400735353"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400735353"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400735353"))][Get cited by]]

OpenAlex: https://openalex.org/W4400735353 (Open access: True)
    
[[https://openalex.org/A5010002903][Jabrane Labidi]], [[https://openalex.org/A5086168773][T. M. McCollom]], [[https://openalex.org/A5035887674][Thomas Giunta]], [[https://openalex.org/A5062872049][Barbara Sherwood Lollar]], [[https://openalex.org/A5035146459][William D. Leavitt]], [[https://openalex.org/A5051840540][Edward Young]], Journal of geophysical research. Solid earth. 129(7)] 2024. https://doi.org/10.1029/2023jb028194 
     
Abstract Methane clumped isotope signatures of abiogenesis may be diagnostic of the origin of methane on Earth and other planetary bodies. We performed synthesis of abiogenic methane in hydrothermal conditions between 130 and 300°C and determined δ 13 C, δD, Δ 13 CH 3 D, and Δ 12 CH 2 D 2 . The experiments were performed by heating water in the presence of Fe 0 powder and CO. The reduction of water on metallic iron led to the formation of H 2 . CO was reacted with both H 2 and H 2 O, generating both CH 4 and CO 2 . Methane δ 13 C values are isotopically depleted by ∼25‰ relative to the CO starting material. This is consistent with carbon isotopic equilibrium between methane, carbon monoxide and carbon dioxide in our experiments. In contrast, D/H ratios are inconsistent with equilibrium isotopic fractionation, as illustrated by δD values of methane fractionated by ∼500‰ relative to starting H 2 O. This suggests that under our experimental conditions, hydrogen additions to carbon may be governed by kinetics. Δ 13 CH 3 D values track experimental temperature, with values between +1.5‰ and +5.0‰ for most samples. In contrast, Δ 12 CH 2 D 2 values are displaced from equilibrium. We find exclusively negative Δ 12 CH 2 D 2 values, showing deficits down to 40‰ relative to thermodynamic equilibrium. We interpret the data as evidence for distinct, kinetically induced D/H pools contributing to methane assembly, that is, a combinatorial effect. The cumulative D/H fractionations associated with CO hydrogenation explain the direction and magnitude of Δ 12 CH 2 D 2 values during abiotic methane formation. We suggest that near equilibrium Δ 13 CH 3 D with negative Δ 12 CH 2 D 2 signatures will help identify methane formed abiotically in nature.    

    

* Density-Driven CO2 Dissolution in Depleted Gas Reservoirs with Bottom Aquifers  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400677287
:TOPICS: Carbon Dioxide Sequestration in Geological Formations, Pore-scale Imaging and Enhanced Oil Recovery, Hydraulic Fracturing in Shale Gas Reservoirs
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17143491")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400677287"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400677287"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400677287"))][Get cited by]]

OpenAlex: https://openalex.org/W4400677287 (Open access: True)
    
[[https://openalex.org/A5000594357][Xiaocong Lyu]], [[https://openalex.org/A5104601033][Fang Cen]], [[https://openalex.org/A5100750532][Rui Wang]], [[https://openalex.org/A5100709945][Huiqing Liu]], [[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5049346405][Jin‐Xin Xiao]], [[https://openalex.org/A5091771176][Xudong Shen]], Energies. 17(14)] 2024. https://doi.org/10.3390/en17143491 
     
Depleted gas reservoirs with bottom water show significant potential for long-term CO2 storage. The residual gas influences mass-transfer dynamics, further affecting CO2 dissolution and convection in porous media. In this study, we conducted a series of numerical simulations to explore how residual-gas mixtures impact CO2 dissolution trapping. Moreover, we analyzed the CO2 dissolution rate at various stages and delineated the initiation and decline of convection in relation to gas composition, thereby quantifying the influence of residual-gas mixtures. The findings elucidate that the temporal evolution of the Sherwood number observed in the synthetic model incorporating CTZ closely parallels that of the single-phase model, but the order of magnitude is markedly higher. The introduction of CTZ serves to augment gravity-induced convection and expedites the dissolution of CO2, whereas the presence of residual-gas mixtures exerts a deleterious impact on mass transfer. The escalation of residual gas content concomitantly diminishes the partial pressure and solubility of CO2. Consequently, there is an alleviation of the concentration and density differentials between saturated water and fresh water, resulting in the attenuation of the driving force governing CO2 diffusion and convection. This leads to a substantial reduction in the rate of CO2 dissolution, primarily governed by gravity-induced fingering, thereby manifesting as a delay in the onset and decay time of convection, accompanied by a pronounced decrement in the maximum Sherwood number. In the field-scale simulation, the injected CO2 improves the reservoir pressure, further pushing more gas to the producers. However, due to the presence of CH4 in the post-injection process, the capacity for CO2 dissolution is reduced.    

    

* The Impact of Smart Home Technologies on Energy Efficiency, Cost Savings, and Environmental Benefits  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400688412
:TOPICS: Demand Response in Smart Grids, Smart Cities: Innovations and Challenges, Impact of Nighttime Light Data on Various Fields
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.55529/jeet.44.21.32")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400688412"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400688412"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400688412"))][Get cited by]]

OpenAlex: https://openalex.org/W4400688412 (Open access: False)
    
[[https://openalex.org/A5104603533][C. Ukpene Patience]], [[https://openalex.org/A5104603534][Tessy N. Apaokueze]], Journal of energy engineering and thermodynamics. None(44)] 2024. https://doi.org/10.55529/jeet.44.21.32 
     
The results of this study addressed the effectiveness of smart home technologies in terms of energy consumption, cost reduction, and environmental advantages in Nigerian homes. Given the growing energy requirements and concern for the environment, assessing the efficiency of such technologies is critical for socioeconomic development. We collected data using a combination of surveys and statistical analysis in five major Nigerian cities: Lagos, Abuja, Kano, Port Harcourt, and Enugu. We evaluated smart home technologies such as smart thermostats, lighting systems, appliances, plugs, and energy monitoring systems based on their energy savings (%), monthly cost savings (NGN), kilogram of CO2 emissions cut, and percent adoption. We used descriptive analysis and regression modeling to analyze the data collected from the respondents. The introduction of smart technologies reduced general energy use by fifteen to twenty-five percent, with smart appliances recording the highest reduction of up to 25%. This feature demonstrated how monthly cost savings varied depending on the technology and geographical location, resulting in significant increases of up to 4000 NGN per household, each household saw a reduction in CO2 emissions by 500 kg to 700 kg annually, resulting in significant environmental benefits. According to the studies, smart home technologies can help promote energy conservation and therefore reduce CO2 emissions in Nigerian households. However, there are still widely recognized obstacles, like high initial costs and a low level of awareness. offering financial incentives, improving Information Promotion of existing policies and overhauling the distribution systems to increase the pace of uptake and impact returns.    

    

* Reducing stomatal density by expression of a synthetic Epidermal Patterning Factor increases leaf intrinsic water use efficiency and reduces plant water use in a C4 crop  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400785850
:TOPICS: Impacts of Elevated CO2 and Ozone on Plant Physiology, Global Forest Drought Response and Climate Change, Molecular Mechanisms of Photosynthesis and Photoprotection
:PUBLICATION_DATE: 2024-07-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/jxb/erae289")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400785850"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400785850"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400785850"))][Get cited by]]

OpenAlex: https://openalex.org/W4400785850 (Open access: False)
    
[[https://openalex.org/A5003685905][John N. Ferguson]], [[https://openalex.org/A5018808383][Peter Schmuker]], [[https://openalex.org/A5012607855][Anna Dmitrieva]], [[https://openalex.org/A5033055220][Truyen Quach]], [[https://openalex.org/A5087647221][Tieling Zhang]], [[https://openalex.org/A5015211115][Zhengxiang Ge]], [[https://openalex.org/A5089122186][Natalya Nersesian]], [[https://openalex.org/A5005727393][Shirley Sato]], [[https://openalex.org/A5012574725][Thomas E. Clemente]], [[https://openalex.org/A5028507482][Andrew D. B. Leakey]], Journal of experimental botany. None(None)] 2024. https://doi.org/10.1093/jxb/erae289 
     
Abstract Enhancing crop water use efficiency (WUE) is a key target trait for climatic resilience and expanding cultivation on marginal lands. Engineering lower stomatal density to reduce stomatal conductance (gs) has improved WUE in multiple C3 crop species. However, reducing gs in C3 species often reduces photosynthetic carbon gain. A different response is expected in C4 plants because they possess specialized anatomy and biochemistry which concentrates CO2 at the site of fixation. This modifies the photosynthesis (AN) relationship with intracellular CO2 concentration (ci) so that photosynthesis is CO2-saturated and reductions in gs are unlikely to limit AN. To test this hypothesis, genetic strategies were investigated to reduce stomatal density in the C4 crop sorghum. Constitutive expression of a synthetic epidermal patterning factor (EPF) transgenic allele in sorghum, led to reduced stomatal densities, reduced gs, reduced plant water use and avoidance of stress during a period of water deprivation. In addition, moderate reduction in stomatal density did not increase stomatal limitation to AN. However, these positive outcomes were associated with negative pleiotropic effects on reproductive development and photosynthetic capacity. Avoiding pleiotropy by targeting expression of the transgene to specific tissues could provide a pathway to improved agronomic outcomes.    

    

* Interface Engineering and Oxygen Vacancy Derived from Plasma-treated Cu2O Synergistically Enhancing Electrocatalytic CO2-to-C2+ Conversion  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400640883
:TOPICS: Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta03492a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400640883"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400640883"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400640883"))][Get cited by]]

OpenAlex: https://openalex.org/W4400640883 (Open access: False)
    
[[https://openalex.org/A5100444820][Xiaogang Wang]], [[https://openalex.org/A5100541793][Xue Yao]], [[https://openalex.org/A5014251891][Subhajit Jana]], [[https://openalex.org/A5101605827][Yongzan Zhou]], [[https://openalex.org/A5080363764][Chunlan Qin]], [[https://openalex.org/A5063417159][Hongwei Shou]], [[https://openalex.org/A5084441836][Youchao Teng]], [[https://openalex.org/A5100353673][Hao Chen]], [[https://openalex.org/A5100416420][Lidong Zhang]], [[https://openalex.org/A5077238261][Chandra Veer Singh]], [[https://openalex.org/A5054969550][Zhongchao Tan]], [[https://openalex.org/A5003768009][Yimin A. Wu]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta03492a 
     
Electrocatalytic CO2 reduction (ECR) into value-added chemicals and fuels helps tackle the challenges of the energy crisis and global warming. However, this strategy relies heavily on the rational design of...    

    

* Effects of solar thermal in district heating systems – the case of parabolic trough collectors in a high-latitude region  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400700929
:TOPICS: Solar Thermal Energy Technologies, Photovoltaic Maximum Power Point Tracking Techniques, Machine Learning Methods for Solar Radiation Forecasting
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4se00607k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400700929"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400700929"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400700929"))][Get cited by]]

OpenAlex: https://openalex.org/W4400700929 (Open access: True)
    
[[https://openalex.org/A5017601046][Nguyen Le Truong]], [[https://openalex.org/A5025971326][Itai Danielski]], [[https://openalex.org/A5084389931][Benjamin Ahlgren]], [[https://openalex.org/A5010085466][Gireesh Nair]], Sustainable energy & fuels. None(None)] 2024. https://doi.org/10.1039/d4se00607k 
     
This study investigates primary energy use and CO2 emission reduction potential resulted by the integration of solar thermal heating in biomass-based district heating systems in high-latitude regions. A newly commissioned...    

    

* Substrate-dependent oxidative inactivation of a W-dependent formate dehydrogenase involving selenocysteine displacement  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400681578
:TOPICS: Enzyme Immobilization Techniques, Biological and Synthetic Hydrogenases: Mechanisms and Applications, Role of Carbonic Anhydrases in Medicine and Biotechnology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc02394c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400681578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400681578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400681578"))][Get cited by]]

OpenAlex: https://openalex.org/W4400681578 (Open access: True)
    
[[https://openalex.org/A5062685418][Guilherme Vilela-Alves]], [[https://openalex.org/A5013104945][Rita Rebelo Manuel]], [[https://openalex.org/A5076636733][Aldino Viegas]], [[https://openalex.org/A5029338783][Philippe Carpentier]], [[https://openalex.org/A5033418548][Frédéric Biaso]], [[https://openalex.org/A5040768868][Bruno Guigliarelli]], [[https://openalex.org/A5088009129][Inês A. C. Pereira]], [[https://openalex.org/A5001383675][Maria João Romão]], [[https://openalex.org/A5036121779][Cristiano Mota]], Chemical science. None(None)] 2024. https://doi.org/10.1039/d4sc02394c 
     
Metal-dependent formate dehydrogenases are very promising targets for enzyme optimization and design of bio-inspired catalysts for CO2 reduction, towards innovative strategies for climate change mitigation. For effective application of these...    

    

* Environmental Policies and Countermeasures for Phase-Out of Ozone-Depleting Substances (ODS) over the Last 30 Years: Case Study in Taiwan  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400686943
:TOPICS: Atmospheric Aerosols and their Impacts
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.20944/preprints202407.1142.v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400686943"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400686943"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400686943"))][Get cited by]]

OpenAlex: https://openalex.org/W4400686943 (Open access: True)
    
[[https://openalex.org/A5087591655][Wen‐Tien Tsai]], No host. None(None)] 2024. https://doi.org/10.20944/preprints202407.1142.v1 
     
It is well established that the reaction cycles involving some halogenated alkanes (so-called ozone-depleting substances, ODS) contribute to the depletion of ozone in the stratosphere, thus causing the Montreal Protocol (initially signed in 1987) and later amendments. The Protocol called for the scheduled phase-out of ODS, including chlorofluorocarbons (CFC), hydrochloro-fluorocarbons (HCFC), carbon tetrachloride (CCl4), halon, methyl chloroform (CH3CCl3), me-thyl chloride (CH3Cl), and even hydrofluorocarbons (HFCs). In view of the urgent importance of ozone layer protection to the globally ecological environment, the Taiwan government took regulatory actions on reducing ODS consumption since 1993 by the joint-venture of the central competent authorities. Under the regulatory requirements and the industry’s efforts by adopt-ing the alternatives to ODS and abatement technologies, the phase-out of some ODS (i.e., CFC, CCl4, halon, and CH3CCl3) have been achieved prior to 2010. The consumptions of HCFCs and methyl chloride have been significantly declined over the past three decades (1993-2022). However, HFC emission indicated a V-type variation during the period. Due to the local pro-duction and extensive use of HFC in Taiwan, its emissions increased from 663 kilotons of carbon dioxide equivalents (CO2eq) in 1993 to 2,330 kilotons of CO2eq in 2001, and then decreased to 373 kilotons of CO2eq in 2011. Since then, the emissions of HFC largely used as the alternatives to ODS showed an upward trend, increasing to 1,555 kilotons of CO2eq in 2022. To be in compliance with the Kigali Amendment (KA-2015) to the Montreal Protocol for mitigating global warming, the Taiwan government has taken regulatory actions in reducing the consumption of some HFC substances with high global warming potential (GWP) under the authorization of the Climate Change Response Act in 2023, aiming at the baseline consumption in 2024 by 80 % reduction by 2045.    

    

* Beyond the single-basket mindset: A multi-gas approach to better constrain overshoot in near term warming  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400720502
:TOPICS: Waste Heat Recovery for Power Generation and Cogeneration, Economic Implications of Climate Change Policies, Integration of Renewable Energy Systems in Power Grids
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1748-9326/ad6461")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400720502"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400720502"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400720502"))][Get cited by]]

OpenAlex: https://openalex.org/W4400720502 (Open access: True)
    
[[https://openalex.org/A5034225218][Julie Miller]], [[https://openalex.org/A5065071480][G. Dreyfus]], [[https://openalex.org/A5072641814][John Daniel]], [[https://openalex.org/A5025628661][Stephen G. Willis]], [[https://openalex.org/A5004079337][Yangyang Xu]], Environmental research letters. None(None)] 2024. https://doi.org/10.1088/1748-9326/ad6461 
     
Abstract The remaining carbon budget framework tracks progress towards the Paris Agreement’s goal to limit longer-term warming to well below 2 ºC, but no analogous framework exists for constraining mid-century warming. Established single-basket methods of combining gases into CO2-equivalents using Global Warming Potentials (GWPs) lead to ambiguity over what combination of short- and long-lived emissions reductions are needed because they obscure the distinct warming impacts of each. We investigate to what extent a multi-basket approach that separates short-lived and long-lived pollutants can better estimate the likelihood for emission pathways to meet a near-term warming goal. We develop logistic regression models to categorize IPCC emission pathways (AR6) based on whether they exceed a mid-century temperature threshold. We focus on two baskets, using CO2 for long-lived and methane (CH4) for short-lived gases. For comparison, we consider several single-basket approaches (e.g., GWP100, GWP20, GWP*). We further apply our framework to a synthetic dataset covering a broader emissions space. Across both datasets, the two-basket outperforms all single-baskets. Using an illustrative near-term goal (1.7ºC), the two-basket approach reduces the magnitude of overshoot by a factor of 7 compared with the traditional single-basket. The two-basket’s advantage is smaller with the AR6 pathways, which we attribute to the high correlation between CO2 and CH4 emissions and confounding effects from other pollutants. Our results indicate that the two-basket approach better constrains overshoot magnitude, particularly if future emissions deviate from the AR6 assumption of correlated CO2 and CH4 reductions. Our approach allows the determination of a metric value and reduction target in the context of a chosen set of scenarios and temperature threshold; the outcome is a near-term methane-specific emissions budget that can be adopted by decisionmakers in a way that is analogous and complementary to the carbon budget. Future work could consider a third basket for very short-lived pollutants.    

    

* Assessment of the industrial emissions impact on the quality of atmospheric air in the Burlin district of West Kazakhstan region DEVELOPMENT  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400741889
:TOPICS: Impact of Climate Change on Ecosystems and Industries
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.37878/2708-0080/2024-2.14")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400741889"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400741889"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400741889"))][Get cited by]]

OpenAlex: https://openalex.org/W4400741889 (Open access: False)
    
[[https://openalex.org/A5093662445][С.О. Кожагулов]], [[https://openalex.org/A5059724149][Vitaliy Salnikov]], Neftʹ i gaz. 140(2)] 2024. https://doi.org/10.37878/2708-0080/2024-2.14 
     
The article is devoted to the study of air pollution in the Burlin district of the West Kazakhstan region, where one of the main sources of air pollution is the Karachagan oil and gas condensate field, the main feature of which is the high content of hydrogen sulfide in natural gas from 4 to 4.3%. The analysis showed that the atmospheric air state in the specified area is determined by the characteristics of harmful emissions sources, composition, volumes of pollutant emissions and climatic characteristics of the territory, which determine the conditions for the polluting components dispersion. The qualitative and quantitative characteristics of the chemical composition of the atmospheric air in the study area, as well as the features of their changes over the years end climatic seasons, are largely determined by emissions of nitrogen oxides, carbon, sulfur dioxide, hydrogen sulfide, volatile organic compounds and inorganic dust into the atmosphere by oil and gas facilities. The anthropogenic influence of industry in this area is also evidenced by the calculated value of the integral coefficient of air pollution. At the same time, industrial enterprises, having increased the anthropogenic impact on the environment, have the ability to prevent negative environmental consequences. The system of industrial environmental control of the chemical composition of industrial emissions at the Karachagnak field facilities is carried out on an ongoing basis. The analysis showed that a reduction in emissions and, accordingly, a reduction in ground-level concentrations of air pollutants at the Karachagnak field facilities is ensured by a whole range of technological and organizational measures, among which the technology of high-pressure gas reinjection deserves special attention. It necessitates the need to carry out systematic work to study the ecological state of the territory of the Karachagnak field, using not only ground-based research methods, but also modern geoinformation and aerospace technologies that make it possible to dynamically assess the changes taking place, conduct a geo-ecological assessment and make a forecast for the development of the environmental situation in this area. territories. The work carried out contributes to further analysis of the regional assessment of the environmental state of the atmosphere of large industrial centers.    

    

* Pathways Towards Improving the Energy Efficiency of Residential Air &#x96; Conditioning Systems in Saudi Arabia  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400683596
:TOPICS: Building Energy Efficiency and Thermal Comfort Optimization
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1115/1.4065973")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400683596"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400683596"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400683596"))][Get cited by]]

OpenAlex: https://openalex.org/W4400683596 (Open access: False)
    
[[https://openalex.org/A5033698567][Abdulaziz M. Alotaibi]], [[https://openalex.org/A5092952092][Taha K. Makhdoom]], [[https://openalex.org/A5054146406][Awad B. S. Alquaity]], Journal of solar energy engineering. None(None)] 2024. https://doi.org/10.1115/1.4065973 
     
Abstract In Saudi Arabia, the residential electricity consumption approaches 50%, primarily driven by air conditioners (AC). This study explores the potential energy savings and CO2 emission reductions up to 2030 through three scenarios: Business as Usual (BAU), Continuous Improvement Scenario (CIS), and Accelerated Improvement Scenario (AIS). BAU scenario assumes that the current Energy Efficiency Ratio (EER) of 11.8 BTU/Wh is maintained until 2030. CIS considers a 5% EER improvement in new AC stock every 2 or 5 years, while AIS assumes a 10% improvement in EER at the same intervals. Additionally, energy savings and emission reductions possible from varying adoption levels of a new refrigerant (R32) are estimated for three scenarios. Lastly, the CO2 emission reduction under each scenario is computed for two extreme cases of grid emission factor. BAU scenario predicts energy savings of up to 17.7 TWh in 2030 compared to 2020 energy consumption figures. AIS with 2 year intervals results in additional energy savings of 10.1 TWh in 2030 and cumulative energy savings of 37.1 TWh over a decade compared to the BAU scenario. Even CIS with 5 year intervals yields additional energy savings of 1.69 TWh in 2030 and 5.1 TWh cumulatively compared to the BAU scenario. In comparison, the introduction of the new refrigerant results in cumulative energy savings of 10.2 TWh in the best-case scenario. These findings emphasize the importance of enhancing the EER of residential AC systems as a priority in energy efficiency policy.    

    

* A quantitative study on the impact of a community falls pharmacist role, on medicines optimisation in older people at risk of falls  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400655149
:TOPICS: Polypharmacy and Inappropriate Medication Use in Elderly, Health Economics and Quality of Life Assessment, Gait Analysis and Fall Prevention in Elderly
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1186/s12877-024-05189-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400655149"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400655149"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400655149"))][Get cited by]]

OpenAlex: https://openalex.org/W4400655149 (Open access: True)
    
[[https://openalex.org/A5024197865][Paula Crawford]], [[https://openalex.org/A5016358721][Robert C. Plumb]], [[https://openalex.org/A5030586417][Paula Burns]], [[https://openalex.org/A5022855565][Stephen Flanagan]], [[https://openalex.org/A5001150636][Carole Parsons]], BMC geriatrics. 24(1)] 2024. https://doi.org/10.1186/s12877-024-05189-6 
     
Abstract Background The World Falls guidance includes medication review as part of its recommended multifactorial risk assessment for those at high risk of falling. Use of Falls Risk Increasing Drugs (FRIDs) along with polypharmacy and anticholinergic burden (ACB) are known to increase the risk of falls in older people. Method The impact of a community falls pharmacist within a hospital Trust, working as part of a multi-professional community falls prevention service, was evaluated in 92 people aged 65 years or older, by analysing data before and after pharmacist review, namely: number and type of FRIDs prescribed; anticholinergic burden score using ACBcalc ® ; appropriateness of medicines prescribed; bone health review using an approved too; significance of clinical intervention; cost avoidance, drug cost savings and environmental impact. Results Following pharmacist review, there was a reduction in polypharmacy (mean number of medicines prescribed per patient reduced by 8%; p < 0.05) and anticholinergic burden score (average score per patient reduced by 33%; p < 0.05). Medicines appropriateness improved (Medicines Appropriateness Index score decreased by 56%; p < 0.05). There were 317 clinically significant interventions by the community falls pharmacist. One hundred and one FRIDs were deprescribed. Annual cost avoidance and drug cost savings were £40,689-£82,642 and avoidable carbon dioxide (CO 2 ) emissions from reducing inappropriate prescribing amounted to 941 kg CO 2 . Conclusion The community falls pharmacist role increases prescribing appropriateness in the older population at risk of falls, and is an effective and cost-efficient means to optimise medicines in this population, as well as having a positive impact on the environment.    

    

* Sustainable Sludge Management in China: Quantifying GHG Emissions and Exploring Its Reduction Strategies  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400668208
:TOPICS: Solid Waste Management, Phosphorus Recovery and Sustainable Management, Long-term Management of Landfills and Waste
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/pr12071481")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400668208"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400668208"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400668208"))][Get cited by]]

OpenAlex: https://openalex.org/W4400668208 (Open access: True)
    
[[https://openalex.org/A5043903036][Dongming Hu]], [[https://openalex.org/A5102626460][Peng Jiang]], [[https://openalex.org/A5101645463][Yipei Chen]], [[https://openalex.org/A5090125446][Fuyan Gao]], [[https://openalex.org/A5019624996][Shuai Liu]], Processes. 12(7)] 2024. https://doi.org/10.3390/pr12071481 
     
This study aims to evaluate the emissions of greenhouse gases (GHGs) stemming from the sludge treatment sector in China and to investigate the feasibility of novel technologies in curtailing these emissions, with the aim of fostering sustainable sludge management methodologies. Employing a life-cycle assessment (LCA) methodology, the research computed the comprehensive GHG emissions resulting from sludge treatment, taking into consideration diverse elements such as treatment techniques (e.g., landfills, incineration, and land application) and the geographical variations among China’s 660 municipalities. Findings indicate that the total amount of GHG emissions from sludge treatment amounted to 18.54 Mt CO2-eq in 2017, with incineration registering the highest emissions (10,011.53 kg CO2-eq/t dry sludge (DS)), followed by landfills (717.51 kg CO2-eq/t DS) and land application (276.41 kg CO2-eq/t DS). The geographical dispersion of emissions characteristics reveal notable regional disparities, with the top 1% of cities responsible for 34.2% of the overall emissions. The concentration of emissions in the top 1 percent of cities underscores the necessity for tailored mitigation measures that consider localized sustainable development challenges. Principal component analysis (PCA) demonstrates that economic determinants and treatment scales exert substantial influence on emissions, underscoring the imperative of aligning Sustainable Development Goals (SDGs) with economic advancement. To curtail the carbon footprint associated with sludge treatment and enhance sustainability, the study evaluated the emission mitigation potential and expenses of diverse technologies, encompassing thermal conversion, anaerobic digestion, hydrothermal treatment, and wet oxidation. These technologies have the capacity to slash GHG emissions by 0.09–0.46 t CO2-eq/t DS in comparison to traditional approaches, while concurrently advancing resource recuperation and principles of circular economy. For instance, gasification could diminish GHG emissions by 0.33–0.46 t CO2-eq/t DS, whereas anaerobic digestion could yield reductions of 0.09–0.30 t CO2-eq/t DS. The implementation of these innovative technologies across 660 Chinese municipalities could potentially curtail total GHG emissions from sludge treatment by 15–40%. Nevertheless, further enhancements are imperative to refine their environmental and economic efficiency and guarantee enduring sustainability. By deploying these technologies and embracing optimization tactics, China’s sludge treatment sector can make a substantial contribution towards attaining national carbon neutrality objectives and advancing sustainable development.    

    

* Electrochemical CO2 Reduction on Cu-Based Monatomic Alloys: A DFT Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400651340
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.langmuir.4c01246")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400651340"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400651340"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400651340"))][Get cited by]]

OpenAlex: https://openalex.org/W4400651340 (Open access: False)
    
[[https://openalex.org/A5074043148][Xiaojiao Li]], [[https://openalex.org/A5004763124][Liyun Jiang]], [[https://openalex.org/A5101430072][Yong Zhou]], [[https://openalex.org/A5017725939][Qi Yu]], Langmuir. None(None)] 2024. https://doi.org/10.1021/acs.langmuir.4c01246 
     
In recent years, single-atom alloy catalysts (SAAs) have received much attention due to the combination of structural features of both single-atom and alloy catalysts, as well as their efficient catalytic activity, high selectivity, and high stability in various chemical reactions. In this work, we designed a series of Cu-based SAAs by doping isolated 3d transition metal (TM1) atoms on the surface of Cu(111) (TM1 = Fe, Co, Ru, Rh, Os and Ir), in which Ir1/Cu(111) SAAs are considered to be the most stable among 3d-series SAAs due to their optimal binding energy (Eb). The density of states of SAAs have been systematically investigated to further discuss structural properties. Based on density functional theory calculations, the activity and selectivity of Ir1/Cu(111) SAAs are investigated for electrocatalytic CO2 reduction reaction (CO2RR). The initial hydrogenation of CO2 on Ir1/Cu(111) SAAs can form *CO intermediates, which will be further to CH4 production by the pathway of *CO → *CHO → *CHOH → *CH2OH → *CH2 → *CH3 → CH4. This study provides theoretical insights for the rational design of selective Cu-based monatomic alloy catalysts.    

    

* Catalytic Biomass Transformation to Hydrocarbons under Supercritical Conditions over Nickel Supported on Schungite  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400723682
:TOPICS: Supercritical Water Gasification for Hydrogen Production, Catalytic Conversion of Biomass to Fuels and Chemicals, Biomass Pyrolysis and Conversion Technologies
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/pr12071503")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400723682"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400723682"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400723682"))][Get cited by]]

OpenAlex: https://openalex.org/W4400723682 (Open access: True)
    
[[https://openalex.org/A5086233744][Elena O. Schipanskaya]], [[https://openalex.org/A5081421585][Аntonina А. Stepacheva]], [[https://openalex.org/A5080981913][Mariia E. Markova]], [[https://openalex.org/A5101429724][Alexey V. Bykov]], [[https://openalex.org/A5077248316][А. И. Сидоров]], [[https://openalex.org/A5057903687][Valentina G. Matveeva]], [[https://openalex.org/A5017693739][Mikhail G. Sulman]], [[https://openalex.org/A5060128762][Lioubov Kiwi‐Minsker]], Processes. 12(7)] 2024. https://doi.org/10.3390/pr12071503 
     
Liquid fuel production from biomass-derived molecules has received great attention due to the diminished fossil fuel reserves, growing energy demand, and the necessity of CO2 emission reduction. The deoxygenation of oils and fatty acids is a promising process to obtain “green” diesel. Herein, we report the results of the study of the deoxygenation of stearic acid to alkanes as a model reaction. Series of Ni-supported on schungite were obtained by precipitation in subcritical water (hydrothermal deposition) and for comparison via wetness impregnation followed, in both cases, by calcination at 500 °C and a reduction in H2 at 300 °C. The catalyst obtained via hydrothermal synthesis showed a three-fold higher specific surface area with a four-fold higher active phase dispersion compared to the catalysts synthesized via conventional impregnation. The catalysts were tested in stearic acid deoxygenation in supercritical n-hexane as the solvent. Under optimized process conditions (temperature of 280 °C, hydrogen partial pressure of 1.5 MPa, and 13.2 mol of stearic acid per mol of Ni), a close to 100% yield of C10–C18 alkanes, containing over 70 wt.% of targeted n-heptadecane, was obtained after 60 min of reaction.    

    

* First Experience With a New Miniaturized Pump-Driven Venovenous Extracorporeal CO2 Removal System (iLA Activve): A Retrospective Data Analysis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400685349
:TOPICS: Mechanical Circulatory Support Systems
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1201/9781003543480-43")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400685349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400685349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400685349"))][Get cited by]]

OpenAlex: https://openalex.org/W4400685349 (Open access: False)
    
[[https://openalex.org/A5005801467][Alexander Hermann]], [[https://openalex.org/A5057787103][Thomas Staudinger]], [[https://openalex.org/A5049452166][Andja Bojic]], [[https://openalex.org/A5073921083][Katharina Riss]], [[https://openalex.org/A5030237419][Philipp Wohlfarth]], [[https://openalex.org/A5049182625][Oliver Robak]], [[https://openalex.org/A5072949561][Wolfgang R. Sperr]], [[https://openalex.org/A5068176345][Peter Schellongowski]], CRC Press eBooks. None(None)] 2024. https://doi.org/10.1201/9781003543480-43 
     
iLA Activve is a new minimally invasive device for extracorporeal CO2 removal (ECCO2-R) using a miniaturized pump, a special gas exchange membrane, and a double-lumen cannula. We retrospectively analyzed our experiences in 12 patients with hypercapnic respiratory failure undergoing ECCO2-R. Indication for ECCO2-R was hypercapnia due to terminal lung failure during bridging to lung transplantation, pneumonia, and chronic obstructive lung disease or asthma. The median duration of ECCO2-R was 8 days (range 2–30). Seven patients were successfully weaned and five died. Patients with primarily hypoxic lung failure were significantly longer ventilated before ECCO2-R and had a higher mortality rate. Complications were retroperitoneal hematoma after cannulation in one patient and repeated system changes because of clotting in two patients. We observed effective CO2 removal in all patients, with significant reduction in ventilation pressures and minute volumes at median blood flow rates of 1.2–1.4 L/ min. The iLA Activve system using venous double-lumen cannulas proved to be an effective method for ECCO2-R. Invasiveness of ventilation could be reduced. Additional severe impairment of oxygenation and prolonged mechanical ventilation before ECCO2-R are factors of adverse prognosis. The use of ECCO2-R should be thoroughly reconsidered in these cases. ASAIO Journal 2014; 60:342–347. ECCO2-R, iLA Activve, hypercapnia, decarboxylation, extracorporeal    

    

* Experimental Optimization of Natural Gas Injection Timing in a Dual-Fuel Marine Engine to Minimize GHG Emissions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400679400
:TOPICS: Chemical Kinetics of Combustion Processes, Estimating Vehicle Fuel Consumption and Emissions, Aviation's Impact on Global Climate Change
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/gases4030011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400679400"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400679400"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400679400"))][Get cited by]]

OpenAlex: https://openalex.org/W4400679400 (Open access: True)
    
[[https://openalex.org/A5079711092][Luigi De Simio]], [[https://openalex.org/A5035171485][Luca Marchitto]], [[https://openalex.org/A5040158519][Sabato Iannaccone]], [[https://openalex.org/A5092703153][Vincenzo Pennino]], [[https://openalex.org/A5099032046][Nunzio Altieri]], Gases. 4(3)] 2024. https://doi.org/10.3390/gases4030011 
     
Phased injection of natural gas into internal combustion marine engines is a promising solution for optimizing performance and reducing harmful emissions, particularly unburned methane, a potent greenhouse gas. This innovative practice distinguishes itself from continuous injection because it allows for more precise control of the combustion process with only a slight increase in system complexity. By synchronizing the injection of natural gas with the intake and exhaust valve opening and closing times while also considering the gas path in the manifolds, methane release into the atmosphere is significantly reduced, making a substantial contribution to efforts to address climate change. Moreover, phased injection improves the efficiency of marine engines, resulting in reduced overall fuel consumption, lower fuel costs, and increased ship autonomy. This technology was tested on a single-cylinder, large-bore, four-stroke research engine designed for marine applications, operating in dual-fuel mode with diesel and natural gas. Performance was compared with that of the conventional continuous feeding method. Evaluation of the effect on equivalent CO2 emissions indicates a potential reduction of up to approximately 20%. This reduction effectively brings greenhouse gas emissions below those of the diesel baseline case, especially when injection control is combined with supercharging control to optimize the air–fuel ratio. In this context, the boost pressure in DF was reduced from 3 to 1.5 bar compared with the FD case.    

    

* A Retrospective Audit with Subsequent Cost and Environmental Analysis of a Denosumab Self Injection Programme  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400728745
:TOPICS: Intramuscular Injection Techniques and Complications
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/jbmrpl/ziae092")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400728745"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400728745"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400728745"))][Get cited by]]

OpenAlex: https://openalex.org/W4400728745 (Open access: True)
    
[[https://openalex.org/A5031644266][Jack Boylan]], [[https://openalex.org/A5061807430][Jane F. Turton]], [[https://openalex.org/A5097124083][Zita R. Hicks]], [[https://openalex.org/A5094252027][Julia Cottam]], [[https://openalex.org/A5039931180][Michael D. Stone]], JBMR plus. None(None)] 2024. https://doi.org/10.1093/jbmrpl/ziae092 
     
Abstract The Metabolic Bone Health Department, Cardiff and Vale University Health Board, serves a local population of approximately 445 000 people. A retrospective audit of attendance data regarding the Denosumab treatment clinic (the traditional treatment pathway) and the Denosumab Self Injection Programme (SIP) was conducted to determine whether the Self Injection Programme is both cost effective and environmentally beneficial, compared to the traditional treatment pathway. Cost analysis was then conducted by the Finance Department. The audit was conducted over 3 years following the implementation of the service development; 233 patients had enrolled in the program at the time of the audit and 69 had completed 3 years of self- injected treatment. A control group of 497 patients were identified by the service. This group remained on the historical pathway and had consistent attendance activity over the three-year period from 2017 to 2019. Pre and post period activity of all patients on the program was compared, together with the activity for the independent control group. The SIP resulted in a reduction in clinical contacts, with financial analysis showing a total opportunity cost saving per patient of £420 per annum. There were obvious benefits to the patient of a reduced number of visits to a clinical site, which also resulted in an estimated carbon footprint reduction of 59 KG CO2 per patient per annum. The cost analysis is based on our organisation’s 2022 charges. The SIP demonstrates that through focusing on care “closer to home”, it is possible to maximise resources, improve the patient experience through reduced travel and reduce the environmental impact of healthcare.    

    

* Flammability, Toxicity, and Microbiological Properties of Polyurethane Flexible Foams  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400683024
:TOPICS: Microplastic Pollution in Marine and Terrestrial Environments, Self-Healing Polymer Materials, Biodegradable Polymers as Biomaterials and Packaging
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ma17143517")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400683024"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400683024"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400683024"))][Get cited by]]

OpenAlex: https://openalex.org/W4400683024 (Open access: True)
    
[[https://openalex.org/A5010148513][A. Glowacki]], [[https://openalex.org/A5017566232][Przemysław Rybiński]], [[https://openalex.org/A5038361698][Grzegorz Czerwonka]], [[https://openalex.org/A5074875291][Witold Żukowski]], [[https://openalex.org/A5005735304][Ulugbek Zakirovich Mirkhodjaev]], [[https://openalex.org/A5067837451][Monika Żelezik]], Materials. 17(14)] 2024. https://doi.org/10.3390/ma17143517 
     
The aim of the research was to investigate the influence of calcium phosphinate (HPCA) and aluminum phosphinate (HPAL) in synergistic systems with organophosphorus compounds, i.e., diphenylcresyl phosphate (CDP) and trichloropropyl phosphate (TCPP), on the thermal stability, flammability, smoke density, and emission of toxic gases during the thermal decomposition of polyurethane (PUR) foams. Thermogravimetric analysis (TGA), along with cone calorimetry and microcalorimetry, were used to assess the influence of fillers on the thermal stability and flammability of PUR foams. The analysis of toxic gas products was performed with the use of a coupled TG–gas analyzer system. The optical density of gases was measured with the use of a smoke density chamber (SDC). The obtained results showed an increase in thermal stability and a decrease in the flammability of the PUR composites. However, the results regarding smoke and gas emissions, as well as toxic combustion by-products, present ambiguity. On one hand, the applied flame retardant systems in the form of PUR-HPCA-CDP and PUR-HPCA-TCPP led to a reduction in the concentration of CO and HCN in the gas by-products. On the other hand, they clearly increased the concentration of CO2, NOx, and smoke emissions. Microbiological studies indicated that the obtained foam material is completely safe for use and does not exhibit biocidal properties.    

    

* Effect of Dry Mix Alkali Activated Slag Binder Composite Properties Cured in Ambient Condition  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400727261
:TOPICS: Geopolymer and Alternative Cementitious Materials, Fiber Reinforced Concrete in Civil Engineering, Magnesium-Based Cements and Nanomaterials
:PUBLICATION_DATE: 2024-06-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.30955/gnj.05746")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400727261"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400727261"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400727261"))][Get cited by]]

OpenAlex: https://openalex.org/W4400727261 (Open access: False)
    
, Global NEST Journal. None(None)] 2024. https://doi.org/10.30955/gnj.05746 
     
<p>A dry mix (solution-free) alkali-activated slag (a primary cementitious material) and/or fly ash based binder composition is developed that can be cast in-site and consequently cured at ambient temperature. Mortar specimens were cast by mixing slag and or fly ash, river sand, powder form alkaline activators (NaOH 14M, varying solids percentage of Na2SiO3) and water were thoroughly mixed in fabricated equipment. The dry density (28 days) of all specimens showed greater than 2200 kg/m3. The compressive strength (28 days) of all mixes was resulted in higher than 40 N/mm2. Among all the four mixes, a mix F103 with 90% slag, 10% fly ash, 30% Na2SiO3 and 14M NaOH at 3, 7 and 28 days curing showed overall higher compressive strength. It is due to fewer solids content of Na2SiO3. The experimental results indicated that solution free studied binder composite can be developed under ambient conditions eliminating other curing types without compromising in the strength. The studied sustainable mixes require only 12-15 percent water which is less compared to regular used mixes. Thus reduced water quantities can be achieved thereby protects the reduction in volume of water bodies, environment hazards, reduces CO2 emissions due to use of industrial by-products as main binders.</p>    

    

* Understanding the Social Determinants of Household Carbon Emissions for Carbon Mitigation Policies: The Case of Mersin, Turkey  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400644633
:TOPICS: Indoor Air Pollution in Developing Countries, Rebound Effect on Energy Efficiency and Consumption, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-07-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16146012")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400644633"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400644633"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400644633"))][Get cited by]]

OpenAlex: https://openalex.org/W4400644633 (Open access: True)
    
[[https://openalex.org/A5030913473][Ali Cenap Yoloğlu]], [[https://openalex.org/A5104542070][Bulent Halisdemir]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16146012 
     
Households are the main consumer-side source of carbon emissions. In Europe, consumer-based CO2 consumption per capita fell from 10.8 tons to 7.8 tons between 1990 and 2022, but in Turkey, the same data showed a rise from 4 tons to 5 tons. Strategies to reduce carbon emissions have recently shifted their focus from the production side to the consumption side. However, because different social segments have varying levels of price sensitivity and differing levels of necessity regarding consuming different items, a simple tax policy only targeting the consumption side is doomed to fail. This has prompted a discussion of the factors influencing carbon emissions on the consumption side and how those factors affect the amount of emissions. This study aims to identify the social determinants affecting household carbon emission levels and to demonstrate that such differences play an important role in effective and efficient carbon emission reduction strategies. In this case study, an appropriate testing method was used to test whether there are significant differences in dependent variables (carbon emissions) between categories of independent variables (the social determinants of households). As our literature review demonstrates, the social determinants of households and the local context were found to have an impact on carbon emissions in the case study. Nevertheless, we found that the degree of association lessens when the relationship between the dependent variables and the independent variables is re-evaluated while controlling for income level. Consequently, it may be concluded that the primary element influencing carbon emissions is income. In our field study, on the other hand, poverty stood out as another important factor affecting the level of carbon emissions. Poverty affects total household carbon emissions in two different ways, causing both carbon-intensive consumer goods and household appliances with low energy efficiency to be preferred because they are cheap to purchase. Therefore, the fight against poverty should be recognized as an important component of carbon reduction policies in Turkey, and the issue of environmental justice should not be ignored, because we know that 30% of the population was living in poverty (compared to the other 70% receiving the national median income) in 2022.    

    

* Unraveling the Interactions between Flooding Dynamics and Agricultural Productivity in a Changing Climate  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400768498
:TOPICS: Plant Responses to Flooding Stress, Global Flood Risk Assessment and Management, Hydrological Modeling and Water Resource Management
:PUBLICATION_DATE: 2024-07-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16146141")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400768498"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400768498"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400768498"))][Get cited by]]

OpenAlex: https://openalex.org/W4400768498 (Open access: True)
    
[[https://openalex.org/A5046433635][Thidarat Rupngam]], [[https://openalex.org/A5029937356][Aimé J. Messiga]], Sustainability. 16(14)] 2024. https://doi.org/10.3390/su16146141 
     
Extreme precipitation and flooding frequency associated with global climate change are expected to increase worldwide, with major consequences in floodplains and areas susceptible to flooding. The purpose of this review was to examine the effects of flooding events on changes in soil properties and their consequences on agricultural production. Flooding is caused by natural and anthropogenic factors, and their effects can be amplified by interactions between rainfall and catchments. Flooding impacts soil structure and aggregation by altering the resistance of soil to slaking, which occurs when aggregates are not strong enough to withstand internal stresses caused by rapid water uptake. The disruption of soil aggregates can enhance soil erosion and sediment transport during flooding events and contribute to the sedimentation of water bodies and the degradation of aquatic ecosystems. Total precipitation, flood discharge, and total water are the main factors controlling suspended mineral-associated organic matter, dissolved organic matter, and particulate organic matter loads. Studies conducted in paddy rice cultivation show that flooded and reduced conditions neutralize soil pH but changes in pH are reversible upon draining the soil. In flooded soil, changes in nitrogen cycling are linked to decreases in oxygen, the accumulation of ammonium, and the volatilization of ammonia. Ammonium is the primary form of dissolved inorganic nitrogen in sediment porewaters. In floodplains, nitrate removal can be enhanced by high denitrification when intermittent flooding provides the necessary anaerobic conditions. In flooded soils, the reductive dissolution of minerals can release phosphorus (P) into the soil solution. Phosphorus can be mobilized during flood events, leading to increased availability during the first weeks of waterlogging, but this availability generally decreases with time. Rainstorms can promote the subsurface transport of P-enriched soil particles, and colloidal P can account for up to 64% of total P in tile drainage water. Anaerobic microorganisms prevailing in flooded soil utilize alternate electron acceptors, such as nitrate, sulfate, and carbon dioxide, for energy production and organic matter decomposition. Anaerobic metabolism leads to the production of fermentation by-products, such as organic acids, methane, and hydrogen sulfide, influencing soil pH, redox potential, and nutrient availability. Soil enzyme activity and the presence of various microbial groups, including Gram+ and Gram− bacteria and mycorrhizal fungi, are affected by flooding. Waterlogging decreases the activity of β-glucosidase and acid phosphomonoesterase but increases N-acetyl-β-glucosaminidase in soil. Since these enzymes control the hydrolysis of cellulose, phosphomonoesters, and chitin, soil moisture content can impact the direction and magnitude of nutrient release and availability. The supply of oxygen to submerged plants is limited because its diffusion in water is extremely low, and this impacts mitochondrial respiration in flooded plant tissues. Fermentation is the only viable pathway for energy production in flooded plants, which, under prolonged waterlogging conditions, is inefficient and results in plant death. Seed germination is also impaired under flooding stress due to decreased sugar and phytohormone biosynthesis. The sensitivity of different crops to waterlogging varies significantly across growth stages. Mitigation and adaptation strategies, essential to the management of flooding impacts on agriculture, enhance resilience to climate change through improved drainage and water management practices, soil amendments and rehabilitation techniques, best management practices, such as zero tillage and cover crops, and the development of flood-tolerant crop varieties. Technological advances play a crucial role in assessing flooding dynamics and impacts on crop production in agricultural landscapes. This review embarks on a comprehensive journey through existing research to unravel the intricate interplay between flooding events, agricultural soil, crop production, and the environment. We also synthesize available knowledge to address critical gaps in understanding, identify methodological challenges, and propose future research directions.    

    

* Study on the Effect of Fly Ash on Mechanical Properties and Seawater Freeze–Thaw Resistance of Seawater Sea Sand Concrete  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400676666
:TOPICS: Geopolymer and Alternative Cementitious Materials, Mechanical Behavior of Soil Reinforcement Techniques
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/buildings14072191")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400676666"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400676666"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400676666"))][Get cited by]]

OpenAlex: https://openalex.org/W4400676666 (Open access: True)
    
[[https://openalex.org/A5101724036][Jingjing He]], [[https://openalex.org/A5081642157][Chuanwu Sun]], [[https://openalex.org/A5024842018][Xuezhi Wang]], Buildings. 14(7)] 2024. https://doi.org/10.3390/buildings14072191 
     
When using seawater and sea sand as mixes, the mechanical properties and durability of concrete are adversely affected because the raw materials themselves contain harmful ions. Fly ash is the tailings formed in the process of industrial production, the use of which does not require the burning of clinker, reducing CO2 emissions. Moreover, it belongs to a new type of cementitious materials with low emissions and high environmental protection. Fly ash enhances the properties of concrete and reduces the effect of harmful ions on concrete. Based on the above considerations, the corresponding specimens were prepared and subjected to cubic compressive strength, flexural strength, and seawater freezing and thawing resistance tests by using fly ash admixture as the main variable. A combination of macro-analysis and micro-analysis was used to investigate the effect of fly ash on the performance of seawater sea sand concrete. The results showed that fly ash significantly enhanced the mechanical properties and resistance to seawater freezing and thawing of seawater sea sand concrete. The best improvement in compressive strength and resistance to seawater freezing and thawing was achieved at a substitution rate of 20%. The maximum increase in compressive strength was 13.22%. The maximum reduction in mass loss rate was 57.26% and the strength loss rate was 43.14% after the specimens were subjected to seawater freezing and thawing 75 times. The maximum enhancement in flexural strength was 17.06% for a substitution rate of 10%. Through microanalysis, it can be seen that the incorporation of coal ash can enhance the compactness of concrete through the microaggregate effect as well as the volcanic ash reaction to promote the secondary hydration reaction, so as to strengthen the seawater freeze–thaw resistance of seawater sea sand concrete. Finally, the damage prediction model established using the mean GM (1, 1) model of gray system theory meets the requirements of the first level of prediction accuracy and can accurately predict the damage of seawater sea sand concrete under seawater freezing and thawing.    

    

* Spotlight on Secondary Metabolites Produced by an Early-Flowering Apulian Artichoke Ecotype Sanitized from Virus Infection by Meristem-Tip-Culture and Thermotherapy  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400682113
:TOPICS: Artichoke Nutraceutical and Functional Food Research, Antioxidants and Free Radicals in Health and Disease, Medicinal Properties of Stinging Nettle
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/antiox13070852")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400682113"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400682113"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400682113"))][Get cited by]]

OpenAlex: https://openalex.org/W4400682113 (Open access: True)
    
[[https://openalex.org/A5048774729][Roberta Spanò]], [[https://openalex.org/A5063736033][Patrizia Gena]], [[https://openalex.org/A5011247203][Vito Linsalata]], [[https://openalex.org/A5049971650][Valeria Sini]], [[https://openalex.org/A5051502295][Isabella D’Antuono]], [[https://openalex.org/A5066364159][Angela Cardinali]], [[https://openalex.org/A5059773876][Pietro Cotugno]], [[https://openalex.org/A5072803870][Giuseppe Calamita]], [[https://openalex.org/A5051236535][Tiziana Mascia]], Antioxidants. 13(7)] 2024. https://doi.org/10.3390/antiox13070852 
     
Globe artichoke (Cynara cardunculus L. subsp. scolymus) is an important crop of the Mediterranean basin characterized by many properties, like hepatoprotective, anticarcinogenic, antioxidant, antibacterial, and beneficial to human health. The high bioactive compounds (BACs) content, as polyphenols, has attracted the research interest in artichoke extracts. We analysed the changes in polyphenol transcriptome profile between sanitized (S) virus-free and non-sanitized (NS) artichoke plants, focusing on genes involved in phenylpropanoid metabolic pathway and flavonoid biosynthesis. A total of 2458 upregulated and 2154 downregulated differentially expressed genes (DEGs) were functionally characterized. Among them, 31 and 35 KEGG orthology entries characterized by upregulated and downregulated DEGs, respectively, were involved in the biosynthesis of other secondary metabolites. A downregulation of PAL, C4H, 4CL, HST/HQT, C3′H, CCoAMT, CCR1, and F5H, was observed in S artichoke compared to NS one, whereas the CSE, CHS, and CHI genes were upregulated in S samples. Transcriptome results were compared to the polyphenols accumulation in S and NS artichoke leaves. A higher content of total polyphenols was observed in older leaves of NS samples, compared to extracts obtained from young leaves or from S plants, and this result was associated with the presence of viral infections in NS plants. In all the conditions tested, the most represented compound was chlorogenic acid, followed by luteolin-7-O-glucoside. The different composition of each extract was evaluated by a polyphenol dose–response treatment on the rodent hepatoma FaO cell line to the accumulation of reactive oxygen species (ROS). A significant reduction in ROS content ranging between −40% and −48% was observed when 10–20 mg/L of polyphenols from NS or S plants were used, characterized by a specific profile of compounds. To reduce MetOH residues in polyphenol extracts, a supercritical fluid CO2 extraction was evaluated to propose a sustainable green extraction.    

    

* Using historical temperature to constrain the climate sensitivity, the transient climate response, and aerosol-induced cooling  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400782529
:TOPICS: Climate Change and Variability Research, Numerical Weather Prediction Models, Global Methane Emissions and Impacts
:PUBLICATION_DATE: 2024-07-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/acp-24-8105-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400782529"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400782529"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400782529"))][Get cited by]]

OpenAlex: https://openalex.org/W4400782529 (Open access: True)
    
[[https://openalex.org/A5007117541][Olaf Morgenstern]], Atmospheric chemistry and physics. 24(14)] 2024. https://doi.org/10.5194/acp-24-8105-2024 
     
Abstract. The most recent generation of climate models that has informed the Sixth Assessment Report (AR6) of the Intergovernmental Panel on Climate Change (IPCC) is characterized by the presence of several models with larger equilibrium climate sensitivities (ECSs) and transient climate responses (TCRs) than exhibited by the previous generation. Partly as a result, AR6 did not use any direct quantifications of ECSs and TCRs based on the 4×CO2 and 1pctCO2 simulations and relied on other evidence when assessing the Earth's actual ECS and TCR. Here I use historical observed global-mean temperature and simulations produced under the Detection and Attribution Model Intercomparison Project to constrain the ECS, TCR, and historical aerosol-related cooling. I introduce additivity criteria that disqualify 8 of the participating 16 models from consideration in multi-model averaging calculations. Based on the remaining eight models, I obtain an average adjusted ECS of 3.5 ± 0.4 K and a TCR of 1.8 ± 0.3 K (both at 68 % confidence). Both are consistent with the AR6 estimates but with substantially reduced uncertainties. Furthermore, importantly I find that the optimal cooling due to short-lived climate forcers consistent with the observed temperature record should, on average, be about 47 % ± 39 % of what these models simulate in their aerosol-only simulations, yielding a multi-model mean, global-mean, and annual-mean cooling due to near-term climate forcers for 2000–2014, relative to 1850–1899, of 0.24 ± 0.11 K (at 68 % confidence). This is consistent with but at the lower end of the very likely uncertainty range of the IPCC's AR6. There is a correlation between the models' ECSs and their aerosol-related cooling, whereby large-ECS models tend to be associated also with strong aerosol-related cooling. The results imply that a reduction in the aerosol-related cooling, along with a more moderate adjustment of the greenhouse-gas-related warming for most models, would bring the historical global-mean temperature simulated by these models into better agreement with observations.    

    

* GOLD ENRICHMENT MECHANISM IN MID-OCEAN RIDGE HYDROTHERMAL SYSTEMS: AN EXAMPLE FROM THE LONGQI HYDROTHERMAL FIELD ON THE ULTRASLOW-SPREADING SOUTHWEST INDIAN RIDGE  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400642729
:TOPICS: Machine Learning for Mineral Prospectivity Mapping, Tectonic and Geochronological Evolution of Orogens, Geochemistry of Manganese Oxides in Sedimentary Environments
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5382/econgeo.5095")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400642729"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400642729"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400642729"))][Get cited by]]

OpenAlex: https://openalex.org/W4400642729 (Open access: False)
    
[[https://openalex.org/A5102754079][Kean Chen]], [[https://openalex.org/A5063191044][Huichao Zhang]], [[https://openalex.org/A5047612204][Nigel J. Cook]], [[https://openalex.org/A5103247739][Tao Wu]], [[https://openalex.org/A5023780582][Fang An]], [[https://openalex.org/A5103843175][Jin Liang]], [[https://openalex.org/A5104076106][Weifang Yang]], Economic geology and the bulletin of the Society of Economic Geologists. None(None)] 2024. https://doi.org/10.5382/econgeo.5095 
     
Abstract In mid-ocean ridge (MOR) hydrothermal systems, the gold grade of sea-floor massive sulfides (SMSs) is negatively correlated with the spreading rate of the ridge. Previous investigations have addressed the distribution of gold in sulfides from hydrothermal fields hosted by ultramafic rocks. In contrast, the gold enrichment mechanisms in sulfides from hydrothermal fields hosted by mafic rocks in ultraslow-spreading ridge environments are less well constrained. The basalt-hosted Longqi hydrothermal field, located on the classic ultraslow-spreading Southwest Indian Ridge, provides an opportunity to examine gold enrichment mechanisms in such an environment. Two ore-forming stages are identified in chimney fragments: anhydrite + barite + colloidal/porous pyrite (Py1) + marcasite + fine-grained sphalerite (stage 1); euhedral-subhedral pyrite (Py2) + coarse-grained sphalerite + chalcopyrite + isocubanite (stage 2). Py1 is usually overgrown by marcasite, which is in turn enclosed by Py2. Py2 coexists with coarse-grained sphalerite and chalcopyrite. Abundant native gold nanoparticles occur in Py1 or at the transition zone between Py1 and Py2. Laser ablation inductively coupled plasma mass spectrometry (LA-ICP-MS) analysis suggests that Py1 contains higher Mo, V, Sn, and Pb and lower As, Co/Ni, and Se/Tl values compared to Py2. In situ LA-multicollector (MC)-ICP-MS analyses show that Py1 has a higher mean δ34S (+7.1‰) value than Py2 (+6.6‰). Sulfur primarily derives from MORB and seawater sulfate, of which the proportion of sulfur from seawater sulfate is between 20.5 and 47.6%. Textures, mineral assemblages, and trace element contents of sulfides indicate that the degree of mixing between hydrothermal fluids and seawater decreases as the chimney grows and is accompanied by a gradual increase in temperature. Based on data compiled from 41 hydrothermal fields hosted by basalt, the large range of sulfide δ34S from slow- and ultraslow-spreading MORs may be attributed to the wide range of sulfur sources (e.g., leaching from MOR basalt, thermochemical reduction of seawater sulfate, magma degassing, and bacterial activity), fluid-basalt interaction, and redox state (CH4/CO2 ratios). Prolonged fluid-basalt interaction and the type of chimneys, such as beehive chimneys, may lead to higher gold grades in hydrothermal fields. Moreover, low H2S content may be an important contributor to gold enrichment in basalt-hosted SMS deposits in ultraslow-spreading MOR environments.    

    

* International convergence towards a climate-neutral economy: modeling the agricultural sector  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4400700094
:TOPICS: Economic Implications of Climate Change Policies, European Agricultural Policy and Reform
:PUBLICATION_DATE: 2024-06-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.51599/are.2024.10.02.03")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400700094"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400700094"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400700094"))][Get cited by]]

OpenAlex: https://openalex.org/W4400700094 (Open access: True)
    
[[https://openalex.org/A5034084864][Andriy Krysovatyy]], [[https://openalex.org/A5017278528][Iryna Maksymova]], [[https://openalex.org/A5008587756][Vitalina Kuryliak]], [[https://openalex.org/A5043974315][Michael A. Radin]], [[https://openalex.org/A5099737620][Maksym Kurilyak]], Agricultural and resource economics. 10(2)] 2024. https://doi.org/10.51599/are.2024.10.02.03 
     
Purpose. This article aims to construct a comprehensive convergent model for assessing the global and EU’s progress, degree of consolidation and symmetry of agricultural economies towards climate neutrality in the context of key international green initiatives. Methodology / approach. This research employs both qualitative and quantitative analyses to assess convergence measures in the agricultural sector’s carbon emissions. The quantitative component relies on the sigma and beta convergence models to evaluate international convergence in carbon emissions CO2 dynamics. The dimensions of modeling are as follows: global sample within 194 countries with reliable emissions data; European Union, focusing on convergence within the EU27 member states, the United Kingdom, and Ukraine. The time period covers open data from 1972–2022. The dynamics of sigma and beta convergence is determined for the points, namely UN Stockholm Conference (1972), UN Rio Conference (1992), Kyoto Protocol (entry into force in 2005), Paris Agreement (2015). Additionally, statistical indicators of variation, skewness, Gini and Theil indices were calculated for delineating global smoothness and the concentration of agricultural emissions. Results. The results of the study reveal an inertial and divergent trend of the agricultural economy towards decarbonisation, which slows down the overall movement towards “net zero” due to the presence of clubs of lagging agricultural countries that increase emissions in violation of international agreements. The reduction in emissions skewness in recent years shows that more countries are “pulling” decarbonisation due to their high capacity to move towards net zero, but this is not enough. The EU is the most prominent example of accelerated climate convergence, but markers of its weakening in recent years are identified due to the inability of economies to maintain the pace of decarbonisation caused by economic constraints, technological barriers, policy and regulatory issues, and misunderstandings of climate neutrality goals. It is shown that the long-term decarbonisation capacity of the agricultural sector is the key trigger for a country to make a positive contribution to the global convergence towards climate neutrality. At the current stage, the pace of decarbonisation plays a much greater role for consolidating efforts in the agricultural economy and achieving climate neutrality than the initial level of emissions in the sector. Factors in this process include proactive compliance with global climate agreements, technology sharing and cooperation, digitalisation and smart agriculture, and green financing and investment. Its implementation requires a three-way integration of stakeholder actions, strategy selection and results evaluation. Originality / scientific novelty. The study’s originality lies in its large-scale analysis of over 50 years of emissions dynamics and the context of five key green agreements that provided support for the green transition. It allows studying international convergence in agricultural sectors globally and within the EU. The novelty implies the integrated use of sigma and beta convergence models that identifies predictors of convergent and divergent processes and separates countries into leaders and laggards of agricultural decarbonisation. This approach provides a comprehensive view of modern climate policy, the impact of international green initiatives, and the position of individual towards climate neutrality in agriculture. Practical value / implications. The practical value lies in the ability to adjust climate policies for the agricultural economy’s decarbonisation, facilitating the determination of prospective outcomes for achieving climate neutrality. The aforementioned factors facilitate the process of governmental decision-making. The assessment of international programmatic agreements' effectiveness is enhanced through these models. The study offers a framework for global convergence towards climate neutrality in agriculture, highlighting the importance of digital technologies and smart agriculture as significant factors in global convergence.    

    
