#+filetags: CO2RR
#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Sun Feb 18 00:47:08 2024

Found 27 results from 2024-02-11 to 2024-02-18
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* The Influence of the Cu Foam on the Electrochemical Reduction of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391753550
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/inorganics12020057")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391753550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391753550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391753550"))][Get cited by]]

OpenAlex: https://openalex.org/W4391753550 (Open access: True)
    
[[https://openalex.org/A5035631045][Yuan-Gee Lee]], [[https://openalex.org/A5016437027][Hui-Hsuan Chiao]], [[https://openalex.org/A5084275546][Yu–Ching Weng]], [[https://openalex.org/A5045826984][Chyi-How Lay]], Inorganics (Basel). 12(2)] 2024. https://doi.org/10.3390/inorganics12020057  ([[https://www.mdpi.com/2304-6740/12/2/57/pdf?version=1707641709][pdf]])
     
Unlike the flat Cu sheet, we employed Cu foam to explore the specific porous effect on the expanding specific area. We found that the foam structure is superior to the sheet feature in the specific location from the morphology investigation. In the practical measurement of surface area, we found that the adsorbate could aptly agglomerate, resulting in a consequential block in the transport path. The specific location of the Cu foam was underestimated because the channels of the deep foam layer were blocked by the agglomerated adsorbate. To explore the protonation process of the electro-reduction, we adopted the carbonate electrolyte as the control group in contrast to the experimental group, the bicarbonate electrolyte. In the carbonate electrolyte, the primary intermediate was shown to be CO molecules, as verified using XPS spectra. In the bicarbonate electrolyte, the intermediate CO disappeared; instead, it was hydrogenated as a hydrocarbon intermediate, CHO*. The bicarbonate ion was also found to suppress electrocatalysis in the deep structure of the Cu foam because its high-molecular-weight intermediates accumulated in the diffusion paths. Furthermore, we found a promotion of the oxidation valence on the electrode from Cu2O to CuO, when the electrode structure transformed from sheet to foam. Cyclic voltammograms demonstrate a succession of electro-reduction consequences: at low reduction potential, hydrogen liberated by the decomposition of water; at elevated reduction potential, formic acid and CO produced; and at high reduction potential, CH4 and C2H4 were formed from −1.4 V to −1.8 V.    

    

* Recent Progress of MXene as a Cocatalyst in Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391760771
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Two-Dimensional Materials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceja.2024.100593")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391760771"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391760771"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391760771"))][Get cited by]]

OpenAlex: https://openalex.org/W4391760771 (Open access: True)
    
[[https://openalex.org/A5082818904][Zhe Wang]], [[https://openalex.org/A5020377897][Samar Al Jitan]], [[https://openalex.org/A5058905109][Inas M. AlNashef]], [[https://openalex.org/A5087660437][Blaise L. Tardy]], [[https://openalex.org/A5035367466][Giovanni Palmisano]], Chemical Engineering Journal Advances. None(None)] 2024. https://doi.org/10.1016/j.ceja.2024.100593 
     
Due to the excessive consumption of fossil fuel resources and the emission of a substantial quantity of CO2 into the environment, it is urgent to develop clean energy solutions. In order to reduce carbon emissions from the source, it is effective approach to convert CO2 into various renewable energy fuels. Inspired by the photosynthesis of green plant, CO2 is converted into clean fuel with the aid of catalysts. Regarding the separation and transfer of photogenerated charge carriers, and inadequate adsorption and activation of CO2 on the surface of catalysts, the current semiconductors utilized in photocatalysis have low efficiency. As a result, the current efficiency of photocatalysts is far from meeting the need for practical industrial demands. MXene materials, for example Ti3C2Tx (9980 S cm−1), have emerged as a promising candidate for CO2 reduction due to the significant number of active sites for functional groups, high conductivity and low defects, large surface areas, and outstanding visible light photoelectronic properties. This review provides a critical overview of the recent progress regarding MXene as a co-catalyst in photocatalytic CO2 reduction systems. We systemically explore the fundamental principles and reaction mechanisms associated with separating and transferring photogenerated charge carriers. Additionally, we investigate the basic properties of MXene as a co-catalyst in the context of CO2 reduction. Furthermore, this review also elucidates the impacts of the microstructure of photocatalysts on enhancing photocatalytic performance. Finally, the challenges and opportunities in using MXene as a co-catalyst for CO2 reduction have been presented to inspire further research in this field.    

    

* High selective electrocatalytic reduction of carbon dioxide to ethylene enabled by regulating the microenvironment over Cu-Ag nanowires  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391850244
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.02.028")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391850244"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391850244"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391850244"))][Get cited by]]

OpenAlex: https://openalex.org/W4391850244 (Open access: False)
    
[[https://openalex.org/A5045324032][D. D. Fan]], [[https://openalex.org/A5037700860][Zhang Shi-ji]], [[https://openalex.org/A5086243301][Yumeng Li]], [[https://openalex.org/A5048916799][Bin Hua]], [[https://openalex.org/A5005268469][Ruopeng Li]], [[https://openalex.org/A5025757874][Yaqiang Li]], [[https://openalex.org/A5070825762][Anmin Liu]], [[https://openalex.org/A5089539354][Peixia Yang]], [[https://openalex.org/A5031711386][Jinqiu Zhang]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.02.028 
     
Copper-based tandem catalysts are effective candidates for yielding multi-carbon (C2+) products in electrochemical reduction of carbon dioxide (CO2RR). However, these catalysts still face a significant challenge regarding in the low selectivity for the production of a specific product. In this study, we report a high selectivity of 77.8 %±2% at −1.0 V (vs RHE) for the production of C2H4 by using a Cu88Ag12NW catalyst which is primarily prepared through a combined Cu-Ag co-deposition and wet chemical method, employing an attractive strategy focused on regulating the microenvironment over Cu-Ag nanowires. The experimental and computational studies show that the higher *CO coverage and lower intermediate adsorption energy are important reasons for achieving the high C2H4 selectivity of Cu88Ag12NW catalyst. Comsol simulation results indicate that dense nanowires exhibit a nano-limiting effect on OH− ions, thereby leading to an increase in local pH and promoting coupling reactions. The catalyst demonstrates no noticeable decrease in current density or selectivity even after 12 h of continuous operation. The Cu-Ag nanowire composite exhibits remarkable catalytic activity, superior faradaic efficiency, excellent stability, and easy synthesis, which highlights its significant potential for electro-reducing carbon dioxide into valuable products.    

    

* Surface Termination Dependent Carbon Dioxide Reduction Reaction on Ti3C2 MXene  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391853343
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Accelerating Materials Innovation through Informatics, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00320a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391853343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391853343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391853343"))][Get cited by]]

OpenAlex: https://openalex.org/W4391853343 (Open access: True)
    
[[https://openalex.org/A5080818001][Ling Meng]], [[https://openalex.org/A5087707184][Likai Yan]], [[https://openalex.org/A5012273051][Francesc Illas]], [[https://openalex.org/A5012273051][Francesc Illas]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d4ta00320a  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ta/d4ta00320a][pdf]])
     
The use of two-dimensional (2D) MXene materials as highly efficient electrocatalysts for carbon dioxide reduction reaction (CO 2 RR) has gained considerable attention in the last years. However, current computational studies on...    

    

* Photocatalytic sponges for wastewater treatment, carbon dioxide reduction, and hydrogen production: a review  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391881021
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10311-024-01696-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391881021"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391881021"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391881021"))][Get cited by]]

OpenAlex: https://openalex.org/W4391881021 (Open access: False)
    
[[https://openalex.org/A5023804914][Akash Balakrishnan]], [[https://openalex.org/A5084872777][Meenu Mariam Jacob]], [[https://openalex.org/A5013338055][Mahendra Chinthala]], [[https://openalex.org/A5083688944][Nanditha Dayanandan]], [[https://openalex.org/A5009615295][M. N. Ponnuswamy]], [[https://openalex.org/A5072272612][Dai‐Viet N. Vo]], Environmental Chemistry Letters. None(None)] 2024. https://doi.org/10.1007/s10311-024-01696-5 
     
No abstract    

    

* Analysis of reduction of carbon dioxide emissions from blast furnace under conditions of using advanced and existing blast furnace melting technologies  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391829285
:TOPICS: Reduction Kinetics in Ironmaking Processes, Underground Coal Gasification: Fundamentals and Applications, Innovative Mining Technology and Sustainable Development
:PUBLICATION_DATE: 2023-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.52150/2522-9117-2023-37-158-174")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391829285"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391829285"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391829285"))][Get cited by]]

OpenAlex: https://openalex.org/W4391829285 (Open access: False)
    
[[https://openalex.org/A5033046194][А. Л. Чайка]], [[https://openalex.org/A5047429694][B. V. Kornilov]], [[https://openalex.org/A5075385238][A. O. Moskalyna]], [[https://openalex.org/A5030140539][V. V. Lebid]], [[https://openalex.org/A5062357536][M. M. Iziumskyi]], [[https://openalex.org/A5091958627][M. H. Dzhyhota]], Fundamental and applied problems of ferrous metallurgy. 37(None)] 2023. https://doi.org/10.52150/2522-9117-2023-37-158-174 
     
The article discusses the results of heat and power and exergy calculations of the possibilities of new and existing technologies to reduce carbon dioxide emissions and coke consumption, increase pig iron production by injecting hydrogen and hydrogen-containing fuel additives (coke and natural gas) into the furnace, using metal additives, increasing the blast temperature, heat losses, and improving gas distribution in the blast furnace. The calculations were performed using a mathematical model of the complete energy balance of blast furnace smelting developed at the Iron and Steel Institute of Z. I. Nekrasov National Academy of Sciences of Ukraine, and the impact of the potential of new and existing technologies on reducing CO2 emissions and technical and economic indicators of blast furnace smelting was assessed when the consumption of pulverized coal, hydrogen and hydrogen-containing fuel additives and their combinations in a wide range was changed. The limit values for the injection of hydrogen and hydrogen-containing fuel additives into the blast furnace horn have been determined, which are determined by the following factors: the degree of direct reduction of iron, theoretical combustion temperature, the presence of industrial oxygen, and the temperature of the furnace gas. The study results showed that CO2 emissions in blast furnace production can be reduced by 25-30% by making changes to blast furnace technology and depend on investments, the raw material and energy base of the steelmaker, and the level of existing blast furnace technology. The paper considers the impact of low-cost measures to increase the blast temperature, use of clean metal additives, reduce heat losses, and improve gas distribution in the blast furnace on the reduction of carbon dioxide emissions and technical and economic indicators of blast furnace smelting. The results can be useful for determining the economic feasibility of a particular measure to reduce CO2 emissions in blast furnace production.    

    

* Graphene-based CO2 reduction electrocatalysts: A review  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391768389
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Thermoelectric Materials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/s1872-5805(24)60839-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391768389"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391768389"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391768389"))][Get cited by]]

OpenAlex: https://openalex.org/W4391768389 (Open access: True)
    
[[https://openalex.org/A5038427980][Zelin Wu]], [[https://openalex.org/A5009018022][Congwei Wang]], [[https://openalex.org/A5052309941][Xiaoxiang Zhang]], [[https://openalex.org/A5029883974][Quangui Guo]], [[https://openalex.org/A5029316647][Junying Wang]], New Carbon Materials. 39(1)] 2024. https://doi.org/10.1016/s1872-5805(24)60839-5 
     
The reduction of carbon dioxide (CO2) by electrochemical methods for the production of fuels and value-added chemicals is an effective strategy for overcoming the global warming problem. Due to the stable molecular structure of CO2, the design of highly selective, energy-efficient and cost-effective electrocatalysts is key. For this reason, graphene and its derivatives are competitive for CO2 electroreduction with their unique and excellent physical, mechanical and electrical properties and relatively low cost. In addition, the surface of graphene-based materials can be modified using different methods, including doping, defect engineering, production of composite structures and wrapped shapes. We first review the fundamental concepts and criteria for evaluating electrochemical CO2 reduction, as well as the catalytic principles and processes. Methods for preparing graphene-based catalysts are briefly introduced, and recent research on them is summarized according to the categories of the catalytic sites. Finally, the future development direction of CO2 electroreduction technology is discussed.    

    

* Gallium Nitride‐Based Artificial Photosynthesis Integrated Devices for Solar Hydrogen Generation and Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391875089
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/9781119600862.ch11")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391875089"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391875089"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391875089"))][Get cited by]]

OpenAlex: https://openalex.org/W4391875089 (Open access: False)
    
[[https://openalex.org/A5010878103][Baowen Zhou]], [[https://openalex.org/A5050902155][Peng Zhou]], [[https://openalex.org/A5061245884][Dong Wu]], [[https://openalex.org/A5070775523][Zetian Mi]], No host. None(None)] 2024. https://doi.org/10.1002/9781119600862.ch11 
     
No abstract    

    

* Defect engineering of carbon-based electrocatalysts for the CO2 reduction reaction: A review  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391768363
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/s1872-5805(24)60833-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391768363"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391768363"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391768363"))][Get cited by]]

OpenAlex: https://openalex.org/W4391768363 (Open access: True)
    
[[https://openalex.org/A5064307398][Youjun Lu]], [[https://openalex.org/A5048657205][B. S. Cheng]], [[https://openalex.org/A5055191809][Hui Zhan]], [[https://openalex.org/A5047600031][Peng Zhou]], New Carbon Materials. 39(1)] 2024. https://doi.org/10.1016/s1872-5805(24)60833-4 
     
Electrocatalytic carbon dioxide (CO2) reduction is an important way to achieve carbon neutrality by converting CO2 into high-value-added chemicals using electric energy. Carbon-based materials are widely used in various electrochemical reactions, including electrocatalytic CO2 reduction, due to their low cost and high activity. In recent years, defect engineering has attracted wide attention by constructing asymmetric defect centers in the materials, which can optimize the physicochemical properties of the material and improve its electrocatalytic activity. This review summarizes the types, methods of formation and defect characterization techniques of defective carbon-based materials. The advantages of defect engineering and the advantages and disadvantages of various defect formation methods and characterization techniques are also evaluated. Finally, the challenges of using defective carbon-based materials in electrocatalytic CO2 reduction are investigated and opportunities for their use are discussed. It is believed that this review will provide suggestions and guidance for developing defective carbon-based materials for CO2 reduction.    

    

* Analysis of CO2 emissions reduction via by-product hydrogen  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391849200
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.138")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391849200"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391849200"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391849200"))][Get cited by]]

OpenAlex: https://openalex.org/W4391849200 (Open access: False)
    
[[https://openalex.org/A5002099738][Chao Wang]], [[https://openalex.org/A5091103434][Yongqiang Li]], [[https://openalex.org/A5000920240][Junmin Wan]], [[https://openalex.org/A5047421180][Yi Hu]], International Journal of Hydrogen Energy. None(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.138 
     
Hydrogen is a clean energy in the world and by-product hydrogen is an important part of global hydrogen production. The yield of by-product hydrogen accounts for 18% of hydrogen production globally. To analyze the current stage and calculate CO2 emissions reduction of by-product hydrogen, sources, purification technology, utilization models, comparison of by-product hydrogen and other hydrogen resources, reduction of CO2 emissions, prospects of industrial by-product hydrogen were analyzed from the respective of industrial utilization. The resources of by-product hydrogen will get expanded further. It can facilitate the utilization of industrial by-product hydrogen to establish industrial zone with the factories producing by-product hydrogen and the downstream factories utilizing by-product hydrogen under the current technology conditions. By analyzing the relevant data, it is calculated that the utilization of industrial by-product hydrogen can reduce CO2 emissions by 6.11x105 t per year in 2022. With the development of hydrogen purification technology, by-product hydrogen can provide an efficient and economical way to reduce CO2 emissions for global warming migration before the completion of green hydrogen substitution for other hydrogen.    

    

* Electrochemical CO2 Reduction by Urea Hangman Mn Terpyridine species  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391881952
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202304218")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391881952"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391881952"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391881952"))][Get cited by]]

OpenAlex: https://openalex.org/W4391881952 (Open access: False)
    
[[https://openalex.org/A5008108716][Minghong Li]], [[https://openalex.org/A5004948530][Fang Huang]], [[https://openalex.org/A5055151897][Ping Zhang]], [[https://openalex.org/A5041998803][Ying Xiong]], [[https://openalex.org/A5030775427][Yaping Zhang]], [[https://openalex.org/A5005228021][Fēi Li]], [[https://openalex.org/A5040730537][Cheng Huang Lin]], Chemistry - A European Journal. None(None)] 2024. https://doi.org/10.1002/chem.202304218 
     
Based on our previous study in chemical subtleties of the proton tunneling distance for metal hydride formation (PTD‐MH) to regulate the selectivity of CO2 reduction reaction (CO2RR), we have developed a family of Mn terpyridine derivatives, in which urea groups functioning as multipoint hydrogen‐bonding hangman to accelerate the reaction rate. We found that such changes to the second coordination sphere significantly increased the turnover frequency (TOF) for CO2 reduction to ca. 360 s‐1 with this family of molecular catalysts while maintaining high selectivity (ca. 100% ± 3) for CO even in the presence of a large amount of phenol as proton source. Notably, the compounds studied in this manuscript all exhibit large value for CO as that achieved by Fe porphyrins derivates, while saving up to 0.55 V in overpotential with respect to the latter.    

    

* How to promote CO2 reduction in urban households from a micro perspective?  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391773165
:TOPICS: Rebound Effect on Energy Efficiency and Consumption, Influence of Built Environment on Active Travel, Spatial Microsimulation Models for Policy Analysis
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.energy.2024.130683")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391773165"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391773165"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391773165"))][Get cited by]]

OpenAlex: https://openalex.org/W4391773165 (Open access: False)
    
[[https://openalex.org/A5065256485][Yang Xu]], [[https://openalex.org/A5068884694][Qingsong Wang]], [[https://openalex.org/A5091108483][Suqing Tian]], [[https://openalex.org/A5060392341][Mengyue Liu]], [[https://openalex.org/A5058555426][Yujie Zhang]], [[https://openalex.org/A5053118202][Xueliang Yuan]], [[https://openalex.org/A5087531458][Qiao Ma]], [[https://openalex.org/A5073459047][Chengqing Liu]], Energy. None(None)] 2024. https://doi.org/10.1016/j.energy.2024.130683 
     
Climate change has received widespread international attention. Household CO2 reduction can play an important role in mitigating climate change. Therefore, studying household carbon reduction plans is one of the research hotspots. Using a Survey-Evaluation-Optimization approach, this study constructs a methodology system for urban household CO2 reduction from micro perspective. It is found that the direct household CO2 emissions in the target community are about 1580 kgCO2/(cap·yr). Cooing and heat supply, cooking, hot water heating are stable and important components, accounting for about 70%. In some households, internal measures such as adjusting the temperature of air conditioning, canceling the insulation of water heaters, and changing travel modes show good CO2 reduction effects, reaching up to 650 kgCO2/yr. When the external measures are introduced to implement, the CO2 reduction effect of the internal measures is weakened, but the overall effect is improved. Especially when the low-carbon adjustment of power structure is introduced, the overall CO2 reduction can be increased by 35%. Based on this methodology, decision makers can obtain “one community, one policy” targeted implementation plan for household carbon reduction.    

    

* Coupling of Electrocatalytic CO2 Reduction and CH4 Oxidation for Efficient Methyl Formate Electrosynthesis  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391854676
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ee00087k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391854676"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391854676"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391854676"))][Get cited by]]

OpenAlex: https://openalex.org/W4391854676 (Open access: False)
    
[[https://openalex.org/A5055720455][Quan Zhang]], [[https://openalex.org/A5045304582][Yangshen Chen]], [[https://openalex.org/A5035054349][Shuai Yan]], [[https://openalex.org/A5046867944][Ximeng Lv]], [[https://openalex.org/A5006812397][Chao Yang]], [[https://openalex.org/A5006596822][Min Kuang]], [[https://openalex.org/A5062325923][Gengfeng Zheng]], Energy and Environmental Science. None(None)] 2024. https://doi.org/10.1039/d4ee00087k 
     
The electrocatalytic carbon dioxide reduction reaction (CO2RR) is promising for converting this greenhouse gas into value-added chemicals, while it suffers from limited energy efficiency and product variability. The direct coupling...    

    

* A surface strategy boosting the ethylene selectivity for CO2 reduction and in situ mechanistic insights  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391722107
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-45704-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391722107"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391722107"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391722107"))][Get cited by]]

OpenAlex: https://openalex.org/W4391722107 (Open access: True)
    
[[https://openalex.org/A5026369478][Yinchao Yao]], [[https://openalex.org/A5007250882][Tong Shi]], [[https://openalex.org/A5014698348][Wenxing Chen]], [[https://openalex.org/A5060256814][Jiu Hui Wu]], [[https://openalex.org/A5066609661][Yunying Fan]], [[https://openalex.org/A5029215411][Yichun Liu]], [[https://openalex.org/A5020824627][Liang Cao]], [[https://openalex.org/A5066940770][Zhuo Chen]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-45704-2  ([[https://www.nature.com/articles/s41467-024-45704-2.pdf][pdf]])
     
Abstract Electrochemical reduction of carbon dioxide into ethylene, as opposed to traditional industrial methods, represents a more environmentally friendly and promising technical approach. However, achieving high activity of ethylene remains a huge challenge due to the numerous possible reaction pathways. Here, we construct a hierarchical nanoelectrode composed of CuO treated with dodecanethiol to achieve elevated ethylene activity with a Faradaic efficiency reaching 79.5%. Through on in situ investigations, it is observed that dodecanethiol modification not only facilitates CO 2 transfer and enhances *CO coverage on the catalyst surfaces, but also stabilizes Cu(100) facet. Density functional theory calculations of activation energy barriers of the asymmetrical C–C coupling between *CO and *CHO further support that the greatly increased selectivity of ethylene is attributed to the thiol-stabilized Cu(100). Our findings not only provide an effective strategy to design and construct Cu-based catalysts for highly selective CO 2 to ethylene, but also offer deep insights into the mechanism of CO 2 to ethylene.    

    

* A comparison between 2D and 3D cobalt–organic framework as catalysts for electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391719630
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.heliyon.2024.e26281")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391719630"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391719630"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391719630"))][Get cited by]]

OpenAlex: https://openalex.org/W4391719630 (Open access: True)
    
[[https://openalex.org/A5071460244][Neda Sadat Barekati]], [[https://openalex.org/A5059917325][Hossein Farsi]], [[https://openalex.org/A5057292515][Alireza Farrokhi]], [[https://openalex.org/A5087760602][Shokufeh Moghiminia]], Heliyon. None(None)] 2024. https://doi.org/10.1016/j.heliyon.2024.e26281  ([[http://www.cell.com/article/S2405844024023120/pdf][pdf]])
     
Electrocatalytic CO2 reduction, as an effective way to reduce the CO2 concentration, has gained attention. In this study, we prepared ZIF-67 nanoparticles and nanosheets and investigated them as electrocatalysts for CO2 reduction. It was found that ZIF-67 nanosheets, because of their two–dimensional morphologies, provide more under–coordinated cobalt nodes and have lower overpotentials for both hydrogen evolution and CO2 reduction reactions. Also, the rate–determining step for hydrogen evolution changes from Volmer for ZIF-67 nanoparticles to Hyrovsky for ZIF-67 nanosheets. Also, the presence of Mg2+ ions in solution causes more facile CO2 reduction, especially for ZIF-67 nanosheets.    

    

* Electrocatalytic CO2 Reduction to Formate by a Cobalt Phosphino-Thiolate Complex  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391759409
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3sc06805f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391759409"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391759409"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391759409"))][Get cited by]]

OpenAlex: https://openalex.org/W4391759409 (Open access: True)
    
[[https://openalex.org/A5035899937][Jeremy A Intrator]], [[https://openalex.org/A5065711892][David Velázquez]], [[https://openalex.org/A5021146191][Sicheng Fan]], [[https://openalex.org/A5073457405][Enrico Mastrobattista]], [[https://openalex.org/A5083203208][Christine Yu]], [[https://openalex.org/A5065193423][Smaranda C. Marinescu]], Chemical Science. None(None)] 2024. https://doi.org/10.1039/d3sc06805f  ([[https://pubs.rsc.org/en/content/articlepdf/2024/sc/d3sc06805f][pdf]])
     
Electrochemical conversion of CO2 to value-added products serves as an attractive method to store renewable energy as energy-dense fuels. Selectivity in this type of conversion can be limited, often leading...    

    

* Direct Air Capture and Utilization: Life Cycle Assessment and CO2 Reduction Potential Estimation  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391749337
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Membrane Gas Separation Technology, Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-3892596/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391749337"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391749337"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391749337"))][Get cited by]]

OpenAlex: https://openalex.org/W4391749337 (Open access: True)
    
[[https://openalex.org/A5073705863][Alexander Ryota Keeley]], [[https://openalex.org/A5018157580][Andrew Chapman]], [[https://openalex.org/A5023795277][Sunbin Yoo]], [[https://openalex.org/A5074415920][Kenichi Kurita]], [[https://openalex.org/A5089189626][Junya Kumagai]], [[https://openalex.org/A5004204174][Dyah Ika Rinawati]], [[https://openalex.org/A5054053969][Tianhui Fan]], [[https://openalex.org/A5074976090][Shunsuke Managi]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-3892596/v1  ([[https://www.researchsquare.com/article/rs-3892596/latest.pdf][pdf]])
     
Abstract Reducing the concentration of carbon dioxide (CO 2 ) in the atmosphere to combat climate change is a global challenge. Direct air capture (DAC) is a new set of technologies that directly removes CO 2 from the air; therefore, DAC can address emissions from any source. This paper begins by reviewing the literature on negative emission technologies to summarize the most recent technological developments. We then conduct a life cycle assessment on one of the most recently developed technologies, the direct air capture and utilization (DAC-U) system. DAC-U systems, like photovoltaic systems, can be installed in various locations, including homes, offices, and mega-plants, resulting in a highly scalable, on-site system that can be deployed in various ways. Based on the life cycle assessment results, this article presents the CO 2 capture and reduction potential of the DAC-U system, with a focus on installations in households, and examines the willingness to adopt the system in Japan. Our results show that the DAC-U system functions as a negative emission technology and demonstrate the large CO 2 capture and reduction potential of the DAC-U system through household-level installations.    

    

* Free-Standing Single-Atom Catalyst-Based Electrodes for CO2 Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391775270
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s41918-023-00193-7")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391775270"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391775270"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391775270"))][Get cited by]]

OpenAlex: https://openalex.org/W4391775270 (Open access: True)
    
[[https://openalex.org/A5005705471][M. Nur Hossain]], [[https://openalex.org/A5084145021][Lei Zhang]], [[https://openalex.org/A5083477030][Roberto Neagu]], [[https://openalex.org/A5093919452][Enoch Rassachack]], Electrochemical Energy Reviews. 7(1)] 2024. https://doi.org/10.1007/s41918-023-00193-7  ([[https://link.springer.com/content/pdf/10.1007/s41918-023-00193-7.pdf][pdf]])
     
Abstract Electrochemical CO 2 reduction technology could solve the CO 2 -induced climate warming by electrochemically converting atmospheric CO 2 back into fuel, essentially recycling it and building a low carbon emission economy. However, the electrochemical CO 2 reduction reaction (CO 2 RR) poses a significant challenge due to the highly stable and linear CO 2 molecules, in addition to a proton-coupled multi-electron transfer process. Thus, highly active catalysts, placed on activity bolstering materials, and permeable electrodes are crucial for CO 2 RR. Single-atom catalysts (SACs) have recently garnered increasing interest in the electrocatalysis community due to their potentially high mass efficiency and cost benefits (every atom is an active center, resulting in nearly 100% utilization) and adjustable selectivity (higher uniformity of the active sites compared to nanoparticles). However, preserving the accessibility and activity of the SACs inside the electrode poses major materials development and electrode design challenges. A conventional layered structure SAC electrode typically consists of a gas diffusion layer (GDL), a microporous layer (MPL) and a SAC catalyst layer (SACCL), fabricated by using a powder bonding process. However, this process usually encounters issues such as delamination and instability of SACs due to the weak binder-catalyst-support interface. Conversely, the free-standing SAC electrode design has the potential to overcome these issues by eliminating the GDL, MPL, and need of a binder, in contrast to the powder bonding process. This work first reviews the latest developments in experimental and modeling studies of powdered SAC electrode by the traditional powder bonding process. Next, it examines the development towards the free-standing SAC electrode for high-performance electrochemical reduction of CO 2 . The synthesis-structure-fabrication-performance relationships of SAC-based materials and associated electrodes are analyzed. Furthermore, the article presents future challenges and perspectives for high-performance SAC electrodes for CO 2 RR. Graphical Abstract    

    

* Co-Utilization of Wastewater Sludge and Heavy Metals for Single-Atom Electrocatalytic Reduction of Gaseous Co2  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391826229
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4725703")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391826229"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391826229"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391826229"))][Get cited by]]

OpenAlex: https://openalex.org/W4391826229 (Open access: False)
    
[[https://openalex.org/A5086977144][Baiqin Zhou]], [[https://openalex.org/A5080912645][Zhida Li]], [[https://openalex.org/A5078673419][Xinyue He]], [[https://openalex.org/A5034234971][Chunyue Zhang]], [[https://openalex.org/A5088624254][Shanshan Pi]], [[https://openalex.org/A5086009509][Min Yang]], [[https://openalex.org/A5031159142][Shiguo Zhang]], [[https://openalex.org/A5049295617][Guifeng Li]], [[https://openalex.org/A5053944287][Ziqi Zhang]], [[https://openalex.org/A5030429211][Lu Lu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4725703 
     
Waste activated sludge (WAS), heavy metals and CO2 are three waste streams that exist in wastewater treatment plants. Synergetic management of these wastes for their valorization and cyclic utilization is rarely reported. Herein, we employed sludge-derived extracellular polymeric substances (EPS) as a matrix to adsorb heavy metal Ni in wastewater, the formed EPS-Ni precursor was directly electrospun and carbonized to fabricate a gas diffusion electrode (GDE) for electrochemical CO2 reduction reaction (ECO2RR). This approach can atomically disperse Ni to form quantitative Ni single atom catalysts (SACs) exposed at each nanofiber of the GDE. Moreover, abundant N element in the EPS was proved to play a key role in the formation of Nx-Ni (mixture of N3-Ni and N4-Ni) sites that enabled GDE to reduce CO2 to CO with high efficiency. The Ni3+ over prevailingly reported Ni+ in Ni SACs was observed and showed its high ECO2RR catalytic activity. The integration of both catalyst synthesis and electrode fabrication simplified the GDE manufacture process, thus reducing the material cost. The GDE was installed in a membrane electrode assembly (MEA) for direct gaseous CO2 reduction and generated a current up to 50 mA⋅cm-1 with a desirable CO selectivity (CO:H2 ratio of ~100 and ~75% Faraday efficiency of CO production) under 2.69 cell voltage. This strategy takes advantage of all waste streams generated on site and can consolidate traditionally separated treatment processes to save costs, produce value-added products and generate carbon benefits during wastewater treatment.    

    

* Engineering stable Cu+-Cu0 sites and oxygen defects in boron-doped copper oxide for electrocatalytic reduction of CO2 to C2+ products  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391848551
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149710")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391848551"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391848551"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391848551"))][Get cited by]]

OpenAlex: https://openalex.org/W4391848551 (Open access: False)
    
[[https://openalex.org/A5065234959][Charles Q. Yang]], [[https://openalex.org/A5022110710][Ruichen Wang]], [[https://openalex.org/A5073326341][Yu Chen]], [[https://openalex.org/A5067760587][Jinhua Xiao]], [[https://openalex.org/A5070233080][Zhiwei Huang]], [[https://openalex.org/A5070144022][Bihong Lv]], [[https://openalex.org/A5035684534][Huawang Zhao]], [[https://openalex.org/A5051976562][Xiaomin Wu]], [[https://openalex.org/A5039243487][Guohua Jing]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149710 
     
Cu-based catalysts inevitably undergo surface reconstruction during the electrochemical carbon dioxide reduction reaction (CO2RR) process. Thus, it is a challenge to construct stable Cu+-Cu0 sites of Cu-based catalysts. In this study, we report a simple and facile engineering strategy for stable Cu+-Cu0 sites and oxygen defects derived from the boron-doped copper oxide (B-CuxO) as an efficient CO2RR electrocatalyst. The 5 % B-CuxO exhibited 48.32 % C2+ products Faraday efficiency (FE) for 12 h at −1.0 V vs reversible hydrogen electrode (RHE) in H-cell, which was far superior to CuxO (23.78 %). Combining density functional theory (DFT) and in situ Attenuated Total Reflection Fourier Transform Infrared spectroscopy (in situ ATR-FTIR), a higher electronic depletion on the catalyst surface inhibited the electrons accumulation around Cu sites, thereby maintaining the positive charge and inhibiting the complete reduction of Cu+. Moreover, the high oxygen defects in 5 % B-CuxO could effectively activate CO2 into *CO. We emphasized that Cu+ functioned as the primary active site by facilitating adsorption and dimerization of *CO, whereas Cu0 assisted in optimizing CO2 activation.    

    

* Artificial Intelligence Vision Technology Application of Automatic Steam&Heat Flow Detection Integrated with Carbon Dioxide Reduction and Brackish Water Treatment: A Sustainable Environmental Merit of Carbon Neutrality Through Solar-Driven Distillation Device  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391851772
:TOPICS: Application of Diagnostic Techniques in Oil Wells, Real-time Water Quality Monitoring and Aquaculture Management
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4727259")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391851772"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391851772"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391851772"))][Get cited by]]

OpenAlex: https://openalex.org/W4391851772 (Open access: False)
    
[[https://openalex.org/A5074199759][Shibiao Fang]], [[https://openalex.org/A5059262581][Wenrong Tu]], [[https://openalex.org/A5074319004][Wei Lu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4727259 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Defect and interface engineering for promoting electrocatalytic N-integrated CO2 co-reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391741567
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/s1872-2067(23)64588-7")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391741567"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391741567"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391741567"))][Get cited by]]

OpenAlex: https://openalex.org/W4391741567 (Open access: False)
    
[[https://openalex.org/A5050219087][Zhichao Wang]], [[https://openalex.org/A5013850346][Mengfan Wang]], [[https://openalex.org/A5079957444][Yunfei Huan]], [[https://openalex.org/A5009208811][Tao Qian]], [[https://openalex.org/A5002547360][Jie Xiong]], [[https://openalex.org/A5090023717][Chengtao Yang]], [[https://openalex.org/A5009136959][Chenglin Yan]], Chinese Journal of Catalysis. 57(None)] 2024. https://doi.org/10.1016/s1872-2067(23)64588-7 
     
No abstract    

    

* Author Correction: Substantial reductions in non-CO2 greenhouse gas emissions reductions implied by IPCC estimates of the remaining carbon budget  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391809086
:TOPICS: Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s43247-024-01254-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391809086"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391809086"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391809086"))][Get cited by]]

OpenAlex: https://openalex.org/W4391809086 (Open access: True)
    
[[https://openalex.org/A5017820045][Joeri Rogelj]], [[https://openalex.org/A5067664553][Robin Lamboll]], Communications Earth & Environment. 5(1)] 2024. https://doi.org/10.1038/s43247-024-01254-5  ([[https://www.nature.com/articles/s43247-024-01254-5.pdf][pdf]])
     
No abstract    

    

* Backbone Engineering of Polymeric Catalysts for High‐Performance CO2 Reduction in Bipolar Membrane Zero‐Gap Electrolyzer  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391778724
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202400414")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391778724"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391778724"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391778724"))][Get cited by]]

OpenAlex: https://openalex.org/W4391778724 (Open access: True)
    
[[https://openalex.org/A5086485895][Geng Li]], [[https://openalex.org/A5085040689][Libei Huang]], [[https://openalex.org/A5007565052][Chengpeng Wei]], [[https://openalex.org/A5026318334][Hanchen Shen]], [[https://openalex.org/A5033080900][Yong Liu]], [[https://openalex.org/A5020234133][Qiang Zhang]], [[https://openalex.org/A5074250683][Jianjun Su]], [[https://openalex.org/A5050533590][Yun Mi Song]], [[https://openalex.org/A5056180249][Weihua Guo]], [[https://openalex.org/A5056588574][Xiaohu Cao]], [[https://openalex.org/A5089379373][Ben Zhong Tang]], [[https://openalex.org/A5078358071][Marc Robert]], [[https://openalex.org/A5003575045][Ruquan Ye]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202400414  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/anie.202400414][pdf]])
     
Bipolar membranes (BPMs) have emerged as a promising solution for mitigating CO2 losses, salt precipitation and high maintenance costs associated with the commonly used anion‐exchange membrane electrode assembly for CO2 reduction reaction (CO2RR). However, the industrial implementation of BPM‐based zero‐gap electrolyzer is hampered by the poor CO2RR performance, largely attributed to the local acidic environment. Here, we report a backbone engineering strategy to improve the CO2RR performance of molecular catalysts in BPM‐based zero‐gap electrolyzers by covalently grafting cobalt tetraaminophthalocyanine onto a positively charged polyfluorene backbone (PF‐CoTAPc). PF‐CoTAPc shows a high acid tolerance in BPM electrode assembly (BPMEA), achieving a high FE of 82.6% for CO at 100 mA/cm2 and a high CO2 utilization efficiency of 87.8%. Notably, the CO2RR selectivity, carbon utilization efficiency and long‐term stability of PF‐CoTAPc in BPMEA outperform reported BPM systems. We attribute the enhancement to the stable cationic shield in the double layer and suppression of proton migration, ultimately inhibiting the undesired hydrogen evolution and improving the CO2RR selectivity. Techno‐economic analysis shows the least energy consumption (957 kJ/mol) for the PF‐CoTAPc catalyst in BPMEA. Our findings provide a viable strategy for designing efficient CO2RR catalysts in acidic environments.    

    

* Backbone Engineering of Polymeric Catalysts for High‐Performance CO2 Reduction in Bipolar Membrane Zero‐Gap Electrolyzer  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391778725
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202400414")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391778725"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391778725"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391778725"))][Get cited by]]

OpenAlex: https://openalex.org/W4391778725 (Open access: False)
    
[[https://openalex.org/A5086485895][Geng Li]], [[https://openalex.org/A5085040689][Libei Huang]], [[https://openalex.org/A5007565052][Chengpeng Wei]], [[https://openalex.org/A5026318334][Hanchen Shen]], [[https://openalex.org/A5033080900][Yong Liu]], [[https://openalex.org/A5020234133][Qiang Zhang]], [[https://openalex.org/A5074250683][Jianjun Su]], [[https://openalex.org/A5050533590][Yun Mi Song]], [[https://openalex.org/A5056180249][Weihua Guo]], [[https://openalex.org/A5056588574][Xiaohu Cao]], [[https://openalex.org/A5089379373][Ben Zhong Tang]], [[https://openalex.org/A5078358071][Marc Robert]], [[https://openalex.org/A5003575045][Ruquan Ye]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202400414 
     
Bipolar membranes (BPMs) have emerged as a promising solution for mitigating CO2 losses, salt precipitation and high maintenance costs associated with the commonly used anion‐exchange membrane electrode assembly for CO2 reduction reaction (CO2RR). However, the industrial implementation of BPM‐based zero‐gap electrolyzer is hampered by the poor CO2RR performance, largely attributed to the local acidic environment. Here, we report a backbone engineering strategy to improve the CO2RR performance of molecular catalysts in BPM‐based zero‐gap electrolyzers by covalently grafting cobalt tetraaminophthalocyanine onto a positively charged polyfluorene backbone (PF‐CoTAPc). PF‐CoTAPc shows a high acid tolerance in BPM electrode assembly (BPMEA), achieving a high FE of 82.6% for CO at 100 mA/cm2 and a high CO2 utilization efficiency of 87.8%. Notably, the CO2RR selectivity, carbon utilization efficiency and long‐term stability of PF‐CoTAPc in BPMEA outperform reported BPM systems. We attribute the enhancement to the stable cationic shield in the double layer and suppression of proton migration, ultimately inhibiting the undesired hydrogen evolution and improving the CO2RR selectivity. Techno‐economic analysis shows the least energy consumption (957 kJ/mol) for the PF‐CoTAPc catalyst in BPMEA. Our findings provide a viable strategy for designing efficient CO2RR catalysts in acidic environments.    

    

* Metal-Free Carbon Dot-Microporous Graphitic Carbon Heterojunctions as Photocatalysts for CO2 Reduction  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391790255
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4se00007b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391790255"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391790255"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391790255"))][Get cited by]]

OpenAlex: https://openalex.org/W4391790255 (Open access: True)
    
[[https://openalex.org/A5040389535][Ana García-Mulero]], [[https://openalex.org/A5051181327][María Cabrero-Antonino]], [[https://openalex.org/A5014540719][Hermenegildo Garcı́a]], [[https://openalex.org/A5071474907][Ana Primo]], Sustainable Energy and Fuels. None(None)] 2024. https://doi.org/10.1039/d4se00007b  ([[https://pubs.rsc.org/en/content/articlepdf/2024/se/d4se00007b][pdf]])
     
A series of photocatalysts containing various loadings of carbon dots (CD) on microporous graphitic carbons (mpC) was prepared by pyrolysis at 900 °C under inert atmosphere of α-cyclodextrin containing preformed...    

    

* Comparative Study for the Electrodeposited Cadmium Chalcogenide by Potentiostatic and Potentiodynamic Methods for Electrochemical Reduction of CO2  :CO2RR:
:PROPERTIES:
:ID: https://openalex.org/W4391730965
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21608/sjsci.2024.236449.1123")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391730965"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391730965"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391730965"))][Get cited by]]

OpenAlex: https://openalex.org/W4391730965 (Open access: True)
    
[[https://openalex.org/A5093907500][Amira Gelany]], [[https://openalex.org/A5061832432][Hossnia S. Mohran]], [[https://openalex.org/A5053521441][Mahmoud Elrouby]], Sohag Journal of Sciences. 9(2)] 2024. https://doi.org/10.21608/sjsci.2024.236449.1123  ([[https://sjsci.journals.ekb.eg/article_339158_28ee088a7ff3241151bc926c7acbcddb.pdf][pdf]])
     
No abstract    

    
