#+filetags: CO2RR
#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Fri Jan 19 00:41:50 2024

Found 53 results from 2024-01-05 to 2024-01-19
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Acarbon%20dioxide%20reduction]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aco2%20reduction]]
** Unbiased Photoelectrochemical Carbon Dioxide Reduction Shaping the Future of Solar Fuels   
:PROPERTIES:
:ID: https://openalex.org/W4390650933
:DOI: https://doi.org/10.1016/j.apcatb.2024.123707
:AUTHORS: Haijiao Lu, Luyao Wang
:HOST: Applied Catalysis B: Environmental
:END:

Haijiao Lu, Luyao Wang, Applied Catalysis B: Environmental. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.123707")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390650933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390650933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390650933"))][Get cited by]]

OpenAlex: https://openalex.org/W4390650933
    
Haijiao Lu, Luyao Wang, Applied Catalysis B: Environmental. https://doi.org/10.1016/j.apcatb.2024.123707
    
As atmospheric carbon dioxide (CO2) levels surge due to human activities, addressing this global crisis is paramount. This article delves into the realm of photoelectrochemical (PEC) CO2 reduction, a promising solution that combines solar energy conversion and electrochemical processes to transform CO2 into clean energy fuels. The primary focus of this article lies in the cutting-edge unbiased PEC tandem configurations, specifically reviewing recent breakthroughs in coupling PEC CO2 reduction with the oxygen evolution reaction through water oxidation. By consolidating the latest insights and knowledge, this comprehensive review guides readers through the evolving landscape of advanced PEC technologies. Furthermore, it provides insights into prospective developments in this evolving field, shedding light on the paths toward sustainable energy solutions and climate mitigation.    

    

** A Sulfur‐Doped Copper Catalyst with Efficient Electrocatalytic Formate Generation during the Electrochemical Carbon Dioxide Reduction Reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390656131
:DOI: https://doi.org/10.1002/ange.202313858
:AUTHORS: Yinuo Wang, Hongming Xu, Yu‐Shen Liu, Juhee Jang, Xiaoyi Qiu, Ernest Pahuyo Delmo, Qinglan Zhao, Ping Gao, Minhua Shao
:HOST: Angewandte Chemie
:END:

Yinuo Wang, Hongming Xu, Yu‐Shen Liu, Juhee Jang, Xiaoyi Qiu, Ernest Pahuyo Delmo, Qinglan Zhao, Ping Gao, Minhua Shao, Angewandte Chemie. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202313858")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390656131"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390656131"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390656131"))][Get cited by]]

OpenAlex: https://openalex.org/W4390656131
    
Yinuo Wang, Hongming Xu, Yu‐Shen Liu, Juhee Jang, Xiaoyi Qiu, Ernest Pahuyo Delmo, Qinglan Zhao, Ping Gao, Minhua Shao, Angewandte Chemie. https://doi.org/10.1002/ange.202313858
    
Catalysts involving post‐transition metals have shown almost invincible performance on generating formate in electrochemical CO2 reduction reaction (CO2RR). Conversely, Cu without post‐transition metals have struggled to achieve comparable activity. In this study, a sulfur (S)‐doped‐copper (Cu)‐based catalyst is developed, exhibiting excellent performance in formate generation with a maximum Faradaic efficiency of 92% and a partial current density of 321 mA cm‐2. Ex‐situ structural elucidations reveal the presence of abundant grain boundaries and high retention of S‐S bonds from the covellite phase during CO2RR. Furthermore, thermodynamic calculations demonstrate that S‐S bonds can moderate the binding energies with various intermediates, further improving the activity of the formate pathway. This work is significant in modifying a low‐cost catalyst (Cu) with a non‐metallic substance (S) to achieve comparable performance to mainstream catalysts for formate generation in industrial grade.    

    

** A Sulfur‐Doped Copper Catalyst with Efficient Electrocatalytic Formate Generation during the Electrochemical Carbon Dioxide Reduction Reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390656198
:DOI: https://doi.org/10.1002/anie.202313858
:AUTHORS: Yinuo Wang, Hongming Xu, Yu‐Shen Liu, Juhee Jang, Xiaoyi Qiu, Ernest Pahuyo Delmo, Qinglan Zhao, Ping Gao, Minhua Shao
:HOST: Angewandte Chemie International Edition
:END:

Yinuo Wang, Hongming Xu, Yu‐Shen Liu, Juhee Jang, Xiaoyi Qiu, Ernest Pahuyo Delmo, Qinglan Zhao, Ping Gao, Minhua Shao, Angewandte Chemie International Edition. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202313858")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390656198"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390656198"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390656198"))][Get cited by]]

OpenAlex: https://openalex.org/W4390656198
    
Yinuo Wang, Hongming Xu, Yu‐Shen Liu, Juhee Jang, Xiaoyi Qiu, Ernest Pahuyo Delmo, Qinglan Zhao, Ping Gao, Minhua Shao, Angewandte Chemie International Edition. https://doi.org/10.1002/anie.202313858
    
Catalysts involving post‐transition metals have shown almost invincible performance on generating formate in electrochemical CO2 reduction reaction (CO2RR). Conversely, Cu without post‐transition metals have struggled to achieve comparable activity. In this study, a sulfur (S)‐doped‐copper (Cu)‐based catalyst is developed, exhibiting excellent performance in formate generation with a maximum Faradaic efficiency of 92% and a partial current density of 321 mA cm‐2. Ex‐situ structural elucidations reveal the presence of abundant grain boundaries and high retention of S‐S bonds from the covellite phase during CO2RR. Furthermore, thermodynamic calculations demonstrate that S‐S bonds can moderate the binding energies with various intermediates, further improving the activity of the formate pathway. This work is significant in modifying a low‐cost catalyst (Cu) with a non‐metallic substance (S) to achieve comparable performance to mainstream catalysts for formate generation in industrial grade.    

    

** Nanobubble-Based Carbon Dioxide Massive Dissolution Using Friction Tubes and Real-Time Reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390673455
:DOI: https://doi.org/10.21203/rs.3.rs-3836511/v1
:AUTHORS: Taekeun Yoo, Y.H. Yoo, Seon-Woo Byun, A-Ram You, Changhee Park, Dae-Hyun Choi, Woo-Seung Lee
:HOST: No host
:END:

Taekeun Yoo, Y.H. Yoo, Seon-Woo Byun, A-Ram You, Changhee Park, Dae-Hyun Choi, Woo-Seung Lee, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-3836511/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390673455"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390673455"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390673455"))][Get cited by]]

OpenAlex: https://openalex.org/W4390673455
    
Taekeun Yoo, Y.H. Yoo, Seon-Woo Byun, A-Ram You, Changhee Park, Dae-Hyun Choi, Woo-Seung Lee, No host. https://doi.org/10.21203/rs.3.rs-3836511/v1
    
Abstract To prevent global warming, various technologies are being developed to suppress carbon dioxide emissions. Nanobubbles are useful in various industrial fields. Carbon dioxide capture technology was studied using the property of activating the reaction of nanobubbles. In this study, carbon dioxide capture was attempted using nanobubble generation tubes based on the friction principle. The world has paid attention to carbon capture, utilization, and storage (CCUS) to inhibit and reduce carbon dioxide emissions, which are known as the main cause of global warming. The problem is that the new process that utilizes carbon dioxide must consume less energy and resources than existing alternative processes. To address this problem, research was conducted on the possibility of dissolving carbon dioxide in large quantities at low power consumption using a nanobubble generation system and real-time chemical reactions in this study. In addition, a mass dissolution system was constructed, and real-time neutralization was verified through the reactions of nanobubble carbon dioxide with ammonia water (NH 4 OH) and calcium hydroxide (Ca(OH) 2 ) solution.    

    

** Atomic-Disorder-Induced Mass Transport and Charge Transfer Enhancement Effect Boost the Intrinsic Activity of the Electrocatalyst Towards Electrochemical Co2 Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390696686
:DOI: https://doi.org/10.2139/ssrn.4689859
:AUTHORS: Xiquan Fu, Ziyu Ma, L.L. Liu, Sajjad Hussain, Dongwei Ma, Shilong Jiao
:HOST: No host
:END:

Xiquan Fu, Ziyu Ma, L.L. Liu, Sajjad Hussain, Dongwei Ma, Shilong Jiao, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4689859")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390696686"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390696686"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390696686"))][Get cited by]]

OpenAlex: https://openalex.org/W4390696686
    
Xiquan Fu, Ziyu Ma, L.L. Liu, Sajjad Hussain, Dongwei Ma, Shilong Jiao, No host. https://doi.org/10.2139/ssrn.4689859
    
Electrochemical conversion of carbon dioxide into formic acid has been demonstratedas an efficient approach for closing the carbon cycle. Here, we boost the intrinsicactivity of the Bi-based electrocatalyst through the synergy of enhanced chargetransfer and mass transport process in the electrochemical reactions by generating anatomic disorder in the crystal lattices. The amorphous Bi-based quantum dots (a-BiQDs) serve as promising electrocatalysts toward formate production in a widepotential range with high Faradaic efficiency (FE) and energy efficiency (EE) in boththe conventional H-cell and flow-cell. The maximum FEs of 94.44% and 98.89% areachieved at the potential of -1.0 V vs. RHE in the H-cell and flow-cell, respectively.Furthermore, long-term stability of more than 900 hours is demonstrated in a two-electrode configuration. Combined molecular dynamics and first-principle calculationsascribe the remarkable activity toward formate production to synergistically acceleratedmass transport and charge transfer kinetics .    

    

** Review of electrocatalytic reduction of CO2 on carbon supported films   
:PROPERTIES:
:ID: https://openalex.org/W4390721078
:DOI: https://doi.org/10.1016/j.ijhydene.2024.01.022
:AUTHORS: Afdhal Yuda, Parisa Ebrahimi, Josephine Selvaraj, Anand Kumar, Vaidyanathan Subramanian
:HOST: International Journal of Hydrogen Energy
:END:

Afdhal Yuda, Parisa Ebrahimi, Josephine Selvaraj, Anand Kumar, Vaidyanathan Subramanian, International Journal of Hydrogen Energy. 57(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.022")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390721078"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390721078"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390721078"))][Get cited by]]

OpenAlex: https://openalex.org/W4390721078
    
Afdhal Yuda, Parisa Ebrahimi, Josephine Selvaraj, Anand Kumar, Vaidyanathan Subramanian, International Journal of Hydrogen Energy. https://doi.org/10.1016/j.ijhydene.2024.01.022
    
Carbon capture and conversion are becoming increasingly important as atmospheric CO2 concentrations rise and their adverse effects become increasingly evident. CO2 conversion/utilization-related research has gained renewed interest on a variety of platforms, including thermal, solar, biological, photochemical, and electrochemical conversions. Electrochemical routes, using suitable catalysts, are potentially suitable for commercial purposes owing to ease of integration with solvent-based carbon capture processes. This paper summarizes and evaluates the studies conducted within the past decade regarding the feasibility of carbon-based supports utilized in electrocatalytic carbon dioxide reduction. CO2 conversion has been reviewed in a number of reports, focusing on specific sections, such as metallic/bimetallic catalysts, CO2 solubility, and the fabrication of electrodes and electrochemical cells. The number of publications addressing various carbon-based electrocatalysts is increasing, but these materials have not yet been reviewed. Herein, we are focused on three types of electrocatalyst materials: metals, metal-oxides, non-oxides, and combinations thereof with carbon. The scope of this study includes the following: i) carbon-based materials and how they are characterized by distinctive properties, ii) electrocatalytic CO2 conversion techniques, and iii) research cases for carbon allotrope-supported composites used in CO2 reduction. The advancement in analytical tools that provide insight into liquid-phase reactions will benefit the development of catalysts and electrodes that will be effective in converting CO2 into the desired products. Such developments will also be applicable to other systems involving liquid electrolytes or solvents for performing reactions on catalyst surfaces.    

    

** Engineering redox-active electrochemically mediated carbon dioxide capture systems   
:PROPERTIES:
:ID: https://openalex.org/W4390754419
:DOI: https://doi.org/10.1038/s44286-023-00003-3
:AUTHORS: Michael Edward Lev Massen-Hane, Kyle M. Diederichsen, T. Alan Hatton
:HOST: No host
:END:

Michael Edward Lev Massen-Hane, Kyle M. Diederichsen, T. Alan Hatton, No host. 1(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s44286-023-00003-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390754419"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390754419"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390754419"))][Get cited by]]

OpenAlex: https://openalex.org/W4390754419
    
Michael Edward Lev Massen-Hane, Kyle M. Diederichsen, T. Alan Hatton, No host. https://doi.org/10.1038/s44286-023-00003-3
    
With ever-increasing atmospheric carbon dioxide concentrations and commitments to limit global temperatures to less than 1.5 °C above pre-industrial levels, the need for versatile, low-cost carbon dioxide capture technologies is paramount. Electrochemically mediated carbon dioxide separation systems promise low energetics, modular scalability and ease of implementation, with direct integration to renewable energy for net-negative carbon dioxide operations. For these systems to be cost-competitive, key factors around their operation, stability and scaling need to be addressed. Energy penalties associated with redox-active species transport, gas transport and bubble formation limit the volumetric productivity and scaling potential due to their cost and footprint. Here we highlight the importance of engineering approaches towards enhancing the performance of redox-active electrochemically mediated carbon dioxide capture systems to enable their widespread implementation. This Perspective discusses electrochemically mediated carbon dioxide capture systems, which can offer lower energetics than standard thermal methods, with modular scalability. New integrated configurations can further reduce costs and improve unit productivity, while further engineering of existing cell designs will enable more rapid implementation.    

    

** Mechanism of electrocatalytic CO2 reduction reaction by borophene supported bimetallic catalysts   
:PROPERTIES:
:ID: https://openalex.org/W4390766525
:DOI: https://doi.org/10.1016/j.jcis.2024.01.051
:AUTHORS: Meiling Liu, Jayaraman Balamurugan, Tongxiang Liang, Chao Liu
:HOST: Journal of Colloid and Interface Science
:END:

Meiling Liu, Jayaraman Balamurugan, Tongxiang Liang, Chao Liu, Journal of Colloid and Interface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.051")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390766525"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390766525"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390766525"))][Get cited by]]

OpenAlex: https://openalex.org/W4390766525
    
Meiling Liu, Jayaraman Balamurugan, Tongxiang Liang, Chao Liu, Journal of Colloid and Interface Science. https://doi.org/10.1016/j.jcis.2024.01.051
    
Bimetal atom catalysts (BACs) hold significant potential for various applications as a result of the synergistic interaction between adjacent metal atoms. This interaction leads to improved catalytic performance, while simultaneously maintaining high atomic efficiency and exceptional selectivity, similar to single atom catalysts (SACs). Bimetallic site catalysts (M2β12) supported by β12-borophene were developed as catalysts for electrocatalytic carbon dioxide reduction reaction (CO2RR). The research on density functional theory (DFT) demonstrates that M2β12 exhibits exceptional stability, conductivity, and catalytic activity. Investigating the most efficient reaction pathway for CO2RR by analyzing the Gibbs free energy (ΔG) during potential determining steps (PDS) and choosing a catalyst with outstanding catalytic performance for CO2RR. The overpotential required for Fe2β12 and Ag2β12 to generate CO is merely 0.05 V. This implies that the conversion of CO2 to CO can be accomplished with minimal additional voltage. The overpotential values for Cu2β12 and Ag2β12 during the formation of HCOOH were merely 0.001 and 0.07 V, respectively. Furthermore, the Rh2β12 catalyst exhibits a relatively low overpotential of 0.51 V for CH3OH and 0.65 V for CH4. The Fe2β12 produces C2H4 through the *CO-*CO pathway, while Ag2β12 generates CH3CH2OH via the *CO-*CHO coupling pathway, with remarkably low overpotentials of 0.84 and 0.60 V, respectively. The study provides valuable insights for the systematic design and screening of electrocatalysts for CO2RR that exhibit exceptional catalytic performance and selectivity.    

    

** Biomass‐Derived Electrocatalysts: Low‐Cost, Robust Materials for Sustainable Electrochemical Energy Conversion   
:PROPERTIES:
:ID: https://openalex.org/W4390777858
:DOI: https://doi.org/10.1002/aesr.202470001
:AUTHORS: Tengyi Liu, Hiroshi Yabu
:HOST: No host
:END:

Tengyi Liu, Hiroshi Yabu, No host. 5(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aesr.202470001")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390777858"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390777858"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390777858"))][Get cited by]]

OpenAlex: https://openalex.org/W4390777858
    
Tengyi Liu, Hiroshi Yabu, No host. https://doi.org/10.1002/aesr.202470001
    
Biomass-Derived Electrocatalysts In article number 2300168, Tengyi Liu, and Hiroshi Yabu summarize the latest reports on synthesizing oxygen reduction reaction, oxygen evolution reaction, carbon dioxide reduction reaction, and other electrochemical catalysts from biomass-derived materials. The review provides guidelines for the design and synthesis of electrocatalysts that form catalytic active sites and realize high conductivity, either individually or both, using biomass-derived materials.    

    

** Comparative microwave catalytic pyrolysis of cellulose and lignin in nitrogen and carbon dioxide atmospheres   
:PROPERTIES:
:ID: https://openalex.org/W4390859703
:DOI: https://doi.org/10.1016/j.jclepro.2024.140750
:AUTHORS: Yang Liu, Chunbao Zhou, Asif Ali Siyal, Chenglong Liu, Yingwen Zhang, Jie Fu, Huimin Yun, Jianjun Dai, Xiaotao Bi
:HOST: Journal of Cleaner Production
:END:

Yang Liu, Chunbao Zhou, Asif Ali Siyal, Chenglong Liu, Yingwen Zhang, Jie Fu, Huimin Yun, Jianjun Dai, Xiaotao Bi, Journal of Cleaner Production. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jclepro.2024.140750")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390859703"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390859703"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390859703"))][Get cited by]]

OpenAlex: https://openalex.org/W4390859703
    
Yang Liu, Chunbao Zhou, Asif Ali Siyal, Chenglong Liu, Yingwen Zhang, Jie Fu, Huimin Yun, Jianjun Dai, Xiaotao Bi, Journal of Cleaner Production. https://doi.org/10.1016/j.jclepro.2024.140750
    
In this paper, a cleaner pyrolysis strategy combining microwave heating, catalyst and carbon dioxide was explored for converting biomass components into higher quality products. Catalytic pyrolysis was more favorable for the decomposition and conversion of complex biomass structures. For furfural residue pyrolysis, potassium sulfate contained in sample served as the main catalytic component. Potassium sulfate promoted the increase of phenols in bio-oil. Notably, carbon dioxide atmosphere promoted the decomposition of substances and exerted a significant effect on biomass pyrolysis, which increased bio-oil yield and declined gas yield. When the pyrolysis atmosphere was changed from nitrogen to carbon dioxide, the ID/IG ratio decreased from 1.07 to 0.74, indicating that carbon dioxide decreased defect structure in biochar. Carbon dioxide enriched the porous structure and surface roughness of biochar. Also, carbon dioxide as a carrier gas was found to be more effective than nitrogen in improving the heating values of biochar and the acidity of bio-oil under carbon dioxide was lower than that under nitrogen, which was conducive to the subsequent utilization of biochar and bio-oil. Carbon dioxide promoted the production of alcohols, alkenes, and alkanes in bio-oil. Beneficially, the interaction of cellulose and lignin inhibited the release of hydrogen chloride. At last, this study also provides insights into the mechanism of catalyst and CO2 on biomass microwave pyrolysis.    

    

** Tuning Carbon Dioxide Reduction Reaction Selectivity of Bi Single‐Atom Electrocatalysts with Controlled Coordination Environments   
:PROPERTIES:
:ID: https://openalex.org/W4390886115
:DOI: https://doi.org/10.1002/cssc.202301452
:AUTHORS: Saswati Santra, Verena Streibel, Laura I. Wagner, Ningyan Cheng, Ding Pan, Guanda Zhou, Elise Sirotti, Ryan Kisslinger, Tim Rieth, Siyuan Zhang, Ian D. Sharp
:HOST: ChemSusChem
:END:

Saswati Santra, Verena Streibel, Laura I. Wagner, Ningyan Cheng, Ding Pan, Guanda Zhou, Elise Sirotti, Ryan Kisslinger, Tim Rieth, Siyuan Zhang, Ian D. Sharp, ChemSusChem. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202301452")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390886115"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390886115"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390886115"))][Get cited by]]

OpenAlex: https://openalex.org/W4390886115
    
Saswati Santra, Verena Streibel, Laura I. Wagner, Ningyan Cheng, Ding Pan, Guanda Zhou, Elise Sirotti, Ryan Kisslinger, Tim Rieth, Siyuan Zhang, Ian D. Sharp, ChemSusChem. https://doi.org/10.1002/cssc.202301452
    
Control over product selectivity of the electrocatalytic CO2 reduction reaction (CO2RR) is a crucial challenge for the sustainable production of carbon-based chemical feedstocks. In this regard, single-atom catalysts (SACs) are promising materials due to their tunable coordination environments, which could enable tailored catalytic activities and selectivities, as well as new insights into structure-activity relationships. However, direct evidence for selectivity control via systematic tuning of the SAC coordination environment is scarce. In this work, we have synthesized two differently coordinated Bi SACs anchored to the same host material (carbon black) and characterized their CO2RR activities and selectivities. We find that oxophilic, oxygen-coordinated Bi atoms produce HCOOH, while nitrogen-coordinated Bi atoms generate CO. Importantly, use of the same support material assured that alternation of the coordination environment is the dominant factor for controlling the CO2RR product selectivity. Overall, this work demonstrates the structure-activity relationship of Bi SACs, which can be utilized to establish control over CO2RR product distributions, and highlights the promise for engineering atomic coordination environments of SACs to tune reaction pathways.    

    

** Cu-Based Materials for Enhanced C2+ Product Selectivity in Photo-/Electro-Catalytic CO2 Reduction: Challenges and Prospects   
:PROPERTIES:
:ID: https://openalex.org/W4390588938
:DOI: https://doi.org/10.1007/s40820-023-01276-2
:AUTHORS: Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang
:HOST: Nano-Micro Letters
:END:

Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang, Nano-Micro Letters. 16(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40820-023-01276-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390588938"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390588938"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390588938"))][Get cited by]]

OpenAlex: https://openalex.org/W4390588938
    
Baker Rhimi, Min Zhou, Zaoxue Yan, Xiaoyan Cai, Zhifeng Jiang, Nano-Micro Letters. https://doi.org/10.1007/s40820-023-01276-2
    
Abstract Carbon dioxide conversion into valuable products using photocatalysis and electrocatalysis is an effective approach to mitigate global environmental issues and the energy shortages. Among the materials utilized for catalytic reduction of CO 2 , Cu-based materials are highly advantageous owing to their widespread availability, cost-effectiveness, and environmental sustainability. Furthermore, Cu-based materials demonstrate interesting abilities in the adsorption and activation of carbon dioxide, allowing the formation of C 2+ compounds through C–C coupling process. Herein, the basic principles of photocatalytic CO 2 reduction reactions (PCO 2 RR) and electrocatalytic CO 2 reduction reaction (ECO 2 RR) and the pathways for the generation C 2+ products are introduced. This review categorizes Cu-based materials into different groups including Cu metal, Cu oxides, Cu alloys, and Cu SACs, Cu heterojunctions based on their catalytic applications. The relationship between the Cu surfaces and their efficiency in both PCO 2 RR and ECO 2 RR is emphasized. Through a review of recent studies on PCO 2 RR and ECO 2 RR using Cu-based catalysts, the focus is on understanding the underlying reasons for the enhanced selectivity toward C 2+ products. Finally, the opportunities and challenges associated with Cu-based materials in the CO 2 catalytic reduction applications are presented, along with research directions that can guide for the design of highly active and selective Cu-based materials for CO 2 reduction processes in the future.    

    

** Monomeric gold hydrides for carbon dioxide reduction: ligand effect on the reactivity   
:PROPERTIES:
:ID: https://openalex.org/W4390674634
:DOI: https://doi.org/10.1002/chem.202303512
:AUTHORS: Elisa Rossi, Diego Sorbelli, Paola Belanzoni, Leonardo Belpassi, Gianluca Ciancaleoni
:HOST: No host
:END:

Elisa Rossi, Diego Sorbelli, Paola Belanzoni, Leonardo Belpassi, Gianluca Ciancaleoni, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202303512")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390674634"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390674634"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390674634"))][Get cited by]]

OpenAlex: https://openalex.org/W4390674634
    
Elisa Rossi, Diego Sorbelli, Paola Belanzoni, Leonardo Belpassi, Gianluca Ciancaleoni, No host. https://doi.org/10.1002/chem.202303512
    
We analyzed the ligand electronic effect in the reaction between a [LAu(I)H]0/‐ hydride species and CO2, leading to a coordinated formate [LAu(HCOO)]0/‐. We explored 20 different ligands, such as carbenes, phosphines and others, carefully selected to cover a wide range of electron‐donor and ‐acceptor properties. We included in the study the only ligand, an NHC‐coordinated diphosphene, that, thus far, experimentally demonstrated facile and reversible reaction between the monomeric gold(I) hydride and carbon dioxide. We elucidated the previously unknown reaction mechanism, which resulted to be concerted and common to all the ligands: the gold‐hydrogen bond attacks the carbon atom of CO2 with one oxygen atom coordinating to the gold center. A correlation between the ligand σ donor ability, which affects the electron density at the reactive site, and the kinetic activation barriers of the reaction has been found. This systematic study offers useful guidelines for the rational design of new ligands for this reaction, while suggesting a few promising and experimentally accessible potential candidates for the stoichiometric or catalytic CO2 activation.    

    

** Carbon dioxide reduction utilizing a bismuth halide perovskite as immobilized photocatalyst in a 3D printed microreactor   
:PROPERTIES:
:ID: https://openalex.org/W4390574119
:DOI: https://doi.org/10.1088/1361-6439/ad1b1c
:AUTHORS: José Francisco Ruiz Cordero, Hannia López Mena, Marisol Ledezma, Leslie W. Pineda, J. Herrera
:HOST: Journal of Micromechanics and Microengineering
:END:

José Francisco Ruiz Cordero, Hannia López Mena, Marisol Ledezma, Leslie W. Pineda, J. Herrera, Journal of Micromechanics and Microengineering. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6439/ad1b1c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390574119"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390574119"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390574119"))][Get cited by]]

OpenAlex: https://openalex.org/W4390574119
    
José Francisco Ruiz Cordero, Hannia López Mena, Marisol Ledezma, Leslie W. Pineda, J. Herrera, Journal of Micromechanics and Microengineering. https://doi.org/10.1088/1361-6439/ad1b1c
    
Abstract The rising concerns about CO 2 levels in the atmosphere and energy dependency on non-renewable sources, such as fossil fuels, could find an integral solution in CO 2 photocatalytic reduction. The present work explores two alternatives to the main hindering factors for this reaction, i.e., the reactor configuration and the photocatalyst utilized. A microreactor was designed and 3D printed, providing a cheap and versatile reaction platform. Three bismuth halide perovskites, Cs 3 Bi 2 Cl 9 , Cs 3 Bi 2 I 9 , and Cs 4 MnBi 2 Cl 12 , were synthesized and characterized by their band gaps (E g ); Cs 3 Bi 2 I 9 presented the lowest E g and was therefore chosen for further evaluation as potential CO 2 -reduction photocatalyst. Aqueous-phase photocatalytic CO 2 reduction was achieved using this perovskite in the microreactor, obtaining CO as a reduction product with maximal production rates of 737 μmol g cat -1 h -1 . The reaction system was evaluated under different flow rates and light intensities. A balance between space-time and reactant feed was found to define the behavior of CO concentration and production in the microreactor. For the light intensity, it was observed that as it increased, both CO production and concentration increased due to generating more electron-hole pairs, favoring the photocatalytic reaction. With these results, Cs 3 Bi 2 I 9 perovskite immobilized in the designed microreactor demonstrates having great potential as an effective CO 2 photocatalytic reduction system.&amp;#xD;    

    

** Full-exposed Cu site of Cu2O-(1 0 0) driven high ethylene selectivity of carbon dioxide reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390640110
:DOI: https://doi.org/10.1016/j.apsusc.2023.159243
:AUTHORS: Youming Dong, Xingcheng Ma, Zhaoyong Jin, Xin Xu, Tianyi Xu, Dantong Zhang, Xiaoqiang Cui
:HOST: Applied Surface Science
:END:

Youming Dong, Xingcheng Ma, Zhaoyong Jin, Xin Xu, Tianyi Xu, Dantong Zhang, Xiaoqiang Cui, Applied Surface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2023.159243")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390640110"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390640110"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390640110"))][Get cited by]]

OpenAlex: https://openalex.org/W4390640110
    
Youming Dong, Xingcheng Ma, Zhaoyong Jin, Xin Xu, Tianyi Xu, Dantong Zhang, Xiaoqiang Cui, Applied Surface Science. https://doi.org/10.1016/j.apsusc.2023.159243
    
Cu2O shows great potential as a catalyst for the electrochemical CO2 reduction reaction (ECO2RR). However, the mechanism behind the formation of different final products from Cu2O nanostructures remains a challenge. In this study, we combine theoretical and experimental approaches to demonstrate that the full-exposed Cu sites in Cu2O (1 0 0) microcubes contribute to superior C2H4 selectivity compared to other microstructures such as Cu2O (1 1 1), (1 1 0), and (3 1 1) facets. Density functional theoretical (DFT) calculations reveal that the stronger orbital splitting between Cu 3d and O 2p orbital of Cu2O (1 0 0) facet facilitates the formation of neighboring and low valence state Cu active site, thereby enhancing *CO adsorption and C2H4 formation. These DFT results are supported by the synthesis of four kinds of Cu2O microparticles (MPs) with different exposed facets, where cubic-Cu2O with the (1 0 0) facet exhibits the highest Faradaic efficiency (61.3 %). This study has significant implications for the structural design and mechanism analysis of innovative catalysts used in ECO2RR.    

    

** Carbon dioxide-steam reforming gasification of carbonized biomass pellet for high syngas yield and TAR reduction through CFD modeling   
:PROPERTIES:
:ID: https://openalex.org/W4390673968
:DOI: https://doi.org/10.1016/j.ces.2024.119716
:AUTHORS: Kannie Winston Kuttin, Asma Leghari, Hai Yu, Zihong Xia, Lu Ding, Guangsuo Yu
:HOST: Chemical Engineering Science
:END:

Kannie Winston Kuttin, Asma Leghari, Hai Yu, Zihong Xia, Lu Ding, Guangsuo Yu, Chemical Engineering Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ces.2024.119716")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390673968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390673968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390673968"))][Get cited by]]

OpenAlex: https://openalex.org/W4390673968
    
Kannie Winston Kuttin, Asma Leghari, Hai Yu, Zihong Xia, Lu Ding, Guangsuo Yu, Chemical Engineering Science. https://doi.org/10.1016/j.ces.2024.119716
    
Experimental and numerical evaluation of steam and carbon dioxide gasification on torrefied palm kernel shell in an updraft fixed bed gasifier is studied. Euler-Lagrangian two-dimensional model with 15 kinetic reactions is developed to investigate tar formation in relation to torrefaction temperature, gasification temperature, and steam-to-carbon-dioxide ratio (S-CO2-R). The combination of steam and CO2 had considerable effect on the tar reduction and also influenced the gaseous composition significantly when the varying parameters were compared. The results show that increasing both gasification temperature and S-CO2-R do enhance the H2 production whiles drastically reducing the tar formation. The tar concentration reduced by 21.4 % and 20.5 % by changing the S-CO2-R from 0.4 to 2.0 and gasification process temperature from 973 and 1173 K respectively. An increase in hydrogen is also observed, from 55.5 % to 60.84 %, when the S-CO2-R is increased to 1.2. Similarly, 29.1 % increase is observed in gasification efficiency as compared to the raw-PKS.    

    

** N-modulated Cu0-Cu+ Sites for C1/C2 Selectivity Regulation of Carbon Dioxide Electrocatalytic Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390768112
:DOI: https://doi.org/10.1016/j.jallcom.2024.173488
:AUTHORS: Wenda Zhang, Yizhong Zou, Ming Chen, Wen Jiang, Xiaodong Yan
:HOST: Journal of Alloys and Compounds
:END:

Wenda Zhang, Yizhong Zou, Ming Chen, Wen Jiang, Xiaodong Yan, Journal of Alloys and Compounds. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173488")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390768112"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390768112"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390768112"))][Get cited by]]

OpenAlex: https://openalex.org/W4390768112
    
Wenda Zhang, Yizhong Zou, Ming Chen, Wen Jiang, Xiaodong Yan, Journal of Alloys and Compounds. https://doi.org/10.1016/j.jallcom.2024.173488
    
Controlling the valence states of copper is pivotal in determining the selectivity of products in CO2 electroreduction. In this study, we developed a Cu doped carbon catalyst (CuNC) derived from a metal-organic framework (MOFs) through a straightforward solution reaction and calcination method. The N-modulated Cu0-Cu+ sites exhibited adjustable C1 and C2 selectivity in electrocatalytic CO2 reduction (CER). Specifically, the CuNC-700 demonstrated an impressive C2 Faradaic efficiency (FE) of 56.0% at -1.0 V vs reversible hydrogen electrode (RHE), and a remarkable C1 FE of 56.7% with a total current density of 600 mA/cm2 at -1.6 V vs RHE. In the entire potential range, the CuNC-700 consistently maintained high FE values of > 92% for CER, while the FE values for hydrogen evolution reaction is below 8%. This study unveiled the correlation between the selectivity and the valence states of copper. At low applied potentials, the abundance of N-modulated Cu0-Cu+ sites led to the predominant production of the C2 products. The Cu0 played a primary role in activating CO2 and facilitating subsequent electron transfer, while the Cu+ enhanced the adsorption of *CO, further promoting the C-C coupling. Under high applied potentials, both Cu2+ and Cu+ were converted to Cu0, favoring the methanation process. This research paves the way for future design of Cu-based MOF-derived materials, enabling precise regulation of C1/C2 selectivity in CER.    

    

** Mesoporous Ts-1 Zeolite-Confined Metal Oxides Photocathode for Efficient Reduction of Carbon Dioxide to Methanol   
:PROPERTIES:
:ID: https://openalex.org/W4390901587
:DOI: https://doi.org/10.2139/ssrn.4697343
:AUTHORS: Haihui Liu, Xiaowen Zhou, Kangli Xu, Heng Zhang, Huan Wang, Hongqing Zhou, Hangrong Chen
:HOST: No host
:END:

Haihui Liu, Xiaowen Zhou, Kangli Xu, Heng Zhang, Huan Wang, Hongqing Zhou, Hangrong Chen, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4697343")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390901587"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390901587"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390901587"))][Get cited by]]

OpenAlex: https://openalex.org/W4390901587
    
Haihui Liu, Xiaowen Zhou, Kangli Xu, Heng Zhang, Huan Wang, Hongqing Zhou, Hangrong Chen, No host. https://doi.org/10.2139/ssrn.4697343
    
Excessive CO2 emission has caused serious environmental problems, and converting CO2 to high value-added fuels is attractive for solving energy and environmental crisis. Herein, a novel mesoporous TS-1(mTS-1) zeolite-confined metal oxides nanoclusters Cu-Bi@mTS-1 was developed for efficient photoelectrochemical reduction reaction of CO2 (PEC CO2RR). The catalyst Cu-Bi@mTS-1 as a photocathode showed high activity, achieving a maximum methanol Faraday efficiency (FECH3OH) of 93.4% at -0.7 V vs. RHE. In-situ Raman results indicate the formation of key reaction intermediates *OCH3 and *CHO during the conversion of CO2 to CH3OH. The C2 product ethanol could be also detected at higher potentials during PEC CO2RR. It is believed that the hierarchically porous structure of mTS-1 is conducive to the enrichment of CO2 molecules to increase the reactant concentration, also can promote C-C coupling through photoelectric synergism. This work provides a favorable reference for the rational design of photocathodes by confinement effect of porous structure.    

    

** Energy recovery potential in Bangladesh from elevated temperature textile processing wastewater: an analysis of energy recovery, energy economics and reduction in carbon dioxide emission   
:PROPERTIES:
:ID: https://openalex.org/W4390668426
:DOI: https://doi.org/10.1007/s40808-023-01933-w
:AUTHORS: I. Haque, Mohammad Moshiur Rahman, Md. Sahil Rafiq, Mohammad Shakhawat Hosen Apurba, Nadim Reza Khandaker
:HOST: Modeling Earth Systems and Environment
:END:

I. Haque, Mohammad Moshiur Rahman, Md. Sahil Rafiq, Mohammad Shakhawat Hosen Apurba, Nadim Reza Khandaker, Modeling Earth Systems and Environment. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s40808-023-01933-w")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390668426"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390668426"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390668426"))][Get cited by]]

OpenAlex: https://openalex.org/W4390668426
    
I. Haque, Mohammad Moshiur Rahman, Md. Sahil Rafiq, Mohammad Shakhawat Hosen Apurba, Nadim Reza Khandaker, Modeling Earth Systems and Environment. https://doi.org/10.1007/s40808-023-01933-w
    
No abstract    

    

** Design of highly selective and stable CsPbI3 perovskite catalyst for photocatalytic reduction of CO2 to C1 product   
:PROPERTIES:
:ID: https://openalex.org/W4390753904
:DOI: https://doi.org/10.1016/j.jcis.2024.01.030
:AUTHORS: Qiming Zhang, Linhao Liu, Tong‐Qi Yuan, Juan Hou, Xiaodong Yang
:HOST: Journal of Colloid and Interface Science
:END:

Qiming Zhang, Linhao Liu, Tong‐Qi Yuan, Juan Hou, Xiaodong Yang, Journal of Colloid and Interface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.030")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390753904"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390753904"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390753904"))][Get cited by]]

OpenAlex: https://openalex.org/W4390753904
    
Qiming Zhang, Linhao Liu, Tong‐Qi Yuan, Juan Hou, Xiaodong Yang, Journal of Colloid and Interface Science. https://doi.org/10.1016/j.jcis.2024.01.030
    
Finding efficient photocatalytic carbon dioxide reduction catalysts is one of the core issues in addressing global climate change. Herein, the pristine CsPbI3 perovskite and doped CsPbI3 perovskite were evaluated in carbon dioxide reduction reaction (CO2RR) to C1 products by using density functional theory. Free energy testing and electronic structure analysis methods have shown that doped CsPbI3 exhibits more effective catalytic performance, higher selectivity, and stability than undoped CsPbI3. Additionally, it is discovered that CsPbI3 (100) and (110) crystal surfaces have varied product selectivity. The photo-catalytic effectiveness is increased by the narrower band gap of Bi and Sn doped CsPbI3, which broadens the absorption spectrum of visible light and makes electron transport easier. The calculation results indicate that Bi doped CsPbI3 (100) and CsPbI3 (110) crystal faces exhibit good selectivity towards CH4, with free energy barriers as low as 0.55 eV and 0.58 eV, respectively. Sn doped CsPbI3 (100) and CsPbI3 (110) crystal planes exhibit good selectivity for HCOOH and CH3OH, respectively. The results indicate that the Bi and Sn doped CsPbI3 perovskite catalyst can further improve the CO2 photocatalytic activity and high selectivity for C1 products, making it a suitable substrate material for high-performance CO2RR.    

    

** Synthesis and Electrocatalytic Applications of Layer‐Structured Metal Chalcogenides Composites   
:PROPERTIES:
:ID: https://openalex.org/W4390884831
:DOI: https://doi.org/10.1002/smll.202310526
:AUTHORS: Yongteng Qian, Fangfang Zhang, Xingguang Luο, Yijun Zhong, Dae Joon Kang, Yong Hu
:HOST: Small
:END:

Yongteng Qian, Fangfang Zhang, Xingguang Luο, Yijun Zhong, Dae Joon Kang, Yong Hu, Small. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310526")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390884831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390884831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390884831"))][Get cited by]]

OpenAlex: https://openalex.org/W4390884831
    
Yongteng Qian, Fangfang Zhang, Xingguang Luο, Yijun Zhong, Dae Joon Kang, Yong Hu, Small. https://doi.org/10.1002/smll.202310526
    
Abstract Featured with the attractive properties such as large surface area, unique atomic layer thickness, excellent electronic conductivity, and superior catalytic activity, layered metal chalcogenides (LMCs) have received considerable research attention in electrocatalytic applications. In this review, the approaches developed to synthesize LMCs‐based electrocatalysts are summarized. Recent progress in LMCs‐based composites for electrochemical energy conversion applications including oxygen reduction reaction, carbon dioxide reduction reaction, oxygen evolution reaction, hydrogen evolution reaction, overall water splitting, and nitrogen reduction reaction is reviewed, and the potential opportunities and practical obstacles for the development of LMCs‐based composites as high‐performing active substances for electrocatalytic applications are also discussed. This review may provide an inspiring guidance for developing high‐performance LMCs for electrochemical energy conversion applications.    

    

** Effect of Co2 Shortage on the Performance of Membrane Electrode Co2 Electrolyzer   
:PROPERTIES:
:ID: https://openalex.org/W4390872406
:DOI: https://doi.org/10.2139/ssrn.4695651
:AUTHORS: Xianwen Zhang, Feiyue Cao, Peng Hao, Yang Cao, Taotao Zhou
:HOST: No host
:END:

Xianwen Zhang, Feiyue Cao, Peng Hao, Yang Cao, Taotao Zhou, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4695651")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390872406"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390872406"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390872406"))][Get cited by]]

OpenAlex: https://openalex.org/W4390872406
    
Xianwen Zhang, Feiyue Cao, Peng Hao, Yang Cao, Taotao Zhou, No host. https://doi.org/10.2139/ssrn.4695651
    
To mitigate greenhouse effects, carbon dioxide reduction reaction (CO2RR) has been used as an efficient means of carbon reduction. In CO2 electrolyzer, CO2 shortage can happen and degrade the reaction efficiency. Herein, an efficient and long-lived formic acid three-cell electrolyzer is used to study the effect of CO2 shortage, by operating the electrolyzer from full CO2 supply to CO2 shortage. In addition, the effects of various CO2 fluxes and concentrations on the electrolyzer current, acid concentration and lifetime are investigated. The results demonstrated that the electrolyzer current and the CO to H2 ratio both decreases from full CO2 to CO2 shortage, indicating that the reactivity of converting CO2 into formic acid ions is weakened. On the contrary, the hydrogen evolution reaction is intensified. Long-term CO2 shortage also cause the catalyst to detach and agglomerate in the cathode catalyst layer, reducing its active surface area and overall performance. Compared with the CO2 flux, the CO2 concentration exerts a more pronounced influence. To ensure the electrolysis efficiency, the carbon dioxide concentration should not be less than 80 %.    

    

** Nature AND Nurture: Enabling formate-dependent growth in Methanosarcina acetivorans   
:PROPERTIES:
:ID: https://openalex.org/W4390697828
:DOI: https://doi.org/10.1101/2024.01.08.574737
:AUTHORS: Jichen Bao, Tejas Somvanshi, Ying Tian, Maxime Gabriel Laird, Pierre Garcia, Christian Schöne, Michael Rother, Guillaume Borrel, Silvan Scheller
:HOST: No host
:END:

Jichen Bao, Tejas Somvanshi, Ying Tian, Maxime Gabriel Laird, Pierre Garcia, Christian Schöne, Michael Rother, Guillaume Borrel, Silvan Scheller, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2024.01.08.574737")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390697828"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390697828"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390697828"))][Get cited by]]

OpenAlex: https://openalex.org/W4390697828
    
Jichen Bao, Tejas Somvanshi, Ying Tian, Maxime Gabriel Laird, Pierre Garcia, Christian Schöne, Michael Rother, Guillaume Borrel, Silvan Scheller, No host. https://doi.org/10.1101/2024.01.08.574737
    
Methanogens are essential players in the global carbon cycle. Methanosarcinales possess one of the most diverse metabolic repertoires for methanogenesis, but they have never been observed to utilize formate as a substrate. We successfully reprogrammed the primary metabolism of Methanosarcina acetivorans by introducing an exogenous formate dehydrogenase derived from a closely related species. The engineered strains acquired the capacity to harness energy from formate-dependent methanogenesis pathways, including formate-dependent methyl reduction and formate-dependent carbon dioxide reduction. The ability of M. acetivorans to thrive on formate suggests the existence of essential accessory machinery and metabolic redundancy for generating reduced ferredoxins from F420H2. This remarkable plasticity in energy metabolism raises the possibility that an ancestral lineage of Methanosarcinales may have possessed the capacity to utilize formate. By combining this genetically modified strain with a disruption in methyl disproportionation, we have created a novel tool for investigating and manipulating the components of the F420 reduction and methanogenesis pathways independently.    

    

** Peeking into the Femtosecond Hot-Carrier Dynamics Reveals Unexpected Mechanisms in Plasmonic Photocatalysis   
:PROPERTIES:
:ID: https://openalex.org/W4390743905
:DOI: https://doi.org/10.1021/jacs.3c12470
:AUTHORS: Giulia Dall’Osto, Margherita Marsili, Mirko Vanzan, Daniele Toffoli, Mauro Stener, Stefano Corni, Emanuele Coccia
:HOST: Journal of the American Chemical Society
:END:

Giulia Dall’Osto, Margherita Marsili, Mirko Vanzan, Daniele Toffoli, Mauro Stener, Stefano Corni, Emanuele Coccia, Journal of the American Chemical Society. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.3c12470")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390743905"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390743905"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390743905"))][Get cited by]]

OpenAlex: https://openalex.org/W4390743905
    
Giulia Dall’Osto, Margherita Marsili, Mirko Vanzan, Daniele Toffoli, Mauro Stener, Stefano Corni, Emanuele Coccia, Journal of the American Chemical Society. https://doi.org/10.1021/jacs.3c12470
    
Plasmonic-driven photocatalysis may lead to reaction selectivity that cannot be otherwise achieved. A fundamental role is played by hot carriers, i.e., electrons and holes generated upon plasmonic decay within the metal nanostructure interacting with molecular species. Understanding the elusive microscopic mechanism behind such selectivity is a key step in the rational design of hot-carrier reactions. To accomplish that, we present state-of-the-art multiscale simulations, going beyond density functional theory, of hot-carrier injections for the rate-determining step of a photocatalytic reaction. We focus on carbon dioxide reduction, for which it was experimentally shown that the presence of a rhodium nanocube under illumination leads to the selective production of methane against carbon monoxide. We show that selectivity is due to a (predominantly) direct hole injection from rhodium to the reaction intermediate CHO. Unexpectedly, such an injection does not promote the selective reaction path by favoring proper bond breaking but rather by promoting bonding of the proper molecular fragment to the surface.    

    

** MXenes as Electrocatalysts for the CO<sub>2</sub> Reduction Reaction: Recent Advances and Future Challenges   
:PROPERTIES:
:ID: https://openalex.org/W4390829428
:DOI: https://doi.org/10.1002/celc.202300598
:AUTHORS: Ling Peng Meng, Ebrahim Tayyebi, Kai S. Exner, Francesc Viñes, Francesc Illas
:HOST: ChemElectroChem
:END:

Ling Peng Meng, Ebrahim Tayyebi, Kai S. Exner, Francesc Viñes, Francesc Illas, ChemElectroChem. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202300598")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390829428"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390829428"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390829428"))][Get cited by]]

OpenAlex: https://openalex.org/W4390829428
    
Ling Peng Meng, Ebrahim Tayyebi, Kai S. Exner, Francesc Viñes, Francesc Illas, ChemElectroChem. https://doi.org/10.1002/celc.202300598
    
Abstract Electrochemical carbon dioxide reduction (CO 2 RR) is gaining momentum as an effective process to capture and convert CO 2 into valuable chemicals and fuels, as well as to contribute reducing greenhouse gas emissions. Two‐dimensional transition metal carbides and/or nitrides (MXenes) are increasingly attracting attention as CO 2 RR electrocatalysts due to their enhanced chemical activity and selectivity, overcoming limitations of traditional metal CO 2 RR electrocatalysts, and likely breaking the scaling relations of reaction intermediates toward the desired product. The present concept reviews the state‐of‐the‐art in the computational description of CO 2 RR on MXenes, going from CO 2 activation on pristine models to different surface terminations, and discuss possible ways to tune the catalytic activity and selectivity, including doping, defects, supported single metal atoms, solvent effects, and electric field effects, while putting in the spotlight prospects by including kinetic aspects.    

    

** ATR–SEIRAS Method to Measure Interfacial pH during Electrocatalytic Nitrate Reduction on Cu   
:PROPERTIES:
:ID: https://openalex.org/W4390805684
:DOI: https://doi.org/10.26434/chemrxiv-2024-mb7hn
:AUTHORS: Elizabeth R. Corson, Jinyu Guo, William A. Tarpeh
:HOST: No host
:END:

Elizabeth R. Corson, Jinyu Guo, William A. Tarpeh, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-mb7hn")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390805684"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390805684"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390805684"))][Get cited by]]

OpenAlex: https://openalex.org/W4390805684
    
Elizabeth R. Corson, Jinyu Guo, William A. Tarpeh, No host. https://doi.org/10.26434/chemrxiv-2024-mb7hn
    
This study reports the accuracy and applications of an attenuated total reflectance–surface-enhanced infrared absorption spectroscopy (ATR–SEIRAS) technique to indirectly measure the interfacial pH of the electrolyte using the ratio of phosphate species within 10 nm of the electrocatalyst surface. This technique can be used in situ to study aqueous electrochemical reactions with a calibration range from pH 1–13, time resolution down to 4 s, and an average 95% confidence interval of 14% that varies depending on the pH region (acidic, neutral, or basic). The method is applied in this study to electrochemical nitrate reduction at a copper cathode to demonstrate its capabilities, but is broadly applicable to any aqueous electrochemical reaction (such as hydrogen evolution, carbon dioxide reduction, or oxygen evolution) and the electrocatalyst may be any SEIRAS-active thin film (e.g., silver, gold, or copper). The time-resolved results show a dramatic increase in the interfacial pH from pH 2–7 in the first minute of operation during both constant current and pulsed current experiments where the bulk pH is unchanged. Attempts to control the pH polarization at the surface by altering the electrochemical operating conditions—lowering the current or increasing the pulse frequency—showed no significant change, demonstrating the challenge of controlling the interfacial pH.    

    

** Regulating CHO* intermediate pathway towards the significant acceleration of photocatalytic CO2 reduction to CH4 through rGO-coated ultrafine Pd nanoparticles   
:PROPERTIES:
:ID: https://openalex.org/W4390587795
:DOI: https://doi.org/10.1016/j.cej.2023.148497
:AUTHORS: Fanlin Kong, Jing Xie, Zhenjiang Lu, Jindou Hu, Yue Feng, Yali Cao
:HOST: Chemical Engineering Journal
:END:

Fanlin Kong, Jing Xie, Zhenjiang Lu, Jindou Hu, Yue Feng, Yali Cao, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2023.148497")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390587795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390587795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390587795"))][Get cited by]]

OpenAlex: https://openalex.org/W4390587795
    
Fanlin Kong, Jing Xie, Zhenjiang Lu, Jindou Hu, Yue Feng, Yali Cao, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2023.148497
    
Tailoring catalytic reaction pathways by using reduced graphene oxide (rGO) to tune the electron-hole separation channels in the active sites of noble metals for achieving ideal yield and selectivity in photocatalytic CO2 reduction of hydrocarbon fuels remains a challenge. Herein, ternary catalyst of rGO-coated SnO2-supported noble metal Pd nanoparticles (Pd4/SnO2@rGO) has been prepared by coassembly between negatively charged graphene oxide and positively charged Pd nanoparticles. By coating with ultrathin rGO, the selectivity can be shifted from CO (44.69 % for Pd4/SnO2) toward CH4 as the prevalent species, in which the Pd nanoparticles acted as catalytic sites and electron capture sites. The rGO coating reduced the recombination of the photogenerated carriers as well as optimized the band gap and reduction potential of the catalyst. The in situ spectroscopic tests and density functional theory calculations revealed that CO2 adsorbed on Pd nanoparticles selectively formed dominant low-energy CHO* intermediates because of the generation of HCOOH* intermediates, thus providing a unique reaction pathway for the reduction of CO2 to CH4. Therefore, under sunlight irradiation, the CH4 selectivity of the catalyst is enhanced to 94.1 % with a production rate of up to 77.8 μmol·g−1·h−1. This work demonstrated the prospect to tune the electronic structure of Pd using rGO, which provided a strategy for enhancing the carbon dioxide reduction reaction and selectively obtaining CH4 products in photocatalytic systems.    

    

** A global synthesis of reported urban tree carbon production rates and approaches   
:PROPERTIES:
:ID: https://openalex.org/W4390695934
:DOI: https://doi.org/10.3389/fevo.2023.1244418
:AUTHORS: G. Darrel Jenerette, Dustin L. Herrmann
:HOST: Frontiers in Ecology and Evolution
:END:

G. Darrel Jenerette, Dustin L. Herrmann, Frontiers in Ecology and Evolution. 11(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/fevo.2023.1244418")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390695934"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390695934"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390695934"))][Get cited by]]

OpenAlex: https://openalex.org/W4390695934
    
G. Darrel Jenerette, Dustin L. Herrmann, Frontiers in Ecology and Evolution. https://doi.org/10.3389/fevo.2023.1244418
    
Trees are a prominent feature of urban ecosystems. Urban tree productivity is a key component of urban ecosystem energetics and has been identified as a possible pathway for reducing global greenhouse gas concentrations. Recently, extensive research has been directed to evaluating the carbon dynamics of urban trees in cities throughout the world. Here, we synthesize this research, using results from previous studies from 154 cities to identify the distribution of urban tree productivity globally and the basis for generating urban tree productivity estimates. Reported urban tree productivity shows a strong relationship with estimated tree carbon content and exhibits increases with both temperature and precipitation, with land cover differences influencing the degree of climate sensitivity. Compared with a reference productivity estimate, urban trees showed greatly reduced estimated rates of productivity and the magnitude of reduced productivity was inversely correlated with precipitation but was independent of temperature. Reported rates of productivity across all studies suggest climate restrictions that are more important with less intensively managed land covers. Scaling these results globally suggests a limited opportunity for urban trees to contribute to atmospheric carbon dioxide reductions, especially in the absence of major carbon emission reductions. We found that the majority of results are derived from tree inventories from a single period with rates of productivity estimate through quasi-empirical or allometric models. The majority of studies have been conducted in temperate biomes and North America. These results show that existing urban tree assessments have substantial methodological restrictions and regional biases. Future research of urban tree productivity should look toward improved methods and can use this synthesis as a baseline for comparisons and improvement.    

    

** Challenges and opportunities of atomic-scales reactive sites in thriving electrochemical CO2 reduction reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390848392
:DOI: https://doi.org/10.1016/j.nantod.2024.102152
:AUTHORS: Pengliang Sun, Sailin Liu, Xiong Zheng, Guangzhi Hu, Qingran Zhang, Xinchao Liu, Guoxiang Zheng, Yinguang Chen
:HOST: Nano Today
:END:

Pengliang Sun, Sailin Liu, Xiong Zheng, Guangzhi Hu, Qingran Zhang, Xinchao Liu, Guoxiang Zheng, Yinguang Chen, Nano Today. 55(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nantod.2024.102152")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390848392"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390848392"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390848392"))][Get cited by]]

OpenAlex: https://openalex.org/W4390848392
    
Pengliang Sun, Sailin Liu, Xiong Zheng, Guangzhi Hu, Qingran Zhang, Xinchao Liu, Guoxiang Zheng, Yinguang Chen, Nano Today. https://doi.org/10.1016/j.nantod.2024.102152
    
Electrochemical carbon dioxide reduction reaction (ECO2RR) converts CO2 into value-added chemicals or fuels to realize carbon recycling as means to solve the problems of renewable energy shortage and environmental pollution. The development of cost-effective CO2RR catalysts with high activity, stability and selectivity is the key that enables efficient conversion from CO2 to valuable products. It is also important to understand intrinsic mechanisms of the underlying active-site that affect the performances of catalysts, which can, in turn, facilitate the rational design of more active electrocatalysts. In this context, it is particularly important to understand the structure-activity relationship of catalyst active sites during the CO2RR process from different atomic-scales, which inspires to organize this review. Specifically, we focus on the atomic-level construction of active sites from single atoms, dual-site metal, clusters, or/and graphitic carbon materials: key approaches for tailoring coordination configurations to enhance target product selectivity, i.e., optimizing the interplay between the catalytic active center and reactants or intermediates, disrupting the linear correlation of intermediate adsorption energies, and promoting intricate cascading reactions involving multiple intermediates. Highlight the intricate correlation between the structure-activity of CO2RR catalysts, which govern the discerning refinement of catalysts and propel advances in their practical application. Then, the electrocatalytic reactors for ECO2R reactions are critically reviewed. The acquisition of key metrics, the challenges faced, and the most suitable solutions for electrocatalytic CO2RR are proposed. Finally, future research directions and strategies are anticipated to inspire revolutionary advancements.    

    

** Site Selection Evaluation of Co2 Storage in Saline Aquifers of Zhuyi Depression, the Pearl River Mouth Basin   
:PROPERTIES:
:ID: https://openalex.org/W4390749093
:DOI: https://doi.org/10.2139/ssrn.4691481
:AUTHORS: xuefeng zhang, Xuan Tao, Bo Gao, Hao Zhang
:HOST: No host
:END:

xuefeng zhang, Xuan Tao, Bo Gao, Hao Zhang, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4691481")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390749093"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390749093"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390749093"))][Get cited by]]

OpenAlex: https://openalex.org/W4390749093
    
xuefeng zhang, Xuan Tao, Bo Gao, Hao Zhang, No host. https://doi.org/10.2139/ssrn.4691481
    
CO2 geological storage is the primary means of achieving large-scale, low-cost carbon dioxide reduction. Compared with onshore basins, sequestration in offshore basins has the advantages of larger storage volume and less impact on people and the environment. At the same time, there are also challenges such as high cost and technical difficulty for sequestration. At present, there are many researches on the selection and suitability evaluation of CCS in China, and there are also very successful demonstration applications, while the research on CO2 geological storage in sea areas is relatively few. Taking Zhuyi Depression of Pearl River Mouth Basin in the South China Sea as an example in this paper, with the goal of meeting the storage capacity of one million tons per year. Making statistics on the factors affecting the suitability of CO2 storage of oil and gas-bearing structures in the depression from three aspects: geological characteristics, storage economy and storage safety, and constructs a screening index system of CO2 geological storage field, which includes 3 levels and 18 evaluation factors. The index weight of each evaluation factor is calculated by AHP. The suitability of CO2 sealing of selected oil and gas-bearing structures is quantitatively evaluated by multi-source information overlap analysis. The results show that the Xijiang 23 and other oil-bearing structures in the west of Huizhou Sag have priority as the storage field. The results of this study can provide reference for the implementation and management decision of CO2 saline aquifers storage in this area.    

    

** Au-decorated Sb2Se3 photocathodes for solar-driven CO2 reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390920767
:DOI: https://doi.org/10.1039/d3ey00222e
:AUTHORS: John Cruz, Anna Balog, Péter S. Tóth, Gábor Bencsik, Gergely F. Samu, Csaba Janáky
:HOST: EES Catalysis
:END:

John Cruz, Anna Balog, Péter S. Tóth, Gábor Bencsik, Gergely F. Samu, Csaba Janáky, EES Catalysis. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ey00222e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390920767"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390920767"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390920767"))][Get cited by]]

OpenAlex: https://openalex.org/W4390920767
    
John Cruz, Anna Balog, Péter S. Tóth, Gábor Bencsik, Gergely F. Samu, Csaba Janáky, EES Catalysis. https://doi.org/10.1039/d3ey00222e
    
Photoelectrodes with FTO/Au/Sb2Se3/TiO2/Au architecture were studied in the photoelectrochemical CO2 reduction reaction (PEC CO2RR). The preparation is based on a simple spin-coating technique, where nanorod-like structures were obtained for Sb2Se3,...    

    

** Surfactant-free 2D/2D Pd/g-C3N4 for enhanced photocatalytic CO2 reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390760438
:DOI: https://doi.org/10.1039/d3cy01623d
:AUTHORS: Zhijun Huang, Jie Wang, Chunliang Yang, Fengqin Yan, Guoqing Yuan
:HOST: No host
:END:

Zhijun Huang, Jie Wang, Chunliang Yang, Fengqin Yan, Guoqing Yuan, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cy01623d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390760438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390760438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390760438"))][Get cited by]]

OpenAlex: https://openalex.org/W4390760438
    
Zhijun Huang, Jie Wang, Chunliang Yang, Fengqin Yan, Guoqing Yuan, No host. https://doi.org/10.1039/d3cy01623d
    
Two-dimensional (2D) photocatalysts loaded with metal nanosheets, posessing enhanced charge transfer efficiency between the large 2D/2D interfaces, exhibit unprecedented advantages in photocatalysis. However, the inhibitory influence of surfactants on catalysis...    

    

** Carbonyl-Linked Cobalt Polyphthalocyanines as High-Selectivity Catalyst for Electrochemical CO2 Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390687040
:DOI: https://doi.org/10.1039/d3cc05844a
:AUTHORS: Hua Jiang, Yajing Di, Yunle Gu, Yu Chen, Meiling Dou, Zhengping Zhang, Feng Wang
:HOST: Chemical Communications
:END:

Hua Jiang, Yajing Di, Yunle Gu, Yu Chen, Meiling Dou, Zhengping Zhang, Feng Wang, Chemical Communications. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cc05844a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390687040"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390687040"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390687040"))][Get cited by]]

OpenAlex: https://openalex.org/W4390687040
    
Hua Jiang, Yajing Di, Yunle Gu, Yu Chen, Meiling Dou, Zhengping Zhang, Feng Wang, Chemical Communications. https://doi.org/10.1039/d3cc05844a
    
One kind of carbonyl-linked cobalt polyphthalocyanine (CL-CoPPc) is synthsized as catalysts for electrochemical CO2 reduction (ECR). Carbonyl linkages can decrease the intermolecular π-π stacking, and serve as intramolecular “gullies” to...    

    

** Reasonable design pentamerous artificial photosynthesis system for efficient overall CO2 reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390674665
:DOI: https://doi.org/10.1016/j.cej.2024.148656
:AUTHORS: Chen Qiao, Hao Wang, Mingzheng Gu, Xiaojun Zhang, Guangfeng Wang
:HOST: Chemical Engineering Journal
:END:

Chen Qiao, Hao Wang, Mingzheng Gu, Xiaojun Zhang, Guangfeng Wang, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148656")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390674665"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390674665"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390674665"))][Get cited by]]

OpenAlex: https://openalex.org/W4390674665
    
Chen Qiao, Hao Wang, Mingzheng Gu, Xiaojun Zhang, Guangfeng Wang, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2024.148656
    
Inspired by the photosynthesis of green plants in nature, an artificial photosynthesis system of MF/Co-BWO/CPB-Cu with “root”, “trunk” and “leaf” is designed in this study, realizing efficient overall photocatalytic CO2 reduction reaction (CO2RR). Melamine foam (MF) with strong hydrophilicity and abundant porosity is selected as “root” and “trunk”, which can store and transfer liquid H2O. For the “leaf” design, Bi2WO6 and CsPbBr3 are selected as oxidation and reduction photocatalysts, respectively, which would generate Bi2WO6/CsPbBr3 S-scheme heterojunction. CuS and CoO as reduction and oxidation centers are also introduced into photosynthesis system, respectively. CuS plays an important role in CO2 adsorption and activation, while CoO could promote H2O oxidation and supply proton. Moreover, Co-BWO/CPB-Cu as “leaf” could trigger the “transpiration” from MF via photo-thermal effect, inducing the formation of gas–solid biphase CO2RR system. As a result, the artificial photosynthesis system of MF/Co-BWO/CPB-Cu exhibits the efficient CO2RR efficiency.    

    

** Adsorption and activation, active site and reaction pathway of photocatalytic CO2 reduction: A review   
:PROPERTIES:
:ID: https://openalex.org/W4390858622
:DOI: https://doi.org/10.1016/j.cej.2024.148754
:AUTHORS: Yong‐Xing He, Lin Yin, Nanci Yuan, Gaoke Zhang
:HOST: Chemical Engineering Journal
:END:

Yong‐Xing He, Lin Yin, Nanci Yuan, Gaoke Zhang, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148754")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390858622"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390858622"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390858622"))][Get cited by]]

OpenAlex: https://openalex.org/W4390858622
    
Yong‐Xing He, Lin Yin, Nanci Yuan, Gaoke Zhang, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2024.148754
    
Photocatalytic CO2 reduction (PCR) technology is one of the potential strategies to mitigate the greenhouse effect, solve the energy crisis and achieve goals of carbon dioxide emissions peak and carbon neutrality. However, it is extremely difficult to adsorb and activate CO2 due to the high dissociation energy of C = O bond in CO2 molecule (750 kJ·mol−1), resulting in poor performance of PCR. In addition, in the heterogeneous reaction process, adsorbing and activating CO2 are closely related to the active sites on the surface of photocatalyst. Therefore, in-depth and detailed exploration of the adsorption and activation of CO2 on active sites is critical to developing high-performance photocatalysts. Herein, this review firstly explores adsorption modes of CO2 on the active sites of photocatalyst, including physisorption and chemisorption, where chemisorption includes oxygen, carbon and mixed adsorption. Secondly, reaction pathways for the formation of different high value-added chemical products are introduced, including formaldehyde, carbene, glyoxal and mixed pathways. Then, strategies for enhancing the adsorption and activation of CO2 are briefly summarized. Finally, the future prospects and challenges of PCR development are discussed. This work provides insights and references for further designing photocatalysts that can enhance the adsorption and activation of CO2 and improve the performance of PCR.    

    

** MAPbBr3/Bi2WO6 Z-scheme-heterojunction photocatalysts for photocatalytic CO2 reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390813250
:DOI: https://doi.org/10.1007/s10853-023-09220-w
:AUTHORS: Yawen Zhang, Njemuwa Nwaji, Longmin Wu, Mingliang Jin, Lemma Teshome Tufa, Guofu Zhou, Michael Giersig, Xin Wang, Tengfei Qiu, Eser Metin Akinoglu
:HOST: Journal of Materials Science
:END:

Yawen Zhang, Njemuwa Nwaji, Longmin Wu, Mingliang Jin, Lemma Teshome Tufa, Guofu Zhou, Michael Giersig, Xin Wang, Tengfei Qiu, Eser Metin Akinoglu, Journal of Materials Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10853-023-09220-w")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390813250"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390813250"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390813250"))][Get cited by]]

OpenAlex: https://openalex.org/W4390813250
    
Yawen Zhang, Njemuwa Nwaji, Longmin Wu, Mingliang Jin, Lemma Teshome Tufa, Guofu Zhou, Michael Giersig, Xin Wang, Tengfei Qiu, Eser Metin Akinoglu, Journal of Materials Science. https://doi.org/10.1007/s10853-023-09220-w
    
No abstract    

    

** Recent advances in single crystal and facet dependency of copper electrodes on electrochemical CO2 reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390684607
:DOI: https://doi.org/10.1016/j.coche.2023.100999
:AUTHORS: Yu Qiao, Brian Seger
:HOST: Current Opinion in Chemical Engineering
:END:

Yu Qiao, Brian Seger, Current Opinion in Chemical Engineering. 43(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.coche.2023.100999")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390684607"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390684607"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390684607"))][Get cited by]]

OpenAlex: https://openalex.org/W4390684607
    
Yu Qiao, Brian Seger, Current Opinion in Chemical Engineering. https://doi.org/10.1016/j.coche.2023.100999
    
Investigations on electrochemical CO2 reduction reaction (eCO2RR) on copper (Cu) provide instructive information for the understanding and development of Cu-based catalysts and thus help improve their eCO2RR selectivity toward desired products. Although most studies on the reaction mechanism rely on computational simulations, experiments conducted on well-defined single-crystal structures are able to effectively mirror the ideal surfaces employed in simulation studies and thus convey insightful knowledge on the structure–performance correlation of Cu catalysts in eCO2RR. This mini-review provides an overview on state-of-the-art development of Cu single crystals and their facet dependency in eCO2RR in the recent years, followed by an outlook and perspective on what can be expected in the future.    

    

** Facile Construction of Metal–Organic Framework/Topological Insulator Heterostructure for Photothermal Catalytic CO2 Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390685478
:DOI: https://doi.org/10.1039/d3tc04332k
:AUTHORS: Jing Sun, Xunfeng Yuan, Baoying Liu, Songde Ma, Chengfang Qiao
:HOST: Journal of Materials Chemistry C
:END:

Jing Sun, Xunfeng Yuan, Baoying Liu, Songde Ma, Chengfang Qiao, Journal of Materials Chemistry C. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3tc04332k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390685478"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390685478"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390685478"))][Get cited by]]

OpenAlex: https://openalex.org/W4390685478
    
Jing Sun, Xunfeng Yuan, Baoying Liu, Songde Ma, Chengfang Qiao, Journal of Materials Chemistry C. https://doi.org/10.1039/d3tc04332k
    
Photothermal catalytic CO2 reduction, which combines the advantages of photocatalysis and photothermal effect, has emerged as one of the most promising strategies to meet the global energy crisis and excessive...    

    

** Controllable Preparation of Cu2o/Cu-Cutcpp Mof Heterojunction for Enhanced Electrocatalytic Co2 Reduction to C2h4   
:PROPERTIES:
:ID: https://openalex.org/W4390910665
:DOI: https://doi.org/10.2139/ssrn.4696662
:AUTHORS: Mingming Sun, Xin Xu, Shihao Min, Jie He, K. Li, Longtian Kang
:HOST: No host
:END:

Mingming Sun, Xin Xu, Shihao Min, Jie He, K. Li, Longtian Kang, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4696662")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390910665"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390910665"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390910665"))][Get cited by]]

OpenAlex: https://openalex.org/W4390910665
    
Mingming Sun, Xin Xu, Shihao Min, Jie He, K. Li, Longtian Kang, No host. https://doi.org/10.2139/ssrn.4696662
    
Copper-based metal-organic framework (Cu-MOF) materials with multiple active sites have attracted increasing attention to the electrocatalytic CO2 reduction reaction (ECR), however, face the huge challenge owing to the poor stability and low C2 selectivity. Here, the Cu2O/Cu-CuTCPP heterojunction (Cu2O/CPFs) with three Cu active sites are firstly constructed through in-situ electrodeposition method. The effect of CuSO4 concentration and electrodeposition conditions on ECR is systematically investigated. The optimized Cu2O/CPFs composite achieves the ethylene Faraday efficiency (FEC2H4) of 61.8% at –1.3 V vs. RHE, which is 1.9 and 3.42 times higher than those of CPFs and Cu2O, respectively. Meanwhile, the C2H4 partial current density (jC2H4) of –7.96 mA·cm-2 is 2.91 and 4.68 times higher than those of CPFs and Cu2O. Further experiments reveals that the formation of Cu2+–O–Cu+–O bond between Cu2O and Cu–O4 sites in Cu2O/CPF heterojunction is crucial. Consequently, the hydrogen (H2), formic acid (HCOOH) and methane (CH4) evolution reactions are restricted, the C–C coupling reaction of *CHO and *CO intermediates is significantly enhanced, and the Cu–O4 sites in CPFs are protected. This work provides an effective strategy to stabilize MOF structure and obtain high value-added C2+ products.    

    

** Penta-coordinated aluminum species: Anchoring Au single atoms for photocatalytic CO2 reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390636108
:DOI: https://doi.org/10.1016/j.apcatb.2024.123703
:AUTHORS: Shaoqiang Li, Yilei Li, H. Y. Bai, Dong-ying Zhou, Ying Liu, Ruihong Liu, Bao‐Hang Han, Xinying Liu, Fa-tang Li
:HOST: Applied Catalysis B: Environmental
:END:

Shaoqiang Li, Yilei Li, H. Y. Bai, Dong-ying Zhou, Ying Liu, Ruihong Liu, Bao‐Hang Han, Xinying Liu, Fa-tang Li, Applied Catalysis B: Environmental. 345(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.123703")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390636108"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390636108"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390636108"))][Get cited by]]

OpenAlex: https://openalex.org/W4390636108
    
Shaoqiang Li, Yilei Li, H. Y. Bai, Dong-ying Zhou, Ying Liu, Ruihong Liu, Bao‐Hang Han, Xinying Liu, Fa-tang Li, Applied Catalysis B: Environmental. https://doi.org/10.1016/j.apcatb.2024.123703
    
Searching substrate materials having inherent photocatalytic activity and interaction with single atoms remains challenge. Herein, amorphous Al2O3 containing penta-coordinated aluminum (AlV) species is synthesized using the solvothermal method and the Au single atom is anchored by AlV via the self-reduction strategy. The Al-O bond energy is weakened by introducing amorphous components, which benefits the release of oxygen atoms and the resultant change of Al coordination environment to a AlV species. The electron transfer between AlV and Au stabilizes the Au single atom. The introduction of the Au single atom occupying the position of O vacancy and anchored by AlV strengthened the chemical absorption abilities for CO2, lowered the energy barrier of CO generation and promoted the charge separation efficiency. The CO generation rate of the Au single atom anchored obtains extraordinary promotion in comparison with pristine Al2O3, resulting in an approximately 6-fold enhancement and 98% product CO selectivity.    

    

** Facilely Tunable Dodecahedral POM Framework Loaded with Mono- or Bimetallic Sites for Efficient Photocatalytic CO2 Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390858455
:DOI: https://doi.org/10.1016/j.apcatb.2024.123733
:AUTHORS: Bonan Li, Mengxue Chen, Qiyu Hu, Jiaqi Zhu, Xu Yang, Zijing Li, Chunlian Hu, Yuanyuan Li, Peihong Ni, Yong Ding
:HOST: Applied Catalysis B: Environmental
:END:

Bonan Li, Mengxue Chen, Qiyu Hu, Jiaqi Zhu, Xu Yang, Zijing Li, Chunlian Hu, Yuanyuan Li, Peihong Ni, Yong Ding, Applied Catalysis B: Environmental. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.123733")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390858455"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390858455"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390858455"))][Get cited by]]

OpenAlex: https://openalex.org/W4390858455
    
Bonan Li, Mengxue Chen, Qiyu Hu, Jiaqi Zhu, Xu Yang, Zijing Li, Chunlian Hu, Yuanyuan Li, Peihong Ni, Yong Ding, Applied Catalysis B: Environmental. https://doi.org/10.1016/j.apcatb.2024.123733
    
Utilizing solar energy to drive the conversion of CO2 into high-value chemicals emerged as a promising approach to decrease CO2 emission. Yolk-shell or hollow structure have drawn much attention for photocatalytic CO2 reduction, owing to their efficient CO2 trapping and more active sites exposing. In this study, we employed a simple method to regulate the morphological evolution of K3PW12O40 dodecahedra. After annealing, mono-/bimetallic active species are homogeneously dispersed on K3PW12O40 framework forming PW12@Co and PW12@CoNi, which exhibit good CO production rates of 11.2 and 15.1 μmol/h, respectively, with selectivity of 90.7% and 92.6%. The differences in the activity and selectivity of CO2RR are attributed to the morphology variations of POM and the influence of mono-/bimetallic species. These results are confirmed through the analysis of SEM, TEM, N2 and CO2 adsorption/desorption, PL, EIS and SPV characterizations. In-situ DRIFTS and DFT provide further support for the formation and transformation of intermediate products.    

    

** Binary Junctions Enhance Electron Storage and Potential Difference for Photo-Assisted Electrocatalytic Co2 Reduction to Hcooh   
:PROPERTIES:
:ID: https://openalex.org/W4390696832
:DOI: https://doi.org/10.2139/ssrn.4689861
:AUTHORS: Yingnan Cao, Qianqian Wang, Yunni Liu, Ying Tao, Jinchen Fan, Ming Chen, Dieqing Zhang, Dieqing Zhang
:HOST: No host
:END:

Yingnan Cao, Qianqian Wang, Yunni Liu, Ying Tao, Jinchen Fan, Ming Chen, Dieqing Zhang, Dieqing Zhang, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4689861")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390696832"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390696832"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390696832"))][Get cited by]]

OpenAlex: https://openalex.org/W4390696832
    
Yingnan Cao, Qianqian Wang, Yunni Liu, Ying Tao, Jinchen Fan, Ming Chen, Dieqing Zhang, Dieqing Zhang, No host. https://doi.org/10.2139/ssrn.4689861
    
Photo-assisted electrocatalytic (PAEC) CO2 conversion is a crucial approach for achieving sustainable carbon neutrality. Here, we have developed a binary-junctions photoanode by integrating SrTiO3 and anatase-rutile TiO2 nanotube arrays (STO/A-R TNTAs), which exhibits exceptional activity and selectivity in converting CO2 to HCOOH. The synergetic effects of the SrTiO3/TiO2 heterogeneous junction and the anatase-rutile TiO2 heterophase junction effectively facilitate photoelectron separation and storage, leading to a potential difference between anode and cathode. The establishment of the electron storage strategy, triggered by hetero- junction/phase interfaces, serves as remarkably efficient electron trapping regions with dam-like characteristics. As a result, the STO/A-R TNTAs achieves a generation rate of 68.24 μmol cm-2 h-1 with 92.25% selectivity and 90.70% Faradic efficiency. This performance is approximately 8 times higher compared to the pristine TiO2 nanotube arrays photoanode. The implementation of the electron storage mechanism presents a promising approach to improve CO2 reduction activity and selectivity.    

    

** Promoted Selectivity of Photocatalytic CO2 reduction to C2H4 via Hybrid CuxCoSy Possessing Dual Unsaturated Sites   
:PROPERTIES:
:ID: https://openalex.org/W4390781704
:DOI: https://doi.org/10.1016/j.apcatb.2024.123704
:AUTHORS: Yu Nie, Yanfang Li, Chen An, Xin Tan, Zhuofeng Hu, Jinhua Ye, Tao Yu
:HOST: Applied Catalysis B: Environmental
:END:

Yu Nie, Yanfang Li, Chen An, Xin Tan, Zhuofeng Hu, Jinhua Ye, Tao Yu, Applied Catalysis B: Environmental. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.123704")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390781704"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390781704"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390781704"))][Get cited by]]

OpenAlex: https://openalex.org/W4390781704
    
Yu Nie, Yanfang Li, Chen An, Xin Tan, Zhuofeng Hu, Jinhua Ye, Tao Yu, Applied Catalysis B: Environmental. https://doi.org/10.1016/j.apcatb.2024.123704
    
Ethylene production by CO2 reduction is sluggish because the repulsive dipole-dipole interaction and 12 proton-coupled electron-transfer steps consecutively. Amorphous structured photocatalysts possess few grain boundaries and abundant unsaturated sites, accelerating the reaction efficiency from the angle of dynamics and thermodynamics, which still not yet be used in PCR to C2 products currently. Herein, an amorphous CuxCoSy composed of the minority crystalline CuCo2S4 is fabricated to realize an excellent C2H4 selectivity in terms of Relectron (94.9%). Unsaturated Co and S play the key roles in the improved efficiency of C2H4 generation. C-C coupling is achieved via shortening Co-S bonds distance, and ⁎CO-⁎CO coupling barrier is decreased by more electrons accumulated on unsaturated S. Water is adsorbed on Co adjacent to S and provide protons for ⁎COCO to form ⁎CH2=C. This work paves a new way for broadening the efficient of C2H4 photocatalytic evolution using amorphous photocatalyst.    

    

** Facile synthesis of self-nitrogen-doped carbon spheres for high-efficient photocatalytic CO2 reduction to CO   
:PROPERTIES:
:ID: https://openalex.org/W4390651239
:DOI: https://doi.org/10.1016/j.matlet.2024.135887
:AUTHORS: Zhiyan Dong, Yudong Wang, Xiaochao Zhang, Xiushuai Guan, Changming Zhang, Wensheng Wu, Caimei Fan
:HOST: Materials Letters
:END:

Zhiyan Dong, Yudong Wang, Xiaochao Zhang, Xiushuai Guan, Changming Zhang, Wensheng Wu, Caimei Fan, Materials Letters. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.135887")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390651239"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390651239"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390651239"))][Get cited by]]

OpenAlex: https://openalex.org/W4390651239
    
Zhiyan Dong, Yudong Wang, Xiaochao Zhang, Xiushuai Guan, Changming Zhang, Wensheng Wu, Caimei Fan, Materials Letters. https://doi.org/10.1016/j.matlet.2024.135887
    
In this work, self-nitrogen-doped carbon microsphere photocatalysts were prepared by hydrothermal and carbonation pyrolysis with first application in photocatalytic CO2 reduction. Coupled with relevant characterization, nitrogen-doped carbon microspheres were successfully prepared and the introduction of nitrogen significantly improved the photogenerated charge separation efficiency and CO2 photoreduction to CO activity, leading to the highest photocatalytic reduction activity with a CO yield of 185.71 μmol g−1 (9 h) under simulated sunlight irradiation. More importantly, its performance remains at about 98 % after ten consecutive cycle tests, indicating the excellent active stability of self-nitrogen-doped carbon spheres. Possible mechanisms for photocatalytic reduction and the role of nitrogen in photocatalytic adsorption and reduction processes are analyzed and proposed. The research provides novel strategies for the design of bifunctional catalysts that offer robust adsorption and efficient reduction, enabling the sustainable conversion of CO2.    

    

** Auto-Tandem Co2 Reduction by Reconstructed Cu Imidazole Framework Isomers: Unveiling Pristine Mof-Mediated Co2 Activation   
:PROPERTIES:
:ID: https://openalex.org/W4390695033
:DOI: https://doi.org/10.2139/ssrn.4690201
:AUTHORS: Xiang-Da Zhang, Jian-Mei Huang, Xiaorong Zhu, Chang Liu, Yue Yin, Jiayi Huang, Ming Xu, Yafei Li, Zhi‐Yuan Gu
:HOST: No host
:END:

Xiang-Da Zhang, Jian-Mei Huang, Xiaorong Zhu, Chang Liu, Yue Yin, Jiayi Huang, Ming Xu, Yafei Li, Zhi‐Yuan Gu, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4690201")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390695033"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390695033"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390695033"))][Get cited by]]

OpenAlex: https://openalex.org/W4390695033
    
Xiang-Da Zhang, Jian-Mei Huang, Xiaorong Zhu, Chang Liu, Yue Yin, Jiayi Huang, Ming Xu, Yafei Li, Zhi‐Yuan Gu, No host. https://doi.org/10.2139/ssrn.4690201
    
Cu-based metal-organic frameworks (MOFs) are widely employed in CO2 reduction reactions (CO2RR) because of their unique advantages to convert CO2 into C2+ products. Mostly, Cu-based MOFs are in-situ reconstructed to Cu-based derivatives such as Cu or Cu oxides during CO2RR, which is regarded as the catalytic active center. However, the key role of pristine MOFs and the coordination environment is often ignored in the process of revealing the catalytic mechanism. Here, we propose an auto-tandem mechanism for in-situ reconstructed Cu imidazole framework isomers, namely CuN2 and Cu2N4. During the auto-tandem catalysis process, pristine Cu(imidazole) served to convert CO2 into CO, while the Cu-based derivatives, in this case, Cu(111) sequentially convert the CO to C2+ products. This auto-tandem catalytic mechanism is supported by electrocatalytic performance, TPD-CO, HRTEM, SAED, XPS, in-situ XANES and XES. Besides, in-situ ATR-SEIRAS and DFT computation illustrate that the coordination environment of pristine Cu(imidazole) affects the selectivity of CO and thus determines the selectivity of C2+ products. The auto-tandem catalytic mechanism provides a new route to design Cu-based MOF electrocatalysts for high product selectivity in CO2RR.    

    

** Stabilizing *CO2 Intermediates at the Acidic Interface using Molecularly Dispersed Cobalt Phthalocyanine as Catalysts for CO2 Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390614569
:DOI: https://doi.org/10.1002/anie.202317942
:AUTHORS: Shijia Feng, Xiaojun Wang, Dongfang Cheng, Yanhong Luo, Mengxin Shen, Jiemin Wang, Wenpeng Zhao, Shu Fang, Hongzhi Zheng, Lianze Ji, Xing Zhang, Weigao Xu, Yongye Liang, Philippe Sautet, Jing Zhu
:HOST: Angewandte Chemie International Edition
:END:

Shijia Feng, Xiaojun Wang, Dongfang Cheng, Yanhong Luo, Mengxin Shen, Jiemin Wang, Wenpeng Zhao, Shu Fang, Hongzhi Zheng, Lianze Ji, Xing Zhang, Weigao Xu, Yongye Liang, Philippe Sautet, Jing Zhu, Angewandte Chemie International Edition. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202317942")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390614569"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390614569"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390614569"))][Get cited by]]

OpenAlex: https://openalex.org/W4390614569
    
Shijia Feng, Xiaojun Wang, Dongfang Cheng, Yanhong Luo, Mengxin Shen, Jiemin Wang, Wenpeng Zhao, Shu Fang, Hongzhi Zheng, Lianze Ji, Xing Zhang, Weigao Xu, Yongye Liang, Philippe Sautet, Jing Zhu, Angewandte Chemie International Edition. https://doi.org/10.1002/anie.202317942
    
CO2 electroreduction (CO2R) operating in acidic media circumvents the problems of carbonate formation and CO2 crossover in neutral/alkaline electrolyzers. Alkali cations have been universally recognized as indispensable components for acidic CO2R, while they cause the inevitable issue of salt precipitation. It is therefore desirable to realize alkali‐cation‐free CO2R in pure acid. However, without alkali cations, stabilizing *CO2 intermediates by catalyst itself at the acidic interface poses as a challenge. Herein, we first demonstrate that a carbon nanotube‐supported molecularly dispersed cobalt phthalocyanine (CoPc@CNT) catalyst provides the Co single‐atom active site with energetically localized d states to strengthen the adsorbate‐surface interactions, which stabilizes *CO2 intermediates at the acidic interface (pH = 1). As a result, we realize CO2 conversion to CO in pure acid with a faradaic efficiency of 60% at pH = 2 in flow cell. Furthermore, CO2 is successfully converted in cation exchanged membrane‐based electrode assembly with a faradaic efficiency of 73%. For CoPc@CNT, acidic conditions also promote the intrinsic activity of CO2R compared to alkaline conditions, since the potential‐limiting step, *CO2 to *COOH, is pH‐dependent. This work provides a new understanding for the stabilization of reaction intermediates and facilitates the designs of catalysts and devices for acidic CO2R.    

    

** Stabilizing *CO2 Intermediates at the Acidic Interface using Molecularly Dispersed Cobalt Phthalocyanine as Catalysts for CO2 Reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390656061
:DOI: https://doi.org/10.1002/ange.202317942
:AUTHORS: Shijia Feng, Xiaojun Wang, Dongfang Cheng, Yanhong Luo, Mengxin Shen, Jiemin Wang, Wenpeng Zhao, Shu Fang, Hongzhi Zheng, Lianze Ji, Xing Zhang, Weigao Xu, Yongye Liang, Philippe Sautet, Jing Zhu
:HOST: Angewandte Chemie
:END:

Shijia Feng, Xiaojun Wang, Dongfang Cheng, Yanhong Luo, Mengxin Shen, Jiemin Wang, Wenpeng Zhao, Shu Fang, Hongzhi Zheng, Lianze Ji, Xing Zhang, Weigao Xu, Yongye Liang, Philippe Sautet, Jing Zhu, Angewandte Chemie. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202317942")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390656061"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390656061"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390656061"))][Get cited by]]

OpenAlex: https://openalex.org/W4390656061
    
Shijia Feng, Xiaojun Wang, Dongfang Cheng, Yanhong Luo, Mengxin Shen, Jiemin Wang, Wenpeng Zhao, Shu Fang, Hongzhi Zheng, Lianze Ji, Xing Zhang, Weigao Xu, Yongye Liang, Philippe Sautet, Jing Zhu, Angewandte Chemie. https://doi.org/10.1002/ange.202317942
    
CO2 electroreduction (CO2R) operating in acidic media circumvents the problems of carbonate formation and CO2 crossover in neutral/alkaline electrolyzers. Alkali cations have been universally recognized as indispensable components for acidic CO2R, while they cause the inevitable issue of salt precipitation. It is therefore desirable to realize alkali‐cation‐free CO2R in pure acid. However, without alkali cations, stabilizing *CO2 intermediates by catalyst itself at the acidic interface poses as a challenge. Herein, we first demonstrate that a carbon nanotube‐supported molecularly dispersed cobalt phthalocyanine (CoPc@CNT) catalyst provides the Co single‐atom active site with energetically localized d states to strengthen the adsorbate‐surface interactions, which stabilizes *CO2 intermediates at the acidic interface (pH = 1). As a result, we realize CO2 conversion to CO in pure acid with a faradaic efficiency of 60% at pH = 2 in flow cell. Furthermore, CO2 is successfully converted in cation exchanged membrane‐based electrode assembly with a faradaic efficiency of 73%. For CoPc@CNT, acidic conditions also promote the intrinsic activity of CO2R compared to alkaline conditions, since the potential‐limiting step, *CO2 to *COOH, is pH‐dependent. This work provides a new understanding for the stabilization of reaction intermediates and facilitates the designs of catalysts and devices for acidic CO2R.    

    

** Ligand dominating the catalytic performance of cucurbit[6]uril modified gold nanoparticles for electrocatalytic CO2 reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390749356
:DOI: https://doi.org/10.1016/j.jallcom.2024.173477
:AUTHORS: Tao Ma, Lizhu Qiu, Tao Yi, Yin Chen, Feng Liang
:HOST: Journal of Alloys and Compounds
:END:

Tao Ma, Lizhu Qiu, Tao Yi, Yin Chen, Feng Liang, Journal of Alloys and Compounds. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173477")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390749356"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390749356"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390749356"))][Get cited by]]

OpenAlex: https://openalex.org/W4390749356
    
Tao Ma, Lizhu Qiu, Tao Yi, Yin Chen, Feng Liang, Journal of Alloys and Compounds. https://doi.org/10.1016/j.jallcom.2024.173477
    
Electrocatalytic conversion of CO2 into high-value products provides a promising means to solve the problem of the greenhouse effect and energy storage but is limited by its sluggish kinetics and poor selectivity. In this work, we report cucurbit[6]uril (CB[6]) modified gold nanoparticles (Au-CB[6] NPs) with different sizes (40 nm, 60 nm, and 80 nm) using a facile in situ method and investigate their electrocatalytic performance for CO2 reduction reaction (CO2RR). The 60 nm Au-CB[6] NPs exhibits exceptional selectivity for CO with the highest Faraday efficiency (FECO) reaching 97.6% at 0.6 V vs. reversible hydrogen electrode (RHE) and excellent stability with FECO over 95% for 10 h. The partial current density of CO formed by 60 nm Au-CB[6] NPs is 8.1 mA/cm2, which is 18-fold that of 60 nm gold nanoparticles (Au NPs). Additionally, when the size increases from 40 nm to 80 nm, the CO selectivity of Au-CB[6] NPs remains around 97%, but that of Au NPs decreases from 81% to 61%. The ligand dominated catalytic performance of Au-CB[6] NPs can be attributed to the excess CB[6] coating on catalyst’s surface, which creates a CO2 enriched and hydrophobic environment. The CB[6] modification on Au NPs not only improves the catalytic activity, but it also suppresses the size effect for selectivity in electrocatalytic CO2RR, which proposes a universal strategy for other nanostructures to simplify preparation and separation process and still maintain decent catalytic performance.    

    

** Novel two-dimensional cobaltporphyrin-based organic framework as a promising electrocatalyst for CO2 reduction reaction: a computational study   
:PROPERTIES:
:ID: https://openalex.org/W4390921354
:DOI: https://doi.org/10.1039/d3nj05424a
:AUTHORS: Kai Gong, Xing Wen, Xiao‐Shu He, Yu-Huai Fei, Jinliang Song, Wenwen Wang
:HOST: New Journal of Chemistry
:END:

Kai Gong, Xing Wen, Xiao‐Shu He, Yu-Huai Fei, Jinliang Song, Wenwen Wang, New Journal of Chemistry. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3nj05424a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390921354"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390921354"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390921354"))][Get cited by]]

OpenAlex: https://openalex.org/W4390921354
    
Kai Gong, Xing Wen, Xiao‐Shu He, Yu-Huai Fei, Jinliang Song, Wenwen Wang, New Journal of Chemistry. https://doi.org/10.1039/d3nj05424a
    
Electrocatalytic CO2 reduction reaction (CO2RR) offers a fascinating approach to converting CO2 into valuable chemical feedstocks. Up to now, the development of highly efficient electrocatalysts has been a significant bottleneck...    

    

** Room Temperature Synthesized Layered CAU-17 MOFs for Highly Active and Selective Electrocatalytic CO2 Reduction to Formate   
:PROPERTIES:
:ID: https://openalex.org/W4390843335
:DOI: https://doi.org/10.1016/j.jallcom.2024.173516
:AUTHORS: Linhua Mi, Banglin Chen, Xianzhu Xu, Siting Cai, Yajun He, Wei Yang, Yaming Jiang, Zheng Chen, Shenghong Zhong, Wenbin Hu, Yuanyuan Wang
:HOST: Journal of Alloys and Compounds
:END:

Linhua Mi, Banglin Chen, Xianzhu Xu, Siting Cai, Yajun He, Wei Yang, Yaming Jiang, Zheng Chen, Shenghong Zhong, Wenbin Hu, Yuanyuan Wang, Journal of Alloys and Compounds. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173516")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390843335"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390843335"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390843335"))][Get cited by]]

OpenAlex: https://openalex.org/W4390843335
    
Linhua Mi, Banglin Chen, Xianzhu Xu, Siting Cai, Yajun He, Wei Yang, Yaming Jiang, Zheng Chen, Shenghong Zhong, Wenbin Hu, Yuanyuan Wang, Journal of Alloys and Compounds. https://doi.org/10.1016/j.jallcom.2024.173516
    
Modulating the morphology of metal-organic frameworks (MOFs) has been identified as an effective strategy for enhancing the electrocatalytic performance of CO2 reduction reactions (CO2RR). In this study, CAU-17 MOFs ([Bi(BTC)(H2O)]·2H2O·MeOH) were prepared via a sonication-assisted method at room temperature, which is considered a simpler technique compared to the conventional hydrothermal method. Additionally, the morphology of CAU-17 MOFs was further regulated by incorporating a rare-earth metal (La), resulting in the observation of two distinct structures, i.e. CAU-17 hexagonal prism (CAU-17-HP) and CAU-17 layer (CAU-17-Layer). Compared to CAU-17-HP, CAU-17-Layer exhibits an excellent selectivity towards formate with the maximum Faradaic efficiency of 95.5% at -1.1 VRHE in an H-cell. Subsequently, the limited catalytic activity of CAU-17-Layer was boosted by anchoring nano CeO2 onto its surfaces (CeO2@CAU-17-Layer). The as-prepared composite catalyst demonstrated outstanding performance in the conversion of CO2 to formate, with a current density surpassing -100 mA cm-2 at potentials more negative than -1.0 VRHE and reaching -200 mA cm-2 at -1.5 VRHE in a flow cell. This study demonstrates the significant potential of morphology-engineered and rare-earth metals composited MOFs in facilitating highly efficient reduction of CO2.    

    

** Decoration of cyanamide groups to tune the surface electronic structures of semiconductor photocatalysts for efficient solar driven CO2 reduction   
:PROPERTIES:
:ID: https://openalex.org/W4390607208
:DOI: https://doi.org/10.1016/j.cej.2023.148495
:AUTHORS: Kai Zhang, Xingjian Zhang, Cheng Sun, Lei Gao, Zhiyi Huang, Qixiang Pian, Kunhong Che, Yue Hu, Xiaokun Cui
:HOST: Chemical Engineering Journal
:END:

Kai Zhang, Xingjian Zhang, Cheng Sun, Lei Gao, Zhiyi Huang, Qixiang Pian, Kunhong Che, Yue Hu, Xiaokun Cui, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2023.148495")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390607208"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390607208"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390607208"))][Get cited by]]

OpenAlex: https://openalex.org/W4390607208
    
Kai Zhang, Xingjian Zhang, Cheng Sun, Lei Gao, Zhiyi Huang, Qixiang Pian, Kunhong Che, Yue Hu, Xiaokun Cui, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2023.148495
    
The using of reductive cocatalysts to dictate the transfer path of electrons towards targeting products is indispensable for photocatalytic CO2 reduction reaction (CRR). However, the development of low-cost and highly selective cocatalysts for photocatalytic CRR remains a daunting challenge. Herein, a functional molecule decoration strategy is proposed to tune the surface electronic structures of semiconductor photocatalysts, in order to promote their photocatalytic performance in CRR. We employ cyanamide groups as the chemical modifiers to regulate the CRR performance of solid solution metal sulphide photocatalysts. The synthesized photocatalysts exhibit excellent photocatalytic performance in CRR, and the highest CO evolution rate exceeds 1400 μmol g−1h−1, being among the best results reported to date. Multiple characterizations in combination with theoretical simulations further demonstrate that the decorated cyanamides do not act as active sites, but changes the electronic structures of the neighboring surface lattice metal atoms and decreases the kinetic barrier of the rate determining *CO2→*COOH step, thereby making the surface much more active for photocatalytic CRR. These findings explicitly verify the effectiveness of the functional molecule decoration strategy in promoting the CRR performance of photocatalysts, and also open up a new pathway for the development of highly efficient and selective catalysts for specific catalytic reactions.    

    

** Pure-water-fed, electrocatalytic CO2 reduction to ethylene beyond 1,000 h stability at 10 A   
:PROPERTIES:
:ID: https://openalex.org/W4390608405
:DOI: https://doi.org/10.1038/s41560-023-01415-4
:AUTHORS: Xiaojie She, Lingling Zhai, Yifei Wang, Pei Xiong, Molly Meng‐Jung Li, Tai Wu, Man‐Chung Wong, Xuyun Guo, Zhihang Xu, Mengxia Ji, Hui Xu, Ye Zhu, Shik Chi Edman Tsang, Shu Ping Lau
:HOST: Nature Energy
:END:

Xiaojie She, Lingling Zhai, Yifei Wang, Pei Xiong, Molly Meng‐Jung Li, Tai Wu, Man‐Chung Wong, Xuyun Guo, Zhihang Xu, Mengxia Ji, Hui Xu, Ye Zhu, Shik Chi Edman Tsang, Shu Ping Lau, Nature Energy. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41560-023-01415-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390608405"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390608405"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390608405"))][Get cited by]]

OpenAlex: https://openalex.org/W4390608405
    
Xiaojie She, Lingling Zhai, Yifei Wang, Pei Xiong, Molly Meng‐Jung Li, Tai Wu, Man‐Chung Wong, Xuyun Guo, Zhihang Xu, Mengxia Ji, Hui Xu, Ye Zhu, Shik Chi Edman Tsang, Shu Ping Lau, Nature Energy. https://doi.org/10.1038/s41560-023-01415-4
    
Abstract Electrocatalytic CO 2 reduction at near-ambient temperatures requires a complex inventory of protons, hydroxyls, carbonate ions and alkali-metal ions at the cathode and anode to be managed, necessitating the use of ion-selective membranes to regulate pH. Anion-exchange membranes provide an alkaline environment, allowing CO 2 reduction at low cell voltages and suppression of hydrogen evolution while maintaining high conversion efficiencies. However, the local alkaline conditions and the presence of alkali cations lead to problematic carbonate formation and even precipitation. Here we report a pure-water-fed (alkali-cation-free) membrane–electrode–assembly system for CO 2 reduction to ethylene by integrating an anion-exchange membrane and a proton-exchange membrane at the cathode and anode side, respectively, under forward bias. This system effectively suppresses carbonate formation and prevents salt precipitation. A scaled-up electrolyser stack achieved over 1,000 h stability without CO 2 and electrolyte losses and with 50% Faradaic efficiency towards ethylene at a total current of 10 A.    

    

** A Review: Construction and Demolition Waste as a Novel Source for CO2 Reduction in Portland Cement Production for Concrete   
:PROPERTIES:
:ID: https://openalex.org/W4390703171
:DOI: https://doi.org/10.3390/su16020585
:AUTHORS: Kubilay Kaptan, Sandra Cunha, José Aguiar
:HOST: Sustainability
:END:

Kubilay Kaptan, Sandra Cunha, José Aguiar, Sustainability. 16(2)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16020585")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390703171"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390703171"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390703171"))][Get cited by]]

OpenAlex: https://openalex.org/W4390703171
    
Kubilay Kaptan, Sandra Cunha, José Aguiar, Sustainability. https://doi.org/10.3390/su16020585
    
There is an increasing global recognition of the need for environmental sustainability in mitigating the adverse impacts of cement production. Despite the implementation of various carbon dioxide (CO2) mitigation strategies in the cement industry, such as waste heat recovery, the use of alternative raw materials and alternative fuels, energy efficiency improvements, and carbon capture and storage, overall emissions have still increased due to the higher production levels. The resolution of this matter can be efficiently achieved by the substitution of traditional materials with an alternative material, such as calcined clay (CC), construction and demolition waste (CDW), which have a significant impact on various areas of sustainable development, including environmental, economic, and social considerations. The primary objectives of employing CDW in the Portland cement production are twofold: firstly, to mitigate the release of CO2 into the atmosphere, as it is a significant contributor to environmental pollution and climate change; and secondly, to optimize the utilization of waste materials, thereby addressing the challenges associated with their disposal. The purpose of this work is to present a thorough examination of the existing body of literature pertaining to the partial replacement of traditional raw materials by CDW and the partial replacement of Portland cement by CDW and to analyze the resulting impact on CO2 emissions.    

    
