#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Sun Oct 13 01:25:12 2024

Found 58 results from 2024-10-06 to 2024-10-13
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Carbon Dioxide and Nitrate Reduction Reactions Tailoring Kinetics Over Cu2o with Mesoporous Carbon Channels for Boosting Electrocatalytic Urea Synthesis  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403183577
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4978955")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403183577"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403183577"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403183577"))][Get cited by]]

OpenAlex: https://openalex.org/W4403183577 (Open access: False)
    
[[https://openalex.org/A5100709035][Jiamin Zhao]], [[https://openalex.org/A5019381699][Ying Yuan]], [[https://openalex.org/A5104339006][Meimei Kou]], [[https://openalex.org/A5074336795][Jinsheng Zhao]], [[https://openalex.org/A5103152647][Wei Lin]], [[https://openalex.org/A5074336795][Jinsheng Zhao]], [[https://openalex.org/A5047349369][Panagiotis Tsiakaras]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4978955 
     
No abstract    

    

* Advancements in MXene-based frameworks towards photocatalytic hydrogen production, carbon dioxide reduction and pollutant degradation: Current challenges and future prospects  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403195408
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ccr.2024.216226")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403195408"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403195408"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403195408"))][Get cited by]]

OpenAlex: https://openalex.org/W4403195408 (Open access: False)
    
[[https://openalex.org/A5039619642][Zeeshan Ajmal]], [[https://openalex.org/A5040048786][Asif Hayat]], [[https://openalex.org/A5048817707][Abdul Qadeer]], [[https://openalex.org/A5061078890][Yuzeng Zhao]], [[https://openalex.org/A5026172778][Essam H. Ibrahim]], [[https://openalex.org/A5101982279][Mahmood Ul Haq]], [[https://openalex.org/A5102949390][Kanwal Iqbal]], [[https://openalex.org/A5107998650][Mohd Imran]], [[https://openalex.org/A5059334921][Mohammed Kuku]], [[https://openalex.org/A5051845249][Iftikhar Hussain]], [[https://openalex.org/A5041745214][Hamid Ali]], [[https://openalex.org/A5085364028][Yasin Orooji]], [[https://openalex.org/A5049437929][John L. Zhou]], [[https://openalex.org/A5050079091][Teng Ben]], Coordination Chemistry Reviews. 523(None)] 2024. https://doi.org/10.1016/j.ccr.2024.216226 
     
No abstract    

    

* Nickel (II) Complexes Bearing Electron Donating OR/OH Groups on a Tetradentate Ligand Scaffold for Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403202205
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-f9djd-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403202205"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403202205"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403202205"))][Get cited by]]

OpenAlex: https://openalex.org/W4403202205 (Open access: True)
    
[[https://openalex.org/A5028441979][Sonya Manafe]], [[https://openalex.org/A5099161410][Gbolagade Olajide]], [[https://openalex.org/A5015730401][Chance M. Boudreaux]], [[https://openalex.org/A5069899755][Fengrui Qu]], [[https://openalex.org/A5032057054][Logan M. Whitt]], [[https://openalex.org/A5107506021][Patrick Pridemore]], [[https://openalex.org/A5078519756][James Fletcher Hall]], [[https://openalex.org/A5075727054][Tibor Szilvási]], [[https://openalex.org/A5063607848][Elizabeth T. Papish]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-f9djd-v2  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/66fc23bccec5d6c142cddf8a/original/nickel-ii-complexes-bearing-electron-donating-or-oh-groups-on-a-tetradentate-ligand-scaffold-for-photocatalytic-carbon-dioxide-reduction.pdf][pdf]])
     
Nickel (II) complexes bearing tetradentate NCCN ligands comprised of optionally protic pyridine and N-heterocyclic carbene (NHC) donors have been synthesized and used as catalysts for carbon dioxide reduction. These complexes were synthesized bearing OMe, OBn, or OH substituents on the pyridine rings and were characterized by 1H NMR, 13C NMR, UV-Vis, IR, HR-MS, and single crystal X-ray diffraction. The OH substituent was partially deprotonated as shown by the crystal structure. Electrochemical studies show that these nickel complexes undergo two electron reduction events prior to CO2 reduction. Catalytic current enhancement under CO2 relative to N2 is not observed under dry conditions, but the addition of proton sources leads to modest current enhancement (icat/ip < 2). Visible light driven photochemical CO2 reduction with a photosensitizer (Ir(ppy)3 where ppy = 2-phenylpyridine) and sacrificial electron and proton donors was studied, and formate is the major product with ~10:1 formate to CO production. Electron donor groups (OMe, OBn, OH) do not enhance formate production (relative to H analog), and CO production is only slightly enhanced. Overall with Ni(II), the tetradentate ligands are comparable to recently published pincer ligands for sensitized CO2 reduction, but pincer ligands offer a clear advantage in self-sensitized catalysis.    

    

* Pitfalls in Photochemical and Photoelectrochemical Reduction of CO2 to Energy Products  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403218775
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29194758")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403218775"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403218775"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403218775"))][Get cited by]]

OpenAlex: https://openalex.org/W4403218775 (Open access: True)
    
[[https://openalex.org/A5068301739][Tomasz Baran]], [[https://openalex.org/A5107822632][Domenico Caringella]], [[https://openalex.org/A5057065869][Angela Dibenedetto]], [[https://openalex.org/A5064915844][Michele Aresta]], Molecules. 29(19)] 2024. https://doi.org/10.3390/molecules29194758 
     
The photochemical and photoelectrochemical reduction of CO2 is a promising approach for converting carbon dioxide into valuable chemicals (materials) and fuels. A key issue is ensuring the accuracy of experimental results in CO2 reduction reactions (CO2RRs) because of potential sources of false positives. This paper reports the results of investigations on various factors that may contribute to erroneous attribution of reduced-carbon species, including degradation of carbon species contained in photocatalysts, residual contaminants from synthetic procedures, laboratory glassware, environmental exposure, and the operator. The importance of rigorous experimental protocols, including the use of labeled 13CO2 and blank tests, to identify true CO2 reduction products (CO2RPs) accurately is highlighted. Our experimental data (eventually complemented with or compared to literature data) underline the possible sources of errors and, whenever possible, quantify the false positives with respect to the effective conversion of CO2 in clean conditions. This paper clarifies that the incidence of false positives is higher in the preliminary phase of photo-material development when CO2RPs are in the range of a few 10s of μg gcat−1 h−1, reducing its importance when significant conversions of CO2 are performed reaching 10s of mol gcat−1 h−1. This paper suggests procedures for improving the reliability and reproducibility of CO2RR experiments, thus validating such technologies.    

    

* Interplanar synergy of copper-based electrocatalyst favors reduction of CO2 into C2+ products  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403202486
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ey00141a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403202486"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403202486"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403202486"))][Get cited by]]

OpenAlex: https://openalex.org/W4403202486 (Open access: True)
    
[[https://openalex.org/A5101687908][Jiangnan Li]], [[https://openalex.org/A5084806004][Xinyi Duan]], [[https://openalex.org/A5062302560][Chao Wu]], [[https://openalex.org/A5032642250][Yucheng Cao]], [[https://openalex.org/A5007032744][Zhiyao Duan]], [[https://openalex.org/A5034984355][Peng Zhang]], [[https://openalex.org/A5101310705][Wenjun Fan]], [[https://openalex.org/A5033612713][Fuxiang Zhang]], EES Catalysis. None(None)] 2024. https://doi.org/10.1039/d4ey00141a 
     
Although electrocatalytic reduction of carbon dioxide (CO2) into chemicals and fuels over Cu-based catalysts has been extensively investigated, the influence of their exposed facets on product selectivity remains elusive. To...    

    

* Longitudinal trajectory of technological growth in Sub-Sahara Africa: new insights for achieving carbon dioxide emissions reduction and environmental sustainability  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403209063
:TOPICS: Rebound Effect on Energy Efficiency and Consumption, Economic Impact of Environmental Policies and Resources, Economic Implications of Climate Change Policies
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10668-024-05467-8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403209063"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403209063"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403209063"))][Get cited by]]

OpenAlex: https://openalex.org/W4403209063 (Open access: False)
    
[[https://openalex.org/A5023778114][Seidu Abdulai Jamatutu]], [[https://openalex.org/A5086420750][Kashif Abbass]], [[https://openalex.org/A5081166150][Huaming Song]], [[https://openalex.org/A5057053493][Sidique Gawusu]], [[https://openalex.org/A5104827214][Kyei Emmanuel Yeboah]], Environment Development and Sustainability. None(None)] 2024. https://doi.org/10.1007/s10668-024-05467-8 
     
No abstract    

    

* Controlling the Polarity of Metal‐Organic Frameworks to Promote Electrochemical CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403335645
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-10-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202416367")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403335645"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403335645"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403335645"))][Get cited by]]

OpenAlex: https://openalex.org/W4403335645 (Open access: False)
    
[[https://openalex.org/A5100395711][Xiaolong Zhang]], [[https://openalex.org/A5085985069][Junnan Chen]], [[https://openalex.org/A5100444820][Xiaogang Wang]], [[https://openalex.org/A5045927677][Yingjun Dong]], [[https://openalex.org/A5029491497][Jiapeng Ji]], [[https://openalex.org/A5101546109][Linbo Li]], [[https://openalex.org/A5100760140][Ming Xue]], [[https://openalex.org/A5100406789][Hui‐Ming Cheng]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202416367 
     
The addition of polar functional groups to porous structures is an effective strategy for increasing the ability of metal‐organic frameworks (MOFs) to capture CO2 by enhancing interactions between the dipoles of the polar functional groups and the quadrupoles of CO2. However, the potential of MOFs grafted to polar functional group to activate CO2 has not been investigated in the context of CO2 electrolysis. In this study, we report a mixed‐ligand strategy to incorporate various functional groups in the MOFs. We found that substituents with strong polarity led to increased catalytic performance of electrochemical CO2 reduction for these polarized MOFs. Both experimental and theoretical evidence indicates that the presence of polar functional groups induces a charge redistribution in the micropores of MOFs. We have shown that higher electron densities of sp2‐carbon atoms in benzimidazolate ligands reduces the energy barrier to generate *COOH, which is simultaneously controlled by the mass transfer of CO2. Our research offers an effective method of disrupting local electron neutrality in the pores of electrocatalysts/supports to activate CO2 under electrochemical conditions.    

    

* COmbined suN-Driven Oxidation and CO2 Reduction for renewable energy storage  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403221851
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2020-11-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3030/101006839")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403221851"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403221851"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403221851"))][Get cited by]]

OpenAlex: https://openalex.org/W4403221851 (Open access: False)
    
, No host. None(None)] 2020. https://doi.org/10.3030/101006839 
     
No abstract    

    

* Exploring Electrocatalytic CO2 Reduction Over Materials Derived from Cu‐Based Metal‐Organic Frameworks  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403195807
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Applications of Ionic Liquids
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202401551")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403195807"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403195807"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403195807"))][Get cited by]]

OpenAlex: https://openalex.org/W4403195807 (Open access: False)
    
[[https://openalex.org/A5101546250][Yining Li]], [[https://openalex.org/A5037723826][Abhishek Dutta Chowdhury]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202401551 
     
The direct valorization of carbon dioxide (CO2) into value‐added chemicals offers an efficient and attractive approach to promoting carbon neutrality. Among the available methods, the electrocatalytic CO2 reduction reaction (eCO2RR) for producing multi‐carbon products (C2+) is gaining attention due to its simplicity. However, achieving selective control over product formation remains a challenge. One key issue is the lack of a reliable correlation between the physicochemical properties of electrocatalytic materials and their activity and selectivity.To address this gap, we conducted a model study in which carbonized CuxZny@C materials, derived from metal‐organic frameworks (MOFs), were synthesized with varying Cu/Zn ratios. The pyrolyzed bimetallic MOFs retained key properties of the original MOFs while also developing new characteristics. These subtle changes in physicochemical properties influenced product selectivity. Our findings showed that higher Zn doping favors the formation of single‐carbon (C1) products, while it is less favorable for multi‐carbon (C2+) products. Optimizing the Cu/Zn ratio was emphasized through characterization techniques, which will help guide the design of improved electrocatalytic systems for the eCO2RR process.    

    

* Dual Metallosalen‐based Covalent Organic Frameworks for Artificial Photosynthetic Diluted CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403189900
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Photocatalytic Materials for Solar Energy Conversion, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202414287")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403189900"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403189900"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403189900"))][Get cited by]]

OpenAlex: https://openalex.org/W4403189900 (Open access: True)
    
[[https://openalex.org/A5029766000][Hong Dong]], [[https://openalex.org/A5015663455][Liang Fang]], [[https://openalex.org/A5100627363][Kexin Chen]], [[https://openalex.org/A5020411455][Jianxin Wei]], [[https://openalex.org/A5100343408][Jiaxin Li]], [[https://openalex.org/A5058959037][Xiu Qiao]], [[https://openalex.org/A5100341469][Ya Wang]], [[https://openalex.org/A5066058184][Fengming Zhang]], [[https://openalex.org/A5060057970][Ya‐Qian Lan]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202414287  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/anie.202414287][pdf]])
     
Directly converting CO2 in flue gas using artificial photosynthetic technology represents a promising green approach for CO2 resource utilization. However, it remains a great challenge to achieve efficient reduction of CO2 from flue gas due to the decreased activity of photocatalysts in diluted CO2 atmosphere. Herein, we designed and synthesized a series of dual metallosalen‐based covalent organic frameworks (MM‐Salen‐COFs, M: Zn, Ni, Cu) for artificial photosynthetic diluted CO2 reduction and confirmed their advantage in comparison to that of single metal M‐Salen‐COFs. As a results, the ZnZn‐Salen‐COF with dual Zn sites exhibits a prominent visible‐light‐driven CO2‐to‐CO conversion rate of 150.9 μmol g−1 h−1 under pure CO2 atmosphere, which is ~6 times higher than that of single metal Zn‐Salen‐COF. Notably, the dual metal ZnZn‐Salen‐COF still displays efficient CO2 conversion activity of 102.1 μmol g−1 h−1 under diluted CO2 atmosphere from simulated flue gas conditions (15% CO2), which is a record high activity among COFs‐ and MOFs‐based photocatalysts under the same reaction conditions. Further investigations and theoretical calculations suggest that the synergistic effect between the neighboring dual metal sites in the ZnZn‐Salen‐COF facilitates low concentration CO2 adsorption and activation, thereby lowering the energy barrier of the rate‐determining step.    

    

* Dual Metallosalen‐based Covalent Organic Frameworks for Artificial Photosynthetic Diluted CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403189955
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrochemical Reduction of CO2 to Fuels, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202414287")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403189955"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403189955"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403189955"))][Get cited by]]

OpenAlex: https://openalex.org/W4403189955 (Open access: False)
    
[[https://openalex.org/A5029766000][Hong Dong]], [[https://openalex.org/A5015663455][Liang Fang]], [[https://openalex.org/A5100627368][Kexin Chen]], [[https://openalex.org/A5020411455][Jianxin Wei]], [[https://openalex.org/A5100343399][Jiaxin Li]], [[https://openalex.org/A5058959037][Xiu Qiao]], [[https://openalex.org/A5100708364][Ya Wang]], [[https://openalex.org/A5066058184][Fengming Zhang]], [[https://openalex.org/A5060057970][Ya‐Qian Lan]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202414287 
     
Directly converting CO2 in flue gas using artificial photosynthetic technology represents a promising green approach for CO2 resource utilization. However, it remains a great challenge to achieve efficient reduction of CO2 from flue gas due to the decreased activity of photocatalysts in diluted CO2 atmosphere. Herein, we designed and synthesized a series of dual metallosalen‐based covalent organic frameworks (MM‐Salen‐COFs, M: Zn, Ni, Cu) for artificial photosynthetic diluted CO2 reduction and confirmed their advantage in comparison to that of single metal M‐Salen‐COFs. As a results, the ZnZn‐Salen‐COF with dual Zn sites exhibits a prominent visible‐light‐driven CO2‐to‐CO conversion rate of 150.9 μmol g−1 h−1 under pure CO2 atmosphere, which is ~6 times higher than that of single metal Zn‐Salen‐COF. Notably, the dual metal ZnZn‐Salen‐COF still displays efficient CO2 conversion activity of 102.1 μmol g−1 h−1 under diluted CO2 atmosphere from simulated flue gas conditions (15% CO2), which is a record high activity among COFs‐ and MOFs‐based photocatalysts under the same reaction conditions. Further investigations and theoretical calculations suggest that the synergistic effect between the neighboring dual metal sites in the ZnZn‐Salen‐COF facilitates low concentration CO2 adsorption and activation, thereby lowering the energy barrier of the rate‐determining step.    

    

* Why do CuAl catalysts outperform in CO2 electro-reduction to C2H4?  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403209488
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11426-024-2292-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403209488"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403209488"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403209488"))][Get cited by]]

OpenAlex: https://openalex.org/W4403209488 (Open access: False)
    
[[https://openalex.org/A5028424510][Dongfang Cheng]], [[https://openalex.org/A5102444773][Gong Zhang]], [[https://openalex.org/A5100421905][Lulu Li]], [[https://openalex.org/A5031229807][Xiangcheng Shi]], [[https://openalex.org/A5079509878][Wenjin Zhu]], [[https://openalex.org/A5030680281][Xintong Yuan]], [[https://openalex.org/A5050666730][Lyudmila V. Moskaleva]], [[https://openalex.org/A5100364230][Peng Zhang]], [[https://openalex.org/A5084194253][Zhi‐Jian Zhao]], [[https://openalex.org/A5084194253][Zhi‐Jian Zhao]], Science China Chemistry. None(None)] 2024. https://doi.org/10.1007/s11426-024-2292-3 
     
No abstract    

    

* Solar light-assisted electrochemical CO2 reduction on Boron-doped Diamond cathode  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403192270
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4se00947a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403192270"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403192270"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403192270"))][Get cited by]]

OpenAlex: https://openalex.org/W4403192270 (Open access: False)
    
[[https://openalex.org/A5055546109][Goki Iwai]], [[https://openalex.org/A5045302625][Andrea Fiorani]], [[https://openalex.org/A5080741768][Chiaki Terashima]], [[https://openalex.org/A5054069544][Yasuaki Einaga]], Sustainable Energy & Fuels. None(None)] 2024. https://doi.org/10.1039/d4se00947a 
     
In this study, photoelectrochemical water oxidation with a hematite (α-Fe 2 O 3 ) photoanode and electrochemical CO 2 reduction with a boron-doped diamond (BDD) cathode were combined to convert CO 2 into formic acid under...    

    

* Unveiling the Roles of Lattice Strain on Cu Doped Ag Nanosheet for Electrochemical Co2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403176482
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Thermoelectric Materials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4978806")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403176482"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403176482"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403176482"))][Get cited by]]

OpenAlex: https://openalex.org/W4403176482 (Open access: False)
    
[[https://openalex.org/A5100837279][Mei Zhu]], [[https://openalex.org/A5100458269][Ting Zhang]], [[https://openalex.org/A5087563095][Xin Du]], [[https://openalex.org/A5101043477][Jinlong Wu]], [[https://openalex.org/A5100439027][Xiuli Wang]], [[https://openalex.org/A5100405896][Jin Zhang]], [[https://openalex.org/A5100448832][Feng Li]], [[https://openalex.org/A5100378741][Jing Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4978806 
     
No abstract    

    

* Review for "Interplanar synergy of copper-based electrocatalyst favors reduction of CO2 into C2+ products"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403224119
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-07-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ey00141a/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403224119"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403224119"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403224119"))][Get cited by]]

OpenAlex: https://openalex.org/W4403224119 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ey00141a/v1/review1 
     
No abstract    

    

* Review for "Interplanar synergy of copper-based electrocatalyst favors reduction of CO2 into C2+ products"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403223487
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-08-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ey00141a/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403223487"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403223487"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403223487"))][Get cited by]]

OpenAlex: https://openalex.org/W4403223487 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ey00141a/v1/review2 
     
No abstract    

    

* Review for "Interplanar synergy of copper-based electrocatalyst favors reduction of CO2 into C2+ products"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403224103
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ey00141a/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403224103"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403224103"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403224103"))][Get cited by]]

OpenAlex: https://openalex.org/W4403224103 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ey00141a/v2/review1 
     
No abstract    

    

* Air pollution mitigation and CO2 emission reduction effects of heterogeneous enterprises synergistic agglomeration  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403170973
:TOPICS: Economic Impact of Environmental Policies and Resources, Spatial Economics and Agglomeration Theory, Impact of Infrastructure and Taxation on Economic Growth
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10668-024-05497-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403170973"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403170973"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403170973"))][Get cited by]]

OpenAlex: https://openalex.org/W4403170973 (Open access: False)
    
[[https://openalex.org/A5100327223][Jiamin Liu]], [[https://openalex.org/A5039772760][Xiaoyu Ma]], [[https://openalex.org/A5062966512][Jiaoning Zhang]], [[https://openalex.org/A5073728540][Chiqun Hu]], [[https://openalex.org/A5068545546][Qiuqiu Guo]], Environment Development and Sustainability. None(None)] 2024. https://doi.org/10.1007/s10668-024-05497-2 
     
No abstract    

    

* Author response for "Interplanar synergy of copper-based electrocatalyst favors reduction of CO2 into C2+ products"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403224004
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-09-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ey00141a/v2/response1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403224004"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403224004"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403224004"))][Get cited by]]

OpenAlex: https://openalex.org/W4403224004 (Open access: False)
    
[[https://openalex.org/A5101687908][Jiangnan Li]], [[https://openalex.org/A5084806004][Xinyi Duan]], [[https://openalex.org/A5062302560][Chao Wu]], [[https://openalex.org/A5032642250][Yucheng Cao]], [[https://openalex.org/A5007032744][Zhiyao Duan]], [[https://openalex.org/A5034984355][Peng Zhang]], [[https://openalex.org/A5101310705][Wenjun Fan]], [[https://openalex.org/A5033612713][Fuxiang Zhang]], No host. None(None)] 2024. https://doi.org/10.1039/d4ey00141a/v2/response1 
     
No abstract    

    

* Electrodeposited Cu2o@Cu Hierarchical Structures for Electrocatalytic Co2 Reduction: Morphological Tuning and Copper Mediation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403176058
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4979269")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403176058"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403176058"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403176058"))][Get cited by]]

OpenAlex: https://openalex.org/W4403176058 (Open access: False)
    
[[https://openalex.org/A5100626308][Wang Zhen]], [[https://openalex.org/A5032386955][Yanmin Zhao]], [[https://openalex.org/A5028786427][Weirui Chen]], [[https://openalex.org/A5018986225][Gaozu Liao]], [[https://openalex.org/A5101797518][Laisheng Li]], [[https://openalex.org/A5100378635][Jing Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4979269 
     
No abstract    

    

* Decision letter for "Interplanar synergy of copper-based electrocatalyst favors reduction of CO2 into C2+ products"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403223846
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-08-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ey00141a/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403223846"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403223846"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403223846"))][Get cited by]]

OpenAlex: https://openalex.org/W4403223846 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ey00141a/v1/decision1 
     
No abstract    

    

* Decision letter for "Interplanar synergy of copper-based electrocatalyst favors reduction of CO2 into C2+ products"  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403224106
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ey00141a/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403224106"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403224106"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403224106"))][Get cited by]]

OpenAlex: https://openalex.org/W4403224106 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ey00141a/v2/decision1 
     
No abstract    

    

* CH4 and CO2 Reductions from Methanol Production Using Municipal Solid Waste Gasification with Hydrogen Enhancement  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403190063
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Biomass Pyrolysis and Conversion Technologies, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16198649")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403190063"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403190063"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403190063"))][Get cited by]]

OpenAlex: https://openalex.org/W4403190063 (Open access: True)
    
[[https://openalex.org/A5062067459][Mohammad Ostadi]], [[https://openalex.org/A5019648851][D.R. Cohn]], [[https://openalex.org/A5066936008][Guiyan Zang]], [[https://openalex.org/A5043885940][L. Bromberg]], Sustainability. 16(19)] 2024. https://doi.org/10.3390/su16198649 
     
This study evaluates the greenhouse gas (GHG) impacts of converting municipal solid waste (MSW) into methanol, focusing on both landfill methane (CH₄) emission avoidance and the provision of cleaner liquid fuels with lower carbon intensity. We conduct a life cycle assessment (LCA) to assess potential GHG reductions from MSW gasification to methanol, enhanced with hydrogen produced via natural gas pyrolysis or water electrolysis. Hydrogen enhancement effectively doubles the methanol yield from a given amount of MSW. Special attention is given to hydrogen production through natural gas pyrolysis due to its potential for lower-cost hydrogen and reduced reliance on renewable electricity compared to electrolytic hydrogen. Our analysis uses a case study of methanol production from an oxygen-fired entrained flow gasifier fed with refuse-derived fuel (RDF) simulated in Aspen HYSYS. The LCA incorporates the significant impact of landfill methane avoidance, particularly when considering the 20-year global warming potential (GWP). Based on the LCA, the process has illustrative net GHG emissions of 183 and 709 kgCO2e/t MeOH using renewable electricity for electrolytic hydrogen and pyrolytic hydrogen, respectively, for the 100-year GWP. The net GHG emissions using 20-year GWP are −1222 and −434 kgCO2e/t MeOH, respectively. Additionally, we analyze the sensitivity of net GHG emissions to varying levels of fugitive methane emissions.    

    

* Fabrication of mesoporous sulfated ZnO-modified g-C3N4 and TiO2 photocatalysts for CO2 reduction in gas phase  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403157643
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cattod.2024.115089")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403157643"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403157643"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403157643"))][Get cited by]]

OpenAlex: https://openalex.org/W4403157643 (Open access: False)
    
[[https://openalex.org/A5039200898][L.A. Al-Hajji]], [[https://openalex.org/A5087857810][Adel A. Ismail]], [[https://openalex.org/A5052431130][M. Alsaidi]], [[https://openalex.org/A5082555423][Ahmed Abdel Nazeer]], [[https://openalex.org/A5053395832][Ahmed Mohamed El‐Toni]], [[https://openalex.org/A5107769307][S.F. Al-Ruwayeh]], [[https://openalex.org/A5103869609][S.A. Ahmed]], [[https://openalex.org/A5107769308][T. Al-Sharrah]], Catalysis Today. None(None)] 2024. https://doi.org/10.1016/j.cattod.2024.115089 
     
No abstract    

    

* Convenient partial reduction of CO2 to a useful C1 building block: efficient access to 13C‐labelled N‐heterocyclic carbenes  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403214267
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Deuterium Incorporation in Pharmaceutical Research, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202401179")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403214267"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403214267"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403214267"))][Get cited by]]

OpenAlex: https://openalex.org/W4403214267 (Open access: False)
    
[[https://openalex.org/A5102128029][Nicholas A. Phillips]], [[https://openalex.org/A5051394623][Joshua S. Sapsford]], [[https://openalex.org/A5058011790][Dániel Csókás]], [[https://openalex.org/A5041928994][Bianka Kótai]], [[https://openalex.org/A5107821512][Ines Perez-Tabarnero]], [[https://openalex.org/A5068447207][Silvia Díez‐González]], [[https://openalex.org/A5008359579][Daniel Scott]], [[https://openalex.org/A5048846178][Imre Pápai]], [[https://openalex.org/A5089340041][Andrew E. Ashley]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202401179 
     
The selective, transition metal‐free hydrosilylation of CO2 to CH2(OSiEt3)2 has been achieved under mild conditions and in high isolated yields (up to 90%) using Et3SiH and the simple, easily prepared borohydride catalyst Li+[HB(C6F5)3]−. The resulting CO2‐derived bis(silyl)acetal product – whose mechanism of formation has been interrogated through detailed computational and experimental studies – can be rapidly valorized through the facile synthesis of N‐heterocyclic carbenes, via their corresponding imidazolium salts. By using relatively inexpensive, isotopically enriched 13CO2 this protocol can be exploited to prepare NHC isotopologues that are selectively 13C labelled at the key, ligating C2 position. This provides an electronically responsive 13C NMR spectroscopic handle with dramatically enhanced sensitivity which can directly benefit reactivity studies in both organo‐ and organometallic catalysis, where NHC use is ubiquitous.    

    

* Effect of Pre-sodium Hydroxide and Post-heat Treatments on Copper Oxide-Based Photocathode: A Perspective on Photoelectrochemical Water Splitting and CO2 Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403187249
:TOPICS: Formation and Properties of Nanocrystals and Nanostructures, Photocatalytic Materials for Solar Energy Conversion, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11664-024-11498-8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403187249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403187249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403187249"))][Get cited by]]

OpenAlex: https://openalex.org/W4403187249 (Open access: False)
    
[[https://openalex.org/A5081867561][Saowaluk Intarasiri]], [[https://openalex.org/A5043190945][Surangkana Wannapop]], [[https://openalex.org/A5081447365][Asanee Somdee]], Journal of Electronic Materials. None(None)] 2024. https://doi.org/10.1007/s11664-024-11498-8 
     
No abstract    

    

* Important structural parameter for curvature effect of TM-N4 embeded C70 fullerenes as electrocatalysts for CO2 reduction interpreted with machine learning and first-principles calculations  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403168428
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Accelerating Materials Innovation through Informatics, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.105233")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403168428"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403168428"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403168428"))][Get cited by]]

OpenAlex: https://openalex.org/W4403168428 (Open access: False)
    
[[https://openalex.org/A5009783384][Aling Ma]], [[https://openalex.org/A5012102127][Zongpeng Ding]], [[https://openalex.org/A5102634533][YuShan Pang]], [[https://openalex.org/A5038934588][Guohong Fan]], [[https://openalex.org/A5017163237][Hong Xu]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.105233 
     
No abstract    

    

* INTEGRATED TECHNOLOGY OF BIOGAS UTILIZATION OF SOLID HOUSEHOLD WASTE LANDFILLS WITH THE PRODUCTION OF ELECTROCITY, HEAT AND CARBON DIOXIDE  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403167145
:TOPICS: Energy Transition and Renewable Resources Integration, Mechanical Engineering and Optimization Techniques, Wireless Sensor Networks for Data Analysis
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.33070/etars.3.2024.04")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403167145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403167145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403167145"))][Get cited by]]

OpenAlex: https://openalex.org/W4403167145 (Open access: True)
    
[[https://openalex.org/A5028585095][Yu.V. Ivanov]], [[https://openalex.org/A5024576741][Serhii Krushnevych]], [[https://openalex.org/A5042431894][H.V. Zhuk]], [[https://openalex.org/A5079699978][Л.Р. Онопа]], [[https://openalex.org/A5107787365][O.V. Verbovskyi]], [[https://openalex.org/A5029606240][Dmitrii Komissarenko]], Energy Technologies & Resource Saving. 80(3)] 2024. https://doi.org/10.33070/etars.3.2024.04  ([[https://etars-journal.org/index.php/journal/article/download/403/336][pdf]])
     
The presence of carbon dioxyl as a non-combustible admixture in the landfill biogas of solid household waste and the absorption of ambient air into the layer of landfill waste, and therefore its entry into the landfill gas, significantly reduces the concentration of methane in it, which affects the efficient operation of the gas piston engine of the power plant and the reduction of volumes electricity generation. With the use of computer modeling for the composition of biogas with an increased content of N2 and a reduced concentration of CH4 £ 32 %, calculations were made on the enrichment of biogas to concentrations of CH4 in it of 36–44 % due to the use of CO2 amine absorption technologies, in which the costs for the regeneration of the absorbent are compensated by the produced thermal energy of the gas piston engine of the power plant. The removal of carbon dioxide from biogas makes it possible to simultaneously increase the concentration of methane in it at the input to the heat engine, which contributes to the stable and efficient operation of the gas piston engine of the power plant and the increase in the amount of electricity generation as a result of energy utilization of landfill gas. The use of complex biogas utilization technology in the cogeneration mode allows obtaining not only electricity, but also heat, which can be used in absorption amine technologies for CO2 extraction from biogas and thus reducing carbon dioxide emissions into the atmosphere. Bibl. 17, Fig. 9, Tab. 3.    

    

* Structural Control of Copper-Based MOF Catalysts for Electroreduction of CO2: A Review  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403296453
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/pr12102205")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403296453"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403296453"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403296453"))][Get cited by]]

OpenAlex: https://openalex.org/W4403296453 (Open access: True)
    
[[https://openalex.org/A5028724152][Hongxin Fu]], [[https://openalex.org/A5061720775][Hailing Ma]], [[https://openalex.org/A5039113583][Shuaifei Zhao]], Processes. 12(10)] 2024. https://doi.org/10.3390/pr12102205 
     
With the excessive use of fossil fuels, atmospheric carbon dioxide (CO2) concentrations have risen dramatically in recent decades, leading to serious environmental and social issues linked to global climate change. The emergence of renewable energy sources, such as solar, tidal, and wind energy, has created favorable conditions for large-scale electricity production. Recently, significant attention has been drawn to utilizing renewable energy to catalyze the conversion of CO2 into fuels, producing substantial industrial feedstocks. In these CO2 conversion processes, the structure and performance of catalysts are critical. Metal-organic frameworks (MOFs) and their derivatives have emerged as promising electrocatalysts for CO2 reduction, offering advantages such as high surface area, porosity, exceptional functionality, and high conversion efficiency. This article provides a comprehensive review of structural regulation strategies for copper-based MOFs, highlighting innovative mechanisms like synergistic bimetallic catalysis, targeted doping strategies, and the construction of heterostructures. These novel approaches distinguish this review from previous studies, offering new insights into the electrocatalytic performance of copper-based MOFs and proposing future research directions for improved catalyst design.    

    

* Impact and Emission of Greenhouse Gases from Paddy Fields and their Mitigation Techniques  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403170447
:TOPICS: Meta-analysis in Ecology and Agriculture Research, Soil Carbon Dynamics and Nutrient Cycling in Ecosystems
:PUBLICATION_DATE: 2024-02-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.70436/nuijb.v3i02.207")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403170447"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403170447"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403170447"))][Get cited by]]

OpenAlex: https://openalex.org/W4403170447 (Open access: False)
    
[[https://openalex.org/A5052829679][Kifayatullah Kakar]], [[https://openalex.org/A5076919362][Asmatullah Durani]], [[https://openalex.org/A5107788595][Tariqullah Hashimi]], [[https://openalex.org/A5107788596][Bakhtmuneer Baber]], [[https://openalex.org/A5018048480][Gulbuddin Gulab]], [[https://openalex.org/A5062090837][Zabihullah Safi]], No host. 03(ICCC(special))] 2024. https://doi.org/10.70436/nuijb.v3i02.207 
     
Agricultural soil functions as both a supplier and absorber of significant greenhouse gases (GHGs) such as methane (CH4), nitrous oxide (N2O), and carbon dioxide (CO2). The scientific community has expressed significant concern regarding rice paddies, as they are responsible for the production of greenhouse gases (GHGs) that pose a long-lasting threat. The primary GHGs emitted from these fields are CH4 and N2O, accounting for approximately 30% and 11% of global agricultural emissions, respectively. Consequently, there is an urgent need to accurately measure the fluxes of CH4 and N2O in order to enhance our comprehension of these gases originating from rice fields. This understanding will enable the development of effective mitigation tactics to combat future climate change. This review aims to exclusively focus on the emission of CH4 and N2O in poddy fields, while also examining the impact of field and crop management activities on these emissions. Modifying traditional crop management practices could yield substantial results in mitigating greenhouse gas (GHG) emissions in poddy fields. By implementing effective management techniques, both environmental and agricultural aspects pertaining to soil can be readily adjusted. Therefore, comprehending the process of CH4 and N2O generation and release in poddy fields, as well as the factors governing these emissions, is crucial for devising efficient strategies to minimize emissions from poddy fields. This will assist regulatory bodies and policymakers in developing appropriate policies for agricultural farmers to enhance the reduction of GHG emissions and mitigate global climate change.    

    

* Enhancement of electrocatalytic CO2 performance by different components of Cu-based bimetallic MOFs  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403199149
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj03650f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403199149"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403199149"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403199149"))][Get cited by]]

OpenAlex: https://openalex.org/W4403199149 (Open access: False)
    
[[https://openalex.org/A5101825565][Jiangwen Liu]], [[https://openalex.org/A5100382001][Qiang Zhang]], [[https://openalex.org/A5100736608][Jianlin Wang]], [[https://openalex.org/A5045804672][Conglin Chen]], [[https://openalex.org/A5082605654][Shenjie Zhang]], [[https://openalex.org/A5087025205][Fang Guo]], [[https://openalex.org/A5058165733][Junqiang Xu]], New Journal of Chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj03650f 
     
Cu-based catalysts have been promising materials for electrocatalytic reduction of carbon dioxide into C 2+ products.    

    

* Design and Implementation of a Facility Intelligent Carbon Dioxide Incubator Control System Based on Improved POA Optimized Fuzzy PID for the Incubation of Termitomyces mushrooms  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403197730
:TOPICS: Medicinal Mushrooms: Antitumor and Immunomodulating Properties, Korean Traditional Food and Health Science
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4984494/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403197730"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403197730"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403197730"))][Get cited by]]

OpenAlex: https://openalex.org/W4403197730 (Open access: True)
    
[[https://openalex.org/A5000418030][Qiangke Luo]], [[https://openalex.org/A5007437651][Zeshuang Zhao]], [[https://openalex.org/A5056058434][Huanbo Zhang]], [[https://openalex.org/A5078457015][Guan Lin]], [[https://openalex.org/A5102943651][Juntao Gao]], [[https://openalex.org/A5014714438][Yong Liu]], [[https://openalex.org/A5048330288][Lingxue Kong]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4984494/v1  ([[https://www.researchsquare.com/article/rs-4984494/latest.pdf][pdf]])
     
Abstract To address the issue of accurately controlling the carbon dioxide environment required for the cultivation of Termitomyces mushrooms in traditional carbon dioxide incubators, and improve the cultivation environment of Termitomyces mushrooms, this study designed an intelligent carbon dioxide incubator control system suitable for the laboratory cultivation of Termitomyces mushrooms. The system was based on an improved POA to optimize fuzzy PID control, regulating the opening of the solenoid valve to precisely control the carbon dioxide concentration in the incubator. Simulation and comparison tests of the improved POA-based optimized fuzzy PID control, PID control, and fuzzy PID control were carried out by MATLAB/Simulink software, which indicated that the system’s overshoot was reduced by 11.7%, the adjustment time was shortened by 71.1 s, and the steady-state error was reduced by 0.1%. The reductions in overshoot, adjustment time, and steady-state error showed that POA-optimized fuzzy PID control was superior to fuzzy PID control in terms of accuracy, response, and stability, with better robustness. In addition, the growth of the Termitomyces eurrhizus MLY19 strain in the incubator environment was compared to that of a traditional carbon dioxide incubator, and we found that the diameters of the cultured Termitomyces mushroom MLY19 cell colonies in the improved incubator were 45.3% and 73.8% larger at 7 and 14 days, respectively. Therefore, the carbon dioxide control system of the Termitomyces mushroom incubator offered a high practical application value.    

    

* The Reduction in the Number of CO2 Defects in the Process of Obtaining Breathing Air for Hyperbaric Oxygen Conditions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403162272
:TOPICS: Mechanical Ventilation in Respiratory Failure and ARDS
:PUBLICATION_DATE: 2023-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2478/phr-2023-0001")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403162272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403162272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403162272"))][Get cited by]]

OpenAlex: https://openalex.org/W4403162272 (Open access: False)
    
[[https://openalex.org/A5070264803][Arkadiusz Woźniak]], Polish Hyperbaric Research. 82(1)] 2023. https://doi.org/10.2478/phr-2023-0001 
     
Abstract Maintaining a stable carbon dioxide content in the process of obtaining breathing air is essential for safe underwater operations and the reduction of the cost of losses resulting from a poor quality product. The paper addresses the modification of the hyperbaric breathing air production process in terms of eliminating harmful carbon dioxide contaminants. It presents the effects of the modifications made to the process in order to minimise the proportion of defects. A description is given of the status of the process before and after the correction in terms of the identified areas of improvement leading to the achievement of the defined critical requirements of the process. Achievement of the objective to rationalise the breathing air production process was confirmed by results of tests carried out at KTPP AMW 1 based on the compressed air supply system of the DGKN - 120 complex 2 .    

    

* Carbon Dioxide Capture and Sequestration for Production of Synthetic Materials  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403219674
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Biodegradable Polymers as Biomaterials and Packaging, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.18412/1816-0395-2024-10-4-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403219674"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403219674"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403219674"))][Get cited by]]

OpenAlex: https://openalex.org/W4403219674 (Open access: False)
    
[[https://openalex.org/A5107823098][E.L. Kolychev]], [[https://openalex.org/A5043473422][Artem Sulimov]], [[https://openalex.org/A5103914421][К. А. Овчинников]], [[https://openalex.org/A5029281669][A. V. Kleimenov]], Ecology and Industry of Russia. 28(10)] 2024. https://doi.org/10.18412/1816-0395-2024-10-4-9 
     
The processes of carbon dioxide sequestration at obtaining various inorganic carbonate materials, including with the use of biotechnologies, and formation of organic polymers and monomers for them from CO 2 are considered. It is revealed that in the case of inorganic materials the use of slags and sludges containing a large amount of metal oxides from various industries looks the most appropriate, and in the case of materials based on organic polymers the technologies based on polycarbonates, as well as polycarbonate-containing polyols and phosgene-free isocyanates for polyurethanes are preferable. New promising methods under active development but not yet industrially applied, such as electrochemical reduction of carbon dioxide and its condensation with butadiene, are analyzed.    

    

* Ways to Decarbonize the Construction Industry as a Modern Challenge for Obtaining Low-Carbon Building Materials  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403194837
:TOPICS: Innovative Mining Technology and Sustainable Development, Technological Development in Mineral Resource Sector, Materials Science and Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.31659/0585-430x-2024-828-9-51-57")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403194837"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403194837"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403194837"))][Get cited by]]

OpenAlex: https://openalex.org/W4403194837 (Open access: False)
    
[[https://openalex.org/A5063932936][Said-Alvi Murtazaev]], [[https://openalex.org/A5107814832][L.R. BEKMURZAEVA]], [[https://openalex.org/A5066336133][Madina Salamanova]], [[https://openalex.org/A5012212416][М.С. Сайдумов]], [[https://openalex.org/A5107814833][R.S. VITARGOVA]], Stroitel nye Materialy. None(None)] 2024. https://doi.org/10.31659/0585-430x-2024-828-9-51-57 
     
The analysis of modern approaches and ideas for the production of new building composite materials with a low carbon footprint, including those obtained using recycled materials from man-made waste, is presented. It is concluded that the reduction of carbon dioxide emissions in the production of low-carbon concretes occurs as a result of replacing part of the cement with other types of binders or special fillers that ensure the preservation or improvement of the basic parameters of the structure of the building material, or due to technologies that reduce the clinker fraction of the binder while maintaining the specified properties of concrete. The leaders in the world practice in the field of low-carbon materials science are noted. The relevance of the development of the topic of environmental safety and sustainable development is indicated.    

    

* Comparative analysis of embodied carbon in modular and conventional construction methods in Hong Kong  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403246062
:TOPICS: Building Information Modeling in Construction Industry, 3D Concrete Printing Technology, Parametric Architecture and Urban Design
:PUBLICATION_DATE: 2024-10-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41598-024-73906-7")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403246062"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403246062"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403246062"))][Get cited by]]

OpenAlex: https://openalex.org/W4403246062 (Open access: True)
    
[[https://openalex.org/A5014167353][Jiaying Wei]], [[https://openalex.org/A5029104703][Bin Ge]], [[https://openalex.org/A5100307040][Ying Zhong]], [[https://openalex.org/A5035720224][Tik Long Lee]], [[https://openalex.org/A5100388118][Yi Zhang]], Scientific Reports. 14(1)] 2024. https://doi.org/10.1038/s41598-024-73906-7 
     
Addressing the rise in global temperatures and the associated increase in greenhouse gases, particularly carbon dioxide, is a critical challenge necessitating innovative approaches within the building sector, a significant contributor to worldwide carbon emissions. While previous studies have demonstrated the prefabrication's potential in reducing emissions, comprehensive assessments using actual project data for buildings constructed entirely with modular methods in Hong Kong are lacking. This study bridges this gap by evaluating the modular integrated construction (MiC) method through an embodied carbon assessment of the Kai Tak Community Isolation Facility. Using comprehensive project data from China State Construction (HK) Limited, the research conducts a comparative analysis between the actual emissions of the MiC method and those of a hypothetical conventional construction approach. Quantitative analysis reveals that MiC achieves a 20.7% reduction in embodied carbon, primarily due to shortened construction timelines, decreased waste generation, and optimized material usage. This significant reduction suggests substantial potential for decreasing the construction industry's carbon footprint. The study provides empirical evidence supporting the environmental benefits of MiC in Hong Kong construction industry, promoting its broader adoption of MiC as a strategy for achieving carbon reduction targets. The findings align with Hong Kong's carbon neutrality goals and contribute to the global initiative to mitigate the effects of climate change.    

    

* The Effects on Climate Change Due to Kitchen Waste Composting and Emissions of Carbon Dioxide  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403154375
:TOPICS: 
:PUBLICATION_DATE: 2024-02-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.70436/nuijb.v3i02.198")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403154375"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403154375"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403154375"))][Get cited by]]

OpenAlex: https://openalex.org/W4403154375 (Open access: False)
    
[[https://openalex.org/A5043105108][Nora’aini Ali]], [[https://openalex.org/A5107767888][Riaz Husnain]], [[https://openalex.org/A5107767889][Munir Baber Bakht]], [[https://openalex.org/A5107767890][Iqbal Tasawar]], No host. 03(ICCC(special))] 2024. https://doi.org/10.70436/nuijb.v3i02.198 
     
The emission of greenhouse gases into the atmosphere due to anthropogenic activities, including the disposal of large quantities of organic kitchen waste into the environment. There is currently no evidence suggesting the likelihood of a future reversal or pause in emissions. The process of carbon sequestration serves to mitigate the emission of greenhouse gases from kitchen organic waste through the creation of compost. Composting is proposed as a potentially effective and cost-efficient solution to address the issue production of kitchen organic waste, which is contributing to environmental pollution. The escalation in complete carbon dioxide and microbial biomass carbon emissions can be attributed to a concurrent reduction in the levels of dissolved organic carbon as the treatments experienced a noteworthy decrease in dissolved organic carbon concentrations. The application of banana and potato compost has been found to have a positive impact on the macro aggregates of soil, leading to an increase in soil stability due to the compost's ability to stabilize soil particles. The study indicate that composting represents the most effective approach for mitigating greenhouse gas emissions originating from kitchen organic waste, while also enhancing the biological and physicochemical characteristics of soil.    

    

* The Role of Catalytic Vehicles in the Reduction of Environmental Pollution in Nangrahar City of Afghanistan  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403228494
:TOPICS: Impact of China-Pakistan Economic Corridor (CPEC), Conflict Reconstruction and State-Building in Central Asia
:PUBLICATION_DATE: 2024-02-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.70436/nuijb.v3i02.293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403228494"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403228494"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403228494"))][Get cited by]]

OpenAlex: https://openalex.org/W4403228494 (Open access: False)
    
[[https://openalex.org/A5108160590][Bashir ullah Safi]], [[https://openalex.org/A5108160591][Fazal Rahman Mukhlis Safi]], [[https://openalex.org/A5108160592][Abdul Rabi Atif]], No host. 03(ICCC(special))] 2024. https://doi.org/10.70436/nuijb.v3i02.293 
     
Due to the increase in the number of vehicles in the cities, air pollution is one of the serious environmental hazards because it increases the greenhouse gases in the atmosphere and causes climate change. To reduce the bad effects of the gases produced by car engines, the gases are filtered with the help of a catalytic in the silencer of the car (carbon monoxide to carbon dioxide, nitrogen monoxide to nitrogen oxide and hydrocarbons to water vapor) before it leaves the silencer of the car. The catalytic was synthesized in 1895 from various expensive (platinum, rhodium, palladium) materials that work as a result of chemical reactions and have a high price. The purpose of this research is to inform people about the role and value of catalytic in preventing environmental pollution in the eastern zone of Afghanistan. Data was collected through online questionnaire and interviews from 102 participants. The findings of the research show that the catalytic play a vital role in the reduction of environmental pollution in Nangarhar city of Afghanistan. The study revealed that catalytic helps the cars in the prevention of air pollution. The catalytic breaks down dangerous gases into environment friendly gases before they leave the silencer of the car and so has a great role in the reduction of environmental pollution. Similarly, the catalytic is an essential part of the car that has a vital role in the health of the car i.e., the car having the catalytic will be in good condition for a longer period of time, will go with high speed and will use less fuel. Moreover, the use of catalytic is recommended in every car and other fuel consuming machines to avoid environmental pollution.    

    

* Agricultural Productivity and Climate Mitigation  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403184700
:TOPICS: Economic Implications of Climate Change Policies, Measurement and Evaluation of Sustainable Development
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1146/annurev-resource-101323-094349")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403184700"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403184700"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403184700"))][Get cited by]]

OpenAlex: https://openalex.org/W4403184700 (Open access: True)
    
[[https://openalex.org/A5021255255][Keith O. Fuglie]], [[https://openalex.org/A5074526613][Thomas W. Hertel]], [[https://openalex.org/A5026642372][David B. Lobell]], [[https://openalex.org/A5030664203][Nelson B. Villoria]], Annual Review of Resource Economics. 16(1)] 2024. https://doi.org/10.1146/annurev-resource-101323-094349 
     
Agriculture will play a central role in meeting greenhouse gas (GHG) emission targets, as the sector currently contributes ∼22% of global emissions. Because emissions are directly tied to resources employed in farm production, such as land, fertilizer, and ruminant animals, the productivity of input use tends to be inversely related to emissions intensity. We review evidence on how productivity gains in agriculture have contributed to historical changes in emissions, how they affect land use emissions both locally and globally, and how investments in research and development (R&D) affect productivity and therefore emissions. The world average agricultural emissions intensity fell by more than half since 1990, with a strong correlation between a region's agricultural productivity growth and reduction in emissions intensity. Additional investment in agricultural R&D offers an opportunity for cost-effective (<US$30 per ton carbon dioxide) and large-scale emissions reductions. Innovations that target specific commodities or inputs could even further reduce the cost of climate mitigation in agriculture.    

    

* Self-Inhibition Phenomena in Cu3Pt Oxidation by CO2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403183740
:TOPICS: Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.4c02218")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403183740"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403183740"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403183740"))][Get cited by]]

OpenAlex: https://openalex.org/W4403183740 (Open access: False)
    
[[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5032792310][Shyam Bharatkumar Patel]], [[https://openalex.org/A5070392626][J. Anibal Boscoboinik]], [[https://openalex.org/A5061621593][Adrian Hunt]], [[https://openalex.org/A5053922026][Iradwikanari Waluyo]], [[https://openalex.org/A5009173681][Guangwen Zhou]], The Journal of Physical Chemistry Letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.4c02218 
     
This study investigates the oxidation behavior of Cu3Pt(100) in CO2 using a combination of ambient-pressure X-ray photoelectron spectroscopy, mass spectroscopy, and density functional theory modeling. Our in situ measurements reveal the simultaneous oxidation and reduction of Cu2O due to the opposing effects of atomic oxygen and CO generated from dissociative CO2 adsorption, leading to a dynamic equilibrium state of simultaneously occurring redox reactions. Complementary atomistic calculations elucidate the inhibitory effects of subsurface Pt enrichment and the counteracting roles of CO2 and CO in surface oxidation and reduction. These results provide mechanistic insights into the dissociative pathway of CO2 molecules and dynamic evolution of surface composition and reactivity of Cu-based alloy catalysts in CO2-rich environments, with broader implications for tuning gas–surface reactions by manipulating gas reactants or solid surface composition.    

    

* Dynamic Interactive Effects of Technological Innovation, Transportation Industry Development, and CO2 Emissions  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403216540
:TOPICS: Rebound Effect on Energy Efficiency and Consumption, Economic Impact of Environmental Policies and Resources, Understanding Attitudes Towards Public Transport and Private Car
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16198672")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403216540"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403216540"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403216540"))][Get cited by]]

OpenAlex: https://openalex.org/W4403216540 (Open access: True)
    
[[https://openalex.org/A5013069987][Kaige An]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5101634974][Zhenning Wang]], [[https://openalex.org/A5100835325][Zisen He]], [[https://openalex.org/A5058610425][Yao Zhong]], [[https://openalex.org/A5101475014][Jia Shen]], [[https://openalex.org/A5034235407][Xiaohong Ren]], Sustainability. 16(19)] 2024. https://doi.org/10.3390/su16198672  ([[https://www.mdpi.com/2071-1050/16/19/8672/pdf?version=1728384856][pdf]])
     
This paper aims to clarify the intricate relationships between technological innovation, transportation industry development, and CO2 emissions to facilitate a positive synergy among technology, the economy, and climate, advancing the fulfillment of the ‘double carbon’ goal. Utilizing panel data from 30 provinces in China from 2005 to 2020, we employ the panel vector autoregressive model using a generalized method of moments to empirically examine the dynamic interactive effects between these participants. The findings reveal that the transportation industry significantly promoted the inhibitory impact of technological innovation on CO2 emissions. However, such reductions cannot counterbalance the rise in emissions from the transportation industry. Moreover, its effects varied significantly across regions. Specifically, transportation industry development within eastern China contributed to a shift in the local carbon emission effects from positive to negative under the positive influence of technological innovation. In the northeast, the transportation industry enhanced the inhibitory effect of technological innovation on CO2 emissions. In contrast, across the western region, industrial development in transportation intensified the role of technological innovation in promoting CO2 emissions. Furthermore, this work found that CO2 emissions notably diminished the CO2 reduction performance of technological innovation in the eastern part and enhanced this performance in the northeastern region. These findings further revealed the complex interplay between technological innovation, the transportation industry, and CO2 emissions. They offer insights for policymakers to tailor region-specific technologies to bolster the ‘dual carbon’ goal and sustainable transportation development strategies, thereby achieving CO2 reduction.    

    

* Molecular Dynamics Simulations for Electrocatalytic CO2 Reduction: Bridging Macroscopic Experimental Observations and Microscopic Explanatory Mechanisms  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403202351
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202413703")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403202351"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403202351"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403202351"))][Get cited by]]

OpenAlex: https://openalex.org/W4403202351 (Open access: False)
    
[[https://openalex.org/A5070744215][Yanzheng He]], [[https://openalex.org/A5100627066][Mengfan Wang]], [[https://openalex.org/A5009366641][Haoqing Ji]], [[https://openalex.org/A5059545154][Qiyang Cheng]], [[https://openalex.org/A5100644544][Sisi Liu]], [[https://openalex.org/A5079957444][Yunfei Huan]], [[https://openalex.org/A5032588771][Qian Tao]], [[https://openalex.org/A5009136959][Chenglin Yan]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202413703 
     
Abstract Electrocatalytic carbon dioxide reduction reaction (CO 2 RR) has been recognized as a promising route to convert carbon emissions to high‐value chemicals and fuels. Significant breakthroughs are usually inseparable from deeper understanding of reaction mechanisms. To this end, molecular dynamics (MD) simulations have been invaluable in providing detailed insights into elucidation of complex reaction pathways and prediction of overall electrochemical performance, thus bridging macroscopic experimental observations and microscopic explanatory mechanisms. Directed by MD simulations, tremendous efforts have been devoted toward enhancing the CO 2 RR with rational design of electrocatalyst and efficient construction of electrode/electrolyte interface. Herein, a comprehensive review of applications of MD simulations in CO 2 RR is emerged. To begin with, specific fundamentals along with familiar methods such as algorithm and force fields of various MD simulations have been summed up. Followed, employment of MD simulations in optimization of CO 2 RR is introduced, encompassing interpretation of electrocatalyst activity, explanation of electrolyte effect, and investigation of electrode microenvironment. Definitively, imminent challenges and avenues for optimization in future MD simulations are contemplated, envisioning this review as a guiding beacon for future endeavors aimed at harnessing MD simulations to propel CO 2 RR toward a realm of heightened efficiency, economic viability, and practical utility.    

    

* Revitalizing subterranean spaces: a comprehensive study on enhancing air quality in underground shopping malls for sustainable urban living  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403197110
:TOPICS: Development and Management of Urban Underground Space, Modeling Pedestrian Dynamics and Evacuations, Impact of Information Technology Infrastructure on Various Sectors
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1186/s42834-024-00231-z")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403197110"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403197110"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403197110"))][Get cited by]]

OpenAlex: https://openalex.org/W4403197110 (Open access: True)
    
[[https://openalex.org/A5101620709][Kichul Kim]], [[https://openalex.org/A5102030299][Jiwoong Kim]], [[https://openalex.org/A5086116598][Yun Gyu Lee]], [[https://openalex.org/A5030210246][Seunghwan Wi]], [[https://openalex.org/A5100429098][Sumin Kim]], Sustainable Environment Research. 34(1)] 2024. https://doi.org/10.1186/s42834-024-00231-z  ([[https://sustainenvironres.biomedcentral.com/counter/pdf/10.1186/s42834-024-00231-z][pdf]])
     
Abstract Cities worldwide are increasingly turning to underground spaces to address the challenges posed by high population density. These subterranean areas are now utilized for various purposes such as offices, shopping malls, subway terminals, and underground sidewalks. However, the semi-closed nature of most underground spaces presents difficulties in ensuring a comfortable environment due to the lack of natural ventilation. This study focuses on a representative underground shopping mall in South Korea, utilizing preliminary surveys and long-term sensor monitoring to identify existing problems. The aging ventilation system was retrofitted to enhance and assess indoor air quality. As a result, concentrations of carbon dioxide, total volatile organic compounds, and radon were reduced by over 33, 74, and 98%, respectively, while particulate matter with a diameter of 2.5 μm or less (PM 2.5 ) concentrations remained the same as before. This not only contributed to maintaining proper indoor air quality, but also led to a reduction in total energy consumption. The goal of this project is to improve air quality in facilities located in underground spaces, such as underground shopping malls, where indoor air quality management is challenging, thereby creating a safe and healthy environment for users and enhancing the overall functionality of the facility.    

    

* LCCO2 Assessment and Fertilizer Production from Absorbed-CO2 Solid Matter in a Small-Scale DACCU Plant  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403250453
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Chemical-Looping Technologies, Membrane Gas Separation Technology
:PUBLICATION_DATE: 2024-10-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17195011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403250453"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403250453"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403250453"))][Get cited by]]

OpenAlex: https://openalex.org/W4403250453 (Open access: True)
    
[[https://openalex.org/A5068336803][Tianjiao Cheng]], [[https://openalex.org/A5108336627][takeji hirota]], [[https://openalex.org/A5091554050][Hiroshi Onoda]], [[https://openalex.org/A5028227966][Andante Hadi Pandyaswargo]], Energies. 17(19)] 2024. https://doi.org/10.3390/en17195011 
     
This study investigates a novel method of utilizing Direct Air Capture (DAC) technology for fertilizer production. Unlike traditional Direct Air Carbon Capture and Utilization (DACCU) technologies, Direct Air Carbon Capture for Fertilizers (FDAC) has the potential to produce fertilizers directly. This study aims to assess the feasibility of FDAC-based fertilizer production by examining the current state of traditional DAC technologies, evaluating the CO2 fixation potential of FDAC, and analyzing the decarbonization effect of producing fertilizers using FDAC. Our evaluation results indicate that CO2 emissions from producing 1 ton of conventional chemical fertilizer, FDAC fertilizer (current status), FDAC fertilizer with ingredient adjustment (sodium hydroxide), and FDAC fertilizer with ingredient adjustment (magnesium hydroxide) are 1.69, 1.12, 1.04, and 1.06 tons of CO2, respectively. The FDAC fertilizer (current status) emits 0.57 tons of CO2 per ton less than commercial fertilizers. FDAC fertilizers also have the potential to reduce CO2 emissions further when the fertilizer composition is adjusted, offering a promising solution for lowering the environmental impact of fertilizer production. Significant CO2 reduction can be expected by replacing conventional low-intensity chemical fertilizers with FDAC-produced fertilizers.    

    

* Life cycle assessment of energy green transition goals in Slovenia and Serbia: Heat pump example  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403192692
:TOPICS: Integration of Renewable Energy Systems in Power Grids, Geothermal Energy Technology and Applications, Global Energy Transition and Fossil Fuel Depletion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2298/tsci240618222t")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403192692"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403192692"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403192692"))][Get cited by]]

OpenAlex: https://openalex.org/W4403192692 (Open access: True)
    
[[https://openalex.org/A5046087762][Jelena Topić Božič]], [[https://openalex.org/A5071410260][Simon Muhič]], [[https://openalex.org/A5057674573][Mirko Komatina]], [[https://openalex.org/A5018428597][Milica Perić]], [[https://openalex.org/A5023133420][Jože Dimnik]], Thermal Science. None(00)] 2024. https://doi.org/10.2298/tsci240618222t 
     
Heat pumps are a promising technology to reduce greenhouse gas emissions (GHGE). Their use benefits from decarbonization of the national electricity mixes across the EU, as running on cleaner electricity would reduce the emissions associated with the heat generated from heat pumps. The study aimed to perform a life cycle assessment (LCA) to compare the impact of using heat pumps as a heating source in Slovenia and Serbia under different electricity scenarios that align with measures presented in National Energy and Climate plans. The results show significant differences in the environmental profiles of Serbian and Slovenian electricity sectors and improvements from the current to the future mixes (2030) with a higher share of renewables such as photovoltaics. In the impact category of global warming, an 84.7 % higher value of 1 MJ of heat produced by ground source heat pump in Serbia (0.080 kg CO2 eq) was observed compared to Slovenia (0.033 kg CO2 eq) and 85.9 % higher value compared to Europe (0.032 kg CO2 eq). The reduction in the impact category global warming in NECP 2030 scenarios that model reduction in coal and increase solar PV was observed in both countries (-17.1% Serbia; -28.6 % Slovenia). On the other hand, an increase in the impact category of mineral resource scarcity was observed, with values higher in Slovenia than in Serbia due to a higher share of PV. The study demonstrates that LCA provides a powerful tool to consider GHGE reduction and other environmental impacts, such as land use and mineral resource scarcity, and it can be used to support decision-makers dealing with future national energy plans and decarbonization strategies.    

    

* Permeability evolution of sandstone caprock transverse fractures during intermittent CO2 injection in coal-bearing strata  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403217154
:TOPICS: Carbon Dioxide Sequestration in Geological Formations, Hydraulic Fracturing in Shale Gas Reservoirs, Rock Mechanics and Engineering
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0231372")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403217154"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403217154"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403217154"))][Get cited by]]

OpenAlex: https://openalex.org/W4403217154 (Open access: False)
    
[[https://openalex.org/A5103006931][Zhaolong Ge]], [[https://openalex.org/A5099362208][Qisi Huai]], [[https://openalex.org/A5084427193][Zhe Zhou]], [[https://openalex.org/A5016417719][Jingwei Zheng]], [[https://openalex.org/A5082309852][Qinglin Deng]], [[https://openalex.org/A5079249290][Yunzhong Jia]], [[https://openalex.org/A5101607979][Chunxiang Liu]], Physics of Fluids. 36(10)] 2024. https://doi.org/10.1063/5.0231372 
     
The caprock of coal-bearing strata plays a critical role in CO2 geological storage, with the presence of fractures posing a heightened risk of CO2 leakage. The cyclic effects of CO2 injection and in situ stress influence the permeability of caprock fractures. However, the combined impact of CO2 and in situ stress on fracture permeability remains uncertain. This study conducted cyclic seepage experiments under varying amplitude stresses on fractured sandstone samples soaked in ScCO2 for different times (0, 15, 30, and 60 days). The microstructural characteristics of the fractured sandstone surfaces were analyzed using scanning electron microscopy and x-ray diffraction. The experimental results indicated that soaking in ScCO2 reduces sandstone fracture permeability, but the extent of this reduction is nonlinearly related to the soaking time. During the stress cycling process, due to the effect of plastic deformation, the permeability of sandstone fractures decreases with increasing cyclic amplitude and remains relatively constant with decreasing cyclic amplitude. At the same cyclic amplitude, the permeability of sandstone fractures initially increases and then decreases with prolonged soaking time. The impact of ScCO2 and stress cycling on the permeability of sandstone fractures is the result of a series of combined chemical–mechanical effects. The combined effects of chemical dissolution and mechanical degradation significantly influence the permeability of sandstone fractures, and this impact is notably time-dependent. During short-term soaking, geochemically induced changes in the surface structure of fractures cause fluctuations in permeability, while in long-term soaking, the combined chemical–mechanical effects promote a reduction in fracture permeability.    

    

* ASSESSING THE POTENTIAL OF RAILWAYS TO REDUCE CO2 EMISSIONS: A COINTEGRATION STUDY OF ESTONIA'S TRANSPORT SECTOR  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403191312
:TOPICS: Estimating Vehicle Fuel Consumption and Emissions, Life Cycle Assessment and Environmental Impact Analysis, Impact of Railway Deregulation on Competition and Efficiency
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.62476/ge.23209")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403191312"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403191312"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403191312"))][Get cited by]]

OpenAlex: https://openalex.org/W4403191312 (Open access: True)
    
[[https://openalex.org/A5015904946][Zakariyya Abbasov]], No host. 2(3)] 2024. https://doi.org/10.62476/ge.23209 
     
This The transportation sector is a major contributor to CO2 emissions, playing a significant role in exacerbating climate change. Railways, known for their greater energy efficiency compared to other modes of transport, present a viable solution for mitigating emissions, particularly in countries like Estonia. In 2014, transport-related CO2 emissions in Estonia were recorded at 12.7%, marking an overall upward trend since 1995, despite experiencing some fluctuations over the years. This study aims to explore the long-term equilibrium relationship between CO2 emissions from transport and railway passenger kilometers in Estonia through the application of cointegration analysis. Utilizing Engle-Granger and Phillips-Ouliaris cointegration tests, the analysis reveals a stable, long-term equilibrium relationship between the two variables. The findings suggest that an increase in railway passenger kilometers could potentially lead to a reduction in CO2 emissions from transport. These results underscore the importance of enhancing railway infrastructure and usage as a strategic measure to curb transportation-related emissions and contribute to environmental sustainability.    

    

* Simultaneous seismic interpolation and statics estimation of land data  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403185372
:TOPICS: Seismic Waveform Inversion in Geophysics, Geological Modeling and Uncertainty Analysis, Artificial Intelligence and Expert Systems
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1190/geo2023-0668.1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403185372"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403185372"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403185372"))][Get cited by]]

OpenAlex: https://openalex.org/W4403185372 (Open access: False)
    
[[https://openalex.org/A5052804043][Ali M. Alfaraj]], [[https://openalex.org/A5004129653][D. J. Verschuur]], [[https://openalex.org/A5010780250][Felix J. Herrmann]], Geophysics. None(None)] 2024. https://doi.org/10.1190/geo2023-0668.1 
     
Imaging and inversion of land seismic data affected by complex weathering layers near the surface are challenging. When the data are additionally subsampled for economical reasons such as monitoring of sequestrated carbon dioxide and hydrogen, the problem is further exacerbated due to the combined influence of subsampling and weathering layers. On the one hand, interpolation performs poorly since the weathering layers reduce the data's coherency. On the other hand, near-surface corrections require knowledge of the subsurface model, separation between primaries and multiples as well as subsurface velocity estimation, which are difficult to perform from subsampled data. To overcome these hurdles, we combine seismic interpolation and statics estimation into a joint single rank-reduction-based algorithm. To our knowledge, this is the first time that this has been done. The proposed method simultaneously accounts for the weathering and subsampling effects, which both contribute to the low-rank structure destruction typically associated with statics-free densely-sampled data, to provide accurate reconstruction. Since a low-rank approximation is used for statics estimation, we also use it in rank-minimization interpolation as a cost-free initial solution to the optimization problem. As both statics estimation and interpolation operate in the midpoint-offset domain, we avoid the cost of transformations back and forth from the source-receiver to midpoint-offset transform domain. Consequently, the proposed reconstruction, which shows its potential on synthetic and field data is also computationally efficient.    

    

* The Synergistic Effect of the Carbon Emission Trading Scheme on Pollution and Carbon Reduction in China’s Power Industry  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403217171
:TOPICS: Economic Implications of Climate Change Policies, Life Cycle Assessment and Environmental Impact Analysis, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16198681")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403217171"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403217171"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403217171"))][Get cited by]]

OpenAlex: https://openalex.org/W4403217171 (Open access: True)
    
[[https://openalex.org/A5077973578][Xiling Zhang]], [[https://openalex.org/A5100683618][Xiaoqian Liu]], [[https://openalex.org/A5012609245][Zeyu Zhang]], [[https://openalex.org/A5030380172][Ruiyi Tang]], [[https://openalex.org/A5100458291][Ting Zhang]], [[https://openalex.org/A5090357240][Junqiang Yao]], Sustainability. 16(19)] 2024. https://doi.org/10.3390/su16198681 
     
The synergistic effect of pollution and carbon reduction can alleviate the dual pressure of improving environmental quality and reducing greenhouse gas emissions in China. The carbon emission trading scheme (CETS) is a crucial market-based tool for carbon emission reduction, and understanding its synergistic impact on air pollution control is essential. Based on data from 30 provincial panels in China spanning from 2007 to 2021, we employ the difference-in-differences (DID) method to analyze the synergistic effects of the carbon emission trading plan in the power industry and its influence mechanisms are examined. We observe that the CETS significantly enhances both pollution and carbon reduction in China’s power sector, particularly demonstrating effective synergy in reducing CO2, SO2, and PM2.5 emissions. Furthermore, mechanism analysis reveals that the CETS achieves joint emission reductions by lowering energy consumption, influencing the power industry’s generation structure, promoting technological innovation among enterprises, and thereby realizing synergistic pollution and carbon reduction effects in China’s power sector. Heterogeneity analysis shows that regions with limited power facility, low electricity generation, and small economic scale exhibit the most pronounced synergistic benefits from pollution and carbon reduction efforts.    

    

* Visible-Light Photoredox-Catalyzed Direct Carboxylation of Tertiary C(sp3)–H Bonds with CO2: Facile Synthesis of All-Carbon Quaternary Carboxylic Acids  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403172647
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Transition-Metal-Catalyzed C–H Bond Functionalization, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c09558")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403172647"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403172647"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403172647"))][Get cited by]]

OpenAlex: https://openalex.org/W4403172647 (Open access: False)
    
[[https://openalex.org/A5100330465][Yi Liu]], [[https://openalex.org/A5064328029][Gi Xue]], [[https://openalex.org/A5073240880][Zhen He]], [[https://openalex.org/A5011183265][Jun‐Ping Yue]], [[https://openalex.org/A5002702669][Min Pan]], [[https://openalex.org/A5013412917][Lei Song]], [[https://openalex.org/A5100441796][Wei Zhang]], [[https://openalex.org/A5059599037][Jian‐Heng Ye]], [[https://openalex.org/A5016358859][Da‐Gang Yu]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c09558 
     
Direct carboxylation of C–H bonds with CO2 represents an attractive strategy to synthesize valuable carboxylic acids with high atom, step, and redox economy. Although great progress has been achieved in this field, catalytic carboxylation of tertiary C(sp3)–H bonds still remains challenging due to their inherent inertness and significant steric hindrance. Herein, we report a direct carboxylation of tertiary benzylic C(sp3)–H bonds with CO2 via visible-light photoredox catalysis. Various all-carbon quaternary carboxylic acids, which are of significant importance in medicinal chemistry, are successfully obtained with high yields. This direct carboxylation is characterized by good functional group tolerance, broad substrate scope, and mild operational conditions. Furthermore, our methodology enables the efficient and rapid synthesis of key drug or bioactive molecules, such as carbetapentane, caramiphen, and PRE-084 (σ1 receptor agonist), and facilitates various functionalizations of C(sp2)–H bonds using the directing ability of target carboxylic acids, thus highlighting its practical applications. Mechanistic studies indicate that a carbanion, which serves as the key intermediate to react with CO2, is catalytically generated via a single electron reduction of a benzylic radical through a consecutive photoinduced electron transfer process.    

    

* Structural Reuse of Decommissioned Ski Lift Steel Trusses for Load-Bearing Applications  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403187287
:TOPICS: Impact of Road Salt on Freshwater Salinization, Mechanical Engineering and Optimization Techniques, Materials Science and Technology
:PUBLICATION_DATE: 2024-10-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/architecture4040044")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403187287"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403187287"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403187287"))][Get cited by]]

OpenAlex: https://openalex.org/W4403187287 (Open access: True)
    
[[https://openalex.org/A5107812154][Adrian Kiesel]], [[https://openalex.org/A5088592714][G Brandi]], [[https://openalex.org/A5107812155][Jael Schlatter]], [[https://openalex.org/A5049697232][Andri Gerber]], [[https://openalex.org/A5031598808][Silke Langenberg]], Architecture. 4(4)] 2024. https://doi.org/10.3390/architecture4040044 
     
The ongoing effects of climate change have led to a rise in global temperature, significantly reducing snow cover and resulting in the abandonment of numerous ski areas across Switzerland. As a result, many ski lifts have been decommissioned and left to deteriorate due to lenient local regulations. To address this issue, this paper presents a case study approach to repurposing steel trusses from abandoned ski lifts for a new structural application within the building industry. The design, sourcing, and construction of a new load-supporting column are described, focusing on reusing the ski lift steel trusses as a whole, without dismantling them into their components. After collection, these elements are adapted to comply with current building standards. By pouring out the hollow structure with the recently developed building material Cleancrete ©, a new load-bearing structure is developed. A comprehensive life cycle assessment (LCA) demonstrates the environmental performance of the steel–Cleancrete hybrid construction, which achieves a global warming potential (GWP) of 536.58 kg CO2-eq. In comparison, alternative designs using wood and concrete exhibited GWP values of 679.45 kg CO2-eq, +26.6%, and 1593.72 kg CO2-eq, +197.02%, respectively. These findings suggest that repurposing abandoned ski lift structures can significantly contribute to sustainable building practices, waste reduction, and the promotion of circular economy principles. The process outlined in this paper holds potential for future applications, particularly in the reuse of other steel components, ensuring continued circularity even as the supply of ski lift structures may dwindle.    

    

* The use of opioids in late‐stage COPD—Where are we now?  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403198556
:TOPICS: Standardisation and Management of COPD, Mechanical Ventilation in Respiratory Failure and ARDS, Pediatric Pain Assessment and Management
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/resp.14839")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403198556"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403198556"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403198556"))][Get cited by]]

OpenAlex: https://openalex.org/W4403198556 (Open access: True)
    
[[https://openalex.org/A5004506727][Thomas J. Altree]], [[https://openalex.org/A5007993808][David C. Currow]], Respirology. None(None)] 2024. https://doi.org/10.1111/resp.14839 
     
Chronic breathlessness is defined as breathlessness that persists on minimal or no exertion despite the optimal treatment of the underlying disease and other contributing factors.1 It is a cardinal and prevalent symptom of late-stage chronic obstructive pulmonary disease (COPD). Chronic breathlessness is present in about 40% of people with COPD in high-income countries, worsening with age and severity of disease. The majority of people with late-stage COPD experience such breathlessness. COPD is also associated with a high frequency of comorbidities.2 Common symptoms related to COPD and its systemic manifestations include, but are not limited to, long-term pain, sleep disturbance, fatigue and cough. This paper focuses on chronic breathlessness. In COPD at a population level, breathlessness is more strongly associated with mortality than the measurable degree of airway obstruction.3, 4 There is also a relatively poor correlation between pulmonary function tests and the subjective assessments of chronic breathlessness. Other population-level associations with chronic breathlessness include poorer quality of life (physical and mental components)5; greater anxiety and depression; poorer workforce participation in people of working age; greater disability measured on the World Health Organization Disability Assessment Schedule (WHO-DAS); poorer perceived health; less sexual activity; and a smaller Life-Space geographic footprint. In symptom management, the first step in managing chronic breathlessness requires clinicians to ensure that reversible causes are optimally treated. More than one underlying aetiology often contributes to chronic breathlessness and all need to be addressed in each person's management plan. Non-pharmacological interventions include pulmonary rehabilitation, activity pacing, and a handheld battery-operated fan.6 Despite these measures, many people still require pharmacotherapy for the symptom, especially in late-stage disease. Several medications have been assessed in adequately powered studies, yet the only class of medications, to date, which has an evidence base is opioids. There are two main sources to inform clinical considerations of effectiveness of opioids for the symptomatic reduction of chronic breathlessness: meta-analyses; and adequately powered studies. A sub-group analysis of people with COPD and breathlessness in a recent meta-analysis of opioids administered long enough to reach steady state (n = 91) found an overall benefit favouring morphine over placebo.7 This suggests that there is a cohort who likely derive meaningful symptomatic benefit. Since the publication of that study, three large randomized, placebo-controlled studies have been reported (n = 284; n = 156; n = 111).8-10 Each had differing primary endpoints at different times (intensity of worst breathlessness at 1 week,9 intensity of breathlessness now at 1 week),8 and COPD Assessment Test (CAT) scores and PaCO2 at 4 weeks.11 Breathlessness remained unchanged in all three studies, however, two of the three studies reported sub-group analyses that described sub-populations that derived significant benefit. The study by Verberkt et al. found two significant improvements in its secondary outcomes: worst breathlessness at 28 days after commencing the study; and a difference between the active and placebo arms for the CAT score. The study by Ferreira et al. identified that people with the most severe breathlessness (mMRC3, 4) and COPD achieved significant clinical benefit.12 Accurately identifying patient characteristics that predict a beneficial response to regular, low-dose, sustained-release morphine remains a challenge for researchers and clinicians. Basic clinico-demographic factors have been defined in two studies using data from double-blind, placebo-controlled, randomized controlled trials.13, 14 In the study by Johnson et al. from four clinical studies of morphine for the symptomatic reduction of breathlessness (n = 213), baseline predictors of a greater likelihood of response included more intense breathlessness and younger age.14 Body mass index (BMI) was not available in this study. In the study by Verberkt et al., 21 participants in the active arm of their parallel arm clinical trial had a ≥1 point improvement on a 0–10 numerical rating scale.13 The two baseline predictors of response were higher baseline intensity of breathlessness and higher BMI. Age was not a predictor in this study. To date, exploring key single nucleotide polymorphisms (SNPs) relating to opioid metabolism, transport or receptors has not found predictors of response.15 There appear to be a group of people (who are yet to be characterized from their pre-treatment characteristics) who have a marked benefit from regular, low-dose, sustained release morphine. The benefits are described by trial participants as 'life-changing' and persisted for at least 6 months with no increase in morphine dose.16 Although there are small numbers who describe benefits of this magnitude, the benefits were further reflected in improved actigraph-measured activity and increased Global Impression of Change scores. Opioids for pain have a wide therapeutic index. Morphine for the symptomatic reduction of chronic breathlessness may have a far narrower window for net benefit. Many people reflect that even mild adverse events negate any symptomatic reduction in chronic breathlessness.17 In a meta-analysis of 64 studies, of which five had data on safety measures, Verberkt et al. found no evidence of rising carbon dioxide partial pressures nor of any drop in oxygenation—two principal concerns when prescribing opioids for people with COPD.11 A pre-planned secondary analysis of the BEAMS study found that daytime drowsiness was no worse in the morphine arm than placebo and that, at 4 weeks, participants who reported reduced breathlessness with morphine also had improvement in Leeds Sleep Evaluation Questionnaire (LSEQ) domain scores including perceived sleep quality and daytime functioning.18 However, objective assessment of the effects of low-dose, slow-release morphine during sleep in people with COPD and chronic breathlessness has identified that although there is no negative effect on next-day alertness (including driving simulator performance), morphine causes lighter sleep depth, higher mean and peak transcutaneous CO2 and lower oxygen saturations.18, 19 The longer-term consequences of these changes are yet to be determined. Of note, any therapeutic benefit does not seem to have a whole-of-class effect for opioids. Studies utilizing oxycodone do not seem to have any signal of symptomatic benefit. Interestingly, it may also be that not all underlying aetiologies of chronic breathlessness derive the same benefits. One study in pulmonary artery hypertension saw no signal of benefit in the primary nor secondary outcomes and another in interstitial lung disease.20 At present, data from a meta-analysis and two large, randomized, controlled studies indicate that in people with severe chronic breathlessness secondary to COPD, a short trial of low dose, sustained release morphine is safe and potentially beneficial. When introduced at a low dose and titrated slowly (at least 1 week between commencing and titration), a sub-group of people derive significant, sometimes life-changing, benefit. Developing accurate methods to identify which patients derive benefit from regular, low-dose, sustained-release morphine is a critical goal for future research. T.J.A. had no disclosures. D.C.C. is an Advisory Board member and consultant for Helsinn Pharmaceuticals; consultant and receives payment for intellectual property with Mayne Pharma International Pty Ltd.; subcontractor to Nous Group Pty Ltd.; Board member for icare Dust Diseases Care NSW; Board member/Director NSW Health Pathology; Board member/Director for Chris O'Brien Lifehouse Cancer Centre.    

    

* Phenotypic and Genomic Characterization of a Sulfate-Reducing Bacterium Pseudodesulfovibrio methanolicus sp. nov. Isolated from a Petroleum Reservoir in Russia  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403190838
:TOPICS: RNA Sequencing Data Analysis, Marine Microbial Diversity and Biogeography, Characterization of Shale Gas Pore Structure
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/biology13100800")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403190838"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403190838"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403190838"))][Get cited by]]

OpenAlex: https://openalex.org/W4403190838 (Open access: True)
    
[[https://openalex.org/A5061505570][Salimat K. Bidzhieva]], [[https://openalex.org/A5038456926][T. P. Tourova]], [[https://openalex.org/A5057798090][Vitaly V. Kadnikov]], [[https://openalex.org/A5107813491][Salima R. Samigullina]], [[https://openalex.org/A5042872987][Alexander S. Shashkov]], [[https://openalex.org/A5081915057][А. Б. Полтараус]], [[https://openalex.org/A5029892927][Alexander N. Avtukh]], [[https://openalex.org/A5062690616][В. М. Терешина]], [[https://openalex.org/A5040498376][Alexey V. Beletsky]], [[https://openalex.org/A5037079734][Andrey V. Mardanov]], [[https://openalex.org/A5069507974][Tamara N. Nazina]], Biology. 13(10)] 2024. https://doi.org/10.3390/biology13100800 
     
The search for the microorganisms responsible for sulfide formation and corrosion of steel equipment in the oil fields of Tatarstan (Russia) resulted in the isolation of a new halotolerant strictly anaerobic sulfate-reducing bacterium, strain 5S69T. The cells were motile curved Gram-negative rods. Optimal growth was observed in the presence of 2.0–4.0% (w/v) NaCl, at pH 6.5, and at 23–28 °C under sulfate-reducing conditions. The isolate was capable of chemoorganotrophic growth with sulfate and other sulfoxides as electron acceptors, resulting in sulfide formation; and of pyruvate fermentation resulting in formation of H2 and acetate. The strain utilized lactate, pyruvate, ethanol, methanol, fumarate, and fructose, as well as H2/CO2/acetate for sulfate reduction. The genome size of the type strain 5S69T was 4.16 Mb with a G + C content of 63.0 mol%. On the basis of unique physiological properties and results of the 16S rRNA gene-based phylogenetic analysis, phylogenomic analysis of the 120 conserved single copy proteins and genomic indexes (ANI, AAI, and dDDH), assigning the type strain 5S69T ((VKM B-3653T = KCTC 25499T) to a new species within the genus Pseudodesulfovibrio, is suggested, with the proposed name Pseudodesulfovibrio methanolicus sp. nov. Genome analysis of the new isolate showed several genes involved in sulfate reduction and its sulfide-producing potential in oil fields with high saline formation water.    

    

* Vibration reduction of an electric vehicle heat exchanger by controlling the polarization of its ferroelectric ceramics  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403266565
:TOPICS: Materials Science and Technology, Hydraulic Systems Control and Optimization, Mechanical Engineering and Optimization Techniques
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3397/in_2024_3673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403266565"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403266565"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403266565"))][Get cited by]]

OpenAlex: https://openalex.org/W4403266565 (Open access: False)
    
[[https://openalex.org/A5101627809][L. Maurin]], [[https://openalex.org/A5012482831][Thomas Durand-Texte]], [[https://openalex.org/A5031384718][Sébastien Goudé]], [[https://openalex.org/A5107479736][Charlie Bricault]], [[https://openalex.org/A5089943802][Adrien Pelat]], [[https://openalex.org/A5009496516][François Gautier]], NOISE-CON proceedings. 270(5)] 2024. https://doi.org/10.3397/in_2024_3673 
     
The growing requirements in terms of CO2 emissions reduction in transports renders necessary the development of new electric traction technologies. This results in new technical constraints for equipment manufacturers, forcing them to reduce the acoustic emissivity of their new products inside and outside vehicles. Heat exchangers for electric cars are part of this new product category. High voltage supplied by the battery of electrical vehicles requires introduction of a new energy conversion process and technology. To this end, components based on ceramics containing barium titanate (BaTiO3) with high electrocaloric coupling properties are selected to provide the heating function. Baryum titanate is ferroelectric. This category of materials is subjected to piezoelectric and electrostrictive effects. The vibrations induced in the components (rods) containing the BaTiO3 ceramics are transmitted through the system, and cause undesired acoustic radiation. This coupling is a suffered effect and is not taken into account in the integration process during the rods manufacturing. In this study, an experimental characterization is proposed to identify the involved electromechanical coupling coefficients. Numerical simulations of the vibrations induced by BaTiO3 are carried out and used to study the possibility of attenuating them by controlling the polarisation of the ceramics or by geometric modifications.    

    

* Fine-tuning syngas composition using laser surface modified silver electrode for CO2 electroreduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403218032
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2351/7.0001542")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403218032"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403218032"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403218032"))][Get cited by]]

OpenAlex: https://openalex.org/W4403218032 (Open access: False)
    
[[https://openalex.org/A5036503837][Austin McKee]], [[https://openalex.org/A5009794335][Wuji Huang]], [[https://openalex.org/A5056553738][Ninggang Shen]], [[https://openalex.org/A5102911514][Syed Mubeen]], [[https://openalex.org/A5031341048][Hongtao Ding]], Journal of Laser Applications. 36(4)] 2024. https://doi.org/10.2351/7.0001542 
     
Electrochemical reduction of CO2 and H2O to synthesize gas (H2 and CO mixture) is of significant interest due to established industrial pathways to tune the H2 to CO composition to generate an array of valuable products including methanol, synthetic fuel, synthetic natural gas, and hydrogen. However, controlled H2:CO ratios are challenging on CO-active electrocatalysts like silver. We demonstrate that applying laser engineering to adjust the surface wetting state of a silver electrocatalyst with water contact angles θw ranging from 47° and 135°, H2:CO ratios can be tuned from 1 to 4 at modest potentials (−0.7 V versus RHE, RHE—reversible hydrogen electrode) with almost total unity Faradaic efficiency. Both hydrophilic (θw = 47°) and more hydrophobic (θw = 135°) samples showed an increasing H2:CO trend with rising potentials (0.7–1.2 V versus RHE) due to mass transport. Conversely, silver electrocatalyst with θw = 110° exhibited a constant H2:CO ratio of 4. This indicates catalyst wettability potentially affects *H and *HOCO intermediates’ adsorption, impacting H2:CO ratios. Our results show the feasibility of syngas composition control on silver catalysts via surface wettability, providing a simpler alternative to complex multicomponent electrocatalytic systems.    

    

* Decarbonizing European Industry: A Novel Technology to Heat Supply Using Waste and Renewable Energy  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403189632
:TOPICS: Waste Heat Recovery for Power Generation and Cogeneration, Integration of Renewable Energy Systems in Power Grids, Global Energy Transition and Fossil Fuel Depletion
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/app14198994")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403189632"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403189632"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403189632"))][Get cited by]]

OpenAlex: https://openalex.org/W4403189632 (Open access: True)
    
[[https://openalex.org/A5060601412][J.D. Marcos]], [[https://openalex.org/A5107620561][Iman Golpour]], [[https://openalex.org/A5012213740][Rubén Barbero]], [[https://openalex.org/A5052272257][Antonio Rovira]], Applied Sciences. 14(19)] 2024. https://doi.org/10.3390/app14198994  ([[https://www.mdpi.com/2076-3417/14/19/8994/pdf?version=1728188464][pdf]])
     
This study examines the potential for the smart integration of waste and renewable energy sources to supply industrial heat at temperatures between 150 °C and 250 °C, aiming to decarbonize heat demand in European industry. This work is part of a European project (SUSHEAT) which focuses on developing a novel technology that integrates several innovative components: a Stirling cycle high-temperature heat pump (HTHP), a bio-inspired phase change material (PCM) thermal energy storage (TES) system, and a control and integration twin (CIT) system based on smart decision-making algorithms. The objective is to develop highly efficient industrial heat upgrading systems for industrial applications using renewable energy sources and waste heat recovery. To achieve this, the specific heat requirements of different European industries were analyzed. The findings indicate that industrial sectors such as food and beverages, plastics, desalination, textiles, ceramics, pulp and paper, wood products, canned food, agricultural products, mining, and chemicals, typically require process heat at temperatures below 250 °C under conditions well within the range of the SUSHEAT system. Moreover, two case studies, namely the Pelagia and Mandrekas companies, were conducted to validate the effectiveness of the system. An analysis of the annual European heat demand by sector and temperature demonstrated that the theoretical potential heat demand that could be met by the SUSHEAT system is 134.92 TWh annually. Furthermore, an environmental impact assessment estimated an annual significant reduction of 19.40 million tonnes of CO2 emissions. These findings underscore the significant potential of the SUSHEAT system to contribute to the decarbonization of European industry by efficiently meeting heat demand and substantially reducing carbon emissions.    

    

* Synthesis, Characterization, and Shaping of UiO-67 Metal-Organic Frameworks  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403222099
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Zeolite Chemistry and Catalysis, Powder Diffraction Analysis
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.33540/2439")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403222099"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403222099"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403222099"))][Get cited by]]

OpenAlex: https://openalex.org/W4403222099 (Open access: False)
    
[[https://openalex.org/A5063599600][Christia Jabbour]], No host. None(None)] 2024. https://doi.org/10.33540/2439 
     
This PhD thesis investigates the flexibility of metal-organic frameworks (MOFs) materials, particularly focusing on their adaptable synthesis and shaping techniques. MOFs, known for their dynamic framework structures and flexible linkers, allow researchers to design new and existing porous materials for specific applications, such as catalysis and environmental protection. The research covers a range of topics, including synthesis, characterization, shaping, and catalytic testing, with particular emphasis on the flexible properties of MOFs. Chapter 2 focuses on the application of MOFs in active coatings on surfaces and functionalized fabrics to deactivate biological and chemical toxins, a crucial topic in light of the global health crisis induced by the SARS-CoV-2 outbreak. The chapter discusses advancements in metal- and metal-oxide-based catalysts for inactivating chemical and biological threats. It also explores MOF applications in textiles, which are designed to capture and degrade chemical warfare agents. Despite progress, challenges remain, particularly in translating laboratory results to real-world conditions, such as creating multifunctional protective suits that are durable and capable of detoxifying toxins while remaining comfortable. The chapter highlights the promise of MOFs in addressing these challenges, but also the need for improved manipulation onto fibers and long-term stability. Chapters 3, 4, and 5 delve into the catalytic potential of MOFs and their manipulation for specific applications. In Chapter 3, the focus is on the catalytic activity of platinum nanoparticles (Pt-NPs) embedded within the UiO-67 MOF structure, specifically investigating their role in the CO2 hydrogenation reaction. The study examines the effects of reduction and pyrolysis treatments on Pt-NPs, finding that certain treatment processes improve the selectivity for methanol formation. This chapter emphasizes the importance of understanding the catalytic properties of MOFs and their potential for CO2 conversion. Chapter 4 investigates surface-mounted MOFs (SURMOFs), which offer promising in situ measurement capabilities. The chapter discusses the synthesis and characterization of three different SURMOF materials: UU-1, ZIF-8, and UiO-67. It explores how different anchor molecules, substrates, and synthetic conditions affect the growth and morphology of these SURMOFs. The chapter also addresses the limitations of current analytical techniques and proposes transmission-based characterization on transparent substrates. The findings highlight the importance of spectroscopic characterization in understanding the behavior of SURMOFs during various processes, offering insights for their application in fields like sensing, separation, and catalysis. Finally, Chapter 5 addresses the challenge of shaping MOFs via mechanical pressure by presenting a synthesis procedure that forms MOF beads through entanglement with chitosan (CS). This method eliminates the need for mechanical pressure, which can be detrimental to MOF structures. The study compares two synthesis procedures—one-pot synthesis (OPS) and post-synthetic functionalization (PSF)—and finds that OPS leads to better incorporation of MOFs into CS beads, resulting in higher thermal stability. Overall, this thesis demonstrates the versatility of MOFs in catalysis, environmental protection, and material science, while also addressing the challenges associated with shaping and long-term stability.    

    

* 12201 Ketogenic-diet As A Trigger Of First Episode Diabetic Ketoacidosis In A Woman Living With Type 1 Diabetes Mellitus  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4403153887
:TOPICS: Effects of Ketogenic Diet on Health, Brown Adipose Tissue Function and Physiology, Genetics and Pathogenesis of Type 1 Diabetes
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1210/jendso/bvae163.826")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403153887"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403153887"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403153887"))][Get cited by]]

OpenAlex: https://openalex.org/W4403153887 (Open access: True)
    
[[https://openalex.org/A5060989480][Margarida Cruz]], [[https://openalex.org/A5022612153][Alex N Gonzalez Bossolo]], [[https://openalex.org/A5030452799][Gabriel Jose Mora Osoria]], Journal of the Endocrine Society. 8(Supplement_1)] 2024. https://doi.org/10.1210/jendso/bvae163.826 
     
Abstract Disclosure: M.E. Chacon Cruz: None. A.N. Gonzalez Bossolo: None. G.J. Mora Osoria: None. A number of dietary patterns have been proposed as an effective method for weight reduction. A keto diet is a strict low-carbohydrate and high-fat diet. The reduction in carbohydrates enables the body to rely on fat as a predominant energy source leading to a state of ketosis. However, a serious but rare complication of the ketogenic diet is ketoacidosis associated with low carbohydrate intake, which should be cautiously monitored in people with a predisposition to the condition, such patient with diabetes mellitus type 1. We report the case of a female patient living with type 1 diabetes mellitus female who developed her first episodes of diabetic ketoacidosis (DKA) as the following the course of ketogenic diet. A 53 y/o Female patient with past medical history diabetes mellitus type 1 and pernicious anemia went emergency department complaining pelvic pain associated with weakness, nausea and vomiting for about 1 day of evolution. Patient also refers that during the past 2 weeks she has been doing a detox and taking some herbal and tea. Other physical examinations were unremarkable except for moderate dehydration. The initial testing revealed patients meet criteria for severe diabetes ketoacidosis (DKA) with a pH: 7.04, CO2 15, serum central bicarbonate in 6 mmol/L and elevated blood glucose in 504 mg/dl and positive urine and serum ketones, C-Peptide less than 0.02 ng/ml. and glycosylated hemoglobin in 8.25%. She was admitted to the intensive care unit and treated with intravenous saline, intravenous insulin infusion, and electrolyte repletion. Blood glucose levels and metabolic acidosis improved. After DKA resolved patient refers that week started with Keto-diet and was restricting carbohydrates. Patient was discharge home with multiple injection insulin and followed by Endocrinologist services in the external clinic for a follow up. This case illustrates the challenges and the importance of dietary history providing clues to the diagnosis. If we had never asked her about her diet, we would not have found the reason that brought her to the DKA. This case demonstrates the development of DKA following ketogenic diet in a patient with type 1 diabetes. It is important for physicians to be aware of this rare potential complication of ketogenic diet which is infrequently reported in literature. Therefore, physicians should be cognizant of the complications and risks, and benefits of the ketogenic diet. Risks and benefits of the ketogenic diet should be discussed with patients before initiation of this diet. The patient was followed in an outpatient clinic with Endocrinologist service for evaluation for an insulin pump. Presentation: 6/1/2024    

    
