#+TITLE: CO2RR
Description: Electrochemical reduction of carbon dioxide
Created on Mon Mar  4 00:44:12 2024

Found 29 results from 2024-02-26 to 2024-03-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C24596552]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%28%28carbon%20dioxide%20reduction%29%20OR%20%28co2%20reduction%29%29%20NOT%20%28photocatalysis%20OR%20photocatalytic%29]]

* Improved photocatalytic carbon dioxide reduction over Bi-doped CeO2 by strain engineering  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392183084
:TOPICS: Catalytic Nanomaterials, Gas Sensing Technology and Materials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3se01680c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392183084"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392183084"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392183084"))][Get cited by]]

OpenAlex: https://openalex.org/W4392183084 (Open access: True)
    
[[https://openalex.org/A5034439957][Chuangwei Liu]], [[https://openalex.org/A5024475563][Ang Tian]], [[https://openalex.org/A5083791713][Zi Mei]], [[https://openalex.org/A5069897736][Luyuan Wang]], [[https://openalex.org/A5042704924][Guangliang Liu]], [[https://openalex.org/A5018083882][Zhiguo Liu]], [[https://openalex.org/A5044797761][Guangming Kong]], [[https://openalex.org/A5028023634][Wenjun Tang]], Sustainable Energy and Fuels. None(None)] 2024. https://doi.org/10.1039/d3se01680c  ([[https://pubs.rsc.org/en/content/articlepdf/2024/se/d3se01680c][pdf]])
     
Room-temperature photocatalytic carbon dioxide reduction reaction (CRR) is an essential method for reducing carbon footprint and achieving valuable fuels. The key challenge to accelerate the process is enhancing the catalytic...    

    

* Reversible Carbon Dioxide/Lithium Oxalate Regulation toward Advanced Aprotic Lithium Carbon Dioxide Battery  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392194463
:TOPICS: Lithium-ion Battery Management in Electric Vehicles, Lithium Battery Technologies, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202400132")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392194463"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392194463"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392194463"))][Get cited by]]

OpenAlex: https://openalex.org/W4392194463 (Open access: False)
    
[[https://openalex.org/A5010294985][Yifeng Wang]], [[https://openalex.org/A5022632473][Lina Song]], [[https://openalex.org/A5005491214][Zheng Luo]], [[https://openalex.org/A5062755510][Qianqian Wang]], [[https://openalex.org/A5033359034][Jiayi Wu]], [[https://openalex.org/A5090414406][Ji‐Jing Xu]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202400132 
     
Li–CO2 batteries have received significant attention owing to their advantages of combining greenhouse gas utilization and energy storage. However, the high kinetic barrier between gaseous CO2 and the Li2CO3 product leads to a low operating voltage (<2.5 V) and poor energy efficiency. In addition, the reversibility of Li2CO3 has always been questioned owing to the introduction of more decomposition paths caused by its higher charging plateau. Here, a novel "trinity" Li–CO2 battery system was developed by synergizing CO2, soluble redox mediator (2,2,6,6‐tetramethylpiperidoxyl, as TEM RM), and reduced graphene oxide electrode to enable selective conversion of CO2 to Li2C2O4. The designed Li–CO2 battery exhibited an output plateau reaching up to 2.97 V, higher than the equilibrium potential of 2.80 V for Li2CO3, and an ultrahigh round‐trip efficiency of 97.1%. The superior performance of Li–CO2 batteries is attributed to the TEM RM‐mediated preferential growth mechanism of Li2C2O4, which enhances the reaction kinetics and rechargeability. Such a unique design enables batteries to cope with sudden CO2‐deficient environments, which provides an avenue for the rationally design of CO2 conversion reactions and a feasible guide for next‐generation Li–CO2 batteries.    

    

* Construction of a Novel Ternary Gqds/G-C3n4/Zif-67 Photocatalyst for Enhanced Photocatalytic Carbon Dioxide Reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392195836
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4739858")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392195836"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392195836"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392195836"))][Get cited by]]

OpenAlex: https://openalex.org/W4392195836 (Open access: False)
    
[[https://openalex.org/A5073117733][Zhiyuan Zhao]], [[https://openalex.org/A5067221645][Jingjing Wang]], [[https://openalex.org/A5000133042][Cheng‐Yan Xu]], [[https://openalex.org/A5025266207][Zhao Du]], [[https://openalex.org/A5053332787][Rongrong Yu]], [[https://openalex.org/A5053863018][Yongjun Zhao]], [[https://openalex.org/A5044820789][Jishu Han]], [[https://openalex.org/A5034422124][Jian‐Min Zuo]], [[https://openalex.org/A5069736534][Zhonglu Guo]], [[https://openalex.org/A5022913125][Chengchun Tang]], [[https://openalex.org/A5054091259][Yi Fang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4739858 
     
No abstract    

    

* Reversible Carbon Dioxide/Lithium Oxalate Regulation toward Advanced Aprotic Lithium Carbon Dioxide Battery  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392197079
:TOPICS: Lithium-ion Battery Management in Electric Vehicles, Lithium Battery Technologies, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202400132")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392197079"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392197079"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392197079"))][Get cited by]]

OpenAlex: https://openalex.org/W4392197079 (Open access: False)
    
[[https://openalex.org/A5010294985][Yifeng Wang]], [[https://openalex.org/A5022632473][Lina Song]], [[https://openalex.org/A5005491214][Zheng Luo]], [[https://openalex.org/A5062755510][Qianqian Wang]], [[https://openalex.org/A5033359034][Jiayi Wu]], [[https://openalex.org/A5090414406][Ji‐Jing Xu]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202400132 
     
Li–CO2 batteries have received significant attention owing to their advantages of combining greenhouse gas utilization and energy storage. However, the high kinetic barrier between gaseous CO2 and the Li2CO3 product leads to a low operating voltage (<2.5 V) and poor energy efficiency. In addition, the reversibility of Li2CO3 has always been questioned owing to the introduction of more decomposition paths caused by its higher charging plateau. Here, a novel "trinity" Li–CO2 battery system was developed by synergizing CO2, soluble redox mediator (2,2,6,6‐tetramethylpiperidoxyl, as TEM RM), and reduced graphene oxide electrode to enable selective conversion of CO2 to Li2C2O4. The designed Li–CO2 battery exhibited an output plateau reaching up to 2.97 V, higher than the equilibrium potential of 2.80 V for Li2CO3, and an ultrahigh round‐trip efficiency of 97.1%. The superior performance of Li–CO2 batteries is attributed to the TEM RM‐mediated preferential growth mechanism of Li2C2O4, which enhances the reaction kinetics and rechargeability. Such a unique design enables batteries to cope with sudden CO2‐deficient environments, which provides an avenue for the rationally design of CO2 conversion reactions and a feasible guide for next‐generation Li–CO2 batteries.    

    

* Gallium-introduced bimetal sites in indium-gallium metal organic framework for efficient electrocatalytic reduction of carbon dioxide into formate  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392206085
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Gas Sensing Technology and Materials, Thermoelectric Materials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00270a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392206085"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392206085"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392206085"))][Get cited by]]

OpenAlex: https://openalex.org/W4392206085 (Open access: False)
    
[[https://openalex.org/A5013702705][Yang Gao]], [[https://openalex.org/A5086758549][Xiaohong He]], [[https://openalex.org/A5002351852][Xiaofang Ma]], [[https://openalex.org/A5010151034][Zhizhu Yue]], [[https://openalex.org/A5044042136][Chunmei Liu]], [[https://openalex.org/A5050474574][Ming‐Chun Zhao]], [[https://openalex.org/A5066716873][Li Zhang]], [[https://openalex.org/A5014506158][Junming Zhang]], [[https://openalex.org/A5081184014][Ergui Luo]], [[https://openalex.org/A5017441697][Tianjun Hu]], [[https://openalex.org/A5087770639][Baoliang Lv]], [[https://openalex.org/A5089859351][Jianfeng Jia]], [[https://openalex.org/A5062029799][Hai‐Shun Wu]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d4ta00270a 
     
In-based catalysts offer an attractive approach for electrocatalytic reduction of CO2 (eCO2RR) into formate. However, precisely controlling the adsorption of competitive intermediates (*COOH and *OCHO) on In-based catalysts remains a...    

    

* Study on the Inhibition of Hydrogen Evolution Reaction by Electrocatalytic Reduction of Carbon Dioxide Using Elsholtzia Harchowensis Biochar  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392193663
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14030172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392193663"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392193663"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392193663"))][Get cited by]]

OpenAlex: https://openalex.org/W4392193663 (Open access: True)
    
[[https://openalex.org/A5071037763][Wei Liu]], [[https://openalex.org/A5014829857][Shiqi Chen]], [[https://openalex.org/A5026300483][Z. Mei]], [[https://openalex.org/A5064564309][Liang Li]], [[https://openalex.org/A5034500479][Hong Tao]], Catalysts. 14(3)] 2024. https://doi.org/10.3390/catal14030172  ([[https://www.mdpi.com/2073-4344/14/3/172/pdf?version=1709014662][pdf]])
     
With the widespread application of plant remediation technology in the field of soil remediation, there was an increasing stock of hyperaccumulating plant tissues containing heavy metals, but there was currently a lack of effective disposal methods. In the preliminary research process, researchers used the copper hyperaccumulating plant Elsholtzia Harchowensis to prepare biochar material electrodes and successfully used them in the electrocatalytic reduction of carbon dioxide (CO2) process. Due to the previous research being conducted in aqueous solutions, the hydrogen evolution reaction (HER) on the working electrode surface has a certain impact on the Faraday efficiency (FE) of carbon-containing products. In order to further improve the electrocatalytic reduction performance of biochar materials, this study was based on B- and N-doped biochar prepared from Elsholtzia Harchowensis as raw material. The influence mechanisms of electrode surface hydrophobicity and electrolyte components (PC/water) on the CO2RR and HER were studied, respectively. After dropwise coating PTFE on the surface of Cu/C-BN material, the hydrophobicity of Cu/C-BN-PT material was improved, and the effect on the active sites of the catalyst was relatively small without changing the structure and elemental characteristics of the original electrode. In a 1.0 M KHCO3 solution, the Faraday efficiency of H2 in Cu/C-BN-PT material decreased by 20.1% compared to Cu/C-BN at −0.32 V (vs. RHE), indicating that changing the hydrophilicity of the material can significantly inhibit the HER. In a solution of PC/water at a ratio of 9:1 (V:V), the FE of converting CO2 to methane (CH4) at −0.32 V (vs. RHE) reached 12.0%, and the FE of carbon monoxide (CO) reached 64.7%. The HER was significantly inhibited, significantly improving the selectivity of electrocatalytic CO2.    

    

* Customizing catalyst surface/interface structures for electrochemical CO2 reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392192493
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3sc06990g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392192493"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392192493"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392192493"))][Get cited by]]

OpenAlex: https://openalex.org/W4392192493 (Open access: True)
    
[[https://openalex.org/A5006282859][Xin Tan]], [[https://openalex.org/A5022155493][Hesun Zhu]], [[https://openalex.org/A5000026480][Chunnian He]], [[https://openalex.org/A5089567081][Zewen Zhuang]], [[https://openalex.org/A5028017378][Kaian Sun]], [[https://openalex.org/A5089966579][Chao Zhang]], [[https://openalex.org/A5059034640][Chen Chen]], Chemical Science. None(None)] 2024. https://doi.org/10.1039/d3sc06990g  ([[https://pubs.rsc.org/en/content/articlepdf/2024/sc/d3sc06990g][pdf]])
     
Electrochemical CO2 reduction reaction (CO2RR) provides a promising route to converting CO2 into value-added chemicals and to neutralizing the greenhouse gas emission. For the industrial application of CO2RR, high-performance electrocatalysts...    

    

* Engineering hydrophobicity and high-index planes of gold nanostructures for highly selective electrochemical CO2 reduction to CO and efficient CO2 capture  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392184761
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Molecular Electronic Devices and Systems, Thermoelectric Materials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150045")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392184761"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392184761"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392184761"))][Get cited by]]

OpenAlex: https://openalex.org/W4392184761 (Open access: False)
    
[[https://openalex.org/A5000421485][Taehui Kwon]], [[https://openalex.org/A5069304290][Sampath Prabhakaran]], [[https://openalex.org/A5022726594][Do Hwan Kim]], [[https://openalex.org/A5016111739][Myung Hwa Kim]], [[https://openalex.org/A5000491334][Youngmi Lee]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150045 
     
In current study, we demonstrate a strategy for improving the catalytic performance of gold (Au) for carbon monoxide reduction reaction (CO2RR), specifically enhancing selectivity for CO over hydrogen reduction reaction (HER) and increasing low-level CO2 capture efficiency. This involved controlling nanostructures without any further modification. Au nanostructures having four different morphologies (i.e., degree of roughness) were fabricated via electrodeposition at varied deposition potential, resulting in different intrinsic surface hydrophobicity and exposure of high-index planes depending on the actual morphology. The roughest Au, with its combination of the most hydrophobic feature and abundant high-index planes, generated greater current density (jCO) and faradaic efficiency for CO (FECO) than the other Au deposits within a tested potential region: The roughest Au showed 6-fold higher FECO (95.8 %) and 327-fold higher jCO (normalized to electrode geometric surface area) at −0.75 VRHE compared to the smoothest Au. Moreover, the roughest Au exhibited excellent CO2 capture ability even at low CO2 concentration, confirmed with scanning electrochemical microscopy. These improvement at hierarchical Au for CO2RR could be ascribed to two factors. Firstly, the morphology-driven hydrophobicity provides an optimal gas–liquid-solid triple-phase interfaces, increasing the local CO2 concentration near the Au catalyst surface due to its superb CO2 capture ability. Secondly, the abundant high index plane serves as stable active sites for CO2RR, expediting the reaction rates. Remarkably, Au with the highest hydrophobicity and enriched high-index planes, even without any chemical modification, showed excellent CO2RR catalytic performance comparable to or even better than the other previously reported Au-based catalysts.    

    

* Tailoring Hydrophobicity of Cuo Electrodes to Boost the Electrochemical Reduction of Co2 to Ethylene  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392205016
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4739940")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392205016"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392205016"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392205016"))][Get cited by]]

OpenAlex: https://openalex.org/W4392205016 (Open access: False)
    
[[https://openalex.org/A5045896637][Quhan Chen]], [[https://openalex.org/A5005274186][Hongqing Zhu]], [[https://openalex.org/A5052043342][Zhiqiang Guo]], [[https://openalex.org/A5085330395][Zijun Yan]], [[https://openalex.org/A5081592461][Gang Yang]], [[https://openalex.org/A5042425447][Yan‐Song Zheng]], [[https://openalex.org/A5010797894][Yalan Xing]], [[https://openalex.org/A5015880241][Hongfeng Yin]], [[https://openalex.org/A5043731569][Tom Wu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4739940 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Molecular engineering binuclear copper catalysts for selective CO2 reduction to C2 products  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392183682
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.01.060")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392183682"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392183682"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392183682"))][Get cited by]]

OpenAlex: https://openalex.org/W4392183682 (Open access: True)
    
[[https://openalex.org/A5007791083][Qi Zhao]], [[https://openalex.org/A5030901999][Kin Fong Lei]], [[https://openalex.org/A5044579750][Bao Yu Xia]], [[https://openalex.org/A5066970784][Rachel Crespo‐Otero]], [[https://openalex.org/A5076994358][Devis Di Tommaso]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.01.060 
     
No abstract    

    

* Theoretical investigation of the adsorbate and potential‐induced stability of Cu facets during electrochemical CO2 and CO reduction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392196163
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cphc.202300959")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392196163"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392196163"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392196163"))][Get cited by]]

OpenAlex: https://openalex.org/W4392196163 (Open access: False)
    
[[https://openalex.org/A5038619483][Hong Yu]], [[https://openalex.org/A5023895763][Nitish Govindarajan]], [[https://openalex.org/A5062728883][Stephen E. Weitzner]], [[https://openalex.org/A5076554343][Rui Serra-Maia]], [[https://openalex.org/A5042139840][Sneha A. Akhade]], [[https://openalex.org/A5089128933][Joel B. Varley]], ChemPhysChem. None(None)] 2024. https://doi.org/10.1002/cphc.202300959 
     
The activity and product selectivity of electrocatalysts for reactions like the carbon dioxide reduction reaction (CO2RR) are intimately dependent on the catalyst’s structure and composition. While engineering catalytic surfaces can improve performance, discovering the key sets of rational design principles remains challenging due to limitations in modeling catalyst stability under operating conditions. Herein, we perform first‐principles density functional calculations adopting implicit solvation methods with potential control to study the influence of adsorbates and applied potential on the stability of different facets of model Cu electrocatalysts. Using coverage dependencies extracted from microkinetic models, we describe an approach for calculating potential and adsorbate‐dependent contributions to surface energies under reaction conditions, where Wulff constructions are used to understand the morphological evolution of Cu electrocatalysts under CO2RR conditions. We identify that CO*, a key reaction intermediate, exhibits higher kinetically and thermodynamically accessible coverages on (100) relative to (111) facets, which can translate into an increased relative stabilization of the (100) facet during CO2RR. Our results support the known tendency for increased (111) faceting of Cu nanoparticles under more reducing conditions and that the relative increase in (100) faceting observed under CO2RR conditions is likely attributed to differences in CO* coverage between these facets.    

    

* Electrocatalytic Reduction of Co2 by Co-Cu Metastable Alloy Nanoparticles Derived from Mofs  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392204954
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4739957")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392204954"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392204954"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392204954"))][Get cited by]]

OpenAlex: https://openalex.org/W4392204954 (Open access: False)
    
[[https://openalex.org/A5049863539][Chaoyun Song]], [[https://openalex.org/A5036203577][Xiao Renshaw Wang]], [[https://openalex.org/A5040394808][Guanqing Song]], [[https://openalex.org/A5054405538][Gansheng Shi]], [[https://openalex.org/A5003642180][Yan Wang]], [[https://openalex.org/A5091161566][Jiajun Yu]], [[https://openalex.org/A5016028983][Xiaofeng Xie]], [[https://openalex.org/A5068911982][Jun Sun]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4739957 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Structure Activity Relationships for Second‐Coordination Sphere Functional Group Dependent CO2 Reduction by Manganese Bipyridyl Electrocatalysts  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392153815
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Carbon Dioxide Utilization for Chemical Synthesis
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301388")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392153815"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392153815"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392153815"))][Get cited by]]

OpenAlex: https://openalex.org/W4392153815 (Open access: False)
    
[[https://openalex.org/A5037174383][Vanna Blasczak]], [[https://openalex.org/A5063180325][Allan Murphy]], [[https://openalex.org/A5080235951][Lisa Suntrup]], [[https://openalex.org/A5059652073][Ken T. Ngo]], [[https://openalex.org/A5024403049][Blake R. Reed]], [[https://openalex.org/A5076502565][Stanislav Groysman]], [[https://openalex.org/A5004375411][David C. Grills]], [[https://openalex.org/A5017611605][Jonathan Rochford]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301388 
     
A series of twelve second coordination sphere (SCS) functionalized manganese tricarbonyl bipyridyl complexes are investigated for their electrocatalytic CO2 reduction properties in acetonitrile. A qualitative and quantitative assessment of the SCS functional groups is discussed with respect to the catalyst’s thermodynamic and kinetic efficiencies, and its product selectivity. In probing a broad scope of functional groups, it is clear that only the aprotic ortho‐arylester SCS is capable of promoting the highly desired low‐overpotential proton‐transfer electron‐transfer (PT‐ET) pathway for selective CO production. The ortho‐phenolic analogues cause an increase in overpotential with a product selectivity favoring H2 evolution, consistent with a high‐overpotential pathway via the anionic [Mn‐H]‐ intermediate. Alternative aprotic Lewis base functional groups such as trifluoromethyl, morpholine and acetamide are shown to also be capable of intermediate manganese hydride generation. The tertiary amine substituent, 2‐morpholinophenyl, exhibits a desirable product distribution characteristic of syn‐gas (CO:H2 = 30:48) with an impressive turnover frequency, while the secondary amine group, 2‐acetamidophenyl, induces a notable shift in selectivity with a faradaic yield of 55% for the formate (HCO2‐) product. In addition to their catalytic properties, cyclic voltammetry and infrared spectroelectrochemistry (IR‐SEC) studies are presented to probe pre‐catalyst electronic properties and the two‐electron reduction activation pathway.    

    

* Elaborate Modulating Binding Strength of Intermediates via Three‐component Covalent Organic Frameworks for CO2 Reduction Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392156542
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202401750")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392156542"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392156542"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392156542"))][Get cited by]]

OpenAlex: https://openalex.org/W4392156542 (Open access: False)
    
[[https://openalex.org/A5060008686][Minghao Liu]], [[https://openalex.org/A5089859489][Cheng‐Xing Cui]], [[https://openalex.org/A5090717104][Shuai Yang]], [[https://openalex.org/A5032456464][Xiubei Yang]], [[https://openalex.org/A5076573585][Xuewen Li]], [[https://openalex.org/A5048468640][Jun He]], [[https://openalex.org/A5003029548][Qing Xu]], [[https://openalex.org/A5028394871][Gaofeng Zeng]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202401750 
     
The catalytic performance for electrocatalytic CO2 reduction reaction (CO2RR) depends on the binding strength of the reactants and intermediates. Covalent organic frameworks (COFs) have been adopted to catalyze CO2RR, and their binding ability were tuned via constructing donor‐acceptor (DA) systems. However, most DA COFs had single donor and acceptor units, which caused wide‐range but lacking accuracy in modulating the binding strength of intermediates. More elaborate regulation of the interactions with intermediates are necessary and challenge to construct high‐efficiency catalysts. Herein, the three‐component COF with donor‐acceptor‐acceptor units was first constructed by introducing electron‐rich diarylamine unit and electron‐deficient benzothiazole and Co‐porphyrin units. Compared with two‐component COFs, the designed COF exhibit elevated electronic conductivity, enhanced reducibility, high efficiency charge transfer, further improving the electrocatalytic CO2RR performance with the faradic efficiency of 97.2% at −0.8 V and high activity with the partial current density of 27.85 mA cm−2 at −1.0 V which exceed other two‐component COFs. Theoretical calculations demonstrate that catalytic sites in three‐component COF had suitable binding ability of the intermediates, which were benefit for formation of *COOH and desorption of *CO. This work offers valuable insights for the advancement of multi‐component COFs, enabling modulated charge transfer to improve the CO2RR activity.    

    

* Elaborate Modulating Binding Strength of Intermediates via Three‐component Covalent Organic Frameworks for CO2 Reduction Reaction  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392168842
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrochemical Reduction of CO2 to Fuels, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202401750")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392168842"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392168842"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392168842"))][Get cited by]]

OpenAlex: https://openalex.org/W4392168842 (Open access: False)
    
[[https://openalex.org/A5060008686][Minghao Liu]], [[https://openalex.org/A5089859489][Cheng‐Xing Cui]], [[https://openalex.org/A5090717104][Shuai Yang]], [[https://openalex.org/A5032456464][Xiubei Yang]], [[https://openalex.org/A5076573585][Xuewen Li]], [[https://openalex.org/A5048468640][Jun He]], [[https://openalex.org/A5003029548][Qing Xu]], [[https://openalex.org/A5028394871][Gaofeng Zeng]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202401750 
     
The catalytic performance for electrocatalytic CO2 reduction reaction (CO2RR) depends on the binding strength of the reactants and intermediates. Covalent organic frameworks (COFs) have been adopted to catalyze CO2RR, and their binding ability were tuned via constructing donor‐acceptor (DA) systems. However, most DA COFs had single donor and acceptor units, which caused wide‐range but lacking accuracy in modulating the binding strength of intermediates. More elaborate regulation of the interactions with intermediates are necessary and challenge to construct high‐efficiency catalysts. Herein, the three‐component COF with donor‐acceptor‐acceptor units was first constructed by introducing electron‐rich diarylamine unit and electron‐deficient benzothiazole and Co‐porphyrin units. Compared with two‐component COFs, the designed COF exhibit elevated electronic conductivity, enhanced reducibility, high efficiency charge transfer, further improving the electrocatalytic CO2RR performance with the faradic efficiency of 97.2% at −0.8 V and high activity with the partial current density of 27.85 mA cm−2 at −1.0 V which exceed other two‐component COFs. Theoretical calculations demonstrate that catalytic sites in three‐component COF had suitable binding ability of the intermediates, which were benefit for formation of *COOH and desorption of *CO. This work offers valuable insights for the advancement of multi‐component COFs, enabling modulated charge transfer to improve the CO2RR activity.    

    

* MOF-derived Pyrrolic N-Stabilized Ni Single Atom Catalyst for Selective Electrochemical Reduction of CO2 to CO at High Current Density  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392205550
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ta06399b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392205550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392205550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392205550"))][Get cited by]]

OpenAlex: https://openalex.org/W4392205550 (Open access: True)
    
[[https://openalex.org/A5074996146][Jin Wook Lim]], [[https://openalex.org/A5083793010][Dong Heon Choo]], [[https://openalex.org/A5033788799][Jin Hyuk Cho]], [[https://openalex.org/A5031754381][Jae Hyun Kim]], [[https://openalex.org/A5032972345][Won Seok Cho]], [[https://openalex.org/A5071892233][Odongo Francis Ngome Okello]], [[https://openalex.org/A5015011368][Ki-Soo Kim]], [[https://openalex.org/A5055973826][Sungwon Lee]], [[https://openalex.org/A5032162545][Junwoo Son]], [[https://openalex.org/A5022054837][Si‐Young Choi]], [[https://openalex.org/A5079427906][Jong Kyu Kim]], [[https://openalex.org/A5067575191][Ho Won Jang]], [[https://openalex.org/A5083183967][Soo Young Kim]], [[https://openalex.org/A5074670180][Jong‐Lam Lee]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d3ta06399b  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ta/d3ta06399b][pdf]])
     
Electrochemical reduction of CO2 to chemical fuels with transition metal-based single atom catalyst (SAC) offers a promising strategy to reduce CO2 with high catalytic selectivity. To date, the study of...    

    

* Analyses of Port Infrastructure Investment and Shore Power Subsidy Policies for Inland Container Transportation Network with CO2 Emission Reduction Targets  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392173419
:TOPICS: Environmental Impact of Maritime Transportation Emissions, Optimization of Container Terminal Operations and Logistics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1504/ijstl.2024.10062557")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392173419"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392173419"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392173419"))][Get cited by]]

OpenAlex: https://openalex.org/W4392173419 (Open access: True)
    
[[https://openalex.org/A5074506944][Xiaofeng Ma]], [[https://openalex.org/A5005595781][Xia Pan]], [[https://openalex.org/A5017054985][Zhong Ming]], [[https://openalex.org/A5020543377][Z.J. Wang]], International Journal of Shipping and Transport Logistics. 1(1)] 2024. https://doi.org/10.1504/ijstl.2024.10062557 
     
No abstract    

    

* Effect of octahedral occupancy of bimetal-doping and CO2-induced surface reconstruction on oxygen reduction reaction of cobalt-based perovskite oxides  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392145417
:TOPICS: Solid Oxide Fuel Cells, Emergent Phenomena at Oxide Interfaces, Magnetocaloric Materials Research
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149770")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392145417"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392145417"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392145417"))][Get cited by]]

OpenAlex: https://openalex.org/W4392145417 (Open access: False)
    
[[https://openalex.org/A5026810495][Haocong Wang]], [[https://openalex.org/A5046863535][Wenka Zhu]], [[https://openalex.org/A5033246962][Jian Gong]], [[https://openalex.org/A5017197771][Gao Min]], [[https://openalex.org/A5048247540][Lanlan Xu]], [[https://openalex.org/A5052588320][Wenwen Zhang]], [[https://openalex.org/A5057877330][Xiaojuan Liu]], [[https://openalex.org/A5009136959][Chenglin Yan]], [[https://openalex.org/A5034781601][Jian Meng]], Chemical Engineering Journal. 485(None)] 2024. https://doi.org/10.1016/j.cej.2024.149770 
     
No abstract    

    

* Auto-Occlusive Lidocaine 7% and Tetracaine 7% Cream has Greater Pain Reduction Effects in Comparison with Lidocaine 4% Cream during Laser CO2 Dermabrasion Procedure in Preparation of Non-Cultured Autologous Epidermal Cell Grafting for Repigmentation in Vitiligo Subjects. An Intrasubject Pilot Evaluation Study  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392163415
:TOPICS: Melanin Pigmentation in Mammalian Skin, Mechanisms of Skin Aging and Photodamage, Biomedical Applications of Silk Biomaterials
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.33140/djclt.03.01.03")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392163415"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392163415"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392163415"))][Get cited by]]

OpenAlex: https://openalex.org/W4392163415 (Open access: False)
    
, Dermatology Journal of Cosmetic and Laser Therapy. 3(1)] 2024. https://doi.org/10.33140/djclt.03.01.03 
     
Introduction: Autologous non-cultured epidermal cell graft is a complex but promising technique in the treatment of vitiligo. Affected vitiligo areas should be de-epithelialized using an ablative Laser CO2 prior healthy epidermal cell inoculation. The dermabrasion (DA) procedure could be painful for the patient. To reduce the discomfort of this step topical anaesthesia is very often required. Topical anaesthetics available differ for composition, concentration of active anaesthetic molecules and methods of application (occlusion or not). An auto occlusive film-forming cream containing Lidocaine 7% and Tetracaine 7% (Pl-C) has shown in previous trials to be very effective in reducing discomfort during dermatological painful procedures like phototherapy, laser-conducted tattoo removal and laser resurfacing for skin ageing. Study Aim: To compare the clinical efficacy of Pl-C with Lidocaine 4% cream (As-C) in reducing the pain during Laser DA procedures in vitiligo subjects in preparation of autologous non-cultured epidermal transplantation. Subjects and Methods: We performed a prospective intra-subject randomized cases series in 7 subjects (4 men and 3 women) with segmental vitiligo with symmetrical lesions suitable for autologous non-cultured epidermal transplantation. Before the DA procedures the Pl-C or As-C were applied in a randomized fashion over the vitiligo areas to be treated. Pl-C was applied for 20 min without occlusion. The product was removed before the Laser procedure. As-C cream was applied for 30 min with occlusive band and then removed before the procedure. The treated skin regions had a mean area of 72±50 cm2; (range: 10 to 150 cm2). The primary outcome was the 100-mm Visual Analogue Scale (VAS) for patient-assessed pain evaluation with 0 mm value means no pain at all and 100 mm representing the worst possible pain. Results: Just after the Laser CO2 DA procedure the VAS score in PL-C area was 32±7 mm and 58±8 mm in As-C treated areas. This difference (-25±4 mm; 95% CI: from -16 to -35 mm) was highly statistically significant (p=0.0001) and clinically relevant (higher than the minimum clinically significant difference). Conclusion: The Lidocaine 7% and Tetracaine 7% auto occlusive cream is more effective than lidocaine 4% cream in reducing the pain associated with Laser CO2 DA procedures in preparation of skin autologous transplantation in vitiligo subjects.    

    

* Carbon and air pollutant emissions forecast of China's cement industry from 2021 to 2035  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392214442
:TOPICS: Life Cycle Assessment and Environmental Impact Analysis, Integrated Pollution Prevention and Control Techniques, Estimating Vehicle Fuel Consumption and Emissions
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.resconrec.2024.107498")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392214442"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392214442"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392214442"))][Get cited by]]

OpenAlex: https://openalex.org/W4392214442 (Open access: False)
    
[[https://openalex.org/A5076409244][Xiao Liu]], [[https://openalex.org/A5064842058][Yang Li]], [[https://openalex.org/A5090018916][Jinlei Du]], [[https://openalex.org/A5049341927][Hao Zhang]], [[https://openalex.org/A5078964223][Jingnan Hu]], [[https://openalex.org/A5039514748][Aizhong Chen]], [[https://openalex.org/A5033748161][Wei Lv]], Resources, Conservation and Recycling. 204(None)] 2024. https://doi.org/10.1016/j.resconrec.2024.107498 
     
The cement industry is a major source of carbon dioxide and air pollutant emissions. This study developed a high-resolution emission inventory for China's cement industry and forecasted emissions from 2025 to 2035. The results showed that emissions in 2020 were 251, 709, 142, and 1.35 × 106 Gg for SO2, NOx, PM2.5, and CO2, respectively. The optimal model projections for 2035 showed that fuel and clinker substitutions had the best reduction effect on SO2 and CO2, with average reduction rates of –11.42 % and –7.37 %, respectively, compared to the 2035 frozen scenario. Pollutant control measures and clinker substitution had the best emission reduction effect on NOx and PM2.5, and the average reduction rates were –26.09 % and –4.23 %, respectively, compared to the 2035 frozen scenario. These results showed that the substitution of fuel and clinker has important co-benefits for air pollutants in the cement industry.    

    

* Green and facile synthesis of OH-functionalized UiO-66 with controlled particle sizes to improve the selective separation of CO2/N2  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392203741
:TOPICS: Membrane Gas Separation Technology, Chemistry and Applications of Metal-Organic Frameworks, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jssc.2024.124631")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392203741"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392203741"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392203741"))][Get cited by]]

OpenAlex: https://openalex.org/W4392203741 (Open access: False)
    
[[https://openalex.org/A5007576255][Jianzhong Ma]], [[https://openalex.org/A5001591791][Tao Zhao]], [[https://openalex.org/A5065172118][Xue Wang]], [[https://openalex.org/A5086455686][Junkuo Gao]], Journal of Solid State Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jssc.2024.124631 
     
The escalating levels of carbon dioxide in flue gas and the resultant greenhouse effect have heightened the need for adsorbents with high CO2 sorption and separation capabilities. However, Traditional heated synthesis methods are energy-intensive and often involve toxic solvents, which are not viable for widespread industrial use. This study introduces a room-temperature, eco-friendly synthesis technique to produce UiO-66-(OH)2 with varying amounts of PVP (0/0.1/0.2 g), effectively adjusting the particle morphology. Results confirm that this method maintains robust CO2 adsorption and selectivity. Notably, the addition of 0.1 g of PVP led to a reduction in pore size and adsorption capacity of CO2, yet remarkably enhanced its CO2/N2 separation performance sixfold, outperforming traditional CO2 adsorbents. Dynamic breakthrough experiments further validated the effectiveness of UiO-66-(OH)2 in separating binary mixtures of CO2/N2 (v/v = 15/85).    

    

* Enhancing CO2-H2S Storage Predictions in High H2S Fields: Improving Model Accuracy and Kinetic Rate Information  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392185286
:TOPICS: Carbon Dioxide Sequestration in Geological Formations, Carbon Dioxide Capture and Storage Technologies, Chemical-Looping Technologies
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2523/iptc-23878-ea")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392185286"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392185286"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392185286"))][Get cited by]]

OpenAlex: https://openalex.org/W4392185286 (Open access: False)
    
[[https://openalex.org/A5037215228][Mohd Fakrumie Zaidin]], [[https://openalex.org/A5007294766][S. M. Amin]], [[https://openalex.org/A5016269972][Farhana Jaafar Azuddin]], [[https://openalex.org/A5041128601][Arman Abdul Razak]], [[https://openalex.org/A5037090946][N. Mohsin]], [[https://openalex.org/A5014470673][Y. W. Pin]], [[https://openalex.org/A5020335412][Raj Deo Tewari]], All Days. None(None)] 2024. https://doi.org/10.2523/iptc-23878-ea 
     
Abstract In the context of carbon capture and storage (CCS), the presence of impurities, such as Hydrogen Sulfide (H2S), in the injected Carbon Dioxide (CO2) stream poses a significant challenge (Bennion and Bachu, 2008). This challenge is particularly pronounced in carbonate reservoirs due to the potential precipitation of the minerals (Ahmad et al., 2023). Such precipitation can have detrimental effects on carbonate rock properties, including a reduction in rock porosity and permeability (Labus & Suchodolska, 2017; Clark et al., 2018). Ultimately, these changes can impact injectivity and storage capacity (Wang et al., 2012; (Zaidin et al., 2018), making it essential to comprehend the geochemical reactions involved, which are demonstrated as follows:    

    

* Effects of Organic Matter Addition on Soil Carbon Contents, CO2 Emissions, and Bacterial Compositions in a Paddy Field in South China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392155766
:TOPICS: Soil Carbon Dynamics and Nutrient Cycling in Ecosystems, Meta-analysis in Ecology and Agriculture Research, Sustainable Diets and Environmental Impact
:PUBLICATION_DATE: 2024-02-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/agronomy14030443")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392155766"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392155766"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392155766"))][Get cited by]]

OpenAlex: https://openalex.org/W4392155766 (Open access: True)
    
[[https://openalex.org/A5035880567][Xiang-Bin Yao]], [[https://openalex.org/A5069622234][Xuechan Zhang]], [[https://openalex.org/A5031289194][Meiyang Duan]], [[https://openalex.org/A5024074896][Yang Yong]], [[https://openalex.org/A5071571264][Qiyue Xie]], [[https://openalex.org/A5028719052][Haowen Luo]], [[https://openalex.org/A5021821095][Jing Peng]], [[https://openalex.org/A5071565869][Zhaowen Mo]], [[https://openalex.org/A5006629736][Shenggang Pan]], [[https://openalex.org/A5017606722][Xiangru Tang]], Agronomy. 14(3)] 2024. https://doi.org/10.3390/agronomy14030443  ([[https://www.mdpi.com/2073-4395/14/3/443/pdf?version=1708764518][pdf]])
     
Increasing soil organic carbon (SOC) contents and reducing carbon dioxide (CO2) emissions in paddy soil fields can result in positive impacts on climate change mitigation and soil quality. However, SOC accumulation and its microbial driving factors under enhanced fertilization strategies (e.g., organic matter application) are still unclear. Therefore, we investigated the effects of organic matter addition on SOC variations, CO2 fluxes, and their relationships with soil bacterial compositions and functions through a 6-year fertilizer experiment in rice fields involving two fertilization types, namely chemical fertilizer (NPK) and chemical fertilizer combined with organic matter (NPK+OM). The results showed significantly higher and lower SOC contents (p < 0.05) in the 10–20 cm soil layer under the NPK+OM treatment before rice transplanting and after rice harvest, respectively, than those under the NPK treatment. The lower SOC contents after rice harvest might be due to the great nutrient consumption, resulting in higher rice yields in the NPK+OM than those in the NPK treatment by 6.68 to 32.35%. Compared with NPK, NPK+OM reduced the in-situ CO2 fluxes by 38.70–118.59%. However, the ex-situ SOC mineralization rates were not affected by NPK+OM in the 0–10 and 10–20 cm soil layers. The 16S rRNA sequence indicated a significant increase in the abundance of non-singleton amplicon sequence variants (ASVs) in the NPK+OM treatment scenario compared to those in the NPK treatment scenario. The top three most important soil bacterial phylum influenced by NPK+OM were LCP-89, BRC1, and Rokubacteria in April, as well as Firmicutes, Nitrospinae, and BRC1 in July. Soil Actinobacteria was negatively correlated with the SOC contents in April and July. The results of the present study demonstrate the economic and ecological benefits of the organic matter addition in rice production, as well as the contribution of soil bacteria to SOC accumulation and CO2 emission reduction.    

    

* From Drilling to Production: Digital Solutions for Automation and Remote Operations in the Amazon Region  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392185376
:TOPICS: Application of Diagnostic Techniques in Oil Wells, Advanced Techniques in Reservoir Management, Drilling Fluid Technology and Well Integrity
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2523/iptc-23887-ms")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392185376"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392185376"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392185376"))][Get cited by]]

OpenAlex: https://openalex.org/W4392185376 (Open access: False)
    
[[https://openalex.org/A5057327815][Johanna Gallegos]], [[https://openalex.org/A5064903825][Hugo Quevedo]], [[https://openalex.org/A5092978712][Kevin Etcheverry]], [[https://openalex.org/A5061476326][José Romero]], [[https://openalex.org/A5005867849][Haddid Vega Vázquez]], [[https://openalex.org/A5036375424][P. Banda Rueda]], [[https://openalex.org/A5036780983][Juan José Anaya]], [[https://openalex.org/A5064355643][Karen Peña]], [[https://openalex.org/A5024065327][Julia Carrera]], No host. None(None)] 2024. https://doi.org/10.2523/iptc-23887-ms 
     
Abstract In a brown field with over 50 years of production in the middle of the Amazon region, it is essential to optimize the operational processes from drilling to the real-time production monitoring, as well as to improve the speed of decision making to minimize downtimes, non- productive times (NPTs), maximizing production and the return of investment of an asset, and reducing carbon dioxide (CO2) emissions. By applying multi-domain digital solutions to automate the drilling operations to bring oil to production earlier and to remotely operate and monitor an artificial lifted system, optimizing production, and providing better decision making, these objectives were successfully achieved, establishing an integrated digital solution that generates tangible values to the operation. The rig automation with a digital solution uses a goal-based approach to handle constantly changing drilling conditions and repetitive tasks such as pre and post connection procedures without the constant need of human intervention. It commands the rig control system to control the surface equipment within the context of standard operating procedures incorporated into the system configuration. Its powerful data analysis and learning systems assist and enhance every task. Once the well is drilled and completed, the installation of gateways that applies cloud and edge computing, has enabled the field team to remotely start up the artificial lift equipment, real-time monitoring, run automated workflows and more effective decision-making to troubleshoot bottlenecks. This has unlocked remote operations to improve production, reduce downtimes, CO2 emissions, and safety-related events. Since 2021 the Operator has drilled 25 wells applying a digital solution for rig automation and has also changed the drillers training, resulting in an average reduction of 46% in pre-post connection times, an 2% increase in on-bottom rate of penetration (ROP), a total saved time of 27.22 days, and an average 82% drilling in automated mode, enabling the field to bring production forward and improve its performance and also reducing 1014 tons of CO2. Since 2020 the asset has implemented gateways to supervise 270 producer wells and several surface equipment's. This has granted the field team the chance to carry out an average of 2,800 remote operations and 2,100 alerts per year, which has had an effect of 1200 barrels of oil per month saved from the related activities and a travel reduction of 72,000 kms per year and a decrease of 60.5 tons of CO2, improving the process efficiency by 96% and increasing personnel efficiency by 17%, generating available man-hours to improve other activities. This successful showcase of the potential of Digital Transformation in the oilfield illustrates how digital tools can help to optimize efficiency and early production, decrease downtime, reduce the carbon footprint, minimize operational risks, and cut costs, making it a game changer for the oil and gas industry.    

    

* Research on the Effect of Carbon Emission Trading Policy on Carbon Emission Reduction-Empirical Analysis based on PSM-DID Model  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392162299
:TOPICS: Life Cycle Assessment and Environmental Impact Analysis, Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-02-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1142/9789811270277_0015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392162299"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392162299"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392162299"))][Get cited by]]

OpenAlex: https://openalex.org/W4392162299 (Open access: False)
    
[[https://openalex.org/A5023479665][Jiaqiu Wang]], [[https://openalex.org/A5025387018][Xiaocheng Sun]], No host. None(None)] 2024. https://doi.org/10.1142/9789811270277_0015 
     
Economic Management and Big Data Application, pp. 157-163 (2024) No AccessResearch on the Effect of Carbon Emission Trading Policy on Carbon Emission Reduction-Empirical Analysis based on PSM-DID ModelJiaqiu Wang and Xiaocheng SunJiaqiu WangSchool of Management, Dalian Polytechnic University, Dalian, 116000, China and Xiaocheng SunSchool of Management, Dalian Polytechnic University, Dalian, 116000, ChinaCorresponding author.https://doi.org/10.1142/9789811270277_0015Cited by:0 (Source: Crossref) PreviousNext AboutSectionsPDF/EPUB ToolsAdd to favoritesDownload CitationsTrack CitationsRecommend to Library ShareShare onFacebookTwitterLinked InRedditEmail Abstract: This paper mainly studies the impact of carbon emission trading policies on carbon dioxide emission intensity. Panel data from 30 provinces (municipalities) from 2005 to 2017 are selected, and the research methods of propensity matching (PSM) and difference method (DID) are used. It is found that the implementation of the carbon emission trading rights policy has a significant impact on carbon dioxide emissions. Compared with the pilot areas, the carbon emission trading rights policy can significantly reduce the carbon dioxide emission intensity in the pilot areas. Given this, on the one hand, it can be shown that certain emission reduction policies have a positive impact on reducing carbon dioxide emissions. On the other hand, it has certain practical significance for the unification of carbon dioxide emission rights in China and realizing China’s dual carbon goals. This work is supported by The Education Department of Liaoning Province. Work partially supported by grant J2020081 of the Education 2020 Scientific Research Funding.Keywords: carbon dioxide emission intensitycarbon emission tradingPSM-DID FiguresReferencesRelatedDetails Recommended Economic Management and Big Data ApplicationMetrics History Keywordscarbon dioxide emission intensitycarbon emission tradingPSM-DIDPDF download    

    

* Can Low-Carbon City Pilot Policies Reduce Environmental Pollution? Evidence From Prefecture-Level Data in China  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392171238
:TOPICS: Economic Impact of Environmental Policies and Resources
:PUBLICATION_DATE: 2024-01-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.54691/40crve68")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392171238"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392171238"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392171238"))][Get cited by]]

OpenAlex: https://openalex.org/W4392171238 (Open access: True)
    
[[https://openalex.org/A5042973046][Ying Zhang]], Frontiers in Humanities and Social Sciences. 4(1)] 2024. https://doi.org/10.54691/40crve68  ([[https://bcpublication.org/index.php/FHSS/article/download/5940/5778][pdf]])
     
Based on the second batch of low-carbon city pilot policies in 2013 as a quasi-natural experiment, this study adopts the panel data of 212 cities in China from 2007 to 2017, and uses the difference-in-differences model (DID) to carry out a policy evaluation of the pollution reduction and emission reduction effects of the low-carbon pilot policies and further analyzes the transmission mechanism. Based on the DID method, the actual impacts of the government's low-carbon call policy and low-carbon governance policy on the urban ecological environment are examined. It is found that compared with non-pilot cities, low-carbon governance construction in low-carbon pilot cities significantly reduces pollutant emissions in the region. Analysis of the transmission mechanism reveals that urban low-carbon governance strengthens the strength of environmental policies and reduces urban carbon and pollutant emissions through the low-carbon treatment of urban waste and the low-carbon industrial structure. The test of regional heterogeneity found that the effect of pollution reduction and emission reduction is more significant in the eastern cities, high population concentrated cities and more economically developed cities. The results are still significant after replacing the explanatory variables with sulphur dioxide content and excluding extreme outliers. Therefore, the emission reduction policy has a significant contribution to improving the urban environment and reducing pollution emissions.    

    

* Confronting climate change and the AI revolution  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392176343
:TOPICS: Smart Cities: Innovations and Challenges, Impact of COVID-19 on Global Environment
:PUBLICATION_DATE: 2023-07-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.46692/9781447369950.015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392176343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392176343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392176343"))][Get cited by]]

OpenAlex: https://openalex.org/W4392176343 (Open access: False)
    
, No host. None(None)] 2023. https://doi.org/10.46692/9781447369950.015 
     
Extreme weather events have already shown us the kind of world we will bequeath our grandchildren and the later generations to come, if we continue business as usual. A rapid reduction of our carbon dioxide emissions requires a rapid shift away from fossil fuels to green energy generators. This raises the real possibility that many workers will be forced into long term unemployment or, at best, trapped in precarious employment. The Green New Deal (GND) is essentially an initiative designed to address these two major concerns.    

    

* Assessing the Electrochemical CO2 Reduction Reaction Performance Requires More Than Reporting Coulombic Efficiency  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392143647
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aesr.202400031")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392143647"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392143647"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392143647"))][Get cited by]]

OpenAlex: https://openalex.org/W4392143647 (Open access: False)
    
[[https://openalex.org/A5053516374][Paniz Izadi]], [[https://openalex.org/A5046744094][Jia Song]], [[https://openalex.org/A5012190219][Chandani Singh]], [[https://openalex.org/A5026207543][Deepak Pant]], [[https://openalex.org/A5040347964][Falk Harnisch]], Advanced energy and sustainability research. None(None)] 2024. https://doi.org/10.1002/aesr.202400031 
     
Reporting coulombic efficiency () is the common way to assess the performance of electrochemical carbon dioxide (CO 2 ) reduction reaction (eCO 2 RR) in literature, whereas its carbon conversion efficiency () is frequently neglected. Herein, the importance of reporting both efficiencies when evaluating the eCO 2 RR is discussed, using Sn‐based gas diffusion electrodes (GDEs) as model electrodes. It is shown that can vary remarkably at a constant with minor operational changes. Over 120 min experiments with operational conditions being representative of numerous previous studies, the is increased from ≈20% to 41% (being only 9% below the theoretical maximum). This was achieved by simply adjusting the inlet CO 2 flow rate from ≈35 to 16 mL min −1 , while was identical at both CO 2 flow rates (≈85%, 7%, and 4% for production of formate/formic acid, CO, and H 2 , respectively at both conditions). Thus, it is advocated that reporting of both efficiencies, for electrons and carbon, is required for meaningfully assessing the performance of an eCO 2 RR system.    

    

* Co-optimization of system configurations and energy scheduling of multiple community integrated energy systems to improve photovoltaic self-consumption  :CO2RR:
:PROPERTIES:
:UUID: https://openalex.org/W4392202961
:TOPICS: Demand Response in Smart Grids, Integration of Renewable Energy Systems in Power Grids, Integration of Electric Vehicles in Power Systems
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.renene.2024.120230")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392202961"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392202961"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392202961"))][Get cited by]]

OpenAlex: https://openalex.org/W4392202961 (Open access: False)
    
[[https://openalex.org/A5050431244][Changqi Wei]], [[https://openalex.org/A5078303039][Jiangjiang Wang]], [[https://openalex.org/A5048976082][Yuan Zhou]], [[https://openalex.org/A5002803940][Yuxin Li]], [[https://openalex.org/A5000799344][Weiliang Liu]], Renewable Energy. None(None)] 2024. https://doi.org/10.1016/j.renene.2024.120230 
     
Given the increasing integration of building photovoltaics and the accelerated transformation of power systems, the supply-demand imbalance in photovoltaic communities has become a pressing issue. This study presents a novel optimization model for collaborative planning and scheduling. The alternating direction multiplier method is utilized to derive an optimal economic scheduling strategy for the community cooperative alliance, while ensuring private information protection. Additionally, the genetic algorithms are employed to ascertain the optimal configuration. The optimization model prioritizes the common good over individual interests in community cooperation alliances, meaning some members may need to compromise their self-interest to attain optimized overall benefits. Therefore, a compensation mechanism based on the Nash negotiation principle is established to ensure fair distribution of benefits. The simulation results demonstrate that the primary energy saving rate, annual cost saving rate, and carbon dioxide emission reduction rate of the photovoltaic community alliance are 42.91%, 32.50%, and 41.81%, respectively, and the self-consumption level of photovoltaic is vastly improved to 98.83% on a typical winter day. The sensitivity analysis illustrates that the photovoltaic panels in buildings contribute to a decrease in energy consumption and carbon emission by 25.57% and 26.15%, respectively. In contrast, they result in a cost increase of 11.05%.    

    
