#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Sat Jul  6 01:07:38 2024

Found 1 results from 2024-06-29 to 2024-07-06
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Choreographing Oscillatory Hydrodynamics with DNA-Coated Gold Nanoparticles  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4400107876
:TOPICS: Nanofluidics and Nanopore Technology, Lipid Rafts and Membrane Dynamics, Plasmonic Nanoparticles: Synthesis, Properties, and Applications
:PUBLICATION_DATE: 2024-06-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c06868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400107876"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400107876"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400107876"))][Get cited by]]

OpenAlex: https://openalex.org/W4400107876 (Open access: True)
    
[[https://openalex.org/A5047482539][Anish Rao]], [[https://openalex.org/A5005106523][Ana Sánchez Iglesias]], [[https://openalex.org/A5006877674][Marek Grzelczak]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c06868 
     
Periodic responses to nonperiodic energy inputs, such as oscillations, are hallmarks of living systems. Nanoparticle-based systems have largely remained unexplored in the generation of oscillatory features. Here, we demonstrate a nanosystem featuring hierarchical response to light, where thermoplasmonic effects and reversible DNA-hybridization generate thermal convective forces and ultimately, oscillatory hydrodynamic flows. The slow aggregation of gold nanoparticles (AuNPs) serves as a positive feedback, while fast photothermal disassembly acts as negative feedback. These asymmetric feedback loops, combined with thermal hysteresis for time-delay, are essential ingredients for orchestrating an oscillating response.    

    
