#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Wed Sep  4 01:16:12 2024

Found 2 results from 2024-08-28 to 2024-09-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Pulse Manipulation on Cu-Based Catalysts for Electrochemical Reduction of CO2  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4402031369
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Applications of Ionic Liquids, Thermoelectric Materials
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c03513")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402031369"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402031369"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402031369"))][Get cited by]]

OpenAlex: https://openalex.org/W4402031369 (Open access: False)
    
[[https://openalex.org/A5101364539][Wanlong Xi]], [[https://openalex.org/A5055828743][Hongyao Zhou]], [[https://openalex.org/A5100681631][Peng Yang]], [[https://openalex.org/A5089177148][Huiting Huang]], [[https://openalex.org/A5061908731][Jia Tian]], [[https://openalex.org/A5039124217][Marina Ratova]], [[https://openalex.org/A5100779279][Dan Wu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c03513 
     
Electrocatalytic carbon dioxide reduction (CO2RR) over Cu-based catalysts has emerged as a promising strategy for value-added artificial carbon cycling, addressing the current climate and energy challenges. However, the product selectivity and long-term stability of Cu-based catalysts are limited by their instability at constant potential. Recent advancements in pulsed techniques aim to overcome these limitations, enhancing the industrial feasibility of the CO2RR systems. This review critically examines recent research progress in pulsed CO2RR over Cu-based catalysts, offering a comprehensive synthesis of current findings. Key pulse parameters and characterization strategies are explored to uncover the mechanisms behind the enhanced CO2RR performance. The focus is on surface reconstruction, encompassing the regeneration and stabilization of the Cu oxidation states alongside morphological evolution, while also discussing microenvironment changes, including local CO2 concentration, local pH, and ionic arrangement. The intricate modulation mechanisms of pulse mode, potential, and duration on the CO2RR performance are elucidated, highlighting their interconnections. Finally, we identify the prevailing challenges and propose future directions for achieving environmentally friendly and economically viable artificial carbon cycling. By providing insightful perspectives on optimizing pulsed CO2RR, this review paves the way for developing more efficient and robust Cu-based catalytic systems.    

    

* Physicochemical Principles of AC Electrosynthesis: Reversible Reactions  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4402079108
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Applications of Photoredox Catalysis in Organic Synthesis
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c06664")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402079108"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402079108"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402079108"))][Get cited by]]

OpenAlex: https://openalex.org/W4402079108 (Open access: False)
    
[[https://openalex.org/A5056946387][Yong Rui Poh]], [[https://openalex.org/A5068620047][Yu Kawamata]], [[https://openalex.org/A5054454592][Joel Yuen-Zhou]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c06664 
     
Electrolysis integrates renewable energy into chemical manufacturing and is key to sustainable chemistry. Controlling the waveform beyond direct current (DC) addresses the long-standing obstacle of chemoselectivity, yet it also expands the parameter set to optimize, creating a demand for theoretical predictions. Here, we report the first analytical theory for predicting chemoselectivity in an alternating current (AC) electrosynthesis. The mechanism is a selective reversal of the unwanted redox reaction during periods of opposite polarity, reflected in the final reaction outcome as a time-averaged effect. In the ideal scenario of all redox reactions being reversible, square AC waveform biases the outcome toward more overoxidation/over-reduction, whereas sine AC waveform exhibits the opposite effect. However, in a more realistic scenario of some redox reactions being quasi-reversible, sine AC may behave mostly like square AC. These predictions are in numerical agreement with model experiments employing acetophenone and align qualitatively with the literature precedent. Collectively, this study provides theoretical proof for a growing trend that promotes changing waveforms to overcome limitations challenging to address by varying canonical electrochemical parameters.    

    
