#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Sun Apr  7 00:50:24 2024

Found 1 results from 2024-03-31 to 2024-04-07
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Kinetic Insights into Boron-Based Materials Catalyzed Oxidative Dehydrogenation of Light Alkanes  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4393375823
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/prechem.4c00003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393375823"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393375823"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393375823"))][Get cited by]]

OpenAlex: https://openalex.org/W4393375823 (Open access: True)
    
[[https://openalex.org/A5078755966][Hao Tian]], [[https://openalex.org/A5073687384][Bingjun Xu]], Precision chemistry. None(None)] 2024. https://doi.org/10.1021/prechem.4c00003  ([[https://pubs.acs.org/doi/pdf/10.1021/prechem.4c00003][pdf]])
     
High selectivity toward alkenes in oxidative dehydrogenation (ODH) of light alkanes makes boron-based materials promising catalysts. However, many key mechanistic aspects are still debated due to the challenge of capturing fleeting reaction intermediates. Kinetic analysis, including determining reaction orders and activation energy, could be informative for reactions involving radical intermediates but has not been extensively exploited. This Review summarizes the current understanding of the apparent alkane reaction order and the apparent activation energy in the boron-catalyzed ODH. Despite varying compositions and structures, a majority of boron-based catalysts share many common features, including alkene selectivity, the evolution and the formation of active site, and the apparent kinetic properties. These common trends could be attributed to the shared gas-phase radical-mediated reaction pathways and the formation of active hydroxylated boron oxide species on boron-containing materials under ODH conditions. Values of apparent alkane reaction orders and apparent activation energies are sensitive and reliable experimental measures of the contributions of the gas-phase radical-mediated and surface-mediated pathways, suggesting the outline of a general mechanistic framework of the boron-catalyzed ODH.    

    
