#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Mon Apr 15 03:23:19 2024

Found 2 results from 2024-04-08 to 2024-04-15
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Dynamic Promotion of the Oxygen Evolution Reaction via Programmable Metal Oxides  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4394568896
:TOPICS: Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsenergylett.4c00365")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394568896"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394568896"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394568896"))][Get cited by]]

OpenAlex: https://openalex.org/W4394568896 (Open access: False)
    
[[https://openalex.org/A5030610409][Sallye R. Gathmann]], [[https://openalex.org/A5065773454][Christopher J. Bartel]], [[https://openalex.org/A5029991019][Lars C. Grabow]], [[https://openalex.org/A5022932212][Omar A. Abdelrahman]], [[https://openalex.org/A5071975512][C. Daniel Frisbie]], [[https://openalex.org/A5003718847][Paul J. Dauenhauer]], ACS energy letters. None(None)] 2024. https://doi.org/10.1021/acsenergylett.4c00365 
     
Hydrogen gas is a promising renewable energy storage medium when produced via water electrolysis, but this process is limited by the sluggish kinetics of the anodic oxygen evolution reaction (OER). Herein, we used a microkinetic model to investigate promoting the OER using programmable oxide catalysts (i.e., forced catalyst dynamics). We found that programmable catalysts could increase current density at a fixed overpotential (100–600× over static rates) or reduce the overpotential required to reach a fixed current density of 10 mA cm–2 (45–140% reduction vs static). In our kinetic parametrization, the key parameters controlling the quality of the catalytic ratchet were the O*-to-OOH* and O*-to-OH* activation barriers. Our findings indicate that programmable catalysts may be a viable strategy for accelerating the OER or enabling lower-overpotential operation, but a more accurate kinetic parametrization is required for precise predictions of performance, ratchet quality, and resulting energy efficiency.    

    

* Tuning Electrocatalytic Oxygen Reduction Reaction with Dynamic Control of Electrochemical Interfaces  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4394769135
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.3c13694")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394769135"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394769135"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394769135"))][Get cited by]]

OpenAlex: https://openalex.org/W4394769135 (Open access: False)
    
[[https://openalex.org/A5024316673][Hyein Lee]], [[https://openalex.org/A5037418435][Haixia Ren]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.3c13694 
     
Herein, we report the tuning of the activity and selectivity of the oxygen reduction reaction (ORR) through the dynamic regulation of the electrochemical interfaces to surpass the performance of conventional electrocatalysis. This is achieved by applying an oscillating potential between the ORR operating potential and anion adsorbing potential on a gold electrode. Oscillating potential enhances the selectivity for H2O2 by up to 1.35 times compared to the static potential, as confirmed by rotating ring-disk electrode and fluorescence assay measurements. We showed that the enhanced selectivity depends on dynamic adsorption and desorption of anions, and the enhancement occurs in the millisecond time scale or shorter. The transient selectivity to H2O2 can reach ∼97% within the first 5 ms after potential switching. Our results suggest that the dynamic interface can create a transient but unique microenvironment for new reactivity that cannot be reproduced under static conditions, which offers a new dimension in controlling electrocatalysis.    

    
