#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Sat Apr 20 01:02:45 2024

Found 1 results from 2024-04-13 to 2024-04-20
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Tuning Electrocatalytic Oxygen Reduction Reaction with Dynamic Control of Electrochemical Interfaces  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4394769135
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.3c13694")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394769135"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394769135"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394769135"))][Get cited by]]

OpenAlex: https://openalex.org/W4394769135 (Open access: False)
    
[[https://openalex.org/A5024316673][Hyein Lee]], [[https://openalex.org/A5037418435][Haixia Ren]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.3c13694 
     
Herein, we report the tuning of the activity and selectivity of the oxygen reduction reaction (ORR) through the dynamic regulation of the electrochemical interfaces to surpass the performance of conventional electrocatalysis. This is achieved by applying an oscillating potential between the ORR operating potential and anion adsorbing potential on a gold electrode. Oscillating potential enhances the selectivity for H2O2 by up to 1.35 times compared to the static potential, as confirmed by rotating ring-disk electrode and fluorescence assay measurements. We showed that the enhanced selectivity depends on dynamic adsorption and desorption of anions, and the enhancement occurs in the millisecond time scale or shorter. The transient selectivity to H2O2 can reach ∼97% within the first 5 ms after potential switching. Our results suggest that the dynamic interface can create a transient but unique microenvironment for new reactivity that cannot be reproduced under static conditions, which offers a new dimension in controlling electrocatalysis.    

    
