#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Wed Aug 21 01:12:01 2024

Found 1 results from 2024-08-14 to 2024-08-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Dynamic Control of Asymmetric Charge Distribution for Electrocatalytic Urea Synthesis  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4401684644
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Ammonia Synthesis and Electrocatalysis, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-08-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202408510")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401684644"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401684644"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401684644"))][Get cited by]]

OpenAlex: https://openalex.org/W4401684644 (Open access: False)
    
[[https://openalex.org/A5100454297][Jia Li]], [[https://openalex.org/A5101507157][Hao Sun]], [[https://openalex.org/A5100676299][Yirong Wang]], [[https://openalex.org/A5000218886][Zhan Shi]], [[https://openalex.org/A5026568078][Rong‐Lin Zhong]], [[https://openalex.org/A5045434827][Chunyi Sun]], [[https://openalex.org/A5013853310][Jing-yao Liu]], [[https://openalex.org/A5013189975][Zhong‐Min Su]], [[https://openalex.org/A5060057970][Ya‐Qian Lan]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202408510 
     
Abstract Constructing dual catalytic sites with charge density differences is an efficient way to promote urea electrosynthesis from parallel and CO 2 reduction yet still challenging in static system. Herein, a dynamic system is constructed by precisely controlling the asymmetric charge density distribution in an Au‐doped coplanar Cu 7 clusters‐based 3D framework catalyst (Au@cpCu 7 CF). In Au@cpCu 7 CF, the redistributed charge between Au and Cu atoms changed periodically with the application of pulse potentials switching between −0.2 and −0.6 V and greatly facilitated the electrosynthesis of urea. Compared with the static condition of pristine cpCu 7 CF (FE urea = 5.10%), the FE urea of Au@cpCu 7 CF under pulsed potentials is up to 55.53%. Theoretical calculations demonstrated that the high potential of −0.6 V improved the adsorption of * HNO 2 and * NH 2 on Au atoms and inhibited the reaction pathways of by‐products. While at the low potential of −0.2 V, the charge distribution between Au and Cu atomic sites facilitated the thermodynamic C–N coupling step. This work demonstrated the important role of asymmetric charge distribution under dynamic regulation for urea electrosynthesis, providing a new inspiration for precise control of electrocatalysis.    

    
