#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Thu Jul 11 01:11:05 2024

Found 2 results from 2024-07-04 to 2024-07-11
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Alumina–Titania Nanolaminate Condensers for Hot Programmable Catalysis  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4400269574
:TOPICS: Atomic Layer Deposition Technology, Lead-free Piezoelectric Materials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsmaterialslett.4c00652")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400269574"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400269574"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400269574"))][Get cited by]]

OpenAlex: https://openalex.org/W4400269574 (Open access: False)
    
[[https://openalex.org/A5069110770][Kyung‐Ryul Oh]], [[https://openalex.org/A5053531082][Amber Walton]], [[https://openalex.org/A5057749512][Jason Chalmers]], [[https://openalex.org/A5080549016][Janet Hopkins]], [[https://openalex.org/A5051020128][Jesse Canavan]], [[https://openalex.org/A5078494384][Tzia Ming Onn]], [[https://openalex.org/A5029871622][Susannah L. Scott]], [[https://openalex.org/A5071975512][C. Daniel Frisbie]], [[https://openalex.org/A5003718847][Paul J. Dauenhauer]], ACS materials letters. None(None)] 2024. https://doi.org/10.1021/acsmaterialslett.4c00652 
     
Nanolaminates composed of thin alternating layers of Al2O3 and TiO2 (ATO) were engineered by using atomic layer deposition as the dielectric material for a Pt-on-carbon catalytic condenser. Investigation assessed synthesis parameters including the deposition temperature, Al2O3 and TiO2 layer thicknesses, total number of layers, and a capping Al2O3 layer on the maximum charge accumulation in the Pt catalyst. The highest capacitance ATO configuration demonstrated a specific capacitance of ∼1200 nF/cm2 with working voltages of ±5 V, enabling the storage of 4 × 1013 electrons or holes per cm2 at room temperature. The ATO devices exhibited enhanced capacitance at elevated temperatures of up to 400 °C, suggesting the suitability of these materials for high-temperature applications. Adsorption of carbon monoxide on the Pt/C-ATO device characterized by grazing incidence infrared spectroscopy showed changes in the surface binding energy of 13.1 ± 0.8 kJ/mol for an applied external voltage bias of ±1 V.    

    

* Decoupling Plasmonic Hot Carrier from Thermal Catalysis via Electrode Engineering  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4400421741
:TOPICS: Electrocatalysis for Energy Conversion, Plasmonic Nanoparticles: Synthesis, Properties, and Applications, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.4c01803")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400421741"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400421741"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400421741"))][Get cited by]]

OpenAlex: https://openalex.org/W4400421741 (Open access: True)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5060648122][Yeersen Patehebieke]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5017286408][Carl‐Johan Wallentin]], [[https://openalex.org/A5016240919][Mikaela Görlin]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], Nano letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.4c01803 
     
Increased attention has been directed toward generating nonequilibrium hot carriers resulting from the decay of collective electronic oscillations on metal known as surface plasmons. Despite numerous experimental endeavors, demonstrating hot carrier-mediated photocatalysis without a heating contribution has proven challenging, particularly for single electron transfer reactions where the thermal contribution is generally detrimental. An innovative engineering solution is proposed to enable single electron transfer reactions with plasmonics. It consists of a photoelectrode designed as an energy filter and photocatalysis performed with light function modulation instead of continuously. The photoelectrode, consisting of FTO/TiO    

    
