#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Mon Sep  2 01:17:09 2024

Found 1 results from 2024-08-26 to 2024-09-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Physicochemical Principles of AC Electrosynthesis: Reversible Reactions  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4402079108
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Breath Analysis Technology
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c06664")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402079108"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402079108"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402079108"))][Get cited by]]

OpenAlex: https://openalex.org/W4402079108 (Open access: False)
    
[[https://openalex.org/A5056946387][Yong Rui Poh]], [[https://openalex.org/A5068620047][Yu Kawamata]], [[https://openalex.org/A5054454592][Joel Yuen-Zhou]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c06664 
     
Electrolysis integrates renewable energy into chemical manufacturing and is key to sustainable chemistry. Controlling the waveform beyond direct current (DC) addresses the long-standing obstacle of chemoselectivity, yet it also expands the parameter set to optimize, creating a demand for theoretical predictions. Here, we report the first analytical theory for predicting chemoselectivity in an alternating current (AC) electrosynthesis. The mechanism is a selective reversal of the unwanted redox reaction during periods of opposite polarity, reflected in the final reaction outcome as a time-averaged effect. In the ideal scenario of all redox reactions being reversible, square AC waveform biases the outcome toward more overoxidation/over-reduction, whereas sine AC waveform exhibits the opposite effect. However, in a more realistic scenario of some redox reactions being quasi-reversible, sine AC may behave mostly like square AC. These predictions are in numerical agreement with model experiments employing acetophenone and align qualitatively with the literature precedent. Collectively, this study provides theoretical proof for a growing trend that promotes changing waveforms to overcome limitations challenging to address by varying canonical electrochemical parameters.    

    
