#+filetags: Dynamic_catalysis_-_citing_and_related
#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Fri Feb 16 00:43:10 2024

Found 1 results from 2024-02-09 to 2024-02-16
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Progress in Single/Multi Atoms and 2D‐Nanomaterials for Electro/Photocatalytic Nitrogen Reduction: Experimental, Computational and Machine Leaning Developments  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:ID: https://openalex.org/W4391751653
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-02-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202304106")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391751653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391751653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391751653"))][Get cited by]]

OpenAlex: https://openalex.org/W4391751653 (Open access: False)
    
[[https://openalex.org/A5054940131][Aditya Narayan Singh]], [[https://openalex.org/A5081232540][Rohit Anand]], [[https://openalex.org/A5042211537][Mohammad Zafari]], [[https://openalex.org/A5065434371][Miran Ha]], [[https://openalex.org/A5091615384][Kwang S. Kim]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202304106 
     
Abstract The conversion of atmospheric nitrogen (N 2 ) into ammonia (NH 3 ), known as nitrogen fixation, plays a crucial role in sustaining life on Earth, facing innovation with electrocatalytic and photocatalytic methods. These approaches promise gentler conversions from atmospheric nitrogen to ammonia, diverging from the energy‐intensive Haber‐Bosch process, which requires complex plant infrastructure. Vitality lies in eco‐friendly, cost‐effective, and energy‐efficient pathways. The challenge is that electrocatalysts and photocatalysts for nitrogen reduction have shown low Faraday efficiency, hampered by hydrogen evolution. This work delves into recent strides in electro/photo‐catalytic nitrogen fixation/reduction, deciphering mechanisms, catalysts, and prospects. By unveiling the core principles steering these processes, it dissects efficiency drivers. Experimental and theoretical studies, ranging from density functional calculations/simulations to machine learning‐based catalyst screening, mark the path toward highly efficient catalysts, including single/multi‐atom catalysts embedded in 2D materials. The journey explores diverse catalysts, assessing their performance, spotlighting emerging nanomaterials, heterostructures, and co‐catalyst techniques. Perspectives on future directions and potential applications of electro/photo‐catalytic nitrogen fixation/reduction are offered, by emphasizing their role in sustainable nitrogen management and their implications for global agriculture and environmental sustainability.    

    
