#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Thu May  2 01:03:36 2024

Found 1 results from 2024-04-25 to 2024-05-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Electrocatalysis for Green(er) Chemistry: Limitations and Opportunities with Traditional and Emerging Characterization Methods for Tangible Societal Impact  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4395109925
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aesr.202400008")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395109925"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395109925"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395109925"))][Get cited by]]

OpenAlex: https://openalex.org/W4395109925 (Open access: True)
    
[[https://openalex.org/A5088443401][Peter C. Sherrell]], [[https://openalex.org/A5088443401][Peter C. Sherrell]], [[https://openalex.org/A5074190324][Mairis Iesalnieks]], [[https://openalex.org/A5069513177][Yemima Ehrnst]], [[https://openalex.org/A5080128381][Amgad R. Rezk]], [[https://openalex.org/A5037983005][Andris Šutka]], Advanced energy and sustainability research. None(None)] 2024. https://doi.org/10.1002/aesr.202400008 
     
The world is facing grand challenges in energy security, environmental pollution, and sustainable use (and re‐use) of resources. Electrochemical processes, incorporating electrosynthesis, electrochemical catalysis, and electrochemical energy storage devices, provide pathways to address these challenges via green chemistry. However, the applicability of electrochemical processes for these systems is limited by the required energy input, the “electrons” in electrochemistry. Electrocatalysis as a subset of electrochemistry is set to underpin many of the United Nations Sustainable Development Goals, including “Affordable and Clean Energy” through the production of future fuels and abatement of carbon emissions; “Responsible Consumption and Production” through recycling and degradation of waste; and “Climate Action” through CO 2 (and other greenhouse gas) remediation. The rise of green photovoltaic power has lowered the carbon cost of these electrons, making electrocatalysis an even more viable, green(er), chemical conversion pathway. This perspective highlights the need for comprehensive understanding of catalyst structure via in situ and operando analysis to complement device design considerations. The challenges faced by the field of electrocatalysis in data reporting, elimination of electrochemical artifacts, catalyst stability, and scaling to industrial relevance, along with opportunities, emerging tools, are discussed with a view to achieve the maximum ‘potential’ of electrocatalysis.    

    
