#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Tue Dec  3 01:27:55 2024

Found 3 results from 2024-11-26 to 2024-12-03
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Shedding Light on the Active Species in a Cobalt‐Based Covalent Organic Framework for the Electrochemical Oxygen Evolution Reaction  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4404723714
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-11-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/advs.202413555")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404723714"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404723714"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404723714"))][Get cited by]]

OpenAlex: https://openalex.org/W4404723714 (Open access: True)
    
[[https://openalex.org/A5001479913][Pouya Hosseini]], [[https://openalex.org/A5009233635][Andrés Rodríguez‐Camargo]], [[https://openalex.org/A5063231916][Yiqun Jiang]], [[https://openalex.org/A5101742243][Shouxin Zhang]], [[https://openalex.org/A5087818652][Christina Scheu]], [[https://openalex.org/A5050729260][Liang Yao]], [[https://openalex.org/A5046180571][Bettina V. Lotsch]], [[https://openalex.org/A5030444454][Kristina Tschulik]], Advanced Science. None(None)] 2024. https://doi.org/10.1002/advs.202413555 
     
Abstract While considerable efforts have been devoted to developing functionalized covalent organic frameworks (COFs) as oxygen evolution electrocatalysts in recent years, studies related to the investigation of the true catalytically active species for the oxygen evolution reaction (OER) remain lacking in the field. In this work, the active species of a cobalt‐functionalized COF (TpBpy‐Co) is studied as electrochemical OER catalyst through a series of electrochemical measurements and post‐electrolysis characterizations. These results suggest that cobalt oxide‐based nanoparticles are formed in TpBpy‐Co from Co(II) ions coordinated to the COF backbone when exposing TpBpy‐Co to alkaline media, and these newly formed nanoparticles serve as the primary active species for oxygen evolution. The study thus emphasizes that caution is warranted when assessing the catalytic activity of COF electrocatalysts, as the pristine COF may act as the pre‐catalyst, with the active species forming only under catalyst operating conditions. Specifically, strong coordination between COFs and metal centers under electrochemical operation conditions is crucial to avoid unintended transformation of COF electrocatalysts. This work thus contributes to the rational development of earth‐abundant COF OER catalysts for the production of green hydrogen from renewable resources.    

    

* Brush-Like Hollow PtTe2 Nanotube for Enhanced Formic Acid Electrooxidation Catalysis  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4404862958
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-11-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.4c05900")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404862958"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404862958"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404862958"))][Get cited by]]

OpenAlex: https://openalex.org/W4404862958 (Open access: False)
    
[[https://openalex.org/A5029264677][Qiaorong Jiang]], [[https://openalex.org/A5100645269][Zhiyi Wang]], [[https://openalex.org/A5100649878][Zhigang Huang]], [[https://openalex.org/A5101046588][Xuyuan Nie]], [[https://openalex.org/A5076815554][Delun Chen]], [[https://openalex.org/A5021321528][Xiao Han]], [[https://openalex.org/A5101957157][Wei Yan]], [[https://openalex.org/A5101473926][Hu Yang]], [[https://openalex.org/A5037198300][Xianmeng Song]], [[https://openalex.org/A5023396901][Haixin Lin]], [[https://openalex.org/A5073681835][Zi‐Ang Nan]], [[https://openalex.org/A5100783934][Zhaoxiong Xie]], The Journal of Physical Chemistry C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.4c05900 
     
No abstract    

    

* Hydrogen Peroxide Electrosynthesis via Selective Oxygen Reduction Reactions Through Interfacial Reaction Microenvironment Engineering  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4404866412
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-11-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202414490")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404866412"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404866412"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404866412"))][Get cited by]]

OpenAlex: https://openalex.org/W4404866412 (Open access: False)
    
[[https://openalex.org/A5018853194][Qiang Tian]], [[https://openalex.org/A5069537889][Lingyan Jing]], [[https://openalex.org/A5100354890][Wenyi Wang]], [[https://openalex.org/A5113221375][Xieshu Ye]], [[https://openalex.org/A5103812168][Xiaoyan Chai]], [[https://openalex.org/A5100445870][Xue Zhang]], [[https://openalex.org/A5101453394][Qi Hu]], [[https://openalex.org/A5009718397][Hengpan Yang]], [[https://openalex.org/A5064805977][Chuanxin He]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202414490 
     
Abstract The electrochemical two‐electron oxygen reduction reaction (2e − ORR) offers a compelling alternative for decentralized and on‐site H 2 O 2 production compared to the conventional anthraquinone process. To advance this electrosynthesis system, there is growing interest in optimizing the interfacial reaction microenvironment to boost electrocatalytic performance. This review consolidates recent advancements in reaction microenvironment engineering for the selective electrocatalytic conversion of O 2 to H 2 O 2 . Starting with fundamental insights into interfacial electrocatalytic mechanisms, an overview of various strategies for constructing the favorable local reaction environment, including adjusting electrode wettability, enhancing mesoscale mass transfer, elevating local pH, incorporating electrolyte additives, and employing pulsed electrocatalysis techniques is provided. Alongside these regulation strategies, the corresponding analyses and technical remarks are also presented. Finally, a summary and outlook on critical challenges, suggesting future research directions to inspire microenvironment engineering and accelerate the practical application of H 2 O 2 electrosynthesis is delivered.    

    
