#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Fri Jan  3 01:20:58 2025

Found 1 results from 2024-12-27 to 2025-01-03
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Visible Light Photolysis at Single Atom Sites in Semiconductor Perovskite Oxides  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:UUID: https://openalex.org/W4405844230
:TOPICS: Catalytic Processes in Materials Science, Advanced Photocatalysis Techniques, Electronic and Structural Properties of Oxides
:PUBLICATION_DATE: 2024-12-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c13821")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405844230"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405844230"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405844230"))][Get cited by]]

OpenAlex: https://openalex.org/W4405844230 (Open access: False)
    
[[https://openalex.org/A5042900117][Michael G. Allan]], [[https://openalex.org/A5087283512][Rachel A. Yang]], [[https://openalex.org/A5078799411][Silvia Mariño]], [[https://openalex.org/A5021173676][Michael J. Gordon]], [[https://openalex.org/A5047217534][Phillip Christopher]], [[https://openalex.org/A5039071105][Eranda Nikolla]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c13821 
     
Designing catalysts with well-defined active sites with chemical functionality responsive to visible light has significant potential for overcoming scaling relations limiting chemical reactions over heterogeneous catalyst surfaces. Visible light can be leveraged to facilitate the removal of strongly bound species from well-defined single cationic sites (Rh) under mild conditions (323 K) when they are incorporated within a photoactive perovskite oxide (Rh-doped SrTiO3). CO, a key intermediate in many chemistries, forms stable geminal dicarbonyl Rh complexes (Rh+(CO)2), that could act as site blockers or poisons during a catalytic cycle. For the first time, we demonstrate that CO removal can occur at mild temperatures (323 K) under low-energy red light (635 nm) irradiation, which is not possible for supported isolated-site Rh catalysts (0.2 wt % Rh/γ-Al2O3). Photolysis of supported Rh+(CO)2 complexes (e.g., 0.2 wt % Rh/γ-Al2O3) has been demonstrated but is limited to high energy UV photons. Rigorous kinetic experiments elucidate disparate mechanisms for CO photodepletion from Rh-doped SrTiO3 and supported isolated site Rh/γ-Al2O3. CO photodepletion from supported isolated site Rh/γ-Al2O3 involves a direct metal to ligand charge transfer mechanism, whereas Rh-doped SrTiO3 is governed by electron–hole pair formation in the perovskite. We show that under visible, low-energy red light, surface Rh species in Rh-doped SrTiO3 introduce midgap energy states above the valence band that facilitate electronic excitations leading to surface CO removal. Isolated Rh sites in Rh-doped SrTiO3 also exhibit exceptional stability under multiple CO photodepletion cycles. Overall, incorporating single sites into photoactive perovskite oxides is an effective strategy to influence surface chemistries with visible light.    

    
