#+filetags: Dynamic_catalysis_-_citing_and_related
#+TITLE: Dynamic catalysis - citing and related
Description: papers related to dynamic catalysis
Created on Wed Feb 14 00:44:29 2024

Found 2 results from 2024-02-07 to 2024-02-14
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=related_to%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]
- [[https://api.openalex.org/works?filter=cites%3Ahttps%3A//openalex.org/W2945032606%7Chttps%3A//openalex.org/W2969923410%7Chttps%3A//openalex.org/W3010067097%7Chttps%3A//openalex.org/W3041061357%7Chttps%3A//openalex.org/W3093929595]]

* Catalytic resonance theory: Circumfluence of programmable catalytic loops  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:ID: https://openalex.org/W4391562623
:TOPICS: Origin of Life and Prebiotic Chemistry, Advancements in Density Functional Theory, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcat.2024.115343")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391562623"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391562623"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391562623"))][Get cited by]]

OpenAlex: https://openalex.org/W4391562623 (Open access: False)
    
[[https://openalex.org/A5051959855][Madeline Murphy]], [[https://openalex.org/A5030610409][Sallye R. Gathmann]], [[https://openalex.org/A5065773454][Christopher J. Bartel]], [[https://openalex.org/A5022932212][Omar A. Abdelrahman]], [[https://openalex.org/A5003718847][Paul J. Dauenhauer]], Journal of Catalysis. 430(None)] 2024. https://doi.org/10.1016/j.jcat.2024.115343 
     
Chemical reactions on heterogeneous catalyst surfaces exhibit complex networks of elementary reactions with multiple pathways to fluid phase products, sometimes leading to surface reaction loops consisting of a closed cycle reaction pathway. While conventional catalysts at steady state exhibit zero net flux in either direction around a catalytic loop, the loop turnover frequency of three-species surface loops was evaluated in this work via microkinetic modeling to assess the reaction loop behavior resulting from a catalytic surface oscillating between two or more surface energy states. For dynamic heterogeneous catalysts undergoing applied oscillations of surface energy (i.e., programs), surface reaction loops of three species were shown to exhibit non-zero net flow of molecules around the loop, with the extent of loop turnover frequency varying with the applied frequency and amplitude of a sinusoidal or square wave oscillation. Alternatively, some dynamic surface reactions exhibited oscillations only between two surface species or resulted in surfaces covered by a single species at all times. More complex behavior was observed for dynamic surface programs of three distinct electronic states, with the temporal order of applied states controlling the direction of flow of molecules within a three-molecule surface loop. Catalytic loops have the potential to limit overall catalytic reaction rates and use energy in programmable catalysts, while some applications could purposely impose non-zero loop turnover frequency for improved surface reaction control.    

    

* Progress in Single/Multi Atoms and 2D‐Nanomaterials for Electro/Photocatalytic Nitrogen Reduction: Experimental, Computational and Machine Leaning Developments  :Dynamic_catalysis___citing_and_related:
:PROPERTIES:
:ID: https://openalex.org/W4391751653
:TOPICS: Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications
:PUBLICATION_DATE: 2024-02-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202304106")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391751653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391751653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391751653"))][Get cited by]]

OpenAlex: https://openalex.org/W4391751653 (Open access: False)
    
[[https://openalex.org/A5054940131][Aditya Narayan Singh]], [[https://openalex.org/A5081232540][Rohit Anand]], [[https://openalex.org/A5042211537][Mohammad Zafari]], [[https://openalex.org/A5065434371][Miran Ha]], [[https://openalex.org/A5091615384][Kwang S. Kim]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202304106 
     
Abstract The conversion of atmospheric nitrogen (N 2 ) into ammonia (NH 3 ), known as nitrogen fixation, plays a crucial role in sustaining life on Earth, facing innovation with electrocatalytic and photocatalytic methods. These approaches promise gentler conversions from atmospheric nitrogen to ammonia, diverging from the energy‐intensive Haber‐Bosch process, which requires complex plant infrastructure. Vitality lies in eco‐friendly, cost‐effective, and energy‐efficient pathways. The challenge is that electrocatalysts and photocatalysts for nitrogen reduction have shown low Faraday efficiency, hampered by hydrogen evolution. This work delves into recent strides in electro/photo‐catalytic nitrogen fixation/reduction, deciphering mechanisms, catalysts, and prospects. By unveiling the core principles steering these processes, it dissects efficiency drivers. Experimental and theoretical studies, ranging from density functional calculations/simulations to machine learning‐based catalyst screening, mark the path toward highly efficient catalysts, including single/multi‐atom catalysts embedded in 2D materials. The journey explores diverse catalysts, assessing their performance, spotlighting emerging nanomaterials, heterostructures, and co‐catalyst techniques. Perspectives on future directions and potential applications of electro/photo‐catalytic nitrogen fixation/reduction are offered, by emphasizing their role in sustainable nitrogen management and their implications for global agriculture and environmental sustainability.    

    
