#+filetags: Emacs_and_org-mode
#+TITLE: Emacs and org-mode
Description: Emacs and org-mode
Created on Sat Feb  3 18:28:53 2024

Found 25 results from 2024-01-20 to 2024-02-03
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=default.search%3Aemacs%7Corgmode%7Corg-mode]]

* Increasing the competitive advantage and the performance of SMEs using entrepreneurial marketing architectural innovation capability in North Sumatera, Indonesia  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391062838
:TOPICS: Impact of the Covid-19 Pandemic on Small and Medium Enterprises in Indonesia
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5267/j.uscm.2023.12.011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391062838"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391062838"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391062838"))][Get cited by]]

OpenAlex: https://openalex.org/W4391062838 (Open access: True)
    
[[https://openalex.org/A5048851522][Mulia Siregar]], [[https://openalex.org/A5043772246][Arlina Nurbaity Lubis]], [[https://openalex.org/A5090919092][Yeni Absah]], [[https://openalex.org/A5016508310][Parapat Gultom]], Uncertain Supply Chain Management. 12(2)] 2024. https://doi.org/10.5267/j.uscm.2023.12.011 
     
The aim of this study is to analyze how to improve the competitive advantage and performance of small and medium-sized enterprises (SMEs) in North Sumatra through marketing entrepreneurship and architectural innovation capabilities. The type of research is quantitative research. The study focused on UMKM in North Sumatra who offered the following categories of products: handicrafts, food and beverages, coffee shops, bakeries, fashion, clothing, and services. The research population consists of all 84,758 UMKMs in North Sumatra. As for the sample number ranging between 100 and 200, or at least 5 times the number of variable indicators, when using Structural Equation Modeling (SEM). The entire sample size for stage 1 was 102 SME samples from Medan city. To analyze the research data, the study used SmartPLS (Partial Least Squares). The findings of this study show that market orientation (MO) has a negative and insignificant impact on SME performance from data processing and hypothesis testing results. Entrepreneurship Marketing Architecture Innovation Capacity (EMAIC) has a beneficial and significant impact on Competitive Advantage (CA). The ability of Enterprise Marketing Architectures (EMAC) to innovate has a significant and beneficial impact on their success. Entrepreneurship orientation (EO) provides tangible proof of SME success through competitive advantage (CA). Corporate orientation has no direct impact on SME performance through competitiveness (CA).    

    

* Quasinormal modes in nonlinear σ models in the Eddington inspired Born-Infeld gravity  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391432376
:TOPICS: Holographic Derivation of Field Theories and Gravity, Cosmological Parameters and Dark Energy, Observation and Study of Gravitational Waves Phenomenon
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1103/physrevd.109.044003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391432376"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391432376"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391432376"))][Get cited by]]

OpenAlex: https://openalex.org/W4391432376 (Open access: False)
    
[[https://openalex.org/A5060307544][Bobir Toshmatov]], [[https://openalex.org/A5036692902][Bobomurat Ahmedov]], [[https://openalex.org/A5093838421][Azamjon Boydedayev]], [[https://openalex.org/A5001447135][Sardor Tojiev]], Physical review. 109(4)] 2024. https://doi.org/10.1103/physrevd.109.044003 
     
In this paper we explore properties of the spacetime of the monopole in nonlinear $\ensuremath{\sigma}$-models in the Eddington inspired Born-Infeld gravity. Particularly, we examine the radii of characteristic circular orbits of the test particles such as the circular null geodesics, marginally bound and stable circular orbits as a function of the spacetime parameters. Furthermore, we explore the dynamics of the massless scalar field. To enhance the precision of calculations, we employ multiple methods, including the WKB (Wentzel-Kramers-Brillouin) approximation, asymptotic iteration, and continued fractions methods. Our calculations demonstrate that the scalar field within the field of the monopole under examination remains stable against scalar perturbations. Notably, variations in the monopole parameter influence the longevity of the damping time of perturbations, with smaller damping rates prolonging their existence.    

    

* Radioactivity of the Atmospheric Aerosols Detected by Ctbto Stations in Africa Following the Accident at the Fukushima Daiichi Nuclear Power Plant  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391212957
:TOPICS: Environmental Impacts of Fukushima Nuclear Disaster, Safety and Management of Nuclear Fuel Transportation, Sources and Effects of Ionizing Radiation on Human Health
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4706329")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391212957"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391212957"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391212957"))][Get cited by]]

OpenAlex: https://openalex.org/W4391212957 (Open access: False)
    
[[https://openalex.org/A5093784909][Modou NIANG]], [[https://openalex.org/A5049186769][Martin Kalinowski]], [[https://openalex.org/A5068413254][T. Christoudias]], [[https://openalex.org/A5043273915][Cheikh Amadou Bamba Dath]], [[https://openalex.org/A5093784910][Aliou NIANE]], [[https://openalex.org/A5043512850][Ndèye Arame Boye Faye]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4706329 
     
Radionuclides from the reactor accident Fukushima Daiichi nuclear power plant were observed in the airborne aerosols at CTBT International Monitoring System (IMS) stations (MRP43, CMP13) in Africa. The maximum activity concentrations in the air measured in Mauritania were 186.44 10-6 Bq.m-3, 264.16 10-6 Bq.m-3 and 1269.94 10-6 Bq.m-3 for 134Cs, 137Cs and 131I respectively, and in Cameroon 16.42 10-6 Bq.m-3, 25.53 10-6 and 37.58 10-6 Bq.m-3 respectively for 134Cs, 137Cs and 131I. The mean ratio of 134Cs/137Cs and 131I/137Cs at both IMS stations was close to 1. The EMAC atmospheric chemistry-general circulation was used to simulate the emission and transport of the isotope 137Cs and map the deposition of the 137Cs deposition over Africa.    

    

* Delocalized nonlinear vibrational modes in Ni3Al  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391486563
:TOPICS: Design and Applications of Intermetallic Alloys, Atomic Force Microscopy Techniques, Discrete Solitons in Nonlinear Photonic Systems
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cnsns.2024.107890")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391486563"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391486563"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391486563"))][Get cited by]]

OpenAlex: https://openalex.org/W4391486563 (Open access: False)
    
[[https://openalex.org/A5015005076][O. V. Bachurina]], [[https://openalex.org/A5007125671][Ramil T. Murzaev]], [[https://openalex.org/A5049285264][S. A. Shcherbinin]], [[https://openalex.org/A5045349556][Aleksey Kudreyko]], [[https://openalex.org/A5067406080][Sergey V. Dmitriev]], [[https://openalex.org/A5085150401][D.V. Bachurin]], Communications in Nonlinear Science and Numerical Simulation. None(None)] 2024. https://doi.org/10.1016/j.cnsns.2024.107890 
     
Delocalized nonlinear vibrational modes (DNVMs) in crystals are exact solutions to the equations of atomic motion. They are determined solely by the symmetry of the lattice, and therefore exist for any interatomic potential and amplitude. DNVMs have been extensively studied in monoatomic crystals. In this work, they are analyzed for the first time in a binary Ni3Al alloy. A class of DNVMs in which only the cubic aluminum sublattice oscillates while the nickel atoms are at rest is considered. Using molecular dynamics, sixteen such DNVMs were found to be able to maintain time-periodic oscillations. The frequency response of the DNVMs was calculated in the wide range of oscillation amplitudes, using three different interatomic potentials. Most of the DNVMs exhibit a hard type nonlinearity when the frequency increases with increasing amplitude. The total energy and the ratio of the total to kinetic energy averaged over the oscillation period (related to the heat capacity of the crystal) were calculated as functions of amplitude. The difference between the results obtained with different potentials suggests the use of DNVMs to check the accuracy of interatomic potentials for binary alloys with L12 structure by comparing the frequency responses obtained from ab initio simulations with similar data from molecular dynamics simulations.    

    

* Orientation-dependent two-dimensional magnonic crystal modes in an ultralow-damping ferrimagnetic waveguide containing repositioned hexagonal lattices of Cu disks  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391348047
:TOPICS: Magnetic Skyrmions and Spintronics, Magneto-Optical Devices for Integrated Photonics, Cavity Optomechanics and Nanomechanical Systems
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1103/physrevapplied.21.014061")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391348047"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391348047"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391348047"))][Get cited by]]

OpenAlex: https://openalex.org/W4391348047 (Open access: True)
    
[[https://openalex.org/A5057152513][Kanta Mori]], [[https://openalex.org/A5072248410][Takumi Koguchi]], [[https://openalex.org/A5052915179][Toshiaki Watanabe]], [[https://openalex.org/A5021601551][Yuki Yoshihara]], [[https://openalex.org/A5029720786][Hidetoshi Miyashita]], [[https://openalex.org/A5070972276][Dirk Grundler]], [[https://openalex.org/A5067466372][Mitsuteru Inoue]], [[https://openalex.org/A5074376676][K. Ishiyama]], [[https://openalex.org/A5081499790][Taichi Goto]], Physical review applied. 21(1)] 2024. https://doi.org/10.1103/physrevapplied.21.014061  ([[http://link.aps.org/pdf/10.1103/PhysRevApplied.21.014061][pdf]])
     
Two-dimensional (2D) hexagonal lattices of $\mathrm{Cu}$ disks are shown to induce orientation-dependent magnonic crystal (MC) modes for propagating forward volume spin waves in a single-crystal yttrium iron garnet (YIG) film. The width and depth of the magnonic band gaps are 0.022 GHz and --15.2 dB at the frequency of 1.815 GHz. Integrating differently oriented lattices on the same YIG film and positioning them between the microwave antenna surrounded by magnon absorbers consisting of $\mathrm{Au}$ films, we clearly resolve a characteristic frequency shift of the magnonic band gap by altering the incident angle of the spin waves to the 2D MC. The shift amounts to approximately 10 MHz when the incident angle is changed between 10\ifmmode^\circ\else\textdegree\fi{} and 30\ifmmode^\circ\else\textdegree\fi{}. The obtained results show a good agreement with calculations using the finite integration technique and are a step toward complete band-gap investigations in YIG of ultralow spin-wave damping.    

    

* The ΔQ-method: State of health and degradation mode estimation for lithium-ion batteries using a mechanistic model with relaxed voltage points  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391197603
:TOPICS: Lithium-ion Battery Management in Electric Vehicles, Lithium-ion Battery Technology, Lithium Battery Technologies
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.234107")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391197603"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391197603"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391197603"))][Get cited by]]

OpenAlex: https://openalex.org/W4391197603 (Open access: False)
    
[[https://openalex.org/A5082980542][Tobias Hofmann]], [[https://openalex.org/A5006908434][Jiahao Li]], [[https://openalex.org/A5067728634][Jacob Hamar]], [[https://openalex.org/A5064301945][Simon V. Erhard]], [[https://openalex.org/A5068483766][Jan Philipp Schmidt]], Journal of Power Sources. 596(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.234107 
     
Lithium-ion batteries exhibit path-dependent aging behavior. dm! (dm!) estimation is a first step towards accurate soh! (soh!) representations by clustering degradation mechanisms. Mechanistic models shift and scale pristine half-cell ocp! (ocp!) curves of both electrodes to reconstruct the ocv! (ocv!) curve by minimizing the difference between measured and reconstructed ocv!. Alignment parameters describe the shift and scaling of the ocp!s and can be used to estimate soh! and dm!s. This study introduces the ΔQ-method, which relies on relaxed voltage points and accumulated charge between these points. It is independent of current rates and applicable after almost every event. The optimization problem minimizes deviation between measured and reconstructed ΔQ. The method is developed with an automotive cell dataset and validated with real-world vehicle data from the BMW i3. The ΔQ-method achieves a mean absolute soh! estimation error of 2.52 % and a mean absolute ocv! reconstruction error of 7.19 mV. Reliable estimations are ensured by predefined filters. The method remains effective with restricted soc! (soc!) windows or limited data points. It is robust against variations in input data, solver choice, and optimization settings. Convergence is improved by constraining the solution space.    

    

* Thermal expansion and temperature dependence of Raman modes in epitaxial layers of Ge and Ge1−xSnx  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391450480
:TOPICS: Silicon Photonics Technology, Physics and Chemistry of Schottky Barrier Height, Porous Silicon Nanoparticles and Nanostructures
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1103/physrevmaterials.8.023801")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391450480"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391450480"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391450480"))][Get cited by]]

OpenAlex: https://openalex.org/W4391450480 (Open access: False)
    
[[https://openalex.org/A5008813300][Agnieszka Anna Corley-Wiciak]], [[https://openalex.org/A5022384517][Diana Ryzhak]], [[https://openalex.org/A5086528569][M. H. Zoellner]], [[https://openalex.org/A5085173894][C. L. Manganelli]], [[https://openalex.org/A5008793083][Omar Concepción]], [[https://openalex.org/A5004068462][Oliver Skibitzki]], [[https://openalex.org/A5061020070][Detlev Grützmacher]], [[https://openalex.org/A5023796900][D. Buca]], [[https://openalex.org/A5090552612][Giovanni Capellini]], [[https://openalex.org/A5000299070][Davide Spirito]], Physical Review Materials. 8(2)] 2024. https://doi.org/10.1103/physrevmaterials.8.023801 
     
Temperature dependence of vibrational modes in semiconductors depends on lattice thermal expansion and anharmonic phonon-phonon scattering. Evaluating the two contributions from experimental data is not straightforward, especially for epitaxial layers that present mechanical deformation and anisotropic lattice expansion. In this paper, a temperature-dependent Raman study in epitaxial Ge and ${\mathrm{Ge}}_{1\ensuremath{-}x}{\mathrm{Sn}}_{x}$ layers is presented. A model is introduced for the Raman mode energy shift as a function of temperature, comprising thermal expansion of the strained lattice and anharmonic corrections. With support of x-ray diffraction, the model is calibrated on experimental data of epitaxial Ge grown on Si and ${\mathrm{Ge}}_{1\ensuremath{-}x}{\mathrm{Sn}}_{x}$ grown on Ge/Si, finding that the main difference between bulk and epitaxial layers is related to the anisotropic lattice expansion. The phonon anharmonicity and other parameters do not depend on dislocation defect density (in the range $7\ifmmode\times\else\texttimes\fi{}{10}^{6}--4\ifmmode\times\else\texttimes\fi{}{10}^{8}\phantom{\rule{0.16em}{0ex}}{\mathrm{cm}}^{\ensuremath{-}2}$) nor on alloy composition in the range 5--14 at.%. The strain-shift coefficient for the main model of Ge and for the Ge-Ge vibrational mode of ${\mathrm{Ge}}_{1\ensuremath{-}x}{\mathrm{Sn}}_{x}$ is weakly dependent on temperature and is around --500 ${\mathrm{cm}}^{\text{--}1}$. In ${\mathrm{Ge}}_{1\ensuremath{-}x}{\mathrm{Sn}}_{x}$, the composition-shift coefficient amounts to --100 ${\mathrm{cm}}^{\text{-1}}$, independent of temperature and strain.    

    

* Air quality and radiative impacts of downward-propagating sudden stratospheric warmings (SSWs)  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391375243
:TOPICS: Stratospheric Chemistry and Climate Change Impacts, Atmospheric Aerosols and their Impacts, Global Methane Emissions and Impacts
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/acp-24-1389-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391375243"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391375243"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391375243"))][Get cited by]]

OpenAlex: https://openalex.org/W4391375243 (Open access: True)
    
[[https://openalex.org/A5064359258][Ryan Williams]], [[https://openalex.org/A5038838249][Michaela I. Hegglin]], [[https://openalex.org/A5040485527][Patrick Jöckel]], [[https://openalex.org/A5061333345][Hella Garny]], [[https://openalex.org/A5042509503][Keith P. Shine]], Atmospheric Chemistry and Physics. 24(2)] 2024. https://doi.org/10.5194/acp-24-1389-2024 
     
Abstract. Sudden stratospheric warmings (SSWs) are abrupt disturbances to the Northern Hemisphere wintertime stratospheric polar vortex that can lead to pronounced regional changes in surface temperature and precipitation. SSWs also strongly impact the distribution of chemical constituents within the stratosphere, but the implications of these changes for stratosphere–troposphere exchange (STE) and radiative effects in the upper troposphere–lower stratosphere (UTLS) have not been extensively studied. Here we show, based on a specified-dynamics simulations from the European Centre for Medium-Range Weather Forecasts – Hamburg (ECHAM)/Modular Earth Submodel System (MESSy) Atmospheric Chemistry (EMAC) chemistry–climate model, that SSWs lead to a pronounced increase in high-latitude ozone just above the tropopause (>25 % relative to climatology), persisting for up to 50 d for the ∼50 % of events classified as downward propagating following Hitchcock et al. (2013). This anomalous feature in lowermost-stratospheric ozone is verified from ozone sonde soundings and using the Copernicus Atmospheric Monitoring Service (CAMS) atmospheric composition reanalysis product. A significant dipole anomaly (>± 25 %) in water vapour also persists in this region for up to 75 d, with a drying signal above a region of moistening, also evident within the CAMS reanalysis. An enhancement in STE leads to a significant 5 %–10 % increase in near-surface ozone of stratospheric origin over the Arctic, with a typical time lag between 20 and 80 d. The signal also propagates to mid-latitudes, leading to significant enhancements in UTLS ozone and also, with weakened strength, in free tropospheric and near-surface ozone up to 90 d after the event. In quantifying the potential significance for surface air quality breaches above ozone regulatory standards, a risk enhancement of up to a factor of 2 to 3 is calculated following such events. The chemical composition perturbations in the Arctic UTLS result in radiatively driven Arctic stratospheric temperature changes of around 2 K. An idealized sensitivity evaluation highlights the changing radiative importance of both ozone and water vapour perturbations with seasonality. Our results highlight that, whilst any background increase in near-surface ozone due to SSW-related stratosphere-to-troposphere (STT) transport is likely to be small, this could be of greater importance locally (e.g. mountainous regions more susceptible to elevated ozone levels). Accurate representation of UTLS composition (namely ozone and water vapour), through its effects on local temperatures, may also help improve numerical weather prediction forecasts on sub-seasonal to seasonal timescales.    

    

* Design of a Peculiar $\text{TM}_{35}$ Transverse Mode THz Extended Interaction Oscillator for Multibeam kW-Class Operation  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391249248
:TOPICS: Vacuum Electronic High Power Terahertz Sources, Superconducting Detectors for Astrophysical Observations, First-Principles Calculations for III-Nitride Semiconductors
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/tps.2024.3353492")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391249248"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391249248"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391249248"))][Get cited by]]

OpenAlex: https://openalex.org/W4391249248 (Open access: False)
    
[[https://openalex.org/A5075036820][Muhammad Shahab Sarwar]], [[https://openalex.org/A5007324907][Xinjian Niu]], [[https://openalex.org/A5017403535][Tianzhong Zhang]], [[https://openalex.org/A5022816638][Yinghui Liu]], IEEE Transactions on Plasma Science. None(None)] 2024. https://doi.org/10.1109/tps.2024.3353492 
     
A terahertz (THz) extended interaction oscillator (EIO) operating in a peculiar  ${\text{TM}_{35}}$  transverse mode and  ${2\pi}$  longitudinal mode has been proposed here. The aim is to generate a high-power THz radiation source with an enlarged cavity. This transverse  ${\text{TM}_{mn}}$  mode (with  $m=3$  ,  $n=5$  ) has an exceptionally large cross section which was unattainable with fundamental mode (i.e.,  ${\text{TM}_{11}}$  ) or even with higher order mode (HOM, i.e.,  ${\text{TM}_{31}}$  ) THz-EIOs. The overmoded structure (i.e.,  $n>1$  ) makes this mode most suitable for three-beam operation by maintaining a sufficiently large separation of 1.0 mm between adjacent beam tunnels. The analytical formalism for setting up an initial ladder-like RF circuit has been discussed along with the field distribution analysis of the  ${\text{TM}_{35}}$  mode. The stability analysis, which is crucial for this complex mode, shows a mode interval of 0.4 kV between the operating voltage ranges of the desired  ${2\pi}$  -mode and the nearest competing  ${\pi/16}$  -mode. Furthermore, an external circuit with an external quality-factor  $Q_e =$  333 has been designed for a stable operation. To demonstrate the effectiveness of this mode in yielding a kilowatt-class THz radiation source, a 0.368 THz  ${\text{TM}_{35}}$  three-beam EIO has been simulated both in computer simulation technology (CST)-particle-in-cell (PIC) and MAGIC-3D software. CST-PIC simulations predict an output power of 1.1 kW at a beam voltage of 18.1 kV at an overall beam current of 2.7 A (3  $\times$  0.9 A). Furthermore, the skin and ohmic losses have been incorporated. These results are validated by MAGIC-PIC simulations which predict an output power of 1.2 kW with an efficiency of 2.45%. This design requiring a relatively small power supply is a potential candidate for compact high-power portable THz systems for present and future applications.    

    

* Binary-Coded Frequency Reconfigurable Antenna for Cognitive Radio  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391095871
:TOPICS: Antenna Design and Applications, Optimization Techniques for Antenna Arrays, Wireless Body Area Networks in Healthcare
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/aespc59761.2023.10390483")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391095871"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391095871"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391095871"))][Get cited by]]

OpenAlex: https://openalex.org/W4391095871 (Open access: False)
    
[[https://openalex.org/A5040567048][Niten Kumar Panda]], [[https://openalex.org/A5077745290][Satish Kumar Gannamaneni]], [[https://openalex.org/A5005463892][Makireddi Ramana]], [[https://openalex.org/A5073104557][Sudhakar Sahu]], No host. None(None)] 2023. https://doi.org/10.1109/aespc59761.2023.10390483 
     
There is a need of antennas which can dynamically reconfigure themselves for cognitive radio (CR) application. This article illustrates an frequency reconfigurable antenna whose modes of operation follow a binary sequence. By using two positive-intrinsic-negative (PIN) diodes, electrical switching is used to toggle between the frequency bands. The possible combination of ‘ $\text{ON}=1$ ’ and ‘ $\text{OFF}=0$ ’ conditions of these two diodes are giving rise to 00,01,10 and 11 coded modes. These four modes covers the frequency band from 2.43 to 6.23 GHz. Ten different tunable frequencies within the above band with different modes of operation is achieved. The antenna is designed over a FR-4 substrate of thickness 1.6 mm with an overall dimension of $10\ \text{mm}\times 17\ \text{mm}$ .    

    

* Concurrent Dual-Mode Directional Coupler for Mode-Division Multiplexed Multidrop Substrate-Integrated Waveguide-Based Links  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391341693
:TOPICS: Microwave Engineering and Waveguides, Silicon Photonics Technology, Microwave Photonics and Optical Access Networks
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/tmtt.2024.3355891")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391341693"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391341693"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391341693"))][Get cited by]]

OpenAlex: https://openalex.org/W4391341693 (Open access: False)
    
[[https://openalex.org/A5036512321][Mohamed Elsawaf]], [[https://openalex.org/A5082629955][Constantine Sideris]], IEEE Transactions on Microwave Theory and Techniques. None(None)] 2024. https://doi.org/10.1109/tmtt.2024.3355891 
     
This article introduces a concurrent dual-mode directional coupler design for substrate-integrated waveguides (SIWs), which can independently excite the fundamental and second higher order modes (  $\text{TE}_{10}$  and  $\text{TE}_{20}$  ). We utilize this coupler to demonstrate the possibility of creating a multimode, multidrop communication link, which exploits mode orthogonality, enhancing the total channel capacity. To the best of our knowledge, this is the first realization of a concurrent multimode directional coupler in SIW technology. The coupling structure consists of four coupling nodes. Each one has two ports (one per mode), resulting in a total of eight ports. The coupling factors for the  $\text{TE}_{10}$  and  $\text{TE}_{20}$  modes are  $-$  10 dB each, allowing ten drop points along the SIW in a multidrop SIW link. The structure was fabricated using a Rogers Duroid 5880 substrate, achieving a 10-dB return loss (RL) bandwidth (BW) of more than 3.2 GHz (11.8–15 GHz) and 3.5 GHz (  $10$  –13.5 GHz) for the fundamental and second modes, respectively, corresponding to 1.7 GHz of BW for concurrent mode division multiplexing. The measured isolation between the two channels is more than 30 dB across the entire band, and the insertion loss (IL) is 1.0 and 1.5 dB, respectively. The measurement results agree well with electromagnetic simulations.    

    

* A Sub-$\mu$W Energy-Performance-Aware IoT SoC With a Triple-Mode Power Management Unit for System Performance Scaling, Fast DVFS, and Energy Minimization  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391020439
:TOPICS: Low-Power VLSI Circuit Design and Optimization, Memristive Devices for Neuromorphic Computing, Parallel Computing and Performance Optimization
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/jssc.2024.3350449")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391020439"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391020439"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391020439"))][Get cited by]]

OpenAlex: https://openalex.org/W4391020439 (Open access: False)
    
[[https://openalex.org/A5057062465][Xinjian Liu]], [[https://openalex.org/A5025461780][Sumanth Kamineni]], [[https://openalex.org/A5053763790][Jacob Breiholz]], [[https://openalex.org/A5080557997][Benton H. Calhoun]], [[https://openalex.org/A5037325164][Shuo Li]], IEEE Journal of Solid-state Circuits. None(None)] 2024. https://doi.org/10.1109/jssc.2024.3350449 
     
This article presents an ultra-low-power (ULP) Internet-of-Things (IoT) system-on-chip (SoC) using a triple-mode power management unit (PMU) to achieve self-adaptive power–performance scaling and energy-minimized operation. The proposed PMU comprises three modes: energy-aware (EA) mode, performance-aware (PA) mode, and minimum energy point (MEP) tracking mode. By controlling a microprocessor with the three modes, the SoC can adaptively scale its frequency and supply voltage based on either the input energy availability or the task priority. To achieve robust and rapid mode transitions, the SoC adopts fast dynamic voltage and frequency scaling (DVFS) and fast load transient response (FLTR) through asynchronous control. For energy-minimized operation, a sub-nW constant-energy-cycle (CEC) algorithm keeps the microprocessor operating at the MEP with a 0.026-mm  $^{2}$  area overhead. In addition, the on-chip integration of a bias generator (BG), clock (CLK), and power-on-reset block empowers the SoC to be a fully self-contained system. Fabricated in 65-nm CMOS, measurement results show that the SoC has a minimum power consumption of 194.3 nW at 180 Hz. The proposed PMU achieves 5.2-nW quiescent power and 92.6% peak efficiency while maintaining  $>$  80% efficiency from 190 nW to 3 mW. The MEP tracking (MEPT) circuits achieve  $<$  2.3% energy per cycle error and  $<$  18 mV voltage tracking error. The measured quiescent power of the MEPT circuits in the idle mode is 379 pW, which only accounts for 0.19% of the total system power. Measurements of the triple-mode transitions show that this SoC is well suited for resource-constrained IoT applications.    

    

* A D-Band Substrate Integrated Waveguide Bandpass Filter Based on Silicon Carbide Technology  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391490572
:TOPICS: Microwave Engineering and Waveguides, Silicon Photonics Technology, Optical Interconnect Technologies
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/imws-amp57814.2023.10381150")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391490572"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391490572"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391490572"))][Get cited by]]

OpenAlex: https://openalex.org/W4391490572 (Open access: False)
    
[[https://openalex.org/A5007801259][Zhenghai Luo]], [[https://openalex.org/A5053863544][Kang Zhou]], No host. None(None)] 2023. https://doi.org/10.1109/imws-amp57814.2023.10381150 
     
In this paper, a third-order bandpass filter (BPF) operating at D-band (110–170 GHz) based on substrate integrated waveguide (SIW) technology is designed on a $100-\text{um}$ -thick silicon carbide (SiC) substrate. The passband is constructed by two TE 101 mode-based SIW rectangular cavities (cavity 1 and 3) coupled with a TE 103 mode-based over-moded SIW rectangular cavity (cavity 2). With cavity 2 is arranged adwisely and operated with TE 103 mode, a larger resonant cavity size denotes a bigger coupling window size could be realized between cavity 2 and the other cavities, thus enabling the designed BPF to perform with a wider bandwidth and a higher unloaded quality factor. Moreover, thanks to the cross coupling generated between two TE 101 mode-based SIW resonant cavities, a transmission zero (TZ) is successfully produced at the upper stopband that improving the frequency-selectivity. The finite-element full-wave electromagnetic software is utilized to simulate the designed BPF. To validate the design, a BPF is designed and simulated with a passband operating at 140 GHz, featuring a 9% 3-dB fractional bandwidth (FBW), a 1.04 dB insert loss (IL), and a 20 dB return loss (RL), and the synthesized responses are found to be in good agreement with the simulated characteristics. These results demonstrate the exceptional performance of SiC-based SIW filters and highlight the promising potential of SIWs in the design of filters, antennas, and other circuit elements on SiC-based chips.    

    

* A Terahertz-Band Rectangular TE$_{\text{10}}$ to Circular TE$_{\text{01}}$ Mode Converter  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391406911
:TOPICS: Vacuum Electronic High Power Terahertz Sources, Terahertz Technology and Applications, Superconducting Detectors for Astrophysical Observations
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/ted.2024.3357435")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391406911"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391406911"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391406911"))][Get cited by]]

OpenAlex: https://openalex.org/W4391406911 (Open access: False)
    
[[https://openalex.org/A5055985336][Guoxiang Shu]], [[https://openalex.org/A5022292150][Xu-Kai Xie]], [[https://openalex.org/A5042640484][Junchen Ren]], [[https://openalex.org/A5077786342][Guangxin Lin]], [[https://openalex.org/A5006026116][Qi Li]], [[https://openalex.org/A5013610293][Jujian Lin]], [[https://openalex.org/A5004292276][Jiacai Liao]], [[https://openalex.org/A5019535751][Jingcong He]], [[https://openalex.org/A5081024667][Biaogang Xu]], [[https://openalex.org/A5083891468][Zhiwei Chang]], [[https://openalex.org/A5064026992][Huabi Yin]], [[https://openalex.org/A5037135597][Guo Liu]], [[https://openalex.org/A5061585999][Cunjun Ruan]], [[https://openalex.org/A5030053520][Wenlong He]], IEEE Transactions on Electron Devices. None(None)] 2024. https://doi.org/10.1109/ted.2024.3357435 
     
The design, fabrication, and experimental measurement of a broadband and compact TE  $^{\Box}_{\text{10}}$  –TE  $^{\circ}_{\text{01}}$  (symbols  $\Box$   $^{^{^{}}}$  and  $\circ $  represent the rectangular and circular waveguides, respectively) mode converter is presented in this article. The proposed mode converter consists of three components, including a TE  $^{\Box}_{\text{10}}$  –TE  $^{\Box}_{\text{20}}$  mode converter based on a two-way H-T junction power divider, a TE  $^{\Box}_{\text{20}}$  –TE  $^{+}_{\text{22}}$  mode converter with variable cross-shaped waveguide, and a TE  $^{+}_{\text{22}}$  –TE  $^{\circ}_{\text{01}}$  mode converter. Two distinct design schemes have been employed for the first part of the TE  $^{\Box}_{\text{10}}$  –TE  $^{\circ}_{\text{01}}$  mode converter, which are based on two-way  $^{^{^{}}}$  H-T junction power dividers with a path difference of odd times half-waveguide wavelength (Scheme 1) and a 180  $^{\circ}$  phase shifter (Scheme 2), respectively. This mode converter is highlighted by the significant advantage of high conversion efficiency over a wide bandwidth with a relatively easy-to-fabricate structure, which is evidenced by the measurement of two identical back-to-back joined mode converters based on Scheme 1. Measurement results matched with simulation ones within reasonable accuracy, which predicted that a 1-dB transmission bandwidth of  $\sim$  56.7 GHz was obtained. Meanwhile, the reflection coefficient S  $_{\text{11}}$  was below  $-$  13.2 dB over that bandwidth.    

    

* A Dual-Core Quad_Mode VCO with Reconfigurable Magnetic Coupling Mode and Negative-Resistive Mode Switch  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391183647
:TOPICS: Radio Frequency Integrated Circuit Design, Quantum Dot Devices and Semiconductors, Superconducting Detectors for Astrophysical Observations
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/asicon58565.2023.10396169")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391183647"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391183647"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391183647"))][Get cited by]]

OpenAlex: https://openalex.org/W4391183647 (Open access: False)
    
[[https://openalex.org/A5025612238][Xiangjian Kong]], [[https://openalex.org/A5024729322][Ding Qiu]], [[https://openalex.org/A5087562363][Mingchao Jian]], [[https://openalex.org/A5014842718][Chunbing Guo]], [[https://openalex.org/A5086469511][Kai‐Da Xu]], No host. None(None)] 2023. https://doi.org/10.1109/asicon58565.2023.10396169 
     
This paper proposed a dual-core quad-mode with re-configurable magnetic coupling mode and negative-resistive mode switch VCO implemented with 65nm CMOS technology. By switching the Even_SW, Odd_SW, SW1, and SW2, the VCO can operate in a different magnetic coupling coefficient Mode causing different oscillation frequency bands. A post-simulation shows the way reconfiguring the coupling coefficient can improve the tuning range up to 91.8% and consume about 15mW achieving the best FoM and FoM T of 185dBc/Hz and 203.3dBc/Hz respectively. Besides the negative-resistive mode switch is proposed to break the trade-off between the parasitic capacitor and phase noise of traditional positive-resistive switch without mode ambiguity.    

    

* Research on Wide Output Step-Down Converter Based on One Cycle Control  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391217590
:TOPICS: Power Electronics and Conversion Systems
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/peas58692.2023.10394779")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391217590"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391217590"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391217590"))][Get cited by]]

OpenAlex: https://openalex.org/W4391217590 (Open access: False)
    
[[https://openalex.org/A5093785758][Hong Yongbin]], [[https://openalex.org/A5078590624][Qiang Zhang]], [[https://openalex.org/A5093785759][Huang Haitai]], [[https://openalex.org/A5078657701][Gu Ao]], No host. None(None)] 2023. https://doi.org/10.1109/peas58692.2023.10394779 
     
When the classical buck converter is applied with large step-down ratio, the operating duty cycle is too small, which leads to the decrease of conversion efficiency and even affects the control stability. In this paper, a wide output step-down converter with variable operating mode is proposed. According to the relationship between input and output voltage, the converter toggles between buck and D 2 buck mode, so that the operating duty cycle can be kept in a reasonable range. Based on one cycle control, a smooth mode switch control scheme is proposed. The key parameters of the converter with 100V input and $\mathbf{5}\sim \mathbf{50}\mathbf{V}$ output are designed. The feasibility of the converter and control scheme are verified by psim simulation platform. The steady-state duty cycle is maintained between 0.22 and 0.54.    

    

* A Compact Broadband Circularly Polarized Antenna with Novel Tilt Fences for GNSS Applications  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391468129
:TOPICS: Antenna Design and Applications, Optimization Techniques for Antenna Arrays, Microwave Engineering and Waveguides
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/lawp.2024.3361682")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391468129"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391468129"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391468129"))][Get cited by]]

OpenAlex: https://openalex.org/W4391468129 (Open access: False)
    
[[https://openalex.org/A5050748517][Rui Wu]], [[https://openalex.org/A5013500379][Jianhong Lin]], [[https://openalex.org/A5011012876][Wen Guojun]], [[https://openalex.org/A5050076555][Shuting Cai]], [[https://openalex.org/A5035519477][Fu‐Chang Chen]], IEEE Antennas and Wireless Propagation Letters. None(None)] 2024. https://doi.org/10.1109/lawp.2024.3361682 
     
A compact broadband circularly polarized antenna with novel tilt fences for GNSS applications is proposed in this paper. The proposed antenna consists of Y-shaped feedlines with vacant-quarter rings, parasitic patches, ground, and novel tilt fences. Good impedance matching as well as circular polarization (CP) characteristics are achieved with novel tilt fences. New resonance modes and CP modes are introduced at low frequencies through novel tilt fences, which is equivalent to antenna miniaturization. The proposed antenna with four CP modes is fabricated using simple PCB technology and has a compact dimension of 0.29λ 0 *0.29λ 0 *0.18λ 0 (λ 0 is the wavelength of the center frequency). Based on the measured results, a wide impedance bandwidth (IBW) and axial ratio bandwidth (ARBW) are achieved. The -15 dB IBW can cover 1.07-1.98 GHz, and the 3-dB ARBW is 61.5% from 1.07-2.02 GHz. In addition, the antenna has a wide overlap bandwidth of 1.07-1.98 GHz (59.7%). This simple and compact CP antenna has good potential in GNSS applications.    

    

* A Multiband Standing Wave Oscillator With Wave Pattern Tailoring for Selective Mode Excitation  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391092540
:TOPICS: Vacuum Electronic High Power Terahertz Sources, Acoustic Wave Biosensors and Thin Film Resonators
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/lmwt.2024.3351133")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391092540"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391092540"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391092540"))][Get cited by]]

OpenAlex: https://openalex.org/W4391092540 (Open access: False)
    
[[https://openalex.org/A5001920492][Zehui Kang]], [[https://openalex.org/A5028306581][Ming-Feng Yang]], [[https://openalex.org/A5006541988][Jun Yin]], [[https://openalex.org/A5028085778][Liang Wu]], IEEE Microwave and Wireless Technology Letters. None(None)] 2024. https://doi.org/10.1109/lmwt.2024.3351133 
     
A wave pattern tailoring (WPT) technique performing selective mode excitation is proposed to enable stable multiband operation for standing wave oscillators (SWOs). Multiple standing-wave modes are inherently allowed in an SWO; however, generally only one mode is utilized, while the others are disregarded. To exploit the multimode nature, WPT based on antinode stimulating and terminal reflection switching is proposed and analyzed. By varying the configurations, different standing-wave modes can be activated and stabilized, resulting in multiple oscillation bands. Implemented in a 65-nm CMOS process, the SWO with the proposed WPT technique operates in seven bands centered at 9.3, 22.3, 26.4, 30.4, 41.1, 51.7, and 55.5 GHz, while consuming 9.5–19.8 mW from a 1-V supply. The phase noise measures from  $-$  117.7 to  $-$  129.2 dBc/Hz at 10-MHz offset, corresponding to figure-of-merit (FoM) from 177.6 to 182.3 dBc/Hz in all bands. The SWO occupies a core area of 0.106 mm  $^{2}$  excluding pads.    

    

* Dual-Band Structure Reused Aperture-Sharing Antenna With Low Sidelobe and High Gain for 5G Communication  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391097022
:TOPICS: Microwave Engineering and Waveguides, Antenna Design and Applications, Millimeter Wave Communications for 5G and Beyond
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/lawp.2024.3356614")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391097022"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391097022"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391097022"))][Get cited by]]

OpenAlex: https://openalex.org/W4391097022 (Open access: False)
    
[[https://openalex.org/A5072240312][Chuang Wang]], [[https://openalex.org/A5079587680][Wenquan Cao]], [[https://openalex.org/A5006786543][Wenyu Ma]], [[https://openalex.org/A5026959455][Cong Li]], [[https://openalex.org/A5052926836][Ju Jing]], IEEE Antennas and Wireless Propagation Letters. None(None)] 2024. https://doi.org/10.1109/lawp.2024.3356614 
     
A dual-band structure reused aperture-sharing antenna is proposed in this letter. The mm-Wave substrate integrated waveguide (SIW) slotted cavity backed antenna array, operating in TE440 mode, is embedded into the microwave annular-ring patch antenna, operating in TM12 mode, to share the radiation aperture. Furthermore, the SIW slot antenna radiator is reused as the field regulator for the microwave antenna, effectively canceling out the electric field opposite to the inner annular-ring patch. As a result, the sidelobe caused by the high-order TM12 mode in the annular-ring patch antenna is successfully suppressed. Experimental results show that the operating bandwidth covers the 5G microwave band (3.4–3.6 GHz) and mm-Wave band (26.5–29.5 GHz). The measured gain reaches 10.65 dBi and 18.5 dBi, respectively, while maintaining sidelobe levels below -18 dB. Furthermore, the antenna profile is only 0.012 λ 0 ( λ 0 is the wavelength in free space at low frequency). Therefore, a compact microwave and mm-Wave dual-band high gain shared-aperture antenna is realized, which provides a promising candidate for 5G communication applications.    

    

* A 115-325MHz Wideband Analog Baseband with 0.5dB-Step Variable Gain Amplifier and Six-order Reconfigurable Gm-C Lowpass Filter  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391183775
:TOPICS: Analog Circuit Design for Biomedical Applications, Radio Frequency Integrated Circuit Design, Silicon Photonics Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/asicon58565.2023.10396077")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391183775"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391183775"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391183775"))][Get cited by]]

OpenAlex: https://openalex.org/W4391183775 (Open access: False)
    
[[https://openalex.org/A5088168485][Wenbao Zuo]], [[https://openalex.org/A5085624118][Wei Li]], [[https://openalex.org/A5088122376][Yun Wang]], [[https://openalex.org/A5059040010][Yue Lin]], [[https://openalex.org/A5030822792][Hongtao Xu]], No host. None(None)] 2023. https://doi.org/10.1109/asicon58565.2023.10396077 
     
This paper presents a wideband analog baseband (ABB) chain with precise gain step and tunable cutoff frequency in a 1.2V 40nm CMOS process. The chip has a core area of 0.21mm 2 . A variable gain amplifier (VGA) realized in super source follower topology is designed to implement precise gain step. Besides, a 6 th -order lowpass filter (LPF) realized in Gm-C topology is designed to implement high and tunable cutoff frequency. The design achieves a maximum gain of 43.3dB and a dynamic gain range of 20.5dB with 0.5dB gain step. Meanwhile, the cutoff frequency can be tuned from 115MHz to 325MHz under 8 different bandwidth modes. The OP1dB is 5.5dBm and input referred noise (IRN) is 4.45 ~ 7.07nV/√Hz in band. The proposed analog baseband chain consumes 27 ~ 50mA in different gain modes and bandwidth modes under supply of 1.2V.    

    

* Disturbance Attenuation in the Euler–Bernoulli Beam with Viscous and Kelvin–Voigt Damping via Piezoelectric Actuators  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391020620
:TOPICS: Analysis and Control of Distributed Parameter Systems, Morphing Aircraft Technology, Modeling and Control of Port-Hamiltonian Systems
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/cdc49753.2023.10383762")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391020620"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391020620"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391020620"))][Get cited by]]

OpenAlex: https://openalex.org/W4391020620 (Open access: False)
    
[[https://openalex.org/A5066639695][Anton Selivanov]], [[https://openalex.org/A5007830129][Emilia Fridman]], No host. None(None)] 2023. https://doi.org/10.1109/cdc49753.2023.10383762 
     
We design a state-feedback controller, applied via piezoelectric actuators, that suppresses the effect of a distributed disturbance in the Euler-Bernoulli beam with viscous and Kelvin-Voigt damping. The controller is designed to improve performance on a finite number of modes. Its effect on the remaining (infinitely many) modes is analysed by constructing an appropriate Lyapunov functional, whose properties are guaranteed by the feasibility of linear matrix inequalities (LMIs). The LMIs allow us to design suitable controller gain and estimate the induced $L^2$ gain. A numerical example demonstrates how this modal decomposition approach leads to a controller that significantly reduces the $L^2$ gain.    

    

* Development of InGaAs/AlGaAsSb Geiger Mode Avalanche Photodiodes  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391326582
:TOPICS: Infrared Detector Technologies, Quantum Dot Devices and Semiconductors, Time-of-Flight Imaging Techniques
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/ted.2024.3354698")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391326582"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391326582"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391326582"))][Get cited by]]

OpenAlex: https://openalex.org/W4391326582 (Open access: False)
    
[[https://openalex.org/A5039759925][Jonathan Taylor-Mew]], [[https://openalex.org/A5043780060][Xiao Collins]], [[https://openalex.org/A5029615314][B. R. White]], [[https://openalex.org/A5006038212][Chee Hing Tan]], [[https://openalex.org/A5045572558][Jo Shien Ng]], IEEE Transactions on Electron Devices. None(None)] 2024. https://doi.org/10.1109/ted.2024.3354698 
     
Near-infrared linear mode Al  $_{\text{0.85}}$  Ga  $_{\text{0.15}}$  As  $_{\text{0.56}}$  Sb  $_{\text{0.44}}$  avalanche photodiodes (APDs) exhibit excellent temperature stability, potentially simplifying Geiger mode operation. We have carried out the first experimental evaluation of In  $_{\text{0.53}}$  Ga  $_{\text{0.47}}$  As/Al  $_{\text{0.85}}$  Ga  $_{\text{0.15}}$  As  $_{\text{0.56}}$  Sb  $_{\text{0.44}}$  APDs in Geiger mode. Characterization on multiple devices included temperature-dependent dark current, avalanche multiplication, dark count rate (DCR), afterpulsing, and single photon detection efficiency (SPDE). The temperature coefficient of breakdown voltage extracted from avalanche multiplication data was 13.5  $\text{mV}\cdot\text{K}^{-\text{1}}$  , much lower than InGaAs/InP Geiger mode APDs, reducing changes in operation voltage and offering possible protection from high optical power thermal attack in communication systems. At 200 K, SPDE were 5%–16% with DCR of 1–20  $\text{Mc}\cdot\text{s}^{-\text{1}}$  , comparable to InAlAs and early InP-based Single Photon APDs. The afterpulsing at 200 K was negligible for hold-off time  $>$  50  $\mu$  s (reducing to 5  $\mu$  s at 250 K). These are similar to the performance of InGaAs/InAlAs and some InGaAs/InP Geiger mode APDs. The data reported in this article is available from the ORDA digital repository (https://doi.org/10.15131/shef.data.24125721).    

    

* Classifier Design for Decentralised Sensing with Digital Communication  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391022142
:TOPICS: Decentralized Inference in Wireless Sensor Networks, Particle Filtering and Nonlinear Estimation Methods, Optimizing Information Freshness in Communication Networks
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/cdc49753.2023.10384268")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391022142"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391022142"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391022142"))][Get cited by]]

OpenAlex: https://openalex.org/W4391022142 (Open access: False)
    
[[https://openalex.org/A5029346030][Gaurav Garg]], [[https://openalex.org/A5045214135][Harshad Khadilkar]], [[https://openalex.org/A5069273068][Ankur A. Kulkarni]], [[https://openalex.org/A5059539778][Aditya A. Paranjape]], No host. None(None)] 2023. https://doi.org/10.1109/cdc49753.2023.10384268 
     
We consider the problem of classifying the operating mode of a plant, using distributed sensors and a digital channel. The abstract problem is formulated using simplifications, where the plant only has two modes, the sensors have independent and identically distributed (but possibly mode-dependent) measurement noise, and a noise-less digital communication channel. The objective is to design a combined distributed digitisation (quantisation) and centralised classification strategy that maximises accuracy while observing $n$ messages, each of which can take $k$ unique values. Even in this simplistic scenario, our analysis shows that (i) the optimal decision boundaries even in the fully observable (analog) case depend strongly on the assumptions about measurement noise, (ii) as a result, the classification strategy selection is non-trivial, and (iii) the distributed quantisation algorithm design also has a strong influence on the final classification accuracy. We support the analytical arguments by empirical simulation experiments.    

    

* Measurement of plasma density profile for edge plasma on J-TEXT Tokamak  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391307661
:TOPICS: Plasma Physics and Fusion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/ciycee59789.2023.10401796")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391307661"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391307661"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391307661"))][Get cited by]]

OpenAlex: https://openalex.org/W4391307661 (Open access: False)
    
[[https://openalex.org/A5075827151][Zhao Jin]], [[https://openalex.org/A5026151938][Zhoujun Yang]], No host. None(None)] 2023. https://doi.org/10.1109/ciycee59789.2023.10401796 
     
In tokamak discharges, the density distribution of the plasma is one of the most important parameters. In recent years, it has been found that the edge parameters of the plasma play a crucial role in the confinement and stability of the plasma. In order to obtain high spatiotemporal resolution information on the density distribution evolution of the edge plasma, a K-band (18-26.5 GHz) ordinary mode (O-mode) microwave reflectometer system has been developed on the J-TEXT Tokamak. This reflectometer system can measure densities in the range of (0.4-0.8) × 10 19 m -3 with a time resolution up to 10 microseconds. In the recent experiment, the system has successfully acquired the evolution of the plasma edge density.    

    

* HTS Microstrip Resonators Excited on WGM and Fundamental Mode: Q-Factor  :Emacs_and_org_mode:
:PROPERTIES:
:ID: https://openalex.org/W4391248573
:TOPICS: Development of Superconducting Magnets for Particle Accelerators and Fusion Reactors, High-Temperature Superconductivity, Accelerator Technology and Superconducting Cavities
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1109/tasc.2024.3358783")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391248573"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391248573"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391248573"))][Get cited by]]

OpenAlex: https://openalex.org/W4391248573 (Open access: False)
    
[[https://openalex.org/A5040942650][А. А. Barannik]], [[https://openalex.org/A5039151645][I. А. Protsenko]], [[https://openalex.org/A5048137677][S. А. Vitusevich]], [[https://openalex.org/A5031827976][Kostiantyn Torokhtii]], [[https://openalex.org/A5043977854][N. T. Cherpak]], IEEE Transactions on Applied Superconductivity. None(None)] 2024. https://doi.org/10.1109/tasc.2024.3358783 
     
For effective technological implementation of HTS-based microstrip resonators, it is of practical interest to study and to compare the dissipative properties of two types of such resonators: excited on whispering gallery modes (WGM) and resonators excited at the fundamental frequency. The analysis was performed in the frequency range from 1.5 GHz to 40 GHz. By using numerical simulation of partial Q-factors it is shown that the value of Q-factor at a temperature of 77 K and lower for the YBa 2 Cu 3 O 7- δ - based WGM resonator  without housing  exceeds the Q-factor for the resonator exited with a fundamental mode  with housing  in the frequency range from 1.5 to 35 GHz. This is an important practical result. The experimental data and the results of numerical simulations are mutually consistent. In the millimeter wavelength range, when the dimensions of traditional resonators become unacceptably small, it will be more convenient to use microstrip WGM resonators.    

    
