#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Fri May 10 01:04:57 2024

Found 2 results from 2024-05-03 to 2024-05-10
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

* Enhancing sulfur resistance of oxides in carbon monoxide oxidation by a high‐entropy‐stabilized strategy  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4396706305
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aic.18470")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396706305"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396706305"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396706305"))][Get cited by]]

OpenAlex: https://openalex.org/W4396706305 (Open access: False)
    
[[https://openalex.org/A5029370723][Shengyu Du]], [[https://openalex.org/A5005363741][Pengfei Zhang]], AIChE journal. None(None)] 2024. https://doi.org/10.1002/aic.18470 
     
Abstract Industrial chemical processes require sulfur‐resistant catalysts, which reduce catalyst replacement costs and simplify process operations. Herein, a high‐entropy‐stabilized strategy was put forward for sulfur‐resistant catalysis. A spinel high entropy (Zn 0.2 Mg 0.2 Cu 0.2 Mn 0.2 Co 0.2 Al 2 O 4 ) was introduced by ball milling process with aluminum isopropoxide as the main precursor. Zn 0.2 Mg 0.2 Cu 0.2 Mn 0.2 Co 0.2 Al 2 O 4 possessed a high surface area of 171.2 m 2 g −1 , higher than typical high‐entropy oxides (HEOs). The high‐entropy spinel catalyst exhibited better SO 2 ‐resistance performance in the oxidation of carbon monoxide, better than the simple oxides. The SO 2 ‐resistance of Zn 0.2 Mg 0.2 Cu 0.2 Mn 0.2 Co 0.2 Al 2 O 4 was primarily improved by reinforcing the stability of the oxide using a high‐entropy structure to decrease the absorption of SO 2 on its surface. Any adsorbed SO 2 on the surface of the HEO was then selectively trapped by sacrificial metal ions with stronger electron‐withdrawing ability, protecting the active center (Cu 2+ , Co 2+ ) from poisoning. This work reveals the significance of high‐entropy structures in sulfur resistance.    

    

* Role of Oxygen Vacancy in High-entropy Cu1Zn1Al0.5Ce5Zr0.5Ox for CO2 Hydrogenation Reaction  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4396655940
:TOPICS: High-Entropy Alloys: Novel Designs and Properties, Synthesis and Properties of Cemented Carbides, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcata.2024.119781")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396655940"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396655940"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396655940"))][Get cited by]]

OpenAlex: https://openalex.org/W4396655940 (Open access: False)
    
[[https://openalex.org/A5020561814][Junting Li]], [[https://openalex.org/A5087073100][Xin Yuan]], [[https://openalex.org/A5062691210][Fuping Tian]], [[https://openalex.org/A5054627070][Min Wang]], [[https://openalex.org/A5001755416][Tao Hu]], [[https://openalex.org/A5067863644][Guang Xiong]], [[https://openalex.org/A5044936528][Xiang Wang]], Applied catalysis. A, General. None(None)] 2024. https://doi.org/10.1016/j.apcata.2024.119781 
     
High-entropy oxides (HEOs) have garnered significant attention in catalysis due to their excellent redox properties and superior stability. In this study, we prepared and investigated a high-entropy oxide, Cu1Zn1Al0.5Ce5Zr0.5Ox, to elucidate the impact of oxygen vacancy density on the CO2 hydrogenation reaction. Comparisons were made with binary or ternary solid solutions composed of the same cations present in this HEO, and possessing the same phase structure. The HEO exhibits a higher surface oxygen vacancy density as evidenced by Raman spectroscopy and XPS. The increased number of oxygen vacancies significantly increases the active sites and enhances the strength for CO2 adsorption. Combined with kinetic analysis, it is suggested that the enhanced CO2 adsorption leads to improved CO2 conversion on the HEO. Moreover, the formation of oxygen vacancies facilitates H2 dissociation and supply, which is pivotal for methanol formation on the HEO. The stability of the HEO Cu1Zn1Al0.5Ce5Zr0.5Ox surpasses that of the medium entropy oxide, showing no significant deactivation after 100 hours of reaction.    

    
