#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Sat May  4 01:03:28 2024

Found 3 results from 2024-04-27 to 2024-05-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

* High-entropy oxide based biomimetic catalysis system enables robust oxidative desulfurization with an excellent regeneration ability  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4396508534
:TOPICS: Desulfurization Technologies for Fuels, Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.127729")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396508534"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396508534"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396508534"))][Get cited by]]

OpenAlex: https://openalex.org/W4396508534 (Open access: False)
    
[[https://openalex.org/A5021686620][Haoyi Lin]], [[https://openalex.org/A5015341679][Bo Shen]], [[https://openalex.org/A5047098061][Lixin Xue]], [[https://openalex.org/A5062410995][Xueyun Wang]], [[https://openalex.org/A5013955092][Ting Su]], [[https://openalex.org/A5052219648][Kaixuan Yang]], [[https://openalex.org/A5069349716][Hongying Lü]], [[https://openalex.org/A5058780747][Zhiguo Zhu]], Separation and purification technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.127729 
     
No abstract    

    

* Scalable Synthesis Methods for High‐Entropy Nanoparticles  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4395683868
:TOPICS: High-Entropy Alloys: Novel Designs and Properties, Laser Ablation Synthesis of Nanoparticles, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-04-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aesr.202300297")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395683868"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395683868"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395683868"))][Get cited by]]

OpenAlex: https://openalex.org/W4395683868 (Open access: True)
    
[[https://openalex.org/A5011096702][Timothy G. Ritter]], [[https://openalex.org/A5033543881][Samhita Pappu]], [[https://openalex.org/A5065515481][Reza Shahbazian‐Yassar]], Advanced energy and sustainability research. None(None)] 2024. https://doi.org/10.1002/aesr.202300297 
     
High‐entropy materials (HEMs) represent a revolutionary class of materials that have garnered significant attention in the field of materials science due to their extraordinary properties in diverse fields of applications such as catalysis and electrochemistry. The past decade has witnessed a substantial increase in the study of these materials, exploring new synthesis routes and compositions. What began as the synthesis of high‐entropy alloys has expanded to encompass several classes of HEMs such as oxides, hydroxides, sulfides, nitrides, and carbides, among others. Several synthesis methods have been developed to produce these materials. This review therefore highlights the fundamental concepts of HEMs, including their core effects, with a major emphasis on their scalable synthesis routes. The advantages and drawbacks of these methods are also discussed. As HEMs transition from the lab to large‐scale production, there is a growing need for cost‐effective and scalable synthesis methods with high material yield suitable for a variety of applications like hydrogen storage, catalysis, batteries, supercapacitors, and fuel cells. Hence, this review serves as an introduction to scalable synthesis routes based on crystal structure, desired elements, synthesis times, and equipment costs.    

    

* Evolution of Oxygen Vacancy Sites in Ceria-Based High-Entropy Oxides and Their Role in N2 Activation  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4396215458
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-04-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.3c16521")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396215458"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396215458"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396215458"))][Get cited by]]

OpenAlex: https://openalex.org/W4396215458 (Open access: True)
    
[[https://openalex.org/A5062810492][Omer Elmutasim]], [[https://openalex.org/A5000917380][Aseel Gamal Suliman Hussien]], [[https://openalex.org/A5031495778][Abhishek Sharan]], [[https://openalex.org/A5031015784][Sara AlKhoori]], [[https://openalex.org/A5014177788][Michalis A. Vasiliades]], [[https://openalex.org/A5036320221][Inas Taha]], [[https://openalex.org/A5026385956][Seok‐Jin Kim]], [[https://openalex.org/A5073269272][Messaoud Harfouche]], [[https://openalex.org/A5046522347][Abdul‐Hamid Emwas]], [[https://openalex.org/A5037684463][Dalaver H. Anjum]], [[https://openalex.org/A5091258830][Angelos M. Efstathiou]], [[https://openalex.org/A5005092754][Cafer T. Yavuz]], [[https://openalex.org/A5017583868][Nirpendra Singh]], [[https://openalex.org/A5008059915][Kyriaki Polychronopoulou]], ACS applied materials & interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.3c16521 
     
In this work, a relatively new class of materials, rare earth (RE) based high entropy oxides (HEO) are discussed in terms of the evolution of the oxygen vacant sites (Ov) content in their structure as the composition changes from binary to HEO using both experimental and computational tools; the composition of HEO under focus is the CeLaPrSmGdO due to the importance of ceria-related (fluorite) materials to catalysis. To unveil key features of quinary HEO structure, ceria-based binary CePrO and CeLaO compositions as well as SiO2, the latter as representative nonreducible oxide, were used and compared as supports for Ru (6 wt % loading). The role of the Ov in the HEO is highlighted for the ammonia production with particular emphasis on the N2 dissociation step (N2(ads) → Nads) over a HEO; the latter step is considered the rate controlling one in the ammonia production. Density functional theory (DFT) calculations and 18O2 transient isotopic experiments were used to probe the energy of formation, the population, and the easiness of formation for the Ov at 650 and 800 °C, whereas Synchrotron EXAFS, Raman, EPR, and XPS probed the Ce-O chemical environment at different length scales. In particular, it was found that the particular HEO composition eases the Ov formation in bulk, in medium (Raman), and in short (localized) order (EPR); more Ov population was found on the surface of the HEO compared to the binary reference oxide (CePrO). Additionally, HEO gives rise to smaller and less sharp faceted Ru particles, yet in stronger interaction with the HEO support and abundance of Ru-O-Ce entities (Raman and XPS). Ammonia production reaction at 400 °C and in the 10-50 bar range was performed over Ru/HEO, Ru/CePrO, Ru/CeLaO, and Ru/SiO2 catalysts; the Ru/HEO had superior performance at 10 bar compared to the rest of catalysts. The best performing Ru/HEO catalyst was activated under different temperatures (650 vs 800 °C) so to adjust the Ov population with the lower temperature maintaining better performance for the catalyst. DFT calculations showed that the HEO active site for N adsorption involves the Ov site adjacent to the adsorption event.    

    
