#+filetags: high-entropy-oxides
#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Sun Jan 21 00:45:19 2024

Found 2 results from 2024-01-07 to 2024-01-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

** Strain‐rich high‐entropy perovskite oxide of (La0.8Sr0.2)(Mn0.2Fe0.2Cr0.2Co0.2Ni0.2)O3 for durable and effective catalysis of oxygen redox reactions in lithium‐oxygen battery   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/bte2.20230053")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390738391"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390738391"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390738391"))][Get cited by]]

OpenAlex: https://openalex.org/W4390738391 (Open access: True)
    
[[https://openalex.org/A5011426914][Zhanpeng Liu]], [[https://openalex.org/A5024495280][Haoyang Xu]], [[https://openalex.org/A5055053389][Xinxiang Wang]], [[https://openalex.org/A5075176253][Guilei Tian]], [[https://openalex.org/A5027390507][Dongxing Du]], [[https://openalex.org/A5046532572][Chaozhu Shu]], No host. None(None)] 2024. https://doi.org/10.1002/bte2.20230053  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/bte2.20230053][pdf]])
     
Abstract Despite their great promise as high‐energy‐density alternatives to Li‐ion batteries, the extensive use of lithium‐oxygen (Li‐O 2 ) batteries is constrained by the slow kinetics of both the oxygen evolution reaction and oxygen reduction reaction. To increase the overall performance of Li‐O 2 batteries, it is essential to increase the efficiency of oxygen electrode reactions by constructing effective electrocatalysts. As a high‐efficiency catalyst for Li‐O 2 batteries, high entropy perovskite oxide (La 0.8 Sr 0.2 )(Mn 0.2 Fe 0.2 Cr 0.2 Co 0.2 Ni 0.2 )O 3 (referred to as LS(MFCCN)O 3 ) is designed and investigated in this article. The introduction of dissimilar metals in LS(MFCCN)O 3 has the potential to cause lattice deformation, thereby enhancing electron transfer between transition metal ions and facilitating the formation of numerous oxygen vacancies. This feature is advantageous for the reversible production and breakdown of discharge product Li 2 O 2 . Consequently, the Li‐O 2 battery utilizing LS(MFCCN)O 3 as a catalyst achieves an impressive discharge capacity of 17,078.2 mAh g −1 and exhibits an extended cycling life of 435 cycles. This study offers a useful method for adjusting the catalytic performance of perovskite oxides toward oxygen redox reactions in Li‐O 2 batteries.    

    

** The selective aerobic oxidative C-C bond cleavage with the high-entropy oxide-derived multimetallic catalyst   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3re00525a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390720071"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390720071"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390720071"))][Get cited by]]

OpenAlex: https://openalex.org/W4390720071 (Open access: False)
    
[[https://openalex.org/A5057493561][Shaoyuan Guo]], [[https://openalex.org/A5052971906][Xinli Tong]], [[https://openalex.org/A5000561318][Jipeng Wang]], [[https://openalex.org/A5024821664][Honggang Tang]], No host. None(None)] 2023. https://doi.org/10.1039/d3re00525a 
     
The use of high-entropy oxides (HEOs) in the heterogeneous catalysis is a fascinating research orientation in the chemical field. In this work, a highly selective aerobic oxidative C-C bond cleavage...    

    
