#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Wed Jan  8 01:21:17 2025

Found 1 results from 2025-01-01 to 2025-01-08
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

* Unveiling the Oxidation Mechanisms of High‐entropy Carbides Through Atomic‐scale Dynamic Observation  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4405994380
:TOPICS: High Entropy Alloys Studies, Advanced materials and composites, High-Temperature Coating Behaviors
:PUBLICATION_DATE: 2025-01-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202417846")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405994380"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405994380"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405994380"))][Get cited by]]

OpenAlex: https://openalex.org/W4405994380 (Open access: False)
    
[[https://openalex.org/A5101409185][Lei Zhuang]], [[https://openalex.org/A5101413446][Zihao Wen]], [[https://openalex.org/A5100770932][Yiwen Liu]], [[https://openalex.org/A5101985744][Jing Yang]], [[https://openalex.org/A5090875999][Hulei Yu]], [[https://openalex.org/A5088060383][Yanhui Chu]], Advanced Materials. None(None)] 2025. https://doi.org/10.1002/adma.202417846 
     
Abstract Understanding the behavior of high‐entropy carbides (HECs) under oxygen‐containing environments is of particular importance for their promising applications in structural components, catalysis, and energy‐related fields. Herein, the structural evolution of (Ta, Ti, Cr, Nb)C (HEC‐1) nanoparticles (NPs) is tracked in situ during the oxidation at the atomic scale by using an open‐cell environmental aberration‐corrected scanning transmission electron microscope. Three key stages are clearly discerned during the oxidation of HEC‐1 NPs at the atomic level below 900 °C: i) increased amorphization of HEC‐1 NPs from 300 to 500 °C due to the energetically favorable formation of carbon vacancies and substitution of carbon with oxygen atoms; ii) nucleation and subsequent growth of locally ordered nanocluster intermediates within the generated amorphous oxides from 500 to 800 °C; and iii) final one‐step crystallization of non‐equimolar MeO 2 and Me 2 O 5 (Me = metallic elements, Ta, Ti, Cr, and Nb) high‐entropy oxides above 800 °C, accompanied with the reduction in atomic defects. This result is further confirmed by theoretical calculations that these observed high‐entropy oxide phases are thermodynamically preferable to generate above 830 °C. The study provides direct evidence of the ordered–disordered–ordered structural transition of HECs during oxidation.    

    
