#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Wed Nov 27 01:26:41 2024

Found 1 results from 2024-11-20 to 2024-11-27
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

* One-Pot Synthesis of (CrMnFeCoNi)Ox High-Entropy Oxides for Efficient Catalytic Oxidation of Propane: A Promising Substitute for Noble Metal Catalysts  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4404582402
:TOPICS: Catalytic Nanomaterials, High-Entropy Alloys: Novel Designs and Properties, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-11-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c14292")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404582402"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404582402"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404582402"))][Get cited by]]

OpenAlex: https://openalex.org/W4404582402 (Open access: False)
    
[[https://openalex.org/A5083364328][Yang Li]], [[https://openalex.org/A5103197890][Bowen Han]], [[https://openalex.org/A5103051803][Feng Bi]], [[https://openalex.org/A5037873853][Zhongbiao Wu]], [[https://openalex.org/A5033599365][Xiaole Weng]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c14292 
     
The efficient catalytic oxidation of propane, as a short-chain alkane, remains challenging in environmental catalysis. High-entropy oxides (HEOs) exhibit advantages in abundant and well-dispersed elemental composition, exceptional thermal stability, and enriched lattice defects. Herein, (CrMnFeCoNi)Ox HEO catalysts are successfully synthesized by using a continuous hydrothermal flow synthesis (CHFS) route, without any subsequent calcination processes. This route yields HEOs with fine particle sizes, high specific surface areas, and abundant near-surface lattice oxygen compared to the traditional coprecipitation method. Notably, the propane conversion over the CHFS-made (CrMnFeCoNi)Ox HEO reaches 90% at 255 °C, with an apparent activation energy of 53.2 kJ/mol, mainly attributed to its enriched lattice oxygen and enhanced oxygen mobility that prevent the accumulation of acetates and the consequent occupation of active sites. In comparison to commercial Pt/Al2O3 and Pd/Al2O3, (CrMnFeCoNi)Ox HEO demonstrates exceptional activity and can maintain long-term stability under high-temperature (upon 650 °C) and moisture-rich conditions (at 2–10 vol %). These attributes highlight its potential as a promising substitute for noble metal catalysts in industrial applications.    

    
