#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Sun Apr 28 01:08:08 2024

Found 1 results from 2024-04-21 to 2024-04-28
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

* Spin‐Regulated Fenton‐Like Catalysis for Nonradical Oxidation over Metal Oxide@Carbon Composites  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4395082091
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Catalytic Oxidation of Alcohols
:PUBLICATION_DATE: 2024-04-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202401397")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395082091"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395082091"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395082091"))][Get cited by]]

OpenAlex: https://openalex.org/W4395082091 (Open access: False)
    
[[https://openalex.org/A5007519947][Bofeng Li]], [[https://openalex.org/A5024121358][Liu Ya]], [[https://openalex.org/A5016690357][Kunsheng Hu]], [[https://openalex.org/A5012805315][Qing Dai]], [[https://openalex.org/A5007184529][Chunmao Chen]], [[https://openalex.org/A5006059700][Xiaoguang Duan]], [[https://openalex.org/A5013288442][Shaobin Wang]], [[https://openalex.org/A5011740811][Yuxian Wang]], Advanced functional materials. None(None)] 2024. https://doi.org/10.1002/adfm.202401397 
     
Abstract The spin state of the transition metal species (TMs) has been recognized as a critical descriptor in Fenton‐like catalysis. The raised spin state of dispersed TMs in carbon will enhance the redox processes with adsorbed peroxides and improve the oxidation performance. Nevertheless, establishing the spin‐activity correlations for the encapsulated TM nanoparticles remains challenging because of the difficulties in fine‐tuning the spin state of TM species and the insufficient understanding of orbital hybridization states upon interaction with peroxides. Here, the advantage of the fast‐temperature heating/quenching of microwave thermal shock is taken to engineer the structure and spin state of encapsulated TMs within the N‐doped graphitic carbons. The reduced TMs particle size and enhanced TMs‐carbon coupling increase surface entropy and regulate e g electron filling of the high‐spin TM‐N coordination, endowing electrons with high mobility and facilitating peroxymonosulfate (PMS) adsorption. The strong interactions further uplift the PMS O 2p band position toward the Fermi level and thus elevate the oxidation potential of surface‐activated PMS (PMS * ) as the dominant nonradical species for pollutant degradation. The deciphered orbital hybridizations of engineered high‐spin TM and PMS enlighten the smart design of spin‐regulated nanocomposites for advanced water purification.    

    
