#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Wed Nov 13 01:20:08 2024

Found 1 results from 2024-11-06 to 2024-11-13
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

* Raman activities of nitrogen reduction and ammonia oxidation intermediates on the high-entropy alloy CoCuFeMoNi catalytic surface  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4404109388
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-11-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0233585")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404109388"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404109388"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404109388"))][Get cited by]]

OpenAlex: https://openalex.org/W4404109388 (Open access: False)
    
[[https://openalex.org/A5060552376][Rafael B. Araujo]], [[https://openalex.org/A5062918296][Jakob Thyr]], [[https://openalex.org/A5035519750][İlknur Bayrak Pehlivan]], [[https://openalex.org/A5056174579][Tomas Edvinsson]], The Journal of Chemical Physics. 161(17)] 2024. https://doi.org/10.1063/5.0233585 
     
We developed a computational framework to extract the Raman spectra of nitrogen reduction and ammonia oxidation intermediates on high-entropy alloy (HEA) surfaces, integrating density functional theory with microstructural representations to account for the inherent lattice randomness in these materials. As a case study, we computed the Raman activities of intermediates (N2*, NNH*, N*, NH*, and NH3*) and H* adsorption on CoCuFeMoNi HEA surfaces. A comprehensive map of Raman peaks was generated and assigned to specific vibrational modes. The method highlighted the effects of lattice randomness on the Raman spectra compared to those of adsorbates on single-element catalysts. For instance, our results showed that the adsorbed N2 exhibits Raman modes that are dependent on whether the adsorption is vertical or horizontal. These peak differences could serve as unique fingerprints to identify nitrogen reduction reaction pathways. Moreover, it is also possible to detect surface poisoning by hydrogen, a common issue in reductive environments, due to the high-frequency peaks of H* compared to the typical N-metal stretching and bending frequencies. These results provide valuable references for identifying intermediates in nitrogen reduction and ammonia oxidation reactions, offering insights into reaction mechanisms and potential surface poisoning. This approach is generalizable to other reactions and surfaces in catalysis, provided that the relevant intermediates can be identified.    

    
