#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Thu Feb 29 00:43:18 2024

Found 1 results from 2024-02-22 to 2024-02-29
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

* Single-Atom Cobalt Catalysts Encapsulating Cobalt Nanoparticles with Built-In Electric Field for Ultrafast and Lasting Peroxymonosulfate Activation  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4392193592
:TOPICS: Advanced Oxidation Processes for Water Treatment, Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsestwater.3c00774")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392193592"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392193592"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392193592"))][Get cited by]]

OpenAlex: https://openalex.org/W4392193592 (Open access: False)
    
[[https://openalex.org/A5035418134][Haiyan Zou]], [[https://openalex.org/A5042900358][Haitao Wang]], [[https://openalex.org/A5089558604][Hongqi Sun]], [[https://openalex.org/A5032974223][Wenshuang Sun]], [[https://openalex.org/A5079948079][Shuangjiang Luo]], [[https://openalex.org/A5044538484][Tielong Li]], [[https://openalex.org/A5006059700][Xiaoguang Duan]], [[https://openalex.org/A5029732718][Sihui Zhan]], ACS ES&T Water. None(None)] 2024. https://doi.org/10.1021/acsestwater.3c00774 
     
Cobalt single-atom catalysts (Co-SAs) are rising stars in persulfate chemistry for their well-defined coordination, reduced metal usage, and exceptional activity. However, the simultaneous formation of cobalt nanoparticles (Co-NPs) with Co-SAs raises questions about their complex interplay and synergy in catalysis. In this study, we synthesized Co-SAs-encapsulated Co-NPs (CoNP@NC/Co-SA) using the laser-induced carbonization strategy of high entropy synthesis technology. The results show that 93.23% of phenol can be removed in 15 min and 91.60% in 3 min in the CoNP@NC/Co-SA/PMS system. Simulation results showed that Co-NPs fine-tune the electronic structure of Co-SA sites, optimizing PMS adsorption and activation to generate confined reactive species. The surface-activated PMS-catalyst complex directly attacked adsorbed pollutants on the catalyst surface via an electron-transfer regime. CoNP@NC/Co-SA catalyzes PMS oxidation through a nonradical pathway with high selectivity toward target organics. The findings emphasize the synergistic effect of Co-SAs and Co-NPs in promoting Fenton-like catalysis, enlightening the rational design of advanced composite materials via synergistic molecular and interfacial engineering for fast and long-lasting catalytic oxidation. At the same time, this work provides insights into the electronic structure regulation of metal centers at the atomic level.    

    
