#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Tue Dec 24 01:21:17 2024

Found 2 results from 2024-12-17 to 2024-12-24
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

* Enhancing Energy Solutions and Environmental Remediation: Piezocatalysis in Ferroelectric High-Entropy Oxides and 2D Materials  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4405590608
:TOPICS: Pigment Synthesis and Properties, Material Science and Thermodynamics, Magnesium Oxide Properties and Applications
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2024-02392595mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405590608"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405590608"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405590608"))][Get cited by]]

OpenAlex: https://openalex.org/W4405590608 (Open access: False)
    
[[https://openalex.org/A5110850785][Jyh-Ming Wu]], Meeting abstracts/Meeting abstracts (Electrochemical Society. CD-ROM). MA2024-02(39)] 2024. https://doi.org/10.1149/ma2024-02392595mtgabs 
     
Hydrogen is the most abundant element on Earth, and it is a safe and efficient source of energy. Through electrocatalysis and photocatalysis water molecules can be split into O and H 2 , which can then be used for fuel. This has been widely studied as a promising approach to reduce CO 2 emissions and reliance on fossil fuels. A solar-assisted electrochemical process that generates H 2 without toxic byproducts is being investigated. Solutions involving the remediation of water pollutants, water splitting, and clean energy alternatives have been widely investigated. However, most semiconducting photocatalysts are not very efficient when used in water-based solutions, because they have a low quantum yield. This talk will report how the piezocatalyts and flexocatalysts can proceed with electrochemical reactions for highly efficient wastewater treatment and hydrogen production. Considering the piezophototronic effect in the visible range, we combined a ferroelectric component with a high entropy oxide (HEO) compound, which can significantly enhance the charge transfer of the HEO's surface, enhancing the catalytic activity (Figure 1). Theoretical calculations revealed that a ferroelectric component could create an inner electric field at interfacial phase boundaries and effectively moderate free carriers, strengthening the charge separation in the ferroelectric HEO catalyst. When an external mechanical force was coupled with photoirradiation, the photoinduced charge separation coupled with piezoelectric polarization enhanced the charge transport in trapping sites. In this talk, I will provide an overview of High Entropy Oxide (HEO) ferroelectric catalysts, along with advancements in piezocatalysts within 2D materials and ferroelectric domains. The concepts presented will pave the way for designing next-generation piezo-photocatalysts. References Y. T. Lin, S. N. Lai, J. M. Wu*, Advanced Materials 32 (34), 2002875, 2020. SC Chang, HY Chen, PH Chen, JT Lee, JM Wu*, Applied Catalysis B: Environmental 324, 122204, 2023. Figure 1    

    

* Correction to “Fe-Based High-Entropy Perovskite Oxide: A Strategy to Suppress Sr Segregation and Performance Evaluation as an Electrode Material for SOFCs”  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4405515799
:TOPICS: Electrocatalysts for Energy Conversion, Fuel Cells and Related Materials, Electrochemical Analysis and Applications
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.4c02978")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405515799"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405515799"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405515799"))][Get cited by]]

OpenAlex: https://openalex.org/W4405515799 (Open access: True)
    
[[https://openalex.org/A5010861850][Muhammad Salman]], [[https://openalex.org/A5028349044][Sumaiya Saleem]], [[https://openalex.org/A5020303601][Yihan Ling]], [[https://openalex.org/A5016964088][Majid Khan]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.4c02978 
     
InfoMetricsFiguresRef.SI ACS Applied Energy MaterialsASAPArticle This publication is free to access through this site. Learn More CiteCitationCitation and abstractCitation and referencesMore citation options ShareShare onFacebookX (Twitter)WeChatLinkedInRedditEmailJump toExpandCollapse ORIGINAL ARTICLE. This notice is a correction.Addition/CorrectionDecember 18, 2024Correction to "Fe-Based High-Entropy Perovskite Oxide: A Strategy to Suppress Sr Segregation and Performance Evaluation as an Electrode Material for SOFCs"Click to copy article linkArticle link copied!Muhammad SalmanMuhammad SalmanMore by Muhammad SalmanSumaiya SaleemSumaiya SaleemMore by Sumaiya SaleemYihan LingYihan LingMore by Yihan LingMajid Khan*Majid KhanMore by Majid Khanhttps://orcid.org/0000-0001-6998-021XOpen PDFSupporting Information (1)ACS Applied Energy MaterialsCite this: ACS Appl. Energy Mater. 2024, XXXX, XXX, XXX-XXXClick to copy citationCitation copied!https://pubs.acs.org/doi/10.1021/acsaem.4c02978https://doi.org/10.1021/acsaem.4c02978Published December 18, 2024 Publication History Received 5 December 2024Published online 18 December 2024correction© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsThis publication is licensed for personal use by The American Chemical Society. ACS Publications© 2024 American Chemical SocietyAn author in our original paper, Muhammad Salman, was a visiting student in China from Pakistan and left Prof. Ling's lab in May 2024 before submitting the manuscript to ACS Applied Energy Materials. Muhammad Salman started preparing this article after he left China, and Majid Khan specializes in low temperature catalysis and has no knowledge of SOFC electrode materials and did not send the manuscript to Prof. Ling for review before submission. So, the article was submitted without sufficient review. Prof. Ling had no knowledge of the content of the article, and as the data was not labeled, Muhammad Salman misused the data. We strongly objected to this behavior after the article was made available online, so we would like to publish this statement and attempt to correct the errors in the manuscript. In addition, Prof. Ling is no longer another corresponding author in the revised article.In the originally published paper, the TEM images (Figure 2b, c) and XPS images (Figure 3b, d) were mistakenly provided as identical to those in another of our published works where the base materials were the same as the current study. Also, Figure 4c and Figure 8d need to be corrected. This was an unintentional oversight due to a file management error. Below are the corrected data which accurately represents the results discussed in the paper and will not affect the conclusion or other discussions.Figure 2Figure 2. TEM images of (b) HEP-LSF and the corresponding HR-TEM images of (c) LSF.High Resolution ImageDownload MS PowerPoint SlideFigure 3Figure 3. XPS fitting results of O 1s spectra of (b, d) HEP-LSF.High Resolution ImageDownload MS PowerPoint SlideFigure 4Figure 4. SEM image of (c) LSF after 150 h treatment at 800 °C.High Resolution ImageDownload MS PowerPoint SlideFigure 8Figure 8. Polarization resistance results of the symmetrical single cell with (d) HEP-LSF|GDC|YSZ|GDC|HEP-LSF.High Resolution ImageDownload MS PowerPoint SlideOn page 8654, the sentence "The Rp values of HEP-LSF are 0.136 Ω·cm2 at 800 °C and 0.743 Ω·cm2 at 600 °C (Tables S1 and S2)." should be corrected to "The Rp values of HEP-LSF are 0.145 Ω·cm2 at 800 °C and 1.803 Ω·cm2 at 600 °C (Tables S1 and S2); the better performance of the HEP-LSF cell is confirmed to be mainly ascribed to the lower interfacial polarization resistance."Lastly, Tables S1 and S2 are corrected in the Supporting Information, associated with this Addition and Correction.Supporting InformationClick to copy section linkSection link copied!The Supporting Information is available free of charge at https://pubs.acs.org/doi/10.1021/acsaem.4c02978.Same description as in original article (PDF)ae4c02978_si_001.pdf (153.51 kb) Terms & Conditions Most electronic Supporting Information files are available without a subscription to ACS Web Editions. Such files may be downloaded by article for research use (if there is a public use license linked to the relevant article, that license may permit other uses). Permission may be obtained from ACS for other uses through requests via the RightsLink permission system: http://pubs.acs.org/page/copyright/permissions.html. Author InformationClick to copy section linkSection link copied!Corresponding AuthorMajid Khan; https://orcid.org/0000-0001-6998-021XAuthorsMuhammad SalmanSumaiya SaleemYihan LingCited By Click to copy section linkSection link copied!This article has not yet been cited by other publications.Download PDFFiguresReferencesSupporting Information Get e-AlertsGet e-AlertsACS Applied Energy MaterialsCite this: ACS Appl. Energy Mater. 2024, XXXX, XXX, XXX-XXXClick to copy citationCitation copied!https://doi.org/10.1021/acsaem.4c02978Published December 18, 2024 Publication History Received 5 December 2024Published online 18 December 2024© 2024 American Chemical Society. This publication is available under these Terms of Use. Request reuse permissionsArticle Views-Altmetric-Citations-Learn about these metrics closeArticle Views are the COUNTER-compliant sum of full text article downloads since November 2008 (both PDF and HTML) across all institutions and individuals. These metrics are regularly updated to reflect usage leading up to the last few days.Citations are the number of other articles citing this article, calculated by Crossref and updated daily. Find more information about Crossref citation counts.The Altmetric Attention Score is a quantitative measure of the attention that a research article has received online. Clicking on the donut icon will load a page at altmetric.com with additional details about the score and the social media presence for the given article. Find more information on the Altmetric Attention Score and how the score is calculated.Recommended Articles FiguresReferencesSupporting InfoFigure 2Figure 2. TEM images of (b) HEP-LSF and the corresponding HR-TEM images of (c) LSF.High Resolution ImageDownload MS PowerPoint SlideFigure 3Figure 3. XPS fitting results of O 1s spectra of (b, d) HEP-LSF.High Resolution ImageDownload MS PowerPoint SlideFigure 4Figure 4. SEM image of (c) LSF after 150 h treatment at 800 °C.High Resolution ImageDownload MS PowerPoint SlideFigure 8Figure 8. Polarization resistance results of the symmetrical single cell with (d) HEP-LSF|GDC|YSZ|GDC|HEP-LSF.High Resolution ImageDownload MS PowerPoint SlideThis publication has no References.Supporting InformationSupporting InformationThe Supporting Information is available free of charge at https://pubs.acs.org/doi/10.1021/acsaem.4c02978.Same description as in original article (PDF)ae4c02978_si_001.pdf (153.51 kb) Terms & Conditions Most electronic Supporting Information files are available without a subscription to ACS Web Editions. Such files may be downloaded by article for research use (if there is a public use license linked to the relevant article, that license may permit other uses). Permission may be obtained from ACS for other uses through requests via the RightsLink permission system: http://pubs.acs.org/page/copyright/permissions.html.    

    
