#+TITLE: high-entropy-oxides
Description: high entropy oxides in catalysis
Created on Mon Jul  1 01:16:48 2024

Found 2 results from 2024-06-24 to 2024-07-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Ahigh%20entropy%20oxide%20catalysis]]

* High-Entropy Perovskite Oxides as a Family of Electrocatalysts for Efficient and Selective Nitrogen Oxidation  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4399957749
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.4c02231")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399957749"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399957749"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399957749"))][Get cited by]]

OpenAlex: https://openalex.org/W4399957749 (Open access: False)
    
[[https://openalex.org/A5044983690][Hui Zheng]], [[https://openalex.org/A5041488712][Yunxia Liu]], [[https://openalex.org/A5082660416][Zhuang Ma]], [[https://openalex.org/A5066461826][Elke Debroye]], [[https://openalex.org/A5038216241][Jinyu Ye]], [[https://openalex.org/A5037139352][Longsheng Zhang]], [[https://openalex.org/A5018950796][Tianxi Liu]], ACS nano. None(None)] 2024. https://doi.org/10.1021/acsnano.4c02231 
     
Electrocatalytic nitrogen oxidation reaction (NOR) can convert nitrogen (N2) into nitrate (NO3–) under ambient conditions, providing an attractive approach for synthesis of NO3–, alternative to the current approach involving the harsh Haber–Bosch and Ostwald oxidation processes that necessitate high temperature, high pressure, and substantial carbon emission. Developing efficient NOR catalysts is a prerequisite, which remains a formidable challenge, owing to the weak activation/dissociation of N2. A variety of NOR electrocatalysts have been developed, but their NOR kinetics are still extremely sluggish, resulting in inferior Faradaic Efficiencies. Here, we report a high-entropy Ru-based perovskite oxide (denoted as Ru-HEP) that can function as a high-performance NOR catalyst and exhibit a high NO3– yield rate of 39.0 μmol mg–1 h–1 with a Faradaic Efficiency of 32.8%. Both our experimental results and theoretical calculations suggest that the high-entropy configuration of Ru-HEP perovskite oxide can markedly enhance the oxygen-vacancy concentration, where the Ru sites and their neighboring oxygen vacancies can serve as unsaturated centers and decrease the overall energy barrier for N2 electrooxidation, thereby leading to promoted NOR kinetics. This work presents an alternative avenue for promoting NOR catalysis on perovskite oxides through the high-entropy engineering strategy.    

    

* Local Nanostructure in Multicomponent High-Entropy Materials  :high_entropy_oxides:
:PROPERTIES:
:UUID: https://openalex.org/W4400078874
:TOPICS: High-Entropy Alloys: Novel Designs and Properties, Mantle Dynamics and Earth's Structure, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-06-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s44210-024-00040-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400078874"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400078874"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400078874"))][Get cited by]]

OpenAlex: https://openalex.org/W4400078874 (Open access: True)
    
[[https://openalex.org/A5064795527][B. Cantor]], Deleted Journal. None(None)] 2024. https://doi.org/10.1007/s44210-024-00040-4 
     
Abstract Multicomponent phase space contains extended regions of random or near-random multicomponent solid-solution single phases, stabilised by a relatively large configurational entropy of mixing that can often (though not always) suppress compound formation between the different atomic species. The present paper shows that there are very extensive variations of local nanostructure, local atomic clusters and associated local lattice strains within multicomponent high-entropy solid-solution single phases such as the fcc Cantor alloys, bcc Senkov alloys and rock-salt-structured Rost mono-oxides, even when there is no short-range ordering, i.e. even when the solid solution is completely random or ideal. There are, for instance, many billions of different local nanostructures and different local atomic clusters in equiatomic five-component fully random solid-solution single-phase materials such as the original fcc Cantor alloy CrMnFeCoNi and the original bcc Senkov alloy VNbMoTaW, extending over distances of many microns, with associated fluctuating hydrostatic and shear lattice strains of several percent. The number and extent of the variations in local nanostructure, atomic clusters and lattice strains increase dramatically to even higher values with increasing number of components in the material. The present paper also shows that there are similar variations in local nanostructure, local atomic clusters and associated local lattice strains surrounding point defects such as vacancies, line defects such as dislocations and planar defects such as grain boundaries and external surfaces, influencing many important material properties such as diffusion, plastic flow, recrystallisation, grain growth and catalysis. The number and extent of the variations in local nanostructure, atomic clusters and lattice strains make it difficult to have too much confidence in structures and properties of multicomponent high-entropy materials calculated using ab initio and other atomistic computer modelling techniques, since these techniques are restricted to relatively small numbers of atoms and are unable to sample effectively the full range of local structures and properties.    

    
