#+filetags: high-entropy-oxides
#+TITLE: high-entropy-oxides
Created on Thu Jan 18 12:35:14 2024

Found 3 results from 2024-01-04 to 2024-01-18
** Strain‐rich high‐entropy perovskite oxide of (La<sub>0.8</sub>Sr<sub>0.2</sub>)(Mn<sub>0.2</sub>Fe<sub>0.2</sub>Cr<sub>0.2</sub>Co<sub>0.2</sub>Ni<sub>0.2</sub>)O<sub>3</sub> for durable and effective catalysis of oxygen redox reactions in lithium‐oxygen battery   
:PROPERTIES:
:ID: https://openalex.org/W4390738391
:DOI: https://doi.org/10.1002/bte2.20230053
:AUTHORS: Zhanpeng Liu, Haoyang Xu, Xinxiang Wang, Guilei Tian, Dongxing Du, Chaozhu Shu
:HOST: No host
:END:

Zhanpeng Liu, Haoyang Xu, Xinxiang Wang, Guilei Tian, Dongxing Du, Chaozhu Shu, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/bte2.20230053")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390738391"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390738391"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390738391"))][Get cited by]]

OpenAlex: https://openalex.org/W4390738391
    
Zhanpeng Liu, Haoyang Xu, Xinxiang Wang, Guilei Tian, Dongxing Du, Chaozhu Shu, No host. https://doi.org/10.1002/bte2.20230053
    
Abstract Despite their great promise as high‐energy‐density alternatives to Li‐ion batteries, the extensive use of lithium‐oxygen (Li‐O 2 ) batteries is constrained by the slow kinetics of both the oxygen evolution reaction and oxygen reduction reaction. To increase the overall performance of Li‐O 2 batteries, it is essential to increase the efficiency of oxygen electrode reactions by constructing effective electrocatalysts. As a high‐efficiency catalyst for Li‐O 2 batteries, high entropy perovskite oxide (La 0.8 Sr 0.2 )(Mn 0.2 Fe 0.2 Cr 0.2 Co 0.2 Ni 0.2 )O 3 (referred to as LS(MFCCN)O 3 ) is designed and investigated in this article. The introduction of dissimilar metals in LS(MFCCN)O 3 has the potential to cause lattice deformation, thereby enhancing electron transfer between transition metal ions and facilitating the formation of numerous oxygen vacancies. This feature is advantageous for the reversible production and breakdown of discharge product Li 2 O 2 . Consequently, the Li‐O 2 battery utilizing LS(MFCCN)O 3 as a catalyst achieves an impressive discharge capacity of 17,078.2 mAh g −1 and exhibits an extended cycling life of 435 cycles. This study offers a useful method for adjusting the catalytic performance of perovskite oxides toward oxygen redox reactions in Li‐O 2 batteries.    

    

** Spin-related Cu-Co pair to increase electrochemical ammonia generation on high-entropy oxides   
:PROPERTIES:
:ID: https://openalex.org/W4390587030
:DOI: https://doi.org/10.1038/s41467-023-44587-z
:AUTHORS: Shengnan Sun, Chencheng Dai, Peng Zhao, Shibo Xi, Yushan Ren, Hui Ru Tan, Poh Chong Lim, Ming Lin, Caozheng Diao, Danwei Zhang, Chao Wu, A Filimonov Yu., Jung−Hyuk Koh, Wei Ying Lieu, Debbie Hwee Leng Seng, Libo Sun, Yuke Li, Teck Leong Tan, Jia Zhang, Zhichuan J. Xu, Zhi Wei Seh
:HOST: Nature Communications
:END:

Shengnan Sun, Chencheng Dai, Peng Zhao, Shibo Xi, Yushan Ren, Hui Ru Tan, Poh Chong Lim, Ming Lin, Caozheng Diao, Danwei Zhang, Chao Wu, A Filimonov Yu., Jung−Hyuk Koh, Wei Ying Lieu, Debbie Hwee Leng Seng, Libo Sun, Yuke Li, Teck Leong Tan, Jia Zhang, Zhichuan J. Xu, Zhi Wei Seh, Nature Communications. 15(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-023-44587-z")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390587030"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390587030"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390587030"))][Get cited by]]

OpenAlex: https://openalex.org/W4390587030
    
Shengnan Sun, Chencheng Dai, Peng Zhao, Shibo Xi, Yushan Ren, Hui Ru Tan, Poh Chong Lim, Ming Lin, Caozheng Diao, Danwei Zhang, Chao Wu, A Filimonov Yu., Jung−Hyuk Koh, Wei Ying Lieu, Debbie Hwee Leng Seng, Libo Sun, Yuke Li, Teck Leong Tan, Jia Zhang, Zhichuan J. Xu, Zhi Wei Seh, Nature Communications. https://doi.org/10.1038/s41467-023-44587-z
    
Abstract The electrochemical conversion of nitrate to ammonia is a way to eliminate nitrate pollutant in water. Cu-Co synergistic effect was found to produce excellent performance in ammonia generation. However, few studies have focused on this effect in high-entropy oxides. Here, we report the spin-related Cu-Co synergistic effect on electrochemical nitrate-to-ammonia conversion using high-entropy oxide Mg 0.2 Co 0.2 Ni 0.2 Cu 0.2 Zn 0.2 O. In contrast, the Li-incorporated MgCoNiCuZnO exhibits inferior performance. By correlating the electronic structure, we found that the Co spin states are crucial for the Cu-Co synergistic effect for ammonia generation. The Cu-Co pair with a high spin Co in Mg 0.2 Co 0.2 Ni 0.2 Cu 0.2 Zn 0.2 O can facilitate ammonia generation, while a low spin Co in Li-incorporated MgCoNiCuZnO decreases the Cu-Co synergistic effect on ammonia generation. These findings offer important insights in employing the synergistic effect and spin states inside for selective catalysis. It also indicates the generality of the magnetic effect in ammonia synthesis between electrocatalysis and thermal catalysis.    

    

** General Synthesis of High-Entropy Oxide Nanofibers   
:PROPERTIES:
:ID: https://openalex.org/W4390579245
:DOI: https://doi.org/10.1021/acsnano.3c07506
:AUTHORS: Mengyuan Zhang, Jian Ye, Ying Gao, Xiaolan Duan, Jiahua Zhao, Shuangshuang Zhang, Xingxu Lu, Kai Luo, Qiongqiong Wang, Qiang Niu, Pengfei Zhang, Sheng Dai
:HOST: ACS Nano
:END:

Mengyuan Zhang, Jian Ye, Ying Gao, Xiaolan Duan, Jiahua Zhao, Shuangshuang Zhang, Xingxu Lu, Kai Luo, Qiongqiong Wang, Qiang Niu, Pengfei Zhang, Sheng Dai, ACS Nano. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.3c07506")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390579245"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390579245"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390579245"))][Get cited by]]

OpenAlex: https://openalex.org/W4390579245
    
Mengyuan Zhang, Jian Ye, Ying Gao, Xiaolan Duan, Jiahua Zhao, Shuangshuang Zhang, Xingxu Lu, Kai Luo, Qiongqiong Wang, Qiang Niu, Pengfei Zhang, Sheng Dai, ACS Nano. https://doi.org/10.1021/acsnano.3c07506
    
The discovery of high-entropy oxides (HEOs) in 2015 has provided a family of potential solid catalysts, due to their tunable components, abundant defects or lattice distorts, excellent thermal stability (ΔG↓ = ΔH – TΔS↑), and so on. When facing the heterogeneous catalysis by HEOs, the micrometer bulky morphology and low surface areas (e.g., <10 m2 g–1) by traditional synthesis methods obstructed their way. In this work, an electrospinning method to fabricate HEO nanofibers with diameters of 50–100 nm was demonstrated. The key point lay in the formation of one-dimensional filamentous precursors, during which the uniform dispersion of five metal species with disordered configuration would help to crystallize into single-phase HEOs at lower temperatures: inverse spinel (Cr0.2Mn0.2Co0.2Ni0.2Fe0.2)3O4 (400 °C), perovskite La(Mn0.2Cu0.2Co0.2Ni0.2Fe0.2)O3 (500 °C), spinel Ni0.2Mg0.2Cu0.2Mn0.2Co0.2)Al2O4 (550 °C), and cubic Ni0.2Mg0.2Cu0.2Zn0.2Co0.2O (750 °C). As a proof-of-concept, (Ni3MoCoZn)Al12O24 nanofiber exhibited good activity (CH4 Conv. > 96%, CO2 Conv. > 99%, H2/CO ≈ 0.98), long-time stability (>100 h) for the dry reforming of methane (DRM) at 700 °C without coke deposition, better than control samples (Ni3MoCoZn)Al12O24-Coprecipitation-700 (CH4 Conv. < 3%, CO2 Conv. < 7%). The reaction mechanism of DRM was studied by in situ infrared spectroscopy, CO2-TPD, and CO2/CH4-TPSR. This electrospinning method provides a synthetic route for HEO nanofibers for target applications.    

    
