#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Tue Nov 19 01:25:00 2024

Found 3 results from 2024-11-12 to 2024-11-19
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Room-Temperature CO2 Conversion to Carbon Using Liquid Metal Alloy Catalysts without External Energy Input  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4404399114
:TOPICS: Carbon Dioxide Capture and Storage Technologies, Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-11-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jics.2024.101467")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404399114"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404399114"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404399114"))][Get cited by]]

OpenAlex: https://openalex.org/W4404399114 (Open access: False)
    
[[https://openalex.org/A5047299189][Mahesh Kumar Gagrai]], Journal of the Indian Chemical Society. None(None)] 2024. https://doi.org/10.1016/j.jics.2024.101467 
     
No abstract    

    

* Better Together: Synergic Effect of Gallium‐Based Catalyst and Porous Support for Reduction Reactions  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4404375720
:TOPICS: Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-11-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202401429")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404375720"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404375720"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404375720"))][Get cited by]]

OpenAlex: https://openalex.org/W4404375720 (Open access: False)
    
[[https://openalex.org/A5103511840][Maialen Sánchez]], [[https://openalex.org/A5090479714][Simon Carl]], [[https://openalex.org/A5001718718][Nicola Taccardi]], [[https://openalex.org/A5040845269][Marco Haumann]], [[https://openalex.org/A5046935930][Benjamin Apeleo Zubiri]], [[https://openalex.org/A5039726667][Peter Wasserscheid]], [[https://openalex.org/A5062733366][Erdmann Spiecker]], [[https://openalex.org/A5090374920][Nicolas Vogel]], [[https://openalex.org/A5002887494][Julien Bachmann]], [[https://openalex.org/A5025433382][Giulia Magnabosco]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202401429 
     
Liquid metal solutions are a new class of catalysts with outstanding properties in terms of catalytic conversion and resistance to coking. Finding the perfect combination of catalytic particles with homogeneous size distribution and support material able to stabilize them during catalysis is key for preparing model systems to gain understanding of these complex catalytic processes. In this work, we present a method for the preparation of small and narrowly distributed gallium‐palladium particles supported on inverse opals, interconnected 3‐dimensional porous networks with a very narrow pore size distribution. Our platform is a promising candidate as supported liquid metal catalytic system thanks to its permeability to fluids and its confined pore environment, which prevents the coalescence of the metal alloy, thus maximizing the surface area available for the catalytic reaction. We demonstrate their enhanced performance when compared to other state of the art systems giving a proof of concept of their application as catalysts for a simple model reaction, the reduction of methylene blue.    

    

* Nanoporous Cu-based amorphous alloys prepared by selective dissolution in acidic media  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4404244174
:TOPICS: Evolution and Applications of Nanoporous Metals, Fabrication and Applications of Porous Alumina Membranes, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1757-899x/1319/1/012032")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404244174"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404244174"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404244174"))][Get cited by]]

OpenAlex: https://openalex.org/W4404244174 (Open access: True)
    
[[https://openalex.org/A5005293169][Sebastian Ambruş]], [[https://openalex.org/A5004837368][Roxana Muntean]], [[https://openalex.org/A5089831717][Dragoş Buzdugan]], [[https://openalex.org/A5011823190][Cosmin Codrean]], IOP Conference Series Materials Science and Engineering. 1319(1)] 2024. https://doi.org/10.1088/1757-899x/1319/1/012032 
     
Abstract Functional nanoporous materials are considered a significant category of nanostructured materials that exhibit distinct characteristics like high surface area, porosity, and improved mass transport properties. These qualities render them suitable for a wide range of applications including catalysis, energy storage, biomedical fields, and electrochemical sensors. Dealloying or laser-induced technologies are the primary methods employed to fabricate such nanoporous materials. Dealloying is a dependable top-down approach used to produce hierarchical, disordered nanoporous materials with customizable pore sizes in the range of a few nanometers. The process of dealloying involves the selective elimination or dissolution of one or more elements from an alloy through a corrosion mechanism, using various dealloying techniques, such as chemical, electrochemical, liquid metal, or vapor phase dealloying. In the present study, copper-based amorphous metallic ribbons (Cu75Ni6Sn5P10Ga4) were initially manufactured using the melt-spinning method. The Cu-based amorphous ribbons were structurally investigated by X-ray diffraction and thermal analysis. Subsequently, the ribbons were subjected to a dealloying treatment, using an acidic solution to selectively dissolve the nickel from their composition and to obtain a nanoporous structure. The microstructure and chemical composition of the ribbons before and after the dealloying process were investigated using scanning electron microscopy (SEM), combined with energy-dispersive X-ray spectroscopy. The dealloying process performed in 1 M H2SO4 solution at 25 °C for 60 minutes leads to a large number of nanopores, uniformly distributed onto the surface of the Cu-based ribbons.    

    
