#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Thu Oct 10 01:19:43 2024

Found 2 results from 2024-10-03 to 2024-10-10
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Cellulose Pyrolysis via Liquid Metal Catalysis  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4403064947
:TOPICS: Biomass Pyrolysis and Conversion Technologies, Recycling Technologies for Carbon Fiber Composites, Characterization and Behavior of Nuclear Graphite Materials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jaap.2024.106800")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403064947"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403064947"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403064947"))][Get cited by]]

OpenAlex: https://openalex.org/W4403064947 (Open access: False)
    
[[https://openalex.org/A5107698611][Aaditya Hari Bharanidharan]], [[https://openalex.org/A5107698612][Kyle McGaugh]], [[https://openalex.org/A5107698613][Aime Laurent Twizeriman]], [[https://openalex.org/A5107698614][Kaylen Ocampo]], [[https://openalex.org/A5027700633][Götz Veser]], [[https://openalex.org/A5013059036][Mohammad S. Masnadi]], Journal of Analytical and Applied Pyrolysis. None(None)] 2024. https://doi.org/10.1016/j.jaap.2024.106800 
     
No abstract    

    

* Flexible Triboelectric Sensor based on Catalyst‐Diffusion Self‐Encapsulated Conductive Liquid‐Metal‐Silicone Ink for Somatosensory Soft Robotic System  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4403214305
:TOPICS: Wearable Nanogenerator Technology, Conducting Polymer Research, Tactile Perception and Cross-modal Plasticity
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202412293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403214305"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403214305"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403214305"))][Get cited by]]

OpenAlex: https://openalex.org/W4403214305 (Open access: False)
    
[[https://openalex.org/A5008857817][Shuai Xian]], [[https://openalex.org/A5010277066][Yong Xu]], [[https://openalex.org/A5006437625][Yixin Li]], [[https://openalex.org/A5001397144][Zhenfeng Wu]], [[https://openalex.org/A5103124477][Xing Xie]], [[https://openalex.org/A5018008505][Zhigang Wu]], [[https://openalex.org/A5089296010][Xiya Yang]], [[https://openalex.org/A5022694543][Yong Zhong]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202412293 
     
Abstract The combination of fluidity and metallic conductivity has attracted considerable attention to liquid metal (LM), but its development remains challenging due to enormous surface tension. Here, vinyl‐terminated silicone oil and platinum catalyst are added to LM to reduce its surface tension, which develops a special type of liquid‐metal‐silicone (LMS) ink with a catalyst diffusion effect. Combined with an embedded three‐dimentional (3D) printing method, the LMS ink is printed on the support matrix, and the catalyst diffuses outward along the print path to cure the silicone around it, directly constructing self‐encapsulated conductive composites with excellent conductivity and self‐encapsulated flexible tactile sensors based on triboelectric nanogenerator (TENG). The sensor exhibits excellent sensitivity (0.308 V kPa −1 ), high linearity (≈0.99), and good durability (over 10 000 cycles). Furthermore, when used in flexible wearable electronics, the sensor demonstrates a good performance with an accuracy of ≈96% in classifying different human postures using a convolutional neural network. Finally, through embedded 3D printing with LMS ink and silicone ink, a somatosensory soft robotic gripper with complex cavity structures is designed and manufactured in one step, achieving the all‐in‐one integration of sensors and actuators. This study shows great application potential in flexible electronics and soft robotic systems.    

    
