#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Mon Apr 29 01:04:52 2024

Found 1 results from 2024-04-22 to 2024-04-29
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Structural Evolution of GaOx-Shell and Intermetallic Phases in Ga–Pt Supported Catalytically Active Liquid Metal Solutions  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4395116373
:TOPICS: Catalytic Nanomaterials, Atomic Layer Deposition Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.3c03494")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4395116373"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4395116373"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4395116373"))][Get cited by]]

OpenAlex: https://openalex.org/W4395116373 (Open access: False)
    
[[https://openalex.org/A5083491990][Shaun A. Carl]], [[https://openalex.org/A5069346417][Johannes Will]], [[https://openalex.org/A5092677750][Nnamdi Madubuko]], [[https://openalex.org/A5016355522][Alexander Götz]], [[https://openalex.org/A5084701861][Thomas Przybilla]], [[https://openalex.org/A5090306088][Mingjian Wu]], [[https://openalex.org/A5009462940][Natarajan Raman]], [[https://openalex.org/A5037516157][Johannes Wirth]], [[https://openalex.org/A5001718718][Nicola Taccardi]], [[https://openalex.org/A5046935930][Benjamin Apeleo Zubiri]], [[https://openalex.org/A5040845269][Marco Haumann]], [[https://openalex.org/A5040845269][Marco Haumann]], [[https://openalex.org/A5039726667][Peter Wasserscheid]], [[https://openalex.org/A5039726667][Peter Wasserscheid]], [[https://openalex.org/A5062733366][Erdmann Spiecker]], The journal of physical chemistry letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.3c03494 
     
We present a comprehensive scale-bridging characterization approach for supported catalytically active liquid metal solutions (SCALMS) which combines lab-based X-ray microscopy, nano X-ray computed tomography (nano-CT), and correlative analytical transmission electron microscopy. SCALMS catalysts consist of low-melting alloy particles and have demonstrated high catalytic activity, selectivity, and long-term stability in propane dehydrogenation (PDH). We established an identical-location nano-CT workflow which allows us to reveal site-specific changes of Ga-Pt SCALMS before and after PDH. These observations are complemented by analytical transmission electron microscopy investigations providing information on the structure, chemical composition, and phase distribution of individual SCALMS particles. Key findings of this combined microscopic approach include (i) structural evolution of the SCALMS particles' GaOx shell, (ii) Pt segregation toward the oxide shell leading to the formation of Ga-Pt intermetallic phases, and (iii) cracking of the oxide shell accompanied by the release of liquid Ga-Pt toward the porous support.    

    
