#+filetags: liquid-metal
#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Sun Feb 25 14:23:18 2024

Found 1 results from 2024-02-18 to 2024-02-25
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* High‐Throughput Ammonia Production from Nitrate Using Liquid Metal Synthesized Bismuth Nano‐Catalyst  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4391946461
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Nanomaterials, Distributed Storage Systems and Network Coding
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202304287")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391946461"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391946461"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391946461"))][Get cited by]]

OpenAlex: https://openalex.org/W4391946461 (Open access: True)
    
[[https://openalex.org/A5002833522][Sahar Nazari]], [[https://openalex.org/A5028910777][Jing Sun]], [[https://openalex.org/A5074034078][Mahroo Baharfar]], [[https://openalex.org/A5079510232][Philippe Poulin]], [[https://openalex.org/A5067220816][Kourosh Kalantar‐zadeh]], [[https://openalex.org/A5032822192][Rouhollah Jalili]], [[https://openalex.org/A5074770372][Dorna Esrafilzadeh]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202304287 
     
Abstract The implementation of renewable energy sources to electrify ammonia (NH 3 ) production is identified as a critical approach for achieving successful decarburization in the pursuit of a more sustainable future. A liquid metal‐based method is presented for synthesizing bismuth (Bi) nano‐electrocatalysts, enabling efficient and sustainable ammonia production via nitrate electroreduction. Bi‐metal precipitated from a gallium liquid metal alloy yields solution‐processable Bi and oxide with controllable nanostructures such as nanosheets, nanotubes, and nanoparticles. Combining Bi nano‐electrocatalysts and graphene liquid crystals creates self‐assembling layered electrocatalytic systems. Integrating 3D printing technology allows for precise control over the geometry, microporosity, and number of deposited layers of the electrocatalytic scaffold electrode, resulting in improved mass transport properties, durability, and the prevention of catalyst detachment. Consequently, the ammonia production rate reaches 400 nmol s −1 cm −2 , with a Faradaic efficiency of over 90% and current densities exceeding 350 mA cm −2 . These numbers indicate the excellent scalability potential of the proposed electrocatalytic system.    

    
