#+filetags: liquid-metal
#+TITLE: liquid-metal
Created on Thu Jan 18 12:35:13 2024

Found 25 results from 2024-01-04 to 2024-01-18
** Liquid Metal Catalysis   
:PROPERTIES:
:ID: https://openalex.org/W4390621338
:DOI: https://doi.org/10.1007/978-981-19-2797-3_48-1
:AUTHORS: Shuting Liang
:HOST: No host
:END:

Shuting Liang, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-981-19-2797-3_48-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390621338"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390621338"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390621338"))][Get cited by]]

OpenAlex: https://openalex.org/W4390621338
    
Shuting Liang, No host. https://doi.org/10.1007/978-981-19-2797-3_48-1
    
With the rapid growth of the world population and the continuous shortage of resources and energy, the research on liquid metal catalyst has gradually come into view. In recent years, the development of liquid metal and its alloys as new catalysts has made a great leap forward. Liquid metals as flow catalysts offer new research and development opportunities. Applications of liquid metal systems include the catalytic controlled growth of graphene, the catalytic growth of 2D materials (MoO2, MoS2, SnOx, etc.), the catalytic reduction of CO2 to achieve carbon neutrality, the catalytic organic and inorganic reactions (including propane dehydrogenation, methane dehydrogenation, polyphenol self-polymerization, free radical polymerization, etc.), and the catalytic production of hydrogen. Liquid metal catalysts also include photocatalysts, electrocatalysts, bimetallic catalysts, LM/MO frame catalysts, and heterogeneous catalysts. The classification, application, and related catalytic mechanism of different liquid metal catalysts at home and abroad were reviewed in this chapter. Liquid metal catalysts could be used as revolutionary materials in the new century, and their application in the field of catalysis presents new challenges.    

    

** Intercalation of pyrazolone-based oxalamide metal complexes into Na-montmorillonite for catalytic liquid-phase oxidation of phenol using H2O2   
:PROPERTIES:
:ID: https://openalex.org/W4390605526
:DOI: https://doi.org/10.55730/1300-0527.3630
:AUTHORS: Serhat Uzan, Eyüp Başaran
:HOST: Turkish Journal of Chemistry
:END:

Serhat Uzan, Eyüp Başaran, Turkish Journal of Chemistry. 47(6)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.55730/1300-0527.3630")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390605526"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390605526"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390605526"))][Get cited by]]

OpenAlex: https://openalex.org/W4390605526
    
Serhat Uzan, Eyüp Başaran, Turkish Journal of Chemistry. https://doi.org/10.55730/1300-0527.3630
    
The intercalation of pyrazolone-based oxalamide metal complexes into Na-montmorillonite (Na-MMT) for catalytic liquid-phase oxidation of phenol using H2O2 was undertaken by a flexible ligand method using metal ions including Mn(II), Zn(II), and Sn(II). First, the metal ions were exchanged with the sodium ions of Na-MMT, and then these metal ions were complexed with a new pyrazolone-based oxalamide ligand. The intercalated metal complexes were characterized by Fourier transform infrared spectroscopy, X-ray diffraction, scanning electron microscopy, energy-dispersive X-ray spectroscopy, elemental analysis, and thermogravimetric analysis. Phenol was successfully oxidized by heterogeneous catalysts based on Mn(II), Zn(II), and Sn(II) pyrazolone-based oxalamide complexes intercalated into Na-MMT. These heterogeneous catalysts catalyze the liquid-phase oxidation of phenol using H2O2 to catechol as the major product and hydroquinone and benzoquinone as the minor products. The Mn(II) and Zn(II) complexes intercalated into Na-MMT showed better activity than the Sn(II) complex intercalated into Na-MMT and the reaction without the catalyst. It has been shown that some metal ion complexes intercalated into Na-MMT are active catalysts for liquid-phase oxidation of phenol with hydrogen peroxide.    

    

** Boosting the Catalytic Activity of Pd-Nanocatalysts by Anchoring Transition Metal Atoms on Carbon Supports for Formic Acid Dehydrogenation   
:PROPERTIES:
:ID: https://openalex.org/W4390910649
:DOI: https://doi.org/10.2139/ssrn.4696668
:AUTHORS: Qiuju Wang, Tian Zhou, Chunhui Wang, Longwei Li, Lianli Zou
:HOST: No host
:END:

Qiuju Wang, Tian Zhou, Chunhui Wang, Longwei Li, Lianli Zou, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4696668")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390910649"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390910649"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390910649"))][Get cited by]]

OpenAlex: https://openalex.org/W4390910649
    
Qiuju Wang, Tian Zhou, Chunhui Wang, Longwei Li, Lianli Zou, No host. https://doi.org/10.2139/ssrn.4696668
    
Liquid formic acid (FA) dehydrogenation, which needs high-performance catalysts to generate green hydrogen at room temperature, is a promising chemical hydrogen storage technology that can replace fossil fuels in energy-related devices. In this work, a novel nanocatalyst with ultrafine palladium nanoparticles immobilized on transition metal atom-decorated carbon supports was synthesized for the dehydrogenation of liquid FA. Via a hydrothermal of glucose and carbonitride with a following Co doping through a heat treatment process, porous carbons with evenly dispersed Co-sites on them were strategically achieved, which could be used as a support for immobilizing Pd nanoparticles. The obtained Pd/NC-Co1% catalyst exhibited much superior catalytic activities to those samples without Co doping on the support (Pd/NC and PdCo1%/NC), showing an impressive turnover frequency of 3045 h−1 at 50 °C for FA dehydrogenation. Other transition metal species such as Fe- and Ni-decorated carbon nanocatalysts also showed an improved catalytic activity for FA dehydrogenation. This work not only provide an efficient method to synthesize nanocatalysts with ultrafine metal nanoparticles but also demonstrate that highly dispersed metal atoms on the support can effectively affect the immobilized nanoparticles, resulting in an enhancement of catalytic performance.    

    

** Polyethylene Upgrading to Liquid Fuels Boosted by Atomic Ce Promoters   
:PROPERTIES:
:ID: https://openalex.org/W4390637146
:DOI: https://doi.org/10.1002/anie.202317594
:AUTHORS: Xueting Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang
:HOST: Angewandte Chemie International Edition
:END:

Xueting Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang, Angewandte Chemie International Edition. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202317594")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390637146"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390637146"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390637146"))][Get cited by]]

OpenAlex: https://openalex.org/W4390637146
    
Xueting Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang, Angewandte Chemie International Edition. https://doi.org/10.1002/anie.202317594
    
Hydrocracking catalysis is a key route to plastic waste upgrading, but the acid site‐driven C‐C cleavage step is relatively sluggish in conventional bifunctional catalysts, dramatically effecting the overall efficiency. We demonstrate here a facile and efficient way to boost the reactivity of acid sites by introducing Ce promoters into Pt/HY catalysts, thus achieving a better metal‐acid balance. Remarkably, 100 % of LDPE can be converted with 80.9 % selectivity of liquid fuels over the obtained Pt/5Ce‐HY catalysts at 300 °C in 2 h. For comparison, Pt/HY only gives 38.8% of LDPE conversion with 21.3% selectivity of liquid fuels. Through multiple experimental studies on the structure‐performance relationship, the Ce species occupied in the supercage are identified as the actual active sites, which possess remarkably‐improved adsorption capability towards short‐chain intermediates.    

    

** Polyethylene Upgrading to Liquid Fuels Boosted by Atomic Ce Promoters   
:PROPERTIES:
:ID: https://openalex.org/W4390637288
:DOI: https://doi.org/10.1002/ange.202317594
:AUTHORS: Xia Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang
:HOST: Angewandte Chemie
:END:

Xia Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang, Angewandte Chemie. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202317594")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390637288"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390637288"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390637288"))][Get cited by]]

OpenAlex: https://openalex.org/W4390637288
    
Xia Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang, Angewandte Chemie. https://doi.org/10.1002/ange.202317594
    
Hydrocracking catalysis is a key route to plastic waste upgrading, but the acid site‐driven C‐C cleavage step is relatively sluggish in conventional bifunctional catalysts, dramatically effecting the overall efficiency. We demonstrate here a facile and efficient way to boost the reactivity of acid sites by introducing Ce promoters into Pt/HY catalysts, thus achieving a better metal‐acid balance. Remarkably, 100 % of LDPE can be converted with 80.9 % selectivity of liquid fuels over the obtained Pt/5Ce‐HY catalysts at 300 °C in 2 h. For comparison, Pt/HY only gives 38.8% of LDPE conversion with 21.3% selectivity of liquid fuels. Through multiple experimental studies on the structure‐performance relationship, the Ce species occupied in the supercage are identified as the actual active sites, which possess remarkably‐improved adsorption capability towards short‐chain intermediates.    

    

** All Platinum Group Metal-Free and Durable Catalysts for Direct Borohydride Fuel Cells   
:PROPERTIES:
:ID: https://openalex.org/W4390722093
:DOI: https://doi.org/10.1021/acsaem.3c02578
:AUTHORS: Youngdon Ko, Junkil Park, Xiong Zhang, Liqun Kang, Thi Ha My Pham, Victor Boureau, Cuong Pham‐Huu, Jihan Kim, Liping Zhong, Andreas Züttel
:HOST: ACS Applied Energy Materials
:END:

Youngdon Ko, Junkil Park, Xiong Zhang, Liqun Kang, Thi Ha My Pham, Victor Boureau, Cuong Pham‐Huu, Jihan Kim, Liping Zhong, Andreas Züttel, ACS Applied Energy Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c02578")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390722093"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390722093"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390722093"))][Get cited by]]

OpenAlex: https://openalex.org/W4390722093
    
Youngdon Ko, Junkil Park, Xiong Zhang, Liqun Kang, Thi Ha My Pham, Victor Boureau, Cuong Pham‐Huu, Jihan Kim, Liping Zhong, Andreas Züttel, ACS Applied Energy Materials. https://doi.org/10.1021/acsaem.3c02578
    
Platinum group metal-free catalysts (e.g., Fe–N–C and Co–N–C) are used as hydrogen peroxide reduction reaction (PRR) catalysts in direct borohydride fuel cells (DBFCs). Fe–N–C is more active in the PRR and demonstrates high performance at the beginning of the DBFC test, whereas Co–N–C exhibits more stability in long-term operation. In the DBFC-accelerated durability test, Fe–N–C displays an activity decline of 18.6%, whereas Co–N–C exhibits a more stable performance, with an activity decrease of only 6.7%. In addition, the active site of Fe–N–C degrades more rapidly than that of Co–N–C in terms of demetalation of the central atom, as revealed by X-ray photoelectron spectroscopy. Furthermore, density functional theory simulations indicate that Co–N–C is more stable than Fe–N–C in both O2 and H2O2 environments. Overall, this study demonstrates that non-noble transition metal catalysts can fully replace platinum group metal catalysts at the cathode and anode in liquid-fuel-powered DBFC systems.    

    

** Review of electrocatalytic reduction of CO2 on carbon supported films   
:PROPERTIES:
:ID: https://openalex.org/W4390721078
:DOI: https://doi.org/10.1016/j.ijhydene.2024.01.022
:AUTHORS: Afdhal Yuda, Parisa Ebrahimi, Josephine Selvaraj, Anand Kumar, Vaidyanathan Subramanian
:HOST: International Journal of Hydrogen Energy
:END:

Afdhal Yuda, Parisa Ebrahimi, Josephine Selvaraj, Anand Kumar, Vaidyanathan Subramanian, International Journal of Hydrogen Energy. 57(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.022")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390721078"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390721078"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390721078"))][Get cited by]]

OpenAlex: https://openalex.org/W4390721078
    
Afdhal Yuda, Parisa Ebrahimi, Josephine Selvaraj, Anand Kumar, Vaidyanathan Subramanian, International Journal of Hydrogen Energy. https://doi.org/10.1016/j.ijhydene.2024.01.022
    
Carbon capture and conversion are becoming increasingly important as atmospheric CO2 concentrations rise and their adverse effects become increasingly evident. CO2 conversion/utilization-related research has gained renewed interest on a variety of platforms, including thermal, solar, biological, photochemical, and electrochemical conversions. Electrochemical routes, using suitable catalysts, are potentially suitable for commercial purposes owing to ease of integration with solvent-based carbon capture processes. This paper summarizes and evaluates the studies conducted within the past decade regarding the feasibility of carbon-based supports utilized in electrocatalytic carbon dioxide reduction. CO2 conversion has been reviewed in a number of reports, focusing on specific sections, such as metallic/bimetallic catalysts, CO2 solubility, and the fabrication of electrodes and electrochemical cells. The number of publications addressing various carbon-based electrocatalysts is increasing, but these materials have not yet been reviewed. Herein, we are focused on three types of electrocatalyst materials: metals, metal-oxides, non-oxides, and combinations thereof with carbon. The scope of this study includes the following: i) carbon-based materials and how they are characterized by distinctive properties, ii) electrocatalytic CO2 conversion techniques, and iii) research cases for carbon allotrope-supported composites used in CO2 reduction. The advancement in analytical tools that provide insight into liquid-phase reactions will benefit the development of catalysts and electrodes that will be effective in converting CO2 into the desired products. Such developments will also be applicable to other systems involving liquid electrolytes or solvents for performing reactions on catalyst surfaces.    

    

** Conversion of Co2 into Carbon Fiber Using Ga-Based Liquid Alloys   
:PROPERTIES:
:ID: https://openalex.org/W4390796939
:DOI: https://doi.org/10.2139/ssrn.4693252
:AUTHORS: Xin Cao, Yong-Kui Chang, Yang-Yang Yang, Hongfang Ma, Weiming Liu, Yixin Lü, Shyue-Yen Yao
:HOST: No host
:END:

Xin Cao, Yong-Kui Chang, Yang-Yang Yang, Hongfang Ma, Weiming Liu, Yixin Lü, Shyue-Yen Yao, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4693252")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390796939"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390796939"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390796939"))][Get cited by]]

OpenAlex: https://openalex.org/W4390796939
    
Xin Cao, Yong-Kui Chang, Yang-Yang Yang, Hongfang Ma, Weiming Liu, Yixin Lü, Shyue-Yen Yao, No host. https://doi.org/10.2139/ssrn.4693252
    
This study investigates the catalytic reduction of CO2 using various ratios of Ga-based liquid alloys under different conditions. We explored the doping of liquid gallium with metals like indium (In) and magnesium (Mg) through mechanical stirring and heating. The alloys, once prepared, were exposed to CO2 in a reactor, with the Ga-In-Mg alloy demonstrating optimal reaction effects. In an exemplary synthesis, 1g of Ga was combined with 30wt.% In and 7wt.% Mg, yielding a 7wt.% Ga-In-Mg alloy. This alloy, when reacted with CO2 for 10 hours, exhibited a maximum weight gain of 445 mg. Elemental analysis showed a carbon content increase from 4.56% to 72.56% post-reaction. The reacted alloy, post-acid washing and electron microscopy examination, revealed the production of carbon fibers approximately 7 μm wide. The primary objectives of this research were to identify the optimal temperature for CO2 reduction by the alloy and to determine the most efficient alloy catalyst using orthogonal experimental methods. Furthermore, we aimed to elucidate the catalytic mechanism of gallium-based liquid metal in CO2 reduction. The study also involved analyzing the adsorption and reaction processes by fitting the adsorption and reaction kinetic curves of the liquid metal with CO2. Achieving these objectives could enable the conversion of CO2 into solid carbon products, aligning with current environmental and sustainable development goals. This research offers new insights and innovative approaches to tackling energy-related challenges, highlighting the potential of liquid metal alloys in carbon capture and reduction applications.    

    

** CuNiZn vs CuZn Electrodes: Electrochemical CO<sub>2</sub> Reduction, Role of Metal Elements, and Insights for C–C Coupling Chemistry   
:PROPERTIES:
:ID: https://openalex.org/W4390563376
:DOI: https://doi.org/10.1021/acsaem.3c02550
:AUTHORS: Yunji Gwon, Seon Young Hwang, Go Eun Park, Sang-Eun Bae, Gak-Won Yun, Choong Kyun Rhee, Youngku Sohn
:HOST: ACS Applied Energy Materials
:END:

Yunji Gwon, Seon Young Hwang, Go Eun Park, Sang-Eun Bae, Gak-Won Yun, Choong Kyun Rhee, Youngku Sohn, ACS Applied Energy Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c02550")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390563376"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390563376"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390563376"))][Get cited by]]

OpenAlex: https://openalex.org/W4390563376
    
Yunji Gwon, Seon Young Hwang, Go Eun Park, Sang-Eun Bae, Gak-Won Yun, Choong Kyun Rhee, Youngku Sohn, ACS Applied Energy Materials. https://doi.org/10.1021/acsaem.3c02550
    
Exploring bi- and trimetallic catalysts in electrochemical CO2 reduction (EC CO2R) has been a focal point for discovering reduction products. This study investigates the distinct roles of metal elements in the CO2R using CuNiZn and CuZn electrodes. Bimetallic CuZn exhibits superior electrochemical activity, yielding substantial amounts of CO, CH4, C2H4, and various liquid products, including formate, ethanol, acetate, propanol, and isopropanol. The study on trimetallic CuNiZn suggests potential connections to Fischer–Tropsch (FT) synthesis, indicating their capability to produce long-chain hydrocarbons (CnH2n and CnH2n+2, n = 2–7) from CO2. EC CO reduction validated the FT process over the bi- and trimetallic catalysts. The discussion explores mechanisms for the formation of CO, CH4, and C–C coupled C2+ products, considering potential- and concentration-dependent Faradaic efficiencies (FEs). Recycling tests emphasize the influence of metal composition on FEs. Surface analyses reveal oxidation states and compositional changes, while the dissolution of metals during electrochemistry highlights dynamic surface characteristics. This work provides insights into the metal composition of bi- and trimetallic catalysts, surface states, and electrochemical conditions, advancing our understanding of these electrodes and their role in CO2 recycling through electrochemistry.    

    

** A magnetic pore-confined catalyst with ionic liquids supported on MOFs for the synthesis of aryl-oxazolidinones: design, performance, and recyclability   
:PROPERTIES:
:ID: https://openalex.org/W4390748587
:DOI: https://doi.org/10.1016/j.cej.2024.148678
:AUTHORS: Siying Chong, Jiaoyan Li, Shuang Zhao, G. Huang, Yajing Zhang, Rui Rui Liu, Kangjun Wang
:HOST: Chemical Engineering Journal
:END:

Siying Chong, Jiaoyan Li, Shuang Zhao, G. Huang, Yajing Zhang, Rui Rui Liu, Kangjun Wang, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148678")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390748587"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390748587"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390748587"))][Get cited by]]

OpenAlex: https://openalex.org/W4390748587
    
Siying Chong, Jiaoyan Li, Shuang Zhao, G. Huang, Yajing Zhang, Rui Rui Liu, Kangjun Wang, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2024.148678
    
Various methods have been explored for preparing heterogeneous catalysts using metal-organic framework (MOF) supported ionic liquids (ILs); however, it is challenging to develop such a synergistic catalyst that combines high efficiency, stability, the capability of maintaining immobilized ILs and active components, and high recovery efficiency. In this study, we successfully developed a magnetic MOF sub-nanostructured carrier by integrating organic UiO-66 with magnetic nanoparticles (MNPs). The resulting magnetic pore-confined catalyst, named MAG-UiO-66-IL(OAc), was prepared by in-situ self-assembly of pore-confining [C4mim] [OAc] within the nano-cavities of the magnetic MOF carrier. The morphology, structure, and thermal properties of the magnetic pore-confined catalyst were comprehensively characterized using various techniques. The novel catalyst MAG-UiO-66-IL(OAc) demonstrated remarkable catalytic efficiency in transforming cyclic carbonates and aryl amines to aryl-oxazolidinones, achieving yields up to 95% under mild solvent-free conditions. Furthermore, the catalyst showed exceptional recyclability, retaining its catalytic activity after ten successive reuses. Notably, the catalyst displayed excellent performance for reactions involving large-size reactants, expanding the range of substrate usability beyond previously reported solid-loading catalysts. Theoretical calculations were also conducted to complement the experimental results, providing valuable insights into the structure–activity relationship between the magnetic MOF carrier and the ionic liquid. These findings emphasize the significance of molecular-scale confinement on reactant diffusion and the overall reaction process, offering valuable guidance for the design of catalyst microstructures and the modulation of reaction performance.    

    

** Reversible hydrogenation and dehydrogenation of benzene for hydrogen storage on highly dispersed Pd/γ-Al2O3 catalyst   
:PROPERTIES:
:ID: https://openalex.org/W4390724268
:DOI: https://doi.org/10.1016/j.jiec.2024.01.018
:AUTHORS: Guilin Zhou, Wenjing Liu, Yue Zhao, Xiaoping Wang, Shuang Chen, Aiping Jia, Hongmei Xie
:HOST: Journal of Industrial and Engineering Chemistry
:END:

Guilin Zhou, Wenjing Liu, Yue Zhao, Xiaoping Wang, Shuang Chen, Aiping Jia, Hongmei Xie, Journal of Industrial and Engineering Chemistry. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jiec.2024.01.018")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390724268"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390724268"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390724268"))][Get cited by]]

OpenAlex: https://openalex.org/W4390724268
    
Guilin Zhou, Wenjing Liu, Yue Zhao, Xiaoping Wang, Shuang Chen, Aiping Jia, Hongmei Xie, Journal of Industrial and Engineering Chemistry. https://doi.org/10.1016/j.jiec.2024.01.018
    
The research and development of efficient catalyst is the key to achieving high-capacity hydrogen storage in liquid organic hydrogen carriers (LOHCs). The highly dispersed Pd/γ-Al2O3 catalysts with few-atom Pd were prepared by impregnation method using HNO3 as promoter. The hydrogen storage capacity of the benzene/cyclohexane hydrogen carriers was further investigated by vapor phase benzene hydrogenation and cyclohexane dehydrogenation reactions over the studied Pd/γ-Al2O3 catalysts. The results showed that the metal Pd was the active centers for the benzene hydrogenation/cyclohexane dehydrogenation reactions. The addition of HNO3 can effectively promote the metal Pd to be highly dispersed, thus improving the Pd atoms utilization and reducing the Pd dosage. Meanwhile, the strongly electronic effects between the highly dispersed Pd species and the Al2O3 support promoted the electron-deficient Pdδ+ sites to be formed, which enhanced the adsorption and activation ability for the reactants molecules. The benzene conversion on the Pd/γ-Al2O3 catalyst with a metallic Pd loading of 1.0 wt.% reached 97.51 % at 200 °C. While the cyclohexane conversion reached 90.94 % at 400 °C with the actual hydrogen storage capacity of 6.54 wt.%, which provided an effective idea for large-scale storage and transportation of H2 based on LOHCs.    

    

** Nickel Carbide Nanoparticle Catalyst for Selective Hydrogenation of Nitriles to Primary Amines   
:PROPERTIES:
:ID: https://openalex.org/W4390615119
:DOI: https://doi.org/10.1002/chem.202303573
:AUTHORS: Sho Yamaguchi, Daiki Kiyohira, Kohei Tada, Taiki Kawakami, Akira Miura, Takato Mitsudome, Tomoo Mizugaki
:HOST: Chemistry - A European Journal
:END:

Sho Yamaguchi, Daiki Kiyohira, Kohei Tada, Taiki Kawakami, Akira Miura, Takato Mitsudome, Tomoo Mizugaki, Chemistry - A European Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202303573")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390615119"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390615119"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390615119"))][Get cited by]]

OpenAlex: https://openalex.org/W4390615119
    
Sho Yamaguchi, Daiki Kiyohira, Kohei Tada, Taiki Kawakami, Akira Miura, Takato Mitsudome, Tomoo Mizugaki, Chemistry - A European Journal. https://doi.org/10.1002/chem.202303573
    
Despite its unique physicochemical properties, the catalytic application of nickel carbide (Ni3C) in organic synthesis is rare. In this study, we report well‐defined nanocrystalline Ni3C (nano‐Ni3C) as a highly active catalyst for the selective hydrogenation of nitriles to primary amines. The activity of the aluminum‐oxide‐supported nano‐Ni3C (nano‐Ni3C/Al2O3) catalyst surpasses that of Ni nanoparticles. Various aromatic and aliphatic nitriles and dinitriles were successfully converted to the corresponding primary amines under mild conditions (1 bar H2 pressure). Furthermore, the nano‐Ni3C/Al2O3 catalyst was reusable and applicable to gram‐scale experiments. Density functional theory calculations suggest the formation of polar hydrogen species on the nano‐Ni3C surface, which were attributed to the high activity of nano‐Ni3C towards nitrile hydrogenation. This study demonstrates the utility of metal carbides as a new class of catalysts for liquid‐phase organic reactions.    

    

** Ionic liquid dopant induced 3D hierarchical CuO nanostructures with doped heteroatoms and highly dispersed Ag for electrochemical upgrading of 5-hydroxymethylfurfural   
:PROPERTIES:
:ID: https://openalex.org/W4390636084
:DOI: https://doi.org/10.1016/j.cej.2024.148580
:AUTHORS: Chaofan Li, Fengke Wang, Yi Nie, Leilei Wang, Zhihao Zhang, Tianhao Liu, Binghui He, Yunqian Ma, Lihua Zang
:HOST: Chemical Engineering Journal
:END:

Chaofan Li, Fengke Wang, Yi Nie, Leilei Wang, Zhihao Zhang, Tianhao Liu, Binghui He, Yunqian Ma, Lihua Zang, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148580")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390636084"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390636084"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390636084"))][Get cited by]]

OpenAlex: https://openalex.org/W4390636084
    
Chaofan Li, Fengke Wang, Yi Nie, Leilei Wang, Zhihao Zhang, Tianhao Liu, Binghui He, Yunqian Ma, Lihua Zang, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2024.148580
    
The electrocatalytic 5-hydroxymethylfurfural oxidation reaction (HMFOR) has received increasing attention due to its carbon–neutral and value-added chemical properties, and the development of electrocatalyst with highly active and selective is crucial. Highly dispersing metal atoms throughout the catalyst can maximize the catalytic efficiency. Here, we synthesized a 3D hierarchical CuO nanostructure induced by ionic liquid with heteroatoms doping and Ag dispersing (Ag-CuO@IL), and this self-supported catalyst can reach 10 mA cm−2 at only 1.33 V vs RHE and achieved HMF conversion of 98.5 %, FDCA yield of 97.1 % and Faraday efficiency of 92.2 %. The excellent catalytic performance of Ag-CuO@IL for HMFOR is attributed to the doped heteroatoms derived from ILs to promote electron redistribution and the generated oxygen vacancies induced by IL anions to highly disperse Ag. Also, the catalyst was the nanosheet-assembled spherical clusters with 3D nanostructure, which exposed a large number of active sites. Density functional theory calculations showed that Ag-CuO@IL possessed moderate adsorption strengths of HMF and OH–, thus facilitating the desorption of the products in the reaction process. The design that induced by ionic liquid dopant not only provides an effective and green mean for HMFOR, but also has the large potential to guide the synthesis of other catalysts with improved performances in various applications.    

    

** Mercury removal performance of sulfated MnCe catalyst prepared by tobacco waste combustion synthesis   
:PROPERTIES:
:ID: https://openalex.org/W4390848176
:DOI: https://doi.org/10.1016/j.fuel.2024.130894
:AUTHORS: Dejun Peng, Zijian Zhou, Yue Zhou, Qi Guo, Siyi Peng, Xiaowei Liu, Minghou Xu
:HOST: Fuel
:END:

Dejun Peng, Zijian Zhou, Yue Zhou, Qi Guo, Siyi Peng, Xiaowei Liu, Minghou Xu, Fuel. 363(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.130894")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390848176"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390848176"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390848176"))][Get cited by]]

OpenAlex: https://openalex.org/W4390848176
    
Dejun Peng, Zijian Zhou, Yue Zhou, Qi Guo, Siyi Peng, Xiaowei Liu, Minghou Xu, Fuel. https://doi.org/10.1016/j.fuel.2024.130894
    
MnOx-CeO2 is a promising catalyst for Hg0 removal from coal flue gas at ∼150 °C but exhibits insufficient catalytic activity. Even though sulfation enhances the catalytic activity of MnOx-CeO2, gas-phase sulfation leads to SO2 poisoning and catalyst deactivation. In this study, we developed a liquid-phase sulfation strategy involving the direct combustion of cigarette butts soaked in a solution of sulfate and metal precursors to directly synthesize sulfated MnCe catalyst (SMC). SMC was characterized via N2 adsorption–desorption isotherms, SEM-EDS, XRD, XPS, and Hg-TPD. Both the MnCe catalyst and SMC exhibited good Hg0 oxidation efficiencies (66.46 % and 88.76 %, respectively) at 150 °C. The enhanced performance of SMC was attributed to the generation of abundant chemically adsorbed oxygen species on the SMC surface during sulfation. Moreover, the synergistic effect between the Ce4+ and Mn4+ species contributed to the improved catalytic performance of SMC. This strategy not only provides a one-step synthesis of sulfated catalysts but also has potential applications in Hg0 removal from coal flue gas in coal-fired power plants.    

    

** Functionalized palm biomass-derived activated carbon for the removal of Pt(IV) from a simulated leachate   
:PROPERTIES:
:ID: https://openalex.org/W4390848579
:DOI: https://doi.org/10.1016/j.biombioe.2024.107055
:AUTHORS: M.L. Firmansyah, Natalia I. Wulan, Alifya P. Nurisca, Karthickeyan Viswanathan, Aishah Abdul Jalil
:HOST: Biomass and Bioenergy
:END:

M.L. Firmansyah, Natalia I. Wulan, Alifya P. Nurisca, Karthickeyan Viswanathan, Aishah Abdul Jalil, Biomass and Bioenergy. 181(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.biombioe.2024.107055")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390848579"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390848579"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390848579"))][Get cited by]]

OpenAlex: https://openalex.org/W4390848579
    
M.L. Firmansyah, Natalia I. Wulan, Alifya P. Nurisca, Karthickeyan Viswanathan, Aishah Abdul Jalil, Biomass and Bioenergy. https://doi.org/10.1016/j.biombioe.2024.107055
    
Over the years, demand for Platinum Group Metals (PGMs) has grown steadily due to increased production of various advanced technologies, such as automotive and electronic products. PGMs are predominantly used in automotive catalysts in the automotive industry. Along with the increase in automotive production, deactivated automotive catalysts pose environmental and health hazards. These wastes are excellent alternative sources of PGMs, which can be exploited to bridge the gap between the demand and supply of PGMs. Adsorption is one of the most popular metal removal/recovery methods due to its various advantages, such as ease of use and cost-effectiveness. In consideration of this method, developing an inexpensive and efficient adsorbent is a crucial point. Thus, activated carbon (AC), derived from a palm kernel shell that is abundantly available in Indonesia, was functionalized using ionic liquid (ACIL) and used for Pt(IV) removal from a simulated automotive catalyst waste leachate. The functionalized AC showed a high adsorption capacity (178.6 mg g−1), in which the adsorption of Pt(IV) followed a chemisorption route, fitting with the monolayer model. The functionalized adsorbent also showed excellent performance during continuous Pt(IV) adsorption from simulated leachate. Recovery of precious metals, such as Pt(IV) and Pd(II), from the simulated leachate containing other metals was possible by maintaining the high hydrochloric acid concentration. Furthermore, targeted separation of Pt(IV) was achieved through sequential desorption using NaClO4. In addition, ACIL showed remarkable reusability after being used for three cycles without showing a noticeable decrease in performance. Thus, this study highlights the capability of a functionalized adsorbent from palm oil industry biomass to recover precious metals from simulated leachate of automotive waste.    

    

** Saccharide formation by sustainable formose reaction using heterogeneous zeolite catalysts   
:PROPERTIES:
:ID: https://openalex.org/W4390768301
:DOI: https://doi.org/10.1039/d3dt02321d
:AUTHORS: Minoru Waki, Soichi Shirai, Yoko Hase
:HOST: Dalton Transactions
:END:

Minoru Waki, Soichi Shirai, Yoko Hase, Dalton Transactions. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3dt02321d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390768301"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390768301"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390768301"))][Get cited by]]

OpenAlex: https://openalex.org/W4390768301
    
Minoru Waki, Soichi Shirai, Yoko Hase, Dalton Transactions. https://doi.org/10.1039/d3dt02321d
    
The formose reaction is a unique chemical reaction for the preparation of saccharides from formaldehyde, a single carbon compound. We applied zeolite materials as heterogeneous catalysts to the formose reaction. The simple addition of Linde type A zeolite containing calcium ions (Ca-LTA) to an aqueous solution of formaldehyde and glycolaldehyde produced saccharides at room temperature. A quantitative analysis performed by high-performance liquid chromatography revealed that triose, tetrose, pentose, and hexose saccharides were produced with few byproducts. Ca-LTA was recovered from the reaction mixture by filtration, and the retrieved zeolite was found to be reusable under the same conditions. The catalytic activity of Ca-LTA was higher than those of conventional calcium catalysts and other solid materials such as silica, alumina, and hydroxyapatite. Several other types of zeolites with different crystal structures and alkali/alkali-earth metal ions also showed catalytic activity for saccharide formation. Based on the analytical results obtained by infrared spectroscopy, temperature-programmed desorption profiles and NMR measurements, we propose a reaction mechanism in which C-C bond formation is promoted by the mild basicity of the oxygen atoms and acidity on the metal ions of the aluminosilicate on the zeolite surfaces with low SiO2/Al2O3 ratios.    

    

** Enhanced Hydroconversion of Polyethylene Via Dual-Functional Catalysis: Exploiting Zsm-22 Pore-Mouth Catalysis and Ru Electronic Effect   
:PROPERTIES:
:ID: https://openalex.org/W4390904224
:DOI: https://doi.org/10.2139/ssrn.4697149
:AUTHORS: Liangliang Cheng, Shaonan Tian, Dong Liang, Jing Gu, Ruizhe Chen, Xueru Chen, Haoran Yuan, Yong Chen
:HOST: No host
:END:

Liangliang Cheng, Shaonan Tian, Dong Liang, Jing Gu, Ruizhe Chen, Xueru Chen, Haoran Yuan, Yong Chen, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4697149")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390904224"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390904224"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390904224"))][Get cited by]]

OpenAlex: https://openalex.org/W4390904224
    
Liangliang Cheng, Shaonan Tian, Dong Liang, Jing Gu, Ruizhe Chen, Xueru Chen, Haoran Yuan, Yong Chen, No host. https://doi.org/10.2139/ssrn.4697149
    
The low-temperature hydroconversion of polyethylene is a subject of extensive research, where the one-step synthesis of iso-alkanes via metal-acid bifunctional catalysis emerges as a promising strategy. Zeolites, favored for their superior compatibility with prevalent petrochemical equipment, are typically utilized as acidic supports. Herein, we loaded Ru nanoparticles onto ZSM-22, known for its pore-mouth catalysis. Mechanical ball milling was employed to augment the pore-mouth area and proximity of metal-acid sites, markedly fostering the hydrocracking reaction. Additionally, by employing various Ru precursors and adjusting load quantities, we modified Ru's electronic properties. In-situ infrared observations revealed that the detachment of olefin intermediates from Ru sites is instrumental in regulating hydrocracking and terminal hydrogenolysis reactions. Incorporating catalyst characterization with DFT-generated reaction barrier computations, we discovered that oxidized Ru species facilitate the release of olefin intermediates, thereby enabling subsequent Brønsted acid-driven β-scission and isomerization reactions. Utilizing commercially accessible catalysts, this study achieved a liquid-phase yield exceeding 82 wt.% and an iso/n ratio surpassing 60% under conditions of low energy consumption.    

    

** Uncovering the Synergy between Gold and Sodium on ZrO2 for Boosting the Reverse Water Gas Shift Reaction: In-Situ Spectroscopic Investigations   
:PROPERTIES:
:ID: https://openalex.org/W4390570953
:DOI: https://doi.org/10.1016/j.apcatb.2023.123685
:AUTHORS: Abdallah I.M. Rabee, Sebastián Cisneros, Dan Zhao, Carsten Kreyenschulte, Stephan Bartling, Vita A. Kondratenko, Christoph Kubis, Evgenii V. Kondratenko, Angelika Brückner, Jabor Rabeah
:HOST: Applied Catalysis B: Environmental
:END:

Abdallah I.M. Rabee, Sebastián Cisneros, Dan Zhao, Carsten Kreyenschulte, Stephan Bartling, Vita A. Kondratenko, Christoph Kubis, Evgenii V. Kondratenko, Angelika Brückner, Jabor Rabeah, Applied Catalysis B: Environmental. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2023.123685")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390570953"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390570953"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390570953"))][Get cited by]]

OpenAlex: https://openalex.org/W4390570953
    
Abdallah I.M. Rabee, Sebastián Cisneros, Dan Zhao, Carsten Kreyenschulte, Stephan Bartling, Vita A. Kondratenko, Christoph Kubis, Evgenii V. Kondratenko, Angelika Brückner, Jabor Rabeah, Applied Catalysis B: Environmental. https://doi.org/10.1016/j.apcatb.2023.123685
    
CO2 conversion to CO via the reverse water-gas shift (RWGS) reaction is a promising source of syngas for subsequent synthesis of liquid fuels and chemicals. Herein, we present the synthesis of catalysts containing Au supported on hydroxylated Na-modified ZrO2, with Au amounts ranging from 0.05 to 1 wt.%. Systematic investigations reveal the formation of cooperative Au/Na sites at the interface. These sites cooperate synergistically to activate CO2 and generate a high surface density of carboxylate-like species, which serve as highly active intermediates for CO formation. It was found that the RWGS reaction on the catalyst with low Au loading proceeds mainly via a carboxylate pathway, with bidentate formate acting as spectators. At higher Au loading, the bidentate formate pathway contributes somewhat to CO formation alongside the carboxylate pathway. Based on temporal analysis of products, we emphasize the significant roles of H2 spillover and the metal-support interface in the RWGS reaction.    

    

** Analysis of kinetics, mechanism, thermodynamic properties and product distribution for pyrolysis of Ni–Fe impregnated coconut husk   
:PROPERTIES:
:ID: https://openalex.org/W4390776076
:DOI: https://doi.org/10.1016/j.renene.2024.119972
:AUTHORS: Rakesh Kumar, P. K. Dubey, Monoj Kumar Mondal
:HOST: Renewable Energy
:END:

Rakesh Kumar, P. K. Dubey, Monoj Kumar Mondal, Renewable Energy. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.renene.2024.119972")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390776076"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390776076"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390776076"))][Get cited by]]

OpenAlex: https://openalex.org/W4390776076
    
Rakesh Kumar, P. K. Dubey, Monoj Kumar Mondal, Renewable Energy. https://doi.org/10.1016/j.renene.2024.119972
    
This study explored on pyrolytic thermal degradation of coconut husk (CH), treated with Ni–Fe electroplating wastewater and Ni–Fe synthetic water, for bioenergy generation. Initially, green coconut husk absorbed solutions resembling electroplating effluent and synthetic Ni–Fe at 105 °C. Physiochemical properties of the husk and ICP-MS analysis of water were thoroughly examined before TG/DTG analysis. The impact of catalysts on pyrolysis was assessed through TG/DTG measurement, the obtained results were utilized to study the kinetics and thermodynamic parameters using the iso-conversional approaches (FWO, KAS, Starink) and Criado plots were used to discuss the reaction mechanism. Metal impregnated biomass with wastewater (MICHw) found to have high activation energy compared to that of metal impregnated with synthetic water (MICHs). For MICHw, average activation energies were calculated as 132.22, 151.37, and 149.78 kJ/molefegurefff for FWO, KAS, Starink, respectively, however, for MICHs the values were 114.79, 114.03.71, and 114.75 kJ/mol. The potential energy barrier (6–10 kJ/mol) between activation energy and reaction enthalpy showed a favourable environment for product development. Various experiments on native green coconut husk (NGCH) and impregnated coconut husk under different conditions showed a higher liquid oil yield for MICHw, attributed to the Ni–Fe catalyst at 650 °C and smaller particle sizes. This research provides key insights into enhancing bioenergy production through the pyrolytic conversion of impregnated coconut husk, highlighting the pivotal role of wastewater-derived catalysts.    

    

** Lignin carbon-initiated Ni/K/Mo2C catalyst for efficient synthesis of higher alcohols from syngas   
:PROPERTIES:
:ID: https://openalex.org/W4390901127
:DOI: https://doi.org/10.1016/j.cej.2024.148751
:AUTHORS: Shihang Meng, Jiafeng Gu, Siyi Jiang, Yujing Weng, Chao Huang, Pengfei Ren, Xiangxin Xue, Qi Sun, Yulong Zhang, Maohong Fan
:HOST: Chemical Engineering Journal
:END:

Shihang Meng, Jiafeng Gu, Siyi Jiang, Yujing Weng, Chao Huang, Pengfei Ren, Xiangxin Xue, Qi Sun, Yulong Zhang, Maohong Fan, Chemical Engineering Journal. 481(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148751")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390901127"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390901127"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390901127"))][Get cited by]]

OpenAlex: https://openalex.org/W4390901127
    
Shihang Meng, Jiafeng Gu, Siyi Jiang, Yujing Weng, Chao Huang, Pengfei Ren, Xiangxin Xue, Qi Sun, Yulong Zhang, Maohong Fan, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2024.148751
    
Bamboo lignin, the principal constituent of non-wood pulping black liquor, is ecologically and environmentally harmful due to its complex molecular structure and stability. Additionally, the syngas-based synthesis of higher alcohols is a desired industrial application, alleviating the dependency on petroleum resources. However, developing highly efficient catalysts with high space–time yield and selectivity towards higher alcohols remains challenging. Herein, for the first time, taking into account the permeable structure of bamboo lignin in paper-making black liquid resulting from cellulose and hemicellulose extraction, porous nano molybdenum carbide was manufactured by designed pretreatment and activation processes of the lignin, which was further doped by the K and Ni additive to create a highly efficient catalyst (Ni/K/Mo2C@LC) for the high alcohols synthesis reaction, yielding a surprising space–time yield of 0.455 g/gcat/h) to alcohol products under the optimal reaction conditions. Control experiments and characterizations were conducted over relevant catalysts, revealing that Ni and K could be integrated to regulate the adsorption property, acidity/basicity, and carbon chain growth ability of the catalysts. Also, the open mesoporous lignin carbon provided larger metal particles, enhancing the hydrogenation ability and better balancing the non-dissociative and dissociative active sites for the high alcohol synthesis reaction. These results provide insights into the structure design of carbide catalysts toward efficiently utilizing industrial lignin and other biomass-derived feedstocks, and the development of an efficient Mo-based catalyst for syngas conversion.    

    

** Enhancing the Production of Phenolic Monomers from Reductive Catalytic Fractionation of Biomass over Catalyst of Ni–N-Doped Carbon   
:PROPERTIES:
:ID: https://openalex.org/W4390754872
:DOI: https://doi.org/10.1021/acssuschemeng.3c06294
:AUTHORS: Kai Wu, Bingbing Luo, Yang Ke, Siyu Wang, Mingfan Li, Huiyan Zhang
:HOST: No host
:END:

Kai Wu, Bingbing Luo, Yang Ke, Siyu Wang, Mingfan Li, Huiyan Zhang, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acssuschemeng.3c06294")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390754872"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390754872"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390754872"))][Get cited by]]

OpenAlex: https://openalex.org/W4390754872
    
Kai Wu, Bingbing Luo, Yang Ke, Siyu Wang, Mingfan Li, Huiyan Zhang, No host. https://doi.org/10.1021/acssuschemeng.3c06294
    
Phenolic monomers and polysaccharides from the reductive catalytic fractionation of biomass are extremely important precursors for producing chemicals and liquid fuels instead of excessive consumption of fossil fuels. In this work, a novel Ni–N-doped catalyst (Ni/Cf) prepared by the metal and bacterial residue carbon was employed for promoting the production of phenolic monomers. The several key parameters such as reaction temperature, pressure, time, gas types, catalyst types, and catalyst carriers were systematically optimized. The experimental results demonstrated that the lignin-derived phenolic monomer (LDPM) yield of 45.2 wt % and holocellulose retention rate of 96.0% were obtained by the birch RCF over Ni/Cf accompanied by the optimal reaction conditions of 220 °C, 3 h, and 2 MPa H2. The LDPM yield of birch over Ni/Cf was about 5.4 times and 3.1 times higher than that of Ni/Cf-u and Cf, respectively, and even better than Ni/AC, Ru/C, and Pd/C. The characterization analyses exhibited that the Ni–N-doped catalyst contained large specific surface areas, small particle sizes, microporous structures, and medium acid sites while increasing the electron transfer and interaction among C–O–N–Ni. These key factors jointly realized the efficient depolymerization of lignin into phenolic monomers and high-retention holocellulose.    

    

** Recent advances on application of Metal-Organic framework based catalysts in biodiesel production Process: A review of catalyst types and Activity, challenges and opportunities   
:PROPERTIES:
:ID: https://openalex.org/W4390848682
:DOI: https://doi.org/10.1016/j.fuel.2024.130905
:AUTHORS: Majid Saidi, Reza Amirnia
:HOST: Fuel
:END:

Majid Saidi, Reza Amirnia, Fuel. 363(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.130905")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390848682"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390848682"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390848682"))][Get cited by]]

OpenAlex: https://openalex.org/W4390848682
    
Majid Saidi, Reza Amirnia, Fuel. https://doi.org/10.1016/j.fuel.2024.130905
    
Metal-organic frameworks (MOFs), as a class of crystalline porous coordinated materials, have become significant candidates in various applications through their outstanding characteristics such as high surface area, large pore size, tunable porosity, and high thermal stability. Therefore, MOFs are capable of being used as heterogeneous catalysts directly, or as carriers for homogenous catalysts to enhance their surface area, stability, and recovery. One of the fields of catalytic activities of MOFs is accelerating the rate of biodiesel production. Biodiesel is a clean and renewable fuel made by esterification of free fatty acids (FFAs) or transesterification of triglycerides. FFAs and triglycerides can be provided from different sources; edible oils, non-edible oils, algal lipids, etc. To carry out esterification/transesterification reactions, a decent catalyst with proper acidic or basic properties is required. The catalyst is mostly preferred to be heterogenous to overcome separation challenges. Here, a comprehensive review has been conducted on studies from 2014 onwards that focus on using different types of MOFs as heterogeneous catalysts or as supports for immobilizing other species such as heteropoly acids, ionic liquids, and enzymes for biodiesel production process. Most of the studies have exhibited satisfying results, with biodiesel yield exceeding 90%, and having excellent catalyst’s reusability with nearly the same functionality as the first cycle. Different methods of MOFs synthesis, their characterization by using different techniques and other applications of MOFs have been discussed as well. Consequently, a brief conclusion about the most favored MOFs in biodiesel production and their future perspective is presented.    

    

** A Kinetic Model of Furfural Hydrogenation to 2-Methylfuran on Nanoparticles of Nickel Supported on Sulfuric Acid-Modified Biochar Catalyst   
:PROPERTIES:
:ID: https://openalex.org/W4390740134
:DOI: https://doi.org/10.3390/catal14010054
:AUTHORS: Ismaila Mudi, Abarasi Hart, Andrew Ingram, Joseph Wood
:HOST: Catalysts
:END:

Ismaila Mudi, Abarasi Hart, Andrew Ingram, Joseph Wood, Catalysts. 14(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14010054")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390740134"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390740134"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390740134"))][Get cited by]]

OpenAlex: https://openalex.org/W4390740134
    
Ismaila Mudi, Abarasi Hart, Andrew Ingram, Joseph Wood, Catalysts. https://doi.org/10.3390/catal14010054
    
Lignocellulosic biomass can uptake CO2 during growth, which can then be pyrolysed into three major products, biochar (BC), syngas, and bio-oil. Due to the presence of oxygenated organic compounds, the produced bio-oil is not suitable for direct use as a fuel and requires upgrading via hydrodeoxygenation (HDO) and hydrogenation. This is typically carried out over a supported metal catalyst. Regarding circular economy and sustainability, the BC from the pyrolysis step can potentially be activated and used as a novel catalyst support, as reported here. A 15 wt% Ni/BC catalyst was developed by chemically modifying BC with sulfuric acid to improve mesoporous structure and surface area. When compared to the pristine Ni/BC catalyst, sulfuric activated Ni/BC catalyst has excellent mesopores and a high surface area, which increases the dispersion of Ni nanoparticles and hence improves the adsorptive effect and thus catalytic performance. A liquid phase hydrogenation of furfural to 2-methylfuran was performed over the developed 15 wt% Ni/BC catalyst. Langmuir–Hinshelwood–Hougen–Watson (LHHW) kinetic type models for adsorption of dissociative H2 were screened based on an R2 value greater than 99%, demonstrating that the experimental data satisfactorily fit to three plausible models: competitive (Model I), competitive at only one type of adsorption site (Model II), and non-competitive with two types of adsorption sites (Model III). With a correlation coefficient greater than 99% between the experimental rates and the predicted rate, Model III, which is a dual-site adsorption mechanism involving furfural adsorption and hydrogen dissociative adsorption and surface reaction, is the best fit. The Ni/BC catalyst demonstrated comparative performance and significant cost savings over previous catalysts; a value of 24.39 kJ mol−1 was estimated for activation energy, −11.43 kJ mol−1 for the enthalpy of adsorption for H2, and −5.86 kJ mol−1 for furfural. The developed Ni/BC catalyst demonstrated excellent stability in terms of conversion of furfural (96%) and yield of 2-methylfuran (54%) at the fourth successive experiments. Based on furfural conversion and yield of products, it appears that pores are constructed slowly during sulfuric acid activation of the biochar.    

    

** The role of added oxidising agents in assisting the photocatalytic treatment of olive mill wastewater using a metal-free g-C3N4 optical semiconductor   
:PROPERTIES:
:ID: https://openalex.org/W4390629322
:DOI: https://doi.org/10.1016/j.jwpe.2023.104722
:AUTHORS: André Torres‐Pinto, Ana R. Fernandes, Cláudia G. Silva, Joaquim L. Faria, Adrián M.T. Silva
:HOST: Journal of Water Process Engineering
:END:

André Torres‐Pinto, Ana R. Fernandes, Cláudia G. Silva, Joaquim L. Faria, Adrián M.T. Silva, Journal of Water Process Engineering. 58(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jwpe.2023.104722")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390629322"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390629322"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390629322"))][Get cited by]]

OpenAlex: https://openalex.org/W4390629322
    
André Torres‐Pinto, Ana R. Fernandes, Cláudia G. Silva, Joaquim L. Faria, Adrián M.T. Silva, Journal of Water Process Engineering. https://doi.org/10.1016/j.jwpe.2023.104722
    
Olive mill wastewaters (OMW) consist of high organic contents and are harmful to aquatic and terrestrial biota. Heterogeneous photocatalysis is a technology that can be operated under mild conditions to remove pollutants in the liquid phase. In the present work, graphitic carbon nitride (g-C3N4, hereafter referred to as GCN) is studied for the first time as a metal-free photocatalyst for OMW treatment. The integration with peroxidation (H2O2), Fenton (Fe2+/H2O2 at both acidic and natural pH), chlorination (HOCl/ClO−) or persulfate (PS) activation is also investigated. This catalyst potentiated the activation of these oxidants, and H2O2 was identified as the best option to achieve high removals of total phenolic content – TPh (87.5 ± 0.3 %), dissolved organic carbon – DOC (63.8 ± 0.4 %) and chemical oxygen demand – COD (87.7 ± 0.6 %), without need to add iron or adjust the pH. The stability and reusability of the GCN material in the H2O2-assisted photocatalytic treatment of OMW give rise to new possibilities for treating these waste waters.    

    

** Solid-state <sup>13</sup>C-NMR spectroscopic determination of side-chain mobilities in zirconium-based metal–organic frameworks   
:PROPERTIES:
:ID: https://openalex.org/W4390612169
:DOI: https://doi.org/10.5194/mr-5-1-2024
:AUTHORS: Günter Hempel, Ricardo Kurz, Silvia Paasch, Kay Saalwächter, Eike Brunner
:HOST: Magnetic resonance
:END:

Günter Hempel, Ricardo Kurz, Silvia Paasch, Kay Saalwächter, Eike Brunner, Magnetic resonance. 5(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/mr-5-1-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390612169"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390612169"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390612169"))][Get cited by]]

OpenAlex: https://openalex.org/W4390612169
    
Günter Hempel, Ricardo Kurz, Silvia Paasch, Kay Saalwächter, Eike Brunner, Magnetic resonance. https://doi.org/10.5194/mr-5-1-2024
    
Abstract. Porous interpenetrated zirconium–organic frameworks (PIZOFs) are a class of Zr-based metal–organic frameworks (MOFs) which are composed of long, rod-like dicarboxylate linkers and Zr6O4(OH)4(O2C)12 nodes. Long oligoethylene glycol or aliphatic side chains are covalently attached to the linker molecules in the cases of PIZOF-10 and PIZOF-11, respectively. These side chains are supposedly highly mobile, thus mimicking a solvent environment. It is anticipated that such MOFs could be used as a solid catalyst – the MOF – with pore systems showing properties similar to a liquid reaction medium. To quantify the side-chain mobility, here we have applied different 1D and 2D NMR solid-state spectroscopic techniques like cross-polarization (CP) and dipolar-coupling chemical-shift correlation (DIPSHIFT) studies. The rather high 1H-13C CP efficiency observed for the CH2 groups of the side chains indicates that the long side chains are unexpectedly immobile or at least that their motions are strongly anisotropic. More detailed information about the mobility of the side chains was then obtained from DIPSHIFT experiments. Analytical expressions for elaborate data analysis are derived. These expressions are used to correlate order parameters and to slow motional rates with signals in indirect spectral dimensions, thus enabling the quantification of order parameters for the CH2 groups. The ends of the chains are rather mobile, whereas the carbon atoms close to the linker are more spatially restricted in mobility.    

    
