#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Sat Jul 27 01:10:05 2024

Found 2 results from 2024-07-20 to 2024-07-27
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Low-temperature dechlorination of polyvinyl chloride (PVC) for production of H 2 and carbon materials using liquid metal catalysts  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4400945077
:TOPICS: Nanoscale Zero-Valent Iron Applications and Remediation, Poly(vinyl chloride) Plasticizers and Stabilizers, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1126/sciadv.adm9963")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400945077"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400945077"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400945077"))][Get cited by]]

OpenAlex: https://openalex.org/W4400945077 (Open access: False)
    
[[https://openalex.org/A5013148515][Felipe Polo‐Garzon]], [[https://openalex.org/A5063354017][Zili Wu]], [[https://openalex.org/A5100384454][Yuanyuan Li]], [[https://openalex.org/A5100405991][Jin Zhang]], [[https://openalex.org/A5006886094][Xinbin Yu]], [[https://openalex.org/A5094167537][Elena Toups]], [[https://openalex.org/A5013740599][Eddie López‐Honorato]], [[https://openalex.org/A5071143092][Joshua T. Damron]], [[https://openalex.org/A5054366623][Jeffrey C. Foster]], [[https://openalex.org/A5033156106][Yongqiang Cheng]], [[https://openalex.org/A5049941485][Luke L. Daemen]], [[https://openalex.org/A5012178439][Anibal J. Ramirez‐Cuesta]], [[https://openalex.org/A5061707133][Harry M. Meyer]], Science Advances. 10(30)] 2024. https://doi.org/10.1126/sciadv.adm9963 
     
Polyvinyl chloride (PVC) is ubiquitous in everyday life; however, it is not recycled because it degrades uncontrollably into toxic products above 250°C. Therefore, it is of interest to controllably dechlorinate PVC at mild temperatures to generate narrowly distributed carbon materials. We present a catalytic route to dechlorinate PVC (~90% reduction of Cl content) at mild temperature (200°C) to produce gas H 2 (with negligible coproduction of corrosive gas HCl) and carbon materials using Ga as a liquid metal (LM) catalyst. A LM was used to promote intimate contact between PVC and the catalytic sites. During dechlorination of PVC, Cl is sequestrated in the carbonaceous solid product. Later, chlorine is easily removed with an acetone wash at room temperature. The Ga LM catalyst is reusable, outperforms a traditional supported metal catalyst, and successfully converts (untreated) discarded PVC pipe.    

    

* Liquid Metal Alloys Enable Efficient Formate Electrosynthesis  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4400887504
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202408966")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400887504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400887504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400887504"))][Get cited by]]

OpenAlex: https://openalex.org/W4400887504 (Open access: False)
    
[[https://openalex.org/A5100684579][Hui Huang]], [[https://openalex.org/A5102010939][Xue Ding]], [[https://openalex.org/A5003725369][Xinnan Mao]], [[https://openalex.org/A5100634108][Yuchen Yan]], [[https://openalex.org/A5013447364][Fang Lv]], [[https://openalex.org/A5030312735][Binbin Pan]], [[https://openalex.org/A5048171248][Wei Huang]], [[https://openalex.org/A5100364512][Lu Wang]], [[https://openalex.org/A5100819249][Na Han]], [[https://openalex.org/A5070610406][Yanguang Li]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202408966 
     
Abstract Liquid metals are an interesting class of materials with the unique combination of metallic nature and liquid fluidity, and have recently been explored in many emerging fields. Their potential applications in catalysis, unfortunately, remain largely untapped. Herein, Ga‐mediated liquid metal alloying as an effective strategy is demonstrated to prepare functional alloys for catalysis. The alloying is carried out by dissolving indium or tin pellets in liquid gallium at room temperature or assisted by gentle heating, giving rise to binary Ga 1− x In x and Ga 1− x Sn x liquid metal alloys with tunable chemical compositions. When further subjected to ultrasonication in water, they are ruptured into nanosized particles with liquid metal cores and thin surface oxide shells. Electrochemical measurements reveal that the liquid metal alloying significantly promotes electrocatalytic CO 2 reduction to formate. Taking Ga 0.75 In 0.25 as an example, its formate Faradaic efficiency is enhanced by 10%–20% compared to those of Ga and In, and its formate partial current density is 4–6 times larger than those of Ga and In. This enhancement is rationalized via computational simulations showing that the surrounding of In active sites with Ga atoms deactivates the undesirable reaction pathways to CO or H 2 , and facilitates selective formate electrosynthesis.    

    
