#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Wed Aug 28 01:14:45 2024

Found 1 results from 2024-08-21 to 2024-08-28
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* From CO2 to solid carbon: reaction mechanism, active species, and conditioning the Ce-alloyed GaInSn catalyst  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4401814905
:TOPICS: Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-1t2ss")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401814905"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401814905"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401814905"))][Get cited by]]

OpenAlex: https://openalex.org/W4401814905 (Open access: True)
    
[[https://openalex.org/A5064317736][Daniel Lörch]], [[https://openalex.org/A5059375955][Aya Gomaa Abdelkader Mohamed]], [[https://openalex.org/A5067661545][Holger Euchner]], [[https://openalex.org/A5045549969][J. David Timm]], [[https://openalex.org/A5083563585][Jonas Hiller]], [[https://openalex.org/A5017548688][Peter Bogdanoff]], [[https://openalex.org/A5010478591][Matthias M. May]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-1t2ss  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/66c7743120ac769e5f79ebb7/original/from-co2-to-solid-carbon-reaction-mechanism-active-species-and-conditioning-the-ce-alloyed-ga-in-sn-catalyst.pdf][pdf]])
     
The electrochemical reduction of CO2 is a promising realisation of negative emissions to mitigate climate change, aiming at the efficient production and safe longterm storage of carbon-rich sink products. This approach, however, necessitates novel catalyst materials specifically targeting electrochemical carbon dioxide removal. In this work, we investigate synthesis routes for a cerium-incorporated GaInSn-based liquid metal catalyst, focusing on the electrochemical production of graphitic carbon. Preparation and preconditioning of the catalyst are found to be crucial for carbon production, while trace amounts of H2O and OH in the organic electrolyte play a decisive role for the efficiency of the electrocatalytic process. Finally, for a better understanding of the reaction mechanism and the involved active species, experimental findings and density functional theory-based calculations are combined, suggesting a two-step reduction pathway with Ce(OH)x as the catalytically active surface species.    

    
