#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Thu Mar  7 19:55:04 2024

Found 2 results from 2024-02-29 to 2024-03-07
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Electrochemical Nitrate‐to‐Ammonia Conversion Enabled by Carbon‐Decoration of Ni─GaOOH Synthesized via Plasma‐Assisted CO2 Reduction  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4392344784
:TOPICS: Ammonia Synthesis and Electrocatalysis, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202311302")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392344784"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392344784"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392344784"))][Get cited by]]

OpenAlex: https://openalex.org/W4392344784 (Open access: True)
    
[[https://openalex.org/A5093015657][Abd H. Babikir]], [[https://openalex.org/A5047854433][Xin Mao]], [[https://openalex.org/A5082839443][Aijun Du]], [[https://openalex.org/A5017219917][J.D. Riches]], [[https://openalex.org/A5013359536][Kostya Ken Ostrikov]], [[https://openalex.org/A5050672687][Anthony P. O’Mullane]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202311302 
     
Abstract The release of nitrates into the environment leads to contaminated soil and water that poses a health risk to humans and animals. Due to the transition to renewable energy‐based technologies, an electrochemical approach is an emerging option that can selectively produce valuable ammonia from nitrate sources. However, traditional metal‐based electrocatalysts often suffer from low nitrate adsorption that reduces NH 3 production rates. Here, a Ni‐GaOOH‐C/Ga electrocatalyst for electrochemical nitrate conversion into NH 3 is synthesized via a low energy atmospheric‐pressure plasma process that reduces CO 2 into highly dispersed activated carbon on dispersed Ni─GaOOH particles produced from a liquid metal Ga─Ni alloy precursor. Nitrate conversion rates of up to 26.3 µg h −1 mg −1 cat are achieved with good stability of up to 20 h. Critically, the presence of carbon centers is central to improved performance where both Ni─C and NiO─C interfaces act as NO 3− adsorption and reduction centers during the reaction. Density functional theory (DFT) calculations indicate that the NiO─C and Ni─C reaction sites reduce the Gibbs free energy required for NO 3− reduction to NH 3 compared to NiO and Ni. Importantly, catalysts without carbon centers do not produce NH 3 , emphasizing the unique effects of incorporating carbon nanoparticles into the electrocatalyst.    

    

* In situ characterisation of graphene growth on liquid copper-gallium alloys: Paving the path for cost-effective synthesis  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4392269378
:TOPICS: Graphene: Properties, Synthesis, and Applications, Lithium-ion Battery Technology, Plasma Physics and Technology in Semiconductor Industry
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159723")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392269378"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392269378"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392269378"))][Get cited by]]

OpenAlex: https://openalex.org/W4392269378 (Open access: False)
    
[[https://openalex.org/A5006929737][Valentina Belova]], [[https://openalex.org/A5093615349][Florian Letellier]], [[https://openalex.org/A5049417640][Maciej Jankowski]], [[https://openalex.org/A5039878670][Marc de Voogd]], [[https://openalex.org/A5010507159][Mahesh K. Prabhu]], [[https://openalex.org/A5001095010][Lei Yao]], [[https://openalex.org/A5010544351][G. J. C. van Baarle]], [[https://openalex.org/A5077055219][Gilles Renaud]], [[https://openalex.org/A5069837152][Mehdi Saedi]], [[https://openalex.org/A5021296109][Irene M. N. Groot]], [[https://openalex.org/A5079450836][Oleg Konovalov]], Applied Surface Science. 657(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159723 
     
Liquid metal catalysts (LMCats), primarily molten copper, have demonstrated their efficiency in the chemical vapour deposition (CVD) approach for synthesising highquality, large-area graphene. However, their high melting temperatures limit broader applications. Reducing the temperature of graphene production on LMCats would lead to a more efficient and cost-effective process. Here, we investigated the effects of alloying copper with a low-melting temperature metal on graphene growth in real-time. We examined a set of liquid copper-gallium alloy systems using two complementary in situ techniques: radiation-mode optical microscopy and synchrotron X-ray reflectivity (XRR). The microscopy observations revealed reduced catalytic activity and graphene quality degradation in compositions with gallium domination. The XRR confirmed the formation of single-layer graphene on alloys with up to 60 wt% of gallium. Furthermore, we detected a systematic increase in adsorption height on the alloys' surface, indicating weaker adhesion of graphene on gallium. These findings suggest that a trade-off between layer quality and cost reduction in production is feasible. Our results provide insights into the CVD synthesis of graphene on bimetallic liquid surfaces and underscore the potential of gallium-copper alloys for enabling the direct transfer of graphene from a liquid substrate, thereby addressing the limitations imposed by the high melting temperatures of conventional LMCats.    

    
