#+filetags: liquid-metal
#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Wed Feb  7 00:42:05 2024

Found 1 results from 2024-01-31 to 2024-02-07
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Deformation Behavior of Eutectic Gallium–Indium under Electric Fields  :liquid_metal:
:PROPERTIES:
:ID: https://openalex.org/W4391388405
:TOPICS: Atomic Force Microscopy Techniques, Plasmonics for Photovoltaic Devices, Nanowire Nanosensors for Biomedical and Energy Applications
:PUBLICATION_DATE: 2024-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jchemed.3c00687")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391388405"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391388405"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391388405"))][Get cited by]]

OpenAlex: https://openalex.org/W4391388405 (Open access: False)
    
[[https://openalex.org/A5039480955][Hai Bo Zhang]], [[https://openalex.org/A5037897379][Qiong Ding]], [[https://openalex.org/A5066726224][Ruohan Li]], [[https://openalex.org/A5039144070][Weihong Chen]], [[https://openalex.org/A5062755510][Qianqian Wang]], Journal of Chemical Education. None(None)] 2024. https://doi.org/10.1021/acs.jchemed.3c00687 
     
Liquid metals are widely applied in various fields, including chemistry, catalysis, energy storage, chemical sensing, and stretchable electronics, due to their unique deformabilities. However, their behavior under a rod or ring electrode has never been analyzed. Furthermore, research on the deformation behavior of eutectic Ga–In (EGaIn), the most commonly used Ga-based liquid metal, under electric fields of varying intensities and shapes is lacking. Therefore, investigating the deformation behavior of liquid metals under electric fields is expected to contribute to the accurate regulation of their morphologies. To this end, herein, an electrochemical device was fabricated using EGaIn, and experiments were conducted by adjusting the potential and the cathode shape. Further, the mechanism of the deformation was analyzed in detail. When a potential was applied, EGaIn droplets deformed into fractal dendrites under circular, polygonal, and nonpolygonal electric fields. Dendrite symmetry was influenced by the cathode shape, as the resulting electric fields varied in shape. The results of this study will aid in precisely controlling the behaviors of LMs and their alloys using electric fields. This topic is suitable for upper-division undergraduates who possess a basic understanding of electrochemistry. Through these experiments, students may explore the effects of potential on the morphology of EGaIn and analyze experimental phenomena such as electrowetting, dendrite formation, and surface oxidation, thereby developing a preliminary understanding of interfacial tension and electrocapillarity. Additionally, these experiments encourage undergraduates to actively participate in laboratory work, which helps foster their enthusiasm for chemistry.    

    
