#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Thu Oct 17 01:20:29 2024

Found 1 results from 2024-10-10 to 2024-10-17
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Methane Pyrolysis to Produce Hydrogen and Carbon Solids Using Thermocatalytic Pathway  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4403287485
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Heat Transfer to Supercritical Fluids in Channels, Chemical-Looping Technologies
:PUBLICATION_DATE: 2024-10-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2118/221204-ms")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403287485"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403287485"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403287485"))][Get cited by]]

OpenAlex: https://openalex.org/W4403287485 (Open access: False)
    
[[https://openalex.org/A5078559865][Ivy Ching Hsia Chai]], [[https://openalex.org/A5005761415][Yang‐Hao Chan]], [[https://openalex.org/A5107489191][K. E. Nikulainen]], [[https://openalex.org/A5107607101][J. Laukka]], [[https://openalex.org/A5030760623][Mohd Azlan Bin Mohd Ishak]], No host. 4(None)] 2024. https://doi.org/10.2118/221204-ms 
     
Thermo-catalytic decomposition (TCD) of natural gas is a suitable technology to provide clean hydrogen (H2). This TCD process directly splits hydrocarbons, mainly methane (CH4), into H2 and carbon as illustrated in Equation 1. [Equation 1]CH4(g)→C(s)+2H2(g)ΔH∘=74 kJ/mol In TCD process, H2 is produced as a gas while carbon is generated in solid form. Though the reaction can occur with heat energy alone, the use of a catalyst significantly reduces the required reaction temperature, making the process less energy-intensive. Various reactor designs are used for TCD to pyrolyze CH4, including fluidized/packed bed reactor, moving bed reactor, bubble column reactor (using molten metal or salt), and plug flow reactor. This paper elucidates ROTOBOOST's bubble column reactor, which utilizes a specific molten metal alloy as TCD catalyst. Although methane pyrolysis demonstration has started since the 1950s, the development and understanding of liquid catalyst in bubble column has gained more momentum since the 2000s. This stems from the benefit of lowering the reaction temperature to below 1000°C, making the process less energy-intensive, mitigating coking issues and subsequent deactivation of solid catalysts, and allowing better control and tuning of solid carbon quality Von Wald et al. (2020) reported that methane pyrolysis using the bubble column technology with liquid metal catalyst is a suitable process for reducing CO2 emissions in the short term. In TCD process with bubble column reactor, pre-treated natural gas or methane is continuously fed to the bottom of the reactor, allowing it to travel upward through the molten catalytic alloy, which is heated to the reaction temperature. The catalytic alloy, with high heat capacity, provides a homogenous heat supply directly to each hydrocarbon gas molecule. As the bubbles burst at the upper interface of the liquid media, H2 and carbon are released. Since the density of carbon is much lower than that of the molten media, the produced carbon rises with the bubbles, floating at top of the liquid surface, and finally deposits at the surface of the liquid column. Therefore, the produced carbon does not affect the reaction zone on the inside/surface of the bubbles as they rise through the molten media, ensuring the bubble surface is a continuously renewed catalyst. The main advantage of liquid bubble column reactors is the continuous carbon removal from the liquid media due to density differences, preventing reactor blockage or contamination from carbon accumulation.    

    
