#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Mon May 20 01:06:13 2024

Found 4 results from 2024-05-13 to 2024-05-20
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Structural Evolution of Liquid Metals and Alloys  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4396856025
:TOPICS: Ice Nucleation and Melting Phenomena
:PUBLICATION_DATE: 2024-05-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202403885")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396856025"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396856025"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396856025"))][Get cited by]]

OpenAlex: https://openalex.org/W4396856025 (Open access: False)
    
[[https://openalex.org/A5046145312][Vaishnavi Krishnamurthi]], [[https://openalex.org/A5019680286][Ph. Vaillant]], [[https://openalex.org/A5080396231][Jitendra Mata]], [[https://openalex.org/A5045506863][Chung Kim Nguyen]], [[https://openalex.org/A5074271382][Caiden J. Parker]], [[https://openalex.org/A5049005415][Karma Zuraiqi]], [[https://openalex.org/A5038505644][Gary Bryant]], [[https://openalex.org/A5062642046][Kin Seng Chiang]], [[https://openalex.org/A5005167263][Salvy P. Russo]], [[https://openalex.org/A5073206123][Andrew J. Christofferson]], [[https://openalex.org/A5031027699][Aaron Elbourne]], [[https://openalex.org/A5091422934][Torben Daeneke]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202403885 
     
Abstract Low‐melting liquid metals are emerging as a new group of highly functional solvents due to their capability to dissolve and alloy various metals in their elemental state to form solutions as well as colloidal systems. Furthermore, these liquid metals can facilitate and catalyze multiple unique chemical reactions. Despite the intriguing science behind liquid metals and alloys, very little is known about their fundamental structures in the nanometric regime. To bridge this gap, this work employs small angle neutron scattering and molecular dynamics simulations, revealing that the most commonly used liquid metal solvents, EGaIn and Galinstan, are surprisingly structured with the formation of clusters ranging from 157 Å to 15.7 Å. Conversely, non‐eutectic liquid metal alloys of GaSn or GaIn at low solute concentrations of 1, 2, and 5wt%, as well as pure Ga, do not exhibit these structures. Importantly, the eutectic alloys retain their structure even at elevated temperatures of 60 and 90 °C, highlighting that they are not just simple homogeneous fluids consisting of individual atoms. Understanding the complex soft structure of liquid alloys will assist in comprehending complex phenomena occurring within these fluids and contribute to deriving reaction mechanisms in the realm of synthesis and liquid metal‐based catalysis. This article is protected by copyright. All rights reserved    

    

* Applications of Liquid Metals  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4396976514
:TOPICS: Advanced Lightweight Materials and Engineering Applications
:PUBLICATION_DATE: 2024-05-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/admt.202400500")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396976514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396976514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396976514"))][Get cited by]]

OpenAlex: https://openalex.org/W4396976514 (Open access: True)
    
[[https://openalex.org/A5068511935][Aaron T. Ohta]], [[https://openalex.org/A5088452440][Michael D. Bartlett]], [[https://openalex.org/A5083975325][Michael D. Dickey]], [[https://openalex.org/A5067220816][Kourosh Kalantar‐Zadeh]], Advanced materials technologies. None(None)] 2024. https://doi.org/10.1002/admt.202400500  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/admt.202400500][pdf]])
     
Low-melting-point metals, especially those that are liquid at room temperature, are being explored for an increasing number of applications. Like solid-phase metals, liquid metals have high electrical and thermal conductivity. However, liquid metals are also conformal, flexible, and stretchable, even when using thick films and large volumes. The shapes and structures that can be achieved with liquid metals span a variety of geometries and scales, ranging from thin films to 3D structures, and from nanoscale to macroscale feature sizes. Furthermore, liquid metals based on alloys of gallium have been shown to have low toxicity, making them suitable for biomedical devices and wearable electronics. These unique properties of low-melting-point metals make them useful materials in a variety of applications such as soft electronics, catalysis, and microfluidics. This Special Section is a collection of ten research articles and one review article, contributed by experts in applications that utilize low-melting-point metals. The articles can be broadly sorted into three themes: 1) liquid metals for stretchable electronics, 2) liquid metals for energy storage devices and recyclable devices, and 3) fabrication processes enabled by or tailored to the use of low-melting-point metals. The topics covered by this special section illustrate the wide applicability of low-melting-point metals, and the utility of this class of materials in important and trending research areas. Liquid metals are inherently suitable for stretchable electronics, as they can be used to realize deformable electrically conductive materials. In addition, repeated cycles of stretching and bending can result in fatigue of solid materials, but liquid–metal components are unaffected. Furthermore, the low toxicity of gallium-based liquid metals makes them suitable for wearable electronics. In this special section, Liu and co-workers demonstrate a wearable sensor that uses a spiral structure of liquid metal to measure a variety of human motion (article number 2300896). Du and co-workers have reviewed the broader field of stretchable and flexible sensors that employ liquid metals (article number 2300431). Lim and co-workers describe a method of fabricating electrodes that use liquid metal in a sponge-like structure, and demonstrate stretchable sensors and flexible electronic breadboards using these "sponge electrodes" (article number 2301589). Malakooti and co-workers have also created stretchable conductors but with a different approach: printing elastomers impregnated with liquid–metal microdroplets (article number 2301324). Under strain, the microdroplets become electrically connected, and remain conductive after the strain is released. Bae and co-workers also used the direct printing of conductive material, but in their work liquid metal was used as an ink to create a stretchable thermoelectric device (article number 2301171). As seen in these papers, not all of the components of stretchable electronics need to be deformable. Jang and co-workers created a stretchable display that consists of an array of light-emitting-diode pixels with liquid–metal interconnects (article number 2301413). It is beneficial to have flexible and stretchable energy sources for stretchable electronics. Low-melting-point metals are also useful in this area of research. As in other stretchable devices, liquid metals can be used for electrodes in energy storage devices. Toward this end, Tavakoli and co-workers show that graphene oxide coatings on eutectic gallium–indium liquid metal films make them more stable in acidic or alkaline solutions (article number 2301428). The coating thus makes electrodes made from these liquid metals more robust, with a higher capacitance per unit area. This is useful for energy storage in devices such as supercapacitors. In a separate article, Tavakoli and co-workers demonstrate a different type of energy storage for stretchable electronics: a strain-tolerant rechargeable battery (article number 2301189). This battery uses a liquid–metal current collector and a gallium-carbon anode, and is capable of self-healing damage to the gallium-carbon electrode. The battery can still be repaired after more extensive damage, and the metals can be recovered and recycled at the end of the battery's lifetime. Handschuh–Wang and co-workers have also developed devices that can be recycled (article number 2301483). In this case, these are transient stretchable circuits made from gelatin biogel substrates with liquid metal conductive elements. The circuits can be quickly and easily degraded, as the biogel substrate dissolves in hot water in less than a minute. The liquid metal and biogel materials can then be recovered and recycled. The articles mentioned above employ a variety of methods to fabricate the devices and circuits that use low-melting-point metals. These fabrication processes have resulted in many types of novel devices and circuits. However, this special section contains two articles that focus on fabrication methods with broader applicability. Gui and co-workers show that molds made of elastomer and polycarbonate membranes can be used to create 3D metal structures with a minimum size of 10 µm (article number 2301625). In this work, a bismuth-indium alloy with a melting point of 72 °C fills the mold in its liquid state, then is cooled to create the final metal structure, forming a variety of 2D or 3D shapes. Lazarus and co-workers describe a fabrication method that integrates the direct laser writing of microfluidic channels with larger features and substrates made by stereolithography (article number 2301980). These multi-scale structures help with the introduction of liquid metal into microchannels, and enable the fabrication of nH-range coil-type inductors. We thank all the authors in this special section for their valuable contributions to this area of applied research. We also appreciate the other experts who have volunteered their expertise and time during the peer review process. We are especially grateful to Dr. Joseph Krumpfer and Dr. Esther Levy for their efforts in making this special section possible. The papers in this special section span a variety of important and interesting topics, all made possible by the use of low-melting-point metals. We hope that this collection of articles informs and stimulates further research using this unique class of liquid–metal materials. Furthermore, because of the variety of applications, and the increasing popularity of liquid metals, this Special Section has been organized jointly with another Special Issue on liquid metals in Advanced Functional Materials. Interested readers are encouraged to also explore this accompanying special issue (see Guest Editorial for details). The authors declare no conflict of interest. Aaron Ohta is a professor in the Department of Electrical and Computer Engineering at the University of Hawaii at Manoa. He received his B.S. degree from the University of Hawaii at Manoa, his M.S. degree from the University of California, Los Angeles, and his Ph.D. degree from the University of California, Berkeley, all in electrical engineering. Aaron's research interests include reconfigurable circuits and systems using liquid metals and other materials, microfluidics, and microelectromechanical systems (MEMS). Michael D. Bartlett is an associate professor and John R. Jones III Faculty Fellow of Mechanical Engineering at Virginia Tech. He received his B.S.E. from the University of Michigan, his Ph.D. from the University of Massachusetts Amherst, and was a postdoctoral fellow at Carnegie Mellon University. Michael leads the Soft Materials and Structures Lab, which investigates multifunctional soft materials and composites with highly controllable mechanical and functional properties for the creation of soft electronics and robotics based on liquid metal, switchable and intelligent adhesives, and adaptive materials. Michael Dickey is the Camille and Henry Dreyfus professor in the Department of Chemical & Biomolecular Engineering at NC State University. He received a BS in Chemical Engineering from Georgia Institute of Technology (1999) and a PhD from the University of Texas (2006) under the guidance of Professor Grant Willson. From 2006–2008 he was a post-doctoral fellow in the lab of Professor George Whitesides at Harvard University. He completed a sabbatical at Microsoft in 2016 and EPFL in 2023. Michael's research interests include soft matter (liquid metals, gels, polymers) for soft and stretchable devices (electronics, energy harvesters, and soft robotics). Kourosh Kalantar-Zadeh is a professor and head of the School of Chemical and Biomolecular Engineering at the University of Sydney. He is involved in research in the fields of analytical chemistry, materials sciences, gastroenterology, electronics, and sensors. Professor Kalantar–Zadeh is best known for his works on ingestible sensors, liquid metals, and 2D semiconductors. He led his group to the invention of an ingestible chemical sensor: a human gas sensing capsule, one of the breakthroughs in the field of medical devices. He has received several international awards for his scientific contributions including the 2017 IEEE Sensor Council Achievement, and 2020 Robert Boyle Prize of RSC.    

    

* Surface‐Enriched Room‐Temperature Liquid Bismuth for Catalytic CO2 Reduction  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4396932166
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202401777")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396932166"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396932166"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396932166"))][Get cited by]]

OpenAlex: https://openalex.org/W4396932166 (Open access: True)
    
[[https://openalex.org/A5034491292][Jing‐Dong Guo]], [[https://openalex.org/A5090095249][Zhi Xing]], [[https://openalex.org/A5069697642][Dingqi Wang]], [[https://openalex.org/A5034125202][Longbing Qu]], [[https://openalex.org/A5048975250][Ali Zavabeti]], [[https://openalex.org/A5016509595][Qining Fan]], [[https://openalex.org/A5004500886][Yuecheng Zhang]], [[https://openalex.org/A5047793151][Joshua D. Butson]], [[https://openalex.org/A5000705290][Jianing Yang]], [[https://openalex.org/A5025243010][Chao Wu]], [[https://openalex.org/A5023896908][Jefferson Zhe Liu]], [[https://openalex.org/A5010731144][Masood S. Alivand]], [[https://openalex.org/A5063556653][Xiaolei Fan]], [[https://openalex.org/A5055340435][Gang Kevin Li]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202401777  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/smll.202401777][pdf]])
     
Abstract Bismuth‐based electrocatalysts are effective for carbon dioxide (CO 2 ) reduction to formate. However, at room temperature, these materials are only available in solid state, which inevitably suffers from surface deactivation, declining current densities, and Faradaic efficiencies. Here, the formation of a liquid bismuth catalyst on the liquid gallium surface at ambient conditions is shown as its exceptional performance in the electrochemical reduction of CO 2 (i.e., CO 2 RR). By doping a trace amount of bismuth (740 ppm atomic) in gallium liquid metal, a surface enrichment of bismuth by over 400 times (30 at%) in liquid state is obtained without atomic aggregation, achieving 98% Faradic efficiency for CO 2 conversion to formate over 80 h. Ab initio molecular simulations and density functional theory calculations reveal that bismuth atoms in the liquid state are the most energetically favorable sites for the CO 2 RR intermediates, superior to solid Bi‐sites, as well as joint GaBi‐sites. This study opens an avenue for fabricating high‐performing liquid‐state metallic catalysts that cannot be reached by elementary metals under electrocatalytic conditions.    

    

* Mechanical Integrity and Reinforcement Efficiency of Graphene Grown on Liquid Copper by Chemical Vapor Deposition  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4396971105
:TOPICS: Graphene: Properties, Synthesis, and Applications, Diamond Nanotechnology and Applications, Metal Matrix Composites: Science and Applications
:PUBLICATION_DATE: 2024-05-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/admi.202400193")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396971105"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396971105"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396971105"))][Get cited by]]

OpenAlex: https://openalex.org/W4396971105 (Open access: True)
    
[[https://openalex.org/A5098666161][Ilias Sfougkaris]], [[https://openalex.org/A5033794109][Christos Tsakonas]], [[https://openalex.org/A5088137297][Anastasios C. Manikas]], [[https://openalex.org/A5003726953][Maria Giovanna Pastore Carbone]], [[https://openalex.org/A5017765214][Christos Pavlou]], [[https://openalex.org/A5021296109][Irene M. N. Groot]], [[https://openalex.org/A5069837152][Mehdi Saedi]], [[https://openalex.org/A5010544351][G. J. C. van Baarle]], [[https://openalex.org/A5039878670][Marc de Voogd]], [[https://openalex.org/A5006929737][Valentina Belova]], [[https://openalex.org/A5049417640][Maciej Jankowski]], [[https://openalex.org/A5079450836][Oleg Konovalov]], [[https://openalex.org/A5077055219][Gilles Renaud]], [[https://openalex.org/A5071814045][Costas Galiotis]], Advanced materials interfaces. None(None)] 2024. https://doi.org/10.1002/admi.202400193  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/admi.202400193][pdf]])
     
Abstract Graphene is a perfect 2D crystal of covalently bonded carbon atoms and constitutes the building block for all graphitic structures. Its superior properties make it an attractive material for a variety of technological applications. However, mass production does not meet the initial expectations. Chemical Vapor Deposition (CVD) is currently the only available method for large‐scale automated production, but the produced graphene sheets suffer from structural and morphological defects that degrade considerably the mechanical and other physical properties of synthesized graphene. Recently, the use of liquid metal catalysts (LMCat) has been proposed as an alternative platform for facile and high‐quality synthesis of single‐crystal graphene. Herein, simultaneous Raman spectroscopy combined with mechanical testing is adopted confirming that the reinforcing efficiency of the LMCat graphene is greatly improved. In fact, the effective Young's modulus of LMCat graphene has been found ≈630 GPa, which is significantly higher than the graphene grown on solid Cu substrate due to differences in the morphology of Cu substrate. Overall, this work paves the way for the development of defect‐free graphene of quality comparable to exfoliated flakes, and this will have a major technological impact for many applications.    

    
