#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Fri May 17 01:06:04 2024

Found 2 results from 2024-05-10 to 2024-05-17
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Liquid Gallium–Zeolite Nanocomposite Catalysts for Propane Dehydrogenation  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4396779052
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-05-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.iecr.4c00411")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396779052"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396779052"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396779052"))][Get cited by]]

OpenAlex: https://openalex.org/W4396779052 (Open access: False)
    
[[https://openalex.org/A5038191313][Shuo Zhang]], [[https://openalex.org/A5006352222][Bofeng Zhang]], [[https://openalex.org/A5028780287][Mingxia Song]], [[https://openalex.org/A5028116005][Liming Xia]], [[https://openalex.org/A5018069202][Guozhu Liu]], Industrial & engineering chemistry research. None(None)] 2024. https://doi.org/10.1021/acs.iecr.4c00411 
     
Liquid metal (LM) with outstanding fluidity, excellent electrical and thermal conductivity is emerging in heterogeneous catalysis, such as Ga-based supported catalytically active liquid-metal solutions. However, liquid gallium droplets are prone to migration and aggregation, especially under high-temperature reaction conditions. Herein, we designed a liquid gallium-zeolite nanocomposite catalyst (L-Ga/S-1) by a simple and low-cost physical mixing method. In propane dehydrogenation, the optimized L-1.5-Ga/S-1 exhibited a high formation rate of 1.17 mol C3H6gGa–1 h–1, 13 times higher than that of 1.5-Ga-MFI, with a propylene selectivity of up to 95% at 550 °C. It could be ascribed to abundant interface GaOx structure between Ga droplet and nanosized Silicalite-1 zeolite, which provided strong Lewis acidic sites to promote the selective scission of C–H bonds. Liquid metal–metal oxide nanocomposites offer an important way for controlling interface precisely in the sphere of heterogeneous catalysis.    

    

* Structural Evolution of Liquid Metals and Alloys  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4396856025
:TOPICS: Ice Nucleation and Melting Phenomena
:PUBLICATION_DATE: 2024-05-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202403885")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396856025"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396856025"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396856025"))][Get cited by]]

OpenAlex: https://openalex.org/W4396856025 (Open access: False)
    
[[https://openalex.org/A5046145312][Vaishnavi Krishnamurthi]], [[https://openalex.org/A5019680286][Ph. Vaillant]], [[https://openalex.org/A5080396231][Jitendra Mata]], [[https://openalex.org/A5045506863][Chung Kim Nguyen]], [[https://openalex.org/A5074271382][Caiden J. Parker]], [[https://openalex.org/A5049005415][Karma Zuraiqi]], [[https://openalex.org/A5038505644][Gary Bryant]], [[https://openalex.org/A5062642046][Kin Seng Chiang]], [[https://openalex.org/A5005167263][Salvy P. Russo]], [[https://openalex.org/A5073206123][Andrew J. Christofferson]], [[https://openalex.org/A5031027699][Aaron Elbourne]], [[https://openalex.org/A5091422934][Torben Daeneke]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202403885 
     
Abstract Low‐melting liquid metals are emerging as a new group of highly functional solvents due to their capability to dissolve and alloy various metals in their elemental state to form solutions as well as colloidal systems. Furthermore, these liquid metals can facilitate and catalyze multiple unique chemical reactions. Despite the intriguing science behind liquid metals and alloys, very little is known about their fundamental structures in the nanometric regime. To bridge this gap, this work employs small angle neutron scattering and molecular dynamics simulations, revealing that the most commonly used liquid metal solvents, EGaIn and Galinstan, are surprisingly structured with the formation of clusters ranging from 157 Å to 15.7 Å. Conversely, non‐eutectic liquid metal alloys of GaSn or GaIn at low solute concentrations of 1, 2, and 5wt%, as well as pure Ga, do not exhibit these structures. Importantly, the eutectic alloys retain their structure even at elevated temperatures of 60 and 90 °C, highlighting that they are not just simple homogeneous fluids consisting of individual atoms. Understanding the complex soft structure of liquid alloys will assist in comprehending complex phenomena occurring within these fluids and contribute to deriving reaction mechanisms in the realm of synthesis and liquid metal‐based catalysis. This article is protected by copyright. All rights reserved    

    
