#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Thu Apr 18 01:02:11 2024

Found 1 results from 2024-04-11 to 2024-04-18
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Supported Catalytically Active Liquid Metal Solutions: Liquid Metal Catalysis with Ternary Alloys, Enhancing Activity in Propane Dehydrogenation  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4394728272
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c01282")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4394728272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4394728272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4394728272"))][Get cited by]]

OpenAlex: https://openalex.org/W4394728272 (Open access: False)
    
[[https://openalex.org/A5071253993][Michael J. Moritz]], [[https://openalex.org/A5005267120][Sven Maisel]], [[https://openalex.org/A5019224120][Narayanan Raman]], [[https://openalex.org/A5020096826][Haiko Wittkämper]], [[https://openalex.org/A5055039669][Christoph Wichmann]], [[https://openalex.org/A5069993975][Mathias Grabau]], [[https://openalex.org/A5016293166][Deniz Kahraman]], [[https://openalex.org/A5054255871][Julien Steffen]], [[https://openalex.org/A5001718718][Nicola Taccardi]], [[https://openalex.org/A5067224843][Andreas Görling]], [[https://openalex.org/A5040845269][Marco Haumann]], [[https://openalex.org/A5039726667][Peter Wasserscheid]], [[https://openalex.org/A5035111702][Hans‐Peter Steinrück]], [[https://openalex.org/A5071842639][Christian Papp]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c01282 
     
The research and optimization of catalysts are instrumental in revolutionizing chemical processes and making them viable in terms of energy and resources. Supported catalytically active liquid metal solutions (SCALMS) are highly active and stable in the harsh environment of the dehydrogenation reaction of alkanes. This is attributed to their liquid and dynamic nature and their isolated catalytically active single-atom sites. SCALMS consists of a liquid metal matrix (gallium) in which a catalytically active transition metal (platinum, rhodium, palladium, or nickel) is dissolved. Binary SCALMS systems are the subject of extensive research, aiming at a better understanding for achieving optimal performance. This work uses a combined multidisciplinary approach to examine ternary systems of the active transition metal platinum with mixtures of gallium with either tin or indium. Reaction engineering and surface chemical analysis by X-ray photoelectron spectroscopy are combined with density functional theory (DFT) and machine learning force field (ML-FF) simulations. Introducing a third metal into the mixture alters the reactivity, surface composition, and concentration gradient in the liquid metal catalyst. We demonstrate that changes in catalytic reactivity correlate with changes in the surface concentration of the active transition metal platinum and of the position of the d-band center. These findings hold great promise for future research directions as they offer potential starting points for developing SCALMS systems.    

    
