#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Fri May  3 01:06:43 2024

Found 2 results from 2024-04-26 to 2024-05-03
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Dynamic dual-atom synergetic catalysis boosted by liquid metal for direct seawater electroreduction  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4396233717
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta01464b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396233717"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396233717"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396233717"))][Get cited by]]

OpenAlex: https://openalex.org/W4396233717 (Open access: False)
    
[[https://openalex.org/A5014946491][Haoxuan Li]], [[https://openalex.org/A5041690571][Jinghui Wang]], [[https://openalex.org/A5071490133][Mei Cui]], [[https://openalex.org/A5059124969][Renliang Huang]], [[https://openalex.org/A5071933793][Wei Qi]], [[https://openalex.org/A5050124317][Rongxin Su]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta01464b 
     
Ga based liquid metal is an ideal matrix to dissolve and disperse other metal atoms for catalysis. Seawater electrolysis is a promising alternative technology for hydrogen production in the crisis...    

    

* Operando Characterization and Molecular Simulations Reveal the Growth Kinetics of Graphene on Liquid Copper During Chemical Vapor Deposition  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4396517390
:TOPICS: Graphene: Properties, Synthesis, and Applications, Diamond Nanotechnology and Applications, Nanoscale Thermal Transport in Carbon Materials
:PUBLICATION_DATE: 2024-04-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.4c02070")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396517390"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396517390"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396517390"))][Get cited by]]

OpenAlex: https://openalex.org/W4396517390 (Open access: False)
    
[[https://openalex.org/A5006929737][Valentina Belova]], [[https://openalex.org/A5050054944][Hao Gao]], [[https://openalex.org/A5031837222][Hendrik H. Heenen]], [[https://openalex.org/A5092061311][Wissal Sghaier]], [[https://openalex.org/A5088137297][Anastasios C. Manikas]], [[https://openalex.org/A5033794109][Christos Tsakonas]], [[https://openalex.org/A5069837152][Mehdi Saedi]], [[https://openalex.org/A5044300693][Johannes T. Margraf]], [[https://openalex.org/A5071814045][Costas Galiotis]], [[https://openalex.org/A5077055219][Gilles Renaud]], [[https://openalex.org/A5079450836][Oleg Konovalov]], [[https://openalex.org/A5021296109][Irene M. N. Groot]], [[https://openalex.org/A5024866637][Karsten Reuter]], [[https://openalex.org/A5049417640][Maciej Jankowski]], ACS nano. None(None)] 2024. https://doi.org/10.1021/acsnano.4c02070 
     
In recent years, liquid metal catalysts have emerged as a compelling choice for the controllable, large-scale, and high-quality synthesis of two-dimensional materials. At present, there is little mechanistic understanding of the intricate catalytic process, though, of its governing factors or what renders it superior to growth at the corresponding solid catalysts. Here, we report on a combined experimental and computational study of the kinetics of graphene growth during chemical vapor deposition on a liquid copper catalyst. By monitoring the growing graphene flakes in real time using in situ radiation-mode optical microscopy, we explore the growth morphology and kinetics over a wide range of CH4-to-H2 pressure ratios and deposition temperatures. Constant growth rates of the flakes' radius indicate a growth mode limited by precursor attachment, whereas methane-flux-dependent flake shapes point to limited precursor availability. Large-scale free energy simulations enabled by an efficient machine-learning moment tensor potential trained to density functional theory data provide quantitative barriers for key atomic-scale growth processes. The wealth of experimental and theoretical data can be consistently combined into a microkinetic model that reveals mixed growth kinetics that, in contrast to the situation at solid Cu, is partly controlled by precursor attachment alongside precursor availability. Key mechanistic aspects that directly point toward the improved graphene quality are a largely suppressed carbon dimer attachment due to the facile incorporation of this precursor species into the liquid surface and a low-barrier ring-opening process that self-heals 5-membered rings resulting from remaining dimer attachments.    

    
