#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Wed Oct  2 01:20:05 2024

Found 3 results from 2024-09-25 to 2024-10-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Design and Application of a Liquid Metal Ball-Supported Layered Double Hydroxide Core-Shell Structure as Highly Efficient Catalysts for the Oxygen Evolution Reaction in Rechargeable Zinc-Air Batteries  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4402889971
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4968676")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402889971"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402889971"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402889971"))][Get cited by]]

OpenAlex: https://openalex.org/W4402889971 (Open access: False)
    
[[https://openalex.org/A5029078467][Liqing Qiao]], [[https://openalex.org/A5101991818][Wenwei Liu]], [[https://openalex.org/A5079336629][Na Du]], [[https://openalex.org/A5074814486][Wangwang Xu]], [[https://openalex.org/A5074870071][Yankun Li]], [[https://openalex.org/A5009161590][Haofeng Wu]], [[https://openalex.org/A5101026895][Zhonghua Bao]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4968676 
     
No abstract    

    

* Microwave-powered liquid metal depolymerization for plastic upcycling  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4402956622
:TOPICS: Global E-Waste Recycling and Management
:PUBLICATION_DATE: 2024-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-3550378/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402956622"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402956622"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402956622"))][Get cited by]]

OpenAlex: https://openalex.org/W4402956622 (Open access: False)
    
[[https://openalex.org/A5083945376][Jianye Gao]], [[https://openalex.org/A5031591139][Jun Zhao]], [[https://openalex.org/A5086869260][Zerong Xing]], [[https://openalex.org/A5076508346][Minghui Guo]], [[https://openalex.org/A5085237771][Haijiao Xie]], [[https://openalex.org/A5101764262][Wangjing Ma]], [[https://openalex.org/A5100725601][Jing Liu]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-3550378/v1 
     
Abstract Upcycling waste plastics is highly promising to tackle the global white pollution while achieving sustainable development. However, prevailing approaches often encounter challenges in scalable engineering practices due to either insufficient capability or arduousness in separation, recovery, and purification of catalysts, which inevitably augments the cost of plastic upcycling. Here, we present the microwave-powered liquid metal synergetic depolymerization to facilitate low-cost plastic upcycling. By leveraging the fluidity of liquid metals and their exceptional chemical-bond activation ability under microwave field, this method efficiently converts various polyolefins into narrowband hydrocarbon oil (Oil yield: 81 wt% for PP, 85.9 wt% for PE) and high-value olefin monomers (C2-4= selectivity: 50% for PE, 65.3% for PP) over 30 successive cycles, resulting in a high turnover frequency of 2.83 kgPlastic/mLCatalyst. These captivating advantages offered by electromagnetically-powered liquid metals are also supported by their self-separation features, thereby paving the way for large-scale engineering solutions in waste plastic upcycling.    

    

* An X‐Ray Absorption Spectroscopy Investigation into the Fundamental Structure of Liquid Metal Alloys  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4402782973
:TOPICS: Thermochemical Properties of Organic Compounds, Ice Nucleation and Melting Phenomena, Solar Water Splitting Technology
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smsc.202400317")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402782973"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402782973"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402782973"))][Get cited by]]

OpenAlex: https://openalex.org/W4402782973 (Open access: True)
    
[[https://openalex.org/A5068858319][Jaydon Meilak]], [[https://openalex.org/A5049005415][Karma Zuraiqi]], [[https://openalex.org/A5034047550][Valerie D. Mitchell]], [[https://openalex.org/A5042673824][Bernt Johannessen]], [[https://openalex.org/A5069370180][Brittany Kerr]], [[https://openalex.org/A5019680286][Pierre H. A. Vaillant]], [[https://openalex.org/A5066302811][Krystina Lamb]], [[https://openalex.org/A5020480772][Patjaree Aukarasereenont]], [[https://openalex.org/A5074271382][Caiden J. Parker]], [[https://openalex.org/A5094034780][Taren Cataldo]], [[https://openalex.org/A5004619045][François Malherbe]], [[https://openalex.org/A5073206123][Andrew J. Christofferson]], [[https://openalex.org/A5091422934][Torben Daeneke]], [[https://openalex.org/A5002235771][Rosalie K. Hocking]], Small Science. None(None)] 2024. https://doi.org/10.1002/smsc.202400317 
     
Gallium and gallium alloys have gained significant interest due to gallium's low melting point. This property allows for gallium‐based catalysts to take advantage of the unique reaction environments only available in the liquid state. While understanding of the catalytic properties of liquid metals is emerging, a comprehensive investigation into the fundamental structures of these materials has yet to be undertaken. Herein, the structure of liquid gallium, along with related liquid alloys EGaIn, EGaSn, and Galinstan are explored using X‐ray absorption spectroscopy (XAS). In contrast to some other studies that show dimers, analysis of the XAS data both in X‐ray absorption near edge structure and extended X‐ray absorption fine structure shows that when fully dissolved the materials are largely homogenous with no obvious signs of local structures. Ga shows a bond contraction when melted which is consistent with its increase in density; however, an expansion in bond length is observed when alloyed with In and Sn. XAS data indicate that the effective nuclear charge ( Z eff ) of In and Sn follows the trend expected based on electronegativity. Molecular dynamic (MD) simulations are performed to simulate the structure and trends between MD and XAS; the trends agree well but MD overestimates bond lengths.    

    
