#+filetags: liquid-metal
#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Fri Feb 16 00:42:59 2024

Found 1 results from 2024-02-09 to 2024-02-16
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Carbon Dioxide Reduction on Alloyed Galinstan  :liquid_metal:
:PROPERTIES:
:ID: https://openalex.org/W4391663508
:TOPICS: Structural Analysis and Design Optimization in Engineering
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472400mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663508"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663508"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663508"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663508 (Open access: False)
    
[[https://openalex.org/A5059375955][Aya Gomaa Abdelkader Mohamed]], [[https://openalex.org/A5017548688][Peter Bogdanoff]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472400mtgabs 
     
Solar powered electrochemical CO₂ reduction to disposable products is presently being developed as one of negative carbon emission technologies 1 . State-of-the-art electrocatalysts are mainly developed for the CO 2 reduction to hydrogen rich products or chemical feedstock materials while for the above-mentioned application solid carbon-rich products are desired (best pure carbon). Even though the formation of solid products is sometimes observed on catalysts (coking effect), this usually leads to an undesirable irreversible deactivation of their solid interfaces. Thus, the development of next generation CO 2 electrocatalysts is demanded based on liquid metal alloys such as galinstan (GaInSn). The advantage of using liquid phase electrodes is to eliminate coking and coarsening limitations that are associated with solid catalysts. For example, it has been reported that ceria-supported liquid galinstan can electrochemically produce carbonaceous materials from CO 2 gas 2 . This shows, that doping with additional active elements can change the CO 2 reduction activity of GaInSn in the direction of other desired products. Our work investigates the activity of galinstan for the electroreduction of CO 2 depending on alloying with additional metals (such as Ce, Ag, Pb). While pure GaInSn shows a predominant activity for the formation of C1 products (CO, HCOOH) in DMF/H 2 O electrolyte, we are mainly interested in the formation of solid carbon or oxalate. Therefore, our investigations aim at finding suitable modifications of GaInSn that achieve high selectivity for these products. Electrochemical analysis coupled with in-line gas chromatography and in-line mass spectroscopy are used to characterize the reactivity. Furthermore, the influence of the water content of the organic electrolyte on the product selectivity will be investigated. In particular, to suppress the observed low hydrogen evolution as a by-product even more efficiently. May, M. M.; Rehfeld, K., Negative Emissions as the New Frontier of Photoelectrochemical CO 2 Reduction. Advanced Energy Materials 2022, 2103801. Esrafilzadeh, D.; Zavabeti, A.; Jalili, R.; Atkin, P.; Choi, J.; Carey, B. J.; Brkljača, R.; O’Mullane, A. P.; Dickey, M. D.; Officer, D. L.; MacFarlane, D. R.; Daeneke, T.; Kalantar-Zadeh, K., Room Temperature CO 2 Reduction to Solid Carbon Species on Liquid Metals Featuring Atomically Thin Ceria Interfaces. Nature Communications 2019, 10 (1), 865. Figure 1    

    
