#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Sun Jun 16 01:13:47 2024

Found 1 results from 2024-06-09 to 2024-06-16
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* High‐Entropy Alloy Array via Liquid Metal Nanoreactor  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4399477201
:TOPICS: Two-Photon Microfabrication Techniques, Laser Ablation Synthesis of Nanoparticles, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202403865")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399477201"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399477201"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399477201"))][Get cited by]]

OpenAlex: https://openalex.org/W4399477201 (Open access: False)
    
[[https://openalex.org/A5050080938][Jingjing Liang]], [[https://openalex.org/A5014045701][S. H. Chen]], [[https://openalex.org/A5090907393][Erli Ni]], [[https://openalex.org/A5050947701][Jiao Tang]], [[https://openalex.org/A5042714994][Guanghui Cao]], [[https://openalex.org/A5024002505][Huiliu Wang]], [[https://openalex.org/A5085504331][Zhongyang Li]], [[https://openalex.org/A5062734314][Mengqi Zeng]], [[https://openalex.org/A5004437037][Lei Fu]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202403865 
     
Abstract High‐entropy alloy (HEA) nanostructures arranged into well‐defined configurations hold great potential for accelerating the development of electronics, photonics, catalysis, and device integration. However, the random nucleation induced by the disparity in physicochemical properties of multiple elements makes it challenging to achieve single‐particle synthesis at the patterned preset sites in the high‐entropy scenario. Herein, we proposed the liquid metal nanoreactor strategy to realize the construction of HEA arrays. The coalescence of the liquid metal driven by the tendency to decrease surface energy provides a restricted environment for the nucleation and growth to form single HEA particles at the preset locations, which could be regarded as a self‐confinement reaction. Liquid metal endowing a low diffusion barrier on the substrate and a high diffusivity of the alloy system could dynamically promote the aggregation process. As a result, the HEA array was prepared with elements up to eleven and possessed uniform periodicity, which exhibited excellent holography response in a broad spectrum. Our work injects new vitality into the construction of HEA nanopatterns and provides an excellent platform for propelling their fundamental research and applications. This article is protected by copyright. All rights reserved    

    
