#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Wed May 15 01:06:04 2024

Found 1 results from 2024-05-08 to 2024-05-15
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Liquid Gallium–Zeolite Nanocomposite Catalysts for Propane Dehydrogenation  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4396779052
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-05-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.iecr.4c00411")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4396779052"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4396779052"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4396779052"))][Get cited by]]

OpenAlex: https://openalex.org/W4396779052 (Open access: False)
    
[[https://openalex.org/A5038191313][Shuo Zhang]], [[https://openalex.org/A5006352222][Bofeng Zhang]], [[https://openalex.org/A5028780287][Mingxia Song]], [[https://openalex.org/A5028116005][Liming Xia]], [[https://openalex.org/A5018069202][Guozhu Liu]], Industrial & engineering chemistry research. None(None)] 2024. https://doi.org/10.1021/acs.iecr.4c00411 
     
Liquid metal (LM) with outstanding fluidity, excellent electrical and thermal conductivity is emerging in heterogeneous catalysis, such as Ga-based supported catalytically active liquid-metal solutions. However, liquid gallium droplets are prone to migration and aggregation, especially under high-temperature reaction conditions. Herein, we designed a liquid gallium-zeolite nanocomposite catalyst (L-Ga/S-1) by a simple and low-cost physical mixing method. In propane dehydrogenation, the optimized L-1.5-Ga/S-1 exhibited a high formation rate of 1.17 mol C3H6gGa–1 h–1, 13 times higher than that of 1.5-Ga-MFI, with a propylene selectivity of up to 95% at 550 °C. It could be ascribed to abundant interface GaOx structure between Ga droplet and nanosized Silicalite-1 zeolite, which provided strong Lewis acidic sites to promote the selective scission of C–H bonds. Liquid metal–metal oxide nanocomposites offer an important way for controlling interface precisely in the sphere of heterogeneous catalysis.    

    
