#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Sat Nov 16 01:23:19 2024

Found 1 results from 2024-11-09 to 2024-11-16
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Nanoporous Cu-based amorphous alloys prepared by selective dissolution in acidic media  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4404244174
:TOPICS: Evolution and Applications of Nanoporous Metals, Fabrication and Applications of Porous Alumina Membranes, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1757-899x/1319/1/012032")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4404244174"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4404244174"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4404244174"))][Get cited by]]

OpenAlex: https://openalex.org/W4404244174 (Open access: True)
    
[[https://openalex.org/A5005293169][Sebastian Ambruş]], [[https://openalex.org/A5004837368][Roxana Muntean]], [[https://openalex.org/A5089831717][Dragoş Buzdugan]], [[https://openalex.org/A5011823190][Cosmin Codrean]], IOP Conference Series Materials Science and Engineering. 1319(1)] 2024. https://doi.org/10.1088/1757-899x/1319/1/012032 
     
Abstract Functional nanoporous materials are considered a significant category of nanostructured materials that exhibit distinct characteristics like high surface area, porosity, and improved mass transport properties. These qualities render them suitable for a wide range of applications including catalysis, energy storage, biomedical fields, and electrochemical sensors. Dealloying or laser-induced technologies are the primary methods employed to fabricate such nanoporous materials. Dealloying is a dependable top-down approach used to produce hierarchical, disordered nanoporous materials with customizable pore sizes in the range of a few nanometers. The process of dealloying involves the selective elimination or dissolution of one or more elements from an alloy through a corrosion mechanism, using various dealloying techniques, such as chemical, electrochemical, liquid metal, or vapor phase dealloying. In the present study, copper-based amorphous metallic ribbons (Cu75Ni6Sn5P10Ga4) were initially manufactured using the melt-spinning method. The Cu-based amorphous ribbons were structurally investigated by X-ray diffraction and thermal analysis. Subsequently, the ribbons were subjected to a dealloying treatment, using an acidic solution to selectively dissolve the nickel from their composition and to obtain a nanoporous structure. The microstructure and chemical composition of the ribbons before and after the dealloying process were investigated using scanning electron microscopy (SEM), combined with energy-dispersive X-ray spectroscopy. The dealloying process performed in 1 M H2SO4 solution at 25 °C for 60 minutes leads to a large number of nanopores, uniformly distributed onto the surface of the Cu-based ribbons.    

    
