#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Thu Oct 31 01:22:00 2024

Found 2 results from 2024-10-24 to 2024-10-31
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Enhanced casein organohydrogel coating with liquid metal catalyst for Electric leather sensor in Human-Machine interaction  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4403847693
:TOPICS: Wearable Nanogenerator Technology, Eye Tracking in Human-Computer Interaction, Conducting Polymer Research
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.156841")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403847693"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403847693"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403847693"))][Get cited by]]

OpenAlex: https://openalex.org/W4403847693 (Open access: False)
    
[[https://openalex.org/A5051866211][Qunna Xu]], [[https://openalex.org/A5001893388][Zhenyang Li]], [[https://openalex.org/A5111360250][Jun Wang]], [[https://openalex.org/A5101605228][Jianzhong Ma]], [[https://openalex.org/A5063084241][Kai Yan]], [[https://openalex.org/A5002958688][Yan Zong]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.156841 
     
No abstract    

    

* Facile and Environmentally Friendly Synthesis of Ga2O3/MFI Catalysts for Propane Dehydrogenation  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4403733617
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-10-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c11679")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403733617"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403733617"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403733617"))][Get cited by]]

OpenAlex: https://openalex.org/W4403733617 (Open access: False)
    
[[https://openalex.org/A5086098186][Chaocheng Weng]], [[https://openalex.org/A5108537272][Dongfang Song]], [[https://openalex.org/A5011257188][Linqing Gu]], [[https://openalex.org/A5100684579][Hui Huang]], [[https://openalex.org/A5029708837][Jiaping Lu]], [[https://openalex.org/A5036834319][Kangjian Tang]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c11679 
     
A GaOx-based catalyst is recognized as a promising catalyst for dehydrogenation of light alkanes. Conventionally, impregnation and calcination are necessary processes for the loading of GaOx. However, the incomplete impregnation of gallium salt solution would generate wastewater, and the calcination for the dissociation of gallium salt would release harmful gases, such as SOx, NOx, and HCl. Meanwhile, the high temperature results in an excessive energy cost and undesired GaOx particle aggregation. Here, we report a facile and environmentally friendly method for the synthesis of GaOx-based catalysts. The gallium salt solution was replaced directly with liquid gallium (LG). Through a simple physical mixing method at room temperature, uniform GaOx nanoparticles with diameters of around 3.5 nm were loaded onto the surface of silicalite-1 (S-1). With the optimal GaOx/MFI catalyst, the propane conversion and propylene selectivity reached 22.9 and 90.1%, respectively, in the propane dehydrogenation reaction. The work offers a clean and economical strategy utilizing liquid metal (LM) as an impregnation solution for the preparation of GaOx-based catalysts.    

    
