#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Sun Dec 22 01:27:05 2024

Found 2 results from 2024-12-15 to 2024-12-22
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* (Invited) How to Make and Manipulate Carbonaceous Materials Using Liquid Metals  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4405590786
:TOPICS: 
:PUBLICATION_DATE: 2024-11-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2024-02111542mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405590786"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405590786"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405590786"))][Get cited by]]

OpenAlex: https://openalex.org/W4405590786 (Open access: False)
    
[[https://openalex.org/A5067220816][Kourosh Kalantar‐zadeh]], Meeting abstracts/Meeting abstracts (Electrochemical Society. CD-ROM). MA2024-02(11)] 2024. https://doi.org/10.1149/ma2024-02111542mtgabs 
     
Liquid metal-based processes offer significant possibilities in the realm of carbon-based materials. Liquid metals are highly electrically conductive, making them suitable for electrochemical redox processes. They serve as atomically smooth templating substrates for creating planar structures. The absence of interfacial forces, owing to the non-polar nature of liquid metals, facilitates self-exfoliation of the synthesized two-dimensional (2D) layers from the surface of liquid metals. In addition, liquid metals can act as natural catalysts for promoting the formation of C-C bonds and are immiscible with non-metallic systems, including electrolytes, making them compatible with various electrochemical systems. Liquid metals can also engineer carbonaceous materials in contact with their interface. These properties facilitate the construction of carbonaceous materials from various organic precursors to CO 2 and also tailoring of carbon based materials using liquid metals. Room temperature synthesis and engineering of 2D graphitic materials (2D-GMs) remains an elusive goal, especially through electrochemical means. Here, it is demonstrated that liquid metals make this achievable by providing catalytic activity and an ultra-smooth templating interface conducive to Frank–van der Merwe regime growth. Moreover, they enable facile exfoliation due to the absence of interfacial forces as a non-polar liquid. The 2D-GMs is shown to be formed at a low onset potential and can be in situ doped based on the choice of organic precursors and the electrochemical setup. The synthesized materials can be tuned to exhibit porous or pinhole-free morphologies and engineered for their degree of oxidation and number of layers. In another part of the talk, the interfacial interaction between eutectic gallium–indium (EGaIn) liquid metal and graphene oxide (GO) for reducing both substrate-based and free-standing GO will be discussed. NanoIR surface mapping confirms the successful removal of carbonyl groups. Building upon this knowledge, a composite comprising assembled reduced GO sheets on LM microdroplets (LM–rGO) is presented. The LM reinforces Ga 3+ coordination within the rGO assembly, thereby modifying the electrochemical interface for selective dopamine sensing by separating the peaks of interfering biologicals. Subsequently, paper-based electrodes modified with LM–rGO is shown, demonstrating the compatibility of the assembly with low-cost commercial technologies.    

    

* Microwave‐Powered Liquid Metal Degradation of Polyolefins  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4405597652
:TOPICS: Microplastics and Plastic Pollution, Recycling and Waste Management Techniques, biodegradable polymer synthesis and properties
:PUBLICATION_DATE: 2024-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202412539")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4405597652"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4405597652"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4405597652"))][Get cited by]]

OpenAlex: https://openalex.org/W4405597652 (Open access: True)
    
[[https://openalex.org/A5083945376][Jianye Gao]], [[https://openalex.org/A5108602781][Jun Zhao]], [[https://openalex.org/A5086869260][Zerong Xing]], [[https://openalex.org/A5076508346][Minghui Guo]], [[https://openalex.org/A5085237771][Haijiao Xie]], [[https://openalex.org/A5112244650][Wangjing Ma]], [[https://openalex.org/A5100653469][Jing Liu]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202412539 
     
Upcycling waste plastics is highly promising to tackle global white pollution while achieving sustainable development. However, prevailing approaches often encounter challenges in scalable engineering practices due to either insufficient plastic upcycling capability or arduousness in the separation, recovery, and purification of catalysts, which inevitably augments the cost of plastic upcycling. Here, the microwave-powered liquid metal synergetic depolymerization is presented to facilitate low-cost plastic upcycling. By leveraging the fluidity of liquid metals and their exceptional chemical-bond activation ability under microwave field, this method efficiently converts various polyolefins into narrowband hydrocarbon oil (Oil yield: 81 wt.% for polypropylene (PP), 85.9 wt.% for polyethylene (PE)) and high-value olefin monomers (C    

    
