#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Sun Oct 13 01:25:13 2024

Found 3 results from 2024-10-06 to 2024-10-13
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Flexible Triboelectric Sensor based on Catalyst‐Diffusion Self‐Encapsulated Conductive Liquid‐Metal‐Silicone Ink for Somatosensory Soft Robotic System  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4403214305
:TOPICS: Wearable Nanogenerator Technology, Conducting Polymer Research, Tactile Perception and Cross-modal Plasticity
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202412293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403214305"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403214305"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403214305"))][Get cited by]]

OpenAlex: https://openalex.org/W4403214305 (Open access: False)
    
[[https://openalex.org/A5008857817][Shuai Xian]], [[https://openalex.org/A5010277066][Yong Xu]], [[https://openalex.org/A5006437625][Yixin Li]], [[https://openalex.org/A5001397144][Zhenfeng Wu]], [[https://openalex.org/A5103124477][Xing Xie]], [[https://openalex.org/A5018008505][Zhigang Wu]], [[https://openalex.org/A5089296010][Xiya Yang]], [[https://openalex.org/A5022694543][Yong Zhong]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202412293 
     
Abstract The combination of fluidity and metallic conductivity has attracted considerable attention to liquid metal (LM), but its development remains challenging due to enormous surface tension. Here, vinyl‐terminated silicone oil and platinum catalyst are added to LM to reduce its surface tension, which develops a special type of liquid‐metal‐silicone (LMS) ink with a catalyst diffusion effect. Combined with an embedded three‐dimentional (3D) printing method, the LMS ink is printed on the support matrix, and the catalyst diffuses outward along the print path to cure the silicone around it, directly constructing self‐encapsulated conductive composites with excellent conductivity and self‐encapsulated flexible tactile sensors based on triboelectric nanogenerator (TENG). The sensor exhibits excellent sensitivity (0.308 V kPa −1 ), high linearity (≈0.99), and good durability (over 10 000 cycles). Furthermore, when used in flexible wearable electronics, the sensor demonstrates a good performance with an accuracy of ≈96% in classifying different human postures using a convolutional neural network. Finally, through embedded 3D printing with LMS ink and silicone ink, a somatosensory soft robotic gripper with complex cavity structures is designed and manufactured in one step, achieving the all‐in‐one integration of sensors and actuators. This study shows great application potential in flexible electronics and soft robotic systems.    

    

* Liquid Metal Electrocatalyst with Ultralow Pt Loading for Ethanol Oxidation  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4403202030
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smsc.202400370")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403202030"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403202030"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403202030"))][Get cited by]]

OpenAlex: https://openalex.org/W4403202030 (Open access: True)
    
[[https://openalex.org/A5101863261][Muhammad Hamza Nazir]], [[https://openalex.org/A5004908996][Tu C. Le]], [[https://openalex.org/A5079980552][Imtisal Zahid]], [[https://openalex.org/A5049005415][Karma Zuraiqi]], [[https://openalex.org/A5092451346][Mew P. Aukarasereenont]], [[https://openalex.org/A5074271382][Caiden J. Parker]], [[https://openalex.org/A5019680286][Pierre H. A. Vaillant]], [[https://openalex.org/A5092152426][Fahad Jabbar]], [[https://openalex.org/A5045506863][Chung Kim Nguyen]], [[https://openalex.org/A5078174778][Mehmood Irfan]], [[https://openalex.org/A5008589079][Mariam Ameen]], [[https://openalex.org/A5076418865][Michelle J. S. Spencer]], [[https://openalex.org/A5073206123][Andrew J. Christofferson]], [[https://openalex.org/A5031877516][Salvy P. Russo]], [[https://openalex.org/A5103100569][Ken Chiang]], [[https://openalex.org/A5050500604][Nastaran Meftahi]], [[https://openalex.org/A5091422934][Torben Daeneke]], [[https://openalex.org/A5031980737][Dan Yang]], Small Science. None(None)] 2024. https://doi.org/10.1002/smsc.202400370 
     
Developing efficient and durable electrocatalysts for ethanol electro‐oxidation is crucial for enabling the application of direct ethanol fuel cell technology. Herein, it is demonstrated that Pt–Ga liquid metal‐based nanodroplets can serve as an efficient electrocatalyst to drive ethanol oxidation. The mass activity of Pt is significantly improved by alloying with liquid gallium. Guided by machine learning neural networks, a low‐concentration alkaline electrolyte is specifically formulated to allow electrodes with ultralow Pt loading to demonstrate remarkable activity toward ethanol oxidation with a mass activity as high as 13.47 A mg −1 Pt , which is more than 14 times higher than that of commercial Pt/C electrocatalysts (i.e., 0.76 A mg −1 Pt ). Computational studies reveal that the superior activity is associated with the presence of Ga oxides adjacent to Pt on the catalyst surface which leads to energetically favorable pathways for the oxidation process. The findings reveal untapped opportunities in the realm of liquid metal catalysis and hold great promise for the future development of high‐performance alcohol fuel cells.    

    

* Methane Pyrolysis to Produce Hydrogen and Carbon Solids Using Thermocatalytic Pathway  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4403287485
:TOPICS: Catalytic Carbon Dioxide Hydrogenation, Heat Transfer to Supercritical Fluids in Channels, Chemical-Looping Technologies
:PUBLICATION_DATE: 2024-10-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2118/221204-ms")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403287485"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403287485"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403287485"))][Get cited by]]

OpenAlex: https://openalex.org/W4403287485 (Open access: False)
    
[[https://openalex.org/A5078559865][Ivy Ching Hsia Chai]], [[https://openalex.org/A5005761415][Yang‐Hao Chan]], [[https://openalex.org/A5107489191][K. E. Nikulainen]], [[https://openalex.org/A5107607101][J. Laukka]], [[https://openalex.org/A5030760623][Mohd Azlan Bin Mohd Ishak]], No host. 4(None)] 2024. https://doi.org/10.2118/221204-ms 
     
Thermo-catalytic decomposition (TCD) of natural gas is a suitable technology to provide clean hydrogen (H2). This TCD process directly splits hydrocarbons, mainly methane (CH4), into H2 and carbon as illustrated in Equation 1. [Equation 1]CH4(g)→C(s)+2H2(g)ΔH∘=74 kJ/mol In TCD process, H2 is produced as a gas while carbon is generated in solid form. Though the reaction can occur with heat energy alone, the use of a catalyst significantly reduces the required reaction temperature, making the process less energy-intensive. Various reactor designs are used for TCD to pyrolyze CH4, including fluidized/packed bed reactor, moving bed reactor, bubble column reactor (using molten metal or salt), and plug flow reactor. This paper elucidates ROTOBOOST's bubble column reactor, which utilizes a specific molten metal alloy as TCD catalyst. Although methane pyrolysis demonstration has started since the 1950s, the development and understanding of liquid catalyst in bubble column has gained more momentum since the 2000s. This stems from the benefit of lowering the reaction temperature to below 1000°C, making the process less energy-intensive, mitigating coking issues and subsequent deactivation of solid catalysts, and allowing better control and tuning of solid carbon quality Von Wald et al. (2020) reported that methane pyrolysis using the bubble column technology with liquid metal catalyst is a suitable process for reducing CO2 emissions in the short term. In TCD process with bubble column reactor, pre-treated natural gas or methane is continuously fed to the bottom of the reactor, allowing it to travel upward through the molten catalytic alloy, which is heated to the reaction temperature. The catalytic alloy, with high heat capacity, provides a homogenous heat supply directly to each hydrocarbon gas molecule. As the bubbles burst at the upper interface of the liquid media, H2 and carbon are released. Since the density of carbon is much lower than that of the molten media, the produced carbon rises with the bubbles, floating at top of the liquid surface, and finally deposits at the surface of the liquid column. Therefore, the produced carbon does not affect the reaction zone on the inside/surface of the bubbles as they rise through the molten media, ensuring the bubble surface is a continuously renewed catalyst. The main advantage of liquid bubble column reactors is the continuous carbon removal from the liquid media due to density differences, preventing reactor blockage or contamination from carbon accumulation.    

    
