#+filetags: liquid-metal
#+TITLE: liquid-metal
Created on Thu Jan 18 00:41:15 2024

Found 10 results from 2024-01-04 to 2024-01-18
** Liquid Metal Catalysis   
:PROPERTIES:
:ID: https://openalex.org/W4390621338
:DOI: https://doi.org/10.1007/978-981-19-2797-3_48-1
:AUTHORS: Shuting Liang
:HOST: No host
:END:

Shuting Liang, No host. None(None)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-981-19-2797-3_48-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390621338"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390621338"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390621338"))][Get cited by]]

OpenAlex: https://openalex.org/W4390621338
    
Shuting Liang, No host. https://doi.org/10.1007/978-981-19-2797-3_48-1
    
With the rapid growth of the world population and the continuous shortage of resources and energy, the research on liquid metal catalyst has gradually come into view. In recent years, the development of liquid metal and its alloys as new catalysts has made a great leap forward. Liquid metals as flow catalysts offer new research and development opportunities. Applications of liquid metal systems include the catalytic controlled growth of graphene, the catalytic growth of 2D materials (MoO2, MoS2, SnOx, etc.), the catalytic reduction of CO2 to achieve carbon neutrality, the catalytic organic and inorganic reactions (including propane dehydrogenation, methane dehydrogenation, polyphenol self-polymerization, free radical polymerization, etc.), and the catalytic production of hydrogen. Liquid metal catalysts also include photocatalysts, electrocatalysts, bimetallic catalysts, LM/MO frame catalysts, and heterogeneous catalysts. The classification, application, and related catalytic mechanism of different liquid metal catalysts at home and abroad were reviewed in this chapter. Liquid metal catalysts could be used as revolutionary materials in the new century, and their application in the field of catalysis presents new challenges.    

    

** Intercalation of pyrazolone-based oxalamide metal complexes into Na-montmorillonite for catalytic liquid-phase oxidation of phenol using H2O2   
:PROPERTIES:
:ID: https://openalex.org/W4390605526
:DOI: https://doi.org/10.55730/1300-0527.3630
:AUTHORS: Serhat Uzan, Eyüp Başaran
:HOST: Turkish Journal of Chemistry
:END:

Serhat Uzan, Eyüp Başaran, Turkish Journal of Chemistry. 47(6)] 2023.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.55730/1300-0527.3630")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390605526"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390605526"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390605526"))][Get cited by]]

OpenAlex: https://openalex.org/W4390605526
    
Serhat Uzan, Eyüp Başaran, Turkish Journal of Chemistry. https://doi.org/10.55730/1300-0527.3630
    
The intercalation of pyrazolone-based oxalamide metal complexes into Na-montmorillonite (Na-MMT) for catalytic liquid-phase oxidation of phenol using H2O2 was undertaken by a flexible ligand method using metal ions including Mn(II), Zn(II), and Sn(II). First, the metal ions were exchanged with the sodium ions of Na-MMT, and then these metal ions were complexed with a new pyrazolone-based oxalamide ligand. The intercalated metal complexes were characterized by Fourier transform infrared spectroscopy, X-ray diffraction, scanning electron microscopy, energy-dispersive X-ray spectroscopy, elemental analysis, and thermogravimetric analysis. Phenol was successfully oxidized by heterogeneous catalysts based on Mn(II), Zn(II), and Sn(II) pyrazolone-based oxalamide complexes intercalated into Na-MMT. These heterogeneous catalysts catalyze the liquid-phase oxidation of phenol using H2O2 to catechol as the major product and hydroquinone and benzoquinone as the minor products. The Mn(II) and Zn(II) complexes intercalated into Na-MMT showed better activity than the Sn(II) complex intercalated into Na-MMT and the reaction without the catalyst. It has been shown that some metal ion complexes intercalated into Na-MMT are active catalysts for liquid-phase oxidation of phenol with hydrogen peroxide.    

    

** Polyethylene Upgrading to Liquid Fuels Boosted by Atomic Ce Promoters   
:PROPERTIES:
:ID: https://openalex.org/W4390637146
:DOI: https://doi.org/10.1002/anie.202317594
:AUTHORS: Xueting Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang
:HOST: Angewandte Chemie International Edition
:END:

Xueting Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang, Angewandte Chemie International Edition. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202317594")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390637146"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390637146"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390637146"))][Get cited by]]

OpenAlex: https://openalex.org/W4390637146
    
Xueting Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang, Angewandte Chemie International Edition. https://doi.org/10.1002/anie.202317594
    
Hydrocracking catalysis is a key route to plastic waste upgrading, but the acid site‐driven C‐C cleavage step is relatively sluggish in conventional bifunctional catalysts, dramatically effecting the overall efficiency. We demonstrate here a facile and efficient way to boost the reactivity of acid sites by introducing Ce promoters into Pt/HY catalysts, thus achieving a better metal‐acid balance. Remarkably, 100 % of LDPE can be converted with 80.9 % selectivity of liquid fuels over the obtained Pt/5Ce‐HY catalysts at 300 °C in 2 h. For comparison, Pt/HY only gives 38.8% of LDPE conversion with 21.3% selectivity of liquid fuels. Through multiple experimental studies on the structure‐performance relationship, the Ce species occupied in the supercage are identified as the actual active sites, which possess remarkably‐improved adsorption capability towards short‐chain intermediates.    

    

** Polyethylene Upgrading to Liquid Fuels Boosted by Atomic Ce Promoters   
:PROPERTIES:
:ID: https://openalex.org/W4390637288
:DOI: https://doi.org/10.1002/ange.202317594
:AUTHORS: Xia Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang
:HOST: Angewandte Chemie
:END:

Xia Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang, Angewandte Chemie. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202317594")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390637288"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390637288"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390637288"))][Get cited by]]

OpenAlex: https://openalex.org/W4390637288
    
Xia Wu, Xiao Wang, Lingling Zhang, Xiaomei Wang, Shuyan Song, Hongjie Zhang, Angewandte Chemie. https://doi.org/10.1002/ange.202317594
    
Hydrocracking catalysis is a key route to plastic waste upgrading, but the acid site‐driven C‐C cleavage step is relatively sluggish in conventional bifunctional catalysts, dramatically effecting the overall efficiency. We demonstrate here a facile and efficient way to boost the reactivity of acid sites by introducing Ce promoters into Pt/HY catalysts, thus achieving a better metal‐acid balance. Remarkably, 100 % of LDPE can be converted with 80.9 % selectivity of liquid fuels over the obtained Pt/5Ce‐HY catalysts at 300 °C in 2 h. For comparison, Pt/HY only gives 38.8% of LDPE conversion with 21.3% selectivity of liquid fuels. Through multiple experimental studies on the structure‐performance relationship, the Ce species occupied in the supercage are identified as the actual active sites, which possess remarkably‐improved adsorption capability towards short‐chain intermediates.    

    

** CuNiZn vs CuZn Electrodes: Electrochemical CO<sub>2</sub> Reduction, Role of Metal Elements, and Insights for C–C Coupling Chemistry   
:PROPERTIES:
:ID: https://openalex.org/W4390563376
:DOI: https://doi.org/10.1021/acsaem.3c02550
:AUTHORS: Yunji Gwon, Seon Young Hwang, Go Eun Park, Sang-Eun Bae, Gak-Won Yun, Choong Kyun Rhee, Youngku Sohn
:HOST: ACS Applied Energy Materials
:END:

Yunji Gwon, Seon Young Hwang, Go Eun Park, Sang-Eun Bae, Gak-Won Yun, Choong Kyun Rhee, Youngku Sohn, ACS Applied Energy Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c02550")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390563376"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390563376"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390563376"))][Get cited by]]

OpenAlex: https://openalex.org/W4390563376
    
Yunji Gwon, Seon Young Hwang, Go Eun Park, Sang-Eun Bae, Gak-Won Yun, Choong Kyun Rhee, Youngku Sohn, ACS Applied Energy Materials. https://doi.org/10.1021/acsaem.3c02550
    
Exploring bi- and trimetallic catalysts in electrochemical CO2 reduction (EC CO2R) has been a focal point for discovering reduction products. This study investigates the distinct roles of metal elements in the CO2R using CuNiZn and CuZn electrodes. Bimetallic CuZn exhibits superior electrochemical activity, yielding substantial amounts of CO, CH4, C2H4, and various liquid products, including formate, ethanol, acetate, propanol, and isopropanol. The study on trimetallic CuNiZn suggests potential connections to Fischer–Tropsch (FT) synthesis, indicating their capability to produce long-chain hydrocarbons (CnH2n and CnH2n+2, n = 2–7) from CO2. EC CO reduction validated the FT process over the bi- and trimetallic catalysts. The discussion explores mechanisms for the formation of CO, CH4, and C–C coupled C2+ products, considering potential- and concentration-dependent Faradaic efficiencies (FEs). Recycling tests emphasize the influence of metal composition on FEs. Surface analyses reveal oxidation states and compositional changes, while the dissolution of metals during electrochemistry highlights dynamic surface characteristics. This work provides insights into the metal composition of bi- and trimetallic catalysts, surface states, and electrochemical conditions, advancing our understanding of these electrodes and their role in CO2 recycling through electrochemistry.    

    

** Nickel Carbide Nanoparticle Catalyst for Selective Hydrogenation of Nitriles to Primary Amines   
:PROPERTIES:
:ID: https://openalex.org/W4390615119
:DOI: https://doi.org/10.1002/chem.202303573
:AUTHORS: Sho Yamaguchi, Daiki Kiyohira, Kohei Tada, Taiki Kawakami, Akira Miura, Takato Mitsudome, Tomoo Mizugaki
:HOST: Chemistry - A European Journal
:END:

Sho Yamaguchi, Daiki Kiyohira, Kohei Tada, Taiki Kawakami, Akira Miura, Takato Mitsudome, Tomoo Mizugaki, Chemistry - A European Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202303573")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390615119"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390615119"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390615119"))][Get cited by]]

OpenAlex: https://openalex.org/W4390615119
    
Sho Yamaguchi, Daiki Kiyohira, Kohei Tada, Taiki Kawakami, Akira Miura, Takato Mitsudome, Tomoo Mizugaki, Chemistry - A European Journal. https://doi.org/10.1002/chem.202303573
    
Despite its unique physicochemical properties, the catalytic application of nickel carbide (Ni3C) in organic synthesis is rare. In this study, we report well‐defined nanocrystalline Ni3C (nano‐Ni3C) as a highly active catalyst for the selective hydrogenation of nitriles to primary amines. The activity of the aluminum‐oxide‐supported nano‐Ni3C (nano‐Ni3C/Al2O3) catalyst surpasses that of Ni nanoparticles. Various aromatic and aliphatic nitriles and dinitriles were successfully converted to the corresponding primary amines under mild conditions (1 bar H2 pressure). Furthermore, the nano‐Ni3C/Al2O3 catalyst was reusable and applicable to gram‐scale experiments. Density functional theory calculations suggest the formation of polar hydrogen species on the nano‐Ni3C surface, which were attributed to the high activity of nano‐Ni3C towards nitrile hydrogenation. This study demonstrates the utility of metal carbides as a new class of catalysts for liquid‐phase organic reactions.    

    

** Ionic liquid dopant induced 3D hierarchical CuO nanostructures with doped heteroatoms and highly dispersed Ag for electrochemical upgrading of 5-hydroxymethylfurfural   
:PROPERTIES:
:ID: https://openalex.org/W4390636084
:DOI: https://doi.org/10.1016/j.cej.2024.148580
:AUTHORS: Chaofan Li, Fengke Wang, Yi Nie, Leilei Wang, Zhihao Zhang, Tianhao Liu, Binghui He, Yunqian Ma, Lihua Zang
:HOST: Chemical Engineering Journal
:END:

Chaofan Li, Fengke Wang, Yi Nie, Leilei Wang, Zhihao Zhang, Tianhao Liu, Binghui He, Yunqian Ma, Lihua Zang, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148580")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390636084"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390636084"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390636084"))][Get cited by]]

OpenAlex: https://openalex.org/W4390636084
    
Chaofan Li, Fengke Wang, Yi Nie, Leilei Wang, Zhihao Zhang, Tianhao Liu, Binghui He, Yunqian Ma, Lihua Zang, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2024.148580
    
The electrocatalytic 5-hydroxymethylfurfural oxidation reaction (HMFOR) has received increasing attention due to its carbon–neutral and value-added chemical properties, and the development of electrocatalyst with highly active and selective is crucial. Highly dispersing metal atoms throughout the catalyst can maximize the catalytic efficiency. Here, we synthesized a 3D hierarchical CuO nanostructure induced by ionic liquid with heteroatoms doping and Ag dispersing (Ag-CuO@IL), and this self-supported catalyst can reach 10 mA cm−2 at only 1.33 V vs RHE and achieved HMF conversion of 98.5 %, FDCA yield of 97.1 % and Faraday efficiency of 92.2 %. The excellent catalytic performance of Ag-CuO@IL for HMFOR is attributed to the doped heteroatoms derived from ILs to promote electron redistribution and the generated oxygen vacancies induced by IL anions to highly disperse Ag. Also, the catalyst was the nanosheet-assembled spherical clusters with 3D nanostructure, which exposed a large number of active sites. Density functional theory calculations showed that Ag-CuO@IL possessed moderate adsorption strengths of HMF and OH–, thus facilitating the desorption of the products in the reaction process. The design that induced by ionic liquid dopant not only provides an effective and green mean for HMFOR, but also has the large potential to guide the synthesis of other catalysts with improved performances in various applications.    

    

** Uncovering the Synergy between Gold and Sodium on ZrO2 for Boosting the Reverse Water Gas Shift Reaction: In-Situ Spectroscopic Investigations   
:PROPERTIES:
:ID: https://openalex.org/W4390570953
:DOI: https://doi.org/10.1016/j.apcatb.2023.123685
:AUTHORS: Abdallah I.M. Rabee, Sebastián Cisneros, Dan Zhao, Carsten Kreyenschulte, Stephan Bartling, Vita A. Kondratenko, Christoph Kubis, Evgenii V. Kondratenko, Angelika Brückner, Jabor Rabeah
:HOST: Applied Catalysis B: Environmental
:END:

Abdallah I.M. Rabee, Sebastián Cisneros, Dan Zhao, Carsten Kreyenschulte, Stephan Bartling, Vita A. Kondratenko, Christoph Kubis, Evgenii V. Kondratenko, Angelika Brückner, Jabor Rabeah, Applied Catalysis B: Environmental. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2023.123685")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390570953"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390570953"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390570953"))][Get cited by]]

OpenAlex: https://openalex.org/W4390570953
    
Abdallah I.M. Rabee, Sebastián Cisneros, Dan Zhao, Carsten Kreyenschulte, Stephan Bartling, Vita A. Kondratenko, Christoph Kubis, Evgenii V. Kondratenko, Angelika Brückner, Jabor Rabeah, Applied Catalysis B: Environmental. https://doi.org/10.1016/j.apcatb.2023.123685
    
CO2 conversion to CO via the reverse water-gas shift (RWGS) reaction is a promising source of syngas for subsequent synthesis of liquid fuels and chemicals. Herein, we present the synthesis of catalysts containing Au supported on hydroxylated Na-modified ZrO2, with Au amounts ranging from 0.05 to 1 wt.%. Systematic investigations reveal the formation of cooperative Au/Na sites at the interface. These sites cooperate synergistically to activate CO2 and generate a high surface density of carboxylate-like species, which serve as highly active intermediates for CO formation. It was found that the RWGS reaction on the catalyst with low Au loading proceeds mainly via a carboxylate pathway, with bidentate formate acting as spectators. At higher Au loading, the bidentate formate pathway contributes somewhat to CO formation alongside the carboxylate pathway. Based on temporal analysis of products, we emphasize the significant roles of H2 spillover and the metal-support interface in the RWGS reaction.    

    

** The role of added oxidising agents in assisting the photocatalytic treatment of olive mill wastewater using a metal-free g-C3N4 optical semiconductor   
:PROPERTIES:
:ID: https://openalex.org/W4390629322
:DOI: https://doi.org/10.1016/j.jwpe.2023.104722
:AUTHORS: André Torres‐Pinto, Ana R. Fernandes, Cláudia G. Silva, Joaquim L. Faria, Adrián M.T. Silva
:HOST: Journal of Water Process Engineering
:END:

André Torres‐Pinto, Ana R. Fernandes, Cláudia G. Silva, Joaquim L. Faria, Adrián M.T. Silva, Journal of Water Process Engineering. 58(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jwpe.2023.104722")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390629322"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390629322"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390629322"))][Get cited by]]

OpenAlex: https://openalex.org/W4390629322
    
André Torres‐Pinto, Ana R. Fernandes, Cláudia G. Silva, Joaquim L. Faria, Adrián M.T. Silva, Journal of Water Process Engineering. https://doi.org/10.1016/j.jwpe.2023.104722
    
Olive mill wastewaters (OMW) consist of high organic contents and are harmful to aquatic and terrestrial biota. Heterogeneous photocatalysis is a technology that can be operated under mild conditions to remove pollutants in the liquid phase. In the present work, graphitic carbon nitride (g-C3N4, hereafter referred to as GCN) is studied for the first time as a metal-free photocatalyst for OMW treatment. The integration with peroxidation (H2O2), Fenton (Fe2+/H2O2 at both acidic and natural pH), chlorination (HOCl/ClO−) or persulfate (PS) activation is also investigated. This catalyst potentiated the activation of these oxidants, and H2O2 was identified as the best option to achieve high removals of total phenolic content – TPh (87.5 ± 0.3 %), dissolved organic carbon – DOC (63.8 ± 0.4 %) and chemical oxygen demand – COD (87.7 ± 0.6 %), without need to add iron or adjust the pH. The stability and reusability of the GCN material in the H2O2-assisted photocatalytic treatment of OMW give rise to new possibilities for treating these waste waters.    

    

** Solid-state <sup>13</sup>C-NMR spectroscopic determination of side-chain mobilities in zirconium-based metal–organic frameworks   
:PROPERTIES:
:ID: https://openalex.org/W4390612169
:DOI: https://doi.org/10.5194/mr-5-1-2024
:AUTHORS: Günter Hempel, Ricardo Kurz, Silvia Paasch, Kay Saalwächter, Eike Brunner
:HOST: Magnetic resonance
:END:

Günter Hempel, Ricardo Kurz, Silvia Paasch, Kay Saalwächter, Eike Brunner, Magnetic resonance. 5(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/mr-5-1-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390612169"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390612169"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390612169"))][Get cited by]]

OpenAlex: https://openalex.org/W4390612169
    
Günter Hempel, Ricardo Kurz, Silvia Paasch, Kay Saalwächter, Eike Brunner, Magnetic resonance. https://doi.org/10.5194/mr-5-1-2024
    
Abstract. Porous interpenetrated zirconium–organic frameworks (PIZOFs) are a class of Zr-based metal–organic frameworks (MOFs) which are composed of long, rod-like dicarboxylate linkers and Zr6O4(OH)4(O2C)12 nodes. Long oligoethylene glycol or aliphatic side chains are covalently attached to the linker molecules in the cases of PIZOF-10 and PIZOF-11, respectively. These side chains are supposedly highly mobile, thus mimicking a solvent environment. It is anticipated that such MOFs could be used as a solid catalyst – the MOF – with pore systems showing properties similar to a liquid reaction medium. To quantify the side-chain mobility, here we have applied different 1D and 2D NMR solid-state spectroscopic techniques like cross-polarization (CP) and dipolar-coupling chemical-shift correlation (DIPSHIFT) studies. The rather high 1H-13C CP efficiency observed for the CH2 groups of the side chains indicates that the long side chains are unexpectedly immobile or at least that their motions are strongly anisotropic. More detailed information about the mobility of the side chains was then obtained from DIPSHIFT experiments. Analytical expressions for elaborate data analysis are derived. These expressions are used to correlate order parameters and to slow motional rates with signals in indirect spectral dimensions, thus enabling the quantification of order parameters for the CH2 groups. The ends of the chains are rather mobile, whereas the carbon atoms close to the linker are more spatially restricted in mobility.    

    
