#+TITLE: liquid-metal
Description: low temperature liquid metals
Created on Sat Jan 25 01:15:30 2025

Found 1 results from 2025-01-18 to 2025-01-25
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3A%22liquid%20metal%22%20AND%20%28catalyst%20OR%20catalysis%29]]

* Molten Sn solvent expands liquid metal catalysis  :liquid_metal:
:PROPERTIES:
:UUID: https://openalex.org/W4406657236
:TOPICS: Catalysis and Hydrodesulfurization Studies, Catalytic Processes in Materials Science, Nanomaterials for catalytic reactions
:PUBLICATION_DATE: 2025-01-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-025-56222-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4406657236"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4406657236"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4406657236"))][Get cited by]]

OpenAlex: https://openalex.org/W4406657236 (Open access: True)
    
[[https://openalex.org/A5010938304][Junma Tang]], [[https://openalex.org/A5050500604][Nastaran Meftahi]], [[https://openalex.org/A5073206123][Andrew J. Christofferson]], [[https://openalex.org/A5107791204][Jing Sun]], [[https://openalex.org/A5033344805][Ruohan Yu]], [[https://openalex.org/A5019983208][Md. Arifur Rahim]], [[https://openalex.org/A5087654837][Jianbo Tang]], [[https://openalex.org/A5018814864][Guangzhao Mao]], [[https://openalex.org/A5091422934][Torben Daeneke]], [[https://openalex.org/A5053257237][Richard B. Kaner]], [[https://openalex.org/A5031877516][Salvy P. Russo]], [[https://openalex.org/A5067220816][Kourosh Kalantar‐zadeh]], Nature Communications. 16(1)] 2025. https://doi.org/10.1038/s41467-025-56222-0 
     
Abstract Regulating favorable assemblies of metallic atoms in the liquid state provides promise for catalyzing various chemical reactions. Expanding the selection of metallic solvents, especially those with unique properties and low cost, enables access to distinctive fluidic atomic structures on the surface of liquid alloys and offers economic feasibility. Here, Sn solvent, as a low-cost commodity, supports unique atomic assemblies at the interface of molten SnIn 0.1034 Cu 0.0094 , which are highly selective for H 2 synthesis from hydrocarbons. Atomistic simulations reveal that distinctive adsorption patterns with hexadecane can be established with Cu transiently reaching the interfacial layer, ensuring an energy-favorable route for H 2 generation. Experiments with a natural oil as feedstock underscore this approach’s performance, producing 1.2 × 10 − 4 mol/min of H 2 with 5.0 g of catalyst at ~93.0% selectivity while offering reliable scalability and durability at 260 °C. This work presents an alternative avenue of tuning fluidic atomic structures, broadening the applications of liquid metals.    

    
