#+TITLE: water splitting
Description: water splitting papers
Created on Mon Sep 23 01:19:50 2024

Found 19 results from 2024-09-16 to 2024-09-23
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Manipulating the Electronic Properties of an Fe Single Atom Catalyst via Secondary Coordination Sphere Engineering to Provide Enhanced Oxygen Electrocatalytic Activity in Zinc-Air Batteries.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402555445
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202410121")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402555445"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402555445"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402555445"))][Get cited by]]

OpenAlex: https://openalex.org/W4402555445 (Open access: False)
    
[[https://openalex.org/A5069816022][Siqi Ji]], [[https://openalex.org/A5107263290][Yimin Mou]], [[https://openalex.org/A5101670166][Hongxue Liu]], [[https://openalex.org/A5100303175][Xue Lu]], [[https://openalex.org/A5101742243][Qian Zhang]], [[https://openalex.org/A5101335497][Chunmin Guo]], [[https://openalex.org/A5058842255][Kai Sun]], [[https://openalex.org/A5100407428][Dong Liu]], [[https://openalex.org/A5033912521][J. Hugh Horton]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5100445356][Yu Wang]], [[https://openalex.org/A5100450029][Zhijun Li]], PubMed. None(None)] 2024. https://doi.org/10.1002/adma.202410121 
     
Oxygen reduction and evolution reactions are two key processes in electrochemical energy conversion technologies. Synthesis of nonprecious metal, carbon-based electrocatalysts with high oxygen bifunctional activity and stability is a crucial, yet challenging step to achieving electrochemical energy conversion. Here, an approach to address this issue: synthesis of an atomically dispersed Fe electrocatalyst (Fe    

    

* Artificial Photosynthetic Cell with Molecular Biomimetic Thylakoid  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402556634
:TOPICS: Electrocatalysis for Energy Conversion, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Molecular Mechanisms of Photosynthesis and Photoprotection
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202416289")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402556634"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402556634"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402556634"))][Get cited by]]

OpenAlex: https://openalex.org/W4402556634 (Open access: False)
    
[[https://openalex.org/A5103105065][Enbo Zhou]], [[https://openalex.org/A5100659472][Shi‐Chen Yan]], [[https://openalex.org/A5065018590][Xiang Zhang]], [[https://openalex.org/A5107263595][Baloch Ur Rehman Ateeq]], [[https://openalex.org/A5102267990][Yangdan Hui]], [[https://openalex.org/A5024516004][F.S. Wang]], [[https://openalex.org/A5051342874][Lei Jiao]], [[https://openalex.org/A5066696182][Jiafang Xie]], [[https://openalex.org/A5016682254][Daqiang Yuan]], [[https://openalex.org/A5100322864][Li Wang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202416289 
     
The construction of solar‐to‐chemical conversion system by mimicking the photosynthetic network of the chloroplast holds great promise on efficient solar energy utilization. We developed an artificial photosynthetic cell (APC) based on molecular biomimetic thylakoid (CoTPP‐FePy) to split water into hydrogen and oxygen (H2 and O2) at low driving voltage (1.1 V) and neutral condition (pH≈7). The CoTPP‐FePy can emulate the light reaction in thylakoids to produce O2 by coupling light harvesting, photocatalysis, and electron/energy storage (FeIII/FeII‐Py). Subsequently, a membrane electrode assembly (MEA) were employed to simulate the dark reaction, wherein the proton, electron and energy generated by the light reaction can drive the H2 producing process. By a temporally and spatially coupling of the light and dark reactions, the resulting APC achieved a solar conversion efficiency of 3.1%, exceeding that of natural photosynthetic systems and demonstrating the potential of artificial photosynthesis.    

    

* Co3O4 nanoparticles synthesized with rotten-grape extract for use in supercapacitors and oxygen evolution devices  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402560066
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.rineng.2024.102922")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402560066"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402560066"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402560066"))][Get cited by]]

OpenAlex: https://openalex.org/W4402560066 (Open access: False)
    
[[https://openalex.org/A5009596475][Asma Hayat]], [[https://openalex.org/A5072179381][Aneela Tahira]], [[https://openalex.org/A5057422780][Muhammad Ali Bhatti]], [[https://openalex.org/A5104094070][Irum Naz]], [[https://openalex.org/A5003076482][Aqeel Ahmed Shah]], [[https://openalex.org/A5073645764][Elmuez A. Dawi]], [[https://openalex.org/A5051512789][Matteo Tonezzer]], [[https://openalex.org/A5034242852][Ayman Nafady]], [[https://openalex.org/A5058142632][Riyadh H. Alshammari]], [[https://openalex.org/A5041247040][Zafar Hussain Ibupoto]], Results in Engineering. 24(None)] 2024. https://doi.org/10.1016/j.rineng.2024.102922 
     
No abstract    

    

* Plasma-engineering of Pt-decorated NiCo2O4 nanowires with rich oxygen vacancies for enhanced oxygen electrocatalysis and zinc-air battery performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402565710
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124607")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402565710"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402565710"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402565710"))][Get cited by]]

OpenAlex: https://openalex.org/W4402565710 (Open access: False)
    
[[https://openalex.org/A5002622705][He Li]], [[https://openalex.org/A5001039797][Luka Hansen]], [[https://openalex.org/A5041745713][Ainura Aliyeva]], [[https://openalex.org/A5101834120][Jihao Wang]], [[https://openalex.org/A5055397040][Haoyi Qiu]], [[https://openalex.org/A5078351395][Martin Müller]], [[https://openalex.org/A5022896242][Shilong Chen]], [[https://openalex.org/A5010210138][Cenk Aktas]], [[https://openalex.org/A5041200678][Lorenz Kienle]], [[https://openalex.org/A5091657793][Bernd Hartke]], [[https://openalex.org/A5069362918][Jan Benedikt]], Applied Catalysis B Environment and Energy. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124607 
     
No abstract    

    

* Green Hydrogen Production by Low‐Temperature Membrane‐Engineered Water Electrolyzers, and Regenerative Fuel Cells  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402567352
:TOPICS: Hydrogen Energy Systems and Technologies, Electrocatalysis for Energy Conversion, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smtd.202400574")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402567352"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402567352"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402567352"))][Get cited by]]

OpenAlex: https://openalex.org/W4402567352 (Open access: True)
    
[[https://openalex.org/A5107266695][Alexandre Bodard]], [[https://openalex.org/A5023209242][Zhangsen Chen]], [[https://openalex.org/A5107266696][Oumayma ELJarray]], [[https://openalex.org/A5023395031][Gaixia Zhang]], Small Methods. None(None)] 2024. https://doi.org/10.1002/smtd.202400574 
     
Abstract Green hydrogen (H 2 ) is an essential component of global plans to reduce carbon emissions from hard‐to‐abate industries and heavy transport. However, challenges remain in the highly efficient H 2 production from water electrolysis powered by renewable energies. The sluggish oxygen evolution restrains the H 2 production from water splitting. Rational electrocatalyst designs for highly efficient H 2 production and oxygen evolution are pivotal for water electrolysis. With the development of high‐performance electrolyzers, the scale‐up of H 2 production to an industrial‐level related activity can be achieved. This review summarizes recent advances in water electrolysis such as the proton exchange membrane water electrolyzer (PEMWE) and anion exchange membrane water electrolyzer (AEMWE). The critical challenges for PEMWE and AEMWE are the high cost of noble‐metal catalysts and their durability, respectively. This review highlights the anode and cathode designs for improving the catalytic performance of electrocatalysts, the electrolyte and membrane engineering for membrane electrode assembly (MEA) optimizations, and stack systems for the most promising electrolyzers in water electrolysis. Besides, the advantages of integrating water electrolyzers, fuel cells (FC), and regenerative fuel cells (RFC) into the hydrogen ecosystem are introduced. Finally, the perspective of electrolyzer designs with superior performance is presented.    

    

* Fluorine‐lodged high‐valent high‐entropy layered double hydroxide for efficient, long‐lasting zinc‐air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402568141
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202410978")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402568141"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402568141"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402568141"))][Get cited by]]

OpenAlex: https://openalex.org/W4402568141 (Open access: False)
    
[[https://openalex.org/A5085664488][Zonglong Zhu]], [[https://openalex.org/A5085082108][Jing Zhong]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5045848015][Jialun Gu]], [[https://openalex.org/A5087109862][Fucong Lyu]], [[https://openalex.org/A5103105803][Shengmei Chen]], [[https://openalex.org/A5079505820][Haikun Wu]], [[https://openalex.org/A5060676955][Lanxi Li]], [[https://openalex.org/A5102942706][Chunyi Zhi]], [[https://openalex.org/A5100341536][Jian Lü]], [[https://openalex.org/A5032400855][Yang Yang Li]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202410978 
     
Efficient and stable bifunctional oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) catalysts are urgently needed to unlock the full potential of zinc‐air batteries (ZABs). High‐valence oxides (HVOs) and high entropy oxides (HEOs) are suitable candidates for their optimal electronic structures and stability but suffer from demanding synthesis. Here, a low‐cost fluorine‐lodged high‐valent high‐entropy layered double hydroxide (HV‐HE‐LDH) (FeCoNi2F4(OH)4) is conveniently prepared through multi‐ions co‐precipitation, where F‐ are firmly embedded into the individual hydroxide layers. Spectroscopic detections and theoretical simulations reveal high valent metal cations are obtained in FeCoNi2F4(OH)4, which enlarge the energy band overlap between metal 3d and O 2p, enhancing the electronic conductivity and charge transfer, thus affording high intrinsic OER catalytic activity. More importantly, the strengthened metal‐oxygen (M‐O) bonds and stable octahedral geometry (M‐O(F)6) in FeCoNi2F4(OH)4 prevent structural reorganization, rendering long‐term catalytic stability. Furthermore, an efficient three‐phase reaction interface with fast oxygen transportation was constructed, significantly improving the ORR activity. ZABs assembled with FeCoNi2F4(OH)4@HCC (hydrophobic carbon cloth) cathodes deliver a top performance with high round‐trip energy efficiency (60.6% at 10 mA cm‐2) and long‐term stability (efficiency remains at 58.8% after 1050 charge‐discharge cycles).    

    

* Trifunctional Graphene‐Sandwiched Heterojunction‐Embedded Layered Lattice Electrocatalyst for High Performance in Zn‐Air Battery‐Driven Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402568155
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/advs.202408869")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402568155"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402568155"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402568155"))][Get cited by]]

OpenAlex: https://openalex.org/W4402568155 (Open access: True)
    
[[https://openalex.org/A5100691394][Dong‐Won Kim]], [[https://openalex.org/A5106821467][Jihoon Kim]], [[https://openalex.org/A5049261439][Jong Hui Choi]], [[https://openalex.org/A5002504130][Do Hwan Jung]], [[https://openalex.org/A5042923657][Jeung Ku Kang]], Advanced Science. None(None)] 2024. https://doi.org/10.1002/advs.202408869 
     
Abstract Zn‐air battery (ZAB)‐driven water splitting holds great promise as a next‐generation energy conversion technology, but its large overpotential, low activity, and poor stability for oxygen reduction reaction (ORR), oxygen evolution reaction (OER), and hydrogen evolution reaction (HER) remain obstacles. Here, a trifunctional graphene‐sandwiched, heterojunction‐embedded layered lattice (G‐SHELL) electrocatalyst offering a solution to these challenges are reported. Its hollow core‐layered shell morphology promotes ion transport to Co 3 S 4 for OER and graphene‐sandwiched MoS 2 for ORR/HER, while its heterojunction‐induced internal electric fields facilitate electron migration. The structural characteristics of G‐SHELL are thoroughly investigated using X‐ray absorption spectroscopy. Additionally, atomic‐resolution transmission electron microscopy (TEM) images align well with the DFT‐relaxed structures and simulated TEM images, further confirming its structure. It exhibits an approximately threefold smaller ORR charge transfer resistance than Pt/C, a lower OER overpotential and Tafel slope than RuO₂, and excellent HER overpotential and Tafel slope, while outlasting noble metals in terms of durability. Ex situ X‐ray photoelectron spectroscopy analysis under varying potentials by examining the peak shifts and ratios (Co 2+ /Co 3+ and Mo 4+ /Mo 6+ ) elucidates electrocatalytic reaction mechanisms. Furthermore, the ZAB with G‐SHELL outperforms Pt/C+RuO 2 in terms of energy density (797 Wh kg −1 ) and peak power density (275.8 mW cm −2 ), realizing the ZAB‐driven water splitting.    

    

* Integrating Multiple Strategies Using Biotechnology to Design High‐Performance Electrocatalysts for Hydrogen and Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402568366
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202413072")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402568366"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402568366"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402568366"))][Get cited by]]

OpenAlex: https://openalex.org/W4402568366 (Open access: False)
    
[[https://openalex.org/A5100539584][Lin Ge]], [[https://openalex.org/A5051852456][Chang Liu]], [[https://openalex.org/A5065081112][Tingting Xue]], [[https://openalex.org/A5051684600][Yiyang Kang]], [[https://openalex.org/A5101515037][Yining Sun]], [[https://openalex.org/A5100764261][Yuxi Chen]], [[https://openalex.org/A5100657940][Jiajie Wu]], [[https://openalex.org/A5064869186][Kai Wen Teng]], [[https://openalex.org/A5100440390][Lei Li]], [[https://openalex.org/A5050763027][Qing Qu]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202413072 
     
Abstract Combining multiple design strategies often enhances catalyst performance but usually comes with high costs and low reproducibility. A technique that enhances catalyst performance in multiple strategies is urgently needed. Herein, a novel bioregulation technique is introduced, allowing simultaneous control over morphology, particle size, doping, interface engineering, and electronic properties. Bioregulation technique utilizes the soluble extracellular polymer from Aspergillus niger as a templating agent to construct high‐performance catalysts for hydrogen and oxygen evolution reaction (HER and OER). This technique controls catalyst morphology, introduces biological N and S doping, and regulates the electronic structure of the catalyst surface. Biomolecule modification enhances surface hydrophilicity, and the nanostructure increases surface roughness and gas‐release efficiency. Theoretical calculations show that the bioregulation technique shortens the d/p‐band center, optimizing reaction intermediate adsorption and desorption. The Bio‐Pt/Co 3 O 4 catalyst with trace Pt on the surface, designed with these strategies, achieves HER ( η 10 of 42 mV), OER ( η 10 of 221 mV), and overall water‐splitting performance (1.51 V at 10 mA cm −2 ), maintaining stability for over 50 h, outperforming most Pt‐based catalysts. Notably, using spent lithium‐ion battery cathodes leachate, rich in Co 2 ⁺, successfully replicates the experiment. This approach holds promise as a mainstream method for synthesizing high‐performance materials in the future.    

    

* Modulation of catalytic activity of BSCF towards electrochemical oxygen reactions using different synthetic approaches  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402568572
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.09.138")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402568572"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402568572"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402568572"))][Get cited by]]

OpenAlex: https://openalex.org/W4402568572 (Open access: False)
    
[[https://openalex.org/A5045576247][Sachin Bhagat]], [[https://openalex.org/A5085652067][Nandita Singh]], [[https://openalex.org/A5101707351][Monika Singh]], [[https://openalex.org/A5035021700][Ashish Kumar Singh]], [[https://openalex.org/A5075153838][Suryabhan Singh]], [[https://openalex.org/A5049948393][Uday Pratap Azad]], [[https://openalex.org/A5044615009][Akhilesh Kumar Singh]], International Journal of Hydrogen Energy. 88(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.09.138 
     
No abstract    

    

* Fe-modulated NiFex Co Layered Double Hydroxide on Ni Foam for Efficient Oxygen Precipitation Reaction in Alkaline Water Electrolysis for Hydrogen Production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402570146
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Carbon Dioxide Hydrogenation, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-07-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.23919/ccc63176.2024.10661943")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402570146"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402570146"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402570146"))][Get cited by]]

OpenAlex: https://openalex.org/W4402570146 (Open access: False)
    
[[https://openalex.org/A5104049478][Jialin Dong]], [[https://openalex.org/A5018962276][Shihong Yue]], No host. None(None)] 2024. https://doi.org/10.23919/ccc63176.2024.10661943 
     
No abstract    

    

* Electrospun Mn1-xCoxFe2O4 (x=0-0.7) Nanofibers for Supercapacitors and Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402549944
:TOPICS: Materials for Electrochemical Supercapacitors, Lithium-ion Battery Technology, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matchemphys.2024.129948")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402549944"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402549944"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402549944"))][Get cited by]]

OpenAlex: https://openalex.org/W4402549944 (Open access: False)
    
[[https://openalex.org/A5093713392][Zahra Ansari Jokandan]], [[https://openalex.org/A5085759711][J. Mazloom]], [[https://openalex.org/A5014599906][Morteza Safari]], Materials Chemistry and Physics. None(None)] 2024. https://doi.org/10.1016/j.matchemphys.2024.129948 
     
No abstract    

    

* Fe, Cu bimetallic precursor-driven quaternary active sites boost oxygen reduction / evolution reaction bifunctional catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402550124
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235423")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402550124"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402550124"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402550124"))][Get cited by]]

OpenAlex: https://openalex.org/W4402550124 (Open access: False)
    
[[https://openalex.org/A5101383673][Yurong Yuan]], [[https://openalex.org/A5026379076][Mengwei Pan]], [[https://openalex.org/A5101509462][Mengjie Zhang]], [[https://openalex.org/A5075343261][Yuchen Zhou]], [[https://openalex.org/A5042495813][Qin Fei-long]], [[https://openalex.org/A5074161773][Yaoyu Yang]], [[https://openalex.org/A5002739525][Rui Hao]], [[https://openalex.org/A5102784975][Weifang Liu]], [[https://openalex.org/A5034594327][Kaiyu Liu]], Journal of Power Sources. 623(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235423 
     
No abstract    

    

* Recommended practice for measurement and evaluation of oxygen evolution reaction electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402567939
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/eom2.12486")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402567939"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402567939"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402567939"))][Get cited by]]

OpenAlex: https://openalex.org/W4402567939 (Open access: True)
    
[[https://openalex.org/A5072641790][Hongyu An]], [[https://openalex.org/A5021708784][Wanki Park]], [[https://openalex.org/A5077614940][Heejong Shin]], [[https://openalex.org/A5055851063][Dong Young Chung]], EcoMat. None(None)] 2024. https://doi.org/10.1002/eom2.12486 
     
Abstract The Oxygen evolution reaction (OER) is a pivotal technology driving next‐generation sustainable energy conversion and storage devices. Establishing a robust analytical methodology is paramount to fostering innovation in this field. This review offers a comprehensive discussion on measurement and interpretation, advocating for standardized protocols and best practices to mitigate the myriad factors that complicate analysis. The initial focus is directed toward substrate electrodes and gas bubbles, both significant contributors to reduced reliability and reproducibility. Subsequently, the review focuses on intrinsic activity assessment, identification of electrochemical active sites, and the disentanglement of competing process contributions. These careful methodologies ensure the systematic delivery of insights crucial for assessing OER performance. In conclusion, the review highlights the critical role played by precise measurement techniques and unbiased activity comparison methodologies in propelling advancements in OER catalyst development. image    

    

* Ligand-tuning of coordination compound for improved oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402565094
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cjche.2024.07.023")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402565094"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402565094"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402565094"))][Get cited by]]

OpenAlex: https://openalex.org/W4402565094 (Open access: False)
    
[[https://openalex.org/A5074866068][Kai Yang]], [[https://openalex.org/A5100624279][Yuanjun Liu]], [[https://openalex.org/A5084900296][Yuyu Liu]], [[https://openalex.org/A5037822353][Xingmei Guo]], [[https://openalex.org/A5102953258][Xiangjun Zheng]], [[https://openalex.org/A5100664142][Junhao Zhang]], [[https://openalex.org/A5087023195][Guoxing Zhu]], Chinese Journal of Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.cjche.2024.07.023 
     
No abstract    

    

* Mo-Induced Surface Reconstruction in Ni/Co-OOH Prickly Flower Clusters for Improving the Hydrogen Production in Alkaline Seawater Splitting.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402554797
:TOPICS: Catalytic Nanomaterials, Desulfurization Technologies for Fuels, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202404858")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402554797"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402554797"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402554797"))][Get cited by]]

OpenAlex: https://openalex.org/W4402554797 (Open access: False)
    
[[https://openalex.org/A5100444342][Wen Zhang]], [[https://openalex.org/A5036318925][Jianyang Gao]], [[https://openalex.org/A5005485664][Qixing Gong]], [[https://openalex.org/A5100708318][Fusheng Liu]], [[https://openalex.org/A5100354843][Yang Zhang]], [[https://openalex.org/A5060955767][Guangrui Xu]], [[https://openalex.org/A5048731817][Zexing Wu]], [[https://openalex.org/A5058772567][Lei Wang]], PubMed. None(None)] 2024. https://doi.org/10.1002/smll.202404858 
     
Seawater electrolysis is the most promising technology for hydrogen production, in which surface reconstruction on the interface of electrode/electrolyte plays a crucial role in activating the catalytic reactions with a low activation energy barrier. Herein, an efficient Mo modifying NiCoMo prickly flower clusters electrocatalyst supported on nickel foam (Mo-doped Ni/Co-OOH prickly flower clusters) is obtained, which serves as an eminently active and durable catalyst for both hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) due to the surface reconstruction during the alkaline seawater electrolysis with ultralow overpotentials. It just requires a cell voltage of 1.52 V to achieve the current density of 10 mA cm    

    

* New Nanostructure NiO–GeSe Core–Shell/MAPbBr3 Solar Cell in Solar Photoelectrochemical Water Splitting: Superior Efficiency Enhancement  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402574927
:TOPICS: Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1155/2024/9454136")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402574927"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402574927"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402574927"))][Get cited by]]

OpenAlex: https://openalex.org/W4402574927 (Open access: True)
    
[[https://openalex.org/A5094218383][Maryam Shahrostami]], [[https://openalex.org/A5021811079][Mehdi Eskandari]], [[https://openalex.org/A5040960527][Davood Fathi]], International Journal of Energy Research. 2024(1)] 2024. https://doi.org/10.1155/2024/9454136 
     
Solar‐driven photoelectrochemical (PEC) water‐splitting cells coupled with a photovoltaic (PV) cell as a photoanode have become an intriguing topic in solar energy conversion. In this study, for the purpose of developing a system with high efficiency, several photoanode materials were investigated to adjust the oxygen evolution reaction and the hydrogen evolution reaction (HER) energy bands. Among all, MAPbBr 3 with a wide bandgap (2.3 eV) was selected. However, the power conversion efficiency of the PV cell was not desirable due to the low light absorption. Therefore, the NiO–GeSe core–shell was placed inside the perovskite layer to enhance light absorption and carrier generation. In order to achieve a cell with the maximum performance, the core–shell height, and the shell radius were optimized, where the optimum structure was recognized with a core–shell height of 300 nm and a radius of 25–60 nm. The system’s total efficiency, which is represented by the solar to hydrogen efficiency, was then increased from 5.49% to 19.74% for the planar and nanostructure photoanode, respectively. The proposed PEC cell with the optimized photoanode is considered as the most efficient half‐tandem and perovskite‐based reported coupled system, operating without the need for an external voltage. In this study, three optical, electrical, and electrochemical models were solved using the finite element method to analyze the coupled system.    

    

* A perspective to efficient synthesis of zirconium carbide via novel pyro-vacuum method: lower temperatures and enhanced purity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402559567
:TOPICS: Synthesis and Properties of Cemented Carbides, Ceramic Materials and Processing, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.53063/synsint.2024.43233")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402559567"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402559567"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402559567"))][Get cited by]]

OpenAlex: https://openalex.org/W4402559567 (Open access: False)
    
[[https://openalex.org/A5005505945][Faramarz Kazemi]], [[https://openalex.org/A5005077956][Behzad Nayebi]], Synthesis and Sintering. 4(3)] 2024. https://doi.org/10.53063/synsint.2024.43233 
     
The use of ultra-high temperature ceramics (UHTCs) as a novel additive in the refractory industry is becoming increasingly popular. However, the synthesis of such materials is associated with some commercial obstacles, mainly high-temperature synthesis methods. In the present study, the pyro-vacuum method is presented as a new method to decrease the final product's synthesis temperature and oxygen content. Some thermodynamic aspects and phase evolution of the materials during the synthesis procedure are described for the synthesis of non-oxide material. Conclusively, it seems that by applying vacuum conditions, the final UHTC phases can be synthesized at significantly lower temperatures (>400 °C lower, for ZrC), if adequate powder mixtures are considered. Also due to phase analysis, it was found that the oxygen content of the final phase is lower than the conventional routes and other references. The process provides promising prospects for the economic synthesis of UHTCs.    

    

* 2D TiNBr as photocatalyst for overall water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402583716
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-09-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-vxdq4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402583716"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402583716"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402583716"))][Get cited by]]

OpenAlex: https://openalex.org/W4402583716 (Open access: False)
    
[[https://openalex.org/A5060550190][Yatong Wang]], [[https://openalex.org/A5047589722][Geert Brocks]], [[https://openalex.org/A5047674683][Ceren Tayran]], [[https://openalex.org/A5073500004][Süleyman Er]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-vxdq4 
     
Two-dimensional (2D) Janus materials gain increasing attention as water splitting photocatalysts for hydrogen production. We use first-principles calculations to predict a stable 2D Janus $T$-TiNBr structure, with strong near-ultraviolet sunlight absorption and band edges that align favorably with the water redox potentials for oxygen and hydrogen evolution. We show that the optical and electronic properties of $T$-TiNBr can be modulated to a certain extend by applying external uniaxial strain. Explicit calculations of the redox reactions reveal that solar-driven water splitting is viable at the N-side of $T$-TiNBr, while the Br-side requires modifications such as vacancy creation, the application of an external potential, or adjustment of the pH conditions.    

    

* Treatment of domestic wastewater and extracellular polymeric substance accumulation in siphon‐type composite vertical subsurface flow constructed wetland  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402570326
:TOPICS: Application of Constructed Wetlands for Wastewater Treatment, Microbial Nitrogen Cycling in Wastewater Treatment Systems, Advancements in Water Purification Technologies
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/wer.11132")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402570326"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402570326"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402570326"))][Get cited by]]

OpenAlex: https://openalex.org/W4402570326 (Open access: False)
    
[[https://openalex.org/A5100353673][Hao Chen]], [[https://openalex.org/A5085485915][Lin Qiu]], [[https://openalex.org/A5046179350][Hong Wu]], [[https://openalex.org/A5102542811][Fahui Nie]], [[https://openalex.org/A5101455992][Yong Liu]], [[https://openalex.org/A5103208347][Wenping Cao]], Water Environment Research. 96(9)] 2024. https://doi.org/10.1002/wer.11132 
     
Abstract In this study, the siphon‐type composite vertical flow constructed wetland (Sc‐VSsFCW) was constructed with anthracite and shale ceramsite chosen as the substrate bed materials. During the 90‐day experiment, typical pollutant removal effects of wastewater and extracellular polymeric substance (EPS) accumulation were investigated. Meanwhile, X‐ray diffraction and scanning electron microscopy were used to examine the phase composition and surface morphology to analyze adsorptive property. Additionally, we evaluated the impact of siphon effluent on clogging and depolymerization by measuring the EPS components' evolution within the system. The findings reveal that both the anthracite and shale ceramsite systems exhibit impressive removal efficiencies for total phosphorus (TP), total dissolved phosphorus (TDP), soluble reactive phosphorus (SRP), chemical oxygen demand (COD), ammonium nitrogen (NH 4 + ‐N), and nitrate nitrogen (NO 3 − ‐N). However, as the experiment progressed, TP removal rates in both systems gradually declined because of the saturation of adsorption sites on the substrate surfaces. Although the dissolved oxygen (DO) levels remained relatively stable throughout the experiment, pH exhibited distinct patterns, suggesting that the anthracite system relies primarily on chemical adsorption, whereas the shale ceramsite system predominantly utilizes physical adsorption. After an initial period of fluctuation, the permeability coefficient and porosity of the system gradually stabilized, and the protein and polysaccharide contents in both systems exhibited a downward trend. The study underscores that anthracite and shale ceramsite have good effectiveness in pollutant removal as substrate materials. Overall, the hydraulic conditions of the double repeated oxygen coupling siphon in the Sc‐VSsFCW system contribute to enhanced re‐oxygenation capacity and permeability coefficient during operation. The changes in EPS content indicate that the siphon effluent exerts a certain depolymerization effect on the EPS within the system, thereby mitigating the risk of biological clogging to a certain extent. Practitioner Points The system can still maintain good pollutant treatment effect in long‐term operation. The re‐oxygenation method of the system can achieve efficient and long‐term re‐oxygenation effect. The siphon effluent has a certain improvement effect on the permeability coefficient and porosity, but it cannot effectively inhibit the occurrence of clogging. The EPS content did not change significantly during the operation of the system, and there was a risk of biological clogging.    

    
