#+TITLE: water splitting
Description: water splitting papers
Created on Sun Jul 14 01:16:07 2024

Found 73 results from 2024-07-07 to 2024-07-14
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Two infrequent organic hybrid transition metal hexa-sulfide electro-catalysts for the efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400380785
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ica.2024.122231")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400380785"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400380785"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400380785"))][Get cited by]]

OpenAlex: https://openalex.org/W4400380785 (Open access: False)
    
[[https://openalex.org/A5019098369][Xuhong Guo]], [[https://openalex.org/A5078829053][Hua Yuan]], [[https://openalex.org/A5016273426][Xing Liu]], [[https://openalex.org/A5088502431][Jian Zhou]], Inorganica chimica acta/Inorganica Chimica Acta. 571(None)] 2024. https://doi.org/10.1016/j.ica.2024.122231 
     
No abstract    

    

* Facet-engineered ruthenium oxide on titanium oxide oxygen evolution electrocatalysts for proton-exchange membrane water electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400381918
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124382")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400381918"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400381918"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400381918"))][Get cited by]]

OpenAlex: https://openalex.org/W4400381918 (Open access: False)
    
[[https://openalex.org/A5060324897][Hyung‐Koo Yoon]], [[https://openalex.org/A5057076775][Hee Jo Song]], [[https://openalex.org/A5092921649][Ji Seong Hyoung]], [[https://openalex.org/A5072213339][Sang Won Jung]], [[https://openalex.org/A5050014999][Andi Haryanto]], [[https://openalex.org/A5004886231][Chan Woo Lee]], [[https://openalex.org/A5016978421][Dong‐Wan Kim]], Applied catalysis. B, Environmental. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124382 
     
No abstract    

    

* Tailoring Mott−Schottky RuO2/MgFe‐LDH Heterojunctions in Electrospun Microfibers: A Bifunctional Electrocatalyst for Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400382717
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202403908")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400382717"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400382717"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400382717"))][Get cited by]]

OpenAlex: https://openalex.org/W4400382717 (Open access: False)
    
[[https://openalex.org/A5047379472][Sreenivasan Nagappan]], [[https://openalex.org/A5080916357][Rahul Jayan]], [[https://openalex.org/A5100033520][Nisarga Rajagopal]], [[https://openalex.org/A5100033521][Adithya V Krishnan]], [[https://openalex.org/A5046600331][Md Mahbubul Islam]], [[https://openalex.org/A5008192564][Subrata Kundu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202403908 
     
Abstract Hydrogen is a fuel of the future that has the potential to replace conventional fossil fuels in several applications. The quickest and most effective method of producing pure hydrogen with no carbon emissions is water electrolysis. Developing highly active electrocatalysts is crucial due to the slow kinetics of oxygen and hydrogen evolution, which limit the usage of precious metals in water splitting. Interfacial engineering of heterostructures has sparked widespread interest in improving charge transfer efficiency and optimizing adsorption/desorption energetics. The emergence of a built‐in‐electric field between RuO 2 and MgFe‐LDH improves the catalytic efficiency toward water splitting reaction. However, LDH‐based materials suffer from poor conductivity, necessitating the design of 1D materials by integration of RuO 2 / MgFe‐LDH to enhance catalytic properties through large surface areas and high electronic conductivity. Experimental results demonstrate lower overpotentials (273 and 122 mV at 10 mA cm −2 ) and remarkable stability (60 h) for the RuO 2 /MgFe‐LDH/Fiber heterostructure in OER (1 m KOH) and HER (0.5 m H 2 SO 4 ) reactions. Density functional theory (DFT) unveils a synergistic mechanism at the RuO 2 /MgFe‐LDH interface, leading to enhanced catalytic activity in OER and improved adsorption energy for hydrogen atoms, thereby facilitating HER catalysis.    

    

* Robust Covalent Organic Frameworks for Photosynthesis of H2O2: Advancements, Challenges and Strategies  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400382801
:TOPICS: Porous Crystalline Organic Frameworks for Energy and Separation Applications, Photocatalytic Materials for Solar Energy Conversion, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-07-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202404139")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400382801"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400382801"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400382801"))][Get cited by]]

OpenAlex: https://openalex.org/W4400382801 (Open access: False)
    
[[https://openalex.org/A5059032190][Jifu Hao]], [[https://openalex.org/A5044348175][Youhong Tang]], [[https://openalex.org/A5067714128][Jiafu Qu]], [[https://openalex.org/A5043648786][Yahui Cai]], [[https://openalex.org/A5013122091][Xiao-Gang Yang]], [[https://openalex.org/A5016334301][Jundie Hu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202404139 
     
Abstract Since 2020, covalent organic frameworks (COFs) are emerging as robust catalysts for the photosynthesis of hydrogen peroxide (H 2 O 2 ), benefiting from their distinct advantages. However, the current efficiency of H 2 O 2 production and solar‐to‐chemical energy conversion efficiency (SCC) remain suboptimal due to various constraints in the reaction mechanism. Therefore, there is an imperative to propose efficiency improvement strategies to accelerate the development of this reaction system. This comprehensive review delineates recent advances, challenges, and strategies in utilizing COFs for photocatalytic H 2 O 2 production. It explores the fundamentals and challenges (e.g., oxygen (O 2 ) mass transfer rate, O 2 adsorption capacity, response to sunlight, electron‐hole separation efficiency, charge transfer efficiency, selectivity, and H 2 O 2 desorption) associated with this process, as well as the advantages, applications, classification, and preparation strategies of COFs for this purpose. Various strategies to enhance the performance of COFs in H 2 O 2 production are highlighted. The review aims to stimulate further advancements in utilizing COFs for photocatalytic H 2 O 2 production and discusses potential prospects, challenges, and application areas in this field.    

    

* Improving the Oxygen Evolution Reaction Kinetics in Zn‐Air Battery by Iodide Oxidation Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400382870
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-07-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202402052")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400382870"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400382870"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400382870"))][Get cited by]]

OpenAlex: https://openalex.org/W4400382870 (Open access: False)
    
[[https://openalex.org/A5020514173][Jiaqi Ran]], [[https://openalex.org/A5101768281][Peng Chen]], [[https://openalex.org/A5012824791][Xiangning Quan]], [[https://openalex.org/A5041743338][Mingsu Si]], [[https://openalex.org/A5079481859][Daqiang Gao]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202402052 
     
Abstract Zinc‐air batteries (ZABs) have garnered considerable attention as a highly promising contender in the field of energy storage and conversion. Nevertheless, their performance is considerably impeded by the proliferation of dendrites on the Zinc anode and the slow kinetics of the redox reaction on the air cathode. Herein, taking Ag 30% @LaCoO 3 (Ag 30% @LCO) heterojunction catalyst as the cathode, it is demonstrated that adding KI additives to the alkaline electrolyte can not only enhance the oxygen electrocatalytic reaction but also inhibit the formation of zinc anode dendrites, thereby achieving a comprehensive improvement in the performance of ZABs. Under the action of the KI additive, the optimized Ag 30% @LCO catalyst shows a decreased overpotential from 460 to 220 mV at j = 10 mA cm −2 , while the assembled ZAB shows reduced charging potential (1.8 V), and long cycle stability (180 h). Furthermore, the morphology characterization results indicate a reduction in dendrites on the Zn anode. Both experimental and calculated results indicate that the presence of I − as a reaction modifier alters the trajectory of the conventional oxygen evolution reaction, resulting in a more thermodynamically favorable pathway. The introduction of KI additives as electrolytes provides a straightforward approach to developing comprehensively improved ZABs.    

    

* Effects of Ir‐Incorporation and Nanostructuring in β‐MnO2 for an Enhanced Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400390757
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400552")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400390757"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400390757"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400390757"))][Get cited by]]

OpenAlex: https://openalex.org/W4400390757 (Open access: False)
    
[[https://openalex.org/A5014253809][Uddipana Kakati]], [[https://openalex.org/A5086356869][Benjamin Roe]], [[https://openalex.org/A5053581353][Shashiprabha P. Dunuweera]], [[https://openalex.org/A5100038714][Jose F. Mendez-Guerra]], [[https://openalex.org/A5058988112][Daniel R. Strongin]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400552 
     
We investigated the electrocatalytic properties of Ir/β‐MnO2, with 4.2‐5.6 atomic % (at%) iridium. The Ir/β‐MnO2 was synthesized by heating Ir/R‐MnO2‐formed via a surfactant‐assisted (SA) method using KMnO4, IrCl3.H2O, and sodium dodecyl sulfate (SDS)‐to 400 oC. The Ir/β‐MnO2 (SA) was nano‐sized based on scanning and transmission electron microscopy (SEM and TEM). Using linear sweep voltammetry (LSV), 5.6 at% Ir/β‐MnO2 (SA) exhibited an overpotential ( of 327 ± 5 mV for the oxygen evolution reaction (OER), at 10 mA cm‐2 in 0.5 M H2SO4 electrolyte. At 10 mA cm‐2 , the Ir/β‐MnO2 (SA) catalyzed the OER for 72 h at an of 534 mV. During this time there was a 12 % loss in Mn and 8 % loss in Ir from the structure. An IrO2 catalyst exhibited an initial η of 420 ± 7 for the OER, but after 20 h of operation at 10 mA cm‐2 there was a steep rise in potential (>550 mV) and 12% loss in Ir. The enhanced activity and stability of Ir/β‐MnO2 (SA) is attributed to the incorporation of Ir into the MnO2 lattice during synthesis and the formation of nano‐sized particles using the SA method.    

    

* Mesoporous graphene-supported nanostructured nickel telluride for efficient electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400405078
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.132439")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400405078"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400405078"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400405078"))][Get cited by]]

OpenAlex: https://openalex.org/W4400405078 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5040396964][Jeongwon Park]], [[https://openalex.org/A5008400233][Hyun Jung]], Fuel. 374(None)] 2024. https://doi.org/10.1016/j.fuel.2024.132439 
     
No abstract    

    

* Surface reconstruction and entropy engineering of Ni(OH)2 nanosheets for enhanced electrocatalytic performances of oxygen evolution reaction in alkaline seawater  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400405981
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.132450")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400405981"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400405981"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400405981"))][Get cited by]]

OpenAlex: https://openalex.org/W4400405981 (Open access: False)
    
[[https://openalex.org/A5085261336][Bobo Wu]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5100434445][Yudong Zhang]], [[https://openalex.org/A5018193512][Peng Wang]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5064618955][Saifang Huang]], Fuel. 374(None)] 2024. https://doi.org/10.1016/j.fuel.2024.132450 
     
No abstract    

    

* In-Situ Transcribed Local Coordinations from Pre-Catalyst for Efficient Electrocatalytic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400406109
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4888866")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400406109"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400406109"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400406109"))][Get cited by]]

OpenAlex: https://openalex.org/W4400406109 (Open access: False)
    
[[https://openalex.org/A5041363328][Yuhao Zhang]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5041026723][Chenyu Yang]], [[https://openalex.org/A5016124646][Baojie Li]], [[https://openalex.org/A5038978426][Jianglong Guo]], [[https://openalex.org/A5011689834][Jingjing Jiang]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5067813768][Dongwei Ma]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4888866 
     
No abstract    

    

* Hydrothermal self-assembly of needle and sheet spherical array CuCo2O4 nanostructures on graphene aerogels for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400406204
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11581-024-05687-y")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400406204"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400406204"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400406204"))][Get cited by]]

OpenAlex: https://openalex.org/W4400406204 (Open access: False)
    
[[https://openalex.org/A5085719743][Qiujie Shou]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5082574333][Zaoxue Yan]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], Ionics. None(None)] 2024. https://doi.org/10.1007/s11581-024-05687-y 
     
No abstract    

    

* Oxygen‐Assisted Supercapacitive Swing Adsorption of Carbon Dioxide  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400408279
:TOPICS: Materials for Electrochemical Supercapacitors, Aqueous Zinc-Ion Battery Technology, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202404881")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400408279"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400408279"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400408279"))][Get cited by]]

OpenAlex: https://openalex.org/W4400408279 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5025998430][Bar Mosevitzky]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/anie.202404881 
     
We report on the supercapacitive swing adsorption (SSA) of carbon dioxide at different voltage windows in the presence of oxygen using activated carbon electrodes, and deliquescent, aqueous electrolytes. The presence of O2 in the CO2/N2 gas mixture results in an up to 11 times higher CO2 adsorption capacity with 3M MgBr2 (at 0.6V) and up to 4‐5 times higher adsorption capacity with 3M MgCl2 (at 1V). A tradeoff between high CO2 adsorption capacities and lower coulombic efficiencies was observed at voltages above 0.6V. The energetic and adsorptive performance of the electrodes in the presence of oxygen below 0.5V was similar to the performance with a CO2/N2 mixture without oxygen at 1V. Cyclic voltammetry (CV) and electrochemical impedance spectroscopy (EIS) of the electrodes demonstrate that the specific capacitance increases while the diffusion resistance decreases in the presence of oxygen. Oxygen concentrations ranging between 5‐20% give similar energetic and adsorptive performance. The electrodes exhibit stable performance for up to 100 cycles of operation.    

    

* Template-Assisted in situ synthesis of superaerophobic bimetallic MOF composites with tunable morphology for boosted oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400413493
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Zinc Oxide Nanostructures
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.07.063")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400413493"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400413493"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400413493"))][Get cited by]]

OpenAlex: https://openalex.org/W4400413493 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5071504062][Wenchao Peng]], [[https://openalex.org/A5071504062][Wenchao Peng]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], Journal of colloid and interface science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.07.063 
     
No abstract    

    

* Facile Synthesis of Oxygen-Doped g-C3N4 Mesoporous Nanosheets for Significant Enhancement of Photocatalytic Hydrogen Evolution Performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400417926
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-07-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ma17133345")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400417926"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400417926"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400417926"))][Get cited by]]

OpenAlex: https://openalex.org/W4400417926 (Open access: True)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], Materials. 17(13)] 2024. https://doi.org/10.3390/ma17133345 
     
In this work, oxygen-doped g-C3N4 mesoporous nanosheets (O-CNS) were synthesized via a facile recrystallization method with the assistance of H2O2. The crystal phase, chemical composition, morphological structure, optical property, electronic structure and electrochemical property of the prepared O-CNS samples were well investigated. The morphological observation combined with the nitrogen adsorption–desorption results demonstrated that the prepared O-CNS samples possessed nanosheet-like morphology with a porous structure. Doping O into g-C3N4 resulted in the augmentation of the specific surface area, which could provide more active sites for photocatalytic reactions. Simultaneously, the visible light absorption capacity of O-CNS samples was boosted owing to the regulation of O doping. The built energy level induced by the O doping could accelerate the migration rate of photoinduced carriers, and the porous structure was most likely to speed up the release of hydrogen during the photocatalytic hydrogen process. Resultantly, the photocatalytic hydrogen production rate of the optimized oxygen-doped g-C3N4 nanosheets reached up to 2012.9 μmol·h−1·g−1, which was 13.4 times higher than that of bulk g-C3N4. Thus, the significantly improved photocatalytic behavior was imputed to the synergistic effect of the porous structure, the increase in active sites, and the enhancement of visible light absorption and charge separation efficiency. Our research highlights that the synergistic effect caused by element doping will make a great contribution to the remarkable improvement in photocatalytic activity, providing a new inspiration for the construction of novel catalysts.    

    

* Electrosynthesis of Transition Metal Coordinated Polymers for Active and Stable Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400422640
:TOPICS: Conducting Polymer Research, Fuel Cell Membrane Technology, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202409628")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400422640"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400422640"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400422640"))][Get cited by]]

OpenAlex: https://openalex.org/W4400422640 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5039881332][Hongye Qin]], [[https://openalex.org/A5061176165][Jinhan Li]], [[https://openalex.org/A5036273689][Xijie Chen]], [[https://openalex.org/A5004425888][Kuiming Liu]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202409628 
     
Transition metal coordination polymers (TM‐CP) are promising inexpensive and flexible electrocatalysts for oxygen evolution reaction in water electrolysis, while their facile synthesis and controllable regulation remain challenging. Here we report an anodic oxidation‐electrodeposition strategy for the growth of TM‐CP (TM = Fe, Co, Ni, Cr, Mn; CP = polyaniline, polypyrrole) films on a variety of metal substrates that act as both catalyst supports and metal ion sources. An exemplified bimetallic NiFe‐polypyrrole (NiFe‐PPy) features superior mechanical stability in friction and exhibits high activity with long‐term durability in alkaline seawater (over 2000 h) and anion exchange membrane electrolyzer devices at current density of 500 mA cm−2. Spectroscopic and microscopic analysis unravels the configurations with atomically distributed metal sites induced by d‐π conjugation, which transforms into a mosaic structure with NiFe (oxy)hydroxides embedded in PPy matrix during oxygen evolution. The superior catalytic performance is ascribed to the anchoring effect of PPy that inhibits the metal dissolution, the strong substrate‐to‐catalyst interaction that ensures good adhesion, and the Fe/Ni−N coordination that modulates the electronic structures to facilitate the deprotonation of *OOH intermediate. This work provides a general strategy and mechanistic insight into building robust inorganic/polymer composite electrodes for oxygen electrocatalysis.    

    

* Electrosynthesis of Transition Metal Coordinated Polymers for Active and Stable Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400422778
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202409628")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400422778"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400422778"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400422778"))][Get cited by]]

OpenAlex: https://openalex.org/W4400422778 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5036273689][Xijie Chen]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5070614866][Tete Zhao]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5049506458][Fangyi Cheng]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/anie.202409628 
     
Transition metal coordination polymers (TM‐CP) are promising inexpensive and flexible electrocatalysts for oxygen evolution reaction in water electrolysis, while their facile synthesis and controllable regulation remain challenging. Here we report an anodic oxidation‐electrodeposition strategy for the growth of TM‐CP (TM = Fe, Co, Ni, Cr, Mn; CP = polyaniline, polypyrrole) films on a variety of metal substrates that act as both catalyst supports and metal ion sources. An exemplified bimetallic NiFe‐polypyrrole (NiFe‐PPy) features superior mechanical stability in friction and exhibits high activity with long‐term durability in alkaline seawater (over 2000 h) and anion exchange membrane electrolyzer devices at current density of 500 mA cm−2. Spectroscopic and microscopic analysis unravels the configurations with atomically distributed metal sites induced by d‐π conjugation, which transforms into a mosaic structure with NiFe (oxy)hydroxides embedded in PPy matrix during oxygen evolution. The superior catalytic performance is ascribed to the anchoring effect of PPy that inhibits the metal dissolution, the strong substrate‐to‐catalyst interaction that ensures good adhesion, and the Fe/Ni−N coordination that modulates the electronic structures to facilitate the deprotonation of *OOH intermediate. This work provides a general strategy and mechanistic insight into building robust inorganic/polymer composite electrodes for oxygen electrocatalysis.    

    

* Elevating Oxygen Evolution using Iron Phthalocyanine Infused Vanillic acid Electrocatalyst  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400425490
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202401759")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400425490"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400425490"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400425490"))][Get cited by]]

OpenAlex: https://openalex.org/W4400425490 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5050550166][Samuel Daniel]], [[https://openalex.org/A5069332807][Lokesh Koodlur Sannegowda]], Chemistry. None(None)] 2024. https://doi.org/10.1002/chem.202401759 
     
Oxygen evolution reaction (OER) is the bottle neck step in water splitting reaction towards the realization of hydrogen based clean energy production and storage. Transition metal based N4 organics are explored extensively as oxygen electrocatalysts i.e., (OER) and oxygen reduction reaction (ORR) catalysts because of their ease of synthesis, tuneable properties, low cost and high performance with long term stability. Here, vanillic acid functionalized iron phthalocyanine (FeVAPc) was synthesised and characterised. The novel FeVAPc exhibited good thermal stability and was coated on Ni foam for OER studies. The scanning electron microscopy images showed net‐work like surface morphology and the X‐ray photoelectron spectroscopy indicated the presence of Fe in +3 oxidation state. The Ni/FeVAPc demonstrated excellent electrocatalytic activity for OER with overpotential of 312 mV at 10 mA.cm‐2 current density in 1.0 M KOH . The designed catalyst exhibited lesser Tafel slope value which is nearer to the benchmark catalyst, IrO2. The proposed catalyst exhibited good stability as phthalocyanines are highly stable and do not undergo decomposition even in strong acidic and basic corrosive media. Integration of FeVAPc onto Ni foam resulted in higher mass activity, lower charge transfer resistance, high active surface area leading to enhanced conductivity and activity.    

    

* Metal-Organic Frameworks (MOFs) for Hybrid Water Electrolysis: Structure-Property-Performance Correlation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400425545
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Magnesium-Based Cements and Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cc02729a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400425545"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400425545"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400425545"))][Get cited by]]

OpenAlex: https://openalex.org/W4400425545 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], Chemical communications. None(None)] 2024. https://doi.org/10.1039/d4cc02729a 
     
Hybrid water electrolysis (HWE) emerges as a promising pathway for the simultaneous production of high-value chemicals and clean H2 fuel. Unlike conventional electrochemical water splitting, which relies on the oxygen...    

    

* Flexible tungsten disulfide superstructure engineering for efficient alkaline hydrogen evolution in anion exchange membrane water electrolysers  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400429700
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-50117-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400429700"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400429700"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400429700"))][Get cited by]]

OpenAlex: https://openalex.org/W4400429700 (Open access: True)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5038067619][Longlu Wang]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5009407423][Xixing Wen]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], Nature communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-50117-2 
     
Abstract Anion exchange membrane (AEM) water electrolysis employing non-precious metal electrocatalysts is a promising strategy for achieving sustainable hydrogen production. However, it still suffers from many challenges, including sluggish alkaline hydrogen evolution reaction (HER) kinetics, insufficient activity and limited lifetime of non-precious metal electrocatalysts for ampere-level-current-density alkaline HER. Here, we report an efficient alkaline HER strategy at industrial-level current density wherein a flexible WS 2 superstructure is designed to serve as the cathode catalyst for AEM water electrolysis. The superstructure features bond-free van der Waals interaction among the low Young’s modulus nanosheets to ensure excellent mechanical flexibility, as well as a stepped edge defect structure of nanosheets to realize high catalytic activity and a favorable reaction interface micro-environment. The unique flexible WS 2 superstructure can effectively withstand the impact of high-density gas-liquid exchanges and facilitate mass transfer, endowing excellent long-term durability under industrial-scale current density. An AEM electrolyser containing this catalyst at the cathode exhibits a cell voltage of 1.70 V to deliver a constant catalytic current density of 1 A cm −2 over 1000 h with a negligible decay rate of 9.67 μV h −1 .    

    

* Modulation of morphology and electronic structure of cobalt thiophenedicarboxylic coordination polymer via ligand exchange for high-performance oxygen evolution reaction and supercapacitor  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400439425
:TOPICS: Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Polyoxometalate Clusters and Materials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.07.071")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400439425"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400439425"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400439425"))][Get cited by]]

OpenAlex: https://openalex.org/W4400439425 (Open access: False)
    
[[https://openalex.org/A5051752937][Wenting Hong]], [[https://openalex.org/A5031350209][Shuai Wu]], [[https://openalex.org/A5015427745][Pei‐Hua Zhao]], [[https://openalex.org/A5100406891][Chao Wang]], [[https://openalex.org/A5057249628][Li Guo]], [[https://openalex.org/A5083531522][Yanzhong Wang]], Journal of colloid and interface science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.07.071 
     
No abstract    

    

* The excellent performance of oxygen evolution reaction on stainless steel electrodes by halogen oxyacid salts etching  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400439514
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.07.043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400439514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400439514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400439514"))][Get cited by]]

OpenAlex: https://openalex.org/W4400439514 (Open access: False)
    
[[https://openalex.org/A5002908773][Junyu Shen]], [[https://openalex.org/A5100295935][Tao Wang]], [[https://openalex.org/A5067471233][Tian Xie]], [[https://openalex.org/A5041421492][Ruihan Wang]], [[https://openalex.org/A5006848518][Dingwei Zhu]], [[https://openalex.org/A5100674049][Yuxi Li]], [[https://openalex.org/A5083820994][S. Xue]], [[https://openalex.org/A5086096402][Yazi Liu]], [[https://openalex.org/A5082615631][Hehua Zeng]], [[https://openalex.org/A5068250943][Wenhui Zhao]], [[https://openalex.org/A5100338047][Shaobin Wang]], Journal of colloid and interface science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.07.043 
     
No abstract    

    

* Novel FeNiP–FeNi–C nanofiber as an outstanding electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400445008
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.030")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400445008"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400445008"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400445008"))][Get cited by]]

OpenAlex: https://openalex.org/W4400445008 (Open access: False)
    
[[https://openalex.org/A5062744888][Hongrui Ma]], [[https://openalex.org/A5001666372][Xiuwen Wu]], [[https://openalex.org/A5032546811][Xiuli Fu]], [[https://openalex.org/A5044034302][Zhijian Peng]], International journal of hydrogen energy. 79(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.030 
     
No abstract    

    

* FeMnO3/CNT as a synergistic bifunctional electrocatalyst for oxygen reduction and oxygen evolution reactions in alkaline medium  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400450915
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matchemphys.2024.129695")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400450915"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400450915"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400450915"))][Get cited by]]

OpenAlex: https://openalex.org/W4400450915 (Open access: False)
    
[[https://openalex.org/A5041331458][Annet Anna Thomas]], [[https://openalex.org/A5003023242][Anook Nazer Eledath]], [[https://openalex.org/A5014212743][J.S. Niranjana]], [[https://openalex.org/A5081839502][Azhagumuthu Muthukrishnan]], [[https://openalex.org/A5068220834][M. Junaid Bushiri]], Materials chemistry and physics. None(None)] 2024. https://doi.org/10.1016/j.matchemphys.2024.129695 
     
No abstract    

    

* Self-Reconstructed Metal–Organic Framework-Based Hybrid Electrocatalysts for Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400452746
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/nano14141168")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400452746"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400452746"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400452746"))][Get cited by]]

OpenAlex: https://openalex.org/W4400452746 (Open access: True)
    
[[https://openalex.org/A5069044030][Kunting Cai]], [[https://openalex.org/A5100733862][Weibin Chen]], [[https://openalex.org/A5077893872][Yinji Wan]], [[https://openalex.org/A5011293216][Hongling Chu]], [[https://openalex.org/A5008110714][Hai Xiao]], [[https://openalex.org/A5078663016][Ruqiang Zou]], Nanomaterials. 14(14)] 2024. https://doi.org/10.3390/nano14141168 
     
Refining synthesis strategies for metal–organic framework (MOF)-based catalysts to improve their performance and stability in an oxygen evolution reaction (OER) is a big challenge. In this study, a series of nanostructured electrocatalysts were synthesized through a solvothermal method by growing MOFs and metal–triazolates (METs) on nickel foam (NF) substrates (named MET-M/NF, M = Fe, Co, Cu), and these electrocatalysts could be used directly as OER self-supporting electrodes. Among these electrocatalysts, MET-Fe/NF exhibited the best OER performance, requiring only an overpotential of 122 mV at a current density of 10 mA cm−2 and showing remarkable stability over 15 h. The experimental results uncovered that MET-Fe/NF underwent an in situ structural reconstruction, resulting in the formation of numerous iron/nickel (oxy)hydroxides with high OER activity. Furthermore, in a two-electrode water-splitting setup, MET-Fe/NF only required 1.463 V to achieve a current density of 10 mA cm−2. Highlighting its potential for practical applications. This work provides insight into the design and development of efficient MOF-based OER catalysts.    

    

* Fe/Ce Co-Doped Ni2p Catalyst to Enhance Alkaline Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400459568
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4889482")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400459568"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400459568"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400459568"))][Get cited by]]

OpenAlex: https://openalex.org/W4400459568 (Open access: False)
    
[[https://openalex.org/A5065115274][Zhixun Luo]], [[https://openalex.org/A5058825953][Li Wang]], [[https://openalex.org/A5054998656][Ruijie Shi]], [[https://openalex.org/A5060611692][Hao Xu]], [[https://openalex.org/A5016288034][Zhuotong Zeng]], [[https://openalex.org/A5009766808][Xiaomin Lang]], [[https://openalex.org/A5028666112][Yong Huang]], [[https://openalex.org/A5036025148][Yuping Liu]], [[https://openalex.org/A5067708304][Xiaoqin Liao]], [[https://openalex.org/A5012919679][Mingzhe Nie]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4889482 
     
No abstract    

    

* Graphitic Carbon Nitride Structures on Carbon Cloth Containing Ultra‐ and Nano‐Dispersed NiO for Photoactivated Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400459946
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202400948")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400459946"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400459946"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400459946"))][Get cited by]]

OpenAlex: https://openalex.org/W4400459946 (Open access: False)
    
[[https://openalex.org/A5098907336][Enrico Scattolin]], [[https://openalex.org/A5054725527][Mattia Benedet]], [[https://openalex.org/A5041872262][Gian Andrea Rizzi]], [[https://openalex.org/A5086668589][Alberto Gasparotto]], [[https://openalex.org/A5085295635][Oleg B. Lebedev]], [[https://openalex.org/A5012412084][Davide Barreca]], [[https://openalex.org/A5081743161][Chiara Maccato]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202400948 
     
Abstract The development of low‐cost and high‐efficiency oxygen evolution reaction (OER) photoelectrocatalysts is a key requirement for H 2 generation via solar‐assisted water splitting. In this study, we report on an amenable fabrication route to carbon cloth‐supported graphitic carbon nitride (gCN) nanoarchitectures, featuring a modular dispersion of NiO as co‐catalyst. The synergistic interaction between gCN and NiO, along with the tailoring of their size and spatial distribution, yield very attractive OER performances and durability in freshwater splitting, of great significance for practical end‐uses. The potential of gCN electrocatalysts containing ultra‐dispersed, i. e . “quasi‐atomic” NiO, exhibiting a higher activity than the ones containing nickel oxide nanoaggregates, is further highlighted by their activity even in real seawater. This work suggests that efficient OER catalysts can be designed through the construction of optimized interfaces between transition metal oxides and carbon nitride, yielding inexpensive and promising noble metal‐free systems for real‐world applications.    

    

* Heterostructure Boosts a Noble-metal-free Oxygen-evolving Electrocatalyst in Acid  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400467045
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ee00189c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400467045"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400467045"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400467045"))][Get cited by]]

OpenAlex: https://openalex.org/W4400467045 (Open access: False)
    
[[https://openalex.org/A5100370328][Jian Wang]], [[https://openalex.org/A5087704385][Yunze Zhang]], [[https://openalex.org/A5100317109][Ying Wang]], [[https://openalex.org/A5023188953][Junsic Cho]], [[https://openalex.org/A5076885525][Ting‐Shan Chan]], [[https://openalex.org/A5066777165][Yang Ha]], [[https://openalex.org/A5033046341][Shu‐Chih Haw]], [[https://openalex.org/A5046273419][Cheng‐Wei Kao]], [[https://openalex.org/A5100441392][Ziyi Wang]], [[https://openalex.org/A5013349560][Lei Jia]], [[https://openalex.org/A5029385071][Min Jiang]], [[https://openalex.org/A5078206959][Jiayi Tang]], [[https://openalex.org/A5083377250][Nan Zheng]], [[https://openalex.org/A5087847070][Zhao Song]], [[https://openalex.org/A5038095598][Yawen Dai]], [[https://openalex.org/A5054904820][Aleksandra Wanda Baron-Wiechec]], [[https://openalex.org/A5048997744][Fu‐Rong Chen]], [[https://openalex.org/A5066308891][Wen‐Xiong Wang]], [[https://openalex.org/A5072570172][Chang Hyuck Choi]], [[https://openalex.org/A5034744923][Zongping Shao]], [[https://openalex.org/A5074347392][Meng Ni]], Energy & environmental science. None(None)] 2024. https://doi.org/10.1039/d4ee00189c 
     
Developing noble metal-free electrocatalysts (NMFEs) for oxygen evolution reaction (OER) is tremendously challenging in acid. Despite extensive research efforts, few reported NMFEs can compete with Ru/Ir oxides for acidic OER....    

    

* Rhenium-boosted electrocatalytic activity and durability of pyrolytic IrO2 for acidic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400468217
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12598-024-02830-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400468217"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400468217"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400468217"))][Get cited by]]

OpenAlex: https://openalex.org/W4400468217 (Open access: False)
    
[[https://openalex.org/A5060908129][Hongwei Lv]], [[https://openalex.org/A5090531383][Hongbin Zhao]], [[https://openalex.org/A5040822775][Xuerong Peng]], [[https://openalex.org/A5042504889][Zhiguo Ye]], [[https://openalex.org/A5067337754][Qikai Huang]], [[https://openalex.org/A5058300296][Xiaotian Yuan]], [[https://openalex.org/A5088419046][Duosheng Li]], [[https://openalex.org/A5002418753][Zhong Jin]], Rare metals/Rare Metals. None(None)] 2024. https://doi.org/10.1007/s12598-024-02830-6 
     
No abstract    

    

* Dual-carbon coupling modulated bimetallic sulfides as high-efficiency bifunctional oxygen electrocatalysts in rechargeable Zn-air battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400472546
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4se00793j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400472546"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400472546"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400472546"))][Get cited by]]

OpenAlex: https://openalex.org/W4400472546 (Open access: False)
    
[[https://openalex.org/A5008705459][Yongxia Wang]], [[https://openalex.org/A5100442572][Jingjing Liu]], [[https://openalex.org/A5100717396][Jiaxi Liu]], [[https://openalex.org/A5020707607][Zhaodi Wang]], [[https://openalex.org/A5076376828][Bin Zhuang]], [[https://openalex.org/A5056662019][Nengneng Xu]], [[https://openalex.org/A5041395114][Xiangzhi Cui]], [[https://openalex.org/A5007984066][Jinli Qiao]], Sustainable energy & fuels. None(None)] 2024. https://doi.org/10.1039/d4se00793j 
     
Design and construction of high-efficiency carbon based non-precious metal electrocatalysts for the kinetic sluggish oxygen reduction and oxygen evolution reactions (ORR and OER) is of great vital but still remain...    

    

* Fabricating Spinel-Type High-Entropy Oxides of (Co, Fe, Mn, Ni, Cr)3O4 for Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400485130
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ma17143415")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400485130"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400485130"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400485130"))][Get cited by]]

OpenAlex: https://openalex.org/W4400485130 (Open access: True)
    
[[https://openalex.org/A5047035069][Xiaofei Hao]], [[https://openalex.org/A5092422194][Ran Wang]], [[https://openalex.org/A5039306880][Xiumin Tan]], [[https://openalex.org/A5077986501][Xiufeng Zhang]], [[https://openalex.org/A5037148185][Xupo Liu]], [[https://openalex.org/A5057274942][Zhaoyang Wu]], [[https://openalex.org/A5000269710][Dongli Yuan]], Materials. 17(14)] 2024. https://doi.org/10.3390/ma17143415 
     
Fabricating efficient oxygen evolution reaction (OER) electrocatalysts is crucial for water electrocatalysis. Herein, the spinel-type high-entropy oxides of (Co, Fe, Mn, Ni, Cr)3O4 were synthesized through the high-temperature calcination approach. The influences of calcination temperatures on structures and electrochemical properties were investigated. The optimized catalyst of HEO-900 contains the hybrid structure of regular polyhedrons and irregular nanoparticles, which is beneficial for the exposure of electrochemically active sites. It was identified that the abundant high-valence metal species of Ni3+, Co3+, Fe3+, Mn4+, and Cr3+ are formed during the OER process, which is generally regarded as the electrochemically active sites for OER. Because of the synergistic effect of multi-metal active sites, the optimized HEO-900 catalyst indicates excellent OER activity, which needs the overpotential of 366 mV to reach the current density of 10 mA cm−2. Moreover, HEO-900 reveals the prominent durability of running for 24 h at the current density of 10 mA cm−2 without clear delay. Therefore, this work supplies a promising route for preparing high-performance multi-metal OER electrocatalysts for water electrocatalysis application.    

    

* The Effect of Removal of External Proteins PsbO, PsbP and PsbQ on Flash-Induced Molecular Oxygen Evolution and Its Biphasicity in Tobacco PSII  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400491314
:TOPICS: Molecular Mechanisms of Photosynthesis and Photoprotection, Molecular Responses to Abiotic Stress in Plants, Dioxygen Activation at Metalloenzyme Active Sites
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/cimb46070428")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400491314"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400491314"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400491314"))][Get cited by]]

OpenAlex: https://openalex.org/W4400491314 (Open access: True)
    
[[https://openalex.org/A5007285445][Sonia Krysiak]], [[https://openalex.org/A5054477050][Květoslava Burda]], Current issues in molecular biology. 46(7)] 2024. https://doi.org/10.3390/cimb46070428 
     
The oxygen evolution within photosystem II (PSII) is one of the most enigmatic processes occurring in nature. It is suggested that external proteins surrounding the oxygen-evolving complex (OEC) not only stabilize it and provide an appropriate ionic environment but also create water channels, which could be involved in triggering the ingress of water and the removal of O2 and protons outside the system. To investigate the influence of these proteins on the rate of oxygen release and the efficiency of OEC function, we developed a measurement protocol for the direct measurement of the kinetics of oxygen release from PSII using a Joliot-type electrode. PSII-enriched tobacco thylakoids were used in the experiments. The results revealed the existence of slow and fast modes of oxygen evolution. This observation is model-independent and requires no specific assumptions about the initial distribution of the OEC states. The gradual removal of exogenous proteins resulted in a slowdown of the rapid phase (~ms) of O2 release and its gradual disappearance while the slow phase (~tens of ms) accelerated. The role of external proteins in regulating the biphasicity and efficiency of oxygen release is discussed based on observed phenomena and current knowledge.    

    

* Recycled Cathodes in Rechargeable Aqueous Batteries as Ready-Made Electrodes for Oxygen Evolution Catalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400493034
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c01862")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400493034"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400493034"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400493034"))][Get cited by]]

OpenAlex: https://openalex.org/W4400493034 (Open access: False)
    
[[https://openalex.org/A5100378540][Jing Wang]], [[https://openalex.org/A5016752102][Yanqi Li]], [[https://openalex.org/A5024071340][Xu Tian]], [[https://openalex.org/A5081867046][Jie Zheng]], [[https://openalex.org/A5059730849][Bingbing Sun]], [[https://openalex.org/A5051520404][Wei Xia]], [[https://openalex.org/A5030808870][Ming Ge]], [[https://openalex.org/A5038012476][Xiaolei Yuan]], [[https://openalex.org/A5091556593][Zhao Cai]], Inorganic chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c01862 
     
The development of a low-cost and efficient oxygen evolution reaction (OER) electrode is of critical importance for water electrolysis technologies. The general approach to achieving a high-efficiency OER electrode is to regulate catalytic material structures by synthetic control. Here we reported an orthogonal approach to obtaining the OER electrode without intentional design and synthesis, namely, recycling MnO    

    

* Solar Light-Driven Molecular Oxygen Activation by BiOCl Nanosheets: Synergy of Coexposed {001}, {110} Facets and Oxygen Vacancies  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400494769
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Emergent Phenomena at Oxide Interfaces, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c06647")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400494769"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400494769"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400494769"))][Get cited by]]

OpenAlex: https://openalex.org/W4400494769 (Open access: False)
    
[[https://openalex.org/A5076719976][Sara E. Ali]], [[https://openalex.org/A5071081111][Sunny Sarkar]], [[https://openalex.org/A5066086354][Astam K. Patra]], ACS applied materials & interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c06647 
     
Single-crystalline BiOCl nanosheets with coexposed {001} and {110} facets, as well as oxygen vacancies, were synthesized using a simple method. These nanosheets have the ability to activate molecular oxygen, producing reactive superoxide radicals (77.8%) and singlet oxygen (22.2%) when exposed to solar light. The BiOCl demonstrated excellent photocatalytic efficiency in producing H    

    

* The defect chemistry and machine learning study 5d transition metal doped on graphitic carbon nitride for bifunctional oxygen electrocatalyst with low overpotential  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400498275
:TOPICS: Memristive Devices for Neuromorphic Computing, Accelerating Materials Innovation through Informatics, Theory and Applications of Extreme Learning Machines
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.034")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400498275"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400498275"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400498275"))][Get cited by]]

OpenAlex: https://openalex.org/W4400498275 (Open access: False)
    
[[https://openalex.org/A5088025824][Wentao Wang]], [[https://openalex.org/A5091260574][Yingdong Qu]], [[https://openalex.org/A5031707610][Dongying Li]], [[https://openalex.org/A5025627195][Aodi Zhang]], [[https://openalex.org/A5003252825][Hongxia Yan]], [[https://openalex.org/A5042469237][Zhenzhen Feng]], [[https://openalex.org/A5030182689][Wenzhi Yao]], International journal of hydrogen energy. 79(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.034 
     
No abstract    

    

* Design of Amorphous High-Entropy FeCoCrMnBS (Oxy) Hydroxides for Boosting Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400505472
:TOPICS: Thermal Barrier Coatings for Gas Turbines, Catalytic Nanomaterials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3866/pku.whxb202404023")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400505472"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400505472"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400505472"))][Get cited by]]

OpenAlex: https://openalex.org/W4400505472 (Open access: False)
    
[[https://openalex.org/A5050150373][Xin Han]], [[https://openalex.org/A5082857475][Zhihao Cheng]], [[https://openalex.org/A5100407229][Jinfeng Zhang]], [[https://openalex.org/A5020960489][Jie Liu]], [[https://openalex.org/A5008178438][Cheng Zhong]], [[https://openalex.org/A5069789783][Wenbin Hu]], Wuli huaxue xuebao. 0(0)] 2024. https://doi.org/10.3866/pku.whxb202404023 
     
No abstract    

    

* Two-Dimensional NiCo2S4 Nanosheets Deliver Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400508869
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2174/0115734137319139240614103935")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400508869"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400508869"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400508869"))][Get cited by]]

OpenAlex: https://openalex.org/W4400508869 (Open access: False)
    
[[https://openalex.org/A5100608920][Meng Li]], [[https://openalex.org/A5100718382][Jidong Zhang]], [[https://openalex.org/A5073233621][Chuanxiao Cheng]], [[https://openalex.org/A5044185552][Shaotao Dai]], [[https://openalex.org/A5100358448][Qiong Li]], [[https://openalex.org/A5042846165][Kun Xiang]], Current nanoscience. 20(None)] 2024. https://doi.org/10.2174/0115734137319139240614103935 
     
Introduction: The development of cost-effective and efficient catalysts plays a pivotal role in the realization of hydrogen production through electrochemical water splitting. Method: In this study, two-dimensional NiCo2S4 nanosheets weresynthesized usinga hydrothermal method followed by a sulfidation process. Results: The resulting materials were thoroughly characterized to understand their morphology and structure. The findings indicate that the NiCo2S4 nanosheets exhibit exceptional electrical conductivity and a high density of pores, which facilitate electrolyte infiltration and interfacial charge transfer during electrochemical reactions. Furthermore, the incorporation of S2− modulates the electronic structure of metal ions, reducing the oxidation potential of metal sites and promoting the surface reconstruction of the electrode to form active species. Electrochemical tests conducted in a 1 M KOH solution using the synthesized catalyst as the working electrode demonstrate an overpotential of merely 280 mV and 300 mV at a current density of 20 mA cm−2 and 40 mA cm−2 , respectively, which are much lower than those of NiCo-LDH electrodes (360 mV and 410 mV). Conclusion: Furthermore, the NiCo2S4 electrode delivers a remarkably low Tafel slope of 47.9 mV dec−1 . This investigation presents a novel approach to the development of efficient transition metal-based electrocatalysts.    

    

* Phase engineering boosting heterogeneous interface effect in RuO2/MnO2 catalysts for acidic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400519936
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.153921")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400519936"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400519936"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400519936"))][Get cited by]]

OpenAlex: https://openalex.org/W4400519936 (Open access: False)
    
[[https://openalex.org/A5100784613][Jia Li]], [[https://openalex.org/A5011176439][Min‐Liang Yao]], [[https://openalex.org/A5029000004][Zhongchun Yuan]], [[https://openalex.org/A5018434228][Jun Ma]], [[https://openalex.org/A5014932145][Shuo Geng]], [[https://openalex.org/A5056248568][Liu Fei]], Chemical engineering journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.153921 
     
No abstract    

    

* Nanocomposite Engineering: Tailoring MXene/Cobalt Oxide for Efficient Electrocatalytic Hydrogen and Oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400520828
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.175532")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400520828"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400520828"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400520828"))][Get cited by]]

OpenAlex: https://openalex.org/W4400520828 (Open access: False)
    
[[https://openalex.org/A5037452737][Anu Tresa Sunny]], [[https://openalex.org/A5018354050][Subramanian Rajalekshmi]], [[https://openalex.org/A5072349340][Alagarsamy Pandikumar]], Journal of alloys and compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.175532 
     
No abstract    

    

* High-Performance Battery-Supercapacitor Hybrid Device and Electrocatalytic Oxygen Evolution Reaction Based on NiCo2-xMnxO4@Ni-MOF Ternary Metal Oxide Core-Shell Structures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400571945
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta02978j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400571945"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400571945"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400571945"))][Get cited by]]

OpenAlex: https://openalex.org/W4400571945 (Open access: False)
    
[[https://openalex.org/A5059831386][Suprimkumar D. Dhas]], [[https://openalex.org/A5086528985][Avinash C. Mendhe]], [[https://openalex.org/A5092412236][Pragati N. Thonge]], [[https://openalex.org/A5032276778][Amar M. Patil]], [[https://openalex.org/A5088470469][Youngsu Kim]], [[https://openalex.org/A5100650947][Daewon Kim]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta02978j 
     
The electrodes, refined by adjusting Co and Mn ratios in the precursor solution to NiCo2-xMnxO4 (X = 0, 0.5, 1, 1.5, 2), demonstrate superior electrochemical performance compared to binary metal...    

    

* Highly Active Oxygen Evolution Reaction Catalyst Using Rhombohedral Boron Monosulfide  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400441158
:TOPICS: Electrocatalysis for Energy Conversion, Innovations in Organic Synthesis Reactions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1380/vss.67.333")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400441158"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400441158"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400441158"))][Get cited by]]

OpenAlex: https://openalex.org/W4400441158 (Open access: True)
    
[[https://openalex.org/A5083128420][Linghui Li]], [[https://openalex.org/A5091858799][Takahiro Kondo]], Hyomen to shinku. 67(7)] 2024. https://doi.org/10.1380/vss.67.333 
     
No abstract    

    

* Fuel assisted crystal structure tailoring of manganese oxides and their surface reactivity towards oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400380417
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-07-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10853-024-09908-7")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400380417"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400380417"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400380417"))][Get cited by]]

OpenAlex: https://openalex.org/W4400380417 (Open access: False)
    
[[https://openalex.org/A5082181758][Pramod Sagar]], [[https://openalex.org/A5091339217][S. Ashoka]], [[https://openalex.org/A5039802353][N. Srinivasa]], [[https://openalex.org/A5027814378][K. Yogesh]], [[https://openalex.org/A5082502225][S. Girish Kumar]], Journal of materials science. None(None)] 2024. https://doi.org/10.1007/s10853-024-09908-7 
     
No abstract    

    

* MoS2@CoFe-MOF catalysts by one-pot hydrothermal synthesis enhanced electron interaction between MoS2 nanoflower and bimetallic MOF for efficient oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400515740
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj02380c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400515740"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400515740"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400515740"))][Get cited by]]

OpenAlex: https://openalex.org/W4400515740 (Open access: False)
    
[[https://openalex.org/A5100462966][Jiahui Li]], [[https://openalex.org/A5009680978][Yufen Wang]], [[https://openalex.org/A5056267428][Qian Yu]], [[https://openalex.org/A5008087704][Xuedong Wei]], New journal of chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj02380c 
     
A kind of MoS2@CoFe-MOF electrocatalyst was prepared on carbon cloth by one-pot hydrothermal method. The excellent electrocatalysts activity of MoS2@CoFe-MOF are demonstrated. It can use the overpotential of 220 mV...    

    

* Correction to: Enhancing the performance of hybrid supercapacitor and oxygen evolution reaction via temperature-modulated binder-free (zinc strontium phosphate/nitrogen-graphene quantum dots) electrode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400472192
:TOPICS: Conducting Polymer Research, Electrochemical Biosensor Technology, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10854-024-13142-x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400472192"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400472192"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400472192"))][Get cited by]]

OpenAlex: https://openalex.org/W4400472192 (Open access: False)
    
[[https://openalex.org/A5040599145][Asma Zaka]], [[https://openalex.org/A5014807301][Muhammad Waqas Iqbal]], [[https://openalex.org/A5027132782][Afaf Khadr Alqorashi]], [[https://openalex.org/A5041634343][Badriah S. Almutairi]], [[https://openalex.org/A5084761641][Hussein Alrobei]], [[https://openalex.org/A5016377497][Amir Muhammad Afzal]], [[https://openalex.org/A5009396077][Haseebul Hassan]], Journal of materials science. Materials in electronics. 35(19)] 2024. https://doi.org/10.1007/s10854-024-13142-x 
     
No abstract    

    

* Oxygen-mediated defect evolution and interface analysis of MoOx/n-Si devices  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400482309
:TOPICS: Atomic Layer Deposition Technology, Failure Analysis of Integrated Circuits, Silicon Solar Cell Technology
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6463/ad6166")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400482309"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400482309"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400482309"))][Get cited by]]

OpenAlex: https://openalex.org/W4400482309 (Open access: False)
    
[[https://openalex.org/A5017430933][Abhishek Kumar]], [[https://openalex.org/A5089474872][Shweta Tomer]], [[https://openalex.org/A5065730581][Vandana Vandana]], [[https://openalex.org/A5065127010][Thomas Fix]], [[https://openalex.org/A5069293460][Mrinal Dutta]], [[https://openalex.org/A5017947174][Sanjay K. Srivastava]], [[https://openalex.org/A5011220601][P. Prathap]], Journal of physics. D, Applied physics. None(None)] 2024. https://doi.org/10.1088/1361-6463/ad6166 
     
Abstract The performance of MoOx based devices is highly influenced by the presence of oxygen vacancies and the trap density at the oxide-semiconductor interface. This paper presents a detailed investigation of the surface states present at the MoOx/c-Si interface through capacitance and conductance methods. Thin films of MoOx were deposited on n-Si using DC reactive sputtering of Mo under varying oxygen flow rates and studied the modulation of metal-insulator-semiconductor (MIS) device parameters using appropriate analysis methods. The capacitance-voltage (CV) analysis reveals the formation of nearly dielectric films at an intermediate oxygen flow rate of 15 sccm, exhibiting a dielectric constant of 24 and negative fixed charges of approximately 1.81x1012 cm-2. Work function evaluated from the Kelvin probe measurements was found to be maximum of 5.08 eV for the films deposited at the intermediate oxygen flow rate of 15 sccm. Furthermore, admittance analysis was performed on all the films to determine the loss mechanism in different regions, ranging from inversion to accumulation. Parallel conductance for different bias conditions was studied and observed the domination of oxide traps at the higher oxygen flow (> 20 sccm). Investigation of deep level defects were performed using the deep level transient spectroscopy (DLTS) in the temperature range of 100 K to 475 K, along with the C-V measurements. A transition in C-V behavior was observed below room temperature that shows the minority carrier response time is controlled by generation-recombination at low temperatures and by diffusion at high temperatures. The X-ray photoelectron spectroscopy (XPS) measurements showed that the films are sub-stoichiometric with the dominant oxidation state of Mo+6. The results have been discussed and presented in detail.&#xD;    

    

* Supported hydrogen–oxygen fuel cell catalysts: From synthesis, structure-performance evolution and mechanism to synergy strategy  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400476130
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nanoms.2024.05.016")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400476130"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400476130"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400476130"))][Get cited by]]

OpenAlex: https://openalex.org/W4400476130 (Open access: True)
    
[[https://openalex.org/A5040312379][Zhijie Kong]], [[https://openalex.org/A5083919920][Dongcai Zhang]], [[https://openalex.org/A5087733111][Shiqian Du]], [[https://openalex.org/A5087330509][Gen Huang]], [[https://openalex.org/A5001044012][Jianghua Wu]], [[https://openalex.org/A5034970777][Zhijuan Liu]], [[https://openalex.org/A5100455306][Tao Li]], [[https://openalex.org/A5042902756][Shuangyin Wang]], Nano materials science. None(None)] 2024. https://doi.org/10.1016/j.nanoms.2024.05.016 
     
No abstract    

    

* Iron-cobalt nanoparticles dispersed in indium-based MIL-68-derived carbon nanosticks for water oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400429122
:TOPICS: Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cy00746h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400429122"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400429122"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400429122"))][Get cited by]]

OpenAlex: https://openalex.org/W4400429122 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5091640552][Yao Fu]], [[https://openalex.org/A5084914364][Junliang Chen]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], Catalysis science & technology. None(None)] 2024. https://doi.org/10.1039/d4cy00746h 
     
FeCo-based catalysts exhibit excellent oxygen evolution reaction (OER) in terms of high activity and robust stability. Herein, the dispersed bimetallic FeCo nanoparticles can be effectively encapsulated into an isostructural In-based...    

    

* Natural biomass derived single-atom catalysts for energy and environmental applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400441693
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijbiomac.2024.133694")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400441693"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400441693"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400441693"))][Get cited by]]

OpenAlex: https://openalex.org/W4400441693 (Open access: False)
    
[[https://openalex.org/A5100608123][Nan Yu]], [[https://openalex.org/A5100352228][Xin Liu]], [[https://openalex.org/A5070574260][Long Kuai]], International journal of biological macromolecules. None(None)] 2024. https://doi.org/10.1016/j.ijbiomac.2024.133694 
     
Single atom catalysts (SACs) excel in various chemical processes, including electrocatalysis and industrial chemistry, due to their efficiency. In contrast to chemically synthesized precursors, biomass offers a greener and more cost-effective approach for SACs fabrication. To date, over forty types of SACs have been synthesized using natural sources like starch, cellulose, lignin, hemicellulose, proteins, and chitin. These catalysts incorporate metals such as Fe, Co, Ni, Cu, Zn, Mn, and Pt. This review concentrates on the preparation of SACs from biomass, exploring innovative techniques and their extensive applications in energy conversion and environmental conservation, including but not limited to reactions involving oxygen reduction, oxygen evolution, and hydrogen evolution. It also discusses current challenges and prospective advancements in this domain. This paper updates and expands on the knowledge of SACs derived from biomass, aiming to foster the development of more effective, low-cost catalyst materials from natural sources.    

    

* Facile Carbothermal Synthesis of Metal Phosphides-Based Multifunctional Electrocatalysts via Polyaniline Doped with Phosphoric Acid  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400520505
:TOPICS: Electrocatalysis for Energy Conversion, Polyoxometalate Clusters and Materials, Homogeneous Catalysis with Transition Metals
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/1945-7111/ad6215")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400520505"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400520505"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400520505"))][Get cited by]]

OpenAlex: https://openalex.org/W4400520505 (Open access: True)
    
[[https://openalex.org/A5070738256][D. O. Mazur]], [[https://openalex.org/A5062202530][Olena O. Pariiska]], [[https://openalex.org/A5035129904][Ya. I. Kurys]], [[https://openalex.org/A5075552244][V. G. Koshechko]], [[https://openalex.org/A5073928802][V. D. Pokhodenko]], Journal of the Electrochemical Society. None(None)] 2024. https://doi.org/10.1149/1945-7111/ad6215 
     
Abstract Transition metal phosphides (TMPs) and their composites are promising non-platinum electrocatalysts for hydrogen evolution (HER), oxygen evolution (OER), and oxygen reduction (ORR) reactions. But traditional methods to obtain these electrocatalysts are usually multi-step and include the participation of hazardous phosphorus compounds during phosphidation. Here, the possibility of using a polyaniline doped with phosphoric acid (PANI∙H3PO4) – as a source of C, N and P simultaneously - to obtain composites based on N,P-doped carbon and nano- and/or submicron TMP particles as HER, OER and ORR electrocatalysts is demonstrated. The pyrolysis of PANI∙H3PO4 together with Co, Ni, Mo, or Fe salt allows the formation of such composite electrocatalysts by the carbon thermal reduction route. Regardless of the pH of the electrolyte, the MoP-based electrocatalyst is characterized in HER by the smallest Tafel slope and overpotential of hydrogen evolution and also exhibits high stability during long-term operation. At the same time, other composites are multifunctional electrocatalysts possessing activity not only in HER, but also in OER and ORR. The proposed approach can be a starting point for a simple, universal in choice of d-metal, and environmentally attractive preparation of multifunctional TMP-based electrocatalysts with further improvement of their performance.    

    

* Stimulating Electron Delocalization of Lanthanide Elements through High-Entropy Confinement to Promote Electrocatalytic Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400446876
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.4c04176")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400446876"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400446876"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400446876"))][Get cited by]]

OpenAlex: https://openalex.org/W4400446876 (Open access: False)
    
[[https://openalex.org/A5043015046][Yong Jiang]], [[https://openalex.org/A5067616773][Liang Zhong]], [[https://openalex.org/A5027309315][Jin‐Cheng Liu]], [[https://openalex.org/A5041941283][Hao Fu]], [[https://openalex.org/A5101557737][Chun‐Hua Yan]], [[https://openalex.org/A5087025894][Yaping Du]], ACS nano. None(None)] 2024. https://doi.org/10.1021/acsnano.4c04176 
     
High-entropy alloys (HEAs) have aroused extensive attention in the field of catalysis. However, due to the integration of multiple active sites in HEA, it exhibits excessive adsorption behavior resulting in difficult desorption of active species from the catalyst surfaces, which hinders the catalytic efficiency. Therefore, adjusting the adsorption strength of the active site in HEA to enhance the catalytic activity is of great importance. By introducing rare-earth (RE) elements into the high-entropy alloy, the delocalization of 4f electrons can be achieved through the interaction between the multimetal active site and RE, which benefits to regulate the adsorption strength of the HEA surface. Herein, the RE Ce-modified hexagonal-close-packed PtRuFeCoNiZn-Ce/C HEAs are synthesized and showed an excellent electrocatalytic activity for hydrogen evolution reaction and oxygen evolution reaction with ultralow overpotentials of 4, 7 and 156, 132 mV, respectively, to reach 10 mA cm    

    

* Electroless plating of Co P O electrocatalyst on carbon cloth for alkaline water electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400391495
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2024.118491")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400391495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400391495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400391495"))][Get cited by]]

OpenAlex: https://openalex.org/W4400391495 (Open access: False)
    
[[https://openalex.org/A5100745246][Pooja Sharma]], [[https://openalex.org/A5001505710][Sohel Siraj]], [[https://openalex.org/A5029947107][Parikshit Sahatiya]], [[https://openalex.org/A5079597192][C.K. Sumesh]], [[https://openalex.org/A5061895171][Pratik M. Pataniya]], Journal of electroanalytical chemistry. None(None)] 2024. https://doi.org/10.1016/j.jelechem.2024.118491 
     
We report the simple method of fabrication, self-supported nanostructure of CoPO nanoparticles (NPs) on carbon cloth scaffold by electroless plating. CoPO demonstrates exceptional bi-functional catalytic performance in water electrolysis, efficiently producing hydrogen (H2) and oxygen (O2) gases simultaneously due to optimized adsorption energy for intermediates and the excellent conductivity of Cobalt-metallic nanoparticles. CoPO achieves a geometric current of 10 mA/cm2 with 190 mV and 280 mV overpotential for hydrogen evolution reaction (HER) and oxygen evolution reaction (OER), respectively, while its continuous catalytic nanoparticle coating on the carbon cloth scaffold ensures superior charge transport with minimal resistance. It is highly encouraging to observe that the HER and OER performance of CoPO electrodes far surpasses that of carbon cloth, approaching the benchmark set by noble electrocatalysts Pt/C and RuO2. The alkaline electrolyser based on the two-electrode cell using CoPO electrodes demonstrates bi-functional water splitting at 1.64 V and 1.98 V at 10 and 100 mA/cm2. Furthermore, the alkaline electrolyser exhibits stable electrocatalytic activity for about more than 16 h at the current density of 50 mA/cm2.    

    

* BaTaO2N and quantum dots-based CuO nanocomposites for HER by solar electrochemical water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400388075
:TOPICS: Zinc Oxide Nanostructures, Emergent Phenomena at Oxide Interfaces, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.inoche.2024.112828")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400388075"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400388075"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400388075"))][Get cited by]]

OpenAlex: https://openalex.org/W4400388075 (Open access: False)
    
[[https://openalex.org/A5011865555][P. Akhil]], [[https://openalex.org/A5101401121][Kothandaraman Ramanujam]], [[https://openalex.org/A5081851002][Smarak Rath]], [[https://openalex.org/A5100036842][Ragul Krishanan]], [[https://openalex.org/A5101179904][Somnath Chandra Roy]], [[https://openalex.org/A5101894294][S. Sankaran]], [[https://openalex.org/A5056217230][Amit Sobti]], [[https://openalex.org/A5079049057][Tiju Thomas]], Inorganic chemistry communications/Inorganic chemistry communications (Online). None(None)] 2024. https://doi.org/10.1016/j.inoche.2024.112828 
     
Barium tantalum oxynitride (BaTaO2N) has been demonstrated to be an attractive catalyst for photo-electrochemical water splitting, especially oxygen evolution reactions. However, the hydrogen production rates and charge transfer resistances of BTN leave much to be desired from a practical standpoint. In fact, it has never been reported for photocathode applications. On the other hand, CuO has been reported for hydrogen evolution reactions. Given this, here nanocomposites of BaTaO2N and copper oxide quantum dots (CuO QDs), where the latter are digestively ripened, are reported for photoelectrochemical water splitting on a carbon paper substrate. To assess the role of ultra-small quantum dots, composites of commercially available CuO nanoparticles with BaTaO2N were also tested. BaTaO2N and CuO QD nanocomposites performed well and showed a high photocurrent density of 3.1 mA cm−2 at 0 V vs RHE. This was also accompanied by reduced charge transfer resistance (225.4 Ω) due to the high interfacial surface area provided by nanoscopic CuO on BaTaO2N.    

    

* Operando-reconstructed polyatomic ion layers boost the activity and stability of industrial current-density water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400391838
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.scib.2024.07.003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400391838"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400391838"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400391838"))][Get cited by]]

OpenAlex: https://openalex.org/W4400391838 (Open access: False)
    
[[https://openalex.org/A5026502078][Yingxia Zhao]], [[https://openalex.org/A5074881067][Ying Wu]], [[https://openalex.org/A5061424808][Qunlei Wen]], [[https://openalex.org/A5055225238][Danji Huang]], [[https://openalex.org/A5027981734][Ruoou Yang]], [[https://openalex.org/A5040389793][Haozhi Wang]], [[https://openalex.org/A5040538229][Yingying Xu]], [[https://openalex.org/A5062411182][Ming Sun]], [[https://openalex.org/A5074615382][Youwen Liu]], [[https://openalex.org/A5027757534][Jiakun Fang]], [[https://openalex.org/A5069378732][Tianrui Zhai]], [[https://openalex.org/A5062414558][Lin Yu]], Science Bulletin. None(None)] 2024. https://doi.org/10.1016/j.scib.2024.07.003 
     
Metal–organic frameworks have garnered attention as highly efficient pre-electrocatalysts for the oxygen evolution reaction (OER). Current structure–activity relationships primarily rely on the assumption that the complete dissolution of organic ligands occurs during electrocatalysis. Herein, modeling based on NiFe Prussian blue analogs (NiFe-PBAs) show that cyanide ligands leach from the matrix and subsequently oxidize to corresponding inorganic ions (ammonium and carbonate) that re-adsorb onto the surface of NiFe OOH during the OER process. Interestingly, the surface-adsorbed inorganic ions induce the OER reaction of NiFe OOH to switch from the adsorbate evolution to the lattice-oxygen–mediated mechanism, thus contributing to the high activity. In addition, this reconstructed inorganic ion layer acting as a versatile protective layer can prevent the dissolution of metal sites to maintain contact between catalytic sites and reactive ions, thus breaking the activity–stability trade-off. Consequently, our constructed NiFe-PBAs exhibit excellent durability for 1250 h with an ultralow overpotential of 253 mV at 100 mA cm−2. The scale-up NiFe-PBAs operated with a low energy consumption of ∼4.18 kWh m−3 H2 in industrial water electrolysis equipment. The economic analysis of the entire life cycle demonstrates that this green hydrogen production is priced at US$2.59/kgH2, meeting global targets (<US$2.5/kgH2).    

    

* Rapid Charge Extraction via Hole Transfer Layer and Interfacial Coordination Bonds on Hematite Photoanode for Efficient Photoelectrochemical Water Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400391363
:TOPICS: Solar Water Splitting Technology, Photocatalytic Materials for Solar Energy Conversion, Advanced Oxidation Processes for Water Treatment
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124369")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400391363"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400391363"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400391363"))][Get cited by]]

OpenAlex: https://openalex.org/W4400391363 (Open access: False)
    
[[https://openalex.org/A5052631316][Huilin Niu]], [[https://openalex.org/A5077078418][Lili Gao]], [[https://openalex.org/A5014210298][Mingming Liu]], [[https://openalex.org/A5001913259][Yanbo Zou]], [[https://openalex.org/A5070568835][Jiaoli Wang]], [[https://openalex.org/A5052825338][Guowen Hu]], [[https://openalex.org/A5025396304][Jun Jin]], Applied catalysis. B, Environmental. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124369 
     
Enhancing carrier separation and transport efficiency to achieve efficient water oxidation reaction is an important issue in photoelectrochemical (PEC) water splitting field, and introducing hole transfer layer (HTL) is an effective strategy to improve it. However, the difficulty of charge transfer between HTL and oxygen evolution catalyst (OEC) is a problem unresolved. To ameliorate the situation, we choose CoOOH as HTL and the metal–organic coordination compound constructed by 4,5-Imidazoledicarboxylic acid (IA) and Co/Ni ions as OEC. Using the interfacial coordination bonds as carrier transfer channels, the holes were rapidly extracted from HTL to OEC containing abundant active sites and participate in oxidation reaction. In consequence, the unique design results in a photocurrent density of 2.97 times that of α-Fe2O3 at 1.23 VRHE for the IACN/CoOOH/Fe2O3. This study reveals how the advisable design of photoanode promotes interfacial charge transfer and provides a valuable reference for the design of composite photoanode.    

    

* CoMoP Hole Transfer Layer Functionally Enhances Efficiency and Stability of BiVO4 Based Photoanode for Solar Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400388037
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Solar Water Splitting Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124375")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400388037"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400388037"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400388037"))][Get cited by]]

OpenAlex: https://openalex.org/W4400388037 (Open access: False)
    
[[https://openalex.org/A5086977108][Yingying Wang]], [[https://openalex.org/A5080796177][Y. Y. Chen]], [[https://openalex.org/A5028551025][Youngjun Yun]], [[https://openalex.org/A5034141375][Xiaoting Hong]], [[https://openalex.org/A5000212258][Yongchao Huang]], [[https://openalex.org/A5015887120][Hongbing Ji]], Applied catalysis. B, Environmental. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124375 
     
Engineering the hole transfer layer is a promising approach to suppress the bulk charge recombination of photoanodes for enhancing solar water splitting performance. Herein, functional cobalt-molybdenum bimetallic phosphide (CoMoP) layer are inserted between bismuth vanadate (BiVO4) and NiFeOx oxygen evolution cocatalyst (OEC) as hole transfer layer to construct an integrated photoanode (NiFeOx/CoMoP/BiVO4). This state-of-the-art NiFeOx/CoMoP/BiVO4 photoanode not only achieves a superior photocurrent density of 5.82 mA/cm2 at 1.23 V versus a reversible hydrogen electrode (vs RHE), but also an outstanding 60 hours long-term photostability (100 mW/cm2). Such excellent PEC performance can be attributed to the engineering CoMoP hole layer in NiFeOx/BiVO4, promoting hole transfer, retarding bulk charge recombination and accelerating the surface water oxidation kinetics. This study contributes to the role of the hole transfer layer and sheds light on the development of effective and stable photoanodes for PEC water splitting.    

    

* Recent advances of carbon fiber-based self-supported electrocatalysts in oxygen electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400391249
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.06.051")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400391249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400391249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400391249"))][Get cited by]]

OpenAlex: https://openalex.org/W4400391249 (Open access: False)
    
[[https://openalex.org/A5011689848][Jian Han]], [[https://openalex.org/A5083541570][Nanping Deng]], [[https://openalex.org/A5037710467][Hao Chi]], [[https://openalex.org/A5100765193][Gang Wang]], [[https://openalex.org/A5100439938][Yilong Wang]], [[https://openalex.org/A5055039492][Qiang Zeng]], [[https://openalex.org/A5013764581][Zhaozhao Peng]], [[https://openalex.org/A5077708116][Bowen Cheng]], [[https://openalex.org/A5063148046][Baoming Zhou]], [[https://openalex.org/A5048811125][Weimin Kang]], Journal of Energy Chemistry/Journal of energy chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.06.051 
     
Oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) are the key reactions in numerous renewable energy devices. Unlike conventional powdered catalysts, self-supported catalysts are extensively employed in oxygen electrocatalysis because of the enhanced electron-transfer rate, high specific surface area, and superior mechanical flexibility. Among the self-supported conductive substrates, carbon fiber usually exhibits several distinctive advantages, such as a straightforward preparation process, relatively low cost, good stability, and excellent conductivity. Against this background, carbon fiber-based self-supported electrocatalysts have been widely applied and studied in oxygen electrocatalysis, indicating a promising development direction in oxygen electrocatalyst research. Thus, it is essential to offer an overall summary of the research progress in this field to facilitate its subsequent development. Taking the regulatory mechanisms and modification methods as a starting point, this review comprehensively summarizes recent research on carbon fiber-based self-supported electrocatalysts in recent years. Firstly, a brief overview of the synthesis methods and regulatory mechanisms of carbon fiber-based self-supported electrocatalysts is given. Furthermore, the view also highlights the modification methods and research progress of self-supported electrocatalysts synthesized on carbon fiber-based substrates in recent years in terms of different dopant atoms. Finally, the prospects for the application of self-supported electrocatalysts based on carbon fiber in oxygen electrocatalysis and the possible future directions of their development are presented. This review summarizes recent developments and applications of self-supported bi-functional electrocatalysts with carbon fiber-based materials as the conducting substrate in oxygen electrocatalysis. It also lays a robust scientific foundation for the subsequent reasonable design of highly effective carbon fiber-based self-supported electrocatalysts.    

    

* Developing Catalysts for Membrane Electrode Assemblies in High Performance Polymer Electrolyte Membrane Water Electrolyzers  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400494512
:TOPICS: Hydrogen Energy Systems and Technologies, Lithium Battery Technologies, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202301827")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400494512"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400494512"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400494512"))][Get cited by]]

OpenAlex: https://openalex.org/W4400494512 (Open access: False)
    
[[https://openalex.org/A5076243133][Sun Seo Jeon]], [[https://openalex.org/A5100429506][Won-Jae Lee]], [[https://openalex.org/A5023665241][Hyeseong Jeon]], [[https://openalex.org/A5006536958][Hyunjoo J. Lee]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202301827 
     
Extensive research is underway to achieve carbon neutrality through the production of green hydrogen via water electrolysis, powered by renewable energy. Polymer membrane water electrolyzers, such as proton exchange membrane water electrolyzer (PEMWE) and anion exchange membrane water electrolyzer (AEMWE), are at the forefront of this research. Developing highly active and durable electrode catalysts is very important for commercializing these electrolyzers. However, most research is conducted in half‐cell setups, which may not fully represent the catalysts' effectiveness in membrane‐electrode‐assembly (MEA) devices. This review explores the catalysts developed for high‐performance PEMWE and AEMWE MEA systems. Only the catalysts reporting the MEA performance were discussed in this review. In PEMWE, strategies aim to minimize Ir use for oxygen evolution reaction (OER) by maximizing activity, employing metal oxide‐based supports, integrating secondary elements into IrOx lattices, or exploring non‐Ir materials. For AEMWE, the emphasis is on enhancing the performance of NiFe‐based and Co‐based catalysts by improving electrical conductivity and mass transport. Pt‐based and Ni‐based catalysts for hydrogen evolution reaction (HER) in AEMWE are also examined. Additionally, this review discusses the unique considerations for catalysts operating in pure water within AEMWE systems.    

    

* Cu Regulating the Bifunctional Activity of Co-O Sites for the High-Performance Rechargeable Zinc-Air Battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400422879
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c04853")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400422879"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400422879"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400422879"))][Get cited by]]

OpenAlex: https://openalex.org/W4400422879 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5053712083][Dandan Yue]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5100624318][Qingyu Li]], ACS applied materials & interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c04853 
     
The rational design of cost-effective and highly active electrocatalysts becomes the crucial energy storage technology to boost the kinetics of the oxygen reduction reaction (ORR) and the oxygen evolution reaction (OER), which hinders the large-scale application of metal-air batteries under the situation of increasingly pressing energy anxiety. Herein, the Co-based ZIF introduced the moderate amount of Cu2+-derived Cu/Co metal nanoparticles (NPs) embedded in carbon frameworks after high-temperature calcination. The Co-O bond on the surface of Co nanoparticles is modulated by adjacent Cu nanoparticles with the surface Cu-O bonds. The resulted increase of the Co2+/Co3+ ratio in 0.1CuCo-NC enhances the ORR/OER bifunctional catalytic kinetics along with the ΔE of 0.639 V. In situ Raman spectra of the catalyst on the three-electrode system as well as in the driven zinc-air battery (ZAB) show that the Co-O active sites regulated by Cu nanoparticles with Cu-O bonds maintain a periodic lattice expansion and compression during discharging and charging. The zinc-air battery based on 0.1CuCo-NC has a peak power density of up to 198.3 mW cm–2, a mass-specific capacity of 798.2 mAh g–1, and a cycling stability of 923 h at room temperature. This work makes up the research gap of a Co-based metal–organic framework (MOF)-derived catalyst regulated by a transition metal.    

    

* CNTs/Ce co-doped PbO2 anode for electro-oxidation of triclosan: Fabrication, kinetics, and degradation mechanism based on DFT calculations  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400386538
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Advanced Oxidation Processes for Water Treatment, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jwpe.2024.105748")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400386538"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400386538"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400386538"))][Get cited by]]

OpenAlex: https://openalex.org/W4400386538 (Open access: False)
    
[[https://openalex.org/A5075779966][Huijiao Wang]], [[https://openalex.org/A5101394021][Siyuan Xue]], [[https://openalex.org/A5030186359][Weiyi Wang]], [[https://openalex.org/A5068332646][Fan Gao]], [[https://openalex.org/A5101394022][Shizuo Yi]], [[https://openalex.org/A5100775732][Jiayin Li]], [[https://openalex.org/A5046902611][Yuxin Yang]], [[https://openalex.org/A5025034715][Erzhuo Zhao]], [[https://openalex.org/A5060947105][Jianchao Wang]], [[https://openalex.org/A5051914364][Jianbing Wang]], Journal of water process engineering. 64(None)] 2024. https://doi.org/10.1016/j.jwpe.2024.105748 
     
In this study, an efficient Ti/SnO2-Sb2O3/CNT-Ce-PbO2 electrode was fabricated for triclosan electro-oxidation by co-doping the transition metal Ce and carbon nanotubes (CNTs) into the PbO2 active layer. Characterization results show that the co-doped Ce and CNTs present a synergistic effect on covering the obvious cracks on the Ti/SnO2-Sb2O3 surface, decreasing the PbO2 crystal size, increasing the electrode oxygen evolution potential from 1.60 to 2.17 V vs SCE, and reducing the charge transfer resistance by 66 %. Consequently, Ti/SnO2-Sb2O3/CNT-Ce-PbO2 was the most effective and energy-efficient electrode for hydroxyl radical (•OH) generation and triclosan electro-oxidation in this study. Compared with other two electrodes (Ti/SnO2-Sb2O3 and Ti/SnO2-Sb2O3/Ce-PbO2), triclosan removal by Ti/SnO2-Sb2O3/CNT-Ce-PbO2 was accelerated by 1.8–2.6 times, with the energy demand for abating 90 % triclosan (EEO) decreased by 49 % – 67 %. Furthermore, triclosan degradation pathways were proposed based on density functional theory (DFT) calculation and transformation product (TP) identification, with •OH addition at C14 and C11 sites being the most favorable pathway. In addition, the estimated acute and chronic toxicities of TPs were generally decreased than their mother compound. Therefore, the results of this study suggest the feasibility and effectiveness of the Ti/SnO2-Sb2O3/CNT-Ce-PbO2 electrode for triclosan electro-oxidation.    

    

* Lanthanum‐Nickel‐Based Mixed‐Oxide‐Coated Nickel Electrodes for the OER Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400446542
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/fuce.202300239")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400446542"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400446542"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400446542"))][Get cited by]]

OpenAlex: https://openalex.org/W4400446542 (Open access: True)
    
[[https://openalex.org/A5016719471][Nikolas Mao Kubo]], [[https://openalex.org/A5086362727][Rim Mhamdi]], [[https://openalex.org/A5078364217][Regina Palkovits]], Fuel cells. None(None)] 2024. https://doi.org/10.1002/fuce.202300239 
     
ABSTRACT The anodic oxygen evolution reaction (OER) remains a bottleneck for electrocatalytic water splitting due to its sluggish kinetics and, thus, high overpotentials. This limits water electrolysis as a key technology for the generation of hydrogen as a sustainable alternative to fossil fuels. For alkaline water splitting, perovskite phases (ABO 3 ) with earth‐abundant first‐row transition‐metals have emerged as a promising material class for OER electrocatalysts. Among these, LaNiO 3 has been found to exhibit high intrinsic OER activity. To increase catalyst utilization, a high surface area of the catalyst is desirable and can be achieved by impregnation of porous templates. In this work, La–Ni‐based oxides were prepared via impregnation of activated carbon and subsequent heating, combining precursor calcination and template removal into one step. The phase structure of the samples is analyzed via powder X‐ray diffractometry, and the morphology is determined by scanning electron microscopy. The synergistic effect of B‐site mixing iron as well as A‐site mixing strontium into LaNiO 3 is studied and found to increase its OER activity, confirming the activity‐enhancing effect of Fe in Ni‐based OER electrocatalysts. To allow for facile technical application of the catalysts, the electrodes are prepared by coating a perovskite ink onto Ni‐metal as industrially relevant substrates, followed by calcination.    

    

* Lattice Distortion Promotes Carrier Separation to Improve the Photoelectrochemical Water Splitting Performance of Bismuth Vanadate Photoanode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400497697
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202410548")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400497697"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400497697"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400497697"))][Get cited by]]

OpenAlex: https://openalex.org/W4400497697 (Open access: False)
    
[[https://openalex.org/A5068749579][Kaige Tian]], [[https://openalex.org/A5090226123][Lujie Jin]], [[https://openalex.org/A5047333790][Asif Mahmood]], [[https://openalex.org/A5060844091][Hua Yang]], [[https://openalex.org/A5020251473][Pengfei An]], [[https://openalex.org/A5100345384][Jing Zhang]], [[https://openalex.org/A5071601763][Yujin Ji]], [[https://openalex.org/A5035944985][Youyong Li]], [[https://openalex.org/A5004290356][Li Deng]], [[https://openalex.org/A5047252183][Junqing Yan]], [[https://openalex.org/A5047252183][Junqing Yan]], Advanced functional materials. None(None)] 2024. https://doi.org/10.1002/adfm.202410548 
     
Abstract The poor carrier separation capability and sluggish water oxidation reaction kinetics are two critical factors that impact the photoelectrochemical (PEC) water splitting performance of the bismuth vanadate (BiVO 4 ) photoanode. Previous studies have demonstrated that doping with rare‐earth elements to induce lattice distortions and loading oxygen evolution reaction (OER) co‐catalysts are effective strategies for enhancing carrier separation capabilities and accelerating the kinetics of the water oxidation reaction. Herein, Cu 2+ ‐doped RuO 2 (Cu‐RuO 2 ) particles are anchored onto rare earth element Thulium (Tm)‐doped BiVO 4 (Tm‐BiVO 4 ) photoanode substrates, constructing an integrated Cu‐RuO 2 ‐Tm‐BiVO 4 photoanode. The newly integrated photoanode not only achieves a photocurrent density of 5.3 mA cm −2 at 1.23 V versus a reversible hydrogen electrode (vs RHE), but also exhibits exceptional stability. A series of detailed physical and chemical characterizations as well as density‐functional theory (DFT) calculations demonstrate that Tm doping induces lattice distortion in BiVO 4 , enhancing the internal electric field and thereby facilitating carrier separation. Moreover, the anchored Cu‐RuO 2 particles not only lattice‐match with the Tm‐BiVO 4 photoanode, reducing interfacial transfer resistance, but also expedite the kinetics of the water oxidation reaction. The profound significance of this work is that it offers a reference for the future design and fabrication of novel integrated photoanodes.    

    

* Vastly Synergistic Fe2CuNiS4‐Nanoarchitectures Anchored 2D‐Nano‐Sandwich Derived from Flower‐Like‐CuFeS2/N‐Graphene and Cube‐Like‐NiFeS2/N‐CNTs for Water Oxidation and Nitrophenol Reduction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400385941
:TOPICS: Catalytic Reduction of Nitro Compounds, Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/eem2.12788")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400385941"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400385941"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400385941"))][Get cited by]]

OpenAlex: https://openalex.org/W4400385941 (Open access: True)
    
[[https://openalex.org/A5087161013][Gopiraman Mayakrishnan]], [[https://openalex.org/A5006365721][V. Ramkumar]], [[https://openalex.org/A5047092365][Junpeng Xiong]], [[https://openalex.org/A5071399825][Muhammad Farooq]], [[https://openalex.org/A5052294693][Azeem Ullah]], [[https://openalex.org/A5100693352][Ke‐Qin Zhang]], [[https://openalex.org/A5086409096][Seong Cheol Kim]], [[https://openalex.org/A5059896592][Ick Soo Kim]], Energy & environment materials. None(None)] 2024. https://doi.org/10.1002/eem2.12788 
     
Surface area, pore properties, synergistic behavior, homogenous dispersion, and interactions between carbon matrix and metal‐nanostructures are the key factors for achieving the better performance of carbon‐metal based (electro)catalysts. However, the traditional hydro‐ or solvothermal preparation of (electro)catalysts, particularly, bi‐ or tri‐metallic nanostructures anchored graphene (G) or carbon nanotubes (CNTs), often pose to poor metal–support interaction, low synergism, and patchy dispersion. At first, bimetallic flower‐like‐CuFeS 2 /NG and cube‐like‐NiFeS 2 /NCNTs nanocomposites were prepared by solvothermal method. The resultant bimetallic nanocomposites were employed to derive the 2D‐nano‐sandwiched Fe 2 CuNiS 4 /NGCNTs‐SW (electro)catalyst by a very simple and green urea‐mediated “mix‐heat” method. The desired physicochemical properties of Fe 2 CuNiS 4 /NGCNTs‐SW such as multiple active sites, strong metal‐support interaction, homogenous dispersion and enhanced surface area were confirmed by various microscopic and spectroscopic techniques. To the best of our knowledge, this is the first urea‐mediated “mix‐heat” method for preparing 2D‐nano‐sandwiched carbon‐metal‐based (electro)catalysts. The Fe 2 CuNiS 4 /NGCNTs‐SW was found to be highly effective for alkaline‐mediated oxygen evolution reaction at low onset potential of 284.24 mV, and the stable current density of 10 mA cm −2 in 1.0 m KOH for 10 h. Further, the Fe 2 CuNiS 4 /NGCNTs‐SW demonstrated excellent catalytic activity in the reduction of 4‐nitrophenol with good k app value of 87.71 × 10 −2 s −1 and excellent reusability over five cycles. Overall, the developed urea‐mediated “mix‐heat” method is highly efficient for the preparation of metal‐nanoarchitectures anchored 2D‐nano‐sandwiched (electro)catalysts with high synergism, uniform dispersion and excellent metal‐support interaction.    

    

* Unraveling the Nature of Local Field Distortion-Induced Dual Electron-Trapping Centers for Efficient Photocatalytic Fuel Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400391718
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124370")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400391718"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400391718"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400391718"))][Get cited by]]

OpenAlex: https://openalex.org/W4400391718 (Open access: False)
    
[[https://openalex.org/A5086954571][Zhenzi Li]], [[https://openalex.org/A5076385576][Teng Gao]], [[https://openalex.org/A5091300678][Hongqi Chu]], [[https://openalex.org/A5103279174][Lijun Liao]], [[https://openalex.org/A5101619658][Xuepeng Wang]], [[https://openalex.org/A5065438243][Liping Guo]], [[https://openalex.org/A5101102446][Yachao Xu]], [[https://openalex.org/A5062192676][Wei Zhou]], Applied catalysis. B, Environmental. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124370 
     
Active electron-trapping centers play significant roles in photocatalysis. Herein, we synergize local field distortion and defects in nanocrystals to produce dual electron-trapping centers and unravel the nature of aluminum doping in porous ZnO with tunable amounts of heteroatoms and oxygen vacancies. The introduced Al atoms in the structural domain induce local field distortion and trigger the movement of Zn2+ from a singlet low spin state to a stable triplet state, resulting in the generation of free carriers trapping centers and optimized electronic energy band structure. Dual active electron-trapping centers of heteroatoms and oxygen vacancies promote the Separation of photo-generated charge carriers and reduce the adsorption energies of H* species. Furthermore, the d-band center of Al-doped ZnO with oxygen vacancies shifts to a higher energy position, thus promoting the adsorption and desorption of hydrogen intermediates and exhibiting 4-fold the photocatalytic H2 efficiency of pristine ZnO. This study provides new insights into the rational design of highly efficient oxide-based photocatalysts toward sustainable solar fuel evolution.    

    

* Direct Observations of Magnetic Reconnections at the Magnetopause of the Martian Mini‐Magnetosphere  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400448066
:TOPICS: Exploration and Study of Mars, Formation and Evolution of the Solar System, Magnetosome Formation in Prokaryotes
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1029/2024gl108880")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400448066"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400448066"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400448066"))][Get cited by]]

OpenAlex: https://openalex.org/W4400448066 (Open access: True)
    
[[https://openalex.org/A5034165272][R. T. Lin]], [[https://openalex.org/A5085605179][S. Y. Huang]], [[https://openalex.org/A5036043864][Zhigang Yuan]], [[https://openalex.org/A5058471962][K. Jiang]], [[https://openalex.org/A5051172910][Honghong Wu]], [[https://openalex.org/A5028168995][Q. Y. Xiong]], Geophysical research letters. 51(13)] 2024. https://doi.org/10.1029/2024gl108880 
     
Abstract While Mars lacks a global intrinsic magnetic field, it does exhibit crustal magnetic anomalies (mostly in its Southern Hemisphere). These crustal magnetic anomalies directly interact with solar wind, which forms a mini‐magnetosphere and a region denoted the mini‐magnetopause. Using magnetic field and plasma measurements from the Mars Atmosphere and Volatile Evolution, we report a novel case of magnetic reconnection at the Martian mini‐magnetopause. In this process, protons and oxygen ions from the Martian atmosphere were accelerated during reconnection and likely escaped along the outflow direction. Magnetic reconnection may occur between the interplanetary magnetic field and crustal magnetic fields at the Martian mini‐magnetopause, which contributes to planetary ion escape, solar wind entering the mini‐magnetosphere and the evolution of magnetic topology in the dayside Martian mini‐magnetosphere.    

    

* Monte Carlo simulations of microdosimetry and radiolytic species production at long time post proton irradiation using GATE and Geant4‐DNA  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400407253
:TOPICS: Particle Therapy for Cancer Treatment, Nuclear Reactor Technology and Development, Scintillation Detector Technology
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/mp.17281")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400407253"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400407253"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400407253"))][Get cited by]]

OpenAlex: https://openalex.org/W4400407253 (Open access: False)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5087632072][Emeline Craff]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5070217555][S. Incerti]], [[https://openalex.org/A5062195470][Charbel Koumeir]], [[https://openalex.org/A5091564591][Vincent Métivier]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5049906273][Lydia Maigne]], Medical physics on CD-ROM/Medical physics. None(None)] 2024. https://doi.org/10.1002/mp.17281 
     
Abstract Background Radiobiological effectiveness of radiation in cancer treatment can be studied at different scales (molecular till organ scale) and different time post irradiation. The production of free radicals and reactive oxygen species during water radiolysis is particularly relevant to understand the fundamental mechanisms playing a role in observed biological outcomes. The development and validation of Monte Carlo tools integrating the simulation of physical, physico‐chemical and chemical stages after radiation is very important to maintain with experiments. Purpose Therefore, in this study, we propose to validate a new Geant4‐DNA chemistry module through the simulation of water radiolysis and Fricke dosimetry experiments on a proton preclinical beam line. Material and methods In this study, we used the GATE Monte Carlo simulation platform (version 9.3) to simulate a 67.5 MeV proton beam produced with the ARRONAX isochronous cyclotron (IBA Cyclone 70XP) at conventional dose rate (0.2 Gy/s) to simulate the irradiation of ultra‐pure liquid water samples and Fricke dosimeter. We compared the depth dose profile with measurements performed with a plane parallel Advanced PTW 34045 Markus ionization chamber. Then, a new Geant4‐DNA chemistry application proposed from Geant4 version 11.2 has been used to assess the evolution of , , , , , , and reactive species along time until 1‐h post‐irradiation. In particular, the effect of oxygen and pH has been investigated through comparisons with experimental measurements of radiolytic yields for and Fe 3+ . Results GATE simulations reproduced, within 4%, the depth dose profile in liquid water. With Geant4‐DNA, we were able to reproduce experimental radiolytic yields 1‐h post‐irradiation in aerated and deaerated conditions, showing the impact of small changes in oxygen concentrations on species evolution along time. For the Fricke dosimeter, simulated G(Fe 3+ ) is 15.97 ± 0.2 molecules/100 eV which is 11% higher than the measured value (14.4 ± 04 molecules/100 eV). Conclusions These results aim to be consolidated by new comparisons involving other radiolytic species, such as or to further study the mechanisms underlying the FLASH effect observed at ultra‐high dose rates (UHDR).    

    

* Evaluation of low-temperature oxidation analysis and the development effect of high-pressure air injection in low-permeability reservoirs  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400512960
:TOPICS: Characterization of Shale Gas Pore Structure, Pore-scale Imaging and Enhanced Oil Recovery, Petroleum Chemistry and Analysis
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3389/feart.2024.1416824")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400512960"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400512960"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400512960"))][Get cited by]]

OpenAlex: https://openalex.org/W4400512960 (Open access: True)
    
[[https://openalex.org/A5100443902][Xinyu Chen]], [[https://openalex.org/A5078956626][Zhongchen Ba]], [[https://openalex.org/A5007953799][Lu Zhang]], [[https://openalex.org/A5027279973][Yuan Gao]], [[https://openalex.org/A5083626954][Yang Zhou]], [[https://openalex.org/A5000991634][Xinrui Li]], Frontiers in earth science. 12(None)] 2024. https://doi.org/10.3389/feart.2024.1416824 
     
In order to solve the problems of conventional water injection development difficulties and low recovery factor in low-permeability reservoirs, the method of high-pressure air drive is adopted to achieve the purpose of reservoir energy enhancement and efficiency improvement. This paper conducted an experimental study on the mechanism of low-temperature oxidation (LTO) for crude oil in the process of high-pressure air flooding, elaborated the relationship between the LTO properties of crude oil and the temperature, pressure, and water saturation of the reservoir, and analyzed the differences in LTO oxygen consumption and oil components under different reaction conditions. In addition, combined with the air flooding physical simulation experiment, the dynamic evolution law of recovery rate in the air flooding process was revealed. Findings from this inquiry indicate that an escalation in the oxidation temperature significantly amplifies the oxygen incorporation reaction within the crude oil matrix. This augmentation in oxidative conditions leads to an uptick in oxygen consumption, which subsequently precipitates a reduction in the lighter fractions of the oxidized oil while enriching its heavier components. Elevated pressures were found to enhance the propensity for the amalgamation of unstable hydrocarbons with oxygen, fostering comprehensive and heterogeneous oxidation reactions. Notably, an excessive presence of water was observed to detrimentally affect the thermal efficacy of crude oil oxidation processes. In the context of low-permeability reservoirs, air injection techniques have emerged as superior in effectuating oil displacement, although an increase in injection pressures has been associated with the phenomenon of gas channeling. Interestingly, adopting a sequential strategy of initiating water flooding before air flooding facilitated the conveyance of high-pressure air via established flushing channels, although it appeared to attenuate the intensity of crude oil oxidation, culminating in an oil recovery efficiency peaking at 51%.    

    

* Cytochrome oxidase requirements in Bordetella reveal insights into evolution towards life in the mammalian respiratory tract  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400408117
:TOPICS: Epidemiology and Pathogenesis of Bacterial Meningitis, RNA Sequencing Data Analysis, Bacterial Physiology and Genetics
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1371/journal.ppat.1012084")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400408117"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400408117"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400408117"))][Get cited by]]

OpenAlex: https://openalex.org/W4400408117 (Open access: True)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5094042890][Alexa R. Spandrio]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5032454867][Sara A. Marlatt]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5050473914][Margaret R. Dedloff]], [[https://openalex.org/A5014527310][Zachary M. Nash]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5027304634][Peggy A. Cotter]], PLOS pathogens. 20(7)] 2024. https://doi.org/10.1371/journal.ppat.1012084 
     
Little is known about oxygen utilization during infection by bacterial respiratory pathogens. The classical Bordetella species, including B . pertussis , the causal agent of human whooping cough, and B . bronchiseptica , which infects nearly all mammals, are obligate aerobes that use only oxygen as the terminal electron acceptor for electron transport-coupled oxidative phosphorylation. B . bronchiseptica , which occupies many niches, has eight distinct cytochrome oxidase-encoding loci, while B . pertussis , which evolved from a B . bronchiseptica -like ancestor but now survives exclusively in and between human respiratory tracts, has only three functional cytochrome oxidase-encoding loci: cydAB1 , ctaCDFGE1 , and cyoABCD1 . To test the hypothesis that the three cytochrome oxidases encoded within the B . pertussis genome represent the minimum number and class of cytochrome oxidase required for respiratory infection, we compared B . bronchiseptica strains lacking one or more of the eight possible cytochrome oxidases in vitro and in vivo . No individual cytochrome oxidase was required for growth in ambient air, and all three of the cytochrome oxidases conserved in B . pertussis were sufficient for growth in ambient air and low oxygen. Using a high-dose, large-volume persistence model and a low-dose, small-volume establishment of infection model, we found that B . bronchiseptica producing only the three B . pertussis -conserved cytochrome oxidases was indistinguishable from the wild-type strain for infection. We also determined that CyoABCD1 is sufficient to cause the same level of bacterial burden in mice as the wild-type strain and is thus the primary cytochrome oxidase required for murine infection, and that CydAB1 and CtaCDFGE1 fulfill auxiliary roles or are important for aspects of infection we have not assessed, such as transmission. Our results shed light on the environment at the surface of the ciliated epithelium, respiration requirements for bacteria that colonize the respiratory tract, and the evolution of virulence in bacterial pathogens.    

    

* Revealing the Limitation Induced by Hydroxyl in Regulating Solvation Structure of Zn2+ and Overcoming Challenges with Hybrid Additives towards Highly Stable Zinc Anodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400431634
:TOPICS: Aqueous Zinc-Ion Battery Technology, Perovskite Solar Cell Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401073")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400431634"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400431634"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400431634"))][Get cited by]]

OpenAlex: https://openalex.org/W4400431634 (Open access: False)
    
[[https://openalex.org/A5100707970][Fuxiang Li]], [[https://openalex.org/A5010477855][Junfeng Yang]], [[https://openalex.org/A5100376911][Minghui Wang]], [[https://openalex.org/A5058640875][Xiang Feng]], [[https://openalex.org/A5073240631][Mingyan Li]], [[https://openalex.org/A5089797668][Hong Zheng]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401073 
     
In the field of electrolyte design for aqueous zinc‐ion batteries (AZIBs), additives containing hydroxyl have been demonstrated to effectively modulate the solvation structure of Zn2+. However, reported studies typically focus solely on the effectiveness of hydroxyl while neglecting the issues that emerge during solvation structure regulation. The strong electron‐attracting capability of Zn2+ attracts electrons from the oxygen in hydroxyl, thereby weakening the strength of hydroxyl, the hydrogen evolution reaction (HER) is also pronounced. This work innovatively reveals the limitation of hydroxyl‐containing additives and proposes a synergistic regulation strategy based on hybrid additives. Arginine with a high isoelectric point is introduced into the electrolyte system containing hydroxyl additives. The protonation effect and electrostatic attraction of arginine enable it to absorb protons at the anode released by the weakened hydroxyl, thereby compensating for the limitation of hydroxyl additives. Under the synergistic action of hybrid additives, the Zn|Zn battery achieved stable deposition/stripping for over 1200 hours under 10 mA cm‐2 and 10 mAh cm‐2. Moreover, the Zn|Cu battery cycled for over 570 hours with a high Coulombic efficiency of 99.82%. This study presents a pioneering perspective for the further application of AZIBs.    

    

* Formation of neutron stars inside planetary nebulae via   accretion-induced collapse and core-merger-induced collapse from white dwarf   binaries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400434169
:TOPICS: Gamma-Ray Bursts and Supernovae Connections, Formation and Evolution of the Solar System, Observation and Study of Gravitational Waves Phenomenon
:PUBLICATION_DATE: 2024-07-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2407.03985")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400434169"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400434169"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400434169"))][Get cited by]]

OpenAlex: https://openalex.org/W4400434169 (Open access: True)
    
[[https://openalex.org/A5033438273][Iminhaji Ablimit]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2407.03985  ([[https://arxiv.org/pdf/2407.03985][pdf]])
     
First, I demonstrate the possible formation channel for neutron stars (NSs) via the accretion-induced collapse (AIC) of oxygen-neon-magnesium (ONeMg) composition white dwarfs (WDs) inside planetary nebulae (PNe; also so-called symbiotic nebulae). A heavy mass loss via the stellar wind or during the the roche-lobe overfilling (RLOF) mass-transfer may happen at the late evolutionary phase of ONeMg WD - red giant (or asymptotic giant branch) star binaries, and it might form nebulae with central accreting WD binaries. The nebulae might be ionized the hot cores of giant stars or accreting WDs. Therefore, the accreting WD inside the symbiotic nebulae might grow in mass to the Chandrasekhar limit mass and collapse. Peculiar NSs born via the AIC of WDs inside the symbiotic nebulae (PNe) may finally have WD companions and become the NS-WD systems, and the Milky Way may contain tens of such kind of systems. Second, I introduce another possibility for the formation of PNe (or pulsar wind nebulae) with newborn NS via the core-merger-induced collapse during the common envelope evolution of ONeMg WD binaries.    

    

* Element abundances of galactic RGB stars in the APO-K2 catalogue.   Dissimilarity in the scaling with [$\alpha$/Fe]  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400484088
:TOPICS: Stellar Astrophysics and Exoplanet Studies, Astronomical Instrumentation and Spectroscopy, Optical 3D Laser Measurement Systems Optimization
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2407.05960")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400484088"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400484088"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400484088"))][Get cited by]]

OpenAlex: https://openalex.org/W4400484088 (Open access: True)
    
[[https://openalex.org/A5051901917][G. Valle]], [[https://openalex.org/A5076825008][M. Dell’Omodarme]], [[https://openalex.org/A5088380880][P. G. Prada Moroni]], [[https://openalex.org/A5054137091][S. Degl’Innocenti]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2407.05960  ([[https://arxiv.org/pdf/2407.05960][pdf]])
     
We conducted an investigation on the chemical abundances of 4,316 stars in the red giant branch (RGB) phase from the recently released APO-K2 catalogue. Our aim was to characterize the abundance trends of the single elements with [$\alpha$/Fe], mainly focusing on C, N, and O, which are the most relevant for the estimation of stellar ages. The chemical analysis of the RGB sample involved cross-matching data from the APO-K2 catalogue with individual element abundances from APOGEE DR17. The analysis detected a statistically significant difference in the [(C+N+O)/Fe] - [$\alpha$/Fe] trend with respect to the simple $\alpha$-enhancement scenario. This difference remained robust across different choices for the reference solar mixture and potential zero-point calibrations of C and N abundances. The primary discrepancy was a steeper increase in [O/Fe] with [$\alpha$/Fe], reaching a 0.1 dex difference at [$\alpha$/Fe] = 0.3. Notably, the impact on the evolutionary timescale of such oxygen over-abundance with respect to the commonly adopted uniform $\alpha$-enhancement is rather limited. We verified that stellar models computed using an ad hoc O-rich mixture sped up the evolution by only 1% at [$\alpha$/Fe] = 0.3, due to the counterbalancing effects of O enrichment on both the evolutionary timescale and the Z-to-[Fe/H] relationship.    

    

* Selective CO2 Photoreduction into CH4 Triggered by the Synergy between Oxygen Vacancy and Ru Substitution under Near‐Infrared Light Irradiation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400449443
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/advs.202405668")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400449443"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400449443"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400449443"))][Get cited by]]

OpenAlex: https://openalex.org/W4400449443 (Open access: True)
    
[[https://openalex.org/A5100361631][Jun Li]], [[https://openalex.org/A5043920428][Xinglong Liu]], [[https://openalex.org/A5020146582][Xi Wu]], [[https://openalex.org/A5028498756][Zhongyi Liu]], [[https://openalex.org/A5033534918][Zaiwang Zhao]], [[https://openalex.org/A5024643475][Yi‐Feng Liu]], [[https://openalex.org/A5028780342][Shi Xue Dou]], [[https://openalex.org/A5050536257][Yao Xiao]], Advanced science. None(None)] 2024. https://doi.org/10.1002/advs.202405668 
     
Abstract Near‐infrared (NIR) light powdered CO 2 photoreduction reaction is generally restricted to the separation efficiency of photogenerated carriers and the supply of active hydrogen (*H). Herein, the study reports a retrofitting hydrogenated MoO 3‐x (H‐MoO 3‐x ) nanosheet photocatalysts with Ru single atom substitution (Ru@H‐MoO 3‐x ) fabricated by one‐step solvothermal method. Experiments together with theoretical calculations demonstrate that the synergistic effect of Ru substitution and oxygen vacancy can not only inhibit the recombination of photogenerated carriers, but also facilitate the CO 2 adsorption/activation as well as the supply of *H. Compared with H‐MoO 3‐x , the Ru@H‐MoO 3‐x exhibit more favorable formation of *CHO in the process of *CO conversion due to the fast *H generation on electron‐rich Ru sites and transfer to *CO intermediates, leading to the preferential photoreduction of CO 2 to CH 4 with high selectivity. The optimized Ru@H‐MoO 3‐x exhibits a superior CO 2 photoreduction activity with CH 4 evolution rate of 111.6 and 39.0 µmol g catalyst −1 under full spectrum and NIR light irradiation, respectively, which is 8.8 and 15.0 times much higher than that of H‐MoO 3‐x . This work provides an in‐depth understanding at the atomic level on the design of NIR responsive photocatalyst for achieving the goal of carbon neutrality.    

    

* Stable Isotopes of Landfast Sea Ice as a Record of La Grande River Under-Ice Plume Dispersal  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400416135
:TOPICS: Arctic Sea Ice Variability and Decline, Impacts of Climate Change on Glaciers and Water Availability, Anaerobic Methane Oxidation and Gas Hydrates
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1139/as-2024-0003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400416135"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400416135"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400416135"))][Get cited by]]

OpenAlex: https://openalex.org/W4400416135 (Open access: True)
    
[[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5076911944][Kaushik Gupta]], [[https://openalex.org/A9999999999][NULL AUTHOR_ID]], [[https://openalex.org/A5023673696][Jens K. Ehn]], Arctic science. None(None)] 2024. https://doi.org/10.1139/as-2024-0003 
     
Vertical profiles of salinity, and isotopic abundance ratios of hydrogen (δ2H ) and oxygen (@delta;18O) of 18 landfast ice cores, collected along the northeast coast of James Bay in March 2019, and one ice core collected in Belcher Islands, were used to obtain the winter timeseries of the spatiotemporal evolution of the under-ice plume of La Grande River (LGR), the dominant river in the area. Variability in the isotopic composition and salinity of the ice cores indicated changes to the water source composition at the ice-water interface when the ice layers formed. The increased presence of river water beneath the ice during January-March was marked by more negative isotopic ratios in the lower portion of the ice as river discharge was increased for hydroelectric production. River water was the source of ~43% of the ice in our ice core samples (n=320) with the interquartile range from 16% to 71%. The river water fractions incorporated into the ice indicate that LGR under-ice plume extended more than 75 km north and at least 30 km south of the river mouth for ~3 months. These findings correspond well with more challenging to obtain hydrographic observations. End-of-winter ice core sampling and analysis for isotopic abundance has potential as a tool to monitor dispersal of LGR discharge into the ice-covered coastal environment.    

    

* Re−Os Isotope and PGE Abundance Systematics of Coast Range Ophiolite Peridotites and Chromitite, California: Insights into Fore-Arc Magmatic Processes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400498125
:TOPICS: Tectonic and Geochronological Evolution of Orogens, Machine Learning for Mineral Prospectivity Mapping, Seismicity and Tectonic Plate Interactions
:PUBLICATION_DATE: 2024-07-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2113/2024/lithosphere_2024_154")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400498125"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400498125"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400498125"))][Get cited by]]

OpenAlex: https://openalex.org/W4400498125 (Open access: True)
    
[[https://openalex.org/A5006242502][Sung Hi Choi]], [[https://openalex.org/A5048580509][Samuel B. Mukasa]], [[https://openalex.org/A5064788534][John W. Shervais]], [[https://openalex.org/A5049608526][I. S. Puchtel]], Lithosphere. 2024(3)] 2024. https://doi.org/10.2113/2024/lithosphere_2024_154 
     
Abstract We report platinum-group element (PGE) and Re concentrations, and Re−Os isotopic data for peridotites and podiform chromitite from the mid-Jurassic Coast Range ophiolite (CRO), California. Our aim is to provide insights into the formation and evolution of the CRO in a fore-arc tectonic setting. The CRO peridotites are divided into two groups: abyssal and supra-subduction zone (SSZ). They have Ir-group PGE concentrations similar to estimates for the primitive mantle and nearly chondritic relative abundances [(Os/Ir)N ≈ 1.1]. Abyssal-type peridotites have slightly subchondritic Pd-group PGE (PPGE)−Re abundances and flat chondrite-normalized patterns, whereas the SSZ-type ones are depleted overall with highly fractionated PPGE−Re patterns. The CRO peridotites have 187Os/188Os values of 0.1188 to 0.1315 (γOs = −8.3 to 1.4) and 187Re/188Os ranging from 0.022 to 0.413. The oxygen fugacity based on the V/Yb ratios of the CRO peridotites is equivalent to the fayalite−magnetite−quartz buffer. The abyssal-type peridotites are residues after ≤5% melting of the primitive upper mantle and represent a remnant of oceanic lithosphere trapped in an SSZ setting but before it was re-melted or modified by subduction processes. The abyssal-type peridotites yield an aluminachron model age of ~1.5 Ga, implying that the CRO mantle had experienced episode(s) of melt extraction before the CRO crust was formed. The SSZ-type peridotites are refractory residues after ~5% to 15% melting. Extraction of fore-arc basalts generated mainly by decompression melting resulted in the SSZ-type peridotites. The chromitite has 187Os/188Os value of 0.1250 (γOs = −3.5) and PGE−Re patterns complementary to that of boninite, indicating a genetic link to fore-arc magmatism.    

    

* A Comprehensive Metallicity Analysis of J0332−3557: Establishing a z ∼ 4 Anchor for Direct Gas Metallicity and C/O Abundance Investigations  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400453327
:TOPICS: Gamma-Ray Bursts and Supernovae Connections, Plasma Physics and Fusion, Astrophysical Studies of Black Holes
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3847/1538-4357/ad4600")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400453327"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400453327"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400453327"))][Get cited by]]

OpenAlex: https://openalex.org/W4400453327 (Open access: True)
    
[[https://openalex.org/A5061673023][Annalisa Citro]], [[https://openalex.org/A5029422172][Danielle A. Berg]], [[https://openalex.org/A5049745927][Dawn K. Erb]], [[https://openalex.org/A5009681773][Matthew W. Auger]], [[https://openalex.org/A5082299044][George D. Becker]], [[https://openalex.org/A5036597377][Bethan L. James]], [[https://openalex.org/A5068738742][Evan D. Skillman]], Astrophysical journal/The Astrophysical journal. 969(2)] 2024. https://doi.org/10.3847/1538-4357/ad4600 
     
Abstract We provide one of the most comprehensive metallicity studies at z ∼ 4 by analyzing the UV/optical Hubble Space Telescope photometry and rest-frame Very Large Telescope (VLT)/FORS2 UV and VLT/XSHOOTER optical spectra of J0332−3557, a gravitationally lensed galaxy magnified by a factor of 20. With a 5 σ detection of the auroral O iii ] λ 1666 line, we are able to derive a direct gas metallicity estimate for our target. We find Z gas  = 12 + log ( O  /  H ) = 8.26 ± 0.06  , which is compatible with an increase of both the gas fraction and the outflow metal loading factor from z ∼ 0 to z ∼ 4. J0332−3557 is the most metal-rich individual galaxy at z ∼ 4 for which the C/O ratio has been measured. We derive a low log(C/O) = −1.02 ± 0.2, which suggests that J0332−3557 is in the early stages of interstellar medium carbon enrichment driven mostly by massive stars. The low C/O abundance also indicates that J0332−3557 is characterized by a low star formation efficiency, higher yields of oxygen, and longer burst duration. We find that EW C III ]1906,9 is as low as ∼3 Å, and the main drivers of the low EW C III ]1906,9 are the higher gas metallicity and the low C/O abundance. J0332−3557 is characterized by one diffuse and two more compact regions ∼1 kpc in size. We find that the carbon emission mostly originates in the compact knots. Our study on J0332−3557 serves as an anchor for studies investigating the evolution of metallicity and C/O abundance across different redshifts.    

    

* Hierarchical Modeling of the Local Reaction Environment in Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400469170
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-07-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-t37bp-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400469170"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400469170"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400469170"))][Get cited by]]

OpenAlex: https://openalex.org/W4400469170 (Open access: False)
    
[[https://openalex.org/A5084794187][Xinwei Zhu]], [[https://openalex.org/A5052713328][Jun Huang]], [[https://openalex.org/A5054676737][Michael Eikerling]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-t37bp-v2 
     
Electrocatalytic reactions, such as oxygen reduction/evolution reactions and CO2 reduction reaction that are pivotal for the energy transition, are multi-step processes that occur in a nanoscale electric double layer (EDL) at a solid-liquid interface. Conventional analyses based on the Sabatier principle, using binding energies or effective electronic structure properties such as the d-band center as descriptors, are able to grasp overall trends in catalytic activity in specific groups of catalysts. However, thermodynamic approaches often fail to account for a plethora of electrolyte effects that arise in the EDL, including pH, cation, and anion effects. These effects have been observed to exert strong impacts on electrocatalytic reactions. There is growing consensus that the local reaction environment (LRE) prevailing in the EDL is the key to deciphering these complex and hitherto perplexing electrolyte effects. Increasing attention is thus paid to designing appropriate electrolytes, positioning the LRE at center stage. To this end, unraveling the LRE is becoming essential for designing electrocatalysts with specifically tailored properties, which could enable much needed breakthroughs in electrochemical energy science. Theory and modeling are getting more and more important and powerful in addressing this multifaceted problem that involves physical phenomena at different scales and interacting in a multidimensional parametric space. Theoretical models developed for this purpose should treat intrinsic multistep kinetics of electrocatalytic reactions, EDL effects from sub-nm scale to the scale of 10 nm, and mass transport phenomena bridging scales from < 0.1 to 100 μm. Given the diverse physical phenomena and scales involved, it is evident that the challenge at hand surpasses the capabilities of any single theoretical or computational approach. In this Account, we present a hierarchical theoretical framework to address the above challenge. It seamlessly integrates several modules: (i) microkinetic modelling that accounts for various reaction pathways; (ii) an LRE model that describes the interfacial region extending from the nanometric EDL continuously to the solution bulk; (iii) first-principles calculations that provide parameters, e.g., adsorption energies, activation barriers and EDL parameters. The microkinetic model considers all elementary steps without designating an a priori rate-determining step. The kinetics of these elementary steps are expressed in terms of local concentrations, potential and electric field that are co-determined by EDL charging and mass transport in the LRE model. Vital insights on electrode kinetic phenomena, i.e., potential-dependent Tafel slopes, cation effects, and pH effects, obtained from this hierarchical framework are then reviewed. Finally, an outlook on further improvement of the model framework is presented, in view of recent developments in first-principles based simulation of electrocatalysis, observations of dynamic reconstruction of catalysts, and machine-learning assisted computational simulations.    

    
