#+TITLE: water splitting
Description: water splitting papers
Created on Tue Oct  1 01:27:10 2024

Found 23 results from 2024-09-24 to 2024-10-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Tuning electronic structure of cobaltous nitride-manganous oxide heterojunction by N-vacancy engineering for optimizing oxygen electrocatalysis activity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402757307
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nanoen.2024.110294")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402757307"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402757307"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402757307"))][Get cited by]]

OpenAlex: https://openalex.org/W4402757307 (Open access: False)
    
[[https://openalex.org/A5032756107][Xiaoqin Xu]], [[https://openalex.org/A5006901660][Tianmi Tang]], [[https://openalex.org/A5077435969][Guiru Zhang]], [[https://openalex.org/A5074571254][Jingqi Guan]], Nano Energy. None(None)] 2024. https://doi.org/10.1016/j.nanoen.2024.110294 
     
No abstract    

    

* Advances in Stability of NiFe‐Based Anodes toward Oxygen Evolution Reaction for Alkaline Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402781797
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202406075")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402781797"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402781797"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402781797"))][Get cited by]]

OpenAlex: https://openalex.org/W4402781797 (Open access: False)
    
[[https://openalex.org/A5017584765][Weiming Song]], [[https://openalex.org/A5050889666][Chenfeng Xia]], [[https://openalex.org/A5066262857][Shahid Zaman]], [[https://openalex.org/A5032988244][Shenghua Chen]], [[https://openalex.org/A5049259092][Chunhui Xiao]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202406075 
     
Abstract Alkaline electrolysis plays a crucial role in sustainable energy solutions by utilizing electrolytic cells to produce hydrogen gas, providing a clean and efficient method for energy storage and conversion. Efficient, stable, and low‐cost electrocatalysts for the oxygen evolution reaction (OER) are essential to facilitate alkaline water electrolysis on a commercial scale. Nickel‐iron‐based (NiFe‐based) transition metal electrocatalysts are considered the most promising non‐precious metal catalysts for alkaline OER due to their low cost, abundance, and tunable catalytic properties. Nevertheless, the majority of existing NiFe‐based catalysts suffer from limited activity and poor stability, posing a significant challenge in meeting industrial applications. This also highlights a common situation where the emphasis on material activity receives significant attention, while the equally critical stability aspect is often underemphasized. Initiating with a comprehensive exploration of the stability of NiFe‐based OER materials, this article first summarizes the debate surrounding the determination of active sites in NiFe‐based OER electrocatalysts. Subsequently, the degradation mechanisms of recently reported NiFe‐based electrocatalysts are outlined, encompassing assessments of both chemical and mechanical endurance, along with essential approaches for enhancing their stability. Finally, suggestions are put forth regarding the essential considerations for the design of NiFe‐based OER electrocatalysts, with a focus on heightened stability.    

    

* Electrocatalytic activity of La0.6Sr0. 4Co1-yCuyO3 (y = 0.1, 0.2, and 0.3) for oxygen evolution in an alkaline medium at 25℃  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402782270
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.56042/ijc.v63i9.10838")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402782270"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402782270"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402782270"))][Get cited by]]

OpenAlex: https://openalex.org/W4402782270 (Open access: False)
    
, Indian Journal of Chemistry. 63(9)] 2024. https://doi.org/10.56042/ijc.v63i9.10838 
     
No abstract    

    

* Construction of a Highly Efficient MoS2-Based Composite Electrocatalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402785987
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cy00923a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402785987"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402785987"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402785987"))][Get cited by]]

OpenAlex: https://openalex.org/W4402785987 (Open access: False)
    
[[https://openalex.org/A5037395563][Mengyan Huang]], [[https://openalex.org/A5084816463][Bo Liu]], [[https://openalex.org/A5100392071][Wei Wang]], [[https://openalex.org/A5082733809][Junfeng Gu]], [[https://openalex.org/A5020656663][Yichen Zheng]], [[https://openalex.org/A5078466458][Peiyan Ma]], [[https://openalex.org/A5100365152][Bin Li]], [[https://openalex.org/A5019325306][Zhengyi Fu]], Catalysis Science & Technology. None(None)] 2024. https://doi.org/10.1039/d4cy00923a 
     
Molybdenum disulfide (MoS2) has great potential for the catalysis of the oxygen evolution reaction (OER) due to its suitable valence band edge. However, the high adsorption energy barriers of the...    

    

* Is the oxygen plasma cleaning technique indicated for any electrochemical purpose?: the case of FTO electrodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402826225
:TOPICS: Gas Sensing Technology and Materials, Emergent Phenomena at Oxide Interfaces, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.145149")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402826225"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402826225"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402826225"))][Get cited by]]

OpenAlex: https://openalex.org/W4402826225 (Open access: False)
    
[[https://openalex.org/A5036260904][P. Dı́az]], [[https://openalex.org/A5033799834][G. Riveros]], [[https://openalex.org/A5010398068][Martín Faúndez]], [[https://openalex.org/A5076825992][A. Enrique Caballero]], [[https://openalex.org/A5104241356][Rodrigo Wittwer]], [[https://openalex.org/A5100775158][F. Martı́n]], [[https://openalex.org/A5057645379][Cecilia Silva Cabrera]], [[https://openalex.org/A5044679612][Daniel Gau]], [[https://openalex.org/A5029884189][Enrique A. Dalchiele]], [[https://openalex.org/A5086262723][Ricardo E. Marotti]], [[https://openalex.org/A5064016258][Daniel Ramírez]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.145149 
     
No abstract    

    

* Hierarchical (Ni,Co)0.85Se Sheets for Efficient Oxygen Evolution Reaction Electrocatalysis: A Combined Approach of Fabrication Control and Mechanistic Understanding  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402837050
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cc04285a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402837050"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402837050"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402837050"))][Get cited by]]

OpenAlex: https://openalex.org/W4402837050 (Open access: True)
    
[[https://openalex.org/A5038572377][Muhammad Sohail Riaz]], [[https://openalex.org/A5102552076][Qirui Huang]], [[https://openalex.org/A5067865085][Jingjing Duan]], [[https://openalex.org/A5100320997][Sheng Chen]], [[https://openalex.org/A5021679611][Fuqiang Huang]], [[https://openalex.org/A5045920682][Pedro F. Costa]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d4cc04285a 
     
We present a fabrication process for hierarchical (Ni,Co)0.85Se sheets, achieving efficient oxygen evolution reaction (OER) activity with a 10 mA cm−2 current density at an overpotential of 290 mV. Porous...    

    

* Development of Potential Electrocatalyst: Highly Multiporous WO3–rGO Nanocomposites for Enhancing Electrocatalytic Oxygen Evolution Reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402839871
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/slct.202402770")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402839871"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402839871"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402839871"))][Get cited by]]

OpenAlex: https://openalex.org/W4402839871 (Open access: False)
    
[[https://openalex.org/A5065182369][Aniruddha Mondal]], [[https://openalex.org/A5102129485][P. C. Srivastava]], [[https://openalex.org/A5102662903][Anand Prakash Singh]], [[https://openalex.org/A5023573813][Amanullah Fatehmulla]], [[https://openalex.org/A5057222563][Kotesh Kumar Mandari]], ChemistrySelect. 9(36)] 2024. https://doi.org/10.1002/slct.202402770 
     
Abstract The development of sustainable energy technologies, such as fuel cells and metal–air batteries, necessitates the use of a highly efficient electrocatalyst for the oxygen evolution process. The fabrication of WO 3 –rGO nanocomposites results in the formation of a multiporous nanostructure. The catalytic activity of highly multiporous WO 3 –rGO nanocomposites containing multiporous nanostructures is shown to be significant. The catalyst has the potential to facilitate highly reactive anodic oxygen reactions, hence augmenting the synergistic impact of interfacial charge transfer and the porous structure of WO 3 –rGO nanocomposites. The findings of this work indicate that the use of WO 3 –rGO nanocomposites as electrocatalysts exhibits a considerable overpotential value of 350 mV, a Tafel slope of 67 mV dec −1 , good stability, roughness factor, and turnover frequency for the process of oxygen evolution in real‐world scenarios.    

    

* Studies on Porous Nanostructured Palladium–Cobalt–Silica as Heterogeneous Catalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402840311
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1134/s1023193524700344")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402840311"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402840311"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402840311"))][Get cited by]]

OpenAlex: https://openalex.org/W4402840311 (Open access: False)
    
[[https://openalex.org/A5004790787][P.C. Pándey]], [[https://openalex.org/A5060337259][Chetna Singh]], Russian Journal of Electrochemistry. 60(9)] 2024. https://doi.org/10.1134/s1023193524700344 
     
No abstract    

    

* Iridium Single‐Atom‐Ensembles Stabilized on Mn‐Substituted Spinel Oxide for Durable Acidic Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402851866
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202401648")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402851866"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402851866"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402851866"))][Get cited by]]

OpenAlex: https://openalex.org/W4402851866 (Open access: True)
    
[[https://openalex.org/A5104651189][Ashwani Kumar]], [[https://openalex.org/A5042194356][Marcos Gil‐Sepulcre]], [[https://openalex.org/A5104652264][Jinsun Lee]], [[https://openalex.org/A5066821118][Viet Q. Bui]], [[https://openalex.org/A5100372012][Yue Wang]], [[https://openalex.org/A5053491539][Serena DeBeer]], [[https://openalex.org/A5100383157][Min Gyu Kim]], [[https://openalex.org/A5053491539][Serena DeBeer]], [[https://openalex.org/A5060841613][Harun Tüysüz]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202401648 
     
Abstract Exploring single‐atom‐catalysts for the acidic oxygen evolution reaction (OER) is of paramount importance for cost‐effective hydrogen production via acidic water electrolyzers. However, the limited durability of most single‐atom‐catalysts and Ir/Ru‐based oxides under harsh acidic OER conditions, primarily attributed to excessive lattice oxygen participation resulting in metal‐leaching and structural collapse, hinders their practical application. Herein, an innovative strategy is developed to fabricate short‐range Ir single‐atom‐ensembles (Ir SAE ) stabilized on the surface of Mn‐substituted spinel Co 3 O 4 (Ir SAE ‐CMO), which exhibits excellent mass activity and significantly improved durability (degradation‐rate: ≈2 mV h −1 ), outperforming benchmark IrO 2 (≈44 mV h −1 ) and conventional Ir single‐atoms on pristine‐Co 3 O 4 for acidic OER. First‐principle calculations reveal that Mn‐substitution in the octahedral sites of Co 3 O 4 substantially reduces the migration energy barrier for Ir single‐atoms on the CMO surface compared to pristine‐Co 3 O 4 , facilitating the migration of Ir single‐atoms to form strongly correlated Ir SAE during pyrolysis. Extensive ex situ characterization, operando X‐ray absorption and Raman spectroscopies, pH‐dependence activity tests, and theoretical calculations indicate that the rigid Ir SAE with appropriate Ir–Ir distance stabilized on the CMO surface effectively suppresses lattice oxygen participation while promoting direct O─O radical coupling, thereby mitigating Ir‐dissolution and structural collapse, boosting the stability in an acidic environment.    

    

* Regular-Hexahedron-Shaped Ion-Copper Bimetallic Oxides Engineered on the Plasma-Treated Ion Foam for a Highly Efficient Oxygen Evolution in an Alkaline Medium  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402909219
:TOPICS: Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4970079")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402909219"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402909219"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402909219"))][Get cited by]]

OpenAlex: https://openalex.org/W4402909219 (Open access: False)
    
[[https://openalex.org/A5100653663][Ziyan Wang]], [[https://openalex.org/A5075691386][GL Chen]], [[https://openalex.org/A5030276265][Yingchun Guo]], [[https://openalex.org/A5011836927][Tongtong Li]], [[https://openalex.org/A5101847546][Bin He]], [[https://openalex.org/A5101183210][Peisong Tang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4970079 
     
No abstract    

    

* Discarded Pen Spring-Supported Cobalt-Based Metal–Organic Framework Catalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402914247
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Electrocatalysis for Energy Conversion, Polyoxometalate Clusters and Materials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4969832")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402914247"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402914247"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402914247"))][Get cited by]]

OpenAlex: https://openalex.org/W4402914247 (Open access: False)
    
[[https://openalex.org/A5069143959][Chandra Sekhar S]], [[https://openalex.org/A5073939122][Bhimanaboina Ramulu]], [[https://openalex.org/A5064322163][Junied Arbaz Junied Shaik]], [[https://openalex.org/A5103079949][Jae Su Yu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4969832 
     
No abstract    

    

* Theoretical Insights into Electrocatalytic Oxygen Evolution on Se-Doped TiO2  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402921973
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.4c04841")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402921973"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402921973"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402921973"))][Get cited by]]

OpenAlex: https://openalex.org/W4402921973 (Open access: False)
    
[[https://openalex.org/A5020813934][Niranji Thilini Ekanayake]], [[https://openalex.org/A5082330744][Nicholas J. Mosey]], The Journal of Physical Chemistry C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.4c04841 
     
No abstract    

    

* Unlocking Oxygen Evolution: The Impact of Hetero Atom Doping on NiFe-Based Pre-Catalysts and Their Transformation into Ultrathin Layered Double Hydroxides  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402939337
:TOPICS: Catalytic Nanomaterials, Desulfurization Technologies for Fuels, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-09-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21275/sr24924124936")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402939337"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402939337"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402939337"))][Get cited by]]

OpenAlex: https://openalex.org/W4402939337 (Open access: True)
    
[[https://openalex.org/A5100444524][Manoj Kumar]], [[https://openalex.org/A5104333422][Raghvendra Singh]], International Journal of Science and Research (IJSR). 13(9)] 2024. https://doi.org/10.21275/sr24924124936 
     
No abstract    

    

* Dual-Phase Microstructure Ptnicumnmo High-Entropy Alloys as High-Performance for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402746430
:TOPICS: Electrocatalysis for Energy Conversion, Atom Probe Tomography Research, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4964821")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402746430"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402746430"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402746430"))][Get cited by]]

OpenAlex: https://openalex.org/W4402746430 (Open access: False)
    
[[https://openalex.org/A5008386681][Fang Miao]], [[https://openalex.org/A5018279936][Wu Wei]], [[https://openalex.org/A5100392899][Bin Zhang]], [[https://openalex.org/A5100392899][Bin Zhang]], [[https://openalex.org/A5101823422][Tao Gu]], [[https://openalex.org/A5014086269][Zhijie Yan]], [[https://openalex.org/A5035203534][Xiubing Liang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4964821 
     
No abstract    

    

* Influence of Fe Ions on Anode Performance and the Mechanism of Action during Copper Electrowinning Process  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402862201
:TOPICS: Electrodeposition and Composite Coatings, Corrosion Inhibitors and Protection Mechanisms, Fabrication and Applications of Porous Alumina Membranes
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29194578")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402862201"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402862201"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402862201"))][Get cited by]]

OpenAlex: https://openalex.org/W4402862201 (Open access: True)
    
[[https://openalex.org/A5101670869][Cheng Jiang]], [[https://openalex.org/A5057398611][Yiwen Chen]], [[https://openalex.org/A5100294720][Yingping Zhou]], [[https://openalex.org/A5103040526][Buming Chen]], [[https://openalex.org/A5058859579][Hui Huang]], [[https://openalex.org/A5034234163][Jun Guo]], [[https://openalex.org/A5016808025][Ruidong Xu]], [[https://openalex.org/A5103655859][Guo Zhong-cheng]], Molecules. 29(19)] 2024. https://doi.org/10.3390/molecules29194578 
     
The performance of the anode varies from the impurity ions in the copper electrowinning process. This work focused on the variation of the electrochemical behavior of the Pb-0.06%Ca-1.2%Sn anode as the Fe ions (Fe3+ and/or Fe2+) existed in the electrolyte by electrochemical characterization. Copper electrodeposition experiments were conducted under a current density of 300 A/m2, with the Fe ion concentration in the electrolyte controlled within the range of 0 to 20 g/L and the Cu ion concentration maintained at 45 g/L at a temperature of 45 °C. The variation in the corrosion resistance, catalytic activity, and structural composition of the anode film layer was analyzed in-depth according to the presence of Fe ions. The results show that the structure of PbO2 on the surface of the film was changed as Fe ions doped into the anode film, and the oxygen evolution activity of the anode was also improved. However, the corrosion resistance decreased with increasing Fe3+ concentration. Furthermore, the addition of 2 g/L Fe2+ in the electrolyte containing 2 g/L Fe3+ led to an elevation in the corrosion resistance of the anode to some extent and further increased the oxygen evolution activity.    

    

* Plasma‐electrified synthesis of atom‐efficient electrocatalysts for sustainable water catalysis and beyond  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402786968
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400899")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402786968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402786968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402786968"))][Get cited by]]

OpenAlex: https://openalex.org/W4402786968 (Open access: False)
    
[[https://openalex.org/A5050157867][M. Gimhani N. Perera]], [[https://openalex.org/A5003540204][Mitchell Barclay]], [[https://openalex.org/A5013359536][Kostya Ostrikov]], [[https://openalex.org/A5010681017][Jennifer MacLeod]], [[https://openalex.org/A5036319813][Anthony P. O’Mullane]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400899 
     
The downsizing of metal structures to the nano and atomic level, thereby creating nanoparticle catalysts (NPCs), sub‐nanometer cluster catalysts (SNCCs) or single atom catalysts (SACs), has gained significant interest. In particular, synthesizing these types of catalysts using low temperature plasma electrified methods is an emerging field which is highly applicable to electrochemical water splitting for the sustainable production of green hydrogen. Surface modification via plasma treatment provides a route for nanoparticle immobilization or single atom trapping which ensures high atom utilization during electrolysis reactions. Plasma can also be used to create NPCs, SNCCs and SACs from various precursors as well as modify their surface properties once formed which impacts significantly on the oxygen evolution reaction and hydrogen evolution reaction. Therefore, in this review we emphasize the role that low temperature plasma electrified synthetic strategies play in electrocatalyst development for water splitting reactions and explore the crucial relationship between the electronic and coordination environment of atom efficient catalysts and their resulting catalytic activity. We also discuss methods to characterize these types of catalysts and the possibility for scaling up this technology which will be required for commercial applications.    

    

* Engineering Amorphous/Crystalline Nanoflower Heterostructures for Enhanced Electrocatalytic Acidic Water Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402962724
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202401472")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402962724"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402962724"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402962724"))][Get cited by]]

OpenAlex: https://openalex.org/W4402962724 (Open access: False)
    
[[https://openalex.org/A5027181760][Rong Cao]], [[https://openalex.org/A5101752894][Chang Liu]], [[https://openalex.org/A5100385169][Bowen Zhang]], [[https://openalex.org/A5078414235][Jun Liang]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202401472 
     
Efficient water electrolysis for green hydrogen production relies on the development of robust oxygen evolution reaction (OER) catalysts, particularly for acidic environments. This study introduces amorphous/crystalline Mn‐Ru binary oxides nanoflowers (a/c‐Mn0.9Ru0.1O2) as a promising acidic OER catalyst, synthesized via a two‐step phase engineering approach. The optimized a/c‐ Mn0.9Ru0.1O2‐200 composition exhibits exceptional OER activity, requiring a low overpotential of 168 mV to achieve a current density of 10 mA/cm2 and demonstrating remarkable stability over 28 hours. This significantly outperforms commercial RuO2 catalysts, which require an overpotential of 320 mV at 10 mA/cm2 and exhibit a stability of only 0.5 h under identical conditions. X‐ray absorption spectroscopy (XAS) and X‐ray photoelectron spectroscopy (XPS) analysis results reveals the formation of Mn‐O‐Ru linkages and an optimized d‐band electronic structure, attributed to strong electronic coupling at the amorphous/crystalline interface. This unique architecture promotes optimal adsorption/desorption of OER intermediates, leading to enhanced catalytic performance. This study offers a novel strategy for the rational design and production of efficient acidic OER catalysts.    

    

* Geobiology: When did animals develop their oxygen habit?  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402737899
:TOPICS: Climate Change and Paleoclimatology, Paleoredox and Paleoproductivity Proxies, Marine Biodiversity and Ecosystem Functioning
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cub.2024.08.024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402737899"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402737899"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402737899"))][Get cited by]]

OpenAlex: https://openalex.org/W4402737899 (Open access: False)
    
[[https://openalex.org/A5080454473][Philip C. J. Donoghue]], [[https://openalex.org/A5049646665][Lewis Alcott]], Current Biology. 34(18)] 2024. https://doi.org/10.1016/j.cub.2024.08.024 
     
The rise of ocean oxygen levels is thought to have boosted the evolution of animals. Modelling of the sedimentary geochemical record provides evidence for a late Ediacaran rise in oxygen, though likely after the origin of animals.    

    

* Topological Protection of Oxygen Redox in Li-Rich Cathodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402885847
:TOPICS: Lithium-ion Battery Technology, Lithium Battery Technologies, Lithium-ion Battery Management in Electric Vehicles
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.4c01929")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402885847"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402885847"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402885847"))][Get cited by]]

OpenAlex: https://openalex.org/W4402885847 (Open access: False)
    
[[https://openalex.org/A5000755101][Zhefeng Chen]], [[https://openalex.org/A5100459852][Wentao Zhang]], [[https://openalex.org/A5021329144][Shunning Li]], [[https://openalex.org/A5055477551][Feng Pan]], The Journal of Physical Chemistry Letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.4c01929 
     
Lithium-rich layered oxides (LRLOs) are regarded as promising candidates for next-generation cathode materials because of their high energy density derived from anionic redox activity. Recent years have seen increasing efforts in promoting the cyclability of LRLO cathodes, at the core of which is the suppression of irreversible internal structural evolution during cycling. The present article aims to provide an informative perspective on the materials design strategies related to the issue of oxygen release. Emphasis is placed on the underlying chemistry of oxygen redox in LRLOs and the strategies based on material topology that can mitigate oxygen migration to the cathode surface. We speculate that these insights could guide researchers in developing high-capacity cathodes with intrinsically high reversibility of oxygen redox.    

    

* Contribution of astrophysical events to the chemical evolution of a dwarf irregular galaxy  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402901438
:TOPICS: Gamma-Ray Bursts and Supernovae Connections, Astronomical Instrumentation and Spectroscopy, Galaxy Formation and Evolution in the Universe
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/mnras/stae2210")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402901438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402901438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402901438"))][Get cited by]]

OpenAlex: https://openalex.org/W4402901438 (Open access: True)
    
[[https://openalex.org/A5037153574][Nao Fukagawa]], [[https://openalex.org/A5009865919][Nikos Prantzos]], Monthly Notices of the Royal Astronomical Society. None(None)] 2024. https://doi.org/10.1093/mnras/stae2210 
     
Abstract We study the contribution of various astrophysical events (AGB stars, core collapse and thermonuclear supernovae, neutron star mergers and collapsars) to the abundances of elements both up to and heavier than the iron peak in a Local Group dwarf irregular galaxy, Wolf-Lundmark-Melotte. Its star formation history has been recently determined by observations with the JWST and we use it to estimate the occurrence of the astrophysical sources. The rates of the gas accretion and the outflow are roughly determined based on the stellar metallicity distribution, the oxygen abundance of HII regions and the gas fraction. As discussed in the literature, the difference in time-scales on which the astrophysical events release the nucleosynthesis products is seen in the occurrence of the events and the evolution of abundance ratios. WLM has an extended star formation history and massive stars are recently and currently formed. Thus, the contribution of rotating massive stars through the weak s-process appears in the abundance ratios of light trans-iron elements to iron at later time of the evolution.    

    

* Buoyancy regulation in insects  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402837241
:TOPICS: Metabolic Theory of Ecology and Climate Change Impacts, Impacts of Crayfish Invasions on Freshwater Ecosystems, Cephalopod Biology and Behavior
:PUBLICATION_DATE: 2024-09-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1152/physiol.00017.2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402837241"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402837241"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402837241"))][Get cited by]]

OpenAlex: https://openalex.org/W4402837241 (Open access: False)
    
[[https://openalex.org/A5014279653][Philip G. D. Matthews]], Physiology. None(None)] 2024. https://doi.org/10.1152/physiol.00017.2024 
     
Multiple insect lineages have successfully reinvaded the aquatic environment, evolving to complete either part or all of their life cycle submerged in water. While these insects vary in their reliance on atmospheric oxygen, with many having the ability to extract dissolved oxygen directly from the water, all retain an internal air-filled respiratory system, their tracheal system, due to their terrestrial origins. However, carrying air within their tracheal system, and even augmenting this volume with additional air bubbles carried on their body, dramatically increases their buoyancy which can make it challenging to remain submerged. But by manipulating this air volume a few aquatic insects can deliberately alter or regulate their position in the water column. Unlike cephalopods and teleost fish that control the volume of gas within their hydrostatic organs by either using osmosis to pull liquid from a rigid chamber or secreting oxygen at high pressure to inflate a flexible chamber, insects have evolved hydrostatic control mechanisms that rely either on the temporary stabilization of a compressible air-bubble volume using O 2 unloaded from hemoglobin, or the mechanical expansion and contraction of a gas-filled volume with rigid, gas-permeable walls. The ability to increase their buoyancy while submerged separates aquatic insects from the buoyancy compensation achieved by other air-breathing aquatic animals which also use air within their respiratory systems to offset their submerged weight. The mechanisms they have evolved to achieve this are unique and provide new insights into the function and evolution of mechanochemical systems.    

    

* Integrating Gen AI and Adaptive AI for Enterprise Solutions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402798801
:TOPICS: Impact of Big Data Analytics on Business Performance, Workflow Mining and Business Process Management, Collaborative Networks in Manufacturing and Organizations
:PUBLICATION_DATE: 2022-03-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.47363/jaicc/2022(1)e146")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402798801"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402798801"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402798801"))][Get cited by]]

OpenAlex: https://openalex.org/W4402798801 (Open access: False)
    
[[https://openalex.org/A5093687887][Chalamayya Batchu -]], [[https://openalex.org/A5093687888][Veera Venkt Satya -]], Journal of Artificial Intelligence & Cloud Computing. None(None)] 2022. https://doi.org/10.47363/jaicc/2022(1)e146 
     
Artificial Intelligence has revolutionized so much that it is influenced into our lives through all day-to-day objects such as phones, IoT objects and other technologies. In the evolution of AI two ground breaking technologies are making a huge impact, Generative AI and Adaptive AI. These technologies can groom the current AI by giving future scope in various domains of digital transformation. When Gen AI is like oxygen in AI as can learn pattern and relationship in a data set well enough to create unique images, text, audio, and video that still adhere to the underlying pattern. Adaptive AI is another emerging field of AI that seek to create intelligent systems to adapt changing circumstances and learning new circumstances. It's so flexible that it is capable of modifying the behavior in response to new information as changes are required in the environment. This paper focus on benefits and scope of integrating both technologies Gen AI and Adaptive AI for the enterprise solutions.    

    

* The impact of third dredge-up on the mass loss of Mira variables  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402741296
:TOPICS: Global Sea Level Variability and Change, Stellar Astrophysics and Exoplanet Studies, Gamma-Ray Bursts and Supernovae Connections
:PUBLICATION_DATE: 2024-09-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1051/0004-6361/202451708")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402741296"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402741296"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402741296"))][Get cited by]]

OpenAlex: https://openalex.org/W4402741296 (Open access: False)
    
[[https://openalex.org/A5034228152][S. Uttenthaler]], [[https://openalex.org/A5043376163][S. Shetye]], [[https://openalex.org/A5049948382][Ambra Nanni]], [[https://openalex.org/A5001982498][B. Aringer]], [[https://openalex.org/A5071231803][Kimmo Eriksson]], [[https://openalex.org/A5042448109][Iain McDonald]], [[https://openalex.org/A5033307604][D. Gobrecht]], [[https://openalex.org/A5042322402][S. Höfner]], [[https://openalex.org/A5068931961][U. Wolter]], [[https://openalex.org/A5017645314][S. Cristallo]], [[https://openalex.org/A5057395448][Klaus Bernhard]], Astronomy and Astrophysics. None(None)] 2024. https://doi.org/10.1051/0004-6361/202451708 
     
The details of the mass-loss process in the late stages of low- and intermediate-mass stellar evolution are not well understood, in particular its dependence on stellar parameters. Mira variables are highly suitable targets for studying this mass-loss process. Here, we follow up on our earlier finding that a near-to-mid-infrared (NIR-MIR) colour versus\ pulsation period diagram shows two sequences of Miras that can be distinguished by the third dredge-up (3DUP) indicator technetium in those stars. While IR colours are good indicators of the dust mass-loss rate (MLR) from Miras, no corresponding sequences have been found using the gas MLR. However, investigations of the gas MLR have been hampered by data limitations. We aim to alleviate these limitations with new observational data. We present new optical spectra of a well-selected sample of Miras. We searched these spectra for absorption lines of Tc and other 3DUP indicators, and combine our findings with gas MLRs and expansion velocities from the literature. Furthermore, we extend the analysis of the MIR emission to WISE data and compare the broadband spectral energy distributions (SEDs) of Miras with and without Tc. We find no systematic difference in gas MLRs between Miras with and without Tc. However, the gas envelopes of Tc-poor Miras appear to have a higher terminal expansion velocity than those of Miras with Tc. Furthermore, our analysis of the IR photometry strongly corroborates the earlier finding that Tc-poor Miras have a higher MIR emission than Tc-rich ones, by as much as a factor of two. We model the IR colours with DARWIN and stationary wind models and conclude that Miras with and without Tc have different dust content or dust properties. We discuss several hypotheses and interpretations of the observations and conclude that the reduction of free oxygen by 3DUP of carbon and iron-depleted dust grains in Tc-rich stars are the most convincing explanations for our observations.    

    
