#+TITLE: water splitting
Description: water splitting papers
Created on Thu Mar 14 00:43:15 2024

Found 40 results from 2024-03-07 to 2024-03-14
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Special atmosphere annealed Co3O4 bifunctional catalysts with oxygen defects for high-efficient water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392499848
:TOPICS: Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159839")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392499848"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392499848"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392499848"))][Get cited by]]

OpenAlex: https://openalex.org/W4392499848 (Open access: False)
    
[[https://openalex.org/A5053936942][Feifei Chen]], [[https://openalex.org/A5049743062][Rui Zhang]], [[https://openalex.org/A5064222660][Yong Zhang]], [[https://openalex.org/A5078300548][Xiaoya Hao]], [[https://openalex.org/A5083446235][Yingda Liu]], [[https://openalex.org/A5058507468][Meiqin Xu]], [[https://openalex.org/A5083679415][Chang Q. Sun]], [[https://openalex.org/A5007697593][Yangfan Song]], [[https://openalex.org/A5053941379][Guozhu Gao]], [[https://openalex.org/A5029766000][Hong Dong]], [[https://openalex.org/A5070289331][Feng Lu]], [[https://openalex.org/A5091145763][Weihua Wang]], [[https://openalex.org/A5044301848][Hui Liu]], [[https://openalex.org/A5005485326][Yahui Cheng]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159839 
     
Electrochemical water splitting is widely recognized as an economical and sustainable method for producing high-purity hydrogen using renewable energy sources. Herein, we prepared 3D urchin-like sphere structures of Co3O4 to serve as an excellent bifunctional catalyst for overall water splitting. Different Co3O4 samples were directly synthesized on Ni foam through hydrothermal and annealing processes under various atmospheric conditions, leading to the formation of oxygen vacancies with varying concentrations. Specifically, the Co3O4/NF-Ar/O2 demonstrates outstanding catalytic performance for both OER (η20 = 269 mV) and HER (η10 = 135 mV), while maintaining excellent durability in 1 M KOH. Electrolysis cells employing Co3O4/NF-Ar/O2 as both anode and cathode demonstrate a low cell voltage of 1.56 V to achieve 10 mV cm−2 in alkaline conditions. The excellent catalytic performance can be mainly attributed to the urchin-like nanostructure and the appropriate concentration of oxygen vacancies. This research provides further insights into the application of the method to induce oxygen vacancies in low-cost and high-efficiency transition metal oxides (TMOs)-based catalysts for electrochemical reaction.    

    

* Localized electronic reconfiguration at CoNi-BTC-MOFs to accelerate oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392504053
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104165")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392504053"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392504053"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392504053"))][Get cited by]]

OpenAlex: https://openalex.org/W4392504053 (Open access: False)
    
[[https://openalex.org/A5002810182][Yichen Liu]], [[https://openalex.org/A5048050043][Yaqi Liu]], [[https://openalex.org/A5064617721][Guangsheng Luo]], [[https://openalex.org/A5052125778][Zhuangzhuang Xu]], [[https://openalex.org/A5072662689][Xuhao Sun]], [[https://openalex.org/A5027099050][Yuan Zhu]], [[https://openalex.org/A5084364619][Shuyi Wu]], [[https://openalex.org/A5085696768][Lizhe Liu]], [[https://openalex.org/A5068054525][Yun Shan]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104165 
     
No abstract    

    

* Spatially and Temporally Resolved Dynamic Response of Co-Based Composite Interface during the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392505127
:TOPICS: Memristive Devices for Neuromorphic Computing, Electrochemical Detection of Heavy Metal Ions, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.3c12820")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392505127"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392505127"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392505127"))][Get cited by]]

OpenAlex: https://openalex.org/W4392505127 (Open access: False)
    
[[https://openalex.org/A5031589981][Xing Zhong]], [[https://openalex.org/A5058812525][Jianmin Xu]], [[https://openalex.org/A5085985069][Junnan Chen]], [[https://openalex.org/A5065225852][Xiyang Wang]], [[https://openalex.org/A5024436776][Qian Zhu]], [[https://openalex.org/A5002156862][Hui Zeng]], [[https://openalex.org/A5037874610][Yaowen Zhang]], [[https://openalex.org/A5084142209][Yunjiao Pu]], [[https://openalex.org/A5028141359][Xiangyan Hou]], [[https://openalex.org/A5041827917][Xiaofeng Wu]], [[https://openalex.org/A5014923511][Yiming Niu]], [[https://openalex.org/A5071755732][Wei Zhang]], [[https://openalex.org/A5003768009][Yimin A. Wu]], [[https://openalex.org/A5025068432][Ying Wang]], [[https://openalex.org/A5088842976][Bingsen Zhang]], [[https://openalex.org/A5058587719][Keke Huang]], [[https://openalex.org/A5070705465][Shouhua Feng]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.3c12820 
     
No abstract    

    

* Oxygen vacancy and heterointerface engineering of Ni3Fe/NiFe2O4@N-GTs oxygen evolution reaction electrocatalyst for water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392507871
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.diamond.2024.110999")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392507871"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392507871"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392507871"))][Get cited by]]

OpenAlex: https://openalex.org/W4392507871 (Open access: False)
    
[[https://openalex.org/A5038689948][Jiachen Zou]], [[https://openalex.org/A5065496242][Guanying Song]], [[https://openalex.org/A5041870560][Ajuan Cui]], [[https://openalex.org/A5082704360][Zhenjiang Li]], Diamond and Related Materials. None(None)] 2024. https://doi.org/10.1016/j.diamond.2024.110999 
     
Developing highly efficient electrocatalysts for oxygen evolution reaction (OER) plays a key role in accelerating electrochemical water splitting green energy conversion systems. Herein, the dual strategy of incorporating oxygen vacancy and engineering heterointerface was employed for constructing N-doping graphene tubes (N-GTs) supported Ni3Fe/NiFe2O4 heterostructure with abundant oxygen vacancies (Ni3Fe/NiFe2O4 @N-GTs). Benefit from accelerating reaction kinetics and optimizing adsorption strength for reaction intermediates resulting from the synergistic effect of vacancies introduction and heterointerface formation, the optimized Ni3Fe/NiFe2O4 @N-GTs catalyst exhibits remarkably enhanced OER performance with an overpotential of 230 mV to achieve a current density of 10 mA cm−2, a low Tafel slope of 33 mV dec−1 and 330 h stability at the high current density of 100 mA cm−2. Meanwhile, the full water splitting cell consisting of the Ni3Fe/NiFe2O4 @N-GTs-350 anode and a Pt/C cathode delivers a low cell voltage of 1.58 V at 10 mA cm−2 and presents excellent durability for over 330 h of continuous operation at the current density of 10 mA cm−2, demonstrating it promising electrocatalyst for potential applications in the hydrogen production field.    

    

* In situ preparation of Fe-doped NiMoO4 nanoflower clusters as efficient electrocatalysts for oxygen evolution reaction and overall water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392509560
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144071")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392509560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392509560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392509560"))][Get cited by]]

OpenAlex: https://openalex.org/W4392509560 (Open access: False)
    
[[https://openalex.org/A5006595918][Qinyan Yue]], [[https://openalex.org/A5019265616][Ruihua Guo]], [[https://openalex.org/A5045122288][Ruifen Wang]], [[https://openalex.org/A5006396300][Guofang Zhang]], [[https://openalex.org/A5061296427][Yarong Huang]], [[https://openalex.org/A5090109065][Lili Guan]], [[https://openalex.org/A5081086386][Wenyu Zhang]], [[https://openalex.org/A5060509952][Tana Wuren]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144071 
     
Water electrolysis for hydrogen production has attracted significant scientific interest because it is sustainable, pure, and environmentally benign. Nevertheless, the slow rate of the oxygen evolution reaction (OER) during electrolytic water splitting greatly impedes the progress of its development, leading to higher energy consumption and higher costs during hydrogen production. Herein, Fe-doped NiMoO4 nanoflower clusters on nickel foam (Fe-NiMoO4-clusters/NF) as a superior electrocatalyst for the OER via a facile hydrothermal synthesis method. The material delivers excellent electrocatalytic performance at optimal Fe doping level (4%) with low overpotentials of 170 mV@10 mA cm−2 and 240 mV@100 mA cm−2, a small Tafel slope, and long-term stability. Remarkably, the overall water splitting system assembled with the designed material and NiMoO4-clusters/NF exhibits superior stability and a low driving voltage. A comprehensive analysis indicates that Fe doping is crucial to the structure and electrocatalytic properties of NiMoO4. Fe-doped NiMoO4-clusters can serve as stable and efficient OER electrocatalysts in alkaline electrolytes.    

    

* Electronic structure-modulated NiFe-metal–organic framework nanosheets for enhance electrochemical oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392511087
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.127017")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392511087"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392511087"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392511087"))][Get cited by]]

OpenAlex: https://openalex.org/W4392511087 (Open access: False)
    
[[https://openalex.org/A5089822136][Jie Dong]], [[https://openalex.org/A5001443017][Weilong Liu]], [[https://openalex.org/A5040711084][Bohan An]], [[https://openalex.org/A5090185699][Hui Su]], [[https://openalex.org/A5058932447][Jintao Zhang]], [[https://openalex.org/A5031810848][Ning Li]], [[https://openalex.org/A5032179051][Yangqin Gao]], [[https://openalex.org/A5011308255][Lei Ge]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.127017 
     
Oxygen Evolution Reaction (OER) is a critical half-reaction that hinders water decomposition due to its sluggish kinetics. Developing efficient, stable electrocatalysts for OER is crucial for addressing the challenges in energy crisis and green hydrogen production. Compared to single-metal Metal-Organic Frameworks (MOFs), synergistic interactions between metal ions in bimetallic MOFs provide sufficient space for tuning the electronic structure and oxygen-containing intermediate adsorption energies, and therefore bimetallic MOFs shows great potential in enhancing the OER kinetics. In this work, NiFe-MIL-88A nanosheets were synthesized on nickel foam via a facile one-step hydrothermal method. The catalyst exhibited exceptional OER performance in 1.0 M KOH solution. Notably, it achieved a current density of 50 mA cm−2 at a low overpotential of 220 mV and displayed a Tafel slope of 43.2 mV/dec. Furthermore, it had impressive electrocatalytic durability suitable for commercial applications. This work elucidates the performance enhancement of NiFe bimetallic MOF from the perspective of electron migration. In-situ Raman spectroscopy was adopted to investigate the structural reconfiguration of the catalyst to reveal the true catalytic active sites. First-principle calculation demonstrate that introduction of Ni atoms with low electronegativity is conducive to optimizing the catalytic d-band center and ƒe value. This work provides insights for the designing bimetallic MOFs with superior OER performance.    

    

* Constructing WS2/WO3-x heterostructured electrocatalyst enriched with oxygen vacancies for accelerated hydrogen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392514257
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.002")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392514257"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392514257"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392514257"))][Get cited by]]

OpenAlex: https://openalex.org/W4392514257 (Open access: False)
    
[[https://openalex.org/A5089846023][Linglong Kong]], [[https://openalex.org/A5052550377][Lu Pan]], [[https://openalex.org/A5061008777][Hongyu Guo]], [[https://openalex.org/A5062329580][Yongfu Qiu]], [[https://openalex.org/A5067227045][Wafa A. Alshahrani]], [[https://openalex.org/A5013632752][Mohammed A. Amin]], [[https://openalex.org/A5067440912][Jianjian Lin]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.002 
     
H2 produced through hydrogen evolution reaction (HER) is a shining star in the field of clean energy. Significant efforts have been dedicated to develop efficient and stable electrocatalysts to reduce the energy barrier and accelerate the kinetics of Hydrogen evolution reaction (HER) under various environments. Herein, we propose a strategy to accelerate the kinetics of HER under acid and alkaline environments by combining heterostructure engineering with defect engineering. We have successfully synthesized a series of WS2/WO3-x heterostructured catalysts, accompanied with substantial oxygen vacancies using a two-step synthesis method. With the partially sulfurization of WO3-x, the heterojunction interface of WS2 and WO3-x was formed along with the appearance of oxygen vacancies, which can facilitate the migration of electrons. The heterostructured catalyst enriched with oxygen vacancies (defined as WS2/WO3-x-2) demonstrates superior HER performance in acidic and alkaline electrolytes. At a current density of 10 mA cm−2, the WS2/WO3-x-2 heterostructured catalyst manifests an overpotential of 120 mV in the acidic electrolytes and a slightly higher overpotential of 150 mV in an alkaline environment. The overpotentials offer an improvement compared to reported W-based catalysts in terms of HER performance. This work provides guiding significance on the design of heterostructured catalysts with promising performance for HER in acidic and alkaline environments.    

    

* Electronic Structure Control of IrO2 via Conjugated Polymer Support for Highly Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392520542
:TOPICS: Fuel Cell Membrane Technology, Advances in Chemical Sensor Technologies, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/2053-1591/ad30ab")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392520542"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392520542"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392520542"))][Get cited by]]

OpenAlex: https://openalex.org/W4392520542 (Open access: True)
    
[[https://openalex.org/A5045039551][Yusaku Asai]], [[https://openalex.org/A5080200773][Koichi Higashimine]], [[https://openalex.org/A5009715855][Shun Nishimura]], [[https://openalex.org/A5030745222][Rajashekar Badam]], [[https://openalex.org/A5072439341][Noriyoshi Matsumi]], Materials Research Express. None(None)] 2024. https://doi.org/10.1088/2053-1591/ad30ab  ([[https://iopscience.iop.org/article/10.1088/2053-1591/ad30ab/pdf][pdf]])
     
Abstract In this paper, we report synthesis of novel nanoparticle catalyst of iridium oxide supported on conjugated polymer along with evaluation of activity and durability for oxygen evolution reaction. The IrO2/poly(BIAN-thiophene)/TNT catalyst was prepared from iridium complex and poly(BIAN-thiophene)/TNT by hydrothermal method. The synthesized IrO2/poly(BIAN-thiophene)/TNT catalysts was characterized by scanning electron microscopy, transmission electron microscopy, Fourier transfer-infrared spectroscopy, ray photoelectron spectroscopy and electrochemical methods. The average particle size of the IrO2 particles on poly(BIAN-thiophene)/TNT was 2.5 nm. The XPS measurement revealed that Ir complex was completely converted to iridium oxide through hydrothermal treatment. The IrO2/poly(BIAN-thiophene)/TNT catalyst showed sufficient performance for OER activity and durability in acidic condition. Our results indicate that IrO2/poly(BIAN-thiophene)/TNT is one of the prospective candidate catalysts for water splitting.    

    

* Ultra-thin layered of Graphitic carbon nitride support Co3O4 for efficient electrocatalytic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392522279
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4re00020j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392522279"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392522279"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392522279"))][Get cited by]]

OpenAlex: https://openalex.org/W4392522279 (Open access: False)
    
[[https://openalex.org/A5024239427][Ruiyan Luo]], [[https://openalex.org/A5019779453][Ruiyan Fu]], [[https://openalex.org/A5003514344][Youping Guo]], [[https://openalex.org/A5056078581][Xi Li]], Reaction Chemistry and Engineering. None(None)] 2024. https://doi.org/10.1039/d4re00020j 
     
Transition metal cobalt oxide (Co3O4) nanoparticles have been widely used as OER catalysts, but their OER catalytic performance is not ideal due to particle agglomeration. To improve the catalytic reaction...    

    

* Investigation of electrocatalytic oxygen evolution reaction (OER) selectivity against methanol oxidation on stainless steel  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392522510
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cy00030g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392522510"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392522510"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392522510"))][Get cited by]]

OpenAlex: https://openalex.org/W4392522510 (Open access: False)
    
[[https://openalex.org/A5080158948][Pitchiah Esakki Karthik]], [[https://openalex.org/A5031808751][L. Sangaletti]], [[https://openalex.org/A5025942857][Matteo Ferroni]], [[https://openalex.org/A5022148644][Ivano Alessandri]], Catalysis Science & Technology. None(None)] 2024. https://doi.org/10.1039/d4cy00030g 
     
Stainless steel (SS) is a cost-effective, stable, and sustainable electrocatalyst for water oxidation. However, to enhance the efficiency of electrochemical processes, such as the cathodic process of carbon dioxide reduction...    

    

* New type of copper–iron metal-organic framework composited with carbon nanotubes for enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392543725
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392543725"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392543725"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392543725"))][Get cited by]]

OpenAlex: https://openalex.org/W4392543725 (Open access: False)
    
[[https://openalex.org/A5012868605][Yashu Liu]], [[https://openalex.org/A5089689385][Wei Zi]], [[https://openalex.org/A5083814134][Zehang Li]], [[https://openalex.org/A5063099722][Shengwei Wu]], [[https://openalex.org/A5036177101][Shuang Qiao]], [[https://openalex.org/A5048897691][Hongbo Zhou]], International Journal of Hydrogen Energy. 61(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.007 
     
No abstract    

    

* Mechanism conversion and accelerated deprotonation of RuO2-GO catalyst to promote acidic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392545524
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.371")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392545524"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392545524"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392545524"))][Get cited by]]

OpenAlex: https://openalex.org/W4392545524 (Open access: False)
    
[[https://openalex.org/A5010723453][Xin Zhang]], [[https://openalex.org/A5051112193][Yue Shi]], [[https://openalex.org/A5037077755][Peng Fei Liu]], [[https://openalex.org/A5074526456][Hongdong Li]], [[https://openalex.org/A5058405216][Yang Yu]], [[https://openalex.org/A5007549223][Yujing Liu]], [[https://openalex.org/A5004517653][Wenxia Xu]], [[https://openalex.org/A5016055692][Tianrong Zhan]], [[https://openalex.org/A5072157142][Jianping Lai]], [[https://openalex.org/A5073216396][Lei Wang]], International Journal of Hydrogen Energy. 61(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.371 
     
No abstract    

    

* MOF-Derived Cobalt Nanoparticles with Dispersed Iron Phthalocyanines as Bifunctional Oxygen Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392552944
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acssuschemeng.4c00459")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392552944"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392552944"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392552944"))][Get cited by]]

OpenAlex: https://openalex.org/W4392552944 (Open access: False)
    
[[https://openalex.org/A5018159956][Jie Liu]], [[https://openalex.org/A5012944291][Qiuhong Sun]], [[https://openalex.org/A5071344500][Ye Qiu]], [[https://openalex.org/A5084914364][Junliang Chen]], [[https://openalex.org/A5036785818][Wu Yong]], [[https://openalex.org/A5089563927][Yifei Ge]], [[https://openalex.org/A5051762373][L. D. Zhang]], [[https://openalex.org/A5037700967][Zhi Yang]], [[https://openalex.org/A5054473752][Jinjie Qian]], ACS Sustainable Chemistry & Engineering. None(None)] 2024. https://doi.org/10.1021/acssuschemeng.4c00459 
     
No abstract    

    

* Synergistic Modulation of the D-Band Center in Ni3s2 by Selenium and Iron for Enhanced Oxygen Evolution Reaction (Oer) and Urea Oxidation Reaction (Uor)  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392553142
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4750997")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392553142"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392553142"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392553142"))][Get cited by]]

OpenAlex: https://openalex.org/W4392553142 (Open access: False)
    
[[https://openalex.org/A5073902206][Xu Song]], [[https://openalex.org/A5033538563][Dongxu Jiao]], [[https://openalex.org/A5051730407][Xiaowen Ruan]], [[https://openalex.org/A5045710217][Zhaoyong Jin]], [[https://openalex.org/A5030521944][Yu Qiu]], [[https://openalex.org/A5048933060][Jinchang Fan]], [[https://openalex.org/A5056340751][Lei Zhang]], [[https://openalex.org/A5063031540][Weitao Zheng]], [[https://openalex.org/A5086736710][Xiaoqiang Cui]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4750997 
     
No abstract    

    

* Facile hydrothermal synthesis of highly durable binary and ternary cobalt nickel copper oxides for high-performance oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392554808
:TOPICS: Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.321")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392554808"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392554808"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392554808"))][Get cited by]]

OpenAlex: https://openalex.org/W4392554808 (Open access: False)
    
[[https://openalex.org/A5082879821][Humaira A. Bibi]], [[https://openalex.org/A5092133629][Muhammad Adil Mansoor]], [[https://openalex.org/A5061456109][Muhammad Adeel Asghar]], [[https://openalex.org/A5028472785][Zubair Ahmad]], [[https://openalex.org/A5061270905][Arshid Numan]], [[https://openalex.org/A5084136832][Ali Haider]], International Journal of Hydrogen Energy. None(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.321 
     
No abstract    

    

* P-doped MOF-derived NiMo bimetallic sulfide used as a high efficiency electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392557460
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj00334a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392557460"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392557460"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392557460"))][Get cited by]]

OpenAlex: https://openalex.org/W4392557460 (Open access: False)
    
[[https://openalex.org/A5068305525][Bingyu Chen]], [[https://openalex.org/A5036173839][Shiping Zhu]], [[https://openalex.org/A5084163597][Yafeng Qian]], [[https://openalex.org/A5046454314][Dong Wang]], [[https://openalex.org/A5050629579][Lumei Huang]], [[https://openalex.org/A5090866405][Jingwen Wang]], [[https://openalex.org/A5003668002][Aijuan Xie]], [[https://openalex.org/A5079149279][Shiping Luo]], New Journal of Chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj00334a 
     
Metal-organic framework (MOF) was used as a template to prepare transition metal sulfides and phosphides in order to expose the active site of the material to a greater extent. According...    

    

* Oxygen Vacancy and Heterostructure Modulation of Co2P/Fe2P Electrocatalysts for Improving Total Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392559758
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.3c19548")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392559758"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392559758"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392559758"))][Get cited by]]

OpenAlex: https://openalex.org/W4392559758 (Open access: False)
    
[[https://openalex.org/A5028526005][Yue Liu]], [[https://openalex.org/A5090302480][Yawen Hu]], [[https://openalex.org/A5061238087][Xin Zhao]], [[https://openalex.org/A5038612054][Sheng Zhu]], [[https://openalex.org/A5029104177][Yulin Min]], [[https://openalex.org/A5033109301][Qing Xu]], [[https://openalex.org/A5071599644][Qiaoxia Li]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.3c19548 
     
Designing a stable and highly active catalyst for hydrogen evolution and oxygen evolution reactions (HER/OER) is essential for the industrialization of hydrogen energy but remains a major challenge. This work reports a simple approach to fabricating coupled Co2P/Fe2P nanorod array catalyst for overall water decomposition, demonstrating the source of excellent activity in the catalytic process. Under alkaline conditions, Co2P/Fe2P heterostructures exhibit an overpotential of 96 and 220 mV for HER and OER, respectively, at 10 mA cm–2. For total water splitting, a low voltage of 1.56 V is required to provide a current density of 10 mA cm–2. And the catalyst exhibits long-term durability for 30 h at a high current density of 250 mA cm–2. The analysis of the results revealed that the presence of interfacial oxygen vacancies and the strong interaction between Co2P/Fe2P provided the catalyst with more electrochemically active sites and a faster charge transfer capability, which improved the hydrolysis dissociation process. Electrochemically active metal (oxygen) hydroxide phases were produced after OER stability testing. The results of this study prove its great potential in practical industrial electrolysis and provide a reasonable and feasible strategy for the design of nonprecious metal phosphide electrocatalysts.    

    

* Bifunctional ligand Co metal-organic framework derived heterostructured Co-based nanocomposites as oxygen electrocatalysts toward rechargeable zinc-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392563475
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Conducting Polymer Research
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.040")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392563475"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392563475"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392563475"))][Get cited by]]

OpenAlex: https://openalex.org/W4392563475 (Open access: False)
    
[[https://openalex.org/A5088690006][Xinglong Xie]], [[https://openalex.org/A5091420432][Zeyu Zhai]], [[https://openalex.org/A5021362384][Wenwu Cao]], [[https://openalex.org/A5065630092][Jian Dong]], [[https://openalex.org/A5054173720][Yushan Li]], [[https://openalex.org/A5019347635][Qiangchuan Hou]], [[https://openalex.org/A5033939183][Guixiang Du]], [[https://openalex.org/A5015378757][Jiajun Wang]], [[https://openalex.org/A5070178772][Li Tian]], [[https://openalex.org/A5018032174][Jingbo Zhang]], [[https://openalex.org/A5042712935][Tierui Zhang]], [[https://openalex.org/A5007039765][Lu Shang]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.040 
     
Rational construction of efficient and robust bifunctional oxygen electrocatalysts is key but challenging for the widespread application of rechargeable zinc-air batteries (ZABs). Herein, bifunctional ligand Co metal–organic frameworks were first explored to fabricate a hybrid of heterostructured CoOx/Co nanoparticles anchored on a carbon substrate rich in CoNx sites (CoOx/Co@CoNC) via a one-step pyrolysis method. Such a unique heterostructure provides abundant CoNx and CoOx/Co active sites to drive oxygen reduction reaction (ORR) and oxygen evolution reaction (OER), respectively. Besides, their positive synergies facilitate electron transfer and optimize charge/mass transportation. Consequently, the obtained CoOx/Co@CoNC exhibits a superior ORR activity with a higher half-wave potential of 0.88 V than Pt/C (0.83 V vs. RHE), and a comparable OER performance with an overpotential of 346 mV at 10 mA cm−2 to the commercial RuO2. The assembled ZAB using CoOx/Co@CoNC as a cathode catalyst displays a maximum power density of 168.4 mW cm−2, and excellent charge–discharge cyclability over 250 h at 5 mA cm−2. This work highlights the great potential of heterostructures in oxygen electrocatalysis and provides a new pathway for designing efficient bifunctional oxygen catalysts toward rechargeable ZABs.    

    

* Super Stable Selenium Nickel-Iron Electrocatalyst for Oxygen Evolution Reaction in Natural Seawater  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392565606
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4750999")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392565606"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392565606"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392565606"))][Get cited by]]

OpenAlex: https://openalex.org/W4392565606 (Open access: False)
    
[[https://openalex.org/A5076036593][Jue Wang]], [[https://openalex.org/A5017916417][Zhi Liu]], [[https://openalex.org/A5068653819][Libei Feng]], [[https://openalex.org/A5035933733][Di Lü]], [[https://openalex.org/A5068653819][Libei Feng]], [[https://openalex.org/A5047437279][Qinfang Zhang]], [[https://openalex.org/A5056534926][Daniel Hedman]], [[https://openalex.org/A5007547111][Shengfu Tong]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4750999 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Molten Salt-Assisted Synthesis of Optimized Catalyst-Support Interaction Irox/Mno2 for Efficient Oxygen Evolution in Acidic Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392567631
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4752038")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392567631"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392567631"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392567631"))][Get cited by]]

OpenAlex: https://openalex.org/W4392567631 (Open access: False)
    
[[https://openalex.org/A5070935951][Fengge Wang]], [[https://openalex.org/A5076258699][Jiaxi Sui]], [[https://openalex.org/A5001942876][Yaotian Yan]], [[https://openalex.org/A5007616213][Junlei Qi]], [[https://openalex.org/A5077884718][Xiaoyan Luo]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4752038 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Rational Design of Organic Electrocatalysts for Hydrogen and Oxygen Electrocatalytic Applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392577718
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202402184")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392577718"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392577718"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392577718"))][Get cited by]]

OpenAlex: https://openalex.org/W4392577718 (Open access: False)
    
[[https://openalex.org/A5019555753][Ruiqi Cheng]], [[https://openalex.org/A5023601668][Xiaoyun He]], [[https://openalex.org/A5032024992][Kaiqi Li]], [[https://openalex.org/A5094095671][Biao Ran]], [[https://openalex.org/A5045481063][Xinlong Zhang]], [[https://openalex.org/A5032696563][Yonghong Qin]], [[https://openalex.org/A5059197749][Guanjie He]], [[https://openalex.org/A5067482957][Huanxin Li]], [[https://openalex.org/A5084049950][Chaopeng Fu]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202402184 
     
Abstract Efficient electrocatalysts are pivotal for advancing green energy conversion technologies. Organic electrocatalysts, as cost‐effective alternatives to noble‐metal benchmarks, have garnered attention. However, the understanding of the relationships between their properties and electrocatalytic activities remains ambiguous. Plenty of research articles regarding low‐cost organic electrocatalysts started to gain momentum in 2010 and have been flourishing recently though, a review article for both entry‐level and experienced researchers in this field is still lacking. This review underscores the urgent need to elucidate the structure‐activity relationship and design suitable electrode structures, leveraging the unique features of organic electrocatalysts like controllability and compatibility for real‐world applications. Organic electrocatalysts are classified into four groups: small molecules, oligomers, polymers, and frameworks, with specific structural and physicochemical properties serving as activity indicators. To unlock the full potential of organic electrocatalysts, five strategies are discussed: integrated structures, surface property modulation, membrane technologies, electrolyte affinity regulation, and addition of anti‐corrosion species, all aimed at enhancing charge efficiency, mass transfer, and long‐term stability during electrocatalytic reactions. The review offers a comprehensive overview of the current state of organic electrocatalysts and their practical applications, bridging the understanding gap and paving the way for future developments of more efficient green energy conversion technologies. This article is protected by copyright. All rights reserved    

    

* Mesoporous Single Atom-Cluster Fe–N/C Oxygen Evolution Electrocatalysts Synthesized with Bottlebrush Block Copolymer-Templated Rapid Thermal Annealing  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392580330
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.3c18693")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392580330"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392580330"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392580330"))][Get cited by]]

OpenAlex: https://openalex.org/W4392580330 (Open access: False)
    
[[https://openalex.org/A5017103228][Dipankar Saha]], [[https://openalex.org/A5059454580][Hsin-Jung Yu]], [[https://openalex.org/A5010887787][Jiacheng Wang]], [[https://openalex.org/A5076746403][Prateek]], [[https://openalex.org/A5010949964][Xiaobo Chen]], [[https://openalex.org/A5078821249][Chaoyun Tang]], [[https://openalex.org/A5053757768][Claire Senger]], [[https://openalex.org/A5031198791][James Nicolas Pagaduan]], [[https://openalex.org/A5065880223][Reika Katsumata]], [[https://openalex.org/A5089769014][Kenneth R. Carter]], [[https://openalex.org/A5009173681][Guangwen Zhou]], [[https://openalex.org/A5042544548][Peng Bai]], [[https://openalex.org/A5008828063][Nianqiang Wu]], [[https://openalex.org/A5073217965][James J. Watkins]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.3c18693 
     
Current electrocatalysts for oxygen evolution reaction (OER) are either expensive (such as IrO2, RuO2) or/and exhibit high overpotential as well as sluggish kinetics. This article reports mesoporous earth-abundant iron (Fe)–nitrogen (N) doped carbon electrocatalysts with iron clusters and closely surrounding Fe–N4 active sites. Unique to this work is that the mechanically stable mesoporous carbon-matrix structure (79 nm in pore size) with well-dispersed nitrogen-coordinated Fe single atom-cluster is synthesized via rapid thermal annealing (RTA) within only minutes using a self-assembled bottlebrush block copolymer (BBCP) melamine–formaldehyde resin composite template. The resulting porous structure and domain size can be tuned with the degree of polymerization of the BBCP backbone, which increases the electrochemically active surface area and improves electron transfer and mass transport for an effective OER process. The optimized electrocatalyst shows a required potential of 1.48 V (versus RHE) to obtain the current density of 10 mA/cm2 in 1 M KOH aqueous electrolyte and a small Tafel slope of 55 mV/decade at a given overpotential of 250 mV, which is significantly lower than recently reported earth-abundant electrocatalysts. Importantly, the Fe single-atom nitrogen coordination environment facilitates the surface reconstruction into a highly active oxyhydroxide under OER conditions, as revealed by X-ray photoelectron spectroscopy and in situ Raman spectroscopy, while the atomic clusters boost the single atoms reactive sites to prevent demetalation during the OER process. Density functional theory (DFT) calculations support that the iron nitrogen environment and reconstructed oxyhydroxides are electrocatalytically active sites as the kinetics barrier is largely reduced. This work has opened a new avenue for simple, rapid synthesis of inexpensive, earth-abundant, tailorable, mechanically stable, mesoporous carbon-coordinated single-atom electrocatalysts that can be used for renewable energy production.    

    

* Oxygen defect based Cobalt-doped-NiMoO4 Hierarchical hollow nanosheet-based-nanosphere for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392587160
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj00659c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392587160"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392587160"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392587160"))][Get cited by]]

OpenAlex: https://openalex.org/W4392587160 (Open access: False)
    
[[https://openalex.org/A5012770110][Zhuoxun Yin]], [[https://openalex.org/A5045073916][Min Zhou]], [[https://openalex.org/A5018077554][Xinping Li]], [[https://openalex.org/A5057117758][Xiangcun Liu]], [[https://openalex.org/A5070267350][Xinzhi Ma]], [[https://openalex.org/A5020624661][Yang Zhou]], [[https://openalex.org/A5022970962][Aleksandra B. Djurišić]], [[https://openalex.org/A5086155499][Jinlong Li]], [[https://openalex.org/A5008141480][Lina Liu]], [[https://openalex.org/A5081067243][Jun Lv]], New Journal of Chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj00659c 
     
Hollow structures with hierarchical architecture and multi-composition have attracted extensive interest because of their fascinating physicochemical properties as well as wide applications. to improve the efficiency of overall water splitting,...    

    

* Direct Synthesis of CuP2 and Cu3P and Their Performance as Electrocatalysts for Hydrogen Evolution, Oxygen Evolution, and Oxygen Reduction Reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392587799
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/solids5010010")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392587799"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392587799"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392587799"))][Get cited by]]

OpenAlex: https://openalex.org/W4392587799 (Open access: True)
    
[[https://openalex.org/A5054836556][Xiao Ma]], [[https://openalex.org/A5048094454][Xueni Huang]], [[https://openalex.org/A5041039029][Abdessadek Lachgar]], Solids. 5(1)] 2024. https://doi.org/10.3390/solids5010010  ([[https://www.mdpi.com/2673-6497/5/1/10/pdf?version=1709790079][pdf]])
     
Copper phosphides are promising materials for energy conversion applications because of their unique electronic structure and controllable composition. Two stoichiometric copper phosphides, CuP2 and Cu3P, were prepared by direct wet-chemical synthesis using red phosphorus. They were characterized by powder X-ray diffraction, scanning and transmission electron microscopy, and X-ray photoelectron spectroscopy. The precursor selection, reaction temperature, time and solvent composition were also studied. CuP2 is the thermodynamically more stable product, but Cu3P is more commonly obtained. This work demonstrated that higher temperature helps in CuP2 formation. More importantly, using more trioctylphosphine oxide helps control the morphology leading to crystal growth along the crystallographic a-axis. CuP2 and Cu3P were tested for hydrogen evolution, oxygen evolution, and oxygen reduction reactions. CuP2 works better for HER in acidic conditions and OER in general, and Cu3P showed better activity than CuP2 for HER and ORR in an alkaline medium. This study has led to a simple approach to the synthesis of CuP2 nanowires.    

    

* Strong Lewis acid-induced self-healing of loose FeOOH for alkaline oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392593905
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150253")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392593905"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392593905"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392593905"))][Get cited by]]

OpenAlex: https://openalex.org/W4392593905 (Open access: False)
    
[[https://openalex.org/A5061173596][Ning Yu]], [[https://openalex.org/A5035651127][Jing Lv]], [[https://openalex.org/A5084027325][Zhanhu Guo]], [[https://openalex.org/A5039170579][Xin-Jie Tian]], [[https://openalex.org/A5050840588][Yusheng Zhang]], [[https://openalex.org/A5077352796][Wenjing Li]], [[https://openalex.org/A5075675634][Yulu Zhou]], [[https://openalex.org/A5062331341][Yong‐Ming Chai]], [[https://openalex.org/A5072072030][Bin Dong]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150253 
     
The fast leaching of the Fe catalytic center and low conductivity of FeOOH have hindered the optimal stability and activity of Fe-based electrocatalysts for oxygen evolution reactions (OER). Here, Zn2+ is introduced into FeOOH with a looser nanosheet structure by regulating electric double layer (EDL) repulsion during electrodeposition. Meanwhile, as strong Lewis acids, Zn2+ in ZnxFeOOH could act as an electron acceptor, accepting electrons from FeOOH. The doping of Zn2+ shortens the bond length of Fe-O and enhances the covalency of Fe-O to improve electron transport rate and stability. The faster catalytic kinetics also been obtained by facilitating O* to form OOH* intermediates. At 100 mA cm−2, Zn0.5FeOOH requires overpotential of only 250 mV and maintains initial activity in 1 M KOH after 120 h. Notably, Zn-induced self-healing is achieved when the leaching and redeposition of Fe reach dynamic equilibrium. In 1 M KOH seawater, Zn0.5FeOOH requires overpotentials of 286 mV to produce current density of 100 mA cm−2. At 2.0 V, Zn0.5FeOOH can achieve 1000 mA cm−2 in anion exchange membrane (AEM) water electrolyzer at room temperature. This work provides an effective Zn-induced strategy for designing efficient and stable OER catalysts for industrial development.    

    

* Perovskite for Electrocatalytic Oxygen Evolution at Elevated Temperatures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392697241
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202301534")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392697241"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392697241"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392697241"))][Get cited by]]

OpenAlex: https://openalex.org/W4392697241 (Open access: False)
    
[[https://openalex.org/A5003993083][Fatma Abdelghafar]], [[https://openalex.org/A5072221758][Xiaomin Xu]], [[https://openalex.org/A5044918647][San Ping Jiang]], [[https://openalex.org/A5064123920][Zongping Shao]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202301534 
     
The development of advanced electrolysis technologies such as anion exchange membrane water electrolyzer (AEMWE) is central to the vision of a sustainable energy future. Key to the realization of such AEMWE technology lies in the exploration of low‐cost and high‐efficient catalysts for facilitating the anodic oxygen evolution reaction (OER). Despite tremendous efforts in the fundamental research, most of today’s OER works are conducted under room temperature, which deviates significantly with AEMWE’s operating temperature (50–80 °C). To bridge this gap, it is highly desirable to obtain insights into the OER catalytic behavior at elevated temperatures. Herein, using the well‐known perovskite catalyst Ba0.5Sr0.5Co0.8Fe0.2O3−δ (BSCF) as a proof of concept, the effect of temperature on the variation in OER catalytic activity and stability is evaluated. It is found that the BSCF’s activity increases with increasing temperature due to enhanced lattice oxygen participation promoting the lattice oxygen‐mediated OER process. Further, surface amorphization and cation leaching of BSCF become more pronounced as temperature increases, causing a somewhat attenuated OER stability. These new understandings of the fundamental OER catalysis over perovskite materials at industrial‐relevant temperature conditions are expected to have strong implications for the research of OER catalysts to be deployed in practical water electrolyzers.    

    

* Platinum Oxide Formation under Oxygen Evolution Reaction Conditions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392593961
:TOPICS: Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-3400440/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392593961"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392593961"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392593961"))][Get cited by]]

OpenAlex: https://openalex.org/W4392593961 (Open access: True)
    
[[https://openalex.org/A5011239656][Leon Jacobse]], [[https://openalex.org/A5042682191][R. Schuster]], [[https://openalex.org/A5059558135][Mona Kohantorabi]], [[https://openalex.org/A5062291345][Silvan Dolling]], [[https://openalex.org/A5070604611][Johannes Pfrommer]], [[https://openalex.org/A5044139774][Xin Deng]], [[https://openalex.org/A5071311974][Tim Weber]], [[https://openalex.org/A5015948967][Olof Gutowski]], [[https://openalex.org/A5051942768][Ann Christin Dippel]], [[https://openalex.org/A5079153075][Olaf Brummel]], [[https://openalex.org/A5063618343][Yaroslava Lykhach]], [[https://openalex.org/A5088659450][Heshmat Noei]], [[https://openalex.org/A5061489989][Herbert Over]], [[https://openalex.org/A5035522337][Jörg Libuda]], [[https://openalex.org/A5024623921][Vedran Vonk]], [[https://openalex.org/A5039287605][Andreas Stierle]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-3400440/v1  ([[https://www.researchsquare.com/article/rs-3400440/latest.pdf][pdf]])
     
Abstract Electrocatalyst degradation, often caused by oxidative processes, forms a large barrier for the wide-spread application of electrolysers and fuel cells, which are crucial for a sustainable energy society. A detailed understanding of the catalyst surface structure under oxygen evolution reaction (OER) conditions is, therefore, required to design more stable catalysts. Here, we study the oxidation of a Pt(111) model electrode under operando conditions combining High-Energy Surface X-ray Diffraction (HE-SXRD) with a Rotating Disk Electrode (RDE) in a unique experimental setup. This novel approach allows us to follow the atomic structure of the electrode/electrolyte interface under oxygen evolution reaction conditions under hitherto unexplored potential regimes. We find that the Pt(111) surface gets electro-oxidized in a layer-by-layer fashion, which is the best scenario in terms of electrode stability. From ex situ X-ray Reflectivity (XRR) and X-ray Photoelectron Spectroscopy (XPS) measurements we find that a sub-nm thick, PtO 2 oxide film is forming, which deactivates the surface and leads to surface roughening after subsequent dissolution. Our results provide important insight for the operation of fuel cells and electrolysers under intermittent conditions of renewable energies.    

    

* Circumventing the Theoretical Scaling Relation Limit for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392519273
:TOPICS: Electrocatalysis for Energy Conversion, Metabolic Theory of Ecology and Climate Change Impacts, Stochastic Thermodynamics and Fluctuation Theorems
:PUBLICATION_DATE: 2024-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.4c00201")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392519273"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392519273"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392519273"))][Get cited by]]

OpenAlex: https://openalex.org/W4392519273 (Open access: False)
    
[[https://openalex.org/A5056199569][Peijia Ding]], [[https://openalex.org/A5083626556][Yufeng Xue]], [[https://openalex.org/A5056731969][Ziwei Chai]], [[https://openalex.org/A5008261391][Qi Hu]], [[https://openalex.org/A5057199691][Chuan‐Jia Tong]], [[https://openalex.org/A5007106018][Gilberto Teobaldi]], [[https://openalex.org/A5024656714][Li Min Liu]], The Journal of Physical Chemistry Letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.4c00201 
     
Transition metal hydr(oxy)oxides (TMHs) are considered efficient electrocatalysts for the oxygen evolution reaction (OER) under alkaline conditions. Toward identification of potential descriptors to circumvent the scaling relation limit for the OER, first-principles calculations were used to quantify the effects on the overpotential of different s (Mg), p (Al), and d (Ti, V, Cr, Fe, Co, Sc, and Zn) electron dopants in Ni-based TMHs. Both the adsorbate evolution mechanism (AEM) and the lattice oxygen-mediated mechanism (LOM) were examined. The results demonstrate that the formation energy of oxygen vacancies (EVO) is strongly affected by the chemical nature of the dopants. A linear relationship is identified between EVO and the free energy difference for the oxygen–oxygen coupling. A descriptor could be employed to discriminate whether the LOM is energetically favored over the AEM. These findings fill existing gaps in appropriate yet computationally light descriptors for direct identification between the AEM and LOM.    

    

* Surface-Functionalized Ni nanostructures for Oxygen Evolution Reaction, a different synthetic approach.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392704432
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2023-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.29363/nanoge.matsus.2024.135")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392704432"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392704432"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392704432"))][Get cited by]]

OpenAlex: https://openalex.org/W4392704432 (Open access: False)
    
[[https://openalex.org/A5047786576][Aureliano Macili]], [[https://openalex.org/A5020337283][Laia Francàs]], [[https://openalex.org/A5080028922][Jordi García‐Antón]], [[https://openalex.org/A5039090961][Xavier Sala]], No host. None(None)] 2023. https://doi.org/10.29363/nanoge.matsus.2024.135 
     
No abstract    

    

* Oxide management in Ruthenium oxide catalysts for efficient Oxygen Evolution Reaction in acid.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392704834
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2023-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.29363/nanoge.matsus.2024.202")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392704834"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392704834"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392704834"))][Get cited by]]

OpenAlex: https://openalex.org/W4392704834 (Open access: False)
    
[[https://openalex.org/A5019487756][Amit Kumar Das]], [[https://openalex.org/A5075242279][F. Pelayo Garcı́a de Arquer]], [[https://openalex.org/A5029072578][Xia Lu]], [[https://openalex.org/A5033159909][Anku Guha]], [[https://openalex.org/A5094126826][Viktoria Holovanova]], No host. None(None)] 2023. https://doi.org/10.29363/nanoge.matsus.2024.202 
     
No abstract    

    

* Nitrogen doped leather waste-derived carbon materials as electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392715055
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.inoche.2024.112295")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392715055"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392715055"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392715055"))][Get cited by]]

OpenAlex: https://openalex.org/W4392715055 (Open access: False)
    
[[https://openalex.org/A5061281601][Afshin Abbasi]], [[https://openalex.org/A5019801918][Musammir Khan]], [[https://openalex.org/A5061051894][Fawad Ahmad]], [[https://openalex.org/A5030639287][Muhammad Imran Khan]], [[https://openalex.org/A5080155587][Abdallah Shanableh]], [[https://openalex.org/A5001143351][R. P. S. Rajput]], [[https://openalex.org/A5009050964][Suryyia Manzoor]], [[https://openalex.org/A5039707327][Shabnam Shahida]], [[https://openalex.org/A5002846345][Rafael Luque]], [[https://openalex.org/A5006821035][Sameh M. Osman]], [[https://openalex.org/A5007253361][Mushtaq Hussain Lashari]], Inorganic Chemistry Communications. None(None)] 2024. https://doi.org/10.1016/j.inoche.2024.112295 
     
Nitrogen doped leather waste-derived carbon materials have been employed as eletrocatalyst for oxygen evolution reaction. Low current densities and complex synthesis routes of other carbon-based materials limit their practical applicability. We present herein a simple and cost-competitive design of a metal free nitrogen-doped carbon matrix (NCM). At 10 mA cm−2 of current density, the assembled NCM showed a low over potential of 330 mV. NCM provided 73 mV dec-1 of slope value according to Tafel analysis, with NCM slope value improved as compared to previously described electrocatalysts inclusive of graphene (113 mV dec−1) and carbon nanosheets (101 mV dec−1), under similar reaction conditions. Linear sweep voltamogram, stability test and electrochemical impedance spectra confirmed the potential of NCM in OER as a heterogeneous electrocatalyst.    

    

* Interface oxidation induced amorphous/crystalline 1D hollandite Rb0.17IrO2 for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392660887
:TOPICS: Electrocatalysis for Energy Conversion, Advanced Materials for Smart Windows, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159881")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392660887"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392660887"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392660887"))][Get cited by]]

OpenAlex: https://openalex.org/W4392660887 (Open access: False)
    
[[https://openalex.org/A5032107505][Danni Li]], [[https://openalex.org/A5002152947][Anhui Zhou]], [[https://openalex.org/A5064789384][Xiang Shao]], [[https://openalex.org/A5079098289][Lin Zhu]], [[https://openalex.org/A5021827773][Youwei Du]], [[https://openalex.org/A5084812419][Limei Cao]], [[https://openalex.org/A5008669070][Chenglong Ma]], [[https://openalex.org/A5029886716][Jie Yang]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159881 
     
Recently, surface reconstruction derived from Ir-based derivatives could achieve satisfactory oxygen evolution performance. Herein, ultra-long nanowire hollandite structured Rb0.17IrO2 was synthesized and a nano-amorphous layer with a thickness of ∼1.5 nm was achieved by interfacial oxidation treatment. The prepared catalyst exhibits outstanding water oxidation activity with an oxygen evolution reaction (OER) current density of 10 mA cm−2 at 330 mV for robust continuous operation in acidic media. Through the spectroscopic and density functional theory (DFT) theoretical calculations, we demonstrate that the nano-amorphous layers induced by interfacial oxidation on the one-dimensional (1D)-nanowire surface have enhanced O-2p centers and increased Ir-O hybridization compared to the bulk Rb0.17IrO2 phase, which essentially balances the adsorption energy of the intermediates. Effectively incorporating surface reconstruction behavior could significantly improve catalyst activity. This work effectively combines 1D Ir-based materials and surface reconstruction, which provides a strategy for the subsequent full utilization of Ir-based materials applied on OER process.    

    

* Modulating space charge of FeP/CoP p-n heterojunction for boosting oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392636984
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.060")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392636984"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392636984"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392636984"))][Get cited by]]

OpenAlex: https://openalex.org/W4392636984 (Open access: False)
    
[[https://openalex.org/A5069899429][Shaqi Fu]], [[https://openalex.org/A5018569451][Peng Cheng]], [[https://openalex.org/A5030386675][Yuancong Luo]], [[https://openalex.org/A5034521153][Lingli Cheng]], [[https://openalex.org/A5011764958][Xuechun Yang]], [[https://openalex.org/A5057732263][Z. Jiao]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.060 
     
Surface reconstruction of electrocatalysts is an effective strategy to modulate the space charge distribution to enhance the electrocatalytic activity. The p-n heterostructured FeP/CoP-2D octagonal nanoplates were successfully constructed by cation-exchange method. The space charge effect caused by the p-n heterojunction accelerated the electron transfer, optimized the electronic structure, and improved the activity of the active sites during the oxygen evolution reaction process. As a result, FeP/CoP-2D required only 247 mV overpotential to achieve a current density of 10 mA cm−2 with a Tafel slope as low as 68 mV dec-1. Density-functional theory calculations confirmed that the construction of p-n heterojunctions can enhance the adsorption of *OH in the active centers and optimize the Gibbs free energy of the OER reaction. This study provides an effective and feasible strategy for constructing p-n heterojunctions to modulate the space charge state for optimizing the OER performance of electrocatalysts.    

    

* Hierarchical FeO H @Ni3B hybrid for efficient alkaline oxygen evolution at high current density  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392714501
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.02.061")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392714501"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392714501"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392714501"))][Get cited by]]

OpenAlex: https://openalex.org/W4392714501 (Open access: False)
    
[[https://openalex.org/A5008664656][Fuxi Liu]], [[https://openalex.org/A5010682216][Qing Liang]], [[https://openalex.org/A5008795836][Zhenyu Li]], [[https://openalex.org/A5007669734][Meiqi Liu]], [[https://openalex.org/A5013227884][Nailin Yue]], [[https://openalex.org/A5033190410][Zizhun Wang]], [[https://openalex.org/A5056514565][Xu Zou]], [[https://openalex.org/A5071755732][Wei Zhang]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.02.061 
     
Electrocatalysts with high activity and long-term durability are vital toward large-scale hydrogen production from electrocatalytic water splitting. Here, the self-supported electrode (FeOxHy@Ni3B/NF) with hierarchical heterostructure was simply prepared by using Ni3B chunks grown on nickel foam as substrate to in situ form vertical FeOxHy nanosheets. Such hybrid shows efficient oxygen evolution reaction activity with overpotentials as low as 267 and 249 mV at 100 mA cm−2 in 1 M KOH solution and 30 wt% KOH solution, respectively. Meanwhile, it also exhibits excellent catalytic stability, sustaining catalysis at 500 mA cm−2 in 1 M KOH solution for 200 h, and even for 200 h at 1000 mA cm−2 in 30 wt% KOH solution. Further experimental results reveal that the FeOxHy@Ni3B/NF is endowed with superhydrophilic and superaerophobic surface properties, which not only provide more mass transport channels, as well as facilitated the diffusion of reaction intermediates and gas bubbles. Also, it holds faster reaction kinetics, more accessible active sites and accelerated electron transfer rates due to strong synergistic interactions at the heterogeneous interface.    

    

* Tungsten Doped Fecop2 Nanoparticles Embedded into Carbon for Highly Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392626811
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4752172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392626811"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392626811"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392626811"))][Get cited by]]

OpenAlex: https://openalex.org/W4392626811 (Open access: False)
    
[[https://openalex.org/A5022780097][Xinyao Quan]], [[https://openalex.org/A5008095269][Jiajia Ma]], [[https://openalex.org/A5021295877][Qian-Shuo Shao]], [[https://openalex.org/A5033209965][Hao-Cong Li]], [[https://openalex.org/A5065738034][Lingxiang Sun]], [[https://openalex.org/A5001387667][Gui Li Huang]], [[https://openalex.org/A5037431207][Yan Su]], [[https://openalex.org/A5061732797][Hong Zhang]], [[https://openalex.org/A5062588973][Yuning Wang]], [[https://openalex.org/A5039772620][Xiaoqing Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4752172 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Enhancement of oxygen evolution reaction in alkaline water electrolysis by Lorentz forces generated by an external magnetic field  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392612847
:TOPICS: Hydrogen Energy Systems and Technologies, Materials and Methods for Hydrogen Storage, Influence of Magnetic Fields on Biological Systems
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.199")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392612847"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392612847"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392612847"))][Get cited by]]

OpenAlex: https://openalex.org/W4392612847 (Open access: False)
    
[[https://openalex.org/A5073839613][Wilton Fogaça]], [[https://openalex.org/A5069559783][Hayata Ikeda]], [[https://openalex.org/A5043452701][Ryuta Misumi]], [[https://openalex.org/A5090206527][Yoshiyuki Kuroda]], [[https://openalex.org/A5073330579][Shigenori Mitsushima]], International Journal of Hydrogen Energy. 61(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.199 
     
The effects of vertical Lorentz forces generated by an external magnetic field applied perpendicular to the inherent electric field on the oxygen evolution reaction conducted on a Ni wire are investigated using cyclic voltammetry, impedance measurements, and particle image velocimetry (PIV). Both downward and upward Lorentz forces provide smaller overpotentials than that generated in their absence. Based on a dual-bubble layer model for reactant transfer, we find that the diffusion resistance of the hydroxide ions and increased ohmic resistance (after iR correction) induced by the layer of bubbles attached to the electrode surface are most effectively alleviated by the downward Lorentz force, while the charge-transfer resistance is retained. Furthermore, the generated bubbles have smaller average diameters. By using PIV measurements, we find that stronger shear stresses induced by the faster flow of the electrolyte in the vicinity of the working electrode facilitate the detachment of bubbles from the electrode surface.    

    

* A review on synthesis and modification of cobalt-molybdenum based sulfides as hydrogen and oxygen evolution catalysts for water electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392660622
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cinorg.2024.100043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392660622"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392660622"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392660622"))][Get cited by]]

OpenAlex: https://openalex.org/W4392660622 (Open access: True)
    
[[https://openalex.org/A5073501391][Jie Zhang]], [[https://openalex.org/A5026246996][Chunlin Hu]], [[https://openalex.org/A5039904213][Peng Deng]], [[https://openalex.org/A5060296132][Yan-Hong Yin]], Chemistry of Inorganic Materials. None(None)] 2024. https://doi.org/10.1016/j.cinorg.2024.100043 
     
Hydrogen energy as the alternative to fossil fuel received wide attention. Among different methods of hydrogen production, water electrolysis is the cleanest and most promising method. However, its development is greatly limited by hydrogen evolution reaction (HER) reaction and oxygen evolution reaction (OER) reaction. Therefore, it is very necessary to develop low-cost, high activity, and good stability of non-precious metal catalyst to replace the precious metal catalyst (Pt, RuO2), and to further reduce overpotential and power consumption. To date, great efforts have been made to develop transition metal compounds with electrocatalytic performance, such as sulfides, oxides, and carbides materials. Especially, transition metal sulfides play a very important role as catalysts and have attracted wide attention for their structural adjustability, high abundance, and mild preparation process. In this introduction, we focus on the role of transition metal sulfides in catalysts for water electrolysis, especially in a few most studied sulfides such as cobalt/molybdenum based sulfides and the recently reported homogeneous cobalt-molybdenum based sulfides, in which cobalt acts as a key element. Composition, morphology, and size are the most important factors that influence the intrinsic activity, electrical conductivity, and electronic structure of these transition metal sulfides. Besides, the effect of carbon nanomaterials as carrier materials is also discussed. The aim of this review is to emphasize the great potentials of cobalt and molybdenum based sulfides with high performance, and to help improve the performance of existing sulfides and explore new modification methods.    

    

* S-doped Yttrium Ruthenate Pyrochlore catalyst for Efficient Electrocatalytic Oxygen Evolution in Acidic Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392639957
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.174072")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392639957"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392639957"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392639957"))][Get cited by]]

OpenAlex: https://openalex.org/W4392639957 (Open access: False)
    
[[https://openalex.org/A5061758333][Rei‐Cheng Yang]], [[https://openalex.org/A5066468525][Hao Qi]], [[https://openalex.org/A5035942767][Jianan Zhao]], [[https://openalex.org/A5009590736][Cong Liu]], [[https://openalex.org/A5038208946][Shujie Xue]], [[https://openalex.org/A5011797167][Fengjuan Miao]], [[https://openalex.org/A5064144494][Wenbing Tang]], [[https://openalex.org/A5035888330][Qinghong Huang]], [[https://openalex.org/A5037677450][Jing Wang]], [[https://openalex.org/A5082323192][Yuping Wu]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.174072 
     
No abstract    

    

* NH4Cl-assisted synthesis of TaON nanoparticle applied to photocatalytic hydrogen and oxygen evolution from water  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392642667
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.02.051")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392642667"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392642667"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392642667"))][Get cited by]]

OpenAlex: https://openalex.org/W4392642667 (Open access: False)
    
[[https://openalex.org/A5014193156][Yanhua Xu]], [[https://openalex.org/A5017622841][Kaiwei Liu]], [[https://openalex.org/A5072552402][Jifang Zhang]], [[https://openalex.org/A5011611335][Boyang Zhang]], [[https://openalex.org/A5085186808][Jiaming Zhang]], [[https://openalex.org/A5073697986][Shaoyong Ke]], [[https://openalex.org/A5043069455][Haifeng Wang]], [[https://openalex.org/A5007957054][Guijun Ma]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.02.051 
     
No abstract    

    

* Tm-Doping Modulated P-D Orbital Coupling to Enhance the Oxygen Evolution Performance of Ni3s2  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392641110
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4755085")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392641110"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392641110"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392641110"))][Get cited by]]

OpenAlex: https://openalex.org/W4392641110 (Open access: False)
    
[[https://openalex.org/A5081449417][Jing Pan]], [[https://openalex.org/A5049808310][Qiuhong Li]], [[https://openalex.org/A5089795720][Minghao Zhang]], [[https://openalex.org/A5002209512][Rui Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4755085 
     
No abstract    

    
