#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Fri Feb 16 00:42:55 2024

Found 49 results from 2024-02-09 to 2024-02-16
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Achieving highly active A-site cation-deficient perovskite electrocatalysts operated at large current density toward hydrogen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391642833
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.seppur.2024.126715")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391642833"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391642833"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391642833"))][Get cited by]]

OpenAlex: https://openalex.org/W4391642833 (Open access: False)
    
[[https://openalex.org/A5083235323][Xiaoxu Yang]], [[https://openalex.org/A5025512880][Tian Xia]], [[https://openalex.org/A5032091517][Qiang Li]], [[https://openalex.org/A5055332524][Jingping Wang]], [[https://openalex.org/A5019182242][Liping Sun]], [[https://openalex.org/A5011496717][Li-Hua Huo]], [[https://openalex.org/A5057147812][Hui Zhao]], Separation and Purification Technology. None(None)] 2024. https://doi.org/10.1016/j.seppur.2024.126715 
     
No abstract    

    

* Self‐etching assembly of designed NiFeMOF nanosheet arrays as high‐efficient oxygen evolution electrocatalyst for water splitting  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391644177
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202301607")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391644177"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391644177"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391644177"))][Get cited by]]

OpenAlex: https://openalex.org/W4391644177 (Open access: False)
    
[[https://openalex.org/A5026396978][Shifan Zhang]], [[https://openalex.org/A5053378837][Miao Liao]], [[https://openalex.org/A5037697971][Zhiyang Huang]], [[https://openalex.org/A5048883827][Mingcheng Gao]], [[https://openalex.org/A5021978869][X. Liu]], [[https://openalex.org/A5089703861][Hao Yin]], [[https://openalex.org/A5021114807][Tayirjan Taylor Isimjan]], [[https://openalex.org/A5013921358][Dandan Cai]], [[https://openalex.org/A5009758777][Xiulin Yang]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202301607 
     
2D metal‐organic frameworks (MOFs) have emerged as potential candidates for electrocatalytic oxygen evolution reactions (OER) due to their inherent properties like abundant coordination unsaturated active sites and efficient charge transfer. Herein, a versatile and massively synthesizable self‐etching assembly strategy wherein nickel‐iron foam (NFF) acts as a substrate and a metal ion source. Specifically, by etching the nickel‐iron foam (NFF) surface using ligands and solvents, Ni/Fe metal ions are activated and subsequently reacted under hydrothermal conditions, resulting in the formation of self‐supporting nanosheet arrays, eliminating the need for external metal salts. The obtained 33% NiFeMOF/NFF exhibits remarkable OER performance with ultra‐low overpotentials of 188/231 mV at 10/100 mA cm−2, respectively, outperforming most recently reported catalysts. Besides, the built 33% NiFeMOF/NFF(+) || Pt/C(−) electrolyzer presents low cell voltages of 1.55/1.83 V at 10/100 mA cm−2, superior to the benchmark RuO2(+) || Pt/C(−), implying good industrialization prospects. The excellent catalytic activity stems from the modulation of the electronic spin state of the Ni active site by the introduction of Fe, which facilitates the adsorption process of oxygen‐containing intermediates and thus enhances the OER activity. This innovative approach offers a promising pathway for commercial‐scale sustainable energy solutions.    

    

* Tailoring the d-band center of iridium-doped cobalt selenide for dual-boosted hydrogen and oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391644293
:TOPICS: Electrocatalysis for Energy Conversion, Thin-Film Solar Cell Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nanoms.2024.01.011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391644293"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391644293"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391644293"))][Get cited by]]

OpenAlex: https://openalex.org/W4391644293 (Open access: True)
    
[[https://openalex.org/A5036448935][Liwei An]], [[https://openalex.org/A5055911393][Jiang Zhu]], [[https://openalex.org/A5051262214][Jun Yang]], [[https://openalex.org/A5088757374][Deli Wang]], Nano Materials Science. None(None)] 2024. https://doi.org/10.1016/j.nanoms.2024.01.011 
     
No abstract    

    

* Ruthenium-lead oxide for acidic oxygen evolution reaction in proton exchange membrane water electrolysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391650124
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12274-024-6460-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391650124"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391650124"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391650124"))][Get cited by]]

OpenAlex: https://openalex.org/W4391650124 (Open access: False)
    
[[https://openalex.org/A5019484731][Feng-Yang Chen]], [[https://openalex.org/A5007510770][Chao Qiu]], [[https://openalex.org/A5089738815][Zhenyu Wu]], [[https://openalex.org/A5081089785][Tae‐Ung Wi]], [[https://openalex.org/A5045648486][Y. Zou Finfrock]], [[https://openalex.org/A5041663670][Haotian Wang]], Nano Research. None(None)] 2024. https://doi.org/10.1007/s12274-024-6460-5 
     
No abstract    

    

* Fabrication of a novel superaerophobic support structure for NiCo-layered double hydroxide electrocatalysts for the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391651088
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.143931")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391651088"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391651088"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391651088"))][Get cited by]]

OpenAlex: https://openalex.org/W4391651088 (Open access: False)
    
[[https://openalex.org/A5036257478][Somayyeh Abbasi]], [[https://openalex.org/A5030019987][Ming Hao]], [[https://openalex.org/A5084861983][Mohsen Fakourihassanabadi]], [[https://openalex.org/A5082185622][Steven J. Thorpe]], [[https://openalex.org/A5088929066][Daniel Guay]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.143931 
     
In this work, 3D Ni substrate with superaerophobic properties were catalyzed through the deposition of NiCo layered double hydroxide (NiCo-LDH). Deposition of NiCo-LDH was achieved using a mixed solution of Ni and Co nitrate salts as precursors. Precipitation of NiCo-LDH was achieved by the application of a negative current that caused a local raise of the solution pH. NiCo-LDHs were deposited in the form of vertically aligned nanosheets that infiltrate throughout the porous structure of the superaerophobic 3D Ni substrate. Variation of the deposition current changed the composition of the NiCo-LDH. The performance and the mechanisms responsible for the OER were investigated through a series of electrochemical experiments that include electrochemical impedance spectroscopy. As exemplified by a change of the Tafel slope from ca. 60 to 40 mV/decade, the OER mechanism is modified by the deposition the NiCo-LDH. In 1M KOH at room temperature, the best electrode has overpotential as small as 269 and 340 mV at 10 and 250 mA cm−2, respectively. Longer-term electrolysis test during 56 hours at 250 mA cm−2 showed a constant overpotential of 340 mV, without any sign of degradation.    

    

* Molecular oxygen activation in photocatalysis: generation, detection and application  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391651375
:TOPICS: Electrochemical Biosensor Technology, Nanomaterials with Enzyme-Like Characteristics, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104033")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391651375"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391651375"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391651375"))][Get cited by]]

OpenAlex: https://openalex.org/W4391651375 (Open access: False)
    
[[https://openalex.org/A5011090171][Yandong Sun]], [[https://openalex.org/A5055495508][Sheng‐Qi Guo]], [[https://openalex.org/A5065149012][Li Fan]], [[https://openalex.org/A5047336245][Jinyuan Cai]], [[https://openalex.org/A5054465909][Weiguang Han]], [[https://openalex.org/A5059228420][Fangyuan Zhang]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104033 
     
Global environmental degradation has been recognized as the most important challenge of the 21st century, and the development of green chemical methods to achieve environmental remediation is a common focus. As a typical representative of advanced oxidation technology, photocatalytic technology driven by solar energy has attracted attention due to its ability to activate oxygen molecules in the atmosphere into reactive oxygen species with oxidizing properties. At present, the development of photocatalysts has reached unprecedented prosperity, but people's understanding of the characteristics and analysis methods of molecular oxygen activation has always been insufficient, especially the lack of systematic summary and sorting. Herein, we focus on the properties and formation pathways of several typical reactive oxygen species (ROS), and summarize the latest advances for the detection of ROS in terms of both qualitative and quantitative detection needs, respectively. Then, preventative photocatalytic applications and performances of ROS, including applications in pollutant degradation, organic matter conversion and biological, are presented.    

    

* Tuning synergy between nickel and iron in Ruddlesden–Popper perovskites through controllable crystal dimensionalities towards enhanced oxygen‐evolving activity and stability  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391653154
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cey2.465")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391653154"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391653154"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391653154"))][Get cited by]]

OpenAlex: https://openalex.org/W4391653154 (Open access: True)
    
[[https://openalex.org/A5073407437][Haijuan Zhang]], [[https://openalex.org/A5006377403][Daqin Guan]], [[https://openalex.org/A5058073887][Yuxing Gu]], [[https://openalex.org/A5068379441][Hengyue Xu]], [[https://openalex.org/A5009701916][Chunchang Wang]], [[https://openalex.org/A5034744923][Zongping Shao]], [[https://openalex.org/A5062306661][Youmin Guo]], Carbon energy. None(None)] 2024. https://doi.org/10.1002/cey2.465  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cey2.465][pdf]])
     
Abstract Ni–Fe‐based oxides are among the most promising catalysts developed to date for the bottleneck oxygen evolution reaction (OER) in water electrolysis. However, understanding and mastering the synergy of Ni and Fe remain challenging. Herein, we report that the synergy between Ni and Fe can be tailored by crystal dimensionality of Ni, Fe‐contained Ruddlesden–Popper (RP)‐type perovskites (La 0.125 Sr 0.875 ) n +1 (Ni 0.25 Fe 0.75 ) n O 3 n +1 ( n = 1, 2, 3), where the material with n = 3 shows the best OER performance in alkaline media. Soft X‐ray absorption spectroscopy spectra before and after OER reveal that the material with n = 3 shows enhanced Ni/Fe–O covalency to boost the electron transfer as compared to those with n = 1 and n = 2. Further experimental investigations demonstrate that the Fe ion is the active site and the Ni ion is the stable site in this system, where such unique synergy reaches the optimum at n = 3. Besides, as n increases, the proportion of unstable rock‐salt layers accordingly decreases and the leaching of ions (especially Sr 2+ ) into the electrolyte is suppressed, which induces a decrease in the leaching of active Fe ions, ultimately leading to enhanced stability. This work provides a new avenue for rational catalyst design through the dimensional strategy.    

    

* Stabilizing Highly Active Ru Sites by Electron Reservoir in Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391653962
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29040785")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391653962"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391653962"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391653962"))][Get cited by]]

OpenAlex: https://openalex.org/W4391653962 (Open access: True)
    
[[https://openalex.org/A5052169469][Jiayan Wu]], [[https://openalex.org/A5004975664][Zhongjie Qiu]], [[https://openalex.org/A5029153042][Jiaxi Zhang]], [[https://openalex.org/A5075171426][Huiyu Song]], [[https://openalex.org/A5023031181][Zhiming Cui]], [[https://openalex.org/A5062744012][Li Du]], Molecules. 29(4)] 2024. https://doi.org/10.3390/molecules29040785  ([[https://www.mdpi.com/1420-3049/29/4/785/pdf?version=1707380330][pdf]])
     
Proton exchange membrane water electrolysis is hindered by the sluggish kinetics of the anodic oxygen evolution reaction. RuO2 is regarded as a promising alternative to IrO2 for the anode catalyst of proton exchange membrane water electrolyzers due to its superior activity and relatively lower cost compared to IrO2. However, the dissolution of Ru induced by its overoxidation under acidic oxygen evolution reaction (OER) conditions greatly hinders its durability. Herein, we developed a strategy for stabilizing RuO2 in acidic OER by the incorporation of high-valence metals with suitable ionic electronegativity. A molten salt method was employed to synthesize a series of high-valence metal-substituted RuO2 with large specific surface areas. The experimental results revealed that a high content of surface Ru4+ species promoted the OER intrinsic activity of high-valence doped RuO2. It was found that there was a linear relationship between the ratio of surface Ru4+/Ru3+ species and the ionic electronegativity of the dopant metals. By regulating the ratio of surface Ru4+/Ru3+ species, incorporating Re, with the highest ionic electronegativity, endowed Re0.1Ru0.9O2 with exceptional OER activity, exhibiting a low overpotential of 199 mV to reach 10 mA cm−2. More importantly, Re0.1Ru0.9O2 demonstrated outstanding stability at both 10 mA cm−2 (over 300 h) and 100 mA cm−2 (over 25 h). The characterization of post-stability Re0.1Ru0.9O2 revealed that Re promoted electron transfer to Ru, serving as an electron reservoir to mitigate excessive oxidation of Ru sites during the OER process and thus enhancing OER stability. We conclude that Re, with the highest ionic electronegativity, attracted a mass of electrons from Ru in the pre-catalyst and replenished electrons to Ru under the operating potential. This work spotlights an effective strategy for stabilizing cost-effective Ru-based catalysts for acidic OER.    

    

* Iron-Nickel Synergistic Catalysis Growth of (Fe,Ni)9s8/Ni3s2@Nsc Bridged Nanowires Enhanced Oxygen Evolution Reaction Performance  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391661226
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4721170")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391661226"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391661226"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391661226"))][Get cited by]]

OpenAlex: https://openalex.org/W4391661226 (Open access: False)
    
[[https://openalex.org/A5034640620][Yixuan Bai]], [[https://openalex.org/A5011021780][Ping Fu]], [[https://openalex.org/A5006025957][Yuan Gao]], [[https://openalex.org/A5009053522][Qinglin Cheng]], [[https://openalex.org/A5062895804][Jiacheng Wang]], [[https://openalex.org/A5037822353][Xingmei Guo]], [[https://openalex.org/A5089961428][Wenhui Xiong]], [[https://openalex.org/A5042533912][Xiaofang Cheng]], [[https://openalex.org/A5000158966][Fenfen Zheng]], [[https://openalex.org/A5031851806][Junhao Zhang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4721170 
     
Improving the conductivity of the electrocatalyst itself is essential for enhancing its performance. In this work, a novel Fe, Ni bimetallic porous coordination polymers (PCPs) was synthesized, featuring a ligand composed of N, S-rich 6-thioguanine. Through bimetallic synergistic catalysis and self-sulfurization, this bimetallic PCPs transforms into N, S co-doped carbon (NSC)-coated (Fe,Ni)9S8/Ni3S2 bridged nanowires. Due to N, S co-doped (Fe,Ni)9S8/Ni3S2@NSC bridged nanowires, additional electrocatalytic active sites are provided, while the interconnected nanowires simultaneously enhance the overall conductivity of the catalyst. The as-obtained (Fe,Ni)9S8/Ni3S2@NSC exhibits excellent OER performance, with an overpotential as low as 252 mV at a current density of 10 mA cm-2. The work proposes a strategy to enhance the overall conductivity of the catalyst by transition metal sulfides bridged nanowires, which are derived through the processes of metal-PCPs self-sulfurization and bimetallic synergistic catalytic growth. It provides new insights and inspiration for the design and preparation of advanced transition metal sulfides electrocatalysts.    

    

* Intrinsic Specific Activity Enhancement for Bifunctional Electrocatalytic Activity toward Oxygen and Hydrogen Evolution Reactions via Structural Modification of Nickel Organophosphonates  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391677825
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.3c03960")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391677825"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391677825"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391677825"))][Get cited by]]

OpenAlex: https://openalex.org/W4391677825 (Open access: False)
    
[[https://openalex.org/A5043127385][Poojita]], [[https://openalex.org/A5084882176][Tanmay Rom]], [[https://openalex.org/A5022351799][Rathindranath Biswas]], [[https://openalex.org/A5016250642][Krishna Kanta Haldar]], [[https://openalex.org/A5052573254][Avijit Kumar Paul]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.3c03960 
     
A comprehensive knowledge of the structure–activity relationship of the framework material is decisive to develop efficient multifunctional electrocatalysts. In this regard, two different metal organophosphonate compounds, [Ni(Hhedp)2]·4H2O (I) and [Ni3(H3hedp)2(C4H4N2)3]·6H2O (II) have been isolated through one-pot hydrothermal strategy by using H4hedp (1-hydroxyethane 1,1-diphosphonic acid) and N-donor auxiliary ligand (pyrazine; C4H4N2). The structures of synthesized materials have been established through single-crystal X-ray diffraction studies, which confirm that compound I formed a one-dimensional molecular chain structure, while compound II exhibited a three-dimensional extended structure. Further, the crystalline materials have participated as efficient electrocatalysts for the oxygen evolution and hydrogen evolution reactions (OER and HER) as compared to the state-of-the-art electrocatalyst RuO2. The electrocatalytic OER and HER performances show that compound II displayed better electrocatalytic performances toward OER (η10 = 305 mV) and HER (η10 = 230 mV) in alkaline (1 M KOH) and acidic (0.5 M H2SO4) media, respectively. Substantially, the specific activity has been assessed in order to measure the inherent electrocatalytic activity of the title electrocatalyst, which displays an enrichment of fourfold higher activity of compound II (0.64 mA/cm2) than compound I (0.16 mA/cm2) for the OER experiments. Remarkably, inclusion of an auxiliary pyrazine ligand into the metal organophosphonate structure (compound II) not only offers higher dimensionality along with significant enhancement of the overall bifunctional electrocatalytic performances but also improves the long-term stability, which is noteworthy for the family of hybrid framework materials.    

    

* Fast‐Charging Zinc‐Air Batteries with Stable Bifunctional Oxygen Electrocatalysis of Mo‐Induced Nanodefective Mo─Co/N─C Catalyst  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391680217
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202314622")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391680217"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391680217"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391680217"))][Get cited by]]

OpenAlex: https://openalex.org/W4391680217 (Open access: False)
    
[[https://openalex.org/A5074456770][Y. Zhang]], [[https://openalex.org/A5019450834][Xiaoli Ma]], [[https://openalex.org/A5008295784][Zhendong Cheng]], [[https://openalex.org/A5090866405][Jingwen Wang]], [[https://openalex.org/A5026265288][Guobin Wen]], [[https://openalex.org/A5014636172][Lin Yang]], [[https://openalex.org/A5051237478][Zhengyu Bai]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202314622 
     
Abstract Fast‐charging technology plays a pivotal role in propelling the commercialization of zinc‐air batteries (ZABs). While the lifetime of ZABs under fast‐charging is severely shortened by the abundant O 2 bubbles and the deactivation of the cathode catalysts. Herein, a defective Mo─Co / N─C electrocatalyst is presented with Co nanoparticles and molybdenum‐oxo subnano clusters by pyrolyzing the Lindqvist polyoxometalate incorporated ZIF‐67 precursor. The crystalline defects are exacerbated by doping the polyoxometalate into the pores of ZIF‐67. Furthermore, the accessibility of the pore defects is increased by Mo‐leaching during the pre‐activation. These accessible pore defects effectively prevent the exfoliation of catalysts from the support under the attack of O 2 bubbles, and improve the electrolyte penetration. Besides, the pore defects offer numerous active sites for the electrocatalytic reactions, resulting in an active and stable Mo─Co / N─C catalyst. Hence, such a Mo─Co / N─C electrocatalyst achieves a long lifetime of 1538 h at 5 mA cm −2 , and a long lifetime of 641 h under a fast charge of 50 mA cm −2 in the homemade ZAB. The unique components and operational mechanisms propel scientists to portray splendid blueprints for durable fast‐charging ZABs for potential industrial applications.    

    

* Fe-Based Metal Organic Framework-Derived FeNiP/N-Doped Carbon Heterogeneous Core–Shell Structures for Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391684595
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.3c04512")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391684595"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391684595"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391684595"))][Get cited by]]

OpenAlex: https://openalex.org/W4391684595 (Open access: False)
    
[[https://openalex.org/A5038834523][Yijia Cao]], [[https://openalex.org/A5043533591][Yunfang Yan]], [[https://openalex.org/A5057814323][Yan Wen]], [[https://openalex.org/A5086361638][Mengya Cao]], [[https://openalex.org/A5041756956][Yanrong Liu]], [[https://openalex.org/A5085237771][Haijiao Xie]], [[https://openalex.org/A5003733633][Wen Gu]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.3c04512 
     
It is of great significance to explore high activity, low overpotential, and outstanding durability electrocatalysts without precious metals for oxygen evolution reaction to reduce the energy consumption in the electrolysis of water to product hydrogen. Metal organic frameworks (MOFs) with periodic structure and uniform pore distribution have been widely used as precursors for the synthesis of transition metal electrocatalysts. Herein, we first synthesized nanoscale Fe-soc-MOFs with relatively high specific surface area and in situ converted it into nickel–iron double layer hydroxide/MOF (FeNi LDH/MOF) by Ni2+ etching. Finally, a nickel–iron phosphide/nitrogen-doped carbon cubic nanocage (FeNiP/NC) was obtained by calcination and phosphating. FeNiP/NC with its unique core–shell structure has an overpotential of only 240 mV at a current density of 10 mA/cm2 and can be continuously electrolyzed for 45 h. High catalytic activity of FeNiP/NC is mainly attributed to the action of Fe and Ni bimetals and the synergistic effect between FeNiP and N-doped porous carbon, which was confirmed by the calculation of density functional theory (i.e., Gibbs free energy). After a long period of electrolysis, FeNiP was converted to MOOH (M = Fe and Ni) and became the new active site. This study provides a feasible optimization strategy for the development of high-efficiency three-dimensional electrode materials without precious metals.    

    

* Copper-doped nickel oxide supported on carbon black for highly active oxygen reduction/evolution electrocatalysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391685515
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mtcomm.2024.108335")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391685515"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391685515"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391685515"))][Get cited by]]

OpenAlex: https://openalex.org/W4391685515 (Open access: True)
    
[[https://openalex.org/A5026460845][Junkai Zhang]], [[https://openalex.org/A5031191155][Xiangqun Zhuge]], [[https://openalex.org/A5046775442][Tong Liu]], [[https://openalex.org/A5049286118][Kun Luo]], [[https://openalex.org/A5018494730][Jiayin Lyu]], [[https://openalex.org/A5001008654][Yurong Ren]], [[https://openalex.org/A5039774761][Yibing Li]], [[https://openalex.org/A5025751238][Xing Li]], Materials Today Communications. None(None)] 2024. https://doi.org/10.1016/j.mtcomm.2024.108335 
     
No abstract    

    

* Enhancing DMC Production from CO2: Tuning Oxygen Vacancies and In Situ Water Removal  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391693710
:TOPICS: Carbon Dioxide Utilization for Chemical Synthesis, Catalytic Nanomaterials, Catalytic Carbon Dioxide Hydrogenation
:PUBLICATION_DATE: 2024-02-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17040839")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391693710"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391693710"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391693710"))][Get cited by]]

OpenAlex: https://openalex.org/W4391693710 (Open access: True)
    
[[https://openalex.org/A5038799334][K Wang]], [[https://openalex.org/A5039113462][Shiguang Li]], [[https://openalex.org/A5009622925][Miao Yu]], [[https://openalex.org/A5037935776][Xinhua Liu]], Energies. 17(4)] 2024. https://doi.org/10.3390/en17040839  ([[https://www.mdpi.com/1996-1073/17/4/839/pdf?version=1707492701][pdf]])
     
The direct synthesis of dimethyl carbonate (DMC) from methanol and CO2 presents an attractive route to turn abundant CO2 into value-added chemicals. However, insufficient DMC yields arise due to the inert nature of CO2 and the limitations of reaction equilibrium. Oxygen vacancies are known to facilitate CO2 activation and improve catalytic performance. In this work, we have demonstrated that tuning oxygen vacancies in catalysts and implementing in situ water removal can enable highly efficient DMC production from CO2. CexZryO2 nanorods with abundant oxygen vacancies were synthesized via a hydrothermal method. In liquid-phase DMC synthesis, the Ce10Zr1O2 nanorods exhibited a 1.7- and 1.4-times higher DMC yield compared to CeO2 nanoparticles and undoped CeO2 nanorods, respectively. Zr doping yielded a CeZr solid solution with increased oxygen vacancies, promoting CO2 adsorption and activation. In addition, adding 2-cyanopyridine as an organic dehydrating agent achieved an outstanding 87% methanol conversion and >99% DMC selectivity by shifting the reaction equilibrium to the desired product. Moreover, mixing CeO2 nanoparticles with hydrophobic fumed SiO2 in gas-phase DMC synthesis led to a doubling of DMC yield. This significant increase was attributed to the faster diffusion of water molecules away from the catalyst surface, facilitated by the hydrophobic SiO2. This study illustrates an effective dual strategy of enhancing oxygen vacancies and implementing in situ water removal to boost DMC production from CO2. The strategy can also be applied to other reactions impacted by water accumulation.    

    

* Unleashing the potential of NiO@V2CTx MXene-derived electrocatalyst for hydrogen and oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391716775
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.322")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391716775"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391716775"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391716775"))][Get cited by]]

OpenAlex: https://openalex.org/W4391716775 (Open access: False)
    
[[https://openalex.org/A5086260024][Usman Naeem]], [[https://openalex.org/A5017725687][Syedah Afsheen Zahra]], [[https://openalex.org/A5082415645][Irfan Ali]], [[https://openalex.org/A5079134604][Hu Li]], [[https://openalex.org/A5065478955][Asif Mahmood]], [[https://openalex.org/A5060386189][Syed Rizwan]], International Journal of Hydrogen Energy. 59(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.01.322 
     
No abstract    

    

* Enhanced Synergistic Redox Activity of SrCoS/PANI for Hybrid Energy Storage and Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391740608
:TOPICS: Perovskite Solar Cell Technology, Electrocatalysis for Energy Conversion, Conducting Polymer Research
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1402-4896/ad28a4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391740608"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391740608"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391740608"))][Get cited by]]

OpenAlex: https://openalex.org/W4391740608 (Open access: False)
    
[[https://openalex.org/A5081199332][Haseeb ul Hassan]], [[https://openalex.org/A5014807301][Muhammad Waqas Iqbal]], [[https://openalex.org/A5038684951][Sameer Akbar]], [[https://openalex.org/A5067573568][Amir Muhammad Afzal]], [[https://openalex.org/A5004587425][Ehtisham Umar]], [[https://openalex.org/A5062023379][S. Noor Mohammad]], [[https://openalex.org/A5028053376][Asma A. Alothman]], [[https://openalex.org/A5018554406][Niaz Ahmad]], [[https://openalex.org/A5091256421][Ehsan Elahi]], Physica Scripta. None(None)] 2024. https://doi.org/10.1088/1402-4896/ad28a4 
     
Abstract Supercapacitors (SCs) and secondary batteries (SBs) are commonly utilized for energy storage, although each has some limitations: low energy density (Ed) and power density (Pd), respectively. To address these issues, a hybrid supercapacitor is a new emerging technique known as supercapattery, which combines both of these devices to optimum the Ed and Pd in a single setting. The hydrothermal method was adopted to synthesize a cost-effective, eco-friendly, and non-toxic SrCoS/PANI, a composite material for optimum results of supercapattery. Crystallinity and morphology study of synthesized nanocomposites strontium cobalt sulfide with Polyaniline (SrCoS/PANI) were examined using SEM and XRD techniques. Initially, the performance was tested using a three-electrode setup of nanocomposites (SrCoS/PANI) in 1 M KOH electrolyte. The effectiveness of a SrCoS/PANI-activated carbon two-electrode supercapattery was examined through cyclic CV, GCD, and EIS techniques. In the two electrodes setup, the device performs admirably with an astonishing specific capacity of 139.4 C/g, a high Ed of 29.56 Wh/kg, and a high Pd of 800 W/kg at 1.0 A/g. The cyclic stability was tested by putting the device through 5000 charging and discharging cycles, which maintained 91.65 % of its Specific capacity (Qs). A hybrid nanocomposite (SrCoS/PANI) device was accomplished, with exceptional electrochemical capabilities at a low price making them a fascinating active material with potential applications in supercapattery technology. The electrocatalytic performance of the synthesized nanostructure (NSs) was studied comprehensively with regard to an oxygen evolution reaction (OER).    

    

* Cathodized Stainless Steel Mesh for Binder-Free NiFe<sub>2</sub>O<sub>4</sub>/NiFe Layer Double Hydroxides Oxygen Evolution Reaction Electrode  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391748095
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.4028/p-1bmxjg")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391748095"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391748095"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391748095"))][Get cited by]]

OpenAlex: https://openalex.org/W4391748095 (Open access: True)
    
[[https://openalex.org/A5092884124][Natthapon Sripallawit]], [[https://openalex.org/A5081163390][Soorathep Kheawhom]], Engineering Innovations. 9(None)] 2024. https://doi.org/10.4028/p-1bmxjg  ([[https://www.scientific.net/EI.9.23.pdf][pdf]])
     
Oxygen evolution reaction (OER) is an essential reaction commonly applied in various energy storage and conversion technologies. One of the common issues of OER lies in its low kinetic activity. Therefore, developing durable, low-cost, and high-performance OER catalysts is critical. Recently, many attempts have used stainless steel mesh (SSM) as the substrate for OER electrodes because SSM is abundant, cheap, and durable. Nickel/iron-based materials, i.e., NiFe 2 O 4 /NiFe layer double hydroxides (LDHs), are regarded as one of the most excellent OER catalysts in alkaline electrolytes, making them attractive low-cost materials for OER catalysts. However, synthesizing NiFe 2 O 4 /NiFe LDHs directly on the surface of SSM is challenging. Modifying the SSM surface through cathodization has proved to enhance the adhesion and OER activity. Moreover, the cathodization technique is facile and cost-effective. In this work, the surface of SSM is modified by cathodization treatment. Subsequently, NiFe 2 O 4 /NiFe LDHs are deposited onto the surface of treated SSM via a low-temperature one-step chemical bath deposition technique. This synthesis is a binder-free method; the resulted electrodes show excellent OER performance without the binder effects. The as-prepared electrodes have a small Tafel slope of 125.4 mV/dec (1 M KOH) and high durability (10 mA/cm2 for 50 hours).    

    

* Hierarchically Designed Co4Fe3@N-Doped Graphitic Carbon as an Electrocatalyst for Oxygen Evolution in Anion-Exchange-Membrane Water Electrolysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391748270
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.energyfuels.3c04077")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391748270"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391748270"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391748270"))][Get cited by]]

OpenAlex: https://openalex.org/W4391748270 (Open access: False)
    
[[https://openalex.org/A5088370461][S.J. Park]], [[https://openalex.org/A5077337831][Jong Han Jun]], [[https://openalex.org/A5005381654][Minjeong Park]], [[https://openalex.org/A5051461491][Jaehoon Jeong]], [[https://openalex.org/A5091716352][Jae-Young Jo]], [[https://openalex.org/A5005779186][Sohee Jeon]], [[https://openalex.org/A5088908902][Juchan Yang]], [[https://openalex.org/A5091482435][Sung Mook Choi]], [[https://openalex.org/A5039897928][Wook Jo]], [[https://openalex.org/A5041248271][Ji-Hoon Lee]], Energy & Fuels. None(None)] 2024. https://doi.org/10.1021/acs.energyfuels.3c04077 
     
No abstract    

    

* Operando Tracking the Interactions between CoOx and CeO2 during Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391754627
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202303529")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391754627"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391754627"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391754627"))][Get cited by]]

OpenAlex: https://openalex.org/W4391754627 (Open access: True)
    
[[https://openalex.org/A5016903963][Jinzhen Huang]], [[https://openalex.org/A5071707273][Natasha Hales]], [[https://openalex.org/A5015698882][Adam H. Clark]], [[https://openalex.org/A5065498532][Nur Sena Yüzbasi]], [[https://openalex.org/A5057560048][Camelia N. Borca]], [[https://openalex.org/A5010118109][Thomas Huthwelker]], [[https://openalex.org/A5084722596][Thomas J. Schmidt]], [[https://openalex.org/A5015187859][Emiliana Fabbri]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202303529  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/aenm.202303529][pdf]])
     
Abstract CeO 2 greatly enhances the electrocatalytic oxygen evolution reaction (OER) activity of CoO x , though the enhancement mechanism beyond this synergy is yet to be understood. Here, operando hard X‐ray absorption spectroscopy (hXAS) is applied to monitor the Co K edge and Ce L 3 edge in CoO x /CeO 2 to shed light on the evolution of the Co and Ce oxidation states during OER. In addition, ex situ soft XAS (sXAS) characterizations provide information on the irreversible surface‐specific transformations of the Co L 3 edge as well as of the O K edge. Combining the operando and ex situ spectroscopic characterizations with comprehensive electrochemical analyses, it is confirmed that CeO 2 is not the active center for the OER. However, coupling CeO 2 with CoO x introduces significant modifications in the Co and O species at the CoO x surface and alters the flat band potential (E fb ), leading to more favorable Co oxidation state transformations during OER and possibly modifying the preferential reaction pathway. This work establishes the connections between electronic structures, Co oxidation state and the OER reaction mechanism for CoO x /CeO 2 composites electrodes.    

    

* Au Micro‐ and Nanoelectrodes as Local Voltammetric pH Sensors During Oxygen Evolution at Electrocatalyst‐Modified Electrodes  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391757154
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Advances in Chemical Sensor Technologies, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smsc.202300283")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391757154"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391757154"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391757154"))][Get cited by]]

OpenAlex: https://openalex.org/W4391757154 (Open access: True)
    
[[https://openalex.org/A5085572041][Lejing Li]], [[https://openalex.org/A5011826961][Ndrina Limani]], [[https://openalex.org/A5059434245][Rajini P. Antony]], [[https://openalex.org/A5087903038][Stefan Dieckhöfer]], [[https://openalex.org/A5048293568][Carla Santana Santos]], [[https://openalex.org/A5035321019][Wolfgang Schuhmann]], Small science. None(None)] 2024. https://doi.org/10.1002/smsc.202300283 
     
The scarcity of state‐of‐the‐art oxygen evolution reaction (OER) electrocatalysts has led to intensive research on alternative viable electrocatalytic materials. While activity and cost are the main factors to be sought after, the catalyst stability under harsh acidic conditions is equally crucial. Considering that OER is a proton‐coupled electron‐transfer reaction that involves local acidification of the reaction environment by liberation of H + , the catalyst stability can be largely compromised in such conditions. Consequently, probing the pH value near the catalyst surface under operation leads to a deeper understanding of this process. The applicability of bare Au microelectrodes and nanoelectrodes as sensitive local pH probes during OER is shown in this work by using scanning electrochemical microscopy (SECM). Two case studies are presented, including the state‐of‐the‐art OER catalyst (IrO 2 ) in acidic media and a ZnGa 2 O 4 catalyst in alkaline buffered solution, demonstrating the suitability of the Au probe to accurately determine the local pH value in a wide pH range.    

    

* Experimental evidences of the direct influence of external magnetic fields on the mechanism of the electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391766798
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0179761")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391766798"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391766798"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391766798"))][Get cited by]]

OpenAlex: https://openalex.org/W4391766798 (Open access: True)
    
[[https://openalex.org/A5027965963][Camilo A. Mesa]], [[https://openalex.org/A5024363203][Felipe A. Garcés‐Pineda]], [[https://openalex.org/A5084426798][Miguel García‐Tecedor]], [[https://openalex.org/A5025789790][Jiahao Yu]], [[https://openalex.org/A5041069274][Bahareh Khezri]], [[https://openalex.org/A5071490785][Sergi Plana-Ruiz]], [[https://openalex.org/A5046172165][Bruno López]], [[https://openalex.org/A5067239975][R. Iturbe]], [[https://openalex.org/A5066694116][Núria López]], [[https://openalex.org/A5053858976][Sixto Giménez]], [[https://openalex.org/A5028397745][José Ramón Galán‐Mascarós]], APL Energy. 2(1)] 2024. https://doi.org/10.1063/5.0179761  ([[https://pubs.aip.org/aip/ape/article-pdf/doi/10.1063/5.0179761/19638236/016106_1_5.0179761.pdf][pdf]])
     
The use of magnetic fields as external stimuli to improve the kinetics of electrochemical reactions is attracting substantial attention, given their potential to reduce energy losses. Despite recent reports showing a positive effect on catalytic performance upon applying a magnetic field to a working electrode, there are still many uncertainties and a lack of experimental evidence correlating the presence of the magnetic field to the electrocatalytic performance. Here, we present a combination of electrochemical and spectroscopic tools that demonstrate how the presence of an external magnetic field alters the reaction mechanism of the electrocatalytic oxygen evolution reaction (OER), accelerating the overall performance of a Ni4FeOx electrode. Complementary experimental evidence has been gathered supporting the participation of this microscopic magnetic field effect. Electrochemical impedance spectroscopy (EIS) points to a speed-up of the intrinsic reaction kinetics, independent of other indirect effects. In the same direction, the spectro-electrochemical fingerprint of the intermediate species that appear during the electrocatalytic cycle, as detected under operando conditions, indicates a change in the order of the reaction as a function of hole accumulation. All these experimental data confirm the direct influence of an external magnetic field on the reaction mechanism at the origin of the magnetically enhanced electrocatalytic OER.    

    

* Limitations of Chronopotentiometry Test Protocols for Stability Study on Oxygen Evolution Reaction Electrocatalysts and Recommendations  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391766804
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.3c07103")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391766804"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391766804"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391766804"))][Get cited by]]

OpenAlex: https://openalex.org/W4391766804 (Open access: False)
    
[[https://openalex.org/A5037679725][Inayat Ali Khan]], [[https://openalex.org/A5044593278][Per Morgen]], [[https://openalex.org/A5028577447][Raghunandan Sharma]], [[https://openalex.org/A5032516491][Shuang Ma Andersen]], The Journal of Physical Chemistry C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.3c07103 
     
The stability studies, using a rotating disk electrode under a constant current, are commonly used for the development of the oxygen evolution reaction (OER) electrocatalyst, where rise in potential with time is reported to be due to the electrocatalyst degradation. Here, we present a careful examination on the use of this technique on commercial IrO2 electrocatalysts in acidic media for a duration of 9 h. We observed that a sudden rise in the electrode potential after ∼6 h is rather due to the glassy carbon surface-edge corrosion and detachment between carbon–catalyst interfaces. Indeed, the layer detachment generates an insulating gap between the electrode and carbon layer, resulting in an increase in the cell potential. On this regard, we examine and recommend a potentiodynamic stability test as a reliable and practical method for fast material screening and for the development of OER electrocatalysts.    

    

* Interplay between Defects and Short-Range Disorder Manipulating the Oxygen Evolution Reaction on a Layered Double Hydroxide Electrocatalyst  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391773871
:TOPICS: Electrocatalysis for Energy Conversion, Layered Double Hydroxide Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.3c02885")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391773871"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391773871"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391773871"))][Get cited by]]

OpenAlex: https://openalex.org/W4391773871 (Open access: False)
    
[[https://openalex.org/A5014502114][Zixian Li]], [[https://openalex.org/A5042488059][Jiangrong Yang]], [[https://openalex.org/A5013553103][Rui Gao]], [[https://openalex.org/A5033474784][Simin Xu]], [[https://openalex.org/A5035045458][Xianggui Kong]], [[https://openalex.org/A5029898691][Xiao Hua]], [[https://openalex.org/A5047701790][Pu Zhao]], [[https://openalex.org/A5036474813][Haigang Hao]], [[https://openalex.org/A5067218691][Dermot O’Hare]], [[https://openalex.org/A5019565719][Yufei Zhao]], The Journal of Physical Chemistry Letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.3c02885 
     
Improving the efficiency of the oxygen evolution reaction (OER) is crucial for advancing sustainable and environmentally friendly hydrogen energy. Layered double hydroxides (LDHs) have emerged as promising electrocatalysts for the OER. However, a thorough understanding of the impact of structural disorder and defects on the catalytic activity of LDHs remains limited. In this work, a series of NiAl-LDH models are systematically constructed, and their OER performance is rigorously screened through theoretical density functional theory. The acquired results unequivocally reveal that the energy increase induced by structural disorder is effectively counteracted at the defect surface, indicating the coexistence of defects and disorder. Notably, it is ascertained that the simultaneous presence of defects and disorder synergistically augments the catalytic activity of LDHs in the context of the OER. These theoretical findings offer valuable insights into the design of highly efficient OER catalysts while also shedding light on the efficacy of LDH electrocatalysts.    

    

* FeCoNi molybdenum-based oxides for efficient electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391774742
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.02.104")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391774742"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391774742"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391774742"))][Get cited by]]

OpenAlex: https://openalex.org/W4391774742 (Open access: False)
    
[[https://openalex.org/A5051102233][Weiliu Fan]], [[https://openalex.org/A5022846124][Chaofan Liu]], [[https://openalex.org/A5082475531][Hairong Wang]], [[https://openalex.org/A5003062406][Jiang Wu]], [[https://openalex.org/A5008768156][Sheng Chen]], [[https://openalex.org/A5030622927][Weijie Fang]], [[https://openalex.org/A5064863955][C. D. Wu]], [[https://openalex.org/A5038726113][Yong Quan]], [[https://openalex.org/A5066475931][Daolei Wang]], [[https://openalex.org/A5020788231][Yongfeng Qi]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.02.104 
     
No abstract    

    

* Tri-metallic fluoride nanoplates immobilized on reduced graphene architectures as efficient oxygen evolution reaction catalyst  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391774927
:TOPICS: Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2024.118108")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391774927"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391774927"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391774927"))][Get cited by]]

OpenAlex: https://openalex.org/W4391774927 (Open access: False)
    
[[https://openalex.org/A5058891185][Yanhui Lu]], [[https://openalex.org/A5074088539][Chengang Pei]], [[https://openalex.org/A5085322409][Han Xu]], [[https://openalex.org/A5023214008][Yong Li]], [[https://openalex.org/A5076348504][Ho Seok Park]], [[https://openalex.org/A5052472508][Jung Kyu Kim]], [[https://openalex.org/A5090891492][Xu Yu]], Journal of Electroanalytical Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jelechem.2024.118108 
     
No abstract    

    

* The Effect of Oxygen Vacancies on Oxygen Evolution: The Case of BiVO_4  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391639104
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472281mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391639104"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391639104"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391639104"))][Get cited by]]

OpenAlex: https://openalex.org/W4391639104 (Open access: False)
    
[[https://openalex.org/A5074525188][Nicklas Österbacka]], [[https://openalex.org/A5023146568][Hassan Ouhbi]], [[https://openalex.org/A5081702682][Julia Wiktor]], [[https://openalex.org/A5040182388][Francesco Ambrosio]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472281mtgabs 
     
Bismuth vanadate, BiVO 4 , is one of the most promising photoanode materials for the challenging oxygen evolution half-reaction in solar-driven water splitting. The material tends to be rich in oxygen vacancies, which strongly affects its photoelectrochemical properties. Experimental evidence suggests that oxygen deficiency is beneficial for the oxygen evolution reaction in the material, but the mechanism behind this enhancement is still controversial. The defects could be involved directly in the reaction if present at the surface, and the occupancy of the defect states could also play an important role. The latter is seldom considered in mechanistic studies, however. Using density functional theory, we show that the surface oxygen vacancy in bismuth vanadate is stablest when fully ionized. We investigate how this affects the oxygen evolution mechanism by mapping out the stablest reaction intermediates and compare the resulting pathway with those on the unionized oxygen-deficient surface as well as the defect-free material. The overpotentials required to drive the reaction in each case are computed to quantify whether or not vacancy formation, and subsequent ionization, improves the thermodynamics of oxygen evolution.    

    

* Electrodeposited Ni-Based Catalysts for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663002
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02201255mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663002"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663002"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663002"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663002 (Open access: False)
    
[[https://openalex.org/A5035874732][Yashwardhan Deo]], [[https://openalex.org/A5034662410][Niklas Thissen]], [[https://openalex.org/A5057402984][Anna K. Mechler]], ECS Meeting Abstracts. MA2023-02(20)] 2023. https://doi.org/10.1149/ma2023-02201255mtgabs 
     
Alkaline water electrolysis is one of the most mature technologies for producing green hydrogen. However, there still are possibilities to enhance this process by using better electrocatalysts for the kinetically limited oxygen evolution reaction (OER). While there are several existing methods for catalyst synthesis, such as spray coating, coprecipitation and hydrothermal synthesis, they face challenges of either versatility or scalability. [1,2] In this regard, electrodeposition is a promising catalyst synthesis method, due to its excellent process control and ease of scalability. In this work, electrodeposition is used to prepare nickel-based catalysts as a benchmark system. These catalysts are deposited on expanded Ni-mesh supports. Initially, the deposition parameters are optimized to obtain uniform Ni deposits, which provide reproducible activity measurements. Herein, we observe that the deposited Ni catalysts exhibit better OER activities than the Ni mesh support, most likely due to the evolution of a pyramidal morphology with an increased surface area (Fig. 1). The optimized deposition parameters are further used to deposit different Ni-based alloys such as Ni-Fe and Ni-Co, by adding the respective ionized metal species to the Ni electrolyte. The microstructure and composition of these catalysts is analyzed using material characterization techniques like scanning electron microscopy (SEM) and energy dispersive X-ray spectroscopy (EDX). Finally, the OER activity and long-term stability of the deposited catalysts is evaluated in an in-house developed electrochemical beaker cell at elevated concentration, temperature, and current densities (30 wt.% KOH, 80 °C, up to 1 A/cm 2 ). The results obtained for the different catalysts are compared to understand the correlation of the catalyst structure and composition with their electrochemical OER performance under industrial conditions. Bibliography [1] Lu Xunyu et al.; Nature Communications; DOI: 10.1038/ncomms7616 [2] Zuraya Angeles-Olvera et al.; Energies ; DOI: 10.3390/en15051609 Figure 1    

    

* Electrocatalytic Activities of High-Entropy Oxides for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638064
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542604mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638064"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638064"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638064"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638064 (Open access: False)
    
[[https://openalex.org/A5004247415][Yun-Hyuk Choi]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542604mtgabs 
     
Electrocatalytic water-splitting hydrogen generation consists of the cathodic hydrogen evolution reaction (HER) and the anodic oxygen evolution reaction (OER), where the four-electron-relevant OER is the rate-determining step. So far, there have been many efforts to substitute for the highly expensive noble-metal electrocatalysts (platinum, ruthenium or rhodium oxides, etc.). Transition-metal oxides based on Co, Ni, Mn, and V have been suggested as such alternatives, due to their low cost, high efficiency, and high stability. Recently, since the compositional diversity can provide a new breakthrough in that area, a high-entropy oxide (HEO) with five transition-metal cations has been suggested as a promising electrocatalyst toward the OER. In our studies, two kinds of HEOs were prepared and their OER activities were investigated. To begin with, for the (Mg 0.2 Fe 0.2 Co 0.2 Ni 0.2 Cu 0.2 )O, the effect of constituent cations on the OER activity was unveiled. Furthermore, a core cation driving the high OER activity was found. For it, the medium-entropy oxides (MEOs) with four cations are prepared by subtracting each cation (Mg, Fe, Co, Ni, or Cu) from the HEO, exhibiting homogeneous morphology, equiatomic composition, and single-phase rocksalt structure. As a result, it is found that the highest concentration of Co 3+ in the MEO (w/o Cu) leads to the best OER activity, and thus Co 3+ is the core ion driving the high OER activity. Furthermore, it is regarded that Cu 2+ ions prevent the conversion of Co or Fe cations from 2 + to 3 + in the HEO and MEOs. Accordingly, maximizing the concentration of Co 3+ within electrocatalysts is suggested as an effective design strategy for the high-efficiency electrocatalysts based on high or medium entropy materials. Secondly, the relationship between structure and OER activity was elucidated for the (Mg 0.2 Fe 0.2 Co 0.2 Zn 0.2 Cu 0.2 )O with a temperature-dependent rocksalt-to-spinel transition.    

    

* Oxygen Evolution Reaction with ZrCo and ZrNi Electrode Materials  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638760
:TOPICS: Fuel Cell Membrane Technology, Nuclear Fuel Development, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422147mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638760"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638760"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638760"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638760 (Open access: False)
    
[[https://openalex.org/A5050317844][Sylvain Le Tonquesse]], [[https://openalex.org/A5021396945][S. G. Altendorf]], [[https://openalex.org/A5072072076][Yuri Grin]], [[https://openalex.org/A5083007953][Iryna Antonyshyn]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422147mtgabs 
     
Investigation of the intermetallic compounds as anode materials for water electrolysis helps to solve a lot of issues, which electrocatalysis and solid state chemistry communities face nowadays. Intermetallic compounds possess unique properties in terms of their crystal structure, electronic properties and chemical bonding, allowing the knowledge-based route for electrocatalyst development. Furthermore, usage of the single-phase anode material is a way to exclude the influence of interface as well as nature and stability issues of the support. At the same time, studies of the intermetallic compounds under the reaction conditions shed light onto the chemical properties of the intermetallic compounds, which are scarcely described in literature and of particular importance for solid state chemistry field. In this study, binary intermetallic compounds ZrCo and ZrNi were studied as anode materials for alkaline water electrolysis. The successful synthesis of single-phase samples of both compounds was followed by manufacturing of the cylindrically-shaped electrodes using spark plasma sintering technique. The assessment of the electrocatalytic performance was carried out in three-electrode cell, applying different measurement protocols, giving the information about OER activity of studied materials, its stability over time as well as other electrochemical features, giving the information about the processes occurring on the electrode surfaces. To monitor the material changes under conditions of OER, the electrodes were comprehensively characterized before and after the electrochemical experiments using bulk- and surface-sensitive techniques. Combined data was discussed and compared with state-of-the-art OER electrocatalysts for alkaline media.    

    

* Gas Diffusion Electrode for Oxygen Evolution Reaction Catalyst Testing  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638856
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02371726mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638856"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638856"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638856"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638856 (Open access: False)
    
[[https://openalex.org/A5056872364][Vinod Kumar Puthiyapura]], [[https://openalex.org/A5030674093][Christopher Mark Zalitis]], [[https://openalex.org/A5015505628][James Stevens]], ECS Meeting Abstracts. MA2023-02(37)] 2023. https://doi.org/10.1149/ma2023-02371726mtgabs 
     
The oxygen evolution reaction (OER) is one of the major contributors of efficiency loss in water electrolysis and consequently, development of OER catalysts to improve the electrolyser efficiency is a major reasearch theme in the field. Though the current commercial PEMWE may operate at anode potential <1.60 V, futue PEMWE may operate at potential higher than this as the drive to operate PEMWE at high current density is inceasing. Inorder to achieve this, an active and stable catalyst is required that can operate at this regime. Also, the potential experienced by the anode during the startup/shutdown of an electrolyser are different to the steady state value. Conventional OER testing involves catalysts coated on a conductive substrate submerged in an electrolyte solution, in a three electrode cell. However, such techniques are generally limited to low current densities due to oxygen bubble formation and site blocking at high current density limiting the system to study the OER kinetics below realistic operating current density. Although Rotating Disk Electrode(RDE) is widely employed to mitigate this, the RDE system is still not effective enough to remove the bubbles 1 . A floating electrode system developed by Kucernak et al 2 shows that combining direct access with a lower catalyst loading improves the O 2 gas mass transport and a higher current density could be achieved for the ORR. This technique also used for OER by Arenz et al. 3 , for easier bubble removal. Combining these two above mentioned systems, we have developed a new GDE cell system which allows screening of OER catalyst at industrially relevant current densities. This cell allows to study the OER kinetics at very realistic voltage/current regime and the information obtained helps to develop more active/stable catalyst. The OER catalyst diagnostics test from our GDE cell was comparable to the standard three electrode cell with an additional advantage of extended potential window upto 1.80 V vs.RHE. Preliminary results obtained from our study shows a promising opportunity to study the OER at high current densities. Reference FathiTovini, A.Hartig-Weiß, H.A.Gasteigerand, H.A.El Sayed, Journal of The ElectrochemicalSociety, 2021, 168, 014512. M.Zalitis,D.KramerandA.R.Kucernak,Phys.Chem.Chem.Phys.,2013,15,4329-4340 Schröder,V.A.Mints,A.Bornet,E.Berner,M.FathiTovini,J.Quinson,etal., JACS Au 2021,1(3),247-25    

    

* Spin States and Spin Order in Perovskite Oxide Oxygen Evolution Electrocatalysts  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638550
:TOPICS: Electrocatalysis for Energy Conversion, Perovskite Solar Cell Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472304mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638550"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638550 (Open access: False)
    
[[https://openalex.org/A5021753479][Emma van der Minne]], [[https://openalex.org/A5015341693][Achim Füngerlings]], [[https://openalex.org/A5009841458][Marcus Wohlgemuth]], [[https://openalex.org/A5060923565][Gertjan Koster]], [[https://openalex.org/A5029467045][Felix Gunkel]], [[https://openalex.org/A5057481702][Rossitza Pentcheva]], [[https://openalex.org/A5003154231][Christoph Baeumer]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472304mtgabs 
     
The ‘power-to-hydrogen’ strategy aims at splitting water into O 2 and H 2 via the oxygen and hydrogen evolution reactions. The complex four-step oxygen evolution reaction (OER) limits the overall efficiency of hydrogen production. An important reason of the low efficiency is that the production of ground-state (triplet) O 2 is a spin-forbidden reaction: in fact, the reactants, OH - or H 2 O, are diamagnetic, but the final product, O 2 , is a paramagnetic molecule. Recently, this was well-recognized theoretically 1 and the use of spin selective catalysts was described as a possible way to promote the OER. 2 . However, it remains complex to understand and exploit intrinsic and extrinsic magnetic features to enhance catalytic performance. Here, we investigate the role of magnetic moments in individual active sites in the catalyst surface layer and the role of spin order in ferromagnetic vs. paramagnetic catalysts, focussing on perovskite oxides. First, we investigated the role of Ni magnetic moment in the the (001), (110) and (111) facet of LaNiO 3 electrocatalysts, which we studied using electrochemical measurements, X-ray photoelectron spectroscopy (XPS), X-ray absorption spectroscopy (XAS), and density functional theory (DFT+ U ) calculations. 3 The results show a facet-dependent activity, where the (111) overpotential is ~60 mV lower as compared to the other facets. Closer investigation of the (001) and (111) facets reveals a surface transformation to a oxyhydroxide-like NiOO with edge-sharing octahedra, 4 and we observed that the transformed surface is thicker for (111) than for (001). 3 The detailed DFT+ U analysis reveals important distinctions that give rise to the increased activity: the transformed LaNiO 3 (111) surface exhibits a better match to the underlying perovskite layer. Moreover, protonation induces reduced Ni 3+ with a finite magnetic moment. A moderate Jahn-Teller distortion enables a favorable binding of reaction intermediates. In contrast, the structural mismatch to the underlying LaNiO 3 (001)-substrate leads to a strong distortion of the transformed layer for this orientation and a weak binding of *O and ultimately to a different potential determining step (PDS), *OH→*O, compared to *O→*OOH for the transformed LaNiO 3 (111) surface. Second, we experimentally demonstrate the effect of intrinsic magnetic order on the OER on catalytic performance. Thin films of La 0.67 Sr 0.33 MnO 3 grown by pulsed laser deposition with appropriate magnetic and electronic properties were chosen as well-defined model systems. Using the ferromagnetic to paramagnetic transition at the Curie temperature in these ferromagnetic perovskite oxides, the magnetic order of the catalysts were switched in situ during the OER by changing the temperature. For ferromagnetic films, the decrease in current density with decreasing temperature, induced by the reduction of thermal energy, was suppressed for temperatures below the Curie temperature, indicating that the presence of ferromagnetic ordering below Curie temperature enhances OER activity. This claim is further supported by an enhancement of OER activity for the same ferromagnetic film upon alignment of magnetic domains with an external magnetic field. All in all, our results reveal that the spin state, intrinsic spin order, and extrinsic magnetic fields are decisive for the OER activity. Biz, C., Fianchini, M. & Gracia, J. Strongly Correlated Electrons in Catalysis: Focus on Quantum Exchange. ACS Catal 11 , 14249–14261 (2021). Sun, Y. et al. Spin‐Related Electron Transfer and Orbital Interactions in Oxygen Electrocatalysis. Advanced Materials 32 , 2003297 (2020). Füngerlings, A. et al. Crystal-facet-dependent surface transformation dictates the oxygen evolution reaction activity in lanthanum nickelate. in preparation (2023). Baeumer, C. et al. Tuning electrochemically driven surface transformation in atomically flat LaNiO 3 thin films for enhanced water electrolysis. Nat Mater 20 , 674–682 (2021).    

    

* Understanding the Role of Cracks in Active Oxygen Species Formation during Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663336
:TOPICS: Reinforcement Corrosion in Concrete Structures, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02653164mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663336"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663336"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663336"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663336 (Open access: False)
    
[[https://openalex.org/A5064222985][Sihong Wang]], [[https://openalex.org/A5081133273][Fang Song]], ECS Meeting Abstracts. MA2023-02(65)] 2023. https://doi.org/10.1149/ma2023-02653164mtgabs 
     
Understanding the formation and location of catalytic intermediates is crucial for unraveling the mechanism of oxygen evolution reaction (OER), a key process in electrochemical water splitting. Despite the availability of various in-situ and ex-situ characterization methods, the formation and location of intermediates remain elusive, hindering the development of more efficient electrocatalysts. In this work, we discovered a stable static active oxygen species formed during the chemical oxidation of cobalt hydroxide flakes, providing a unique opportunity to probe the intermediates involved in OER. We are able to monitor the equilibrium conversion between stable peroxo structure and superoxo radical via EPR and Raman test, shedding light on the nature of the active oxygen species. In addition, CoOOH flakes with cracks were synthesized via controlled chemical oxidation, enabling the investigation of the role of crack/edge structures in the electrocatalytic activity. Statistical regression analysis combining morphological features, electrochemical performance, and Raman spectroscopy confirmed a strong correlation between morphology evolution, OER activity, and active oxygen species, highlighting the importance of controlling the morphology of electrocatalysts for enhancing their performance. Therefore, we propose that the source of active oxygen intermediates can be attributed to the presence of crack/edge structures. The crack-rich CoOOH exhibit significantly higher current density at a lower overpotential, providing a new direction for the design of efficient water oxidation electrocatalysts. Overall, this work offers important insights into the mechanism of OER and provides a basis for the development of more efficient and sustainable electrocatalysts for energy conversion and storage.    

    

* Tungsten Oxide-Based Materials as Catalyst Support for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663247
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422096mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663247"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663247"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663247"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663247 (Open access: False)
    
[[https://openalex.org/A5044676059][Yung‐Tin Pan]], [[https://openalex.org/A5093893761][Lu Yu Chueh]], [[https://openalex.org/A5002345502][Yu-Wei Hsu]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422096mtgabs 
     
The high cost of iridium (Ir) is a major concern for the large scale deployment of polymer electrolyte membrane water electrolysis (PEMWE). To mitigate its impact, the usage of Ir on the anode must be significantly reduced. Down-sizing the catalyst particle is a straight forward strategy but requires the use of appropriate support materials to disperse and anchor fine Ir nanoparticles. We have investigated the use of tungsten oxide-based materials as support for the oxygen evolution reaction (OER) Ir and ruthenium (Ru) catalyst. The synthesis of nanostructured substoichiometric tungsten oxide and the subsequent loading of ultrafine Ir/Ru-based nanoparticles is thoroughly studied. Due to the successful loading, the mass activity of the tungsten oxide-supported Ir/Ru-based catalyst shows significant improvements under rotating disk electrode (RDE) conditions compared with commercially available Ir/Ru-blacks. Furthermore, non-destructive depth profiling by synchrotron-based X-ray photoelectron spectroscopy (XPS) has revealed the strong catalyst-support interaction which suppressed the oxidation of the supported Ir/Ru-based catalysts, leading to much enhanced durability under accelerated durability testing conditions. To verify its performance under practical PEM electrolysis conditions, the tungsten oxide-supported OER catalyst is directly coated onto a polymer electrolyte membrane, i.e., forming a catalyst coated membrane (CCM), and tested under single cell testing conditions without pressure differential. The voltage dependent chemical state of the supported catalyst is also probed in-situ by synchrotron-based XPS where a potential dependent electron transfer between the catalyst and tungsten-oxide support is discovered. Our discovery is anticipated to aid the development of cost effective PEM electrolysis anodes.    

    

* Ionomer-Dependent Oxygen Evolution Reaction in a Half-Cell and a Liquid Electrolyzer  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638465
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02391892mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638465"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638465"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638465"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638465 (Open access: False)
    
[[https://openalex.org/A5015545381][Joy Marie Mora]], [[https://openalex.org/A5086997032][Guangfu Li]], [[https://openalex.org/A5048183453][Po‐Ya Abel Chuang]], ECS Meeting Abstracts. MA2023-02(39)] 2023. https://doi.org/10.1149/ma2023-02391892mtgabs 
     
Electrocatalytic oxygen evolution reaction (OER) is an important area of research due to its significance in water electrolysis, which contributes to the clean-energy storage and conversion techniques. OER exhibits irreversible and sluggish kinetics, which necessitates a high overpotential to achieve the desired reaction rate. In an alkaline medium, non-precious metals (such as Ni, Fe, Co) or metal-free materials (such as 3d-transition metal oxides and heteroatom-doped carbons) can replace expensive iridium and ruthenium oxides, which is otherwise required in an acidic medium to facilitate the reaction. However, developing new catalysts for alkaline OER is limited by the scaling relations among adsorption energetics of key intermediates (i.e., OOH*, OH*, and O*). The electrochemical reaction kinetics depends critically on the nature of the interface between catalyst and the electrolyte where an electrical double layer (EDL) forms during OER. The current understanding of the EDL structure involves the interfacial interactions between adsorbates and catalyst layer (CL) which can be modified to improve the reaction efficiency. Ionomers are essential components of the CL and are vital in uniformly dispersing catalyst particles in ink solution. The ionomers also act as binder for the catalyst particles in the CL, helping to improve the electrode’s durability and stability over time. In addition, despite the fact that ionomers affect the properties of EDL, the impact of ionomer on the reaction pathway is often overlooked in electrocatalytic research. In this study, we investigate the role of ionomer in the catalyst layer by comparing different polymer dispersions, including PTFE, Nafion, and commercial As-4. The results indicate that the Nafion-contained CL performs better than other polymer CLs in TF-RDE/RRDE, as it facilitates direct O*-O* coupling. In contrast, anionic ionomer demonstrates superior long-term stability in alkaline liquid electrolyzers, despite oxidization degradation.    

    

* Insights into the Structure Sensitivity of Fe-Based Materials for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663581
:TOPICS: Electrocatalysis for Energy Conversion, Solar Water Splitting Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542547mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663581"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663581"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663581"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663581 (Open access: False)
    
[[https://openalex.org/A5075460624][Ricardo Alberto Hincapié Isaza]], [[https://openalex.org/A5026566541][Viktor Čolić]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542547mtgabs 
     
The conversion of renewable energy into storable fuels is fundamental to the meeting of the net-zero CO 2 emissions objective by 2050. However, the sluggish kinetics of the oxygen evolution reaction (OER) and the poor stability of electrocatalysts at industrial-level currents remain a problem for electrolyzers 1 . Using platinum group metal-free electrocatalysts in anion exchange membrane electrolyzers is an appealing strategy to overcome some of the problems associated with PEM electrolyzers. Fe-based materials offer the possibility for the development of active, stable, and cost-effective electrocatalysts for the OER in alkaline media. In this work, we explore the influence of structure, composition, or crystalline phase on different Fe-based electrodes for the OER. Different fabrication procedures such as additive manufacturing 2 , flame spray synthesis, or pulse laser ablation 3 allow us to have a wide range of Fe-based materials with a well-defined structure/composition/phase. The materials have been extensively characterized by physicochemical methods (XPS, Raman, XRD, ICP) and their electrocatalytic activity evaluates following careful procedures in order to obtain reliable results. The results show that the activity of Fe-rich electrodes is poor. However, if Fe is alloyed with other materials or its surface structure or crystallinity degree is modified, it results in a more active material. This information could guide the synthesis of more active and stable water-splitting materials. References S. Cherevko, S. Geiger, O. Kasian, N. Kulyk, J.-P. Grote, A. Savan, B. R. Shrestha, S. Merzlikin, B. Breitbach, A. Ludwig, and K. J. J. Mayrhofer, Catalysis Today, 262 170-180 (2016). J. Wegner, R. Martínez-Hincapié, V. Čolić, and S. Kleszczynski, Advanced Materials Interfaces, n/a (n/a), 2202499 (2023). J. Johny, Y. Li, M. Kamp, O. Prymak, S.-X. Liang, T. Krekeler, M. Ritter, L. Kienle, C. Rehbock, S. Barcikowski, and S. Reichenberger, Nano Research, 15 (6), 4807-4819 (2022).    

    

* Iridium Single Atom Catalysts for Oxygen Evolution Reaction in Acidic Medium  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638495
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422087mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638495"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638495 (Open access: False)
    
[[https://openalex.org/A5093888179][Jean Rouger]], [[https://openalex.org/A5035038630][Sara Cavaliere]], [[https://openalex.org/A5015338172][Frédéric Jaouen]], [[https://openalex.org/A5046537142][Deborah J. Jones]], [[https://openalex.org/A5080444382][Fabien Dufour]], [[https://openalex.org/A5042428372][Maureen Georges]], [[https://openalex.org/A5004000315][Julien Thuilliez]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422087mtgabs 
     
In order to reduce CO 2 emissions and produce clean hydrogen one solution is to use sustainable energies (wind, solar or hydraulic) coupled with water electrolyser to produce H 2 and store it before use it in fuel cell. The electrolyzer based on proton exchange membranes (PEM) is a promising technology because it can reach high current density (2 A.cm -2 ) [1] and can be easily coupled with intermittent energy sources [2]. However, the acidic conditions and working temperatures (80 °C) require the use of noble metals. On the anode side the oxidative condition prevents the use of carbon supported catalyst and the best catalyst for the oxygen evolution reaction (OER) so far is IrO x . The use of Ir single atom catalyst (SAC) supported on conducting oxide is a promising way to reduce the quantity of the scarce and expensive noble metal, increasing the electroactive surface and durability. SACs present an excellent dispersion and activity [3] and some conducting oxides are very promising regarding electrical conductivity and stability under oxidative conditions [4]. There are different approaches to prepare Ir SAC (wet impregnation, co-precipitation, photoelectrochemical reduction...) [3], whose success mainly depends on the nature of the Ir precursor, its interaction with the support and the thermal treatment temperature/duration. Some research groups have prepared and characterized Ir SAC on indium-tin oxide [5] but the activity and stability still need to be improved. The objective of this communication is to present the synthesis and the characterization of Ir SAC on different conducting oxide supports. Ir precursor was synthesized and deposed on various supports. The physical characterization entails XRD, TEM, MEB, EDX to assess the morphology and composition of the catalyst. Spectroscopic analysis like XPS and XAS brings information on the chemical environment of Ir sites, while electrochemical measurements give information on the OER activity and stability of the catalyst. References [1] C.D. Ferreira da Silva et al. , ACS Catal. , 2021 , 11, 4107-4116 [2] O. Schmidt et al. , Int. J. Hydrog. Energy , 2017 , 42, 30471-30492 [3] J. Liu, ACS Catal. , 2017 , 7, 34-59 [4] Moriau et al. , ChemCatChem , 2022 , 14, e202200586 [5] D. Lebedev et al., ACS Cent. Sci. 2020 , 6, 1189-1198 [6] Q. Wang et al. , ACS Catal., 2020 , 142, 7425-7433    

    

* Theoretical Study on Inhibition of Oxygen Evolution in Layered Cathode Materials during Charging  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391662769
:TOPICS: Lithium-ion Battery Management in Electric Vehicles, Lithium-ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-025828mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391662769"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391662769"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391662769"))][Get cited by]]

OpenAlex: https://openalex.org/W4391662769 (Open access: False)
    
[[https://openalex.org/A5079893811][Kuan-Yu Lin]], [[https://openalex.org/A5009770522][Shaohui Xu]], [[https://openalex.org/A5088941900][Santhanamoorthi Nachimuthu]], [[https://openalex.org/A5037150692][Jyh‐Chiang Jiang]], ECS Meeting Abstracts. MA2023-02(5)] 2023. https://doi.org/10.1149/ma2023-025828mtgabs 
     
In recent years, Ni, Mn-based layered cathode materials (Li 1.2 Ni 0.2 Mn 0.6 O 2 , LiNi 1-x-y Co x Mn y O 2 ) have shown great promise for high energy density LIBs. Research has shown that nickel-rich materials are ideal candidates for high-capacity batteries. The valence state from Ni 2+ to Ni 4+ allows more Li + to transfer between the cathode and anode, providing excellent electrochemical performance. However, the oxidation of oxygen atoms triggers irreversible structural rearrangements on the surface, while Ni 3+ introduces Jahn-Teller distortion. At high voltages, the stability of layered cathode materials is severely hampered. We present theoretical work on Li 1.2 Ni 0.2 Mn 0.6 O 2 and LiNi 1-x-y Co x Mn y O 2 using density functional theory, considering cation- and anion-doped surface treatments. We found that doped layered cathode materials successfully suppressed O 2 formation at highly delithiated levels. Through DFT calculations, we understand the mechanism of oxygen evolution from layered cathode materials during the charging process and discover how to suppress oxygen evolution strategies.    

    

* The Interplay of Anodic Passivation and Oxygen Evolution of Medium Entropy Alloys in Artificial Seawater  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391639471
:TOPICS: Atom Probe Tomography Research, High-Entropy Alloys: Novel Designs and Properties, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02111073mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391639471"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391639471"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391639471"))][Get cited by]]

OpenAlex: https://openalex.org/W4391639471 (Open access: False)
    
[[https://openalex.org/A5076601076][Annica Wetzel]], [[https://openalex.org/A5072476528][Özlem Özcan]], [[https://openalex.org/A5044822731][Julia Witt]], [[https://openalex.org/A5093888344][Daniel Morell]], ECS Meeting Abstracts. MA2023-02(11)] 2023. https://doi.org/10.1149/ma2023-02111073mtgabs 
     
Medium entropy alloys (MEA) have gained increased interest in both academic and industrial sectors due to their favorable mechanical and anti-corrosion properties, rendering them ideal candidates for engineering and potentially catalytic applications. Although previous studies have shown high current densities at high anodic potentials for MEAs, a lack of understanding on the underlying transpassive dissolution and local corrosion behavior remains. This project aimed to investigate and compare the passivation behavior of MEAs CrCoNi and FeCrNi (equimolar) under high anodic potentials, focusing on the mechanisms of transpassive dissolution and the oxygen evolution reaction in artificial seawater. The study utilized various techniques such as scanning electrochemical microscopy (SECM) to instantaneously detect evolving metal species and oxygen, and inductively coupled plasma mass spectrocmetry (ICP-MS) to quantify the dissolved metal species. For these investigations, the alloys were subjected to precisely controlled corrosion loads employing potentiodynamic, potentiostatic, and chronoamperometric methods during the SECM experiments and subsequent ICP-MS analysis. Macroscopic corrosion and passive film properties were studied via potentiodynamic polarization, electrochemical impedance spectroscopy (EIS), and X-Ray Photoelectron Spectroscopy (XPS). Finally, in-situ atomic force microscopy (AFM) and scanning Kelvin probe force microscopy (SKPFM) were used to analyze the corrosion morphology and surface potentials before, during, and after passivity breakdown. Overall, this study aimed to provide a comprehensive understanding of the interplay between passivation, anodic dissolution and oxygen evolution of the MEAs in artificial seawater.    

    

* Supported-Ir Catalysts: The Impact of the Supports' Chemical Composition on the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663482
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422097mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663482"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663482"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663482"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663482 (Open access: False)
    
[[https://openalex.org/A5089464452][Lucinda Blanco Redondo]], [[https://openalex.org/A5032887364][Yevheniia Lobko]], [[https://openalex.org/A5006021426][Miquel Gamón Rodríguez]], [[https://openalex.org/A5047472204][Thu Ngan Dinhová]], [[https://openalex.org/A5077307847][Tomáš Hrbek]], [[https://openalex.org/A5073666601][Serhiy Cherevko]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422097mtgabs 
     
In water electrolyzer cells, the anode electrode is one of the most important components, where the oxygen evolution reaction (OER) takes place. In this process, the water molecules split into oxygen ions, protons, and electrons, and the oxygen gas is produced on the anode surface [1]. The most suitable materials that catalyze OER are ruthenium, iridium, and their oxides, but their cost and scarcity require reduction and enhancement of their utilization [2]. One morphological strategy consists of the dispersion of the active nanoparticles in supportive nanoparticles made of less expensive materials to increase their mass activity. In addition, due to the high potential reached during operating conditions for water splitting, supportive materials have to possess a high corrosion resistance. Titanium oxides are good candidates because of their high thermal and chemical stability, low cost, and commercial availability [3]. But their poor electric conductivity (∼10 −6 S cm −1 ) makes the design of an active and stable catalyst a complex task. In this work, Ir nanoparticles have been synthesized on the surface of several Ti-based nanoparticles and a complete analysis of their physicochemical properties have been carried out ( Fig. 1a-b ). In addition, electrochemical behaviour has been tested ex-situ in a half cell by the rotating disk electrode technique and after, the catalysts have been deposited in a polymer membrane for testing in-situ in a single cell proton exchange membrane water electrolyzer. The results show a successful performance of the supported Ir/TiO 2 nanoparticles comparable to the pure Ir black nanoparticles but with an active metal loading five times lower. Differently, even though TiC showed excellent electrical conductivity during the ex-situ characterization, Ir/TiC nanoparticles had a poor activity after just one day of performance in the WE due to the complete oxidation of the TiC into TiO 2 ( Fig. 1c-d ). Finally, Ir/TiB 2 showed a balanced result in terms of activity and stability, showing promising properties as a catalyst for PEM-WE. Sadhasivam T., Ho-Young J. Chapter 3 - Nanostructured bifunctional electrocatalyst support materials for unitized regenerative fuel cells// Nanostructured, Functional, and Flexible Materials for Energy Conversion and Storage Systems- 2020. - 69-103. Antolini E. Iridium as Catalyst and Cocatalyst for Oxygen Evolution /Reduction in Acidic Polymer Electrolyte Membrane Electrolyzers and Fuel Cells // ACS Catal. - 2014.- 4, N 5.- P. 1426-1440. Van Pham C., Bühler M. IrO2 coated TiO2 core-shell microparticles advance performance of low loading proton exchange membrane water electrolyzers// Applied Catalysis B: Environmental-2020.- P 269.- P. 118762. Figure 1. TEM image of Ir/TIO 2 (a), EDX mapping of Ir/TiO 2 (b), linear sweep voltammetry of catalysts (c), the current density at given potential 1.80 V (d). Figure 1    

    

* Self-Terminated Surface Reconstruction of Lanthanum Nickelates Promotes Alkaline Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663278
:TOPICS: Solid Oxide Fuel Cells, Catalytic Nanomaterials, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542536mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663278"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663278"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663278"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663278 (Open access: False)
    
[[https://openalex.org/A5063384458][Yi‐Hsuan Wu]], [[https://openalex.org/A5093893767][Marcel Janák]], [[https://openalex.org/A5005303303][Paula M. Abdala]], [[https://openalex.org/A5079220919][Denis A. Kuznetsov]], [[https://openalex.org/A5024347042][Christoph R. Müller]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542536mtgabs 
     
Oxygen evolution reaction (OER) itself is expected to have a strong impact on the state of the surface of the electrocatalyst, yet the actual structure of the surface under operating conditions is rarely considered while formulating structure-activity correlations in electrocatalysis. In this study, changes in the surface structure of Ruddlesden-Popper-type lanthanum nickelate, La 2 NiO 4+δ , and the perovskite LaNiO 3 are probed and contrasted using a series of complementary surface sensitive techniques, including XPS, HRTEM and O K-edge XAS. We found noticeable surface changes to occur on La 2 NiO 4+δ after exposure its exposure to the alkaline electrolyte that is accompanied by the emergence of a strong Ni n+/n+1 redox feature and the coincides with a 45-fold enhancement of the OER activity (at η = 370 mV) in 0.1 M KOH, as compared to the pristine La 2 NiO 4+δ phase. We observe that the in situ formation of an amorphous nickel (oxy)hydroxide layer on the surface increases the electrochemically-active surface area of La 2 NiO 4+δ and imparts a high stability of the catalyst under OER conditions (the formation of the amorphous layer self-terminates at ca. 3 nm). In addition, the transition from octahedral Ni sites (O h ) to square-planar Ni sites (D 4h ) in the reconstructed surface was observed using O K-edge X-ray absorption spectroscopy. Further, we found no evidence for any surface transformations in the perovskite-based catalyst LaNiO 3 that also did not demonstrate any improvement in its activity over cycling. This work highlights the importance of a detailed surface analysis of the catalysts under operation to build robust structure-activity correlations for the metal oxides under electrochemical reaction conditions. Figure 1    

    

* Nanostructured Fe-Doped Nickel Sulfide on Ni Foam As Electrocatalyst for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638605
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542621mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638605"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638605"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638605"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638605 (Open access: False)
    
[[https://openalex.org/A5012911188][Jianguo Zhu]], [[https://openalex.org/A5052888056][Paolo P. Pescarmona]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542621mtgabs 
     
In recent years, with the increasing demand for clean and renewable energy, growing research efforts have been dedicated to the generation of hydrogen through water electrolysis [1,2] . To industrialize hydrogen production, it is important to find low-cost and high-activity electrocatalysts for hydrogen evolution reaction (HER) and, especially, oxygen evolution reaction (OER) [3] . OER is more challenging because it involves a four-electron transfer process, while HER is a two-electron transfer process. In this study, Ni 3 S 2 nanorods were synthesized on Ni foam (NiS/Ni foam, Fig. 1a) by a new one-step solvothermal reaction, with S powder as the sulfur source and Ni foam as the nickel source. Experimental results indicated that the NiS/Ni foam electrocatalyst had an overpotential of 276 mV at 10 mA/cm 2 for OER in 1 M KOH electrolyte. To boost the electrocatalytic activity of Ni 3 S 2 , we developed an effective method of doping with Fe via hydrothermal reaction. The obtained nanostructured Fe-doped Ni 3 S 2 on Ni foam (Fe-NiS/Ni foam, see Fig. 1b) achieved OER at an extremely low overpotential of 218 mV at 10 mA/cm 2 . Remarkably, Fe-NiS/Ni foam exhibited high stability at an industrially-relevant high current density (500 mA/cm 2 for 24h). Currently, we are studying its phase transfer process with in situ XPS. REFERENCES Jiao, S., et al., Energy & Environmental Science, 2021. 14(4): p. 1722-1770. Boppella, R., et al., Coordination Chemistry Reviews, 2021. 427. Du, J., F. Li, and L. Sun, Chem Soc Rev, 2021. 50(4): p. 2663-2695. Figure 1    

    

* Lattice Oxygen Exchange in Transition Metal Oxyhydroxides and Metal Hydroxide Organic Frameworks Elucidated for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663343
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422146mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663343"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663343 (Open access: False)
    
[[https://openalex.org/A5019272572][Mikaela Gorlin]], [[https://openalex.org/A5031010219][Nicole A. Saguì]], [[https://openalex.org/A5024844208][Daniel J. Zheng]], [[https://openalex.org/A5062113791][Kaylee Lynn McCormack]], [[https://openalex.org/A5070557069][Z. Khosravizadeh]], [[https://openalex.org/A5007449670][Junghwa Kim]], [[https://openalex.org/A5008841733][Hongbin Xu]], [[https://openalex.org/A5042383151][Jiayu Peng]], [[https://openalex.org/A5001680940][Per Malmberg]], [[https://openalex.org/A5016487357][Yuriy Román‐Leshkov]], [[https://openalex.org/A5024361437][Mario Valvo]], [[https://openalex.org/A5072645578][Yang Shao‐Horn]], [[https://openalex.org/A5056174579][Tomas Edvinsson]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422146mtgabs 
     
To achieve the goal of climate neutrality by 2050, it is essential to increase the use of renewable fuels and carbon-neutral energy. 1 The anodic oxygen evolution reaction (OER) is a key reaction not only in electrocatalytic production of many renewable fuels, 2 but also for next generation of charge storage devices such as metal-air batteries. 3 However, the slow kinetics of the OER process result in high energy losses and costs. 4 Therefore, the development of more efficient electrocatalysts is critical for making renewable energy via electrocatalysis a viable option in emerging energy systems. Transition metal (TM) oxides are a promising alternative to expensive noble metals due to their high catalytic OER activity under alkaline conditions and wider earth-abundance. Despite extensive research, establishing structure-activity correlations and understanding mechanistic processes is challenging, given the intricate interplay between external and intrinsic parameters. In this study, we investigate the role of lattice oxygens in electrodeposited Ni-Fe, Co-Fe, and Mn-Fe oxyhydroxide (M(OH) x O y , M = TM) electrocatalysts using surface-enhanced Raman spectroscopy (SERS) in conjunction with secondary ion mass spectroscopy (SIMS). By taking advantage of the Raman shift that results from 16 O/ 18 O isotope exchange, 5–7 we can track the participation of lattice oxygens in the electrocatalytic cycle. Our investigation reveals that, during OER, all the electrocatalysts display minimal exchange of lattice oxygens with the electrolyte (less than 5%). However, many of these electrocatalysts show partial or complete exchange when exposed to non-catalytic potential when in their more reduced states (see Figure 1). Apart from fully inorganic catalysts, we also present results from Ni-derived metal-hydroxide-organic frameworks (MHOFs), which are analogous to M(OH) x O y catalysts but with organic linkers separating the layers. 8 Our findings indicate that MHOFs with linkers that have a high π-π stacking energy (and a high structural stability) 8 undergo near complete 16 O/ 18 O exchange during OER, while MHOFs employing linkers with a low π-π stacking energy (and thus a low stability) show minor or no lattice exchange during OER. Our study suggests that participation oflattice oxygens is closely linked to the oxidation state of the transition metals rather than to the catalytic process. The work provides a detailed picture of the exchange mechanism and elucidates alternative processes involved in lattice oxygen participation and discusses their relation to the mechanisms of the OER process. References IEA (2023), Energy Technology Perspectives 2023, IEA, Paris https://www.iea.org/reports/energy-technology-perspectives-2023, License: CC BY 4.0 . Wei, S. Z. et al. Combining theory and experiment in electrocatalysis: Insights into materials design. Science (80-. ). 355 , eaad4998 (2017). Li, Y. & Lu, J. Metal–Air Batteries: Will They Be the Future Electrochemical Energy Storage Device of Choice? ACS Energy Lett. 2 , 1370–1377 (2017). Song, F. et al. Transition Metal Oxides as Electrocatalysts for the Oxygen Evolution Reaction in Alkaline Solutions: An Application-Inspired Renaissance. J. Am. Chem. Soc. 140 , 7748–7759 (2018). Lee, S., Banjac, K., Lingenfelder, M. & Hu, X. Oxygen Isotope Labeling Experiments Reveal Different Reaction Sites for the Oxygen Evolution Reaction on Nickel and Nickel Iron Oxides. Angew. Chemie Int. Ed. 58 , 10295–10299 (2019). Moysiadou, A., Lee, S., Hsu, C.-S., Chen, H. M. & Hu, X. Mechanism of Oxygen Evolution Catalyzed by Cobalt Oxyhydroxide: Cobalt Superoxide Species as a Key Intermediate and Dioxygen Release as a Rate-Determining Step. J. Am. Chem. Soc. 142 , 11901–11914 (2020). Diaz-Morales, O., Ferrus-Suspedra, D. & Koper, M. T. M. The importance of nickel oxyhydroxide deprotonation on its activity towards electrochemical water oxidation. Chem. Sci. 7 , 2639–2645 (2016). Yuan, S. et al. Tunable metal hydroxide–organic frameworks for catalysing oxygen evolution. Nat. Mater. 21 , 673–680 (2022). Figure 1    

    

* Hollow TiO2 Supports for Enhanced Acidic Oxygen Evolution Activity  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663439
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02582810mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663439"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663439"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663439"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663439 (Open access: False)
    
[[https://openalex.org/A5027844987][Laurie A. King]], [[https://openalex.org/A5093893784][Debora Belami]], [[https://openalex.org/A5068678989][Umesh Sai Jonnalagadda]], [[https://openalex.org/A5024639628][Wenhao Fan]], [[https://openalex.org/A5091646124][James J. Kwan]], [[https://openalex.org/A5087146859][Yagya N. Regmi]], ECS Meeting Abstracts. MA2023-02(58)] 2023. https://doi.org/10.1149/ma2023-02582810mtgabs 
     
The usage of scarce and expensive iridium as a catalyst for the acidic oxygen evolution reaction (OER) represents a significant barrier to up-scaling the deployment of proton exchange membrane water electrolysers (PEM-WEs). Accordingly, strategies such as nanostructuring catalysts to increase the electrochemical surface area (e.g. nanoparticles, single-atom catalysts, nanoclusters) as well as investigating mixed metal alloys and oxides (e.g. perovskites, pyrochlores) have been developed with promising half-cell performances. One further approach that has recently gained attention is the deployment of catalyst-supports whereby a high surface area support is used to scaffold the dispersed iridium catalyst. 1 Analogous to the selection of a catalyst, the catalyst support must withstand the highly corrosive and oxidising conditions of a PEM-WE anode. Thus, metal oxides such as titanium dioxide are commonly deployed as catalyst-supports for acidic OER. The catalyst-support moiety must also be sufficiently conductive when integrated into the PEM-WE catalyst layers. Otherwise, the cell voltages required to generate sufficient activity will render the device impractical. Accordingly, strategies such as doping, or the addition of conductive layers between the catalyst and support have been investigated. 2 In this study we investigate a unique support morphology that affords promising OER activity and stability in acidic electrolyte with high iridium mass activities. Specifically, we deploy a hollow TiO 2 catalyst support, 3 coated with a Au/Pd interlayer to provide electrical conductivity. The OER activity and stability is initially screened in a rotating disk electrode (RDE) configuration as a function of thermal treatments (reducing vs oxidising) as well as with at various Au/Pd (1 – 5 wt%) and Ir loadings (35 – 50 wt%). Our highest performing catalyst have a mass activity of around 480 A/g Ir at 1.60 V vs RHE. The catalysts are subsequently investigated in a membrane electrode assembly (MEA) and subject to 10k accelerated stress test stability measurements. To understand the role of the support morphology, Au/Pd interlayer and iridium loadings on electrochemical performance, we also characterise the synthesised catalysts by (scanning) transmission electron microscopy (STEM/TEM), X-ray diffraction (XRD), X-ray photoelectron microscopy (XPS) and electrical conductivity measurements. Collectively, we report the critical role of the Au/Pd interlayer to enable such high electrochemical performance. We also show that the hollow structure of the TiO 2 support may be enhancing mass transport in the catalyst layers. References 1 A. S. Pushkarev, I. V Pushkareva and D. G. Bessarabov, Energy & Fuels , 2022, 36 , 6631–6625. 2 Y. N. Regmi, E. Tzanetopoulos, G. Zeng, X. Peng, D. I. Kushner, T. A. Kistler, L. A. King and N. Danilovic, ACS Catal. , 2020, 10 , 13125–13135. 3 U. S. Jonnalagadda, X. Su and J. J. Kwan, Ultrason. Sonochem. , 2021, 73 , 105530.    

    

* The Active Interface of Iron-Decorated Cobalt (Oxy)Hydroxide for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391637763
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02653141mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391637763"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391637763"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391637763"))][Get cited by]]

OpenAlex: https://openalex.org/W4391637763 (Open access: False)
    
[[https://openalex.org/A5045546838][Qiyang Jiang]], [[https://openalex.org/A5081133273][Fang Song]], ECS Meeting Abstracts. MA2023-02(65)] 2023. https://doi.org/10.1149/ma2023-02653141mtgabs 
     
Iron can significantly enhance the activity of Co (oxy)hydroxide. However, the nature of active sites is currently under debate for Fe-Co (oxy)hydroxide. Here, we use well-define crystalline cobalt hydroxide nanosheets and nanorods as model catalysts to investigate the role of Fe on different crystal planes. The electrochemical reactivity and morphology-dependent analysis suggest that the lateral facets of Co(OH) 2 are active sites and the enhancement effect of iron incorporation only occurs on lateral facets rather than basal facets. Furthermore, by introducing tetramethylammonium cation (TMA+) as a chemical probe in KOH solution, we demonstrate the Fe species can interact strongly with the “active species” on the lateral facets and promote the improvement of OER activity. This work identifies the active site of cobalt hydroxides in the presence and absence of iron and elucidates the interaction of Fe species with “active oxygen” species on the lateral facets of cobalt hydroxide, which has a fundamental implication on the design of efficient OER catalysts.    

    

* Digital Composition Control of Cobalt Nickel Oxides by ALD for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391662767
:TOPICS: Solid Oxide Fuel Cells, Catalytic Nanomaterials, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02291504mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391662767"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391662767"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391662767"))][Get cited by]]

OpenAlex: https://openalex.org/W4391662767 (Open access: False)
    
[[https://openalex.org/A5068731097][Renee T. M. van Limpt]], [[https://openalex.org/A5040363865][Marek Lavorenti]], [[https://openalex.org/A5047229199][Mengmeng Lao]], [[https://openalex.org/A5048719407][Marcel A. Verheijen]], [[https://openalex.org/A5052330817][Mihalis N. Tsampas]], [[https://openalex.org/A5082522882][M. Creatore]], ECS Meeting Abstracts. MA2023-02(29)] 2023. https://doi.org/10.1149/ma2023-02291504mtgabs 
     
Anion exchange membrane water electrolysis is a potentially low-cost and sustainable technology for renewable-energy driven hydrogen production. Realisation of its full potential relies on the development of cost-effective, earth-abundant OER electrocatalysts alternatives to the state-of-the art noble metal oxides 1 . Ternary transition metal oxides, such as cobalt nickel oxides, are promising candidates due to their excellent alkali resistance in combination with remarkable catalytic activities. The latter relate to their tuneable oxidation states and variation in coordination of their metal centres. These correlations can be properly investigated when precise control over the layer chemical composition is attained. Atomic layer deposition (ALD) is widely acknowledged to deliver control over film uniformity, thickness and conformality, as well as film chemical composition due to the self-limiting nature of its surface reactions. In this study, an ALD supercycle process based on cobalt cyclopentadienyl (CoCp 2 ) and nickel methylcyclopentadienyl (Ni( Me Cp) 2 ) precursors and an oxygen plasma co-reactant has been developed 2 to investigate the influence of chemical composition and crystallographic properties of cobalt nickel oxide thin films on their electrocatalytic OER performance. Deposition of ~20 nm binary nickel oxide and cobalt oxide results in the growth of polycrystalline films of the rock-salt and spinel phase, respectively. Ternary cobalt nickel oxide films with various ratios can be deposited uniformly, as indicated by energy dispersive x-ray spectroscopy mapping. The mixed oxides display a transition from the +2 oxidation state-based pure rock-salt phase (<25 at.% Co) to the spinel phase consisting of mixed +2/+3 oxidation states (>75% at.% Co) upon increasing Co at.% as verified by electron diffraction (figure a) and x-ray photoelectron spectroscopy (XPS). XPS furthermore reveals a linear increase in the Ni 3+ -to-Ni 2+ ratio with increasing Co at.%, which indicates that an inverse spinel structure is formed. The formation of a Ni 3+ -rich inverse spinel cobalt nickel oxide between 55 and 75 at.% Co facilitates the formation of a semi-metallic state (10 2 S/cm) as opposed to the poorly conductive binary oxides (10 -3 S/cm and 10 -2 S/cm for NiO and Co 3 O 4 , respectively). Cyclic voltammetry (CV) measurements in 1M KOH, reveal chemical composition dependent activation behaviour (figure b). Continuous activation behaviour is observed for rock-salt phase films, whilst increment of the Co at.% results in reduced film activation until virtually no activation of the spinel phase films is observed. The activation of the nickel-rich film is accompanied by irreversible redox changes from the +2 to +3 oxidation state as indicated by the integrated non-catalytic wave. Post CV XPS analysis confirms the transition from Co 2+ and Ni 2+ oxidation states to Co 3+ and Ni 3+ . The formation of an (oxy)hydroxide state is observed for the rock-salt dominated films, whilst oxidation states characteristic of a spinel- like oxide structure are observed for the cobalt-rich films. No changes in the transition metal ratios are observed after activation. Scanning electron microscopy images furthermore reveal that the transformation of the Ni-rich films is accompanied by surface restructuring. These results indicate that initial composition can significantly influence the electrocatalytic performance of ternary oxides and therefore highlight the importance of techniques such as atomic layer deposition to study their complex behaviour. 1 Xu et al., Energy Chem., 4 (2022) 100087 2 van Limpt et al., J. Vac. Sci. Technol. A, 41 (2023) 032407 This work has been carried out within the SCALE project (NWA.1237.18.001) funded jointly by the Netherlands Organization for Scientific Research. Authors would like to thank the co-founders of the project ISPT, Syngaschem, VecoPrecision and Vsparticle and international partners Toyota Motor Europe and FORTH institute. Figure: (a) ALD deposited cobalt nickel oxide film show a transition from the +2 oxidation state-based rock-salt phase (NiO) to the spinel structure consisting of mixed +2/+3 oxidation states (Co 3 O 4 ) upon tuning the chemical composition as identified by electron diffraction. (b) This significantly affects the OER-electrocatalytic performance and activation of the films as represented by the current density at 1.8V vs RHE over 500 CV cycles in 1M KOH. Data labels indicate cobalt concentration as at.% Co/(at.% Co+ at.% Ni) . Figure 1    

    

* Every Step Counts: Importance of Final ALD Sequences for Oxygen Evolution Reaction Catalysts  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391640089
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02291503mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391640089"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391640089"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391640089"))][Get cited by]]

OpenAlex: https://openalex.org/W4391640089 (Open access: False)
    
[[https://openalex.org/A5010858255][Ruben Blomme]], [[https://openalex.org/A5077670292][R. Ramesh]], [[https://openalex.org/A5065960121][Lowie Henderick]], [[https://openalex.org/A5039168166][Christophe Detavernier]], [[https://openalex.org/A5081161746][Jolien Dendooven]], ECS Meeting Abstracts. MA2023-02(29)] 2023. https://doi.org/10.1149/ma2023-02291503mtgabs 
     
In achieving the global dream of a sustainable future, the development of new and alternative methods to generate electricity are of high importance. Current renewable energy sources are mainly dependent on sun and wind, and are thus very unpredictable. To obtain an overall reliable energy supply, we need to be able to store clean energy for extended periods of time to compensate for unfavorable weather conditions or sudden surges in energy demand. One way to store energy is by generating H 2 -gas, which has a set of interesting advantages as an energy carrier molecule. It has a very high energy density, is multifunctional as feedstock or energy carrier and it is not a greenhouse gas in itself. The production efficiency of green H 2 , however, still needs to be optimized before it can be adapted on a global scale. Electrochemical water splitting is mainly hampered by the sluggish kinetics of the oxygen evolution half-reaction (OER) of the process. This involves a transfer of four electrons, each with its own intermediary product(s) requiring catalysis, resulting in a significant overpotential[1]. Atomic layer deposition (ALD) could be an interesting technique in the research, development and possibly production of such OER catalytic materials. This technique is suited to deposit thin films in a controlled layer-by-layer way with dimension control up to the Angström level. In this development, transition metals could be interesting catalyst candidates due to their availability and pricing over tradition OER catalysts based on noble metals [2]. Both oxides and phosphate variants have been explored; the latter occasionally outperforming the former[3][4]. Nickel has shown to be one of the more OER-active transition metals, and doping or combining it with iron seems to further increase its performance [5]. Inspired by these results, ALD was used in this work to deposit and finetune the properties of a Ni-Fe ternary phosphate for its use as an OER-catalyst material. This material was deposited by alternating ALD cycles of Ni- and Fe-phosphate (denoted here as NiPO and FePO) based on previous works of Rongé et al.[6] and Henderick et al.[7]. Ni-Fe phosphates with varying composition and thickness were deposited on a solid nickel disc and tested in a rotating-disc electrode (RDE) set-up to quantify their electrochemical performance. Applying a coating with a selected composition of 4 NiPO to 1 FePO cycles improves the performance over a bare Ni-PVD substrate (Fig 1). A current density of 91 mA/cm 2 at 0.685 V vs Hg/HgO is obtained for this material which is 75% higher than the uncoated nickel disk (51 mA/cm 2 ) which indicates that the material has catalytic properties for the OER increasing the production of H 2 at an identical overpotential. An additional observation was that the pulsing order of the two sub-processes within an ALD super-cycle has an important impact on the resulting layer’s performance. If the FePO sub-cycle is pulsed last, the current density increases further to approx. 150 mA/cm 2 for a total increase of 200% compared to the uncoated performance. The results of this explorative work in the use of ALD for the development of OER catalytic materials indicate that it is a promising technique due to the precise control that can be exerted over both the thickness and composition of the material. Specifically the option to exert high control over the surface of the catalyst can be a big asset in researching catalytic materials. References [1] X. Xie, Adv. Funct. Mater., 32 , 2110036 (2022) [2] C.C.L. McRory,J. Am. Chem. Soc., 137 , 13, 4347–4357 (2015) [3] J. Rongé, Nanoscale Adv., 1 , 4166-4172 (2019) [4] R. Zhang, ACS Catal., 11 , 5, 2774–2785 (2021) [5] F. Diongini, Adv. Energy Mater., 6 , 1600621(2016) [6] T. Dobbelaere, Chem. Mater., 28 , 10, 3435-3445(2016) [7] L. Henderick, Dalton Trans., 51 , 2059(2022) Figure 1    

    

* Tracking Oxygen Evolution Activities of Perovskite Oxide Catalysts By 3D Electrochemical Impedance Spectroscopy  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638074
:TOPICS: Fuel Cell Membrane Technology, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542629mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638074"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638074"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638074"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638074 (Open access: False)
    
[[https://openalex.org/A5077212635][Yuta Inoue]], [[https://openalex.org/A5008278763][Yuto Miyahara]], [[https://openalex.org/A5016383117][Kohei Miyazaki]], [[https://openalex.org/A5064765980][Changhee Lee]], [[https://openalex.org/A5014192679][Takeshi Abe]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542629mtgabs 
     
Introduction Promoting the oxygen evolution reaction (OER) is important for more efficient electrochemical water splitting because its sluggish reaction kinetics degenerate the overall efficiency. Perovskite oxides (ABO 3 ) are known as promising electrocatalysts for the OER, which have a flexibility of composition and structure. Among these electrocatalysts, Ba 0.5 Sr 0.5 Co 0.8 Fe 0.2 O 3– δ (BSCF) exhibits good OER activities in an alkaline solution 1 . One of its specific properties is the change of the surface structure and composition during the OER in alkaline solutions, leading the improvement of the OER activity 2 . In general, the OER activities of metal oxides significantly depend on electrochemical surface area (ECSA) and activity per surface area (specific activity). However, it is not easy to decouple these two factors when the surface structure and composition change continuously during the OER. Electrochemical impedance spectroscopy (EIS) has been used as a useful tool, which provides information related to electrode/electrolyte interface 3 . Here, in order to reveal the origin of the OER activities behavior, we used 3D EIS including time axis and tracked the ECSA and specific activity of perovskite oxides during the OER in alkaline solutions. Experimental methods Perovskite oxides used in this study (BSCF, La 0.5 Sr 0.5 Co 0.8 Fe 0.2 O 3– δ (LSCF) and LaCoO 3– δ (LCO)) were synthesized by the sol–gel method. The OER activities of obtained perovskite oxides were evaluated using a three-electrode electrochemical cell with a rotating disk electrode (RDE) in 1.0 mol dm –3 KOH solution. A working electrode was prepared by drop-casting an ink suspension with perovskite oxides (0.25 mg cm –2 ), acetylene black (0.05 mg cm –2 ), and Nafion (0.05 mg cm –2 ) on glassy carbon. Pt wire and a reversible hydrogen electrode (RHE) were used as the counter and reference electrodes, respectively. 3D EIS was obtained in the following steps: First, cyclic voltammetry (CV) was performed at certain cycles (1, 5, 10 ,30, and 50 cycles). Second, the electrode was left at open circuit potential for 5 min. Finally, potentiostatic EIS (PEIS) was recorded 5 times (approximately 10 min), and then Nyquist plots at 5 min from the beginning of the first PEIS were compared. Results and discussion From CV measurements of perovskite oxides, while the OER activities of BSCF increased, those of LSCF and LCO slightly decreased with increasing CV cycles. Figure shows Nyquist plots of perovskite oxides after certain CV cycles. The impedance spectra show a semicircle in the high- and mid-frequency regions, respectively. While a semicircle in the high-frequency region was independent on the direct current (DC) potential, the mid-frequency region semicircle was dependent on DC potential. The contrasting behavior indicated that the semicircle in the mid-frequency region corresponds to the charge transfer resistance, which contains the information of double-layer capacitance for the OER. Therefore, we tracked the semicircle in the mid-frequency region during the OER. A semicircle in the mid-frequency region of BSCF gradually decreased with CV cycles, indicating that the BSCF surface changed to a preferred structure during the OER cycles. As a result of the equivalent circuit fitting, the charge transfer resistance decreased and the double-layer capacitance increased with CV cycles. On the other hand, a semicircle in the mid-frequency region of LSCF and LCO remained unchanged or slightly increased. More detailed evaluation of their ECSA and specific activities during OER will be discussed at the conference. Reference [1] J. Suntivich, K. J. May, H. A. Gasteiger, J. B. Goodenough and Y. Shao−Horn, Science , 334 , 1383 (2011). [2] K. J. May, C. E. Carlton, K. A. Stoerzinger, M. Risch, J. Suntivich, Y.-L. Lee, A. Grimaud and Y. Shao-Horn, J. Phys. Chem. Lett. , 3 , 3264 (2012) [3] V. A. Alves, L. A. da Silva, and J. F. C. Boodts, Electrochim. Acta , 44 , 1525 (1998). Figure 1    

    

* Iron Phosphates as Highly Efficient Precatalysts for Oxygen Evolution Reaction and Their in Situ Electrochemical Conversion  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663201
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422141mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663201"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663201"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663201"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663201 (Open access: False)
    
[[https://openalex.org/A5020049969][Yuuki Sugawara]], [[https://openalex.org/A5075720737][Keigo Kamata]], [[https://openalex.org/A5008418848][Ayaka Matsuda]], [[https://openalex.org/A5020439739][Takeo Yamaguchi]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422141mtgabs 
     
Current energy issues have prompted demand for the innovations in constructing a clean and sustainable energy platforms. One of examples for energy carrier to actualize a zero carbon society is hydrogen, which is a promising carbon-free fuel with an excellent weight energy density. Hydrogen production through alkaline water electrolysis using renewable energy resources (light and wind)-derived electricity is an attractive ecofriendly and cost-effective technology because cheap nonprecious electrocatalysts can be employed in alkaline media. However, oxygen evolution reaction (OER) at the anode side in the water electrolysis is basically slow and prevents the widespread applications of water electrolysis. Thus, highly efficient and cheap electrocatalysts for OER are highly desirable. Iron (Fe)-based compounds have recently received much attention as OER electrocatalysts because Fe is a quite earth-abundant metallic element that is a very cheap and non-toxic. Therefore, Fe is a promising candidate as electrocatalyst for OER. Due to the insufficient OER activity on simple Fe oxides, previous studies have attempted to enhance the activity by incorporating Fe and other metallic elements. [1,2] Recently, we established a novel comprehensive structural descriptor for the OER on Fe-based simple and multimetal oxides; [3] i.e. , shorter minimum Fe–O bond length in the crystalline structures led to higher OER activity regardless of elemental composition, Fe–O coordination number, and crystal category. Thus, this descriptor enabled us to quickly develop excellent OER catalyst, Ba 0.65 Ca 0.35 Fe 12 O 19 , comprising extremely short Fe–O bond lengths. [4] Furthermore, we found that post-spinel CaFe 2 O 4 catalyzes OER via "multi-iron-site mechanism" involving a reaction intermediate with O–O direct formation on multiple Fe atoms, and CaFe 2 O 4 consequently displayed outstanding OER activity despite the long Fe–O bond length. [5] However, we speculate that OER activity of Fe-based oxides cannot be further enhanced based on crystal structures, and it necessitates to employ another type of compounds. In this study, we report the OER performances of Fe-based phosphates in alkaline media. We selected three kinds of Fe-based phosphates with distinct crystal structures: trigonal FePO 4 , trigonal Fe 3 O 3 (PO 4 ), and monoclinic Fe 4 (P 2 O 7 ) 3 . The electrochemical measurements and post-characterizations identified the Fe-based phosphates as efficient precatalysts that can be electrochemically converted into highly active Fe-based compounds. Notably, the OER performances of the electrochemically converted Fe-based compounds overcame those of the above-mentioned most active Fe-based multimetal oxides and any previously reported crystalline OER electrocatalysts. Therefore, the Fe-based phosphates are promising candidates as OER precatalysts, which can be in situ converted into excellent OER electrocatalysts, and have further advantages of low price, environmental friendliness, and easy production. [6] The part of this paper is based on results obtained from a project, JPNP14021, commissioned by the New Energy and Industrial Technology Development Organization (NEDO). This paper was funded in part by the JSPS KAKENHI Grant-in-Aid (18H01786), the JST PRESTO (JPMJPR15S3) and CREST (JPMJCR16P3) programs, the Tokuyama Science Foundation, and the “Creation of Life Innovative Materials for Interdisciplinary and International Researcher Development” program of the MEXT. The authors thank Dr. Takeshi Aihara in Tokyo Institute of Technology for fruitful discussions. References [1] I. Yamada, A. Takamatsu, K. Asai, T. Shirakawa, H. Ohzuku, A. Seno, T. Uchimura, H. Fujii, S. Kawaguchi, K. Wada, H. Ikeno, S. Yagi, J. Phys. Chem. C , 2018 , 122 , 27885. [2] B. H. Han, A. Grimaud, L. Giordano, W. T. Hong, O. Diaz-Morales, L. Yueh-Lin, J. Hwang, N. Charles, K. A. Stoerzinger, W. L. Yang, M. Y. M. Koper, Y. Shao-Horn, J. Phys. Chem. C, 2018 , 122 , 8445. [3] Y. Sugawara, K. Kamata, E. Hayashi, M. Itoh, Y. Hamasaki, T. Yamaguchi ChemElectroChem , 2021 , 8 , 4466. [4] Y. Sugawara. S. Ueno, K. Kamata, T. Yamaguchi, ChemElectroChem , 2022 , 9 , e202101679. [5] Y. Sugawara, K. Kamata, A. Ishikawa, Y. Tateyama, T Yamaguchi, ACS Appl. Energy Mater. , 2021 , 4 , 3057. [6] Y. Sugawara, K. Kamata, A. Matsuda, T. Yamaguchi, ACS Appl. Energy Mater. , 2023 , in press.    

    

* Lanthanide Vanadate: An Efficient and Stable Oxygen Evolution Reaction Catalyst for Enhanced Water-Splitting Applications  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391637756
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02653171mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391637756"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391637756"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391637756"))][Get cited by]]

OpenAlex: https://openalex.org/W4391637756 (Open access: False)
    
[[https://openalex.org/A5017095603][Youness El Issmaeli]], [[https://openalex.org/A5042511611][Amina Lahrichi]], [[https://openalex.org/A5048345538][Shankara S. Kalanur]], [[https://openalex.org/A5010934181][S. Natarajan]], [[https://openalex.org/A5045098563][Bruno G. Pollet]], ECS Meeting Abstracts. MA2023-02(65)] 2023. https://doi.org/10.1149/ma2023-02653171mtgabs 
     
Hydrogen fuel production through water-splitting reactions offers a sustainable approach to store renewable energies. However, the efficiency of this process is impeded by the oxygen evolution reaction (OER), a complex four-electron oxidation half-reaction. In this study, we present a highly active and stable OER catalyst, lanthanide vanadate (LnVO 4 - Ln = La to Lu), synthesized using a straightforward hydrothermal method. Comprehensive characterization of the electrocatalysts was performed employing scanning electron microscopy (SEM), transmission electron microscopy (TEM), X-ray photoelectron spectroscopy (XPS), and X-ray diffraction (XRD) analysis. When applied to nickel (Ni) foam, lanthanide vanadate achieved a current density of 10 mA cm -2 at an overpotential of +280 mV in a 1.0 M KOH electrolyte. Furthermore, exceptional stability was demonstrated for over 5 hours of continuous operation. These findings highlight the potential of lanthanide vanadate-based materials as promising catalysts for efficient and stable overall water-splitting processes.    

    
