#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Tue Jan 30 00:38:43 2024

Found 49 results from 2024-01-16 to 2024-01-30
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

** Mil-101(Fe)-Derivatized Cathode as an Efficient Oxygen Electrocatalyst for Rechargeable Zn-Air Battery   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4695712")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390870941"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390870941"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390870941"))][Get cited by]]

OpenAlex: https://openalex.org/W4390870941 (Open access: False)
    
[[https://openalex.org/A5085411841][Long Hao]], [[https://openalex.org/A5030380449][Rui Guo]], [[https://openalex.org/A5074617036][Ting Yu]], [[https://openalex.org/A5011907117][Chunming Liu]], [[https://openalex.org/A5019173699][Jingbi You]], [[https://openalex.org/A5007642500][Hangzhou Zhang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4695712 
     
The exploration of multifunctional electrocatalysts with cost-effective and high kinetic activity for oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) is crucial for the development of advanced energy conversion and storage equipment. Herein, A novel hierarchical mesoporous/macropores MIL-101(Fe) derivative carbon catalyst material was prepared by a simple molten ZnCl2-assisted synthesis route. Specifically, 1H-benzotriazole (BTA) organic ligands were intentionally introduced as nitrogen sources in order to induce the formation of charge-rich regions through an electronegative nitrogen doping control strategy, and most importantly, the lone pair electron-rich nature of element N could facilitate the separation and anchoring of iron species enchanted the utilization rate of active sites. Because of these properties, the as-prepared catalyst (denoted as FeSACs/NxC) possesses unrivalled bifunction electrocatalytic activity and durability for the ORR and OER. The FeSACs/N1.25C as working electrode exhibits a quite satisfactory electrochemical performance for the ORR (half-wave potential of 0.82 V) and OER (a small overpotential of 302 mV at 10 mA cm−2) in the classic three-electrode configuration. Moreover, the FeSACs/N1.25C-based air cathode imparts encouraging performance in a rechargeable Zn–air battery prototype with an open-circuit voltage of 1.45 V, a specific capacity of 792.16 mAh g−1, an energy density of 871.38 Wh kg−1, and excellent stability for 120 h. This work has opened the way for the development of low-cost, fast kinetic and stable non-noble metal multifunctional catalysts.    

    

** High‐Surface Area Mesoporous Sc2o3 with Abundant Oxygen Vacancies as New and Advanced Electrocatalyst for Electrochemical Biomass Valorization   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202311698")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390871310"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390871310"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390871310"))][Get cited by]]

OpenAlex: https://openalex.org/W4390871310 (Open access: False)
    
[[https://openalex.org/A5027160438][Yufeng Wu]], [[https://openalex.org/A5009621488][Lei Ma]], [[https://openalex.org/A5026592308][Jialing Wu]], [[https://openalex.org/A5060768508][Maoyong Song]], [[https://openalex.org/A5086584148][Changlong Wang]], [[https://openalex.org/A5036668774][Jun Lü]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202311698 
     
Scandium oxide (Sc2 O3 ) is considered as omnipotent "Industrial Ajinomoto" and holds promise in catalytic applications. However, rarely little attention have been paid to its electrochemistry. Here, we reported the first nanocasting design of high-surface area Sc2 O3 with abundant oxygen vacancies (mesoporous VO -Sc2 O3 ) for efficient electrochemical biomass valorization. In the case of the electro-oxidation of 5-hydroxymethylfurfural (HMF) to 2,5-furandicarboxylic acid (FDCA), quantitative HMF conversion, high yield and high faradic efficiency of 2,5-furandicarboxylic acid (FDCA) via the hydroxymethylfurancarboxylic acid (HMFCA) pathway were achieved by this advanced electrocatalyst. The beneficial effect of the VO on the electrocatalytic performance of the mesoporous VO -Sc2 O3 was revealed by the enhanced adsorption of reactants and the reduced energy barrier in the electrochemical process. The concerted design, in-situ and ex-situ experimental studies and theoretical calculations shown in this work should shed light on the rational elaboration of advanced electrocatalysts, and contribute to the establishment of a circular carbon economy since the bio-plastic monomer and green hydrogen are efficiently synthesized. This article is protected by copyright. All rights reserved.    

    

** Ni2p-Nise2 Heterostructure Aerogel for Highly Efficient Electrocatalytic Hydrogen Evolution and 5-Hydroxymethylfurfural Oxidation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4695647")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390872314"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390872314"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390872314"))][Get cited by]]

OpenAlex: https://openalex.org/W4390872314 (Open access: False)
    
[[https://openalex.org/A5014235931][Hongchen Liu]], [[https://openalex.org/A5034255116][Fan Yang]], [[https://openalex.org/A5002894983][Zhengyang Chen]], [[https://openalex.org/A5050938886][Jialin Qian]], [[https://openalex.org/A5025592561][Jianfeng Wang]], [[https://openalex.org/A5033201032][Yongfeng Li]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4695647 
     
Green hydrogen prepared by the cathodic hydrogen evolution reaction (HER) of renewable energy water electrolysis is one of the best choices for future energy. However, the anodic oxygen evolution reaction (OER) with high theoretical potential limits the efficiency of overall water splitting. Herein, a bifunctional Ni2P-NiSe2 heterostructure aerogel (Ni-P-Se aerogel) was constructed to boost HER and replace OER by 5-hydroxymethylfurfural oxidation reaction (HMFOR) to produce high-valued 2,5-furandicarboxylic acid (FDCA) with low operating voltage and high conversion. The NiSe2 with cubic pyrite-type crystal structure was favor for anodic reconstruction, which allowed the effective generation of activated oxygen species and further promoted HMFOR. Moreover, the coupling of Ni2P modulated the adsorption energy of OH- in HMFOR and enhanced the activity toward HER. Besides, the aerogel structure with porous network structure provides abundant active sites and mass-transfer pathways. Benefit from these advantages, the optimized Ni-P-Se aerogel exhibited high HER performance (68 mV at 10 mA·cm-2), low onset oxidation potential (1.30 V) and high Faradaic efficiency (97.4%) and FDCA production rate (99.2 μmolFDCA·h-1·cm-2) of HMFOR. Compared to OER, the two-electrode system coupled with HMFOR had significantly increased current density at low operating voltage (87 mA·cm-2 increase at 1.50 V), proving the superiority of HMFOR as alternative anodic reaction. This work offers an anticipated perspective of bifunctional electrocatalysts toward the combination of HER and organics oxidation.    

    

** Strategically Designed Pd-Induced Changes in Alkaline Hydrogen Evolution Reaction and Oxygen Evolution Reaction Performances of Electrochemical Water Oxidation by the Galvanically Synthesized MoO2/MoO3 Composite Thin Film   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.3c16499")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390873823"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390873823"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390873823"))][Get cited by]]

OpenAlex: https://openalex.org/W4390873823 (Open access: False)
    
[[https://openalex.org/A5090569641][Uday Kumar Ghorui]], [[https://openalex.org/A5067363426][Bibhutibhushan Show]], [[https://openalex.org/A5058114509][Dipayan Roy]], [[https://openalex.org/A5086114063][Arindam Basak]], [[https://openalex.org/A5058050968][Bibhutosh Adhikary]], [[https://openalex.org/A5091390027][Anup Mondal]], No host. None(None)] 2024. https://doi.org/10.1021/acsami.3c16499 
     
Electrochemical water oxidation is believed to be an effective pathway to produce clean, carbon-free, and environmentally sustainable green energy. In this work, we report a simple, easy-to-construct, facile, low-cost, and single-step galvanic technique to synthesize a Pd-supported temperature-assisted MoOx thin film nanocomposite for effective water oxidation. The most suitable nanocomposite exhibits very low overpotential at 10 mA/cm2 with smaller Tafel slope values for both hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) processes in an alkaline medium. The formation of a metal oxide-metal junction accelerates the growth of more active sites, promoting induced electronic synergism at the MoOx-Pd interface. This endows higher electrical conductivity and faster electron transfer kinetics, thus accelerating the faster water dissociation reaction following the Tafel-Volmer mechanism to boost the HER process in an alkaline medium. The excellent electrochemical HER and OER performances of our electrocatalyst even supersede the accomplishments of the benchmark catalysts Pt/C and RuO2. Moreover, neither of these two catalysts demonstrates both catalytic reactions, i.e., HER and OER at the same time, which have been observed for our synthesized catalyst. Our findings illustrate the potential of a thin-film MoOx-Pd nanocomposite to be an exceedingly effective electrocatalyst developed by interface engineering strategies. This also provides insight into designing several other semiconductor composite catalysts using simple synthesis techniques for highly efficient HER/OER processes that could be alternatives to benchmark electrocatalysts for water electrolysis.    

    

** Microzone-Acidification-Driven Degradation Mechanism of the NiFe-Based Anode in Seawater Electrolysis   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.3c13929")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390882210"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390882210"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390882210"))][Get cited by]]

OpenAlex: https://openalex.org/W4390882210 (Open access: False)
    
[[https://openalex.org/A5023790454][Mengyi Tang]], [[https://openalex.org/A5037293109][Keming Du]], [[https://openalex.org/A5038107949][Rui Yu]], [[https://openalex.org/A5003529917][Hao Shi]], [[https://openalex.org/A5063467703][Peilin Wang]], [[https://openalex.org/A5009399906][Yifan Guo]], [[https://openalex.org/A5012532235][Qinyi Wei]], [[https://openalex.org/A5082860861][Huayi Yin]], [[https://openalex.org/A5001972742][Dihua Wang]], No host. None(None)] 2024. https://doi.org/10.1021/acsami.3c13929 
     
The anode stability is critical for efficient and reliable seawater electrolyzers. Herein, a NiFe-based film catalyst was prepared by anodic oxidation to serve as a model electrode, which exhibited a satisfactory oxygen evolution performance in simulated alkaline seawater (1 M KOH + 0.5 M NaCl) with an overpotential of 348 mV at 100 mA cm–2 and a long-term stability of over 100 h. After that, the effects of the current density and bulk pH of the electrolyte on its stability were evaluated. It was found that the electrode stability was sensitive to electrolysis conditions, failing at 20 mA cm–2 in 0.1 M KOH + 0.5 M NaCl but over 500 mA cm–2 in 0.5 M KOH + 0.5 M NaCl. The electrode dissolved, and some precipitates immediately formed at the region very close to the electrode surface during the electrolysis. This can be ascribed to the pH difference between the electrode/electrolyte interface and the bulk electrolyte under anodic polarization. In other words, the microzone acidification accelerates the corrosion of the electrode by Cl–, thus affecting the electrode stability. The operational performances of the electrode under different electrolysis conditions were classified to further analyze the degradation behavior, which resulted in three regions corresponding to the stable oxygen evolution, violent dissolution–precipitation, and complete passivation processes, respectively. Thereby increasing the bulk pH could alleviate the microzone acidification and improve the stability of the anode at high current densities. Overall, this study provides new insights into understanding the degradation mechanism of NiFe-based catalysts and offers electrolyte engineering strategies for the application of anodes.    

    

** NiCo2S4 octahedral configuration doped by Mn, Zn and Cu for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cc06171j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390883323"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390883323"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390883323"))][Get cited by]]

OpenAlex: https://openalex.org/W4390883323 (Open access: False)
    
[[https://openalex.org/A5019389546][Yi-Ting Chen]], [[https://openalex.org/A5015792001][Wu H]], [[https://openalex.org/A5056540688][Ning Tang]], [[https://openalex.org/A5051439492][Mengjie Zhang]], [[https://openalex.org/A5067124076][Yuqiao Wang]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d3cc06171j 
     
Transition metals with similar atomic radius were used to doping spinel NiCo2S4 to adjust octahedral configuration. Mn dopants adjusted the morphology and surface charge distribution, optimized the electron transport and...    

    

** Harnessing Wind Energy for Ultraefficient Green Hydrogen Production with Tin Selenide/Tin Telluride Heterostructures   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smsc.202300222")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390883629"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390883629"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390883629"))][Get cited by]]

OpenAlex: https://openalex.org/W4390883629 (Open access: True)
    
[[https://openalex.org/A5046860517][Aparna Sajeev]], [[https://openalex.org/A5044682504][M. Perumalsamy]], [[https://openalex.org/A5093720829][Vijaykumar Elumalai]], [[https://openalex.org/A5087122773][Arunprasath Sathyaseelan]], [[https://openalex.org/A5032684520][A. Saravanakumar]], [[https://openalex.org/A5057045759][Monunith Anithkumar]], [[https://openalex.org/A5081731391][Sang‐Jae Kim]], No host. None(None)] 2024. https://doi.org/10.1002/smsc.202300222  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/smsc.202300222][pdf]])
     
Industrialization of green hydrogen production through electrolyzers is hindered by cost‐effective electrocatalysts and sluggish oxygen evolution reaction (OER). Herein, a facile one‐step hydrothermal technique for the in situ growth of non‐noble tin chalcogenides and their heterostructures on nickel foam (NF) as trifunctional electrocatalysts for hydrogen evolution reaction (HER), OER, and methanol oxidation reaction (MOR) is detailed. Among them, the heterostructured SnSe/SnTe/NF outperforms all others and recently reported catalysts, boasting an impressively low potential of −0.077, 1.51, and 1.33 V versus reversible hydrogen electrode to achieve 10 mA cm −2 for HER, OER, and MOR. Owing to the rod‐like morphology with hetero‐phases for enhancing the performance. Furthermore, a hybrid MOR‐mediated water electrolyzer requiring only 1.49 V to achieve 10 mA cm −2 with value‐added formate is introduced and traditional water electrolyzer is outperformed. Additionally, a zero‐gap commercial anion‐exchange membrane water electrolyzer (AEMWE) with bifunctional SnSe/SnTe/NF electrodes is tested, successfully achieving an industrially required 1 A cm −2 at a low potential of 1.93 V at 70 °C. Moreover, AEMWE using a windmill is powered and H 2 and O 2 production with wind speed is measured. Overall, this work paves the development of unexplored tin chalcogenide heterostructure as a potent candidate for cost‐effective, energy‐efficient, and carbon‐neutral hydrogen production.    

    

** Hybrid Zeolitic Imidazolate Framework‐Derived Co3Mo/Mo2C Heterostructure for Enhanced Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202314247")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390883869"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390883869"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390883869"))][Get cited by]]

OpenAlex: https://openalex.org/W4390883869 (Open access: False)
    
[[https://openalex.org/A5045774406][Xiao‐Li Wang]], [[https://openalex.org/A5002854208][Liming Sun]], [[https://openalex.org/A5025620806][Lei Yang]], [[https://openalex.org/A5087869625][Jianwei Zhao]], [[https://openalex.org/A5064109029][Qiang Xu]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202314247 
     
Abstract Constructing heterostructures is an efficient strategy to develop high‐performance and robust electrocatalysts for oxygen evolution reaction (OER). Herein, an ion‐impregnation method and an environmentally friendly in situ carbonization strategy are successively employed to fabricate a novel Co 3 Mo/Mo 2 C heterostructure anchored on nitrogen‐doped carbon (Co 3 Mo/Mo 2 C@NC). Thanks to the formation of heterostructure, the obtained Co 3 Mo/Mo 2 C@NC exhibits an enhanced catalytic performance toward OER with a low overpotential (282 mV @ 10 mA cm −2 , 322 mV @ 50 mA cm −2 , and 355 mV @100 mA cm −2 ) and robust stability (100 mA cm −2 for 200 h) in alkaline media. Detailed experimental results combined with theoretical calculations reveal the formation of a Co 3 Mo/Mo 2 C heterojunction interface can decrease the energy barrier of the rate‐determining step for intermediates during the OER process, thereby inherently enhancing the OER performance. This work presents a rational synthetic route for designing high‐performance heterostructures for energy conversion technologies.    

    

** Progress on Bifunctional Carbon‐Based Electrocatalysts for Rechargeable Zinc–Air Batteries Based on Voltage Difference Performance   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202303352")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390884699"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390884699"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390884699"))][Get cited by]]

OpenAlex: https://openalex.org/W4390884699 (Open access: False)
    
[[https://openalex.org/A5067857962][Yubin Song]], [[https://openalex.org/A5081239726][Weijie Li]], [[https://openalex.org/A5003850660][Kai Zhang]], [[https://openalex.org/A5043886297][Chao Han]], [[https://openalex.org/A5018192733][Anqiang Pan]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202303352 
     
Abstract Zinc–air batteries (ZABs) hold potential as clean, cost‐effective, and sustainable energy storage system for the next generation. However, the application of ZABs remains challenging because of their poor rechargeability and low efficiency . The design of efficient bifunctional catalysts toward oxygen reduction reaction (ORR) during discharging and the oxygen evolution reaction (OER) during charging is essential to developing rechargeable ZABs. Transition metal (TM)‐doped carbon (TM‐C) materials stand out from all the available bifunctional catalysts due to the excellent specific surface area, diverse morphological structures , and the multiple metal active sites formed after TM doping. This paper, therefore, focuses on the synthesis, electrochemical properties, and potential mechanism of TM‐C catalysts. To make a novelty and logical statement, the voltage difference (Δ E = E i = 10 − E 1/2 ) between the ORR/OER catalytic process is employed to categorize different TM‐C catalysts reported in recent years, which are divided into two groups: I (Δ E = 0.7 − 0.9 V) and II (Δ E = 0.5 − 0.7 V). The catalytic mechanisms of bifunctional catalysts are clarified. More ways and ideas for synthesizing high‐performance bifunctional TM‐C catalysts are also provided. Finally, the current problem and prospects of this group materials are presented.    

    

** Synthesis and Electrocatalytic Applications of Layer‐Structured Metal Chalcogenides Composites   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310526")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390884831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390884831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390884831"))][Get cited by]]

OpenAlex: https://openalex.org/W4390884831 (Open access: False)
    
[[https://openalex.org/A5000836661][Yongteng Qian]], [[https://openalex.org/A5066738004][Fangfang Zhang]], [[https://openalex.org/A5026571332][Xingguang Luο]], [[https://openalex.org/A5037880072][Yijun Zhong]], [[https://openalex.org/A5061505485][Dae Joon Kang]], [[https://openalex.org/A5004880276][Yong Hu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202310526 
     
Abstract Featured with the attractive properties such as large surface area, unique atomic layer thickness, excellent electronic conductivity, and superior catalytic activity, layered metal chalcogenides (LMCs) have received considerable research attention in electrocatalytic applications. In this review, the approaches developed to synthesize LMCs‐based electrocatalysts are summarized. Recent progress in LMCs‐based composites for electrochemical energy conversion applications including oxygen reduction reaction, carbon dioxide reduction reaction, oxygen evolution reaction, hydrogen evolution reaction, overall water splitting, and nitrogen reduction reaction is reviewed, and the potential opportunities and practical obstacles for the development of LMCs‐based composites as high‐performing active substances for electrocatalytic applications are also discussed. This review may provide an inspiring guidance for developing high‐performance LMCs for electrochemical energy conversion applications.    

    

** Novel Heterostructure‐Based CoFe and Cobalt Oxysulfide Nanocubes for Effective Bifunctional Electrocatalytic Water and Urea Oxidation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310112")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390884900"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390884900"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390884900"))][Get cited by]]

OpenAlex: https://openalex.org/W4390884900 (Open access: False)
    
[[https://openalex.org/A5076825790][Athibala Mariappan]], [[https://openalex.org/A5072181586][M. Karthigai Pandian]], [[https://openalex.org/A5026280033][Kugalur Shanmugam Ranjith]], [[https://openalex.org/A5065751319][Ta Thi Thuy Nga]], [[https://openalex.org/A5077558935][Young‐Kyu Han]], [[https://openalex.org/A5047174251][Chung‐Li Dong]], [[https://openalex.org/A5086593828][Ranjith Kumar Dharman]], [[https://openalex.org/A5086593828][Ranjith Kumar Dharman]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202310112 
     
Abstract The development of effective oxygen evolution reaction (OER) and urea oxidation reaction (UOR) on heterostructure electrocatalysts with specific interfaces and characteristics provides a distinctive character. In this study, heterostructure nanocubes (NCs) comprising inner cobalt oxysulfide (CoOS) NCs and outer CoFe (CF) layered double hydroxide (LDH) are developed using a hydrothermal methodology. During the sulfidation process, the divalent sulfur ions (S 2− ) are released from the breakdown of the sulfur source and react with the Co‐precursors on the surface leading to the transformation of CoOH nanorods into CoOS nanocubes. Further, X‐ray photoelectron spectroscopy (XPS) and X‐ray absorption spectroscopy (XAS) analyses reveal that the interactions at the interface of the CF@CoOS NCs significantly altered the electronic structure, thus enhancing the electrocatalytic performance. The optimal catalysts exhibited effective OER and UOR activities, the attained potentials are 1.51 and 1.36 V. This remarkable performance is attributable to the induction of electron transfer from the CoFe LDH to CoOS, which reduces the energy barrier of the intermediates for the OER and UOR. Furthermore, an alkaline water and urea two‐cell electrolyzer assembled using CF@CoOS‐2 NCs and Pt/C as the anode and cathode requires a cell voltage of 1.63 and 1.56 V along with a durability performance.    

    

** Dual-modified engineering suppressed the formation of Li-concentration gradient and oxygen vacancies for single-crystal Ni-rich layered cathodes   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159398")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390886748"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390886748"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390886748"))][Get cited by]]

OpenAlex: https://openalex.org/W4390886748 (Open access: False)
    
[[https://openalex.org/A5043326307][L. Liu]], [[https://openalex.org/A5028628264][Yuanduo Qu]], [[https://openalex.org/A5023413170][Zhencheng Xie]], [[https://openalex.org/A5013085238][Xin Zhong]], [[https://openalex.org/A5072625816][Junkai Wang]], [[https://openalex.org/A5043819030][Shilong Su]], [[https://openalex.org/A5025299463][Di He]], [[https://openalex.org/A5055884922][Qiuyan Li]], [[https://openalex.org/A5090394279][Lianfeng Duan]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159398 
     
Ni-rich single-crystal layered cathodes, LiNixCoyMnzO2 (SC-NCM, x ≥ 0.6), have been considered as the most favorable candidates for next-generation high-performance batteries. However, the rapid lithium concentration gradient and increased oxygen vacancies, caused by electrode/electrolyte interface degradation, are the primary reasons leading to the formation of irreversible intergranular cracks and the deterioration of material properties. Herein, the dual-modified LiNi0.6Co0.2Mn0.2O2 (SC-NCM622) nanoparticle with LiTaO3 protective layer containing Ta5+ is synthesized by a facile sol–gel method. The dual-modified strategy could provide rapid lithium-ion channels, effectively relieving stress evolution, polarization, and dynamic degradation of cathode materials during cycling. This strategy hinders the formation of oxygen vacancies on the cathode surface and prevents the development of intragranular cracks. As expected, the 2 wt% LTO@SC-NCM622 exhibits excellent capacity retention of 90.39 % at 1 C after 200 cycles. Even at 10 C, the 2 wt%LTO@SC-NCM622 retains a specific capacity of 88.7 mAh g−1 (82.7 %) after 500 cycles. This work offers guidance for the design of new stable Ni-rich cathodes for next-generation LIBs.    

    

** A Facile Approach to Construct Co2p@Fe(Po3)2-Ncnt Heterojunction with Highly Dispersed Active Sites for Photosensitive Oxygen Reduction Reaction and Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4695434")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390887127"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390887127"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390887127"))][Get cited by]]

OpenAlex: https://openalex.org/W4390887127 (Open access: False)
    
[[https://openalex.org/A5081438845][Junhua Song]], [[https://openalex.org/A5015150923][Xue Li]], [[https://openalex.org/A5012333741][Zuoxu Xiao]], [[https://openalex.org/A5052810141][Tianle Yang]], [[https://openalex.org/A5001989550][Chenhuinan Wei]], [[https://openalex.org/A5079661540][Hongyan Zhuo]], [[https://openalex.org/A5073080176][Wenmiao Chen]], [[https://openalex.org/A5001530798][Yanli Chen]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4695434 
     
A facile pre-anchored approach is employed to prepare a non-precious bifunctional electrocatalyst Co2P@Fe(PO3)2-NCNT with a p−n heterojunction structure for the oxygen reduction reaction (ORR) and oxygen evolution reaction (OER). Firstly, a well-designed Co3O4/Fe(CN)64−@PPy-CNT precursor is synthesized via an one-pot method, in which Fe(CN)64− and Co3O4 are pre-anchored on polypyrrole (PPy) chains that in-situ formed on carbon nanotubes (CNTs). Subsequent pyrolysis and phosphating of the precursor resulted in the Co2P@Fe(PO3)2-NCNT catalyst, which contains highly dispersed Co2P and Fe(PO3)2 nanoparticles within N-doped carbon (NCNT). Compared to Co2P-NCNT with only n-type Co2P, introducing p-type Fe(PO3)2 into Co2P@Fe(PO3)2-NCNT leads to not only its Fermi level (EF) closer to Pt, but a larger energy gap between EF and the conduction band. This makes it a higher half-wave potential (E1/2) of 0.85 V for ORR, and a lower overpotential (η10) of only 300 mV for OER, superior to both Co2P-NCNT (E1/2 = 0.76 V, η10 = 510 mV), the commercial 20% Pt/C (E1/2 = 0.84 V) and RuO2 (η10 = 360 mV). Impressively, the unique p−n heterojunction structure of Co2P@Fe(PO3)2-NCNT is resulted in the significant improvement on both ORR with E1/2 increased by 10 mV and OER with overpotential decreased by 20 mV under visible light.    

    

** None   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cjoc.v42.4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390891343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390891343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390891343"))][Get cited by]]

OpenAlex: https://openalex.org/W4390891343 (Open access: False)
    
, Chinese Journal of Chemistry. 42(4)] 2024. https://doi.org/10.1002/cjoc.v42.4 
     
Fe-based oxyhydroxides are state-of-the-art electrocatalysts for alkaline OER, however, the role of Fe still remains a hot topic of considerable discussion over the past decades. The in situ generated Fe vacancies on CoFeOOH derived from dynamic Fe dissolution during OER process are responsible for the significantly enhanced OER performance. More details are discussed in the article by Luo et al. on page 343—350.    

    

** Low onset potential for oxygen evolution reaction on hematite electrodes processed with He plasma irradiation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.110")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390892019"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390892019"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390892019"))][Get cited by]]

OpenAlex: https://openalex.org/W4390892019 (Open access: False)
    
[[https://openalex.org/A5010001497][Shin Kajita]], [[https://openalex.org/A5087006716][Anja Bieberle‐Hütter]], International Journal of Hydrogen Energy. 57(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.01.110 
     
In this study, we investigated the effects of helium (He) plasma irradiation and thermal treatment on the morphology, the surface characteristics, and the photoelectrochemical performance of bulk iron (Fe) sheets. After processing, all samples consisted mainly of an α-Fe2O3 surface. Helium plasma irradiation resulted in a cathodic shift in the onset potential of the photocurrent from 1.16 VRHE (no pretreatment) to 0.57 VRHE (plasma exposure at 660 °C), where VRHE represents the potential versus reversible hydrogen electrode (RHE). An increase in the surface roughness and a smaller amount of hydroxyl or oxygen vacancies at the surface after photoelectrochemical measurement are related to the decrease of the onset potential. The results show that He plasma irradiation does not only modify the surface morphology, but also affects the functional properties of the materials.    

    

** Unveiling the electrochemical activation mechanism of Prussian blue analogue pre-catalysts for high-efficient oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26599/emd.2023.9370014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390894160"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390894160"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390894160"))][Get cited by]]

OpenAlex: https://openalex.org/W4390894160 (Open access: True)
    
[[https://openalex.org/A5088850707][Han‐Xun Wei]], [[https://openalex.org/A5047557663][Huanhuan Sun]], [[https://openalex.org/A5079043288][Yueying Li]], [[https://openalex.org/A5058932447][Jintao Zhang]], [[https://openalex.org/A5070964621][Jian‐Gan Wang]], Energy Materials and Devices. None(None)] 2024. https://doi.org/10.26599/emd.2023.9370014  ([[https://file.sciopen.com/sciopen_public/1747072852409516033.pdf][pdf]])
     
Prussian blue analogues (PBAs) are regarded as effective pre-catalysts for oxygen evolution reaction (OER), but the underlying mechanism of their electrochemical activation is still not well elucidated. In this work, we design and construct PBAs-based pre-catalysts to unveil the activation mechanism and achieve high-efficient OER. The PBAs undergo in situ electrochemical transformation to form the corresponding metal (oxy)hydroxides (M(O)OH) as the true OER catalyst. More importantly, the hexacyanoferrate ligands are unveiled to experience repetitive interfactial coordination/etching with/from the M(O)OH during the activation process. The distinct mechanism could achieve in situ Fe doping and the increase of defect concentration. The defect-enriched Fe-NiOOH derived from a well-designed NiHCF/Ni(OH)2 pre-catalyst requires a low overpotential of 227 mV to drive the current density of 10 mA cm-2, and could work stably at 130 mA cm-2 over 100 h. This work offers a fundamental insight into the activation mechanism for developing advanced pre-catalysts for OER.    

    

** Understanding Highly Active and Durable Fe-Doped Co(Oh)2 Catalysts in Alkaline Oxygen Evolution Reaction by in Situ Xanes Studies   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4697142")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390904175"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390904175"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390904175"))][Get cited by]]

OpenAlex: https://openalex.org/W4390904175 (Open access: False)
    
[[https://openalex.org/A5003171150][Du-Hyeon Kim]], [[https://openalex.org/A5067799791][Yong‐Kul Lee]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4697142 
     
The activation and degradation mechanisms of CoFe layered double hydroxide (CoFe-LDH) and Fe-doped Co(OH)2 (Fe-Co(OH)2) have been investigated using in situ X-ray absorption spectroscopy coupled with cyclic voltammetry (CV) in 0-0.9V (vs Hg/HgO). A series of CoFe-LDH samples have been prepared by co-electrodeposition with varying Co/Fe ratios. Fe-doping on Co(OH)2 has been applied using 10 ppm of Fe in 1.0M KOH. Electrochemical impedance spectroscopy (EIS) and CV cycles confirm the degradation of Co(OH)2 and CoFe-LDH due to the irreversible redox of Co(OH)2/CoOOH, and Fe extraction. In contrast, Fe-doped Co(OH)2 shows high activity and stability in the OER. In situ XANES analysis suggests that the Fe-doping allows the Co(OH)2 to remain as CoOOH even under potential fluctuations.    

    

** Site-specific metal-support interaction to switch the activity of Ir single atoms for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-44815-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390904335"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390904335"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390904335"))][Get cited by]]

OpenAlex: https://openalex.org/W4390904335 (Open access: True)
    
[[https://openalex.org/A5013382299][Jie Wei]], [[https://openalex.org/A5044601163][Hengjing Tang]], [[https://openalex.org/A5010634879][Li Sheng]], [[https://openalex.org/A5033862876][Ruyang Wang]], [[https://openalex.org/A5074130931][Minghui Fan]], [[https://openalex.org/A5018898375][Jin Wan]], [[https://openalex.org/A5091026913][Yaoguo Wu]], [[https://openalex.org/A5000151255][Z. D. Zhang]], [[https://openalex.org/A5039567536][Shiming Zhou]], [[https://openalex.org/A5075571728][Jie Zeng]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-44815-0  ([[https://www.nature.com/articles/s41467-024-44815-0.pdf][pdf]])
     
Abstract The metal-support interactions (MSI) could greatly determine the electronic properties of single-atom catalysts, thus affecting the catalytic performance. However, the typical approach to regulating MSI usually suffers from interference of the variation of supports or sacrificing the stability of catalysts. Here, we effectively regulate the site-specific MSI of Ir single atoms anchored on Ni layered double hydroxide through an electrochemical deposition strategy. Cathodic deposition drives Ir atoms to locate at three-fold facial center cubic hollow sites with strong MSI, while anodic deposition drives Ir atoms to deposit onto oxygen vacancy sites with weak MSI. The mass activity and intrinsic activity of Ir single-atom catalysts with strong MSI towards oxygen evolution reaction are 19.5 and 5.2 times that with weak MSI, respectively. Mechanism study reveals that the strong MSI between Ir atoms and the support stimulates the activity of Ir sites by inducing the switch of active sites from Ni sites to Ir sites and optimizes the adsorption strength of intermediates, thereby enhancing the activity.    

    

** Ligands Defect-Induced Structural Self-Reconstruction of Fe–Ni–Co-Hydroxyl Oxides with Crystalline/Amorphous Heterophase from a 2D Metal–Organic Framework for an Efficient Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05314")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390907090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390907090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390907090"))][Get cited by]]

OpenAlex: https://openalex.org/W4390907090 (Open access: False)
    
[[https://openalex.org/A5091300678][Hongqi Chu]], [[https://openalex.org/A5044789787][Rujin Li]], [[https://openalex.org/A5000139851][Panpan Feng]], [[https://openalex.org/A5086890929][Dongyan Wang]], [[https://openalex.org/A5046884970][Chunxiang Li]], [[https://openalex.org/A5028136131][Yanling Yu]], [[https://openalex.org/A5048237780][Min Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05314 
     
The two-dimensional (2D) Fe–Ni–Co-MOF is synthesized using a simple double ligand strategy at room temperature. The surface reconstruction process transforms it into a crystalline–amorphous heterojunction composed of polycrystalline metal (oxy)hydroxide (MOOH) and amorphous metal oxides/hydroxides with terephthalic acid (TPA) by coordination covalent bonding. In situ Raman spectroscopy discloses the dynamic structure conversion. Density functional theory (DFT), Fourier transform infrared spectroscopy (FTIR), and solid-state nuclear magnetic resonance (SSNMR) reveal the induction of the ligand defects on surface reconstruction and the enhancing effect of TPA on the oxygen evolution reaction (OER) performance through a covalent interaction. The amorphous–crystalline heterojunction of Fe–Ni–CoOOH-TPA has numerous structural defects and high electrical conductivity, resulting in an efficient and stable OER performance with overpotentials of 236 mV at 10 mA cm–2. It has also been observed that the catalyst processes self-healing in an idle state, arising from the reversible conversion of MOOH to M(OH)2. This work reveals the structural and compositional transformation of the 2D Fe–Ni–Co-MOF during surface reconstruction, elucidating the relationship between electrocatalytic reconstruction and water-splitting performance of metal–organic framework (MOF)-based catalysts. It has been proven that appropriate covalent interactions enhance the OER of electrocatalysts.    

    

** Heterojunction Induced Rapid Transformation of Ni3+/Ni2+ Sites Which Mediates Urea Oxidation for Energy‐Efficient Hydrogen Production   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202311766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390907515"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390907515"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390907515"))][Get cited by]]

OpenAlex: https://openalex.org/W4390907515 (Open access: False)
    
[[https://openalex.org/A5081774843][Peng Guo]], [[https://openalex.org/A5014503942][Shoufu Cao]], [[https://openalex.org/A5048074828][Wenjing Huang]], [[https://openalex.org/A5052850228][Xiaoqing Lü]], [[https://openalex.org/A5084151450][Weizhe Chen]], [[https://openalex.org/A5032946295][Youzi Zhang]], [[https://openalex.org/A5039796972][Yijin Wang]], [[https://openalex.org/A5012799970][Xin Xu]], [[https://openalex.org/A5034805827][Ruiqing Zou]], [[https://openalex.org/A5050597874][Sibi Liu]], [[https://openalex.org/A5003462637][Tongtong Li]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202311766 
     
Abstract Water electrolysis is an environmentally‐friendly strategy for hydrogen production but suffers from significant energy consumption. Substituting urea oxidation reaction (UOR) with lower theoretical voltage for water oxidation reaction adopting nickel‐based electrocatalysts engenders reduced energy consumption for hydrogen production. The main obstacle remains strong interaction between accumulated Ni 3+ and *COO in the conventional Ni 3+ ‐catalyzing pathway. Herein, we develop a novel Ni 3+ /Ni 2+ mediated pathway for UOR via constructing a heterojunction of nickel metaphosphate and nickel telluride (Ni 2 P 4 O 12 /NiTe), which efficiently lowers the energy barrier of UOR avoids the accumulation of Ni 3+ and excessive adsorption of *COO on the electrocatalysts. As a result, Ni 2 P 4 O 12 /NiTe demonstrates an exceptionally low potential of 1.313 V to achieve a current density of 10 mA cm −2 towards efficient urea oxidation reaction while simultaneously showcases an overpotential of merely 24 mV at 10 mA cm −2 for hydrogen evolution reaction. Constructing urea electrolysis electrolyzer using Ni 2 P 4 O 12 /NiTe at both sides attains 100 mA cm −2 at a low cell voltage of 1.475 V along with excellent stability over 500 hours accompanied with nearly 100% Faradic efficiency. This article is protected by copyright. All rights reserved    

    

** Electrochemical Synthesis of Ammonia via Nitrogen Reduction and Oxygen Evolution Reactions—A Comprehensive Review on Electrolyte-Supported Cells   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17020441")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390910364"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390910364"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390910364"))][Get cited by]]

OpenAlex: https://openalex.org/W4390910364 (Open access: True)
    
[[https://openalex.org/A5017146414][Hizkia Manuel Vieri]], [[https://openalex.org/A5084484351][M. W. Kim]], [[https://openalex.org/A5072403902][Arash Badakhsh]], [[https://openalex.org/A5083337587][Sun Hee Choi]], Energies. 17(2)] 2024. https://doi.org/10.3390/en17020441  ([[https://www.mdpi.com/1996-1073/17/2/441/pdf?version=1705409050][pdf]])
     
The application of protonic ceramic electrolysis cells (PCECs) for ammonia (NH3) synthesis has been evaluated over the past 14 years. While nitrogen (N2) is the conventional fuel on the cathode side, various fuels such as methane (CH4), hydrogen (H2), and steam (H2O) have been investigated for the oxygen evolution reaction (OER) on the anode side. Because H2 is predominantly produced through CO2-emitting methane reforming, H2O has been the conventional carbon-free option thus far. Although the potential of utilizing H2O and N2 as fuels is considerable, studies exploring this specific combination remain limited. PCEC fabrication technologies are being developed extensively, thus necessitating a comprehensive review. Several strategies for electrode fabrication, deposition, and electrolyte design are discussed herein. The progress in electrode development for PCECs has also been delineated. Finally, the existing challenges and prospective outlook of PCEC for NH3 synthesis are analyzed and discussed. The most significant finding is the lack of past research involving PCEC with H2O and N2 as fuel configurations and the diversity of nitrogen reduction reaction catalysts. This review indicates that the maximum NH3 synthesis rate is 14 × 10−9 mol cm−2 s−1, and the maximum current density for the OER catalyst is 1.241 A cm−2. Moreover, the pellet electrolyte thickness must be maintained at approximately 0.8–1.5 mm, and the stability of thin-film electrolytes must be improved.    

    

** Oxygen Vacancy Optimization of the Titanium Carbide Mxene Surface for Enhanced Electrochemical Nitrogen Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4696673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390910683"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390910683"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390910683"))][Get cited by]]

OpenAlex: https://openalex.org/W4390910683 (Open access: False)
    
[[https://openalex.org/A5057936702][Leiming Tao]], [[https://openalex.org/A5050145382][Zhenghong Guo]], [[https://openalex.org/A5090251912][Kui Pang]], [[https://openalex.org/A5057489654][Zhi Zhang]], [[https://openalex.org/A5013038112][Chen Wang]], [[https://openalex.org/A5034904172][Liming Huang]], [[https://openalex.org/A5079944667][Guanhua Zhu]], [[https://openalex.org/A5031173998][Linhai Duan]], [[https://openalex.org/A5045985930][Jianjun Yang]], [[https://openalex.org/A5044283271][Xiquan Fu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4696673 
     
Electrochemical N2 reduction reaction (NRR) provides a hopeful way for sustainable NH3 production. It is the key to realize efficient NRR reaction to optimize the structure and electronic configuration of catalyst materials. Increasing the number of active centers in Ti3C2Tx MXene allows for the development of effective NRR electrocatalysts. Herein, we rationally integrated defect engineering to create oxygen vacancy-rich Ti3C2-Mxene (K-Ti3C2-400) as an efficient NRR catalyst with an NH3 yield of 32.25± 0.8 μg·h-1·mg-1cat. at −0.55 V and a Faradaic efficiency of 12.85% ± 0.26% at −0.45 V versus reversible hydrogen electrode. According to the density functional theory, oxygen vacancies can prevent the hydrogen evolution reaction by delaying H adsorption, thereby activating absorbed N2 and encouraging *N2H synthesis. This research opens up new possibilities for creating MXene-based catalysts with surface reactivity and selectivity for electrochemical N2 fixation.    

    

** Interatomic interaction of 2D crumpled V2O5 nanosheets layered with Ni-MOF as a bifunctional electrocatalyst for overall water splitting and supercapacitor applications   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2023.110348")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390911953"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390911953"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390911953"))][Get cited by]]

OpenAlex: https://openalex.org/W4390911953 (Open access: False)
    
[[https://openalex.org/A5041446513][Muhammad Kashif]], [[https://openalex.org/A5051943320][Sadhasivam Thangarasu]], [[https://openalex.org/A5001779926][N. Murugan]], [[https://openalex.org/A5061257936][Sahil S. Magdum]], [[https://openalex.org/A5005760245][Yoong Ahm Kim]], [[https://openalex.org/A5016350367][Mahaveer D. Kurkuri]], [[https://openalex.org/A5029047892][Tae Hwan Oh]], Journal of Energy Storage. 81(None)] 2024. https://doi.org/10.1016/j.est.2023.110348 
     
Herein, we have synthesized a highly efficient and economical noble metal-free catalyst via a novel combination of V2O5 nanosheets and Ni MOF. The critical points of this study are (i) achieving a 2D layer structured crumpled V2O5 nanosheets without excessive stacking/aggregation using freeze drying method, (ii) decorating Ni-MOF over the crumpled V2O5 nanosheets to attain an excellent homogeneity and (iii) developing a V2O5 based novel and bifunctional electrocatalyst for overall water splitting and supercapacitor applications. Forming a well-interlinked morphological structure accompanies a homogeneous dispersion of Ni MOF over the V2O5 nanosheet. Among the multiple compositions, the NiV4 exhibited superior electrocatalytic oxygen evolution reaction (OER) and hydrogen evolution reaction (HER) performances with an overpotential (η30) of 336 mV and 108 mV, respectively. NiV4 also displayed remarkable stability as confirmed by chronopotentiometry (24 h) and CV (after 5000 cycles). The excellent OER performance is possible due to the interatomic interaction and the heterojunction formation between V2O5 nanosheets and Ni MOF, resulting in the preferential adsorption of ⁎OOH reaction intermediates to Ni active sites. During HER, the interfacial interaction between V2O5 nanosheets and Ni MOF allowed the OH− to adsorb on the V5+ center. Furthermore, the Ni active sites simultaneously accelerated the Volmer step by promoting the H adsorption. The uniform mass transfer routes aid in fast charge transfer, resulting in excellent OER and HER performances. Interestingly, in the 2-electrode system, the NiV4 exhibited an overpotential of 1.81 V at 10 mA cm−2 and excellent durability over 15 h. For supercapacitor applications, the NiV4 exhibits efficient specific capacitance (546 Fg−1 at 1Ag−1). Furthermore, the NiV4 electrode provides significant long-term stability during the supercapacitor application, with the stability being consistent after 10,000 cycles. The NiV4 offers excellent water splitting and supercapacitor performance due to its multifunctional properties and remarkable structural integrity.    

    

** Composition‐Dependent NiS‐Enriched FeNi2S4/ZnCr2O4 Catalyst for Electrochemical Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/slct.202302556")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390914377"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390914377"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390914377"))][Get cited by]]

OpenAlex: https://openalex.org/W4390914377 (Open access: False)
    
[[https://openalex.org/A5015741945][N. Jabena Begum]], [[https://openalex.org/A5022351799][Rathindranath Biswas]], [[https://openalex.org/A5009077939][Ayan Roy]], [[https://openalex.org/A5042201959][Imtiaz Ahmed]], [[https://openalex.org/A5080457147][Pooja Thakur]], [[https://openalex.org/A5022029107][Krishna Kanta Haldar]], ChemistrySelect. 9(3)] 2024. https://doi.org/10.1002/slct.202302556 
     
Abstract Transition metal sulfide and oxide nanomaterials are gaining popularity as catalysts for electrochemical water splitting because of their cost effectiveness, durability, and stability without using noble metals. Our study focuses on a hybrid electrocatalyst, NiS‐enriched FeNi 2 S 4 /ZnCr 2 O 4 , which is synthesized in two steps by sol‐gel followed through thermal decomposition in an aqueous solution by a hydrothermal process. We investigated its potential application in the electrochemical oxygen evolution reaction (OER). Powder X‐ray diffraction and X‐ray photoelectron spectroscopy analyses were used to determine the chemical composition and structure. The results showed that the FeNi 2 S 4 structure has an enriched NiS phase. Additionally, the morphology of the synthesized FeNi 2 S 4 /ZnCr 2 O 4 was revealed by field emission scanning electron microscopy (FE‐SEM). Under alkaline (1 M KOH) conditions, the FeNi 2 S 4 /ZnCr 2 O 4 hybrid nanostructure showed a low overpotential value of 295 mV (Tafel slope, 59 mV dec −1 ) for OER activities due to the synergistic effects of FeNi 2 S 4 and ZnCr 2 O 4 . Furthermore, the hybrid nanostructure demonstrated its long‐term stability and efficiency as an electrocatalyst for OER activities, surpassing previously reported superior electrocatalysts and state‐of‐the‐art materials.    

    

** From Small‐Area Observations to Insight: Surface‐Feature‐Extrapolation of Anodes for Alkaline Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301461")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390916005"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390916005"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390916005"))][Get cited by]]

OpenAlex: https://openalex.org/W4390916005 (Open access: False)
    
[[https://openalex.org/A5016774685][Arvind Kumar Jain]], [[https://openalex.org/A5025930612][Vineetha Vinayakumar]], [[https://openalex.org/A5004899785][André Olean‐Oliveira]], [[https://openalex.org/A5006249717][Christian Marcks]], [[https://openalex.org/A5052683041][Mohit Chatwani]], [[https://openalex.org/A5057402984][Anna K. Mechler]], [[https://openalex.org/A5082583063][Corina Andronescu]], [[https://openalex.org/A5062824606][Doris Segets]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301461 
     
In this study, we developed a statistical framework, named multistage data quantification (MSDQ), to evaluate representative surface characteristics such as surface roughness, surface area, and homogeneity score of cobalt oxide‐based anodes, and contributing to a deeper insight into quality of anode surface. Atomic force microscopy (AFM) was employed to capture the surface morphology of two anodes that have a comparable loading of cobalt oxide but exhibit distinct morphological features. Application of MSDQ exposed notable disparities in surface characteristics across these anodes, underlining the critical importance of MSDQ in precise surface characterization. Specifically, surface roughness, surface area and homogeneity score effectively elucidated the disparities in electrocatalytic activity for the oxygen evolution reaction (OER), as quantified through scanning droplet cell (SDC) measurements. By conducting a systematic comparative analysis, the respective contributions of the extrinsic surface characteristics of the anodes to the intrinsic electrocatalytic material property could be differentiated and quantified. Applications of our findings range from benchmarking of anodes to optimization of anode manufacturing processes.    

    

** Advancing oxygen evolution electrocatalysis with human-machine intelligence   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.checat.2023.100868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391043168"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391043168"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391043168"))][Get cited by]]

OpenAlex: https://openalex.org/W4391043168 (Open access: True)
    
[[https://openalex.org/A5083865054][Liping Liu]], [[https://openalex.org/A5047424183][Siwen Wang]], [[https://openalex.org/A5013986686][Chen Ling]], [[https://openalex.org/A5040429065][Hongliang Xin]], Chem Catalysis. 4(1)] 2024. https://doi.org/10.1016/j.checat.2023.100868 
     
In this article, Hongliang Xin (associate professor at Virginia Tech), Chen Ling (senior principal research scientist at Toyota), and their colleagues discuss the critical challenges in developing high-performance electrocatalysts for the oxygen evolution reaction (OER), particularly by emphasizing the role of artificial intelligence (AI) in materials exploration and discovery. They highlight the necessity of a collaborative human-machine intelligence approach to overcome the complexities of OER catalysis and accelerate the advancement of sustainable energy solutions.    

    

** Insights on MOF-derived metal–carbon nanostructures for oxygen evolution   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3dt04263d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391225155"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391225155"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391225155"))][Get cited by]]

OpenAlex: https://openalex.org/W4391225155 (Open access: False)
    
[[https://openalex.org/A5084914364][Junliang Chen]], [[https://openalex.org/A5054473752][Jinjie Qian]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d3dt04263d 
     
This article focuses on elucidating the fabrication and design of metal-organic framework derived metal-carbon nanostructures for oxygen evolution. It is categorized into three following topics: MOF selection, metal introduction and carbon structure.    

    

** Surface reconstruction of La0.6Sr0.4Co0.8Ni0.2O3- perovskite nanofibers for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.01.211")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390942237"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390942237"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390942237"))][Get cited by]]

OpenAlex: https://openalex.org/W4390942237 (Open access: False)
    
[[https://openalex.org/A5087438347][Yusong Niu]], [[https://openalex.org/A5014609476][Xin Chang]], [[https://openalex.org/A5052582378][Mingyi Zhang]], [[https://openalex.org/A5031140913][Jingbo Mu]], Ceramics International. None(None)] 2024. https://doi.org/10.1016/j.ceramint.2024.01.211 
     
Perovskites have become promising alternatives to precious metal-catalyzed oxygen evolution reaction (OER). Herein, we report the synthesis of several perovskite nanofibers, specifically La0.6Sr0.4CoxNi1-xO3-δ (LSCN), and investigate their electrocatalytic water oxidation activity in alkaline electrolytes. La0.6Sr0.4Co0.8Ni0.2O3-δ (LSCN-0.8) is selected and immersed in an aqueous NaBH4 solution for 1 h for surface reconstruction. The perovskite nanofibers' electrocatalytic OER activity and stability are rigorously evaluated using a standard three-electrode system. Results reveal that even a slight Co substitution for Ni content within the LSCN perovskite structure has a notable impact on electrocatalytic activity. Moreover, LSCN-0.8 exhibits an overpotential of 363 mV at 20 mA cm−2 in 1 M KOH. However, significant improvement is observed after the surface reconstruction process. The optimized LSCN-0.8 (now called LSCN-2) displays the lowest OER overpotential (320 mV) under the same conditions. Furthermore, the LSCN-2 nanostructure demonstrates exceptional electrode stability, as evidenced by only a slight decrease in electrocatalytic performance during 5000 cycles of linear sweep voltammetry.    

    

** Enhanced catalytic activity of ZnWO4 by nickel-doping in oxygen evolution reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mssp.2024.108151")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391197664"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391197664"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391197664"))][Get cited by]]

OpenAlex: https://openalex.org/W4391197664 (Open access: False)
    
[[https://openalex.org/A5087592842][Meng Li]], [[https://openalex.org/A5086054627][Deijun Xiong]], [[https://openalex.org/A5036224962][Jinxing Wang]], [[https://openalex.org/A5082373186][Xiaoyang Dong]], [[https://openalex.org/A5069325690][Peiyang Zhang]], Materials Science in Semiconductor Processing. 173(None)] 2024. https://doi.org/10.1016/j.mssp.2024.108151 
     
The development of efficient and low-cost metal materials is indispensable in clean energy technology. Metal tungstates have previously been reported as catalysts for oxygen evolution reactions (OER). However, ZnWO4 alone does not exhibit significant catalytic activity for OER, it requires 330 mV to drive the reaction at 10 mA cm−2. To address this issue, a self-supporting electrode mixed with tungstate is synthesized by a hydrothermal method. Notably, the Ni-doped ZnWO4 self-supporting material demonstrates improved OER catalytic activity. Specifically, when comparing ZnWO4 to ZnNiWO4, it exhibits a reduced Tafel slope by 190 mV·dec−1, resulting in an overpotential of only 110 mV at 10 mA cm−2, with long-term stability for at least 20 h. Furthermore, the d-band center of ZnNiWO4 is modeled using Materials Studio and simulated through projected density of states (PDOS) calculations. These calculations reveal that the presence of Ni activates the metal ion as an OER active site with strong orbital overlap with the reaction intermediate. This adjustment in the electronic structure of the Ni–Zn metal active site during the oxygen evolution reaction alters the adsorption energy. Consequently, doping of Ni enhances the metal's ability to adsorb *OOH radical, shifting the d-band center of ZnNiWO4 further away from the Fermi level, and facilitates rapid oxygen release.    

    

** Dynamic Promotion of the Oxygen Evolution Reaction via Programmable Metal Oxides   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-gs6zn")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391172933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391172933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391172933"))][Get cited by]]

OpenAlex: https://openalex.org/W4391172933 (Open access: True)
    
[[https://openalex.org/A5030610409][Sallye R. Gathmann]], [[https://openalex.org/A5065773454][Christopher J. Bartel]], [[https://openalex.org/A5029991019][Lars C. Grabow]], [[https://openalex.org/A5089122189][Omar Abdel‐Rahman]], [[https://openalex.org/A5071975512][C. Daniel Frisbie]], [[https://openalex.org/A5003718847][Paul J. Dauenhauer]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-gs6zn  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65af381d66c13817290d5404/original/dynamic-promotion-of-the-oxygen-evolution-reaction-via-programmable-metal-oxides.pdf][pdf]])
     
Hydrogen gas is a promising renewable energy storage medium when produced via water electrolysis, but this process is limited by the sluggish kinetics of the anodic oxygen evolution reaction (OER). Herein, we used a microkinetic model to investigate promoting the OER using programmable oxide catalysts (i.e., forced catalyst dynamics). We found that programmable catalysts could increase current density at a fixed overpotential (100X to 600X over static rates) or reduce the overpotential required to reach a fixed current density of 10 mA/cm^2 (45 – 140% reduction vs. static). In our kinetic parameterization, the key parameters controlling the quality of the catalytic ratchet were the O*-to-OOH* and O*-to-OH* activation barriers. Our findings indicate that programmable catalysts may be a viable strategy for accelerating the OER or enabling lower-overpotential operation, but a more accurate kinetic parameterization is required for precise predictions of performance, ratchet quality, and resulting energy efficiency.    

    

** Material Dynamics of Manganese-Based Oxychlorides for Oxygen Evolution Reaction in Acid   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.chemmater.3c02362")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390918522"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390918522"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390918522"))][Get cited by]]

OpenAlex: https://openalex.org/W4390918522 (Open access: False)
    
[[https://openalex.org/A5014692849][Ruihan Li]], [[https://openalex.org/A5015462149][Dennis Nordlund]], [[https://openalex.org/A5037183181][Linsey C. Seitz]], Chemistry of Materials. None(None)] 2024. https://doi.org/10.1021/acs.chemmater.3c02362 
     
Earth-abundant manganese-based oxides have emerged as promising alternatives to noble-metal-based catalysts for the oxygen evolution reaction (OER) in acidic conditions; however, their inferior activity and stability present critical challenges for the sustainable production of hydrogen via water electrolysis. Moving beyond oxides, heteroanionic materials, which incorporate anions with lower electronegativity than oxygen, have shown potential for improving the OER performance, but a detailed understanding of the underlying mechanisms is lacking. Here, we investigate manganese-based oxychlorides (Mn8O10Cl3 and FeMn7O10Cl3) that exhibit excellent activity and stability for acidic OER to elucidate material property dynamics and correlate them with OER behaviors. Our rigorous electrochemical stability testing reveals that the high operating potential mitigates Mn dissolution over prolonged exposure to the OER conditions. Through a combination of ex situ and in situ surface and bulk-sensitive X-ray spectroscopy analyses, we observe a trade-off between increasing Mn valence and maintaining structural integrity, which results in dynamic bond length changes within the [MnCl6] octahedra during the activation and degradation processes of these oxychloride catalysts. This study provides insights into the fundamental relationships between the chemical, electronic, and geometric properties of the catalysts and their electrocatalytic outcomes.    

    

** Fabrication of hexagonal Cu2O nanocrystals on CNTs for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpcs.2023.111853")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391179968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391179968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391179968"))][Get cited by]]

OpenAlex: https://openalex.org/W4391179968 (Open access: False)
    
[[https://openalex.org/A5083753418][Salma Aman]], [[https://openalex.org/A5018207831][Meznah M. Alanazi]], [[https://openalex.org/A5008098859][Shaimaa A. M. Abdelmohsen]], [[https://openalex.org/A5088716481][Saeed D. Alahmari]], [[https://openalex.org/A5078102681][Abdullah G. Al‐Sehemi]], [[https://openalex.org/A5014861084][Muhammad Suleman Waheed]], [[https://openalex.org/A5051797797][A.M.A. Henaish]], [[https://openalex.org/A5084172156][Zubair Ahmad]], [[https://openalex.org/A5001974005][Hafiz Muhammad Tahir Farid]], Journal of Physics and Chemistry of Solids. None(None)] 2024. https://doi.org/10.1016/j.jpcs.2023.111853 
     
Electrocatalytic water (H2O) splitting relies heavily on the rational formation of most effective, long-lasting catalysts that should be cheaper and earth abundant. Therefore, an effective electrocatalyst is the need of the hour that may effectively pursue both electrocatalytic OER and HER. This study paves the way for the straightforward preparation of conductive polymer tailored metal oxide nanocomposite Cu2O/CNTs by a facile hydrothermal approach to be employed as overall water splitting electrocatalyst. The techniques comprising SEM, XRD, EDX and the BET test were employed to characterize the synthesized Cu2O/CNTs electrocatalyst. The generated Cu2O/CNTs electrocatalysts exhibited a Tafel value of 39 mV/dec, an overpotential of 267 mV@10 mA/cm2, and stability of OER activity that lasted for at least 70 hours. The electrocatalytic results show that the combination of Cu2O and CNTs has a synergistic impact to reduce the overpotential value. In an effort to pinpoint the rate determining processes for OER, the voltage of OER is connected to the electrolyte pH and exhibits a non-proton concerted approach. The above designed nanocomposite is quite promising for modern hydrogen production systems due to their quick electron transfer mechanism, remarkable durability, and good activity for OER.    

    

** Spinel-type high-entropy oxide nanotubes for efficient oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.colsurfa.2024.133315")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391177777"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391177777"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391177777"))][Get cited by]]

OpenAlex: https://openalex.org/W4391177777 (Open access: False)
    
[[https://openalex.org/A5046042839][Yanbin Zhu]], [[https://openalex.org/A5070686219][Qing Xiang]], [[https://openalex.org/A5050156870][Guo Le]], [[https://openalex.org/A5060213367][Shuanglong Lu]], [[https://openalex.org/A5067758457][Fang Duan]], [[https://openalex.org/A5036927789][Mingliang Du]], [[https://openalex.org/A5014327956][Han Zhu]], Colloids and Surfaces A: Physicochemical and Engineering Aspects. None(None)] 2024. https://doi.org/10.1016/j.colsurfa.2024.133315 
     
Oxygen evolution reaction (OER) involved 4-electron transfers is generally considered as the bottleneck for electrocatalytic water splitting. High-entropy oxides (HEO) show promising potential for OER due to their flexible structures and tunable compositions. Herein, we report a facile strategy to synthesize spinel-type (FeCoNiMnCr)3O4 HEO nanotubes (NTs) with unique hollow structures by combining electrospinning process and calcination treatment. The (FeCoNiMnCr)3O4 HEO NTs prepared at 400 °C exhibit the low overpotential of 353 mV at 50 mA cm-2 and small Tafel slope of 55.6 mV dec-1 in 1 M KOH electrolyte. The three-dimensional (3D) nanofiber-based architecture ensure the superior stability, as evidenced by the stable current density under continuous OER process for more than 60 h. Meanwhile, the hollow structure provides abundant exposed active sites, which could significantly improve the OER activity. This work provides new design of low-cost and high-efficient HEO with ensemble active sites for OER.    

    

** Strategic Design and Insights into Lanthanum and Strontium Perovskite Oxides for Oxygen Reduction and Oxygen Evolution Reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202308443")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391142464"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391142464"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391142464"))][Get cited by]]

OpenAlex: https://openalex.org/W4391142464 (Open access: False)
    
[[https://openalex.org/A5050236680][Sagar Ingavale]], [[https://openalex.org/A5036345289][Mohan Gopalakrishnan]], [[https://openalex.org/A5092896607][Carolin Mercy Enoch]], [[https://openalex.org/A5067676218][Chanon Pornrungroj]], [[https://openalex.org/A5000448228][Meena Rittiruam]], [[https://openalex.org/A5036226683][Supareak Praserthdam]], [[https://openalex.org/A5007823738][Anongnat Somwangthanaroj]], [[https://openalex.org/A5093770957][Kasadit Nootong]], [[https://openalex.org/A5074004594][Rojana Pornprasertsuk]], [[https://openalex.org/A5081163390][Soorathep Kheawhom]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202308443 
     
Abstract Perovskite oxides exhibit bifunctional activity for both oxygen reduction (ORR) and oxygen evolution reactions (OER), making them prime candidates for energy conversion in applications like fuel cells and metal‐air batteries. Their intrinsic catalytic prowess, combined with low‐cost, abundance, and diversity, positions them as compelling alternatives to noble metal and metal oxides catalysts. This review encapsulates the nuances of perovskite oxide structures and synthesis techniques, providing insight into pivotal active sites that underscore their bifunctional behavior. The focus centers on the breakthroughs surrounding lanthanum (La) and strontium (Sr)‐based perovskite oxides, specifically their roles in zinc‐air batteries (ZABs). An introduction to the mechanisms of ORR and OER is provided. Moreover, the light is shed on strategies and determinants central to optimizing the bifunctional performance of La and Sr‐based perovskite oxides.    

    

** Carbon nanotubes immobilized copper(salen) nanocomposite for electrochemical oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.56042/ijc.v63i1.2312")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391174987"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391174987"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391174987"))][Get cited by]]

OpenAlex: https://openalex.org/W4391174987 (Open access: True)
    
, Indian Journal of Chemistry. 63(1)] 2024. https://doi.org/10.56042/ijc.v63i1.2312  ([[https://or.niscpr.res.in/index.php/IJC/article/download/2312/2438][pdf]])
     
An efficient oxygen evolution reaction (OER) electrocatalysts are widely required in the realm of water electrolysis and rechargeable metal-air batteries. This work describes an easy and simple method for the synthesis of copper salen (Cu(Salen))-functionalized multiwalled carbon nanotubes (MWCNTs) nanocomposite materials (Cu(Salen)/MWCNTs). It was used for OER in the basic medium (0.1 M KOH). The resulting nanocomposite, Cu(Salen)/MWCNTs, was studied using spectroscopic and microscopic techniques. For example, Fourier transform infrared (FT-IR), UV-visible spectroscopy, powder X-ray diffraction (p-XRD), scanning electron microscopy (SEM), and energy dispersive X-ray analysis (EDAX). The electrochemical characterization of prepared Cu(Salen)/MWCNTs nanocomposite based modified glassy carbon (GC) electrodes (GC/Cu(Salen)/MWCNTs) and their application towards OER were performed using an electrochemical method. The Tafel slope of nanocomposite material is 159.6 mv/dec in 0.1 M KOH solution, indicating that GC/Cu(Salen)/MWCNTs could be a promising and cost-effective electrode material for the OER. This study demonstrates a novel way for creating an active nanocomposite catalyst for OER in alkaline media.    

    

** NiCo2O4/MXene hybrid as an efficient bifunctional electrocatalyst for oxygen evolution and reduction reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301250")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391296391"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391296391"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391296391"))][Get cited by]]

OpenAlex: https://openalex.org/W4391296391 (Open access: False)
    
[[https://openalex.org/A5016038695][Ashalatha Vazhayil]], [[https://openalex.org/A5015987837][Vazhayal Linsha]], [[https://openalex.org/A5086819981][Shyamli Ashok C]], [[https://openalex.org/A5087024992][Jasmine Thomas]], [[https://openalex.org/A5053127989][Nygil Thomas]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301250 
     
For the advancement of energy conversion and storage technologies, bifunctional electrocatalysts are crucial for efficiently driving both the oxygen evolution (OER) and reduction reactions (ORR). Cobalt‐based spinel oxides are a class of promising bifunctional electrocatalysts. However their low electrical conductivity and stability may hinder further improvement. A novel composite material composed of NiCo2O4(NCO) nanoparticles integrated with emerging two dimensional MXene nanosheets (NCO/MXene) was developed. The successful integration of NCO with MXene brings about a number of attractive structural features. This includes synergistic effects between NCO and MXene, highly accessible surface areas, complete exposure of numerous active sites, and excellent electronic conductivity, all of which collectively contribute to the desirability of composite material for OER and ORR. The synthesized NCO/MXene composite showed extraordinary OER electrocatalytic activity with a lower overpotential of 360 mV at a current density of 10 mA/cm2, and a small Tafel slope of 64.63 mV/dec compared to NCO, MXene and NCO+MXene (physically mixed). Additionally, it displays a superior ORR limiting current density (‐4 mA/cm2). In particular, it exhibited highest onset potential and half wave potential of 0.92 V and 0.72 V vs. RHE, respectively, for the ORR in alkaline media    

    

** Copper oxide nanofibers obtained by solution blow spinning as catalysts for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.01.213")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390965940"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390965940"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390965940"))][Get cited by]]

OpenAlex: https://openalex.org/W4390965940 (Open access: False)
    
[[https://openalex.org/A5012056564][Alessandra Patrícia de Araújo Dantas]], [[https://openalex.org/A5001528670][Rafael A. Raimundo]], [[https://openalex.org/A5011364392][Pedro de Lima Neto]], [[https://openalex.org/A5013176757][Caio M. S. Lopes]], [[https://openalex.org/A5075400591][Jakeline R.D. Santos]], [[https://openalex.org/A5090398034][Francisco J.A. Loureiro]], [[https://openalex.org/A5029685103][Tatiany Barata Pereira]], [[https://openalex.org/A5088882865][Marco A. Morales]], [[https://openalex.org/A5061360133][Eliton S. Medeiros]], [[https://openalex.org/A5069774051][Daniel A. Macedo]], Ceramics International. None(None)] 2024. https://doi.org/10.1016/j.ceramint.2024.01.213 
     
In this work, we report copper oxide nanofibers (CuO – N) synthesized by Solution Blow Spinning (SBS) for oxygen evolution reaction (OER), and their comparison with a control sample based on a commercial powder (CuO – C). Both materials were characterized by various techniques, including X-ray diffraction (XRD), magnetometry, scanning electron microscopy (SEM), and spectroscopy (Fourier transform infrared (FT-IR), Raman and X-ray photoelectron (XPS)) to confirm the purity, and microstructural and surface chemical properties. Subsequently, the performance of copper oxide catalysts in a 1.0 M KOH solution was investigated. Copper oxide with nanofiber morphology (CuO – N) exhibited a small overpotential of 385 mV @ 10 mA cm−2 and a Tafel coefficient of only 76 mV dec−1, i.e., fast kinetics for water splitting, a result that is modulated by oxygen vacancies (O2/O1 = 0.83). The oxygen vacancies are due to the presence of Cu1+ in the lattice. The analyses of the magnetization measurements at 5 K suggest a larger amount of Cu1+ in sample CuO – N. Therefore, this work sheds light on how to design low-cost nanofibrous catalysts based on abundant transition metals in the earth's crust by SBS, an economical and scalable technique, which is promising for energy applications.    

    

** Constructing highly efficient bifunctional catalysts for oxygen reduction and oxygen evolution by modifying MXene with transition metal   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.089")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391063505"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391063505"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391063505"))][Get cited by]]

OpenAlex: https://openalex.org/W4391063505 (Open access: False)
    
[[https://openalex.org/A5061630253][Dai Yu]], [[https://openalex.org/A5047850201][Xiuyun Zhao]], [[https://openalex.org/A5016833284][Desheng Zheng]], [[https://openalex.org/A5059700536][Qingrui Zhao]], [[https://openalex.org/A5082664273][Jing Feng]], [[https://openalex.org/A5019670440][Yingjie Feng]], [[https://openalex.org/A5063446819][Xingbo Ge]], [[https://openalex.org/A5024977426][Xin Chen]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.089 
     
Exploring highly active electrocatalysts for oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) has become a growing interest in recent years. Herein, an efficient pathway for designing MXene-based ORR/OER catalysts is proposed. It involves introducing non-noble metals into Vo (vacancy site), H1 and H2 (the hollow sites on top of C and the metal atom, respectively) sites on M2CO2 surfaces, named TM-VO/H1/H2-M2CO2 (TM = Fe, Co, Ni, M = V, Nb, Ta). Among these recombination catalysts, Co-H1-V2CO2 and Ni-H1-V2CO2 exhibit the most promising ORR catalytic activities, with low overpotential values of 0.35 and 0.37 V, respectively. Similarly, Fe-H1-V2CO2, Co-VO-Nb2CO2, and Ni-H2-Nb2CO2 possess low OER overpotential values of 0.29, 0.39, and 0.44 V, respectively, suggesting they have enormous potential as effective catalysts for OER. Notably, Co-H2-Ta2CO2 possesses the lowest potential gap value of 0.53 V, demonstrating it has an extraordinary bifunctional catalytic activity. The excellent catalytic performance of these recombination catalysts can be elucidated through an electronic structure analysis, which primarily relies on the electron-donating capacity and synergistic effects between transition metals and sub-metals. These results provide theoretical guidance for designing new ORR and OER catalysts using 2D MXene materials.    

    

** Exploring the role of iron in Fe5Ni4S8 toward oxygen evolution through modulation of electronic orbital occupancy   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.01.028")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391152145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391152145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391152145"))][Get cited by]]

OpenAlex: https://openalex.org/W4391152145 (Open access: False)
    
[[https://openalex.org/A5070671117][Zhengyan Du]], [[https://openalex.org/A5069619264][Zeshuo Meng]], [[https://openalex.org/A5035280619][H. Sun]], [[https://openalex.org/A5085794085][Yifan Li]], [[https://openalex.org/A5018421780][Chao Jiang]], [[https://openalex.org/A5037742951][Yaxin Li]], [[https://openalex.org/A5016312685][Xiaoying Hu]], [[https://openalex.org/A5063995082][Yi Cui]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5037428389][Hongwei Tian]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.01.028 
     
Ni-Fe-based catalysts are considered to be among the most active catalysts for the oxygen evolution reaction (OER) under alkaline conditions, with Fe playing a crucial role. However, Fe leaching occurs during the reaction due to thermodynamic instability, which has resulted in conflicting reports within the literature regarding its role. To clarify this point, we propose a strategy consisting of modulating the electronic orbital occupancy to suppress the extensive loss of Fe atoms during the OER process. Theoretical calculations, in-situ X-ray photoelectron spectroscopy, molecular dynamics simulations, and a series of characterization showed that the stable presence of Fe not only accelerates the electron transfer process but also optimizes the reaction barriers of the oxygen evolution intermediates, promoting the phase transition of Fe5Ni4S8 to highly active catalytic species. The modulated Fe5Ni4S8-based pre-catalysts exhibit improved OER activity and long-term durability. This study provides a novel perspective for understanding the role of Fe in the OER process.    

    

** Efficient Oxygen Evolution Reaction by Ru(II) Polypyridyl Complex based AIEgen   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3qi02380j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987133"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987133"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987133"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987133 (Open access: False)
    
[[https://openalex.org/A5071842308][Snehadrinarayan Khatua]], [[https://openalex.org/A5058986428][Monosh Rabha]], [[https://openalex.org/A5047379472][Sreenivasan Nagappan]], [[https://openalex.org/A5029602773][Bhaskar Sen]], [[https://openalex.org/A5031222788][Khanindram Baruah]], [[https://openalex.org/A5067628877][Subrata Kundu]], No host. None(None)] 2024. https://doi.org/10.1039/d3qi02380j 
     
Ruthenium polypyridyl complexes are known for their excellent photophysical properties and rich electrochemical behavior. Thus, developing complexes with multifunctional behavior showing potential applications in multiple fields is of great importance....    

    

** Efficient oxygen evolution using conductive cobalt-based metal-organic framework   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131044")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391143814"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391143814"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391143814"))][Get cited by]]

OpenAlex: https://openalex.org/W4391143814 (Open access: False)
    
[[https://openalex.org/A5061145215][Munzir H. Suliman]], [[https://openalex.org/A5025288698][Lolwah Tawfiq Alfuhaid]], [[https://openalex.org/A5042532738][Mohd Yusuf Khan]], [[https://openalex.org/A5090138718][Muhammad Usman]], [[https://openalex.org/A5088210851][Aasif Helal]], Fuel. 363(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131044 
     
No abstract    

    

** Laser assisted oxygen vacancy engineering on Fe doped CoO nanoparticles for oxygen evolution at large current density   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.143841")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391037653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391037653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391037653"))][Get cited by]]

OpenAlex: https://openalex.org/W4391037653 (Open access: False)
    
[[https://openalex.org/A5005245760][Min Zhu]], [[https://openalex.org/A5072946813][Zong‐Qiang Sheng]], [[https://openalex.org/A5019261932][Zhifen Fu]], [[https://openalex.org/A5075847376][Yang Li]], [[https://openalex.org/A5001017073][Juan Gao]], [[https://openalex.org/A5089966579][Chao Zhang]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.143841 
     
Exploring cost-effective non-noble metal-based catalysts with high activity and stability is of great significance for energy conversion and storage involving oxygen evolution reaction (OER). Here, we employed a laser irradiation technique to synthesis Fe doped CoO nanoparticles with ultrafine size (≈ 5.4 nm) and abundant oxygen vacancies (Fe-Ov-CoO). The ultrafine size of Fe-Ov-CoO nanoparticles provides more active sites to be exposed. Fe doping and oxygen vacancy promote the intrinsic activity and electron transfer rates of Fe-Ov-CoO, giving rise to high activity and stability catalyst for OER. Fe-Ov-CoO delivers a large current density of 1000 mA cm−2 at an overpotential of 548 mV, which is much better than commercial RuO2. Moreover, Fe-Ov-CoO presents a remarkable long-term stability with negligible degeneration at a high current density of 500 mA cm−2 for 120 h. This work provides a new route to develop OER electrocatalyst with high activity and stability.    

    

** Three-dimensional ordered macroporous design of heterogeneous cobalt-iron phosphides as oxygen evolution electrocatalyst   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6528/ad21a5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391127015"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391127015"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391127015"))][Get cited by]]

OpenAlex: https://openalex.org/W4391127015 (Open access: False)
    
[[https://openalex.org/A5010184929][Suqing Zhao]], [[https://openalex.org/A5057639371][Weijin Cao]], [[https://openalex.org/A5030429211][Lu Lu]], [[https://openalex.org/A5084750748][Zhaoyang Tan]], [[https://openalex.org/A5007948614][Yanji Wang]], [[https://openalex.org/A5045477027][Lanlan Wu]], [[https://openalex.org/A5083687798][Jingde Li]], Nanotechnology. None(None)] 2024. https://doi.org/10.1088/1361-6528/ad21a5 
     
Abstract Oxygen evolution reaction (OER) plays a key role in electrochemical conversion, which needs efficient and economical electrocatalyst to boost its kinetics for large-scale application. Herein, a bimetallic CoP/FeP2 heterostructure with a three-dimensional ordered macroporous structure (3DOM-CoP/FeP2) was synthesized as an OER catalyst to demonstrate a heterogeneous engineering induction strategy. By adjusting the electron distribution and producing a lot of active sites, the heterogeneous interface enhances catalytic performance. High specific surface area is provided by the 3DOM structure. Additionally, at the solid-gas-electrolyte threephase interface, the electrocatalytic reaction exhibits good mass transfer. In-situ Raman spectroscopy characterization revealed that FeOOH and CoOOH reconstructed from CoP/FeP2 were the true OER active sites. Consequently, the 3DOM-CoP/FeP2 demonstrates superior OER activity with a low overpotentials of 300/420 mV at 10/100 mA cm–2 and meritorious OER durability. It also reveals promising performance as the overall water splitting anode.&#xD;    

    

** Origin of Anomalous Activities during Oxygen Evolution Reaction in Cubic CoNiCuFe Prussian Blue Analogue   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-bfvb8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391168303"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391168303"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391168303"))][Get cited by]]

OpenAlex: https://openalex.org/W4391168303 (Open access: True)
    
[[https://openalex.org/A5039487681][Yu Han]], [[https://openalex.org/A5038741154][Youngnam Kang]], [[https://openalex.org/A5017298534][Jie Wei]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-bfvb8  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65afb1ba9138d231618da1ab/original/origin-of-anomalous-activities-during-oxygen-evolution-reaction-in-cubic-co-ni-cu-fe-prussian-blue-analogue.pdf][pdf]])
     
Amorphous oxide catalysts typically exhibit excellent activity toward oxygen evolution reaction (OER) due to a large number of undercoordinated sites or lattice defects, but also generally suffering from low stability and difficulty in characterizing the structure. Herein, we report a well-crystallized cubic CoNiCuFe prussian blue analogue (PBA) catalyst with anomalous activities in electrocatalyzing OER when compared with its amorphized oxide. In situ Raman spectroscopy revealed a much more abundant MOOH active phase accumulated on the cubic CoNiCuFe-PBA surface than that on the amorphous CoNiCuFe-oxide surface. Further characterizations demonstrate that more high-valence metal (i.e. Co3+, Ni3+) sites are available on the cubic CoNiCuFe-PBA surface at the initial state, which is suggested to be more susceptible to redox-active surface hydroxylation and serve as the origin of active sites during OER process. The maintained cubic framework structure as well as the lower valence of Fe could contribute to considerably better stability. Such findings would open up a new door to future highly active and stable catalyst designs.    

    

** Benchmarking Stability of Iridium Oxide in Acidic Media under Oxygen Evolution Conditions: A Review: Part II   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1595/205651324x17055018154113")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987310"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987310"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987310"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987310 (Open access: True)
    
[[https://openalex.org/A5028610474][James Murawski]], [[https://openalex.org/A5004372016][Søren B. Scott]], [[https://openalex.org/A5027366818][Reshma R. Rao]], [[https://openalex.org/A5040293372][Katie Rigg]], [[https://openalex.org/A5030674093][Christopher Mark Zalitis]], [[https://openalex.org/A5015505628][James Stevens]], [[https://openalex.org/A5007586547][Jonathan Sharman]], [[https://openalex.org/A5055131883][Gareth Hinds]], [[https://openalex.org/A5039064548][Ifan E. L. Stephens]], Johnson Matthey Technology Review. None(None)] 2024. https://doi.org/10.1595/205651324x17055018154113 
     
Part I (1) introduced state-of-the-art proton exchange membrane (PEM) electrolysers with iridium-based catalysts for oxygen evolution at the anode in green hydrogen applications. Aqueous model systems and full cell testing were discussed along with proton exchange membrane water electrolyser (PEMWE) catalyst degradation mechanisms, types of iridium oxide, mechanisms of iridium dissolution and stability studies. In Part II, we highlight considerations and best practices for the investigation of activity and stability of oxygen evolution catalysts via short term testing.    

    

** Halogen-Modified Iron-Based Metal–Organic Frameworks for Remarkably Improved Electrocatalytic Oxygen Evolution   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.3c06800")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391157099"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391157099"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391157099"))][Get cited by]]

OpenAlex: https://openalex.org/W4391157099 (Open access: False)
    
[[https://openalex.org/A5088936095][Qianglong Qi]], [[https://openalex.org/A5010776860][Yue Zhang]], [[https://openalex.org/A5064403506][Chengxu Zhang]], [[https://openalex.org/A5081844561][Feng Li]], [[https://openalex.org/A5008888331][Richeng Liu]], [[https://openalex.org/A5027149538][Jue Hu]], The Journal of Physical Chemistry C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.3c06800 
     
Iron-based metal–organic frameworks (MOFs) have shown potential as catalysts for the electrocatalysis oxygen evolution reaction (OER). Despite numerous methods being employed to enhance the OER performance of MOFs, the influence of halogen-containing linkers on the electronic structure of iron-based MOF catalysts remains unexplored. In this study, a series of Fe-based MOFs (denoted as MOF-R, where R = H, Cl, or Br) with comparable structures are synthesized by changing the organic linkers coordinated with the Fe metal active center, with the aim of investigating the influence of halogen-containing linkers on the OER activity. Significantly, MOF-Br exhibited superior OER activity compared to MOF-Cl and MOF-H. Density functional theory calculations reveal that the tuning of halogen groups on organic linkers can modulate the electronic structure of the metal active sites and effectively regulate the adsorption behavior of key intermediates near the optimal d-band center, leading to the enhancement of electroactivity. Notably, the bromine-substituted MOF-Br catalyst displayed remarkable intrinsic OER activity, including a low overpotential of 251.2 mV at a current density of 10 mA cm–2 and a low Tafel slope of 44.5 mV dec–1, surpassing the halogen-unsubstituted MOF-H (262.6 mV and 63.4 mV dec–1) and commercial IrO2 (335.3 mV and 98.6 mV dec–1). Moreover, the high turnover frequency at an overpotential of 300 mV was measured to be 0.537 s–1, which is 30 times greater than that of the commercial IrO2 catalyst (0.018 s–1). This research offers a potential strategy for designing MOF electrocatalysts with superior OER activity, laying a solid foundation for the rational design and synthesis of excellent OER electrocatalysts in the future.    

    

** Data driven computational design of stable oxygen evolution catalysts by DFT and machine learning: Promising electrocatalysts   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2023.12.048")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390937419"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390937419"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390937419"))][Get cited by]]

OpenAlex: https://openalex.org/W4390937419 (Open access: False)
    
[[https://openalex.org/A5091408659][Hwanyeol Park]], [[https://openalex.org/A5016517520][Yunseok Kim]], [[https://openalex.org/A5080230233][Sang‐Hoon Choi]], [[https://openalex.org/A5084806533][Ho Jun Kim]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2023.12.048 
     
The revolutionary development of machine learning (ML), data science, and analytics, coupled with its application in material science, stands as a significant milestone of the scientific community over the last decade. Investigating active, stable, and cost-efficient catalysts is crucial for oxygen evolution reaction owing to the significance in a range of electrochemical energy conversion processes. In this work, we have demonstrated an efficient approach of high-throughput screening to find stable transition metal oxides under acid condition for high-performance oxygen evolution reaction (OER) catalysts through density functional theory (DFT) calculation and a machine learning algorithm. A methodology utilizing both the Materials Project database and DFT calculations was introduced to assess the acid stability under specific reaction conditions. Building upon this, OER catalytic activity of acid-stable materials was examined, highlighting potential OER catalysts that meet the required properties. We identified IrO2, Fe(SbO3)2, Co(SbO3)2, Ni(SbO3)2, FeSbO4, Fe(SbO3)4, MoWO6, TiSnO4, CoSbO4, and Ti(WO4)2 as promising catalysts, several of which have already been experimentally discovered for their robust OER performance, while others are novel for experimental exploration, thereby broadening the chemical scope for efficient OER electrocatalysts. Descriptors of the bond length of TM–O and the first ionization energy were used to unveil the OER activity origin. From the calculated results, guidance has been derived to effectively execute advanced high-throughput screenings for the discovery of catalysts with favorable properties. Furthermore, the intrinsic correlation between catalytic performance and various atomic and structural factors was elucidated using the ML algorithm. Through these approaches, we not only streamline the choice of the promising electrocatalysts but also offer insights for the design of varied catalyst models and the discovery of superior catalysts.    

    

** Recycling spent LiNi1-x-yCoxMnyO2 cathodes to efficient catalysts for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3gc04503j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391112539"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391112539"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391112539"))][Get cited by]]

OpenAlex: https://openalex.org/W4391112539 (Open access: False)
    
[[https://openalex.org/A5038689848][Mingfei Chen]], [[https://openalex.org/A5053008395][Yixin Zhou]], [[https://openalex.org/A5040027560][Wang Li]], [[https://openalex.org/A5017138446][Ganglin Xue]], [[https://openalex.org/A5082529409][Jili Guo]], [[https://openalex.org/A5086161254][Yaping Wang]], Green Chemistry. None(None)] 2024. https://doi.org/10.1039/d3gc04503j 
     
The wide application of lithium-ion batteries (LIBs) for electric vehicles forebodes the future decommissioning tide of spent LIBs. Therefore, the recycling of spent LIBs has garnered significant attention, primarily due...    

    

** Synergistic CuCoS-PANI Materials for Binder-Free Electrodes in Asymmetric Supercapacitors and Oxygen Evolution   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3na01066j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391260063"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391260063"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391260063"))][Get cited by]]

OpenAlex: https://openalex.org/W4391260063 (Open access: True)
    
[[https://openalex.org/A5024005569][Hiba A. Hasan]], [[https://openalex.org/A5067573568][Amir Muhammad Afzal]], [[https://openalex.org/A5084761641][Hussein Alrobei]], [[https://openalex.org/A5093796837][Fareeha Riasat]], [[https://openalex.org/A5034087002][Amir Muhammad Afzal]], [[https://openalex.org/A5057428775][Ali Saeedi]], [[https://openalex.org/A5093796838][Hasan B. Albargib]], [[https://openalex.org/A5003070785][A. Rehmat]], Nanoscale advances. None(None)] 2024. https://doi.org/10.1039/d3na01066j  ([[https://pubs.rsc.org/en/content/articlepdf/2024/na/d3na01066j][pdf]])
     
In advanced electronics, supercapacitors (SCs) have received a lot of attention. Nevertheless, it has been shown that different electrode designs that are based on metal sulfides are prone to oxidation,...    

    
