#+TITLE: water splitting
Description: water splitting papers
Created on Sun Sep 29 01:26:02 2024

Found 3 results from 2024-09-22 to 2024-09-29
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Amorphous Fe-Mo oxides activated by hydrogen peroxide etching for enhanced electrocatalytic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402715087
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.137405")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402715087"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402715087"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402715087"))][Get cited by]]

OpenAlex: https://openalex.org/W4402715087 (Open access: False)
    
[[https://openalex.org/A5007172285][Wei He]], [[https://openalex.org/A5014982941][Menglu Gan]], [[https://openalex.org/A5089182802][Jun Tang]], [[https://openalex.org/A5100748993][ZhengMing Sun]], Materials Letters. 377(None)] 2024. https://doi.org/10.1016/j.matlet.2024.137405 
     
No abstract    

    

* Enhance the Proportion of Fe3+ in NiFe‐Layered Double Hydroxides by utilizing Citric Acid to Improve the Efficiency and Durability of the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402720922
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Layered Double Hydroxide Nanomaterials
:PUBLICATION_DATE: 2024-09-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401582")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402720922"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402720922"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402720922"))][Get cited by]]

OpenAlex: https://openalex.org/W4402720922 (Open access: False)
    
[[https://openalex.org/A5101527396][Guoqi Li]], [[https://openalex.org/A5100412807][Lin Li]], [[https://openalex.org/A5022371210][Jihao Zhang]], [[https://openalex.org/A5102658611][Shiran Shan]], [[https://openalex.org/A5072872054][Chunze Yuan]], [[https://openalex.org/A5006108211][Tsu‐Chien Weng]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401582 
     
NiFe-layered double hydroxides (NiFe-LDH) are a type of catalyst known for their exceptional catalytic performance during the oxygen evolution reaction (OER). In this study, citric acid was incorporated into the synthesis process of NiFe-LDH, resulting in the NiFe-LDH-CA catalyst with superior OER performance. The catalytic efficacy is evaluated using linear sweep voltammetry (LSV), which demonstrates a significant reduction in the OER overpotential from 320 mV to 240 mV at a current density of 100 mA cm-2. X-ray photoelectron spectroscopy (XPS) and X-ray absorption spectrum (XAS) indicate that the distribution of nickel valence states showed no significant difference between two samples, yet the NiFe-LDH-CA has a significantly higher proportion of Fe3+ ions in its iron content. In-situ Raman spectroscopes reveal that Fe3+ broadens the redox potential of nickel and Pourbaix diagrams indicate that higher Fe3+ levels could facilitate the interaction with oxygen active sites. Based on the analysis of test data, we propose a hypothesis that the high proportion of Fe3+ in catalysts may accelerate the oxygen evolution process by modulating the redox potential of nickel and engaging with reactive oxygen species. This provides valuable insights into how to improve the reaction rate of nickel-based catalysts.    

    

* Electrocatalytic activity of La0.6Sr0. 4Co1-yCuyO3 (y = 0.1, 0.2, and 0.3) for oxygen evolution in an alkaline medium at 25℃  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402782270
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.56042/ijc.v63i9.10838")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402782270"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402782270"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402782270"))][Get cited by]]

OpenAlex: https://openalex.org/W4402782270 (Open access: False)
    
, Indian Journal of Chemistry. 63(9)] 2024. https://doi.org/10.56042/ijc.v63i9.10838 
     
No abstract    

    
