#+TITLE: water splitting
Description: water splitting papers
Created on Sun Mar 17 00:47:26 2024

Found 42 results from 2024-03-10 to 2024-03-17
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* A high-efficiency oxygen evolution electrocatalyst based on a Co3[Co (CN)6]2@NiFe LDH composite material  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392621570
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj00908h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392621570"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392621570"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392621570"))][Get cited by]]

OpenAlex: https://openalex.org/W4392621570 (Open access: False)
    
[[https://openalex.org/A5013473862][Jiaan Yu]], [[https://openalex.org/A5026131497][Ruru Fu]], [[https://openalex.org/A5024025712][Shanhai Ge]], [[https://openalex.org/A5023363049][Yang Liu]], [[https://openalex.org/A5027555354][Yun Zhao]], [[https://openalex.org/A5084194933][Caihong Feng]], [[https://openalex.org/A5062958272][Qingze Jiao]], [[https://openalex.org/A5018705134][Hansheng Li]], New Journal of Chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj00908h 
     
Due to the slow kinetics and large overpotential of oxygen evolution reaction (OER) in electrochemical water splitting. It is important to develop efficient and low-cost electrocatalysts for OER. In this...    

    

* Fabrication of defective mesoporous cerium oxide nanostructure for promoting an efficient and stable electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392621869
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nxmate.2024.100169")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392621869"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392621869"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392621869"))][Get cited by]]

OpenAlex: https://openalex.org/W4392621869 (Open access: False)
    
[[https://openalex.org/A5065182369][Aniruddha Mondal]], [[https://openalex.org/A5083155948][Muthuraja Velpandian]], [[https://openalex.org/A5048091744][Himadri Tanaya Das]], [[https://openalex.org/A5079624303][Apurba Sinhamahapatra]], [[https://openalex.org/A5053116355][Suddhasatwa Basu]], [[https://openalex.org/A5002773573][Mohd Afzal]], Next Materials. 3(None)] 2024. https://doi.org/10.1016/j.nxmate.2024.100169 
     
No abstract    

    

* Improved Oxygen Evolution Reaction Kinetics with Titanium Incorporated Nickel Ferrite for Efficient Anion Exchange Membrane Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392622761
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05761")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392622761"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392622761"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392622761"))][Get cited by]]

OpenAlex: https://openalex.org/W4392622761 (Open access: False)
    
[[https://openalex.org/A5035658742][Ki-Yong Yoon]], [[https://openalex.org/A5037937178][Kyung‐Bok Lee]], [[https://openalex.org/A5051461491][Jaehoon Jeong]], [[https://openalex.org/A5089096028][Myung‐Jun Kwak]], [[https://openalex.org/A5004040977][Dohyung Kim]], [[https://openalex.org/A5031554355][Hyunchul Roh]], [[https://openalex.org/A5041248271][Ji-Hoon Lee]], [[https://openalex.org/A5091482435][Sung Mook Choi]], [[https://openalex.org/A5022099174][Hosik Lee]], [[https://openalex.org/A5088908902][Juchan Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05761 
     
No abstract    

    

* Construction of porous flower-like Ru-doped CoNiFe layered double hydroxide for supercapacitors and oxygen evolution reaction catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392626543
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.044")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392626543"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392626543"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392626543"))][Get cited by]]

OpenAlex: https://openalex.org/W4392626543 (Open access: False)
    
[[https://openalex.org/A5033280750][Qian Ding]], [[https://openalex.org/A5052633287][Jingbo Yin]], [[https://openalex.org/A5039692998][Yueyue Huang]], [[https://openalex.org/A5018194804][Chaofan Wang]], [[https://openalex.org/A5077303263][Hubin Luo]], [[https://openalex.org/A5055081841][Shiguo Sun]], [[https://openalex.org/A5037241212][Yongqian Xu]], [[https://openalex.org/A5048068113][Hongjuan Li]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.044 
     
In recent years, ternary layered double hydroxide (LDH) has become a research hotspot for electrode materials and oxygen evolution reaction (OER) catalyst due to the enhanced synergistic effect between individual elements. However, the application of LDH is greatly limited by its low electrical conductivity and the disadvantage that nanosheets tend to accumulate and mask the active sites. Herein, a novel Ru-doped CoNiFe − LDH was prepared via a facile hydrothermal method. According to the density functional theory (DFT) calculations, the doping of Ru element could improve electron state density and band gaps of LDH and consequently boosted the electrochemical reaction kinetics as well as electrical conductivity. Furthermore, introduction of Ru atom induced the formation of porous flower-like structures in nanosheets. Compared to CoNiFe − LDH (28.9 m2/g), Ru-doped CoNiFe − LDH performed larger specific surface area of 53.1 m2/g, resulting in more electrochemically active sites. In these case, Ru-doped CoNiFe − LDH demonstrated better energy storage performance of 176.0 mAh/g at 1 A/g compared to original CoNiFe − LDH (78.9 mAh/g at 1 A/g). Besides, the assembled Ru-doped CoNiFe − LDH//activated carbon (AC) device delivered a maximum energy density of 36.4 W h kg−1 at the power density of 740.3 W kg−1 and an outstanding cycle life (78.7 % after 10,000 cycles). Meanwhile, Ru-doped CoNiFe − LDH exhibited lower overpotential (339 mV at 50 mA cm−2) and Tafel slope (93.2 mV dec−1). Therefore, this work provided novel and valuable insights into the rational doping of Ru elements for the controlled synthesis of supercapacitor electrode materials and OER catalysts.    

    

* Tungsten Doped Fecop2 Nanoparticles Embedded into Carbon for Highly Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392626811
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4752172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392626811"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392626811"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392626811"))][Get cited by]]

OpenAlex: https://openalex.org/W4392626811 (Open access: False)
    
[[https://openalex.org/A5022780097][Xinyao Quan]], [[https://openalex.org/A5008095269][Jiajia Ma]], [[https://openalex.org/A5021295877][Qian-Shuo Shao]], [[https://openalex.org/A5033209965][Hao-Cong Li]], [[https://openalex.org/A5065738034][Lingxiang Sun]], [[https://openalex.org/A5001387667][Gui Li Huang]], [[https://openalex.org/A5037431207][Yan Su]], [[https://openalex.org/A5061732797][Hong Zhang]], [[https://openalex.org/A5062588973][Yuning Wang]], [[https://openalex.org/A5039772620][Xiaoqing Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4752172 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Self‐Supported Fe‐Based Nanostructured Electrocatalysts for Water Splitting and Selective Oxidation Reactions: Past, Present, and Future  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392632371
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202303730")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392632371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392632371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392632371"))][Get cited by]]

OpenAlex: https://openalex.org/W4392632371 (Open access: True)
    
[[https://openalex.org/A5034827445][Mayur A. Gaikwad]], [[https://openalex.org/A5091898572][Vishal Burungale]], [[https://openalex.org/A5043360205][D.B. Malavekar]], [[https://openalex.org/A5044910327][Uma V. Ghorpade]], [[https://openalex.org/A5010175599][Umesh P. Suryawanshi]], [[https://openalex.org/A5055701402][Sae Jang]], [[https://openalex.org/A5013364501][Xiaofeng Guo]], [[https://openalex.org/A5014112848][Seung Wook Shin]], [[https://openalex.org/A5046528165][Jun‐Seok Ha]], [[https://openalex.org/A5045121125][Mahesh P. Suryawanshi]], [[https://openalex.org/A5079554524][Jihun Kim]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202303730 
     
Abstract Electrochemical water splitting plays a vital role in facilitating the transition towards a sustainable energy future by enabling renewable hydrogen (H 2 ) production, energy storage, and emission‐free transportation. Developing earth‐abundant electrocatalysts with outstanding overall water‐splitting performance, excellent catalytic activity, and robust long‐term stability is highly important in the practical application of water electrolysis. Self‐supported electrocatalysts have emerged as the most appealing candidate for practical H 2 production due to their increased active site loading, rapid mass and charge transfer, and strong interaction with the underneath conducting support. Additionally, these electrocatalysts also provide enhanced reaction kinetics and stability. Here, a comprehensive review of recent progress in developing self‐supported Fe‐based electrocatalysts for water splitting and selective oxidation reactions is presented with examples of oxyhydroxides, layered double hydroxides, oxides, chalcogenides, phosphides, nitrides, and other Fe‐containing electrocatalysts. A comprehensive historical development in the synthesis of self‐supported Fe‐based electrocatalysts is provided, with an emphasis on the various deposition methods and the choice of self‐supported conducting substrates considering large‐scale commercial applications. An overview of mechanistic understanding and approaches for enhanced H 2 production are also presented. Finally, the challenges and opportunities associated with developing Fe‐based electrocatalysts for practical applications in water splitting and alternative oxidation reactions are discussed.    

    

* Ru Species Anchored on Defective Cobalt Iron Oxide for Biomass Electro-Oxidation Coupled with Hydrogen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392634950
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4754289")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392634950"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392634950"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392634950"))][Get cited by]]

OpenAlex: https://openalex.org/W4392634950 (Open access: False)
    
[[https://openalex.org/A5079949918][Shasha Cui]], [[https://openalex.org/A5007329775][Guangjin Wang]], [[https://openalex.org/A5075130252][Fen Wang]], [[https://openalex.org/A5064769969][Ting‐Ting Li]], [[https://openalex.org/A5034970777][Zhijuan Liu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4754289 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* In Situ-Generated Hollow CoFe-LDH/Co-MOF Heterostructure Nanorod Arrays for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392637087
:TOPICS: Catalytic Nanomaterials, Gas Sensing Technology and Materials, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c00021")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392637087"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392637087"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392637087"))][Get cited by]]

OpenAlex: https://openalex.org/W4392637087 (Open access: False)
    
[[https://openalex.org/A5065546985][Guoying Yang]], [[https://openalex.org/A5064691727][Yonghua Song]], [[https://openalex.org/A5088167080][Song‐De Han]], [[https://openalex.org/A5080527274][Zhen‐Zhen Xue]], [[https://openalex.org/A5076574339][De‐Xuan Liu]], [[https://openalex.org/A5040610212][Ani Wang]], [[https://openalex.org/A5011677079][Guo‐Ming Wang]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c00021 
     
Assembling a heterostructure is an effective strategy for enhancing the electrocatalytic activity of hybrid materials. Herein, CoFe-layered double hydroxide and Co-metal–organic framework (CoFe-LDH/Co-MOF) hollow heterostructure nanorod arrays are synthesized. First, [Co(DIPL)(H3BTC)(H2O)2]n [named as Co-MOF, DIPL = 2,6-di(pyrid-4-yl)-4-phenylpyridine, H3BTC = 1,3,5-benzenetricarboxylic acid] crystalline materials with a uniform hollow structure were prepared on the nickel foam. The CoFe-LDH/Co-MOF composite perfectly inherits the original hollow nanorod array morphology after the subsequent electrodeposition process. Optimized CoFe-LDH/Co-MOF hollow heterostructure nanorod arrays display excellent performance in oxygen evolution reaction (OER) with ultralow overpotentials of 215 mV to deliver current densities of 10 mA cm–2 and maintain the electrocatalytic activity for a duration as long as 220 h, ranking it one of the non-noble metal-based electrocatalysts for OER. Density functional theory calculations validate the reduction in free energy for the rate-determining step by the synergistic effect of Co-MOF and CoFe-LDH, with the increased charge density and noticeable electron transfer at the Co–O site, which highlights the capability of Co-MOF to finely adjust the electronic structure and facilitate the creation of active sites. This work establishes an experimental and theoretical basis for promoting efficient water splitting through the design of heterostructures in catalysts.    

    

* Regulating atomic Fe/Cu dual sites with unsymmetrical Fe-N6 and Cu-N1S2 coordination for promoting bifunctional oxygen electrocatalysis in advanced zinc-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392639396
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ensm.2024.103342")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392639396"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392639396"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392639396"))][Get cited by]]

OpenAlex: https://openalex.org/W4392639396 (Open access: False)
    
[[https://openalex.org/A5021821095][Jing Peng]], [[https://openalex.org/A5081153296][Bihua Hu]], [[https://openalex.org/A5047192667][Zhitong Li]], [[https://openalex.org/A5079367889][Xiongwei Zhong]], [[https://openalex.org/A5026483252][Junwei Shi]], [[https://openalex.org/A5062853436][Shuyu Cui]], [[https://openalex.org/A5085092374][Xingzhu Wang]], [[https://openalex.org/A5062112444][Baomin Xu]], Energy Storage Materials. None(None)] 2024. https://doi.org/10.1016/j.ensm.2024.103342 
     
Dual-metal single-atom catalysts with heteronuclear active sites exhibit superior oxygen catalysis performance than their single-atom counterparts, facilitating the practical applications in advanced electrochemical energy devices. Herein, a Fe-Cu dual-metal single-atom catalyst with Fe-N6 and Cu-N1S2 coordination environment (FeCu-DSAs/NSC) is reported. Due to the synergism of bimetallic active sites and asymmetric heteroatom coordination, the resultant FeCu-DSAs/NSC displays better bifunctional catalytic performance (a small potential gap between the Eη10 and E1/2, ΔE=0.647 V) when compared with the counterparts (Pt/C+IrO2 and Cu-ISAs/NSC), as well as surpassing most of bifunctional metal atom-based catalysts reported to date. As expected, FeCu-DSAs/NSC based rechargeable zinc-air battery shows remarkable superiority than commercial Pt/C+IrO2 benchmark, resulting in a high peak power density (230.66 mW cm−2), open-circuit voltage (1.464 V) and long-term cycling stability (up to 350 h at 10 mA cm−2).    

    

* S-doped Yttrium Ruthenate Pyrochlore catalyst for Efficient Electrocatalytic Oxygen Evolution in Acidic Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392639957
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.174072")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392639957"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392639957"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392639957"))][Get cited by]]

OpenAlex: https://openalex.org/W4392639957 (Open access: False)
    
[[https://openalex.org/A5061758333][Rei‐Cheng Yang]], [[https://openalex.org/A5066468525][Hao Qi]], [[https://openalex.org/A5035942767][Jianan Zhao]], [[https://openalex.org/A5009590736][Cong Liu]], [[https://openalex.org/A5038208946][Shujie Xue]], [[https://openalex.org/A5011797167][Fengjuan Miao]], [[https://openalex.org/A5064144494][Wenbing Tang]], [[https://openalex.org/A5035888330][Qinghong Huang]], [[https://openalex.org/A5037677450][Jing Wang]], [[https://openalex.org/A5082323192][Yuping Wu]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.174072 
     
No abstract    

    

* Tm-Doping Modulated P-D Orbital Coupling to Enhance the Oxygen Evolution Performance of Ni3s2  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392641110
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4755085")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392641110"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392641110"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392641110"))][Get cited by]]

OpenAlex: https://openalex.org/W4392641110 (Open access: False)
    
[[https://openalex.org/A5081449417][Jing Pan]], [[https://openalex.org/A5049808310][Qiuhong Li]], [[https://openalex.org/A5089795720][Minghao Zhang]], [[https://openalex.org/A5002209512][Rui Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4755085 
     
No abstract    

    

* NH4Cl-assisted synthesis of TaON nanoparticle applied to photocatalytic hydrogen and oxygen evolution from water  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392642667
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.02.051")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392642667"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392642667"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392642667"))][Get cited by]]

OpenAlex: https://openalex.org/W4392642667 (Open access: False)
    
[[https://openalex.org/A5014193156][Yanhua Xu]], [[https://openalex.org/A5017622841][Kaiwei Liu]], [[https://openalex.org/A5072552402][Jifang Zhang]], [[https://openalex.org/A5011611335][Boyang Zhang]], [[https://openalex.org/A5085186808][Jiaming Zhang]], [[https://openalex.org/A5073697986][Shaoyong Ke]], [[https://openalex.org/A5043069455][Haifeng Wang]], [[https://openalex.org/A5007957054][Guijun Ma]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.02.051 
     
No abstract    

    

* Surface-Engineered Titanium with Nanoceria to Enhance Soft Tissue Integration Via Reactive Oxygen Species Modulation and Nanotopographical Sensing  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392650694
:TOPICS: Nanotechnology and Imaging for Cancer Therapy and Diagnosis, Nanomaterials with Enzyme-Like Characteristics, Bone Tissue Engineering and Biomaterials
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c02119")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392650694"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392650694"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392650694"))][Get cited by]]

OpenAlex: https://openalex.org/W4392650694 (Open access: False)
    
[[https://openalex.org/A5078950874][Hye-Won Shim]], [[https://openalex.org/A5061522355][Amal George Kurian]], [[https://openalex.org/A5046523006][Jiwon Lee]], [[https://openalex.org/A5035019823][Sang Cheol Lee]], [[https://openalex.org/A5014129887][Hae‐Won Kim]], [[https://openalex.org/A5041064140][Rajendra K. Singh]], [[https://openalex.org/A5080238951][Jung Hwan Lee]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c02119 
     
The design of implantable biomaterials involves precise tuning of surface features because the early cellular fate on such engineered surfaces is highly influenced by many physicochemical factors [roughness, hydrophilicity, reactive oxygen species (ROS) responsiveness, etc.]. Herein, to enhance soft tissue integration for successful implantation, Ti substrates decorated with uniform layers of nanoceria (Ce), called Ti@Ce, were optimally developed by a simple and cost-effective in situ immersion coating technique. The characterization of Ti@Ce shows a uniform Ce distribution with enhanced roughness (∼3-fold increase) and hydrophilicity (∼4-fold increase) and adopted ROS-scavenging capacity by nanoceria coating. When human gingival fibroblasts were seeded on Ti@Ce under oxidative stress conditions, Ti@Ce supported cellular adhesion, spreading, and survivability by its cellular ROS-scavenging capacity. Mechanistically, the unique nanocoating resulted in higher expression of amphiphysin (a nanotopology sensor), paxillin (a focal adhesion protein), and cell adhesive proteins (collagen-1 and fibronectin). Ti@Ce also led to global chromatin condensation by decreasing histone 3 acetylation as an early differentiation feature. Transcriptome analysis by RNA sequencing confirmed the chromatin remodeling, antiapoptosis, antioxidant, cell adhesion, and TGF-β signaling-related gene signatures in Ti@Ce. As key fibroblast transcription (co)factors, Ti@Ce promotes serum response factor and MRTF-α nucleus localization. Considering all of this, it is proposed that the surface engineering approach using Ce could improve the biological properties of Ti implants, supporting their functioning at soft tissue interfaces and utilization as a bioactive implant for clinical conditions such as peri-implantitis.    

    

* Boosting Efficient Alkaline Hydrogen Evolution Reaction of CoFe‐Layered Double Hydroxides Nanosheets via Co‐Coordination Mechanism of W‐Doping and Oxygen Defect Engineering  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392658994
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202311221")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392658994"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392658994"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392658994"))][Get cited by]]

OpenAlex: https://openalex.org/W4392658994 (Open access: False)
    
[[https://openalex.org/A5000808868][Shaohong Wang]], [[https://openalex.org/A5051099864][Jing Wu]], [[https://openalex.org/A5029467709][Yin Xu]], [[https://openalex.org/A5062655882][Dandan Liang]], [[https://openalex.org/A5049864956][Da Li]], [[https://openalex.org/A5088753104][Gang Chen]], [[https://openalex.org/A5071554002][Guohong Liu]], [[https://openalex.org/A5001523912][Yujie Feng]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202311221 
     
Abstract While surface defects and heteroatom doping exhibit promising potential in augmenting the electrocatalytic hydrogen evolution reaction (HER), their performance remains unable to rival that of the costly Pt‐based catalysts. Yet, the concurrent modification of catalysts by integrating both approaches stands as a promising strategy to effectively address the aforementioned limitation. In this work, tungsten dopants are introduced into self‐supported CoFe‐layered double hydroxides (LDH) on nickel foam using a hydrothermal method, and oxygen vacancies (Ov) are further introduced through calcination. The analysis results demonstrated that tungsten doping reduces the Ov formation energy of CoFeW‐LDH. The Ov acted as oxophilic sites, facilitating water adsorption and dissociation, and reducing the barrier for cleaving HO─H bonds from 0.64 to 0.14 eV. Additionally, Ov regulated the electronic structure of CoFeW‐LDH to endow optimized hydrogen binding ability on tungsten atoms, thereby accelerating alkaline Volmer and Heyrovsky reaction kinetics. Specifically, the abundance of Ov induced a transition of tungsten from a six‐coordinated to highly active four‐coordinated structure, which becomes the active site for HER. Consequently, an ultra‐low overpotential of 41 mV at 10 mA cm −2 , and a low Tafel slope of 35 mV dec −1 are achieved. These findings offer crucial insights for the design of efficient HER electrocatalysts.    

    

* Synergistic Effect of Electrocatalyst for Enhanced Oxygen Reduction Reaction: Low Pt-Loaded CuPt Alloy Nanoparticles Supported on N-Doped Hierarchical Porous Carbon  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392659004
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c00297")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392659004"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392659004"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392659004"))][Get cited by]]

OpenAlex: https://openalex.org/W4392659004 (Open access: False)
    
[[https://openalex.org/A5050747300][Min Li]], [[https://openalex.org/A5070883766][Feng Liu]], [[https://openalex.org/A5012127433][Yongming Zhang]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c00297 
     
It is challenging to synthesize oxygen reduction reaction (ORR) electrocatalysts that are highly efficient, affordable, and stable for use in proton exchange membrane fuel cells. To address this challenge, we developed a low platinum-loading (only 6.68% wt) ORR catalyst (PtCu1-NC), comprising CuPt nanoparticles (average size: 1.51 nm) supported on the N-doped carbon substrates. PtCu1-NC possesses a high specific surface area of 662 m2 g–1 and a hierarchical porous structure, facilitating efficient mass transfer. The synergistic effect from introduced copper and the electron effect from nitrogen modify the electronic structure of platinum, effectively accelerating the ORR reaction and enhancing stability. Density functional theory calculations demonstrate the catalytic mechanism and further verify the synergistic effect. Electrochemical assessments indicate that PtCu1-NC exhibits specific activity and mass activity 5.3 and 5.6 times higher, respectively, than commercial Pt/C. The half-wave potential is 27 mV more positive than that of commercial Pt/C. The electrochemical active surface area value is 104.3 m2 g–1, surpassing that of Pt/C. Approximately 78% of current is retained after 10,000 s chronoamperometry measurement. These results highlight the effectiveness of alloying in improving the catalyst performance.    

    

* A review on synthesis and modification of cobalt-molybdenum based sulfides as hydrogen and oxygen evolution catalysts for water electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392660622
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cinorg.2024.100043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392660622"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392660622"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392660622"))][Get cited by]]

OpenAlex: https://openalex.org/W4392660622 (Open access: True)
    
[[https://openalex.org/A5073501391][Jie Zhang]], [[https://openalex.org/A5026246996][Chunlin Hu]], [[https://openalex.org/A5039904213][Peng Deng]], [[https://openalex.org/A5060296132][Yan-Hong Yin]], Chemistry of Inorganic Materials. None(None)] 2024. https://doi.org/10.1016/j.cinorg.2024.100043 
     
Hydrogen energy as the alternative to fossil fuel received wide attention. Among different methods of hydrogen production, water electrolysis is the cleanest and most promising method. However, its development is greatly limited by hydrogen evolution reaction (HER) reaction and oxygen evolution reaction (OER) reaction. Therefore, it is very necessary to develop low-cost, high activity, and good stability of non-precious metal catalyst to replace the precious metal catalyst (Pt, RuO2), and to further reduce overpotential and power consumption. To date, great efforts have been made to develop transition metal compounds with electrocatalytic performance, such as sulfides, oxides, and carbides materials. Especially, transition metal sulfides play a very important role as catalysts and have attracted wide attention for their structural adjustability, high abundance, and mild preparation process. In this introduction, we focus on the role of transition metal sulfides in catalysts for water electrolysis, especially in a few most studied sulfides such as cobalt/molybdenum based sulfides and the recently reported homogeneous cobalt-molybdenum based sulfides, in which cobalt acts as a key element. Composition, morphology, and size are the most important factors that influence the intrinsic activity, electrical conductivity, and electronic structure of these transition metal sulfides. Besides, the effect of carbon nanomaterials as carrier materials is also discussed. The aim of this review is to emphasize the great potentials of cobalt and molybdenum based sulfides with high performance, and to help improve the performance of existing sulfides and explore new modification methods.    

    

* Water film-mediated photocatalytic oxidation of oxalate on TiO2  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392660874
:TOPICS: Photocatalysis and Solar Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Solar Water Splitting Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcat.2024.115425")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392660874"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392660874"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392660874"))][Get cited by]]

OpenAlex: https://openalex.org/W4392660874 (Open access: True)
    
[[https://openalex.org/A5087726941][N. Tan Luong]], [[https://openalex.org/A5013347955][Khalil Hanna]], [[https://openalex.org/A5028158469][Jean-François Boily]], Journal of Catalysis. None(None)] 2024. https://doi.org/10.1016/j.jcat.2024.115425 
     
Water films on minerals under humid environment can be photocatalytic hotspots when exposed to sunlight or artificial sources of ultraviolet (and visible) radiation. In this study, we resolved the water film-mediated photocatalysis on a model system of oxalate and TiO2 by in situ infrared spectroscopy. We find that 0.5 to 4 monolayer- (ML) thick water films enhanced photodecomposition rates of oxalate under 21 kPa O2 through the combination of direct hole transfer, ligand-to-metal-charge transfer and the production of hydroxyl radical and reactive oxygen species. Rates were, however, substantially slower in the absence of O2 because charge recombination, together with water film-mediated charge localization, disrupted hole transfer and hydroxyl radical production. Our work adds insight into the impact of humidity on controlling important photocatalytic processes in nature (drying soils, atmospheric aerosols), and technology (water and air treatment).    

    

* Interface oxidation induced amorphous/crystalline 1D hollandite Rb0.17IrO2 for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392660887
:TOPICS: Electrocatalysis for Energy Conversion, Advanced Materials for Smart Windows, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159881")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392660887"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392660887"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392660887"))][Get cited by]]

OpenAlex: https://openalex.org/W4392660887 (Open access: False)
    
[[https://openalex.org/A5032107505][Danni Li]], [[https://openalex.org/A5002152947][Anhui Zhou]], [[https://openalex.org/A5064789384][Xiang Shao]], [[https://openalex.org/A5079098289][Lin Zhu]], [[https://openalex.org/A5021827773][Youwei Du]], [[https://openalex.org/A5084812419][Limei Cao]], [[https://openalex.org/A5008669070][Chenglong Ma]], [[https://openalex.org/A5029886716][Jie Yang]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159881 
     
Recently, surface reconstruction derived from Ir-based derivatives could achieve satisfactory oxygen evolution performance. Herein, ultra-long nanowire hollandite structured Rb0.17IrO2 was synthesized and a nano-amorphous layer with a thickness of ∼1.5 nm was achieved by interfacial oxidation treatment. The prepared catalyst exhibits outstanding water oxidation activity with an oxygen evolution reaction (OER) current density of 10 mA cm−2 at 330 mV for robust continuous operation in acidic media. Through the spectroscopic and density functional theory (DFT) theoretical calculations, we demonstrate that the nano-amorphous layers induced by interfacial oxidation on the one-dimensional (1D)-nanowire surface have enhanced O-2p centers and increased Ir-O hybridization compared to the bulk Rb0.17IrO2 phase, which essentially balances the adsorption energy of the intermediates. Effectively incorporating surface reconstruction behavior could significantly improve catalyst activity. This work effectively combines 1D Ir-based materials and surface reconstruction, which provides a strategy for the subsequent full utilization of Ir-based materials applied on OER process.    

    

* Heterojunction of MXenes and MN4–graphene: Machine learning to accelerate the design of bifunctional oxygen electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392661236
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Memristive Devices for Neuromorphic Computing, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.073")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392661236"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392661236"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392661236"))][Get cited by]]

OpenAlex: https://openalex.org/W4392661236 (Open access: False)
    
[[https://openalex.org/A5021919979][Xue Bai]], [[https://openalex.org/A5067079504][Sen Lu]], [[https://openalex.org/A5065267972][Pei Song]], [[https://openalex.org/A5057780297][Zepeng Jia]], [[https://openalex.org/A5022933774][Zi Gao]], [[https://openalex.org/A5040111779][Tongjang Peng]], [[https://openalex.org/A5069796893][Zhiguo Wang]], [[https://openalex.org/A5044278509][Qi Jiang]], [[https://openalex.org/A5051174606][Hong‐Ling Cui]], [[https://openalex.org/A5016364450][Weizhi Tian]], [[https://openalex.org/A5064403200][Rong Feng]], [[https://openalex.org/A5004278262][Zhiyong Liang]], [[https://openalex.org/A5002645765][Qin Kang]], [[https://openalex.org/A5007869766][Hongkuan Yuan]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.073 
     
Oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) are essential for the development of excellent bifunctional electrocatalysts, which are key functions in clean energy production. The emphasis of this study lies in the rapid design and investigation of 153 MN4–graphene (Gra)/ MXene (M2NO) electrocatalysts for ORR/OER catalytic activity using machine learning (ML) and density functional theory (DFT). The DFT results indicated that CoN4–Gra/Ti2NO had both good ORR (0.37 V) and OER (0.30 V) overpotentials, while TiN4–Gra/M2NO and MN4–Gra/Cr2NO had high overpotentials. Our research further indicated orbital spin polarization and d-band centers far from the Fermi energy level, affecting the adsorption energy of oxygen-containing intermediates and thus reducing the catalytic activity. The ML results showed that the gradient boosting regression (GBR) model successfully predicted the overpotentials of the monofunctional catalysts RhN4–Gra/Ti2NO (ORR, 0.39 V) and RuN4–Gra/W2NO (OER, 0.45 V) as well as the overpotentials of the bifunctional catalyst RuN4–Gra/W2NO (ORR, 0.39 V; OER, 0.45 V). The symbolic regression (SR) algorithm was used to construct the overpotential descriptors without environmental variable features to accelerate the catalyst screening and shorten the trial-and-error costs from the source, providing a reliable theoretical basis for the experimental synthesis of MXene heterostructures.    

    

* Sandwich-like MnOx/MnN0.84/Mn Electrode toward Improved Electrocatalytic Oxygen Evolution in Acidic Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392661629
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaenm.3c00706")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392661629"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392661629"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392661629"))][Get cited by]]

OpenAlex: https://openalex.org/W4392661629 (Open access: False)
    
[[https://openalex.org/A5054409131][Zhiqiang Xu]], [[https://openalex.org/A5034271384][Weiguang Ma]], [[https://openalex.org/A5024416620][Guifa Long]], [[https://openalex.org/A5087264224][Xiaomei Wang]], [[https://openalex.org/A5058298755][Haibo Chi]], [[https://openalex.org/A5059076745][Xu Zong]], [[https://openalex.org/A5011065863][Can Li]], ACS Applied Engineering Materials. None(None)] 2024. https://doi.org/10.1021/acsaenm.3c00706 
     
Developing efficient and robust noble-metal-free electrocatalysts capable of catalyzing water oxidation in acidic media is highly desirable for producing H2 while it remains a great challenge. Herein, a self-supported MnOx/MnN0.84/Mn electrode with a sandwich-like configuration was prepared by consecutive steps involving a nitridation treatment and an in situ electrochemical activation process. The electrode requires overpotentials of ca. 475 and 571 mV at current densities of 10 and 100 mA cm–2, respectively, for the oxygen evolution reaction (OER) in 1.0 M H2SO4. More impressively, the electrode remains stable for over 300 h of continuous operation at a current density of 100 mA cm–2, which is, as far as we know, among the best values reported for Mn-based materials in the field of acidic water electrolysis. It is found that the metallic MnN0.84 layer is not only the precursor for the formation of MnOx nanosheet electrocatalysts as the actual catalyst for the OER but also enables efficient charge transfer between the active sites at the surface and the substrate. Moreover, the anticorrosive MnN0.84 interlayer that acts as the binder between the Mn substrate and the MnOx catalyst can protect the Mn substrate from corrosion in acidic electrolytes, highlighting the importance of interlayer modification in stabilizing electrocatalysts in harsh reaction conditions.    

    

* In Situ Fabrication of Low-Crystallinity (Ni,Fe)Xsy Nanosheet Arrays Via Room-Temperature Corrosion Engineering Toward Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392697090
:TOPICS: Atomic Layer Deposition Technology, Fabrication and Applications of Porous Alumina Membranes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4756896")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392697090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392697090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392697090"))][Get cited by]]

OpenAlex: https://openalex.org/W4392697090 (Open access: False)
    
[[https://openalex.org/A5086050138][Mingyue Chen]], [[https://openalex.org/A5014510012][Wenhui Li]], [[https://openalex.org/A5091099530][Yu Long]], [[https://openalex.org/A5002588646][Pengcheng Qi]], [[https://openalex.org/A5021642253][HengAn Wu]], [[https://openalex.org/A5013045058][Kunyu Hao]], [[https://openalex.org/A5018646101][Yiwen Tang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4756896 
     
No abstract    

    

* Perovskite for Electrocatalytic Oxygen Evolution at Elevated Temperatures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392697241
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202301534")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392697241"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392697241"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392697241"))][Get cited by]]

OpenAlex: https://openalex.org/W4392697241 (Open access: False)
    
[[https://openalex.org/A5003993083][Fatma Abdelghafar]], [[https://openalex.org/A5072221758][Xiaomin Xu]], [[https://openalex.org/A5044918647][San Ping Jiang]], [[https://openalex.org/A5064123920][Zongping Shao]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202301534 
     
The development of advanced electrolysis technologies such as anion exchange membrane water electrolyzer (AEMWE) is central to the vision of a sustainable energy future. Key to the realization of such AEMWE technology lies in the exploration of low‐cost and high‐efficient catalysts for facilitating the anodic oxygen evolution reaction (OER). Despite tremendous efforts in the fundamental research, most of today’s OER works are conducted under room temperature, which deviates significantly with AEMWE’s operating temperature (50–80 °C). To bridge this gap, it is highly desirable to obtain insights into the OER catalytic behavior at elevated temperatures. Herein, using the well‐known perovskite catalyst Ba0.5Sr0.5Co0.8Fe0.2O3−δ (BSCF) as a proof of concept, the effect of temperature on the variation in OER catalytic activity and stability is evaluated. It is found that the BSCF’s activity increases with increasing temperature due to enhanced lattice oxygen participation promoting the lattice oxygen‐mediated OER process. Further, surface amorphization and cation leaching of BSCF become more pronounced as temperature increases, causing a somewhat attenuated OER stability. These new understandings of the fundamental OER catalysis over perovskite materials at industrial‐relevant temperature conditions are expected to have strong implications for the research of OER catalysts to be deployed in practical water electrolyzers.    

    

* Triggering Synergy between p-Type Sputter-Deposited FeMnOx or FeNiOx and W-Doped BiVO4 for Enhanced Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392699319
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c02739")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392699319"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392699319"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392699319"))][Get cited by]]

OpenAlex: https://openalex.org/W4392699319 (Open access: False)
    
[[https://openalex.org/A5081128002][Niqab Khan]], [[https://openalex.org/A5048444247][Ariadne Köche]], [[https://openalex.org/A5013036655][Higor A. Centurion]], [[https://openalex.org/A5026162988][Lucas G. Rabelo]], [[https://openalex.org/A5056093125][Jefferson Bettini]], [[https://openalex.org/A5041561897][Gabriel Trindade dos Santos]], [[https://openalex.org/A5046567819][Flávio L. Souza]], [[https://openalex.org/A5032974999][Renato V. Gonçalves]], [[https://openalex.org/A5011464959][Sherdil Khan]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.3c02739 
     
No abstract    

    

* Experimental and first-principles insights into an enhanced performance of Ru-doped copper phosphate electrocatalyst during oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392713728
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.sajce.2024.03.006")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392713728"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392713728"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392713728"))][Get cited by]]

OpenAlex: https://openalex.org/W4392713728 (Open access: True)
    
[[https://openalex.org/A5090149269][Jasmin S. Shaikh]], [[https://openalex.org/A5000448228][Meena Rittiruam]], [[https://openalex.org/A5054768027][Tinnakorn Saelee]], [[https://openalex.org/A5063387137][Victor Márquez]], [[https://openalex.org/A5082222268][Navajsharif S. Shaikh]], [[https://openalex.org/A5015354344][Patcharaporn Khajondetchairit]], [[https://openalex.org/A5018107750][Sumayya C. Pathan]], [[https://openalex.org/A5088767687][Mohammad Khaja Nazeeruddin]], [[https://openalex.org/A5001087403][Piyasan Praserthdam]], [[https://openalex.org/A5036226683][Supareak Praserthdam]], South African Journal of Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.sajce.2024.03.006 
     
No abstract    

    

* Nitrogen doped leather waste-derived carbon materials as electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392715055
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.inoche.2024.112295")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392715055"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392715055"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392715055"))][Get cited by]]

OpenAlex: https://openalex.org/W4392715055 (Open access: False)
    
[[https://openalex.org/A5061281601][Afshin Abbasi]], [[https://openalex.org/A5019801918][Musammir Khan]], [[https://openalex.org/A5061051894][Fawad Ahmad]], [[https://openalex.org/A5030639287][Muhammad Imran Khan]], [[https://openalex.org/A5080155587][Abdallah Shanableh]], [[https://openalex.org/A5001143351][R. P. S. Rajput]], [[https://openalex.org/A5009050964][Suryyia Manzoor]], [[https://openalex.org/A5039707327][Shabnam Shahida]], [[https://openalex.org/A5002846345][Rafael Luque]], [[https://openalex.org/A5006821035][Sameh M. Osman]], [[https://openalex.org/A5007253361][Mushtaq Hussain Lashari]], Inorganic Chemistry Communications. None(None)] 2024. https://doi.org/10.1016/j.inoche.2024.112295 
     
Nitrogen doped leather waste-derived carbon materials have been employed as eletrocatalyst for oxygen evolution reaction. Low current densities and complex synthesis routes of other carbon-based materials limit their practical applicability. We present herein a simple and cost-competitive design of a metal free nitrogen-doped carbon matrix (NCM). At 10 mA cm−2 of current density, the assembled NCM showed a low over potential of 330 mV. NCM provided 73 mV dec-1 of slope value according to Tafel analysis, with NCM slope value improved as compared to previously described electrocatalysts inclusive of graphene (113 mV dec−1) and carbon nanosheets (101 mV dec−1), under similar reaction conditions. Linear sweep voltamogram, stability test and electrochemical impedance spectra confirmed the potential of NCM in OER as a heterogeneous electrocatalyst.    

    

* Acidic Oxygen Evolution Reaction: Fundamental Understanding and Electrocatalysts Design  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392813847
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202400239")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392813847"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392813847"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392813847"))][Get cited by]]

OpenAlex: https://openalex.org/W4392813847 (Open access: False)
    
[[https://openalex.org/A5063922467][Jiao Li]], [[https://openalex.org/A5030554560][Weiming Tian]], [[https://openalex.org/A5020746135][Qi Li]], [[https://openalex.org/A5084344855][Shenlong Zhao]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202400239 
     
Water electrolysis driven by “green electricity“ is an ideal technology to realize energy conversion and store renewable energy into hydrogen. With the development of proton exchange membrane (PEM), water electrolysis in acidic media suitable for many situations with an outstanding advantage of high gas purity has attracted significant attention. Compared with hydrogen evolution reaction (HER) in water electrolysis, oxygen evolution reaction (OER) is a kinetic sluggish process that needs a higher overpotential. Especially in acidic media, OER process poses higher requirements for the electrocatalysts, such as high efficiency, high stability and low costs. This review focuses on the acidic OER electrocatalysis, reaction mechanisms, and critical parameters used to evaluate performance. Especially the modification strategies applied in the design and construction of new‐type electrocatalysts are also summarized. The characteristics of traditional noble metal‐based electrocatalysts and the noble metal‐free electrocatalysts developed in recent decades are compared and discussed. Finally, the current challenges for the most promising acidic OER electrocatalysts are presented, together with a perspective for future water electrolysis.    

    

* Recent progress of electrocatalysts for acidic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392743186
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ccr.2024.215758")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392743186"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392743186"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392743186"))][Get cited by]]

OpenAlex: https://openalex.org/W4392743186 (Open access: False)
    
[[https://openalex.org/A5005711039][Yuping Chen]], [[https://openalex.org/A5011544541][Chunyan Shang]], [[https://openalex.org/A5016588737][Xin Xiao]], [[https://openalex.org/A5084740267][Weihua Guo]], [[https://openalex.org/A5064109029][Qiang Xu]], Coordination Chemistry Reviews. 508(None)] 2024. https://doi.org/10.1016/j.ccr.2024.215758 
     
No abstract    

    

* Surface-Functionalized Ni nanostructures for Oxygen Evolution Reaction, a different synthetic approach.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392704432
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2023-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.29363/nanoge.matsus.2024.135")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392704432"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392704432"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392704432"))][Get cited by]]

OpenAlex: https://openalex.org/W4392704432 (Open access: False)
    
[[https://openalex.org/A5047786576][Aureliano Macili]], [[https://openalex.org/A5020337283][Laia Francàs]], [[https://openalex.org/A5080028922][Jordi García‐Antón]], [[https://openalex.org/A5039090961][Xavier Sala]], No host. None(None)] 2023. https://doi.org/10.29363/nanoge.matsus.2024.135 
     
No abstract    

    

* Oxide management in Ruthenium oxide catalysts for efficient Oxygen Evolution Reaction in acid.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392704834
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2023-12-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.29363/nanoge.matsus.2024.202")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392704834"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392704834"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392704834"))][Get cited by]]

OpenAlex: https://openalex.org/W4392704834 (Open access: False)
    
[[https://openalex.org/A5019487756][Amit Kumar Das]], [[https://openalex.org/A5075242279][F. Pelayo Garcı́a de Arquer]], [[https://openalex.org/A5029072578][Xia Lu]], [[https://openalex.org/A5033159909][Anku Guha]], [[https://openalex.org/A5094126826][Viktoria Holovanova]], No host. None(None)] 2023. https://doi.org/10.29363/nanoge.matsus.2024.202 
     
No abstract    

    

* Core-shell cobalt iron oxide nanoparticles for the electrocatalysis of the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392769583
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2022-11-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392769583"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392769583"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392769583"))][Get cited by]]

OpenAlex: https://openalex.org/W4392769583 (Open access: True)
    
[[https://openalex.org/A5083775184][Lisa Royer]], No host. None(None)] 2022. None  ([[https://theses.hal.science/tel-04213561/document][pdf]])
     
No abstract    

    

* Cation-Modified Co-Based Borophosphates for Efficient and Robust Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392839522
:TOPICS: Electrocatalysis for Energy Conversion, Desulfurization Technologies for Fuels, Polyoxometalate Clusters and Materials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4725648")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392839522"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392839522"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392839522"))][Get cited by]]

OpenAlex: https://openalex.org/W4392839522 (Open access: False)
    
[[https://openalex.org/A5070332647][Jun‐Ling Song]], [[https://openalex.org/A5084186256][Yonggang Meng]], [[https://openalex.org/A5001006550][Dong-Sheng Pan]], [[https://openalex.org/A5078776283][Ao Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4725648 
     
No abstract    

    

* In Situ Modulation of Oxygen Vacancies on 2D Metal Hydroxide Organic Frameworks for High‐Efficiency Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392732464
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202311713")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392732464"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392732464"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392732464"))][Get cited by]]

OpenAlex: https://openalex.org/W4392732464 (Open access: False)
    
[[https://openalex.org/A5091228890][Kai Ge]], [[https://openalex.org/A5034128349][Yi Zhao]], [[https://openalex.org/A5019180285][Yunxia Hu]], [[https://openalex.org/A5024183430][Zhuozhi Wang]], [[https://openalex.org/A5067221645][Jingjing Wang]], [[https://openalex.org/A5038236550][Mei‐Sang Yang]], [[https://openalex.org/A5069013809][Canfei He]], [[https://openalex.org/A5066825255][Yongfang Yang]], [[https://openalex.org/A5052172266][Lei Zhu]], [[https://openalex.org/A5083408654][Boxiong Shen]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202311713 
     
Abstract The discovery of non‐precious catalysts for replacing the precious metal of ruthenium in the oxygen evolution reaction (OER) represents a key step in reducing the cost of green hydrogen production. The 2D d ‐MHOFs, a new 2D materials with controllable oxygen vacancies formed by controlling the degree of coordination bridging between metal hydroxyl oxide and BDC ligands are synthesized at room temperature, exhibit excellent OER properties with low overpotentials of 207 mV at 10 mA cm −2 . High‐resolution transmission electron microscopy images and density functional theory calculations demonstrate that the introduction of oxygen vacancy sites leads to a lattice distortion and charge redistribution in the catalysts, enhancing the OER activity of 2D d ‐MHOFs comprehensively. Synchrotron radiation and in situ Raman/Fourier transform infrared spectroscopy indicate that part of oxygen defect sites on the surface of 2D d ‐MHOFs are prone to transition to highly active metal hydroxyl oxides during the OER process. This work provides a mild strategy for scalable preparation of 2D d ‐MHOFs nanosheets with controllable oxygen defects, reveals the relationship between oxygen vacancies and OER performance, and offers a profound insight into the basic process of structural transformation in the OER process.    

    

* Modulating space charge of FeP/CoP p-n heterojunction for boosting oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392636984
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.060")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392636984"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392636984"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392636984"))][Get cited by]]

OpenAlex: https://openalex.org/W4392636984 (Open access: False)
    
[[https://openalex.org/A5069899429][Shaqi Fu]], [[https://openalex.org/A5018569451][Peng Cheng]], [[https://openalex.org/A5030386675][Yuancong Luo]], [[https://openalex.org/A5034521153][Lingli Cheng]], [[https://openalex.org/A5011764958][Xuechun Yang]], [[https://openalex.org/A5057732263][Z. Jiao]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.060 
     
Surface reconstruction of electrocatalysts is an effective strategy to modulate the space charge distribution to enhance the electrocatalytic activity. The p-n heterostructured FeP/CoP-2D octagonal nanoplates were successfully constructed by cation-exchange method. The space charge effect caused by the p-n heterojunction accelerated the electron transfer, optimized the electronic structure, and improved the activity of the active sites during the oxygen evolution reaction process. As a result, FeP/CoP-2D required only 247 mV overpotential to achieve a current density of 10 mA cm−2 with a Tafel slope as low as 68 mV dec-1. Density-functional theory calculations confirmed that the construction of p-n heterojunctions can enhance the adsorption of *OH in the active centers and optimize the Gibbs free energy of the OER reaction. This study provides an effective and feasible strategy for constructing p-n heterojunctions to modulate the space charge state for optimizing the OER performance of electrocatalysts.    

    

* Hierarchical FeO H @Ni3B hybrid for efficient alkaline oxygen evolution at high current density  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392714501
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.02.061")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392714501"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392714501"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392714501"))][Get cited by]]

OpenAlex: https://openalex.org/W4392714501 (Open access: False)
    
[[https://openalex.org/A5008664656][Fuxi Liu]], [[https://openalex.org/A5010682216][Qing Liang]], [[https://openalex.org/A5008795836][Zhenyu Li]], [[https://openalex.org/A5007669734][Meiqi Liu]], [[https://openalex.org/A5013227884][Nailin Yue]], [[https://openalex.org/A5033190410][Zizhun Wang]], [[https://openalex.org/A5056514565][Xu Zou]], [[https://openalex.org/A5071755732][Wei Zhang]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.02.061 
     
Electrocatalysts with high activity and long-term durability are vital toward large-scale hydrogen production from electrocatalytic water splitting. Here, the self-supported electrode (FeOxHy@Ni3B/NF) with hierarchical heterostructure was simply prepared by using Ni3B chunks grown on nickel foam as substrate to in situ form vertical FeOxHy nanosheets. Such hybrid shows efficient oxygen evolution reaction activity with overpotentials as low as 267 and 249 mV at 100 mA cm−2 in 1 M KOH solution and 30 wt% KOH solution, respectively. Meanwhile, it also exhibits excellent catalytic stability, sustaining catalysis at 500 mA cm−2 in 1 M KOH solution for 200 h, and even for 200 h at 1000 mA cm−2 in 30 wt% KOH solution. Further experimental results reveal that the FeOxHy@Ni3B/NF is endowed with superhydrophilic and superaerophobic surface properties, which not only provide more mass transport channels, as well as facilitated the diffusion of reaction intermediates and gas bubbles. Also, it holds faster reaction kinetics, more accessible active sites and accelerated electron transfer rates due to strong synergistic interactions at the heterogeneous interface.    

    

* NiFeLDH/Mo4/3B2-xTz/NF composite electrodes to enhance oxygen evolution performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392723773
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00834k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392723773"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392723773"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392723773"))][Get cited by]]

OpenAlex: https://openalex.org/W4392723773 (Open access: False)
    
[[https://openalex.org/A5031728975][Lulu Xu]], [[https://openalex.org/A5048150327][Ping Yang]], [[https://openalex.org/A5056876602][Rongbin Ye]], [[https://openalex.org/A5031397370][Xin Wu]], [[https://openalex.org/A5033402702][Yong Tao]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d4ta00834k 
     
A NiFeLDH /Mo4/3B2-xTz/NF (foam nickel) composite electrode was prepared by electrodepositing a layer of NiFe-layered hydroxides (NiFeLDH) on the Mo4/3B2-xTz /NF which was obtained by NF being soaked in two-dimensional...    

    

* A series of Isostructural Metal-Organic Frameworks for Enhanced Electro-catalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392741361
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dt00210e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392741361"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392741361"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392741361"))][Get cited by]]

OpenAlex: https://openalex.org/W4392741361 (Open access: False)
    
[[https://openalex.org/A5070860189][Pampa Jhariat]], [[https://openalex.org/A5032926378][Abdul Kareem]], [[https://openalex.org/A5056422496][Priyanka Kumari]], [[https://openalex.org/A5093368488][Shafeeq Sarfudeen]], [[https://openalex.org/A5067954187][Pravati Panda]], [[https://openalex.org/A5075161334][Sellappan Senthilkumar]], [[https://openalex.org/A5012686513][Tamas Panda]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d4dt00210e 
     
Three new isostructural MOFs (ZnTIA, CoTIA and CdTIA) were synthesized by the solvothermal synthesis of organic linker 5-triazole isophthalic acid (5-TIA) with the transition metals Zn(II), Co(II) and Cd(II) salts...    

    

* Constructing Oxygen Vacancies by Doping Mo into Spinel Co3O4 to Trigger Fast Oxide Path Mechanism for Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392844308
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00655k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392844308"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392844308"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392844308"))][Get cited by]]

OpenAlex: https://openalex.org/W4392844308 (Open access: False)
    
[[https://openalex.org/A5067063344][Xin Yue]], [[https://openalex.org/A5061849630][Li Sun]], [[https://openalex.org/A5003948701][Minghui Feng]], [[https://openalex.org/A5040317071][Yang Peng]], [[https://openalex.org/A5055838753][Chao Wang]], [[https://openalex.org/A5047061145][Yiye Shao]], [[https://openalex.org/A5058642281][Shaoming Huang]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d4ta00655k 
     
The development of non-precious metal electrocatalysts for the acidic oxygen evolution reaction (OER) that are highly durable, cost-effective, and efficient is crucial to advancing the use of proton exchange membrane...    

    

* Intermetallic Cobalt Indium Nanoparticles as Oxygen Evolution Reaction Precatalyst: A Non‐Leaching p‐Block Element  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392782764
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202309749")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392782764"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392782764"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392782764"))][Get cited by]]

OpenAlex: https://openalex.org/W4392782764 (Open access: True)
    
[[https://openalex.org/A5033292901][J. Niklas Hausmann]], [[https://openalex.org/A5052063617][Marten L. P. Ashton]], [[https://openalex.org/A5025002760][Stefan Mebs]], [[https://openalex.org/A5040951340][Carsten Walter]], [[https://openalex.org/A5083154124][Sören Selve]], [[https://openalex.org/A5008932544][Michael Haumann]], [[https://openalex.org/A5087747378][Tobias Sontheimer]], [[https://openalex.org/A5054018303][Holger Dau]], [[https://openalex.org/A5051647346][Matthias Drieß]], [[https://openalex.org/A5009720807][Prashanth W. Menezes]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202309749  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/smll.202309749][pdf]])
     
Abstract Merely all transition‐metal‐based materials reconstruct into similar oxyhydroxides during the electrocatalytic oxygen evolution reaction (OER), severely limiting the options for a tailored OER catalyst design. In such reconstructions, initial constituent p‐block elements take a sacrificial role and leach into the electrolyte as oxyanions, thereby losing the ability to tune the catalyst's properties systematically. From a thermodynamic point of view, indium is expected to behave differently and should remain in the solid phase under alkaline OER conditions. However, the structural behavior of transition metal indium phases during the OER remains unexplored. Herein, are synthesized intermetallic cobalt indium (CoIn 3 ) nanoparticles and revealed by in situ X‐ray absorption spectroscopy and scanning transmission microscopy that they undergo phase segregation to cobalt oxyhydroxide and indium hydroxide. The obtained cobalt oxyhydroxide outperforms a metallic‐cobalt‐derived one due to more accessible active sites. The observed phase segregation shows that indium behaves distinctively differently from most p‐block elements and remains at the electrode surface, where it can form lasting interfaces with the active metal oxo phases.    

    

* Metal Vacancies and Self-Reconstruction of High Entropy Metal Borates to Boost the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392840754
:TOPICS: Lithium Battery Technologies, Nuclear Fuel Development, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4736191")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392840754"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392840754"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392840754"))][Get cited by]]

OpenAlex: https://openalex.org/W4392840754 (Open access: False)
    
[[https://openalex.org/A5081085876][Mengyuan Zhang]], [[https://openalex.org/A5084711013][Kai Luo]], [[https://openalex.org/A5023895169][Yaning Fan]], [[https://openalex.org/A5001453501][Xiaoyan Lü]], [[https://openalex.org/A5032700450][Jian Ye]], [[https://openalex.org/A5071339229][Ning Liu]], [[https://openalex.org/A5070412038][Jie Dong]], [[https://openalex.org/A5072202821][Qiang Niu]], [[https://openalex.org/A5016528100][Junjun Zhang]], [[https://openalex.org/A5029804956][Pengfei Zhang]], [[https://openalex.org/A5018814519][Sheng Dai]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4736191 
     
No abstract    

    

* Ir metal nanoparticles and IrO2 for acidic oxygen evolution reaction: Insight from Raman spectroscopy  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392845191
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.susmat.2024.e00901")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392845191"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392845191"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392845191"))][Get cited by]]

OpenAlex: https://openalex.org/W4392845191 (Open access: True)
    
[[https://openalex.org/A5086588496][Léonard Moriau]], [[https://openalex.org/A5051420819][Mohammed Azeezulla Nazrulla]], [[https://openalex.org/A5067506046][Anja Lončar]], [[https://openalex.org/A5057907379][Luka Pavko]], [[https://openalex.org/A5059203752][Marjan Bele]], [[https://openalex.org/A5065843632][Nejc Hodnik]], [[https://openalex.org/A5029592401][Angelja Kjara Šurca]], Sustainable Materials and Technologies. None(None)] 2024. https://doi.org/10.1016/j.susmat.2024.e00901 
     
No abstract    

    

* Hierarchical cobalt-molybdenum layered double hydroxide arrays power efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392804986
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Polyoxometalate Clusters and Materials
:PUBLICATION_DATE: 2024-03-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12274-024-6529-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392804986"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392804986"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392804986"))][Get cited by]]

OpenAlex: https://openalex.org/W4392804986 (Open access: False)
    
[[https://openalex.org/A5021339843][Xinyi Zhu]], [[https://openalex.org/A5049385562][Jiahui Lyu]], [[https://openalex.org/A5055299862][Shanshan Wang]], [[https://openalex.org/A5071319290][Xingchuan Li]], [[https://openalex.org/A5072826155][Xiaoyü Wei]], [[https://openalex.org/A5038019595][Cheng Chen]], [[https://openalex.org/A5009397761][Wanida Koo‐Amornpattana]], [[https://openalex.org/A5050655757][Francis Verpoort]], [[https://openalex.org/A5020891991][Jianxin Wu]], [[https://openalex.org/A5005358046][Zongkui Kou]], Nano Research. None(None)] 2024. https://doi.org/10.1007/s12274-024-6529-1 
     
No abstract    

    

* Nickel-cobalt alloy oxide nanoparticles wrapped by carbon black for efficient oxygen evolution electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392791612
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131462")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392791612"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392791612"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392791612"))][Get cited by]]

OpenAlex: https://openalex.org/W4392791612 (Open access: False)
    
[[https://openalex.org/A5025713069][Bosheng Zhang]], [[https://openalex.org/A5053417225][Panchao Zhao]], [[https://openalex.org/A5028598891][Junqiu Guo]], [[https://openalex.org/A5082665603][Hemu Pi]], Fuel. 367(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131462 
     
No abstract    

    
