#+TITLE: water splitting
Description: water splitting papers
Created on Mon Apr  1 00:50:19 2024

Found 25 results from 2024-03-25 to 2024-04-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Preparation of NiFeCoMnCr Hydroxide on Nickel Foam by Corrosion Method and its Enhanced Electrochemical Performance in Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393130679
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-03-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11814-024-00160-y")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393130679"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393130679"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393130679"))][Get cited by]]

OpenAlex: https://openalex.org/W4393130679 (Open access: False)
    
[[https://openalex.org/A5024316673][Hyein Lee]], [[https://openalex.org/A5044838419][Min‐Ho Han]], [[https://openalex.org/A5064245264][Hee-Jin Noh]], [[https://openalex.org/A5008933483][Taekyung Yu]], Korean Journal of Chemical Engineering. None(None)] 2024. https://doi.org/10.1007/s11814-024-00160-y 
     
No abstract    

    

* Highly dispersed carbon-encapsulated FeS/Fe3C nanoparticles distributed in Fe-N-C for enhanced oxygen electrocatalysis and Zn-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393131844
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393131844"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393131844"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393131844"))][Get cited by]]

OpenAlex: https://openalex.org/W4393131844 (Open access: False)
    
[[https://openalex.org/A5016808540][Shuhui Sun]], [[https://openalex.org/A5008908523][Fan Yang]], [[https://openalex.org/A5010301533][Xiaoyun Zhang]], [[https://openalex.org/A5050938886][Jialin Qian]], [[https://openalex.org/A5079842107][Kexin Wei]], [[https://openalex.org/A5033923057][Ji Hun An]], [[https://openalex.org/A5003203596][Yang Sun]], [[https://openalex.org/A5080534131][Shuyang Wang]], [[https://openalex.org/A5056078581][Xi Li]], [[https://openalex.org/A5033201032][Yongfeng Li]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150673 
     
Transition metal single-atom catalysts (SACs) have been widely used in oxygen reduction reactions (ORR) and oxygen evolution reaction (OER) due to its greatest atomic utilization and low costs, which catalytic performance can be further enhanced by electron distribution adjustment. Herein, we synthesized a carbon-encapsulated FeS/Fe3C nanoparticles doped carbon-based Fe single atom catalyst from fluid catalytic cracking (FCC) slurry though a one-pot pyrolysis. The synergistic effect between FeS/Fe3C nanoparticles and Fe single atom structure (FeNx) promotes the ORR/OER processes, which may due to the reduction of the adsorption free energy of intermediates. Meanwhile, the polyaromatic hydrocarbon in FCC slurry enhances the graphitization of catalyst to facilitate charge transfer in electrocatalysis process, and the carbon-encapsulated nanoparticles sites possess higher stability and dispersion. As a result, the optimized catalyst (FeS/Fe3C@Fe-N-C) presents a high nanoparticles dispersion and graphitization level, which has a higher ORR catalytic ability (E1/2 = 0.91 V vs RHE) compared with commercial Pt/C (20 wt%, E1/2 = 0.879 V vs RHE) and a similar OER catalytic ability (E10 = 0.1.506 V vs RHE) compared with RuO2 (E10 = 1.518 V vs RHE). A liquid Zn-air battery assembled with FeS/Fe3C@Fe-N-C show a peak power density of 113 mW cm−2 and an open potential of 1.432 V. This work sheds light on a new method to design transition metal active sites carbon based single-atom catalyst for enhanced ORR and OER processes.    

    

* Dual-function CoP on nitrogen doped carbon framework with induced interfacial coupling for overall water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393136880
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104224")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393136880"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393136880"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393136880"))][Get cited by]]

OpenAlex: https://openalex.org/W4393136880 (Open access: False)
    
[[https://openalex.org/A5000282265][Manting Zhang]], [[https://openalex.org/A5075195590][Tingting Zhou]], [[https://openalex.org/A5070193556][Gang Huang]], [[https://openalex.org/A5066194422][Fengyan Han]], [[https://openalex.org/A5011385180][Huaiyu Shao]], [[https://openalex.org/A5029425717][Ting Hu]], [[https://openalex.org/A5034581450][Caiqin Wang]], Surfaces and Interfaces. 47(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104224 
     
Strong interfacial coupling in the hybrid catalysts could enhance catalytic performances. In this work, N, P were co-doped in zeolitic imidazolate framework-67 (ZIF-67) derived Co-based materials (denoted as CoP/NC) via in-situ carbonization and phosphating strategy, which accordingly induced strong interfacial coupling, leading to promote the catalytic activity in overall water splitting. In detail, the CoP/NC-2 presents the overpotential of 98 and 139 mV for hydrogen evolution reaction (HER) in 0.5 M H2SO4 and 1.0 M KOH at 10 mA cm−2, respectively, and 295 mV for oxygen evolution reaction (OER) in 1.0 M KOH at 20 mA cm−2, which is excellent during the non-noble metal-based catalysts. It also achieved a potential of 1.69 V (η20) in the overall water splitting. Density functional theory (DFT) based calculation reveals that the in-situ N, P co-doping induced strong interface coupling, which enhances the interaction in the interface of catalysts and improves electron conduction. More importantly, it contributes to adjusting electronic structure and d-band center, optimizing the adsorption energy for HER and/or OER and improving the kinetics of water splitting reaction. This work sheds new light on the heteroatom doping strategy to construct bifunctional transition metal-based electrocatalyst with boosting electrocatalytic performance in energy conversion application.    

    

* Unveiling the synergistic effect of amorphous CoW-phospho-borides for overall alkaline water electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393137824
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.090")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393137824"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393137824"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393137824"))][Get cited by]]

OpenAlex: https://openalex.org/W4393137824 (Open access: False)
    
[[https://openalex.org/A5031596947][Aniruddha Bhide]], [[https://openalex.org/A5023415473][Suraj Gupta]], [[https://openalex.org/A5093813426][Rinkoo Bhabal]], [[https://openalex.org/A5001090064][Kishan H. Mali]], [[https://openalex.org/A5018855602][B.R. Bhagat]], [[https://openalex.org/A5079181416][Alpa Dashora]], [[https://openalex.org/A5043158829][Maulik Patel]], [[https://openalex.org/A5059024873][R. Fernandes]], [[https://openalex.org/A5069531160][N. Patel]], International Journal of Hydrogen Energy. 63(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.090 
     
Amorphous transition-metal-phospho-borides (TMPBs) are emerging as a new class of hybrid bifunctional catalysts for water-splitting. The present work reports the discovery of CoWPB as a new promising material that adds to the smaller family of TMPBs. The optimized compositions, namely Co4WPB5 and Co2WPB1 could achieve 10 mA/cm2 at just 72 mV and 262 mV of overpotentials for hydrogen evolution reaction (HER) and oxygen evolution reaction (OER), respectively, in 1 M KOH. Furthermore, the catalyst showed good performance in a 2-electrode assembly (1.59 V for 10 mA/cm2) with considerable stability (70 h stability, 10,000 operating cycles). Detailed morphological and electrochemical characterizations unveiled insights into the role of all elements in catalyst's improved performance. The presence of W was found to be crucial in improving the electronic conductivity and charge redistribution, making CoWPB suitable for both HER and OER. In computational simulation analysis, two configurations with different atomic environments, namely, CoWPBH and CoWPBO were found to have the lowest calculated overpotentials for HER and OER, respectively. It was found that the surface P-sites in CoWPBH were HER-active while the Co-sites in CoWPBO were OER-active sites. The study presents new knowledge about active sites in such multi-component catalysts that will foster more advancement in the area of water electrolysis.    

    

* Ultrasound-Assisted Synthesis of High-Entropy Materials for Enhanced Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393142290
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/met14040384")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393142290"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393142290"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393142290"))][Get cited by]]

OpenAlex: https://openalex.org/W4393142290 (Open access: True)
    
[[https://openalex.org/A5059386082][Zhiyuan Wang]], [[https://openalex.org/A5064403506][Chengxu Zhang]], [[https://openalex.org/A5010776860][Yue Zhang]], [[https://openalex.org/A5027149538][Jue Hu]], Metals. 14(4)] 2024. https://doi.org/10.3390/met14040384  ([[https://www.mdpi.com/2075-4701/14/4/384/pdf?version=1711383336][pdf]])
     
High-entropy materials (HEMs) play a significant role in the electrocatalytic oxygen evolution reaction (OER) due to their unique properties. However, there are still challenges in the preparation of HEMs for OER catalysts. In this study, the FeCoNiMnCr catalyst is synthesized for the first time using the ultrasonic hydrothermal-sintering technique and exhibits excellent performance for OER electrocatalysis. There is an optimal ultrasonic hydrothermal time and power for achieving the best OER performance. The results demonstrate that the performance of FeCoNiMnCr catalysts prepared through ultrasonic hydrothermal sintering (US-FeCoNiMnCr) is significantly improved compared with the traditional hydrothermal-sintering method. The US-FeCoNiMnCr catalyst exhibits an overpotential of 228 mV at the current density of 10 mA cm−2 and a Tafel slope as low as 45.39 mV dec−1 in an alkaline medium. Moreover, the US-FeCoNiMnCr catalyst demonstrates remarkable stability in electrocatalytic OER with a minimal potential increase observed even after 48 h. This work not only provides valuable insights into high-entropy material synthesis, but also presents a powerful electrocatalyst for water electrolysis.    

    

* Iron Integration in Nickel Hydroxide Matrix vs Surface for Oxygen-Evolution Reaction: Where the Nernst Equation Does Not Work  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393144203
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.4c00604")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393144203"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393144203"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393144203"))][Get cited by]]

OpenAlex: https://openalex.org/W4393144203 (Open access: False)
    
[[https://openalex.org/A5020471931][Mohammad Saleh Ali Akbari]], [[https://openalex.org/A5047020055][Subhajit Nandy]], [[https://openalex.org/A5063597709][Keun Hwa Chae]], [[https://openalex.org/A5047640712][Mohammad Mahdi Najafpour]], The Journal of Physical Chemistry Letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.4c00604 
     
No abstract    

    

* Cerium Doping‐Induced Enrichment of Ni 3 S 4 Phase for Boosting Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393149499
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202400056")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393149499"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393149499"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393149499"))][Get cited by]]

OpenAlex: https://openalex.org/W4393149499 (Open access: False)
    
[[https://openalex.org/A5033205455][Chunqing Gao]], [[https://openalex.org/A5052550377][Lu Pan]], [[https://openalex.org/A5032245741][Hong Wang]], [[https://openalex.org/A5061008777][Hongyu Guo]], [[https://openalex.org/A5064804120][Saad Melhi]], [[https://openalex.org/A5046264812][Mohammed A. Amin]], [[https://openalex.org/A5086802047][Jianjian Lin]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202400056 
     
The development of low‐cost transition metal compounds with high‐performance for efficient oxygen evolution reaction (OER) is of great significance in promoting the development of electrocatalysis. In this study, a Ce‐doped Ni3S4 catalyst (Ce0.2‐Ni3S4) was synthesized through a one‐step solvothermal method, where the doped rare earth element Ce induced the transformation of NiS to Ni3S4. The Ce0.2‐Ni3S4 catalyst exhibited excellent OER performance in 1 M KOH. At a current density of 10 mA cm‐2, it showed a low overpotential of 230 mV and a low Tafel slope of 52.39 mV dec‐1. Long‐term OER tests at the same potential lasted for 24 h without significant loss of current density. This work introduces a novel method of Ce element doping for modifying transition metal sulfides, providing new insights into the effective utilization of rare earth elements in the field of electrochemistry. It creates more chances for the progress of highly efficient catalysts for efficient OER, contributing to the advancement of electrocatalysis.    

    

* Self-Supported CoSe2 Nanorods for Efficient Oxygen Evolution and Urea Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393158032
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.3c05856")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393158032"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393158032"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393158032"))][Get cited by]]

OpenAlex: https://openalex.org/W4393158032 (Open access: False)
    
[[https://openalex.org/A5073479438][Ke Zhao]], [[https://openalex.org/A5038328764][Xiao Chen]], [[https://openalex.org/A5045527589][Haixia Liu]], [[https://openalex.org/A5025592561][Jianfeng Wang]], [[https://openalex.org/A5001063931][Jie Zhang]], ACS Applied Nano Materials. None(None)] 2024. https://doi.org/10.1021/acsanm.3c05856 
     
It is important for the practical application of water electrolysis to explore stable and earth-rich bifunctional catalysts for oxygen evolution reaction (OER) and urea oxidation reaction (UOR). An immersion-selenization strategy was proposed to prepare CoSe2/Co nanorods anchored on Co foam as bifunctional catalysts for OER and UOR. Due to the self-supported properties of CoSe2/Co and its unique nanorod structure, the OER activity is enhanced, showing an overpotential of 318 mV and a Tafel slope of 91.11 mV dec–1. In addition, the electrode showed excellent electrocatalytic UOR activity with an overpotential of 260 mV and a Tafel slope of 94.83 mV dec–1. The nanorod structure was basically retained after a 28 h durability test. This work provides a broad approach to the development of low-cost bifunctional electrocatalysts.    

    

* Interface Engineering of Electrocatalysts for Efficient and Selective Oxygen Evolution in Alkaline/Seawater  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393161543
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400125")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393161543"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393161543"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393161543"))][Get cited by]]

OpenAlex: https://openalex.org/W4393161543 (Open access: True)
    
[[https://openalex.org/A5033309633][Dae-Kyu Kim]], [[https://openalex.org/A5055769349][Wenhan Zu]], [[https://openalex.org/A5082292067][Cheuk S. Kwok]], [[https://openalex.org/A5028129738][Yoon Suk Lee]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400125  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cctc.202400125][pdf]])
     
Electrochemical water splitting is regarded as an effective technology for producing green hydrogen, which is crucial for addressing energy and environmental challenges. In particular, direct seawater splitting offers significant economic and environmental advantages. However, its efficiency is hindered by the high overpotential required for the oxygen evolution reaction (OER) and the competition from chloride oxidation. This review highlights the potential of interface engineering to overcome these limitations and develop efficient OER electrocatalysts. We comprehensively explore recent advancements in interface engineering for OER in both alkaline and seawater environments. We begin by introducing the mechanisms of freshwater and seawater electrolysis, emphasizing key considerations for OER catalyst design. Subsequently, we review the recent progress made in various interface engineering strategies, analyzing their impact on OER performance in both electrolytes. Finally, we outline promising future directions for developing efficient seawater oxidation catalysts through interface engineering.    

    

* Fabrication of nanocrystalline high-entropy oxide CoNiFeCrMnOx thin film electrodes by dip-coating for oxygen evolution electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393170112
:TOPICS: Electrocatalysis for Energy Conversion, High-Entropy Alloys: Novel Designs and Properties, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ya00026a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393170112"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393170112"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393170112"))][Get cited by]]

OpenAlex: https://openalex.org/W4393170112 (Open access: True)
    
[[https://openalex.org/A5004982680][Qingyin Wu]], [[https://openalex.org/A5092416365][Achim Alkemper]], [[https://openalex.org/A5058407349][Stefan Lauterbach]], [[https://openalex.org/A5039183696][Jan P. Hofmann]], [[https://openalex.org/A5076962213][Marcus Einert]], Energy advances. None(None)] 2024. https://doi.org/10.1039/d4ya00026a  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ya/d4ya00026a][pdf]])
     
Nanocrystalline high-entropy CoNiFeCrMnO x thin films were prepared by dip-coating and annealing at 400 °C, showing stable oxygen evolution with overpotentials of 258 mV vs. RHE at 10 mA cm −2 over 10 hours in alkaline media.    

    

* Iron-doped cobalt phosphide nanowires prepared via one-step solvothermal phosphidization of metal–organic frameworks for the oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393170501
:TOPICS: Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4gc00132j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393170501"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393170501"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393170501"))][Get cited by]]

OpenAlex: https://openalex.org/W4393170501 (Open access: False)
    
[[https://openalex.org/A5038487257][Jianbo Tong]], [[https://openalex.org/A5044626392][Yichuang Xing]], [[https://openalex.org/A5075441298][Xuechun Xiao]], [[https://openalex.org/A5010274839][Yuan Liu]], [[https://openalex.org/A5043199080][Zhiping Hu]], [[https://openalex.org/A5015077424][Zeyi Wang]], [[https://openalex.org/A5028748116][Yafei Hu]], [[https://openalex.org/A5086324364][B. Xin]], [[https://openalex.org/A5010940638][Shuling Liu]], [[https://openalex.org/A5021471823][He Wang]], [[https://openalex.org/A5061165588][Chao Wang]], Green Chemistry. None(None)] 2024. https://doi.org/10.1039/d4gc00132j 
     
A solvothermal phosphidization method is adopted to construct CoFeP nanowires to electrochemically catalyze oxygen evolution reaction.    

    

* Fe2W18Fe4@MOF-Ni-100 nanocomposite: Insights into synthesis and application as a promising material towards the electrocatalytic water oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393178854
:TOPICS: Polyoxometalate Clusters and Materials, Nanomaterials with Enzyme-Like Characteristics, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apt.2024.104380")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393178854"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393178854"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393178854"))][Get cited by]]

OpenAlex: https://openalex.org/W4393178854 (Open access: False)
    
[[https://openalex.org/A5012325638][Mohammad Ali Rezvani]], [[https://openalex.org/A5065079404][Hadi Hassani Ardeshiri]], [[https://openalex.org/A5021132490][Hossein Ghafuri]], [[https://openalex.org/A5036550735][Nasrin Khalafi]], Advanced Powder Technology. 35(4)] 2024. https://doi.org/10.1016/j.apt.2024.104380 
     
In this research, a new nanocomposite was synthesized via the sol–gel method by encapsulation of tetranuclear sandwich-type hetropolyanion (Na9K[(FeW9O34)2Fe4(H2O)2].32H2O, abbreviated as Fe2W18Fe4, on the surface of MOF-Ni-100 for the first time. The as-prepared nanocomposite (Fe2W18Fe4@MOF-Ni-100) was examined using different microscopy and spectroscopy techniques, including FT-IR, UV–vis, XRD, SEM, EDX, and BET techniques. The assembled Fe2W18Fe4@MOF-Ni-100 nanocomposite served as a potential heterogeneous catalyst in the water oxidation process for the purpose of oxygen evolution reaction (OER) at neutral pH conditions (N2-saturated 0.1 M Na2SO4). The electrochemical characteristics of the Fe2W18Fe4@MOF-Ni-100 nanocomposite was assessed through cyclic voltammetry (CV), linear sweep voltammetry (LSV), and electrochemical impedance spectroscopy (EIS) methods. The desired nanocatalyst displayed a low onset potential of 1.1 V vs. NHE and low overpotential of 269 mV at a current density (j) of 10 mAĊcm−2 with a Tafel slope of 73 mV.dec−1 (pH = 7). Furthermore, the Fe2W18Fe4@MOF-Ni-100 nanocomposite exhibited remarkable stability and retained its catalytic activity even after 200 catalytic cycles.    

    

* FeCoNiMgB high-entropy boride powder with a fluffy cotton structure and enhanced activity in the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393167181
:TOPICS: High-Entropy Alloys: Novel Designs and Properties, Synthesis and Properties of Cemented Carbides, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jmrt.2024.03.158")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393167181"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393167181"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393167181"))][Get cited by]]

OpenAlex: https://openalex.org/W4393167181 (Open access: True)
    
[[https://openalex.org/A5008386681][Fang Miao]], [[https://openalex.org/A5086015921][Peng Cui]], [[https://openalex.org/A5076776353][Zhiyuan Jing]], [[https://openalex.org/A5045957625][Wei Wu]], [[https://openalex.org/A5032499056][Zhibin Zhang]], [[https://openalex.org/A5062120914][Tingyue Gu]], [[https://openalex.org/A5014086269][Zhijie Yan]], [[https://openalex.org/A5071481252][Xiubing Liang]], Journal of Materials Research and Technology. None(None)] 2024. https://doi.org/10.1016/j.jmrt.2024.03.158 
     
Exploring efficient, low-cost electrocatalysts is critical for improving the efficiency of water splitting reactions. Noble-metal-based oxides exhibit high activities in the oxygen evolution reaction (OER). However, their high cost and the lack of natural resources hinder their practical application. Therefore, in this study, we successfully synthesized an FeCoNiMgB high-entropy boride powder via a facile chemical reduction method for use as an OER catalyst in an alkaline medium. The FeCoNiMgB powder, with an ultrathin fluffy cotton structure, exhibited an excellent OER catalytic performance, affording an overpotential of 268 mV at a current density of 10 mA/cm2 and a low Tafel slope of 42.9 mV/dec; this performance was superior to those of FeCoNiB, FeNiMgB, CoNiMgB, FeCoMgB, and commercial RuO2. The FeCoNiMgB powder also displayed remarkably stable catalytic properties for >72 h with no clear evidence of degradation. Finally, using theoretical calculations, the excellent OER performance of FeCoNiMgB was verified in terms of its adsorption and charge transfer energies and covalence. The performance and stability of FeCoNiMgB were equivalent or superior to those of several nanostructured catalysts, and thus, this study provided valuable insight into the design of efficient high-entropy boride materials.    

    

* Catalysis of the Oxygen-Evolution Reaction in 1.0 M Sulfuric Acid by Manganese Antimonate Films Synthesized via Chemical Vapor Deposition  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393164139
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.4c00135")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393164139"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393164139"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393164139"))][Get cited by]]

OpenAlex: https://openalex.org/W4393164139 (Open access: True)
    
[[https://openalex.org/A5003944273][Jacqueline A. Dowling]], [[https://openalex.org/A5047222245][Zachary P. Ifkovits]], [[https://openalex.org/A5016781712][Azhar I. Carim]], [[https://openalex.org/A5036811504][Jake M. Evans]], [[https://openalex.org/A5094241868][Madeleine C. Swint]], [[https://openalex.org/A5073978538][Alexandre Z. Ye]], [[https://openalex.org/A5072433173][Matthias H. Richter]], [[https://openalex.org/A5026118086][A. Li]], [[https://openalex.org/A5015008318][Nathan S. Lewis]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.4c00135  ([[https://pubs.acs.org/doi/pdf/10.1021/acsaem.4c00135][pdf]])
     
Manganese antimonate (MnySb1–yOx) electrocatalysts for the oxygen-evolution reaction (OER) were synthesized via chemical vapor deposition. Mn-rich rutile Mn0.63Sb0.37Ox catalysts on fluorine-doped tin oxide (FTO) supports drove the OER for 168 h (7 days) at 10 mA cm–2 with a time-averaged overpotential of 687 ± 9 mV and with >97% Faradaic efficiency. Time-dependent anolyte composition analysis revealed the steady dissolution of Mn and Sb. Extended durability analysis confirmed that Mn-rich MnySb1–yOx materials are more active but dissolve at a faster rate than previously reported Sb-rich MnySb1–yOx alloys.    

    

* Enhancing the steam electrolysis by simultaneously regulating the electron and oxygen ion conductivity of la1-xsr1+xfeo4-δ oxides  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393136727
:TOPICS: Solid Oxide Fuel Cells, Magnetocaloric Materials Research, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.234388")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393136727"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393136727"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393136727"))][Get cited by]]

OpenAlex: https://openalex.org/W4393136727 (Open access: False)
    
[[https://openalex.org/A5023603373][Changyang Liu]], [[https://openalex.org/A5041542637][Liuzhen Bian]], [[https://openalex.org/A5040953944][Ting Ting]], [[https://openalex.org/A5056498578][Pengyu Wei]], [[https://openalex.org/A5090989509][Yang Xu]], [[https://openalex.org/A5024830909][Wei Han]], [[https://openalex.org/A5029639649][Liang Yang]], [[https://openalex.org/A5057763747][Jun Peng]], [[https://openalex.org/A5076472848][Shengli An]], Journal of Power Sources. 602(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.234388 
     
Ruddlesden-Popper (RP) La1-xSr1+xFeO4-δ(x = 0,0.2,0.4) oxides with different Sr content are investigated as air electrodes for solid oxide electrolytic cells. The increased Sr content in La1-xSr1+xFeO4-δ significantly improves the electronic and oxygen ionic conductivity, enhancing the oxygen evolution reaction (OER) activity and electrochemical performance of steam electrolysis. The polarization resistance of the La0.8Sr1.2FeO4-δ symmetrical cell reaches 1.04 Ω cm2 at 800 °C, and the electrolysis cell delivers a current density of −1709 mA cm−2 at 1.3 V, corresponding to the hydrogen production rates of 714 ml/(cm2 h). Moreover, adding Sm0.2Ce0.8O2-δ (SDC) oxide further improves the steam electrolysis performance due to enhanced three-phase boundary active sites. The electrolysis cell with La0.8Sr1.2FeO4-δ-SDC electrode exhibits excellent stability for over 200 h and cycling durability for 100 h under 750 °C and 1.2 V in 50%H2O–H2 condition.    

    

* Development of unsupported IrO2 nano-catalysts for polymer electrolyte membrane water electrolyser applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393176859
:TOPICS: Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-03-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.17159/sajs.2024/16026")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393176859"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393176859"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393176859"))][Get cited by]]

OpenAlex: https://openalex.org/W4393176859 (Open access: False)
    
[[https://openalex.org/A5019400343][Simoné Karels]], [[https://openalex.org/A5025722881][Cecil Felix]], [[https://openalex.org/A5038199582][Sivakumar Pasupathi]], South African Journal of Science. 120(3/4)] 2024. https://doi.org/10.17159/sajs.2024/16026 
     
IrO2 is a current state-of-the-art catalyst for polymer electrolyte membrane water electrolyser (PEMWE) applications due to its high stability during the oxygen evolution reaction (OER). However, its activity needs to be significantly improved to justify the use of such a high-cost material. In this study, the activity of the IrO2 catalyst was improved by optimising and comparing two synthesis methods: the modified Adams fusion method (MAFM) and the molten salt method (MSM). Optimum OER performances of the IrO2 catalysts synthesised with the two synthesis methods were obtained at different temperatures. For the MAFM, a synthesis temperature of 350 °C produced the IrO2 catalyst with an overpotential of 279 mV and the highest OER stability of ~ 82 h at 10 mAcm−2. However, for the MSM, the lowest overpotential of 271 mV was observed for IrO2 synthesised at 350 °C, while the highest stability of ~ 75 h was obtained for the IrO2 synthesised at 500 °C.    

    

* Coupling NiFe-MOF with antiperovskite nickel-based nitrides as efficient electrocatalysts for overall water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393167184
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.rinp.2024.107611")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393167184"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393167184"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393167184"))][Get cited by]]

OpenAlex: https://openalex.org/W4393167184 (Open access: True)
    
[[https://openalex.org/A5091298536][Aixia Zhou]], [[https://openalex.org/A5003490528][Dongpo Song]], [[https://openalex.org/A5091792744][Zhenzhen Hui]], [[https://openalex.org/A5084731400][Jundi Yang]], [[https://openalex.org/A5016162807][Wei An]], [[https://openalex.org/A5055516463][Xuzhong Zuo]], [[https://openalex.org/A5088600147][Xiangju Ye]], [[https://openalex.org/A5061693363][Miaomiao Jiang]], Results in Physics. None(None)] 2024. https://doi.org/10.1016/j.rinp.2024.107611 
     
The exploration of high-performance, durable and cost-effective catalysts for overall water splitting, including the hydrogen evolution reaction (HER) and the oxygen evolution reaction (OER), has always been a vibrant topic in electrochemical water splitting techniques. Here we report a facile strategy for the synthesis of antiperovskite bimetallic nitrides (FeNNi3 and CuNNi3) and their NiFe-MOF morphology on nickel foams (NF) for HER and OER respectively in alkaline media. The NiFe-MOF and FeNNi3 nanoparticle exhibit strong coupling and synergistic effects, resulting in a solid integrated structure and fast electron transfer. The FeNNi3 towards HER shows an overpotential of 57 mV at 10 mA cm−2 in alkaline media, and its MOF morphology shows a low overpotential of 219 mV at 10 mA cm−2 towards OER. The alkaline electrolyzer of FeNNi3/NF || NiFe-MOF@FeNNi3/NF for overall water splitting demonstrates a low cell voltage of 1.49 V at 10 mA cm−2 with high cycling durability. This work investigates antiperovskite nitrides' capabilities for overall water splitting and provides guidance on designing high-performance catalytic materials.    

    

* Experimental characterization and non-isothermal simulation of a zero-gap alkaline electrolyser with nickel-iron porous electrode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393176804
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.145")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393176804"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393176804"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393176804"))][Get cited by]]

OpenAlex: https://openalex.org/W4393176804 (Open access: False)
    
[[https://openalex.org/A5019253282][Menghua Liu]], [[https://openalex.org/A5061084605][Shuang Li]], [[https://openalex.org/A5051893179][Yixiang Shi]], [[https://openalex.org/A5047913997][Ningsheng Cai]], International Journal of Hydrogen Energy. 63(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.145 
     
The availability of self-supported porous electrodes with excellent hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) catalytic activity has been an important cornerstone for the performance of alkaline water electrolysers (AWEs). In addition, the management of heat and two-phase flow during ion/electron transfer in porous electrodes poses significant challenges to the stable operation of AWE electrolysers. In this work, a two-dimensional non-isothermal multiphysical model considering two-phase flow, mass, heat and charge transfer processes is developed based on COMSOL Multiphysics and well validated with reliable experimental data. The model exhibits excellent agreement with actual electrolyser operating voltages between 323–343 K, and the relative error is within acceptable 2.2% even at high current densities up to 1.5 A cm−2. In addition, the electrode kinetic data obtained based on standard three-electrode experiments allow the model to predict the corresponding HER and OER overpotentials of the porous electrodes with great accuracy, as well as to obtain the distribution of temperature and ionic species inside the porous electrodes under various volumetric flow rates and current densities. This work provides a practical and reliable guide for the design of porous electrodes and the performance enhancement of electrolysers from both experimental and simulation perspectives.    

    

* Recent Developments in Two-Dimensional Carbon-Based Nanomaterials for Electrochemical Water Oxidation: A Mini Review  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393163615
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14040221")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393163615"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393163615"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393163615"))][Get cited by]]

OpenAlex: https://openalex.org/W4393163615 (Open access: True)
    
[[https://openalex.org/A5087168333][Yijiang Zhao]], [[https://openalex.org/A5017593937][Siyuan Niu]], [[https://openalex.org/A5094241802][Baichuan Xi]], [[https://openalex.org/A5066285234][Zurong Du]], [[https://openalex.org/A5074617036][Ting Yu]], [[https://openalex.org/A5064178282][Tongtao Wan]], [[https://openalex.org/A5004469684][Chaojun Lei]], [[https://openalex.org/A5077784535][Siliu Lyu]], Catalysts. 14(4)] 2024. https://doi.org/10.3390/catal14040221  ([[https://www.mdpi.com/2073-4344/14/4/221/pdf?version=1711376406][pdf]])
     
Water splitting is considered a renewable and eco−friendly technique for future clean energy requirements to realize green hydrogen production, which is, to a large extent, hindered by the oxygen evolution reaction (OER) process. In recent years, two−dimensional (2D) carbon−based electrocatalysts have drawn sustained attention owing to their good electrical conductivity, unique physicochemical properties, and excellent electrocatalytic performance. Particularly, it is easy for 2D carbon−based materials to form nanocomposites, which further provides an effective strategy for electrocatalytic applications. In this review, we discuss recent advances in synthetic methods, structure−property relationships, and a basic understanding of electrocatalytic mechanisms of 2D carbon−based electrocatalysts for water oxidation. In detail, precious, non−precious metal−doped, and non−metallic 2D carbon−based electrocatalysts, as well as 2D carbon−based confined electrocatalysts, are introduced to conduct OER. Finally, current challenges, opportunities, and perspectives for further research directions of 2D carbon−based nanomaterials are outlined. This review can provide significant comprehension of high−performance 2D carbon−based electrocatalysts for water-splitting applications.    

    

* Effective development and utilization of SILAR-assisted TiO2 and CsPb2Br5 nanocomposites for photochemical and biological cleaning of environment  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393132197
:TOPICS: Perovskite Solar Cell Technology, Upconversion Nanoparticles, Laser Cooling of Solids to Cryogenic Temperatures
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.03.234")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393132197"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393132197"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393132197"))][Get cited by]]

OpenAlex: https://openalex.org/W4393132197 (Open access: False)
    
[[https://openalex.org/A5065993854][Mamoona Yasmeen]], [[https://openalex.org/A5029491639][Syeda Ammara Batool]], [[https://openalex.org/A5059163435][Syed Imran Abbas Shah]], [[https://openalex.org/A5061069978][Muhammad Naeem Ashiq]], [[https://openalex.org/A5017634684][Muhammad Atiq Ur Rehman]], [[https://openalex.org/A5006739182][Abdul Khaliq]], [[https://openalex.org/A5038040617][Tayyab Subhani]], [[https://openalex.org/A5021767343][Mohamed Ramadan]], [[https://openalex.org/A5055734568][Muhammad Abdul Basit]], Ceramics International. None(None)] 2024. https://doi.org/10.1016/j.ceramint.2024.03.234 
     
Recently, cesium lead halide perovskites such as CsPb2Br5 and CsPbBr3 have drawn the attention of researchers because of their unique optical, electronic, and chemical properties. To improve the photo and/or chemical performance of such CsPb2Br5 (termed as CPB hereafter), we have realized multiple facile routes for its combination with UV-active TiO2 nanoparticles. Resultantly developed binary nanocomposites of TiO2, CPB perovskites and TiO2/CPB-nanocomposite (TiO2/CPB-NC) offered a meaningful photochemical contrast between pseudo-successive ionic layer adsorption and reaction (p-SILAR) and electrostatic self-assembly methods for targeting photocatalytic degradation of toxic dyes under solar irradiation and resulted significant performance as reactant for oxygen evolution (OER) as revealed by extensive electrochemical impedance spectroscopy (EIS). In parallel to extensive material-based characterization using SEM, XRD, and UV Vis. etc, the study was further extended to the theoretical investigation of the structure of CsPb2Br5, and antibacterial activity against gram-positive and gram-negative bacteria namely Escherichia coli (E. coli) and Staphylococcus aureus (S. aureus). RhB degradation of TiO2 increased from 13% to 58% by deposition of CPB, in parallel to 100% inhabitation zone growth.    

    

* Hydrogen Production via Electrolysis of Wastewater  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393161111
:TOPICS: Hydrogen Energy Systems and Technologies, Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/nano14070567")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393161111"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393161111"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393161111"))][Get cited by]]

OpenAlex: https://openalex.org/W4393161111 (Open access: True)
    
[[https://openalex.org/A5082797357][Lijun Huang]], [[https://openalex.org/A5041429156][Chaoqiong Fang]], [[https://openalex.org/A5091685833][Ting Pan]], [[https://openalex.org/A5088499834][Quing Zhu]], [[https://openalex.org/A5094241395][Tiangeng Geng]], [[https://openalex.org/A5033895107][Guixiang Li]], [[https://openalex.org/A5035339773][Xiao Li]], [[https://openalex.org/A5074653939][Jiayuan Yu]], Nanomaterials. 14(7)] 2024. https://doi.org/10.3390/nano14070567  ([[https://www.mdpi.com/2079-4991/14/7/567/pdf?version=1711357116][pdf]])
     
The high energy consumption of traditional water splitting to produce hydrogen is mainly due to complex oxygen evolution reaction (OER), where low-economic-value O2 gas is generated. Meanwhile, cogeneration of H2 and O2 may result in the formation of an explosive H2/O2 gas mixture due to gas crossover. Considering these factors, a favorable anodic oxidation reaction is employed to replace OER, which not only reduces the voltage for H2 production at the cathode and avoids H2/O2 gas mixture but also generates value-added products at the anode. In recent years, this innovative strategy that combines anodic oxidation for H2 production has received intensive attention in the field of electrocatalysis. In this review, the latest research progress of a coupled hydrogen production system with pollutant degradation/upgrading is systematically introduced. Firstly, wastewater purification via anodic reaction, which produces free radicals instead of OER for pollutant degradation, is systematically presented. Then, the coupled system that allows for pollutant refining into high-value-added products combined with hydrogen production is displayed. Thirdly, the photoelectrical system for pollutant degradation and upgrade are briefly introduced. Finally, this review also discusses the challenges and future perspectives of this coupled system.    

    

* Synergistic strategy of solute environment and phase control of Pb-based anodes to solve the activity-stability trade-off  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393131831
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jhazmat.2024.134119")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393131831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393131831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393131831"))][Get cited by]]

OpenAlex: https://openalex.org/W4393131831 (Open access: False)
    
[[https://openalex.org/A5011949501][Siwei Zhuang]], [[https://openalex.org/A5054325872][Ning Duan]], [[https://openalex.org/A5088196965][Linhua Jiang]], [[https://openalex.org/A5015922796][Fang Xu]], Journal of Hazardous Materials. None(None)] 2024. https://doi.org/10.1016/j.jhazmat.2024.134119 
     
The contradiction between the activity and stability of metal anodes exists extensively, especially in acid electrooxidation under industrial-level current density. Although the anode modification enhanced the initial activity of anodes, its long-term activity is limited by anode slime accumulation. Herein, a synergistic strategy, coupling the solute environment with the phase control of anodes, is proposed to achieve the trade-off between activity and stability of Pb-based anodes in concentrated sulfuric acid electrolysis. Non-exogenous Mn2+ motivated a series of positive behaviours of reactive-oxygen-species capture, anode reconstruction and corrosion-dependent activity alleviation. The synergistic effects, which are crystal phase-dependent, mainly benefit from the continuous self-healing ability of the specific crystal phase of MnO2 on the anodes by the coexisted Mn2+. Compared with Mn2+/α-MnO2, Mn2+/γ-MnO2 exhibited outperformed activity and stability in boosting oxygen evolution reaction (OER) and reducing hazardous pollutants, which resulted from the energy difference in the rate-determining step of OER and in the selectivity priority of Mn2+/MnO2 oxidation pathway. Interestingly, the pre-coated γ-MnO2 on the anode also presents excellent inheritance, guaranteeing the unchanged crystal phase of MnO2 and the high performance in ultra-low hazardous slime generation in subsequent Mn2+ oxidation. The sustainability of Mn2+/γ-MnO2 was proved in the operating hydrometallurgy conditions on Pb-based anodes. This strategy offers a promising approach for this common issue in electrooxidation-related areas.    

    

* Bifunctional Mo4O11 Nanosheets-Engineered Co-Ni alloy nanowires enable High-Efficiency seawater electrolysis and Zn-Seawater battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393131615
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150664")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393131615"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393131615"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393131615"))][Get cited by]]

OpenAlex: https://openalex.org/W4393131615 (Open access: False)
    
[[https://openalex.org/A5025944641][Muhaiminul Islam]], [[https://openalex.org/A5077411994][Sambedan Jena]], [[https://openalex.org/A5093549463][Saleem Sidra]], [[https://openalex.org/A5068920211][Joong Hee Lee]], [[https://openalex.org/A5022726594][Do Hwan Kim]], [[https://openalex.org/A5008014896][Nam Hoon Kim]], [[https://openalex.org/A5068920211][Joong Hee Lee]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150664 
     
This study reports an electrocatalyst derived from multi-valent Mo4O11 nanosheets coupled Co-Ni (CN) nanowires (NW) (denoted as CN@Mo4O11) with improved catalytic coherency for both high-performance seawater splitting and Zn-seawater battery. The CN@Mo4O11 material significantly enhances the catalytical activity with a low overpotential of 63 mV/69 mV for hydrogen evolution and 100 mV/120 mV for oxygen evolution, respectively, to attain 10 mA cm−2 in alkaline freshwater/seawater. An electrolyzer cell of CN@Mo4O11(+,-) exhibits a low cell voltage of 1.40 V/1.44 V at 10 mA‧cm−2 during alkaline freshwater/seawater splitting with an excellent performance retention of 98.6 %/97.6 % after a long-term operation for 50 h. The solar cell coupled electrolyzer also delivers a high solar to hydrogen conversion efficiency of 15.54 %/16.1 % in alkaline freshwater/seawater. A Zn-seawater battery based on CN@Mo4O11 cathode also delivers high current and power densities of 82 mA‧cm−2 and 27.6 mW‧cm−2, respectively, with a stable discharge time of 40 h. The CN@Mo4O11 heterostructure imparts favorable density of states and optimized adsorption energy for HER and OER, as deduced from DFT calculations, leading to improved overall catalytic performance and corrosion resistance in seawater. Results of this work clearly prove that this proposed catalyst architecture indeed has a huge potential for both seawater splitting and Zn-seawater battery fabrication.    

    

* Large-area, flexible bimetallic phosphorus-based electrodes for prolong-stable industrial grade overall seawater splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393129800
:TOPICS: Science and Technology of Capacitive Deionization for Water Desalination, Advanced Oxidation Processes for Water Treatment, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150624")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393129800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393129800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393129800"))][Get cited by]]

OpenAlex: https://openalex.org/W4393129800 (Open access: False)
    
[[https://openalex.org/A5033334181][Xiang Ma]], [[https://openalex.org/A5048586382][Rikai Liang]], [[https://openalex.org/A5037335239][Yiming Wang]], [[https://openalex.org/A5030824072][Lijun Wu]], [[https://openalex.org/A5071444732][Fengjing Lei]], [[https://openalex.org/A5011581422][Jinchen Fan]], [[https://openalex.org/A5081945932][Lincai Wang]], [[https://openalex.org/A5009156159][Weiju Hao]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150624 
     
The economical and efficient preparation of highly stable electrodes for hydrogen from water splitting is one of the current challenges. Herein, a flexible and durable bifunctional nickel–cobalt-phosphide electrode is constructed in situ on hydrophilicity filter paper (NiCoP@HP) via a one-step mild electroless plating method for industrial-scale water splitting. The bimetallic synergy of Ni-Co facilitates efficient electron transfer, while the electronegativity of phosphide contributes to high intrinsic activity, and the flexible paper substrate allow the electrode to be folded and bent. The NiCoP@HP electrodes exhibit outstanding performance for the hydrogen/oxygen evolution reaction (HER/OER), with low overpotentials only 43 mV and 164 mV at a current density of 10 mA cm−2 in simulated seawater (1.0 M KOH + 0.5 M NaCl). Importantly, the NiCoP@HP electrode demonstrates long-term stability, operating for over 1440 h at a current density of 500 mA cm−2 in 1.0 M KOH + 0.5 M NaCl and 1.0 M KOH + Seawater, respectively. This universally applicable method allows the preparation of a range of highly efficient catalytic electrodes (Fe, Mo, W etc.). This work provides a simple, scalable, and versatile approach for the in situ construction of noble metal-free, highly efficient, and cost-effective bifunctional electrocatalysts, opening new possibilities for industrial-scale water splitting.    

    

* Role of Electrolyte pH on Water Oxidation for Iridium Oxides  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393157935
:TOPICS: Perovskite Solar Cell Technology, Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.3c12011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393157935"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393157935"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393157935"))][Get cited by]]

OpenAlex: https://openalex.org/W4393157935 (Open access: True)
    
[[https://openalex.org/A5026417092][Caiwu Liang]], [[https://openalex.org/A5059373986][Yu Katayama]], [[https://openalex.org/A5083338093][Yemin Tao]], [[https://openalex.org/A5078147814][Asuka Morinaga]], [[https://openalex.org/A5005889599][Benjamin Moss]], [[https://openalex.org/A5020884368][Verónica Celorrio]], [[https://openalex.org/A5038499496][Mary P. Ryan]], [[https://openalex.org/A5039064548][Ifan E. L. Stephens]], [[https://openalex.org/A5086035043][James R. Durrant]], [[https://openalex.org/A5027366818][Reshma R. Rao]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.3c12011  ([[https://pubs.acs.org/doi/pdf/10.1021/jacs.3c12011][pdf]])
     
Understanding the effect of noncovalent interactions of intermediates at the polarized catalyst–electrolyte interface on water oxidation kinetics is key for designing more active and stable electrocatalysts. Here, we combine operando optical spectroscopy, X-ray absorption spectroscopy (XAS), and surface-enhanced infrared absorption spectroscopy (SEIRAS) to probe the effect of noncovalent interactions on the oxygen evolution reaction (OER) activity of IrOx in acidic and alkaline electrolytes. Our results suggest that the active species for the OER (Ir4.x+–*O) binds much stronger in alkaline compared with acid at low coverage, while the repulsive interactions between these species are higher in alkaline electrolytes. These differences are attributed to the larger fraction of water within the cation hydration shell at the interface in alkaline electrolytes compared to acidic electrolytes, which can stabilize oxygenated intermediates and facilitate long-range interactions between them. Quantitative analysis of the state energetics shows that although the *O intermediates bind more strongly than optimal in alkaline electrolytes, the larger repulsive interaction between them results in a significant weakening of *O binding with increasing coverage, leading to similar energetics of active states in acid and alkaline at OER-relevant potentials. By directly probing the electrochemical interface with complementary spectroscopic techniques, our work goes beyond conventional computational descriptors of the OER activity to explain the experimentally observed OER kinetics of IrOx in acidic and alkaline electrolytes.    

    
