#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Fri Feb  2 00:38:56 2024

Found 48 results from 2024-01-19 to 2024-02-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

** Copper oxide nanofibers obtained by solution blow spinning as catalysts for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.01.213")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390965940"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390965940"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390965940"))][Get cited by]]

OpenAlex: https://openalex.org/W4390965940 (Open access: False)
    
[[https://openalex.org/A5012056564][Alessandra Patrícia de Araújo Dantas]], [[https://openalex.org/A5001528670][Rafael A. Raimundo]], [[https://openalex.org/A5011364392][Pedro de Lima Neto]], [[https://openalex.org/A5013176757][Caio M. S. Lopes]], [[https://openalex.org/A5075400591][Jakeline R.D. Santos]], [[https://openalex.org/A5090398034][Francisco J.A. Loureiro]], [[https://openalex.org/A5029685103][Tatiany Barata Pereira]], [[https://openalex.org/A5088882865][Marco A. Morales]], [[https://openalex.org/A5061360133][Eliton S. Medeiros]], [[https://openalex.org/A5069774051][Daniel A. Macedo]], Ceramics International. None(None)] 2024. https://doi.org/10.1016/j.ceramint.2024.01.213 
     
In this work, we report copper oxide nanofibers (CuO – N) synthesized by Solution Blow Spinning (SBS) for oxygen evolution reaction (OER), and their comparison with a control sample based on a commercial powder (CuO – C). Both materials were characterized by various techniques, including X-ray diffraction (XRD), magnetometry, scanning electron microscopy (SEM), and spectroscopy (Fourier transform infrared (FT-IR), Raman and X-ray photoelectron (XPS)) to confirm the purity, and microstructural and surface chemical properties. Subsequently, the performance of copper oxide catalysts in a 1.0 M KOH solution was investigated. Copper oxide with nanofiber morphology (CuO – N) exhibited a small overpotential of 385 mV @ 10 mA cm−2 and a Tafel coefficient of only 76 mV dec−1, i.e., fast kinetics for water splitting, a result that is modulated by oxygen vacancies (O2/O1 = 0.83). The oxygen vacancies are due to the presence of Cu1+ in the lattice. The analyses of the magnetization measurements at 5 K suggest a larger amount of Cu1+ in sample CuO – N. Therefore, this work sheds light on how to design low-cost nanofibrous catalysts based on abundant transition metals in the earth's crust by SBS, an economical and scalable technique, which is promising for energy applications.    

    

** High-throughput electrochemical strategy for synthesis of iron-based nanostructures for electrocatalytic water splitting   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10853-023-09290-w")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390966433"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390966433"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390966433"))][Get cited by]]

OpenAlex: https://openalex.org/W4390966433 (Open access: False)
    
[[https://openalex.org/A5080141109][Tatyana Molodtsova]], [[https://openalex.org/A5019265904][Anna Ulyankina]], [[https://openalex.org/A5050248202][М.В. Горшенков]], [[https://openalex.org/A5033676013][С. П. Кубрин]], [[https://openalex.org/A5080417513][В. В. Каичев]], [[https://openalex.org/A5008358594][Nina Smirnova]], Journal of Materials Science. None(None)] 2024. https://doi.org/10.1007/s10853-023-09290-w 
     
No abstract    

    

** Review of acidic titanium-based oxygen evolution anode catalyst design: mechanistic, compositional design, and research status   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173576")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390967206"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390967206"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390967206"))][Get cited by]]

OpenAlex: https://openalex.org/W4390967206 (Open access: False)
    
[[https://openalex.org/A5078344429][Chuanbin Li]], [[https://openalex.org/A5050008056][Tao Lin]], [[https://openalex.org/A5058300296][Xiaotian Yuan]], [[https://openalex.org/A5028885861][Hongzhou Jiang]], [[https://openalex.org/A5048777235][Zhifang Hu]], [[https://openalex.org/A5025710679][Yanxi Yin]], Journal of Alloys and Compounds. 979(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.173576 
     
Oxygen evolution reaction (OER) is a key half-reaction in fields including water electrolysis, organic synthesis, and water treatment. With the development of the industry, research into highly active and stable oxygen evolution anodes in an acidic environment is essential. DSA is the dimensionally stable anode. Widespread attention has been paid to titanium-based DSAs in the field of acidic oxygen precipitation due to their low overpotential and high acid resistance. The titanium-based anode mainly consists of two parts: catalyst and titanium substrate, where the design of the catalyst is the key to the anode design. The factors affecting the catalytic activity and durability of the titanium-based DSA were heterogeneous and rarely reported. In this paper, the influence of catalytic mechanism and composition design on the catalytic activity and service life of anode is reviewed from the perspective of the catalyst. Then, the current situation related to anode preparation is summarized, and an improvement strategy to enhance the activity and stability of anode is proposed based on the failure mode of titanium-based DSA.    

    

** Constructing Asymmetrical Coordination Microenvironment with Phosphorus‐Incorporated Nitrogen‐Doped Carbon to Boost Bifunctional Oxygen Electrocatalytic Activity   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202314444")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390978765"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390978765"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390978765"))][Get cited by]]

OpenAlex: https://openalex.org/W4390978765 (Open access: False)
    
[[https://openalex.org/A5077776870][Zhijun Li]], [[https://openalex.org/A5069816022][Siqi Ji]], [[https://openalex.org/A5039930256][Hongxue Liu]], [[https://openalex.org/A5042785211][Xu Chen]], [[https://openalex.org/A5057239216][Chengchao Guo]], [[https://openalex.org/A5033684035][Xue Li]], [[https://openalex.org/A5004012018][Haixin Sun]], [[https://openalex.org/A5060128347][Shuo Dou]], [[https://openalex.org/A5076713273][Shixuan Xin]], [[https://openalex.org/A5033912521][J. Hugh Horton]], [[https://openalex.org/A5008473333][Cheng He]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202314444 
     
Abstract Carbon‐based metal‐free electrocatalysts have been recognized as inexpensive alternatives to afford excellent activity in oxygen reduction/evolution reactions (ORR/OER). Nevertheless, precisely identifying the local active sites and tailoring the corresponding electronic properties to enhance the reaction kinetics remain challenging. Herein, a facile strategy to create a metal‐free electrocatalyst comprised of a mesoporous nitrogen‐doped carbon matrix with phosphorus incorporation (NPC) is described. The as‐prepared NPC‐950 electrocatalyst demonstrates superior ORR activity under alkaline and acidic conditions with half‐wave potentials of 0.88 and 0.72 V, respectively, comparable to commercial Pt/C (0.85 and 0.76 V) and overwhelmingly superior to other N‐doped carbon catalyst materials. In addition, a remarkable promotion of OER activity under alkaline conditions is observed. Notably, a zinc–air battery equipped with this NCP‐950 electrocatalyst exhibits exceptional performance in peak power density, specific capacity, and long‐term operation durability. Theoretical calculations uncover that the incorporation of phosphorus in NC material results in effective charge density redistribution, thus modulating the electronic properties of active sites to achieve optimum adsorption and desorption of ORR intermediates. The work provides a deep understanding of active sites in heteroatom‐doped carbon materials and highlights the importance of the electronic properties modulation in oxygen bifunctional electrocatalytic activity.    

    

** Electrically Insulated Catalyst-Ionomer Anode Interfaces towards Durable Alkaline Membrane Electrolyzer   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-lp0l6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390980864"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390980864"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390980864"))][Get cited by]]

OpenAlex: https://openalex.org/W4390980864 (Open access: True)
    
[[https://openalex.org/A5014415643][Minkyoung Kwak]], [[https://openalex.org/A5025668965][Kasinath Ojha]], [[https://openalex.org/A5049440736][Meikun Shen]], [[https://openalex.org/A5032458792][Shannon W. Boettcher]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-lp0l6  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65a701f6e9ebbb4db951c96a/original/electrically-insulated-catalyst-ionomer-anode-interfaces-towards-durable-alkaline-membrane-electrolyzer.pdf][pdf]])
     
Anion-exchange-membrane water electrolysis (AEMWE) is an emerging technology for scalable hydrogen production. AEMWE has poor durability when operating without supporting electrolyte due to the oxidation of ionomers and membranes in contact with anode oxygen evolution reaction (OER) catalyst. We report a new “passivated” anode architecture for AEMWE where OER catalysts and ionomers are physically separated with a thin film amorphous oxide coating that is electrically insulating but conductive to hydroxide ions. We find that 2–3 nm of HfOx passivation layers show sufficient hydroxide ion transport to minimally limit the cell performance while suppressing ionomer degradation with both Ir (500 mA·cm−2 for 40 h) and CoOx (1.0 A·cm−2 for 100 h) model porous-transport-layer-supported catalysts in AEMWE. This interfacial engineering approach guides electrode design to improve the durability of AEMWE, particularly for systems operating with pure water feed.    

    

** A Cluster-Type Self-Healing Catalyst for Stable Saline–Alkali Water Splitting   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14010081")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390986406"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390986406"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390986406"))][Get cited by]]

OpenAlex: https://openalex.org/W4390986406 (Open access: True)
    
[[https://openalex.org/A5002285545][Haiming Wang]], [[https://openalex.org/A5039744969][Sheng Chen]], Catalysts. 14(1)] 2024. https://doi.org/10.3390/catal14010081  ([[https://www.mdpi.com/2073-4344/14/1/81/pdf?version=1705587459][pdf]])
     
In electrocatalytic processes, traditional powder/film electrodes inevitably suffer from damage or deactivation, reducing their catalytic performance and stability. In contrast, self-healing electrocatalysts, through special structural design or composition methods, can automatically repair at the damaged sites, restoring their electrocatalytic activity. Here, guided by Pourbaix diagrams, foam metal was activated by a simple cyclic voltammetry method to synthesize metal clusters dispersion solution (MC/KOH). The metal clusters-modified hydroxylated Ni-Fe oxyhydroxide electrode (MC/NixFeyOOH) by a facile Ni-Fe metal–organic framework-reconstructed strategy, exhibiting superior performance toward the oxygen evolution reaction (OER) in the mixture of MC/KOH and saline–alkali water (MC/KOH+SAW). Specifically, using a nickel clusters-modified hydroxylated Ni-Fe oxyhydroxide electrode (NC/NixFeyOOH) for OER, the NC/NixFeyOOH catalyst has an ultra-low overpotential of 149 mV@10 mA cm−2, and durable stability of 100 h at 500 mA cm−2. By coupling this OER catalyst with an efficient hydrogen evolution reaction catalyst, high activity and durability in overall SAW splitting is exhibited. What is more, benefiting from the excellent fluidity, flexibility, and enhanced catalytic activity effect of the liquid NC, we demonstrate a self-healing electrocatalysis system for OER operated in the flowing NC/(KOH+SAW). This strategy provides innovative solutions for the fields of sustainable energy and environmental protection.    

    

** Benchmarking Stability of Iridium Oxide in Acidic Media under Oxygen Evolution Conditions: A Review: Part II   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1595/205651324x17055018154113")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987310"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987310"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987310"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987310 (Open access: True)
    
[[https://openalex.org/A5028610474][James Murawski]], [[https://openalex.org/A5004372016][Søren B. Scott]], [[https://openalex.org/A5027366818][Reshma R. Rao]], [[https://openalex.org/A5040293372][Katie Rigg]], [[https://openalex.org/A5030674093][Christopher Mark Zalitis]], [[https://openalex.org/A5015505628][James Stevens]], [[https://openalex.org/A5007586547][Jonathan Sharman]], [[https://openalex.org/A5055131883][Gareth Hinds]], [[https://openalex.org/A5039064548][Ifan E. L. Stephens]], Johnson Matthey Technology Review. None(None)] 2024. https://doi.org/10.1595/205651324x17055018154113 
     
Part I (1) introduced state-of-the-art proton exchange membrane (PEM) electrolysers with iridium-based catalysts for oxygen evolution at the anode in green hydrogen applications. Aqueous model systems and full cell testing were discussed along with proton exchange membrane water electrolyser (PEMWE) catalyst degradation mechanisms, types of iridium oxide, mechanisms of iridium dissolution and stability studies. In Part II, we highlight considerations and best practices for the investigation of activity and stability of oxygen evolution catalysts via short term testing.    

    

** Production of manganese telluride-based manganese oxide nano-composite works as a catalyst for effective oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.130919")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391007038"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391007038"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391007038"))][Get cited by]]

OpenAlex: https://openalex.org/W4391007038 (Open access: False)
    
[[https://openalex.org/A5084962407][Zainab M. Almarhoon]], [[https://openalex.org/A5032441176][Karam Jabbour]], [[https://openalex.org/A5049370676][Sumaira Manzoor]], [[https://openalex.org/A5059163435][Syed Imran Abbas Shah]], [[https://openalex.org/A5047878257][Muhammad Faheem Ashiq]], [[https://openalex.org/A5028081043][Muhammad Yousaf ur Rehman]], [[https://openalex.org/A5063142393][Muhammad Fahad Ehsan]], [[https://openalex.org/A5020371871][Muhammad Najam‐ul‐Haq]], [[https://openalex.org/A5061069978][Muhammad Naeem Ashiq]], Fuel. 363(None)] 2024. https://doi.org/10.1016/j.fuel.2024.130919 
     
Individuals experiencing poverty and possessing limited financial resources are particularly susceptible to impacts of climate change and rising costs associated with fossil fuels. In response to this pressing issue, researchers are actively investigating water oxidation as a sustainable solution to mitigate the challenges posed by climate changes and energy crisis. The oxygen evolution reaction (OER), which plays a pivotal role in water electrolysis, necessitates the utilization of highly stable and efficient electrode materials to overcome its intrinsic sluggish kinetics and enhance the overall efficiency of the electrochemical device. This investigation employed a reduction method to synthesize manganese oxide (MnO) nanoparticles, using manganese telluride (MnTe) as the base material, yielding a MnTe@MnO nanocomposite. This innovative composite was subsequently immobilized onto a nickel foam (NF) substrate. Remarkably, the MnTe@MnO nanocomposite exhibited exceptional OER performance in a 1.0 M alkaline solution, manifesting an impressively low overpotential of 208 mV at a benchmark current density of 10 mA cm−2. This overpotential significantly surpassed that of the individual MnTe and MnO electrode materials, underscoring the synergistic advantages of the MnTe@MnO nanocomposite. Further analysis revealed a notably shallow Tafel slope of 39 mV dec-1, indicative of the enhanced reaction kinetics and electrocatalytic efficiency inherent to the MnTe@MnO nanocomposite. Moreover, the durability assessment over a span of 30 h demonstrated minimal current loss, emphasizing the substantial electrocatalytic active surface area of the fabricated nanocomposite.    

    

** Amorphous MnO2 Lamellae Encapsulated Covalent Triazine Polymer‐Derived Multi‐Heteroatoms‐Doped Carbon for Orr/Oer Bifunctional Electrocatalysis   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202312868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391014747"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391014747"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391014747"))][Get cited by]]

OpenAlex: https://openalex.org/W4391014747 (Open access: False)
    
[[https://openalex.org/A5080719917][Liping Huo]], [[https://openalex.org/A5091573895][Mei Lv]], [[https://openalex.org/A5063869163][Mingjin Li]], [[https://openalex.org/A5020487385][Xuepeng Ni]], [[https://openalex.org/A5059733264][Jingyu Guan]], [[https://openalex.org/A5060165452][Jian Liu]], [[https://openalex.org/A5022593750][Shuxing Mei]], [[https://openalex.org/A5087133964][Yu‐Ting Yang]], [[https://openalex.org/A5023410444][Miaomiao Zhu]], [[https://openalex.org/A5020990336][Qichun Feng]], [[https://openalex.org/A5047932356][Ping Geng]], [[https://openalex.org/A5035209833][Jianhua Hou]], [[https://openalex.org/A5090524398][Niu Huang]], [[https://openalex.org/A5071037763][Wei Liu]], [[https://openalex.org/A5005904436][Xin Ying Kong]], [[https://openalex.org/A5088200752][Yong Zheng]], [[https://openalex.org/A5009243555][Liqun Ye]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202312868 
     
The intelligent construction of non-noble metal materials that exhibit reversible oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) with bifunctional electrocatalytic performance is greatly coveted in the realm of zinc-air batteries (ZABs). Herein, a crafted structure-amorphous MnO2 lamellae encapsulated covalent triazine polymer-derived N, S, P co-doped carbon sphere (A-MnO2 /NSPC) is designed using a self-doped pyrolysis coupled with an in situ encapsulation strategy. The customized A-MnO2 /NSPC-2 demonstrates a superior bifunctional electrocatalytic performance, confirmed by a small ΔE index of 0.64 V for ORR/OER. Experimental investigations, along with density functional theory calculations validate that predesigned amorphous MnO2 surface defects and abundant heteroatom catalytic active sites collectively enhance the oxygen electrocatalytic performance. Impressively, the A-MnO2 /NSPC-based rechargeable liquid ZABs show a large open-circuit potential of 1.54 V, an ultrahigh peak power density of 181 mW cm-2 , an enormous capacity of 816 mAh g-1 , and a remarkable stability for more than 1720 discharging/charging cycles. Additionally, the assembled flexible all-solid-state ZABs also demonstrate outstanding cycle stability, surpassing 140 discharging/charging cycles. Therefore, this highly operable synthetic strategy offers substantial understanding in the development of magnificent bifunctional electrocatalysts for various sustainable energy conversions and beyond.    

    

** Excellent Bifunctional Oxygen Evolution and Reduction Electrocatalysts (5A1/5)Co2O4 and Their Tunability   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsmaterialsau.3c00088")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391017352"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391017352"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391017352"))][Get cited by]]

OpenAlex: https://openalex.org/W4391017352 (Open access: True)
    
[[https://openalex.org/A5035370911][Xin Wang]], [[https://openalex.org/A5071503860][Harcharan Singh]], [[https://openalex.org/A5071642497][Manashi Nath]], [[https://openalex.org/A5093744834][Kurt Lagemann]], [[https://openalex.org/A5037999285][Katharine Page]], ACS Materials Au. None(None)] 2024. https://doi.org/10.1021/acsmaterialsau.3c00088  ([[https://pubs.acs.org/doi/pdf/10.1021/acsmaterialsau.3c00088][pdf]])
     
Hastening the progress of rechargeable metal–air batteries and hydrogen fuel cells necessitates the advancement of economically feasible, earth-abundant, inexpensive, and efficient electrocatalysts facilitating both the oxygen evolution reaction (OER) and oxygen reduction reaction (ORR). Herein, a recently reported family of nano (5A1/5)Co2O4 (A = combinations of transition metals, Mg, Mn, Fe, Ni, Cu, and Zn) compositionally complex oxides (CCOs) [Wang et al., Chemistry of Materials, 2023, 35 (17), 7283–7291.] are studied as bifunctional OER and ORR electrocatalysts. Among the different low-temperature soft-templating samples, those subjected to 600 °C postannealing heat treatment exhibit superior performance in alkaline media. One specific composition (Mn0.2Fe0.2Ni0.2Cu0.2Zn0.2)Co2O4 exhibited an exceptional overpotential (260 mV at 10 mA cm–2) for the OER, a favorable Tafel slope of 68 mV dec–1, excellent onset potential (0.9 V) for the ORR, and lower than 6% H2O2 yields over a potential range of 0.2 to 0.8 V vs the reversible hydrogen electrode. Furthermore, this catalyst displayed stability over a 22 h chronoamperometry measurement, as confirmed by X-ray photoelectron spectroscopy analysis. Considering the outstanding performance, the low cost and scalability of the synthesis method, and the demonstrated tunability through chemical substitutions and processing variables, CCO ACo2O4 spinel oxides are highly promising candidates for future sustainable electrocatalytic applications.    

    

** Co-doped 1T-MoS2 microspheres embedded in N-doped reduced graphene oxide for efficient electrocatalysis toward hydrogen and oxygen evolution reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.234088")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391019379"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391019379"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391019379"))][Get cited by]]

OpenAlex: https://openalex.org/W4391019379 (Open access: False)
    
[[https://openalex.org/A5039003426][Gyawali Ghanashyam]], [[https://openalex.org/A5016483703][Haekyoung Kim]], Journal of Power Sources. 596(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.234088 
     
The development of an efficient, bifunctional, and affordable catalyst has emerged as a valuable approach in electrocatalysis because it can enhance the conductivity, charge transfer capability, and number of active sites of the catalyst. In this study, we synthesis flower-like morphologies of 1T-phase cobalt (Co)-doped molybdenum disulfide (MoS2) embedded on nitrogen-doped reduced graphene oxide (N-rGO) using a facile hydrothermal technique. Owing to this configuration, the optimal Co0.18/1T-Mo0.82S2@N-rGO catalyst exhibits remarkable activity toward the oxygen evolution reaction, with a low overpotential of 243 mV and a Tafel slope of 75 mV/dec at 10 mA/cm2. The catalyst also demonstrates excellent performance in the hydrogen evolution reaction with an overpotential of 142 mV and a Tafel slope of 48 mV/dec to afford a current density of −10 mA/cm2 in basic media, which are comparable to platinum on carbon and iridium dioxide, along with excellent stability. To perform overall water splitting, assembled Co0.18/1T-Mo0.82S2@N-rGO (+//-) cell requires only 1.51 V to achieve 10 mA/cm2. This study illustrates the beneficial effect of Co doping on the synthesized flower-shaped MoS2, formation of the 1T phase, and the performance of N-rGO as a conductive network, which holds significant potential in the field of electrocatalysis.    

    

** Pre-implanting metal oxides to endow the N-doped carbon with boosted bifunctional catalytic activities towards oxygen reduction and oxygen evolution reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173590")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391022876"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391022876"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391022876"))][Get cited by]]

OpenAlex: https://openalex.org/W4391022876 (Open access: False)
    
[[https://openalex.org/A5082944340][Lei Yu]], [[https://openalex.org/A5039420617][Yang Xiang]], [[https://openalex.org/A5081064590][Chuanlan Xu]], [[https://openalex.org/A5011802849][Rong Jin]], [[https://openalex.org/A5057116148][Lingtao Sun]], [[https://openalex.org/A5086992948][Haifeng Chen]], [[https://openalex.org/A5069984955][Mei Yang]], [[https://openalex.org/A5073410815][Yujun Si]], [[https://openalex.org/A5057741794][Changguo Chen]], [[https://openalex.org/A5020870418][Chaozhong Guo]], Journal of Alloys and Compounds. 980(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.173590 
     
Nitrogen-doped carbon-based materials exhibit promising prospect as the catalysts to oxygen reduction reaction (ORR). Incorporating transition metal oxides with the catalysts can endow them with oxygen evolution reaction (OER) activity to construct bifunctional catalysts for rechargeable zinc-air batteries. In this work, a catalyst (named as 300NiFe-Mi-C) was prepared by a metal oxide-implanting strategy. The mixed metal salts of Ni and Fe were first heated to produce metal oxides, and then blended with 2-methylimidazole and carbon black, and subsequently pyrolyzed at a high temperature. In the pyrolysis, a part of metal oxides was reduced to metallic state to facilitate the doping of nitrogen atoms into carbon to form the ORR active sites while a part of metal oxides was retained to afford OER activity. Benefiting from the pre-implanting strategy of metal oxides, the resultant 300NiFe-Mi-C presents enhanced OER performance with 1.56 V of OER potential at 10 mA cm−2, outperforming the 1.68 V of the controlled sample NiFe-Mi-C (without pre-implanting) and 1.70 V of RuO2. The 0.83 V of ORR half-wave potential of 300NiFe-Mi-C is also comparable to the 0.82 V of NiFe-Mi-C and 0.86 V of Pt/C, revealing satisfactory bifunctional catalytic activities. The rechargeable zinc-air battery equipped with 300NiFe-Mi-C can stably operate at ~1.25 V with 10 mA cm−2, being higher than ~1.21 V of Pt/C+RuO2. The battery also presents outstanding durability and rechargeability, demonstrating the bifunctional activities of 300NiFe-Mi-C can be realized in practical applications.    

    

** One-Pot Formation of an rGO-Based ZnAl2O4 Nanocomposite for Electrochemical Studies toward Oxygen Evolution Reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.energyfuels.3c04297")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391025659"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391025659"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391025659"))][Get cited by]]

OpenAlex: https://openalex.org/W4391025659 (Open access: False)
    
[[https://openalex.org/A5002469930][Mohamed H. Helal]], [[https://openalex.org/A5084459974][Hamdy Khamees Thabet]], [[https://openalex.org/A5083753418][Salma Aman]], [[https://openalex.org/A5048764625][Naseeb Ahmad]], [[https://openalex.org/A5001974005][Hafiz Muhammad Tahir Farid]], [[https://openalex.org/A5029616052][Zeinhom M. El‐Bahy]], No host. None(None)] 2024. https://doi.org/10.1021/acs.energyfuels.3c04297 
     
Electrocatalysts for water (H2O) splitting to give oxygen (O2) and hydrogen (H2) fuels are challenging to build, but mixing carbon materials with transition-metal-based compounds offers an intriguing and innovative method for the development of environment-friendly fuel. Hydrothermal synthesis is a cheap and effective catalyst based on a ZnAl2O4 nanocomposite anchored over reduced graphene oxide (rGO) and is presented here, along with characterization by microscopy and spectroscopy. As a possible oxygen evolution reaction (OER) electrocatalyst on nickel foam’s surface (NF), the electrochemical properties of this catalyst were also studied. The electrochemical studies showed that the ZnAl2O4 anchored on rGO sample exhibited high stability for the OER and an enhanced surface area, ionic conductivity, and active zones of the electrocatalyst was observed compared to that of the other investigated composites. It also exhibited an overpotential of 244 mV achieved at 10 mA cm–2 and lowered solution resistance (Rs = 0.63 Ω) and charge transfer resistance (Rct = 0.6 Ω). This catalyst has a wide operating current range and, therefore, may function for long periods of time at both high and low current densities. High electrical conductivity, a larger surface area, and enriched active zones are responsible for enhancing the ZnAl2O4@rGO composite’s multifunctional qualities, as shown by the results. The electrocatalytic properties of ZnAl2O4@rGO composites were enhanced, and they exhibited a high cycling stability of 50 h even after the 5000th cycle due to the combined influence of these surface features. The present investigation has revealed that the ZnAl2O4@rGO nanocomposite demonstrates significant versatility, making it highly suitable for various fields related to sustainable and renewable energy. This suggests that it could be employed in developing an efficient and promising electrode for the OER, thereby paving the way for new possibilities.    

    

** Electrochemical deuterated ammonia (ND3) production at A cm-2 current densities   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-3745766/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391031158"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391031158"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391031158"))][Get cited by]]

OpenAlex: https://openalex.org/W4391031158 (Open access: True)
    
[[https://openalex.org/A5026990918][Zishuai Zhang]], [[https://openalex.org/A5014439877][Ping Zhu]], [[https://openalex.org/A5031130542][Jiangzhou Qin]], [[https://openalex.org/A5016260569][Jun Li]], [[https://openalex.org/A5049693814][Kuichang Zuo]], No host. None(None)] 2024. https://doi.org/10.21203/rs.3.rs-3745766/v1  ([[https://www.researchsquare.com/article/rs-3745766/latest.pdf][pdf]])
     
Abstract Deuterated ammonia (ND3) treatment contributes significantly to the reliability of semiconductors in manufacturing. Current ND3 production suffers from high energy consumption, CO2 emissions and capital expenditure. In this study, we present an electrochemical approach using iron (Fe) single-atom catalysts supported by nitrogen-doped carbon in an electrolyzer, operating at A cm-2 current densities for ND3 production. Through systematic optimization of catalyst composition, electrode/electrolyzer architectures, anodic reactions, and operating conditions, the system achieved a ND3 selectivity exceeding 80% at 200 mA cm-2 and 60% at 600 mA cm-2, with a maximal production rate of 1.73 mmol h-1 cm-2 and stability over 100 hours (assessed at 200 mA cm-2). The full cell voltage is 3.2 V when combined with an oxygen evolution reaction (OER) anode, and it decreases to 2.3 V when coupled with a hydrogen oxidation reaction (HOR) anode at 600 mA cm-2. Techno-economic analysis (TEA) results demonstrate a fivefold energy consumption reduction to 0.19 MJ molND3-1, threefold emission reduction to 16.13 g molND3-1, and threefold cost reduction to $6,000 from $27,000 kgND3-1, highlighting the potential for widespread commercialization and contributing to the more environmentally sustainable ND3 production.    

    

** Accessible Ni‐Fe‐Oxalate Framework for Electrochemical Urea Oxidation with Radically Enhanced Kinetics   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202315625")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391031743"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391031743"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391031743"))][Get cited by]]

OpenAlex: https://openalex.org/W4391031743 (Open access: False)
    
[[https://openalex.org/A5072751301][Jiseon Kim]], [[https://openalex.org/A5028095065][Min Cheol Kim]], [[https://openalex.org/A5067470445][Sang Soo Han]], [[https://openalex.org/A5033596181][Kangwoo Cho]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202315625 
     
Abstract Urea oxidation reaction (UOR) has been utilized to substitute the oxygen evolution reaction (OER), to escalate the energy conversion efficiency in electrochemical hydrogen generation processes with denitrification of widespread urea in wastewater. This study reports breakthroughs in Ni‐based UOR electrocatalysts, particularly with NiFe oxalate (O‐NFF), derived from Ni 3 Fe alloy foam with prismatic nanostructures and elevated surface area. The O‐NFF achieves cutting‐edge performances, representing 500 mA cm −2 of current density at 1.47 V RHE and exceptionally low Tafel slope of 12.1 mV dec −1 (in 1 m KOH with 0.33 m urea). X‐ray photoelectron/absorption spectroscopy (XPS/XAS) coupled with density functional theory calculations unveil that oxalate ligands induce charge deficient Ni center, promoting stable urea‐O adsorption. Furthermore, Fe dopants enhance oxalate‐O charge density and H‐bond strength, facilitating C‐N cleavage for N 2 and NO 2 − formation. The extraordinary UOR kinetics by the tandem effects of oxalate and Fe prevent Ni over‐oxidation, corroborated by operando XAS, minimizing OER interference. It agrees with an adaptive reconstruction to Fe‐doped β‐NiOOH on top surface in extended urea electrolysis with marginal loss in UOR kinetics. This findings shed light to bimetal‐organic‐framework as (pre)catalysts to improve industrial electrolytic H 2 production.    

    

** Fe3C/Fe Decorated N‐doped Carbon Derived from Tetrabutylammonium tetrachloroferrate Complex as Bifunctional Electrocatalysts for ORR, OER and Zn‐Air Batteries in Alkaline Medium   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/asia.202300933")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391035614"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391035614"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391035614"))][Get cited by]]

OpenAlex: https://openalex.org/W4391035614 (Open access: False)
    
[[https://openalex.org/A5043561901][Debojit Ghosh]], [[https://openalex.org/A5072583471][Rumeli Banerjee]], [[https://openalex.org/A5047017381][Samanka Narayan Bhaduri]], [[https://openalex.org/A5073089043][Rupak Chatterjee]], [[https://openalex.org/A5007872973][Abhisek Brata Ghosh]], [[https://openalex.org/A5064559604][Samarpita Das]], [[https://openalex.org/A5092784947][Indrani Pramanick]], [[https://openalex.org/A5043502752][Asim Bhaumik]], [[https://openalex.org/A5076909165][Papu Biswas]], No host. None(None)] 2024. https://doi.org/10.1002/asia.202300933 
     
The emergence of non-precious metal-based robust and economic bifunctional oxygen electrocatalysts for both oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) is crucial for the rational design of commercial rechargeable Zn-air batteries (RZAB) with safe energy conversion and storage systems. Herein, a facile strategy to fabricate a cost-efficient, bifunctional oxygen electrocatalyst Fe3C/Fe decorated N doped carbon (FeC-700) with a unique structure has been developed by carbonization of a single source precursor, tetrabutylammonium tetrachloroferrate(III) complex. The ORR and OER activity revealed excellent performance (ΔE = 0.77 V) of the FeC-700 electrocatalyst, comparable to commercial Pt/C and RuO2, respectively. The designed temperature-tuneable structure provided sufficiently accessible active sites for the continuous passage of electrons by shortening the mass transfer pathway, leading to extremely durable electrocatalysts with high ECSA and amazing charge transfer performance. Remarkably, the assembled Zn-air batteries with the FeC-700 catalyst as the bifunctional air electrode delivers gratifying charging-discharging ability with an impressive power density of 134 mW cm-2 with a long lifespan, demonstrating prodigious possibilities for practical application.    

    

** Pulse electrodeposition synthesis of Ti/PbO2-IrO2 nano-composite electrode to restrict the OER in the zinc electrowinning   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jece.2024.111985")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391035928"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391035928"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391035928"))][Get cited by]]

OpenAlex: https://openalex.org/W4391035928 (Open access: False)
    
[[https://openalex.org/A5037806350][Fateme Hakimi]], [[https://openalex.org/A5063550410][Masoumeh Ghalkhani]], [[https://openalex.org/A5035000524][Fereshteh Rashchi]], [[https://openalex.org/A5017505164][Abolghasem Dolati]], Journal of Environmental Chemical Engineering. 12(2)] 2024. https://doi.org/10.1016/j.jece.2024.111985 
     
Pulsed and constant direct current electrodepositions were applied to synthesize PbO2-IrO2 nano-composites on Ti substrate. By compositing PbO2 with nano-sized IrO2 particles, a suitable anode was prepared for zinc electrowinning that decreases the electrocatalytic activity for oxygen evolution reaction overpotential (OER) while increasing the electrochemical active surface area and the electrocatalytic activity for OER. To provide PbO2-IrO2 nano-composites on Ti substrate with Sb2O3 interlayer, current density, temperature, and time of anodization are optimized using the one-at-the-time method. The optimal condition for the anode involves a DC time of 1 hour, incorporating 2 g L-1 of IrO2 nanoparticles, maintaining a current density of 50 mA/cm2 for the DC mode, and setting the pulse off-time (toff) to 770 ms. Based on the electrochemical evaluations in a simulated zinc electrowinning electrolyte, the effect of IrO2 nanoparticles on the catalytic activity of Ti/β-PbO2 anode for OER was determined. Anodic polarization curves showed that the OER overpotential of PbO2-IrO2 micro-composite and PbO2-IrO2 nano-composites at a current density of 10 mA cm-2 decreased to 0.471 V, respectively, compared to 0.711 V for pure PbO2. The Nyquist plots in the OER zone confirm that the PbO2-IrO2 nano-composite anode exhibits the lowest Rct 2.79 Ω compared to 6.0 Ω and 9.46 Ω for PbO2-IrO2 micro-composite and pure PbO2, which can be attributed to the presence of electro-catalytic IrO2 nanoparticles.    

    

** Ce-4f as an Electron-Modulation Reservoir Weakening Fe-O Bond to Induce Iron Vacancies in Cefevni Hydroxide for Enhancing Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4699906")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391036096"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391036096"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391036096"))][Get cited by]]

OpenAlex: https://openalex.org/W4391036096 (Open access: False)
    
[[https://openalex.org/A5051645819][Le Gao]], [[https://openalex.org/A5090656500][Yue Yao]], [[https://openalex.org/A5061402622][Yun Chen]], [[https://openalex.org/A5088401238][Jiajun Huang]], [[https://openalex.org/A5057359491][Y. Ma]], [[https://openalex.org/A5045712324][Wenbin Chen]], [[https://openalex.org/A5029474718][Huan Li]], [[https://openalex.org/A5015834487][Yu Wang]], [[https://openalex.org/A5030624915][Lishan Jia]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4699906 
     
Designing novel rare earth-transition metal composites is frontier electrocatalyst research. However, rare earths modulating the electronic structure of the transition metal with the aim of inducing vacancy defects to enhance the electrochemical performance has rarely been reported. Herein, the mechanism of Ce-4f electron-modulation reservoir induced weakening of Fe-O bond to modulate the electronic structure in CeFevNi hydroxide to improve oxygen evolution reaction (OER) performance has been systematically investigated. Theoretical calculations and characterization results demonstrate that the Ce-4f orbitals, working as an electron-modulation reservoir, play a crucial role in not only retaining or donating electrons, but also in modulating the electronic structure of the material. Furthermore, Ce-4f bands optimize the Fe lower Hubbard bands (LHB) and O-2p bands, resulting in the weakening of the Fe-O bond to form cationic vacancies for upshifting the d-band center of the active site Ni, which favors the reaction energy barrier of the oxygen intermediate for OER. The synthesized catalyst exhibited a low overpotential of 201 mV at 10 mA cm-2 and demonstrated a lifetime of more than 200 hours at 100 mA cm-2 under alkaline conditions. This work serves as a proof-of-concept for the application of the mechanism of rare earth-induced transition metal vacancy defects, which can provide a generalized guideline for the design and development of novel highly efficient catalysts.    

    

** Laser assisted oxygen vacancy engineering on Fe doped CoO nanoparticles for oxygen evolution at large current density   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.143841")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391037653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391037653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391037653"))][Get cited by]]

OpenAlex: https://openalex.org/W4391037653 (Open access: False)
    
[[https://openalex.org/A5005245760][Min Zhu]], [[https://openalex.org/A5072946813][Zong‐Qiang Sheng]], [[https://openalex.org/A5019261932][Zhifen Fu]], [[https://openalex.org/A5075847376][Yang Li]], [[https://openalex.org/A5001017073][Juan Gao]], [[https://openalex.org/A5089966579][Chao Zhang]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.143841 
     
Exploring cost-effective non-noble metal-based catalysts with high activity and stability is of great significance for energy conversion and storage involving oxygen evolution reaction (OER). Here, we employed a laser irradiation technique to synthesis Fe doped CoO nanoparticles with ultrafine size (≈ 5.4 nm) and abundant oxygen vacancies (Fe-Ov-CoO). The ultrafine size of Fe-Ov-CoO nanoparticles provides more active sites to be exposed. Fe doping and oxygen vacancy promote the intrinsic activity and electron transfer rates of Fe-Ov-CoO, giving rise to high activity and stability catalyst for OER. Fe-Ov-CoO delivers a large current density of 1000 mA cm−2 at an overpotential of 548 mV, which is much better than commercial RuO2. Moreover, Fe-Ov-CoO presents a remarkable long-term stability with negligible degeneration at a high current density of 500 mA cm−2 for 120 h. This work provides a new route to develop OER electrocatalyst with high activity and stability.    

    

** Evolution of Grain Boundaries Promoted Hydrogen Production for Industrial‐Grade Current Density   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202313156")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391042365"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391042365"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391042365"))][Get cited by]]

OpenAlex: https://openalex.org/W4391042365 (Open access: False)
    
[[https://openalex.org/A5063705533][Yu Cheng]], [[https://openalex.org/A5025015767][Huanyu Chen]], [[https://openalex.org/A5085185712][Lifang Zhang]], [[https://openalex.org/A5011837783][Xinnan Xu]], [[https://openalex.org/A5075680933][Haobo Cheng]], [[https://openalex.org/A5009136959][Chenglin Yan]], [[https://openalex.org/A5009208811][Tao Qian]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202313156 
     
The development of efficient and durable high-current-density hydrogen production electrocatalysts is crucial for the large-scale production of green hydrogen and the early realization of hydrogen economic blueprint. Herein, we have successfully driven the evolution of grain boundaries through Cu-mediated NiMo bimetallic oxides (MCu-BNiMo), which leading to the high efficiency of electrocatalyst for hydrogen evolution process (HER) in industrial-grade current density. The optimal MCu0.10 -BNiMo demonstrated ultrahigh current density (> 2 A cm-2 ) at a smaller overpotential in 1 M KOH (572 mV), than that of BNiMo, which does not have lattice strain. Experimental and theoretical calculations revealed that MCu0.10 -BNiMo with optimal lattice strain generated more electrophilic Mo sites with partial oxidation owing to accelerated charge transfer from Cu to Mo, which lowers the energy barriers for H* adsorption. These synergistic effects led to the enhanced HER performance of MCu0.10 -BNiMo. More importantly, industrial application of MCu0.10 -BNiMo operated in alkaline electrolytic cell was also determined, with its current density reached 0.5 A cm-2 at 2.12 V and 0.1 A cm-2 at 1.79 V, which is nearly five-fold that of the state-of-the-art HER electrocatalyst Pt/C. Our strategy provides valuable insights for achieving industrial-scale hydrogen production through a highly efficient HER electrocatalyst. This article is protected by copyright. All rights reserved.    

    

** Morphology Engineering of Self-Assembled Porous Bimetallic Ptco Alloy Nanofoams as Efficient Multifunctional Electrocatalysts for Oxygen Reduction and Alcohol Oxidation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4700801")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391042860"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391042860"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391042860"))][Get cited by]]

OpenAlex: https://openalex.org/W4391042860 (Open access: False)
    
[[https://openalex.org/A5002603990][Meida Chen]], [[https://openalex.org/A5055509222][Liuxuan Luo]], [[https://openalex.org/A5075979734][Chong Wu]], [[https://openalex.org/A5068952541][Qingmei Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4700801 
     
The exploration of high properties of electrocatalysts is imperative for the commercialization application of fuel cells. The catalytic activity and stability of Pt-based catalysts can be effectively enhanced by rationally designing their morphology and composition. Here, we synthesized self-assembled PtCo alloy nanofoams (ANs) catalysts with controllable surface composition and porous network. The experimental results show that prepared PtxCo1-ANs catalysts display excellent electrochemical performance in oxygen reduction reaction (ORR), methanol oxidation reaction (MOR) and ethanol oxidation reaction (EOR). Interestingly, the mass activities of Pt2Co1-ANs with optimized surface composition for ORR, MOR, and EOR are 6.41, 6.64, and 7.71-fold higher than commercial Pt/C catalysts, respectively. Meantime, it also maintains high electrocatalytic durability in ORR, MOR, and EOR. Such results ascribe to the modified surface composition, optimized electronic structure, and porous interconnected nanofoam structure. These findings are insight of designing highly active and durable multifunctional electrocatalysts with controllable shapes and composition    

    

** Bi-Doped Nico2o4 Catalyst for Electrocatalysis Glucose Oxidation Accompanied Hydrogen Generation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4700856")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391042964"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391042964"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391042964"))][Get cited by]]

OpenAlex: https://openalex.org/W4391042964 (Open access: False)
    
[[https://openalex.org/A5074842909][Yu Xiong]], [[https://openalex.org/A5066852254][Fengchao Sun]], [[https://openalex.org/A5038669372][Liangbing Huang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4700856 
     
The slow dynamics of oxygen evolution reaction and the use of the proton exchange membrane have been troubling the hydrogen production from electrolytic water splitting. Reducing the electrolytic voltage and avoiding the utilization of proton exchange membranes are crucial targets for electrolytic hydrogen evolution. Bi doped NiCo2O4 catalyst is prepared and applied in electrocatalysis glucose oxidation coupled hydrogen generation. Structural characterizations confirm the successful preparation of NiCo2O4 and the existence of Bi. Bi leads to the electrons transfer from Co to Ni, increasing the content of Co3+, and lowers the oxidation potential of Co and Ni. Electrochemical experiments indicate that NiCo2O4-Bi has good electrocatalytic activity and stability toward electrochemical glucose oxidation, with a potential of 1.13 V vs. RHE at 10 mA cm-2 current density. The asymmetric electrolysis of two electrodes requires just 1.26 V to achieve a 10 mA cm-2 current density. The design of NiCo2O4-Bi is an exploration for electrocatalytic glucose oxidation coupled hydrogen production with low voltage and no proton exchange membrane.    

    

** Enhancing the stability of NiFe-layered double hydroxide nanosheet array for alkaline seawater oxidation by Ce doping   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.01.011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391043029"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391043029"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391043029"))][Get cited by]]

OpenAlex: https://openalex.org/W4391043029 (Open access: False)
    
[[https://openalex.org/A5084708809][Yongchao Yao]], [[https://openalex.org/A5086150710][Shengjun Sun]], [[https://openalex.org/A5003759585][Hui Zhang]], [[https://openalex.org/A5084960189][Zixiao Li]], [[https://openalex.org/A5043019150][Chaoxin Yang]], [[https://openalex.org/A5074106302][Zhengwei Cai]], [[https://openalex.org/A5027180761][Xun He]], [[https://openalex.org/A5065792572][Kai Dong]], [[https://openalex.org/A5062916226][Yonglan Luo]], [[https://openalex.org/A5084034088][Yan Wang]], [[https://openalex.org/A5032191049][Yuchun Ren]], [[https://openalex.org/A5003055293][Qian Liu]], [[https://openalex.org/A5042148629][Dongdong Zheng]], [[https://openalex.org/A5088189891][Wei Zhuang]], [[https://openalex.org/A5090789682][Bo Tang]], [[https://openalex.org/A5073001285][Xuping Sun]], [[https://openalex.org/A5016591821][Walter Hu]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.01.011 
     
Electrocatalytic hydrogen production from seawater holds enormous promise for clean energy generation. Nevertheless, the direct electrolysis of seawater encounters significant challenges due to poor anodic stability caused by detrimental chlorine chemistry. Herein, we present our recent discovery that the incorporation of Ce into NiFe layered double hydroxide nanosheet array on Ni foam (Ce-NiFe LDH/NF) emerges as a robust electrocatalyst for seawater oxidation. During the seawater oxidation process, CeO2 is generated, effectively repelling Cl− and inhibiting the formation of ClO−, resulting in a notable enhancement in the oxidation activity and stability of alkaline seawater. The prepared Ce-NiFe LDH/NF requires only overpotential of 390 mV to achieve the current density of 1 A cm−2, while maintaining long-term stability for 500 h, outperforming the performance of NiFe LDH/NF (430 mV, 150 h) by a significant margin. This study highlights the effectiveness of a Ce-doping strategy in augmenting the activity and stability of materials based on NiFe LDH in seawater electrolysis for oxygen evolution.    

    

** Advancing oxygen evolution electrocatalysis with human-machine intelligence   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.checat.2023.100868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391043168"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391043168"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391043168"))][Get cited by]]

OpenAlex: https://openalex.org/W4391043168 (Open access: True)
    
[[https://openalex.org/A5083865054][Liping Liu]], [[https://openalex.org/A5047424183][Siwen Wang]], [[https://openalex.org/A5013986686][Chen Ling]], [[https://openalex.org/A5040429065][Hongliang Xin]], Chem Catalysis. 4(1)] 2024. https://doi.org/10.1016/j.checat.2023.100868 
     
In this article, Hongliang Xin (associate professor at Virginia Tech), Chen Ling (senior principal research scientist at Toyota), and their colleagues discuss the critical challenges in developing high-performance electrocatalysts for the oxygen evolution reaction (OER), particularly by emphasizing the role of artificial intelligence (AI) in materials exploration and discovery. They highlight the necessity of a collaborative human-machine intelligence approach to overcome the complexities of OER catalysis and accelerate the advancement of sustainable energy solutions.    

    

** Faradically Dominant Pseudocapacitive Manganese Cobalt Oxide Electrode Materials for Hybrid Supercapacitors and Electrochemical Water Splitting   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.energyfuels.3c03444")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391044383"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391044383"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391044383"))][Get cited by]]

OpenAlex: https://openalex.org/W4391044383 (Open access: False)
    
[[https://openalex.org/A5015504249][Muhammad Zahir Iqbal]], [[https://openalex.org/A5050774711][Misbah Shaheen]], [[https://openalex.org/A5003012034][Umair Aftab]], [[https://openalex.org/A5084172156][Zubair Ahmad]], [[https://openalex.org/A5017619505][Muhammad Yameen Solangi]], [[https://openalex.org/A5039369854][Muhammad Ishaque Abro]], [[https://openalex.org/A5056919969][Saikh Mohammad Wabaidur]], No host. None(None)] 2024. https://doi.org/10.1021/acs.energyfuels.3c03444 
     
Owing to their potential usage and great electrochemical performance, transition metal oxides (TMOs) are attracting enormous interest to be scrutinized for the energy-storage and conversion domain. Our work describes the electrochemical response of spinel transition metal oxides (Co3O4 and MnCo2O4) for electrochemical water splitting (oxidation evolution reaction (OER)) and hybrid energy-storage devices. After a comprehensive study of the structure and morphology, the synthesized materials were initially evaluated for the OER performance. Mn-doped Co3O4 performed better for OER due to the inclusion of Mn ions in the spinel structure. For the OER activity, the fabricated electrode showed an overpotential of 311 mV and a Tafel slope of 71 mV/dec upon obtaining the good performance of Mn-doped Co3O4 for OER; it was further utilized for energy-storage application by fabricating its hybrid supercapacitor device with activated carbon. The hybrid supercapacitor showed a better energy (36 W h/kg) and power density (4274 W/kg) relatively. Moreover, the semiempirical approach was adapted to further elaborate the experimental results obtained. The significant response of the developed electrodes enhances their potential for future energy-storage and conversion applications.    

    

** Interface effect of MXene/CoP2 on oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.136024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391345030"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391345030"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391345030"))][Get cited by]]

OpenAlex: https://openalex.org/W4391345030 (Open access: False)
    
[[https://openalex.org/A5053911795][Xiu Juan Du]], [[https://openalex.org/A5028486288][Yan Wang]], [[https://openalex.org/A5045672660][Zicong Ye]], [[https://openalex.org/A5029061297][Wei Wang]], [[https://openalex.org/A5067124076][Yuqiao Wang]], Materials Letters. None(None)] 2024. https://doi.org/10.1016/j.matlet.2024.136024 
     
Zero/two-dimension MXene/CoP2 was fabricated by hydrothermal and chemical vapor deposition phosphate. MXene nanosheets were employed as substrate to increase dispersion and stability of the multicomponent catalyst. The morphology of CoP2 was regulated by the addtion of Co precursor in hydrothermal process. The catalyst prepared by 40 mg MXene with 0.5 mmol Co precursor (MXene/CoP2-0.5) showed a uniform growth of CoP2 and formed aboundant reaction sites. The interfacial electron transfer between MXene and CoP2 modulated the electron structure of CoP2 and stimulated the oxygen evolution reaction (OER) activity. The optimized MXene/CoP2-0.5 exhibited the OER overpotential of 263 mV and a long-term stability over 16 h. Modulating the interfacial electron transfer of multicomponent catalysts provided a guidance for electrocatalyst design and synthesis.    

    

** Reconstructing Hydrogen‐Bond Network for Efficient Acidic Oxygen Evolution   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202319462")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391328163"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391328163"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391328163"))][Get cited by]]

OpenAlex: https://openalex.org/W4391328163 (Open access: False)
    
[[https://openalex.org/A5049330397][Shicheng Zhu]], [[https://openalex.org/A5027981734][Ruoou Yang]], [[https://openalex.org/A5023169057][Huangjingwei Li]], [[https://openalex.org/A5011612912][Sirui Huang]], [[https://openalex.org/A5040389793][Haozhi Wang]], [[https://openalex.org/A5032965785][Youwen Liu]], [[https://openalex.org/A5028386144][Huiqiao Li]], [[https://openalex.org/A5069378732][Tianrui Zhai]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202319462 
     
Developing highly active oxygen evolution reaction (OER) catalysts in acidic conditions is a pressing demand for proton‐exchange membrane water electrolysis. Manipulating proton character at the electrified interface, as the crux of all proton‐coupled electrochemical reactions, is highly desirable but elusive. Herein we present a promising protocol, which reconstruct a connected hydrogen‐bond network beween the catalyst‐electrolyte interface by coupling hydrophilic units to boost acidic OER activity. Modelling on N‐doped‐carbon‐layer clothed Mn‐doped‐Co3O4 (Mn‐Co3O4@CN), we unravel that the hydrogen‐bond interaction between CN units and H2O molecule not only drags the free water to enrich the surface of Mn‐Co3O4 but also serves as a channel to promote the dehydrogenation process. Meanwhile, the modulated local charge of the Co sites from CN units/Mn dopant lowers the OER barrier. Therefore, Mn‐Co3O4@CN surpasses RuO2 at high current density (100 mA cm‐2 @ ~538 mV).    

    

** Reconstructing Hydrogen‐Bond Network for Efficient Acidic Oxygen Evolution   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202319462")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391329795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391329795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391329795"))][Get cited by]]

OpenAlex: https://openalex.org/W4391329795 (Open access: False)
    
[[https://openalex.org/A5049330397][Shicheng Zhu]], [[https://openalex.org/A5027981734][Ruoou Yang]], [[https://openalex.org/A5023169057][Huangjingwei Li]], [[https://openalex.org/A5011612912][Sirui Huang]], [[https://openalex.org/A5040389793][Haozhi Wang]], [[https://openalex.org/A5032965785][Youwen Liu]], [[https://openalex.org/A5028386144][Huiqiao Li]], [[https://openalex.org/A5069378732][Tianrui Zhai]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202319462 
     
Developing highly active oxygen evolution reaction (OER) catalysts in acidic conditions is a pressing demand for proton‐exchange membrane water electrolysis. Manipulating proton character at the electrified interface, as the crux of all proton‐coupled electrochemical reactions, is highly desirable but elusive. Herein we present a promising protocol, which reconstruct a connected hydrogen‐bond network beween the catalyst‐electrolyte interface by coupling hydrophilic units to boost acidic OER activity. Modelling on N‐doped‐carbon‐layer clothed Mn‐doped‐Co3O4 (Mn‐Co3O4@CN), we unravel that the hydrogen‐bond interaction between CN units and H2O molecule not only drags the free water to enrich the surface of Mn‐Co3O4 but also serves as a channel to promote the dehydrogenation process. Meanwhile, the modulated local charge of the Co sites from CN units/Mn dopant lowers the OER barrier. Therefore, Mn‐Co3O4@CN surpasses RuO2 at high current density (100 mA cm‐2 @ ~538 mV).    

    

** Insights on MOF-derived metal–carbon nanostructures for oxygen evolution   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3dt04263d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391225155"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391225155"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391225155"))][Get cited by]]

OpenAlex: https://openalex.org/W4391225155 (Open access: False)
    
[[https://openalex.org/A5084914364][Junliang Chen]], [[https://openalex.org/A5054473752][Jinjie Qian]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d3dt04263d 
     
Electrochemical water splitting has been regarded a promising method for the production of green hydrogen, addressing the need for efficient energy conversion and storage. However, it is severely hindered by the oxygen evolution reaction (OER) because of its multi-step four-electron transfer pathway with sluggish reaction kinetics. Microporous metal-organic-frameworks (MOFs), by virtue of large specific surface area, high porosity, tunable composition and morphology, find widespread use as precursors of metal-carbon nanostructures. The resulting carbon nanomaterials can well inherit the characteristics and advantages of the crystalline MOF precursors, and exhibit versatile application prospects in the fields of environment and energy, particularly in OER. Herein, a meticulous overview of the synthesis strategy for MOF-derived metal-carbon nanostructures and the origins of their enhanced OER properties has been demonstrated. We comprehensively illustrate these aspects across three dimensions: MOF selection, metal introduction, and carbon structures. Finally, the challenges and future prospects for this emerging field will be presented.    

    

** Enhanced catalytic activity of ZnWO4 by nickel-doping in oxygen evolution reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mssp.2024.108151")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391197664"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391197664"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391197664"))][Get cited by]]

OpenAlex: https://openalex.org/W4391197664 (Open access: False)
    
[[https://openalex.org/A5087592842][Meng Li]], [[https://openalex.org/A5086054627][Deijun Xiong]], [[https://openalex.org/A5036224962][Jinxing Wang]], [[https://openalex.org/A5082373186][Xiaoyang Dong]], [[https://openalex.org/A5069325690][Peiyang Zhang]], Materials Science in Semiconductor Processing. 173(None)] 2024. https://doi.org/10.1016/j.mssp.2024.108151 
     
The development of efficient and low-cost metal materials is indispensable in clean energy technology. Metal tungstates have previously been reported as catalysts for oxygen evolution reactions (OER). However, ZnWO4 alone does not exhibit significant catalytic activity for OER, it requires 330 mV to drive the reaction at 10 mA cm−2. To address this issue, a self-supporting electrode mixed with tungstate is synthesized by a hydrothermal method. Notably, the Ni-doped ZnWO4 self-supporting material demonstrates improved OER catalytic activity. Specifically, when comparing ZnWO4 to ZnNiWO4, it exhibits a reduced Tafel slope by 190 mV·dec−1, resulting in an overpotential of only 110 mV at 10 mA cm−2, with long-term stability for at least 20 h. Furthermore, the d-band center of ZnNiWO4 is modeled using Materials Studio and simulated through projected density of states (PDOS) calculations. These calculations reveal that the presence of Ni activates the metal ion as an OER active site with strong orbital overlap with the reaction intermediate. This adjustment in the electronic structure of the Ni–Zn metal active site during the oxygen evolution reaction alters the adsorption energy. Consequently, doping of Ni enhances the metal's ability to adsorb *OOH radical, shifting the d-band center of ZnNiWO4 further away from the Fermi level, and facilitates rapid oxygen release.    

    

** Dynamic Promotion of the Oxygen Evolution Reaction via Programmable Metal Oxides   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-gs6zn")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391172933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391172933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391172933"))][Get cited by]]

OpenAlex: https://openalex.org/W4391172933 (Open access: True)
    
[[https://openalex.org/A5030610409][Sallye Gathmann]], [[https://openalex.org/A5065773454][Christopher J. Bartel]], [[https://openalex.org/A5029991019][Lars C. Grabow]], [[https://openalex.org/A5089122189][Omar Abdel‐Rahman]], [[https://openalex.org/A5071975512][C. Daniel Frisbie]], [[https://openalex.org/A5003718847][Paul J. Dauenhauer]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-gs6zn  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65af381d66c13817290d5404/original/dynamic-promotion-of-the-oxygen-evolution-reaction-via-programmable-metal-oxides.pdf][pdf]])
     
Hydrogen gas is a promising renewable energy storage medium when produced via water electrolysis, but this process is limited by the sluggish kinetics of the anodic oxygen evolution reaction (OER). Herein, we used a microkinetic model to investigate promoting the OER using programmable oxide catalysts (i.e., forced catalyst dynamics). We found that programmable catalysts could increase current density at a fixed overpotential (100X to 600X over static rates) or reduce the overpotential required to reach a fixed current density of 10 mA/cm^2 (45 – 140% reduction vs. static). In our kinetic parameterization, the key parameters controlling the quality of the catalytic ratchet were the O*-to-OOH* and O*-to-OH* activation barriers. Our findings indicate that programmable catalysts may be a viable strategy for accelerating the OER or enabling lower-overpotential operation, but a more accurate kinetic parameterization is required for precise predictions of performance, ratchet quality, and resulting energy efficiency.    

    

** Fabrication of hexagonal Cu2O nanocrystals on CNTs for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpcs.2023.111853")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391179968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391179968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391179968"))][Get cited by]]

OpenAlex: https://openalex.org/W4391179968 (Open access: False)
    
[[https://openalex.org/A5083753418][Salma Aman]], [[https://openalex.org/A5018207831][Meznah M. Alanazi]], [[https://openalex.org/A5008098859][Shaimaa A. M. Abdelmohsen]], [[https://openalex.org/A5088716481][Saeed D. Alahmari]], [[https://openalex.org/A5078102681][Abdullah G. Al‐Sehemi]], [[https://openalex.org/A5014861084][Muhammad Suleman Waheed]], [[https://openalex.org/A5051797797][A.M.A. Henaish]], [[https://openalex.org/A5084172156][Zubair Ahmad]], [[https://openalex.org/A5001974005][Hafiz Muhammad Tahir Farid]], Journal of Physics and Chemistry of Solids. None(None)] 2024. https://doi.org/10.1016/j.jpcs.2023.111853 
     
Electrocatalytic water (H2O) splitting relies heavily on the rational formation of most effective, long-lasting catalysts that should be cheaper and earth abundant. Therefore, an effective electrocatalyst is the need of the hour that may effectively pursue both electrocatalytic OER and HER. This study paves the way for the straightforward preparation of conductive polymer tailored metal oxide nanocomposite Cu2O/CNTs by a facile hydrothermal approach to be employed as overall water splitting electrocatalyst. The techniques comprising SEM, XRD, EDX and the BET test were employed to characterize the synthesized Cu2O/CNTs electrocatalyst. The generated Cu2O/CNTs electrocatalysts exhibited a Tafel value of 39 mV/dec, an overpotential of 267 mV@10 mA/cm2, and stability of OER activity that lasted for at least 70 hours. The electrocatalytic results show that the combination of Cu2O and CNTs has a synergistic impact to reduce the overpotential value. In an effort to pinpoint the rate determining processes for OER, the voltage of OER is connected to the electrolyte pH and exhibits a non-proton concerted approach. The above designed nanocomposite is quite promising for modern hydrogen production systems due to their quick electron transfer mechanism, remarkable durability, and good activity for OER.    

    

** Efficient oxygen evolution using conductive cobalt-based metal-organic framework   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131044")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391143814"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391143814"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391143814"))][Get cited by]]

OpenAlex: https://openalex.org/W4391143814 (Open access: False)
    
[[https://openalex.org/A5061145215][Munzir H. Suliman]], [[https://openalex.org/A5025288698][Lolwah Tawfiq Alfuhaid]], [[https://openalex.org/A5042532738][Mohd Yusuf Khan]], [[https://openalex.org/A5090138718][Muhammad Usman]], [[https://openalex.org/A5088210851][Aasif Helal]], Fuel. 363(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131044 
     
The electrically conductive Cobalt-benzene-1,3,5-tribenzoate metal–organic framework (Co-BTB) was easily synthesized using the hydrothermal synthesis process. The framework showed a low overpotential (only 170 mV to obtain 10 mA cm−2) for the oxygen evolution reaction (OER) surpassing the benchmark electrocatalyst IrO2 which showed an overpotential of 250 mV at the same obtained current density. Moreover, the Co-BTB possesses good kinetics with an estimated Tafel slope of only 46.5 mV dec−1. It provided a high density of catalytic centers with electrically conductive characteristics, as suggested by ECSA. The framework was identified as a promising MOF electrocatalyst for the OER due to its performance as well as its chemical and electrochemical robustness.    

    

** Spinel-type high-entropy oxide nanotubes for efficient oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.colsurfa.2024.133315")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391177777"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391177777"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391177777"))][Get cited by]]

OpenAlex: https://openalex.org/W4391177777 (Open access: False)
    
[[https://openalex.org/A5046042839][Yanbin Zhu]], [[https://openalex.org/A5070686219][Qing Xiang]], [[https://openalex.org/A5050156870][Guo Le]], [[https://openalex.org/A5060213367][Shuanglong Lu]], [[https://openalex.org/A5067758457][Fang Duan]], [[https://openalex.org/A5036927789][Mingliang Du]], [[https://openalex.org/A5014327956][Han Zhu]], Colloids and Surfaces A: Physicochemical and Engineering Aspects. None(None)] 2024. https://doi.org/10.1016/j.colsurfa.2024.133315 
     
Oxygen evolution reaction (OER) involved 4-electron transfers is generally considered as the bottleneck for electrocatalytic water splitting. High-entropy oxides (HEO) show promising potential for OER due to their flexible structures and tunable compositions. Herein, we report a facile strategy to synthesize spinel-type (FeCoNiMnCr)3O4 HEO nanotubes (NTs) with unique hollow structures by combining electrospinning process and calcination treatment. The (FeCoNiMnCr)3O4 HEO NTs prepared at 400 °C exhibit the low overpotential of 353 mV at 50 mA cm-2 and small Tafel slope of 55.6 mV dec-1 in 1 M KOH electrolyte. The three-dimensional (3D) nanofiber-based architecture ensure the superior stability, as evidenced by the stable current density under continuous OER process for more than 60 h. Meanwhile, the hollow structure provides abundant exposed active sites, which could significantly improve the OER activity. This work provides new design of low-cost and high-efficient HEO with ensemble active sites for OER.    

    

** Carbon nanotubes immobilized copper(salen) nanocomposite for electrochemical oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.56042/ijc.v63i1.2312")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391174987"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391174987"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391174987"))][Get cited by]]

OpenAlex: https://openalex.org/W4391174987 (Open access: True)
    
, Indian Journal of Chemistry. 63(1)] 2024. https://doi.org/10.56042/ijc.v63i1.2312  ([[https://or.niscpr.res.in/index.php/IJC/article/download/2312/2438][pdf]])
     
An efficient oxygen evolution reaction (OER) electrocatalysts are widely required in the realm of water electrolysis and rechargeable metal-air batteries. This work describes an easy and simple method for the synthesis of copper salen (Cu(Salen))-functionalized multiwalled carbon nanotubes (MWCNTs) nanocomposite materials (Cu(Salen)/MWCNTs). It was used for OER in the basic medium (0.1 M KOH). The resulting nanocomposite, Cu(Salen)/MWCNTs, was studied using spectroscopic and microscopic techniques. For example, Fourier transform infrared (FT-IR), UV-visible spectroscopy, powder X-ray diffraction (p-XRD), scanning electron microscopy (SEM), and energy dispersive X-ray analysis (EDAX). The electrochemical characterization of prepared Cu(Salen)/MWCNTs nanocomposite based modified glassy carbon (GC) electrodes (GC/Cu(Salen)/MWCNTs) and their application towards OER were performed using an electrochemical method. The Tafel slope of nanocomposite material is 159.6 mv/dec in 0.1 M KOH solution, indicating that GC/Cu(Salen)/MWCNTs could be a promising and cost-effective electrode material for the OER. This study demonstrates a novel way for creating an active nanocomposite catalyst for OER in alkaline media.    

    

** Strategic Design and Insights into Lanthanum and Strontium Perovskite Oxides for Oxygen Reduction and Oxygen Evolution Reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202308443")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391142464"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391142464"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391142464"))][Get cited by]]

OpenAlex: https://openalex.org/W4391142464 (Open access: False)
    
[[https://openalex.org/A5050236680][Sagar Ingavale]], [[https://openalex.org/A5036345289][Mohan Gopalakrishnan]], [[https://openalex.org/A5092896607][Carolin Mercy Enoch]], [[https://openalex.org/A5067676218][Chanon Pornrungroj]], [[https://openalex.org/A5000448228][Meena Rittiruam]], [[https://openalex.org/A5036226683][Supareak Praserthdam]], [[https://openalex.org/A5007823738][Anongnat Somwangthanaroj]], [[https://openalex.org/A5093770957][Kasadit Nootong]], [[https://openalex.org/A5074004594][Rojana Pornprasertsuk]], [[https://openalex.org/A5081163390][Soorathep Kheawhom]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202308443 
     
Abstract Perovskite oxides exhibit bifunctional activity for both oxygen reduction (ORR) and oxygen evolution reactions (OER), making them prime candidates for energy conversion in applications like fuel cells and metal‐air batteries. Their intrinsic catalytic prowess, combined with low‐cost, abundance, and diversity, positions them as compelling alternatives to noble metal and metal oxides catalysts. This review encapsulates the nuances of perovskite oxide structures and synthesis techniques, providing insight into pivotal active sites that underscore their bifunctional behavior. The focus centers on the breakthroughs surrounding lanthanum (La) and strontium (Sr)‐based perovskite oxides, specifically their roles in zinc‐air batteries (ZABs). An introduction to the mechanisms of ORR and OER is provided. Moreover, the light is shed on strategies and determinants central to optimizing the bifunctional performance of La and Sr‐based perovskite oxides.    

    

** NiCo2O4/MXene hybrid as an efficient bifunctional electrocatalyst for oxygen evolution and reduction reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301250")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391296391"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391296391"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391296391"))][Get cited by]]

OpenAlex: https://openalex.org/W4391296391 (Open access: False)
    
[[https://openalex.org/A5016038695][Ashalatha Vazhayil]], [[https://openalex.org/A5015987837][Vazhayal Linsha]], [[https://openalex.org/A5086819981][Shyamli Ashok C]], [[https://openalex.org/A5087024992][Jasmine Thomas]], [[https://openalex.org/A5053127989][Nygil Thomas]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301250 
     
For the advancement of energy conversion and storage technologies, bifunctional electrocatalysts are crucial for efficiently driving both the oxygen evolution (OER) and reduction reactions (ORR). Cobalt‐based spinel oxides are a class of promising bifunctional electrocatalysts. However their low electrical conductivity and stability may hinder further improvement. A novel composite material composed of NiCo2O4(NCO) nanoparticles integrated with emerging two dimensional MXene nanosheets (NCO/MXene) was developed. The successful integration of NCO with MXene brings about a number of attractive structural features. This includes synergistic effects between NCO and MXene, highly accessible surface areas, complete exposure of numerous active sites, and excellent electronic conductivity, all of which collectively contribute to the desirability of composite material for OER and ORR. The synthesized NCO/MXene composite showed extraordinary OER electrocatalytic activity with a lower overpotential of 360 mV at a current density of 10 mA/cm2, and a small Tafel slope of 64.63 mV/dec compared to NCO, MXene and NCO+MXene (physically mixed). Additionally, it displays a superior ORR limiting current density (‐4 mA/cm2). In particular, it exhibited highest onset potential and half wave potential of 0.92 V and 0.72 V vs. RHE, respectively, for the ORR in alkaline media    

    

** Novel Amorphous Feooh-Modified Co9s8 Nanosheets with Enhanced Oxygen Evolution Reaction Activity   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4711575")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391405828"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391405828"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391405828"))][Get cited by]]

OpenAlex: https://openalex.org/W4391405828 (Open access: False)
    
[[https://openalex.org/A5007803202][Chong Wang]], [[https://openalex.org/A5036746330][Huanlu Tu]], [[https://openalex.org/A5071814351][Zeyu Hao]], [[https://openalex.org/A5037742951][Yaxin Li]], [[https://openalex.org/A5038906848][Jing Xu]], [[https://openalex.org/A5016312685][Xiaoying Hu]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5037428389][Hongwei Tian]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4711575 
     
Efficient oxygen evolution reaction (OER) is important for water electrolysis and advanced hydrogen production energy. However, the sluggish kinetics of this reaction require significant overpotentials, leading to high energy consumption. Therefore, developing OER electrocatalysts with exceptional performance and long-term durability is crucial for enhancing the energy efficiency and cost-effectiveness of the hydrogen production process. In this paper, novel FeOOH/Co9S8 catalysts were prepared through a two-step hydrothermal reaction followed by one-step electrodeposition on nickel foam substrates for an alkaline oxygen evolution reaction (OER). The as-obtained catalysts possessed abundant non-homogeneous interfaces between FeOOH and Co9S8 nanosheets, conducive to optimized coordination environments of Fe and Co sites through the redistribution of interfacial charges. This strengthened the chemisorption of oxygenated intermediates, leading to accelerated reaction kinetics, abundant active sites, and enhanced OER properties. The optimized electrocatalyst FeOOH/Co9S8 achieved a current density of 10 mA cm-2 at an overpotential of 248 mV coupled with good stability for over 140 h. Overall, a novel approach for producing effective and durable alkaline dielectric OER electrocatalysts was proposed, useful for future manufacturing of advanced energy devices.    

    

** Machine Learning-Based Optimization Method for the Oxygen Evolution and Reduction Reaction of the High-Entropy Alloy Catalysts   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.17762/ijritcc.v11i9.9214")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391330920"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391330920"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391330920"))][Get cited by]]

OpenAlex: https://openalex.org/W4391330920 (Open access: True)
    
[[https://openalex.org/A5093816237][Et al. Jagannath Jijaba Kadam]], International Journal on Recent and Innovation Trends in Computing and Communication. 11(9)] 2023. https://doi.org/10.17762/ijritcc.v11i9.9214 
     
In recent times, high-entropy alloys (HEAs) have found application in heterogeneous catalysis, capitalizing on their vast chemical potential. Yet, this extensive chemical landscape presents significant challenges when attempting a comprehensive exploration of HEAs through traditional trial-and-error approaches. Therefore, the machine learning (ML) approach is offered to appearance into the catalytic activity (CA) of countless sensitive sites on HEA surfaces in the oxygen-lessening response (ORR) and oxygen evolution reactions (OER). In this research, a Density Functional Theory (DFT) with a supervised ML model is assembled and founded on the gradient boosting regression (GBR) algorithm that predicted the O2 adsorption energies with a high overpotential of all surface sites on the two HEAs. Initially, the HEAs Co-Fe-Ga-Ni-Zn and Al-Cu-Pd-Pt offer a framework for adjusting the composition of disordered multi-metallic alloys to regulate the activity and selectivity of the reduction of oxygen to extremely reduced compounds. This attains generalizability, high accuracy and simplicity with the proposed technique. For fine-tuning such features, HEAs provide a huge compositional space. Consequently, the research reports the custom of the Bayesian optimization model based on HEA active compositions to suppress the formation of Oxygen (O2) and with strong O2 adsorption to favour the lessening of O2. The GBR approach is applied to build a highly accurate, easily generalizable, and effective ML model. The proposed work is analysed using Python software. The findings show that the separate charities of correlated metal atoms close to the responsive site are mixed to form the adsorption energy, which is clear from a thorough analysis of the data. It is suggested that a highly effective HEA catalyst composed of Co-Fe-Ga-Ni-Zn and Al-Cu-Pd-Pt be exploited, which is an effective method for further enhancing the ORR CA of potential HEA catalysts. An instruction manual for the logical design and synthesis of HEA catalysts' nanostructures is provided by the proposed research.    

    

** Tungsten-doped cobalt-iron bimetallic phosphide nanoparticles for enhanced oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jtice.2024.105356")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057421"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057421"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057421"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057421 (Open access: False)
    
[[https://openalex.org/A5029733101][Yaoxia Yang]], [[https://openalex.org/A5076729121][Dangxia Wang]], [[https://openalex.org/A5078314562][Xingwei Guo]], [[https://openalex.org/A5072659920][Fengyao Guo]], [[https://openalex.org/A5067107304][Zhang Lan]], [[https://openalex.org/A5032918016][Dongfei Sun]], [[https://openalex.org/A5081104591][Xiaozhong Zhou]], [[https://openalex.org/A5031098226][Zhiwang Yang]], [[https://openalex.org/A5026631111][Ziqiang Lei]], Journal of the Taiwan Institute of Chemical Engineers. 156(None)] 2024. https://doi.org/10.1016/j.jtice.2024.105356 
     
Hydrogen obtained from electrochemical water splitting is an efficient method for hydrogen production, which is urgent to develop high efficiency electrocatalyst and commercialize the process. In our work, we used coprecipitation, doping and phosphating strategies to report the trimetallic Prussian blue analogue precursors (W-CoFe PBA) were prepared by doping sodium tungstate into cobalt-iron-Prussian blue analogues (CoFe PBA), and then by a low temperature phosphating treatment to obtain tungsten doped cobalt-iron phosphide (W-CoP/FeP) heterostructures. This strategy of doping and then phosphating can allow the charge distribution is adjusted, the conductivity is increased, the electron transport to the surface is accelerated, and the synergistic effect between CoP and FeP is enhanced. The experimental results show that the mass ratio of tungsten source to CoFe-PBA is 0.5 (0.5W-CoP/FeP), which shows outstanding activity with overpotentials of 282 mV for the oxygen evolution reaction (OER) in 1 M KOH at a current density of 10 mA cm−2 and Tafel slope of 29.14 mV dec−1. Simultaneously, it also exhibits excellent stability for 24 h in the chronopotentiometry test. This work provides a simple improvement for the application of Prussian blue analogues in the electrochemical water splitting.    

    

** Constructing highly efficient bifunctional catalysts for oxygen reduction and oxygen evolution by modifying MXene with transition metal   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.089")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391063505"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391063505"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391063505"))][Get cited by]]

OpenAlex: https://openalex.org/W4391063505 (Open access: False)
    
[[https://openalex.org/A5061630253][Dai Yu]], [[https://openalex.org/A5047850201][Xiuyun Zhao]], [[https://openalex.org/A5016833284][Desheng Zheng]], [[https://openalex.org/A5059700536][Qingrui Zhao]], [[https://openalex.org/A5082664273][Jing Feng]], [[https://openalex.org/A5019670440][Yingjie Feng]], [[https://openalex.org/A5063446819][Xingbo Ge]], [[https://openalex.org/A5024977426][Xin Chen]], Journal of Colloid and Interface Science. 660(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.089 
     
Exploring highly active electrocatalysts for oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) has become a growing interest in recent years. Herein, an efficient pathway for designing MXene-based ORR/OER catalysts is proposed. It involves introducing non-noble metals into Vo (vacancy site), H1 and H2 (the hollow sites on top of C and the metal atom, respectively) sites on M2CO2 surfaces, named TM-VO/H1/H2-M2CO2 (TM = Fe, Co, Ni, M = V, Nb, Ta). Among these recombination catalysts, Co-H1-V2CO2 and Ni-H1-V2CO2 exhibit the most promising ORR catalytic activities, with low overpotential values of 0.35 and 0.37 V, respectively. Similarly, Fe-H1-V2CO2, Co-VO-Nb2CO2, and Ni-H2-Nb2CO2 possess low OER overpotential values of 0.29, 0.39, and 0.44 V, respectively, suggesting they have enormous potential as effective catalysts for OER. Notably, Co-H2-Ta2CO2 possesses the lowest potential gap value of 0.53 V, demonstrating it has an extraordinary bifunctional catalytic activity. The excellent catalytic performance of these recombination catalysts can be elucidated through an electronic structure analysis, which primarily relies on the electron-donating capacity and synergistic effects between transition metals and sub-metals. These results provide theoretical guidance for designing new ORR and OER catalysts using 2D MXene materials.    

    

** Mixed-valent cobalt phosphate/borophene nanohybrids for efficient electrocatalytic oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.188")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391319509"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391319509"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391319509"))][Get cited by]]

OpenAlex: https://openalex.org/W4391319509 (Open access: False)
    
[[https://openalex.org/A5016235312][Bitan Pratihar]], [[https://openalex.org/A5048541923][Omkar Roy]], [[https://openalex.org/A5080383377][Arijit Jana]], [[https://openalex.org/A5021909284][Sirshendu De]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.188 
     
Developing efficient, low-cost, non-precious and stable electrocatalyst is necessary for sustainable electrocatalytic water splitting. Recently, borophene has emerged as a novel two-dimensional material with exciting properties. Although several researchers have theoretically predicted its applicability towards effective electrocatalytic water splitting, studies on its practical applications are still limited. In this regard, a mixed-valent cobalt phosphate/borophene nanohybrid (BCoPi) was synthesized using hydrothermal method, and its activity towards oxygen evolution reaction (OER) was systematically studied. The electron-deficient nature of borophene enables activation of catalytic sites and facilitates electron transport owing to its highly conductive nature. It can act as a proton acceptor along with phosphate groups, as well as provide multiple secondary active sites in addition to Co, breaking the scaling relation of OER. For BCoPi, achieving a current density of 50 mA cm−2, 100 mA cm−2 and 500 mA cm−2 requires an overpotential of 337 mV, 357 mV and 401 mV, respectively, in an alkaline medium, that are superior to pristine cobalt phosphate (CoPi). It also exhibits low Tafel slope of 61.81 mV dec−1, suggesting faster OER kinetics and excellent long-term stability. This study will extend the development and application of borophene-based heterostructures for highly active and stable electrocatalysts for various applications.    

    

** Exploring the role of iron in Fe5Ni4S8 toward oxygen evolution through modulation of electronic orbital occupancy   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.01.028")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391152145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391152145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391152145"))][Get cited by]]

OpenAlex: https://openalex.org/W4391152145 (Open access: False)
    
[[https://openalex.org/A5070671117][Zhengyan Du]], [[https://openalex.org/A5069619264][Zeshuo Meng]], [[https://openalex.org/A5035280619][H. Sun]], [[https://openalex.org/A5085794085][Yifan Li]], [[https://openalex.org/A5018421780][Chao Jiang]], [[https://openalex.org/A5037742951][Yaxin Li]], [[https://openalex.org/A5016312685][Xiaoying Hu]], [[https://openalex.org/A5063995082][Yi Cui]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5037428389][Hongwei Tian]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.01.028 
     
Ni-Fe-based catalysts are considered to be among the most active catalysts for the oxygen evolution reaction (OER) under alkaline conditions, with Fe playing a crucial role. However, Fe leaching occurs during the reaction due to thermodynamic instability, which has resulted in conflicting reports within the literature regarding its role. To clarify this point, we propose a strategy consisting of modulating the electronic orbital occupancy to suppress the extensive loss of Fe atoms during the OER process. Theoretical calculations, in-situ X-ray photoelectron spectroscopy, molecular dynamics simulations, and a series of characterization showed that the stable presence of Fe not only accelerates the electron transfer process but also optimizes the reaction barriers of the oxygen evolution intermediates, promoting the phase transition of Fe5Ni4S8 to highly active catalytic species. The modulated Fe5Ni4S8-based pre-catalysts exhibit improved OER activity and long-term durability. This study provides a novel perspective for understanding the role of Fe in the OER process.    

    

** Co atom-doped NiMoO4 Hierarchical hollow nanosheet-based-nanosphere for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.22541/au.170664116.61933326/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391343114"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391343114"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391343114"))][Get cited by]]

OpenAlex: https://openalex.org/W4391343114 (Open access: False)
    
[[https://openalex.org/A5012770110][Zhuoxun Yin]], [[https://openalex.org/A5045073916][Min Zhou]], [[https://openalex.org/A5018077554][Xinping Li]], [[https://openalex.org/A5057117758][Xiangcun Liu]], [[https://openalex.org/A5070267350][Xinzhi Ma]], [[https://openalex.org/A5020624661][Yang Zhou]], [[https://openalex.org/A5017541508][Wei Chen]], [[https://openalex.org/A5086155499][Jinlong Li]], No host. None(None)] 2024. https://doi.org/10.22541/au.170664116.61933326/v1 
     
Hollow structures with hierarchical architecture and multi-composition have attracted extensive interest because of their fascinating physicochemical properties as well as wide applications. to improve the efficiency of overall water splitting, highly active and stable electrocatalysts are highly desirable. A novel high-efficiency Hierarchical hollow nanosheet-based-nanosphere Co-NiMoO4-HNS electrocatalyst for oxygen evolution was arranged by doping Co on Ni-MoEG yolk/shelll nanosphere. Remarkably, the hierarchical hollow Co2-NiMoO4-HNS catalyst exhibits favorable catalytic performance toward the oxygen evolution reaction (OER) with a receivable overpotential of 270 mV achieving a current density of 10 mA cm−2 and a Tafel slope of 65 mV dec−1. In expansion, as a electrocatalyst, Co2-NiMo4-HNS appeared to have great long-term steadiness in the electrolyte. This work may give broad hypothetical and specialized back for the plan of cost-effective bifunctional electrocatalysts.    

    

** Efficient Oxygen Evolution Reaction by Ru(II) Polypyridyl Complex based AIEgen   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3qi02380j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987133"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987133"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987133"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987133 (Open access: False)
    
[[https://openalex.org/A5071842308][Snehadrinarayan Khatua]], [[https://openalex.org/A5058986428][Monosh Rabha]], [[https://openalex.org/A5047379472][Sreenivasan Nagappan]], [[https://openalex.org/A5029602773][Bhaskar Sen]], [[https://openalex.org/A5031222788][Khanindram Baruah]], [[https://openalex.org/A5067628877][Subrata Kundu]], No host. None(None)] 2024. https://doi.org/10.1039/d3qi02380j 
     
Ruthenium polypyridyl complexes are known for their excellent photophysical properties and rich electrochemical behavior. Thus, developing complexes with multifunctional behavior showing potential applications in multiple fields is of great importance....    

    

** Cop Nanoparticles Embedded in N-Doped Carbon for Highly Efficient Oxygen Evolution Reaction Electrocatalysis   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4710700")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391365597"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391365597"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391365597"))][Get cited by]]

OpenAlex: https://openalex.org/W4391365597 (Open access: False)
    
[[https://openalex.org/A5006592632][Zewu Zhang]], [[https://openalex.org/A5070879896][Yifan Dai]], [[https://openalex.org/A5075427631][L.Y. Chen]], [[https://openalex.org/A5004600892][Jiakai Bai]], [[https://openalex.org/A5061173049][Xiaohai Bu]], [[https://openalex.org/A5022583323][Jiehua Bao]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4710700 
     
Development of high-activity and low-cost electrocatalysts is significant to enhance the low-kinetic process of oxygen evolution reaction (OER). In this paper, we utilized the self-assembly between melamine, phytic acid and cobalt ions to obtain two-dimensional Co-MPA. Subsequently, in situ phosphating of Co ions to obtain CoP/N-CNT was achieved by the pyrolytic of Co-MPA. The small size of CoP (~18 nm) and the N-doped carbon material endowed CoP/N-CNT with excellent OER electrocatalytic activity, which delivered an overpotential of 285 mV to drive a current density of 10 mA cm-2. Moreover, the TOF value of CoP/N-CNT catalyst is 4.6 times higher than the incumbent commercial RuO2 catalyst (at the overpotential of 480 mV), providing it as a promising electrocatalyst for OER.    

    

** Novel two-dimensional boron-centered graphdiyne analogue as multifunctional electrocatalyst for hydrogen evolution, oxygen evolution, and oxygen reduction reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.278")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391301139"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391301139"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391301139"))][Get cited by]]

OpenAlex: https://openalex.org/W4391301139 (Open access: False)
    
[[https://openalex.org/A5046078938][Cong Wang]], [[https://openalex.org/A5006822602][Xin Wang]], [[https://openalex.org/A5072373593][Donglai Han]], [[https://openalex.org/A5042379128][Jing Song]], [[https://openalex.org/A5054852294][Zhong‐Min Su]], [[https://openalex.org/A5060649823][Min Zhang]], International Journal of Hydrogen Energy. 58(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.01.278 
     
Seeking multifunctional electrocatalysts capable of driving the hydrogen evolution reaction (HER), oxygen evolution reaction (OER), and oxygen reduction reaction (ORR) is becoming increasingly crucial in the realm of sustainable energy development. Herein, the multifunctional electrocatalytic activities of HER, OER, and ORR in two-dimensional (2D) boron-centered graphdiyne analogue (B-GDY) are identified by first-principles computations, and its low overpotentials of HER/OER/ORR (0.02/0.55/0.52 V) are comparable to, or even surpasses, well-developed noble-metal-based catalysts. The remarkable multifunctional electrocatalytic activity of B-GDY can be attributed to the unique orbital distribution of the 2D framework as evidenced by its highest occupied molecular orbitals (HOMO), and synergistic interplay of boron-centered carbocycles and diacetylene linkages in its unique 2D framework. More importantly, the data confirm our motivation by replacing the central C in small aromatic groups with the adjacent element of B can realize/create multi-active sites in the original aromatic functional groups (the simplest boron-centered triangulene-like units). Hence, this study not only provides cost-effective alternatives to metal-based catalysts but also paves the way for designing and developing novel, multifunctional electrocatalysts.    

    

** Sputter‐Deposited La–Co–Mn–O Nanocolumns as Stable Electrocatalyst for the Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/sstr.202300415")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391328293"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391328293"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391328293"))][Get cited by]]

OpenAlex: https://openalex.org/W4391328293 (Open access: True)
    
[[https://openalex.org/A5051844684][Tobias Horst Piotrowiak]], [[https://openalex.org/A5067459856][Olga A. Krysiak]], [[https://openalex.org/A5054007615][Ellen Suhr]], [[https://openalex.org/A5051585830][Jian Zhang]], [[https://openalex.org/A5081079430][Rico Zehl]], [[https://openalex.org/A5050028599][Aleksander Kostka]], [[https://openalex.org/A5035321019][Wolfgang Schuhmann]], [[https://openalex.org/A5048192399][Alfred Ludwig]], No host. None(None)] 2024. https://doi.org/10.1002/sstr.202300415  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/sstr.202300415][pdf]])
     
A thin‐film materials library (ML) of the La–Co–Mn–O system is fabricated by hot reactive combinatorial cosputter deposition and screened for its electrocatalytic activity for the oxygen evolution reaction. Within this ML, an area with superior catalytic activity is identified. In‐depth characterization of this region reveals a unique columnar‐grown microstructure showing a large catalytic surface and excellent stability during electrocatalytic measurements. A zoom‐in into these structures shows that the columns are compositionally and structurally not homogeneous but are composed of a mixture of the perovskite phase LaCoMnO 3 and Co–Mn–O oxide. Nanoelectrochemistry using the particle on a nanoelectrode approach confirms the high activity as well as stability of the single columns.    

    
