#+TITLE: water splitting
Description: water splitting papers
Created on Fri Mar 29 00:43:49 2024

Found 37 results from 2024-03-22 to 2024-03-29
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Revolutionizing Zn-Air batteries with chainmail catalysts: Ultrathin carbon-encapsulated FeNi alloys on N-doped graphene for enhanced oxygen electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393033727
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/s1872-2067(23)64603-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393033727"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393033727"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393033727"))][Get cited by]]

OpenAlex: https://openalex.org/W4393033727 (Open access: False)
    
[[https://openalex.org/A5035673043][Yibo Guo]], [[https://openalex.org/A5006614081][Yuanyuan Xue]], [[https://openalex.org/A5078316246][Zhen Zhou]], Chinese Journal of Catalysis. 58(None)] 2024. https://doi.org/10.1016/s1872-2067(23)64603-0 
     
No abstract    

    

* Material dynamics for active and resilient oxygen evolution reaction in acid media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393037886
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.checat.2024.100956")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393037886"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393037886"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393037886"))][Get cited by]]

OpenAlex: https://openalex.org/W4393037886 (Open access: False)
    
[[https://openalex.org/A5035194297][Juliana Carneiro]], [[https://openalex.org/A5010742433][Daniela V. Fraga Alvarez]], Chem Catalysis. 4(3)] 2024. https://doi.org/10.1016/j.checat.2024.100956 
     
No abstract    

    

* Efficient Machine Learning Model Focusing on Active Sites for the Discovery of Bifunctional Oxygen Electrocatalysts in Binary Alloys  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393039373
:TOPICS: Accelerating Materials Innovation through Informatics, Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.3c17377")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393039373"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393039373"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393039373"))][Get cited by]]

OpenAlex: https://openalex.org/W4393039373 (Open access: False)
    
[[https://openalex.org/A5049867502][C Y Wang]], [[https://openalex.org/A5006421709][Bing Wang]], [[https://openalex.org/A5053689795][Changhao Wang]], [[https://openalex.org/A5086456117][Zhipeng Chang]], [[https://openalex.org/A5041426175][Mengqi Yang]], [[https://openalex.org/A5048314994][Ruzhi Wang]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.3c17377 
     
No abstract    

    

* Heterointerface Engineering of hollow CoP/CeO2 p-n heterojunction for Efficient Electrocatalytic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393047353
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104227")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393047353"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393047353"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393047353"))][Get cited by]]

OpenAlex: https://openalex.org/W4393047353 (Open access: False)
    
[[https://openalex.org/A5008678513][Xiaofan Zhang]], [[https://openalex.org/A5052469496][Zhao-Rong Lai]], [[https://openalex.org/A5040793911][Yipeng Ye]], [[https://openalex.org/A5082160863][Xiaojing Su]], [[https://openalex.org/A5059393955][Huali Xie]], [[https://openalex.org/A5066449275][Yunhui Wu]], [[https://openalex.org/A5011482160][Kunquan Li]], [[https://openalex.org/A5055688440][Wenjian Wu]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104227 
     
No abstract    

    

* MOF-mediated synthesis of novel PtFeCoNiMn high-entropy nanoalloy as bifunctional oxygen electrocatalysts for zinc-air battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393049171
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12274-024-6526-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393049171"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393049171"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393049171"))][Get cited by]]

OpenAlex: https://openalex.org/W4393049171 (Open access: False)
    
[[https://openalex.org/A5030147208][Mingyu Xie]], [[https://openalex.org/A5016588737][Xin Xiao]], [[https://openalex.org/A5007672814][Duojie Wu]], [[https://openalex.org/A5039483901][Zhihui Cheng]], [[https://openalex.org/A5022688859][Chunsheng Wu]], [[https://openalex.org/A5046732096][Wenjuan Wang]], [[https://openalex.org/A5006424865][Hao Nian]], [[https://openalex.org/A5001551387][Fayan Li]], [[https://openalex.org/A5075853475][Meng Gu]], [[https://openalex.org/A5064109029][Qiang Xu]], Nano Research. None(None)] 2024. https://doi.org/10.1007/s12274-024-6526-4 
     
No abstract    

    

* Chemical Fabrication and Synergistic Mechanism of N-doped Carbon Modified with FeP as Catalysts for Flexible Rechargeable Zn-Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393049690
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4se00197d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393049690"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393049690"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393049690"))][Get cited by]]

OpenAlex: https://openalex.org/W4393049690 (Open access: False)
    
[[https://openalex.org/A5032240987][Xianli Wu]], [[https://openalex.org/A5076664714][Ting Zhou]], [[https://openalex.org/A5034292850][Gaorong Han]], [[https://openalex.org/A5051323527][Shilin Liu]], [[https://openalex.org/A5030318973][Mengmeng Cao]], [[https://openalex.org/A5091316366][Shu-Qi Li]], [[https://openalex.org/A5045058519][Jiawen Wang]], [[https://openalex.org/A5090455604][Yanyan Liu]], [[https://openalex.org/A5083684958][Jianchun Jiang]], [[https://openalex.org/A5042348933][Yongfeng Wang]], [[https://openalex.org/A5036975470][Baojun Li]], Sustainable Energy and Fuels. None(None)] 2024. https://doi.org/10.1039/d4se00197d 
     
Low-cost and efficient electrocatalysts for oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) are vital for the applications of flexible rechargeable Zinc-air batteries (ZABs). Herein, three-dimensional (3D) porous N-doping...    

    

* Achieving Superior Oxygen Evolution of Perovskite via Phase Transition and Electrochemical Reconstruction Strategy  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393050021
:TOPICS: Solid Oxide Fuel Cells, Perovskite Solar Cell Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ee04338j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393050021"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393050021"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393050021"))][Get cited by]]

OpenAlex: https://openalex.org/W4393050021 (Open access: False)
    
[[https://openalex.org/A5024624524][Yi-Ru Hao]], [[https://openalex.org/A5057436798][Huaiguo Xue]], [[https://openalex.org/A5032829548][Junqi Sun]], [[https://openalex.org/A5084790005][Niankun Guo]], [[https://openalex.org/A5043086390][Tianshan Song]], [[https://openalex.org/A5017933165][Hongliang Dong]], [[https://openalex.org/A5023763385][Zhonglong Zhao]], [[https://openalex.org/A5084434322][Jiangwei Zhang]], [[https://openalex.org/A5061445988][Aiqin Wang]], [[https://openalex.org/A5050141240][Limin Wu]], Energy and Environmental Science. None(None)] 2024. https://doi.org/10.1039/d3ee04338j 
     
Surface reconstruction is an effective strategy to improve the OER performance of perovskite. However, understanding the reconstruction kinetics of perovskite and revealing real active sites for OER remain elusive. Herein,...    

    

* Activating Lattice Oxygen in a Nanoporous Crystalline/Amorphous NiFe(II, III)OxHy Heterostructure for Electrocatalytic Water Oxidation with Ampere-Level Activity and Durability  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393056441
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-03-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acssuschemeng.4c00318")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393056441"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393056441"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393056441"))][Get cited by]]

OpenAlex: https://openalex.org/W4393056441 (Open access: False)
    
[[https://openalex.org/A5000653833][Yu Tang]], [[https://openalex.org/A5009096186][Wen Ge]], [[https://openalex.org/A5077453931][Lanxian Shen]], [[https://openalex.org/A5070120794][Peizhi Yang]], [[https://openalex.org/A5003875622][Shukang Deng]], [[https://openalex.org/A5019464613][Jinsong Wang]], ACS Sustainable Chemistry & Engineering. None(None)] 2024. https://doi.org/10.1021/acssuschemeng.4c00318 
     
Developing oxygen evolution reaction (OER) electrocatalysts with ampere-level activity and durability is an open challenge toward the final industrial application. Here, a nanoporous crystalline/amorphous nickel–iron oxyhydroxide heterostructure with abundant Fe2+ (c/a NiFe(II, III)OxHy) by partially substituting Ni2+ with Fe2+ is reported. Combination of X-ray absorption spectroscopy, in situ Raman, and density functional theory investigation suggested that the crystalline/amorphous structure with abundant cation defects and oxygen vacancy is conducive to lattice oxygen oxidation mechanism (LOM) and enhances OER kinetics. Fe2+ acts as an electron-sacrificing band to protect Fe3+ from overoxidation and promote the chemical stability. Meanwhile, the nanoporous structure can accelerate the detachment of the O2 and minimize structural oscillations to strengthen the mechanical stability. As a result, the c/a NiFe(II, III)OxHy catalyst not only exhibits superior electrocatalytic activity with an ultralow overpotential of 192 mV at 10 mA/cm2 and a Tafel slope of 41.8 mV/dec but also delivers industrial stability over 200 h at a current density of 1000 mA/cm2. This work provides a simple strategy and fundamental understanding for the development of industrial OER electrocatalysts.    

    

* Modified photoanode by in situ growth of covalent organic frameworks on BiVO4 for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393073237
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra00899e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393073237"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393073237"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393073237"))][Get cited by]]

OpenAlex: https://openalex.org/W4393073237 (Open access: True)
    
[[https://openalex.org/A5017749079][Abing Guo]], [[https://openalex.org/A5062599970][Xingchun Wu]], [[https://openalex.org/A5082662578][S. M. Ali]], [[https://openalex.org/A5047897879][Huawei Shen]], [[https://openalex.org/A5072655852][Ligong Chen]], [[https://openalex.org/A5024536637][Yang Li]], [[https://openalex.org/A5072633467][Bowei Wang]], RSC Advances. 14(14)] 2024. https://doi.org/10.1039/d4ra00899e  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ra/d4ra00899e][pdf]])
     
COF-Azo and COF-Ben are grown in situ on a modified BiVO 4 photoanode, which exhibit better catalytic performance in OER.    

    

* 2d Co-Based Conductive Metal-Organic Framework for Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393085603
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4768541")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393085603"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393085603"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393085603"))][Get cited by]]

OpenAlex: https://openalex.org/W4393085603 (Open access: False)
    
[[https://openalex.org/A5022826260][Haijiao Wang]], [[https://openalex.org/A5038547295][Zhe Chuan Feng]], [[https://openalex.org/A5061418233][Yantao Wang]], [[https://openalex.org/A5002884743][Junfeng Huang]], [[https://openalex.org/A5018390453][Cailing Xu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4768541 
     
No abstract    

    

* P‐Bridging Asymmetry Diatomic Catalysts Sites Drive Efficient Bifunctional Oxygen Electrocatalysis for Zinc‐Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393087011
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202400327")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393087011"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393087011"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393087011"))][Get cited by]]

OpenAlex: https://openalex.org/W4393087011 (Open access: False)
    
[[https://openalex.org/A5092089822][Nan Wang]], [[https://openalex.org/A5024537485][Riguo Mei]], [[https://openalex.org/A5028495424][Liqiong Chen]], [[https://openalex.org/A5020731202][Tao Yang]], [[https://openalex.org/A5063414968][Gaoran Li]], [[https://openalex.org/A5017726959][Xidong Lin]], [[https://openalex.org/A5018339079][Qingxia Liu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202400327 
     
Abstract Rechargeable zinc‐air batteries (ZABs) rely on the development of high‐performance bifunctional oxygen electrocatalysts to facilitate efficient oxygen reduction/evolution reactions (ORR/OER). Single‐atom catalysts (SACs), characterized by their precisely defined active sites, have great potential for applications in ZABs. However, the design and architecture of atomic site electrocatalysts with both high activity and durability present significant challenges, owing to their spatial confinement and electronic states. In this study, a strategy is proposed to fabricate structurally uniform dual single‐atom electrocatalyst (denoted as P‐FeCo/NC) consisting of P‐bridging Fe and Co bimetal atom (i.e., Fe‐P‐Co) decorated on N, P‐co‐doped carbon framework as an efficient and durable bifunctional electrocatalyst for ZABs. Experimental investigations and theoretical calculations reveal that the Fe‐P‐Co bridge‐coupling structure enables a facile adsorption/desorption of oxygen intermediates and low activation barrier. The resultant P‐FeCo/NC exhibits ultralow overpotential of 340 mV at 10 mA cm −2 for OER and high half‐wave potential of 0.95 V for ORR. In addition, the application of P‐FeCo/NC in rechargeable ZABs demonstrates enhanced performance with maximum power density of 115 mW cm −2 and long cyclic stability, which surpass Pt/C and RuO 2 catalysts. This study provides valuable insights into the design and mechanism of atomically dispersed catalysts for energy conversion applications.    

    

* Enhanced oxygen evolution reaction of electrodeposited Functionally-Graded Ni-Cu-Fe coating  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393087725
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Electrodeposition and Composite Coatings
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2024.118215")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393087725"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393087725"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393087725"))][Get cited by]]

OpenAlex: https://openalex.org/W4393087725 (Open access: False)
    
[[https://openalex.org/A5094222555][Mohammad Mehdi Tavallaie]], [[https://openalex.org/A5020029633][Morteza Alizadeh]], Journal of Electroanalytical Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jelechem.2024.118215 
     
No abstract    

    

* Sub‐2 nm IrRuNiMoCo High‐Entropy Alloy with Ir‐Rich Medium‐Entropy Oxide Shell to Boost Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393093375
:TOPICS: High-Entropy Alloys: Novel Designs and Properties, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-03-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202314049")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393093375"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393093375"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393093375"))][Get cited by]]

OpenAlex: https://openalex.org/W4393093375 (Open access: False)
    
[[https://openalex.org/A5039033013][Longping Yao]], [[https://openalex.org/A5056960644][Fengru Zhang]], [[https://openalex.org/A5090717104][Shuai Yang]], [[https://openalex.org/A5003759585][Hui Zhang]], [[https://openalex.org/A5041083181][Yuze Li]], [[https://openalex.org/A5069545530][Chaoyu Yang]], [[https://openalex.org/A5010951249][Hui Yang]], [[https://openalex.org/A5078573596][Qingqing Cheng]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202314049 
     
Abstract Ensuring high catalytic activity and durability at low Ir usage is still a big challenge for the development of electrocatalysts towards oxygen evolution reaction (OER) in proton exchange membrane water electrolysis (PEMWE). Here, a rapid liquid‐reduction combined with surface galvanic replacement strategy is reported to synthesize the sub 2 nm high‐entropy alloy (HEA) nanoparticles featured with Ir‐rich IrRuNiMo medium‐entropy oxide shell (Ir‐MEO) and a IrRuCoNiMo HEA core (HEA@Ir‐MEO), which exhibits a low overpotential of 243 mV at 10 mA cm −2 and high mass activity (261.5 A g Ir −1 ). Advanced spectroscopies reveal that the Ir‐rich MEO shell inhibits the severe structural evolution of transition metals upon the OER, thus guaranteeing the structural stability. In‐situ DEMS, activation energy analysis and DFT calculations unveil that the OER on HEA@Ir‐MEO follows an adsorbate evolution mechanism pathway, where the energy barrier of rate‐determining step is substantially lowered, interpreting the enhanced OER kinetics. The optimized catalyst is assembled into PEM electrolyzer with low Ir usage of ca. 0.4 mg cm −2 , and to give the excellent performance (1.85 V/3.0 A cm −2 °C), long‐term stability (>500 h@1.0 Acm −2 ) and low energy consumption (3.98 kWh Nm −3 H 2 @1.0 A cm −2 ), realizing the dramatical reduction of hydrogen production cost to USD 0.88 per kg H 2 . This article is protected by copyright. All rights reserved    

    

* Tuning the Electronic Property of Reconstructed Atomic Ni‐CuO Cluster Supported on N/O‐C for Electrocatalytic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393095206
:TOPICS: Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/advs.202310181")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393095206"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393095206"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393095206"))][Get cited by]]

OpenAlex: https://openalex.org/W4393095206 (Open access: True)
    
[[https://openalex.org/A5059672786][Xinran Li]], [[https://openalex.org/A5062242174][Yang‐Yi Liu]], [[https://openalex.org/A5066442515][Li Cheng]], [[https://openalex.org/A5013119154][Xue Han]], [[https://openalex.org/A5065505890][Songqing Chen]], [[https://openalex.org/A5064109029][Qiang Xu]], [[https://openalex.org/A5061891868][Huan Pang]], Advanced Science. None(None)] 2024. https://doi.org/10.1002/advs.202310181  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/advs.202310181][pdf]])
     
Abstract Electrochemical activation usually accompanies in situ atom rearrangement forming new catalytic sites with higher activity due to reconstructed atomic clusters or amorphous phases with abundant dangling bonds, vacancies, and defects. By harnessing the pre‐catalytic process of reconstruction, a multilevel structure of CuNi alloy nanoparticles encapsulated in N‐doped carbon (CuNi nanoalloy@N/C) transforms into a highly active compound of Ni‐doped CuO nanocluster supported on (N/O‐C) co‐doped C. Both the exposure of accessible active sites and the activity of individual active sites are greatly improved after the pre‐catalytic reconstruction. Manipulating the Cu/Ni ratios of CuNi nanoalloy@N/C can tailor the electronic property and d‐band center of the high‐active compound, which greatly optimizes the energetics of oxygen evolution reaction (OER) intermediates. This interplay among Cu, Ni, C, N, and O modifies the interface, triggers the active sites, and regulates the work functions, thereby realizing a synergistic boost in OER.    

    

* Multiscale Regulation of Ordered PtCu Intermetallic Electrocatalyst for Highly Durable Oxygen Reduction Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393097442
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-03-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.4c00583")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393097442"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393097442"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393097442"))][Get cited by]]

OpenAlex: https://openalex.org/W4393097442 (Open access: False)
    
[[https://openalex.org/A5075369470][Zhiping Deng]], [[https://openalex.org/A5025598122][Zhe Gong]], [[https://openalex.org/A5022215689][Mingxing Gong]], [[https://openalex.org/A5037323808][Xiaolei Wang]], Nano Letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.4c00583 
     
Transforming the Pt–M alloy into an ordered intermetallic is an effective strategy to improve the electrocatalytic activity and stability toward the oxygen reduction reaction (ORR). However, the synthesis of nanosized intermetallics remains challenging. Herein, we report an efficient ORR electrocatalyst, consisting of a monodisperse nanosized PtCu intermetallic on hollow mesoporous carbon spheres (HMCS). As predicted by theoretical calculations, PtCu intermetallics exhibit beneficial electronic structure, with a low theoretical overpotential of 0.33 V and enhanced Cu stability. Resulting from the multiscale modulation of catalyst structure, the O-PtCu/HMCS catalyst delivers a high mass activity of 2.73 A cm–2Pt at 0.9 V and remarkable stability. Identical location transmission electron microscopy (IL-TEM) investigations demonstrate that the rate of carbon corrosion is alleviated on HMCS, which contributes to the long-term durability. This work provides a promising design strategy for an ORR electrocatalyst, and the IL-TEM investigations offer new perspectives for the performance enhancement mechanism.    

    

* Eco-friendly high entropy oxide rock-salt type structure for oxygen evolution reaction obtained by green synthesis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393098730
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2024.118191")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393098730"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393098730"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393098730"))][Get cited by]]

OpenAlex: https://openalex.org/W4393098730 (Open access: True)
    
[[https://openalex.org/A5075400591][Jakeline R.D. Santos]], [[https://openalex.org/A5001528670][Rafael A. Raimundo]], [[https://openalex.org/A5055842564][João F.G. de A. Oliveira]], [[https://openalex.org/A5093204290][Johnnys da S. Hortencio]], [[https://openalex.org/A5090398034][Francisco J.A. Loureiro]], [[https://openalex.org/A5069774051][Daniel A. Macedo]], [[https://openalex.org/A5088882865][Marco A. Morales]], [[https://openalex.org/A5054657278][Isacco Gualandi]], [[https://openalex.org/A5070302667][Domenica Tonelli]], [[https://openalex.org/A5090218474][Uílame Umbelino Gomes]], Journal of Electroanalytical Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jelechem.2024.118191 
     
Global energy consumption increases year after year, causing the depletion of non-renewable sources. According to the International Energy Agency (IEA), global demand for electrical energy is expected to increase by 3.3 % in 2024. Therefore, developing new renewable sources is urgent, including new devices for energy storage and conversion, particularly those based on electrochemical reactions. Water splitting is a clean and sustainable technology capable of facing this issue by producing oxygen and hydrogen from water and electricity. However, an issue related to this technology is the slow kinetics of oxygen evolution reaction, making it necessary to develop new electrocatalysts with high electrochemical performance. To meet this requirement, this work deals, for the first time, with a high entropy oxide with a rock-salt structure synthesized by a green sol-gel synthesis using red seaweed (Rhodophyta) as a polymerizing agent. Sol-gel synthesis allows the large-scale production of nanomaterials with high uniformity and dispersion of the chemical elements involved. The literature, which discussed the synthesis of these oxides, reveals that agents harmful to the environment are employed, including sodium hydroxide, acetic acid, hexadecyltrimethylammonium bromide, urea, and ammonium hydroxide. The composition of the high entropy oxide is (Mg0.2Ni0.2Co0.2Cu0.2Zn0.2)O. As electrocatalyst for oxygen evolution reaction, it exhibits a low overpotential (336 mV vs. RHE at 10 mA cm-2), a Tafel slope of 68 mV dec-1, and excellent durability. The electrochemical performance of the high entropy oxide prepared in this work is superior to other electrocatalysts of the same class that were produced using transition metal-based precursors.    

    

* A comprehensive comparison of plastic derived and commercial Pt/C electrocatalysts in methanol oxidation, hydrogen evolution reaction, oxygen evolution and reduction reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393103490
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.227")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393103490"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393103490"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393103490"))][Get cited by]]

OpenAlex: https://openalex.org/W4393103490 (Open access: False)
    
[[https://openalex.org/A5080738196][Neelam Zaman]], [[https://openalex.org/A5023469241][Naseem Iqbal]], [[https://openalex.org/A5045593961][Tayyaba Nооr]], International Journal of Hydrogen Energy. 63(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.227 
     
This work utilized an innovative and economical remediation method to convert inexpensive waste feedstock into extremely useful catalysts. The procedure centered on polyethylene (PE), an easily accessible substance, and effectively transformed it at a mild temperature utilizing a new solvothermal technique, which entailed the reaction of sulfuric acid with PE chains at 120 °C. Throughout this process, the polymer experienced a pivotal cross-linking stage, resulting in its conversion into carbon materials when exposed to temperatures above 500 °C. To improve the catalytic characteristics, platinum (Pt) was effectively integrated into the resultant carbon matrix using the existing impregnation technique. Further, the catalyst's physicochemical properties were thoroughly analyzed utilizing SEM, FTIR, and XRD techniques. After that, the catalyst's performance was thoroughly evaluated in several electrocatalytic reactions, such as methanol oxidation, oxygen evolution and reduction reactions, and hydrogen evolution. The results of this investigation reveal the impressive electrocatalytic ability of the Pt/C catalyst made from waste plastic. It was found to be comparable to the best commercially available Pt/C catalysts in all the reactions that were examined. This research not only demonstrates the possibility of using waste plastic for catalyst production, but also serves as the first documented example, based on successfully converting waste plastic bags into Pt/C through the conventional Liquid Phase Reduction (LPR) process. This novel method has great potential for sustainable and ecologically responsible catalytic applications.    

    

* Influence of Ion Doping on the Oxygen Evolution Reaction Performance of Mn3o4 Oxides  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393103772
:TOPICS: Negative Temperature Coefficient Resistance (NTCR) Ceramic Thermistors, Catalytic Nanomaterials, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4769602")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393103772"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393103772"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393103772"))][Get cited by]]

OpenAlex: https://openalex.org/W4393103772 (Open access: False)
    
[[https://openalex.org/A5052397093][Peng Yu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4769602 
     
No abstract    

    

* Abundant heterointerfaces in CoS2/MoS2 nanosheet array electrocatalysts for the enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393107715
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj00357h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393107715"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393107715"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393107715"))][Get cited by]]

OpenAlex: https://openalex.org/W4393107715 (Open access: False)
    
[[https://openalex.org/A5078711522][Zhaojin Li]], [[https://openalex.org/A5086320668][Qian Ma]], [[https://openalex.org/A5084317268][Shaofei Zhang]], [[https://openalex.org/A5030611214][Di Zhang]], [[https://openalex.org/A5009988205][Huan Wang]], [[https://openalex.org/A5039934460][Qiujun Wang]], [[https://openalex.org/A5034278049][Huilan Sun]], [[https://openalex.org/A5007175755][Bo Wang]], New Journal of Chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj00357h 
     
The rich heterogeneous interface between CoS 2 and MoS 2 regulates the electronic structure and provides sufficient electrochemical active sites, thus forming a highly active region for the OER.    

    

* Constructing novel metal-free g-C3N4@HCOF-Ph heterojunctions through molecular expansion to enhance photogenerated carrier involved molecular oxygen activation and photocatalytic hydrogen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393109168
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4770114")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393109168"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393109168"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393109168"))][Get cited by]]

OpenAlex: https://openalex.org/W4393109168 (Open access: False)
    
[[https://openalex.org/A5035419178][Qingmei Tang]], [[https://openalex.org/A5039634196][Qingrong Cheng]], [[https://openalex.org/A5068445612][Zhiquan Pan]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4770114 
     
No abstract    

    

* Cr dopant regulating d-orbital electronic configuration of NiFe spinel oxide to improve oxygen evolution reaction in Zn-air battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393110836
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.174248")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393110836"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393110836"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393110836"))][Get cited by]]

OpenAlex: https://openalex.org/W4393110836 (Open access: False)
    
[[https://openalex.org/A5057127521][Shihui Liu]], [[https://openalex.org/A5033120372][Yao‐Cheng Shi]], [[https://openalex.org/A5010623844][Fengqin Tang]], [[https://openalex.org/A5063967789][Penggang Wei]], [[https://openalex.org/A5015184948][Wenrui Huang]], [[https://openalex.org/A5061934627][Jiapeng Wu]], [[https://openalex.org/A5029283807][Sujuan Zhao]], [[https://openalex.org/A5033311780][Jikui Zhu]], [[https://openalex.org/A5000209298][Chunhui Shi]], [[https://openalex.org/A5055297727][Libing Hu]], Journal of Alloys and Compounds. 987(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.174248 
     
No abstract    

    

* Transition metal-based layered double hydroxides and their derivatives for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393111188
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.150")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393111188"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393111188"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393111188"))][Get cited by]]

OpenAlex: https://openalex.org/W4393111188 (Open access: False)
    
[[https://openalex.org/A5022194241][Chun Han]], [[https://openalex.org/A5021666111][Yunhe Zhao]], [[https://openalex.org/A5011540763][Yuan Yuan]], [[https://openalex.org/A5080690473][Zehua Guo]], [[https://openalex.org/A5049778213][Gong Chen]], [[https://openalex.org/A5037410384][Jack Yang]], [[https://openalex.org/A5050289757][Qi Bao]], [[https://openalex.org/A5028365905][Li Guo]], [[https://openalex.org/A5058025282][Chunxia Chen]], International Journal of Hydrogen Energy. 63(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.150 
     
No abstract    

    

* Oxygen vacancy-rich CoMoO4/Carbon Nitride S-scheme heterojunction for boosted photocatalytic H2 production: microstructure regulation and charge transfer mechanism  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393115053
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jmst.2024.02.032")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393115053"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393115053"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393115053"))][Get cited by]]

OpenAlex: https://openalex.org/W4393115053 (Open access: False)
    
[[https://openalex.org/A5061959364][Jiani Qin]], [[https://openalex.org/A5035378312][Yanli Dong]], [[https://openalex.org/A5046079326][Xiaojuan Lai]], [[https://openalex.org/A5048609803][Bo Su]], [[https://openalex.org/A5059787779][Bao Pan]], [[https://openalex.org/A5084410248][Chuanyi Wang]], [[https://openalex.org/A5066759526][Sibo Wang]], Journal of Materials Science & Technology. None(None)] 2024. https://doi.org/10.1016/j.jmst.2024.02.032 
     
No abstract    

    

* Zn‐Leaching Induced Rapid Self‐Reconstruction of NiFe‐Layered Double Hydroxides for Boosted Oxygen Evolution Reaction (Small 12/2024)  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393120024
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202470098")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393120024"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393120024"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393120024"))][Get cited by]]

OpenAlex: https://openalex.org/W4393120024 (Open access: True)
    
[[https://openalex.org/A5086712260][Haonan Guo]], [[https://openalex.org/A5071798264][Lei Zhang]], [[https://openalex.org/A5072873062][Deliu Ou]], [[https://openalex.org/A5072085683][Qiao Liu]], [[https://openalex.org/A5051045584][Zhaohui Wu]], [[https://openalex.org/A5072403367][Weiyou Yang]], [[https://openalex.org/A5066956428][Zhi Fang]], [[https://openalex.org/A5017607299][Qing Shi]], Small. 20(12)] 2024. https://doi.org/10.1002/smll.202470098  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/smll.202470098][pdf]])
     
SmallVolume 20, Issue 12 2470098 FrontispieceFree Access Zn-Leaching Induced Rapid Self-Reconstruction of NiFe-Layered Double Hydroxides for Boosted Oxygen Evolution Reaction (Small 12/2024) Haonan Guo, Haonan Guo School of Material Science and Engineering, Taiyuan University of Science and Technology, Taiyuan, 030024 China Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorLei Zhang, Lei Zhang School of Material Science and Engineering, Taiyuan University of Science and Technology, Taiyuan, 030024 ChinaSearch for more papers by this authorDeliu Ou, Deliu Ou Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorQiao Liu, Qiao Liu Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorZhisheng Wu, Zhisheng Wu School of Material Science and Engineering, Taiyuan University of Science and Technology, Taiyuan, 030024 ChinaSearch for more papers by this authorWeiyou Yang, Weiyou Yang Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorZhi Fang, Zhi Fang Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorQing Shi, Qing Shi Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 China Zhejiang Institute of Tianjin University, Ningbo University of Technology, Ningbo, Zhejiang, 315201 ChinaSearch for more papers by this author Haonan Guo, Haonan Guo School of Material Science and Engineering, Taiyuan University of Science and Technology, Taiyuan, 030024 China Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorLei Zhang, Lei Zhang School of Material Science and Engineering, Taiyuan University of Science and Technology, Taiyuan, 030024 ChinaSearch for more papers by this authorDeliu Ou, Deliu Ou Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorQiao Liu, Qiao Liu Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorZhisheng Wu, Zhisheng Wu School of Material Science and Engineering, Taiyuan University of Science and Technology, Taiyuan, 030024 ChinaSearch for more papers by this authorWeiyou Yang, Weiyou Yang Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorZhi Fang, Zhi Fang Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 ChinaSearch for more papers by this authorQing Shi, Qing Shi Institute of Micro/Nano Materials and Devices, Ningbo University of Technology, Ningbo, 315211 China Zhejiang Institute of Tianjin University, Ningbo University of Technology, Ningbo, Zhejiang, 315201 ChinaSearch for more papers by this author First published: 22 March 2024 https://doi.org/10.1002/smll.202470098AboutPDF ToolsRequest permissionExport citationAdd to favoritesTrack citation ShareShare Give accessShare full text accessShare full-text accessPlease review our Terms and Conditions of Use and check box below to share full-text version of article.I have read and accept the Wiley Online Library Terms and Conditions of UseShareable LinkUse the link below to share a full-text version of this article with your friends and colleagues. Learn more.Copy URL Share a linkShare onEmailFacebookTwitterLinkedInRedditWechat Graphical Abstract Oxygen Evolution Reaction In article number 2307069, Zhisheng Wu, Zhi Fang, Qing Shi, and co-workers report a simple and fast strategy to promote self reconstruction of NiFe-layered double hydroxides and form highly active NiFeOOH centers. The trace Zn dopants have been introduced in advance, followed by leaching over the electrochemical activation process. The self-restructured NiFeOOH-VZn exhibits excellent catalytic activity and stability for the oxygen evolution reaction. Volume20, Issue12March 22, 20242470098 RelatedInformation    

    

* Preparation of NiFeCoMnCr Hydroxide on Nickel Foam by Corrosion Method and its Enhanced Electrochemical Performance in Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393130679
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-03-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11814-024-00160-y")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393130679"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393130679"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393130679"))][Get cited by]]

OpenAlex: https://openalex.org/W4393130679 (Open access: False)
    
[[https://openalex.org/A5024316673][Hyein Lee]], [[https://openalex.org/A5044838419][Min‐Ho Han]], [[https://openalex.org/A5064245264][Hee-Jin Noh]], [[https://openalex.org/A5008933483][Taekyung Yu]], Korean Journal of Chemical Engineering. None(None)] 2024. https://doi.org/10.1007/s11814-024-00160-y 
     
No abstract    

    

* Interface Engineering of Electrocatalysts for Efficient and Selective Oxygen Evolution in Alkaline/Seawater  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393161543
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400125")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393161543"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393161543"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393161543"))][Get cited by]]

OpenAlex: https://openalex.org/W4393161543 (Open access: True)
    
[[https://openalex.org/A5033309633][Dae-Kyu Kim]], [[https://openalex.org/A5055769349][Wenhan Zu]], [[https://openalex.org/A5082292067][Cheuk S. Kwok]], [[https://openalex.org/A5028129738][Yoon Suk Lee]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400125  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cctc.202400125][pdf]])
     
Electrochemical water splitting is regarded as an effective technology for producing green hydrogen, which is crucial for addressing energy and environmental challenges. In particular, direct seawater splitting offers significant economic and environmental advantages. However, its efficiency is hindered by the high overpotential required for the oxygen evolution reaction (OER) and the competition from chloride oxidation. This review highlights the potential of interface engineering to overcome these limitations and develop efficient OER electrocatalysts. We comprehensively explore recent advancements in interface engineering for OER in both alkaline and seawater environments. We begin by introducing the mechanisms of freshwater and seawater electrolysis, emphasizing key considerations for OER catalyst design. Subsequently, we review the recent progress made in various interface engineering strategies, analyzing their impact on OER performance in both electrolytes. Finally, we outline promising future directions for developing efficient seawater oxidation catalysts through interface engineering.    

    

* Ultrasound-Assisted Synthesis of High-Entropy Materials for Enhanced Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393142290
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/met14040384")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393142290"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393142290"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393142290"))][Get cited by]]

OpenAlex: https://openalex.org/W4393142290 (Open access: True)
    
[[https://openalex.org/A5059386082][Zhiyuan Wang]], [[https://openalex.org/A5064403506][Chengxu Zhang]], [[https://openalex.org/A5010776860][Yue Zhang]], [[https://openalex.org/A5027149538][Jue Hu]], Metals. 14(4)] 2024. https://doi.org/10.3390/met14040384  ([[https://www.mdpi.com/2075-4701/14/4/384/pdf?version=1711383336][pdf]])
     
High-entropy materials (HEMs) play a significant role in the electrocatalytic oxygen evolution reaction (OER) due to their unique properties. However, there are still challenges in the preparation of HEMs for OER catalysts. In this study, the FeCoNiMnCr catalyst is synthesized for the first time using the ultrasonic hydrothermal-sintering technique and exhibits excellent performance for OER electrocatalysis. There is an optimal ultrasonic hydrothermal time and power for achieving the best OER performance. The results demonstrate that the performance of FeCoNiMnCr catalysts prepared through ultrasonic hydrothermal sintering (US-FeCoNiMnCr) is significantly improved compared with the traditional hydrothermal-sintering method. The US-FeCoNiMnCr catalyst exhibits an overpotential of 228 mV at the current density of 10 mA cm−2 and a Tafel slope as low as 45.39 mV dec−1 in an alkaline medium. Moreover, the US-FeCoNiMnCr catalyst demonstrates remarkable stability in electrocatalytic OER with a minimal potential increase observed even after 48 h. This work not only provides valuable insights into high-entropy material synthesis, but also presents a powerful electrocatalyst for water electrolysis.    

    

* Self-Supported CoSe2 Nanorods for Efficient Oxygen Evolution and Urea Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393158032
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.3c05856")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393158032"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393158032"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393158032"))][Get cited by]]

OpenAlex: https://openalex.org/W4393158032 (Open access: False)
    
[[https://openalex.org/A5073479438][Ke Zhao]], [[https://openalex.org/A5038328764][Xiao Chen]], [[https://openalex.org/A5045527589][Haixia Liu]], [[https://openalex.org/A5025592561][Jianfeng Wang]], [[https://openalex.org/A5001063931][Jie Zhang]], ACS Applied Nano Materials. None(None)] 2024. https://doi.org/10.1021/acsanm.3c05856 
     
It is important for the practical application of water electrolysis to explore stable and earth-rich bifunctional catalysts for oxygen evolution reaction (OER) and urea oxidation reaction (UOR). An immersion-selenization strategy was proposed to prepare CoSe2/Co nanorods anchored on Co foam as bifunctional catalysts for OER and UOR. Due to the self-supported properties of CoSe2/Co and its unique nanorod structure, the OER activity is enhanced, showing an overpotential of 318 mV and a Tafel slope of 91.11 mV dec–1. In addition, the electrode showed excellent electrocatalytic UOR activity with an overpotential of 260 mV and a Tafel slope of 94.83 mV dec–1. The nanorod structure was basically retained after a 28 h durability test. This work provides a broad approach to the development of low-cost bifunctional electrocatalysts.    

    

* Cerium Doping‐Induced Enrichment of Ni 3 S 4 Phase for Boosting Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393149499
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202400056")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393149499"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393149499"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393149499"))][Get cited by]]

OpenAlex: https://openalex.org/W4393149499 (Open access: False)
    
[[https://openalex.org/A5033205455][Chunqing Gao]], [[https://openalex.org/A5052550377][Lu Pan]], [[https://openalex.org/A5032245741][Hong Wang]], [[https://openalex.org/A5061008777][Hongyu Guo]], [[https://openalex.org/A5064804120][Saad Melhi]], [[https://openalex.org/A5046264812][Mohammed A. Amin]], [[https://openalex.org/A5086802047][Jianjian Lin]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202400056 
     
The development of low‐cost transition metal compounds with high‐performance for efficient oxygen evolution reaction (OER) is of great significance in promoting the development of electrocatalysis. In this study, a Ce‐doped Ni3S4 catalyst (Ce0.2‐Ni3S4) was synthesized through a one‐step solvothermal method, where the doped rare earth element Ce induced the transformation of NiS to Ni3S4. The Ce0.2‐Ni3S4 catalyst exhibited excellent OER performance in 1 M KOH. At a current density of 10 mA cm‐2, it showed a low overpotential of 230 mV and a low Tafel slope of 52.39 mV dec‐1. Long‐term OER tests at the same potential lasted for 24 h without significant loss of current density. This work introduces a novel method of Ce element doping for modifying transition metal sulfides, providing new insights into the effective utilization of rare earth elements in the field of electrochemistry. It creates more chances for the progress of highly efficient catalysts for efficient OER, contributing to the advancement of electrocatalysis.    

    

* FeCoNiMgB high-entropy boride powder with a fluffy cotton structure and enhanced activity in the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393167181
:TOPICS: High-Entropy Alloys: Novel Designs and Properties, Synthesis and Properties of Cemented Carbides, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jmrt.2024.03.158")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393167181"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393167181"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393167181"))][Get cited by]]

OpenAlex: https://openalex.org/W4393167181 (Open access: True)
    
[[https://openalex.org/A5008386681][Fang Miao]], [[https://openalex.org/A5086015921][Peng Cui]], [[https://openalex.org/A5076776353][Zhiyuan Jing]], [[https://openalex.org/A5045957625][Wei Wu]], [[https://openalex.org/A5032499056][Zhibin Zhang]], [[https://openalex.org/A5062120914][Tingyue Gu]], [[https://openalex.org/A5014086269][Zhijie Yan]], [[https://openalex.org/A5071481252][Xiubing Liang]], Journal of Materials Research and Technology. None(None)] 2024. https://doi.org/10.1016/j.jmrt.2024.03.158 
     
Exploring efficient, low-cost electrocatalysts is critical for improving the efficiency of water splitting reactions. Noble-metal-based oxides exhibit high activities in the oxygen evolution reaction (OER). However, their high cost and the lack of natural resources hinder their practical application. Therefore, in this study, we successfully synthesized an FeCoNiMgB high-entropy boride powder via a facile chemical reduction method for use as an OER catalyst in an alkaline medium. The FeCoNiMgB powder, with an ultrathin fluffy cotton structure, exhibited an excellent OER catalytic performance, affording an overpotential of 268 mV at a current density of 10 mA/cm2 and a low Tafel slope of 42.9 mV/dec; this performance was superior to those of FeCoNiB, FeNiMgB, CoNiMgB, FeCoMgB, and commercial RuO2. The FeCoNiMgB powder also displayed remarkably stable catalytic properties for >72 h with no clear evidence of degradation. Finally, using theoretical calculations, the excellent OER performance of FeCoNiMgB was verified in terms of its adsorption and charge transfer energies and covalence. The performance and stability of FeCoNiMgB were equivalent or superior to those of several nanostructured catalysts, and thus, this study provided valuable insight into the design of efficient high-entropy boride materials.    

    

* Theoretical Design of Bifunctional Single-Atom Catalyst over g-C2N2 for Oxygen Evolution and Reduction Reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393089380
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cattod.2024.114657")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393089380"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393089380"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393089380"))][Get cited by]]

OpenAlex: https://openalex.org/W4393089380 (Open access: False)
    
[[https://openalex.org/A5039963973][Xuefei Wu]], [[https://openalex.org/A5037532055][Junan Gao]], [[https://openalex.org/A5053644345][Hong Zhao]], [[https://openalex.org/A5066562229][Zhigang Lei]], [[https://openalex.org/A5088596691][Jimmy Yun]], [[https://openalex.org/A5008720433][Jie Zhang]], [[https://openalex.org/A5066878588][Guang-Jie Xia]], Catalysis Today. None(None)] 2024. https://doi.org/10.1016/j.cattod.2024.114657 
     
No abstract    

    

* Deciphering the Underlying Mechanism of the Fourth Entity in Medium-Entropy Nicofemp Towards Boosting Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393063221
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4768125")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393063221"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393063221"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393063221"))][Get cited by]]

OpenAlex: https://openalex.org/W4393063221 (Open access: False)
    
[[https://openalex.org/A5082517492][Xue‐Zhi Song]], [[https://openalex.org/A5012788495][Xiaobing Wang]], [[https://openalex.org/A5035701638][Tao Zhang]], [[https://openalex.org/A5032668704][Yutong Meng]], [[https://openalex.org/A5079682073][Dameng Liu]], [[https://openalex.org/A5023040724][Yu‐Xin Luan]], [[https://openalex.org/A5048623079][Changguang Yao]], [[https://openalex.org/A5068462482][Zhenquan Tan]], [[https://openalex.org/A5010642871][Xiaofeng Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4768125 
     
No abstract    

    

* Catalysis of the Oxygen-Evolution Reaction in 1.0 M Sulfuric Acid by Manganese Antimonate Films Synthesized via Chemical Vapor Deposition  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393164139
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.4c00135")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393164139"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393164139"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393164139"))][Get cited by]]

OpenAlex: https://openalex.org/W4393164139 (Open access: True)
    
[[https://openalex.org/A5003944273][Jacqueline A. Dowling]], [[https://openalex.org/A5047222245][Zachary P. Ifkovits]], [[https://openalex.org/A5016781712][Azhar I. Carim]], [[https://openalex.org/A5036811504][Jake M. Evans]], [[https://openalex.org/A5094241868][Madeleine C. Swint]], [[https://openalex.org/A5073978538][Alexandre Z. Ye]], [[https://openalex.org/A5072433173][Matthias H. Richter]], [[https://openalex.org/A5026118086][A. Li]], [[https://openalex.org/A5015008318][Nathan S. Lewis]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.4c00135  ([[https://pubs.acs.org/doi/pdf/10.1021/acsaem.4c00135][pdf]])
     
Manganese antimonate (MnySb1–yOx) electrocatalysts for the oxygen-evolution reaction (OER) were synthesized via chemical vapor deposition. Mn-rich rutile Mn0.63Sb0.37Ox catalysts on fluorine-doped tin oxide (FTO) supports drove the OER for 168 h (7 days) at 10 mA cm–2 with a time-averaged overpotential of 687 ± 9 mV and with >97% Faradaic efficiency. Time-dependent anolyte composition analysis revealed the steady dissolution of Mn and Sb. Extended durability analysis confirmed that Mn-rich MnySb1–yOx materials are more active but dissolve at a faster rate than previously reported Sb-rich MnySb1–yOx alloys.    

    

* Theoretical study on oxygen evolution reaction mechanism of double rare earth europium-doped graphene under hydroxyl modification in alkaline environment  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393105438
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Biosensor Technology, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.114053")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393105438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393105438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393105438"))][Get cited by]]

OpenAlex: https://openalex.org/W4393105438 (Open access: False)
    
[[https://openalex.org/A5013203857][Tongtong Xu]], [[https://openalex.org/A5022952764][Daomiao Wang]], [[https://openalex.org/A5087429872][Qiming Fu]], [[https://openalex.org/A5012737529][Kang Wu]], [[https://openalex.org/A5044538497][Chao Liu]], Molecular Catalysis. 559(None)] 2024. https://doi.org/10.1016/j.mcat.2024.114053 
     
The development and design of high performance OER catalyst is the key to electrocatalysis technology. Herein, based on density functional theory (DFT), the oxygen evolution reaction mechanism of double rare earth europium-doped graphene under hydroxyl modification in alkaline environment has been systematically studied. Through thermodynamic and kinetic stability analysis, and the optimal reaction path and different adsorption sites of intermediates were compared. Four catalysts with good catalytic activity for OER reaction were selected. The results show that when the two hydroxyl groups are modified, the overpotentials on the optimal pathway for the four catalyst configurations are 0.54 V, 0.50 V, 0.54 V, and 0.61 V, respectively. These catalysts demonstrate excellent catalytic activity for the oxygen evolution reaction (OER). Moreover, these catalysts have good electrical conductivity, and the active site and adsorption intermediates can be stably bonded together. In addition, the scaling relationship between oxygen adsorption free energy and overpotential is described. This work may provide new insights and guidance for future research on rare-earth atom-based OER catalysts.    

    

* Iron Integration in Nickel Hydroxide Matrix vs Surface for Oxygen-Evolution Reaction: Where the Nernst Equation Does Not Work  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393144203
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.4c00604")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393144203"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393144203"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393144203"))][Get cited by]]

OpenAlex: https://openalex.org/W4393144203 (Open access: False)
    
[[https://openalex.org/A5020471931][Mohammad Saleh Ali Akbari]], [[https://openalex.org/A5047020055][Subhajit Nandy]], [[https://openalex.org/A5063597709][Keun Hwa Chae]], [[https://openalex.org/A5047640712][Mohammad Mahdi Najafpour]], The Journal of Physical Chemistry Letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.4c00604 
     
No abstract    

    

* Iron-doped cobalt phosphide nanowires prepared via one-step solvothermal phosphidization of metal–organic frameworks for the oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393170501
:TOPICS: Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4gc00132j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393170501"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393170501"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393170501"))][Get cited by]]

OpenAlex: https://openalex.org/W4393170501 (Open access: False)
    
[[https://openalex.org/A5038487257][Jianbo Tong]], [[https://openalex.org/A5044626392][Yichuang Xing]], [[https://openalex.org/A5075441298][Xuechun Xiao]], [[https://openalex.org/A5010274839][Yuan Liu]], [[https://openalex.org/A5043199080][Zhiping Hu]], [[https://openalex.org/A5015077424][Zeyi Wang]], [[https://openalex.org/A5028748116][Yafei Hu]], [[https://openalex.org/A5086324364][B. Xin]], [[https://openalex.org/A5010940638][Shuling Liu]], [[https://openalex.org/A5021471823][He Wang]], [[https://openalex.org/A5061165588][Chao Wang]], Green Chemistry. None(None)] 2024. https://doi.org/10.1039/d4gc00132j 
     
A solvothermal phosphidization method is adopted to construct CoFeP nanowires to electrochemically catalyze oxygen evolution reaction.    

    

* Fabrication of nanocrystalline high-entropy oxide CoNiFeCrMnOx thin film electrodes by dip-coating for oxygen evolution electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393170112
:TOPICS: Electrocatalysis for Energy Conversion, High-Entropy Alloys: Novel Designs and Properties, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ya00026a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393170112"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393170112"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393170112"))][Get cited by]]

OpenAlex: https://openalex.org/W4393170112 (Open access: True)
    
[[https://openalex.org/A5004982680][Qingyin Wu]], [[https://openalex.org/A5092416365][Achim Alkemper]], [[https://openalex.org/A5058407349][Stefan Lauterbach]], [[https://openalex.org/A5039183696][Jan P. Hofmann]], [[https://openalex.org/A5076962213][Marcus Einert]], Energy advances. None(None)] 2024. https://doi.org/10.1039/d4ya00026a  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ya/d4ya00026a][pdf]])
     
Nanocrystalline high-entropy CoNiFeCrMnO x thin films were prepared by dip-coating and annealing at 400 °C, showing stable oxygen evolution with overpotentials of 258 mV vs. RHE at 10 mA cm −2 over 10 hours in alkaline media.    

    
