#+TITLE: water splitting
Description: water splitting papers
Created on Sat Sep 21 01:16:33 2024

Found 54 results from 2024-09-14 to 2024-09-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Manipulating the Electronic Properties of an Fe Single Atom Catalyst via Secondary Coordination Sphere Engineering to Provide Enhanced Oxygen Electrocatalytic Activity in Zinc-Air Batteries.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402555445
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202410121")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402555445"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402555445"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402555445"))][Get cited by]]

OpenAlex: https://openalex.org/W4402555445 (Open access: False)
    
[[https://openalex.org/A5069816022][Siqi Ji]], [[https://openalex.org/A5107263290][Yimin Mou]], [[https://openalex.org/A5101670166][Hongxue Liu]], [[https://openalex.org/A5100303175][Xue Lu]], [[https://openalex.org/A5101742243][Qian Zhang]], [[https://openalex.org/A5101335497][Chunmin Guo]], [[https://openalex.org/A5058842255][Kai Sun]], [[https://openalex.org/A5100407428][Dong Liu]], [[https://openalex.org/A5033912521][J. Hugh Horton]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5100445356][Yu Wang]], [[https://openalex.org/A5100450029][Zhijun Li]], PubMed. None(None)] 2024. https://doi.org/10.1002/adma.202410121 
     
Oxygen reduction and evolution reactions are two key processes in electrochemical energy conversion technologies. Synthesis of nonprecious metal, carbon-based electrocatalysts with high oxygen bifunctional activity and stability is a crucial, yet challenging step to achieving electrochemical energy conversion. Here, an approach to address this issue: synthesis of an atomically dispersed Fe electrocatalyst (Fe    

    

* Artificial Photosynthetic Cell with Molecular Biomimetic Thylakoid  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402556634
:TOPICS: Electrocatalysis for Energy Conversion, Role of Porphyrins and Phthalocyanines in Materials Chemistry, Molecular Mechanisms of Photosynthesis and Photoprotection
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202416289")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402556634"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402556634"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402556634"))][Get cited by]]

OpenAlex: https://openalex.org/W4402556634 (Open access: False)
    
[[https://openalex.org/A5103105065][Enbo Zhou]], [[https://openalex.org/A5100659472][Shi‐Chen Yan]], [[https://openalex.org/A5065018590][Xiang Zhang]], [[https://openalex.org/A5107263595][Baloch Ur Rehman Ateeq]], [[https://openalex.org/A5102267990][Yangdan Hui]], [[https://openalex.org/A5024516004][F.S. Wang]], [[https://openalex.org/A5051342874][Lei Jiao]], [[https://openalex.org/A5066696182][Jiafang Xie]], [[https://openalex.org/A5016682254][Daqiang Yuan]], [[https://openalex.org/A5100322864][Li Wang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202416289 
     
The construction of solar‐to‐chemical conversion system by mimicking the photosynthetic network of the chloroplast holds great promise on efficient solar energy utilization. We developed an artificial photosynthetic cell (APC) based on molecular biomimetic thylakoid (CoTPP‐FePy) to split water into hydrogen and oxygen (H2 and O2) at low driving voltage (1.1 V) and neutral condition (pH≈7). The CoTPP‐FePy can emulate the light reaction in thylakoids to produce O2 by coupling light harvesting, photocatalysis, and electron/energy storage (FeIII/FeII‐Py). Subsequently, a membrane electrode assembly (MEA) were employed to simulate the dark reaction, wherein the proton, electron and energy generated by the light reaction can drive the H2 producing process. By a temporally and spatially coupling of the light and dark reactions, the resulting APC achieved a solar conversion efficiency of 3.1%, exceeding that of natural photosynthetic systems and demonstrating the potential of artificial photosynthesis.    

    

* Co3O4 nanoparticles synthesized with rotten-grape extract for use in supercapacitors and oxygen evolution devices  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402560066
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.rineng.2024.102922")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402560066"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402560066"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402560066"))][Get cited by]]

OpenAlex: https://openalex.org/W4402560066 (Open access: False)
    
[[https://openalex.org/A5009596475][Asma Hayat]], [[https://openalex.org/A5072179381][Aneela Tahira]], [[https://openalex.org/A5057422780][Muhammad Ali Bhatti]], [[https://openalex.org/A5104094070][Irum Naz]], [[https://openalex.org/A5003076482][Aqeel Ahmed Shah]], [[https://openalex.org/A5073645764][Elmuez A. Dawi]], [[https://openalex.org/A5051512789][Matteo Tonezzer]], [[https://openalex.org/A5034242852][Ayman Nafady]], [[https://openalex.org/A5058142632][Riyadh H. Alshammari]], [[https://openalex.org/A5041247040][Zafar Hussain Ibupoto]], Results in Engineering. 24(None)] 2024. https://doi.org/10.1016/j.rineng.2024.102922 
     
No abstract    

    

* Plasma-engineering of Pt-decorated NiCo2O4 nanowires with rich oxygen vacancies for enhanced oxygen electrocatalysis and zinc-air battery performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402565710
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124607")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402565710"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402565710"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402565710"))][Get cited by]]

OpenAlex: https://openalex.org/W4402565710 (Open access: False)
    
[[https://openalex.org/A5002622705][He Li]], [[https://openalex.org/A5001039797][Luka Hansen]], [[https://openalex.org/A5041745713][Ainura Aliyeva]], [[https://openalex.org/A5101834120][Jihao Wang]], [[https://openalex.org/A5055397040][Haoyi Qiu]], [[https://openalex.org/A5078351395][Martin Müller]], [[https://openalex.org/A5022896242][Shilong Chen]], [[https://openalex.org/A5010210138][Cenk Aktas]], [[https://openalex.org/A5041200678][Lorenz Kienle]], [[https://openalex.org/A5091657793][Bernd Hartke]], [[https://openalex.org/A5069362918][Jan Benedikt]], Applied Catalysis B Environment and Energy. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124607 
     
No abstract    

    

* Green Hydrogen Production by Low‐Temperature Membrane‐Engineered Water Electrolyzers, and Regenerative Fuel Cells  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402567352
:TOPICS: Hydrogen Energy Systems and Technologies, Electrocatalysis for Energy Conversion, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smtd.202400574")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402567352"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402567352"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402567352"))][Get cited by]]

OpenAlex: https://openalex.org/W4402567352 (Open access: True)
    
[[https://openalex.org/A5107266695][Alexandre Bodard]], [[https://openalex.org/A5023209242][Zhangsen Chen]], [[https://openalex.org/A5107266696][Oumayma ELJarray]], [[https://openalex.org/A5023395031][Gaixia Zhang]], Small Methods. None(None)] 2024. https://doi.org/10.1002/smtd.202400574 
     
Abstract Green hydrogen (H 2 ) is an essential component of global plans to reduce carbon emissions from hard‐to‐abate industries and heavy transport. However, challenges remain in the highly efficient H 2 production from water electrolysis powered by renewable energies. The sluggish oxygen evolution restrains the H 2 production from water splitting. Rational electrocatalyst designs for highly efficient H 2 production and oxygen evolution are pivotal for water electrolysis. With the development of high‐performance electrolyzers, the scale‐up of H 2 production to an industrial‐level related activity can be achieved. This review summarizes recent advances in water electrolysis such as the proton exchange membrane water electrolyzer (PEMWE) and anion exchange membrane water electrolyzer (AEMWE). The critical challenges for PEMWE and AEMWE are the high cost of noble‐metal catalysts and their durability, respectively. This review highlights the anode and cathode designs for improving the catalytic performance of electrocatalysts, the electrolyte and membrane engineering for membrane electrode assembly (MEA) optimizations, and stack systems for the most promising electrolyzers in water electrolysis. Besides, the advantages of integrating water electrolyzers, fuel cells (FC), and regenerative fuel cells (RFC) into the hydrogen ecosystem are introduced. Finally, the perspective of electrolyzer designs with superior performance is presented.    

    

* Fluorine‐lodged high‐valent high‐entropy layered double hydroxide for efficient, long‐lasting zinc‐air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402568141
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202410978")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402568141"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402568141"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402568141"))][Get cited by]]

OpenAlex: https://openalex.org/W4402568141 (Open access: False)
    
[[https://openalex.org/A5085664488][Zonglong Zhu]], [[https://openalex.org/A5085082108][Jing Zhong]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5045848015][Jialun Gu]], [[https://openalex.org/A5087109862][Fucong Lyu]], [[https://openalex.org/A5103105803][Shengmei Chen]], [[https://openalex.org/A5079505820][Haikun Wu]], [[https://openalex.org/A5060676955][Lanxi Li]], [[https://openalex.org/A5102942706][Chunyi Zhi]], [[https://openalex.org/A5100341536][Jian Lü]], [[https://openalex.org/A5032400855][Yang Yang Li]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202410978 
     
Efficient and stable bifunctional oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) catalysts are urgently needed to unlock the full potential of zinc‐air batteries (ZABs). High‐valence oxides (HVOs) and high entropy oxides (HEOs) are suitable candidates for their optimal electronic structures and stability but suffer from demanding synthesis. Here, a low‐cost fluorine‐lodged high‐valent high‐entropy layered double hydroxide (HV‐HE‐LDH) (FeCoNi2F4(OH)4) is conveniently prepared through multi‐ions co‐precipitation, where F‐ are firmly embedded into the individual hydroxide layers. Spectroscopic detections and theoretical simulations reveal high valent metal cations are obtained in FeCoNi2F4(OH)4, which enlarge the energy band overlap between metal 3d and O 2p, enhancing the electronic conductivity and charge transfer, thus affording high intrinsic OER catalytic activity. More importantly, the strengthened metal‐oxygen (M‐O) bonds and stable octahedral geometry (M‐O(F)6) in FeCoNi2F4(OH)4 prevent structural reorganization, rendering long‐term catalytic stability. Furthermore, an efficient three‐phase reaction interface with fast oxygen transportation was constructed, significantly improving the ORR activity. ZABs assembled with FeCoNi2F4(OH)4@HCC (hydrophobic carbon cloth) cathodes deliver a top performance with high round‐trip energy efficiency (60.6% at 10 mA cm‐2) and long‐term stability (efficiency remains at 58.8% after 1050 charge‐discharge cycles).    

    

* Trifunctional Graphene‐Sandwiched Heterojunction‐Embedded Layered Lattice Electrocatalyst for High Performance in Zn‐Air Battery‐Driven Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402568155
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/advs.202408869")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402568155"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402568155"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402568155"))][Get cited by]]

OpenAlex: https://openalex.org/W4402568155 (Open access: True)
    
[[https://openalex.org/A5100691394][Dong‐Won Kim]], [[https://openalex.org/A5106821467][Jihoon Kim]], [[https://openalex.org/A5049261439][Jong Hui Choi]], [[https://openalex.org/A5002504130][Do Hwan Jung]], [[https://openalex.org/A5042923657][Jeung Ku Kang]], Advanced Science. None(None)] 2024. https://doi.org/10.1002/advs.202408869 
     
Abstract Zn‐air battery (ZAB)‐driven water splitting holds great promise as a next‐generation energy conversion technology, but its large overpotential, low activity, and poor stability for oxygen reduction reaction (ORR), oxygen evolution reaction (OER), and hydrogen evolution reaction (HER) remain obstacles. Here, a trifunctional graphene‐sandwiched, heterojunction‐embedded layered lattice (G‐SHELL) electrocatalyst offering a solution to these challenges are reported. Its hollow core‐layered shell morphology promotes ion transport to Co 3 S 4 for OER and graphene‐sandwiched MoS 2 for ORR/HER, while its heterojunction‐induced internal electric fields facilitate electron migration. The structural characteristics of G‐SHELL are thoroughly investigated using X‐ray absorption spectroscopy. Additionally, atomic‐resolution transmission electron microscopy (TEM) images align well with the DFT‐relaxed structures and simulated TEM images, further confirming its structure. It exhibits an approximately threefold smaller ORR charge transfer resistance than Pt/C, a lower OER overpotential and Tafel slope than RuO₂, and excellent HER overpotential and Tafel slope, while outlasting noble metals in terms of durability. Ex situ X‐ray photoelectron spectroscopy analysis under varying potentials by examining the peak shifts and ratios (Co 2+ /Co 3+ and Mo 4+ /Mo 6+ ) elucidates electrocatalytic reaction mechanisms. Furthermore, the ZAB with G‐SHELL outperforms Pt/C+RuO 2 in terms of energy density (797 Wh kg −1 ) and peak power density (275.8 mW cm −2 ), realizing the ZAB‐driven water splitting.    

    

* Integrating Multiple Strategies Using Biotechnology to Design High‐Performance Electrocatalysts for Hydrogen and Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402568366
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202413072")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402568366"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402568366"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402568366"))][Get cited by]]

OpenAlex: https://openalex.org/W4402568366 (Open access: False)
    
[[https://openalex.org/A5100539584][Lin Ge]], [[https://openalex.org/A5051852456][Chang Liu]], [[https://openalex.org/A5065081112][Tingting Xue]], [[https://openalex.org/A5051684600][Yiyang Kang]], [[https://openalex.org/A5101515037][Yining Sun]], [[https://openalex.org/A5100764261][Yuxi Chen]], [[https://openalex.org/A5100657940][Jiajie Wu]], [[https://openalex.org/A5064869186][Kai Wen Teng]], [[https://openalex.org/A5100440390][Lei Li]], [[https://openalex.org/A5050763027][Qing Qu]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202413072 
     
Abstract Combining multiple design strategies often enhances catalyst performance but usually comes with high costs and low reproducibility. A technique that enhances catalyst performance in multiple strategies is urgently needed. Herein, a novel bioregulation technique is introduced, allowing simultaneous control over morphology, particle size, doping, interface engineering, and electronic properties. Bioregulation technique utilizes the soluble extracellular polymer from Aspergillus niger as a templating agent to construct high‐performance catalysts for hydrogen and oxygen evolution reaction (HER and OER). This technique controls catalyst morphology, introduces biological N and S doping, and regulates the electronic structure of the catalyst surface. Biomolecule modification enhances surface hydrophilicity, and the nanostructure increases surface roughness and gas‐release efficiency. Theoretical calculations show that the bioregulation technique shortens the d/p‐band center, optimizing reaction intermediate adsorption and desorption. The Bio‐Pt/Co 3 O 4 catalyst with trace Pt on the surface, designed with these strategies, achieves HER ( η 10 of 42 mV), OER ( η 10 of 221 mV), and overall water‐splitting performance (1.51 V at 10 mA cm −2 ), maintaining stability for over 50 h, outperforming most Pt‐based catalysts. Notably, using spent lithium‐ion battery cathodes leachate, rich in Co 2 ⁺, successfully replicates the experiment. This approach holds promise as a mainstream method for synthesizing high‐performance materials in the future.    

    

* Modulation of catalytic activity of BSCF towards electrochemical oxygen reactions using different synthetic approaches  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402568572
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.09.138")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402568572"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402568572"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402568572"))][Get cited by]]

OpenAlex: https://openalex.org/W4402568572 (Open access: False)
    
[[https://openalex.org/A5045576247][Sachin Bhagat]], [[https://openalex.org/A5085652067][Nandita Singh]], [[https://openalex.org/A5101707351][Monika Singh]], [[https://openalex.org/A5035021700][Ashish Kumar Singh]], [[https://openalex.org/A5075153838][Suryabhan Singh]], [[https://openalex.org/A5049948393][Uday Pratap Azad]], [[https://openalex.org/A5044615009][Akhilesh Kumar Singh]], International Journal of Hydrogen Energy. 88(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.09.138 
     
No abstract    

    

* Fe-modulated NiFex Co Layered Double Hydroxide on Ni Foam for Efficient Oxygen Precipitation Reaction in Alkaline Water Electrolysis for Hydrogen Production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402570146
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Carbon Dioxide Hydrogenation, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-07-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.23919/ccc63176.2024.10661943")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402570146"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402570146"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402570146"))][Get cited by]]

OpenAlex: https://openalex.org/W4402570146 (Open access: False)
    
[[https://openalex.org/A5104049478][Jialin Dong]], [[https://openalex.org/A5018962276][Shihong Yue]], No host. None(None)] 2024. https://doi.org/10.23919/ccc63176.2024.10661943 
     
No abstract    

    

* Preparation of hollow CoFe Prussian blue analogues and their derived CoP-FeP nanoboxes as efficient electrocatalysts as oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402503792
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235454")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402503792"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402503792"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402503792"))][Get cited by]]

OpenAlex: https://openalex.org/W4402503792 (Open access: False)
    
[[https://openalex.org/A5100362565][Shiqi Zhang]], [[https://openalex.org/A5024794473][Ying Cheng]], [[https://openalex.org/A5075456959][Zhiyuan Ni]], [[https://openalex.org/A5060430863][Xuefei Lei]], [[https://openalex.org/A5100439502][Biao Wang]], [[https://openalex.org/A5081185893][Xuanwen Liu]], [[https://openalex.org/A5017651445][Rui Guo]], Journal of Power Sources. 623(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235454 
     
No abstract    

    

* NiFe2O4 in MoSe2 Exhibits Bifunctional Water Oxidation and Oxygen Reduction (OER and ORR) Catalytic Reactions for Energy Applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402506190
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.4c01586")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402506190"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402506190"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402506190"))][Get cited by]]

OpenAlex: https://openalex.org/W4402506190 (Open access: False)
    
[[https://openalex.org/A5059659171][Merin Mary Sebastian]], [[https://openalex.org/A5003489789][Ditty Dixon]], [[https://openalex.org/A5089963600][T. Daniel Thangadurai]], [[https://openalex.org/A5064125049][Nandakumar Kalarikkal]], [[https://openalex.org/A5037699843][Alex Schechter]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.4c01586 
     
No abstract    

    

* Breaking the Bottleneck of Activity and Stability of RuO2-Based Electrocatalysts for Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402507206
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.4c03643")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402507206"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402507206"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402507206"))][Get cited by]]

OpenAlex: https://openalex.org/W4402507206 (Open access: False)
    
[[https://openalex.org/A5047902639][Weimo Li]], [[https://openalex.org/A5100600897][Ce Wang]], [[https://openalex.org/A5075456232][Xiaofeng Lu]], Nano Letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.4c03643 
     
Electrochemical acidic oxygen evolution reaction (OER) is an important part for water electrolysis utilizing a proton exchange membrane (PEM) apparatus for industrial H    

    

* Insights of oxygen vacancies engineered structural, morphological, and electrochemical attributes of Cr-doped Co3O4 nanoparticles as redox active battery-type electrodes for hybrid supercapacitors  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402508520
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2024.113751")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402508520"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402508520"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402508520"))][Get cited by]]

OpenAlex: https://openalex.org/W4402508520 (Open access: False)
    
[[https://openalex.org/A5031913257][K. Mallikarjuna]], [[https://openalex.org/A5009249208][B. Deva Prasad Raju]], [[https://openalex.org/A5049990132][Mohamed A. Ghanem]], [[https://openalex.org/A5073224842][G.R. Dillip]], [[https://openalex.org/A5067306788][Sang Woo Joo]], Journal of Energy Storage. 100(None)] 2024. https://doi.org/10.1016/j.est.2024.113751 
     
No abstract    

    

* Comprehensive Study on the Electrochemical Evolution, Reaction Kinetics, and Mass Transport at the Anion Exchange Ionomer–Pt Interface for Oxygen Reduction Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402510645
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c10293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402510645"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402510645"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402510645"))][Get cited by]]

OpenAlex: https://openalex.org/W4402510645 (Open access: False)
    
[[https://openalex.org/A5100353177][Chang Liu]], [[https://openalex.org/A5003585143][Ruimin Ding]], [[https://openalex.org/A5013588765][Xi Yin]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c10293 
     
Understanding the structure evolution, kinetics, and mass transfer for the oxygen reduction reaction (ORR) at the ionomer-catalyst interface is fundamental for the development of anion exchange membrane fuel cells (AEMFCs). Herein, we investigate the structural evolution of ionomer-Pt interfaces during the activation process of polycrystalline Pt (poly-Pt) electrodes and their ORR kinetics and mass transfer characteristics at steady state. The results suggest the ionomer thickness as a critical factor in determining the Pt surface structure and the flux of the O    

    

* Porous Silicon‐Supported Catalytic Materials for Energy Conversion and Storage  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402512252
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401459")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402512252"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402512252"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402512252"))][Get cited by]]

OpenAlex: https://openalex.org/W4402512252 (Open access: False)
    
[[https://openalex.org/A5028123645][Man Wong]], [[https://openalex.org/A5042493730][Wen Ou]], [[https://openalex.org/A5088926552][Zhen‐Tao Yu]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401459 
     
Porous silicon (Si) has a tetrahedral structure similar to that of sp3‐ hybridized carbon atoms in a typical diamond structure, which affords it unique chemical and physical properties including an adjustable intrinsic bandgap, a high‐speed carrier transfer efficiency. It has shown great potential in photocatalysis, rechargeable batteries, solar cells, detectors, and electrocatalysis. This review introduces various porous Si‐supported electrocatalysts and analyzes the reasons why porous Si is used as a new carrier/active sites from the perspectives of its molecular structure, electronic properties, synthesis methods, etc. The electrochemical applications of porous Si‐based electrocatalysts in energy conversion reactions such as hydrogen evolution reaction, oxygen evolution reaction, oxygen reduction reaction, and total water decomposition together with lithium‐ion batteries (LIBs) and supercapacitors in energy storage are summarized. The challenges and future research directions for porous Si are also discussed. This review aims to deepen the understanding of porous Si and promote the development and applications of this new type of Si material.    

    

* Highly Valent Cobalt-manganese Spinel Nanowires Induced by Fluorine-Doping for Durable Acid Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402512599
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.176500")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402512599"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402512599"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402512599"))][Get cited by]]

OpenAlex: https://openalex.org/W4402512599 (Open access: False)
    
[[https://openalex.org/A5003084986][Xufeng Hong]], [[https://openalex.org/A5101587702][Yong Gao]], [[https://openalex.org/A5024680462][Mengyao Ji]], [[https://openalex.org/A5061176165][Jinhan Li]], [[https://openalex.org/A5061529098][Yingshui Yao]], [[https://openalex.org/A5012597202][Zhicheng Yu]], [[https://openalex.org/A5037960542][Kun Chang]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.176500 
     
No abstract    

    

* Restricting the over-oxidation of active sites in high-entropy electrocatalysts towards ultra-stabilized oxygen evolution in alkaline water electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402519737
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05449k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402519737"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402519737"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402519737"))][Get cited by]]

OpenAlex: https://openalex.org/W4402519737 (Open access: False)
    
[[https://openalex.org/A5077648060][Yimin Zhang]], [[https://openalex.org/A5101525739][Jianli Kang]], [[https://openalex.org/A5055438935][Haonan Xie]], [[https://openalex.org/A5101604783][Hongxia Yin]], [[https://openalex.org/A5079408077][Zhijia Zhang]], [[https://openalex.org/A5004914639][Yuhan Ma]], [[https://openalex.org/A5101600096][Guangxin Sun]], [[https://openalex.org/A5044321397][Enzuo Liu]], [[https://openalex.org/A5060352654][Liying Ma]], [[https://openalex.org/A5100458396][Biao Chen]], [[https://openalex.org/A5046671426][Junwei Sha]], [[https://openalex.org/A5102957132][Lihua Qian]], [[https://openalex.org/A5030979204][Wenbin Hu]], [[https://openalex.org/A5000026480][Chunnian He]], [[https://openalex.org/A5090219547][Naiqin Zhao]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta05449k 
     
Based on ionic electronegativity, theoretical calculation guided the synthesis of np-MnFeCoNiCuOOH exhibiting ultra-stabilized oxygen evolution in alkaline water electrolysis.    

    

* Dependence of Oxygen Evolution Reaction Catalysis at Thin Cathodically-Deposited Nickel-Iron-Selenide on Fe in the Alkaline Electrolyte vs. Codeposited Fe  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402520122
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.145062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402520122"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402520122"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402520122"))][Get cited by]]

OpenAlex: https://openalex.org/W4402520122 (Open access: False)
    
[[https://openalex.org/A5045851824][Jihan Dhainy]], [[https://openalex.org/A5049127648][M. El Jamal]], [[https://openalex.org/A5107184729][Issaaf Mouawad]], [[https://openalex.org/A5079295334][Lara I. Halaoui]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.145062 
     
No abstract    

    

* Designing neighboring-site activation of single atom via tunnel ions for boosting acidic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402520438
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-52410-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402520438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402520438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402520438"))][Get cited by]]

OpenAlex: https://openalex.org/W4402520438 (Open access: True)
    
[[https://openalex.org/A5102937378][Yixin Hao]], [[https://openalex.org/A5060265950][Sung‐Fu Hung]], [[https://openalex.org/A5101733772][Luqi Wang]], [[https://openalex.org/A5029117570][Liming Deng]], [[https://openalex.org/A5019148170][Wen‐Jing Zeng]], [[https://openalex.org/A5100408858][Chenchen Zhang]], [[https://openalex.org/A5029202084][Zih‐Yi Lin]], [[https://openalex.org/A5010783003][Chun‐Han Kuo]], [[https://openalex.org/A5100423448][Ye Wang]], [[https://openalex.org/A5101723568][Ying Zhang]], [[https://openalex.org/A5084555578][Han‐Yi Chen]], [[https://openalex.org/A5075628250][Feng Hu]], [[https://openalex.org/A5100318907][Linlin Li]], [[https://openalex.org/A5034879972][Shengjie Peng]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-52410-6 
     
Realizing an efficient turnover frequency in the acidic oxygen evolution reaction by modifying the reaction configuration is crucial in designing high-performance single-atom catalysts. Here, we report a "single atom-double site" concept, which involves an activatable inert manganese atom redox chemistry in a single-atom Ru-Mn dual-site platform with tunnel Ni ions as the trigger. In contrast to conventional single-atom catalysts, the proposed configuration allows direct intramolecular oxygen coupling driven by the Ni ions intercalation effect, bypassing the secondary deprotonation step instead of the kinetically sluggish adsorbate evolution mechanism. The strong bonding of Ni ions activates the inert manganese terminal groups and inhibits the cross-site disproportionation process inherent in the Mn scaffolding, which is crucial to ensure the dual-site platform. As a result, the single-atom Ru-Ni-Mn octahedral molecular sieves catalyst delivers a low overpotential, adequate mass activity and good stability.    

    

* Formation of Core‐Shell Ir@TiO2 Nanoparticles through Hydrogen Treatment as Acidic Oxygen Evolution Reaction Catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402520720
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202408848")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402520720"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402520720"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402520720"))][Get cited by]]

OpenAlex: https://openalex.org/W4402520720 (Open access: True)
    
[[https://openalex.org/A5013626829][Jihyeon Park]], [[https://openalex.org/A5039887129][E Liu]], [[https://openalex.org/A5002888212][Shayan Angizi]], [[https://openalex.org/A5072697794][Ahmed M. Abdellah]], [[https://openalex.org/A5034198209][Ecem Yelekli Kirici]], [[https://openalex.org/A5044827415][Drew Higgins]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202408848 
     
Abstract The transition to a sustainable energy economy requires the availability of renewably produced hydrogen through proton exchange membrane water electrolysis. The techno‐economic viability of this technology requires addressing materials challenges regarding the lack of active and stable catalysts for the electrochemical oxygen evolution reaction (OER) in acidic conditions. Herein, core‐shell iridium/titanium dioxide (Core‐shell Ir@TiO 2 ) catalysts for acidic OER are synthesized through a polyol method to create TiO 2 nanoparticles, followed by urea reduction with Ir, and subsequent annealing in hydrogen. The formation process of the core‐shell structure is observed through in situ environmental transmission electron microscopy under annealing conditions. Ir segregation occurred from an initially blended mixed metal oxide structure to a core‐shell configuration at 500 °C. Core‐shell Ir@TiO 2 showed a three‐fold higher stability number (i.e., S‐number) than commercial IrO x (3.34 × 10 6 versus 1.02 × 10 6 ). Furthermore, an Ir‐mass normalized activity of 1,880 A g Ir −1 at 1.7 V versus RHE is measured for Core‐shell Ir@TiO 2 , compared to 624 A g Ir −1 for commercial IrO x . The developed synthetic route to prepare a composite structure with a TiO 2 core and Ir‐based shell has enabled an Ir content reduction without a compromise in activity and stability, thus offering a promising avenue for developing next‐generation catalysts tailored for acidic water electrolysis.    

    

* Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402532298
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402532298"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402532298"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402532298"))][Get cited by]]

OpenAlex: https://openalex.org/W4402532298 (Open access: False)
    
[[https://openalex.org/A5016040017][Feifan Wang]], [[https://openalex.org/A5101814743][Yukui Zhang]], [[https://openalex.org/A5100378741][Jing Wang]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta05700g 
     
Spin state modulation has been demonstrated an effective strategy to tune the catalytic performance of metal organic frameworks for electrochemical oxygen reduction reaction (OER). However, the undisclosed correlation between spin-state...    

    

* Review for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538460
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Molecular Magnetism and Spintronics, Electron Spin Resonance in Biomolecular Studies
:PUBLICATION_DATE: 2024-09-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538460"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538460"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538460"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538460 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v1/review2 
     
No abstract    

    

* Decision letter for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538465
:TOPICS: Electron Spin Resonance in Biomolecular Studies, Molecular Magnetism and Spintronics, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-09-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538465"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538465"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538465"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538465 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v1/decision1 
     
No abstract    

    

* Author response for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538479
:TOPICS: Accelerating Materials Innovation through Informatics, Electron Spin Resonance in Biomolecular Studies, Molecular Magnetism and Spintronics
:PUBLICATION_DATE: 2024-09-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v2/response1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538479"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538479"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538479"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538479 (Open access: False)
    
[[https://openalex.org/A5016040017][Feifan Wang]], [[https://openalex.org/A5101814743][Yukui Zhang]], [[https://openalex.org/A5100378741][Jing Wang]], No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v2/response1 
     
No abstract    

    

* Review for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538494
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Molecular Magnetism and Spintronics, Electron Spin Resonance in Biomolecular Studies
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538494"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538494"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538494"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538494 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v1/review1 
     
No abstract    

    

* Decision letter for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538504
:TOPICS: Electron Spin Resonance in Biomolecular Studies, Molecular Magnetism and Spintronics, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538504"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538504 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v2/decision1 
     
No abstract    

    

* Review for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538882
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Molecular Magnetism and Spintronics, Electron Spin Resonance in Biomolecular Studies
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538882"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538882"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538882"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538882 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v2/review1 
     
No abstract    

    

* A Rechargeable Urea‐Assisted Zn‐Air Battery with High Energy Efficiency and Fast‐Charging Enabled by Engineering High‐Energy Interfacial Structures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402542550
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-09-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202410845")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402542550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402542550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402542550"))][Get cited by]]

OpenAlex: https://openalex.org/W4402542550 (Open access: False)
    
[[https://openalex.org/A5000272762][Mingjie Wu]], [[https://openalex.org/A5003409409][Yinghui Xu]], [[https://openalex.org/A5071388400][Jian Luo]], [[https://openalex.org/A5103154463][Siyi Yang]], [[https://openalex.org/A5023395031][Gaixia Zhang]], [[https://openalex.org/A5017404634][Lei Du]], [[https://openalex.org/A5068328164][Huixia Luo]], [[https://openalex.org/A5037920786][Xun Cui]], [[https://openalex.org/A5046799991][Yingkui Yang]], [[https://openalex.org/A5080743510][Shuhui Sun]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202410845 
     
Electrochemical urea oxidation reaction (UOR) offers a promising alternative to the oxygen evolution reaction (OER) in clean energy conversion and storage systems. Nickel‐based catalysts are highly regarded as promising electrocatalysts for the UOR. However, their effectiveness is significantly hindered by the unavoidable self‐oxidation reaction of nickel species during UOR. To address this challenge, we proposed an interface chemistry modulation strategy to boost UOR kinetics by creating a high‐energy interfacial heterostructure. This heterostructure features the incorporation of Ag at the CoOOH@NiOOH heterojunction interface. Strong interactions significantly promote the electron exchanges in the heterointerface between the ‐OH and ‐O. Consequently, the improved electron delocalization led to the formation of stronger bonds between Co sites and urea CO(NH2)2, promoting a preference for urea to occupy Co active sites over OH*. The resulting catalyst, Ag‐CoOOH@NiOOH, affords an ultrahigh UOR activity with a low potential of 1.33 V at 100 mA cm‐2. The fabricated catalyst exhibits a mass activity exceeding that of initial cobalt oxyhydroxide by over 11.9 times. The rechargeable urea‐assisted zinc‐air batteries (ZABs) achieves a record‐breaking energy efficiency of 74.56% at 1 mA cm‐2, remarkable durability (1000 hours at even a current density of 50 mA cm‐2), and quick charge performances.    

    

* Facile Synthesis of Carbon-Coated Nips3 Nanoparticle Electrocatalyst for Highly Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402545967
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4956197")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402545967"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402545967"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402545967"))][Get cited by]]

OpenAlex: https://openalex.org/W4402545967 (Open access: False)
    
[[https://openalex.org/A5100626026][Dongjun Lee]], [[https://openalex.org/A5005654711][Doyeon Lee]], [[https://openalex.org/A5100662247][Wook Kim]], [[https://openalex.org/A5065081264][Seong‐Hyeon Hong]], [[https://openalex.org/A5057076775][Hee Jo Song]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4956197 
     
No abstract    

    

* Origin of Enhanced Oxygen Evolution in Restructured Metal‐Organic Frameworks for Anion Exchange Membrane Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402546461
:TOPICS: Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions, Science and Technology of Capacitive Deionization for Water Desalination
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202413916")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402546461"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402546461"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402546461"))][Get cited by]]

OpenAlex: https://openalex.org/W4402546461 (Open access: False)
    
[[https://openalex.org/A5100414299][Ying Li]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5008686232][Xiaolei Hao]], [[https://openalex.org/A5101064771][Xiaopei Xu]], [[https://openalex.org/A5016082953][Lingling Xu]], [[https://openalex.org/A5085459146][Bo Wei]], [[https://openalex.org/A5100784976][Zhongwei Chen]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202413916 
     
Metal‐Organic Frameworks (MOFs), praised for structural flexibility and tunability, are prominent catalyst prototypes for exploring oxygen evolution reaction (OER). Yet, their intricate transformations under OER, especially in industrial high‐current environments, pose significant challenges in accurately elucidating their structure‐activity correlation. Here, we harnessed an electrooxidation process for controllable MOF reconstruction, discovering that Fe doping expedites Ni(Fe)‐MOF structural evolution, accompanied by the elongation of Ni‐O bonds, monitored by in‐situ Raman and UV‐visible spectroscopy. Theoretical modeling further reveals that Fe doping and defect‐induced tensile strain in the NiO6 octahedra augments the metal ds‐Op hybridization, optimizing their adsorption behavior and augmenting OER activity. The reconstructed Ni(Fe)‐MOF, serving as the anode in anion exchange membrane water electrolysis, achieves a noteworthy current density of 3.3 A cm‐2 at 2.2 V while maintaining equally stable operation for 160 h spanning from 0.5 A cm‐2 to 1 A cm‐2. This undertaking elevates our comprehension of OER catalyst reconstruction, furnishing promising avenues for designing highly efficacious catalysts across electrochemical platforms.    

    

* Origin of Enhanced Oxygen Evolution in Restructured Metal‐Organic Frameworks for Anion Exchange Membrane Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402546561
:TOPICS: Electrocatalysis for Energy Conversion, Chemistry and Applications of Metal-Organic Frameworks, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202413916")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402546561"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402546561"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402546561"))][Get cited by]]

OpenAlex: https://openalex.org/W4402546561 (Open access: False)
    
[[https://openalex.org/A5100414294][Ying Li]], [[https://openalex.org/A5047614812][Yang Liu]], [[https://openalex.org/A5008686232][Xiaolei Hao]], [[https://openalex.org/A5101064771][Xiaopei Xu]], [[https://openalex.org/A5016082953][Lingling Xu]], [[https://openalex.org/A5085459146][Bo Wei]], [[https://openalex.org/A5100784976][Zhongwei Chen]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202413916 
     
Metal‐Organic Frameworks (MOFs), praised for structural flexibility and tunability, are prominent catalyst prototypes for exploring oxygen evolution reaction (OER). Yet, their intricate transformations under OER, especially in industrial high‐current environments, pose significant challenges in accurately elucidating their structure‐activity correlation. Here, we harnessed an electrooxidation process for controllable MOF reconstruction, discovering that Fe doping expedites Ni(Fe)‐MOF structural evolution, accompanied by the elongation of Ni‐O bonds, monitored by in‐situ Raman and UV‐visible spectroscopy. Theoretical modeling further reveals that Fe doping and defect‐induced tensile strain in the NiO6 octahedra augments the metal ds‐Op hybridization, optimizing their adsorption behavior and augmenting OER activity. The reconstructed Ni(Fe)‐MOF, serving as the anode in anion exchange membrane water electrolysis, achieves a noteworthy current density of 3.3 A cm‐2 at 2.2 V while maintaining equally stable operation for 160 h spanning from 0.5 A cm‐2 to 1 A cm‐2. This undertaking elevates our comprehension of OER catalyst reconstruction, furnishing promising avenues for designing highly efficacious catalysts across electrochemical platforms.    

    

* Electrospun Mn1-xCoxFe2O4 (x=0-0.7) Nanofibers for Supercapacitors and Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402549944
:TOPICS: Materials for Electrochemical Supercapacitors, Lithium-ion Battery Technology, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matchemphys.2024.129948")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402549944"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402549944"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402549944"))][Get cited by]]

OpenAlex: https://openalex.org/W4402549944 (Open access: False)
    
[[https://openalex.org/A5093713392][Zahra Ansari Jokandan]], [[https://openalex.org/A5085759711][J. Mazloom]], [[https://openalex.org/A5014599906][Morteza Safari]], Materials Chemistry and Physics. None(None)] 2024. https://doi.org/10.1016/j.matchemphys.2024.129948 
     
No abstract    

    

* Fe, Cu bimetallic precursor-driven quaternary active sites boost oxygen reduction / evolution reaction bifunctional catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402550124
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235423")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402550124"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402550124"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402550124"))][Get cited by]]

OpenAlex: https://openalex.org/W4402550124 (Open access: False)
    
[[https://openalex.org/A5101383673][Yurong Yuan]], [[https://openalex.org/A5026379076][Mengwei Pan]], [[https://openalex.org/A5101509462][Mengjie Zhang]], [[https://openalex.org/A5075343261][Yuchen Zhou]], [[https://openalex.org/A5042495813][Qin Fei-long]], [[https://openalex.org/A5074161773][Yaoyu Yang]], [[https://openalex.org/A5002739525][Rui Hao]], [[https://openalex.org/A5102784975][Weifang Liu]], [[https://openalex.org/A5034594327][Kaiyu Liu]], Journal of Power Sources. 623(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235423 
     
No abstract    

    

* Recommended practice for measurement and evaluation of oxygen evolution reaction electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402567939
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/eom2.12486")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402567939"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402567939"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402567939"))][Get cited by]]

OpenAlex: https://openalex.org/W4402567939 (Open access: True)
    
[[https://openalex.org/A5072641790][Hongyu An]], [[https://openalex.org/A5021708784][Wanki Park]], [[https://openalex.org/A5077614940][Heejong Shin]], [[https://openalex.org/A5055851063][Dong Young Chung]], EcoMat. None(None)] 2024. https://doi.org/10.1002/eom2.12486 
     
Abstract The Oxygen evolution reaction (OER) is a pivotal technology driving next‐generation sustainable energy conversion and storage devices. Establishing a robust analytical methodology is paramount to fostering innovation in this field. This review offers a comprehensive discussion on measurement and interpretation, advocating for standardized protocols and best practices to mitigate the myriad factors that complicate analysis. The initial focus is directed toward substrate electrodes and gas bubbles, both significant contributors to reduced reliability and reproducibility. Subsequently, the review focuses on intrinsic activity assessment, identification of electrochemical active sites, and the disentanglement of competing process contributions. These careful methodologies ensure the systematic delivery of insights crucial for assessing OER performance. In conclusion, the review highlights the critical role played by precise measurement techniques and unbiased activity comparison methodologies in propelling advancements in OER catalyst development. image    

    

* Ligand-tuning of coordination compound for improved oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402565094
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cjche.2024.07.023")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402565094"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402565094"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402565094"))][Get cited by]]

OpenAlex: https://openalex.org/W4402565094 (Open access: False)
    
[[https://openalex.org/A5074866068][Kai Yang]], [[https://openalex.org/A5100624279][Yuanjun Liu]], [[https://openalex.org/A5084900296][Yuyu Liu]], [[https://openalex.org/A5037822353][Xingmei Guo]], [[https://openalex.org/A5102953258][Xiangjun Zheng]], [[https://openalex.org/A5100664142][Junhao Zhang]], [[https://openalex.org/A5087023195][Guoxing Zhu]], Chinese Journal of Chemical Engineering. None(None)] 2024. https://doi.org/10.1016/j.cjche.2024.07.023 
     
No abstract    

    

* Evolution of oxygen and stratification and their relationship in the North Pacific Ocean in CMIP6 Earth system models  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402522349
:TOPICS: Climate Change and Paleoclimatology, Anaerobic Methane Oxidation and Gas Hydrates, Oceanic Modeling and Circulation Studies
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/bg-21-3985-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402522349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402522349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402522349"))][Get cited by]]

OpenAlex: https://openalex.org/W4402522349 (Open access: True)
    
[[https://openalex.org/A5045710398][Lyuba Novi]], [[https://openalex.org/A5073045368][Annalisa Bracco]], [[https://openalex.org/A5049005458][Takamitsu Ito]], [[https://openalex.org/A5063962207][Yohei Takano]], Biogeosciences. 21(17)] 2024. https://doi.org/10.5194/bg-21-3985-2024 
     
Abstract. This study examines the linkages between the upper-ocean (0–200 m) oxygen (O2) content and stratification in the North Pacific Ocean using four Earth system models (ESMs), an ocean hindcast simulation, and an ocean reanalysis. The trends and variability in oceanic O2 content are driven by the imbalance between physical supply and biological demand. Physical supply is primarily controlled by ocean ventilation, which is responsible for the transport of O2-rich surface waters to the subsurface. Isopycnic potential vorticity (IPV), a quasi-conservative tracer proportional to density stratification that can be evaluated from temperature and salinity measurements, is used herein as a dynamical proxy for ocean ventilation. The predictability potential of the IPV field is evaluated through its information entropy. The results highlight a strong O2–IPV connection and somewhat higher (as compared to the rest of the basin) predictability potential for IPV across the tropical Pacific, where the El Niño–Southern Oscillation occurs. This pattern of higher predictability and strong anticorrelation between O2 and stratification is robust across multiple models and datasets. In contrast, IPV at mid-latitudes has low predictability potential and its center of action differs from that of O2. In addition, the locations of extreme events or hotspots may or may not differ between the two fields, with a strong model dependency, which persists in future projections. On the one hand, these results suggest that it may be possible to monitor ocean O2 in the tropical Pacific based on a few observational sites co-located with the more abundant IPV measurements; on the other, they lead us to question the robustness of the IPV–O2 relationship in the extratropics. The proposed framework helps to characterize and interpret O2 variability in relation to physical variability and may be especially useful in the analysis of new observation-based data products derived from the BGC-Argo float array in combination with the traditional but far more abundant Argo data.    

    

* Oxygen-induced evolution of anammox granular sludge explains its unique responses during preservation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402533251
:TOPICS: Microbial Nitrogen Cycling in Wastewater Treatment Systems, Application of Constructed Wetlands for Wastewater Treatment
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.watres.2024.122447")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402533251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402533251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402533251"))][Get cited by]]

OpenAlex: https://openalex.org/W4402533251 (Open access: False)
    
[[https://openalex.org/A5012427370][Leiyan Guo]], [[https://openalex.org/A5101594693][Chao Pan]], [[https://openalex.org/A5100392071][Wei Wang]], [[https://openalex.org/A5100411379][Yang Yu]], [[https://openalex.org/A5030367743][Dongdong Xu]], [[https://openalex.org/A5037687318][Wenda Chen]], [[https://openalex.org/A5101707590][Wenji Li]], [[https://openalex.org/A5100688078][Ping Zheng]], [[https://openalex.org/A5100437750][Meng Zhang]], Water Research. None(None)] 2024. https://doi.org/10.1016/j.watres.2024.122447 
     
No abstract    

    

* Understanding the evolution of molybdenum-nitrogen doped carbon with long-term durability for efficient oxygen reduction reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402546983
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.155778")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402546983"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402546983"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402546983"))][Get cited by]]

OpenAlex: https://openalex.org/W4402546983 (Open access: False)
    
[[https://openalex.org/A5039256728][Xingyu Luo]], [[https://openalex.org/A5032925772][Bingbao Mei]], [[https://openalex.org/A5102219039][Ru Feng]], [[https://openalex.org/A5070471951][Xiaofeng Xu]], [[https://openalex.org/A5090182164][Zhongyan Zhang]], [[https://openalex.org/A5083029433][Mingyu Ou]], [[https://openalex.org/A5073162955][Fanfei Sun]], [[https://openalex.org/A5052267311][Huajun Zheng]], [[https://openalex.org/A5068056660][Meiqin Shi]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.155778 
     
No abstract    

    

* MOF-Derived Ni/NiO-C Nanocomposites as Bifunctional Electrocatalysts Capable of Driving Both ORR and OER  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402518343
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c02856")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402518343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402518343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402518343"))][Get cited by]]

OpenAlex: https://openalex.org/W4402518343 (Open access: False)
    
[[https://openalex.org/A5034154670][Sagarmani Rasaily]], [[https://openalex.org/A5085239724][Shivanand Chettri]], [[https://openalex.org/A5001575217][Debesh Sharma]], [[https://openalex.org/A5031222788][Khanindram Baruah]], [[https://openalex.org/A5056511280][Rajani Dewan]], [[https://openalex.org/A5061637624][Sudarsan Tamang]], [[https://openalex.org/A5007779130][Anand Pariyar]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c02856 
     
Bifunctional electrocatalysts, capable of efficiently driving both the oxygen reduction reaction (ORR) and the oxygen evolution reaction (OER), are crucial for advancing electrochemical processes. While noble-metal-based catalysts are widely recognized for their role in oxygen processes, current state-of-the-art designs are limited to either ORR or OER activity, presenting a notable research gap. In addressing this challenge, we have developed a novel    

    

* Isolated Octahedral Pt-Induced Electron Transfer to Ultralow-Content Ruthenium-Doped Spinel Co3O4 for Enhanced Acidic Overall Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402507216
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c07089")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402507216"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402507216"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402507216"))][Get cited by]]

OpenAlex: https://openalex.org/W4402507216 (Open access: False)
    
[[https://openalex.org/A5100446377][Di Li]], [[https://openalex.org/A5017666924][Da‐Zhen Xu]], [[https://openalex.org/A5006399803][Yuhou Pei]], [[https://openalex.org/A5100652206][Qicheng Zhang]], [[https://openalex.org/A5032392383][Yingying Lü]], [[https://openalex.org/A5048496954][Bing Zhang]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c07089 
     
The development of a highly active and stable oxygen evolution reaction (OER) electrocatalyst is desirable for sustainable and efficient hydrogen production via proton exchange membrane water electrolysis (PEMWE) powered by renewable electricity yet challenging. Herein, we report a robust Pt/Ru-codoped spinel cobalt oxide (PtRu-Co    

    

* Mo-Induced Surface Reconstruction in Ni/Co-OOH Prickly Flower Clusters for Improving the Hydrogen Production in Alkaline Seawater Splitting.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402554797
:TOPICS: Catalytic Nanomaterials, Desulfurization Technologies for Fuels, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202404858")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402554797"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402554797"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402554797"))][Get cited by]]

OpenAlex: https://openalex.org/W4402554797 (Open access: False)
    
[[https://openalex.org/A5100444342][Wen Zhang]], [[https://openalex.org/A5036318925][Jianyang Gao]], [[https://openalex.org/A5005485664][Qixing Gong]], [[https://openalex.org/A5100708318][Fusheng Liu]], [[https://openalex.org/A5100354843][Yang Zhang]], [[https://openalex.org/A5060955767][Guangrui Xu]], [[https://openalex.org/A5048731817][Zexing Wu]], [[https://openalex.org/A5058772567][Lei Wang]], PubMed. None(None)] 2024. https://doi.org/10.1002/smll.202404858 
     
Seawater electrolysis is the most promising technology for hydrogen production, in which surface reconstruction on the interface of electrode/electrolyte plays a crucial role in activating the catalytic reactions with a low activation energy barrier. Herein, an efficient Mo modifying NiCoMo prickly flower clusters electrocatalyst supported on nickel foam (Mo-doped Ni/Co-OOH prickly flower clusters) is obtained, which serves as an eminently active and durable catalyst for both hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) due to the surface reconstruction during the alkaline seawater electrolysis with ultralow overpotentials. It just requires a cell voltage of 1.52 V to achieve the current density of 10 mA cm    

    

* Catalytic Properties of Polyampholytes, Polyampholyte-Metal Complexes, Polyampholyte-Metal Nanoparticles and Polyampholyte-Enzyme Conjugates: a Mini-Review  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402527974
:TOPICS: Catalytic Reduction of Nitro Compounds, Dendrimer-Encapsulated Nanoparticles and Hyperbranched Polymers
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.31489/2959-0663/3-24-8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402527974"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402527974"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402527974"))][Get cited by]]

OpenAlex: https://openalex.org/W4402527974 (Open access: False)
    
[[https://openalex.org/A5045844357][Sarkyt E. Kudaibergenov]], Eurasian Journal of Chemistry. None(None)] 2024. https://doi.org/10.31489/2959-0663/3-24-8 
     
This mini-review briefly discusses the catalytic properties of polyampholytes, polyampholyte-metal complexes, polyampholyte-metal nanoparticles and polyampholyte-catalase conjugates. Polyampholyte-based catalysts can mimic enzyme functions, facilitating reactions like hydrolysis, decomposition, hydrogenation, and oxidation of various substrates. Special focus is given to amphoteric hydrogels and cryogels that encapsulate metal nanoparticles or enzymes. These materials have demonstrated effectiveness in the hydrogenation of nitroaromatic compounds, oxidation of disulfide and aliphatic (or aromatic) alcohols under mild conditions, both in batch and flow-through reactors. Kinetic parameters, turnover numbers (TON), turnover frequencies (TOF), and activation energies are presented for a series of specific catalytic processes. Notably, flow-through reactors exhibit significantly higher catalytic efficiency compared to batch reactors and can be used continuously for extended periods. Additionally, the review explores the potential of light-driven hydrogen and oxygen evolution reactions from water, facilitated by metal nanoparticles within amphoteric hydrogels in the presence of photosensitizers.    

    

* New Nanostructure NiO–GeSe Core–Shell/MAPbBr3 Solar Cell in Solar Photoelectrochemical Water Splitting: Superior Efficiency Enhancement  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402574927
:TOPICS: Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1155/2024/9454136")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402574927"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402574927"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402574927"))][Get cited by]]

OpenAlex: https://openalex.org/W4402574927 (Open access: True)
    
[[https://openalex.org/A5094218383][Maryam Shahrostami]], [[https://openalex.org/A5021811079][Mehdi Eskandari]], [[https://openalex.org/A5040960527][Davood Fathi]], International Journal of Energy Research. 2024(1)] 2024. https://doi.org/10.1155/2024/9454136 
     
Solar‐driven photoelectrochemical (PEC) water‐splitting cells coupled with a photovoltaic (PV) cell as a photoanode have become an intriguing topic in solar energy conversion. In this study, for the purpose of developing a system with high efficiency, several photoanode materials were investigated to adjust the oxygen evolution reaction and the hydrogen evolution reaction (HER) energy bands. Among all, MAPbBr 3 with a wide bandgap (2.3 eV) was selected. However, the power conversion efficiency of the PV cell was not desirable due to the low light absorption. Therefore, the NiO–GeSe core–shell was placed inside the perovskite layer to enhance light absorption and carrier generation. In order to achieve a cell with the maximum performance, the core–shell height, and the shell radius were optimized, where the optimum structure was recognized with a core–shell height of 300 nm and a radius of 25–60 nm. The system’s total efficiency, which is represented by the solar to hydrogen efficiency, was then increased from 5.49% to 19.74% for the planar and nanostructure photoanode, respectively. The proposed PEC cell with the optimized photoanode is considered as the most efficient half‐tandem and perovskite‐based reported coupled system, operating without the need for an external voltage. In this study, three optical, electrical, and electrochemical models were solved using the finite element method to analyze the coupled system.    

    

* A Rechargeable Urea‐Assisted Zn‐Air Battery with High Energy Efficiency and Fast‐Charging Enabled by Engineering High‐Energy Interfacial Structures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402542551
:TOPICS: Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-09-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202410845")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402542551"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402542551"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402542551"))][Get cited by]]

OpenAlex: https://openalex.org/W4402542551 (Open access: False)
    
[[https://openalex.org/A5000272762][Mingjie Wu]], [[https://openalex.org/A5003409409][Yinghui Xu]], [[https://openalex.org/A5071388400][Jian Luo]], [[https://openalex.org/A5103154463][Siyi Yang]], [[https://openalex.org/A5023395031][Gaixia Zhang]], [[https://openalex.org/A5017404634][Lei Du]], [[https://openalex.org/A5068328164][Huixia Luo]], [[https://openalex.org/A5037920786][Xun Cui]], [[https://openalex.org/A5046799991][Yingkui Yang]], [[https://openalex.org/A5080743510][Shuhui Sun]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202410845 
     
Electrochemical urea oxidation reaction (UOR) offers a promising alternative to the oxygen evolution reaction (OER) in clean energy conversion and storage systems. Nickel‐based catalysts are highly regarded as promising electrocatalysts for the UOR. However, their effectiveness is significantly hindered by the unavoidable self‐oxidation reaction of nickel species during UOR. To address this challenge, we proposed an interface chemistry modulation strategy to boost UOR kinetics by creating a high‐energy interfacial heterostructure. This heterostructure features the incorporation of Ag at the CoOOH@NiOOH heterojunction interface. Strong interactions significantly promote the electron exchanges in the heterointerface between the ‐OH and ‐O. Consequently, the improved electron delocalization led to the formation of stronger bonds between Co sites and urea CO(NH2)2, promoting a preference for urea to occupy Co active sites over OH*. The resulting catalyst, Ag‐CoOOH@NiOOH, affords an ultrahigh UOR activity with a low potential of 1.33 V at 100 mA cm‐2. The fabricated catalyst exhibits a mass activity exceeding that of initial cobalt oxyhydroxide by over 11.9 times. The rechargeable urea‐assisted zinc‐air batteries (ZABs) achieves a record‐breaking energy efficiency of 74.56% at 1 mA cm‐2, remarkable durability (1000 hours at even a current density of 50 mA cm‐2), and quick charge performances.    

    

* Direct Evidence for Buffer-Enhanced Proton-Coupled Electron Transfer in Metal Aquo Bond Formation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402529806
:TOPICS: Molecular Electronic Devices and Systems, Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-l776x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402529806"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402529806"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402529806"))][Get cited by]]

OpenAlex: https://openalex.org/W4402529806 (Open access: False)
    
[[https://openalex.org/A5080823071][Matthew C. Kessinger]], [[https://openalex.org/A5005799122][Thomas Whittemore]], [[https://openalex.org/A5033549112][Silvia Grandi]], [[https://openalex.org/A5064486136][Evgeny O. Danilov]], [[https://openalex.org/A5004379175][Stefano Caramori]], [[https://openalex.org/A5017888744][Felix N. Castellano]], [[https://openalex.org/A5073119387][Gerald J. Meyer]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-l776x 
     
Proton-coupled electron transfer (PCET) reactions play a crucial role in the interconversion of metal-aqua and metal-hydroxo species present in transition metal complexes and oxide surfaces (M(III)-OH + e− + H+ M(II)-OH2). For ruthenium-based water oxidation catalysts, PCET reactions involved in the mechanism of oxygen evolution have demonstrated a strong dependence on the identity and concentration of the proton donor and acceptor with significant rate enhancements observed for electrocatalysis performed in acetate, phosphate, and borate buffered electrolytes. However, the systematic study of this phenomenon has been hampered by the inability to independently measure discrete rates for electron transfer (ET) and proton transfer (PT) under electrochemical applied potentials. Herein, the PCET kinetics and mechanism of metal aqua bond formation in a ruthenium water oxidation catalyst [Ru(tpy)(bpy′)H2O]2+, Ru(II)−OH2 where tpy is 2,2′:6′,2″-terpyridine and bpy′ is 4,4′-diaminopropylsilatrane-2,2′-bypyridine were investigated at a conductive metal oxide interface as a function of buffer identity and concentration. The reaction of interest was triggered by visible light excitation of the catalyst and the kinetics of the independent ET and PT steps of the PCET mechanism were determined through nanosecond transient absorption spectroscopy. Kinetic measurements performed in aqueous acetate, phosphate, or borate buffer solutions revealed two distinct regimes of PT kinetics solely dependent on the buffer concentration. At the greatest buffer concentrations investigated (2 M acetate) spectral signals corresponding to the discreet ET and PT steps were absent indicative in a change in underlying PCET mechanism. Likewise, kinetic modeling indicated that PT from protonated acetate or phosphate occurred with rate constants that were 2-4 orders of magnitude greater than those for bulk water. In all, these results suggest that the presence of buffer-bases can significantly enhance PCET rates and, in this reaction, may alter the underlying mechanism.    

    

* A perspective to efficient synthesis of zirconium carbide via novel pyro-vacuum method: lower temperatures and enhanced purity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402559567
:TOPICS: Synthesis and Properties of Cemented Carbides, Ceramic Materials and Processing, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.53063/synsint.2024.43233")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402559567"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402559567"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402559567"))][Get cited by]]

OpenAlex: https://openalex.org/W4402559567 (Open access: False)
    
[[https://openalex.org/A5005505945][Faramarz Kazemi]], [[https://openalex.org/A5005077956][Behzad Nayebi]], Synthesis and Sintering. 4(3)] 2024. https://doi.org/10.53063/synsint.2024.43233 
     
The use of ultra-high temperature ceramics (UHTCs) as a novel additive in the refractory industry is becoming increasingly popular. However, the synthesis of such materials is associated with some commercial obstacles, mainly high-temperature synthesis methods. In the present study, the pyro-vacuum method is presented as a new method to decrease the final product's synthesis temperature and oxygen content. Some thermodynamic aspects and phase evolution of the materials during the synthesis procedure are described for the synthesis of non-oxide material. Conclusively, it seems that by applying vacuum conditions, the final UHTC phases can be synthesized at significantly lower temperatures (>400 °C lower, for ZrC), if adequate powder mixtures are considered. Also due to phase analysis, it was found that the oxygen content of the final phase is lower than the conventional routes and other references. The process provides promising prospects for the economic synthesis of UHTCs.    

    

* 2D TiNBr as photocatalyst for overall water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402583716
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-09-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-vxdq4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402583716"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402583716"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402583716"))][Get cited by]]

OpenAlex: https://openalex.org/W4402583716 (Open access: False)
    
[[https://openalex.org/A5060550190][Yatong Wang]], [[https://openalex.org/A5047589722][Geert Brocks]], [[https://openalex.org/A5047674683][Ceren Tayran]], [[https://openalex.org/A5073500004][Süleyman Er]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-vxdq4 
     
Two-dimensional (2D) Janus materials gain increasing attention as water splitting photocatalysts for hydrogen production. We use first-principles calculations to predict a stable 2D Janus $T$-TiNBr structure, with strong near-ultraviolet sunlight absorption and band edges that align favorably with the water redox potentials for oxygen and hydrogen evolution. We show that the optical and electronic properties of $T$-TiNBr can be modulated to a certain extend by applying external uniaxial strain. Explicit calculations of the redox reactions reveal that solar-driven water splitting is viable at the N-side of $T$-TiNBr, while the Br-side requires modifications such as vacancy creation, the application of an external potential, or adjustment of the pH conditions.    

    

* Depth-resolved characterization of Meissner screening breakdown in surface treated niobium  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402541511
:TOPICS: Accelerator Technology and Superconducting Cavities, Vacuum Electronic High Power Terahertz Sources, Plasma Physics and Technology in Semiconductor Industry
:PUBLICATION_DATE: 2024-09-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41598-024-71724-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402541511"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402541511"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402541511"))][Get cited by]]

OpenAlex: https://openalex.org/W4402541511 (Open access: True)
    
[[https://openalex.org/A5033617037][Edward Thoeng]], [[https://openalex.org/A5066212291][Md Asaduzzaman]], [[https://openalex.org/A5024868933][Philipp Kolb]], [[https://openalex.org/A5065665606][Ryan M. L. McFadden]], [[https://openalex.org/A5017930902][G. D. Morris]], [[https://openalex.org/A5054818798][John O. Ticknor]], [[https://openalex.org/A5020731483][S. R. Dunsiger]], [[https://openalex.org/A5065523228][Victoria L. Karner]], [[https://openalex.org/A5082660511][Derek Fujimoto]], [[https://openalex.org/A5047356504][Tobias Junginger]], [[https://openalex.org/A5055420269][R. F. Kiefl]], [[https://openalex.org/A5070714748][W. A. MacFarlane]], [[https://openalex.org/A5002878273][Ruohong Li]], [[https://openalex.org/A5013346237][Suresh Saminathan]], [[https://openalex.org/A5046714003][Robert Laxdal]], Scientific Reports. 14(1)] 2024. https://doi.org/10.1038/s41598-024-71724-5 
     
We report direct measurements of the magnetic field screening at the limits of the Meissner phase for two superconducting niobium (Nb) samples. The samples are processed with two different surface treatments that have been developed for superconducting radio-frequency (SRF) cavity applications-a "baseline" treatment and an oxygen-doping ("O-doping") treatment. The measurements show: (1) that the screening length is significantly longer in the "O-doping" sample compared to the "baseline" sample; (2) that the screening length near the limits of the Meissner phase increases with applied field; (3) the evolution of the screening profile as the material transitions from the Meissner phase to the mixed phase; and (4) a demonstration of the absence of any screening profile for the highest applied field, indicative of the full flux entering the sample. Measurements are performed utilizing the    

    

* Treatment of domestic wastewater and extracellular polymeric substance accumulation in siphon‐type composite vertical subsurface flow constructed wetland  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402570326
:TOPICS: Application of Constructed Wetlands for Wastewater Treatment, Microbial Nitrogen Cycling in Wastewater Treatment Systems, Advancements in Water Purification Technologies
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/wer.11132")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402570326"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402570326"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402570326"))][Get cited by]]

OpenAlex: https://openalex.org/W4402570326 (Open access: False)
    
[[https://openalex.org/A5100353673][Hao Chen]], [[https://openalex.org/A5085485915][Lin Qiu]], [[https://openalex.org/A5046179350][Hong Wu]], [[https://openalex.org/A5102542811][Fahui Nie]], [[https://openalex.org/A5101455992][Yong Liu]], [[https://openalex.org/A5103208347][Wenping Cao]], Water Environment Research. 96(9)] 2024. https://doi.org/10.1002/wer.11132 
     
Abstract In this study, the siphon‐type composite vertical flow constructed wetland (Sc‐VSsFCW) was constructed with anthracite and shale ceramsite chosen as the substrate bed materials. During the 90‐day experiment, typical pollutant removal effects of wastewater and extracellular polymeric substance (EPS) accumulation were investigated. Meanwhile, X‐ray diffraction and scanning electron microscopy were used to examine the phase composition and surface morphology to analyze adsorptive property. Additionally, we evaluated the impact of siphon effluent on clogging and depolymerization by measuring the EPS components' evolution within the system. The findings reveal that both the anthracite and shale ceramsite systems exhibit impressive removal efficiencies for total phosphorus (TP), total dissolved phosphorus (TDP), soluble reactive phosphorus (SRP), chemical oxygen demand (COD), ammonium nitrogen (NH 4 + ‐N), and nitrate nitrogen (NO 3 − ‐N). However, as the experiment progressed, TP removal rates in both systems gradually declined because of the saturation of adsorption sites on the substrate surfaces. Although the dissolved oxygen (DO) levels remained relatively stable throughout the experiment, pH exhibited distinct patterns, suggesting that the anthracite system relies primarily on chemical adsorption, whereas the shale ceramsite system predominantly utilizes physical adsorption. After an initial period of fluctuation, the permeability coefficient and porosity of the system gradually stabilized, and the protein and polysaccharide contents in both systems exhibited a downward trend. The study underscores that anthracite and shale ceramsite have good effectiveness in pollutant removal as substrate materials. Overall, the hydraulic conditions of the double repeated oxygen coupling siphon in the Sc‐VSsFCW system contribute to enhanced re‐oxygenation capacity and permeability coefficient during operation. The changes in EPS content indicate that the siphon effluent exerts a certain depolymerization effect on the EPS within the system, thereby mitigating the risk of biological clogging to a certain extent. Practitioner Points The system can still maintain good pollutant treatment effect in long‐term operation. The re‐oxygenation method of the system can achieve efficient and long‐term re‐oxygenation effect. The siphon effluent has a certain improvement effect on the permeability coefficient and porosity, but it cannot effectively inhibit the occurrence of clogging. The EPS content did not change significantly during the operation of the system, and there was a risk of biological clogging.    

    

* Ferric Iron Evolution During Crystallization of the Earth and Mars  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402525918
:TOPICS: Magnetosome Formation in Prokaryotes, Exploration and Study of Mars, Machine Learning for Mineral Prospectivity Mapping
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1029/2023je008262")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402525918"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402525918"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402525918"))][Get cited by]]

OpenAlex: https://openalex.org/W4402525918 (Open access: False)
    
[[https://openalex.org/A5052639092][Laura Schaefer]], [[https://openalex.org/A5024217562][Kaveh Pahlevan]], [[https://openalex.org/A5033726538][L. T. Elkins‐Tanton]], Journal of Geophysical Research Planets. 129(9)] 2024. https://doi.org/10.1029/2023je008262 
     
Abstract Magma ocean crystallization models that track f O 2 evolution can reproduce the D/H ratios of both the Earth and Mars without the need for exogenous processes. Fractional crystallization leads to compositional evolution of the bulk oxide components. Recent work suggests that metal‐saturated magma oceans may contain near‐present‐day Fe 3+ concentrations. We model the fractional crystallization of Earth and Mars, including Fe 2+ and Fe 3+ as separate components. We calculate Fe 3+ partition coefficients for lower mantle minerals and compare the results of fractional crystallization for both Earth and Mars. We calculate oxygen fugacity ( f O 2 ) at the surface as the systems evolve and compare them to constraints on the f O 2 of the last magma ocean atmosphere from D/H ratios, both with and without metal saturation. For Earth, we find that Fe 3+ likely behaves incompatibly in the lower mantle in order to match the D/H constraint for whole mantle models, but shallow magma ocean models also provide reasonable matches. Disproportionation in whole mantle magma oceans likely overpredicts the amount of Fe 3+ and metal that form or require subsequent reduction to return to present‐day values. For Mars, we cannot match the D/H constraints on last f O 2 unless the magma ocean begins with <50% of the predicted Fe 3+ , but better match the present day mantle redox. We show that Fe 3+ partitioning has a measurable effect on magma ocean redox, and that it evolves throughout the magma ocean's lifetime. We highlight the need for additional experimental constraints on ferric iron mineral/melt partitioning and more thermodynamic data for the Fe‐disproportionation reaction.    

    

* The Star–Planet Composition Connection  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402503252
:TOPICS: Formation and Evolution of the Solar System, Stellar Astrophysics and Exoplanet Studies, Star Formation in Molecular Clouds and Protoplanetary Disks
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1146/annurev-astro-071221-053007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402503252"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402503252"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402503252"))][Get cited by]]

OpenAlex: https://openalex.org/W4402503252 (Open access: False)
    
[[https://openalex.org/A5047489063][Johanna Teske]], Annual Review of Astronomy and Astrophysics. 62(1)] 2024. https://doi.org/10.1146/annurev-astro-071221-053007 
     
The mantra “know thy star, know thy planet” has proven to be very important for many aspects of exoplanet science. Here I review how stellar abundances inform our understanding of planet composition and, thus, formation and evolution. In particular, I discuss how: ▪ The strongest star–planet connection is still the giant planet–metallicity correlation, the strength of which may indicate a break point between the formation of planets versus brown dwarfs. ▪ We do not have very good constraints on the lower metallicity limit for planet formation, although new statistics from TESS are helping, and it appears that, at low [Fe/H], α elements can substitute for iron as seeds for planet formation. ▪ The depletion of refractory versus volatile elements in stellar photospheres (particularly the Sun) was initially suggested as a sign of small planet formation but is challenging to interpret, and small differences in binary star compositions can be attributed mostly to processes other than planet formation. ▪ We can and should go beyond comparisons of the carbon-to-oxygen ratio in giant planets and their host stars, incorporating other volatile and refractory species to better constrain planet formation pathways. ▪ There appears to be a positive correlation between small planet bulk density and host star metallicity, but exactly how closely small planet refractory compositions match those of their host stars—and their true diversity—is still uncertain.    

    

* Modeling and 3-D simulation of petroleum coke calcination process: investigation of the effect of main operating variables  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402507204
:TOPICS: Biomass Pyrolysis and Conversion Technologies, Zeolite Chemistry and Catalysis, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1515/ijcre-2024-0016")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402507204"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402507204"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402507204"))][Get cited by]]

OpenAlex: https://openalex.org/W4402507204 (Open access: False)
    
[[https://openalex.org/A5053498370][Mohammad Hosein Eghbal Ahmadi]], [[https://openalex.org/A5034222903][Shokoufe Tayyebi]], [[https://openalex.org/A5000473622][Amir Mosayebi]], International Journal of Chemical Reactor Engineering. None(None)] 2024. https://doi.org/10.1515/ijcre-2024-0016 
     
Abstract Coke calcination is a process that involves heating green petroleum coke to purify it and eliminate volatile materials for subsequent processing. Due to the complexity of the rotary kiln used in this process, conducting experimental studies can be challenging and restricted. However, quantitative analyses based on developed models can provide a foundation for optimizing and controlling the process, which can significantly enhance the design efficiency. A three-dimensional simulation model of a rotary calcining kiln for petroleum coke was created using COMSOL Multiphysics in a steady-state mode. This model accounted for all relevant physical and chemical phenomena in the gas stream and coke bed flow, including heat transfer, combustion, and the evolution of volatile matter and coke dust. The mathematical modeling yielded distributions of temperature and mass fractions within the kiln, as well as the velocity field. The results revealed two distinct peak temperatures in the gas phase: 1,780 K near the primary air injection point and 1,605 K near the tertiary air injection points. The findings were analyzed, and the impact of key variables was explored. The simulation data indicated that for every decrease of 10–15 m/s in air flow, the gas peak temperature dropped by approximately 100°. Additionally, an increase in the input oxygen concentration led to enhanced combustion, resulting in higher peak concentrations of CO 2 . The developed simulation model has proven to be a valuable and promising tool for the design and optimization of petroleum coke rotary kilns.    

    

* Enhancing Built‐In Electric Field via Defect‐Mediated Interfacial Chemical Bond Construction in Chalcogenide Heterojunction for Alcohol Photooxidation Coupled with H2 Production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402541839
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-09-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202411991")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402541839"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402541839"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402541839"))][Get cited by]]

OpenAlex: https://openalex.org/W4402541839 (Open access: False)
    
[[https://openalex.org/A5103937843][Yi‐Wen Han]], [[https://openalex.org/A5016978102][Ying‐Hao Chu]], [[https://openalex.org/A5031783119][Lei Ye]], [[https://openalex.org/A5049677180][Tian‐Jun Gong]], [[https://openalex.org/A5049639221][Xuebin Lü]], [[https://openalex.org/A5100719200][Yao Fu]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202411991 
     
Abstract Rationally designing nanostructures based on an adequate understanding of structure‐performance relationships is key for directional charge transfer regulation in heterojunction photocatalysts. A general strategy is developed for synthesizing bifunctional Sv‐chalcogenide/Ti 3 C 2 Schottky junctions (Sv = sulfur vacancies, chalcogenides containing CdS, CdIn 2 S 4 , ZnIn 2 S 4 , ZnS, CuInS 2 ) featuring a giant built‐in electric field (BIEF) via defect‐mediated heterocomponent anchorage, which consists of sulfur vacancy modulation of chalcogenides and Ti 3 C 2 nanoparticle anchoring at defects via interfacial Metal─Oxygen (M─O) bonds. These heterojunctions have the distinctive interface structure of semicoherent phase boundaries and a directionally aligned BIEF pointing from chalcogenides to Ti 3 C 2 . The enhanced BIEF creates an asymmetrical charge distribution, which not only governs the charge migration behavior by enabling charge carrier localization and delocalized electron transport continuity but also regulates the molecular catalytic behavior by optimizing pivotal intermediate adsorption/activation ( * Ar‐CH(R 2 )‐OH in dehydrogenation and H * in H 2 evolution) in selective alcohol photooxidation coupled with H 2 generation. Encouragingly, Sv‐chalcogenide/Ti 3 C 2 exhibits unprecedented performance (up to 13.34‐fold higher efficiency than unmodulated chalcogenides) and good substrate compatibility for various alcohols. This work demonstrates the synergistic effects of surface electron density control and interfacial interaction modulation in regulating BIEFs, elucidating the substantial impact of reinforced BIEF on carrier transport properties and molecular catalytic behavior.    

    
