#+TITLE: water splitting
Description: water splitting papers
Created on Mon Sep 30 01:22:23 2024

Found 5 results from 2024-09-23 to 2024-09-30
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Enhance the Proportion of Fe3+ in NiFe‐Layered Double Hydroxides by utilizing Citric Acid to Improve the Efficiency and Durability of the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402720922
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Layered Double Hydroxide Nanomaterials
:PUBLICATION_DATE: 2024-09-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401582")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402720922"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402720922"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402720922"))][Get cited by]]

OpenAlex: https://openalex.org/W4402720922 (Open access: False)
    
[[https://openalex.org/A5101527396][Guoqi Li]], [[https://openalex.org/A5100412807][Lin Li]], [[https://openalex.org/A5022371210][Jihao Zhang]], [[https://openalex.org/A5102658611][Shiran Shan]], [[https://openalex.org/A5072872054][Chunze Yuan]], [[https://openalex.org/A5006108211][Tsu‐Chien Weng]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401582 
     
NiFe-layered double hydroxides (NiFe-LDH) are a type of catalyst known for their exceptional catalytic performance during the oxygen evolution reaction (OER). In this study, citric acid was incorporated into the synthesis process of NiFe-LDH, resulting in the NiFe-LDH-CA catalyst with superior OER performance. The catalytic efficacy is evaluated using linear sweep voltammetry (LSV), which demonstrates a significant reduction in the OER overpotential from 320 mV to 240 mV at a current density of 100 mA cm-2. X-ray photoelectron spectroscopy (XPS) and X-ray absorption spectrum (XAS) indicate that the distribution of nickel valence states showed no significant difference between two samples, yet the NiFe-LDH-CA has a significantly higher proportion of Fe3+ ions in its iron content. In-situ Raman spectroscopes reveal that Fe3+ broadens the redox potential of nickel and Pourbaix diagrams indicate that higher Fe3+ levels could facilitate the interaction with oxygen active sites. Based on the analysis of test data, we propose a hypothesis that the high proportion of Fe3+ in catalysts may accelerate the oxygen evolution process by modulating the redox potential of nickel and engaging with reactive oxygen species. This provides valuable insights into how to improve the reaction rate of nickel-based catalysts.    

    

* Electrocatalytic activity of La0.6Sr0. 4Co1-yCuyO3 (y = 0.1, 0.2, and 0.3) for oxygen evolution in an alkaline medium at 25℃  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402782270
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.56042/ijc.v63i9.10838")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402782270"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402782270"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402782270"))][Get cited by]]

OpenAlex: https://openalex.org/W4402782270 (Open access: False)
    
, Indian Journal of Chemistry. 63(9)] 2024. https://doi.org/10.56042/ijc.v63i9.10838 
     
No abstract    

    

* Development of Potential Electrocatalyst: Highly Multiporous WO3–rGO Nanocomposites for Enhancing Electrocatalytic Oxygen Evolution Reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402839871
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/slct.202402770")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402839871"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402839871"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402839871"))][Get cited by]]

OpenAlex: https://openalex.org/W4402839871 (Open access: False)
    
[[https://openalex.org/A5065182369][Aniruddha Mondal]], [[https://openalex.org/A5102129485][P. C. Srivastava]], [[https://openalex.org/A5102662903][Anand Prakash Singh]], [[https://openalex.org/A5023573813][Amanullah Fatehmulla]], [[https://openalex.org/A5057222563][Kotesh Kumar Mandari]], ChemistrySelect. 9(36)] 2024. https://doi.org/10.1002/slct.202402770 
     
Abstract The development of sustainable energy technologies, such as fuel cells and metal–air batteries, necessitates the use of a highly efficient electrocatalyst for the oxygen evolution process. The fabrication of WO 3 –rGO nanocomposites results in the formation of a multiporous nanostructure. The catalytic activity of highly multiporous WO 3 –rGO nanocomposites containing multiporous nanostructures is shown to be significant. The catalyst has the potential to facilitate highly reactive anodic oxygen reactions, hence augmenting the synergistic impact of interfacial charge transfer and the porous structure of WO 3 –rGO nanocomposites. The findings of this work indicate that the use of WO 3 –rGO nanocomposites as electrocatalysts exhibits a considerable overpotential value of 350 mV, a Tafel slope of 67 mV dec −1 , good stability, roughness factor, and turnover frequency for the process of oxygen evolution in real‐world scenarios.    

    

* Geobiology: When did animals develop their oxygen habit?  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402737899
:TOPICS: Climate Change and Paleoclimatology, Paleoredox and Paleoproductivity Proxies, Marine Biodiversity and Ecosystem Functioning
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cub.2024.08.024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402737899"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402737899"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402737899"))][Get cited by]]

OpenAlex: https://openalex.org/W4402737899 (Open access: False)
    
[[https://openalex.org/A5080454473][Philip C. J. Donoghue]], [[https://openalex.org/A5049646665][Lewis Alcott]], Current Biology. 34(18)] 2024. https://doi.org/10.1016/j.cub.2024.08.024 
     
The rise of ocean oxygen levels is thought to have boosted the evolution of animals. Modelling of the sedimentary geochemical record provides evidence for a late Ediacaran rise in oxygen, though likely after the origin of animals.    

    

* Integrating Gen AI and Adaptive AI for Enterprise Solutions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402798801
:TOPICS: Impact of Big Data Analytics on Business Performance, Workflow Mining and Business Process Management, Collaborative Networks in Manufacturing and Organizations
:PUBLICATION_DATE: 2022-03-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.47363/jaicc/2022(1)e146")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402798801"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402798801"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402798801"))][Get cited by]]

OpenAlex: https://openalex.org/W4402798801 (Open access: False)
    
[[https://openalex.org/A5093687887][Chalamayya Batchu -]], [[https://openalex.org/A5093687888][Veera Venkt Satya -]], Journal of Artificial Intelligence & Cloud Computing. None(None)] 2022. https://doi.org/10.47363/jaicc/2022(1)e146 
     
Artificial Intelligence has revolutionized so much that it is influenced into our lives through all day-to-day objects such as phones, IoT objects and other technologies. In the evolution of AI two ground breaking technologies are making a huge impact, Generative AI and Adaptive AI. These technologies can groom the current AI by giving future scope in various domains of digital transformation. When Gen AI is like oxygen in AI as can learn pattern and relationship in a data set well enough to create unique images, text, audio, and video that still adhere to the underlying pattern. Adaptive AI is another emerging field of AI that seek to create intelligent systems to adapt changing circumstances and learning new circumstances. It's so flexible that it is capable of modifying the behavior in response to new information as changes are required in the environment. This paper focus on benefits and scope of integrating both technologies Gen AI and Adaptive AI for the enterprise solutions.    

    
