#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Wed Feb 21 00:43:57 2024

Found 36 results from 2024-02-14 to 2024-02-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Interplay between Defects and Short-Range Disorder Manipulating the Oxygen Evolution Reaction on a Layered Double Hydroxide Electrocatalyst  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391773871
:TOPICS: Electrocatalysis for Energy Conversion, Layered Double Hydroxide Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.3c02885")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391773871"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391773871"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391773871"))][Get cited by]]

OpenAlex: https://openalex.org/W4391773871 (Open access: False)
    
[[https://openalex.org/A5014502114][Zixian Li]], [[https://openalex.org/A5042488059][Jiangrong Yang]], [[https://openalex.org/A5013553103][Rui Gao]], [[https://openalex.org/A5033474784][Simin Xu]], [[https://openalex.org/A5035045458][Xianggui Kong]], [[https://openalex.org/A5029898691][Xiao Hua]], [[https://openalex.org/A5047701790][Pu Zhao]], [[https://openalex.org/A5036474813][Haigang Hao]], [[https://openalex.org/A5067218691][Dermot O’Hare]], [[https://openalex.org/A5019565719][Yufei Zhao]], The Journal of Physical Chemistry Letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.3c02885 
     
Improving the efficiency of the oxygen evolution reaction (OER) is crucial for advancing sustainable and environmentally friendly hydrogen energy. Layered double hydroxides (LDHs) have emerged as promising electrocatalysts for the OER. However, a thorough understanding of the impact of structural disorder and defects on the catalytic activity of LDHs remains limited. In this work, a series of NiAl-LDH models are systematically constructed, and their OER performance is rigorously screened through theoretical density functional theory. The acquired results unequivocally reveal that the energy increase induced by structural disorder is effectively counteracted at the defect surface, indicating the coexistence of defects and disorder. Notably, it is ascertained that the simultaneous presence of defects and disorder synergistically augments the catalytic activity of LDHs in the context of the OER. These theoretical findings offer valuable insights into the design of highly efficient OER catalysts while also shedding light on the efficacy of LDH electrocatalysts.    

    

* FeCoNi molybdenum-based oxides for efficient electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391774742
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.02.104")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391774742"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391774742"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391774742"))][Get cited by]]

OpenAlex: https://openalex.org/W4391774742 (Open access: False)
    
[[https://openalex.org/A5051102233][Weiliu Fan]], [[https://openalex.org/A5022846124][Chaofan Liu]], [[https://openalex.org/A5082475531][Hairong Wang]], [[https://openalex.org/A5003062406][Jiang Wu]], [[https://openalex.org/A5008768156][Sheng Chen]], [[https://openalex.org/A5030622927][Weijie Fang]], [[https://openalex.org/A5064863955][C. D. Wu]], [[https://openalex.org/A5038726113][Yong Quan]], [[https://openalex.org/A5066475931][Daolei Wang]], [[https://openalex.org/A5020788231][Yongfeng Qi]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.02.104 
     
The search for highly efficient and inexpensive electrocatalysts is crucial to the advancement of environmentally friendly and sustainable energy sources. Here, adopting a one-step hydrothermal method, we have effectively fabricated a self-supported multi-metal molybdenum-based oxide (FeCoNi-MoO4) on nickel foam (NF). In addition to changing the catalyst's microstructure, the introducing of Fe and Co, enhanced its active center count, improved its electronic structure, and in turn reduced the difficulty for high-valence Ni and Fe species to form, which accelerates the oxygen evolution reaction (OER) kinetics by promoting the development of the actual active materials, NiOOH and FeOOH. FeCoNi-MoO4 has outstanding OER performance, requiring just 204 mV overpotentials at 10 mA cm−2 and 271 mV at 100 mA cm−2. Its exceptional OER kinetics at both low and high currents are indicated by a Tafel slope of 50.6 mV dec−1, which is attributed to the combined effect of its multi-metal composition and a higher number of active sites. Moreover, the FeCoNi-MoO4 electrode was operated continuously for over 48 h. Furthermore, the density functional theory (DFT) results demonstrated that the introducing of Fe and Co, which quickens the rate of electron transfer during the electrocatalytic process, improves the ability of oxygen intermediate species to adsorb, and ultimately lowers the overpotential, is responsible for the increased electrocatalytic activity of FeCoNi-MoO4. This work offers hope for further developments in the sector by proposing an efficient approach for creating multi-active electrocatalysts that are stable, economical, and efficient.    

    

* Tri-metallic fluoride nanoplates immobilized on reduced graphene architectures as efficient oxygen evolution reaction catalyst  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391774927
:TOPICS: Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2024.118108")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391774927"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391774927"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391774927"))][Get cited by]]

OpenAlex: https://openalex.org/W4391774927 (Open access: False)
    
[[https://openalex.org/A5058891185][Yanhui Lu]], [[https://openalex.org/A5074088539][Chengang Pei]], [[https://openalex.org/A5085322409][Han Xu]], [[https://openalex.org/A5023214008][Yong Li]], [[https://openalex.org/A5076348504][Ho Seok Park]], [[https://openalex.org/A5052472508][Jung Kyu Kim]], [[https://openalex.org/A5090891492][Xu Yu]], Journal of Electroanalytical Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jelechem.2024.118108 
     
Exploring the transition metal fluoride-based catalysts with highly catalytic activity is of great importance to satisfy the electrochemical oxygen evolution reaction (OER). Herein, the tri-metallic (cobalt, iron, and nickel) fluorides immobilizing on reduced graphene oxide architectures (CoFeNiF-rGAs) are constructed by hydrothermal and low-temperature fluoridation. The hierarchical structure assembled by the π-π configuration of graphene can provide abundant channels for fast ion diffusion and guarantee the uniform loading of metal fluorides. Owing to the hierarchical morphology and the formation of metal fluorides/graphene interfaces, CoFeNiF-rGAs can show excellent OER performance. Only 238 mV of overpotential is required to achieve a current density of 10 mA cm−2 in alkaline electrolyte, and the Tafel slope (78.8 mV dec-1) and charge transfer resistance (13.6 Ω) are smaller than the control samples, respectively, implying a fast kinetic behavior during OER. The highly catalytic stability of CoFeNiF-rGAs is confirmed by 1000 cyclic voltammetry and chronoamperometry test for 20 h, and the boosted catalytic mechanism is elucidated by density function theory calculation.    

    

* Transition Metals Based Dual Single‐atom Catalysts for Oxygen Electrocatalysis: Stunning Advances and Future Prospects  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391778585
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301392")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391778585"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391778585"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391778585"))][Get cited by]]

OpenAlex: https://openalex.org/W4391778585 (Open access: False)
    
[[https://openalex.org/A5033369944][Saira Ajmal]], [[https://openalex.org/A5035446738][Yang Zhao]], [[https://openalex.org/A5002637244][Ghulam Yasin]], [[https://openalex.org/A5039851699][Felix Ofori Boakye]], [[https://openalex.org/A5047096803][Mohammad Tabish]], [[https://openalex.org/A5005163120][Mohammed Mujahid Alam]], [[https://openalex.org/A5078102681][Abdullah G. Al‐Sehemi]], [[https://openalex.org/A5069924270][Wei Zhao]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301392 
     
Abstract During the past few years, single‐atom catalysts (SACs) have attracted considerable attention in electrolysis due to their outstanding catalytic performance and efficient atomic utilization. SACs exhibit a simple structure, high catalytic activity, consistent scaling relationships for single sites, and low metal content but their practical applications are still limited. Dual single‐atom catalysts (DACs), which feature excellent selectivity, high atomic utilization efficiency, and remarkable stability, are emerging as new frontiers in heterogeneous electrocatalysis. They increase catalytic activity by promoting synergistic effects between metal‐active sites. In this paper, we present a comprehensive overview of the latest developments in dual‐atom catalysts for oxygen evolution reaction (OER) and oxygen reduction reaction (ORR). In addition, we explore the differences between homonuclear and heteronuclear configurations, the emergence of single/dual‐site metal catalysts, and the methods currently used for their synthesis. Lastly, this review discusses several perspectives for advancing the development of dual‐atom catalysts for OER and ORR electrocatalysis.    

    

* Nanostructured Co3O4@NiFe-LDH Heterojunction Catalysts for Improving Oxygen Evolution Reaction in Alkaline Environment  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391787360
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173837")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391787360"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391787360"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391787360"))][Get cited by]]

OpenAlex: https://openalex.org/W4391787360 (Open access: False)
    
[[https://openalex.org/A5078500521][Zhehao Liu]], [[https://openalex.org/A5002785817][Hefeng Yuan]], [[https://openalex.org/A5063340075][Zihao Wan]], [[https://openalex.org/A5029556527][Zhanhong Ma]], [[https://openalex.org/A5009473442][Xiaoyang Deng]], [[https://openalex.org/A5014812749][Xiaoguang Wang]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.173837 
     
Constructing nano-heterojunction catalysts is a highly efficient method for enhancing the thermodynamics and kinetics towards oxygen evolution reaction. In the present study, NiFe-LDH nanoparticles in-situ grown on Co3O4 nanowires bring about abundant heterogeneous interfaces, which productively increase specific surface area and tune electron density distribution. The as-obtained composite comprises rich unsaturated Co sites on Co3O4 and hybrid crystalline/amorphous NiFe-LDH phase, both of which expedite the flow of charge and expose large amounts of active sites. The Co-Ni-Fe electron transport channels are established at the core-shell heterojunction with the transmission of electrons from Co3O4 to NiFe-LDH. The resultant optimal Co3O4@NiFe-LDH/NF-100 catalyst displayed attractive OER activity with low overpotential of 270 mV at 50 mA cm−2, along with excellent durability in alkaline media. This typical core-shell heterojunction promotes H2O dissociation and strengthens the adsorption of intermediates, thereby enhancing oxygen evolution reaction.    

    

* Photosynthetic live microorganism-incorporated hydrogels promote diabetic wound healing via self-powering and oxygen production  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391788147
:TOPICS: Molecular Mechanisms of Planarian Regeneration, Wound Healing and Regeneration, Low-Level Laser Therapy in Biomedical Applications
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149545")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391788147"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391788147"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391788147"))][Get cited by]]

OpenAlex: https://openalex.org/W4391788147 (Open access: False)
    
[[https://openalex.org/A5071867794][Yan Wu]], [[https://openalex.org/A5069530184][Meiyun Li]], [[https://openalex.org/A5008631547][Ruiying He]], [[https://openalex.org/A5032079976][Lan Xiao]], [[https://openalex.org/A5025588604][Sen Liu]], [[https://openalex.org/A5056539856][Kaiyuan Chen]], [[https://openalex.org/A5057688049][Huifen Qiang]], [[https://openalex.org/A5091502908][kim eun ji]], [[https://openalex.org/A5062992930][Luxin Li]], [[https://openalex.org/A5059728494][Yunfei Yin]], [[https://openalex.org/A5013594735][Xianglin Yuan]], [[https://openalex.org/A5087592842][Meng Li]], [[https://openalex.org/A5066565410][Jie Gao]], [[https://openalex.org/A5059317683][Yulin Li]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149545 
     
Electrical stimulation and oxygen are vital for promoting cell proliferation, migration, and differentiation to repair damaged tissues in chronic wound healing in patients with diabetes. The effective oxygen production by Chlorella has garnered attention in the medical field, but the potential of extracellular electron production in skin repair has not been explored. Inspired by this, we developed CHPS hydrogels, a composite of polyacrylamide and sodium alginate, with Chlorella loaded in a semi-interpenetrating network. This network is formed by crosslinking acrylamide initiated by free radicals, with alginate chains dispersed within the network. When applied to wounds, CHPS hydrogels effectively protect damaged tissue, provide mechanical support to Chlorella against external forces, and create an optimal artificial microenvironment to promote the proliferation of Chlorella. Our study demonstrated that CHPS hydrogels exhibit remarkable fracture elongation and adhesion properties and continuously produce oxygen and bioelectrical currents through photosynthesis. Furthermore, the sustained release of dissolved oxygen and bioelectricity by CHPS hydrogels significantly enhances cell proliferation, migration, and angiogenesis, leading to improved wound healing in diabetic mice. These findings provide compelling evidence for further exploration of CHPS hydrogels as a cost-effective, simple, and accessible strategy for enhancing the clinical treatment of chronic wounds in diabetic patients.    

    

* Ru-Mn Pair-Site Triggers Key Oxygen Intermediate for Enhanced Acidic Oxygen Evolution Reaction Kinetics  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391790841
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4725247")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391790841"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391790841"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391790841"))][Get cited by]]

OpenAlex: https://openalex.org/W4391790841 (Open access: False)
    
[[https://openalex.org/A5072859291][Faming Gao]], [[https://openalex.org/A5004956679][Y. Wang]], [[https://openalex.org/A5029483060][Kuo Wei]], [[https://openalex.org/A5027491967][Yanli Song]], [[https://openalex.org/A5027516712][Adekunle Adedapo Obisanya]], [[https://openalex.org/A5002233140][Heen Li]], [[https://openalex.org/A5049157372][Jing Wang]], [[https://openalex.org/A5043812309][Hongguan Li]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4725247 
     
Herein, variable valence states Mn was adopted to regulate Ru-NC, which serves as a model to reduce the localization of Ru 4d structure and stimulate facile charge transfer, achieving accelerated surface reconstruction to generate Ru‒O active ingredient with high active to acidic water oxidation. Doping Mn not only accelerate surface reconstruction, but also improves durability by eliminating Ru peroxidation due to Mn-buffered charge compensation. The enhancement of OER activity results from the Mn and O induced Ru spin states to change from intermediate spin to low spin, thereby weakening the interaction with *O intermediates, and promoting *OH adsorption，which benefits the initial step of OER.    

    

* Directed Electron Transport Induced Surface Reconstruction of 2d Nife-Ldh/Stanene Heterojunction Catalysts for Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391790924
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4725244")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391790924"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391790924"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391790924"))][Get cited by]]

OpenAlex: https://openalex.org/W4391790924 (Open access: False)
    
[[https://openalex.org/A5082624913][Ze Sheng Lu]], [[https://openalex.org/A5055054317][Jingkun Wang]], [[https://openalex.org/A5066863522][Pengfei Zhang]], [[https://openalex.org/A5039199589][Wenhao Guo]], [[https://openalex.org/A5024047234][Yongqing Shen]], [[https://openalex.org/A5024912302][Peizhi Liu]], [[https://openalex.org/A5016415747][Jianlong Ji]], [[https://openalex.org/A5061234819][Min Zhao]], [[https://openalex.org/A5011335839][Hao‐Jie Liang]], [[https://openalex.org/A5025306333][Junjie Guo]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4725244 
     
As promising non-noble candidates for oxygen evolution reaction (OER), NiFe-based layered double hydroxides (NiFe-LDH) has been proven to transform into its high-oxidation-state Ni/Fe oxyhydroxide, which act as the primary active sites. However, advancing the emergence of high-oxidation-state Ni/Fe oxyhydroxide during OER process currently remains a challenge. Herein, a novel 2D NiFe-LDH/stanene p-n junction catalyst is achieved by inserting stanene between NiFe LDH and Ni foam. Time-dependent Raman spectra and density functional theory calculations (DFT) confirm that stanene not only benefits for the construction of built-in electric field, but also serves as an electron absorber to induce a directed electron transport from Ni, Fe to Sn, which thus facilitates the surface reconstruction to form the catalytically active NiOOH. Consequently, an ultralow OER overpotential (230 mV) at 100 mA cm-2 is achieved, corresponding to a considerable decrease of 22.3 % and 42.1 % compared with the individual NiFe-LDH and stanene, respectively.    

    

* Inlaying CoP/Ni2P/Fe2P triple heterostructure in MOF-derived carbon nanobox for robust oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391795662
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131181")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391795662"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391795662"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391795662"))][Get cited by]]

OpenAlex: https://openalex.org/W4391795662 (Open access: False)
    
[[https://openalex.org/A5050921384][Cuiqing Zhang]], [[https://openalex.org/A5027353414][Zhiyuan Xing]], [[https://openalex.org/A5045101474][Peng Yi]], [[https://openalex.org/A5049341927][Hao Zhang]], [[https://openalex.org/A5082164874][Lei Zhang]], [[https://openalex.org/A5014575317][Zhang‐Hui Lu]], Fuel. 365(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131181 
     
Water electrolysis is a promising strategy for hydrogen production but the major hindrance lies in the inherently sluggish kinetics of the anodic oxygen evolution reaction (OER). Here, a potential OER catalyst with hollow nanostructure is designed and fabricated, which is composed of highly dispersed mixed metal phosphide (CoP/Ni2P/Fe2P) nanoparticles encapsulated in the mesoporous carbon nanoboxes (denoted as CoNiFeP@C NBs). Beneficial from abundant CoP/Ni2P/Fe2P interfaces in these nanoparticles, the electronic structure would be optimized and thus decrease the catalytic energy barrier. Furthermore, the porous hollow carbon layer can not only promote electron and mass transport but also expose more active sites and prevent aggregation of active CoNiFeP units. Owing to the structural and compositional advantages including the suitable electronic structure, promoted charge and mass transfer capability, and massive electrochemical catalytic active sites, the optimized CoNiFeP@C NBs exhibit excellent electrocatalytic performance towards OER. Typically, an overpotential of 260 mV is achieved for CoNiFeP@C NBs at 10 mA cm−2 with a low Tafel slope of 65.5 mV dec−1, which is among the top values of the reported Co-based OER electrocatalysts and even outperform commercial RuO2. Impressive stability is also realized in alkaline electrolyte due to the protective carbon layer. This work paves the way for developing advanced OER catalyst towards high catalytic capability and remarkable stability.    

    

* Optimizing binder for enhanced oxygen evolution and supercapacitance in a PCN-224 functionalized V2CTx composite  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391795749
:TOPICS: Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2024.110923")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391795749"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391795749"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391795749"))][Get cited by]]

OpenAlex: https://openalex.org/W4391795749 (Open access: False)
    
[[https://openalex.org/A5004587425][Ehtisham Umar]], [[https://openalex.org/A5009396077][Haseebul Hassan]], [[https://openalex.org/A5014807301][Muhammad Waqas Iqbal]], [[https://openalex.org/A5027132782][Afaf Alqorashi]], [[https://openalex.org/A5041634343][Badriah S. Almutairi]], [[https://openalex.org/A5084761641][Hussein Alrobei]], Journal of Energy Storage. 84(None)] 2024. https://doi.org/10.1016/j.est.2024.110923 
     
The synthesis of nanoscale porous coordination network (PCN-224 MOF) is intricate due to the difficulty in spatially influencing typical soluble metal salt chemicals, leading to the formation of bulk MOFs. This study presents the novel utilization of V2CTx as a metal precursor for the preparation of PCN-224 MOF nanostructures, with the ability to modulate the resulting nanostructure by adjusting the reaction temperature. The growth of PCN-224 provides the surface atoms with strong electronegative in V2CTx MXene and the availability of abundant accessible active sites for ligands. This study introduces a novel methodology for fabricating a composite material by integrating V2CTx MXene and PCN-224 MOF. The PCN-224/V2CTx supercapattery have 185.5C/g specific capacity (Qs) at 2 A/g and an electrode with 82 Wh/kg and 840 W/kg energy density (Ed) and power density (Pd). The electrode exhibited a coulombic efficiency and capacitive retention of 96 % and 82 % after undergoing 15,000 cycles. It has outstanding cyclic stability, maintaining 94 % of charge time and 97 % discharge time after 15,000 cycles. This study suggests using duplicate cell electrodes of PCN-224/V2CTx supercapattery in daily-use portable devices and oxygen evaluation reaction (OER) investigation. This is the first study to examine PCN-224/V2CTx electrochemical behavior and propose high-energy, high-rate electrochemical devices use it as an electrode.    

    

* Doubly-Enhanced Strategy to Construct a Highly Efficient Carbon-Based Bifunctional Catalyst to Oxygen Reduction and Oxygen Evolution Reactions for Rechargeable Zinc-Air Batteries  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391804875
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4726915")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391804875"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391804875"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391804875"))][Get cited by]]

OpenAlex: https://openalex.org/W4391804875 (Open access: False)
    
[[https://openalex.org/A5011788131][Tongwen Xu]], [[https://openalex.org/A5007962016][Jie Zhang]], [[https://openalex.org/A5076988030][Xiong Zhang]], [[https://openalex.org/A5046525078][Jingqi Sha]], [[https://openalex.org/A5014715855][Shijin Zhang]], [[https://openalex.org/A5018152814][Yang Mei]], [[https://openalex.org/A5041923029][Lei Ying]], [[https://openalex.org/A5011802849][Rong Jin]], [[https://openalex.org/A5086992948][Haifeng Chen]], [[https://openalex.org/A5057116148][Lingtao Sun]], [[https://openalex.org/A5073410815][Yujun Si]], [[https://openalex.org/A5020870418][Chaozhong Guo]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4726915 
     
Regulating the oxygen evolution reaction (OER) performance of N-doped carbon-based catalyst to oxygen reduction reaction (ORR) is of prospective to the wide-ranging applications of rechargeable zinc-air batteries. In this work, a facile double-enhancing strategy is proposed to prepared a bifunctional catalyst to ORR and OER. In the strategy, the smaller carbon particles were generated by carbonizing cyclodextrin. The fresh carbon material can react with the gaseous product of melamine to favor the anchoring of nitrogen to prepare the N-doped Fe-N-CD-C-A2 catalyst to ORR. Then an OER-enhanced bifunctional catalyst Fe-N-CD-C-A2-Ni was prepared by separately blending Ni2+ and OH- with Fe-N-CD-C-A2 to evenly load Ni(OH)2 particles as OER catalyst. Benefiting from the intentionally regulated properties, the Fe-N-CD-C-A2-Ni shows 0.8728 V of ORR half wave potential and 1.6868 V of OER potential at 10 mA cm-2, both being realized in a practical rechargeable zinc-air battery with 1.526 V of open circuit potential, 192 mW cm-2 of peak power density, 1.18-1.27 V of discharge voltage plateau and 957 mWh g-1 Zn of energy density. Importantly, the Fe-N-CD-C-A2-Ni exhibits superior rechargeability and durability during the discharge-recharge cycles, being very superior than those of Pt/C+RuO2 catalyst and revealing the promising prospect in the practical application.    

    

* Self-Supported Nifes2/Nife-Ldh Nanoflowers for High-Efficiency Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391809531
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4726604")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391809531"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391809531"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391809531"))][Get cited by]]

OpenAlex: https://openalex.org/W4391809531 (Open access: False)
    
[[https://openalex.org/A5042282225][Luyao Wang]], [[https://openalex.org/A5040647242][Lin Liu]], [[https://openalex.org/A5023044882][Hongxu Zhang]], [[https://openalex.org/A5020647265][Jian Yu]], [[https://openalex.org/A5009956168][Lijia Chen]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4726604 
     
Exploiting low-cost and efficient transition metal-based oxygen evolution catalysts is significant for water splitting. Herein, the composite catalyst (NiFeS2/NiFe-LDH) with the flower-like nanostructure was prepared on the surface of nickel-iron binary alloy. The sulfuretted catalyst displays larger Cdl (8.8 mF cm-2) and higher TOF (0.44 s-1). It also showed a low overpotential of 223 mV at 10 mA cm-2. In addition, it shows excellent stability at 10 mA cm-2 and 100 mA cm-2 for 10 h without a noticeable activity loss. The strategy of combining layered double hydroxides with transition bimetallic sulfides may provide important insights for the exploitation of low-cost and high-activity OER catalysts.    

    

* Strong Electron Interaction at the Amorphous/Crystalline Interface Enables Advanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391815529
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acssuschemeng.3c07189")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391815529"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391815529"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391815529"))][Get cited by]]

OpenAlex: https://openalex.org/W4391815529 (Open access: False)
    
[[https://openalex.org/A5028024246][Xingheng Zhang]], [[https://openalex.org/A5079056547][Xingwen Lin]], [[https://openalex.org/A5014503942][Shoufu Cao]], [[https://openalex.org/A5034654778][Xiao Chen]], [[https://openalex.org/A5020278538][Qi Hou]], [[https://openalex.org/A5002382898][Shuxian Wei]], [[https://openalex.org/A5055640195][Siyuan Liu]], [[https://openalex.org/A5058579111][Zhaojie Wang]], [[https://openalex.org/A5063818470][Fang Dai]], [[https://openalex.org/A5004933770][Xiaoqing Lu]], ACS Sustainable Chemistry & Engineering. None(None)] 2024. https://doi.org/10.1021/acssuschemeng.3c07189 
     
No abstract    

    

* 2D Ruthenium–Chromium Oxide with Rich Grain Boundaries Boosts Acidic Oxygen Evolution Reaction Kinetics  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391818792
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202311172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391818792"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391818792"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391818792"))][Get cited by]]

OpenAlex: https://openalex.org/W4391818792 (Open access: False)
    
[[https://openalex.org/A5040900980][Xuhao Zhao]], [[https://openalex.org/A5055517335][Zijian Li]], [[https://openalex.org/A5008892245][Haeseong Jang]], [[https://openalex.org/A5056691753][Xiaoqian Wei]], [[https://openalex.org/A5051580036][Liu Wang]], [[https://openalex.org/A5040569943][Min Kim]], [[https://openalex.org/A5037450342][Jaephil Cho]], [[https://openalex.org/A5091447700][Xien Liu]], [[https://openalex.org/A5065424751][Qing Qin]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202311172 
     
Abstract Ruthenium oxide is currently considered as the promising alternative to Ir‐based catalysts employed for proton exchange membrane water electrolyzers but still faces the bottlenecks of limited durability and slow kinetics. Herein, a 2D amorphous/crystalline heterophase ac‐Cr 0.53 Ru 0.47 O 2‐δ substitutional solid solution with pervasive grain boundaries (GBs) is developed to accelerate the kinetics of acidic oxygen evolution reaction (OER) and extend the long‐term stability simultaneously. The ac‐Cr 0.53 Ru 0.47 O 2‐δ shows a super stability with a slow degradation rate and a remarkable mass activity of 455 A g Ru −1 at 1.6 V vs RHE, which is ≈3.6‐ and 5.9‐fold higher than those of synthesized RuO 2 and commercial RuO 2 , respectively. The strong interaction of Cr–O–Ru local units in synergy with the specific 2D structural characteristics of ac‐Cr 0.53 Ru 0.47 O 2‐δ dominates its enhanced stability. Meanwhile, high‐density GBs and the shortened Ru‐O bonds tailored by amorphous/crystalline structure and Cr–O–Ru interaction regulate the adsorption and desorption rates of oxygen intermediates, thus accelerating the overall acidic OER kinetics.    

    

* Cobalt decorated S-doped carbon electrocatalyst assembly for enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391819159
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mtsust.2024.100717")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391819159"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391819159"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391819159"))][Get cited by]]

OpenAlex: https://openalex.org/W4391819159 (Open access: False)
    
[[https://openalex.org/A5050750294][Selvam Mathi]], [[https://openalex.org/A5057554515][Venkatachalam Ashok]], [[https://openalex.org/A5026460148][Abdullah Alodhayb]], [[https://openalex.org/A5001629698][Saravanan Pandiaraj]], [[https://openalex.org/A5090106395][Nagaraj P. Shetti]], Materials Today Sustainability. None(None)] 2024. https://doi.org/10.1016/j.mtsust.2024.100717 
     
The different ratios of CoII(OH)2 decorated on sulfur doped nano carbon soot (SDCN) nanoparticles were synthesized and described as Co2II@SDCN, Co4II@SDCN, Co6II@SDCN, and Co8II@SDCN nanoparticles electrocatalysts. The collaborative effect of SDCN and Co concentration boosted the electron conductivity and constancy of CoII@SDCN. SDCN significantly binds cobalt ions and inhibits aggregation. The Co8II@SDCN/GC reveals a very low potential of 361 mV at 10 mAcm−2 current density and its Tafel is lesser than that of IrO2 (54 mV dec−1). Co8II@SDCN/GC showed a computed turnover frequency of 0.0165 s−1, around 9 times more than IrO2 0.0016 s−1 at 1.60 V. The Co8II@SDCN/NF electrode catalyst also exhibits a remarkably low potential of 251 mV @10 mA cm−2. In an alkaline medium, this brand-new Co8II@SDCN/NF displays durability over a period of 250 h with only a 5.1% potential loss. Excellent oxygen evolution reaction (OER) performance and sufficient kinetics in the Co8II@SDCN catalyst allow it to address the slow rate of water oxidation. The solar-assisted water electrolysis demonstration at 1.54 V confirms the effectiveness of the newly developed electrocatalyst in the conversion of solar energy to hydrogen. These results demonstrate that Co8II@SDCN can be utilized to produce hydrogen on a big scale at the lowest possible cost.    

    

* Effect of ferroelectric polarization on oxygen evolution reaction: a theoretical study of MIrSn2S6 (M = Bi, Mn, and Sb)  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391819463
:TOPICS: Biohydrometallurgical Processes for Metal Extraction, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00152d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391819463"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391819463"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391819463"))][Get cited by]]

OpenAlex: https://openalex.org/W4391819463 (Open access: True)
    
[[https://openalex.org/A5052207106][Haoyun Bai]], [[https://openalex.org/A5012291309][Weng Fai Ip]], [[https://openalex.org/A5028960638][Weixu Feng]], [[https://openalex.org/A5068386911][Hui Pan]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d4ta00152d  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ta/d4ta00152d][pdf]])
     
The ferroelectric polarization plays important roles in catalytic reactions, but the mechanism is still under debate. In this work, 2D ferroelectric MIrSn2S6 is systematically investigated for revealing the effects of...    

    

* A Theoretical Study on the Enhanced Oxygen evolution Performance of NiN4-graphene by Ni Nanoclusters  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391824445
:TOPICS: Atomic Layer Deposition Technology, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6463/ad297c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391824445"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391824445"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391824445"))][Get cited by]]

OpenAlex: https://openalex.org/W4391824445 (Open access: False)
    
[[https://openalex.org/A5068559282][Runchuan Shi]], [[https://openalex.org/A5083733443][Shihao Feng]], [[https://openalex.org/A5013231137][Zhaoming Fu]], [[https://openalex.org/A5036331877][Zongxian Yang]], [[https://openalex.org/A5020899933][Xilin Zhang]], Journal of Physics D: Applied Physics. None(None)] 2024. https://doi.org/10.1088/1361-6463/ad297c 
     
Abstract Isolated metal-coordinated nitrogen embedded carbon (M-N-C) materials are potential alternatives to noble catalysts for oxygen evolution reaction (OER), and the activity of metal centers can be further modulated by adjusting the coordination environment. Recently, experimental studies have shown that the aggregation of metal atoms into small clusters or particles is inevitable during the high temperature pyrolysis, while the influences of metal clusters on the OER activity of single metal atoms in M-N-C are unclear. Herein, taking Ni-based single atom as examples, the interaction characters of NiN4 doped graphene (NiN4-graphene) with different Ni clusters were studied. The modulation effects of Ni clusters to the NiN4-graphene were systematically investigated from the geometric configurations, electronic structures, and the OER activity of the Ni single atom. It was found that the OER&#xD;performance of NiN4-graphene can be remarkably improved through the addition of Ni clusters, and the lowest overpotential of 0.43 V is achieved on NiN4-graphene with the modification of Ni13 cluster, which is smaller than that of 0.69 V on NiN4-graphene. Electronic properties calculations showed that the charge transfer from Ni clusters to NiN4-graphene will alter the density of states of Ni single atom near the Fermi level, which promotes the charge transfer from NiN4-graphene to oxygen containing products and optimizes the adsorption strength of oxygen intermediate to close to the ideal adsorption free energy of 2.46 eV by enhancing the hybridization interaction between the O-p orbitals and the Ni-dxz, Ni-dyz orbitals, and finally leading to an enhanced OER activity. The current findings highlight the important role of metal clusters on improving the catalytic performance of M-N-C materials, which benefits for the rational design of M-N-C catalysts with high catalytic activity.    

    

* Lowering the kinetic barrier via enhancing electrophilicity of surface oxygen to boost acidic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391825290
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matt.2024.01.025")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391825290"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391825290"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391825290"))][Get cited by]]

OpenAlex: https://openalex.org/W4391825290 (Open access: False)
    
[[https://openalex.org/A5079381089][Ning Han]], [[https://openalex.org/A5016622484][Xuan Zhang]], [[https://openalex.org/A5057252784][Chengkai Zhang]], [[https://openalex.org/A5003036585][Shihui Feng]], [[https://openalex.org/A5030671367][Wei Zhang]], [[https://openalex.org/A5038282552][Wei Guo]], [[https://openalex.org/A5034974804][Runtian Zheng]], [[https://openalex.org/A5027922091][Renji Zheng]], [[https://openalex.org/A5073531537][Pengyun Liu]], [[https://openalex.org/A5059462676][Yunwei Li]], [[https://openalex.org/A5003567873][Jan Fransaer]], [[https://openalex.org/A5022972481][Bao‐Lian Su]], Matter. None(None)] 2024. https://doi.org/10.1016/j.matt.2024.01.025 
     
The acidic oxygen evolution reaction (OER) is essential for many renewable energy conversion and storage technologies. However, the high energy required to break the strong covalent O-H bond of H2O in acidic media results in sluggish OER kinetics. Here, we report the critical role of iron in a new family of iron-containing yttrium ruthenate (Y2-xFexRu2O7-δ) electrocatalysts in highly increasing the electrophilicity of surface oxygen, leading to a significant reduction of the kinetics barrier by 33%, thus an exceptional OER mass activity of 1,021 A · g Ru − 1 up to 12.4 and 7.7 times that of Y2Ru2O7-δ and RuO2, respectively. Introducing iron reduces the Mulliken atomic charge on the O sites in the generated Ru-O-Fe structure, thereby facilitating the acid-base nucleophilic assault from H2O and reducing the free energy on the rate-determining step of OER. This work provides an effective strategy to reduce the kinetics barrier to achieve highly efficient and economic OER in acidic conditions.    

    

* NiMoSe/Ti3C2Tx MXene @ CC as a highly operative bifunctional electrocatalyst for hydrogen and oxygen evolution reactions in an alkaline medium  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391830822
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.100")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391830822"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391830822"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391830822"))][Get cited by]]

OpenAlex: https://openalex.org/W4391830822 (Open access: False)
    
[[https://openalex.org/A5005616367][Mohammad Saquib]], [[https://openalex.org/A5057849732][Nitish Srivastava]], [[https://openalex.org/A5029080204][Pratham Arora]], [[https://openalex.org/A5086137545][Amit C. Bhosale]], International Journal of Hydrogen Energy. 59(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.100 
     
Low-cost and highly efficient cathode and anode materials are required for proton exchange membrane and alkaline water electrolyzers. The present work demonstrates the development of a bifunctional cathode and anode material for hydrogen and oxygen evolution reactions (HER/OER) in an alkaline environment. The bimetallic Ni–Mo selenide is fabricated over the MXene (Ti3C2Tx) grown over the activated carbon fibers by an inexpensive, simple one-step and eco-friendly approach. The electrocatalyst NiMoSe/Ti3C2Tx@CC is developed via a hydrothermal method wherein NiMoSe is observed to grow highly dense nanoporous structure as confirmed by various characterization techniques. Highest activity for HER is observed using NiMoSe/Ti3C2Tx@CC with only overpotential of 203 mV at 10 mA cm−2 with low Tafel slope (45 mV dec−1). The catalyst is also proven to support OER activity with requirement of 320 mV as overpotential at 10 mA cm−2, thus better than commercial IrO2 (η10 = 380 mV). The Tafel slope obtained by NiMoSe/Ti3C2Tx@CC for OER is found to be minimum (189 mV dec−1) along with a very low charge transfer resistance (3.04 Ω) and high electrochemical surface area (0.0378 mF cm−2). The NiMoSe/Ti3C2Tx@CC is found to be highly stable for HER/OER with 1000 LSV cycles.    

    

* RuO2–CeO2 Lattice Matching Strategy Enables Robust Water Oxidation Electrocatalysis in Acidic Media via Two Distinct Oxygen Evolution Mechanisms  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391836369
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06182")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391836369"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391836369"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391836369"))][Get cited by]]

OpenAlex: https://openalex.org/W4391836369 (Open access: False)
    
[[https://openalex.org/A5010471250][Haoqiang Song]], [[https://openalex.org/A5053714754][Xue Yong]], [[https://openalex.org/A5044592235][Geoffrey I. N. Waterhouse]], [[https://openalex.org/A5000696036][Jingkun Yu]], [[https://openalex.org/A5015576369][Hao Wang]], [[https://openalex.org/A5052291064][Jinmeng Cai]], [[https://openalex.org/A5067430528][Zhiyong Tang]], [[https://openalex.org/A5000046177][Bai Yang]], [[https://openalex.org/A5071937806][Jiangwei Chang]], [[https://openalex.org/A5085836074][Siyu Lu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06182 
     
The discovery of acid-stable and highly active electrocatalysts for the oxygen evolution reaction (OER) is crucial in the quest for high-performance water-splitting technologies. Herein, a heterostructured RuO2–CeO2 electrocatalyst was constructed by using a lattice-matching strategy. The interfacial Ru–O–Ce bridge structure provided a channel for electron transfer between Ru and Ce, creating a lattice stress that distorts the local structure of RuO2. The resulting RuO2–CeO2 catalyst exhibited attractive stability with negligible decay after 1000 h of the OER in 0.5 M H2SO4, along with high activity with an overpotential of only 180 mV at 10 mA cm–2. In situ attenuated total reflectance surface-enhanced infrared absorption spectroscopy (ATR-SEIRAS), in situ differential electrochemical mass spectrometry (DEMS), and density functional theory (DFT) calculations were used to reveal that the interface and noninterface RuO2 sites enabled an oxide path mechanism (OPM) and the enhanced adsorbate evolution mechanism (AEM-plus), respectively, during the OER. The simultaneous and independent OER pathways accessible by lattice matching guides improved electrocatalyst design for the OER in acidic media.    

    

* Trapping of Intermediates of a Photocatalytic Oxygen Evolution Reaction in Overall Water Splitting  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391838821
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, DNA Nanotechnology and Bioanalytical Applications, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c03172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391838821"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391838821"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391838821"))][Get cited by]]

OpenAlex: https://openalex.org/W4391838821 (Open access: False)
    
[[https://openalex.org/A5089839552][Fumiaki Amano]], [[https://openalex.org/A5058928771][Satoshi Nakayama]], [[https://openalex.org/A5072383931][Sachihiro C. Suzuki]], [[https://openalex.org/A5043442763][Akira Yamakata]], [[https://openalex.org/A5001287498][Kosuke Beppu]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.3c03172 
     
Intermediates in the overall water splitting on particulate photocatalysts were investigated by electron paramagnetic resonance (EPR) measurements using 5,5-dimethyl-1-pyrroline N-oxide (DMPO) as a spin trap. In situ EPR spectra under ultraviolet light showed the exclusive formation of a hydroxyl radical adduct (•DMPO-OH) over Ga2O3 and NaTaO3:La without a Rh–Cr oxide cocatalyst. In contrast, the Rh–Cr oxide cocatalyst-loaded photocatalysts active for water splitting formed a 5,5-dimethyl-2-oxo-pyrroline-1-oxyl radical (•DMPOX). •DMPOX is suggested as an indicator of the surface peroxyl radical intermediate (M-OO•) in the oxygen evolution reaction pathway.    

    

* Author Correction: Iridium single atoms incorporated in Co3O4 efficiently catalyze the oxygen evolution in acidic conditions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391842906
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-45791-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391842906"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391842906"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391842906"))][Get cited by]]

OpenAlex: https://openalex.org/W4391842906 (Open access: True)
    
[[https://openalex.org/A5041252312][Yiming Zhu]], [[https://openalex.org/A5090915513][Jiaao Wang]], [[https://openalex.org/A5090441736][Toshinari Koketsu]], [[https://openalex.org/A5011934559][Matthias Kroschel]], [[https://openalex.org/A5000351218][Jin‐Ming Chen]], [[https://openalex.org/A5012833616][Su-Yang Hsu]], [[https://openalex.org/A5047676104][Graeme Henkelman]], [[https://openalex.org/A5049605727][Z. Hu]], [[https://openalex.org/A5034066582][Peter Strasser]], [[https://openalex.org/A5060759067][Jiwei Ma]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-45791-1  ([[https://www.nature.com/articles/s41467-024-45791-1.pdf][pdf]])
     
No abstract    

    

* Excellent Electrocatalytic Oxygen Evolution Reaction by Non-Noble Metal-Based 3D Perovskite Oxides Ba3–xSrxMTiSbO9 (x = 1, 1.5 for M = Co and x = 2 for Mn/Co)  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391845350
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c02750")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391845350"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391845350"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391845350"))][Get cited by]]

OpenAlex: https://openalex.org/W4391845350 (Open access: False)
    
[[https://openalex.org/A5084524229][Sujan Sen]], [[https://openalex.org/A5009194799][Megha Goyal]], [[https://openalex.org/A5078609691][Lalit Kumar]], [[https://openalex.org/A5050699362][Tapas Kumar Mandal]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.3c02750 
     
The large-scale production of green hydrogen from water electrolysis is hindered due to the higher overpotential required for oxygen evolution reaction (OER). While commercial use of noble metal oxide OER catalysts suffer from poor stability and cost ineffectiveness, the development of non-noble metal-based OER catalysts is still a challenge to overcome. The compositional and structural flexibility of 3D perovskite oxides presents a distinct opportunity to design electrocatalysts that can overcome the kinetic sluggishness of OER and address its associated limitations. Herein, we have designed and synthesized a series of 3D perovskite catalysts, Ba3–xSrxMTiSbO9 (x = 1, 1.5 for Co and x = 2 for Mn/Co), by the conventional solid-state method. The Co analogues exhibit exceptional OER performance when compared with the manganese counterpart and a similar or comparable overpotential at 10 mA/cm2 (η10) but with a significantly lower overpotential at 100 mA/cm2 (η100) as compared to RuO2, benchmark electrocatalysts for OER. The Co compounds have also shown superior kinetics as compared to RuO2. The charge-transfer resistance across interfaces measured by operando electrochemical impedance spectroscopy at different potentials follow the activity order of the compounds. The higher electrocatalytic activity of Ba3–xSrxCoTiSbO9 originates from higher d-electron counts, close to unity filling of the eg-orbital electrons, structural factor, μ/t (μ = perovskite B-cation to O2– radius ratio and t = tolerance factor), and higher lattice oxygen participation. A plausible mechanism is also provided based on the pH-dependent OER study. The Co perovskite with the highest lattice oxygen participation and lowest μ/t exhibited the highest OER activity and fastest kinetics. The study demonstrates a nonconventional tool of A-cation manipulation in synthesizing non-noble metal-based 3D perovskites as efficient OER electrocatalysts despite the elusive nature of their active sites.    

    

* Improved oxygen evolution reaction for high-current PEM water electrolysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391849833
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.checat.2023.100897")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391849833"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391849833"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391849833"))][Get cited by]]

OpenAlex: https://openalex.org/W4391849833 (Open access: False)
    
[[https://openalex.org/A5010788326][Guoyu Zhong]], [[https://openalex.org/A5055030458][Shurui Xu]], [[https://openalex.org/A5028065702][Baizeng Fang]], Chem Catalysis. 4(2)] 2024. https://doi.org/10.1016/j.checat.2023.100897 
     
Ru-based electrocatalysts have been extensively studied for the oxygen evolution reaction in proton exchange membrane water electrolysis, and the interactions between Ru atoms and their supports play a crucial role. In a recent issue of Nature Communications, Lv and co-workers reported that the enhanced metal-support interaction significantly improved the stability.    

    

* g-C3N4 /polymeric metallophthalocyanine as novel electrocatalysts for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391849942
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.131")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391849942"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391849942"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391849942"))][Get cited by]]

OpenAlex: https://openalex.org/W4391849942 (Open access: False)
    
[[https://openalex.org/A5004465494][Duygu Akyüz]], [[https://openalex.org/A5067659604][Ümit Demirbaş]], International Journal of Hydrogen Energy. None(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.131 
     
In this work, non-peripherally tetra 3-(4-(4-acetylpiperazin-1-yl)phenoxy) substituted nickel(II) phthalocyanine (NiPc), cobalt(II) phthalocyanine (CoPc), zinc(II) phthalocyanine (ZnPc), copper(II) phthalocyanine (CuPc) and lead(II) phthalocyanine (PbPc) were synthesized. The structural characterization of the novel compounds was performed by a combination of instrumental methods. The electrochemical and in-situ spectroelectrochemical responses of the compounds were recorded and redox properties were illuminated. Graphitic carbon nitride(g-C3N4) was synthesized by thermal decomposition of urea and combined with metallophthalocyanines to avoid agglomeration of phthalocyanine, to obtain homogeneous microstructured catalyst and to provide synergistic effects between pyridinic N-metal bonds of g-C3N4 and metallophthalocyanines (MPcs). The synthesized compounds were electropolymerized onto g-C3N4 thanks to piperazin substitute groups. The oxygen evolution reaction (OER) of g-C3N4/Poly-MPcs was investigated in alkaline electrolyte (1 M KOH). The g-C3N4/Poly-NiPc exhibited excellent electrocatalytic performance with low overpotential and Tafel slope, respectively, 380 mV@ 10 mA cm−2 and 80 mVdec−1, which is superior to the g-C3N4. Moreover, g-C3N4/Poly-NiPc electrocatalyst exhibited ∼100 times higher current density than g-C3N4.    

    

* Computational Study of Two-Dimensional SnGe2N4 as a Promising Photocatalyst for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391851935
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Accelerating Materials Innovation through Informatics, Two-Dimensional Transition Metal Carbides and Nitrides (MXenes)
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj00204k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391851935"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391851935"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391851935"))][Get cited by]]

OpenAlex: https://openalex.org/W4391851935 (Open access: False)
    
[[https://openalex.org/A5080124765][Noor ul Ain]], [[https://openalex.org/A5059888528][Arooba Kanwal]], [[https://openalex.org/A5065519247][Abdul Jalil]], [[https://openalex.org/A5001795469][Chang Fu Dee]], [[https://openalex.org/A5086336181][Tingkai Zhao]], [[https://openalex.org/A5019008123][Raza Ali Raza]], [[https://openalex.org/A5004475369][Ishaq Ahmad]], New Journal of Chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj00204k 
     
In the domain of photocatalysis, the oxygen evolution reaction (OER) serves as a crucial process in sustainable energy production. The development of efficient photocatalysts for OER is therefore highly desirable....    

    

* Fabrication and characterisation of CrMnFeCoNi high entropy alloy electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391906377
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, High-Entropy Alloys: Novel Designs and Properties
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apmt.2024.102128")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391906377"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391906377"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391906377"))][Get cited by]]

OpenAlex: https://openalex.org/W4391906377 (Open access: False)
    
[[https://openalex.org/A5017816629][Xun Cao]], Applied Materials Today. 37(None)] 2024. https://doi.org/10.1016/j.apmt.2024.102128 
     
Water electrolysis is attracting increasing attention in becoming the main method for green energy production, which has long been hindered by the sluggish kinetics of oxygen evolution reaction (OER) and high cost of noble-metal (NM) containing electrodes. Template replication technique has been employed to fabricate porous CrMnFeCoNi high entropy alloy (HEA) bulk foams with > 95 % porosity. High entropy led to the formation of a single-phase solid solution of transition metals in the as-fabricated porous HEA bulk foam, and the lattice distortion brings about the outstanding OER performance that is close to that of the RuO2 reference sample. Effective electrochemically active surface area and amount of exposed active sites are increased by grinding into nanoparticles, which produced superior OER performance with a near-record low overpotential of ∼ 245 mV to drive a current density of 10 mA/cm2, a low Tafel slope of 73.6 mV/dec, a double layer capacitance of 102.3 mF, and excellent long-term stability over 24 h. This work demonstrates a cost-effective way to fabricate NM-free HEA electrocatalyst with complex structure and excellent stability in OER, which could help in advancing the research for alkaline water electrolysis.    

    

* Hierarchical sea urchin‐like Fe‐doped heazlewoodite for high‐efficient oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391880837
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cphc.202300414")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391880837"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391880837"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391880837"))][Get cited by]]

OpenAlex: https://openalex.org/W4391880837 (Open access: False)
    
[[https://openalex.org/A5005113911][Ke Shang]], [[https://openalex.org/A5067782993][Junpo Guo]], [[https://openalex.org/A5090235347][Yingjun Ma]], [[https://openalex.org/A5055514273][H.K. Liu]], [[https://openalex.org/A5042956973][Xiaoling Zhang]], [[https://openalex.org/A5082207315][Huizhen Wang]], [[https://openalex.org/A5055588334][Jie Wang]], [[https://openalex.org/A5037738045][Zhenhua Yan]], ChemPhysChem. None(None)] 2024. https://doi.org/10.1002/cphc.202300414 
     
Electrochemical water‐splitting to produce hydrogen is potential to substitute the traditional industrial coal gasification, but the oxygen evolution kinetics at the anode remains sluggish. In this paper, sea urchin‐like Fe doped Ni3S2 catalyst growing on nickel foam (NF) substrate is constructed via a simple two‐step strategy, including surface iron activation and post sulfuration process. The NF‐Fe‐Ni3S2 obtains at temperature of 130 ℃ (NF‐Fe‐Ni3S2‐130) features nanoneedle‐like arrays which are vertically grown on the particles to form sea urchin‐like morphology, features high electrochemical surface area. As oxygen evolution catalyst, NF‐Fe‐Ni3S2‐130 exhibits excellent oxygen evolution activities, fast reaction kinetics, and superior reaction stability. The excellent OER performance of sea urchin‐like NF‐Fe‐Ni3S2‐130 is mainly ascribed to the high‐vertically dispersive of nanoneedles and the existing Fe dopants, which obviously improved the reaction kinetics and the intrinsic catalytic properties. The simple preparation strategy is conducive to establish high‐electrochemical‐interface catalysts, which shows great potential in renewable energy conversion.    

    

* Key Role of Subsurface Doping in Optimizing Active Sites of IrO2 for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391890840
:TOPICS: Catalytic Nanomaterials, Atomic Layer Deposition Technology, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cc00075g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391890840"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391890840"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391890840"))][Get cited by]]

OpenAlex: https://openalex.org/W4391890840 (Open access: False)
    
[[https://openalex.org/A5089250541][Xindi Han]], [[https://openalex.org/A5004836336][Lu-E Shi]], [[https://openalex.org/A5011090841][Hui Chen]], [[https://openalex.org/A5046104594][Xiaoxin Zou]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d4cc00075g 
     
The oxygen evolution reaction (OER) over a family of metal-doped rutile IrO2 catalysts is theoretically investigated by controlling the species and position of doping elements. The subsurface substitution doping is...    

    

* The Role of Reducibility vis-à-vis Oxygen Vacancies of doped Co3O4/CeO2 in Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391913283
:TOPICS: Catalytic Nanomaterials, Solid Oxide Fuel Cells, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dt00315b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391913283"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391913283"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391913283"))][Get cited by]]

OpenAlex: https://openalex.org/W4391913283 (Open access: True)
    
[[https://openalex.org/A5047126873][Saraswati Roy]], [[https://openalex.org/A5022592991][Preeti Dahiya]], [[https://openalex.org/A5050699362][Tapas Kumar Mandal]], [[https://openalex.org/A5068743211][Sounak Roy]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d4dt00315b 
     
Electrochemical water splitting, a highly promising and environmentally friendly technology for H2 fuel production, faces significant hurdles due to the sluggish kinetics of the oxygen evolution reaction. Co based oxide...    

    

* Transpassive Metal Dissolution vs. Oxygen Evolution Reaction: Implication for Alloy Stability and Electrocatalysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391921021
:TOPICS: Atom Probe Tomography Research
:PUBLICATION_DATE: 2024-02-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202317058")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391921021"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391921021"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391921021"))][Get cited by]]

OpenAlex: https://openalex.org/W4391921021 (Open access: False)
    
[[https://openalex.org/A5076601076][Annica Wetzel]], [[https://openalex.org/A5093888344][Daniel Morell]], [[https://openalex.org/A5017993519][Marcus von der Au]], [[https://openalex.org/A5038064548][Günther Wittstock]], [[https://openalex.org/A5072476528][Özlem Ozcan]], [[https://openalex.org/A5044822731][Julia Witt]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202317058 
     
Multi‐principal element alloys (MPEAs) are gaining interest in corrosion and electrocatalysis research due to their electrochemical stability across a broad pH range and the design flexibility they offer. Using the equimolar CrCoNi alloy, we observe significant metal dissolution in a corrosive electrolyte (0.1 M NaCl, pH 2) concurrently with the oxygen evolution reaction (OER) in the transpassive region despite the absence of hysteresis in polarization curves or other obvious corrosion indicators. We present a characterization scheme to delineate the contribution of OER and alloy dissolution, using scanning electrochemical microscopy (SECM) for OER‐onset detection, and quantitative chemical analysis with inductively coupled‐mass spectrometry (ICP‐MS) and ultraviolet visible light (UV‐Vis) spectroscopy to elucidate metal dissolution processes. In‐situ electrochemical atomic force microscopy (EC‐AFM) revealed that the transpassive metal dissolution on CrCoNi is dominated by intergranular corrosion. These results have significant implications for the stability of MPEAs in corrosion systems, emphasizing the necessity of analytically determining metal ions released from MPEA electrodes into the electrolyte when evaluating Faradaic efficiencies of OER catalysts. The release of transition metal ions not only reduces the Faradaic efficiency of electrolyzers but may also cause poisoning and degradation of membranes in electrochemical reactors.    

    

* Novel nanotubes based on methylene-bridged cycloparaphenyleneas as highly efficient catalysts for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391849061
:TOPICS: Electrocatalysis for Energy Conversion, Chemistry and Applications of Fullerenes, Role of Porphyrins and Phthalocyanines in Materials Chemistry
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.comptc.2024.114502")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391849061"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391849061"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391849061"))][Get cited by]]

OpenAlex: https://openalex.org/W4391849061 (Open access: False)
    
[[https://openalex.org/A5048555978][Hazem Abdelsalam]], [[https://openalex.org/A5057985504][Omar H. Abd‐Elkader]], [[https://openalex.org/A5050838220][Mohamed A. Saad]], [[https://openalex.org/A5048983493][Mahmoud A. S. Sakr]], [[https://openalex.org/A5047437279][Qinfang Zhang]], Computational and Theoretical Chemistry. None(None)] 2024. https://doi.org/10.1016/j.comptc.2024.114502 
     
Nanotubes constructed from methylene-bridged cycloparaphenyleneas (MCPPs) are investigated using density functional theory. The dynamical stability is indicated by the real vibrational frequencies of the infrared spectra. MCPPs are semiconductors with an energy gap of ∼ 2.9 eV that significantly decreases in the finite nanotubes. This decrease is a result of the interactive molecular orbitals that are localized at the pentagonal rings linking MCPPs. The UV-vis spectra show that transitions from the highest occupied and neighbor orbitals to the lowest unoccupied orbital dominate the primary absorption peaks. Oxygen evolution reaction shows that all the reaction intermediates, HO, O, and HOO are adsorbed by the pentagonal active sites. The considered nanotubes show good catalytic performance but the best performance is observed in the wider nanotubes with an overpotential of 0.10 V. This remarkably low overpotential in addition to the abundant active sites makes finite nanotubes from MCPPs exceptional catalysts for oxygen evolution.    

    

* Iridium-Based Perovskites as Efficient Oxygen Evolution Reaction Catalysts in Acid Media  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391895875
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-02-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaenm.3c00713")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391895875"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391895875"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391895875"))][Get cited by]]

OpenAlex: https://openalex.org/W4391895875 (Open access: False)
    
[[https://openalex.org/A5062340921][Hossein Fadaei]], [[https://openalex.org/A5050744084][Carl W. Brown]], [[https://openalex.org/A5060364670][Georges Houlachi]], [[https://openalex.org/A5029340956][Houshang Alamdari]], ACS Applied Engineering Materials. None(None)] 2024. https://doi.org/10.1021/acsaenm.3c00713 
     
No abstract    

    

* Rational development of PPy/CuWO4 nanostructure as competent electrocatalyst for oxygen evolution, and hydrogen evolution reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391867968
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.125")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391867968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391867968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391867968"))][Get cited by]]

OpenAlex: https://openalex.org/W4391867968 (Open access: False)
    
[[https://openalex.org/A5041700640][Nouf H. Alotaibi]], [[https://openalex.org/A5049370676][Sumaira Manzoor]], [[https://openalex.org/A5015215111][Shahroz Saleem]], [[https://openalex.org/A5062023379][S. Noor Mohammad]], [[https://openalex.org/A5062281954][Mazhar Khalil]], [[https://openalex.org/A5090663793][Şenay Yalçın]], [[https://openalex.org/A5052155429][Abdul Ghafoor Abid]], [[https://openalex.org/A5049328863][Suleyman I. Allakhverdiev]], International Journal of Hydrogen Energy. 59(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.125 
     
Hydrogen has recently attracted a lot of attention as a clean as well as sustainable energy source. However, the vast bulk of industrial hydrogen is produced by converting natural gas into hydrogen. One of the primary goals of large-scale electrolysis is to find efficient, cost-effective, stable, and many other catalysts capable of producing hydrogen from water with minimal electrical bias. Using readily available electrocatalysts on Earth to facilitate the oxidation of water is one way to get closer to an effective method of splitting water to produce hydrogen. Here in the present work, CuWO4 was coated on the conducting polypyrrole (PPy) polymer via hydrothermal techniques to boost its catalytic performance. The fabricated PPy/CuWO4 composite is then utilized for water splitting to yield hydrogen in addition to oxygen. The PPy is able to raise the CuWO4 Fermi levels are separated, as a result, the PPy/CuWO4 produced a large number of strong and readily accessible charges, which led to the splitting of water into hydrogen, and demonstrated that at a potential of 1.470 V vs. RHE, the current density intended for CuWO4-3/PPY reached 10 mAcm−2, attaining an overpotential of 197 mV, with a Tafel plot slope of about 34.4 mVdec−1, and also with a charge transfer resistance of 2.3Ω for OER. Furthermore, the HER activity also attained lower overpotential (250 mV), with a Tafel slope of 50 mV dec−1 in order to reach a 10 mAcm−2 current density. In addition, the CuWO4 is completely encased by the PPy, facilitating charge transfer, allowing the particles to travel rapidly to the polymer's surface. Hence, this study demonstrates that the highly effective CuWO4-3/PPy nanocomposite is responsible for future energy-related applications.    

    

* Development of an ultra-thin electrode for the oxygen evolution reaction in proton exchange membrane water electrolyzers  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391849959
:TOPICS: Electrocatalysis for Energy Conversion, Hydrogen Energy Systems and Technologies, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.renene.2024.120159")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391849959"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391849959"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391849959"))][Get cited by]]

OpenAlex: https://openalex.org/W4391849959 (Open access: False)
    
[[https://openalex.org/A5079901404][Zhenye Kang]], [[https://openalex.org/A5068791597][Gaoqiang Yang]], [[https://openalex.org/A5022627494][Jinjun Mo]], Renewable Energy. None(None)] 2024. https://doi.org/10.1016/j.renene.2024.120159 
     
Noble metal electrocatalysts are highly preferred for the oxygen evolution reaction (OER) in a proton exchange membrane water electrolysis cell (PEMWE) due to their exceptional catalytic activity and stability. This study proposes a novel thin electrode (NTE) design to enhance the performance of noble metal electrocatalysts for the OER in PEMWE. The NTE utilizes a thin porous transport layer for the direct deposition of Iridium (Ir). Unlike conventional gas diffusion electrodes with deep porous structures that underutilize the catalyst due to limited triple-phase boundary conditions, the flat NTEs with straight-through pores overcome this restriction. The paper compares two deposition methods, electroplating and sputter coating. The in-situ electrochemical properties of NTEs with varying Ir loadings (0.06–1.01 mg cm−2) are investigated. The electroplated NTE demonstrates excellent mass activity, achieving 5.05 A mg−1 at 1.6 V and 80 °C. The NTE exhibits a simple fabrication process and low cost while significantly improving catalyst mass activity. Additionally, the NTE reduces electrode thickness from hundreds of micrometers to only 25 μm. This concept holds great promise for the future advancement of compact and high-efficiency PEMWE electrodes, resulting in reduced cost, volume, and mass of both the electrode itself and the overall system.    

    

* Single Transition‐Metal Atom Anchored on a Rhenium Disulfide Monolayer: An Efficient Bifunctional Electrocatalyst for the Oxygen Evolution and Oxygen Reduction Reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391880793
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202308416")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391880793"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391880793"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391880793"))][Get cited by]]

OpenAlex: https://openalex.org/W4391880793 (Open access: False)
    
[[https://openalex.org/A5004910340][Meiling Pan]], [[https://openalex.org/A5059121164][X. Cui]], [[https://openalex.org/A5024066427][Qun Jing]], [[https://openalex.org/A5029207520][Haiming Duan]], [[https://openalex.org/A5082278504][Fangping Ouyang]], [[https://openalex.org/A5034965764][Rong Wu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202308416 
     
Abstract Developing efficient oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) bifunctional electrocatalysts is attractive for rechargeable metal–air batteries. Meanwhile, single metal atoms embedded in 2D layered transition metal chalcogenides (TMDs) have become a very promising catalyst. Recently, many attentions have been paid to the 2D ReS 2 electrocatalyst due to its unique distorted octahedral 1T’ crystal structure and thickness‐independent electronic properties. Here, the catalytic activity of different transition metal (TM) atoms embedded in ReS 2 using the density functional theory is investigated. The results indicate that TM@ReS 2 exhibits outstanding thermal stability, good electrical conductivity, and electron transfer for electrochemical reactions. And the Ir@ReS 2 and Pd@ReS 2 can be used as OER/ORR bifunctional electrocatalysts with a lower overpotential for OER (η OER ) of 0.44 V and overpotentials for ORR (η ORR ) of 0.26 V and 0.27 V, respectively. The excellent catalytic activity is attributed to the optimal adsorption strength for oxygen intermediates coming from the effective modulation of the electronic structure of ReS 2 after Ir/Pd doping. The results can help to deeply understand the catalytic activity of TM@ReS 2 and develop novel and highly efficient OER/ORR electrocatalysts.    

    
