#+TITLE: water splitting
Description: water splitting papers
Created on Fri Aug  2 01:11:00 2024

Found 42 results from 2024-07-26 to 2024-08-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Improving the Electrocatalytic Activity of Cobalt Oxide with Bismuth for Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400970409
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta02845g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400970409"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400970409"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400970409"))][Get cited by]]

OpenAlex: https://openalex.org/W4400970409 (Open access: True)
    
[[https://openalex.org/A5004226797][Tewodros Asefa]], [[https://openalex.org/A5067036957][Belvin Thomas]], [[https://openalex.org/A5105063958][Bowen Peng]], [[https://openalex.org/A5013032351][Xiaoxi Huang]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta02845g 
     
Highly durable, low-cost electrocatalysts for acidic oxygen evolution reaction (OER) are very essential for the commercial success of proton exchange membrane-based water electrolysis. The catalysts currently available for this reaction...    

    

* Ru Single-Atom Nanoarchitectonics on Co-Based Conducting Metal–Organic Frameworks for Enhanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400971488
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c02804")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400971488"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400971488"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400971488"))][Get cited by]]

OpenAlex: https://openalex.org/W4400971488 (Open access: False)
    
[[https://openalex.org/A5105048618][Ruyu Xue]], [[https://openalex.org/A5101660914][Zhe Chuan Feng]], [[https://openalex.org/A5101818527][Yantao Wang]], [[https://openalex.org/A5002884743][Junfeng Huang]], [[https://openalex.org/A5101473086][Wei Dou]], [[https://openalex.org/A5018390453][Cailing Xu]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c02804 
     
The development of oxygen evolution reaction (OER) electrocatalysts is essential for the production of green hydrogen from water electrolysis, but it is challenging. Herein, ruthenium (Ru) single-atom-modified Co-HHTP (HHTP = 2,3,6,7,10,11-hexahydroxytriphenylene) (Ru@Co-HHTP) was prepared via a solvothermal and ion exchange method. Systematic experiments highlight that the atomically dispersed Ru can optimize the electronic structure and electronic conductivity of Co-HHTP. As a result, the obtained Ru@Co-HHTP shows a low overpotential of 247 mV at 100 mA cm    

    

* Structural Regulation of NiFe LDH under Spontaneous Corrosion to Enhance the Oxygen Evolution Properties  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400977781
:TOPICS: Corrosion Inhibitors and Protection Mechanisms
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202400640")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400977781"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400977781"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400977781"))][Get cited by]]

OpenAlex: https://openalex.org/W4400977781 (Open access: False)
    
[[https://openalex.org/A5090235347][Yingjun Ma]], [[https://openalex.org/A5104128049][Hangning Liu]], [[https://openalex.org/A5062220756][Lin Wang]], [[https://openalex.org/A5035825835][Changhui Sun]], [[https://openalex.org/A5100683018][Liangyu Gong]], [[https://openalex.org/A5100440149][Jie Wang]], [[https://openalex.org/A5009593753][Jiangmin Jiang]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202400640 
     
Electrochemical water splitting holds promise for sustainable hydrogen production but restricted by the sluggish reaction kinetics at the anodic oxygen evolution. Herein, we present a room-temperature spontaneous corrosion strategy to convert inexpensive iron (Fe) on iron foam substrates into highly active and stable self-supporting nickel iron layered hydroxide (NiFe LDH) catalysts. The corrosion evolution mechanisms are elucidated combining ex-situ scanning electron microscopy (SEM) and X-ray photo electron spectroscopy (XPS) techniques, demonstrating precise control over the concentration of Ni2+ and reaction time to achieve controllable micro-structures of NiFe LDH. Taking advantage of the self-supporting morphology and hierarchical micro-/nano- structure, the NiFe LDH with optimized Ni2+ concentration and reaction time exhibits significant small overpotentials of 160 mV and 200 mV for the OER at current densities of 10 mA cm-2 and 100 mA cm-2 respectively, showcasing excellent OER activities. Furthermore, this catalyst demonstrates superior reaction kinetics, high electrochemical stability, and excellent integral water splitting performance when coupled with a commercial Pt/C cathode. The energy-efficient, cost-effective, and scalable spontaneous corrosion strategy opens new avenues for the development of high-electrochemical-interface catalysts.    

    

* Manipulating Dual-Metal Catalytic Activities toward Organic Upgrading in Upcycling Plastic Wastes with Inhibited Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400978536
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.4c04219")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400978536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400978536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400978536"))][Get cited by]]

OpenAlex: https://openalex.org/W4400978536 (Open access: False)
    
[[https://openalex.org/A5087202662][Dengke Xiong]], [[https://openalex.org/A5100944630][Xiaoyang He]], [[https://openalex.org/A5103160714][Xuan Liu]], [[https://openalex.org/A5101999480][Kaiyan Zhang]], [[https://openalex.org/A5054193824][Zhentao Tu]], [[https://openalex.org/A5100737528][Jianying Wang]], [[https://openalex.org/A5100673667][Shi‐Gang Sun]], [[https://openalex.org/A5076251832][Zuofeng Chen]], ACS Nano. None(None)] 2024. https://doi.org/10.1021/acsnano.4c04219 
     
Electrorefinery of polybutylene terephthalate (PBT) waste plastic, specifically conversion of a PBT-derived 1,4-butanediol (BDO) monomer into value-added succinate coupled with H    

    

* High performance oxygen reduction and evolution reactions by graphitization of nickel –cobalt framework system  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400981045
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.309")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400981045"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400981045"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400981045"))][Get cited by]]

OpenAlex: https://openalex.org/W4400981045 (Open access: False)
    
[[https://openalex.org/A5061786851][Karim Kakaei]], [[https://openalex.org/A5069772071][A. Rahmati]], [[https://openalex.org/A5105065171][Mohammad Ghadiri]], [[https://openalex.org/A5105065172][Fatemeh Asgharnezhad]], International Journal of Hydrogen Energy. 81(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.309 
     
No abstract    

    

* Copper dopants facilitated generation of high-valent cobalt sites for improved oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400982018
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4qi01507j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400982018"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400982018"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400982018"))][Get cited by]]

OpenAlex: https://openalex.org/W4400982018 (Open access: False)
    
[[https://openalex.org/A5072916605][Jingrui Han]], [[https://openalex.org/A5009913485][Jieshu Zhou]], [[https://openalex.org/A5100397032][Hao Zhang]], [[https://openalex.org/A5100408823][Haibin Wang]], [[https://openalex.org/A5071442579][Kangning Liu]], [[https://openalex.org/A5029872654][Xuhui Sun]], [[https://openalex.org/A5100359387][Lihua Liu]], [[https://openalex.org/A5077003796][Hongyan Liang]], Inorganic Chemistry Frontiers. None(None)] 2024. https://doi.org/10.1039/d4qi01507j 
     
Developing a reliable strategy to adjust dynamic reconstruction and formation of active oxygen species on electrocatalyst surfaces is crucial for enhancing OER performance and still needs further elaborate elucidation. Here,...    

    

* In-situ evolution of bulk-active γ-CoOOH with immobilized Gd dopants enabling an efficient oxygen evolution electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400986166
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nr01743a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400986166"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400986166"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400986166"))][Get cited by]]

OpenAlex: https://openalex.org/W4400986166 (Open access: True)
    
[[https://openalex.org/A5073349735][Tianjue Hou]], [[https://openalex.org/A5036312417][Ruotao Yang]], [[https://openalex.org/A5058016226][Jiaxin Xu]], [[https://openalex.org/A5056970641][Xiaodie He]], [[https://openalex.org/A5101804437][Hongyuan Yang]], [[https://openalex.org/A5009720807][Prashanth W. Menezes]], [[https://openalex.org/A5029864603][Ziliang Chen]], Nanoscale. None(None)] 2024. https://doi.org/10.1039/d4nr01743a 
     
Promoting the in-situ reconstruction of transition metal (TM)-based precatalysts into low-crystalline and well-modified TM (oxy)hydroxides (TMOxHy) during alkaline oxygen evolution reaction (OER) is crucial for enhancing their catalytic performances. In...    

    

* Surface oxygen engineered ZnCo2O4 planar hybrid supercapacitor electrode for high energy applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400986943
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2024.112954")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400986943"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400986943"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400986943"))][Get cited by]]

OpenAlex: https://openalex.org/W4400986943 (Open access: False)
    
[[https://openalex.org/A5031660043][Muthukumar Ganesan]], [[https://openalex.org/A5009991260][Srinivasan Alagar]], [[https://openalex.org/A5049532172][Vivek Bagchi]], [[https://openalex.org/A5060879980][Shakkthivel Piraman]], Journal of Energy Storage. 98(None)] 2024. https://doi.org/10.1016/j.est.2024.112954 
     
No abstract    

    

* Iron doping enhances ZIF-67 based hierarchical carbon bifunction catalyst for oxygen reduction and evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400986969
:TOPICS: Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2024.113004")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400986969"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400986969"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400986969"))][Get cited by]]

OpenAlex: https://openalex.org/W4400986969 (Open access: False)
    
[[https://openalex.org/A5012686674][Kanjun Sun]], [[https://openalex.org/A5102222625][Xiaofei Lei]], [[https://openalex.org/A5087315070][Xuan Xie]], [[https://openalex.org/A5100431492][Wenjuan Li]], [[https://openalex.org/A5012205983][Wenbo Hou]], [[https://openalex.org/A5032007926][Hui Peng]], [[https://openalex.org/A5101063054][Guofu Ma]], Journal of Energy Storage. 98(None)] 2024. https://doi.org/10.1016/j.est.2024.113004 
     
No abstract    

    

* Built-in electric field construction and lattice oxygen activation for boosting alkaline electrochemical water/seawater oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401002555
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.154279")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401002555"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401002555"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401002555"))][Get cited by]]

OpenAlex: https://openalex.org/W4401002555 (Open access: False)
    
[[https://openalex.org/A5100352811][Xinyu Wang]], [[https://openalex.org/A5100606297][Xu Yu]], [[https://openalex.org/A5045338445][Pinyi He]], [[https://openalex.org/A5067123324][Guohui Yang]], [[https://openalex.org/A5011704577][Fu Qin]], [[https://openalex.org/A5088442952][Yongkang Yao]], [[https://openalex.org/A5031277854][Lili Ren]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.154279 
     
No abstract    

    

* Engineering Ru‐Au‐Mn Trimetallic Nanostructure for High‐Performance Acidic Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401006709
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400751")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401006709"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401006709"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401006709"))][Get cited by]]

OpenAlex: https://openalex.org/W4401006709 (Open access: False)
    
[[https://openalex.org/A5003384545][Minna Cao]], [[https://openalex.org/A5091896736][Yuhang Zhang]], [[https://openalex.org/A5085467179][Shuai Yue]], [[https://openalex.org/A5078414235][Jun Liang]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400751 
     
Developing highly efficient and stable electrocatalysts in acidic media is essential for proton exchange membrane water electrolyzers (PEMWEs). Especially for oxygen evolution reaction (OER), high overpotential is needed to overcome the high thermodynamic energy barrier of water splitting. Herein, we report a high‐efficiency self‐supported ternary alloy OER catalyst with high activity and good durability in acidic electrolytes by a simple electrodeposition method. The as‐prepared electrocatalyst consists of Ru, Au, and Mn alloy which is deposited on the carbon fiber paper (denoted as RuAuMn‐CFP). The RuAuMn‐CFP exhibits superior activity and only requires an overpotential of 131 mV at 10 mA cm−2 and outstanding stability of 30 h (10 mA cm−2) in acidic media, which outperforms the commercial Ru/C and Ir/C catalysts. Besides, at an overpotential of 140 mV, the RuAuMn‐CFP catalyst exhibited a remarkable mass activity of 29.63 mA/mg for OER. It is 7.9 times and 23.8 times higher than the commercial Ru/C and Ir/C catalysts (3.73 mA/mg, 1.24 mA/mg, respectively).    

    

* MOF˗derived sulfur˗doped iron˗nickel bimetallic phosphide nanowires: A bifunctional electrode for hydrogen and oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401011361
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.332")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401011361"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401011361"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401011361"))][Get cited by]]

OpenAlex: https://openalex.org/W4401011361 (Open access: False)
    
[[https://openalex.org/A5045088146][Munisamy Maniyazagan]], [[https://openalex.org/A5052345549][Esakkimuthu Shanmugasundaram]], [[https://openalex.org/A5014572856][Naveenkumar Perumal]], [[https://openalex.org/A5000231631][Hyeon-Woo Yang]], [[https://openalex.org/A5070528992][Nayoung Kang]], [[https://openalex.org/A5007736462][Woo Seung Kang]], [[https://openalex.org/A5001931238][Stalin Thambusamy]], [[https://openalex.org/A5081421570][Sun-Jae Kim]], International Journal of Hydrogen Energy. 81(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.332 
     
No abstract    

    

* Hexavalent iridium boosts oxygen evolution performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401014289
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.greenca.2024.07.003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401014289"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401014289"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401014289"))][Get cited by]]

OpenAlex: https://openalex.org/W4401014289 (Open access: True)
    
[[https://openalex.org/A5099843342][Mengtian Huo]], [[https://openalex.org/A5034644483][Y. T. Liang]], [[https://openalex.org/A5105099433][Kaichi Qin]], [[https://openalex.org/A5086300086][Guanzhi Wang]], [[https://openalex.org/A5078288522][Zihao Xing]], [[https://openalex.org/A5050931062][Jinfa Chang]], Green Carbon. None(None)] 2024. https://doi.org/10.1016/j.greenca.2024.07.003 
     
No abstract    

    

* Titanium Dioxide Induced Nickel-iron Alloy-based Precatalyst towards Efficient and Durable Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401025947
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.175729")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401025947"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401025947"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401025947"))][Get cited by]]

OpenAlex: https://openalex.org/W4401025947 (Open access: False)
    
[[https://openalex.org/A5102312625][Ran Qiao]], [[https://openalex.org/A5100324026][Kai Zhang]], [[https://openalex.org/A5008202465][Shuaichong Wei]], [[https://openalex.org/A5101388310][Hongtao Bai]], [[https://openalex.org/A5100773482][Xiangchao Meng]], [[https://openalex.org/A5046850864][Jingde Li]], [[https://openalex.org/A5100741974][Guihua Liu]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.175729 
     
No abstract    

    

* Quantifying Stern Layer Water Alignment Prior to and During the Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401026900
:TOPICS: Quantum Coherence in Photosynthesis and Aqueous Systems, Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2023-m9d1z-v4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401026900"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401026900"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401026900"))][Get cited by]]

OpenAlex: https://openalex.org/W4401026900 (Open access: True)
    
[[https://openalex.org/A5085342735][Raiden Speelman]], [[https://openalex.org/A5054512446][Franz M. Geiger]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2023-m9d1z-v4  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/66a28abd5101a2ffa809f6ed/original/quantifying-stern-layer-water-alignment-prior-to-and-during-the-oxygen-evolution.pdf][pdf]])
     
While water's oxygen is the electron source in the industrially important oxygen evolution reaction, the strong absorber problem clouds our view of how the Stern layer water molecules orient themselves in response to applied potentials. Here, we report nonlinear optical measurements on nickel electrodes held at pH 13 indicating a disorder-to-order transition in the Stern layer water molecules prior to the onset of Faradaic current. A full water monolater (1.1 x 10^15 cm-2) aligns with oxygen atoms pointing towards the electrode at +0.8 V and the associated work is 80 kJ mol-1. Our experiments identify water flipping energetics as a target for understanding overpotentials, advance molecular electrochemistry, provide benchmarks for electrical double layer models, and serve as a diagnostic tool for understanding electrocatalysis.    

    

* Minimal Doping Approach to Activate Lattice Oxygen Participation in K2WO4 Electrocatalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401027067
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124423")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027067"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027067"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027067"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027067 (Open access: False)
    
[[https://openalex.org/A5020359856][Selvaraj Seenivasan]], [[https://openalex.org/A5017820325][M. H. Kim]], [[https://openalex.org/A5033014275][Jeong Woo Han]], [[https://openalex.org/A5078799389][Do‐Heyoung Kim]], Applied Catalysis B Environment and Energy. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124423 
     
No abstract    

    

* Oxygen-deficient annealing boosts performance of CoNiFe oxide electrocatalyst in oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401032956
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcat.2024.115675")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401032956"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401032956"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401032956"))][Get cited by]]

OpenAlex: https://openalex.org/W4401032956 (Open access: False)
    
[[https://openalex.org/A5000842558][Thi-Thu-Hien Pham]], [[https://openalex.org/A5066261986][Michaela Plevová]], [[https://openalex.org/A5059009629][Stephan Bartling]], [[https://openalex.org/A5067238534][Nils Rockstroh]], [[https://openalex.org/A5032019000][Armin Springer]], [[https://openalex.org/A5004773873][Adam Slabon]], [[https://openalex.org/A5064651777][Jaromír Hnát]], [[https://openalex.org/A5055688484][Annette‐Enrica Surkus]], [[https://openalex.org/A5062902347][Robert Francke]], Journal of Catalysis. None(None)] 2024. https://doi.org/10.1016/j.jcat.2024.115675 
     
No abstract    

    

* Cation-Triggered Growth of Nanowires for Enhanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401034705
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c02315")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401034705"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401034705"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401034705"))][Get cited by]]

OpenAlex: https://openalex.org/W4401034705 (Open access: False)
    
[[https://openalex.org/A5100371313][Sheng Wang]], [[https://openalex.org/A5044457554][Weiying Ye]], [[https://openalex.org/A5100723123][Zhilin Zhang]], [[https://openalex.org/A5004335358][Yuan‐Zhao Hua]], [[https://openalex.org/A5050826407][Chenyang Cai]], [[https://openalex.org/A5100714826][Zhenghao Zhang]], [[https://openalex.org/A5060906248][Yitian Wu]], [[https://openalex.org/A5100342686][Kui Wang]], [[https://openalex.org/A5103565409][Wenshu Yang]], [[https://openalex.org/A5041067396][Weidong Shi]], [[https://openalex.org/A5038699851][Jinhui Hao]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c02315 
     
The oxygen evolution reaction (OER), which occurs in a variety of energy-related devices, necessitates optimization of the reaction pathways for efficient and scalable deployment. Nevertheless, fully harnessing the advanced structure of synthetic electrocatalysts remains a significant challenge due to the inevitable surface reconstruction process during OER. Here we present an efficient and flexible method to control the surface reconstruction process by engineering an electrolyte containing trace Co    

    

* Core–Shell Co‐CoxP Nanoparticle‐Embedded N‐Doped Carbon Nanowhiskers Hollow Sphere for Efficient Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401035151
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202409390")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401035151"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401035151"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401035151"))][Get cited by]]

OpenAlex: https://openalex.org/W4401035151 (Open access: False)
    
[[https://openalex.org/A5068308955][Wei Zhu]], [[https://openalex.org/A5100727143][Wenhui Hu]], [[https://openalex.org/A5012915643][Ying Wei]], [[https://openalex.org/A5066988739][Yongcai Zhang]], [[https://openalex.org/A5019781253][Kunming Pan]], [[https://openalex.org/A5101844277][Songtao Zhang]], [[https://openalex.org/A5090645667][Xinxin Hang]], [[https://openalex.org/A5089682316][Mingbo Zheng]], [[https://openalex.org/A5100629513][Huan Pang]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202409390 
     
Abstract The development of efficient oxygen evolution reaction (OER) electrocatalysts is critical to overcome the efficiency bottleneck in hydrogen generation via water electrolysis. Hollow nanostructured materials have emerged as a hot topic for electrocatalysis research because of their advantages, including abundant active sites, a large contact area between the catalyst and the electrolyte, and a short transmission path. As highly efficient and stable OER electrocatalysts, cobalt‐based nanostructured materials have attracted more and more attention. In this work, cobalt metal/cobalt phosphides/nitrogen‐doped carbon composites (Co‐Co x P/NC) with a hierarchical hollow structure are designed by using hollow ZIF‐67 microspheres as precursors. By coating ZIF‐8 on the surface of hollow ZIF‐67 microspheres and further carbonizing, carbon nanowhiskers are successfully formed on the surface of hollow carbon spheres under the catalytic effect of Co nanoparticles at a high temperature. In the subsequent phosphating process, solid Co nanocrystalline particles are transformed into core–shell CoP and Co 2 P nanoparticles on account of the Kirkendall effect. Through the optimization of the microstructure of the material and the synergistic effect of transition metal, transition metal phosphide, and nitrogen doping, the overpotential of the optimal material is only 287 mV at 10 mA cm −2 current density in 1 m KOH.    

    

* Effect of Different N/C Coordination Electronic Structures on the Activity of Bifunctional Rare-Earth Ytterbium Electrocatalysts for Oxygen Electrodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401035209
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.langmuir.4c01797")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401035209"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401035209"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401035209"))][Get cited by]]

OpenAlex: https://openalex.org/W4401035209 (Open access: False)
    
[[https://openalex.org/A5102549730][Tao Xu]], [[https://openalex.org/A5102849871][Daomiao Wang]], [[https://openalex.org/A5087429872][Qiming Fu]], [[https://openalex.org/A5044538497][Chao Liu]], Langmuir. None(None)] 2024. https://doi.org/10.1021/acs.langmuir.4c01797 
     
The research and development of bifunctional electrocatalysts for the oxygen electrode is of great significance to solve the problem of electrochemical energy. Herein, the effect of different structure-activity relationships on the performance of YbN    

    

* FeNi‐LDH COATED WITH ORANGE‐PEEL CARBON AEROGEL FOR OXYGEN EVOLUTION REACTION  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401038504
:TOPICS: Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401276")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401038504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401038504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401038504"))][Get cited by]]

OpenAlex: https://openalex.org/W4401038504 (Open access: False)
    
[[https://openalex.org/A5017659349][Hai Jia]], [[https://openalex.org/A5045814743][Peng-Cheng Ji]], [[https://openalex.org/A5100773000][Yang Teng]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401276 
     
In this work, the waste orange-peel was used as carbon source, and the orange-peel derived carbon material can be obtained through simple pyrolysis. Then, we designed the structure of orange-peel carbon aerogel grown on iron-nickel layered double hydroxides in situ to achieve the effect of carbon coating (FeNi-LDH/CA). The oxygen evolution reaction catalytic performance of FeNi-LDH/CA is excellent, far exceeding that of commercial RuO2. In 1 M KOH, the overpotential of FeNi-LDH/CA is only 250 mV (10 mA cm-2), obviously better than that of commercial RuO2 (295 mV). FeNi-LDH/CA shows good cycling stability, and after long-term i-t testing, the performance only decays by 3% after running at 100 mA cm-2 for 100 h. When used as an anode, the voltage of water-splitting is only 1.48 V at 10 mA cm-2. The rechargeable liquid zinc-air battery based on Pt/C-FeNi-LDH/CA catalyst has higher open-circuit voltage (1.543 V) and galvanostatic discharge capacity at 1.23 V (830 min, 10 mA cm-2). Moreover, the zinc-air battery based on Pt/C-FeNi-LDH/CA has a small charge-discharge voltage gap (0.65 V) at 10 mA cm-2, after 200 consecutive cycles (66 h), the charge-discharge voltage gap only increased by about 30 mV, indicating good cycling stability.    

    

* Selection of metal halide redox mediator suitable for lithium air battery by evaluating oxygen evolution efficiency  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401040180
:TOPICS: Conducting Polymer Research, Lithium-ion Battery Management in Electric Vehicles
:PUBLICATION_DATE: 2024-06-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.53619/kobs.2024.6.4.1.58")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401040180"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401040180"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401040180"))][Get cited by]]

OpenAlex: https://openalex.org/W4401040180 (Open access: False)
    
[[https://openalex.org/A5103072955][Juhyoung Kim]], [[https://openalex.org/A5100359367][Dongwook Kim]], Journal of the Korean Battery Society. 4(1)] 2024. https://doi.org/10.53619/kobs.2024.6.4.1.58 
     
No abstract    

    

* Promoting Surface Reconstruction in Spinel Oxides via Tetrahedral‐Octahedral Phase Boundary Construction for Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400981749
:TOPICS: Emergent Phenomena at Oxide Interfaces, Catalytic Nanomaterials, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202409912")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400981749"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400981749"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400981749"))][Get cited by]]

OpenAlex: https://openalex.org/W4400981749 (Open access: False)
    
[[https://openalex.org/A5070625824][Anqi Zou]], [[https://openalex.org/A5084950399][Chao Wu]], [[https://openalex.org/A5076586440][Qi Zhang]], [[https://openalex.org/A5100617553][Ying Tang]], [[https://openalex.org/A5100329144][Junhua Li]], [[https://openalex.org/A5050445254][Hecheng Meng]], [[https://openalex.org/A5101800679][Zhen Wang]], [[https://openalex.org/A5059436219][Caozheng Diao]], [[https://openalex.org/A5056256510][Zhi Gen Yu]], [[https://openalex.org/A5034827883][Junmin Xue]], [[https://openalex.org/A5031292832][Shibo Xi]], [[https://openalex.org/A5100730229][Xiaopeng Wang]], [[https://openalex.org/A5102812387][Jiagang Wu]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202409912 
     
Understanding the origin of surface reconstruction is crucial for developing highly efficient lattice oxygen oxidation mechanism (LOM) based spinel oxides. Traditionally, the reconstruction has been achieved through electrochemical procedures, such as cyclic voltammetry (CV), linear sweep voltammetry (LSV). In this work, we found that the surface reconstruction in LOM‐based CoFe0.25Al1.75O4 catalyst was an irreversible oxygen redox chemical reaction. And a lower oxygen vacancy formation energy (EO‐V) could benefit the combination of the activated lattice oxygen atoms with adsorbed water molecular. Motivated by this finding, a strategy of phase boundary construction from Co tetrahedral to octahedral was employed to decrease EO‐V in CoFe0.25Al1.75O4. The results showed that as the Co octahedral occupancy ratio rose to 64%, a 3.5 nm‐thick reconstructed layer formed on the catalyst surface with a 158 mV decrease in overpotential. Further experiments indicated that the coexistence of tetrahedral‐octahedral (O‐T) phase would result in lattice mismatch, promoting non‐bonding oxygen states and lowering EO‐V. Then more active lattice oxygen combined with H2O molecules to generate hydroxide ions (OH‐), followed by soluble cation leaching, which enhanced the reconstruction process. This work provided new insights into the relationship between the intrinsic structure of pre‐catalysts and surface reconstruction in LOM‐based spinel electrocatalysts.    

    

* Promoting Surface Reconstruction in Spinel Oxides via Tetrahedral‐Octahedral Phase Boundary Construction for Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400981750
:TOPICS: Catalytic Nanomaterials, Emergent Phenomena at Oxide Interfaces, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202409912")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400981750"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400981750"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400981750"))][Get cited by]]

OpenAlex: https://openalex.org/W4400981750 (Open access: False)
    
[[https://openalex.org/A5070625824][Anqi Zou]], [[https://openalex.org/A5084950399][Chao Wu]], [[https://openalex.org/A5076586440][Qi Zhang]], [[https://openalex.org/A5100617553][Ying Tang]], [[https://openalex.org/A5100329144][Junhua Li]], [[https://openalex.org/A5050445254][Hecheng Meng]], [[https://openalex.org/A5101800679][Zhen Wang]], [[https://openalex.org/A5059436219][Caozheng Diao]], [[https://openalex.org/A5056256510][Zhi Gen Yu]], [[https://openalex.org/A5034827883][Junmin Xue]], [[https://openalex.org/A5031292832][Shibo Xi]], [[https://openalex.org/A5100730229][Xiaopeng Wang]], [[https://openalex.org/A5102812387][Jiagang Wu]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202409912 
     
Understanding the origin of surface reconstruction is crucial for developing highly efficient lattice oxygen oxidation mechanism (LOM) based spinel oxides. Traditionally, the reconstruction has been achieved through electrochemical procedures, such as cyclic voltammetry (CV), linear sweep voltammetry (LSV). In this work, we found that the surface reconstruction in LOM-based CoFe0.25Al1.75O4 catalyst was an irreversible oxygen redox chemical reaction. And a lower oxygen vacancy formation energy (EO-V) could benefit the combination of the activated lattice oxygen atoms with adsorbed water molecular. Motivated by this finding, a strategy of phase boundary construction from Co tetrahedral to octahedral was employed to decrease EO-V in CoFe0.25Al1.75O4. The results showed that as the Co octahedral occupancy ratio rose to 64%, a 3.5 nm-thick reconstructed layer formed on the catalyst surface with a 158 mV decrease in overpotential. Further experiments indicated that the coexistence of tetrahedral-octahedral (O-T) phase would result in lattice mismatch, promoting non-bonding oxygen states and lowering EO-V. Then more active lattice oxygen combined with H2O molecules to generate hydroxide ions (OH-), followed by soluble cation leaching, which enhanced the reconstruction process. This work provided new insights into the relationship between the intrinsic structure of pre-catalysts and surface reconstruction in LOM-based spinel electrocatalysts.    

    

* Transparent TiO2 nanotubes supporting silver sulfide for photoelectrochemical water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401029688
:TOPICS: Photocatalysis and Solar Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nr01440e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401029688"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401029688"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401029688"))][Get cited by]]

OpenAlex: https://openalex.org/W4401029688 (Open access: False)
    
[[https://openalex.org/A5043329735][Wiktoria Lipińska]], [[https://openalex.org/A5014026736][Stefania Wolff]], [[https://openalex.org/A5089248762][Katharina E. Dehm]], [[https://openalex.org/A5019815848][Simon Hager]], [[https://openalex.org/A5003469307][Justyna Gumieniak]], [[https://openalex.org/A5079638281][Agnieszka Kramek]], [[https://openalex.org/A5036160372][Ryan W. Crisp]], [[https://openalex.org/A5066606506][Emerson Coy]], [[https://openalex.org/A5039043497][Katarzyna Grochowska]], [[https://openalex.org/A5082279488][Katarzyna Siuzdak]], Nanoscale. None(None)] 2024. https://doi.org/10.1039/d4nr01440e 
     
Differences between photoelectrochemical and electrochemical activity were thoroughly investigated for the oxygen evolution reaction mediated by Ag 2 S deposited on two types of ordered titania substrates. Titanium dioxide in the form...    

    

* Universal synthesis of coral-like Ternary MOF-Derived Sulfides as efficient OER electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400969813
:TOPICS: Innovations in Organic Synthesis Reactions, Desulfurization Technologies for Fuels, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4qi01725k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400969813"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400969813"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400969813"))][Get cited by]]

OpenAlex: https://openalex.org/W4400969813 (Open access: False)
    
[[https://openalex.org/A5059102739][Tianpeng Liu]], [[https://openalex.org/A5056349795][Yangping Zhang]], [[https://openalex.org/A5082084628][Jun Yu]], [[https://openalex.org/A5006071289][Mengyun Hu]], [[https://openalex.org/A5010896261][Zhengying Wu]], [[https://openalex.org/A5090080711][Xiao Wei]], [[https://openalex.org/A5079994695][Shudi Yu]], [[https://openalex.org/A5004666624][Yukou Du]], Inorganic Chemistry Frontiers. None(None)] 2024. https://doi.org/10.1039/d4qi01725k 
     
The strategy of synthesizing a high-efficiency oxygen evolution reaction (OER) catalysts by sacrificing metal-organic frameworks (MOF) templates is considered promising. However, few reports have focused on improving the intrinsic electrocatalytic...    

    

* Single-atom nickel on defective g-C4N3 as a promising bifunctional electrocatalyst for the OER and ORR: a first-principles analysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401007558
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/2053-1591/ad674b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401007558"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401007558"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401007558"))][Get cited by]]

OpenAlex: https://openalex.org/W4401007558 (Open access: True)
    
[[https://openalex.org/A5101276901][Teng fei Gao]], [[https://openalex.org/A5102957728][Xiao-Kuan Wu]], [[https://openalex.org/A5066425442][Dan Wen]], [[https://openalex.org/A5100846080][Xin Zhi]], [[https://openalex.org/A5052495835][Yu Fang]], [[https://openalex.org/A5100456542][Liang Wang]], [[https://openalex.org/A5100436765][Jie Zhang]], [[https://openalex.org/A5101165186][Jimmy Yun]], Materials Research Express. None(None)] 2024. https://doi.org/10.1088/2053-1591/ad674b 
     
Abstract Searching for inexpensive and highly active materials to replace noble metals for oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) is an important challenge. The two-dimensional semi-metallic carbon nitride g-C4N3 is an excellent candidate for electrochemical reactions owing to its eminent conductivity and stability. Here, using density functional theory (DFT) a series of low-budget non-noble transition metal single-atom (SAC) loaded on the g-C4N3 (named as TM@C4N3, TM=Cr, Mn, Fe, Co, Ni, Cu) were investigated as electrocatalysts for OER and ORR. Ni@C4N3 shows an enormous application potential as electrode material, with OER and ORR overpotentials of 0.59 V and 0.23 V, respectively. The second lowest binding energy between Ni and support g-C4N3 indicates that Ni@C4N3 possesses good overall stability. The d-band center as well as metal valence as the descriptor exhibit good agreement with the adsorption energy of the intermediate. A linear relationship exists among the adsorption energies of the three intermediates O, OH, and OOH, given the similarity that they are all bonded to the metal through one oxygen atom. By adjusting the adsorption energy of these intermediates, the catalytic activity of electrocatalysts can be tuned for OER and ORR. This study confirmed that Ni@C4N3 is a good bifunctional catalyst and provides important guidance for the design of bifunctional electrocatalysts for OER and ORR.    

    

* Electrochemical Performance of a Hybrid NiCo2O4@NiFelt Electrode at Different Operating Temperatures and Electrolyte pH  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401015177
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17153703")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401015177"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401015177"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401015177"))][Get cited by]]

OpenAlex: https://openalex.org/W4401015177 (Open access: True)
    
[[https://openalex.org/A5030861695][Ataollah Niyati]], [[https://openalex.org/A5057441958][Arianna Moranda]], [[https://openalex.org/A5105099730][Pouya Beigzadeh Arough]], [[https://openalex.org/A5018160528][Federico Navarra]], [[https://openalex.org/A5069334959][Ombretta Paladino]], Energies. 17(15)] 2024. https://doi.org/10.3390/en17153703 
     
Transition metals such as nickel and cobalt as an alternative to Pt and Pd can be used for oxygen evolution reactions (OERs) and hydrogen production reactions (HERs) in alkaline environments, facilitating green hydrogen production as a sustainable alternative to fossil fuels. In this study, an NiCo2O4 catalyst was produced by a sono-hydrothermal method using urea as a hydrolysis agent. The electrochemical performance of the catalyst-coated NiFelt electrode was evaluated at different KOH concentrations (0.25, 0.5, and 1 M) and four operating temperatures in the interval of 20–80 °C. The electrode characteristics were investigated via electrochemical spectroscopy (cyclic voltammetry, EIS, multistep chronopotentiometry, multistep chronoamperometry) using two different reference electrodes (Ag/AgCl and Hg/HgO), to obtain insight into the anodic and cathodic peaks. XRD, SEM, EDS, and TEM analyses confirmed the purity, structure, and nanoscale particle size (20–45 nm) of the NiCo2O4 catalyst. The electrode showed symmetric CV with Ag/AgCl, making this reference electrode more appropriate for capacitance measurements, while Hg/HgO proved advantageous for EIS in alkaline solutions due to reduced noise. The overpotential of the catalyst-coated NiFelt decreased by 108 mV at 10 mA/cm2 compared to bare NiFelt, showing a good potential for its application in anion exchange membranes and alkaline electrolyzers at an industrial scale.    

    

* The Modification of Aluminum Oxide Inclusions in Bearing Steel under Different Cleanliness Conditions by Rare Earth Elements  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401014801
:TOPICS: Thermochemical Software and Databases in Metallurgy, Thermal Barrier Coatings for Gas Turbines, High-Strength Steel Materials
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/met14080861")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401014801"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401014801"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401014801"))][Get cited by]]

OpenAlex: https://openalex.org/W4401014801 (Open access: True)
    
[[https://openalex.org/A5058107332][Ning Wang]], [[https://openalex.org/A5027991565][Wen-zhi Xia]], [[https://openalex.org/A5101486255][Yun Zhou]], [[https://openalex.org/A5102709109][Aijun Deng]], [[https://openalex.org/A5053004252][Guang-da Bao]], [[https://openalex.org/A5087535000][Zhiyou Liao]], [[https://openalex.org/A5071932994][Haichuan Wang]], Metals. 14(8)] 2024. https://doi.org/10.3390/met14080861 
     
The impact of rare earth treatment on the chemical morphology evolution of non-metallic inclusions in bearing steel under different initial cleanliness conditions was studied through simulation. Thermodynamic calculations indicate that at an oxygen content of 0.001%, the evolution route of inclusions with increasing Ce content was Al2O3 → CeAl11O18 + CeAlO3 → CeAlO3 + Ce2O2S → Ce2O2S → Ce2O2S + CeS. As the initial oxygen content decreases, the proportion of CeAlO3 decreases, leading to easier conversion of CeAlO3 to Ce2O2S. Vacuum induction furnace experiments demonstrated that with an oxygen content of 0.001%, an increase in Ce content results in a gradual rise in the proportion of inclusions in steel sized 1~2 μm. In contrast, the proportion of inclusions sized 2~5 μm decreases. Consequently, the overall content of inclusions in steel decreases, along with a reduction in both the number density and average size of inclusions. Introducing bearing steel melt with approximately 0.01% Ce rare earth to bearing steel with initial oxygen contents of 0.0005%, 0.001%, and 0.0015% showed an evolution of inclusions from Ce2O2S and CeS to Ce2O3, CeAlO3, etc. The average inclusion size significantly increased from 0.7 μm to 2.16 μm. Morphologically, the transition of inclusions from precipitated to polymerized forms occurred as the initial oxygen content rose. High-temperature laser confocal microscopy experiments demonstrated that inclusions in low cleanliness conditions tend to agglomerate more than those in high cleanliness conditions, contributing to the increase in average size.    

    

* Evolution and persistence of SiO emission in nanosecond laser ablation plumes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401067381
:TOPICS: Laser-Induced Breakdown Spectroscopy in Material Analysis, Laser Ablation Synthesis of Nanoparticles, Femtosecond Laser Micromachining in Transparent Materials
:PUBLICATION_DATE: 2024-07-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6463/ad687f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401067381"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401067381"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401067381"))][Get cited by]]

OpenAlex: https://openalex.org/W4401067381 (Open access: False)
    
[[https://openalex.org/A5037292608][Abdul Kalam Shaik]], [[https://openalex.org/A5002517047][Mark C. Phillips]], [[https://openalex.org/A5086105335][S. S. Harilal]], Journal of Physics D Applied Physics. None(None)] 2024. https://doi.org/10.1088/1361-6463/ad687f 
     
Abstract Analyzing laser-produced plasmas (LPP) in a controlled oxygen-containing environment provides insight into the formation and evolution of molecular species through gas-phase oxidation. This study explores the role of ambient pressure and oxygen availability in forming SiO molecular species in laser ablation plumes. The self-emission emanating during the reactive ablation of Si targets was characterized by optical emission spectroscopy and optical time-of-flight techniques. Our results showed that the SiO species formation was greatly influenced by both the ambient pressure and oxygen availability. The intensity and the persistence of SiO emission bands are lower at higher oxygen concentrations, indicating they are depopulated by the formation of more complex silicon oxides. The oxygen partial pressure effects on plume chemistry showed that SiO formation is favored even with a minimal oxygen concentration in the environment.    

    

* Dynamic Evolution of Antisite Defect and Coupling Anionic Redox in High‐Voltage Ultrahigh‐Ni Cathode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401037985
:TOPICS: Corrosion Inhibitors and Protection Mechanisms, Hydrogen Embrittlement in Metals and Alloys, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202410326")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401037985"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401037985"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401037985"))][Get cited by]]

OpenAlex: https://openalex.org/W4401037985 (Open access: False)
    
[[https://openalex.org/A5100815082][Kang Wu]], [[https://openalex.org/A5023540032][Peilin Ran]], [[https://openalex.org/A5024336975][Wen Yin]], [[https://openalex.org/A5048079565][Lunhua He]], [[https://openalex.org/A5029977105][Bao‐Tian Wang]], [[https://openalex.org/A5022016300][Jinming Jian]], [[https://openalex.org/A5011501177][Enyue Zhao]], [[https://openalex.org/A5060076875][Jinkui Zhao]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202410326 
     
High-voltage ultrahigh-Ni cathodes (LiNixCoyMn1-x-yO2, x ≥ 0.9) can significantly enhance the energy density and cost-effectiveness of Li-ion batteries beyond current levels. However, severe Li-Ni antisite defects and their undetermined dynamic evolutions during high-voltage cycling limit the further development of these ultrahigh-Ni cathodes. In this study, we quantify the dynamic evolutions of the Li-Ni antisite defect using operando neutron diffraction and reveal its coupling relationship with anionic redox, another critical challenge restricting ultrahigh-Ni cathodes. We detect a clear Ni migration coupled with an unstable oxygen lattice, which accompanies the oxidation of oxygen anions at high voltages. Based on these findings, we propose that minimized Li-Ni antisite defects and controlled Ni migrations are essential for achieving stable high-voltage cycling structures in ultrahigh-Ni cathodes. This is further demonstrated by the optimized ultrahigh-Ni cathode, where reduced dynamic evolutions of the Li-Ni antisite defect effectively inhibit the anionic redox, enhancing the 4.5 V cycling stability.    

    

* Dynamic Evolution of Antisite Defect and Coupling Anionic Redox in High‐Voltage Ultrahigh‐Ni Cathode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401038097
:TOPICS: Corrosion Inhibitors and Protection Mechanisms, Electrochemical Detection of Heavy Metal Ions, Hydrogen Embrittlement in Metals and Alloys
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202410326")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401038097"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401038097"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401038097"))][Get cited by]]

OpenAlex: https://openalex.org/W4401038097 (Open access: False)
    
[[https://openalex.org/A5100815082][Kang Wu]], [[https://openalex.org/A5023540032][Peilin Ran]], [[https://openalex.org/A5100699028][Wen Yin]], [[https://openalex.org/A5048079565][Lunhua He]], [[https://openalex.org/A5029977105][Bao‐Tian Wang]], [[https://openalex.org/A5022016300][Jinming Jian]], [[https://openalex.org/A5011501177][Enyue Zhao]], [[https://openalex.org/A5060076875][Jinkui Zhao]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202410326 
     
High‐voltage ultrahigh‐Ni cathodes (LiNixCoyMn1−x−yO2, x ≥ 0.9) can significantly enhance the energy density and cost‐effectiveness of Li‐ion batteries beyond current levels. However, severe Li‐Ni antisite defects and their undetermined dynamic evolutions during high‐voltage cycling limit the further development of these ultrahigh‐Ni cathodes. In this study, we quantify the dynamic evolutions of the Li‐Ni antisite defect using operando neutron diffraction and reveal its coupling relationship with anionic redox, another critical challenge restricting ultrahigh‐Ni cathodes. We detect a clear Ni migration coupled with an unstable oxygen lattice, which accompanies the oxidation of oxygen anions at high voltages. Based on these findings, we propose that minimized Li‐Ni antisite defects and controlled Ni migrations are essential for achieving stable high‐voltage cycling structures in ultrahigh‐Ni cathodes. This is further demonstrated by the optimized ultrahigh‐Ni cathode, where reduced dynamic evolutions of the Li‐Ni antisite defect effectively inhibit the anionic redox, enhancing the 4.5 V cycling stability.    

    

* Unique myoglobin adaptation to endothermy and flight since the origin of birds  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401006652
:TOPICS: Hemoglobin Function and Regulation in Vertebrates, Metabolic Theory of Ecology and Climate Change Impacts, Neural Mechanisms of Respiratory Control and Homeostasis
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/1749-4877.12870")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401006652"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401006652"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401006652"))][Get cited by]]

OpenAlex: https://openalex.org/W4401006652 (Open access: False)
    
[[https://openalex.org/A5026378449][Shengjing Song]], [[https://openalex.org/A5036798398][H. D. Chen]], [[https://openalex.org/A5100437614][Yu Zhang]], [[https://openalex.org/A5015941197][Xiaojia Zhu]], [[https://openalex.org/A5086259776][David M. Irwin]], [[https://openalex.org/A5062724953][Kai He]], [[https://openalex.org/A5015039329][Yang Liu]], Integrative Zoology. None(None)] 2024. https://doi.org/10.1111/1749-4877.12870 
     
Myoglobin (Mb) mediates oxygen diffusion and storage in muscle tissue and thus is important for the energy utilization and activity of animals. Birds generally have a high body temperature, and most species also possess the capability of powered flight. Both of these require high levels of aerobic metabolism. Within endothermic mammals, bats also independently evolved flight. Although the functional evolution of myoglobins in deep-diving amniote vertebrates has been well-studied, the functional evolution of myoglobin since the origins of both birds and bats is unclear. Here, with Mb-coding sequences from >200 extant amniote species, we reconstructed ancestral sequences to estimate the functional properties of myoglobin through amniote evolution. A dramatic change in net surface charge on myoglobin occurred during the origin of Aves, which might have been driven by positively selected amino acid substitutions that occurred on the lineage leading to all birds. However, in bats, no change in net surface charge occurred and instead, the Mb genes show evidence of strong purifying selection. The increased net surface charge on bird myoglobins implies an adaptation to flight-related endothermic and higher body temperatures, possibly by reducing harmful protein aggregations. Different from the findings of net surface charge, myoglobins of extant birds show lower stability compared with other amniotes, which probably accelerates the rate of oxygen utilization in muscles. In bats and other mammals, higher stability of Mb may be an alternative pathway for adaptation to endothermy, indicating divergent evolution of myoglobin in birds and bats.    

    

* Divergent molecular strategies drive evolutionary adaptation to competitive fitness in biofilm formation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400974308
:TOPICS: Evolutionary Dynamics of Genetic Adaptation and Mutation, Ecology and Evolution of Viruses in Ecosystems, Evolution of Cooperation and Altruism in Social Systems
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/ismejo/wrae135")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400974308"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400974308"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400974308"))][Get cited by]]

OpenAlex: https://openalex.org/W4400974308 (Open access: True)
    
[[https://openalex.org/A5101469857][Mingxing Tang]], [[https://openalex.org/A5101073182][Ruixue Yang]], [[https://openalex.org/A5057095235][Zilin Zhuang]], [[https://openalex.org/A5013954506][Shuhong Han]], [[https://openalex.org/A5006148444][Yehuan Sun]], [[https://openalex.org/A5101773773][Peiyu Li]], [[https://openalex.org/A5049411475][Kewei Fan]], [[https://openalex.org/A5101415139][Cai Zhao]], [[https://openalex.org/A5101292510][Yang Qiong]], [[https://openalex.org/A5069007742][Zhijian Yu]], [[https://openalex.org/A5062430868][Liang Yang]], [[https://openalex.org/A5100386628][Shuo Li]], The ISME Journal. None(None)] 2024. https://doi.org/10.1093/ismejo/wrae135  ([[https://academic.oup.com/ismej/advance-article-pdf/doi/10.1093/ismejo/wrae135/58650367/wrae135.pdf][pdf]])
     
Abstract Biofilm is a group of heterogeneously structured and densely packed bacteria with limited access to nutrients and oxygen. These intrinsic features can allow a mono-species biofilm to diversify into polymorphic subpopulations, determining the overall community’s adaptive capability to changing ecological niches. However, the specific biological functions underlying biofilm diversification and fitness adaptation are poorly demonstrated. Here, we launched and monitored the experimental evolution of Pseudomonas aeruginosa biofilms, finding that two divergent molecular trajectories were adopted for adaptation to higher competitive fitness in biofilm formation: one involved hijacking bacteriophage superinfection to aggressively inhibit kin competitors, whereas the other induced a subtle change in c-di-GMP signaling to gain a positional advantage via enhanced early biofilm adhesion. Bioinformatics analyses implicated that similar evolutionary strategies were prevalent among clinical P. aeruginosa strains, indicative of parallelism between natural and experimental evolution. Divergence in the molecular bases illustrated the adaptive values of genomic plasticity for gaining competitive fitness in biofilm formation. Finally, we demonstrated that these fitness-adaptive mutations reduced bacterial virulence. Our findings revealed how the mutations intrinsically generated from the biofilm environment influence the evolution of P. aeruginosa.    

    

* Microstructure and oxidation behaviour of Mo–Si–B–Hf alloys at 800 °C and 1100 °C  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401033451
:TOPICS: Synthesis and Properties of Cemented Carbides, Design and Applications of Intermetallic Alloys, Ceramic Materials and Processing
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1177/02670836241266451")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401033451"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401033451"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401033451"))][Get cited by]]

OpenAlex: https://openalex.org/W4401033451 (Open access: False)
    
[[https://openalex.org/A5100343241][Shuo Sun]], [[https://openalex.org/A5100560011][Xiaohui Lin]], [[https://openalex.org/A5058495371][Xuanqiao Gao]], [[https://openalex.org/A5100768010][Yanchao Li]], [[https://openalex.org/A5046478804][Jing Liang]], [[https://openalex.org/A5069268058][Wei Zai]], [[https://openalex.org/A5100444342][Wen Zhang]], Materials Science and Technology. None(None)] 2024. https://doi.org/10.1177/02670836241266451 
     
The influences of the microstructure evolution and oxidation behaviour of Hf-modified Mo–12Si–12B alloys were systematically studied at 800 °C and 1100 °C. Vickers hardness tests show that the Hf addition increases the hardness of Mo–Si–B–Hf alloys. The oxidation experiments were conducted at 800 °C and 1100 °C for 12 h; the detailed analysis revealed that the formation of HfSiO 4 in Mo–12Si–12B–10Hf alloy can effectively decrease the content of oxygen and make the surface of the oxide layer more complete at 800 °C. At 1100°C, the distinct difference in the expansion coefficient among the oxide films results in the formation of cracks and holes in Mo–12Si–12B–10Hf alloy, so the Mo–12Si–12B–10Hf alloy shows poor oxidation resistance.    

    

* Pushing the limits: expanding the temperature tolerance of a coral photosymbiont through differing selection regimes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400995935
:TOPICS: Resilience of Coral Reef Ecosystems to Climate Change, Ecological Dynamics of Marine Environments, Impacts of Climate Change on Marine Fisheries
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/nph.19996")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400995935"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400995935"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400995935"))][Get cited by]]

OpenAlex: https://openalex.org/W4400995935 (Open access: True)
    
[[https://openalex.org/A5030572658][Hugo Scharfenstein]], [[https://openalex.org/A5089963189][Lesa M. Peplow]], [[https://openalex.org/A5010436120][Carlos Alvarez‐Roa]], [[https://openalex.org/A5063307504][Matthew R. Nitschke]], [[https://openalex.org/A5019308572][Wing Yan Chan]], [[https://openalex.org/A5046444751][Patrick Buerger]], [[https://openalex.org/A5086971721][Madeleine J. H. van Oppen]], New Phytologist. None(None)] 2024. https://doi.org/10.1111/nph.19996 
     
Coral thermal bleaching resilience can be improved by enhancing photosymbiont thermal tolerance via experimental evolution. While successful for some strains, selection under stable temperatures was ineffective at increasing the thermal threshold of an already thermo-tolerant photosymbiont (Durusdinium trenchii). Corals from environments with fluctuating temperatures tend to have comparatively high heat tolerance. Therefore, we investigated whether exposure to temperature oscillations can raise the upper thermal limit of D. trenchii. We exposed a D. trenchii strain to stable and fluctuating temperature profiles, which varied in oscillation frequency. After 2.1 yr (54-73 generations), we characterised the adaptive responses under the various experimental evolution treatments by constructing thermal performance curves of growth from 21 to 31°C for the heat-evolved and wild-type lineages. Additionally, the accumulation of extracellular reactive oxygen species, photophysiology, photosynthesis and respiration rates were assessed under increasing temperatures. Of the fluctuating temperature profiles investigated, selection under the most frequent oscillations (diurnal) induced the greatest widening of D. trenchii's thermal niche. Continuous selection under elevated temperatures induced the only increase in thermal optimum and a degree of generalism. Our findings demonstrate how differing levels of thermal homogeneity during selection drive unique adaptive responses to heat in a coral photosymbiont.    

    

* Origin of the Surface Magnetic Dead Layer in Rare‐Earth Titanates  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401038578
:TOPICS: Magnetocaloric Materials Research, Emergent Phenomena at Oxide Interfaces, Quantum Spin Liquids in Frustrated Magnets
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/admi.202400489")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401038578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401038578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401038578"))][Get cited by]]

OpenAlex: https://openalex.org/W4401038578 (Open access: True)
    
[[https://openalex.org/A5087769815][Raphaël Aeschlimann]], [[https://openalex.org/A5031758687][Manuel Bibès]], [[https://openalex.org/A5025915332][Alexandre Gloter]], Advanced Materials Interfaces. None(None)] 2024. https://doi.org/10.1002/admi.202400489 
     
Abstract Perovskite rare‐earth titanates RTiO 3 display a rich array of magnetic and electronic properties, with a Mott‐insulating ground state and ferro‐ or antiferromagnetic spin orders depending on the rare‐earth R. The nominal Ti valence is 3+ with a corresponding 3 d 1 configuration. Yet, at the surface of both bulk and thin films of RTiO 3 , the Ti valence has been found to strongly deviate towards the more stable 4+ state, adversely affecting magnetic properties. While this finding is rather ubiquitous, its exact origin is still poorly understood, which hampers the integration of RTiO 3 into complex heterostructures harnessing their rich physics. Here, scanning transmission electron microscope and electron energy loss spectroscopy experiments are used to analyze the top part of an epitaxial DyTiO 3 thin film displaying a well‐developed Ti 4+ ‐rich layer over several nanometres. It shows that this valence evolution is related to a combination of short‐range ordered interstitial oxygen planes and Ti‐Dy cationic imbalance. Both defects synergistically contribute to enough hole doping for a complete transition toward Ti 4+ over a few unit‐cells from the surface while a structure primarily of the perovskite‐type is maintained.    

    

* Emerging insights into the pathogenesis and therapeutic strategies for vascular endothelial injury-associated diseases: focus on mitochondrial dysfunction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401010620
:TOPICS: Mitochondrial Dynamics and Reactive Oxygen Species Regulation, Pathophysiology of Myocardial Reperfusion Injury, Copper and Zinc in Health and Disease
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10456-024-09938-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401010620"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401010620"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401010620"))][Get cited by]]

OpenAlex: https://openalex.org/W4401010620 (Open access: True)
    
[[https://openalex.org/A5074106903][Boxian Pang]], [[https://openalex.org/A5070949320][Guangtong Dong]], [[https://openalex.org/A5071917815][Tieliang Pang]], [[https://openalex.org/A5054279552][Xinyao Sun]], [[https://openalex.org/A5100352198][Xin Liu]], [[https://openalex.org/A5054558623][Yifeng Nie]], [[https://openalex.org/A5065945066][Xing Chang]], Angiogenesis. None(None)] 2024. https://doi.org/10.1007/s10456-024-09938-4 
     
As a vital component of blood vessels, endothelial cells play a key role in maintaining overall physiological function by residing between circulating blood and semi-solid tissue. Various stress stimuli can induce endothelial injury, leading to the onset of corresponding diseases in the body. In recent years, the importance of mitochondria in vascular endothelial injury has become increasingly apparent. Mitochondria, as the primary site of cellular aerobic respiration and the organelle for "energy information transfer," can detect endothelial cell damage by integrating and receiving various external stress signals. The generation of reactive oxygen species (ROS) and mitochondrial dysfunction often determine the evolution of endothelial cell injury towards necrosis or apoptosis. Therefore, mitochondria are closely associated with endothelial cell function, helping to determine the progression of clinical diseases. This article comprehensively reviews the interconnection and pathogenesis of mitochondrial-induced vascular endothelial cell injury in cardiovascular diseases, renal diseases, pulmonary-related diseases, cerebrovascular diseases, and microvascular diseases associated with diabetes. Corresponding therapeutic approaches are also provided. Additionally, strategies for using clinical drugs to treat vascular endothelial injury-based diseases are discussed, aiming to offer new insights and treatment options for the clinical diagnosis of related vascular injuries.    

    

* First Detection of CO Isotopologues in a High-redshift Main-sequence Galaxy: Evidence of a Top-heavy Stellar Initial Mass Function  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400999003
:TOPICS: Stellar Astrophysics and Exoplanet Studies, Star Formation in Molecular Clouds and Protoplanetary Disks, Galaxy Formation and Evolution in the Universe
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3847/1538-4357/ad4da2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400999003"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400999003"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400999003"))][Get cited by]]

OpenAlex: https://openalex.org/W4400999003 (Open access: True)
    
[[https://openalex.org/A5101951001][Ziyi Guo]], [[https://openalex.org/A5035994027][Zhi-Yu Zhang]], [[https://openalex.org/A5064997161][Zhiqiang Yan]], [[https://openalex.org/A5075780212][Eda Gjergo]], [[https://openalex.org/A5028329336][Allison Man]], [[https://openalex.org/A5062504729][R. J. Ivison]], [[https://openalex.org/A5052555995][X. Fu]], [[https://openalex.org/A5047464767][Yong Shi]], The Astrophysical Journal. 970(2)] 2024. https://doi.org/10.3847/1538-4357/ad4da2 
     
Abstract Recent observations and theories have presented a strong challenge to the universality of the stellar initial mass function (IMF) in extreme environments. A notable example has been found for starburst conditions, where evidence favors a top-heavy IMF, i.e., there is a bias toward massive stars compared to the IMF that is responsible for the stellar mass function and elemental abundances observed in the Milky Way. Local starburst galaxies have star formation rates similar to those in high-redshift main-sequence galaxies, which appear to dominate the stellar mass budget at early epochs. However, the IMF of high-redshift main-sequence galaxies is yet to be probed. Since 13 CO and C 18 O isotopologues are sensitive to the IMF, we have observed these lines toward four strongly lensed high-redshift main-sequence galaxies using the Atacama Large Millimeter/submillimeter Array. Of our four targets, SDSS J0901+1814, at z ≈ 2.26, is seen clearly in 13 CO and C 18 O, the first detection of CO isotopologues in the high-redshift main-sequence galaxy population. The observed 13 C/ 18 O ratio, 2.4 ± 0.8, is significantly lower than that of local main-sequence galaxies. We estimate the isotope ratio, oxygen abundance, and stellar mass using a series of chemical evolution models with varying star formation histories and IMFs. All models favor an IMF that is more top-heavy than that of the Milky Way. Thus, as with starburst galaxies, main-sequence galaxies in the high-redshift Universe have a greater fraction of massive stars than a Milky Way IMF would imply.    

    

* Genomic Evolution of Influenza During the 2023-2024 Season, the Johns Hopkins Health System  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401022367
:TOPICS: Influenza Virus Research and Epidemiology, Epidemiology and Pathogenesis of Respiratory Viral Infections, Digital Epidemiology and Disease Surveillance
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcv.2024.105718")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401022367"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401022367"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401022367"))][Get cited by]]

OpenAlex: https://openalex.org/W4401022367 (Open access: True)
    
[[https://openalex.org/A5092068755][Madeline Yunker]], [[https://openalex.org/A5093861399][David A. Villafuerte]], [[https://openalex.org/A5066361964][Amary Fall]], [[https://openalex.org/A5054162197][Julie M. Norton]], [[https://openalex.org/A5101993611][Omar Abdullah]], [[https://openalex.org/A5018269231][Richard E. Rothman]], [[https://openalex.org/A5011142719][Katherine Fenstermacher]], [[https://openalex.org/A5040756646][C. Paul Morris]], [[https://openalex.org/A5066093013][Andrew Pekosz]], [[https://openalex.org/A5011589199][Eili Klein]], [[https://openalex.org/A5015631762][Heba H. Mostafa]], Journal of Clinical Virology. 174(None)] 2024. https://doi.org/10.1016/j.jcv.2024.105718 
     
Influenza, a human disease caused by viruses in the Orthomyxoviridae family, is estimated to infect 5% -10 % of adults and 20% -30 % of children annually. Influenza A (IAV) and Influenza B (IBV) viruses accumulate amino acid substitutions (AAS) in the hemagglutinin (HA) and neuraminidase (NA) proteins seasonally. These changes, as well as the dominating viral subtypes, vary depending on geographical location, which may impact disease prevalence and the severity of the season. Genomic surveillance is crucial for capturing circulation patterns and characterizing AAS that may affect disease outcomes, vaccine efficacy, or antiviral drug activities. In this study, whole-genome sequencing of IAV and IBV was attempted on positive remnant clinical samples (587) collected from 580 patients between June 2023 and February 2024 in the Johns Hopkins Health System (JHHS). Full-length HA segments were obtained from 424 (72.2 %) samples. H1N1pdm09 (71.7 %) was the predominant IAV subtype, followed by H3N2 (16.7 %) and IBV-Victoria clade V1A.3a.2 (11.6 %). Within H1N1pdm09 HA sequences, the 6B1A.5a.2a.1 (60.5 %) clade was the most represented. Full-length NA segments were obtained from 421 (71.7 %) samples. Within H1N1pdm09 and IBV, AAS previously proposed to change susceptibility to NA inhibitors were infrequently detected. Phylogeny of HA and NA demonstrated heterogeneous HA and NA H1N1pdm09 and IBV subclades. No significant differences were observed in admission rates or use of supplemental oxygen between different subtypes or clades. Influenza virus genomic surveillance is essential for understanding the seasonal evolution of influenza viruses and their association with disease prevalence and outcomes.    

    

* The origin and migration laws of hydrocarbons in uranium‐bearing Luohe Formation, Pengyang area, SW Ordos Basin  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401007272
:TOPICS: Characterization of Shale Gas Pore Structure, Chemistry of Actinide and Lanthanide Elements, Tectonic and Geochronological Evolution of Orogens
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/gj.5017")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401007272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401007272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401007272"))][Get cited by]]

OpenAlex: https://openalex.org/W4401007272 (Open access: False)
    
[[https://openalex.org/A5069183921][Qinghong Si]], [[https://openalex.org/A5026044728][Xueming Teng]], [[https://openalex.org/A5103273498][Qiang Zhu]], [[https://openalex.org/A5101418468][Zongxing Li]], [[https://openalex.org/A5052386407][Hualei Zhao]], [[https://openalex.org/A5011677079][Guo‐Ming Wang]], [[https://openalex.org/A5101243426][Haikui Tong]], [[https://openalex.org/A5087632511][Hongliang Dang]], Geological Journal. None(None)] 2024. https://doi.org/10.1002/gj.5017 
     
The hydrocarbon activity in Pengyang area, situated in the southwestern Ordos Basin, is notably prominent. Investigation on the migration laws of hydrocarbons is imperative for comprehending the involvement in uranium mineralization. Based on the analysis of spatial distribution of hydrocarbon containing fluid and hydrocarbon generation conditions of sandstone in the Luohe Formation, the organic geochemical characteristics including hydrocarbon components, carbon isotopes and biomarker compounds were analysed. The research results indicate that: (1) hydrocarbon fluid activities in the Luohe Formation are predominantly observed in layers exhibiting higher uranium mineralization. The mudstone of the Luohe Formation had low organic matter content and low thermal maturity, which was not conducive to hydrocarbon generation. (2) Hydrocarbon‐containing fluid in the sandstone of Luohe Formation not only contained reducing gases such as methane and hydrogen but also chloroform asphalt components. The carbon isotopes of hydrocarbon in sandstone inform Luohe Formation resemble oil and gas in the Mesozoic. The biomarker parameter inferred that the parent rock of hydrocarbons in the Luohe Formation was formed under reducing and freshwater conditions, and hydrocarbon generation occurred at the mature stage. As above mentioned, a comparison was carried out between the affinity of hydrocarbon‐containing fluid in the Luohe Formation and different layers of hydrocarbon source rocks. The migration behaviour of hydrocarbon‐containing fluid in the Pengyang area has been summarized, and the involvement of hydrocarbon‐containing fluid in uranium mineralization has been discussed. The main concepts are as follows: the sedimentary environment and thermal evolution conditions of hydrocarbons in the sandstone of Luohe Formation resemble those of the primary hydrocarbon source rocks in the Yanchang Formation. The main hydrocarbon charging events in the Luohe Formation occurred before the Late Cretaceous period, which is primarily related to two hydrocarbon generation events from 130 to 100 Ma in the Yanchang Formation and fault conduits connecting the Triassic to the Cretaceous Strata. The hydrocarbon‐containing fluid released from Yanchang Formation migrating to the Luohe Formation provides reducing conditions for the precipitation of uranium in oxygen‐bearing water bodies.    

    

* Lithium Ions as Modulators of Complex Biological Processes: The Conundrum of Multiple Targets, Responsiveness and Non-Responsiveness, and the Potential to Prevent or Correct Dysregulation of Systems during Aging and in Disease  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400980549
:TOPICS: Molecular Mechanisms of Synaptic Plasticity and Neurological Disorders, Epidemiology and Management of Bipolar Disorder, Mechanisms of Alzheimer's Disease
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/biom14080905")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400980549"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400980549"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400980549"))][Get cited by]]

OpenAlex: https://openalex.org/W4400980549 (Open access: True)
    
[[https://openalex.org/A5061396807][David A. Hart]], Biomolecules. 14(8)] 2024. https://doi.org/10.3390/biom14080905 
     
Lithium is one of the lightest elements on Earth and it has been in the environment since the formation of the galaxy. While a common element, it has not been found to be an essential element in biological processes, ranging from single cell organisms to Homo sapiens. Instead, at an early stage of evolution, organisms committed to a range of elements such as sodium, potassium, calcium, magnesium, zinc, and iron to serve essential functions. Such ions serve critical functions in ion channels, as co-factors in enzymes, as a cofactor in oxygen transport, in DNA replication, as a storage molecule in bone and liver, and in a variety of other roles in biological processes. While seemingly excluded from a major essential role in such processes, lithium ions appear to be able to modulate a variety of biological processes and “correct” deviation from normal activity, as a deficiency of lithium can have biological consequences. Lithium salts are found in low levels in many foods and water supplies, but the effectiveness of Li salts to affect biological systems came to recent prominence with the work of Cade, who reported that administrating Li salts calmed guinea pigs and was subsequently effective at relatively high doses to “normalize” a subset of patients with bipolar disorders. Because of its ability to modulate many biological pathways and processes (e.g., cyclic AMP, GSK-3beta, inositol metabolism, NaK ATPases, neuro processes and centers, immune-related events, respectively) both in vitro and in vivo and during development and adult life, Li salts have become both a useful tool to better understand the molecular regulation of such processes and to also provide insights into altered biological processes in vivo during aging and in disease states. While the range of targets for lithium action supports its possible role as a modulator of biological dysregulation, it presents a conundrum for researchers attempting to elucidate its specific primary target in different tissues in vivo. This review will discuss aspects of the state of knowledge regarding some of the systems that can be influenced, focusing on those involving neural and autoimmunity as examples, some of the mechanisms involved, examples of how Li salts can be used to study model systems, as well as suggesting areas where the use of Li salts could lead to additional insights into both disease mechanisms and natural processes at the molecular and cell levels. In addition, caveats regarding lithium doses used, the strengths and weaknesses of rodent models, the background genetics of the strain of mice or rats employed, and the sex of the animals or the cells used, are discussed. Low-dose lithium may have excellent potential, alone or in combination with other interventions to prevent or alleviate aging-associated conditions and disease progression.    

    
