#+TITLE: water splitting
Description: water splitting papers
Created on Sun Apr  7 00:50:15 2024

Found 44 results from 2024-03-31 to 2024-04-07
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Construction of spinel (Fe0.2Co0.2Ni0.2Cr0.2M0.2)3O4 (M = Mg, Mn, Zn, and Cu) high-entropy oxides with tunable valance states for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393339884
:TOPICS: Electrocatalysis for Energy Conversion, High-Entropy Alloys: Novel Designs and Properties, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.174304")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393339884"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393339884"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393339884"))][Get cited by]]

OpenAlex: https://openalex.org/W4393339884 (Open access: False)
    
[[https://openalex.org/A5044180884][Yuanxi Guo]], [[https://openalex.org/A5035441171][Xinxin Zhang]], [[https://openalex.org/A5058501731][Hehe Wei]], [[https://openalex.org/A5021714259][Haitao Yu]], [[https://openalex.org/A5012050092][Ying Xie]], Journal of alloys and compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.174304 
     
No abstract    

    

* Development of CuSe/polypyrrole electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393342827
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s00339-024-07429-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393342827"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393342827"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393342827"))][Get cited by]]

OpenAlex: https://openalex.org/W4393342827 (Open access: False)
    
[[https://openalex.org/A5059163435][Syed Imran Abbas Shah]], [[https://openalex.org/A5049370676][Sumaira Manzoor]], [[https://openalex.org/A5062700170][Muhammad Moazzam Khan]], [[https://openalex.org/A5064746961][Nargis Bano]], [[https://openalex.org/A5022798909][Sameh M. Osman]], [[https://openalex.org/A5063142393][Muhammad Fahad Ehsan]], [[https://openalex.org/A5061069978][Muhammad Naeem Ashiq]], Applied physics. A, Materials science & processing (Print). 130(4)] 2024. https://doi.org/10.1007/s00339-024-07429-3 
     
No abstract    

    

* Hollow-structured cobalt sulfide electrocatalyst for alkaline oxygen evolution reaction: Rational tuning of electronic structure using iron and fluorine dual-doping strategy  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393346162
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.201")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393346162"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393346162"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393346162"))][Get cited by]]

OpenAlex: https://openalex.org/W4393346162 (Open access: False)
    
[[https://openalex.org/A5039271899][Hye-Jin Kim]], [[https://openalex.org/A5043789079][Kyeongseok Min]], [[https://openalex.org/A5009094213][Guoqiang Song]], [[https://openalex.org/A5018263246][Junseong Kim]], [[https://openalex.org/A5066805209][Hyung Chul Ham]], [[https://openalex.org/A5048322224][Sung‐Hyeon Baeck]], Journal of colloid and interface science (Print). None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.201 
     
Utilizing renewable electricity for water electrolysis offers a promising way for generating high-purity hydrogen gases while mitigating the emission of environmental pollutants. To realize the water electrolysis, it is necessary to develop highly active and precious metal-free electrocatalyst for oxygen evolution reaction (OER) which incurs significant overpotential due to its complicated four-electron transfer mechanism. Hence, we propose a facile preparation method for hollow-structured Fe and F dual-doped CoS2 nanosphere (Fe-CoS2-F) as an efficient OER electrocatalyst. The uniform hollow and porous structure of Fe-CoS2-F enlarge the specific surface area and increase the number of exposed active sites. Furthermore, the Fe and F dual-dopants synergistically contributed to the adjustment of electronic structure, thereby promoting the adsorption/desorption of oxygen-containing reaction intermediates on active sites during the alkaline OER procedure. As a result, the prepared Fe-CoS2-F exhibits outstanding OER activity, characterized by a low overpotential of 298 mV to achieve a current density of 10 mA cm−2 and a Tafel slope as small as 46.0 mV dec−1. Based on computational theoretical calculations, the introduction of the dual-dopants into CoS2 structure reduce the excessively strong adsorption energy of reaction intermediate in the rate determining step, leading to effectively promoted electrocatalytic cycle for OER in alkaline environment. This study presents an effective strategy for preparing noble metal-free OER electrocatalysts with promising potential for large-scale industrial water electrolysis.    

    

* Bifunctional oxygen electrocatalyst based on Fe, Co, and nitrogen co-doped graphene-coated alumina nanofibers for Zn-air battery air electrode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393346761
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.160024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393346761"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393346761"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393346761"))][Get cited by]]

OpenAlex: https://openalex.org/W4393346761 (Open access: False)
    
[[https://openalex.org/A5006364002][Marek Mooste]], [[https://openalex.org/A5048289155][Zakarya Ahmed]], [[https://openalex.org/A5094286231][Pavels Kapitulskis]], [[https://openalex.org/A5041364545][Roman Ivanov]], [[https://openalex.org/A5087819640][Alexey Treshchalov]], [[https://openalex.org/A5010424617][Helle‐Mai Piirsoo]], [[https://openalex.org/A5055185943][Arvo Kikas]], [[https://openalex.org/A5050547923][Vambola Kisand]], [[https://openalex.org/A5034289485][Kaupo Kukli]], [[https://openalex.org/A5063726897][Irina Hussainova]], [[https://openalex.org/A5059851555][Kaido Tammeveski]], Applied surface science (Print). None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.160024 
     
Aqueous rechargeable zinc-air battery (RZAB) is an emerging environmentally friendly energy storage device for a wide variety of industrial applications such as electric vehicles, consumer electronics, and stationary power plants. For successful commercialization of RZABs, a cost-effective bifunctional catalyst is highly required to catalyze the oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) at the air electrode. Dual transition-metal and nitrogen-doped nanocarbon materials have shown good potential as an affordable and scalable bifunctional oxygen electrocatalysts alternative to Pt-group metal-based catalysts for RZAB. To achieve this goal, we have developed electrocatalysts based on Fe, Co, and nitrogen co-doped graphene-augmented inorganic alumina nanofibers (Fe/Co-NGr). The Fe/Co-NGr catalysts demonstrate high oxygen reduction and evolution reaction reversibility (ΔE) of 0.85–0.88 V due to the graphene-covered nanofibrous structure doped with FeCo alloy nanoparticles and containing nitrogen, transition metal (TM) coordinated to nitrogen and TM oxide active sites. The primary zinc-air battery with Fe/Co-NGr air electrode exhibits a high maximum power density of 149 mW cm−2 and a specific capacity of 807 mAh gZn-1. The RZAB assessment has shown a low charge–discharge voltage gap of 0.86 V and high energy utilization efficiency of 58 % up to 90 h of charge–discharge cycling at 5 mA cm−2.    

    

* Exploring Cu-Doped Co3O4 Bifunctional Oxygen Electrocatalysts for Aqueous Zn–Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393363876
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c00571")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393363876"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393363876"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393363876"))][Get cited by]]

OpenAlex: https://openalex.org/W4393363876 (Open access: False)
    
[[https://openalex.org/A5075661668][Ashis Kumar Behera]], [[https://openalex.org/A5041617146][Deepak Seth]], [[https://openalex.org/A5067873495][Manish Agarwal]], [[https://openalex.org/A5013844830][M. Ali Haider]], [[https://openalex.org/A5040392509][Aninda J. Bhattacharyya]], ACS applied materials & interfaces (Print). None(None)] 2024. https://doi.org/10.1021/acsami.4c00571 
     
The efficiency of oxygen electrocatalysis is a key factor in diverse energy domain applications, including the performance of metal–air batteries, such as aqueous Zinc (Zn)–air batteries. We demonstrate here that the doping of cobalt oxide with optimal amounts of copper (abbreviated as Cu-doped Co3O4) results in a stable and efficient bifunctional electrocatalyst for oxygen reduction (ORR) and evolution (OER) reactions in aqueous Zn–air batteries. At high Cu-doping concentrations (≥5%), phase segregation occurs with the simultaneous presence of Co3O4 and copper oxide (CuO). At Cu-doping concentrations ≤5%, the Cu ion resides in the octahedral (Oh) site of Co3O4, as revealed by X-ray diffraction (XRD)/Raman spectroscopy investigations and molecular dynamics (MD) calculations. The residence of Cu@Oh sites leads to an increased concentration of surface Co3+-ions (at catalytically active planes) and oxygen vacancies, which is beneficial for the OER. Temperature-dependent magnetization measurements reveal favorable d-orbital configuration (high eg occupancy ≈ 1) and a low → high spin-state transition of the Co3+-ions, which are beneficial for the ORR in the alkaline medium. The influence of Cu-doping on the ORR activity of Co3O4 is additionally accounted in DFT calculations via interactions between solvent water molecules and oxygen vacancies. The application of the bifunctional Cu-doped (≤5%) Co3O4 electrocatalyst resulted in an aqueous Zn–air battery with promising power density (=84 mW/cm2), stable cyclability (over 210 cycles), and low charge/discharge overpotential (=0.92 V).    

    

* Pyrolysis-Free Coupling Strategy to Synthesize Two-Dimensional Oxygen Reaction Electrocatalysts for Rechargeable Zn-Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393370872
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4780694")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393370872"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393370872"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393370872"))][Get cited by]]

OpenAlex: https://openalex.org/W4393370872 (Open access: False)
    
[[https://openalex.org/A5051365489][Pengfei Xie]], [[https://openalex.org/A5025509682][Hao Hu]], [[https://openalex.org/A5078156613][Lingzhe Fang]], [[https://openalex.org/A5020582501][Xiaohua Yu]], [[https://openalex.org/A5092768696][ju rog]], [[https://openalex.org/A5089516306][Xiaoyi Qiu]], [[https://openalex.org/A5041827917][Xiaofeng Wu]], [[https://openalex.org/A5065723594][Tao Li]], [[https://openalex.org/A5069700804][Minhua Shao]], [[https://openalex.org/A5080476738][Jincheng Li]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4780694 
     
No abstract    

    

* Impact of Applied Potential Range on Corrosion Behavior of Stainless Steel Oxygen Evolution Electrode Under Potential Cycle Loading  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393371182
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4780625")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393371182"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393371182"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393371182"))][Get cited by]]

OpenAlex: https://openalex.org/W4393371182 (Open access: False)
    
[[https://openalex.org/A5068147445][Naoto Todoroki]], [[https://openalex.org/A5074172776][Toshimasa Wadayama]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4780625 
     
No abstract    

    

* Oxygen evolution reaction enhancement enabled by a Ni-doped cobalt-based phosphate electrode with hierarchical pore structures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393373481
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.307")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393373481"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393373481"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393373481"))][Get cited by]]

OpenAlex: https://openalex.org/W4393373481 (Open access: False)
    
[[https://openalex.org/A5041484012][Jian Huang]], [[https://openalex.org/A5033647472][Jun Li]], [[https://openalex.org/A5015743959][Run Liu]], [[https://openalex.org/A5083046241][Ruiqiong Wang]], [[https://openalex.org/A5065115274][Zhixun Luo]], [[https://openalex.org/A5013946471][Peng Zou]], [[https://openalex.org/A5056532764][Xun Zhu]], [[https://openalex.org/A5037303341][Qiang Liao]], International journal of hydrogen energy. 64(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.307 
     
No abstract    

    

* An Efficient Photocatalytic Oxygen Evolution System with the Coupling of Polyoxometalates with Bismuth Vanadate  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393379318
:TOPICS: Polyoxometalate Clusters and Materials, Nanomaterials with Enzyme-Like Characteristics, Innovations in Organic Synthesis Reactions
:PUBLICATION_DATE: 2024-03-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14040236")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393379318"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393379318"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393379318"))][Get cited by]]

OpenAlex: https://openalex.org/W4393379318 (Open access: True)
    
[[https://openalex.org/A5022993483][Boon Chong Ong]], [[https://openalex.org/A5046137696][Teik‐Thye Lim]], [[https://openalex.org/A5026626040][Can Xue]], [[https://openalex.org/A5033949863][Zhili Dong]], Catalysts. 14(4)] 2024. https://doi.org/10.3390/catal14040236  ([[https://www.mdpi.com/2073-4344/14/4/236/pdf?version=1711922265][pdf]])
     
In this work, a coupling system consisting of bismuth vanadate (BiVO4) and cobalt-based polyoxometalates (Co-POMs) was developed to enhance the oxygen evolution reaction. Crystallization-driven self-assembly and the wet chemical synthesis method were deployed in synthesizing Co-POMs and monoclinic–tetragonal mixed–phase BiVO4, respectively. The introduction of Co-POMs into a BiVO4-containing mixture significantly enhanced the water oxidation reaction, with a more than twofold increment in the total amount of oxygen evolved. For instance, 461.2 µmol of oxygen was evolved from the system containing 20 mg of Co-POMs compared to 195 µmol of oxygen produced from a pristine BiVO4 system. This extraordinary improvement in the oxygen evolution reaction indicates the existence of a positive synergic effect between BiVO4 and Co-POMs, in which Co-POMs could act as effective cocatalysts to extract photogenerated charge carriers generated by BiVO4 and improve the charge transfer process. However, the amount of oxygen produced was slightly reduced to 440.7 µmol with an increase in AgNO3 loading from 30 mg to 60 mg. This unforeseen phenomenon could be elucidated by the shielding effect of silver particles, in which a higher AgNO3 loading led to a more prominent shielding effect. The presence of silver nanoparticles on post-reaction BiVO4 was confirmed by TEM and XPS analysis. This newly established process scheme provides an insight into the development of an efficient photocatalytic oxygen evolution system in realizing future commercial applications toward green energy production.    

    

* Feco5/Nitrogen Doped Carbon As An Efficient Bifunctional Oxygen Electrocatalyst for Zn−Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393386021
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4780082")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393386021"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393386021"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393386021"))][Get cited by]]

OpenAlex: https://openalex.org/W4393386021 (Open access: False)
    
[[https://openalex.org/A5023589886][Jingyu Wang]], [[https://openalex.org/A5058290024][Tianai Zhang]], [[https://openalex.org/A5027109186][Simin He]], [[https://openalex.org/A5047224338][Chunwen Sun]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4780082 
     
No abstract    

    

* Stabilization of Lattice Oxygen Evolution Reactions in Oxophilic Ce‐mediated Bi/BiCeO1.8H Electrocatalysts for Efficient Anion Exchange Membrane Water Electrolyzers  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393387961
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202314211")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393387961"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393387961"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393387961"))][Get cited by]]

OpenAlex: https://openalex.org/W4393387961 (Open access: False)
    
[[https://openalex.org/A5059577219][Seunghwan Jo]], [[https://openalex.org/A5015120198][Jeong In Jeon]], [[https://openalex.org/A5040251435][Ki Hoon Shin]], [[https://openalex.org/A5007878766][L. Zhang]], [[https://openalex.org/A5091517291][Keon Beom Lee]], [[https://openalex.org/A5020219075][John Hong]], [[https://openalex.org/A5055241203][Jung Inn Sohn]], Advanced materials (Weinheim. Print). None(None)] 2024. https://doi.org/10.1002/adma.202314211 
     
Abstract The lattice oxygen mechanism (LOM) offers an efficient reaction pathway for oxygen evolution reactions (OERs) in energy storage and conversion systems. Owing to the involvement of active lattice oxygen that enhances electrochemical activity in this approach, addressing the structural and electrochemical stabilities of LOM materials is crucial. Therefore, it is important to devise effective strategies for activating lattice oxygen in such materials while minimizing material deformations and ion elution. Herein, a heterostructure (Bi/BiCeO 1.8 H) containing abundant under‐coordinated oxygen atoms having oxygen nonbonding states is synthesized by a simple electrochemical deposition method. Given the difference in reduction potentials between Bi and Ce, partially reduced Bi nanoparticles and surrounding under‐coordinated oxygen atoms are generated in BiCeO 1.8 H. It is found that the lattice oxygen can also be activated as a reactant of the OER when the valence state of Bi increases to Bi 5+ , increasing metal–oxygen covalency and that the oxophilic Ce 3+ / 4+ redox couple allows maintaining the Bi nanoparticles and surrounding under‐coordinated oxygen atoms by preventing over‐oxidation of Bi. As a demonstration of the practical applications, an anion exchange membrane water electrolyzer (AEMWE) with Bi/BiCeO 1.8 H as the anode is analyzed. The AEMWE exhibits a low cell voltage of 1.79 V even at a high practical current density of 1.0 A cm −2 . Furthermore, the cell performance remains significantly stable over 100 h with only a 2.2% increase in the initial cell voltage, demonstrating sustainable lattice oxygen redox. This article is protected by copyright. All rights reserved    

    

* Theoretically Insight into Co and S Pairs Dispersed on N‐Doped Graphene: Promising Bifunctional Electrocatalysts for Oxygen Reduction/Evolution Reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393388274
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adts.202400076")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393388274"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393388274"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393388274"))][Get cited by]]

OpenAlex: https://openalex.org/W4393388274 (Open access: True)
    
[[https://openalex.org/A5007613197][Ji Zhang]], [[https://openalex.org/A5088584503][Aimin Yu]], [[https://openalex.org/A5076345724][Dongsheng Li]], [[https://openalex.org/A5058308419][Chenghua Sun]], Advanced theory and simulations. None(None)] 2024. https://doi.org/10.1002/adts.202400076  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/adts.202400076][pdf]])
     
Abstract Single atom catalysts (SACs) are considered as efficient catalysts for hydrogen‐based energy conversion and storage because of their excellent catalytic performance for oxygen evolution reactions (OER) and oxygen reduction reactions (ORR). In the present work, a new concept of SACs is proposed with the capacity to form d ‐ p orbital hybridization. These computationally designed SACs contain a metal and non‐metal pair embedded in the N‐doped graphene framework (MX@N 6 ). Based on the overpotential evaluation by the first principle theory calculations, CoS@N 6 containing Co and S atom pair possessed a low overpotential of 0.37 V/0.29 V when used as a bifunctional ORR/OER catalyst. These overpotentials are much lower than Co@N 6 without S atom. The electronic structure analysis revealed that non‐metal atoms of the catalyst can regulate the electronic structure of active metal sites and facilitate the adsorption and charge transfer between intermediates and the catalyst resulting in enhanced catalytic performance. This work demonstrates an alternative way to further improve the catalytic activity of SACs by introducing a non‐metal atom that may shed light on the rational design of advanced SACs for ORR/OER with high efficiency and stability.    

    

* NiFe Catalysts for Oxygen Evolution Reaction: Is There an Optimal Thickness for Generating a Dynamically Stable Active Interface?  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393389421
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400286")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393389421"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393389421"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393389421"))][Get cited by]]

OpenAlex: https://openalex.org/W4393389421 (Open access: False)
    
[[https://openalex.org/A5051130087][Luca Ciambriello]], [[https://openalex.org/A5022148644][Ivano Alessandri]], [[https://openalex.org/A5007878932][Luca Gavioli]], [[https://openalex.org/A5023787065][Irene Vassalini]], ChemCatChem (Print). None(None)] 2024. https://doi.org/10.1002/cctc.202400286 
     
Here we investigated the dynamics of OER activity of NiFe (90/10) catalysts over 1000 potential sweep cycles as a function of their mass loading. Over twenty different films with mass loading in the 10 ng/cm2‐30 μg/cm2 range were deposited by Supersonic Cluster Beam Deposition (SCBD), allowing to study the progress of OER in sub‐monolayer, monolayer and multilayer regimes. Upon prolonged potential sweeps the electrocatalytic performances of multilayers decreased, while those of monolayers were significantly improved. The best balance in terms of catalytic efficiency and stability in working conditions is found for mass loadings corresponding to a NiFe monolayer, corresponding to a mass loading around 1 μg/cm2 and a thickness of about 3 nm.    

    

* Bifunctional activity and theoretical study of transition metal molybdates for hydrogen and oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393393474
:TOPICS: Electrocatalysis for Energy Conversion, Desulfurization Technologies for Fuels, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.254")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393393474"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393393474"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393393474"))][Get cited by]]

OpenAlex: https://openalex.org/W4393393474 (Open access: False)
    
[[https://openalex.org/A5026033742][Namita Dalai]], [[https://openalex.org/A5037335900][Manikandan Kandasamy]], [[https://openalex.org/A5006680940][Shraddhanjali Senapati]], [[https://openalex.org/A5087958993][Brahmananda Chakraborty]], [[https://openalex.org/A5032102667][Bijayalaxmi Jena]], International journal of hydrogen energy. 64(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.254 
     
Effective, sturdy and cheap electrocatalysts are extremely desirable for water electrolysis. In this work, transition metal molybdates (MMoO4, M = Fe, Co, Ni) with extraordinary oxygen evolution reaction (OER), and hydrogen evolution reaction (HER) in basic electrolyte solution was reported. β-Fe2(MoO4)3 catalyst exhibits better electrocatalytic performance and robustness for both HER and OER compared to NiMoO4 and CoMoO4. Theoretical study (DFT calculation) disclose that the Fe atoms increase the energy states near the Fermi level in β-Fe2(MoO4)3 which makes it more conductive leading to superior OER and HER activity. Compared to CoMoO4 and NiMoO4, β-Fe2(MoO4)3 have well defined multiple Mo 4d orbitals at the conduction band. These are empty states in conduction band, ready to receive the electrons. Further, the computed overpotential values for NiMoO4, CoMoO4, and β-Fe2(MoO4)3 surfaces follow the trend, β-Fe2(MoO4)3 < NiMoO4 < CoMoO4, corroborating with the experimental results.    

    

* Boosting the electrocatalytic activity of NdBaCo2O5+ via calcium co-doping as bifunctional oxygen electrodes for reversible solid oxide cells  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393397416
:TOPICS: Solid Oxide Fuel Cells, Magnetocaloric Materials Research, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131625")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393397416"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393397416"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393397416"))][Get cited by]]

OpenAlex: https://openalex.org/W4393397416 (Open access: False)
    
[[https://openalex.org/A5008479546][Fangjun Jin]], [[https://openalex.org/A5050452321][Jiangxin Li]], [[https://openalex.org/A5026409460][Yuan Gao]], [[https://openalex.org/A5055875257][Wenjing Zhang]], [[https://openalex.org/A5010315884][Yunfeng Tian]], [[https://openalex.org/A5026511504][Fangsheng Liu]], [[https://openalex.org/A5055814385][Xinxin Wang]], [[https://openalex.org/A5036714477][Cheng Zhai]], [[https://openalex.org/A5020303601][Yihan Ling]], Fuel (Guildford). 368(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131625 
     
The oxygen electrode of the solid oxide cells (SOCs) operates under an oxidizing atmosphere. Lattice shrinkage in a high oxygen partial pressure environment results in cation misalignment, leading to a decline in performance. Addressing the drawbacks associated with A-site cation mismatch in LnBaCo2O5+δ double perovskite oxides for reversible solid oxide cells (RSOCs) oxygen electrodes, a novel calcium ion co-doping strategy is proposed. This approach effectively mitigates A-site cation segregation and enhances stability. The glycine-nitrate method was employed to synthesize Nd0.8Ca0.2Ba1−xCaxCo2O5+δ (x = 0–0.2) layered double perovskites oxides co-doped with calcium ions, denoted as NCBCC. NCBCC exhibits excellent compatibility with commonly used electrolytes. The doping of calcium co-doped in NdBaCo2O5+δ decreases the thermal expansion coefficient and improves the electron transfer characteristics. The sample with x = 0.1 exhibited an area-specific resistance (ASR) of 0.024 Ω cm2 when operated at a temperature of 800 °C in air. In the solid oxide fuel cell mode, employing x = 0.1 as an oxygen electrode, the maximum power density achieved was 766 mW cm−2 at 800 °C. In the solid oxide electrolysis cell mode, operating with CO2 and steam at an electrolysis voltage of 1.5 V and a temperature of 800 °C, the corresponding current densities were −1.51 and −1.85 A cm−2, respectively. The incorporation of calcium ions into layered perovskite oxides offers a promising strategy to enhance the performance of oxygen electrodes in RSOCs.    

    

* Amorphous/Crystalline Phases Mixed Nanosheets Array Rich in Oxygen Vacancies Boost Oxygen Evolution Reaction of Spinel Oxides in Alkaline Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393403940
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202401504")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393403940"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393403940"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393403940"))][Get cited by]]

OpenAlex: https://openalex.org/W4393403940 (Open access: False)
    
[[https://openalex.org/A5060002817][Ying Liu]], [[https://openalex.org/A5044098602][Liyang Xiao]], [[https://openalex.org/A5086327328][Haiwen Tan]], [[https://openalex.org/A5033881111][Jingtong Zhang]], [[https://openalex.org/A5025368262][Cunku Dong]], [[https://openalex.org/A5044301848][Hui Liu]], [[https://openalex.org/A5031056448][Xi‐Wen Du]], [[https://openalex.org/A5081819768][Jing Yang]], Small (Weinheim. Print). None(None)] 2024. https://doi.org/10.1002/smll.202401504 
     
Abstract As promising oxygen evolution reaction (OER) catalysts, spinel‐type oxides face the bottleneck of weak adsorption for oxygen‐containing intermediates, so it is challenging to make a further breakthrough in remarkably lowering the OER overpotential. In this study, a novel strategy is proposed to substantially enhance the OER activity of spinel oxides based on amorphous/crystalline phases mixed spinel FeNi 2 O 4 nanosheets array, enriched with oxygen vacancies, in situ grown on a nickel foam (NF). This unique architecture is achieved through a one‐step millisecond laser direct writing method. The presence of amorphous phases with abundant oxygen vacancies significantly enhances the adsorption of oxygen‐containing intermediates and changes the rate‐determining step from OH*→O* to O*→OOH*, which greatly reduces the thermodynamic energy barrier. Moreover, the crystalline phase interweaving with amorphous domains serves as a conductive shortcut to facilitate rapid electron transfer from active sites in the amorphous domain to NF, guaranteeing fast OER kinetics. Such an anodic electrode exhibits a nearly ten fold enhancement in OER intrinsic activity compared to the pristine counterpart. Remarkably, it demonstrates record‐low overpotentials of 246 and 315 mV at 50 and 500 mA cm −2 in 1 m KOH with superior long‐term stability, outperforming other NiFe‐based spinel oxides catalysts.    

    

* CoP nanoparticles embedded in N-doped carbon for highly efficient oxygen evolution reaction electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393410258
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.136405")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393410258"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393410258"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393410258"))][Get cited by]]

OpenAlex: https://openalex.org/W4393410258 (Open access: False)
    
[[https://openalex.org/A5006592632][Zewu Zhang]], [[https://openalex.org/A5003757306][Yifan Dai]], [[https://openalex.org/A5094305508][Chen Lijingxian]], [[https://openalex.org/A5094305509][Bai Jiakai]], [[https://openalex.org/A5027886921][卜小海 Bu Xiaohai]], [[https://openalex.org/A5022583323][Jiehua Bao]], Materials letters (General ed.). None(None)] 2024. https://doi.org/10.1016/j.matlet.2024.136405 
     
No abstract    

    

* Oxidized phosphorus linking promotes the activity of a cobalt molecular assembly for electrochemical oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393447058
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2024.118237")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393447058"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393447058"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393447058"))][Get cited by]]

OpenAlex: https://openalex.org/W4393447058 (Open access: False)
    
[[https://openalex.org/A5027643367][Jian Yang]], [[https://openalex.org/A5080098919][Runze He]], [[https://openalex.org/A5063026386][Jiong Wang]], Journal of electroanalytical chemistry (1992). None(None)] 2024. https://doi.org/10.1016/j.jelechem.2024.118237 
     
Molecular assemblies represent a classical type of active electrocatalysts for oxygen evolution reaction (OER), while the practical application is limited by the relatively low electrical conductivity. Herein, a cobalt molecular assembly was synthesized and supported by a conductive phosphorus doped graphene. It served as a potential OER electrocatalyst by affording a current density of 10 mA cm−2 at a small overpotential of 390 mV, and the turnover frequency of cobalt sites was increased by 21.5 times comparing to the assembly supported by the pristine graphene. Our observations unveil that the potential linking of oxidized phosphorus atoms in the carbon matrix is mainly responsible for the high activity of cobalt molecular assembly. The overall OER catalytic cycle was analyzed by in situ attenuated total reflectance-surface enhanced infrared absorption spectroscopy, suggesting that the formation of *OOH species on the cobalt sites could be critical for the final evolution of oxygen. These results open a potential avenue into the exploration of highly active OER electrocatalysts toward replacing the noble metals based electrocatalysts.    

    

* Nickel engineered in-situ graphitization of carbon derived from bagasse: A robust and highly efficient catalyst for oxygen evolution reaction and water remediation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393489185
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jclepro.2024.142002")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393489185"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393489185"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393489185"))][Get cited by]]

OpenAlex: https://openalex.org/W4393489185 (Open access: False)
    
[[https://openalex.org/A5052695822][S Akhila]], [[https://openalex.org/A5054975537][Sayali Ashok Patil]], [[https://openalex.org/A5000186978][Sai Rashmi M.]], [[https://openalex.org/A5038200205][Arvind H. Jadhav]], [[https://openalex.org/A5070896864][Akshaya K. Samal]], [[https://openalex.org/A5032252451][Rupesh S. Devan]], [[https://openalex.org/A5056852381][Manav Saxena]], Journal of cleaner production. None(None)] 2024. https://doi.org/10.1016/j.jclepro.2024.142002 
     
Upcycling bagasse into functional materials such as electrocatalysts and adsorbents is crucial for renewable energy and water remediation. The present work accounts for preparing in-situ nickel-engineered graphitic-layered carbon (Ni@GLC) using different loading of Ni2+ on bagasse waste by carbonization technique. Various spectro-analytical and physiochemical techniques are used to characterize and elucidate the plausible mechanism of in situ carbonization and grafting of Ni on GLC. Initially, the Ni@GLC was employed as an electrocatalyst for OER reaction under ambient conditions. Results revealed that effective nickel loading Ni@GLC-2 showed enhanced electrocatalytic activity with a Tafel slope of 86 mV dec−1 and ɳ of 284 mV (vs. RHE) to drive j10 mA cm−2 in an alkaline medium (pH 13). The material showed 12 h chronoamperometry (CA) stability. Further, in the case of water remediation, Ni@GLC-2 was employed as an adsorbent through the adsorption technique using Methy orange (MO), Amido black (AB), and regular hair dye (HD) as emerging pollutants. Reaction variables such as the effect of pH and dosage study were investigated and discussed. Results revealed that time-dependent kinetic data was better fitted for the pseudo-second-order model, and isotherm studies with the Langmuir model attained qm capacity of 2232 and 617 mg g−1 for MO and AB, respectively. Interestingly, 96 % removal of Garnier color naturals HD was achieved. Based on the results obtained from ζ-potential and FT-IR analysis support the interaction between the dye and Ni@GLC-2. We believe this work opens new outcomes for designing and synthesizing efficient electrocatalysts and sorbents for energy development and environmental conservation.    

    

* ZIF-67-Derived CoFe2O4/NiCo2O4@NC/CC with Oxygen-Enriched Vacancy for High-Performance Electrocatalyst toward Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393515332
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.energyfuels.4c00453")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393515332"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393515332"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393515332"))][Get cited by]]

OpenAlex: https://openalex.org/W4393515332 (Open access: False)
    
[[https://openalex.org/A5010826836][Jianhua Wu]], [[https://openalex.org/A5088228062][Xueliang Sun]], [[https://openalex.org/A5030641799][Haosen Chen]], [[https://openalex.org/A5021718280][Siwei Guo]], [[https://openalex.org/A5026983787][Dong Hou]], [[https://openalex.org/A5073577917][Deyong Wang]], [[https://openalex.org/A5053633521][Huihua Wang]], Energy & fuels (Print). None(None)] 2024. https://doi.org/10.1021/acs.energyfuels.4c00453 
     
Oxygen evolution reaction (OER) impedes the electrochemical water splitting for H2 production, ascribing to the depressed kinetics of the four proton-coupled transfer process. Transition metal oxides, especially bimetallic oxides, have been proven to be promising OER electrocatalysts due to their part unoccupied d-band characteristics. More interestingly, oxygen vacancies (Ov) easily constructed in transition metal oxides can modulate the electron structures and thereby boost the OER performance. However, most synthesized processes involving oxygen vacancy engineering, such as atom dopant, chemical/electrochemical reduction, and H2/Ar-dependent calcination, are energy-intensive and time-consuming, largely hampering their commercial applications. Herein, we suggest a simple and facile strategy for fabricating double spinel oxides with abundant oxygen vacancies by calcinating Ni/Fe@ZIF-67/CC precursor under a nonoxidation condition. The obtained Ov-CF1N2O@NC/CC-550 with vast oxygen vacancies exhibits excellent OER performance, representing a lower overpotential of 185 mV at 10 mA cm–2, smaller Tafel slope of 47.3 mV dec–1, as well as faster interface reaction kinetics (Rct = 0.7336). Theoretical calculations further confirm that the excellent electrochemical activity strongly corresponds to the lower d-band center of active sites on the Ov-CoFe2O4 (311) model and decreased reaction Gibbs energy barrier. The work might shed light on oxygen vacancy engineering via a simple and facile strategy and inspire a smart design of multimetallic oxide electrocatalysts with high OER performance.    

    

* Iron in the Presence of Iridium for Oxygen-Evolution Reaction under Alkaline Conditions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393527642
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Chemistry of Actinide and Lanthanide Elements
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.4c00069")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393527642"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393527642"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393527642"))][Get cited by]]

OpenAlex: https://openalex.org/W4393527642 (Open access: False)
    
[[https://openalex.org/A5020471931][Mohammad Saleh Ali Akbari]], [[https://openalex.org/A5047020055][Subhajit Nandy]], [[https://openalex.org/A5063597709][Keun Hwa Chae]], [[https://openalex.org/A5067202056][P. Aleshkevych]], [[https://openalex.org/A5047640712][Mohammad Mahdi Najafpour]], ACS applied energy materials. None(None)] 2024. https://doi.org/10.1021/acsaem.4c00069 
     
The potential of the oxygen-evolution reaction (OER) to serve as a vital source of electrons for reducing water, carbon dioxide, and ammonia is an area of intense research. Among the numerous catalysts investigated for the OER, Ir compounds have emerged as particularly promising candidates. A notable highlight of this study is the concurrent OER activity of both Ir and Fe. Remarkably, Ir independently exhibits high OER activity, even at exceedingly low overpotentials, establishing its distinctiveness among other metal oxides. Under alkaline conditions, the presence of both Fe and Ir (hydr)oxides in OER systems introduces complexity, given that Fe (hydr)oxides are also known for their efficiency in the OER. This combination of elements creates a multifaceted reaction environment, where the unique properties of each component interact, influencing the overall OER process. In this study, the focus is on investigating the OER process on an Ir wire in an alkaline environment (with pH 13 and 14) in the presence of K2FeO4. To gain a comprehensive understanding of the reaction, various techniques, such as electrochemical methods, X-ray diffraction (XRD), electron paramagnetic resonance (EPR), X-ray absorption spectroscopy (XAS), Raman spectroscopy, transmission electron microscopy (TEM), and scanning electron microscopy (SEM), were employed. Following an in-depth investigation and detailed analysis of the interaction between K2FeO4 and an Ir wire, it was observed that the activity of the OER increased at overpotentials exceeding 320 mV. The observed improvement was limited to cases where Fe species had deposited on the surface of the Ir wire. The Tafel slopes were found to be 196.10 (149.20) and 102.16 (56.30) mV/decade for the Ir electrode in 0.10 M (1.0 M) KOH, in the absence and presence of K2FeO4, respectively. XAS analysis revealed the presence of the FeHyOx species on the surface of IrO2. These experiments indicate that Fe and Ir sites can independently catalyze the OER without exhibiting any synergistic interaction between them.    

    

* Constructing interlaced network structure by grain boundary corrosion methods on CrCoNiFe alloy for high-performance oxygen evolution reaction and urea oxidation reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393531286
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jmst.2024.01.096")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393531286"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393531286"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393531286"))][Get cited by]]

OpenAlex: https://openalex.org/W4393531286 (Open access: False)
    
[[https://openalex.org/A5029142691][Qiancheng Liu]], [[https://openalex.org/A5079678680][Feng Zhao]], [[https://openalex.org/A5077024465][Xulin Yang]], [[https://openalex.org/A5000165978][Jie Zhu]], [[https://openalex.org/A5048979833][Sudong Yang]], [[https://openalex.org/A5078143614][Lin Chen]], [[https://openalex.org/A5061523947][Peng Zhao]], [[https://openalex.org/A5083228477][Hongtao Wang]], [[https://openalex.org/A5052441498][Qian Zhang]], Journal of Materials Science and Technology (Shenyang). None(None)] 2024. https://doi.org/10.1016/j.jmst.2024.01.096 
     
Corrosion engineering is an effective way to improve the oxygen evolution reaction (OER) activity of alloys. However, the impact of grain boundary corrosion on the structure and electrochemical performance of alloy is still unknown. Herein, the vacuum arc-melted CrCoNiFe alloys with interlaced network structures via grain boundary corrosion methods were fabricated. The grain boundaries that existed as defects were severely corroded and an interlaced network structure was formed, promoting the exposure of the active site and the release of gas bubbles. Besides, the (oxy)hydroxides layer (25 nm) on the surface could act as the true active center and improve the surface wettability. Benefiting from the unique structure and constructed surface, the CrCoNiFe-12 affords a high urea oxidation reaction (UOR) performance with the lowest overpotential of 250 mV at 10 mA/cm2 in 1 M KOH adding 0.33 M urea. The CrCoNiFe-12||Pt only required a cell voltage of 1.485 V to afford 10 mA/cm2 for UOR and long-term stability of 100 h at 10 mA/cm2 (27.6 mV decrease). These findings offer a facile strategy for designing bulk multiple-principal-element alloy electrodes for energy conversion.    

    

* Photo‐promoted rapid reconstruction induced alterations in active site of Ag@amorphous NiFe hydroxides for enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393549861
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cey2.543")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393549861"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393549861"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393549861"))][Get cited by]]

OpenAlex: https://openalex.org/W4393549861 (Open access: True)
    
[[https://openalex.org/A5075989623][Zhi Cai]], [[https://openalex.org/A5016050256][Mingyuan Xu]], [[https://openalex.org/A5064435064][Yanhong Li]], [[https://openalex.org/A5033188755][Xinyan Zhou]], [[https://openalex.org/A5064074240][Kai Yin]], [[https://openalex.org/A5019531815][Lidong Li]], [[https://openalex.org/A5084237401][Baohua Jia]], [[https://openalex.org/A5015153086][Lin Guo]], [[https://openalex.org/A5059893553][Hewei Zhao]], Carbon energy. None(None)] 2024. https://doi.org/10.1002/cey2.543  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cey2.543][pdf]])
     
Abstract The dynamic surface self‐reconstruction behavior in local structure correlates with oxygen evolution reaction (OER) performance, which has become an effective strategy for constructing the catalytic active phase. However, it remains a challenge to understand the mechanisms of reconstruction and to accomplish it fast and deeply. Here, we reported a photo‐promoted rapid reconstruction (PRR) process on Ag nanoparticle‐loaded amorphous Ni‐Fe hydroxide nanosheets on carbon cloth for enhanced OER. The photogenerated holes generated by Ag in conjunction with the anodic potential contributed to a thorough reconstruction of the amorphous substrate. The valence state of unsaturated coordinated Fe atoms, which serve as active sites, is significantly increased, while the corresponding crystalline substrate shows little change. The different structural evolutions of amorphous and crystalline substrates during reconstruction lead to diverse pathways of OER. This PRR utilizing loaded noble metal nanoparticles can accelerate the generation of active species in the substrate and increase the electrical conductivity, which provides a new inspiration to develop efficient catalysts via reconstruction strategies.    

    

* Data from ''From Small-Area Observations to Insight: Surface-Feature-Extrapolation of Anodes for Alkaline Oxygen Evolution Reaction''  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393550398
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-01-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.10512766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393550398"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393550398"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393550398"))][Get cited by]]

OpenAlex: https://openalex.org/W4393550398 (Open access: True)
    
[[https://openalex.org/A5041070012][Abhi Jain]], [[https://openalex.org/A5025930612][Vineetha Vinayakumar]], [[https://openalex.org/A5004899785][André Olean‐Oliveira]], [[https://openalex.org/A5006249717][Christian Marcks]], [[https://openalex.org/A5052683041][Mohit Chatwani]], [[https://openalex.org/A5057402984][Anna K. Mechler]], [[https://openalex.org/A5082583063][Corina Andronescu]], [[https://openalex.org/A5062824606][Doris Segets]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2024. https://doi.org/10.5281/zenodo.10512766 
     
Data used in publication called 'From Small-Area Observations to Insight: Surface-Feature-Extrapolation of Anodes for Alkaline Oxygen Evolution Reaction' in ChemCatChem journal.    

    

* Electrodeposited CrMnFeCoNi Oxy-carbide film and effect of selective dissolution of Cr on oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393550831
:TOPICS: Electrocatalysis for Energy Conversion, Electrodeposition and Composite Coatings, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jmst.2024.02.068")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393550831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393550831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393550831"))][Get cited by]]

OpenAlex: https://openalex.org/W4393550831 (Open access: False)
    
[[https://openalex.org/A5020470912][Tian Xia]], [[https://openalex.org/A5058308419][Chenghua Sun]], [[https://openalex.org/A5001117275][Rongguang Wang]], Journal of Materials Science and Technology (Shenyang). None(None)] 2024. https://doi.org/10.1016/j.jmst.2024.02.068 
     
High entropy compounds were proven to exhibit excellent catalytic activity. Here, a series of amorphous CrMnFeCoNi Oxy-carbide films were successfully synthesized by one-step electrodeposition. As demonstrated, the film presented superior electrocatalytic activity for oxygen evolution reaction (OER) with an overpotential of 295 mV at a current density of 10 mA/cm2. Uniquely, selective dissolution of Chromium (Cr) was observed, which increased the catalytic activity and showed high stability under a large current density of up to 400 mA/cm2. Cr dissolution not only increased the surface area but also improved the conductivity due to newly formed metal-metal bonding, promoting electron transfer and improving OER performance. As revealed by density functional theory (DFT) calculations, Cr-dissolution mediates the bonding of OER intermediates over surface active sites and ultimately reduces OER overpotential. The one-step electrodeposition method and the micro-dissolution mechanism provided a potential way to design and prepare high entropy compound electrodes, aiming to achieve efficient water electrolysis.    

    

* Transition Metal Selenides for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393852952
:TOPICS: Electrocatalysis for Energy Conversion, Thin-Film Solar Cell Technology, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-04-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ente.202301574")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393852952"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393852952"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393852952"))][Get cited by]]

OpenAlex: https://openalex.org/W4393852952 (Open access: False)
    
[[https://openalex.org/A5056646047][Zuoqiang Wu]], Energy technology (Weinheim. Print). None(None)] 2024. https://doi.org/10.1002/ente.202301574 
     
Oxygen evolution reaction (OER) is essential to the water splitting and CO 2 reduction reactions, while this reaction is kinetically sluggish and demands the efficient electrocatalyst. Transition metal selenides (TMSes) have gained greater attention as nonprecious metal‐based electrocatalysts due to their low cost, earth abundance, and high efficiency. Typically, TMSe can exhibit superior OER activity to their counterparts such as hydroxides/oxyhydroxides and sulfides. As such, their unique way to boost the catalytic activity is intriguing to researchers and many studies have been recently carried out. The last decades have witnessed the rapid development of TMSe‐based electrocatalysts in design and preparation for OER. However, there is still no exclusive review summarizing the recent development of this material for OER electrocatalysis. Herein, this article underscores the significant promise of TMSes in advancing the field of high‐performance OER electrocatalysts. The research progress is summarized and the importance of strategies to improve the performance of selenide electrodes including multimetal composite, hybrid composite with carbonaceous materials, morphological engineering, heterostructure engineering, and vacancies engineering is emphasized. Finally, the future challenges and opportunities concerning the improvement of TMSe electrocatalysts are outlined, which are essential for their further application in electrochemical energy conversion.    

    

* Supplementary Data for 'The electron-proton bottleneck of photosynthetic oxygen evolution'  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393546533
:TOPICS: Molecular Mechanisms of Photosynthesis and Photoprotection
:PUBLICATION_DATE: 2023-03-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.7681840")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393546533"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393546533"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393546533"))][Get cited by]]

OpenAlex: https://openalex.org/W4393546533 (Open access: True)
    
[[https://openalex.org/A5027659709][Paul Greife]], [[https://openalex.org/A5064578696][Matthias Schönborn]], [[https://openalex.org/A5054018303][Holger Dau]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2023. https://doi.org/10.5281/zenodo.7681840 
     
Supplementary data for the publication: 'The electron-proton bottleneck of photosynthetic oxygen evolution', Greife et al. Heat_Artefact_Spectrum.xlsx Spectrum assigned to rapid heating by laser-flash excitation of high-activity Photosystem II membrane particles. This spectrum was used for heat artefact correction of the step-scan data set. The first column is the wavenumber in cm-1, the second column the absorption in arbitrary OD units. Log_Averaged_Interferograms.xlsx Averaged time-resolved FTIR interferograms recorded before and after the application of a saturating excitation flash to high activity Photosystem II membrane particles from spinach. In total 10 sequential flashes were applied. The first column is the time in milliseconds. Remaining columns are the mirror positions of the phase-corrected interferograms with the centerburst shifted to the first position. Amplitude is in arbitrary units. Individual columns correspond to individual time courses at the respective mirror positions. Rows corresponds to interferograms at the respective time. The data for each of the 10 flashes is provided in a separate spreadsheet, which is accordingly labeled. The mirror positions were chosen such that after Fourier transformation the wavenumber range of the resulting spectra corresponds to 929.33 cm-1 to 1858.67 cm-1 , with data points equally spaced on a wavenumber axis.    

    

* STUDY ON THE REACTION OF OXYGEN EVOLUTION ON PbO2 ELECTRODE BY MEANS OF A.C.IMPEDANOE MEASUREMENT  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393910007
:TOPICS: On-line Monitoring of Wastewater Quality
:PUBLICATION_DATE: 1983-12-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3724/j.issn.1000-0518.1983.1.8793")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393910007"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393910007"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393910007"))][Get cited by]]

OpenAlex: https://openalex.org/W4393910007 (Open access: True)
    
[[https://openalex.org/A5032336798][Xuejuan Gao]], [[https://openalex.org/A5069630060][Yi Shi]], [[https://openalex.org/A5066747947][Haoyu Zhang]], [[https://openalex.org/A5050613147][Yunlong Wang]], [[https://openalex.org/A5045309022][Zhenyu Zhang]], Yingyong huaxue. 0(1)] 1983. https://doi.org/10.3724/j.issn.1000-0518.1983.1.8793  ([[https://www.sciengine.com/doi/pdfView/D0F6DB0FC98941D2AB997B334A1A490D][pdf]])
     
The anodic reaction of oxygen evolution on PbO2 electrode was studied by A. C. impedance measurement. The Faradaic. resistance Rt,double layer capacitance Cd adsorption resistance Ra and adsorption capacitance Ca were determined by analyzing the impedance spectra with microcomputer curve-fitting method. The rate-controlling step of the reaction was considered to be (OH)ad+H2O→(O)ad+H3O+e-. The relation between Cd, Ca.and OH-ion concentration was discussed in view of the adsorption effect.    

    

* Data for: Manganese Dissolution in alkaline medium with and without concurrent oxygen evolution in LiMn2O4  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393739103
:TOPICS: Battery Recycling and Rare Earth Recovery
:PUBLICATION_DATE: 2023-12-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.10377481")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393739103"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393739103"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393739103"))][Get cited by]]

OpenAlex: https://openalex.org/W4393739103 (Open access: True)
    
[[https://openalex.org/A5068195942][Marcel Risch]], [[https://openalex.org/A5025861092][Omeshwari Yadorao Bisen]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2023. https://doi.org/10.5281/zenodo.10377481 
     
Raw data and processed data shown in figures of the publication titled: "Manganese Dissolution in alkaline medium with and without concurrent oxygen evolution in LiMn2O4" DOI: 10.1039/D3YA00434A by Omeshwari Yadorao Bisen,[a,b] Max Baumung,[a,b] Michael Tatzel,[c] Cynthia A. Volkert[b] and Marcel Risch[a,b] [a] Dr. Omeshwari Yadorao Bisen, Dr. Max Baumung, Dr. Marcel RischNachwuchsgruppe Gestaltung des SauerstoffentwicklungsmechanismusHelmholtz-Zentrum Berlin für Materialien und Energie GmbHHahn-Meitner-Platz 1, 14109 BerlinE-mail: marcel.risch@helmholtz-berlin.de [b] Dr. Omeshwari Yadorao Bisen, Dr. Max Baumung, Prof. Dr. Cynthia A. Volkert, Dr. Marcel RischInstitut für Material PhysikGeorg-August-Universität GöttingenFriedrich-Hund-Platz 1, 37085 Göttingen [c] Prof. Dr. Michael TatzelAbteilung Sedimentologie und UmweltgeologieGeorg-August-Universität GöttingenGoldschmidtstr. 3, 37077 Göttingen    

    

* Data for: Manganese Dissolution in alkaline medium with and without concurrent oxygen evolution in LiMn2O4  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393828218
:TOPICS: Battery Recycling and Rare Earth Recovery
:PUBLICATION_DATE: 2023-12-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.10377482")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393828218"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393828218"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393828218"))][Get cited by]]

OpenAlex: https://openalex.org/W4393828218 (Open access: True)
    
[[https://openalex.org/A5068195942][Marcel Risch]], [[https://openalex.org/A5025861092][Omeshwari Yadorao Bisen]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2023. https://doi.org/10.5281/zenodo.10377482 
     
Raw data and processed data shown in figures of the publication titled: "Manganese Dissolution in alkaline medium with and without concurrent oxygen evolution in LiMn2O4" DOI: 10.1039/D3YA00434A by Omeshwari Yadorao Bisen,[a,b] Max Baumung,[a,b] Michael Tatzel,[c] Cynthia A. Volkert[b] and Marcel Risch[a,b] [a] Dr. Omeshwari Yadorao Bisen, Dr. Max Baumung, Dr. Marcel RischNachwuchsgruppe Gestaltung des SauerstoffentwicklungsmechanismusHelmholtz-Zentrum Berlin für Materialien und Energie GmbHHahn-Meitner-Platz 1, 14109 BerlinE-mail: marcel.risch@helmholtz-berlin.de [b] Dr. Omeshwari Yadorao Bisen, Dr. Max Baumung, Prof. Dr. Cynthia A. Volkert, Dr. Marcel RischInstitut für Material PhysikGeorg-August-Universität GöttingenFriedrich-Hund-Platz 1, 37085 Göttingen [c] Prof. Dr. Michael TatzelAbteilung Sedimentologie und UmweltgeologieGeorg-August-Universität GöttingenGoldschmidtstr. 3, 37077 Göttingen    

    

* Oxygen evolution reaction catalysis for energy efficient CO2 reduction devices  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393399933
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2021-10-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393399933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393399933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393399933"))][Get cited by]]

OpenAlex: https://openalex.org/W4393399933 (Open access: False)
    
[[https://openalex.org/A5089324708][Adèle Peugeot]], HAL (Le Centre pour la Communication Scientifique Directe). None(None)] 2021. None 
     
No abstract    

    

* Research Progress of High-Entropy Oxides as Oxygen Evolution Reaction Catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393566072
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-04-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.energyfuels.3c05202")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393566072"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393566072"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393566072"))][Get cited by]]

OpenAlex: https://openalex.org/W4393566072 (Open access: False)
    
[[https://openalex.org/A5083026796][Qi Zhang]], [[https://openalex.org/A5019173699][Jingbi You]], [[https://openalex.org/A5005001168][Zhen Xi]], [[https://openalex.org/A5055446747][Baolin Yi]], [[https://openalex.org/A5031769026][Yao Zhao]], [[https://openalex.org/A5063160067][Yuhui Li]], [[https://openalex.org/A5007642500][Hangzhou Zhang]], Energy & fuels (Print). None(None)] 2024. https://doi.org/10.1021/acs.energyfuels.3c05202 
     
Equimolar or nearly molar mixtures of five or more metals are used to create high-entropy oxides (HEOs). HEOs also possess the kinetic slow diffusion effect, structural lattice distortion, the thermodynamic high-entropy effect, and the cocktail effect. Consequently, a growing number of scientists are investigating high-entropy oxides. High active site density, low overpotential, and entropic stabilization effects are the main reasons why HEOs now show good electrocatalytic oxygen evolution reaction. However, the complexity of the elemental composition, organization, and surface morphology of high-entropy oxides limits the use of HEOs. The development of HEOs and the mechanisms behind OER are reviewed in this work, along with a description of the OER response pathways and evaluation standards. The OER performance of HEOs with diverse organizational structures is reviewed in this research because HEOs come in a variety of kinds. Additionally, when HEOs are utilized as carriers, the trend of OER performance is examined. Lastly, potential future development problems and opportunities for HEO electrocatalysts are discussed.    

    

* The formation of unsaturated IrOx in SrIrO3 by cobalt-doping for acidic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393928569
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-46801-y")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393928569"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393928569"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393928569"))][Get cited by]]

OpenAlex: https://openalex.org/W4393928569 (Open access: True)
    
[[https://openalex.org/A5069491797][Jiawei Zhao]], [[https://openalex.org/A5061211337][Kaihang Yue]], [[https://openalex.org/A5069849278][Hong Zhang]], [[https://openalex.org/A5033944069][Shuyin Wei]], [[https://openalex.org/A5071157860][Jiawei Zhu]], [[https://openalex.org/A5052077971][Dongdong Wang]], [[https://openalex.org/A5018082870][Junze Chen]], [[https://openalex.org/A5043217345][V. Yu. Fominski]], [[https://openalex.org/A5090484465][Gao‐Ren Li]], Nature communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-46801-y  ([[https://www.nature.com/articles/s41467-024-46801-y.pdf][pdf]])
     
Abstract Electrocatalytic water splitting is a promising route for sustainable hydrogen production. However, the high overpotential of the anodic oxygen evolution reaction poses significant challenge. SrIrO 3 -based perovskite-type catalysts have shown great potential for acidic oxygen evolution reaction, but the origins of their high activity are still unclear. Herein, we develop a Co-doped SrIrO 3 system to enhance oxygen evolution reaction activity and elucidate the origin of catalytic activity. In situ experiments reveal Co activates surface lattice oxygen, rapidly exposing IrO x active sites, while bulk Co doping optimizes the adsorbate binding energy of IrO x . The Co-doped SrIrO 3 demonstrates high oxygen evolution reaction electrocatalytic activity, markedly surpassing the commercial IrO 2 catalysts in both conventional electrolyzer and proton exchange membrane water electrolyzer.    

    

* Oxygen evolution reaction on IrO2(110) is governed by Walden-type mechanisms  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393945519
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-04-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4101847/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393945519"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393945519"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393945519"))][Get cited by]]

OpenAlex: https://openalex.org/W4393945519 (Open access: True)
    
[[https://openalex.org/A5004991965][Kai S. Exner]], [[https://openalex.org/A5016574967][Muhammad Usama]], [[https://openalex.org/A5030887337][Samad Razzaq]], [[https://openalex.org/A5019753746][Christof Hättig]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4101847/v1  ([[https://www.researchsquare.com/article/rs-4101847/latest.pdf][pdf]])
     
Abstract Oxygen evolution reaction (OER) is a key process for sustainable energy, although renewable sources require the use of proton exchange membrane electrolyzers, with IrO 2 -based materials being the gold standard due to their high activity and stability under dynamic anodic polarization conditions. However, even for the (110) facet of a single-crystalline IrO 2 model electrode, the reaction mechanism is not settled yet due to contradictory reports in literature. In the present manuscript, we disentangle the conflicting results of previous theoretical studies in the density functional theory approximation. We demonstrate that dissimilar reaction mechanisms and limiting steps for the OER over IrO 2 (110) are obtained for different active surface configurations present on the IrO 2 electrode. In contrast to previous studies, we factor Walden-type mechanisms, in which the formation of the product O 2 and adsorption of the reactant H 2 O occur simultaneously, into the analysis of the elementary steps. Combining free-energy diagrams along the reaction coordinate and Bader charge analysis of the active site under constant potential, we elucidate why mononuclear- or bifunctional-Walden pathways excel the traditional OER mechanisms for the OER over IrO 2 (110). Our computational methodology to identify the reaction mechanism and limiting step of proton-coupled electron transfer steps is universally applicable to electrochemical processes in the field of energy conversion and storage.    

    

* Research Advances of Non-Noble Metal Catalysts for Oxygen Evolution Reaction in Acid  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393871266
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-04-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ma17071637")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393871266"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393871266"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393871266"))][Get cited by]]

OpenAlex: https://openalex.org/W4393871266 (Open access: True)
    
[[https://openalex.org/A5066914507][Zhimin Yan]], [[https://openalex.org/A5022072189][Shengmin Guo]], [[https://openalex.org/A5003696485][Zhaojun Tan]], [[https://openalex.org/A5000815865][Lijun Wang]], [[https://openalex.org/A5074942308][Gang Li]], [[https://openalex.org/A5041325514][Mingqi Tang]], [[https://openalex.org/A5057006310][Zaiqiang Feng]], [[https://openalex.org/A5080539550][Xianjie Yuan]], [[https://openalex.org/A5007164380][Yingjia Wang]], [[https://openalex.org/A5086225546][Bin Cao]], Materials (Basel). 17(7)] 2024. https://doi.org/10.3390/ma17071637  ([[https://www.mdpi.com/1996-1944/17/7/1637/pdf?version=1712132769][pdf]])
     
Water splitting is an important way to obtain hydrogen applied in clean energy, which mainly consists of two half-reactions: hydrogen evolution reaction (HER) and oxygen evolution reaction (OER). However, the kinetics of the OER of water splitting, which occurs at the anode, is slow and inefficient, especially in acid. Currently, the main OER catalysts are still based on noble metals, such as Ir and Ru, which are the main active components. Hence, the exploration of new OER catalysts with low cost, high activity, and stability has become a key issue in the research of electrolytic water hydrogen production technology. In this paper, the reaction mechanism of OER in acid was discussed and summarized, and the main methods to improve the activity and stability of non-noble metal OER catalysts were summarized and categorized. Finally, the future prospects of OER catalysts in acid were made to provide a little reference idea for the development of advanced OER catalysts in acid in the future.    

    

* Boron-Incorporated Cobalt–Nickel Oxide Nanosheets for Electrochemical Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393903021
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c03136")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393903021"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393903021"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393903021"))][Get cited by]]

OpenAlex: https://openalex.org/W4393903021 (Open access: True)
    
[[https://openalex.org/A5033632697][Yue Wang]], [[https://openalex.org/A5040727901][Ashwani Kumar]], [[https://openalex.org/A5077259177][Eko Budiyanto]], [[https://openalex.org/A5018571913][Haritha Cheraparambil]], [[https://openalex.org/A5076366179][Claudia Weidenthaler]], [[https://openalex.org/A5060841613][Harun Tüysüz]], ACS applied energy materials. None(None)] 2024. https://doi.org/10.1021/acsaem.3c03136  ([[https://pubs.acs.org/doi/pdf/10.1021/acsaem.3c03136][pdf]])
     
The composition and crystal structure are crucial parameters for the activity and stability of the electrocatalysts. Herein, we synthesize a series of CoxNi–B oxide nanosheets with low degree of crystallinity for alkaline media oxygen evolution reaction (OER). The sample with an optimized ratio Co8Ni–B oxide shows the best OER performance, achieving a current density of 10 mA/cm2 at an overpotential of 312 mV and a Tafel slope of 47 mV/dec in the 1 M KOH electrolyte. This sample is stable in the purified Fe-free KOH electrolyte and strongly activated in the nonpurified commercial electrolyte due to the Fe impurity uptake. The high surface area and partially crystalline structure caused by boron incorporation and low-temperature treatment provide more accessible active sites with retaining good stability against leaching during the OER. In situ electrochemical Raman spectroscopy investigation reveals the formation of OER active Co and Ni oxyhydroxides in Co8Ni–B oxides under a potential bias. The Ni substitution in Co oxides modulates the electronic structure of Co, and the OER activity of the electrocatalyst can be enhanced by Fe uptake from the KOH electrolyte.    

    

* Two-Dimensional Nico2s4 Nanosheets Deliver Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393619882
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4781076")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393619882"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393619882"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393619882"))][Get cited by]]

OpenAlex: https://openalex.org/W4393619882 (Open access: False)
    
[[https://openalex.org/A5042846165][Kun Xiang]], [[https://openalex.org/A5004638032][Meng Li]], [[https://openalex.org/A5058267937][Jidong Zhang]], [[https://openalex.org/A5073233621][Chuanxiao Cheng]], [[https://openalex.org/A5044185552][Shaotao Dai]], [[https://openalex.org/A5025382217][Qiong Li]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4781076 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Unraveling Surface Reconstruction During Oxygen Evolution Reaction on the Defined Spinel Oxide Surface  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393364585
:TOPICS: Catalytic Nanomaterials, Atomic Layer Deposition Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202401095")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393364585"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393364585"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393364585"))][Get cited by]]

OpenAlex: https://openalex.org/W4393364585 (Open access: False)
    
[[https://openalex.org/A5009235836][Kyungbeen Yeom]], [[https://openalex.org/A5084067051][Jung Hyun Jo]], [[https://openalex.org/A5077614940][Hyun-Seop Shin]], [[https://openalex.org/A5019783246][Hyunsoo Ji]], [[https://openalex.org/A5039548543][Sun-Young Moon]], [[https://openalex.org/A5054551527][Ji‐Eun Park]], [[https://openalex.org/A5061877778][Seongbeom Lee]], [[https://openalex.org/A5020781886][Jae-Hyuk Shim]], [[https://openalex.org/A5001151989][Dong Hyeon Mok]], [[https://openalex.org/A5072687754][Megalamane S. Bootharaju]], [[https://openalex.org/A5058710447][Seoin Back]], [[https://openalex.org/A5025901845][Taeghwan Hyeon]], [[https://openalex.org/A5084410026][Yung‐Eun Sung]], Advanced functional materials (Print). None(None)] 2024. https://doi.org/10.1002/adfm.202401095 
     
Abstract The reconstructed surface structure of Co‐based spinel oxides serves as the active site for oxygen evolution reaction (OER). However, the structural complexity of spinel oxides and surface dynamics during the OER hinder the understanding of the reconstruction mechanism and electronic structure of the active site. In this study, spinel Co 3 O 4 @(CoFeV) 3 O 4 nanocube (CoFeV) is reported, a (001) facet‐defined spinel oxide comprising Co, Fe, and V deposited on the Co 3 O 4 nanocube template to exclude facet‐dependent factors. Introducing highly dissoluble V cations accelerates the reconstruction process to enhance the electrocatalytic activity. CoFeV exhibited enhanced electrocatalytic activity (266 mV at 10 mA cm −2 in 1 M KOH) and durability (maintained stable electrocatalytic activity during a 200 h chronopotentiometry (CP) test at 100 mA cm −2 ) with significantly enlarged electrochemically active surface area (ECSA). The experimental and theoretical results demonstrated that V dissolution during catalysis induced oxygen vacancies, accelerating the surface reconstruction to highly active oxyhydroxide. Consequently, the anion exchange membrane water electrolyzer (AEMWE) of CoFeV as the anode exhibited a remarkable performance of 6.19 A cm −2 at 2.0 V cell in 1 M KOH and robust durability for 96 h at a constant current density of 500 mA cm −2 .    

    

* Dataset of "Tracking high-valent surface iron species in the oxygen evolution reaction on cobalt iron (oxy)hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393474992
:TOPICS: Neural Network Fundamentals and Applications
:PUBLICATION_DATE: 2021-11-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.5723297")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393474992"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393474992"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393474992"))][Get cited by]]

OpenAlex: https://openalex.org/W4393474992 (Open access: True)
    
[[https://openalex.org/A5039469376][Seunghwa Lee]], [[https://openalex.org/A5023300347][Aliki Moysiadou]], [[https://openalex.org/A5052774133][You‐Chiuan Chu]], [[https://openalex.org/A5073478852][Hao Ming Chen]], [[https://openalex.org/A5076829051][Xile Hu]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2021. https://doi.org/10.5281/zenodo.5723297 
     
Dataset of the paper entitled "Tracking high-valent surface iron species in the oxygen evolution reaction on cobalt iron (oxy)hydroxides"    

    

* Dataset of "Tracking high-valent surface iron species in the oxygen evolution reaction on cobalt iron (oxy)hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393691265
:TOPICS: Neural Network Fundamentals and Applications
:PUBLICATION_DATE: 2021-11-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.5723296")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393691265"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393691265"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393691265"))][Get cited by]]

OpenAlex: https://openalex.org/W4393691265 (Open access: True)
    
[[https://openalex.org/A5039469376][Seunghwa Lee]], [[https://openalex.org/A5023300347][Aliki Moysiadou]], [[https://openalex.org/A5052774133][You‐Chiuan Chu]], [[https://openalex.org/A5073478852][Hao Ming Chen]], [[https://openalex.org/A5076829051][Xile Hu]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2021. https://doi.org/10.5281/zenodo.5723296 
     
Dataset of the paper entitled "Tracking high-valent surface iron species in the oxygen evolution reaction on cobalt iron (oxy)hydroxides"    

    

* Data Set for Operando Identification of a Side-On Nickel Superoxide Intermediate and the Mechanism of Oxygen Evolution on Nickel Oxyhydroxide  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393557894
:TOPICS: Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2022-11-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.7319397")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393557894"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393557894"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393557894"))][Get cited by]]

OpenAlex: https://openalex.org/W4393557894 (Open access: True)
    
[[https://openalex.org/A5039469376][Seunghwa Lee]], [[https://openalex.org/A5052774133][You‐Chiuan Chu]], [[https://openalex.org/A5077313849][Lichen Bai]], [[https://openalex.org/A5073478852][Hao Ming Chen]], [[https://openalex.org/A5076829051][Xile Hu]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2022. https://doi.org/10.5281/zenodo.7319397 
     
Dataset of the paper entitled "Operando Identification of a Side-On Nickel Superoxide Intermediate and the Mechanism of Oxygen Evolution on Nickel Oxyhydroxide"    

    

* Data Set for Operando Identification of a Side-On Nickel Superoxide Intermediate and the Mechanism of Oxygen Evolution on Nickel Oxyhydroxide  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393809773
:TOPICS: Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2022-11-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5281/zenodo.7319396")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393809773"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393809773"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393809773"))][Get cited by]]

OpenAlex: https://openalex.org/W4393809773 (Open access: True)
    
[[https://openalex.org/A5039469376][Seunghwa Lee]], [[https://openalex.org/A5052774133][You‐Chiuan Chu]], [[https://openalex.org/A5077313849][Lichen Bai]], [[https://openalex.org/A5073478852][Hao Ming Chen]], [[https://openalex.org/A5076829051][Xile Hu]], Zenodo (CERN European Organization for Nuclear Research). None(None)] 2022. https://doi.org/10.5281/zenodo.7319396 
     
Dataset of the paper entitled "Operando Identification of a Side-On Nickel Superoxide Intermediate and the Mechanism of Oxygen Evolution on Nickel Oxyhydroxide"    

    

* Epitaxially Heterointerficial Electron Bridge Synchoronizes Oxygen Evolution Activity and Stability on a Layered Double Hydroxide Surface  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393619881
:TOPICS: Catalytic Nanomaterials, Layered Double Hydroxide Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ey00037d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393619881"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393619881"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393619881"))][Get cited by]]

OpenAlex: https://openalex.org/W4393619881 (Open access: True)
    
[[https://openalex.org/A5054352845][Jia Wang]], [[https://openalex.org/A5089593268][Zelin Zhao]], [[https://openalex.org/A5024227929][Min Guo]], [[https://openalex.org/A5085782601][Xiao Liang]], [[https://openalex.org/A5086617910][Haolin Tang]], [[https://openalex.org/A5031995574][Jiantao Li]], [[https://openalex.org/A5059733113][Zongkui Kou]], [[https://openalex.org/A5061583280][Junsheng Li]], EES catalysis. None(None)] 2024. https://doi.org/10.1039/d4ey00037d  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ey/d4ey00037d][pdf]])
     
Scalable green hydrogen production via electrocatalytic water splitting is largely restricted by insufficient activity and stability of oxygen evolution reaction (OER) catalysts at the cathode. As a class of most...    

    

* New strategies for the elaboration of porous materials based on iridium towards the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393370747
:TOPICS: Evolution and Applications of Nanoporous Metals, Fabrication and Applications of Porous Alumina Membranes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2022-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393370747"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393370747"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393370747"))][Get cited by]]

OpenAlex: https://openalex.org/W4393370747 (Open access: True)
    
[[https://openalex.org/A5053316352][Marine Elmaalouf]], No host. None(None)] 2022. None  ([[https://theses.hal.science/tel-04225703/document][pdf]])
     
No abstract    

    
