#+TITLE: water splitting
Description: water splitting papers
Created on Sun Jul 21 01:15:58 2024

Found 84 results from 2024-07-14 to 2024-07-21
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Unveiling the Role of Electrochemical Activation for Iron-doped Ni Oxyhydroxide in Enhancing the Catalytic Performance of Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400605694
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.22541/au.172088317.78083290/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400605694"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400605694"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400605694"))][Get cited by]]

OpenAlex: https://openalex.org/W4400605694 (Open access: False)
    
[[https://openalex.org/A5100384053][Jiyoung Kim]], [[https://openalex.org/A5033502982][JeongEun Yoo]], [[https://openalex.org/A5100719658][Ki‐Young Lee]], No host. None(None)] 2024. https://doi.org/10.22541/au.172088317.78083290/v1 
     
No abstract    

    

* Superhydrophilic cobalt-doped NiFe LDH graphite felt with enriched oxygen vacancy as an efficient oxygen evolution electrocatalyst in alkaline media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400612401
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.109")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400612401"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400612401"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400612401"))][Get cited by]]

OpenAlex: https://openalex.org/W4400612401 (Open access: False)
    
[[https://openalex.org/A5100664693][Danni Li]], [[https://openalex.org/A5064789384][Xiang Shao]], [[https://openalex.org/A5056455537][Muhammad Umair]], [[https://openalex.org/A5004937509][Fengxiao Hou]], [[https://openalex.org/A5101676646][Sa Li]], [[https://openalex.org/A5087387348][Yingming Tang]], [[https://openalex.org/A5084812419][Limei Cao]], [[https://openalex.org/A5045154172][Ji Yang]], International journal of hydrogen energy. 80(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.109 
     
No abstract    

    

* Efficient and robust single-layer IrO cluster electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400614572
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ces.2024.120508")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400614572"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400614572"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400614572"))][Get cited by]]

OpenAlex: https://openalex.org/W4400614572 (Open access: False)
    
[[https://openalex.org/A5100330681][Wenbo Liu]], [[https://openalex.org/A5060588356][Zhicheng Hu]], [[https://openalex.org/A5101696833][Tong Ren]], [[https://openalex.org/A5023821521][Zhipeng Xiang]], [[https://openalex.org/A5044407910][Jinhua Piao]], [[https://openalex.org/A5006641147][Kai Wan]], [[https://openalex.org/A5064527037][Zhiyong Fu]], [[https://openalex.org/A5084212550][Zhenxing Liang]], Chemical engineering science. None(None)] 2024. https://doi.org/10.1016/j.ces.2024.120508 
     
No abstract    

    

* A review of efficient electrocatalysts for the oxygen evolution reaction at large current density  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400614763
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.decarb.2024.100062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400614763"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400614763"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400614763"))][Get cited by]]

OpenAlex: https://openalex.org/W4400614763 (Open access: True)
    
[[https://openalex.org/A5066088830][Youtao Yao]], [[https://openalex.org/A5049385562][Jiahui Lyu]], [[https://openalex.org/A5103155569][Xingchuan Li]], [[https://openalex.org/A5038019595][Cheng Chen]], [[https://openalex.org/A5050655757][Francis Verpoort]], [[https://openalex.org/A5100605872][John Wang]], [[https://openalex.org/A5042492387][Zhenghui Pan]], [[https://openalex.org/A5005358046][Zongkui Kou]], DeCarbon. None(None)] 2024. https://doi.org/10.1016/j.decarb.2024.100062 
     
No abstract    

    

* Corrigendum to ‘Single atom catalysts supported on cyclo[18]carbon and its allotropes (B9N9 and Al9N9) for the hydrogen evolution and oxygen evolution reactions’ Surfaces and Interfaces Volume 42, Part A (2023) 103319  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400618052
:TOPICS: Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics, Boron Neutron Capture Therapy
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104787")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400618052"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400618052"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400618052"))][Get cited by]]

OpenAlex: https://openalex.org/W4400618052 (Open access: False)
    
[[https://openalex.org/A5051746447][Nuha Wazzan]], [[https://openalex.org/A5009902080][Prafulla K. Jha]], Surfaces and interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104787 
     
No abstract    

    

* Rational design of highly corrosion-resistant chromium hydroxide coupled amorphous-crystalline heterostructure to achieve efficient and stable seawater oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400621650
:TOPICS: Emergent Phenomena at Oxide Interfaces, Photocatalytic Materials for Solar Energy Conversion, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcat.2024.115655")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400621650"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400621650"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400621650"))][Get cited by]]

OpenAlex: https://openalex.org/W4400621650 (Open access: False)
    
[[https://openalex.org/A5055737517][Fanjia Sun]], [[https://openalex.org/A5100372549][Yanhui Wang]], [[https://openalex.org/A5003925465][Xueqing Tian]], [[https://openalex.org/A5100617068][Rui Zhu]], [[https://openalex.org/A5101697095][Zhiwei Hou]], [[https://openalex.org/A5101544759][Youbin Zheng]], [[https://openalex.org/A5052479731][Jianbing Zang]], [[https://openalex.org/A5101814743][Yukui Zhang]], Journal of catalysis. None(None)] 2024. https://doi.org/10.1016/j.jcat.2024.115655 
     
No abstract    

    

* Bifunctional amorphous high entropy materials for sensitive nitrite detection and efficient oxygen evolution reaction electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400622597
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.153997")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400622597"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400622597"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400622597"))][Get cited by]]

OpenAlex: https://openalex.org/W4400622597 (Open access: False)
    
[[https://openalex.org/A5100459747][Jiali Chen]], [[https://openalex.org/A5100437854][Lijuan Chen]], [[https://openalex.org/A5071650164][Wanting Zhu]], [[https://openalex.org/A5101831774][Xiaobing Huang]], [[https://openalex.org/A5100392071][Wei Wang]], [[https://openalex.org/A5032132815][Dongxue Han]], [[https://openalex.org/A5100710974][Li Niu]], Chemical engineering journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.153997 
     
No abstract    

    

* Unraveling the oxygen evolution in layered LiNiO2 with the role of Li/Ni disordering  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400624264
:TOPICS: Lithium-ion Battery Technology, Lithium Battery Technologies, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ensm.2024.103632")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400624264"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400624264"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400624264"))][Get cited by]]

OpenAlex: https://openalex.org/W4400624264 (Open access: False)
    
[[https://openalex.org/A5043069484][Yining Jia]], [[https://openalex.org/A5059122991][Xudong Hou]], [[https://openalex.org/A5100377535][Kun Li]], [[https://openalex.org/A5102785847][Linyu Wang]], [[https://openalex.org/A5101987736][Meng Zhang]], [[https://openalex.org/A5103220946][Zikun Li]], [[https://openalex.org/A5053476579][Xianqi Xu]], [[https://openalex.org/A5039376323][Jiaxin Zheng]], Energy storage materials. None(None)] 2024. https://doi.org/10.1016/j.ensm.2024.103632 
     
No abstract    

    

* Electronic Promoter Breaks the Linear Scaling Relationship：Ultra-Rapid High-Temperature Synthesis of Heterostructured Cos/Sno2@C as a Bifunctional Oxygen Catalyst for Li‐O2 Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400641638
:TOPICS: Lithium Battery Technologies, Lithium-ion Battery Technology, Synthesis and Properties of Inorganic Cluster Compounds
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4894968")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400641638"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400641638"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400641638"))][Get cited by]]

OpenAlex: https://openalex.org/W4400641638 (Open access: False)
    
[[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5035060111][Tung-Jing Fang]], [[https://openalex.org/A5036310452][Truong Thien Vinh An]], [[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5100325943][Jiaqi Li]], [[https://openalex.org/A5101315418][Shuming Yu]], [[https://openalex.org/A5103564225][Honghai Sun]], [[https://openalex.org/A5060128126][Xiang Dong]], [[https://openalex.org/A5040990969][Xiangjie Bo]], [[https://openalex.org/A5037048154][Kedi Cai]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4894968 
     
No abstract    

    

* Engineering electronic structures and oxygen vacancies of manganese-doped nickel molybdate porous nanosheets for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400648309
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.07.118")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400648309"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400648309"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400648309"))][Get cited by]]

OpenAlex: https://openalex.org/W4400648309 (Open access: False)
    
[[https://openalex.org/A5100540728][Fang Miao]], [[https://openalex.org/A5035130673][Peng Cui]], [[https://openalex.org/A5003676774][Tiantian Gu]], [[https://openalex.org/A5100886334][Bo Sun]], [[https://openalex.org/A5014086269][Zhijie Yan]], Journal of colloid and interface science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.07.118 
     
No abstract    

    

* Facile Synthesis of Carbon-Coated Nips3 Nanoparticle Electrocatalyst for Highly Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400648521
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4895223")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400648521"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400648521"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400648521"))][Get cited by]]

OpenAlex: https://openalex.org/W4400648521 (Open access: False)
    
[[https://openalex.org/A5104542569][Dongjun Lee]], [[https://openalex.org/A5005654711][Doyeon Lee]], [[https://openalex.org/A5100662247][Wook Kim]], [[https://openalex.org/A5104542570][Seong-Hyeon Hong]], [[https://openalex.org/A5057076775][Hee Jo Song]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4895223 
     
No abstract    

    

* Approaching high oxygen evolution reaction performance by synergetic dual-ion leaching  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400656142
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12274-024-6812-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400656142"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400656142"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400656142"))][Get cited by]]

OpenAlex: https://openalex.org/W4400656142 (Open access: False)
    
[[https://openalex.org/A5004377507][Hancheng Ma]], [[https://openalex.org/A5021782238][Yao Ding]], [[https://openalex.org/A5100454297][Jia Li]], [[https://openalex.org/A5080585847][Wei Peng]], [[https://openalex.org/A5022270398][Liqiang Mai]], Nano research. None(None)] 2024. https://doi.org/10.1007/s12274-024-6812-1 
     
No abstract    

    

* Co@Ir Core-shell Nanochain Aerogels for Hydrogen Evolution Reaction and Oxygen Evolution Reaction in Alkaline Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400661800
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Mesoporous Materials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj02733g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400661800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400661800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400661800"))][Get cited by]]

OpenAlex: https://openalex.org/W4400661800 (Open access: False)
    
[[https://openalex.org/A5019324790][Jiacheng Chen]], [[https://openalex.org/A5101939975][Zihao Xie]], [[https://openalex.org/A5051273729][Yujun Tang]], [[https://openalex.org/A5076295398][Zhenghua Tang]], [[https://openalex.org/A5100709897][Xiufang Wang]], New journal of chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj02733g 
     
Developing efficient and stable oxygen evolution reaction (OER) and hydrogen evolution reaction (HER) catalysts is critical for realizing large-scale hydrogen production via electrochemical water splitting. Here, we report a facile...    

    

* Harnessing the Trade‐Off between CoFe/Fe3C Interfacial Junction with Unparalleled Potential Gap of 0.58 V for Reversible Oxygen Electrocatalysis: Application toward Liquid and Solid‐State Zn‐Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400664469
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-07-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202407078")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400664469"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400664469"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400664469"))][Get cited by]]

OpenAlex: https://openalex.org/W4400664469 (Open access: False)
    
[[https://openalex.org/A5001612544][Srijib Das]], [[https://openalex.org/A5022051010][A. J. Pathak]], [[https://openalex.org/A5053783996][Ujjwal Phadikar]], [[https://openalex.org/A5050890241][Chinmoy Kuila]], [[https://openalex.org/A5016837086][Animesh Maji]], [[https://openalex.org/A5052738033][Tapas Kuila]], [[https://openalex.org/A5023748022][Naresh Chandra Murmu]], [[https://openalex.org/A5028088995][Ranjit Thapa]], [[https://openalex.org/A5059342210][Aniruddha Kundu]], Advanced functional materials. None(None)] 2024. https://doi.org/10.1002/adfm.202407078 
     
Abstract Effective integration of multiple active moieties and strategic engineering of coordinated interfacial junctions are crucial for optimizing the reaction kinetics and intrinsic activities of heterogeneous electrocatalysts. Herein, a simple integrated heterostructure of biphasic Co 0.7 Fe 0.3 /Fe 3 C embedded on in situ grown N‐doped carbon sheets is constructed. Rationally designed CoFe/Fe 3 C‐T 2 owns more accessible active sites and interfacial junction effects, cooperatively boosting the electron and mass transfer, needed for multifunctional electrocatalysis. Leveraging the synergistic effect of dual active sites, CoFe/Fe 3 C‐T 2 demonstrates outstanding oxygen electrocatalytic activity in alkaline medium with an ultra‐low potential gap of 0.58 V, surpassing the recently available state‐of‐the‐art catalysts. Moreover, CoFe/Fe 3 C‐T 2 air‐electrode achieves a high peak power density of 249 mW cm −2 , a large specific capacity of 808 mAh g −1 and excellent cycling stability for aqueous Zn‐air batteries. Remarkably, the solid‐state flexible ZAB also exhibits satisfactory performance, showcasing an open‐circuit voltage of 1.43 V and a peak power density of 66 mW cm −2 . These outstanding results push this catalyst to the top of the list of non‐noble metal‐based electrode materials. This work offers a viable method for using the active‐site‐uniting strategy to create double‐active‐site catalysts, which may find real‐time applications in energy conversion/storage devices.    

    

* Rutile‐Structured Ru0.48Mn0.52O2 Solid Solution for Highly Active and Stable Oxygen Evolution at Large Current Density in Acidic Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400664556
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202409714")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400664556"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400664556"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400664556"))][Get cited by]]

OpenAlex: https://openalex.org/W4400664556 (Open access: False)
    
[[https://openalex.org/A5100731663][Zonglin Li]], [[https://openalex.org/A5090028076][Hong Sheng]], [[https://openalex.org/A5006971744][Yichao Lin]], [[https://openalex.org/A5103734386][Hongyan Hu]], [[https://openalex.org/A5018383506][Hongfei Sun]], [[https://openalex.org/A5100675435][Dong Yan]], [[https://openalex.org/A5100392071][Wei Wang]], [[https://openalex.org/A5054515051][Lingzhi Wei]], [[https://openalex.org/A5043875055][Ziqi Tian]], [[https://openalex.org/A5014087781][Qianwang Chen]], [[https://openalex.org/A5012066622][Jianwei Su]], [[https://openalex.org/A5100334576][Liang Chen]], Advanced functional materials. None(None)] 2024. https://doi.org/10.1002/adfm.202409714 
     
Abstract The development of active, stable, and cost‐effective electrocatalysts for the oxygen evolution reaction (OER) in acidic media is crucial for proton‐exchange‐membrane water electrolysis. Inspired by theoretical screening on a series of transition metal incorporated RuO 2 systems, a low Ru‐content solid solution oxide (Ru 0.48 Mn 0.52 O 2 ) achieved is fabricated by a simple two‐step synthesis method through the combination of rutile RuO 2 and β‐MnO 2 . The Ru 0.48 Mn 0.52 O 2 catalyst exhibits an exceptionally low overpotential of 154 mV at 10 mA cm −2 and maintains a high stability under a high current of 100 mA cm −2 for 50 h in 0.5 m H 2 SO 4 electrolyte. Furthermore, the obtained catalyst exhibits sustained stability at a large current of 0.5 A cm −2 for at least 50 h when loaded onto a Ti felt. The in‐situ characterization results indicate that Ru 0.48 Mn 0.52 O 2 preferably followed the adsorbate evolution mechanism rather than the lattice oxygen oxidation mechanism during the OER process, contributing to its high activity and stability at large current densities in acidic media.    

    

* Promoted surface reconstruction of pentlandite via phosphorus-doping for enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400640426
:TOPICS: Solar Water Splitting Technology, Emergent Phenomena at Oxide Interfaces, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-12-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.07.122")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400640426"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400640426"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400640426"))][Get cited by]]

OpenAlex: https://openalex.org/W4400640426 (Open access: False)
    
[[https://openalex.org/A5100378838][Yaxin Li]], [[https://openalex.org/A5056514565][Xu Zou]], [[https://openalex.org/A5100398969][Yunhong Wang]], [[https://openalex.org/A5100380901][Jian Xu]], [[https://openalex.org/A5070671117][Zhengyan Du]], [[https://openalex.org/A5069619264][Zeshuo Meng]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5037428389][Hongwei Tian]], [[https://openalex.org/A5100617037][Weitao Zheng]], Journal of colloid and interface science. 676(None)] 2024. https://doi.org/10.1016/j.jcis.2024.07.122 
     
The pentlandite Fe    

    

* Nanocomposites based on Cu2O coated silver nanowire networks for high-performance oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400652784
:TOPICS: Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4na00364k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400652784"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400652784"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400652784"))][Get cited by]]

OpenAlex: https://openalex.org/W4400652784 (Open access: True)
    
[[https://openalex.org/A5025809849][Sergio Battiato]], [[https://openalex.org/A5090140297][Abderrahime Sekkat]], [[https://openalex.org/A5070050556][Celso Velásquez]], [[https://openalex.org/A5068652182][Anna Lucia Pellegrino]], [[https://openalex.org/A5020193511][Daniel Bellet]], [[https://openalex.org/A5026110528][A. Terrasi]], [[https://openalex.org/A5012394754][S. Mirabella]], [[https://openalex.org/A5076132595][David Muñoz‐Rojas]], Nanoscale advances. None(None)] 2024. https://doi.org/10.1039/d4na00364k 
     
The development of highly active, low-cost, and robust electrocatalysts for the oxygen evolution reaction (OER) is a crucial endeavor for the clean and economically viable production of hydrogen via electrochemical water splitting.    

    

* In situ Production of Hydroxyl Radicals via Three‐Electron Oxygen Reduction: Opportunities for Water Treatment  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400658295
:TOPICS: Advanced Oxidation Processes for Water Treatment, Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202407628")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400658295"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400658295"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400658295"))][Get cited by]]

OpenAlex: https://openalex.org/W4400658295 (Open access: False)
    
[[https://openalex.org/A5100372799][Zhiming Wang]], [[https://openalex.org/A5101603420][Nan Hu]], [[https://openalex.org/A5100363651][Lan Wang]], [[https://openalex.org/A5026819840][Hongying Zhao]], [[https://openalex.org/A5078771370][Guohua Zhao]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/anie.202407628 
     
The electro‐Fenton (EF) process is an advanced oxidation technology with significant potential; however, it is limited by two steps: generation and activation of H2O2. In contrast to the production of H2O2 via the electrochemical two‐electron oxygen reduction reaction (ORR), the electrochemical three‐electron (3e‐) ORR can directly activate molecular oxygen to yield the hydroxyl radical (·OH), thus breaking through the conceptual and operational limitations of the traditional EF reaction. Therefore, the 3e‐ ORR is a vital process for efficiently producing ·OH in situ, thus charting a new path toward the development of green water‐treatment technologies. This review summarizes the characteristics and mechanisms of the 3e‐ ORR, focusing on the basic principles and latest progress in the in situ generation and efficient utilization of ·OH through the modulation of the reaction pathway, shedding light on the rational design of 3e‐ ORR catalysts, mechanistic exploration, and practical applications for water treatment. Finally, the future developments and challenges of efficient, stable, and large‐scale utilization of ·OH are discussed based on achieving optimal 3e‐ ORR regulation and the potential to combine it with other technologies.    

    

* Synergistic effect of heterogeneous single atoms and clusters for improved catalytic performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400658750
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.52396/justc-2024-0046")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400658750"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400658750"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400658750"))][Get cited by]]

OpenAlex: https://openalex.org/W4400658750 (Open access: False)
    
[[https://openalex.org/A5100394072][Haibo Liu]], [[https://openalex.org/A5033808483][Wenting Gao]], [[https://openalex.org/A5057359491][Yiling Ma]], [[https://openalex.org/A5082138580][Kainan Mei]], [[https://openalex.org/A5100300689][Wang Wenlong]], [[https://openalex.org/A5100442424][Hongliang Li]], [[https://openalex.org/A5100602201][Zhirong Zhang]], [[https://openalex.org/A5075571728][Jie Zeng]], Zhongguo Kexue Jishu Daxue xuebao. 54(6)] 2024. https://doi.org/10.52396/justc-2024-0046 
     
Electrocatalytic water splitting provides an efficient method for the production of hydrogen. In electrocatalytic water splitting, the oxygen evolution reaction (OER) involves a kinetically sluggish four-electron transfer process, which limits the efficiency of electrocatalytic water splitting. Therefore, it is urgent to develop highly active OER catalysts to accelerate reaction kinetics. Coupling single atoms and clusters in one system is an innovative approach for developing efficient catalysts that can synergistically optimize the adsorption and configuration of intermediates and improve catalytic activity. However, research in this area is still scarce. Herein, we constructed a heterogeneous single-atom cluster system by anchoring Ir single atoms and Co clusters on the surface of Ni(OH)<sub>2</sub> nanosheets. Ir single atoms and Co clusters synergistically improved the catalytic activity toward the OER. Specifically, Co<sub><i>n</i></sub>Ir<sub>1</sub>/Ni(OH)<sub>2</sub> required an overpotential of 255 mV at a current density of 10 mA·cm<sup>−2</sup>, which was 60 mV and 67 mV lower than those of Co<sub><i>n</i></sub>/Ni(OH)<sub>2</sub> and Ir<sub>1</sub>/Ni(OH)<sub>2</sub>, respectively. The turnover frequency of Co<sub><i>n</i></sub>Ir<sub>1</sub>/Ni(OH)<sub>2</sub> was 0.49 s<sup>−1</sup>, which was 4.9 times greater than that of Co<sub><i>n</i></sub>/Ni(OH)<sub>2</sub> at an overpotential of 300 mV.    

    

* Inactive Ag Modification and Defect Engineering Optimization on Three-Dimensional Coral-Like High-Entropy Oxides to Trigger Effective Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400673542
:TOPICS: Emergent Phenomena at Oxide Interfaces, Catalytic Nanomaterials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4896977")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400673542"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400673542"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400673542"))][Get cited by]]

OpenAlex: https://openalex.org/W4400673542 (Open access: False)
    
[[https://openalex.org/A5100389704][Bing Zhang]], [[https://openalex.org/A5009734444][Mengzhao Liu]], [[https://openalex.org/A5101364952][Meiqin Cui]], [[https://openalex.org/A5026310569][Weiming Lü]], [[https://openalex.org/A5100697988][Ping Geng]], [[https://openalex.org/A5001547039][Weiming Yi]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4896977 
     
No abstract    

    

* Development of nickel-cobalt-zinc oxide/manganese-nickel hydroxide/reduced graphene oxide on nickel foam for efficient supercapacitors and oxygen evolution reaction applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400676349
:TOPICS: Materials for Electrochemical Supercapacitors, Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.07.193")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400676349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400676349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400676349"))][Get cited by]]

OpenAlex: https://openalex.org/W4400676349 (Open access: False)
    
[[https://openalex.org/A5090841814][Shangru Zhou]], [[https://openalex.org/A5056265959][Hanwei Zhao]], [[https://openalex.org/A5064493726][E. Fan]], [[https://openalex.org/A5065772702][Zhuanfang Zhang]], [[https://openalex.org/A5003248211][Guohua Dong]], [[https://openalex.org/A5101732008][Wenzhi Zhang]], [[https://openalex.org/A5050607567][Yu Zang]], [[https://openalex.org/A5101705015][Ming Zhao]], [[https://openalex.org/A5048157332][Dong‐Feng Chai]], [[https://openalex.org/A5064748004][Xiaoming Huang]], Ceramics international. None(None)] 2024. https://doi.org/10.1016/j.ceramint.2024.07.193 
     
No abstract    

    

* Single-Atom Catalysts for Electrochemical Water Splitting: A Critical Review of Recent Advancements in Single-Site, Dual-Site, and Alloy Configurations for Enhanced Hydrogen and Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400678453
:TOPICS: Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.22541/au.172115273.30149968/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400678453"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400678453"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400678453"))][Get cited by]]

OpenAlex: https://openalex.org/W4400678453 (Open access: False)
    
[[https://openalex.org/A5104601258][Maheswari Arunachalm]], [[https://openalex.org/A5051993858][Kwang‐Soon Ahn]], [[https://openalex.org/A5074976953][Soon Hyung Kang]], Authorea (Authorea). None(None)] 2024. https://doi.org/10.22541/au.172115273.30149968/v1 
     
No abstract    

    

* Facile Hydrothermal Synthesis of NiMn2O4/C Nanosheets for Solid-State Asymmetric Supercapacitor and Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400681305
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.4c02216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400681305"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400681305"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400681305"))][Get cited by]]

OpenAlex: https://openalex.org/W4400681305 (Open access: False)
    
[[https://openalex.org/A5092412236][Pragati N. Thonge]], [[https://openalex.org/A5059831386][Suprimkumar D. Dhas]], [[https://openalex.org/A5074998805][Shivaji D. Waghmare]], [[https://openalex.org/A5085682295][Aravind H. Patil]], [[https://openalex.org/A5091175901][Teja M. Patil]], [[https://openalex.org/A5027432798][Manesh A. Yewale]], [[https://openalex.org/A5086528985][Avinash C. Mendhe]], [[https://openalex.org/A5100650947][Daewon Kim]], ACS applied nano materials. None(None)] 2024. https://doi.org/10.1021/acsanm.4c02216 
     
No abstract    

    

* MoS2@MWCNTs Core–shell Heterostructure for Enhanced Oxygen Evolution Reaction in Alkaline Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400684062
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.22541/au.172114242.28442487/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400684062"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400684062"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400684062"))][Get cited by]]

OpenAlex: https://openalex.org/W4400684062 (Open access: False)
    
[[https://openalex.org/A5001325073][Huy Du Nguyen]], [[https://openalex.org/A5043109791][Kyu Yeon Jang]], [[https://openalex.org/A5085253892][Hye Bin Jung]], [[https://openalex.org/A5031401877][MinJoong Kim]], [[https://openalex.org/A5067736825][Chang‐Soo Lee]], [[https://openalex.org/A5102018865][Young‐Woo Lee]], [[https://openalex.org/A5053360364][Kyu‐Nam Jung]], [[https://openalex.org/A5100671067][Seung Woo Lee]], [[https://openalex.org/A5045489385][Hyun‐Seok Cho]], [[https://openalex.org/A5023819463][Hana Yoon]], [[https://openalex.org/A5101500728][Younghyun Cho]], Authorea (Authorea). None(None)] 2024. https://doi.org/10.22541/au.172114242.28442487/v1 
     
This work reports the development of a MoS2@MWCNTs core–shell heterostructure synthesized through an optimized hydrothermal process, designed to enhance the oxygen evolution reaction (OER) efficiency in alkaline water electrolysis. By employing continuous tumbling during synthesis, a uniform and precise thickness of MoS2 was grown on the MWCNTs, striking a balance between maximal catalytic activity at the MoS2 edges, and leveraging the high electrical conductivity of the MWCNTs. The resulting MoS2@MWCNTs catalyst exhibited outstanding electrocatalytic performance for OER, with low overpotential of 285 mV at current density of 10 mA·cm−2, Tafel slope of 42 mV·dec−1, and exceptional durability, maintaining stable operation over 900 hours. Furthermore, the catalyst demonstrated robust performance under dynamic and unstable operating conditions, highlighting its potential for real-world applications in green hydrogen production. This study showcases the successful application of a core–shell structure for OER catalysis, while contributing to the advancement of sustainable energy technologies by providing a cost-effective and efficient solution for hydrogen production through water electrolysis.    

    

* Aerosol Assisted Synthesis of Iron Oxide@High Entropy Alloy Core-Shell Nanospheres as Superior Electrocatalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400684242
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.22541/au.172114236.61135092/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400684242"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400684242"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400684242"))][Get cited by]]

OpenAlex: https://openalex.org/W4400684242 (Open access: False)
    
[[https://openalex.org/A5060712549][Burak Küçükelyas]], [[https://openalex.org/A5057534534][İhsan Çaha]], [[https://openalex.org/A5031553868][Zhipeng Yu]], [[https://openalex.org/A5006429774][Duygu Yeşiltepe Özçelik]], [[https://openalex.org/A5037311572][Francis Leonard Deepak]], [[https://openalex.org/A5064978886][Deniz Uzunsoy]], [[https://openalex.org/A5002915542][Sebahattin Gürmen]], Authorea (Authorea). None(None)] 2024. https://doi.org/10.22541/au.172114236.61135092/v1 
     
No abstract    

    

* Anchoring Ni(OH)2‐CeOx Heterostructure on FeOOH‐Modified Nickel‐Mesh for Efficient Alkaline Water‐Splitting Performance with Improved Stability under Quasi‐Industrial Conditions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400686614
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202403971")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400686614"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400686614"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400686614"))][Get cited by]]

OpenAlex: https://openalex.org/W4400686614 (Open access: False)
    
[[https://openalex.org/A5086205318][Waleed Yaseen]], [[https://openalex.org/A5081448854][Yuanguo Xu]], [[https://openalex.org/A5103219393][Bashir Adegbemiga Yusuf]], [[https://openalex.org/A5051059043][Suci Meng]], [[https://openalex.org/A5054123047][Iltaf Khan]], [[https://openalex.org/A5011755433][Jimin Xie]], [[https://openalex.org/A5081448854][Yuanguo Xu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202403971 
     
Abstract Developing low‐cost and industrially viable electrode materials for efficient water‐splitting performance and constructing intrinsically active materials with abundant active sites is still challenging. In this study, a self‐supported porous network Ni(OH) 2 ‐CeO x heterostructure layer on a FeOOH‐modified Ni‐mesh (NiCe/Fe@NM) electrode is successfully prepared by a facile, scalable two‐electrode electrodeposition strategy for overall alkaline water splitting. The optimized NiCe 0.05 /Fe@NM catalyst reaches a current density of 100 mA cm −2 at an overpotential of 163 and 262 mV for hydrogen evolution reaction (HER) and oxygen evolution reaction (OER), respectively, in 1.0 m KOH with excellent stability. Additionally, NiCe 0.05 /Fe@NM demonstrates exceptional HER performance in alkaline seawater, requiring only 148 mV overpotential at 100 mA cm −2 . Under real water splitting conditions, NiCe 0.05 /Fe@NM requires only 1.701 V to achieve 100 mA cm −2 with robust stability over 1000 h in an alkaline medium. The remarkable water‐splitting performance and stability of the NiCe 0.05 /Fe@NM catalyst result from a synergistic combination of factors, including well‐optimized surface and electronic structures facilitated by an optimal Ce ratio, rapid reaction kinetics, a superhydrophilic/superaerophobic interface, and enhanced intrinsic catalytic activity. This study presents a simple two‐electrode electrodeposition method for the scalable production of self‐supported electrocatalysts, paving the way for their practical application in industrial water‐splitting processes.    

    

* Ion- and surface-sensitive interactions during oxygen evolution reaction in alkaline media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400686653
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1755-1315/1372/1/012101")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400686653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400686653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400686653"))][Get cited by]]

OpenAlex: https://openalex.org/W4400686653 (Open access: True)
    
[[https://openalex.org/A5104618745][P D Angeles]], [[https://openalex.org/A5001672257][Author Bustamante]], [[https://openalex.org/A5104603077][H A S Sasil]], [[https://openalex.org/A5092501104][D E D Loresca]], [[https://openalex.org/A5037055367][Julie Anne D. del Rosario]], IOP conference series. Earth and environmental science. 1372(1)] 2024. https://doi.org/10.1088/1755-1315/1372/1/012101 
     
Abstract Clean and sustainable energy has turned towards electrochemical water splitting as a viable solution in minimizing carbon emissions. Electrolysis of water converts electrical energy to chemical energy, through the production of hydrogen and oxygen gases, which can be harnessed for potential applications without contributing to greenhouse emissions. While this energy storage process shows great potential, its efficiency is hindered by the sluggish kinetics of the oxygen evolution reaction (OER). As a result, its widespread application in green electrolytic technologies is limited hence investigations on improving OER kinetics are of utmost importance. Recent research breakthroughs indicate that alkali metal cations are more than passive observers. They play complex roles in the electric double layer (EDL), which positively influences the OER kinetics. The presence of numerous ions and their combinations presents a challenge of complexity. This study aims to delve into the impact of alkali metal cations on OER activity due to the variance in their hydration energies. Specific investigations focusing on different alkali metal cations in solution, such as Li + , Na + , and K + , was conducted on RuO 2 to gain a deeper understanding of how these ions interact with both reactants and intermediate species in the reaction kinetics. Traditional electrochemical tests, including cyclic voltammetry (CV), linear sweep voltammetry (LSV), electrochemical impedance spectroscopy (EIS), and accelerated degradation test (ADT) measurements were employed to elucidate critical aspects such as surface activation, electric double layer interactions, catalytic activity and stability, ohmic resistance, and mass and charge transport.    

    

* Nitrogen-Mediated Promotion of Cobalt-Based Oxygen Evolution Catalyst for Practical Anion-Exchange Membrane Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400688461
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c05983")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400688461"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400688461"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400688461"))][Get cited by]]

OpenAlex: https://openalex.org/W4400688461 (Open access: False)
    
[[https://openalex.org/A5038084499][Pengcheng Yu]], [[https://openalex.org/A5059787769][Xiaolong Zhang]], [[https://openalex.org/A5082143139][Tian-Yun Zhang]], [[https://openalex.org/A5050666718][Xuyingnan Tao]], [[https://openalex.org/A5055962979][Yang Yu]], [[https://openalex.org/A5039342550][Ye-Hua Wang]], [[https://openalex.org/A5063235043][Sichao Zhang]], [[https://openalex.org/A5010084472][Fei‐Yue Gao]], [[https://openalex.org/A5083454521][Zhuang‐Zhuang Niu]], [[https://openalex.org/A5074130931][Minghui Fan]], [[https://openalex.org/A5018140110][Min‐Rui Gao]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c05983 
     
Scarce and expensive iridium oxide is still the cornerstone catalyst of polymer-electrolyte membrane electrolyzers for green hydrogen production because of its exceptional stability under industrially relevant oxygen evolution reaction (OER) conditions. Earth-abundant transition metal oxides used for this task, however, show poor long-term stability. We demonstrate here the use of nitrogen-doped cobalt oxide as an effective iridium substitute. The catalyst exhibits a low overpotential of 240 mV at 10 mA cm    

    

* Unbiased photoelectrochemical H2O2 coupled to H2 production via dual Sb2S3‐based photoelectrodes with ultralow onset potential  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400697173
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202411305")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400697173"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400697173"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400697173"))][Get cited by]]

OpenAlex: https://openalex.org/W4400697173 (Open access: False)
    
[[https://openalex.org/A5100435779][Lei Wang]], [[https://openalex.org/A5019373849][Fei Guo]], [[https://openalex.org/A5073406394][Shijie Ren]], [[https://openalex.org/A5036327118][Rui‐Ting Gao]], [[https://openalex.org/A5100702398][Limin Wu]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/anie.202411305 
     
The productions of hydrogen peroxide (H2O2) and hydrogen (H2) in a photoelectrochemical (PEC) water splitting cell suffer from an onset potential that limits solar conversion efficiencies. The formation of H2O2 through two‐electron PEC water oxidation reaction competes with four‐electron oxidation evolution reaction. Herein, we developed the surface selenium doped antimony trisulfide photoelectrode with the integrated ruthenium cocatalyst (Ru/Sb2(S,Se)3) to achieve the low onset potential and high Faraday efficiency (FE) for selective H2O2 production. The photoanode exhibits an average FE of 85% in the potential range of 0.4‐1.6 VRHE and the H2O2 yield of 1.01 μmol cm‐2 min‐1 at 1.6 VRHE, especially at low potentials of 0.1‐0.55 VRHE with 80.4% FE. Impressively, an unassisted PEC system that employs light and electrolyte was constructed to simultaneously produce H2O2 and H2 production on both Ru/Sb2(S,Se)3 photoanode and the Pt/TiO2/Sb2S3 photocathode. The integrated system enables the average PEC H2O2 production rate of 0.637 μmol cm‐2 min‐1 without applying any addition bias. This is the first demonstration that Sb2S3‐based photoelectrodes exhibit H2O2/H2 two‐side production with a strict key factor of the system, which represents its powerful platform to achieve high efficiency and productivity and the feasibility to facilitate value‐added products in neutral conditions.    

    

* Atomic‐Level Observation of Potential‐Dependent Variations at the Surface of an Oxide Catalyst during Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400699451
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202403392")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400699451"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400699451"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400699451"))][Get cited by]]

OpenAlex: https://openalex.org/W4400699451 (Open access: True)
    
[[https://openalex.org/A5084732968][Chang Hyun Park]], [[https://openalex.org/A5074968848][Hyungdoh Lee]], [[https://openalex.org/A5071734868][Jin‐Seok Choi]], [[https://openalex.org/A5039746262][Tae Gyu Yun]], [[https://openalex.org/A5074338972][Young-Hwan Lim]], [[https://openalex.org/A5006971528][Hyung Bin Bae]], [[https://openalex.org/A5083703475][Sung‐Yoon Chung]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202403392 
     
Understanding the intricate details of the surface atomic structure and composition of catalysts during the oxygen evolution reaction (OER) is crucial for developing catalysts with high stability in water electrolyzers. While many notable studies highlight surface amorphization and reconstruction, systematic analytical tracing of the catalyst surface as a function of overpotential remains elusive. Heteroepitaxial (001) films of chemically stable and lattice-oxygen-inactive LaCoO    

    

* Thermocatalytic Epoxidation by Cobalt Sulfide Inspired by the Material’s Electrocatalytic Activity for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400701558
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cy00518j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400701558"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400701558"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400701558"))][Get cited by]]

OpenAlex: https://openalex.org/W4400701558 (Open access: True)
    
[[https://openalex.org/A5045912612][Vanessa Wyss]], [[https://openalex.org/A5033568331][Ionel Adrian Dinu]], [[https://openalex.org/A5034042210][L. Marot]], [[https://openalex.org/A5015692939][Cornelia G. Palivan]], [[https://openalex.org/A5033224567][Murielle F. Delley]], Catalysis science & technology. None(None)] 2024. https://doi.org/10.1039/d4cy00518j 
     
New discoveries in catalysis by earth-abundant materials can be guided by leveraging knowledge across two sub-disciplines of heterogeneous catalysis: electrocatalysis and thermocatalysis. Cobalt sulfide has been reported to be a...    

    

* Rational design of MXene-based vacancy-confined single-atom catalyst for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400721513
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.07.014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400721513"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400721513"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400721513"))][Get cited by]]

OpenAlex: https://openalex.org/W4400721513 (Open access: False)
    
[[https://openalex.org/A5025032051][Zhongheng Fu]], [[https://openalex.org/A5067368667][Guangtong Hai]], [[https://openalex.org/A5102437306][Xia‐Xia Ma]], [[https://openalex.org/A5069170567][Dominik Legut]], [[https://openalex.org/A5088780310][Yongchao Zheng]], [[https://openalex.org/A5100641667][Xiang Chen]], Journal of Energy Chemistry/Journal of energy chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.07.014 
     
No abstract    

    

* Ultrathin high-entropy layered double hydroxide electrocatalysts for enhancing oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400721805
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.175584")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400721805"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400721805"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400721805"))][Get cited by]]

OpenAlex: https://openalex.org/W4400721805 (Open access: False)
    
[[https://openalex.org/A5016481203][Xianxu Chu]], [[https://openalex.org/A5100427915][Ting Wang]], [[https://openalex.org/A5007138428][Haoyuan Wang]], [[https://openalex.org/A5101349948][Bingbing Du]], [[https://openalex.org/A5053897140][Guanqun Guo]], [[https://openalex.org/A5062891953][Yanli Zhou]], [[https://openalex.org/A5084486318][Xuelin Dong]], Journal of alloys and compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.175584 
     
No abstract    

    

* Tailoring of bulk oxygen vacancies in BiVO4 photoanodes via crystallization dynamics engineering for boosted photoelectrochemical water oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400722422
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.154064")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400722422"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400722422"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400722422"))][Get cited by]]

OpenAlex: https://openalex.org/W4400722422 (Open access: False)
    
[[https://openalex.org/A5100640301][Shiyuan Wang]], [[https://openalex.org/A5059068965][Jie Jian]], [[https://openalex.org/A5100373596][Fan Li]], [[https://openalex.org/A5101601747][Ziying Zhang]], [[https://openalex.org/A5000587290][Xiao‐Long Feng]], [[https://openalex.org/A5023422087][Yazhou Shuang]], [[https://openalex.org/A5100354546][Yang Zhang]], [[https://openalex.org/A5001158309][Yong Wang]], [[https://openalex.org/A5102000251][Jiulong Wang]], [[https://openalex.org/A5101742243][Shouxin Zhang]], [[https://openalex.org/A5101678065][Lichao Jia]], [[https://openalex.org/A5100757645][Hongqiang Wang]], Chemical engineering journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.154064 
     
No abstract    

    

* Bimetallic NiCo-MOF engineering on foam nickel for efficient oxygen evolution reaction in wide-pH-value water and seawater  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400722642
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.154093")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400722642"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400722642"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400722642"))][Get cited by]]

OpenAlex: https://openalex.org/W4400722642 (Open access: False)
    
[[https://openalex.org/A5081064895][Shuangyan Shang]], [[https://openalex.org/A5032863029][Weichang Li]], [[https://openalex.org/A5100427812][Lixin Zhang]], [[https://openalex.org/A5102879357][Suyi Liu]], [[https://openalex.org/A5101355201][Qinyu Tang]], [[https://openalex.org/A5100609414][Chuanqi Feng]], [[https://openalex.org/A5100440504][Chunsheng Li]], [[https://openalex.org/A5006832624][Yanzhi Sun]], [[https://openalex.org/A5068732890][Huimin Wu]], Chemical engineering journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.154093 
     
No abstract    

    

* Reactive oxygen species generation for catalysis and biotherapeutic applications based on crystalline porous materials  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400726429
:TOPICS: Nanomaterials with Enzyme-Like Characteristics, Nanotechnology and Imaging for Cancer Therapy and Diagnosis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-11-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ccr.2024.216068")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400726429"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400726429"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400726429"))][Get cited by]]

OpenAlex: https://openalex.org/W4400726429 (Open access: False)
    
[[https://openalex.org/A5065976322][Yunyang Qian]], [[https://openalex.org/A5100374368][Bo Li]], [[https://openalex.org/A5100671374][Muhammad Irfan]], [[https://openalex.org/A5100439911][Dandan Li]], [[https://openalex.org/A5038041764][Hai‐Long Jiang]], Coordination chemistry reviews. 518(None)] 2024. https://doi.org/10.1016/j.ccr.2024.216068 
     
No abstract    

    

* CoFe2O4 supported on g-CN nanosheet for oxygen evolution reaction in basic media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400728693
:TOPICS: Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.133")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400728693"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400728693"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400728693"))][Get cited by]]

OpenAlex: https://openalex.org/W4400728693 (Open access: False)
    
[[https://openalex.org/A5083362806][K. M. Ashfaq]], [[https://openalex.org/A5012177096][Muhammad Imran Saleem]], [[https://openalex.org/A5005733480][Ahmed A. Ibrahim]], [[https://openalex.org/A5078102681][Abdullah G. Al‐Sehemi]], [[https://openalex.org/A5104195938][Muhammad Arslan Aslam]], [[https://openalex.org/A5051797797][A.M.A. Henaish]], [[https://openalex.org/A5050910877][Muhammad Jahangir Khan]], [[https://openalex.org/A5045982614][Khurshid Ahmad]], International journal of hydrogen energy. 80(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.133 
     
No abstract    

    

* (Bi2O3)0.705(Er2O3)0.245(WO3)0.05–Co3O4: A new oxygen electrode material with high oxygen reduction and evolution reaction catalytic activity for low-temperature solid oxide electrochemical cells  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400731103
:TOPICS: Solid Oxide Fuel Cells, Emergent Phenomena at Oxide Interfaces, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235052")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400731103"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400731103"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400731103"))][Get cited by]]

OpenAlex: https://openalex.org/W4400731103 (Open access: False)
    
[[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5035942683][Jiaqi Tang]], [[https://openalex.org/A5100357431][Chengxin Li]], [[https://openalex.org/A5042561898][Shan-Lin Zhang]], Journal of power sources. 614(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235052 
     
No abstract    

    

* Enhanced Oxygen Evolution Reaction Catalytic Properties of Novel Nanowire Structures from FeCo‐MOFs/GO via Low‐Temperature Annealing  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400734512
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ente.202400058")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400734512"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400734512"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400734512"))][Get cited by]]

OpenAlex: https://openalex.org/W4400734512 (Open access: False)
    
[[https://openalex.org/A5071919196][Hao Liang]], [[https://openalex.org/A5031974724][Yujie Lv]], [[https://openalex.org/A5101391725][Kui Tang]], [[https://openalex.org/A5070086944][Yuxin Chai]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5100373457][Yuyang Liu]], [[https://openalex.org/A5101580576][Jianping Sun]], Energy technology. None(None)] 2024. https://doi.org/10.1002/ente.202400058 
     
Metal‐organic frameworks (MOFs) often suffer from poor stability, making them suitable precursors for metal oxides/porous carbon catalysts in the oxygen evolution reaction via pyrolysis. High‐temperature treatment, however, leads to significant loss of active sites. To address this, Fe‐MOFs, FeCo‐MOFs, and FeCo‐MOFs/graphene oxide (GO) composites using a one‐pot hydrothermal method are synthesized and annealed at a low temperature of 300 °C. Characterization reveals that FeCo‐MOFs/GO composites possess unique nanowire structures mixed with a small amount of nanoflakes. It is believed that introducing graphene oxide plays a critical role in forming this structure, because the defects in GO provide numerous nucleation sites for nanowire growth. With high specific surface area and good stability, these nanostructures show a low overpotential of 261.5 mV at a current density of 10 mA cm − 2 and a Tafel slope of 20.47 mV dec −1 in 1 mol L −1 KOH alkaline water electrolysis. Density functional theory calculations further indicate that the synergistic effect of Fe and Co atoms enhances the catalytic activity.    

    

* Rational Construction of a 3D Self-Supported Electrode Based on ZIF-67 and Amorphous NiCoP for an Enhanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400741414
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c01863")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400741414"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400741414"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400741414"))][Get cited by]]

OpenAlex: https://openalex.org/W4400741414 (Open access: False)
    
[[https://openalex.org/A5086361638][Mengya Cao]], [[https://openalex.org/A5100907109][Yanrong Li]], [[https://openalex.org/A5038834523][Yijia Cao]], [[https://openalex.org/A5100862113][Yusong Wen]], [[https://openalex.org/A5100717157][Li Bao]], [[https://openalex.org/A5086264250][Qing Shen]], [[https://openalex.org/A5003733633][Wen Gu]], Inorganic chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c01863 
     
The development of efficient and Earth-abundant electrocatalysts for the oxygen evolution reaction (OER) is an urgent requirement in the field of electrochemical water splitting. The electrocatalytic performance of the OER can be greatly enhanced by the synergistic combination of zeolite imidazolate frameworks (ZIFs) and transition-metal phosphides, both of which individually exhibit promising capabilities in this regard. In this study, a novel amorphous NiCoP deposited on ZIF-67 sheets supported on Ni foam (labeled as NiCoP/ZIF-67/NF) as an OER electrocatalytic material was successfully synthesized using a simple, secure, and time-efficient two-step strategy. The experimental results demonstrate that NiCoP/ZIF-67/NF possesses a large active surface area with abundant active sites. Also, the synergistic effect and interaction between NiCoP and ZIF-67, as well as between Ni and Co within NiCoP, effectively enhance its electrochemical performance under alkaline conditions. Consequently, NiCoP/ZIF-67/NF exhibits outstanding catalytic activity for OER with an overpotential (η) of 175 mV at a current density of 10 mA cm    

    

* Unraveling the Role of Particle Size and Nanostructuring on the Oxygen Evolution Activity of Fe-Doped NiO  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400741431
:TOPICS: Electrocatalysis for Energy Conversion, Advanced Materials for Smart Windows, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02329")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400741431"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400741431"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400741431"))][Get cited by]]

OpenAlex: https://openalex.org/W4400741431 (Open access: True)
    
[[https://openalex.org/A5027366818][Reshma R. Rao]], [[https://openalex.org/A5076988276][Alberto Bucci]], [[https://openalex.org/A5003975479][Sacha Corby]], [[https://openalex.org/A5005889599][Benjamin Moss]], [[https://openalex.org/A5026417092][Caiwu Liang]], [[https://openalex.org/A5021705835][Aswin Gopakumar]], [[https://openalex.org/A5039064548][Ifan E. L. Stephens]], [[https://openalex.org/A5013865355][Julio Lloret‐Fillol]], [[https://openalex.org/A5086035043][James R. Durrant]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02329 
     
No abstract    

    

* B‐site Doping Boosts the OER and ORR Performance of Double Perovskite Oxide as Air Cathode for Zinc‐Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400769965
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cphc.202400531")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400769965"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400769965"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400769965"))][Get cited by]]

OpenAlex: https://openalex.org/W4400769965 (Open access: False)
    
[[https://openalex.org/A5057821324][Cagla Ozgur]], [[https://openalex.org/A5015526496][Tuncay Erdil]], [[https://openalex.org/A5093335060][Uygar Geyikci]], [[https://openalex.org/A5083328619][İlker Yıldız]], [[https://openalex.org/A5076666313][Ersu LOKCU]], [[https://openalex.org/A5089482069][Çiğdem Toparlı]], ChemPhysChem. None(None)] 2024. https://doi.org/10.1002/cphc.202400531 
     
Double perovskite oxides are key players as electrocatalytic oxygen catalysts in alkaline media. In this study, we synthesized B‐site doped NdBaCoaFe2‐aO5+δ (a= 1.0, 1.4, 1.6, 1.8) electrocatalysts, systematically to probe their bifunctionality and assess their performance in zinc‐air batteries as air cathodes. X‐ray photoelectron spectroscopy analysis reveals a correlation between iron reduction and increased oxygen vacancy content, influencing electrocatalyst bifunctionality by lowering the work function. The electrocatalyst with highest cobalt content, NdBaCo1.8Fe0.2O5+δ exhibited a bifunctional index of 0.95 V, outperforming other synthesized electrocatalysts. Remarkably, NdBaCo1.8Fe0.2O5+δ, demonstrated facilitated charge transfer rate in oxygen evolution reaction with four‐electron oxygen reduction reaction process. As an air cathode in a zinc‐air battery, NdBaCo1.8Fe0.2O5+δ demonstrated superior performance characteristics, including maximum capacity of 428.27 mA h at 10 mA cm‐2 discharge current density, highest peak power density of 64 mW cm‐2, with an outstanding durability and stability. It exhibits lowest voltage gap change between charge and discharge even after 350 hours of cyclic operation with a rate capability of 87.14%.    

    

* La-induced nanosheet intercalated spheroid hierarchical structure with abundant oxygen vacancy promotes electrocatalytic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400798723
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cy00653d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400798723"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400798723"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400798723"))][Get cited by]]

OpenAlex: https://openalex.org/W4400798723 (Open access: False)
    
[[https://openalex.org/A5100401443][Di Wang]], [[https://openalex.org/A5056770846][Jianguo Tang]], [[https://openalex.org/A5068191838][Wenguang Cui]], [[https://openalex.org/A5091561399][Chaozheng He]], [[https://openalex.org/A5002961462][Zhongkui Zhao]], Catalysis science & technology. None(None)] 2024. https://doi.org/10.1039/d4cy00653d 
     
The electron coupling effect at the interface, as well as the introduction of oxygen vacancy (Ov), play critical roles in the electrocatalytic activity. The key to lowering the energy barrier...    

    

* Tailoring the oxygen evolution reaction activity of lanthanide-doped NiFe-LDHs through lanthanide contraction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400673171
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.154059")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400673171"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400673171"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400673171"))][Get cited by]]

OpenAlex: https://openalex.org/W4400673171 (Open access: False)
    
[[https://openalex.org/A5100340974][Min Wang]], [[https://openalex.org/A5071740726][Kai-Sheng Chen]], [[https://openalex.org/A5104617175][ZihaoYan]], [[https://openalex.org/A5100371668][Yongjun Chen]], [[https://openalex.org/A5100693380][Hongtao Liu]], [[https://openalex.org/A5101631873][Pengfei Yin]], Chemical engineering journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.154059 
     
No abstract    

    

* Role of Heteroatom Doping in Enhancing the Catalytic Activities and Stability of Atomically Dispersed Metal Catalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400692872
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.4c02747")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400692872"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400692872"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400692872"))][Get cited by]]

OpenAlex: https://openalex.org/W4400692872 (Open access: False)
    
[[https://openalex.org/A5029998682][Xueqi Cheng]], [[https://openalex.org/A5016063742][Dengfeng Wu]], [[https://openalex.org/A5100748572][Hui Xu]], [[https://openalex.org/A5102878658][Wei Zhang]], Journal of physical chemistry. C./Journal of physical chemistry. C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.4c02747 
     
No abstract    

    

* Fe-Mof-Based Catalysts for Oxygen Evolution Reaction: Microenvironment Regulated by Organic Ligands, Metals and Carbonization Synergistically  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400672123
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4896757")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400672123"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400672123"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400672123"))][Get cited by]]

OpenAlex: https://openalex.org/W4400672123 (Open access: False)
    
[[https://openalex.org/A5089630307][Chenchen Ding]], [[https://openalex.org/A5031487651][Wenge Zhong]], [[https://openalex.org/A5025175329][Yuqi Cao]], [[https://openalex.org/A5100528425][Tingting Ma]], [[https://openalex.org/A5018766240][Huimin Ye]], [[https://openalex.org/A5005640649][Zheng Fang]], [[https://openalex.org/A5101770125][Yirong Feng]], [[https://openalex.org/A5101844206][Shuangfei Zhao]], [[https://openalex.org/A5100616156][Jiming Yang]], [[https://openalex.org/A5101667147][Yuguang Li]], [[https://openalex.org/A5058192166][L. Shen]], [[https://openalex.org/A5001372636][Wei He]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4896757 
     
No abstract    

    

* Fabrication of Fe–Zr, Co–Zr, and Ni–Zr Catalysts to Boost CNTs Synthesis from Plastic Wastes and the Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400725437
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.langmuir.4c01357")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400725437"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400725437"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400725437"))][Get cited by]]

OpenAlex: https://openalex.org/W4400725437 (Open access: False)
    
[[https://openalex.org/A5101019003][Xinyao Sun]], [[https://openalex.org/A5069731675][Xu Hou]], [[https://openalex.org/A5102750183][Dong Ao]], [[https://openalex.org/A5040483273][Changchang Tian]], [[https://openalex.org/A5013412356][Li Yin]], [[https://openalex.org/A5057929231][Jing Huang]], [[https://openalex.org/A5034795109][Tingting Cui]], [[https://openalex.org/A5056966293][Enxian Yuan]], Langmuir. None(None)] 2024. https://doi.org/10.1021/acs.langmuir.4c01357 
     
The efficient conversion of plastic wastes to high-value carbon materials like carbon nanotubes (CNTs) is one important issue about the rational recycling, reduction, and reuse of solid wastes. Herein, Fe-, Co-, and Ni-Zr catalysts were prepared and used for CNTs synthesis from polyethylene (PE) waste via a two-stage reaction system. At the same time, the effects of the PE/catalyst ratio and reaction temperature on CNTs synthesis have been studied. Compared with Co-Zr and Ni-Zr, Fe-Zr exhibited the best activity in CNTs synthesis from PE, and it achieved the highest CNTs yield of 806.3 mg/g (per gram of Fe-Zr) at 800 °C with a PE/catalyst ratio of 4. Furthermore, the obtained Fe-Zr/CNTs composite exhibited a low overpotential of 267 mV for the electrocatalytic oxygen evolution reaction (OER) at 20 mA/cm    

    

* Enhanced oxygen evolution reaction by modulating the electronic states of a flexible van der Waals membranous catalyst with infinite-layer phase  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400612712
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.07.133")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400612712"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400612712"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400612712"))][Get cited by]]

OpenAlex: https://openalex.org/W4400612712 (Open access: False)
    
[[https://openalex.org/A5015772054][Hang Xu]], [[https://openalex.org/A5054404994][Siqi Meng]], [[https://openalex.org/A5101814743][Yukui Zhang]], [[https://openalex.org/A5020829478][Linglong Hu]], [[https://openalex.org/A5050640373][Daming Yang]], [[https://openalex.org/A5101328219][Ze Gao]], [[https://openalex.org/A5027458993][Zeyu Zhao]], [[https://openalex.org/A5089120773][Ming Feng]], Ceramics international. None(None)] 2024. https://doi.org/10.1016/j.ceramint.2024.07.133 
     
No abstract    

    

* High-temperature structural evolution and mechanical properties of oxygen-containing NiCrAlY coatings  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400644696
:TOPICS: Thermal Barrier Coatings for Gas Turbines, Synthesis and Properties of Cemented Carbides, Mechanical Properties of Thin Film Coatings
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.160745")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400644696"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400644696"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400644696"))][Get cited by]]

OpenAlex: https://openalex.org/W4400644696 (Open access: False)
    
[[https://openalex.org/A5103176054][Bin Peng]], [[https://openalex.org/A5011349887][Yu X. Xu]], [[https://openalex.org/A5101767378][Qimin Wang]], Applied surface science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.160745 
     
No abstract    

    

* Mechanochemically synthesized RuO2‐doped LaMnO3 perovskites as bifunctional cathodes for rechargeable Zn/air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400676634
:TOPICS: Conducting Polymer Research, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400341")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400676634"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400676634"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400676634"))][Get cited by]]

OpenAlex: https://openalex.org/W4400676634 (Open access: False)
    
[[https://openalex.org/A5050659541][Antonio J. Fernández Romero]], [[https://openalex.org/A5104617472][Katherine Jejen]], [[https://openalex.org/A5104617473][Florencio Santos Cutillas]], [[https://openalex.org/A5037487505][J. J. López Cascales]], [[https://openalex.org/A5031880162][François Huet]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400341 
     
Herein, we have developed LaMnO3 (LMO) perovskite‐based electrocatalysts of oxygen reduction and oxygen evolution reactions (ORR and OER) in a basic aqueous solution. Mechanochemical grinding and thermal annealing leads to highly‐pure perovskites as shown by X‐ray diffraction. This methodology allows as well for a swift integration of RuO2 additive which improves especially the oxygen evolution reaction. ORR have been analyzed by rotating ring‐disk electrode (RRDE). Eventually, these catalysts are employed in Zn/air batteries resulting in specific capacity values of 12.76 Ahg‐1 at 1 Ag‐1, when LMO‐RuO2 (LMO‐Ru) was used as catalyst in the positive electrodes. Besides, high operational stability of Zn/air batteries for over 100 cycles was obtained, saving 1,46 mWh per cycle when LMO‐Ru was used with respect to pure LMO.    

    

* Activating Cobalt Inverse Spinel Oxides via Fe Substitution for Enhanced Water Splitting Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400697118
:TOPICS: Catalytic Reduction of Nitro Compounds, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4se00468j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400697118"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400697118"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400697118"))][Get cited by]]

OpenAlex: https://openalex.org/W4400697118 (Open access: True)
    
[[https://openalex.org/A5047126873][Saraswati Roy]], [[https://openalex.org/A5068743211][Sounak Roy]], Sustainable energy & fuels. None(None)] 2024. https://doi.org/10.1039/d4se00468j 
     
Owing to the expeditious kinetics and remarkable catalytic prowess, spinel oxides have garnered significant attention as promising non-precious metal electrocatalysts for oxygen evolution reaction (OER). Modulating the oxidation state of...    

    

* Zn Leaching Reconstructs High-Entropy Hydroxyl Oxides for Efficient OER at Large Current Density  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400672638
:TOPICS: Electron Beam Lithography: Resolution and Applications, Surface Analysis and Electron Spectroscopy Techniques, Electrodeposition and Composite Coatings
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta03296a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400672638"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400672638"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400672638"))][Get cited by]]

OpenAlex: https://openalex.org/W4400672638 (Open access: False)
    
[[https://openalex.org/A5101785788][Xiaolong Liang]], [[https://openalex.org/A5100440745][Kang Xu]], [[https://openalex.org/A5001207241][Wenqian Gao]], [[https://openalex.org/A5101814743][Yukui Zhang]], [[https://openalex.org/A5019609127][Tingting Lv]], [[https://openalex.org/A5010480846][H. Zhang]], [[https://openalex.org/A5101814934][Jun Lv]], [[https://openalex.org/A5040726095][Lie Zou]], [[https://openalex.org/A5046493050][Jinxuan Liu]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta03296a 
     
The study of oxygen evolution reaction (OER) catalysts is crucial for the development of hydrogen energy technology. However, industrial water splitting requires high current densities, and monometallic catalysts have poor...    

    

* Optical in situ deciphering of the surface reconstruction–assistant multielectron transfer event of single Co 3 O 4 nanoparticles  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400729762
:TOPICS: Formation and Properties of Nanocrystals and Nanostructures, Advanced Materials for Smart Windows, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1073/pnas.2407146121")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400729762"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400729762"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400729762"))][Get cited by]]

OpenAlex: https://openalex.org/W4400729762 (Open access: True)
    
[[https://openalex.org/A5005667904][Bo Jiang]], [[https://openalex.org/A5100327715][Haoran Li]], [[https://openalex.org/A5100391983][Wei Wang]], [[https://openalex.org/A5100644358][Hui Wang]], Proceedings of the National Academy of Sciences of the United States of America. 121(30)] 2024. https://doi.org/10.1073/pnas.2407146121 
     
Surface reconstruction determines the fate of catalytic sites on the near-surface during the oxygen evolution reaction. However, deciphering the conversion mechanism of various intermediate-states during surface reconstruction remains a challenge. Herein, we employed an optical imaging technique to draw the landscape of dynamic surface reconstruction on individual Co    

    

* Electronic-Structure Transformation of Platinum-Rich Nanowires as Efficient Electrocatalyst for Overall Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400688649
:TOPICS: Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c03946")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400688649"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400688649"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400688649"))][Get cited by]]

OpenAlex: https://openalex.org/W4400688649 (Open access: False)
    
[[https://openalex.org/A5019192072][Bolin Zhao]], [[https://openalex.org/A5103203497][Chuhao Liu]], [[https://openalex.org/A5070768020][Azhar Mahmood]], [[https://openalex.org/A5046716176][Shamraiz Hussain Talib]], [[https://openalex.org/A5005623458][Pengchong Wang]], [[https://openalex.org/A5100702227][Ying He]], [[https://openalex.org/A5021223547][Dongyang Qu]], [[https://openalex.org/A5100710974][Li Niu]], ACS applied materials & interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c03946 
     
Platinum (Pt) has been widely used as cathodic electrocatalysts for the hydrogen evolution reaction (HER) but unfortunately neglected as an anodic electrocatalyst for the oxygen evolution reaction (OER) due to excessively strong bonding with oxygen species in water splitting electrolyzers. Herein we report that fine control over the electronic-structure and local-coordination environment of Pt-rich PtPbCu nanowires (NWs) by doping of iridium (Ir) lowers the overpotential of the OER and simultaneously suppresses the overoxidation of Pt in IrPtPbCu NWs during water electrolysis. In light of the one-dimensional morphology featured with atomically dispersed IrO    

    

* The cobalt-based metal organic frameworks array derived CoFeNi-layered double hydroxides anode and CoP/FeNi2P heterojunction cathode for ampere-level seawater overall splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400614475
:TOPICS: Aqueous Zinc-Ion Battery Technology, Lithium-ion Battery Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2024-12-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.07.098")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400614475"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400614475"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400614475"))][Get cited by]]

OpenAlex: https://openalex.org/W4400614475 (Open access: False)
    
[[https://openalex.org/A5100657035][Liyuan Liu]], [[https://openalex.org/A5100633076][Zhen Zhang]], [[https://openalex.org/A5061662290][S. Gu]], [[https://openalex.org/A5009864572][Yanan Liu]], [[https://openalex.org/A5101617508][Ying Deng]], [[https://openalex.org/A5100379938][Yuqing Li]], [[https://openalex.org/A5050093139][Zhenyu Xiao]], [[https://openalex.org/A5100389906][Kang Liu]], [[https://openalex.org/A5002735037][Zexing Wu]], [[https://openalex.org/A5100435779][Lei Wang]], Journal of colloid and interface science. 676(None)] 2024. https://doi.org/10.1016/j.jcis.2024.07.098 
     
The seawater electrolysis technology powered by renewable energy is recognized as the promising "green hydrogen" production method to solve serious energy and environmental problems. The lack of low-cost and ampere-level current OER (oxygen evolution reaction) and HER (hydrogen evolution reaction) catalysis limits their industrial application. In this work, a unique tri-metal (Co/Fe/Ni) layered double hydroxide hollow array anode catalyst (CFN-LDH/NF) and the CoP/FeNi    

    

* Component leaching of water oxidation electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400746813
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/inf2.12609")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400746813"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400746813"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400746813"))][Get cited by]]

OpenAlex: https://openalex.org/W4400746813 (Open access: True)
    
[[https://openalex.org/A5100413146][Gao Chen]], [[https://openalex.org/A5068861080][Yanping Zhu]], [[https://openalex.org/A5045709420][Sixuan She]], [[https://openalex.org/A5026268638][Zezhou Lin]], [[https://openalex.org/A5019776537][Hainan Sun]], [[https://openalex.org/A5064469812][Haitao Huang]], InfoMat. None(None)] 2024. https://doi.org/10.1002/inf2.12609 
     
Abstract Most electrocatalysts are known to experience structural change during the oxygen evolution reaction (OER) process. Considerable endeavors have been dedicated thus far to comprehending the catalytic process and uncovering the underlying mechanism. During the dynamic evolution of catalyst structure, component leaching of electrocatalysts is the most common phenomenon. This article offers a concise overview of recent findings and developments related to the leaching phenomena in the OER process in terms of fundamental understanding of leaching, advanced characterization techniques used to investigate leaching, leaching of inactive components, and leaching of active components. Leaching behaviors and the induced effects in various kinds of OER catalysts are discussed, progress in manipulating leaching amount/degree toward a tunable surface evolution is spotlighted, and finally, three representative types of structure transformations induced by leaching metastable species in OER condition are proposed. By understanding the process of component leaching in the OER, it will provide more guidance for the rational design of superior electrocatalysts. image    

    

* Multiple-perspective design of hollow-structured cerium-vanadium-based nanopillar arrays for enhanced overall water electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400621329
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.07.104")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400621329"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400621329"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400621329"))][Get cited by]]

OpenAlex: https://openalex.org/W4400621329 (Open access: False)
    
[[https://openalex.org/A5091640230][Yi Qin]], [[https://openalex.org/A5045731479][Caizheng Wang]], [[https://openalex.org/A5040940320][Xinran Hou]], [[https://openalex.org/A5100631044][Huijie Zhang]], [[https://openalex.org/A5084750748][Zhaoyang Tan]], [[https://openalex.org/A5100604898][Xiaobin Wang]], [[https://openalex.org/A5046850864][Jingde Li]], [[https://openalex.org/A5041381623][Feichao Wu]], Journal of colloid and interface science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.07.104 
     
It is critical and challenging to develop highly active and low cost bifunctional electrocatalysts for the hydrogen/oxygen evolution reaction (HER/OER) in water electrolysis. Herein, we propose cerium-vanadium-based hollow nanopillar arrays supported on nickel foam (CeV-HNA/NF) as bifunctional HER/OER electrocatalysts, which are prepared by etching the V metal-organic framework with Ce salt and then pyrolyzing. Etching results in multidimensional optimizations of electrocatalysts, covering substantial oxygen vacancies, optimized electronic configurations, and an open-type structure of hollow nanopillar arrays, which contribute to accelerating the charge transfer rate, regulating the adsorption energy of H/O-containing reaction intermediates, and fully exposing the active sites. The reconstruction of the electrocatalyst is also accelerated by Ce doping, which results in highly active hydroxy vanadium oxide interfaces. Therefore, extremely low overpotentials of 170 and 240 mV under a current density of 100 mA cm    

    

* Lattice‐Confined Single‐Atom Catalyst: Preparation, Application and Electron Regulation Mechanism  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400657987
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smtd.202400530")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400657987"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400657987"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400657987"))][Get cited by]]

OpenAlex: https://openalex.org/W4400657987 (Open access: False)
    
[[https://openalex.org/A5100587485][Ting Ma]], [[https://openalex.org/A5087817454][Haibo Li]], [[https://openalex.org/A5047401798][Yamin Yu]], [[https://openalex.org/A5100619523][Kaixuan Wang]], [[https://openalex.org/A5100606245][Wei Yu]], [[https://openalex.org/A5102204226][Yu Shang]], [[https://openalex.org/A5101970865][Yu Bai]], [[https://openalex.org/A5059182665][Rongyu Zhang]], [[https://openalex.org/A5100629298][Yue Yang]], [[https://openalex.org/A5066685891][Xiaoyi Nie]], Small methods. None(None)] 2024. https://doi.org/10.1002/smtd.202400530 
     
Abstract Lattice‐confined single‐atom catalyst (LC SAC), featuring exceptional activity, intriguing stability and prominent selectivity, has attracted extensive attention in the fields of various reactions (e.g., hydrogen evolution reaction (HER), oxygen evolution reaction (OER), oxygen reduction reaction (ORR), etc.). To design a “smart” LC SAC for catalytic applications, one must systematically comprehend updated advances in the preparation, the application, and especially the peculiar electron regulation mechanism of LC SAC. In this review, the specific preparation methods of LC SAC based on general coordination strategy are updated, and its applications in HER, OER, ORR, N 2 reduction reaction (NRR), advanced oxidation processes (AOPs) and so forth are summarized to display outstanding activity, stability and selectivity. Uniquely, the electron regulation mechanisms are first and deeply discussed and can be primarily categorized as electron transfer bridge with monometallic active sites, novel catalytic centers with polymetallic active sites, and positive influence by surrounding environments. In the end, the existing issues and future development directions are put forward with a view to further optimize the performance of LC SAC. This review is expected to contribute to the in‐depth understanding and practical application of highly efficient LC SAC.    

    

* Theoretical study on the carbon nanomaterial‐supported Pt complex electrocatalysts for efficient and selective chlorine evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400735545
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/jcc.27466")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400735545"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400735545"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400735545"))][Get cited by]]

OpenAlex: https://openalex.org/W4400735545 (Open access: False)
    
[[https://openalex.org/A5078450012][Jewel Hossen]], [[https://openalex.org/A5077534241][Naoki Nakatani]], Journal of computational chemistry. None(None)] 2024. https://doi.org/10.1002/jcc.27466 
     
Chlorine is an important chemical which has long been produced in chlor-alkali process using dimensionally stable anodes (DSA). However, some serious drawbacks of DSA inspire the development of alternative anodes for chlorine evolution reaction (CER). In this study, we focused on the graphene- and carbon nanotube-supported platinum tetra-phenyl porphyrins as electrocatalysts for CER, which have been theoretically investigated based on density functional theory. Our results reveal that the supported substrates possess potential CER electrocatalytic activity with very low thermodynamic overpotentials (0.012-0.028 V) via Cl* pathway instead of ClO*. The electronic structures analyses showed that electron transfer from the support to the adsorbed chlorine via the Pt center leads to strong Pt-Cl interactions. Furthermore, the supported electrocatalysts exhibited excellent selectivity toward CER because of high overpotentials and reaction barriers of oxygen evolution process. Therefore, our results may pave the way for designing CER electrocatalyst utilizing emerging carbon nanomaterials.    

    

* Development of highly active and robust Cu-Co–rGO electro-catalytic electrode for OER  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400646882
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4589766/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400646882"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400646882"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400646882"))][Get cited by]]

OpenAlex: https://openalex.org/W4400646882 (Open access: False)
    
[[https://openalex.org/A5051216176][P.M. Aiswarya]], [[https://openalex.org/A5101967359][R. Manu]], No host. None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4589766/v1 
     
Abstract In the present work a facile method was adopted for the fabrication of highly active and dimensionally stable cobalt-reduced graphene oxide (rGO) based composite electrode for OER process. The metal loading and the amount of graphene was optimized for better performance of the electrode. The development of these type of electrodes is noteworthy taking the advantage of the method and the materials used. The morphology and the composition were analyzed through scanning electron microscopy (SEM), energy dispersive X-ray analysis (EDAX) and X-ray photo electron spectroscopy (XPS). Spectroscopic characterization was done using Fourier transform infrared (FTIR) analysis. Electrochemical characterization revealed excellent electro-catalytic activity of the prepared electrode and strongly suggest synergistic reaction between Co3O4 and rGO. The developed electrode can realize excellent Oxygen Evolution Reaction (OER) activity in alkaline media with low over potential and low tafel slope with long-term stability as evidenced from various analysis.    

    

* Nonpyrolytic Fe‐N‐C/Fe2O3 heterostructure with RuO2‐like OER Activity Synthesized via Polyacrylonitrile‐derived Conjugated Pyridinic‐nitrogen‐carbon Sheet  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400694809
:TOPICS: Desulfurization Technologies for Fuels, Catalytic Nanomaterials, Mesoporous Materials
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400786")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400694809"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400694809"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400694809"))][Get cited by]]

OpenAlex: https://openalex.org/W4400694809 (Open access: False)
    
[[https://openalex.org/A5001986022][Richard Appiah‐Ntiamoah]], [[https://openalex.org/A5058562100][Hern Kim]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400786 
     
Pyrolytic single Fe atom‐nitrogen‐carbon materials (Fe‐N‐C) and their derivatives are excellent catalysts for electrochemical oxygen reduction reactions. However, they exhibit poor oxygen evolution reaction (OER) activity due to non‐optimal Fe‐O* bonding. This limitation is overcome via electronic structure modulation (i.e., tuning the heteroatom type, concentration, and location within Fe’s n ≥ 1 coordination sphere). However, the methods used are complex and energy‐intensive (i.e., 1000 to 1200°C) raising concerns about reproducibility and cost. This study introduces a method for synthesizing nonpyrolytic Fe‐N‐C/Fe2O3 composites with similar electronic structure modulation as pyrolytic Fe‐N‐C and OER activity akin to commercial RuO2. The methodology involves doping low‐melting hydrated Fe‐salts in electrospun polyacrylonitrile nanofiber to catalyze its transformation into conjugated pyridinic‐N‐rich graphite‐like sheets (i.e., N‐C) at 300°C. N‐C chelate effectively with oxygen‐vacant (Ov)‐rich Fe atoms derived from Fe2O3 NPs resulting in Fe‐N‐C/Fe2O3 heterostructures. The Fe2O3 coupling effectively tunes Fe‐N‐C’s electronic structure via Ov modulation. Consequently, the Fermi and d‐orbital energy levels are optimized leading to partial filling of the antibonding states, optimal Fe‐O* bonding, high electrochemically active surface area, and OER activity. Because Fe‐N‐C/Fe2O3 is synthesized at 300 oC using well‐established techniques, its complexity and cost are favorable compared to pyrolytic Fe‐N‐C materials.    

    

* A Solid‐Solution with Asymmetric Ni‐O‐Cr Sites for Boosting Protonation toward Anodic Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400663772
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202401501")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400663772"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400663772"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400663772"))][Get cited by]]

OpenAlex: https://openalex.org/W4400663772 (Open access: False)
    
[[https://openalex.org/A5010186619][Yihan Feng]], [[https://openalex.org/A5048686427][Xunlu Wang]], [[https://openalex.org/A5100743741][Junqing Ma]], [[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5051820883][Qiunan Liu]], [[https://openalex.org/A5062940537][Kazu Suenaga]], [[https://openalex.org/A5100344302][Wei Chen]], [[https://openalex.org/A5001911896][Jitang Zhang]], [[https://openalex.org/A5104343821][Yin Zhou]], [[https://openalex.org/A5100727960][Jiacheng Wang]], Advanced energy materials. None(None)] 2024. https://doi.org/10.1002/aenm.202401501 
     
Abstract Replacing the slow protonation process of oxygen evolution reaction (OER) with the fast protonation of alcohol electro‐oxidation can decrease the driving potentials, thus improving overall efficiency of electrochemical devices. However, the formation of effective catalytic sites for alcohol oxidation remains challenging in accelerating protonation to inhibit metal leaching and improve catalyst stability. Herein, asymmetric Ni‐O‐Cr sites are constructed by alloying Cr into the NiO matrix to optimize coordination environments, showing significantly enhanced stability during alcohol electro‐oxidation. The asymmetric Ni‐O‐Cr can maintain constant valence states of Cr and Ni during alcohol oxidation, efficiently suppressing metal dissolution even at high oxidation potentials. In situ electrochemical characterizations combined with theoretical calculations indicate that asymmetric Ni‐O‐Cr can improve adsorption and activation of OH* and alcohol molecules compared to pure NiO, thus increasing anodic kinetics. The theoretical results also indicate that the smaller gap of Ni 3 d ‐O 2 p in asymmetric Ni‐O‐Cr strengthens charge transfer, leading to fast protonation of catalytic sites with enhanced stability. This work gives insights into boosting anodic protonation using asymmetric sites‐enriched solid‐solution electrocatalysts.    

    

* Closed‐Loop Direct Upcycling of Spent Ni‐Rich Layered Cathodes into High‐Voltage Cathode Materials  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400657884
:TOPICS: Battery Recycling and Rare Earth Recovery, Lithium-ion Battery Technology, Global E-Waste Recycling and Management
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202407029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400657884"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400657884"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400657884"))][Get cited by]]

OpenAlex: https://openalex.org/W4400657884 (Open access: False)
    
[[https://openalex.org/A5075721531][Haocheng Ji]], [[https://openalex.org/A5050681387][Junxiong Wang]], [[https://openalex.org/A5102614317][Haotian Qu]], [[https://openalex.org/A5100450066][Junfeng Li]], [[https://openalex.org/A5068187721][Wenhai Ji]], [[https://openalex.org/A5021631150][Xiao Qiu]], [[https://openalex.org/A5040878095][Yanfei Zhu]], [[https://openalex.org/A5040364007][Hengyu Ren]], [[https://openalex.org/A5057527162][Ruyu Shi]], [[https://openalex.org/A5029667588][Guanjun Ji]], [[https://openalex.org/A5101026837][Wenguang Zhao]], [[https://openalex.org/A5028227545][Guangmin Zhou]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202407029 
     
Abstract Facing the resource and environmental pressures brought by the retiring wave of lithium‐ion batteries (LIBs), direct recycling methods are considered to be the next generation's solution. However, the contradiction between limited battery life and the demand for rapidly iterating technology forces the direct recovery paradigm to shift toward “direct upcycling.” Herein, a closed‐loop direct upcycling strategy that converts waste current collector debris into dopants is proposed, and a highly inclusive eutectic molten salt system is utilized to repair structural defects in degraded polycrystalline LiNi 0.83 Co 0.12 Mn 0.05 O 2 cathodes while achieving single‐crystallization transformation and introducing Al/Cu dual‐doping. Upcycled materials can effectively overcome the two key challenges at high voltages: strain accumulation and lattice oxygen evolution. It exhibits comprehensive electrochemical performance far superior to commercial materials at 4.6 V, especially its fast charging capability at 15 C, and an impressive 91.1% capacity retention after 200 cycles in a 1.2 Ah pouch cell. Importantly, this approach demonstrates broad applicability to various spent layered cathodes, particularly showcasing its value in the recycling of mixed spent cathodes. This work effectively bridges the gap between waste management and material performance enhancement, offering a sustainable path for the recycling of spent LIBs and the production of next‐generation high‐voltage cathodes.    

    

* The Role of Carbon Catalyst Coatings in the Electrochemical Water Splitting Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400697323
:TOPICS: Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4682574/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400697323"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400697323"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400697323"))][Get cited by]]

OpenAlex: https://openalex.org/W4400697323 (Open access: False)
    
[[https://openalex.org/A5037328306][Graham N. Newton]], [[https://openalex.org/A5061967337][William J. V. Townsend]], [[https://openalex.org/A5078174445][Diego López-Alcalá]], [[https://openalex.org/A5045033540][Matthew A. Bird]], [[https://openalex.org/A5058037817][Graham A. Rance]], [[https://openalex.org/A5002418054][Johannes Biskupek]], [[https://openalex.org/A5023331891][José J. Baldoví]], [[https://openalex.org/A5007090343][Darren A. Walsh]], [[https://openalex.org/A5029597293][Lee Johnson]], [[https://openalex.org/A5081135562][Andrei N. Khlobystov]], [[https://openalex.org/A5017684207][Ute Kaiser]], No host. None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4682574/v1 
     
Abstract The availability of efficient electrocatalysts is key to the development of next-generation electrolyzers for water splitting to produce so-called ‘green hydrogen’ for a future hydrogen economy. The oxygen-evolution reaction (OER) is one half of the water-splitting reaction and is slow at most electrocatalysts. Designing inexpensive, sustainable, stable, and high-performance OER electrocatalysts remains the largest obstacle hindering the development of new electrolyzers. Carbon-coated metal/metal oxide (nano)particles have been used in such applications, but the role played by the carbon coatings in electrocatalysis has provoked debate in the field and is poorly understood. We show here that the carbon coating itself acts as the active site in OER, with the underlying material activating the carbon through a charge-transfer mechanism. We demonstrate this phenomenon using model catalysts consisting of < 2 nm metal-oxide electrocatalyst nanoparticles encapsulated within single-walled carbon nanotubes (SWNTs). Access of electrolyte to the encapsulated metal oxides is blocked by plugging the SWNTs with fullerenes, which shuts off redox processes inherent to the metal oxide but does not affect catalytic activity, showing that the carbon surface is the active OER site. This analysis is supported by electrochemical analysis, which shows that the rate-determining step for the OER is the same at SWNT with and without encapsuled metal oxides, but different to that at bare metal oxides. In-situ electrochemical Raman spectroscopy and computational analysis demonstrate that charge transfer from the carbon host to the metal oxide occurs during the OER. This charge transfer results in a decrease in electron density on the carbon surface, which may facilitate binding of –OH to the carbon surface, the first step in the OER and the RDS (as determined by electrochemical analysis) and may be key to the activity of carbon coated electrocatalysts. This understanding of how carbon coatings play an active role in electrocatalytic reactions is crucial for the development of future low cost, sustainable electrocatalysts for the OER, and the proposed charge transfer-driven mechanism could be tuneable to both oxidative and reductive reactions.    

    

* A phenomenological study of the evolution of shock-induced O I emission   lines in the spectrum of nova V2891 Cygni  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400702705
:TOPICS: Astrophysical Studies of Black Holes, Interactions of Low-Energy Electrons with Matter and Atoms, Optical 3D Laser Measurement Systems Optimization
:PUBLICATION_DATE: 2024-07-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2407.09634")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400702705"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400702705"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400702705"))][Get cited by]]

OpenAlex: https://openalex.org/W4400702705 (Open access: True)
    
[[https://openalex.org/A5043764828][Ruchi Pandey]], [[https://openalex.org/A5027445519][Mudit Srivastava]], [[https://openalex.org/A5076535429][Gargi Shaw]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2407.09634  ([[https://arxiv.org/pdf/2407.09634][pdf]])
     
The eruption of Nova V2891 Cygni in 2019 offers a rare opportunity to explore the shock-induced processes in novae ejecta. The spectral evolution shows noticeable differences in the evolution of various oxygen emission lines such as O I 7773 {\AA}, O I 8446 {\AA}, O I 1.1286 $\mu$m, O I 1.3164 $\mu$m, etc. Here, we use spectral synthesis code CLOUDY to study the temporal evolution of these oxygen emission lines. Our photoionization model requires the introduction of a component with a very high density ($n ~ 10^{11}$ cm$^{-3}$) and an enhanced oxygen abundance (O/H $\sim$ 28) to produce the O I 7773 {\AA} emission line, suggesting a stratification of material with high oxygen abundance within the ejecta. An important outcome is the behaviour of the O I 1.3164 $\mu$m line, which could only be generated by invoking the collisional ionization models in CLOUDY. Our phenomenological analysis suggests that O I 1.3164 $\mu$m emission originates from a thin, dense shell characterized by a high density of about $10^{12.5} - 10^{12.8}$ cm$^{-3}$, which is most likely formed due to the strong internal collisions. If such is the case, the O I 1.3164 $\mu$m emission presents itself as a tracer of shock-induced dust formation in V2891 Cyg. The collisional ionization models have also been successful in creating the high-temperature conditions ($~ 7.07 - 7.49 \times 10^5$ K) required to reproduce the observed high ionization potential coronal lines, which coincide with the epoch of dust formation and evolution of the O I 1.3164 $\mu$m emission line.    

    

* A phenomenological study of the evolution of shock-induced O i emission lines in the spectrum of nova V2891 Cygni  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400612249
:TOPICS: Astrophysical Studies of Black Holes, Optical 3D Laser Measurement Systems Optimization, Gamma-Ray Bursts and Supernovae Connections
:PUBLICATION_DATE: 2024-07-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/mnras/stae1719")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400612249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400612249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400612249"))][Get cited by]]

OpenAlex: https://openalex.org/W4400612249 (Open access: True)
    
[[https://openalex.org/A5043764828][Ruchi Pandey]], [[https://openalex.org/A5027445519][Mudit Srivastava]], [[https://openalex.org/A5076535429][Gargi Shaw]], Monthly Notices of the Royal Astronomical Society. None(None)] 2024. https://doi.org/10.1093/mnras/stae1719 
     
Abstract The eruption of Nova V2891 Cygni in 2019 offers a rare opportunity to explore the shock-induced processes in novae ejecta. The spectral evolution shows noticeable differences in the evolution of various oxygen emission lines such as O i 7773 Å, O i 8446 Å, O i 1.1286 μm, O i 1.3164 μm, etc. Here, we use spectral synthesis code cloudy to study the temporal evolution of these oxygen emission lines. Our photoionization model requires the introduction of a component with a very high density (n ∼ 1011 cm−3) and an enhanced oxygen abundance (O/H ∼ 28) to produce the O i 7773 Å emission line, suggesting a stratification of material with high oxygen abundance within the ejecta. An important outcome is the behaviour of the O i 1.3164 μm line, which could only be generated by invoking the collisional ionization models in cloudy. Our phenomenological analysis suggests that O i 1.3164 μm emission originates from a thin, dense shell characterized by a high density of about 1012.5 − 1012.8 cm−3, which is most likely formed due to the strong internal collisions. If such is the case, the O i 1.3164 μm emission presents itself as a tracer of shock-induced dust formation in V2891 Cyg. The collisional ionization models have also been successful in creating the high-temperature conditions (∼7.07 − 7.49 × 105 K) required to reproduce the observed high ionization potential coronal lines, which coincide with the epoch of dust formation and evolution of the O i 1.3164 μm emission line.    

    

* Charting the Electronic Structure for Discovering Low-cost Intermetallic Catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400654892
:TOPICS: Atom Probe Tomography Research, Catalytic Nanomaterials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta03880k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400654892"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400654892"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400654892"))][Get cited by]]

OpenAlex: https://openalex.org/W4400654892 (Open access: True)
    
[[https://openalex.org/A5024349225][Zhengda He]], [[https://openalex.org/A5070260665][Bin Ouyang]], Journal of materials chemistry. A. None(None)] 2024. https://doi.org/10.1039/d4ta03880k 
     
Discovering affordable, high-performance, and stable catalysts for the hydrogen evolution reaction (HER) and oxygen reduction reaction (ORR) is essential for the commercialization of clean hydrogen technology. In this study, we...    

    

* Melting at the base of a terrestrial magma ocean controlled by oxygen fugacity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400690152
:TOPICS: Tectonic and Geochronological Evolution of Orogens, Mantle Dynamics and Earth's Structure, Geological Evolution of the Arctic Region
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41561-024-01495-1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400690152"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400690152"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400690152"))][Get cited by]]

OpenAlex: https://openalex.org/W4400690152 (Open access: True)
    
[[https://openalex.org/A5041189782][Yanhao Lin]], [[https://openalex.org/A5047922721][Takayuki Ishii]], [[https://openalex.org/A5087659263][W. van Westrenen]], [[https://openalex.org/A5087236919][Tomoo Katsura]], [[https://openalex.org/A5085863207][Ho‐kwang Mao]], Nature geoscience. None(None)] 2024. https://doi.org/10.1038/s41561-024-01495-1 
     
Abstract Heat delivered from accretionary impacts is thought to have led to extensive melting of early Earth’s silicate mantle, resulting in a deep magma ocean covering the surface. The mantle’s oxygen fugacity is thought to have increased over accretion and core formation due to increasingly oxidated impactors and lower mantle self-oxidation, but the influence of this on the solidus of deep primitive mantle materials has not been well constrained. Here we assess the effect of oxygen fugacity on conditions at the bottom of a magma ocean by experimentally determining the solidus of mantle pyrolite at pressures of 16–26 GPa at high oxygen fugacities. We find that over this pressure range, the solidus in experiments conducted under oxidizing conditions is at least 230–450 °C lower than in experiments conducted under more reducing conditions. Assuming constant magma ocean temperature, this would imply a magma ocean floor that deepens by about 60 km for each log unit increase in mantle oxygen fugacity. The strong influence of oxygen fugacity on mantle melting suggests that models of early Earth thermal evolution and geochemical models of core formation should be reassessed.    

    

* In situ Ion Pumping Anodization to Confine Single‐Atom Fe onto TiO2 Nanotubes for Enhanced Noble‐Metal‐Free Photocatalytic Hydrogen Generation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400657865
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202407834")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400657865"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400657865"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400657865"))][Get cited by]]

OpenAlex: https://openalex.org/W4400657865 (Open access: False)
    
[[https://openalex.org/A5011043936][Jingtao Bi]], [[https://openalex.org/A5100613431][Chengqian Li]], [[https://openalex.org/A5045020120][Jie Ren]], [[https://openalex.org/A5088317350][Yingying Zhao]], [[https://openalex.org/A5068989045][Zhiyong Ji]], [[https://openalex.org/A5100427995][Ting Wang]], [[https://openalex.org/A5007836691][Xin Huang]], [[https://openalex.org/A5100732394][Hongxun Hao]], Advanced functional materials. None(None)] 2024. https://doi.org/10.1002/adfm.202407834 
     
Abstract Achieving a high dispersity of deposited transition metal is crucial in the anodization preparation of noble‐metal‐free composites for photocatalytic hydrogen generation. Herein, for the first time, an in situ ion pumping anodization method is proposed to confine single‐atom Fe within the spatially ordered structure of anodized TiO 2 nanotubes (TNT), assisted by ferric sodium salt of ethylenediaminetetraacetic acid (EDTA) as an “ion pump” to deliver Fe 3+ toward anodes. Both experimental and theoretical calculations confirm that highly dispersed single‐atom Fe can interact with single‐electron‐trapped oxygen vacancies (SETOV), effectively reducing the oxygen vacancy concentration in TiO 2 nanotubes. This reduction promotes efficient charge carrier separation through the Fe(III)/Fe(II) pathway and enhances hydrogen desorption, ultimately boosting the photocatalytic hydrogen evolution performance.    

    

* The smallest angiosperm genomes may be the price for effective traps of bladderworts.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400702093
:TOPICS: Strigolactone Signaling in Plant Interactions
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/aob/mcae107")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400702093"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400702093"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400702093"))][Get cited by]]

OpenAlex: https://openalex.org/W4400702093 (Open access: False)
    
[[https://openalex.org/A5084599136][František Zedek]], [[https://openalex.org/A5005238411][Jakub Šmerda]], [[https://openalex.org/A5104607216][Aneta Halasová]], [[https://openalex.org/A5037577398][Lubomír Adamec]], [[https://openalex.org/A5083348219][Adam Veleba]], [[https://openalex.org/A5040695617][Klára Plačková]], [[https://openalex.org/A5047966192][Petr Bureš]], PubMed. None(None)] 2024. https://doi.org/10.1093/aob/mcae107 
     
Species of the carnivorous family Lentibulariaceae exhibit the smallest genomes in flowering plants. We explored the hypothesis that their minute genomes result from the unique mitochondrial cytochrome c oxidase (COX) mutation. The mutation may boost mitochondrial efficiency, which is especially useful for suction-bladder traps of Utricularia, but also increase DNA-damaging reactive oxygen species, leading to genome shrinkage through deletion-biased DNA repair. We aimed to explore this mutation's impact on genome size, providing insights into genetic mutation roles in plant genome evolution under environmental pressures.    

    

* Elevational constraints on flight efficiency shape global gradients in avian wing morphology  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400747516
:TOPICS: Geometric Morphometrics and Statistical Analysis
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2024.07.12.603304")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400747516"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400747516"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400747516"))][Get cited by]]

OpenAlex: https://openalex.org/W4400747516 (Open access: False)
    
[[https://openalex.org/A5074331426][Jingyi Yang]], [[https://openalex.org/A5102538117][Chenyue Yang]], [[https://openalex.org/A5056180242][Hsi–Hsin Lin]], [[https://openalex.org/A5040268982][Alexander Charles Lees]], [[https://openalex.org/A5079773056][Joseph A. Tobias]], No host. None(None)] 2024. https://doi.org/10.1101/2024.07.12.603304 
     
Wings with elongated shape or larger surface area are associated with increased flight efficiency and dispersal ability in a wide range of animals from insects to birds. Inter- and intraspecific variation in these attributes of wing shape is determined by a range of factors - including foraging ecology, migration and climatic seasonality - all of which may drive latitudinal gradients in wing morphology. A separate hypothesis predicts that wing shape should also follow an elevational gradient because air density and oxygen supply decline with altitude, altering the aerodynamics of flight, and driving the evolution of more efficient wings in high-elevation species to compensate for reduced lift. However, previous analyses have found only mixed support for the 'thin-air' hypothesis, and we currently lack a global synthesis of elevational gradients in wing design for any taxonomic group. In this study, we use phylogenetic comparative models to explore elevational effects on wing morphology in 9986 bird species, while accounting for multiple climatic and ecological attributes, including latitude, temperature seasonality, body mass, aerial lifestyle and migration. We found that relative wing elongation (hand-wing index) and wing area increase with elevation, particularly in the upper montane zone (>4 km above sea level). These results confirm a pervasive elevational gradient in avian wing morphology, highlighting the role of aerodynamic constraints as key mechanisms shaping global patterns of trait evolution in flying animals.    

    

* Bioenergetic stress potentiates antimicrobial resistance and persistence  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400625331
:TOPICS: Global Challenge of Antibiotic Resistance in Bacteria, Evolutionary Dynamics of Genetic Adaptation and Mutation, Clustered Regularly Interspaced Short Palindromic Repeats and CRISPR-associated proteins
:PUBLICATION_DATE: 2024-07-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2024.07.12.603336")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400625331"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400625331"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400625331"))][Get cited by]]

OpenAlex: https://openalex.org/W4400625331 (Open access: False)
    
[[https://openalex.org/A5075049099][B.-H. Li]], [[https://openalex.org/A5104518756][Shivani Srivastava]], [[https://openalex.org/A5000695648][Majid B. Shaikh]], [[https://openalex.org/A5104488363][Gautam Mereddy]], [[https://openalex.org/A5104541460][Madison R Garcia]], [[https://openalex.org/A5087398570][Aditi Shah]], [[https://openalex.org/A5104504105][Nana Ofori-Anyinam]], [[https://openalex.org/A5052769779][Timothy Shun Man Chu]], [[https://openalex.org/A5104518757][Nicole Cheney]], [[https://openalex.org/A5076398738][Jason H. Yang]], bioRxiv (Cold Spring Harbor Laboratory). None(None)] 2024. https://doi.org/10.1101/2024.07.12.603336 
     
Antimicrobial resistance (AMR) is a global health crisis and there is an urgent need to better understand AMR mechanisms. Antibiotic treatment alters several aspects of bacterial physiology, including increased ATP utilization, carbon metabolism, and reactive oxygen species (ROS) formation. However, how the "bioenergetic stress" induced by increased ATP utilization affects treatment outcomes is unknown. Here we utilized a synthetic biology approach to study the direct effects of bioenergetic stress on antibiotic efficacy. We engineered a genetic system that constitutively hydrolyzes ATP or NADH in Escherichia coli. We found that bioenergetic stress potentiates AMR evolution via enhanced ROS production, mutagenic break repair, and transcription-coupled repair. We also find that bioenergetic stress potentiates antimicrobial persistence via potentiated stringent response activation. We propose a unifying model that antibiotic-induced antimicrobial resistance and persistence is caused by antibiotic-induced. This has important implications for preventing or curbing the spread of AMR infections.    

    

* Interfacial Engineering of Fluorescent Carbon Dots with Metal Oxides for Real‐Time Visualization of Oxygen Vacancy Dynamics  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400735836
:TOPICS: Synthesis and Applications of Carbon Quantum Dots, Catalytic Nanomaterials, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202402827")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400735836"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400735836"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400735836"))][Get cited by]]

OpenAlex: https://openalex.org/W4400735836 (Open access: False)
    
[[https://openalex.org/A5089379689][Lei Jiang]], [[https://openalex.org/A5043751076][Wanlu Cao]], [[https://openalex.org/A5100406494][Zijian Li]], [[https://openalex.org/A5009701916][Chunchang Wang]], [[https://openalex.org/A5072112023][Hong Bi]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202402827 
     
Oxygen vacancy (Vo), as one of the most common surface defects, significantly influence the physiochemical properties of metal oxides. However, it remains a challenge for existing techniques to visualize the evolution of Vo during redox process due to its heterogeneous distribution, small size, and dynamic nature. Herein, the real-time monitoring of such microscopic interfacial events is reported by advantage of the high-contrast fluorescence response of carbon dots (H-CDs) to Vo. The green emissive H-CDs possess a unique disc-shaped structure and exceptional hydrophilicity, allowing their tight adhesion to the surfaces of Vo-rich MgO by simple mixing. Subsequently, a water involved interfacial reaction occurred between H-CDs and Vo, resulting in gradual quenching of the original green emission and simultaneously emergence of bright red fluorescence. Moreover, the spatiotemporal diffusion dynamics and reaction kinetics are investigated by confocal laser scanning microscopy, revealing the time-dependent reorganization and structural heterogeneity at the interface. The finding provides a new toolbox for in situ imaging of Vo-triggered phenomena at a microscopic level, which will be helpful in promoting the rational design of oxide materials.    

    

* New information about the cyclable capacity fading process of a pouch cell with Li-rich layered oxide cathodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400740121
:TOPICS: Lithium-ion Battery Management in Electric Vehicles, Lithium-ion Battery Technology, Power Electronics and Conversion Systems
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02472a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400740121"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400740121"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400740121"))][Get cited by]]

OpenAlex: https://openalex.org/W4400740121 (Open access: True)
    
[[https://openalex.org/A5104241432][Jinhong Luo]], [[https://openalex.org/A5044018192][Jinghao Liu]], [[https://openalex.org/A5041722579][Zilong Su]], [[https://openalex.org/A5011637223][Hongxing Dong]], [[https://openalex.org/A5100867573][Zhimin Ren]], [[https://openalex.org/A5100670229][Guohua Li]], [[https://openalex.org/A5052278320][Xiaopeng Qi]], [[https://openalex.org/A5104245927][Bo Hu]], [[https://openalex.org/A5100525341][Wei Quan]], [[https://openalex.org/A5100632945][Jiantao Wang]], RSC advances. 14(31)] 2024. https://doi.org/10.1039/d4ra02472a 
     
Most studies investigate the cyclable capacity fading mechanism of Li-rich layered oxides (LLOs) from the microscopic structure level, lacking discussions about how the structure degradation influences the performance of the pouch cell precisely and quantitatively. Based on the analysis of the evolution of key parameters during the whole cycling period, a new transition-type fading mechanism is proposed. From the early-to-middle stage of the cycling period, polarization increases, most of which is interface-related, causing about 67% of the whole capacity loss. From the middle-to-late stage of the cycling period, active material losses turn out to be the dominating factor, inducing about 61% of the total capacity loss. Diffusion-related polarization, replacing the interface type, is responsible for most of the increased overpotential. Relative analysis confirms that during the early stage, the increase of the charge transfer resistance, induced by CEI (cathode electrolyte interface) growth and initial surface layered-structure degradation, is the main source of interface polarization. As the cycling evolves to the late stage, severe bulky structure degradation, including lattice-oxygen release, Li/Ni mixture and generation of a new spinel phase, turns out to be the major factor, causing further capacity fading.    

    

* Oxidative stress-mediated epigenetic remodeling, metastatic progression and cell signaling in cancer  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400666417
:TOPICS: Role of Histone Deacetylases in Cellular Regulation, Epigenetic Modifications and Their Functional Implications, Role of Nrf2 Signaling in Oxidative Stress Response
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1515/oncologie-2024-0157")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400666417"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400666417"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400666417"))][Get cited by]]

OpenAlex: https://openalex.org/W4400666417 (Open access: False)
    
[[https://openalex.org/A5048512259][Abdul Rehman Phull]], [[https://openalex.org/A5001504266][Sadia Qamar Arain]], [[https://openalex.org/A5102013928][Abdul Majid]], [[https://openalex.org/A5009718163][Humaira Fatima]], [[https://openalex.org/A5101813695][Madiha Ahmed]], [[https://openalex.org/A5043860930][Song Ja Kim]], Oncologie. 0(0)] 2024. https://doi.org/10.1515/oncologie-2024-0157 
     
Abstract Cancer is a serious public health issue and cases are rising at a high rate around the world. Altered production of reactive oxygen species (ROS) causes oxidative stress (OS) which plays a vital role in cancer development by disrupting signaling pathways and genomic integrity in the cellular microenvironment. In this study, we reviewed the regulation of noncoding RNAs, histone modifications, and DNA methylation which OS is involved in. These mechanisms promote cancer growth, metastasis, and resistance to chemotherapeutic agents. There is significant potential to improve patient outcomes through the development of customized medications and interventions that precisely address the role of OS in the onset and progression of cancer. Redox-modulating drugs, antioxidant-based therapies, and measures to restore regular cellular activity and OS-modulated signaling pathways are some examples of these strategies. One other hypothesis rationalizes the cancer-suppressing effect of OS, which acts as a two-edged condition that warns against the use of antioxidants for cancer treatment and management. The present study was executed to review the impact of OS on epigenetic machinery, the evolution of metastatic cancer, and how OS mediates cellular signaling. Along with, insights into the potential of targeting OS-mediated mechanisms for cancer therapy.    

    

* Early combination of sotrovimab with nirmatrelvir/ritonavir or remdesivir is associated with low rate of persisting SARS CoV-2 infection in immunocompromised outpatients with mild-to-moderate COVID-19: a prospective single center study.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400701323
:TOPICS: Coronavirus Disease 2019, Coronavirus Disease 2019 Research, Heparin-Induced Thrombocytopenia and Thrombosis
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2024.07.15.24310384")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400701323"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400701323"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400701323"))][Get cited by]]

OpenAlex: https://openalex.org/W4400701323 (Open access: False)
    
[[https://openalex.org/A5085119093][Ivan Gentile]], [[https://openalex.org/A5020002623][Giulio Viceconte]], [[https://openalex.org/A5033782844][F. M. Cuccurullo]], [[https://openalex.org/A5099044934][Daria Pietroluongo]], [[https://openalex.org/A5008674329][Alessia D’Agostino]], [[https://openalex.org/A5092839599][Maria Silvitelli]], [[https://openalex.org/A5076584393][Simona Mercinelli]], [[https://openalex.org/A5066109758][Riccardo Scotto]], [[https://openalex.org/A5006522103][Francesco Grimaldi]], [[https://openalex.org/A5060752899][Salvatore Palmieri]], [[https://openalex.org/A5033579313][Angela Gravetti]], [[https://openalex.org/A5023269204][Fabio Trastulli]], [[https://openalex.org/A5087987306][Marcello Moccia]], [[https://openalex.org/A5031247439][Antonio Riccardo Buonomo]], No host. None(None)] 2024. https://doi.org/10.1101/2024.07.15.24310384 
     
Background Immunocompromised patients are at high risk of developing persisting/prolonged COVID-19. Data concerning early combined use of antivirals and monoclonal antibodies in this population are scarce. Research design and methods We performed an observational, prospective study, enrolling immunocompromised outpatient adults with mild-to-moderate COVID-19 treated with a combination of sotrovimab plus one antiviral (remdesivir or nirmatrelvir/ritonavir) within 7 days from symptoms onset. Results We enrolled 52 patients. No patient was hospitalized within 30 days from the disease onset, needed oxygen administration or died within 60 days, or experienced a reinfection or a clinical relapse within 90 days. Clearance rates were 67% and 97% at 14th day after the end of therapy and at the end of follow-up, respectively. Factors associated with longer infection were initiation of therapy after 3 days from symptoms onset, and enrollment more than 180 days from the beginning of the study. However, only the latter factor was independently associated with longer SARS-CoV-2 infection, suggesting a loss of efficacy of this strategy with the evolution of SARS-CoV-2 variants Conclusions Early administration of combination therapy with a direct antiviral and sotrovimab seems to be effective in preventing hospitalization, progression to severe COVID-19 and the development of prolonged/persisting SARS-CoV-2 infection in immunocompromised patients.    

    

* Mobile forensics tools and techniques for digital crime investigation: a comprehensive review  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400665585
:TOPICS: Digital Forensics Research and Challenges, Characterization and Detection of Android Malware, Digital Image Forgery Detection and Identification
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.11591/ijict.v13i2.pp321-332")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400665585"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400665585"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400665585"))][Get cited by]]

OpenAlex: https://openalex.org/W4400665585 (Open access: False)
    
[[https://openalex.org/A5059360335][Tole Sutikno]], International Journal of Informatics and Communication Technology/International Journal of Informatics and Communication Technology (IJ-ICT). 13(2)] 2024. https://doi.org/10.11591/ijict.v13i2.pp321-332 
     
<p>Extracting and analyzing data from smartphones, IoT devices, and drones is crucial for conducting digital crime investigations. Effective cyberattack mitigation necessitates the use of advanced Android mobile forensics techniques. The investigation necessitates proficiency in manual, logical, hex dump, chip-off, and microread methodologies. This paper provides a comprehensive overview of Android mobile forensics tools and techniques for digital crime investigation, as well as their use in gathering and analyzing evidence. Forensic software tools like Cellebrite UFED, Oxygen Forensic Detective, XRY by MSAB, Magnet AXIOM, SPF Pro by SalvationDATA, MOBILedit Forensic Express, and EnCase Forensic employ both physical and logical techniques to retrieve data from mobile devices. These advanced tools offer a structured approach to tackling digital crimes effectively. We compare dependability, speed, compatibility, data recovery accuracy, and reporting. Mobile-network forensics ensures data acquisition, decryption, and analysis success. Conclusions show that Android mobile forensics tools for digital crime investigations are diverse and have different capabilities. Mobile forensics software offers complete solutions, but new data storage and encryption methods require constant development. The continuous evolution of forensic software tools and a comprehensive tool classification system could further enhance digital crime investigation capabilities.</p>    

    

* Exploring Heterointerface Characteristics and Charge-Storage Dynamics in ALD-Developed Ultra-Thin TiO2-In2O3/Au Heterojunctions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400640339
:TOPICS: Memristive Devices for Neuromorphic Computing, Advanced Materials for Smart Windows, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-07-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/coatings14070880")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400640339"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400640339"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400640339"))][Get cited by]]

OpenAlex: https://openalex.org/W4400640339 (Open access: True)
    
[[https://openalex.org/A5055810944][Mohammad Karbalaei Akbari]], [[https://openalex.org/A5080151322][Nasrin Siraj Lopa]], [[https://openalex.org/A5084838483][Serge Zhuiykov]], Coatings. 14(7)] 2024. https://doi.org/10.3390/coatings14070880 
     
Directional ionic migration in ultra-thin metal-oxide semiconductors under applied electric fields is a key mechanism for developing various electronic nanodevices. However, understanding charge transfer dynamics is challenging due to rapid ionic migration and uncontrolled charge transfer, which can reduce the functionality of microelectronic devices. This research investigates the supercapacitive-coupled memristive characteristics of ultra-thin heterostructured metal-oxide semiconductor films at TiO2-In2O3/Au Schottky junctions. Using atomic layer deposition (ALD), we nano-engineered In2O3/Au-based metal/semiconductor heterointerfaces. TEM studies followed by XPS elemental analysis revealed the chemical and structural characteristics of the heterointerfaces. Subsequent AFM studies of the hybrid heterointerfaces demonstrated supercapacitor-like behavior in nanometer-thick TiO2-In2O3/Au junctions, resembling ultra-thin supercapacitors, pseudocapacitors, and nanobatteries. The highest specific capacitance of 2.6 × 104 F.g−1 was measured in the TiO2-In2O3/Au junctions with an amorphous In2O3 electron gate. Additionally, we examined the impact of crystallization, finding that thermal annealing led to the formation of crystalline In2O3 films with higher oxygen vacancy content at TiO2-In2O3 heterointerfaces. This crystallization process resulted in the evolution of non-zero I-V hysteresis loops into zero I-V hysteresis loops with supercapacitive-coupled memristive characteristics. This research provides a platform for understanding and designing adjustable ultra-thin Schottky junctions with versatile electronic properties.    

    

* A record of magmatic differentiation in plutonic xenoliths from Santorini (Greece)  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400701470
:TOPICS: Tectonic and Geochronological Evolution of Orogens, Radiocarbon Dating and Agricultural Origins, Seismicity and Tectonic Plate Interactions
:PUBLICATION_DATE: 2024-07-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.30909/vol.07.02.421446")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400701470"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400701470"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400701470"))][Get cited by]]

OpenAlex: https://openalex.org/W4400701470 (Open access: True)
    
[[https://openalex.org/A5016875765][Sean Whitley]], [[https://openalex.org/A5022407292][Ralf Halama]], [[https://openalex.org/A5001098294][Ralf Gertisser]], [[https://openalex.org/A5051390784][Thor H. Hansteen]], [[https://openalex.org/A5043716768][Matthias Frische]], [[https://openalex.org/A5013438964][Torsten Vennemann]], Volcanica. 7(2)] 2024. https://doi.org/10.30909/vol.07.02.421446 
     
Plutonic xenoliths from volcanic arcs provide unique insights into transcrustal magmatic systems in subduction zone settings. At Santorini volcano in the Central Aegean Volcanic Arc (Greece), plutonic xenoliths occur throughout a sequence of lavas and pyroclastic rocks erupted within the last ~360 ka. They are mineralogically variable, ranging from troctolites to olivine gabbros, gabbros, gabbronorites, and diorites. Thermobarometric calculations based on mineral and melt inclusion compositions indicate equilibration over a range of temperatures (1100 to 750 °C) at shallow to mid-crustal depths (P <400 MPa), but there is no evidence for crystallisation at lower crustal depths. Oxygen isotope data of mineral separates and calculated δ18O melt values are in line with extensive closed-system fractional crystallisation at magmatic temperatures, without a requirement for extensive assimilation of the subvolcanic continental basement. The xenolith minerals compositionally overlap with phenocrysts from the volcanic rocks, but they also contain evidence for the presence of highly evolved melt compositions in the form of melt inclusions with extremely silica-rich compositions (up to 82 wt.% SiO2) and high enrichments of incompatible trace elements coupled with increasing negative Eu anomalies in clinopyroxenes. Since these characteristics correlate systematically with differentiation indices and rock type, they are interpreted to reflect melt evolution via fractional crystallisation as the dominant differentiation process with no significant role of reactive porous flow. These observations highlight that trapped melt fractions can influence mineral compositional variations in the plutonic xenoliths, and in turn the mineral compositions demonstrate a melt compositional variability not preserved in the volcanic rock record.    

    

* The NIRVANDELS Survey: The stellar and gas-phase mass-metallicity relations of star-forming galaxies at z = 3.5  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400639883
:TOPICS: Stellar Astrophysics and Exoplanet Studies, Star Formation in Molecular Clouds and Protoplanetary Disks, Supercritical Fluid Extraction and Processing
:PUBLICATION_DATE: 2024-07-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/mnras/stae1705")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400639883"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400639883"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400639883"))][Get cited by]]

OpenAlex: https://openalex.org/W4400639883 (Open access: True)
    
[[https://openalex.org/A5023371135][T M Stanton]], [[https://openalex.org/A5065251185][F. Cullen]], [[https://openalex.org/A5057206732][R. J. McLure]], [[https://openalex.org/A5075633773][Alice E. Shapley]], [[https://openalex.org/A5022983189][K. Z. Arellano-Córdova]], [[https://openalex.org/A5013399952][R Begley]], [[https://openalex.org/A5075217338][R. Amorín]], [[https://openalex.org/A5017175706][L. Barrufet]], [[https://openalex.org/A5024204484][Antonio Calabrò]], [[https://openalex.org/A5005550724][A. C. Carnall]], [[https://openalex.org/A5104581094][Michele Cirasuolo]], [[https://openalex.org/A5039140400][J. S. Dunlop]], [[https://openalex.org/A5039748526][C T Donnan]], [[https://openalex.org/A5006363864][M. L. Hamadouche]], [[https://openalex.org/A5080975631][Feng-Yuan Liu]], [[https://openalex.org/A5057206732][R. J. McLure]], [[https://openalex.org/A5012650176][L Pentericci]], [[https://openalex.org/A5090420192][L. Pozzetti]], [[https://openalex.org/A5090712914][Ryan L. Sanders]], [[https://openalex.org/A5028060062][Dirk Scholte]], [[https://openalex.org/A5023923034][Michael W. Topping]], Monthly Notices of the Royal Astronomical Society. None(None)] 2024. https://doi.org/10.1093/mnras/stae1705 
     
Abstract We present determinations of the gas-phase and stellar metallicities of a sample of 65 star-forming galaxies at z ≃ 3.5 using rest-frame far-ultraviolet (FUV) spectroscopy from the VANDELS survey in combination with follow-up rest-frame optical spectroscopy from VLT/KMOS and Keck/MOSFIRE. We infer gas-phase oxygen abundances (Zg; tracing O/H) via strong optical nebular lines and stellar iron abundances (Z⋆; tracing Fe/H) from full spectral fitting to the FUV continuum. Our sample spans the stellar mass range 8.5 &lt; log(M⋆/M⊙) &lt; 10.5 and shows clear evidence for both a stellar and gas-phase mass-metallicity relation (MZR). We find that our O and Fe abundance estimates both exhibit a similar mass-dependence, such that $\mathrm{Fe/H}\propto M_{\star }^{0.30\pm 0.11}$ and $\mathrm{O/H}\propto M_{\star }^{0.32\pm 0.09}$. At fixed M⋆ we find that, relative to their solar values, O abundances are systematically larger than Fe abundances (i.e. α-enhancement). We estimate an average enhancement of (O/Fe) = 2.65 ± 0.16 × (O/Fe)⊙ which appears to be independent of M⋆. We employ analytic chemical evolution models to place a constraint on the strength of galactic-level outflows via the mass-outflow factor (η). We show that outflow efficiencies that scale as $\eta \propto M_{\star }^{-0.32}$ can simultaneously explain the functional form of of the stellar and gas-phase MZR, as well as the degree of α-enhancement at fixed Fe/H. Our results add further evidence to support a picture in which α-enhanced abundance ratios are ubiquitous in high-redshift star-forming galaxies, as expected for young systems whose interstellar medium is primarily enriched by core-collapse supernovae.    

    

* Quantitative 3D electron microscopy characterization of mitochondrial structure, mitophagy, and organelle interactions in murine atrial fibrillation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400616816
:TOPICS: Mitochondrial Dynamics and Reactive Oxygen Species Regulation, Functions and Regulation of RNA Editing by ADARs, Molecular Mechanisms of Neurodegenerative Diseases
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jsb.2024.108110")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400616816"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400616816"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400616816"))][Get cited by]]

OpenAlex: https://openalex.org/W4400616816 (Open access: False)
    
[[https://openalex.org/A5060777533][Pavithran Guttipatti]], [[https://openalex.org/A5078428969][Najla Saadallah]], [[https://openalex.org/A5011475864][Ruiping Ji]], [[https://openalex.org/A5079725786][Uma Mahesh R. Avula]], [[https://openalex.org/A5040915172][Chris N. Goulbourne]], [[https://openalex.org/A5015846564][Elaine Y. Wan]], Journal of structural biology. None(None)] 2024. https://doi.org/10.1016/j.jsb.2024.108110 
     
Atrial fibrillation (AF) is the most common clinical arrhythmia, however there is limited understanding of its pathophysiology including the cellular and ultrastructural changes rendered by the irregular rhythm, which limits pharmacological therapy development. Prior work has demonstrated the importance of reactive oxygen species (ROS) and mitochondrial dysfunction in the development of AF. Mitochondrial structure, interactions with other organelles such as sarcoplasmic reticulum (SR) and T-tubules (TT), and degradation of dysfunctional mitochondria via mitophagy are important processes to understand ultrastructural changes due to AF. However, most analysis of mitochondrial structure and interactome in AF has been limited to two-dimensional (2D) modalities such as transmission electron microscopy (EM), which does not fully visualize the morphological evolution of the mitochondria during mitophagy. Herein, we utilize focused ion beam-scanning electron microscopy (FIB-SEM) and perform reconstruction of three-dimensional (3D) EM from murine left atrial samples and measure the interactions of mitochondria with SR and TT. We developed a novel 3D quantitative analysis of FIB-SEM in a murine model of AF to quantify mitophagy stage, mitophagosome size in cardiomyocytes, and mitochondrial structural remodeling when compared with control mice. We show that in our murine model of spontaneous and continuous AF due to persistent late sodium current, left atrial cardiomyocytes have heterogenous mitochondria, with a significant number which are enlarged with increased elongation and structural complexity. Mitophagosomes in AF cardiomyocytes are located at Z-lines where they neighbor large, elongated mitochondria. Mitochondria in AF cardiomyocytes show increased organelle interaction, with 5X greater contact area with SR and are 4X as likely to interact with TT when compared to control. We show that mitophagy in AF cardiomyocytes involves 2.5X larger mitophagosomes that carry increased organelle contents. In conclusion, when oxidative stress overcomes compensatory mechanisms, mitophagy in AF faces a challenge of degrading bulky complex mitochondria, which may result in increased SR and TT contacts, perhaps allowing for mitochondrial Ca    

    

* An oxidation flow reactor for simulating and accelerating secondary aerosol formation in aerosol liquid water and cloud droplets  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400743280
:TOPICS: Atmospheric Aerosols and their Impacts, Aerosols' Impact on Climate and Hydrological Cycle, Stratospheric Chemistry and Climate Change Impacts
:PUBLICATION_DATE: 2024-07-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/amt-17-4227-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400743280"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400743280"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400743280"))][Get cited by]]

OpenAlex: https://openalex.org/W4400743280 (Open access: True)
    
[[https://openalex.org/A5089058454][Ningjin Xu]], [[https://openalex.org/A5101891053][Le Chen]], [[https://openalex.org/A5010774871][David R. Cocker]], [[https://openalex.org/A5087707527][Kunpeng Chen]], [[https://openalex.org/A5031313025][Ying‐Hsuan Lin]], [[https://openalex.org/A5012564009][Don Collins]], Atmospheric measurement techniques. 17(14)] 2024. https://doi.org/10.5194/amt-17-4227-2024 
     
Abstract. Liquid water in cloud droplets and aqueous aerosols serves as an important reaction medium for the formation of secondary aerosol through aqueous-phase reactions (aqSA). Large uncertainties remain in estimates of the production and chemical evolution of aqSA in the dilute solutions found in cloud droplets and the concentrated solutions found in aerosol liquid water, which is partly due to the lack of available measurement tools and techniques. A new oxidation flow reactor (OFR), the Accelerated Production and Processing of Aerosols (APPA) reactor, was developed to measure secondary aerosol formed through gas- and aqueous-phase reactions, both for laboratory gas mixtures containing one or more precursors and for ambient air. For simulating in-cloud processes, ∼ 3.3 µm diameter droplets formed on monodisperse seed particles are introduced into the top of the reactor, and the relative humidity (RH) inside it is controlled to 100 %. Similar measurements made with the RH in the reactor < 100 % provide contrasts for aerosol formation with no liquid water and with varying amounts of aerosol liquid water. The reactor was characterized through a series of experiments and used to form secondary aerosol from known concentrations of an organic precursor and from ambient air. The residence time distributions of both gases and particles are narrow relative to other OFRs and lack the tails at long residence time expected with laminar flow. Initial cloud processing experiments focused on the well-studied oxidation of dissolved SO2 by O3, with the observed growth of seed particles resulting from the added sulfuric acid agreeing well with estimates based on the relevant set of aqueous-phase reactions. The OH exposure (OHexp) for low RH, high RH, and in-cloud conditions was determined experimentally from the loss of SO2 and benzene and simulated from the KinSim chemical kinetics solver with inputs of the measured 254 nm UV intensity profile through the reactor and loss of O3 due to photolysis. The aerosol yield for toluene at high OHexp ranged from 21.4 % at low RH with dry seed particles present in the reactor to 78.1 % with cloud droplets present. Measurement of the composition of the secondary aerosol formed from ambient air using an aerosol mass spectrometer showed that the oxygen-to-carbon ratio (O : C) of the organic component increased with increasing RH (and liquid water content).    

    

* Does water transparency control the banding in shallow water iron formations?  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400747134
:TOPICS: Paleoredox and Paleoproductivity Proxies, Geochemistry of Manganese Oxides in Sedimentary Environments, Climate Change and Paleoclimatology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.25131/sajg.127.0014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400747134"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400747134"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400747134"))][Get cited by]]

OpenAlex: https://openalex.org/W4400747134 (Open access: True)
    
[[https://openalex.org/A5079423760][Daniel Herwartz]], [[https://openalex.org/A5027533484][Sebastian Viehmann]], South African journal of geology. 127(2)] 2024. https://doi.org/10.25131/sajg.127.0014 
     
Abstract Iron formations (IFs) are marine chemical sediments that are conined to the Precambrian rock record and provide unique insights into the co-evolution of the atmosphere-hydrosphere and biosphere through almost three billion years of Earth’s history. IFs commonly appear throughout the Archaean until the Palaeoproterozoic ca. 1.8 billion years ago and re-appear during the “Snowball Earth” epoch in the Neoproterozoic. The formation and deposition mechanism(s) of IFs are, however, still incompletely understood, hindering unique interpretations of palaeoenvironments. Many IFs are banded iron formations (BIFs) with layer thickness of alternating Fe- and Si-rich layers ranging over several orders of magnitude from the nanometre to the metre scale. A second textural type, so called granular iron formations (GIFs) that form above storm wave base become widespread in the Palaeoproterozoic. Understanding the fundamental mechanisms that are responsible for the textural types and the periodicity of banding in BIFs is crucial to link these features to the environmental and geochemical evolution of the Earth. We here provide a conceptual model that highlights the role of changing light conditions and water transparency for Iron Formation (IF) precipitation. We show that the model is particularly feasible for IFs deposited in shallow waters but may also be applicable for some IFs deposited in deeper water settings. The model builds on other primary Banded Iron Formation (BIF) precipitation models postulating that Fe(III)-(oxyhydr)oxide production can be dominated by anoxygenic photoautotrophic Fe2+-oxidising bacteria. These so called photoferrotrophs are adapted to very low light levels corresponding to about 1% of the light level required by oxygen-producing phototrophs allowing them to thrive deep down in the water column. The depth of Fe(III)-(oxyhydr)oxide production is mainly controlled by water turbidity which controls how deep photosynthetically available radiation (PAR) penetrates the water column. Eutrophic conditions result in relatively shallow Fe(III)-(oxyhydr)oxide production depth due to turbidity either induced by the biomass itself and/or by particles that are actively or passively produced by microorganisms (e.g., Fe(III) and Mn(IV)-(oxyhydr)oxides, sulphides), triggering the formation of Fe-rich bands. During oligotrophic stages, Fe(III)-(oxyhydr)oxides are only produced relatively deep down in the water column, so that only silica-rich bands form in the Fe(III)-(oxyhydr)oxide free upper water column. Reactive transport modelling adopted from Ozaki et al., (2019) shows that besides upwelling and nutrient supply, alternating Fe(III) production depth is mainly associated with changing light conditions as a result of water transparency. Periodicities reflected by alternating Fe- and Si-rich bands in IFs in our model can thus be associated with: (1) nutrient supply patterns; (2) additional sources of turbidity in the water column such as Fe(III) and Mn(IV) oxide particles, sulphides, and wind-blown silicate particles; or (3) formation and clearing of organic haze in the atmosphere. One or all of these reasons for low light conditions seem to become more important in the Palaeoproterozoic (&lt;2.4 Ga) and could be partly responsible for the more widespread occurrences of shallow marine granular IFs relative to former epochs, which is often assigned to the gradual oxidation of the ocean. Our model shows that variable water transparency should be considered as additional factor for IF deposition especially for shallow marine settings. This model also reasonably explains the prominent layering in BIFs as syn-depositional feature.    

    

* The Geology, Fluid Inclusions, and O‐S Isotopes of the Mibei Gold Deposit, Hunan Province, Southern China  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400697833
:TOPICS: Tectonic and Geochronological Evolution of Orogens, Machine Learning for Mineral Prospectivity Mapping, Seismicity and Tectonic Plate Interactions
:PUBLICATION_DATE: 2024-07-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/1755-6724.15184")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400697833"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400697833"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400697833"))][Get cited by]]

OpenAlex: https://openalex.org/W4400697833 (Open access: False)
    
[[https://openalex.org/A5074320223][Wenhao Xue]], [[https://openalex.org/A5058473034][Yayun Liang]], [[https://openalex.org/A5100347685][Xiaofeng Li]], [[https://openalex.org/A5032790556][Minyong Li]], [[https://openalex.org/A5100617974][Wei Xie]], [[https://openalex.org/A5070138464][Xue Peng]], [[https://openalex.org/A5022494657][Rui Xia]], [[https://openalex.org/A5100612268][Honglin He]], [[https://openalex.org/A5021277283][Jinzhi Xiao]], Acta geologica Sinica/Acta geologica sinica. None(None)] 2024. https://doi.org/10.1111/1755-6724.15184 
     
Abstract The Mibei gold deposit, located in the southwestern part of the Xuefengshan uplift zone, the middle section of the Jiangnan orogenic belt in southern China, has estimated gold resources of approximately seven tons. This deposit is primarily a quartz vein‐type gold deposit, with ore bodies occurring mainly within Neoproterozoic metasediments. The main metallic minerals in the ore are pyrite, chalcopyrite, and arsenopyrite. In this study, the petrography and microthermometry of ore‐forming fluid inclusions, oxygen isotopes of gold‐bearing quartz, and sulfur isotopes of gold‐bearing sulfides and arsenopyrite were analyzed. Three types of fluid inclusions were identified: type Ia three‐phase inclusions comprising vapor and two phases of liquids (V CO2 + L CO2 + L H2O ), type Ib two‐phase liquids (L CO2 + L H2O ), type II two‐phase vapor‐rich inclusions (V/V + L > 50%), and type III pure liquid inclusions. Type I inclusions were heated uniformly to the liquid phase, type II inclusions were heated uniformly to the gas phase, and type III inclusions were heated without change. In general, the temperature range of homogenization to liquid phase of fluid inclusions in the Mibei gold deposit is 204–227°C. The salinity of the inclusion ranges from 4.6 to 12.2 wt% NaCl equiv. The δ 18 O SMOW of gold‐bearing quartz varies from 16.9‰ to 17.5‰. The δ 18 O H2O of gold‐bearing quartz are varied from 6.5‰ to 7.5‰. The δ 34 S values of gold‐bearing pyrite range from 1.7‰ to 6.8‰. The δ 34 S values of gold‐bearing arsenopyrite range from 5.6‰ to 5.9‰. The δ 34 S values of pyrite from wall rocks slate range from 6.4‰ to 11.6‰. This evidence implies that the ore‐forming fluids of the Mibei gold deposit originated from magmatic‐hydrothermal processes, mixing with minor S from the surrounding metasediments. Combined with the evolution of the Jiangnan orogenic belt, due to the magmatic and tectonic activities of the Xuefengshan uplift during the Caledonian period, the fault seal mechanism controlled the ore‐forming process. Overall, the Mibei gold deposit is more akin to a magmatic‐hydrothermal gold deposit.    

    
