#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Sun Feb  4 14:23:14 2024

Found 49 results from 2024-01-21 to 2024-02-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Nitrogen and Sulfur Co‐Doped Carbon‐Coated Ni3S2/MoO2 Nanowires as Bifunctional Catalysts for Alkaline Seawater Electrolysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391050864
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202309655")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391050864"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391050864"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391050864"))][Get cited by]]

OpenAlex: https://openalex.org/W4391050864 (Open access: False)
    
[[https://openalex.org/A5045874509][Xiaocheng Fan]], [[https://openalex.org/A5023494462][Bei Li]], [[https://openalex.org/A5084212238][Chunling Zhu]], [[https://openalex.org/A5063257047][Feng Yan]], [[https://openalex.org/A5005742457][Xitian Zhang]], [[https://openalex.org/A5049399769][Yujin Chen]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202309655 
     
Abstract Bifunctional catalysts have inherent advantages in simplifying electrolysis devices and reducing electrolysis costs. Developing efficient and stable bifunctional catalysts is of great significance for industrial hydrogen production. Herein, a bifunctional catalyst, composed of nitrogen and sulfur co‐doped carbon‐coated trinickel disulfide (Ni 3 S 2 )/molybdenum dioxide (MoO 2 ) nanowires (NiMoS@NSC NWs), is developed for seawater electrolysis. The designed NiMoS@NSC exhibited high activity in alkaline electrolyte with only 52 and 191 mV overpotential to attain 10 mA cm −2 for hydrogen evolution reaction (HER) and oxygen evolution reaction (OER), respectively. Significantly, the electrolyzer (NiMoS@NSC||NiMoS@NSC) based on this bifunctional catalyst drove 100 mA cm −2 at only 1.71 V along with a robust stability over 100 h in alkaline seawater, which is superior to a platinum/nickel‐iron layered double hydroxide couple (Pt||NiFe LDH). Theoretical calculations indicated that interfacial interactions between Ni 3 S 2 and MoO 2 rearranged the charge at interfaces and endowed Mo sites at the interfaces with Pt‐like HER activity, while Ni sites on Ni 3 S 2 surfaces at non‐interfaces are the active centers for OER. Meanwhile, theoretical calculations and experimental results also demonstrated that interfacial interactions improved the electrical conductivity, boosting reaction kinetics for both HER and OER. This study presented a novel insight into the design of high‐performance bifunctional electrocatalysts for seawater splitting.    

    

* Optimization of Interfacial OH− Accessibility by Constructing a Delayed–Release Membrane Electrode for Ampere–Level Hydrogen Production  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391052873
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202313233")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391052873"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391052873"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391052873"))][Get cited by]]

OpenAlex: https://openalex.org/W4391052873 (Open access: False)
    
[[https://openalex.org/A5063705533][Yu Cheng]], [[https://openalex.org/A5025015767][Huanyu Chen]], [[https://openalex.org/A5011837783][Xinnan Xu]], [[https://openalex.org/A5024499169][Junjie Dong]], [[https://openalex.org/A5013850346][Mengfan Wang]], [[https://openalex.org/A5056439522][Chenglin Yan]], [[https://openalex.org/A5009208811][Tao Qian]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202313233 
     
Abstract Achieving a high current density during electrochemical overall water splitting is a promising strategy for industrial energy conversion. The mass diffusion rate of OH − ions from the electrolyte to the interfacial active sites strongly influences the hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) . Herein, the delayed‐release of OH − ions modulated by a proper organic polymer membrane on the electrode surface can optimize the OH − accessibility to the active sites (as indicated by the molecular dynamics simulations) is demonstrated and that van der Waals interaction force modulates the OH − residence time in the reaction system. The remarkable performance of the membrane‐modified electrode is achieved at ultra‐high current densities of 1.9 A cm −2 (with an HER overpotential of 602 mV) and 2 A cm −2 (with an OER overpotential of 459 mV) in 1 M KOH solution. Consequently, a super‐high current density of 1.3 A cm −2 is obtained for overall water splitting (at a voltage of only 2.2 V), which is 1.9‐fold higher than that of a benchmarked Pt/C‐IrO 2 (684 mA cm −2 ). Therefore, the delayed‐release of OH − has optimized the mass conversion efficiency of the active sites, thus improving the electrochemical performance of overall water splitting.    

    

* Reinforcing oxygen electrocatalytic activity via selective dual-phase heterointerface engineering for rechargeable Zn–air batteries  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391053486
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12598-023-02531-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391053486"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391053486"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391053486"))][Get cited by]]

OpenAlex: https://openalex.org/W4391053486 (Open access: False)
    
[[https://openalex.org/A5033511090][Chao Cheng]], [[https://openalex.org/A5037609171][Chunyi Zhi]], [[https://openalex.org/A5049586106][Zhongti Sun]], [[https://openalex.org/A5053798363][Yongqiang Ming]], [[https://openalex.org/A5000096613][T. Xiang]], [[https://openalex.org/A5024436776][Qian Zhu]], [[https://openalex.org/A5076564883][Zirui Wu]], [[https://openalex.org/A5083581319][Bing Li]], [[https://openalex.org/A5064842058][Yang Li]], [[https://openalex.org/A5020222501][Cheng Jin]], [[https://openalex.org/A5038871313][Yong Cao]], [[https://openalex.org/A5072063902][Juan Yang]], Rare Metals. None(None)] 2024. https://doi.org/10.1007/s12598-023-02531-6 
     
No abstract    

    

* A Mg Thermal Evaporation-Assisted Alloying/Dealloying Route for the Fabrication of Self-Supporting Nanostructured Metals  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391053773
:TOPICS: Evolution and Applications of Nanoporous Metals, Catalytic Reduction of Nitro Compounds, Electrocatalysis for Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4701091")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391053773"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391053773"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391053773"))][Get cited by]]

OpenAlex: https://openalex.org/W4391053773 (Open access: False)
    
[[https://openalex.org/A5064019950][Jian‐Bin Lin]], [[https://openalex.org/A5008587352][Weitao Zheng]], [[https://openalex.org/A5078083722][Wenxue Ke]], [[https://openalex.org/A5078699325][Xin He]], [[https://openalex.org/A5048714447][Pei Liang]], [[https://openalex.org/A5088141052][Chi Zhang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4701091 
     
Nanostructured metal-based materials exhibit significant promise as catalysts in applications involving oxygen catalysis. The surface alloying-dealloying combined strategy serves as a practical approach for creating a nanostructured layer on metal foils. In this study, we employed a magnesium (Mg) thermal evaporation-assisted method to establish a Mg-based alloy layer on corresponding metal foils (Cu, Ni, and Ag). Subsequent dealloying resulted in the formation of nanoporous Ag, Cu, and Ni on the ductile metal substrate. The dealloyed nanoporous Ni foil underwent additional treatment in an alkaline solution to produce a Ni(OH)2/Ni foil for catalyzing the oxygen evolution reaction (OER). The as-obtained self-supporting catalyst requires a 349 mV overpotential at a current density of 10 mA cm–2 and exhibits a Tafel slope of 84.52 mV dec–1 in 1 M KOH. After a 10-hour OER test under a constant potential, the catalyst shows negligible activity decrease. The distinctive thermal evaporation-assisted alloying/dealloying process is envisioned as a promising route for fabricating nanostructured self-supporting metal foils.    

    

* In Situ Growth of Nimoo4-C Nanocomposite and Electrodeposition of Multi-Metal Selenide to Enhance Oxygen Evolution Efficiency in Alkaline Solution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391053808
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4701118")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391053808"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391053808"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391053808"))][Get cited by]]

OpenAlex: https://openalex.org/W4391053808 (Open access: False)
    
[[https://openalex.org/A5047757698][Jin Liang]], [[https://openalex.org/A5001939388][Zhen Yang]], [[https://openalex.org/A5055827247][Liangliang Tian]], [[https://openalex.org/A5027120099][Yaxi Zhang]], [[https://openalex.org/A5009766034][Zhao Yin]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4701118 
     
The present study involves the in-situ preparation of a NiMoO4-C@NiFeMoSe composite electrocatalyst on a nickel foam (NF) substrate, achieved through the combined use of hydrothermal and electrodeposition techniques. After the hydrothermal process, the NF substrate was enveloped by a notably rugged composite structure composed of carbon sub-micron spheres uniformly dispersed and interlinked with NiMoO4 nanorods. To further enhance the electrocatalytic efficiency, a NiFeMo-based selenide was electrodeposited onto the surface of the NiMoO4-C/NF composite electrode. The NiMoO4-C@NiFeMoSe/NF composite electrode exhibited exceptional OER catalytic activity in a 1 M KOH solution, displaying an overpotential of merely 228 mV at a current density of 50 mA·cm-2 and a Tafel slope of 35.9 mV·dec-1, significantly lower than that of the blank NF. Moreover, for overall water splitting, the two-electrode NiMoO4-C@NiFeMoSe/NF||Pt-C/NF electrolyzer required a low potential of 1.48 V to achieve a current density of 10 mA·cm-2 and displayed exceptional long-term durability.    

    

* Enhanced Lanthanum-Stabilized Low Crystallinity Metal Oxide Electrocatalysts with Superior Activity for Oxygen Reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391057954
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.143858")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057954"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057954"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057954"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057954 (Open access: True)
    
[[https://openalex.org/A5062957668][M. García-Rodríguez]], [[https://openalex.org/A5080951898][D. Cazorla‐Amorós]], [[https://openalex.org/A5017951202][Emilia Morallón]], Electrochimica Acta. 479(None)] 2024. https://doi.org/10.1016/j.electacta.2024.143858 
     
Oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) are key electrochemical reactions for the development of rechargeable Zn-air batteries. However, due to the high cost of commercial noble metal-based catalysts and their limited bifunctionality, it is necessary the design of new electrocatalysts. In this study, stable electrocatalysts have been synthesized through a hydrothermal method and further low-temperature thermal treatment. The materials consist of La stabilized low crystallinity Mn and Co metal (hydro-)oxides. The electrocatalytic performance of these materials has been compared with counterparts calcined at higher temperatures. The findings demonstrate that materials synthesized at lower temperatures and with low crystallinity exhibit superior electrocatalytic activity for both ORR and OER. Moreover, the research highlights the favorable influence of the lanthanum cation, which enhances changes of surface morphology and oxidation states of other cations (Mn and Co). Additionally, the positive contribution of the carbon component to electrochemical activity and electrical conductivity has been elucidated. The best electrocatalyst was studied in a rechargeable Zn-air battery with a durability of up to 120 hours. They exhibited better stability and performance than the commercial Pt/C + RuO2 catalyst currently used.    

    

* Constructing highly efficient bifunctional catalysts for oxygen reduction and oxygen evolution by modifying MXene with transition metal  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391063505
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.089")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391063505"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391063505"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391063505"))][Get cited by]]

OpenAlex: https://openalex.org/W4391063505 (Open access: False)
    
[[https://openalex.org/A5061630253][Dai Yu]], [[https://openalex.org/A5047850201][Xiuyun Zhao]], [[https://openalex.org/A5016833284][Desheng Zheng]], [[https://openalex.org/A5059700536][Qingrui Zhao]], [[https://openalex.org/A5082664273][Jing Feng]], [[https://openalex.org/A5019670440][Yingjie Feng]], [[https://openalex.org/A5063446819][Xingbo Ge]], [[https://openalex.org/A5024977426][Xin Chen]], Journal of Colloid and Interface Science. 660(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.089 
     
Exploring highly active electrocatalysts for oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) has become a growing interest in recent years. Herein, an efficient pathway for designing MXene-based ORR/OER catalysts is proposed. It involves introducing non-noble metals into Vo (vacancy site), H1 and H2 (the hollow sites on top of C and the metal atom, respectively) sites on M2CO2 surfaces, named TM-VO/H1/H2-M2CO2 (TM = Fe, Co, Ni, M = V, Nb, Ta). Among these recombination catalysts, Co-H1-V2CO2 and Ni-H1-V2CO2 exhibit the most promising ORR catalytic activities, with low overpotential values of 0.35 and 0.37 V, respectively. Similarly, Fe-H1-V2CO2, Co-VO-Nb2CO2, and Ni-H2-Nb2CO2 possess low OER overpotential values of 0.29, 0.39, and 0.44 V, respectively, suggesting they have enormous potential as effective catalysts for OER. Notably, Co-H2-Ta2CO2 possesses the lowest potential gap value of 0.53 V, demonstrating it has an extraordinary bifunctional catalytic activity. The excellent catalytic performance of these recombination catalysts can be elucidated through an electronic structure analysis, which primarily relies on the electron-donating capacity and synergistic effects between transition metals and sub-metals. These results provide theoretical guidance for designing new ORR and OER catalysts using 2D MXene materials.    

    

* Ultrafast nanomanufacturing via high-temperature shock of La0.6Sr0.4CoO3 catalysts for overall water splitting  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391063536
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jmst.2023.11.067")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391063536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391063536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391063536"))][Get cited by]]

OpenAlex: https://openalex.org/W4391063536 (Open access: False)
    
[[https://openalex.org/A5063551301][Xiaoya Cui]], [[https://openalex.org/A5045048134][Wenyu Li]], [[https://openalex.org/A5043337244][Yanchang Liu]], [[https://openalex.org/A5072076154][Yumei Zhu]], [[https://openalex.org/A5003253796][Yanan Chen]], [[https://openalex.org/A5027586643][Cairong Gong]], [[https://openalex.org/A5014106223][Gang Xue]], No host. None(None)] 2024. https://doi.org/10.1016/j.jmst.2023.11.067 
     
Electrochemical water splitting, as an effective sustainable and eco-friendly energy conversion strategy, can produce high-purity hydrogen (H2) and oxygen (O2) via hydrogen evolution reaction (HER) and oxygen evolution reaction (OER), respectively, altering the nonrenewable fossil fuels. Here, La0.6Sr0.4CoO3 perovskite oxide nanoparticles with an orthorhombic phase were synthesized within 2 minutes in a one-step reaction, using a rapid and efficient high-temperature shock (HTS) method. Impressively, the as-prepared La0.6Sr0.4CoO3 with orthorhombic phase (HTS-2) exhibited better OER and HER performance than the hexagonal phase counterpart prepared using the traditional muffle furnace calcination method. The electrocatalytic performance enhancement of orthorhombic La0.6Sr0.4CoO3 can be attributed to the novel orthorhombic structure, such as confined strontium segregation, a higher percentage of highly oxidative oxygen species, and more active sites on the surface. This facile and rapid synthesis technique shows great potential for the rational design and crystal phase engineering of nanocatalysts.    

    

* Functionality Modulation Towards Thianthrene‐based Metal‐Free Electrocatalysts for Water Splitting  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391064426
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202310938")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391064426"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391064426"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391064426"))][Get cited by]]

OpenAlex: https://openalex.org/W4391064426 (Open access: False)
    
[[https://openalex.org/A5012601166][Arnab Sadhukhan]], [[https://openalex.org/A5001956023][Arun Karmakar]], [[https://openalex.org/A5072633154][Kalipada Koner]], [[https://openalex.org/A5021583376][Shayan Karak]], [[https://openalex.org/A5017849021][Rahul Kumar Sharma]], [[https://openalex.org/A5020461124][Avishek Roy]], [[https://openalex.org/A5050594951][Prince Sen]], [[https://openalex.org/A5006778568][Krishna Kishor Dey]], [[https://openalex.org/A5023539527][Venkataramanan Mahalingam]], [[https://openalex.org/A5018218171][Biswarup Pathak]], [[https://openalex.org/A5067628877][Subrata Kundu]], [[https://openalex.org/A5037939795][Rahul Banerjee]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202310938 
     
The development of metal-free bifunctional electrocatalysts for hydrogen and oxygen evolution reactions (HER and OER) is of significant importance but has been rarely demonstrated. Porous organic polymers (POPs) with well-defined electroactive functionalities show superior performance in HER and OER. Precise control of the active sites' local environment requires careful modulation of linkers through the judicious selection of building units. Here, we have introduced a systematic strategy for modulating functionality to design and synthesize a series of thianthrene-based bifunctional sp2 C = C bonded POPs with hollow spherical morphologies exhibiting superior electrocatalytic activity. This precise structural tuning allowed us to gain insight into the effects of heteroatom incorporation, hydrophilicity, and variations in linker length on electrocatalytic activity. The most efficient bifunctional electrocatalyst THT-PyDAN achieved a current density of 10 mAcm─2 at an overpotential (η10 ) of approximately 65 mV (in 0.5 M H2 SO4 ) and around 283 mV (in 1 M KOH) for HER and OER, respectively. THT-PyDAN exhibited superior activity to all previously reported metal-free bifunctional electrocatalysts in the literature. Furthermore, our investigations demonstrated that THT-PyDAN maintains its performance even after 36 hours of chronoamperometry and 1000 CV cycling. Post-catalytic characterization using FT-IR, XPS, and microscopic imaging techniques underscores the long-term durability of THT-PyDAN. This article is protected by copyright. All rights reserved.    

    

* Perovskite oxide-based nanoparticles embedded MXene composites for supercapacitors and oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391065582
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2023.110342")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391065582"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391065582"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391065582"))][Get cited by]]

OpenAlex: https://openalex.org/W4391065582 (Open access: False)
    
[[https://openalex.org/A5076144723][Zulfqar Ali Sheikh]], [[https://openalex.org/A5038308978][Dhanasekaran Vikraman]], [[https://openalex.org/A5076725095][Honggyun Kim]], [[https://openalex.org/A5044370419][Sikandar Aftab]], [[https://openalex.org/A5088213123][Shoyebmohamad F. Shaikh]], [[https://openalex.org/A5042724110][Faisal Shahzad]], [[https://openalex.org/A5076648886][Jongwan Jung]], [[https://openalex.org/A5005647960][Hyun‐Seok Kim]], [[https://openalex.org/A5084895339][Sajjad Hussain]], [[https://openalex.org/A5037744343][Deok‐kee Kim]], Journal of Energy Storage. 81(None)] 2024. https://doi.org/10.1016/j.est.2023.110342 
     
In this report, perovskite oxide-MnFeO3 nanoparticles embedded MXene sheets were prepared by hydrothermal approach for the effective water splitting and energy stowage uses. The prepared MXene@MnFeO3 hybrid nanocomposites exhibited outstanding 1077 F/g specific capacitance at a current density of 1 A g−1 and excellent cycling solidity (capacitance retention after the 3000 cycle is 96.5 %). In addition, an asymmetric capacitor delivered a ultimate specific energy of 114 Wh/kg at a specific power of 2117 W/kg. MXene@MnFeO3 hybrid catalyst required a credible overpotential of 235 mV to achieve the 10 mA cm−2 current density, along with the small Tafel slope of 41 mV dec−1 for OER in 1 M KOH and long-span 24 h stability. Our proposed strategy of perovskite oxide nanoparticles hybridized highly conductive MXene sheets would be suitable alternative as the potential electrode materials for the efficient energy storage/conversion application.    

    

* Transition metal Co induce CoSe2/NiWSe2 interface structural reorganization for efficient oxygen evolution reaction and urea oxidation reaction.  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391072038
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.103950")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391072038"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391072038"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391072038"))][Get cited by]]

OpenAlex: https://openalex.org/W4391072038 (Open access: False)
    
[[https://openalex.org/A5014155211][Kankan Liu]], [[https://openalex.org/A5086137269][Jing Cheng]], [[https://openalex.org/A5045801401][Yi-miao Yu]], [[https://openalex.org/A5040797280][Sui Zhitong]], [[https://openalex.org/A5012751989][Fengbo Guo]], [[https://openalex.org/A5085709665][Shijun Lei]], [[https://openalex.org/A5055603268][Lixin Zhang]], [[https://openalex.org/A5087592842][Meng Li]], [[https://openalex.org/A5000092852][Yun Ye]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.103950 
     
Urea-containing wastewater has become an increasingly serious environmental and energy problem. The use of electrochemical urea oxidation reaction (UOR) technology to treat wastewater containing urea has gained considerable significance. The regulation of the composition and electronic properties of the catalyst by doping transition metal elements is crucial for the development of oxygen evolution reaction (OER) and UOR catalysts with high catalytic activity. In this paper, WSe2, CoSe2, NiWSe2 and CoSe2/NiWSe2 were synthesized by hydrothermal method combined with annealing treatment. Compared with WSe2, CoSe2, and NiWSe2, the OER and UOR catalytic activity of CoSe2/NiWSe2 are significantly improved. For OER, a low overpotential of 1.44 V is all that is needed to reach a current density of 10 mA cm−2. The overpotential of UOR is only 1.32 @ 10 mA cm−2, and it can still maintain excellent electrochemical stability after 30 h. The electronic structure of CoSe2/NiWSe2 is changed by the incorporation of Co, thereby improving the conductivity and accelerating the reaction kinetics. CoSe2 particles are uniformly distributed on the layered NiWSe2 nanosheets, which promotes the charge transfer and synergistic effect at the interface between CoSe2 and NiWSe2. The nanoflower-like structure with thin edges enriches the active sites of CoSe2/NiWSe2. Therefore, the transition metal element doping technology can provide a new method for the development of efficient OER and UOR electrocatalysts and provide a new way to reduce the overall energy consumption during urea degradation.    

    

* Le Chatelier’s principle to stabilize intrinsic surface structure of oxygen-evolving catalyst for enabling ultra-high catalytic stability of zinc-air battery and water splitting  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391072091
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Catalytic Nanomaterials
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nanoen.2024.109300")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391072091"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391072091"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391072091"))][Get cited by]]

OpenAlex: https://openalex.org/W4391072091 (Open access: False)
    
[[https://openalex.org/A5008124643][Jie Zhu]], [[https://openalex.org/A5056465234][Long Li]], [[https://openalex.org/A5085613060][Minhua Cao]], Nano Energy. 122(None)] 2024. https://doi.org/10.1016/j.nanoen.2024.109300 
     
Well-designed highly active intrinsic surface structure of a catalyst for oxygen evolution reaction (OER) often faces the problem of corrosion dissolution, which severely deteriorates its catalytic stability, and breaking this activity-stability trade-off has always been a huge and long-term challenge. Herein, we employ Le Chatelier’s principle to address this dissolution problem of the catalyst to maintain its intrinsic surface structure for highly efficient and ultra-stable OER. Taking highly active but susceptible oxygen vacancy-rich Co-W oxide as the model catalyst for alkaline OER, its dissolving kinetics is significantly passivated by introducing homo ions into the electrolyte to regulate the dissolution equilibrium, thus achieving ultralong operating stability without sacrificing its high activity. The theoretical calculations and in-situ experimental results unravel the underlying mechanism of this strategy, that is, the homo ions (tungstate ions) can be preferentially adsorbed on the catalyst surface to construct a local non-corrosive environment, thus effectively stabilizing the well-designed unsaturated active cobalt sites to maintain the intrinsic surface structure of the catalyst and preventing them from being reconstructed or transformed toward the unfavorable direction. Importantly, this strategy is also effective in zinc-air battery and electrolytic water splitting, achieving ultra-stable performance over 1200 h, which is of great importance for promoting the practical applications of low-cost non-noble metal-based catalysts in energy devices.    

    

* RuO2 Catalysts for Electrocatalytic Oxygen Evolution in Acidic Media: Mechanism, Activity Promotion Strategy and Research Progress  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391089701
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29020537")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391089701"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391089701"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391089701"))][Get cited by]]

OpenAlex: https://openalex.org/W4391089701 (Open access: True)
    
[[https://openalex.org/A5017868526][Jirong Bai]], [[https://openalex.org/A5010613556][Wei Zhou]], [[https://openalex.org/A5076374914][Jingliang Xu]], [[https://openalex.org/A5073422926][Quanfa Zhou]], [[https://openalex.org/A5089644945][Yaoyao Deng]], [[https://openalex.org/A5043376291][Mei Xiang]], [[https://openalex.org/A5050863510][Dongsheng Xiang]], [[https://openalex.org/A5013121247][Yaqiong Su]], Molecules. 29(2)] 2024. https://doi.org/10.3390/molecules29020537  ([[https://www.mdpi.com/1420-3049/29/2/537/pdf?version=1705913442][pdf]])
     
Proton Exchange Membrane Water Electrolysis (PEMWE) under acidic conditions outperforms alkaline water electrolysis in terms of less resistance loss, higher current density, and higher produced hydrogen purity, which make it more economical in long-term applications. However, the efficiency of PEMWE is severely limited by the slow kinetics of anodic oxygen evolution reaction (OER), poor catalyst stability, and high cost. Therefore, researchers in the past decade have made great efforts to explore cheap, efficient, and stable electrode materials. Among them, the RuO2 electrocatalyst has been proved to be a major promising alternative to Ir-based catalysts and the most promising OER catalyst owing to its excellent electrocatalytic activity and high pH adaptability. In this review, we elaborate two reaction mechanisms of OER (lattice oxygen mechanism and adsorbate evolution mechanism), comprehensively summarize and discuss the recently reported RuO2-based OER electrocatalysts under acidic conditions, and propose many advanced modification strategies to further improve the activity and stability of RuO2-based electrocatalytic OER. Finally, we provide suggestions for overcoming the challenges faced by RuO2 electrocatalysts in practical applications and make prospects for future research. This review provides perspectives and guidance for the rational design of highly active and stable acidic OER electrocatalysts based on PEMWE.    

    

* Atomic Single-Layer Ir Clusters Enabling 100% Selective Chlorine Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391096719
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05738")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391096719"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391096719"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391096719"))][Get cited by]]

OpenAlex: https://openalex.org/W4391096719 (Open access: False)
    
[[https://openalex.org/A5061084605][Shuang Li]], [[https://openalex.org/A5040981831][Xu Guo]], [[https://openalex.org/A5086532814][Xiaofang Liu]], [[https://openalex.org/A5017390855][Jianglan Shui]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05738 
     
The exclusive selectivity of the chlorine evolution reaction (CER) is crucial for the chlor-alkali industry to obtain pure chlorine gas and avoid the cost of separating the byproduct oxygen. However, 100% CER selectivity remains a challenge for the currently known CER catalysts. Here, we report a catalyst of atomic single-layer Ir clusters on CeO2 nanorods (IrSL/CeO2). Under the strong metal/support interaction, IrSL has a strong adsorption to oxygen, thereby suppressing the oxygen evolution reaction. Coupled with the uniform active sites of the single-layer Ir clusters, IrSL/CeO2 achieves almost 100% CER selectivity in acidic NaCl solution ranging from open circuit potential to practical current density levels. In addition, IrSL/CeO2 exhibits 1.7 times higher catalytic activity than its single-atom counterparts, and its noble metal efficiency is 84 times higher than that of commercial anodes (DSAs). Our finding provides a solution to the selective catalysis of chlor-alkali electrolysis.    

    

* Biomimetic nucleotide-graphene hybrids for electrocatalytic oxygen conversion: Quantifying biomolecule mass loading  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391099761
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Conducting Polymer Research
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.susmat.2024.e00835")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391099761"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391099761"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391099761"))][Get cited by]]

OpenAlex: https://openalex.org/W4391099761 (Open access: True)
    
[[https://openalex.org/A5067007951][A. Letona-Elizburu]], [[https://openalex.org/A5035141064][Marina Enterría]], [[https://openalex.org/A5024135658][Alex Aziz]], [[https://openalex.org/A5015242194][S. Villar–Rodil]], [[https://openalex.org/A5011616803][J.I. Paredes]], [[https://openalex.org/A5072947717][Javier Carrasco]], [[https://openalex.org/A5036598552][Nagore Ortiz‐Vitoriano]], Sustainable Materials and Technologies. None(None)] 2024. https://doi.org/10.1016/j.susmat.2024.e00835 
     
Metal-free electrocatalysts for the electrochemical conversion of gases constitute an important asset for a sustainable energy transition. Nucleotides act as redox mediators in the electron transport chain to reduce oxygen in cellular respiration. The biomimicry of such an efficient natural mechanism could be utilized to address the challenges associated with electrochemical gas conversion technologies, such as sluggish kinetics and high overpotentials. Multiple descriptors are generally reported to benchmark the activity of electrocatalysts where the turnover frequency (TOF) is claimed to be the most accurate criterion. Here, a library of graphene nanosheets-nucleotide hybrid materials was prepared, and the electrocatalytic performance towards ORR/OER reactions of a graphene-flavin mononucleotide hybrid was evaluated by rotating disc electrode experiments and TOF estimation. The determination of catalyst loading and dispersion is especially relevant when assessing the intrinsic activity of a catalyst and, therefore, the amount of nucleotide electrocatalyst loaded into the graphene support was thoroughly quantified by a combination of characterization techniques. Density functional theory calculations supported the observed experimental trends, both on the adsorption rate of a given nucleotide on graphene and the catalytic activity of a specific hybrid material. This work constitutes an avenue to predict nature-mimicking electrocatalysts for efficient energy storage.    

    

* Cooperative Agreement of Binuclear 2D Metal–Organic Framework Sites for Superior Bifunctional Oxygen Electrocatalysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391101616
:TOPICS: Electrocatalysis for Energy Conversion, Chemistry and Applications of Metal-Organic Frameworks, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.3c07547")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391101616"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391101616"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391101616"))][Get cited by]]

OpenAlex: https://openalex.org/W4391101616 (Open access: False)
    
[[https://openalex.org/A5075466230][Naomi Helsel]], [[https://openalex.org/A5047745844][Pabitra Pal Choudhury]], The Journal of Physical Chemistry C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.3c07547 
     
This work analyzes the bifunctional activity of a binuclear two-dimensional metal–organic framework fragment (2D-SA) utilizing ab initio spin-polarized density functional theory calculations. Cobalt, iron, and a combination of the two metals were simulated due to their history with promising oxygen reduction/oxygen evolution reactions (ORR/OER) activity. The favorable reaction pathways of both the ORR and OER have been realized including the addition of pristine/doped graphene substrate. The Co-2D-SAs had the best performance toward OER only, while the Fe-2D-SAs were favorable toward ORR. The results show that when the bimetallic Co/Fe-2D-SA was supported by graphene, both the ORR overpotential of the Fe site and the OER overpotential of the Co site were found to be the best for the bifunctional activity. This superior bifunctional activity is attributed to both the substrate effect and cooperative agreement between iron and cobalt in the bimetallic 2D-SA by adjusting their spin states due to the antiferromagnetic coupling of the binuclear sites.    

    

* Supramolecular Macrocycle Regulated Single‐Atom MoS2@Co Catalysts for Enhanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391104715
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/eem2.12702")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391104715"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391104715"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391104715"))][Get cited by]]

OpenAlex: https://openalex.org/W4391104715 (Open access: True)
    
[[https://openalex.org/A5041883250][Shuai Cao]], [[https://openalex.org/A5074070914][Wenzhuo Wu]], [[https://openalex.org/A5024518325][Chaozhong Liu]], [[https://openalex.org/A5080837140][Leqian Song]], [[https://openalex.org/A5073882835][Qun Xu]], [[https://openalex.org/A5000730080][Huacheng Zhang]], [[https://openalex.org/A5045285053][Yanli Zhao]], No host. None(None)] 2024. https://doi.org/10.1002/eem2.12702  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/eem2.12702][pdf]])
     
The development of active water oxidation catalysts for water splitting has stimulated considerable interest. Herein, the design and building of single atom Co sites using a supramolecular tailoring strategy are reported, that is, the introduction of pillar[4]arene[1]quinone (P4A1Q) permits mononuclear Co species stereoelectronically assembled on MoS 2 matrix to construct an atomically dispersed MoS 2 @Co catalyst with modulated local electronic structure, definite chemical environment and enhanced oxygen evolution reaction performance. Theoretical calculations indicate that immsobilized single‐Co sites exhibit an optimized adsorption capability of oxygen‐containing intermediates, endowing the catalyst an excellent electrocatalytic oxygen evolution reaction activity, with a low overpotential of 370 mV at 10 mA cm −2 and a small Tafel slope of 90 mV dec −1 . The extendable potential of this strategy to other electrocatalysts such as MoS 2 @Ni and MoS 2 @Zn, and other applications such as the hydrogen evolution reaction was also demonstrated. This study affords new insights into the rational design of single metal atom systems with enhanced electrocatalytic performance.    

    

* Metal‐Organic Frameworks: Direct Synthesis by Organic Acid‐Etching and Reconstruction Disclosure as Oxygen Evolution Electrocatalysts  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391106343
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202400323")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391106343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391106343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391106343"))][Get cited by]]

OpenAlex: https://openalex.org/W4391106343 (Open access: False)
    
[[https://openalex.org/A5058010200][Xiao Wang]], [[https://openalex.org/A5003073100][Wei Zhou]], [[https://openalex.org/A5079909263][Shengliang Zhai]], [[https://openalex.org/A5002323224][Xiaokang Chen]], [[https://openalex.org/A5083593030][Peng Zheng]], [[https://openalex.org/A5017916417][Zhi Liu]], [[https://openalex.org/A5080964989][Weiqiao Deng]], [[https://openalex.org/A5000637115][Hao Wu]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202400323 
     
Metal‐organic frameworks (MOFs) have emerged as promising oxygen evolution reaction (OER) electrocatalysts. Chemically bonded MOFs on supports are desirable yet lacking in routine synthesis, as they may allow variable structural evolution and the underlying structure‐activity relationship to be disclosed. Herein, direct MOF synthesis is achieved by an organic acid‐etching strategy (AES). Using π‐conjugated ferrocene (Fc) dicarboxylic acid as the etching agent and organic ligand, a series of MFc‐MOF (M = Ni, Co, Fe, Zn) nanosheets are synthesized on the metal supports. The crystal structure is studied using X‐ray diffraction and low‐dose transmission electron microscopy, which is quasi‐lattice‐matched with that of the metal, enabling in‐situ MOF growth. Operando Raman and attenuated total reflectance Fourier transform infrared spectroscopy disclose that the NiFc‐MOF features dynamic structural rebuilding during OER. The reconstructed one showing optimized electronic structures with an upshifted total d‐band center, high M‐O bonding state occupancy, and localized electrons on adsorbates indicated by density functional theory calculations, exhibits outstanding OER performance with a fairly low overpotential (130 mV at 10 mA cm‐2) and good stability (144 h). The newly established approach for direct MOF synthesis and structural reconstruction disclosure stimulate the development of more prudent catalysts for advancing OER.    

    

* P‐Incorporation Induced Enhancement of Lattice Oxygen Participation in Double Perovskite Oxides to Boost Water Oxidation  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391108255
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202309091")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391108255"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391108255"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391108255"))][Get cited by]]

OpenAlex: https://openalex.org/W4391108255 (Open access: False)
    
[[https://openalex.org/A5064379315][Gaoliang Fu]], [[https://openalex.org/A5041308193][Leilei Zhang]], [[https://openalex.org/A5038016779][Ruixue Wei]], [[https://openalex.org/A5091194552][Huili Liu]], [[https://openalex.org/A5053413075][Ruipeng Hou]], [[https://openalex.org/A5033669929][Yue Zhang]], [[https://openalex.org/A5038424932][Kun Yang]], [[https://openalex.org/A5084707037][Shouren Zhang]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202309091 
     
Abstract Activating the lattice oxygen in the catalysts to participate in the oxygen evolution reaction (OER), which can break the scaling relation–induced overpotential limitation (> 0.37 V) of the adsorbate evolution mechanism, has emerged as a new and highly effective guide to accelerate the OER. However, how to increase the lattice oxygen participation of catalysts during OER remains a major challenge. Herein, P‐incorporation induced enhancement of lattice oxygen participation in double perovskite LaNi 0.58 Fe 0.38 P 0.07 O 3‐σ (PLNFO) is studied. P‐incorporation is found to be crucial for enhancing the OER activity. The current density reaches 1.35 mA cm ECSA −2 at 1.63 V (vs RHE), achieving a sixfold increase in intrinsic activity. Experimental evidences confirm the dominant lattice oxygen participation mechanism (LOM) for OER pathway on PLNFO. Further electronic structures reveal that P‐incorporation shifts the O p ‐band center by 0.7 eV toward the Fermi level, making the states near the Fermi level more O p character, thus facilitating LOM and fast OER kinetics. This work offers a possible method to develop high‐performance double perovskite OER catalysts for electrochemical water splitting.    

    

* Metal‐Organic Frameworks: Direct Synthesis by Organic Acid‐Etching and Reconstruction Disclosure as Oxygen Evolution Electrocatalysts  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391109251
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202400323")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391109251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391109251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391109251"))][Get cited by]]

OpenAlex: https://openalex.org/W4391109251 (Open access: False)
    
[[https://openalex.org/A5058010200][Xiao Wang]], [[https://openalex.org/A5003073100][Wei Zhou]], [[https://openalex.org/A5079909263][Shengliang Zhai]], [[https://openalex.org/A5002323224][Xiaokang Chen]], [[https://openalex.org/A5083593030][Peng Zheng]], [[https://openalex.org/A5017916417][Zhi Liu]], [[https://openalex.org/A5080964989][Weiqiao Deng]], [[https://openalex.org/A5000637115][Hao Wu]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202400323 
     
Metal-organic frameworks (MOFs) have emerged as promising oxygen evolution reaction (OER) electrocatalysts. Chemically bonded MOFs on supports are desirable yet lacking in routine synthesis, as they may allow variable structural evolution and the underlying structure-activity relationship to be disclosed. Herein, direct MOF synthesis is achieved by an organic acid-etching strategy (AES). Using π-conjugated ferrocene (Fc) dicarboxylic acid as the etching agent and organic ligand, a series of MFc-MOF (M = Ni, Co, Fe, Zn) nanosheets are synthesized on the metal supports. The crystal structure is studied using X-ray diffraction and low-dose transmission electron microscopy, which is quasi-lattice-matched with that of the metal, enabling in-situ MOF growth. Operando Raman and attenuated total reflectance Fourier transform infrared spectroscopy disclose that the NiFc-MOF features dynamic structural rebuilding during OER. The reconstructed one showing optimized electronic structures with an upshifted total d-band center, high M-O bonding state occupancy, and localized electrons on adsorbates indicated by density functional theory calculations, exhibits outstanding OER performance with a fairly low overpotential (130 mV at 10 mA cm-2) and good stability (144 h). The newly established approach for direct MOF synthesis and structural reconstruction disclosure stimulate the development of more prudent catalysts for advancing OER.    

    

* Enhancing the Oxygen Evolution Reaction Activity of Sputtered Ni, NiO, and NiNiO Thin Films by Incorporating Fe  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391111261
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202300485")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391111261"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391111261"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391111261"))][Get cited by]]

OpenAlex: https://openalex.org/W4391111261 (Open access: True)
    
[[https://openalex.org/A5091924449][Megan Heath]], [[https://openalex.org/A5083983909][M.C. Potgieter]], [[https://openalex.org/A5030723152][Frode Seland]], [[https://openalex.org/A5082270903][Svein Sunde]], [[https://openalex.org/A5075904387][R.J. Kriek]], ChemElectroChem. None(None)] 2024. https://doi.org/10.1002/celc.202300485  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/celc.202300485][pdf]])
     
Abstract The effect of Fe‐containing alkaline electrolyte, on the oxygen evolution reaction (OER) activity of Ni electrocatalysts, has long been of interest as Fe increases the OER activity of Ni electrocatalysts. However, controversy exists as to whether it is surface or bulk Fe that is responsible for the increased activity. In this study, magnetron sputtering was employed to sputter Ni, NiO and NiNiO thin film electrocatalysts to study the effect that different concentrations of Fe in the electrolyte have on their OER activities. It was found that increasing concentrations of Fe increasingly enhanced the OER activity of these thin film electrocatalysts until the electrolyte was saturated with Fe. The lowest overpotential achieved is 279 mV (at 10 mA cm −2 ) for NiNiO cycled in KOH containing 1 mM Fe, with all three thin film electrocatalysts exhibiting overpotentials within the same range after 30 voltammetry cycles in 0.9 ppm Fe and 1 mM Fe. All Tafel slopes are between 36 and 45 mV dec −1 indicating similar kinetics for the samples cycled in different Fe concentrations. Energy‐dispersive X‐ray spectroscopy and X‐ray photoelectron spectroscopy results show that Fe is found in the top layers of the electrocatalysts after cycling.    

    

* Recycling spent LiNi1-x-yCoxMnyO2 cathodes to efficient catalysts for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391112539
:TOPICS: Battery Recycling and Rare Earth Recovery, Lithium-ion Battery Technology, Global E-Waste Recycling and Management
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3gc04503j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391112539"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391112539"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391112539"))][Get cited by]]

OpenAlex: https://openalex.org/W4391112539 (Open access: False)
    
[[https://openalex.org/A5038689848][Mingfei Chen]], [[https://openalex.org/A5053008395][Yixin Zhou]], [[https://openalex.org/A5040027560][Wang Li]], [[https://openalex.org/A5017138446][Ganglin Xue]], [[https://openalex.org/A5082529409][Jili Guo]], [[https://openalex.org/A5086161254][Yaping Wang]], Green Chemistry. None(None)] 2024. https://doi.org/10.1039/d3gc04503j 
     
The wide application of lithium-ion batteries (LIBs) for electric vehicles forebodes the future decommissioning tide of spent LIBs. Therefore, the recycling of spent LIBs has garnered significant attention, primarily due...    

    

* Recent Advances in the Electrochemical Production of Hydrogen Peroxide  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391116428
:TOPICS: Electrocatalysis for Energy Conversion, Microbial Fuel Cells and Electrogenic Bacteria Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.143872")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391116428"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391116428"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391116428"))][Get cited by]]

OpenAlex: https://openalex.org/W4391116428 (Open access: False)
    
[[https://openalex.org/A5093765053][Nishu Dhanda]], [[https://openalex.org/A5093765054][Yogesh Kumar Panday]], [[https://openalex.org/A5086118092][Sudesh Kumar]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.143872 
     
Hydrogen peroxide (H2O2) is an innovative and environmentally friendly oxidant that finds wide-ranging applications across multiple industries. In the past, H2O2 production predominantly relied on the anthraquinone method, which had drawbacks such as the generation of organic waste and the requirement for energy-intensive reactions. A cheap, efficient, and sustainable way of producing H2O2 may be achieved through the redox reaction between oxygen and water. On both small and large scales, the electrosynthesis of H2O2 is practical and affordable. In recent years, it has been thought that the energy-intensive anthraquinone process may be replaced by the electrochemical synthesis of H2O2 via the two-electron oxygen reduction reaction (ORR) route. To eliminate the organic pollutants found in drinking water and industrial effluent, highly effective hydrogen peroxide (H2O2) must be produced electrochemically using gas diffusion electrodes (GDEs). Compared to other carbonaceous cathodes, the GDEs as cathodic electrocatalysts demonstrate greater cost-effectiveness, lower energy consumption, and higher oxygen utilization efficiency for the formation of H2O2. A promising alternative for enabling the growth of sustainable economics in the W&W sector is microbial electrochemical systems (MESs) that create H2O2. To enhance the efficiency and predictability of H2O2 production in MESs, a machine-learning approach was adopted, incorporating a meta-learning methodology to forecast the generation rate of H2O2 in MES based on the seven input variables, comprising several design and operational parameters.    

    

* Manganese doped hollow cobalt oxide catalysts for highly efficient oxygen evolution in wide pH range  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391116783
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148926")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391116783"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391116783"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391116783"))][Get cited by]]

OpenAlex: https://openalex.org/W4391116783 (Open access: False)
    
[[https://openalex.org/A5064335791][Jingyi Xie]], [[https://openalex.org/A5075396691][Fuli Wang]], [[https://openalex.org/A5044697608][Xue-Jun Zhai]], [[https://openalex.org/A5022526821][Xin Li]], [[https://openalex.org/A5050840588][Yusheng Zhang]], [[https://openalex.org/A5020310913][Ruo‐Yao Fan]], [[https://openalex.org/A5056244939][Ren-Qing Lv]], [[https://openalex.org/A5062331341][Yong‐Ming Chai]], [[https://openalex.org/A5072072030][Bin Dong]], Chemical Engineering Journal. 482(None)] 2024. https://doi.org/10.1016/j.cej.2024.148926 
     
Heteroatomic substitution of spinel oxides can theoretically optimize oxygen evolution reaction (OER) via redistribution of charges and modification of d-band center. However, the wide pH range of electrocatalysis and catalytic mechanism are still great challenges. Herein, we successfully construct heteroatom Mn-substituted spinel Co3O4 (Mn-Co3O4) with porous hollow sphere structure for highly efficient and wide pH range OER. Benefiting from the atomic Mn-substitution and charge transfer, the Co site in Mn-Co3O4 displays an increased ratio of Co3+/Co2+. Electrochemical measurements demonstrate that Mn-Co3O4 exhibited superior OER activities with small overpotentials of only 305, 520 and 460 mV to afford a current density of 10 mA cm−2 in alkaline, neutral and acidic media, respectively. Meanwhile, Mn-Co3O4 also possesses favorable long-term stability in wide-pH electrolyte. The improved reaction kinetics of Mn-Co3O4 are mainly attributed to the unique hollow sphere structure with high specific surface area, and the increased high valency of Co, which can introduce the d-band center modification of Mn-Co3O4, and reduce the adsorption energy of oxygen intermediates in rate-determining step (RDS).    

    

* Ligand and Strain Synergistic Effect in NiFeP0.32 LDH for Triggering Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391138320
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202309689")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391138320"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391138320"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391138320"))][Get cited by]]

OpenAlex: https://openalex.org/W4391138320 (Open access: False)
    
[[https://openalex.org/A5022499603][Hao Chen]], [[https://openalex.org/A5006727551][Yongbing Ma]], [[https://openalex.org/A5052938560][Yun Han]], [[https://openalex.org/A5047854433][Xin Mao]], [[https://openalex.org/A5026237491][Yongbin Hu]], [[https://openalex.org/A5059383335][Xin Zhao]], [[https://openalex.org/A5037548250][Qi Dong]], [[https://openalex.org/A5022721559][Bo Wen]], [[https://openalex.org/A5082839443][Aijun Du]], [[https://openalex.org/A5006822602][Xin Wang]], [[https://openalex.org/A5029525816][Xiao Lyu]], [[https://openalex.org/A5019299841][Yi Jia]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202309689 
     
Abstract Developing efficient water‐splitting electrocatalysts to accelerate the slow oxygen evolution reaction (OER) kinetics is urgently desired for hydrogen production. Herein, ultralow phosphorus (P)‐doped NiFe LDH (NiFeP x LDH) with mild compressive strain is synthesized as an efficient OER electrocatalyst. Remarkably, NiFeP x LDH with the phosphorus mass ratio of 0.32 wt.% and compressive strain ratio of 2.53% (denoted as NiFeP 0.32 LDH) exhibits extraordinary OER activity with an overpotential as low as 210 mV, which is superior to that of commercial IrO 2 and other reported P‐based OER electrocatalysts. Both experimental performance and density function theory (DFT) calculation demonstrate that the doping of P atoms can generate covalent Fe─P coordination bonds and lattice distortion, thus resulting in the consequent depletion of electrons around the Fe active center and the downward shift of the d ‐band center, which can lead to a weaker adsorption ability of * O intermediate to improve the catalytic performance of NiFeP 0.32 LDH for OER. This work provides novel insights into the distinctive coordinated configuration of P in NiFeP x LDH, which can result in superior catalytic performance for OER.    

    

* Single-atom catalysts for electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391488890
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/b978-0-323-95237-8.00012-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391488890"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391488890"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391488890"))][Get cited by]]

OpenAlex: https://openalex.org/W4391488890 (Open access: False)
    
[[https://openalex.org/A5069942203][Ajit Singh]], [[https://openalex.org/A5071537088][B. N. Singh]], [[https://openalex.org/A5019059433][Arindam Indra]], Elsevier eBooks. None(None)] 2024. https://doi.org/10.1016/b978-0-323-95237-8.00012-4 
     
In recent years, a series of noble metals and transition metal-based single-atom catalysts (SACs) have been explored for electrochemical oxygen evolution reaction (OER). The unique structural and electronic features of the SACs facilitate the OER with maximum atomic utilization. As a result, a high turnover frequency is achieved with SACs. In this chapter, we have summarized the fundamentals of the SACs and their design strategies for electrochemical OER. The detailed characterization of the SACs and its utilization in OER has been discussed with suitable examples. The principles and reaction mechanism of electrochemical OER with SACs have been discussed looking at the structure of the active catalyst and reaction intermediates.    

    

* Interface effect of MXene/CoP2 on oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391345030
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Memristive Devices for Neuromorphic Computing, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.136024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391345030"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391345030"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391345030"))][Get cited by]]

OpenAlex: https://openalex.org/W4391345030 (Open access: False)
    
[[https://openalex.org/A5053911795][Xiu Juan Du]], [[https://openalex.org/A5028486288][Yan Wang]], [[https://openalex.org/A5045672660][Zicong Ye]], [[https://openalex.org/A5029061297][Wei Wang]], [[https://openalex.org/A5067124076][Yuqiao Wang]], Materials Letters. None(None)] 2024. https://doi.org/10.1016/j.matlet.2024.136024 
     
Zero/two-dimension MXene/CoP2 was fabricated by hydrothermal and chemical vapor deposition phosphate. MXene nanosheets were employed as substrate to increase dispersion and stability of the multicomponent catalyst. The morphology of CoP2 was regulated by the addtion of Co precursor in hydrothermal process. The catalyst prepared by 40 mg MXene with 0.5 mmol Co precursor (MXene/CoP2-0.5) showed a uniform growth of CoP2 and formed aboundant reaction sites. The interfacial electron transfer between MXene and CoP2 modulated the electron structure of CoP2 and stimulated the oxygen evolution reaction (OER) activity. The optimized MXene/CoP2-0.5 exhibited the OER overpotential of 263 mV and a long-term stability over 16 h. Modulating the interfacial electron transfer of multicomponent catalysts provided a guidance for electrocatalyst design and synthesis.    

    

* Insights on MOF-derived metal–carbon nanostructures for oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391225155
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Nanomaterials with Enzyme-Like Characteristics
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3dt04263d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391225155"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391225155"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391225155"))][Get cited by]]

OpenAlex: https://openalex.org/W4391225155 (Open access: False)
    
[[https://openalex.org/A5084914364][Junliang Chen]], [[https://openalex.org/A5054473752][Jinjie Qian]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d3dt04263d 
     
Electrochemical water splitting has been regarded a promising method for the production of green hydrogen, addressing the need for efficient energy conversion and storage. However, it is severely hindered by the oxygen evolution reaction (OER) because of its multi-step four-electron transfer pathway with sluggish reaction kinetics. Microporous metal-organic-frameworks (MOFs), by virtue of large specific surface area, high porosity, tunable composition and morphology, find widespread use as precursors of metal-carbon nanostructures. The resulting carbon nanomaterials can well inherit the characteristics and advantages of the crystalline MOF precursors, and exhibit versatile application prospects in the fields of environment and energy, particularly in OER. Herein, a meticulous overview of the synthesis strategy for MOF-derived metal-carbon nanostructures and the origins of their enhanced OER properties has been demonstrated. We comprehensively illustrate these aspects across three dimensions: MOF selection, metal introduction, and carbon structures. Finally, the challenges and future prospects for this emerging field will be presented.    

    

* Reconstructing Hydrogen‐Bond Network for Efficient Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391328163
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202319462")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391328163"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391328163"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391328163"))][Get cited by]]

OpenAlex: https://openalex.org/W4391328163 (Open access: False)
    
[[https://openalex.org/A5049330397][Shicheng Zhu]], [[https://openalex.org/A5027981734][Ruoou Yang]], [[https://openalex.org/A5023169057][Huangjingwei Li]], [[https://openalex.org/A5011612912][Sirui Huang]], [[https://openalex.org/A5040389793][Haozhi Wang]], [[https://openalex.org/A5032965785][Youwen Liu]], [[https://openalex.org/A5028386144][Huiqiao Li]], [[https://openalex.org/A5069378732][Tianrui Zhai]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202319462 
     
Developing highly active oxygen evolution reaction (OER) catalysts in acidic conditions is a pressing demand for proton‐exchange membrane water electrolysis. Manipulating proton character at the electrified interface, as the crux of all proton‐coupled electrochemical reactions, is highly desirable but elusive. Herein we present a promising protocol, which reconstruct a connected hydrogen‐bond network beween the catalyst‐electrolyte interface by coupling hydrophilic units to boost acidic OER activity. Modelling on N‐doped‐carbon‐layer clothed Mn‐doped‐Co3O4 (Mn‐Co3O4@CN), we unravel that the hydrogen‐bond interaction between CN units and H2O molecule not only drags the free water to enrich the surface of Mn‐Co3O4 but also serves as a channel to promote the dehydrogenation process. Meanwhile, the modulated local charge of the Co sites from CN units/Mn dopant lowers the OER barrier. Therefore, Mn‐Co3O4@CN surpasses RuO2 at high current density (100 mA cm‐2 @ ~538 mV).    

    

* Reconstructing Hydrogen‐Bond Network for Efficient Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391329795
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202319462")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391329795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391329795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391329795"))][Get cited by]]

OpenAlex: https://openalex.org/W4391329795 (Open access: False)
    
[[https://openalex.org/A5049330397][Shicheng Zhu]], [[https://openalex.org/A5027981734][Ruoou Yang]], [[https://openalex.org/A5023169057][Huangjingwei Li]], [[https://openalex.org/A5011612912][Sirui Huang]], [[https://openalex.org/A5040389793][Haozhi Wang]], [[https://openalex.org/A5032965785][Youwen Liu]], [[https://openalex.org/A5028386144][Huiqiao Li]], [[https://openalex.org/A5069378732][Tianrui Zhai]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202319462 
     
Developing highly active oxygen evolution reaction (OER) catalysts in acidic conditions is a pressing demand for proton‐exchange membrane water electrolysis. Manipulating proton character at the electrified interface, as the crux of all proton‐coupled electrochemical reactions, is highly desirable but elusive. Herein we present a promising protocol, which reconstruct a connected hydrogen‐bond network beween the catalyst‐electrolyte interface by coupling hydrophilic units to boost acidic OER activity. Modelling on N‐doped‐carbon‐layer clothed Mn‐doped‐Co3O4 (Mn‐Co3O4@CN), we unravel that the hydrogen‐bond interaction between CN units and H2O molecule not only drags the free water to enrich the surface of Mn‐Co3O4 but also serves as a channel to promote the dehydrogenation process. Meanwhile, the modulated local charge of the Co sites from CN units/Mn dopant lowers the OER barrier. Therefore, Mn‐Co3O4@CN surpasses RuO2 at high current density (100 mA cm‐2 @ ~538 mV).    

    

* Enhanced catalytic activity of ZnWO4 by nickel-doping in oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391197664
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Perovskite Solar Cell Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mssp.2024.108151")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391197664"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391197664"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391197664"))][Get cited by]]

OpenAlex: https://openalex.org/W4391197664 (Open access: False)
    
[[https://openalex.org/A5087592842][Meng Li]], [[https://openalex.org/A5086054627][Deijun Xiong]], [[https://openalex.org/A5036224962][Jinxing Wang]], [[https://openalex.org/A5082373186][Xiaoyang Dong]], [[https://openalex.org/A5069325690][Peiyang Zhang]], Materials Science in Semiconductor Processing. 173(None)] 2024. https://doi.org/10.1016/j.mssp.2024.108151 
     
The development of efficient and low-cost metal materials is indispensable in clean energy technology. Metal tungstates have previously been reported as catalysts for oxygen evolution reactions (OER). However, ZnWO4 alone does not exhibit significant catalytic activity for OER, it requires 330 mV to drive the reaction at 10 mA cm−2. To address this issue, a self-supporting electrode mixed with tungstate is synthesized by a hydrothermal method. Notably, the Ni-doped ZnWO4 self-supporting material demonstrates improved OER catalytic activity. Specifically, when comparing ZnWO4 to ZnNiWO4, it exhibits a reduced Tafel slope by 190 mV·dec−1, resulting in an overpotential of only 110 mV at 10 mA cm−2, with long-term stability for at least 20 h. Furthermore, the d-band center of ZnNiWO4 is modeled using Materials Studio and simulated through projected density of states (PDOS) calculations. These calculations reveal that the presence of Ni activates the metal ion as an OER active site with strong orbital overlap with the reaction intermediate. This adjustment in the electronic structure of the Ni–Zn metal active site during the oxygen evolution reaction alters the adsorption energy. Consequently, doping of Ni enhances the metal's ability to adsorb *OOH radical, shifting the d-band center of ZnNiWO4 further away from the Fermi level, and facilitates rapid oxygen release.    

    

* Dynamic Promotion of the Oxygen Evolution Reaction via Programmable Metal Oxides  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391172933
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-gs6zn")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391172933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391172933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391172933"))][Get cited by]]

OpenAlex: https://openalex.org/W4391172933 (Open access: True)
    
[[https://openalex.org/A5030610409][Sallye Gathmann]], [[https://openalex.org/A5065773454][Christopher J. Bartel]], [[https://openalex.org/A5029991019][Lars C. Grabow]], [[https://openalex.org/A5089122189][Omar Abdel‐Rahman]], [[https://openalex.org/A5071975512][C. Daniel Frisbie]], [[https://openalex.org/A5003718847][Paul J. Dauenhauer]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-gs6zn  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65af381d66c13817290d5404/original/dynamic-promotion-of-the-oxygen-evolution-reaction-via-programmable-metal-oxides.pdf][pdf]])
     
Hydrogen gas is a promising renewable energy storage medium when produced via water electrolysis, but this process is limited by the sluggish kinetics of the anodic oxygen evolution reaction (OER). Herein, we used a microkinetic model to investigate promoting the OER using programmable oxide catalysts (i.e., forced catalyst dynamics). We found that programmable catalysts could increase current density at a fixed overpotential (100X to 600X over static rates) or reduce the overpotential required to reach a fixed current density of 10 mA/cm^2 (45 – 140% reduction vs. static). In our kinetic parameterization, the key parameters controlling the quality of the catalytic ratchet were the O*-to-OOH* and O*-to-OH* activation barriers. Our findings indicate that programmable catalysts may be a viable strategy for accelerating the OER or enabling lower-overpotential operation, but a more accurate kinetic parameterization is required for precise predictions of performance, ratchet quality, and resulting energy efficiency.    

    

* Role of A-sites in pyrochlore lanthanide ruthenate for electrocatalysis of oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391450654
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jmat.2023.12.009")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391450654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391450654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391450654"))][Get cited by]]

OpenAlex: https://openalex.org/W4391450654 (Open access: True)
    
[[https://openalex.org/A5002424714][Hengyu Guo]], [[https://openalex.org/A5026495381][Zhengping Zhang]], [[https://openalex.org/A5085586043][Feng Wang]], Journal of Materiomics. None(None)] 2024. https://doi.org/10.1016/j.jmat.2023.12.009 
     
Developing highly stable and efficient catalysts for oxygen evolution reaction (OER) is extremely important to sustainable energy conversion and storage, but improved efficiency is largely hindered by sluggish reaction kinetics. Dense and bimetal ruthenates have emerged as one of the promising substitutes to replace single-metal ruthenium or iridium oxides, but the fundamental understanding the role of A-site cations is still blurring. Herein, a family of lanthanides (Ln = all the lanthanides except Pm) are applied to synthesize pyrochlore lanthanide ruthenates (Ln2Ru2O7), and only Ln2Ru2O7 (Ln = Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb, or Lu) with pure phase can be obtained by the ambient-pressure calcination. Compared with the perovskite ruthenates (SrRuO3) and rutile RuO2, the [RuO6] units in these Ln2Ru2O7 present the largely distorted configurations and different energy level splitting to prevent the excessive Ru oxidation and dissolution, which leads the primary improvement in the electrocatalytic OER performance. In the similar crystalline field split states, the charge transfer between [RuO6] units and Ln3+ cations also affect catalytic activities, even in the Ln2Ru2O7 surface reconstruction during the OER process. Consequently, Tb2Ru2O7 showed the highest OER performance among all the prepared Ln2Ru2O7 with similar morphologies and crystallization. This systematic work gives fundamental cognition to rational design of high-performance OER electrocatalysts in proper water electrolysis technologies.    

    

* Fabrication of hexagonal Cu2O nanocrystals on CNTs for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391179968
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Formation and Properties of Nanocrystals and Nanostructures
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpcs.2023.111853")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391179968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391179968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391179968"))][Get cited by]]

OpenAlex: https://openalex.org/W4391179968 (Open access: False)
    
[[https://openalex.org/A5083753418][Salma Aman]], [[https://openalex.org/A5018207831][Meznah M. Alanazi]], [[https://openalex.org/A5008098859][Shaimaa A. M. Abdelmohsen]], [[https://openalex.org/A5088716481][Saeed D. Alahmari]], [[https://openalex.org/A5078102681][Abdullah G. Al‐Sehemi]], [[https://openalex.org/A5014861084][Muhammad Suleman Waheed]], [[https://openalex.org/A5051797797][A.M.A. Henaish]], [[https://openalex.org/A5084172156][Zubair Ahmad]], [[https://openalex.org/A5001974005][Hafiz Muhammad Tahir Farid]], Journal of Physics and Chemistry of Solids. None(None)] 2024. https://doi.org/10.1016/j.jpcs.2023.111853 
     
Electrocatalytic water (H2O) splitting relies heavily on the rational formation of most effective, long-lasting catalysts that should be cheaper and earth abundant. Therefore, an effective electrocatalyst is the need of the hour that may effectively pursue both electrocatalytic OER and HER. This study paves the way for the straightforward preparation of conductive polymer tailored metal oxide nanocomposite Cu2O/CNTs by a facile hydrothermal approach to be employed as overall water splitting electrocatalyst. The techniques comprising SEM, XRD, EDX and the BET test were employed to characterize the synthesized Cu2O/CNTs electrocatalyst. The generated Cu2O/CNTs electrocatalysts exhibited a Tafel value of 39 mV/dec, an overpotential of 267 mV@10 mA/cm2, and stability of OER activity that lasted for at least 70 hours. The electrocatalytic results show that the combination of Cu2O and CNTs has a synergistic impact to reduce the overpotential value. In an effort to pinpoint the rate determining processes for OER, the voltage of OER is connected to the electrolyte pH and exhibits a non-proton concerted approach. The above designed nanocomposite is quite promising for modern hydrogen production systems due to their quick electron transfer mechanism, remarkable durability, and good activity for OER.    

    

* Strategic Design and Insights into Lanthanum and Strontium Perovskite Oxides for Oxygen Reduction and Oxygen Evolution Reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391142464
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202308443")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391142464"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391142464"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391142464"))][Get cited by]]

OpenAlex: https://openalex.org/W4391142464 (Open access: False)
    
[[https://openalex.org/A5050236680][Sagar Ingavale]], [[https://openalex.org/A5036345289][Mohan Gopalakrishnan]], [[https://openalex.org/A5092896607][Carolin Mercy Enoch]], [[https://openalex.org/A5067676218][Chanon Pornrungroj]], [[https://openalex.org/A5000448228][Meena Rittiruam]], [[https://openalex.org/A5036226683][Supareak Praserthdam]], [[https://openalex.org/A5007823738][Anongnat Somwangthanaroj]], [[https://openalex.org/A5093770957][Kasadit Nootong]], [[https://openalex.org/A5074004594][Rojana Pornprasertsuk]], [[https://openalex.org/A5081163390][Soorathep Kheawhom]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202308443 
     
Abstract Perovskite oxides exhibit bifunctional activity for both oxygen reduction (ORR) and oxygen evolution reactions (OER), making them prime candidates for energy conversion in applications like fuel cells and metal‐air batteries. Their intrinsic catalytic prowess, combined with low‐cost, abundance, and diversity, positions them as compelling alternatives to noble metal and metal oxides catalysts. This review encapsulates the nuances of perovskite oxide structures and synthesis techniques, providing insight into pivotal active sites that underscore their bifunctional behavior. The focus centers on the breakthroughs surrounding lanthanum (La) and strontium (Sr)‐based perovskite oxides, specifically their roles in zinc‐air batteries (ZABs). An introduction to the mechanisms of ORR and OER is provided. Moreover, the light is shed on strategies and determinants central to optimizing the bifunctional performance of La and Sr‐based perovskite oxides.    

    

* Efficient oxygen evolution using conductive cobalt-based metal-organic framework  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391143814
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology, Conducting Polymer Research
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131044")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391143814"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391143814"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391143814"))][Get cited by]]

OpenAlex: https://openalex.org/W4391143814 (Open access: False)
    
[[https://openalex.org/A5061145215][Munzir H. Suliman]], [[https://openalex.org/A5025288698][Lolwah Tawfiq Alfuhaid]], [[https://openalex.org/A5042532738][Mohd Yusuf Khan]], [[https://openalex.org/A5090138718][Muhammad Usman]], [[https://openalex.org/A5088210851][Aasif Helal]], Fuel. 363(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131044 
     
The electrically conductive Cobalt-benzene-1,3,5-tribenzoate metal–organic framework (Co-BTB) was easily synthesized using the hydrothermal synthesis process. The framework showed a low overpotential (only 170 mV to obtain 10 mA cm−2) for the oxygen evolution reaction (OER) surpassing the benchmark electrocatalyst IrO2 which showed an overpotential of 250 mV at the same obtained current density. Moreover, the Co-BTB possesses good kinetics with an estimated Tafel slope of only 46.5 mV dec−1. It provided a high density of catalytic centers with electrically conductive characteristics, as suggested by ECSA. The framework was identified as a promising MOF electrocatalyst for the OER due to its performance as well as its chemical and electrochemical robustness.    

    

* NiCo2O4/MXene hybrid as an efficient bifunctional electrocatalyst for oxygen evolution and reduction reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391296391
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301250")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391296391"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391296391"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391296391"))][Get cited by]]

OpenAlex: https://openalex.org/W4391296391 (Open access: False)
    
[[https://openalex.org/A5016038695][Ashalatha Vazhayil]], [[https://openalex.org/A5015987837][Vazhayal Linsha]], [[https://openalex.org/A5086819981][Shyamli Ashok C]], [[https://openalex.org/A5087024992][Jasmine Thomas]], [[https://openalex.org/A5053127989][Nygil Thomas]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301250 
     
For the advancement of energy conversion and storage technologies, bifunctional electrocatalysts are crucial for efficiently driving both the oxygen evolution (OER) and reduction reactions (ORR). Cobalt‐based spinel oxides are a class of promising bifunctional electrocatalysts. However their low electrical conductivity and stability may hinder further improvement. A novel composite material composed of NiCo2O4(NCO) nanoparticles integrated with emerging two dimensional MXene nanosheets (NCO/MXene) was developed. The successful integration of NCO with MXene brings about a number of attractive structural features. This includes synergistic effects between NCO and MXene, highly accessible surface areas, complete exposure of numerous active sites, and excellent electronic conductivity, all of which collectively contribute to the desirability of composite material for OER and ORR. The synthesized NCO/MXene composite showed extraordinary OER electrocatalytic activity with a lower overpotential of 360 mV at a current density of 10 mA/cm2, and a small Tafel slope of 64.63 mV/dec compared to NCO, MXene and NCO+MXene (physically mixed). Additionally, it displays a superior ORR limiting current density (‐4 mA/cm2). In particular, it exhibited highest onset potential and half wave potential of 0.92 V and 0.72 V vs. RHE, respectively, for the ORR in alkaline media    

    

* Tailoring Metal-Ion-Doped Carbon Nitrides for Photocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391486029
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391486029"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391486029"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391486029"))][Get cited by]]

OpenAlex: https://openalex.org/W4391486029 (Open access: False)
    
[[https://openalex.org/A5006958502][Shanping Liu]], [[https://openalex.org/A5080802270][Valentin Diez‐Cabanes]], [[https://openalex.org/A5069062661][Dong Fan]], [[https://openalex.org/A5080107062][Peixiang Lu]], [[https://openalex.org/A5027738164][Yuanxing Fang]], [[https://openalex.org/A5075963769][Markus Antonietti]], [[https://openalex.org/A5087859676][Guillaume Maurin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05961 
     
Poly(heptazine imides) (PHIs) have emerged as prominent layered carbon nitride-based materials with potential oxygen evolution reaction (OER) catalytic activity owing to their strong VIS light absorption, long excited-state lifetimes, high surface-to-volume ratios, and the possibility of tuning their properties via hosting different metal ions in their pores. A series of metal-ion-doped PHI-M (M = K+, Rb+, Mg2+, Zn2+, Mn2+, and Co2+) were first systematically explored using density functional theory calculations. These simulations led an in-depth understanding of the microscopic OER mechanism in these systems and identified PHI-Co2+ as the best OER catalyst of this family of PHIs, whereas PHI-Mn2+ can be an alternative promising OER catalyst. This level of performance was attributed to a thermodynamically favorable formation of the reaction intermediates as well as its red-shifted absorption in the VIS region involving the population of long-lived states, as revealed by time-dependent density functional theory calculations. We further demonstrated that the electronic properties of the *OH intermediates (Bader population, crystal orbital Hamilton population analysis, and adsorption energies) are reliable descriptors to anticipate the OER activity of this family of PHIs. This rational analysis paved the way toward the prediction of the OER performance of another PHI-M derivative, i.e., PHI-Fe2+. The computationally explored PHI-Fe2+, PHI-Mn2+, and PHI-Co2+ systems were then synthesized alongside PHI-K+, and their photocatalytic OER activities were assessed. These experimental findings confirmed the best photocatalytic OER performance for PHI-Co2+ with an oxygen production of 31.2 μmol·h–1 that is 60 times higher than the pristine g-C3N4 (0.5 μmol·h–1), whereas PHI-Fe2+ and PHI-Mn2+ are seen as alternative OER catalysts with attractive oxygen production of 11.20 and 4.69 μmol·h–1, respectively. Decisively, this joint experimental–computational study reveals PHI-Co2+ to be among the best of the OER catalysts so far reported in the literature including some perovskites.    

    

* Spinel-type high-entropy oxide nanotubes for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391177777
:TOPICS: Electrocatalysis for Energy Conversion, Emergent Phenomena at Oxide Interfaces, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.colsurfa.2024.133315")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391177777"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391177777"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391177777"))][Get cited by]]

OpenAlex: https://openalex.org/W4391177777 (Open access: False)
    
[[https://openalex.org/A5046042839][Yanbin Zhu]], [[https://openalex.org/A5070686219][Qing Xiang]], [[https://openalex.org/A5050156870][Guo Le]], [[https://openalex.org/A5060213367][Shuanglong Lu]], [[https://openalex.org/A5067758457][Fang Duan]], [[https://openalex.org/A5036927789][Mingliang Du]], [[https://openalex.org/A5014327956][Han Zhu]], Colloids and Surfaces A: Physicochemical and Engineering Aspects. None(None)] 2024. https://doi.org/10.1016/j.colsurfa.2024.133315 
     
Oxygen evolution reaction (OER) involved 4-electron transfers is generally considered as the bottleneck for electrocatalytic water splitting. High-entropy oxides (HEO) show promising potential for OER due to their flexible structures and tunable compositions. Herein, we report a facile strategy to synthesize spinel-type (FeCoNiMnCr)3O4 HEO nanotubes (NTs) with unique hollow structures by combining electrospinning process and calcination treatment. The (FeCoNiMnCr)3O4 HEO NTs prepared at 400 °C exhibit the low overpotential of 353 mV at 50 mA cm-2 and small Tafel slope of 55.6 mV dec-1 in 1 M KOH electrolyte. The three-dimensional (3D) nanofiber-based architecture ensure the superior stability, as evidenced by the stable current density under continuous OER process for more than 60 h. Meanwhile, the hollow structure provides abundant exposed active sites, which could significantly improve the OER activity. This work provides new design of low-cost and high-efficient HEO with ensemble active sites for OER.    

    

* Carbon nanotubes immobilized copper(salen) nanocomposite for electrochemical oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391174987
:TOPICS: Electrocatalysis for Energy Conversion, Conducting Polymer Research, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.56042/ijc.v63i1.2312")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391174987"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391174987"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391174987"))][Get cited by]]

OpenAlex: https://openalex.org/W4391174987 (Open access: True)
    
, Indian Journal of Chemistry. 63(1)] 2024. https://doi.org/10.56042/ijc.v63i1.2312  ([[https://or.niscpr.res.in/index.php/IJC/article/download/2312/2438][pdf]])
     
An efficient oxygen evolution reaction (OER) electrocatalysts are widely required in the realm of water electrolysis and rechargeable metal-air batteries. This work describes an easy and simple method for the synthesis of copper salen (Cu(Salen))-functionalized multiwalled carbon nanotubes (MWCNTs) nanocomposite materials (Cu(Salen)/MWCNTs). It was used for OER in the basic medium (0.1 M KOH). The resulting nanocomposite, Cu(Salen)/MWCNTs, was studied using spectroscopic and microscopic techniques. For example, Fourier transform infrared (FT-IR), UV-visible spectroscopy, powder X-ray diffraction (p-XRD), scanning electron microscopy (SEM), and energy dispersive X-ray analysis (EDAX). The electrochemical characterization of prepared Cu(Salen)/MWCNTs nanocomposite based modified glassy carbon (GC) electrodes (GC/Cu(Salen)/MWCNTs) and their application towards OER were performed using an electrochemical method. The Tafel slope of nanocomposite material is 159.6 mv/dec in 0.1 M KOH solution, indicating that GC/Cu(Salen)/MWCNTs could be a promising and cost-effective electrode material for the OER. This study demonstrates a novel way for creating an active nanocomposite catalyst for OER in alkaline media.    

    

* Machine Learning-Based Optimization Method for the Oxygen Evolution and Reduction Reaction of the High-Entropy Alloy Catalysts  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391330920
:TOPICS: High-Entropy Alloys: Novel Designs and Properties, Atom Probe Tomography Research, Thermal Barrier Coatings for Gas Turbines
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.17762/ijritcc.v11i9.9214")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391330920"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391330920"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391330920"))][Get cited by]]

OpenAlex: https://openalex.org/W4391330920 (Open access: True)
    
[[https://openalex.org/A5093816237][Et al. Jagannath Jijaba Kadam]], International Journal on Recent and Innovation Trends in Computing and Communication. 11(9)] 2023. https://doi.org/10.17762/ijritcc.v11i9.9214 
     
In recent times, high-entropy alloys (HEAs) have found application in heterogeneous catalysis, capitalizing on their vast chemical potential. Yet, this extensive chemical landscape presents significant challenges when attempting a comprehensive exploration of HEAs through traditional trial-and-error approaches. Therefore, the machine learning (ML) approach is offered to appearance into the catalytic activity (CA) of countless sensitive sites on HEA surfaces in the oxygen-lessening response (ORR) and oxygen evolution reactions (OER). In this research, a Density Functional Theory (DFT) with a supervised ML model is assembled and founded on the gradient boosting regression (GBR) algorithm that predicted the O2 adsorption energies with a high overpotential of all surface sites on the two HEAs. Initially, the HEAs Co-Fe-Ga-Ni-Zn and Al-Cu-Pd-Pt offer a framework for adjusting the composition of disordered multi-metallic alloys to regulate the activity and selectivity of the reduction of oxygen to extremely reduced compounds. This attains generalizability, high accuracy and simplicity with the proposed technique. For fine-tuning such features, HEAs provide a huge compositional space. Consequently, the research reports the custom of the Bayesian optimization model based on HEA active compositions to suppress the formation of Oxygen (O2) and with strong O2 adsorption to favour the lessening of O2. The GBR approach is applied to build a highly accurate, easily generalizable, and effective ML model. The proposed work is analysed using Python software. The findings show that the separate charities of correlated metal atoms close to the responsive site are mixed to form the adsorption energy, which is clear from a thorough analysis of the data. It is suggested that a highly effective HEA catalyst composed of Co-Fe-Ga-Ni-Zn and Al-Cu-Pd-Pt be exploited, which is an effective method for further enhancing the ORR CA of potential HEA catalysts. An instruction manual for the logical design and synthesis of HEA catalysts' nanostructures is provided by the proposed research.    

    

* Novel Amorphous Feooh-Modified Co9s8 Nanosheets with Enhanced Oxygen Evolution Reaction Activity  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391405828
:TOPICS: Catalytic Reduction of Nitro Compounds, Formation and Properties of Nanocrystals and Nanostructures, Materials for Electrochemical Supercapacitors
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4711575")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391405828"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391405828"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391405828"))][Get cited by]]

OpenAlex: https://openalex.org/W4391405828 (Open access: False)
    
[[https://openalex.org/A5007803202][Chong Wang]], [[https://openalex.org/A5036746330][Huanlu Tu]], [[https://openalex.org/A5071814351][Zeyu Hao]], [[https://openalex.org/A5037742951][Yaxin Li]], [[https://openalex.org/A5038906848][Jing Xu]], [[https://openalex.org/A5016312685][Xiaoying Hu]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5037428389][Hongwei Tian]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4711575 
     
Efficient oxygen evolution reaction (OER) is important for water electrolysis and advanced hydrogen production energy. However, the sluggish kinetics of this reaction require significant overpotentials, leading to high energy consumption. Therefore, developing OER electrocatalysts with exceptional performance and long-term durability is crucial for enhancing the energy efficiency and cost-effectiveness of the hydrogen production process. In this paper, novel FeOOH/Co9S8 catalysts were prepared through a two-step hydrothermal reaction followed by one-step electrodeposition on nickel foam substrates for an alkaline oxygen evolution reaction (OER). The as-obtained catalysts possessed abundant non-homogeneous interfaces between FeOOH and Co9S8 nanosheets, conducive to optimized coordination environments of Fe and Co sites through the redistribution of interfacial charges. This strengthened the chemisorption of oxygenated intermediates, leading to accelerated reaction kinetics, abundant active sites, and enhanced OER properties. The optimized electrocatalyst FeOOH/Co9S8 achieved a current density of 10 mA cm-2 at an overpotential of 248 mV coupled with good stability for over 140 h. Overall, a novel approach for producing effective and durable alkaline dielectric OER electrocatalysts was proposed, useful for future manufacturing of advanced energy devices.    

    

* Medium-Entropy Co–Fe–Cr–Mo Spinel Nanoflowers as Electrocatalysts for Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391464648
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.3c05568")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391464648"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391464648"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391464648"))][Get cited by]]

OpenAlex: https://openalex.org/W4391464648 (Open access: False)
    
[[https://openalex.org/A5007542563][Yuhang Sun]], [[https://openalex.org/A5006901660][Tianmi Tang]], [[https://openalex.org/A5072475535][Liyuan Xiao]], [[https://openalex.org/A5053838411][Jingyi Han]], [[https://openalex.org/A5086755732][Xue Bai]], [[https://openalex.org/A5033773174][Mingyuan Shi]], [[https://openalex.org/A5086922328][Siyu Chen]], [[https://openalex.org/A5007095017][Jingru Sun]], [[https://openalex.org/A5060962227][Yuanyuan Ma]], [[https://openalex.org/A5074571254][Jingqi Guan]], ACS Applied Nano Materials. None(None)] 2024. https://doi.org/10.1021/acsanm.3c05568 
     
Oxygen evolution reaction (OER) plays an important role in many electrocatalysis-related fields. However, the slow kinetics of the OER seriously hinders energy efficiency. Here, we synthesize flower-like Co–Fe–Cr–Mo medium-entropy spinel (MES) nanosheets on nickel foam (NF) using one-step solvothermal method for the OER. Due to high stability and compositional diversity, the CoFeCrMoOx/NF catalyst exhibits excellent electrocatalytic OER performance with an overpotential of only 196 mV at 10 mA cm–2 in 1.0 M KOH solution, much lower than CoFeCrMnOx/NF, CoFeCrCeOx/NF, CoFeCrSnOx/NF, CoFeCrAlOx/NF, and commercial IrO2 catalysts, reflecting that the formation of flower-like MES has a positive effect on the improvement of OER performance. The introduction of Mo increases active sites, promotes electron transfer, accelerates the adsorption and desorption of the OER intermediates, reduces the energy barrier, and thus improves the performance of the OER. In situ Raman spectra indicate that the surface CoOOH and FeOOH species are important active components for the OER.    

    

* Tungsten-doped cobalt-iron bimetallic phosphide nanoparticles for enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391057421
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jtice.2024.105356")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057421"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057421"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057421"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057421 (Open access: False)
    
[[https://openalex.org/A5029733101][Yaoxia Yang]], [[https://openalex.org/A5076729121][Dangxia Wang]], [[https://openalex.org/A5078314562][Xingwei Guo]], [[https://openalex.org/A5072659920][Fengyao Guo]], [[https://openalex.org/A5067107304][Zhang Lan]], [[https://openalex.org/A5032918016][Dongfei Sun]], [[https://openalex.org/A5081104591][Xiaozhong Zhou]], [[https://openalex.org/A5031098226][Zhiwang Yang]], [[https://openalex.org/A5026631111][Ziqiang Lei]], Journal of the Taiwan Institute of Chemical Engineers. 156(None)] 2024. https://doi.org/10.1016/j.jtice.2024.105356 
     
Hydrogen obtained from electrochemical water splitting is an efficient method for hydrogen production, which is urgent to develop high efficiency electrocatalyst and commercialize the process. In our work, we used coprecipitation, doping and phosphating strategies to report the trimetallic Prussian blue analogue precursors (W-CoFe PBA) were prepared by doping sodium tungstate into cobalt-iron-Prussian blue analogues (CoFe PBA), and then by a low temperature phosphating treatment to obtain tungsten doped cobalt-iron phosphide (W-CoP/FeP) heterostructures. This strategy of doping and then phosphating can allow the charge distribution is adjusted, the conductivity is increased, the electron transport to the surface is accelerated, and the synergistic effect between CoP and FeP is enhanced. The experimental results show that the mass ratio of tungsten source to CoFe-PBA is 0.5 (0.5W-CoP/FeP), which shows outstanding activity with overpotentials of 282 mV for the oxygen evolution reaction (OER) in 1 M KOH at a current density of 10 mA cm−2 and Tafel slope of 29.14 mV dec−1. Simultaneously, it also exhibits excellent stability for 24 h in the chronopotentiometry test. This work provides a simple improvement for the application of Prussian blue analogues in the electrochemical water splitting.    

    

* Mixed-valent cobalt phosphate/borophene nanohybrids for efficient electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391319509
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.188")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391319509"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391319509"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391319509"))][Get cited by]]

OpenAlex: https://openalex.org/W4391319509 (Open access: False)
    
[[https://openalex.org/A5016235312][Bitan Pratihar]], [[https://openalex.org/A5048541923][Omkar Roy]], [[https://openalex.org/A5080383377][Arijit Jana]], [[https://openalex.org/A5021909284][Sirshendu De]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.188 
     
Developing efficient, low-cost, non-precious and stable electrocatalyst is necessary for sustainable electrocatalytic water splitting. Recently, borophene has emerged as a novel two-dimensional material with exciting properties. Although several researchers have theoretically predicted its applicability towards effective electrocatalytic water splitting, studies on its practical applications are still limited. In this regard, a mixed-valent cobalt phosphate/borophene nanohybrid (BCoPi) was synthesized using hydrothermal method, and its activity towards oxygen evolution reaction (OER) was systematically studied. The electron-deficient nature of borophene enables activation of catalytic sites and facilitates electron transport owing to its highly conductive nature. It can act as a proton acceptor along with phosphate groups, as well as provide multiple secondary active sites in addition to Co, breaking the scaling relation of OER. For BCoPi, achieving a current density of 50 mA cm−2, 100 mA cm−2 and 500 mA cm−2 requires an overpotential of 337 mV, 357 mV and 401 mV, respectively, in an alkaline medium, that are superior to pristine cobalt phosphate (CoPi). It also exhibits low Tafel slope of 61.81 mV dec−1, suggesting faster OER kinetics and excellent long-term stability. This study will extend the development and application of borophene-based heterostructures for highly active and stable electrocatalysts for various applications.    

    

* Mesoporous hydrogel electrodes with flexible framework exhibiting enhanced mass transport for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391509597
:TOPICS: Conducting Polymer Research, Fuel Cell Membrane Technology, Electrochemical Biosensor Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cc04632j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391509597"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391509597"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391509597"))][Get cited by]]

OpenAlex: https://openalex.org/W4391509597 (Open access: False)
    
[[https://openalex.org/A5078670038][Ritsuki Nakajima]], [[https://openalex.org/A5093855209][Hiroki Wago]], [[https://openalex.org/A5067573679][Tatsuya Taniguchi]], [[https://openalex.org/A5061217758][Yuta Sasaki]], [[https://openalex.org/A5065223963][Yoshinori Nishiki]], [[https://openalex.org/A5054248011][Zaenal Awaludin]], [[https://openalex.org/A5031262649][Takaaki Nakai]], [[https://openalex.org/A5005243857][Akihisa Kato]], [[https://openalex.org/A5093855210][Mitsushima Mitsushima]], [[https://openalex.org/A5090206527][Yoshiyuki Kuroda]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d3cc04632j 
     
Mesoporous hydrogel electrodes with unique flexible mesopores surrounded by CoOOH nanosheets were prepared via the electrochemical deposition of hybrid cobalt hydroxide nanosheets, exhibiting high oxygen evolution reaction activity at a...    

    

* Co atom-doped NiMoO4 Hierarchical hollow nanosheet-based-nanosphere for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391343114
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.22541/au.170664116.61933326/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391343114"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391343114"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391343114"))][Get cited by]]

OpenAlex: https://openalex.org/W4391343114 (Open access: False)
    
[[https://openalex.org/A5012770110][Zhuoxun Yin]], [[https://openalex.org/A5045073916][Min Zhou]], [[https://openalex.org/A5018077554][Xinping Li]], [[https://openalex.org/A5057117758][Xiangcun Liu]], [[https://openalex.org/A5070267350][Xinzhi Ma]], [[https://openalex.org/A5020624661][Yang Zhou]], [[https://openalex.org/A5017541508][Wei Chen]], [[https://openalex.org/A5086155499][Jinlong Li]], Authorea (Authorea). None(None)] 2024. https://doi.org/10.22541/au.170664116.61933326/v1 
     
Hollow structures with hierarchical architecture and multi-composition have attracted extensive interest because of their fascinating physicochemical properties as well as wide applications. to improve the efficiency of overall water splitting, highly active and stable electrocatalysts are highly desirable. A novel high-efficiency Hierarchical hollow nanosheet-based-nanosphere Co-NiMoO4-HNS electrocatalyst for oxygen evolution was arranged by doping Co on Ni-MoEG yolk/shelll nanosphere. Remarkably, the hierarchical hollow Co2-NiMoO4-HNS catalyst exhibits favorable catalytic performance toward the oxygen evolution reaction (OER) with a receivable overpotential of 270 mV achieving a current density of 10 mA cm−2 and a Tafel slope of 65 mV dec−1. In expansion, as a electrocatalyst, Co2-NiMo4-HNS appeared to have great long-term steadiness in the electrolyte. This work may give broad hypothetical and specialized back for the plan of cost-effective bifunctional electrocatalysts.    

    

* Exploring the role of iron in Fe5Ni4S8 toward oxygen evolution through modulation of electronic orbital occupancy  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391152145
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Catalytic Nanomaterials
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.01.028")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391152145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391152145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391152145"))][Get cited by]]

OpenAlex: https://openalex.org/W4391152145 (Open access: False)
    
[[https://openalex.org/A5070671117][Zhengyan Du]], [[https://openalex.org/A5069619264][Zeshuo Meng]], [[https://openalex.org/A5035280619][H. Sun]], [[https://openalex.org/A5085794085][Yifan Li]], [[https://openalex.org/A5018421780][Chao Jiang]], [[https://openalex.org/A5037742951][Yaxin Li]], [[https://openalex.org/A5016312685][Xiaoying Hu]], [[https://openalex.org/A5063995082][Yi Cui]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5037428389][Hongwei Tian]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.01.028 
     
Ni-Fe-based catalysts are considered to be among the most active catalysts for the oxygen evolution reaction (OER) under alkaline conditions, with Fe playing a crucial role. However, Fe leaching occurs during the reaction due to thermodynamic instability, which has resulted in conflicting reports within the literature regarding its role. To clarify this point, we propose a strategy consisting of modulating the electronic orbital occupancy to suppress the extensive loss of Fe atoms during the OER process. Theoretical calculations, in-situ X-ray photoelectron spectroscopy, molecular dynamics simulations, and a series of characterization showed that the stable presence of Fe not only accelerates the electron transfer process but also optimizes the reaction barriers of the oxygen evolution intermediates, promoting the phase transition of Fe5Ni4S8 to highly active catalytic species. The modulated Fe5Ni4S8-based pre-catalysts exhibit improved OER activity and long-term durability. This study provides a novel perspective for understanding the role of Fe in the OER process.    

    

* A rational strategy for CoFe layered double hydroxide oxygen evolution catalysts with high activity and stability  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391311547
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.colsurfa.2024.133360")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391311547"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391311547"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391311547"))][Get cited by]]

OpenAlex: https://openalex.org/W4391311547 (Open access: False)
    
[[https://openalex.org/A5081751519][Linfeng Yang]], [[https://openalex.org/A5007024868][Shuang Yu]], [[https://openalex.org/A5040998948][Feng Luo]], [[https://openalex.org/A5052053894][Yang Liu]], [[https://openalex.org/A5017761703][Xiaoqiang Wu]], [[https://openalex.org/A5000124572][Xiao‐Nan Liu]], Colloids and Surfaces A: Physicochemical and Engineering Aspects. None(None)] 2024. https://doi.org/10.1016/j.colsurfa.2024.133360 
     
Oxygen evolution reaction (OER) catalyzed by non-precious metals and their compounds in alkaline environments are regarded as a key research topic for the use of water for hydrogen production to alleviate the global energy crisis. Cobalt-iron layered double hydroxide (CoFe-LDH) has attracted much attention as a potential high-performance oxygen evolution reaction catalyst. In this paper, we report a strategy to introduce metal elements M (M = Cu, K, Al, Cr and Zn) into CoFe-LDH to further enhance the OER performance. The experimental results show that CoFeK-15 exhibits the lowest overpotential (203 mV to reach 10 mA cm-2) and Tafel slope (77.1 mV dec-1) and maintains excellent catalytic activity after 50 h i-t test. Through the introduction of potassium ions, the electronic structure inside the catalyst underwent lattice distortion, resulting in a larger active surface area and exposure of more oxygen vacancies, which in turn accelerated the OER reaction. This study reveals the important influence of potassium doping on the electronic structure modification strategy to enhance the performance of OER and provides new ideas for the development of more efficient catalysts in the future.    

    
