#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Sat Jan 20 00:40:56 2024

Found 48 results from 2024-01-06 to 2024-01-20
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]
** PdOs bimetallene for energy-saving hydrogen production coupled with ethanol electro-oxidation   
:PROPERTIES:
:ID: https://openalex.org/W4390630246
:DOI: https://doi.org/10.1016/j.mtener.2024.101493
:AUTHORS: Ziqiang Wang, Min Li, Shan Xu, Heng-Qing Ye, Kai Deng, You Xu, Hongjing Wang, Liang Wang
:HOST: Materials Today Energy
:END:

Ziqiang Wang, Min Li, Shan Xu, Heng-Qing Ye, Kai Deng, You Xu, Hongjing Wang, Liang Wang, Materials Today Energy. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mtener.2024.101493")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390630246"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390630246"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390630246"))][Get cited by]]

OpenAlex: https://openalex.org/W4390630246
    
Ziqiang Wang, Min Li, Shan Xu, Heng-Qing Ye, Kai Deng, You Xu, Hongjing Wang, Liang Wang, Materials Today Energy. https://doi.org/10.1016/j.mtener.2024.101493
    
The replacement of sluggish oxygen evolution reaction by more thermodynamically favorable ethanol oxidation reaction (EOR) is a promising strategy for co-production of hydrogen and valuable chemicals in energy-saving mode. Here, we propose the synthesis of highly curved PdOs bimetallene, which possesses high active sites atomic utilization and conductivity. Furthermore, alloy effect can regulate electronic structure and optimize adsorption energy of reactants. Therefore, PdOs bimetallene exhibits superior performance for hydrogen evolution reaction (HER) and EOR under basic solutions, with overpotential of 36 mV at 10 mA cm-2 and mass activity of 1.51 mA μg-1Pd, respectively. In the EOR-HER co-electrolysis system, PdOs bimetallene requires low voltage of 0.801 V for concurrent production of hydrogen and acetate at 50 mA cm−2, which greatly reduces energy consumption compared to conventional water electrolysis (1.976 V). This method provides a promising strategy for designing bimetallic electrocatalysts towards simultaneous energy-saving generation of hydrogen and high-value chemicals by replacing sluggish OER with more favorable ethanol oxidation reaction.    

    

** Reinforced electrochemical energy storage through controlled construction of hierarchical hollow β-Ni(OH)2 microspheres enriched with oxygen vacancies induced by functionalized MWCNTs   
:PROPERTIES:
:ID: https://openalex.org/W4390636146
:DOI: https://doi.org/10.1016/j.apsusc.2024.159331
:AUTHORS: Zhi-Jia Sun, J. Chen, Xiao‐Man Cao, Hao Ge, Daliang Liu, Qiong Wu, Xi–Ming Song
:HOST: Applied Surface Science
:END:

Zhi-Jia Sun, J. Chen, Xiao‐Man Cao, Hao Ge, Daliang Liu, Qiong Wu, Xi–Ming Song, Applied Surface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159331")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390636146"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390636146"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390636146"))][Get cited by]]

OpenAlex: https://openalex.org/W4390636146
    
Zhi-Jia Sun, J. Chen, Xiao‐Man Cao, Hao Ge, Daliang Liu, Qiong Wu, Xi–Ming Song, Applied Surface Science. https://doi.org/10.1016/j.apsusc.2024.159331
    
As promising electrode materials, hollow-structured metallic oxides/hydroxides have attracted extensive attention for their significantly enhanced catalyst and electrochemical performances. In practice, however, it is still challenging to construct well-dispersed hollow structures using facile and versatile template-free methods. And, as a result of the weak conductivity of most metallic oxides/hydroxides, it is a particularly effective means to integrate metallic oxides/hydroxides with carbon-based conductive substrates or introduce oxygen vacancies for further promoting reaction kinetics and achieving boosted electrochemical performance. Herein, a novel composite material consisting of oxygen-rich vacancy β-Ni(OH)2 coupled with oxidized multi-wall carbon nanotubes (Ov-Nβ/Cm) was synthesized using a one-step hydrothermal technique without the need for templates. The hierarchical hollow microsphere structure was achieved by utilizing oxidized multi-wall carbon nanotubes (MWCNTs) as an alternative to conventional surfactants or templates. The uniform distribution of multistage pores in the newly designed Ov-Nβ/Cm composite facilitates the transportation of electrolyte ions, thereby endowing it with outstanding electrochemical performance. A straightforward technique for producing high-quality Ni(OH)2-based electrode materials is presented in this investigation, along with fresh perspectives on the formation mechanism of hollow-structured composites. Developing MWCNT-based hollow nanostructured composites with oxygen vacancies-enriched will offer an essential novel avenue to exploit excellent electrode materials for supercapacitors and other energy storage systems.    

    

** Spray Pyrolysis Regulated FeCo Alloy Anchoring on Nitrogen–Doped Carbon Hollow Spheres Boost the Performance of Zinc–Air Batteries   
:PROPERTIES:
:ID: https://openalex.org/W4390637300
:DOI: https://doi.org/10.1002/smll.202310318
:AUTHORS: Hong-Rui Huang, Qianqian Liang, Huajun Guo, Zhixing Wang, Guochun Yan, Feixiang Wu, Jiexi Wang
:HOST: Small
:END:

Hong-Rui Huang, Qianqian Liang, Huajun Guo, Zhixing Wang, Guochun Yan, Feixiang Wu, Jiexi Wang, Small. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310318")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390637300"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390637300"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390637300"))][Get cited by]]

OpenAlex: https://openalex.org/W4390637300
    
Hong-Rui Huang, Qianqian Liang, Huajun Guo, Zhixing Wang, Guochun Yan, Feixiang Wu, Jiexi Wang, Small. https://doi.org/10.1002/smll.202310318
    
Abstract Low‐cost and high‐efficiency non‐precious metal‐based oxygen reduction reaction (ORR)/oxygen evolution reaction (OER) bifunctional catalysts are the key to promoting the commercial application of metal–air batteries. Herein, a highly efficient catalyst of Fe 0.18 Co 0.82 alloy anchoring on the nitrogen‐doped porous carbon hollow sphere (Fe x Co 1‐x /N‐C) is intelligently designed by spray pyrolysis (SP). The zinc in the SP‐derived metal oxides and metal‐organic framework volatilize at high temperature to construct a hierarchical porous structure with abundant defects and fully exposes the FeCo nanoparticles which uniformly anchor on the carbon substrate. In this structure, the coexistence of Fe 0.18 Co 0.82 alloy and binary metal active sites (Fe‐N x /Co‐N x ) guarantees the Fe 0.2 Co 0.8 /N‐C catalyst exhibiting an excellent half‐wave potential ( E 1/2 ═ 0.84 V) superior to 20% Pt/C for ORR and a suppressed overpotential (280 mV) than RuO 2 for OER. Assembled rechargeable Zn–air battery (RZAB) demonstrates a promising specific capacity of 807.02 mAh g −1 , peak power density of 159.08 mW cm −2 and durability without electrolyte circulation (550 h). This work proposes the design concept of utilizing an oxide core to in situ consume the porous carbon shell for anchoring metal active sites and construct defects, which benefits from spray pyrolysis in achieving precise control of the alloy structure and mass preparation.    

    

** Electrochemical properties and kinetic studies of sulphur-induced oxygen vacancies in hydrothermally synthesized manganese molybdenum oxide   
:PROPERTIES:
:ID: https://openalex.org/W4390650057
:DOI: https://doi.org/10.1016/j.matlet.2024.135892
:AUTHORS: Arumugam Sudalai, K. Vinoth Kumar, A. Aseema Banu, Sujin P. Jose
:HOST: Materials Letters
:END:

Arumugam Sudalai, K. Vinoth Kumar, A. Aseema Banu, Sujin P. Jose, Materials Letters. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.135892")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390650057"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390650057"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390650057"))][Get cited by]]

OpenAlex: https://openalex.org/W4390650057
    
Arumugam Sudalai, K. Vinoth Kumar, A. Aseema Banu, Sujin P. Jose, Materials Letters. https://doi.org/10.1016/j.matlet.2024.135892
    
Manganese molybdenum oxide (MnMoO4) has recently garnered significant attention as a promising electrode material for advanced energy storage systems. It is found that the incorporation of oxygen vacancies due to the sulphur doping in MnMoO4 led to a larger interlayer spacing, facilitated charge storage kinetics, and maintained structural durability throughout the electrochemical processes. Hence, this work is focused on the hydrothermal synthesis of MnMoO4 with the sulphur-induced oxygen vacancies (S-MnMoO4) by secondary thermal heating processes. Structural and morphological characterizations confirmed the successful inclusion of oxygen vacancies in MnMoO4. Further drop casting S-MnMoO4 on nickel foam revealed significant improvements in electrochemical performance. It showed a specific capacitance of about 1131F g−1 at 1 A/g, which is six-fold that of pristine MnMoO4. S-MnMoO4 demonstrated excellent cyclic stability with 90% of capacitive retention across 5000 cycles and a coulombic efficiency of 98%. These results highlight the potential of S-MnMoO4 as an efficient electrode material for advanced energy storage applications.    

    

** Fe(OH)x modified ultra-small Ru nanoparticles for highly efficient hydrogen evolution reaction and its application in water splitting   
:PROPERTIES:
:ID: https://openalex.org/W4390650504
:DOI: https://doi.org/10.1016/j.jcis.2024.01.018
:AUTHORS: Yufan Mo, Dongdong Du, Yiyun Du, Yongjun Feng, Pinggui Tang, Dianqing Li
:HOST: Journal of Colloid and Interface Science
:END:

Yufan Mo, Dongdong Du, Yiyun Du, Yongjun Feng, Pinggui Tang, Dianqing Li, Journal of Colloid and Interface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.018")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390650504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390650504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390650504"))][Get cited by]]

OpenAlex: https://openalex.org/W4390650504
    
Yufan Mo, Dongdong Du, Yiyun Du, Yongjun Feng, Pinggui Tang, Dianqing Li, Journal of Colloid and Interface Science. https://doi.org/10.1016/j.jcis.2024.01.018
    
Developing highly active electrocatalysts for overall water splitting is of remarkable significance for industrial production of H2. Herein, exceptionally active Fe(OH)x modified ultra-small Ru nanoparticles on Ni(OH)2 nanosheets array (Fe(OH)x-Ru/Ni(OH)2) for both hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) are reported. The Fe(OH)x-Ru/Ni(OH)2 nanosheets array prepared with Fe/Ru molar ratio of 5 only requires extremely low overpotentials of 61, 127 and 170 mV to reach current densities of 100, 500 and 800 mA cm−2 in 1 M KOH, respectively, exceeding Pt/C catalyst (75, 160 and 177 mV). Meanwhile, the Fe(OH)x/Ni(OH)2 nanosheets array derived from Fe(OH)x-Ru/Ni(OH)2 exhibits excellent OER activity. It gains current densities of 100, 500 and 800 mA cm−2 at considerably low overpotentials of 265, 285 and 296 mV, respectively, much lower than those of RuO2 and most reported electrocatalysts. The introduction of Fe(OH)x significantly improves the HER activity of Ru nanoparticles by tunning the electronic structure and forming interfaces between Ru and Fe(OH)x. Dramatically, the integrated alkaline electrolyzer based on Fe(OH)x-Ru/Ni(OH)2 and Fe(OH)x/Ni(OH)2 nanosheets array pair just needs 1.649 V to yield a current density up to 500 mA cm−2, exceeding most reported water-splitting electrocatalysts. The strategy reported in this work can be facilely extended to prepare other similar Ru based materials and their derivatives with outstanding catalytic performance for water splitting.    

    

** Unbiased Photoelectrochemical Carbon Dioxide Reduction Shaping the Future of Solar Fuels   
:PROPERTIES:
:ID: https://openalex.org/W4390650933
:DOI: https://doi.org/10.1016/j.apcatb.2024.123707
:AUTHORS: Haijiao Lu, Luyao Wang
:HOST: Applied Catalysis B: Environmental
:END:

Haijiao Lu, Luyao Wang, Applied Catalysis B: Environmental. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.123707")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390650933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390650933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390650933"))][Get cited by]]

OpenAlex: https://openalex.org/W4390650933
    
Haijiao Lu, Luyao Wang, Applied Catalysis B: Environmental. https://doi.org/10.1016/j.apcatb.2024.123707
    
As atmospheric carbon dioxide (CO2) levels surge due to human activities, addressing this global crisis is paramount. This article delves into the realm of photoelectrochemical (PEC) CO2 reduction, a promising solution that combines solar energy conversion and electrochemical processes to transform CO2 into clean energy fuels. The primary focus of this article lies in the cutting-edge unbiased PEC tandem configurations, specifically reviewing recent breakthroughs in coupling PEC CO2 reduction with the oxygen evolution reaction through water oxidation. By consolidating the latest insights and knowledge, this comprehensive review guides readers through the evolving landscape of advanced PEC technologies. Furthermore, it provides insights into prospective developments in this evolving field, shedding light on the paths toward sustainable energy solutions and climate mitigation.    

    

** Constructing delocalized electronic structures to motivate the oxygen reduction activity of zinc selenide for high-performance zinc-air battery   
:PROPERTIES:
:ID: https://openalex.org/W4390651045
:DOI: https://doi.org/10.1016/j.cej.2024.148598
:AUTHORS: Lei Yang, Xiuyun Yao, Changliang Du, Zhanli Han, Mingwei Jin, Shichao Peng, Xiaoqing Ma, Youqi Zhu, Meishuai Zou, Chuanbao Cao
:HOST: Chemical Engineering Journal
:END:

Lei Yang, Xiuyun Yao, Changliang Du, Zhanli Han, Mingwei Jin, Shichao Peng, Xiaoqing Ma, Youqi Zhu, Meishuai Zou, Chuanbao Cao, Chemical Engineering Journal. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148598")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390651045"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390651045"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390651045"))][Get cited by]]

OpenAlex: https://openalex.org/W4390651045
    
Lei Yang, Xiuyun Yao, Changliang Du, Zhanli Han, Mingwei Jin, Shichao Peng, Xiaoqing Ma, Youqi Zhu, Meishuai Zou, Chuanbao Cao, Chemical Engineering Journal. https://doi.org/10.1016/j.cej.2024.148598
    
Rechargeable zinc-air battery (ZAB) typically necessitates highly efficient, durable, and cost-effective electrocatalysts to accelerate oxygen reduction reaction (ORR). Zinc selenide (ZnSe) has been demonstrated as a superior energy storage material due to its unique electronic structure for various energy-related applications but is still rarely developed in electrocatalysis field. Herein, the efficient interfacial engineering is reported to motivate and sufficiently boost the ORR performances of ZnSe to an unprecedented level. Density functional theory (DFT) calculations demonstrate that the introduction of robust Se-C interactions and N species regulation could efficiently modulate the local electronic structure of ZnSe and improve the interaction with oxygen-containing intermediate, thus producing lower reaction energy barrier of O2 → OOH* conversion. The optimized ZnSe@PNC catalyst manifests remarkable ORR activity with a half-wave potential of 0.905 VRHE in alkaline. Furthermore, the assembled Zn-air batteries with ZnSe@PNC cathodes show large peak power density (126 mW cm−2), high specific capacity (818 mAh/g) and long cycling life (200 h). This work provides more possibilities for the electrocatalytic applications of nonprecious metal selenide electrocatalyst for future energy storage.    

    

** One-step microwave synthesis of self-supported NiCoMn medium-entropy alloy with long cycling stability for supercapacitors and oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390651117
:DOI: https://doi.org/10.1016/j.materresbull.2024.112681
:AUTHORS: Jinjuan Dong, Ning Lv, Xiaoning Kang, Xianrui Liu, H. Li, Tianbao Li, Zhen Guo, Jun Luo
:HOST: Materials Research Bulletin
:END:

Jinjuan Dong, Ning Lv, Xiaoning Kang, Xianrui Liu, H. Li, Tianbao Li, Zhen Guo, Jun Luo, Materials Research Bulletin. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.materresbull.2024.112681")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390651117"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390651117"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390651117"))][Get cited by]]

OpenAlex: https://openalex.org/W4390651117
    
Jinjuan Dong, Ning Lv, Xiaoning Kang, Xianrui Liu, H. Li, Tianbao Li, Zhen Guo, Jun Luo, Materials Research Bulletin. https://doi.org/10.1016/j.materresbull.2024.112681
    
This work reports the preparation of NiCoMn medium-entropy alloys and Ag-Bi bimetallic alloys grown on nickel foam using the microwave method. X-ray diffraction confirms the single face-centered cubic phase organization of NiCoMn. Electrochemical analyses show that it has a high capacitance of 3206 F g–1 at 1 A g–1 and remarkable cycle stability (83.0% retention over 70,000 cycles). The Ag-Bi alloys manifest a decent storage capacity of 2462.5 F g–1. To meet the demand for high energy density, the prepared NiCoMn and Ag-Bi are used as positive and negative electrodes to assemble an asymmetric supercapacitor, respectively. The energy density of 218.8 Wh kg–1 is exhibited when the operating voltage is set to 1.5. The NiCoMn alloys also show favorable oxygen evolution reaction catalytic activity, with a low overpotential (186.6 mV) at 10 mA cm–2 and a small Tafel slope (79.6 mV dec–1).    

    

** Co3O4/NiCo2O4 heterojunction as oxygen evolution reaction catalyst for efficient luminol anode electrochemiluminescence   
:PROPERTIES:
:ID: https://openalex.org/W4390651512
:DOI: https://doi.org/10.1016/j.jcis.2024.01.015
:AUTHORS: Chulei Zhao, Chaoyun Ma, Fuping Zhang, Wenjun Li, Chenglin Hong, Fuxi Bao
:HOST: Journal of Colloid and Interface Science
:END:

Chulei Zhao, Chaoyun Ma, Fuping Zhang, Wenjun Li, Chenglin Hong, Fuxi Bao, Journal of Colloid and Interface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.015")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390651512"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390651512"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390651512"))][Get cited by]]

OpenAlex: https://openalex.org/W4390651512
    
Chulei Zhao, Chaoyun Ma, Fuping Zhang, Wenjun Li, Chenglin Hong, Fuxi Bao, Journal of Colloid and Interface Science. https://doi.org/10.1016/j.jcis.2024.01.015
    
Luminol has garnered significant attention from analysts as one of the most effective and commonly used electrochemiluminescence (ECL) reagents. However, the efficient luminescence of luminol anode is limited by the excitation of various reactive oxygen species (ROS). Typically, ROS are generated through co-reactive reagents and dissolved oxygen. Unfortunately, the former suffers from two drawbacks, namely biotoxicity and instability, while the latter cannot offer sufficient oxygen due to its limited solubility in aqueous solutions. Consequently, a low decomposition rate is usually obtained, leading to insufficient ROS. Therefore, there is an urgent need to develop efficient luminol anode systems. This study focuses on the use of zeolitic imidazolate framework-67 (ZIF-67) as a template, employing a controlled chemical etching method to create a ZIF-67/Ni-Co-layered double hydroxide (LDH). The intermediate composite is then annealed in air, resulting in the formation of a Co3O4/NiCo2O4 double-shelled nanobox (DSNB) heterostructure. Due to its structural advantages, the DSNB exhibits excellent electrocatalytic performance in the oxygen evolution reaction (OER). Furthermore, it was found that both the intermediates and products of OER can directly participate in the luminol chemiluminescence process, ultimately resulting in a 700-fold increase in the electrochemiluminescence (ECL) signal compared to an equal molar concentration of luminol solution. This work not only establishes the OER-mediated ECL system but also deepens the understanding of the relationship between ROS and luminol, providing a new pathway to study the luminol anodic ECL luminescence system.    

    

** Engineering Non‐precious Trifunctional Cobalt‐Based Electrocatalysts for Industrial Water Splitting and Ultra‐High‐Temperature Flexible Zinc‐Air Battery   
:PROPERTIES:
:ID: https://openalex.org/W4390655066
:DOI: https://doi.org/10.1002/smll.202308355
:AUTHORS: Tengteng Gu, Jiadong Shen, Zhaoyu Sun, Fangkun Li, Chunyi Zhi, Min Zhu, Jiangwen Liu
:HOST: Small
:END:

Tengteng Gu, Jiadong Shen, Zhaoyu Sun, Fangkun Li, Chunyi Zhi, Min Zhu, Jiangwen Liu, Small. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202308355")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390655066"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390655066"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390655066"))][Get cited by]]

OpenAlex: https://openalex.org/W4390655066
    
Tengteng Gu, Jiadong Shen, Zhaoyu Sun, Fangkun Li, Chunyi Zhi, Min Zhu, Jiangwen Liu, Small. https://doi.org/10.1002/smll.202308355
    
Abstract Developing efficient, robust, and cost‐effective trifunctional catalysts for the hydrogen evolution reaction (HER), oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) at high current density and high temperature is crucial for water splitting at industry‐level conditions and ultra‐high‐temperature Zinc‐air battery (ZAB). Herein, cobalt nanoparticles well‐integrated with nitrogen‐doped porous carbon leaves (Co@NPCL) by direct annealing of core‐shell bimetallic zeolite imidazolate frameworks is synthesized. Benefiting from the homogeneous distribution of metallic Co nanoparticles, the conductive porous carbon, and the doped N species, the as‐fabricated Co@NPCL catalysts exhibit outstanding trifunctional performances with low overpotentials at 10 mA cm −2 for HER (87 mV) and OER (276 mV), long‐lasting lifetime of over 2000 h, and a high half‐wave potential of 0.86 V versus RHE for ORR. Meanwhile, the Co@NPCL catalyst can serve as both cathode and anode for water splitting at industrial conduction, and exhibit a stable cell voltage of 1.87 V to deliver a constant catalytic current of 500 mA cm −2 over 60 h. Moreover, the excellent trifunctional activity of Co@NPCL enables the flexible ZAB to operate efficiently at ultra‐high temperature of 70 °C, delivering 162 mW cm −2 peaks power density and an impressive stability for 4500 min at 2 mA cm −2 .    

    

** Borate Anion‐Intercalated NiV‐LDH Nanoflakes/NiCoP Nanowires Heterostructures for Enhanced Oxygen Evolution Selectivity in Seawater Splitting   
:PROPERTIES:
:ID: https://openalex.org/W4390656116
:DOI: https://doi.org/10.1002/adfm.202315949
:AUTHORS: Taotao Gao, Yuqing Zhou, Xiao‐Jun Zhao, Zhi‐Hong Liu, Juan Bai
:HOST: Advanced Functional Materials
:END:

Taotao Gao, Yuqing Zhou, Xiao‐Jun Zhao, Zhi‐Hong Liu, Juan Bai, Advanced Functional Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202315949")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390656116"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390656116"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390656116"))][Get cited by]]

OpenAlex: https://openalex.org/W4390656116
    
Taotao Gao, Yuqing Zhou, Xiao‐Jun Zhao, Zhi‐Hong Liu, Juan Bai, Advanced Functional Materials. https://doi.org/10.1002/adfm.202315949
    
Abstract Resourceful and inexpensive seawater direct splitting omits the desalination process and effectively increases the efficiency of hydrogen energy generation. However, the development of seawater splitting is hampered by the competing selectivity challenges from anodic oxygen evolution reaction (OER) and chlorine evolution reaction and the issues of electrode corrosion. Herein, the borate anion‐intercalated NiV‐LDH nanoflakes/NiCoP nanowires heterostructures supported on Ni foam (2D/1D NiV‐BLDH/NiCoP/NF) is synthesized. Theoretical calculations show that a small amount of V atom doping in Ni(OH) 2 is favorable for changing the electronic environment around Ni atoms via bridging Ni─O, which can construct Ni─O─V to accelerate electron transfer and promote catalytic activity. The borate anions (B(OH) 4 − ) intercalation not only results in the good hydrophilicity and high OH − selectivity but also weakens the adsorption of chlorine (Cl − ), which effectively restrains the chlorine evolution reaction. Thus, the component optimized NiV 0.1 ‐BLDH/NiCoP/NF electrocatalyst only requires 268 mV overpotential to reach 100 mA cm −2 for OER in an alkaline environment. Particularly, the NiCoP/NF||NiV 0.1 ‐BLDH/NiCoP/NF cell exhibits attractive overall water splitting performance with a low voltage of 1.46 and 1.53 V at 10 mA cm −2 in alkaline freshwater and alkaline seawater, respectively. The design strategy of this electrocatalyst provides a new avenue for seawater splitting.    

    

** Si-doped ZnAl-LDH nanosheets by layer-engineering for efficient photoelectrocatalytic water splitting   
:PROPERTIES:
:ID: https://openalex.org/W4390661684
:DOI: https://doi.org/10.1016/j.apcatb.2024.123706
:AUTHORS: Wentao Bao, Ying Tang, Jie Yu, Wenxia Yan, Chenxu Wang, Yangyang Li, Zhimou Wang, Jinfeng Yang, Li Li Zhang, Feng Ye
:HOST: Applied Catalysis B: Environmental
:END:

Wentao Bao, Ying Tang, Jie Yu, Wenxia Yan, Chenxu Wang, Yangyang Li, Zhimou Wang, Jinfeng Yang, Li Li Zhang, Feng Ye, Applied Catalysis B: Environmental. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.123706")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390661684"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390661684"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390661684"))][Get cited by]]

OpenAlex: https://openalex.org/W4390661684
    
Wentao Bao, Ying Tang, Jie Yu, Wenxia Yan, Chenxu Wang, Yangyang Li, Zhimou Wang, Jinfeng Yang, Li Li Zhang, Feng Ye, Applied Catalysis B: Environmental. https://doi.org/10.1016/j.apcatb.2024.123706
    
A highly efficient Si-doped ZnAl-LDH (denoted as Si-ZnAl-LDH nanosheet) catalyst that is derived from large-area chemical exfoliation for photoelectrocatalytic water splitting. The formation of amorphous Si-ZnAl-LDH nanosheets through chemical exfoliation or layer engineering leads to much more accessible surfaces that originally are not accessible in highly crystalline ZnAl-LDH sheets. The incorporation of Si to highly exfoliated ZnAl-LDH nanosheets generates more oxygen vacancies, increases the number of active sites, redistributes the local charge density of the active centers and effectively suppresses the recombination of the generated electron-hole pairs. Specifically, the overpotential of HER and OER for Si-ZnAl-LDH nanosheet is 108 mV and 260 mV, respectively, at current density of 10 mA cm-2 under light-assisted conditions. Total applied voltage is 1.673 V for water splitting in a full cell. This work provides a novel chemical exfoliation or layer-engineering strategy for the synthesis of scalable and cost-effective LDH nanosheets with efficient photoelectric response.    

    

** Synthesis of Cnt/Ru/Cobalt Oxide Composites as Oxygen Evolution Reaction Electrocatalysts Via Ball Milling Approach   
:PROPERTIES:
:ID: https://openalex.org/W4390661742
:DOI: https://doi.org/10.2139/ssrn.4687449
:AUTHORS: Tongya Tian, Sen Zhang, Song Yang, Chang Ming Li, Xi Zhou, Zhenghua Yang, Qizhe Ji, Xianglong Zhao, Feiyong Chen
:HOST: No host
:END:

Tongya Tian, Sen Zhang, Song Yang, Chang Ming Li, Xi Zhou, Zhenghua Yang, Qizhe Ji, Xianglong Zhao, Feiyong Chen, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4687449")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390661742"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390661742"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390661742"))][Get cited by]]

OpenAlex: https://openalex.org/W4390661742
    
Tongya Tian, Sen Zhang, Song Yang, Chang Ming Li, Xi Zhou, Zhenghua Yang, Qizhe Ji, Xianglong Zhao, Feiyong Chen, No host. https://doi.org/10.2139/ssrn.4687449
    
Ruthenium (Ru) and cobalt oxides (CoxOy) nanoparticles are uniformly decorated on surfaces of carbon nanotubes (CNTs), via ball milling of mixtures consisting of CNTs, triphenylphosphine ruthenium chlorides and cobalt nitrates. Due to collective contributions of Ru and CoxOy, the obtained CNT/Ru/CoxOy composites exhibit excellent electrocatalytic activities and durability for oxygen evolution reaction (OER), both of which outperform those of the state-of-the-art iridium oxide catalysts.    

    

** Bifunctional Electrocatalyst Derived by High-Temperature Pyrolysis of 3-Amino-1,2,4-Triazole-Modified Fe-ZIF Nanostructures for Oxygen Reduction and Evolution Reactions   
:PROPERTIES:
:ID: https://openalex.org/W4390663908
:DOI: https://doi.org/10.1021/acsanm.3c05011
:AUTHORS: Duc‐Viet Nguyen, Ravi Nivetha, Nam Le, Jin Suk Chung, Won Mook Choi, Seung Hyun Hur
:HOST: ACS Applied Nano Materials
:END:

Duc‐Viet Nguyen, Ravi Nivetha, Nam Le, Jin Suk Chung, Won Mook Choi, Seung Hyun Hur, ACS Applied Nano Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.3c05011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390663908"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390663908"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390663908"))][Get cited by]]

OpenAlex: https://openalex.org/W4390663908
    
Duc‐Viet Nguyen, Ravi Nivetha, Nam Le, Jin Suk Chung, Won Mook Choi, Seung Hyun Hur, ACS Applied Nano Materials. https://doi.org/10.1021/acsanm.3c05011
    
Recently, the oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) have received great attention for the development of renewable energy and energy storage systems. In the context of catalyst standpoint, developing single-atom catalysts (SACs) with bifunctional electrocatalytic reactions (ORR/OER) has emerged as a fascinating research field in recent years. However, a majority of SACs that have been reported have a complicated synthesis route that involves many steps and harmful solvents and suffer from aggregation phenomena, which makes them unsustainable for industrial use. Herein, a bifunctional C-Atz-20 electrocatalyst was fabricated by inserting a secondary organic linker, 3-amino-1,2,4-triazole (Atz), into Fe-ZIF followed by high-temperature pyrolysis and its ORR/OER elucidated. To fully comprehend the function of Atz addition, the nanostructured materials underwent an extensive characteristic analysis. The results showed that the C-Atz-20 exhibited better long-term ORR and OER stability tests when compared with Pt/C and RuO2, respectively. Interestingly, the high ORR activity of C-Atz-20 originally contributed to the presence of a large fraction of pyridinic and graphitic N. Rotating ring-disk electrode (RRDE) measurement illustrates the ORR mechanism in the catalytic process, giving a better understanding of electron transport, thus paving the way for the design and development of heterogeneous catalysts with simple preparation and operating procedures.    

    

** Manganese Dissolution in alkaline medium with and without concurrent oxygen evolution in LiMn<sub>2</sub>O<sub>4</sub>   
:PROPERTIES:
:ID: https://openalex.org/W4390667978
:DOI: https://doi.org/10.1039/d3ya00434a
:AUTHORS: Omeshwari Yadorao Bisen, Max Baumung, Michael Tatzel, Cynthia A. Volkert, Marcel Risch
:HOST: No host
:END:

Omeshwari Yadorao Bisen, Max Baumung, Michael Tatzel, Cynthia A. Volkert, Marcel Risch, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ya00434a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390667978"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390667978"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390667978"))][Get cited by]]

OpenAlex: https://openalex.org/W4390667978
    
Omeshwari Yadorao Bisen, Max Baumung, Michael Tatzel, Cynthia A. Volkert, Marcel Risch, No host. https://doi.org/10.1039/d3ya00434a
    
Manganese dissolution during the oxygen evolution reaction (OER) has been a persistent challenge that impedes the practical implementation of Mn-based electrocatalysts including the Li x Mn 2 O 4 system in aqueous alkaline electrolyte. The...    

    

** Low-Pressure Plasma-Processed NiCo Metal–Organic Framework for Oxygen Evolution Reaction and Its Application in Alkaline Water Electrolysis Module   
:PROPERTIES:
:ID: https://openalex.org/W4390670435
:DOI: https://doi.org/10.3390/jcs8010019
:AUTHORS: Yu-Ming Su, Shuo-En Yu, I‐Chih Ni, Chih-I Wu, Yong-Song Chen, Yi-Cheng Chuang, I-Chun Cheng, Jian-Zhang Chen
:HOST: No host
:END:

Yu-Ming Su, Shuo-En Yu, I‐Chih Ni, Chih-I Wu, Yong-Song Chen, Yi-Cheng Chuang, I-Chun Cheng, Jian-Zhang Chen, No host. 8(1)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/jcs8010019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390670435"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390670435"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390670435"))][Get cited by]]

OpenAlex: https://openalex.org/W4390670435
    
Yu-Ming Su, Shuo-En Yu, I‐Chih Ni, Chih-I Wu, Yong-Song Chen, Yi-Cheng Chuang, I-Chun Cheng, Jian-Zhang Chen, No host. https://doi.org/10.3390/jcs8010019
    
Ar, Ar/H2 (95:5), and Ar/O2 (95:5) plasmas are used for treating the NiCo metal–organic framework (MOF), and the plasma-processed NiCo MOF is applied for catalyzing the oxygen evolution reaction (OER) in a 1 M KOH electrolyte. Linear sweep voltammetry measurements show that after plasma treatment with Ar/H2 (95:5) and Ar gases, the overpotential reaches 552 and 540 mV, respectively, at a current density of 100 mA/cm2. The increase in the double-layer capacitance further confirms the enhanced oxygen production activity. We test the Ar plasma-treated NiCo MOF as an electrocatalyst at the OER electrode and Ru as an electrocatalyst at the hydrogen evolution reaction (HER) electrode in the alkaline water electrolysis module. The energy efficiency of the electrolyzer with the Ar plasma-processed NiCo-MOF catalyst increases from 54.7% to 62.5% at a current density of 500 mA/cm2 at 25 °C. The alkaline water electrolysis module with the Ar plasma-processed catalyst also exhibits a specific energy consumption of 5.20 kWh/m3 and 4.69 kWh/m3 at 25 °C and 70 °C, respectively. The alkaline water electrolysis module performance parameters such as the hydrogen production rate, specific energy consumption, and energy efficiency are characterized at temperatures between 25 °C and 70 °C. Our experimental results show that the NiCo MOF is an efficient OER electrocatalyst for the alkaline water electrolysis module.    

    

** In-based coordination polymer-derived carbon nanoribbons with abundant CoP nanoparticles in carbon nanotubes for water oxidation   
:PROPERTIES:
:ID: https://openalex.org/W4390670646
:DOI: https://doi.org/10.1063/5.0185031
:AUTHORS: X.-F. Wang, Yuanyuan Guo, Yanqiong Shen, Jinjie Qian
:HOST: The Journal of Chemical Physics
:END:

X.-F. Wang, Yuanyuan Guo, Yanqiong Shen, Jinjie Qian, The Journal of Chemical Physics. 160(2)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0185031")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390670646"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390670646"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390670646"))][Get cited by]]

OpenAlex: https://openalex.org/W4390670646
    
X.-F. Wang, Yuanyuan Guo, Yanqiong Shen, Jinjie Qian, The Journal of Chemical Physics. https://doi.org/10.1063/5.0185031
    
The sluggish oxygen evolution reaction (OER) in overall electrocatalytic water splitting poses a significant challenge in hydrogen production. A series of transition metal phosphides are emerging as promising electrocatalysts, effectively modulating the charge distribution of surrounding atoms for OER. In this study, a highly efficient OER electrocatalyst (CoP-CNR-CNT) was successfully synthesized through the pyrolysis and phosphatization of a Co-doped In-based coordination polymer, specifically InOF-25. This process resulted in evenly dispersed CoP nanoparticles encapsulated in coordination polymer-derived carbon nanoribbons. The synthesized CoP-CNR-CNT demonstrated a competitive OER activity with a smaller overpotential (η10) of 295.7 mV at 10 mA cm-2 and a satisfactory long-term stability compared to the state-of-the-art RuO2 (η10 = 353.7 mV). The high OER activity and stability can be attributed to the high conductivity of the carbon network, the abundance of CoP particles, and the intricate nanostructure of nanoribbons/nanotubes. This work provides valuable insights into the rational design and facile preparation of efficient non-precious metal-based OER electrocatalysts from inorganic-organic coordination polymers, with potential applications in various energy conversion and storage systems.    

    

** Spontaneous Formation of Ultrasmall Noble Metal Nanoparticles on Cobalt‐Based Layered Double Hydroxide for Electrochemical and Environmental Catalysis   
:PROPERTIES:
:ID: https://openalex.org/W4390671687
:DOI: https://doi.org/10.1002/smll.202310380
:AUTHORS: Qian Chen, Peisheng Cao, Yanying Wang, Jinying Yuan, Peng Wu
:HOST: Small
:END:

Qian Chen, Peisheng Cao, Yanying Wang, Jinying Yuan, Peng Wu, Small. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310380")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390671687"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390671687"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390671687"))][Get cited by]]

OpenAlex: https://openalex.org/W4390671687
    
Qian Chen, Peisheng Cao, Yanying Wang, Jinying Yuan, Peng Wu, Small. https://doi.org/10.1002/smll.202310380
    
Supported noble metal nanoparticles (NMNPs) are appealing for energy and environment catalysis. To facilitate the loading of NMNPs, in situ reduction of Mn+ on the support with extra reductants/surfactants is adopted, but typically results in aggregated NMNPs with uneven size distributions or blocked active sites of the NMNPs. Herein, the use of cobalt layered double hydroxide (Co-LDH) is proposed as both support and reductant for the preparation of supported NMNPs with ultrasmall sizes and even distributions. The resultant Co-LDH-supported NMNPs exhibit excellent catalytic performance and stability. For example, Ir/Co-LDH displays a low overpotential of 188 mV (10 mA cm-2 ) for electrocatalytic oxygen evolution reaction and a long-term stability over 100 h (100 mA cm-2 ) in overall water splitting. Ru/Co-LDH can achieve a 4-nitrophenol reduction with high rate of 0.36 min-1 and S2- detection with low limit of detection (LOD) of 0.34 µm. Overall, this work provides a green and effective strategy to fabricate supported NMNPs with greatly improved catalytic performances.    

    

** Solution plasma assisted Mn-doping: A novel strategy for developing highly durable and active oxygen evolution catalysts   
:PROPERTIES:
:ID: https://openalex.org/W4390673576
:DOI: https://doi.org/10.1039/d3se01398g
:AUTHORS: Hong He, Takeshi Matsuda, Akira Miura, Masanori Nagao, Jeevan Kumar Padarti, Tomoya Ohno, Shigeto Hirai
:HOST: No host
:END:

Hong He, Takeshi Matsuda, Akira Miura, Masanori Nagao, Jeevan Kumar Padarti, Tomoya Ohno, Shigeto Hirai, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3se01398g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390673576"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390673576"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390673576"))][Get cited by]]

OpenAlex: https://openalex.org/W4390673576
    
Hong He, Takeshi Matsuda, Akira Miura, Masanori Nagao, Jeevan Kumar Padarti, Tomoya Ohno, Shigeto Hirai, No host. https://doi.org/10.1039/d3se01398g
    
Oxygen evolution and oxygen reduction catalysts play a crucial role in energy conversion technologies for achieving a decarbonized society. In the present study, we introduce the Mn-doping as a tool...    

    

** A facile synthesis of hierarchical CoFe2O4 nanosheets for efficient oxygen evolution in neutral medium   
:PROPERTIES:
:ID: https://openalex.org/W4390674249
:DOI: https://doi.org/10.1016/j.jssc.2024.124553
:AUTHORS: Xinqi Wang, Zhaoyuan Wang, Yuanyuan Cao, Xinxin Liu, Liping Zhou, Jianjun Shi, Bao‐Zhu Guo, Di Li, Rongrong Ye, Zhao Zhang
:HOST: Journal of Solid State Chemistry
:END:

Xinqi Wang, Zhaoyuan Wang, Yuanyuan Cao, Xinxin Liu, Liping Zhou, Jianjun Shi, Bao‐Zhu Guo, Di Li, Rongrong Ye, Zhao Zhang, Journal of Solid State Chemistry. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jssc.2024.124553")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390674249"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390674249"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390674249"))][Get cited by]]

OpenAlex: https://openalex.org/W4390674249
    
Xinqi Wang, Zhaoyuan Wang, Yuanyuan Cao, Xinxin Liu, Liping Zhou, Jianjun Shi, Bao‐Zhu Guo, Di Li, Rongrong Ye, Zhao Zhang, Journal of Solid State Chemistry. https://doi.org/10.1016/j.jssc.2024.124553
    
It is of great significance to develop electrocatalysts that are abundant in Earth's crust, highly efficient, and exceptionally durable for the oxygen evolution reaction (OER), particularly in neutral media. Herein, the hierarchical CoFe2O4 nanosheets supported on iron foam (CoFe2O4/IF) are prepared by the ambient spontaneous redox reaction between iron foam and Co2+ at room temperature. The as-obtained CoFe2O4/IF electrode presents excellent electrocatalytic OER activity with an overpotential of 429 mV at 10 mA cm−2 and maintains the stability of 50 h in 1 M PBS. The outstanding electrocatalytic OER activity of CoFe2O4/IF can be credited to the decreased transfer resistance and unique structural features. In addition, the CoFe2O4/IF presented here holds promise for noble-metal-free OER electrocatalyst.    

    

** Stable overall water electrolysis performance of interface engineered Y2Ru2O7/NiMoO4@NF in alkaline solution   
:PROPERTIES:
:ID: https://openalex.org/W4390674399
:DOI: https://doi.org/10.1016/j.apsusc.2024.159336
:AUTHORS: Venkatesan Jayaraman, Ganghyun Jang, Do‐Heyoung Kim
:HOST: Applied Surface Science
:END:

Venkatesan Jayaraman, Ganghyun Jang, Do‐Heyoung Kim, Applied Surface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159336")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390674399"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390674399"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390674399"))][Get cited by]]

OpenAlex: https://openalex.org/W4390674399
    
Venkatesan Jayaraman, Ganghyun Jang, Do‐Heyoung Kim, Applied Surface Science. https://doi.org/10.1016/j.apsusc.2024.159336
    
Problems faced in water electrolysis, such as sluggish reaction kinetics and poor electrode stability, can be overcome by developing electrode materials with tailormade properties. Introducing a nanostructured interface with pyrochlore materials is an efficient but complex strategy. This study focused on the interface engineering of the pyrochlore Y2Ru2O7/NiMoO4@NF. The material was found to show significantly high overall water splitting performance in 1 M KOH electrolyte solution. Specifically, the prepared Y2Ru2O7/NiMoO4@NF showed oxygen evolution and hydrogen evolution overpotentials of 287 and 112 mV at a current density of 10 mA cm−2, respectively. A Y2Ru2O7/NiMoO4@NF electrode with higher stability that was prepared rationally required a cell voltage of only 1.613 V to achieve a current density of 10 mA cm−2 for alkaline water electrolysis. This showed the excellent catalytic ability of the electrode for overall water splitting. In particular, the temperature dependence of the electrode’s performance in water electrolysis in a practical water electrolyzer was examined to ascertain the electrode’s suitability for use on an industrial scale; the operating temperature of the electrolyzer was varied in the range 25–75 °C. The observed exceptional alkaline overall water splitting performance of the electrode resulted from the high charge mobility at the interface that enhanced synergy between Y2Ru2O7 and NiMoO4. The results of this study show that combining the metal oxides Y2Ru2O7 and NiMoO4 is a promising approach for preparing materials with high catalytic activity for use in alkaline overall water splitting.    

    

** Ruthenium-anchored aminated MWCNTs/polyaniline membrane electrode assembly for alkaline water splitting   
:PROPERTIES:
:ID: https://openalex.org/W4390675146
:DOI: https://doi.org/10.1016/j.jelechem.2024.118027
:AUTHORS: Dimple K. Bora, Priyanka P. Bavdane, Bhavana Bhatt, Devendra Y. Nikumbe, Govind Sethia, Rajaram K. Nagarale
:HOST: Journal of Electroanalytical Chemistry
:END:

Dimple K. Bora, Priyanka P. Bavdane, Bhavana Bhatt, Devendra Y. Nikumbe, Govind Sethia, Rajaram K. Nagarale, Journal of Electroanalytical Chemistry. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2024.118027")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390675146"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390675146"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390675146"))][Get cited by]]

OpenAlex: https://openalex.org/W4390675146
    
Dimple K. Bora, Priyanka P. Bavdane, Bhavana Bhatt, Devendra Y. Nikumbe, Govind Sethia, Rajaram K. Nagarale, Journal of Electroanalytical Chemistry. https://doi.org/10.1016/j.jelechem.2024.118027
    
Here, we present a ruthenium-anchored aminated multi-walled carbon nanotube-based bifunctional electrocatalyst for alkaline water splitting (Ru@AM-MWCNTs). The method involves functionalizing MWCNTs before stabilising the ruthenium active sites. The prepared Ru@AM-MWCNTs displayed a low overpotential of 67 mV for HER on a glassy carbon electrode in a 1 M KOH electrolyte. Further, to promote the OER activity, Ru@AM-MWCNTs is sintered at 300 °C which reflected the OER at 283 mV overpotential at a current density of 10 mAcm−2. The MEA made up of free-standing polyaniline and Ru@AM-MWCNTs as cathode and T-Ru@AM-MWCNTs as anode on nickel foam, achieved 80 % faradic efficiency for water splitting. In a 1 M KOH, it maintained a current density of 0.51 Acm−2 for 30 h at an onset potential of 2 V, surpassing the Neosepta membrane's performance under identical experimental conditions. Furthermore, the produced oxygen is 98 % pure, demonstrating the MEA's excellent potential for green hydrogen production.    

    

** Leveraging phosphate group in Pd/PdO decorated nickel phosphate microflowers via pulsed laser for robust hydrogen production in hydrazine-assisted electrolyzer   
:PROPERTIES:
:ID: https://openalex.org/W4390683852
:DOI: https://doi.org/10.1016/j.ijhydene.2024.01.029
:AUTHORS: Hyeyeon Lee, Jayaraman Theerthagiri, M.L. Aruna Kumari, Ahreum Min, Cheol Joo Moon, V. Anbazhagan, Richard L. Brutchey, Myong Yong Choi
:HOST: International Journal of Hydrogen Energy
:END:

Hyeyeon Lee, Jayaraman Theerthagiri, M.L. Aruna Kumari, Ahreum Min, Cheol Joo Moon, V. Anbazhagan, Richard L. Brutchey, Myong Yong Choi, International Journal of Hydrogen Energy. 57(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390683852"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390683852"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390683852"))][Get cited by]]

OpenAlex: https://openalex.org/W4390683852
    
Hyeyeon Lee, Jayaraman Theerthagiri, M.L. Aruna Kumari, Ahreum Min, Cheol Joo Moon, V. Anbazhagan, Richard L. Brutchey, Myong Yong Choi, International Journal of Hydrogen Energy. https://doi.org/10.1016/j.ijhydene.2024.01.029
    
By driving the electrooxidation of small molecules instead of relying on sluggish oxygen evolution reaction (OER), low-input voltage is obtained for overall water splitting (OWS) and hydrogen generation, requiring active electrocatalysts. Using single-step pulsed laser irradiation, strong metal-support interaction is achieved on Pd/PdO-decorated Ni3(PO4)2·8H2O (NiPh) microflowers, yielding an outstanding bifunctional electrocatalyst for hydrogen evolution (HER) and hydrazine oxidation (HzOR). When Pd/PdO-NiPh-3 serves as both anode and cathode in the OWS electrolyzer (OER||HER), a cell voltage of 2.098 V achieves 10 mA/cm2 in 1.0 M KOH. When evaluated in the hydrazine-coupled electrolyzer (HzOR||HER), Pd/PdO-NiPh-3 exhibits remarkable stability with a low cell voltage of 0.538 V in 0.5 M-N2H4/1.0 M-KOH, which is approximately 1.56 V lower than that of the traditional water electrolyzers. In Pd/PdO-NiPh, the empty 4s and 5s orbitals of Ni2+ and Pd, respectively, serve as two absorption sites. These sites facilitate chemisorption on the electrocatalyst surface by forming a two-electron dipolar bond between the lone-pair electrons of NH2 groups in N2H4 and Ni2+ as well as Pd. A feasible strategy for utilizing Pd/PdO-NiPh catalysts in developing direct N2H4 fuel cells is investigated in this work, enabling the simultaneous production of robust energy-saving H2 fuel and electricity.    

    

** Operando X-ray photoelectron spectroscopy cell for water electrolysis: A complete picture of iridium electronic structure during oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390683983
:DOI: https://doi.org/10.1016/j.ijhydene.2023.12.216
:AUTHORS: Tomáš Hrbek, Peter Kúš, Miquel Gamón Rodríguez, Vladimı́r Matolín, Serhiy Cherevko
:HOST: International Journal of Hydrogen Energy
:END:

Tomáš Hrbek, Peter Kúš, Miquel Gamón Rodríguez, Vladimı́r Matolín, Serhiy Cherevko, International Journal of Hydrogen Energy. 57(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2023.12.216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390683983"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390683983"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390683983"))][Get cited by]]

OpenAlex: https://openalex.org/W4390683983
    
Tomáš Hrbek, Peter Kúš, Miquel Gamón Rodríguez, Vladimı́r Matolín, Serhiy Cherevko, International Journal of Hydrogen Energy. https://doi.org/10.1016/j.ijhydene.2023.12.216
    
Operando investigations are crucial for understanding various catalytical processes. We present a newly designed cell for operando X-ray Photoelectron Spectroscopy water electrolysis. All measurements are done on a laboratory X-ray source, which makes the cell easily accessible to a wide audience. We demonstrate the cell operation on a magnetron-sputtered iridium catalyst for the anode of a Proton Exchange Membrane Water Electrolyzer. The main challenges consist of the anode water intake through the membrane from the cathode and the electrical contact. We can oxidize metallic Ir0 into a stable IrIV and reduce it back to metal, which agrees well with the ex-situ measurements. Furthermore, the operando tracking of the Ir 4f and O 1s spectra during the oxidation uncovers the presence of intermediates of the Oxygen Evolution Reaction on Ir, and thus allows the improvement of the understanding of its mechanism. The cell can be used to further study other catalysts for low-temperature water electrolyzers, both noble and non-noble metal-based.    

    

** Conductive nitrogen-doped carbon armored MOF-derived Fe doped nickel sulfide for efficient oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390683992
:DOI: https://doi.org/10.1016/j.ijhydene.2024.01.006
:AUTHORS: Fusheng Wen, Le Pang, Tao Zhang, Xiaoli Huang, Changdi Li, Hailong Liu
:HOST: International Journal of Hydrogen Energy
:END:

Fusheng Wen, Le Pang, Tao Zhang, Xiaoli Huang, Changdi Li, Hailong Liu, International Journal of Hydrogen Energy. 57(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.006")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390683992"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390683992"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390683992"))][Get cited by]]

OpenAlex: https://openalex.org/W4390683992
    
Fusheng Wen, Le Pang, Tao Zhang, Xiaoli Huang, Changdi Li, Hailong Liu, International Journal of Hydrogen Energy. https://doi.org/10.1016/j.ijhydene.2024.01.006
    
Developing clean energy sources is vital amid the global energy crisis. Hydrogen, emerging as a sustainable energy vector via water electrolysis, mandates adept catalysts owing to the sluggish electrochemical oxygen evolution reaction (OER) kinetics. This work provides a three-step synthesis of Fe-doped NiS2 catalyst from metal-organic frameworks (MOFs). By encapsulating with nitrogen-doped carbon (NC) armor derived from polypyrrole (PPy) through thermal annealing, a novel Fe–NiS2@NC catalyst is achieved for improving the OER performance. The Fe–NiS2@NC demonstrates outstanding prowess, achieves a current density of 10 mA cm−2 with an overpotential as modest as 255 mV, accompanied with a Tafel slope of only 77 mV dec−1. Furthermore, it maintains operational stability for over 40 h under demanding conditions of 50 mA cm−2, displaying an impressive durability compared to the pure NiS2 catalyst. This work combines Fe-doping in NiS2 and PPy-derived NC encapsulation, achieving a dual enhancement of activity and stability of the catalyst. And this strategy also offers a feasible pathway to simultaneously boost the activity and stability in OER electrocatalysts, significantly contributing to clean energy solutions and providing ideas for future research.    

    

** Surface reconstruction of La0.6Sr0.4Co0.8Ni0.2O3- perovskite nanofibers for oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390942237
:DOI: https://doi.org/10.1016/j.ceramint.2024.01.211
:AUTHORS: Yusong Niu, Xin Chang, Mingyi Zhang, Jingbo Mu
:HOST: Ceramics International
:END:

Yusong Niu, Xin Chang, Mingyi Zhang, Jingbo Mu, Ceramics International. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.01.211")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390942237"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390942237"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390942237"))][Get cited by]]

OpenAlex: https://openalex.org/W4390942237
    
Yusong Niu, Xin Chang, Mingyi Zhang, Jingbo Mu, Ceramics International. https://doi.org/10.1016/j.ceramint.2024.01.211
    
Perovskites have become promising alternatives to precious metal-catalyzed oxygen evolution reaction (OER). Herein, we report the synthesis of several perovskite nanofibers, specifically La0.6Sr0.4CoxNi1-xO3-δ (LSCN), and investigate their electrocatalytic water oxidation activity in alkaline electrolytes. La0.6Sr0.4Co0.8Ni0.2O3-δ (LSCN-0.8) is selected and immersed in an aqueous NaBH4 solution for 1 h for surface reconstruction. The perovskite nanofibers' electrocatalytic OER activity and stability are rigorously evaluated using a standard three-electrode system. Results reveal that even a slight Co substitution for Ni content within the LSCN perovskite structure has a notable impact on electrocatalytic activity. Moreover, LSCN-0.8 exhibits an overpotential of 363 mV at 20 mA cm−2 in 1 M KOH. However, significant improvement is observed after the surface reconstruction process. The optimized LSCN-0.8 (now called LSCN-2) displays the lowest OER overpotential (320 mV) under the same conditions. Furthermore, the LSCN-2 nanostructure demonstrates exceptional electrode stability, as evidenced by only a slight decrease in electrocatalytic performance during 5000 cycles of linear sweep voltammetry.    

    

** The strategies to improve TMDs represented by MoS2 electrocatalytic oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390843576
:DOI: https://doi.org/10.1016/j.cclet.2024.109515
:AUTHORS: Junan Pan, Xin-Yi Liu, Hangjie Ji, Yi Zhu, Yanling Zhuang, Kang Chen, Ning Sun, Yongqi Liu, Yongquan Lei, Kun Wang, Bowen Zang, Longlu Wang
:HOST: Chinese Chemical Letters
:END:

Junan Pan, Xin-Yi Liu, Hangjie Ji, Yi Zhu, Yanling Zhuang, Kang Chen, Ning Sun, Yongqi Liu, Yongquan Lei, Kun Wang, Bowen Zang, Longlu Wang, Chinese Chemical Letters. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cclet.2024.109515")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390843576"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390843576"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390843576"))][Get cited by]]

OpenAlex: https://openalex.org/W4390843576
    
Junan Pan, Xin-Yi Liu, Hangjie Ji, Yi Zhu, Yanling Zhuang, Kang Chen, Ning Sun, Yongqi Liu, Yongquan Lei, Kun Wang, Bowen Zang, Longlu Wang, Chinese Chemical Letters. https://doi.org/10.1016/j.cclet.2024.109515
    
The hydrogen evolution reaction (HER) and the oxygen evolution reaction (OER) are the two half reactions that make up the over water splitting reaction. Increasing oxygen evolution reaction rate wound immensely raise the efficiency of over water splitting reaction because it is the rate limiting reaction in water splitting reaction. The key to improve OER performance is the development and utilization of advanced catalysts. As one of the most potential catalysts for HER, it has gradually attracted the attention of researchers in the aspect of catalytic OER. It is very necessary to review the research progress of Transition metal dichalcogenides (TMDs) in catalytic OER to promote the research process in the field. In this review, we comprehensively and systematically summarized the strategies to improve TMDs electrocatalytic OER. First of all, structural regulation of TMDs-based electrocatalyst was summarized in detail, mainly including size engineering, defect engineering, doping engineering, phase engineering and heterojunction engineering. Once more, magnetic field regulation as a representative of external field regulation to improve TMDs electrocatalytic OER performance was discussed in depth. Last but not least, the strategies to improve TMDs electrocatalytic OER is prospected and some views on the development of this field are also put forward, which are expected to enhance the catalytic efficiency of TMDs for OER.    

    

** Material Dynamics of Manganese-Based Oxychlorides for Oxygen Evolution Reaction in Acid   
:PROPERTIES:
:ID: https://openalex.org/W4390918522
:DOI: https://doi.org/10.1021/acs.chemmater.3c02362
:AUTHORS: Ruihan Li, Dennis Nordlund, Linsey C. Seitz
:HOST: Chemistry of Materials
:END:

Ruihan Li, Dennis Nordlund, Linsey C. Seitz, Chemistry of Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.chemmater.3c02362")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390918522"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390918522"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390918522"))][Get cited by]]

OpenAlex: https://openalex.org/W4390918522
    
Ruihan Li, Dennis Nordlund, Linsey C. Seitz, Chemistry of Materials. https://doi.org/10.1021/acs.chemmater.3c02362
    
Earth-abundant manganese-based oxides have emerged as promising alternatives to noble-metal-based catalysts for the oxygen evolution reaction (OER) in acidic conditions; however, their inferior activity and stability present critical challenges for the sustainable production of hydrogen via water electrolysis. Moving beyond oxides, heteroanionic materials, which incorporate anions with lower electronegativity than oxygen, have shown potential for improving the OER performance, but a detailed understanding of the underlying mechanisms is lacking. Here, we investigate manganese-based oxychlorides (Mn8O10Cl3 and FeMn7O10Cl3) that exhibit excellent activity and stability for acidic OER to elucidate material property dynamics and correlate them with OER behaviors. Our rigorous electrochemical stability testing reveals that the high operating potential mitigates Mn dissolution over prolonged exposure to the OER conditions. Through a combination of ex situ and in situ surface and bulk-sensitive X-ray spectroscopy analyses, we observe a trade-off between increasing Mn valence and maintaining structural integrity, which results in dynamic bond length changes within the [MnCl6] octahedra during the activation and degradation processes of these oxychloride catalysts. This study provides insights into the fundamental relationships between the chemical, electronic, and geometric properties of the catalysts and their electrocatalytic outcomes.    

    

** Elucidating the Mechanism of Oxygen Evolution Reaction on Nanostructured Copper-Based Catalysts   
:PROPERTIES:
:ID: https://openalex.org/W4390806435
:DOI: https://doi.org/10.1021/acsanm.3c05313
:AUTHORS: Chi Xie, Kaili Zhang, Yongyong Lai, Lili Du, Jing Ma, Shouwu Xu, Ping Qiu
:HOST: ACS Applied Nano Materials
:END:

Chi Xie, Kaili Zhang, Yongyong Lai, Lili Du, Jing Ma, Shouwu Xu, Ping Qiu, ACS Applied Nano Materials. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.3c05313")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390806435"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390806435"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390806435"))][Get cited by]]

OpenAlex: https://openalex.org/W4390806435
    
Chi Xie, Kaili Zhang, Yongyong Lai, Lili Du, Jing Ma, Shouwu Xu, Ping Qiu, ACS Applied Nano Materials. https://doi.org/10.1021/acsanm.3c05313
    
In water splitting processes, the oxygen evolution reaction (OER) is one of the main kinetic control steps that should be triggered by high-efficiency catalysts. A series of Cu-based catalysts are considered potential candidates. This work provides a simple and effective strategy for fabricating large-scale copper-based catalysts by anodization on a copper foil at room temperature in a KOH solution. The representative petal-shaped CuO and Cu(OH)2 nanorods are obtained. The corresponding surface areas are 0.0197 and 1.966 m2/g, respectively. The surface wettability of Cu(OH)2 is lower than that of CuO. The catalytic performance is studied by linear sweep voltammetry (LSV). The results show that the potential of the OER for CuO at 10 mA/cm2 is 1.67 V, which reduces by 130 mV compared to Cu(OH)2. The CuO could keep 10 mA/cm2 after a 1 h chronoamperometry test, which is about 3 times higher than that of Cu(OH)2. To verify the distinguishing catalytic difference between CuO and Cu(OH)2, in situ Raman spectra have been recorded. Inspiringly, the CuIII active specie at 603 cm–1 is captured during the OER process on CuO instead of Cu(OH)2. The related mechanism has been discussed in detail.    

    

** High-entropy borides with frame structure: Efficient electrocatalysts for oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390758147
:DOI: https://doi.org/10.1016/j.ijhydene.2023.12.082
:AUTHORS: Tingyue Gu, Zhiyuan Jing, Fang Miao, Wei Wu, Yuhong Zhao, Hua Hou, Xiubing Liang
:HOST: International Journal of Hydrogen Energy
:END:

Tingyue Gu, Zhiyuan Jing, Fang Miao, Wei Wu, Yuhong Zhao, Hua Hou, Xiubing Liang, International Journal of Hydrogen Energy. 56(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2023.12.082")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390758147"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390758147"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390758147"))][Get cited by]]

OpenAlex: https://openalex.org/W4390758147
    
Tingyue Gu, Zhiyuan Jing, Fang Miao, Wei Wu, Yuhong Zhao, Hua Hou, Xiubing Liang, International Journal of Hydrogen Energy. https://doi.org/10.1016/j.ijhydene.2023.12.082
    
Innovative methods for producing catalytic nanomaterials are crucial for advancing environmental conversion and storage technologies. This study introduces a novel approach to fabricate a high-entropy boride alloy with a frame structure, FeCoNiMgB/NF, using in situ growth of high-entropy alloy powder on nickel foam (NF). The resulting frame-structured FeCoNiMgB/NF high-entropy boride alloy exhibits superior electrocatalytic performance for the oxygen evolution reaction (OER) compared to pure FeCoNiMgB powder and other counterparts. It demonstrates a low overpotential of 183 mV at a current density of 10 mA cm−2, a Tafel slope of 34 mV dec−1 in 1 M KOH, and excellent stability over 72 h without significant decay. The outstanding catalytic performance of the frame-structured FeCoNiMgB/NF high-entropy alloy can be attributed to the synergistic effects of FeCoNiMgB–NF, a larger specific surface area, and excellent frame-structure conductivity. The alloy's long-term stability is a result of the gradual formation of the FeCoNiMgOOH lath structure array during the reaction process, facilitating low adsorption and charge transfer energies as per theoretical calculations. This study presents a new method for constructing advanced frame-structured high-entropy boride alloys, promising advancements in energy conversion and storage technologies.    

    

** A p-d block synergistic effect enables robust electrocatalytic oxygen evolution   
:PROPERTIES:
:ID: https://openalex.org/W4390733560
:DOI: https://doi.org/10.1016/j.cclet.2024.109496
:AUTHORS: Xiaohui Zhao, Rui Zhao, Qian Liu, H.R. Chen, Jing Wang, Yongfeng Hu, Yan Li, Qiuming Peng, John S. Tse
:HOST: Chinese Chemical Letters
:END:

Xiaohui Zhao, Rui Zhao, Qian Liu, H.R. Chen, Jing Wang, Yongfeng Hu, Yan Li, Qiuming Peng, John S. Tse, Chinese Chemical Letters. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cclet.2024.109496")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390733560"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390733560"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390733560"))][Get cited by]]

OpenAlex: https://openalex.org/W4390733560
    
Xiaohui Zhao, Rui Zhao, Qian Liu, H.R. Chen, Jing Wang, Yongfeng Hu, Yan Li, Qiuming Peng, John S. Tse, Chinese Chemical Letters. https://doi.org/10.1016/j.cclet.2024.109496
    
Oxygen evolution reaction (OER), occurring at the anode of electrochemical water splitting requires a comprehensive understanding of oxygen electrocatalysis mechanism to optimize its efficiency. Atomically dispersed transition metal supported by nitrogen-doped carbon is featured with excellent catalytic performance. Herein, we report a Mg/Co bimetal site which utilizes Mg 3p electrons with strong binding of *OH (the first key reaction intermediates in the free energy diagram) to trigger the OER reaction and Co 3d itinerant character to regulate the binding strength of *O. Benefiting from the fine-tuned adsorption/desorption possesses, the optimized catalyst delivers superior OER activity with low overpotential, i.e., 310 mV at a current density of 10 mA/cm2 and 455 mV at 100 mA/cm2. Moreover, the current density is able to be maintained at 10 mA/cm2 for 10 h, consistent with the theoretical simulations for oxidization process, which demonstrates stable configurations after multiple *OH modification, revealing robust applicability in alkaline medium.    

    

** NiSe-modified CoMoO4 nanosheets as bifunctional electrocatalysts for hydrogen and oxygen evolution reactions   
:PROPERTIES:
:ID: https://openalex.org/W4390755768
:DOI: https://doi.org/10.1016/j.jallcom.2024.173495
:AUTHORS: Menghe Jiang, Zhicong Hu, Yongjin Zou, Cuili Xiang, Fen Xu, Lin Sun, Xiaoyun Hu
:HOST: Journal of Alloys and Compounds
:END:

Menghe Jiang, Zhicong Hu, Yongjin Zou, Cuili Xiang, Fen Xu, Lin Sun, Xiaoyun Hu, Journal of Alloys and Compounds. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173495")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390755768"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390755768"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390755768"))][Get cited by]]

OpenAlex: https://openalex.org/W4390755768
    
Menghe Jiang, Zhicong Hu, Yongjin Zou, Cuili Xiang, Fen Xu, Lin Sun, Xiaoyun Hu, Journal of Alloys and Compounds. https://doi.org/10.1016/j.jallcom.2024.173495
    
Selecting self-supporting substrates with large specific surface areas is an effective strategy to avoid the agglomeration of nanomaterials and improve the structural stability of materials while increasing their electrical conductivity. In this study, CoMoO4 nanosheet structures were first grown on a nickel foam (NF) substrate by hydrothermal and calcination processes. Then, NiSe nanoparticles were deposited on NF/CoMoO4 by a constant potential method to construct NF/CoMoO4@NiSe nanosheet electrode materials with graded layered structures. This nanosheet structure grown on NF substrates provided enough space for mass transfer and fully exposed the electrochemical active sites. Meanwhile, the self-supported electrode reduced the indirect contact resistance between the electrocatalyst and the substrate, which promoted the timely release of generated bubbles from the electrode. The NF/CoMoO4@NiSe electrode exhibited excellent hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) electrocatalytic activities under alkaline conditions. Overpotentials of only 58 mV and 184 mV were needed to achieve a current density of 10 mA·cm-2 for the HER and OER, respectively. This study presents new ideas for the construction of nanosheet structures and the design of efficient HER and OER bifunctional electrocatalysts using transition metal selenides.    

    

** IrNi Nanoparticles as Highly Efficient Electrocatalysts Towards the Oxygen Evolution Reaction in an Acidic Medium   
:PROPERTIES:
:ID: https://openalex.org/W4390746910
:DOI: https://doi.org/10.1007/978-981-99-8581-4_11
:AUTHORS: Yongwen Sun, Hong Lv, Gao Da, Cunman Zhang
:HOST: No host
:END:

Yongwen Sun, Hong Lv, Gao Da, Cunman Zhang, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-981-99-8581-4_11")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390746910"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390746910"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390746910"))][Get cited by]]

OpenAlex: https://openalex.org/W4390746910
    
Yongwen Sun, Hong Lv, Gao Da, Cunman Zhang, No host. https://doi.org/10.1007/978-981-99-8581-4_11
    
The development of efficient and durable bifunctional electrocatalysts for oxygen evolution reaction (OER), still poses huge challenges. Herein, we utilize a facile hydrothermal method to synthesize a novel IrNi nanocrystals. In particular, the electronic structure is altered when a portion of the iridium atom is replaced by a Ni atom, which causes the center of the d band to shift downward, favoring the catalytic reaction. The overpotentials for OER of 273 mV at a current density of 10 mA cm−2, exceed the capabilities of commercial Ir catalysts. The alloying of Ir with Ni reduces the adsorption energy of oxygen intermediates to achieve a fast oxygen evolution reaction. This work highlights a potentially powerful strategy toward the general synthesis of novel, Ir-based alloy as highly active and durable bifunctional electrocatalysts for high-performance electrochemical overall-water-splitting devices.    

    

** Anisotropic structural carbon skeleton decorated with Co nanoparticles towards oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390843849
:DOI: https://doi.org/10.1016/j.colsurfa.2024.133228
:AUTHORS: Changshui Wang, Qian Zhang, B. Li, Zhenlu Liu, Cenlin He, Guangli Yang, Longjun Jiang, Chunmei Zhang, Kunming Liu, Shuijian He
:HOST: Colloids and Surfaces A: Physicochemical and Engineering Aspects
:END:

Changshui Wang, Qian Zhang, B. Li, Zhenlu Liu, Cenlin He, Guangli Yang, Longjun Jiang, Chunmei Zhang, Kunming Liu, Shuijian He, Colloids and Surfaces A: Physicochemical and Engineering Aspects. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.colsurfa.2024.133228")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390843849"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390843849"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390843849"))][Get cited by]]

OpenAlex: https://openalex.org/W4390843849
    
Changshui Wang, Qian Zhang, B. Li, Zhenlu Liu, Cenlin He, Guangli Yang, Longjun Jiang, Chunmei Zhang, Kunming Liu, Shuijian He, Colloids and Surfaces A: Physicochemical and Engineering Aspects. https://doi.org/10.1016/j.colsurfa.2024.133228
    
Hierarchical carbon skeletons derived from natural wood can be employed as the substrates to fabricate self-supported catalysts. The typically three sections (cross section, radial section, and tangential section) of wood would significantly affect the electrocatalytic performance. Therefore, the correlations between anisotropy structure of wood derived hierarchical carbon skeletons and oxygen evolution reaction (OER) performances was systematically investigated. The cross-sectional wood-derived carbon decorated with Co nanoparticles requires an overpotential of 370 mV to deliver 50 mA cm-2 superior to those of radial-sectional and tangential-sectional counterparts. The cross-section of wood derived carbon skeleton possesses higher content of Co nanoparticles, which is accounted for the enhanced OER catalytic activity. This work highlights the critical contribution of anisotropy of carbon skeletons in promoting the OER properties and provides a new paradigm for designing advanced electrocatalysts.    

    

** Recent advances on cationic vacancy engineering application of oxygen evolution reaction electrocatalyst in seawater   
:PROPERTIES:
:ID: https://openalex.org/W4390858649
:DOI: https://doi.org/10.1016/j.jece.2024.111946
:AUTHORS: Hong Liang, Bo Li, Chenchen Jing, Zihan Zhuang, Yuji Zhang, Huajie Huang, Qianqian Jiang, Jianguo Tang
:HOST: Journal of Environmental Chemical Engineering
:END:

Hong Liang, Bo Li, Chenchen Jing, Zihan Zhuang, Yuji Zhang, Huajie Huang, Qianqian Jiang, Jianguo Tang, Journal of Environmental Chemical Engineering. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jece.2024.111946")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390858649"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390858649"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390858649"))][Get cited by]]

OpenAlex: https://openalex.org/W4390858649
    
Hong Liang, Bo Li, Chenchen Jing, Zihan Zhuang, Yuji Zhang, Huajie Huang, Qianqian Jiang, Jianguo Tang, Journal of Environmental Chemical Engineering. https://doi.org/10.1016/j.jece.2024.111946
    
Seawater oxygen evolution reaction (OER) is a kind of feasible method to solve energy problems. Through studying seawater OER, it can not only reduce the dependence on traditional energy sources, but also protect the environment and reducing pollution. Cationic defect engineering can effectively enhance the properties of seawater OER. This way can make more catalysts active sites exposed and simultaneously change the electronic properties of materials to improve the conductivity of materials. Meanwhile, defects lead to electron delocalization, promote carrier migration and increase the charge transfer rate of materials. Cationic vacancy defects can effectively improve the OER properties of materials. Therefore, studying relationship between structure and function of vacancy defect electrocatalysts is beneficial to improve the seawater OER performance better. The transition metal-based vacancy catalyst has good seawater OER performance, for example, Fe, Co and Ni based vacancy catalysts. The influence of cationic vacancy on the improvement of OER performance in seawater was further expounded by the DFT of analysis of cationic vacancy catalyst. With the continuous progress of technology, the cost of seawater electrolysis technology will be gradually reduced, which can greatly promote the development of sustainable and renewable clean energy.    

    

** Copper oxide nanofibers obtained by solution blow spinning as catalysts for oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390965940
:DOI: https://doi.org/10.1016/j.ceramint.2024.01.213
:AUTHORS: Alessandra Patrícia de Araújo Dantas, Rafael A. Raimundo, Pedro de Lima Neto, Caio M. S. Lopes, Jakeline R.D. Santos, Francisco J.A. Loureiro, Tatiany Barata Pereira, Marco A. Morales, Eliton S. Medeiros, Daniel A. Macedo
:HOST: Ceramics International
:END:

Alessandra Patrícia de Araújo Dantas, Rafael A. Raimundo, Pedro de Lima Neto, Caio M. S. Lopes, Jakeline R.D. Santos, Francisco J.A. Loureiro, Tatiany Barata Pereira, Marco A. Morales, Eliton S. Medeiros, Daniel A. Macedo, Ceramics International. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.01.213")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390965940"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390965940"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390965940"))][Get cited by]]

OpenAlex: https://openalex.org/W4390965940
    
Alessandra Patrícia de Araújo Dantas, Rafael A. Raimundo, Pedro de Lima Neto, Caio M. S. Lopes, Jakeline R.D. Santos, Francisco J.A. Loureiro, Tatiany Barata Pereira, Marco A. Morales, Eliton S. Medeiros, Daniel A. Macedo, Ceramics International. https://doi.org/10.1016/j.ceramint.2024.01.213
    
In this work, we report copper oxide nanofibers (CuO – N) synthesized by Solution Blow Spinning (SBS) for oxygen evolution reaction (OER), and their comparison with a control sample based on a commercial powder (CuO – C). Both materials were characterized by various techniques, including X-ray diffraction (XRD), magnetometry, scanning electron microscopy (SEM), and spectroscopy (Fourier transform infrared (FT-IR), Raman and X-ray photoelectron (XPS)) to confirm the purity, and microstructural and surface chemical properties. Subsequently, the performance of copper oxide catalysts in a 1.0 M KOH solution was investigated. Copper oxide with nanofiber morphology (CuO – N) exhibited a small overpotential of 385 mV @ 10 mA cm−2 and a Tafel coefficient of only 76 mV dec−1, i.e., fast kinetics for water splitting, a result that is modulated by oxygen vacancies (O2/O1 = 0.83). The oxygen vacancies are due to the presence of Cu1+ in the lattice. The analyses of the magnetization measurements at 5 K suggest a larger amount of Cu1+ in sample CuO – N. Therefore, this work sheds light on how to design low-cost nanofibrous catalysts based on abundant transition metals in the earth's crust by SBS, an economical and scalable technique, which is promising for energy applications.    

    

** Magnetic field enhanced surface reconstruction of Fe2P and the promotional effect in electrochemical oxygen evolution   
:PROPERTIES:
:ID: https://openalex.org/W4390755203
:DOI: https://doi.org/10.1016/j.apsusc.2024.159357
:AUTHORS: Fu‐Rong Chen, Shen Chen, Yujun Zhu, Yidan Liu, Difan Zhou, Lei Huang, Liyi Shi, Hongbin Zhang, Shixun Cao, Rongrong Jia
:HOST: Applied Surface Science
:END:

Fu‐Rong Chen, Shen Chen, Yujun Zhu, Yidan Liu, Difan Zhou, Lei Huang, Liyi Shi, Hongbin Zhang, Shixun Cao, Rongrong Jia, Applied Surface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159357")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390755203"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390755203"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390755203"))][Get cited by]]

OpenAlex: https://openalex.org/W4390755203
    
Fu‐Rong Chen, Shen Chen, Yujun Zhu, Yidan Liu, Difan Zhou, Lei Huang, Liyi Shi, Hongbin Zhang, Shixun Cao, Rongrong Jia, Applied Surface Science. https://doi.org/10.1016/j.apsusc.2024.159357
    
In recent years, the utilization of magnetic fields to enhance the oxygen evolution reaction (OER) performance of catalysts has emerged as an effective approach. However, current research primarily focusing on the impact on magnetic transition metal oxides, and the relevant mechanisms are still worth further exploration. Here, the OER performance of Fe2P loaded on carbon paper (Fe2P/CP) and nickel foam (Fe2P/NF) substrates under in situ magnetic field was investigated. It is revealed that magnetic fields can substantially enhance the OER performance of Fe2P/CP and Fe2P/NF. With a magnetic field of 1.0 T, the current density of 75–Fe2P/CP increases by 28 times (1.8 V vs. RHE), leading to a maximum magnetic current density percentage of 2770%. According to our results, the magnetic enhancement effect is highly correlated with the surface reconstruction of Fe2P to α-FeOOH with lower OER energy barriers. Additionally, the spin pinning effect is observed on the α-FeOOH/ Fe2P interfaces, which leads to the rapid alignment of spin electrons on the surface of catalysts under magnetic field, lowering the O–O coupling energy barrier, and therefore improve OER kinetics. These discoveries have the potential to contribute to a fundamental and comprehensive understanding of electrochemical reactions involving magnetic fields.    

    

** Charge Engineering in Black Phosphorene with Tunable Electronic Structures as Efficient Oxygen Evolution Electrocatalysis   
:PROPERTIES:
:ID: https://openalex.org/W4390837510
:DOI: https://doi.org/10.2139/ssrn.4694215
:AUTHORS: Huating Liu, Zongyu Huang, Hui Qiao, Xiang Qi
:HOST: No host
:END:

Huating Liu, Zongyu Huang, Hui Qiao, Xiang Qi, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4694215")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390837510"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390837510"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390837510"))][Get cited by]]

OpenAlex: https://openalex.org/W4390837510
    
Huating Liu, Zongyu Huang, Hui Qiao, Xiang Qi, No host. https://doi.org/10.2139/ssrn.4694215
    
Layered black phosphorus (BP) has unique electronic structure, which makes it an ideal candidate material for electrocatalytic oxygen evolution reaction (OER). Charge doping effectively improves the environmental stability and catalytic activity of BP by providing electron transfer channels and reducing the charge transfer barrier. Therefore, based on the method of first principles calculation, this paper theoretically discusses how the intrinsic charge doping without introducing impurities changes the electronic structure and improves the catalytic activity of BP. It is found that charge engineering can stimulate the hybridization between different P-p orbitals, effectively regulate and change the electronic structure and work function while maintaining the direct bandgap semiconductor characteristics of monolayer BP system. More importantly, in the catalytic process of OER, electrons and hole doping as free charges provide different donor and acceptor energy levels for the system depending on the doping concentration, and affect the adsorption capacity of monolayer BP to different reaction intermediates. When the doping concentration is 0.15 e/u.c, monolayer BP can achieves the optimal Gibbs free energy and overpotential, the rate-determining step of reaction free-energy diagram is downhill and exothermal, and carrier mobility is significantly increased. These results provide new opportunities and possibilities for designing charge-engineered BP catalysts with adjustable electronic structure and excellent OER activity.    

    

** NiCo2S4 octahedral configuration doped by Mn, Zn and Cu for oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390883323
:DOI: https://doi.org/10.1039/d3cc06171j
:AUTHORS: Yi-Ting Chen, Wu H, Ning Tang, Mengjie Zhang, Yuqiao Wang
:HOST: Chemical Communications
:END:

Yi-Ting Chen, Wu H, Ning Tang, Mengjie Zhang, Yuqiao Wang, Chemical Communications. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cc06171j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390883323"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390883323"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390883323"))][Get cited by]]

OpenAlex: https://openalex.org/W4390883323
    
Yi-Ting Chen, Wu H, Ning Tang, Mengjie Zhang, Yuqiao Wang, Chemical Communications. https://doi.org/10.1039/d3cc06171j
    
Transition metals with similar atomic radius were used to doping spinel NiCo2S4 to adjust octahedral configuration. Mn dopants adjusted the morphology and surface charge distribution, optimized the electron transport and...    

    

** The electronic structure of the active center of Co3Se4 electrocatalyst was adjusted by Te doping for efficient oxygen evolution   
:PROPERTIES:
:ID: https://openalex.org/W4390725329
:DOI: https://doi.org/10.1016/j.jcis.2024.01.026
:AUTHORS: Hao Wang, Xueya Deng, A.R. Bari, Mingzheng Gu, Man Lin, Gaoyun An, Xiaomin Huang, Xiaojun Zhang
:HOST: Journal of Colloid and Interface Science
:END:

Hao Wang, Xueya Deng, A.R. Bari, Mingzheng Gu, Man Lin, Gaoyun An, Xiaomin Huang, Xiaojun Zhang, Journal of Colloid and Interface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.026")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390725329"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390725329"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390725329"))][Get cited by]]

OpenAlex: https://openalex.org/W4390725329
    
Hao Wang, Xueya Deng, A.R. Bari, Mingzheng Gu, Man Lin, Gaoyun An, Xiaomin Huang, Xiaojun Zhang, Journal of Colloid and Interface Science. https://doi.org/10.1016/j.jcis.2024.01.026
    
In order to enhance the energy efficiency of water electrolysis, it is imperative to devise electrocatalysts for oxygen evolution reaction that are both non-precious metal-based and highly efficient. Efficient catalyst design is generally based on electronic structural engineering. Considering the electronegativity disparity between selenium (Se) and tellurium (Te), the tunable bandgaps, and the conductive metallic nature of Te. We designed a material wherein Te atoms are uniformly doped onto the surface of Cobalt tetra selenide (Co3Se4) nanorods, leading to the synthesis of a defect-rich material. Experimental results demonstrate that Te doping in Co3Se4 increases active sites and optimizes the electronic structure of Co cations, enhancing the design of multi-defect structures. This promotes the generation of the Co(oxy) hydroxide (CoOOH) active phase, enhancing catalytic activity by maximizing the binding strength between Co sites and oxygenated intermediates. Te-Co3Se4 nanorods exhibit good catalytic activity for oxygen evolution reactions, with an overpotential of 269 mV at a driving current density of 50 mA cm−2 and excellent stability in alkaline media (over 100 h). This discovery indicates the feasibility of strategically combining various imperfect structures, thereby unlocking the latent potential of diverse catalysts in electrocatalytic reactions.    

    

** Hollow CoVOx/Ag nanoprism with tailored electronic structure for high efficiency oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390843673
:DOI: https://doi.org/10.1016/j.jcis.2024.01.073
:AUTHORS: Siru Chen, Yingying Yao, Jing Xu, Junyan Chen, Zhuo Wang, Pengyu Li, Yanqiang Li
:HOST: Journal of Colloid and Interface Science
:END:

Siru Chen, Yingying Yao, Jing Xu, Junyan Chen, Zhuo Wang, Pengyu Li, Yanqiang Li, Journal of Colloid and Interface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.073")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390843673"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390843673"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390843673"))][Get cited by]]

OpenAlex: https://openalex.org/W4390843673
    
Siru Chen, Yingying Yao, Jing Xu, Junyan Chen, Zhuo Wang, Pengyu Li, Yanqiang Li, Journal of Colloid and Interface Science. https://doi.org/10.1016/j.jcis.2024.01.073
    
Developing high-active and inexpensive electrocatalysts for oxygen evolution reaction (OER) is very important in the field of water splitting. The catalytic performance of electrocatalysts can be significantly improved by optimizing the electronic structure and designing suitable nanostructure. In this work, we represent the synthesis of hollow CoVOx/Ag-5 for OER. Due to the interaction of CoVOx and Ag nanoparticles, the electronic structure is optimized to improve the intrinsic catalytic activity. Additionally, the extrinsic catalytic activity of CoVOx/Ag is enhanced by the abundant active sites from the hollow structure. As a result, the CoVOx/Ag-5 demonstrates significantly enhanced OER catalytic activity with a low overpotential of 247 mV at 10 mA cm−2. In addition, it also exhibits excellent durability, without obvious attenuation in performance after continuous operation for 60 h. Furthermore, the catalyst can enable full water splitting with appropriate 100 % Faraday efficiency, demonstrating its practical application.    

    

** Facile and scalable synthesis of Ni3S2/Fe3O4 nanoblocks as an efficient and stable electrocatalyst for oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390858579
:DOI: https://doi.org/10.1016/j.jcis.2024.01.072
:AUTHORS: Jing Mei, Yu Deng, Xiaohong Cheng, Qi Wu
:HOST: Journal of Colloid and Interface Science
:END:

Jing Mei, Yu Deng, Xiaohong Cheng, Qi Wu, Journal of Colloid and Interface Science. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.072")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390858579"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390858579"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390858579"))][Get cited by]]

OpenAlex: https://openalex.org/W4390858579
    
Jing Mei, Yu Deng, Xiaohong Cheng, Qi Wu, Journal of Colloid and Interface Science. https://doi.org/10.1016/j.jcis.2024.01.072
    
This study employed a one-step hydrothermal process to synthesize Ni3S2/Fe3O4 nanoblocks in situ on nickel foam (NF). The resulting Ni3S2/Fe3O4/NF catalyst demonstrates exceptional electrocatalytic activity for the oxygen evolution reaction (OER) and robust long-term stability. It achieves a low overpotential of only 220 mV for a current density of 10 mA cm−2 with a Tafel slope of 54.1 mV dec−1 and remains stable in 1.0 M KOH for 66 h. The binder-free self-supported three-dimensional nanoblocks enhance the reaction region and long-term stability. Electronic interactions between Fe3O4 and Ni3S2, coupled with heterogeneous interfaces, optimize the electronic structure, fostering the formation of highly reactive species. Density-functional theory (DFT) calculations confirm that Ni3S2/Fe3O4, with a heterogeneous interfacial structure, modulates the chemisorption of reaction intermediates on the catalyst surface, optimizing the Gibbs free energies (ΔG) of oxygen-containing intermediates. The synergistic effect between the two active materials within the heterogeneous structure enhances OER catalytic performance. This finding offers a valuable approach to designing efficient and stable OER electrocatalysts.    

    

** Regulating Ru‐O Bonding Interactions by Ir Doping Boosts the Acid Oxygen Evolution Performance   
:PROPERTIES:
:ID: https://openalex.org/W4390615127
:DOI: https://doi.org/10.1002/cctc.202301222
:AUTHORS: Jianxin Zeng, Zhengxin Qian, Qing-Na Zheng, Jing‐Hua Tian, Hua Zhang, Jianfeng Li
:HOST: ChemCatChem
:END:

Jianxin Zeng, Zhengxin Qian, Qing-Na Zheng, Jing‐Hua Tian, Hua Zhang, Jianfeng Li, ChemCatChem. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301222")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390615127"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390615127"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390615127"))][Get cited by]]

OpenAlex: https://openalex.org/W4390615127
    
Jianxin Zeng, Zhengxin Qian, Qing-Na Zheng, Jing‐Hua Tian, Hua Zhang, Jianfeng Li, ChemCatChem. https://doi.org/10.1002/cctc.202301222
    
Highly active and stable oxygen evolution reaction (OER) catalysts are crucial for the large‐scale application of proton exchange membrane water electrolyzers. However, the dynamic reconfiguration of the catalyst surface structure and active centers is still undefined, which greatly hinders the development and application of efficient OER catalysts. Herein, we report an IrRuOx/C catalyst with a facile low‐temperature synthesis route, which can reach 10 mA cm‐2 at an overpotential of 217 mV with a Tafel slope as low as 39.4 mV dec‐1, and yields a mass activity 61 times that of commercial IrO2/C at an overpotential of 300 mV. The lattice oxygen structure of RuOx is stabilized by the introduction of Ir species, thus greatly promoting the OER activity and durability. Further in situ Raman reveals that RuOx emerges as the active species at high potentials, and Ru‐O bonding interactions are enhanced with Ir regulation, stabilizing the solvation of Ru at high potentials and accelerating the nucleophilic attack of water molecules, leading to the improved OER performance. This work deepens the fundamental understanding of OER and offers an effective way to advance the utilization of Ru‐based OER catalysts.    

    

** Efficient Oxygen Evolution Reaction by Ru(II) Polypyridyl Complex based AIEgen   
:PROPERTIES:
:ID: https://openalex.org/W4390987133
:DOI: https://doi.org/10.1039/d3qi02380j
:AUTHORS: Snehadrinarayan Khatua, Monosh Rabha, Sreenivasan Nagappan, Bhaskar Sen, Khanindram Baruah, Subrata Kundu
:HOST: No host
:END:

Snehadrinarayan Khatua, Monosh Rabha, Sreenivasan Nagappan, Bhaskar Sen, Khanindram Baruah, Subrata Kundu, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3qi02380j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987133"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987133"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987133"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987133
    
Snehadrinarayan Khatua, Monosh Rabha, Sreenivasan Nagappan, Bhaskar Sen, Khanindram Baruah, Subrata Kundu, No host. https://doi.org/10.1039/d3qi02380j
    
Ruthenium polypyridyl complexes are known for their excellent photophysical properties and rich electrochemical behavior. Thus, developing complexes with multifunctional behavior showing potential applications in multiple fields is of great importance....    

    

** Polypyrrole-wrapped Hofmann type metal–organic framework nanoflowers to boost oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390843720
:DOI: https://doi.org/10.1016/j.jssc.2024.124559
:AUTHORS: Yuhang Wu, Yuwen Li, Ling Shen, Quanwen Pan, Ye Tao, Junkuo Gao
:HOST: Journal of Solid State Chemistry
:END:

Yuhang Wu, Yuwen Li, Ling Shen, Quanwen Pan, Ye Tao, Junkuo Gao, Journal of Solid State Chemistry. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jssc.2024.124559")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390843720"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390843720"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390843720"))][Get cited by]]

OpenAlex: https://openalex.org/W4390843720
    
Yuhang Wu, Yuwen Li, Ling Shen, Quanwen Pan, Ye Tao, Junkuo Gao, Journal of Solid State Chemistry. https://doi.org/10.1016/j.jssc.2024.124559
    
The exploration of efficient and stable metal-organic frameworks (MOFs) for electrocatalytic oxygen evolution reaction (OER) has received increasing attention. However, the limited electronic conductivity of MOFs hinders the electron transfer rate. Herein, we report the preparation of conducting polypyrrole (PPy)-modified MOF nanoflowers (MOF-NFs@PPy) as promising electrocatalysts for OER. The PPy layer significantly increases the electrical conductivity and modulates the ionic transmittance between MOF-NFs and the electrolyte. The interaction of PPy with the MOF-NFs modifies the electronic structure and improves the reaction efficiency at the active sites. The obtained MOF-NFs@PPy exhibits excellent electrocatalytic activity with an OER overpotential of only 218 mV@10 mA cm−2 and small Tafel slope of 47.4 mV dec−1. In addition, the MOF-NFs@PPy exhibited excellent long-term stability (>24 h). This work may provide a new idea and a novel construction strategy for MOFs to improve OER performance.    

    

** Benchmarking Stability of Iridium Oxide in Acidic Media under Oxygen Evolution Conditions: A Review: Part II   
:PROPERTIES:
:ID: https://openalex.org/W4390987310
:DOI: https://doi.org/10.1595/205651324x17055018154113
:AUTHORS: James Murawski, Søren B. Scott, Reshma R. Rao, Katie Rigg, Christopher Mark Zalitis, James Stevens, Jonathan Sharman, Gareth Hinds, Ifan E. L. Stephens
:HOST: Johnson Matthey Technology Review
:END:

James Murawski, Søren B. Scott, Reshma R. Rao, Katie Rigg, Christopher Mark Zalitis, James Stevens, Jonathan Sharman, Gareth Hinds, Ifan E. L. Stephens, Johnson Matthey Technology Review. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1595/205651324x17055018154113")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987310"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987310"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987310"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987310
    
James Murawski, Søren B. Scott, Reshma R. Rao, Katie Rigg, Christopher Mark Zalitis, James Stevens, Jonathan Sharman, Gareth Hinds, Ifan E. L. Stephens, Johnson Matthey Technology Review. https://doi.org/10.1595/205651324x17055018154113
    
Part I (1) introduced state-of-the-art proton exchange membrane (PEM) electrolysers with iridium-based catalysts for oxygen evolution at the anode in green hydrogen applications. Aqueous model systems and full cell testing were discussed along with proton exchange membrane water electrolyser (PEMWE) catalyst degradation mechanisms, types of iridium oxide, mechanisms of iridium dissolution and stability studies. In Part II, we highlight considerations and best practices for the investigation of activity and stability of oxygen evolution catalysts via short term testing.    

    

** Dynamic stabilization of nickel-based oxygen evolution electrocatalysts in the presence of chloride ions using a phosphate additive   
:PROPERTIES:
:ID: https://openalex.org/W4390796596
:DOI: https://doi.org/10.1039/d3ta05566c
:AUTHORS: Hiroki Komiya, Keisuke Obata, Tetsuo Honma, Kazuhiro Takanabe
:HOST: No host
:END:

Hiroki Komiya, Keisuke Obata, Tetsuo Honma, Kazuhiro Takanabe, No host. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ta05566c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390796596"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390796596"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390796596"))][Get cited by]]

OpenAlex: https://openalex.org/W4390796596
    
Hiroki Komiya, Keisuke Obata, Tetsuo Honma, Kazuhiro Takanabe, No host. https://doi.org/10.1039/d3ta05566c
    
The phosphate stabilizes Ni and borate maintains an appropriate pH for durable oxygen evolution, even with Cl − .    

    

** Cr doping and heterostructure accelerated NiFe LDH reaction kinetics assist MoS2 oxygen evolution reaction   
:PROPERTIES:
:ID: https://openalex.org/W4390766348
:DOI: https://doi.org/10.1039/d3nr06058f
:AUTHORS: Jinzhao Huang, Jun Tanida, Sixuan Zhang, Zehui Liu, Jing Xiao
:HOST: Nanoscale
:END:

Jinzhao Huang, Jun Tanida, Sixuan Zhang, Zehui Liu, Jing Xiao, Nanoscale. None(None)] 2024.
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3nr06058f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390766348"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390766348"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390766348"))][Get cited by]]

OpenAlex: https://openalex.org/W4390766348
    
Jinzhao Huang, Jun Tanida, Sixuan Zhang, Zehui Liu, Jing Xiao, Nanoscale. https://doi.org/10.1039/d3nr06058f
    
Although molybdenum disulfide (MoS2) has garnered significant interest as a potential catalyst for the oxygen evolution reaction (OER), its poor intrinsic activity and few marginal active spots restrict its electrocatalytic...    

    
