#+TITLE: water splitting
Description: water splitting papers
Created on Wed Jun 12 01:08:44 2024

Found 36 results from 2024-06-05 to 2024-06-12
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Accelerate Sustainable Enabling of Oxygen Evolution Reaction Catalyst for Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399347332
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Hydrogen Energy Systems and Technologies
:PUBLICATION_DATE: 2025-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3030/101150584")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399347332"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399347332"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399347332"))][Get cited by]]

OpenAlex: https://openalex.org/W4399347332 (Open access: False)
    
, No host. None(None)] 2025. https://doi.org/10.3030/101150584 
     
No abstract    

    

* Cobalt Titanate–Phosphorous-Doped g-C3N4 Heterostructure with Impressive Electrocatalytic Activity for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399322660
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11664-024-11148-z")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399322660"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399322660"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399322660"))][Get cited by]]

OpenAlex: https://openalex.org/W4399322660 (Open access: False)
    
[[https://openalex.org/A5099012178][Rekha Muthuvel]], [[https://openalex.org/A5081220271][Mukul Sethi]], [[https://openalex.org/A5013108193][L. Cindrella]], Journal of electronic materials. None(None)] 2024. https://doi.org/10.1007/s11664-024-11148-z 
     
No abstract    

    

* Simple and Scalable Synthetic Route for Tunable Compositions of Multimetallic Oxyfluorides as Oxygen Evolution Reaction Catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399323479
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.4c00259")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399323479"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399323479"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399323479"))][Get cited by]]

OpenAlex: https://openalex.org/W4399323479 (Open access: False)
    
[[https://openalex.org/A5067856485][Alexandre Terry]], [[https://openalex.org/A5099012400][Samuel Mathiot]], [[https://openalex.org/A5057585517][Amandine Guiet]], [[https://openalex.org/A5024267039][Édouard Boivin]], [[https://openalex.org/A5032399312][Zahra Goharibajestani]], [[https://openalex.org/A5035016002][Vincent Maisonneuve]], [[https://openalex.org/A5006226200][Annie Hémon‐Ribaud]], [[https://openalex.org/A5008136772][Romain Moury]], [[https://openalex.org/A5018580006][Nikolay Kornienko]], [[https://openalex.org/A5084091531][Jérôme Lhoste]], ACS applied energy materials. None(None)] 2024. https://doi.org/10.1021/acsaem.4c00259 
     
This work suggests a simple and scalable synthetic route to prepare multimetallic oxyfluorides, without requiring high temperature, high pressure, and a specific atmosphere (F2, N2, Ar, vacuum, etc.). For that, tunable compositions of Ni2+–Co2+–Fe3+-based oxyfluorides Co(1–x)/2Nix/2Fe0.5O0.5F1.5 have been prepared by calcination at moderate temperature under ambient air of Co1–xNixFeF5(H2O)7 precursors, prepared beforehand through coprecipitation at room temperature, across the whole range of the solid solution (0 ≤ x ≤ 1). Structural and thermal analyses confirmed the successful substitution for both hydrated fluoride precursors and oxyfluorides. Finally, we evaluated the electrocatalytic performance of the different Ni2+–Co2+–Fe3+ oxyfluorides for oxygen evolution reaction. Among these, the trimetallic Co0.25Ni0.25Fe0.5O0.5F1.5 exhibits the lowest overpotential (290 and 370 mV respectively at 10 and 100 mA cm–2) and the highest specific activity (3.9 A m–2 at 1.53 V vs RHE). These results highlight the need for compositional tunability to maximize performance.    

    

* Strong Metal‐Support Interaction Modulation between Pt Nanoclusters and Mn3O4 Nanosheets through Oxygen Vacancy Control to Achieve High Activities for Acidic Hydrogen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399330823
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202402652")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399330823"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399330823"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399330823"))][Get cited by]]

OpenAlex: https://openalex.org/W4399330823 (Open access: False)
    
[[https://openalex.org/A5036342077][Dan Hu]], [[https://openalex.org/A5077999325][Yongjie Wang]], [[https://openalex.org/A5037837951][Weiheng Chen]], [[https://openalex.org/A5022429952][Zhongqing Jiang]], [[https://openalex.org/A5039480720][Binglu Deng]], [[https://openalex.org/A5003604997][Zhong‐Jie Jiang]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202402652 
     
Abstract The optimization of metal‐support interactions is used to fabricate noble metal‐based nanoclusters with high activity for hydrogen evolution reaction (HER) in acid media. Specifically, the oxygen‐defective Mn 3 O 4 nanosheets supported Pt nanoclusters of ≈1.71 nm in diameter (Pt/V·‐Mn 3 O 4 NSs) are synthesized through the controlled solvothermal reaction. The Pt/V·‐Mn 3 O 4 NSs show a superior activity and excellent stability for the HER in the acidic media. They only require an overpotential of 19 mV to drive −10 mA cm −2 and show negligible activity loss at −10 and −250 mA cm −2 for >200 and >60 h, respectively. Their Pt mass activity is 12.4 times higher than that of the Pt/C and even higher than those of many single‐atom based Pt catalysts. DFT calculations show that their high HER activity arises mainly from the strong metal‐support interaction between Pt and Mn 3 O 4 . It can facilitate the charge transfer from Mn 3 O 4 to Pt, optimizing the H adsorption on the catalyst surface and promoting the evolution of H 2 through the Volmer–Tafel mechanism. The oxygen vacancies in the V·‐Mn 3 O 4 NSs are found to be inconducive to the high activity of the Pt/V·‐Mn 3 O 4 NSs, highlighting the great importance to reduce the vacancy levels in V·‐Mn 3 O 4 NSs.    

    

* Wood‐Structured Nanomaterials as Highly Efficient, Self‐Standing Electrocatalysts for Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399331219
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202402511")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399331219"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399331219"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399331219"))][Get cited by]]

OpenAlex: https://openalex.org/W4399331219 (Open access: False)
    
[[https://openalex.org/A5030047391][Jianlin Huang]], [[https://openalex.org/A5044264654][Zhikai Shi]], [[https://openalex.org/A5048679629][Chengwei Mao]], [[https://openalex.org/A5045927468][Gaixiu Yang]], [[https://openalex.org/A5037458498][Yan Chen]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202402511 
     
Abstract Electrocatalytic water splitting (EWS) driven by renewable energy is widely considered an environmentally friendly and sustainable approach for generating hydrogen (H 2 ), an ideal energy carrier for the future. However, the efficiency and economic viability of large‐scale water electrolysis depend on electrocatalysts that can efficiently accelerate the electrochemical reactions taking place at the two electrodes. Wood‐derived nanomaterials are well‐suited for serving as EWS catalysts because of their hierarchically porous structure with high surface area and low tortuosity, compositional tunability, cost‐effectiveness, and self‐standing integral electrode configuration. Here, recent advancements in the design and synthesis of wood‐structured nanomaterials serving as advanced electrocatalysts for water splitting are summarized. First, the design principles and corresponding strategies toward highly effective wood‐structured electrocatalysts (WSECs) are emphasized. Then, a comprehensive overview of current findings on WSECs, encompassing diverse structural designs and functionalities such as supported‐metal nanoparticles (NPs), single‐atom catalysts (SACs), metal compounds, and heterostructured electrocatalysts based on engineered wood hosts are presented. Subsequently, the application of these WSECs in various aspects of water splitting, including the hydrogen evolution reaction (HER), oxygen evolution reaction (OER), overall water splitting (OWS), and hybrid water electrolysis (HWE) are explored. Finally, the prospects, challenges, and opportunities associated with the broad application of WSECs are briefly discussed. This review aims to provide a comprehensive understanding of the ongoing developments in water‐splitting catalysts, along with outlining design principles for the future development of WSECs.    

    

* Water Ligands Regulate the Redox Leveling Mechanism of the Oxygen-Evolving Complex of the Photosystem II  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399332391
:TOPICS: Molecular Mechanisms of Photosynthesis and Photoprotection, Optogenetics in Neuroscience and Biophysics Research, Mitochondrial Dynamics and Reactive Oxygen Species Regulation
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c02926")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399332391"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399332391"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399332391"))][Get cited by]]

OpenAlex: https://openalex.org/W4399332391 (Open access: False)
    
[[https://openalex.org/A5008203795][Jinchan Liu]], [[https://openalex.org/A5010438957][Ke Yang]], [[https://openalex.org/A5083398956][Zhuoran Long]], [[https://openalex.org/A5032302972][William H. Armstrong]], [[https://openalex.org/A5064040856][Gary W. Brudvig]], [[https://openalex.org/A5089129603][Víctor S. Batista]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c02926 
     
Understanding how water ligands regulate the conformational changes and functionality of the oxygen-evolving complex (OEC) in photosystem II (PSII) throughout the catalytic cycle of oxygen evolution remains a highly intriguing and unresolved challenge. In this study, we investigate the effect of water insertion (WI) on the redox state of the OEC by using the molecular dynamics (MD) and quantum mechanics/molecular mechanics (QM/MM) hybrid methods. We find that water binding significantly reduces the free energy change for proton-coupled electron transfer (PCET) from Mn to Y    

    

* NiFe<sub>2</sub>O<sub>4</sub>Materials Based on Mo and Mn Diatomic Co-Doping Were Used to Study Oxygen Evolution Performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399349968
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.12677/japc.2024.132028")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399349968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399349968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399349968"))][Get cited by]]

OpenAlex: https://openalex.org/W4399349968 (Open access: False)
    
[[https://openalex.org/A5099020435][颖 顾]], Wu li hua xue jin zhan. 13(02)] 2024. https://doi.org/10.12677/japc.2024.132028 
     
No abstract    

    

* Vacancy Mediated Electrooxidation of 5‐Hydroxymethyl Furfuryl Using Defect Engineered Layered Double Hydroxide Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399355849
:TOPICS: Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202400676")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399355849"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399355849"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399355849"))][Get cited by]]

OpenAlex: https://openalex.org/W4399355849 (Open access: False)
    
[[https://openalex.org/A5052178810][Muhammad Zubair]], [[https://openalex.org/A5007275934][Pavel M. Usov]], [[https://openalex.org/A5077549415][Hiroyoshi Ohtsu]], [[https://openalex.org/A5067007716][Jodie A. Yuwono]], [[https://openalex.org/A5054142686][Carter S. Gerke]], [[https://openalex.org/A5031633022][Gregory D. Foley]], [[https://openalex.org/A5091519108][Haira G. Hackbarth]], [[https://openalex.org/A5044168251][Richard F. Webster]], [[https://openalex.org/A5079625567][Yintang Yang]], [[https://openalex.org/A5013302657][William Hadinata Lie]], [[https://openalex.org/A5053180714][Zhipeng Ma]], [[https://openalex.org/A5040663143][Lars Thomsen]], [[https://openalex.org/A5048557783][Masaki Kawano]], [[https://openalex.org/A5060108388][Nicholas M. Bedford]], Advanced energy materials. None(None)] 2024. https://doi.org/10.1002/aenm.202400676 
     
Abstract Electrochemical biomass oxidation coupled with hydrogen evolution offers a promising route to generate value‐added chemicals and clean energy. The complex adsorption behavior of 5‐hydroxymethyl furfural (HMF) and hydroxyl ions (OH − ) on the electrocatalyst surface during HMF electrooxidation reaction (HMFOR) necessitates an in‐depth understanding of active sites available for adsorption. Herein, oxygen vacancy (V O ) defects are introduced in NiFe layered double hydroxide (LDH) using Ce dopants to manipulate electronic structure. Synchrotron‐based HE‐XRD and XAS indicate negligible V O in La‐doped NiFe while Ce doping leads to V O defects due to flexible Ce redox (Ce 3+ ↔ Ce 4+ ). The V O ‐rich Ce‐NiFe exhibits higher Faradic efficiency of ≈90% to produce 2,5‐furan dicarboxylic acid (FDCA), far greater than ≈60% for NiFe V O in Ce‐NiFe act as alternative active sites for OH − adsorption, hence reducing adsorption competition for the same metal sites. DFT calculation results corroborate experimental findings by showcasing that the presence of V O in Ce‐NiFe manipulates the adsorption energies and facilitates the chemical adsorption OH − in V O to improve HMFOR. In situ HE‐XRD derived pair distribution function coupled to RMC simulations confirm OH − trapping in V O and HMF adsorption on metal centers as evident by interlayer distance evolution. Taken together, this work showcases routes for dual‐site electrocatalyst design for improved biomass electrooxidation.    

    

* Engineering antibonding orbital occupancy of NiMoO4-supported Ru nanoparticles for enhanced chlorine evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399357409
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.06.023")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399357409"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399357409"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399357409"))][Get cited by]]

OpenAlex: https://openalex.org/W4399357409 (Open access: False)
    
[[https://openalex.org/A5074676938][D. W. Zhang]], [[https://openalex.org/A5001141405][Haiming Gong]], [[https://openalex.org/A5013297039][Tao Liu]], [[https://openalex.org/A5065418938][Yuanyuan Wang]], [[https://openalex.org/A5081369869][Panyong Kuang]], Journal of colloid and interface science. 672(None)] 2024. https://doi.org/10.1016/j.jcis.2024.06.023 
     
Chlorine evolution reaction (CER) is crucial for industrial-scale production of high-purity Cl2. Despite the development of classical dimensionally stable anodes to enhance CER efficiency, the competitive oxygen evolution reaction (OER) remains a barrier to achieving high Cl2 selectivity. Herein, a binder-free electrode, Ru nanoparticles (NPs)-decorated NiMoO4 nanorod arrays (NRAs) supported on Ti foam (Ru-NiMoO4/Ti), was designed for active CER in saturated NaCl solution (pH = 2). The Ru-NiMoO4/Ti electrode exhibits a low overpotential of 20 mV at 10 mA cm−2 current density, a high Cl2 selectivity exceeding 90 %, and robust durability for 90 h operation. The marked difference in Tafel slopes between CER and OER indicates the high Cl2 selectivity and superior reaction kinetics of Ru-NiMoO4/Ti electrode. Further studies reveal a strong metal-support interaction (SMSI) between Ru and NiMoO4, facilitating electron transfer through the Ru–O bridge bond and increasing the Ru 3d–Cl 2p antibonding orbital occupancy, which eventually results in weakened Ru–Cl bonding, promoted Cl desorption, and enhanced Cl2 evolution. Our findings provide new insights into developing electrodes with enhanced CER performance through antibonding orbital occupancy engineering.    

    

* Prediction of Feasibility of Polaronic OER on the (110) Surface of Rutile TiO2  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399359402
:TOPICS: Surface Analysis and Electron Spectroscopy Techniques, X-ray Absorption Spectroscopy, Development of High-Efficiency Photocathodes for Electron Sources
:PUBLICATION_DATE: 2024-06-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cphc.202400523")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399359402"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399359402"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399359402"))][Get cited by]]

OpenAlex: https://openalex.org/W4399359402 (Open access: True)
    
[[https://openalex.org/A5001727106][Hori Pada Sarker]], [[https://openalex.org/A5014248031][Frank Abild‐Pedersen]], [[https://openalex.org/A5067205287][Michal Bajdich]], ChemPhysChem. 25(11)] 2024. https://doi.org/10.1002/cphc.202400523  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cphc.202400523][pdf]])
     
Abstract The front cover artwork is provided by Dr. Hori Pada Sarker from Dr. Frank Abild‐Pedersen's research group at the SLAC National Accelerator Laboratory. The image shows the generation of photoexcited carriers (electrons and holes) and the subsequent formation of hole polaron in rutile TiO 2 during oxygen evolution reaction (OER). Read the full text of the Research Article at 10.1002/cphc.202400060 .    

    

* Self‐Powered Electrochemical CO2 Conversion Enabled by a Multifunctional Carbon‐Based Electrocatalyst and a Rechargeable Zn–Air Battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399359807
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202401766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399359807"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399359807"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399359807"))][Get cited by]]

OpenAlex: https://openalex.org/W4399359807 (Open access: False)
    
[[https://openalex.org/A5072916605][Jingrui Han]], [[https://openalex.org/A5016096115][Lei Shi]], [[https://openalex.org/A5058131010][Huamei Xie]], [[https://openalex.org/A5027039231][Ruilin Song]], [[https://openalex.org/A5058380236][Dan Wang]], [[https://openalex.org/A5075927344][Dong Liu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202401766 
     
Abstract Multifunctional electrocatalysts are required for diverse clean energy‐related technologies (e.g., electrochemical CO 2 reduction reaction (CO 2 RR) and metal–air batteries). Herein, a nitrogen and fluorine co‐doped carbon nanotube (NFCNT) is reported to simultaneously achieve multifunctional catalytic activities for CO 2 RR, oxygen reduction reaction (ORR), and oxygen evolution reaction (OER). Theoretical calculations reveal that the superior multifunctional catalytic activities of NFCNT are attributed to the synergistic effect of nitrogen and fluorine co‐doping to induce charge redistribution and decrease the energy barrier of rate‐determining step for different electrocatalytic reactions. Furthermore, the rechargeable Zn–air battery (ZAB) with NFCNT electrode delivers a high peak power density of 230 mW cm −2 and superior durability over 100 cycles, outperforming the ZAB with Pt/C+RuO 2 based electrodes. More importantly, a self‐driven CO 2 electrolysis unit powered by the as‐assembled ZABs is developed, which achieves 80% CO Faraday efficiency and 60% total energy efficiency. This work provides a new insight into the exploration of highly efficient multifunctional carbon‐based electrocatalysts for novel energy‐related applications.    

    

* Vanadium‐Doped Heterogeneous Bimetallic Phosphides Derived from Layered Double Hydroxides for Saline Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399360497
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202402250")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399360497"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399360497"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399360497"))][Get cited by]]

OpenAlex: https://openalex.org/W4399360497 (Open access: False)
    
[[https://openalex.org/A5078018786][Yixuan Li]], [[https://openalex.org/A5027280914][Jiahui Jiang]], [[https://openalex.org/A5034269122][Qing Wu]], [[https://openalex.org/A5004990899][Yi Feng]], [[https://openalex.org/A5070185260][Zhongxu Chen]], [[https://openalex.org/A5007599353][Guan‐Cheng Xu]], [[https://openalex.org/A5034396732][Li Zhang]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202402250 
     
Abstract The development of energy‐ and time‐saving synthetic methods to prepare bifunctional and high stability catalysts are vital for overall water splitting. Here, V‐doped nickel‐iron hydroxide precursor by etching NiFe foam (NFF) at room temperature with dual chloride solution (“NaCl‐VCl3”), is obtained then phosphating to obtain V‐Ni 2 P‐FeP/NFF as efficient bifunctional (oxygen/hydrogen exchange reaction, OER/HER) electrocatalysts, denoted as NFF(V, Na)‐P. The NFF(V, Na)‐P requires only 185 and 117 mV overpotentials to reach 10 mA cm −2 for OER and HER. When used as a catalyst for water splitting in a full cell, it can be stably sustained for more than 1000 h in alkaline brine electrolysis at both current densities of 100 and 500 mA cm −2 . In situ Raman analyses and density functional theory (DFT) show that the V‐doping‐induced surface remodeling generates hydroxyl oxides as the true catalytic active centers, which not only enhances the reaction kinetics, but also reduces the free energy change in the rate‐determining step. This work provides a cost‐effective substrate self‐derivation method to convert commercial NFF into a powerful catalyst for electrolytic brine, offering a unique route to the development of efficient electrocatalysts for saline water splitting.    

    

* Ceria‐Optimized Oxygen‐Species Exchange in Hierarchical Bimetallic Hydroxide for Electrocatalytic Water Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399360588
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202406682")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399360588"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399360588"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399360588"))][Get cited by]]

OpenAlex: https://openalex.org/W4399360588 (Open access: False)
    
[[https://openalex.org/A5088510694][Li Guo]], [[https://openalex.org/A5016109147][Zhuang Zhang]], [[https://openalex.org/A5058789488][Zhaori Mu]], [[https://openalex.org/A5026905475][Pengfei Da]], [[https://openalex.org/A5019063196][An Li]], [[https://openalex.org/A5086277480][Wei Shen]], [[https://openalex.org/A5047914748][Yichao Hou]], [[https://openalex.org/A5081074386][Pinxian Xi]], [[https://openalex.org/A5055781053][Chun‐Hua Yan]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202406682 
     
Abstract The utilization of rare earth elements to regulate the interaction between catalysts and oxygen‐containing species holds promising prospects in the field of oxygen electrocatalysis. Through structural engineering and adsorption regulation, it is possible to achieve high‐performance catalytic sites with a broken activity‐stability tradeoff. Herein, we fabricate a hierarchical CeO 2 /NiCo hydroxide for electrocatalytic oxygen evolution reaction (OER). This material exhibits superior overpotentials and enhanced stability. Multiple potential‐dependent experiments reveal that CeO 2 promotes oxygen‐species exchange, especially OH − ions, between catalyst and environment, thereby optimizing the redox transformation of hydroxide and the adsorption of oxygen‐containing intermediates during OER. This is attributed to the reduction in the adsorption energy barrier of Ni to *OH facilitated by CeO 2 , particularly the near‐interfacial Ni sites. The less‐damaging adsorbate evolution mechanism and the CeO 2 hierarchical shell significantly enhance the structural robustness, leading to exceptional stability. Additionally, the observed “self‐healing” phenomenon provides further substantiation for the accelerated oxygen exchange. This work provides a neat strategy for the synthesis of ceria‐based complex hollow electrocatalysts, as well as an in‐depth insight into the co‐catalytic role of CeO 2 in terms of oxygen transfer. This article is protected by copyright. All rights reserved    

    

* Block copolymer-mediated synthesis of TiO2/RuO2 nanocomposite for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399362951
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10853-024-09702-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399362951"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399362951"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399362951"))][Get cited by]]

OpenAlex: https://openalex.org/W4399362951 (Open access: True)
    
[[https://openalex.org/A5099024598][Binod Raj KC]], [[https://openalex.org/A5012014778][Dhananjay Kumar]], [[https://openalex.org/A5075515275][Bishnu Prasad Bastakoti]], Journal of materials science. None(None)] 2024. https://doi.org/10.1007/s10853-024-09702-5  ([[https://link.springer.com/content/pdf/10.1007/s10853-024-09702-5.pdf][pdf]])
     
Abstract An amphiphilic block copolymer, poly (styrene-2-polyvinyl pyridine-ethylene oxide), was used as a structure-directing and stabilizing agent to synthesize TiO 2 /RuO 2 nanocomposite. The strong interaction of polymers with metal precursors led to formation of a porous heterointerface of TiO 2 /RuO 2 . It acted as a bridge for electron transport, which can accelerate the water splitting reaction. Scanning electron microscopy, energy-dispersive X -ray spectroscopy, transmission electron microscopy, and X -ray diffraction analysis of TiO 2 /RuO 2 samples revealed successful fabrication of TiO 2 /RuO 2 nanocomposites. The TiO 2 /RuO 2 nanocomposites were used to measure electrochemical water splitting in three-electrode systems in 0.1-M KOH. Electrochemical activities unveil that TiO 2 /RuO 2 -150 nanocomposites displayed superior oxygen evolution reaction activity, having a low overpotential of 260 mV with a Tafel slope of 80 mVdec −1 . Graphical abstract    

    

* Pt Single Atoms on TiO2 Can Catalyze Water Oxidation in Photoelectrochemical Experiments  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399380646
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c03319")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399380646"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399380646"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399380646"))][Get cited by]]

OpenAlex: https://openalex.org/W4399380646 (Open access: False)
    
[[https://openalex.org/A5086631373][Shi Wu]], [[https://openalex.org/A5030917506][Wu Lu]], [[https://openalex.org/A5042616956][Nikita Denisov]], [[https://openalex.org/A5067344132][Zdeňěk Baďura]], [[https://openalex.org/A5060249822][Giorgio Zoppellaro]], [[https://openalex.org/A5072942701][Xiaoyu Yang]], [[https://openalex.org/A5073750190][Patrik Schmuki]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c03319 
     
Photoelectrochemical water splitting on n-type semiconductors is highly dependent on catalysis of the rate-determining reaction of O2 evolution. Conventionally, in electrochemistry and photoelectrochemistry O2 evolution is catalyzed by metal oxide catalysts like IrO2 and RuO2, whereas noble metals such as Pt are considered unsuitable for this purpose. However, our study finds that Pt, in its single-atom form, exhibits exceptional cocatalytic properties for photoelectrochemical water oxidation on a TiO2 photoanode, in contrast to Pt in a nanoparticle form. The decoration of Pt single atoms onto TiO2 yields a remarkable current density of 5.89 mA cm–2 at 1.23 VRHE, surpassing bare TiO2 (or Pt nanoparticle decorated TiO2) by 2.52 times. Notably, this enhancement remains consistent over a wide pH range. By accompanying theoretical work, we assign this significant enhancement to an improved charge transfer and separation efficiency along with accelerated kinetics in the oxygen evolution reaction facilitated by the presence of Pt single atoms on the TiO2 surface.    

    

* Reconstruction of High Entropy Alloys on a Metal–Organic Framework Approaching Active Oxygen Reduction Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399380880
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-06-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.4c01278")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399380880"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399380880"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399380880"))][Get cited by]]

OpenAlex: https://openalex.org/W4399380880 (Open access: False)
    
[[https://openalex.org/A5075257377][Jing Liang]], [[https://openalex.org/A5028912037][Yanling Ma]], [[https://openalex.org/A5001561384][Yanjie Li]], [[https://openalex.org/A5037451400][Wencong Zhang]], [[https://openalex.org/A5068307504][Hao Hu]], [[https://openalex.org/A5011085395][Jie Su]], [[https://openalex.org/A5014141631][Zhenpeng Yao]], [[https://openalex.org/A5029244026][Wenpei Gao]], [[https://openalex.org/A5047036159][Wen Shang]], [[https://openalex.org/A5005057065][Tao Deng]], [[https://openalex.org/A5065507268][Jianbo Wu]], Nano letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.4c01278 
     
High-entropy alloys (HEAs) have garnered considerable attention as promising nanocatalysts for effectively utilizing Pt in catalysis toward oxygen reduction reactions due to their unique properties. Nonetheless, there is a relative dearth of attention regarding the structural evolution of HEAs in response to electrochemical conditions. In this work, we propose a thermal reduction method to synthesize high entropy nanoparticles by leveraging the confinement effect and abundant nitrogen-anchored sites provided by pyrolyzed metal–organic frameworks (MOFs). Notably, the prepared catalysts exhibit enhanced activity accompanied by structural reconstruction during electrochemical activation, approaching 1 order of magnitude higher mass activity compared to Pt/C in oxygen reduction. Atomic-scale structural characterization reveals that abundant defects and single atoms are formed during the activation process, contributing to a significant boost in the catalytic performance for oxygen reduction reactions. This study provides deep insights into surface reconstruction engineering during electrochemical operations, with practical implications for fuel cell applications.    

    

* Fabrication of N and S co-doped lignin-based porous carbon aerogels loaded with FeCo alloys and their application to oxygen evolution and reduction reactions in Zn-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399382547
:TOPICS: Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijbiomac.2024.132961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399382547"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399382547"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399382547"))][Get cited by]]

OpenAlex: https://openalex.org/W4399382547 (Open access: False)
    
[[https://openalex.org/A5058132261][Ying Han]], [[https://openalex.org/A5040599204][Zihao Ma]], [[https://openalex.org/A5045021562][Xing Wang]], [[https://openalex.org/A5069180245][Guangwei Sun]], International journal of biological macromolecules. None(None)] 2024. https://doi.org/10.1016/j.ijbiomac.2024.132961 
     
Zn-air batteries are a highly promising clean energy sustainable conversion technology, and the design of dual-function electrocatalysts with excellent activity and stability is crucial for their development. In this work, FeCo alloy loaded biomass-based N and S co-doped carbon aerogels (FeCo@NS-LCA) were fabricated from chitosan and lignosulfonate-metal chelates via liquid nitrogen pre-frozen synergistic high-temperature carbonization with application in electrocatalytic reactions. The abundant oxygen-containing functional groups on lignosulfonates have a chelating effect on metal ions, which can avoid the aggregation of metal nanoparticles during carbonation and catalysis, facilitating the construction of a nanoconfinement catalytic system with biomass carbon as the domain-limiting body and FeCo nanoparticles as the active sites. FeCo@NS-LCA exhibited catalytic activity (E1/2 = 0.87 V, JL = 5.7 mA cm−2) comparable to the commercial Pt/C in the oxygen reduction reaction (ORR), excellent resistance to methanol toxicity and stability. Meanwhile, the overpotential of oxygen evolution reaction (OER) was 324 mV, close to that of commercial RuO2 catalysts (351 mV). This study utilizes the coordination action of lignosulfonate to provide a novel and environmentally friendly method for the preparation of confined nano-catalysts and provides a new perspective for the high-value utilization of biomass resources.    

    

* Engineering Internal and External Low-Coordination Atoms in Nickel–Organic Framework Nanoarrays to Promote the Electrochemical Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399393923
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c01086")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399393923"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399393923"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399393923"))][Get cited by]]

OpenAlex: https://openalex.org/W4399393923 (Open access: False)
    
[[https://openalex.org/A5066244840][Shun Wang]], [[https://openalex.org/A5066869555][Chong Lin]], [[https://openalex.org/A5021692087][Xuetong Zhang]], [[https://openalex.org/A5061035893][Yisheng Tan]], [[https://openalex.org/A5072077711][B.L. Xiao]], [[https://openalex.org/A5080610686][Yi Zeng]], [[https://openalex.org/A5031344917][Jingyang Tian]], [[https://openalex.org/A5054363687][Minghui Cao]], [[https://openalex.org/A5024062892][Yuanping Jiang]], [[https://openalex.org/A5050344464][Min Li]], Inorganic chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c01086 
     
Monometallic nickel–organic frameworks based on a carboxylated ligand [2,6-naphthalenedicarboxylic acid (Ni-NDC)] have abundant and uniformly distributed single-atom Ni sites, enabling superior oxygen evolution reaction (OER) activity. In theory, most of the Ni atoms inside Ni-NDC microcrystals are coordinatively saturated except for the surface. Therefore, there are no accessible low-coordination atoms (LCAs) as electrocatalytic sites for the OER. One effective way is to expose more LCAs by preparing self-supporting Ni-NDC nanoarrays (Ni-NDC NAs) with hierarchical secondary structural units. Another effective method is to create more internal LCAs by removing partial ligands or coordination atoms attached to the Ni atoms. Herein, by combining the two strategies, we engineered LCAs in the interior and exterior of Ni-NDC to synergistically accelerate the OER. In brief, ultrathick "brick-like" Ni-NDC NAs were first prepared with dissolution and coordination effects of NDC on self-sacrificial templates of "agaric-like" nickel hydroxide nanoarrays [Ni(OH)2 NAs]. Subsequently, dual-coordinated NDC was partially replaced by monocoordinated 2-naphthoic acid (NA). The Ni-NDC NAs were further tailed into ultrathin "liner leaf-like" nanoneedle arrays (LCAs-Ni-NDC NAs). As a consequence, the LCAs-Ni-NDC NAs have more internal and external LCAs, which can deliver an OER performance that is superior to that of Ni-NDC NAs.    

    

* Tuning the high-entropy perovskite as efficient and reliable electrocatalysts for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399411629
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02680b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399411629"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399411629"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399411629"))][Get cited by]]

OpenAlex: https://openalex.org/W4399411629 (Open access: True)
    
[[https://openalex.org/A5030068214][Ruirui Wei]], [[https://openalex.org/A5064379315][Gaoliang Fu]], [[https://openalex.org/A5016494270][Hui Qi]], [[https://openalex.org/A5027492529][Hewei Liu]], RSC advances. 14(26)] 2024. https://doi.org/10.1039/d4ra02680b 
     
This work reports a high-entropy perovskite La 0.3 Sr 0.7 (CrMnFeCoNi) 0.2 O 3 as a high-performance OER electrocatalyst. Sr doping induces the formation of higher-valence Cr 6+ , Mn 4+ , Fe 4+ , Co 4+ and Ni 3+ responsible for the excellent OER activity.    

    

* 3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399432345
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399432345"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399432345"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399432345"))][Get cited by]]

OpenAlex: https://openalex.org/W4399432345 (Open access: True)
    
[[https://openalex.org/A5048372554][Chao Shuai]], [[https://openalex.org/A5048610528][Chunyang Kong]], [[https://openalex.org/A5006083213][Y.S. Li]], [[https://openalex.org/A5035061957][Liang Zhang]], [[https://openalex.org/A5049238095][Qi Chen]], [[https://openalex.org/A5074381132][Zunli Mo]], RSC advances. 14(26)] 2024. https://doi.org/10.1039/d4ra02280g 
     
3D flower-like bimetallic MOF (F-Ni1Co4-BTC) was successfully designed and synthesized and exhibited excellent OER activity. Moreover, fixed on the surface of a carbon cloth, F-Ni1Co4-BTC realized high OER activity and long-term durability.    

    

* Review for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399455932
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399455932"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399455932"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399455932"))][Get cited by]]

OpenAlex: https://openalex.org/W4399455932 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v1/review1 
     
No abstract    

    

* Review for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399455934
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-05-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399455934"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399455934"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399455934"))][Get cited by]]

OpenAlex: https://openalex.org/W4399455934 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v1/review2 
     
No abstract    

    

* Review for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399455937
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-05-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399455937"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399455937"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399455937"))][Get cited by]]

OpenAlex: https://openalex.org/W4399455937 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v2/review1 
     
No abstract    

    

* Decision letter for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399456113
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-05-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399456113"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399456113"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399456113"))][Get cited by]]

OpenAlex: https://openalex.org/W4399456113 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v1/decision1 
     
No abstract    

    

* Decision letter for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399456174
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-05-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399456174"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399456174"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399456174"))][Get cited by]]

OpenAlex: https://openalex.org/W4399456174 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v2/decision1 
     
No abstract    

    

* Unraveling the Oxidation Kinetics Through Electronic Structure Regulation of MnCo2O4.5@Ni3S2 p–n Junction for Urea‐Assisted Electrocatalytic Activity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399462204
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202311548")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399462204"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399462204"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399462204"))][Get cited by]]

OpenAlex: https://openalex.org/W4399462204 (Open access: False)
    
[[https://openalex.org/A5017136680][Sangeeta Adhikari]], [[https://openalex.org/A5043194301][Stephan N. Steinmann]], [[https://openalex.org/A5066078135][Maheswari Arunachalam]], [[https://openalex.org/A5074976953][Soon Hyung Kang]], [[https://openalex.org/A5018707438][Do‐Heyoung Kim]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202311548 
     
Abstract A promising strategy to boost electrocatalytic performance is via assembly of hetero‐nanostructured electrocatalysts that delivers the essential specific surface area and also active sites by lowering the reaction barrier. However, the challenges associated with the intricate designs and mechanisms remain underexplored. Therefore, the present study constructs a p–n junction in a free‐standing MnCo 2 O 4.5 @Ni 3 S 2 on Ni‐Foam. The space‐charge region's electrical characteristics is dramatically altered by the formed p–n junction, which enhances the electron transfer process for urea‐assisted electrocatalytic water splitting (UOR). The optimal MnCo 2 O 4.5 @Ni 3 S 2 electrocatalyst results in greater oxygen evolution reactivity (OER) than pure systems, delivering an overpotential of only 240 mV. Remarkably, upon employing as UOR electrode the required potential decreases to 30 mV. The impressive performance of the designed catalyst is attributed to the enhanced electrical conductivity, greater number of electrochemical active sites, and improved redox activity due to the junction interface formed between p‐MnCo 2 O 4.5 and n‐Ni 3 S 2 . There are strong indications that the in situ formed extreme‐surface NiOOH, starting from Ni 3 S 2, boosts the electrocatalytic activity, i.e., the electrochemical surface reconstruction generates the active species. In conclusion, this work presents a high‐performance p–n junction design for broad use, together with a viable and affordable UOR electrocatalyst.    

    

* ZIF‐Co3O4@ZIF‐Derived Urchin‐Like Hierarchically Porous Carbon as Efficient Bifunctional Oxygen Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399490831
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/open.202400057")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399490831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399490831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399490831"))][Get cited by]]

OpenAlex: https://openalex.org/W4399490831 (Open access: True)
    
[[https://openalex.org/A5041880317][Lingling Zhang]], [[https://openalex.org/A5074049940][Xiaokang Wang]], [[https://openalex.org/A5046187929][Chong Gong]], [[https://openalex.org/A5001980743][Wanying Sun]], [[https://openalex.org/A5034760240][Zihan Lu]], ChemistryOpen. None(None)] 2024. https://doi.org/10.1002/open.202400057 
     
Abstract Co 3 O 4 nanoparticles were sandwiched into interlayers between ZIF‐8 and ZIF‐67 to form ZIF‐Co 3 O 4 @ZIF precursors. Pyrolysis of ZIF‐Co 3 O 4 @ZIF yielded an urchin‐like hierarchically porous carbon (Co@CNT/NC), the thorns of which were carbon nanotubes embedded Co nanoparticles. With large specific surface area and hierarchically porous structure, as‐prepared Co@CNT/NC exhibited excellent bifunctional oxygen electrocatalytic performances. It has good ORR performance with E 1/2 of 0.85 V, which exceeds the Pt/C half‐wave potential (E 1/2 =0.83 V). In addition, Co@CNT/NC has an OER performance close to that of RuO 2 . To further demonstrate the effect of Co modifying on the properties, the samples were subjected to acid washing treatment. Co‐based nanoparticles were proved to After acid washing, there was obvious loss of Co particles in Co@CNT/NC, resulting in poor oxygen electrocatalysis. So, the pyrolysis products of ZIF‐8‐Co 3 O 4 @ZIF‐67 retained large specific surface area and porous structure can be retained, and on the other hand, the carbon tube structure and original polyhedron framework. Besides, existence of Co nanoparticle@carbon nanotube provided more active sites and improved the ORR and OER performances.    

    

* Application of machine learning to discover new intermetallic catalysts for the hydrogen evolution and the oxygen reduction reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399336542
:TOPICS: Accelerating Materials Innovation through Informatics, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cy00491d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399336542"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399336542"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399336542"))][Get cited by]]

OpenAlex: https://openalex.org/W4399336542 (Open access: False)
    
[[https://openalex.org/A5079538646][Carmen Martínez-Alonso]], [[https://openalex.org/A5002697621][Valentín Vassilev-Galindo]], [[https://openalex.org/A5043795015][Benjamin M. Comer]], [[https://openalex.org/A5014248031][Frank Abild‐Pedersen]], [[https://openalex.org/A5023868918][Kirsten T. Winther]], [[https://openalex.org/A5068957187][J. Llorca]], Catalysis science & technology. None(None)] 2024. https://doi.org/10.1039/d4cy00491d 
     
The adsorption energies for hydrogen, oxygen, and hydroxyl were calculated by means of density functional theory on the lowest energy surface of 24 pure metals and 332 binary intermetallic compounds...    

    

* Enhanced Photocatalytic Hydrogen Evolution of In2S3 by Decorating In2O3 with Rich Oxygen Vacancies  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399331742
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c00720")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399331742"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399331742"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399331742"))][Get cited by]]

OpenAlex: https://openalex.org/W4399331742 (Open access: False)
    
[[https://openalex.org/A5017555330][Changxue Dong]], [[https://openalex.org/A5078326314][Qiuyan Chen]], [[https://openalex.org/A5019316738][Xin Deng]], [[https://openalex.org/A5090166634][Lan Jiang]], [[https://openalex.org/A5004859642][Tianli Han]], [[https://openalex.org/A5086036922][Yufeng Zhou]], [[https://openalex.org/A5064703123][Jinwei Chen]], [[https://openalex.org/A5005949841][Ruilin Wang]], Inorganic chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c00720 
     
The hydrogen (H2) evolution rates of photocatalysts suffer from weak oxidation and reduction ability and low photogenerated charge carrier separation efficiency. Herein, by combining band-gap structure optimization and vacancy modulation through a one-step hydrothermal method, In2O3 containing oxygen vacancy (Ov/In2O3) is simply introduced into In2S3 to promote photocatalytic hydrogen evolution. Specifically, the change in the sulfur source ratio can induce the coexistence of Ov/In2O3 and In2S3 in a high-temperature hydrothermal process. Under light irradiation, In2S3@Ov/In2O3-0.1 nanosheets hold a remarkable average H2 evolution rate up to 4.04 mmol g–1 h–1, which is 32.14, 11.91, and 2.25-fold better than those of pristine In2S3, In2S3@Ov/In2O3-0.02, and In2S3@Ov/In2O3-0.25 nanosheets, respectively. The ultraviolet–visible (UV–vis) diffuse reflectance and photoluminescence (PL) spectra reveal that the formation of Ov/In2O3 in In2S3 optimizes the band-gap structure and accelerates the migration of the photogenerated charge carrier of In2S3@Ov/In2O3-x nanosheets, respectively. Both the enhancement of oxidation and reduction ability and photogenerated charge carrier separation ability are responsible for the remarkable improvement in photocatalytic H2 evolution performance. This work provides a new strategy to prepare a composite of metal sulfide and metal oxide through a one-step hydrothermal method.    

    

* Biochar Made from Luffa Cylindrica and Applied as Bifunctional Electrocatalyst in Zn-Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399343780
:TOPICS: Catalytic Reduction of Nitro Compounds, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4853912")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399343780"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399343780"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399343780"))][Get cited by]]

OpenAlex: https://openalex.org/W4399343780 (Open access: False)
    
[[https://openalex.org/A5099018522][Natalia Tsoukala]], [[https://openalex.org/A5055031799][Antonios N. Papadopoulos]], [[https://openalex.org/A5093123663][Vasiliki Premeti]], [[https://openalex.org/A5099018523][Alexandros K. Bikogiannakis]], [[https://openalex.org/A5059967348][Eftychia Martino]], [[https://openalex.org/A5049614796][Eleana Kordouli]], [[https://openalex.org/A5000371803][Κaterina Govatsi]], [[https://openalex.org/A5017616023][Ioannis D. Manariotis]], [[https://openalex.org/A5072926317][Georgios Kyriakou]], [[https://openalex.org/A5004875775][Dionissios Mantzavinos]], [[https://openalex.org/A5081631223][Panagiotis Lianos]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4853912 
     
Biochar has been prepared by pyrolysis of Luffa Cylindrica (the vegetable sponge produced by Luffa Aegiptiaca) and activated by mixing with KOH and a second pyrolysis step. Non-activated and activated biochar have both been structurally and then electrochemically characterized to record their differences and assess their suitability as bifunctional oxygen reduction and oxygen evolution reaction electrocatalysts in Zn-air batteries. Non activated biochar carries several functional groups; however, the activation procedure led to a material with mainly O and Mg groups. Biochar activation improved its electrocatalytic properties, but both activated and non-activated luffa biochar were functional as bifunctional electrocatalysts to a satisfactory degree. This is justified by the fact that both carried a large percentage of carbon and graphitic carbon. The advantage of the non-activated biochar versus the activated biochar was its variety of functional groups while that of the activated biochar was its large specific surface area.    

    

* Nanostructured Mnmoo4 as a Trifunctional Electrocatalyst for Overall Water Splitting and Co2 Reduction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399337243
:TOPICS: Ammonia Synthesis and Electrocatalysis, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4853666")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399337243"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399337243"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399337243"))][Get cited by]]

OpenAlex: https://openalex.org/W4399337243 (Open access: False)
    
[[https://openalex.org/A5071460244][Neda Sadat Barekati]], [[https://openalex.org/A5040890176][Eshagh Irandoost]], [[https://openalex.org/A5059917325][Hossein Farsi]], [[https://openalex.org/A5012599798][Elahe Dana]], [[https://openalex.org/A5099016446][Safiye Kolangikhah]], [[https://openalex.org/A5087760602][Shokufeh Moghiminia]], [[https://openalex.org/A5057292515][Alireza Farrokhi]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4853666 
     
Electrochemical water splitting and CO2 reduction are important processes to produce hydrogen and low–carbon fuels as renewable energy sources. Here, nanostructured MnMoO4, prepared by the reflux precipitation method, was investigated as a trifunctional electrocatalyst for overall water splitting and CO2 reduction reactions. Using a combination of diffuse reflectance spectroscopy and electrochemical impedance spectroscopy results, a direct band gap of 3.05 eV was obtained experimentally for the prepared MnMoO4. An overpotential of 0.36 V at a current density of 5 mA cm-2 and a Tafel slope of 58 mV dec-1 were obtained for the oxygen evolution reaction. At a current density of 3 mA cm-2, overpotentials of 0.39 V and 0.58 V were achieved in the absence and presence of CO2 bubbling into a 0.1 M KOH solution, respectively, emphasizing the poisoning effect of CO2 reduction intermediates for the hydrogen evolution reaction. Based on the obtained results, MnMoO4 could be a promising electrocatalyst for water splitting and CO2 reduction reactions.    

    

* Waxberry-Like Hydrophilic Co-Doped Znfe2o4 as Bifunctional Electrocatalysts for Water Splittingwaxberry-Like Hydrophilic Co-Doped Znfe2o4 as Bifunctional Electrocatalysts for Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399347211
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4853910")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399347211"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399347211"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399347211"))][Get cited by]]

OpenAlex: https://openalex.org/W4399347211 (Open access: False)
    
[[https://openalex.org/A5062457169][Xiao Lyu]], [[https://openalex.org/A5026237491][Yongbin Hu]], [[https://openalex.org/A5011741860][Yun Han]], [[https://openalex.org/A5077211208][Xuning Li]], [[https://openalex.org/A5090372525][Yu Q]], [[https://openalex.org/A5064332635][Bin Wen]], [[https://openalex.org/A5027524424][Xin Zhao]], [[https://openalex.org/A5037548250][Qi Dong]], [[https://openalex.org/A5068612585][Aijun Du]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4853910 
     
The development of bifunctional electrocatalysts is challenging but desirable for the scale-up applications of water splitting. Nowadays transition metal oxides (TMOs) are considered as the promising electrocatalysts due to their low cost, structural flexibility and stability, however, their electrocatalytic activities are eager to be improved. Here, we synthesized waxberry-like hydrophilic Co-doped ZnFe2O4 electrocatalysts as bifunctional electrocatalysts for water splitting. Due to the enhanced active sites by morphology regulation and metallic doping strategy, the spinel ZFO-Co0.5 electrocatalyst exhibits excellent catalytic activities both on oxygen evolution reaction (OER) and hydrogen evolution reaction (HER). It exhibits a remarkable low OER overpotential of 220 mV and a Tafel slope of 28.2 mV dec-1, surpassing the performance of commercial IrO2 electrocatalyst. Meanwhile, it achieves a low overpotential of 73 mV with the Tafel slope of 87 mV dec -1 for HER. In addition, water-splitting performance of ZFO-Co0.5||ZFO-Co0.5 surpasses that of commercial IrO2||Pt/C. Our work reveals that the hydrophilic morphology regulation combined with metallic doping strategy is a facile and effective approach to synthesize spinel TMOs as excellent bifunctional electrocatalyst for water splitting.    

    

* On the physiology of high-altitude flight and altitudinal migration in birds  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399322452
:TOPICS: Genetic and Physiological Adaptations to High-Altitude Environments, Avian Ecology and Climate Change Impacts, Climate Change and Variability Research
:PUBLICATION_DATE: 2024-06-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/icb/icae062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399322452"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399322452"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399322452"))][Get cited by]]

OpenAlex: https://openalex.org/W4399322452 (Open access: False)
    
[[https://openalex.org/A5042785646][Catherine M. Ivy]], [[https://openalex.org/A5071944605][Jessie L. Williamson]], Integrative and comparative biology. None(None)] 2024. https://doi.org/10.1093/icb/icae062 
     
Abstract Many bird species fly at high altitudes for short periods and/or shift seasonally in altitude during migration, but little is known about the physiology of these behaviors. Transient high-altitude flight, or short-term flight at extreme altitudes, is a strategy used by lowland-native birds, often in the absence of topographic barriers. Altitudinal migration, or seasonal roundtrip movement in altitude between the breeding and non-breeding seasons, is a form of migration that occurs as a regular part of the annual cycle and results in periods of seasonal residency at high altitudes. Despite their nuanced differences, these two behaviors share a common challenge: Exposure to reduced oxygen environments during at least part of the migratory journey. In this perspective piece, we compare what is known about the physiology of oxygen transport during transient high-altitude flight and altitudinal migration by highlighting case studies and recent conceptual advances from work on captive and wild birds. We aim to open avenues for integrative research on the ecology, evolution, and physiology of high-flying and mountain-climbing birds.    

    

* Environment-Driven Variability in Absolute Band Edge Positions and Work Functions of Reduced Ceria  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399367657
:TOPICS: Catalytic Nanomaterials, Emergent Phenomena at Oxide Interfaces, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c05053")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399367657"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399367657"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399367657"))][Get cited by]]

OpenAlex: https://openalex.org/W4399367657 (Open access: True)
    
[[https://openalex.org/A5043608187][Xingfan Zhang]], [[https://openalex.org/A5082037593][Christopher S. Blackman]], [[https://openalex.org/A5056443409][Robert G. Palgrave]], [[https://openalex.org/A5085247610][Sobia Ashraf]], [[https://openalex.org/A5074215000][Avishek Dey]], [[https://openalex.org/A5007924175][Matthew O. Blunt]], [[https://openalex.org/A5073568638][Xu Zhang]], [[https://openalex.org/A5027996639][Taifeng Liu]], [[https://openalex.org/A5050790072][Shijia Sun]], [[https://openalex.org/A5025820671][Lei Zhu]], [[https://openalex.org/A5034641351][Jingcheng Guan]], [[https://openalex.org/A5075439339][You Lü]], [[https://openalex.org/A5033050680][Thomas W. Keal]], [[https://openalex.org/A5060187040][John Buckeridge]], [[https://openalex.org/A5042572313][C. Richard A. Catlow]], [[https://openalex.org/A5017393061][Alexey A. Sokol]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c05053  ([[https://pubs.acs.org/doi/pdf/10.1021/jacs.4c05053][pdf]])
     
The absolute band edge positions and work function (Φ) are the key electronic properties of metal oxides that determine their performance in electronic devices and photocatalysis. However, experimental measurements of these properties often show notable variations, and the mechanisms underlying these discrepancies remain inadequately understood. In this work, we focus on ceria (CeO2), a material renowned for its outstanding oxygen storage capacity, and combine theoretical and experimental techniques to demonstrate environmental modifications of its ionization potential (IP) and Φ. Under O-deficient conditions, reduced ceria exhibits a decreased IP and Φ with significant sensitivity to defect distributions. In contrast, the IP and Φ are elevated in O-rich conditions due to the formation of surface peroxide species. Surface adsorbates and impurities can further augment these variabilities under realistic conditions. We rationalize the shifts in energy levels by separating the individual contributions from bulk and surface factors, using hybrid quantum mechanical/molecular mechanical (QM/MM) embedded-cluster and periodic density functional theory (DFT) calculations supported by interatomic-potential-based electrostatic analyses. Our results highlight the critical role of on-site electrostatic potentials in determining the absolute energy levels in metal oxides, implying a dynamic evolution of band edges under catalytic conditions.    

    

* Electrochemically regulating COD/TN ratio of aged landfill leachate via rapid chlorine-mediated ammonia oxidation with RuO2-IrO2/Ti anode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399327555
:TOPICS: Occurrence and Health Effects of Drinking Water Disinfection By-Products, Advanced Oxidation Processes for Water Treatment, Microbial Nitrogen Cycling in Wastewater Treatment Systems
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jece.2024.113255")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399327555"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399327555"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399327555"))][Get cited by]]

OpenAlex: https://openalex.org/W4399327555 (Open access: False)
    
[[https://openalex.org/A5017712129][Haoran Sun]], [[https://openalex.org/A5013038112][Chen Wang]], [[https://openalex.org/A5012645891][Hongtao Liu]], [[https://openalex.org/A5020423899][Yucheng Liu]], [[https://openalex.org/A5052600259][Yufan Chen]], [[https://openalex.org/A5067279934][Lizhang Wang]], Journal of environmental chemical engineering. 12(4)] 2024. https://doi.org/10.1016/j.jece.2024.113255 
     
Electrochemical oxidation process was employed to regulate the ratio of chemical oxygen demand to total nitrogen (COD/TN ratio) of aged landfill leachate, aiming to meet the requirement of biological treatment. The results indicate that the ammonia nitrogen can be rapidly removed through electrogenerated chlorine radicals over a typical chlorine evolution RuO2-IrO2/Ti anode. The increased input current and decreased flow rate are beneficial to COD/TN ratio improvement, and COD/TN ratio can be increased to more than 16 at 1000 mA (input current) and 0.3 L/h (flow rate). According to the obtained experimental data, we present a strategy for COD/TN ratio increase: (i) determining the COD/TN ratio balance coefficient (B) of aged landfill leachate, and selecting the anode with COD/TN ratio adjustment coefficient (TN) > B, where TN represents the ability to regulate COD/TN ratio, and B represents the specific TN to keep the same COD/TN ratio; (ii) performing the wastewater treatment experiments at different control parameters during electrochemical process; (iii) calculating the k of control parameter sensitivity curves to achieve different tolerance abilities, and further preferentially regulating the reaction process to high average current efficiency (ACE) of ammonia nitrogen and low ACE of COD. This work validates that the electrochemical process can increase the COD/TN ratio together with enhancing the biodegradability of such refractory wastewater, and also provides an effective tool for regulation of the COD/TN ratio via complete ammonia oxidation.    

    

* A Male with Acute Dermonecrosis over the Right Flank  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399320463
:TOPICS: Snake Venom Evolution and Toxinology, Biology and Pathology of Keratins and Related Disorders, Cutaneous Manifestations of COVID-19: A Comprehensive Review
:PUBLICATION_DATE: 2024-06-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.4103/idoj.idoj_776_23")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399320463"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399320463"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399320463"))][Get cited by]]

OpenAlex: https://openalex.org/W4399320463 (Open access: True)
    
[[https://openalex.org/A5084011114][Vijayasankar Palaniappan]], [[https://openalex.org/A5090109060][Anusuya Sadhasivamohan]], [[https://openalex.org/A5086436082][Kaliaperumal Karthikeyan]], Indian dermatology online journal. None(None)] 2024. https://doi.org/10.4103/idoj.idoj_776_23 
     
A 42-year-old farmer presented with an acute onset painful red raised lesion over the right side of his abdomen. While working in the paddy fields, the patient experienced a spider bite 3 days before the onset of this complaint. Initially, he had pain for a day, followed by redness and blister formation that eventually ruptured. He did not have any systemic complaints. On cutaneous examination, he had a single necrotic boggy plaque over the right flank. A linear streak of erythema was noted emanating from the superior aspect of the ovoid lesion [Figure 1a]. Dermoscopy showed a central bluish-black crust outlined by an irregular non-homogeneous reddish blue area in an erythematous background [Figure 2]. There was no regional lymphadenopathy.Figure 1: (a) A single oval erythematous boggy plaque of size 9 cm × 7 cm with a central necrosis over the right flank, with a linear streak of erythema emanating from the superior aspect of the ovoid lesion; (b-f) Follow-up on day 5, day 10, day 16, day 30, and day 52Figure 2: A central bluish-black crust outlined by an irregular non-homogeneous reddish blue area in an erythematous backgroundThe vital parameters, hemogram, liver function tests, renal function tests, bleeding time, and clotting time were found to be normal. What is the diagnosis? Answer: Cutaneous loxoscelism with dermonecrosis Discussion The diagnosis of cutaneous arachnidism (loxoscelism) with dermonecrosis was made based on the positive history of spider bite, clinical presentation, and dermoscopy. The patient was managed with topical collagenase ointment, oral acetaminophen, a prophylactic antibiotic with intravenous ceftazidime twice daily, and oral prednisolone 0.4 mg/kg/day for 7 days. The patient was periodically followed up [Figures 1b-f]. The lesion healed with a hypertrophic scar. Necrotic arachnidism is a cutaneous reaction to toxins released from the venoms of spider bites. Loxoscelism is a term used for spider bites associated with loxosceles species.[1] Cutaneous loxoscelism is the most common presentation of loxoscelism. Systemic involvement with fever, myalgia, and hemolytic anemia can rarely occur.[1] The differences between cutaneous and systemic loxoscelism are mentioned in Table 1.[2] The toxins responsible for cutaneous loxoscelism are enzymes sphingomyelinase-D, phospholipase-D, alkaline phosphatase, hyaluronidase, esterase, and proteases.Table 1: Differences between cutaneous and systemic loxoscelism.Clinically cutaneous loxoscelism presents as a painful localized bluish-gray halo surrounding the bite site. This is followed by a vesicle or cyanotic pustule with surrounding erythema, edema, and purpura. Later, a central ischemic pallor with a dry, crusted, necrotic lesion with surrounding erythema, vesiculation, and pustulation is noted. The lesion spreads rapidly and extensively, with the eschar shedding and leaving erosions and ulcers. The affected site may take up to 6 months to heal with or without scarring. The pathognomic lesional description is a classical red, white, and blue sign. The red depicts erythema, followed by a palisaded white ring of vasoconstriction due to the toxin, and a central blue necrotic zone.[1] The most common affected sites are the proximal part of the lower extremity and the distal part of the upper extremity. Lymphedema can occur as a complication to loxoscelism.[3] The conditions that mimic cutaneous loxoscelism are arthropod bites, erysipelas, ecthyma, cellulitis, urticaria and angioedema, burns, vasculitis, pyoderma gangrenosum, cutaneous diphtheroid, anthrax, and cutaneous malignancies.[4,5] There are no standard guidelines for the management of cutaneous loxoscelism. Spider bites generally require rest to the involved part, analgesia, sterile dressing, and periodic follow-up. Cutaneous loxoscelism with dermonecrosis may require systemic steroids, prophylactic antibiotics, vasodilators, dapsone, tetracycline, heparin, and hyperbaric oxygen therapy.[4,6] Systemic involvement, which develops anytime within 12–36 hours after the bite, requires vigorous hemodynamic management.[2] Antivenin provides beneficial effects like prevention of necrosis, edema, and ecchymoses when administered as early as possible.[7] A high index of suspicion should be kept in mind to diagnose this entity in patients presenting with acute onset ulceration. A proper history taking and clinical examination holds the key to clinching the diagnosis. The aim of reporting this case is to emphasize the clinical evolution of cutaneous loxoscelism, which may pose a diagnostic dilemma. Declaration of patient consent The authors certify that they have obtained all appropriate patient consent forms. In the form the patient(s) has/have given his/her/their consent for his/her/their images and other clinical information to be reported in the journal. The patients understand that their names and initials will not be published and due efforts will be made to conceal their identity, but anonymity cannot be guaranteed. Financial support and sponsorship Nil. Conflicts of interest There are no conflicts of interest.    

    
