#+TITLE: water splitting
Description: water splitting papers
Created on Wed Apr  3 00:43:42 2024

Found 42 results from 2024-03-27 to 2024-04-03
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Low-Overpotential Rechargeable Na–CO2 Batteries Enabled by an Oxygen-Vacancy-Rich Cobalt Oxide Catalyst  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393183540
:TOPICS: Aqueous Zinc-Ion Battery Technology, Lithium-ion Battery Technology, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c01682")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393183540"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393183540"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393183540"))][Get cited by]]

OpenAlex: https://openalex.org/W4393183540 (Open access: False)
    
[[https://openalex.org/A5057620071][Zhi Zheng]], [[https://openalex.org/A5006411143][Xiaobo Zheng]], [[https://openalex.org/A5043984043][Jiazhao Wang]], [[https://openalex.org/A5026984704][Qi Zhang]], [[https://openalex.org/A5032852285][Peng Li]], [[https://openalex.org/A5011065863][Can Li]], [[https://openalex.org/A5006873671][Qinfen Gu]], [[https://openalex.org/A5085624118][Wei Li]], [[https://openalex.org/A5017208832][Konstantin Konstantinov]], [[https://openalex.org/A5001301417][Weishen Yang]], [[https://openalex.org/A5019065325][Yuan Chen]], [[https://openalex.org/A5028273524][Jiazhao Wang]], ACS applied materials & interfaces (Print). None(None)] 2024. https://doi.org/10.1021/acsami.4c01682 
     
No abstract    

    

* Probing Surface Transformations of Lanthanum Nickelate Electrocatalysts during Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393187140
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c00863")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393187140"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393187140"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393187140"))][Get cited by]]

OpenAlex: https://openalex.org/W4393187140 (Open access: False)
    
[[https://openalex.org/A5063384458][Yi‐Hsuan Wu]], [[https://openalex.org/A5093893767][Marcel Janák]], [[https://openalex.org/A5005303303][Paula M. Abdala]], [[https://openalex.org/A5057560048][Camelia N. Borca]], [[https://openalex.org/A5027590901][Anna Wach]], [[https://openalex.org/A5085197921][Agnieszka M. Kierzkowska]], [[https://openalex.org/A5083773986][Felix Donat]], [[https://openalex.org/A5010118109][Thomas Huthwelker]], [[https://openalex.org/A5079220919][Denis A. Kuznetsov]], [[https://openalex.org/A5024347042][Christoph R. Müller]], Journal of the American Chemical Society (Print). None(None)] 2024. https://doi.org/10.1021/jacs.4c00863 
     
No abstract    

    

* Cold-plasma activation converting conductive agent in spent Li-ion batteries to bifunctional oxygen reduction/evolution electrocatalyst for zinc-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393188914
:TOPICS: Lithium-ion Battery Technology, Battery Recycling and Rare Earth Recovery, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.169")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393188914"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393188914"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393188914"))][Get cited by]]

OpenAlex: https://openalex.org/W4393188914 (Open access: True)
    
[[https://openalex.org/A5035801000][Yifan Liu]], [[https://openalex.org/A5031191155][Xiangqun Zhuge]], [[https://openalex.org/A5046775442][Tong Liu]], [[https://openalex.org/A5075433170][Zhenyue Luo]], [[https://openalex.org/A5058330685][Kun Luo]], [[https://openalex.org/A5039774761][Yibing Li]], [[https://openalex.org/A5001008654][Yurong Ren]], [[https://openalex.org/A5041985676][Maryam Bayati]], [[https://openalex.org/A5057337284][Xiaoteng Liu]], Journal of colloid and interface science (Print). None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.169 
     
No abstract    

    

* Enhanced bifunctional oxygen electrochemical catalytic performance using La-doped CoFe2O4 spinel supported by 3D-G for Zn-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393189491
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.03.019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393189491"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393189491"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393189491"))][Get cited by]]

OpenAlex: https://openalex.org/W4393189491 (Open access: False)
    
[[https://openalex.org/A5035717978][Yinggang Sun]], [[https://openalex.org/A5074203767][Tingwei Zhang]], [[https://openalex.org/A5001293486][Peng Sun]], [[https://openalex.org/A5024135429][Jigang Wang]], [[https://openalex.org/A5001977253][Wenjie Duan]], [[https://openalex.org/A5032303899][Yanqiong Zhuang]], [[https://openalex.org/A5025178851][Likai Wang]], [[https://openalex.org/A5071554002][Guohong Liu]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.03.019 
     
No abstract    

    

* Selective electrooxidation of 5-hydroxymethylfurfural at low working potentials promoted by 3D hierarchical Cu(OH)2@Ni3Co1-layered double hydroxide architecture with oxygen vacancies  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393193041
:TOPICS: Materials for Electrochemical Supercapacitors, Lithium-ion Battery Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra00769g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393193041"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393193041"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393193041"))][Get cited by]]

OpenAlex: https://openalex.org/W4393193041 (Open access: True)
    
[[https://openalex.org/A5009194583][Wei Qian]], [[https://openalex.org/A5085745145][Yanqi Xu]], [[https://openalex.org/A5044523773][Cunjun Li]], [[https://openalex.org/A5079747209][Zhu Wang]], [[https://openalex.org/A5074919112][Hai Wang]], [[https://openalex.org/A5016518215][Xin Yu Wang]], [[https://openalex.org/A5078754143][Aimiao Qin]], [[https://openalex.org/A5021825405][Haiqing Qin]], [[https://openalex.org/A5007125266][Linjiang Wang]], RSC advances. 14(14)] 2024. https://doi.org/10.1039/d4ra00769g  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ra/d4ra00769g][pdf]])
     
An effective and stable catalyst with 3D hierarchical architecture was synthesized by electrodepositing Ni 3 Co 1 -LDH nanosheets on copper foam-supported Cu(OH) 2 nanorods. The catalyst can be used to prepare FDCA continuously, showing great potential in the electrochemical conversion of biomass.    

    

* Selenium-doped mixed metal oxide nanoparticles decorated on g-C3N4 and MXenes sheets as promising bifunctional Oxygen electrocatalyst for rechargeable Zn-air battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393194974
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3se01419c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393194974"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393194974"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393194974"))][Get cited by]]

OpenAlex: https://openalex.org/W4393194974 (Open access: False)
    
[[https://openalex.org/A5094250602][Mohaddeseh Rastgoo]], [[https://openalex.org/A5012585666][Ali Esfandiar]], [[https://openalex.org/A5027051019][Valeri P. Tolstoy]], Sustainable energy & fuels. None(None)] 2024. https://doi.org/10.1039/d3se01419c 
     
Designing bifunctional electrocatalyst to conduct appropriate oxygen reduction reaction (ORR) and oxy-gen evolution reaction (OER) for high performance zinc-air battery is one of the most important challeng-es for sustainable energy...    

    

* 1D Monoclinic IrxRu1‐xO2 Solid Solution with Ru‐Enhanced Electrocatalytic Activity for Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393198977
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202402226")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393198977"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393198977"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393198977"))][Get cited by]]

OpenAlex: https://openalex.org/W4393198977 (Open access: False)
    
[[https://openalex.org/A5008126805][Keyang Qin]], [[https://openalex.org/A5053287310][Hao Yu]], [[https://openalex.org/A5021658618][Wenxiang Zhu]], [[https://openalex.org/A5087224097][Yunjie Zhou]], [[https://openalex.org/A5015760821][Zhiyong Guo]], [[https://openalex.org/A5065985607][Qi Shao]], [[https://openalex.org/A5019188058][Yangbo Wu]], [[https://openalex.org/A5032488454][Xuepeng Wang]], [[https://openalex.org/A5035944985][Youyong Li]], [[https://openalex.org/A5071601763][Yujin Ji]], [[https://openalex.org/A5043301652][Fan Liao]], [[https://openalex.org/A5078686082][Yang Liu]], [[https://openalex.org/A5071907213][Zhenhui Kang]], [[https://openalex.org/A5057299366][Mingwang Shao]], Advanced functional materials (Print). None(None)] 2024. https://doi.org/10.1002/adfm.202402226 
     
Abstract The rutile phase IrO 2 , as a promising catalyst for oxygen evolution reaction (OER), still falls short of satisfactory activity. Here, a novel 1D monoclinic phase iridium‐ruthenium oxide solid solution (m‐Ir x Ru 1‐x O 2 ) is reported. For m‐Ir x Ru 1‐x O 2 with different metal proportions, the optimal m‐Ir 0.91 Ru 0.09 O 2‐δ catalyst exhibits excellent OER activity under acidic conditions with an overpotential of 180 mV at 10 mA cm −2 . As an anode catalyst in a proton exchange membrane electrolyzer, m‐Ir 0.91 Ru 0.09 O 2‐δ with a low catalyst loading (0.1 mg cm −2 ) can operate ≈256 h at 1.8 V with a high current density over 900 mA cm −2 at room temperature. Such a satisfied stability may have originated from the specific morphology and crystal structure, which is confirmed by the transient potential scanning test. Density functional theory calculations show that the Ru in the m‐Ir x Ru 1‐x O 2 facilitates decreasing the OER overpotentials due to the electron transfer from Ru to Ir.    

    

* Lattice Oxygen Redox Mechanisms in the Alkaline Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393199067
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202401610")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393199067"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393199067"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393199067"))][Get cited by]]

OpenAlex: https://openalex.org/W4393199067 (Open access: False)
    
[[https://openalex.org/A5073189107][Xiangrong Ren]], [[https://openalex.org/A5018190045][Yiyue Zhai]], [[https://openalex.org/A5089739504][Na Yang]], [[https://openalex.org/A5016725133][Bolun Wang]], [[https://openalex.org/A5091362073][Shengzhong Liu]], Advanced functional materials (Print). None(None)] 2024. https://doi.org/10.1002/adfm.202401610 
     
Abstract Understanding of fundamental mechanism and kinetics of the oxygen evolution reaction (OER) is pivotal for designing efficient OER electrocatalysts owing to its key role in electrochemical energy conversion devices. In the past few years, the lattice oxygen oxidation mechanism (LOM) arising from the anodic redox chemistry has attracted significant attention as it involves a direct O─O coupling and thus bypasses thermodynamic limitations in the traditional adsorbate evolution mechanism (AEM). Transition metal‐based oxyhydroxides are generally acknowledged as the real catalytic phase in alkaline media. In particular, their low‐dimensional layered structures offer sufficient structural flexibility to trigger the LOM. Herein, a comprehensive overview is provided for recent advances in anion redox from LOM‐based electrocatalysts. Based on analyses of electronic structure of electrocatalysts and LOM, a strategy is proposed to activate LOM. Possible identification techniques for corroboration of the oxygen redox are also reviewed. In addition, the structural reconstruction process induced by the LOM is focused and the importance of multiple in situ/operando characterizations is highlighted to unveil the structural and chemical origins of the LOM. To conclude, a prospect on the remaining challenges and future opportunities for LOM electrocatalysts is presented.    

    

* Solar Oxidative Hydrogen Peroxide Production: Is the Oxygen Vacancy Always a Promoter in Solar Water Oxidation?  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393199759
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Photocatalysis and Solar Energy Conversion, Solar-Powered Water Desalination Technologies
:PUBLICATION_DATE: 2024-03-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05764")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393199759"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393199759"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393199759"))][Get cited by]]

OpenAlex: https://openalex.org/W4393199759 (Open access: False)
    
[[https://openalex.org/A5013345379][Songying Qu]], [[https://openalex.org/A5031786435][Hao Wu]], [[https://openalex.org/A5072979493][Yun Hau Ng]], ACS catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05764 
     
Photoelectrochemical (PEC) water oxidation to hydrogen peroxide (H2O2) is an alternative route to the conventional anthraquinone process, but it is still restricted by the prevailing competitive oxygen evolution reaction (OER). Here, we reveal that intrinsic oxygen vacancies (OVs) of BiVO4 photoanodes are detrimental to PEC water oxidation to H2O2. The superabundant OVs of the BiVO4 photoanode are passivated by a thermal treatment in a pressurized O2 atmosphere by a Parr reactor. The passivated BiVO4 photoanode with the least OV concentration achieves ca. two times H2O2 selectivity enhancement than the BiVO4 photoanode with introduced OVs, resulting from the weakened band bending, the positively shifted quasi-Fermi level, and the suppressed decomposition of as-formed H2O2. In particular, the photoexcited electrochemical impedance spectra demonstrate a hole distribution rearrangement of the OVs-passivated BiVO4, which eliminates the OER-related surface states and steers the water oxidation reaction pathway toward H2O2 formation. This work reveals the importance of interfacial energetics induced by regulating intrinsic OVs in selective PEC water oxidation.    

    

* Highly Effective Bifunctional Electrocatalysts: Synthesizing NiCo 2 O 4 Nanostructures via Chemical Precipitation for Enhanced Oxygen Evolution and Reduction Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393200279
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4092883/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393200279"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393200279"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393200279"))][Get cited by]]

OpenAlex: https://openalex.org/W4393200279 (Open access: True)
    
[[https://openalex.org/A5076617636][Ananta Sasmal]], [[https://openalex.org/A5086071571][Dipankar Gogoi]], [[https://openalex.org/A5031104739][T.D. Das]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4092883/v1  ([[https://www.researchsquare.com/article/rs-4092883/latest.pdf][pdf]])
     
Abstract In this investigation, we successfully produced NiCo 2 O 4 nanostructures using a simple chemical precipitation method, wherein we adjusted molarity concentration of sodium bicarbonate (NaHCO 3 ) and precursor ratios of Ni and Co. Analysis of surface features revealed a diverse range of shapes, including particles, flowers, rods, and flakes. Notably, the NiCo 2 O 4 nanorods (NCO3) demonstrated a significant threefold increase in BET surface area compared to NCO5. The alterations observed in the physical and chemical characteristics significantly influenced the electrocatalytic efficacy in alkaline environments for both the oxygen evolution reaction (OER) and oxygen reduction reaction (ORR). In the context of the oxygen reduction reaction, NCO5 displayed a commencement potential of 0.72 V compared to the reversible hydrogen electrode (RHE), surpassing NCO4 by 110 mV, albeit falling short by 90 mV when compared to Pt/C, the standard benchmark material with a potential of 0.82 V. In terms of OER, NCO3 displayed a potential difference of 152 mV@10mA/cm 2 compared to other NiCo 2 O 4 materials and Pt/C. The increased level of activity observed can be attributed not only to the increased surface area but also to enhancements in electrical properties. This is supported by the lower charge transfer resistance measured in NCO3 (215.2 Ω.cm 2 ) compared to NCO5 (350.2 Ω.cm 2 ) as revealed by electrochemical impedance spectroscopy (EIS).    

    

* Citrus sap-stabilized regulated cobalt ferricyanide efficiently enhanced electrocatalytic activity and durability for oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393206114
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj00704b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393206114"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393206114"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393206114"))][Get cited by]]

OpenAlex: https://openalex.org/W4393206114 (Open access: False)
    
[[https://openalex.org/A5072058273][Muthukumaran Sangamithirai]], [[https://openalex.org/A5057554515][Venkatachalam Ashok]], [[https://openalex.org/A5036327239][A. Gayathri]], [[https://openalex.org/A5064833206][Murugan Vijayarangan]], [[https://openalex.org/A5027764093][Jayaraman Jayabharathi]], New journal of chemistry (1987). None(None)] 2024. https://doi.org/10.1039/d4nj00704b 
     
Citrus sap-stabilized RCoFe nanoplatelets were synthesized by simple co-precipitation, and are highly efficient and stable electrocatalysts for solar cell water splitting (1.56 V).    

    

* Fenico Aerogel for Oxygen Evolution Reaction in Alkaline Systems: Microfluidic and Anion Exchange Membrane Electrolyzers  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393206912
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4773647")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393206912"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393206912"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393206912"))][Get cited by]]

OpenAlex: https://openalex.org/W4393206912 (Open access: False)
    
[[https://openalex.org/A5086079098][A. Martínez-Lázaro]], [[https://openalex.org/A5057149352][F.I. Espinosa-Lagunes]], [[https://openalex.org/A5045345758][Arturo Molina]], [[https://openalex.org/A5046448939][Gabriel Luna‐Bárcenas]], [[https://openalex.org/A5069240724][Carmelo Lo Vecchio]], [[https://openalex.org/A5059513044][Irene Gatto]], [[https://openalex.org/A5021635834][A. Arenillas]], [[https://openalex.org/A5058250351][Vincenzo Baglio]], [[https://openalex.org/A5012413067][J. Ledesma‐García]], [[https://openalex.org/A5026514741][Luis Arriaga]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4773647 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Deepening surface reconstruction on anodized nickel mesh boosts oxygen evolution under industrial alkaline conditions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393215889
:TOPICS: Fabrication and Applications of Porous Alumina Membranes, Memristive Devices for Neuromorphic Computing, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.186")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393215889"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393215889"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393215889"))][Get cited by]]

OpenAlex: https://openalex.org/W4393215889 (Open access: False)
    
[[https://openalex.org/A5079003324][Tai An]], [[https://openalex.org/A5025529267][Qinglin Jin]], [[https://openalex.org/A5034011970][Junyao Shen]], [[https://openalex.org/A5058955656][Weitao Zhang]], [[https://openalex.org/A5088263947][Qian Huang]], [[https://openalex.org/A5067331026][Cong Chen]], [[https://openalex.org/A5024390360][Wen Dong]], [[https://openalex.org/A5064038482][Ronglei Fan]], [[https://openalex.org/A5007539628][Mingrong Shen]], International journal of hydrogen energy. 64(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.186 
     
No abstract    

    

* Construction of mesoporous Ni-Co-Mo oxide/sulfide composite composite nanosheet arrays as bifunctional material for charge storage and oxygen evolution reaction applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393229900
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Advanced Materials for Smart Windows
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.colsurfa.2024.133808")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393229900"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393229900"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393229900"))][Get cited by]]

OpenAlex: https://openalex.org/W4393229900 (Open access: False)
    
[[https://openalex.org/A5055661297][Fulin Yuan]], [[https://openalex.org/A5024521638][Jinyu Wu]], [[https://openalex.org/A5009590736][Cong Liu]], [[https://openalex.org/A5023124620][Faxin Yan]], [[https://openalex.org/A5072988644][Yongfang Liang]], [[https://openalex.org/A5068425398][Jianghai Li]], [[https://openalex.org/A5040698416][Junyu Liu]], [[https://openalex.org/A5020086649][Haifu Huang]], [[https://openalex.org/A5049434555][Xianqing Liang]], [[https://openalex.org/A5021073141][Wenzheng Zhou]], Colloids and surfaces. A, Physicochemical and engineering aspects (Print). None(None)] 2024. https://doi.org/10.1016/j.colsurfa.2024.133808 
     
No abstract    

    

* FeCoO Nanosheet Grown on Free-Standing Carbon Fiber Paper for Boosting the Oxygen Evolution Reaction and Lithium-Ion Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393235843
:TOPICS: Lithium-ion Battery Technology, Materials for Electrochemical Supercapacitors, Conducting Polymer Research
:PUBLICATION_DATE: 2024-03-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.4c00009")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393235843"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393235843"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393235843"))][Get cited by]]

OpenAlex: https://openalex.org/W4393235843 (Open access: False)
    
[[https://openalex.org/A5072555354][Li Deng]], [[https://openalex.org/A5033092340][Yanqing Wang]], [[https://openalex.org/A5056036725][Dong Liu]], [[https://openalex.org/A5020487385][Xuepeng Ni]], [[https://openalex.org/A5016235472][Anqi Ju]], ACS applied energy materials. None(None)] 2024. https://doi.org/10.1021/acsaem.4c00009 
     
The application of transition metal oxides in the oxygen evolution reaction (OER) and lithium-ion batteries (LIBs) for generating pollution-free energy has received extensive attention; however, many challenges still hinder its commercial application. Herein, a carbon fiber paper (CFP) with high conductivity (σ = 176.72 S m–1) was prepared in our lab and used as a free-standing substrate for OER and LIB electrodes. The FeCoO nanosheets with a mesoporous structure are homogeneously anchored on the CFP by a hydrothermal method and air calcination oxidation. The nanosheet structure of FeCoO effectively mitigates the volumetric expansion of the FeCoO/CFP composite while cycling, preventing the collapse of FeCoO and ensuring the fabrication integrity of the electrode. Moreover, the high conductivity of CFP accelerates electron transport and enhances reaction kinetics. For OER, the prepared FeCoO/CFP composites achieve an overpotential of 258 mV at a current density of 10 mA cm–2 with a long-term durability of about 50 h. For LIBs, the FeCoO/CFP composites possess a high reversible capacity of 715.2 mA h g–1 after 300 cycles at 0.5 A g–1. It is confirmed that the self-made CFP is a good substrate for freestanding electrodes, and the FeCoO/CFP composites show potential applications in OER electrocatalysts and LIB anode materials.    

    

* Preparation of Fe/P co-doped MMoO4 (M=Co, Cu and Zn) as environmentally friendly oxygen evolution reaction electrocatalyst  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393237835
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104266")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393237835"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393237835"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393237835"))][Get cited by]]

OpenAlex: https://openalex.org/W4393237835 (Open access: False)
    
[[https://openalex.org/A5066357964][Shijie Liu]], [[https://openalex.org/A5046643126][Yanhong Wang]], [[https://openalex.org/A5049043901][Xiaoqiang Du]], [[https://openalex.org/A5013582226][Xiaoshuang Zhang]], Surfaces and interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104266 
     
Hydrogen production from electrolyzed water has become an ideal new energy source for people to replace traditional fossil energy sources due to its high efficiency and low-carbon characteristics. Therefore, this paper presents preparation of a series of Fe/P co-doped MMoO4 (M=Co, Cu and Zn) catalyst loaded on nickel foam by simple hydrothermal and phosphorization process for the first time. After comparing different molybdate metal salts as precursors, it was demonstrated that the fabricated Fe/P co-doped CuMoO4 target catalysts possessed excellent catalytic performance with an overpotential of only 287 mV at a current density of 100 mA cm−2, faster reaction kinetics and a large active surface area for oxygen evolution reaction (OER). Density functional theory (DFT) calculation shows that the absorption energy of water and the electrical conductivity of the material are enhanced by the co-doping of the Fe and P. The doping of the Fe and P changes the electronic state and coordination environment of the active site, thus enhancing the catalytic activity of the electrode. The experimental results further prove that the doping of the Fe and P makes the active site more exposed and the resistance smaller, thus enhancing the conductivity and activation energy of the material. What is noteworthy is that the electrode also performed well in stability tests, which provided a fabrication solution of new catalyst for green hydrogen production.    

    

* Spin-state regulation by secondary coordination sphere for improved oxygen evolution activity of LaCo1-Ni O3 perovskite  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393238163
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.03.306")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393238163"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393238163"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393238163"))][Get cited by]]

OpenAlex: https://openalex.org/W4393238163 (Open access: False)
    
[[https://openalex.org/A5010122735][Di Yao]], [[https://openalex.org/A5063898322][M. Y. Chai]], [[https://openalex.org/A5028310744][Yunyun Lv]], [[https://openalex.org/A5005299568][Enhui Wang]], [[https://openalex.org/A5058601835][Tao Yang]], [[https://openalex.org/A5066956428][Zhi Fang]], [[https://openalex.org/A5068369655][Xinmei Hou]], Ceramics international. None(None)] 2024. https://doi.org/10.1016/j.ceramint.2024.03.306 
     
The evolution of oxygen evolution reaction (OER) remains a pivotal challenge in the realm of oxygen electrocatalysis. Recently, the proposition of regulating spin states has emerged as a novel avenue for enhancing the efficiency of electrocatalytic reactions. Presently, accurately modulating the metal active center into immediate spin (IS) remains a formidable challenge. Here, our research has achieved a breakthrough in precise spin state control and catalytic performance enhancement of Co3+ through the utilization of Ni-substituted LaCo1-xNixO3 perovskite. This achievement is primarily attributed to the fine regulation of both the secondary coordination sphere (SCS) and primary coordination sphere (PCS), i.e., Co6-y-[Co]-Niy (y = 0–6) and Co-O lengths, respectively. Our findings reveal that LaCo7/9Ni2/9O3 consisted of the SCS (y ≤ 2) with the eg1 fillings of IS Co3+ exhibits an optimal OER activity. Additionally, adjusting the Co-O bond length in PCS to approximately 1.89 Å proves to be more conducive to the transition of Co3+ spin states from high spin (HS) and low spin (LS) to IS. These discoveries present new approach to precisely modulating the spin state, offering promising prospects for the development of high-efficiency OER catalysts.    

    

* Photoelectrochemical water oxidation for on-site production of hydrogen peroxide  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393238383
:TOPICS: Advanced Oxidation Processes for Water Treatment, Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mtphys.2024.101411")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393238383"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393238383"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393238383"))][Get cited by]]

OpenAlex: https://openalex.org/W4393238383 (Open access: False)
    
[[https://openalex.org/A5013395319][Aizhen Liao]], [[https://openalex.org/A5051414501][Yiqing Wei]], [[https://openalex.org/A5073105499][Qi Xie]], [[https://openalex.org/A5045940028][Kan Zhang]], [[https://openalex.org/A5001800737][Linji Zhang]], [[https://openalex.org/A5008523475][Gangqiang Zhu]], [[https://openalex.org/A5038570826][Zixu Zhao]], [[https://openalex.org/A5004866288][Yong Zhou]], [[https://openalex.org/A5018143125][Zhigang Zou]], Materials today physics. None(None)] 2024. https://doi.org/10.1016/j.mtphys.2024.101411 
     
Photoelectrochemical (PEC) two-electron water-oxidation reaction is a promising route for renewable and on-site generation of H2O2 as an alternative to the traditional anthraquinone process. However, large overpotential, low product selectivity, and poor stability limit its practical applications of PEC producing H2O2. This review discusses the fundamental aspects of two-electron water oxidation toward H2O2 in a simple PEC device. It also presents the research background and all prevailing and recent breakthrough in the mechanisms of anodic H2O2 generation. Afterward, it comprehensively reviews the progress made so far in enhancing the Faradaic efficiency of H2O2 synthesis by tuning the thermodynamic energy barriers and reaction kinetics, facilitating the mass transfer of reactants and products, and stabilizing the products and catalytic surfaces. Finally, the critical challenges and opportunities for future development in this field are discussed. We believe that this review would stimulate further efforts to achieve highly efficient on-site H2O2 production and high-power-density fuel cells with H2O2 chemical utilization.    

    

* Single-atom Co dispersed on polyoxometalate derivatives confined in bamboo-like carbon nanotubes enabling efficient dual-site lattice oxygen mediated oxygen evolution electrocatalysis for acidic water electrolyzers  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393239594
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ee00173g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393239594"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393239594"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393239594"))][Get cited by]]

OpenAlex: https://openalex.org/W4393239594 (Open access: False)
    
[[https://openalex.org/A5037743019][Jianyun Liu]], [[https://openalex.org/A5052822186][Tanyuan Wang]], [[https://openalex.org/A5069480005][Zijie Lin]], [[https://openalex.org/A5010639117][Mengyi Liao]], [[https://openalex.org/A5069009550][Shuxia Liu]], [[https://openalex.org/A5074034944][Shiyu Wang]], [[https://openalex.org/A5046876747][Zhao Cai]], [[https://openalex.org/A5089558604][Hongqi Sun]], [[https://openalex.org/A5017423904][Yanbin Shen]], [[https://openalex.org/A5058963412][Yunhui Huang]], [[https://openalex.org/A5053780153][Qing Li]], Energy & environmental science (Print). None(None)] 2024. https://doi.org/10.1039/d4ee00173g 
     
The development of efficient and durable earth-abundant electrocatalysts for acidic oxygen evolution reaction (OER) is crucial for the large-scale application of proton exchange membrane water electrolyzers (PEMWEs). Here, we report...    

    

* Composition-tunable Co3-xFexSe4 as efficient electrocatalysts for the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393246480
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393246480"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393246480"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393246480"))][Get cited by]]

OpenAlex: https://openalex.org/W4393246480 (Open access: False)
    
[[https://openalex.org/A5034212633][G Chen]], [[https://openalex.org/A5011958588][Sheng Zhu]], [[https://openalex.org/A5077397216][Qingwei Gao]], [[https://openalex.org/A5005857127][Shuaiqi Gong]], [[https://openalex.org/A5039502138][Gregory A. Solan]], [[https://openalex.org/A5033109301][Qing Xu]], [[https://openalex.org/A5029104177][Yulin Min]], International journal of hydrogen energy. 64(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.003 
     
In the oxygen evolution reaction (OER), the selection of highly active catalysts is fundamental to curtail overpotentials and to enhance the typically sluggish kinetics characteristic of the reaction. Cobalt selenide (Co3Se4), with its optimally configured electronic structure of cobalt ions, is consistently hailed as a prospective electrocatalyst for the OER, making it highly efficient in facilitating the reaction. Despite the persistent challenges of the exposure of catalytic active sites and the limited electronic conductivity, our study unveils a breakthrough solution. We introduce a highly efficient Fe-doped Co3Se4 electrocatalyst for the OER, addressing these long-standing issues, and it has desirable compositional flexibility, formed Co3-xFexSe4 (0 ≤ x ≤ 3) selenides, by introducing Fe doping, the electronic structure of Co3Se4 is effectively regulated, resulting in a remarkable reduction in the overpotential of the OER under alkaline conditions. Simultaneously, the introduction of Fe induces the formation of highly active Co–O sites, ultimately establishing a highly active and stable catalytic surface for oxygen evolution. Consequently, this leads to a significant improvement in the activity of the oxygen evolution reaction (OER). The synthesized Co2.5Fe0.5Se4 catalyst exhibits lower overpotential (η10 = 220 mV) and Tafel slope (41.2 mV dec−1), which is superior to the general commercial RuO2 benchmark. In addition, Co2.5Fe0.5Se4 also exhibits exceptional structural integrity and sustained operational longevity, with a durability of up to 280 h at 100 mA cmgeo−2. Impressively, the Pt/C∥Co2.5Fe0.5Se4 water electrolysis cell only requires a battery voltage of 1.67 V to provide a current density of 100 mA cmgeo−2 and has excellent long-term stability.    

    

* Decision letter for "Boosting oxygen evolution reaction rates with mesoporous Fe-doped MoCo-phosphide nanosheets"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393251122
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-01-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra00146j/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393251122"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393251122"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393251122"))][Get cited by]]

OpenAlex: https://openalex.org/W4393251122 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra00146j/v1/decision1 
     
No abstract    

    

* Review for "Boosting oxygen evolution reaction rates with mesoporous Fe-doped MoCo-phosphide nanosheets"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393251195
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-01-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra00146j/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393251195"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393251195"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393251195"))][Get cited by]]

OpenAlex: https://openalex.org/W4393251195 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra00146j/v1/review1 
     
No abstract    

    

* Controllable Synthesis Heterojunction of g-C3N4 and BiVO4 to Enhance the Photocatalytic Oxygen Evolution Activity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393267411
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-03-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acssuschemeng.4c00637")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393267411"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393267411"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393267411"))][Get cited by]]

OpenAlex: https://openalex.org/W4393267411 (Open access: False)
    
[[https://openalex.org/A5046643606][Qingyan Zhang]], [[https://openalex.org/A5002521182][Guowei Liu]], [[https://openalex.org/A5027996639][Taifeng Liu]], ACS sustainable chemistry & engineering. None(None)] 2024. https://doi.org/10.1021/acssuschemeng.4c00637 
     
Heterojunctions formed between semiconductors have been confirmed to efficiently enhance the separation of photogenerated carriers, thereby boosting the photocatalytic activity. However, achieving controllable synthesis of heterojunctions remains a challenge. In this study, g-C3N4 (CN) was positively charged by carefully adjusting the pH of the solution. Subsequently, it was precisely located on the (010) crystal facet of decahedral BiVO4 (BVO) under light irradiation, where photogenerated negative electrons accumulate on the (010) facet of BVO. This process results in the construction of a composite with a heterojunction between CN and the (010) facet of BVO. The optimal photocatalytic oxygen production activity of this composite reaches 2966.9 μmol/g/h, a remarkable 3.3 times better than that of BVO alone. This result shows that the heterojunction can significantly improve the oxygen production activity of the composite photocatalyst. By a combination of the Kubelka–Munk function, Mott–Schottky, and theoretical calculations, we found that the migration of photogenerated electrons from BVO to CN matches well with the S-scheme mechanism. This work provides valuable suggestions and guidance for the precise synthesis of heterojunction photocatalyst and is looking forward to being applied to other materials related to environmental and energy research.    

    

* Decision letter for "Boosting oxygen evolution reaction rates with mesoporous Fe-doped MoCo-phosphide nanosheets"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393280937
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-03-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra00146j/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393280937"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393280937"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393280937"))][Get cited by]]

OpenAlex: https://openalex.org/W4393280937 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra00146j/v2/decision1 
     
No abstract    

    

* Review for "Boosting oxygen evolution reaction rates with mesoporous Fe-doped MoCo-phosphide nanosheets"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393280950
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-03-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra00146j/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393280950"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393280950"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393280950"))][Get cited by]]

OpenAlex: https://openalex.org/W4393280950 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra00146j/v2/review1 
     
No abstract    

    

* Development of CuSe/polypyrrole electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393342827
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s00339-024-07429-3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393342827"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393342827"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393342827"))][Get cited by]]

OpenAlex: https://openalex.org/W4393342827 (Open access: False)
    
[[https://openalex.org/A5059163435][Syed Imran Abbas Shah]], [[https://openalex.org/A5049370676][Sumaira Manzoor]], [[https://openalex.org/A5062700170][Muhammad Moazzam Khan]], [[https://openalex.org/A5064746961][Nargis Bano]], [[https://openalex.org/A5022798909][Sameh M. Osman]], [[https://openalex.org/A5063142393][Muhammad Fahad Ehsan]], [[https://openalex.org/A5061069978][Muhammad Naeem Ashiq]], Applied physics. A, Materials science & processing (Print). 130(4)] 2024. https://doi.org/10.1007/s00339-024-07429-3 
     
No abstract    

    

* An Efficient Photocatalytic Oxygen Evolution System with the Coupling of Polyoxometalates with Bismuth Vanadate  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393379318
:TOPICS: Polyoxometalate Clusters and Materials, Nanomaterials with Enzyme-Like Characteristics, Innovations in Organic Synthesis Reactions
:PUBLICATION_DATE: 2024-03-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14040236")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393379318"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393379318"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393379318"))][Get cited by]]

OpenAlex: https://openalex.org/W4393379318 (Open access: True)
    
[[https://openalex.org/A5022993483][Boon Chong Ong]], [[https://openalex.org/A5046137696][Teik‐Thye Lim]], [[https://openalex.org/A5026626040][Can Xue]], [[https://openalex.org/A5033949863][Zhili Dong]], Catalysts. 14(4)] 2024. https://doi.org/10.3390/catal14040236  ([[https://www.mdpi.com/2073-4344/14/4/236/pdf?version=1711922265][pdf]])
     
In this work, a coupling system consisting of bismuth vanadate (BiVO4) and cobalt-based polyoxometalates (Co-POMs) was developed to enhance the oxygen evolution reaction. Crystallization-driven self-assembly and the wet chemical synthesis method were deployed in synthesizing Co-POMs and monoclinic–tetragonal mixed–phase BiVO4, respectively. The introduction of Co-POMs into a BiVO4-containing mixture significantly enhanced the water oxidation reaction, with a more than twofold increment in the total amount of oxygen evolved. For instance, 461.2 µmol of oxygen was evolved from the system containing 20 mg of Co-POMs compared to 195 µmol of oxygen produced from a pristine BiVO4 system. This extraordinary improvement in the oxygen evolution reaction indicates the existence of a positive synergic effect between BiVO4 and Co-POMs, in which Co-POMs could act as effective cocatalysts to extract photogenerated charge carriers generated by BiVO4 and improve the charge transfer process. However, the amount of oxygen produced was slightly reduced to 440.7 µmol with an increase in AgNO3 loading from 30 mg to 60 mg. This unforeseen phenomenon could be elucidated by the shielding effect of silver particles, in which a higher AgNO3 loading led to a more prominent shielding effect. The presence of silver nanoparticles on post-reaction BiVO4 was confirmed by TEM and XPS analysis. This newly established process scheme provides an insight into the development of an efficient photocatalytic oxygen evolution system in realizing future commercial applications toward green energy production.    

    

* Electric-field-assisted Proton Coupling Enhanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393182518
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4158621/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393182518"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393182518"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393182518"))][Get cited by]]

OpenAlex: https://openalex.org/W4393182518 (Open access: True)
    
[[https://openalex.org/A5043695923][Xuelei Pan]], [[https://openalex.org/A5028466176][Mengyu Yan]], [[https://openalex.org/A5000510528][Qian Liu]], [[https://openalex.org/A5053518453][Xunbiao Zhou]], [[https://openalex.org/A5077864081][Congli Sun]], [[https://openalex.org/A5027375542][Jiexin Zhu]], [[https://openalex.org/A5065733335][Callum D. McAleese]], [[https://openalex.org/A5030783885][Pierre Couture]], [[https://openalex.org/A5030474458][Matthew K. Sharpe]], [[https://openalex.org/A5071772117][Richard W. Smith]], [[https://openalex.org/A5081938563][Nianhua Peng]], [[https://openalex.org/A5082693795][Jonathan England]], [[https://openalex.org/A5091670688][Shik Chi Edman Tsang]], [[https://openalex.org/A5076778501][Yunlong Zhao]], [[https://openalex.org/A5022270398][Liqiang Mai]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4158621/v1  ([[https://www.researchsquare.com/article/rs-4158621/latest.pdf][pdf]])
     
Abstract The discovery of Mn-Ca complex in photosystem II stimulates research of manganese-based catalysts for oxygen evolution reaction (OER). However, conventional chemical strategies face challenges in regulating the four electron-proton processes of OER. Herein, we investigate alpha-manganese dioxide (α-MnO 2 ) with typical Mn IV -O-Mn III -H x O motifs as a model for adjusting proton coupling. We reveal that pre-equilibrium proton-coupled redox transition provides an adjustable energy profile for OER, paving the way for in-situ enhancing proton coupling through a new "reagent"— external electric field. Based on the α-MnO 2 single-nanowire device, gate voltage induces a 6-fold increase in OER current density at 1.7 V versus reversible hydrogen electrode. Moreover, the proof-of-principle external electric field-assisted flow cell for water splitting demonstrates a 34% increase in current density and a 44.7 mW/cm² increase in net output power. These findings indicate an in-depth understanding of the role of proton-incorporated redox transition and develop practical approach for high-efficiency electrocatalysis.    

    

* Stable N-doped NiMoO4/NiO2 electrocatalyst for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393322437
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3dt04034h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393322437"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393322437"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393322437"))][Get cited by]]

OpenAlex: https://openalex.org/W4393322437 (Open access: False)
    
[[https://openalex.org/A5030439608][Zhengfang Hou]], [[https://openalex.org/A5072647200][Fangyuan Fan]], [[https://openalex.org/A5037583815][Zhe Wang]], [[https://openalex.org/A5028270305][Yeshuang Du]], Dalton transactions (2003. Print). None(None)] 2024. https://doi.org/10.1039/d3dt04034h 
     
Recently, there has been a significant increasing interest in the research of highly active and stable transition metal-based electrocatalysts for oxygen evolution reaction (OER). Non-noble metals nanocatalysts with excellent inherent...    

    

* In situ growth of Mo-CoFe LDH on nickel foam for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393321245
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144189")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393321245"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393321245"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393321245"))][Get cited by]]

OpenAlex: https://openalex.org/W4393321245 (Open access: False)
    
[[https://openalex.org/A5077749222][Yuchen Duan]], [[https://openalex.org/A5044234080][Bin Hu]], [[https://openalex.org/A5090224078][Yongping Luo]], [[https://openalex.org/A5064085955][Yu Xie]], [[https://openalex.org/A5085462851][Yong Chen]], [[https://openalex.org/A5036658104][Yifan Zhang]], [[https://openalex.org/A5038826345][Yun Ling]], [[https://openalex.org/A5074336795][Jinsheng Zhao]], Electrochimica acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144189 
     
The study of non-precious metals to prepare catalytic materials with high performance and excellent stability is an important part of improving hydrogen production by electrolysis of water. In this work, we report on the preparation of direct composite Mo-CoFe LDH/NF as the working electrode of oxygen evolution reaction (OER) using nickel foam as the substrate via one-step hydrothermal method. The direct growth in situ ensured the close contact between LDH and NF substrate, thereby reducing the charge transfer resistance and making the electrode have high electrocatalytic performance. At the current density of 10 mA·cm−2, the oxygen evolution overpotential of the Mo-CoFe LDH/NF catalytic material was 252 mV, the Tafel slope was 22.07 mV/dec, and the material could be maintained in alkaline solution for 10 hours, showing good stability. Therefore, this work proposed new ideas for the design and fabrication of low-cost and efficient electrocatalyst materials.    

    

* Interfacial Engineering Layered Bimetallic Oxyhydroxides For Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393324035
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4777421")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393324035"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393324035"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393324035"))][Get cited by]]

OpenAlex: https://openalex.org/W4393324035 (Open access: False)
    
[[https://openalex.org/A5053643954][Xiaolin Zhang]], [[https://openalex.org/A5040942247][Huanjun Xu]], [[https://openalex.org/A5044955952][Qiang Shen]], [[https://openalex.org/A5002125111][Weiling Sun]], [[https://openalex.org/A5012838456][Xu Han]], [[https://openalex.org/A5040294744][Dan Jiang]], [[https://openalex.org/A5051158759][Yang Cao]], [[https://openalex.org/A5011809026][Duanwei He]], [[https://openalex.org/A5086736710][Xiaoqiang Cui]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4777421 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Bifunctional activity and theoretical study of transition metal molybdates for hydrogen and oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393393474
:TOPICS: Electrocatalysis for Energy Conversion, Desulfurization Technologies for Fuels, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.254")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393393474"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393393474"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393393474"))][Get cited by]]

OpenAlex: https://openalex.org/W4393393474 (Open access: False)
    
[[https://openalex.org/A5026033742][Namita Dalai]], [[https://openalex.org/A5037335900][Manikandan Kandasamy]], [[https://openalex.org/A5006680940][Shraddhanjali Senapati]], [[https://openalex.org/A5087958993][Brahmananda Chakraborty]], [[https://openalex.org/A5032102667][Bijayalaxmi Jena]], International journal of hydrogen energy. 64(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.254 
     
Effective, sturdy and cheap electrocatalysts are extremely desirable for water electrolysis. In this work, transition metal molybdates (MMoO4, M = Fe, Co, Ni) with extraordinary oxygen evolution reaction (OER), and hydrogen evolution reaction (HER) in basic electrolyte solution was reported. β-Fe2(MoO4)3 catalyst exhibits better electrocatalytic performance and robustness for both HER and OER compared to NiMoO4 and CoMoO4. Theoretical study (DFT calculation) disclose that the Fe atoms increase the energy states near the Fermi level in β-Fe2(MoO4)3 which makes it more conductive leading to superior OER and HER activity. Compared to CoMoO4 and NiMoO4, β-Fe2(MoO4)3 have well defined multiple Mo 4d orbitals at the conduction band. These are empty states in conduction band, ready to receive the electrons. Further, the computed overpotential values for NiMoO4, CoMoO4, and β-Fe2(MoO4)3 surfaces follow the trend, β-Fe2(MoO4)3 < NiMoO4 < CoMoO4, corroborating with the experimental results.    

    

* Unraveling Surface Reconstruction During Oxygen Evolution Reaction on the Defined Spinel Oxide Surface  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393364585
:TOPICS: Catalytic Nanomaterials, Atomic Layer Deposition Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202401095")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393364585"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393364585"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393364585"))][Get cited by]]

OpenAlex: https://openalex.org/W4393364585 (Open access: False)
    
[[https://openalex.org/A5009235836][Kyungbeen Yeom]], [[https://openalex.org/A5084067051][Jung Hyun Jo]], [[https://openalex.org/A5077614940][Hyun-Seop Shin]], [[https://openalex.org/A5019783246][Hyunsoo Ji]], [[https://openalex.org/A5039548543][Sun-Young Moon]], [[https://openalex.org/A5054551527][Ji‐Eun Park]], [[https://openalex.org/A5061877778][Seongbeom Lee]], [[https://openalex.org/A5020781886][Jae-Hyuk Shim]], [[https://openalex.org/A5001151989][Dong Hyeon Mok]], [[https://openalex.org/A5072687754][Megalamane S. Bootharaju]], [[https://openalex.org/A5058710447][Seoin Back]], [[https://openalex.org/A5025901845][Taeghwan Hyeon]], [[https://openalex.org/A5084410026][Yung‐Eun Sung]], Advanced functional materials (Print). None(None)] 2024. https://doi.org/10.1002/adfm.202401095 
     
Abstract The reconstructed surface structure of Co‐based spinel oxides serves as the active site for oxygen evolution reaction (OER). However, the structural complexity of spinel oxides and surface dynamics during the OER hinder the understanding of the reconstruction mechanism and electronic structure of the active site. In this study, spinel Co 3 O 4 @(CoFeV) 3 O 4 nanocube (CoFeV) is reported, a (001) facet‐defined spinel oxide comprising Co, Fe, and V deposited on the Co 3 O 4 nanocube template to exclude facet‐dependent factors. Introducing highly dissoluble V cations accelerates the reconstruction process to enhance the electrocatalytic activity. CoFeV exhibited enhanced electrocatalytic activity (266 mV at 10 mA cm −2 in 1 M KOH) and durability (maintained stable electrocatalytic activity during a 200 h chronopotentiometry (CP) test at 100 mA cm −2 ) with significantly enlarged electrochemically active surface area (ECSA). The experimental and theoretical results demonstrated that V dissolution during catalysis induced oxygen vacancies, accelerating the surface reconstruction to highly active oxyhydroxide. Consequently, the anion exchange membrane water electrolyzer (AEMWE) of CoFeV as the anode exhibited a remarkable performance of 6.19 A cm −2 at 2.0 V cell in 1 M KOH and robust durability for 96 h at a constant current density of 500 mA cm −2 .    

    

* New strategies for the elaboration of porous materials based on iridium towards the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393370747
:TOPICS: Evolution and Applications of Nanoporous Metals, Fabrication and Applications of Porous Alumina Membranes, Catalytic Nanomaterials
:PUBLICATION_DATE: 2022-01-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393370747"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393370747"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393370747"))][Get cited by]]

OpenAlex: https://openalex.org/W4393370747 (Open access: True)
    
[[https://openalex.org/A5053316352][Marine Elmaalouf]], No host. None(None)] 2022. None  ([[https://theses.hal.science/tel-04225703/document][pdf]])
     
No abstract    

    

* Boosting oxygen evolution reaction rates with mesoporous Fe-doped MoCo-phosphide nanosheets  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393239770
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra00146j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393239770"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393239770"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393239770"))][Get cited by]]

OpenAlex: https://openalex.org/W4393239770 (Open access: True)
    
[[https://openalex.org/A5037577649][Gouda K. Helal]], [[https://openalex.org/A5049719890][Zhenhang Xu]], [[https://openalex.org/A5015220732][Wei Zuo]], [[https://openalex.org/A5068207417][Yueying Yu]], [[https://openalex.org/A5064348390][Jinyan Liu]], [[https://openalex.org/A5042807824][Hongping Su]], [[https://openalex.org/A5058697019][Jiang Xu]], [[https://openalex.org/A5017170652][Houbin Li]], [[https://openalex.org/A5010309536][Gongzhen Cheng]], [[https://openalex.org/A5087868751][Pingping Zhao]], RSC advances. 14(15)] 2024. https://doi.org/10.1039/d4ra00146j  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ra/d4ra00146j][pdf]])
     
In this study, we explord the catalytic activity of MoCoFephosphide nanosheets as highly active and stable catalysts for OER. Electrochemical analysis exhibits a low overpotential of 250 mV in (1 M KOH), achieving a current density of 10 mA cm −2 with a low Tafel slope of 43.38 mV dec −2 .    

    

* Acid Electrolyte Anions Adsorption Effects on IrO2 Electrocatalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393302584
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.3c08103")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393302584"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393302584"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393302584"))][Get cited by]]

OpenAlex: https://openalex.org/W4393302584 (Open access: False)
    
[[https://openalex.org/A5093483426][S. A. Keishana Navodye]], [[https://openalex.org/A5045374317][G. T. Kasun Kalhara Gunasooriya]], Journal of physical chemistry. C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.3c08103 
     
Proton exchange membrane water electrolysis is a promising technology merging the usage of intermittent renewable energy sources with the production of green hydrogen. The anodic oxygen evolution reaction remains the bottleneck of the efficiency of these devices due to sluggish reaction kinetics, high cost, and the scarcity of state-of-the-art catalytic materials. Though most research is focused on the discovery of new catalytic materials, understanding the effects of acid electrolyte anions is crucial to designing and optimizing existing electrocatalysts in diverse electrochemical microenvironments. Herein, we systematically study the effects of acid electrolytes on the IrO2(110) surface under OER reaction conditions using density functional theory. The potential-dependent anion adsorption results show that HPO42– adsorbs the strongest, followed by SO42–, NO3–, and ClO4– respectively at 1.6 V (vs RHE). HPO42– and SO42– block the Ir-active sites by competitively adsorbing with the OER intermediates while ClO4– does not interfere with OER performance. By evaluating dipole-field interactions, surface work function changes, Bader charges of adsorbed anions, and the effects of adsorbed electrolyte anions on the adsorption of the OER intermediates, we provide further insights into acid anion electrolyte effects under the OER conditions. This expansion of fundamental understanding of the effects of acid electrolyte anion adsorption on IrO2 assists in engineering better-performing catalysts with integrated electrolyte microenvironment for OER.    

    

* NiFe Catalysts for Oxygen Evolution Reaction: Is There an Optimal Thickness for Generating a Dynamically Stable Active Interface?  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393389421
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Molecular Electronic Devices and Systems
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400286")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393389421"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393389421"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393389421"))][Get cited by]]

OpenAlex: https://openalex.org/W4393389421 (Open access: False)
    
[[https://openalex.org/A5051130087][Luca Ciambriello]], [[https://openalex.org/A5022148644][Ivano Alessandri]], [[https://openalex.org/A5007878932][Luca Gavioli]], [[https://openalex.org/A5023787065][Irene Vassalini]], ChemCatChem (Print). None(None)] 2024. https://doi.org/10.1002/cctc.202400286 
     
Here we investigated the dynamics of OER activity of NiFe (90/10) catalysts over 1000 potential sweep cycles as a function of their mass loading. Over twenty different films with mass loading in the 10 ng/cm2‐30 μg/cm2 range were deposited by Supersonic Cluster Beam Deposition (SCBD), allowing to study the progress of OER in sub‐monolayer, monolayer and multilayer regimes. Upon prolonged potential sweeps the electrocatalytic performances of multilayers decreased, while those of monolayers were significantly improved. The best balance in terms of catalytic efficiency and stability in working conditions is found for mass loadings corresponding to a NiFe monolayer, corresponding to a mass loading around 1 μg/cm2 and a thickness of about 3 nm.    

    

* Review for "Boosting oxygen evolution reaction rates with mesoporous Fe-doped MoCo-phosphide nanosheets"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393283781
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-01-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra00146j/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393283781"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393283781"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393283781"))][Get cited by]]

OpenAlex: https://openalex.org/W4393283781 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra00146j/v1/review2 
     
No abstract    

    

* Enhancing the oxygen evolution activity and stability of Pb anode in Mn2+-containing acidic solution by embedding MnCo2O4 particles  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393306091
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.290")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393306091"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393306091"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393306091"))][Get cited by]]

OpenAlex: https://openalex.org/W4393306091 (Open access: False)
    
[[https://openalex.org/A5050463246][Xiaocong Zhong]], [[https://openalex.org/A5023680214][Yanwei Ren]], [[https://openalex.org/A5041726830][Huai Jiang]], [[https://openalex.org/A5009415480][Kuifang Zhang]], [[https://openalex.org/A5083280220][Ruixiang Wang]], [[https://openalex.org/A5004659490][Zhifeng Xu]], International journal of hydrogen energy. 64(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.290 
     
Due to the excellent activity and stability of MnCo2O4 toward the oxygen evolution reaction (OER) in acidic solution, a Pb–MnCo2O4 composite anode for zinc electrowinning was prepared by embedding dispersed MnCo2O4 particles into a Pb matrix in a powder metallurgy process. In this work, the phase structure, chemical composition, and morphology of the oxide layers formed on Pure-Pb and Pb–MnCo2O4 were analyzed by XRD, SEM, and EDS. Galvanostatic polorization, Tafel tests, and EIS measurements were performed to investigate the anodic potential variation and OER kinetics of the Pure-Pb and Pb–MnCo2O4 composite anodes. Compared with that on the Pure-Pb anode, the oxide layer on Pb–MnCo2O4 is thinner, more compact, and more stable in a 160 g L−1 H2SO4 solution containing 4 g L−1 Mn2+. Consequently, the Pb–MnCo2O4 composite anode exhibited a much lower anode slime production (8.7 mg) during 72 h of the simulated zinc electrowinning process. Despite the smaller surface area and lower PbO2 content of the oxide layer, the Pb–MnCo2O4 composite anode presented preferable OER kinetics with a lower OER charge transfer resistance (0.729 Ω cm2) and a smaller Tafel slope (90.74 mV dec−1), which contributed to a 70 mV reduction in the anodic potential compared with that of the Pure-Pb anode.    

    

* Construction of iron-modulated VN/V3O4/Co5·47N nanoparticles with rich heterogeneous interfaces for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393332725
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.03.301")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393332725"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393332725"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393332725"))][Get cited by]]

OpenAlex: https://openalex.org/W4393332725 (Open access: False)
    
[[https://openalex.org/A5040594189][Dangxia Wang]], [[https://openalex.org/A5029733101][Yaoxia Yang]], [[https://openalex.org/A5078314562][Xingwei Guo]], [[https://openalex.org/A5071773009][Yu Zhang]], [[https://openalex.org/A5053116259][Bin Lü]], [[https://openalex.org/A5071334688][Qingtao Wang]], [[https://openalex.org/A5032918016][Dongfei Sun]], [[https://openalex.org/A5046085824][Jian Li]], [[https://openalex.org/A5026631111][Ziqiang Lei]], International journal of hydrogen energy. 64(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.03.301 
     
With the increasing need of clean energy demand, the development of efficient and green electrocatalysts for water electrolysis plays an irreplaceable role in the realization of large-scale production of hydrogen. Herein, an original iron modulated heterogeneous VN/V3O4/Co5·47N nanoparticles (FVOCN) is successfully synthesized using hydrothermal technique and in situ pyrolysis protocol. Through a series of characterization, it is found that the addition of iron in VN/V3O4/Co5·47N (VOCN) can significantly regulate the electronic structure and make it have better electrochemical oxygen evolution activity in 1 M KOH solution as opposed to the VOCN. The catalyst is obtained at the sintering temperature of 600 °C has the best performance, which only requires a lower overpotential of 270 mV to attain the current density of 10 mA cm−2 and superior to commercial IrO2. The method of introducing iron into vanadium-based, cobalt-based nitrides and vanadium-based oxides can broaden the research content of new electrochemical oxygen evolution reaction (OER) catalysts and provide a reference idea for the development of energy industry.    

    

* Tailoring hypervalent Nickel induced by oxygen vacancy toward enhanced oxygen evolution reaction performance in self-supporting NiFe-(oxy)hydroxides electrodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393320806
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.03.184")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393320806"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393320806"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393320806"))][Get cited by]]

OpenAlex: https://openalex.org/W4393320806 (Open access: False)
    
[[https://openalex.org/A5038297813][Chun Kong]], [[https://openalex.org/A5037609171][Chunyi Zhi]], [[https://openalex.org/A5076564883][Zirui Wu]], [[https://openalex.org/A5030339000][Wenqiang Yang]], [[https://openalex.org/A5000720000][Juan Yang]], [[https://openalex.org/A5049586106][Zhongti Sun]], Journal of colloid and interface science (Print). None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.03.184 
     
NiFe-(oxy)hydroxides are the most active transition metal oxide electrocatalysts for oxygen evolution reaction (OER) under the alkaline media. Herein, we controllably manipulated oxygen vacancy (VO)-tunable NiFe-(oxy) hydroxides that their OER performances possessed a volcano-type relationship with VO concentration, positively-correlated with Ni3+/Ni2+ ratio. Theoretical simulations further unearthed the enhanced activation and dissociation of H2O by the inserting of VO. As a result, the optimal sample featuring the Ni3+/Ni2+ ratio of 30.3 % and VO of 23.8 % exhibited the overpotential of 243 mV at the current density of 100 mA cm–2, simultaneously lasting 120 h durability without any attenuation, exceding the most reported NiFe-(oxy)hydroxides. This work offers an innovative view to understand the OER performance using hypervalent Ni ratio induced by VO defects.    

    

* Author response for "Boosting oxygen evolution reaction rates with mesoporous Fe-doped MoCo-phosphide nanosheets"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4393281153
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra00146j/v2/response1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4393281153"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4393281153"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4393281153"))][Get cited by]]

OpenAlex: https://openalex.org/W4393281153 (Open access: False)
    
[[https://openalex.org/A5037577649][Gouda K. Helal]], [[https://openalex.org/A5049719890][Zhenhang Xu]], [[https://openalex.org/A5015220732][Wei Zuo]], [[https://openalex.org/A5068207417][Yueying Yu]], [[https://openalex.org/A5064348390][Jinyan Liu]], [[https://openalex.org/A5042807824][Hongping Su]], [[https://openalex.org/A5058697019][Jiang Xu]], [[https://openalex.org/A5017170652][Houbin Li]], [[https://openalex.org/A5010309536][Gongzhen Cheng]], [[https://openalex.org/A5087868751][Pingping Zhao]], No host. None(None)] 2024. https://doi.org/10.1039/d4ra00146j/v2/response1 
     
No abstract    

    
