#+TITLE: water splitting
Description: water splitting papers
Created on Wed Mar  6 00:43:31 2024

Found 26 results from 2024-02-28 to 2024-03-06
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Surface addition of Ag on PbO2 to enable efficient oxygen evolution reaction in pH-neutral media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392184832
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392184832"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392184832"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392184832"))][Get cited by]]

OpenAlex: https://openalex.org/W4392184832 (Open access: False)
    
[[https://openalex.org/A5041930796][Siming Li]], [[https://openalex.org/A5047811811][Meng Shi]], [[https://openalex.org/A5072254497][Chen Wu]], [[https://openalex.org/A5032967714][Kaiqi Nie]], [[https://openalex.org/A5052267876][Zheng Wang]], [[https://openalex.org/A5050687293][Xiaoxu Jiang]], [[https://openalex.org/A5038908444][Xinbing Liu]], [[https://openalex.org/A5063251071][Huili Chen]], [[https://openalex.org/A5024069386][Xinlong Tian]], [[https://openalex.org/A5053821178][Daoxiong Wu]], [[https://openalex.org/A5041930796][Siming Li]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150043 
     
Electrocatalysts, particularly earth-abundant metal oxide ones, exhibit poor performance in catalyzing the oxygen evolution reaction (OER) under neutral conditions due to low ionic concentrations. This study introduces a novel strategy for fabricating a PbO2 + Ag composite electrode with significantly improved OER activity and stability in a pH-neutral environment. Our results suggest that incorporating Ag as a surface additive improves the efficiency of utilizing adsorbed oxygenated species via the bridge-site-top-site pathway. Moreover, the surface decoration of Ag resulted in enhanced electrocatalytic stability by diverting the attack of oxygenated species to Pb thereby effectively preventing Pb dissolution. The results not only establish a method for utilizing PbO2 in pH-neutral OER applications, but also propose a potential strategy for employing less noble catalysts in cost-effective electrochemical energy conversions.    

    

* Carbon Nanotube Composites with Bimetallic Transition Metal Selenides as Efficient Electrocatalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392189844
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16051953")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392189844"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392189844"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392189844"))][Get cited by]]

OpenAlex: https://openalex.org/W4392189844 (Open access: True)
    
[[https://openalex.org/A5053208255][Saira Riaz]], [[https://openalex.org/A5026183354][Muhammad Shafiq Anjum]], [[https://openalex.org/A5009004798][Abid Ali]], [[https://openalex.org/A5081498908][Yasir Mehmood]], [[https://openalex.org/A5064930579][Muhammad Ahmad]], [[https://openalex.org/A5066178049][Norah Alwadai]], [[https://openalex.org/A5010504371][Munawar Iqbal]], [[https://openalex.org/A5052430989][Salih Akyürekli]], [[https://openalex.org/A5051204593][Noor Hassan]], [[https://openalex.org/A5050144026][Rizwan Shoukat]], Sustainability. 16(5)] 2024. https://doi.org/10.3390/su16051953  ([[https://www.mdpi.com/2071-1050/16/5/1953/pdf?version=1709030630][pdf]])
     
Hydrogen fuel is a clean and versatile energy carrier that can be used for various applications, including transportation, power generation, and industrial processes. Electrocatalytic water splitting could be the most beneficial and facile approach for producing hydrogen. In this work, transition metal selenide composites with carbon nanotubes (CNTs) have been investigated for electrocatalytic water splitting. The synthesis process involved the facile one-step hydrothermal growth of transition metal nanoparticles over the CNTs and acted as an efficient electrode toward electrochemical water splitting. Scanning electron microscopy and XRD patterns reveal that nanoparticles were firmly anchored on the CNTs, resulting in the formation of composites. The electrochemical measurements reveal that CNT composite with nickel–cobalt selenides (NiCo-Se/CNTs@NF) display remarkable oxygen evolution reaction (OER) activity in basic media, which is an important part of hydrogen production. It demonstrates the lowest overpotential (η10mAcm−2) of 0.560 V vs. RHE, a reduced Tafel slope of 163 mV/dec, and lower charge transfer impedance for the OER process. The multi-metallic selenide composite with CNTs demonstrating unique nanostructure and synergistic effects offers a promising platform for enhancing electrocatalytic OER performance and opens up new avenues for efficient energy conversion and storage applications.    

    

* Ultrasmall Ruthenium Nanoclusters Anchored on Thiol-Functionalized Metal–Organic Framework as a Catalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392191736
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.3c06102")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392191736"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392191736"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392191736"))][Get cited by]]

OpenAlex: https://openalex.org/W4392191736 (Open access: False)
    
[[https://openalex.org/A5085843260][Biswajit Mishra]], [[https://openalex.org/A5050309292][Swayamprakash Biswal]], [[https://openalex.org/A5065162947][Bijay P. Tripathi]], ACS Applied Nano Materials. None(None)] 2024. https://doi.org/10.1021/acsanm.3c06102 
     
No abstract    

    

* Stability challenges and opportunities of NiFe‐based electrocatalysts for oxygen evolution reaction in alkaline media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392196226
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cnl2.110")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392196226"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392196226"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392196226"))][Get cited by]]

OpenAlex: https://openalex.org/W4392196226 (Open access: True)
    
[[https://openalex.org/A5006182339][Yujun Han]], [[https://openalex.org/A5001395097][Jingyi Wang]], [[https://openalex.org/A5064684366][Yuhang Liu]], [[https://openalex.org/A5087372065][Tianqi Li]], [[https://openalex.org/A5031555539][Tongzhou Wang]], [[https://openalex.org/A5024541563][Xinyue Li]], [[https://openalex.org/A5013256964][X. J. Ye]], [[https://openalex.org/A5027334799][Guodong Li]], [[https://openalex.org/A5063383376][Jihong Li]], [[https://openalex.org/A5069789783][Wenbin Hu]], [[https://openalex.org/A5073977425][Yida Deng]], Carbon Neutralization. None(None)] 2024. https://doi.org/10.1002/cnl2.110  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cnl2.110][pdf]])
     
Abstract Water splitting is a critical process for the production of green hydrogen, contributing to the advancement of a circular economy. However, the application of water splitting devices on a large scale is primarily impeded by the sluggish oxygen evolution reaction (OER) at the anode. Thus, developing and designing efficient OER catalysts is a significant target. NiFe‐based catalysts are extensively researched as excellent OER electrocatalysts due to their affordability, abundant reserves, and intrinsic activities. However, they still suffer from long‐term stability challenges. To date, few systematic strategies for improving OER durability have been reported. In this review, various advanced NiFe‐based catalysts are introduced. Moreover, the OER stability challenges of NiFe‐based electrocatalysts in alkaline media, including iron segregation, structural degradation, and peeling from the substrate are summarized. More importantly, strategies to enhance OER stability are highlighted and opportunities are discussed to facilitate future stability studies for alkaline water electrolysis. This review presents a design strategy for NiFe‐based electrocatalysts and anion exchange membrane (AEM) electrolyzers to overcome stability challenges in OER, which also emphasizes the importance of long‐term stability in alkaline media and its significance for achieving large‐scale commercialization.    

    

* Pyridine caused structural reconfiguration forming ultrathin 2D metal-organic frameworks for oxygen evolution reaction.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392205602
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Nanomaterials with Enzyme-Like Characteristics, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ta08079j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392205602"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392205602"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392205602"))][Get cited by]]

OpenAlex: https://openalex.org/W4392205602 (Open access: False)
    
[[https://openalex.org/A5002109316][Liusi Yang]], [[https://openalex.org/A5077139864][Shuwei Deng]], [[https://openalex.org/A5037703959][Shenyuan Fu]], [[https://openalex.org/A5054834291][Xiaoteng Wang]], [[https://openalex.org/A5013487932][Gang Liu]], [[https://openalex.org/A5033332677][Haidong Yang]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d3ta08079j 
     
Two-dimensional metal-organic frameworks (2D MOFs) as an ideal prototype material for electrocatalytic oxygen evolution reaction (OER) can expose more metal active sites due to their ultrathin 2D structure. Herein, a...    

    

* The behaviors of electrochemical oxygen intercalation of some oxygen-deficient ferrites and physical properties of perovskite Sr2LaFe3O8.95 prepared by electrochemical oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392225188
:TOPICS: Synthesis and Applications of Ferrite Nanoparticles, Multiferroic and Magnetoelectric Materials, Magnetocaloric Materials Research
:PUBLICATION_DATE: 1997-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392225188"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392225188"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392225188"))][Get cited by]]

OpenAlex: https://openalex.org/W4392225188 (Open access: True)
    
[[https://openalex.org/A5056667091][Fang Zhou]], No host. None(None)] 1997. None  ([[https://theses.hal.science/tel-00833236/document][pdf]])
     
No abstract    

    

* Nanocomposites of Carbon for Metal-Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392207371
:TOPICS: Lithium-ion Battery Technology, Materials for Electrochemical Supercapacitors, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-981-99-9931-6_7")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392207371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392207371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392207371"))][Get cited by]]

OpenAlex: https://openalex.org/W4392207371 (Open access: False)
    
[[https://openalex.org/A5043747431][Kriti Shrivastava]], [[https://openalex.org/A5080277395][Ankur Jain]], Engineering materials. None(None)] 2024. https://doi.org/10.1007/978-981-99-9931-6_7 
     
Extensive studies are being made on clean and sustainable energy conversion technologies to harness their potential in terms of great efficiency, large-scale uses, and negligible greenhouse gas emissions including fuel cells, metal-air batteries, and water-splitting techniques. Among them all, metal-air batteries are the most promising systems for portable electronic devices, electrical vehicles, and stationary microgrid applications due to their high energy density. However, the major limitation is the fundamental issues with their mechanism. The efficiency of energy conversion and storage is controlled by the oxygen reduction reaction (ORR) and oxygen evolution reaction (OER), which are generally very slow and require noble metal catalysts for fast operation. The high cost and limited availability of noble metals caused a growing interest in developing metal-free carbons as a novel class of bifunctional electrocatalysts. These materials display exceptional strength, stability, conductivity, large surface area, and high stability in both acidic and alkaline environments and therefore can play a significant role in the field of clean energy storage/conversion technologies. In this chapter, the recent advances regarding the rational design of carbon-based electrocatalysts for the oxygen reduction reaction and oxygen evolution reaction are summarized, with a special focus on their applications in Zn–air and Li–air batteries.    

    

* An NiFeSn Oxyhydroxide Electrocatalyst Wet Gel for Highly Efficient Water Electrolysis in Alkaline Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392184869
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nanoen.2024.109428")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392184869"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392184869"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392184869"))][Get cited by]]

OpenAlex: https://openalex.org/W4392184869 (Open access: False)
    
[[https://openalex.org/A5031885225][Taehee Kim]], [[https://openalex.org/A5004680310][Hwapyung Jung]], [[https://openalex.org/A5016637469][Hee Young Choi]], [[https://openalex.org/A5075259600][Donghyeon Kang]], [[https://openalex.org/A5001628148][Wonjun Lee]], [[https://openalex.org/A5065166904][Vinayak G. Parale]], [[https://openalex.org/A5071151758][Umakant M. Patil]], [[https://openalex.org/A5056562445][Younghun Kim]], [[https://openalex.org/A5046632041][J. S. Kim]], [[https://openalex.org/A5005487766][Sang-Hyun Kim]], [[https://openalex.org/A5084473082][Sang Woo Kim]], [[https://openalex.org/A5051853768][Kazuyoshi Kanamori]], [[https://openalex.org/A5015673562][Hyung Ho Park]], Nano Energy. None(None)] 2024. https://doi.org/10.1016/j.nanoen.2024.109428 
     
Since the kinetic barrier posed by the oxygen evolution reaction (OER) is a significant obstacle in water-splitting systems, the creation of effective and inexpensive OER electrocatalysts has received considerable research interest. We report the facile synthesis of an amorphized NiFeSn oxyhydroxide wet gel on Ni foam via a gelation-induced embedding method. Its intrinsic pore structure provided a sufficiently large surface area without the need for a binder. The NiFeSn oxyhydroxide wet-gel electrocatalyst only needed overpotentials of 253, 301, and 346 mV to produce 100, 200, and 300 mA·cm-2, respectively, for the OER and an overpotential value of 198 mV at 50 mA·cm-2 for the hydrogen evolution reaction. Moreover, an exceptionally low voltage of 1.55 V was required for overall water splitting under alkaline conditions. Enhancement of the catalytic properties of the oxyhydroxide by adding Sn was confirmed by using density functional theory calculations. The nanoporous multi-metallic wet gel can be used to create effective low-cost stable self-supporting electrocatalysts with a high current density for enhanced water electrolysis.    

    

* Boosting overall saline water splitting by constructing a strain‐engineered high‐entropy electrocatalyst  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392199493
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cey2.519")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392199493"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392199493"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392199493"))][Get cited by]]

OpenAlex: https://openalex.org/W4392199493 (Open access: True)
    
[[https://openalex.org/A5009410342][Ateer Bao]], [[https://openalex.org/A5074635667][Yaohang Gu]], [[https://openalex.org/A5001753313][Yuxuan Zhang]], [[https://openalex.org/A5042328954][Bowen Zhang]], [[https://openalex.org/A5013655092][Juncheng Wu]], [[https://openalex.org/A5039717240][Bo Niu]], [[https://openalex.org/A5021636467][Xiaoyan Zhang]], [[https://openalex.org/A5042747805][Haijun Pan]], [[https://openalex.org/A5017229059][Xiwei Qi]], Carbon energy. None(None)] 2024. https://doi.org/10.1002/cey2.519  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cey2.519][pdf]])
     
Abstract High‐entropy materials (HEMs), which are newly manufactured compounds that contain five or more metal cations, can be a platform with desired properties, including improved electrocatalytic performance owing to the inherent complexity. Here, a strain engineering methodology is proposed to design transition‐metal‐based HEM by Li manipulation (LiTM) with tunable lattice strain, thus tailoring the electronic structure and boosting electrocatalytic performance. As confirmed by the experiments and calculation results, tensile strain in the LiTM after Li manipulation can optimize the d ‐band center and increase the electrical conductivity. Accordingly, the as‐prepared LiTM‐25 demonstrates optimized oxygen evolution reaction and hydrogen evolution reaction activity in alkaline saline water, requiring ultralow overpotentials of 265 and 42 mV at 10 mA cm −2 , respectively. More strikingly, LiTM‐25 retains 94.6% activity after 80 h of a durability test when assembled as an anion‐exchange membrane water electrolyzer. Finally, in order to show the general efficacy of strain engineering, we incorporate Li into electrocatalysts with higher entropies as well.    

    

* In-situ construction of cation vacancies in amphoteric-metallic element-doped NiFe-LDH as ultrastable and efficient alkaline hydrogen evolution electrocatalysts at 1000 mA cm-2  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392203793
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.02.184")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392203793"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392203793"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392203793"))][Get cited by]]

OpenAlex: https://openalex.org/W4392203793 (Open access: False)
    
[[https://openalex.org/A5042968837][Q J Liu]], [[https://openalex.org/A5071740726][Kaisheng Chen]], [[https://openalex.org/A5014095615][Min Wang]], [[https://openalex.org/A5003220159][Haibo Fan]], [[https://openalex.org/A5046573190][Zihao Yan]], [[https://openalex.org/A5031056448][Xi‐Wen Du]], [[https://openalex.org/A5000357063][Yongjun Chen]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.02.184 
     
Developing efficient and stable electrocatalysts at affordable costs is very important for large-scale production of green hydrogen. In this study, unique amphoteric metallic element-doped NiFe-LDH nanosheet arrays (NiFeCd-LDH, NiFeZn-LDH and NiFeAl-LDH) using as high-performance bifunctional electrocatalysts for hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) were reported, by tuning electronic structure and vacancy engineering. It was found that NiFeCd-LDH possesses the lowest overpotentials of 85 mV and 240 mV (at 10 mA cm-2) for HER and OER, respectively. Density functional theory (DFT) calculations reveal the synergistic effect of Cd vacancies and Cd doping on improving alkaline HER performance, which promote the achievement of excellent catalytic activity and ultrastable hydrogen production at a large current density of 1000 mA cm-2 within 270 hours. Besides, the overall water splitting performance of the as-prepared NiFeCd-LDH requires only 1.580 V to achieve a current density of 10 mA cm-2 in alkaline seawater media, underscoring the importance of modifying the electronic properties of LDH for efficient overall water splitting in both alkaline water/seawater environments.    

    

* Optimizing Water Oxidation Kinetics by Modulating Spin Alignment through Non-metal Vacancy Engineering  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392185671
:TOPICS: Electrocatalysis for Energy Conversion, Atomic Layer Deposition Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c03125")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392185671"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392185671"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392185671"))][Get cited by]]

OpenAlex: https://openalex.org/W4392185671 (Open access: False)
    
[[https://openalex.org/A5006440865][Jianyong Lou]], [[https://openalex.org/A5067392495][Junhui Liang]], [[https://openalex.org/A5040069267][Xin Yao]], [[https://openalex.org/A5047991046][Ma Hong]], [[https://openalex.org/A5070829517][Yiqing Zhang]], [[https://openalex.org/A5005985350][Huayu Chen]], [[https://openalex.org/A5046633997][Laishun Qin]], [[https://openalex.org/A5053114163][Yuexiang Huang]], [[https://openalex.org/A5071855419][Ying Zhao]], [[https://openalex.org/A5077114202][Da Chen]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.3c03125 
     
The efficiency of water splitting is primarily hampered by the sluggish kinetics of the oxygen evolution reaction (OER). Recently, increasing attention has been drawn to leverage spin polarization under an external magnetic field. However, the application of a magnetic field requires additional energy consumption and poses design challenges. Herein, we propose a simple defect engineering strategy aimed at aligning spins in paramagnetic materials to achieve an enhanced intrinsic OER activity. The hydrogenated NiFeP with P vacancies demonstrates elevated saturation magnetization (MS) and reduced overpotential (MS = 5.8 emu/mg, η10 = 303 mV) compared to the untreated NiFeP sample (MS = 1.2 emu/mg, η10 = 341 mV). We elucidate the underlying mechanism of the spin magnetic effect on the OER performance and provide insights into the intricate relationship among vacancies, saturation magnetization, spin state alignment, and oxygenated intermediates. These insights contribute to a better understanding and design of catalysts at the spintronic level, paving the way for more efficient water splitting processes.    

    

* Ni-doped Fe-based perovskite to obtain multifunctional and highly efficient electrocatalytic active IT-SOFC electrode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392213929
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131334")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392213929"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392213929"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392213929"))][Get cited by]]

OpenAlex: https://openalex.org/W4392213929 (Open access: False)
    
[[https://openalex.org/A5010702043][Jinghe Bai]], [[https://openalex.org/A5010073411][Leilei Niu]], [[https://openalex.org/A5051604684][Qiurong Zhu]], [[https://openalex.org/A5083949455][Defeng Zhou]], [[https://openalex.org/A5037885920][Xiaofei Zhu]], [[https://openalex.org/A5043839950][Ning Wang]], [[https://openalex.org/A5076675436][Wenfu Yan]], [[https://openalex.org/A5079335387][Jianqiu Wang]], [[https://openalex.org/A5077442851][Qingwen Liang]], [[https://openalex.org/A5089061216][Zhidong Chen]], Fuel. 365(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131334 
     
This paper systematically studies Ni doping at Fe sites in La0.6Sr0.4Co0.3Fe0.7O3-δ (LSCF) as an intermediate temperature solid oxide fuel cell (IT-SOFC) electrode. The electrocatalytic activity of Ni-doped electrodes in oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) modes was analyzed, rather than individual cathode or anode. The results indicate that Ni doping increases the internal vacancies, ORR activity, and charge transfer ability of La0.6Sr0.4Co0.3Fe0.6Ni0.15O3-δ (LSCFN15). In addition, compared to LSCF, LSCFN15 also reduces the energy barriers for surface oxygen exchange and bulk diffusion, thereby increasing the overall ORR kinetic rate. Combined with the distribution of relaxation time (DRT) analysis, it was confirmed that Ni-doped LSCFN15 increased the adsorption and dissociation rates of oxygen. At 750 ℃, the area-specific resistance (ASR) of LSCFN15 reached 0.045 Ω cm2, which is only 58.4 % of LSCF (0.077 Ω cm2). As a SOFC cathode, the peak power density (PPD) reached 1175 mW cm−2, 1.31 times that of LSCF (898 mW cm−2). As a SOFC anode, the current exchange density of LSCFN15 in OER mode reaches 164 mA cm−2, which is higher than the 125 mA cm−2 of LSCF, indicating that LSCFN15 also has the potential to serve as an anode for SOFC. In addition, Ni doping reduces the thermal expansion coefficient of the electrode and improves its thermal compatibility with traditional electrolytes. As an electrode, LSCFN15 exhibits excellent long-term stability in both SOFC and SOEC modes. Overall, Ni-doped Fe-based perovskite can improve the ORR and OER activities while enhancing the stability of cell operation and is expected to obtain multifunctional SOFC electrode materials.    

    

* Robust and Corrosion‐Resistant Overall Water Splitting Electrode Enabled by Additive Manufacturing  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392186155
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202312216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392186155"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392186155"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392186155"))][Get cited by]]

OpenAlex: https://openalex.org/W4392186155 (Open access: False)
    
[[https://openalex.org/A5035069843][Binbin Guo]], [[https://openalex.org/A5005706497][Jui‐Teng Lin]], [[https://openalex.org/A5002622770][Funian Mo]], [[https://openalex.org/A5075316965][Yihong Ding]], [[https://openalex.org/A5058081404][Tianbiao Zeng]], [[https://openalex.org/A5000111419][Haowen Liang]], [[https://openalex.org/A5052787170][Liping Wang]], [[https://openalex.org/A5029676538][Xiaoteng Chen]], [[https://openalex.org/A5071628797][Jinpeng Mo]], [[https://openalex.org/A5039825340][Dongsheng Li]], [[https://openalex.org/A5082297990][Hui Ying Yang]], [[https://openalex.org/A5014315173][Jiaming Bai]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202312216 
     
Abstract Electrolysis of water has emerged as a prominent area of research in recent years. As a promising catalyst support, copper foam is widely investigated for electrolytic water, yet the insufficient mechanical strength and corrosion resistance render it less suitable for harsh working conditions. To exploit high‐performance catalyst supports, various metal supports are comprehensively evaluated, and Ti 6 Al 4 V (Ti64) support exhibited outstanding compression and corrosion resistance. With this in mind, a 3D porous Ti64 catalyst support is fabricated using the selective laser sintering (SLM) 3D printing technology, and a conductive layer of nickel (Ni) is coated to increase the electrical conductivity and facilitate the deposition of catalysts. Subsequently, Co 0.8 Ni 0.2 (CO 3 ) 0.5 (OH)·0.11H 2 O (CoNiCH) nanoneedles are deposited. The resulting porous Ti64/Ni/CoNiCH electrode displayed an impressive performance in the oxygen evolution reaction (OER) and reached 30 mA cm −2 at an overpotential of only 200 mV. Remarkably, even after being compressed at 15.04 MPa, no obvious structural deformation is observed, and the attenuation of its catalytic efficiency is negligible. Based on the computational analysis, the CoNiCH catalyst demonstrated superior catalytic activity at the Ni site in comparison to the Co site. Furthermore, the electrode reached 30 mA cm −2 at 1.75 V in full water splitting conditions and showed no significant performance degradation even after 60 h of continuous operation. This study presents an innovative approach to robust and corrosion‐resistant catalyst design.    

    

* Laser‐Synthesized Co‐Doped CuO Electrocatalyst: Unveiling Boosted Methanol Oxidation Kinetics for Enhanced Hydrogen Production Efficiency by In Situ/Operando Raman and Theoretical Analyses  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392186166
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smtd.202301628")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392186166"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392186166"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392186166"))][Get cited by]]

OpenAlex: https://openalex.org/W4392186166 (Open access: False)
    
[[https://openalex.org/A5025931538][Sieon Jung]], [[https://openalex.org/A5058019178][Raja Arumugam Senthil]], [[https://openalex.org/A5000061857][Ahreum Min]], [[https://openalex.org/A5087525540][Anuj Kumar]], [[https://openalex.org/A5011667598][Cheol Joo Moon]], [[https://openalex.org/A5067975222][Myong Yong Choi]], Small Methods. None(None)] 2024. https://doi.org/10.1002/smtd.202301628 
     
Abstract The present study details the strategic development of Co‐doped CuO nanostructures via sophisticated and expedited pulsed laser ablation in liquids (PLAL) technique. Subsequently, these structures are employed as potent electrocatalysts for the anodic methanol oxidation reaction (MOR), offering an alternative to the sluggish oxygen evolution reaction (OER). Electrochemical assessments indicate that the Co–CuO catalyst exhibits exceptional MOR activity, requiring a reduced potential of 1.42 V at 10 mA cm –2 compared to that of pure CuO catalyst (1.57 V at 10 mA cm –2 ). Impressively, the Co–CuO catalyst achieved a nearly 180 mV potential reduction in MOR compared to its OER performance (1.60 V at 10 mA cm −2 ). Furthermore, when pairing Co–CuO(+)ǀǀPt/C(−) in methanol electrolysis, the cell voltage required is only 1.51 V at 10 mA cm −2 , maintaining remarkable stability over 12 h. This represents a substantial voltage reduction of ≈160 mV relative to conventional water electrolysis (1.67 V at 10 mA cm −2 ). Additionally, both in situ /operando Raman spectroscopy studies and theoretical calculations have confirmed that Co‐doping plays a crucial role in enhancing the activity of the Co–CuO catalyst. This research introduces a novel synthetic approach for fabricating high‐efficiency electrocatalysts for large‐scale hydrogen production while co‐synthesizing value‐added formic acid.    

    

* Lattice-Matched Spinel/Layered Double Hydroxide 2d/2d Heterojunction Towards Large-Current-Density Overall Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392208263
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Layered Double Hydroxide Nanomaterials, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4741152")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392208263"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392208263"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392208263"))][Get cited by]]

OpenAlex: https://openalex.org/W4392208263 (Open access: False)
    
[[https://openalex.org/A5005627824][Jian Chen]], [[https://openalex.org/A5047244598][Lirong Zheng]], [[https://openalex.org/A5024948361][Zhenhua Li]], [[https://openalex.org/A5081440965][Yangen Zhou]], [[https://openalex.org/A5088069528][Yanqing Lai]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4741152 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Lattice-Matched Spinel/Layered Double Hydroxide 2d/2d Heterojunction Towards Large-Current-Density Overall Water Splitting 24 Pages Posted: 27 Feb 2024 See all articles by Jian ChenJian ChenCentral South UniversityZheng LiCentral South UniversityZhenhua LiCentral South UniversityYangen ZhouCentral South UniversityYanqing LaiCentral South University Abstract It is fascinating and challenging to construct earth-abundant first-row transition metal-based bifunctional electrocatalysts for large-scale hydrogen production via water electrolysis. Here we report a progressive conversion from spinel nanosheets to layered double hydroxide (LDH) nanosheets through the preferential dissolution of alternated layers in spinel. This process enables the formation of a lattice-matched and chemically bonded spinel/LDH 2D/2D heterojunction. Significant charge redistribution at the 2D/2D heterointerface accelerates water dissociation kinetics and optimize adsorption energy of hydrogen- and oxygen-containing intermediates. The synthesized CoFe2O4/CoFe-LDH 2D/2D heterojunction demonstrates exceptional performance in the hydrogen evolution reaction, achieving an overpotential of 337 mV at a high current density of 1000 mA cm-2, surpassing previously reported non-noble metal-based spinels and LDHs. Furthermore, its oxygen evolution reaction performance is comparable to that of typical spinel and LDH catalysts. The in-depth insights can guide rational interfacial engineering of heterogeneous catalysts for energy and environmental applications. Keywords: HER, OER, 2D/2D Heterojunction, Spinel oxides, layered double hydroxides Suggested Citation: Suggested Citation Chen, Jian and Li, Zheng and Li, Zhenhua and Zhou, Yangen and Lai, Yanqing, Lattice-Matched Spinel/Layered Double Hydroxide 2d/2d Heterojunction Towards Large-Current-Density Overall Water Splitting. Available at SSRN: https://ssrn.com/abstract=4741152 Jian Chen Central South University ( email ) Changsha, 410083China Zheng Li Central South University ( email ) Changsha, 410083China Zhenhua Li Central South University ( email ) Changsha, 410083China Yangen Zhou (Contact Author) Central South University ( email ) Changsha, 410083China Yanqing Lai Central South University ( email ) Changsha, 410083China Download This Paper Open PDF in Browser Do you have negative results from your research you’d like to share? Submit Negative Results Paper statistics Downloads 0 Abstract Views 2 53 References PlumX Metrics Feedback Feedback to SSRN Feedback (required) Email (required) Submit If you need immediate assistance, call 877-SSRNHelp (877 777 6435) in the United States, or +1 212 448 2500 outside of the United States, 8:30AM to 6:00PM U.S. Eastern, Monday - Friday.    

    

* A 3d-Printed Lab Scale 3-Electrode Holder for Zero-Gap Electrode Configuration  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392208348
:TOPICS: Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4741210")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392208348"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392208348"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392208348"))][Get cited by]]

OpenAlex: https://openalex.org/W4392208348 (Open access: False)
    
[[https://openalex.org/A5090155361][Fabian Luca Buchauer]], [[https://openalex.org/A5088746059][A. Russo]], [[https://openalex.org/A5018683322][Enzo Raffaele Moretti]], [[https://openalex.org/A5039089366][Sarmad Iqbal]], [[https://openalex.org/A5051181947][Mikkel Rykær Kraglund]], [[https://openalex.org/A5004729904][Christodoulos Chatzichristodoulou]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4741210 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL A 3d-Printed Lab Scale 3-Electrode Holder for Zero-Gap Electrode Configuration 15 Pages Posted: 27 Feb 2024 See all articles by Fabian Luca BuchauerFabian Luca Buchaueraffiliation not provided to SSRNAndrea Russoaffiliation not provided to SSRNEnzo Raffaele Morettiaffiliation not provided to SSRNSarmad Iqbalaffiliation not provided to SSRNMikkel Rykær KraglundTechnical University of DenmarkChristodoulos Chatzichristodoulouaffiliation not provided to SSRN Abstract Electrochemistry is key for green fuel and chemical production. In order to achieve low production costs required for large-scale deployment of e.g. electrolyzers, more active and stable catalyst materials for both anode and cathode are necessary. While extensive research efforts are devoted to this, most lab-scale catalyst testing is performed in either rotating disk electrodes or beaker-type cells that hardly reflect the operating conditions in a technological electrolyzer. While more realistic test setups are available commercially, they are usually expensive and complex. In this work, we provide a 3D-printable cell holder design that allows for lab-scale testing under zero-gap or controlled-gap electrode configuration while supporting the placement of a reference electrode in the middle of the separator. The customizable design can accommodate electrodes of various sizes and geometries (foam, mesh, foil, etc.). Polypropylene (PP) or high-performance thermoplastics like polyetheretherketone (PEEK) can be used as filaments, depending on the application. 3D-printing of the herein presented cell results in material savings of 70%, thereby reducing material waste and environmental impact. We demonstrate the holder in both zero-gap and controlled-gap configurations, assessing data quality and reproducibility, using Fe-free Ni electrodes in alkaline electrolysis as a test case. Furthermore, the holder was used during long-term stability testing at 60°C applying a fixed current density of 500mA/cm2 for more than 250h. The design is freely available for download as a CAD file. Keywords: Alkaline electrolysis, Test setup, Long-term stability, hydrogen evolution reaction, oxygen evolution reaction Suggested Citation: Suggested Citation Buchauer, Fabian Luca and Russo, Andrea and Moretti, Enzo Raffaele and Iqbal, Sarmad and Kraglund, Mikkel Rykær and Chatzichristodoulou, Christodoulos, A 3d-Printed Lab Scale 3-Electrode Holder for Zero-Gap Electrode Configuration. Available at SSRN: https://ssrn.com/abstract=4741210 Fabian Luca Buchauer (Contact Author) affiliation not provided to SSRN ( email ) No Address Available Andrea Russo affiliation not provided to SSRN ( email ) No Address Available Enzo Raffaele Moretti affiliation not provided to SSRN ( email ) No Address Available Sarmad Iqbal affiliation not provided to SSRN ( email ) No Address Available Mikkel Rykær Kraglund Technical University of Denmark ( email ) Anker Engelunds Vej 1Building 101ALyngby, 2800Denmark Christodoulos Chatzichristodoulou affiliation not provided to SSRN ( email ) No Address Available Download This Paper Open PDF in Browser Do you have negative results from your research you’d like to share? Submit Negative Results Paper statistics Downloads 0 Abstract Views 7 PlumX Metrics Feedback Feedback to SSRN Feedback (required) Email (required) Submit If you need immediate assistance, call 877-SSRNHelp (877 777 6435) in the United States, or +1 212 448 2500 outside of the United States, 8:30AM to 6:00PM U.S. Eastern, Monday - Friday.    

    

* Unraveling the atomic interdiffusion mechanism of NiFe2O4 oxygen carriers during chemical looping CO2 conversion  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392199435
:TOPICS: Chemical-Looping Technologies, Solid Oxide Fuel Cells, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cey2.493")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392199435"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392199435"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392199435"))][Get cited by]]

OpenAlex: https://openalex.org/W4392199435 (Open access: True)
    
[[https://openalex.org/A5072341456][Da Song]], [[https://openalex.org/A5044483333][Yan Lin]], [[https://openalex.org/A5016212470][Shiwen Fang]], [[https://openalex.org/A5047083341][Li Yang]], [[https://openalex.org/A5090929533][Kun Zhao]], [[https://openalex.org/A5042123915][Xinfei Chen]], [[https://openalex.org/A5026838244][Zhen Huang]], [[https://openalex.org/A5043624439][Fang He]], [[https://openalex.org/A5059653492][Zengli Zhao]], [[https://openalex.org/A5035378307][Hongyu Huang]], [[https://openalex.org/A5081461600][Fanxing Li]], Carbon energy. None(None)] 2024. https://doi.org/10.1002/cey2.493  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cey2.493][pdf]])
     
Abstract By employing metal oxides as oxygen carriers, chemical looping demonstrates its effectiveness in transferring oxygen between reduction and oxidation environments to partially oxidize fuels into syngas and convert CO 2 into CO. Generally, NiFe 2 O 4 oxygen carriers have demonstrated remarkable efficiency in chemical looping CO 2 conversion. Nevertheless, the intricate process of atomic migration and evolution within the internal structure of bimetallic oxygen carriers during continuous high‐temperature redox cycling remains unclear. Consequently, the lack of a fundamental understanding of the complex ionic migration and oxygen transfer associated with energy conversion processes hampers the design of high‐performance oxygen carriers. Thus, in this study, we employed in situ characterization techniques and theoretical calculations to investigate the ion migration behavior and structural evolution in the bulk of NiFe 2 O 4 oxygen carriers during H 2 reduction and CO 2 /lab air oxidation cycles. We discovered that during the H 2 reduction step, lattice oxygen rapidly migrates to vacancy layers to replenish consumed active oxygen species, while Ni leaches from the material and migrates to the surface. During the CO 2 splitting step, Ni migrates toward the core of the bimetallic oxygen carrier, forming Fe–Ni alloys. During the air oxidation step, Fe–Ni migrates outward, creating a hollow structure owing to the Kirkendall effect triggered by the swift transfer of lattice oxygen. The metal atom migration paths depend on the oxygen transfer rates. These discoveries highlight the significance of regulating the release–recovery rate of lattice oxygen to uphold the structures and reactivity of oxygen carriers. This work offers a comprehensive understanding of the oxidation/reduction‐driven atomic interdiffusion behavior of bimetallic oxygen carriers.    

    

* A nickel-modified perovskite-supported iron oxide oxygen carrier for chemical looping dry reforming of methane for syngas production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392202787
:TOPICS: Chemical-Looping Technologies, Catalytic Carbon Dioxide Hydrogenation, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150033")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392202787"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392202787"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392202787"))][Get cited by]]

OpenAlex: https://openalex.org/W4392202787 (Open access: False)
    
[[https://openalex.org/A5079007017][Qiong Rao]], [[https://openalex.org/A5082223185][Jinrui Zhang]], [[https://openalex.org/A5004060675][Tianlong Yang]], [[https://openalex.org/A5064842058][Yang Li]], [[https://openalex.org/A5060336991][Zhongrui Gai]], [[https://openalex.org/A5031498126][Li Peng]], [[https://openalex.org/A5091313861][Xuyun Wang]], [[https://openalex.org/A5082839498][Ying Pan]], [[https://openalex.org/A5000991486][Hongguang Jin]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150033 
     
The chemical looping dry reforming of methane (CLDRM) process, which converts methane and carbon dioxide into syngas, is an environmentally friendly greenhouse gas utilization strategy. In this work, it is demonstrated that a nickel-modified perovskite-supported iron-based oxygen carrier (Ni-Fe2O3/La0.8Sr0.2FeO3) significantly enhances the reactivity of CLDRM in the temperature range of 770–800 °C while maintaining high CO selectivity and oxygen capacity, as well as good carbon deposition resistance. With the addition of nickel, the methane conversion is 52 % higher than that without nickel at 800 °C. Rational coupling of the oxygen carrier components achieves over 99 % CO selectivity. 160 consecutive isothermal cycles confirm the outstanding stability of Ni-Fe2O3/La0.8Sr0.2FeO3. Based on the experimental results and characterizations, the evolution scheme and synergistic effects between the components of the Ni-Fe2O3/La0.8Sr0.2FeO3 oxygen carrier for CLDRM reaction are proposed. The results provide a pathway for oxygen carrier design to decrease the reforming temperature while maintaining excellent reaction performance in iron-based chemical looping systems.    

    

* Fe, Co-Induced Hydrolysis to Prepare Α-Ni (Oh)2/Β-Ni(Oh)2 Interfaces for Improved Overall Water Splitting Efficiency  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392208337
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Atomic Layer Deposition Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4741208")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392208337"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392208337"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392208337"))][Get cited by]]

OpenAlex: https://openalex.org/W4392208337 (Open access: False)
    
[[https://openalex.org/A5090101808][Guoxu Zhou]], [[https://openalex.org/A5047002691][Zining Wang]], [[https://openalex.org/A5052856934][Xichun Zhang]], [[https://openalex.org/A5006134133][Shan Ji]], [[https://openalex.org/A5054435515][Rongfang Wang]], [[https://openalex.org/A5076272779][Xianguo Ma]], [[https://openalex.org/A5044387079][Xunyun Wang]], [[https://openalex.org/A5040493082][Vladimir Linkov]], [[https://openalex.org/A5090366405][Hui Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4741208 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Fe, Co-Induced Hydrolysis to Prepare Α-Ni (Oh)2/Β-Ni(Oh)2 Interfaces for Improved Overall Water Splitting Efficiency 30 Pages Posted: 27 Feb 2024 See all articles by Guoxu ZhouGuoxu ZhouQingdao University of Science and TechnologyZining WangTongji UniversityXichun ZhangQingdao University of Science and TechnologyShan JiJiaxing UniversityRongfang WangQingdao University of Science and TechnologyXianguo MaGuizhou Institute of TechnologyXunyun WangQingdao University of Science and TechnologyVladimir LinkovUniversity of the Western CapeHui WangQingdao University of Science and Technology There are 2 versions of this paper Fe, Co-Induced Hydrolysis to Prepare Α-Ni (Oh)2/Β-Ni(Oh)2 Interfaces for Improved Overall Water Splitting Efficiency Number of pages: 30 Posted: 27 Feb 2024 You are currently viewing this paper Fe, Co-Induced Hydrolysis to Prepare Α-Ni (Oh)2/Β-Ni(Oh)2 Interfaces for Improved Overall Water Splitting Efficiency Number of pages: 30 Posted: 24 Dec 2023 Downloads 10 Abstract The development of effective bifunctional electrode materials is necessary for worldwide adoption of large-scale hydrogen production by water electrolysis. Nickel hydroxide - based transition metal materials are among the most promising electrodes for the hydrogen evolution reaction (HER) and the oxygen evolution reaction (OER). While Ni(OH)2 exists in two crystalline states, namely α-Ni(OH)2 and β-Ni(OH)2, neither can meet requirements for effective bifunctional electrode materials on their own, due to relatively low catalytic activity. In this study, bifunctional catalysts with α-Ni(OH)2/β-Ni(OH)2 interfaces, prepared using Fe, Co-induced hydrolysis, have been successfully applied for electrolytic water splitting. According to physical characterization, Fe3+ and Co2+ are incorporated into Ni(OH)2 layers, where Fe doping leads to the formation of a regular flake structure, while Co doping facilitates surface electron transfer, enhancing electrocatalytic activity towards HER and OER. Overpotentials of the obtained catalysts at 100 mA·cm-2 are as low as 224 mV for HER and 324 mV for OER. Both HER and OER overpotentials remained almost unchanged after 24 h operation at a high current density of 1 A·cm-2, demonstrating excellent stability of the newly prepared materials during water electrolysis. The synthesis of α-Ni(OH)2/β-Ni(OH)2 interfaces is a new direction for the manufacturing of industrially applicable water splitting electrocatalysts suitable for high current density operation. Keywords: hydrolysis effect, α-Ni(OH)2/β-Ni(OH)2 interfaces, high current density, overall water splitting, excellent stability Suggested Citation: Suggested Citation Zhou, Guoxu and Wang, Zining and Zhang, Xichun and Ji, Shan and Wang, Rongfang and Ma, Xianguo and Wang, Xunyun and Linkov, Vladimir and Wang, Hui, Fe, Co-Induced Hydrolysis to Prepare Α-Ni (Oh)2/Β-Ni(Oh)2 Interfaces for Improved Overall Water Splitting Efficiency. Available at SSRN: https://ssrn.com/abstract=4741208 Guoxu Zhou Qingdao University of Science and Technology ( email ) Qingdao, 266042China Zining Wang Tongji University ( email ) 1239 Siping RoadShanghai, 200092China Xichun Zhang Qingdao University of Science and Technology ( email ) Qingdao, 266042China Shan Ji Jiaxing University ( email ) ZhejiangChina Rongfang Wang Qingdao University of Science and Technology ( email ) Qingdao, 266042China Xianguo Ma Guizhou Institute of Technology ( email ) chinaUnited States Xunyun Wang Qingdao University of Science and Technology ( email ) Qingdao, 266042China Vladimir Linkov University of the Western Cape ( email ) Robert Sobukwe RoadBellville, 7535South Africa Hui Wang (Contact Author) Qingdao University of Science and Technology ( email ) Download This Paper Open PDF in Browser Do you have negative results from your research you’d like to share? Submit Negative Results Paper statistics Downloads 0 Abstract Views 9 53 References PlumX Metrics Feedback Feedback to SSRN Feedback (required) Email (required) Submit If you need immediate assistance, call 877-SSRNHelp (877 777 6435) in the United States, or +1 212 448 2500 outside of the United States, 8:30AM to 6:00PM U.S. Eastern, Monday - Friday.    

    

* Front Matter  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392267369
:TOPICS: 
:PUBLICATION_DATE: 1997-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1520/stp13807s")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392267369"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392267369"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392267369"))][Get cited by]]

OpenAlex: https://openalex.org/W4392267369 (Open access: False)
    
, No host. None(None)] 1997. https://doi.org/10.1520/stp13807s 
     
STP 1326 features the most current information from the world's leading experts on innovative methods describing the physical properties and oxidative behavior of polymers, lubricants and petrochemicals. 18 comprehensive papers, including two key-note addresses, are divided into two major categories: Oxidative Behavior of Polymers and Petrochemicals, and Instrumental Techniques — Oxidation Induction Processes. Topics covered include: Factors impacting the oxidation induction time (OIT) • Oxidation measurement in formulated passenger car and diesel engine oils • Polymer oxidation • Temperature effects on thermal and oxidative processes • Oxygen diffusion rate limitations • Additive effectiveness • The evolution of oxidation systems • Innovative test and robotic methods • New reference standards • Bias considerations.    

    

* Air‐Promoted Light‐Driven Hydrogen Production from Bioethanol over Core/Shell Cr2O3@GaN Nanoarchitecture  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392196147
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Materials and Methods for Hydrogen Storage, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202400011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392196147"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392196147"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392196147"))][Get cited by]]

OpenAlex: https://openalex.org/W4392196147 (Open access: False)
    
[[https://openalex.org/A5079702656][Zhouzhou Wang]], [[https://openalex.org/A5015402957][Yiqing Chen]], [[https://openalex.org/A5014362602][Bowen Sheng]], [[https://openalex.org/A5047612561][Jinglin Li]], [[https://openalex.org/A5010497745][Lin Yao]], [[https://openalex.org/A5077909232][Ying Yu]], [[https://openalex.org/A5081444975][Jun Song]], [[https://openalex.org/A5073191432][Tianqi Yu]], [[https://openalex.org/A5089669072][Yixin Li]], [[https://openalex.org/A5053786338][Hongge Pan]], [[https://openalex.org/A5009983145][Ping Wang]], [[https://openalex.org/A5018896619][Xinqiang Wang]], [[https://openalex.org/A5042265316][Lei Zhu]], [[https://openalex.org/A5010878103][Baowen Zhou]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202400011 
     
Light‐driven hydrogen production from biomass derivatives offers a path towards carbon neutrality. It is often however operated with the limitations of sluggish kinetics and severe coking. Herein, a disruptive air‐promoted strategy is explored for efficient and durable light‐driven hydrogen production from ethanol over a core/shell Cr2O3@GaN nanoarchitecture. The correlative computational and experimental investigations show ethanol is energetically favorable to be adsorbed on the Cr2O3@GaN interface, followed by dehydrogenation toward acetaldehyde and protons by photoexcited holes. The released protons are then consumed for H2 evolution by photogenerated electrons. Afterward, O2 can be evolved into active oxygen species and promote the deprotonation and C‐C cleavage of the key C2 intermediate, thus significantly lowering the reaction energy barrier of hydrogen evolution and removing the carbon residual with inhibited overoxidation. Consequently, hydrogen is produced at a high rate of 76.9 mole H2 per gram Cr2O3@GaN per hour by only feeding ethanol, air, and light, leading to the achievement of a turnover number of 266,943,000 mole H2 per mole Cr2O3 over a long‐term operation of 180 hours. Notably, an unprecedented light‐to‐hydrogen efficiency of 17.6% is achieved under concentrated light illumination. The simultaneous generation of aldehyde from ethanol dehydrogenation enables the process more economically promising.    

    

* Air‐Promoted Light‐Driven Hydrogen Production from Bioethanol over Core/Shell Cr2O3@GaN Nanoarchitecture  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392196481
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Materials and Methods for Hydrogen Storage, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202400011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392196481"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392196481"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392196481"))][Get cited by]]

OpenAlex: https://openalex.org/W4392196481 (Open access: False)
    
[[https://openalex.org/A5079702656][Zhouzhou Wang]], [[https://openalex.org/A5015402957][Yiqing Chen]], [[https://openalex.org/A5014362602][Bowen Sheng]], [[https://openalex.org/A5047612561][Jinglin Li]], [[https://openalex.org/A5010497745][Lin Yao]], [[https://openalex.org/A5077909232][Ying Yu]], [[https://openalex.org/A5081444975][Jun Song]], [[https://openalex.org/A5073191432][Tianqi Yu]], [[https://openalex.org/A5089669072][Yixin Li]], [[https://openalex.org/A5053786338][Hongge Pan]], [[https://openalex.org/A5009983145][Ping Wang]], [[https://openalex.org/A5074432763][Xinqiang Wang]], [[https://openalex.org/A5042265316][Lei Zhu]], [[https://openalex.org/A5010878103][Baowen Zhou]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202400011 
     
Light‐driven hydrogen production from biomass derivatives offers a path towards carbon neutrality. It is often however operated with the limitations of sluggish kinetics and severe coking. Herein, a disruptive air‐promoted strategy is explored for efficient and durable light‐driven hydrogen production from ethanol over a core/shell Cr2O3@GaN nanoarchitecture. The correlative computational and experimental investigations show ethanol is energetically favorable to be adsorbed on the Cr2O3@GaN interface, followed by dehydrogenation toward acetaldehyde and protons by photoexcited holes. The released protons are then consumed for H2 evolution by photogenerated electrons. Afterward, O2 can be evolved into active oxygen species and promote the deprotonation and C‐C cleavage of the key C2 intermediate, thus significantly lowering the reaction energy barrier of hydrogen evolution and removing the carbon residual with inhibited overoxidation. Consequently, hydrogen is produced at a high rate of 76.9 mole H2 per gram Cr2O3@GaN per hour by only feeding ethanol, air, and light, leading to the achievement of a turnover number of 266,943,000 mole H2 per mole Cr2O3 over a long‐term operation of 180 hours. Notably, an unprecedented light‐to‐hydrogen efficiency of 17.6% is achieved under concentrated light illumination. The simultaneous generation of aldehyde from ethanol dehydrogenation enables the process more economically promising.    

    

* Photoreceptor-induced LHL4 protects photosystem II inChlamydomonas reinhardtii  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392185985
:TOPICS: Molecular Mechanisms of Photosynthesis and Photoprotection, Light Signal Transduction in Plants, Microalgae as a Source for Biofuels Production
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2024.02.23.581703")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392185985"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392185985"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392185985"))][Get cited by]]

OpenAlex: https://openalex.org/W4392185985 (Open access: True)
    
[[https://openalex.org/A5094009515][Marie Dannay]], [[https://openalex.org/A5080373536][C. Bertin]], [[https://openalex.org/A5093861858][Eva Cavallari]], [[https://openalex.org/A5011133849][Pascal Albanese]], [[https://openalex.org/A5076624912][Dimitri Tolleter]], [[https://openalex.org/A5002465160][Cécile Giustini]], [[https://openalex.org/A5033402628][Mathilde Menneteau]], [[https://openalex.org/A5076178507][Sabine Brugière]], [[https://openalex.org/A5085954072][Yohann Couté]], [[https://openalex.org/A5028356813][Guido Finazzi]], [[https://openalex.org/A5086855287][Emilie Demarsy]], [[https://openalex.org/A5060917610][Roman Ulm]], [[https://openalex.org/A5084675262][Guillaume Allorent]], bioRxiv (Cold Spring Harbor Laboratory). None(None)] 2024. https://doi.org/10.1101/2024.02.23.581703  ([[https://www.biorxiv.org/content/biorxiv/early/2024/02/23/2024.02.23.581703.full.pdf][pdf]])
     
Abstract Photosynthesis, the fundamental process using light energy to convert CO 2 to organic matter, is vital for life on Earth. It relies on capturing light through light-harvesting complexes in evolutionarily well-conserved photosystems (PS) I and II and on the conversion of light energy into chemical energy. Composition and organization of both photosystem core complexes are well conserved across evolution. PSII is particularly sensitive to photodamage but benefits from a large diversity of photoprotective mechanisms, finely tuned for the specific light conditions. Light Harvesting Complex protein family members (LHC and LHC-like families) have acquired a dual function during evolution. Members of the LHC antenna complexes of photosystems capture light energy whereas others dissipate excess energy that cannot be harnessed for photosynthesis. This process mainly occurs through non photochemical quenching (NPQ). In this work, we focus on the LHL4 protein, which is a LHC-like protein induced by UV-B and blue light photoreceptor signaling pathways in the model green microalgae Chlamydomonas reinhardtii . We demonstrate that alongside established NPQ effectors, LHL4 plays a key role in photoprotection, preventing singlet oxygen accumulation in PSII and promoting cell survival upon light stress. LHL4 protective function is distinct from that of NPQ-related proteins, as it specifically and uniquely binds to the transient monomeric form of the core PSII complex, safeguarding its integrity. LHL4 characterization expands our understanding of the interplay between light harvesting and photoprotection mechanisms upon light stress in photosynthetic microalgae.    

    

* Electrochemical Reduction of Flue Gas Denitrification Wastewater to Ammonia Using a Dual-Defective Cu2O@Cu Heterojunction Electrode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392186963
:TOPICS: Ammonia Synthesis and Electrocatalysis, Content-Centric Networking for Information Delivery, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.est.3c09811")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392186963"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392186963"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392186963"))][Get cited by]]

OpenAlex: https://openalex.org/W4392186963 (Open access: False)
    
[[https://openalex.org/A5049615690][Runlong Hao]], [[https://openalex.org/A5081314881][Yunchang Song]], [[https://openalex.org/A5041056226][Liuyan Yang]], [[https://openalex.org/A5005019318][Yongxue Guo]], [[https://openalex.org/A5068824319][Xuanhao Wu]], [[https://openalex.org/A5047876800][Zhao Ma]], [[https://openalex.org/A5015633793][Z. Qian]], [[https://openalex.org/A5000372526][Feng Liu]], [[https://openalex.org/A5069987608][Li Dong Wang]], Environmental Science & Technology. None(None)] 2024. https://doi.org/10.1021/acs.est.3c09811 
     
Wet flue gas denitrification offers a new route to convert industrial nitrogen oxides (NOx) into highly concentrated nitrate wastewater, from which the nitrogen resource can be recovered to ammonia (NH3) via electrochemical nitrate reduction reactions (NITRRs). Low-cost, scalable, and efficient cathodic materials need to be developed to enhance the NH3 production rate. Here, in situ electrodeposition was adopted to fabricate a foamy Cu-based heterojunction electrode containing both Cu-defects and oxygen vacancy loaded Cu2O (OVs-Cu2O), which achieved an NH3 yield rate of 3.59 mmol h–1 cm–2, NH3 Faradaic efficiency of 99.5%, and NH3 selectivity of 100%. Characterizations and theoretical calculations unveiled that the Cu-defects and OVs-Cu2O heterojunction boosted the H* yield, suppressed the hydrogen evolution reaction (HER), and served as dual reaction sites to coherently match the tandem reactions kinetics of NO3-to-NO2 and NO2-to-NH3. An integrated system was further built to combine wet flue gas denitrification and desulfurization, simultaneously converting NO and SO2 to produce the (NH4)2SO4 fertilizer. This study offers new insights into the application of low-cost Cu-based cathode for electrochemically driven wet denitrification wastewater valorization.    

    

* Current progress in heterojunctions based on Nb2O5 for photocatalytic water treatment and energy applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392204011
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.molliq.2024.124360")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392204011"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392204011"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392204011"))][Get cited by]]

OpenAlex: https://openalex.org/W4392204011 (Open access: False)
    
[[https://openalex.org/A5001364732][Amit Kumar]], [[https://openalex.org/A5031533917][Sahil Rana]], [[https://openalex.org/A5031773624][Pooja Dhiman]], [[https://openalex.org/A5058967285][Gaurav Sharma]], [[https://openalex.org/A5073987958][Florian J. Stadler]], Journal of Molecular Liquids. None(None)] 2024. https://doi.org/10.1016/j.molliq.2024.124360 
     
Significant advancements in the field of photocatalysis in recent years have highlighted the heterojunctions based on Nb2O5 as a focal point of research. This comprehensive review diligently analyses the progress in Nb2O5-based heterojunctions for their application in photocatalysis, focusing on synthesis, characteristics and their pivotal role in addressing crucial energy and environmental challenges. The review emphasizes the fundamental principles of photocatalysis in pollutant removal and H2 generation, elucidating key processes such as light absorption, charge generation and surface reactions. The different types of heterojunctions, their basic principles and role in enhancing the charge separation and overall photocatlytic performance have been discussed. The recent advances in Nb2O5-based heterojunctions are extensively discussed for the photocatalytic applications such as pollutants removal and H2 evolution. Furthermore, the review delves into strategies employed to enhance the photocatalytic activity of Nb2O5-based heterojunctions such as doping, oxygen vacancies modification, morphological engineering and atomic control, as well as loading with support materials. Each strategy is explained, emphasizing its impact on charge separation and overall efficiency. The review concludes by highlighting existing challenges and providing insights into potential future directions that integrates synthetic processes, novel methods for photoelectric characterization, and an in-depth understanding of the local structure of Nb2O5. This review serves as a valuable resource for researchers in the field, offering a comprehensive overview of the state-of-the-art in Nb2O5-based heterojunctions for advanced photocatalytic applications.    

    

* Electrochemically Induced Ru/CoOOH Synergistic Catalyst as Bifunctional Electrode Materials for Alkaline Overall Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392186966
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202311884")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392186966"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392186966"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392186966"))][Get cited by]]

OpenAlex: https://openalex.org/W4392186966 (Open access: False)
    
[[https://openalex.org/A5077737058][Yan Ma]], [[https://openalex.org/A5083770692][Yuan Ha]], [[https://openalex.org/A5032472230][Liangqiang Chen]], [[https://openalex.org/A5014560149][Ziqi An]], [[https://openalex.org/A5053736386][Xing Liu]], [[https://openalex.org/A5087227415][Zhenni Wang]], [[https://openalex.org/A5080276547][Zhimin Li]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202311884 
     
Abstract Efficient and affordable price bifunctional electrocatalysts based on transition metal oxides for oxygen and hydrogen evolution reactions have a balanced efficiency, but it remains a significant challenge to control their activity and durability. Herein, a trace Ru (0.74 wt.%) decorated ultrathin CoOOH nanosheets (≈4 nm) supported on the surface of nickel foam (Ru/CoOOH@NF) is rationally designed via an electrochemically induced strategy to effectively drive the electrolysis of alkaline overall water splitting. The as‐synthesized Ru/CoOOH@NF electrocatalysts integrate the advantages of a large number of different HER (Ru nanoclusters) and OER (CoOOH nanosheets) active sites as well as strong in‐suit structure stability, thereby exhibiting exceptional catalytic activity. In particular, the ultra‐low overpotential of the HER (36 mV) and the OER (264 mV) are implemented to achieve 10 mA cm −2 . Experimental and theoretical calculations also reveal that Ru/CoOOH@NF possesses high intrinsic conductivity, which facilitates electron release from H 2 O and H‐OH bond breakage and accelerates electron/mass transfer by regulating the charge distribution. This work provides a new avenue for the rational design of low‐cost and high‐activity bifunctional electrocatalysts for large‐scale water‐splitting technology and expects to help contribute to the creation of various hybrid electrocatalysts.    

    
