#+TITLE: water splitting
Description: water splitting papers
Created on Thu Jun 13 01:08:17 2024

Found 45 results from 2024-06-06 to 2024-06-13
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Vacancy Mediated Electrooxidation of 5‐Hydroxymethyl Furfuryl Using Defect Engineered Layered Double Hydroxide Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399355849
:TOPICS: Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors, Catalytic Conversion of Biomass to Fuels and Chemicals
:PUBLICATION_DATE: 2024-06-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202400676")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399355849"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399355849"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399355849"))][Get cited by]]

OpenAlex: https://openalex.org/W4399355849 (Open access: False)
    
[[https://openalex.org/A5052178810][Muhammad Zubair]], [[https://openalex.org/A5007275934][Pavel M. Usov]], [[https://openalex.org/A5077549415][Hiroyoshi Ohtsu]], [[https://openalex.org/A5067007716][Jodie A. Yuwono]], [[https://openalex.org/A5054142686][Carter S. Gerke]], [[https://openalex.org/A5031633022][Gregory D. Foley]], [[https://openalex.org/A5091519108][Haira G. Hackbarth]], [[https://openalex.org/A5044168251][Richard F. Webster]], [[https://openalex.org/A5079625567][Yintang Yang]], [[https://openalex.org/A5013302657][William Hadinata Lie]], [[https://openalex.org/A5053180714][Zhipeng Ma]], [[https://openalex.org/A5040663143][Lars Thomsen]], [[https://openalex.org/A5048557783][Masaki Kawano]], [[https://openalex.org/A5060108388][Nicholas M. Bedford]], Advanced energy materials. None(None)] 2024. https://doi.org/10.1002/aenm.202400676 
     
Abstract Electrochemical biomass oxidation coupled with hydrogen evolution offers a promising route to generate value‐added chemicals and clean energy. The complex adsorption behavior of 5‐hydroxymethyl furfural (HMF) and hydroxyl ions (OH − ) on the electrocatalyst surface during HMF electrooxidation reaction (HMFOR) necessitates an in‐depth understanding of active sites available for adsorption. Herein, oxygen vacancy (V O ) defects are introduced in NiFe layered double hydroxide (LDH) using Ce dopants to manipulate electronic structure. Synchrotron‐based HE‐XRD and XAS indicate negligible V O in La‐doped NiFe while Ce doping leads to V O defects due to flexible Ce redox (Ce 3+ ↔ Ce 4+ ). The V O ‐rich Ce‐NiFe exhibits higher Faradic efficiency of ≈90% to produce 2,5‐furan dicarboxylic acid (FDCA), far greater than ≈60% for NiFe V O in Ce‐NiFe act as alternative active sites for OH − adsorption, hence reducing adsorption competition for the same metal sites. DFT calculation results corroborate experimental findings by showcasing that the presence of V O in Ce‐NiFe manipulates the adsorption energies and facilitates the chemical adsorption OH − in V O to improve HMFOR. In situ HE‐XRD derived pair distribution function coupled to RMC simulations confirm OH − trapping in V O and HMF adsorption on metal centers as evident by interlayer distance evolution. Taken together, this work showcases routes for dual‐site electrocatalyst design for improved biomass electrooxidation.    

    

* Engineering antibonding orbital occupancy of NiMoO4-supported Ru nanoparticles for enhanced chlorine evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399357409
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.06.023")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399357409"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399357409"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399357409"))][Get cited by]]

OpenAlex: https://openalex.org/W4399357409 (Open access: False)
    
[[https://openalex.org/A5074676938][D. W. Zhang]], [[https://openalex.org/A5001141405][Haiming Gong]], [[https://openalex.org/A5013297039][Tao Liu]], [[https://openalex.org/A5065418938][Yuanyuan Wang]], [[https://openalex.org/A5081369869][Panyong Kuang]], Journal of colloid and interface science. 672(None)] 2024. https://doi.org/10.1016/j.jcis.2024.06.023 
     
Chlorine evolution reaction (CER) is crucial for industrial-scale production of high-purity Cl2. Despite the development of classical dimensionally stable anodes to enhance CER efficiency, the competitive oxygen evolution reaction (OER) remains a barrier to achieving high Cl2 selectivity. Herein, a binder-free electrode, Ru nanoparticles (NPs)-decorated NiMoO4 nanorod arrays (NRAs) supported on Ti foam (Ru-NiMoO4/Ti), was designed for active CER in saturated NaCl solution (pH = 2). The Ru-NiMoO4/Ti electrode exhibits a low overpotential of 20 mV at 10 mA cm−2 current density, a high Cl2 selectivity exceeding 90 %, and robust durability for 90 h operation. The marked difference in Tafel slopes between CER and OER indicates the high Cl2 selectivity and superior reaction kinetics of Ru-NiMoO4/Ti electrode. Further studies reveal a strong metal-support interaction (SMSI) between Ru and NiMoO4, facilitating electron transfer through the Ru–O bridge bond and increasing the Ru 3d–Cl 2p antibonding orbital occupancy, which eventually results in weakened Ru–Cl bonding, promoted Cl desorption, and enhanced Cl2 evolution. Our findings provide new insights into developing electrodes with enhanced CER performance through antibonding orbital occupancy engineering.    

    

* Prediction of Feasibility of Polaronic OER on the (110) Surface of Rutile TiO2  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399359402
:TOPICS: Surface Analysis and Electron Spectroscopy Techniques, X-ray Absorption Spectroscopy, Development of High-Efficiency Photocathodes for Electron Sources
:PUBLICATION_DATE: 2024-06-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cphc.202400523")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399359402"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399359402"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399359402"))][Get cited by]]

OpenAlex: https://openalex.org/W4399359402 (Open access: True)
    
[[https://openalex.org/A5001727106][Hori Pada Sarker]], [[https://openalex.org/A5014248031][Frank Abild‐Pedersen]], [[https://openalex.org/A5067205287][Michal Bajdich]], ChemPhysChem. 25(11)] 2024. https://doi.org/10.1002/cphc.202400523  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cphc.202400523][pdf]])
     
Abstract The front cover artwork is provided by Dr. Hori Pada Sarker from Dr. Frank Abild‐Pedersen's research group at the SLAC National Accelerator Laboratory. The image shows the generation of photoexcited carriers (electrons and holes) and the subsequent formation of hole polaron in rutile TiO 2 during oxygen evolution reaction (OER). Read the full text of the Research Article at 10.1002/cphc.202400060 .    

    

* Self‐Powered Electrochemical CO2 Conversion Enabled by a Multifunctional Carbon‐Based Electrocatalyst and a Rechargeable Zn–Air Battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399359807
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202401766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399359807"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399359807"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399359807"))][Get cited by]]

OpenAlex: https://openalex.org/W4399359807 (Open access: False)
    
[[https://openalex.org/A5072916605][Jingrui Han]], [[https://openalex.org/A5016096115][Lei Shi]], [[https://openalex.org/A5058131010][Huamei Xie]], [[https://openalex.org/A5027039231][Ruilin Song]], [[https://openalex.org/A5058380236][Dan Wang]], [[https://openalex.org/A5075927344][Dong Liu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202401766 
     
Abstract Multifunctional electrocatalysts are required for diverse clean energy‐related technologies (e.g., electrochemical CO 2 reduction reaction (CO 2 RR) and metal–air batteries). Herein, a nitrogen and fluorine co‐doped carbon nanotube (NFCNT) is reported to simultaneously achieve multifunctional catalytic activities for CO 2 RR, oxygen reduction reaction (ORR), and oxygen evolution reaction (OER). Theoretical calculations reveal that the superior multifunctional catalytic activities of NFCNT are attributed to the synergistic effect of nitrogen and fluorine co‐doping to induce charge redistribution and decrease the energy barrier of rate‐determining step for different electrocatalytic reactions. Furthermore, the rechargeable Zn–air battery (ZAB) with NFCNT electrode delivers a high peak power density of 230 mW cm −2 and superior durability over 100 cycles, outperforming the ZAB with Pt/C+RuO 2 based electrodes. More importantly, a self‐driven CO 2 electrolysis unit powered by the as‐assembled ZABs is developed, which achieves 80% CO Faraday efficiency and 60% total energy efficiency. This work provides a new insight into the exploration of highly efficient multifunctional carbon‐based electrocatalysts for novel energy‐related applications.    

    

* Vanadium‐Doped Heterogeneous Bimetallic Phosphides Derived from Layered Double Hydroxides for Saline Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399360497
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202402250")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399360497"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399360497"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399360497"))][Get cited by]]

OpenAlex: https://openalex.org/W4399360497 (Open access: False)
    
[[https://openalex.org/A5078018786][Yixuan Li]], [[https://openalex.org/A5027280914][Jiahui Jiang]], [[https://openalex.org/A5034269122][Qing Wu]], [[https://openalex.org/A5004990899][Yi Feng]], [[https://openalex.org/A5070185260][Zhongxu Chen]], [[https://openalex.org/A5007599353][Guan‐Cheng Xu]], [[https://openalex.org/A5034396732][Li Zhang]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202402250 
     
Abstract The development of energy‐ and time‐saving synthetic methods to prepare bifunctional and high stability catalysts are vital for overall water splitting. Here, V‐doped nickel‐iron hydroxide precursor by etching NiFe foam (NFF) at room temperature with dual chloride solution (“NaCl‐VCl3”), is obtained then phosphating to obtain V‐Ni 2 P‐FeP/NFF as efficient bifunctional (oxygen/hydrogen exchange reaction, OER/HER) electrocatalysts, denoted as NFF(V, Na)‐P. The NFF(V, Na)‐P requires only 185 and 117 mV overpotentials to reach 10 mA cm −2 for OER and HER. When used as a catalyst for water splitting in a full cell, it can be stably sustained for more than 1000 h in alkaline brine electrolysis at both current densities of 100 and 500 mA cm −2 . In situ Raman analyses and density functional theory (DFT) show that the V‐doping‐induced surface remodeling generates hydroxyl oxides as the true catalytic active centers, which not only enhances the reaction kinetics, but also reduces the free energy change in the rate‐determining step. This work provides a cost‐effective substrate self‐derivation method to convert commercial NFF into a powerful catalyst for electrolytic brine, offering a unique route to the development of efficient electrocatalysts for saline water splitting.    

    

* Ceria‐Optimized Oxygen‐Species Exchange in Hierarchical Bimetallic Hydroxide for Electrocatalytic Water Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399360588
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202406682")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399360588"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399360588"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399360588"))][Get cited by]]

OpenAlex: https://openalex.org/W4399360588 (Open access: False)
    
[[https://openalex.org/A5088510694][Li Guo]], [[https://openalex.org/A5016109147][Zhuang Zhang]], [[https://openalex.org/A5058789488][Zhaori Mu]], [[https://openalex.org/A5026905475][Pengfei Da]], [[https://openalex.org/A5019063196][An Li]], [[https://openalex.org/A5086277480][Wei Shen]], [[https://openalex.org/A5047914748][Yichao Hou]], [[https://openalex.org/A5081074386][Pinxian Xi]], [[https://openalex.org/A5055781053][Chun‐Hua Yan]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202406682 
     
Abstract The utilization of rare earth elements to regulate the interaction between catalysts and oxygen‐containing species holds promising prospects in the field of oxygen electrocatalysis. Through structural engineering and adsorption regulation, it is possible to achieve high‐performance catalytic sites with a broken activity‐stability tradeoff. Herein, we fabricate a hierarchical CeO 2 /NiCo hydroxide for electrocatalytic oxygen evolution reaction (OER). This material exhibits superior overpotentials and enhanced stability. Multiple potential‐dependent experiments reveal that CeO 2 promotes oxygen‐species exchange, especially OH − ions, between catalyst and environment, thereby optimizing the redox transformation of hydroxide and the adsorption of oxygen‐containing intermediates during OER. This is attributed to the reduction in the adsorption energy barrier of Ni to *OH facilitated by CeO 2 , particularly the near‐interfacial Ni sites. The less‐damaging adsorbate evolution mechanism and the CeO 2 hierarchical shell significantly enhance the structural robustness, leading to exceptional stability. Additionally, the observed “self‐healing” phenomenon provides further substantiation for the accelerated oxygen exchange. This work provides a neat strategy for the synthesis of ceria‐based complex hollow electrocatalysts, as well as an in‐depth insight into the co‐catalytic role of CeO 2 in terms of oxygen transfer. This article is protected by copyright. All rights reserved    

    

* Block copolymer-mediated synthesis of TiO2/RuO2 nanocomposite for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399362951
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10853-024-09702-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399362951"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399362951"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399362951"))][Get cited by]]

OpenAlex: https://openalex.org/W4399362951 (Open access: True)
    
[[https://openalex.org/A5099024598][Binod Raj KC]], [[https://openalex.org/A5012014778][Dhananjay Kumar]], [[https://openalex.org/A5075515275][Bishnu Prasad Bastakoti]], Journal of materials science. None(None)] 2024. https://doi.org/10.1007/s10853-024-09702-5  ([[https://link.springer.com/content/pdf/10.1007/s10853-024-09702-5.pdf][pdf]])
     
Abstract An amphiphilic block copolymer, poly (styrene-2-polyvinyl pyridine-ethylene oxide), was used as a structure-directing and stabilizing agent to synthesize TiO 2 /RuO 2 nanocomposite. The strong interaction of polymers with metal precursors led to formation of a porous heterointerface of TiO 2 /RuO 2 . It acted as a bridge for electron transport, which can accelerate the water splitting reaction. Scanning electron microscopy, energy-dispersive X -ray spectroscopy, transmission electron microscopy, and X -ray diffraction analysis of TiO 2 /RuO 2 samples revealed successful fabrication of TiO 2 /RuO 2 nanocomposites. The TiO 2 /RuO 2 nanocomposites were used to measure electrochemical water splitting in three-electrode systems in 0.1-M KOH. Electrochemical activities unveil that TiO 2 /RuO 2 -150 nanocomposites displayed superior oxygen evolution reaction activity, having a low overpotential of 260 mV with a Tafel slope of 80 mVdec −1 . Graphical abstract    

    

* Pt Single Atoms on TiO2 Can Catalyze Water Oxidation in Photoelectrochemical Experiments  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399380646
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c03319")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399380646"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399380646"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399380646"))][Get cited by]]

OpenAlex: https://openalex.org/W4399380646 (Open access: False)
    
[[https://openalex.org/A5086631373][Shi Wu]], [[https://openalex.org/A5030917506][Wu Lu]], [[https://openalex.org/A5042616956][Nikita Denisov]], [[https://openalex.org/A5067344132][Zdeňěk Baďura]], [[https://openalex.org/A5060249822][Giorgio Zoppellaro]], [[https://openalex.org/A5072942701][Xiaoyu Yang]], [[https://openalex.org/A5073750190][Patrik Schmuki]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c03319 
     
Photoelectrochemical water splitting on n-type semiconductors is highly dependent on catalysis of the rate-determining reaction of O2 evolution. Conventionally, in electrochemistry and photoelectrochemistry O2 evolution is catalyzed by metal oxide catalysts like IrO2 and RuO2, whereas noble metals such as Pt are considered unsuitable for this purpose. However, our study finds that Pt, in its single-atom form, exhibits exceptional cocatalytic properties for photoelectrochemical water oxidation on a TiO2 photoanode, in contrast to Pt in a nanoparticle form. The decoration of Pt single atoms onto TiO2 yields a remarkable current density of 5.89 mA cm–2 at 1.23 VRHE, surpassing bare TiO2 (or Pt nanoparticle decorated TiO2) by 2.52 times. Notably, this enhancement remains consistent over a wide pH range. By accompanying theoretical work, we assign this significant enhancement to an improved charge transfer and separation efficiency along with accelerated kinetics in the oxygen evolution reaction facilitated by the presence of Pt single atoms on the TiO2 surface.    

    

* Reconstruction of High Entropy Alloys on a Metal–Organic Framework Approaching Active Oxygen Reduction Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399380880
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-06-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.4c01278")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399380880"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399380880"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399380880"))][Get cited by]]

OpenAlex: https://openalex.org/W4399380880 (Open access: False)
    
[[https://openalex.org/A5075257377][Jing Liang]], [[https://openalex.org/A5028912037][Yanling Ma]], [[https://openalex.org/A5001561384][Yanjie Li]], [[https://openalex.org/A5037451400][Wencong Zhang]], [[https://openalex.org/A5068307504][Hao Hu]], [[https://openalex.org/A5011085395][Jie Su]], [[https://openalex.org/A5014141631][Zhenpeng Yao]], [[https://openalex.org/A5029244026][Wenpei Gao]], [[https://openalex.org/A5047036159][Wen Shang]], [[https://openalex.org/A5005057065][Tao Deng]], [[https://openalex.org/A5065507268][Jianbo Wu]], Nano letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.4c01278 
     
High-entropy alloys (HEAs) have garnered considerable attention as promising nanocatalysts for effectively utilizing Pt in catalysis toward oxygen reduction reactions due to their unique properties. Nonetheless, there is a relative dearth of attention regarding the structural evolution of HEAs in response to electrochemical conditions. In this work, we propose a thermal reduction method to synthesize high entropy nanoparticles by leveraging the confinement effect and abundant nitrogen-anchored sites provided by pyrolyzed metal–organic frameworks (MOFs). Notably, the prepared catalysts exhibit enhanced activity accompanied by structural reconstruction during electrochemical activation, approaching 1 order of magnitude higher mass activity compared to Pt/C in oxygen reduction. Atomic-scale structural characterization reveals that abundant defects and single atoms are formed during the activation process, contributing to a significant boost in the catalytic performance for oxygen reduction reactions. This study provides deep insights into surface reconstruction engineering during electrochemical operations, with practical implications for fuel cell applications.    

    

* Unravelling the operando structural and chemical stability of rare earth metals co-doped CeO2-based electrocatalysts for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399382442
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.06.019")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399382442"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399382442"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399382442"))][Get cited by]]

OpenAlex: https://openalex.org/W4399382442 (Open access: False)
    
[[https://openalex.org/A5056104466][Tauseef Munawar]], [[https://openalex.org/A5015371105][Ambreen Bashir]], [[https://openalex.org/A5062239342][Mehar Un Nisa]], [[https://openalex.org/A5003194921][Razan A. Alshgari]], [[https://openalex.org/A5079586000][Faisal Mukhtar]], [[https://openalex.org/A5062023379][S. Noor Mohammad]], [[https://openalex.org/A5061069978][Muhammad Naeem Ashiq]], [[https://openalex.org/A5057680707][Muhammad Fahad Ehsan]], [[https://openalex.org/A5004262523][Faisal Iqbal]], [[https://openalex.org/A5049328863][Suleyman I. Allakhverdiev]], International journal of hydrogen energy. None(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.06.019 
     
Highly efficient, abundant, and long-lasting electrocatalysts for oxygen evolution will be essential to industrial hydrogen production via water splitting. Hydrogen has emerged as an alternative to conventional fossil fuels, a sustainable and green energy source. Water electrolysis via co-doped metal oxides has been employed to reduce energy loss during electrochemical oxygen evolution reactions (OER), a great alternative to noble-metal-derived electrocatalysts. In the present work, Nd-dopped CeO2 (CeNdO2) nanostructures co-doped with rare earth metals are fabricated via sol-gel technique and analysed via state-of-the-art methods, focusing on structural, morphological, elemental, electrical and electronic capabilities. All fabricated samples were coated on nickel foam (NF) and fluorinated tin oxide (FTO) substrate for electrochemical splitting of water in a 1.0 M KOH. The Pr/Nd co-doped CeO2 grown on NF demonstrates high electrochemical activity with a significantly reduced OER overpotential of around 274 mV, Tafel slope around 84 mV/dec, and increased electrochemical surface area. This co-doped metal oxide nanostructure causes interactions with oxy-radicals (confirmed from XPS and Raman), which are thought to be source of easy charge transport and decrease overpotential. The least charge transfer resistance of Pr-doped CeNdO2/NF presented excellent electroactivity due to reduced polarization resistance between electrolyte and catalyst material. Additionally, for a practical water electrolysis system, the high stability of Pr doped CeNdO2/NF electrode was exposed by continuous cyclic voltammetry sweeps of electrolysis up to 1500 cycles. This work reveals a synergistic effect between metal atoms (Ce, Nd, and Pr) on nickel foam substrate, which is mainly responsible for electron transfer and well-balanced kinetics under beginning conditions.    

    

* Fabrication of N and S co-doped lignin-based porous carbon aerogels loaded with FeCo alloys and their application to oxygen evolution and reduction reactions in Zn-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399382547
:TOPICS: Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijbiomac.2024.132961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399382547"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399382547"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399382547"))][Get cited by]]

OpenAlex: https://openalex.org/W4399382547 (Open access: False)
    
[[https://openalex.org/A5058132261][Ying Han]], [[https://openalex.org/A5040599204][Zihao Ma]], [[https://openalex.org/A5045021562][Xing Wang]], [[https://openalex.org/A5069180245][Guangwei Sun]], International journal of biological macromolecules. None(None)] 2024. https://doi.org/10.1016/j.ijbiomac.2024.132961 
     
Zn-air batteries are a highly promising clean energy sustainable conversion technology, and the design of dual-function electrocatalysts with excellent activity and stability is crucial for their development. In this work, FeCo alloy loaded biomass-based N and S co-doped carbon aerogels (FeCo@NS-LCA) were fabricated from chitosan and lignosulfonate-metal chelates via liquid nitrogen pre-frozen synergistic high-temperature carbonization with application in electrocatalytic reactions. The abundant oxygen-containing functional groups on lignosulfonates have a chelating effect on metal ions, which can avoid the aggregation of metal nanoparticles during carbonation and catalysis, facilitating the construction of a nanoconfinement catalytic system with biomass carbon as the domain-limiting body and FeCo nanoparticles as the active sites. FeCo@NS-LCA exhibited catalytic activity (E1/2 = 0.87 V, JL = 5.7 mA cm−2) comparable to the commercial Pt/C in the oxygen reduction reaction (ORR), excellent resistance to methanol toxicity and stability. Meanwhile, the overpotential of oxygen evolution reaction (OER) was 324 mV, close to that of commercial RuO2 catalysts (351 mV). This study utilizes the coordination action of lignosulfonate to provide a novel and environmentally friendly method for the preparation of confined nano-catalysts and provides a new perspective for the high-value utilization of biomass resources.    

    

* Engineering Internal and External Low-Coordination Atoms in Nickel–Organic Framework Nanoarrays to Promote the Electrochemical Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399393923
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c01086")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399393923"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399393923"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399393923"))][Get cited by]]

OpenAlex: https://openalex.org/W4399393923 (Open access: False)
    
[[https://openalex.org/A5066244840][Shun Wang]], [[https://openalex.org/A5066869555][Chong Lin]], [[https://openalex.org/A5021692087][Xuetong Zhang]], [[https://openalex.org/A5061035893][Yisheng Tan]], [[https://openalex.org/A5072077711][B.L. Xiao]], [[https://openalex.org/A5080610686][Yi Zeng]], [[https://openalex.org/A5031344917][Jingyang Tian]], [[https://openalex.org/A5054363687][Minghui Cao]], [[https://openalex.org/A5024062892][Yuanping Jiang]], [[https://openalex.org/A5050344464][Min Li]], Inorganic chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c01086 
     
Monometallic nickel–organic frameworks based on a carboxylated ligand [2,6-naphthalenedicarboxylic acid (Ni-NDC)] have abundant and uniformly distributed single-atom Ni sites, enabling superior oxygen evolution reaction (OER) activity. In theory, most of the Ni atoms inside Ni-NDC microcrystals are coordinatively saturated except for the surface. Therefore, there are no accessible low-coordination atoms (LCAs) as electrocatalytic sites for the OER. One effective way is to expose more LCAs by preparing self-supporting Ni-NDC nanoarrays (Ni-NDC NAs) with hierarchical secondary structural units. Another effective method is to create more internal LCAs by removing partial ligands or coordination atoms attached to the Ni atoms. Herein, by combining the two strategies, we engineered LCAs in the interior and exterior of Ni-NDC to synergistically accelerate the OER. In brief, ultrathick "brick-like" Ni-NDC NAs were first prepared with dissolution and coordination effects of NDC on self-sacrificial templates of "agaric-like" nickel hydroxide nanoarrays [Ni(OH)2 NAs]. Subsequently, dual-coordinated NDC was partially replaced by monocoordinated 2-naphthoic acid (NA). The Ni-NDC NAs were further tailed into ultrathin "liner leaf-like" nanoneedle arrays (LCAs-Ni-NDC NAs). As a consequence, the LCAs-Ni-NDC NAs have more internal and external LCAs, which can deliver an OER performance that is superior to that of Ni-NDC NAs.    

    

* Tuning the high-entropy perovskite as efficient and reliable electrocatalysts for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399411629
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02680b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399411629"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399411629"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399411629"))][Get cited by]]

OpenAlex: https://openalex.org/W4399411629 (Open access: True)
    
[[https://openalex.org/A5030068214][Ruirui Wei]], [[https://openalex.org/A5064379315][Gaoliang Fu]], [[https://openalex.org/A5016494270][Hui Qi]], [[https://openalex.org/A5027492529][Hewei Liu]], RSC advances. 14(26)] 2024. https://doi.org/10.1039/d4ra02680b 
     
This work reports a high-entropy perovskite La 0.3 Sr 0.7 (CrMnFeCoNi) 0.2 O 3 as a high-performance OER electrocatalyst. Sr doping induces the formation of higher-valence Cr 6+ , Mn 4+ , Fe 4+ , Co 4+ and Ni 3+ responsible for the excellent OER activity.    

    

* 3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399432345
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399432345"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399432345"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399432345"))][Get cited by]]

OpenAlex: https://openalex.org/W4399432345 (Open access: True)
    
[[https://openalex.org/A5048372554][Chao Shuai]], [[https://openalex.org/A5048610528][Chunyang Kong]], [[https://openalex.org/A5006083213][Y.S. Li]], [[https://openalex.org/A5035061957][Liang Zhang]], [[https://openalex.org/A5049238095][Qi Chen]], [[https://openalex.org/A5074381132][Zunli Mo]], RSC advances. 14(26)] 2024. https://doi.org/10.1039/d4ra02280g 
     
3D flower-like bimetallic MOF (F-Ni1Co4-BTC) was successfully designed and synthesized and exhibited excellent OER activity. Moreover, fixed on the surface of a carbon cloth, F-Ni1Co4-BTC realized high OER activity and long-term durability.    

    

* Design of pH‐universal electrocatalysts for hydrogen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399436717
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cey2.555")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399436717"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399436717"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399436717"))][Get cited by]]

OpenAlex: https://openalex.org/W4399436717 (Open access: True)
    
[[https://openalex.org/A5002353800][Jingwen Lin]], [[https://openalex.org/A5062755510][Qianqian Wang]], [[https://openalex.org/A5034640572][Zhenyun Zhao]], [[https://openalex.org/A5028247609][Dongliang Chen]], [[https://openalex.org/A5059889376][Rumin Liu]], [[https://openalex.org/A5012672064][Zhizhen Ye]], [[https://openalex.org/A5053116259][Bin Lü]], [[https://openalex.org/A5055040301][Bin Yang]], [[https://openalex.org/A5009757340][Jianguo Lu]], Carbon energy. None(None)] 2024. https://doi.org/10.1002/cey2.555 
     
Abstract The path to searching for sustainable energy has never stopped since the depletion of fossil fuels can lead to serious environmental pollution and energy shortages. Using water electrolysis to produce hydrogen has been proven to be a prioritized approach for green resource production. It is highly crucial to explore inexpensive and high‐performance electrocatalysts for accelerating hydrogen evolution reaction (HER) and apply them to industrial cases on a large scale. Here, we summarize the different mechanisms of HER in different pH settings and review recent advances in non‐noble‐metal‐based electrocatalysts. Then, based on the previous efforts, we discuss several universal strategies for designing pH‐independent catalysts and show directions for the future design of pH‐universal catalysts.    

    

* Craved Ni3S2–Sm2O3 heterojunction with enhanced electrocatalytic stability and oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399439988
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s43207-024-00411-y")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399439988"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399439988"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399439988"))][Get cited by]]

OpenAlex: https://openalex.org/W4399439988 (Open access: False)
    
[[https://openalex.org/A5003194921][Razan A. Alshgari]], [[https://openalex.org/A5051155813][Jafar Hussain Shah]], [[https://openalex.org/A5062023379][S. Noor Mohammad]], [[https://openalex.org/A5050511139][Ome Parkash Kumar]], [[https://openalex.org/A5052155429][Abdul Ghafoor Abid]], Han-guk seramik hakoeji/Han'gug se'la'mig haghoeji. None(None)] 2024. https://doi.org/10.1007/s43207-024-00411-y 
     
No abstract    

    

* Enhanced Stability of Boron Modified NiFe Hydroxide for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399452068
:TOPICS: Electrocatalysis for Energy Conversion, Desulfurization Technologies for Fuels, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nr01186d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399452068"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399452068"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399452068"))][Get cited by]]

OpenAlex: https://openalex.org/W4399452068 (Open access: False)
    
[[https://openalex.org/A5016683966][Yewon Hong]], [[https://openalex.org/A5041098296][Juhyung Choi]], [[https://openalex.org/A5041098296][Juhyung Choi]], [[https://openalex.org/A5041098296][Juhyung Choi]], Nanoscale. None(None)] 2024. https://doi.org/10.1039/d4nr01186d 
     
The introduction of non-metal elements including boron has been identified as a significant means to enhance oxygen evolution reaction (OER) performance in NiFe-based catalysts. To understand the catalytic activity and...    

    

* Review for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399455932
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399455932"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399455932"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399455932"))][Get cited by]]

OpenAlex: https://openalex.org/W4399455932 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v1/review1 
     
No abstract    

    

* Review for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399455934
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-05-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399455934"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399455934"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399455934"))][Get cited by]]

OpenAlex: https://openalex.org/W4399455934 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v1/review2 
     
No abstract    

    

* Review for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399455937
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-05-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399455937"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399455937"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399455937"))][Get cited by]]

OpenAlex: https://openalex.org/W4399455937 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v2/review1 
     
No abstract    

    

* Decision letter for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399456113
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-05-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399456113"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399456113"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399456113"))][Get cited by]]

OpenAlex: https://openalex.org/W4399456113 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v1/decision1 
     
No abstract    

    

* Decision letter for "3D flower-like bimetallic Ni–Co metal–organic framework as an electrocatalyst for the oxygen evolution reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399456174
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-05-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra02280g/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399456174"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399456174"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399456174"))][Get cited by]]

OpenAlex: https://openalex.org/W4399456174 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ra02280g/v2/decision1 
     
No abstract    

    

* Unraveling the Oxidation Kinetics Through Electronic Structure Regulation of MnCo2O4.5@Ni3S2 p–n Junction for Urea‐Assisted Electrocatalytic Activity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399462204
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202311548")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399462204"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399462204"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399462204"))][Get cited by]]

OpenAlex: https://openalex.org/W4399462204 (Open access: False)
    
[[https://openalex.org/A5017136680][Sangeeta Adhikari]], [[https://openalex.org/A5043194301][Stephan N. Steinmann]], [[https://openalex.org/A5066078135][Maheswari Arunachalam]], [[https://openalex.org/A5074976953][Soon Hyung Kang]], [[https://openalex.org/A5018707438][Do‐Heyoung Kim]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202311548 
     
Abstract A promising strategy to boost electrocatalytic performance is via assembly of hetero‐nanostructured electrocatalysts that delivers the essential specific surface area and also active sites by lowering the reaction barrier. However, the challenges associated with the intricate designs and mechanisms remain underexplored. Therefore, the present study constructs a p–n junction in a free‐standing MnCo 2 O 4.5 @Ni 3 S 2 on Ni‐Foam. The space‐charge region's electrical characteristics is dramatically altered by the formed p–n junction, which enhances the electron transfer process for urea‐assisted electrocatalytic water splitting (UOR). The optimal MnCo 2 O 4.5 @Ni 3 S 2 electrocatalyst results in greater oxygen evolution reactivity (OER) than pure systems, delivering an overpotential of only 240 mV. Remarkably, upon employing as UOR electrode the required potential decreases to 30 mV. The impressive performance of the designed catalyst is attributed to the enhanced electrical conductivity, greater number of electrochemical active sites, and improved redox activity due to the junction interface formed between p‐MnCo 2 O 4.5 and n‐Ni 3 S 2 . There are strong indications that the in situ formed extreme‐surface NiOOH, starting from Ni 3 S 2, boosts the electrocatalytic activity, i.e., the electrochemical surface reconstruction generates the active species. In conclusion, this work presents a high‐performance p–n junction design for broad use, together with a viable and affordable UOR electrocatalyst.    

    

* Oxygen‐tolerant CO2 Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399465290
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-06-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400659")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399465290"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399465290"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399465290"))][Get cited by]]

OpenAlex: https://openalex.org/W4399465290 (Open access: False)
    
[[https://openalex.org/A5036968098][Hongfei Zhu]], [[https://openalex.org/A5084772771][Hui Guo]], [[https://openalex.org/A5027181760][Rong Cao]], [[https://openalex.org/A5047300245][Yuan–Biao Huang]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400659 
     
The electrochemical carbon dioxide reduction reaction (CO2RR) to generate high‐value products is considered to be a promising approach to reduce the atmospheric concentration of CO2. However, the pure CO2 gas is generally required in the most of the reported CO2RR system, which brings tedious capture and separation procedures and high cost. The utilization of realistic CO2 emission directly such as flue gas for the CO2RR is highly desirable. However, the gas impurities in the real CO2 sources such as oxygen could seriously affect the activity and selectivity of the CO2RR. This concept summarizes the recently reported works about CO2RR studies in the presence of O2 and highlights the physical and chemical strategies to boost CO2 electroreduction performance. We further discuss the implications of these strategies for future progress in this emerging field.    

    

* ZIF‐Co3O4@ZIF‐Derived Urchin‐Like Hierarchically Porous Carbon as Efficient Bifunctional Oxygen Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399490831
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/open.202400057")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399490831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399490831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399490831"))][Get cited by]]

OpenAlex: https://openalex.org/W4399490831 (Open access: True)
    
[[https://openalex.org/A5041880317][Lingling Zhang]], [[https://openalex.org/A5074049940][Xiaokang Wang]], [[https://openalex.org/A5046187929][Chong Gong]], [[https://openalex.org/A5001980743][Wanying Sun]], [[https://openalex.org/A5034760240][Zihan Lu]], ChemistryOpen. None(None)] 2024. https://doi.org/10.1002/open.202400057 
     
Abstract Co 3 O 4 nanoparticles were sandwiched into interlayers between ZIF‐8 and ZIF‐67 to form ZIF‐Co 3 O 4 @ZIF precursors. Pyrolysis of ZIF‐Co 3 O 4 @ZIF yielded an urchin‐like hierarchically porous carbon (Co@CNT/NC), the thorns of which were carbon nanotubes embedded Co nanoparticles. With large specific surface area and hierarchically porous structure, as‐prepared Co@CNT/NC exhibited excellent bifunctional oxygen electrocatalytic performances. It has good ORR performance with E 1/2 of 0.85 V, which exceeds the Pt/C half‐wave potential (E 1/2 =0.83 V). In addition, Co@CNT/NC has an OER performance close to that of RuO 2 . To further demonstrate the effect of Co modifying on the properties, the samples were subjected to acid washing treatment. Co‐based nanoparticles were proved to After acid washing, there was obvious loss of Co particles in Co@CNT/NC, resulting in poor oxygen electrocatalysis. So, the pyrolysis products of ZIF‐8‐Co 3 O 4 @ZIF‐67 retained large specific surface area and porous structure can be retained, and on the other hand, the carbon tube structure and original polyhedron framework. Besides, existence of Co nanoparticle@carbon nanotube provided more active sites and improved the ORR and OER performances.    

    

* Lanthanide-regulating Ru-O covalency optimizes acidic oxygen evolution electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399539823
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-49281-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399539823"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399539823"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399539823"))][Get cited by]]

OpenAlex: https://openalex.org/W4399539823 (Open access: True)
    
[[https://openalex.org/A5043019475][Lü Li]], [[https://openalex.org/A5048961496][Gengwei Zhang]], [[https://openalex.org/A5065063220][Chenhui Zhou]], [[https://openalex.org/A5033073898][Fan Liu]], [[https://openalex.org/A5000305461][Yingjun Tan]], [[https://openalex.org/A5090948282][Yong-Nam Han]], [[https://openalex.org/A5086433793][Heng Luo]], [[https://openalex.org/A5003249083][Dawei Wang]], [[https://openalex.org/A5015013360][Youxing Liu]], [[https://openalex.org/A5056885452][Changshuai Shang]], [[https://openalex.org/A5028121137][Lingyou Zeng]], [[https://openalex.org/A5019108433][Qizheng Huang]], [[https://openalex.org/A5061309835][Ruijin Zeng]], [[https://openalex.org/A5034167985][Yinghao Ning]], [[https://openalex.org/A5001987994][Mingchuan Luo]], [[https://openalex.org/A5069379580][Shaojun Guo]], Nature communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-49281-2 
     
Abstract Precisely modulating the Ru-O covalency in RuO x for enhanced stability in proton exchange membrane water electrolysis is highly desired. However, transition metals with d -valence electrons, which were doped into or alloyed with RuO x , are inherently susceptible to the influence of coordination environment, making it challenging to modulate the Ru-O covalency in a precise and continuous manner. Here, we first deduce that the introduction of lanthanide with gradually changing electronic configurations can continuously modulate the Ru-O covalency owing to the shielding effect of 5 s /5 p orbitals. Theoretical calculations confirm that the durability of Ln-RuO x following a volcanic trend as a function of Ru-O covalency. Among various Ln-RuO x , Er-RuO x is identified as the optimal catalyst and possesses a stability 35.5 times higher than that of RuO 2 . Particularly, the Er-RuO x -based device requires only 1.837 V to reach 3 A cm −2 and shows a long-term stability at 500 mA cm −2 for 100 h with a degradation rate of mere 37 μV h −1 .    

    

* Theoretical Prediction and Experimental Verification of IrOx Supported on Titanium Nitride for Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399546622
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c02936")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399546622"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399546622"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399546622"))][Get cited by]]

OpenAlex: https://openalex.org/W4399546622 (Open access: False)
    
[[https://openalex.org/A5087214567][Xue Han]], [[https://openalex.org/A5062136198][Tianyou Mou]], [[https://openalex.org/A5079637441][A. T. M. N. Islam]], [[https://openalex.org/A5073903036][Sinwoo Kang]], [[https://openalex.org/A5055079978][Qiaowan Chang]], [[https://openalex.org/A5013590799][Zhenghui Xie]], [[https://openalex.org/A5009916557][Xinbing Zhao]], [[https://openalex.org/A5024644817][Kotaro Sasaki]], [[https://openalex.org/A5038550012][José A. Rodríguez]], [[https://openalex.org/A5064944001][Ping Liu]], [[https://openalex.org/A5034358731][Jingguang G. Chen]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c02936 
     
Reducing iridium (Ir) catalyst loading for acidic oxygen evolution reaction (OER) is a critical strategy for large-scale hydrogen production via proton exchange membrane (PEM) water electrolysis. However, simultaneously achieving high activity, long-term stability, and reduced material cost remains challenging. To address this challenge, we develop a framework by combining density functional theory (DFT) prediction using model surfaces and proof-of-concept experimental verification using thin films and nanoparticles. DFT results predict that oxidized Ir monolayers over titanium nitride (IrO    

    

* Invoking Interfacial Engineering Boosts Structural Stability Empowering Exceptional Cyclability of Ni‐Rich Cathode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399552458
:TOPICS: Lithium-ion Battery Technology, Lithium Battery Technologies, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202405628")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399552458"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399552458"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399552458"))][Get cited by]]

OpenAlex: https://openalex.org/W4399552458 (Open access: False)
    
[[https://openalex.org/A5005433596][Youqi Chu]], [[https://openalex.org/A5008002256][Yongbiao Mu]], [[https://openalex.org/A5076340546][Huan Gu]], [[https://openalex.org/A5024300764][Yan Hu]], [[https://openalex.org/A5081672117][Xianbin Wei]], [[https://openalex.org/A5068132441][Lingfeng Zou]], [[https://openalex.org/A5033892514][Can Yu]], [[https://openalex.org/A5049204344][Xianglong Xu]], [[https://openalex.org/A5086662388][Shaowei Kang]], [[https://openalex.org/A5040258136][Kang Li]], [[https://openalex.org/A5075745850][Meisheng Han]], [[https://openalex.org/A5025851882][Qing Zhang]], [[https://openalex.org/A5022926692][Lin Zeng]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202405628 
     
Abstract The cycling stability of LiNi 0.8 Co 0.1 Mn 0.1 O 2 under high voltages is hindered by the occurrence of hybrid anion‐ and cation‐redox processes, leading to oxygen escape and uncontrolled phase collapse. In this study, we propose an interfacial engineering strategy involving a straightforward mechanical ball milling and low‐temperature calcination, employing a Se‐doped and FeSe 2 &Fe 2 O 3 ‐modified approach to design a stable Ni‐rich cathode. Se 2− are selectively adsorbed within oxygen vacancies to form O‐TM‐Se bond, effectively stabilizing lattice oxygen, and preventing structural distortion. Simultaneously, the Se‐NCM811//FeSe 2 //Fe 2 O 3 self‐assembled electric field is activated, improving interfacial charge transfer and coupling. Furthermore, FeSe 2 accelerates Li + diffusion and reacts with oxygen to form Fe 2 O 3 and SeO 2 . The Fe 2 O 3 coating mitigates HF erosion and acts as an electrostatic shield layer, limiting the outward migration of oxygen anions. Impressively, the modified materials exhibit significantly improved electrochemical performance, with a capacity retention of 79.7% after 500 cycles at 1C under 4.5 V. Furthermore, it provides an extraordinary capacity retention of 94.6% in 3 – 4.25 V after 550 cycles in pouch‐type full battery. This dual‐modification approach demonstrates its feasibility and opens new perspectives for the development of stable lithium‐ion batteries operating at high voltages. This article is protected by copyright. All rights reserved    

    

* High Entropy Materials for Oxygen Evolution Reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399537582
:TOPICS: Stochastic Thermodynamics and Fluctuation Theorems
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1201/9781003391388-11")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399537582"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399537582"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399537582"))][Get cited by]]

OpenAlex: https://openalex.org/W4399537582 (Open access: False)
    
[[https://openalex.org/A5067170578][Bhagyashri B. Kamble]], [[https://openalex.org/A5001956023][Arun Karmakar]], [[https://openalex.org/A5089559041][Subrata Kundu]], CRC Press eBooks. None(None)] 2024. https://doi.org/10.1201/9781003391388-11 
     
No abstract    

    

* A review of Advancements in Theoretical Simulation of Oxygen Reduction Reaction and Oxygen Evolution Reaction Single-Atom Catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399458462
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mtsust.2024.100876")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399458462"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399458462"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399458462"))][Get cited by]]

OpenAlex: https://openalex.org/W4399458462 (Open access: False)
    
[[https://openalex.org/A5062375032][Ninggui Ma]], [[https://openalex.org/A5062264843][Yu Xiong]], [[https://openalex.org/A5082322039][Yuhang Wang]], [[https://openalex.org/A5031438011][Yaqin Zhang]], [[https://openalex.org/A5062755510][Qianqian Wang]], [[https://openalex.org/A5069290077][Shuang Luo]], [[https://openalex.org/A5046732879][Jingbo Zhao]], [[https://openalex.org/A5070409736][Changxiong Huang]], [[https://openalex.org/A5081922643][Fan Jiang]], Materials today sustainability. None(None)] 2024. https://doi.org/10.1016/j.mtsust.2024.100876 
     
No abstract    

    

* Nano-etching of carbon nanofiber surface and subsequent Fe–N–C thin film coating for enhancement of oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399552391
:TOPICS: Electrocatalysis for Energy Conversion, Diamond Nanotechnology and Applications, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.tsf.2024.140412")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399552391"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399552391"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399552391"))][Get cited by]]

OpenAlex: https://openalex.org/W4399552391 (Open access: False)
    
[[https://openalex.org/A5041171288][Jun Maruyama]], [[https://openalex.org/A5028782865][Shohei Maruyama]], [[https://openalex.org/A5038047940][Setsuko Shibuya]], [[https://openalex.org/A5010359555][Yoshiyuki Nonoguchi]], [[https://openalex.org/A5086224758][Zyun Siroma]], Thin solid films. None(None)] 2024. https://doi.org/10.1016/j.tsf.2024.140412 
     
No abstract    

    

* Structural Evolution and Electronic Properties of Anionic Plutonium-Doped Oxygen Clusters  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399520536
:TOPICS: Chemistry of Actinide and Lanthanide Elements, Catalytic Nanomaterials, Nuclear Fuel Development
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4855417")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399520536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399520536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399520536"))][Get cited by]]

OpenAlex: https://openalex.org/W4399520536 (Open access: False)
    
[[https://openalex.org/A5079714560][Zaifu Jiang]], [[https://openalex.org/A5086600480][Pingping Fu]], [[https://openalex.org/A5059826081][Shuguang Jin]], [[https://openalex.org/A5049028135][Panlong Kong]], [[https://openalex.org/A5073501391][Jie Zhang]], [[https://openalex.org/A5009348332][Hanqing Lu]], [[https://openalex.org/A5007660467][Cheng Lu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4855417 
     
No abstract    

    

* Lattice oxygen evolution in rutile Ru1−xNixO<mml:math xmlns:mml="http://www.w3.org/1998/Math/…  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399544974
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144567")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399544974"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399544974"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399544974"))][Get cited by]]

OpenAlex: https://openalex.org/W4399544974 (Open access: False)
    
[[https://openalex.org/A5006002507][Adrian Frandsen]], [[https://openalex.org/A5034826864][Kateřina Macounová]], [[https://openalex.org/A5083668074][Jan Rossmeisl]], [[https://openalex.org/A5020354378][Petr Krtil]], Electrochimica acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144567 
     
No abstract    

    

* Coordination of Ti3+ and Ni3+ to promote the electrocatalytic OER properties of SrTiO3@TiO2 heterojunctions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399516839
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4se00258j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399516839"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399516839"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399516839"))][Get cited by]]

OpenAlex: https://openalex.org/W4399516839 (Open access: False)
    
[[https://openalex.org/A5063838727][Yongqiang Bi]], [[https://openalex.org/A5071317715][Zifeng Zhao]], [[https://openalex.org/A5054158369][Jianhua Qian]], [[https://openalex.org/A5047526983][Liang Chen]], [[https://openalex.org/A5041811908][Chengjiao Duan]], Sustainable energy & fuels. None(None)] 2024. https://doi.org/10.1039/d4se00258j 
     
Limited current and overpotential are critical factors for efficient hydrogen production through photoelectrochemical water oxidation. To enhance the oxygen evolution reaction (OER), transition metals (Ni, Co, Cu) are doped into...    

    

* The Mechanism of Enhanced Electrocatalytic Water Splitting on S-Doped NiFe2O4/Ni-Fe Alloy@Copper Foams  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399518641
:TOPICS: Catalytic Reduction of Nitro Compounds, Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6528/ad5683")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399518641"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399518641"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399518641"))][Get cited by]]

OpenAlex: https://openalex.org/W4399518641 (Open access: False)
    
[[https://openalex.org/A5008091677][Wenbin Wang]], [[https://openalex.org/A5092134429][Wei Yang]], [[https://openalex.org/A5033909694][Ruidong Xu]], [[https://openalex.org/A5064832458][Suyang Feng]], [[https://openalex.org/A5065415603][Xiaozhe Wang]], Nanotechnology. None(None)] 2024. https://doi.org/10.1088/1361-6528/ad5683 
     
Abstract The development of bifunctional catalysts with subtle structures, high efficiencies and good durabilities for the oxygen evolution reaction (OER) and hydrogen evolution reaction (HER) is crucial for overall water splitting. In this work, a multicomponent S-doped NiFe2O4/Ni-Fe micronano flower electrocatalyst was synthesized rapidly on foam copper using a simple one-step constant current electrodeposition method. The introduction of S leads to the transformation of the microsphere structure of the Ni-Fe alloy into a cauliflower-like morphology and induces changes in the surface electronic structure, significantly enhancing the catalytic performance for the HER and OER. The S-NiFe2O4/Ni-Fe alloy/CF showed low overpotentials of 220 mV and 66 mV at 10 mA cm-2 in 1.0 M KOH for the OER and HER, respectively. High durability OER and HER performances were demonstrated through 60 h of chronopotentiometry and 6000 CV cycles test. Excellent overall water splitting electrocatalytic activity was observed in the S-NiFe2O4/Ni-Fe alloy/CF‖S-NiFe2O4/Ni-Fe alloy/CF two-electrode system. In particular, active-phase NiOOH, a highly active substance for OER, can be controllably formed in the reaction process owing to the nanoflower structure of multi-layer sulfur which slows down the dissolution of NiFe2O4/Ni-Fe alloy. These results suggest that this composite structure is a promising bifunctional electrocatalyst.&#xD;    

    

* Unlocking Efficient Hydrogen Production: Nucleophilic Oxidation Reactions Coupled with Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399480524
:TOPICS: Homogeneous Catalysis with Transition Metals, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202404806")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399480524"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399480524"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399480524"))][Get cited by]]

OpenAlex: https://openalex.org/W4399480524 (Open access: True)
    
[[https://openalex.org/A5049078993][Peng Wang]], [[https://openalex.org/A5021634017][Jie Zheng]], [[https://openalex.org/A5028315721][Xin Xue]], [[https://openalex.org/A5085370636][Yuqing Zhang]], [[https://openalex.org/A5008838534][Qingshan Shi]], [[https://openalex.org/A5006575032][Yong Wan]], [[https://openalex.org/A5071200114][Seeram Ramakrishna]], [[https://openalex.org/A5071672663][Jun Zhang]], [[https://openalex.org/A5070475445][Liyang Zhu]], [[https://openalex.org/A5026905211][Tokihiko Yokoshima]], [[https://openalex.org/A5037509120][Yusuke Yamauchi]], [[https://openalex.org/A5049174582][Yun‐Ze Long]], Advanced materials. None(None)] 2024. https://doi.org/10.1002/adma.202404806 
     
Electrocatalytic water splitting driven by sustainable energy is a clean and promising water-chemical fuel conversion technology for the production of high purity green hydrogen. However, the sluggish kinetics of anodic oxygen evolution reaction (OER) pose challenges for large-scale hydrogen production, limiting its efficiency and safety. Recently, the anodic OER has been replaced by a nucleophilic oxidation reaction (NOR) with biomass as the substrate and coupled with hydrogen evolution reaction (HER), which has attracted great interest. Anode NOR offers faster kinetics, generates high-value products, and reduces energy consumption. By coupling NOR with hydrogen evolution reaction, hydrogen production efficiency can be enhanced while yielding high-value oxidation products or degrading pollutants. Therefore, NOR-coupled HER hydrogen production is another new green electrolytic hydrogen production strategy after electrolytic water hydrogen production, which is of great significance for realizing sustainable energy development and global decarbonization. This review explores the potential of nucleophilic oxidation reactions as an alternative to OER and delves into NOR mechanisms, guiding future research in NOR-coupled hydrogen production. It assesses different NOR-coupled production methods, analyzing reaction pathways and catalyst effects. Furthermore, it evaluates the role of electrolyzers in industrialized NOR-coupled hydrogen production and discusses future prospects and challenges. This comprehensive review aims to advance efficient and economical large-scale hydrogen production. This article is protected by copyright. All rights reserved.    

    

* From computational screening to the synthesis of a promising OER catalyst  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399391244
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-06-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2023-j98r4-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399391244"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399391244"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399391244"))][Get cited by]]

OpenAlex: https://openalex.org/W4399391244 (Open access: True)
    
[[https://openalex.org/A5013443338][Sai Govind Hari Kumar]], [[https://openalex.org/A5085504653][Carlota Bozal‐Ginesta]], [[https://openalex.org/A5043839950][Ning Wang]], [[https://openalex.org/A5049493917][Jehad Abed]], [[https://openalex.org/A5032610126][Chunhui Shan]], [[https://openalex.org/A5014141631][Zhenpeng Yao]], [[https://openalex.org/A5086779313][Alán Aspuru‐Guzik]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2023-j98r4-v2  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/6660b23b21291e5d1d25dccb/original/from-computational-screening-to-the-synthesis-of-a-promising-oer-catalyst.pdf][pdf]])
     
The search for new materials can be laborious and expensive. Given the challenges that mankind faces today concerning the climate change crisis, the need to accelerate materials discovery for applications like water-splitting could be very relevant for a renewable economy. In this work, we introduce a computational framework to predict the activity of oxygen evolution reaction (OER) catalysts, in order to accelerate the discovery of materials that can facilitate water splitting. We use this framework to screen 6155 ternary-phase spinel oxides and have isolated 33 candidates which are predicted to have potentially high OER activity. We have also trained a machine learning model to predict the binding energies of the *O, *OH and *OOH intermediates calculated within this workflow to gain a deeper understanding of the relationship between electronic structure descriptors and OER activity. Out of the 33 candidates predicted to have high OER activity, we have synthesized three compounds and characterized them using linear sweep voltammetry to gauge their performance in OER. From these three catalyst materials, we have identified a new material, Co2.5Ga0.5O4, that is competitive with benchmark OER catalysts in the literature with a low overpotential of 220mV at 10mAcm-2 and a Tafel slope at 56.0 mV dec-1. Given the vast size of chemical space as well as the success of this technique to date, we believe that further application of this computational framework based on the high-throughput virtual screening of materials can lead to the discovery of additional novel, high-performing OER catalysts.    

    

* Oxygen Vacancy‐Controlled CuOx/N,Se Co‐Doped Porous Carbon via Plasma‐Treatment for Enhanced Electro‐Reduction of Nitrate to Green Ammonia  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399540364
:TOPICS: Ammonia Synthesis and Electrocatalysis, Content-Centric Networking for Information Delivery, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202403253")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399540364"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399540364"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399540364"))][Get cited by]]

OpenAlex: https://openalex.org/W4399540364 (Open access: False)
    
[[https://openalex.org/A5017811970][Junbeom Maeng]], [[https://openalex.org/A5091606131][Daehee Jang]], [[https://openalex.org/A5076482592][Jungseub Ha]], [[https://openalex.org/A5002032870][Junhyuk Ji]], [[https://openalex.org/A5023916165][Jong Heo]], [[https://openalex.org/A5052432429][Yeji Park]], [[https://openalex.org/A5015735286][Subin Kim]], [[https://openalex.org/A5019669804][Won Kim]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202403253 
     
Abstract The electrochemical nitrate reduction reaction (NO 3 RR) is of significance in regards of environmentally friendly issues and green ammonia production. However, relatively low performance with a competitive hydrogen evolution reaction (HER) is a challenge to overcome for the NO 3 RR. In this study, oxygen vacancy‐controlled copper oxide (CuO x ) catalysts through a plasma treatment are successfully prepared and supported on high surface area porous carbon that are co‐doped with N, Se species for its enhanced electrochemical properties. The oxygen vacancy‐increased CuO x catalyst supported on the N,Se co‐doped porous carbon (CuO x ‐H/NSePC) exhibited the highest NO 3 RR performance with faradaic efficiency (FE) of 87.2% and yield of 7.9 mg cm −2 h −1 for the ammonia production, representing significant enhancements of FE and ammonia yield as compared to the un‐doped or the oxygen vacancy‐decreased catalysts. This high performance should be attributed to a significant increase in the catalytic active sites with facilitated energetics from strategies of doping the catalytic materials and weakening the N─O bonding strength for the adsorption of NO 3 − ions on the modulated oxygen vacancies. This results show a promise that co‐doping of heteroatoms and regulating of oxygen vacancies can be key factors for performance enhancement, suggesting new guidelines for effective catalyst design of NO 3 RR.    

    

* The Implications of Thermal Hydrodynamic Atmospheric Escape on the TRAPPIST-1 Planets  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399540498
:TOPICS: Formation and Evolution of the Solar System, Stellar Astrophysics and Exoplanet Studies, Exploration and Study of Mars
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3847/psj/ad4454")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399540498"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399540498"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399540498"))][Get cited by]]

OpenAlex: https://openalex.org/W4399540498 (Open access: True)
    
[[https://openalex.org/A5066415755][Megan T. Gialluca]], [[https://openalex.org/A5056051251][Rory Barnes]], [[https://openalex.org/A5051034436][Victoria Meadows]], [[https://openalex.org/A5020655518][Rodolfo García]], [[https://openalex.org/A5027612303][Jessica Birky]], [[https://openalex.org/A5083799931][Eric Agol]], The planetary science journal. 5(6)] 2024. https://doi.org/10.3847/psj/ad4454 
     
Abstract JWST observations of the seven-planet TRAPPIST-1 system will provide an excellent opportunity to test outcomes of stellar-driven evolution of terrestrial planetary atmospheres, including atmospheric escape, ocean loss, and abiotic oxygen production. While most previous studies use a single luminosity evolution for the host star, we incorporate observational uncertainties in stellar mass, luminosity evolution, system age, and planetary parameters to statistically explore the plausible range of planetary atmospheric escape outcomes. We present probabilistic distributions of total water loss and oxygen production as a function of initial water content, for planets with initially pure water atmospheres and no interior–atmosphere exchange. We find that the interior planets are desiccated for initial water contents below 50 Earth oceans. For TRAPPIST-1e, f, g, and h, we report maximum water-loss ranges of    8.0   − 0.9   + 1.3    ,    4.8   − 0.4   + 0.6    ,    3.4   − 0.3   + 0.3    , and    0.8   − 0.1   + 0.2    Earth oceans, respectively, with corresponding maximum oxygen retention of    1290   − 75   + 75    ,    800   − 40   + 40    ,    560   − 25   + 30    , and    90   − 10   + 10    bars. We explore statistical constraints on initial water content imposed by current water content, which could inform evolutionary history and planet formation. If TRAPPIST-1b is airless while TRAPPIST-1c possesses a tenuous oxygen atmosphere, as initial JWST observations suggest, then our models predict an initial surface water content of 8.2     − 1.0   + 1.5    Earth oceans for these worlds, leading to the outer planets retaining >1.5 Earth oceans after entering the habitable zone. Even if TRAPPIST-1c is airless, surface water on the outer planets would not be precluded.    

    

* Magnetic field evolution for crystallization-driven dynamos in C/O white
  dwarfs  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399405338
:TOPICS: Magnetosome Formation in Prokaryotes, Formation and Evolution of the Solar System, Solar Physics and Space Weather
:PUBLICATION_DATE: 2024-06-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2406.01807")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399405338"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399405338"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399405338"))][Get cited by]]

OpenAlex: https://openalex.org/W4399405338 (Open access: True)
    
[[https://openalex.org/A5045952653][Matias Castro-Tapia]], [[https://openalex.org/A5024665846][Shuang‐Nan Zhang]], [[https://openalex.org/A5040229398][Andrew Cumming]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2406.01807  ([[https://arxiv.org/pdf/2406.01807][pdf]])
     
We investigate the evolution of magnetic fields generated by the crystallization-driven dynamo in carbon-oxygen white dwarfs (WDs) with masses $\lesssim1.05\ M_{\odot}$. We use scalings for the dynamo to demonstrate that the initial magnetic field strength ($B_{0}$) has an upper limit that depends on the initial convection zone size ($R_{\mathrm{out},0}$) and the WD mass. We solve the induction equation to follow the magnetic field evolution after the dynamo phase ends. We show that the predicted surface magnetic field strength ($B_{\mathrm{surf}}$) differs from $B_{0}$ by at least a factor of $\sim$0.3. This reduction depends on $R_{\mathrm{out},0}$, where values smaller than half of the star radius give $B_{\mathrm{surf}}\lesssim0.01\ B_{0}$. We implement electrical conductivities that account for the solid phase effect on the Ohmic diffusion. We observe that the conductivity increases as the solid core grows, freezing in the magnetic field at a certain point of the evolution and slowing its outwards transport. We study the effect of turbulent magnetic diffusivity induced by the convection and find that for a small $R_{\mathrm{out},0}$, $B_{\mathrm{surf}}$ is stronger than the non-turbulent diffusion cases because of the more rapid transport, but still orders of magnitude smaller than $B_{0}$. Given these limitations, the crystallization-driven dynamo theory could explain only magnetic C/O WDs with field strengths less than a few MG for the mass range 0.45-1.05 $M_{\odot}$. Our results also suggest that a buried fossil field must be at least 100 times stronger than observed surface fields if crystallization-driven convection is responsible for its transport to the surface.    

    

* Geochemistry of forty‐one eclogitic and pyroxenitic mantle xenoliths from the Central Slave Craton, Canada (Ekati Diamond Mine)  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399532353
:TOPICS: Tectonic and Geochronological Evolution of Orogens, Mantle Dynamics and Earth's Structure, Seismicity and Tectonic Plate Interactions
:PUBLICATION_DATE: 2024-06-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/gdj3.258")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399532353"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399532353"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399532353"))][Get cited by]]

OpenAlex: https://openalex.org/W4399532353 (Open access: True)
    
[[https://openalex.org/A5031751266][Dorrit E. Jacob]], [[https://openalex.org/A5052215051][Agnes Fung]], Geoscience data journal. None(None)] 2024. https://doi.org/10.1002/gdj3.258 
     
Abstract This article describes a novel dataset on non‐diamondiferous eclogite and garnet pyroxenite xenoliths from four kimberlite pipes of the Ekati Diamond Mine (Central Slave Craton, Canada). Xenoliths brought to the surface by kimberlite eruptions are direct sources of information on the composition and evolution of the Earth's mantle. Eclogite and garnet pyroxenite xenoliths, specifically, are testimony of subduction into, and metasomatism of, the mantle beneath cratons. Furthermore, these rocks are major hosts for diamond and thus an important part of the deep carbon cycle. The sample suite consists of 41 small xenoliths (2–5 cm) recovered from drill cores. The dataset includes major and trace element concentrations for garnet, clinopyroxene and ilmenite, as well as stable oxygen isotope compositions of garnets. Strontium and neodymium isotopic compositions are reported for garnet and clinopyroxene for four samples which were large enough to allow for analysis. Overall, this dataset significantly expands and complements existing datasets on diamondiferous and non‐diamondiferous xenoliths from the Slave Craton in Canada, furthering our understanding of the composition of the Slave subcratonic lithosphere. The dataset includes several samples with rare mineral assemblages, including an olivine‐bearing eclogite as well as ilmenite and apatite‐bearing garnet‐pyroxenites, and thus provides data shedding light on rarely reported compositional nuances in xenolith suites found in kimberlites.    

    

* Diagenetic evolution of Upper Cretaceous carbonate sequences (Sarvak Formation) in the Abadan Plain, Iran: evidence from petrographic, elemental, stable, and strontium isotopic data  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399362563
:TOPICS: Paleoredox and Paleoproductivity Proxies, Characterization of Shale Gas Pore Structure, Geological Evolution of South China Sea
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1080/00206814.2024.2361276")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399362563"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399362563"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399362563"))][Get cited by]]

OpenAlex: https://openalex.org/W4399362563 (Open access: False)
    
[[https://openalex.org/A5051350061][R. Abbasi]], [[https://openalex.org/A5086988024][Hamzeh Mehrabi]], [[https://openalex.org/A5092253092][Emad Yahyaei]], [[https://openalex.org/A5053742946][Hossain Rahimpour–Bonab]], International geology review. None(None)] 2024. https://doi.org/10.1080/00206814.2024.2361276 
     
This study investigates the diagenetic evolution and geochemical variations within the Sarvak Formation by integrating the core, thin-section, scanning electron microscopy, X-ray diffraction, trace elements, carbon-oxygen, and strontium isotopic data from three wells in the Abadan Plain. The formation displays diverse diagenetic processes, influenced by multiple exposure surface condition including the Cenomanian-Turonian boundary (CT-ES) and middle Turonian (mT-ES). Meteoric diagenesis, shaped by tectonic activities and eustatic sea level changes, played a pivotal role, leading to dissolution (karstification), brecciation, cementation, and palaeosol formation. Geochemical analysis revealed significant elemental variations across the studied wells. Magnesium (Mg) exhibited peaks at sequence boundaries, responding to facies changes, while iron (Fe) and manganese (Mn) concentrations increased below disconformities, reflecting changes in redox conditions and karstification. Sodium (Na) concentrations varied with facies changes, showing peaks at sequence boundaries, indicative of palaeoexposure events. Strontium (Sr) isotopes aided in delineating stratigraphic positions of palaeoexposure surfaces and absolute dating of sequences. Increases in87Sr/86Sr ratios below disconformities suggested subaerial exposure events, with shorter durations at CT-ES and longer durations at mT-ES, contributing to dissolution features development. The δ13Ccarb and δ18Ocarb values indicated severe meteoric diagenesis below sequence boundaries, characterized by dissolution and reprecipitation of calcium carbonate as low-magnesium calcite (LMC) cements. Cross plots of δ13Ccarb vs. δ18Ocarb displayed inverted-J patterns, indicative of meteoric diagenesis effects. Comparison with previous studies highlighted similar trends in geochemical variations, with notable differences in element concentrations between wells. This study enhances our understanding of diagenetic history of the Sarvak Formation in the Abadan Plain and, in a larger scale, provides insights into diagenetic evolution of palaeoexposure-related carbonate sequences.    

    

* Environment-Driven Variability in Absolute Band Edge Positions and Work Functions of Reduced Ceria  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399367657
:TOPICS: Catalytic Nanomaterials, Emergent Phenomena at Oxide Interfaces, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-06-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c05053")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399367657"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399367657"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399367657"))][Get cited by]]

OpenAlex: https://openalex.org/W4399367657 (Open access: True)
    
[[https://openalex.org/A5043608187][Xingfan Zhang]], [[https://openalex.org/A5082037593][Christopher S. Blackman]], [[https://openalex.org/A5056443409][Robert G. Palgrave]], [[https://openalex.org/A5085247610][Sobia Ashraf]], [[https://openalex.org/A5074215000][Avishek Dey]], [[https://openalex.org/A5007924175][Matthew O. Blunt]], [[https://openalex.org/A5073568638][Xu Zhang]], [[https://openalex.org/A5027996639][Taifeng Liu]], [[https://openalex.org/A5050790072][Shijia Sun]], [[https://openalex.org/A5025820671][Lei Zhu]], [[https://openalex.org/A5034641351][Jingcheng Guan]], [[https://openalex.org/A5075439339][You Lü]], [[https://openalex.org/A5033050680][Thomas W. Keal]], [[https://openalex.org/A5060187040][John Buckeridge]], [[https://openalex.org/A5042572313][C. Richard A. Catlow]], [[https://openalex.org/A5017393061][Alexey A. Sokol]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c05053  ([[https://pubs.acs.org/doi/pdf/10.1021/jacs.4c05053][pdf]])
     
The absolute band edge positions and work function (Φ) are the key electronic properties of metal oxides that determine their performance in electronic devices and photocatalysis. However, experimental measurements of these properties often show notable variations, and the mechanisms underlying these discrepancies remain inadequately understood. In this work, we focus on ceria (CeO2), a material renowned for its outstanding oxygen storage capacity, and combine theoretical and experimental techniques to demonstrate environmental modifications of its ionization potential (IP) and Φ. Under O-deficient conditions, reduced ceria exhibits a decreased IP and Φ with significant sensitivity to defect distributions. In contrast, the IP and Φ are elevated in O-rich conditions due to the formation of surface peroxide species. Surface adsorbates and impurities can further augment these variabilities under realistic conditions. We rationalize the shifts in energy levels by separating the individual contributions from bulk and surface factors, using hybrid quantum mechanical/molecular mechanical (QM/MM) embedded-cluster and periodic density functional theory (DFT) calculations supported by interatomic-potential-based electrostatic analyses. Our results highlight the critical role of on-site electrostatic potentials in determining the absolute energy levels in metal oxides, implying a dynamic evolution of band edges under catalytic conditions.    

    

* Advanced electrocatalysts for fuel cells: Evolution of active sites and synergistic properties of catalysts and carrier materials  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399516623
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-06-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/exp.20230052")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399516623"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399516623"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399516623"))][Get cited by]]

OpenAlex: https://openalex.org/W4399516623 (Open access: True)
    
[[https://openalex.org/A5040312379][Zhijie Kong]], [[https://openalex.org/A5001044012][Jianghua Wu]], [[https://openalex.org/A5034970777][Zhijuan Liu]], [[https://openalex.org/A5026864143][Dafeng Yan]], [[https://openalex.org/A5037531970][Zhi Peng Wu]], [[https://openalex.org/A5026877218][Chuan‐Jian Zhong]], Exploration. None(None)] 2024. https://doi.org/10.1002/exp.20230052 
     
Abstract Proton exchange‐membrane fuel cell (PEMFC) is a clean and efficient type of energy storage device. However, the sluggish reaction rate of the cathode oxygen reduction reaction (ORR) has been a significant problem in its development. This review reports the recent progress of advanced electrocatalysts focusing on the interface/surface electronic structure and exploring the synergistic relationship of precious‐based and non‐precious metal‐based catalysts and support materials. The support materials contain non‐metal (C/N/Si, etc.) and metal‐based structures, which have demonstrated a crucial role in the synergistic enhancement of electrocatalytic properties, especially for high‐temperature fuel cell systems. To improve the strong interaction, some exciting synergistic strategies by doping and coating heterogeneous elements or connecting polymeric ligands containing carbon and nitrogen were also shown herein. Besides the typical role of the crystal surface, phase structure, lattice strain, etc., the evolution of structure‐performance relations was also highlighted in real‐time tests. The advanced in situ characterization techniques were also reviewed to emphasize the accurate structure‐performance relations. Finally, the challenge and prospect for developing the ORR electrocatalysts were concluded for commercial applications in low‐ and high‐temperature fuel cell systems.    

    

* Redistribution and activation of inert N-configuration in metallic electron donor towards boosted oxygen reaction kinetics for zinc-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4399365720
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.152863")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4399365720"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4399365720"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4399365720"))][Get cited by]]

OpenAlex: https://openalex.org/W4399365720 (Open access: False)
    
[[https://openalex.org/A5053477678][Yong Cao]], [[https://openalex.org/A5066838000][Y. H. Chen]], [[https://openalex.org/A5084188467][Ke Chen]], [[https://openalex.org/A5045556967][Lili Sun]], [[https://openalex.org/A5079321464][Shi Wu Wen]], [[https://openalex.org/A5048411184][Yan Yan]], [[https://openalex.org/A5019773832][Huijuan Lin]], [[https://openalex.org/A5034405729][Jixin Zhu]], [[https://openalex.org/A5026599083][Peilei He]], [[https://openalex.org/A5045545412][Na Liu‎]], [[https://openalex.org/A5085237771][Haijiao Xie]], [[https://openalex.org/A5028083442][Kun Rui]], Chemical engineering journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.152863 
     
The utilization of metallic nitrides as air–cathode electrocatalysts is promising for sparking fresh vitality to rechargeable zinc-air batteries, but successful case is rare due to their limitation to catalyze one specific reaction. Here, mild topochemical evolution coupled with assembly self-templating is presented to achieve electrocatalytic furnishing on the 2D metallic VN nanosheet. Density functional theory (DFT) calculations predict that lowered energy barriers for potential limiting steps can be achieved by hybridization VN with cost-effective active species. Metallic VN hybrid architecture buffered with flocculent carbon matrix is constructed, featuring decoration of active FeNi alloy nanoparticles (VN-FeNiA@FC). Particularly, prominent interfacial electron delocalization owing to the electron donating from VN boosts the oxygen reaction kinetics. As a stride forward, the redistribution and activation of inert N-configuration from host VN to the formation of Fe/Ni–Nx are revealed, contributing to promoted exposure of active sites. As a proof of concept, a rechargeable zinc-air battery based on bifunctional VN-FeNiA@FC catalyst exhibits desired galvanostatic charge/discharge stability for over 200 h, surpassing the noble metal-based benchmarks (Pt/C + Ir/C). This study is expected to open new avenues for designing hybrid materials with modulated electronic environment and interface chemistry for electrocatalytic applications and beyond.    

    
