#+TITLE: water splitting
Description: water splitting papers
Created on Sat Oct 12 01:18:02 2024

Found 75 results from 2024-10-05 to 2024-10-12
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Fe/FeCo-based metal-organic framework nanosheet/ nanoparticle directly grown on nickel foam as a stable electrode for electrochemical oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403119174
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.10.003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403119174"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403119174"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403119174"))][Get cited by]]

OpenAlex: https://openalex.org/W4403119174 (Open access: False)
    
[[https://openalex.org/A5021593506][Jiangyan Dang]], [[https://openalex.org/A5107674748][Uzma sattar]], [[https://openalex.org/A5100966760][Wenjuan Xu]], [[https://openalex.org/A5100449445][Xiaoying Zhang]], [[https://openalex.org/A5100359871][Wenliang Li]], [[https://openalex.org/A5053537780][Jingping Zhang]], International Journal of Hydrogen Energy. 89(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.10.003 
     
No abstract    

    

* Facile fabrication of thiourea-intercalated iron-cobalt-nickel layered double hydroxides on nickel foam for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403120601
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235403")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403120601"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403120601"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403120601"))][Get cited by]]

OpenAlex: https://openalex.org/W4403120601 (Open access: False)
    
[[https://openalex.org/A5101392289][Chun Geng Sun]], [[https://openalex.org/A5025806620][Zhongcheng Zhao]], [[https://openalex.org/A5017471501][Dongyan Xu]], [[https://openalex.org/A5100633212][Xiaojin Li]], [[https://openalex.org/A5072537853][Ke Ye]], Journal of Power Sources. 623(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235403 
     
No abstract    

    

* Vanadate-Mediated Mismatch Configuration over the Reconstructed Nickel–Iron Electrocatalyst for Boosting Alkaline Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403130365
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.4c03670")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403130365"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403130365"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403130365"))][Get cited by]]

OpenAlex: https://openalex.org/W4403130365 (Open access: False)
    
[[https://openalex.org/A5005268469][Ruopeng Li]], [[https://openalex.org/A5011555779][Youzheng Wu]], [[https://openalex.org/A5089539354][Peixia Yang]], [[https://openalex.org/A5025757874][Yaqiang Li]], [[https://openalex.org/A5032787806][Fan Meng]], [[https://openalex.org/A5101341371][Yuhao Fan]], [[https://openalex.org/A5100411770][Dan Wang]], [[https://openalex.org/A5034700166][Penghui Ren]], [[https://openalex.org/A5102920844][Hao Xu]], [[https://openalex.org/A5023702000][Xuesong Peng]], [[https://openalex.org/A5102502381][Weirun Zhu]], [[https://openalex.org/A5100460889][Hui Wang]], [[https://openalex.org/A5102856042][Jiang Qin]], [[https://openalex.org/A5031711386][Jinqiu Zhang]], [[https://openalex.org/A5101883167][Maozhong An]], Nano Letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.4c03670 
     
During the oxygen evolution reaction (OER), catalyst candidates that can fully trigger self-reconstruction to derive active species with favorable configurations are expected to overcome the sluggish reaction kinetics. Herein, we innovatively propose the introduction of heterogeneous vanadate dopants into nickel-iron alloy precatalysts, where the crystal mismatch structure induces local electron delocalization in the hexagonal close packed alloy phase, thereby facilitating adequate electrochemical reconstruction to form (oxy)hydroxides as the real catalytic species. Simultaneously, the participation of vanadate in the reconstruction also triggers mismatch in the derived (oxy)hydroxides, reinforcing the metal-oxygen covalence, so that lattice oxygen activation is kinetically favorable and facilitates the OER via the lattice oxygen pathway. Optimized reconstructed catalyst r-NiFeVO    

    

* High-Entropy Engineering in Hollow Layered Hydroxide Arrays to Boost 5-Hydroxymethylfurfural Electrooxidation by Suppressing Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403138626
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscentsci.4c01085")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403138626"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403138626"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403138626"))][Get cited by]]

OpenAlex: https://openalex.org/W4403138626 (Open access: True)
    
[[https://openalex.org/A5034761551][Xin Yu]], [[https://openalex.org/A5056325752][Hongchuan Fu]], [[https://openalex.org/A5100698222][Liyu Chen]], [[https://openalex.org/A5072753033][Yongfei Ji]], [[https://openalex.org/A5100643109][Yingwei Li]], [[https://openalex.org/A5090629837][Kui Shen]], ACS Central Science. None(None)] 2024. https://doi.org/10.1021/acscentsci.4c01085 
     
No abstract    

    

* Rational Design of Diatomic Active Sites for Elucidating Oxygen Evolution Reaction Performance Trends  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403140657
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202413749")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403140657"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403140657"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403140657"))][Get cited by]]

OpenAlex: https://openalex.org/W4403140657 (Open access: False)
    
[[https://openalex.org/A5056972184][Nanfeng Xu]], [[https://openalex.org/A5021304834][Yuxiang Jin]], [[https://openalex.org/A5051820883][Qiunan Liu]], [[https://openalex.org/A5100770786][Meng Yu]], [[https://openalex.org/A5100411473][Xiao Wang]], [[https://openalex.org/A5100322864][Li Wang]], [[https://openalex.org/A5022293237][Wei Tu]], [[https://openalex.org/A5100602195][Zhirong Zhang]], [[https://openalex.org/A5043633750][Zhigang Geng]], [[https://openalex.org/A5062940537][Kazu Suenaga]], [[https://openalex.org/A5049506458][Fangyi Cheng]], [[https://openalex.org/A5055999788][Erhong Song]], [[https://openalex.org/A5034722101][Zhangquan Peng]], [[https://openalex.org/A5067389666][Junyuan Xu]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202413749 
     
Diatomic catalysts, especially those with heteronuclear active sites, have recently attracted significant attention for their advantages over single‐atom catalysts in reactions with relatively high energy barrier, e.g. oxygen evolution reaction. Rational design and synthesis of heteronuclear diatomic catalysts are of immense significance but have so far been plagued by the lack of a definitive correlation between structure and catalytic properties. Here, we report macrocyclic precursor constrained strategy to fabricate series of transition metal (MT, Ni, Co, Fe, Mn, or Cu)‐noble (MN, Ir or Ru) centers in carbon material. One notable performance trend is observed in the order of Cu‐MN < Mn‐MN < Fe‐MN < MN < Co‐MN < Ni‐MN. However, the pathway has been not altered, still following the traditional adsorption reaction mechanism. The effect of the MT atoms on the performances could possibly originate from the distinct adsorption/desorption behaviors of key intermediates (i.e. *OH, *O and/or *OOH), strongly implying that ΔG*OOH‐ΔG*OH could be used as the performance descriptor. We believe that our work provides useful strategy for synthesis of diatomic active sites with sole coordination configuration and varied composition, and in‐depth insight to their catalytic mechanism, which could be used for further optimization of diatomic catalysts towards oxygen electrocatalysis.    

    

* Novel electrocatalyst with abundant oxygen vacancies Enabling efficient Two-Electron water oxidation reaction for H2O2 synthesis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403143747
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.156418")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403143747"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403143747"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403143747"))][Get cited by]]

OpenAlex: https://openalex.org/W4403143747 (Open access: False)
    
[[https://openalex.org/A5107157374][Chemeda Barasa Guta]], [[https://openalex.org/A5093613204][Habib Gemechu Edao]], [[https://openalex.org/A5027860241][Woldesenbet Bafe Dilebo]], [[https://openalex.org/A5061126514][Chia‐Yu Chang]], [[https://openalex.org/A5026201499][Fikiru Temesgen Angerasa]], [[https://openalex.org/A5069681139][Endalkachew Asefa Moges]], [[https://openalex.org/A5082309206][Yosef Nikodimos]], [[https://openalex.org/A5048665495][Keseven Lakshmanan]], [[https://openalex.org/A5011428472][Meng‐Che Tsai]], [[https://openalex.org/A5031136629][Wei‐Nien Su]], [[https://openalex.org/A5030917995][Bing‐Joe Hwang]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.156418 
     
No abstract    

    

* Boosting the Bifunctional Catalytic Activity of Co3O4 on Silver and Nickel Substrates for the Alkaline Oxygen Evolution and Reduction Reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403143985
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.105218")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403143985"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403143985"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403143985"))][Get cited by]]

OpenAlex: https://openalex.org/W4403143985 (Open access: False)
    
[[https://openalex.org/A5103187322][Richard G. Compton]], [[https://openalex.org/A5083644369][Lingxing Zan]], [[https://openalex.org/A5079323430][Helmut Baltruschat]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.105218 
     
No abstract    

    

* The mechanisms of the copper-carbonate catalyzed oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403147718
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-10-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1080/00958972.2024.2409824")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403147718"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403147718"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403147718"))][Get cited by]]

OpenAlex: https://openalex.org/W4403147718 (Open access: False)
    
[[https://openalex.org/A5107765848][Oren Rozanski]], [[https://openalex.org/A5103247426][Dan Meyerstein]], Journal of Coordination Chemistry. None(None)] 2024. https://doi.org/10.1080/00958972.2024.2409824 
     
No abstract    

    

* Continuous lattice oxygen participation of NiFe stack anode for Sustainable water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403152048
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.156469")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403152048"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403152048"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403152048"))][Get cited by]]

OpenAlex: https://openalex.org/W4403152048 (Open access: False)
    
[[https://openalex.org/A5073903036][Sinwoo Kang]], [[https://openalex.org/A5013946603][Dong-yeol Lee]], [[https://openalex.org/A5005479319][Yeongin Kim]], [[https://openalex.org/A5011044307][Sooan Bae]], [[https://openalex.org/A5100334532][Jaeyoung Lee]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.156469 
     
No abstract    

    

* High‐Entropy Ag‐Ru‐based Electrocatalysts with Dual‐Active‐Center for Highly Stable Ultra‐Low‐Temperature Zinc‐Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403165063
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202415216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403165063"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403165063"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403165063"))][Get cited by]]

OpenAlex: https://openalex.org/W4403165063 (Open access: True)
    
[[https://openalex.org/A5034351888][Ziming Qiu]], [[https://openalex.org/A5100724115][Xiaotian Guo]], [[https://openalex.org/A5076507725][Shuai Cao]], [[https://openalex.org/A5060756190][Meng Du]], [[https://openalex.org/A5060311561][Qinchao Wang]], [[https://openalex.org/A5008846267][Yecan Pi]], [[https://openalex.org/A5006121200][Chun‐Sen Liu]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202415216  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/anie.202415216][pdf]])
     
The development of advanced bifunctional catalysts for oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) is significant for rechargeable zinc‐air batteries (ZABs). Herein, a unique dual active center alloying strategy is proposed to achieve the efficient bifunctional oxygen catalysis, and the high entropy effect is further exploited to modulate the structure and performance of the catalysts. The MOF‐assisted pyrolysis‐replacement‐alloying method was employed to construct the CoCuFeAgRu high‐entropy alloy (HEA), which are uniformly anchored in porous nitrogen‐doped carbon nanosheets. Notably, the obtained HEA catalyst exhibits excellent catalytic performance for both ORR and OER, and a peak power density of 136. 53 mW cm‐2 and an energy density of 987.9 mAh gZn‐1, surpassing the most of the previously reported bifunctional oxygen electrocatalysts. Moreover, the assembled flexible rechargeable ZAB enables excellent performance even at the ultralow temperature of ‐40°C, with an energy density of 601.6 mAh gZn‐1 and remarkable cycling stability up to 1,650 hours. Combined experimental and theoretical calculation results reveal that the excellent bifunctional catalytic activity of the HEA catalyst originated from the synergistic effect of the Ag and Ru dual active centers, and the optimization of the electronic structure by alloying effect.    

    

* Phosphorus Doping Heterostructure La(OH)3@CuO @NF as an Advanced Electrocatalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403168525
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijoes.2024.100826")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403168525"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403168525"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403168525"))][Get cited by]]

OpenAlex: https://openalex.org/W4403168525 (Open access: True)
    
[[https://openalex.org/A5088064886][Decui Liang]], [[https://openalex.org/A5019949984][Weishun Hou]], [[https://openalex.org/A5100386252][Ying Zhang]], [[https://openalex.org/A5101388970][Jihua SHANG]], [[https://openalex.org/A5018466210][Haibo Ren]], [[https://openalex.org/A5100945554][Yufeng Sun]], International Journal of Electrochemical Science. None(None)] 2024. https://doi.org/10.1016/j.ijoes.2024.100826 
     
No abstract    

    

* Research Progress in Structure Evolution and Durability Modulation of Ir‐ and Ru‐Based OER Catalysts under Acidic Conditions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403170675
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202406657")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403170675"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403170675"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403170675"))][Get cited by]]

OpenAlex: https://openalex.org/W4403170675 (Open access: False)
    
[[https://openalex.org/A5029664909][You Zi]], [[https://openalex.org/A5064403506][Chengxu Zhang]], [[https://openalex.org/A5077422333][Jian-Qiang Zhao]], [[https://openalex.org/A5043905805][Ying Cheng]], [[https://openalex.org/A5043053835][Jinliang Yuan]], [[https://openalex.org/A5027149538][Jue Hu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202406657 
     
Abstract Green hydrogen energy, as one of the most promising energy carriers, plays a crucial role in addressing energy and environmental issues. Oxygen evolution reaction catalysts, as the key to water electrolysis hydrogen production technology, have been subject to durability constraints, preventing large‐scale commercial development. Under the high current density and harsh acid‐base electrolyte conditions of the water electrolysis reaction, the active metals in the catalysts are easily converted into high‐valent soluble species to dissolve, leading to poor structural durability of the catalysts. There is an urgent need to overcome the durability challenges under acidic conditions and develop electrocatalysts with both high catalytic activity and high durability. In this review, the latest research results are analyzed in depth from both thermodynamic and kinetic perspectives. First, a comprehensive summary of the structural deactivation state process of noble metal oxide catalysts is presented. Second, the evolution of the structure of catalysts possessing high durability is discussed. Finally, four new strategies for the preparation of stable catalysts, “electron buffer (ECB) strategy”, combination strength control, strain control, and surface coating, are summarized. The challenges and prospects are also elaborated for the future synthesis of more effective Ru/Ir‐based catalysts and boost their future application.    

    

* Raman Spectroscopic Observation of Electrolyte-Dependent Oxygen Evolution Reaction Intermediates in Nickel-Based Electrodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403172070
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Advances in Chemical Sensor Technologies, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-k9mr8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403172070"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403172070"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403172070"))][Get cited by]]

OpenAlex: https://openalex.org/W4403172070 (Open access: True)
    
[[https://openalex.org/A5056676776][Tomohiro Fukushima]], [[https://openalex.org/A5079571449][Kanji Tsuchimoto]], [[https://openalex.org/A5048259607][Nobuaki Oyamada]], [[https://openalex.org/A5081655998][Daiki Sato]], [[https://openalex.org/A5064297220][Hiro Minamimoto]], [[https://openalex.org/A5069703005][Kei Murakoshi]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-k9mr8  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/670136c651558a15ef2c07f0/original/raman-spectroscopic-observation-of-electrolyte-dependent-oxygen-evolution-reaction-intermediates-in-nickel-based-electrodes.pdf][pdf]])
     
Oxygen evolution reaction (OER) is the counterpart in the hydrogen production by the water electrolysis. Further challenges have been required to bypass the energy consumption processes in OER. It is still important to unveil the OER intermediates toward the effective green hydrogen production. In this study, we conducted the in-situ Raman observation of the OER intermediates over Ni nanohole-array electrodes in the various electrolyte conditions. Ni nanohole-array electrodes were prepared with the interference exposure methods. Intense Raman peaks were observed from the Ni-OH, Ni-OOH, and active oxygen species as OER intermediates. The OER behavior can be classified with the reactants, such as OH− and H2O. The presented study demonstrates the importance of the electrolyte for the designing active OER catalysis for the next generation energy society.    

    

* Electronic Structure Modulating of W 18 O 49 Nanospheres by Niobium Doping for Efficient Hydrogen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403193963
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202403043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403193963"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403193963"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403193963"))][Get cited by]]

OpenAlex: https://openalex.org/W4403193963 (Open access: False)
    
[[https://openalex.org/A5101391365][Hui Guo]], [[https://openalex.org/A5101999930][Pan Lu]], [[https://openalex.org/A5059775541][Mengyou Gao]], [[https://openalex.org/A5063245517][Linghui Kong]], [[https://openalex.org/A5082715902][Jingpeng Zhang]], [[https://openalex.org/A5032556104][Aslam Khan]], [[https://openalex.org/A5090209489][Nadeem Siddiqui]], [[https://openalex.org/A5086802047][Jianjian Lin]], Chemistry - A European Journal. None(None)] 2024. https://doi.org/10.1002/chem.202403043 
     
Developing efficient electrocatalysts to reduce HER overpotential is vital to enhance hydrogen production efficiency and minimize energy consumption. Adjusting the electronic structure of transition metal oxides via elemental doping is a potent strategy to improve the effectiveness of electrocatalysts for hydrogen evolution. In this work, we synthesized a set of niobium‐doped tungsten oxides (Nbx‐W18O49) under anoxic conditions using a straightforward “one‐pot” solvothermal approach. After doping Nb, the oxygen vacancy content inside W18O49 was increased, which induced a synergistic effect with the active sites of tungsten. In acidic environments, the hydrogen evolution activity of the Nb0.6‐W18O49 electrocatalyst is second only by 20 wt% Pt/C. It attains a current density of ‐10 mA cm‐2 at an overpotential of 102 mV. By comparison with W18O49, Nb0.4‐W18O49 and Nb0.5‐W18O49, Nb0.6‐W18O49 demonstrates a reduced charge transfer resistance, which significantly enhances its conductivity and the speed of electron movement across interfaces. Coupled with this feature are notably faster HER kinetics. Additionally, it exhibits excellent stability, meaning it maintains its performance and structural integrity over prolonged periods and under various operational conditions. This article provides a new perspective for discovering inexpensive and efficient hydrogen evolution electrocatalyst materials.    

    

* Effects of Dynamic Surface Transformation on the Activity and Stability of Mixed Co‐Mn Cubic Spinel Oxides in the Oxygen Evolution Reaction in Alkaline Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403194568
:TOPICS: Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202403096")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403194568"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403194568"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403194568"))][Get cited by]]

OpenAlex: https://openalex.org/W4403194568 (Open access: True)
    
[[https://openalex.org/A5064556208][Biao He]], [[https://openalex.org/A5001479913][Pouya Hosseini]], [[https://openalex.org/A5053923970][Daniel Escalera‐López]], [[https://openalex.org/A5038730574][Jonas Schulwitz]], [[https://openalex.org/A5053491539][Serena DeBeer]], [[https://openalex.org/A5074048659][Ulrich Hagemann]], [[https://openalex.org/A5009434127][Markus Heidelmann]], [[https://openalex.org/A5053491539][Serena DeBeer]], [[https://openalex.org/A5039691617][Martin Muhler]], [[https://openalex.org/A5073666601][Serhiy Cherevko]], [[https://openalex.org/A5030444454][Kristina Tschulik]], [[https://openalex.org/A5100783224][Tong Li]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202403096 
     
Abstract An atomic‐scale understanding of how electrocatalyst surfaces reconstruct and transform during electrocatalytic reactions is essential for optimizing their activity and longevity. This is particularly important for the oxygen evolution reaction (OER), where dynamic and substantial structural and compositional changes occur during the reaction. Herein, a multimodal method is developed by combining X‐ray fine structure absorption and photoemission spectroscopy, transmission electron microscopy, and atom probe tomography with electrochemical measurements to interrogate the temporal evolution of oxidation states, atom coordination, structure, and composition on Co 2 MnO 4 and CoMn 2 O 4 cubic spinel nanoparticle surfaces upon OER cycling in alkaline media. Co 2 MnO 4 is activated at the onset of OER due to the formation of ≈2 nm Co‐Mn oxyhydroxides with an optimal Co/Mn ratio of ≈3. As OER proceeds, Mn dissolution and redeposition occur for the CoMn oxyhydroxides, extending the OER stability of Co 2 MnO 4 . Such dynamic dissolution and redeposition are also observed for CoMn 2 O 4 , leading to the formation of less OER‐active Mn‐rich oxides on the nanoparticle surfaces. This study provides mechanistic insights into how dynamic surface reconstruction and transformation affect the activity and stability of mixed CoMn cubic spinels toward OER.    

    

* High‐Efficiency Photo‐Assisted Large Current‐Density Water Splitting with Mott‐Schottky Heterojunctions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403195683
:TOPICS: Electrocatalysis for Energy Conversion, Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202415492")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403195683"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403195683"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403195683"))][Get cited by]]

OpenAlex: https://openalex.org/W4403195683 (Open access: True)
    
[[https://openalex.org/A5044465572][Minming Jiang]], [[https://openalex.org/A5103038896][Jiang Xu]], [[https://openalex.org/A5100459039][Yujie Chen]], [[https://openalex.org/A5101733772][Luqi Wang]], [[https://openalex.org/A5026716909][Paul Munroe]], [[https://openalex.org/A5056283665][Zonghan Xie]], [[https://openalex.org/A5034879972][Shengjie Peng]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202415492  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/anie.202415492][pdf]])
     
The development of bifunctional photogenerated carrier‐assisted electrocatalytic (PCA‐EC) electrodes that operate with stability at large current‐density remains a significant challenge. Herein, we demonstrate a simple sputtering‐deposition process to synthesize a novel MnWO4/FeCoNi Mott‐Schottky heterojunction coating and deposit it on a pure Ti substrate to prepare high‐performance PCA‐EC electrodes, which exhibits enhanced light absorption range/intensity and rapidly separated photogenerated electron‐hole pairs. This design allows photogenerated electrons to directly participate in the hydrogen evolution reaction (HER), while the strong oxidation of photogenerated holes significantly reduces the defect formation energy of active metals, thereby facilitating the rapid reconstruction of highly active Ni(FeCo)OOH/MnOOH species for the oxygen evolution reaction (OER). As expected, the as‐prepared electrode demonstrates the overpotentials of 64 mV for the HER and 204 mV for the OER at 10 mA cm−2 under illumination. Benefiting from the stable interface with Fe/Co/Ni‐O‐Mn/W bonding units, the dual‐electrode photoassisted electrolytic cell achieves long‐term stability at current densities of 500 and 1000 mA cm−2. This work provides detailed insights into the enhancement mechanism of PCA‐EC and contributes to the development of photo‐assisted water splitting electrodes for large current‐density applications.    

    

* Closed‐Loop and Precipitation‐Free CO2 Capture Process Enabled by Electrochemical pH Gradient  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403199271
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Membrane Gas Separation Technology, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401533")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403199271"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403199271"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403199271"))][Get cited by]]

OpenAlex: https://openalex.org/W4403199271 (Open access: False)
    
[[https://openalex.org/A5064060507][Jiayin Zhou]], [[https://openalex.org/A5059212792][Xiaofei Guan]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401533 
     
Carbon dioxide (CO2) capture is a crucial negative‐emission technology for the mitigation of climate change and global warming. The urgent need of combating climate change motivates the research and development of economical, effective and environmentally benign processes for CO2 capture. Herein, we design and report a flow cell for the CO2 capture from air or flue gas in a precipitate‐free and closed‐loop manner. No ion‐exchange membrane is used in the electrolyser. The water electrolysis produces acidic solution near the anode and alkaline solution near the cathode, while generating valuable hydrogen and oxygen byproducts. The dilute CO2 in air or flue gas is captured by the alkaline solution, which is then mixed with the acidic solution to release the concentrated CO2. The process operates in a cyclic manner as driven by the water electrolysis and the mechanical pumping. No precipitation of calcium carbonate is involved for fixing CO2, which may simplify the separation process and minimizing the materials loss. The simple process enabled by electrochemical pH gradient shows promise for efficient CO2 capture on both small and large scales.    

    

* Advanced In Situ Spectroscopic Techniques for Probing the Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403199440
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.4c05891")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403199440"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403199440"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403199440"))][Get cited by]]

OpenAlex: https://openalex.org/W4403199440 (Open access: False)
    
[[https://openalex.org/A5022584221][Suk-Kyoung Hong]], [[https://openalex.org/A5075486320][Ze‐Cheng Yao]], [[https://openalex.org/A5000380050][Xing Cheng]], [[https://openalex.org/A5101930537][Zhe Jiang]], [[https://openalex.org/A5008036335][Tang Tang]], [[https://openalex.org/A5043884286][Jin‐Song Hu]], The Journal of Physical Chemistry C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.4c05891 
     
No abstract    

    

* Coordination Tuning of Ni/Fe Complexes based Electrocatalysts for Enhanced Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403201390
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4qi01934b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403201390"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403201390"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403201390"))][Get cited by]]

OpenAlex: https://openalex.org/W4403201390 (Open access: False)
    
[[https://openalex.org/A5065543748][Hong Zhou]], [[https://openalex.org/A5049422615][Xuan Hao]], [[https://openalex.org/A5104171663][Jiexin Guan]], [[https://openalex.org/A5023830330][Yilin Deng]], [[https://openalex.org/A5046416746][Zi Wei]], [[https://openalex.org/A5101485471][Yashu Liu]], [[https://openalex.org/A5103635416][Guofeng Zhu]], Inorganic Chemistry Frontiers. None(None)] 2024. https://doi.org/10.1039/d4qi01934b 
     
Non-noble oxygen evolution reaction (OER) catalysts have garnered considerable attention in recent years. Alkaline OER catalysts based on coordination complexes exhibit high performance but often undergo irreversible ligand dissociation, resulting...    

    

* Regulation of electrocatalytic properties of high entropy alloy electrocatalysts for oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403202259
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04984e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403202259"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403202259"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403202259"))][Get cited by]]

OpenAlex: https://openalex.org/W4403202259 (Open access: False)
    
[[https://openalex.org/A5101558625][Xiaojun Lv]], [[https://openalex.org/A5011172552][kaixin wang]], [[https://openalex.org/A5100318645][Guoqiang Wang]], [[https://openalex.org/A5100346547][Ye Liu]], [[https://openalex.org/A5102621776][Qianqian Cai]], [[https://openalex.org/A5089725500][Xueyuan Chen]], [[https://openalex.org/A5100433920][Lei Zhang]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta04984e 
     
With the rapid increase of demand for green hydrogen, the development of electrolytic water technology has been widely concerned. The efficient oxygen evolution catalyst provides the feasibility of hydrogen production...    

    

* Enhanced oxygen evolution reaction in alkaline water electrolysis using bimetallic NiFe metal-organic frameworks integrated with carbon nanotubes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403204122
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.10.039")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403204122"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403204122"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403204122"))][Get cited by]]

OpenAlex: https://openalex.org/W4403204122 (Open access: False)
    
[[https://openalex.org/A5101680707][Sungwon Cho]], [[https://openalex.org/A5085402319][Joo Hyun Kang]], [[https://openalex.org/A5001325073][Huy Du Nguyen]], [[https://openalex.org/A5033251223][Kwon Seok Chae]], [[https://openalex.org/A5008798768][Nguyen Anh Thu Tran]], [[https://openalex.org/A5102018865][Young‐Woo Lee]], [[https://openalex.org/A5083304744][Jinkee Hong]], [[https://openalex.org/A5007884412][Dongwon Shin]], [[https://openalex.org/A5045489385][Hyun‐Seok Cho]], [[https://openalex.org/A5101500728][Younghyun Cho]], International Journal of Hydrogen Energy. 90(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.10.039 
     
No abstract    

    

* Pt Single Atom‐Doped Triphasic VP‐Ni3P‐MoP Heterostructure: Unveiling a Breakthrough Electrocatalyst for Efficient Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403213720
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202405952")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403213720"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403213720"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403213720"))][Get cited by]]

OpenAlex: https://openalex.org/W4403213720 (Open access: False)
    
[[https://openalex.org/A5045395357][Ganesh Bhandari]], [[https://openalex.org/A5060234952][Purna Prasad Dhakal]], [[https://openalex.org/A5101870136][Duy Thanh Tran]], [[https://openalex.org/A5101950010][Thanh Hai Nguyen]], [[https://openalex.org/A5106607234][Van An Dinh]], [[https://openalex.org/A5100615737][Nam Hoon Kim]], [[https://openalex.org/A5103002413][Joong Hee Lee]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202405952 
     
Abstract Enhancement of an alkaline water splitting reaction in Pt‐based single‐atom catalysts (SACs) relies on effective metal‐support interactions. A Pt single atom (Pt SA )‐immobilized three‐phased Pt SA @VP‐Ni 3 P‐MoP heterostructure on nickel foam is presented, demonstrating high catalytic performance. The existence of Pt SA on triphasic metal phosphides gives an outstanding performance toward overall water splitting. The Pt SA @VP‐Ni 3 P‐MoP performs a low overpotential of 28 and 261 mV for hydrogen evolution reaction (HER) and oxygen evolution reaction (OER) at a current density of 10 and 25 mA cm −2 , respectively. The Pt SA @VP‐Ni 3 P‐MoP (+,−) alkaline electrolyzer achieves a minimum cell voltage of 1.48 V at a current density of 10 mA cm −2 for overall water splitting. Additionally, the electrocatalyst exhibits a substantial Faradaic yield of ≈98.12% for H 2 and 98.47% for O 2 at a current density of 50 mA cm −2 . Consequently, this study establishes a connection for understanding the active role of single metal atoms in substrate configuration for catalytic performance. It also facilitates the successful synthesis of SACs, with a substantial loading on transition metal phosphides and maximal atomic utilization, providing more active sites and, thereby enhancing electrocatalytic activity.    

    

* Unveiling the Structure and Dissociation of Interfacial Water on RuO2 for Efficient Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403214909
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202413334")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403214909"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403214909"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403214909"))][Get cited by]]

OpenAlex: https://openalex.org/W4403214909 (Open access: False)
    
[[https://openalex.org/A5103255324][Liqing Wu]], [[https://openalex.org/A5063535343][Wenxia Huang]], [[https://openalex.org/A5100459318][Dongyang Li]], [[https://openalex.org/A5061834556][Hongnan Jia]], [[https://openalex.org/A5101728440][Bingbing Zhao]], [[https://openalex.org/A5033441626][Juan Zhu]], [[https://openalex.org/A5016078941][Haiqing Zhou]], [[https://openalex.org/A5100392071][Wei Wang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202413334 
     
Understanding the structure and dynamic process of interfacial water molecules at the catalyst‐electrolyte interface on acidic oxygen evolution reaction (OER) kinetics is highly desirable for the development of proton exchange membrane water electrolyzers. Herein, we construct a series of p‐block metallic elements (Ga, In, Sn) doped RuO2 catalysts with manipulated electronic structure and Ru‐O covalency to investigate the effect of electrochemical interfacial engineering on the improvement of acidic OER activity. Associated with operando attenuated total reflectance surface‐enhanced infrared absorption spectroscopy measurements and theoretical analysis, we uncover the free‐H2O enriched local environment and dynamic evolution from 4‐coordinated hydrogen‐bonded water and 2‐coordinated hydrogen‐bonded water to free‐H2O on the surface of Ga‐RuO2, are responsible for the optimized connectivity of hydrogen bonding network in the electrical double layer by promoting solvent reorganization. In addition, the structurally ordered interfacial water molecules facilitate high‐efficiency proton‐coupled electron transfer across the interface, leading to reduced energy barrier of the follow‐up dissociation process and enhanced acidic OER performance. This work highlights the key role of structure and dynamic process of interfacial water for acidic OER, and demonstrates the electrochemical interfacial engineering as an efficient strategy to design high‐performance electrocatalysts.    

    

* Unveiling the Structure and Dissociation of Interfacial Water on RuO2 for Efficient Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403218349
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202413334")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403218349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403218349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403218349"))][Get cited by]]

OpenAlex: https://openalex.org/W4403218349 (Open access: True)
    
[[https://openalex.org/A5001271717][Liqing Wu]], [[https://openalex.org/A5063535343][Wenxia Huang]], [[https://openalex.org/A5100459318][Dongyang Li]], [[https://openalex.org/A5061834556][Hongnan Jia]], [[https://openalex.org/A5101728440][Bingbing Zhao]], [[https://openalex.org/A5033441626][Juan Zhu]], [[https://openalex.org/A5016078941][Haiqing Zhou]], [[https://openalex.org/A5062213729][Wei Luo]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202413334  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/anie.202413334][pdf]])
     
Understanding the structure and dynamic process of interfacial water molecules at the catalyst‐electrolyte interface on acidic oxygen evolution reaction (OER) kinetics is highly desirable for the development of proton exchange membrane water electrolyzers. Herein, we construct a series of p‐block metallic elements (Ga, In, Sn) doped RuO2 catalysts with manipulated electronic structure and Ru‐O covalency to investigate the effect of electrochemical interfacial engineering on the improvement of acidic OER activity. Associated with operando attenuated total reflectance surface‐enhanced infrared absorption spectroscopy measurements and theoretical analysis, we uncover the free‐H2O enriched local environment and dynamic evolution from 4‐coordinated hydrogen‐bonded water and 2‐coordinated hydrogen‐bonded water to free‐H2O on the surface of Ga‐RuO2, are responsible for the optimized connectivity of hydrogen bonding network in the electrical double layer by promoting solvent reorganization. In addition, the structurally ordered interfacial water molecules facilitate high‐efficiency proton‐coupled electron transfer across the interface, leading to reduced energy barrier of the follow‐up dissociation process and enhanced acidic OER performance. This work highlights the key role of structure and dynamic process of interfacial water for acidic OER, and demonstrates the electrochemical interfacial engineering as an efficient strategy to design high‐performance electrocatalysts.    

    

* Bifunctional catalytic activity of anion-doped LaSrCoO 4 for oxygen reduction and evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403259305
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1098/rsos.240387")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403259305"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403259305"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403259305"))][Get cited by]]

OpenAlex: https://openalex.org/W4403259305 (Open access: True)
    
[[https://openalex.org/A5030520387][Ittoku Nozawa]], [[https://openalex.org/A5003300746][Hidehisa Hagiwara]], Royal Society Open Science. 11(10)] 2024. https://doi.org/10.1098/rsos.240387  ([[https://royalsocietypublishing.org/doi/pdf/10.1098/rsos.240387][pdf]])
     
Here, we synthesized Co-based, anion-incorporated‍ ‌R‌u‌d‌d‌l‌e‌s-d‌e‌n‌-‌Popper perovskite electrocatalysts (LaSrCoO    

    

* Rational Design of Diatomic Active Sites for Elucidating Oxygen Evolution Reaction Performance Trends  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403140470
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202413749")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403140470"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403140470"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403140470"))][Get cited by]]

OpenAlex: https://openalex.org/W4403140470 (Open access: False)
    
[[https://openalex.org/A5056972184][Nanfeng Xu]], [[https://openalex.org/A5102303641][Yuxiang Jin]], [[https://openalex.org/A5051820883][Qiunan Liu]], [[https://openalex.org/A5034510572][Meng Yu]], [[https://openalex.org/A5081883145][Zibo Wang]], [[https://openalex.org/A5100444820][Xiaogang Wang]], [[https://openalex.org/A5101934722][Wei Tu]], [[https://openalex.org/A5100602201][Zhirong Zhang]], [[https://openalex.org/A5043633750][Zhigang Geng]], [[https://openalex.org/A5062940537][Kazu Suenaga]], [[https://openalex.org/A5049506458][Fangyi Cheng]], [[https://openalex.org/A5055999788][Erhong Song]], [[https://openalex.org/A5034722101][Zhangquan Peng]], [[https://openalex.org/A5067389666][Junyuan Xu]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202413749 
     
Diatomic catalysts, especially those with heteronuclear active sites, have recently attracted significant attention for their advantages over single‐atom catalysts in reactions with relatively high energy barrier, e.g. oxygen evolution reaction. Rational design and synthesis of heteronuclear diatomic catalysts are of immense significance but have so far been plagued by the lack of a definitive correlation between structure and catalytic properties. Here, we report macrocyclic precursor constrained strategy to fabricate series of transition metal (MT, Ni, Co, Fe, Mn, or Cu)‐noble (MN, Ir or Ru) centers in carbon material. One notable performance trend is observed in the order of Cu‐MN < Mn‐MN < Fe‐MN < MN < Co‐MN < Ni‐MN. However, the pathway has been not altered, still following the traditional adsorption reaction mechanism. The effect of the MT atoms on the performances could possibly originate from the distinct adsorption/desorption behaviors of key intermediates (i.e. *OH, *O and/or *OOH), strongly implying that ΔG*OOH‐ΔG*OH could be used as the performance descriptor. We believe that our work provides useful strategy for synthesis of diatomic active sites with sole coordination configuration and varied composition, and in‐depth insight to their catalytic mechanism, which could be used for further optimization of diatomic catalysts towards oxygen electrocatalysis.    

    

* Regulating Local Coordination Sphere of Ir Single Atoms at the Atomic Interface for Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403208726
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c08847")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403208726"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403208726"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403208726"))][Get cited by]]

OpenAlex: https://openalex.org/W4403208726 (Open access: True)
    
[[https://openalex.org/A5101675957][Ashwani Kumar]], [[https://openalex.org/A5042194356][Marcos Gil‐Sepulcre]], [[https://openalex.org/A5058780014][Pascal Fandré]], [[https://openalex.org/A5000971313][Olaf Rüdiger]], [[https://openalex.org/A5100383157][Min Gyu Kim]], [[https://openalex.org/A5053491539][Serena DeBeer]], [[https://openalex.org/A5060841613][Harun Tüysüz]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c08847 
     
Single-atom catalysts dispersed on an oxide support are essential for overcoming the sluggishness of the oxygen evolution reaction (OER). However, the durability of most metal single-atoms is compromised under harsh OER conditions due to their low coordination (weak metal-support interactions) and excessive disruption of metal-O    

    

* Simultaneous Measurement of Gross Oxygen Evolution and Underlying Photosynthetic Redox Reactions: A Case Study Using Cyanobacteria  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403143045
:TOPICS: On-line Monitoring of Wastewater Quality
:PUBLICATION_DATE: 2024-10-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2024.10.03.616403")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403143045"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403143045"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403143045"))][Get cited by]]

OpenAlex: https://openalex.org/W4403143045 (Open access: True)
    
[[https://openalex.org/A5074018177][Oded Liran]], bioRxiv (Cold Spring Harbor Laboratory). None(None)] 2024. https://doi.org/10.1101/2024.10.03.616403 
     
In phytoplankton, the intricate balance between respiration and photosynthesis is co-regulated to ensure efficient energy management and adaptation to varying environmental conditions. In cyanobacteria, both processes occur on the same membrane, sharing electron transport carriers within the same cellular compartment. By studying the interaction between photosynthesis and respiration, we can better understand how cyanobacteria balance their energetic budget for survival. In this study, we present an integrated approach that combines tracking gas exchange between cyanobacteria and their environment with analysing the redox kinetics of the underlying photosynthetic electron transport chain. This combined system allows for real-time, simultaneous acquisition of respiration and photosynthesis data. For example, it enabled us to show that the electron transport rate generated by photosystem II, translated to in-vivo oxygen concentration, equals the actual concentration of oxygen produced by water splitting plus the amount of oxygen respired. We further demonstrate that our system can accurately assess light respiration in wild-type strains of cyanobacteria, which amounts to 1/10 of their photosynthetic activity under optimal growth conditions. This level of accuracy was previously achievable only with specific cyanobacteria mutants. We envision applying this system in monitoring programs to elaborate on the role of photosynthetic light reactions within the broader context of primary productivity and to understand its dynamics in response to fluctuations in external environmental conditions.    

    

* Self-Supporting FeCoNiCuTiGa High-Entropy Alloy Electrodes for Alkaline Hydrogen and Oxygen Evolution Reactions: Experimental and Theoretical Insights  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403215206
:TOPICS: Electrocatalysis for Energy Conversion, High-Entropy Alloys: Novel Designs and Properties, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.4c01036")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403215206"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403215206"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403215206"))][Get cited by]]

OpenAlex: https://openalex.org/W4403215206 (Open access: False)
    
[[https://openalex.org/A5042195984][Yezeng He]], [[https://openalex.org/A5102182718][Jiazhen Wu]], [[https://openalex.org/A5078037264][Fangyu Hu]], [[https://openalex.org/A5074463904][Liang Mao]], [[https://openalex.org/A5076026149][Tejraj M. Aminabhavi]], [[https://openalex.org/A5014458126][Yasser Vasseghian]], [[https://openalex.org/A5015219834][Akbar Hojjati–Najafabadi]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.4c01036 
     
No abstract    

    

* Synergistic Effects of FeNi Bimetal-Doped Biochar on Oxygen Evolution Reaction Kinetics: A One-Step, Low-Temperature Pyrolysis Approach  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403147813
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cattod.2024.115082")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403147813"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403147813"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403147813"))][Get cited by]]

OpenAlex: https://openalex.org/W4403147813 (Open access: False)
    
[[https://openalex.org/A5100688200][Qiaoling Liu]], [[https://openalex.org/A5035366118][Baofeng Zhao]], [[https://openalex.org/A5012877703][Haibin Guan]], [[https://openalex.org/A5005029883][Jian Sun]], [[https://openalex.org/A5101821674][Di Zhu]], [[https://openalex.org/A5033348859][Bari Wulan]], [[https://openalex.org/A5005394616][Laizhi Sun]], [[https://openalex.org/A5089030200][Angang Song]], [[https://openalex.org/A5100622274][Chongmin Wang]], [[https://openalex.org/A5100986468][Qing Yao]], Catalysis Today. None(None)] 2024. https://doi.org/10.1016/j.cattod.2024.115082 
     
No abstract    

    

* Size-Dependent Core–Shell Fine Structures and Oxygen Evolution Activity of Electrochemical IrOx Nanoparticles Revealed by Cryogenic Electron Microscopy  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403213920
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Advanced Materials for Smart Windows
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.4c10657")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403213920"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403213920"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403213920"))][Get cited by]]

OpenAlex: https://openalex.org/W4403213920 (Open access: False)
    
[[https://openalex.org/A5103691216][Jingbo Xu]], [[https://openalex.org/A5037607492][Liang Chang]], [[https://openalex.org/A5012363093][Yinping Wei]], [[https://openalex.org/A5100626070][Jie Wei]], [[https://openalex.org/A5033107823][Wenting Cui]], [[https://openalex.org/A5032569996][Taokai Ying]], [[https://openalex.org/A5051784756][Lin Gan]], ACS Nano. None(None)] 2024. https://doi.org/10.1021/acsnano.4c10657 
     
Electrochemically oxidized amorphous iridium oxides (IrO    

    

* Fe single atoms coupled Fe3C multi-functional catalysts on P, F, N-doped carbon nanotubes for stable Zn-air batteries with ultra-high power densities  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403214915
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04194a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403214915"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403214915"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403214915"))][Get cited by]]

OpenAlex: https://openalex.org/W4403214915 (Open access: False)
    
[[https://openalex.org/A5077027902][R. Manigandan]], [[https://openalex.org/A5059340675][Hongsong Yu]], [[https://openalex.org/A5035947425][Anand Rajkamal]], [[https://openalex.org/A5056226186][Gun Jin Yun]], [[https://openalex.org/A5100613118][Ziheng Zhang]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5100392071][Wei Wang]], [[https://openalex.org/A5100540593][Wu Yu]], [[https://openalex.org/A5107821652][Chen Daiqian]], [[https://openalex.org/A5100750156][Bo Yu]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta04194a 
     
It is still challengeable to develop low-cost, efficient, and stable multi-functional electrocatalyst for oxygen evolution (OER), overall water splitting (OWS), oxygen reduction (ORR), and zinc-air batteries (ZABs). To address such...    

    

* Exploring Hybrid Seawater Electrolysis with Anodic Oxidation Reactions (AORs): Recent Progress and Prospect  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403173965
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4se01191k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403173965"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403173965"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403173965"))][Get cited by]]

OpenAlex: https://openalex.org/W4403173965 (Open access: False)
    
[[https://openalex.org/A5071537088][Baghendra Singh]], [[https://openalex.org/A5054237579][Anuj Goyal]], [[https://openalex.org/A5084919770][Sunil Verma]], [[https://openalex.org/A5049323293][Lakhwinder Singh]], [[https://openalex.org/A5077518541][Apparao Draksharapu]], Sustainable Energy & Fuels. None(None)] 2024. https://doi.org/10.1039/d4se01191k 
     
The major obstacle in electrocatalytic seawater splitting (ESS) is the electro-oxidation of dissolved ions at the anode, which causes significant electrode corrosion and competes with the oxygen evolution reaction (OER),...    

    

* Porous and B‐site Substituted Y2[Mn0.2Ru0.8]2O7 Pyrochlore for Boosting Acidic Water Oxidation Activity and Stability  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403164899
:TOPICS: Pyrochlore as Nuclear Waste Form, Quantum Spin Liquids in Frustrated Magnets, Novel Methods for Cesium Removal from Wastewater
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202401419")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403164899"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403164899"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403164899"))][Get cited by]]

OpenAlex: https://openalex.org/W4403164899 (Open access: True)
    
[[https://openalex.org/A5072322326][Zhan Tian]], [[https://openalex.org/A5075109537][Xin Yang]], [[https://openalex.org/A5002908323][Hongrui Jia]], [[https://openalex.org/A5100394072][Бо Лю]], [[https://openalex.org/A5100354165][Guoqiang Li]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202401419  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cctc.202401419][pdf]])
     
Boosting the reaction stability without sacrificing the activity and cost is extremely important but full of challenging for the RuO2‐based oxygen evolution catalysts. Herein, porous and B‐site substituted Y2[Mn0.2Ru0.8]2O7 (p‐Y2[Mn0.2Ru0.8]2O7) pyrochlore toward oxygen evolution reaction is innovatively synthesized. The formed meso/macro‐porous structure can increase the specific surface area and corresponding active sites, meanwhile, Mn‐substitution can modulate the electronic structure, stabilize the morphology, and reduce the dosage of Ru species. Excitingly, the p‐Y2[Mn0.2Ru0.8]2O7 performs 50 h stable operation, significantly outperforming the commercial RuO2(CM) counterpart with less than 2 h life. Furthermore, the required overpotential to achieve 10 mA cm‐2 is only 266 mV, accompanied with favorable reaction kinetics and catalyst utilization.    

    

* Critical Aspects to Select Suitable Substrate for Anodic Oxidation Reactions (AORs)  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403189434
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Advances in Chemical Sensor Technologies, Fabrication and Applications of Porous Alumina Membranes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cy00907j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403189434"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403189434"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403189434"))][Get cited by]]

OpenAlex: https://openalex.org/W4403189434 (Open access: False)
    
[[https://openalex.org/A5071537088][Baghendra Singh]], [[https://openalex.org/A5045907831][Neetu Verma]], Catalysis Science & Technology. None(None)] 2024. https://doi.org/10.1039/d4cy00907j 
     
Hybrid water electrolysis (HWE) stands out as a promising avenue for simultaneously producing high-value-added chemicals and clean H2 fuel. In HWE, instead of the oxygen evolution reaction (OER) typical in...    

    

* A Soft Molecular Single-Source Precursor Approach to Nanostructured Co9S8 (Pre)Catalyst for Efficient Water Oxidation and Biomass Valorization  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403201437
:TOPICS: Formation and Properties of Nanocrystals and Nanostructures, Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05436a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403201437"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403201437"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403201437"))][Get cited by]]

OpenAlex: https://openalex.org/W4403201437 (Open access: True)
    
[[https://openalex.org/A5061948626][Basundhara Dasgupta]], [[https://openalex.org/A5074953046][Suptish Ghosh]], [[https://openalex.org/A5040951340][Carsten Walter]], [[https://openalex.org/A5107404671][Markus Stefan Budde]], [[https://openalex.org/A5107817472][Georg J. Marquardt]], [[https://openalex.org/A5100420388][Hong Chen]], [[https://openalex.org/A5107817473][Markus G. M. Breithaupt]], [[https://openalex.org/A5102866880][Taner Yılmaz]], [[https://openalex.org/A5107817474][Christoph Garmatter]], [[https://openalex.org/A5080595139][Tansir Ahamad]], [[https://openalex.org/A5046252920][Ingo Zebger]], [[https://openalex.org/A5051647346][Matthias Drieß]], [[https://openalex.org/A5009720807][Prashanth W. Menezes]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta05436a 
     
The molecular single-source precursor (SSP) route emerges as a promising avenue for synthesizing highly efficient electro(pre)catalysts tailored for both oxygen evolution (OER) and organic electrooxidation reactions. This study introduces a...    

    

* Mild and rapid construction of Ti electrodes for efficient and corrosion-resistant oxidative catalysis at industrial-grade intensity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403144529
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.10.010")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403144529"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403144529"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403144529"))][Get cited by]]

OpenAlex: https://openalex.org/W4403144529 (Open access: False)
    
[[https://openalex.org/A5084804962][Rui Xiao]], [[https://openalex.org/A5065847227][Ding‐Kun Ji]], [[https://openalex.org/A5102649014][Liugang Wu]], [[https://openalex.org/A5102699034][Ziyan Fang]], [[https://openalex.org/A5101581701][Yanhui Guo]], [[https://openalex.org/A5009156159][Weiju Hao]], Journal of Colloid and Interface Science. 679(None)] 2024. https://doi.org/10.1016/j.jcis.2024.10.010 
     
The development of cost-effective and corrosion-resistant catalytic electrodes for chlorine/oxygen evolution reaction (CER/OER) in large-scale industrial applications is a significant challenge. Herein, the sol-gel method is employed to achieve a uniform coating of ruthenium (Ru) doping copper (Cu) on titanium sheet (Ru + 20 %Cu@Ti), and the highly efficient industrial grade stable Ti dimensional stable anode can be quickly constructed at 723.15 K for 2 h. Cu doping reduces the vacancy formation energy of surface oxygen, promotes additional lattice oxygen vacancy assisted hydrolysis dissociation pathway, improves the selectivity and specific activity of CER at high concentration doping, and reduces the binding energy of OER intermediates (e.g., *OH, *O, and *OOH) at adjacent Ru active sites. The overpotentials require to reach the current density of 10 mA cm    

    

* The Construction of Face-to-Face Combination between NiFe-layered Double Hydroxide Nanosheets and Monolayer rGO for Efficient Water Splitting and Oxygen Reduction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403243018
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-10-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c10721")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403243018"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403243018"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403243018"))][Get cited by]]

OpenAlex: https://openalex.org/W4403243018 (Open access: False)
    
[[https://openalex.org/A5072624360][Daoxin Liu]], [[https://openalex.org/A5100397653][Yang Yang]], [[https://openalex.org/A5011074259][Bing Xue]], [[https://openalex.org/A5100640211][Dongxu Zhang]], [[https://openalex.org/A5014094513][Fangfei Li]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c10721 
     
Developing cost-effective and efficient electrocatalysts is essential for advancing a green energy future. Herein, a NiFe-layered double hydroxide loaded on reduced graphene oxide (NiFe-LDHs@rGO) hybrid was synthesized using a straightforward three-step process involving exfoliation tearing, electrostatic self-assembly, and chemical reduction. The face-to-face packing and ultrathin exfoliation enable strong heterogeneous interactions, fully harnessing the potential of these complementary two-dimensional counterparts. Consequently, the resultant catalyst displays outstanding oxygen evolution reaction (OER) catalytic activity and stability, whose overpotential is as low as 241 mV at 30 mA cm    

    

* Optimizing NiFe-Modified Graphite for Enhanced Catalytic Performance in Alkaline Water Electrolysis: Influence of Substrate Geometry and Catalyst Loading  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403218313
:TOPICS: Electrocatalysis for Energy Conversion, Lithium-ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29194755")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403218313"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403218313"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403218313"))][Get cited by]]

OpenAlex: https://openalex.org/W4403218313 (Open access: True)
    
[[https://openalex.org/A5024905549][Mateusz Kuczyński]], [[https://openalex.org/A5033031053][Tomasz Mikołajczyk]], [[https://openalex.org/A5042738896][Bogusław Pierożyński]], [[https://openalex.org/A5045591954][Jakub Karczewski]], Molecules. 29(19)] 2024. https://doi.org/10.3390/molecules29194755 
     
The oxygen evolution reaction (OER) and the hydrogen evolution reaction (HER) are critical processes in water splitting, yet achieving efficient performance with minimal overpotential remains a significant challenge. Although NiFe-based catalysts are widely studied, their performance can be further enhanced by optimizing the interaction between the catalyst and the substrate. Here, we present a detailed investigation of NiFe-modified graphite electrodes, comparing the effects of compressed and expanded graphite substrates on catalytic performance. Our study reveals that substrate geometry plays a pivotal role in catalyst distribution and activity, with expanded graphite facilitating more effective electron transfer and active site utilization. Additionally, we observe that increasing the NiFe loading leads to only modest gains in performance, due to catalyst agglomeration at higher loadings. The optimized NiFe–graphite composites exhibit superior stability and catalytic activity, achieving lower overpotentials and higher current densities, making them promising candidates for sustainable hydrogen production via alkaline electrolysis.    

    

* High‐Entropy Ag‐Ru‐based Electrocatalysts with Dual‐Active‐Center for Highly Stable Ultra‐Low‐Temperature Zinc‐Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403165108
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202415216")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403165108"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403165108"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403165108"))][Get cited by]]

OpenAlex: https://openalex.org/W4403165108 (Open access: True)
    
[[https://openalex.org/A5034351888][Ziming Qiu]], [[https://openalex.org/A5100724115][Xiaotian Guo]], [[https://openalex.org/A5076507725][Shuai Cao]], [[https://openalex.org/A5060756190][Meng Du]], [[https://openalex.org/A5060311561][Qinchao Wang]], [[https://openalex.org/A5008846267][Yecan Pi]], [[https://openalex.org/A5100408029][Bo Wang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202415216  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/ange.202415216][pdf]])
     
The development of advanced bifunctional catalysts for oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) is significant for rechargeable zinc‐air batteries (ZABs). Herein, a unique dual active center alloying strategy is proposed to achieve the efficient bifunctional oxygen catalysis, and the high entropy effect is further exploited to modulate the structure and performance of the catalysts. The MOF‐assisted pyrolysis‐replacement‐alloying method was employed to construct the CoCuFeAgRu high‐entropy alloy (HEA), which are uniformly anchored in porous nitrogen‐doped carbon nanosheets. Notably, the obtained HEA catalyst exhibits excellent catalytic performance for both ORR and OER, and a peak power density of 136. 53 mW cm‐2 and an energy density of 987.9 mAh gZn‐1, surpassing the most of the previously reported bifunctional oxygen electrocatalysts. Moreover, the assembled flexible rechargeable ZAB enables excellent performance even at the ultralow temperature of ‐40°C, with an energy density of 601.6 mAh gZn‐1 and remarkable cycling stability up to 1,650 hours. Combined experimental and theoretical calculation results reveal that the excellent bifunctional catalytic activity of the HEA catalyst originated from the synergistic effect of the Ag and Ru dual active centers, and the optimization of the electronic structure by alloying effect.    

    

* All‐in‐One Polymer Gel Electrolyte towards High‐Efficiency and Stable Fiber Zinc‐Air Battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403202689
:TOPICS: Aqueous Zinc-Ion Battery Technology, Conducting Polymer Research, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202414772")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403202689"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403202689"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403202689"))][Get cited by]]

OpenAlex: https://openalex.org/W4403202689 (Open access: True)
    
[[https://openalex.org/A5017746300][Zhe Yang]], [[https://openalex.org/A5029416027][Pengzhou Li]], [[https://openalex.org/A5100343408][Jiaxin Li]], [[https://openalex.org/A5030247809][Chuanfa Li]], [[https://openalex.org/A5100415543][Yanan Zhang]], [[https://openalex.org/A5008540970][Taoyi Kong]], [[https://openalex.org/A5079786615][Meng Liao]], [[https://openalex.org/A5101199963][Tianbing Song]], [[https://openalex.org/A5101519524][Jinyan Li]], [[https://openalex.org/A5100716211][Peiyu Liu]], [[https://openalex.org/A5091309632][Siwei Cao]], [[https://openalex.org/A5100764817][Yonggang Wang]], [[https://openalex.org/A5080568430][Peining Chen]], [[https://openalex.org/A5023035506][Huisheng Peng]], [[https://openalex.org/A5100643440][Bingjie Wang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202414772  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/anie.202414772][pdf]])
     
Fiber zinc‐air batteries are explored as promising power systems for wearable and portable electronic devices due to their intrinsic safety and the use of ambient oxygen as cathode material. However, challenges such as limited zinc anode reversibility and sluggish cathode reaction kinetics result in poor cycling stability and low energy efficiency. To address these challenges, we design a polydopamine‐based all‐in‐one gel electrolyte (PAGE) that simultaneously regulates the reversibility of zinc anodes and the kinetics of air cathodes through polydopamine interfacial and redox chemistry, respectively. The intrinsic catechol and carboxylate groups in PAGE regulate the transport and solvation structure of Zn2+, facilitating dendrite‐free zinc deposition with a lamellar stacking morphology. Additionally, the oxidation of redox‐active catechol groups in PAGE replaces the sluggish oxygen evolution reaction on the air cathode and reduces the energy barrier for charging, enabling fiber zinc‐air batteries to achieve a significantly improved energy efficiency of 95% and a longer lifespan of 40 hours. Further integration into self‐powered electronic textiles underscores its potential for next‐generation wearable systems.    

    

* All‐in‐One Polymer Gel Electrolyte towards High‐Efficiency and Stable Fiber Zinc‐Air Battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403202690
:TOPICS: Aqueous Zinc-Ion Battery Technology, Lithium Battery Technologies, Conducting Polymer Research
:PUBLICATION_DATE: 2024-10-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202414772")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403202690"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403202690"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403202690"))][Get cited by]]

OpenAlex: https://openalex.org/W4403202690 (Open access: False)
    
[[https://openalex.org/A5082292343][Zhe Yang]], [[https://openalex.org/A5029416027][Pengzhou Li]], [[https://openalex.org/A5100343408][Jiaxin Li]], [[https://openalex.org/A5030247809][Chuanfa Li]], [[https://openalex.org/A5073791430][Yanan Zhang]], [[https://openalex.org/A5008540970][Taoyi Kong]], [[https://openalex.org/A5079786615][Meng Liao]], [[https://openalex.org/A5101199963][Tianbing Song]], [[https://openalex.org/A5101519524][Jinyan Li]], [[https://openalex.org/A5100716216][Peiyu Liu]], [[https://openalex.org/A5091309632][Siwei Cao]], [[https://openalex.org/A5106079885][Yonggang Wang]], [[https://openalex.org/A5080568430][Peining Chen]], [[https://openalex.org/A5023035506][Huisheng Peng]], [[https://openalex.org/A5100643441][Bingjie Wang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202414772 
     
Fiber zinc‐air batteries are explored as promising power systems for wearable and portable electronic devices due to their intrinsic safety and the use of ambient oxygen as cathode material. However, challenges such as limited zinc anode reversibility and sluggish cathode reaction kinetics result in poor cycling stability and low energy efficiency. To address these challenges, we design a polydopamine‐based all‐in‐one gel electrolyte (PAGE) that simultaneously regulates the reversibility of zinc anodes and the kinetics of air cathodes through polydopamine interfacial and redox chemistry, respectively. The intrinsic catechol and carboxylate groups in PAGE regulate the transport and solvation structure of Zn2+, facilitating dendrite‐free zinc deposition with a lamellar stacking morphology. Additionally, the oxidation of redox‐active catechol groups in PAGE replaces the sluggish oxygen evolution reaction on the air cathode and reduces the energy barrier for charging, enabling fiber zinc‐air batteries to achieve a significantly improved energy efficiency of 95% and a longer lifespan of 40 hours. Further integration into self‐powered electronic textiles underscores its potential for next‐generation wearable systems.    

    

* Synergistic Vertical Graphene‐Exsolved Perovskite to Boost Reaction Kinetics for Flexible Zinc–Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403214087
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202415351")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403214087"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403214087"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403214087"))][Get cited by]]

OpenAlex: https://openalex.org/W4403214087 (Open access: False)
    
[[https://openalex.org/A5055916949][Juwei Du]], [[https://openalex.org/A5100331347][Nan Zhang]], [[https://openalex.org/A5101953638][Wenyu Zhang]], [[https://openalex.org/A5101755876][Xiaojun Shi]], [[https://openalex.org/A5102758524][Yansheng Gong]], [[https://openalex.org/A5100431108][Rui Wang]], [[https://openalex.org/A5059823291][Huanwen Wang]], [[https://openalex.org/A5025396304][Jun Jin]], [[https://openalex.org/A5100414931][Ling Zhao]], [[https://openalex.org/A5026277955][Beibei He]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202415351 
     
Abstract Zinc–air batteries (ZABs) hold significant promise for flexible electronics due to their high energy density and low cost. However, their practical application is hindered by the sluggish kinetics of the oxygen evolution and oxygen reduction reactions (OER/ORR). This study highlights a novel design of vertical graphene arrays (VGs) anchored on PrBa 0.5 Sr 0.5 Co 1.8 Ru 0.2 O 5+δ (PBSCRu) perovskite nanofibers, fabricated via plasma‐enhanced chemical vapor deposition. Notably, the VG growth induces the exsolution of Co nanoparticles from the PBSCRu perovskite, resulting in a unique PBSCRu‐Co‐VG heterostructure. Theoretical calculations demonstrate that constructing PBSCRu‐Co‐VG heterojunction regulates interfacial electronic redistribution, thereby lowering energy barriers for both OER and ORR. As a result, the PBSCRu@VG‐5 electrocatalyst exhibits superior stability and higher peak power density in both liquid and flexible solid‐state ZABs compared to the pristine PBSCRu electrocatalyst. This protocol advances the integration of synergetic perovskite/metal/graphene composites, offering considerable potential for next‐generation energy conversion technologies.    

    

* Renaissance of Chlorine Evolution Reaction: Emerging Theory and Catalytic Materials  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403191457
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202417293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403191457"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403191457"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403191457"))][Get cited by]]

OpenAlex: https://openalex.org/W4403191457 (Open access: True)
    
[[https://openalex.org/A5047777020][Jinjong Kim]], [[https://openalex.org/A5101510923][Muhammad Usama]], [[https://openalex.org/A5004991965][Kai S. Exner]], [[https://openalex.org/A5049712479][Sang Hoon Joo]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202417293  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/anie.202417293][pdf]])
     
Chlorine (Cl2) is one of the most important commodity chemicals that has found widespread utility in chemical industry. Most Cl2 is currently produced via the chlorine evolution reaction (CER) at the anode of chlor–alkali electrolyzers, for which precious group‐metal‐based mixed metal oxides (MMOs) have been used for more than half a century. However, MMOs suffer from the use of platinum‐group metals, which are costly and scarce, and the selectivity issue arises from the parasitic oxygen evolution reaction. Over the last decade, the field of CER catalysis has seen dramatic advances in both the theory and discovery of new catalysts. Theoretical approaches have enabled a fundamental understanding of CER mechanisms and provided catalyst design principles. The exploration of new materials has led to the discovery of CER catalysts other than MMOs, including non‐PGM‐based oxides, atomically dispersed single‐site catalysts, and organic molecules, with some of which following novel reaction pathways. This minireview provides an overview of the recent advances in CER electrocatalyst research and suggests future directions for this revitalized field.    

    

* Renaissance of Chlorine Evolution Reaction: Emerging Theory and Catalytic Materials  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403192334
:TOPICS: Biohydrometallurgical Processes for Metal Extraction, Organic Chemistry and Catalysis
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202417293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403192334"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403192334"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403192334"))][Get cited by]]

OpenAlex: https://openalex.org/W4403192334 (Open access: False)
    
[[https://openalex.org/A5047777020][Jinjong Kim]], [[https://openalex.org/A5101510923][Muhammad Usama]], [[https://openalex.org/A5004991965][Kai S. Exner]], [[https://openalex.org/A5049712479][Sang Hoon Joo]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202417293 
     
Chlorine (Cl2) is one of the most important commodity chemicals that has found widespread utility in chemical industry. Most Cl2 is currently produced via the chlorine evolution reaction (CER) at the anode of chlor–alkali electrolyzers, for which precious group‐metal‐based mixed metal oxides (MMOs) have been used for more than half a century. However, MMOs suffer from the use of platinum‐group metals, which are costly and scarce, and the selectivity issue arises from the parasitic oxygen evolution reaction. Over the last decade, the field of CER catalysis has seen dramatic advances in both the theory and discovery of new catalysts. Theoretical approaches have enabled a fundamental understanding of CER mechanisms and provided catalyst design principles. The exploration of new materials has led to the discovery of CER catalysts other than MMOs, including non‐PGM‐based oxides, atomically dispersed single‐site catalysts, and organic molecules, with some of which following novel reaction pathways. This minireview provides an overview of the recent advances in CER electrocatalyst research and suggests future directions for this revitalized field.    

    

* Innovative Nanoarchitectures: CuO:Er2O3 Synergy for Enhanced Performance in Energy Storage and Generation Applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403173993
:TOPICS: Materials for Electrochemical Supercapacitors, Formation and Properties of Nanocrystals and Nanostructures, Advanced Materials for Smart Windows
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aoc.7795")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403173993"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403173993"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403173993"))][Get cited by]]

OpenAlex: https://openalex.org/W4403173993 (Open access: False)
    
[[https://openalex.org/A5027251549][Sundus Azhar]], [[https://openalex.org/A5073226453][Khuram Shahzad Ahmad]], [[https://openalex.org/A5053541941][Isaac Abrahams]], [[https://openalex.org/A5081515848][Tenzin Ingsel]], [[https://openalex.org/A5091126286][Ram K. Gupta]], [[https://openalex.org/A5070109697][Essam A. Al‐Ammar]], [[https://openalex.org/A5066445487][Ghulam Abbas Ashraf]], [[https://openalex.org/A5068061341][Mahwash Mahar Gul]], Applied Organometallic Chemistry. None(None)] 2024. https://doi.org/10.1002/aoc.7795 
     
ABSTRACT In this study, we have synthesized facile Cu‐based CuO:Er 2 O 3 nanoelectrode material for energy storage and generation. CuO:Er 2 O 3 nanomaterial was synthesized employing phyto‐extract of Amaranthus viridis L. (AVL) as stabilizing and reducing agents. Spherical‐shaped CuO:Er 2 O 3 nanomaterial was initially employed to study supercapacitor behavior. The specific capacitance of 82.25 F/g was found at 0.5 A/g by galvanostatic charge–discharge, whereas the value of 319 F/g was achieved at 2 mV/s by cyclic voltammetry (CV) measurements. Furthermore, CuO:Er 2 O 3 electrode was investigated for water splitting energy generation potential and revealed an overpotential value of 323 mV at 10 mA/cm 2 for hydrogen evolution reaction (HER). However, for the oxygen evolution reaction (OER), an overpotential value of 370 mV was found. The electrochemical impedance analysis revealed the faster flow of electrons and ions, suggesting great conductivity and lower resistance of the fabricated electrode. Thus, current electrochemical results are proposing CuO:Er 2 O 3 as an competent electrode for overall energy‐generating as well as storage applications.    

    

* NixB/Mo0.8B3 Nanorods Encapsulated by a Boron‐Rich Amorphous Layer for Universal pH Water Splitting at the Ampere Level  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403158348
:TOPICS: Electrocatalysis for Energy Conversion, Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202402866")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403158348"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403158348"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403158348"))][Get cited by]]

OpenAlex: https://openalex.org/W4403158348 (Open access: True)
    
[[https://openalex.org/A5022259781][Madiha Rafiq]], [[https://openalex.org/A5086445869][Karim Harrath]], [[https://openalex.org/A5049798297][Minyan Feng]], [[https://openalex.org/A5100454297][Jia Li]], [[https://openalex.org/A5084311563][Abebe Reda Woldu]], [[https://openalex.org/A5082656873][Paul K. Chu]], [[https://openalex.org/A5014924091][Liangsheng Hu]], [[https://openalex.org/A5006499989][Fushen Lu]], [[https://openalex.org/A5022148039][Xiangdong Yao]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202402866  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/aenm.202402866][pdf]])
     
Abstract Heterostructured interfaces are crucial to electrocatalysts for water splitting. Herein, coral‐like multiheterostructured Ni x B/Mo 0.8 B 3 (NMB) nanorods encapsulated by a boron‐rich amorphous layer are prepared for water splitting. Density‐functional theory (DFT) calculations indicate that the NMB interface adjusts the d ‐band center and electronic structure of the molybdenum sites. Owing to the strong electronic coupling between Ni, Mo, and B at the heterojunction, large number of exposed catalytic active sites, as well as the special hydrophilic characteristics endowed by the surrounding amorphous layer, the NMB catalyst exhibits remarkable universal‐pH hydrogen evolution reaction (HER) activity with low overpotentials ( η ) of 15, 26, and 83 mV to deliver 10 mA cm −2 in basic, acid, and neutral media, respectively, and outstanding oxygen evolution reaction (OER) characteristics in the basic medium with η 10 and η 500 of 170 and 420 mV, respectively. The unique self‐supporting 3D hierarchical interconnected structure facilitates mass transport thus leading to high mechanical stability for 450 and 200 h in HER and OER at ≈1000 mA cm −2 . More importantly, the NMB exhibits excellent performance toward overall‐water electrolysis as a bifunctional catalyst with ultralow cell voltages of 1.45/1.56/1.85 V @ 10/100/1000 mA cm −2 , demonstrating the large potential in industrial water splitting applications.    

    

* Bioinspired synthesis of ZrO2‐Zr3Er4O12‐based mixed nanomaterial; characterization and analyzing its potential as an electrode material in energy‐based devices and its electrocatalytic property  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403213331
:TOPICS: Electrocatalysis for Energy Conversion, Lithium-ion Battery Technology, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/jccs.202400187")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403213331"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403213331"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403213331"))][Get cited by]]

OpenAlex: https://openalex.org/W4403213331 (Open access: False)
    
[[https://openalex.org/A5027251549][Sundus Azhar]], [[https://openalex.org/A5073226453][Khuram Shahzad Ahmad]], [[https://openalex.org/A5053541941][Isaac Abrahams]], [[https://openalex.org/A5081515848][Tenzin Ingsel]], [[https://openalex.org/A5091126286][Ram K. Gupta]], [[https://openalex.org/A5079370257][Dan Liu]], [[https://openalex.org/A5062023379][S. Noor Mohammad]], [[https://openalex.org/A5068061341][Mahwash Mahar Gul]], Journal of the Chinese Chemical Society. None(None)] 2024. https://doi.org/10.1002/jccs.202400187 
     
Abstract The sustainable and ecofriendly synthesis of transition metal oxide‐based nanomaterials has always been a matter of concern. In this study, a bioinspired synthesis route was adopted to synthesize ZrO 2 ‐Zr 3 Er 4 O 12 ‐based mixed nanomaterial using leaf extract of medicinal plant Amaranthus viridis as reducing and stabilizing agent in replacement of the obnoxious chemicals which are a great threat to the sustainable environment. The synthesized material revealed the spherical shaped morphology through scanning electron microscopy, whereas crystal size of 15.7 nm was observed through Xray‐diffraction, and band gap value of 2.7 eV was acquired using Tauc plot. Newly synthesized ZrO 2 ‐Zr 3 Er 4 O 12 nanocomposite was then investigated for its role as electrocatalyst in a generation of energy through the hydrogen evolution reaction and oxygen evolution reaction. The ZrO 2 ‐Zr 3 Er 4 O 12 ‐based electrocatalyst showed better potential for hydrogen evolution reaction measurements with the overpotential value of 242 mV. Furthermore, the notable capacitance value of 495.6 F/g was obtained through cyclic voltammetry for energy storage studies. The cyclic stability was also analyzed using linear sweep voltammetry and results showed promising stability for 2000 cycles. Consequently, the green and economical synthesis route as well as promising electrochemical behavior of ZrO 2 ‐Zr 3 Er 4 O 12 ‐based electrode make it feasible choice for large scale application.    

    

* A Review of Hydrogen Production via Seawater Electrolysis: Current Status and Challenges  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403136707
:TOPICS: Hydrogen Energy Systems and Technologies, Global Energy Transition and Fossil Fuel Depletion, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/catal14100691")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403136707"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403136707"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403136707"))][Get cited by]]

OpenAlex: https://openalex.org/W4403136707 (Open access: True)
    
[[https://openalex.org/A5048117304][Yi Xin Zhang]], [[https://openalex.org/A5101814743][Yang Yang]], [[https://openalex.org/A5008178617][Zhichuan Li]], [[https://openalex.org/A5101312013][Ende Yu]], [[https://openalex.org/A5047989511][H. J. Ye]], [[https://openalex.org/A5025746827][Zihang Li]], [[https://openalex.org/A5070940269][Margot Pellegrino]], [[https://openalex.org/A5052565332][Daojin Zhou]], [[https://openalex.org/A5100417003][Cheng Wang]], [[https://openalex.org/A5046700718][Qihao Sha]], [[https://openalex.org/A5042347465][Yun Kuang]], Catalysts. 14(10)] 2024. https://doi.org/10.3390/catal14100691 
     
Seawater electrolysis represents a promising green energy technology with significant potential for efficient energy conversion. This study provides an in-depth examination of the key scientific challenges inherent in the seawater-electrolysis process and their potential solutions. Initially, it analyzes the potential issues of precipitation and aggregation at the cathode during hydrogen evolution, proposing strategies such as self-cleaning cathodes and precipitate removal to ensure cathode stability in seawater electrolysis. Subsequently, it addresses the corrosion challenges faced by anode catalysts in seawater, introducing several anti-corrosion strategies to enhance anode stability, including substrate treatments such as sulfidation, phosphidation, selenidation, and LDH (layered double hydroxide) anion intercalation. Additionally, this study explores the role of regulating the electrode surface microenvironment and forming unique coordination environments for active atoms to enhance seawater electrolysis performance. Regulating the surface microenvironment provides a novel approach to mitigating seawater corrosion. Contrary to the traditional understanding that chloride ions accelerate anode corrosion, certain catalysts benefit from the unique coordination environment of chloride ions on the catalyst surface, potentially enhancing oxygen evolution reaction (OER) performance. Lastly, this study presents the latest advancements in the industrialization of seawater electrolysis, including the in situ electrolysis of undiluted seawater and the implementation of three-chamber dual anion membranes coupled with circulating electrolyte systems. The prospects of seawater electrolysis are also explored.    

    

* High‐Efficiency Photo‐Assisted Large Current‐Density Water Splitting with Mott‐Schottky Heterojunctions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403193807
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, DNA Nanotechnology and Bioanalytical Applications
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202415492")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403193807"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403193807"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403193807"))][Get cited by]]

OpenAlex: https://openalex.org/W4403193807 (Open access: False)
    
[[https://openalex.org/A5044465572][Minming Jiang]], [[https://openalex.org/A5103038896][Jiang Xu]], [[https://openalex.org/A5100459039][Yujie Chen]], [[https://openalex.org/A5101733772][Luqi Wang]], [[https://openalex.org/A5026716909][Paul Munroe]], [[https://openalex.org/A5056283665][Zonghan Xie]], [[https://openalex.org/A5034879972][Shengjie Peng]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202415492 
     
The development of bifunctional photogenerated carrier‐assisted electrocatalytic (PCA‐EC) electrodes that operate with stability at large current‐density remains a significant challenge. Herein, we demonstrate a simple sputtering‐deposition process to synthesize a novel MnWO4/FeCoNi Mott‐Schottky heterojunction coating and deposit it on a pure Ti substrate to prepare high‐performance PCA‐EC electrodes, which exhibits enhanced light absorption range/intensity and rapidly separated photogenerated electron‐hole pairs. This design allows photogenerated electrons to directly participate in the hydrogen evolution reaction (HER), while the strong oxidation of photogenerated holes significantly reduces the defect formation energy of active metals, thereby facilitating the rapid reconstruction of highly active Ni(FeCo)OOH/MnOOH species for the oxygen evolution reaction (OER). As expected, the as‐prepared electrode demonstrates the overpotentials of 64 mV for the HER and 204 mV for the OER at 10 mA cm−2 under illumination. Benefiting from the stable interface with Fe/Co/Ni‐O‐Mn/W bonding units, the dual‐electrode photoassisted electrolytic cell achieves long‐term stability at current densities of 500 and 1000 mA cm−2. This work provides detailed insights into the enhancement mechanism of PCA‐EC and contributes to the development of photo‐assisted water splitting electrodes for large current‐density applications.    

    

* Solvent-free Synthesis of Transition Metals Nanoparticles Decorated Foamy Flakes-like Nitrogen-doped Carbon as Bifunctional-catalyst for High-performance Rechargeable Zn-air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403218810
:TOPICS: Materials for Electrochemical Supercapacitors, Zinc Oxide Nanostructures, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2023-09-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5614/j.eng.technol.sci.2024.56.5.10")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403218810"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403218810"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403218810"))][Get cited by]]

OpenAlex: https://openalex.org/W4403218810 (Open access: True)
    
[[https://openalex.org/A5092405935][Pilar Bela Persada]], [[https://openalex.org/A5103256889][Davin Adinata Tan]], [[https://openalex.org/A5092686145][Rachendra Akmalia]], [[https://openalex.org/A5086766574][Yuyun Irmawati]], [[https://openalex.org/A5009803366][Afriyanti Sumboja]], Journal of Engineering and Technological Sciences. 56(5)] 2023. https://doi.org/10.5614/j.eng.technol.sci.2024.56.5.10 
     
Transition metal-nitrogen-carbon (M/NC) demonstrates a promising effective electrocatalyst for enhancing oxygen evolution/reduction reactions (OER/ORR). However, synthesizing these catalysts is often complex, time-consuming, and involves hazardous solvents while producing a low yield. This work introduces a versatile, eco-friendly, and straightforward solvent-free method to produce M/NC (M = Co, Ni, and Fe) catalysts in ~3 h using a glucose, urea, and metal nitrate hydrate mixture. The high-yield M/NC catalysts exhibit a porous architecture and uniform distribution of metal nanoparticles within a foaming flakes-like nitrogen-doped carbon matrix. The metal nanoparticles are wrapped with protective nitrogen-doped carbon layers, producing stable active sites. Possessing these unique properties, the obtained M/NC catalysts show high-performance and stable bifunctional OER/ORR. As the best result, Co/NC presents an OER/ORR potential difference (ΔE) of 0.78 V and retains 96% and 89% of its OER and ORR performance after a 10 h stability test. In practical application, the Co/NC-based Zn-air battery depicts a high power density of 184 mW cm−2 and good rechargeability of up to 120 h, outperforming the battery with noble metal-based catalysts. This work sheds light on the versatile, eco-friendly, and scalable synthesis of M/NC catalysts while presenting a strategy to accelerate the generation of inexpensive and highly effective bifunctional OER/ORR catalysts.    

    

* Composites Based on Electrodeposited WO3 and TiO2 Nanoparticles for Photoelectrochemical Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403217581
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Photocatalysis and Solar Energy Conversion, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/ma17194914")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403217581"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403217581"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403217581"))][Get cited by]]

OpenAlex: https://openalex.org/W4403217581 (Open access: True)
    
[[https://openalex.org/A5028883060][Ramūnas Levinas]], [[https://openalex.org/A5026441168][Elizabeth J. Podlaha]], [[https://openalex.org/A5049880114][Н. Цынцару]], [[https://openalex.org/A5073342220][H. Cesiulis]], Materials. 17(19)] 2024. https://doi.org/10.3390/ma17194914 
     
Photoelectrochemically active WO3 films were fabricated by electrodeposition from an acidic (pH 2), hydrogen-peroxide-containing electrolyte at −0.5 V vs. SCE. WO3-TiO2 composites were then synthesized under the same conditions, but with 0.2 g/L of anatase TiO2 nanoparticles (⌀ 36 nm), mechanically suspended in the solution by stirring. After synthesis, the films were annealed at 400 °C. Structural characterization by XRD showed that the WO3 films exhibit the crystalline structure of a non-stoichiometric hydrate, whereas, in WO3-TiO2, the WO3 phase was monoclinic. The oxidation of tungsten, as revealed by XPS, was W6+ for both materials. Ti was found to exist mainly as Ti4+ in the composite, with a weak Ti3+ signal. The efficiency of the WO3 films and composites as an oxygen evolution reaction (OER) photo-electrocatalyst was examined. The composite would generate approximately three times larger steady-state photocurrents at 1.2 V vs. SCE in a neutral 0.5 M Na2SO4 electrolyte compared to WO3 alone. The surface recombination of photogenerated electron–hole pairs was characterized by intensity-modulated photocurrent spectroscopy (IMPS). Photogenerated charge transfer efficiencies were calculated from the spectra, and at 1.2 V vs. SCE, were 86.6% for WO3 and 62% for WO3-TiO2. Therefore, the composite films suffered from relatively more surface recombination but generated larger photocurrents, which resulted in overall improved photoactivity.    

    

* Green Hydrogen, an Alternative Renewable Energy Source: Based on Solar-Energy-Driven Water-Splitting Technology  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403139835
:TOPICS: Hydrogen Energy Systems and Technologies, Indoor Air Pollution in Developing Countries
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.31674/book.2024ecc.12")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403139835"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403139835"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403139835"))][Get cited by]]

OpenAlex: https://openalex.org/W4403139835 (Open access: False)
    
[[https://openalex.org/A5103053734][Amit Kumar Dutta]], No host. None(None)] 2024. https://doi.org/10.31674/book.2024ecc.12 
     
The need for zero-emission, eco-friendly hydrogen fuel has increased enormously over the years due to adverse impacts on the environment caused by conventional fuels such as natural gas, coal, oil, fossil fuels, bio-mass etc. This chapter reports the safest and most efficient route for hydrogen-fuel production based on solar-energy-driven watersplitting technology over a heterogeneous photo-catalyst. Several challenges have been made for the extension of photo-catalyst, based on nano-sized semiconducting materials such as binary and ternary metal chalcogenides nano-materials, CuS, CdS, Fe3O4, CuInO2, CuInS2, CuGaS2 and their composites with hetero-nanostructure. When the nano-structures have the ability to absorb solar-light-energy (having a narrow band gap energy < 3.6 eV), i.e., to utilise the most of the solar-spectrum, the photo-catalytic performances have increased much more. The catalytic performances of the semiconductors have also been improved for enhanced hydrogen production using nano-engineering technology, i.e., different modifications to the nano-catalyst surface and electronic energy structure, so that they can act as an efficient photo-catalyst for solar-energy driven water electrolysis to produce enhanced large-scale hydrogen-fuel. The possible mechanism of the photo-chemical processes has also been explored through the formation of free electron-hole pair (e- /h+) on suitable heterogeneous catalyst’s surface and controlling the kinetics of hydrogen evolution reaction and oxygen evolution reaction. How the proposed nano-catalyst materials have been designed to optimize solar-to-hydrogen conversion efficiency, improve the rate of hydrogen production and commercialized for the sake of society has been deliberated.    

    

* Magnetron technology for manufacturing electrodes of electrolysers with a proton-exchange membrane  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403121643
:TOPICS: Hydrogen Energy Systems and Technologies, Materials and Methods for Hydrogen Storage, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.31857/s0424857024030071")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403121643"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403121643"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403121643"))][Get cited by]]

OpenAlex: https://openalex.org/W4403121643 (Open access: False)
    
[[https://openalex.org/A5054153486][С. И. Нефедкин]], [[https://openalex.org/A5032182812][A. V. Ryabukhin]], [[https://openalex.org/A5096943896][V. E. Eletskikh]], [[https://openalex.org/A5002009766][Р. Г. Болдин]], [[https://openalex.org/A5096971282][V. D. Mikhnevich]], [[https://openalex.org/A5008381056][М. А. Климова]], Электрохимия. 60(3)] 2024. https://doi.org/10.31857/s0424857024030071 
     
The results of the development and study of catalysts for the anode of water decomposition electrolyzers with a proton exchange membrane are presented. To deposit catalytic layers on a titanium carrier, the magnetron method of sputtering composite targets in a vacuum was used. Iridium and ruthenium were used as the main catalyst, and molybdenum, chromium, and titanium were used as functional additives. The electrochemical and structural characteristics of catalytic coatings have been studied. Using voltammetry methods, cyclic current-voltage and anodic characteristics of catalytic compositions were obtained, including at different temperatures of subsequent heat treatment in air, as well as at different measurement temperatures. The Tafel slopes of the current-voltage characteristics of the composite anodes, as well as the currents at a potential of 1.55 V (RHE), were determined. It has been shown that the minimum slopes were obtained for the Ir–Ru–Mo–Ti catalytic composition (b = 40–63 mV/dec), and the maximum currents for the Ir–Mo–Cr catalytic composition (i = 100–110 mA/cm2 at E = 1.55 V (RHE)). It has been shown that the magnitude of CV adsorption currents in the anodic potential region correlates with the coefficient b of the Tafel equation E–lgi and determines the number of catalytic centers for the deprotonization stage of the oxygen evolution reaction. However, the activity of the catalyst in the OER is determined not only by the number of such centers, but mainly by the functional features of the catalyst itself, i.e., the composition of the catalyst and the conditions for its preparation (including the temperature of subsequent heat treatment of the catalyst in air). Catalytic compositions based on iridium with additions of molybdenum and chromium have higher activity in OER. Structural studies have shown that during magnetron sputtering of composite targets, even with small catalyst loadings, dispersed structures are formed, which on real porous titanium anodes should form on the front surface with a higher catalyst content.    

    

* The Inclusion Characteristics and Mechanical Properties of M2 High-Speed Steel Treated with a Vacuum Carbon Deoxidation Process  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403217185
:TOPICS: Effects of Cryogenic Treatment on Material Properties, Synthesis and Properties of Cemented Carbides, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/met14101146")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403217185"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403217185"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403217185"))][Get cited by]]

OpenAlex: https://openalex.org/W4403217185 (Open access: True)
    
[[https://openalex.org/A5073745338][Yuheng Dai]], [[https://openalex.org/A5081285203][Tinghui Man]], [[https://openalex.org/A5100664124][Zhongliang Wang]], [[https://openalex.org/A5060338438][Yu Liu]], [[https://openalex.org/A5100751025][Yan-ping Bao]], [[https://openalex.org/A5101651832][Xicheng Wei]], Metals. 14(10)] 2024. https://doi.org/10.3390/met14101146 
     
The oxygen content of M2 high-speed steel has not been intentionally controlled in industrial production through secondary refinement in vacuum furnaces. However, a lower oxygen content has a significant effect on the cleanliness, toughness, and addition of rare-earth elements to M2 high-speed steel. The changes in total oxygen content controlled by vacuum carbon deoxidation (VCD) treatment and inclusion evolution were investigated in M2 high-speed steel to understand the effects of carbon on dissolved oxygen and oxides in the carbon–oxygen (C-O) reaction process. Furthermore, the microstructure and properties of M2 high-speed steel caused by vacuum insulation and the role of reducing oxygen content in rare-earth alloying were briefly demonstrated. The results showed that the [O%] decreased from 30 ppm to 3 ppm in a vacuum at holding times above 25 min through the C-O reaction, leading to an inclusion reduction of approximately 70%. In the case of [O%] = 3 ppm in M2 high-speed steel, the addition of rare-earth elements has a greater effect on the inclusion characteristics. Lowering the oxygen content of M2 high-speed steel improves cleanliness and plays a significant role in rare-earth alloying.    

    

* Application of the MELTS program to the fractional crystallization of low-alumina alkaline magma on Jeju Volcanic Island, Korea  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403148993
:TOPICS: Tectonic and Geochronological Evolution of Orogens, Applications of Clay Nanotubes in Various Fields, Machine Learning for Mineral Prospectivity Mapping
:PUBLICATION_DATE: 2024-10-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1186/s40562-024-00360-8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403148993"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403148993"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403148993"))][Get cited by]]

OpenAlex: https://openalex.org/W4403148993 (Open access: True)
    
[[https://openalex.org/A5033866191][Huy Lê]], [[https://openalex.org/A5064831542][Cheolwoo Chang]], [[https://openalex.org/A5069394933][Sung-Hyo Yun]], Geoscience Letters. 11(1)] 2024. https://doi.org/10.1186/s40562-024-00360-8 
     
Abstract Jeju Volcanic Island is the largest island in South Korea and is considered a continental shelf intraplate volcanic island. In this study, MELTS, a powerful program for modeling magmatic evolution processes, was applied to simulate the fractional crystallization process of the low-alumina alkaline volcanic rock suite on Jeju Island. MELTS modeling was conducted at many isobaric pressures ranging from 2.0 GPa to 0.1 GPa, different oxygen fugacities (fO 2 ) from FMQ-3 to FMQ + 3, and different H 2 O contents. The results demonstrate that the most suitable fractionation model for the Jeju low-alumina alkaline magma involves a pressure of 0.2 GPa to 0.1 GPa and an oxygen fugacity close to the FMQ buffer. Additionally, an H 2 O content of 0.5 wt.% is the most consistent with the evolution trend and mineral composition of the natural rock suite on Jeju Island. Although MELTS possesses several limitations in terms of the stability of calibration, such as spinel overestimation and a lack of experiments on hydrous minerals (which should be improved), MELTS performs well in terms of temperature and pressure prediction and in terms of the assessment of other factors of the fractional crystallization process on Jeju Island. Consequently, to evaluate a magmatic process in a particular region, MELTS should be combined with other analyses and not relied upon independently.    

    

* Unveiling high-temperature stability and growth dynamics of CVD-SiOC coatings across different deposition conditions and environments  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403175808
:TOPICS: Mechanical Properties of Thin Film Coatings, Diamond Nanotechnology and Applications, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/2053-1591/ad8411")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403175808"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403175808"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403175808"))][Get cited by]]

OpenAlex: https://openalex.org/W4403175808 (Open access: True)
    
[[https://openalex.org/A5032284545][Weiguo Jing]], [[https://openalex.org/A5090978455][Naeem ul Haq Tariq]], [[https://openalex.org/A5102627123][Wenkang Hou]], [[https://openalex.org/A5100509914][Tianying Xiong]], [[https://openalex.org/A5101195926][Mingqiang Tang]], Materials Research Express. None(None)] 2024. https://doi.org/10.1088/2053-1591/ad8411 
     
Abstract In this study, we systematically investigated the high-temperature protection performance and evolution behavior of three different SiOC coatings (1050SiOC, 1100SiOC, 1150SiOC) under different atmospheres. The coatings were prepared by the organometallic chemical vapor deposition (CVD) method and characterized using scanning electron microscopy (SEM), grazing incidence X-ray diffraction (GIXRD), X-ray photoelectron spectroscopy (XPS) techniques. It was found that the composition and microstructure of SiOC coatings, environmental atmosphere, and heat treatment temperature can affect the thermal stability and high-temperature reaction mechanism of SiOC coatings. Further, it was revealed that the three SiOC coatings only exhibit the same high-temperature evolution behavior and reaction mechanism in an air environment while exhibiting different high-temperature evolution behavior and reaction mechanisms in both an inert atmosphere and a reduced air atmosphere. Among the coatings prepared, the 1050SiOC coating demonstrated the highest on-set oxidation temperature under identical oxygen content conditions. This characteristic may contribute to the coating’s excellent resistance to high-temperature oxidation.&#xD;    

    

* Geography, altitude, agriculture and hypoxia  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403133408
:TOPICS: Plant Responses to Flooding Stress, Genetic and Physiological Adaptations to High-Altitude Environments
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/plphys/kiae535")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403133408"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403133408"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403133408"))][Get cited by]]

OpenAlex: https://openalex.org/W4403133408 (Open access: False)
    
[[https://openalex.org/A5033499276][Michael J. Holdsworth]], [[https://openalex.org/A5100722309][Huanhuan Liu]], [[https://openalex.org/A5035794310][Simone Castellana]], [[https://openalex.org/A5070670005][Mohamad Abbas]], [[https://openalex.org/A5101545916][Minjie Li]], [[https://openalex.org/A5029714534][Pierdomenico Perata]], PLANT PHYSIOLOGY. None(None)] 2024. https://doi.org/10.1093/plphys/kiae535 
     
Abstract Reduced oxygen availability (hypoxia) represents a key plant abiotic stress in natural and agricultural systems, but conversely it is also an important component of normal growth and development. We review recent advances that demonstrate how genetic adaptations associated with hypoxia impact the known plant oxygen sensing mechanism through the PLANT CYSTEINE OXIDASE (PCO) N-degron pathway. Only three protein substrates of this pathway have been identified, and all adaptations identified to date are associated with the most important of these, the group VII ETHYLENE RESPONSE FACTOR transcription factors (ERFVIIs). We discuss how geography, altitude, and agriculture have all shaped molecular responses to hypoxia, and how these responses have emerged at different taxonomic levels through the evolution of land plants. Understanding how ecological and agricultural genetic variation acts positively to enhance hypoxia tolerance will provide novel tools and concepts to improve the performance of crops in the face of increasing extreme flooding events.    

    

* Revealing Local Grain Boundary Chemistry and Correlating it with Local Mass Transport in Mixed‐Conducting Perovskite Electrodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403158504
:TOPICS: Emergent Phenomena at Oxide Interfaces, Solid Oxide Fuel Cells, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202404702")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403158504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403158504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403158504"))][Get cited by]]

OpenAlex: https://openalex.org/W4403158504 (Open access: True)
    
[[https://openalex.org/A5020317167][Zijie Sha]], [[https://openalex.org/A5058149016][James O. Douglas]], [[https://openalex.org/A5041824738][Lluís Yedra]], [[https://openalex.org/A5004733589][Ieuan D. Seymour]], [[https://openalex.org/A5029022628][Sònia Estradé]], [[https://openalex.org/A5045026109][F. Peiró]], [[https://openalex.org/A5042156783][Stephen J. Skinner]], [[https://openalex.org/A5011474977][John A. Kilner]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202404702 
     
Abstract Grain boundary (GB) mass transport, and chemistry exert a pronounced influence on both the performance and stability of electrodes for solid oxide electrochemical cells. Lanthanum strontium cobalt ferrite (LSCF6428) is applied as a model mixed ionic and electronic conducting (MIEC) perovskite oxide. The cation‐vacancy distribution at the GBs is studied at both single and multi‐grain scales using high‐resolution characterization techniques and computational approaches. The accumulation of oxygen vacancies () in the GB region, rather than necessarily at the GB core, results in an enhancement of the oxygen diffusivity by 3 – 4 orders of magnitude along the GBs ( D gb ). At 350 °C, the oxygen tracer diffusion coefficient ( D *) is measured as 2.5 × 10 −14 cm 2 s −1 . The D gb is determined to be 2.8 × 10 −10 cm 2 s −1 assuming a crystallographic GB width (δ crystal ) of 1 nm, and 2.5 × 10 −11 cm 2 s −1 using a chemically measured δ chem of 11.10 nm by atom probe tomography (APT). The origin of the concomitant changes in the cation composition is also investigate. In addition to the host cations, strong Na segregation is detected at all the GBs examined. Despite the low (ppm) level of this impurity, its presence can affect the space charge potential (Φ 0 ). This, in turn, will influence the evolution of GB chemistry.    

    

* Molten Salt‐Assisted Synthesis of Ferric Oxide/M–N–C Nanosheet Electrocatalysts for Efficient Oxygen Reduction Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403215671
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smtd.202401278")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403215671"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403215671"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403215671"))][Get cited by]]

OpenAlex: https://openalex.org/W4403215671 (Open access: False)
    
[[https://openalex.org/A5084226674][Zhiwei Lu]], [[https://openalex.org/A5102256671][Weiming Gong]], [[https://openalex.org/A5101835468][Jinpeng Chen]], [[https://openalex.org/A5032333570][Peng Guo]], [[https://openalex.org/A5101672224][Yingxian Zhang]], [[https://openalex.org/A5002577895][Lan Zhang]], [[https://openalex.org/A5043046106][Minglei Yan]], [[https://openalex.org/A5026305465][Chun‐Yi Wu]], [[https://openalex.org/A5041993637][Mengmeng Sun]], [[https://openalex.org/A5044345668][Gehong Su]], [[https://openalex.org/A5100417669][Yan Wang]], [[https://openalex.org/A5018286530][Yanying Wang]], [[https://openalex.org/A5103045522][Jianshan Ye]], [[https://openalex.org/A5030572896][Wenxin Zhu]], [[https://openalex.org/A5100666575][Jianlong Wang]], [[https://openalex.org/A5013078647][Hanbing Rao]], Small Methods. None(None)] 2024. https://doi.org/10.1002/smtd.202401278 
     
Abstract Efficient, stable, and low‐cost oxygen reduction catalysts are the key to the large‐scale application of metal–air batteries. Herein, high‐dispersive Fe 2 O 3 nanoparticles (NPs) with abundant oxygen vacancies uniformly are anchored on lignin‐derived metal–nitrogen–carbon (M–N–C) hierarchical porous nanosheets as efficient oxygen reduction reaction (ORR) catalysts (Fe 2 O 3 /M–N–C, M═Cu, Mn, W, Mo) based on a general and economical KCl molten salt‐assisted method. The combination of Fe with the highly electronegative O induces charge redistribution through the Fe–O–M structure, thereby reducing the adsorption energy of oxygen‐containing substances. The coupling effect of Fe 2 O 3 NPs with M–N–C expedites the catalytic activity toward ORR by promoting proton generation on Fe 2 O 3 and transfer to M–N–C. Experimental and theoretical calculation further revealed the remarkable electronic structure evolution of the metal site during the ORR process, where the emission density and local magnetic moment of the metal atoms change continuously throughout their reaction. The unique layered porous structure and highly active M–N 4 sites resulted in the excellent ORR activity of Fe 2 O 3 /Cu–N–C with the onset potential of 0.977 V, which is superior to Pt/C. This study offers a feasible strategy for the preparation of non‐noble metal catalysts and provides a new comprehension of the catalytic mechanism of M–N–C catalysts.    

    

* Observations of Extremely Metal-poor O Stars: Weak Winds and Constraints for Evolution Models  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403198149
:TOPICS: Stellar Astrophysics and Exoplanet Studies, Star Formation in Molecular Clouds and Protoplanetary Disks, Astronomical Instrumentation and Spectroscopy
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3847/1538-4357/ad697e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403198149"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403198149"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403198149"))][Get cited by]]

OpenAlex: https://openalex.org/W4403198149 (Open access: True)
    
[[https://openalex.org/A5057187752][O. Grace Telford]], [[https://openalex.org/A5086826162][John Chisholm]], [[https://openalex.org/A5065540117][A. A. C. Sander]], [[https://openalex.org/A5060467151][V. S. Ramachandran]], [[https://openalex.org/A5032681455][Kristen B. W. McQuinn]], [[https://openalex.org/A5029422172][Danielle A. Berg]], The Astrophysical Journal. 974(1)] 2024. https://doi.org/10.3847/1538-4357/ad697e 
     
Abstract Metal-poor massive stars drive the evolution of low-mass galaxies, both locally and at high redshift. However, quantifying the feedback they impart to their local surroundings remains uncertain because models of stellar evolution, mass loss, and ionizing spectra are unconstrained by observations below 20% solar metallicity ( Z ⊙ ). We present new Keck Cosmic Web Imager optical spectroscopy of three O-type stars in the nearby dwarf galaxies Leo P, Sextans A, and WLM, which have gas-phase oxygen abundances of 3%–14% Z ⊙ . To characterize their fundamental stellar properties and radiation-driven winds, we fit PoWR atmosphere models to the optical spectra simultaneously with Hubble Space Telescope far-ultraviolet (FUV) spectra and multiwavelength photometry. We find that all three stars have effective temperatures consistent with their spectral types and surface gravities typical of main-sequence dwarf stars. Yet, the combination of those inferred parameters and luminosity for the two lower- Z stars is not reproduced by stellar evolution models, even those that include rotation or binary interactions. The scenario of multiple-star systems is difficult to reconcile with all available data, suggesting that these observations pose a challenge to current evolution models. We highlight the importance of validating the relationship between stellar mass, temperature, and luminosity at very low Z for accurate estimates of ionizing photon production and spectral hardness. Finally, all three stars’ FUV wind profiles reveal low mass-loss rates and terminal wind velocities in tension with expectations from widely adopted radiation-driven wind models. These results provide empirical benchmarks for future development of mass-loss and evolution models for metal-poor stellar populations.    

    

* Microstructure Evolution Analysis of Ni/YSZ Cermet Electrode using Cross-Sectional Model Cells  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403175959
:TOPICS: Thin-Film Solar Cell Technology, Physics and Chemistry of Schottky Barrier Height, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/1945-7111/ad83f6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403175959"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403175959"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403175959"))][Get cited by]]

OpenAlex: https://openalex.org/W4403175959 (Open access: True)
    
[[https://openalex.org/A5091981305][Nanako Bisaka]], [[https://openalex.org/A5036167481][Takashi Sato]], [[https://openalex.org/A5061728826][Riyan Achmad Budiman]], [[https://openalex.org/A5038261130][M. Yamaguchi]], [[https://openalex.org/A5083637129][‪Tatsuya Kawada]], [[https://openalex.org/A5049998841][Keiji Yashiro]], Journal of The Electrochemical Society. None(None)] 2024. https://doi.org/10.1149/1945-7111/ad83f6 
     
Abstract Degradation of solid oxide cells can be partially attributed to the microstructural changes in Ni/YSZ fuel electrodes owing to Ni migration. This study aims to evaluate the microstructural evolution of Ni/YSZ fuel electrodes as a function of the oxygen potential along the thickness direction. To this end, comb-shaped Ni-patterned electrodes were designed on the top layer of a YSZ thin film using two different systems: (a) a symmetrical Ni-patterned electrode and (b) an asymmetrical Ni–Pt electrode with a reference electrode. In the symmetrical electrode, one side of the Ni-patterned electrode operated at the fuel cell (FC) mode, exhibiting expansion that led to an increase in triple-phase boundary (TPB) length and a decrease in electrolyte width. Conversely, the Ni-patterned electrodes that operated in electrolysis (EC) mode showed a slight migration away from the electrolyte. Detailed microstructural changes in the EC mode were examined using the asymmetrical electrode, revealing a correlation between water vapor content and Ni morphology. The results suggest that the amount of water vapor adsorbed on the electrode surface causes the decrease of oxygen potential at TPB. This causes the decrease in the wettability that led to significant change of Ni microstructure across the electrode length.    

    

* Differentiation of the Anammox Core Microbiome: Unraveling the Evolutionary Impetus of Scalable Gene Flow  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403154407
:TOPICS: Microbial Nitrogen Cycling in Wastewater Treatment Systems, Marine Microbial Diversity and Biogeography, Environmental DNA in Biodiversity Monitoring
:PUBLICATION_DATE: 2024-10-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.watres.2024.122580")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403154407"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403154407"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403154407"))][Get cited by]]

OpenAlex: https://openalex.org/W4403154407 (Open access: False)
    
[[https://openalex.org/A5024617555][Quan Zhang]], [[https://openalex.org/A5014019663][Xiao-Ming Ji]], [[https://openalex.org/A5100634476][Xueting Wang]], [[https://openalex.org/A5066975583][Wei Wang]], [[https://openalex.org/A5102363180][Xijun Xu]], [[https://openalex.org/A5100360199][Qi Zhang]], [[https://openalex.org/A5015101701][Defeng Xing]], [[https://openalex.org/A5100429140][Chuan Chen]], [[https://openalex.org/A5100436302][Duu‐Jong Lee]], [[https://openalex.org/A5100429140][Chuan Chen]], Water Research. 268(None)] 2024. https://doi.org/10.1016/j.watres.2024.122580 
     
Anaerobic ammonium oxidation bacteria (AAOB), distinguished by their unique autotrophic nitrogen metabolism, hold pivotal positions in the global nitrogen cycle and environmental biotechnologies. However, the ecophysiology and evolution of AAOB remain poorly understood, attributed to the absence of monocultures. Hence, a comprehensive elucidation of the AAOB-dominated core microbiome, anammox core, is imperative to further completing the theory of engineered nitrogen removal and ecological roles of anammox. Performing taxonomic and phylogenetic analyses on collected genome repertoires, we show here that Candidatus Brocadia and Candidatus Kuenenia possesses a more compact core than Candidatus Jettenia, which partly explains why the latter has a less common ecological presence. Evidence of gene flow is particularly striking in functions related to biosynthesis and oxygen detoxification, underscoring the evolutionary forces driving lineage and core differentiation. Furthermore, CRISPR spacer traceback of the AAOB metagenome-assembled genomes (MAGs) reveals a series of genetic traces for the concealed phages. By reconceptualizing the functional divergence of AAOB with the historical role of phages, we ultimately propose a coevolutionary framework to understand the evolutionary trajectory of anammox microecology. The discoveries provided in this study offer new insights into understanding the evolution of AAOB and the ecology of anammox.    

    

* Self-Inhibition Phenomena in Cu3Pt Oxidation by CO2  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403183740
:TOPICS: Catalytic Nanomaterials, Electrochemical Reduction of CO2 to Fuels, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.4c02218")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403183740"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403183740"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403183740"))][Get cited by]]

OpenAlex: https://openalex.org/W4403183740 (Open access: False)
    
[[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5032792310][Shyam Bharatkumar Patel]], [[https://openalex.org/A5070392626][J. Anibal Boscoboinik]], [[https://openalex.org/A5061621593][Adrian Hunt]], [[https://openalex.org/A5053922026][Iradwikanari Waluyo]], [[https://openalex.org/A5009173681][Guangwen Zhou]], The Journal of Physical Chemistry Letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.4c02218 
     
This study investigates the oxidation behavior of Cu3Pt(100) in CO2 using a combination of ambient-pressure X-ray photoelectron spectroscopy, mass spectroscopy, and density functional theory modeling. Our in situ measurements reveal the simultaneous oxidation and reduction of Cu2O due to the opposing effects of atomic oxygen and CO generated from dissociative CO2 adsorption, leading to a dynamic equilibrium state of simultaneously occurring redox reactions. Complementary atomistic calculations elucidate the inhibitory effects of subsurface Pt enrichment and the counteracting roles of CO2 and CO in surface oxidation and reduction. These results provide mechanistic insights into the dissociative pathway of CO2 molecules and dynamic evolution of surface composition and reactivity of Cu-based alloy catalysts in CO2-rich environments, with broader implications for tuning gas–surface reactions by manipulating gas reactants or solid surface composition.    

    

* Oxygen Isotope Exchange Between Dust Aggregates and Ambient Nebular Gas  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403160420
:TOPICS: Exploration and Study of Mars, Formation and Evolution of the Solar System
:PUBLICATION_DATE: 2024-09-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.48550/arxiv.2409.02736")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403160420"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403160420"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403160420"))][Get cited by]]

OpenAlex: https://openalex.org/W4403160420 (Open access: True)
    
[[https://openalex.org/A5041381450][Sota Arakawa]], [[https://openalex.org/A5091633185][Daiki Yamamoto]], [[https://openalex.org/A5092698821][Lily Ishizaki]], [[https://openalex.org/A5035791187][Tamami Okamoto]], [[https://openalex.org/A5024341217][Noriyuki Kawasaki]], arXiv (Cornell University). None(None)] 2024. https://doi.org/10.48550/arxiv.2409.02736  ([[http://arxiv.org/pdf/2409.02736][pdf]])
     
Meteorites and their components exhibit a diverse range of oxygen isotope compositions, and the isotopic exchange timescale between dust grains and ambient gas is a key parameter for understanding the spatiotemporal evolution of the solar nebula. As dust grains existed as macroscopic aggregates in the solar nebula, it is necessary to consider the isotopic exchange timescales for these aggregates. Here, we theoretically estimate the isotope exchange timescales between dust aggregates and ambient vapor. The isotope exchange process between aggregates and ambient vapor is divided into four processes: (i) supply of gas molecules to the aggregate surface, (ii) diffusion of molecules within the aggregate, (iii) isotope exchange on the surface of constituent particles, and (iv) isotope diffusion within the particles. We evaluate these timescales and assess which one becomes the rate-determining step. We reveal that the isotope exchange timescale is approximately the same as that of the constituent particles when the aggregate radius is smaller than the critical value, which is a few centimeters when considering the exchange reaction between amorphous forsterite aggregates and water vapor.    

    

* Recent Achievements in Heterogeneous Bimetallic Atomically Dispersed Catalysts for Zn–Air Batteries: A Minireview  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403139836
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202406776")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403139836"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403139836"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403139836"))][Get cited by]]

OpenAlex: https://openalex.org/W4403139836 (Open access: False)
    
[[https://openalex.org/A5037393188][Sanshuang Gao]], [[https://openalex.org/A5027340734][Lian Kang]], [[https://openalex.org/A5010888912][Xinzhong Wang]], [[https://openalex.org/A5067268817][Xijun Liu]], [[https://openalex.org/A5068816309][Abdukader Abdukayum]], [[https://openalex.org/A5021045081][Qingquan Kong]], [[https://openalex.org/A5053355651][Guangzhi Hu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202406776 
     
Abstract Rechargeable Zn–air batteries (ZABs) hold promise as the next‐generation energy‐storage devices owing to their affordability, environmental friendliness, and safety. However, cathodic catalysts are easily inactivated in prolonged redox potential environments, resulting in inadequate energy efficiency and poor cycle stability. To address these challenges, anodic active sites require multiple‐atom combinations, that is, ensembles of metals. Heterogeneous bimetallic atomically dispersed catalysts (HBADCs), consisting of heterogeneous isolated single atoms and atomic pairs, are expected to synergistically boost the cyclic oxygen reduction and evolution reactions of ZABs owing to their tuneable microenvironments. This minireview revisits recent achievements in HBADCs for ZABs. Coordination environment engineering and catalytic substrate structure optimization strategies are summarized to predict the innovation direction for HBADCs in ZAB performance enhancement. These HBADCs are divided into ferrous and nonferrous dual sites with unique microenvironments, including synergistic effects, ion modulation, electronic coupling, and catalytic activity. Finally, conclusions and perspectives relating to future challenges and potential opportunities are provided to optimise the performance of ZABs.    

    

* Transformation Dynamics of Nanosized Bi Films into Semiconductor Films of Bismuth Oxide in the Cold Plasma Device  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403204707
:TOPICS: Emergent Phenomena at Oxide Interfaces, Topological Insulators and Superconductors, Quantum Spin Liquids in Frustrated Magnets
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/pssb.202400364")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403204707"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403204707"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403204707"))][Get cited by]]

OpenAlex: https://openalex.org/W4403204707 (Open access: True)
    
[[https://openalex.org/A5077718232][Emrah Koç]], [[https://openalex.org/A5011199946][B. G. Salamov]], [[https://openalex.org/A5043452347][T. G. Mammadov]], [[https://openalex.org/A5057717589][Nelli N. Lebedeva]], [[https://openalex.org/A5018509007][V. I. Orbukh]], physica status solidi (b). None(None)] 2024. https://doi.org/10.1002/pssb.202400364  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/pssb.202400364][pdf]])
     
This work proposes an original method that reveals the transformation dynamics of nanosized Bi films into semiconductor films of bismuth oxide (Bi 2 O 3 ) and the factors affecting the low‐energy cold plasma on the electro‐optical properties of Bi 2 O 3 . In the plasma microreactor with a photosensitive GaAs:Cr electrode, the transformed Bi films 400–1100 nm thick are analyzed by X‐ray diffraction to determine the crystal structure of Bi 2 O 3 and by an electron probe microanalyzer to explore the evolution of the composition. The morphological properties of the Bi films exposed to electron–ion flow are examined by processing the scanning electron microscope images. It is found that as a result of the combined effect of photoactive illumination, charged particles, and active plasma components: 1) an absorption spectrum of a new substance is formed in the range λ = 330–1100 nm; 2) the optical width of the bandgap of the resulting substance is E g ≈ 3 eV, which satisfactorily coincides with the width of the bandgap of Bi 2 O 3 ; and 3) to overcome the potential barrier and formation of semiconducting Bi 2 O 3 film energy is required, which is provided by the combined kinetic energy of electrons and negatively charged oxygen ions bombarding on the Bi film.    

    

* Phenanthridine‐based Covalent Organic Frameworks for Boosting Overall Solar H2O2 Production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403140481
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202417115")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403140481"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403140481"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403140481"))][Get cited by]]

OpenAlex: https://openalex.org/W4403140481 (Open access: False)
    
[[https://openalex.org/A5000627937][Jieyu Yue]], [[https://openalex.org/A5101335843][Jing‐Xian Luo]], [[https://openalex.org/A5055702535][Zi‐Xian Pan]], [[https://openalex.org/A5069765087][Qing Xu]], [[https://openalex.org/A5058775682][Peng Yang]], [[https://openalex.org/A5087098070][Bo Tang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202417115 
     
Solar‐driven H2O2 production via the oxygen reduction reaction (ORR) and water oxidation reaction (WOR) dual channels is green and sustainable, but severely restricted by the sluggish reaction kinetics. Constructing intriguing photocatalysts with effective active centers is a shortcut to breaking the kinetic bottleneck with great significance. Herein, we synthesize two novel neutral phenanthridine‐based covalent organic frameworks (PD‐COF1 and PD‐COF2) for photosynthesizing H2O2. Compared to the no phenanthridine counterpart (AN‐COF), the H2O2 photosynthetic activities of PD‐COF1 and PD‐COF2 are markedly boosted. In air and pure water without sacrificial agents, under Xe lamp and natural sunlight, the H2O2 photogeneration rate of PD‐COF2 is 6103 and 3646 μmol g‐1 h‐1, respectively. Further experimental and theoretical inspections demonstrate that introducing phenanthridine units into COFs smoothly modulates the charge carrier dynamics and thermodynamically favors the generation of crucial OOH* and OH* intermediates in the ORR and WOR paths, respectively. Additionally, this is the first time the neutral phenanthridine moiety serves as the photooxidation unit for 2e‐ WOR towards H2O2 photoproduction. The current work sheds light on exploring novel catalytic centers for high‐performance H2O2 evolution.    

    

* Phenanthridine‐based Covalent Organic Frameworks for Boosting Overall Solar H2O2 Production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403140863
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202417115")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403140863"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403140863"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403140863"))][Get cited by]]

OpenAlex: https://openalex.org/W4403140863 (Open access: False)
    
[[https://openalex.org/A5000627937][Jieyu Yue]], [[https://openalex.org/A5101335843][Jing‐Xian Luo]], [[https://openalex.org/A5055702535][Zi‐Xian Pan]], [[https://openalex.org/A5101875831][Q. N. Xu]], [[https://openalex.org/A5058775682][Peng Yang]], [[https://openalex.org/A5100679233][Bo Tang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202417115 
     
Solar‐driven H2O2 production via the oxygen reduction reaction (ORR) and water oxidation reaction (WOR) dual channels is green and sustainable, but severely restricted by the sluggish reaction kinetics. Constructing intriguing photocatalysts with effective active centers is a shortcut to breaking the kinetic bottleneck with great significance. Herein, we synthesize two novel neutral phenanthridine‐based covalent organic frameworks (PD‐COF1 and PD‐COF2) for photosynthesizing H2O2. Compared to the no phenanthridine counterpart (AN‐COF), the H2O2 photosynthetic activities of PD‐COF1 and PD‐COF2 are markedly boosted. In air and pure water without sacrificial agents, under Xe lamp and natural sunlight, the H2O2 photogeneration rate of PD‐COF2 is 6103 and 3646 μmol g‐1 h‐1, respectively. Further experimental and theoretical inspections demonstrate that introducing phenanthridine units into COFs smoothly modulates the charge carrier dynamics and thermodynamically favors the generation of crucial OOH* and OH* intermediates in the ORR and WOR paths, respectively. Additionally, this is the first time the neutral phenanthridine moiety serves as the photooxidation unit for 2e‐ WOR towards H2O2 photoproduction. The current work sheds light on exploring novel catalytic centers for high‐performance H2O2 evolution.    

    

* The importance of inventions in the development of national industrial culture  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403149071
:TOPICS: Strategizing of Regional and National Development, Digital Economy and Sustainable Development
:PUBLICATION_DATE: 2024-09-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.15276/ict.01.2024.43")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403149071"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403149071"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403149071"))][Get cited by]]

OpenAlex: https://openalex.org/W4403149071 (Open access: False)
    
[[https://openalex.org/A5107766199][Oleksii M. Kozachenko]], [[https://openalex.org/A5107766200][Sofiia R. Honcharuk]], [[https://openalex.org/A5107766201][Aleksandra Rusek]], No host. 1(1)] 2024. https://doi.org/10.15276/ict.01.2024.43 
     
The work is dedicated to highlighting the influence of prominent inventors on the development of culture and the traditions of invention, which play a key role in shaping national identity and industrial culture. The article analyzes how innovations and technological achievements of individuals contribute to the formation of national pride, raising awareness, and strengthening the international image of a nation. Special attention is given to inventions that have become symbols of national progress and reflect unique cultural traits embedded in the collective consciousness of the people. The study emphasizes the importance of invention as an integral part of national culture and its significance in building a society focused on innovation and development. In particular, the research highlights the most important moments in the life and scientific activity of a prominent Polish inventor closely connected with Odesa. It traces the evolution of creative ideas and the diversity of interests of Stefan Drzewiecki, whose multifaceted and extraordinary creative interests are reflected in innovations that were groundbreaking in the mechanical engineering of that time. Special attention is given to inventions in the field of submarine construction, particularly the creation of the first military submarine prototype. The structural features of the submarine stimulated further research, which, in turn, led to new inventions. These included the development of an autonomous power system using batteries, an oxygen storage and supply system, and equipment for submarine maneuvering. Many of the proposed solutions were revolutionary for their time and significantly advanced global shipbuilding.    

    

* AN ADVANCED APPROACH TO THE DEFINITION OF THE “MILKY WAY GALAXIES-ANALOGUES”  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403160335
:TOPICS: Astronomical Instrumentation and Spectroscopy, Stellar Astrophysics and Exoplanet Studies, Galaxy Formation and Evolution in the Universe
:PUBLICATION_DATE: 2024-08-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.15407/knit2024.04.081")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403160335"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403160335"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403160335"))][Get cited by]]

OpenAlex: https://openalex.org/W4403160335 (Open access: False)
    
[[https://openalex.org/A5075593412][Ya. S. Yatskiv]], [[https://openalex.org/A5024473058][P. N. Fedorov]], [[https://openalex.org/A5021053040][D. V. Dobrycheva]], [[https://openalex.org/A5065891867][O. Sergijenko]], [[https://openalex.org/A5016686641][A. A. Vasylenko]], [[https://openalex.org/A5065446313][Artem Dmytrenko]], [[https://openalex.org/A5003725176][Vladislav Khramtsov]], [[https://openalex.org/A5082986576][O. V. KOMPANIIETS]], Kosmìčna nauka ì tehnologìâ. 30(4)] 2024. https://doi.org/10.15407/knit2024.04.081 
     
Our Galaxy — the Milky Way — has certain features of the structure and evolution. The morphological, photometric, kinematic, and chemodynamical properties are usually considered in search for the Milky Way galaxies-analogues (MWAs). The discovery of MWA galaxies with a larger number of simultaneous selection parameters, as well as more stringent constraints on a given parameter, yields a sample of MWA galaxies with properties closer to the true properties of the Milky Way. So, in general, such MW parameters as the morphological type, luminosity, color indices, structural parameters (size, bar, bulge, thin and thick disks, inner ring, halo), bulge- to-total ratio, stellar mass, star formation rate, metallicity, and rotation velocity were used in various combinations for comparison with other galaxies. However, the offset of some MW features in the multi-parameter space of MWAs features should be significant. The paper aims to give a brief overview of the problematics and to present our approach for studying Milky Way and MWAs match- ing characteristics (this project is supported by the National Research Fund of Ukraine). We propose to enlarge as much as possible the number of Milky Way features and compile various samples of MWAs in our co-moving cosmological volume for their further optimization. Such features can include 3D-kinematics of star’s movement in certain regions, low oxygen content on the periphery, low nuclear activity, and the lack of significant merging over the past 10 Gyrs (isolation criterion). This approach will make it possible to widely formulate the necessary and sufficient conditions for the detection of MWA galaxies as well as to reveal other MW multiwave- length features    

    

* Insight into Structure, Regulatable Photoluminescence of Stably Self and Codoped Phosphor Ba3Y2B6O15: Dy/Eu for nUV wLEDs  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403196243
:TOPICS: Upconversion Nanoparticles, Perovskite Solar Cell Technology, Nonlinear Optical Materials
:PUBLICATION_DATE: 2024-10-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/lpor.202400874")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403196243"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403196243"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403196243"))][Get cited by]]

OpenAlex: https://openalex.org/W4403196243 (Open access: True)
    
[[https://openalex.org/A5102276138][Wang Chang]], [[https://openalex.org/A5007631877][Li Yue]], [[https://openalex.org/A5046151714][Wanyuan Li]], [[https://openalex.org/A5008110151][Yifeng Lei]], [[https://openalex.org/A5101576131][Man Xu]], [[https://openalex.org/A5079451455][Wubin Dai]], Laser & Photonics Review. None(None)] 2024. https://doi.org/10.1002/lpor.202400874  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/lpor.202400874][pdf]])
     
Abstract The exploitation of borate‐based phosphors is garnered tremendous attention in w LEDs. Although previous research provided some insights into borates from the viewpoints of synthesis, structure, and defect evolutions, their photoluminescence (PL) with dopants is still insufficient for actual application, especially on aspects of efficiency/stability. Herein, to alleviate the above issues, a new type of lesser‐known high symmetry Ba 3 Y 2 B 6 O 15 (BYB) codoped with Dy 3+ /Eu 3+ phosphors are synthesized via multistep solid‐state reaction and possessed controllable PL based on n UV excitation, defect‐induced (self‐) PL, and energy transfer (ET) from Dy 3+ to Eu 3+ . The origin of blue self‐PL is clarified based on oxygen‐related defects and optimized via adjusting synthetic atmosphere (air/Ar) and (co)doping dopants to control the defect content. Thanks to dense connectivity, and highly symmetric structure with perfectly ordered octahedral sites of Y 3+ for accommodation of Dy/Eu and ET, “cool” white and red PL from Dy 3+ and Eu 3+ , respectively, show high PL efficiency with narrow full width at half the maximum (fwhm). The phosphor also exhibits excellent thermal stability because of high bandgap and low electron‐phonon coupling. Finally, a high‐quality phosphor‐converted w LED (pc‐ w LED) device is assembled via remote “capping” packaging by adopting the BYB: Dy/Eu and a 350 nm n UV LED chip.    

    

* Ocean oxygenation and ecological restructuring caused by the late Paleozoic evolution of land plants  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403205883
:TOPICS: Evolution and Classification of Flowering Plants, Analysis of Land Cover and Ecosystems, Climate Change and Paleoclimatology
:PUBLICATION_DATE: 2024-10-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1130/g52502.1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403205883"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403205883"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403205883"))][Get cited by]]

OpenAlex: https://openalex.org/W4403205883 (Open access: False)
    
[[https://openalex.org/A5089996625][Jack Stacey]], [[https://openalex.org/A5030034970][Malcolm W. Wallace]], [[https://openalex.org/A5065040092][Ashleigh v.S. Hood]], [[https://openalex.org/A5052596204][Alice Shuster]], [[https://openalex.org/A5075383401][Hilary Corlett]], [[https://openalex.org/A5101828553][Chris Reed]], [[https://openalex.org/A5063590785][Conor Moynihan]], Geology. None(None)] 2024. https://doi.org/10.1130/g52502.1 
     
The dramatic increase in ocean-atmosphere oxygen levels during the Devonian and Mississippian is increasingly linked to the diversification of land plants, yet the timing and extent of this event remain uncertain. This study uses the redox-sensitive rare earth element cerium (cerium anomaly—Ce/Ce*) to investigate ocean redox conditions during the deposition of globally distributed Paleozoic carbonate strata. Our Paleozoic Ce/Ce* record suggests that Cambrian, Ordovician, and Silurian oceans had relatively low O2 levels (mean Ce/Ce* = 0.86 ± 0.10, 0.91 ± 0.14, and 0.91 ± 0.10 [±1σ], respectively). In contrast, short-lived ocean oxygenation events, possibly related to the diversification of small land plants, likely occurred throughout the Early and Middle Devonian (mean Ce/Ce* = 0.80 ± 0.07 and 0.58 ± 0.14, respectively). “Modern” Ce/Ce* values (&lt;0.36) first occurred during the Late Devonian, suggesting that the main phase of Devonian and Mississippian oceanic oxygenation was related to the evolution of large vascular plants and the first forests. Despite this, the significant variability of Ce/Ce* values during this time suggests that shallow marine settings were susceptible to redox instability, possibly caused by upwelling of anoxic deep waters. This redox instability potentially provides evidence of a mechanism for contemporaneous mass extinction and metazoan reef collapse events. Development of strongly oxic conditions during the Late Devonian may have resulted in the demise of many Paleozoic-type organisms, facilitated the radiation of the modern evolutionary fauna, and established the modern oxygenated ocean-atmosphere system.    

    

* Experimental investigation of the swirling steam jet condensation at low mass flux  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403216499
:TOPICS: Nuclear Thermal Hydraulics in Passive Systems, Challenges and Applications of Detonation Propulsion Technology, Nuclear Reactor Technology and Development
:PUBLICATION_DATE: 2024-10-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0231525")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403216499"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403216499"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403216499"))][Get cited by]]

OpenAlex: https://openalex.org/W4403216499 (Open access: False)
    
[[https://openalex.org/A5023452385][Hongchuan Cong]], [[https://openalex.org/A5077868791][Peidong Han]], [[https://openalex.org/A5089387872][Ziqi Zhou]], [[https://openalex.org/A5102902654][Sun Zhong]], [[https://openalex.org/A5047066282][Guang Xi]], Physics of Fluids. 36(10)] 2024. https://doi.org/10.1063/5.0231525 
     
Swirling steam jet condensation holds significant applications in industrial processes such as nuclear safety and gas–liquid mixing in the oxygen transmission pipeline of the liquid rocket engine. However, due to its involvement with complex flow and phase-change heat transfer, the application and optimization of related condensation technologies still face challenges. Therefore, this paper aims to investigate the condensation characteristics of the swirling steam jet by numerous experiments. The steam mass flux is 15–45 kg/(m2·s), and the water temperature ranges from 40 to 85 °C. A novel X-type swirl pressure nozzle is selected to achieve the swirling flow of the steam jet. A comparative analysis is conducted on the interface behavior and evolution of condensation parameters of the non-swirling and swirling steam jets during condensation processes. Results show that the swirling jet condensation includes three flow patterns, namely, chugging regime, smooth grown bubble regime, and rough grown bubble regime. Compared with the non-swirling steam jet condensation, swirling steam jets exhibit a 10.36% increase in the smooth grown bubble regime region and a 14.63% decrease in the rough grown bubble regime. Swirling bubble morphology evolves steadily, and the surface is smoother and more rounded. Simultaneously, irregular deformation behaviors can also occur in the swirling bubble condensation process, such as spiral growth of jet bulge, neck torsion, and the corolla pattern. This deformation helps to increase the contact area and prolongs the bubble lifetime, allowing for more adequate heat transfer at the steam–water interface. The swirling motion of the steam jet will reduce the bubble collapse frequency. As the water temperature rises from 60 to 80 °C, the bubble condensation rate and collapse frequency decrease. The bubble radius increases and the condensation time is extended. With the increasing steam mass flux, the collapse frequency gradually increases. The condensation rate and the bubble radius vary nonlinearly. At the higher steam mass flux, the swirling motion can effectively release the heat that accumulates inside the bubble after reaching the condensation equilibrium state.    

    

* Cathodoluminescence textures and trace elements in quartz: Constraints on Ag mineralization in adularia–sericite epithermal systems  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4403123277
:TOPICS: Geochemistry and Petrology of Gemstones, Tectonic and Geochronological Evolution of Orogens, Machine Learning for Mineral Prospectivity Mapping
:PUBLICATION_DATE: 2024-10-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2138/am-2024-9415")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4403123277"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4403123277"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4403123277"))][Get cited by]]

OpenAlex: https://openalex.org/W4403123277 (Open access: False)
    
[[https://openalex.org/A5101954526][Shen Gao]], [[https://openalex.org/A5021732448][Xinyu Zou]], [[https://openalex.org/A5053243562][Albert H. Hofstra]], [[https://openalex.org/A5081788680][Liangliang Huang]], [[https://openalex.org/A5101984225][Haijun Yang]], [[https://openalex.org/A5083847024][Kezhang Qin]], [[https://openalex.org/A5055759132][Erin E. Marsh]], [[https://openalex.org/A5051306008][Kaixuan Hui]], [[https://openalex.org/A5030793797][Jing Xu]], [[https://openalex.org/A5107956335][Le Wang]], [[https://openalex.org/A5100448266][Zhenzhen Li]], [[https://openalex.org/A5101970125][Junxing Zhao]], [[https://openalex.org/A5059420957][Ri Han]], [[https://openalex.org/A5100635451][Guangming Li]], American Mineralogist. None(None)] 2024. https://doi.org/10.2138/am-2024-9415 
     
Abstract Quartz chemistry is important for revealing fluid sources and evolution in hydrothermal deposits, but such information is lacking for many epithermal systems and deposit types. To investigate quartz chemistry in this system further, we collected representative samples of quartz from adularia-sericite epithermal Ag deposits in China and determined their chemical compositions. In adularia-sericite epithermal Ag-bearing systems, magmatic quartz from porphyry intrusions and host subvolcanic rocks is SEM-CL spectral peaks at 360 and 415 nm and exhibits homogenous CL or weak zonal textures (alternating growth zones within individual quartz crystal). Trace elements in magmatic quartz have the lowest Sb concentrations (median = 0.1 ppm; n = 80). Hydrothermal quartz can be classified into type I and type II by CL false color and CL spectral peaks. Hydrothermal type I quartz has spectral peaks at 360 and 415 nm, exhibits zonal or sector textures, and is associated with base metal sulfides and minor Ag mineralization. Such hydrothermal type I quartz has low Sb concentrations (median = 4.5 ppm; n = 839), contains liquid-rich fluid inclusions and formed by cooling. The cooling trend is indicated by a positive correlation between the concentrations of Sb and Al, as well as between Li and Al. Hydrothermal type I quartz has an Fe center by electron spin resonance, whereas other centers are missing or weak at room temperature. In general, hydrothermal type II quartz mantles type I quartz. Hydrothermal type II quartz has a very high intensity peak (by several orders of magnitude) at 580 nm, zonal textures, and is associated with abundant Ag mineralization. Hydrothermal type II quartz has the highest Sb concentrations (median = 71 ppm; n = 185), which remain constant as Al decreases on an Sb vs. Al plot. This quartz has colloform, bladed or zonal textures and contains coexisting liquid- and vapor-rich fluid inclusions, indicative of boiling. Additionally, this quartz has a significantly higher E'1 center intensity, suggesting a high concentration of oxygen vacancies associated with rapid crystallization. The mineral paragenesis, analytical results, and geochemical models show that in these Ag-bearing epithermal systems hydrothermal type I quartz associated with base metal sulfides precipitated during cooling whereas subsequent growth zoned hydrothermal type II quartz with high Sb concentrations and Ag-minerals precipitated during boiling. These results suggest that the CL texture and spectra, trace elements, and electron spin resonance data of quartz could identify veins with potential for Ag mineralization in epithermal systems.    

    
