#+TITLE: water splitting
Description: water splitting papers
Created on Mon Sep  2 01:16:59 2024

Found 53 results from 2024-08-26 to 2024-09-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Key role of nonprecious oxygen-evolving active site in NiOOH electrocatalysts for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401858995
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.161066")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401858995"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401858995"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401858995"))][Get cited by]]

OpenAlex: https://openalex.org/W4401858995 (Open access: False)
    
[[https://openalex.org/A5078261490][Qi Zhang]], [[https://openalex.org/A5052639398][Na Song]], [[https://openalex.org/A5101836429][Ming Fang]], [[https://openalex.org/A5014057758][Yixing Li]], [[https://openalex.org/A5101385821][Xuedi Chen]], [[https://openalex.org/A5100387720][Yue Li]], [[https://openalex.org/A5100591696][Lei He]], [[https://openalex.org/A5101436430][Wenbiao Zhang]], [[https://openalex.org/A5025630109][Xiaoyu Ma]], [[https://openalex.org/A5037548079][Xianzhang Lei]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.161066 
     
No abstract    

    

* Novel Ni-doped dual MOF-derived urchin-like Co-Fe layered double hydroxides for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401862575
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.176155")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401862575"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401862575"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401862575"))][Get cited by]]

OpenAlex: https://openalex.org/W4401862575 (Open access: False)
    
[[https://openalex.org/A5068275623][Zikang Tang]], [[https://openalex.org/A5050807267][Lin Hao]], [[https://openalex.org/A5102295729][Mingjie Hu]], [[https://openalex.org/A5101788579][Gao Y]], [[https://openalex.org/A5100773712][Yufan Zhang]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.176155 
     
No abstract    

    

* Modulation of interface electric field over CoMoP-CoMoP2 heterostructure for high-efficiency oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401862923
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.155184")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401862923"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401862923"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401862923"))][Get cited by]]

OpenAlex: https://openalex.org/W4401862923 (Open access: False)
    
[[https://openalex.org/A5102641672][Shaoshuai Xu]], [[https://openalex.org/A5101706041][Wenjing Cui]], [[https://openalex.org/A5060910348][Yudong Feng]], [[https://openalex.org/A5100687716][Chunping Li]], [[https://openalex.org/A5101585938][Xingwei Sun]], [[https://openalex.org/A5090878267][J. Bai]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.155184 
     
No abstract    

    

* Enhancing the Electrochemical Catalytic Performance of Novel Bifunctional Oxygen Vacancy-Enriched Silver Niobate (Agnbo3) Through Electrochemical Activation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401863282
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4936286")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401863282"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401863282"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401863282"))][Get cited by]]

OpenAlex: https://openalex.org/W4401863282 (Open access: False)
    
[[https://openalex.org/A5101895233][Deepak R. Patil]], [[https://openalex.org/A5087069788][Harish S. Chavan]], [[https://openalex.org/A5055367754][A. F. Lee]], [[https://openalex.org/A5100756275][Geon Lee]], [[https://openalex.org/A5101895233][Deepak R. Patil]], [[https://openalex.org/A5100719658][Ki‐Young Lee]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4936286 
     
No abstract    

    

* Cover Feature: Self‐Modification of Defective TiO2 under Controlled H2/Ar Gas Environment and Dynamics of Photoinduced Surface Oxygen Vacancies (ChemSusChem 16/2024)  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401881215
:TOPICS: Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-08-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202481603")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401881215"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401881215"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401881215"))][Get cited by]]

OpenAlex: https://openalex.org/W4401881215 (Open access: True)
    
[[https://openalex.org/A5072463672][Tim Tjardts]], [[https://openalex.org/A5042641995][Marie Elis]], [[https://openalex.org/A5005679336][Josiah Shondo]], [[https://openalex.org/A5103259175][Lennart Voß]], [[https://openalex.org/A5054341679][Ulrich Schürmann]], [[https://openalex.org/A5031853093][Franz Faupel]], [[https://openalex.org/A5041200678][Lorenz Kienle]], [[https://openalex.org/A5056864337][Salih Veziroğlu]], [[https://openalex.org/A5081995579][Oral Cenk Aktas]], ChemSusChem. 17(16)] 2024. https://doi.org/10.1002/cssc.202481603  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cssc.202481603][pdf]])
     
The Cover Feature abstractly depicts the influence of a mixture of argon (symbolized by pink) and hydrogen (symbolized by blue) on a TiO2 pellet sample in the hydrogenation process. The blue cylinder in the center shows a defective TiO2 pellet sample with an enhanced photocatalytic activity. The green and yellow corona around the cylinder embodies this activity. The grey ellipse to the right shows the induced defects; the Ti3+ site and the oxygen vacancy Vo. More information can be found in the Research Article by S. Veziroglu, O. C. Aktas and co-workers.    

    

* Insights from Ca2+→Sr2+ substitution on the mechanism of O-O bond formation in photosystem II  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401884144
:TOPICS: Molecular Mechanisms of Photosynthesis and Photoprotection, Quantum Coherence in Photosynthesis and Aqueous Systems, Dioxygen Activation at Metalloenzyme Active Sites
:PUBLICATION_DATE: 2024-08-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11120-024-01117-2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401884144"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401884144"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401884144"))][Get cited by]]

OpenAlex: https://openalex.org/W4401884144 (Open access: False)
    
[[https://openalex.org/A5008357139][Gabriel Bury]], [[https://openalex.org/A5006147088][Yulia Pushkar]], Photosynthesis Research. None(None)] 2024. https://doi.org/10.1007/s11120-024-01117-2 
     
No abstract    

    

* Highly Efficient CoFeP Nanoparticle Catalysts for Superior Oxygen Evolution Reaction Performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401891652
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-08-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/nano14171384")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401891652"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401891652"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401891652"))][Get cited by]]

OpenAlex: https://openalex.org/W4401891652 (Open access: True)
    
[[https://openalex.org/A5013205846][Abhishek Meena]], [[https://openalex.org/A5016800946][Abu Talha Aqueel Ahmed]], [[https://openalex.org/A5054940131][Aditya Narayan Singh]], [[https://openalex.org/A5080948891][Vijaya Gopalan Sree]], [[https://openalex.org/A5019371419][Hyunsik Im]], [[https://openalex.org/A5103680968][S. K. Cho]], Nanomaterials. 14(17)] 2024. https://doi.org/10.3390/nano14171384  ([[https://www.mdpi.com/2079-4991/14/17/1384/pdf?version=1724573748][pdf]])
     
Developing effective and long-lasting electrocatalysts for oxygen evolution reaction (OER) is critical for increasing sustainable hydrogen production. This paper describes the production and characterization of CoFeP nanoparticles (CFP NPs) as high-performance electrocatalysts for OER. The CFP NPs were produced using a simple hydrothermal technique followed by phosphorization, yielding an amorphous/crystalline composite structure with improved electrochemical characteristics. Our results reveal that CFP NPs have a surprisingly low overpotential of 284 mV at a current density of 100 mA cm−2, greatly exceeding the precursor CoFe oxide/hydroxide (CFO NPs) and the commercial RuO2 catalyst. Furthermore, CFP NPs demonstrate exceptional stability, retaining a constant performance after 70 h of continuous operation. Post-OER characterization analysis revealed transformations in the catalyst, including the formation of cobalt–iron oxides/oxyhydroxides. Despite these changes, CFP NPs showed superior long-term stability compared to native metal oxides/oxyhydroxides, likely due to enhanced surface roughness and increased active sites. This study proposes a viable strategy for designing low-cost, non-precious metal-based OER catalysts, which will help advance sustainable energy technology.    

    

* Integrated MXenes and Metal Oxide Electrocatalysts for Oxygen Evolution Reaction: Synthesis, Mechanisms, and Advances  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401893313
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc04141k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401893313"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401893313"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401893313"))][Get cited by]]

OpenAlex: https://openalex.org/W4401893313 (Open access: True)
    
[[https://openalex.org/A5062711370][Muhammad Nazim Lakhan]], [[https://openalex.org/A5051360478][Abdul Hanan]], [[https://openalex.org/A5100344858][Yuan Wang]], [[https://openalex.org/A5006483461][Hiang Kwee Lee]], [[https://openalex.org/A5047282351][Hamidreza Arandiyan]], Chemical Science. None(None)] 2024. https://doi.org/10.1039/d4sc04141k 
     
Electrochemical water splitting is a promising approach to produce H2 through renewable electricity, but its energy efficiency is severely constrained by the kinetically slow anodic oxygen evolution reaction (OER), which...    

    

* Fabrication of novel FeSe–GO composite: a highly efficient electro-catalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401893438
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-08-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s43207-024-00434-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401893438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401893438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401893438"))][Get cited by]]

OpenAlex: https://openalex.org/W4401893438 (Open access: False)
    
[[https://openalex.org/A5040146302][Khadim Hussain]], [[https://openalex.org/A5040295128][Ali Junaid]], [[https://openalex.org/A5059163435][Syed Imran Abbas Shah]], [[https://openalex.org/A5102316296][Muhammad Moazzam Khan]], [[https://openalex.org/A5048229373][Muhammad Shoaib]], [[https://openalex.org/A5103113713][Nigarish Bano]], [[https://openalex.org/A5003194921][Razan A. Alshgari]], [[https://openalex.org/A5092569925][Nosheen Blouch]], [[https://openalex.org/A5063142393][Muhammad Fahad Ehsan]], [[https://openalex.org/A5061069978][Muhammad Naeem Ashiq]], Journal of the Korean Ceramic Society. None(None)] 2024. https://doi.org/10.1007/s43207-024-00434-5 
     
No abstract    

    

* Co–Mn Bimetallic Metal–Organic Frameworks Nanosheets for Efficient Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401911685
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-08-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ente.202401049")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401911685"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401911685"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401911685"))][Get cited by]]

OpenAlex: https://openalex.org/W4401911685 (Open access: False)
    
[[https://openalex.org/A5079175962][Yongchao Hao]], [[https://openalex.org/A5100371313][Sheng Wang]], [[https://openalex.org/A5063497599][Shuling Cheng]], [[https://openalex.org/A5102516749][Huiya Cheng]], [[https://openalex.org/A5057002330][Qianyun He]], [[https://openalex.org/A5101585730][Lizhi Yi]], Energy Technology. None(None)] 2024. https://doi.org/10.1002/ente.202401049 
     
Developing an efficient oxygen evolution reaction (OER) catalyst is the footstone of many electrochemical energy conversion devices. Herein, a cobalt–manganese bimetallic metal–organic framework (MOF) is developed as an efficient OER catalyst (denoted as Co 3 Mn 1 BDC). The Co 3 Mn 1 BDC nanosheets demonstrate advantages in specific surface area, pore size distribution comparing with monometallic Co BDC and Mn BDC. The performance investigations demonstrate that the doping of Mn in Co‐based MOFs facilitates the electrochemical area, charge transfer efficiency, reaction kinetics, and turnover frequency. As a consequence, the Co 3 Mn 1 BDC exhibits a low overpotential of 289 mV at current of 10 mA cm −2 and a favorable Tafel slope of 56.8 mV dec −1 on glassy carbon electrode, which is better than IrO 2 . When the catalyst is loaded on Ni foam, the overpotential and Tafel slope are further decreased to 231 mV and 50.8 mV dec −1 . Moreover, the Raman spectrum confirms that the Co 3 Mn 1 BDC can be transformed into active CoOOH, suggesting the bright prospect in electrocatalysis devices as “precatalyst”.    

    

* Enhanced Oxygen Evolution Reaction Activity on Two-Dimensional vdW Ferromagnetic Cr2Ge2Te6 Through A Two-Active-Sites Synergism  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401921914
:TOPICS: Two-Dimensional Materials, Magnetocaloric Materials Research, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cp01941e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401921914"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401921914"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401921914"))][Get cited by]]

OpenAlex: https://openalex.org/W4401921914 (Open access: False)
    
[[https://openalex.org/A5088943806][Zongxiang Kang]], [[https://openalex.org/A5100755439][Wei Su]], [[https://openalex.org/A5100701719][Qiuhong Li]], [[https://openalex.org/A5101280278][Hu Jing-Guo]], [[https://openalex.org/A5100658336][Jing Pan]], Physical Chemistry Chemical Physics. None(None)] 2024. https://doi.org/10.1039/d4cp01941e 
     
To design an efficient, low-cost, and easily recoverable oxygen evolution reaction (OER) electrocatalysts, we focus on two-dimensional vdW ferromagnetic Cr2Ge2Te6. Based on the density functional theory (DFT) calculation, the adsorption...    

    

* Ultrasonic-Induced Surface Disordering Promotes Photocatalytic Hydrogen Evolution of TiO2  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401933572
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Photocatalysis and Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-08-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c10977")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401933572"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401933572"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401933572"))][Get cited by]]

OpenAlex: https://openalex.org/W4401933572 (Open access: False)
    
[[https://openalex.org/A5102492014][Chunyao Liu]], [[https://openalex.org/A5002695529][Changhua Wang]], [[https://openalex.org/A5100371335][Sheng Wang]], [[https://openalex.org/A5080932376][Dashuai Li]], [[https://openalex.org/A5010680943][Dexin Jin]], [[https://openalex.org/A5087432418][Bunsho Ohtani]], [[https://openalex.org/A5063817096][Baoshun Liu]], [[https://openalex.org/A5082917352][He Ma]], [[https://openalex.org/A5040267828][Jinglun Du]], [[https://openalex.org/A5100658559][Yichun Liu]], [[https://openalex.org/A5100461957][Xintong Zhang]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c10977 
     
Surface disordering has been considered an effective strategy for tailoring the charge separation and surface chemistry of semiconductor photocatalysts. A simple but reliable method to create surface disordering is, therefore, urgently needed for the development of high-performance semiconductor photocatalysts and their practical applications. Herein, we report that the ultrasonic processing, which is commonly employed in the dispersion of photocatalysts, can induce the surface disordering of TiO2 and significantly promote its performance for photocatalytic hydrogen evolution. A 40 min ultrasonic treatment of TiO2 (Degussa P25) enhances the photocatalytic hydrogen production by 42.7 times, achieving a hydrogen evolution rate of 1425.4 μmol g–1 h–1 without any cocatalyst. Comprehensive structural, spectral, and electrochemical analyses reveal that the ultrasonic treatment induces the surface disordering of TiO2, and consequently reduces the density of deep electron traps, extends the separation of photogenerated charges, and facilitates the hydrogen evolution reaction relative to oxygen reduction. The ultrasonic treatment manifests a more pronounced effect on disordering the surface of anatase than rutile, agreeing well with the enhanced photocatalysis of anatase rather than rutile. This study demonstrates that ultrasonic-induced surface disordering could be an effective strategy for the activation of photocatalysts and might hold significant implications for the applications in photocatalytic hydrogen evolution, small molecule activation, and biomass conversion.    

    

* Review for "Ultrathin iridium carbonyl formate for efficient and durable acidic oxygen evolution electrocatalysis"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401935618
:TOPICS: Electrocatalysis for Energy Conversion, Conducting Polymer Research, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-08-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04064c/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401935618"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401935618"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401935618"))][Get cited by]]

OpenAlex: https://openalex.org/W4401935618 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04064c/v2/review1 
     
No abstract    

    

* Decision letter for "Ultrathin iridium carbonyl formate for efficient and durable acidic oxygen evolution electrocatalysis"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401935662
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-08-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04064c/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401935662"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401935662"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401935662"))][Get cited by]]

OpenAlex: https://openalex.org/W4401935662 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04064c/v2/decision1 
     
No abstract    

    

* Review for "Ultrathin iridium carbonyl formate for efficient and durable acidic oxygen evolution electrocatalysis"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401935697
:TOPICS: Electrocatalysis for Energy Conversion, Conducting Polymer Research, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04064c/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401935697"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401935697"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401935697"))][Get cited by]]

OpenAlex: https://openalex.org/W4401935697 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04064c/v1/review2 
     
No abstract    

    

* Review for "Ultrathin iridium carbonyl formate for efficient and durable acidic oxygen evolution electrocatalysis"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401935698
:TOPICS: Electrocatalysis for Energy Conversion, Conducting Polymer Research, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04064c/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401935698"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401935698"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401935698"))][Get cited by]]

OpenAlex: https://openalex.org/W4401935698 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04064c/v1/review1 
     
No abstract    

    

* Decision letter for "Ultrathin iridium carbonyl formate for efficient and durable acidic oxygen evolution electrocatalysis"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401935802
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-06-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta04064c/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401935802"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401935802"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401935802"))][Get cited by]]

OpenAlex: https://openalex.org/W4401935802 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta04064c/v1/decision1 
     
No abstract    

    

* Review for "Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401937743
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc01841a/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401937743"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401937743"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401937743"))][Get cited by]]

OpenAlex: https://openalex.org/W4401937743 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4sc01841a/v1/review2 
     
No abstract    

    

* Review for "Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401937824
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-04-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc01841a/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401937824"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401937824"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401937824"))][Get cited by]]

OpenAlex: https://openalex.org/W4401937824 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4sc01841a/v1/review1 
     
No abstract    

    

* Review for "Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401937912
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc01841a/v2/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401937912"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401937912"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401937912"))][Get cited by]]

OpenAlex: https://openalex.org/W4401937912 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4sc01841a/v2/review2 
     
No abstract    

    

* Review for "Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401937913
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-08-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc01841a/v3/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401937913"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401937913"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401937913"))][Get cited by]]

OpenAlex: https://openalex.org/W4401937913 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4sc01841a/v3/review1 
     
No abstract    

    

* Decision letter for "Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401938081
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-08-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc01841a/v3/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401938081"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401938081"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401938081"))][Get cited by]]

OpenAlex: https://openalex.org/W4401938081 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4sc01841a/v3/decision1 
     
No abstract    

    

* Review for "Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401938123
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc01841a/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401938123"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401938123"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401938123"))][Get cited by]]

OpenAlex: https://openalex.org/W4401938123 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4sc01841a/v2/review1 
     
No abstract    

    

* Decision letter for "Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401938303
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-05-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc01841a/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401938303"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401938303"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401938303"))][Get cited by]]

OpenAlex: https://openalex.org/W4401938303 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4sc01841a/v1/decision1 
     
No abstract    

    

* Decision letter for "Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401938401
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-08-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc01841a/v4/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401938401"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401938401"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401938401"))][Get cited by]]

OpenAlex: https://openalex.org/W4401938401 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4sc01841a/v4/decision1 
     
No abstract    

    

* Decision letter for "Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401938503
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc01841a/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401938503"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401938503"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401938503"))][Get cited by]]

OpenAlex: https://openalex.org/W4401938503 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4sc01841a/v2/decision1 
     
No abstract    

    

* Scale-Up, Continuous and Low-Temperature Production of Multimetal Based Electrocatalysts toward Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401942075
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-08-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c08677")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401942075"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401942075"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401942075"))][Get cited by]]

OpenAlex: https://openalex.org/W4401942075 (Open access: False)
    
[[https://openalex.org/A5063490642][Pak Kin Wong]], [[https://openalex.org/A5100433276][Jun Zhang]], [[https://openalex.org/A5080019524][Jia‐qi Bai]], [[https://openalex.org/A5101530595][Yong Jiang]], [[https://openalex.org/A5051022800][Jingshuai Chen]], [[https://openalex.org/A5101970159][Mingyuan Wu]], [[https://openalex.org/A5078325730][Song Sun]], [[https://openalex.org/A5075545986][Jingshuai Chen]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c08677 
     
Electrocatalytic water splitting is a crucial strategy for advancing hydrogen energy and addressing the global energy crisis. Despite its significance, the need for a straightforward and swift method to synthesize electrocatalysts with exceptional performance remains pressing. In this study, we demonstrate a novel approach for the preparation of multimetal-based electrocatalysts in a continuous flow reactor, enabling the quick synthesis of a large number of products through a streamlined process. The resultant NiFe-LDH comprises nanoflakes with a high specific surface area and requires only 255.4 mV overpotential to achieve a current density of 10 mA·cm–2 in 1 M KOH, surpassing samples fabricated by conventional hydrothermal methods. Our method can also be applied to craft a spectrum of other multimetal-based electrocatalysts, including CoFe-LDH, CoAl-LDH, NiMn-LDH, and NiCoFe-LDH. Additionally, the NiFe-LDH electrocatalyst is further applied to anodic methanol electrooxidation coupled with cathodic hydrogen evolution. Moreover, the simplicity and generality of our fabrication method render it applicable for the facile preparation of various multimetal-based electrocatalysts, offering a scalable solution to the quest for high-performance catalysts in advancing sustainable energy technologies.    

    

* Developing new electrocatalysts for oxygen evolution reaction via high throughput experiments and artificial intelligence  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401944607
:TOPICS: Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-08-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41524-024-01386-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401944607"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401944607"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401944607"))][Get cited by]]

OpenAlex: https://openalex.org/W4401944607 (Open access: True)
    
[[https://openalex.org/A5102588816][S. L. XU]], [[https://openalex.org/A5047364309][Zhuyang Chen]], [[https://openalex.org/A5012551379][Mingyang Qin]], [[https://openalex.org/A5021983972][Bijun Cai]], [[https://openalex.org/A5100666422][Weixuan Li]], [[https://openalex.org/A5059248453][Ronggui Zhu]], [[https://openalex.org/A5011577177][Chen Xu]], [[https://openalex.org/A5040345095][X.‐D. Xiang]], npj Computational Materials. 10(1)] 2024. https://doi.org/10.1038/s41524-024-01386-4  ([[https://www.nature.com/articles/s41524-024-01386-4.pdf][pdf]])
     
The development of non-noble metal electrocatalysts for the Oxygen Evolution Reaction (OER) is advancing towards the use of multi-element materials. To reveal the complex correlations of multi-element OER electrocatalysts, we developed an iterative workflow combining high-throughput experiments and AI-generated content (AIGC) processes. An increased number of 909 (compared to 145 in previous literature) universal descriptors for inorganic materials science were constructed and used as Artificial Neural Network (ANN) input. A large number of statistical ensembles with each ANN individual ensemble having a reduced number of descriptors were integrated with a new Hierarchical Neural Network (HNN) algorithm. This algorithm addresses the longstanding challenge of balancing overwhelming descriptor numbers with insufficient datasets in traditional ANN approaches to materials science problems. As a result, the combination of AIGC and experimental validation significantly enhanced prediction accuracy, increase the R2 values from 0.7 to 0.98 for Tafel slopes.    

    

* Exploring the potential application of Cr2AlC MAX phase as an emerging electrocatalyst for overall water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401958081
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Photocatalytic Materials for Solar Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-08-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s42247-024-00815-w")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401958081"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401958081"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401958081"))][Get cited by]]

OpenAlex: https://openalex.org/W4401958081 (Open access: False)
    
[[https://openalex.org/A5031221429][R Madhushree]], [[https://openalex.org/A5051664413][K.R. Sunaja Devi]], Emergent Materials. None(None)] 2024. https://doi.org/10.1007/s42247-024-00815-w 
     
No abstract    

    

* Nanocarbon-based Bifunctional Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401959818
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-08-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/9781837674497-00297")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401959818"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401959818"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401959818"))][Get cited by]]

OpenAlex: https://openalex.org/W4401959818 (Open access: False)
    
[[https://openalex.org/A5083247129][Shouvik Mete]], [[https://openalex.org/A5106781076][Kushagra Goel]], [[https://openalex.org/A5072094113][Santosh K. Singh]], Royal Society of Chemistry eBooks. None(None)] 2024. https://doi.org/10.1039/9781837674497-00297 
     
For the sustainable development of green and clean electrochemical energy technologies, the advancement of high-performance electrode materials is essential. Precious metal catalysts such as those based on Pt, Ir, and Ru show high catalytic performance, but their scarcity and high cost restrict their application in energy technologies. Hence nanocarbon-based bifunctional electrocatalysts have emerged as a promising class of materials that hold the key to addressing critical challenges in energy conversion and storage technologies. Nanocarbon materials, such as carbon nanotubes, graphene, and their derivatives, have shown remarkable electrical conductivity, high surface area, and exceptional chemical stability, making them ideal candidates for electrocatalysis. However, these nanocarbon materials as such are electroneutral and catalytically inactive. Heteroatom doping and functionalization change the electronic properties of the nanocarbons and permit multifunctional electrocatalytic activity. These modified nanocarbons can catalyze the oxygen reduction reaction (ORR), the hydrogen evolution reaction (HER), and the oxygen evolution reaction (OER) in electrochemical systems, making them applicable in fuel cells, water electrolyzers, metal–air batteries, etc. This dual functionality of the materials in energy devices enhances the overall efficiency of energy conversion devices. Applications of nanocarbon-based bifunctional electrocatalysts extend beyond energy storage and conversion, encompassing electrochemical sensors, environmental remediation, etc. The multifunctional nature of nanocarbon materials, coupled with their versatility, holds great promise for developing efficient, durable, and cost-effective electrochemical devices. This chapter provides an insight into the promising field of nanocarbon-based bifunctional electrocatalysts and underscores their significance in shaping a sustainable energy future.    

    

* Bifunctional Electrocatalysts for Metal–Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401959858
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-08-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/9781837674497-00185")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401959858"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401959858"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401959858"))][Get cited by]]

OpenAlex: https://openalex.org/W4401959858 (Open access: False)
    
[[https://openalex.org/A5097271490][Ganesh D. Jadhav]], [[https://openalex.org/A5035836018][Arti A. Jadhav]], [[https://openalex.org/A5101329432][Sumita S. Patil]], [[https://openalex.org/A5027968768][S.S. Shinde]], [[https://openalex.org/A5065577369][Nayantara K. Wagh]], [[https://openalex.org/A5039877781][Sharad B. Patil]], [[https://openalex.org/A5057586032][C.D. Lokhande]], [[https://openalex.org/A5071151758][Umakant M. Patil]], Royal Society of Chemistry eBooks. None(None)] 2024. https://doi.org/10.1039/9781837674497-00185 
     
Metal–air batteries (MABs) have been gaining attention as a promising solution for next-generation electrochemical energy storage devices since they have a higher theoretical energy density than metal ion batteries, making them ideal for applications such as electric vehicles and grid energy storage. These attributes are essential for achieving the ultimate objective of phasing out the world’s reliance on fossil fuels in the long term. However, efficient bifunctional oxygen evolution/reduction reaction (OER/ORR) catalysts are crucial for the further development of MABs. This chapter summarizes the exploration of materials such as metal oxides and conductive polymers that have been identified as promising candidates exhibiting strong catalytic activity and stability in MABs. These materials demonstrate adaptability to diverse environments, whether aqueous or non-aqueous electrolytes, employing various methods for energy storage. These advances are a crucial step towards realizing the potential of MABs, meeting the increasing demand for reliable, high-energy density batteries in emerging technologies. The study of bifunctional electrocatalysts for MABs has provided valuable insights into their performance across different electrolytes and battery types, including Zn, Li, Mg, Na, and Al systems. Bifunctional electrocatalysts play a pivotal role by significantly enhancing both ORR and OER, essential for processes governing the efficiency of MABs. The applicability of bifunctional electrocatalysts underscores their potential to drive advances in various MAB technologies, facilitating the development of more efficient, durable, and versatile energy storage solutions. Ongoing research on and enhancement of these catalysts could lead to more efficient and sustainable energy storage solutions, ushering in a new era in MAB technology.    

    

* Metal–Organic Framework-derived Bifunctional Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401960715
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-08-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/9781837674497-00226")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401960715"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401960715"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401960715"))][Get cited by]]

OpenAlex: https://openalex.org/W4401960715 (Open access: False)
    
[[https://openalex.org/A5036823475][Debal Kanti Singha]], [[https://openalex.org/A5050639751][Tapan Ping]], [[https://openalex.org/A5058234659][Bibhuranjan Nayak]], [[https://openalex.org/A5102874057][Rupali Ipsita Mohanty]], [[https://openalex.org/A5027922078][Bikash Kumar Jena]], Royal Society of Chemistry eBooks. None(None)] 2024. https://doi.org/10.1039/9781837674497-00226 
     
This chapter provides an introduction to the oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) and discusses the fundamental aspects and their significance in different applications. Measurements of different electrochemical parameters needed for the measurement of the OER and ORR performance of a catalyst are considered. A novel class of advanced porous hybrid materials has emerged: metal–organic frameworks (MOFs) with variable pore sizes and large surface areas characterized by various periodic patterns. Because of their immense porosity and mechanical and thermal durability, they are used in a wide variety of applications. However, the low electrical conductivity and poor stability of MOFs make their use in electrocatalysis difficult. The benefits of using MOF-derived materials as bifunctional electrocatalysts for OER and ORR are discussed.    

    

* Unveiling the Aggregation of M−N−C Single‐Atom Electrocatalysts into Highly Efficient MOOH Nanoclusters during Alkaline Water Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401970934
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-08-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202413308")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401970934"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401970934"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401970934"))][Get cited by]]

OpenAlex: https://openalex.org/W4401970934 (Open access: False)
    
[[https://openalex.org/A5021532810][Shanshan Lu]], [[https://openalex.org/A5033653384][Zhipu Zhang]], [[https://openalex.org/A5069312764][Chuanqi Cheng]], [[https://openalex.org/A5100667648][Bin Zhang]], [[https://openalex.org/A5011604879][Yanmei Shi]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202413308 
     
M−N−C‐type single‐atom catalysts (SACs) are highly efficient for the electrocatalytic oxygen evolution reaction (OER). And the isolated metal atoms are usually considered real active sites. However, the oxidative structural evolution of coordinated N during the OER will probably damage the structure of M−N−C, hence resulting in a completely different reaction mechanism. Here, we reveal the aggregation of M−N−C materials during the alkaline OER. Taking Ni−N−C as an example, multiple characterizations show that the coordinated N on the surface of Ni‐N‐C is almost completely dissolved in the form of NO3−, accompanied by the generation of abundant O functional groups on the surface of the carbon support. Accordingly, the Ni−N bonds are broken. Through a dissolution‐redeposition mechanism and further oxidation, the isolated Ni atoms are finally converted to NiOOH nanoclusters supported by carbon as the real active sites for the enhanced OER. Fe−N−C and Co−N−C also have similar aggregation mechanism. Our findings provide unique insight into the structural evolution and activity origin of M−N−C‐based catalysts under electrooxidative conditions.    

    

* Internal Electric Field Engineering Induced by Co3O4/Bi2MoO6 Nanotubes for Trifunctional Electrocatalytic and Photocatalytic Applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401989955
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-08-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.energyfuels.4c03204")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401989955"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401989955"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401989955"))][Get cited by]]

OpenAlex: https://openalex.org/W4401989955 (Open access: False)
    
[[https://openalex.org/A5059906836][Xinpei Zhao]], [[https://openalex.org/A5101814743][Yukui Zhang]], [[https://openalex.org/A5002638006][Zhihui Shang]], [[https://openalex.org/A5017292276][Qifang Lu]], [[https://openalex.org/A5080449293][Xiujun Han]], [[https://openalex.org/A5102598861][Xue-Yang Ji]], [[https://openalex.org/A5011541826][Huayang Zhang]], Energy & Fuels. None(None)] 2024. https://doi.org/10.1021/acs.energyfuels.4c03204 
     
Electrocatalytic water splitting is an intriguing technique for clean energy production, and engineering heterojunctions with an internal electric field (IEF) can significantly enhance the electrocatalytic performance. In this paper, Co3O4/Bi2MoO6 heterojunction nanotubes have been prepared via electrospinning and calcination and show stronger activity and stability than single-phase Co3O4 and Bi2MoO6 due to the so-called "1 + 1 > 2" synergistic effect induced by IEF. In particular, 1.00Co3O4/Bi2MoO6 nanotube catalyst performed the overpotential toward hydrogen evolution reaction (HER) with 197 mV and oxygen evolution reaction (OER) with 332 mV at 10 mA·cm–2. Based on the enhancement of IEF verified by density functional theory calculation, the extended photocatalytic degradation of tetracycline (TC) showed an efficiency of 68.5% within 200 min under visible light irradiation. This work provides a facile "one stone, three birds' strategy to construct nanotube heterojunctions and develops the IEF mechanism from photocatalytic to electrocatalytic application.    

    

* Dynamics of Highly Active Ln3IrO7 Catalysts for the Oxygen Evolution Reaction in Acid  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402013247
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-08-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202402333")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402013247"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402013247"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402013247"))][Get cited by]]

OpenAlex: https://openalex.org/W4402013247 (Open access: True)
    
[[https://openalex.org/A5027776440][Jane Edgington]], [[https://openalex.org/A5055511531][R. Vicente]], [[https://openalex.org/A5106868026][Sejal Vispute]], [[https://openalex.org/A5014692849][Ruihan Li]], [[https://openalex.org/A5072919330][Matthew E. Sweers]], [[https://openalex.org/A5106868027][Simone R. Sullivan]], [[https://openalex.org/A5101581911][Pablo S. Fernández]], [[https://openalex.org/A5037183181][Linsey C. Seitz]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202402333 
     
Abstract An improved understanding of catalyst dynamics for the oxygen evolution reaction (OER) in acid is critical for informing the development of highly efficient, stable, and cost‐effective OER catalysts for proton exchange membrane water electrolysis applications. Herein highly tunable, active, and dynamic Ir 5+ materials are studied, Ln 3 IrO 7 (Ln = Pr, Nd, Sm, and Eu). Leveraging a combination of in situ and ex situ characterization, as well as an advanced mercury underpotential deposition technique for Ir surface site quantification, the dynamic nature of Ln 3 IrO 7 materials throughout electrochemical activation under OER conditions is characterized. The trends are elucidated between intrinsic OER activity, surface Ir site quantity, and metal site dissolution behavior as tuned by the Ln site's atomic number. A critical relationship is uncovered to show that maintenance of excellent OER activity throughout performance testing is correlated with a catalysts’ ability to preserve a high degree of Ir enrichment, where heightened stability of Ir sites interestingly parallels reduced stability of Ln sites throughout testing. It is found that as the Ln site's atomic number is decreased, the materials’ intrinsic OER performance improves, due to an increased thermodynamic driving force for Ln dissolution, which is hypothesized to enable the maintenance of highly active Ir‐based surface motifs.    

    

* Boosting the electrochemical oxygen evolution performance of CuS by using P element as an anionic dopant  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402036176
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.176166")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402036176"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402036176"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402036176"))][Get cited by]]

OpenAlex: https://openalex.org/W4402036176 (Open access: False)
    
[[https://openalex.org/A5099086169][Xue’er Ming]], [[https://openalex.org/A5077295091][Ning Liu]], [[https://openalex.org/A5100341243][Qi Wang]], [[https://openalex.org/A5014397086][Lefu Mei]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.176166 
     
No abstract    

    

* Record-breaking bifunctional oxygen electrocatalyst accomplished by a data-driven approach for zinc-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402071756
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-08-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.08.040")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402071756"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402071756"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402071756"))][Get cited by]]

OpenAlex: https://openalex.org/W4402071756 (Open access: False)
    
[[https://openalex.org/A5038404835][Deviprasath Chinnadurai]], [[https://openalex.org/A5040683211][Zhi Wei Seh]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.08.040 
     
No abstract    

    

* Recent Advances in Engineering Fe‐N‐C Catalysts for Oxygen Electrocatalysis in Zn‐Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402096056
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401186")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402096056"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402096056"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402096056"))][Get cited by]]

OpenAlex: https://openalex.org/W4402096056 (Open access: False)
    
[[https://openalex.org/A5100450294][Le Li]], [[https://openalex.org/A5075745850][Meisheng Han]], [[https://openalex.org/A5031605616][Penggang Zhang]], [[https://openalex.org/A5021083097][Donglei Yang]], [[https://openalex.org/A5100437682][Meng Zhang]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401186 
     
Fe‐N‐C single‐atom catalysts (SACs) have emerged as one of the most promising candidates for oxygen electrocatalysis due to their maximized atom utilization efficiency, high intrinsic activity, and strong metal‐support interaction. Significant progress has been made in engineering Fe‐N‐C SACs for oxygen electrocatalysis in Zn‐air batteries (ZABs). This review provides a comprehensive overview of the recent advancements in Fe‐N‐C SACs, with a special focus on effective engineering strategies, their performance in oxygen electrocatalysis, and their potential applications in ZABs. The review also discusses the key challenges and future directions in the development of Fe‐N‐C SACs for efficient and durable oxygen electrocatalysis in ZABs. This review aims to offer valuable insights into the current state of research in this field and to guide future efforts in the development of advanced oxygen electrocatalysts for ZABs.    

    

* Fractionation of an oxygen-evolving Photosystem II preparation: characterization of the light-harvesting antennae and reaction center components  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402037878
:TOPICS: Molecular Mechanisms of Photosynthesis and Photoprotection, Optogenetics in Neuroscience and Biophysics Research, Quantum Coherence in Photosynthesis and Aqueous Systems
:PUBLICATION_DATE: 1984-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/s0165-8646(24)00629-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402037878"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402037878"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402037878"))][Get cited by]]

OpenAlex: https://openalex.org/W4402037878 (Open access: True)
    
[[https://openalex.org/A5101555092][Eric Lam]], [[https://openalex.org/A5069283861][Barbara G. Baltimore]], [[https://openalex.org/A5056985522][William Ortiz]], [[https://openalex.org/A5081162006][Richard Malkin]], No host. 7(2)] 1984. https://doi.org/10.1016/s0165-8646(24)00629-9 
     
No abstract    

    

* Study on the Oxygen Evolution Reaction of Zeolite Imidazolide with Cobalt Porphyrin  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401962699
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.12677/japc.2024.133049")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401962699"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401962699"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401962699"))][Get cited by]]

OpenAlex: https://openalex.org/W4401962699 (Open access: False)
    
[[https://openalex.org/A5106803870][腾坤 张]], Journal of Advances in Physical Chemistry. 13(03)] 2024. https://doi.org/10.12677/japc.2024.133049 
     
No abstract    

    

* Individual Marcus-type kinetics controls singlet and triplet oxygen evolution from superoxide  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401955824
:TOPICS: Mitochondrial Dynamics and Reactive Oxygen Species Regulation
:PUBLICATION_DATE: 2024-08-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-3vrzz")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401955824"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401955824"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401955824"))][Get cited by]]

OpenAlex: https://openalex.org/W4401955824 (Open access: True)
    
[[https://openalex.org/A5011902021][Soumyadip Mondal]], [[https://openalex.org/A5100690081][Hung Duc Nguyen]], [[https://openalex.org/A5008738767][Robert Hauschild]], [[https://openalex.org/A5039467561][Stefan A. Freunberger]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-3vrzz  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/66cdf17720ac769e5f047b68/original/individual-marcus-type-kinetics-controls-singlet-and-triplet-oxygen-evolution-from-superoxide.pdf][pdf]])
     
Oxygen evolution from superoxide is a critical aspect of oxygen redox chemistry. However, the factors determining the formation of often harmful singlet oxygen are unclear. Here, we report that the release of triplet or singlet oxygen is governed by individual Marcus normal and inverted region behavior. Using a wide range of chemical oxidants, we found that as the driving force increases, the initially dominant evolution of triplet oxygen slows down, and singlet oxygen evolution becomes predominant with higher maximum kinetics. This behavior also applies to superoxide disproportionation, the oxidation of one superoxide by another, in both non-aqueous and aqueous systems, where Lewis and Brønsted acidity control driving forces. Our findings suggest ways to understand and control spin states and kinetics in oxygen redox chemistry.    

    

* Cholate Extraction of a Heme-Protein from Spinach Thylakoids and its Possible Involvement in PS-II Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402020885
:TOPICS: Molecular Mechanisms of Photosynthesis and Photoprotection, Hemoglobin Function and Regulation in Vertebrates, Dioxygen Activation at Metalloenzyme Active Sites
:PUBLICATION_DATE: 1981-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/s0165-8646(24)00190-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402020885"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402020885"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402020885"))][Get cited by]]

OpenAlex: https://openalex.org/W4402020885 (Open access: True)
    
[[https://openalex.org/A5072018513][H.Y. Nakatani]], [[https://openalex.org/A5084770324][James Barber]], No host. 2(1-2)] 1981. https://doi.org/10.1016/s0165-8646(24)00190-9 
     
No abstract    

    

* "Research Progress on the Electrocatalytic Degradation of Organic Pollutants by PbO2-Based Electrode"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402051867
:TOPICS: On-line Monitoring of Wastewater Quality
:PUBLICATION_DATE: 2024-08-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26717/bjstr.2024.58.009143")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402051867"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402051867"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402051867"))][Get cited by]]

OpenAlex: https://openalex.org/W4402051867 (Open access: True)
    
[[https://openalex.org/A5004773684][Wenlong Liu]], Biomedical Journal of Scientific & Technical Research. 58(3)] 2024. https://doi.org/10.26717/bjstr.2024.58.009143 
     
As an inactive electrode, PbO2-based electrode can produce abundant hydroxyl radicals which are beneficial to the degradation of organic pollutants. In recent years, as a widely used material in electrochemical oxidation technology, more and more PbO2-based electrodes have attracted much attention due to their high oxygen evolution potential, high catalytic activity and good stability. Presently, most of the articles are devoted to the modification of the electrode. To better understand electrochemical degradation of pollutants from waste water, this review summarizes the research progress of wastewater treatment in recent years.    

    

* Growth of trimetallic CeFeNi-MOF-74 on nickel foam as a bifunctional electrocatalyst for water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401887147
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-08-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4815956/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401887147"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401887147"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401887147"))][Get cited by]]

OpenAlex: https://openalex.org/W4401887147 (Open access: True)
    
[[https://openalex.org/A5100400217][Jun Zhang]], [[https://openalex.org/A5100921826][Tao Long]], [[https://openalex.org/A5032844079][Yangwen Liu]], [[https://openalex.org/A5089606871][Zhiyong Zhong]], [[https://openalex.org/A5100354655][Yang Zhang]], [[https://openalex.org/A5039026308][X. H. Chen]], [[https://openalex.org/A5042561352][Guanghuan Li]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4815956/v1  ([[https://www.researchsquare.com/article/rs-4815956/latest.pdf][pdf]])
     
Abstract In order to facilitate the industrial synthesis of hydrogen from electrolytic water on a wide scale, high-performance non-precious metal electrocatalysts that can substitute precious metal electrocatalysts must be developed. This paper reports a trimetallic CeFeNi-MOF-74 electrocatalyst grown on nickel foam (NF) by solvothermal method. The introduction of trimetallics gives the metal-organic frameworks (MOFs) materials synergistic and complementary properties, resulting in better catalytic properties of the materials. Tuning the electronic structure of materials to optimize electrocatalytic performance by modulating metal ratios. It was found that the prepared Ce0.9FeNi-MOF-74 exhibited excellent electrocatalytic activity and stability in the hydrogen evolution reaction (HER) and oxygen evolution reaction (OER). In 1 M KOH, the overpotential is only 262 mV for HER at a current density of 100 mA cm− 2 and 257 mV for OER at a current density of 100 mA cm− 2. For overall water splitting (OWS), a low voltage of only 1.68 V is required to achieve a 10 mA cm− 2 current density. The excellent catalytic performance of Ce0.9FeNi-MOF-74 exceeds that of many commercial catalysts. This study provides new insights into the synthesis of high-performance and stable MOF electrocatalysts.    

    

* Spiral‐concave Prussian Blue Crystals with Rich Steps: Growth Mechanism and Coordination Regulation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402011550
:TOPICS: Photonic Crystals
:PUBLICATION_DATE: 2024-08-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202414650")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402011550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402011550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402011550"))][Get cited by]]

OpenAlex: https://openalex.org/W4402011550 (Open access: False)
    
[[https://openalex.org/A5031896402][Guangxun Zhang]], [[https://openalex.org/A5100454297][Jia Li]], [[https://openalex.org/A5058300395][Guangyu Du]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5102407871][Wang Qiujing]], [[https://openalex.org/A5102304098][Kejian J. Wu]], [[https://openalex.org/A5101844277][Songtao Zhang]], [[https://openalex.org/A5084555578][Han‐Yi Chen]], [[https://openalex.org/A5100643387][Yizhou Zhang]], [[https://openalex.org/A5100294142][Huaiguo Xue]], [[https://openalex.org/A5087437525][Mohsen Shakouri]], [[https://openalex.org/A5067065264][Zheng Liu]], [[https://openalex.org/A5100629513][Huan Pang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202414650 
     
Investigating the formation and transformation mechanisms of spiral‐concave crystals holds significant potential for advancing innovative material design and comprehension. We examined the kinetics‐controlled nucleation and growth mechanisms of Prussian Blue crystals with spiral concave structures, and constructed a detailed crystal growth phase diagram. The spiral‐concave hexacyanoferrate (SC‐HCF) crystals, characterized by high‐density surface steps and a low stress‐strain architecture, exhibit enhanced activity due to their facile interaction with reactants. Notably, the coordination environment of SC‐HCF can be precisely modulated by the introduction of diverse metals. Utilizing X‐ray absorption fine structure spectroscopy and in‐situ ultraviolet‐visible spectroscopy, we elucidated the formation mechanism of SC‐HCF to Co‐HCF facilitated by oriented adsorption‐ion exchange (OA‐IE) process. Both experimental data, and density functional theory confirm that Co‐HCF possesses an optimized energy band structure, capable of adjusting the local electronic environment and enhancing the performance of the oxygen evolution reaction. This work not only elucidates the formation mechanism and coordination regulation for rich steps HCF, but also offers a novel perspective for constructing nanocrystals with intricate spiral‐concave structures.    

    

* Influence of Bi3+ Doping on Electrochemical Properties of Ti/Sb-SnO2/PbO2 Electrode for Zinc Electrowinning  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401909119
:TOPICS: Conducting Polymer Research, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-08-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29174062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401909119"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401909119"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401909119"))][Get cited by]]

OpenAlex: https://openalex.org/W4401909119 (Open access: True)
    
[[https://openalex.org/A5007475662][Jia Wu]], [[https://openalex.org/A5040574228][Xuanqi Kang]], [[https://openalex.org/A5051971312][Shuang Xu]], [[https://openalex.org/A5101629742][Zhen Wei]], [[https://openalex.org/A5102289060][Shangyuan Xu]], [[https://openalex.org/A5100389906][Kang Liu]], [[https://openalex.org/A5054287192][Qing Feng]], [[https://openalex.org/A5020033792][Bo Jia]], [[https://openalex.org/A5068754949][Yun‐Hai Wang]], Molecules. 29(17)] 2024. https://doi.org/10.3390/molecules29174062  ([[https://www.mdpi.com/1420-3049/29/17/4062/pdf?version=1724772214][pdf]])
     
Bi3+ doped Ti/Sb-SnO2/PbO2 electrode materials were fabricated by electrodeposition to improve their electrochemical performance in zinc electrowinning. The surface morphology, chemical composition, and hydrophilicity of the as-prepared electrodes were characterized using scanning electron microscopy (SEM), energy dispersive X-ray spectroscopy (EDS), X-ray diffraction (XRD), X-ray photoelectron spectroscopy (XPS), and contact angle. An electrochemical measurement and an accelerated lifetime experiment were also conducted to investigate the electrocatalytic performance and stability of the electrodes. The results show that the Bi3+ modification electrode has an important effect on the coating morphology, the crystal structure, the surface hydrophilicity, the electrocatalytic activity, and the stability. The electrode prepared from the solution containing 2 mmol·L−1 Bi(NO3)3 (marked as the Ti/Sb-SnO2/2Bi-PbO2 electrode) exhibits the best hydrophilicity performance (θ = 21.6°) and the longest service life (1196 h). During the electrochemical characterization analysis, the Ti/Sb-SnO2/2Bi-PbO2 electrode showed the highest oxygen evolution activity, which can be attributed to it having the highest electroactive surface (qT* = 21.20 C·cm−2) and the best charge-transfer efficiency. The DFT calculation demonstrated that the doping of Bi3+ leads to a decrease in the OER reaction barrier and an increase in the DOS of the electrode, which further enhances the catalytic activity and the conductivity of the electrode. Moreover, the simulated zinc electrowinning experiment demonstrated that the Ti/Sb-SnO2/2Bi-PbO2 electrode consumes less energy than other electrodes. Therefore, it is expected that the Bi3+ modified electrode will become a very promising electrode material for zinc electrowinning in the future.    

    

* Preliminary Verification of Key Physical Models in Oxide Fuel Performance Analysis Code FEATURE Based on COMSOL  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402077524
:TOPICS: Nuclear Fuel Development, Nuclear Reactor Technology and Development, Nuclear Thermal Hydraulics in Passive Systems
:PUBLICATION_DATE: 2024-08-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1080/00295639.2024.2384225")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402077524"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402077524"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402077524"))][Get cited by]]

OpenAlex: https://openalex.org/W4402077524 (Open access: False)
    
[[https://openalex.org/A5049675369][Rui Yu]], [[https://openalex.org/A5100325267][Guan Wang]], [[https://openalex.org/A5040433090][Wei Jiang]], [[https://openalex.org/A5102184839][Yanlei Zhu]], [[https://openalex.org/A5066618090][Changping Qin]], [[https://openalex.org/A5085671271][Long Gu]], Nuclear Science and Engineering. None(None)] 2024. https://doi.org/10.1080/00295639.2024.2384225 
     
Nuclear performance analysis is of great significance for fuel design optimization and the safe operation of a reactor. Considering the design requirements of the China initiative Accelerator Driven System (CiADS) project, it is necessary to develop relevant fuel performance analysis tools to predict fuel performance evolution during service. The Fuel Element Analysis Tool for Undercritical Reactor Engineering (FEATURE) code, based on the advanced multiphysics coupling platform COMSOL software, is under development in this context, with a current focus on oxide fuel for fast reactors. This paper mainly conducts preliminary comparative verification of the oxygen redistribution, plutonium redistribution, and fission gas release modules of the FEATURE code through model examples, code-to-code evaluation, and experimental data. The results indicate that the FEATURE code exhibits good accuracy and reliability in simulating oxygen and plutonium redistribution, as well as fission gas release, making it suitable for integrated coupling calculations.    

    

* Oxidation behavior of SiC‐AlN ceramics exposed to dry oxygen and water oxygen environments at 1100–1300°C  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401864334
:TOPICS: Ceramic Materials and Processing, Atomic Layer Deposition Technology, Magnesium-Based Cements and Nanomaterials
:PUBLICATION_DATE: 2024-08-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/ijac.14903")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401864334"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401864334"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401864334"))][Get cited by]]

OpenAlex: https://openalex.org/W4401864334 (Open access: False)
    
[[https://openalex.org/A5054367652][Xiaofan Sun]], [[https://openalex.org/A5101579467][Xiao‐Wu Chen]], [[https://openalex.org/A5101566622][Min Tan]], [[https://openalex.org/A5056227887][Yanmei Kan]], [[https://openalex.org/A5102204437][Xihai Jin]], [[https://openalex.org/A5100422411][Zhen Wang]], [[https://openalex.org/A5100394072][Haibo Liu]], [[https://openalex.org/A5061597448][Jianbao Hu]], [[https://openalex.org/A5019973164][Jinshan Yang]], [[https://openalex.org/A5023781669][Shaoming Dong]], International Journal of Applied Ceramic Technology. None(None)] 2024. https://doi.org/10.1111/ijac.14903 
     
Abstract The corrosion of SiC f /SiC composites in gas environment threatens their long‐term service in aeroengines as hot‐end structure components. Addition of corrosion‐resistant phases into SiC matrix is a potential strategy to improve the service performance of SiC f /SiC materials. Here, AlN added SiC ceramics were prepared by reactive melt infiltration, and the effect of AlN phase on the oxidation resistance of the ceramics was emphasized. The oxidation tests were performed in dry oxygen and water oxygen atmospheres at 1100°C–1300°C, respectively. The oxidation mechanism was discussed based on the microstructure evolution of the oxide layer. The results show that the oxide layer is composed of aluminum silicate glass and Al 2 O 3 flakes dispersedly distributed in the glass phase. As the temperature rises, the oxide layer gradually grows and thickens. Finally, a smooth and dense protective layer could be formed on the surface of ceramics to resist oxidation. This study can provide a profound insight to construct SiC f /SiC composites with excellent oxidation resistance.    

    

* Interfacial Lattice Strain‐Induced Vacancy Evolution Facilitating Highly Reversible Dendrite‐Free Zinc Metal Anodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401969660
:TOPICS: Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-08-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202402586")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401969660"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401969660"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401969660"))][Get cited by]]

OpenAlex: https://openalex.org/W4401969660 (Open access: True)
    
[[https://openalex.org/A5100428408][Tian Wang]], [[https://openalex.org/A5101978720][Liangliang Xu]], [[https://openalex.org/A5026556999][Weiwei Xiang]], [[https://openalex.org/A5061338573][Shaocong Tang]], [[https://openalex.org/A5101848805][Ya Xiao]], [[https://openalex.org/A5103079949][Jae Su Yu]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202402586 
     
Abstract Interfacial stress caused by semi‐coherent and incoherent interfaces during zinc (Zn) plating and its effect on subsequent Zn deposition are important considerations for designing electrode/electrolyte interfaces to improve the electrochemical performance of Zn anodes. Although some studies have paid attention to this issue, the influence of lattice strain induced by Zn ion diffusion in the interface coating on Zn deposition is infrequently discussed. Herein, a tin‐doped indium oxide (ITO) interfacial is constructed, and the evolution of interfacial lattice oxygen to vacancy oxygen (O V ) induced by lattice stress generated by Zn ion migration in the interface during Zn deposition is confirmed. The formed O V ‐rich ITO interface exhibits strong affinity and a low Zn ion diffusion barrier, accelerating the Zn ion transport kinetics. Meanwhile, the interface layer can appropriately capture anions in the electrolyte and improve the corrosion resistance of the electrode through the electrostatic repulsion effect. As a result, the O V ‐rich ITO‐decorated Zn anode achieves stable Zn plating/stripping for more than 4500 h and delivers a high average Coulombic efficiency of 99.6% after 1400 cycles at 1.0 mA cm −2 . This work provides a new horizon for the rational construction of the interface layer to achieve a highly reversible dendrite‐free Zn metal anode.    

    

* Nebulized enriched heparin improves respiratory parameters in patients with COVID-19: a phase I/II randomized and triple-blind clinical trial  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401900049
:TOPICS: Coronavirus Disease 2019, Neurological Manifestations of COVID-19 Infection, Mechanical Ventilation in Respiratory Failure and ARDS
:PUBLICATION_DATE: 2024-08-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41598-024-70064-8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401900049"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401900049"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401900049"))][Get cited by]]

OpenAlex: https://openalex.org/W4401900049 (Open access: True)
    
[[https://openalex.org/A5065479327][Vinicius Tadeu Ramos da Silva Grillo]], [[https://openalex.org/A5028435018][Matheus Bertanha]], [[https://openalex.org/A5068110827][Lenize da Silva Rodrigues]], [[https://openalex.org/A5053197776][Marcelo Andrade de Lima]], [[https://openalex.org/A5000476219][Pedro Luciano Mellucci Filho]], [[https://openalex.org/A5089936584][Rafael Rahal Guaragna Machado]], [[https://openalex.org/A5024090944][Edison Luíz Durigon]], [[https://openalex.org/A5050454549][Nathália Dias Sertório]], [[https://openalex.org/A5082916266][Márjorie de Assis Golim]], [[https://openalex.org/A5025585267][Andrei Moroz]], [[https://openalex.org/A5068368009][Aline Márcia Marques Braz]], [[https://openalex.org/A5026849297][Leonardo Nazário de Moraes]], [[https://openalex.org/A5102019441][Marco Antônio Leite]], [[https://openalex.org/A5087235862][Helena B. Nader]], [[https://openalex.org/A5031611400][Gustavo Constantino de Campos]], [[https://openalex.org/A5044165661][Cristiane Rodrigues Guzzo]], [[https://openalex.org/A5016141294][Fábio Florença Cardoso]], [[https://openalex.org/A5023945612][Ângelo J. Magro]], [[https://openalex.org/A5045981988][Helga Caputo Nunes]], [[https://openalex.org/A5018202329][Rejane Maria Tommasini Grotto]], [[https://openalex.org/A5035022859][Rita de Cássia Alvarado]], [[https://openalex.org/A5045451934][Maria Inês de Moura Campos Pardini]], [[https://openalex.org/A5050555958][Marcone Lima Sobreira]], [[https://openalex.org/A5038100122][Érika Alessandra Pellison Nunes da Costa]], [[https://openalex.org/A5007167507][Alexandre Naime Barbosa]], [[https://openalex.org/A5085857830][Carlos Magno Castelo Branco Fortaleza]], Scientific Reports. 14(1)] 2024. https://doi.org/10.1038/s41598-024-70064-8 
     
To evaluate the safety and the potential antiviral treatment of inhaled enriched heparin in patients with COVID-19. The specific objectives were to investigate the anticoagulation profile, antiviral and anti-inflammatory effects, and respiratory evolution of inhaled enriched heparin. We conducted a randomized, triple-blind, placebo-controlled Phase I/II clinical trial in hospitalized adults with COVID-19 receiving inhalation of enriched heparin or saline (placebo) every 4 h for 7 days. Among the 27 patients who completed the study, no changes in blood coagulation parameters were observed, indicating the safety of inhaled enriched heparin. The group receiving enriched heparin showed a significant reduction in the need for supplemental oxygen and improvement in respiratory parameters, such as the PaO2/FiO2 ratio. Inhalation of enriched heparin is shown to be safe and has also demonstrated potential therapeutic benefits for patients with COVID-19. These promising results justify the continuation of the study to the next phase, Phase II/III, to further evaluate the therapeutic efficacy of inhaled enriched heparin in the treatment of COVID-19-associated viral pneumonia. Trial registration: ClinicalTrials.gov. 08/02/2021. Identifier: NCT04743011.    

    

* Diagnosis and mitigation of the systemic impact of genome reduction in Escherichia coli DGF-298  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402001164
:TOPICS: Metabolic Engineering and Synthetic Biology, Technologies for Biofuel Production from Biomass, Bacterial Physiology and Genetics
:PUBLICATION_DATE: 2024-08-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1128/mbio.00873-24")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402001164"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402001164"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402001164"))][Get cited by]]

OpenAlex: https://openalex.org/W4402001164 (Open access: True)
    
[[https://openalex.org/A5028264325][Antoine Champie]], [[https://openalex.org/A5035981186][Jean‐Christophe Lachance]], [[https://openalex.org/A5103003297][Anand Sastry]], [[https://openalex.org/A5024732561][Dominick Matteau]], [[https://openalex.org/A5008123229][Colton J. Lloyd]], [[https://openalex.org/A5072279874][Frédéric Grenier]], [[https://openalex.org/A5012946533][Cameron Lamoureux]], [[https://openalex.org/A5085160317][Simon Jeanneau]], [[https://openalex.org/A5062042072][Adam M. Feist]], [[https://openalex.org/A5007050002][Pierre‐Étienne Jacques]], [[https://openalex.org/A5051097609][Bernhard Ø. Palsson]], [[https://openalex.org/A5074451072][Sébastien Rodrigue]], mBio. None(None)] 2024. https://doi.org/10.1128/mbio.00873-24 
     
ABSTRACT Microorganisms with simplified genomes represent interesting cell chassis for systems and synthetic biology. However, genome reduction can lead to undesired traits, such as decreased growth rate and metabolic imbalances. To investigate the impact of genome reduction on Escherichia coli strain DGF-298, a strain in which ~ 36% of the genome has been removed, we reconstructed a strain-specific metabolic model ( i AC1061), investigated the regulation of gene expression using iModulon-based transcriptome analysis, and performed adaptive laboratory evolution to let the strain correct potential imbalances that arose during its simplification. The model notably predicted that the removal of all three key pathways for glycolaldehyde disposal in this microorganism would lead to a metabolic bottleneck through folate starvation. Glycolaldehyde is also known to cause self-generation of reactive oxygen species, as evidenced by the increased expression of oxidative stress resistance genes in the SoxS iModulon. The reintroduction of the aldA gene, responsible for one native glycolaldehyde disposal route, alleviated the constitutive oxidative stress response. Our results suggest that systems-level approaches and adaptive laboratory evolution have additive benefits when trying to repair and optimize genome-engineered strains. IMPORTANCE Genomic streamlining can be employed in model organisms to reduce complexity and enhance strain predictability. One of the most striking examples is the bacterial strain Escherichia coli DGF-298, notable for having over one-third of its genome deleted. However, such extensive genome modifications raise the question of how similar this simplified cell remains when compared with its parent, and what are the possible unintended consequences of this simplification. In this study, we used metabolic modeling along with iModulon-based transcriptomic analysis in different growth conditions to assess the impact of genome reduction on metabolism and gene regulation. We observed little impact of genomic reduction on the regulatory network of E. coli DGF-298 and identified a potential metabolic bottleneck leading to the constitutive activity of the SoxS iModulon. We then leveraged the model's predictions to successfully restore SoxS activity to the basal level.    

    

* The Impact of Antioxidant-Ciprofloxacin Combinations on the Evolution of Antibiotic Resistance in Pseudomonas aeruginosa Biofilms  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401881589
:TOPICS: Bacterial Biofilms and Quorum Sensing Mechanisms, Global Challenge of Antibiotic Resistance in Bacteria, Antibiotic Resistance in Aquatic Environments and Wastewater
:PUBLICATION_DATE: 2024-08-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4756544/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401881589"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401881589"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401881589"))][Get cited by]]

OpenAlex: https://openalex.org/W4401881589 (Open access: True)
    
[[https://openalex.org/A5009112406][Oana Ciofu]], [[https://openalex.org/A5035109855][Doaa Higazy]], [[https://openalex.org/A5076397036][Marwa Ahmed]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4756544/v1  ([[https://www.researchsquare.com/article/rs-4756544/latest.pdf][pdf]])
     
Abstract Antibiotic resistance in biofilms is a critical challenge driven by mechanisms such as increased oxidative stress, which could lead to enhanced mutagenesis. Experimental evolution studies have shown that biofilm growth fosters antimicrobial resistance and tolerance. The bactericidal antibiotic ciprofloxacin (CIP) exacerbates oxidative stress, enhancing reactive oxygen species (ROS) production and mutagenesis at sub-inhibitory concentrations. This study tests the hypothesis that antioxidants (AOs) such as N-acetyl-cysteine (NAC), and Edaravone (ED) could serve as anti-evolutionary drugs to prevent or reduce antimicrobial resistance in P. aeruginosa biofilms exposed to sub-inhibitory concentrations of ciprofloxacin (CIP), with Thiourea (THU) used as a control. In vitro experimental evolution studies using the monitor strain PAO1-mCherry-PCD-gfp + were conducted in flow cells and glass beads biofilm models. The harvested biofilm populations underwent population analysis and the flow-cell populations were also whole genome sequenced (WGS). The results showed that the CIP-AO combination of CIP-THU could reduce the fast increase of mutagenic resistance in both biofilm models. The confocal laser microscopy of flow cells biofilms showed a reduction in the percentage of nfxB mutants in biofilms treated with all the three CIP-AO combinations compared to the CIP treatment alone following 24h of treatment. The population analysis revealed a significant reduction of the subpopulations growing on 0.5 mg/L of CIP-supplemented plates in all the combined treatments of CIP-AO as compared to CIP populations. The WGS results showed CIP-specific mutants in the CIP-treated populations including nfxB and nalC mutations which were not observed in CIP-AO-treated ones. Flagellar gene mutations appeared in CIP-ED (fliG) and CIP-NAC (flhA) treatments. Additionally, wspA, which regulates biofilm formation, had a transversion mutation in CIP-ED and a deletion mutation in CIP-NAC. The minimum inhibitory concentrations (MICs) level for CIP-treated isolates was significantly higher than all isolates from CIP-AO treatments in both tested biofilm models of flow cells and glass beads. Overall, these findings suggest that the two clinical antioxidants may have a potential role in mitigating the development of antibiotic resistance in biofilms.    

    

* The Banská Štiavnica ore district  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401944450
:TOPICS: Tectonic Evolution of Carpathian-Pannonian Region
:PUBLICATION_DATE: 1999-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5382/gb.31.09")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401944450"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401944450"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401944450"))][Get cited by]]

OpenAlex: https://openalex.org/W4401944450 (Open access: False)
    
[[https://openalex.org/A5087333317][Jaroslav Lexa]], [[https://openalex.org/A5087892160][J. Štohl]], [[https://openalex.org/A5090805360][Vlastimil Konečný]], No host. None(None)] 1999. https://doi.org/10.5382/gb.31.09 
     
Abstract The Banská Štiavnica ore district is in the central zone of the largest stratovolcano in the Central Slovakia Neogene Volcanic Field, which is situated at the inner side of the Carpathian arc over the Hercynian basement with the Late Paleozoic and Mesozoic sedimentary cover. Volcanic rocks of the High-K orogenic suite are of the Badenian through Pannonian age (16.5– 8.5 Ma). Their petrogenesis is closely related to subduction of flysch belt oceanic basement underneath the advancing Carpathian arc and to back-arc extension processes. The stratovolcano includes a large caldera 20 km in diameter and a late-stage resurgent horst in its centre, exposing a basement and extensive subvolcanic intrusive complex. The following stages have been recognized in the evolution of the stratovolcano: (1) formation of a large pyroxene/hornblende-pyroxene andesite stratovolcano; (2) denudation, emplacement of a diorite intrusion; (3) emplacement of a large granodiorite bell-jar pluton within the basement; (4) emplacement of granodiorite/quartz-diorite porphyry stocks and dyke clusters around the pluton; (5) caldera subsidence and its filling by biotite-hornblende andesite volcanics, emplacement of quartz-diorite porphyry sills and dykes at the subvolcanic level; (6) renewed activity of andesites from dispersed centres on slopes of the volcano; (7) uplift of a resurgent horst accompanied by rhyolite volcanics and granite porphyry dykes. The following types of ore deposits (mineralizations) have been identified in the Banská Štiavnica ore district: 1. Quartz-pyrophyllite-pyrite high-sulphidation system at Šobov, related to the diorite intrusion. 2. Magnetite skarn deposits and occurrences at contacts of the granodiorite pluton with Mesozoic carbonate rocks. Magnetite ores occur as lenses in the calcic skarns. 3. Stockwork/disseminated base metal deposit along an irregular network of fractures in apical parts of the granodiorite pluton and in remnants of basement rocks. Mineral paragenesis is simple, with leading sphalerite and galena and minor chalcopyrite and pyrite. In overlying andesites the mineralization is accompanied by metasomatic quartzites and argillites with pyrophyllite, kaolinite, illite and pyrite. 4. Porphyry /skarn copper deposits and occurrences related to granodiorite/quartz-diorite porphyry dyke clusters and stocks around the granodiorite intrusion. The mineralized zone is represented by accumulations of chalcopyrite in exo- and endo-skarns, usually of the magnesian type affected by serpentinization. Besides chalcopyrite, pyrhotite, minor bornite, chalcosite, tennantite and magnetite, rare molybdenite and gold are present. The alteration pattern around productive intrusions includes an external zone of propylitization, a zone of argillitic alteration (kaolinite — illite — pyrite) and an internal zone of phyllic alteration (quartz — sericite — pyrite). Biotitization is rare and limited to porphyry intrusions. 5. Intrusion related “mesothermal” gold deposit in an andesitic environment just above the granodiorite intrusion. Gold of high fineness with base metal mineralization is contained in brecciated and/or banded quartz veins of subhorizontal orientation, parallel to the surface of granodiorite pluton. At least the first phase of mineralization is older than quartz-diorite porphyry sills, which separate granodiorite and blocks of mineralized andesite. 6. Hot spring type advanced argillic systems in the caldera filling. Silicites and opalites accompanied by kaolinite, alunite and pyrite grade downward into smectite dominated argillites. 7. Vein type epithermal precious/base metal deposits and occurrences as a result of the long lasting interaction among structural evolution of the resurgent horst and evolving hydrothermal system, extensive intrusive complex and deep seated siliceous magma chamber serving as heat and magmatic fluid source. Three types of epithermal veins occur in a zonal arrangement: (a) base metal veins ± Au with transition to Cu ± Bi mineralization at depth in the east/central part of the horst, (b) Ag — Au veins with minor base metal mineralization and (c) Au — Ag veins located at marginal faults of the horst. Isotopic composition of oxygen and hydrogen in hydrothermal fluids indicate mixing of magmatic and meteoric component (with generally increasing proportion of meteoric component towards younger mineralization periods?). Veins are accompanied by zones of silicification, adularization and sericitization, indicating a low sulphidation environment. 8. Replacement base metal mineralization of a limited extent in the Mesozoic carbonate rocks next to sulphide rich epithermal base metal veins.    

    
