#+TITLE: water splitting
Description: water splitting papers
Created on Thu Mar  7 00:35:35 2024

Found 42 results from 2024-02-29 to 2024-03-07
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Atomic layer deposition for tuning the surface chemical composition of nickel iron phosphates for oxygen evolution reaction in alkaline electrolyzers  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392229456
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-02-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6528/ad2e48")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392229456"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392229456"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392229456"))][Get cited by]]

OpenAlex: https://openalex.org/W4392229456 (Open access: False)
    
[[https://openalex.org/A5010858255][Ruben Blomme]], [[https://openalex.org/A5077670292][R. Ramesh]], [[https://openalex.org/A5065960121][Lowie Henderick]], [[https://openalex.org/A5088374919][Matthias Minjauw]], [[https://openalex.org/A5070258112][Philippe M. Vereecken]], [[https://openalex.org/A5034963096][Mieke Adriaens]], [[https://openalex.org/A5039168166][Christophe Detavernier]], [[https://openalex.org/A5081161746][Jolien Dendooven]], Nanotechnology. None(None)] 2024. https://doi.org/10.1088/1361-6528/ad2e48 
     
Abstract Transition metal phosphates are promising catalysts for the oxygen evolution reaction (OER) in alkaline medium. Herein, Fe-doped Ni phosphates are deposited using plasma-enhanced atomic layer deposition (PE-ALD) at 300°C. A sequence of f Fe phosphate PE-ALD cycles and n Ni phosphate PE-ALD cycles is repeated x times. The Fe to Ni ratio can be controlled by the cycle ratio (f /n), while the film thickness can be controlled by the number of cycles (x times (n+f )). 30 nm films with an Fe/Ni ratio of ∼10% and ∼37%, respectively, are evaluated in 1.0 M KOH solution. Remarkably, a significant difference in OER activity is found when the order of the Ni and Fe phosphate PE-ALD cycles in the deposition sequence is reversed. A 20 to 45% larger current density is obtained for catalysts grown with an Fe phosphate PE-ALD cycle at the end compared to the Ni phosphate-terminated flavour. We attribute this to a higher concentration of Fe centers on the surface, as a consequence of the specific PE-ALD approach. Secondly, increasing the thickness of the catalyst films up to 160 nm results in an increase of the OER current density and active surface area, suggesting that the as-deposited smooth and continuous films are converted into electrolyte-permeable structures during catalyst activation and operation. This work demonstrates the ability of PE-ALD to control both the surface and bulk composition of thin film electrocatalysts, offering valuable opportunities to understand their impact on performance.    

    

* Structural reconstruction of cobalt and ferrocene-based metal-organic framework during electrochemical oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392232800
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-vlqz5-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392232800"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392232800"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392232800"))][Get cited by]]

OpenAlex: https://openalex.org/W4392232800 (Open access: True)
    
[[https://openalex.org/A5071440495][Thomas Doughty]], [[https://openalex.org/A5094005131][Andrea Zingl]], [[https://openalex.org/A5070524825][Maximilian Wünschek]], [[https://openalex.org/A5035468865][Christian M. Pichler]], [[https://openalex.org/A5006409298][Matthew Watkins]], [[https://openalex.org/A5019861460][Souvik Roy]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-vlqz5-v2  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65df1f219138d231613a89d6/original/structural-reconstruction-of-cobalt-and-ferrocene-based-metal-organic-framework-during-electrochemical-oxygen-evolution-reaction.pdf][pdf]])
     
Metal-organic frameworks (MOFs) are increasingly being investigated as electrocatalysts for oxygen evolution reaction (OER) due to their unique modular structures that present a hybrid between molecular and heterogeneous catalysts, featuring well-defined active sites. However, many fundamental questions remain open regarding the electrochemical stability of MOFs, structural reconstruction of coordination sites, and the role of in situ-formed species. Here we report structural transformation of a surface-grown MOF containing cobalt nodes and 1,1’-ferrocenedicarboxylic acid linkers (denoted as CoFc-MOF) during OER in alkaline electrolyte. Ex situ and in situ investigations of CoFc-MOF film suggests that the MOF acts as a pre-catalyst and undergoes a two-step restructuring process under operating conditions to generate a metal oxyhydroxide phase. The MOF-derived metal oxyhydroxide catalyst, supported on nickel foam electrodes, displays high activity towards OER with an overpotential of 190 mV at a current density of 10 mA cm–2. While this study demonstrates the necessity of investigating structural evolution of MOFs in electrocatalysis, it also shows potential of using MOFs as precursors in catalyst design.    

    

* Engineered 2D materials for oxygen evolution reaction (OER)  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392233924
:TOPICS: Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/978-0-7503-5719-7ch4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392233924"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392233924"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392233924"))][Get cited by]]

OpenAlex: https://openalex.org/W4392233924 (Open access: False)
    
[[https://openalex.org/A5062412552][Pratik V. Shinde]], [[https://openalex.org/A5055593216][Komal Patil]], [[https://openalex.org/A5074386798][Vitthal M Shinde]], [[https://openalex.org/A5060818209][Chandra Sekhar Rout]], IOP Publishing eBooks. None(None)] 2024. https://doi.org/10.1088/978-0-7503-5719-7ch4 
     
No abstract    

    

* Synthesis of MFe2O4 (M=Ni, Co) Nanoparticles by a Bicontinuous Microemulsion Method for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392235702
:TOPICS: Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials, Zeolite Chemistry and Catalysis
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cnma.202300541")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392235702"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392235702"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392235702"))][Get cited by]]

OpenAlex: https://openalex.org/W4392235702 (Open access: False)
    
[[https://openalex.org/A5094020393][Faiz Sultan]], [[https://openalex.org/A5094020394][Guillermo E. González Sepúlveda]], [[https://openalex.org/A5063694239][Dora I. Medina]], [[https://openalex.org/A5055217273][Marcelo Videa]], [[https://openalex.org/A5075165551][Margarita Sánchez-Domínguez]], [[https://openalex.org/A5049785621][Jorge L. Cholula-Díaz]], ChemNanoMat. None(None)] 2024. https://doi.org/10.1002/cnma.202300541 
     
Developing efficient and low‐cost electrocatalysts for the oxygen evolution reaction (OER) is crucial for sustainable hydrogen production through water splitting. In this study, CoFe2O4 and NiFe2O4 nanoparticles as electrocatalysts were prepared via an inexpensive method involving the use of bicontinuous microemulsions as nanoreactors. The crystalline structure, morphology, and elemental composition of the electrocatalysts were characterized by XRD, Raman spectroscopy, TEM, and EDS. The electronic structure and textural properties were examined by using XPS and the nitrogen adsorption‐desorption method. The OER measurements were carried out in a standard three‐electrode system. CoFe2O4 demonstrated relatively higher OER catalytic activity than NiFe2O4 in 1M KOH solution, with a smaller overpotential of 410 mV to achieve a current density of 10 mA cm‐2 and a smaller Tafe slope of 80 mV dec‐1. In contrast, NiFe2O4 offered a higher overpotential of 450 mV to reach the same current density. The superior performance of CoFe2O4 is ascribed to higher ECSA, better conductivity, and lower charge transfer resistance. However, both electrocatalysts showed stability up to more than three hours of continuous performance.    

    

* Continuous strain tuning of oxygen evolution catalysts with anisotropic thermal expansion  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392238969
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-46216-9")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392238969"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392238969"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392238969"))][Get cited by]]

OpenAlex: https://openalex.org/W4392238969 (Open access: True)
    
[[https://openalex.org/A5085393847][Yu Du]], [[https://openalex.org/A5019030186][Feng Xie]], [[https://openalex.org/A5060340002][Mengfei Lu]], [[https://openalex.org/A5016734293][Ruitao Lv]], [[https://openalex.org/A5006328423][Wangxi Liu]], [[https://openalex.org/A5064109221][Yuandong Yan]], [[https://openalex.org/A5013461643][Shicheng Yan]], [[https://openalex.org/A5018143125][Zhigang Zou]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-46216-9  ([[https://www.nature.com/articles/s41467-024-46216-9.pdf][pdf]])
     
Abstract Compressive strain, downshifting the d -band center of transition metal oxides, is an effective way to accelerate the sluggish kinetics of oxygen evolution reaction (OER) for water electrolysis. Here, we find that anisotropic thermal expansion can produce compressive strains of the IrO 6 octahedron in Sr 2 IrO 4 catalyst, thus downshifting its d- band center. Different from the previous strategies to create constant strains in the crystals, the thermal-triggered compressive strains can be real-timely tuned by varying temperature. As a result of the thermal strain accelerating OER kinetics, the Sr 2 IrO 4 exhibits the nonlinear ln j o - T −1 ( j o , exchange current density; T , absolute temperature) Arrhenius relationship, resulting from the thermally induced low-barrier electron transfer in the presence of thermal compressive strains. Our results verify that the thermal field can be utilized to manipulate the electronic states of Sr 2 IrO 4 via thermal compressive strains downshifting the d -band center, significantly accelerating the OER kinetics, beyond the traditional thermal diffusion effects.    

    

* Synthesis of graphene/Ru/NiO composites as highly active oxygen evolution reaction electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392245399
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.136230")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392245399"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392245399"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392245399"))][Get cited by]]

OpenAlex: https://openalex.org/W4392245399 (Open access: False)
    
[[https://openalex.org/A5016801402][Qizhe Ji]], [[https://openalex.org/A5056735222][Luyan Li]], [[https://openalex.org/A5046824126][Song Yang]], [[https://openalex.org/A5046867711][Chang Ming Li]], [[https://openalex.org/A5006375563][Xi Zhou]], [[https://openalex.org/A5008435796][Zhenghua Yang]], [[https://openalex.org/A5028508059][Sen Zhang]], [[https://openalex.org/A5061544261][Xianglong Zhao]], [[https://openalex.org/A5064124661][Feiyong Chen]], Materials Letters. None(None)] 2024. https://doi.org/10.1016/j.matlet.2024.136230 
     
Graphene nanoplates which are decorated uniformly with ruthenium (Ru) and nickel oxide (NiO) nanoparticles, are fabricated via ball milling of graphite, triphenylphosphine ruthenium chlorides and nickel chlorides. Electrochemical measurement results demonstrate that the resultant graphene/Ru/NiO composites deliver a lower overpotential of 240 mV at current density of 10 mA cm−2 and better durability for oxygen evolution reaction (OER) than the state-of-the-art iridium oxide catalysts. The superior OER performances of the graphene/Ru/NiO composites are attributed to collective contributions of Ru and NiO.    

    

* Activating lattice oxygen based on energy band engineering in oxides for industrial water/saline oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392249967
:TOPICS: Advances in Chemical Sensor Technologies, Atomic Layer Deposition Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ee00214h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392249967"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392249967"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392249967"))][Get cited by]]

OpenAlex: https://openalex.org/W4392249967 (Open access: False)
    
[[https://openalex.org/A5005349597][Yijie Zhang]], [[https://openalex.org/A5058215602][Weiyi Zhang]], [[https://openalex.org/A5028009429][Xiaowen Zhang]], [[https://openalex.org/A5026769100][Xinlong Wang]], [[https://openalex.org/A5015378757][Jiajun Wang]], [[https://openalex.org/A5061998264][Qiang Zhao]], [[https://openalex.org/A5086718326][Yuhan Sun]], [[https://openalex.org/A5001998362][Jinping Li]], [[https://openalex.org/A5012841530][Guang Liu]], [[https://openalex.org/A5025874763][Xiaopeng Han]], Energy and Environmental Science. None(None)] 2024. https://doi.org/10.1039/d4ee00214h 
     
Lattice-oxygen oxidation mechanism can bypass certain limitations in the adsorbate evolution mechanism to lower the energy barrier. Herein, we propose to regulate energy band levels by introducing Fe and F-stabilized...    

    

* In situ formed ZIF-67 derived NiFeCo-P nano-array for accelerating electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392250889
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ya00581j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392250889"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392250889"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392250889"))][Get cited by]]

OpenAlex: https://openalex.org/W4392250889 (Open access: True)
    
[[https://openalex.org/A5088927183][Xiaolong Guo]], [[https://openalex.org/A5076495171][Lipeng Zhang]], [[https://openalex.org/A5009414213][Shuo Wang]], [[https://openalex.org/A5046483460][Huan Zhang]], [[https://openalex.org/A5050928295][Yafei Kuang]], [[https://openalex.org/A5016047921][Guo Xing Duan]], [[https://openalex.org/A5048761022][Bingqiang Cao]], Energy advances. None(None)] 2024. https://doi.org/10.1039/d3ya00581j  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ya/d3ya00581j][pdf]])
     
In-situ growth of nano-array on substrate materials is a neoteric and efficacious catalyst design strategy, but it is still a difficulty to prepare unique nano-structured electrocatalysts with excellent activity for...    

    

* Intensified effect of phosphorus doping to La-Fe-O perovskite-type oxygen carrier in microalgae chemical looping gasification for enhanced syngas production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392266505
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Chemical-Looping Technologies
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131345")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392266505"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392266505"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392266505"))][Get cited by]]

OpenAlex: https://openalex.org/W4392266505 (Open access: False)
    
[[https://openalex.org/A5001168394][Jingchun Yan]], [[https://openalex.org/A5044495947][Changwei Shi]], [[https://openalex.org/A5003395657][Yan Shen]], [[https://openalex.org/A5034229182][Junjie Lai]], [[https://openalex.org/A5064158352][Yongbo Yan]], [[https://openalex.org/A5079144123][Lulu Wang]], [[https://openalex.org/A5048681849][Zhong Ma]], [[https://openalex.org/A5036881995][Li Yang]], Fuel. 366(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131345 
     
Chemical looping gasification (CLG) with perovskite-type oxygen carriers has been gaining an increasing interest for efficient and clean utilization of biomass resources. Compared with conventional metal-doping method, the incorporation of non-metallic element in perovskite has advantages in reactivity and cost. Herein, a novel phosphorus doping strategy was applied to enhance the reactivity of LaFeO3 for microalgae CLG. Comprehensive studies including kinetic analysis, thermodynamic investigation and gaseous products evaluation were carried out via TG-FTIR-MS method. TG results showed the enhanced CLG performance over LaFe1-xPxO3 oxygen carriers. Specifically, CLG with LaFe0.99P0.01O3 (LFP1) gained the largest pre-exponential factor of 4.38 × 1033 s−1 and average ΔS value of −8.8 J·mol−1·K−1 through kinetic and thermodynamic analysis using FWO method, indicating the enhancing reactivity of MA-LFP1 system. The FTIR and MS spectra also revealed the best CLG performance of LFP1 with the highest total gas yield and syngas production. Meanwhile, the release kinetics of gaseous products demonstrated the minimum E(H2), E(CH4) and E2(CO) values of 14.86, 11.37 and 201.67 kJ/mol, respectively, owing to the highest proportion of surface-active oxygen species and oxygen vacancies on the LFP1 surface confirmed by characterizations. Results in this study provided helpful guidance for designing efficient perovskite-type oxygen carrier via doping with non-metallic elements toward the full utilization of microalgae.    

    

* Highly active late second-row transition metals loaded B12P12 nanocages as bifunctional single atom catalysts toward hydrogen and oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392267384
:TOPICS: Synthesis and Properties of Boron-based Materials, Accelerating Materials Innovation through Informatics, Two-Dimensional Transition Metal Carbides and Nitrides (MXenes)
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.294")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392267384"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392267384"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392267384"))][Get cited by]]

OpenAlex: https://openalex.org/W4392267384 (Open access: False)
    
[[https://openalex.org/A5088673435][Abdulrahman Allangawi]], [[https://openalex.org/A5036596256][Khurshid Ayub]], [[https://openalex.org/A5084837992][Mazhar Amjad Gilani]], [[https://openalex.org/A5046815580][Abdulla Ebrahim]], [[https://openalex.org/A5024263703][Muhammad Imran]], [[https://openalex.org/A5088375413][Tariq Mahmood]], International Journal of Hydrogen Energy. 61(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.294 
     
To fully realize the potential of hydrogen and oxygen production via the electrochemical water splitting process, single atom catalysts (SACs) are recently proposed and applied with high metal % utilization. In this regard, we have designed and examined the suitability of late second-row transition metal (TM) loaded B12P12 nanocages as SACs for the water splitting reaction. The viability of the designed electrocatalysts has been evaluated based on density functional theory (DFT) calculations. Outstandingly, the Rh@B12P12 SACs revealed high stability (Eint = −2.73 eV), which ensures that the Rh atoms can maintain single atom dispersion throughout extended periods and can withstand harsh catalytic conditions. In addition, the Rh@B12P12 SACs showed excellent catalytic activity as a bifunctional electrocatalyst (ΔGH = 0.17 eV & ηOER = 0.61 V) for both the hydrogen and oxygen evolution reactions (HER & OER, respectively). We hope that this study demonstrates the applicability of TM doped nanocage SACs as potential electrocatalysts.    

    

* ELECTROCHEMICALLY PRODUCED FILMS BASED ON INDIVIDUAL PORPHYRINS AND BIMETALLIC COMPOSITES: MORPHOLOGY AND ELECTROCATALYTIC PROPERTIES IN THE REACTION OF OXYGEN ELECTROREDUCTION  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392271658
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144025")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392271658"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392271658"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392271658"))][Get cited by]]

OpenAlex: https://openalex.org/W4392271658 (Open access: False)
    
[[https://openalex.org/A5018166861][Sergey M. Kuzmin]], [[https://openalex.org/A5058186237][S. A. Chulovskaya]], [[https://openalex.org/A5013817690][Mariya V. Tesakova]], [[https://openalex.org/A5037662282][О. И. Койфман]], [[https://openalex.org/A5026671786][V. I. Parfenyuk]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144025 
     
No abstract    

    

* Reductive Segregation During the Synthesis of Sb−SnO2-Supported Iridium Electrocatalysts for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392281325
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-02-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/1945-7111/ad2ef0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392281325"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392281325"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392281325"))][Get cited by]]

OpenAlex: https://openalex.org/W4392281325 (Open access: True)
    
[[https://openalex.org/A5020177563][Ziba Shabir Hussein Somjee Rajan]], [[https://openalex.org/A5034597223][Tobias Binninger]], [[https://openalex.org/A5006112425][Patricia J. Kooyman]], [[https://openalex.org/A5050192530][Darija Susac]], [[https://openalex.org/A5053846431][Rhiyaad Mohamed]], Journal of The Electrochemical Society. None(None)] 2024. https://doi.org/10.1149/1945-7111/ad2ef0 
     
Abstract A metal-organic chemical deposition approach using an Ir(acac) 3 precursor was employed to synthesise oxide−supported iridium-based electrocatalysts for the oxygen evolution reaction (OER) in acidic media. Inert and oxidising deposition conditions were explored in two temperature regimes, and the influence of these parameters on the physicochemical and electrochemical properties of catalysts consisting of IrO x supported on Sb–SnO 2 (ATO) were studied. Surprisingly, it was found that increasing the deposition temperature to 620°C favoured the formation of reduced iridium phases even in the presence of an oxidising reaction environment. This was explained by a thermodynamic preference for reduced phases at high temperatures, as well as the presence of acac-ligand decomposition products serving as reducing agents. Similarly, the reductive segregation of Sb from the ATO support at high temperatures leads to the loss of conductivity of the support, and the formation of Ir–Sb–Sn alloyed nanoparticles. These processes resulted in a loss of OER performance for the materials prepared under high-temperature conditions. Our findings highlight the importance of carefully selecting the temperature range during the synthesis of oxidic support materials and electrocatalysts for the OER.    

    

* Composite Nanoarchitectonics of Co3O4 Nanopolyhedrons with N-Doped Carbon and Carbon Nanotubes for Alkaline Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392284207
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10562-024-04615-z")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392284207"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392284207"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392284207"))][Get cited by]]

OpenAlex: https://openalex.org/W4392284207 (Open access: False)
    
[[https://openalex.org/A5017059450][H.M. Yang]], [[https://openalex.org/A5027597025][Nuo Liu]], [[https://openalex.org/A5084850705][Changliang Shan]], [[https://openalex.org/A5059804178][Yuee Zhao]], [[https://openalex.org/A5078686082][Yang Liu]], Catalysis Letters. None(None)] 2024. https://doi.org/10.1007/s10562-024-04615-z 
     
No abstract    

    

* Heterostructures by Templated Synthesis of Layered Double Hydroxide to Modulate the Electronic Structure of Nickel Sites for a Highly Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392290654
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smsc.202300294")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392290654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392290654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392290654"))][Get cited by]]

OpenAlex: https://openalex.org/W4392290654 (Open access: True)
    
[[https://openalex.org/A5076139079][Ke Xu]], [[https://openalex.org/A5075105240][Haihong Zhong]], [[https://openalex.org/A5049620625][Xuying Li]], [[https://openalex.org/A5081438845][Junhua Song]], [[https://openalex.org/A5082046835][Luis Alberto Estudillo‐Wong]], [[https://openalex.org/A5051262214][Jun Yang]], [[https://openalex.org/A5028441112][Yongjun Feng]], [[https://openalex.org/A5087432052][Xiaojuan Zhao]], [[https://openalex.org/A5085058884][Nicolás Alonso-Vante]], Small science. None(None)] 2024. https://doi.org/10.1002/smsc.202300294 
     
The design and development of highly efficient electrocatalysts for oxygen evolution reaction (OER) are critical for renewable energy generation. Ni‐based electrocatalysts are widely used in the water electrolysis process. In this work, heterostructure consisting of selenides and layered double hydroxides (LDH) named (Co, Ni)Se 4 @NiFe‐LDH, are prepared by an LDH‐based strategy, in which the electronic structure of Ni active sites is regulated by interfacial electron interaction. The (Co, Ni)Se 4 @NiFe‐LDH shows an optimized charge distribution of Ni sites and excellent catalytic activity. The effective charge modulation results in lowering the energy barrier of OOH* intermediate formation and adequate adsorption strength of the intermediates on Ni‐active sites, which improves the kinetics of OER. Specifically, the (Co, Ni)Se 4 @NiFe‐LDH only requires an overpotential of 237 mV to reach the current density of 10 mA cm −2 under alkaline conditions. The results of this work demonstrate that reasonable engineering of heterostructure is an effective strategy to improve the intrinsic property of OER electrocatalysts for water splitting.    

    

* Investigation of Active Spots on a TiC@MnSe Nanocomposite: An Efficient Electrocatalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392296658
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.energyfuels.3c05196")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392296658"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392296658"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392296658"))][Get cited by]]

OpenAlex: https://openalex.org/W4392296658 (Open access: False)
    
[[https://openalex.org/A5056104466][Tauseef Munawar]], [[https://openalex.org/A5023236497][Saman Fatima]], [[https://openalex.org/A5005163120][Mohammed Mujahid Alam]], [[https://openalex.org/A5015371105][Ambreen Bashir]], [[https://openalex.org/A5078102681][Abdullah G. Al‐Sehemi]], [[https://openalex.org/A5079586000][Faisal Mukhtar]], [[https://openalex.org/A5064746961][Nargis Bano]], [[https://openalex.org/A5049370676][Sumaira Manzoor]], [[https://openalex.org/A5079096059][Awais Khalid]], [[https://openalex.org/A5023867233][Sami G. Al-Ghamdi]], [[https://openalex.org/A5060990652][Muammer Koç]], [[https://openalex.org/A5004262523][Faisal Iqbal]], Energy & Fuels. None(None)] 2024. https://doi.org/10.1021/acs.energyfuels.3c05196 
     
Electrocatalysts with outstanding electrochemical performance and ecofriendly nature are desired for water-splitting studies to develop substantial hydrogen energy resources. In this report, a titanium carbide (TiC), MnSe, and novel TiC@MnSe heterostructure nanocomposite has been prepared by a facile hydrothermal process and analyzed using physical and electrochemical tools for electrocatalytic water splitting via the oxygen evolution reaction (OER). The heterostructure TiC@MnSe catalyst possesses a reduced overpotential of 299 mV at a universal standard current density of 10 mA/cm2, a small Tafel slope of 48.4 mV/dec, a large Cdl 54 mF, an enhanced electrochemical functional surface area of 1350 cm2, a low charge transfer resistance of 1.13 Ω, and robust stability after 70 h constant vigorous OER activity in an alkaline medium. The fabricated catalyst exhibits an encapsulated heterostructure morphology that supplies the active channels for the OER and remarkably boosts the electrochemical activity of the proposed catalyst for electrochemical water splitting (EWS). This work presents the superb electrochemical activity of the metal chalcogenide-based composite TiC@MnSe and addresses the fundamental reason for its robust performance. The research outcome pushes for large-scale electrochemical commercial applications, and the proposed TiC@MnSe can act as a cutting edge against costly noble metal-based electrocatalysts.    

    

* FeCoNiW medium entropy alloys loaded on N-doped carbon skeletons as efficient electrocatalysts for oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392306245
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj00011k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392306245"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392306245"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392306245"))][Get cited by]]

OpenAlex: https://openalex.org/W4392306245 (Open access: False)
    
[[https://openalex.org/A5000529032][Yuan-Yuan Ye]], [[https://openalex.org/A5003759585][Hui Zhang]], [[https://openalex.org/A5065140987][Xian Chen]], [[https://openalex.org/A5049109470][Zhaoshun Zhang]], [[https://openalex.org/A5040217177][Shaowei Jin]], [[https://openalex.org/A5073518820][Huaibao Tang]], [[https://openalex.org/A5067652153][Qun Yang]], [[https://openalex.org/A5022410466][Xueqin Zuo]], [[https://openalex.org/A5055328507][Guang Li]], New Journal of Chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj00011k 
     
Medium entropy alloys, consisting of four elements in close to isotropic proportions, have attracted a great deal of attention because of their unique properties (excellent strength, corrosion resistance, ect.). Here,...    

    

* Bimetallic sulfide/N-doped carbon composite derived from Prussian blue analogues/cellulose nanofibers film toward enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392306578
:TOPICS: Nanomaterials with Enzyme-Like Characteristics, Conducting Polymer Research, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3dt04336c")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392306578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392306578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392306578"))][Get cited by]]

OpenAlex: https://openalex.org/W4392306578 (Open access: False)
    
[[https://openalex.org/A5027676254][Zhengping Li]], [[https://openalex.org/A5050239112][Feiyang Chen]], [[https://openalex.org/A5029240863][Chunlong Li]], [[https://openalex.org/A5002648033][Zhiliang Zhang]], [[https://openalex.org/A5010955532][Fangong Kong]], [[https://openalex.org/A5065997618][Xipeng Pu]], [[https://openalex.org/A5017292276][Qifang Lu]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d3dt04336c 
     
Exploiting effectual, stable and cost-efficient electrocatalysts for the water oxidation reaction is highly desirable to renewable energy conversion techniques. Constructional design and compositional manipulation are widely used approaches to efficaciously...    

    

* Synergetic Improvement of Manganese Doped Ceria Nanocomposites with Dual Functionality of Propoxur Sensing and Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392310363
:TOPICS: Nanomaterials with Enzyme-Like Characteristics, Electrochemical Biosensor Technology, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4743618")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392310363"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392310363"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392310363"))][Get cited by]]

OpenAlex: https://openalex.org/W4392310363 (Open access: False)
    
[[https://openalex.org/A5064779642][Yu‐Hsu Chang]], [[https://openalex.org/A5085717612][N. Manjula]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4743618 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Confined Growth of Ultrathin, Nanometer-Sized Feooh/Cop Heterojunction Nanosheet Arrays as Efficient Self-Supported Electrode For Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392310630
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4743572")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392310630"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392310630"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392310630"))][Get cited by]]

OpenAlex: https://openalex.org/W4392310630 (Open access: False)
    
[[https://openalex.org/A5019723430][Xiaojing Fan]], [[https://openalex.org/A5061720627][Xiaoguang Bao]], [[https://openalex.org/A5066488748][Liang Guo]], [[https://openalex.org/A5005089910][Yao Lu]], [[https://openalex.org/A5070961992][Lulu Zhang]], [[https://openalex.org/A5002256316][Maosen Jing]], [[https://openalex.org/A5080797868][Qing Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4743572 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Trace rare earth modulated tetranickel nitride embedded in mesoporous carbon as electrocatalysts for the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392337523
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.307")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392337523"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392337523"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392337523"))][Get cited by]]

OpenAlex: https://openalex.org/W4392337523 (Open access: False)
    
[[https://openalex.org/A5011131329][Fangfei Lv]], [[https://openalex.org/A5083592980][Yongsheng Yan]], [[https://openalex.org/A5066046763][Zejun Ma]], [[https://openalex.org/A5030100725][Yingying Guo]], [[https://openalex.org/A5062734606][Wei Wu]], [[https://openalex.org/A5050736924][Suwen Li]], [[https://openalex.org/A5025859603][Lili Huo]], International Journal of Hydrogen Energy. 61(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.307 
     
The sluggish kinetics of anodic oxygen evolution reaction (OER) has been the restricted factor for large-scale hydrogen production from water electrolysis. Exploring highly efficient OER electrocatalysts is essential to varied renewable energy storage and conversion devices. In this work, we designed and fabricated subminiature tetranickel nitride (Ni4N) nanocrystallines modulated by trace amounts of rare earth (RE) encapsulated in ultrathin mesoporous nitrogen-doped carbon shells (RE-Ni4N@mesoNC) derived from ultrathin layered hydroxide nanosheets as highly active and stable electrocatalysts for the OER in water spilling. In view of the advantages of excellent electrical conductivity, adjustable surface electronic structure and a high density of utilizable active sites, the as-synthesized RE-Ni4N@mesoNC electrodes exhibit more superior performance than RE-free Ni4N@mesoNC and commercial IrO2. The optimal La–Ni4N@mesoNC achieved a lower overpotential of 330 mV at the current density of 10 mA cm−2 and a smaller Tafel slope of 66 mV·dec−1. And the La–Ni4N@mesoNC electrode also exhibit the excellent stability of continuous 72 h i-t tests and the overlapped polarization curve before and after 3000 consecutive CV cycles.    

    

* Gradient‐Tuned VO4 Vacancies in BiVO4 Photoanode for Boosting Bulk Hole Transport and Oxygen Evolution Reaction Performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392341901
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Gas Sensing Technology and Materials, Gallium Oxide (Ga2O3) Semiconductor Materials and Devices
:PUBLICATION_DATE: 2024-02-29
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202401122")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392341901"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392341901"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392341901"))][Get cited by]]

OpenAlex: https://openalex.org/W4392341901 (Open access: False)
    
[[https://openalex.org/A5008389503][Hao Pei]], [[https://openalex.org/A5065734711][Lingling Peng]], [[https://openalex.org/A5065187833][Zhaoji Jiang]], [[https://openalex.org/A5054907108][Yuexing Zhang]], [[https://openalex.org/A5077274385][Renjie Li]], [[https://openalex.org/A5074584092][Tianyou Peng]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202401122 
     
Abstract Although bismuth vanadate (BiVO 4 ) photoanode has been widely used, the solar‐driven oxygen evolution reaction (OER) performance is constrained due to the substantial bulk recombination and poor mobility of charge carriers. Herein, a facile solvothermal post‐treatment approach that employs N,N‐dimethylformamide (DMF) is developed to induce a VO 4 vacancy gradient from bulk to surface of BiVO 4 film, which not only improves the charge diffusion but also establishes an advantageous upward band gradient to promote the bulk hole transport. Under Air Mass 1.5 Global (AM1.5G) simulated solar illumination, the optimized BiVO 4 photoanode with a VO 4 vacancy gradient (denoted as B(VO) 1‐δ ) exhibits excellent OER performance with a charge separation efficiency of 74.4% at 1.23 V versus reversible hydrogen electrode (RHE) and incident‐photon‐to‐current conversion efficiency of 30.7% at 445 nm, 1.2 and 1.4 times higher than that of the pristine BiVO 4 , respectively. After loading nickel‐iron hydroxyl oxide (NiFeOOH) as a cocatalyst, the photocurrent density of B(VO) 1‐δ escalates to 5.92 mA cm −2 in a hole scavenger (Na 2 SO 3 ) solution and 5.07 mA cm −2 in a potassium borate buffer solution at 1.23 V versus RHE, far superior to the pristine BiVO 4 . This work highlights that the gradient‐tuned VO 4 vacancies can effectively modulate the bulk band structure and charge transfer in BiVO 4 photoanode, providing a new strategy for boosting solar water splitting performance.    

    

* First-principles study of the catalytic mechanism of boron-doped graphene oxide on the oxygen evolution reaction of lithium peroxide  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392341946
:TOPICS: Lithium-ion Battery Technology, Advanced Materials for Smart Windows, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.7498/aps.73.20240197")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392341946"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392341946"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392341946"))][Get cited by]]

OpenAlex: https://openalex.org/W4392341946 (Open access: True)
    
[[https://openalex.org/A5018986472][Xueling Lei]], [[https://openalex.org/A5094040155][Zhu Ju-Yong]], [[https://openalex.org/A5020862263][Qiang Ke]], [[https://openalex.org/A5042974614][Chuying Ouyang]], Chinese Physics. 0(0)] 2024. https://doi.org/10.7498/aps.73.20240197  ([[https://wulixb.iphy.ac.cn/pdf-content/10.7498/aps.73.20240197.pdf][pdf]])
     
Lithium-oxygen batteries stand out among post-lithium-ion batteries due to their theorical high energy density, while the sluggish reaction kinetics of lithium peroxide reduces the rate performance of the batteries. Therefore, improving the reaction kinetics of the lithium peroxide and then lowering the charge overpotential are of great importance for realizing reversible lithium-oxygen batteries with high energy density. In this paper, the catalytic mechanism of graphene oxide (GO) and boron-doped graphene oxide (BGO) on the oxygen evolution reaction of (Li<sub>2</sub>O<sub>2</sub>)<sub>2</sub> cluster is investigated by first-principles calculations. The results show that the charge transfers from (Li<sub>2</sub>O<sub>2</sub>)<sub>2</sub> cluster to GO and BGO are 0.59 e and 0.96 e, respectively, suggests that B doping improves the charge transfer from the discharged products to the cathode materials. The Gibbs free energy of the 4-electron decomposition process shows that the (Li<sub>2</sub>O<sub>2</sub>)<sub>2</sub> cluster favors the Li-O<sub>2</sub>-Li decomposition pathway, and the rate-determining step for the reaction on both GO and BGO is the third step, that is the removal of the third lithium. At the equilibrium potential, the charge overpotentials of GO and BGO are 0.76 V and 0.23 V, respectively, shows that B doping greatly reduces the charging overpotential of lithium-oxygen batteries. Moreover, mechanistic analysis showed that B doping enhances the electronic conductance of GO and forms an electron-deficient active center, which facilitates charge transport in cathode and charge transfer from lithium peroxide to cathode materials, thereby reducing the charging overpotential of the lithium-oxygen batteries and improving its cycling performance. B and O play a synergistic role in catalyzing the oxygen evolution reaction of (Li<sub>2</sub>O<sub>2</sub>)<sub>2</sub> clusters.    

    

* Ni-Co ternary nitrides with multiple surface oxides as bifunctional oxygen electrocatalysts for metal-air batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392343642
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jelechem.2024.118162")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392343642"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392343642"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392343642"))][Get cited by]]

OpenAlex: https://openalex.org/W4392343642 (Open access: False)
    
[[https://openalex.org/A5057903251][Xiaorong Chen]], [[https://openalex.org/A5028383740][Xinmeng Yu]], [[https://openalex.org/A5014282682][Guixin Zhang]], [[https://openalex.org/A5048507101][Sisi Wei]], [[https://openalex.org/A5067540103][Youguo Huang]], [[https://openalex.org/A5079420932][Shaoyi Wang]], [[https://openalex.org/A5067979856][Juantao Jiang]], [[https://openalex.org/A5091251729][Zhaoling Ma]], [[https://openalex.org/A5012413938][Qingyu Li]], Journal of Electroanalytical Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jelechem.2024.118162 
     
The bifunctional non-noble metal catalysts based on the metal nitrides with high activity and high efficiency is very challenging for the development of high-performance metal-air batteries. Herein, a new Ni-Co ternary nitrides anchored on nitrogen-doped carbontubes (denoted as NiCoxN/CNT) is rationally designed by the thermal of corresponding hydroxide/carbontubes at low temperature, following nitridation. The synergistic effect between Ni-Co ternary nitrides (Ni4N, Co5.47N, CoN) effectively regulates the electronic configuration of the active site, thereby optimizing the chemisorption energy of the reaction intermediates, resulting in improved intrinsic catalytic activity. The result shows that NiCoxN/CNT not only exhibits excellent half-wave potential of 0.80 V for ORR but also with a low overpotential of 280 mV for OER at 10 mA cm−2, outperforming those of cobalt mononitride and nickel mononitride. Furthermore, Zn-air batteries assembled with NiCoxN/CNT show a high specific capacity of 826.9 mA h g−1 and excellent cycling stabilities up to 190 h in an aqueous electrolyte. More attractively, when assembled into Mg-air batteries, NiCoxN/CNT cathode realizes high power density of 112.38 mWcm−2. Therefore, the design and construction of multiple TMNs is a new guide to break through the bifunctional catalytic activity.    

    

* Modulator directed synthesis of Size-Tunable mesoporous MOFs and their derived Nanocarbon-Based electrocatalysts for oxygen reduction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392343663
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Gas Sensing Technology and Materials, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150088")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392343663"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392343663"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392343663"))][Get cited by]]

OpenAlex: https://openalex.org/W4392343663 (Open access: False)
    
[[https://openalex.org/A5054392992][Hongjuan Zhang]], [[https://openalex.org/A5076800264][Ziruo Li]], [[https://openalex.org/A5051123510][Xue Yang]], [[https://openalex.org/A5061252299][Yingji Zhao]], [[https://openalex.org/A5064804120][Saad Melhi]], [[https://openalex.org/A5058451699][Jianping Ge]], [[https://openalex.org/A5006852120][Tao Cheng]], [[https://openalex.org/A5006160595][Jing Tang]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150088 
     
Although MOF-derived carbon materials have been widely used for electrocatalysis, it is challenging to prepare size-tunable MOF precursors through simple modulation. In this work, a series of mesoporous MOF (PCN-224) with a wide tunable particle size from micro- to nano-scale were successfully synthesized by in-situ introduction of 3-mercaptopropionic acid as the modulator. After carbonization and acid etching, the derived carbons (MAx-NC) inherit the mesoporous structure and exhibit uniform particles ranging from 30 to 900 nm. MAx-NC were used as model catalysts to explore the size effects on electrocatalysis. Considering the similar compositional and structural properties, the electrochemical activity depends on the number of accessible surface active sites. MA3-NC has optimized particle sizes (∼300 nm) would not only provide abundant surface active sites but also consist of large secondary pores between the particles for fast mass transport. Moreover, suitable Fe atom was introduced into the optimized MAx-NC, which shows comparable half-wave potential and better stability than commercial Pt/C for the typical oxygen reduction reaction. This work provides an efficient “modulation” strategy for preparing size-tunable mesoporous MOF cubes and their carbon derivatives, paving a new way to customize nanosized MOFs for wider applications.    

    

* Highly Active CoNi‐CoN3 Composite Sites Synergistically Accelerate Oxygen Electrode Reactions in Rechargeable Zinc–Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392344189
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-03-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202401506")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392344189"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392344189"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392344189"))][Get cited by]]

OpenAlex: https://openalex.org/W4392344189 (Open access: True)
    
[[https://openalex.org/A5015105154][Nan Li]], [[https://openalex.org/A5077976121][Mingzi Sun]], [[https://openalex.org/A5091432796][Jiaxiang Xiao]], [[https://openalex.org/A5073296337][Xiaoyu Ma]], [[https://openalex.org/A5054383720][Lijuan Huang]], [[https://openalex.org/A5052813770][Hongyu Li]], [[https://openalex.org/A5080320229][Chao Xie]], [[https://openalex.org/A5066276881][Yahui Yang]], [[https://openalex.org/A5020732750][Hao Jiang]], [[https://openalex.org/A5022350148][Bolong Huang]], [[https://openalex.org/A5067139848][Wenjun Zhang]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202401506 
     
Abstract Reaching rapid reaction kinetics of oxygen reduction (ORR) and oxygen evolution reactions (OER) is critical for realizing efficient rechargeable zinc–air batteries (ZABs). Herein, a novel CoNi‐CoN 3 composite site containing CoNi alloyed nanoparticles and CoN 3 moieties is first constructed in N‐doped carbon nanosheet matrix (CoNi‐CoN 3 /C). Benefiting from the high electroactivity of CoNi‐CoN 3 composite sites and large surface area, CoNi‐CoN 3 /C shows a superior half‐wave potential (0.88 V versus RHE) for ORR and a small overpotential (360 mV) for OER at 10 mA cm −2 . Theoretical calculations have demonstrated that the introduction of CoNi alloys has modulated the electronic distributions near the CoN 3 moiety, inducing the d‐band center of CoNi‐CoN 3 composite site to shift down, thus stabilizing the valence state of Co active sites and balancing the adsorption of OER/ORR intermediates. Accordingly, the reaction energy trends exhibit optimized overpotentials for OER/ORR, leading to superior battery performances. For aqueous and flexible quasi‐solid‐state rechargeable ZABs with CoNi‐CoN 3 /C as catalyst, a large power density (250 mW cm −2 ) and high specific capacity (804 mAh g −1 ) are achieved. The in‐depth understanding of the electroactivity enhancement mechanism of interactive metal nanoparticles and metal coordinated with nitrogen (MN x ) moieties is crucial for designing novel high‐performance metal/nitrogen‐doped carbon (M─N─C) catalysts.    

    

* Electronic Structure Tailoring of Cuco2o4 for Boosting Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392406405
:TOPICS: On-line Monitoring of Wastewater Quality, Gas Sensing Technology and Materials, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4747711")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392406405"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392406405"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392406405"))][Get cited by]]

OpenAlex: https://openalex.org/W4392406405 (Open access: False)
    
[[https://openalex.org/A5037548250][Qi Dong]], [[https://openalex.org/A5064332635][Bin Wen]], [[https://openalex.org/A5061238087][Xin Zhao]], [[https://openalex.org/A5058808692][Peiyi Wang]], [[https://openalex.org/A5062457169][Xiao Lyu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4747711 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Computational Study of Oxygen Evolution Reaction on Flat and Stepped Surfaces of Strontium Titanate  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392350128
:TOPICS: Emergent Phenomena at Oxide Interfaces, Solid Oxide Fuel Cells, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cattod.2024.114609")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392350128"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392350128"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392350128"))][Get cited by]]

OpenAlex: https://openalex.org/W4392350128 (Open access: False)
    
[[https://openalex.org/A5024831781][Maksim Sokolov]], [[https://openalex.org/A5063495259][Yuri A. Mastrikov]], [[https://openalex.org/A5035011242][Dmitry Bocharov]], [[https://openalex.org/A5039961910][Veera Krasnenko]], [[https://openalex.org/A5038309311][G. Zvejnieks]], [[https://openalex.org/A5004991965][Kai S. Exner]], [[https://openalex.org/A5009091089][E. A. Kotomin]], Catalysis Today. None(None)] 2024. https://doi.org/10.1016/j.cattod.2024.114609 
     
Oxygen evolution reaction (OER) is reconciled with the bottleneck in hydrogen production via photo- or electrocatalytic water splitting. One of the remedies to overcome this shortcoming is to develop catalytically efficient anode materials. Strontium titanate (STO) is a potential candidate for the OER by referring to recent experimental reports on enhanced photocatalytic activity of faceted nanoparticles. In this paper, we perform electronic structure calculations in the density functional theory approximation to study the OER on flat and stepped surfaces, such as encountered in nano-sized STO. We demonstrate that stepped surfaces reveal higher OER activity than flat surfaces, which is consistent with experimental data. We also observe partial breaking of OER scaling relation on stepped surfaces, albeit this does not necessarily cause higher catalytic activity. Finally, we propose recommendations for thorough implementation of zero-point energy calculations as the calculation method may impact the free-energy landscape of the OER.    

    

* Photo-assisted electrocatalysis of NiO/CeO2 heterojunction for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392401644
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.113984")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392401644"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392401644"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392401644"))][Get cited by]]

OpenAlex: https://openalex.org/W4392401644 (Open access: False)
    
[[https://openalex.org/A5015868117][Shengjie Wei]], [[https://openalex.org/A5037983523][L. Zhang]], [[https://openalex.org/A5017428165][Haiyang Xu]], [[https://openalex.org/A5055083617][Dingcheng Sun]], [[https://openalex.org/A5002588177][Qingfeng He]], [[https://openalex.org/A5038010623][Xu Ji]], [[https://openalex.org/A5063142669][Yong Yang]], Molecular Catalysis. 557(None)] 2024. https://doi.org/10.1016/j.mcat.2024.113984 
     
In recent years, photo-assisted electrocatalysis has attracted significant interest in the field of electrolytic hydrogen production. By integrating electrical and optical energy, supplementary energy is harnessed for the electrocatalytic process, which offers an efficient strategy to enhance the performance of oxygen evolution reaction (OER). Herein, the heterojunction NiO/CeO2 composite nanostructures supported by nickel foam (represented as NiO/CeO2@NF) was selected as the photo-assisted electrocatalyst, through the mutual synergy of voltage and light to improve the catalytic activity of OER in electrolytic water. Under light irradiation, the NiO component undergoes photoexcited to produce photogenerated electrons that move towards the CeO2 component, stimulating the generation and accumulation of more holes accelerating the formation of Ni (III) to improve the reaction efficiency with electrons, thereby boosting the enhancement of OER activity. The results demonstrate that the overpotential corresponding to NiO/CeO2@NF in non-irradiation at 10 mA cm−2 current density was 280 mV, and the NiO/CeO2@NF in light irradiation displays robust OER activity, with lower over-potentials 260 mV at 10 mA cm−2, which 20 mV lower than in non-irradiation. Moreover, NiO/CeO2@NF in light irradiation exhibits high catalytic activity and durability for OER in an alkaline electrolyte, delivering 100 mA cm−2 at 320 mV and outperforming RuO2 under high current densities.    

    

* Promotion of oxygen evolution through the modification of Co-O bond in spinel NiCo2O4  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392360203
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Advanced Materials for Smart Windows
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpcs.2024.111955")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392360203"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392360203"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392360203"))][Get cited by]]

OpenAlex: https://openalex.org/W4392360203 (Open access: False)
    
[[https://openalex.org/A5067015557][M.Y. Ruan]], [[https://openalex.org/A5085663764][Xing Wei]], [[https://openalex.org/A5054374657][Hongshan Chen]], [[https://openalex.org/A5073216396][Lei Wang]], [[https://openalex.org/A5090323662][Tianyi Li]], [[https://openalex.org/A5016338405][Haonan Wang]], [[https://openalex.org/A5067217210][Angang Dong]], [[https://openalex.org/A5018936100][Mengting Guo]], Journal of Physics and Chemistry of Solids. None(None)] 2024. https://doi.org/10.1016/j.jpcs.2024.111955 
     
The coordination environment of magnetic ions in transition metal oxides has a significant impact on the oxygen evolution reaction (OER) activity. Herein, we synthesized inverse spinel oxide NiCo2-xFexO4 (x = 0–1.5) on the nickel foam (NiCo2-xFexO4@NF) to explore the impact of Fe3+ ions doping in Co site on OER activity. The electrochemical results indicate that the introduction of Fe3+ ions drastically improved the OER performance for x ≤ 1.0. While the OER activity would decrease with further doping of Fe3+. The overpotential of 10 mA cm−2 decreased from 331 mV (NiCo2O4@NF) to 260 mV versus RHE (NiCoFeO4@NF) and lower Tafel slope (41.46 mV/dec) for OER in 1.0 M KOH electrolyte. Furthermore, there is a slightly decrease in overpotential after the stability test and the difference is not more than 2%. By comparing the structure of NiCoFeO4@NF and pristine NiCo2O4@NF, it was found that the doping of moderate amounts Fe3+ (x ≤ 1.0) would help to form the structure which can expose more active sites. Furthermore, XPS results indicate that transition from Co2+ to Co3+, the higher Co3+/Co2+ ratio contributes to good reducibility and oxygen mobility, and 3d state of Co3+ would generate strong hybridization with O 2p state. The EIS results imply that the incorporation of Fe can effectively improve the conductivity of materials and reduce the charge transfer resistance. Together with the magnetic properties, we found that Fe3+ ions replaced Co site in octahedral site with low spin state for x ≤ 1.0 implies beneficial effect for OER activity. While For x > 1.0, part of the Fe3+ ions locate in tetrahedron site with high spin state which show harmful effect for the OER activity.    

    

* Carbon-based synergistic catalysis with transition metal dichalcogenides for electrocatalytic oxygen evolution/reduction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392374396
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matchemphys.2024.129163")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392374396"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392374396"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392374396"))][Get cited by]]

OpenAlex: https://openalex.org/W4392374396 (Open access: False)
    
[[https://openalex.org/A5033073898][Fan Liu]], [[https://openalex.org/A5007382007][Changzhen Zhan]], [[https://openalex.org/A5050917029][Hao Lin]], [[https://openalex.org/A5090437811][Deping Xu]], [[https://openalex.org/A5090802897][Zheng‐Hong Huang]], [[https://openalex.org/A5016734293][Ruitao Lv]], Materials Chemistry and Physics. None(None)] 2024. https://doi.org/10.1016/j.matchemphys.2024.129163 
     
Oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) are considered as two of the most critical processes in various renewable energy systems, including multi-electron transfer reactions. However, the kinetics of ORR/OER are usually sluggish, significantly impeding their related applications. This review article summarizes the research advancements in electrocatalytic ORR/OER achieved using traditional noble metals, transition metal dichalcogenides (TMDCs), and carbon-based materials. Exploring diverse engineering strategies, such as defect engineering, strain engineering, and alloying, takes full advantage of the inherent energy band tunability of TMDCs and the advantages of carbon materials, including tunable specific surface area, high conductivity, and good stability. These strategies aim to regulate the intrinsic activity of materials and boost the apparent activity of the electrocatalytic ORR/OER. Finally, the challenges and prospects along this research line are proposed.    

    

* Preliminary investigation of factors influencing the bubbles detachment of iridium oxide in oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392481685
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.369")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392481685"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392481685"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392481685"))][Get cited by]]

OpenAlex: https://openalex.org/W4392481685 (Open access: False)
    
[[https://openalex.org/A5077749322][Yuling Hu]], [[https://openalex.org/A5019819126][Yifei Yang]], [[https://openalex.org/A5037890103][Zhen Zeng]], [[https://openalex.org/A5076559742][Tingxi Zhou]], [[https://openalex.org/A5057711219][Fei Yang]], [[https://openalex.org/A5081306801][Wei Sun]], [[https://openalex.org/A5000359400][He Li]], International Journal of Hydrogen Energy. 61(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.369 
     
Oxygen evolution reaction (OER) is a well-known gas-involved reaction in which oxygen bubbles are formed and adhered on anode surface to lead to a sharp decline of performance. Iridium oxide (IrO2) is the catalyst for water oxidation and is often used as a benchmark material. However, the factors affecting the bubbles detachment of IrO2 are still unclear. Herein, we found that: 1. Nafion®, one of the main components of PEM membrane and usually used as electrode binder, can significantly increase the hydrophobicity of the electrode surface and is unfavorable to bubble detachment. 2. IrO2 itself has good hydrophilicity but is not enough for efficient bubble separation, and no obvious linear relationship between bubble detachment performance and the particle size. 3. For improving bubble separation, irregularly rough surfaces should be avoided to prevent cavities trapping effect and multiple unnecessary bubble adhesion sites, both of which play the roles in stabilizing bubbles. In contrast, the uniformity and regularity of electrode surface should be paid more attention, as evidenced by comparing the surface morphology between drop-casting and pyrolysis in IrO2 and RuO2.    

    

* The optimized oxygen evolution reaction of FeCoNi layer double hydroxide by the adhesion of Ag nanoparticles  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392435047
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.078")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392435047"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392435047"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392435047"))][Get cited by]]

OpenAlex: https://openalex.org/W4392435047 (Open access: False)
    
[[https://openalex.org/A5041797844][Wenxin He]], [[https://openalex.org/A5050958607][Xue-wei Wang]], [[https://openalex.org/A5019678627][Yu Chen]], [[https://openalex.org/A5019110446][Wenhua Zhang]], [[https://openalex.org/A5000902609][Jia Li]], [[https://openalex.org/A5024438183][Xiao Li]], International Journal of Hydrogen Energy. 61(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.078 
     
Modulating the morphological structure and establishing heterogeneous interface of layered double hydroxides (LDHs) are feasible strategies in electrocatalytic oxygen evolution reaction (OER). In this work, FeCoNi-LDH nanosheets are synthesized on the surface of copper foam (CF) by a simple electrodeposition method, where cross-linked nanosheets were aggregated into microspheres and then uniformly loaded with Ag nanoparticles. The unique heterogeneous interface between Ag nanoparticles and FeCoNi-LDH was demonstrated by TEM characterization. The electrochemical results show that the Ag@FeCoNi-LDH@CF is an efficient OER electrocatalyst in alkaline media. The required overpotential at 100 mA/cm2 is not only significantly lower than that of FeCoNi-LDH@CF but also superior to most of recently reported OER electrocatalysts. The results of XPS and BET indicate that the introduction of Ag nanoparticles accelerates the electron transfer and optimizes the activity of the original sites, thus improving the efficiency of the OER catalyst. It is also experimentally verified that Ag@FeCoNi-LDH@CF can maintain its stability after a long time of chronoamperometry cycling, which shows good prospects for future practical applications. Therefore, this finding suggests that the targeted assembly of noble metals and transition metals into a system to construct new OER electrocatalysts with integrated improvements is an effective design approach to improve the OER performance of LDHs.    

    

* A Coordination‐Derived Cerium‐Based Amorphous–Crystalline Heterostructure with High Electrocatalytic Oxygen Evolution Activity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392401653
:TOPICS: Electrocatalysis for Energy Conversion, Polyoxometalate Clusters and Materials, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-03-03
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202311505")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392401653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392401653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392401653"))][Get cited by]]

OpenAlex: https://openalex.org/W4392401653 (Open access: False)
    
[[https://openalex.org/A5088969778][Haiyan An]], [[https://openalex.org/A5035027792][Xijiao Mu]], [[https://openalex.org/A5089354865][Guoying Tan]], [[https://openalex.org/A5017470545][Pingru Su]], [[https://openalex.org/A5049117772][Liangliang Liu]], [[https://openalex.org/A5079560786][Nan Song]], [[https://openalex.org/A5043452476][Shi‐Qiang Bai]], [[https://openalex.org/A5055781053][Chun‐Hua Yan]], [[https://openalex.org/A5076853026][Yu Tang]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202311505 
     
Abstract The rational design of heterogeneous catalysts is crucial for achieving optimal physicochemical properties and high electrochemical activity. However, the development of new amorphous–crystalline heterostructures is significantly more challenging than that of the existing crystalline–crystalline heterostructures. To overcome these issues, a coordination‐assisted strategy that can help fabricate an amorphous NiO/crystalline NiCeO x (a‐NiO/c‐NiCeO x ) heterostructure is reported herein. The coordination geometry of the organic ligands plays a pivotal role in permitting the formation of coordination polymers with high Ni contents. This consequently provides an opportunity for enabling the supersaturation of Ni in the NiCeO x structure during annealing, leading to the endogenous spillover of Ni from the depths of NiCeO x to its surface. The resulting heterostructure, featuring strongly coupled amorphous NiO and crystalline NiCeO x , exhibits harmonious interactions in addition to low overpotentials and high catalytic stability in the oxygen evolution reaction (OER). Theoretical calculations prove that the amorphous–crystalline interfaces facilitate charge transfer, which plays a critical role in regulating the local electron density of the Ni sites, thereby promoting the adsorption of oxygen‐based intermediates on the Ni sites and lowering the dissociation‐related energy barriers. Overall, this study underscores the potential of coordinating different metal ions at the molecular level to advance amorphous–crystalline heterostructure design.    

    

* Mn-doped RuO2 nanocrystals with abundant oxygen vacancies for enhanced oxygen evolution in acidic media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392394344
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4qi00013g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392394344"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392394344"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392394344"))][Get cited by]]

OpenAlex: https://openalex.org/W4392394344 (Open access: False)
    
[[https://openalex.org/A5073895879][Chengchao Zheng]], [[https://openalex.org/A5011903103][Bing Huang]], [[https://openalex.org/A5049810380][Xuwei Liu]], [[https://openalex.org/A5080102032][Hao Wang]], [[https://openalex.org/A5087843398][Lunhui Guan]], Inorganic chemistry frontiers. None(None)] 2024. https://doi.org/10.1039/d4qi00013g 
     
Synthesizing Mn–RuO 2 -120(NaNO 3 ) with abundant oxygen vacancies using the molten salt method enhances the oxygen evolution reaction (OER) catalytic performance, demonstrating excellent activity and stability.    

    

* In situ formation of robust nanostructured Cobalt oxyhydroxide / Cobalt oxide oxygen evolution reaction electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392353445
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-j9ml0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392353445"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392353445"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392353445"))][Get cited by]]

OpenAlex: https://openalex.org/W4392353445 (Open access: True)
    
[[https://openalex.org/A5002962939][Yupeng Zhao]], [[https://openalex.org/A5088121808][Dandan Gao]], [[https://openalex.org/A5002418054][Johannes Biskupek]], [[https://openalex.org/A5017684207][Ute Kaiser]], [[https://openalex.org/A5089443613][Rongji Liu]], [[https://openalex.org/A5080329256][Carsten Streb]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-j9ml0  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65e04983e9ebbb4db98b043b/original/in-situ-formation-of-robust-nanostructured-cobalt-oxyhydroxide-cobalt-oxide-oxygen-evolution-reaction-electrocatalysts.pdf][pdf]])
     
The design of efficient and stable oxygen evolution reaction (OER) catalysts-based earth-abundant metal precursors is crucial for large-scale energy conversion and storage. To-date, many catalyst materials are limited by poor stability in harsh oxidative conditions. Thus, much research is targeted at developing materials that can operate under demanding OER conditions. One promising approach is the in-situ formation of catalysts which are inherently stable under the oxidizing, alkaline conditions often used in OER studies. Here, we report how mixed metal sulfide precursors (i.e. CoMo2S4 and FeS2) which give the low overpotentials (307 mV at j = 10 mA·cm-2) at the beginning of catalysis, are converted in-situ to give a highly stable composite OER catalyst under alkaline OER conditions (1 M aqueous KOH solution, pH = 13.8). Mechanistic studies reveal that under operation, the precursor materials are converted to γ-CoOOH nanofibers and Co2O3 nanoparticles, both well-known prototype OER catalysts. The report demonstrates that the presence of crystalline mix metal sulfide precursors is critical for the simultaneous in-situ formation of the active catalysts, highlighting that use of these earth-abundant minerals might offer an economically and chemically viable route for scalable catalyst development.    

    

* Oxide Encapsulated Ruthenium Oxide Catalysts for Selective Oxygen Evolution in Unbuffered pH Neutral Seawater  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392357009
:TOPICS: On-line Monitoring of Wastewater Quality, Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-szsq8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392357009"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392357009"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392357009"))][Get cited by]]

OpenAlex: https://openalex.org/W4392357009 (Open access: True)
    
[[https://openalex.org/A5079786247][Daniela Bushiri]], [[https://openalex.org/A5001963058][Amanda F. Baxter]], [[https://openalex.org/A5094044118][Onaolapo Odunjo]], [[https://openalex.org/A5081827586][Diego Álvarez]], [[https://openalex.org/A5041615964][Yong Yuan]], [[https://openalex.org/A5034358731][Jingguang G. Chen]], [[https://openalex.org/A5073994683][Daniel V. Esposito]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-szsq8  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65e0c01d66c1381729dd4ea3/original/oxide-encapsulated-ruthenium-oxide-catalysts-for-selective-oxygen-evolution-in-unbuffered-p-h-neutral-seawater.pdf][pdf]])
     
Direct seawater electrolysis is a promising approach to producing green hydrogen in water-scarce environments using renewable energy. However, the undesirable chlorine evolution reaction (CER) and hypochlorite evolution reaction (HCER) compete with the desired oxygen evolution reaction (OER) at the anode electrocatalyst. This issue is most pronounced in unbuffered pH neutral solutions due to local acidification resulting from the OER. To overcome this challenge, this study explores the use of silicon oxide (SiOx) and titanium oxide (TiOx) nanoscale overlayers coated on metallic ruthenium (Ru) and ruthenium oxide (RuOx) thin film electrodes to block chloride ions from reaching active sites during operation in unbuffered 0.6 M NaCl electrolyte. Using a combination of (electro)analytical techniques, encapsulated RuOx anodes are shown to effectively suppress Cl- transport to buried catalyst active sites while allowing for the desired OER to occur, leading to increases in OER faradaic efficiency at moderate overpotentials. Evidence for the ability of SiOx overlayers to block Cl- ions from reaching the active buried interface was obtained by monitoring the OH stretching mode of OH adsorbates using in situ Raman spectroscopy. This study also reports trade-offs between the activity, selectivity, and stability of bare and encapsulated Ru and RuOx electrocatalysts, finding that the magnitude of these trade-offs strongly depends on the nature of both the catalyst and overlayer material. The most promising anode electrocatalyst is RuOx encapsulated by 4 nm of SiOx, which gives the largest improvement in OER faradaic efficiency while demonstrating a relatively stable operating current and minimal increases in overpotential.    

    

* Facile synthesis of nanosized spinel high entropy oxide (FeCoNiCrMn)3O4 for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392360598
:TOPICS: Electrocatalysis for Energy Conversion, High-Entropy Alloys: Novel Designs and Properties, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jmat.2024.02.003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392360598"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392360598"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392360598"))][Get cited by]]

OpenAlex: https://openalex.org/W4392360598 (Open access: True)
    
[[https://openalex.org/A5016936946][Bomin Feng]], [[https://openalex.org/A5082857859][Jun Chen]], [[https://openalex.org/A5037117751][Yifei Yang]], [[https://openalex.org/A5045305703][Ming‐Bo Yang]], [[https://openalex.org/A5015403864][Hongbing Wang]], [[https://openalex.org/A5036851362][Changyin Zhong]], [[https://openalex.org/A5046793899][Xiaochong Zhao]], [[https://openalex.org/A5034504744][Yunxi Yao]], Journal of Materiomics. None(None)] 2024. https://doi.org/10.1016/j.jmat.2024.02.003 
     
The sluggish reaction kinetics of oxygen evolution reaction (OER) and the high price of noble metal catalysts hinder the wide application of water electrolysis for hydrogen generation. High-entropy oxides (HEOs) with multi-components and high entropy stabilized structures have attracted great research interests due to their efficient and durable performance in electrolytic water splitting reactions. However, the development of efficient HEO electrocatalysts are often hindered by the limited surface exposed active sites because high temperature is usually required to form a high entropy stabilized structure. Herein, a flaky high-entropy oxide with a spinel structure, (FeCoNiCrMn)3O4, was synthesized by using the sacrificial layered carbon template in situ prepared by the volatile reaction between ammonium sulfate and molten glucose. High-resolution TEM results show the as-prepared (FeCoNiCrMn)3O4 flakes are composed of nanosized HEO particles. The nanosized (FeCoNiCrMn)3O4 HEO electrocatalysts exhibit excellent OER activity, with an overpotential of 239 mV at 10 mA/cm2 and a Tafel slope of 52.4 mV/dec. The electrocatalyst has excellent stability. Even at a high current density of 100 mA/cm2, the activity remains unchanged during the stability test for 24 h. The results here shed a new light in the design and fabrication of highly efficient HEO electrocatalysts.    

    

* Enhancing Oxygen Evolution Reaction Performance of Ruddlesden–Popper Perovskite Oxide Through Heteroatom Incorporation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392458686
:TOPICS: Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4748569")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392458686"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392458686"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392458686"))][Get cited by]]

OpenAlex: https://openalex.org/W4392458686 (Open access: False)
    
[[https://openalex.org/A5040548501][Shu-Fang Li]], [[https://openalex.org/A5021859056][Baoqin Zhang]], [[https://openalex.org/A5016059098][Zhen‐Bo Wang]], [[https://openalex.org/A5037045692][Dong Yan]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4748569 
     
No abstract    

    

* Enhancing Oxygen Evolution Reaction of CoP nanosheets via Interfacial Engineering with CoFe-LDH Nanosheets  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392453559
:TOPICS: Catalytic Nanomaterials, Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.colsurfa.2024.133640")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392453559"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392453559"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392453559"))][Get cited by]]

OpenAlex: https://openalex.org/W4392453559 (Open access: False)
    
[[https://openalex.org/A5051647392][Morteza Kolaei]], [[https://openalex.org/A5087069788][Harish S. Chavan]], [[https://openalex.org/A5041792310][Jiyoung Kim]], [[https://openalex.org/A5058855547][Ki-Young Lee]], Colloids and Surfaces A: Physicochemical and Engineering Aspects. None(None)] 2024. https://doi.org/10.1016/j.colsurfa.2024.133640 
     
No abstract    

    

* Effect of Ni Sulfate Residue on Oxygen Evolution Reaction (OER) in Porous NiFe@NiFe Layered Double Hydroxide  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392472905
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-03-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202400046")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392472905"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392472905"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392472905"))][Get cited by]]

OpenAlex: https://openalex.org/W4392472905 (Open access: False)
    
[[https://openalex.org/A5069252580][Jong‐Hwan Park]], [[https://openalex.org/A5008074780][Hyun Jun Kwon]], [[https://openalex.org/A5043690102][Da Young Lee]], [[https://openalex.org/A5047362137][Su‐Jeong Suh]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202400046 
     
Abstract The development of cost‐effective and high‐performance oxygen evolution reaction (OER) catalysts is a significant challenge. This study presents the synthesis of binder‐free NiFe@NiFe layered double hydroxide (NNF) via one‐pot electrodeposition on carbon paper and Ni foam at high current densities. The presence of Ni sulfate residues on the prepared NNF is also investigated. The findings indicate that Ni sulfate significantly improves OER performance and durability. The sulfate content can be controlled by varying the method and duration of washing. NNF prepared through dipping (NNF‐D) exhibits outstanding OER activity with a low overpotential of 241 mV, which is 25 mV lower than that of NNF washed for 60 s (NNF‐W‐60 s) at 10 mA cm −2 in 1 m KOH. Furthermore, density functional theory analyses indicate that the Ni sulfate residue helps modify the electronic structure, thereby optimizing the binding strength of *OOH. This synthetic strategy is expected to inspire the development of next‐generation catalysts utilizing various adsorbates.    

    

* High-entropy oxide (Mg0.2Fe0.2Co0.2Cu0.2Zn0.2)O with rocksalt-to-spinel transformation and its electrocatalytic activity for the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392388335
:TOPICS: High-Entropy Alloys: Novel Designs and Properties, Electrocatalysis for Energy Conversion, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2024-05-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.174029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392388335"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392388335"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392388335"))][Get cited by]]

OpenAlex: https://openalex.org/W4392388335 (Open access: False)
    
[[https://openalex.org/A5069966623][Daehyeon Hong]], [[https://openalex.org/A5004247415][Yun-Hyuk Choi]], Journal of Alloys and Compounds. 985(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.174029 
     
Since the recent application of the concept of high entropy to multicomponent oxide systems, there has been an active pursuit of fabricating high-entropy oxides (HEOs) and exploring their applications across various fields. Given the relatively recent discovery of this novel material system, additional studies are necessary to enhance our understanding of structures and properties in a broader range of compositions. In this study, a rocksalt HEO with a novel composition, (Mg0.2Fe0.2Co0.2Cu0.2Zn0.2)O, is prepared through solid-state reactions at various calcination temperatures within the range of 1000–1400 °C. The formation of single-phased rocksalt solid solutions is observed under low-temperature calcination, while a spinel-related metastable phase and a spinel phase separate from the rocksalt phase during calcination at 1300 °C and 1400 °C, respectively. These rocksalt-to-spinel structural transformations (i.e., phase separations), depending on calcination temperature, are carefully characterized using scanning transmission electron microscopy (STEM) and energy-dispersive spectroscopy (EDS) mapping techniques. Subsequently, it is discovered that the microstructure in the HEO significantly influences the kinetics of the electrocatalytic oxygen evolution reaction (OER) in alkaline water oxidation. These findings offer valuable insights into the structural phase transformation and the structure–activity relationship within HEO systems.    

    

* Fabrication and characterization of Nickel-coated 3D printed electrodes for enhanced oxygen evolution reaction in acidic media at various temperatures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392438953
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131172")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392438953"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392438953"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392438953"))][Get cited by]]

OpenAlex: https://openalex.org/W4392438953 (Open access: False)
    
[[https://openalex.org/A5082448730][Bulut Hüner]], [[https://openalex.org/A5055475408][Nesrin Demïr]], [[https://openalex.org/A5029117505][Mehmet Fatih Kaya]], Fuel. 366(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131172 
     
Additive manufacturing (AM), often referred to as 3D printing, is a new technology that allows objects to be created by adding layer by layer, as opposed to traditional manufacturing processes. Therefore, the rapid and cost-effective AM method can facilitate research and development efforts in the field of electrochemistry. In this study, oxygen evolution reaction (OER) electrodes are fabricated by a 3D printing technique utilizing carbon-based (PP filament) and graphene-based PLA filaments (BM filament). Electrodes are then coated with Ni by electrochemical deposition method at different temperatures. Electrochemical analysis of Ni coated PP and BM electrodes is made in acidic environments (0.5 M H2SO4) using different characterization techniques. The results indicate that PP/Ni-50 and BM/Ni-50 electrodes have the highest catalytic activity for OER in acidic media. PP/Ni-50 and BM/Ni-50 electrodes exhibited a superior double layer (Cdl) value than other Ni coated 3D printed electrode samples, and their active surface areas are calculated as 0.201 cm2 and 0.286 cm2, respectively. A larger active surface area leads to an increase in the number of active sites, causing the OER process to be more effective. Consequently, increasing the active surface area of electrode samples is crucial for improving the efficiency and effectiveness of the Oxygen Evolution Reaction (OER) process, especially in the context of renewable energy and sustainable technology applications.    

    
