#+TITLE: water splitting
Description: water splitting papers
Created on Thu Sep 19 01:18:07 2024

Found 81 results from 2024-09-12 to 2024-09-19
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Computational screening of transition metal atom doped ZnS and ZnSe nanostructures as promising bifunctional oxygen electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402491900
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra04011b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402491900"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402491900"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402491900"))][Get cited by]]

OpenAlex: https://openalex.org/W4402491900 (Open access: True)
    
[[https://openalex.org/A5008151031][Feifei Xia]], [[https://openalex.org/A5100707363][Shu Li]], [[https://openalex.org/A5101466950][Fengli Yang]], [[https://openalex.org/A5101694936][Yingpin Wen]], [[https://openalex.org/A5031745096][Chunzhi Zheng]], RSC Advances. 14(40)] 2024. https://doi.org/10.1039/d4ra04011b 
     
The design of bifunctional oxygen electrocatalysts showing high catalytic performance for the oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) is of great significance for developing new renewable energy storage and conversion technologies. Herein, based on the first principles calculations, we systematically explored the electrocatalytic activity of a series of transition metal atom (Fe, Co, Ni, Cu, Pd and Pt)-doped ZnS and ZnSe nanostructures for OER and ORR. The calculated results revealed that Ni- and Pt-doped ZnS and ZnSe nanostructures exhibit promising electrocatalytic performance for both OER and ORR in comparison to the pristine ZnS and ZnSe nanostructures. Especially, the OER/ORR overpotentials of Ni-doped ZnS and ZnSe nanostructures are estimated to be 0.28/0.30 and 0.31/0.31 V, respectively, disclosing their great potential as bifunctional oxygen electrocatalysts. Moreover, it is found that Ni-doped ZnS and ZnSe nanostructures for OER and ORR are on the top of the volcano plots, evincing promising catalytic performance. Our results provide theoretical insights into a feasible strategy to synthesize highly efficient ZnS- and ZnSe-based bifunctional oxygen electrocatalysts in the future.    

    

* Green Hydrogen Production by Low‐Temperature Membrane‐Engineered Water Electrolyzers, and Regenerative Fuel Cells  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402567352
:TOPICS: Hydrogen Energy Systems and Technologies, Electrocatalysis for Energy Conversion, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smtd.202400574")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402567352"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402567352"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402567352"))][Get cited by]]

OpenAlex: https://openalex.org/W4402567352 (Open access: True)
    
[[https://openalex.org/A5107266695][Alexandre Bodard]], [[https://openalex.org/A5023209242][Zhangsen Chen]], [[https://openalex.org/A5107266696][Oumayma ELJarray]], [[https://openalex.org/A5023395031][Gaixia Zhang]], Small Methods. None(None)] 2024. https://doi.org/10.1002/smtd.202400574 
     
Abstract Green hydrogen (H 2 ) is an essential component of global plans to reduce carbon emissions from hard‐to‐abate industries and heavy transport. However, challenges remain in the highly efficient H 2 production from water electrolysis powered by renewable energies. The sluggish oxygen evolution restrains the H 2 production from water splitting. Rational electrocatalyst designs for highly efficient H 2 production and oxygen evolution are pivotal for water electrolysis. With the development of high‐performance electrolyzers, the scale‐up of H 2 production to an industrial‐level related activity can be achieved. This review summarizes recent advances in water electrolysis such as the proton exchange membrane water electrolyzer (PEMWE) and anion exchange membrane water electrolyzer (AEMWE). The critical challenges for PEMWE and AEMWE are the high cost of noble‐metal catalysts and their durability, respectively. This review highlights the anode and cathode designs for improving the catalytic performance of electrocatalysts, the electrolyte and membrane engineering for membrane electrode assembly (MEA) optimizations, and stack systems for the most promising electrolyzers in water electrolysis. Besides, the advantages of integrating water electrolyzers, fuel cells (FC), and regenerative fuel cells (RFC) into the hydrogen ecosystem are introduced. Finally, the perspective of electrolyzer designs with superior performance is presented.    

    

* Fe-modulated NiFex Co Layered Double Hydroxide on Ni Foam for Efficient Oxygen Precipitation Reaction in Alkaline Water Electrolysis for Hydrogen Production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402570146
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Carbon Dioxide Hydrogenation, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-07-28
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.23919/ccc63176.2024.10661943")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402570146"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402570146"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402570146"))][Get cited by]]

OpenAlex: https://openalex.org/W4402570146 (Open access: False)
    
[[https://openalex.org/A5104049478][Jialin Dong]], [[https://openalex.org/A5018962276][Shihong Yue]], No host. None(None)] 2024. https://doi.org/10.23919/ccc63176.2024.10661943 
     
No abstract    

    

* Facile Synthesis of Ir-Based High-Entropy Alloy Nanomaterials Towards for Oxygen Evolution Electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402435814
:TOPICS: Electrocatalysis for Energy Conversion, Supercritical Water Gasification for Hydrogen Production, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4953778")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402435814"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402435814"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402435814"))][Get cited by]]

OpenAlex: https://openalex.org/W4402435814 (Open access: False)
    
[[https://openalex.org/A5071473961][Xiaodong Hao]], [[https://openalex.org/A5028461520][Yuzhao Qi]], [[https://openalex.org/A5076903055][Shukai Ding]], [[https://openalex.org/A5063605507][Shufang Ma]], [[https://openalex.org/A5029833193][Bingshe Xu]], [[https://openalex.org/A5025713069][Bosheng Zhang]], [[https://openalex.org/A5065440567][Qigao Cao]], [[https://openalex.org/A5053417225][Panchao Zhao]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4953778 
     
No abstract    

    

* Constructing novel metal-free HCOF-Ph@g-C3N4 heterojunctions through molecular expansion to enhance photogenerated carrier involved molecular oxygen activation and photocatalytic hydrogen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402437806
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.susmat.2024.e01115")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402437806"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402437806"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402437806"))][Get cited by]]

OpenAlex: https://openalex.org/W4402437806 (Open access: False)
    
[[https://openalex.org/A5035419178][Qingmei Tang]], [[https://openalex.org/A5029885748][Qingrong Cheng]], [[https://openalex.org/A5068445612][Zhi‐Quan Pan]], Sustainable materials and technologies. None(None)] 2024. https://doi.org/10.1016/j.susmat.2024.e01115 
     
No abstract    

    

* Selective Electrochemical Conversion of Co2 to Formate Via Redox-Modulated Porous Metal Electrodes Coupled with Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402439828
:TOPICS: Electrochemical Reduction of CO2 to Fuels, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4953570")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402439828"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402439828"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402439828"))][Get cited by]]

OpenAlex: https://openalex.org/W4402439828 (Open access: False)
    
[[https://openalex.org/A5014751746][Sabahat Asif]], [[https://openalex.org/A5055839292][Ifra Bashir]], [[https://openalex.org/A5085249589][Syed Zajif Hussain]], [[https://openalex.org/A5019765811][Senem Çïtoğlu]], [[https://openalex.org/A5001507251][Hatïce Duran]], [[https://openalex.org/A5086925656][Ingo Lieberwirth]], [[https://openalex.org/A5079617191][Habib ur Rehman]], [[https://openalex.org/A5020589974][Bien Tan]], [[https://openalex.org/A5033915531][Irshad Hussain]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4953570 
     
No abstract    

    

* In-situ surface activation of polycrystalline LaNiO3 electrocatalyst for the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402440638
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.09.038")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402440638"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402440638"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402440638"))][Get cited by]]

OpenAlex: https://openalex.org/W4402440638 (Open access: True)
    
[[https://openalex.org/A5092350462][Giuditta De Amicis]], [[https://openalex.org/A5090199124][Anna Testolin]], [[https://openalex.org/A5102528879][Cristina Cazzaniga]], [[https://openalex.org/A5031244506][F. D’Acapito]], [[https://openalex.org/A5045284208][Alessandro Minguzzi]], [[https://openalex.org/A5002558002][Paolo Ghigna]], [[https://openalex.org/A5016496410][Alberto Vertova]], International Journal of Hydrogen Energy. 87(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.09.038 
     
No abstract    

    

* Composition Dependent Synergistic Effects on Oxygen Evolution Reaction Catalysis for CaFe<sub>1–</sub><i><sub>x</sub></i>Mn<i><sub>x</sub></i>O<sub>3</sub>  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402444163
:TOPICS: Catalytic Nanomaterials, Solid Oxide Fuel Cells, Magnetocaloric Materials Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2109/jcersj2.24069")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402444163"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402444163"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402444163"))][Get cited by]]

OpenAlex: https://openalex.org/W4402444163 (Open access: True)
    
[[https://openalex.org/A5025262517][Asuka Ochi]], [[https://openalex.org/A5076065370][Shukuji Asakura]], [[https://openalex.org/A5045212575][Manami Goto]], [[https://openalex.org/A5054675462][Shunsuke Yagi]], [[https://openalex.org/A5083459020][Ikuya Yamada]], [[https://openalex.org/A5021785936][Hidekazu Ikeno]], Journal of the Ceramic Society of Japan. None(None)] 2024. https://doi.org/10.2109/jcersj2.24069 
     
No abstract    

    

* Energy-Induced Phase-Control Syntheses of Single-Phase NixRu1–x Solid Solutions and Active-Moderate-Sites Synergy in the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402447144
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-09-10
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.chemmater.4c02027")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402447144"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402447144"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402447144"))][Get cited by]]

OpenAlex: https://openalex.org/W4402447144 (Open access: False)
    
[[https://openalex.org/A5100350527][Yuhan Liu]], [[https://openalex.org/A5039008201][Wenfang Zhai]], [[https://openalex.org/A5102176377][Panpan Cui]], [[https://openalex.org/A5054823742][Zhengfei Dai]], [[https://openalex.org/A5054823742][Zhengfei Dai]], [[https://openalex.org/A5066123069][Bo Huang]], Chemistry of Materials. None(None)] 2024. https://doi.org/10.1021/acs.chemmater.4c02027 
     
No abstract    

    

* Activating Lattice Oxygen Oxidation Mechanism in Asymmetric [IrO6] Octahedra of Ir‐Based Oxides Toward Superior Acidic Electrochemical Water Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402449034
:TOPICS: Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202402902")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402449034"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402449034"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402449034"))][Get cited by]]

OpenAlex: https://openalex.org/W4402449034 (Open access: False)
    
[[https://openalex.org/A5100685994][Yuying Liu]], [[https://openalex.org/A5100383199][Ziyi Liu]], [[https://openalex.org/A5100368015][Na Li]], [[https://openalex.org/A5068812098][Chao Wang]], [[https://openalex.org/A5100376817][Huijuan Wang]], [[https://openalex.org/A5020016810][Qianqian Ji]], [[https://openalex.org/A5073116374][Fengchun Hu]], [[https://openalex.org/A5069910699][Hao Tan]], [[https://openalex.org/A5100762392][Xiansong Liu]], [[https://openalex.org/A5100747209][Chenglong Liu]], [[https://openalex.org/A5100382345][Zhi Li]], [[https://openalex.org/A5066350763][Sihua Feng]], [[https://openalex.org/A5035223262][Bing Tang]], [[https://openalex.org/A5100737796][Ruiqi Liu]], [[https://openalex.org/A5063285667][Liyang Lv]], [[https://openalex.org/A5066996088][Weiren Cheng]], [[https://openalex.org/A5052333339][Wensheng Yan]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202402902 
     
Abstract The activation of lattice oxygen oxidation mechanism (LOM) will endow iridium‐based electrocatalysts with desired acid‐available water oxidation activity, compared to the conventional adsorbate evolution mechanism (AEM). However, the inherent symmetric [IrO 6 ] octahedra of commercial Ir‐based catalysts generally thermodynamically favor the AEM pathway contributing to the moderate water oxidation performance. Here, based on typical layered Ca 2 IrO 4 (CIO) modeled materials, the d ‐orbitals electron repulsion strategy is demonstrated, via constructing asymmetrically polarized Ir‒O‒Ru configuration in Ru‐CIO, to effectively activate the lattice oxygen participating in water oxidation process for decent oxygen‐related electrocatalytic activity. Specifically, a great increase of ≈700‐fold and ≈170‐fold in mass activity and turnover frequency, respectively, has been realized for the optimal Ru‐CIO electrocatalyst in an acid medium relative to the commercial IrO 2 electrocatalysts, where a small overpotential of only 175 mV is required for achieving 10 mA cm geo ‒2 . In situ X‐ray fine structure spectroscopies combined with in situ 18 O‐ isotope‐labeled differential electrochemical mass spectrometry analyses reveal that desirable LOM has been boosted by the activated lattice oxygen and the flexible Ir (3+δ)+ active sites of asymmetric [IrO 6 ] octahedra, which results in superior OER kinetics for Ir‐based oxide catalysts.    

    

* Effect of Iron Doping in Ordered Nickel Oxide Thin Film Catalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402449530
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.4c02572")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402449530"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402449530"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402449530"))][Get cited by]]

OpenAlex: https://openalex.org/W4402449530 (Open access: True)
    
[[https://openalex.org/A5087081787][Ane Etxebarria]], [[https://openalex.org/A5065494944][Mauricio López Luna]], [[https://openalex.org/A5090694870][Andrea Martini]], [[https://openalex.org/A5042706943][Uta Hejral]], [[https://openalex.org/A5076226674][Martina Rüscher]], [[https://openalex.org/A5069389722][Chao Zhan]], [[https://openalex.org/A5055020562][Antonia Herzog]], [[https://openalex.org/A5015258087][Afshan Jamshaid]], [[https://openalex.org/A5021040709][David Kordus]], [[https://openalex.org/A5012003003][Arno Bergmann]], [[https://openalex.org/A5041824875][H. Kuhlenbeck]], [[https://openalex.org/A5065326930][Beatriz Roldán Cuenya]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.4c02572 
     
No abstract    

    

* Controlling Surface Wetting in High-Alkaline Electrolytes for Single Facet Pt Oxygen Evolution Electrocatalytic Activity Mapping by Scanning Electrochemical Cell Microscopy  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402460501
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4sc04407j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402460501"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402460501"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402460501"))][Get cited by]]

OpenAlex: https://openalex.org/W4402460501 (Open access: True)
    
[[https://openalex.org/A5040750842][Geovane Arruda de Oliveira]], [[https://openalex.org/A5053830925][Moonjoo Kim]], [[https://openalex.org/A5048293568][Carla Santana Santos]], [[https://openalex.org/A5011826961][Ndrina Limani]], [[https://openalex.org/A5016428798][Taek Dong Chung]], [[https://openalex.org/A5033898814][Emmanuel Batsa Tetteh]], [[https://openalex.org/A5035321019][Wolfgang Schuhmann]], Chemical Science. None(None)] 2024. https://doi.org/10.1039/d4sc04407j 
     
Scanning electrochemical cell microscopy (SECCM) has been used to explore structure-electrocatalytic activity relationships through high-resolution mapping of local activities of electrocatalysts. However, utilizing SECCM in strongly alkaline conditions presents a...    

    

* Impact of graphene incorporation on the oxygen evolution reaction of Co-Fe-based electrocatalysts synthesized via one-step electrodeposition  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402465059
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.08.503")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402465059"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402465059"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402465059"))][Get cited by]]

OpenAlex: https://openalex.org/W4402465059 (Open access: False)
    
[[https://openalex.org/A5091950182][Mohammad Jahanbazi Goujani]], [[https://openalex.org/A5039343862][Morteza Alizadeh]], [[https://openalex.org/A5079360727][Shima Pashangeh]], International Journal of Hydrogen Energy. 87(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.08.503 
     
No abstract    

    

* Surface oxygen-doping induced atom migration of iron-nickel sulfides with tailored d-band center for enhanced oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402468872
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.155272")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402468872"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402468872"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402468872"))][Get cited by]]

OpenAlex: https://openalex.org/W4402468872 (Open access: False)
    
[[https://openalex.org/A5071749377][Q. Chen]], [[https://openalex.org/A5101532318][Jinghan Zhang]], [[https://openalex.org/A5100652206][Qicheng Zhang]], [[https://openalex.org/A5100670081][Bin Chen]], [[https://openalex.org/A5071504062][Wenchao Peng]], [[https://openalex.org/A5100688703][Yang Li]], [[https://openalex.org/A5060247796][Xiaobin Fan]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.155272 
     
No abstract    

    

* Exploring Discharged Dry Cell as an Electrocatalyst for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402472684
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/2053-1591/ad7a56")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402472684"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402472684"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402472684"))][Get cited by]]

OpenAlex: https://openalex.org/W4402472684 (Open access: True)
    
[[https://openalex.org/A5080158948][Pitchiah Esakki Karthik]], [[https://openalex.org/A5013014074][Sanjit Mondal]], [[https://openalex.org/A5010100785][Lipipuspa Sahoo]], Materials Research Express. None(None)] 2024. https://doi.org/10.1088/2053-1591/ad7a56 
     
Abstract Transition metal compounds with a high affinity for oxygen in dry cell configurations, such as MnO2, Mn3O4, and ZnxMn3O4−x, exhibit exceptional electrocatalytic properties in the oxygen evolution reaction (OER). However, the disposal of these dry cell materials, unlike that of rechargeable batteries, poses environmental hazards. In this study, we focused on optimizing these manganese oxides for energy-related applications, specifically OER. To achieve this goal, we investigated the electrocatalytic behaviour of both used and fresh dry cells in OER. Our results show that the used dry cell material achieved a current density of 10 mA·cm−2 at an overpotential of 525 mV, whereas the fresh dry cell required an overpotential 100 mV higher to reach the same current density. We further characterized the nature of these fresh and used materials using various techniques, including X-ray diffraction (XRD), scanning electron microscopy (SEM), thermogravimetric analysis (TGA), Raman spectroscopy, Fourier-transform infrared spectroscopy (FT-IR), and contact angle measurements. The enhanced activity of the used dry cell can be attributed to the formation of highly active Mn3O4 from MnO2 and graphene oxide under discharging conditions.    

    

* Nickel–Iron Layered Double Hydroxides/Nickel Sulfide Heterostructured Electrocatalysts on Surface-Modified Ti Foam for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402474891
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c08215")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402474891"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402474891"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402474891"))][Get cited by]]

OpenAlex: https://openalex.org/W4402474891 (Open access: True)
    
[[https://openalex.org/A5093613204][Habib Gemechu Edao]], [[https://openalex.org/A5079358114][Chia-Yu Chang]], [[https://openalex.org/A5027860241][Woldesenbet Bafe Dilebo]], [[https://openalex.org/A5026201499][Fikiru Temesgen Angerasa]], [[https://openalex.org/A5069681139][Endalkachew Asefa Moges]], [[https://openalex.org/A5082309206][Yosef Nikodimos]], [[https://openalex.org/A5107157374][Chemeda Barasa Guta]], [[https://openalex.org/A5048665495][Keseven Lakshmanan]], [[https://openalex.org/A5064103813][Jeng‐Lung Chen]], [[https://openalex.org/A5011428472][Meng‐Che Tsai]], [[https://openalex.org/A5031136629][Wei‐Nien Su]], [[https://openalex.org/A5030917995][Bing‐Joe Hwang]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c08215 
     
Electrochemical approaches for generating hydrogen from water splitting can be more promising if the challenges in the anodic oxygen evolution reaction (OER) can be harnessed. The interface heterostructure materials offer strong electronic coupling and appropriate charge transport at the interface regions, promoting accessible active sites to prompt kinetics and optimize the adsorption-desorption of active species. Herein, we have designed an efficient multi-interface-engineered Ni    

    

* Crystal Facet Regulation and Ru Incorporation of Co3O4 for Acidic Oxygen Evolution Reaction Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402477642
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnanoscienceau.4c00037")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402477642"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402477642"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402477642"))][Get cited by]]

OpenAlex: https://openalex.org/W4402477642 (Open access: True)
    
[[https://openalex.org/A5021614012][Mengting Zhao]], [[https://openalex.org/A5086343002][Hanfeng Liang]], ACS Nanoscience Au. None(None)] 2024. https://doi.org/10.1021/acsnanoscienceau.4c00037 
     
No abstract    

    

* Elucidating Template‐To‐Precursor Interactions for Synthesizing Highly Active Single Atomic Fe─N─C Electrocatalysts for the Oxygen Reduction Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402479297
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1155/2024/8714253")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402479297"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402479297"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402479297"))][Get cited by]]

OpenAlex: https://openalex.org/W4402479297 (Open access: True)
    
[[https://openalex.org/A5101809708][Dong‐Gun Kim]], [[https://openalex.org/A5100611851][Subin Park]], [[https://openalex.org/A5006838631][Yong Nam Choi]], [[https://openalex.org/A5100673477][Eunhee Lee]], [[https://openalex.org/A5053578792][Y.‐H. Cho]], [[https://openalex.org/A5016952605][Jae Young Jung]], [[https://openalex.org/A5076850392][Nam Dong Kim]], [[https://openalex.org/A5056537064][Pil Kim]], [[https://openalex.org/A5066553887][Sung Jong Yoo]], International Journal of Energy Research. 2024(1)] 2024. https://doi.org/10.1155/2024/8714253 
     
Iron‐ and nitrogen‐doped carbon (Fe─N─C) catalysts have garnered attention owing to their high oxygen reduction reaction (ORR) activity, which is comparable to that of Pt/C catalysts. Among the various methods for designing Fe─N─C catalysts, the use of templates has been emphasized as a means to create hierarchical porous structures. This strategy has enabled the achievement of high ORR activity. In this study, we propose a method for manufacturing a catalyst with high ORR activity by maximizing the interactions between commercial silica templates and catalyst precursors. By manipulating the charge on the commercial silica surface and adjusting the pH of the dispersion, the catalyst fabricated through these methods exhibited superior ORR activity compared to Pt/C and recently reported nonprecious metal catalysts. Through diverse physicochemical and electrochemical analyses, we confirmed that this activity stems from the effectively generated hierarchical porous structure and the resulting high density of Fe─N active sites. This catalyst exhibited a kinetic current density of over 2.73 mA cm −2 , which is more than double that of platinum and displayed a high ORR mass activity of 4.49 mA mg −1 . This strategy holds significant potential for application in various carbon‐based materials, paving the way for the development of highly efficient electrochemical energy devices.    

    

* RuO2 with Short‐Range Ordered Tantalum Single Atoms for Enhanced Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402486933
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202403388")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402486933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402486933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402486933"))][Get cited by]]

OpenAlex: https://openalex.org/W4402486933 (Open access: False)
    
[[https://openalex.org/A5100451941][Xuefeng Wang]], [[https://openalex.org/A5100406494][Zijian Li]], [[https://openalex.org/A5008892245][Haeseong Jang]], [[https://openalex.org/A5100751848][Changsheng Chen]], [[https://openalex.org/A5102788609][Shangguo Liu]], [[https://openalex.org/A5100400371][Liu Wang]], [[https://openalex.org/A5100383157][Min Gyu Kim]], [[https://openalex.org/A5037450342][Jaephil Cho]], [[https://openalex.org/A5065424751][Qing Qin]], [[https://openalex.org/A5100674776][Xien Liu]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202403388 
     
Abstract Ruthenium Dioxide (RuO 2 ), as one of the most promising alternatives to IrO 2 , suffers from the severe dissolution and overoxidation of Ru active sites during the acidic oxygen evolution reaction (OER), which hinders its practical application. Herein, the study constructs a short‐range ordered tantalum single atoms‐doped RuO 2 catalyst (Ta‐RuO 2 ) with asymmetric Ru‐O‐Ta(‐O‐Ta) active units for the enhanced acidic OER. The Ta‐RuO 2 catalyst exhibits superior catalytic activity with an overpotential of 201 mV at 10 mA cm −2 and a long‐lasting stability of 280 h. Physical characterizations combined with electrochemical tests reveal that the incorporation of atomically arranged Ta atoms induces significant tensile strain, effectively optimizing the adsorption strength of oxygen‐containing intermediates by regulating the Ru d ‐band center and weakening the Ru‐O covalency, thus boosting the catalytic activity. Furthermore, the formed Ru‐O‐Ta(‐O‐Ta) active local structure is well maintained during the OER process owing to the synergy of strong corrosion resistance of Ta‐O bonds and the electron transfers from Ta to Ru via oxygen bridge stabilizing the Ru sites, contributing to the enhanced stability. This study provides a novel method via incorporation of corrosion‐resistant and short‐range ordered single atoms to significantly enhance the acidic OER stability and activity of cost‐effective catalysts.    

    

* Structural and Compositional Optimization of Fe–Co–Ni Ternary Amorphous Electrocatalysts for Efficient Oxygen Evolution in Anion Exchange Membrane Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402488374
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202405468")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402488374"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402488374"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402488374"))][Get cited by]]

OpenAlex: https://openalex.org/W4402488374 (Open access: False)
    
[[https://openalex.org/A5101696473][Changsoo Lee]], [[https://openalex.org/A5076400736][Young Hwa Yun]], [[https://openalex.org/A5101763187][Se‐Ho Kim]], [[https://openalex.org/A5084913556][Gisu Doo]], [[https://openalex.org/A5056086792][Sechan Lee]], [[https://openalex.org/A5101648082][Hyun-Jeong Park]], [[https://openalex.org/A5101800988][Youngtae Park]], [[https://openalex.org/A5075513547][J. Shin]], [[https://openalex.org/A5045489385][Hyun‐Seok Cho]], [[https://openalex.org/A5070296329][Sang‐Kyung Kim]], [[https://openalex.org/A5001116375][EunAe Cho]], [[https://openalex.org/A5043949541][Chanwon Jung]], [[https://openalex.org/A5031401877][MinJoong Kim]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202405468 
     
Abstract Anion exchange membrane water electrolysis (AEMWE) offers a sustainable path for hydrogen production with advantages such as high current density, dynamic responsiveness, and low‐cost electrocatalysts. However, the development of efficient and durable oxygen evolution reaction (OER) electrocatalysts under operating conditions is crucial for achieving the AEMWE. This study systematically investigated Fe–Co–Ni ternary amorphous electrocatalysts for the OER in AEMWE through a comprehensive material library system comprising 21 composition series. The study aims to explore the relationship between composition, degree of crystallinity, and electrocatalytic activity using ternary contours and binary plots to derive optimal catalysts. The findings reveal that higher Co and lower Fe contents lead to increased structural disorder within the Fe–Co–Ni system, whereas an appropriate amount of Fe addition is necessary for OER activity. It is concluded that the amorphous structure of Fe–Co 3 –Ni possesses an optimal ternary composition and degree of crystallinity to facilitate the OER. Post‐OER analyses reveal that the optimized ternary amorphous structure induces structural reconstruction into an OER‐favorable OOH‐rich surface. The Fe–Co 3 –Ni electrocatalysts exhibit outstanding performances in both half‐cells and single‐cells, with an overpotential of 256 mV at 10 mA cm − 2 and a current density of 2.0 A cm − 2 at 1.89 V, respectively.    

    

* Catalytic ‘gelectrodes’ based on Co and Ni–Fe oxy/hydroxides for sustainable and enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402492776
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta03866e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402492776"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402492776"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402492776"))][Get cited by]]

OpenAlex: https://openalex.org/W4402492776 (Open access: False)
    
[[https://openalex.org/A5059369352][Anu Bovas]], [[https://openalex.org/A5051359400][T. P. Radhakrishnan]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta03866e 
     
‘Gelectrodes’ based on nanocomposites of cobalt oxyhydroxide and nickel–iron hydroxide in chitosan on nickel foam are developed, and their efficient mediation of the oxygen evolution reaction with high and sustainable current densities demonstrated.    

    

* Co-production of hydrogen, oxygen, and electricity via an integrated solar-driven system with decoupled water electrolyzer and Na-Zn ion battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402494176
:TOPICS: Aqueous Zinc-Ion Battery Technology, Hydrogen Energy Systems and Technologies, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.08.062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402494176"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402494176"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402494176"))][Get cited by]]

OpenAlex: https://openalex.org/W4402494176 (Open access: False)
    
[[https://openalex.org/A5002034014][Fei Lv]], [[https://openalex.org/A5081771543][Longjie Liu]], [[https://openalex.org/A5023203847][Jiazhe Wu]], [[https://openalex.org/A5007909496][Pengfei Wang]], [[https://openalex.org/A5101589733][Lixia Pan]], [[https://openalex.org/A5066493240][Dengwei Jing]], [[https://openalex.org/A5021205475][Yubin Chen]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.08.062 
     
No abstract    

    

* Transition metal doped into layered double hydroxide as efficient electrocatalysts for oxygen evolution reaction: A DFT study  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402495714
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.161233")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402495714"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402495714"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402495714"))][Get cited by]]

OpenAlex: https://openalex.org/W4402495714 (Open access: False)
    
[[https://openalex.org/A5100725233][Shilong Li]], [[https://openalex.org/A5066772622][Caiwei Yue]], [[https://openalex.org/A5101561667][Haohao Wang]], [[https://openalex.org/A5034976758][Jirui Du]], [[https://openalex.org/A5047585298][Hongyun Cui]], [[https://openalex.org/A5052819361][Min Pu]], [[https://openalex.org/A5002150542][Ming Lei]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.161233 
     
No abstract    

    

* Synergistic effect of oxygen defects and calabash-like hollow carbon matrix enables VO2 as high-performance cathode for zinc ion battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402496582
:TOPICS: Aqueous Zinc-Ion Battery Technology, Advanced Materials for Smart Windows, Lithium-ion Battery Management in Electric Vehicles
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.09.097")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402496582"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402496582"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402496582"))][Get cited by]]

OpenAlex: https://openalex.org/W4402496582 (Open access: False)
    
[[https://openalex.org/A5040130698][Xiaoqing Liu]], [[https://openalex.org/A5102189063][Ze Xu]], [[https://openalex.org/A5048569180][Jinjiang Wu]], [[https://openalex.org/A5100397195][Kexin Wang]], [[https://openalex.org/A5008927032][Chuang Yu]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.09.097 
     
Vanadium dioxide (VO    

    

* Preparation of hollow CoFe Prussian blue analogues and their derived CoP-FeP nanoboxes as efficient electrocatalysts as oxygen evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402503792
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235454")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402503792"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402503792"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402503792"))][Get cited by]]

OpenAlex: https://openalex.org/W4402503792 (Open access: False)
    
[[https://openalex.org/A5100362565][Shiqi Zhang]], [[https://openalex.org/A5024794473][Ying Cheng]], [[https://openalex.org/A5075456959][Zhiyuan Ni]], [[https://openalex.org/A5060430863][Xuefei Lei]], [[https://openalex.org/A5100439502][Biao Wang]], [[https://openalex.org/A5081185893][Xuanwen Liu]], [[https://openalex.org/A5017651445][Rui Guo]], Journal of Power Sources. 623(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235454 
     
No abstract    

    

* NiFe2O4 in MoSe2 Exhibits Bifunctional Water Oxidation and Oxygen Reduction (OER and ORR) Catalytic Reactions for Energy Applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402506190
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.4c01586")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402506190"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402506190"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402506190"))][Get cited by]]

OpenAlex: https://openalex.org/W4402506190 (Open access: False)
    
[[https://openalex.org/A5059659171][Merin Mary Sebastian]], [[https://openalex.org/A5003489789][Ditty Dixon]], [[https://openalex.org/A5089963600][T. Daniel Thangadurai]], [[https://openalex.org/A5064125049][Nandakumar Kalarikkal]], [[https://openalex.org/A5037699843][Alex Schechter]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.4c01586 
     
No abstract    

    

* Breaking the Bottleneck of Activity and Stability of RuO2-Based Electrocatalysts for Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402507206
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.nanolett.4c03643")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402507206"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402507206"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402507206"))][Get cited by]]

OpenAlex: https://openalex.org/W4402507206 (Open access: False)
    
[[https://openalex.org/A5047902639][Weimo Li]], [[https://openalex.org/A5100600897][Ce Wang]], [[https://openalex.org/A5075456232][Xiaofeng Lu]], Nano Letters. None(None)] 2024. https://doi.org/10.1021/acs.nanolett.4c03643 
     
Electrochemical acidic oxygen evolution reaction (OER) is an important part for water electrolysis utilizing a proton exchange membrane (PEM) apparatus for industrial H    

    

* Insights of oxygen vacancies engineered structural, morphological, and electrochemical attributes of Cr-doped Co3O4 nanoparticles as redox active battery-type electrodes for hybrid supercapacitors  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402508520
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2024.113751")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402508520"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402508520"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402508520"))][Get cited by]]

OpenAlex: https://openalex.org/W4402508520 (Open access: False)
    
[[https://openalex.org/A5031913257][K. Mallikarjuna]], [[https://openalex.org/A5009249208][B. Deva Prasad Raju]], [[https://openalex.org/A5049990132][Mohamed A. Ghanem]], [[https://openalex.org/A5073224842][G.R. Dillip]], [[https://openalex.org/A5067306788][Sang Woo Joo]], Journal of Energy Storage. 100(None)] 2024. https://doi.org/10.1016/j.est.2024.113751 
     
No abstract    

    

* Comprehensive Study on the Electrochemical Evolution, Reaction Kinetics, and Mass Transport at the Anion Exchange Ionomer–Pt Interface for Oxygen Reduction Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402510645
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c10293")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402510645"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402510645"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402510645"))][Get cited by]]

OpenAlex: https://openalex.org/W4402510645 (Open access: False)
    
[[https://openalex.org/A5100353177][Chang Liu]], [[https://openalex.org/A5003585143][Ruimin Ding]], [[https://openalex.org/A5013588765][Xi Yin]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c10293 
     
Understanding the structure evolution, kinetics, and mass transfer for the oxygen reduction reaction (ORR) at the ionomer-catalyst interface is fundamental for the development of anion exchange membrane fuel cells (AEMFCs). Herein, we investigate the structural evolution of ionomer-Pt interfaces during the activation process of polycrystalline Pt (poly-Pt) electrodes and their ORR kinetics and mass transfer characteristics at steady state. The results suggest the ionomer thickness as a critical factor in determining the Pt surface structure and the flux of the O    

    

* Porous Silicon‐Supported Catalytic Materials for Energy Conversion and Storage  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402512252
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401459")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402512252"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402512252"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402512252"))][Get cited by]]

OpenAlex: https://openalex.org/W4402512252 (Open access: False)
    
[[https://openalex.org/A5028123645][Man Wong]], [[https://openalex.org/A5042493730][Wen Ou]], [[https://openalex.org/A5088926552][Zhen‐Tao Yu]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401459 
     
Porous silicon (Si) has a tetrahedral structure similar to that of sp3‐ hybridized carbon atoms in a typical diamond structure, which affords it unique chemical and physical properties including an adjustable intrinsic bandgap, a high‐speed carrier transfer efficiency. It has shown great potential in photocatalysis, rechargeable batteries, solar cells, detectors, and electrocatalysis. This review introduces various porous Si‐supported electrocatalysts and analyzes the reasons why porous Si is used as a new carrier/active sites from the perspectives of its molecular structure, electronic properties, synthesis methods, etc. The electrochemical applications of porous Si‐based electrocatalysts in energy conversion reactions such as hydrogen evolution reaction, oxygen evolution reaction, oxygen reduction reaction, and total water decomposition together with lithium‐ion batteries (LIBs) and supercapacitors in energy storage are summarized. The challenges and future research directions for porous Si are also discussed. This review aims to deepen the understanding of porous Si and promote the development and applications of this new type of Si material.    

    

* Highly Valent Cobalt-manganese Spinel Nanowires Induced by Fluorine-Doping for Durable Acid Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402512599
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.176500")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402512599"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402512599"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402512599"))][Get cited by]]

OpenAlex: https://openalex.org/W4402512599 (Open access: False)
    
[[https://openalex.org/A5003084986][Xufeng Hong]], [[https://openalex.org/A5101587702][Yong Gao]], [[https://openalex.org/A5024680462][Mengyao Ji]], [[https://openalex.org/A5061176165][Jinhan Li]], [[https://openalex.org/A5061529098][Yingshui Yao]], [[https://openalex.org/A5012597202][Zhicheng Yu]], [[https://openalex.org/A5037960542][Kun Chang]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.176500 
     
No abstract    

    

* Restricting the over-oxidation of active sites in high-entropy electrocatalysts towards ultra-stabilized oxygen evolution in alkaline water electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402519737
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05449k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402519737"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402519737"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402519737"))][Get cited by]]

OpenAlex: https://openalex.org/W4402519737 (Open access: False)
    
[[https://openalex.org/A5077648060][Yimin Zhang]], [[https://openalex.org/A5101525739][Jianli Kang]], [[https://openalex.org/A5055438935][Haonan Xie]], [[https://openalex.org/A5101604783][Hongxia Yin]], [[https://openalex.org/A5079408077][Zhijia Zhang]], [[https://openalex.org/A5004914639][Yuhan Ma]], [[https://openalex.org/A5101600096][Guangxin Sun]], [[https://openalex.org/A5044321397][Enzuo Liu]], [[https://openalex.org/A5060352654][Liying Ma]], [[https://openalex.org/A5100458396][Biao Chen]], [[https://openalex.org/A5046671426][Junwei Sha]], [[https://openalex.org/A5102957132][Lihua Qian]], [[https://openalex.org/A5030979204][Wenbin Hu]], [[https://openalex.org/A5000026480][Chunnian He]], [[https://openalex.org/A5090219547][Naiqin Zhao]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta05449k 
     
Based on ionic electronegativity, theoretical calculation guided the synthesis of np-MnFeCoNiCuOOH exhibiting ultra-stabilized oxygen evolution in alkaline water electrolysis.    

    

* Dependence of Oxygen Evolution Reaction Catalysis at Thin Cathodically-Deposited Nickel-Iron-Selenide on Fe in the Alkaline Electrolyte vs. Codeposited Fe  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402520122
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Thin-Film Solar Cell Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.145062")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402520122"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402520122"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402520122"))][Get cited by]]

OpenAlex: https://openalex.org/W4402520122 (Open access: False)
    
[[https://openalex.org/A5045851824][Jihan Dhainy]], [[https://openalex.org/A5049127648][M. El Jamal]], [[https://openalex.org/A5107184729][Issaaf Mouawad]], [[https://openalex.org/A5079295334][Lara I. Halaoui]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.145062 
     
No abstract    

    

* Designing neighboring-site activation of single atom via tunnel ions for boosting acidic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402520438
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-52410-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402520438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402520438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402520438"))][Get cited by]]

OpenAlex: https://openalex.org/W4402520438 (Open access: True)
    
[[https://openalex.org/A5102937378][Yixin Hao]], [[https://openalex.org/A5060265950][Sung‐Fu Hung]], [[https://openalex.org/A5101733772][Luqi Wang]], [[https://openalex.org/A5029117570][Liming Deng]], [[https://openalex.org/A5019148170][Wen‐Jing Zeng]], [[https://openalex.org/A5100408858][Chenchen Zhang]], [[https://openalex.org/A5029202084][Zih‐Yi Lin]], [[https://openalex.org/A5010783003][Chun‐Han Kuo]], [[https://openalex.org/A5100423448][Ye Wang]], [[https://openalex.org/A5101723568][Ying Zhang]], [[https://openalex.org/A5084555578][Han‐Yi Chen]], [[https://openalex.org/A5075628250][Feng Hu]], [[https://openalex.org/A5100318907][Linlin Li]], [[https://openalex.org/A5034879972][Shengjie Peng]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-52410-6 
     
Realizing an efficient turnover frequency in the acidic oxygen evolution reaction by modifying the reaction configuration is crucial in designing high-performance single-atom catalysts. Here, we report a "single atom-double site" concept, which involves an activatable inert manganese atom redox chemistry in a single-atom Ru-Mn dual-site platform with tunnel Ni ions as the trigger. In contrast to conventional single-atom catalysts, the proposed configuration allows direct intramolecular oxygen coupling driven by the Ni ions intercalation effect, bypassing the secondary deprotonation step instead of the kinetically sluggish adsorbate evolution mechanism. The strong bonding of Ni ions activates the inert manganese terminal groups and inhibits the cross-site disproportionation process inherent in the Mn scaffolding, which is crucial to ensure the dual-site platform. As a result, the single-atom Ru-Ni-Mn octahedral molecular sieves catalyst delivers a low overpotential, adequate mass activity and good stability.    

    

* Formation of Core‐Shell Ir@TiO2 Nanoparticles through Hydrogen Treatment as Acidic Oxygen Evolution Reaction Catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402520720
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202408848")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402520720"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402520720"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402520720"))][Get cited by]]

OpenAlex: https://openalex.org/W4402520720 (Open access: True)
    
[[https://openalex.org/A5013626829][Jihyeon Park]], [[https://openalex.org/A5039887129][E Liu]], [[https://openalex.org/A5002888212][Shayan Angizi]], [[https://openalex.org/A5072697794][Ahmed M. Abdellah]], [[https://openalex.org/A5034198209][Ecem Yelekli Kirici]], [[https://openalex.org/A5044827415][Drew Higgins]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202408848 
     
Abstract The transition to a sustainable energy economy requires the availability of renewably produced hydrogen through proton exchange membrane water electrolysis. The techno‐economic viability of this technology requires addressing materials challenges regarding the lack of active and stable catalysts for the electrochemical oxygen evolution reaction (OER) in acidic conditions. Herein, core‐shell iridium/titanium dioxide (Core‐shell Ir@TiO 2 ) catalysts for acidic OER are synthesized through a polyol method to create TiO 2 nanoparticles, followed by urea reduction with Ir, and subsequent annealing in hydrogen. The formation process of the core‐shell structure is observed through in situ environmental transmission electron microscopy under annealing conditions. Ir segregation occurred from an initially blended mixed metal oxide structure to a core‐shell configuration at 500 °C. Core‐shell Ir@TiO 2 showed a three‐fold higher stability number (i.e., S‐number) than commercial IrO x (3.34 × 10 6 versus 1.02 × 10 6 ). Furthermore, an Ir‐mass normalized activity of 1,880 A g Ir −1 at 1.7 V versus RHE is measured for Core‐shell Ir@TiO 2 , compared to 624 A g Ir −1 for commercial IrO x . The developed synthetic route to prepare a composite structure with a TiO 2 core and Ir‐based shell has enabled an Ir content reduction without a compromise in activity and stability, thus offering a promising avenue for developing next‐generation catalysts tailored for acidic water electrolysis.    

    

* Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402532298
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402532298"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402532298"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402532298"))][Get cited by]]

OpenAlex: https://openalex.org/W4402532298 (Open access: False)
    
[[https://openalex.org/A5016040017][Feifan Wang]], [[https://openalex.org/A5101814743][Yukui Zhang]], [[https://openalex.org/A5100378741][Jing Wang]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta05700g 
     
Spin state modulation has been demonstrated an effective strategy to tune the catalytic performance of metal organic frameworks for electrochemical oxygen reduction reaction (OER). However, the undisclosed correlation between spin-state...    

    

* Review for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538460
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Molecular Magnetism and Spintronics, Electron Spin Resonance in Biomolecular Studies
:PUBLICATION_DATE: 2024-09-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v1/review2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538460"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538460"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538460"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538460 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v1/review2 
     
No abstract    

    

* Decision letter for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538465
:TOPICS: Electron Spin Resonance in Biomolecular Studies, Molecular Magnetism and Spintronics, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-09-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v1/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538465"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538465"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538465"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538465 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v1/decision1 
     
No abstract    

    

* Author response for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538479
:TOPICS: Accelerating Materials Innovation through Informatics, Electron Spin Resonance in Biomolecular Studies, Molecular Magnetism and Spintronics
:PUBLICATION_DATE: 2024-09-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v2/response1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538479"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538479"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538479"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538479 (Open access: False)
    
[[https://openalex.org/A5016040017][Feifan Wang]], [[https://openalex.org/A5101814743][Yukui Zhang]], [[https://openalex.org/A5100378741][Jing Wang]], No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v2/response1 
     
No abstract    

    

* Review for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538494
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Molecular Magnetism and Spintronics, Electron Spin Resonance in Biomolecular Studies
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v1/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538494"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538494"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538494"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538494 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v1/review1 
     
No abstract    

    

* Decision letter for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538504
:TOPICS: Electron Spin Resonance in Biomolecular Studies, Molecular Magnetism and Spintronics, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538504"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538504 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v2/decision1 
     
No abstract    

    

* Review for "Correlation between Spin Effect and Catalytic Activity of Two Dimensional Metal Organic Frameworks for Oxygen Evolution Reaction"  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402538882
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Molecular Magnetism and Spintronics, Electron Spin Resonance in Biomolecular Studies
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta05700g/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402538882"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402538882"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402538882"))][Get cited by]]

OpenAlex: https://openalex.org/W4402538882 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d4ta05700g/v2/review1 
     
No abstract    

    

* A Rechargeable Urea‐Assisted Zn‐Air Battery with High Energy Efficiency and Fast‐Charging Enabled by Engineering High‐Energy Interfacial Structures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402542550
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-09-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202410845")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402542550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402542550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402542550"))][Get cited by]]

OpenAlex: https://openalex.org/W4402542550 (Open access: False)
    
[[https://openalex.org/A5000272762][Mingjie Wu]], [[https://openalex.org/A5003409409][Yinghui Xu]], [[https://openalex.org/A5071388400][Jian Luo]], [[https://openalex.org/A5103154463][Siyi Yang]], [[https://openalex.org/A5023395031][Gaixia Zhang]], [[https://openalex.org/A5017404634][Lei Du]], [[https://openalex.org/A5068328164][Huixia Luo]], [[https://openalex.org/A5037920786][Xun Cui]], [[https://openalex.org/A5046799991][Yingkui Yang]], [[https://openalex.org/A5080743510][Shuhui Sun]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202410845 
     
Electrochemical urea oxidation reaction (UOR) offers a promising alternative to the oxygen evolution reaction (OER) in clean energy conversion and storage systems. Nickel‐based catalysts are highly regarded as promising electrocatalysts for the UOR. However, their effectiveness is significantly hindered by the unavoidable self‐oxidation reaction of nickel species during UOR. To address this challenge, we proposed an interface chemistry modulation strategy to boost UOR kinetics by creating a high‐energy interfacial heterostructure. This heterostructure features the incorporation of Ag at the CoOOH@NiOOH heterojunction interface. Strong interactions significantly promote the electron exchanges in the heterointerface between the ‐OH and ‐O. Consequently, the improved electron delocalization led to the formation of stronger bonds between Co sites and urea CO(NH2)2, promoting a preference for urea to occupy Co active sites over OH*. The resulting catalyst, Ag‐CoOOH@NiOOH, affords an ultrahigh UOR activity with a low potential of 1.33 V at 100 mA cm‐2. The fabricated catalyst exhibits a mass activity exceeding that of initial cobalt oxyhydroxide by over 11.9 times. The rechargeable urea‐assisted zinc‐air batteries (ZABs) achieves a record‐breaking energy efficiency of 74.56% at 1 mA cm‐2, remarkable durability (1000 hours at even a current density of 50 mA cm‐2), and quick charge performances.    

    

* Facile Synthesis of Carbon-Coated Nips3 Nanoparticle Electrocatalyst for Highly Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402545967
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4956197")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402545967"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402545967"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402545967"))][Get cited by]]

OpenAlex: https://openalex.org/W4402545967 (Open access: False)
    
[[https://openalex.org/A5100626026][Dongjun Lee]], [[https://openalex.org/A5005654711][Doyeon Lee]], [[https://openalex.org/A5100662247][Wook Kim]], [[https://openalex.org/A5065081264][Seong‐Hyeon Hong]], [[https://openalex.org/A5057076775][Hee Jo Song]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4956197 
     
No abstract    

    

* Origin of Enhanced Oxygen Evolution in Restructured Metal‐Organic Frameworks for Anion Exchange Membrane Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402546461
:TOPICS: Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions, Science and Technology of Capacitive Deionization for Water Desalination
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202413916")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402546461"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402546461"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402546461"))][Get cited by]]

OpenAlex: https://openalex.org/W4402546461 (Open access: False)
    
[[https://openalex.org/A5100414299][Ying Li]], [[https://openalex.org/A5100378741][Jing Wang]], [[https://openalex.org/A5008686232][Xiaolei Hao]], [[https://openalex.org/A5101064771][Xiaopei Xu]], [[https://openalex.org/A5016082953][Lingling Xu]], [[https://openalex.org/A5085459146][Bo Wei]], [[https://openalex.org/A5100784976][Zhongwei Chen]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202413916 
     
Metal‐Organic Frameworks (MOFs), praised for structural flexibility and tunability, are prominent catalyst prototypes for exploring oxygen evolution reaction (OER). Yet, their intricate transformations under OER, especially in industrial high‐current environments, pose significant challenges in accurately elucidating their structure‐activity correlation. Here, we harnessed an electrooxidation process for controllable MOF reconstruction, discovering that Fe doping expedites Ni(Fe)‐MOF structural evolution, accompanied by the elongation of Ni‐O bonds, monitored by in‐situ Raman and UV‐visible spectroscopy. Theoretical modeling further reveals that Fe doping and defect‐induced tensile strain in the NiO6 octahedra augments the metal ds‐Op hybridization, optimizing their adsorption behavior and augmenting OER activity. The reconstructed Ni(Fe)‐MOF, serving as the anode in anion exchange membrane water electrolysis, achieves a noteworthy current density of 3.3 A cm‐2 at 2.2 V while maintaining equally stable operation for 160 h spanning from 0.5 A cm‐2 to 1 A cm‐2. This undertaking elevates our comprehension of OER catalyst reconstruction, furnishing promising avenues for designing highly efficacious catalysts across electrochemical platforms.    

    

* Origin of Enhanced Oxygen Evolution in Restructured Metal‐Organic Frameworks for Anion Exchange Membrane Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402546561
:TOPICS: Electrocatalysis for Energy Conversion, Chemistry and Applications of Metal-Organic Frameworks, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202413916")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402546561"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402546561"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402546561"))][Get cited by]]

OpenAlex: https://openalex.org/W4402546561 (Open access: False)
    
[[https://openalex.org/A5100414294][Ying Li]], [[https://openalex.org/A5047614812][Yang Liu]], [[https://openalex.org/A5008686232][Xiaolei Hao]], [[https://openalex.org/A5101064771][Xiaopei Xu]], [[https://openalex.org/A5016082953][Lingling Xu]], [[https://openalex.org/A5085459146][Bo Wei]], [[https://openalex.org/A5100784976][Zhongwei Chen]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202413916 
     
Metal‐Organic Frameworks (MOFs), praised for structural flexibility and tunability, are prominent catalyst prototypes for exploring oxygen evolution reaction (OER). Yet, their intricate transformations under OER, especially in industrial high‐current environments, pose significant challenges in accurately elucidating their structure‐activity correlation. Here, we harnessed an electrooxidation process for controllable MOF reconstruction, discovering that Fe doping expedites Ni(Fe)‐MOF structural evolution, accompanied by the elongation of Ni‐O bonds, monitored by in‐situ Raman and UV‐visible spectroscopy. Theoretical modeling further reveals that Fe doping and defect‐induced tensile strain in the NiO6 octahedra augments the metal ds‐Op hybridization, optimizing their adsorption behavior and augmenting OER activity. The reconstructed Ni(Fe)‐MOF, serving as the anode in anion exchange membrane water electrolysis, achieves a noteworthy current density of 3.3 A cm‐2 at 2.2 V while maintaining equally stable operation for 160 h spanning from 0.5 A cm‐2 to 1 A cm‐2. This undertaking elevates our comprehension of OER catalyst reconstruction, furnishing promising avenues for designing highly efficacious catalysts across electrochemical platforms.    

    

* Electrospun Mn1-xCoxFe2O4 (x=0-0.7) Nanofibers for Supercapacitors and Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402549944
:TOPICS: Materials for Electrochemical Supercapacitors, Lithium-ion Battery Technology, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matchemphys.2024.129948")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402549944"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402549944"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402549944"))][Get cited by]]

OpenAlex: https://openalex.org/W4402549944 (Open access: False)
    
[[https://openalex.org/A5093713392][Zahra Ansari Jokandan]], [[https://openalex.org/A5085759711][J. Mazloom]], [[https://openalex.org/A5014599906][Morteza Safari]], Materials Chemistry and Physics. None(None)] 2024. https://doi.org/10.1016/j.matchemphys.2024.129948 
     
No abstract    

    

* Fe, Cu bimetallic precursor-driven quaternary active sites boost oxygen reduction / evolution reaction bifunctional catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402550124
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.235423")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402550124"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402550124"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402550124"))][Get cited by]]

OpenAlex: https://openalex.org/W4402550124 (Open access: False)
    
[[https://openalex.org/A5101383673][Yurong Yuan]], [[https://openalex.org/A5026379076][Mengwei Pan]], [[https://openalex.org/A5101509462][Mengjie Zhang]], [[https://openalex.org/A5075343261][Yuchen Zhou]], [[https://openalex.org/A5042495813][Qin Fei-long]], [[https://openalex.org/A5074161773][Yaoyu Yang]], [[https://openalex.org/A5002739525][Rui Hao]], [[https://openalex.org/A5102784975][Weifang Liu]], [[https://openalex.org/A5034594327][Kaiyu Liu]], Journal of Power Sources. 623(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.235423 
     
No abstract    

    

* Recommended practice for measurement and evaluation of oxygen evolution reaction electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402567939
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/eom2.12486")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402567939"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402567939"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402567939"))][Get cited by]]

OpenAlex: https://openalex.org/W4402567939 (Open access: True)
    
[[https://openalex.org/A5072641790][Hongyu An]], [[https://openalex.org/A5021708784][Wanki Park]], [[https://openalex.org/A5077614940][Heejong Shin]], [[https://openalex.org/A5055851063][Dong Young Chung]], EcoMat. None(None)] 2024. https://doi.org/10.1002/eom2.12486 
     
Abstract The Oxygen evolution reaction (OER) is a pivotal technology driving next‐generation sustainable energy conversion and storage devices. Establishing a robust analytical methodology is paramount to fostering innovation in this field. This review offers a comprehensive discussion on measurement and interpretation, advocating for standardized protocols and best practices to mitigate the myriad factors that complicate analysis. The initial focus is directed toward substrate electrodes and gas bubbles, both significant contributors to reduced reliability and reproducibility. Subsequently, the review focuses on intrinsic activity assessment, identification of electrochemical active sites, and the disentanglement of competing process contributions. These careful methodologies ensure the systematic delivery of insights crucial for assessing OER performance. In conclusion, the review highlights the critical role played by precise measurement techniques and unbiased activity comparison methodologies in propelling advancements in OER catalyst development. image    

    

* Influence of aflatoxin B1 on growth, photosynthetic oxygen evolution and regreening of Chlorella fusca  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402490839
:TOPICS: Biological Soil Crusts and their Roles in Ecosystems, Biogeochemical Cycling of Turf Grasses in the United States, Microalgae as a Source for Biofuels Production
:PUBLICATION_DATE: 1992-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5962/p.309334")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402490839"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402490839"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402490839"))][Get cited by]]

OpenAlex: https://openalex.org/W4402490839 (Open access: False)
    
[[https://openalex.org/A5013842174][O. H. Sayed]], [[https://openalex.org/A5040999393][E. M. Fadl-Allah]], Cryptogamie Algologie. 13(1)] 1992. https://doi.org/10.5962/p.309334 
     
No abstract    

    

* Optimizing entropy-stabilized synthesis kinetics to modulate the oxygen evolution mechanism  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402433891
:TOPICS: Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mattod.2024.08.014")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402433891"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402433891"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402433891"))][Get cited by]]

OpenAlex: https://openalex.org/W4402433891 (Open access: True)
    
[[https://openalex.org/A5069619264][Zeshuo Meng]], [[https://openalex.org/A5068379441][Hengyue Xu]], [[https://openalex.org/A5070671117][Zhengyan Du]], [[https://openalex.org/A5043968022][Zijin Xu]], [[https://openalex.org/A5100380901][Jian Xu]], [[https://openalex.org/A5100715935][Wei Zhang]], [[https://openalex.org/A5016312685][Xiaoying Hu]], [[https://openalex.org/A5055251195][Haoteng Sun]], [[https://openalex.org/A5037428389][Hongwei Tian]], [[https://openalex.org/A5006868699][Jingsan Xu]], [[https://openalex.org/A5100617037][Weitao Zheng]], [[https://openalex.org/A5031493683][Sheng Dai]], Materials Today. None(None)] 2024. https://doi.org/10.1016/j.mattod.2024.08.014 
     
No abstract    

    

* Dual internal electric field induced by Ni3C selectively deposited onto Mn2O3 on faceted BiVO4 for boosting photocatalytic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402486272
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124589")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402486272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402486272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402486272"))][Get cited by]]

OpenAlex: https://openalex.org/W4402486272 (Open access: False)
    
[[https://openalex.org/A5004659338][Xiaoming Xu]], [[https://openalex.org/A5005485326][Yahui Cheng]], [[https://openalex.org/A5100671241][Xiaoyan Zhu]], [[https://openalex.org/A5016059266][Jiaying Huang]], [[https://openalex.org/A5033570122][Bowen Zhu]], [[https://openalex.org/A5056821526][Jingjing Meng]], [[https://openalex.org/A5055487387][Junshan Li]], [[https://openalex.org/A5084128430][Guolin Jing]], [[https://openalex.org/A5028603621][Lihui Zheng]], [[https://openalex.org/A5101806079][Shaogui Yang]], [[https://openalex.org/A5100418656][Cheng Sun]], [[https://openalex.org/A5100338539][Xiaohui Li]], [[https://openalex.org/A5078159002][Ruixia Yuan]], [[https://openalex.org/A5004893546][Yongfa Zhu]], Applied Catalysis B Environment and Energy. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124589 
     
No abstract    

    

* Evolution of oxygen and stratification and their relationship in the North Pacific Ocean in CMIP6 Earth system models  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402522349
:TOPICS: Climate Change and Paleoclimatology, Anaerobic Methane Oxidation and Gas Hydrates, Oceanic Modeling and Circulation Studies
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5194/bg-21-3985-2024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402522349"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402522349"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402522349"))][Get cited by]]

OpenAlex: https://openalex.org/W4402522349 (Open access: True)
    
[[https://openalex.org/A5045710398][Lyuba Novi]], [[https://openalex.org/A5073045368][Annalisa Bracco]], [[https://openalex.org/A5049005458][Takamitsu Ito]], [[https://openalex.org/A5063962207][Yohei Takano]], Biogeosciences. 21(17)] 2024. https://doi.org/10.5194/bg-21-3985-2024 
     
Abstract. This study examines the linkages between the upper-ocean (0–200 m) oxygen (O2) content and stratification in the North Pacific Ocean using four Earth system models (ESMs), an ocean hindcast simulation, and an ocean reanalysis. The trends and variability in oceanic O2 content are driven by the imbalance between physical supply and biological demand. Physical supply is primarily controlled by ocean ventilation, which is responsible for the transport of O2-rich surface waters to the subsurface. Isopycnic potential vorticity (IPV), a quasi-conservative tracer proportional to density stratification that can be evaluated from temperature and salinity measurements, is used herein as a dynamical proxy for ocean ventilation. The predictability potential of the IPV field is evaluated through its information entropy. The results highlight a strong O2–IPV connection and somewhat higher (as compared to the rest of the basin) predictability potential for IPV across the tropical Pacific, where the El Niño–Southern Oscillation occurs. This pattern of higher predictability and strong anticorrelation between O2 and stratification is robust across multiple models and datasets. In contrast, IPV at mid-latitudes has low predictability potential and its center of action differs from that of O2. In addition, the locations of extreme events or hotspots may or may not differ between the two fields, with a strong model dependency, which persists in future projections. On the one hand, these results suggest that it may be possible to monitor ocean O2 in the tropical Pacific based on a few observational sites co-located with the more abundant IPV measurements; on the other, they lead us to question the robustness of the IPV–O2 relationship in the extratropics. The proposed framework helps to characterize and interpret O2 variability in relation to physical variability and may be especially useful in the analysis of new observation-based data products derived from the BGC-Argo float array in combination with the traditional but far more abundant Argo data.    

    

* Oxygen-induced evolution of anammox granular sludge explains its unique responses during preservation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402533251
:TOPICS: Microbial Nitrogen Cycling in Wastewater Treatment Systems, Application of Constructed Wetlands for Wastewater Treatment
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.watres.2024.122447")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402533251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402533251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402533251"))][Get cited by]]

OpenAlex: https://openalex.org/W4402533251 (Open access: False)
    
[[https://openalex.org/A5012427370][Leiyan Guo]], [[https://openalex.org/A5101594693][Chao Pan]], [[https://openalex.org/A5100392071][Wei Wang]], [[https://openalex.org/A5100411379][Yang Yu]], [[https://openalex.org/A5030367743][Dongdong Xu]], [[https://openalex.org/A5037687318][Wenda Chen]], [[https://openalex.org/A5101707590][Wenji Li]], [[https://openalex.org/A5100688078][Ping Zheng]], [[https://openalex.org/A5100437750][Meng Zhang]], Water Research. None(None)] 2024. https://doi.org/10.1016/j.watres.2024.122447 
     
No abstract    

    

* Understanding the evolution of molybdenum-nitrogen doped carbon with long-term durability for efficient oxygen reduction reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402546983
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.155778")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402546983"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402546983"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402546983"))][Get cited by]]

OpenAlex: https://openalex.org/W4402546983 (Open access: False)
    
[[https://openalex.org/A5039256728][Xingyu Luo]], [[https://openalex.org/A5032925772][Bingbao Mei]], [[https://openalex.org/A5102219039][Ru Feng]], [[https://openalex.org/A5070471951][Xiaofeng Xu]], [[https://openalex.org/A5090182164][Zhongyan Zhang]], [[https://openalex.org/A5083029433][Mingyu Ou]], [[https://openalex.org/A5073162955][Fanfei Sun]], [[https://openalex.org/A5052267311][Huajun Zheng]], [[https://openalex.org/A5068056660][Meiqin Shi]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.155778 
     
No abstract    

    

* MOF-Derived Ni/NiO-C Nanocomposites as Bifunctional Electrocatalysts Capable of Driving Both ORR and OER  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402518343
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c02856")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402518343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402518343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402518343"))][Get cited by]]

OpenAlex: https://openalex.org/W4402518343 (Open access: False)
    
[[https://openalex.org/A5034154670][Sagarmani Rasaily]], [[https://openalex.org/A5085239724][Shivanand Chettri]], [[https://openalex.org/A5001575217][Debesh Sharma]], [[https://openalex.org/A5031222788][Khanindram Baruah]], [[https://openalex.org/A5056511280][Rajani Dewan]], [[https://openalex.org/A5061637624][Sudarsan Tamang]], [[https://openalex.org/A5007779130][Anand Pariyar]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c02856 
     
Bifunctional electrocatalysts, capable of efficiently driving both the oxygen reduction reaction (ORR) and the oxygen evolution reaction (OER), are crucial for advancing electrochemical processes. While noble-metal-based catalysts are widely recognized for their role in oxygen processes, current state-of-the-art designs are limited to either ORR or OER activity, presenting a notable research gap. In addressing this challenge, we have developed a novel    

    

* Isolated Octahedral Pt-Induced Electron Transfer to Ultralow-Content Ruthenium-Doped Spinel Co3O4 for Enhanced Acidic Overall Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402507216
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/jacs.4c07089")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402507216"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402507216"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402507216"))][Get cited by]]

OpenAlex: https://openalex.org/W4402507216 (Open access: False)
    
[[https://openalex.org/A5100446377][Di Li]], [[https://openalex.org/A5017666924][Da‐Zhen Xu]], [[https://openalex.org/A5006399803][Yuhou Pei]], [[https://openalex.org/A5100652206][Qicheng Zhang]], [[https://openalex.org/A5032392383][Yingying Lü]], [[https://openalex.org/A5048496954][Bing Zhang]], Journal of the American Chemical Society. None(None)] 2024. https://doi.org/10.1021/jacs.4c07089 
     
The development of a highly active and stable oxygen evolution reaction (OER) electrocatalyst is desirable for sustainable and efficient hydrogen production via proton exchange membrane water electrolysis (PEMWE) powered by renewable electricity yet challenging. Herein, we report a robust Pt/Ru-codoped spinel cobalt oxide (PtRu-Co    

    

* Factorial Optimization of CoCuFe-LDH/Graphene Ternary Composites as Electrocatalysts for Water Splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402478012
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Catalytic Reduction of Nitro Compounds, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c10870")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402478012"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402478012"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402478012"))][Get cited by]]

OpenAlex: https://openalex.org/W4402478012 (Open access: True)
    
[[https://openalex.org/A5003640881][Daniele Alves]], [[https://openalex.org/A5010732323][Rafael de Andrade Moral]], [[https://openalex.org/A5093834938][Darshana Jayakumari]], [[https://openalex.org/A5055426199][Eithne Dempsey]], [[https://openalex.org/A5062098315][Carmel B. Breslin]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c10870 
     
The layered double hydroxides (LDHs) have demonstrated significant potential as non-noble-metal electrocatalysts for the hydrogen evolution reaction (HER) and oxygen evolution reaction (OER). Their unique compositional and structural properties contribute to their efficiency and stability as catalysts. In this study, CoCuFe-LDH composites were grown on graphene (G) via a cost-effective and straightforward one-step hydrothermal process. A 2-level full-factorial model was employed to determine the impact of Co (1.5, 3, and 4.5 mmol) and graphene (10, 30, and 50 mg) concentrations on the onset potential of OER and HER, which were the chosen response variables. OER and HER activity variabilities were assessed in triplicate using Co    

    

* Gas Evolution in Water Electrolysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402453997
:TOPICS: Hydrogen Energy Systems and Technologies, Electrocatalysis for Energy Conversion, Materials and Methods for Hydrogen Storage
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.chemrev.4c00211")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402453997"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402453997"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402453997"))][Get cited by]]

OpenAlex: https://openalex.org/W4402453997 (Open access: False)
    
[[https://openalex.org/A5003067415][Paul A. Kempler]], [[https://openalex.org/A5049904697][Robert H. Coridan]], [[https://openalex.org/A5075263309][Long Luo]], Chemical Reviews. None(None)] 2024. https://doi.org/10.1021/acs.chemrev.4c00211 
     
Gas bubbles generated by the hydrogen evolution reaction and oxygen evolution reaction during water electrolysis influence the energy conversion efficiency of hydrogen production. Here, we survey what is known about the interaction of gas bubbles and electrode surfaces and the influence of gas evolution on practicable devices used for water electrolysis. We outline the physical processes occurring during the life cycle of a bubble, summarize techniques used to characterize gas evolution phenomena in situ and in practical device environments, and discuss ways that electrodes can be tailored to facilitate gas removal at high current densities. Lastly, we review efforts to model the behavior of individual gas bubbles and multiphase flows produced at gas-evolving electrodes. We conclude our review with a short summary of outstanding questions that could be answered by future efforts to characterize gas evolution in electrochemical device environments or by improved simulations of multiphase flows.    

    

* Ru@NiMoS aggregate with boosted electrochemical catalysis for enhanced electrochemiluminescence and lidocaine detection  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402498837
:TOPICS: DNA Nanotechnology and Bioanalytical Applications, Electrochemical Detection of Heavy Metal Ions, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smo.20240011")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402498837"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402498837"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402498837"))][Get cited by]]

OpenAlex: https://openalex.org/W4402498837 (Open access: True)
    
[[https://openalex.org/A5041191007][Yongzhuang Lu]], [[https://openalex.org/A5100324834][Haoran Wang]], [[https://openalex.org/A5072699746][Qiyao Li]], [[https://openalex.org/A5100318569][Qian Liu]], [[https://openalex.org/A5100372782][Xiaoxu Zhang]], [[https://openalex.org/A5078458939][Yuying Jia]], [[https://openalex.org/A5050967725][X.D. Cai]], [[https://openalex.org/A5076870814][Zheng Zhao]], [[https://openalex.org/A5020219378][Yanfu Huan]], [[https://openalex.org/A5089379373][Ben Zhong Tang]], Smart Molecules. None(None)] 2024. https://doi.org/10.1002/smo.20240011 
     
Abstract A binder‐free Ru@NiMoS electrode was engineered by in situ growth of two‐dimensional NiMoS nanosheets on nickel foam. This process effectively promoted the electrostatic‐driven aggregation of Ru(bpy) 3 2+ , harnessing the synergistic effect to enhance electrochemiluminescence (ECL) performance. The integration (Ru@NiMoS) achieved an impressive ECL efficiency of 70.1%, marking an impressive 36.9‐fold enhancement over conventional Ru. Additionally, its ECL intensity was found to be remarkably 172.2 times greater than that of Ru. Within the Ru(bpy) 3 2+ /TPA system, NiMoS emerged as a pivotal electrochemical catalyst, markedly boosting both the oxygen evolution reaction and the generation of reactive intermediates. Leveraging these distinctive properties, a highly efficient ECL sensor for lidocaine detection was developed. This sensor exhibited a linear response within the concentration range of 1 nM to 1 μM and achieved a remarkably low detection limit of 0.22 nM, underlining its substantial potential for practical application.    

    

* Catalytic Properties of Polyampholytes, Polyampholyte-Metal Complexes, Polyampholyte-Metal Nanoparticles and Polyampholyte-Enzyme Conjugates: a Mini-Review  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402527974
:TOPICS: Catalytic Reduction of Nitro Compounds, Dendrimer-Encapsulated Nanoparticles and Hyperbranched Polymers
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.31489/2959-0663/3-24-8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402527974"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402527974"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402527974"))][Get cited by]]

OpenAlex: https://openalex.org/W4402527974 (Open access: False)
    
[[https://openalex.org/A5045844357][Sarkyt E. Kudaibergenov]], Eurasian Journal of Chemistry. None(None)] 2024. https://doi.org/10.31489/2959-0663/3-24-8 
     
This mini-review briefly discusses the catalytic properties of polyampholytes, polyampholyte-metal complexes, polyampholyte-metal nanoparticles and polyampholyte-catalase conjugates. Polyampholyte-based catalysts can mimic enzyme functions, facilitating reactions like hydrolysis, decomposition, hydrogenation, and oxidation of various substrates. Special focus is given to amphoteric hydrogels and cryogels that encapsulate metal nanoparticles or enzymes. These materials have demonstrated effectiveness in the hydrogenation of nitroaromatic compounds, oxidation of disulfide and aliphatic (or aromatic) alcohols under mild conditions, both in batch and flow-through reactors. Kinetic parameters, turnover numbers (TON), turnover frequencies (TOF), and activation energies are presented for a series of specific catalytic processes. Notably, flow-through reactors exhibit significantly higher catalytic efficiency compared to batch reactors and can be used continuously for extended periods. Additionally, the review explores the potential of light-driven hydrogen and oxygen evolution reactions from water, facilitated by metal nanoparticles within amphoteric hydrogels in the presence of photosensitizers.    

    

* Ni3S2 particle–embedded nanotubes as a high-performance electrocatalyst for overall water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402454503
:TOPICS: Electrocatalysis for Energy Conversion, Ammonia Synthesis and Electrocatalysis, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0225168")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402454503"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402454503"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402454503"))][Get cited by]]

OpenAlex: https://openalex.org/W4402454503 (Open access: True)
    
[[https://openalex.org/A5068834260][Pengcheng Zhu]], [[https://openalex.org/A5100339226][Li Ye]], [[https://openalex.org/A5100366463][Xiaolei Li]], [[https://openalex.org/A5101917711][Tianxing Wang]], [[https://openalex.org/A5072198685][Zhong Yao]], [[https://openalex.org/A5062499493][Lin Zhuang]], APL Materials. 12(9)] 2024. https://doi.org/10.1063/5.0225168 
     
Hydrogen evolution reactions (HERs) and oxygen evolution reactions (OERs) are crucial for renewable energy production. Developing stable, cost-effective, and highly catalytic HER and OER electrocatalysts is paramount. In this study, a combination of hydrothermal synthesis and annealing was used to fabricate nickel sulfide (Ni3S2) particle–embedded nanotubes supported on nickel (Ni) foam (Ni3S2 PN/NF). The Ni3S2 PN/NF structures featured a highly branched morphology with a large specific surface area, surpassing that of conventional Ni metal nanotubes. This design increased the number of reactive sites and enhanced the charge-transfer process. The Ni foam substrate expanded the contact area of Ni3S2, thereby improving conductivity and facilitating the adsorption/desorption of intermediates on the Ni3S2 surface. Density functional theory calculations showed that the electronic structure of Ni3S2 provides excellent conductivity. Moreover, the multi-branched structure and inherent conductivity of the NiS nanomaterials enhanced the Ni3S2 PN/NF performance in 1M KOH, with overpotentials of 87 and 210 mV with iR compensation at 10 mA cm−2 for the HER and OER, respectively. The synthesized Ni3S2 PN/NF also exhibited robust durability for 20 h. These results demonstrate that Ni3S2 PN/NF is an excellent catalyst for both HER and OER.    

    

* Unveiling crystal orientation-dependent interface property in composite cathodes for solid-state batteries by in situ microscopic probe  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402441219
:TOPICS: Lithium Battery Technologies, Lithium-ion Battery Technology, Lithium-ion Battery Management in Electric Vehicles
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-52226-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402441219"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402441219"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402441219"))][Get cited by]]

OpenAlex: https://openalex.org/W4402441219 (Open access: True)
    
[[https://openalex.org/A5016915776][Sunyoung Lee]], [[https://openalex.org/A5061327803][Hayoung Park]], [[https://openalex.org/A5100319275][Jae Young Kim]], [[https://openalex.org/A5042627473][Jihoon Kim]], [[https://openalex.org/A5084253035][Min‐Ju Choi]], [[https://openalex.org/A5065070843][Sang-Wook Han]], [[https://openalex.org/A5002466144][Sewon Kim]], [[https://openalex.org/A5088144082][Wonju Kim]], [[https://openalex.org/A5017376744][Ho Won Jang]], [[https://openalex.org/A5100650928][Jungwon Park]], [[https://openalex.org/A5073090248][Kisuk Kang]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-52226-4 
     
A critical bottleneck toward all-solid-state batteries lies in how the solid(electrode)-solid(electrolyte) interface is fabricated and maintained over repeated cycles. Conventional composite cathodes, with crystallographically distinct electrode/electrolyte interfaces of random particles, create complexities with varying (electro)chemical compatibilities. To address this, we employ an epitaxial model system where the crystal orientations of cathode and solid electrolyte are precisely controlled, and probe the interfaces in real-time during co-sintering by in situ electron microscopy. The interfacial reaction is highly dependent on crystal orientation/alignment, especially the availability of open ion channels. Interfaces bearing open ion paths of NCM are more susceptible to interdiffusion, but stabilize with the early formed passivation layer. Conversely, interfaces with closed ion pathway exhibit stability at intermediate temperatures, but deteriorate rapidly at high temperature due to oxygen evolution, increasing interfacial resistance. The elucidation of these distinct interfacial behaviors emphasizes the need for decoupling collective interfacial properties to enable rational design in solid-state batteries.    

    

* Processing of molybdenum industrial waste into sustainable and efficient nanocatalysts for water electrolysis reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402499807
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s12274-024-6972-z")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402499807"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402499807"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402499807"))][Get cited by]]

OpenAlex: https://openalex.org/W4402499807 (Open access: True)
    
[[https://openalex.org/A5052008093][F. Ursino]], [[https://openalex.org/A5086082391][Giacometta Mineo]], [[https://openalex.org/A5025473062][Antonino Scandurra]], [[https://openalex.org/A5078115818][M. Scuderi]], [[https://openalex.org/A5093934161][Angelo Forestan]], [[https://openalex.org/A5102832747][Catya Alba]], [[https://openalex.org/A5002812574][R. Reitano]], [[https://openalex.org/A5026110528][A. Terrasi]], [[https://openalex.org/A5012394754][S. Mirabella]], Nano Research. None(None)] 2024. https://doi.org/10.1007/s12274-024-6972-z 
     
Abstract The increasing need for sustainable energy and the transition from a linear to a circular economy pose great challenges to the materials science community. In this view, the chance of producing efficient nanocatalysts for water splitting using industrial waste as starting material is attractive. Here, we report low-cost processes to convert Mo-based industrial waste powder into efficient catalysts for oxygen evolution reaction (OER) and hydrogen evolution reaction (HER). pH controlled hydrothermal processing of Mo-based industrial waste powder leads to pure orthorhombic MoO 3 nanobelts (50–200 nm wide, 10 µm long) with promising OER performances at 10 mA·cm −2 with an overpotential of 324 mV and Tafel slope of 45 mV·dec −1 in alkaline electrolyte. Indeed, MoS 2 /MoO 3 nanostructures were obtained after sulfurization during hydrothermal processes of the MoO 3 nanobelts. HER tests in acidic environment show a promising overpotential of 208 mV at 10 mA·cm −2 and a Tafel slope of 94 mV·dec −1 . OER and HER performances of nanocatalysts obtained from Mo industrial waste powder are comparable or better than Mo-based nanocatalysts obtained from pure commercial Mo reagent. This work shows the great potential of reusing industrial waste for energy applications, opening a promising road to join waste management and efficient and sustainable nanocatalysts for water splitting.    

    

* CO2- tolerant CuFe2O4 as Bifunctional Electrocatalyst for Transition from Rechargeable Li-O2 to Li-CO2 Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402489128
:TOPICS: Lithium Battery Technologies, Lithium-ion Battery Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-02
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/1945-7111/ad76e1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402489128"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402489128"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402489128"))][Get cited by]]

OpenAlex: https://openalex.org/W4402489128 (Open access: False)
    
[[https://openalex.org/A5010107953][Pamangadan C. Sharafudeen]], [[https://openalex.org/A5013785396][Snehangshu Patra]], [[https://openalex.org/A5041102656][Perumal Elumalai]], Journal of The Electrochemical Society. 171(9)] 2024. https://doi.org/10.1149/1945-7111/ad76e1 
     
CO 2 -tolerant rechargeable Lithium-Air batteries are seen as a high-performing alternative to Li-ion batteries. They utilize O 2 from the air, reducing it at the cathode to form lithium peroxide (Li 2 O 2 ) during discharge which is then oxidized to form lithium-metal and freeing O 2 during charging. Most of the present studies involve pure O 2 as the cathode material instead of aerial O 2 , which has a stiff-challenge due to atmospheric CO 2 which produces Li 2 CO 3 during discharge, posing a resistive load on the battery if not re-oxidized on charging. Ideally, presence of CO 2 should enhance the charge-storage capacity if it is cycled reversibly. Thus, present research aims at taking advantage of both O 2 and CO 2 by employing metallic Cu on CuFe 2 O 4 catalyst, synthesized from a one-step auto-combustion route. The Cu metal present in the catalyst leads to a low surface-area, yet the catalyst demonstrates excellent oxygen reduction reaction and moderate oxygen evolution reaction activity. excellent CO 2 reduction reaction activity, oxidizing both the Li 2 O 2 and the Li 2 CO 3 during charge in both 10% CO 2 and 100% CO 2 atmospheres. The fabricated Li-CO 2 battery operates for practical application, suggesting the suitability of the catalyst for the transition from practical Li-O 2 battery to Li-Air battery.    

    

* Swelling the d/p‐Band Center Difference Induced by Heterostructure Self‐Optimization Engineering for Enhanced Water Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402483676
:TOPICS: Solar-Powered Water Desalination Technologies, Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202402923")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402483676"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402483676"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402483676"))][Get cited by]]

OpenAlex: https://openalex.org/W4402483676 (Open access: False)
    
[[https://openalex.org/A5091868708][Xuemin Wang]], [[https://openalex.org/A5100394072][Бо Лю]], [[https://openalex.org/A5100368015][Na Li]], [[https://openalex.org/A5100363799][Zhigang Li]], [[https://openalex.org/A5100606174][Cui Zhang]], [[https://openalex.org/A5101781957][Shuangxi Liu]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202402923 
     
Abstract Monitoring the dynamic behavior of active species and modulating their electronic architecture are crucial for the development of efficient catalysts. Here, a 3D ordered multi‐level porous Ni 2 P/CeO 2 heterojunction catalyst with a “self‐optimization effect” is strategically synthesized for efficient oxygen evolution reaction (OER). This catalyst exhibits a low overpotential of 235 mV at 20 mA cm −2 in 1.0 m KOH. During the OER process, the heterojunction catalyst specifically undergoes a unique phase transition involving the leaching of the P element, which triggers the formation of the PO 4 3− ‐NiOOH/CeO 2 catalyst with PO 4 3− adsorbed on the surface of the reconstructed product NiOOH/CeO 2 . Density functional theory calculations reveal that the CeO 2 and adsorbed‐PO 4 3− in the self‐optimized structure are essential and minor factors for enhancing catalytic activity, respectively. They collaborate to promote the redistribution of electron density in surface Ni and O, increasing the d / p ‐band center difference. This phenomenon results in optimized adsorption/desorption of the key intermediates such as *OOH and improved catalytic performance. Overall, this research highlights the potential of d / p ‐band modulation for the rational design of cost‐effective and high‐efficiency electrocatalysts.    

    

* A Rechargeable Urea‐Assisted Zn‐Air Battery with High Energy Efficiency and Fast‐Charging Enabled by Engineering High‐Energy Interfacial Structures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402542551
:TOPICS: Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-09-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202410845")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402542551"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402542551"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402542551"))][Get cited by]]

OpenAlex: https://openalex.org/W4402542551 (Open access: False)
    
[[https://openalex.org/A5000272762][Mingjie Wu]], [[https://openalex.org/A5003409409][Yinghui Xu]], [[https://openalex.org/A5071388400][Jian Luo]], [[https://openalex.org/A5103154463][Siyi Yang]], [[https://openalex.org/A5023395031][Gaixia Zhang]], [[https://openalex.org/A5017404634][Lei Du]], [[https://openalex.org/A5068328164][Huixia Luo]], [[https://openalex.org/A5037920786][Xun Cui]], [[https://openalex.org/A5046799991][Yingkui Yang]], [[https://openalex.org/A5080743510][Shuhui Sun]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202410845 
     
Electrochemical urea oxidation reaction (UOR) offers a promising alternative to the oxygen evolution reaction (OER) in clean energy conversion and storage systems. Nickel‐based catalysts are highly regarded as promising electrocatalysts for the UOR. However, their effectiveness is significantly hindered by the unavoidable self‐oxidation reaction of nickel species during UOR. To address this challenge, we proposed an interface chemistry modulation strategy to boost UOR kinetics by creating a high‐energy interfacial heterostructure. This heterostructure features the incorporation of Ag at the CoOOH@NiOOH heterojunction interface. Strong interactions significantly promote the electron exchanges in the heterointerface between the ‐OH and ‐O. Consequently, the improved electron delocalization led to the formation of stronger bonds between Co sites and urea CO(NH2)2, promoting a preference for urea to occupy Co active sites over OH*. The resulting catalyst, Ag‐CoOOH@NiOOH, affords an ultrahigh UOR activity with a low potential of 1.33 V at 100 mA cm‐2. The fabricated catalyst exhibits a mass activity exceeding that of initial cobalt oxyhydroxide by over 11.9 times. The rechargeable urea‐assisted zinc‐air batteries (ZABs) achieves a record‐breaking energy efficiency of 74.56% at 1 mA cm‐2, remarkable durability (1000 hours at even a current density of 50 mA cm‐2), and quick charge performances.    

    

* Direct Evidence for Buffer-Enhanced Proton-Coupled Electron Transfer in Metal Aquo Bond Formation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402529806
:TOPICS: Molecular Electronic Devices and Systems, Electrochemical Reduction of CO2 to Fuels, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-l776x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402529806"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402529806"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402529806"))][Get cited by]]

OpenAlex: https://openalex.org/W4402529806 (Open access: False)
    
[[https://openalex.org/A5080823071][Matthew C. Kessinger]], [[https://openalex.org/A5005799122][Thomas Whittemore]], [[https://openalex.org/A5033549112][Silvia Grandi]], [[https://openalex.org/A5064486136][Evgeny O. Danilov]], [[https://openalex.org/A5004379175][Stefano Caramori]], [[https://openalex.org/A5017888744][Felix N. Castellano]], [[https://openalex.org/A5073119387][Gerald J. Meyer]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-l776x 
     
Proton-coupled electron transfer (PCET) reactions play a crucial role in the interconversion of metal-aqua and metal-hydroxo species present in transition metal complexes and oxide surfaces (M(III)-OH + e− + H+ M(II)-OH2). For ruthenium-based water oxidation catalysts, PCET reactions involved in the mechanism of oxygen evolution have demonstrated a strong dependence on the identity and concentration of the proton donor and acceptor with significant rate enhancements observed for electrocatalysis performed in acetate, phosphate, and borate buffered electrolytes. However, the systematic study of this phenomenon has been hampered by the inability to independently measure discrete rates for electron transfer (ET) and proton transfer (PT) under electrochemical applied potentials. Herein, the PCET kinetics and mechanism of metal aqua bond formation in a ruthenium water oxidation catalyst [Ru(tpy)(bpy′)H2O]2+, Ru(II)−OH2 where tpy is 2,2′:6′,2″-terpyridine and bpy′ is 4,4′-diaminopropylsilatrane-2,2′-bypyridine were investigated at a conductive metal oxide interface as a function of buffer identity and concentration. The reaction of interest was triggered by visible light excitation of the catalyst and the kinetics of the independent ET and PT steps of the PCET mechanism were determined through nanosecond transient absorption spectroscopy. Kinetic measurements performed in aqueous acetate, phosphate, or borate buffer solutions revealed two distinct regimes of PT kinetics solely dependent on the buffer concentration. At the greatest buffer concentrations investigated (2 M acetate) spectral signals corresponding to the discreet ET and PT steps were absent indicative in a change in underlying PCET mechanism. Likewise, kinetic modeling indicated that PT from protonated acetate or phosphate occurred with rate constants that were 2-4 orders of magnitude greater than those for bulk water. In all, these results suggest that the presence of buffer-bases can significantly enhance PCET rates and, in this reaction, may alter the underlying mechanism.    

    

* Effects of residual oxygen on superconducting niobium films  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402458592
:TOPICS: High-Temperature Superconductivity, Semiconductor Spintronics and Quantum Computing, Accelerator Technology and Superconducting Cavities
:PUBLICATION_DATE: 2024-09-09
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1063/5.0225589")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402458592"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402458592"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402458592"))][Get cited by]]

OpenAlex: https://openalex.org/W4402458592 (Open access: False)
    
[[https://openalex.org/A5093793869][Miguel Manzo-Perez]], [[https://openalex.org/A5093045265][Moeid Jamalzadeh]], [[https://openalex.org/A5101677893][Zhujun Huang]], [[https://openalex.org/A5034130133][Xiao Tong]], [[https://openalex.org/A5054131257][Kim Kisslinger]], [[https://openalex.org/A5024076860][Dmytro Nykypanchuk]], [[https://openalex.org/A5063826797][Davood Shahrjerdi]], Applied Physics Letters. 125(11)] 2024. https://doi.org/10.1063/5.0225589 
     
The integration of niobium (Nb) into emerging superconducting circuits can enhance their performance and function. However, growth of high purity Nb can be challenging due to its high reactivity with oxygen. Here, we examine the role of residual oxygen inside the growth chamber in transforming the structural, chemical, and superconducting properties of Nb films. We demonstrate that an increase in unintentional oxygen impurities lowers the superconducting critical temperature of Nb. This evolution coincides with the reduction of Nb crystal domains, which are separated by highly disordered oxygen-rich regions. Moreover, chemical analysis reveals the formation of niobium monoxide within the film during growth. These findings provide a comprehensive picture of how residual oxygen in the growth chamber can affect the properties of the Nb films. This study contributes to the materials science and engineering knowledge of superconducting Nb growth.    

    

* Regulation via repression: Regulator of symbiosome differentiation (RSD) acts as zone-specific repressor to mediate nodule development  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402490914
:TOPICS: Symbiotic Nitrogen Fixation in Legumes, Plant-Parasitic Nematodes in Molecular Plant Pathology, Genetic Diversity and Improvement of Soybean
:PUBLICATION_DATE: 2024-06-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.52843/cassyni.tzg3n6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402490914"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402490914"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402490914"))][Get cited by]]

OpenAlex: https://openalex.org/W4402490914 (Open access: False)
    
[[https://openalex.org/A5062739274][Akanksha Bhardwaj]], No host. None(None)] 2024. https://doi.org/10.52843/cassyni.tzg3n6 
     
This talk will be pre-recorded, with virtual Q A. Medicago truncatula forms indeterminate nodules having successive development zones. Indeterminate nodules maintain an oxygen gradient to uncouple symbiosome differentiation at invasion zone and nitrogen fixation at fixation zone. The oxygen gradient maxima to minima from apex to base of nodule length depends on *leghemoglobins (LgHbs )* expression which is responsible for oxygen buffering as LgHbs create micro-oxic environment. In this study, we demonstrate the mode of action of Regulator of Symbiosome Differentiation (RSD), a transcriptional repressor. RSD interacts with Nodule Inception (NIN) and NIN-like protein 2 (NLP2). Studies confirm NIN-NLP2 activate *LgHbs* expression. RSD expression and protein localization remains confined within invasion and interzone. We identified this zone-specific expression of RSD is crucial as RSD represses *LgHb* expression at invasion zone. Manipulation of the stoichiometry of RSD, NIN, and NLP2 in planta disrupts *LgHb* expression and impairs functional nodule development. To unravel, the dynamics of the invasion zone-specific regulation, we performed translatome and transcriptome profiling using the RSD promoter, to identify putative targets of RSD. Collectively, our findings suggest that RSD-mediated repression of NIN and NLP2-targets are crucial for symbiosome differentiation. RSD recruitment in the nitrogen-fixing clade also recommends its evolution during nodulation and conserved functionality in other legume species as well. Thus RSD, as a repressor from its invasion zone optimizes the genetic network crucial for functional nodule development.    

    

* Depth-resolved characterization of Meissner screening breakdown in surface treated niobium  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402541511
:TOPICS: Accelerator Technology and Superconducting Cavities, Vacuum Electronic High Power Terahertz Sources, Plasma Physics and Technology in Semiconductor Industry
:PUBLICATION_DATE: 2024-09-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41598-024-71724-5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402541511"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402541511"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402541511"))][Get cited by]]

OpenAlex: https://openalex.org/W4402541511 (Open access: True)
    
[[https://openalex.org/A5033617037][Edward Thoeng]], [[https://openalex.org/A5066212291][Md Asaduzzaman]], [[https://openalex.org/A5024868933][Philipp Kolb]], [[https://openalex.org/A5065665606][Ryan M. L. McFadden]], [[https://openalex.org/A5017930902][G. D. Morris]], [[https://openalex.org/A5054818798][John O. Ticknor]], [[https://openalex.org/A5020731483][S. R. Dunsiger]], [[https://openalex.org/A5065523228][Victoria L. Karner]], [[https://openalex.org/A5082660511][Derek Fujimoto]], [[https://openalex.org/A5047356504][Tobias Junginger]], [[https://openalex.org/A5055420269][R. F. Kiefl]], [[https://openalex.org/A5070714748][W. A. MacFarlane]], [[https://openalex.org/A5002878273][Ruohong Li]], [[https://openalex.org/A5013346237][Suresh Saminathan]], [[https://openalex.org/A5046714003][Robert Laxdal]], Scientific Reports. 14(1)] 2024. https://doi.org/10.1038/s41598-024-71724-5 
     
We report direct measurements of the magnetic field screening at the limits of the Meissner phase for two superconducting niobium (Nb) samples. The samples are processed with two different surface treatments that have been developed for superconducting radio-frequency (SRF) cavity applications-a "baseline" treatment and an oxygen-doping ("O-doping") treatment. The measurements show: (1) that the screening length is significantly longer in the "O-doping" sample compared to the "baseline" sample; (2) that the screening length near the limits of the Meissner phase increases with applied field; (3) the evolution of the screening profile as the material transitions from the Meissner phase to the mixed phase; and (4) a demonstration of the absence of any screening profile for the highest applied field, indicative of the full flux entering the sample. Measurements are performed utilizing the    

    

* Degenerated intraligamentary leiomioma as a simulator of malignant ovarian pathology. Report of a case  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402468802
:TOPICS: Uterine Conditions and Treatments, Clinicopathology of Fibrous Tumors and Treatment Strategies, Genitourinary Soft Tissue Tumors and Anomalies
:PUBLICATION_DATE: 2024-08-31
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.51288/00840316")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402468802"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402468802"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402468802"))][Get cited by]]

OpenAlex: https://openalex.org/W4402468802 (Open access: False)
    
[[https://openalex.org/A5022928114][Ernesto Lara]], [[https://openalex.org/A5107156028][Dariela Perdomo]], [[https://openalex.org/A5065785833][Héctor Puente González]], Revista de Obstetricia y Ginecología de Venezuela. 84(03)] 2024. https://doi.org/10.51288/00840316 
     
Leiomyomas are benign mesenchymal tumors that occur as the most common uterine neoplasm in women of reproductive age. Depending on its growth, its blood supply may be compromised, causing degenerative changes due to lack of oxygen, which gives it an atypical appearance that may cause confusion with the diagnosis. The case of a 47-year-old patient is described, who consults for a progressive increase in the volume of abdominal circumference of 7 months of evolution, referred to the gynecology oncology consultation due to a large retrouterine tumor mass of probable ovarian origin with a high risk of malignancy. After performing preoperative studies, she was taken to the operating room, obtaining as a definitive diagnosis, leiomyoma with hyaline and focal hydropic degeneration. Leiomyomas with degenerative changes can simulate malignant ovarian tumors, which is why they should be considered as a differential diagnosis before surgical interventions for large abdominopelvic tumors. Keywords: Leiomyoma, Hyaline Degeneration, Hydropic Degeneration, Simulator.    

    

* Surface chemistry and catalytic activity in H2O2 decomposition of pyrolytically fluoralkylated activated carbons  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402482731
:TOPICS: Catalytic Nanomaterials, Graphene: Properties, Synthesis, and Applications, Carbon Nanotubes and their Applications
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ra04883k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402482731"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402482731"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402482731"))][Get cited by]]

OpenAlex: https://openalex.org/W4402482731 (Open access: True)
    
[[https://openalex.org/A5060146992][Gauhar Mussabek]], [[https://openalex.org/A5006141648][Saule Baktygerey]], [[https://openalex.org/A5014352321][Yerzhan Taurbayev]], [[https://openalex.org/A5091624652][Dana Yermukhamed]], [[https://openalex.org/A5074940998][Nazym Zhylkybayeva]], [[https://openalex.org/A5024138518][Alexander N. Zaderko]], [[https://openalex.org/A5041312664][Vitaliy E. Diyuk]], [[https://openalex.org/A5052330345][Sergii Afonin]], [[https://openalex.org/A5049063772][Gulmira Yar-Mukhamedova]], [[https://openalex.org/A5062911686][Ruslan Mariychuk]], [[https://openalex.org/A5028923815][Liudmyla M. Grishchenko]], [[https://openalex.org/A5011701942][Mária Kaňuchová]], [[https://openalex.org/A5084774371][Vladyslav V. Lisnyak]], RSC Advances. 14(40)] 2024. https://doi.org/10.1039/d4ra04883k 
     
According to the proposed pyrolytic method, granular activated carbon (AC) Norit 830 W was functionalized by thermal treatment of AC in hydrofluorocarbon (HFC) gases, pentafluoroethane and 1,1,1,2-tetrafluoroethane, at 400-800 °C. This method does not require activation by plasma and photons. Chemical and elemental analysis showed that the pyrolytic treatment provides a loading of 2.95 mmol (5.6 wt%) of fluorine per gram of AC. Nitrogen adsorption measurements indicated that the microporous structure contracted when AC was treated with HFC at temperatures above 400 °C. Thermogravimetry, Fourier transform infrared spectroscopy (FTIR) with attenuated total reflectance (ATR), and X-ray photoelectron spectroscopy (XPS) demonstrated the evolution of oxygen-containing and fluorine-containing groups to more thermostable groups with treatment temperature. The fluorine-containing groups grafted at high temperature, above 600 °C exhibited the highest thermal stability up to 1250 °C in dry argon. From the data of XPS and solid-state    

    

* Treatment of domestic wastewater and extracellular polymeric substance accumulation in siphon‐type composite vertical subsurface flow constructed wetland  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402570326
:TOPICS: Application of Constructed Wetlands for Wastewater Treatment, Microbial Nitrogen Cycling in Wastewater Treatment Systems, Advancements in Water Purification Technologies
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/wer.11132")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402570326"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402570326"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402570326"))][Get cited by]]

OpenAlex: https://openalex.org/W4402570326 (Open access: False)
    
[[https://openalex.org/A5100353673][Hao Chen]], [[https://openalex.org/A5085485915][Lin Qiu]], [[https://openalex.org/A5046179350][Hong Wu]], [[https://openalex.org/A5102542811][Fahui Nie]], [[https://openalex.org/A5101455992][Yong Liu]], [[https://openalex.org/A5103208347][Wenping Cao]], Water Environment Research. 96(9)] 2024. https://doi.org/10.1002/wer.11132 
     
Abstract In this study, the siphon‐type composite vertical flow constructed wetland (Sc‐VSsFCW) was constructed with anthracite and shale ceramsite chosen as the substrate bed materials. During the 90‐day experiment, typical pollutant removal effects of wastewater and extracellular polymeric substance (EPS) accumulation were investigated. Meanwhile, X‐ray diffraction and scanning electron microscopy were used to examine the phase composition and surface morphology to analyze adsorptive property. Additionally, we evaluated the impact of siphon effluent on clogging and depolymerization by measuring the EPS components' evolution within the system. The findings reveal that both the anthracite and shale ceramsite systems exhibit impressive removal efficiencies for total phosphorus (TP), total dissolved phosphorus (TDP), soluble reactive phosphorus (SRP), chemical oxygen demand (COD), ammonium nitrogen (NH 4 + ‐N), and nitrate nitrogen (NO 3 − ‐N). However, as the experiment progressed, TP removal rates in both systems gradually declined because of the saturation of adsorption sites on the substrate surfaces. Although the dissolved oxygen (DO) levels remained relatively stable throughout the experiment, pH exhibited distinct patterns, suggesting that the anthracite system relies primarily on chemical adsorption, whereas the shale ceramsite system predominantly utilizes physical adsorption. After an initial period of fluctuation, the permeability coefficient and porosity of the system gradually stabilized, and the protein and polysaccharide contents in both systems exhibited a downward trend. The study underscores that anthracite and shale ceramsite have good effectiveness in pollutant removal as substrate materials. Overall, the hydraulic conditions of the double repeated oxygen coupling siphon in the Sc‐VSsFCW system contribute to enhanced re‐oxygenation capacity and permeability coefficient during operation. The changes in EPS content indicate that the siphon effluent exerts a certain depolymerization effect on the EPS within the system, thereby mitigating the risk of biological clogging to a certain extent. Practitioner Points The system can still maintain good pollutant treatment effect in long‐term operation. The re‐oxygenation method of the system can achieve efficient and long‐term re‐oxygenation effect. The siphon effluent has a certain improvement effect on the permeability coefficient and porosity, but it cannot effectively inhibit the occurrence of clogging. The EPS content did not change significantly during the operation of the system, and there was a risk of biological clogging.    

    

* Ferric Iron Evolution During Crystallization of the Earth and Mars  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402525918
:TOPICS: Magnetosome Formation in Prokaryotes, Exploration and Study of Mars, Machine Learning for Mineral Prospectivity Mapping
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1029/2023je008262")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402525918"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402525918"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402525918"))][Get cited by]]

OpenAlex: https://openalex.org/W4402525918 (Open access: False)
    
[[https://openalex.org/A5052639092][Laura Schaefer]], [[https://openalex.org/A5024217562][Kaveh Pahlevan]], [[https://openalex.org/A5033726538][L. T. Elkins‐Tanton]], Journal of Geophysical Research Planets. 129(9)] 2024. https://doi.org/10.1029/2023je008262 
     
Abstract Magma ocean crystallization models that track f O 2 evolution can reproduce the D/H ratios of both the Earth and Mars without the need for exogenous processes. Fractional crystallization leads to compositional evolution of the bulk oxide components. Recent work suggests that metal‐saturated magma oceans may contain near‐present‐day Fe 3+ concentrations. We model the fractional crystallization of Earth and Mars, including Fe 2+ and Fe 3+ as separate components. We calculate Fe 3+ partition coefficients for lower mantle minerals and compare the results of fractional crystallization for both Earth and Mars. We calculate oxygen fugacity ( f O 2 ) at the surface as the systems evolve and compare them to constraints on the f O 2 of the last magma ocean atmosphere from D/H ratios, both with and without metal saturation. For Earth, we find that Fe 3+ likely behaves incompatibly in the lower mantle in order to match the D/H constraint for whole mantle models, but shallow magma ocean models also provide reasonable matches. Disproportionation in whole mantle magma oceans likely overpredicts the amount of Fe 3+ and metal that form or require subsequent reduction to return to present‐day values. For Mars, we cannot match the D/H constraints on last f O 2 unless the magma ocean begins with <50% of the predicted Fe 3+ , but better match the present day mantle redox. We show that Fe 3+ partitioning has a measurable effect on magma ocean redox, and that it evolves throughout the magma ocean's lifetime. We highlight the need for additional experimental constraints on ferric iron mineral/melt partitioning and more thermodynamic data for the Fe‐disproportionation reaction.    

    

* The Star–Planet Composition Connection  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402503252
:TOPICS: Formation and Evolution of the Solar System, Stellar Astrophysics and Exoplanet Studies, Star Formation in Molecular Clouds and Protoplanetary Disks
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1146/annurev-astro-071221-053007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402503252"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402503252"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402503252"))][Get cited by]]

OpenAlex: https://openalex.org/W4402503252 (Open access: False)
    
[[https://openalex.org/A5047489063][Johanna Teske]], Annual Review of Astronomy and Astrophysics. 62(1)] 2024. https://doi.org/10.1146/annurev-astro-071221-053007 
     
The mantra “know thy star, know thy planet” has proven to be very important for many aspects of exoplanet science. Here I review how stellar abundances inform our understanding of planet composition and, thus, formation and evolution. In particular, I discuss how: ▪ The strongest star–planet connection is still the giant planet–metallicity correlation, the strength of which may indicate a break point between the formation of planets versus brown dwarfs. ▪ We do not have very good constraints on the lower metallicity limit for planet formation, although new statistics from TESS are helping, and it appears that, at low [Fe/H], α elements can substitute for iron as seeds for planet formation. ▪ The depletion of refractory versus volatile elements in stellar photospheres (particularly the Sun) was initially suggested as a sign of small planet formation but is challenging to interpret, and small differences in binary star compositions can be attributed mostly to processes other than planet formation. ▪ We can and should go beyond comparisons of the carbon-to-oxygen ratio in giant planets and their host stars, incorporating other volatile and refractory species to better constrain planet formation pathways. ▪ There appears to be a positive correlation between small planet bulk density and host star metallicity, but exactly how closely small planet refractory compositions match those of their host stars—and their true diversity—is still uncertain.    

    

* IL-1β primed mesenchymal stromal cells moderate hemorrhagic shock-induced vascular permeability  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402463365
:TOPICS: Fluid Resuscitation in Trauma and Critical Care
:PUBLICATION_DATE: 2024-09-11
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-4866976/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402463365"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402463365"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402463365"))][Get cited by]]

OpenAlex: https://openalex.org/W4402463365 (Open access: False)
    
[[https://openalex.org/A5040000226][Nathalie Baudry]], [[https://openalex.org/A5046432516][Aurélie Campeanu]], [[https://openalex.org/A5045950683][Claude Aussel]], [[https://openalex.org/A5107136429][Caroline Doutrelon]], [[https://openalex.org/A5069433296][Marion Grosbot]], [[https://openalex.org/A5064116117][Sébastien Banzet]], [[https://openalex.org/A5088096181][Éric Vicaut]], [[https://openalex.org/A5034579991][Juliette Peltzer]], No host. None(None)] 2024. https://doi.org/10.21203/rs.3.rs-4866976/v1 
     
Abstract Background: Hemorrhagic shock (HS) corresponds to absolute hypovolemia creating an imbalance between oxygen supply and consumption. This causes an impaired hemostasis, a systemic inflammatory response, and microvascular permeability which can lead to multiple organ failure (MOF). There is no specific treatment for the endothelial dysfunction that plays a major role in the evolution towards MOF. Mesenchymal Stromal Cells (MSC) have been used in clinical trials for their immunomodulation and tissue repair capabilities for many years. Moreover, we previously showed that IL-1β-primed-MSC (MSCp) attenuated HS-induced organ injuries. The objective was to determine whether MSCp could prevent the onset of MOF after HS by preventing endothelial dysfunction. Methods: We developed a rat model: 90min of HS at a fixed Mean Arterial Pressure of 35mmHg, followed by resuscitation and transfusion. MSCp treatment was administered intravenously at the beginning of the resuscitation. After 6h, plasmatic endothelial markers, vascular permeability (Evans Blue (EB) administration) and renal and hepatic water contents (difference between wet and dry weight), were evaluated. We also evaluated the ability of MSCp to limit the adhesion of leukocytes to an activated endothelium in vitro. Results: Our results indicate that early administration of MSCp could reduce hepatic vascular leakage associated with a trend to decrease of Syndecan-1, ICAM-1, vWF and VCAM-1. In vitro, these cells are able to decrease leukocyte-endothelial cell bonding. Therefore, we suggest that MSCp are able to prevent endothelial dysfonction that contributes to liver injury.    

    

* Modeling and 3-D simulation of petroleum coke calcination process: investigation of the effect of main operating variables  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402507204
:TOPICS: Biomass Pyrolysis and Conversion Technologies, Zeolite Chemistry and Catalysis, Carbon Dioxide Capture and Storage Technologies
:PUBLICATION_DATE: 2024-09-13
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1515/ijcre-2024-0016")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402507204"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402507204"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402507204"))][Get cited by]]

OpenAlex: https://openalex.org/W4402507204 (Open access: False)
    
[[https://openalex.org/A5053498370][Mohammad Hosein Eghbal Ahmadi]], [[https://openalex.org/A5034222903][Shokoufe Tayyebi]], [[https://openalex.org/A5000473622][Amir Mosayebi]], International Journal of Chemical Reactor Engineering. None(None)] 2024. https://doi.org/10.1515/ijcre-2024-0016 
     
Abstract Coke calcination is a process that involves heating green petroleum coke to purify it and eliminate volatile materials for subsequent processing. Due to the complexity of the rotary kiln used in this process, conducting experimental studies can be challenging and restricted. However, quantitative analyses based on developed models can provide a foundation for optimizing and controlling the process, which can significantly enhance the design efficiency. A three-dimensional simulation model of a rotary calcining kiln for petroleum coke was created using COMSOL Multiphysics in a steady-state mode. This model accounted for all relevant physical and chemical phenomena in the gas stream and coke bed flow, including heat transfer, combustion, and the evolution of volatile matter and coke dust. The mathematical modeling yielded distributions of temperature and mass fractions within the kiln, as well as the velocity field. The results revealed two distinct peak temperatures in the gas phase: 1,780 K near the primary air injection point and 1,605 K near the tertiary air injection points. The findings were analyzed, and the impact of key variables was explored. The simulation data indicated that for every decrease of 10–15 m/s in air flow, the gas peak temperature dropped by approximately 100°. Additionally, an increase in the input oxygen concentration led to enhanced combustion, resulting in higher peak concentrations of CO 2 . The developed simulation model has proven to be a valuable and promising tool for the design and optimization of petroleum coke rotary kilns.    

    

* Macroalgae from the early Cambrian Chengjiang biota  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402484130
:TOPICS: Paleoredox and Paleoproductivity Proxies, Ecological Dynamics of Marine Environments, Climate Change and Paleoclimatology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/spp2.1585")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402484130"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402484130"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402484130"))][Get cited by]]

OpenAlex: https://openalex.org/W4402484130 (Open access: False)
    
[[https://openalex.org/A5035973562][Gaorong Li]], [[https://openalex.org/A5103071324][Fan Wei]], [[https://openalex.org/A5071309017][Jason Guo]], [[https://openalex.org/A5013500705][Peiyun Cong]], Papers in Palaeontology. 10(5)] 2024. https://doi.org/10.1002/spp2.1585 
     
Abstract The Chengjiang biota, a Burgess Shale‐type Lagerstätte in eastern Yunnan, South China (Cambrian Series 2, Stage 3), provides valuable information regarding the origin and early evolution of metazoans, and complex marine ecosystems. Although the major animal phyla in the Chengjiang biota have been extensively studied, macroalgae have received comparatively little attention. Here, we establish new taxa Yunnanospirellus typica and Y . elegans , describe five genera and six species ( Tawuia sp., Morania fragmenta , Liulingjitaenia alloplecta , Longfengshania stipitata , Lo . spheria and Paralongfengshania sicyoides ) not previously reported in the Chengjiang biota, and elucidate the pith structure of Enteromophites intestinalis . With 13 genera and 17 species now recorded, macroalgae rank fourth in species‐level biodiversity in the Chengjiang biota (behind Euarthropoda, Porifera and Priapulida). Macroalgae account for 71.57% of total abundance, far more than all other animal phyla in the Chengjiang biota. Fuxianospira is the most dominant genus, accounting for 52.01% of all macroalgae specimens. Unattached (floating, planktonic or drifting) forms dominate (eight attached; nine unattached species). The high diversity of attached macroalgae indicates that the macroalgal communities adapted to the Proterozoic firm substrate (probably covered by microbial mats) persisted from the Ediacaran to the early Cambrian, providing compelling evidence for the existence of firm substrate during this time. Meanwhile, the blooming of unattached macroalgae in the Chengjiang biota suggests that other niches were also rich in macroalgae. Unattached macroalgae might have provided oxygen and energy to metazoans, eventually leading to ecological expansion in the upper and middle water column of the early Cambrian seas.    

    

* Enhancing Built‐In Electric Field via Defect‐Mediated Interfacial Chemical Bond Construction in Chalcogenide Heterojunction for Alcohol Photooxidation Coupled with H2 Production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402541839
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology, Applications of Quantum Dots in Nanotechnology
:PUBLICATION_DATE: 2024-09-14
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202411991")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402541839"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402541839"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402541839"))][Get cited by]]

OpenAlex: https://openalex.org/W4402541839 (Open access: False)
    
[[https://openalex.org/A5103937843][Yi‐Wen Han]], [[https://openalex.org/A5016978102][Ying‐Hao Chu]], [[https://openalex.org/A5031783119][Lei Ye]], [[https://openalex.org/A5049677180][Tian‐Jun Gong]], [[https://openalex.org/A5049639221][Xuebin Lü]], [[https://openalex.org/A5100719200][Yao Fu]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202411991 
     
Abstract Rationally designing nanostructures based on an adequate understanding of structure‐performance relationships is key for directional charge transfer regulation in heterojunction photocatalysts. A general strategy is developed for synthesizing bifunctional Sv‐chalcogenide/Ti 3 C 2 Schottky junctions (Sv = sulfur vacancies, chalcogenides containing CdS, CdIn 2 S 4 , ZnIn 2 S 4 , ZnS, CuInS 2 ) featuring a giant built‐in electric field (BIEF) via defect‐mediated heterocomponent anchorage, which consists of sulfur vacancy modulation of chalcogenides and Ti 3 C 2 nanoparticle anchoring at defects via interfacial Metal─Oxygen (M─O) bonds. These heterojunctions have the distinctive interface structure of semicoherent phase boundaries and a directionally aligned BIEF pointing from chalcogenides to Ti 3 C 2 . The enhanced BIEF creates an asymmetrical charge distribution, which not only governs the charge migration behavior by enabling charge carrier localization and delocalized electron transport continuity but also regulates the molecular catalytic behavior by optimizing pivotal intermediate adsorption/activation ( * Ar‐CH(R 2 )‐OH in dehydrogenation and H * in H 2 evolution) in selective alcohol photooxidation coupled with H 2 generation. Encouragingly, Sv‐chalcogenide/Ti 3 C 2 exhibits unprecedented performance (up to 13.34‐fold higher efficiency than unmodulated chalcogenides) and good substrate compatibility for various alcohols. This work demonstrates the synergistic effects of surface electron density control and interfacial interaction modulation in regulating BIEFs, elucidating the substantial impact of reinforced BIEF on carrier transport properties and molecular catalytic behavior.    

    

* The oxygen paradox in alkaline zinc-air battery via the competition of an unidentified anodic chemical reduction with cathodic kinetics  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4402498178
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-09-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-2rxlx")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4402498178"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4402498178"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4402498178"))][Get cited by]]

OpenAlex: https://openalex.org/W4402498178 (Open access: False)
    
[[https://openalex.org/A5107165478][Subhra R. Pattanayak]], [[https://openalex.org/A5057514270][Pallavi Thakur]], [[https://openalex.org/A5018703123][Ravi K. Biroju]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-2rxlx 
     
Can the fuel in use adversely affect the performance of an energy storage system? Here, oxygen (O2) in zinc-air (O2) battery (ZAB) is shown to impact the anodic process adversely, leading to early cell failure, though its amount limiting can affect the cathodic reaction kinetics. An unexplored chemical reduction process of dissolved O2 on metallic zinc in alkaline medium leading to peroxide radical (O2˙¯) species generation is proven, by electron paramagnetic resonance spectroscopy (EPR) and hydrodynamic voltammetry studies, followed by the formation of ZnO passivation layer on the Zn surface causing cell death. Keeping similar discharge times, early ZnO passivation occurred on the ZAB with its anode kept in an O2 rich environment than in the other one of O2 free environment. A slight modification in the cell design ensuring the limited availability of O2 at anode provided ~5 times extended cyclability (~7 hours to ~35 hours) than the ZAB with no such control leading to enhanced specific capacity. Presence of O2 in the anodic compartment leads to early cell failure from passivating ZnO formation impeding charge transfer. Limiting the O2 transfer from the cathodic side to anodic compartment can extend the cell cyclability and enhance discharge capacity. As alkaline ZABs are proposed for applications ranging from portable hearing aids to mini-grids, with self-discharge from the hydrogen evolution reaction (HER) on metallic Zn as a major roadblock, this study unravels predominant parasitic chemical process by O2 on the Zn surface, highlighting the importance of cathodic O2 crossover inhibition in the alkaline ZAB.    

    
