#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Sun Feb  4 23:59:47 2024

Found 42 results from 2024-01-27 to 2024-02-04
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Novel cobalt nanorods@ cobalt-platinum nanoparticles for electrocatalytic hydrogen evolution reactions and oxygen evolution reactions study  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391247068
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.171")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391247068"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391247068"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391247068"))][Get cited by]]

OpenAlex: https://openalex.org/W4391247068 (Open access: False)
    
[[https://openalex.org/A5037709424][Tong Zhang]], [[https://openalex.org/A5067607038][Yuemin Zhao]], [[https://openalex.org/A5069909200][Fangxun Liu]], [[https://openalex.org/A5035856815][Ming Zheng]], [[https://openalex.org/A5032467563][Kun Shi]], [[https://openalex.org/A5009997945][Jinpeng Liu]], [[https://openalex.org/A5004245595][Yuena Sun]], [[https://openalex.org/A5085530250][Yufan Zhang]], [[https://openalex.org/A5086928534][Huan Wang]], International Journal of Hydrogen Energy. 58(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.01.171 
     
In this work, we prepared a novel material of cobalt nanorods@ cobalt-platinum nanoparticles using a facile, green method. We used a hydrothermal method to first synthesize a cobalt nanorod, which was used as a substrate material on which a ZIF-67 MOF structure was controllably loaded, and then, platinum was loaded into the MOF using a redox substitution reaction, resulting in the formation of a new type of nanocomposites, cobalt nanorods@ cobalt-platinum nanoparticles. The composites were successfully doped with a small amount of precious metal platinum into cobalt nanorods @ cobalt MOF by replacement method, which combines the unique structure of cobalt nanorods, cobalt MOF and high electrocatalytic performance of platinum, realizes the organic combination of precious metal-transition metal and effectively improves the electrocatalytic performance of the composites. The novel composites Co NRs@Co10–Pt1 NPs exhibit high catalytic activity and stability for the hydrogen and oxygen evolution reactions, Tafel slopes is 25 mV dec−1 in HER and 56 mV dec−1 in OER. This work provides a new idea for the preparation step of novel transition metal-precious metal composites and contributes to the effective improvement of the material's performance in electrocatalytic water decomposition reaction.    

    

* Decision letter for "FeNi decorated nitrogen-doped hollow carbon spheres as ultra-stable bifunctional oxygen electrocatalyst for rechargeable zinc–air battery with 2.7% decay after 300 hours cycling"  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391250016
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Conducting Polymer Research
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ra08572d/v2/decision1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391250016"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391250016"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391250016"))][Get cited by]]

OpenAlex: https://openalex.org/W4391250016 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d3ra08572d/v2/decision1 
     
No abstract    

    

* Review for "FeNi decorated nitrogen-doped hollow carbon spheres as ultra-stable bifunctional oxygen electrocatalyst for rechargeable zinc–air battery with 2.7% decay after 300 hours cycling"  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391250229
:TOPICS: Electrocatalysis for Energy Conversion, Conducting Polymer Research, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ra08572d/v2/review1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391250229"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391250229"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391250229"))][Get cited by]]

OpenAlex: https://openalex.org/W4391250229 (Open access: False)
    
, No host. None(None)] 2024. https://doi.org/10.1039/d3ra08572d/v2/review1 
     
No abstract    

    

* Author response for "FeNi decorated nitrogen-doped hollow carbon spheres as ultra-stable bifunctional oxygen electrocatalyst for rechargeable zinc–air battery with 2.7% decay after 300 hours cycling"  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391250410
:TOPICS: Electrocatalysis for Energy Conversion, Conducting Polymer Research, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ra08572d/v2/response1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391250410"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391250410"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391250410"))][Get cited by]]

OpenAlex: https://openalex.org/W4391250410 (Open access: False)
    
[[https://openalex.org/A5085208475][Lun Shi-yi]], [[https://openalex.org/A5038231583][Hanbin Wang]], [[https://openalex.org/A5090064986][Yijing Deng]], [[https://openalex.org/A5068319391][Jinting Cui]], [[https://openalex.org/A5036443199][Pei Liang]], [[https://openalex.org/A5060390157][Kaiwen Wang]], [[https://openalex.org/A5051452798][Lin Li]], [[https://openalex.org/A5007052387][Houzhao Wan]], [[https://openalex.org/A5072043925][Hao Wang]], No host. None(None)] 2024. https://doi.org/10.1039/d3ra08572d/v2/response1 
     
No abstract    

    

* Synergistic CuCoS-PANI Materials for Binder-Free Electrodes in Asymmetric Supercapacitors and Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391260063
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Catalytic Reduction of Nitro Compounds
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3na01066j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391260063"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391260063"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391260063"))][Get cited by]]

OpenAlex: https://openalex.org/W4391260063 (Open access: True)
    
[[https://openalex.org/A5024005569][Hiba A. Hasan]], [[https://openalex.org/A5067573568][Amir Muhammad Afzal]], [[https://openalex.org/A5084761641][Hussein Alrobei]], [[https://openalex.org/A5093796837][Fareeha Riasat]], [[https://openalex.org/A5034087002][Amir Muhammad Afzal]], [[https://openalex.org/A5057428775][Ali Saeedi]], [[https://openalex.org/A5093796838][Hasan B. Albargib]], [[https://openalex.org/A5003070785][A. Rehmat]], No host. None(None)] 2024. https://doi.org/10.1039/d3na01066j  ([[https://pubs.rsc.org/en/content/articlepdf/2024/na/d3na01066j][pdf]])
     
In advanced electronics, supercapacitors (SCs) have received a lot of attention. Nevertheless, it has been shown that different electrode designs that are based on metal sulfides are prone to oxidation,...    

    

* Non-noble metal-based electro-catalyst for the oxygen evolution reaction (OER): Towards an active & stable electro-catalyst for PEM water electrolysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391270883
:TOPICS: Electrocatalysis for Energy Conversion, Hydrogen Energy Systems and Technologies, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.222")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391270883"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391270883"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391270883"))][Get cited by]]

OpenAlex: https://openalex.org/W4391270883 (Open access: False)
    
[[https://openalex.org/A5093799731][B. Tamilarasi]], [[https://openalex.org/A5093799732][K.P. Jithul]], [[https://openalex.org/A5090330319][Jay Pandey]], International Journal of Hydrogen Energy. 58(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.01.222 
     
Among water electrolysis methods, proton exchange membrane electrolyzers (PEMWEs) stand out for their potential to generate high-purity hydrogen with remarkable efficiency and dynamic response, making them a cornerstone technology for the sustainable hydrogen economy. However, a key bottleneck lies in the slow reaction rate of the oxygen evolution reaction (OER) at the anode, a four-electron transfer process that significantly throttles the system's full potential. This significantly impacts overall efficiency and calls for unfolding stable, durable, and highly active electrocatalysts that are cost-effective. However, the inherent acidity generated by the OER itself complicates this task. Noble metal catalysts like iridium (Ir) and ruthenium (Rh), pure or combined with other elements, exhibit excellent activity in the acidic OER environment. However, their high cost hinders large-scale PEMWE deployment. Therefore, extensive research has concentrated on non-noble metal alternatives, particularly transition metal oxides (monometallic and polymetallic) and carbon-based materials. This comprehensive review meticulously examines the emerging progress in non-noble metal electrocatalysts designed for low-pH OER conditions within PEMWEs. Following an introductory classification of water electrolyzer technologies, it explores how factors such as structure and synthesis route modulate the crucial performance parameters across diverse catalyst groups. Drawing upon these insights, the review also evaluates the current challenges and outlines promising avenues for future research.    

    

* Multi metallic Electro-Catalyst Design for Enhanced Oxygen Evolution Reaction: Immobilizing MnFe Nanoparticles on ZIF-67-decorated Graphene Oxide  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391277748
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.143884")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391277748"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391277748"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391277748"))][Get cited by]]

OpenAlex: https://openalex.org/W4391277748 (Open access: False)
    
[[https://openalex.org/A5069793621][Zhwan Naghshbandi]], [[https://openalex.org/A5040505150][Kayvan Moradi]], [[https://openalex.org/A5000899157][Azam Salimi]], [[https://openalex.org/A5059846753][Mohammad Gholinejad]], [[https://openalex.org/A5082026516][Ali Feizabadi]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.143884 
     
The advancement of large-scale hydrogen production and its application via electrocatalytic water splitting heavily relies on progress in developing highly active inexpensive, and efficient electrocatalysts for oxygen evolution reactions (OER), which continues to pose a significant challenge. Herein, we prepare GO@ZIF-67@MnFe with embedded iron (Fe) and manganese (Mn) nanoparticles on graphene oxide (GO) decorated with a zeolitic imidazolate framework (ZIF-67) using a facile and cost-effective method. The as-prepared GO@ZIF-67@MnFe catalyst exhibits remarkable electrocatalytic activity with a low overpotential of only 236 mV at the current density of 10 mA cm–2, a small Tafel slope of 55.7 mV dec–1, and robust durability in 1.0 M KOH electrolyte. Additionally, we conduct a systematic study to investigate the electrocatalytic OER activity of ZIF-67, ZIF-67@Mn, ZIF-67@Fe, and ZIF-67@MnFe using density functional theory (DFT) calculations. The experimental and DFT calculation results suggest that the introduction of Fe and Mn to ZIF-67 improves OER performance by reducing the activation energy barrier and accelerating kinetics. This study presents a promising strategy and rational design methodology for the developing multi-metallic catalysts utilizing ZIF derivatives for water splitting.    

    

* Ligand-Confinement-Induced Catalyst–Support Interface Interactions in Co3O4-Supported RuO2 for Long-Term Stable Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391282624
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acssuschemeng.3c06895")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391282624"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391282624"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391282624"))][Get cited by]]

OpenAlex: https://openalex.org/W4391282624 (Open access: False)
    
[[https://openalex.org/A5020310913][Ruo‐Yao Fan]], [[https://openalex.org/A5066058965][Haijun Liu]], [[https://openalex.org/A5059673434][Jun Ren]], [[https://openalex.org/A5027736477][Yichuan Li]], [[https://openalex.org/A5081304185][Jun Nan]], [[https://openalex.org/A5075675634][Yulu Zhou]], [[https://openalex.org/A5003822620][Chunying Liu]], [[https://openalex.org/A5062331341][Yong‐Ming Chai]], [[https://openalex.org/A5072072030][Bin Dong]], No host. None(None)] 2024. https://doi.org/10.1021/acssuschemeng.3c06895 
     
The proton exchange membrane (PEM) water hydrolyzer is crucial to promoting the sustainable development of hydrogen energy and facilitating large-scale energy transformation. However, achieving sustained and stable oxygen evolution reaction (OER) in acidic solutions presents a significant challenge for noniridium based electrocatalysts. Herein, we develop a Co3O4-supported RuO2 electrocatalyst with optimized catalyst–support interface interactions for breaking the activity–stability trade-off relationship in acidic OER. Through detailed electrochemical experiments and characterization analysis, we demonstrate that the crystal growth of Co3O4 support can be precisely regulated by modifying the ligand layer-confined domain of cobalt-based metal–organic frameworks (Co-MOF) precursor, thereby optimizing the RuO2/Co3O4 interface. Due to the weakened self-sacrifice effect of Co3O4, active heterogeneous interface electron interaction and impeccable support crystal coating effect, the acidic OER stability of RuO2/Co3O4–B3DC is significantly improved compared with RuO2 while preserving intrinsic activity. Theoretical modeling suggests that the formation of a RuO2/Co3O4 catalyst–support interface optimizes the adsorption energy of oxygen intermediates, promoting the oxygen evolution process. Additionally, the RuO2/Co3O4–B3DC anode demonstrates promising potential application in PEM electrolyzers and a variety of renewable energy-driven electrolytic cells.    

    

* Layered Quasi-Nevskite Metastable-Phase Cobalt Oxide Accelerates Alkaline Oxygen Evolution Reaction Kinetics  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391300453
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.3c11199")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391300453"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391300453"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391300453"))][Get cited by]]

OpenAlex: https://openalex.org/W4391300453 (Open access: False)
    
[[https://openalex.org/A5061980234][Zhenglong Fan]], [[https://openalex.org/A5082781988][Qingzhu Sun]], [[https://openalex.org/A5055582929][Hao Yang]], [[https://openalex.org/A5021658618][Wenxiang Zhu]], [[https://openalex.org/A5043301652][Fan Liao]], [[https://openalex.org/A5065985607][Qi Shao]], [[https://openalex.org/A5033375147][Tianyang Zhang]], [[https://openalex.org/A5071907213][Zhenhui Kang]], [[https://openalex.org/A5027704532][Tao Cheng]], [[https://openalex.org/A5061196165][Yang Liu]], [[https://openalex.org/A5057299366][Mingwang Shao]], [[https://openalex.org/A5069700804][Minhua Shao]], [[https://openalex.org/A5071907213][Zhenhui Kang]], ACS Nano. None(None)] 2024. https://doi.org/10.1021/acsnano.3c11199 
     
Clarifying the structure–reactivity relationship of non-noble-metal electrocatalysts is one of the decisive factors for the practical application of water electrolysis. In this field, the anodic oxygen evolution reaction (OER) with a sluggish kinetic process has become a huge challenge for large-scale production of high-purity hydrogen. Here we synthesize a layered quasi-nevskite metastable-phase cobalt oxide (LQNMP-Co2O3) nanosheet via a simple molten alkali synthesis strategy. The unit-cell parameters of LQNMP-Co2O3 are determined to be a = b = 2.81 Å and c = 6.89 Å with a space group of P3̅m1 (No. 164). The electrochemical results show that the LQNMP-Co2O3 electrocatalyst enables delivering an ultralow overpotential of 266 mV at a current density of 10 mA cmgeo–2 with excellent durability. The operando XANES and EXAFS analyses clearly reveal the origin of the OER activity and the electrochemical stability of the LQNMP-Co2O3 electrocatalyst. Density functional theory (DFT) simulations show that the energy barrier of the rate-determining step (RDS) (from *O to *OOH) is significantly reduced on the LQNMP-Co2O3 electrocatalyst by comparing with simulated monolayered CoO2 (M-CoO2).    

    

* Novel two-dimensional boron-centered graphdiyne analogue as multifunctional electrocatalyst for hydrogen evolution, oxygen evolution, and oxygen reduction reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391301139
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.278")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391301139"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391301139"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391301139"))][Get cited by]]

OpenAlex: https://openalex.org/W4391301139 (Open access: False)
    
[[https://openalex.org/A5046078938][Cong Wang]], [[https://openalex.org/A5006822602][Xin Wang]], [[https://openalex.org/A5072373593][Donglai Han]], [[https://openalex.org/A5042379128][Jing Song]], [[https://openalex.org/A5054852294][Zhong‐Min Su]], [[https://openalex.org/A5060649823][Min Zhang]], International Journal of Hydrogen Energy. 58(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.01.278 
     
Seeking multifunctional electrocatalysts capable of driving the hydrogen evolution reaction (HER), oxygen evolution reaction (OER), and oxygen reduction reaction (ORR) is becoming increasingly crucial in the realm of sustainable energy development. Herein, the multifunctional electrocatalytic activities of HER, OER, and ORR in two-dimensional (2D) boron-centered graphdiyne analogue (B-GDY) are identified by first-principles computations, and its low overpotentials of HER/OER/ORR (0.02/0.55/0.52 V) are comparable to, or even surpasses, well-developed noble-metal-based catalysts. The remarkable multifunctional electrocatalytic activity of B-GDY can be attributed to the unique orbital distribution of the 2D framework as evidenced by its highest occupied molecular orbitals (HOMO), and synergistic interplay of boron-centered carbocycles and diacetylene linkages in its unique 2D framework. More importantly, the data confirm our motivation by replacing the central C in small aromatic groups with the adjacent element of B can realize/create multi-active sites in the original aromatic functional groups (the simplest boron-centered triangulene-like units). Hence, this study not only provides cost-effective alternatives to metal-based catalysts but also paves the way for designing and developing novel, multifunctional electrocatalysts.    

    

* Mixed-valent cobalt phosphate/borophene nanohybrids for efficient electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391319509
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.188")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391319509"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391319509"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391319509"))][Get cited by]]

OpenAlex: https://openalex.org/W4391319509 (Open access: False)
    
[[https://openalex.org/A5016235312][Bitan Pratihar]], [[https://openalex.org/A5048541923][Omkar Roy]], [[https://openalex.org/A5080383377][Arijit Jana]], [[https://openalex.org/A5021909284][Sirshendu De]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.188 
     
Developing efficient, low-cost, non-precious and stable electrocatalyst is necessary for sustainable electrocatalytic water splitting. Recently, borophene has emerged as a novel two-dimensional material with exciting properties. Although several researchers have theoretically predicted its applicability towards effective electrocatalytic water splitting, studies on its practical applications are still limited. In this regard, a mixed-valent cobalt phosphate/borophene nanohybrid (BCoPi) was synthesized using hydrothermal method, and its activity towards oxygen evolution reaction (OER) was systematically studied. The electron-deficient nature of borophene enables activation of catalytic sites and facilitates electron transport owing to its highly conductive nature. It can act as a proton acceptor along with phosphate groups, as well as provide multiple secondary active sites in addition to Co, breaking the scaling relation of OER. For BCoPi, achieving a current density of 50 mA cm−2, 100 mA cm−2 and 500 mA cm−2 requires an overpotential of 337 mV, 357 mV and 401 mV, respectively, in an alkaline medium, that are superior to pristine cobalt phosphate (CoPi). It also exhibits low Tafel slope of 61.81 mV dec−1, suggesting faster OER kinetics and excellent long-term stability. This study will extend the development and application of borophene-based heterostructures for highly active and stable electrocatalysts for various applications.    

    

* Soft-templated, mesoporous Co3O4 thin films for electrocatalysis of the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391325553
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ma01054f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391325553"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391325553"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391325553"))][Get cited by]]

OpenAlex: https://openalex.org/W4391325553 (Open access: True)
    
[[https://openalex.org/A5004982680][Qingyin Wu]], [[https://openalex.org/A5067205162][Maximilian Mellin]], [[https://openalex.org/A5058407349][Stefan Lauterbach]], [[https://openalex.org/A5051788024][Cuicui Tian]], [[https://openalex.org/A5091231607][Christian Dietz]], [[https://openalex.org/A5039183696][Jan P. Hofmann]], [[https://openalex.org/A5076962213][Marcus Einert]], No host. None(None)] 2024. https://doi.org/10.1039/d3ma01054f  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ma/d3ma01054f][pdf]])
     
Mesoporous Co 3 O 4 thin films, prepared by dip-coating and using Pluronic ® F-127 as template, demonstrated improved OER activity compared to dense Co 3 O 4 by providing high surface areas with increased concentration of catalytically active surface sites.    

    

* 1D α-NiMoO4 nanorods/reduced graphene oxide nanocomposite based efficient electrocatalyst for oxygen evolution reaction and p-nitrophenol sensing  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391326843
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Biosensor Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.diamond.2024.110870")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391326843"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391326843"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391326843"))][Get cited by]]

OpenAlex: https://openalex.org/W4391326843 (Open access: False)
    
[[https://openalex.org/A5029755514][Dinesh Manandhar]], [[https://openalex.org/A5088543972][N. Gokila]], [[https://openalex.org/A5027187840][Stella Vargheese]], [[https://openalex.org/A5010520738][Yuvaraj Haldorai]], [[https://openalex.org/A5037371927][Ramasamy Thangavelu Rajendra Kumar]], Diamond and Related Materials. None(None)] 2024. https://doi.org/10.1016/j.diamond.2024.110870 
     
In this work, nickel molybdate/reduced graphene oxide (α-NiMoO4/rGO) based bifunctional electrocatalysts for oxygen evolution reaction (OER) and p-nitrophenol (p-NP) sensing were studied. To replace noble metal-based catalysts for oxygen evolution reactions, it is essential to develop a potential alternative low-cost, electrochemically active catalyst. Even at a very low level p-NP present in water is harmful to the environment, so a rapid and sensitive method for detecting the presence of p-NP is indispensable. In this study, α-NiMoO4/rGO nanocomposite has been synthesized by hydrothermal method and used for OER and p-NP sensing. The XRD and Raman analysis confirm the α phase of NiMoO4 and SEM, and HRTEM studies confirm that 1D NiMoO4 growing on 2D rGO and the length and diameter of NiMoO4 rod are 5–10 μm and 50 nm, respectively. The α-NiMoO4 and α-NiMoO4/rGO showed an over-potential of 510 mV and 450 mV vs RHE, respectively for OER. The Tafel slope of the α-NiMoO4 and α-NiMoO4/rGO exhibited 159 mV dec−1 and 121 mV dec−1, respectively. The composite was found to split water into oxygen continuously for 23 h indicating its good stability for OER. For the electrochemical sensing of p-NP, the best OER performed α-NiMoO4/rGO-10 composite was chosen and modified with GCE. The sensor exhibits two sets of the linear range 0.5–10 μM and 30–500 μM for sensing of p-NP with a limit of detection 0.256 μM and sensitivity of 3.5042 μA cm2/μM.    

    

* Sputter‐Deposited La–Co–Mn–O Nanocolumns as Stable Electrocatalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391328293
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/sstr.202300415")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391328293"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391328293"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391328293"))][Get cited by]]

OpenAlex: https://openalex.org/W4391328293 (Open access: True)
    
[[https://openalex.org/A5051844684][Tobias Horst Piotrowiak]], [[https://openalex.org/A5067459856][Olga A. Krysiak]], [[https://openalex.org/A5054007615][Ellen Suhr]], [[https://openalex.org/A5051585830][Jian Zhang]], [[https://openalex.org/A5081079430][Rico Zehl]], [[https://openalex.org/A5050028599][Aleksander Kostka]], [[https://openalex.org/A5035321019][Wolfgang Schuhmann]], [[https://openalex.org/A5048192399][Alfred Ludwig]], No host. None(None)] 2024. https://doi.org/10.1002/sstr.202300415  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/sstr.202300415][pdf]])
     
A thin‐film materials library (ML) of the La–Co–Mn–O system is fabricated by hot reactive combinatorial cosputter deposition and screened for its electrocatalytic activity for the oxygen evolution reaction. Within this ML, an area with superior catalytic activity is identified. In‐depth characterization of this region reveals a unique columnar‐grown microstructure showing a large catalytic surface and excellent stability during electrocatalytic measurements. A zoom‐in into these structures shows that the columns are compositionally and structurally not homogeneous but are composed of a mixture of the perovskite phase LaCoMnO 3 and Co–Mn–O oxide. Nanoelectrochemistry using the particle on a nanoelectrode approach confirms the high activity as well as stability of the single columns.    

    

* Surface Reconstruction of Co‐based Catalysts for Enhanced Oxygen Evolution Activity in Anion Exchange Membrane Water Electrolysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391329686
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202314573")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391329686"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391329686"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391329686"))][Get cited by]]

OpenAlex: https://openalex.org/W4391329686 (Open access: False)
    
[[https://openalex.org/A5064163109][Sanghwi Han]], [[https://openalex.org/A5078212799][Jungwon Park]], [[https://openalex.org/A5075933098][Jeyong Yoon]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202314573 
     
Abstract Developing high‐performance and durable electrocatalysts for the oxygen evolution reaction (OER) is of utmost importance for green hydrogen production via anion exchange membrane water electrolysis (AEMWE). Herein, it is presented that a straightforward surface reconstruction strategy for preparing a robust Co‐based OER catalyst with increased mass transfer activity while preserving the active CoOOH phase during the OER. This strategy comprises electrochemical oxidation of electrodeposited Co‐based catalysts prior to heat treatment, allowing for the meticulous control of the oxidation potential to optimize the OER activity. The optimized catalyst exhibits an overpotential of 190 mV at 10 mA cm −2 and a Tafel slope of 32.7 mV dec −1 under half‐cell conditions. In an AEMWE single‐cell system, it shows a current density of 1590 mA cm −2 at 1.8 V and 60 °C and demonstrates a degradation rate of 0.2 mV h −1 during 1000 h of operation at 500 mA cm −2 . This study not only provides a simple yet potent strategy to enhance the OER activity but also offers insights regarding the factors enhancing the OER performance.    

    

* Electronic Properties Modulation of NiFe-based Nanoalloy by Introducing Cu and P for Faster Oxygen Evolution Reaction Kinetics  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391337278
:TOPICS: Electrocatalysis for Energy Conversion, Atomic Layer Deposition Technology, Catalytic Nanomaterials
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaem.3c02617")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391337278"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391337278"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391337278"))][Get cited by]]

OpenAlex: https://openalex.org/W4391337278 (Open access: False)
    
[[https://openalex.org/A5042683391][Arpita Nandy]], [[https://openalex.org/A5061469016][Tanmay Ghosh]], [[https://openalex.org/A5047840240][Ravi Kumar]], [[https://openalex.org/A5088610809][D. Bhattacharyya]], [[https://openalex.org/A5039069189][Dulal Senapati]], ACS Applied Energy Materials. None(None)] 2024. https://doi.org/10.1021/acsaem.3c02617 
     
The introduction of Cu and P centers in the NiFe-based nanoalloy not only increases the stability of the resulting transition metal-based hierarchical nanostructure (NiFeCuP) but also enhances its catalytic activity (faster OER kinetics with an overpotential of 213 mV at 10 mA/cm2). Various X-ray-based techniques along with detailed electron imaging and electrochemical measurements of NiFeCuP before and after OER allowed us to understand the relationship between the local geometry of catalytically active sites and their extent of participation in the OER activity based on crystal field theory.    

    

* Self-Supporting Nanosheet Electrode for Efficient Oxygen Evolution in a Wide pH Range: Engineering Electronic Structure of Co 3 O 4 by Fe Doping  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391339137
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-3896219/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391339137"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391339137"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391339137"))][Get cited by]]

OpenAlex: https://openalex.org/W4391339137 (Open access: True)
    
[[https://openalex.org/A5016429807][Xinqi Cheng]], [[https://openalex.org/A5019707525][Ningning Han]], [[https://openalex.org/A5023302391][Guangli He]], [[https://openalex.org/A5055851483][Zhuang Xu]], No host. None(None)] 2024. https://doi.org/10.21203/rs.3.rs-3896219/v1  ([[https://www.researchsquare.com/article/rs-3896219/latest.pdf][pdf]])
     
Abstract Developing low-cost and efficient non-precious metal-based electrocatalysts for oxygen evolution reaction (OER) is of great significance for large-scale application of water electrolysis technology. Herein, we present a facile and scalable one-step pyrolysis strategy to fabricate a self-supporting nanosheet electrode involving Fe-doped Co 3 O 4 catalyst (Fe-Co 3 O 4 ) in-situ grown on carbon paper for efficient and durable OER catalysis in both alkaline and acidic electrolyte. Results show that doping Fe induces the formation of uniform a nanosheet-like morphology with larger specific surface area that facilitates the full exposure of active sites with accessible contact with electrolyte. Electrochemical test results show that the obtained Fe-Co 3 O 4 exhibits superior activity and high stability for OER catalysis in wide pH range, showing the low overpotentials of 263 and 295 mV in 1.0 M KOH and in 0.5 M H 2 SO 4 , respectively, outperforming commercial IrO 2 , and also exhibiting outstanding electrochemical stability up to 420 h in 1.0 M KOH and 15 h in 0.5 M H 2 SO 4 at 10 mA cm − 2 . X-ray photoelectron spectroscopy and DFT theoretical calculations reveal that doping Fe modifies the electronic structure of Co 3 O 4 by decreasing the valence state of Co, which upwards d band center of Co site and then promotes adsorption intensity of oxygen intermediates, leading to an enhanced OER activity. Furthermore, doping Fe also increases the cobalt vacancy formation energy in Fe-Co 3 O 4 , which inhibits the thermodynamics of Co dissolution, thus improving the structural stability during OER catalysis. This work provides a new insight into the design of high-performance of Co 3 O 4 -based non-precious electrocatalysts in both alkaline and acidic electrolyte for large-scale application of water electrolysis.    

    

* Scalable exothermic synthesis of sprout-like Ni-Co-Fe trimetallic oxide nanoparticles anchored on N-doped carbon nanotubes as bifunctional oxygen catalysts for zinc-air batteries  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391339598
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.carbon.2024.118859")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391339598"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391339598"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391339598"))][Get cited by]]

OpenAlex: https://openalex.org/W4391339598 (Open access: False)
    
[[https://openalex.org/A5057948516][Youngsun Cha]], [[https://openalex.org/A5071485475][Tae−Won Kim]], [[https://openalex.org/A5046098787][Kyungmin Kim]], [[https://openalex.org/A5079692522][Jae Wook Seo]], [[https://openalex.org/A5090943867][Ho Young Jang]], [[https://openalex.org/A5024370138][Wonjoon Choi]], Carbon. None(None)] 2024. https://doi.org/10.1016/j.carbon.2024.118859 
     
Zn-air batteries (ZABs) offer a high specific energy density, cost-effectiveness, and eco-friendliness. Hence, they are attractive candidates for use as sustainable energy-storage devices. However, their practical applications are limited by their high bifunctional oxygen evolution reaction/oxygen reduction reaction (OER/ORR) overpotential and sluggish kinetics. To address these limitations, in this study, a highly active bifunctional oxygen catalyst, TNPs@N-CNT, is developed, in which Ni-Co-Fe trimetallic nanoparticles are anchored on N-doped carbon networks. TNPs@N-CNT is synthesized via the thermally driven combustion of collodion fuel. The carbonization of melamine foam containing pyridinic N in TNPs@N-CNT enhances the ORR and affords a high catalytic surface area and high electrical conductivity. Morphological studies and chemical characterization aid in finely tuning the thermal processing conditions, affording a TNPs@N-CNT suitable for charge transfer. TNPs@N-CNT shows enhanced ORR activity (half-wave potential = 0.62 V and onset potential = 1.49 V) in alkaline media. A ZAB with TNPs@N-CNT as the air cathode exhibits an output power density of 90 mW cm−2 and excellent cycling stability for over 200 h, outperforming previously reported carbon-supported precious-metal catalysts. This tunable and scalable fabrication strategy could promote the development of novel mesoporous structures combined with high-efficiency multi-metallic catalysts for applications in energy-storage systems.    

    

* Interface effect of MXene/CoP2 on oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391345030
:TOPICS: Two-Dimensional Transition Metal Carbides and Nitrides (MXenes), Memristive Devices for Neuromorphic Computing, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.matlet.2024.136024")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391345030"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391345030"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391345030"))][Get cited by]]

OpenAlex: https://openalex.org/W4391345030 (Open access: False)
    
[[https://openalex.org/A5053911795][Xiu Juan Du]], [[https://openalex.org/A5028486288][Yan Wang]], [[https://openalex.org/A5045672660][Zicong Ye]], [[https://openalex.org/A5029061297][Wei Wang]], [[https://openalex.org/A5067124076][Yuqiao Wang]], Materials Letters. None(None)] 2024. https://doi.org/10.1016/j.matlet.2024.136024 
     
Zero/two-dimension MXene/CoP2 was fabricated by hydrothermal and chemical vapor deposition phosphate. MXene nanosheets were employed as substrate to increase dispersion and stability of the multicomponent catalyst. The morphology of CoP2 was regulated by the addtion of Co precursor in hydrothermal process. The catalyst prepared by 40 mg MXene with 0.5 mmol Co precursor (MXene/CoP2-0.5) showed a uniform growth of CoP2 and formed aboundant reaction sites. The interfacial electron transfer between MXene and CoP2 modulated the electron structure of CoP2 and stimulated the oxygen evolution reaction (OER) activity. The optimized MXene/CoP2-0.5 exhibited the OER overpotential of 263 mV and a long-term stability over 16 h. Modulating the interfacial electron transfer of multicomponent catalysts provided a guidance for electrocatalyst design and synthesis.    

    

* Modulating positive charge sites generations and iron oxidation state transitions in FeP4/CoP/C p-n heterojunction toward efficient oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391352975
:TOPICS: Electrocatalysis for Energy Conversion, Atomic Layer Deposition Technology, Memristive Devices for Neuromorphic Computing
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149121")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391352975"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391352975"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391352975"))][Get cited by]]

OpenAlex: https://openalex.org/W4391352975 (Open access: False)
    
[[https://openalex.org/A5032791091][Pandeng Zhao]], [[https://openalex.org/A5018569451][Peng Cheng]], [[https://openalex.org/A5030386675][Yuancong Luo]], [[https://openalex.org/A5034521153][Lingli Cheng]], [[https://openalex.org/A5010444377][Zhen Li]], [[https://openalex.org/A5057732263][Z. Jiao]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149121 
     
Promoting the formation of positive charge active sites and high oxidation state FeOOH in the heterojunction electrocatalyst can enhance its intrinsic activity for oxygen evolution reaction (OER). However, the current synthesis methods that can simultaneously achieve both properties remain a great challenge. In this work, a feasible strategy for concurrently promoting the generation of positive charge active sites and high oxidation state metal species by constructing a heterojunction between FeP4 and CoP is proposed. Specifically, the p-n heterojunction between FeP4 and CoP is constructed by pyrolysis of MIL88A@FeCoLDH prepared by introducing Co through cation exchange using MIL88A as a template. The experimental and density functional theory calculation analyses suggest the construction of p-n heterojunction can effectively modulate the electron structure, optimize the d-band center, induce the generation of strong space charge region, and shorten the bond length of Fe-O, thus promoting the formation of positive charge active sites and high active species FeOOH and the adsorption ability of oxygen-containing intermediates for enhancing the OER performance. Benefiting from the synergistic effect between positive charge active sites and FeOOH, the obtained FeP4/CoP/C electrocatalyst exhibits a low overpotential of 258 mV for the OER at a current density of 10 mA cm−2 and superior stability at 20 mA cm−2 for 52 h. This work gives insights into the charge regulation effect in the heterojunction for enhancing the OER catalytic activity and provides a general strategy for designing more efficient oxygen evolution electrocatalysts.    

    

* Geometric and Electronic Engineering in Co/VN Nanoparticles to Boost Bifunctional Oxygen Electrocatalysis for Aqueous/Flexible Zn‐Air Batteries  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391360504
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/chem.202303943")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391360504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391360504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391360504"))][Get cited by]]

OpenAlex: https://openalex.org/W4391360504 (Open access: False)
    
[[https://openalex.org/A5024654016][Zuyang Luo]], [[https://openalex.org/A5090438111][Jie Gong]], [[https://openalex.org/A5047576745][Qiuxia Li]], [[https://openalex.org/A5057668939][Fengli Wei]], [[https://openalex.org/A5072477902][B. Liu]], [[https://openalex.org/A5021114807][Tayirjan Taylor Isimjan]], [[https://openalex.org/A5002897591][Yuting Yang]], No host. None(None)] 2024. https://doi.org/10.1002/chem.202303943 
     
Modulating metal‐metal and metal‐support interactions is one of the potent tools for augmenting catalytic performance. Herein, highly active Co/VN nanoparticles are well dispersed on three‐dimensional porous carbon nanofoam (Co/VN@NC) with the assistance of dicyandiamide. Studies certify that the consequential disordered carbon substrate reinforces the confinement of electrons, while the coupling of diverse components optimizes charge redistribution among species. Besides, theoretical analyses confirm that the regulated electron configuration can significantly tune the binding strength between the active sites and intermediates, thus optimizing reaction energy barriers. Therefore, Co/VN@NC exhibits a competitive potential difference (ΔE, 0.65 V) between the half‐wave potential of ORR and OER potential at 10 mA cm−2, outperforming Pt/C+RuO2 (0.67 V). Further, catalyst‐based aqueous/flexible ZABs present superior performances with peak power densities of 156 and 85 mW cm−2, superior to Pt/C‐based counterparts (128 and 73 mW cm−2). This research provides a pivotal foundation for the evolution of bifunctional catalysts in the energy sector.    

    

* Lowering the Coordination of Octahedra in Spinel Oxides by the Robust Fe–N Bonds for Enhancing Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391362025
:TOPICS: Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05344")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391362025"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391362025"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391362025"))][Get cited by]]

OpenAlex: https://openalex.org/W4391362025 (Open access: False)
    
[[https://openalex.org/A5061418233][Yantao Wang]], [[https://openalex.org/A5000364516][Jinzhi Jia]], [[https://openalex.org/A5079262736][Xiaohua Zhao]], [[https://openalex.org/A5062426880][Wenhui Hu]], [[https://openalex.org/A5021987795][Hua Li]], [[https://openalex.org/A5073327563][Xiaowan Bai]], [[https://openalex.org/A5002884743][Junfeng Huang]], [[https://openalex.org/A5047171623][Jinhua Zhang]], [[https://openalex.org/A5052883326][Jian Li]], [[https://openalex.org/A5038927175][Xiaohai Tang]], [[https://openalex.org/A5070724508][Yong Peng]], [[https://openalex.org/A5038255119][Jier Huang]], [[https://openalex.org/A5018390453][Cailing Xu]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05344 
     
The coordination environment of octahedra in spinel oxides plays a vital role in regulating the OER performance. But selectively engineering the octahedral units is very challenging for the design of low-cost and high-efficient electrocatalysts. In this work, the low Fe coordinated CoFe2O4 (CoFe2O4–Cd) is successfully obtained by taking advantage of the different bond strength between metal centers and N atoms in 7,7,8,8-tetracyanoquinodimethane-decorated CoFe-MOF-74 (CoFe-MOF-74/TCNQ) and shows promising physical and chemical properties. DFT calculations reveal that the low-coordinated Fe improves the electrochemical symmetry of catalysts and reduces the free energy barrier of the potential-determining step, resulting in the high activity and stability of CoFe2O4–Cd. Systematic experimental and theoretical analyses demonstrate that TCNQ motivates the more electron-occupied states at the Fermi level of CoFe-MOF-74 and enhances the hybridization of Co 3d, Fe 3d, and N 2p, leading to the formation of the Co/Fe–N bond. Owing to the stronger Fe–N bonds, CoFe-MOF-74/TCNQ realizes the step-by-step phase transformation upon electrochemical activation, achieving the CoFe2O4–Cd. This work advances the current comprehension of the controllable regulation of coordination environment of octahedra in spinel oxides, which in turn contributes to the design of high-performance electrocatalysts for OER.    

    

* Insights into supramolecular and molecular electrocatalytic properties for oxygen and hydrogen evolution reactions of 1,2-bis(diphenylphosphine)ethane appended nickel(II) 1,2-dithiosquarate  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391363873
:TOPICS: Molecular Magnetism and Spintronics, Platinum-Based Cancer Chemotherapy, Coexistence of Ferromagnetism and Metallic Conductivity in Organic Molecular Metals
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nj00247d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391363873"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391363873"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391363873"))][Get cited by]]

OpenAlex: https://openalex.org/W4391363873 (Open access: False)
    
[[https://openalex.org/A5071110704][Aparna Kushwaha]], [[https://openalex.org/A5056040682][Devyani Srivastava]], [[https://openalex.org/A5007016647][Gabriele Kociok‐Köhn]], [[https://openalex.org/A5022402882][Yogita Padwal]], [[https://openalex.org/A5025202071][Ratna Chauhan]], [[https://openalex.org/A5029112460][Suresh Gosavi]], [[https://openalex.org/A5030834706][Mohd. Muddassir]], [[https://openalex.org/A5064559096][Abhinav Kumar]], New Journal of Chemistry. None(None)] 2024. https://doi.org/10.1039/d4nj00247d 
     
A new heteroleptic Ni(II) dithiolate [Nidppe(dtsq)] (Nidtsq) (dppe = 1,2-bis-(diphenylphosphino)ethane, dtsq2- = 3,4-dioxocyclobut-1-ene-1,2-dithiolate) has been synthesised and characterized spectroscopically and by single crystal X-ray diffraction. The single crystal X-ray diffraction...    

    

* Trimetallic-organic framework/MXene composite as an oxygen evolution reaction electrocatalyst with elevated intrinsic activity  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391364318
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Two-Dimensional Transition Metal Carbides and Nitrides (MXenes)
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00131a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391364318"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391364318"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391364318"))][Get cited by]]

OpenAlex: https://openalex.org/W4391364318 (Open access: False)
    
[[https://openalex.org/A5023644242][Mahrokh Nazari]], [[https://openalex.org/A5024817634][Ali Morsali]], No host. None(None)] 2024. https://doi.org/10.1039/d4ta00131a 
     
A composite of trimetallic Fe 2.1 Ni 0.2 Co 0.7 -MIL-88A grown on Ti 3 C 2 T x MXene nanosheets was successfully synthesized and employed as a high-performance OER electrocatalyst with a low overpotential of 231 mV at 10 mA cm −2 current density in alkaline media.    

    

* Cop Nanoparticles Embedded in N-Doped Carbon for Highly Efficient Oxygen Evolution Reaction Electrocatalysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391365597
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Conducting Polymer Research
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4710700")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391365597"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391365597"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391365597"))][Get cited by]]

OpenAlex: https://openalex.org/W4391365597 (Open access: False)
    
[[https://openalex.org/A5006592632][Zewu Zhang]], [[https://openalex.org/A5070879896][Yifan Dai]], [[https://openalex.org/A5075427631][L.Y. Chen]], [[https://openalex.org/A5004600892][Jiakai Bai]], [[https://openalex.org/A5061173049][Xiaohai Bu]], [[https://openalex.org/A5022583323][Jiehua Bao]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4710700 
     
Development of high-activity and low-cost electrocatalysts is significant to enhance the low-kinetic process of oxygen evolution reaction (OER). In this paper, we utilized the self-assembly between melamine, phytic acid and cobalt ions to obtain two-dimensional Co-MPA. Subsequently, in situ phosphating of Co ions to obtain CoP/N-CNT was achieved by the pyrolytic of Co-MPA. The small size of CoP (~18 nm) and the N-doped carbon material endowed CoP/N-CNT with excellent OER electrocatalytic activity, which delivered an overpotential of 285 mV to drive a current density of 10 mA cm-2. Moreover, the TOF value of CoP/N-CNT catalyst is 4.6 times higher than the incumbent commercial RuO2 catalyst (at the overpotential of 480 mV), providing it as a promising electrocatalyst for OER.    

    

* Single-atom catalysts for electrocatalytic oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391488890
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/b978-0-323-95237-8.00012-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391488890"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391488890"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391488890"))][Get cited by]]

OpenAlex: https://openalex.org/W4391488890 (Open access: False)
    
[[https://openalex.org/A5069942203][Ajit Singh]], [[https://openalex.org/A5071537088][B. N. Singh]], [[https://openalex.org/A5019059433][Arindam Indra]], Elsevier eBooks. None(None)] 2024. https://doi.org/10.1016/b978-0-323-95237-8.00012-4 
     
In recent years, a series of noble metals and transition metal-based single-atom catalysts (SACs) have been explored for electrochemical oxygen evolution reaction (OER). The unique structural and electronic features of the SACs facilitate the OER with maximum atomic utilization. As a result, a high turnover frequency is achieved with SACs. In this chapter, we have summarized the fundamentals of the SACs and their design strategies for electrochemical OER. The detailed characterization of the SACs and its utilization in OER has been discussed with suitable examples. The principles and reaction mechanism of electrochemical OER with SACs have been discussed looking at the structure of the active catalyst and reaction intermediates.    

    

* Reconstructing Hydrogen‐Bond Network for Efficient Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391328163
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202319462")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391328163"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391328163"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391328163"))][Get cited by]]

OpenAlex: https://openalex.org/W4391328163 (Open access: False)
    
[[https://openalex.org/A5049330397][Shicheng Zhu]], [[https://openalex.org/A5027981734][Ruoou Yang]], [[https://openalex.org/A5023169057][Huangjingwei Li]], [[https://openalex.org/A5011612912][Sirui Huang]], [[https://openalex.org/A5040389793][Haozhi Wang]], [[https://openalex.org/A5032965785][Youwen Liu]], [[https://openalex.org/A5028386144][Huiqiao Li]], [[https://openalex.org/A5069378732][Tianrui Zhai]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202319462 
     
Developing highly active oxygen evolution reaction (OER) catalysts in acidic conditions is a pressing demand for proton‐exchange membrane water electrolysis. Manipulating proton character at the electrified interface, as the crux of all proton‐coupled electrochemical reactions, is highly desirable but elusive. Herein we present a promising protocol, which reconstruct a connected hydrogen‐bond network beween the catalyst‐electrolyte interface by coupling hydrophilic units to boost acidic OER activity. Modelling on N‐doped‐carbon‐layer clothed Mn‐doped‐Co3O4 (Mn‐Co3O4@CN), we unravel that the hydrogen‐bond interaction between CN units and H2O molecule not only drags the free water to enrich the surface of Mn‐Co3O4 but also serves as a channel to promote the dehydrogenation process. Meanwhile, the modulated local charge of the Co sites from CN units/Mn dopant lowers the OER barrier. Therefore, Mn‐Co3O4@CN surpasses RuO2 at high current density (100 mA cm‐2 @ ~538 mV).    

    

* Reconstructing Hydrogen‐Bond Network for Efficient Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391329795
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202319462")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391329795"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391329795"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391329795"))][Get cited by]]

OpenAlex: https://openalex.org/W4391329795 (Open access: False)
    
[[https://openalex.org/A5049330397][Shicheng Zhu]], [[https://openalex.org/A5027981734][Ruoou Yang]], [[https://openalex.org/A5023169057][Huangjingwei Li]], [[https://openalex.org/A5011612912][Sirui Huang]], [[https://openalex.org/A5040389793][Haozhi Wang]], [[https://openalex.org/A5032965785][Youwen Liu]], [[https://openalex.org/A5028386144][Huiqiao Li]], [[https://openalex.org/A5069378732][Tianrui Zhai]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202319462 
     
Developing highly active oxygen evolution reaction (OER) catalysts in acidic conditions is a pressing demand for proton‐exchange membrane water electrolysis. Manipulating proton character at the electrified interface, as the crux of all proton‐coupled electrochemical reactions, is highly desirable but elusive. Herein we present a promising protocol, which reconstruct a connected hydrogen‐bond network beween the catalyst‐electrolyte interface by coupling hydrophilic units to boost acidic OER activity. Modelling on N‐doped‐carbon‐layer clothed Mn‐doped‐Co3O4 (Mn‐Co3O4@CN), we unravel that the hydrogen‐bond interaction between CN units and H2O molecule not only drags the free water to enrich the surface of Mn‐Co3O4 but also serves as a channel to promote the dehydrogenation process. Meanwhile, the modulated local charge of the Co sites from CN units/Mn dopant lowers the OER barrier. Therefore, Mn‐Co3O4@CN surpasses RuO2 at high current density (100 mA cm‐2 @ ~538 mV).    

    

* Role of A-sites in pyrochlore lanthanide ruthenate for electrocatalysis of oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391450654
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jmat.2023.12.009")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391450654"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391450654"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391450654"))][Get cited by]]

OpenAlex: https://openalex.org/W4391450654 (Open access: True)
    
[[https://openalex.org/A5002424714][Hengyu Guo]], [[https://openalex.org/A5026495381][Zhengping Zhang]], [[https://openalex.org/A5085586043][Feng Wang]], Journal of Materiomics. None(None)] 2024. https://doi.org/10.1016/j.jmat.2023.12.009 
     
Developing highly stable and efficient catalysts for oxygen evolution reaction (OER) is extremely important to sustainable energy conversion and storage, but improved efficiency is largely hindered by sluggish reaction kinetics. Dense and bimetal ruthenates have emerged as one of the promising substitutes to replace single-metal ruthenium or iridium oxides, but the fundamental understanding the role of A-site cations is still blurring. Herein, a family of lanthanides (Ln = all the lanthanides except Pm) are applied to synthesize pyrochlore lanthanide ruthenates (Ln2Ru2O7), and only Ln2Ru2O7 (Ln = Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb, or Lu) with pure phase can be obtained by the ambient-pressure calcination. Compared with the perovskite ruthenates (SrRuO3) and rutile RuO2, the [RuO6] units in these Ln2Ru2O7 present the largely distorted configurations and different energy level splitting to prevent the excessive Ru oxidation and dissolution, which leads the primary improvement in the electrocatalytic OER performance. In the similar crystalline field split states, the charge transfer between [RuO6] units and Ln3+ cations also affect catalytic activities, even in the Ln2Ru2O7 surface reconstruction during the OER process. Consequently, Tb2Ru2O7 showed the highest OER performance among all the prepared Ln2Ru2O7 with similar morphologies and crystallization. This systematic work gives fundamental cognition to rational design of high-performance OER electrocatalysts in proper water electrolysis technologies.    

    

* NiCo2O4/MXene hybrid as an efficient bifunctional electrocatalyst for oxygen evolution and reduction reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391296391
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301250")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391296391"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391296391"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391296391"))][Get cited by]]

OpenAlex: https://openalex.org/W4391296391 (Open access: False)
    
[[https://openalex.org/A5016038695][Ashalatha Vazhayil]], [[https://openalex.org/A5015987837][Vazhayal Linsha]], [[https://openalex.org/A5086819981][Shyamli Ashok C]], [[https://openalex.org/A5087024992][Jasmine Thomas]], [[https://openalex.org/A5053127989][Nygil Thomas]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301250 
     
For the advancement of energy conversion and storage technologies, bifunctional electrocatalysts are crucial for efficiently driving both the oxygen evolution (OER) and reduction reactions (ORR). Cobalt‐based spinel oxides are a class of promising bifunctional electrocatalysts. However their low electrical conductivity and stability may hinder further improvement. A novel composite material composed of NiCo2O4(NCO) nanoparticles integrated with emerging two dimensional MXene nanosheets (NCO/MXene) was developed. The successful integration of NCO with MXene brings about a number of attractive structural features. This includes synergistic effects between NCO and MXene, highly accessible surface areas, complete exposure of numerous active sites, and excellent electronic conductivity, all of which collectively contribute to the desirability of composite material for OER and ORR. The synthesized NCO/MXene composite showed extraordinary OER electrocatalytic activity with a lower overpotential of 360 mV at a current density of 10 mA/cm2, and a small Tafel slope of 64.63 mV/dec compared to NCO, MXene and NCO+MXene (physically mixed). Additionally, it displays a superior ORR limiting current density (‐4 mA/cm2). In particular, it exhibited highest onset potential and half wave potential of 0.92 V and 0.72 V vs. RHE, respectively, for the ORR in alkaline media    

    

* Tailoring Metal-Ion-Doped Carbon Nitrides for Photocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391486029
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05961")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391486029"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391486029"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391486029"))][Get cited by]]

OpenAlex: https://openalex.org/W4391486029 (Open access: False)
    
[[https://openalex.org/A5006958502][Shanping Liu]], [[https://openalex.org/A5080802270][Valentin Diez‐Cabanes]], [[https://openalex.org/A5069062661][Dong Fan]], [[https://openalex.org/A5080107062][Peixiang Lu]], [[https://openalex.org/A5027738164][Yuanxing Fang]], [[https://openalex.org/A5075963769][Markus Antonietti]], [[https://openalex.org/A5087859676][Guillaume Maurin]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05961 
     
Poly(heptazine imides) (PHIs) have emerged as prominent layered carbon nitride-based materials with potential oxygen evolution reaction (OER) catalytic activity owing to their strong VIS light absorption, long excited-state lifetimes, high surface-to-volume ratios, and the possibility of tuning their properties via hosting different metal ions in their pores. A series of metal-ion-doped PHI-M (M = K+, Rb+, Mg2+, Zn2+, Mn2+, and Co2+) were first systematically explored using density functional theory calculations. These simulations led an in-depth understanding of the microscopic OER mechanism in these systems and identified PHI-Co2+ as the best OER catalyst of this family of PHIs, whereas PHI-Mn2+ can be an alternative promising OER catalyst. This level of performance was attributed to a thermodynamically favorable formation of the reaction intermediates as well as its red-shifted absorption in the VIS region involving the population of long-lived states, as revealed by time-dependent density functional theory calculations. We further demonstrated that the electronic properties of the *OH intermediates (Bader population, crystal orbital Hamilton population analysis, and adsorption energies) are reliable descriptors to anticipate the OER activity of this family of PHIs. This rational analysis paved the way toward the prediction of the OER performance of another PHI-M derivative, i.e., PHI-Fe2+. The computationally explored PHI-Fe2+, PHI-Mn2+, and PHI-Co2+ systems were then synthesized alongside PHI-K+, and their photocatalytic OER activities were assessed. These experimental findings confirmed the best photocatalytic OER performance for PHI-Co2+ with an oxygen production of 31.2 μmol·h–1 that is 60 times higher than the pristine g-C3N4 (0.5 μmol·h–1), whereas PHI-Fe2+ and PHI-Mn2+ are seen as alternative OER catalysts with attractive oxygen production of 11.20 and 4.69 μmol·h–1, respectively. Decisively, this joint experimental–computational study reveals PHI-Co2+ to be among the best of the OER catalysts so far reported in the literature including some perovskites.    

    

* Machine Learning-Based Optimization Method for the Oxygen Evolution and Reduction Reaction of the High-Entropy Alloy Catalysts  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391330920
:TOPICS: High-Entropy Alloys: Novel Designs and Properties, Atom Probe Tomography Research, Thermal Barrier Coatings for Gas Turbines
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.17762/ijritcc.v11i9.9214")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391330920"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391330920"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391330920"))][Get cited by]]

OpenAlex: https://openalex.org/W4391330920 (Open access: True)
    
[[https://openalex.org/A5093816237][Et al. Jagannath Jijaba Kadam]], International Journal on Recent and Innovation Trends in Computing and Communication. 11(9)] 2023. https://doi.org/10.17762/ijritcc.v11i9.9214 
     
In recent times, high-entropy alloys (HEAs) have found application in heterogeneous catalysis, capitalizing on their vast chemical potential. Yet, this extensive chemical landscape presents significant challenges when attempting a comprehensive exploration of HEAs through traditional trial-and-error approaches. Therefore, the machine learning (ML) approach is offered to appearance into the catalytic activity (CA) of countless sensitive sites on HEA surfaces in the oxygen-lessening response (ORR) and oxygen evolution reactions (OER). In this research, a Density Functional Theory (DFT) with a supervised ML model is assembled and founded on the gradient boosting regression (GBR) algorithm that predicted the O2 adsorption energies with a high overpotential of all surface sites on the two HEAs. Initially, the HEAs Co-Fe-Ga-Ni-Zn and Al-Cu-Pd-Pt offer a framework for adjusting the composition of disordered multi-metallic alloys to regulate the activity and selectivity of the reduction of oxygen to extremely reduced compounds. This attains generalizability, high accuracy and simplicity with the proposed technique. For fine-tuning such features, HEAs provide a huge compositional space. Consequently, the research reports the custom of the Bayesian optimization model based on HEA active compositions to suppress the formation of Oxygen (O2) and with strong O2 adsorption to favour the lessening of O2. The GBR approach is applied to build a highly accurate, easily generalizable, and effective ML model. The proposed work is analysed using Python software. The findings show that the separate charities of correlated metal atoms close to the responsive site are mixed to form the adsorption energy, which is clear from a thorough analysis of the data. It is suggested that a highly effective HEA catalyst composed of Co-Fe-Ga-Ni-Zn and Al-Cu-Pd-Pt be exploited, which is an effective method for further enhancing the ORR CA of potential HEA catalysts. An instruction manual for the logical design and synthesis of HEA catalysts' nanostructures is provided by the proposed research.    

    

* Novel Amorphous Feooh-Modified Co9s8 Nanosheets with Enhanced Oxygen Evolution Reaction Activity  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391405828
:TOPICS: Catalytic Reduction of Nitro Compounds, Formation and Properties of Nanocrystals and Nanostructures, Materials for Electrochemical Supercapacitors
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4711575")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391405828"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391405828"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391405828"))][Get cited by]]

OpenAlex: https://openalex.org/W4391405828 (Open access: False)
    
[[https://openalex.org/A5007803202][Chong Wang]], [[https://openalex.org/A5036746330][Huanlu Tu]], [[https://openalex.org/A5071814351][Zeyu Hao]], [[https://openalex.org/A5037742951][Yaxin Li]], [[https://openalex.org/A5038906848][Jing Xu]], [[https://openalex.org/A5016312685][Xiaoying Hu]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5037428389][Hongwei Tian]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4711575 
     
Efficient oxygen evolution reaction (OER) is important for water electrolysis and advanced hydrogen production energy. However, the sluggish kinetics of this reaction require significant overpotentials, leading to high energy consumption. Therefore, developing OER electrocatalysts with exceptional performance and long-term durability is crucial for enhancing the energy efficiency and cost-effectiveness of the hydrogen production process. In this paper, novel FeOOH/Co9S8 catalysts were prepared through a two-step hydrothermal reaction followed by one-step electrodeposition on nickel foam substrates for an alkaline oxygen evolution reaction (OER). The as-obtained catalysts possessed abundant non-homogeneous interfaces between FeOOH and Co9S8 nanosheets, conducive to optimized coordination environments of Fe and Co sites through the redistribution of interfacial charges. This strengthened the chemisorption of oxygenated intermediates, leading to accelerated reaction kinetics, abundant active sites, and enhanced OER properties. The optimized electrocatalyst FeOOH/Co9S8 achieved a current density of 10 mA cm-2 at an overpotential of 248 mV coupled with good stability for over 140 h. Overall, a novel approach for producing effective and durable alkaline dielectric OER electrocatalysts was proposed, useful for future manufacturing of advanced energy devices.    

    

* Medium-Entropy Co–Fe–Cr–Mo Spinel Nanoflowers as Electrocatalysts for Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391464648
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.3c05568")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391464648"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391464648"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391464648"))][Get cited by]]

OpenAlex: https://openalex.org/W4391464648 (Open access: False)
    
[[https://openalex.org/A5007542563][Yuhang Sun]], [[https://openalex.org/A5006901660][Tianmi Tang]], [[https://openalex.org/A5072475535][Liyuan Xiao]], [[https://openalex.org/A5053838411][Jingyi Han]], [[https://openalex.org/A5086755732][Xue Bai]], [[https://openalex.org/A5033773174][Mingyuan Shi]], [[https://openalex.org/A5086922328][Siyu Chen]], [[https://openalex.org/A5007095017][Jingru Sun]], [[https://openalex.org/A5060962227][Yuanyuan Ma]], [[https://openalex.org/A5074571254][Jingqi Guan]], ACS Applied Nano Materials. None(None)] 2024. https://doi.org/10.1021/acsanm.3c05568 
     
Oxygen evolution reaction (OER) plays an important role in many electrocatalysis-related fields. However, the slow kinetics of the OER seriously hinders energy efficiency. Here, we synthesize flower-like Co–Fe–Cr–Mo medium-entropy spinel (MES) nanosheets on nickel foam (NF) using one-step solvothermal method for the OER. Due to high stability and compositional diversity, the CoFeCrMoOx/NF catalyst exhibits excellent electrocatalytic OER performance with an overpotential of only 196 mV at 10 mA cm–2 in 1.0 M KOH solution, much lower than CoFeCrMnOx/NF, CoFeCrCeOx/NF, CoFeCrSnOx/NF, CoFeCrAlOx/NF, and commercial IrO2 catalysts, reflecting that the formation of flower-like MES has a positive effect on the improvement of OER performance. The introduction of Mo increases active sites, promotes electron transfer, accelerates the adsorption and desorption of the OER intermediates, reduces the energy barrier, and thus improves the performance of the OER. In situ Raman spectra indicate that the surface CoOOH and FeOOH species are important active components for the OER.    

    

* Mesoporous hydrogel electrodes with flexible framework exhibiting enhanced mass transport for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391509597
:TOPICS: Conducting Polymer Research, Fuel Cell Membrane Technology, Electrochemical Biosensor Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3cc04632j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391509597"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391509597"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391509597"))][Get cited by]]

OpenAlex: https://openalex.org/W4391509597 (Open access: False)
    
[[https://openalex.org/A5078670038][Ritsuki Nakajima]], [[https://openalex.org/A5093855209][Hiroki Wago]], [[https://openalex.org/A5067573679][Tatsuya Taniguchi]], [[https://openalex.org/A5061217758][Yuta Sasaki]], [[https://openalex.org/A5065223963][Yoshinori Nishiki]], [[https://openalex.org/A5054248011][Zaenal Awaludin]], [[https://openalex.org/A5031262649][Takaaki Nakai]], [[https://openalex.org/A5005243857][Akihisa Kato]], [[https://openalex.org/A5093855210][Mitsushima Mitsushima]], [[https://openalex.org/A5090206527][Yoshiyuki Kuroda]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d3cc04632j 
     
Mesoporous hydrogel electrodes with unique flexible mesopores surrounded by CoOOH nanosheets were prepared via the electrochemical deposition of hybrid cobalt hydroxide nanosheets, exhibiting high oxygen evolution reaction activity at a...    

    

* Co atom-doped NiMoO4 Hierarchical hollow nanosheet-based-nanosphere for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391343114
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.22541/au.170664116.61933326/v1")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391343114"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391343114"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391343114"))][Get cited by]]

OpenAlex: https://openalex.org/W4391343114 (Open access: False)
    
[[https://openalex.org/A5012770110][Zhuoxun Yin]], [[https://openalex.org/A5045073916][Min Zhou]], [[https://openalex.org/A5018077554][Xinping Li]], [[https://openalex.org/A5057117758][Xiangcun Liu]], [[https://openalex.org/A5070267350][Xinzhi Ma]], [[https://openalex.org/A5020624661][Yang Zhou]], [[https://openalex.org/A5017541508][Wei Chen]], [[https://openalex.org/A5086155499][Jinlong Li]], Authorea (Authorea). None(None)] 2024. https://doi.org/10.22541/au.170664116.61933326/v1 
     
Hollow structures with hierarchical architecture and multi-composition have attracted extensive interest because of their fascinating physicochemical properties as well as wide applications. to improve the efficiency of overall water splitting, highly active and stable electrocatalysts are highly desirable. A novel high-efficiency Hierarchical hollow nanosheet-based-nanosphere Co-NiMoO4-HNS electrocatalyst for oxygen evolution was arranged by doping Co on Ni-MoEG yolk/shelll nanosphere. Remarkably, the hierarchical hollow Co2-NiMoO4-HNS catalyst exhibits favorable catalytic performance toward the oxygen evolution reaction (OER) with a receivable overpotential of 270 mV achieving a current density of 10 mA cm−2 and a Tafel slope of 65 mV dec−1. In expansion, as a electrocatalyst, Co2-NiMo4-HNS appeared to have great long-term steadiness in the electrolyte. This work may give broad hypothetical and specialized back for the plan of cost-effective bifunctional electrocatalysts.    

    

* A rational strategy for CoFe layered double hydroxide oxygen evolution catalysts with high activity and stability  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391311547
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Aqueous Zinc-Ion Battery Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.colsurfa.2024.133360")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391311547"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391311547"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391311547"))][Get cited by]]

OpenAlex: https://openalex.org/W4391311547 (Open access: False)
    
[[https://openalex.org/A5081751519][Linfeng Yang]], [[https://openalex.org/A5007024868][Shuang Yu]], [[https://openalex.org/A5040998948][Feng Luo]], [[https://openalex.org/A5052053894][Yang Liu]], [[https://openalex.org/A5017761703][Xiaoqiang Wu]], [[https://openalex.org/A5000124572][Xiao‐Nan Liu]], Colloids and Surfaces A: Physicochemical and Engineering Aspects. None(None)] 2024. https://doi.org/10.1016/j.colsurfa.2024.133360 
     
Oxygen evolution reaction (OER) catalyzed by non-precious metals and their compounds in alkaline environments are regarded as a key research topic for the use of water for hydrogen production to alleviate the global energy crisis. Cobalt-iron layered double hydroxide (CoFe-LDH) has attracted much attention as a potential high-performance oxygen evolution reaction catalyst. In this paper, we report a strategy to introduce metal elements M (M = Cu, K, Al, Cr and Zn) into CoFe-LDH to further enhance the OER performance. The experimental results show that CoFeK-15 exhibits the lowest overpotential (203 mV to reach 10 mA cm-2) and Tafel slope (77.1 mV dec-1) and maintains excellent catalytic activity after 50 h i-t test. Through the introduction of potassium ions, the electronic structure inside the catalyst underwent lattice distortion, resulting in a larger active surface area and exposure of more oxygen vacancies, which in turn accelerated the OER reaction. This study reveals the important influence of potassium doping on the electronic structure modification strategy to enhance the performance of OER and provides new ideas for the development of more efficient catalysts in the future.    

    

* Regulating the Electronic Structure of Metal–Organic Frameworks by Introducing Mn for Enhanced Oxygen Evolution Activity  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391401818
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Chemistry and Applications of Metal-Organic Frameworks
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.3c03769")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391401818"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391401818"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391401818"))][Get cited by]]

OpenAlex: https://openalex.org/W4391401818 (Open access: False)
    
[[https://openalex.org/A5049341927][Hao Zhang]], [[https://openalex.org/A5007651004][Na Sun]], [[https://openalex.org/A5074890326][Xie Si]], [[https://openalex.org/A5065075495][Yuehong Zhang]], [[https://openalex.org/A5057969449][Fu Ding]], [[https://openalex.org/A5067035683][Xiangru Kong]], [[https://openalex.org/A5036393374][Yaguang Sun]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.3c03769 
     
The construction of low-cost and highly efficient oxygen evolution electrocatalysts is paramount for clean and sustainable hydrogen energy. In recent years, metal–organic framework (MOF) OER electrocatalysts have attracted tremendous research attention. Herein, we report a simple and facile strategy to construct bimetallic MOFs (named CoMn0.01) for enhancing OER catalytic performance. Significantly, CoMn0.01 exhibited remarkable OER activity (255 mV at 10 mA cm–2) and a low Tafel slope of 66 mV dec–1, superior to those of commercial benchmark electrocatalysts (RuO2, 352 mV, 178 mV dec–1). Besides, the catalyst demonstrated outstanding longevity for 144 h at a current density of 100 mA cm –2. Mn doping can regulate the electronic structure of Co MOFs, which optimizes charge transfer capability and improves conductivity.    

    

* Surface Addition of Ag on Pbo2 to Enable Efficient Oxygen Evolution Reaction in Ph-Neutral Media  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391339279
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4697150")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391339279"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391339279"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391339279"))][Get cited by]]

OpenAlex: https://openalex.org/W4391339279 (Open access: False)
    
[[https://openalex.org/A5034855042][Siming Li]], [[https://openalex.org/A5047811811][Min Shi]], [[https://openalex.org/A5072254497][Chen Wu]], [[https://openalex.org/A5032967714][Kaiqi Nie]], [[https://openalex.org/A5052267876][Zheng Wang]], [[https://openalex.org/A5050687293][Xiaoxu Jiang]], [[https://openalex.org/A5038908444][Xinbing Liu]], [[https://openalex.org/A5063251071][Huili Chen]], [[https://openalex.org/A5024069386][Xinlong Tian]], [[https://openalex.org/A5053821178][Daoxiong Wu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4697150 
     
Developing a catalyst with high pH-neutral performance for oxygen evolution reaction (OER) is highly desirable due to its mild corrosion, low pollution, and ability to maintain system efficiency while reducing operating costs. However, the current earth-abundant metal oxide electrocatalysts developed for OER have poor performance in neutral media. This study introduces a novel strategy for fabricating a PbO2+Ag composite electrode with significantly improved OER activity and stability in a pH-neutral environment. Our results suggest that incorporating Ag as a surface additive improves the efficiency of utilizing absorbed oxygenated species via the bridge-site-top-site pathway. This effect is particularly pronounced in pH-neutral solutions where the concentration of hydroxyl is significantly limited. Furthermore, the surface decoration of Ag resulted in enhanced electrocatalytic stability. The results not only establish a method for utilizing PbO2 in pH-neutral OER applications, but also propose a potential strategy for employing less noble catalysts in cost-effective electrochemical energy conversions.    

    

* Photocatalytic and Oxygen Evolution Reaction (OER) of Novel Supercritical Fluid Synthesized Nanobiocomposite MoS2/Silk G  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391402616
:TOPICS: Biomedical Applications of Silk Biomaterials, Nanomaterials with Enzyme-Like Characteristics, Textile Dyeing Techniques and Materials
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.14233/ajchem.2024.30910")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391402616"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391402616"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391402616"))][Get cited by]]

OpenAlex: https://openalex.org/W4391402616 (Open access: True)
    
[[https://openalex.org/A5023544432][S. Chetana]], [[https://openalex.org/A5092333050][Halligudra Guddappa]], [[https://openalex.org/A5018368252][Sanjay Upadhyay]], [[https://openalex.org/A5040310257][Naveen Chandra Joshi]], [[https://openalex.org/A5045625228][Niraj Kumar]], [[https://openalex.org/A5038735783][Priyvart Choudhary]], [[https://openalex.org/A5076148023][Vikas N. Thakur]], Asian Journal of Chemistry. 36(2)] 2024. https://doi.org/10.14233/ajchem.2024.30910  ([[https://asianpubs.org/index.php/ajchem/article/download/36_2_20/29506][pdf]])
     
The photocatalytic activity and oxygen evolution reaction (OER) of MoS2 and silk graphene (silk G) composite synthesized using supercritical fluids and chemical vapor deposition (CVD) methods were investigated for their potential application in photocatalysis. This material was subjected to characterize by XRD, TEM, SEM and FTIR techniques to demonstrate that MoS2/silk G composite still existed in the supercritical fluids methods obtained MoS2 & MoS2/silk G. The optical features of MoS2 was improved by introduction of silk G, which inturn caused shift in band gap from 1.65 to 1.85 eV. Within visible region, creation of high electron-hole pairs is possible by adequate band gap modifications. The fast movement of photo-induced charge carrier can be enhanced by silk G as they decrease the recombination activity. Additionally, the MoS2/silk G shows high oxygen evolution reaction with low Tafel slope of 157.2 mV dec-1 and low overpotential of 603 mV at a current density of 10 mA cm-2. The present study signifies that with addition of silk G in the MoS2 host improved the photocatalytic activity by 13% and electrocatalytic activity by nearly 5% compared to bare MoS2 nanoparticles.    

    

* A Novel Synthesis and Enhanced Electrochemical Performance of Nickelocene-Derived Hexagonal Nickel Hydroxide in Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391407386
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4704432")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391407386"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391407386"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391407386"))][Get cited by]]

OpenAlex: https://openalex.org/W4391407386 (Open access: False)
    
[[https://openalex.org/A5051392796][Sher Zaman]], [[https://openalex.org/A5093833613][Naila Gulshan]], [[https://openalex.org/A5022523912][Ghulam Ali]], [[https://openalex.org/A5055386927][Faheem K. Butt]], [[https://openalex.org/A5036334797][Shahid Ali]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4704432 
     
The Oxygen evolution reaction is in high demand for clean energy applications, particularly in water splitting for hydrogen production. Researchers are actively developing efficient catalyst designs to improve OER performance, contributing to solutions for global energy and environmental challenges. This study focused on the synthesis of nickel hydroxide as an efficient catalyst for OER using two different precursors: nickelocene and nickel sulfate tetrahydrate (NiSO4.4H2O). The characterizations showed that the sample prepared using nickelocene as a precursor (Ni(OH)2-N), had a hexagonal shape, uniform size, and was highly crystalline, while the sample prepared using nickel sulfate tetrahydrate (Ni(OH)2-NS) had a spherical shape, non-uniform sizes and low order of crystallinity. The electrochemical performance for the OER of the samples was evaluated using linear sweep voltammetry in a solution of 1M potassium hydroxide (KOH). The results demonstrate that the Ni(OH)2-N sample exhibited a lower overpotential (274 mV) compared to the Ni(OH)2-NS sample (495 mV) at a current density of 10 mA/cm2. The low overpotential may be due to the high crystallinity in the sample that possesses a large number of well-defined crystalline domains, which act as efficient charge transport pathways during the oxygen evolution reaction, leading to improved reaction kinetics and overall performance. This suggests that nickel hydroxide synthesized using nickelocene may be a promising alternative to noble metals and provides a basis for further work on the development of new electro-catalysts.    

    

* Ir loaded Co(OH)2 nanosheets with vacancy defects for boosting oxygen evolution reaction and stability  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391482605
:TOPICS: Electrocatalysis for Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures, Electrochemical Detection of Heavy Metal Ions
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcat.2024.115352")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391482605"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391482605"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391482605"))][Get cited by]]

OpenAlex: https://openalex.org/W4391482605 (Open access: False)
    
[[https://openalex.org/A5070461940][Junfang Zhang]], [[https://openalex.org/A5027089731][Xiang Li]], [[https://openalex.org/A5008154965][Zehao Zang]], [[https://openalex.org/A5031461208][Chuanyan Fan]], [[https://openalex.org/A5007861370][Yubo Luo]], [[https://openalex.org/A5027943437][Lanlan Li]], [[https://openalex.org/A5025634082][Xiaofei Yu]], [[https://openalex.org/A5055910967][Xiaojing Yang]], [[https://openalex.org/A5014712188][Zunming Lu]], [[https://openalex.org/A5064217591][Xinghua Zhang]], Journal of Catalysis. None(None)] 2024. https://doi.org/10.1016/j.jcat.2024.115352 
     
Transition metal hydroxides have great potential as oxygen evolution reaction (OER) catalysts, while its low reaction kinetics and unsatisfactory stability limits the further application. Herein, Co(OH)2 nanosheets with oxygen vacancies defects and anchored Ir atoms and clusters (Ir/D-Co(OH)2) were prepared by electrochemical deposition and in-situ etching. The Introduction of Ir species is beneficial to regulate the valence electron configuration on Co 3d orbit and enhance the conductivity, which contributes to improving kinetics of Co(OH)2. In addition, the introduced defects not only regulate the adsorption energy barrier of reaction intermediates, but also serve as anchor centers for stabilizing Ir atoms and clusters, thus enhancing the active surface area and catalytic stability. The Ir/D-Co(OH)2/NF catalyst owns ultralow OER potential of 270.5 mV at 100 mA cm-2, and it has superior long-term stability under high current density of 100 mA cm-2 for 100 hours. This work provides a simple method to design noble atoms loaded transition metal hydroxides with specific defects for enhancing OER performance and high stability.    

    
