#+TITLE: water splitting
Description: water splitting papers
Created on Sun Mar  3 00:46:19 2024

Found 27 results from 2024-02-25 to 2024-03-03
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Nanoflowers of Ternary Cobalt–Copper–Manganese Oxide as an Efficient Electrocatalyst for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392130324
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ente.202301355")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392130324"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392130324"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392130324"))][Get cited by]]

OpenAlex: https://openalex.org/W4392130324 (Open access: False)
    
[[https://openalex.org/A5003445703][Jyoti Raghav]], [[https://openalex.org/A5045408244][P. Rosaiah]], [[https://openalex.org/A5051674509][Bandar Ali Al‐Asbahi]], [[https://openalex.org/A5001688048][Soumyendu Roy]], Energy Technology. None(None)] 2024. https://doi.org/10.1002/ente.202301355 
     
Oxygen evolution reaction (OER) is an integral step in the water‐splitting process. Hence, to promote OER, efficient catalysts are required to lower the energy barriers at the electrode/electrolyte interface. Low‐cost and highly active catalysts are in great demand. Herein, a ternary metal oxide, CoCuMnO x , synthesized by a facile hydrothermal method is reported, which possesses excellent catalytic ability for OER in alkaline electrolytes. The nanoscale morphology of the catalyst with flower‐like nanostructures is instrumental in increasing the electrochemical surface area of the electrode. The presence of multivalent ions and the incorporation of copper greatly enhance the electrochemical properties of the catalysts. The catalysts typically demonstrate an overpotential value of 220 mV for achieving 10 mA cm −2 current density and a Tafel slope of 73 mV dec −1 . The catalysts demonstrate good stability with minimal degradation in OER activity even after 20 h of chronopotentiometry test. For practical applications, this low‐cost material holds great potential.    

    

* Tracking accelerated oxygen evolution reaction enabled by explosive reconstruction of active species based on CoxN@NC  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392135567
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00196f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392135567"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392135567"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392135567"))][Get cited by]]

OpenAlex: https://openalex.org/W4392135567 (Open access: False)
    
[[https://openalex.org/A5042054457][Hyung Wook Choi]], [[https://openalex.org/A5091554389][Jiwon Kim]], [[https://openalex.org/A5015012876][Hyeon‐Seok Bang]], [[https://openalex.org/A5078354747][Khaled Badawy]], [[https://openalex.org/A5024947859][Ui Young Lee]], [[https://openalex.org/A5049204244][Dong In Jeong]], [[https://openalex.org/A5039821968][Yeseul Kim]], [[https://openalex.org/A5054520248][Kotiba Hamad]], [[https://openalex.org/A5078886160][Bong Kyun Kang]], [[https://openalex.org/A5079700977][Byung Mook Weon]], [[https://openalex.org/A5001603223][Hyung Suk Oh]], [[https://openalex.org/A5017583868][Nirpendra Singh]], [[https://openalex.org/A5045038094][Dae Ho Yoon]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d4ta00196f 
     
The development of a hierarchical structure of Co/Co 4 N@NC has been successfully achieved. The robust oxygen evolution reaction activity of Co/Co 4 N@NC is attributed to the modulation of the d-band center, which reconstruct Co 2+ into Co 3+ .    

    

* Interface‐Engineered NiFe/Ni‐S Nanoparticles for Reliable Alkaline Oxygen Production at Industrial Current: A Sulfur Source Confinement Strategy  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392139199
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Layered Double Hydroxide Nanomaterials
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310737")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392139199"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392139199"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392139199"))][Get cited by]]

OpenAlex: https://openalex.org/W4392139199 (Open access: False)
    
[[https://openalex.org/A5010217323][Bin Chen]], [[https://openalex.org/A5017882728][Tao Liu]], [[https://openalex.org/A5027689004][Xiangwen Zhang]], [[https://openalex.org/A5048537490][Shichao Zhao]], [[https://openalex.org/A5061055076][Runfei Yue]], [[https://openalex.org/A5040298454][Sipu Wang]], [[https://openalex.org/A5038532525][Lianqin Wang]], [[https://openalex.org/A5015399496][Zhihao Chen]], [[https://openalex.org/A5019670440][Yingjie Feng]], [[https://openalex.org/A5052713328][Jun Huang]], [[https://openalex.org/A5079178497][Yan Yin]], [[https://openalex.org/A5021480695][Michael D. Guiver]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202310737 
     
Abstract Using powder‐based ink appears to be the most suitable candidate for commercializing the membrane electrode assembly (MEA), while research on the powder‐based NPM catalyst for anion exchange membrane water electrolyzer (AEMWE) is currently insufficient, especially at high current density. Herein, a sulfur source (NiFe Layered double hydroxide adsorbed ) confinement strategy is developed to integrate Ni 3 S 2 onto the surface of amorphous/crystalline NiFe alloy nanoparticles (denoted NiFe/Ni‐S), achieving advanced control over the sulfidation process for the formation of metal sulfides. The constructed interface under the sulfur source confinement strategy generates abundant active sites that increase electron transport at the electrode‐electrolyte interface and improve ability over an extended period at a high current density. Consequently, the constructed NiFe/Ni‐S delivers an ultra‐low overpotential of 239 mV at 10 mA cm −2 and 0.66 mA under an overpotential of 300 mV. The AEMWE with NiFe/Ni‐S anode exhibits a cell voltage of 1.664 V @ 0.5 A cm −2 and a 400 h stability at 1.0 A cm −2 .    

    

* Phytic-acid-doped conductive hydrogels as alkaline seawater electrocatalysts with anomalous chloride promoted oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392139371
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159754")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392139371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392139371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392139371"))][Get cited by]]

OpenAlex: https://openalex.org/W4392139371 (Open access: False)
    
[[https://openalex.org/A5027580867][Lin Hu]], [[https://openalex.org/A5058103707][Xuecai Tan]], [[https://openalex.org/A5078231129][Rui Luo]], [[https://openalex.org/A5043057827][Xiao-Ju Wen]], [[https://openalex.org/A5051350429][Xiankun Wu]], [[https://openalex.org/A5041854485][Hua-xun Luo]], [[https://openalex.org/A5072559438][Zhenghao Fei]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159754 
     
No abstract    

    

* Seven mechanisms of oxygen evolution reaction proposed recently: A mini review  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392142198
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149992")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392142198"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392142198"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392142198"))][Get cited by]]

OpenAlex: https://openalex.org/W4392142198 (Open access: False)
    
[[https://openalex.org/A5022885630][Zhixuan Feng]], [[https://openalex.org/A5037480797][Chia-Tsen Dai]], [[https://openalex.org/A5032553249][Peng Shi]], [[https://openalex.org/A5060430863][Xuefei Lei]], [[https://openalex.org/A5021363847][Rui Guo]], [[https://openalex.org/A5075523709][Biao Wang]], [[https://openalex.org/A5081185893][Xuanwen Liu]], [[https://openalex.org/A5019520436][Jinyuan You]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149992 
     
No abstract    

    

* P-doped RuPd nanoparticles anchored on Y2Ru2-xPdxO7 pyrochlore oxide surface as oxygen evolution and reduction electrocatalysts for Zn-air battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392142396
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159788")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392142396"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392142396"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392142396"))][Get cited by]]

OpenAlex: https://openalex.org/W4392142396 (Open access: False)
    
[[https://openalex.org/A5052090122][Geunhyeong Lee]], [[https://openalex.org/A5017828132][Eun-Su Jang]], [[https://openalex.org/A5050138704][Pei-Chen Su]], [[https://openalex.org/A5009818257][Jooheon Kim]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159788 
     
No abstract    

    

* Distance effect of single atoms on stability of cobalt oxide catalysts for acidic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392153698
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-46176-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392153698"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392153698"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392153698"))][Get cited by]]

OpenAlex: https://openalex.org/W4392153698 (Open access: True)
    
[[https://openalex.org/A5000151255][Z. D. Zhang]], [[https://openalex.org/A5046463704][Chuanyi Jia]], [[https://openalex.org/A5063955135][Peiyu Ma]], [[https://openalex.org/A5021979312][Feng Chen]], [[https://openalex.org/A5071791749][Yang Jin]], [[https://openalex.org/A5041677976][Jian Huang]], [[https://openalex.org/A5049713859][Jian‐Guo Zheng]], [[https://openalex.org/A5043676611][Ming J. Zuo]], [[https://openalex.org/A5045653991][Mingkai Liu]], [[https://openalex.org/A5039567536][Shiming Zhou]], [[https://openalex.org/A5075571728][Jie Zeng]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-46176-0  ([[https://www.nature.com/articles/s41467-024-46176-0.pdf][pdf]])
     
Abstract Developing efficient and economical electrocatalysts for acidic oxygen evolution reaction (OER) is essential for proton exchange membrane water electrolyzers (PEMWE). Cobalt oxides are considered promising non-precious OER catalysts due to their high activities. However, the severe dissolution of Co atoms in acid media leads to the collapse of crystal structure, which impedes their application in PEMWE. Here, we report that introducing acid-resistant Ir single atoms into the lattice of spinel cobalt oxides can significantly suppress the Co dissolution and keep them highly stable during the acidic OER process. Combining theoretical and experimental studies, we reveal that the stabilizing effect induced by Ir heteroatoms exhibits a strong dependence on the distance of adjacent Ir single atoms, where the OER stability of cobalt oxides continuously improves with decreasing the distance. When the distance reduces to about 0.6 nm, the spinel cobalt oxides present no obvious degradation over a 60-h stability test for acidic OER, suggesting potential for practical applications.    

    

* Exfoliation of Metal–Organic Frameworks to Give 2D MOF Nanosheets for the Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392156438
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202402969")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392156438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392156438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392156438"))][Get cited by]]

OpenAlex: https://openalex.org/W4392156438 (Open access: False)
    
[[https://openalex.org/A5049967323][Peng Wu]], [[https://openalex.org/A5039931061][Shuang Geng]], [[https://openalex.org/A5021984184][Xinyu Wang]], [[https://openalex.org/A5039734738][Xinglong Zhang]], [[https://openalex.org/A5007884941][Hongfeng Li]], [[https://openalex.org/A5070961992][Lulu Zhang]], [[https://openalex.org/A5037726491][Yu Shen]], [[https://openalex.org/A5057374450][Baoli Zha]], [[https://openalex.org/A5086476705][Suoying Zhang]], [[https://openalex.org/A5040039962][Fengwei Huo]], [[https://openalex.org/A5023634611][Weina Zhang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202402969 
     
The structure and properties of materials are determined by a diverse range of chemical bond formation and breaking mechanisms, which greatly motivates the development of selectively controlling the chemical bonds in order to achieve materials with specific characteristics. Here, an orientational intervening bond‐breaking strategy is demonstrated for synthesizing ultrathin metal–organic framework (MOF) nanosheets through balancing the process of thermal decomposition and liquid nitrogen exfoliation. In such approach, proper thermal treatment can weaken the interlayer bond while maintaining the stability of the intralayer bond in the layered MOFs. And the following liquid nitrogen treatment results in significant deformation and stress in the layered MOFs’ structure due to the instant temperature drop and drastic expansion of liquid N2, leading to the curling, detachment, and separation of the MOF layers. The produced MOF nanosheets with five cycles of treatment are primarily composed of nanosheets that are less than 10 nm in thickness. The MOF nanosheets exhibit enhanced catalytic performance in oxygen evolution reactions owing to the ultrathin thickness without capping agents which provide improved charge transfer efficiency and dense exposed active sites. This strategy underscores the significance of orientational intervention in chemical bonds to engineer innovative materials.    

    

* Exfoliation of Metal–Organic Frameworks to Give 2D MOF Nanosheets for the Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392166415
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202402969")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392166415"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392166415"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392166415"))][Get cited by]]

OpenAlex: https://openalex.org/W4392166415 (Open access: False)
    
[[https://openalex.org/A5049967323][Peng Wu]], [[https://openalex.org/A5039931061][Shuang Geng]], [[https://openalex.org/A5021984184][Xinyu Wang]], [[https://openalex.org/A5039734738][Xinglong Zhang]], [[https://openalex.org/A5007884941][Hongfeng Li]], [[https://openalex.org/A5070961992][Lulu Zhang]], [[https://openalex.org/A5037726491][Yu Shen]], [[https://openalex.org/A5057374450][Baoli Zha]], [[https://openalex.org/A5086476705][Suoying Zhang]], [[https://openalex.org/A5040039962][Fengwei Huo]], [[https://openalex.org/A5086476705][Suoying Zhang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202402969 
     
The structure and properties of materials are determined by a diverse range of chemical bond formation and breaking mechanisms, which greatly motivates the development of selectively controlling the chemical bonds in order to achieve materials with specific characteristics. Here, an orientational intervening bond‐breaking strategy is demonstrated for synthesizing ultrathin metal–organic framework (MOF) nanosheets through balancing the process of thermal decomposition and liquid nitrogen exfoliation. In such approach, proper thermal treatment can weaken the interlayer bond while maintaining the stability of the intralayer bond in the layered MOFs. And the following liquid nitrogen treatment results in significant deformation and stress in the layered MOFs’ structure due to the instant temperature drop and drastic expansion of liquid N2, leading to the curling, detachment, and separation of the MOF layers. The produced MOF nanosheets with five cycles of treatment are primarily composed of nanosheets that are less than 10 nm in thickness. The MOF nanosheets exhibit enhanced catalytic performance in oxygen evolution reactions owing to the ultrathin thickness without capping agents which provide improved charge transfer efficiency and dense exposed active sites. This strategy underscores the significance of orientational intervention in chemical bonds to engineer innovative materials.    

    

* Structural reconstruction of cobalt and ferrocene-based metal-organic framework during electrochemical oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392168646
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-vlqz5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392168646"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392168646"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392168646"))][Get cited by]]

OpenAlex: https://openalex.org/W4392168646 (Open access: True)
    
[[https://openalex.org/A5071440495][Thomas Doughty]], [[https://openalex.org/A5094005131][Andrea Zingl]], [[https://openalex.org/A5070524825][Maximilian Wünschek]], [[https://openalex.org/A5035468865][Christian M. Pichler]], [[https://openalex.org/A5006409298][Matthew Watkins]], [[https://openalex.org/A5019861460][Souvik Roy]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-vlqz5  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65d88265e9ebbb4db90983ee/original/structural-reconstruction-of-cobalt-and-ferrocene-based-metal-organic-framework-during-electrochemical-oxygen-evolution-reaction.pdf][pdf]])
     
Metal-organic frameworks (MOFs) are increasingly being investigated as electrocatalysts for oxygen evolution reaction (OER) due to their unique modular structures that present a hybrid between molecular and heterogeneous catalysts, featuring well-defined active sites. However, many fundamental questions remain open regarding the electrochemical stability of MOFs, structural reconstruction of coordination sites, and the role of in situ-formed species. Here we report structural transformation of a surface-grown MOF containing cobalt nodes and 1,1’-ferrocenedicarboxylic acid linkers (denoted as CoFc-MOF) during OER in alkaline electrolyte. Ex situ and in situ investigations of CoFc-MOF film suggests that the MOF acts as a pre-catalyst and undergoes a two-step restructuring process under operating conditions to generate a metal oxyhydroxide phase. The MOF-derived metal oxyhydroxide catalyst, supported on nickel foam electrodes, displays high activity towards OER with an overpotential of 190 mV at the current density of 10 mA cm–2. While this study demonstrates the necessity of investigating structural evolution of MOFs in electrocatalysis, it also shows potential of using MOFs as precursors in catalyst design.    

    

* Electroactive heterojunctions of iron-based compounds in oxygen evolution reaction – insight into synergy and mechanism  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392170706
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144005")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392170706"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392170706"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392170706"))][Get cited by]]

OpenAlex: https://openalex.org/W4392170706 (Open access: False)
    
[[https://openalex.org/A5034044475][Anna Dymerska]], [[https://openalex.org/A5064148144][Ewa Mijowska]], [[https://openalex.org/A5030552243][Almaz L. Zinnatullin]], [[https://openalex.org/A5005873235][Rustem Zairov]], [[https://openalex.org/A5064148144][Ewa Mijowska]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144005 
     
This research addresses the inherent challenges of low catalytic activity and stability often associated with Oxygen Evolution Reaction (OER) catalysts. We designed composites with outstanding electrocatalytic performance. The methodology is characterized by low-temperature operation and environmentally friendly substrates. We have successfully fostered a synergistic interplay between Fe and oxygen, carbon and nickel, respectively. Fabricated material composed of three different heterojunctions triggered the stability of the catalyst and facilitated efficient charge transfer in OER. Our optimized catalyst (Fe/Ni_3.0h), emerges as a promising candidate for practical applications, exhibiting an overpotential of 310 mV, a Tafel slope of 37 mV/dec, and a potential retention of 98.8% which is a 50% lower drop in respect to commercial RuO2. Therefore, our approach underlines the substantial influence of conductive Fe-based materials: FeNi3, Fe3C, and Fe3O4 on OER performance with revealed comprehensive mechanism via ex-situ XRD and Mössbauer spectroscopy analyses.    

    

* Surface addition of Ag on PbO2 to enable efficient oxygen evolution reaction in pH-neutral media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392184832
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392184832"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392184832"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392184832"))][Get cited by]]

OpenAlex: https://openalex.org/W4392184832 (Open access: False)
    
[[https://openalex.org/A5041930796][Siming Li]], [[https://openalex.org/A5047811811][Meng Shi]], [[https://openalex.org/A5072254497][Chen Wu]], [[https://openalex.org/A5032967714][Kaiqi Nie]], [[https://openalex.org/A5052267876][Zheng Wang]], [[https://openalex.org/A5050687293][Xiaoxu Jiang]], [[https://openalex.org/A5038908444][Xinbing Liu]], [[https://openalex.org/A5063251071][Huili Chen]], [[https://openalex.org/A5024069386][Xinlong Tian]], [[https://openalex.org/A5053821178][Daoxiong Wu]], [[https://openalex.org/A5041930796][Siming Li]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150043 
     
Electrocatalysts, particularly earth-abundant metal oxide ones, exhibit poor performance in catalyzing the oxygen evolution reaction (OER) under neutral conditions due to low ionic concentrations. This study introduces a novel strategy for fabricating a PbO2 + Ag composite electrode with significantly improved OER activity and stability in a pH-neutral environment. Our results suggest that incorporating Ag as a surface additive improves the efficiency of utilizing adsorbed oxygenated species via the bridge-site-top-site pathway. Moreover, the surface decoration of Ag resulted in enhanced electrocatalytic stability by diverting the attack of oxygenated species to Pb thereby effectively preventing Pb dissolution. The results not only establish a method for utilizing PbO2 in pH-neutral OER applications, but also propose a potential strategy for employing less noble catalysts in cost-effective electrochemical energy conversions.    

    

* Carbon Nanotube Composites with Bimetallic Transition Metal Selenides as Efficient Electrocatalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392189844
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16051953")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392189844"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392189844"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392189844"))][Get cited by]]

OpenAlex: https://openalex.org/W4392189844 (Open access: True)
    
[[https://openalex.org/A5053208255][Saira Riaz]], [[https://openalex.org/A5026183354][Muhammad Shafiq Anjum]], [[https://openalex.org/A5009004798][Abid Ali]], [[https://openalex.org/A5081498908][Yasir Mehmood]], [[https://openalex.org/A5064930579][Muhammad Ahmad]], [[https://openalex.org/A5066178049][Norah Alwadai]], [[https://openalex.org/A5010504371][Munawar Iqbal]], [[https://openalex.org/A5052430989][Salih Akyürekli]], [[https://openalex.org/A5051204593][Noor Hassan]], [[https://openalex.org/A5050144026][Rizwan Shoukat]], Sustainability. 16(5)] 2024. https://doi.org/10.3390/su16051953  ([[https://www.mdpi.com/2071-1050/16/5/1953/pdf?version=1709030630][pdf]])
     
Hydrogen fuel is a clean and versatile energy carrier that can be used for various applications, including transportation, power generation, and industrial processes. Electrocatalytic water splitting could be the most beneficial and facile approach for producing hydrogen. In this work, transition metal selenide composites with carbon nanotubes (CNTs) have been investigated for electrocatalytic water splitting. The synthesis process involved the facile one-step hydrothermal growth of transition metal nanoparticles over the CNTs and acted as an efficient electrode toward electrochemical water splitting. Scanning electron microscopy and XRD patterns reveal that nanoparticles were firmly anchored on the CNTs, resulting in the formation of composites. The electrochemical measurements reveal that CNT composite with nickel–cobalt selenides (NiCo-Se/CNTs@NF) display remarkable oxygen evolution reaction (OER) activity in basic media, which is an important part of hydrogen production. It demonstrates the lowest overpotential (η10mAcm−2) of 0.560 V vs. RHE, a reduced Tafel slope of 163 mV/dec, and lower charge transfer impedance for the OER process. The multi-metallic selenide composite with CNTs demonstrating unique nanostructure and synergistic effects offers a promising platform for enhancing electrocatalytic OER performance and opens up new avenues for efficient energy conversion and storage applications.    

    

* Ultrasmall Ruthenium Nanoclusters Anchored on Thiol-Functionalized Metal–Organic Framework as a Catalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392191736
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.3c06102")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392191736"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392191736"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392191736"))][Get cited by]]

OpenAlex: https://openalex.org/W4392191736 (Open access: False)
    
[[https://openalex.org/A5085843260][Biswajit Mishra]], [[https://openalex.org/A5050309292][Swayamprakash Biswal]], [[https://openalex.org/A5065162947][Bijay P. Tripathi]], ACS Applied Nano Materials. None(None)] 2024. https://doi.org/10.1021/acsanm.3c06102 
     
No abstract    

    

* Stability challenges and opportunities of NiFe‐based electrocatalysts for oxygen evolution reaction in alkaline media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392196226
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cnl2.110")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392196226"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392196226"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392196226"))][Get cited by]]

OpenAlex: https://openalex.org/W4392196226 (Open access: True)
    
[[https://openalex.org/A5006182339][Yujun Han]], [[https://openalex.org/A5001395097][Jingyi Wang]], [[https://openalex.org/A5064684366][Yuhang Liu]], [[https://openalex.org/A5087372065][Tianqi Li]], [[https://openalex.org/A5031555539][Tongzhou Wang]], [[https://openalex.org/A5024541563][Xinyue Li]], [[https://openalex.org/A5013256964][X. J. Ye]], [[https://openalex.org/A5027334799][Guodong Li]], [[https://openalex.org/A5063383376][Jihong Li]], [[https://openalex.org/A5069789783][Wenbin Hu]], [[https://openalex.org/A5073977425][Yida Deng]], Carbon Neutralization. None(None)] 2024. https://doi.org/10.1002/cnl2.110  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cnl2.110][pdf]])
     
Abstract Water splitting is a critical process for the production of green hydrogen, contributing to the advancement of a circular economy. However, the application of water splitting devices on a large scale is primarily impeded by the sluggish oxygen evolution reaction (OER) at the anode. Thus, developing and designing efficient OER catalysts is a significant target. NiFe‐based catalysts are extensively researched as excellent OER electrocatalysts due to their affordability, abundant reserves, and intrinsic activities. However, they still suffer from long‐term stability challenges. To date, few systematic strategies for improving OER durability have been reported. In this review, various advanced NiFe‐based catalysts are introduced. Moreover, the OER stability challenges of NiFe‐based electrocatalysts in alkaline media, including iron segregation, structural degradation, and peeling from the substrate are summarized. More importantly, strategies to enhance OER stability are highlighted and opportunities are discussed to facilitate future stability studies for alkaline water electrolysis. This review presents a design strategy for NiFe‐based electrocatalysts and anion exchange membrane (AEM) electrolyzers to overcome stability challenges in OER, which also emphasizes the importance of long‐term stability in alkaline media and its significance for achieving large‐scale commercialization.    

    

* Pyridine caused structural reconfiguration forming ultrathin 2D metal-organic frameworks for oxygen evolution reaction.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392205602
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Nanomaterials with Enzyme-Like Characteristics, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ta08079j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392205602"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392205602"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392205602"))][Get cited by]]

OpenAlex: https://openalex.org/W4392205602 (Open access: False)
    
[[https://openalex.org/A5002109316][Liusi Yang]], [[https://openalex.org/A5077139864][Shuwei Deng]], [[https://openalex.org/A5037703959][Shenyuan Fu]], [[https://openalex.org/A5054834291][Xiaoteng Wang]], [[https://openalex.org/A5013487932][Gang Liu]], [[https://openalex.org/A5033332677][Haidong Yang]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d3ta08079j 
     
Two-dimensional metal-organic frameworks (2D MOFs) as an ideal prototype material for electrocatalytic oxygen evolution reaction (OER) can expose more metal active sites due to their ultrathin 2D structure. Herein, a...    

    

* Oxygen evolution reaction on iridium-molybdenum mixed oxide electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392181502
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2019-10-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392181502"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392181502"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392181502"))][Get cited by]]

OpenAlex: https://openalex.org/W4392181502 (Open access: False)
    
[[https://openalex.org/A5047338943][Cédric Tard]], [[https://openalex.org/A5053316352][Marine Elmaalouf]], [[https://openalex.org/A5028372389][Silvia Durán]], [[https://openalex.org/A5017960042][Mateusz Odziomek]], [[https://openalex.org/A5065949519][Marco Faustini]], [[https://openalex.org/A5087775789][Cédric Boissière]], [[https://openalex.org/A5072727657][Marion Giraud]], [[https://openalex.org/A5007926541][Jennifer Péron]], No host. None(None)] 2019. None 
     
No abstract    

    

* The behaviors of electrochemical oxygen intercalation of some oxygen-deficient ferrites and physical properties of perovskite Sr2LaFe3O8.95 prepared by electrochemical oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392225188
:TOPICS: Synthesis and Applications of Ferrite Nanoparticles, Multiferroic and Magnetoelectric Materials, Magnetocaloric Materials Research
:PUBLICATION_DATE: 1997-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392225188"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392225188"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392225188"))][Get cited by]]

OpenAlex: https://openalex.org/W4392225188 (Open access: True)
    
[[https://openalex.org/A5056667091][Fang Zhou]], No host. None(None)] 1997. None  ([[https://theses.hal.science/tel-00833236/document][pdf]])
     
No abstract    

    

* Tailoring First Coordination Sphere of Dual‐Metal Atom Sites Boosts Oxygen Reduction and Evolution Activities  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392139655
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-02-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202315376")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392139655"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392139655"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392139655"))][Get cited by]]

OpenAlex: https://openalex.org/W4392139655 (Open access: False)
    
[[https://openalex.org/A5083673334][Zhe Wang]], [[https://openalex.org/A5021418048][Ruojie Xu]], [[https://openalex.org/A5006151140][Qitong Ye]], [[https://openalex.org/A5058923008][Jin X]], [[https://openalex.org/A5082619738][Zhe Lü]], [[https://openalex.org/A5055796972][Zhenbei Yang]], [[https://openalex.org/A5035836023][Yong Wang]], [[https://openalex.org/A5032912701][Tao Yan]], [[https://openalex.org/A5009315315][Yipu Liu]], [[https://openalex.org/A5008216048][Zhijuan Pan]], [[https://openalex.org/A5004164674][Seong‐Ju Hwang]], [[https://openalex.org/A5015059832][Hong Jin Fan]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202315376 
     
Abstract It is important to tune the coordination configuration of dual‐atom catalyst (DAC), especially in the first coordination sphere, to render high intrinsic catalytic activities for oxygen reduction/evolution reactions (ORR/OER). Herein, a type of atomically dispersed and boron‐coordinated DAC structure, namely, FeN 4 B‐NiN 4 B dual sites, is reported. In this structure, the incorporation of boron into the first coordination sphere of FeN 4 /NiN 4 atomic sites regulates its geometry and electronic structure by forming “Fe‐B‐N” and “Ni‐B‐N” bridges. The FeN 4 B‐NiN 4 B DAC exhibits much enhanced ORR and OER property compared to the FeN 4 ‐NiN 4 counterparts. Density functional theory calculations reveal that the boron‐induced charge transfer and asymmetric charge distributions of the central Fe/Ni atoms optimize the adsorption and desorption behavior of the ORR/OER intermediates and reduce the activation energy for the potential‐determining step. Zinc‐air batteries employing the FeN 4 B‐NiN 4 B cathode exhibit a high maximum power density (236.9 mW cm −2 ) and stable cyclability up to 1100 h. The result illustrates the pivotal role of the first‐coordination sphere of DACs in tuning the electrochemical energy conversion and storage activities.    

    

* Nanocomposites of Carbon for Metal-Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392207371
:TOPICS: Lithium-ion Battery Technology, Materials for Electrochemical Supercapacitors, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/978-981-99-9931-6_7")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392207371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392207371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392207371"))][Get cited by]]

OpenAlex: https://openalex.org/W4392207371 (Open access: False)
    
[[https://openalex.org/A5043747431][Kriti Shrivastava]], [[https://openalex.org/A5080277395][Ankur Jain]], Engineering materials. None(None)] 2024. https://doi.org/10.1007/978-981-99-9931-6_7 
     
Extensive studies are being made on clean and sustainable energy conversion technologies to harness their potential in terms of great efficiency, large-scale uses, and negligible greenhouse gas emissions including fuel cells, metal-air batteries, and water-splitting techniques. Among them all, metal-air batteries are the most promising systems for portable electronic devices, electrical vehicles, and stationary microgrid applications due to their high energy density. However, the major limitation is the fundamental issues with their mechanism. The efficiency of energy conversion and storage is controlled by the oxygen reduction reaction (ORR) and oxygen evolution reaction (OER), which are generally very slow and require noble metal catalysts for fast operation. The high cost and limited availability of noble metals caused a growing interest in developing metal-free carbons as a novel class of bifunctional electrocatalysts. These materials display exceptional strength, stability, conductivity, large surface area, and high stability in both acidic and alkaline environments and therefore can play a significant role in the field of clean energy storage/conversion technologies. In this chapter, the recent advances regarding the rational design of carbon-based electrocatalysts for the oxygen reduction reaction and oxygen evolution reaction are summarized, with a special focus on their applications in Zn–air and Li–air batteries.    

    

* A new Co-doped PbO2 anode for copper electrowinning: Electrochemical and morphological characterization  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392180202
:TOPICS: Electrodeposition and Composite Coatings, Conducting Polymer Research, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2024.111053")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392180202"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392180202"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392180202"))][Get cited by]]

OpenAlex: https://openalex.org/W4392180202 (Open access: False)
    
[[https://openalex.org/A5050857507][Rasoul Rezaei]], [[https://openalex.org/A5055042300][K. Jafarzadeh]], [[https://openalex.org/A5066547318][S.M. Mirali]], [[https://openalex.org/A5090753750][hadiseh mazhari abbasi]], Journal of Energy Storage. 85(None)] 2024. https://doi.org/10.1016/j.est.2024.111053 
     
Anodic electrodeposition was used to create a high catalytic activity Co-doped PbO2 composite coating on Ti substrate, in order to reduce the overpotential and raising the electrocatalytic activity for oxygen evolution during the copper electrowinning process. The temperature, composition, and current density of the electrolyte were investigated in order to produce a composite anode with the best electrocatalytic behavior, stability, and efficiency in the electrowinning process. Scanning electron microscopy (SEM) was utilized to investigate the morphology of the coating, and electrowinning, cyclic voltammetry (CV), and the accelerated life time test (ALT) were employed to evaluate the electrodes' electrochemical behavior. The ideal conditions in this investigation involved 65 g.L−1 cobalt nitrate with a 5 mA.cm−2 current density at 65 °C for the electrodeposition of Co-doped PbO2 coating. Furthermore, the potential for oxygen evolution of the PbO2-CoOx anode was found to be approximately 180 and 220 mV lower than that of the PbO2 and Pb-Ca-Sn anodes, respectively, based on the results of the electrochemical test. The ALT test results showed that the PbO2-CoOx anode had a significantly lower initial cell voltage than the Pb-Ca-Sn and PbO2 anodes; however, this value increased after 165 h due to the anode's mechanical breakdown. The results showed that Cu electrowinning efficiency for Pb-Ca-Sn, PbO2, and PbO2-CoOx was 91.9 %, 98.4 %, and 100 % respectively.    

    

* Dual-site segmentally synergistic catalysis mechanism: boosting CoFeSx nanocluster for sustainable water oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392165142
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-45700-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392165142"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392165142"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392165142"))][Get cited by]]

OpenAlex: https://openalex.org/W4392165142 (Open access: True)
    
[[https://openalex.org/A5027128330][Siran Xu]], [[https://openalex.org/A5066350763][Sihua Feng]], [[https://openalex.org/A5049816813][Yue Yu]], [[https://openalex.org/A5048201598][Dongping Xue]], [[https://openalex.org/A5072864302][Mengli Liu]], [[https://openalex.org/A5032208819][Chao Wang]], [[https://openalex.org/A5009148187][Kaiyue Zhao]], [[https://openalex.org/A5073687384][Bingjun Xu]], [[https://openalex.org/A5058865217][Jianan Zhang]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-45700-6  ([[https://www.nature.com/articles/s41467-024-45700-6.pdf][pdf]])
     
Abstract Efficient oxygen evolution reaction electrocatalysts are essential for sustainable clean energy conversion. However, catalytic materials followed the conventional adsorbate evolution mechanism (AEM) with the inherent scaling relationship between key oxygen intermediates *OOH and *OH, or the lattice-oxygen-mediated mechanism (LOM) with the possible lattice oxygen migration and structural reconstruction, which are not favorable to the balance between high activity and stability. Herein, we propose an unconventional Co-Fe dual-site segmentally synergistic mechanism (DSSM) for single-domain ferromagnetic catalyst CoFeS x nanoclusters on carbon nanotubes (CNT) (CFS-ACs/CNT), which can effectively break the scaling relationship without sacrificing stability. Co 3+ (L.S, t 2g 6 e g 0 ) supplies the strongest OH* adsorption energy, while Fe 3+ (M.S, t 2g 4 e g 1 ) exposes strong O* adsorption. These dual-sites synergistically produce of Co-O-O-Fe intermediates, thereby accelerating the release of triplet-state oxygen ( ↑ O = O ↑ ). As predicted, the prepared CFS-ACs/CNT catalyst exhibits less overpotential than that of commercial IrO 2 , as well as approximately 633 h of stability without significant potential loss.    

    

* Efficient NiFeCr0.1/NF by incorporating chromium to boost OER catalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392135418
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mcat.2024.113980")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392135418"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392135418"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392135418"))][Get cited by]]

OpenAlex: https://openalex.org/W4392135418 (Open access: False)
    
[[https://openalex.org/A5011475097][zhonggang zhang]], [[https://openalex.org/A5004187884][Zuobo Yang]], [[https://openalex.org/A5037532055][Junan Gao]], [[https://openalex.org/A5039857226][Xiaofeng Wu]], [[https://openalex.org/A5088596691][Jimmy Yun]], [[https://openalex.org/A5008720433][Jie Zhang]], Molecular Catalysis. 557(None)] 2024. https://doi.org/10.1016/j.mcat.2024.113980 
     
This study developed ternary NiFeCr hydroxide microsphere composites for efficient oxygen evolution reaction (OER) in alkaline water. Compared to binary NiFe composites, the ternary composites exhibited superior electrocatalytic activity. In a 1 M KOH solution, the ternary composite demonstrated a low initial potential of 1.46 V (RHE), and the overpotential is only 268 mV @ 100 mA cm−2. Charge rearrangement due to chromium oxidation helped maintain iron's low oxidation state, preserving OER activity. The redistribution of chromium particles stabilized iron and prevented its dissolution in an alkaline solution. Consequently, the optimized NiFeCr catalyst exhibits excellent stability, with a stability of 200 h at 100 mA cm−2. This study offers a novel approach to designing efficient and stable catalysts for water decomposition.    

    

* Fe, N‐Inducing Interfacial Electron Redistribution in NiCo Spinel on Biomass‐Derived Carbon for Bi‐functional Oxygen Conversion  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392160710
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-02-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202319983")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392160710"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392160710"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392160710"))][Get cited by]]

OpenAlex: https://openalex.org/W4392160710 (Open access: False)
    
[[https://openalex.org/A5061810022][Yanyan Liu]], [[https://openalex.org/A5050034119][Limin Zhou]], [[https://openalex.org/A5051323527][Shilin Liu]], [[https://openalex.org/A5091316366][Shu-Qi Li]], [[https://openalex.org/A5041855727][Jingjing Zhou]], [[https://openalex.org/A5022526821][Xin Li]], [[https://openalex.org/A5088081170][Xiangmeng Chen]], [[https://openalex.org/A5025538710][Kang Sun]], [[https://openalex.org/A5036975470][Baojun Li]], [[https://openalex.org/A5013636938][Jianchun Jiang]], [[https://openalex.org/A5014960517][Huan Pang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202319983 
     
Herein, an interfacial electron redistribution is proposed to boost the activity of carbon‐supported spinel NiCo2O4 catalyst toward oxygen conversion via Fe, N‐doping strategy. Fe‐doping into octahedron induces a redistribution of electrons between Co and Ni atoms on NiCo1.8Fe0.2O4@N‐carbon. The increased electron density of Co promotes the coordination of water to Co sites and further dissociation. The generation of proton from water improves the overall activity for the oxygen reduction reaction (ORR). The increased electron density of Ni facilitates the generation of oxygen vacancies. The Ni‐VO‐Fe structure accelerates the deprotonation of *OOH to improve the activity toward oxygen evolution reaction (OER). N‐doping modulates the electron density of carbon to form active sites for the adsorption and protonation of oxygen species. Fir wood‐derived carbon endows catalyst with an integral structure to enable outstanding electrocatalytic performance. The NiCo1.8Fe0.2O4@N‐carbon express high half‐wave potential up to 0.86 V in ORR and low overpotential of 270 mV at 10 mA cm‐2 in OER. The zinc‐air batteries (ZABs) assembled with the as‐prepared catalyst achieve long‐term cycle stability (over 2000 cycles) with peak power density (180 mW cm‐2). Fe, N‐doping strategy drives the catalysis of biomass‐derived carbon‐based catalysts to the highest level for the oxygen conversion in ZABs.    

    

* Fe, N‐Inducing Interfacial Electron Redistribution in NiCo Spinel on Biomass‐Derived Carbon for Bi‐functional Oxygen Conversion  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392164726
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Catalytic Reduction of Nitro Compounds
:PUBLICATION_DATE: 2024-02-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202319983")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392164726"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392164726"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392164726"))][Get cited by]]

OpenAlex: https://openalex.org/W4392164726 (Open access: False)
    
[[https://openalex.org/A5061810022][Yanyan Liu]], [[https://openalex.org/A5050034119][Limin Zhou]], [[https://openalex.org/A5051323527][Shilin Liu]], [[https://openalex.org/A5091316366][Shu-Qi Li]], [[https://openalex.org/A5041855727][Jingjing Zhou]], [[https://openalex.org/A5022526821][Xin Li]], [[https://openalex.org/A5088081170][Xiangmeng Chen]], [[https://openalex.org/A5020145622][Kang Sun]], [[https://openalex.org/A5036975470][Baojun Li]], [[https://openalex.org/A5083684958][Jianchun Jiang]], [[https://openalex.org/A5014960517][Huan Pang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202319983 
     
Herein, an interfacial electron redistribution is proposed to boost the activity of carbon‐supported spinel NiCo2O4 catalyst toward oxygen conversion via Fe, N‐doping strategy. Fe‐doping into octahedron induces a redistribution of electrons between Co and Ni atoms on NiCo1.8Fe0.2O4@N‐carbon. The increased electron density of Co promotes the coordination of water to Co sites and further dissociation. The generation of proton from water improves the overall activity for the oxygen reduction reaction (ORR). The increased electron density of Ni facilitates the generation of oxygen vacancies. The Ni‐VO‐Fe structure accelerates the deprotonation of *OOH to improve the activity toward oxygen evolution reaction (OER). N‐doping modulates the electron density of carbon to form active sites for the adsorption and protonation of oxygen species. Fir wood‐derived carbon endows catalyst with an integral structure to enable outstanding electrocatalytic performance. The NiCo1.8Fe0.2O4@N‐carbon express high half‐wave potential up to 0.86 V in ORR and low overpotential of 270 mV at 10 mA cm‐2 in OER. The zinc‐air batteries (ZABs) assembled with the as‐prepared catalyst achieve long‐term cycle stability (over 2000 cycles) with peak power density (180 mW cm‐2). Fe, N‐doping strategy drives the catalysis of biomass‐derived carbon‐based catalysts to the highest level for the oxygen conversion in ZABs.    

    

* An NiFeSn Oxyhydroxide Electrocatalyst Wet Gel for Highly Efficient Water Electrolysis in Alkaline Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392184869
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nanoen.2024.109428")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392184869"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392184869"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392184869"))][Get cited by]]

OpenAlex: https://openalex.org/W4392184869 (Open access: False)
    
[[https://openalex.org/A5031885225][Taehee Kim]], [[https://openalex.org/A5004680310][Hwapyung Jung]], [[https://openalex.org/A5016637469][Hee Young Choi]], [[https://openalex.org/A5075259600][Donghyeon Kang]], [[https://openalex.org/A5001628148][Wonjun Lee]], [[https://openalex.org/A5065166904][Vinayak G. Parale]], [[https://openalex.org/A5071151758][Umakant M. Patil]], [[https://openalex.org/A5056562445][Younghun Kim]], [[https://openalex.org/A5046632041][J. S. Kim]], [[https://openalex.org/A5005487766][Sang-Hyun Kim]], [[https://openalex.org/A5084473082][Sang Woo Kim]], [[https://openalex.org/A5051853768][Kazuyoshi Kanamori]], [[https://openalex.org/A5015673562][Hyung Ho Park]], Nano Energy. None(None)] 2024. https://doi.org/10.1016/j.nanoen.2024.109428 
     
Since the kinetic barrier posed by the oxygen evolution reaction (OER) is a significant obstacle in water-splitting systems, the creation of effective and inexpensive OER electrocatalysts has received considerable research interest. We report the facile synthesis of an amorphized NiFeSn oxyhydroxide wet gel on Ni foam via a gelation-induced embedding method. Its intrinsic pore structure provided a sufficiently large surface area without the need for a binder. The NiFeSn oxyhydroxide wet-gel electrocatalyst only needed overpotentials of 253, 301, and 346 mV to produce 100, 200, and 300 mA·cm-2, respectively, for the OER and an overpotential value of 198 mV at 50 mA·cm-2 for the hydrogen evolution reaction. Moreover, an exceptionally low voltage of 1.55 V was required for overall water splitting under alkaline conditions. Enhancement of the catalytic properties of the oxyhydroxide by adding Sn was confirmed by using density functional theory calculations. The nanoporous multi-metallic wet gel can be used to create effective low-cost stable self-supporting electrocatalysts with a high current density for enhanced water electrolysis.    

    

* Boosting overall saline water splitting by constructing a strain‐engineered high‐entropy electrocatalyst  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392199493
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cey2.519")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392199493"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392199493"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392199493"))][Get cited by]]

OpenAlex: https://openalex.org/W4392199493 (Open access: True)
    
[[https://openalex.org/A5009410342][Ateer Bao]], [[https://openalex.org/A5074635667][Yaohang Gu]], [[https://openalex.org/A5001753313][Yuxuan Zhang]], [[https://openalex.org/A5042328954][Bowen Zhang]], [[https://openalex.org/A5013655092][Juncheng Wu]], [[https://openalex.org/A5039717240][Bo Niu]], [[https://openalex.org/A5021636467][Xiaoyan Zhang]], [[https://openalex.org/A5042747805][Haijun Pan]], [[https://openalex.org/A5017229059][Xiwei Qi]], Carbon energy. None(None)] 2024. https://doi.org/10.1002/cey2.519  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cey2.519][pdf]])
     
Abstract High‐entropy materials (HEMs), which are newly manufactured compounds that contain five or more metal cations, can be a platform with desired properties, including improved electrocatalytic performance owing to the inherent complexity. Here, a strain engineering methodology is proposed to design transition‐metal‐based HEM by Li manipulation (LiTM) with tunable lattice strain, thus tailoring the electronic structure and boosting electrocatalytic performance. As confirmed by the experiments and calculation results, tensile strain in the LiTM after Li manipulation can optimize the d ‐band center and increase the electrical conductivity. Accordingly, the as‐prepared LiTM‐25 demonstrates optimized oxygen evolution reaction and hydrogen evolution reaction activity in alkaline saline water, requiring ultralow overpotentials of 265 and 42 mV at 10 mA cm −2 , respectively. More strikingly, LiTM‐25 retains 94.6% activity after 80 h of a durability test when assembled as an anion‐exchange membrane water electrolyzer. Finally, in order to show the general efficacy of strain engineering, we incorporate Li into electrocatalysts with higher entropies as well.    

    
