#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Wed Jan 31 00:38:52 2024

Found 47 results from 2024-01-17 to 2024-01-31
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

** Understanding Highly Active and Durable Fe-Doped Co(Oh)2 Catalysts in Alkaline Oxygen Evolution Reaction by in Situ Xanes Studies   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4697142")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390904175"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390904175"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390904175"))][Get cited by]]

OpenAlex: https://openalex.org/W4390904175 (Open access: False)
    
[[https://openalex.org/A5003171150][Du-Hyeon Kim]], [[https://openalex.org/A5067799791][Yong‐Kul Lee]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4697142 
     
The activation and degradation mechanisms of CoFe layered double hydroxide (CoFe-LDH) and Fe-doped Co(OH)2 (Fe-Co(OH)2) have been investigated using in situ X-ray absorption spectroscopy coupled with cyclic voltammetry (CV) in 0-0.9V (vs Hg/HgO). A series of CoFe-LDH samples have been prepared by co-electrodeposition with varying Co/Fe ratios. Fe-doping on Co(OH)2 has been applied using 10 ppm of Fe in 1.0M KOH. Electrochemical impedance spectroscopy (EIS) and CV cycles confirm the degradation of Co(OH)2 and CoFe-LDH due to the irreversible redox of Co(OH)2/CoOOH, and Fe extraction. In contrast, Fe-doped Co(OH)2 shows high activity and stability in the OER. In situ XANES analysis suggests that the Fe-doping allows the Co(OH)2 to remain as CoOOH even under potential fluctuations.    

    

** Site-specific metal-support interaction to switch the activity of Ir single atoms for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-44815-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390904335"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390904335"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390904335"))][Get cited by]]

OpenAlex: https://openalex.org/W4390904335 (Open access: True)
    
[[https://openalex.org/A5013382299][Jie Wei]], [[https://openalex.org/A5044601163][Hengjing Tang]], [[https://openalex.org/A5010634879][Li Sheng]], [[https://openalex.org/A5033862876][Ruyang Wang]], [[https://openalex.org/A5074130931][Minghui Fan]], [[https://openalex.org/A5018898375][Jin Wan]], [[https://openalex.org/A5091026913][Yaoguo Wu]], [[https://openalex.org/A5000151255][Z. D. Zhang]], [[https://openalex.org/A5039567536][Shiming Zhou]], [[https://openalex.org/A5075571728][Jie Zeng]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-44815-0  ([[https://www.nature.com/articles/s41467-024-44815-0.pdf][pdf]])
     
Abstract The metal-support interactions (MSI) could greatly determine the electronic properties of single-atom catalysts, thus affecting the catalytic performance. However, the typical approach to regulating MSI usually suffers from interference of the variation of supports or sacrificing the stability of catalysts. Here, we effectively regulate the site-specific MSI of Ir single atoms anchored on Ni layered double hydroxide through an electrochemical deposition strategy. Cathodic deposition drives Ir atoms to locate at three-fold facial center cubic hollow sites with strong MSI, while anodic deposition drives Ir atoms to deposit onto oxygen vacancy sites with weak MSI. The mass activity and intrinsic activity of Ir single-atom catalysts with strong MSI towards oxygen evolution reaction are 19.5 and 5.2 times that with weak MSI, respectively. Mechanism study reveals that the strong MSI between Ir atoms and the support stimulates the activity of Ir sites by inducing the switch of active sites from Ni sites to Ir sites and optimizes the adsorption strength of intermediates, thereby enhancing the activity.    

    

** Ligands Defect-Induced Structural Self-Reconstruction of Fe–Ni–Co-Hydroxyl Oxides with Crystalline/Amorphous Heterophase from a 2D Metal–Organic Framework for an Efficient Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05314")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390907090"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390907090"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390907090"))][Get cited by]]

OpenAlex: https://openalex.org/W4390907090 (Open access: False)
    
[[https://openalex.org/A5091300678][Hongqi Chu]], [[https://openalex.org/A5044789787][Rujin Li]], [[https://openalex.org/A5000139851][Panpan Feng]], [[https://openalex.org/A5086890929][Dongyan Wang]], [[https://openalex.org/A5046884970][Chunxiang Li]], [[https://openalex.org/A5028136131][Yanling Yu]], [[https://openalex.org/A5048237780][Min Yang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05314 
     
The two-dimensional (2D) Fe–Ni–Co-MOF is synthesized using a simple double ligand strategy at room temperature. The surface reconstruction process transforms it into a crystalline–amorphous heterojunction composed of polycrystalline metal (oxy)hydroxide (MOOH) and amorphous metal oxides/hydroxides with terephthalic acid (TPA) by coordination covalent bonding. In situ Raman spectroscopy discloses the dynamic structure conversion. Density functional theory (DFT), Fourier transform infrared spectroscopy (FTIR), and solid-state nuclear magnetic resonance (SSNMR) reveal the induction of the ligand defects on surface reconstruction and the enhancing effect of TPA on the oxygen evolution reaction (OER) performance through a covalent interaction. The amorphous–crystalline heterojunction of Fe–Ni–CoOOH-TPA has numerous structural defects and high electrical conductivity, resulting in an efficient and stable OER performance with overpotentials of 236 mV at 10 mA cm–2. It has also been observed that the catalyst processes self-healing in an idle state, arising from the reversible conversion of MOOH to M(OH)2. This work reveals the structural and compositional transformation of the 2D Fe–Ni–Co-MOF during surface reconstruction, elucidating the relationship between electrocatalytic reconstruction and water-splitting performance of metal–organic framework (MOF)-based catalysts. It has been proven that appropriate covalent interactions enhance the OER of electrocatalysts.    

    

** Heterojunction Induced Rapid Transformation of Ni3+/Ni2+ Sites Which Mediates Urea Oxidation for Energy‐Efficient Hydrogen Production   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202311766")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390907515"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390907515"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390907515"))][Get cited by]]

OpenAlex: https://openalex.org/W4390907515 (Open access: False)
    
[[https://openalex.org/A5081774843][Peng Guo]], [[https://openalex.org/A5014503942][Shoufu Cao]], [[https://openalex.org/A5048074828][Wenjing Huang]], [[https://openalex.org/A5052850228][Xiaoqing Lü]], [[https://openalex.org/A5084151450][Weizhe Chen]], [[https://openalex.org/A5032946295][Youzi Zhang]], [[https://openalex.org/A5039796972][Yijin Wang]], [[https://openalex.org/A5012799970][Xin Xu]], [[https://openalex.org/A5034805827][Ruiqing Zou]], [[https://openalex.org/A5050597874][Sibi Liu]], [[https://openalex.org/A5003462637][Tongtong Li]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202311766 
     
Abstract Water electrolysis is an environmentally‐friendly strategy for hydrogen production but suffers from significant energy consumption. Substituting urea oxidation reaction (UOR) with lower theoretical voltage for water oxidation reaction adopting nickel‐based electrocatalysts engenders reduced energy consumption for hydrogen production. The main obstacle remains strong interaction between accumulated Ni 3+ and *COO in the conventional Ni 3+ ‐catalyzing pathway. Herein, we develop a novel Ni 3+ /Ni 2+ mediated pathway for UOR via constructing a heterojunction of nickel metaphosphate and nickel telluride (Ni 2 P 4 O 12 /NiTe), which efficiently lowers the energy barrier of UOR avoids the accumulation of Ni 3+ and excessive adsorption of *COO on the electrocatalysts. As a result, Ni 2 P 4 O 12 /NiTe demonstrates an exceptionally low potential of 1.313 V to achieve a current density of 10 mA cm −2 towards efficient urea oxidation reaction while simultaneously showcases an overpotential of merely 24 mV at 10 mA cm −2 for hydrogen evolution reaction. Constructing urea electrolysis electrolyzer using Ni 2 P 4 O 12 /NiTe at both sides attains 100 mA cm −2 at a low cell voltage of 1.475 V along with excellent stability over 500 hours accompanied with nearly 100% Faradic efficiency. This article is protected by copyright. All rights reserved    

    

** Electrochemical Synthesis of Ammonia via Nitrogen Reduction and Oxygen Evolution Reactions—A Comprehensive Review on Electrolyte-Supported Cells   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17020441")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390910364"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390910364"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390910364"))][Get cited by]]

OpenAlex: https://openalex.org/W4390910364 (Open access: True)
    
[[https://openalex.org/A5017146414][Hizkia Manuel Vieri]], [[https://openalex.org/A5084484351][M. W. Kim]], [[https://openalex.org/A5072403902][Arash Badakhsh]], [[https://openalex.org/A5083337587][Sun Hee Choi]], Energies. 17(2)] 2024. https://doi.org/10.3390/en17020441  ([[https://www.mdpi.com/1996-1073/17/2/441/pdf?version=1705409050][pdf]])
     
The application of protonic ceramic electrolysis cells (PCECs) for ammonia (NH3) synthesis has been evaluated over the past 14 years. While nitrogen (N2) is the conventional fuel on the cathode side, various fuels such as methane (CH4), hydrogen (H2), and steam (H2O) have been investigated for the oxygen evolution reaction (OER) on the anode side. Because H2 is predominantly produced through CO2-emitting methane reforming, H2O has been the conventional carbon-free option thus far. Although the potential of utilizing H2O and N2 as fuels is considerable, studies exploring this specific combination remain limited. PCEC fabrication technologies are being developed extensively, thus necessitating a comprehensive review. Several strategies for electrode fabrication, deposition, and electrolyte design are discussed herein. The progress in electrode development for PCECs has also been delineated. Finally, the existing challenges and prospective outlook of PCEC for NH3 synthesis are analyzed and discussed. The most significant finding is the lack of past research involving PCEC with H2O and N2 as fuel configurations and the diversity of nitrogen reduction reaction catalysts. This review indicates that the maximum NH3 synthesis rate is 14 × 10−9 mol cm−2 s−1, and the maximum current density for the OER catalyst is 1.241 A cm−2. Moreover, the pellet electrolyte thickness must be maintained at approximately 0.8–1.5 mm, and the stability of thin-film electrolytes must be improved.    

    

** Oxygen Vacancy Optimization of the Titanium Carbide Mxene Surface for Enhanced Electrochemical Nitrogen Reduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4696673")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390910683"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390910683"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390910683"))][Get cited by]]

OpenAlex: https://openalex.org/W4390910683 (Open access: False)
    
[[https://openalex.org/A5057936702][Leiming Tao]], [[https://openalex.org/A5050145382][Zhenghong Guo]], [[https://openalex.org/A5090251912][Kui Pang]], [[https://openalex.org/A5057489654][Zhi Zhang]], [[https://openalex.org/A5013038112][Chen Wang]], [[https://openalex.org/A5034904172][Liming Huang]], [[https://openalex.org/A5079944667][Guanhua Zhu]], [[https://openalex.org/A5031173998][Linhai Duan]], [[https://openalex.org/A5045985930][Jianjun Yang]], [[https://openalex.org/A5044283271][Xiquan Fu]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4696673 
     
Electrochemical N2 reduction reaction (NRR) provides a hopeful way for sustainable NH3 production. It is the key to realize efficient NRR reaction to optimize the structure and electronic configuration of catalyst materials. Increasing the number of active centers in Ti3C2Tx MXene allows for the development of effective NRR electrocatalysts. Herein, we rationally integrated defect engineering to create oxygen vacancy-rich Ti3C2-Mxene (K-Ti3C2-400) as an efficient NRR catalyst with an NH3 yield of 32.25± 0.8 μg·h-1·mg-1cat. at −0.55 V and a Faradaic efficiency of 12.85% ± 0.26% at −0.45 V versus reversible hydrogen electrode. According to the density functional theory, oxygen vacancies can prevent the hydrogen evolution reaction by delaying H adsorption, thereby activating absorbed N2 and encouraging *N2H synthesis. This research opens up new possibilities for creating MXene-based catalysts with surface reactivity and selectivity for electrochemical N2 fixation.    

    

** Interatomic interaction of 2D crumpled V2O5 nanosheets layered with Ni-MOF as a bifunctional electrocatalyst for overall water splitting and supercapacitor applications   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2023.110348")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390911953"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390911953"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390911953"))][Get cited by]]

OpenAlex: https://openalex.org/W4390911953 (Open access: False)
    
[[https://openalex.org/A5041446513][Muhammad Kashif]], [[https://openalex.org/A5051943320][Sadhasivam Thangarasu]], [[https://openalex.org/A5001779926][N. Murugan]], [[https://openalex.org/A5061257936][Sahil S. Magdum]], [[https://openalex.org/A5005760245][Yoong Ahm Kim]], [[https://openalex.org/A5016350367][Mahaveer D. Kurkuri]], [[https://openalex.org/A5029047892][Tae Hwan Oh]], Journal of Energy Storage. 81(None)] 2024. https://doi.org/10.1016/j.est.2023.110348 
     
Herein, we have synthesized a highly efficient and economical noble metal-free catalyst via a novel combination of V2O5 nanosheets and Ni MOF. The critical points of this study are (i) achieving a 2D layer structured crumpled V2O5 nanosheets without excessive stacking/aggregation using freeze drying method, (ii) decorating Ni-MOF over the crumpled V2O5 nanosheets to attain an excellent homogeneity and (iii) developing a V2O5 based novel and bifunctional electrocatalyst for overall water splitting and supercapacitor applications. Forming a well-interlinked morphological structure accompanies a homogeneous dispersion of Ni MOF over the V2O5 nanosheet. Among the multiple compositions, the NiV4 exhibited superior electrocatalytic oxygen evolution reaction (OER) and hydrogen evolution reaction (HER) performances with an overpotential (η30) of 336 mV and 108 mV, respectively. NiV4 also displayed remarkable stability as confirmed by chronopotentiometry (24 h) and CV (after 5000 cycles). The excellent OER performance is possible due to the interatomic interaction and the heterojunction formation between V2O5 nanosheets and Ni MOF, resulting in the preferential adsorption of ⁎OOH reaction intermediates to Ni active sites. During HER, the interfacial interaction between V2O5 nanosheets and Ni MOF allowed the OH− to adsorb on the V5+ center. Furthermore, the Ni active sites simultaneously accelerated the Volmer step by promoting the H adsorption. The uniform mass transfer routes aid in fast charge transfer, resulting in excellent OER and HER performances. Interestingly, in the 2-electrode system, the NiV4 exhibited an overpotential of 1.81 V at 10 mA cm−2 and excellent durability over 15 h. For supercapacitor applications, the NiV4 exhibits efficient specific capacitance (546 Fg−1 at 1Ag−1). Furthermore, the NiV4 electrode provides significant long-term stability during the supercapacitor application, with the stability being consistent after 10,000 cycles. The NiV4 offers excellent water splitting and supercapacitor performance due to its multifunctional properties and remarkable structural integrity.    

    

** Composition‐Dependent NiS‐Enriched FeNi2S4/ZnCr2O4 Catalyst for Electrochemical Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/slct.202302556")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390914377"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390914377"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390914377"))][Get cited by]]

OpenAlex: https://openalex.org/W4390914377 (Open access: False)
    
[[https://openalex.org/A5015741945][N. Jabena Begum]], [[https://openalex.org/A5022351799][Rathindranath Biswas]], [[https://openalex.org/A5009077939][Ayan Roy]], [[https://openalex.org/A5042201959][Imtiaz Ahmed]], [[https://openalex.org/A5080457147][Pooja Thakur]], [[https://openalex.org/A5022029107][Krishna Kanta Haldar]], ChemistrySelect. 9(3)] 2024. https://doi.org/10.1002/slct.202302556 
     
Abstract Transition metal sulfide and oxide nanomaterials are gaining popularity as catalysts for electrochemical water splitting because of their cost effectiveness, durability, and stability without using noble metals. Our study focuses on a hybrid electrocatalyst, NiS‐enriched FeNi 2 S 4 /ZnCr 2 O 4 , which is synthesized in two steps by sol‐gel followed through thermal decomposition in an aqueous solution by a hydrothermal process. We investigated its potential application in the electrochemical oxygen evolution reaction (OER). Powder X‐ray diffraction and X‐ray photoelectron spectroscopy analyses were used to determine the chemical composition and structure. The results showed that the FeNi 2 S 4 structure has an enriched NiS phase. Additionally, the morphology of the synthesized FeNi 2 S 4 /ZnCr 2 O 4 was revealed by field emission scanning electron microscopy (FE‐SEM). Under alkaline (1 M KOH) conditions, the FeNi 2 S 4 /ZnCr 2 O 4 hybrid nanostructure showed a low overpotential value of 295 mV (Tafel slope, 59 mV dec −1 ) for OER activities due to the synergistic effects of FeNi 2 S 4 and ZnCr 2 O 4 . Furthermore, the hybrid nanostructure demonstrated its long‐term stability and efficiency as an electrocatalyst for OER activities, surpassing previously reported superior electrocatalysts and state‐of‐the‐art materials.    

    

** From Small‐Area Observations to Insight: Surface‐Feature‐Extrapolation of Anodes for Alkaline Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301461")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390916005"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390916005"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390916005"))][Get cited by]]

OpenAlex: https://openalex.org/W4390916005 (Open access: False)
    
[[https://openalex.org/A5016774685][Arvind Kumar Jain]], [[https://openalex.org/A5025930612][Vineetha Vinayakumar]], [[https://openalex.org/A5004899785][André Olean‐Oliveira]], [[https://openalex.org/A5006249717][Christian Marcks]], [[https://openalex.org/A5052683041][Mohit Chatwani]], [[https://openalex.org/A5057402984][Anna K. Mechler]], [[https://openalex.org/A5082583063][Corina Andronescu]], [[https://openalex.org/A5062824606][Doris Segets]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301461 
     
In this study, we developed a statistical framework, named multistage data quantification (MSDQ), to evaluate representative surface characteristics such as surface roughness, surface area, and homogeneity score of cobalt oxide‐based anodes, and contributing to a deeper insight into quality of anode surface. Atomic force microscopy (AFM) was employed to capture the surface morphology of two anodes that have a comparable loading of cobalt oxide but exhibit distinct morphological features. Application of MSDQ exposed notable disparities in surface characteristics across these anodes, underlining the critical importance of MSDQ in precise surface characterization. Specifically, surface roughness, surface area and homogeneity score effectively elucidated the disparities in electrocatalytic activity for the oxygen evolution reaction (OER), as quantified through scanning droplet cell (SDC) measurements. By conducting a systematic comparative analysis, the respective contributions of the extrinsic surface characteristics of the anodes to the intrinsic electrocatalytic material property could be differentiated and quantified. Applications of our findings range from benchmarking of anodes to optimization of anode manufacturing processes.    

    

** Origin of Spin‐State Precise Modulation for Enhanced Oxygen Evolution Activity: Effect of Secondary Coordination Sphere   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202315039")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390916157"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390916157"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390916157"))][Get cited by]]

OpenAlex: https://openalex.org/W4390916157 (Open access: False)
    
[[https://openalex.org/A5066956428][Zhi Fang]], [[https://openalex.org/A5063898322][M. Y. Chai]], [[https://openalex.org/A5028310744][Yunyun Lv]], [[https://openalex.org/A5042724589][Wanting Zhao]], [[https://openalex.org/A5068369655][Xinmei Hou]], [[https://openalex.org/A5087247583][Yanglong Hou]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202315039 
     
Abstract The process of oxygen evolution reaction (OER) is crucial for energy storage and conversion, and the spin electronic structure of catalyst significantly influences its catalytic activity. Precisely regulating the spin electronic structures of metal active centers with intermediate spin (IS) states is challenging but important. This study presents a general method for achieving spin‐state precise modulation by altering the secondary coordination sphere (SCS) in Fe‐substituted LaCo 1‐ x Fe x O 3 perovskites, denoted as Co 6‐ y −[Co]−Fe y ( y = 0–6). The concentration‐dependent SCSs can precisely regulate the spin state of Co 3+ from high‐spin (HS) to IS and low‐spin (LS) state by tuning the Co─O binding energy of primary coordination sphere (PCS) to ≈567 KJ mol −1 . The binding energy demonstrates a strong negative correlation with the spin state of Co 3+ , serving as a quantitative descriptor for precise spin‐state modulation. Furthermore, a universal optimal doping concentration is proposed for generating IS‐state Co 3+ with the best OER activity, ranging from 1/( m +1) to 2/( m +1) in M‐doped ACo 1‐ x M x O y system with the coordination number of m . As a proof‐of‐concept, the LaCo 7/9 Fe 2/9 O 3 with IS Co 3+ exhibits significantly enhanced OER activity, almost six times higher than the control samples (without IS Co 3+ ). These findings provide new insights into spin‐state modulation for effective OER catalysts.    

    

** Material Dynamics of Manganese-Based Oxychlorides for Oxygen Evolution Reaction in Acid   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.chemmater.3c02362")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390918522"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390918522"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390918522"))][Get cited by]]

OpenAlex: https://openalex.org/W4390918522 (Open access: False)
    
[[https://openalex.org/A5014692849][Ruihan Li]], [[https://openalex.org/A5015462149][Dennis Nordlund]], [[https://openalex.org/A5037183181][Linsey C. Seitz]], Chemistry of Materials. None(None)] 2024. https://doi.org/10.1021/acs.chemmater.3c02362 
     
Earth-abundant manganese-based oxides have emerged as promising alternatives to noble-metal-based catalysts for the oxygen evolution reaction (OER) in acidic conditions; however, their inferior activity and stability present critical challenges for the sustainable production of hydrogen via water electrolysis. Moving beyond oxides, heteroanionic materials, which incorporate anions with lower electronegativity than oxygen, have shown potential for improving the OER performance, but a detailed understanding of the underlying mechanisms is lacking. Here, we investigate manganese-based oxychlorides (Mn8O10Cl3 and FeMn7O10Cl3) that exhibit excellent activity and stability for acidic OER to elucidate material property dynamics and correlate them with OER behaviors. Our rigorous electrochemical stability testing reveals that the high operating potential mitigates Mn dissolution over prolonged exposure to the OER conditions. Through a combination of ex situ and in situ surface and bulk-sensitive X-ray spectroscopy analyses, we observe a trade-off between increasing Mn valence and maintaining structural integrity, which results in dynamic bond length changes within the [MnCl6] octahedra during the activation and degradation processes of these oxychloride catalysts. This study provides insights into the fundamental relationships between the chemical, electronic, and geometric properties of the catalysts and their electrocatalytic outcomes.    

    

** Hollow-Structured Cobalt Sulfide Electrocatalyst for Alkaline Oxygen Evolution Reaction: Rational Tuning of Electronic Structure Using Iron and Fluorine Dual-Doping Strategy   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4696257")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390919814"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390919814"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390919814"))][Get cited by]]

OpenAlex: https://openalex.org/W4390919814 (Open access: False)
    
[[https://openalex.org/A5039271899][Hye-Jin Kim]], [[https://openalex.org/A5043789079][Kyeongseok Min]], [[https://openalex.org/A5009094213][Guoqiang Song]], [[https://openalex.org/A5018263246][Junseong Kim]], [[https://openalex.org/A5066805209][Hyung Chul Ham]], [[https://openalex.org/A5048322224][Sung‐Hyeon Baeck]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4696257 
     
Efficiency of water electrolysis critically relies on the development of highly active electrocatalysts for the oxygen evolution reaction (OER). In this study, we propose facile preparation method for hollow-structured nanospheres of Fe and F dual-doped CoS2 (Fe-CoS2-F) as efficient OER electrocatalyst. The uniform hollow and porous structure of the Fe-CoS2-F enhances the specific surface area and increases the number of exposed active sites. Furthermore, Fe and F dual-dopants synergistically adjust the surface electronic structure, thereby promoting the adsorption/desorption of reaction intermediates on the active sites during the alkaline OER process. As a result, the Fe-CoS2-F exhibits outstanding OER activity, demonstrating low overpotential of 298 mV at current density of 10 mA cm−2 and small Tafel slope of 46.0 mV dec−1. Theoretical calculations support these findings by revealing that the incorporation of dual-dopants into the CoS2 structure reduces the overly strong adsorption energy of reaction intermediates in the rate determining step.    

    

** Unveiling the Synergistic Effect of Two-Dimensional Heterostructure Nifep@Feooh as Stable Electrocatalyst for Oxygen Evolution Reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4696269")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390920060"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390920060"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390920060"))][Get cited by]]

OpenAlex: https://openalex.org/W4390920060 (Open access: False)
    
[[https://openalex.org/A5078559315][Zhigang Jiang]], [[https://openalex.org/A5009792649][Mengtian Chen]], [[https://openalex.org/A5039232756][Qinglong Hou]], [[https://openalex.org/A5077625103][Ching-Hua Wang]], [[https://openalex.org/A5083356131][Yang Shen]], [[https://openalex.org/A5020231301][Haizhen Liu]], [[https://openalex.org/A5017195907][Liehuang Zhu]], [[https://openalex.org/A5075183175][Honghui Cheng]], [[https://openalex.org/A5005149210][Kuikui Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4696269 
     
Introducing multiple active sites and constructing heterostructure are efficient strategies to develop high-performance electrocatalysts. Herein, two-dimensional heterostructure NiFeP@FeOOH nanosheets supported by nickel foam are equipped by hydrothermal-phosphorization-electrodeposition process. The synthesis of self-supporting heterostructure NiFeP@FeOOH nanosheets on the NF increased the specific surface region, bimetallic phosphide realized rapid charge transfer, improved the electron transfer rate. The introduction of FeOOH and the construction of heterostructure realized the synergistic effect among the components, and the surface active sites are abundant. In situ Raman spectroscopy showed that the excellent oxygen evolution reaction (OER) performance was due to the reconstruction-induced hydroxyl oxide, which achieved a multi-active site reaction. The NiFeP@FeOOH/NF electrocatalytic activity is significantly improved. The findings indicate that in 1.0 M KOH alkaline solution, NiFeP@FeOOH/NF showed an OER overpotential of 235 mV at 100 mA cm-2, a Tafel slope of 46.46 mV dec-1 and worked stably at 50 mA cm-2 for 80 h. This research proves the importance of constructing heterostructure and introducing FeOOH are of great significance to the study of the properties of OER electrocatalysts.    

    

** Fe2O3/P-doped CoMoO4 electrocatalyst delivers efficient overall water splitting in alkaline media   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.123741")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390920143"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390920143"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390920143"))][Get cited by]]

OpenAlex: https://openalex.org/W4390920143 (Open access: False)
    
[[https://openalex.org/A5058659834][Bowen Wang]], [[https://openalex.org/A5082640049][Xiangxiong Chen]], [[https://openalex.org/A5015677809][Yingjian He]], [[https://openalex.org/A5071375088][Qin Liu]], [[https://openalex.org/A5035441171][Xinxin Zhang]], [[https://openalex.org/A5070400739][Ziyu Luo]], [[https://openalex.org/A5010925967][John Kennedy]], [[https://openalex.org/A5007477535][Junhua Li]], [[https://openalex.org/A5013791293][Dong Qian]], [[https://openalex.org/A5013972114][Jinlong Liu]], [[https://openalex.org/A5044592235][Geoffrey I. N. Waterhouse]], Applied Catalysis B: Environmental. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.123741 
     
Phosphorization of molybdates has been shown to promote hydrogen evolution reaction (HER) activity but is usually detrimental to oxygen evolution reaction (OER) activity, frustrating efforts to create bifunctional HER/OER electrocatalysts. Herein, we show that Fe2O3-modulated P-doped CoMoO4 on nickel foam (Fe-P-CMO) is an excellent bifunctional HER/OER electrocatalyst in alkaline media, with the adverse effect of phosphorization on the OER activity of CoMoO4 being countered via Fe2O3 introduction. An alkaline splitting electrolyser assembled directly using the self-supporting Fe-P-CMO electrode possessed outstanding long-term durability with ultralow cell voltages of 1.48 and 1.59 V required to achieve current densities of 10 and 100 mA cm−2, respectively. Detailed experimental investigations showed that during HER, P-doped CoMoO4 in Fe-P-CMO underwent surface reconstruction with the in-situ formation of Co(OH)2 on the P-CoMoO4 (Co(OH)2/P-CoMoO4). During OER, P-doped CoMoO4 was deeply reconstructed to CoOOH with the complete dissolution of Mo, leading to the in-situ formation of Fe2O3/CoOOH heterojunctions.    

    

** Synergy of Pd2+/S2− Doped TiO2 Supported on 2‐methylimidazolium Functionalized Polypyrrole/Graphene Oxide for Enhanced Nitrogen Electro‐Oxidation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202313155")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390929187"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390929187"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390929187"))][Get cited by]]

OpenAlex: https://openalex.org/W4390929187 (Open access: True)
    
[[https://openalex.org/A5005925090][Hui Mao]], [[https://openalex.org/A5079705305][Yan Sun]], [[https://openalex.org/A5063351008][Huinan Li]], [[https://openalex.org/A5076213027][Shuyao Wu]], [[https://openalex.org/A5031884742][Daliang Liu]], [[https://openalex.org/A5011280888][Hui Li]], [[https://openalex.org/A5043296622][Shuo Li]], [[https://openalex.org/A5069632856][Tianyi Ma]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202313155  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/adma.202313155][pdf]])
     
Abstract The electrosynthesis of nitrate catalyzed by electrochemical nitrogen oxidation reaction (NOR) had been considered as an alternative and sustainable approach to the conventional industrial manufacture, but optimizing the electrocatalytic NOR performance and fabricating the efficient NOR electrocatalysts at the design level still encountered great challenges. Herein, unique Pd 2+ and S 2− doped TiO 2 (Pb/S‐TiO 2 ) nanoparticles had successfully in situ grown on the surface of 2‐methylimidazolium functionalized polypyrrole/graphene oxide (2‐MeIm/PPy/GO), which presented the typical hierarchical micro‐nanostructures, resulting in the excellent electrocatalytic NOR performance with the highest NO 3 − yield of 72.69 µg h −1 mg −1 act. and the maximum FE of 8.92% at 2.04 V (versus RHE) due to the synergistic effect of each component. Due to the doping effect, the appropriate oxygen evolution reaction (OER) activity was achieved by Ti‐site, where OER principally occurred, providing *O during the non‐electrochemical step of NOR, while the electrocatalytic NOR process as the electrochemical conversion of inert N 2 to active *NO intermediates mainly occurred at the Pd‐site. Especially, the sulfate radicals in situ formed on Pb/S‐TiO 2 @2‐MeIm/PPy/GO would further promote nitrogen adsorption and decreased the reaction energy barrier, resulting in the acceleration of NOR. It would provide theoretical and practical experience for the design and preparation of NOR elecctrocatalysts. This article is protected by copyright. All rights reserved    

    

** Electrocatalytic Water Oxidation by Mononuclear Copper Complexes of Bis-amide Ligands with N4 Donor: Experimental and Theoretical Investigation   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.3c03512")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390937001"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390937001"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390937001"))][Get cited by]]

OpenAlex: https://openalex.org/W4390937001 (Open access: False)
    
[[https://openalex.org/A5013979216][Sahanwaj Khan]], [[https://openalex.org/A5063974979][Swaraj Sengupta]], [[https://openalex.org/A5045820945][Md. Adnan Khan]], [[https://openalex.org/A5000088460][Palashuddin Sk]], [[https://openalex.org/A5075918485][Narayan Ch. Jana]], [[https://openalex.org/A5031066693][Subhendu Naskar]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.3c03512 
     
The present work describes electrocatalytic water oxidation of three monomeric copper complexes [CuII(L1)] (1), [CuII(L2)(H2O)] (2), and [CuII(L3)] (3) with bis-amide tetradentate ligands: L1 = N,N'-(1,2-phenylene)dipicolinamide, L2 = N,N'-(4,5-dimethyl-1,2-phenylene)bis(pyrazine-2-carboxamide), L3 = N,N'-(1,2-phenylene)bis(pyrazine-2-carboxamide), for the production of molecular oxygen by the oxidation of water at pH 13.0. Ligands and all complexes have been synthesized and characterized by single crystal XRD, analytical, and spectroscopic techniques. X-ray crystallographic data show that the ligand coordinates to copper in a dianionic fashion through deprotonation of two -NH protons. Cyclic voltammetry study shows a reversible copper-centered redox couple with one ligand-based oxidation event. The electrocatalytic water oxidation occurs at an onset potential of 1.16 (overpotential, η ≈ 697 mV), 1.2 (η ≈ 737 mV), and 1.23 V (η ≈ 767 mV) for 1, 2, and 3 respectively. A systematic variation of the ligand scaffold has been found to display a profound effect on the rate of electrocatalytic oxygen evolution. The results of the theoretical (density functional theory) studies show the stepwise ligand-centered oxidation process and the formation of the O-O bond during water oxidation passes through the water nucleophilic attack for all the copper complexes. At pH = 13, the turnover frequencies have been experimentally obtained as 88, 1462, and 10 s-1 (peak current measurements) for complexes 1, 2, and 3, respectively. Production of oxygen gas during controlled potential electrolysis was detected by gas chromatography.    

    

** Coordination and Architecture Regulation of Electrocatalysts for Sustainable Hydrogen Energy Conversion   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/accountsmr.3c00197")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390937271"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390937271"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390937271"))][Get cited by]]

OpenAlex: https://openalex.org/W4390937271 (Open access: True)
    
[[https://openalex.org/A5004817348][Ming Shi]], [[https://openalex.org/A5015167590][Di Bao]], [[https://openalex.org/A5002436361][Jun‐Min Yan]], [[https://openalex.org/A5030897242][Haixia Zhong]], [[https://openalex.org/A5087936668][Xinbo Zhang]], Accounts of Materials Research. None(None)] 2024. https://doi.org/10.1021/accountsmr.3c00197  ([[https://pubs.acs.org/doi/pdf/10.1021/accountsmr.3c00197][pdf]])
     
ConspectusWith the increasing concerns about the energy and environmental crisis, hydrogen, with the high energy density and cleanliness, has been widely regarded as one ideal energy carrier for adjusting the fossil fuel dependent energy system. In this context, extensive studies are focused on improving the efficiency of the sustainable hydrogen production, storage, and utilization coupled with the renewable energy. And it can be realized in electrolysis cells and fuel cell devices. Several electrochemical reactions are involved, such as water splitting (hydrogen/oxygen evolution: HER/OER) for hydrogen production, electroreduction of nitrogen/nitrate, and carbon dioxide to NH3 and HCOOH (NRR, NO3RR, CO2RR) for hydrogen storage, and oxygen reduction reaction (ORR) for hydrogen utilization. However, the achieved efficiency of the hydrogen energy conversion is still unsatisfactory due to these intrinsically sluggish electrochemical reactions, which has spawned a revival of research interests in developing the electrocatalysts with high activity, selectivity, and durability. Therefore, various strategies have been established to construct effective electrocatalysts, such as coordination or architecture structure regulation, which will determine the intrinsic activity and the efficiency of mass transport, respectively. Besides, combined with the progress of characterization techniques and theoretical studies, insightful understanding of the electrocatalytic sites and reaction mechanism are also investigated, guiding the rational design of future electrocatalysts.In this Account, we summarize our recent efforts in exploring electrocatalysts through the regulation of coordination and construction of porous architecture structures toward the highly efficient electrochemical hydrogen energy conversion. First, an overview of the hydrogen energy conversion process is presented to reveal the advantages and challenges of these reactions. Then, we introduced effective strategies to optimize the coordination and architecture structure to enhance the catalytic performance, such as tailoring the particle size, valence state, and crystal plane, defect engineering, substrate incorporation, structural reconstruction, etc. Additionally, it is also illustrated the insightful mechanism study on the improvement of the catalytic performance via the experimental characterization and theoretical calculations. Finally, a brief outlook is proposed to address the challenges to be overcome for improving the hydrogen conversion efficiency through developing rational catalysts.    

    

** Data driven computational design of stable oxygen evolution catalysts by DFT and machine learning: Promising electrocatalysts   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2023.12.048")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390937419"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390937419"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390937419"))][Get cited by]]

OpenAlex: https://openalex.org/W4390937419 (Open access: False)
    
[[https://openalex.org/A5091408659][Hwanyeol Park]], [[https://openalex.org/A5016517520][Yunseok Kim]], [[https://openalex.org/A5080230233][Sang‐Hoon Choi]], [[https://openalex.org/A5084806533][Ho Jun Kim]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2023.12.048 
     
The revolutionary development of machine learning (ML), data science, and analytics, coupled with its application in material science, stands as a significant milestone of the scientific community over the last decade. Investigating active, stable, and cost-efficient catalysts is crucial for oxygen evolution reaction owing to the significance in a range of electrochemical energy conversion processes. In this work, we have demonstrated an efficient approach of high-throughput screening to find stable transition metal oxides under acid condition for high-performance oxygen evolution reaction (OER) catalysts through density functional theory (DFT) calculation and a machine learning algorithm. A methodology utilizing both the Materials Project database and DFT calculations was introduced to assess the acid stability under specific reaction conditions. Building upon this, OER catalytic activity of acid-stable materials was examined, highlighting potential OER catalysts that meet the required properties. We identified IrO2, Fe(SbO3)2, Co(SbO3)2, Ni(SbO3)2, FeSbO4, Fe(SbO3)4, MoWO6, TiSnO4, CoSbO4, and Ti(WO4)2 as promising catalysts, several of which have already been experimentally discovered for their robust OER performance, while others are novel for experimental exploration, thereby broadening the chemical scope for efficient OER electrocatalysts. Descriptors of the bond length of TM–O and the first ionization energy were used to unveil the OER activity origin. From the calculated results, guidance has been derived to effectively execute advanced high-throughput screenings for the discovery of catalysts with favorable properties. Furthermore, the intrinsic correlation between catalytic performance and various atomic and structural factors was elucidated using the ML algorithm. Through these approaches, we not only streamline the choice of the promising electrocatalysts but also offer insights for the design of varied catalyst models and the discovery of superior catalysts.    

    

** An asymmetric electrode matching reversible kinetics of oxygen reaction for a rechargeable Zn-air battery   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.148868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390937605"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390937605"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390937605"))][Get cited by]]

OpenAlex: https://openalex.org/W4390937605 (Open access: False)
    
[[https://openalex.org/A5084510530][Shuxin Li]], [[https://openalex.org/A5050852420][Han Zhang]], [[https://openalex.org/A5065939635][Lin Wu]], [[https://openalex.org/A5043744321][Hongwei Zhao]], [[https://openalex.org/A5000771235][Lin Tao]], [[https://openalex.org/A5065813999][Lixiang Li]], [[https://openalex.org/A5022726425][Chengguo Sun]], [[https://openalex.org/A5061399332][Dongying Ju]], [[https://openalex.org/A5054286336][Baigang An]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.148868 
     
The development of zinc-air batteries (ZABs) is hindered by the sluggish kinetics of the oxygen reduction reaction (ORR) and the oxygen evolution reaction (OER) which occur in the complex interfaces between gaseous oxygen, liquid electrolyte and solid catalyst. Designing a rational interface that aligns with the kinetics of these multi-phase reactions is of utmost importance. Herein, an asymmetric cathode (Asy-electrode) has been designed and fabricated that the carbon nanotubes arrays (CNAs) encapsulating Co nanoparticles grown on carbon cloth is used as the aerophilic side (AI-side) to match and catalyze the ORR kinetics, the other side that deposition of NiFe layered double hydroxide (NiFe-LDH) on the CNAs plays as aerophobic side (AO-side) to accelerate the OER kinetics. The Asy-electrode effectively balances the adsorption and desorption of O2 and OH–, and promotes the efficient transport of gaseous and liquid reactants and products. Therefore, the efficiency of ORR and OER onto the corresponding catalytic sites of Co/CNAs and NiFe-LDH/CNAs are significantly enhanced. Consequently, the ZAB employing the asymmetric cathode can acquire a remarkable higher power density (236.26 mW cm−2) and an excellent long-term cycling stability (over 1920 cycles at 10 mA cm−2) due to the enhanced kinetic and the improved reversibility of the charge–discharge reaction on the cathode benefiting from the aerophilic/hydrophilic interfacial construction on each side of electrode. The present study could explore a route to design the catalysts from the view of matching the multi-phase reaction characteristics.    

    

** Nife2o4 in Mose2 Exhibits Bifunctional Water Oxidation and Oxygen Reduction (Oer and Orr) Catalytic Reactions for Energy Applications   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4698366")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390938954"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390938954"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390938954"))][Get cited by]]

OpenAlex: https://openalex.org/W4390938954 (Open access: False)
    
[[https://openalex.org/A5059659171][Merin Mary Sebastian]], [[https://openalex.org/A5003489789][Ditty Dixon]], [[https://openalex.org/A5089963600][T. Daniel Thangadurai]], [[https://openalex.org/A5037699843][Alex Schechter]], [[https://openalex.org/A5064125049][Nandakumar Kalarikkal]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4698366 
     
Abstract: Highly active bifunctional oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) catalysts made of nickel ferrite (NiFe2O4) supported on MoSe2 nanosheets have been rigorously studied in our present work. The OER activity evaluation was conducted in an alkaline solution for all catalysts. The MoSe2@NiFe2O4 (1:1) catalyst, which had shown superior activity compared to other catalysts, delivered 10 mA cm-2 at a potential of 1.50 V vs. RHE, similar to the state-of-the-art commercial IrO2. The ORR activity of the MoSe2@NiFe2O4 electrocatalyst exhibited an ORR onset potential of 0.83 V vs. RHE. We report MoSe2@NiFe2O4 bifunctional catalyst for noticeable activity in ORR and OER, with a potential difference (ΔE) of 0.84 V. In the accelerated test, after 5000 potential cycles, the MoSe2@NiFe2O4 (1:1) catalyst had about 86% retention of the ORR diffusion-limiting current density. The OER depicts a loss of around 70.6% after 2000 cycles, which is significantly lower than the state-of-the-art IrO2, deactivated after 2000 cycles. Harnessing the excellent bifunctionality of our catalyst in a Zn–air battery depicts 300 cycles with a loss of only 55 % in charging capacity and 5% in discharge capacity after 200 cycles at a current density of 20 mA cm-2. Considering the excellent bi-functional activity, the MoSe2@NiFe2O4 hetero-structured composite is an exceptional candidate for energy storage applications.    

    

** Surface reconstruction of La0.6Sr0.4Co0.8Ni0.2O3- perovskite nanofibers for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.01.211")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390942237"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390942237"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390942237"))][Get cited by]]

OpenAlex: https://openalex.org/W4390942237 (Open access: False)
    
[[https://openalex.org/A5087438347][Yusong Niu]], [[https://openalex.org/A5014609476][Xin Chang]], [[https://openalex.org/A5052582378][Mingyi Zhang]], [[https://openalex.org/A5031140913][Jingbo Mu]], Ceramics International. None(None)] 2024. https://doi.org/10.1016/j.ceramint.2024.01.211 
     
Perovskites have become promising alternatives to precious metal-catalyzed oxygen evolution reaction (OER). Herein, we report the synthesis of several perovskite nanofibers, specifically La0.6Sr0.4CoxNi1-xO3-δ (LSCN), and investigate their electrocatalytic water oxidation activity in alkaline electrolytes. La0.6Sr0.4Co0.8Ni0.2O3-δ (LSCN-0.8) is selected and immersed in an aqueous NaBH4 solution for 1 h for surface reconstruction. The perovskite nanofibers' electrocatalytic OER activity and stability are rigorously evaluated using a standard three-electrode system. Results reveal that even a slight Co substitution for Ni content within the LSCN perovskite structure has a notable impact on electrocatalytic activity. Moreover, LSCN-0.8 exhibits an overpotential of 363 mV at 20 mA cm−2 in 1 M KOH. However, significant improvement is observed after the surface reconstruction process. The optimized LSCN-0.8 (now called LSCN-2) displays the lowest OER overpotential (320 mV) under the same conditions. Furthermore, the LSCN-2 nanostructure demonstrates exceptional electrode stability, as evidenced by only a slight decrease in electrocatalytic performance during 5000 cycles of linear sweep voltammetry.    

    

** Alkaline-based aqueous sodium-ion batteries for large-scale energy storage   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-44855-6")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390943969"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390943969"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390943969"))][Get cited by]]

OpenAlex: https://openalex.org/W4390943969 (Open access: True)
    
[[https://openalex.org/A5053272104][Wei Han]], [[https://openalex.org/A5067503371][Junnan Hao]], [[https://openalex.org/A5007497108][Yunling Jiang]], [[https://openalex.org/A5012120241][Yiran Jiao]], [[https://openalex.org/A5019056615][Jiahao Liu]], [[https://openalex.org/A5091773218][Xin Xu]], [[https://openalex.org/A5066863992][Kenneth Davey]], [[https://openalex.org/A5054651739][Chunsheng Wang]], [[https://openalex.org/A5032628543][Shi‐Zhang Qiao]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-44855-6  ([[https://www.nature.com/articles/s41467-024-44855-6.pdf][pdf]])
     
Aqueous sodium-ion batteries are practically promising for large-scale energy storage, however energy density and lifespan are limited by water decomposition. Current methods to boost water stability include, expensive fluorine-containing salts to create a solid electrolyte interface and addition of potentially-flammable co-solvents to the electrolyte to reduce water activity. However, these methods significantly increase costs and safety risks. Shifting electrolytes from near neutrality to alkalinity can suppress hydrogen evolution while also initiating oxygen evolution and cathode dissolution. Here, we present an alkaline-type aqueous sodium-ion batteries with Mn-based Prussian blue analogue cathode that exhibits a lifespan of 13,000 cycles at 10 C and high energy density of 88.9 Wh kg-1 at 0.5 C. This is achieved by building a nickel/carbon layer to induce a H3O+-rich local environment near the cathode surface, thereby suppressing oxygen evolution. Concurrently Ni atoms are in-situ embedded into the cathode to boost the durability of batteries.    

    

** Exploration of metal‐free 2D electrocatalysts toward the oxygen electroreduction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/exp.20220174")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390944231"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390944231"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390944231"))][Get cited by]]

OpenAlex: https://openalex.org/W4390944231 (Open access: True)
    
[[https://openalex.org/A5066781523][Joyjit Kundu]], [[https://openalex.org/A5059563152][Taehyun Kwon]], [[https://openalex.org/A5009755251][Kwangyeol Lee]], [[https://openalex.org/A5026994173][Sang‐Il Choi]], Exploration. None(None)] 2024. https://doi.org/10.1002/exp.20220174  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/EXP.20220174][pdf]])
     
Abstract The advancement of economical and readily available electrocatalysts for the oxygen reduction reaction (ORR) holds paramount importance in the advancement of fuel cells and metal‐air batteries. Recently, 2D non‐metallic materials have obtained substantial attention as viable alternatives for ORR catalysts due to their manifold advantages, encompassing low cost, ample availability, substantial surface‐to‐volume ratio, high conductivity, exceptional durability, and competitive activity. The augmented ORR performances observed in metal‐free 2D materials typically arise from heteroatom doping, defects, or the formation of heterostructures. Here, the authors delve into the realm of electrocatalysts for the ORR, pivoting around metal‐free 2D materials. Initially, the merits of metal‐free 2D materials are explored and the reaction mechanism of the ORR is dissected. Subsequently, a comprehensive survey of diverse metal‐free 2D materials is presented, tracing their evolutionary journey from fundamental concepts to pragmatic applications in the context of ORR. Substantial importance is given on the exploration of various strategies for enhancing metal‐free 2D materials and assessing their impact on inherent material performance, including electronic properties. Finally, the challenges and future prospects that lie ahead for metal‐free 2D materials are underscored, as they aspire to serve as efficient ORR electrocatalysts.    

    

** Catalytic Water Electrolysis by Co-Cu-W Mixed Metal Oxides: In-sights from Operando X-ray Absorption Spectroscopy   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2023-wn28g-v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390945203"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390945203"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390945203"))][Get cited by]]

OpenAlex: https://openalex.org/W4390945203 (Open access: True)
    
[[https://openalex.org/A5084476486][Nikita Gupta]], [[https://openalex.org/A5043189039][Carlo U. Segre]], [[https://openalex.org/A5080329256][Carsten Streb]], [[https://openalex.org/A5088121808][Dandan Gao]], [[https://openalex.org/A5035954011][Ksenija D. Glusac]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2023-wn28g-v2  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65a5aab566c1381729870ab2/original/catalytic-water-electrolysis-by-co-cu-w-mixed-metal-oxides-in-sights-from-operando-x-ray-absorption-spectroscopy.pdf][pdf]])
     
Mixed Metal oxides (MMOs) are a promising class of electrocatalysts for the oxygen evolution reaction (OER) and hydrogen evolu-tion reaction (HER). Despite their importance for sustainable energy schemes, our understanding of relevant reaction pathways, catalytically active sites and synergistic effects is rather limited. Here, we applied synchrotron-based X-ray absorption spectrosco-py (XAS) to explore the evolution of an amorphous Co-Cu-W MMO electrocatalyst, shown previously to be an efficient bifunc-tional OER and HER catalyst for water splitting. Ex-situ K- and L-edge XAS measurements provided structural environments and the oxidation state of the metals involved, revealing Co2+ (octahedral), Cu+/2+ (tetrahedral / square-planar) and W6+ (octahedral) cen-ters. Operando XAS investigations, including X-ray absorption near-edge structure (XANES) and extended X-ray absorption fine structure (EXAFS), elucidated the dynamic structural transformations of Co, Cu, and W metal centers during OER or HER. The ex-perimental results indicate that Co3+ and Cu0 are the active catalytic sites involved in OER and HER, respectively, while Cu2+ and W6+ play crucial roles as structure stabilizers, suggesting strong synergistic interactions within the Co-Cu-W MMO system. These results, combined with the Tafel slope analysis, revealed that the bottleneck intermediate during OER is Co3+ hydroperoxide, whose formation is accompanied by changes in the Cu-O bond lengths, pointing to a possible synergistic effect between Co and Cu ions. Our study reveals important structural effects taking place during MMO-driven OER/HER electrocatalysis and provides es-sential experimental insights into the complex catalytic mechanism of emerging noble metal-free MMO electrocatalysts for full water splitting.    

    

** Interfacial engineering to construct an IrOx/WO3 hetero-structured catalyst for efficient acidic OER catalysis   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3nj04468h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390946110"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390946110"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390946110"))][Get cited by]]

OpenAlex: https://openalex.org/W4390946110 (Open access: False)
    
[[https://openalex.org/A5017056133][Zeyu Guan]], [[https://openalex.org/A5082980005][Yuxiao Weng]], [[https://openalex.org/A5079415041][Jiankun Li]], [[https://openalex.org/A5013355381][Shiyi Li]], [[https://openalex.org/A5091764376][Keyu Wang]], [[https://openalex.org/A5044754090][Linfeng Lei]], [[https://openalex.org/A5088263932][Yixing Wang]], [[https://openalex.org/A5045661046][Linzhou Zhuang]], [[https://openalex.org/A5081669439][Zhiheng Li]], New Journal of Chemistry. None(None)] 2024. https://doi.org/10.1039/d3nj04468h 
     
A heterogeneous interface structure between WO 3 and IrO x nanoclusters can be formed for robust acidic oxygen evolution catalysis, where the coordination environment of IrO x is regulated as WO 3 can provide electrons while IrO x accepts electrons.    

    

** Advancing oxygen evolution electrocatalysis with human-machine intelligence   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.checat.2023.100868")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391043168"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391043168"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391043168"))][Get cited by]]

OpenAlex: https://openalex.org/W4391043168 (Open access: True)
    
[[https://openalex.org/A5083865054][Liping Liu]], [[https://openalex.org/A5047424183][Siwen Wang]], [[https://openalex.org/A5013986686][Chen Ling]], [[https://openalex.org/A5040429065][Hongliang Xin]], Chem Catalysis. 4(1)] 2024. https://doi.org/10.1016/j.checat.2023.100868 
     
In this article, Hongliang Xin (associate professor at Virginia Tech), Chen Ling (senior principal research scientist at Toyota), and their colleagues discuss the critical challenges in developing high-performance electrocatalysts for the oxygen evolution reaction (OER), particularly by emphasizing the role of artificial intelligence (AI) in materials exploration and discovery. They highlight the necessity of a collaborative human-machine intelligence approach to overcome the complexities of OER catalysis and accelerate the advancement of sustainable energy solutions.    

    

** Insights on MOF-derived metal–carbon nanostructures for oxygen evolution   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3dt04263d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391225155"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391225155"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391225155"))][Get cited by]]

OpenAlex: https://openalex.org/W4391225155 (Open access: False)
    
[[https://openalex.org/A5084914364][Junliang Chen]], [[https://openalex.org/A5054473752][Jinjie Qian]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d3dt04263d 
     
This article focuses on elucidating the fabrication and design of metal-organic framework derived metal-carbon nanostructures for oxygen evolution. It is categorized into three following topics: MOF selection, metal introduction and carbon structure.    

    

** Enhanced catalytic activity of ZnWO4 by nickel-doping in oxygen evolution reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mssp.2024.108151")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391197664"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391197664"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391197664"))][Get cited by]]

OpenAlex: https://openalex.org/W4391197664 (Open access: False)
    
[[https://openalex.org/A5087592842][Meng Li]], [[https://openalex.org/A5086054627][Deijun Xiong]], [[https://openalex.org/A5036224962][Jinxing Wang]], [[https://openalex.org/A5082373186][Xiaoyang Dong]], [[https://openalex.org/A5069325690][Peiyang Zhang]], Materials Science in Semiconductor Processing. 173(None)] 2024. https://doi.org/10.1016/j.mssp.2024.108151 
     
The development of efficient and low-cost metal materials is indispensable in clean energy technology. Metal tungstates have previously been reported as catalysts for oxygen evolution reactions (OER). However, ZnWO4 alone does not exhibit significant catalytic activity for OER, it requires 330 mV to drive the reaction at 10 mA cm−2. To address this issue, a self-supporting electrode mixed with tungstate is synthesized by a hydrothermal method. Notably, the Ni-doped ZnWO4 self-supporting material demonstrates improved OER catalytic activity. Specifically, when comparing ZnWO4 to ZnNiWO4, it exhibits a reduced Tafel slope by 190 mV·dec−1, resulting in an overpotential of only 110 mV at 10 mA cm−2, with long-term stability for at least 20 h. Furthermore, the d-band center of ZnNiWO4 is modeled using Materials Studio and simulated through projected density of states (PDOS) calculations. These calculations reveal that the presence of Ni activates the metal ion as an OER active site with strong orbital overlap with the reaction intermediate. This adjustment in the electronic structure of the Ni–Zn metal active site during the oxygen evolution reaction alters the adsorption energy. Consequently, doping of Ni enhances the metal's ability to adsorb *OOH radical, shifting the d-band center of ZnNiWO4 further away from the Fermi level, and facilitates rapid oxygen release.    

    

** Dynamic Promotion of the Oxygen Evolution Reaction via Programmable Metal Oxides   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-gs6zn")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391172933"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391172933"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391172933"))][Get cited by]]

OpenAlex: https://openalex.org/W4391172933 (Open access: True)
    
[[https://openalex.org/A5030610409][Sallye R. Gathmann]], [[https://openalex.org/A5065773454][Christopher J. Bartel]], [[https://openalex.org/A5029991019][Lars C. Grabow]], [[https://openalex.org/A5089122189][Omar Abdel‐Rahman]], [[https://openalex.org/A5071975512][C. Daniel Frisbie]], [[https://openalex.org/A5003718847][Paul J. Dauenhauer]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-gs6zn  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65af381d66c13817290d5404/original/dynamic-promotion-of-the-oxygen-evolution-reaction-via-programmable-metal-oxides.pdf][pdf]])
     
Hydrogen gas is a promising renewable energy storage medium when produced via water electrolysis, but this process is limited by the sluggish kinetics of the anodic oxygen evolution reaction (OER). Herein, we used a microkinetic model to investigate promoting the OER using programmable oxide catalysts (i.e., forced catalyst dynamics). We found that programmable catalysts could increase current density at a fixed overpotential (100X to 600X over static rates) or reduce the overpotential required to reach a fixed current density of 10 mA/cm^2 (45 – 140% reduction vs. static). In our kinetic parameterization, the key parameters controlling the quality of the catalytic ratchet were the O*-to-OOH* and O*-to-OH* activation barriers. Our findings indicate that programmable catalysts may be a viable strategy for accelerating the OER or enabling lower-overpotential operation, but a more accurate kinetic parameterization is required for precise predictions of performance, ratchet quality, and resulting energy efficiency.    

    

** Fabrication of hexagonal Cu2O nanocrystals on CNTs for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpcs.2023.111853")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391179968"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391179968"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391179968"))][Get cited by]]

OpenAlex: https://openalex.org/W4391179968 (Open access: False)
    
[[https://openalex.org/A5083753418][Salma Aman]], [[https://openalex.org/A5018207831][Meznah M. Alanazi]], [[https://openalex.org/A5008098859][Shaimaa A. M. Abdelmohsen]], [[https://openalex.org/A5088716481][Saeed D. Alahmari]], [[https://openalex.org/A5078102681][Abdullah G. Al‐Sehemi]], [[https://openalex.org/A5014861084][Muhammad Suleman Waheed]], [[https://openalex.org/A5051797797][A.M.A. Henaish]], [[https://openalex.org/A5084172156][Zubair Ahmad]], [[https://openalex.org/A5001974005][Hafiz Muhammad Tahir Farid]], Journal of Physics and Chemistry of Solids. None(None)] 2024. https://doi.org/10.1016/j.jpcs.2023.111853 
     
Electrocatalytic water (H2O) splitting relies heavily on the rational formation of most effective, long-lasting catalysts that should be cheaper and earth abundant. Therefore, an effective electrocatalyst is the need of the hour that may effectively pursue both electrocatalytic OER and HER. This study paves the way for the straightforward preparation of conductive polymer tailored metal oxide nanocomposite Cu2O/CNTs by a facile hydrothermal approach to be employed as overall water splitting electrocatalyst. The techniques comprising SEM, XRD, EDX and the BET test were employed to characterize the synthesized Cu2O/CNTs electrocatalyst. The generated Cu2O/CNTs electrocatalysts exhibited a Tafel value of 39 mV/dec, an overpotential of 267 mV@10 mA/cm2, and stability of OER activity that lasted for at least 70 hours. The electrocatalytic results show that the combination of Cu2O and CNTs has a synergistic impact to reduce the overpotential value. In an effort to pinpoint the rate determining processes for OER, the voltage of OER is connected to the electrolyte pH and exhibits a non-proton concerted approach. The above designed nanocomposite is quite promising for modern hydrogen production systems due to their quick electron transfer mechanism, remarkable durability, and good activity for OER.    

    

** Spinel-type high-entropy oxide nanotubes for efficient oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.colsurfa.2024.133315")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391177777"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391177777"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391177777"))][Get cited by]]

OpenAlex: https://openalex.org/W4391177777 (Open access: False)
    
[[https://openalex.org/A5046042839][Yanbin Zhu]], [[https://openalex.org/A5070686219][Qing Xiang]], [[https://openalex.org/A5050156870][Guo Le]], [[https://openalex.org/A5060213367][Shuanglong Lu]], [[https://openalex.org/A5067758457][Fang Duan]], [[https://openalex.org/A5036927789][Mingliang Du]], [[https://openalex.org/A5014327956][Han Zhu]], Colloids and Surfaces A: Physicochemical and Engineering Aspects. None(None)] 2024. https://doi.org/10.1016/j.colsurfa.2024.133315 
     
Oxygen evolution reaction (OER) involved 4-electron transfers is generally considered as the bottleneck for electrocatalytic water splitting. High-entropy oxides (HEO) show promising potential for OER due to their flexible structures and tunable compositions. Herein, we report a facile strategy to synthesize spinel-type (FeCoNiMnCr)3O4 HEO nanotubes (NTs) with unique hollow structures by combining electrospinning process and calcination treatment. The (FeCoNiMnCr)3O4 HEO NTs prepared at 400 °C exhibit the low overpotential of 353 mV at 50 mA cm-2 and small Tafel slope of 55.6 mV dec-1 in 1 M KOH electrolyte. The three-dimensional (3D) nanofiber-based architecture ensure the superior stability, as evidenced by the stable current density under continuous OER process for more than 60 h. Meanwhile, the hollow structure provides abundant exposed active sites, which could significantly improve the OER activity. This work provides new design of low-cost and high-efficient HEO with ensemble active sites for OER.    

    

** Strategic Design and Insights into Lanthanum and Strontium Perovskite Oxides for Oxygen Reduction and Oxygen Evolution Reactions   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202308443")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391142464"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391142464"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391142464"))][Get cited by]]

OpenAlex: https://openalex.org/W4391142464 (Open access: False)
    
[[https://openalex.org/A5050236680][Sagar Ingavale]], [[https://openalex.org/A5036345289][Mohan Gopalakrishnan]], [[https://openalex.org/A5092896607][Carolin Mercy Enoch]], [[https://openalex.org/A5067676218][Chanon Pornrungroj]], [[https://openalex.org/A5000448228][Meena Rittiruam]], [[https://openalex.org/A5036226683][Supareak Praserthdam]], [[https://openalex.org/A5007823738][Anongnat Somwangthanaroj]], [[https://openalex.org/A5093770957][Kasadit Nootong]], [[https://openalex.org/A5074004594][Rojana Pornprasertsuk]], [[https://openalex.org/A5081163390][Soorathep Kheawhom]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202308443 
     
Abstract Perovskite oxides exhibit bifunctional activity for both oxygen reduction (ORR) and oxygen evolution reactions (OER), making them prime candidates for energy conversion in applications like fuel cells and metal‐air batteries. Their intrinsic catalytic prowess, combined with low‐cost, abundance, and diversity, positions them as compelling alternatives to noble metal and metal oxides catalysts. This review encapsulates the nuances of perovskite oxide structures and synthesis techniques, providing insight into pivotal active sites that underscore their bifunctional behavior. The focus centers on the breakthroughs surrounding lanthanum (La) and strontium (Sr)‐based perovskite oxides, specifically their roles in zinc‐air batteries (ZABs). An introduction to the mechanisms of ORR and OER is provided. Moreover, the light is shed on strategies and determinants central to optimizing the bifunctional performance of La and Sr‐based perovskite oxides.    

    

** Carbon nanotubes immobilized copper(salen) nanocomposite for electrochemical oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.56042/ijc.v63i1.2312")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391174987"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391174987"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391174987"))][Get cited by]]

OpenAlex: https://openalex.org/W4391174987 (Open access: True)
    
, Indian Journal of Chemistry. 63(1)] 2024. https://doi.org/10.56042/ijc.v63i1.2312  ([[https://or.niscpr.res.in/index.php/IJC/article/download/2312/2438][pdf]])
     
An efficient oxygen evolution reaction (OER) electrocatalysts are widely required in the realm of water electrolysis and rechargeable metal-air batteries. This work describes an easy and simple method for the synthesis of copper salen (Cu(Salen))-functionalized multiwalled carbon nanotubes (MWCNTs) nanocomposite materials (Cu(Salen)/MWCNTs). It was used for OER in the basic medium (0.1 M KOH). The resulting nanocomposite, Cu(Salen)/MWCNTs, was studied using spectroscopic and microscopic techniques. For example, Fourier transform infrared (FT-IR), UV-visible spectroscopy, powder X-ray diffraction (p-XRD), scanning electron microscopy (SEM), and energy dispersive X-ray analysis (EDAX). The electrochemical characterization of prepared Cu(Salen)/MWCNTs nanocomposite based modified glassy carbon (GC) electrodes (GC/Cu(Salen)/MWCNTs) and their application towards OER were performed using an electrochemical method. The Tafel slope of nanocomposite material is 159.6 mv/dec in 0.1 M KOH solution, indicating that GC/Cu(Salen)/MWCNTs could be a promising and cost-effective electrode material for the OER. This study demonstrates a novel way for creating an active nanocomposite catalyst for OER in alkaline media.    

    

** NiCo2O4/MXene hybrid as an efficient bifunctional electrocatalyst for oxygen evolution and reduction reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301250")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391296391"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391296391"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391296391"))][Get cited by]]

OpenAlex: https://openalex.org/W4391296391 (Open access: False)
    
[[https://openalex.org/A5016038695][Ashalatha Vazhayil]], [[https://openalex.org/A5015987837][Vazhayal Linsha]], [[https://openalex.org/A5086819981][Shyamli Ashok C]], [[https://openalex.org/A5087024992][Jasmine Thomas]], [[https://openalex.org/A5053127989][Nygil Thomas]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301250 
     
For the advancement of energy conversion and storage technologies, bifunctional electrocatalysts are crucial for efficiently driving both the oxygen evolution (OER) and reduction reactions (ORR). Cobalt‐based spinel oxides are a class of promising bifunctional electrocatalysts. However their low electrical conductivity and stability may hinder further improvement. A novel composite material composed of NiCo2O4(NCO) nanoparticles integrated with emerging two dimensional MXene nanosheets (NCO/MXene) was developed. The successful integration of NCO with MXene brings about a number of attractive structural features. This includes synergistic effects between NCO and MXene, highly accessible surface areas, complete exposure of numerous active sites, and excellent electronic conductivity, all of which collectively contribute to the desirability of composite material for OER and ORR. The synthesized NCO/MXene composite showed extraordinary OER electrocatalytic activity with a lower overpotential of 360 mV at a current density of 10 mA/cm2, and a small Tafel slope of 64.63 mV/dec compared to NCO, MXene and NCO+MXene (physically mixed). Additionally, it displays a superior ORR limiting current density (‐4 mA/cm2). In particular, it exhibited highest onset potential and half wave potential of 0.92 V and 0.72 V vs. RHE, respectively, for the ORR in alkaline media    

    

** Copper oxide nanofibers obtained by solution blow spinning as catalysts for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ceramint.2024.01.213")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390965940"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390965940"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390965940"))][Get cited by]]

OpenAlex: https://openalex.org/W4390965940 (Open access: False)
    
[[https://openalex.org/A5012056564][Alessandra Patrícia de Araújo Dantas]], [[https://openalex.org/A5001528670][Rafael A. Raimundo]], [[https://openalex.org/A5011364392][Pedro de Lima Neto]], [[https://openalex.org/A5013176757][Caio M. S. Lopes]], [[https://openalex.org/A5075400591][Jakeline R.D. Santos]], [[https://openalex.org/A5090398034][Francisco J.A. Loureiro]], [[https://openalex.org/A5029685103][Tatiany Barata Pereira]], [[https://openalex.org/A5088882865][Marco A. Morales]], [[https://openalex.org/A5061360133][Eliton S. Medeiros]], [[https://openalex.org/A5069774051][Daniel A. Macedo]], Ceramics International. None(None)] 2024. https://doi.org/10.1016/j.ceramint.2024.01.213 
     
In this work, we report copper oxide nanofibers (CuO – N) synthesized by Solution Blow Spinning (SBS) for oxygen evolution reaction (OER), and their comparison with a control sample based on a commercial powder (CuO – C). Both materials were characterized by various techniques, including X-ray diffraction (XRD), magnetometry, scanning electron microscopy (SEM), and spectroscopy (Fourier transform infrared (FT-IR), Raman and X-ray photoelectron (XPS)) to confirm the purity, and microstructural and surface chemical properties. Subsequently, the performance of copper oxide catalysts in a 1.0 M KOH solution was investigated. Copper oxide with nanofiber morphology (CuO – N) exhibited a small overpotential of 385 mV @ 10 mA cm−2 and a Tafel coefficient of only 76 mV dec−1, i.e., fast kinetics for water splitting, a result that is modulated by oxygen vacancies (O2/O1 = 0.83). The oxygen vacancies are due to the presence of Cu1+ in the lattice. The analyses of the magnetization measurements at 5 K suggest a larger amount of Cu1+ in sample CuO – N. Therefore, this work sheds light on how to design low-cost nanofibrous catalysts based on abundant transition metals in the earth's crust by SBS, an economical and scalable technique, which is promising for energy applications.    

    

** Constructing highly efficient bifunctional catalysts for oxygen reduction and oxygen evolution by modifying MXene with transition metal   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.01.089")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391063505"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391063505"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391063505"))][Get cited by]]

OpenAlex: https://openalex.org/W4391063505 (Open access: False)
    
[[https://openalex.org/A5061630253][Dai Yu]], [[https://openalex.org/A5047850201][Xiuyun Zhao]], [[https://openalex.org/A5016833284][Desheng Zheng]], [[https://openalex.org/A5059700536][Qingrui Zhao]], [[https://openalex.org/A5082664273][Jing Feng]], [[https://openalex.org/A5019670440][Yingjie Feng]], [[https://openalex.org/A5063446819][Xingbo Ge]], [[https://openalex.org/A5024977426][Xin Chen]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.01.089 
     
Exploring highly active electrocatalysts for oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) has become a growing interest in recent years. Herein, an efficient pathway for designing MXene-based ORR/OER catalysts is proposed. It involves introducing non-noble metals into Vo (vacancy site), H1 and H2 (the hollow sites on top of C and the metal atom, respectively) sites on M2CO2 surfaces, named TM-VO/H1/H2-M2CO2 (TM = Fe, Co, Ni, M = V, Nb, Ta). Among these recombination catalysts, Co-H1-V2CO2 and Ni-H1-V2CO2 exhibit the most promising ORR catalytic activities, with low overpotential values of 0.35 and 0.37 V, respectively. Similarly, Fe-H1-V2CO2, Co-VO-Nb2CO2, and Ni-H2-Nb2CO2 possess low OER overpotential values of 0.29, 0.39, and 0.44 V, respectively, suggesting they have enormous potential as effective catalysts for OER. Notably, Co-H2-Ta2CO2 possesses the lowest potential gap value of 0.53 V, demonstrating it has an extraordinary bifunctional catalytic activity. The excellent catalytic performance of these recombination catalysts can be elucidated through an electronic structure analysis, which primarily relies on the electron-donating capacity and synergistic effects between transition metals and sub-metals. These results provide theoretical guidance for designing new ORR and OER catalysts using 2D MXene materials.    

    

** Exploring the role of iron in Fe5Ni4S8 toward oxygen evolution through modulation of electronic orbital occupancy   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.01.028")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391152145"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391152145"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391152145"))][Get cited by]]

OpenAlex: https://openalex.org/W4391152145 (Open access: False)
    
[[https://openalex.org/A5070671117][Zhengyan Du]], [[https://openalex.org/A5069619264][Zeshuo Meng]], [[https://openalex.org/A5035280619][H. Sun]], [[https://openalex.org/A5085794085][Yifan Li]], [[https://openalex.org/A5018421780][Chao Jiang]], [[https://openalex.org/A5037742951][Yaxin Li]], [[https://openalex.org/A5016312685][Xiaoying Hu]], [[https://openalex.org/A5063995082][Yi Cui]], [[https://openalex.org/A5020651129][Shansheng Yu]], [[https://openalex.org/A5037428389][Hongwei Tian]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.01.028 
     
Ni-Fe-based catalysts are considered to be among the most active catalysts for the oxygen evolution reaction (OER) under alkaline conditions, with Fe playing a crucial role. However, Fe leaching occurs during the reaction due to thermodynamic instability, which has resulted in conflicting reports within the literature regarding its role. To clarify this point, we propose a strategy consisting of modulating the electronic orbital occupancy to suppress the extensive loss of Fe atoms during the OER process. Theoretical calculations, in-situ X-ray photoelectron spectroscopy, molecular dynamics simulations, and a series of characterization showed that the stable presence of Fe not only accelerates the electron transfer process but also optimizes the reaction barriers of the oxygen evolution intermediates, promoting the phase transition of Fe5Ni4S8 to highly active catalytic species. The modulated Fe5Ni4S8-based pre-catalysts exhibit improved OER activity and long-term durability. This study provides a novel perspective for understanding the role of Fe in the OER process.    

    

** Efficient Oxygen Evolution Reaction by Ru(II) Polypyridyl Complex based AIEgen   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3qi02380j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987133"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987133"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987133"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987133 (Open access: False)
    
[[https://openalex.org/A5071842308][Snehadrinarayan Khatua]], [[https://openalex.org/A5058986428][Monosh Rabha]], [[https://openalex.org/A5047379472][Sreenivasan Nagappan]], [[https://openalex.org/A5029602773][Bhaskar Sen]], [[https://openalex.org/A5031222788][Khanindram Baruah]], [[https://openalex.org/A5067628877][Subrata Kundu]], No host. None(None)] 2024. https://doi.org/10.1039/d3qi02380j 
     
Ruthenium polypyridyl complexes are known for their excellent photophysical properties and rich electrochemical behavior. Thus, developing complexes with multifunctional behavior showing potential applications in multiple fields is of great importance....    

    

** Efficient oxygen evolution using conductive cobalt-based metal-organic framework   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131044")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391143814"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391143814"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391143814"))][Get cited by]]

OpenAlex: https://openalex.org/W4391143814 (Open access: False)
    
[[https://openalex.org/A5061145215][Munzir H. Suliman]], [[https://openalex.org/A5025288698][Lolwah Tawfiq Alfuhaid]], [[https://openalex.org/A5042532738][Mohd Yusuf Khan]], [[https://openalex.org/A5090138718][Muhammad Usman]], [[https://openalex.org/A5088210851][Aasif Helal]], Fuel. 363(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131044 
     
No abstract    

    

** Laser assisted oxygen vacancy engineering on Fe doped CoO nanoparticles for oxygen evolution at large current density   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.143841")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391037653"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391037653"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391037653"))][Get cited by]]

OpenAlex: https://openalex.org/W4391037653 (Open access: False)
    
[[https://openalex.org/A5005245760][Min Zhu]], [[https://openalex.org/A5072946813][Zong‐Qiang Sheng]], [[https://openalex.org/A5019261932][Zhifen Fu]], [[https://openalex.org/A5075847376][Yang Li]], [[https://openalex.org/A5001017073][Juan Gao]], [[https://openalex.org/A5089966579][Chao Zhang]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.143841 
     
Exploring cost-effective non-noble metal-based catalysts with high activity and stability is of great significance for energy conversion and storage involving oxygen evolution reaction (OER). Here, we employed a laser irradiation technique to synthesis Fe doped CoO nanoparticles with ultrafine size (≈ 5.4 nm) and abundant oxygen vacancies (Fe-Ov-CoO). The ultrafine size of Fe-Ov-CoO nanoparticles provides more active sites to be exposed. Fe doping and oxygen vacancy promote the intrinsic activity and electron transfer rates of Fe-Ov-CoO, giving rise to high activity and stability catalyst for OER. Fe-Ov-CoO delivers a large current density of 1000 mA cm−2 at an overpotential of 548 mV, which is much better than commercial RuO2. Moreover, Fe-Ov-CoO presents a remarkable long-term stability with negligible degeneration at a high current density of 500 mA cm−2 for 120 h. This work provides a new route to develop OER electrocatalyst with high activity and stability.    

    

** Three-dimensional ordered macroporous design of heterogeneous cobalt-iron phosphides as oxygen evolution electrocatalyst   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/1361-6528/ad21a5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391127015"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391127015"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391127015"))][Get cited by]]

OpenAlex: https://openalex.org/W4391127015 (Open access: False)
    
[[https://openalex.org/A5010184929][Suqing Zhao]], [[https://openalex.org/A5057639371][Weijin Cao]], [[https://openalex.org/A5030429211][Lu Lu]], [[https://openalex.org/A5084750748][Zhaoyang Tan]], [[https://openalex.org/A5007948614][Yanji Wang]], [[https://openalex.org/A5045477027][Lanlan Wu]], [[https://openalex.org/A5083687798][Jingde Li]], Nanotechnology. None(None)] 2024. https://doi.org/10.1088/1361-6528/ad21a5 
     
Abstract Oxygen evolution reaction (OER) plays a key role in electrochemical conversion, which needs efficient and economical electrocatalyst to boost its kinetics for large-scale application. Herein, a bimetallic CoP/FeP2 heterostructure with a three-dimensional ordered macroporous structure (3DOM-CoP/FeP2) was synthesized as an OER catalyst to demonstrate a heterogeneous engineering induction strategy. By adjusting the electron distribution and producing a lot of active sites, the heterogeneous interface enhances catalytic performance. High specific surface area is provided by the 3DOM structure. Additionally, at the solid-gas-electrolyte threephase interface, the electrocatalytic reaction exhibits good mass transfer. In-situ Raman spectroscopy characterization revealed that FeOOH and CoOOH reconstructed from CoP/FeP2 were the true OER active sites. Consequently, the 3DOM-CoP/FeP2 demonstrates superior OER activity with a low overpotentials of 300/420 mV at 10/100 mA cm–2 and meritorious OER durability. It also reveals promising performance as the overall water splitting anode.&#xD;    

    

** Origin of Anomalous Activities during Oxygen Evolution Reaction in Cubic CoNiCuFe Prussian Blue Analogue   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-bfvb8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391168303"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391168303"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391168303"))][Get cited by]]

OpenAlex: https://openalex.org/W4391168303 (Open access: True)
    
[[https://openalex.org/A5039487681][Yu Han]], [[https://openalex.org/A5038741154][Youngnam Kang]], [[https://openalex.org/A5017298534][Jie Wei]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-bfvb8  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65afb1ba9138d231618da1ab/original/origin-of-anomalous-activities-during-oxygen-evolution-reaction-in-cubic-co-ni-cu-fe-prussian-blue-analogue.pdf][pdf]])
     
Amorphous oxide catalysts typically exhibit excellent activity toward oxygen evolution reaction (OER) due to a large number of undercoordinated sites or lattice defects, but also generally suffering from low stability and difficulty in characterizing the structure. Herein, we report a well-crystallized cubic CoNiCuFe prussian blue analogue (PBA) catalyst with anomalous activities in electrocatalyzing OER when compared with its amorphized oxide. In situ Raman spectroscopy revealed a much more abundant MOOH active phase accumulated on the cubic CoNiCuFe-PBA surface than that on the amorphous CoNiCuFe-oxide surface. Further characterizations demonstrate that more high-valence metal (i.e. Co3+, Ni3+) sites are available on the cubic CoNiCuFe-PBA surface at the initial state, which is suggested to be more susceptible to redox-active surface hydroxylation and serve as the origin of active sites during OER process. The maintained cubic framework structure as well as the lower valence of Fe could contribute to considerably better stability. Such findings would open up a new door to future highly active and stable catalyst designs.    

    

** Benchmarking Stability of Iridium Oxide in Acidic Media under Oxygen Evolution Conditions: A Review: Part II   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1595/205651324x17055018154113")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4390987310"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4390987310"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4390987310"))][Get cited by]]

OpenAlex: https://openalex.org/W4390987310 (Open access: True)
    
[[https://openalex.org/A5028610474][James Murawski]], [[https://openalex.org/A5004372016][Søren B. Scott]], [[https://openalex.org/A5027366818][Reshma R. Rao]], [[https://openalex.org/A5040293372][Katie Rigg]], [[https://openalex.org/A5030674093][Christopher Mark Zalitis]], [[https://openalex.org/A5015505628][James Stevens]], [[https://openalex.org/A5007586547][Jonathan Sharman]], [[https://openalex.org/A5055131883][Gareth Hinds]], [[https://openalex.org/A5039064548][Ifan E. L. Stephens]], Johnson Matthey Technology Review. None(None)] 2024. https://doi.org/10.1595/205651324x17055018154113 
     
Part I (1) introduced state-of-the-art proton exchange membrane (PEM) electrolysers with iridium-based catalysts for oxygen evolution at the anode in green hydrogen applications. Aqueous model systems and full cell testing were discussed along with proton exchange membrane water electrolyser (PEMWE) catalyst degradation mechanisms, types of iridium oxide, mechanisms of iridium dissolution and stability studies. In Part II, we highlight considerations and best practices for the investigation of activity and stability of oxygen evolution catalysts via short term testing.    

    

** Halogen-Modified Iron-Based Metal–Organic Frameworks for Remarkably Improved Electrocatalytic Oxygen Evolution   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.3c06800")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391157099"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391157099"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391157099"))][Get cited by]]

OpenAlex: https://openalex.org/W4391157099 (Open access: False)
    
[[https://openalex.org/A5088936095][Qianglong Qi]], [[https://openalex.org/A5010776860][Yue Zhang]], [[https://openalex.org/A5064403506][Chengxu Zhang]], [[https://openalex.org/A5081844561][Feng Li]], [[https://openalex.org/A5008888331][Richeng Liu]], [[https://openalex.org/A5027149538][Jue Hu]], The Journal of Physical Chemistry C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.3c06800 
     
Iron-based metal–organic frameworks (MOFs) have shown potential as catalysts for the electrocatalysis oxygen evolution reaction (OER). Despite numerous methods being employed to enhance the OER performance of MOFs, the influence of halogen-containing linkers on the electronic structure of iron-based MOF catalysts remains unexplored. In this study, a series of Fe-based MOFs (denoted as MOF-R, where R = H, Cl, or Br) with comparable structures are synthesized by changing the organic linkers coordinated with the Fe metal active center, with the aim of investigating the influence of halogen-containing linkers on the OER activity. Significantly, MOF-Br exhibited superior OER activity compared to MOF-Cl and MOF-H. Density functional theory calculations reveal that the tuning of halogen groups on organic linkers can modulate the electronic structure of the metal active sites and effectively regulate the adsorption behavior of key intermediates near the optimal d-band center, leading to the enhancement of electroactivity. Notably, the bromine-substituted MOF-Br catalyst displayed remarkable intrinsic OER activity, including a low overpotential of 251.2 mV at a current density of 10 mA cm–2 and a low Tafel slope of 44.5 mV dec–1, surpassing the halogen-unsubstituted MOF-H (262.6 mV and 63.4 mV dec–1) and commercial IrO2 (335.3 mV and 98.6 mV dec–1). Moreover, the high turnover frequency at an overpotential of 300 mV was measured to be 0.537 s–1, which is 30 times greater than that of the commercial IrO2 catalyst (0.018 s–1). This research offers a potential strategy for designing MOF electrocatalysts with superior OER activity, laying a solid foundation for the rational design and synthesis of excellent OER electrocatalysts in the future.    

    

** Recycling spent LiNi1-x-yCoxMnyO2 cathodes to efficient catalysts for oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3gc04503j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391112539"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391112539"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391112539"))][Get cited by]]

OpenAlex: https://openalex.org/W4391112539 (Open access: False)
    
[[https://openalex.org/A5038689848][Mingfei Chen]], [[https://openalex.org/A5053008395][Yixin Zhou]], [[https://openalex.org/A5040027560][Wang Li]], [[https://openalex.org/A5017138446][Ganglin Xue]], [[https://openalex.org/A5082529409][Jili Guo]], [[https://openalex.org/A5086161254][Yaping Wang]], Green Chemistry. None(None)] 2024. https://doi.org/10.1039/d3gc04503j 
     
The wide application of lithium-ion batteries (LIBs) for electric vehicles forebodes the future decommissioning tide of spent LIBs. Therefore, the recycling of spent LIBs has garnered significant attention, primarily due...    

    

** Synergistic CuCoS-PANI Materials for Binder-Free Electrodes in Asymmetric Supercapacitors and Oxygen Evolution   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3na01066j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391260063"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391260063"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391260063"))][Get cited by]]

OpenAlex: https://openalex.org/W4391260063 (Open access: True)
    
[[https://openalex.org/A5024005569][Hiba A. Hasan]], [[https://openalex.org/A5067573568][Amir Muhammad Afzal]], [[https://openalex.org/A5084761641][Hussein Alrobei]], [[https://openalex.org/A5093796837][Fareeha Riasat]], [[https://openalex.org/A5034087002][Amir Muhammad Afzal]], [[https://openalex.org/A5057428775][Ali Saeedi]], [[https://openalex.org/A5093796838][Hasan B. Albargib]], [[https://openalex.org/A5003070785][A. Rehmat]], Nanoscale advances. None(None)] 2024. https://doi.org/10.1039/d3na01066j  ([[https://pubs.rsc.org/en/content/articlepdf/2024/na/d3na01066j][pdf]])
     
In advanced electronics, supercapacitors (SCs) have received a lot of attention. Nevertheless, it has been shown that different electrode designs that are based on metal sulfides are prone to oxidation,...    

    

** Tungsten-doped cobalt-iron bimetallic phosphide nanoparticles for enhanced oxygen evolution reaction   
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jtice.2024.105356")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391057421"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391057421"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391057421"))][Get cited by]]

OpenAlex: https://openalex.org/W4391057421 (Open access: False)
    
[[https://openalex.org/A5029733101][Yaoxia Yang]], [[https://openalex.org/A5076729121][Dangxia Wang]], [[https://openalex.org/A5078314562][Xingwei Guo]], [[https://openalex.org/A5072659920][Fengyao Guo]], [[https://openalex.org/A5067107304][Zhang Lan]], [[https://openalex.org/A5032918016][Dongfei Sun]], [[https://openalex.org/A5081104591][Xiaozhong Zhou]], [[https://openalex.org/A5031098226][Zhiwang Yang]], [[https://openalex.org/A5026631111][Ziqiang Lei]], Journal of the Taiwan Institute of Chemical Engineers. 156(None)] 2024. https://doi.org/10.1016/j.jtice.2024.105356 
     
No abstract    

    
