#+TITLE: water splitting
Description: water splitting papers
Created on Tue Feb 27 00:43:03 2024

Found 36 results from 2024-02-20 to 2024-02-27
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Correction: Spent tea leaves templated synthesis of highly active and durable cobalt-based trifunctional versatile electrocatalysts for hydrogen and oxygen evolution and oxygen reduction reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391926812
:TOPICS: Nanomaterials with Enzyme-Like Characteristics, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4gc90017k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391926812"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391926812"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391926812"))][Get cited by]]

OpenAlex: https://openalex.org/W4391926812 (Open access: True)
    
[[https://openalex.org/A5063363228][Ariful Ahsan]], [[https://openalex.org/A5033283090][Muhammad A. Imam]], [[https://openalex.org/A5052938805][Alain R. Puente Santiago]], [[https://openalex.org/A5074843219][Alejandro Rodrı́guez]], [[https://openalex.org/A5062849452][Bonifacio Alvarado-Tenorio]], [[https://openalex.org/A5009293092][Ricardo A. Bernal]], [[https://openalex.org/A5078421218][Rafael Luque]], [[https://openalex.org/A5007869284][Juan C. Noveron]], Green Chemistry. None(None)] 2024. https://doi.org/10.1039/d4gc90017k  ([[https://pubs.rsc.org/en/content/articlepdf/2024/gc/d4gc90017k][pdf]])
     
Correction for ‘Spent tea leaves templated synthesis of highly active and durable cobalt-based trifunctional versatile electrocatalysts for hydrogen and oxygen evolution and oxygen reduction reactions’ by Md Ariful Ahsan et al. , Green Chem. , 2020, 22 , 6967–6980, https://doi.org/10.1039/D0GC02155E.    

    

* Transpassive Metal Dissolution vs. Oxygen Evolution Reaction: Implication for Alloy Stability and Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391944172
:TOPICS: Atom Probe Tomography Research
:PUBLICATION_DATE: 2024-02-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202317058")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391944172"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391944172"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391944172"))][Get cited by]]

OpenAlex: https://openalex.org/W4391944172 (Open access: False)
    
[[https://openalex.org/A5076601076][Annica Wetzel]], [[https://openalex.org/A5093888344][Daniel Morell]], [[https://openalex.org/A5017993519][Marcus von der Au]], [[https://openalex.org/A5038064548][Günther Wittstock]], [[https://openalex.org/A5072476528][Özlem Ozcan]], [[https://openalex.org/A5044822731][Julia Witt]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202317058 
     
Multi‐principal element alloys (MPEAs) are gaining interest in corrosion and electrocatalysis research due to their electrochemical stability across a broad pH range and the design flexibility they offer. Using the equimolar CrCoNi alloy, we observe significant metal dissolution in a corrosive electrolyte (0.1 M NaCl, pH 2) concurrently with the oxygen evolution reaction (OER) in the transpassive region despite the absence of hysteresis in polarization curves or other obvious corrosion indicators. We present a characterization scheme to delineate the contribution of OER and alloy dissolution, using scanning electrochemical microscopy (SECM) for OER‐onset detection, and quantitative chemical analysis with inductively coupled‐mass spectrometry (ICP‐MS) and ultraviolet visible light (UV‐Vis) spectroscopy to elucidate metal dissolution processes. In‐situ electrochemical atomic force microscopy (EC‐AFM) revealed that the transpassive metal dissolution on CrCoNi is dominated by intergranular corrosion. These results have significant implications for the stability of MPEAs in corrosion systems, emphasizing the necessity of analytically determining metal ions released from MPEA electrodes into the electrolyte when evaluating Faradaic efficiencies of OER catalysts. The release of transition metal ions not only reduces the Faradaic efficiency of electrolyzers but may also cause poisoning and degradation of membranes in electrochemical reactors.    

    

* Alkali Containing Layered Metal Oxides as Catalysts for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391948002
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202300761")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391948002"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391948002"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391948002"))][Get cited by]]

OpenAlex: https://openalex.org/W4391948002 (Open access: True)
    
[[https://openalex.org/A5076436151][Mario Falsaperna]], [[https://openalex.org/A5007560583][Rosa Arrigo]], [[https://openalex.org/A5071095075][Frank Marken]], [[https://openalex.org/A5044793501][Simon J. Freakley]], ChemElectroChem. None(None)] 2024. https://doi.org/10.1002/celc.202300761 
     
Abstract Improving the efficiency of the oxygen evolution reaction (OER) is essential to realise energy systems based on water electrolysis. Many catalysts have been developed for the OER to date, with iridium‐based oxides being the most promising due to their relative stability towards corrosion in acidic electrolytes under oxidising potentials. In recent years, examples of catalysts adopting layered structures have been shown to have promising characteristics such as higher conductivity and higher electrochemically active surface area compared to highly crystalline metal oxides. Furthermore, such materials possess additional tuneable properties such as interlayer spacing, identity and concentration of the interlayer species, edge and interlayer active sites, and higher active surface area. Recent attention has focused on mono‐ and polymetallic lithium‐containing layered materials, where the presence of interlayer lithium cations, in situ delithiation processes and combinations of transition metal oxides result in enhanced catalytic properties towards OER. This review aims to provide a summary of the recent developments of such layered materials, in which lithium or other alkali metal ions occupy interlayer sites in oxides.    

    

* Doping Ru on FeNi LDH/FeⅡ/Ⅲ-MOF heterogeneous core-shell structure for efficient oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391948180
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dt00008k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391948180"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391948180"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391948180"))][Get cited by]]

OpenAlex: https://openalex.org/W4391948180 (Open access: False)
    
[[https://openalex.org/A5038834523][Yijia Cao]], [[https://openalex.org/A5057814323][Yan Wen]], [[https://openalex.org/A5041756956][Yanrong Liu]], [[https://openalex.org/A5086361638][Mengya Cao]], [[https://openalex.org/A5057603195][Bao Li]], [[https://openalex.org/A5036911553][Qing Shen]], [[https://openalex.org/A5003733633][Wen Gu]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d4dt00008k 
     
Noble metal based catalysts as RuO2 and IrO2 have been widely used in the catalysis of OER. Because of the high price and poor stability, it is urgent to develop...    

    

* Glassy State Hydroxide Materials for Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391952436
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202312168")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391952436"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391952436"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391952436"))][Get cited by]]

OpenAlex: https://openalex.org/W4391952436 (Open access: False)
    
[[https://openalex.org/A5037677450][Jing Wang]], [[https://openalex.org/A5013419645][Jingyu Chen]], [[https://openalex.org/A5003605384][Jian Zhang]], [[https://openalex.org/A5007627021][Qiang Gao]], [[https://openalex.org/A5043105845][Bo Han]], [[https://openalex.org/A5032667823][Ruimin Sun]], [[https://openalex.org/A5084756664][Chenggang Zhou]], [[https://openalex.org/A5091556593][Zhao Cai]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202312168 
     
Abstract Hydroxides are the archetype of layered crystals with metal‐oxygen (M‐O) octahedron units, which have been widely investigated as oxygen evolution reaction (OER) catalysts. However, the better crystallinity of hydroxide materials, the more perfect octahedral symmetry and atomic ordering, resulting in the less exposed metal sites and limited electrocatalytic activity. Herein, a glassy state hydroxide material featuring with short‐range order and long‐range disorder structure is developed to achieve high intrinsic activity for OER. Specifically, a rapid freezing point precipitation method is utilized to fabricate amorphous multi‐component hydroxide. Owing to the freezing‐point crystallization environment and chaotic M‐O (M = Ni/Fe/Co/Mn/Cr etc.) structures, the as‐fabricated NiFeCoMnCr hydroxide exhibit a highly‐disordered glassy structure, as‐confirmed by X‐ray/electron diffraction, enthalpic response, and pair distribution function analysis. The as‐achieved glassy‐state hydroxide materials display a low OER overpotential of 269 mV at 20 mA cm −2 with a small Tafel slope of 33.3 mV dec −1 , outperform the benchmark noble‐metal RuO 2 catalyst (341 mV, 84.9 mV dec −1 ) . Operando Raman and density functional theory studies reveal that the glassy state hydroxide converted into disordered active oxyhydroxide phase with optimized oxygen intermediates adsorption under low OER overpotentials, thus boosting the intrinsic electrocatalytic activity.    

    

* From Synthesis to Mechanisms: In‐Depth Exploration of the Dual‐Atom Catalytic Mechanisms Toward Oxygen Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391952929
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202311434")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391952929"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391952929"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391952929"))][Get cited by]]

OpenAlex: https://openalex.org/W4391952929 (Open access: False)
    
[[https://openalex.org/A5032200326][Lei Lei]], [[https://openalex.org/A5026097984][Xinghua Guo]], [[https://openalex.org/A5089619087][Xu Han]], [[https://openalex.org/A5056012629][Fei Ling]], [[https://openalex.org/A5005863427][Xiangmin Guo]], [[https://openalex.org/A5084430513][D D Wang]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202311434 
     
Abstract Dual‐atom catalysts (DACs) hold a higher metal atom loading and provide greater flexibility in terms of the structural characteristics of their active sites in comparison to SACs. Consequently, DACs hold great promise for achieving improved catalytic performance. This article aims to provide a focused overview of the latest advancements in DACs, covering their synthesis and mechanisms in reversible oxygen electrocatalysis, which plays a key role in sustainable energy conversion and storage technologies. The discussion starts by highlighting the structures of DACs and the differences in diatomic coordination induced by various substrates. Subsequently, the state‐of‐the‐art fabrication strategies of DACs for oxygen electrocatalysis are discussed from several different perspectives. It particularly highlights the challenges of increasing the diatomic loading capacity. More importantly, the main focus of this overview is to investigate the correlation between the configuration and activity in DACs in order to gain a deeper understanding of their active roles in oxygen electrocatalysis. This will be achieved through density functional theory (DFT) calculations and sophisticated in situ characterization technologies. The aim is to provide guidelines for optimizing and upgrading DACs in oxygen electrocatalysis. Additionally, the overview discusses the current challenges and future prospects in this rapidly evolving area of research. This article is protected by copyright. All rights reserved    

    

* A fingerprint-like supramolecular-assembled Ag3PO4/polydopamine/g-C3N4 heterojunction nanocomposite for enhanced solar-driven oxygen evolution in vivo  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391953305
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.02.087")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391953305"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391953305"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391953305"))][Get cited by]]

OpenAlex: https://openalex.org/W4391953305 (Open access: False)
    
[[https://openalex.org/A5019386186][Shihong Shen]], [[https://openalex.org/A5015770587][Qian Gao]], [[https://openalex.org/A5048921157][Zhenpeng Hu]], [[https://openalex.org/A5043935829][Daidi Fan]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.02.087 
     
Biocompatible photocatalytic water-splitting systems are promising for tissue self-oxygenation. Herein, a structure–function dual biomimetic fingerprint-like silver phosphate/polydopamine/graphitic carbon nitride (Ag3PO4/PDA/g-C3N4) heterojunction nanocomposite is proposed for enhanced solar-driven oxygen (O2) evolution in vivo in situ. Briefly, a porous nitrogen-defected g-C3N4 nanovoile (CN) is synthesized as the base. Dopamine molecules are controllably inserted into the CN interlayer, forming PDA spacers (4.28 nm) through self-polymerization-induced supramolecular-assembly. Ag3PO4 nanoparticles are then in situ deposited to create Ag3PO4/PDA/CN. The fingerprint-like structure of PDA/CN enlarges the layer spacing, thereby accelerating mass transfer and increasing reaction sites. The PDA spacer roles as excellent light harvester, electronic-ionic conductor, and redox pair through conformational changes, resulting in tailored electronic band structure, optimized carrier behavior, and reduced electrochemical impedance. In physiological conditions, Ag3PO4/PDA/CN exhibits O2 evolution rate of 45.35 μmol⋅g−1⋅h−1, 9-fold of bulk g-C3N4. The biocompatibility and in vivo oxygen supply effectiveness for biomedical applications have been verified in animal models.    

    

* Enhanced Electrocatalytic Oxygen Evolution Reaction by Photothermal Effect and Its Induced Micro-electric Field  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391955701
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nr00170b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391955701"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391955701"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391955701"))][Get cited by]]

OpenAlex: https://openalex.org/W4391955701 (Open access: False)
    
[[https://openalex.org/A5058002676][Feng Ding]], [[https://openalex.org/A5023418189][Qian Zou]], [[https://openalex.org/A5093960993][Li Junzhe]], [[https://openalex.org/A5075233676][Xianrui Yuan]], [[https://openalex.org/A5037920786][Xun Cui]], [[https://openalex.org/A5061945778][Chuan Jing]], [[https://openalex.org/A5028101986][Shuman Tao]], [[https://openalex.org/A5088522668][Xiujuan Wei]], [[https://openalex.org/A5069817927][Huichao He]], [[https://openalex.org/A5047377429][Yingze Song]], Nanoscale. None(None)] 2024. https://doi.org/10.1039/d4nr00170b 
     
Promoting better thermodynamics and kinetics of electrocatalysts is the key to achieving efficient electrocatalytic oxygen evolution reaction (OER). Utilizing the photothermal effect and micro-electric field of electrocatalyst is a promising...    

    

* Fabrication of Highly Efficient FeNi-based Electrodes using Thermal Plasma Spray for Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391957745
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104091")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391957745"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391957745"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391957745"))][Get cited by]]

OpenAlex: https://openalex.org/W4391957745 (Open access: False)
    
[[https://openalex.org/A5073057852][B. Narayanan]], [[https://openalex.org/A5066726222][Lakshmanan Kumaresan]], [[https://openalex.org/A5003611696][G. Shanmugavelayutham]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104091 
     
No abstract    

    

* Challenges and progress in oxygen evolution reaction catalyst development for seawater electrolysis for hydrogen production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391958854
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ra08648h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391958854"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391958854"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391958854"))][Get cited by]]

OpenAlex: https://openalex.org/W4391958854 (Open access: True)
    
[[https://openalex.org/A5089450078][Joel C. Corbin]], [[https://openalex.org/A5002185829][M. Jones]], [[https://openalex.org/A5042026897][Cheng Liu]], [[https://openalex.org/A5041409819][Adeline Loh]], [[https://openalex.org/A5045309022][Zhenyu Zhang]], [[https://openalex.org/A5088619248][Yan Zhu]], [[https://openalex.org/A5020406154][Xiaohong Li]], RSC Advances. 14(9)] 2024. https://doi.org/10.1039/d3ra08648h 
     
Modification techniques to oxygen evolution reaction (OER) electrocatalysts for direct seawater electrolysis (DSWE) to mitigate chloride corrosion from seawater.    

    

* Silver Nanowires Cascaded Layered Double Hydroxides Nanocages with Enhanced Directional Electron Transport for Efficient Electrocatalytic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391958988
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202309859")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391958988"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391958988"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391958988"))][Get cited by]]

OpenAlex: https://openalex.org/W4391958988 (Open access: False)
    
[[https://openalex.org/A5011581422][Jinchen Fan]], [[https://openalex.org/A5067934401][Jin Ma]], [[https://openalex.org/A5089424513][Liuliu Zhu]], [[https://openalex.org/A5016212362][Hui Wang]], [[https://openalex.org/A5082506540][Weiju Hao]], [[https://openalex.org/A5029104177][Yulin Min]], [[https://openalex.org/A5025388218][Qingyuan Bi]], [[https://openalex.org/A5013446276][Guisheng Li]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202309859 
     
Abstract Designing and fabricating highly efficient oxygen evolution reaction (OER) electrocatalytic materials for water splitting is a promising and practical approach to green and sustainable low‐carbon energy systems. Herein, a facile in situ growth self‐template strategy by using ZIF‐67 as a consumable layered double hydroxides (LDHs) template and silver nanowires (AgNWs) as 1D conductive cascaded substrate to controllably synthesize the target AgNWs@CoFe‐LDH composites with unique hollow shell sugar gourd‐like structure and enhanced directional electron transport effect is reported. The AgNWs exhibit the key functions of the close connection of CoFe‐LDH nanocages and the support of the directional electron transport effect in the composite catalyst inducing electrons directionally moving from CoFe‐LDH to AgNWs. Meanwhile, the CoFe‐LDH nanocages with ultrathin nanosheets and hollow structural properties show abundant active sites for electrocatalytic oxygen generation. The versatile AgNWs@CoFe‐LDH catalyst with optimized components, enhanced directional electron transport, and synergistic effect achieves high OER performance with the overpotential of 207 mV and long‐term 50 h stability at 10 mA cm −2 in an alkaline medium. Moreover, in‐depth insights into the microstructure, structure‐activity relationships, identification of key intermediate species, and a proton‐coupled four‐electron OER mechanism based on experimental discovery and theoretical calculation are also demonstrated.    

    

* The Synergistic Effect of IR and Oxygen Vacancies on Enhancing the Oer Performance of Surface-Reconstructed Feco Ldh  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391973777
:TOPICS: Catalytic Nanomaterials, Zinc Oxide Nanostructures, Advanced Materials for Smart Windows
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4732029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391973777"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391973777"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391973777"))][Get cited by]]

OpenAlex: https://openalex.org/W4391973777 (Open access: False)
    
[[https://openalex.org/A5020035945][Xianjun Deng]], [[https://openalex.org/A5064703123][Jinwei Chen]], [[https://openalex.org/A5078326314][Qiuyan Chen]], [[https://openalex.org/A5051959681][Yunzhe Zhou]], [[https://openalex.org/A5037956890][Xinchi Liu]], [[https://openalex.org/A5014840423][Jie Zhang]], [[https://openalex.org/A5030921116][Gang Wang]], [[https://openalex.org/A5005949841][Ruilin Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4732029 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Oxygen-enriched vacancies Co3O4/NiCo2O4 heterojunction hollow nanocages with enhanced electrochemical properties for supercapacitors  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391981031
:TOPICS: Materials for Electrochemical Supercapacitors, Lithium-ion Battery Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159732")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391981031"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391981031"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391981031"))][Get cited by]]

OpenAlex: https://openalex.org/W4391981031 (Open access: False)
    
[[https://openalex.org/A5019812851][P. Zhu]], [[https://openalex.org/A5056977440][Fangyuan Su]], [[https://openalex.org/A5002536773][Lingling Xie]], [[https://openalex.org/A5084461414][Xiaoming Li]], [[https://openalex.org/A5033201032][Yongfeng Li]], [[https://openalex.org/A5062211076][Cheng-Meng Chen]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159732 
     
No abstract    

    

* Self-Supported Low-Crystallinity Cofe Layered Double Hydroxide Nanospheres on Monolayer Ti3c2 Electrode for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391981843
:TOPICS: Electrocatalysis for Energy Conversion, Perovskite Solar Cell Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4732198")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391981843"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391981843"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391981843"))][Get cited by]]

OpenAlex: https://openalex.org/W4391981843 (Open access: False)
    
[[https://openalex.org/A5029484872][Lu Wang]], [[https://openalex.org/A5085245939][Yi Lü]], [[https://openalex.org/A5051434566][Shuo Wang]], [[https://openalex.org/A5045455578][Qingqing Li]], [[https://openalex.org/A5035885460][Yinghua Zhou]], [[https://openalex.org/A5037476812][Wei Chen]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4732198 
     
No abstract    

    

* Stainless Steel Activation for Efficient Alkaline Oxygen Evolution in Advanced Electrolyzers  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391981888
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202312071")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391981888"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391981888"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391981888"))][Get cited by]]

OpenAlex: https://openalex.org/W4391981888 (Open access: False)
    
[[https://openalex.org/A5028765513][Yong Zuo]], [[https://openalex.org/A5093966575][Valentina Mastronard]], [[https://openalex.org/A5093575180][Agnese Gamberini]], [[https://openalex.org/A5034371294][Marilena Isabella Zappia]], [[https://openalex.org/A5031285770][Thi‐Hong‐Hanh Le]], [[https://openalex.org/A5004029612][Mirko Prato]], [[https://openalex.org/A5082004546][Silvia Dante]], [[https://openalex.org/A5006596283][Sebastiano Bellani]], [[https://openalex.org/A5025956413][Liberato Manna]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202312071 
     
Abstract Designing robust and cost‐effective electrocatalysts for efficient alkaline oxygen evolution reaction (OER) is of great significance in the field of water electrolysis. In this study, we introduce an electrochemical strategy to activate stainless steel (SS) electrodes for efficient OER. By cycling the SS electrode within a potential window that encompasses the Fe(II)↔Fe(III) process, we can greatly enhance its OER activity compared to using a potential window that excludes this redox reaction, decreasing the overpotential at current density of 100 mA cm −2 by 40 mV. Electrochemical characterization, Inductively Coupled Plasma – Optical Emission Spectroscopy and operando Raman measurements demonstrated that the Fe leaching at the SS surface can be accelerated through a Fe → γ‐Fe 2 O 3 → Fe 3 O 4 or FeO → Fe 2+ (aq.) conversion process, leading to the sustained exposure of Cr and Ni species. While Cr leaching occurs during its oxidation process, Ni species display higher resistance to leaching and gradually accumulate on the SS surface in the form of OER‐active Fe‐incorporated NiOOH species. Furthermore, a potential‐pulse strategy was also introduced to regenerate the OER‐activity of 316‐type SS for stable OER, both in the three‐electrode configuration (without performance decay after 300 h at 350 mA cm −2 ) and in an alkaline water electrolyzer (ca. 30 mV cell voltage increase after accelerated stress test‐AST). The AST‐stabilized cell can still reach 1000 mA cm −2 and 4000 mA cm −2 at cell voltages of 1.69 V and 2.1 V, which makes it competitive with state‐of‐the‐art electrolyzers based on ion‐exchange‐membranes using Ir‐based anodes. This article is protected by copyright. All rights reserved    

    

* Iron-Based nanoporous Metal-Organic frameworks with Side-Chain amino substituents for Efficiency-Regulated oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391984044
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jiec.2024.02.022")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391984044"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391984044"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391984044"))][Get cited by]]

OpenAlex: https://openalex.org/W4391984044 (Open access: False)
    
[[https://openalex.org/A5064106038][Bowen Peng]], [[https://openalex.org/A5049238742][Dongmei Yang]], [[https://openalex.org/A5078276870][Ziyao Li]], [[https://openalex.org/A5016060184][Haoyu Yuan]], [[https://openalex.org/A5011439848][Peng Wu]], [[https://openalex.org/A5029699414][Kexin Huang]], [[https://openalex.org/A5046781770][Kaixuan Sun]], [[https://openalex.org/A5079953797][Jun Zhu]], [[https://openalex.org/A5010872059][Keliang Wu]], [[https://openalex.org/A5072090352][Zhiyong Liu]], Journal of Industrial and Engineering Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jiec.2024.02.022 
     
No abstract    

    

* High-Entropy Effect Promoting Self-Healing Behavior of Two-Dimensional Metal Oxide Electrocatalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4391991674
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c05870")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391991674"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391991674"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391991674"))][Get cited by]]

OpenAlex: https://openalex.org/W4391991674 (Open access: False)
    
[[https://openalex.org/A5051788822][Dongdong Gao]], [[https://openalex.org/A5021658618][Wenxiang Zhu]], [[https://openalex.org/A5087269163][Jinxin Chen]], [[https://openalex.org/A5008126805][Keyang Qin]], [[https://openalex.org/A5074338325][Mengjie Ma]], [[https://openalex.org/A5025849211][Jie Shi]], [[https://openalex.org/A5013134577][Qun Wang]], [[https://openalex.org/A5061980234][Zhenglong Fan]], [[https://openalex.org/A5065985607][Qi Shao]], [[https://openalex.org/A5043301652][Fan Liao]], [[https://openalex.org/A5057299366][Mingwang Shao]], [[https://openalex.org/A5071907213][Zhenhui Kang]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c05870 
     
No abstract    

    

* Dense Heterogeneous Interfaces Boost the Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392000713
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4733793")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392000713"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392000713"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392000713"))][Get cited by]]

OpenAlex: https://openalex.org/W4392000713 (Open access: False)
    
[[https://openalex.org/A5032711329][Shuai Liu]], [[https://openalex.org/A5083980378][Fumin Wang]], [[https://openalex.org/A5044785404][Jiawei Wang]], [[https://openalex.org/A5008587352][Weitao Zheng]], [[https://openalex.org/A5085400189][Xinyuan He]], [[https://openalex.org/A5074690414][Tongxue Zhang]], [[https://openalex.org/A5019005078][Zhiwei Zhang]], [[https://openalex.org/A5022576893][Qian Liu]], [[https://openalex.org/A5067268817][Xijun Liu]], [[https://openalex.org/A5033775732][Xubin Zhang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4733793 
     
No abstract    

    

* Silver zirconate: A versatile visible light harvesting photocatalyst for oxygen evolution, PMS activation, and bactericidal activity  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392005660
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jphotochem.2024.115537")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392005660"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392005660"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392005660"))][Get cited by]]

OpenAlex: https://openalex.org/W4392005660 (Open access: False)
    
[[https://openalex.org/A5081656746][Rudra Pratap Singh]], [[https://openalex.org/A5093972281][Mrunal M. Shiwankar]], [[https://openalex.org/A5086570143][Amit Kumar Maurya]], [[https://openalex.org/A5092127017][Awanti S. Talmale]], [[https://openalex.org/A5006205634][G.S. Gaikwad]], [[https://openalex.org/A5063299328][Atul V. Wankhade]], Journal of Photochemistry and Photobiology A: Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jphotochem.2024.115537 
     
Herein, we have synthesized silver zirconate using a co-precipitation method at room temperature. The synthesized Ag2ZrO3 (SZ) was then subjected to calcination at different temperatures (300 °C, 500 °C, and 700 °C). The synthesized Ag2ZrO3 material was evaluated for its photocatalytic oxygen evolution, activation of peroxymonosulfate (PMS) ions, and antibacterial activity under visible light irradiation. Among the different samples, the SZ sample (Ag2ZrO3 synthesized at room temperature) exhibited the highest photocatalytic oxygen evolution rate (2175.02 μmolg-1h−1). This enhanced performance can be attributed to the higher surface area of SZ compared to the other samples. Furthermore, all four samples were tested for the photoactivation of peroxymonosulfate (PMS) ions to assess their ability for the decontamination of organic pollutant. The SZ photocatalyst demonstrated complete degradation (100 %) of RhB dye (2.1 × 10-5 M) within 120 min of visible light irradiation in the presence of PMS. In contrast, without PMS, only 54.33 % degradation of RhB was recorded in 300 min. This result indicates that SZ effectively activates PMS ions for the degradation of organic pollutants. Additionally, SZ exhibited excellent bactericidal activity against E. coli and S. aureus bacteria, both in the dark and in the presence of visible light. The findings demonstrate the multifunctional properties of Ag2ZrO3, making it suitable for a wide range of environmental remediation applications.    

    

* Sulfate anchored on the defective NiO by ion irradiation realizes enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392005855
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149890")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392005855"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392005855"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392005855"))][Get cited by]]

OpenAlex: https://openalex.org/W4392005855 (Open access: False)
    
[[https://openalex.org/A5005285333][Derun Li]], [[https://openalex.org/A5091812681][Wenfeng Guo]], [[https://openalex.org/A5043006241][Zhuo Xing]], [[https://openalex.org/A5080382748][Tao Jiang]], [[https://openalex.org/A5076699693][Zhaowu Wang]], [[https://openalex.org/A5020636129][Shanshan Wu]], [[https://openalex.org/A5091854956][Liuqing Huang]], [[https://openalex.org/A5017470521][Yichao Liu]], [[https://openalex.org/A5044845618][Hengyi Wu]], [[https://openalex.org/A5028412020][Changzhong Jiang]], [[https://openalex.org/A5085724915][Feng Ren]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149890 
     
NiO has attracted wide attention in the past decade as a cost-effective electrochemical catalyst for OER. However, its relatively poor performance and conductivity limit its commercial applications. Here, we highlight a unique ion irradiation method to enhance the catalytic activity of NiO. Benefiting from sulfate anchoring and the introduction of oxygen vacancies by He+ ion irradiation, the optimal catalyst (ir-S-NiO) exhibits an outstanding OER performance with a low overpotential of 269 mV at 10 mA cm−2. Moreover, the fabricated Anion exchange membrane water electrolyzer (AEMWE) constructed by the ir-S-NiO is demonstrated to need a cell voltage of 1.72 V to reach a current density of 0.1 A cm−2 and shows remarkably long-term stability for 200 h without obvious attenuation at the current density of 0.5 A cm−2. This work provides a new method for the development of high-performance and stable OER electrocatalysts.    

    

* Construction of nickel phosphide/iron oxyhydroxide heterostructure nanoparticles for oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392005890
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nanoen.2024.109402")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392005890"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392005890"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392005890"))][Get cited by]]

OpenAlex: https://openalex.org/W4392005890 (Open access: False)
    
[[https://openalex.org/A5044626392][Yichuang Xing]], [[https://openalex.org/A5010940638][Shuling Liu]], [[https://openalex.org/A5010274839][Yuan Liu]], [[https://openalex.org/A5075441298][Xuechun Xiao]], [[https://openalex.org/A5085736683][Yvpei Li]], [[https://openalex.org/A5015077424][Zeyi Wang]], [[https://openalex.org/A5028748116][Yafei Hu]], [[https://openalex.org/A5086324364][B. Xin]], [[https://openalex.org/A5021471823][He Wang]], [[https://openalex.org/A5061165588][Chao Wang]], Nano Energy. None(None)] 2024. https://doi.org/10.1016/j.nanoen.2024.109402 
     
Active and stable oxygen evolution electrocatalysts are essential in increasing the efficiency of the water electrolyzers. The Ni2P/Fe(O)OH heterostructure nanoparticles are prepared via solvothermal phosphidization of Ni metal-organic frameworks (MOF) followed by immersing in Fe3+ aqueous solution. Characterizations reveal that the Ni2P/Fe(O)OH heterostructure nanoparticles are 12.83 nm in size averagely, and the heterointerface induces electron interactions between the Ni2P and Fe(O)OH phases. When used to catalyze OER in alkaline solutions, the Ni2P/Fe(O)OH-40/nickel foam (NF) is the most active and exhibits 240 mV overpotential to reach 10 mA cm-2 oxygen evolution (OER) current densities, which is significantly better than the Ni2P/NF. Lower apparent activation energy, charge transfer resistance, and Tafel slope, along with higher electron rate constant are observed at Ni2P/Fe(O)OH-40/NF, which suggests that the OER kinetics is more facile at the heterostructure surface. Both Ni2P/Fe(O)OH-40/NF and Ni2P/NF involve decoupled electron and proton transfer process, and higher degree of lattice oxygen oxidation mechanism (LOM) participation is observed at Ni2P/Fe(O)OH-40/NF, which results from the increased acidity of the Ni3+ sites. Density functional theory calculations prove that the formation of heterostructure with Fe(O)OH alters the band structure and the OER intermediate adsorption energies, that lead to lower energy barrier in the rate-determining step. The Ni2P/Fe(O)OH-40/NF is also stable towards OER in alkaline solutions.    

    

* Controlled fabrication of various nanostructures iron-based tellurides as highly performed oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392010419
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.051")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392010419"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392010419"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392010419"))][Get cited by]]

OpenAlex: https://openalex.org/W4392010419 (Open access: False)
    
[[https://openalex.org/A5086085281][Munirah D. Albaqami]], [[https://openalex.org/A5038180168][Mehar Un Nisa]], [[https://openalex.org/A5049370676][Sumaira Manzoor]], [[https://openalex.org/A5051155813][Jafar Hussain Shah]], [[https://openalex.org/A5062023379][S. Noor Mohammad]], [[https://openalex.org/A5090663793][Şenay Yalçın]], [[https://openalex.org/A5052155429][Abdul Ghafoor Abid]], [[https://openalex.org/A5049328863][Suleyman I. Allakhverdiev]], International Journal of Hydrogen Energy. 60(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.051 
     
Electrochemical water splitting is a process that shows promise for the sustainable conversion, storage, and delivery of hydrogen energy. The support development of electrocatalysts that support hydrogen and oxygen evolution processes (HER/OER) without requiring precious metals and with superior activity and durability is crucial for the broad adoption of water electrolysis. Compared to the traditional powder-coated type, a freestanding electrode architecture exhibits superior stability and kinetics. In this study, the layered FeTe-PANI nanocomposite is designed for hydrogen generation. Various nanostructures of FeTe-PANI like nanorods and nanosheets by controllable expansion of surfactants such as hexadecyl trimethyl ammonium bromide (CTAB) can be adjusted to agglomerations. The nanosheets combined with nanorods (FeTe-PANI) show remarkable electrocatalytic activity with 195 mV overpotentials at 10 mAcm−2 for OER. Additionally, FeTe-PANI employed in a 2-electrode electrolyzer as a cathodic electrode electrocatalyst in 1.0 Molar potassium hydroxide media, yields a cell voltage of 1.52 V at a current density of 10 mAcm−2 with a noteworthy 80 h sturdiness, making it an ideal electrocatalyst towards empirical deployment of water splitting electrolyzers.    

    

* Metal-organic framework-derived heterostructured CoSe2-ZnSe nanorods coupled with carbon polyhedron supported carbon paper for oxygen evolution electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392010859
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.190")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392010859"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392010859"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392010859"))][Get cited by]]

OpenAlex: https://openalex.org/W4392010859 (Open access: False)
    
[[https://openalex.org/A5071534457][Shuaiqiang Liu]], [[https://openalex.org/A5091990584][Yu Li]], [[https://openalex.org/A5034297296][Yinghua Yan]], [[https://openalex.org/A5084986402][Huazhao Yang]], [[https://openalex.org/A5008650346][Chuanmin Ding]], [[https://openalex.org/A5051082404][Junwen Wang]], [[https://openalex.org/A5076323414][Donghong Duan]], [[https://openalex.org/A5012298533][Qinbo Yuan]], [[https://openalex.org/A5090208803][Xiaogang Hao]], [[https://openalex.org/A5019721584][Shibin Liu]], International Journal of Hydrogen Energy. 60(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.190 
     
Development of low-cost, efficient, and stable oxygen evolution electrocatalysts is crucial for the conversion and storage of renewable energy. Therefore, an effective integrated heterostructure catalyst is needed to achieve a lower overpotential during oxygen evolution process. In this paper, cobalt-zinc bimetallic MOF precursors are used as templates to prepare bimetallic cobalt-based selenides with good oxygen evolution catalytic activity and stability on carbon fiber paper. Due to the high specific surface area and porous structure of the coupling structure of nanorods and polyhedra, and the strong electronic coupling between CoSe2 and ZnSe on nanorods. CoSe2-ZnSe/CP exhibits excellent electrocatalytic activity in 1 M KOH solution. It only requires an overpotential of 275 mV to reach the current density of 10 mA cm-2, and the Tafel slope is 68.9 mV dec-1. In addition, after 12 h of continuous operation of CoSe2-ZnSe/CP, the activity decay of the catalyst is negligible. This work provides a method for the design of heterogeneous bimetallic selenide integrated oxygen evolution electrocatalysts.    

    

* Electrodeposited graphene@Co3O4 nanosheets for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392014924
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.234219")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392014924"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392014924"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392014924"))][Get cited by]]

OpenAlex: https://openalex.org/W4392014924 (Open access: False)
    
[[https://openalex.org/A5075883325][Qianyu Wang]], [[https://openalex.org/A5026017086][Zi-Ye Liu]], [[https://openalex.org/A5076421896][Ji-Ming Hu]], Journal of Power Sources. 599(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.234219 
     
No abstract    

    

* Regulating the Spin Polarization of NiFe Layered Double Hydroxide for the Enhanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392018831
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06180")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392018831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392018831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392018831"))][Get cited by]]

OpenAlex: https://openalex.org/W4392018831 (Open access: False)
    
[[https://openalex.org/A5017834536][Wenwu Cao]], [[https://openalex.org/A5068375738][Xianhui Gao]], [[https://openalex.org/A5038747062][Jie Wu]], [[https://openalex.org/A5056746694][Anqi Huang]], [[https://openalex.org/A5015273050][Huan Hu]], [[https://openalex.org/A5091083063][Zhongwei Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06180 
     
No abstract    

    

* The role of strain in oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392122210
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.02.007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392122210"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392122210"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392122210"))][Get cited by]]

OpenAlex: https://openalex.org/W4392122210 (Open access: False)
    
[[https://openalex.org/A5022885630][Zhixuan Feng]], [[https://openalex.org/A5037480797][Chia-Tsen Dai]], [[https://openalex.org/A5026635004][Zhe Zhang]], [[https://openalex.org/A5060430863][Xuefei Lei]], [[https://openalex.org/A5031052370][Wenning Mu]], [[https://openalex.org/A5021363847][Rui Guo]], [[https://openalex.org/A5081185893][Xuanwen Liu]], [[https://openalex.org/A5019520436][Jinyuan You]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.02.007 
     
No abstract    

    

* Nickel and Commercially Available Nickel‐Containing Alloys as Electrodes for the Electrochemical Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392105251
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202300460")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392105251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392105251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392105251"))][Get cited by]]

OpenAlex: https://openalex.org/W4392105251 (Open access: True)
    
[[https://openalex.org/A5016719471][Nikolas Mao Kubo]], [[https://openalex.org/A5093264058][Fabian Ketter]], [[https://openalex.org/A5065818528][Stefan Palkovits]], [[https://openalex.org/A5078364217][Regina Palkovits]], ChemElectroChem. None(None)] 2024. https://doi.org/10.1002/celc.202300460  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/celc.202300460][pdf]])
     
Abstract Water electrolysis is a crucial technology for independency on fossil fuels. However, water splitting is limited by the sluggish kinetics of oxygen evolution reaction (OER). While many studies report highly active, non‐precious metal‐based electrocatalysts for alkaline OER, applicability under industrial conditions is often omitted. Such conditions require catalysts being applied on nickel or nickel‐containing alloys in elevated electrolyte concentrations. In contrast to the rather inert substrates often used in scientific studies, such industrially applied substrates exhibit significant OER activity themselves and show dynamic behaviour. Therefore, it is crucial to understand the OER behaviour of such substrates. Here, nickel and seven commercially available nickel‐containing alloys are investigated as anodes in alkaline OER and their elemental compositions correlated to their corresponding activities. Repeated potential cycling across the Ni(II)/Ni(III)‐redox couple is established as activity‐enhancing procedure. Overall, the nickel‐base alloy Hastelloy® X exhibits the highest activity due to its Fe‐, Cr‐, Mo‐ and Co‐content. Though, the activity gain differs significantly for the various materials. Comparing Ni and Hastelloy® X as least and most active materials, the positive impact of activation on both activity and stability becomes evident. While untreated Ni suffers from poor OER stability, the activity‐enhancing procedure also significantly increases electrode stability in 24 h chronopotentiometry.    

    

* Seven mechanisms of oxygen evolution reaction proposed recently: A mini review  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392142198
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149992")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392142198"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392142198"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392142198"))][Get cited by]]

OpenAlex: https://openalex.org/W4392142198 (Open access: False)
    
[[https://openalex.org/A5022885630][Zhixuan Feng]], [[https://openalex.org/A5037480797][Chia-Tsen Dai]], [[https://openalex.org/A5032553249][Peng Shi]], [[https://openalex.org/A5060430863][Xuefei Lei]], [[https://openalex.org/A5021363847][Rui Guo]], [[https://openalex.org/A5075523709][Biao Wang]], [[https://openalex.org/A5081185893][Xuanwen Liu]], [[https://openalex.org/A5019520436][Jinyuan You]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149992 
     
No abstract    

    

* Polarized Ultrathin BN Induced Dynamic Electron Interactions for Enhancing Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392109777
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202402018")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392109777"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392109777"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392109777"))][Get cited by]]

OpenAlex: https://openalex.org/W4392109777 (Open access: False)
    
[[https://openalex.org/A5036780151][Yixin Hao]], [[https://openalex.org/A5060265950][Sung‐Fu Hung]], [[https://openalex.org/A5078634223][Cheng Tian]], [[https://openalex.org/A5049099959][Luqi Wang]], [[https://openalex.org/A5091632977][Yiyu Chen]], [[https://openalex.org/A5002546727][Sheng Zhao]], [[https://openalex.org/A5081952140][Kang-Lin Peng]], [[https://openalex.org/A5056489746][Chenchen Zhang]], [[https://openalex.org/A5047629524][Ying Zhang]], [[https://openalex.org/A5010783003][Chun‐Han Kuo]], [[https://openalex.org/A5084555578][Han‐Yi Chen]], [[https://openalex.org/A5011395130][Shengjie Peng]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202402018 
     
Developing ruthenium‐based heterogeneous catalysts with an efficient and stable interface is essential for enhanced acidic oxygen evolution reaction (OER). Herein, we report a defect‐rich ultrathin boron nitride nanosheet support with relatively independent electron donor and acceptor sites, which serves as an electron reservoir and receiving station for RuO2, realizing the rapid supply and reception of electrons. Through precisely controlling the reaction interface, a low OER overpotential of only 180 mV (at 10 mA cm−2) and long‐term operational stability (350 h) are achieved, suggesting potential practical applications. In‐situ characterization and theoretical calculations have validated the existence of a localized electronic recycling between RuO2 and BNNS. The electron‐rich Ru sites accelerate the adsorption of water molecules and the dissociation of intermediates, while the interconnection between the O‐terminal and B‐terminal edge establishes electronic back‐donation, effectively suppressing the over‐oxidation of lattice oxygen. This study provides a new perspective for constructing a stable and highly active catalytic interface.    

    

* Polarized Ultrathin BN Induced Dynamic Electron Interactions for Enhancing Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392110312
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202402018")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392110312"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392110312"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392110312"))][Get cited by]]

OpenAlex: https://openalex.org/W4392110312 (Open access: False)
    
[[https://openalex.org/A5036780151][Yixin Hao]], [[https://openalex.org/A5060265950][Sung‐Fu Hung]], [[https://openalex.org/A5078634223][Cheng Tian]], [[https://openalex.org/A5049099959][Luqi Wang]], [[https://openalex.org/A5091632977][Yiyu Chen]], [[https://openalex.org/A5002546727][Sheng Zhao]], [[https://openalex.org/A5081952140][Kang-Lin Peng]], [[https://openalex.org/A5056489746][Chenchen Zhang]], [[https://openalex.org/A5042973046][Ying Zhang]], [[https://openalex.org/A5010783003][Chun‐Han Kuo]], [[https://openalex.org/A5084555578][Han‐Yi Chen]], [[https://openalex.org/A5011395130][Shengjie Peng]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202402018 
     
Developing ruthenium‐based heterogeneous catalysts with an efficient and stable interface is essential for enhanced acidic oxygen evolution reaction (OER). Herein, we report a defect‐rich ultrathin boron nitride nanosheet support with relatively independent electron donor and acceptor sites, which serves as an electron reservoir and receiving station for RuO2, realizing the rapid supply and reception of electrons. Through precisely controlling the reaction interface, a low OER overpotential of only 180 mV (at 10 mA cm−2) and long‐term operational stability (350 h) are achieved, suggesting potential practical applications. In‐situ characterization and theoretical calculations have validated the existence of a localized electronic recycling between RuO2 and BNNS. The electron‐rich Ru sites accelerate the adsorption of water molecules and the dissociation of intermediates, while the interconnection between the O‐terminal and B‐terminal edge establishes electronic back‐donation, effectively suppressing the over‐oxidation of lattice oxygen. This study provides a new perspective for constructing a stable and highly active catalytic interface.    

    

* Nanoflowers of Ternary Cobalt–Copper–Manganese Oxide as an Efficient Electrocatalyst for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392130324
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ente.202301355")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392130324"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392130324"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392130324"))][Get cited by]]

OpenAlex: https://openalex.org/W4392130324 (Open access: False)
    
[[https://openalex.org/A5003445703][Jyoti Raghav]], [[https://openalex.org/A5045408244][P. Rosaiah]], [[https://openalex.org/A5051674509][Bandar Ali Al‐Asbahi]], [[https://openalex.org/A5001688048][Soumyendu Roy]], Energy Technology. None(None)] 2024. https://doi.org/10.1002/ente.202301355 
     
Oxygen evolution reaction (OER) is an integral step in the water‐splitting process. Hence, to promote OER, efficient catalysts are required to lower the energy barriers at the electrode/electrolyte interface. Low‐cost and highly active catalysts are in great demand. Herein, a ternary metal oxide, CoCuMnO x , synthesized by a facile hydrothermal method is reported, which possesses excellent catalytic ability for OER in alkaline electrolytes. The nanoscale morphology of the catalyst with flower‐like nanostructures is instrumental in increasing the electrochemical surface area of the electrode. The presence of multivalent ions and the incorporation of copper greatly enhance the electrochemical properties of the catalysts. The catalysts typically demonstrate an overpotential value of 220 mV for achieving 10 mA cm −2 current density and a Tafel slope of 73 mV dec −1 . The catalysts demonstrate good stability with minimal degradation in OER activity even after 20 h of chronopotentiometry test. For practical applications, this low‐cost material holds great potential.    

    

* Constructions of hierarchical nitrogen doped carbon nanotubes anchored on CoFe2O4 nanoflakes for efficient hydrogen evolution, oxygen evolution and oxygen reduction reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392077017
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.234218")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392077017"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392077017"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392077017"))][Get cited by]]

OpenAlex: https://openalex.org/W4392077017 (Open access: False)
    
[[https://openalex.org/A5027131833][JiaJun Lai]], [[https://openalex.org/A5026918847][Zeng Chen]], [[https://openalex.org/A5088166213][Song Peng]], [[https://openalex.org/A5040296357][Qin Zhou]], [[https://openalex.org/A5062815625][Zeng Ju]], [[https://openalex.org/A5038072194][Chao Liu]], [[https://openalex.org/A5045410326][Xiaopeng Qi]], Journal of Power Sources. 599(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.234218 
     
The three primary reactions in metal-air batteries and electrochemical hydrolysis are the hydrogen evolution reaction (HER), the oxygen evolution reaction (OER), and the oxygen reduction reaction (ORR). Therefore, it is crucial to develop efficient low-cost trifunctional catalysts. In this study, we design a self-supported electrocatalyst with hierarchical nanostructure, in which the bamboo-like nitrogen doped carbon nanotubes (NCNTs) encapsulated CoFe nanoparticles (CoFe NPs) in-situ anchored on nanoflower like CoFe2O4 via chemical vapor deposition. Strikingly, the resulting catalysts CoFe@NC/CoFe2O4/IF demonstrate exciting trifunctional catalytic performance, overpotential of 66 mV and 185 mV for HER and OER at current densities of 10 mA cm−2, and a half-wave potential of 0.852 V for ORR, respectively. In addition, the maximum power density of the Zinc-air batteries (ZABs) assembled with CoFe@NC/CoFe2O4/IF as the cathode electrode is 134.5 mW cm−2; and the overall water splitting requires only a voltage of 1.50 V at a decomposition current density at 10 mA cm−2. This method provides a new strategy for trifunctional electrocatalysts and offers a promising approach for self-driven water electrolysis devices.    

    

* Tuning Mo cations dissolution and surface reconstruction of CoMoO4 for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392095514
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173963")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392095514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392095514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392095514"))][Get cited by]]

OpenAlex: https://openalex.org/W4392095514 (Open access: False)
    
[[https://openalex.org/A5030288532][Hong Yin]], [[https://openalex.org/A5075330438][Yaonan Mo]], [[https://openalex.org/A5005792080][Chuang Liu]], [[https://openalex.org/A5008858273][Hengbo Xiao]], [[https://openalex.org/A5005752974][Zhilong Zheng]], [[https://openalex.org/A5088697406][Songliu Yuan]], [[https://openalex.org/A5025306333][Junjie Guo]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.173963 
     
No abstract    

    

* Boosting activity on molten salt-synthesized Ce doped cobalt hydroxyl nitrate nanorods by oxygen vacancies for efficient oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392074898
:TOPICS: Formation and Properties of Nanocrystals and Nanostructures, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131214")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392074898"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392074898"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392074898"))][Get cited by]]

OpenAlex: https://openalex.org/W4392074898 (Open access: False)
    
[[https://openalex.org/A5039804899][Na Xu]], [[https://openalex.org/A5061173596][Ning Yu]], [[https://openalex.org/A5068775213][Zhaoxia Jin]], [[https://openalex.org/A5005475250][Yanan Zhou]], [[https://openalex.org/A5050840588][Yusheng Zhang]], [[https://openalex.org/A5058907569][Jin-Long Tan]], [[https://openalex.org/A5075675634][Yulu Zhou]], [[https://openalex.org/A5062331341][Yong‐Ming Chai]], [[https://openalex.org/A5072072030][Bin Dong]], Fuel. 365(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131214 
     
Rationalizing the development of highly active, non-precious electrocatalysts through facile and cost-effective synthesis methods for the oxygen evolution reaction (OER) constitutes a paramount research objective. In this study, we introduce an innovative molten salt approach to fabricate an arrayed nanorod architecture supported on a cobalt foam substrate denoted as Ce doped cobalt hydroxyl nitrate (Ce-CoNH). Cerium (Ce) is strategically employed to induce oxygen vacancies and effect localized electronic structure modifications of the cobalt (Co) sites. In comparison to individual CoNH catalysts, Ce-CoNH exhibits exceptional catalytic activity in alkaline water oxidation, achieving a notably low overpotential of 270 mV at a current density of 50 mA cm−2. Notably, the Ce-CoNH catalyst also demonstrates remarkable durability, sustaining a current density of 100 mA cm−2 for an impressive duration of 50 h, surpassing the performance of Ce-free CoNH samples, which can be attributed to the flexible influence of Ce doping and the robust nanorod structure. Collectively, our study underscores the viability of molten salt-synthesized heteroatom substitution, accompanied by the introduction of defect-rich structures, as an effective strategy for the rational design of advanced electrocatalysts tailored for water electrolysis applications.    

    

* Ultrafast electronic and vibrational spectroscopy of electrochemical transformations on a metal-oxide surface during oxygen evolution from water  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392103902
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Quantum Coherence in Photosynthesis and Aqueous Systems
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-rzgp3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392103902"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392103902"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392103902"))][Get cited by]]

OpenAlex: https://openalex.org/W4392103902 (Open access: True)
    
[[https://openalex.org/A5066895569][Tanja Cuk]], [[https://openalex.org/A5054037567][Xihan Chen]], [[https://openalex.org/A5082056990][Suryansh Singh]], [[https://openalex.org/A5012639606][Michael Paolino]], [[https://openalex.org/A5060242817][James J. P. Stewart]], [[https://openalex.org/A5028760607][Ilya Vinogradov]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-rzgp3  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65d779d166c138172943186c/original/ultrafast-electronic-and-vibrational-spectroscopy-of-electrochemical-transformations-on-a-metal-oxide-surface-during-oxygen-evolution-from-water.pdf][pdf]])
     
The oxygen evolution reaction (OER) from water fuels the planet through photosynthesis and is a primary means for hydrogen storage in energy technologies. Yet the detection of intermediates of OER central to the catalytic mechanism has been an ongoing challenge. This review covers the relevance of ultrafast electronic and vibrational spectroscopy of the electrochemical transformations of a metal-oxide surface undergoing OER. The electron doped SrTiO3/electrolyte is the system under review because of its high photocurrent efficiency with an ultrafast light trigger and because it allowed for detection of intermediate forms across the electromagnetic spectrum. The first part covers how the efficient catalytic reaction is triggered by ultrafast light pulses, describing the Schottky diode, the depletion layer, and Helmholtz layer under operating conditions to the extent possible. The second part covers the detection of the surface bound intermediates by transient spectroscopy. These target ultrafast (ps-ns) electron transfer from (or hole-trapping to) bound surface water species that are associated with the reactive oxygen intermediates of OER (e.g. OH*, O*). Their detection via a broadband visible probe, a mid-infrared evanescent wave, and coherent acoustic waves is then described. These target, respectively, the electronic states, the vibrational levels, and the lattice strain associated with the intermediates. The review is primarily concerned with how the measurements are made and the intermediates’ experimental spectra. The theoretical descriptions are brought in as a needed to provide context to spectra that are difficult to interpret on their own. A concluding section summarizes the essential findings and methodologies.    

    

* Investigation of the Relationship between Metal Loading and Acidic Oxygen Evolution Reaction Activity in Single-Atom Catalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392084683
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-02-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06263")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392084683"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392084683"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392084683"))][Get cited by]]

OpenAlex: https://openalex.org/W4392084683 (Open access: False)
    
[[https://openalex.org/A5035223262][Bing Tang]], [[https://openalex.org/A5059787769][Xiaolong Zhang]], [[https://openalex.org/A5020016810][Qianqian Ji]], [[https://openalex.org/A5017197771][Gao Min]], [[https://openalex.org/A5036519850][Huijuan Wang]], [[https://openalex.org/A5067669061][Ruiqi Liu]], [[https://openalex.org/A5017430213][Peng Jiang]], [[https://openalex.org/A5005402696][Hengjie Liu]], [[https://openalex.org/A5055838753][Chao Wang]], [[https://openalex.org/A5069910699][Hao Tan]], [[https://openalex.org/A5052333339][Wensheng Yan]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06263 
     
No abstract    

    
