#+TITLE: water splitting
Description: water splitting papers
Created on Thu Aug  1 01:17:18 2024

Found 56 results from 2024-07-25 to 2024-08-01
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Effect of Transition Metals (Mn, Co, Ni, and Zn) in Size-Controlled Metal Ferrite Nanocrystals on the Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400935288
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.4c03007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400935288"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400935288"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400935288"))][Get cited by]]

OpenAlex: https://openalex.org/W4400935288 (Open access: False)
    
[[https://openalex.org/A5022093708][Vijayakrishnan Jeyavani]], [[https://openalex.org/A5058437657][Shanmugasundaram Manoj]], [[https://openalex.org/A5038542375][Shatabdi Porel Mukherjee]], ACS Applied Nano Materials. None(None)] 2024. https://doi.org/10.1021/acsanm.4c03007 
     
No abstract    

    

* Fe,Ce Co‐Doped Ni3S2/NiS Polymorphism Nanosheets with Improved Electrocatalytic Activity and Stability for Water Oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400936838
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202400896")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400936838"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400936838"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400936838"))][Get cited by]]

OpenAlex: https://openalex.org/W4400936838 (Open access: False)
    
[[https://openalex.org/A5063099993][Shaoxia Wang]], [[https://openalex.org/A5100338268][Huihui Li]], [[https://openalex.org/A5100774424][Shifeng Li]], [[https://openalex.org/A5052994411][Yonghong Ni]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202400896 
     
Balancing the relationship between electrocatalytic activity and stability of sulfide catalysts during oxygen evolution reaction (OER) has been attracting extensive research interest. Here, a simple electrodeposition‐vulcanization two‐step route was designed to successfully construct nickel foam supported sheet‐like Fe,Ce‐codoped Ni3S2/NiS polymorphism catalyst (labeled as Fe,Ce‐Ni3S2/NiS/NF). Electrochemical measurements showed that the as‐obtained Fe,Ce‐Ni3S2/NiS/NF electrode presented excellent OER electrocatalytic performances. In 1 M KOH solution, merely 173 and 234 mV of overpotentials were required to deliver the current densities of 10 and 100 mA cm‐2, respectively. Further investigations revealed that the Fe,Ce co‐doping regulated the electron density around Ni, which promoted the conversion of Ni towards the higher valence state and simultaneously, avoided the stability decrease of the catalyst caused by excessive oxidation corrosion. Moreover, the defects generated during vulcanization also contributed to promoting water oxidation. The present work provides a facile and feasible approach to balance the relationship between the stability and the activity of sulfide catalysts for OER.    

    

* Oxygen deficient BaTiO3 loading sub-nm PtOx for photocatalytic biological wastewater splitting to green hydrogen production  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400942716
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Photocatalysis and Solar Energy Conversion, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.154261")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400942716"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400942716"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400942716"))][Get cited by]]

OpenAlex: https://openalex.org/W4400942716 (Open access: False)
    
[[https://openalex.org/A5100737156][Guilin Chen]], [[https://openalex.org/A5071601763][Yujin Ji]], [[https://openalex.org/A5081873082][Xintong Shi]], [[https://openalex.org/A5020251473][Pengfei An]], [[https://openalex.org/A5100345523][Jing Zhang]], [[https://openalex.org/A5035944985][Youyong Li]], [[https://openalex.org/A5091362073][Shengzhong Liu]], [[https://openalex.org/A5047252183][Junqing Yan]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.154261 
     
No abstract    

    

* In Situ Hydrogel with Immobilized Mn-Porphyrin for Reactive Oxygen Species Scavenging, Oxygen Generation, and Risedronate Delivery in Bone Defect Treatment  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400948237
:TOPICS: Biomedical Applications of Graphene Nanomaterials, Nanotechnology and Imaging for Cancer Therapy and Diagnosis, Nanoparticle-Based Drug Delivery Systems
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsami.4c08350")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400948237"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400948237"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400948237"))][Get cited by]]

OpenAlex: https://openalex.org/W4400948237 (Open access: False)
    
[[https://openalex.org/A5100725749][Kim M]], [[https://openalex.org/A5045367174][Soo Bin Yoon]], [[https://openalex.org/A5022843563][Han Bi Ji]], [[https://openalex.org/A5042914198][Cho Rim Kim]], [[https://openalex.org/A5019758327][Jae Hoon Han]], [[https://openalex.org/A5075200035][Sena Kim]], [[https://openalex.org/A5000754818][Chang Hee Min]], [[https://openalex.org/A5101781931][Chul Lee]], [[https://openalex.org/A5002050254][Lan Sook Chang]], [[https://openalex.org/A5043970272][Young Bin Choy]], ACS Applied Materials & Interfaces. None(None)] 2024. https://doi.org/10.1021/acsami.4c08350 
     
We propose a hydrogel immobilized with manganese porphyrin (MnP), a biomimetic superoxide dismutase (SOD), and catalase (CAT) to modulate reactive oxygen species (ROS) and hypoxia that impede the repair of large bone defects. Our hydrogel synthesis involved thiolated chitosan and polyethylene glycol-maleimide conjugated with MnPs (MnP-PEG-MAL), which enabled    

    

* Titanium oxide supported molybdenum-nickel-iron oxide electrocatalyst for efficient and durable oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400952027
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-11-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.132509")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400952027"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400952027"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400952027"))][Get cited by]]

OpenAlex: https://openalex.org/W4400952027 (Open access: False)
    
[[https://openalex.org/A5100392071][Wei Wang]], [[https://openalex.org/A5100324049][Kai Zhang]], [[https://openalex.org/A5008202465][Shuaichong Wei]], [[https://openalex.org/A5100773482][Xiangchao Meng]], [[https://openalex.org/A5103280374][Haisheng Han]], [[https://openalex.org/A5100741974][Guihua Liu]], Fuel. 375(None)] 2024. https://doi.org/10.1016/j.fuel.2024.132509 
     
No abstract    

    

* High-Efficiency Oxygen Evolution Reaction: Effect of Phosphorus Doped on the Surface Reconstruction of High-Entropy Spinel Oxides  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400953696
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.175696")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400953696"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400953696"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400953696"))][Get cited by]]

OpenAlex: https://openalex.org/W4400953696 (Open access: False)
    
[[https://openalex.org/A5102637709][Ziming Bai]], [[https://openalex.org/A5041713741][Ghulam Mustafa]], [[https://openalex.org/A5100443030][Zhe Zhang]], [[https://openalex.org/A5028379634][Changgong Meng]], [[https://openalex.org/A5103585651][Yuzhen Pan]], [[https://openalex.org/A5052154037][Zhen Chen]], [[https://openalex.org/A5100392071][Wei Wang]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.175696 
     
No abstract    

    

* Cofe-Ldhs Were Grown on Co-Layered Hydroxides to Achieve 3d-Hierarchical Flower Like Architecture for Efficient Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400966452
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4903722")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400966452"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400966452"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400966452"))][Get cited by]]

OpenAlex: https://openalex.org/W4400966452 (Open access: False)
    
[[https://openalex.org/A5100394072][Haibo Liu]], [[https://openalex.org/A5100773712][Yufan Zhang]], [[https://openalex.org/A5088923369][Ningzhao Shang]], [[https://openalex.org/A5101788579][Gao Y]], [[https://openalex.org/A5038208666][Huan Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4903722 
     
No abstract    

    

* Improving the Electrocatalytic Activity of Cobalt Oxide with Bismuth for Acidic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400970409
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta02845g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400970409"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400970409"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400970409"))][Get cited by]]

OpenAlex: https://openalex.org/W4400970409 (Open access: True)
    
[[https://openalex.org/A5004226797][Tewodros Asefa]], [[https://openalex.org/A5067036957][Belvin Thomas]], [[https://openalex.org/A5105063958][Bowen Peng]], [[https://openalex.org/A5013032351][Xiaoxi Huang]], Journal of Materials Chemistry A. None(None)] 2024. https://doi.org/10.1039/d4ta02845g 
     
Highly durable, low-cost electrocatalysts for acidic oxygen evolution reaction (OER) are very essential for the commercial success of proton exchange membrane-based water electrolysis. The catalysts currently available for this reaction...    

    

* Ru Single-Atom Nanoarchitectonics on Co-Based Conducting Metal–Organic Frameworks for Enhanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400971488
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c02804")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400971488"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400971488"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400971488"))][Get cited by]]

OpenAlex: https://openalex.org/W4400971488 (Open access: False)
    
[[https://openalex.org/A5105048618][Ruyu Xue]], [[https://openalex.org/A5101660914][Zhe Chuan Feng]], [[https://openalex.org/A5101818527][Yantao Wang]], [[https://openalex.org/A5002884743][Junfeng Huang]], [[https://openalex.org/A5101473086][Wei Dou]], [[https://openalex.org/A5018390453][Cailing Xu]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c02804 
     
The development of oxygen evolution reaction (OER) electrocatalysts is essential for the production of green hydrogen from water electrolysis, but it is challenging. Herein, ruthenium (Ru) single-atom-modified Co-HHTP (HHTP = 2,3,6,7,10,11-hexahydroxytriphenylene) (Ru@Co-HHTP) was prepared via a solvothermal and ion exchange method. Systematic experiments highlight that the atomically dispersed Ru can optimize the electronic structure and electronic conductivity of Co-HHTP. As a result, the obtained Ru@Co-HHTP shows a low overpotential of 247 mV at 100 mA cm    

    

* Structural Regulation of NiFe LDH under Spontaneous Corrosion to Enhance the Oxygen Evolution Properties  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400977781
:TOPICS: Corrosion Inhibitors and Protection Mechanisms
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202400640")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400977781"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400977781"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400977781"))][Get cited by]]

OpenAlex: https://openalex.org/W4400977781 (Open access: False)
    
[[https://openalex.org/A5090235347][Yingjun Ma]], [[https://openalex.org/A5104128049][Hangning Liu]], [[https://openalex.org/A5062220756][Lin Wang]], [[https://openalex.org/A5035825835][Changhui Sun]], [[https://openalex.org/A5100683018][Liangyu Gong]], [[https://openalex.org/A5100440149][Jie Wang]], [[https://openalex.org/A5009593753][Jiangmin Jiang]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202400640 
     
Electrochemical water splitting holds promise for sustainable hydrogen production but restricted by the sluggish reaction kinetics at the anodic oxygen evolution. Herein, we present a room-temperature spontaneous corrosion strategy to convert inexpensive iron (Fe) on iron foam substrates into highly active and stable self-supporting nickel iron layered hydroxide (NiFe LDH) catalysts. The corrosion evolution mechanisms are elucidated combining ex-situ scanning electron microscopy (SEM) and X-ray photo electron spectroscopy (XPS) techniques, demonstrating precise control over the concentration of Ni2+ and reaction time to achieve controllable micro-structures of NiFe LDH. Taking advantage of the self-supporting morphology and hierarchical micro-/nano- structure, the NiFe LDH with optimized Ni2+ concentration and reaction time exhibits significant small overpotentials of 160 mV and 200 mV for the OER at current densities of 10 mA cm-2 and 100 mA cm-2 respectively, showcasing excellent OER activities. Furthermore, this catalyst demonstrates superior reaction kinetics, high electrochemical stability, and excellent integral water splitting performance when coupled with a commercial Pt/C cathode. The energy-efficient, cost-effective, and scalable spontaneous corrosion strategy opens new avenues for the development of high-electrochemical-interface catalysts.    

    

* Manipulating Dual-Metal Catalytic Activities toward Organic Upgrading in Upcycling Plastic Wastes with Inhibited Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400978536
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsnano.4c04219")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400978536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400978536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400978536"))][Get cited by]]

OpenAlex: https://openalex.org/W4400978536 (Open access: False)
    
[[https://openalex.org/A5087202662][Dengke Xiong]], [[https://openalex.org/A5100944630][Xiaoyang He]], [[https://openalex.org/A5103160714][Xuan Liu]], [[https://openalex.org/A5101999480][Kaiyan Zhang]], [[https://openalex.org/A5054193824][Zhentao Tu]], [[https://openalex.org/A5100737528][Jianying Wang]], [[https://openalex.org/A5100673667][Shi‐Gang Sun]], [[https://openalex.org/A5076251832][Zuofeng Chen]], ACS Nano. None(None)] 2024. https://doi.org/10.1021/acsnano.4c04219 
     
Electrorefinery of polybutylene terephthalate (PBT) waste plastic, specifically conversion of a PBT-derived 1,4-butanediol (BDO) monomer into value-added succinate coupled with H    

    

* High performance oxygen reduction and evolution reactions by graphitization of nickel –cobalt framework system  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400981045
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.07.309")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400981045"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400981045"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400981045"))][Get cited by]]

OpenAlex: https://openalex.org/W4400981045 (Open access: False)
    
[[https://openalex.org/A5061786851][Karim Kakaei]], [[https://openalex.org/A5069772071][A. Rahmati]], [[https://openalex.org/A5105065171][Mohammad Ghadiri]], [[https://openalex.org/A5105065172][Fatemeh Asgharnezhad]], International Journal of Hydrogen Energy. 81(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.07.309 
     
No abstract    

    

* Copper dopants facilitated generation of high-valent cobalt sites for improved oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400982018
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4qi01507j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400982018"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400982018"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400982018"))][Get cited by]]

OpenAlex: https://openalex.org/W4400982018 (Open access: False)
    
[[https://openalex.org/A5072916605][Jingrui Han]], [[https://openalex.org/A5009913485][Jieshu Zhou]], [[https://openalex.org/A5100397032][Hao Zhang]], [[https://openalex.org/A5100408823][Haibin Wang]], [[https://openalex.org/A5071442579][Kangning Liu]], [[https://openalex.org/A5029872654][Xuhui Sun]], [[https://openalex.org/A5100359387][Lihua Liu]], [[https://openalex.org/A5077003796][Hongyan Liang]], Inorganic Chemistry Frontiers. None(None)] 2024. https://doi.org/10.1039/d4qi01507j 
     
Developing a reliable strategy to adjust dynamic reconstruction and formation of active oxygen species on electrocatalyst surfaces is crucial for enhancing OER performance and still needs further elaborate elucidation. Here,...    

    

* In-situ evolution of bulk-active γ-CoOOH with immobilized Gd dopants enabling an efficient oxygen evolution electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400986166
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nr01743a")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400986166"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400986166"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400986166"))][Get cited by]]

OpenAlex: https://openalex.org/W4400986166 (Open access: True)
    
[[https://openalex.org/A5073349735][Tianjue Hou]], [[https://openalex.org/A5036312417][Ruotao Yang]], [[https://openalex.org/A5058016226][Jiaxin Xu]], [[https://openalex.org/A5056970641][Xiaodie He]], [[https://openalex.org/A5101804437][Hongyuan Yang]], [[https://openalex.org/A5009720807][Prashanth W. Menezes]], [[https://openalex.org/A5029864603][Ziliang Chen]], Nanoscale. None(None)] 2024. https://doi.org/10.1039/d4nr01743a 
     
Promoting the in-situ reconstruction of transition metal (TM)-based precatalysts into low-crystalline and well-modified TM (oxy)hydroxides (TMOxHy) during alkaline oxygen evolution reaction (OER) is crucial for enhancing their catalytic performances. In...    

    

* Surface oxygen engineered ZnCo2O4 planar hybrid supercapacitor electrode for high energy applications  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400986943
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2024.112954")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400986943"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400986943"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400986943"))][Get cited by]]

OpenAlex: https://openalex.org/W4400986943 (Open access: False)
    
[[https://openalex.org/A5031660043][Muthukumar Ganesan]], [[https://openalex.org/A5009991260][Srinivasan Alagar]], [[https://openalex.org/A5049532172][Vivek Bagchi]], [[https://openalex.org/A5060879980][Shakkthivel Piraman]], Journal of Energy Storage. 98(None)] 2024. https://doi.org/10.1016/j.est.2024.112954 
     
No abstract    

    

* Iron doping enhances ZIF-67 based hierarchical carbon bifunction catalyst for oxygen reduction and evolution reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400986969
:TOPICS: Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.est.2024.113004")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400986969"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400986969"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400986969"))][Get cited by]]

OpenAlex: https://openalex.org/W4400986969 (Open access: False)
    
[[https://openalex.org/A5012686674][Kanjun Sun]], [[https://openalex.org/A5102222625][Xiaofei Lei]], [[https://openalex.org/A5087315070][Xuan Xie]], [[https://openalex.org/A5100431492][Wenjuan Li]], [[https://openalex.org/A5012205983][Wenbo Hou]], [[https://openalex.org/A5032007926][Hui Peng]], [[https://openalex.org/A5101063054][Guofu Ma]], Journal of Energy Storage. 98(None)] 2024. https://doi.org/10.1016/j.est.2024.113004 
     
No abstract    

    

* Built-in electric field construction and lattice oxygen activation for boosting alkaline electrochemical water/seawater oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401002555
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.154279")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401002555"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401002555"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401002555"))][Get cited by]]

OpenAlex: https://openalex.org/W4401002555 (Open access: False)
    
[[https://openalex.org/A5100352811][Xinyu Wang]], [[https://openalex.org/A5100606297][Xu Yu]], [[https://openalex.org/A5045338445][Pinyi He]], [[https://openalex.org/A5067123324][Guohui Yang]], [[https://openalex.org/A5011704577][Fu Qin]], [[https://openalex.org/A5088442952][Yongkang Yao]], [[https://openalex.org/A5031277854][Lili Ren]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.154279 
     
No abstract    

    

* Engineering Ru‐Au‐Mn Trimetallic Nanostructure for High‐Performance Acidic Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401006709
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202400751")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401006709"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401006709"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401006709"))][Get cited by]]

OpenAlex: https://openalex.org/W4401006709 (Open access: False)
    
[[https://openalex.org/A5003384545][Minna Cao]], [[https://openalex.org/A5091896736][Yuhang Zhang]], [[https://openalex.org/A5085467179][Shuai Yue]], [[https://openalex.org/A5078414235][Jun Liang]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202400751 
     
Developing highly efficient and stable electrocatalysts in acidic media is essential for proton exchange membrane water electrolyzers (PEMWEs). Especially for oxygen evolution reaction (OER), high overpotential is needed to overcome the high thermodynamic energy barrier of water splitting. Herein, we report a high‐efficiency self‐supported ternary alloy OER catalyst with high activity and good durability in acidic electrolytes by a simple electrodeposition method. The as‐prepared electrocatalyst consists of Ru, Au, and Mn alloy which is deposited on the carbon fiber paper (denoted as RuAuMn‐CFP). The RuAuMn‐CFP exhibits superior activity and only requires an overpotential of 131 mV at 10 mA cm−2 and outstanding stability of 30 h (10 mA cm−2) in acidic media, which outperforms the commercial Ru/C and Ir/C catalysts. Besides, at an overpotential of 140 mV, the RuAuMn‐CFP catalyst exhibited a remarkable mass activity of 29.63 mA/mg for OER. It is 7.9 times and 23.8 times higher than the commercial Ru/C and Ir/C catalysts (3.73 mA/mg, 1.24 mA/mg, respectively).    

    

* Hexavalent iridium boosts oxygen evolution performance  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401014289
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.greenca.2024.07.003")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401014289"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401014289"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401014289"))][Get cited by]]

OpenAlex: https://openalex.org/W4401014289 (Open access: True)
    
[[https://openalex.org/A5099843342][Mengtian Huo]], [[https://openalex.org/A5034644483][Y. T. Liang]], [[https://openalex.org/A5105099433][Kaichi Qin]], [[https://openalex.org/A5086300086][Guanzhi Wang]], [[https://openalex.org/A5078288522][Zihao Xing]], [[https://openalex.org/A5050931062][Jinfa Chang]], Green Carbon. None(None)] 2024. https://doi.org/10.1016/j.greenca.2024.07.003 
     
No abstract    

    

* Titanium Dioxide Induced Nickel-iron Alloy-based Precatalyst towards Efficient and Durable Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401025947
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.175729")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401025947"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401025947"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401025947"))][Get cited by]]

OpenAlex: https://openalex.org/W4401025947 (Open access: False)
    
[[https://openalex.org/A5102312625][Ran Qiao]], [[https://openalex.org/A5100324026][Kai Zhang]], [[https://openalex.org/A5008202465][Shuaichong Wei]], [[https://openalex.org/A5101388310][Hongtao Bai]], [[https://openalex.org/A5100773482][Xiangchao Meng]], [[https://openalex.org/A5046850864][Jingde Li]], [[https://openalex.org/A5100741974][Guihua Liu]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.175729 
     
No abstract    

    

* Quantifying Stern Layer Water Alignment Prior to and During the Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401026900
:TOPICS: Quantum Coherence in Photosynthesis and Aqueous Systems, Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2023-m9d1z-v4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401026900"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401026900"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401026900"))][Get cited by]]

OpenAlex: https://openalex.org/W4401026900 (Open access: True)
    
[[https://openalex.org/A5085342735][Raiden Speelman]], [[https://openalex.org/A5054512446][Franz M. Geiger]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2023-m9d1z-v4  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/66a28abd5101a2ffa809f6ed/original/quantifying-stern-layer-water-alignment-prior-to-and-during-the-oxygen-evolution.pdf][pdf]])
     
While water's oxygen is the electron source in the industrially important oxygen evolution reaction, the strong absorber problem clouds our view of how the Stern layer water molecules orient themselves in response to applied potentials. Here, we report nonlinear optical measurements on nickel electrodes held at pH 13 indicating a disorder-to-order transition in the Stern layer water molecules prior to the onset of Faradaic current. A full water monolater (1.1 x 10^15 cm-2) aligns with oxygen atoms pointing towards the electrode at +0.8 V and the associated work is 80 kJ mol-1. Our experiments identify water flipping energetics as a target for understanding overpotentials, advance molecular electrochemistry, provide benchmarks for electrical double layer models, and serve as a diagnostic tool for understanding electrocatalysis.    

    

* Minimal Doping Approach to Activate Lattice Oxygen Participation in K2WO4 Electrocatalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401027067
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apcatb.2024.124423")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401027067"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401027067"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401027067"))][Get cited by]]

OpenAlex: https://openalex.org/W4401027067 (Open access: False)
    
[[https://openalex.org/A5020359856][Selvaraj Seenivasan]], [[https://openalex.org/A5017820325][M. H. Kim]], [[https://openalex.org/A5033014275][Jeong Woo Han]], [[https://openalex.org/A5078799389][Do‐Heyoung Kim]], Applied Catalysis B Environment and Energy. None(None)] 2024. https://doi.org/10.1016/j.apcatb.2024.124423 
     
No abstract    

    

* Oxygen-deficient annealing boosts performance of CoNiFe oxide electrocatalyst in oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401032956
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcat.2024.115675")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401032956"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401032956"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401032956"))][Get cited by]]

OpenAlex: https://openalex.org/W4401032956 (Open access: False)
    
[[https://openalex.org/A5000842558][Thi-Thu-Hien Pham]], [[https://openalex.org/A5066261986][Michaela Plevová]], [[https://openalex.org/A5059009629][Stephan Bartling]], [[https://openalex.org/A5067238534][Nils Rockstroh]], [[https://openalex.org/A5032019000][Armin Springer]], [[https://openalex.org/A5004773873][Adam Slabon]], [[https://openalex.org/A5064651777][Jaromír Hnát]], [[https://openalex.org/A5055688484][Annette‐Enrica Surkus]], [[https://openalex.org/A5062902347][Robert Francke]], Journal of Catalysis. None(None)] 2024. https://doi.org/10.1016/j.jcat.2024.115675 
     
No abstract    

    

* Cation-Triggered Growth of Nanowires for Enhanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401034705
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.inorgchem.4c02315")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401034705"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401034705"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401034705"))][Get cited by]]

OpenAlex: https://openalex.org/W4401034705 (Open access: False)
    
[[https://openalex.org/A5100371313][Sheng Wang]], [[https://openalex.org/A5044457554][Weiying Ye]], [[https://openalex.org/A5100723123][Zhilin Zhang]], [[https://openalex.org/A5004335358][Yuan‐Zhao Hua]], [[https://openalex.org/A5050826407][Chenyang Cai]], [[https://openalex.org/A5100714826][Zhenghao Zhang]], [[https://openalex.org/A5060906248][Yitian Wu]], [[https://openalex.org/A5100342686][Kui Wang]], [[https://openalex.org/A5103565409][Wenshu Yang]], [[https://openalex.org/A5041067396][Weidong Shi]], [[https://openalex.org/A5038699851][Jinhui Hao]], Inorganic Chemistry. None(None)] 2024. https://doi.org/10.1021/acs.inorgchem.4c02315 
     
The oxygen evolution reaction (OER), which occurs in a variety of energy-related devices, necessitates optimization of the reaction pathways for efficient and scalable deployment. Nevertheless, fully harnessing the advanced structure of synthetic electrocatalysts remains a significant challenge due to the inevitable surface reconstruction process during OER. Here we present an efficient and flexible method to control the surface reconstruction process by engineering an electrolyte containing trace Co    

    

* Core–Shell Co‐CoxP Nanoparticle‐Embedded N‐Doped Carbon Nanowhiskers Hollow Sphere for Efficient Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401035151
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adfm.202409390")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401035151"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401035151"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401035151"))][Get cited by]]

OpenAlex: https://openalex.org/W4401035151 (Open access: False)
    
[[https://openalex.org/A5068308955][Wei Zhu]], [[https://openalex.org/A5100727143][Wenhui Hu]], [[https://openalex.org/A5012915643][Ying Wei]], [[https://openalex.org/A5066988739][Yongcai Zhang]], [[https://openalex.org/A5019781253][Kunming Pan]], [[https://openalex.org/A5101844277][Songtao Zhang]], [[https://openalex.org/A5090645667][Xinxin Hang]], [[https://openalex.org/A5089682316][Mingbo Zheng]], [[https://openalex.org/A5100629513][Huan Pang]], Advanced Functional Materials. None(None)] 2024. https://doi.org/10.1002/adfm.202409390 
     
Abstract The development of efficient oxygen evolution reaction (OER) electrocatalysts is critical to overcome the efficiency bottleneck in hydrogen generation via water electrolysis. Hollow nanostructured materials have emerged as a hot topic for electrocatalysis research because of their advantages, including abundant active sites, a large contact area between the catalyst and the electrolyte, and a short transmission path. As highly efficient and stable OER electrocatalysts, cobalt‐based nanostructured materials have attracted more and more attention. In this work, cobalt metal/cobalt phosphides/nitrogen‐doped carbon composites (Co‐Co x P/NC) with a hierarchical hollow structure are designed by using hollow ZIF‐67 microspheres as precursors. By coating ZIF‐8 on the surface of hollow ZIF‐67 microspheres and further carbonizing, carbon nanowhiskers are successfully formed on the surface of hollow carbon spheres under the catalytic effect of Co nanoparticles at a high temperature. In the subsequent phosphating process, solid Co nanocrystalline particles are transformed into core–shell CoP and Co 2 P nanoparticles on account of the Kirkendall effect. Through the optimization of the microstructure of the material and the synergistic effect of transition metal, transition metal phosphide, and nitrogen doping, the overpotential of the optimal material is only 287 mV at 10 mA cm −2 current density in 1 m KOH.    

    

* Effect of Different N/C Coordination Electronic Structures on the Activity of Bifunctional Rare-Earth Ytterbium Electrocatalysts for Oxygen Electrodes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401035209
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.langmuir.4c01797")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401035209"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401035209"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401035209"))][Get cited by]]

OpenAlex: https://openalex.org/W4401035209 (Open access: False)
    
[[https://openalex.org/A5102549730][Tao Xu]], [[https://openalex.org/A5102849871][Daomiao Wang]], [[https://openalex.org/A5087429872][Qiming Fu]], [[https://openalex.org/A5044538497][Chao Liu]], Langmuir. None(None)] 2024. https://doi.org/10.1021/acs.langmuir.4c01797 
     
The research and development of bifunctional electrocatalysts for the oxygen electrode is of great significance to solve the problem of electrochemical energy. Herein, the effect of different structure-activity relationships on the performance of YbN    

    

* FeNi‐LDH COATED WITH ORANGE‐PEEL CARBON AEROGEL FOR OXYGEN EVOLUTION REACTION  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401038504
:TOPICS: Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cssc.202401276")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401038504"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401038504"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401038504"))][Get cited by]]

OpenAlex: https://openalex.org/W4401038504 (Open access: False)
    
[[https://openalex.org/A5017659349][Hai Jia]], [[https://openalex.org/A5045814743][Peng-Cheng Ji]], [[https://openalex.org/A5100773000][Yang Teng]], ChemSusChem. None(None)] 2024. https://doi.org/10.1002/cssc.202401276 
     
In this work, the waste orange-peel was used as carbon source, and the orange-peel derived carbon material can be obtained through simple pyrolysis. Then, we designed the structure of orange-peel carbon aerogel grown on iron-nickel layered double hydroxides in situ to achieve the effect of carbon coating (FeNi-LDH/CA). The oxygen evolution reaction catalytic performance of FeNi-LDH/CA is excellent, far exceeding that of commercial RuO2. In 1 M KOH, the overpotential of FeNi-LDH/CA is only 250 mV (10 mA cm-2), obviously better than that of commercial RuO2 (295 mV). FeNi-LDH/CA shows good cycling stability, and after long-term i-t testing, the performance only decays by 3% after running at 100 mA cm-2 for 100 h. When used as an anode, the voltage of water-splitting is only 1.48 V at 10 mA cm-2. The rechargeable liquid zinc-air battery based on Pt/C-FeNi-LDH/CA catalyst has higher open-circuit voltage (1.543 V) and galvanostatic discharge capacity at 1.23 V (830 min, 10 mA cm-2). Moreover, the zinc-air battery based on Pt/C-FeNi-LDH/CA has a small charge-discharge voltage gap (0.65 V) at 10 mA cm-2, after 200 consecutive cycles (66 h), the charge-discharge voltage gap only increased by about 30 mV, indicating good cycling stability.    

    

* Selection of metal halide redox mediator suitable for lithium air battery by evaluating oxygen evolution efficiency  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401040180
:TOPICS: Conducting Polymer Research, Lithium-ion Battery Management in Electric Vehicles
:PUBLICATION_DATE: 2024-06-30
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.53619/kobs.2024.6.4.1.58")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401040180"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401040180"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401040180"))][Get cited by]]

OpenAlex: https://openalex.org/W4401040180 (Open access: False)
    
[[https://openalex.org/A5103072955][Juhyoung Kim]], [[https://openalex.org/A5100359367][Dongwook Kim]], Journal of the Korean Battery Society. 4(1)] 2024. https://doi.org/10.53619/kobs.2024.6.4.1.58 
     
No abstract    

    

* Promoting Surface Reconstruction in Spinel Oxides via Tetrahedral‐Octahedral Phase Boundary Construction for Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400981749
:TOPICS: Emergent Phenomena at Oxide Interfaces, Catalytic Nanomaterials, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202409912")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400981749"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400981749"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400981749"))][Get cited by]]

OpenAlex: https://openalex.org/W4400981749 (Open access: False)
    
[[https://openalex.org/A5070625824][Anqi Zou]], [[https://openalex.org/A5084950399][Chao Wu]], [[https://openalex.org/A5076586440][Qi Zhang]], [[https://openalex.org/A5100617553][Ying Tang]], [[https://openalex.org/A5100329144][Junhua Li]], [[https://openalex.org/A5050445254][Hecheng Meng]], [[https://openalex.org/A5101800679][Zhen Wang]], [[https://openalex.org/A5059436219][Caozheng Diao]], [[https://openalex.org/A5056256510][Zhi Gen Yu]], [[https://openalex.org/A5034827883][Junmin Xue]], [[https://openalex.org/A5031292832][Shibo Xi]], [[https://openalex.org/A5100730229][Xiaopeng Wang]], [[https://openalex.org/A5102812387][Jiagang Wu]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202409912 
     
Understanding the origin of surface reconstruction is crucial for developing highly efficient lattice oxygen oxidation mechanism (LOM) based spinel oxides. Traditionally, the reconstruction has been achieved through electrochemical procedures, such as cyclic voltammetry (CV), linear sweep voltammetry (LSV). In this work, we found that the surface reconstruction in LOM‐based CoFe0.25Al1.75O4 catalyst was an irreversible oxygen redox chemical reaction. And a lower oxygen vacancy formation energy (EO‐V) could benefit the combination of the activated lattice oxygen atoms with adsorbed water molecular. Motivated by this finding, a strategy of phase boundary construction from Co tetrahedral to octahedral was employed to decrease EO‐V in CoFe0.25Al1.75O4. The results showed that as the Co octahedral occupancy ratio rose to 64%, a 3.5 nm‐thick reconstructed layer formed on the catalyst surface with a 158 mV decrease in overpotential. Further experiments indicated that the coexistence of tetrahedral‐octahedral (O‐T) phase would result in lattice mismatch, promoting non‐bonding oxygen states and lowering EO‐V. Then more active lattice oxygen combined with H2O molecules to generate hydroxide ions (OH‐), followed by soluble cation leaching, which enhanced the reconstruction process. This work provided new insights into the relationship between the intrinsic structure of pre‐catalysts and surface reconstruction in LOM‐based spinel electrocatalysts.    

    

* Promoting Surface Reconstruction in Spinel Oxides via Tetrahedral‐Octahedral Phase Boundary Construction for Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400981750
:TOPICS: Catalytic Nanomaterials, Emergent Phenomena at Oxide Interfaces, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202409912")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400981750"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400981750"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400981750"))][Get cited by]]

OpenAlex: https://openalex.org/W4400981750 (Open access: False)
    
[[https://openalex.org/A5070625824][Anqi Zou]], [[https://openalex.org/A5084950399][Chao Wu]], [[https://openalex.org/A5076586440][Qi Zhang]], [[https://openalex.org/A5100617553][Ying Tang]], [[https://openalex.org/A5100329144][Junhua Li]], [[https://openalex.org/A5050445254][Hecheng Meng]], [[https://openalex.org/A5101800679][Zhen Wang]], [[https://openalex.org/A5059436219][Caozheng Diao]], [[https://openalex.org/A5056256510][Zhi Gen Yu]], [[https://openalex.org/A5034827883][Junmin Xue]], [[https://openalex.org/A5031292832][Shibo Xi]], [[https://openalex.org/A5100730229][Xiaopeng Wang]], [[https://openalex.org/A5102812387][Jiagang Wu]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202409912 
     
Understanding the origin of surface reconstruction is crucial for developing highly efficient lattice oxygen oxidation mechanism (LOM) based spinel oxides. Traditionally, the reconstruction has been achieved through electrochemical procedures, such as cyclic voltammetry (CV), linear sweep voltammetry (LSV). In this work, we found that the surface reconstruction in LOM-based CoFe0.25Al1.75O4 catalyst was an irreversible oxygen redox chemical reaction. And a lower oxygen vacancy formation energy (EO-V) could benefit the combination of the activated lattice oxygen atoms with adsorbed water molecular. Motivated by this finding, a strategy of phase boundary construction from Co tetrahedral to octahedral was employed to decrease EO-V in CoFe0.25Al1.75O4. The results showed that as the Co octahedral occupancy ratio rose to 64%, a 3.5 nm-thick reconstructed layer formed on the catalyst surface with a 158 mV decrease in overpotential. Further experiments indicated that the coexistence of tetrahedral-octahedral (O-T) phase would result in lattice mismatch, promoting non-bonding oxygen states and lowering EO-V. Then more active lattice oxygen combined with H2O molecules to generate hydroxide ions (OH-), followed by soluble cation leaching, which enhanced the reconstruction process. This work provided new insights into the relationship between the intrinsic structure of pre-catalysts and surface reconstruction in LOM-based spinel electrocatalysts.    

    

* A nanocoral like carbon composite based on dual-MOFs for catalytic reduction and evolution of oxygen  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400966451
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Electrocatalysis for Energy Conversion, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-09-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mtchem.2024.102213")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400966451"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400966451"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400966451"))][Get cited by]]

OpenAlex: https://openalex.org/W4400966451 (Open access: False)
    
[[https://openalex.org/A5030872805][Junyuan Zhang]], [[https://openalex.org/A5100431696][Wei Liu]], [[https://openalex.org/A5078976221][Linfeng Liang]], [[https://openalex.org/A5012730184][Ziwei Deng]], [[https://openalex.org/A5100764009][Changyu Liu]], [[https://openalex.org/A5101790140][Xiaolong Xu]], [[https://openalex.org/A5043698418][Jianbo Jia]], Materials Today Chemistry. 40(None)] 2024. https://doi.org/10.1016/j.mtchem.2024.102213 
     
No abstract    

    

* Co-Zn single atoms anchored carbon nanotubes derived from anti-perovskite carbides for boosted hydrogen evolution and oxygen reduction reactions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400934242
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.154255")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400934242"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400934242"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400934242"))][Get cited by]]

OpenAlex: https://openalex.org/W4400934242 (Open access: False)
    
[[https://openalex.org/A5087941629][Liangliang Feng]], [[https://openalex.org/A5024135281][Mengfei Zhou]], [[https://openalex.org/A5032891578][Danyang He]], [[https://openalex.org/A5101237597][Hongyan Yin]], [[https://openalex.org/A5103221787][Yixuan Huang]], [[https://openalex.org/A5025928722][Liyun Cao]], [[https://openalex.org/A5002978063][Yuan Fang]], [[https://openalex.org/A5087368019][Dewei Chu]], [[https://openalex.org/A5009315315][Yipu Liu]], [[https://openalex.org/A5100334137][Hui Chen]], [[https://openalex.org/A5100360760][Guodong Li]], [[https://openalex.org/A5101608697][Jianfeng Huang]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.154255 
     
No abstract    

    

* Transparent TiO2 nanotubes supporting silver sulfide for photoelectrochemical water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401029688
:TOPICS: Photocatalysis and Solar Energy Conversion, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nr01440e")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401029688"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401029688"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401029688"))][Get cited by]]

OpenAlex: https://openalex.org/W4401029688 (Open access: False)
    
[[https://openalex.org/A5043329735][Wiktoria Lipińska]], [[https://openalex.org/A5014026736][Stefania Wolff]], [[https://openalex.org/A5089248762][Katharina E. Dehm]], [[https://openalex.org/A5019815848][Simon Hager]], [[https://openalex.org/A5003469307][Justyna Gumieniak]], [[https://openalex.org/A5079638281][Agnieszka Kramek]], [[https://openalex.org/A5036160372][Ryan W. Crisp]], [[https://openalex.org/A5066606506][Emerson Coy]], [[https://openalex.org/A5039043497][Katarzyna Grochowska]], [[https://openalex.org/A5082279488][Katarzyna Siuzdak]], Nanoscale. None(None)] 2024. https://doi.org/10.1039/d4nr01440e 
     
Differences between photoelectrochemical and electrochemical activity were thoroughly investigated for the oxygen evolution reaction mediated by Ag 2 S deposited on two types of ordered titania substrates. Titanium dioxide in the form...    

    

* Universal synthesis of coral-like Ternary MOF-Derived Sulfides as efficient OER electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400969813
:TOPICS: Innovations in Organic Synthesis Reactions, Desulfurization Technologies for Fuels, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4qi01725k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400969813"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400969813"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400969813"))][Get cited by]]

OpenAlex: https://openalex.org/W4400969813 (Open access: False)
    
[[https://openalex.org/A5059102739][Tianpeng Liu]], [[https://openalex.org/A5056349795][Yangping Zhang]], [[https://openalex.org/A5082084628][Jun Yu]], [[https://openalex.org/A5006071289][Mengyun Hu]], [[https://openalex.org/A5010896261][Zhengying Wu]], [[https://openalex.org/A5090080711][Xiao Wei]], [[https://openalex.org/A5079994695][Shudi Yu]], [[https://openalex.org/A5004666624][Yukou Du]], Inorganic Chemistry Frontiers. None(None)] 2024. https://doi.org/10.1039/d4qi01725k 
     
The strategy of synthesizing a high-efficiency oxygen evolution reaction (OER) catalysts by sacrificing metal-organic frameworks (MOF) templates is considered promising. However, few reports have focused on improving the intrinsic electrocatalytic...    

    

* Clarification of Degradation Mechanisms of the OER Activity of Ir-Based Electrocatalyst with Potentiodynamic Accelerated Stress Test  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400937411
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/1945-7111/ad6716")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400937411"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400937411"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400937411"))][Get cited by]]

OpenAlex: https://openalex.org/W4400937411 (Open access: True)
    
[[https://openalex.org/A5028577447][Raghunandan Sharma]], [[https://openalex.org/A5044593278][P. Morgen]], [[https://openalex.org/A5057716057][Darko Makovec]], [[https://openalex.org/A5082111268][Sašo Gyergyek]], [[https://openalex.org/A5032516491][Shuang Ma Andersen]], Journal of The Electrochemical Society. None(None)] 2024. https://doi.org/10.1149/1945-7111/ad6716 
     
Abstract It is vital to understand the degradation mechanisms for the oxygen evolution reaction (OER) activity under acidic electrolyser operating conditions. To this end, we have studied a commercial benchmark Ir-Oxide electrocatalyst during an accelerated stress test (AST) of potential cycling (2000 cycles at 100 mV/s) between 1.0 and 1.7 V in 0.1 M HClO4. The OER activity degradation (>60%) has been investigated due to (i) bulk structure changes from metal dissolution, (ii) particle growth and, (iii) surface chemical state changes. Microscopic images of the Ir-Oxide catalyst before and after the AST show no significant change in the particle size or agglomeration; moreover, negligible mass loss of the element. Therefore, the OER activity degradation is found to be dominantly (99%) associated with changes of the surface chemical state of Ir, i.e., increase in the Ir4+/Ir3+ ratio at the surface of Ir-Oxide during the AST.    

    

* Single-atom nickel on defective g-C4N3 as a promising bifunctional electrocatalyst for the OER and ORR: a first-principles analysis  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401007558
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1088/2053-1591/ad674b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401007558"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401007558"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401007558"))][Get cited by]]

OpenAlex: https://openalex.org/W4401007558 (Open access: True)
    
[[https://openalex.org/A5101276901][Teng fei Gao]], [[https://openalex.org/A5102957728][Xiao-Kuan Wu]], [[https://openalex.org/A5066425442][Dan Wen]], [[https://openalex.org/A5100846080][Xin Zhi]], [[https://openalex.org/A5052495835][Yu Fang]], [[https://openalex.org/A5100456542][Liang Wang]], [[https://openalex.org/A5100436765][Jie Zhang]], [[https://openalex.org/A5101165186][Jimmy Yun]], Materials Research Express. None(None)] 2024. https://doi.org/10.1088/2053-1591/ad674b 
     
Abstract Searching for inexpensive and highly active materials to replace noble metals for oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) is an important challenge. The two-dimensional semi-metallic carbon nitride g-C4N3 is an excellent candidate for electrochemical reactions owing to its eminent conductivity and stability. Here, using density functional theory (DFT) a series of low-budget non-noble transition metal single-atom (SAC) loaded on the g-C4N3 (named as TM@C4N3, TM=Cr, Mn, Fe, Co, Ni, Cu) were investigated as electrocatalysts for OER and ORR. Ni@C4N3 shows an enormous application potential as electrode material, with OER and ORR overpotentials of 0.59 V and 0.23 V, respectively. The second lowest binding energy between Ni and support g-C4N3 indicates that Ni@C4N3 possesses good overall stability. The d-band center as well as metal valence as the descriptor exhibit good agreement with the adsorption energy of the intermediate. A linear relationship exists among the adsorption energies of the three intermediates O, OH, and OOH, given the similarity that they are all bonded to the metal through one oxygen atom. By adjusting the adsorption energy of these intermediates, the catalytic activity of electrocatalysts can be tuned for OER and ORR. This study confirmed that Ni@C4N3 is a good bifunctional catalyst and provides important guidance for the design of bifunctional electrocatalysts for OER and ORR.    

    

* Modulation strategies of electrocatalysts for 5-hydroxymethylfurfural oxidation-assisted water splitting  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400961728
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Conversion of Biomass to Fuels and Chemicals, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.20517/microstructures.2023.93")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400961728"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400961728"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400961728"))][Get cited by]]

OpenAlex: https://openalex.org/W4400961728 (Open access: True)
    
[[https://openalex.org/A5074690414][Tongxue Zhang]], [[https://openalex.org/A5009292056][Hua Yin]], [[https://openalex.org/A5100770480][Fumin Wang]], [[https://openalex.org/A5103165623][Wenxian Liu]], [[https://openalex.org/A5077918494][Xinyuan He]], [[https://openalex.org/A5100318555][Qian Liu]], [[https://openalex.org/A5033775732][Xubin Zhang]], [[https://openalex.org/A5067268817][Xijun Liu]], Microstructures. 4(3)] 2024. https://doi.org/10.20517/microstructures.2023.93 
     
To address energy shortages and environmental issues, prioritizing renewable energy development and usage is crucial. Employing renewable sources for water electrolysis offers a sustainable method for hydrogen generation. Reducing the water electrolysis potential is vital for efficient clean energy conversion and storage. Substituting the anodic oxygen evolution reaction in conventional hydrogen production from water electrolysis with the more thermodynamically favorable 5-hydroxymethylfurfural (HMF) oxidation reaction can greatly decrease overpotential and yield the valuable product 2,5-furan dicarboxylic acid. The key to this process is developing effective electrocatalysts to minimize the potential of the HMF electrooxidation-hydrogen production system. Therefore, this review provides a comprehensive introduction to the modulation strategies that affect the electronic and geometric structure of electrocatalysts for HMF oxidation-assisted water splitting. The strategies encompass heteroatom doping, defect projection, interface engineering, structural design, and multi-metal synergies. The catalysts are assessed from various angles, encompassing structural characterization, reaction mechanisms, and electrochemical performance. Finally, current challenges in the catalyst design and potential development of this promising field are proposed.    

    

* CoFe2O4@N‐CNH as Bifunctional Hybrid Catalysts for Rechargeable Zinc‐Air Batteries  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400935985
:TOPICS: Aqueous Zinc-Ion Battery Technology, Materials for Electrochemical Supercapacitors, Lithium-ion Battery Technology
:PUBLICATION_DATE: 2024-07-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/admi.202400415")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400935985"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400935985"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400935985"))][Get cited by]]

OpenAlex: https://openalex.org/W4400935985 (Open access: True)
    
[[https://openalex.org/A5002130362][Sudheer Kumar Yadav]], [[https://openalex.org/A5022119158][Daniel Deckenbach]], [[https://openalex.org/A5011582677][Sandeep Yadav]], [[https://openalex.org/A5062169154][Christian Njel]], [[https://openalex.org/A5031871116][Vanessa Trouillet]], [[https://openalex.org/A5062201331][Jörg J. Schneider]], Advanced Materials Interfaces. None(None)] 2024. https://doi.org/10.1002/admi.202400415 
     
Abstract Improving the efficiency of bifunctional electrocatalysts is a decisive challenge in the area of long‐lasting rechargeable zinc‐air batteries. Enhancing the catalysts' performance is crucial for advancing zinc‐air batteries. Transition‐metal oxides have emerged as promising non‐precious, noble‐metal‐free catalysts. Herein, a unique precursor directed approach is introduced for preparing a cobalt ferrite@nitrogen doped carbon nanohorns (CoFe 2 O 4 @N‐CNHs) nanohybrid catalyst in a single step annealing process involving stoichiometric amounts of single‐source cobalt and iron molecular precursors and carbon nanohorns (CNHs) under an argon/ammonia (Ar/NH 3 ) atmosphere. This procedure enables a simultaneous CoFe 2 O 4 ferrite synthesis and nitrogen functionalization of CNHs. The precious metal free nanohybrid CoFe 2 O 4 @N‐CNHs‐30% containing 30% of carbon presents an oxygen reduction reaction (ORR) half wave potential and onset potential comparable to the standard ORR catalyst 20% Pt/C. CoFe 2 O 4 @N‐CNHs‐30% also establishes superior oxygen evolution reaction (OER) performance with a low overpotential and a small Tafel slope than benchmark OER catalyst RuO 2 . Furthermore, the rechargeable zinc‐air battery with the CoFe 2 O 4 @N‐CNHs‐30% nanohybrid as air electrode demonstrates steadier and more durable charge–discharge cycles, and outstanding energy density relative to the state‐of‐the‐art 20% Pt/C‐RuO 2 catalyst.    

    

* Long‐Durability, Surfactant‐Free, and Bifunctional Ir‐Doped Pt3Co/MWCNTs Electrocatalysts towards ORR and OER in Acidic Media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400948633
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/slct.202402029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400948633"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400948633"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400948633"))][Get cited by]]

OpenAlex: https://openalex.org/W4400948633 (Open access: False)
    
[[https://openalex.org/A5100417669][Yan Wang]], [[https://openalex.org/A5100386715][Chuang Li]], [[https://openalex.org/A5035158182][Guangwei Li]], [[https://openalex.org/A5100339632][Xiaoqiang Li]], [[https://openalex.org/A5079149279][Shiping Luo]], [[https://openalex.org/A5102582783][Danmin Xing]], [[https://openalex.org/A5014316928][Changhai Liang]], ChemistrySelect. 9(28)] 2024. https://doi.org/10.1002/slct.202402029 
     
Abstract Developing cost‐effective, high‐performance, and durable electrocatalysts for oxygen reduction reaction (ORR) and oxygen evolution reaction (OER) is pivotal for advancing hydrogen energy conversion and storage technologies. Simultaneously, establishing scalable methods for their production is essential for the widespread adoption of these renewable energy solutions. In this study, we present a successful large‐scale synthesis of surfactant‐free iridium‐doped Pt−cobalt nanoparticles supported on multiwalled carbon nanotubes (Ir−Pt 3 Co/MWCNTs). This composite demonstrates significantly enhanced ORR and OER activity compared to commercial Pt/C and IrO 2 in acidic environments. The Ir−Pt 3 Co/MWCNTs catalyst composite exhibits a low overpotential of 357 mV at 10 mA cm −2 and a remarkable mass activity of 0.594 A/mg Pt . Investigating the influence of Ir doping content on ORR and OER, we found that Pt 3 Co 0.6 Ir 0.4 /MWCNTs showcased the most superior activity in both reactions. We present a reproducible protocol for the synthesis of surfactant‐free Ir−Pt 3 Co nanoparticles supported on MWCNTs, yielding a bifunctional catalyst capable of efficiently catalyzing both ORR and OER with outstanding efficiency and stability in acidic media. Detailed X‐ray photoelectron spectroscopy (XPS) analysis elucidates the electron transfer between atoms, optimizing the electronic structure and adjusting the position of the d‐band. This optimization enhances the electrocatalytic activity and structural stability of the catalysts, contributing to their superior performance in ORR and OER.    

    

* Electrochemical Performance of a Hybrid NiCo2O4@NiFelt Electrode at Different Operating Temperatures and Electrolyte pH  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401015177
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/en17153703")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401015177"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401015177"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401015177"))][Get cited by]]

OpenAlex: https://openalex.org/W4401015177 (Open access: True)
    
[[https://openalex.org/A5030861695][Ataollah Niyati]], [[https://openalex.org/A5057441958][Arianna Moranda]], [[https://openalex.org/A5105099730][Pouya Beigzadeh Arough]], [[https://openalex.org/A5018160528][Federico Navarra]], [[https://openalex.org/A5069334959][Ombretta Paladino]], Energies. 17(15)] 2024. https://doi.org/10.3390/en17153703 
     
Transition metals such as nickel and cobalt as an alternative to Pt and Pd can be used for oxygen evolution reactions (OERs) and hydrogen production reactions (HERs) in alkaline environments, facilitating green hydrogen production as a sustainable alternative to fossil fuels. In this study, an NiCo2O4 catalyst was produced by a sono-hydrothermal method using urea as a hydrolysis agent. The electrochemical performance of the catalyst-coated NiFelt electrode was evaluated at different KOH concentrations (0.25, 0.5, and 1 M) and four operating temperatures in the interval of 20–80 °C. The electrode characteristics were investigated via electrochemical spectroscopy (cyclic voltammetry, EIS, multistep chronopotentiometry, multistep chronoamperometry) using two different reference electrodes (Ag/AgCl and Hg/HgO), to obtain insight into the anodic and cathodic peaks. XRD, SEM, EDS, and TEM analyses confirmed the purity, structure, and nanoscale particle size (20–45 nm) of the NiCo2O4 catalyst. The electrode showed symmetric CV with Ag/AgCl, making this reference electrode more appropriate for capacitance measurements, while Hg/HgO proved advantageous for EIS in alkaline solutions due to reduced noise. The overpotential of the catalyst-coated NiFelt decreased by 108 mV at 10 mA/cm2 compared to bare NiFelt, showing a good potential for its application in anion exchange membranes and alkaline electrolyzers at an industrial scale.    

    

* The Modification of Aluminum Oxide Inclusions in Bearing Steel under Different Cleanliness Conditions by Rare Earth Elements  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401014801
:TOPICS: Thermochemical Software and Databases in Metallurgy, Thermal Barrier Coatings for Gas Turbines, High-Strength Steel Materials
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/met14080861")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401014801"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401014801"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401014801"))][Get cited by]]

OpenAlex: https://openalex.org/W4401014801 (Open access: True)
    
[[https://openalex.org/A5058107332][Ning Wang]], [[https://openalex.org/A5027991565][Wen-zhi Xia]], [[https://openalex.org/A5101486255][Yun Zhou]], [[https://openalex.org/A5102709109][Aijun Deng]], [[https://openalex.org/A5053004252][Guang-da Bao]], [[https://openalex.org/A5087535000][Zhiyou Liao]], [[https://openalex.org/A5071932994][Haichuan Wang]], Metals. 14(8)] 2024. https://doi.org/10.3390/met14080861 
     
The impact of rare earth treatment on the chemical morphology evolution of non-metallic inclusions in bearing steel under different initial cleanliness conditions was studied through simulation. Thermodynamic calculations indicate that at an oxygen content of 0.001%, the evolution route of inclusions with increasing Ce content was Al2O3 → CeAl11O18 + CeAlO3 → CeAlO3 + Ce2O2S → Ce2O2S → Ce2O2S + CeS. As the initial oxygen content decreases, the proportion of CeAlO3 decreases, leading to easier conversion of CeAlO3 to Ce2O2S. Vacuum induction furnace experiments demonstrated that with an oxygen content of 0.001%, an increase in Ce content results in a gradual rise in the proportion of inclusions in steel sized 1~2 μm. In contrast, the proportion of inclusions sized 2~5 μm decreases. Consequently, the overall content of inclusions in steel decreases, along with a reduction in both the number density and average size of inclusions. Introducing bearing steel melt with approximately 0.01% Ce rare earth to bearing steel with initial oxygen contents of 0.0005%, 0.001%, and 0.0015% showed an evolution of inclusions from Ce2O2S and CeS to Ce2O3, CeAlO3, etc. The average inclusion size significantly increased from 0.7 μm to 2.16 μm. Morphologically, the transition of inclusions from precipitated to polymerized forms occurred as the initial oxygen content rose. High-temperature laser confocal microscopy experiments demonstrated that inclusions in low cleanliness conditions tend to agglomerate more than those in high cleanliness conditions, contributing to the increase in average size.    

    

* Dynamic Evolution of Antisite Defect and Coupling Anionic Redox in High‐Voltage Ultrahigh‐Ni Cathode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401037985
:TOPICS: Corrosion Inhibitors and Protection Mechanisms, Hydrogen Embrittlement in Metals and Alloys, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202410326")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401037985"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401037985"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401037985"))][Get cited by]]

OpenAlex: https://openalex.org/W4401037985 (Open access: False)
    
[[https://openalex.org/A5100815082][Kang Wu]], [[https://openalex.org/A5023540032][Peilin Ran]], [[https://openalex.org/A5024336975][Wen Yin]], [[https://openalex.org/A5048079565][Lunhua He]], [[https://openalex.org/A5029977105][Bao‐Tian Wang]], [[https://openalex.org/A5022016300][Jinming Jian]], [[https://openalex.org/A5011501177][Enyue Zhao]], [[https://openalex.org/A5060076875][Jinkui Zhao]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202410326 
     
High-voltage ultrahigh-Ni cathodes (LiNixCoyMn1-x-yO2, x ≥ 0.9) can significantly enhance the energy density and cost-effectiveness of Li-ion batteries beyond current levels. However, severe Li-Ni antisite defects and their undetermined dynamic evolutions during high-voltage cycling limit the further development of these ultrahigh-Ni cathodes. In this study, we quantify the dynamic evolutions of the Li-Ni antisite defect using operando neutron diffraction and reveal its coupling relationship with anionic redox, another critical challenge restricting ultrahigh-Ni cathodes. We detect a clear Ni migration coupled with an unstable oxygen lattice, which accompanies the oxidation of oxygen anions at high voltages. Based on these findings, we propose that minimized Li-Ni antisite defects and controlled Ni migrations are essential for achieving stable high-voltage cycling structures in ultrahigh-Ni cathodes. This is further demonstrated by the optimized ultrahigh-Ni cathode, where reduced dynamic evolutions of the Li-Ni antisite defect effectively inhibit the anionic redox, enhancing the 4.5 V cycling stability.    

    

* Dynamic Evolution of Antisite Defect and Coupling Anionic Redox in High‐Voltage Ultrahigh‐Ni Cathode  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401038097
:TOPICS: Corrosion Inhibitors and Protection Mechanisms, Electrochemical Detection of Heavy Metal Ions, Hydrogen Embrittlement in Metals and Alloys
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202410326")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401038097"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401038097"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401038097"))][Get cited by]]

OpenAlex: https://openalex.org/W4401038097 (Open access: False)
    
[[https://openalex.org/A5100815082][Kang Wu]], [[https://openalex.org/A5023540032][Peilin Ran]], [[https://openalex.org/A5100699028][Wen Yin]], [[https://openalex.org/A5048079565][Lunhua He]], [[https://openalex.org/A5029977105][Bao‐Tian Wang]], [[https://openalex.org/A5022016300][Jinming Jian]], [[https://openalex.org/A5011501177][Enyue Zhao]], [[https://openalex.org/A5060076875][Jinkui Zhao]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202410326 
     
High‐voltage ultrahigh‐Ni cathodes (LiNixCoyMn1−x−yO2, x ≥ 0.9) can significantly enhance the energy density and cost‐effectiveness of Li‐ion batteries beyond current levels. However, severe Li‐Ni antisite defects and their undetermined dynamic evolutions during high‐voltage cycling limit the further development of these ultrahigh‐Ni cathodes. In this study, we quantify the dynamic evolutions of the Li‐Ni antisite defect using operando neutron diffraction and reveal its coupling relationship with anionic redox, another critical challenge restricting ultrahigh‐Ni cathodes. We detect a clear Ni migration coupled with an unstable oxygen lattice, which accompanies the oxidation of oxygen anions at high voltages. Based on these findings, we propose that minimized Li‐Ni antisite defects and controlled Ni migrations are essential for achieving stable high‐voltage cycling structures in ultrahigh‐Ni cathodes. This is further demonstrated by the optimized ultrahigh‐Ni cathode, where reduced dynamic evolutions of the Li‐Ni antisite defect effectively inhibit the anionic redox, enhancing the 4.5 V cycling stability.    

    

* Unique myoglobin adaptation to endothermy and flight since the origin of birds  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401006652
:TOPICS: Hemoglobin Function and Regulation in Vertebrates, Metabolic Theory of Ecology and Climate Change Impacts, Neural Mechanisms of Respiratory Control and Homeostasis
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/1749-4877.12870")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401006652"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401006652"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401006652"))][Get cited by]]

OpenAlex: https://openalex.org/W4401006652 (Open access: False)
    
[[https://openalex.org/A5026378449][Shengjing Song]], [[https://openalex.org/A5036798398][H. D. Chen]], [[https://openalex.org/A5100437614][Yu Zhang]], [[https://openalex.org/A5015941197][Xiaojia Zhu]], [[https://openalex.org/A5086259776][David M. Irwin]], [[https://openalex.org/A5062724953][Kai He]], [[https://openalex.org/A5015039329][Yang Liu]], Integrative Zoology. None(None)] 2024. https://doi.org/10.1111/1749-4877.12870 
     
Myoglobin (Mb) mediates oxygen diffusion and storage in muscle tissue and thus is important for the energy utilization and activity of animals. Birds generally have a high body temperature, and most species also possess the capability of powered flight. Both of these require high levels of aerobic metabolism. Within endothermic mammals, bats also independently evolved flight. Although the functional evolution of myoglobins in deep-diving amniote vertebrates has been well-studied, the functional evolution of myoglobin since the origins of both birds and bats is unclear. Here, with Mb-coding sequences from >200 extant amniote species, we reconstructed ancestral sequences to estimate the functional properties of myoglobin through amniote evolution. A dramatic change in net surface charge on myoglobin occurred during the origin of Aves, which might have been driven by positively selected amino acid substitutions that occurred on the lineage leading to all birds. However, in bats, no change in net surface charge occurred and instead, the Mb genes show evidence of strong purifying selection. The increased net surface charge on bird myoglobins implies an adaptation to flight-related endothermic and higher body temperatures, possibly by reducing harmful protein aggregations. Different from the findings of net surface charge, myoglobins of extant birds show lower stability compared with other amniotes, which probably accelerates the rate of oxygen utilization in muscles. In bats and other mammals, higher stability of Mb may be an alternative pathway for adaptation to endothermy, indicating divergent evolution of myoglobin in birds and bats.    

    

* The Role of Interfacial Interactions and Oxygen Vacancies in Tuning Magnetic Anisotropy in LaCrO3/LaMnO3 Heterostructures  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400963754
:TOPICS: Magnetocaloric Materials Research, Quantum Spin Liquids in Frustrated Magnets, Multiferroic and Magnetoelectric Materials
:PUBLICATION_DATE: 2024-07-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/admi.202400243")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400963754"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400963754"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400963754"))][Get cited by]]

OpenAlex: https://openalex.org/W4400963754 (Open access: True)
    
[[https://openalex.org/A5101482717][Xuanyi Zhang]], [[https://openalex.org/A5035977445][Athby H. Al‐Tawhid]], [[https://openalex.org/A5059150857][P. Schäfer]], [[https://openalex.org/A5100393413][Zhan Zhang]], [[https://openalex.org/A5012250744][Divine P. Kumah]], Advanced Materials Interfaces. None(None)] 2024. https://doi.org/10.1002/admi.202400243 
     
Abstract The interplay of lattice, electronic, and spin degrees of freedom at epitaxial complex oxide interfaces provides a route to tune their magnetic ground states. Unraveling the competing contributions is critical for tuning their functional properties. The relationship between magnetic ordering and magnetic anisotropy and the lattice symmetry, oxygen content, and film thickness in compressively strained LaMnO 3 (LMO)/LaCrO 3 (LCO) superlattices is investigated. Mn–O–Cr antiferromagnetic superexchange interactions across the heterointerface result in a net ferrimagnetic magnetic structure. Bulk magnetometry measurements reveal isotropic in‐plane magnetism for as‐grown oxygen‐deficient thin samples due to equal fractions of orthorhombic a+a‐c‐, and a‐a+c‐ twin domains. As the superlattice thickness is increased, in‐plane magnetic anisotropy emerges as the fraction of the a+a‐c‐ domain increases. On annealing in oxygen, the suppression of oxygen vacancies results in a contraction of the lattice volume, and an orthorhombic to rhombohedral transition leads to isotropic magnetism independent of the film thickness. The complex interactions are investigated using high‐resolution synchrotron diffraction and X‐ray absorption spectroscopy. These results highlight the role of the evolution of structural domains with film thickness, interfacial spin interactions, and oxygen‐vacancy‐induced structural phase transitions in tuning the magnetic properties of complex oxide heterostructures.    

    

* Evolutionary Origins of Self-sustained Kai Protein Circadian Oscillators  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400937324
:TOPICS: Light Signal Transduction in Plants, Molecular Mechanisms of Plant Development and Regulation
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1101/2024.07.23.604570")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400937324"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400937324"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400937324"))][Get cited by]]

OpenAlex: https://openalex.org/W4400937324 (Open access: False)
    
[[https://openalex.org/A5020166009][Atsushi Mukaiyama]], [[https://openalex.org/A5069863551][Yoshihiko Furuike]], [[https://openalex.org/A5063091798][Kumiko Ito-Miwa]], [[https://openalex.org/A5031809046][Yasuhiro Onoue]], [[https://openalex.org/A5011140296][Kota Horiuchi]], [[https://openalex.org/A5005727731][Eiki Yamashita]], [[https://openalex.org/A5071330832][Shuji Akiyama]], bioRxiv (Cold Spring Harbor Laboratory). None(None)] 2024. https://doi.org/10.1101/2024.07.23.604570 
     
Light-dark cycles affect photosynthetic efficiency in autotrophic cyanobacteria; therefore, determining whether ancient cyanobacteria possessed a self-sustained circadian clock when oxygenic photosynthetic systems were established is an important issue in chronobiology. Here we examined the oscillation of the clock protein KaiC in modern cyanobacteria, as well as the function and structure of ancestral Kai proteins, to determine the evolutionary origin of the self-sustained Kai-protein oscillators. The results show that the oldest double-domain KaiC in ancestral bacteria lacked the factors functionally and structurally essential for rhythmicity. The ancestral Kai proteins had acquired these factors through molecular evolution that occurred around Global Oxidation and Snowball Earth events, and were eventually inherited as a self-sustained circadian oscillator by the most recent common ancestor of cyanobacteria capable of oxygenic photosynthesis. This autonomous Kai protein oscillator was further inherited by most freshwater and marine cyanobacteria present today as an autotrophic basis for time-optimal acquisition and consumption of energy from oxygenic photosynthesis.    

    

* Divergent molecular strategies drive evolutionary adaptation to competitive fitness in biofilm formation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400974308
:TOPICS: Evolutionary Dynamics of Genetic Adaptation and Mutation, Ecology and Evolution of Viruses in Ecosystems, Evolution of Cooperation and Altruism in Social Systems
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1093/ismejo/wrae135")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400974308"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400974308"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400974308"))][Get cited by]]

OpenAlex: https://openalex.org/W4400974308 (Open access: True)
    
[[https://openalex.org/A5101469857][Mingxing Tang]], [[https://openalex.org/A5101073182][Ruixue Yang]], [[https://openalex.org/A5057095235][Zilin Zhuang]], [[https://openalex.org/A5013954506][Shuhong Han]], [[https://openalex.org/A5006148444][Yehuan Sun]], [[https://openalex.org/A5101773773][Peiyu Li]], [[https://openalex.org/A5049411475][Kewei Fan]], [[https://openalex.org/A5101415139][Cai Zhao]], [[https://openalex.org/A5101292510][Yang Qiong]], [[https://openalex.org/A5069007742][Zhijian Yu]], [[https://openalex.org/A5062430868][Liang Yang]], [[https://openalex.org/A5100386628][Shuo Li]], The ISME Journal. None(None)] 2024. https://doi.org/10.1093/ismejo/wrae135  ([[https://academic.oup.com/ismej/advance-article-pdf/doi/10.1093/ismejo/wrae135/58650367/wrae135.pdf][pdf]])
     
Abstract Biofilm is a group of heterogeneously structured and densely packed bacteria with limited access to nutrients and oxygen. These intrinsic features can allow a mono-species biofilm to diversify into polymorphic subpopulations, determining the overall community’s adaptive capability to changing ecological niches. However, the specific biological functions underlying biofilm diversification and fitness adaptation are poorly demonstrated. Here, we launched and monitored the experimental evolution of Pseudomonas aeruginosa biofilms, finding that two divergent molecular trajectories were adopted for adaptation to higher competitive fitness in biofilm formation: one involved hijacking bacteriophage superinfection to aggressively inhibit kin competitors, whereas the other induced a subtle change in c-di-GMP signaling to gain a positional advantage via enhanced early biofilm adhesion. Bioinformatics analyses implicated that similar evolutionary strategies were prevalent among clinical P. aeruginosa strains, indicative of parallelism between natural and experimental evolution. Divergence in the molecular bases illustrated the adaptive values of genomic plasticity for gaining competitive fitness in biofilm formation. Finally, we demonstrated that these fitness-adaptive mutations reduced bacterial virulence. Our findings revealed how the mutations intrinsically generated from the biofilm environment influence the evolution of P. aeruginosa.    

    

* Microstructure and oxidation behaviour of Mo–Si–B–Hf alloys at 800 °C and 1100 °C  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401033451
:TOPICS: Synthesis and Properties of Cemented Carbides, Design and Applications of Intermetallic Alloys, Ceramic Materials and Processing
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1177/02670836241266451")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401033451"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401033451"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401033451"))][Get cited by]]

OpenAlex: https://openalex.org/W4401033451 (Open access: False)
    
[[https://openalex.org/A5100343241][Shuo Sun]], [[https://openalex.org/A5100560011][Xiaohui Lin]], [[https://openalex.org/A5058495371][Xuanqiao Gao]], [[https://openalex.org/A5100768010][Yanchao Li]], [[https://openalex.org/A5046478804][Jing Liang]], [[https://openalex.org/A5069268058][Wei Zai]], [[https://openalex.org/A5100444342][Wen Zhang]], Materials Science and Technology. None(None)] 2024. https://doi.org/10.1177/02670836241266451 
     
The influences of the microstructure evolution and oxidation behaviour of Hf-modified Mo–12Si–12B alloys were systematically studied at 800 °C and 1100 °C. Vickers hardness tests show that the Hf addition increases the hardness of Mo–Si–B–Hf alloys. The oxidation experiments were conducted at 800 °C and 1100 °C for 12 h; the detailed analysis revealed that the formation of HfSiO 4 in Mo–12Si–12B–10Hf alloy can effectively decrease the content of oxygen and make the surface of the oxide layer more complete at 800 °C. At 1100°C, the distinct difference in the expansion coefficient among the oxide films results in the formation of cracks and holes in Mo–12Si–12B–10Hf alloy, so the Mo–12Si–12B–10Hf alloy shows poor oxidation resistance.    

    

* Pushing the limits: expanding the temperature tolerance of a coral photosymbiont through differing selection regimes  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400995935
:TOPICS: Resilience of Coral Reef Ecosystems to Climate Change, Ecological Dynamics of Marine Environments, Impacts of Climate Change on Marine Fisheries
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1111/nph.19996")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400995935"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400995935"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400995935"))][Get cited by]]

OpenAlex: https://openalex.org/W4400995935 (Open access: True)
    
[[https://openalex.org/A5030572658][Hugo Scharfenstein]], [[https://openalex.org/A5089963189][Lesa M. Peplow]], [[https://openalex.org/A5010436120][Carlos Alvarez‐Roa]], [[https://openalex.org/A5063307504][Matthew R. Nitschke]], [[https://openalex.org/A5019308572][Wing Yan Chan]], [[https://openalex.org/A5046444751][Patrick Buerger]], [[https://openalex.org/A5086971721][Madeleine J. H. van Oppen]], New Phytologist. None(None)] 2024. https://doi.org/10.1111/nph.19996 
     
Coral thermal bleaching resilience can be improved by enhancing photosymbiont thermal tolerance via experimental evolution. While successful for some strains, selection under stable temperatures was ineffective at increasing the thermal threshold of an already thermo-tolerant photosymbiont (Durusdinium trenchii). Corals from environments with fluctuating temperatures tend to have comparatively high heat tolerance. Therefore, we investigated whether exposure to temperature oscillations can raise the upper thermal limit of D. trenchii. We exposed a D. trenchii strain to stable and fluctuating temperature profiles, which varied in oscillation frequency. After 2.1 yr (54-73 generations), we characterised the adaptive responses under the various experimental evolution treatments by constructing thermal performance curves of growth from 21 to 31°C for the heat-evolved and wild-type lineages. Additionally, the accumulation of extracellular reactive oxygen species, photophysiology, photosynthesis and respiration rates were assessed under increasing temperatures. Of the fluctuating temperature profiles investigated, selection under the most frequent oscillations (diurnal) induced the greatest widening of D. trenchii's thermal niche. Continuous selection under elevated temperatures induced the only increase in thermal optimum and a degree of generalism. Our findings demonstrate how differing levels of thermal homogeneity during selection drive unique adaptive responses to heat in a coral photosymbiont.    

    

* Role of hypogenesis in the evolution of karst in the Taurus Mountains Range, Turkey  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400947810
:TOPICS: Karst Hydrogeology and Geohazards, Mapping Groundwater Potential Zones Using GIS Techniques, Climate Change and Paleoclimatology
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.5038/1827-806x.53.2.2501")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400947810"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400947810"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400947810"))][Get cited by]]

OpenAlex: https://openalex.org/W4400947810 (Open access: True)
    
[[https://openalex.org/A5021176197][Serdar Bayarı]], [[https://openalex.org/A5031151244][Naciye Nur Özyurt]], [[https://openalex.org/A5021792858][Lütfi Nazik]], [[https://openalex.org/A5013102247][Koray Törk]], [[https://openalex.org/A5069614265][Noyan Güner]], [[https://openalex.org/A5076686059][Emrah Pekkan]], [[https://openalex.org/A5054679472][Pınar Avcı]], International Journal of Speleology. 53(2)] 2024. https://doi.org/10.5038/1827-806x.53.2.2501 
     
Field observations and laboratory data collected from the Taurus Mountains Range, Turkey during the last two decades provided evidence for the link between the evolution of hypogene karst and the geodynamic history. Major evidence includes; carbonate-hosted secondary ore deposits that are converted from primarily hypogene minerals by epigene, oxygen-rich groundwater circulating at local to intermediate depths. Another piece of evidence of hypogene karst in the Tauride is the Kırkgöz springs’ huge submerged cave/conduit system, which formed the Antalya Travertine Plateau, which is the world’s largest deposit precipitated by cool karst groundwater. The obruks in central Tauride are giant collapse dolines formed by ascending hypogene fluids in the upper continental crust, rich in volcanogenic carbondioxide. The groundwater’s noble gas and carbon isotope data are helpful in determining the existing but asymptomatic hypogene activity in the upper crust. Hypogene karst development seems common in parts of the world with current or past geodynamic activity. However, a hydrogeological overview of the geodynamic history is essential to assess the hypogene processes and their reflections on the land surface.    

    

* An in situ exploration of how Fe/N/C oxygen reduction catalysts evolve during synthesis under pyrolytic conditions  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400965814
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-50629-x")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400965814"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400965814"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400965814"))][Get cited by]]

OpenAlex: https://openalex.org/W4400965814 (Open access: True)
    
[[https://openalex.org/A5017209222][Shuhu Yin]], [[https://openalex.org/A5005655897][H. Yi]], [[https://openalex.org/A5072864302][Mengli Liu]], [[https://openalex.org/A5102918065][Jian Yang]], [[https://openalex.org/A5104089361][Shuangli Yang]], [[https://openalex.org/A5037320195][Binwei Zhang]], [[https://openalex.org/A5100336419][Long Chen]], [[https://openalex.org/A5101282366][Xiaoyang Cheng]], [[https://openalex.org/A5100670330][Huan Huang]], [[https://openalex.org/A5072851267][Rui Huang]], [[https://openalex.org/A5017615701][Yanxia Jiang]], [[https://openalex.org/A5035314482][Hong‐Gang Liao]], [[https://openalex.org/A5100673667][Shi‐Gang Sun]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-50629-x 
     
Abstract In pursuing cheap and effective oxygen reduction catalysts, the Fe/N/C system emerges as a promising candidate. Nevertheless, the structural transformations of starting materials into Fe- and N-doped carbon catalysts remains poorly characterized under pyrolytic conditions. Here, we explore the evolution of Fe species and track the formation of Fe–N 4 site development by employing diverse in-situ diagnostic techniques. In-situ heating microscopy reveals the initial formation of FeO x nanoparticles and subsequent internal migration within the carbon matrix, which stops once FeO x is fully reduced. The migration and decomposition of nanoparticles then leads to carbon layer reconstruction. Experimental and theoretical analysis reveals size-dependent behavior of FeO x where nanoparticles below 7 nm readily release Fe atoms to form Fe–N 4 while nanoparticles with sizes >10 nm tend to coalesce and impede Fe–N 4 site formation. The work visualizes the pyrolysis process of Fe/N/C materials, providing theoretical guidance for the rational design of catalysts.    

    

* Origin of the Surface Magnetic Dead Layer in Rare‐Earth Titanates  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401038578
:TOPICS: Magnetocaloric Materials Research, Emergent Phenomena at Oxide Interfaces, Quantum Spin Liquids in Frustrated Magnets
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/admi.202400489")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401038578"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401038578"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401038578"))][Get cited by]]

OpenAlex: https://openalex.org/W4401038578 (Open access: True)
    
[[https://openalex.org/A5087769815][Raphaël Aeschlimann]], [[https://openalex.org/A5031758687][Manuel Bibès]], [[https://openalex.org/A5025915332][Alexandre Gloter]], Advanced Materials Interfaces. None(None)] 2024. https://doi.org/10.1002/admi.202400489 
     
Abstract Perovskite rare‐earth titanates RTiO 3 display a rich array of magnetic and electronic properties, with a Mott‐insulating ground state and ferro‐ or antiferromagnetic spin orders depending on the rare‐earth R. The nominal Ti valence is 3+ with a corresponding 3 d 1 configuration. Yet, at the surface of both bulk and thin films of RTiO 3 , the Ti valence has been found to strongly deviate towards the more stable 4+ state, adversely affecting magnetic properties. While this finding is rather ubiquitous, its exact origin is still poorly understood, which hampers the integration of RTiO 3 into complex heterostructures harnessing their rich physics. Here, scanning transmission electron microscope and electron energy loss spectroscopy experiments are used to analyze the top part of an epitaxial DyTiO 3 thin film displaying a well‐developed Ti 4+ ‐rich layer over several nanometres. It shows that this valence evolution is related to a combination of short‐range ordered interstitial oxygen planes and Ti‐Dy cationic imbalance. Both defects synergistically contribute to enough hole doping for a complete transition toward Ti 4+ over a few unit‐cells from the surface while a structure primarily of the perovskite‐type is maintained.    

    

* Emerging insights into the pathogenesis and therapeutic strategies for vascular endothelial injury-associated diseases: focus on mitochondrial dysfunction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401010620
:TOPICS: Mitochondrial Dynamics and Reactive Oxygen Species Regulation, Pathophysiology of Myocardial Reperfusion Injury, Copper and Zinc in Health and Disease
:PUBLICATION_DATE: 2024-07-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10456-024-09938-4")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401010620"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401010620"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401010620"))][Get cited by]]

OpenAlex: https://openalex.org/W4401010620 (Open access: True)
    
[[https://openalex.org/A5074106903][Boxian Pang]], [[https://openalex.org/A5070949320][Guangtong Dong]], [[https://openalex.org/A5071917815][Tieliang Pang]], [[https://openalex.org/A5054279552][Xinyao Sun]], [[https://openalex.org/A5100352198][Xin Liu]], [[https://openalex.org/A5054558623][Yifeng Nie]], [[https://openalex.org/A5065945066][Xing Chang]], Angiogenesis. None(None)] 2024. https://doi.org/10.1007/s10456-024-09938-4 
     
As a vital component of blood vessels, endothelial cells play a key role in maintaining overall physiological function by residing between circulating blood and semi-solid tissue. Various stress stimuli can induce endothelial injury, leading to the onset of corresponding diseases in the body. In recent years, the importance of mitochondria in vascular endothelial injury has become increasingly apparent. Mitochondria, as the primary site of cellular aerobic respiration and the organelle for "energy information transfer," can detect endothelial cell damage by integrating and receiving various external stress signals. The generation of reactive oxygen species (ROS) and mitochondrial dysfunction often determine the evolution of endothelial cell injury towards necrosis or apoptosis. Therefore, mitochondria are closely associated with endothelial cell function, helping to determine the progression of clinical diseases. This article comprehensively reviews the interconnection and pathogenesis of mitochondrial-induced vascular endothelial cell injury in cardiovascular diseases, renal diseases, pulmonary-related diseases, cerebrovascular diseases, and microvascular diseases associated with diabetes. Corresponding therapeutic approaches are also provided. Additionally, strategies for using clinical drugs to treat vascular endothelial injury-based diseases are discussed, aiming to offer new insights and treatment options for the clinical diagnosis of related vascular injuries.    

    

* First Detection of CO Isotopologues in a High-redshift Main-sequence Galaxy: Evidence of a Top-heavy Stellar Initial Mass Function  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400999003
:TOPICS: Stellar Astrophysics and Exoplanet Studies, Star Formation in Molecular Clouds and Protoplanetary Disks, Galaxy Formation and Evolution in the Universe
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3847/1538-4357/ad4da2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400999003"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400999003"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400999003"))][Get cited by]]

OpenAlex: https://openalex.org/W4400999003 (Open access: True)
    
[[https://openalex.org/A5101951001][Ziyi Guo]], [[https://openalex.org/A5035994027][Zhi-Yu Zhang]], [[https://openalex.org/A5064997161][Zhiqiang Yan]], [[https://openalex.org/A5075780212][Eda Gjergo]], [[https://openalex.org/A5028329336][Allison Man]], [[https://openalex.org/A5062504729][R. J. Ivison]], [[https://openalex.org/A5052555995][X. Fu]], [[https://openalex.org/A5047464767][Yong Shi]], The Astrophysical Journal. 970(2)] 2024. https://doi.org/10.3847/1538-4357/ad4da2 
     
Abstract Recent observations and theories have presented a strong challenge to the universality of the stellar initial mass function (IMF) in extreme environments. A notable example has been found for starburst conditions, where evidence favors a top-heavy IMF, i.e., there is a bias toward massive stars compared to the IMF that is responsible for the stellar mass function and elemental abundances observed in the Milky Way. Local starburst galaxies have star formation rates similar to those in high-redshift main-sequence galaxies, which appear to dominate the stellar mass budget at early epochs. However, the IMF of high-redshift main-sequence galaxies is yet to be probed. Since 13 CO and C 18 O isotopologues are sensitive to the IMF, we have observed these lines toward four strongly lensed high-redshift main-sequence galaxies using the Atacama Large Millimeter/submillimeter Array. Of our four targets, SDSS J0901+1814, at z ≈ 2.26, is seen clearly in 13 CO and C 18 O, the first detection of CO isotopologues in the high-redshift main-sequence galaxy population. The observed 13 C/ 18 O ratio, 2.4 ± 0.8, is significantly lower than that of local main-sequence galaxies. We estimate the isotope ratio, oxygen abundance, and stellar mass using a series of chemical evolution models with varying star formation histories and IMFs. All models favor an IMF that is more top-heavy than that of the Milky Way. Thus, as with starburst galaxies, main-sequence galaxies in the high-redshift Universe have a greater fraction of massive stars than a Milky Way IMF would imply.    

    

* The origin and migration laws of hydrocarbons in uranium‐bearing Luohe Formation, Pengyang area, SW Ordos Basin  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4401007272
:TOPICS: Characterization of Shale Gas Pore Structure, Chemistry of Actinide and Lanthanide Elements, Tectonic and Geochronological Evolution of Orogens
:PUBLICATION_DATE: 2024-07-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/gj.5017")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4401007272"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4401007272"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4401007272"))][Get cited by]]

OpenAlex: https://openalex.org/W4401007272 (Open access: False)
    
[[https://openalex.org/A5069183921][Qinghong Si]], [[https://openalex.org/A5026044728][Xueming Teng]], [[https://openalex.org/A5103273498][Qiang Zhu]], [[https://openalex.org/A5101418468][Zongxing Li]], [[https://openalex.org/A5052386407][Hualei Zhao]], [[https://openalex.org/A5011677079][Guo‐Ming Wang]], [[https://openalex.org/A5101243426][Haikui Tong]], [[https://openalex.org/A5087632511][Hongliang Dang]], Geological Journal. None(None)] 2024. https://doi.org/10.1002/gj.5017 
     
The hydrocarbon activity in Pengyang area, situated in the southwestern Ordos Basin, is notably prominent. Investigation on the migration laws of hydrocarbons is imperative for comprehending the involvement in uranium mineralization. Based on the analysis of spatial distribution of hydrocarbon containing fluid and hydrocarbon generation conditions of sandstone in the Luohe Formation, the organic geochemical characteristics including hydrocarbon components, carbon isotopes and biomarker compounds were analysed. The research results indicate that: (1) hydrocarbon fluid activities in the Luohe Formation are predominantly observed in layers exhibiting higher uranium mineralization. The mudstone of the Luohe Formation had low organic matter content and low thermal maturity, which was not conducive to hydrocarbon generation. (2) Hydrocarbon‐containing fluid in the sandstone of Luohe Formation not only contained reducing gases such as methane and hydrogen but also chloroform asphalt components. The carbon isotopes of hydrocarbon in sandstone inform Luohe Formation resemble oil and gas in the Mesozoic. The biomarker parameter inferred that the parent rock of hydrocarbons in the Luohe Formation was formed under reducing and freshwater conditions, and hydrocarbon generation occurred at the mature stage. As above mentioned, a comparison was carried out between the affinity of hydrocarbon‐containing fluid in the Luohe Formation and different layers of hydrocarbon source rocks. The migration behaviour of hydrocarbon‐containing fluid in the Pengyang area has been summarized, and the involvement of hydrocarbon‐containing fluid in uranium mineralization has been discussed. The main concepts are as follows: the sedimentary environment and thermal evolution conditions of hydrocarbons in the sandstone of Luohe Formation resemble those of the primary hydrocarbon source rocks in the Yanchang Formation. The main hydrocarbon charging events in the Luohe Formation occurred before the Late Cretaceous period, which is primarily related to two hydrocarbon generation events from 130 to 100 Ma in the Yanchang Formation and fault conduits connecting the Triassic to the Cretaceous Strata. The hydrocarbon‐containing fluid released from Yanchang Formation migrating to the Luohe Formation provides reducing conditions for the precipitation of uranium in oxygen‐bearing water bodies.    

    

* Lithium Ions as Modulators of Complex Biological Processes: The Conundrum of Multiple Targets, Responsiveness and Non-Responsiveness, and the Potential to Prevent or Correct Dysregulation of Systems during Aging and in Disease  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4400980549
:TOPICS: Molecular Mechanisms of Synaptic Plasticity and Neurological Disorders, Epidemiology and Management of Bipolar Disorder, Mechanisms of Alzheimer's Disease
:PUBLICATION_DATE: 2024-07-25
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/biom14080905")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4400980549"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4400980549"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4400980549"))][Get cited by]]

OpenAlex: https://openalex.org/W4400980549 (Open access: True)
    
[[https://openalex.org/A5061396807][David A. Hart]], Biomolecules. 14(8)] 2024. https://doi.org/10.3390/biom14080905 
     
Lithium is one of the lightest elements on Earth and it has been in the environment since the formation of the galaxy. While a common element, it has not been found to be an essential element in biological processes, ranging from single cell organisms to Homo sapiens. Instead, at an early stage of evolution, organisms committed to a range of elements such as sodium, potassium, calcium, magnesium, zinc, and iron to serve essential functions. Such ions serve critical functions in ion channels, as co-factors in enzymes, as a cofactor in oxygen transport, in DNA replication, as a storage molecule in bone and liver, and in a variety of other roles in biological processes. While seemingly excluded from a major essential role in such processes, lithium ions appear to be able to modulate a variety of biological processes and “correct” deviation from normal activity, as a deficiency of lithium can have biological consequences. Lithium salts are found in low levels in many foods and water supplies, but the effectiveness of Li salts to affect biological systems came to recent prominence with the work of Cade, who reported that administrating Li salts calmed guinea pigs and was subsequently effective at relatively high doses to “normalize” a subset of patients with bipolar disorders. Because of its ability to modulate many biological pathways and processes (e.g., cyclic AMP, GSK-3beta, inositol metabolism, NaK ATPases, neuro processes and centers, immune-related events, respectively) both in vitro and in vivo and during development and adult life, Li salts have become both a useful tool to better understand the molecular regulation of such processes and to also provide insights into altered biological processes in vivo during aging and in disease states. While the range of targets for lithium action supports its possible role as a modulator of biological dysregulation, it presents a conundrum for researchers attempting to elucidate its specific primary target in different tissues in vivo. This review will discuss aspects of the state of knowledge regarding some of the systems that can be influenced, focusing on those involving neural and autoimmunity as examples, some of the mechanisms involved, examples of how Li salts can be used to study model systems, as well as suggesting areas where the use of Li salts could lead to additional insights into both disease mechanisms and natural processes at the molecular and cell levels. In addition, caveats regarding lithium doses used, the strengths and weaknesses of rodent models, the background genetics of the strain of mice or rats employed, and the sex of the animals or the cells used, are discussed. Low-dose lithium may have excellent potential, alone or in combination with other interventions to prevent or alleviate aging-associated conditions and disease progression.    

    
