#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Mon Feb 12 00:44:18 2024

Found 48 results from 2024-02-05 to 2024-02-12
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Desiging Asymmetrical Tmn4 Sites Via Phosphorous or Sulfur Dual Coordination as High-Performanceelectrocatalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391523080
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4716365")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391523080"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391523080"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391523080"))][Get cited by]]

OpenAlex: https://openalex.org/W4391523080 (Open access: False)
    
[[https://openalex.org/A5029725226][Xia Zhe]], [[https://openalex.org/A5068080781][Jinzhong Tian]], [[https://openalex.org/A5004753547][Rui Tan]], [[https://openalex.org/A5065987129][Hua Hou]], [[https://openalex.org/A5046173951][Xinyu Zhang]], [[https://openalex.org/A5054295426][Yuhong Zhao]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4716365 
     
The development of highly efficient oxygen evolution reaction (OER) catalysts based on more cost-effective and earth-abundant elements is of great significance and still faces a huge challenge. In this work, a series of transition metal (TM) embedding a new-defined monolayer carbon nitride phase is theoretically profiled and constructed as a catalytic platform for OER studies. Typically, a four-step screening strategy was proposed to rapidly identified high performance candidates and the coordination structure and catalytic performance relationship was thoroughly analyzed. Moreover, the eliminating criterion was established to condenses valid range based on the Gibbs free energy of OH*. Our results reveal that the as-constructed 2FeCN/P exhibits superior activity toward OER with an ultralow overpotential of 0.25 V, at the same time, the established 3FeCN/S configuration performed well as a bifunctional OER/ORR electrocatalysis with extremely lower overpotential ηOER/ηORR of 0.26/0.48 V. Overall, this work provides an effective framework for screening advanced OER catalysts, which can also be extended to the complex multistep catalytic reactions.    

    

* WS2/Mesoporous Carbon Nanostructures as a Bifunctional Electrode for All Quasi‐Solid‐State Supercapacitor and Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391537477
:TOPICS: Materials for Electrochemical Supercapacitors, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-04
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/admt.202301797")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391537477"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391537477"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391537477"))][Get cited by]]

OpenAlex: https://openalex.org/W4391537477 (Open access: False)
    
[[https://openalex.org/A5083916755][Muzahir Iqbal]], [[https://openalex.org/A5072933305][Nilesh G. Saykar]], [[https://openalex.org/A5078590198][Abhijeet Singh]], [[https://openalex.org/A5042201959][Imtiaz Ahmed]], [[https://openalex.org/A5042903687][Anil Arya]], [[https://openalex.org/A5022029107][Krishna Kanta Haldar]], [[https://openalex.org/A5069297291][S. K. Mahapatra]], Advanced Materials Technologies. None(None)] 2024. https://doi.org/10.1002/admt.202301797 
     
Abstract 2D transition‐metal sulfides have developed as favorable electroactive materials for electrochemical energy storage and conversion applications. In this work, WS 2 /mesoporous carbon (MC) is developed by a one‐step hydrothermal technique for supercapacitor and oxygen evaluation reaction (OER) application. However, the metal sulfides have poor rate and cyclic performance due to the aggregations between two layers of structures restricting their performance. The interaction between WS 2 nanosheets and MC produces a synergistic effect, resulting in a decent electrochemical energy storage and conversion application. The synthesized materials used to prepare quasi‐solid‐state symmetric (QSSS) and asymmetric (QSSA) supercapacitor configuration enable the highest specific capacitance ( C SP ) of 305.45 F g −1 and 204.21 F g −1 @ 10 mV s −1 , respectively. Moreover, the specific energy and power density of QSSS and QSSA devices are 31.1 Wh kg −1 @824.95 W kg −1 and 24.74 Wh kg −1 @549.84 W kg −1 , respectively. Additionally, the multifunctionality of the synthesized binary nanocomposite is also tested for OER. The composite shows a desirable over potential of 307 mV in 6 m KOH electrolyte, with a 69 mV dec −1 Tafel slope. The dual role of WS 2 /MC for energy storage and oxygen evaluation reaction conversion reveals the potential of metal sulfides.    

    

* The Photoelectrochemically Enhanced Oxygen Evolution reaction via Thin Films of novel (1:2:1) SnO-Mn2O3-TiO2 hybrid nanotubes  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391538514
:TOPICS: Gas Sensing Technology and Materials, Photocatalytic Materials for Solar Energy Conversion, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104034")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391538514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391538514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391538514"))][Get cited by]]

OpenAlex: https://openalex.org/W4391538514 (Open access: False)
    
[[https://openalex.org/A5008504521][Rabia Naeem]], [[https://openalex.org/A5042719496][Sehar Shakir]], [[https://openalex.org/A5037439793][Shahzad Sharif]], [[https://openalex.org/A5069717769][Saba Afzal]], [[https://openalex.org/A5080934334][Shahid Bashir]], [[https://openalex.org/A5021048997][Muhammad Adil Mansoor]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104034 
     
The oxygen and hydrogen evolution reactions play a significant role in overall water splitting. The photoelectrochemical water splitting offers a high potential for conversion efficiency at low voltage and temperature. Therefore, in the present work comparative studies of novel (1:2:1)) SnO-Mn2O3-TiO2 (SMT) ternary and SnO-Mn2O3 (SM), SnO-TiO2 (ST) and Mn2O3-TiO2 (MT) binary mixed-metal oxides thin films for hydrogen generation are performed. method. The Aerosol Assisted Chemical Vapor Deposition (AACVD) fabricated thin films were analyzed through X-ray diffraction (XRD), Raman spectroscopy, scanning electron microscopy (SEM) coupled with energy-dispersive X-ray spectroscopy (EDX), X-ray photoelectron microscopy (XPS) and UV-visible spectroscopy to determine the crystallinity, surface morphology, binding energy, and band gaps. The Photoelectrochemical studies demonstrate that the SnO-Mn2O3-TiO2 (SMT) thin film yields 1.96, 2.37, and 2.7 times maximum current density than the binary SnO-Mn2O3 (SM), SnO-TiO2 (ST) and Mn2O3-TiO2 (MT) metal oxides, respectively. These results illustrate that due to unique topography, uniform distribution, and good optoelectronic properties of ternary SnO-Mn2O3-TiO2 (SMT) nanotubular layers show better light-harvesting performance as compared to the binary (SM, ST, and MT) metal oxides. Therefore, it is believed that SMT is a promising candidate for energy harvesting applications.    

    

* Voltage activation induced MoO42− dissolution to enhance performance of iron doped nickel molybdate for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391539673
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.02.016")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391539673"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391539673"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391539673"))][Get cited by]]

OpenAlex: https://openalex.org/W4391539673 (Open access: False)
    
[[https://openalex.org/A5072211414][Xiaoqing Zhang]], [[https://openalex.org/A5050871189][Hanxiao Liao]], [[https://openalex.org/A5014662952][Pengfei Tan]], [[https://openalex.org/A5044544424][Yi Zhang]], [[https://openalex.org/A5067431842][Binhua Zhou]], [[https://openalex.org/A5007612582][Meihuan Liu]], [[https://openalex.org/A5053274988][Jun Pan]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.02.016 
     
Transition metal-based precatalysts are typically voltage-activated before electrochemical testing in the condition of alkaline oxygen evolution reaction. Nevertheless, the impact of voltage on the catalyst and the anion dissolution is frequently disregarded. In this study, Fe-doped NiMoO4 (Fe-NiMoO4) was synthesized as a precursor through a straightforward hydrothermal method, and MoFe-modified Ni (oxygen) hydroxide (MoFe-NiOxHy) was obtained via cyclic voltammetry (CV) activation. The effects of voltage on Fe-NiMoO4 and the dissolved inactive MoO42− ions in the process were examined in relation to OER performance. It has demonstrated that the crystallinity of the catalyst is reduced by voltage, thereby enhancing its electrocatalytic activity. The electron distribution state can be adjusted during the application of voltage, leading to the generation of additional active sites and an acceleration in the reaction rate. Additionally, MoO42− exhibits potential dependence during its dissolution. In the OER process, the dissolution of MoO42− enhances the reconstruction degree of Fe-NiMoO4 into the active substance and expedites the formation of active Ni(Fe)OOH. Hence, the optimized MoFe-NiOxHy exhibited exceptional electrocatalytic performance, with a current density of 100 mA cm−2 achieved at an overpotential of only 256 mV. This discovery contributes to a more comprehensive understanding of alkaline OER performance under the influence of applied voltage and the presence of inactive oxygen ions, offering a promising avenue for the development of efficient electrocatalysts.    

    

* Regulating the binding strength of oxygen intermediates with a conductive π–d conjugated metal-organic polymer CoTAA on BiVO4 photoanode for efficient photoelectrochemical water oxidation  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391542817
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Porous Crystalline Organic Frameworks for Energy and Separation Applications, Perovskite Solar Cell Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149400")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391542817"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391542817"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391542817"))][Get cited by]]

OpenAlex: https://openalex.org/W4391542817 (Open access: False)
    
[[https://openalex.org/A5024259754][Liang Zhu]], [[https://openalex.org/A5055144058][Zhifu Liang]], [[https://openalex.org/A5013079528][Shouguo Zhu]], [[https://openalex.org/A5061135232][Yingchun Cheng]], [[https://openalex.org/A5027224656][Zhongfei Li]], [[https://openalex.org/A5002982501][Haiwei Du]], [[https://openalex.org/A5013295789][Congshan Zhu]], [[https://openalex.org/A5036560264][Daochuan Jiang]], [[https://openalex.org/A5003176702][Yupeng Yuan]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149400 
     
The slow charge transfer and sluggish water oxidation reaction kinetics represent the main obstacles in the advancement of efficient BiVO4 photoanodes for photoelectrochemical (PEC) water splitting. Herein, a conductive π-d conjugated metal–organic polymer composed of 1,4,8,11-tetraaza[14]annulene (TAA) and atomically dispersed Co sites (CoTAA) was developed as an efficient oxygen evolution catalyst (OEC) to overcome these limitations. In CoTAA, the highly delocalized π-d conjugation results in superior electrical conductivity, leading to improved charge transfer. Additionally, X-ray absorption fine structure (XAFS) spectra and theoretical simulations reveal that the atomically dispersed Co sites within CoTAA, configured as Co-N4, modulates the binding strength of water oxidation intermediates (*OH, *O, and *OOH), thereby decreasing the energy barrier and facilitating the water oxidation reaction kinetics. Consequently, when combining with ultrathin FeOOH withdrawing the holes, the optimized CoTAA/FeOOH/BiVO4 photoanode achieves a high photocurrent density of 4.97 mA cm−2 at 1.23 VRHE under one sun irradiation (100 mW cm−2). This photocurrent represents a 2.59-fold enhancement when compared to that of pure BiVO4. These findings demonstrate the tremendous potential of π-d conjugated metal–organic polymers as active OECs in enhancing the PEC performance of water splitting.    

    

* Halogen-assisted Ni based MOFs ball-flowers for enhanced electrocatalytic oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391554725
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.267")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391554725"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391554725"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391554725"))][Get cited by]]

OpenAlex: https://openalex.org/W4391554725 (Open access: False)
    
[[https://openalex.org/A5039338889][Lan Wu]], [[https://openalex.org/A5038403420][Huolin Zhong]], [[https://openalex.org/A5035771491][Y. Li]], [[https://openalex.org/A5018452581][Xia Zhong]], [[https://openalex.org/A5075105337][Wei Feng]], [[https://openalex.org/A5069644773][Fangting Chi]], [[https://openalex.org/A5037406345][Ruishi Xie]], International Journal of Hydrogen Energy. 58(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.01.267 
     
Although metal-organic framework (MOF) materials are now a hot candidate for improving the kinetics of the anodic oxygen evolution reaction (OER), direct application of them is challenging due to their poor intrinsic conductivity and internal active sites. Here, we successfully introduced halogen atoms into the octahedral topological structure of Ni based MOF materials, achieving an impressive improvement in OER activity. Accordingly, the as-obtained halogen-containing Ni based MOF ball-flowers (X-Ni-MOF BFs, X = F, Cl, Br and I) exhibit significantly enhanced electrocatalytic OER activity with an increase in electronegativity. The optimal F-Ni-MOF BFs possess an ultra-low overpotential of 222 mV at 10 mA cm−2, ∼70 mV lower than Ni-MOF nanosheets. Further research demonstrates that the introduction of halogen atoms can cause NiO6 octahedral distortion and strong electronic interactions between halogen and the adjacent Ni atoms, resulting in rapid reaction kinetics and lower electron transfer barriers. This work provides a reference for designing excellent electrocatalysts by adjusting their topological structure.    

    

* Superhydrophilic CoMoO4 with high oxygen vacancy for outstanding alkaline OER  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391554818
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Desulfurization Technologies for Fuels
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.01.338")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391554818"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391554818"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391554818"))][Get cited by]]

OpenAlex: https://openalex.org/W4391554818 (Open access: False)
    
[[https://openalex.org/A5064789384][Xiang Shao]], [[https://openalex.org/A5032107505][Danni Li]], [[https://openalex.org/A5002152947][Anhui Zhou]], [[https://openalex.org/A5079098289][Lin Zhu]], [[https://openalex.org/A5021827773][Youwei Du]], [[https://openalex.org/A5087645440][Binbin Li]], [[https://openalex.org/A5084058732][Yuting Zhang]], [[https://openalex.org/A5084812419][Limei Cao]], [[https://openalex.org/A5029886716][Jie Yang]], International Journal of Hydrogen Energy. 58(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.01.338 
     
The development of low-cost, long-life alkaline OER catalysts with competitive precious metal activity is of great importance for the sustainable decomposition of water and the development of hydrogen energy. In this study, Mo-doped CoOx electrode CMOT (Co: Mo = 7:3+Tween20) with superhydrophilic surface structure was prepared on titanium plates by using a more industrial thermal decomposition coating method. The results showed that the addition of Mo not only adjusted the pore structure of the catalyst but also increased the oxygen vacancy level. The self-loading effect of Tween20 makes the catalyst more dispersed and granulated. It changes the particle size distribution and improves the specific surface area while increasing the wettability of the material surface and accelerating the adsorption of water molecules at the anode. When the electrode is used for anodic oxygen evolution, its oxygen evolution overpotential at 0.1 M KOH, 10 mA cm−2 is as low as 250 mV vs.RHE. Its accelerated life can be up to 304 h under severe test conditions of 1 M KOH, 1 A cm−2, 60 °C. Therefore, the CMOT electrode has excellent OER catalytic activity and stability. This study provides a new idea for developing anode materials for water electrolysis hydrogen production.    

    

* Rhodium Substituted La0.85Sr0.15CoO3: An Active Oxygen Evolution Electrocatalyst Based upon Ionic Rhodium  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391558623
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Reduction of CO2 to Fuels
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpcc.3c08433")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391558623"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391558623"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391558623"))][Get cited by]]

OpenAlex: https://openalex.org/W4391558623 (Open access: False)
    
[[https://openalex.org/A5093868961][Rajeshree Liya]], [[https://openalex.org/A5043077661][Rajinder Kour]], [[https://openalex.org/A5001274885][Sudhanshu Sharma]], [[https://openalex.org/A5023623283][Aditi Singhal]], The Journal of Physical Chemistry C. None(None)] 2024. https://doi.org/10.1021/acs.jpcc.3c08433 
     
Nanocrystalline La0.85Sr0.15CoO3 (LSCO) as well as a series of metal substituted La0.85Sr0.15M0.05Co0.95O3 (M = Rh, Pt, Ru, Pd) compounds were prepared and a detailed characterization and electrochemical studies was carried out. Rh substituted La0.85Sr0.15CoO3 showed the best activity with respect to current density. Thereafter, a series of Rhodium substituted LSCO catalysts were synthesized varying the concentration of Rh and were then fully characterized. XRD showed a pure nanocrystalline phase of La0.85Sr0.15CoO3 having no Rh or Rh-oxide related peaks, confirming that Rh does not exist as a separated phase and is well substituted in the perovskite lattice. Electrochemical oxygen evolution reaction (OER) studies performed in neutral, as well as basic conditions show that Rh substitution has the most profound effect on the OER activity. Variation in the Rh concentration indicates that the OER activity peaks at 2.5% Rh substituted LSCO catalyst (La0.85Sr0.15Rh0.025Co0.975O3) and decreases thereafter. Electrochemical surface area study and Tafel slope measurements for all Rh substituted LSCO indicated a profound increment in the electrocatalytic activity because of the presence of ionic Rh in the La0.85Sr0.15CoO3 lattice in comparison to pure LSCO. X-ray photoelectron spectroscopy of the postcharacterized sample confirmed that Rh3+ is the active center for the reaction.    

    

* Transition metal incorporation: electrochemical, structure, and chemical composition effects on nickel oxyhydroxide oxygen-evolution electrocatalysts  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391563047
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Conducting Polymer Research
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ee03617k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391563047"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391563047"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391563047"))][Get cited by]]

OpenAlex: https://openalex.org/W4391563047 (Open access: True)
    
[[https://openalex.org/A5064669801][Raúl A. Márquez]], [[https://openalex.org/A5093767641][Emma Kalokowski]], [[https://openalex.org/A5014865175][Michael Espinosa]], [[https://openalex.org/A5004569228][Jay T. Bender]], [[https://openalex.org/A5089658948][Yoon Jun Son]], [[https://openalex.org/A5003599694][Kenta Kawashima]], [[https://openalex.org/A5058357026][Chikaodili E. Chukwuneke]], [[https://openalex.org/A5011516492][Lettie A Smith]], [[https://openalex.org/A5000791602][Hugo Celio]], [[https://openalex.org/A5037952567][Andrei Dolocan]], [[https://openalex.org/A5066320776][Xun Zhan]], [[https://openalex.org/A5046237493][Nathaniel R. Miller]], [[https://openalex.org/A5077085087][Delia J. Milliron]], [[https://openalex.org/A5018687349][Joaquin Resasco]], [[https://openalex.org/A5077813936][C. Buddie Mullins]], Energy and Environmental Science. None(None)] 2024. https://doi.org/10.1039/d3ee03617k  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ee/d3ee03617k][pdf]])
     
Understanding how electrode materials evolve in energy conversion and storage devices is critical to optimizing their performance. We report a comprehensive investigation into the impact of in situ metal incorporation...    

    

* Targeted synthesis, characterization, and electrochemical analysis of transition-metal-oxide catalysts for the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391563312
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.checat.2024.100905")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391563312"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391563312"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391563312"))][Get cited by]]

OpenAlex: https://openalex.org/W4391563312 (Open access: False)
    
[[https://openalex.org/A5040151260][David Hayes]], [[https://openalex.org/A5090914666][Shaun M Alia]], [[https://openalex.org/A5089224819][Bryan S. Pivovar]], [[https://openalex.org/A5079577690][Ryan M. Richards]], Chem Catalysis. None(None)] 2024. https://doi.org/10.1016/j.checat.2024.100905 
     
No abstract    

    

* The role of composition and porosity of MOF derived Cu-embedded carbon electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391568315
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s42247-024-00633-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391568315"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391568315"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391568315"))][Get cited by]]

OpenAlex: https://openalex.org/W4391568315 (Open access: False)
    
[[https://openalex.org/A5093871285][Mahesh Burud]], [[https://openalex.org/A5074619769][Amruta Koli]], [[https://openalex.org/A5089744508][Akshata Pattanshetti]], [[https://openalex.org/A5093871286][Prathamesh Chougale]], [[https://openalex.org/A5006453224][Rohant Dhabbe]], [[https://openalex.org/A5044519958][V. P. Chavan]], [[https://openalex.org/A5037744343][Deok‐kee Kim]], [[https://openalex.org/A5065955406][Amit R. Supale]], [[https://openalex.org/A5025870282][Sandip Sabale]], Emergent Materials. None(None)] 2024. https://doi.org/10.1007/s42247-024-00633-0 
     
No abstract    

    

* Fe-doped MnO2/NiCo2O4 as Bifunctional Electrocatalyst for Oxygen Evolution Reaction and Oxygen Reduction Reaction in Alkaline Electrolyte  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391576582
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s10562-023-04573-y")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391576582"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391576582"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391576582"))][Get cited by]]

OpenAlex: https://openalex.org/W4391576582 (Open access: False)
    
[[https://openalex.org/A5090474023][Chen‐hui Wei]], [[https://openalex.org/A5088828820][Chen-xin Li]], [[https://openalex.org/A5081805002][Jinliang Liu]], [[https://openalex.org/A5012065142][Hongfeng Huang]], [[https://openalex.org/A5009047490][Shao-Ling Wu]], Catalysis Letters. None(None)] 2024. https://doi.org/10.1007/s10562-023-04573-y 
     
No abstract    

    

* Efficient electrocatalytic oxygen evolution by nano NiO-In 2 O 3 electrode materials  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391578443
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1080/16583655.2024.2312597")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391578443"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391578443"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391578443"))][Get cited by]]

OpenAlex: https://openalex.org/W4391578443 (Open access: True)
    
[[https://openalex.org/A5017132300][Asghar Ali]], [[https://openalex.org/A5006758122][Muhammad Zubair]], [[https://openalex.org/A5031068587][Muhammad Shahzeb Khan]], [[https://openalex.org/A5036861201][Muhammad Ali Ehsan]], [[https://openalex.org/A5070599716][Amir Habib]], [[https://openalex.org/A5027392055][Naseer Iqbal]], Journal of Taibah University for Science. 18(1)] 2024. https://doi.org/10.1080/16583655.2024.2312597  ([[https://www.tandfonline.com/doi/pdf/10.1080/16583655.2024.2312597?needAccess=true][pdf]])
     
An effective low-cost nano NiO-In2O3 electrode material for oxygen evolution (OER) is presented. Electrochemical studies uncovered electrocatalytic recital in Ascorbic Acid, Hydrogen Peroxide (H2O2), and ethanol. The cubic crystal structure of NiO-In2O3 was revealed by XRD. FT-IR, FE-SEM and HR-TEM studies exploit the structure and morphology of NiO-In2O3. Electrochemistry of NiO-In2O3 uncovered high current density (900mA/cm2) at substantially low overpotential (230mV), realizing its OER recital. On top, high mass activity and turnover frequency by NiO-In2O3 comprehend improved electrical and semiconductive properties in H2O2. The NiO-In2O3 durability beyond 90 hours was estimated by chronopotentiometry (CP). The Impedance analysis (EIS) revealed low charge transfer resistance and high exchange current density. Given electrocatalytic studies, we found a direct relationship between NiO-In2O3 nanocomposite and the degradation of H2O2 compared to its counterparts. Hence, this strategy can be an alternative and potential source of hydrogen and oxygen production at commercial scale.    

    

* Insights into the active nickel centers embedded in graphitic carbon nitride for the oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391581239
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ta07389k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391581239"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391581239"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391581239"))][Get cited by]]

OpenAlex: https://openalex.org/W4391581239 (Open access: True)
    
[[https://openalex.org/A5026698318][Nicolò Rossetti]], [[https://openalex.org/A5012980073][Aldo Ugolotti]], [[https://openalex.org/A5009780201][Claudio Cometto]], [[https://openalex.org/A5020884368][Verónica Celorrio]], [[https://openalex.org/A5016652154][Goran Dražić]], [[https://openalex.org/A5076721274][Cristiana Di Valentin]], [[https://openalex.org/A5023100324][Laura Calvillo]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d3ta07389k  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ta/d3ta07389k][pdf]])
     
Experimental and theoretical studies have demonstrated that the use of single atom catalysts (SACs) for energy conversion processes is very promissing. However, their stability under catalytic conditions is the main...    

    

* Co and Fe bimetallic MOF for enhanced electrocatalytic oxygen evolution performance: Exploring the electronic environment modifications upon Fe incorporation  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391582191
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ya00572k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391582191"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391582191"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391582191"))][Get cited by]]

OpenAlex: https://openalex.org/W4391582191 (Open access: True)
    
[[https://openalex.org/A5006570436][Varsha Singh]], [[https://openalex.org/A5023966920][Devesh Kumar Singh]], [[https://openalex.org/A5076671117][Mamta Yadav]], [[https://openalex.org/A5050132568][Sunil Kumar Singh]], [[https://openalex.org/A5093571140][Vikram Rathour]], [[https://openalex.org/A5064812434][Ananya Tiwari]], [[https://openalex.org/A5037060080][Vellaichamy Ganesan]], Energy advances. None(None)] 2024. https://doi.org/10.1039/d3ya00572k  ([[https://pubs.rsc.org/en/content/articlepdf/2024/ya/d3ya00572k][pdf]])
     
The incorporation of iron into the cobalt-based metal-organic framework (Co-MOF) modifies the electronic environment and the resulting bimetallic MOF exhibits an enhanced oxygen evolution reaction (OER). Co-MOF, Fe-MOF, and different...    

    

* Tailored nanocomposite FeNiB/MnO2/rGO@NF electrocatalyst for highly efficient and stable oxygen evolution reaction in freshwater and seawater environments  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391589896
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.mtchem.2024.101957")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391589896"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391589896"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391589896"))][Get cited by]]

OpenAlex: https://openalex.org/W4391589896 (Open access: False)
    
[[https://openalex.org/A5077083284][Min Jong Song]], [[https://openalex.org/A5011462871][Xue Yang]], [[https://openalex.org/A5050384919][Junwei Ma]], [[https://openalex.org/A5012665072][Xiaoyan Deng]], [[https://openalex.org/A5087397767][Hongtao Gao]], Materials Today Chemistry. 36(None)] 2024. https://doi.org/10.1016/j.mtchem.2024.101957 
     
Efficient and stable electrocatalysts are of paramount importance for addressing the slow kinetics of the Oxygen Evolution Reaction (OER). In this study, we employ a robust strategy focusing on precise electronic modulation through nanocomposite structural engineering. FeNiB/MnO2/rGO@NF nanocomposites have been synthesized using a continuous hydrothermal method, with fine-tuned adjustments in the Ni/Fe ratio and boride content. The optimized composite, characterized by a Ni: Fe ratio of 2:1 and subjected to five boronization cycles, exhibited exceptional electrocatalytic performance in both alkaline freshwater (1.0 M KOH) and simular alkaline seawater (1.0 M KOH + 0.5 M NaCl). These materials achieved impressively low overpotentials of 266 mV and 276 mV to drive OER at 100 mA cm−2 in freshwater and seawater. Remarkably low Tafel slopes of 52.97 mV·dec−1 and 73.11 mV·dec−1 in alkaline freshwater and seawater, respectively, highlight their outstanding performance. The distinctive FeNiB/MnO2/rGO@NF composite amorphous structure emerges as a potent approach to fine-tune the catalyst's electronic configuration, significantly boosting OER performance. The incorporation of MnO2 within the rGO framework further mitigates agglomeration while creating additional catalytically active sites. This not only amplifies charge transfer capacity but also enhances overall electrochemical performance. The presence of nickel-iron boride renders the catalyst suitable for challenging seawater conditions, such as high salinity and corrosiveness. This study introduces a streamlined yet highly effective approach, offering a feasible and scalable route for crafting robust non-precious metal electrocatalysts tailored for OER applications in both freshwater and seawater environments.    

    

* Interplay Between Element-Specific Distortions and Electrocatalytic Oxygen Evolution for Cobalt-Iron Hydroxides  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391592838
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.21203/rs.3.rs-3290074/v2")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391592838"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391592838"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391592838"))][Get cited by]]

OpenAlex: https://openalex.org/W4391592838 (Open access: True)
    
[[https://openalex.org/A5003731097][Rodney D. L. Smith]], [[https://openalex.org/A5029749427][Elif Pınar Alsaç]], [[https://openalex.org/A5056806530][Marc Böke]], [[https://openalex.org/A5070835650][Justine Bissonnette]], Research Square (Research Square). None(None)] 2024. https://doi.org/10.21203/rs.3.rs-3290074/v2  ([[https://www.researchsquare.com/article/rs-3290074/latest.pdf][pdf]])
     
Abstract A microscopic understanding of how Fe-doping of Co(OH) 2 improves electrocatalytic oxygen evolution remains elusive. We study two Co 1-x Fe x (OH) 2 series that differ in fabrication protocol and find composition alone poorly correlates to catalyst performance. Structural descriptors extracted using X-ray diffraction, X-ray absorption spectroscopy, and Raman spectroscopy reveal element-specific distortions in Co 1-x Fe x (OH) 2 . These structural descriptors are composition-dependent within individual sample series but inconsistent across fabrication protocols, revealing fabrication-dependence in catalyst microstructure. Correlations between structural parameters from different techniques show that Fe-O resists bond length changes, forcing distortion of Co environments. We find the difference in O-M-O bond angles between Co and Fe sites to correlate with electrocatalytic behavior across both sample series, which we attribute to asymmetric distortion of potential energy surfaces for the Co(III) to Co(IV) oxidation. A Tafel slope consistent with a rate-limiting step without electron transfer emerges as the O-Co-O angle decreases, implying a distortion-induced transition in rate-limiting step. The fabrication dependence of electronic and bonding structure in the catalysts should be considered in theoretical and high-throughput analyses of electrocatalyst materials.    

    

* Synthesis and Oxygen Evolution Reaction Application of a Co‐Cd Based Bimetallic Metal‐Organic Framework  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391593271
:TOPICS: Chemistry and Applications of Metal-Organic Frameworks, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/asia.202301039")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391593271"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391593271"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391593271"))][Get cited by]]

OpenAlex: https://openalex.org/W4391593271 (Open access: False)
    
[[https://openalex.org/A5042665195][Syed Shaheen Shah]], [[https://openalex.org/A5063349699][Ahmed Albadrani]], [[https://openalex.org/A5048307198][Mohammed Fettouhi]], [[https://openalex.org/A5067724271][Md. Abdul Aziz]], [[https://openalex.org/A5088210851][Aasif Helal]], Chemistry-An Asian Journal. None(None)] 2024. https://doi.org/10.1002/asia.202301039 
     
In the realm of renewable energy technologies, the development of efficient and durable electrocatalysts is paramount, especially for applications like electrochemical water splitting. This research focuses on synthesizing a novel bimetallic metal‐organic framework (BMMOF11) using earth‐abundant elements, cobalt (Co) and cadmium (Cd). BMMOF11 showcases a distinctive structure with distorted octahedral chains of CoO and CdO, linked by benzene tricarboxylic acid (BTC). Our study primarily investigates the electrocatalytic efficiency of BMMOF11, particularly in water oxidation reactions. For practical analysis, BMMOF11 was anchored onto nickel foam, forming BMMOF11/NF, to evaluate its electrocatalytic properties. Electrochemical testing revealed that BMMOF11/NF begins water oxidation at an onset potential of 1.62 V versus RHE, demonstrating high activity with a lower overpotential of 0.4 V to achieve a current density of 10 mA/cm². Moreover, BMMOF11/NF maintained stable water splitting performance, sustaining a current density of approximately 70 mA/cm2 under a voltage of 1.9 V relative to RHE. These findings indicate that BMMOF11/NF is a promising candidate for large‐scale electrochemical water splitting, offering a blend of high activity and stability    

    

* Measurement of Enthalpy and Entropy of a Model Electrocatalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391605478
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cctc.202301578")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391605478"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391605478"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391605478"))][Get cited by]]

OpenAlex: https://openalex.org/W4391605478 (Open access: True)
    
[[https://openalex.org/A5068808479][Joaquín Morales-Santelices]], [[https://openalex.org/A5068195942][Marcel Risch]], ChemCatChem. None(None)] 2024. https://doi.org/10.1002/cctc.202301578  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cctc.202301578][pdf]])
     
Experimentally determined thermodynamic parameters are rarely reported for electrocatalytic reactions including the oxygen evolution reaction (OER). Yet, they contain unique and valuable mechanistic insight and present a missing link to theoretical investigations. Herein, a protocol for determining thermodynamic properties of the rate determining state and intermediate (RDSI) of the OER is presented. Cobalt oxide is investigated at pH 7 as a case study. Two different approaches are employed: steady state polarization (SSP) that uses chronopotentiometry at different temperatures and current values, and potentiostatic electrochemical impedance spectroscopy (PEIS) at different DC voltages and temperatures. The data is used to fit a 3D plane from which entropy and enthalpy of the RDSI are obtained. The data analysis requires an appropriate filtering of the data. Hence, we discuss suitable figures of merit for establishing appropriate filtering criteria. The values obtained are 0.72 and ‐0.39 eV (at 298 K) for enthalpic and entropic contributions, respectively. The obtained values are reproducible for both approaches and consistent with literature.    

    

* General Synthesis of Composition‐Tunable High‐Entropy Amorphous Oxides Toward High Efficiency Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391607819
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Advanced Materials for Smart Windows
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310786")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391607819"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391607819"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391607819"))][Get cited by]]

OpenAlex: https://openalex.org/W4391607819 (Open access: False)
    
[[https://openalex.org/A5019020896][Shunda Jiang]], [[https://openalex.org/A5019226659][Yihang Yu]], [[https://openalex.org/A5003452086][Huan He]], [[https://openalex.org/A5001556458][Zhiyuan Wang]], [[https://openalex.org/A5059496516][Runguo Zheng]], [[https://openalex.org/A5039667666][Hongyu Sun]], [[https://openalex.org/A5056512009][Yanguo Liu]], [[https://openalex.org/A5058380236][Dan Wang]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202310786 
     
Abstract High‐entropy materials have attracted much attention in the electrocatalysis field due to their unique structure, high chemical activity, and compositional tunability. However, the harsh and complex synthetic methods limit the application of such materials. Herein, a universal non‐equilibrium liquid‐phase synthesis strategy is reported to prepare high‐entropy amorphous oxide nanoparticles (HEAO‐NPs), and the composition of HEAO‐NPs can be precisely controlled from tri‐ to ten‐component. The non‐equilibrium synthesis environment provided by an excessively strong reducing agent overcomes the difference in the reduction potentials of various metal ions, resulting in the formation of HEAO‐NPs with a nearly equimolar ratio. The oxygen evolution reaction (OER) performance of HEAO‐NPs is further improved by adjusting the composition and optimizing the electronic structure. The Fe 16 Co 32 Ni 32 Mn 10 Cu 10 BO y exhibits a smaller overpotential (only 259 mV at 10 mA cm −2 ) and higher stability in OER compared with commercial RuO 2 . The amorphous high‐entropy structure with an optimized concentration of iron makes the binding energy of CoNi shift to a higher direction, promotes the generation of high‐valence active intermediates, and accelerates the OER kinetic process. The HEAO‐NPs have promising application potential in the field of catalysis, biology, and energy storage, and this work provides a general synthesis method for composition‐controllable high‐entropy materials.    

    

* Corrigendum: Synthesis of Graphite Oxide/Cobalt Molybdenum Oxide Hybrid Nanosheets for Enhanced Electrochemical Performance in Supercapacitors and the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391611920
:TOPICS: Materials for Electrochemical Supercapacitors, Catalytic Reduction of Nitro Compounds, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202400041")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391611920"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391611920"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391611920"))][Get cited by]]

OpenAlex: https://openalex.org/W4391611920 (Open access: True)
    
, ChemElectroChem. None(None)] 2024. https://doi.org/10.1002/celc.202400041  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/celc.202400041][pdf]])
     
ChemElectroChemEarly View e202400041 CorrigendumFree Access Corrigendum: Synthesis of Graphite Oxide/Cobalt Molybdenum Oxide Hybrid Nanosheets for Enhanced Electrochemical Performance in Supercapacitors and the Oxygen Evolution Reaction This article corrects the following: Synthesis of Graphite Oxide/Cobalt Molybdenum Oxide Hybrid Nanosheets for Enhanced Electrochemical Performance in Supercapacitors and the Oxygen Evolution Reaction Jahangeer Ahmed, Mohd Ubaidullah, Tokeer Ahmad, Norah Alhokbany, Saad M. Alshehri, Volume 6Issue 9ChemElectroChem pages: 2524-2530 First Published online: May 7, 2019 First published: 06 February 2024 https://doi.org/10.1002/celc.202400041AboutPDF ToolsRequest permissionExport citationAdd to favoritesTrack citation ShareShare Give accessShare full text accessShare full-text accessPlease review our Terms and Conditions of Use and check box below to share full-text version of article.I have read and accept the Wiley Online Library Terms and Conditions of UseShareable LinkUse the link below to share a full-text version of this article with your friends and colleagues. Learn more.Copy URL Share a linkShare onEmailFacebookTwitterLinkedInRedditWechat No abstract is available for this article. Early ViewOnline Version of Record before inclusion in an issuee202400041 RelatedInformation    

    

* Strong Interface Coupling Enables Stability of Amorphous Meta‐Stable State in CoS/Ni3S2 for Efficient Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391612685
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Formation and Properties of Nanocrystals and Nanostructures
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310387")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391612685"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391612685"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391612685"))][Get cited by]]

OpenAlex: https://openalex.org/W4391612685 (Open access: False)
    
[[https://openalex.org/A5037501466][Wei Luo]], [[https://openalex.org/A5000713707][Yanli Yu]], [[https://openalex.org/A5000234334][Yucheng Wu]], [[https://openalex.org/A5008091677][Wenbin Wang]], [[https://openalex.org/A5078715492][Yimin Jiang]], [[https://openalex.org/A5086277480][Wei Shen]], [[https://openalex.org/A5073741395][Rongxing He]], [[https://openalex.org/A5088398026][Wei Su]], [[https://openalex.org/A5092337974][Ming Li]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202310387 
     
Abstract Rational design of heterostructure catalysts through phase engineering strategy plays a critical role in heightening the electrocatalytic performance of catalysts. Herein, a novel amorphous/crystalline (a/c) heterostructure (a‐CoS/Ni 3 S 2 ) is manufactured by a facile hydrothermal sulfurization method. Strikingly, the interface coupling between amorphous phase (a‐CoS) and crystalline phase (Ni 3 S 2 ) in a‐CoS/Ni 3 S 2 is much stronger than that between crystalline phase (c‐CoS) and crystalline phase (Ni 3 S 2 ) in crystalline/crystalline (c/c) heterostructure (c‐CoS/Ni 3 S 2 ) as control sample, which makes the meta‐stable amorphous structure more stable. Meanwhile, a‐CoS/Ni 3 S 2 has more S vacancies (S v ) than c‐CoS/Ni 3 S 2 because of the presence of an amorphous phase. Eventually, for the oxygen evolution reaction (OER), the a‐CoS/Ni 3 S 2 exhibits a significantly lower overpotential of 192 mV at 10 mA cm −2 compared to the c‐CoS/Ni 3 S 2 (242 mV). An exceptionally low cell voltage of 1.51 V is required to achieve a current density of 50 mA cm −2 for overall water splitting in the assembled cell (a‐CoS/Ni 3 S 2 || Pt/C). Theoretical calculations reveal that more charges transfer from a‐CoS to Ni 3 S 2 in a‐CoS/Ni 3 S 2 than in c‐CoS/Ni 3 S 2 , which promotes the enhancement of OER activity. This work will bring into play a fabrication strategy of a/c catalysts and the understanding of the catalytic mechanism of a/c heterostructures.    

    

* Bulk‐Heterojunction Electrocatalysts in Confined Geometry Boosting Stable, Acid/Alkaline‐Universal Water Electrolysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391612925
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Photocatalytic Materials for Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-06
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/aenm.202303924")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391612925"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391612925"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391612925"))][Get cited by]]

OpenAlex: https://openalex.org/W4391612925 (Open access: False)
    
[[https://openalex.org/A5050892929][Gyu Yong Jang]], [[https://openalex.org/A5057483582][Sungsoon Kim]], [[https://openalex.org/A5054059476][Ja-Yeon Choi]], [[https://openalex.org/A5013048728][Jeong Hwan Park]], [[https://openalex.org/A5052142023][Soyeon An]], [[https://openalex.org/A5033839627][Jihyun Baek]], [[https://openalex.org/A5005523364][Yuzhe Li]], [[https://openalex.org/A5018680335][Teng Liu]], [[https://openalex.org/A5015146814][Eugene Kim]], [[https://openalex.org/A5080238951][Jung Hwan Lee]], [[https://openalex.org/A5041663670][Haotian Wang]], [[https://openalex.org/A5031401877][Min-Joong Kim]], [[https://openalex.org/A5045489385][Hyun‐Seok Cho]], [[https://openalex.org/A5063671472][Xiaolin Zheng]], [[https://openalex.org/A5002074895][Jong Suk Yoo]], [[https://openalex.org/A5021240329][Kwanyong Seo]], [[https://openalex.org/A5017792494][Jae Hyung Park]], Advanced Energy Materials. None(None)] 2024. https://doi.org/10.1002/aenm.202303924 
     
Abstract Alkaline water splitting electrocatalysts have been studied for decades; however, many difficulties remain for commercialization, such as sluggish hydrogen evolution reaction (HER) kinetics and poor catalytic stability. Herein, by mimicking the bulk‐heterojunction morphology of conventional organic solar cells, a uniform 10 nm scale nanocube is reported that consists of subnanometer‐scale heterointerfaces between transition metal phosphides and oxides, which serves as an alkaline water splitting electrocatalyst; showing great performance and stability toward HER and oxygen evolution reaction (OER). Interestingly, the nanocube electrocatalyst reveals acid/alkaline independency from the synergistic effect of electrochemical HER (cobalt phosphide) and thermochemical water dissociation (cobalt oxide). From the spray coating process, nanocube electrocatalyst spreads uniformly on large scale (≈6.6 × 5.6 cm 2 ) and is applied to alkaline water electrolyzers, stably delivering 600 mA cm −2 current for >100 h. The photovoltaic‐electrochemical (PV‐EC) system, including silicon PV cells, achieves 11.5% solar‐to‐hydrogen (STH) efficiency stably for >100 h.    

    

* Frontispiz: Anchoring Fe Species on the Highly Curved Surface of S and N Co‐Doped Carbonaceous Nanosprings for Oxygen Electrocatalysis and a Flexible Zinc‐Air Battery  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391613260
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-05
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202480761")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391613260"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391613260"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391613260"))][Get cited by]]

OpenAlex: https://openalex.org/W4391613260 (Open access: True)
    
[[https://openalex.org/A5025596795][Yanzhi Wang]], [[https://openalex.org/A5091584958][Taimin Yang]], [[https://openalex.org/A5004191746][Xingwang Fan]], [[https://openalex.org/A5081431423][Zijia Bao]], [[https://openalex.org/A5027341167][Akhil Tayal]], [[https://openalex.org/A5074586825][Huang Tan]], [[https://openalex.org/A5049862415][Mengxiao Shi]], [[https://openalex.org/A5056978567][Zuozhong Liang]], [[https://openalex.org/A5076699095][Wei Zhang]], [[https://openalex.org/A5071238079][Haiping Lin]], [[https://openalex.org/A5023594276][Rui Cao]], [[https://openalex.org/A5045207725][Zhehao Huang]], [[https://openalex.org/A5021383691][Haoquan Zheng]], Angewandte Chemie. 136(7)] 2024. https://doi.org/10.1002/ange.202480761  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/ange.202480761][pdf]])
     
Electrocatalysis. Haiping Lin, Zhehao Huang, Haoquan Zheng et al. report in their Research Article (e202313034) the anchoring of Fe species on the highly curved surface of S and N co-doped carbonaceous nanosprings for electrocatalytic oxygen reduction reaction.    

    

* Li+ Cations Activate NiFeOOH for Oxygen Evolution in Sodium and Potassium Hydroxide  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391614562
:TOPICS: Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202318692")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391614562"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391614562"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391614562"))][Get cited by]]

OpenAlex: https://openalex.org/W4391614562 (Open access: False)
    
[[https://openalex.org/A5033625892][Onno van der Heijden]], [[https://openalex.org/A5049961714][Jordy J.J. Eggebeen]], [[https://openalex.org/A5087146050][Hanna Trzesniowski]], [[https://openalex.org/A5021743372][Nipon Deka]], [[https://openalex.org/A5020266867][Ronny Golnak]], [[https://openalex.org/A5045077840][Jie Xiao]], [[https://openalex.org/A5093882643][Maartje van Rijn]], [[https://openalex.org/A5003052106][Rik V. Mom]], [[https://openalex.org/A5028485156][Marc T. M. Koper]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202318692 
     
The efficiency of green hydrogen production is reduced due to the sluggish oxygen evolution reaction (OER). In addition to the optimal catalyst properties, electrocatalytic activity also depends on the interaction of the electrocatalyst with the electrolyte. Here, we show that the addition of small amounts of Li+ to Fe‐free NaOH or KOH electrolytes activates NiFeOOH for the OER compared to single‐cation electrolytes. Moreover, the activation was maintained when the solution was returned to pure NaOH. Importantly, we show that the origin of activation by Li+ cations is primarily non‐kinetic in nature, as the OER onset for the mixed electrolyte does not change and the Tafel slope at low current density is ~30 mV/dec in both electrolytes. However, the increase of the apparent Tafel slope remains lower at increasing current densities in the presence of Li+. Based on electrochemical quartz crystal microbalance and in situ X‐Ray Absorption Spectroscopy measurements, we show that this reduction of non‐kinetic effects is due to enhanced intercalation of sodium, water and hydroxide in the Li+ activated catalyst. This enhanced electrolyte penetration facilitates the OER, especially at higher current densities and for increased catalyst loading, which is important for industrial electrolyzer systems.    

    

* An Effective Oxygen Evolution Catalyst  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391606168
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 1985-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1595/003214085x2912626")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391606168"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391606168"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391606168"))][Get cited by]]

OpenAlex: https://openalex.org/W4391606168 (Open access: False)
    
[[https://openalex.org/A5039831368][Tao Dou]], Platinum Metals Review. 29(1)] 1985. https://doi.org/10.1595/003214085x2912626 
     
No abstract    

    

* The Effect of Oxygen Vacancies on Oxygen Evolution: The Case of BiVO_4  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391639104
:TOPICS: Catalytic Nanomaterials, Catalytic Dehydrogenation of Light Alkanes, Gas Sensing Technology and Materials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472281mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391639104"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391639104"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391639104"))][Get cited by]]

OpenAlex: https://openalex.org/W4391639104 (Open access: False)
    
[[https://openalex.org/A5074525188][Nicklas Österbacka]], [[https://openalex.org/A5023146568][Hassan Ouhbi]], [[https://openalex.org/A5081702682][Julia Wiktor]], [[https://openalex.org/A5040182388][Francesco Ambrosio]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472281mtgabs 
     
Bismuth vanadate, BiVO 4 , is one of the most promising photoanode materials for the challenging oxygen evolution half-reaction in solar-driven water splitting. The material tends to be rich in oxygen vacancies, which strongly affects its photoelectrochemical properties. Experimental evidence suggests that oxygen deficiency is beneficial for the oxygen evolution reaction in the material, but the mechanism behind this enhancement is still controversial. The defects could be involved directly in the reaction if present at the surface, and the occupancy of the defect states could also play an important role. The latter is seldom considered in mechanistic studies, however. Using density functional theory, we show that the surface oxygen vacancy in bismuth vanadate is stablest when fully ionized. We investigate how this affects the oxygen evolution mechanism by mapping out the stablest reaction intermediates and compare the resulting pathway with those on the unionized oxygen-deficient surface as well as the defect-free material. The overpotentials required to drive the reaction in each case are computed to quantify whether or not vacancy formation, and subsequent ionization, improves the thermodynamics of oxygen evolution.    

    

* Electrodeposited Ni-Based Catalysts for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663002
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02201255mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663002"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663002"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663002"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663002 (Open access: False)
    
[[https://openalex.org/A5035874732][Yashwardhan Deo]], [[https://openalex.org/A5034662410][Niklas Thissen]], [[https://openalex.org/A5057402984][Anna K. Mechler]], ECS Meeting Abstracts. MA2023-02(20)] 2023. https://doi.org/10.1149/ma2023-02201255mtgabs 
     
Alkaline water electrolysis is one of the most mature technologies for producing green hydrogen. However, there still are possibilities to enhance this process by using better electrocatalysts for the kinetically limited oxygen evolution reaction (OER). While there are several existing methods for catalyst synthesis, such as spray coating, coprecipitation and hydrothermal synthesis, they face challenges of either versatility or scalability. [1,2] In this regard, electrodeposition is a promising catalyst synthesis method, due to its excellent process control and ease of scalability. In this work, electrodeposition is used to prepare nickel-based catalysts as a benchmark system. These catalysts are deposited on expanded Ni-mesh supports. Initially, the deposition parameters are optimized to obtain uniform Ni deposits, which provide reproducible activity measurements. Herein, we observe that the deposited Ni catalysts exhibit better OER activities than the Ni mesh support, most likely due to the evolution of a pyramidal morphology with an increased surface area (Fig. 1). The optimized deposition parameters are further used to deposit different Ni-based alloys such as Ni-Fe and Ni-Co, by adding the respective ionized metal species to the Ni electrolyte. The microstructure and composition of these catalysts is analyzed using material characterization techniques like scanning electron microscopy (SEM) and energy dispersive X-ray spectroscopy (EDX). Finally, the OER activity and long-term stability of the deposited catalysts is evaluated in an in-house developed electrochemical beaker cell at elevated concentration, temperature, and current densities (30 wt.% KOH, 80 °C, up to 1 A/cm 2 ). The results obtained for the different catalysts are compared to understand the correlation of the catalyst structure and composition with their electrochemical OER performance under industrial conditions. Bibliography [1] Lu Xunyu et al.; Nature Communications; DOI: 10.1038/ncomms7616 [2] Zuraya Angeles-Olvera et al.; Energies ; DOI: 10.3390/en15051609 Figure 1    

    

* Electrocatalytic Activities of High-Entropy Oxides for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638064
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542604mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638064"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638064"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638064"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638064 (Open access: False)
    
[[https://openalex.org/A5004247415][Yun-Hyuk Choi]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542604mtgabs 
     
Electrocatalytic water-splitting hydrogen generation consists of the cathodic hydrogen evolution reaction (HER) and the anodic oxygen evolution reaction (OER), where the four-electron-relevant OER is the rate-determining step. So far, there have been many efforts to substitute for the highly expensive noble-metal electrocatalysts (platinum, ruthenium or rhodium oxides, etc.). Transition-metal oxides based on Co, Ni, Mn, and V have been suggested as such alternatives, due to their low cost, high efficiency, and high stability. Recently, since the compositional diversity can provide a new breakthrough in that area, a high-entropy oxide (HEO) with five transition-metal cations has been suggested as a promising electrocatalyst toward the OER. In our studies, two kinds of HEOs were prepared and their OER activities were investigated. To begin with, for the (Mg 0.2 Fe 0.2 Co 0.2 Ni 0.2 Cu 0.2 )O, the effect of constituent cations on the OER activity was unveiled. Furthermore, a core cation driving the high OER activity was found. For it, the medium-entropy oxides (MEOs) with four cations are prepared by subtracting each cation (Mg, Fe, Co, Ni, or Cu) from the HEO, exhibiting homogeneous morphology, equiatomic composition, and single-phase rocksalt structure. As a result, it is found that the highest concentration of Co 3+ in the MEO (w/o Cu) leads to the best OER activity, and thus Co 3+ is the core ion driving the high OER activity. Furthermore, it is regarded that Cu 2+ ions prevent the conversion of Co or Fe cations from 2 + to 3 + in the HEO and MEOs. Accordingly, maximizing the concentration of Co 3+ within electrocatalysts is suggested as an effective design strategy for the high-efficiency electrocatalysts based on high or medium entropy materials. Secondly, the relationship between structure and OER activity was elucidated for the (Mg 0.2 Fe 0.2 Co 0.2 Zn 0.2 Cu 0.2 )O with a temperature-dependent rocksalt-to-spinel transition.    

    

* Oxygen Evolution Reaction with ZrCo and ZrNi Electrode Materials  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638760
:TOPICS: Fuel Cell Membrane Technology, Nuclear Fuel Development, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422147mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638760"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638760"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638760"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638760 (Open access: False)
    
[[https://openalex.org/A5050317844][Sylvain Le Tonquesse]], [[https://openalex.org/A5021396945][S. G. Altendorf]], [[https://openalex.org/A5072072076][Yuri Grin]], [[https://openalex.org/A5083007953][Iryna Antonyshyn]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422147mtgabs 
     
Investigation of the intermetallic compounds as anode materials for water electrolysis helps to solve a lot of issues, which electrocatalysis and solid state chemistry communities face nowadays. Intermetallic compounds possess unique properties in terms of their crystal structure, electronic properties and chemical bonding, allowing the knowledge-based route for electrocatalyst development. Furthermore, usage of the single-phase anode material is a way to exclude the influence of interface as well as nature and stability issues of the support. At the same time, studies of the intermetallic compounds under the reaction conditions shed light onto the chemical properties of the intermetallic compounds, which are scarcely described in literature and of particular importance for solid state chemistry field. In this study, binary intermetallic compounds ZrCo and ZrNi were studied as anode materials for alkaline water electrolysis. The successful synthesis of single-phase samples of both compounds was followed by manufacturing of the cylindrically-shaped electrodes using spark plasma sintering technique. The assessment of the electrocatalytic performance was carried out in three-electrode cell, applying different measurement protocols, giving the information about OER activity of studied materials, its stability over time as well as other electrochemical features, giving the information about the processes occurring on the electrode surfaces. To monitor the material changes under conditions of OER, the electrodes were comprehensively characterized before and after the electrochemical experiments using bulk- and surface-sensitive techniques. Combined data was discussed and compared with state-of-the-art OER electrocatalysts for alkaline media.    

    

* Gas Diffusion Electrode for Oxygen Evolution Reaction Catalyst Testing  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638856
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02371726mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638856"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638856"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638856"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638856 (Open access: False)
    
[[https://openalex.org/A5056872364][Vinod Kumar Puthiyapura]], [[https://openalex.org/A5030674093][Christopher Mark Zalitis]], [[https://openalex.org/A5015505628][James Stevens]], ECS Meeting Abstracts. MA2023-02(37)] 2023. https://doi.org/10.1149/ma2023-02371726mtgabs 
     
The oxygen evolution reaction (OER) is one of the major contributors of efficiency loss in water electrolysis and consequently, development of OER catalysts to improve the electrolyser efficiency is a major reasearch theme in the field. Though the current commercial PEMWE may operate at anode potential <1.60 V, futue PEMWE may operate at potential higher than this as the drive to operate PEMWE at high current density is inceasing. Inorder to achieve this, an active and stable catalyst is required that can operate at this regime. Also, the potential experienced by the anode during the startup/shutdown of an electrolyser are different to the steady state value. Conventional OER testing involves catalysts coated on a conductive substrate submerged in an electrolyte solution, in a three electrode cell. However, such techniques are generally limited to low current densities due to oxygen bubble formation and site blocking at high current density limiting the system to study the OER kinetics below realistic operating current density. Although Rotating Disk Electrode(RDE) is widely employed to mitigate this, the RDE system is still not effective enough to remove the bubbles 1 . A floating electrode system developed by Kucernak et al 2 shows that combining direct access with a lower catalyst loading improves the O 2 gas mass transport and a higher current density could be achieved for the ORR. This technique also used for OER by Arenz et al. 3 , for easier bubble removal. Combining these two above mentioned systems, we have developed a new GDE cell system which allows screening of OER catalyst at industrially relevant current densities. This cell allows to study the OER kinetics at very realistic voltage/current regime and the information obtained helps to develop more active/stable catalyst. The OER catalyst diagnostics test from our GDE cell was comparable to the standard three electrode cell with an additional advantage of extended potential window upto 1.80 V vs.RHE. Preliminary results obtained from our study shows a promising opportunity to study the OER at high current densities. Reference FathiTovini, A.Hartig-Weiß, H.A.Gasteigerand, H.A.El Sayed, Journal of The ElectrochemicalSociety, 2021, 168, 014512. M.Zalitis,D.KramerandA.R.Kucernak,Phys.Chem.Chem.Phys.,2013,15,4329-4340 Schröder,V.A.Mints,A.Bornet,E.Berner,M.FathiTovini,J.Quinson,etal., JACS Au 2021,1(3),247-25    

    

* Spin States and Spin Order in Perovskite Oxide Oxygen Evolution Electrocatalysts  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638550
:TOPICS: Electrocatalysis for Energy Conversion, Perovskite Solar Cell Technology, Conducting Polymer Research
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02472304mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638550"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638550"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638550"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638550 (Open access: False)
    
[[https://openalex.org/A5021753479][Emma van der Minne]], [[https://openalex.org/A5015341693][Achim Füngerlings]], [[https://openalex.org/A5009841458][Marcus Wohlgemuth]], [[https://openalex.org/A5060923565][Gertjan Koster]], [[https://openalex.org/A5029467045][Felix Gunkel]], [[https://openalex.org/A5057481702][Rossitza Pentcheva]], [[https://openalex.org/A5012106030][Christoph Baeumer]], ECS Meeting Abstracts. MA2023-02(47)] 2023. https://doi.org/10.1149/ma2023-02472304mtgabs 
     
The ‘power-to-hydrogen’ strategy aims at splitting water into O 2 and H 2 via the oxygen and hydrogen evolution reactions. The complex four-step oxygen evolution reaction (OER) limits the overall efficiency of hydrogen production. An important reason of the low efficiency is that the production of ground-state (triplet) O 2 is a spin-forbidden reaction: in fact, the reactants, OH - or H 2 O, are diamagnetic, but the final product, O 2 , is a paramagnetic molecule. Recently, this was well-recognized theoretically 1 and the use of spin selective catalysts was described as a possible way to promote the OER. 2 . However, it remains complex to understand and exploit intrinsic and extrinsic magnetic features to enhance catalytic performance. Here, we investigate the role of magnetic moments in individual active sites in the catalyst surface layer and the role of spin order in ferromagnetic vs. paramagnetic catalysts, focussing on perovskite oxides. First, we investigated the role of Ni magnetic moment in the the (001), (110) and (111) facet of LaNiO 3 electrocatalysts, which we studied using electrochemical measurements, X-ray photoelectron spectroscopy (XPS), X-ray absorption spectroscopy (XAS), and density functional theory (DFT+ U ) calculations. 3 The results show a facet-dependent activity, where the (111) overpotential is ~60 mV lower as compared to the other facets. Closer investigation of the (001) and (111) facets reveals a surface transformation to a oxyhydroxide-like NiOO with edge-sharing octahedra, 4 and we observed that the transformed surface is thicker for (111) than for (001). 3 The detailed DFT+ U analysis reveals important distinctions that give rise to the increased activity: the transformed LaNiO 3 (111) surface exhibits a better match to the underlying perovskite layer. Moreover, protonation induces reduced Ni 3+ with a finite magnetic moment. A moderate Jahn-Teller distortion enables a favorable binding of reaction intermediates. In contrast, the structural mismatch to the underlying LaNiO 3 (001)-substrate leads to a strong distortion of the transformed layer for this orientation and a weak binding of *O and ultimately to a different potential determining step (PDS), *OH→*O, compared to *O→*OOH for the transformed LaNiO 3 (111) surface. Second, we experimentally demonstrate the effect of intrinsic magnetic order on the OER on catalytic performance. Thin films of La 0.67 Sr 0.33 MnO 3 grown by pulsed laser deposition with appropriate magnetic and electronic properties were chosen as well-defined model systems. Using the ferromagnetic to paramagnetic transition at the Curie temperature in these ferromagnetic perovskite oxides, the magnetic order of the catalysts were switched in situ during the OER by changing the temperature. For ferromagnetic films, the decrease in current density with decreasing temperature, induced by the reduction of thermal energy, was suppressed for temperatures below the Curie temperature, indicating that the presence of ferromagnetic ordering below Curie temperature enhances OER activity. This claim is further supported by an enhancement of OER activity for the same ferromagnetic film upon alignment of magnetic domains with an external magnetic field. All in all, our results reveal that the spin state, intrinsic spin order, and extrinsic magnetic fields are decisive for the OER activity. Biz, C., Fianchini, M. & Gracia, J. Strongly Correlated Electrons in Catalysis: Focus on Quantum Exchange. ACS Catal 11 , 14249–14261 (2021). Sun, Y. et al. Spin‐Related Electron Transfer and Orbital Interactions in Oxygen Electrocatalysis. Advanced Materials 32 , 2003297 (2020). Füngerlings, A. et al. Crystal-facet-dependent surface transformation dictates the oxygen evolution reaction activity in lanthanum nickelate. in preparation (2023). Baeumer, C. et al. Tuning electrochemically driven surface transformation in atomically flat LaNiO 3 thin films for enhanced water electrolysis. Nat Mater 20 , 674–682 (2021).    

    

* Understanding the Role of Cracks in Active Oxygen Species Formation during Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663336
:TOPICS: Reinforcement Corrosion in Concrete Structures, Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02653164mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663336"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663336"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663336"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663336 (Open access: False)
    
[[https://openalex.org/A5064222985][Sihong Wang]], [[https://openalex.org/A5081133273][Fang Song]], ECS Meeting Abstracts. MA2023-02(65)] 2023. https://doi.org/10.1149/ma2023-02653164mtgabs 
     
Understanding the formation and location of catalytic intermediates is crucial for unraveling the mechanism of oxygen evolution reaction (OER), a key process in electrochemical water splitting. Despite the availability of various in-situ and ex-situ characterization methods, the formation and location of intermediates remain elusive, hindering the development of more efficient electrocatalysts. In this work, we discovered a stable static active oxygen species formed during the chemical oxidation of cobalt hydroxide flakes, providing a unique opportunity to probe the intermediates involved in OER. We are able to monitor the equilibrium conversion between stable peroxo structure and superoxo radical via EPR and Raman test, shedding light on the nature of the active oxygen species. In addition, CoOOH flakes with cracks were synthesized via controlled chemical oxidation, enabling the investigation of the role of crack/edge structures in the electrocatalytic activity. Statistical regression analysis combining morphological features, electrochemical performance, and Raman spectroscopy confirmed a strong correlation between morphology evolution, OER activity, and active oxygen species, highlighting the importance of controlling the morphology of electrocatalysts for enhancing their performance. Therefore, we propose that the source of active oxygen intermediates can be attributed to the presence of crack/edge structures. The crack-rich CoOOH exhibit significantly higher current density at a lower overpotential, providing a new direction for the design of efficient water oxidation electrocatalysts. Overall, this work offers important insights into the mechanism of OER and provides a basis for the development of more efficient and sustainable electrocatalysts for energy conversion and storage.    

    

* Tungsten Oxide-Based Materials as Catalyst Support for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663247
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422096mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663247"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663247"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663247"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663247 (Open access: False)
    
[[https://openalex.org/A5044676059][Yung‐Tin Pan]], [[https://openalex.org/A5093893761][Lu Yu Chueh]], [[https://openalex.org/A5002345502][Yu-Wei Hsu]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422096mtgabs 
     
The high cost of iridium (Ir) is a major concern for the large scale deployment of polymer electrolyte membrane water electrolysis (PEMWE). To mitigate its impact, the usage of Ir on the anode must be significantly reduced. Down-sizing the catalyst particle is a straight forward strategy but requires the use of appropriate support materials to disperse and anchor fine Ir nanoparticles. We have investigated the use of tungsten oxide-based materials as support for the oxygen evolution reaction (OER) Ir and ruthenium (Ru) catalyst. The synthesis of nanostructured substoichiometric tungsten oxide and the subsequent loading of ultrafine Ir/Ru-based nanoparticles is thoroughly studied. Due to the successful loading, the mass activity of the tungsten oxide-supported Ir/Ru-based catalyst shows significant improvements under rotating disk electrode (RDE) conditions compared with commercially available Ir/Ru-blacks. Furthermore, non-destructive depth profiling by synchrotron-based X-ray photoelectron spectroscopy (XPS) has revealed the strong catalyst-support interaction which suppressed the oxidation of the supported Ir/Ru-based catalysts, leading to much enhanced durability under accelerated durability testing conditions. To verify its performance under practical PEM electrolysis conditions, the tungsten oxide-supported OER catalyst is directly coated onto a polymer electrolyte membrane, i.e., forming a catalyst coated membrane (CCM), and tested under single cell testing conditions without pressure differential. The voltage dependent chemical state of the supported catalyst is also probed in-situ by synchrotron-based XPS where a potential dependent electron transfer between the catalyst and tungsten-oxide support is discovered. Our discovery is anticipated to aid the development of cost effective PEM electrolysis anodes.    

    

* Ionomer-Dependent Oxygen Evolution Reaction in a Half-Cell and a Liquid Electrolyzer  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638465
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02391892mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638465"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638465"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638465"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638465 (Open access: False)
    
[[https://openalex.org/A5015545381][Joy Marie Mora]], [[https://openalex.org/A5086997032][Guangfu Li]], [[https://openalex.org/A5048183453][Po‐Ya Abel Chuang]], ECS Meeting Abstracts. MA2023-02(39)] 2023. https://doi.org/10.1149/ma2023-02391892mtgabs 
     
Electrocatalytic oxygen evolution reaction (OER) is an important area of research due to its significance in water electrolysis, which contributes to the clean-energy storage and conversion techniques. OER exhibits irreversible and sluggish kinetics, which necessitates a high overpotential to achieve the desired reaction rate. In an alkaline medium, non-precious metals (such as Ni, Fe, Co) or metal-free materials (such as 3d-transition metal oxides and heteroatom-doped carbons) can replace expensive iridium and ruthenium oxides, which is otherwise required in an acidic medium to facilitate the reaction. However, developing new catalysts for alkaline OER is limited by the scaling relations among adsorption energetics of key intermediates (i.e., OOH*, OH*, and O*). The electrochemical reaction kinetics depends critically on the nature of the interface between catalyst and the electrolyte where an electrical double layer (EDL) forms during OER. The current understanding of the EDL structure involves the interfacial interactions between adsorbates and catalyst layer (CL) which can be modified to improve the reaction efficiency. Ionomers are essential components of the CL and are vital in uniformly dispersing catalyst particles in ink solution. The ionomers also act as binder for the catalyst particles in the CL, helping to improve the electrode’s durability and stability over time. In addition, despite the fact that ionomers affect the properties of EDL, the impact of ionomer on the reaction pathway is often overlooked in electrocatalytic research. In this study, we investigate the role of ionomer in the catalyst layer by comparing different polymer dispersions, including PTFE, Nafion, and commercial As-4. The results indicate that the Nafion-contained CL performs better than other polymer CLs in TF-RDE/RRDE, as it facilitates direct O*-O* coupling. In contrast, anionic ionomer demonstrates superior long-term stability in alkaline liquid electrolyzers, despite oxidization degradation.    

    

* Insights into the Structure Sensitivity of Fe-Based Materials for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663581
:TOPICS: Electrocatalysis for Energy Conversion, Solar Water Splitting Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542547mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663581"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663581"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663581"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663581 (Open access: False)
    
[[https://openalex.org/A5075460624][Ricardo Alberto Hincapié Isaza]], [[https://openalex.org/A5026566541][Viktor Čolić]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542547mtgabs 
     
The conversion of renewable energy into storable fuels is fundamental to the meeting of the net-zero CO 2 emissions objective by 2050. However, the sluggish kinetics of the oxygen evolution reaction (OER) and the poor stability of electrocatalysts at industrial-level currents remain a problem for electrolyzers 1 . Using platinum group metal-free electrocatalysts in anion exchange membrane electrolyzers is an appealing strategy to overcome some of the problems associated with PEM electrolyzers. Fe-based materials offer the possibility for the development of active, stable, and cost-effective electrocatalysts for the OER in alkaline media. In this work, we explore the influence of structure, composition, or crystalline phase on different Fe-based electrodes for the OER. Different fabrication procedures such as additive manufacturing 2 , flame spray synthesis, or pulse laser ablation 3 allow us to have a wide range of Fe-based materials with a well-defined structure/composition/phase. The materials have been extensively characterized by physicochemical methods (XPS, Raman, XRD, ICP) and their electrocatalytic activity evaluates following careful procedures in order to obtain reliable results. The results show that the activity of Fe-rich electrodes is poor. However, if Fe is alloyed with other materials or its surface structure or crystallinity degree is modified, it results in a more active material. This information could guide the synthesis of more active and stable water-splitting materials. References S. Cherevko, S. Geiger, O. Kasian, N. Kulyk, J.-P. Grote, A. Savan, B. R. Shrestha, S. Merzlikin, B. Breitbach, A. Ludwig, and K. J. J. Mayrhofer, Catalysis Today, 262 170-180 (2016). J. Wegner, R. Martínez-Hincapié, V. Čolić, and S. Kleszczynski, Advanced Materials Interfaces, n/a (n/a), 2202499 (2023). J. Johny, Y. Li, M. Kamp, O. Prymak, S.-X. Liang, T. Krekeler, M. Ritter, L. Kienle, C. Rehbock, S. Barcikowski, and S. Reichenberger, Nano Research, 15 (6), 4807-4819 (2022).    

    

* Iridium Single Atom Catalysts for Oxygen Evolution Reaction in Acidic Medium  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638495
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Catalytic Nanomaterials
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422087mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638495"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638495"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638495"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638495 (Open access: False)
    
[[https://openalex.org/A5093888179][Jean Rouger]], [[https://openalex.org/A5035038630][Sara Cavaliere]], [[https://openalex.org/A5015338172][Frédéric Jaouen]], [[https://openalex.org/A5046537142][Deborah J. Jones]], [[https://openalex.org/A5080444382][Fabien Dufour]], [[https://openalex.org/A5042428372][Maureen Georges]], [[https://openalex.org/A5004000315][Julien Thuilliez]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422087mtgabs 
     
In order to reduce CO 2 emissions and produce clean hydrogen one solution is to use sustainable energies (wind, solar or hydraulic) coupled with water electrolyser to produce H 2 and store it before use it in fuel cell. The electrolyzer based on proton exchange membranes (PEM) is a promising technology because it can reach high current density (2 A.cm -2 ) [1] and can be easily coupled with intermittent energy sources [2]. However, the acidic conditions and working temperatures (80 °C) require the use of noble metals. On the anode side the oxidative condition prevents the use of carbon supported catalyst and the best catalyst for the oxygen evolution reaction (OER) so far is IrO x . The use of Ir single atom catalyst (SAC) supported on conducting oxide is a promising way to reduce the quantity of the scarce and expensive noble metal, increasing the electroactive surface and durability. SACs present an excellent dispersion and activity [3] and some conducting oxides are very promising regarding electrical conductivity and stability under oxidative conditions [4]. There are different approaches to prepare Ir SAC (wet impregnation, co-precipitation, photoelectrochemical reduction...) [3], whose success mainly depends on the nature of the Ir precursor, its interaction with the support and the thermal treatment temperature/duration. Some research groups have prepared and characterized Ir SAC on indium-tin oxide [5] but the activity and stability still need to be improved. The objective of this communication is to present the synthesis and the characterization of Ir SAC on different conducting oxide supports. Ir precursor was synthesized and deposed on various supports. The physical characterization entails XRD, TEM, MEB, EDX to assess the morphology and composition of the catalyst. Spectroscopic analysis like XPS and XAS brings information on the chemical environment of Ir sites, while electrochemical measurements give information on the OER activity and stability of the catalyst. References [1] C.D. Ferreira da Silva et al. , ACS Catal. , 2021 , 11, 4107-4116 [2] O. Schmidt et al. , Int. J. Hydrog. Energy , 2017 , 42, 30471-30492 [3] J. Liu, ACS Catal. , 2017 , 7, 34-59 [4] Moriau et al. , ChemCatChem , 2022 , 14, e202200586 [5] D. Lebedev et al., ACS Cent. Sci. 2020 , 6, 1189-1198 [6] Q. Wang et al. , ACS Catal., 2020 , 142, 7425-7433    

    

* Theoretical Study on Inhibition of Oxygen Evolution in Layered Cathode Materials during Charging  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391662769
:TOPICS: Lithium-ion Battery Management in Electric Vehicles, Lithium-ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-025828mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391662769"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391662769"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391662769"))][Get cited by]]

OpenAlex: https://openalex.org/W4391662769 (Open access: False)
    
[[https://openalex.org/A5079893811][Kuan-Yu Lin]], [[https://openalex.org/A5009770522][Shaohui Xu]], [[https://openalex.org/A5088941900][Santhanamoorthi Nachimuthu]], [[https://openalex.org/A5037150692][Jyh‐Chiang Jiang]], ECS Meeting Abstracts. MA2023-02(5)] 2023. https://doi.org/10.1149/ma2023-025828mtgabs 
     
In recent years, Ni, Mn-based layered cathode materials (Li 1.2 Ni 0.2 Mn 0.6 O 2 , LiNi 1-x-y Co x Mn y O 2 ) have shown great promise for high energy density LIBs. Research has shown that nickel-rich materials are ideal candidates for high-capacity batteries. The valence state from Ni 2+ to Ni 4+ allows more Li + to transfer between the cathode and anode, providing excellent electrochemical performance. However, the oxidation of oxygen atoms triggers irreversible structural rearrangements on the surface, while Ni 3+ introduces Jahn-Teller distortion. At high voltages, the stability of layered cathode materials is severely hampered. We present theoretical work on Li 1.2 Ni 0.2 Mn 0.6 O 2 and LiNi 1-x-y Co x Mn y O 2 using density functional theory, considering cation- and anion-doped surface treatments. We found that doped layered cathode materials successfully suppressed O 2 formation at highly delithiated levels. Through DFT calculations, we understand the mechanism of oxygen evolution from layered cathode materials during the charging process and discover how to suppress oxygen evolution strategies.    

    

* The Interplay of Anodic Passivation and Oxygen Evolution of Medium Entropy Alloys in Artificial Seawater  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391639471
:TOPICS: Atom Probe Tomography Research, High-Entropy Alloys: Novel Designs and Properties, Thermal Barrier Coatings for Gas Turbines
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02111073mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391639471"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391639471"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391639471"))][Get cited by]]

OpenAlex: https://openalex.org/W4391639471 (Open access: False)
    
[[https://openalex.org/A5076601076][Annica Wetzel]], [[https://openalex.org/A5072476528][Özlem Özcan]], [[https://openalex.org/A5044822731][Julia Witt]], [[https://openalex.org/A5093888344][Daniel Morell]], ECS Meeting Abstracts. MA2023-02(11)] 2023. https://doi.org/10.1149/ma2023-02111073mtgabs 
     
Medium entropy alloys (MEA) have gained increased interest in both academic and industrial sectors due to their favorable mechanical and anti-corrosion properties, rendering them ideal candidates for engineering and potentially catalytic applications. Although previous studies have shown high current densities at high anodic potentials for MEAs, a lack of understanding on the underlying transpassive dissolution and local corrosion behavior remains. This project aimed to investigate and compare the passivation behavior of MEAs CrCoNi and FeCrNi (equimolar) under high anodic potentials, focusing on the mechanisms of transpassive dissolution and the oxygen evolution reaction in artificial seawater. The study utilized various techniques such as scanning electrochemical microscopy (SECM) to instantaneously detect evolving metal species and oxygen, and inductively coupled plasma mass spectrocmetry (ICP-MS) to quantify the dissolved metal species. For these investigations, the alloys were subjected to precisely controlled corrosion loads employing potentiodynamic, potentiostatic, and chronoamperometric methods during the SECM experiments and subsequent ICP-MS analysis. Macroscopic corrosion and passive film properties were studied via potentiodynamic polarization, electrochemical impedance spectroscopy (EIS), and X-Ray Photoelectron Spectroscopy (XPS). Finally, in-situ atomic force microscopy (AFM) and scanning Kelvin probe force microscopy (SKPFM) were used to analyze the corrosion morphology and surface potentials before, during, and after passivity breakdown. Overall, this study aimed to provide a comprehensive understanding of the interplay between passivation, anodic dissolution and oxygen evolution of the MEAs in artificial seawater.    

    

* Supported-Ir Catalysts: The Impact of the Supports' Chemical Composition on the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663482
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422097mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663482"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663482"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663482"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663482 (Open access: False)
    
[[https://openalex.org/A5089464452][Lucinda Blanco Redondo]], [[https://openalex.org/A5032887364][Yevheniia Lobko]], [[https://openalex.org/A5006021426][Miquel Gamón Rodríguez]], [[https://openalex.org/A5047472204][Thu Ngan Dinhová]], [[https://openalex.org/A5077307847][Tomáš Hrbek]], [[https://openalex.org/A5073666601][Serhiy Cherevko]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422097mtgabs 
     
In water electrolyzer cells, the anode electrode is one of the most important components, where the oxygen evolution reaction (OER) takes place. In this process, the water molecules split into oxygen ions, protons, and electrons, and the oxygen gas is produced on the anode surface [1]. The most suitable materials that catalyze OER are ruthenium, iridium, and their oxides, but their cost and scarcity require reduction and enhancement of their utilization [2]. One morphological strategy consists of the dispersion of the active nanoparticles in supportive nanoparticles made of less expensive materials to increase their mass activity. In addition, due to the high potential reached during operating conditions for water splitting, supportive materials have to possess a high corrosion resistance. Titanium oxides are good candidates because of their high thermal and chemical stability, low cost, and commercial availability [3]. But their poor electric conductivity (∼10 −6 S cm −1 ) makes the design of an active and stable catalyst a complex task. In this work, Ir nanoparticles have been synthesized on the surface of several Ti-based nanoparticles and a complete analysis of their physicochemical properties have been carried out ( Fig. 1a-b ). In addition, electrochemical behaviour has been tested ex-situ in a half cell by the rotating disk electrode technique and after, the catalysts have been deposited in a polymer membrane for testing in-situ in a single cell proton exchange membrane water electrolyzer. The results show a successful performance of the supported Ir/TiO 2 nanoparticles comparable to the pure Ir black nanoparticles but with an active metal loading five times lower. Differently, even though TiC showed excellent electrical conductivity during the ex-situ characterization, Ir/TiC nanoparticles had a poor activity after just one day of performance in the WE due to the complete oxidation of the TiC into TiO 2 ( Fig. 1c-d ). Finally, Ir/TiB 2 showed a balanced result in terms of activity and stability, showing promising properties as a catalyst for PEM-WE. Sadhasivam T., Ho-Young J. Chapter 3 - Nanostructured bifunctional electrocatalyst support materials for unitized regenerative fuel cells// Nanostructured, Functional, and Flexible Materials for Energy Conversion and Storage Systems- 2020. - 69-103. Antolini E. Iridium as Catalyst and Cocatalyst for Oxygen Evolution /Reduction in Acidic Polymer Electrolyte Membrane Electrolyzers and Fuel Cells // ACS Catal. - 2014.- 4, N 5.- P. 1426-1440. Van Pham C., Bühler M. IrO2 coated TiO2 core-shell microparticles advance performance of low loading proton exchange membrane water electrolyzers// Applied Catalysis B: Environmental-2020.- P 269.- P. 118762. Figure 1. TEM image of Ir/TIO 2 (a), EDX mapping of Ir/TiO 2 (b), linear sweep voltammetry of catalysts (c), the current density at given potential 1.80 V (d). Figure 1    

    

* Self-Terminated Surface Reconstruction of Lanthanum Nickelates Promotes Alkaline Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663278
:TOPICS: Solid Oxide Fuel Cells, Catalytic Nanomaterials, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542536mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663278"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663278"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663278"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663278 (Open access: False)
    
[[https://openalex.org/A5063384458][Yi‐Hsuan Wu]], [[https://openalex.org/A5093893767][Marcel Janák]], [[https://openalex.org/A5005303303][Paula M. Abdala]], [[https://openalex.org/A5079220919][Denis A. Kuznetsov]], [[https://openalex.org/A5024347042][Christoph R. Müller]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542536mtgabs 
     
Oxygen evolution reaction (OER) itself is expected to have a strong impact on the state of the surface of the electrocatalyst, yet the actual structure of the surface under operating conditions is rarely considered while formulating structure-activity correlations in electrocatalysis. In this study, changes in the surface structure of Ruddlesden-Popper-type lanthanum nickelate, La 2 NiO 4+δ , and the perovskite LaNiO 3 are probed and contrasted using a series of complementary surface sensitive techniques, including XPS, HRTEM and O K-edge XAS. We found noticeable surface changes to occur on La 2 NiO 4+δ after exposure its exposure to the alkaline electrolyte that is accompanied by the emergence of a strong Ni n+/n+1 redox feature and the coincides with a 45-fold enhancement of the OER activity (at η = 370 mV) in 0.1 M KOH, as compared to the pristine La 2 NiO 4+δ phase. We observe that the in situ formation of an amorphous nickel (oxy)hydroxide layer on the surface increases the electrochemically-active surface area of La 2 NiO 4+δ and imparts a high stability of the catalyst under OER conditions (the formation of the amorphous layer self-terminates at ca. 3 nm). In addition, the transition from octahedral Ni sites (O h ) to square-planar Ni sites (D 4h ) in the reconstructed surface was observed using O K-edge X-ray absorption spectroscopy. Further, we found no evidence for any surface transformations in the perovskite-based catalyst LaNiO 3 that also did not demonstrate any improvement in its activity over cycling. This work highlights the importance of a detailed surface analysis of the catalysts under operation to build robust structure-activity correlations for the metal oxides under electrochemical reaction conditions. Figure 1    

    

* Li+ Cations Activate NiFeOOH for Oxygen Evolution in Sodium and Potassium Hydroxide  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391617266
:TOPICS: Advances in Chemical Sensor Technologies
:PUBLICATION_DATE: 2024-02-07
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202318692")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391617266"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391617266"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391617266"))][Get cited by]]

OpenAlex: https://openalex.org/W4391617266 (Open access: True)
    
[[https://openalex.org/A5033625892][Onno van der Heijden]], [[https://openalex.org/A5049961714][Jordy J.J. Eggebeen]], [[https://openalex.org/A5087146050][Hanna Trzesniowski]], [[https://openalex.org/A5021743372][Nipon Deka]], [[https://openalex.org/A5020266867][Ronny Golnak]], [[https://openalex.org/A5045077840][Jie Xiao]], [[https://openalex.org/A5093882643][Maartje van Rijn]], [[https://openalex.org/A5003052106][Rik V. Mom]], [[https://openalex.org/A5028485156][Marc T. M. Koper]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202318692  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/anie.202318692][pdf]])
     
The efficiency of green hydrogen production is reduced due to the sluggish oxygen evolution reaction (OER). In addition to the optimal catalyst properties, electrocatalytic activity also depends on the interaction of the electrocatalyst with the electrolyte. Here, we show that the addition of small amounts of Li+ to Fe‐free NaOH or KOH electrolytes activates NiFeOOH for the OER compared to single‐cation electrolytes. Moreover, the activation was maintained when the solution was returned to pure NaOH. Importantly, we show that the origin of activation by Li+ cations is primarily non‐kinetic in nature, as the OER onset for the mixed electrolyte does not change and the Tafel slope at low current density is ~30 mV/dec in both electrolytes. However, the increase of the apparent Tafel slope remains lower at increasing current densities in the presence of Li+. Based on electrochemical quartz crystal microbalance and in situ X‐Ray Absorption Spectroscopy measurements, we show that this reduction of non‐kinetic effects is due to enhanced intercalation of sodium, water and hydroxide in the Li+ activated catalyst. This enhanced electrolyte penetration facilitates the OER, especially at higher current densities and for increased catalyst loading, which is important for industrial electrolyzer systems.    

    

* Nanostructured Fe-Doped Nickel Sulfide on Ni Foam As Electrocatalyst for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391638605
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02542621mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391638605"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391638605"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391638605"))][Get cited by]]

OpenAlex: https://openalex.org/W4391638605 (Open access: False)
    
[[https://openalex.org/A5012911188][Jianguo Zhu]], [[https://openalex.org/A5052888056][Paolo P. Pescarmona]], ECS Meeting Abstracts. MA2023-02(54)] 2023. https://doi.org/10.1149/ma2023-02542621mtgabs 
     
In recent years, with the increasing demand for clean and renewable energy, growing research efforts have been dedicated to the generation of hydrogen through water electrolysis [1,2] . To industrialize hydrogen production, it is important to find low-cost and high-activity electrocatalysts for hydrogen evolution reaction (HER) and, especially, oxygen evolution reaction (OER) [3] . OER is more challenging because it involves a four-electron transfer process, while HER is a two-electron transfer process. In this study, Ni 3 S 2 nanorods were synthesized on Ni foam (NiS/Ni foam, Fig. 1a) by a new one-step solvothermal reaction, with S powder as the sulfur source and Ni foam as the nickel source. Experimental results indicated that the NiS/Ni foam electrocatalyst had an overpotential of 276 mV at 10 mA/cm 2 for OER in 1 M KOH electrolyte. To boost the electrocatalytic activity of Ni 3 S 2 , we developed an effective method of doping with Fe via hydrothermal reaction. The obtained nanostructured Fe-doped Ni 3 S 2 on Ni foam (Fe-NiS/Ni foam, see Fig. 1b) achieved OER at an extremely low overpotential of 218 mV at 10 mA/cm 2 . Remarkably, Fe-NiS/Ni foam exhibited high stability at an industrially-relevant high current density (500 mA/cm 2 for 24h). Currently, we are studying its phase transfer process with in situ XPS. REFERENCES Jiao, S., et al., Energy & Environmental Science, 2021. 14(4): p. 1722-1770. Boppella, R., et al., Coordination Chemistry Reviews, 2021. 427. Du, J., F. Li, and L. Sun, Chem Soc Rev, 2021. 50(4): p. 2663-2695. Figure 1    

    

* Lattice Oxygen Exchange in Transition Metal Oxyhydroxides and Metal Hydroxide Organic Frameworks Elucidated for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663343
:TOPICS: Catalytic Dehydrogenation of Light Alkanes, Catalytic Nanomaterials, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02422146mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663343"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663343"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663343"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663343 (Open access: False)
    
[[https://openalex.org/A5019272572][Mikaela Gorlin]], [[https://openalex.org/A5031010219][Nicole A. Saguì]], [[https://openalex.org/A5024844208][Daniel J. Zheng]], [[https://openalex.org/A5062113791][Kaylee Lynn McCormack]], [[https://openalex.org/A5070557069][Z. Khosravizadeh]], [[https://openalex.org/A5007449670][Junghwa Kim]], [[https://openalex.org/A5008841733][Hongbin Xu]], [[https://openalex.org/A5042383151][Jiayu Peng]], [[https://openalex.org/A5001680940][Per Malmberg]], [[https://openalex.org/A5016487357][Yuriy Román‐Leshkov]], [[https://openalex.org/A5024361437][Mario Valvo]], [[https://openalex.org/A5072645578][Yang Shao‐Horn]], [[https://openalex.org/A5056174579][Tomas Edvinsson]], ECS Meeting Abstracts. MA2023-02(42)] 2023. https://doi.org/10.1149/ma2023-02422146mtgabs 
     
To achieve the goal of climate neutrality by 2050, it is essential to increase the use of renewable fuels and carbon-neutral energy. 1 The anodic oxygen evolution reaction (OER) is a key reaction not only in electrocatalytic production of many renewable fuels, 2 but also for next generation of charge storage devices such as metal-air batteries. 3 However, the slow kinetics of the OER process result in high energy losses and costs. 4 Therefore, the development of more efficient electrocatalysts is critical for making renewable energy via electrocatalysis a viable option in emerging energy systems. Transition metal (TM) oxides are a promising alternative to expensive noble metals due to their high catalytic OER activity under alkaline conditions and wider earth-abundance. Despite extensive research, establishing structure-activity correlations and understanding mechanistic processes is challenging, given the intricate interplay between external and intrinsic parameters. In this study, we investigate the role of lattice oxygens in electrodeposited Ni-Fe, Co-Fe, and Mn-Fe oxyhydroxide (M(OH) x O y , M = TM) electrocatalysts using surface-enhanced Raman spectroscopy (SERS) in conjunction with secondary ion mass spectroscopy (SIMS). By taking advantage of the Raman shift that results from 16 O/ 18 O isotope exchange, 5–7 we can track the participation of lattice oxygens in the electrocatalytic cycle. Our investigation reveals that, during OER, all the electrocatalysts display minimal exchange of lattice oxygens with the electrolyte (less than 5%). However, many of these electrocatalysts show partial or complete exchange when exposed to non-catalytic potential when in their more reduced states (see Figure 1). Apart from fully inorganic catalysts, we also present results from Ni-derived metal-hydroxide-organic frameworks (MHOFs), which are analogous to M(OH) x O y catalysts but with organic linkers separating the layers. 8 Our findings indicate that MHOFs with linkers that have a high π-π stacking energy (and a high structural stability) 8 undergo near complete 16 O/ 18 O exchange during OER, while MHOFs employing linkers with a low π-π stacking energy (and thus a low stability) show minor or no lattice exchange during OER. Our study suggests that participation oflattice oxygens is closely linked to the oxidation state of the transition metals rather than to the catalytic process. The work provides a detailed picture of the exchange mechanism and elucidates alternative processes involved in lattice oxygen participation and discusses their relation to the mechanisms of the OER process. References IEA (2023), Energy Technology Perspectives 2023, IEA, Paris https://www.iea.org/reports/energy-technology-perspectives-2023, License: CC BY 4.0 . Wei, S. Z. et al. Combining theory and experiment in electrocatalysis: Insights into materials design. Science (80-. ). 355 , eaad4998 (2017). Li, Y. & Lu, J. Metal–Air Batteries: Will They Be the Future Electrochemical Energy Storage Device of Choice? ACS Energy Lett. 2 , 1370–1377 (2017). Song, F. et al. Transition Metal Oxides as Electrocatalysts for the Oxygen Evolution Reaction in Alkaline Solutions: An Application-Inspired Renaissance. J. Am. Chem. Soc. 140 , 7748–7759 (2018). Lee, S., Banjac, K., Lingenfelder, M. & Hu, X. Oxygen Isotope Labeling Experiments Reveal Different Reaction Sites for the Oxygen Evolution Reaction on Nickel and Nickel Iron Oxides. Angew. Chemie Int. Ed. 58 , 10295–10299 (2019). Moysiadou, A., Lee, S., Hsu, C.-S., Chen, H. M. & Hu, X. Mechanism of Oxygen Evolution Catalyzed by Cobalt Oxyhydroxide: Cobalt Superoxide Species as a Key Intermediate and Dioxygen Release as a Rate-Determining Step. J. Am. Chem. Soc. 142 , 11901–11914 (2020). Diaz-Morales, O., Ferrus-Suspedra, D. & Koper, M. T. M. The importance of nickel oxyhydroxide deprotonation on its activity towards electrochemical water oxidation. Chem. Sci. 7 , 2639–2645 (2016). Yuan, S. et al. Tunable metal hydroxide–organic frameworks for catalysing oxygen evolution. Nat. Mater. 21 , 673–680 (2022). Figure 1    

    

* Hollow TiO2 Supports for Enhanced Acidic Oxygen Evolution Activity  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391663439
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02582810mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391663439"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391663439"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391663439"))][Get cited by]]

OpenAlex: https://openalex.org/W4391663439 (Open access: False)
    
[[https://openalex.org/A5027844987][Laurie A. King]], [[https://openalex.org/A5093893784][Debora Belami]], [[https://openalex.org/A5068678989][Umesh Sai Jonnalagadda]], [[https://openalex.org/A5024639628][Wenhao Fan]], [[https://openalex.org/A5091646124][James J. Kwan]], [[https://openalex.org/A5087146859][Yagya N. Regmi]], ECS Meeting Abstracts. MA2023-02(58)] 2023. https://doi.org/10.1149/ma2023-02582810mtgabs 
     
The usage of scarce and expensive iridium as a catalyst for the acidic oxygen evolution reaction (OER) represents a significant barrier to up-scaling the deployment of proton exchange membrane water electrolysers (PEM-WEs). Accordingly, strategies such as nanostructuring catalysts to increase the electrochemical surface area (e.g. nanoparticles, single-atom catalysts, nanoclusters) as well as investigating mixed metal alloys and oxides (e.g. perovskites, pyrochlores) have been developed with promising half-cell performances. One further approach that has recently gained attention is the deployment of catalyst-supports whereby a high surface area support is used to scaffold the dispersed iridium catalyst. 1 Analogous to the selection of a catalyst, the catalyst support must withstand the highly corrosive and oxidising conditions of a PEM-WE anode. Thus, metal oxides such as titanium dioxide are commonly deployed as catalyst-supports for acidic OER. The catalyst-support moiety must also be sufficiently conductive when integrated into the PEM-WE catalyst layers. Otherwise, the cell voltages required to generate sufficient activity will render the device impractical. Accordingly, strategies such as doping, or the addition of conductive layers between the catalyst and support have been investigated. 2 In this study we investigate a unique support morphology that affords promising OER activity and stability in acidic electrolyte with high iridium mass activities. Specifically, we deploy a hollow TiO 2 catalyst support, 3 coated with a Au/Pd interlayer to provide electrical conductivity. The OER activity and stability is initially screened in a rotating disk electrode (RDE) configuration as a function of thermal treatments (reducing vs oxidising) as well as with at various Au/Pd (1 – 5 wt%) and Ir loadings (35 – 50 wt%). Our highest performing catalyst have a mass activity of around 480 A/g Ir at 1.60 V vs RHE. The catalysts are subsequently investigated in a membrane electrode assembly (MEA) and subject to 10k accelerated stress test stability measurements. To understand the role of the support morphology, Au/Pd interlayer and iridium loadings on electrochemical performance, we also characterise the synthesised catalysts by (scanning) transmission electron microscopy (STEM/TEM), X-ray diffraction (XRD), X-ray photoelectron microscopy (XPS) and electrical conductivity measurements. Collectively, we report the critical role of the Au/Pd interlayer to enable such high electrochemical performance. We also show that the hollow structure of the TiO 2 support may be enhancing mass transport in the catalyst layers. References 1 A. S. Pushkarev, I. V Pushkareva and D. G. Bessarabov, Energy & Fuels , 2022, 36 , 6631–6625. 2 Y. N. Regmi, E. Tzanetopoulos, G. Zeng, X. Peng, D. I. Kushner, T. A. Kistler, L. A. King and N. Danilovic, ACS Catal. , 2020, 10 , 13125–13135. 3 U. S. Jonnalagadda, X. Su and J. J. Kwan, Ultrason. Sonochem. , 2021, 73 , 105530.    

    

* The Active Interface of Iron-Decorated Cobalt (Oxy)Hydroxide for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391637763
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02653141mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391637763"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391637763"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391637763"))][Get cited by]]

OpenAlex: https://openalex.org/W4391637763 (Open access: False)
    
[[https://openalex.org/A5045546838][Qiyang Jiang]], [[https://openalex.org/A5081133273][Fang Song]], ECS Meeting Abstracts. MA2023-02(65)] 2023. https://doi.org/10.1149/ma2023-02653141mtgabs 
     
Iron can significantly enhance the activity of Co (oxy)hydroxide. However, the nature of active sites is currently under debate for Fe-Co (oxy)hydroxide. Here, we use well-define crystalline cobalt hydroxide nanosheets and nanorods as model catalysts to investigate the role of Fe on different crystal planes. The electrochemical reactivity and morphology-dependent analysis suggest that the lateral facets of Co(OH) 2 are active sites and the enhancement effect of iron incorporation only occurs on lateral facets rather than basal facets. Furthermore, by introducing tetramethylammonium cation (TMA+) as a chemical probe in KOH solution, we demonstrate the Fe species can interact strongly with the “active species” on the lateral facets and promote the improvement of OER activity. This work identifies the active site of cobalt hydroxides in the presence and absence of iron and elucidates the interaction of Fe species with “active oxygen” species on the lateral facets of cobalt hydroxide, which has a fundamental implication on the design of efficient OER catalysts.    

    

* Digital Composition Control of Cobalt Nickel Oxides by ALD for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391662767
:TOPICS: Solid Oxide Fuel Cells, Catalytic Nanomaterials, Atomic Layer Deposition Technology
:PUBLICATION_DATE: 2023-12-22
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1149/ma2023-02291504mtgabs")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391662767"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391662767"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391662767"))][Get cited by]]

OpenAlex: https://openalex.org/W4391662767 (Open access: False)
    
[[https://openalex.org/A5068731097][Renee T. M. van Limpt]], [[https://openalex.org/A5040363865][Marek Lavorenti]], [[https://openalex.org/A5047229199][Mengmeng Lao]], [[https://openalex.org/A5048719407][Marcel A. Verheijen]], [[https://openalex.org/A5052330817][Mihalis N. Tsampas]], [[https://openalex.org/A5082522882][M. Creatore]], ECS Meeting Abstracts. MA2023-02(29)] 2023. https://doi.org/10.1149/ma2023-02291504mtgabs 
     
Anion exchange membrane water electrolysis is a potentially low-cost and sustainable technology for renewable-energy driven hydrogen production. Realisation of its full potential relies on the development of cost-effective, earth-abundant OER electrocatalysts alternatives to the state-of-the art noble metal oxides 1 . Ternary transition metal oxides, such as cobalt nickel oxides, are promising candidates due to their excellent alkali resistance in combination with remarkable catalytic activities. The latter relate to their tuneable oxidation states and variation in coordination of their metal centres. These correlations can be properly investigated when precise control over the layer chemical composition is attained. Atomic layer deposition (ALD) is widely acknowledged to deliver control over film uniformity, thickness and conformality, as well as film chemical composition due to the self-limiting nature of its surface reactions. In this study, an ALD supercycle process based on cobalt cyclopentadienyl (CoCp 2 ) and nickel methylcyclopentadienyl (Ni( Me Cp) 2 ) precursors and an oxygen plasma co-reactant has been developed 2 to investigate the influence of chemical composition and crystallographic properties of cobalt nickel oxide thin films on their electrocatalytic OER performance. Deposition of ~20 nm binary nickel oxide and cobalt oxide results in the growth of polycrystalline films of the rock-salt and spinel phase, respectively. Ternary cobalt nickel oxide films with various ratios can be deposited uniformly, as indicated by energy dispersive x-ray spectroscopy mapping. The mixed oxides display a transition from the +2 oxidation state-based pure rock-salt phase (<25 at.% Co) to the spinel phase consisting of mixed +2/+3 oxidation states (>75% at.% Co) upon increasing Co at.% as verified by electron diffraction (figure a) and x-ray photoelectron spectroscopy (XPS). XPS furthermore reveals a linear increase in the Ni 3+ -to-Ni 2+ ratio with increasing Co at.%, which indicates that an inverse spinel structure is formed. The formation of a Ni 3+ -rich inverse spinel cobalt nickel oxide between 55 and 75 at.% Co facilitates the formation of a semi-metallic state (10 2 S/cm) as opposed to the poorly conductive binary oxides (10 -3 S/cm and 10 -2 S/cm for NiO and Co 3 O 4 , respectively). Cyclic voltammetry (CV) measurements in 1M KOH, reveal chemical composition dependent activation behaviour (figure b). Continuous activation behaviour is observed for rock-salt phase films, whilst increment of the Co at.% results in reduced film activation until virtually no activation of the spinel phase films is observed. The activation of the nickel-rich film is accompanied by irreversible redox changes from the +2 to +3 oxidation state as indicated by the integrated non-catalytic wave. Post CV XPS analysis confirms the transition from Co 2+ and Ni 2+ oxidation states to Co 3+ and Ni 3+ . The formation of an (oxy)hydroxide state is observed for the rock-salt dominated films, whilst oxidation states characteristic of a spinel- like oxide structure are observed for the cobalt-rich films. No changes in the transition metal ratios are observed after activation. Scanning electron microscopy images furthermore reveal that the transformation of the Ni-rich films is accompanied by surface restructuring. These results indicate that initial composition can significantly influence the electrocatalytic performance of ternary oxides and therefore highlight the importance of techniques such as atomic layer deposition to study their complex behaviour. 1 Xu et al., Energy Chem., 4 (2022) 100087 2 van Limpt et al., J. Vac. Sci. Technol. A, 41 (2023) 032407 This work has been carried out within the SCALE project (NWA.1237.18.001) funded jointly by the Netherlands Organization for Scientific Research. Authors would like to thank the co-founders of the project ISPT, Syngaschem, VecoPrecision and Vsparticle and international partners Toyota Motor Europe and FORTH institute. Figure: (a) ALD deposited cobalt nickel oxide film show a transition from the +2 oxidation state-based rock-salt phase (NiO) to the spinel structure consisting of mixed +2/+3 oxidation states (Co 3 O 4 ) upon tuning the chemical composition as identified by electron diffraction. (b) This significantly affects the OER-electrocatalytic performance and activation of the films as represented by the current density at 1.8V vs RHE over 500 CV cycles in 1M KOH. Data labels indicate cobalt concentration as at.% Co/(at.% Co+ at.% Ni) . Figure 1    

    

* Stabilizing Highly Active Ru Sites by Electron Reservoir in Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391653962
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-08
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/molecules29040785")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391653962"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391653962"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391653962"))][Get cited by]]

OpenAlex: https://openalex.org/W4391653962 (Open access: True)
    
[[https://openalex.org/A5052169469][Jiayan Wu]], [[https://openalex.org/A5004975664][Zhongjie Qiu]], [[https://openalex.org/A5029153042][Jiaxi Zhang]], [[https://openalex.org/A5075171426][Huiyu Song]], [[https://openalex.org/A5023031181][Zhiming Cui]], [[https://openalex.org/A5062744012][Li Du]], Molecules. 29(4)] 2024. https://doi.org/10.3390/molecules29040785  ([[https://www.mdpi.com/1420-3049/29/4/785/pdf?version=1707380330][pdf]])
     
Proton exchange membrane water electrolysis is hindered by the sluggish kinetics of the anodic oxygen evolution reaction. RuO2 is regarded as a promising alternative to IrO2 for the anode catalyst of proton exchange membrane water electrolyzers due to its superior activity and relatively lower cost compared to IrO2. However, the dissolution of Ru induced by its overoxidation under acidic oxygen evolution reaction (OER) conditions greatly hinders its durability. Herein, we developed a strategy for stabilizing RuO2 in acidic OER by the incorporation of high-valence metals with suitable ionic electronegativity. A molten salt method was employed to synthesize a series of high-valence metal-substituted RuO2 with large specific surface areas. The experimental results revealed that a high content of surface Ru4+ species promoted the OER intrinsic activity of high-valence doped RuO2. It was found that there was a linear relationship between the ratio of surface Ru4+/Ru3+ species and the ionic electronegativity of the dopant metals. By regulating the ratio of surface Ru4+/Ru3+ species, incorporating Re, with the highest ionic electronegativity, endowed Re0.1Ru0.9O2 with exceptional OER activity, exhibiting a low overpotential of 199 mV to reach 10 mA cm−2. More importantly, Re0.1Ru0.9O2 demonstrated outstanding stability at both 10 mA cm−2 (over 300 h) and 100 mA cm−2 (over 25 h). The characterization of post-stability Re0.1Ru0.9O2 revealed that Re promoted electron transfer to Ru, serving as an electron reservoir to mitigate excessive oxidation of Ru sites during the OER process and thus enhancing OER stability. We conclude that Re, with the highest ionic electronegativity, attracted a mass of electrons from Ru in the pre-catalyst and replenished electrons to Ru under the operating potential. This work spotlights an effective strategy for stabilizing cost-effective Ru-based catalysts for acidic OER.    

    
