#+TITLE: water splitting
Description: water splitting papers
Created on Sat Mar  2 00:42:27 2024

Found 27 results from 2024-02-24 to 2024-03-02
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Dipole Effect on Oxygen Evolution Reaction of 2D Janus Single-Atom Catalysts: A Case of Rh Anchored on the P6m2-NP Configurations  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392093761
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.jpclett.3c03148")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392093761"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392093761"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392093761"))][Get cited by]]

OpenAlex: https://openalex.org/W4392093761 (Open access: False)
    
[[https://openalex.org/A5031645533][Tao Huang]], [[https://openalex.org/A5005455089][Yaping Zhong]], [[https://openalex.org/A5075889094][Lei Li]], [[https://openalex.org/A5042904729][Wan Hui]], [[https://openalex.org/A5059314269][Can Leng]], [[https://openalex.org/A5039189577][Gui‐Fang Huang]], [[https://openalex.org/A5064262109][Wangyu Hu]], [[https://openalex.org/A5067640198][Wei‐Qing Huang]], The Journal of Physical Chemistry Letters. None(None)] 2024. https://doi.org/10.1021/acs.jpclett.3c03148 
     
Catalytic performance of single-atom catalysts (SACs) relies fundamentally on the electronic nature and local coordination environment of the active site. Here, based on a machine-learning (ML)-aided density functional theory (DFT) method, we reveal that the intrinsic dipole in Janus materials has a significant impact on the catalytic activity of SACs, using 2D γ-phosphorus carbide (γ-PC) as a model system. Specifically, a local dipole around the active site is a key degree to tune the catalytic activity and can be used as an important descriptor with a high feature importance of 17.1% in predicting the difference of adsorption free energy (ΔGO* – ΔGOH*) to assess the activity of the oxygen evolution reaction. As a result, the catalytic performance of SACs can be tuned by an intrinsic dipole, in stark contrast to those external stimuli strategies previously used. These results suggest that dipole engineering and the revolutionary DFT-ML hybrid scheme are novel approaches for designing high-performance catalysts.    

    

* Tuning Mo cations dissolution and surface reconstruction of CoMoO4 for efficient oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392095514
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jallcom.2024.173963")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392095514"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392095514"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392095514"))][Get cited by]]

OpenAlex: https://openalex.org/W4392095514 (Open access: False)
    
[[https://openalex.org/A5030288532][Hong Yin]], [[https://openalex.org/A5075330438][Yaonan Mo]], [[https://openalex.org/A5005792080][Chuang Liu]], [[https://openalex.org/A5008858273][Hengbo Xiao]], [[https://openalex.org/A5005752974][Zhilong Zheng]], [[https://openalex.org/A5088697406][Songliu Yuan]], [[https://openalex.org/A5025306333][Junjie Guo]], Journal of Alloys and Compounds. None(None)] 2024. https://doi.org/10.1016/j.jallcom.2024.173963 
     
No abstract    

    

* Ultrafast electronic and vibrational spectroscopy of electrochemical transformations on a metal-oxide surface during oxygen evolution from water  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392103902
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Quantum Coherence in Photosynthesis and Aqueous Systems
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-rzgp3")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392103902"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392103902"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392103902"))][Get cited by]]

OpenAlex: https://openalex.org/W4392103902 (Open access: True)
    
[[https://openalex.org/A5066895569][Tanja Cuk]], [[https://openalex.org/A5054037567][Xihan Chen]], [[https://openalex.org/A5082056990][Suryansh Singh]], [[https://openalex.org/A5012639606][Michael Paolino]], [[https://openalex.org/A5060242817][James J. P. Stewart]], [[https://openalex.org/A5028760607][Ilya Vinogradov]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-rzgp3  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65d779d166c138172943186c/original/ultrafast-electronic-and-vibrational-spectroscopy-of-electrochemical-transformations-on-a-metal-oxide-surface-during-oxygen-evolution-from-water.pdf][pdf]])
     
The oxygen evolution reaction (OER) from water fuels the planet through photosynthesis and is a primary means for hydrogen storage in energy technologies. Yet the detection of intermediates of OER central to the catalytic mechanism has been an ongoing challenge. This review covers the relevance of ultrafast electronic and vibrational spectroscopy of the electrochemical transformations of a metal-oxide surface undergoing OER. The electron doped SrTiO3/electrolyte is the system under review because of its high photocurrent efficiency with an ultrafast light trigger and because it allowed for detection of intermediate forms across the electromagnetic spectrum. The first part covers how the efficient catalytic reaction is triggered by ultrafast light pulses, describing the Schottky diode, the depletion layer, and Helmholtz layer under operating conditions to the extent possible. The second part covers the detection of the surface bound intermediates by transient spectroscopy. These target ultrafast (ps-ns) electron transfer from (or hole-trapping to) bound surface water species that are associated with the reactive oxygen intermediates of OER (e.g. OH*, O*). Their detection via a broadband visible probe, a mid-infrared evanescent wave, and coherent acoustic waves is then described. These target, respectively, the electronic states, the vibrational levels, and the lattice strain associated with the intermediates. The review is primarily concerned with how the measurements are made and the intermediates’ experimental spectra. The theoretical descriptions are brought in as a needed to provide context to spectra that are difficult to interpret on their own. A concluding section summarizes the essential findings and methodologies.    

    

* Nickel and Commercially Available Nickel‐Containing Alloys as Electrodes for the Electrochemical Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392105251
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202300460")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392105251"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392105251"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392105251"))][Get cited by]]

OpenAlex: https://openalex.org/W4392105251 (Open access: True)
    
[[https://openalex.org/A5016719471][Nikolas Mao Kubo]], [[https://openalex.org/A5093264058][Fabian Ketter]], [[https://openalex.org/A5065818528][Stefan Palkovits]], [[https://openalex.org/A5078364217][Regina Palkovits]], ChemElectroChem. None(None)] 2024. https://doi.org/10.1002/celc.202300460  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/celc.202300460][pdf]])
     
Abstract Water electrolysis is a crucial technology for independency on fossil fuels. However, water splitting is limited by the sluggish kinetics of oxygen evolution reaction (OER). While many studies report highly active, non‐precious metal‐based electrocatalysts for alkaline OER, applicability under industrial conditions is often omitted. Such conditions require catalysts being applied on nickel or nickel‐containing alloys in elevated electrolyte concentrations. In contrast to the rather inert substrates often used in scientific studies, such industrially applied substrates exhibit significant OER activity themselves and show dynamic behaviour. Therefore, it is crucial to understand the OER behaviour of such substrates. Here, nickel and seven commercially available nickel‐containing alloys are investigated as anodes in alkaline OER and their elemental compositions correlated to their corresponding activities. Repeated potential cycling across the Ni(II)/Ni(III)‐redox couple is established as activity‐enhancing procedure. Overall, the nickel‐base alloy Hastelloy® X exhibits the highest activity due to its Fe‐, Cr‐, Mo‐ and Co‐content. Though, the activity gain differs significantly for the various materials. Comparing Ni and Hastelloy® X as least and most active materials, the positive impact of activation on both activity and stability becomes evident. While untreated Ni suffers from poor OER stability, the activity‐enhancing procedure also significantly increases electrode stability in 24 h chronopotentiometry.    

    

* Tuning the d-band states of NiFe-MOFs by combining early and late transition metals for enhanced electrocatalytic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392105540
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ce01265d")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392105540"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392105540"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392105540"))][Get cited by]]

OpenAlex: https://openalex.org/W4392105540 (Open access: False)
    
[[https://openalex.org/A5066425442][Dan Wen]], [[https://openalex.org/A5045484625][Xie Dan]], [[https://openalex.org/A5039787287][Bo Huang]], [[https://openalex.org/A5010357231][Qiuping Huang]], [[https://openalex.org/A5041582832][Dunmin Lin]], [[https://openalex.org/A5031892138][Xu Cheng]], [[https://openalex.org/A5020475870][Fengyu Xie]], [[https://openalex.org/A5068049785][Guangzhao Wang]], [[https://openalex.org/A5084740267][Weihua Guo]], CrystEngComm. None(None)] 2024. https://doi.org/10.1039/d3ce01265d 
     
This work presents a strategy of early-and-late transition metal combination to provide new pathways for efficient water splitting catalyst development.    

    

* Polarized Ultrathin BN Induced Dynamic Electron Interactions for Enhancing Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392109777
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202402018")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392109777"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392109777"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392109777"))][Get cited by]]

OpenAlex: https://openalex.org/W4392109777 (Open access: False)
    
[[https://openalex.org/A5036780151][Yixin Hao]], [[https://openalex.org/A5060265950][Sung‐Fu Hung]], [[https://openalex.org/A5078634223][Cheng Tian]], [[https://openalex.org/A5049099959][Luqi Wang]], [[https://openalex.org/A5091632977][Yiyu Chen]], [[https://openalex.org/A5002546727][Sheng Zhao]], [[https://openalex.org/A5081952140][Kang-Lin Peng]], [[https://openalex.org/A5056489746][Chenchen Zhang]], [[https://openalex.org/A5047629524][Ying Zhang]], [[https://openalex.org/A5010783003][Chun‐Han Kuo]], [[https://openalex.org/A5084555578][Han‐Yi Chen]], [[https://openalex.org/A5011395130][Shengjie Peng]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202402018 
     
Developing ruthenium‐based heterogeneous catalysts with an efficient and stable interface is essential for enhanced acidic oxygen evolution reaction (OER). Herein, we report a defect‐rich ultrathin boron nitride nanosheet support with relatively independent electron donor and acceptor sites, which serves as an electron reservoir and receiving station for RuO2, realizing the rapid supply and reception of electrons. Through precisely controlling the reaction interface, a low OER overpotential of only 180 mV (at 10 mA cm−2) and long‐term operational stability (350 h) are achieved, suggesting potential practical applications. In‐situ characterization and theoretical calculations have validated the existence of a localized electronic recycling between RuO2 and BNNS. The electron‐rich Ru sites accelerate the adsorption of water molecules and the dissociation of intermediates, while the interconnection between the O‐terminal and B‐terminal edge establishes electronic back‐donation, effectively suppressing the over‐oxidation of lattice oxygen. This study provides a new perspective for constructing a stable and highly active catalytic interface.    

    

* Polarized Ultrathin BN Induced Dynamic Electron Interactions for Enhancing Acidic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392110312
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202402018")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392110312"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392110312"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392110312"))][Get cited by]]

OpenAlex: https://openalex.org/W4392110312 (Open access: False)
    
[[https://openalex.org/A5036780151][Yixin Hao]], [[https://openalex.org/A5060265950][Sung‐Fu Hung]], [[https://openalex.org/A5078634223][Cheng Tian]], [[https://openalex.org/A5049099959][Luqi Wang]], [[https://openalex.org/A5091632977][Yiyu Chen]], [[https://openalex.org/A5002546727][Sheng Zhao]], [[https://openalex.org/A5081952140][Kang-Lin Peng]], [[https://openalex.org/A5056489746][Chenchen Zhang]], [[https://openalex.org/A5042973046][Ying Zhang]], [[https://openalex.org/A5010783003][Chun‐Han Kuo]], [[https://openalex.org/A5084555578][Han‐Yi Chen]], [[https://openalex.org/A5011395130][Shengjie Peng]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202402018 
     
Developing ruthenium‐based heterogeneous catalysts with an efficient and stable interface is essential for enhanced acidic oxygen evolution reaction (OER). Herein, we report a defect‐rich ultrathin boron nitride nanosheet support with relatively independent electron donor and acceptor sites, which serves as an electron reservoir and receiving station for RuO2, realizing the rapid supply and reception of electrons. Through precisely controlling the reaction interface, a low OER overpotential of only 180 mV (at 10 mA cm−2) and long‐term operational stability (350 h) are achieved, suggesting potential practical applications. In‐situ characterization and theoretical calculations have validated the existence of a localized electronic recycling between RuO2 and BNNS. The electron‐rich Ru sites accelerate the adsorption of water molecules and the dissociation of intermediates, while the interconnection between the O‐terminal and B‐terminal edge establishes electronic back‐donation, effectively suppressing the over‐oxidation of lattice oxygen. This study provides a new perspective for constructing a stable and highly active catalytic interface.    

    

* Nanoflowers of Ternary Cobalt–Copper–Manganese Oxide as an Efficient Electrocatalyst for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392130324
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-24
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ente.202301355")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392130324"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392130324"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392130324"))][Get cited by]]

OpenAlex: https://openalex.org/W4392130324 (Open access: False)
    
[[https://openalex.org/A5003445703][Jyoti Raghav]], [[https://openalex.org/A5045408244][P. Rosaiah]], [[https://openalex.org/A5051674509][Bandar Ali Al‐Asbahi]], [[https://openalex.org/A5001688048][Soumyendu Roy]], Energy Technology. None(None)] 2024. https://doi.org/10.1002/ente.202301355 
     
Oxygen evolution reaction (OER) is an integral step in the water‐splitting process. Hence, to promote OER, efficient catalysts are required to lower the energy barriers at the electrode/electrolyte interface. Low‐cost and highly active catalysts are in great demand. Herein, a ternary metal oxide, CoCuMnO x , synthesized by a facile hydrothermal method is reported, which possesses excellent catalytic ability for OER in alkaline electrolytes. The nanoscale morphology of the catalyst with flower‐like nanostructures is instrumental in increasing the electrochemical surface area of the electrode. The presence of multivalent ions and the incorporation of copper greatly enhance the electrochemical properties of the catalysts. The catalysts typically demonstrate an overpotential value of 220 mV for achieving 10 mA cm −2 current density and a Tafel slope of 73 mV dec −1 . The catalysts demonstrate good stability with minimal degradation in OER activity even after 20 h of chronopotentiometry test. For practical applications, this low‐cost material holds great potential.    

    

* Tracking accelerated oxygen evolution reaction enabled by explosive reconstruction of active species based on CoxN@NC  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392135567
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4ta00196f")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392135567"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392135567"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392135567"))][Get cited by]]

OpenAlex: https://openalex.org/W4392135567 (Open access: False)
    
[[https://openalex.org/A5042054457][Hyung Wook Choi]], [[https://openalex.org/A5091554389][Jiwon Kim]], [[https://openalex.org/A5015012876][Hyeon‐Seok Bang]], [[https://openalex.org/A5078354747][Khaled Badawy]], [[https://openalex.org/A5024947859][Ui Young Lee]], [[https://openalex.org/A5049204244][Dong In Jeong]], [[https://openalex.org/A5039821968][Yeseul Kim]], [[https://openalex.org/A5054520248][Kotiba Hamad]], [[https://openalex.org/A5078886160][Bong Kyun Kang]], [[https://openalex.org/A5079700977][Byung Mook Weon]], [[https://openalex.org/A5001603223][Hyung Suk Oh]], [[https://openalex.org/A5017583868][Nirpendra Singh]], [[https://openalex.org/A5045038094][Dae Ho Yoon]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d4ta00196f 
     
The development of a hierarchical structure of Co/Co 4 N@NC has been successfully achieved. The robust oxygen evolution reaction activity of Co/Co 4 N@NC is attributed to the modulation of the d-band center, which reconstruct Co 2+ into Co 3+ .    

    

* Interface‐Engineered NiFe/Ni‐S Nanoparticles for Reliable Alkaline Oxygen Production at Industrial Current: A Sulfur Source Confinement Strategy  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392139199
:TOPICS: Aqueous Zinc-Ion Battery Technology, Electrocatalysis for Energy Conversion, Layered Double Hydroxide Nanomaterials
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202310737")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392139199"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392139199"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392139199"))][Get cited by]]

OpenAlex: https://openalex.org/W4392139199 (Open access: False)
    
[[https://openalex.org/A5010217323][Bin Chen]], [[https://openalex.org/A5017882728][Tao Liu]], [[https://openalex.org/A5027689004][Xiangwen Zhang]], [[https://openalex.org/A5048537490][Shichao Zhao]], [[https://openalex.org/A5061055076][Runfei Yue]], [[https://openalex.org/A5040298454][Sipu Wang]], [[https://openalex.org/A5038532525][Lianqin Wang]], [[https://openalex.org/A5015399496][Zhihao Chen]], [[https://openalex.org/A5019670440][Yingjie Feng]], [[https://openalex.org/A5052713328][Jun Huang]], [[https://openalex.org/A5079178497][Yan Yin]], [[https://openalex.org/A5021480695][Michael D. Guiver]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202310737 
     
Abstract Using powder‐based ink appears to be the most suitable candidate for commercializing the membrane electrode assembly (MEA), while research on the powder‐based NPM catalyst for anion exchange membrane water electrolyzer (AEMWE) is currently insufficient, especially at high current density. Herein, a sulfur source (NiFe Layered double hydroxide adsorbed ) confinement strategy is developed to integrate Ni 3 S 2 onto the surface of amorphous/crystalline NiFe alloy nanoparticles (denoted NiFe/Ni‐S), achieving advanced control over the sulfidation process for the formation of metal sulfides. The constructed interface under the sulfur source confinement strategy generates abundant active sites that increase electron transport at the electrode‐electrolyte interface and improve ability over an extended period at a high current density. Consequently, the constructed NiFe/Ni‐S delivers an ultra‐low overpotential of 239 mV at 10 mA cm −2 and 0.66 mA under an overpotential of 300 mV. The AEMWE with NiFe/Ni‐S anode exhibits a cell voltage of 1.664 V @ 0.5 A cm −2 and a 400 h stability at 1.0 A cm −2 .    

    

* Phytic-acid-doped conductive hydrogels as alkaline seawater electrocatalysts with anomalous chloride promoted oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392139371
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159754")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392139371"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392139371"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392139371"))][Get cited by]]

OpenAlex: https://openalex.org/W4392139371 (Open access: False)
    
[[https://openalex.org/A5027580867][Lin Hu]], [[https://openalex.org/A5058103707][Xuecai Tan]], [[https://openalex.org/A5078231129][Rui Luo]], [[https://openalex.org/A5043057827][Xiao-Ju Wen]], [[https://openalex.org/A5051350429][Xiankun Wu]], [[https://openalex.org/A5041854485][Hua-xun Luo]], [[https://openalex.org/A5072559438][Zhenghao Fei]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159754 
     
No abstract    

    

* Seven mechanisms of oxygen evolution reaction proposed recently: A mini review  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392142198
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149992")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392142198"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392142198"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392142198"))][Get cited by]]

OpenAlex: https://openalex.org/W4392142198 (Open access: False)
    
[[https://openalex.org/A5022885630][Zhixuan Feng]], [[https://openalex.org/A5037480797][Chia-Tsen Dai]], [[https://openalex.org/A5032553249][Peng Shi]], [[https://openalex.org/A5060430863][Xuefei Lei]], [[https://openalex.org/A5021363847][Rui Guo]], [[https://openalex.org/A5075523709][Biao Wang]], [[https://openalex.org/A5081185893][Xuanwen Liu]], [[https://openalex.org/A5019520436][Jinyuan You]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149992 
     
No abstract    

    

* P-doped RuPd nanoparticles anchored on Y2Ru2-xPdxO7 pyrochlore oxide surface as oxygen evolution and reduction electrocatalysts for Zn-air battery  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392142396
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apsusc.2024.159788")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392142396"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392142396"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392142396"))][Get cited by]]

OpenAlex: https://openalex.org/W4392142396 (Open access: False)
    
[[https://openalex.org/A5052090122][Geunhyeong Lee]], [[https://openalex.org/A5017828132][Eun-Su Jang]], [[https://openalex.org/A5050138704][Pei-Chen Su]], [[https://openalex.org/A5009818257][Jooheon Kim]], Applied Surface Science. None(None)] 2024. https://doi.org/10.1016/j.apsusc.2024.159788 
     
No abstract    

    

* Distance effect of single atoms on stability of cobalt oxide catalysts for acidic oxygen evolution  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392153698
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1038/s41467-024-46176-0")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392153698"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392153698"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392153698"))][Get cited by]]

OpenAlex: https://openalex.org/W4392153698 (Open access: True)
    
[[https://openalex.org/A5000151255][Z. D. Zhang]], [[https://openalex.org/A5046463704][Chuanyi Jia]], [[https://openalex.org/A5063955135][Peiyu Ma]], [[https://openalex.org/A5021979312][Feng Chen]], [[https://openalex.org/A5071791749][Yang Jin]], [[https://openalex.org/A5041677976][Jian Huang]], [[https://openalex.org/A5049713859][Jian‐Guo Zheng]], [[https://openalex.org/A5043676611][Ming J. Zuo]], [[https://openalex.org/A5045653991][Mingkai Liu]], [[https://openalex.org/A5039567536][Shiming Zhou]], [[https://openalex.org/A5075571728][Jie Zeng]], Nature Communications. 15(1)] 2024. https://doi.org/10.1038/s41467-024-46176-0  ([[https://www.nature.com/articles/s41467-024-46176-0.pdf][pdf]])
     
Abstract Developing efficient and economical electrocatalysts for acidic oxygen evolution reaction (OER) is essential for proton exchange membrane water electrolyzers (PEMWE). Cobalt oxides are considered promising non-precious OER catalysts due to their high activities. However, the severe dissolution of Co atoms in acid media leads to the collapse of crystal structure, which impedes their application in PEMWE. Here, we report that introducing acid-resistant Ir single atoms into the lattice of spinel cobalt oxides can significantly suppress the Co dissolution and keep them highly stable during the acidic OER process. Combining theoretical and experimental studies, we reveal that the stabilizing effect induced by Ir heteroatoms exhibits a strong dependence on the distance of adjacent Ir single atoms, where the OER stability of cobalt oxides continuously improves with decreasing the distance. When the distance reduces to about 0.6 nm, the spinel cobalt oxides present no obvious degradation over a 60-h stability test for acidic OER, suggesting potential for practical applications.    

    

* Exfoliation of Metal–Organic Frameworks to Give 2D MOF Nanosheets for the Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392156438
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202402969")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392156438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392156438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392156438"))][Get cited by]]

OpenAlex: https://openalex.org/W4392156438 (Open access: False)
    
[[https://openalex.org/A5049967323][Peng Wu]], [[https://openalex.org/A5039931061][Shuang Geng]], [[https://openalex.org/A5021984184][Xinyu Wang]], [[https://openalex.org/A5039734738][Xinglong Zhang]], [[https://openalex.org/A5007884941][Hongfeng Li]], [[https://openalex.org/A5070961992][Lulu Zhang]], [[https://openalex.org/A5037726491][Yu Shen]], [[https://openalex.org/A5057374450][Baoli Zha]], [[https://openalex.org/A5086476705][Suoying Zhang]], [[https://openalex.org/A5040039962][Fengwei Huo]], [[https://openalex.org/A5023634611][Weina Zhang]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202402969 
     
The structure and properties of materials are determined by a diverse range of chemical bond formation and breaking mechanisms, which greatly motivates the development of selectively controlling the chemical bonds in order to achieve materials with specific characteristics. Here, an orientational intervening bond‐breaking strategy is demonstrated for synthesizing ultrathin metal–organic framework (MOF) nanosheets through balancing the process of thermal decomposition and liquid nitrogen exfoliation. In such approach, proper thermal treatment can weaken the interlayer bond while maintaining the stability of the intralayer bond in the layered MOFs. And the following liquid nitrogen treatment results in significant deformation and stress in the layered MOFs’ structure due to the instant temperature drop and drastic expansion of liquid N2, leading to the curling, detachment, and separation of the MOF layers. The produced MOF nanosheets with five cycles of treatment are primarily composed of nanosheets that are less than 10 nm in thickness. The MOF nanosheets exhibit enhanced catalytic performance in oxygen evolution reactions owing to the ultrathin thickness without capping agents which provide improved charge transfer efficiency and dense exposed active sites. This strategy underscores the significance of orientational intervention in chemical bonds to engineer innovative materials.    

    

* Exfoliation of Metal–Organic Frameworks to Give 2D MOF Nanosheets for the Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392166415
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Chemistry and Applications of Metal-Organic Frameworks
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202402969")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392166415"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392166415"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392166415"))][Get cited by]]

OpenAlex: https://openalex.org/W4392166415 (Open access: False)
    
[[https://openalex.org/A5049967323][Peng Wu]], [[https://openalex.org/A5039931061][Shuang Geng]], [[https://openalex.org/A5021984184][Xinyu Wang]], [[https://openalex.org/A5039734738][Xinglong Zhang]], [[https://openalex.org/A5007884941][Hongfeng Li]], [[https://openalex.org/A5070961992][Lulu Zhang]], [[https://openalex.org/A5037726491][Yu Shen]], [[https://openalex.org/A5057374450][Baoli Zha]], [[https://openalex.org/A5086476705][Suoying Zhang]], [[https://openalex.org/A5040039962][Fengwei Huo]], [[https://openalex.org/A5086476705][Suoying Zhang]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202402969 
     
The structure and properties of materials are determined by a diverse range of chemical bond formation and breaking mechanisms, which greatly motivates the development of selectively controlling the chemical bonds in order to achieve materials with specific characteristics. Here, an orientational intervening bond‐breaking strategy is demonstrated for synthesizing ultrathin metal–organic framework (MOF) nanosheets through balancing the process of thermal decomposition and liquid nitrogen exfoliation. In such approach, proper thermal treatment can weaken the interlayer bond while maintaining the stability of the intralayer bond in the layered MOFs. And the following liquid nitrogen treatment results in significant deformation and stress in the layered MOFs’ structure due to the instant temperature drop and drastic expansion of liquid N2, leading to the curling, detachment, and separation of the MOF layers. The produced MOF nanosheets with five cycles of treatment are primarily composed of nanosheets that are less than 10 nm in thickness. The MOF nanosheets exhibit enhanced catalytic performance in oxygen evolution reactions owing to the ultrathin thickness without capping agents which provide improved charge transfer efficiency and dense exposed active sites. This strategy underscores the significance of orientational intervention in chemical bonds to engineer innovative materials.    

    

* Structural reconstruction of cobalt and ferrocene-based metal-organic framework during electrochemical oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392168646
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Conducting Polymer Research, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.26434/chemrxiv-2024-vlqz5")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392168646"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392168646"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392168646"))][Get cited by]]

OpenAlex: https://openalex.org/W4392168646 (Open access: True)
    
[[https://openalex.org/A5071440495][Thomas Doughty]], [[https://openalex.org/A5094005131][Andrea Zingl]], [[https://openalex.org/A5070524825][Maximilian Wünschek]], [[https://openalex.org/A5035468865][Christian M. Pichler]], [[https://openalex.org/A5006409298][Matthew Watkins]], [[https://openalex.org/A5019861460][Souvik Roy]], No host. None(None)] 2024. https://doi.org/10.26434/chemrxiv-2024-vlqz5  ([[https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/65d88265e9ebbb4db90983ee/original/structural-reconstruction-of-cobalt-and-ferrocene-based-metal-organic-framework-during-electrochemical-oxygen-evolution-reaction.pdf][pdf]])
     
Metal-organic frameworks (MOFs) are increasingly being investigated as electrocatalysts for oxygen evolution reaction (OER) due to their unique modular structures that present a hybrid between molecular and heterogeneous catalysts, featuring well-defined active sites. However, many fundamental questions remain open regarding the electrochemical stability of MOFs, structural reconstruction of coordination sites, and the role of in situ-formed species. Here we report structural transformation of a surface-grown MOF containing cobalt nodes and 1,1’-ferrocenedicarboxylic acid linkers (denoted as CoFc-MOF) during OER in alkaline electrolyte. Ex situ and in situ investigations of CoFc-MOF film suggests that the MOF acts as a pre-catalyst and undergoes a two-step restructuring process under operating conditions to generate a metal oxyhydroxide phase. The MOF-derived metal oxyhydroxide catalyst, supported on nickel foam electrodes, displays high activity towards OER with an overpotential of 190 mV at the current density of 10 mA cm–2. While this study demonstrates the necessity of investigating structural evolution of MOFs in electrocatalysis, it also shows potential of using MOFs as precursors in catalyst design.    

    

* Electroactive heterojunctions of iron-based compounds in oxygen evolution reaction – insight into synergy and mechanism  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392170706
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.electacta.2024.144005")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392170706"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392170706"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392170706"))][Get cited by]]

OpenAlex: https://openalex.org/W4392170706 (Open access: False)
    
[[https://openalex.org/A5034044475][Anna Dymerska]], [[https://openalex.org/A5064148144][Ewa Mijowska]], [[https://openalex.org/A5030552243][Almaz L. Zinnatullin]], [[https://openalex.org/A5005873235][Rustem Zairov]], [[https://openalex.org/A5064148144][Ewa Mijowska]], Electrochimica Acta. None(None)] 2024. https://doi.org/10.1016/j.electacta.2024.144005 
     
This research addresses the inherent challenges of low catalytic activity and stability often associated with Oxygen Evolution Reaction (OER) catalysts. We designed composites with outstanding electrocatalytic performance. The methodology is characterized by low-temperature operation and environmentally friendly substrates. We have successfully fostered a synergistic interplay between Fe and oxygen, carbon and nickel, respectively. Fabricated material composed of three different heterojunctions triggered the stability of the catalyst and facilitated efficient charge transfer in OER. Our optimized catalyst (Fe/Ni_3.0h), emerges as a promising candidate for practical applications, exhibiting an overpotential of 310 mV, a Tafel slope of 37 mV/dec, and a potential retention of 98.8% which is a 50% lower drop in respect to commercial RuO2. Therefore, our approach underlines the substantial influence of conductive Fe-based materials: FeNi3, Fe3C, and Fe3O4 on OER performance with revealed comprehensive mechanism via ex-situ XRD and Mössbauer spectroscopy analyses.    

    

* Surface addition of Ag on PbO2 to enable efficient oxygen evolution reaction in pH-neutral media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392184832
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.150043")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392184832"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392184832"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392184832"))][Get cited by]]

OpenAlex: https://openalex.org/W4392184832 (Open access: False)
    
[[https://openalex.org/A5041930796][Siming Li]], [[https://openalex.org/A5047811811][Meng Shi]], [[https://openalex.org/A5072254497][Chen Wu]], [[https://openalex.org/A5032967714][Kaiqi Nie]], [[https://openalex.org/A5052267876][Zheng Wang]], [[https://openalex.org/A5050687293][Xiaoxu Jiang]], [[https://openalex.org/A5038908444][Xinbing Liu]], [[https://openalex.org/A5063251071][Huili Chen]], [[https://openalex.org/A5024069386][Xinlong Tian]], [[https://openalex.org/A5053821178][Daoxiong Wu]], [[https://openalex.org/A5041930796][Siming Li]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.150043 
     
Electrocatalysts, particularly earth-abundant metal oxide ones, exhibit poor performance in catalyzing the oxygen evolution reaction (OER) under neutral conditions due to low ionic concentrations. This study introduces a novel strategy for fabricating a PbO2 + Ag composite electrode with significantly improved OER activity and stability in a pH-neutral environment. Our results suggest that incorporating Ag as a surface additive improves the efficiency of utilizing adsorbed oxygenated species via the bridge-site-top-site pathway. Moreover, the surface decoration of Ag resulted in enhanced electrocatalytic stability by diverting the attack of oxygenated species to Pb thereby effectively preventing Pb dissolution. The results not only establish a method for utilizing PbO2 in pH-neutral OER applications, but also propose a potential strategy for employing less noble catalysts in cost-effective electrochemical energy conversions.    

    

* Carbon Nanotube Composites with Bimetallic Transition Metal Selenides as Efficient Electrocatalysts for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392189844
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/su16051953")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392189844"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392189844"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392189844"))][Get cited by]]

OpenAlex: https://openalex.org/W4392189844 (Open access: True)
    
[[https://openalex.org/A5053208255][Saira Riaz]], [[https://openalex.org/A5026183354][Muhammad Shafiq Anjum]], [[https://openalex.org/A5009004798][Abid Ali]], [[https://openalex.org/A5081498908][Yasir Mehmood]], [[https://openalex.org/A5064930579][Muhammad Ahmad]], [[https://openalex.org/A5066178049][Norah Alwadai]], [[https://openalex.org/A5010504371][Munawar Iqbal]], [[https://openalex.org/A5052430989][Salih Akyürekli]], [[https://openalex.org/A5051204593][Noor Hassan]], [[https://openalex.org/A5050144026][Rizwan Shoukat]], Sustainability. 16(5)] 2024. https://doi.org/10.3390/su16051953  ([[https://www.mdpi.com/2071-1050/16/5/1953/pdf?version=1709030630][pdf]])
     
Hydrogen fuel is a clean and versatile energy carrier that can be used for various applications, including transportation, power generation, and industrial processes. Electrocatalytic water splitting could be the most beneficial and facile approach for producing hydrogen. In this work, transition metal selenide composites with carbon nanotubes (CNTs) have been investigated for electrocatalytic water splitting. The synthesis process involved the facile one-step hydrothermal growth of transition metal nanoparticles over the CNTs and acted as an efficient electrode toward electrochemical water splitting. Scanning electron microscopy and XRD patterns reveal that nanoparticles were firmly anchored on the CNTs, resulting in the formation of composites. The electrochemical measurements reveal that CNT composite with nickel–cobalt selenides (NiCo-Se/CNTs@NF) display remarkable oxygen evolution reaction (OER) activity in basic media, which is an important part of hydrogen production. It demonstrates the lowest overpotential (η10mAcm−2) of 0.560 V vs. RHE, a reduced Tafel slope of 163 mV/dec, and lower charge transfer impedance for the OER process. The multi-metallic selenide composite with CNTs demonstrating unique nanostructure and synergistic effects offers a promising platform for enhancing electrocatalytic OER performance and opens up new avenues for efficient energy conversion and storage applications.    

    

* Ultrasmall Ruthenium Nanoclusters Anchored on Thiol-Functionalized Metal–Organic Framework as a Catalyst for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392191736
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-27
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsanm.3c06102")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392191736"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392191736"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392191736"))][Get cited by]]

OpenAlex: https://openalex.org/W4392191736 (Open access: False)
    
[[https://openalex.org/A5085843260][Biswajit Mishra]], [[https://openalex.org/A5050309292][Swayamprakash Biswal]], [[https://openalex.org/A5065162947][Bijay P. Tripathi]], ACS Applied Nano Materials. None(None)] 2024. https://doi.org/10.1021/acsanm.3c06102 
     
No abstract    

    

* Stability challenges and opportunities of NiFe‐based electrocatalysts for oxygen evolution reaction in alkaline media  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392196226
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-26
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cnl2.110")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392196226"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392196226"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392196226"))][Get cited by]]

OpenAlex: https://openalex.org/W4392196226 (Open access: True)
    
[[https://openalex.org/A5006182339][Yujun Han]], [[https://openalex.org/A5001395097][Jingyi Wang]], [[https://openalex.org/A5064684366][Yuhang Liu]], [[https://openalex.org/A5087372065][Tianqi Li]], [[https://openalex.org/A5031555539][Tongzhou Wang]], [[https://openalex.org/A5024541563][Xinyue Li]], [[https://openalex.org/A5013256964][X. J. Ye]], [[https://openalex.org/A5027334799][Guodong Li]], [[https://openalex.org/A5063383376][Jihong Li]], [[https://openalex.org/A5069789783][Wenbin Hu]], [[https://openalex.org/A5073977425][Yida Deng]], Carbon Neutralization. None(None)] 2024. https://doi.org/10.1002/cnl2.110  ([[https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/cnl2.110][pdf]])
     
Abstract Water splitting is a critical process for the production of green hydrogen, contributing to the advancement of a circular economy. However, the application of water splitting devices on a large scale is primarily impeded by the sluggish oxygen evolution reaction (OER) at the anode. Thus, developing and designing efficient OER catalysts is a significant target. NiFe‐based catalysts are extensively researched as excellent OER electrocatalysts due to their affordability, abundant reserves, and intrinsic activities. However, they still suffer from long‐term stability challenges. To date, few systematic strategies for improving OER durability have been reported. In this review, various advanced NiFe‐based catalysts are introduced. Moreover, the OER stability challenges of NiFe‐based electrocatalysts in alkaline media, including iron segregation, structural degradation, and peeling from the substrate are summarized. More importantly, strategies to enhance OER stability are highlighted and opportunities are discussed to facilitate future stability studies for alkaline water electrolysis. This review presents a design strategy for NiFe‐based electrocatalysts and anion exchange membrane (AEM) electrolyzers to overcome stability challenges in OER, which also emphasizes the importance of long‐term stability in alkaline media and its significance for achieving large‐scale commercialization.    

    

* Pyridine caused structural reconfiguration forming ultrathin 2D metal-organic frameworks for oxygen evolution reaction.  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392205602
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Nanomaterials with Enzyme-Like Characteristics, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ta08079j")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392205602"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392205602"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392205602"))][Get cited by]]

OpenAlex: https://openalex.org/W4392205602 (Open access: False)
    
[[https://openalex.org/A5002109316][Liusi Yang]], [[https://openalex.org/A5077139864][Shuwei Deng]], [[https://openalex.org/A5037703959][Shenyuan Fu]], [[https://openalex.org/A5054834291][Xiaoteng Wang]], [[https://openalex.org/A5013487932][Gang Liu]], [[https://openalex.org/A5033332677][Haidong Yang]], Journal of materials chemistry. A, Materials for energy and sustainability. None(None)] 2024. https://doi.org/10.1039/d3ta08079j 
     
Two-dimensional metal-organic frameworks (2D MOFs) as an ideal prototype material for electrocatalytic oxygen evolution reaction (OER) can expose more metal active sites due to their ultrathin 2D structure. Herein, a...    

    

* Oxygen evolution reaction on iridium-molybdenum mixed oxide electrocatalysts  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392181502
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2019-10-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392181502"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392181502"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392181502"))][Get cited by]]

OpenAlex: https://openalex.org/W4392181502 (Open access: False)
    
[[https://openalex.org/A5047338943][Cédric Tard]], [[https://openalex.org/A5053316352][Marine Elmaalouf]], [[https://openalex.org/A5028372389][Silvia Durán]], [[https://openalex.org/A5017960042][Mateusz Odziomek]], [[https://openalex.org/A5065949519][Marco Faustini]], [[https://openalex.org/A5087775789][Cédric Boissière]], [[https://openalex.org/A5072727657][Marion Giraud]], [[https://openalex.org/A5007926541][Jennifer Péron]], No host. None(None)] 2019. None 
     
No abstract    

    

* The behaviors of electrochemical oxygen intercalation of some oxygen-deficient ferrites and physical properties of perovskite Sr2LaFe3O8.95 prepared by electrochemical oxidation  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392225188
:TOPICS: Synthesis and Applications of Ferrite Nanoparticles, Multiferroic and Magnetoelectric Materials, Magnetocaloric Materials Research
:PUBLICATION_DATE: 1997-06-12
:END:    
    
[[elisp:(doi-add-bibtex-entry "None")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392225188"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392225188"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392225188"))][Get cited by]]

OpenAlex: https://openalex.org/W4392225188 (Open access: True)
    
[[https://openalex.org/A5056667091][Fang Zhou]], No host. None(None)] 1997. None  ([[https://theses.hal.science/tel-00833236/document][pdf]])
     
No abstract    

    

* The role of strain in oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392122210
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jechem.2024.02.007")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392122210"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392122210"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392122210"))][Get cited by]]

OpenAlex: https://openalex.org/W4392122210 (Open access: False)
    
[[https://openalex.org/A5022885630][Zhixuan Feng]], [[https://openalex.org/A5037480797][Chia-Tsen Dai]], [[https://openalex.org/A5026635004][Zhe Zhang]], [[https://openalex.org/A5060430863][Xuefei Lei]], [[https://openalex.org/A5031052370][Wenning Mu]], [[https://openalex.org/A5021363847][Rui Guo]], [[https://openalex.org/A5081185893][Xuanwen Liu]], [[https://openalex.org/A5019520436][Jinyuan You]], Journal of Energy Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jechem.2024.02.007 
     
No abstract    

    

* Oxidation Characterization of Water Immersion Coal on Pore Evolution and Oxygen Adsorption Behavior  :water_splitting:
:PROPERTIES:
:UUID: https://openalex.org/W4392096000
:TOPICS: Mining Technology and Safety Measures, Coalbed Methane Recovery and Utilization Practices, Characterization of Shale Gas Pore Structure
:PUBLICATION_DATE: 2024-02-23
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1007/s11053-024-10314-8")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392096000"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392096000"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392096000"))][Get cited by]]

OpenAlex: https://openalex.org/W4392096000 (Open access: False)
    
[[https://openalex.org/A5044855693][Xinxiao Lu]], [[https://openalex.org/A5087538879][Guoyu Shi]], [[https://openalex.org/A5009414213][Shuo Wang]], [[https://openalex.org/A5065074483][Xiao Jin-xiang]], Natural Resources Research. None(None)] 2024. https://doi.org/10.1007/s11053-024-10314-8 
     
No abstract    

    
