#+filetags: water_splitting
#+TITLE: water splitting
Description: water splitting papers
Created on Sat Feb 24 00:41:36 2024

Found 36 results from 2024-02-17 to 2024-02-24
OpenAlex URLS (not including from_created_date or the API key)
- [[https://api.openalex.org/works?filter=concepts.id%3Ahttps%3A//openalex.org/C135473242]]
- [[https://api.openalex.org/works?filter=title-and-abstract.search%3Aoxygen%20evolution]]

* Modulation Strategies and Activity Descriptors of Spinel Electrocatalysts for Lithium‐Oxygen Batteries  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391879176
:TOPICS: Fuel Cell Membrane Technology, Conducting Polymer Research, Electrocatalysis for Energy Conversion
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/batt.202300609")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391879176"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391879176"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391879176"))][Get cited by]]

OpenAlex: https://openalex.org/W4391879176 (Open access: False)
    
[[https://openalex.org/A5043664105][Yu Pan]], [[https://openalex.org/A5082387651][Ruizhe Xu]], [[https://openalex.org/A5067923609][Chaozhu Shu]], [[https://openalex.org/A5046268649][Chuan Zhao]], [[https://openalex.org/A5018555927][Runjing Li]], [[https://openalex.org/A5053289609][Bo Zhou]], [[https://openalex.org/A5021304952][Jing Liu]], [[https://openalex.org/A5025023889][Jianping Long]], Batteries & Supercaps. None(None)] 2024. https://doi.org/10.1002/batt.202300609 
     
The exploitation of high energy density lithium‐oxygen batteries (LOBs) holds significant importance for energy storage and applications. An efficient cathode catalyst can effectively prevent the accumulation of the insulating insoluble discharge product Li2O2, thereby enhancing the electrochemical performance. Spinel materials, widely available and cost‐effective, exhibit superior catalytic activity, making them ideal candidates for LOBs cathode catalysts. This review aims to offer a comprehensive and insightful overview of the recent progress in the design of spinel‐type electrocatalysts for LOBs. This review exhaustively summarizes various modification strategies applied to spinel materials and emphasizes the influential role of catalytic descriptors in designing highly active spinel‐type catalysts. This review provides guidance for the design and utilization of high‐performance spinel‐type catalysts, thereby contributing to the dynamic development of LOBs.    

    

* Single Transition‐Metal Atom Anchored on a Rhenium Disulfide Monolayer: An Efficient Bifunctional Electrocatalyst for the Oxygen Evolution and Oxygen Reduction Reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391880793
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202308416")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391880793"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391880793"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391880793"))][Get cited by]]

OpenAlex: https://openalex.org/W4391880793 (Open access: False)
    
[[https://openalex.org/A5004910340][Meiling Pan]], [[https://openalex.org/A5059121164][X. Cui]], [[https://openalex.org/A5024066427][Qun Jing]], [[https://openalex.org/A5029207520][Haiming Duan]], [[https://openalex.org/A5082278504][Fangping Ouyang]], [[https://openalex.org/A5034965764][Rong Wu]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202308416 
     
Abstract Developing efficient oxygen evolution reaction (OER) and oxygen reduction reaction (ORR) bifunctional electrocatalysts is attractive for rechargeable metal–air batteries. Meanwhile, single metal atoms embedded in 2D layered transition metal chalcogenides (TMDs) have become a very promising catalyst. Recently, many attentions have been paid to the 2D ReS 2 electrocatalyst due to its unique distorted octahedral 1T’ crystal structure and thickness‐independent electronic properties. Here, the catalytic activity of different transition metal (TM) atoms embedded in ReS 2 using the density functional theory is investigated. The results indicate that TM@ReS 2 exhibits outstanding thermal stability, good electrical conductivity, and electron transfer for electrochemical reactions. And the Ir@ReS 2 and Pd@ReS 2 can be used as OER/ORR bifunctional electrocatalysts with a lower overpotential for OER (η OER ) of 0.44 V and overpotentials for ORR (η ORR ) of 0.26 V and 0.27 V, respectively. The excellent catalytic activity is attributed to the optimal adsorption strength for oxygen intermediates coming from the effective modulation of the electronic structure of ReS 2 after Ir/Pd doping. The results can help to deeply understand the catalytic activity of TM@ReS 2 and develop novel and highly efficient OER/ORR electrocatalysts.    

    

* Hierarchical sea urchin‐like Fe‐doped heazlewoodite for high‐efficient oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391880837
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-02-15
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/cphc.202300414")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391880837"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391880837"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391880837"))][Get cited by]]

OpenAlex: https://openalex.org/W4391880837 (Open access: False)
    
[[https://openalex.org/A5005113911][Ke Shang]], [[https://openalex.org/A5067782993][Junpo Guo]], [[https://openalex.org/A5090235347][Yingjun Ma]], [[https://openalex.org/A5055514273][H.K. Liu]], [[https://openalex.org/A5042956973][Xiaoling Zhang]], [[https://openalex.org/A5082207315][Huizhen Wang]], [[https://openalex.org/A5055588334][Jie Wang]], [[https://openalex.org/A5037738045][Zhenhua Yan]], ChemPhysChem. None(None)] 2024. https://doi.org/10.1002/cphc.202300414 
     
Electrochemical water‐splitting to produce hydrogen is potential to substitute the traditional industrial coal gasification, but the oxygen evolution kinetics at the anode remains sluggish. In this paper, sea urchin‐like Fe doped Ni3S2 catalyst growing on nickel foam (NF) substrate is constructed via a simple two‐step strategy, including surface iron activation and post sulfuration process. The NF‐Fe‐Ni3S2 obtains at temperature of 130 ℃ (NF‐Fe‐Ni3S2‐130) features nanoneedle‐like arrays which are vertically grown on the particles to form sea urchin‐like morphology, features high electrochemical surface area. As oxygen evolution catalyst, NF‐Fe‐Ni3S2‐130 exhibits excellent oxygen evolution activities, fast reaction kinetics, and superior reaction stability. The excellent OER performance of sea urchin‐like NF‐Fe‐Ni3S2‐130 is mainly ascribed to the high‐vertically dispersive of nanoneedles and the existing Fe dopants, which obviously improved the reaction kinetics and the intrinsic catalytic properties. The simple preparation strategy is conducive to establish high‐electrochemical‐interface catalysts, which shows great potential in renewable energy conversion.    

    

* A revolutionary design concept: full-sealed lithium-oxygen batteries  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391888461
:TOPICS: Lithium-ion Battery Management in Electric Vehicles, Lithium-ion Battery Technology, Lithium Battery Technologies
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nanoen.2024.109405")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391888461"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391888461"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391888461"))][Get cited by]]

OpenAlex: https://openalex.org/W4391888461 (Open access: False)
    
[[https://openalex.org/A5045002396][Xiangyu Wen]], [[https://openalex.org/A5021567277][Xingbao Zhu]], [[https://openalex.org/A5019984418][Tao Xing]], [[https://openalex.org/A5058813026][Yuanguo Wu]], [[https://openalex.org/A5015501827][Weichao Yu]], [[https://openalex.org/A5005622840][Zining Man]], [[https://openalex.org/A5000338518][Wenjuan Qi]], [[https://openalex.org/A5029762841][Jiaqi Wang]], [[https://openalex.org/A5082619738][Zhe Lü]], Nano Energy. None(None)] 2024. https://doi.org/10.1016/j.nanoen.2024.109405 
     
At this moment, non-aqueous rechargeable lithium-oxygen batteries (LOBs) with extremely high energy density are regarded as the most viable energy storage devices to potentially replace petroleum. One of the most crucial impediments to their implementation has been ensuring facile oxygen availability. Moreover, as semi-sealed systems, LOBs have confronted challenges including oxygen impurities, product degradation, anode corrosion, frequent side reactions, and mediocre cycling performance. In this work, utilizing the physical adsorption of porous (micro-, meso- and macro-porous) solid carbon materials, we incorporate an oxygen storage layer (OSL) with reversible oxygen ad/desorption capabilities into a LOB to develop novel fully-sealed lithium-oxygen batteries (F-S-LOBs). The results demonstrate mesoporous carbons exhibit optimal oxygen adsorption/desorption kinetics, rendering them highly suitable for F-S-LOBs without developing complex oxygen-permeable membranes or carrying oxygen tanks. The OSL fabricated with mesoporous carbon can sustain battery charge/discharge at various current densities with exceptional cycling performance. Additionally, we provide approximate pore size guidelines for oxygen storage materials to aid future research. This study is anticipated to offer a new robust research direction for metal-air batteries and to forge a new path toward promoting the commercialization and development of this technology.    

    

* Greenly synthesised NCF-LDH as a sustainable electrocatalyst for oxygen evolution reaction with low cell voltage  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391888536
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.catcom.2024.106878")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391888536"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391888536"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391888536"))][Get cited by]]

OpenAlex: https://openalex.org/W4391888536 (Open access: True)
    
[[https://openalex.org/A5040284938][Bakthavachalam Vishnu]], [[https://openalex.org/A5003495311][Sundarraj Sriram]], [[https://openalex.org/A5027764093][Jayaraman Jayabharathi]], Catalysis Communications. None(None)] 2024. https://doi.org/10.1016/j.catcom.2024.106878 
     
The advancement of extremely effective and long-lasting sustainable electrocatalysts developed from abundant earth elements is an emergence aspect in green energy generation. The greenly synthesised NCF-LDH has been shown that promising candidate for the OER process. Mechnochemical processes are often quick, inexpensive, and easily scalable to produce industrial quantities. In comparison with IrO2 (370 mV), the optimum NCF-LDH-X on GC electrode showed the modest required overpotential (240 mV) at 10 mA cm−2. Solar-assisted water oxidation at 1.57 V shows more expert efficacy of NCF-LDH-2 for solar to hydrogen generation. As an outcome, the greenly synthesised NCF-LDH outperformed the high-priced electrocatalysts. Consequently, low-cost industrial-scale H2 generation using commercial solar cells might be possible.    

    

* Triggering efficient Mn active centers by tuning the localized Sr2+ sites in high-entropy ABO3 oxygen electrocatalysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391888627
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149755")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391888627"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391888627"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391888627"))][Get cited by]]

OpenAlex: https://openalex.org/W4391888627 (Open access: False)
    
[[https://openalex.org/A5081531916][Lincheng Xu]], [[https://openalex.org/A5012173709][Yue Wang]], [[https://openalex.org/A5046851457][Yonggao Yan]], [[https://openalex.org/A5047947291][Hao Zhang]], [[https://openalex.org/A5024977426][Xin Chen]], [[https://openalex.org/A5034579880][Fan Li]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149755 
     
Understanding the function of individual elements in high-entropy perovskites is one of the critical issues for the design of inexpensive and efficient bifunctional electrocatalysts. Here, we report our findings in boosting the electrochemical activity and durability of a high-entropy perovskite catalyst via sequential substitution of Sr2+ for the A-site elements. According to the Sr2+ localized tuned, the catalyst of (LaSmGdSrPr)0.2MnO3 has a half-wave potential of 0.786 V vs. RHE and an overpotential of 0.378 V and has better ORR and OER electrocatalytic activity than the Sr-free high-entropy perovskite catalyst (LaSmGdYPr)0.2MnO3.This is attributed to the local doping of Sr2+ activating the active center of the high-entropy perovskite catalyst (LaSmGdSrPr)0.2MnO3, modulating the adsorption energy of the oxygen-containing intermediates and the electronic structure of the transition metal at the B-site, which results in efficient oxygen electrocatalytic activity. On the other hand, the introduction of Sr2+ enhances the hybridization between Mn 2p and O 1 s and accelerates the adsorption and desorption kinetics of the intermediates, leading to both enhanced activity and durability of (LaSmGdSrPr)0.2MnO3. DFT theoretical calculations also demonstrate the key role played by Sr2+ in the high-entropy perovskite structure for the improvement of the electrocatalytic activity. This study provides new insights for designing high-entropy electrocatalysts for various potential applications.    

    

* Ionic liquid in-situ functionalized carbon nanotube film as self-supported metal-free electrocatalysts for oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391888650
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149767")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391888650"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391888650"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391888650"))][Get cited by]]

OpenAlex: https://openalex.org/W4391888650 (Open access: False)
    
[[https://openalex.org/A5005226621][Tianhao Li]], [[https://openalex.org/A5016171317][Yage Wang]], [[https://openalex.org/A5017384752][Tingting Chen]], [[https://openalex.org/A5068049785][Guangzhao Wang]], [[https://openalex.org/A5055876656][Chenglong Qiu]], [[https://openalex.org/A5069482443][Weihua Hu]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149767 
     
The oxygen evolution reaction (OER) is a critical cathode reaction for hydrogen production from water splitting. However, due to the sluggish kinetics of OER, the water-splitting process is impeded. Thus, it is imperative to develop efficient and low-cost electrocatalysts that reduce the overpotential and improve the kinetics of OER. Herein, an in-situ synthesis strategy was applied to prepare the ionic liquid functionalized carbon nanotube (IL-CNT) that served as a metal-free electrocatalyst for OER. This powder material exhibited exceptional electrocatalytic activity for OER, with an overpotential of 335 mV at 10 mA cm−2 and a Tafel slope of 71 mV dec-1. Then, it was found that catalytic activity was influenced by the IL anion. Moreover, this IL-CNT powder could self-assemble to form carbon film during preparation, exhibiting outstanding catalytic activity for OER (a low overpotential of 153 mV at 10 mA cm−2), which was highly beneficial for practical application. Based on the theoretical calculations and experimental results, these in-situ functionalization sites on CNT surface played a significant role in regulating their electron structure. This, in turn, promoted electron transfer and hydroxyl adsorption, resulting in a substantial increase in catalytic activity for the OER.    

    

* Key Role of Subsurface Doping in Optimizing Active Sites of IrO2 for Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391890840
:TOPICS: Catalytic Nanomaterials, Atomic Layer Deposition Technology, Emergent Phenomena at Oxide Interfaces
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4cc00075g")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391890840"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391890840"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391890840"))][Get cited by]]

OpenAlex: https://openalex.org/W4391890840 (Open access: False)
    
[[https://openalex.org/A5089250541][Xindi Han]], [[https://openalex.org/A5004836336][Lu-E Shi]], [[https://openalex.org/A5011090841][Hui Chen]], [[https://openalex.org/A5046104594][Xiaoxin Zou]], Chemical Communications. None(None)] 2024. https://doi.org/10.1039/d4cc00075g 
     
The oxygen evolution reaction (OER) over a family of metal-doped rutile IrO2 catalysts is theoretically investigated by controlling the species and position of doping elements. The subsurface substitution doping is...    

    

* Enhanced Electrocatalytic Oxygen Reduction Reaction of TiO2 Nanotubes by Combining Surface Oxygen Vacancy Engineering and Zr Doping  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391893370
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.3390/nano14040366")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391893370"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391893370"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391893370"))][Get cited by]]

OpenAlex: https://openalex.org/W4391893370 (Open access: True)
    
[[https://openalex.org/A5004546616][Maged N. Shaddad]], [[https://openalex.org/A5082353856][Prabhakarn Arunachalam]], [[https://openalex.org/A5034359786][Mahmoud Hezam]], [[https://openalex.org/A5007727648][Saba A. Aladeemy]], [[https://openalex.org/A5022053524][Mamduh J. Aljaafreh]], [[https://openalex.org/A5020964148][Sharif Abu Alrub]], [[https://openalex.org/A5030651199][Abdullah M. Al‐Mayouf]], Nanomaterials. 14(4)] 2024. https://doi.org/10.3390/nano14040366  ([[https://www.mdpi.com/2079-4991/14/4/366/pdf?version=1708066838][pdf]])
     
This work examines the cooperative effect between Zr doping and oxygen vacancy engineering in anodized TiO2 nanotubes (TNTs) for enhanced oxygen reduction reactions (ORRs). Zr dopant and annealing conditions significantly affected the electrocatalytic characteristics of grown TNTs. Zr doping results in Zr4+ substituted for Ti4+ species, which indirectly creates oxygen vacancy donors that enhance charge transfer kinetics and reduce carrier recombination in TNT bulk. Moreover, oxygen vacancies promote the creation of unsaturated Ti3+(Zr3+) sites at the surface, which also boosts the ORR interfacial process. Annealing at reductive atmospheres (e.g., H2, vacuum) resulted in a larger increase in oxygen vacancies, which greatly enhanced the ORR activity. In comparison to bare TNTs, Zr doping and vacuum treatment (Zr:TNT–Vac) significantly improved the conductivity and activity of ORRs in alkaline media. The finding also provides selective hydrogen peroxide production by the electrochemical reduction of oxygen.    

    

* Iridium-Based Perovskites as Efficient Oxygen Evolution Reaction Catalysts in Acid Media  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391895875
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-02-17
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acsaenm.3c00713")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391895875"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391895875"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391895875"))][Get cited by]]

OpenAlex: https://openalex.org/W4391895875 (Open access: False)
    
[[https://openalex.org/A5062340921][Hossein Fadaei]], [[https://openalex.org/A5050744084][Carl W. Brown]], [[https://openalex.org/A5060364670][Georges Houlachi]], [[https://openalex.org/A5029340956][Houshang Alamdari]], ACS Applied Engineering Materials. None(None)] 2024. https://doi.org/10.1021/acsaenm.3c00713 
     
No abstract    

    

* Optimizing Oxygen-Production Kinetics of Manganese Dioxide Nanoparticles Improves Hypoxia Reversal and Survival in Mice with Bone Metastases  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391899438
:TOPICS: Nanotechnology and Imaging for Cancer Therapy and Diagnosis, Metabolic Reprogramming in Cancer Biology, Nanoparticle-Based Drug Delivery Systems
:PUBLICATION_DATE: 2024-02-16
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acs.molpharmaceut.3c00671")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391899438"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391899438"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391899438"))][Get cited by]]

OpenAlex: https://openalex.org/W4391899438 (Open access: False)
    
[[https://openalex.org/A5054164050][Declan Murphy]], [[https://openalex.org/A5093946466][Daniela Osteicochea]], [[https://openalex.org/A5069877793][Aidan Atkins]], [[https://openalex.org/A5093946467][Caitlin Sannes]], [[https://openalex.org/A5093946468][Zachary McClarnon]], [[https://openalex.org/A5028558981][Isaac M. Adjei]], Molecular Pharmaceutics. None(None)] 2024. https://doi.org/10.1021/acs.molpharmaceut.3c00671 
     
Persistent hypoxia in bone metastases induces an immunosuppressive environment, limiting the effectiveness of immunotherapies. To address chronic hypoxia, we have developed manganese dioxide (MnO2) nanoparticles with tunable oxygen production kinetics for sustained oxygenation in bone metastases lesions. Using polyethylene glycol (PEG)-stabilized MnO2 or poly(lactic[50]-co-glycolic[50] acid) (50:50 PLGA), poly(lactic[75]-co-glycolic[25] acid) (75:25 PLGA), and polylactic acid (PLA)-encapsulated MnO2 NPs, we demonstrate that polymer hydrophobicity attenuates burst oxygen production and enables tunable oxygen production kinetics. The PEG-MnO2 NPs resulted in rapid hypoxia reduction in spheroids, which was rapidly attenuated, while the PLA-MnO2 NPs exhibited delayed hypoxia control in cancer spheroids. The 50:50 PLGA-MnO2 NPs exhibited the best short- and long-term control of hypoxia in cancer spheroids, resulting in sustained regulation of the expression of HIF-1α and immunosuppressive genes. The sustained control of hypoxia by the 50:50 PLGA-MnO2 NPs enhanced the cytotoxicity of natural killer cells against cancer spheroids. In vivo, 50:50 PLGA-MnO2 showed greater accumulation in the long bones and pelvis, common sites for bone metastases. The NPs decreased hypoxia in bone metastases and decreased regulatory T cell levels, resulting in enhanced survival of mice with established bone metastases.    

    

* Fabrication and characterisation of CrMnFeCoNi high entropy alloy electrocatalyst for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391906377
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, High-Entropy Alloys: Novel Designs and Properties
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.apmt.2024.102128")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391906377"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391906377"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391906377"))][Get cited by]]

OpenAlex: https://openalex.org/W4391906377 (Open access: False)
    
[[https://openalex.org/A5017816629][Xun Cao]], Applied Materials Today. 37(None)] 2024. https://doi.org/10.1016/j.apmt.2024.102128 
     
Water electrolysis is attracting increasing attention in becoming the main method for green energy production, which has long been hindered by the sluggish kinetics of oxygen evolution reaction (OER) and high cost of noble-metal (NM) containing electrodes. Template replication technique has been employed to fabricate porous CrMnFeCoNi high entropy alloy (HEA) bulk foams with > 95 % porosity. High entropy led to the formation of a single-phase solid solution of transition metals in the as-fabricated porous HEA bulk foam, and the lattice distortion brings about the outstanding OER performance that is close to that of the RuO2 reference sample. Effective electrochemically active surface area and amount of exposed active sites are increased by grinding into nanoparticles, which produced superior OER performance with a near-record low overpotential of ∼ 245 mV to drive a current density of 10 mA/cm2, a low Tafel slope of 73.6 mV/dec, a double layer capacitance of 102.3 mF, and excellent long-term stability over 24 h. This work demonstrates a cost-effective way to fabricate NM-free HEA electrocatalyst with complex structure and excellent stability in OER, which could help in advancing the research for alkaline water electrolysis.    

    

* The Role of Reducibility vis-à-vis Oxygen Vacancies of doped Co3O4/CeO2 in Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391913283
:TOPICS: Catalytic Nanomaterials, Solid Oxide Fuel Cells, Catalytic Dehydrogenation of Light Alkanes
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dt00315b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391913283"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391913283"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391913283"))][Get cited by]]

OpenAlex: https://openalex.org/W4391913283 (Open access: True)
    
[[https://openalex.org/A5047126873][Saraswati Roy]], [[https://openalex.org/A5022592991][Preeti Dahiya]], [[https://openalex.org/A5050699362][Tapas Kumar Mandal]], [[https://openalex.org/A5068743211][Sounak Roy]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d4dt00315b 
     
Electrochemical water splitting, a highly promising and environmentally friendly technology for H2 fuel production, faces significant hurdles due to the sluggish kinetics of the oxygen evolution reaction. Co based oxide...    

    

* Correction: Spent tea leaves templated synthesis of highly active and durable cobalt-based trifunctional versatile electrocatalysts for hydrogen and oxygen evolution and oxygen reduction reactions  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391926812
:TOPICS: Nanomaterials with Enzyme-Like Characteristics, Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4gc90017k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391926812"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391926812"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391926812"))][Get cited by]]

OpenAlex: https://openalex.org/W4391926812 (Open access: True)
    
[[https://openalex.org/A5063363228][Ariful Ahsan]], [[https://openalex.org/A5033283090][Muhammad A. Imam]], [[https://openalex.org/A5052938805][Alain R. Puente Santiago]], [[https://openalex.org/A5074843219][Alejandro Rodrı́guez]], [[https://openalex.org/A5062849452][Bonifacio Alvarado-Tenorio]], [[https://openalex.org/A5009293092][Ricardo A. Bernal]], [[https://openalex.org/A5078421218][Rafael Luque]], [[https://openalex.org/A5007869284][Juan C. Noveron]], Green Chemistry. None(None)] 2024. https://doi.org/10.1039/d4gc90017k  ([[https://pubs.rsc.org/en/content/articlepdf/2024/gc/d4gc90017k][pdf]])
     
Correction for ‘Spent tea leaves templated synthesis of highly active and durable cobalt-based trifunctional versatile electrocatalysts for hydrogen and oxygen evolution and oxygen reduction reactions’ by Md Ariful Ahsan et al. , Green Chem. , 2020, 22 , 6967–6980, https://doi.org/10.1039/D0GC02155E.    

    

* Transpassive Metal Dissolution vs. Oxygen Evolution Reaction: Implication for Alloy Stability and Electrocatalysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391944172
:TOPICS: Atom Probe Tomography Research
:PUBLICATION_DATE: 2024-02-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/ange.202317058")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391944172"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391944172"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391944172"))][Get cited by]]

OpenAlex: https://openalex.org/W4391944172 (Open access: False)
    
[[https://openalex.org/A5076601076][Annica Wetzel]], [[https://openalex.org/A5093888344][Daniel Morell]], [[https://openalex.org/A5017993519][Marcus von der Au]], [[https://openalex.org/A5038064548][Günther Wittstock]], [[https://openalex.org/A5072476528][Özlem Özcan]], [[https://openalex.org/A5044822731][Julia Witt]], Angewandte Chemie. None(None)] 2024. https://doi.org/10.1002/ange.202317058 
     
Multi‐principal element alloys (MPEAs) are gaining interest in corrosion and electrocatalysis research due to their electrochemical stability across a broad pH range and the design flexibility they offer. Using the equimolar CrCoNi alloy, we observe significant metal dissolution in a corrosive electrolyte (0.1 M NaCl, pH 2) concurrently with the oxygen evolution reaction (OER) in the transpassive region despite the absence of hysteresis in polarization curves or other obvious corrosion indicators. We present a characterization scheme to delineate the contribution of OER and alloy dissolution, using scanning electrochemical microscopy (SECM) for OER‐onset detection, and quantitative chemical analysis with inductively coupled‐mass spectrometry (ICP‐MS) and ultraviolet visible light (UV‐Vis) spectroscopy to elucidate metal dissolution processes. In‐situ electrochemical atomic force microscopy (EC‐AFM) revealed that the transpassive metal dissolution on CrCoNi is dominated by intergranular corrosion. These results have significant implications for the stability of MPEAs in corrosion systems, emphasizing the necessity of analytically determining metal ions released from MPEA electrodes into the electrolyte when evaluating Faradaic efficiencies of OER catalysts. The release of transition metal ions not only reduces the Faradaic efficiency of electrolyzers but may also cause poisoning and degradation of membranes in electrochemical reactors.    

    

* Alkali Containing Layered Metal Oxides as Catalysts for the Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391948002
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-19
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/celc.202300761")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391948002"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391948002"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391948002"))][Get cited by]]

OpenAlex: https://openalex.org/W4391948002 (Open access: True)
    
[[https://openalex.org/A5076436151][Mario Falsaperna]], [[https://openalex.org/A5007560583][Rosa Arrigo]], [[https://openalex.org/A5071095075][Frank Marken]], [[https://openalex.org/A5044793501][Simon J. Freakley]], ChemElectroChem. None(None)] 2024. https://doi.org/10.1002/celc.202300761 
     
Abstract Improving the efficiency of the oxygen evolution reaction (OER) is essential to realise energy systems based on water electrolysis. Many catalysts have been developed for the OER to date, with iridium‐based oxides being the most promising due to their relative stability towards corrosion in acidic electrolytes under oxidising potentials. In recent years, examples of catalysts adopting layered structures have been shown to have promising characteristics such as higher conductivity and higher electrochemically active surface area compared to highly crystalline metal oxides. Furthermore, such materials possess additional tuneable properties such as interlayer spacing, identity and concentration of the interlayer species, edge and interlayer active sites, and higher active surface area. Recent attention has focused on mono‐ and polymetallic lithium‐containing layered materials, where the presence of interlayer lithium cations, in situ delithiation processes and combinations of transition metal oxides result in enhanced catalytic properties towards OER. This review aims to provide a summary of the recent developments of such layered materials, in which lithium or other alkali metal ions occupy interlayer sites in oxides.    

    

* Doping Ru on FeNi LDH/FeⅡ/Ⅲ-MOF heterogeneous core-shell structure for efficient oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391948180
:TOPICS: Catalytic Nanomaterials, Electrocatalysis for Energy Conversion, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4dt00008k")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391948180"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391948180"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391948180"))][Get cited by]]

OpenAlex: https://openalex.org/W4391948180 (Open access: False)
    
[[https://openalex.org/A5038834523][Yijia Cao]], [[https://openalex.org/A5057814323][Yan Wen]], [[https://openalex.org/A5041756956][Yanrong Liu]], [[https://openalex.org/A5086361638][Mengya Cao]], [[https://openalex.org/A5057603195][Bao Li]], [[https://openalex.org/A5036911553][Qing Shen]], [[https://openalex.org/A5003733633][Wen Gu]], Dalton Transactions. None(None)] 2024. https://doi.org/10.1039/d4dt00008k 
     
Noble metal based catalysts as RuO2 and IrO2 have been widely used in the catalysis of OER. Because of the high price and poor stability, it is urgent to develop...    

    

* Glassy State Hydroxide Materials for Oxygen Evolution Electrocatalysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391952436
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202312168")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391952436"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391952436"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391952436"))][Get cited by]]

OpenAlex: https://openalex.org/W4391952436 (Open access: False)
    
[[https://openalex.org/A5037677450][Jing Wang]], [[https://openalex.org/A5013419645][Jingyu Chen]], [[https://openalex.org/A5003605384][Jian Zhang]], [[https://openalex.org/A5007627021][Qiang Gao]], [[https://openalex.org/A5043105845][Bo Han]], [[https://openalex.org/A5032667823][Ruimin Sun]], [[https://openalex.org/A5084756664][Chenggang Zhou]], [[https://openalex.org/A5091556593][Zhao Cai]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202312168 
     
Abstract Hydroxides are the archetype of layered crystals with metal‐oxygen (M‐O) octahedron units, which have been widely investigated as oxygen evolution reaction (OER) catalysts. However, the better crystallinity of hydroxide materials, the more perfect octahedral symmetry and atomic ordering, resulting in the less exposed metal sites and limited electrocatalytic activity. Herein, a glassy state hydroxide material featuring with short‐range order and long‐range disorder structure is developed to achieve high intrinsic activity for OER. Specifically, a rapid freezing point precipitation method is utilized to fabricate amorphous multi‐component hydroxide. Owing to the freezing‐point crystallization environment and chaotic M‐O (M = Ni/Fe/Co/Mn/Cr etc.) structures, the as‐fabricated NiFeCoMnCr hydroxide exhibit a highly‐disordered glassy structure, as‐confirmed by X‐ray/electron diffraction, enthalpic response, and pair distribution function analysis. The as‐achieved glassy‐state hydroxide materials display a low OER overpotential of 269 mV at 20 mA cm −2 with a small Tafel slope of 33.3 mV dec −1 , outperform the benchmark noble‐metal RuO 2 catalyst (341 mV, 84.9 mV dec −1 ) . Operando Raman and density functional theory studies reveal that the glassy state hydroxide converted into disordered active oxyhydroxide phase with optimized oxygen intermediates adsorption under low OER overpotentials, thus boosting the intrinsic electrocatalytic activity.    

    

* From Synthesis to Mechanisms: In‐Depth Exploration of the Dual‐Atom Catalytic Mechanisms Toward Oxygen Electrocatalysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391952929
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Accelerating Materials Innovation through Informatics
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202311434")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391952929"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391952929"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391952929"))][Get cited by]]

OpenAlex: https://openalex.org/W4391952929 (Open access: False)
    
[[https://openalex.org/A5032200326][Lei Lei]], [[https://openalex.org/A5026097984][Xinghua Guo]], [[https://openalex.org/A5089619087][Xu Han]], [[https://openalex.org/A5056012629][Fei Ling]], [[https://openalex.org/A5005863427][Xiangmin Guo]], [[https://openalex.org/A5084430513][D D Wang]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202311434 
     
Abstract Dual‐atom catalysts (DACs) hold a higher metal atom loading and provide greater flexibility in terms of the structural characteristics of their active sites in comparison to SACs. Consequently, DACs hold great promise for achieving improved catalytic performance. This article aims to provide a focused overview of the latest advancements in DACs, covering their synthesis and mechanisms in reversible oxygen electrocatalysis, which plays a key role in sustainable energy conversion and storage technologies. The discussion starts by highlighting the structures of DACs and the differences in diatomic coordination induced by various substrates. Subsequently, the state‐of‐the‐art fabrication strategies of DACs for oxygen electrocatalysis are discussed from several different perspectives. It particularly highlights the challenges of increasing the diatomic loading capacity. More importantly, the main focus of this overview is to investigate the correlation between the configuration and activity in DACs in order to gain a deeper understanding of their active roles in oxygen electrocatalysis. This will be achieved through density functional theory (DFT) calculations and sophisticated in situ characterization technologies. The aim is to provide guidelines for optimizing and upgrading DACs in oxygen electrocatalysis. Additionally, the overview discusses the current challenges and future prospects in this rapidly evolving area of research. This article is protected by copyright. All rights reserved    

    

* A fingerprint-like supramolecular-assembled Ag3PO4/polydopamine/g-C3N4 heterojunction nanocomposite for enhanced solar-driven oxygen evolution in vivo  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391953305
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Perovskite Solar Cell Technology, Nanomaterials with Enzyme-Like Characteristics
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jcis.2024.02.087")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391953305"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391953305"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391953305"))][Get cited by]]

OpenAlex: https://openalex.org/W4391953305 (Open access: False)
    
[[https://openalex.org/A5019386186][Shihong Shen]], [[https://openalex.org/A5015770587][Qian Gao]], [[https://openalex.org/A5048921157][Zhenpeng Hu]], [[https://openalex.org/A5043935829][Daidi Fan]], Journal of Colloid and Interface Science. None(None)] 2024. https://doi.org/10.1016/j.jcis.2024.02.087 
     
Biocompatible photocatalytic water-splitting systems are promising for tissue self-oxygenation. Herein, a structure–function dual biomimetic fingerprint-like silver phosphate/polydopamine/graphitic carbon nitride (Ag3PO4/PDA/g-C3N4) heterojunction nanocomposite is proposed for enhanced solar-driven oxygen (O2) evolution in vivo in situ. Briefly, a porous nitrogen-defected g-C3N4 nanovoile (CN) is synthesized as the base. Dopamine molecules are controllably inserted into the CN interlayer, forming PDA spacers (4.28 nm) through self-polymerization-induced supramolecular-assembly. Ag3PO4 nanoparticles are then in situ deposited to create Ag3PO4/PDA/CN. The fingerprint-like structure of PDA/CN enlarges the layer spacing, thereby accelerating mass transfer and increasing reaction sites. The PDA spacer roles as excellent light harvester, electronic-ionic conductor, and redox pair through conformational changes, resulting in tailored electronic band structure, optimized carrier behavior, and reduced electrochemical impedance. In physiological conditions, Ag3PO4/PDA/CN exhibits O2 evolution rate of 45.35 μmol⋅g−1⋅h−1, 9-fold of bulk g-C3N4. The biocompatibility and in vivo oxygen supply effectiveness for biomedical applications have been verified in animal models.    

    

* Enhanced Electrocatalytic Oxygen Evolution Reaction by Photothermal Effect and Its Induced Micro-electric Field  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391955701
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d4nr00170b")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391955701"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391955701"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391955701"))][Get cited by]]

OpenAlex: https://openalex.org/W4391955701 (Open access: False)
    
[[https://openalex.org/A5058002676][Feng Ding]], [[https://openalex.org/A5023418189][Qian Zou]], [[https://openalex.org/A5093960993][Li Junzhe]], [[https://openalex.org/A5075233676][Xianrui Yuan]], [[https://openalex.org/A5037920786][Xun Cui]], [[https://openalex.org/A5061945778][Chuan Jing]], [[https://openalex.org/A5028101986][Shuman Tao]], [[https://openalex.org/A5088522668][Xiujuan Wei]], [[https://openalex.org/A5069817927][Huichao He]], [[https://openalex.org/A5047377429][Yingze Song]], Nanoscale. None(None)] 2024. https://doi.org/10.1039/d4nr00170b 
     
Promoting better thermodynamics and kinetics of electrocatalysts is the key to achieving efficient electrocatalytic oxygen evolution reaction (OER). Utilizing the photothermal effect and micro-electric field of electrocatalyst is a promising...    

    

* Fabrication of Highly Efficient FeNi-based Electrodes using Thermal Plasma Spray for Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391957745
:TOPICS: Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.surfin.2024.104091")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391957745"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391957745"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391957745"))][Get cited by]]

OpenAlex: https://openalex.org/W4391957745 (Open access: False)
    
[[https://openalex.org/A5073057852][B. Narayanan]], [[https://openalex.org/A5066726222][Lakshmanan Kumaresan]], [[https://openalex.org/A5003611696][G. Shanmugavelayutham]], Surfaces and Interfaces. None(None)] 2024. https://doi.org/10.1016/j.surfin.2024.104091 
     
No abstract    

    

* Challenges and progress in oxygen evolution reaction catalyst development for seawater electrolysis for hydrogen production  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391958854
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1039/d3ra08648h")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391958854"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391958854"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391958854"))][Get cited by]]

OpenAlex: https://openalex.org/W4391958854 (Open access: True)
    
[[https://openalex.org/A5089450078][Joel C. Corbin]], [[https://openalex.org/A5002185829][M. Jones]], [[https://openalex.org/A5042026897][Cheng Liu]], [[https://openalex.org/A5041409819][Adeline Loh]], [[https://openalex.org/A5045309022][Zhenyu Zhang]], [[https://openalex.org/A5088619248][Yan Zhu]], [[https://openalex.org/A5020406154][Xiaohong Li]], RSC Advances. 14(9)] 2024. https://doi.org/10.1039/d3ra08648h 
     
Modification techniques to oxygen evolution reaction (OER) electrocatalysts for direct seawater electrolysis (DSWE) to mitigate chloride corrosion from seawater.    

    

* Silver Nanowires Cascaded Layered Double Hydroxides Nanocages with Enhanced Directional Electron Transport for Efficient Electrocatalytic Oxygen Evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391958988
:TOPICS: Electrocatalysis for Energy Conversion, Photocatalytic Materials for Solar Energy Conversion, Aqueous Zinc-Ion Battery Technology
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/smll.202309859")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391958988"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391958988"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391958988"))][Get cited by]]

OpenAlex: https://openalex.org/W4391958988 (Open access: False)
    
[[https://openalex.org/A5011581422][Jinchen Fan]], [[https://openalex.org/A5067934401][Jin Ma]], [[https://openalex.org/A5089424513][Liuliu Zhu]], [[https://openalex.org/A5016212362][Hui Wang]], [[https://openalex.org/A5082506540][Weiju Hao]], [[https://openalex.org/A5029104177][Yulin Min]], [[https://openalex.org/A5025388218][Qingyuan Bi]], [[https://openalex.org/A5013446276][Guisheng Li]], Small. None(None)] 2024. https://doi.org/10.1002/smll.202309859 
     
Abstract Designing and fabricating highly efficient oxygen evolution reaction (OER) electrocatalytic materials for water splitting is a promising and practical approach to green and sustainable low‐carbon energy systems. Herein, a facile in situ growth self‐template strategy by using ZIF‐67 as a consumable layered double hydroxides (LDHs) template and silver nanowires (AgNWs) as 1D conductive cascaded substrate to controllably synthesize the target AgNWs@CoFe‐LDH composites with unique hollow shell sugar gourd‐like structure and enhanced directional electron transport effect is reported. The AgNWs exhibit the key functions of the close connection of CoFe‐LDH nanocages and the support of the directional electron transport effect in the composite catalyst inducing electrons directionally moving from CoFe‐LDH to AgNWs. Meanwhile, the CoFe‐LDH nanocages with ultrathin nanosheets and hollow structural properties show abundant active sites for electrocatalytic oxygen generation. The versatile AgNWs@CoFe‐LDH catalyst with optimized components, enhanced directional electron transport, and synergistic effect achieves high OER performance with the overpotential of 207 mV and long‐term 50 h stability at 10 mA cm −2 in an alkaline medium. Moreover, in‐depth insights into the microstructure, structure‐activity relationships, identification of key intermediate species, and a proton‐coupled four‐electron OER mechanism based on experimental discovery and theoretical calculation are also demonstrated.    

    

* The Synergistic Effect of IR and Oxygen Vacancies on Enhancing the Oer Performance of Surface-Reconstructed Feco Ldh  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391973777
:TOPICS: Catalytic Nanomaterials, Zinc Oxide Nanostructures, Advanced Materials for Smart Windows
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4732029")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391973777"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391973777"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391973777"))][Get cited by]]

OpenAlex: https://openalex.org/W4391973777 (Open access: False)
    
[[https://openalex.org/A5020035945][Xianjun Deng]], [[https://openalex.org/A5064703123][Jinwei Chen]], [[https://openalex.org/A5078326314][Qiuyan Chen]], [[https://openalex.org/A5051959681][Yunzhe Zhou]], [[https://openalex.org/A5037956890][Xinchi Liu]], [[https://openalex.org/A5014840423][Jie Zhang]], [[https://openalex.org/A5030921116][Gang Wang]], [[https://openalex.org/A5005949841][Ruilin Wang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4732029 
     
Download This Paper Open PDF in Browser Add Paper to My Library Share: Permalink Using these links will ensure access to this page indefinitely Copy URL Copy DOI    

    

* Electrodeposited graphene@Co3O4 nanosheets for oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4392014924
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Electrochemical Biosensor Technology
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.234219")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392014924"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392014924"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392014924"))][Get cited by]]

OpenAlex: https://openalex.org/W4392014924 (Open access: False)
    
[[https://openalex.org/A5075883325][Qianyu Wang]], [[https://openalex.org/A5026017086][Zi-Ye Liu]], [[https://openalex.org/A5076421896][Ji-Ming Hu]], Journal of Power Sources. 599(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.234219 
     
No abstract    

    

* Construction of nickel phosphide/iron oxyhydroxide heterostructure nanoparticles for oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4392005890
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.nanoen.2024.109402")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392005890"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392005890"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392005890"))][Get cited by]]

OpenAlex: https://openalex.org/W4392005890 (Open access: False)
    
[[https://openalex.org/A5044626392][Yichuang Xing]], [[https://openalex.org/A5010940638][Shuling Liu]], [[https://openalex.org/A5010274839][Yuan Liu]], [[https://openalex.org/A5075441298][Xuechun Xiao]], [[https://openalex.org/A5085736683][Yvpei Li]], [[https://openalex.org/A5015077424][Zeyi Wang]], [[https://openalex.org/A5028748116][Yafei Hu]], [[https://openalex.org/A5086324364][B. Xin]], [[https://openalex.org/A5021471823][He Wang]], [[https://openalex.org/A5061165588][Chao Wang]], Nano Energy. None(None)] 2024. https://doi.org/10.1016/j.nanoen.2024.109402 
     
Active and stable oxygen evolution electrocatalysts are essential in increasing the efficiency of the water electrolyzers. The Ni2P/Fe(O)OH heterostructure nanoparticles are prepared via solvothermal phosphidization of Ni metal-organic frameworks (MOF) followed by immersing in Fe3+ aqueous solution. Characterizations reveal that the Ni2P/Fe(O)OH heterostructure nanoparticles are 12.83 nm in size averagely, and the heterointerface induces electron interactions between the Ni2P and Fe(O)OH phases. When used to catalyze OER in alkaline solutions, the Ni2P/Fe(O)OH-40/nickel foam (NF) is the most active and exhibits 240 mV overpotential to reach 10 mA cm-2 oxygen evolution (OER) current densities, which is significantly better than the Ni2P/NF. Lower apparent activation energy, charge transfer resistance, and Tafel slope, along with higher electron rate constant are observed at Ni2P/Fe(O)OH-40/NF, which suggests that the OER kinetics is more facile at the heterostructure surface. Both Ni2P/Fe(O)OH-40/NF and Ni2P/NF involve decoupled electron and proton transfer process, and higher degree of lattice oxygen oxidation mechanism (LOM) participation is observed at Ni2P/Fe(O)OH-40/NF, which results from the increased acidity of the Ni3+ sites. Density functional theory calculations prove that the formation of heterostructure with Fe(O)OH alters the band structure and the OER intermediate adsorption energies, that lead to lower energy barrier in the rate-determining step. The Ni2P/Fe(O)OH-40/NF is also stable towards OER in alkaline solutions.    

    

* Stainless Steel Activation for Efficient Alkaline Oxygen Evolution in Advanced Electrolyzers  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391981888
:TOPICS: Fuel Cell Membrane Technology, Electrocatalysis for Energy Conversion, Solid Oxide Fuel Cells
:PUBLICATION_DATE: 2024-02-20
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/adma.202312071")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391981888"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391981888"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391981888"))][Get cited by]]

OpenAlex: https://openalex.org/W4391981888 (Open access: False)
    
[[https://openalex.org/A5028765513][Yong Zuo]], [[https://openalex.org/A5093966575][Valentina Mastronard]], [[https://openalex.org/A5093575180][Agnese Gamberini]], [[https://openalex.org/A5034371294][Marilena Isabella Zappia]], [[https://openalex.org/A5031285770][Thi‐Hong‐Hanh Le]], [[https://openalex.org/A5004029612][Mirko Prato]], [[https://openalex.org/A5082004546][Silvia Dante]], [[https://openalex.org/A5006596283][Sebastiano Bellani]], [[https://openalex.org/A5025956413][Liberato Manna]], Advanced Materials. None(None)] 2024. https://doi.org/10.1002/adma.202312071 
     
Abstract Designing robust and cost‐effective electrocatalysts for efficient alkaline oxygen evolution reaction (OER) is of great significance in the field of water electrolysis. In this study, we introduce an electrochemical strategy to activate stainless steel (SS) electrodes for efficient OER. By cycling the SS electrode within a potential window that encompasses the Fe(II)↔Fe(III) process, we can greatly enhance its OER activity compared to using a potential window that excludes this redox reaction, decreasing the overpotential at current density of 100 mA cm −2 by 40 mV. Electrochemical characterization, Inductively Coupled Plasma – Optical Emission Spectroscopy and operando Raman measurements demonstrated that the Fe leaching at the SS surface can be accelerated through a Fe → γ‐Fe 2 O 3 → Fe 3 O 4 or FeO → Fe 2+ (aq.) conversion process, leading to the sustained exposure of Cr and Ni species. While Cr leaching occurs during its oxidation process, Ni species display higher resistance to leaching and gradually accumulate on the SS surface in the form of OER‐active Fe‐incorporated NiOOH species. Furthermore, a potential‐pulse strategy was also introduced to regenerate the OER‐activity of 316‐type SS for stable OER, both in the three‐electrode configuration (without performance decay after 300 h at 350 mA cm −2 ) and in an alkaline water electrolyzer (ca. 30 mV cell voltage increase after accelerated stress test‐AST). The AST‐stabilized cell can still reach 1000 mA cm −2 and 4000 mA cm −2 at cell voltages of 1.69 V and 2.1 V, which makes it competitive with state‐of‐the‐art electrolyzers based on ion‐exchange‐membranes using Ir‐based anodes. This article is protected by copyright. All rights reserved    

    

* Dense Heterogeneous Interfaces Boost the Electrocatalytic Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4392000713
:TOPICS: Electrochemical Detection of Heavy Metal Ions, Electrocatalysis for Energy Conversion, Fuel Cell Membrane Technology
:PUBLICATION_DATE: 2024-01-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.2139/ssrn.4733793")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392000713"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392000713"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392000713"))][Get cited by]]

OpenAlex: https://openalex.org/W4392000713 (Open access: False)
    
[[https://openalex.org/A5032711329][Shuai Liu]], [[https://openalex.org/A5083980378][Fumin Wang]], [[https://openalex.org/A5044785404][Jiawei Wang]], [[https://openalex.org/A5008587352][Weitao Zheng]], [[https://openalex.org/A5085400189][Xinyuan He]], [[https://openalex.org/A5074690414][Tongxue Zhang]], [[https://openalex.org/A5019005078][Zhiwei Zhang]], [[https://openalex.org/A5022576893][Qian Liu]], [[https://openalex.org/A5067268817][Xijun Liu]], [[https://openalex.org/A5033775732][Xubin Zhang]], No host. None(None)] 2024. https://doi.org/10.2139/ssrn.4733793 
     
No abstract    

    

* Transpassive Metal Dissolution vs. Oxygen Evolution Reaction: Implication for Alloy Stability and Electrocatalysis  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4391921021
:TOPICS: Atom Probe Tomography Research
:PUBLICATION_DATE: 2024-02-18
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1002/anie.202317058")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4391921021"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4391921021"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4391921021"))][Get cited by]]

OpenAlex: https://openalex.org/W4391921021 (Open access: False)
    
[[https://openalex.org/A5076601076][Annica Wetzel]], [[https://openalex.org/A5093888344][Daniel Morell]], [[https://openalex.org/A5017993519][Marcus von der Au]], [[https://openalex.org/A5038064548][Günther Wittstock]], [[https://openalex.org/A5072476528][Özlem Özcan]], [[https://openalex.org/A5044822731][Julia Witt]], Angewandte Chemie International Edition. None(None)] 2024. https://doi.org/10.1002/anie.202317058 
     
Multi‐principal element alloys (MPEAs) are gaining interest in corrosion and electrocatalysis research due to their electrochemical stability across a broad pH range and the design flexibility they offer. Using the equimolar CrCoNi alloy, we observe significant metal dissolution in a corrosive electrolyte (0.1 M NaCl, pH 2) concurrently with the oxygen evolution reaction (OER) in the transpassive region despite the absence of hysteresis in polarization curves or other obvious corrosion indicators. We present a characterization scheme to delineate the contribution of OER and alloy dissolution, using scanning electrochemical microscopy (SECM) for OER‐onset detection, and quantitative chemical analysis with inductively coupled‐mass spectrometry (ICP‐MS) and ultraviolet visible light (UV‐Vis) spectroscopy to elucidate metal dissolution processes. In‐situ electrochemical atomic force microscopy (EC‐AFM) revealed that the transpassive metal dissolution on CrCoNi is dominated by intergranular corrosion. These results have significant implications for the stability of MPEAs in corrosion systems, emphasizing the necessity of analytically determining metal ions released from MPEA electrodes into the electrolyte when evaluating Faradaic efficiencies of OER catalysts. The release of transition metal ions not only reduces the Faradaic efficiency of electrolyzers but may also cause poisoning and degradation of membranes in electrochemical reactors.    

    

* Controlled fabrication of various nanostructures iron-based tellurides as highly performed oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4392010419
:TOPICS: Electrocatalysis for Energy Conversion, Electrochemical Detection of Heavy Metal Ions, Catalytic Nanomaterials
:PUBLICATION_DATE: 2024-03-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.ijhydene.2024.02.051")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392010419"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392010419"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392010419"))][Get cited by]]

OpenAlex: https://openalex.org/W4392010419 (Open access: False)
    
[[https://openalex.org/A5086085281][Munirah D. Albaqami]], [[https://openalex.org/A5038180168][Mehar Un Nisa]], [[https://openalex.org/A5049370676][Sumaira Manzoor]], [[https://openalex.org/A5051155813][Jafar Hussain Shah]], [[https://openalex.org/A5062023379][S. Noor Mohammad]], [[https://openalex.org/A5090663793][Şenay Yalçın]], [[https://openalex.org/A5052155429][Abdul Ghafoor Abid]], [[https://openalex.org/A5049328863][Suleyman I. Allakhverdiev]], International Journal of Hydrogen Energy. 60(None)] 2024. https://doi.org/10.1016/j.ijhydene.2024.02.051 
     
Electrochemical water splitting is a process that shows promise for the sustainable conversion, storage, and delivery of hydrogen energy. The support development of electrocatalysts that support hydrogen and oxygen evolution processes (HER/OER) without requiring precious metals and with superior activity and durability is crucial for the broad adoption of water electrolysis. Compared to the traditional powder-coated type, a freestanding electrode architecture exhibits superior stability and kinetics. In this study, the layered FeTe-PANI nanocomposite is designed for hydrogen generation. Various nanostructures of FeTe-PANI like nanorods and nanosheets by controllable expansion of surfactants such as hexadecyl trimethyl ammonium bromide (CTAB) can be adjusted to agglomerations. The nanosheets combined with nanorods (FeTe-PANI) show remarkable electrocatalytic activity with 195 mV overpotentials at 10 mAcm−2 for OER. Additionally, FeTe-PANI employed in a 2-electrode electrolyzer as a cathodic electrode electrocatalyst in 1.0 Molar potassium hydroxide media, yields a cell voltage of 1.52 V at a current density of 10 mAcm−2 with a noteworthy 80 h sturdiness, making it an ideal electrocatalyst towards empirical deployment of water splitting electrolyzers.    

    

* Constructions of hierarchical nitrogen doped carbon nanotubes anchored on CoFe2O4 nanoflakes for efficient hydrogen evolution, oxygen evolution and oxygen reduction reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4392077017
:TOPICS: Electrocatalysis for Energy Conversion, Aqueous Zinc-Ion Battery Technology, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-04-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jpowsour.2024.234218")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392077017"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392077017"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392077017"))][Get cited by]]

OpenAlex: https://openalex.org/W4392077017 (Open access: False)
    
[[https://openalex.org/A5027131833][JiaJun Lai]], [[https://openalex.org/A5026918847][Zeng Chen]], [[https://openalex.org/A5088166213][Song Peng]], [[https://openalex.org/A5040296357][Qin Zhou]], [[https://openalex.org/A5062815625][Zeng Ju]], [[https://openalex.org/A5038072194][Chao Liu]], [[https://openalex.org/A5045410326][Xiaopeng Qi]], Journal of Power Sources. 599(None)] 2024. https://doi.org/10.1016/j.jpowsour.2024.234218 
     
The three primary reactions in metal-air batteries and electrochemical hydrolysis are the hydrogen evolution reaction (HER), the oxygen evolution reaction (OER), and the oxygen reduction reaction (ORR). Therefore, it is crucial to develop efficient low-cost trifunctional catalysts. In this study, we design a self-supported electrocatalyst with hierarchical nanostructure, in which the bamboo-like nitrogen doped carbon nanotubes (NCNTs) encapsulated CoFe nanoparticles (CoFe NPs) in-situ anchored on nanoflower like CoFe2O4 via chemical vapor deposition. Strikingly, the resulting catalysts CoFe@NC/CoFe2O4/IF demonstrate exciting trifunctional catalytic performance, overpotential of 66 mV and 185 mV for HER and OER at current densities of 10 mA cm−2, and a half-wave potential of 0.852 V for ORR, respectively. In addition, the maximum power density of the Zinc-air batteries (ZABs) assembled with CoFe@NC/CoFe2O4/IF as the cathode electrode is 134.5 mW cm−2; and the overall water splitting requires only a voltage of 1.50 V at a decomposition current density at 10 mA cm−2. This method provides a new strategy for trifunctional electrocatalysts and offers a promising approach for self-driven water electrolysis devices.    

    

* Silver zirconate: A versatile visible light harvesting photocatalyst for oxygen evolution, PMS activation, and bactericidal activity  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4392005660
:TOPICS: Photocatalytic Materials for Solar Energy Conversion, Nanomaterials with Enzyme-Like Characteristics, Photocatalysis and Solar Energy Conversion
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.jphotochem.2024.115537")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392005660"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392005660"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392005660"))][Get cited by]]

OpenAlex: https://openalex.org/W4392005660 (Open access: False)
    
[[https://openalex.org/A5081656746][Rudra Pratap Singh]], [[https://openalex.org/A5093972281][Mrunal M. Shiwankar]], [[https://openalex.org/A5086570143][Amit Kumar Maurya]], [[https://openalex.org/A5092127017][Awanti S. Talmale]], [[https://openalex.org/A5006205634][G.S. Gaikwad]], [[https://openalex.org/A5063299328][Atul V. Wankhade]], Journal of Photochemistry and Photobiology A: Chemistry. None(None)] 2024. https://doi.org/10.1016/j.jphotochem.2024.115537 
     
Herein, we have synthesized silver zirconate using a co-precipitation method at room temperature. The synthesized Ag2ZrO3 (SZ) was then subjected to calcination at different temperatures (300 °C, 500 °C, and 700 °C). The synthesized Ag2ZrO3 material was evaluated for its photocatalytic oxygen evolution, activation of peroxymonosulfate (PMS) ions, and antibacterial activity under visible light irradiation. Among the different samples, the SZ sample (Ag2ZrO3 synthesized at room temperature) exhibited the highest photocatalytic oxygen evolution rate (2175.02 μmolg-1h−1). This enhanced performance can be attributed to the higher surface area of SZ compared to the other samples. Furthermore, all four samples were tested for the photoactivation of peroxymonosulfate (PMS) ions to assess their ability for the decontamination of organic pollutant. The SZ photocatalyst demonstrated complete degradation (100 %) of RhB dye (2.1 × 10-5 M) within 120 min of visible light irradiation in the presence of PMS. In contrast, without PMS, only 54.33 % degradation of RhB was recorded in 300 min. This result indicates that SZ effectively activates PMS ions for the degradation of organic pollutants. Additionally, SZ exhibited excellent bactericidal activity against E. coli and S. aureus bacteria, both in the dark and in the presence of visible light. The findings demonstrate the multifunctional properties of Ag2ZrO3, making it suitable for a wide range of environmental remediation applications.    

    

* Sulfate anchored on the defective NiO by ion irradiation realizes enhanced oxygen evolution reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4392005855
:TOPICS: Electrocatalysis for Energy Conversion, Memristive Devices for Neuromorphic Computing, Electrochemical Detection of Heavy Metal Ions
:PUBLICATION_DATE: 2024-02-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.cej.2024.149890")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392005855"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392005855"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392005855"))][Get cited by]]

OpenAlex: https://openalex.org/W4392005855 (Open access: False)
    
[[https://openalex.org/A5005285333][Derun Li]], [[https://openalex.org/A5091812681][Wenfeng Guo]], [[https://openalex.org/A5043006241][Zhuo Xing]], [[https://openalex.org/A5080382748][Tao Jiang]], [[https://openalex.org/A5076699693][Zhaowu Wang]], [[https://openalex.org/A5020636129][Shanshan Wu]], [[https://openalex.org/A5091854956][Liuqing Huang]], [[https://openalex.org/A5017470521][Yichao Liu]], [[https://openalex.org/A5044845618][Hengyi Wu]], [[https://openalex.org/A5028412020][Changzhong Jiang]], [[https://openalex.org/A5085724915][Feng Ren]], Chemical Engineering Journal. None(None)] 2024. https://doi.org/10.1016/j.cej.2024.149890 
     
NiO has attracted wide attention in the past decade as a cost-effective electrochemical catalyst for OER. However, its relatively poor performance and conductivity limit its commercial applications. Here, we highlight a unique ion irradiation method to enhance the catalytic activity of NiO. Benefiting from sulfate anchoring and the introduction of oxygen vacancies by He+ ion irradiation, the optimal catalyst (ir-S-NiO) exhibits an outstanding OER performance with a low overpotential of 269 mV at 10 mA cm−2. Moreover, the fabricated Anion exchange membrane water electrolyzer (AEMWE) constructed by the ir-S-NiO is demonstrated to need a cell voltage of 1.72 V to reach a current density of 0.1 A cm−2 and shows remarkably long-term stability for 200 h without obvious attenuation at the current density of 0.5 A cm−2. This work provides a new method for the development of high-performance and stable OER electrocatalysts.    

    

* Regulating the Spin Polarization of NiFe Layered Double Hydroxide for the Enhanced Oxygen Evolution Reaction  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4392018831
:TOPICS: Electrocatalysis for Energy Conversion, Catalytic Nanomaterials, Materials for Electrochemical Supercapacitors
:PUBLICATION_DATE: 2024-02-21
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1021/acscatal.3c06180")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392018831"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392018831"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392018831"))][Get cited by]]

OpenAlex: https://openalex.org/W4392018831 (Open access: False)
    
[[https://openalex.org/A5017834536][Wenwu Cao]], [[https://openalex.org/A5068375738][Xianhui Gao]], [[https://openalex.org/A5038747062][Jie Wu]], [[https://openalex.org/A5056746694][Anqi Huang]], [[https://openalex.org/A5015273050][Huan Hu]], [[https://openalex.org/A5091083063][Zhongwei Chen]], ACS Catalysis. None(None)] 2024. https://doi.org/10.1021/acscatal.3c06180 
     
No abstract    

    

* Boosting activity on molten salt-synthesized Ce doped cobalt hydroxyl nitrate nanorods by oxygen vacancies for efficient oxygen evolution  :water_splitting:
:PROPERTIES:
:ID: https://openalex.org/W4392074898
:TOPICS: Formation and Properties of Nanocrystals and Nanostructures, Electrochemical Detection of Heavy Metal Ions, Memristive Devices for Neuromorphic Computing
:PUBLICATION_DATE: 2024-06-01
:END:    
    
[[elisp:(doi-add-bibtex-entry "https://doi.org/10.1016/j.fuel.2024.131214")][Get bibtex entry]] 

- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--referenced-works "https://openalex.org/W4392074898"))][Get references]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--related-works "https://openalex.org/W4392074898"))][Get related work]]
- [[elisp:(progn (xref--push-markers (current-buffer) (point)) (oa--cited-by-works "https://openalex.org/W4392074898"))][Get cited by]]

OpenAlex: https://openalex.org/W4392074898 (Open access: False)
    
[[https://openalex.org/A5039804899][Na Xu]], [[https://openalex.org/A5061173596][Ning Yu]], [[https://openalex.org/A5068775213][Zhaoxia Jin]], [[https://openalex.org/A5005475250][Yanan Zhou]], [[https://openalex.org/A5050840588][Yusheng Zhang]], [[https://openalex.org/A5058907569][Jin-Long Tan]], [[https://openalex.org/A5075675634][Yulu Zhou]], [[https://openalex.org/A5062331341][Yong‐Ming Chai]], [[https://openalex.org/A5072072030][Bin Dong]], Fuel. 365(None)] 2024. https://doi.org/10.1016/j.fuel.2024.131214 
     
Rationalizing the development of highly active, non-precious electrocatalysts through facile and cost-effective synthesis methods for the oxygen evolution reaction (OER) constitutes a paramount research objective. In this study, we introduce an innovative molten salt approach to fabricate an arrayed nanorod architecture supported on a cobalt foam substrate denoted as Ce doped cobalt hydroxyl nitrate (Ce-CoNH). Cerium (Ce) is strategically employed to induce oxygen vacancies and effect localized electronic structure modifications of the cobalt (Co) sites. In comparison to individual CoNH catalysts, Ce-CoNH exhibits exceptional catalytic activity in alkaline water oxidation, achieving a notably low overpotential of 270 mV at a current density of 50 mA cm−2. Notably, the Ce-CoNH catalyst also demonstrates remarkable durability, sustaining a current density of 100 mA cm−2 for an impressive duration of 50 h, surpassing the performance of Ce-free CoNH samples, which can be attributed to the flexible influence of Ce doping and the robust nanorod structure. Collectively, our study underscores the viability of molten salt-synthesized heteroatom substitution, accompanied by the introduction of defect-rich structures, as an effective strategy for the rational design of advanced electrocatalysts tailored for water electrolysis applications.    

    
