#on: push
# at the beginning of every hour: '0 * * * *'
# every day at 8am: '0 8 * * *'
# On sunday: '0 0 * * SUN'
on:
  workflow_dispatch:
  schedule:
#    - cron: '59 23 * * SUN' # weekly sunday night
    - cron: '59 23 * * *'  # daily at 11:59pm
#    - cron: '0 * * * *'
      
jobs:

  openalex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -e src
        
      - shell: bash
        
        env:
          OPENALEX_API_KEY: ${{ secrets.OPENALEX_API_KEY }}
          ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}		
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
            source .venv/bin/activate
            lazotero -f catalysis.yml -s 1
            oa-discord -f catalysis.yml -s 1
            litalerts -s 1 -f catalysis.yml
          
          

        
