on:
  schedule:
    - cron: '30 21 * * 0'
      
jobs:

  openalex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install dependencies
        run: pip install requests
        
      - shell: bash
        
        env:
          OPENALEX_API_KEY: ${{ secrets.OPENALEX_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            python script.py            
            git config --global user.email "jkitchin@andrew.cmu.edu"
            git config --global user.name "John Kitchin"            
            git add results.org
            git commit results.org -m "adding new results to results.org"
            git push
            gh issue create --label "new references" --assignee jkitchin --title "New references found" --body "New references to look at. See [results.org](../blob/main/results.org)."
          
          

        
