on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step was run at `date`"


  build_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create a file
        run: |
          date >> results.dat
          git config --global user.email "jkitchin@andrew.cmu.edu"
          git config --global user.name "John Kitchin"
          git add results.dat
          git commit results.dat -m "adding to results.dat"
          git push

  openalex:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install requests
        
      - name: Use API key
        env:
          OPENALEX_API_KEY: ${{ secrets.OPENALEX_API_KEY }}
        run: |            
            python script.py
            git add results.org
            git commit results.org -m "adding new results to results.dat"
            git push

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
          

        
