on: push
#  schedule:
#    - cron: '*/15 * * * *'
      
jobs:

  openalex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install dependencies
        run: pip install requests rfeed lxml dotenv
        
      - shell: bash
        
        env:
          OPENALEX_API_KEY: ${{ secrets.OPENALEX_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            python script.py            
            git config --global user.email "jkitchin@andrew.cmu.edu"
            git config --global user.name "John Kitchin"            
            git add results.org            
            git add rss.xml
            git commit results.org rss.xml -m "adding new results"            
            git push
            gh issue create --label "new references" --assignee jkitchin --title "New references found" --body "New references to look at. See [results.org](../blob/main/results.org)."
          
          

        
