#on: push
# at the beginning of every hour: '0 * * * *'
# every day at 8am: '0 8 * * *'
# On sunday: '0 0 * * SUN'
on:
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'
      
jobs:

  openalex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install dependencies
        run: pip install requests rfeed lxml python-dotenv
        
      - shell: bash
        
        env:
          OPENALEX_API_KEY: ${{ secrets.OPENALEX_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            python script.py            
            git config --global user.email "jkitchin@andrew.cmu.edu"
            git config --global user.name "John Kitchin"            
            git add rss results
            git commit rss results -m "adding new results"            
            git push
            if [ -f MAKEISSUE ]; then
                gh issue create --label "new references" --assignee jkitchin --title "New references found: `date`" --body "New references to look at. See [results](../blob/main/results)."
            fi
          
          

        
